### ISSUE TITLE
Different ordering of fields in form and index

### ISSUE THREAD

**Issue by alexjose** [laravel/nova-issues#100]
The ordering of the fields based on the view might a cool thing.

For example State and District resource scenario, I would like to show the State drop-down first in the Create District form, but in the district listing or details page, I would like to show the state only after the district name.

**Comment by danrichards** [comment]
Yes, this can be accomplished by duplicating your field in the resource and being creative with how you hide / show it in particular sections.

**Comment by alexjose** [comment]
That would be a wild hack. Nice find @danrichards. Does this add any overhead as the same field is defined multiple times just for this purpose? Something out of the box might be helpful in future.

**Comment by danrichards** [comment]
It feels a little weird, but I think overall, the way they arranged everything in one method to control fields for a variety of views with hide / show helper methods means writing less code.

If you wanted to be really explicit, I suppose you code do something like:

```
 public function fields(Request $request)
{
    return array_merge(
        $this->indexFields(),
        $this->displayFields(),
        $this->formFields(),
    );
```

Then use `onlys` everywhere in your helpers.

**Comment by sfinktah** [comment]
Well, this seems to have magically appeared in Nova 4.0 as `fieldsForIndex`, `fieldsForDetails`, `fieldsForUpdate`, etc.   Thanks for the credit.

https://nova.laravel.com/docs/4.0/resources/fields.html#dynamic-field-methods
