### ISSUE TITLE
How to add Bootstrap to my Tool?

### ISSUE THREAD

**Issue by DianaR19** [laravel/nova-issues#1000]
I would like to add some components and designs offered by Bootstrap, such as modals, buttons and alerts.

as some examples here https://bootstrap-vue.js.org/docs/components/modal/

But it only shows me the following

![image](https://user-images.githubusercontent.com/35699310/48809639-062ecc00-eceb-11e8-8952-4e57921659cd.png)

**Comment by davidhemphill** [comment]
Nova uses Tailwind CSS as its visual framework and Vue.js for components. Introducing Bootstrap will overwrite Tailwind's CSS and create a situation like the above.

Also, this issue board is for tracking bugs. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).
