### ISSUE TITLE
dump() in Model won't render Create view

### ISSUE THREAD

**Issue by 949mac** [laravel/nova-issues#1002]
- Laravel Version: 5.7
- Nova Version: 1.7
- PHP Version: 7.2

### Description:

**App\Order**
```
class Order extends Model
{
    public function line_items()
    {
        return $this->hasMany(LineItem::class);
    }

    public function count_line_items()
    {
        dump($this->line_items()->get());
        
        return $this->line_items()->count();
    }
}
```

**App\Nova\Order**
```
    public function fields(Request $request)
    {
        return [
            Text::make('Total', function () {
                return $this->total();
            }),
        ];
    }
```

**JavaScript Console + Front-end frozen**
![image](https://user-images.githubusercontent.com/23151962/48818744-6e88a800-ed01-11e8-9285-db4ed29ac584.png)

### Steps To Reproduce:

1. Setup your model like mine
2. Setup your Nova controller like mine
3. Buckle your seat belt and observe your CPU fan spinning faster than a jet turbine 
4. Remove dump statement and see the issue resolves itself

**Comment by davidhemphill** [comment]
Using `dump` like that will generate an invalid response which is why you see the error.

**Comment by lichtner** [comment]
@davidhemphill so how can I dump some value in nova?

**Comment by davidhemphill** [comment]
Depends on the type of error. Most exceptions will bubble up to the front-end error toast messages. You can also log things to the console. There is also the ability to write a test to debug (for custom packages, for example). The built-in log should also have any Exception output as well. You can also inspect what's going on by using something like Laravel Debugbar or Laravel Telescope.
