### ISSUE TITLE
BelongsToMany edit not work and no needed

### ISSUE THREAD

**Issue by approached** [laravel/nova-issues#1003]
- Laravel Version: 5.6.39
- Nova Version: 1.1.7
- PHP Version: 7.1

### Description:

I have BelongsToMany connection. If click on edit i can't edit it. This problem i have on all models.
I have no extra fields, so me don't need the edit function. Is that possible to disable?

```php
BelongsToMany::make('Products that use this attribute', 'products', \App\Nova\Product\Product::class),
```

### Steps To Reproduce:
1.
![screen shot 2018-11-21 at 13 03 30](https://user-images.githubusercontent.com/3439330/48840249-5e6ada00-ed8e-11e8-97a4-8e500a5839c4.png)
2.
![screen shot 2018-11-21 at 13 03 42](https://user-images.githubusercontent.com/3439330/48840265-69256f00-ed8e-11e8-9722-19038e0f4a4b.png)

**Comment by dillingham** [comment]
This is not a bug. Don’t ignore the instructions to ask questions in their proper channels.

**Comment by approached** [comment]
I'm just follow the documentation: https://nova.laravel.com/docs/1.0/resources/authorization.html#policies

Just attach and detach is possible to control.

**Comment by carloshc** [comment]
It's make senses. It's not necessary to edit a BelongsToMany relation.

**Comment by cristafortuno** [comment]
Running on a similar issue. 

I would like to hide the Edit button (and probably the View button as well) so as to leave just the Attach and Detach functionality. 

Is there a way to do this?

**Comment by 93gaurav93** [comment]
@taylorotwell I also want to hide the **Attach** button. Do we have any solution?

**Comment by jeffcaulfield-morphsites** [comment]
I struggled with a similar issue for some time. It wasn't at all obvious from the Nova documentation how to hide the "edit" button for simple pivot relationships where it isn't needed or wanted, though the solution makes sense in hindsight.

Let's assume you have an `Attribute` resource and a `Product` resource and that each manages a model of the same name. Further, let's assume that there is a `belongsToMany(Product::class)` relationship called `products` on the `Attribute` model and the `Attribute` resource has a corresponding `BelongsToMany::make('Products')` field.

First, you need to create an `AttributePolicy` class that defines what the user is [authorised](https://nova.laravel.com/docs/2.0/resources/authorization.html) to do with this resource. You'll probably want to add policies for `view`, `create`, `update` and so forth. However, you should **also** define the following.

* `attachAnyProduct`—This determines whether the "Attach Product" button appears at the top of the list of products.
* `attachProduct`—See blow.
* `detachProduct`—This determines whether the "Detach" (rubbish bin) button is available for a particular product in the list.

You'll either want to hard-code `attachAnyProduct` and `detachProduct` to return `true` or implement a permissions model of some kind, but whatever the case, the key to getting rid of the unwanted "edit" button is down to how you write the `attachProduct` policy.

```php
public function attachProduct(User $user, Attribute $attribute, Product $product)
{
    if ($attribute->products->contains('id', $product->id)) {
        return false;
    } else {
        return $this->attachAnyProduct($user, $attribute);
    }
}
```

This checks to see if the relationship already exists between the current attribute and a given product; if it does, then you're not allowed to "attach" it again. This removes the unwanted "edit" button and **also** removes that particular product from the drop-down list when creating a new relationship (via "Attach Product").

Of course, if you also have the `attributes` relationship/field on the `Product` model/resource then you'll want to define the corresponding `attachAnyAttribute`, `attachAttribute` and `detachAttribute` policies in a `ProductPolicy` class as well.

Hopefully others will find this explanation useful.

PS> I'm using Nova 2.0.5, which I believe is the latest version.

**Comment by daniel-de-wit** [comment]
Thanks for clarifying @jeffcaulfield-morphsites, works great.

The default behaviour for `attachAnyProduct` is to return `true`.
So, it's possible to skip adding it yourself and use a somewhat simplified version of what you suggested.

```php
public function attachProduct(User $user, Attribute $attribute, Product $product)
{
    return ! $attribute->products->contains($product);
}
```

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!

**Comment by YarinceP** [comment]
> I struggled with a similar issue for some time. It wasn't at all obvious from the Nova documentation how to hide the "edit" button for simple pivot relationships where it isn't needed or wanted, though the solution makes sense in hindsight.
> 
> Let's assume you have an `Attribute` resource and a `Product` resource and that each manages a model of the same name. Further, let's assume that there is a `belongsToMany(Product::class)` relationship called `products` on the `Attribute` model and the `Attribute` resource has a corresponding `BelongsToMany::make('Products')` field.
> 
> First, you need to create an `AttributePolicy` class that defines what the user is [authorised](https://nova.laravel.com/docs/2.0/resources/authorization.html) to do with this resource. You'll probably want to add policies for `view`, `create`, `update` and so forth. However, you should **also** define the following.
> 
> * `attachAnyProduct`—This determines whether the "Attach Product" button appears at the top of the list of products.
> * `attachProduct`—See blow.
> * `detachProduct`—This determines whether the "Detach" (rubbish bin) button is available for a particular product in the list.
> 
> You'll either want to hard-code `attachAnyProduct` and `detachProduct` to return `true` or implement a permissions model of some kind, but whatever the case, the key to getting rid of the unwanted "edit" button is down to how you write the `attachProduct` policy.
> 
> ```
> public function attachProduct(User $user, Attribute $attribute, Product $product)
> {
>     if ($attribute->products->contains('id', $product->id)) {
>         return false;
>     } else {
>         return $this->attachAnyProduct($user, $attribute);
>     }
> }
> ```
> 
> This checks to see if the relationship already exists between the current attribute and a given product; if it does, then you're not allowed to "attach" it again. This removes the unwanted "edit" button and **also** removes that particular product from the drop-down list when creating a new relationship (via "Attach Product").
> 
> Of course, if you also have the `attributes` relationship/field on the `Product` model/resource then you'll want to define the corresponding `attachAnyAttribute`, `attachAttribute` and `detachAttribute` policies in a `ProductPolicy` class as well.
> 
> Hopefully others will find this explanation useful.
> 
> PS> I'm using Nova 2.0.5, which I believe is the latest version.

Thats so nice 💯  but i have a question.
How can I remove(or hide) Show Icon 
of my related resource.
![Question Show button](https://user-images.githubusercontent.com/28911286/74550486-1433c280-4f17-11ea-8c55-9cdc0f91808d.png)

**Comment by YarinceP** [comment]
> Running on a similar issue.
> 
> I would like to hide the Edit button (and probably the View button as well) so as to leave just the Attach and Detach functionalities.
> 
> Is there a way to do this?

Hi @cristafortuno , did you find a way to hide the view button?

**Comment by ThaDaVos** [comment]
Anyone found a way to hide the view button? This stuff is driving me crazy... I would have expected to just add a `viewProduct` function to the policy...

**Comment by foxx9** [comment]
I could not find an easy way either to hide the edit attached button that is useless in my use case.
What I did to only hide the "Edit attached" buttons and not the "Edit" buttons was to use that CSS : 

```css

[dusk*="-edit-attached-button"] {
    display: none;
}
```

**Comment by cristafortuno** [comment]
@YarinceP I think I wasn't able to remove it. Realized just now that maybe the Edit button is meant for editing any available pivot fields.

**Comment by bkuhl** [comment]
Problem still exists in Nova 4.
