### ISSUE TITLE
Update & Continue Editing throws error if attempted more than once

### ISSUE THREAD

**Issue by mpenna** [laravel/nova-issues#1004]
- Laravel Version: 5.6.39
- Nova Version: 1.1.7
- PHP Version: PHP 7.2.9-1+ubuntu18.04.1+deb.sury.org+1

### Description:
When attempting the "Update & Continue Editing" action a second time around (and for all subsequent attempts), the following error message is shown: "Another user has updated this resource since this page was loaded. Please refresh the page and try again.". As a sidenote, I'm the sole user interacting with the app.

### Steps To Reproduce:
Pick any resource, open its Edit view and then try the update & continue editing action more than once.  Regardless if any fields have been altered or not, the aforementioned error is thrown. 

![snag-2018-11-21-12-41-09](https://user-images.githubusercontent.com/6953141/48848918-5ca01700-ed8c-11e8-8ef4-c285ad7cb7c7.png)

**Comment by unlikenesses** [comment]
Possibly related to #838

**Comment by yehudahkay** [comment]
+ 1

**Comment by mislam** [comment]
This is happening when I wait little bit then press update. If I quickly click update within 3-4 seconds, then it updates without any problem. This is a severe issue for us as it significantly slows down our daily business.

**Comment by jbrooksuk** [comment]
I couldn't replicate this in Nova v2.0.9

![image](https://user-images.githubusercontent.com/246103/62199973-60088b00-b37c-11e9-871d-15852f83593d.png)

**Comment by klimov-paul** [comment]
This is a duplicate of #1082

@jbrooksuk, all steps to reproduce the issue are provided at the description of #1808.
To see the actual error you should **manually change times at your clients machine (where browser is launched) to be in the past**.
E.g. in case current time at server is '2019-10-16 10:35:00' - the current time at client will be '2019-10-16 10:30:00'.
This will cause timestamp written on model saving at the server side to be ahead of the timestamp generated by JavaScript at the resource retrival. Thus method `ResourceUpdateController::modelHasBeenUpdatedSinceRetrieval()` will return `false` causing the 409 error.
