### ISSUE TITLE
Resource Model is not respected for relationships

### ISSUE THREAD

**Issue by geodeveloper** [laravel/nova-issues#1005]
- Laravel Version: 5.7.13
- Nova Version: 1.1.7
- PHP Version: 7.1.13

### Description:
The relationship between resources is not respected because of different namespace for Models classes.

### Steps To Reproduce:
User Model (extends parent User)
```php
namespace App;

class User extends \Acme\Models\User
{
```
User Resource
```php
namespace App\Nova;

class User extends Resource
{
    public static $model = 'App\\User';
```
Alert Model (different namespace)
```php
namespace Acme\Models;

use Illuminate\Database\Eloquent\Model;

class Alert extends Model
{ 
    public function user()
    {
        return $this->belongsTo('Acme\\Models\\User');
    }
}
```
Alert Resource
```php
namespace App\Nova;

class Alert extends Resource
{
    public static $model = 'Acme\\Models\\Alert';

    public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
            BelongsTo::make('User')
        ];
    }
```

Now if I load the Alert Resource index page I get the following error:

`Class name must be a valid object or a string`

**Comment by davidhemphill** [comment]
In this case, Nova will look for a resource at `App\Nova\User`. If you want it to use the model `Acme\Models\User` like your field is configured, you need to provide a Resource with that model set as its `$model` property.
