### ISSUE TITLE
How to run `npm run dev` or `npm run prod` on multiple components in one npm script

### ISSUE THREAD

**Issue by wishinghand** [laravel/nova-issues#1006]
What's the best method for recursively running npm scripts on each component in Nova? We're not making our components public, so keeping them silo'd isn't necessary.

**Comment by davidhemphill** [comment]
Create a script in your top-level `package.json` that you can run:

```json
scripts: {
  "build:all": "npm run compile:fields && npm run compile:cards",
  "compile:fields": "cd nova-components/this && npm run prod",
  "compile:cards": "cd nova-components/that && npm run prod",
}
```

Or consider throwing your non-public components in one project-specific one and compile just it.

**Comment by wishinghand** [comment]
Aw dang, I figured there was some command line trickery that could have solved the issue. The former solution could work, it's just a bit manual.

**Comment by mrvnklm** [comment]
I solved it that way:
Add this to `package.json`: `"prod-build":` "./prod-build-nova-components && npm run prod && rm -rf node_modules"`
And this to `prod-build-nova-components` in laravel root folder:
`#!/bin/sh
for dir in "nova-components/"*
do
    printf "Building $dir for production\n" &&
    cd "$dir" &&
    npm i &&
    npm run prod &&
    rm -rf node_modules &&
    cd ../..
done
`
