### ISSUE TITLE
After upgrading to version 1.1.8 got sql errors

### ISSUE THREAD

**Issue by RespectPick** [laravel/nova-issues#1008]
- Laravel Version: 5.7.13
- Nova Version: 1.1.8
- PHP Version:7.2

When I open the resource index page I got some mysql errors such as

Invalid input syntax for integer
screen - http://joxi.ru/12MWJXLsl41blr

Before the update, this was not. I noticed that this only happens on pages with my custom filters which are created by 

> php artisan nova:filter

I use PostgreSQL 10.5

**Comment by RespectPick** [comment]
If I remove the filters

**before** 
```
    public function filters(Request $request)
    {
        return [
            new Filters\BidTeamOnSeason\Team,
            new Filters\BidTeamOnSeason\Season,
        ];
    }
```
**after**

```
    public function filters(Request $request)
    {
        return [

        ];
    }
```

the exception is not thrown.

**Comment by davidhemphill** [comment]
Please post the code to a filter that causes the error.
