### ISSUE TITLE
Resource index empty when resource has any filters registered (1.1.8)

### ISSUE THREAD

**Issue by pix2D** [laravel/nova-issues#1009]
- Laravel Version: 5.7.14
- Nova Version: 1.1.8
- PHP Version: 7.2

### Description:

When viewing a resource index the content flashes in briefly, and then is removed and a empty table remains with `No {resource} matched the given criteria.`.

This only happens if there are filters added to the resource. Without filters everything shows correctly.

Looking at the network it seems that there are 2 requests done simultaneously. One of the requests is fine, and returns the correct data. The other request returns no data. If I reload the resource page multiple times it will on occasion happen that the data shows because presumably the correct request finished "last".

There are no console errors or anything in laravel.log.

### Steps To Reproduce:

1. Make a resource
2. Make a filter
3. Add filter to the resource
4. Go to the resource page

**Comment by pix2D** [comment]
And to clarify, this only happens on 1.1.8. On 1.1.7 everything works fine. No other changes were made in between.

**Comment by dwyer14** [comment]
I'm not having this issue w/ a filterable index...did you `nova:publish` after updating? Not sure if that would make a difference, but kinda the only thing I can think of.

**Comment by pix2D** [comment]
Yes I ran publish. I also tried removing all fields, actions etc and just having the ID show and it still happens. Not sure what else to try at this point.

**Comment by mixartemev** [comment]
I'm interested too, why it made so in 1.1.8? It's uncomfortable! And now I need to rewrite hundreds of filters. Maybe it's bug?

**Comment by mixartemev** [comment]
In addition, now xhr requests are repeats duplicates.

For example in 1.1.7 request `http://127.0.0.1:8000/nova/resources/users` generates such xhr requests:
<img width="608" alt="2018-11-23 20 56 01" src="https://user-images.githubusercontent.com/5181924/48956141-4fd51c00-ef62-11e8-8c24-c8727e0677c0.png">

And the same request in 1.1.8:
<img width="635" alt="2018-11-23 20 59 59" src="https://user-images.githubusercontent.com/5181924/48956201-c540ec80-ef62-11e8-8c01-0ef265108364.png">

**Comment by StanBarrows** [comment]
Same Problem here ;)

**Comment by jkudish** [comment]
Same here too 👎

**Comment by dillingham** [comment]
So bug fixes are now creating bugs? I will be extra careful not to even update minor versions

**Comment by davidhemphill** [comment]
This was fixed in the latest version.
