### ISSUE TITLE
Login page load css function

### ISSUE THREAD

**Issue by jcc** [laravel/nova-issues#101]
I think `mix` function should replace `asset` function.
When I set up ssl on my site, the login page can't load the css.

In `nova/resources/views/auth/layout.blade.php` line 14.

```php
-    <link rel="stylesheet" href="{{ asset('/nova-assets/app.css') }}">
+    <link rel="stylesheet" href="{{ mix('app.css', 'nova-assets') }}">
```

**Comment by davidhemphill** [comment]
This has been fixed and will be included in an upcoming release.
