### ISSUE TITLE
Updating model with a file now broken in 1.1.8

### ISSUE THREAD

**Issue by laurencei** [laravel/nova-issues#1010]
- Laravel Version: 5.7.18
- Nova Version: 1.1.8
- PHP Version: 7.2

When updating a model that "requires" an image, and the model **already** has a saved photo attached, the system returns "the picture field is required" even though there is already a picture saved on the model.

You are forced to re-upload the file every time you want to edit the model, which is incorrect (because there is already a photo saved on the model).

This is a change in behaviour from 1.1.7->1.1.8

![image](https://user-images.githubusercontent.com/1210658/48898672-77b07b00-eea1-11e8-91dd-f6df29c8428c.png)

**Comment by bonzai** [comment]
I can't confirm using the following validation rules:

```php
public function fields(Request $request)
{
    return [
        ID::make()->sortable(),

        Image::make('Profile Photo')
            ->disk('public')
            ->creationRules('required')
            ->updateRules('sometimes', 'required'),
    ];
}
```

**Comment by laurencei** [comment]
That's not the rule I have. The rule I have is 

        Image::make('Profile Photo')
            ->disk('public')
            ->rules('required');

This worked in 1.1.7 and has stopped in 1.1.8.

**Comment by davidhemphill** [comment]
I don't believe anything changed regarding Image fields between those versions.

**Comment by davidhemphill** [comment]
You would need to have `sometimes` in your rule set or the `required` rule would apply for both create and update actions.

**Comment by laurencei** [comment]
@davidhemphill - I'm happy to do that, it does make sense.
