### ISSUE TITLE
Button escaping changed in 1.1.8

### ISSUE THREAD

**Issue by laurencei** [laravel/nova-issues#1011]
- Laravel Version: 5.7
- Nova Version: 1.1.8
- PHP Version: 7.2

### Description:
The `&` is escaped in 1.1.8 on the buttons as `&amp;`

### Steps To Reproduce:
I only noticed this after I republished the 1.1.8 assets after upgrading and doing `view:clear` etc. If you dont re-publish and use the 1.1.7 assets the error doesnt show up.

![image](https://user-images.githubusercontent.com/1210658/48898590-39b35700-eea1-11e8-99c1-e9c7b6c58134.png)

**Comment by bonzai** [comment]
#750 was fixed in 1.1.8.

**Comment by laurencei** [comment]
@bonzai - are you saying that fix is the likely cause of this new issue?

**Comment by bonzai** [comment]
Did you update the translations (`resources/lang/vendor/nova`) after the upgrade?

```
php artisan nova:publish --force
```

**Comment by laurencei** [comment]
Yes

**Comment by laurencei** [comment]
Changing

`\resources\lang\vendor\nova\en.json` with

```diff
- "Update & Continue Editing": "Update &amp; Continue **Editing",**
+ "Update & Continue Editing": "Update & Continue Editing",
```

fixes the issue.

But we shouldnt have to do that manually for all buttons? Seems like a bug to me...

**Comment by bonzai** [comment]
You're right. This is a bug.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍

**Comment by laurencei** [comment]
Thanks

**Comment by asheaheartcup** [comment]
This is still happening in 1.2.0
