### ISSUE TITLE
Menu items and dashboard cards are duplicated each page reload. If using swoole.

### ISSUE THREAD

**Issue by fsotomsk** [laravel/nova-issues#1013]
- Laravel Version: 5.7.14
- Nova Version: 1.1.7
- PHP Version: 7.2.10

### Description:
Menu items and dashboard cards are duplicated each page reload.
![image](https://user-images.githubusercontent.com/7643673/48902341-592e8d80-ee69-11e8-9a98-31e232c6a433.png)

### Steps To Reproduce:
1. Install swoole php-extension and package `swooletw/laravel-swoole (2.5.0)`.
2. Run laravel `php artisan swoole:http start`.
3. Go to Nova dashboard and reload page

**Comment by davidhemphill** [comment]
I don't think there's a problem with Nova here in particular. Seems to work fine on conventional PHP servers.

**Comment by fsotomsk** [comment]
if RoadRunner is used, there is a issue too

**Comment by juberjj** [comment]
Hi there, 

I'm having the same problem here but not really sure what to do, any help is very much appreciated.

Thanks in advance.

![image](https://user-images.githubusercontent.com/16324958/61629481-ec2ff980-ac7c-11e9-8fac-53b9bc267733.png)

**Comment by fsotomsk** [comment]
@juberjj 

https://github.com/laravel/nova-issues/issues/1013#issuecomment-441191088

**Comment by juberjj** [comment]
@fsotomsk 

I'll try that and post the results here. Thanks again.

**Comment by juberjj** [comment]
@fsotomsk 

My setup is different and I don't have any references similar to the ones you've posted.

I wonder if within Swoole config file a resetter or registration of a provider would possibly help on this?

Best regards

**Comment by juberjj** [comment]
Hey @fsotomsk 

That was my bad on the interpretation of the solution presented here - path /vendor/laravel/nova/src/Nova.php - after change the file it rendered accordingly. Thanks a lot @fsotomsk, I wonder why they cannot merge your proposed solution.

**Comment by juberjj** [comment]
hey @fsotomsk,

After implementation of the suggested for some weird reason I can see the menu part fixed but the cards are being replicated, any suggestions?

**Comment by fsotomsk** [comment]
@juberjj hm.. show me your code

**Comment by juberjj** [comment]
Hi @fsotomsk  probably some new component or some update introduced by one of our fellows here but it was working just fine on Thursday past and now for the cards no matter what it gets duplicated. We're not calling a specific part of code but just calling components groups, users and so on I'm not sure what part would be relevant for you to see. The Nova.php was edited according to your suggestion.

**Comment by Sunhat** [comment]
If you're using the laravel swoole package, 
https://github.com/swooletw/laravel-swoole
Then publish your config, and add the Laravle Nova Authenticate Middleware to instances to clear.
```

    'instances' => [
        Laravel\Nova\Http\Middleware\Authenticate::class,
    ],

```

Laravel nova pushed data to a static array.
