### ISSUE TITLE
Can 1/3 and 1/2 cards not have a fixed height

### ISSUE THREAD

**Issue by rosswintle** [laravel/nova-issues#1014]
- Laravel Version: 5.6.39
- Nova Version: 1.1.7
- PHP Version: 7.1.8

### Description:

Full-width cards can assume the height of their content. 1/2 and 1/3 width card are fixed at 150px.

### Steps To Reproduce:

Task/Goal: Replace the "Help" card on the Nova dashboard with some introductory/welcome text of my own.

* Create a new card and registered it in `NovaServiceProvider`'s `cards()` method
* In `MyCard/src/MyCard.php` I set `public $width = 'full';`
* Create the card content in `MyCard/resources/js/components/Card.vue`
* Compile with `npm run watch` in the card's directory
* The card is fine, but now you decide you don't want it full-width, you want it narrower, so change `public $width = 'full';` to `public $width = '1/2';` 
* Refresh the dashboard
* Card content now overflows the card

The issue is that the 1/2 and 1/3 width cards have a `card-panel` class applied which is styled with a fixed height of 150px.

If the concern is that cards will look odd if they are different heights then we should use flexbox to fix this.

I see no reason why cards should be a fixed height.

**Comment by dillingham** [comment]
```css
.card-panel {
    height: auto !important;
    min-height: 150px;
}
```

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
