### ISSUE TITLE
Filter affects queries even if empty (v 1.1.8)

### ISSUE THREAD

**Issue by bomshteyn** [laravel/nova-issues#1015]
- Laravel Version: 5.7.14
- Nova Version: 1.1.8
- PHP Version: 7.2

### Description:
Since the 1.1.8 update even if select filter is empty it affects the queries, so if nothing is selected the following query is run

`select * from deals where vendor = ''` etc... 

And hence returns wrong results

**Comment by davidhemphill** [comment]
You need to check if the value is empty in your filter, just like before.

**Comment by dillingham** [comment]
Idk how much more blind faith I have in me

**Comment by davidhemphill** [comment]
So to follow up, I decided to fix the behavior for filters that have a single value like the select and the new date filter. The new boolean filter type will still need to have a check.
