### ISSUE TITLE
Error when creating Resource Tool

### ISSUE THREAD

**Issue by DianaR19** [laravel/nova-issues#1018]
Implement the resource tool example that laravel nova provides with the instructions in the documentation and generates the error

![image](https://user-images.githubusercontent.com/35699310/48956725-3a3c0400-ef1a-11e8-9b26-4f540b81be44.png)

![image](https://user-images.githubusercontent.com/35699310/48956754-63f52b00-ef1a-11e8-802e-47e59241caa0.png)

This is my code 
![image](https://user-images.githubusercontent.com/35699310/48954656-2095bf00-ef10-11e8-9b5a-343d5f0793d8.png)

**Comment by DianaR19** [comment]
I tried the solution of issue #33 and #939  but it did not work

**Comment by davidhemphill** [comment]
I can tell from the error above it's an issue with your template. Try removing the SVG and see if it works.

**Comment by bucksterbuck** [comment]
Correction: Running composer update fixed this, for some reason when it does on via the CLI it doesn't register...
