### ISSUE TITLE
Creating custom resource link?

### ISSUE THREAD

**Issue by huglester** [laravel/nova-issues#1023]
Hello,

it would be nice, so that adding resource links would be possible :
![image](https://user-images.githubusercontent.com/150731/48984617-78961680-f106-11e8-9e60-8f5fb82d2157.png)

So for example, for some resources, we could hide SHOW button. Or add custom one.

**Comment by dillingham** [comment]
The eye icon..

**Comment by uwascan** [comment]
Take a look at this issue for some inspiration [https://github.com/laravel/nova-issues/issues/786](https://github.com/laravel/nova-issues/issues/786)

**Comment by davidhemphill** [comment]
You can hide the show button by using authorization: https://nova.laravel.com/docs/1.0/resources/authorization.html#policies

**Comment by huglester** [comment]
thanks @uwascan I was checking that issue earlier but did not find a sollution
@davidhemphill - well it's about hiding 'show', and what about adding a button?
