### ISSUE TITLE
Can't construct new query in detailQuery() override

### ISSUE THREAD

**Issue by aphofstede** [laravel/nova-issues#1025]
- Laravel Version: 5.6.39
- Nova Version: 1.1.8
- PHP Version: 7.1.18

### Description:
The following `tap()` in nova/src/Http/Controllers/ResourceShowController.php makes it so that we can only _modify_ a query in our resource models, not return a whole new one. 
When overriding `detailQuery()` in my own class, I was expecting the parent to just execute whatever I passed back down, but any new objects are ignored.

```
class ResourceShowController extends Controller
{
    /**
     * Display the resource for administration.
     *
     * @param  \Laravel\Nova\Http\Requests\ResourceDetailRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function handle(ResourceDetailRequest $request)
    {
        $resource = $request->newResourceWith(tap($request->findModelQuery(), function ($query) use ($request) {
            $request->newResource()->detailQuery($request, $query);
        })->firstOrFail());
```

### Steps To Reproduce:
Override `detailQuery()` in your resource model and `return parent::detailQuery($request, $query)` with new request or query objects.
e.g. `return parent::detailQuery($request, new \Illuminate\Database\Eloquent\Builder(\DB::table('users')->...)))`

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
