### ISSUE TITLE
Can't Render Resources

### ISSUE THREAD

**Issue by Hemus** [laravel/nova-issues#1027]
When I open the Dashboard of my Nova app I don't encounter any errors, but when I attempt to open a resource I get the following errors:

<img width="1278" alt="nova_resource_error" src="https://user-images.githubusercontent.com/5630773/49008086-e83aee80-f164-11e8-8140-5757d56a959c.png">

Does anyone know what might be causing this? I can see the resources perfectly fine on my local deployment, it's the live deployment where it's playing up.

**Comment by davidhemphill** [comment]
Sorry, but we are unable to debug your issue without a reproducible code example. Once you provide that we can open this up again.
