### ISSUE TITLE
Number -> Integer?

### ISSUE THREAD

**Issue by danrichards** [laravel/nova-issues#103]
It took me like 5 minutes to figure out, but I did read the entire documentation and watch the keynote.

A decimal number is still a number. Right?

Currency FTW, for now.

<img width="715" alt="screen shot 2018-08-24 at 2 07 46 am" src="https://user-images.githubusercontent.com/470255/44568035-00086e00-a743-11e8-8857-278bee1fc817.png">

<img width="834" alt="screen shot 2018-08-24 at 2 10 56 am" src="https://user-images.githubusercontent.com/470255/44568036-00086e00-a743-11e8-93ac-f9d6b7278be4.png">

**Comment by mrmonat** [comment]
You can use `->step(0.01)`

**Comment by danrichards** [comment]
Yes, this worked. Thank you!

![image](https://user-images.githubusercontent.com/470255/44586657-7c6c7280-a77e-11e8-8c4c-7e3f011b07ab.png)
