### ISSUE TITLE
Applying creationRules requires additional syntax

### ISSUE THREAD

**Issue by jesseschutt** [laravel/nova-issues#1031]
- Laravel Version: 5.6.39
- Nova Version: 1.1.7
- PHP Version: 7.2

### Description:

When attempting to add a Rule Object to the `creationRules` method on a Nova field, the validation is not applied unless there is an empty `''` in the first parameter.

### Steps To Reproduce:

Attempt to apply a Rule Object in the `creationRules` method like this:

```php
Text::make('Name')
    ->rules('required', 'max:255')
    ->creationRules(new AvailableName),
```

The `AvailableName` validation rule is not applied to the request. However, adding an empty parameter to position 1 causes the `AvailableName` validation rule to be applied:

```php
Text::make('Name')
    ->rules('required', 'max:255')
    ->creationRules('', new AvailableName), // Note addition of ''
```

**Comment by crnkovic** [comment]
This is intentional, as Taylor stated in the his Laracon US talk.

Common theme throughout Nova is the ability to pass a invokable object as method parameters. So, if you pass an instance of a class to the `rules` method, it will call the `__invoke` method and return the content of that method. In your case, you're returning an instance of the validation rule instead of the invokable object.

Example:

```php
// app/Nova/User.php

Text::make('Email')
    ->sortable()
    ->updateRules(new EmailRules),

// app/Nova/EmailRules.php

class EmailRules
{
    public function __invoke()
    {
        return ['required', new MyCustomRule];
    }
}
```

**Comment by davidhemphill** [comment]
Closed in laravel/nova#148

**Comment by jesseschutt** [comment]
Thanks @davidhemphill  - I can't see #148, so I'm curious what the change was?

**Comment by dkulyk** [comment]
@jesseschutt It mean what PR "Allows to pass custom rules as the first argument" was applied and will be included in the next release. :)

**Comment by davidhemphill** [comment]
Here's a pic of the diff, if you're looking to patch this in:

![image](https://user-images.githubusercontent.com/58970/49394308-256d2680-f6f9-11e8-8d73-0f61d931e878.png)

**Comment by jesseschutt** [comment]
Thanks @davidhemphill 👍

**Comment by dkulyk** [comment]
Ну ось. Ти робиш. А лаври збирає хтось інший :)

**Comment by davidhemphill** [comment]
I'm just the merger in this case, @dkulyk is to thank for this.

**Comment by dkulyk** [comment]
If you translated my comment. It was a joke ;)
