### ISSUE TITLE
Reuse Nova Resource route to update the resource with custom Card from the Dashboard

### ISSUE THREAD

**Issue by zendrax** [laravel/nova-issues#1032]
- Laravel Version: 5.7.14
- Nova Version: 1.1.8
- PHP Version: 7.2.10

### Description:

I've created custom card and it is used to provide quick update to User's status. I've tried to target the same route that is used by Laravel Nova Resource and it works. It updates the status, but response code is `canceled`. Not sure if I'm missing anything so that is why I came here.

### Steps To Reproduce:

1. Create custom Card for Nova and place it in the Dashboard
2. For quick reproduction, you can use the form that is generated for Nova's User resource and you can type in changed name of the User
3. Submit new data with `Nova.request().post` to `/nova-api/users/{id}` with following payload
```
{
    name: "Test",
    email: "test@example.com",
    password: "",
    _method: "PUT"
}
```
I'm not sure if `_retrieved_at: 1543269952` is of any value to the route but it's the same with or without it.

Expected result is that User resource is updated and response is OK.
Actual result is that User resource __is updated__ but response is Canceled.

**Comment by davidhemphill** [comment]
Don't think there's an issue per se here. You can watch the propery on $route of the component and do what you need there.

This issue board is for tracking bugs. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).

**Comment by zendrax** [comment]
OK. That sounds more convenient than passing the data from PHP. Will check it out. Thanks.
