### ISSUE TITLE
Using external library in a component

### ISSUE THREAD

**Issue by DanielProtopopov** [laravel/nova-issues#1033]
How was it planned to use external library in a component, especially the connection of the exports and data binding for the API? For example, if I use https://github.com/ClickerMonkey/dayspan-vuetify and install it through NPM (or Composer, if it's easier), how, at best, it can be achieved? The only viable option for now is to copy files across into the directories and try to accomplish it that way.

**Comment by davidhemphill** [comment]
Can't speak to specific libraries but you just import them like any other node dependency. 

Also, this issue board is for tracking bugs. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).
