### ISSUE TITLE
The toast message is not work same as work with the rerource for attached resource 

### ISSUE THREAD

**Issue by yatin13490** [laravel/nova-issues#1034]
- Laravel Version: 5.7.14
- Nova Version: 1.1.8
- PHP Version: 7.1.24

### Description:
why we did not get the same update toast code with the updateResource and updateAttachedResource?
In, nova/resources/js/views/Update.vue
this.$toasted.show(
                    this.__('The :resource was updated!', {
                        resource: this.resourceInformation.singularLabel.toLowerCase(),
                    }),
                    { type: 'success' }
                )

but in the nova/resources/js/views/UpdateAttached.vue
this.$toasted.show(this.__('The resource was updated!'), { type: 'success' })

Why should we not get the same with the updateAttachedResource, as It is better to show the relationship name then the static "resource" word

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
