### ISSUE TITLE
[Bug, FR] Nullable fields support.

### ISSUE THREAD

**Issue by dkulyk** [laravel/nova-issues#1037]
- Laravel Version: 5.7
- Nova Version: <=1.1.9
- PHP Version: 7.3RC6

### Description:
1. DateTime fields store wrong value if date was empty on the form, although the field is specified as nullable. 
2. BelongsTo field store empty string instead null if field is nullable.
3. Other fields store empty  string when must be null

#647, #89, #771

### Proposition:
Add nullable property to the all fields and store empty string as null if the property set true.

**Comment by davidhemphill** [comment]
I'm not able to reproduce the issue you claim exists on the DateTime field. If I pass an empty value to the field and submit, it's saved as `NULL` in the database. What's a way I can reproduce this problem on my end?

**Comment by dkulyk** [comment]
Middleware Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull did null from empty string but if you use text fields that can may contain an empty string but don't contain null doesn't work. In this case you have an error like `SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'full_name' cannot be null`

In my project I don't use ConvertEmptyStringsToNull.

**Comment by bonzai** [comment]
Cast value to a string on your model?

https://laravel.com/docs/5.7/eloquent-mutators#defining-a-mutator

**Comment by dkulyk** [comment]
@bonzai Do I have to consciously convert strings to null so that later I convert them back? 

My project is based since Laravel 5.1. If I'll add ConvertEmptyStringsToNull many things will work wrong.
