### ISSUE TITLE
Use css class instead of inline style in layout

### ISSUE THREAD

**Issue by FaridAghili** [laravel/nova-issues#1039]
In `nova\resources\views\layout.blade.php` line 48:
`<dropdown class="ml-auto h-9 flex items-center" style="right: 20px">`

Can be changed to:
```
<dropdown class="ml-auto h-9 flex items-center your-preferred-class-name">
.your-preferred-class-name {
  right: 20px
}
```

When using postcss-rtl to auto generate RTL layout for nova, this single inline style force you to edit the layout.blade.php file manually.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍

**Comment by AlShahawi** [comment]
Hi @FaridAghili, I'm planning to purchase a Nova licenses for my Arabian client projects, Did you faced any issues while flapping the direction to RTL using a tool such as RTLCSS?

**Comment by FaridAghili** [comment]
@AlShahawi 
Using RTLCSS doesn't result as expected.
The layout and simple fields like text, textarea, checkbox, etc are OK, but more complex fields like Trix, Markdown and upload fields get weird.
I ended up overriding only *some* of the css rules by a custom theme without using RTLCSS.

**Comment by AlShahawi** [comment]
Thanks @FaridAghili
