### ISSUE TITLE
Belongs to relationship to authenticated user

### ISSUE THREAD

**Issue by sasureshkumar** [laravel/nova-issues#104]
I have a model "Customer" and a customer belongs to a "User" who creates the customer.

customers table contains -> id, name, email, user_id, created_at, updated_at, deleted_at

When a user creating a customer record the user id should be authenticated user id, instead of selecting a user in the UI.

How can this be achieved in Nova?

**Comment by rcknr** [comment]
Hide the field from the form and create an event listener to assign the value when creating the object.

**Comment by squierll** [comment]
Just simple create model observer and then register observers in the boot method method in AppServiceProvider.


CustomerObserver
```
<?php

namespace App\Observers;

use App\Models\Customer;

class CustomerObserver
{
    public function creating(Customer $customer)
    {
        $customer->user_id = auth()->user()->id;
    }
}
```
AppServiceProvider
```

public function boot()
    {
        Customer::observe(CustomerObserver::class);
    }
```

**Comment by davidhemphill** [comment]
Use an Observer as listed above.

**Comment by osbre** [comment]
To don't have a conflict with another use case,

Associate your observer with nova:

```php
        // NovaServiceProvider.php - boot method
        Nova::serving(function () {
            Post::observe(PostObserver::class);
        });
```
https://nova.laravel.com/docs/3.0/resources/#resource-events
