### ISSUE TITLE
How to Make Nova Layout Fixed  (fixed header & sidebar)

### ISSUE THREAD

**Issue by uwascan** [laravel/nova-issues#1040]
I am currently using Laravel Nova for a complex web App (Not CMS or Blog) and have been struggling to make the Nova Layout fixed (fixed header & sidebar) with only the content section scrollable. Any guidance from CSS gurus in the house would be appreciated.

**Comment by davidhemphill** [comment]
Nova's layout is not designed to be customized in this way. 
Also, this issue board is for tracking bugs. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq). They may be able to help you hack it. 👍

**Comment by uwascan** [comment]
I got it to work by using CSS GRID and some custom css

**Comment by stephenlake** [comment]
https://github.com/stephenlake/nova-fixed-bars
