### ISSUE TITLE
Problem in translation (en.json)

### ISSUE THREAD

**Issue by FaridAghili** [laravel/nova-issues#1042]
- Laravel Version: 5.7.15
- Nova Version: 1.1.9
- PHP Version: 7.2.12

### Description:
There is a problem with the translation file (en.json) line 361:
`"resource": "resource",`

### Steps To Reproduce:
For example, change the above key like:
`"resource": "foo",`

And you get this:
![image](https://user-images.githubusercontent.com/8607021/49118253-da967d80-f2b8-11e8-82ef-53e6e4edf2de.png)

This is odd in 2 ways:
1. An 's' is added to it: foo -> foo**s**
2. Check en.json line 362!

**Comment by ceejayoz** [comment]
1. When there's multiple, it gets pluralized, via `Str::plural`.
2. Line 362 is `"Choose date": "Choose date",` for me. Can you clarify?

**Comment by FaridAghili** [comment]
1. Not every languages use an `s` for pluralizing.
2. Sorry, for me it was `"resources": "resources"`, the pluralized form of `"resource": "resource"`.

For example in Persian, it's something like this:
```
"resource": "منبع",
"resources": "منابع",
```

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍It'll use the translation for the plural instead of being computed at runtime.
