### ISSUE TITLE
HasMany paging is broken on Resource

### ISSUE THREAD

**Issue by 949mac** [laravel/nova-issues#1043]
- Laravel Version: 5.7
- Nova Version: 1.1.9
- PHP Version: 7.2

### Description:

- Paging always shows 5/35
- You can see I'm on page 4 (look in the URL)
- I would expect it to say 20/35 or something similar
![image](https://user-images.githubusercontent.com/23151962/49120062-05a0b300-f260-11e8-9918-db297661e1b6.png)

### Steps To Reproduce:
```
public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
            HasMany::make('Template Booking Disclosures'),
        ];
    }
```

**Comment by davidhemphill** [comment]
Not broken. It's showing you how many are visible of the current result set.
