### ISSUE TITLE
Updated to nova 1.1.8 broke all filters

### ISSUE THREAD

**Issue by tristanbailey** [laravel/nova-issues#1044]
Hi

When I updated to 1.1.8 the filters broke and do not show any more on any of my models. 
Sometimes the data for the table of entries will not show either. This is fixed by removing filter from the resource. 

I don’t see any php errors just Vue errors for missing name or values. I thought this was maybe the type as was looking at a Status and could be null but then I saw all of my filters missing. 

Maybe it is from the code of the new data and types of filter. I made a new make:filter which added a new public var but even empty with no filter on the $query it still shows errors. 

Have done a pinkish and publish force on this. Only change I could see was the translation file. (So think i will add nova vendor folder to git or keep copies in the future for checking)

I have not found an issue that describes this but have in slack seen people say similar. 

Could I also ask if for future updates a style of upgrade post or code change log could be shared as because I updated I can’t diff back to 1.1.7 to see what files changes to try and debug. 

Thanks

**Comment by tristanbailey** [comment]
Sample filter:
```
<?php
namespace App\Nova\Filters;
use Illuminate\Http\Request;
use Laravel\Nova\Filters\Filter;
class ProductStatus extends Filter
{
    /**
     * Apply the filter to the given query.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @param  mixed  $value
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function apply(Request $request, $query, $value)
    {
        return $query->where('status', $value);
    }
    /**
     * Get the filter's available options.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function options(Request $request)
    {
        return [
            'Live' => 'live',
            'Missing Check' => 'missing',
            'Removed' => 'removed',
        ];
    }
}
```

To add some sample errors:
```
app.js?id=ae5d9bd3a5a9a5b44593:2264 Uncaught TypeError: (0 , _composedPath2.default)(...).filter(...).flatMap is not a function
    at pathIncludesClass (app.js?id=ae5d9bd3a5a9a5b44593:2264)
    at app.js?id=ae5d9bd3a5a9a5b44593:2250
    at arrayFilter (vendor.js?id=c7d4f184dad3c7c6c376:41571)
    at Function.filter (vendor.js?id=c7d4f184dad3c7c6c376:50162)
    at VueComponent.close (app.js?id=ae5d9bd3a5a9a5b44593:2249)
    at HTMLHtmlElement.el.(anonymous function) (http://rental.holdingbay.co.uk/vendor/nova/vendor.js?id=c7d4f184dad3c7c6c376:91797:23)
pathIncludesClass @ app.js?id=ae5d9bd3a5a9a5b44593:2264
(anonymous) @ app.js?id=ae5d9bd3a5a9a5b44593:2250
arrayFilter @ vendor.js?id=c7d4f184dad3c7c6c376:41571
filter @ vendor.js?id=c7d4f184dad3c7c6c376:50162
close @ app.js?id=ae5d9bd3a5a9a5b44593:2249
el.(anonymous function) @ vendor.js?id=c7d4f184dad3c7c6c376:91797
```

```
[Vue warn]: Missing required prop: "filter"

found in

---> <SelectFilter>
       <ScrollWrap> at resources/js/components/ScrollWrap.vue
         <DropdownMenu> at resources/js/components/DropdownMenu.vue
           <Dropdown> at resources/js/components/Dropdown.vue
             <FilterMenu> at resources/js/components/FilterMenu.vue
               <Card> at resources/js/components/Card.vue
                 <LoadingCard> at resources/js/components/LoadingCard.vue
                   <LoadingView> at resources/js/components/LoadingView.vue
                     <ResourceIndex> at resources/js/views/Index.vue
                       <Root>
```

**Comment by bonzai** [comment]
It looks like you didn't [re-publish the assets](https://nova.laravel.com/docs/1.0/installation.html#updating-nova) after updating Nova:

```
php artisan nova:publish
```

Also, there's a new version available.

**Comment by tristanbailey** [comment]
@bonzai I had run nova:publish, but this was not solving the issue.
I went through 1.1.8 update and then saw a new error. 'nova-custom-filters' in console js.

FIX:
```
composer remove 64robots/nova-date-filter
php artisan nova:publish
```
Looks like the nicer date filter is now incompatible, until updates, and it is in vendor.js so breaks the other pages.
So not directly a nova issue.

**Comment by crnkovic** [comment]
Make sure to close the issue after the issue has been resolved.
