### ISSUE TITLE
PHPDoc block for File::path() has incorrect return type

### ISSUE THREAD

**Issue by mnightingale** [laravel/nova-issues#1045]
- Laravel Version: 5.6.39
- Nova Version: 1.1.9
- PHP Version: 7.2.10

### Description:
Should be `@return $this` instead of `string`, messes up IDE code completion at the moment.

```php
/**
 * Set the file's storage path.
 *
 * @param  string  $path
 * @return string
 */
public function path($path)
{
    $this->storagePath = $path;

    return $this;
}
```

**Comment by bonzai** [comment]
This has been fixed and will be included in the next release.
