### ISSUE TITLE
Footer Version not updated with 1.1.19

### ISSUE THREAD

**Issue by StanBarrows** [laravel/nova-issues#1046]
- Nova Version: 1.1.19

### Description:
<img width="615" alt="image" src="https://user-images.githubusercontent.com/10268813/49146676-f45cb280-f302-11e8-8940-2a1617887c1e.png">

**Comment by bonzai** [comment]
I can't confirm:

![zrzut ekranu 2018-11-28 11 55 39](https://user-images.githubusercontent.com/98191/49147286-8fa25780-f304-11e8-8ede-a54742d74532.png)

**Comment by crnkovic** [comment]
Did you hard refresh?

**Comment by DannyStreur** [comment]
Make sure to clear your view cache.

`php artisan view:cache`

**Comment by davidhemphill** [comment]
Republish your assets `php artisan nova:publish`. I like to add the `--force` option if I haven't customized the main layout.
