### ISSUE TITLE
How to change property value

### ISSUE THREAD

**Issue by BobbyBorisov** [laravel/nova-issues#1048]
Guys, sorry that i am posting the question here but i cannot find answer nowhere. So it is how is it possible from my custom field to trigger change in all of the field? for example when i am using template and it needs to populate the data in the creation form? is it a scenario that can be done?

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).
