### ISSUE TITLE
Partition metric with thousands with dutch numberformat

### ISSUE THREAD

**Issue by bbrala** [laravel/nova-issues#105]
When using the Partition stat, when the result is higher than 1000 it breaks on the `formatAggregateResult`. 

Line 125 Metrics\Partition
```
return [$key => (int) number_format($result->aggregate, 0)];
```

What happens is:

```
$formatted = number_format($result->aggregate, 0) // result: 1,750
$cast = (int) $formatted; // result: 1
```

This breaks the aggregate numbers.

**Comment by rcknr** [comment]
#18

**Comment by bbrala** [comment]
Ah thanks, sorry
