### ISSUE TITLE
dimensions validation on Laravel\Nova\Fields\Image validates file name, not object

### ISSUE THREAD

**Issue by ceejayoz** [laravel/nova-issues#1050]
- Laravel Version: 5.7.13
- Nova Version: 1.1.9
- PHP Version: 7.2.9

### Description:

Validation rules on an `Laravel\Nova\Fields\Image` field appear to apply to the file's name, not the underlying file. As such, it's not possible to apply dimensions rules. This is for an S3 upload; I have not tested it on other file drivers.

### Steps To Reproduce:

    \Laravel\Nova\Fields\Image::make('Image', 'key')
        ->rules('required', 'dimensions:min_width=1000,min_height=1000,ratio=1', 'max:25000000')
         ->disk('s3-public')

Results in a validation error of:

>  The key has invalid image dimensions.

(Side note: The `max` validator is similarly affected, working on the filename string instead of the file istelf.)

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
