### ISSUE TITLE
Specify Different Reset Password Broker in config/nova.php file

### ISSUE THREAD

**Issue by rthomas023** [laravel/nova-issues#1051]
It would be great to be able to specify a different reset password broker as you can with specifying a new guard.

// This exists, but still uses the default Laravel reset password broker
'guard' => env('NOVA_GUARD', 'nova'),

// It would be great if we had something like this, or of course, something more elegant
'passwords' => env('NOVA_PASSWORDS', 'nova'),

This would eliminate the need to modify the following files to override the broker method.

    /**
     * Get the broker to be used during password reset.
     *
     * @return PasswordBroker
     */
    protected function broker()
    {
        return Password::broker('nova');
    }

nova/src/Http/Controllers/ForgotPasswordController.php
nova/src/Http/Controllers/ResetPasswordController.php

I see that others have requested this as well in the following thread.
https://github.com/laravel/nova-issues/issues/43

Thanks,
Rick

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
