### ISSUE TITLE
[1.2.0] Global Search results overlapped by metric card.

### ISSUE THREAD

**Issue by MarceauKa** [laravel/nova-issues#1052]
- Laravel Version: 5.7.15
- Nova Version: 1.2.0
- PHP Version: 7.2.8

### Description:
 
Cards on dashboard or resource view.

### Steps To Reproduce:

See the picture.

### Possible fix

Replaced the CSS class of the element `//*[@id="nova"]/div/div[2]/div[1]` (xpath) from `z-20` to `z-50`

<img width="345" alt="capture d ecran 2018-11-28 a 17 29 24" src="https://user-images.githubusercontent.com/1665333/49166361-7b298380-f333-11e8-8903-090c3b268a6d.png">

**Comment by bonzai** [comment]
#807
