### ISSUE TITLE
My tool does not redirect to another view

### ISSUE THREAD

**Issue by DianaR19** [laravel/nova-issues#1054]
create a tool in which to place several buttons in actions, one of them is a button that I want to redirect me to another view created in my tool.
My code is as follows:

![image](https://user-images.githubusercontent.com/35699310/49180994-d3ed2200-f31b-11e8-90f7-0aab3d0e51f3.png)

**My tool.js**

![image](https://user-images.githubusercontent.com/35699310/49181047-f41ce100-f31b-11e8-9dd8-ddd0c5eccdd5.png)

**My Button in Tool.vue**

```
<span class="whitespace-no-wrap text-left" via-resource via-resource-id>                                        
   <router-link :to="{ name: 'edit'}" >
         <button class="bg-transparent hover:bg-red text-red-dark font-semibold hover:text-white py-2 px-4 border border-red hover:border-transparent rounded">
             Edit
         </button>
   </router-link>
</span>
```

**This the error**
![image](https://user-images.githubusercontent.com/35699310/49181507-28dd6800-f31d-11e8-9ae6-e7a29eccb051.png)

**Comment by davidhemphill** [comment]
You have errors in your template code. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).
