### ISSUE TITLE
[Bug] Error when using onlyOnForms and onlyOnIndex on the same column

### ISSUE THREAD

**Issue by rodrigore** [laravel/nova-issues#1056]
- Laravel Version: 5.7.15
- Nova Version: 1.2.0
- PHP Version: 7.1.24

### Description:

In order to display the name of a relation table I use a Text field on the index, and a belongsTo field on the forms. So my first attempt was to mix the 'onlyOnIndex and exceptOnForms': 

      BelongsTo::make('Instrumento')->onlyOnIndex(),

      Text::make('Instrumento')->displayUsing(function ($request) {
            return $this->instrumento->nombre;
       })->exceptOnForms(),              

This works fine on the index but in the form nova through an error: **Undefined property Laravel\Field\Text::$resourceClass**

The solution was to use 'exceptOnForms() and onlyOnForms()'

![image](https://user-images.githubusercontent.com/1557305/49193235-33b7ed00-f35d-11e8-9be2-6d58c077a877.png)

**Comment by davidhemphill** [comment]
Sorry, but we are unable to debug your issue without a reproducible code example. When you're able to demonstrate the issue with an example, feel free to open a new issue.
