### ISSUE TITLE
metric $this->result() does not accept a collection

### ISSUE THREAD

**Issue by ceejayoz** [laravel/nova-issues#1057]
- Laravel Version: 5.7.13
- Nova Version: 1.1.9
- PHP Version: 7.2.9

### Description:
Metric `$this->result()` should accept a collection.

### Steps To Reproduce:
I expected this code to work:

    public function calculate(Request $request) {
        $tags = Tag::withCount('stories')->pluck('stories_count', 'name');
        return $this->result($tags);
    }

Instead:

> Argument 1 passed to Laravel\\Nova\\Metrics\\Partition::result() must be of the type array, object given...

Sure, I can `toArray()` it, but Laravel's collections are so nice (and prevalent throughout the framework) it shouldn't be strictly necessary.

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
