### ISSUE TITLE
Call to a member function getKey() on null

### ISSUE THREAD

**Issue by liyuanzao** [laravel/nova-issues#1058]
- Laravel Version: 5.7
- Nova Version: 1.2.0
- PHP Version:  7.2.12

### Description:

message | Call to a member function getKey() on null
-- | --
exception | Symfony\Component\Debug\Exception\FatalThrowableError
file | /application/vendor/laravel/nova/src/Rules/Relatable.php
line | 84

### Steps To Reproduce:

I have two DB tables

one is **account**, the other is **domains**

In **Account** table, there's two columns called domain_id, target_domain_id,

So In  the Nova/Account.php

I have 

```
BelongsTo::make('Domain','Domain','\App\Nova\Domain')->searchable()->nullable(),
BelongsTo::make('Target Domain','targetDomain','App\Nova\Domain')->searchable()->nullable(),
```

and In Account.php Model have

```
 public function domain()
    {
        return $this->BelongsTo('App\DBModels\Domain');
    }
```

    public function targetDomain()
    {
        return $this->BelongsTo('App\DBModels\Domain');
    }

The index page and detail page shows fine, it is able to create new account, everything works fine. But can't edit, once edit with null value for domain and tagetDomain, it shows  error

**Call to a member function getKey() on null**

**Comment by waygou** [comment]
This one happens for a long time, guess it was never corrected.

Somehow there is no dynamic attribute possible to get on the getKey() method (line 84, on the src/Rules/Relatable.php).

So, I made this change:

![image](https://user-images.githubusercontent.com/39349827/49221086-605d1a80-f3d8-11e8-8cfe-d478e169232e.png)

I don't know how much this is the right fix, but it works on my case.

Hope it helps.

**Comment by liyuanzao** [comment]
Thanks,  it looks fix the bug, but need to confirm with @taylorotwell

**Comment by Goldfinch** [comment]
I believe this conditional statement should be updated as the related model might be null, like it was in my case when the model was created initially without belongsTo relationship (nullable, default = null) but when you go to update it this line obviously fails the request as we can't get getKey() from null

```php
if ($modelBeingUpdated->{$attribute}->getKey() == $value) {
```
this looks better to me

```php
if ($modelBeingUpdated->{$attribute} && $modelBeingUpdated->{$attribute}->getKey() == $value) {
```

**Comment by liyuanzao** [comment]
@Goldfinch Thanks a lot

**Comment by lichtner** [comment]
@Goldfinch thanks, for the solution. Still an issue with Nova 1.3.2. 
Could it be fixed in next release @taylorotwell?

**Comment by tumispro** [comment]
Any news on this? Seems weird that such a simple bug can exist for so long.

**Comment by iventru** [comment]
What did not fix?

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!

**Comment by halberio** [comment]
+1

**Comment by brendanquinlan** [comment]
Hey @jbrooksuk - still experiencing this issue on the latest version of Nova. 

Nova Version: 3.29.0
Laravel Version: 8.61.0

**Comment by 16hands** [comment]
This is found by google if you search something like "2019_05_10_000000_add_fields_to_action_events_table Call to a member function getKeyType() on null"

Nova is getting the user model in the migration and assumes that the returned user provider is DB based

If you have a none DB based user driver/provider like Statamic installed this fails and you get this error, 

while there is the bigger issue that you will need to work through (Nova needs users and can't use Statamic Users) to get this to migrate edit the config/auth.php file and change providers back to eloquent and then run the nova migrations and then set this back again if you need to login into Statamic 

If Statamic is setup to use file users you will need to set that to DB users if you want to get NOVA and Statamic working in the same laravel install 

If you do this on a production Statamic install you will break the site ;-)

Hope this helps
