### ISSUE TITLE
withMetaOnUpdate & withMetaOnCreate

### ISSUE THREAD

**Issue by AbanoubNassem** [laravel/nova-issues#1059]
at this point , I can't seem to find a way to send meta condaintally , so for example :

```
Number::make('Order')->withMetaOnCreate([
                'extraAttributes' => [
                    'readonly' => true,
                ],
            ])->fillUsing(function ($request, $model, $attribute, $requestAttribute) {
                $model->order =  \App\Models\Restaurant::find($request->get('restaurant'))->menuItems->count() + 1;
            }),
```

so on creation the order filed is readonly , but after it's in the database the User can update it, hopefully I made it clear enough.

**Comment by dillingham** [comment]
'readonly' => request()->segment(4) == 'new'

this isnt a place for people to write your code & this isnt a bug

**Comment by davidhemphill** [comment]
@dillingham's answer will work
