### ISSUE TITLE
Using Form request validation for Nova resource

### ISSUE THREAD

**Issue by peanut24** [laravel/nova-issues#106]
I have existing form request validation classes that I'm using for storing a user for instance, is it possible to reuse these in my Nova resource, or do you have to specify the validation rules per field? I can't find reference to this in the documentation for Nova.

Thanks

**Comment by stevelacey** [comment]
Also would make it possible to validate arrays, which I am not sure is possible via the validation rules per field implementation

**Comment by davidhemphill** [comment]
This is not currently supported.

**Comment by fbingha** [comment]
Is this planned?

**Comment by yehudahkay** [comment]
You can add an array on either the model or form request and then reference it in the nova controller, it would be nice if this would work automatically though.

**Comment by EricPaulson** [comment]
It doesn't make sense for Nova to require its own homegrown validation rather than using Laravel's perfectly functional Requests for validation. This requires many of us to duplicate logic in our applications. When will this be addressed?

**Comment by davidhemphill** [comment]
Don't know why folks don't like that I said it's currently not supported. It's the truth. 😄 

Would welcome a PR to add this, otherwise there are more pressing features/bugs to address at this time.
