### ISSUE TITLE
Global search & searchable relations are case-sensitive when using Oracle driver.

### ISSUE THREAD

**Issue by michaelsabatino** [laravel/nova-issues#1061]
- Laravel Version: 5.7.15
- Nova Version: 1.1.8
- PHP Version: 7.2.4
- Database: Oracle 12c

### Description:
I'm using yajra/laravel-oci8 Oracle driver: https://github.com/yajra/laravel-oci8. Global search is case-sensitive-only as are searchable relations.

### Steps To Reproduce:
After defining search fields in the Nova resource:

`public static $search = [
        'id',
        'name'
    ];`

Searching for "Medical" will return only names containing "Medical" and not, for example, "biomedical". Searching for "medical" will only return names containing "medical" (including "biomedical") but not "Medical".

This may render Nova unusable for our enterprise.

**Comment by dkulyk** [comment]
You can overload applySearch method in your resource and write a search query as you need.

**Comment by michaelsabatino** [comment]
> You can overload applySearch method in your resource and write a search query as you need.

This work-around seems to work, thanks.

**Comment by davidhemphill** [comment]
Closing as Oracle is not a built-in Laravel database provider.

**Comment by jarda256** [comment]
@davidhemphill It is same with mysql. At least for me php 7.2 nova 1.2.1

**Comment by royduin** [comment]
I can also confirm this is also a issue with MySQL 5.7.18, PHP 7.2.1 and Nova 1.3.2

**Comment by fede91it** [comment]
Same for me
