### ISSUE TITLE
Nova depends on method getKey() that is not defined in Authenticatable

### ISSUE THREAD

**Issue by jakobbuis** [laravel/nova-issues#1063]
- Laravel Version: 5.7.13
- Nova Version: 1.1.8
- PHP Version: 7.2.11-4

### Description:
Nova depends on the getKey() method for the User-model, but it isn't required on the Authenticatable-interface.

### Steps To Reproduce:
1. Create a default laravel project.
2. Create and register a custom User class that implements `Illuminate\Contracts\Auth\Authenticatable`.
3. Create a resource. 
4. Create an instance of that resource. 
5. Open the instance for editing, and save some changes.

Expected: model succesfully saved
Happened: error notification stating `Undefined method App\Salesforce\User::getKey()` (where App\Salesforce is the namespace of my custom User)

I would expect Nova to only depend on the Authenticatable-interface - or that the Authenticatable interface contains `getKey()` - but I might be seeing that wrong? 

Attached is the laravel.log file with only the stack-trace for this error:. [laravel.log](https://github.com/laravel/nova-issues/files/2629498/laravel.log)

**Comment by jakobbuis** [comment]
I just realised that the problem is in the action_events logging: Nova gets the id of the current user to insert the action taken into that table.

**Comment by deleugpn** [comment]
I haven't reached this step yet, but I am working on installing nova in a project which has Authenticatable objects. This problem had affected Telescope as well and the solution was to simply call `getAuthIdentifier()` instead. Hope it get fixed soon.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
