### ISSUE TITLE
How to call third party API ?

### ISSUE THREAD

**Issue by Keyur-Galdhariya** [laravel/nova-issues#1066]
I wanted to put new button called 'Sync' on one page of nova.
And on click of that, I want to fetch data from third-party and save it to the database.

How can I do that?

**Comment by davidhemphill** [comment]
Use something like axios to call the API in a custom tool. Make a router with a controller and send a request to it. Basic app development stuff.

Also, this issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).
