### ISSUE TITLE
Missing ability to hyperlink text fields

### ISSUE THREAD

**Issue by jameslkingsley** [laravel/nova-issues#107]
It would be great if we could tag a text field as a hyperlink, something like:

```php
Text::make('Url')->hyperlink('Optional Name')
```

Which should render out:

```html
<a href="the-underlying-url-value" target="_blank">Optional Name</a>
```

**Comment by kayyyy** [comment]
Take a look at this[Nova External URL Field](https://novapackages.com/packages/pdewit/nova-external-url)

**Comment by davidhemphill** [comment]
You can do this recently-released `asHtml` option for computed Text fields: https://nova.laravel.com/docs/1.0/resources/fields.html#computed-fields
