### ISSUE TITLE
Call filter options again on filter change 🔥

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#1070]
- Laravel Version: 5.7
- Nova Version: 1.2.0
- PHP Version: 7.2

### Description:

On filter change, filters get their `options()` called again (ajax) and receives other filter values
and we add conditions within our filter's `options()` based on other filter values

### Scenarios

- Country > State > City
- Office > Office Users
- Category > Sub Category

Selecting an Office, calls all current page's filter options() again 

### Implementation 

This conditional would make Users empty until Office is selected
```php
function options($request, $filters)
{
    return \App\User::where('office_id', $filters['office'])->pluck('name', 'id);
}
```

But you could also do it conditionally, allowing all users and all offices initially 
```php
function options($request, $filters)
{
    return \App\User::query()->when($filters[‘office’], function ($query, $office_id) {
            return $query->where('office_id', $office_id);
    })->pluck('name', 'id);
}
```

### Filter Properties 

*`$hideWhenEmpty = true;`*

If condition returns no results, hide filter. This would make super clean "dependent filtering" 

`$optionRefresh = true;`

A way to indicate that you don't wish for the options on certain filters to be called again

### Possible Gotchas
> On page load, sometimes filters may be applied.. options would need filtering on initial state

> Long request times for options() would require some sort of loading indication
> I would imagine it on the filter that just changed.. little spin wheel in title
> otherwise hidden filters due to 0 options may not appear in time for user to see

> would be optimal if a change on “filter a” only checked the options for “filter a”  or had a isDirty approach at least to return false form options if not changed maybe

### Related
https://github.com/laravel/nova-issues/issues/223 https://github.com/laravel/nova-issues/issues/821

**Comment by dkulyk** [comment]
You can write you own filter with more than one field and use AJAX for it.

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by dkulyk** [comment]
It already implemented in [awesome-nova/dependent-filter](https://github.com/awesome-nova/dependent-filter)
