### ISSUE TITLE
Searchable field not working on Android

### ISSUE THREAD

**Issue by pjhile** [laravel/nova-issues#1073]
- Laravel Version: 5.7.15
- Nova Version: 1.2.0
- PHP Version: 7.1.20

### Description:
Searchable fields don't keep the value after selection on Android. Tested with Pixel 3 and Pixel 2 xl, Chrome and Firefox. Seems to work on an iPhone 5 Chrome and Safari.

### Steps To Reproduce:

![20181201_175949](https://user-images.githubusercontent.com/224067/49333798-23895300-f593-11e8-9766-b0da1992ed7a.gif)

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
