### ISSUE TITLE
PHPDoc Typo

### ISSUE THREAD

**Issue by OwenMelbz** [laravel/nova-issues#1074]
- Laravel Version: 5.7
- Nova Version: 1.2.7
- PHP Version: 7.2

### Description:
Within `vendor/laravel/nova/src/Nova.php` it has

```php
   /**
     * Register the Nova routes.
     *
     * @return void
     */
    public static function routes()
    {
        Route::aliasMiddleware('nova.guest', RedirectIfAuthenticated::class);

        return new PendingRouteRegistration;
    }
```

The PHPDoc says `@return void` however it returns `new PendingRouteRegistration`

I imagine this is just at typo thats easily updated?

**Comment by OwenMelbz** [comment]
Oh okay?

**Comment by dkulyk** [comment]
This has been fixed and will be included in the next release.
