### ISSUE TITLE
can i get the resource url and send  param to  redirect url?

### ISSUE THREAD

**Issue by loveyuxiao** [laravel/nova-issues#1076]
```
    public function fields(Request $request){
       1、$Url=   MyRedirectResourceClass  How can i get the MyRedirectResourceClass Url?
       $Param='?Param1=XXX&Param2=XXXX';
       Text::make("Link",function(){
            return '<a href="'.  $Url. $Param .'">Link</a>';
       })->asHtml(),
  }
```
2、in the target MyRedirectResourceClass ,how can i get the $Param in indexQuery,the following code not work

```
    public static function indexQuery(NovaRequest $request, $query)
    {
        return $query->where('Param1', $request->get('Param1'))
            ->where('Param2', $request->get('Param2'));

    }
```

**Comment by dkulyk** [comment]
You can try to use filters instead params.

**Comment by loveyuxiao** [comment]
@dkulyk  thx

**Comment by loveyuxiao** [comment]
@dkulyk  but first i should kown which param send and  use filter.

**Comment by dkulyk** [comment]
You need to make filter. After you add query parameter with name `YourResource::uriKey().'_filters'`
As value you need to set base64 encoded JSON where key is the filter class name and value is you filter value(s).

This is my guess, I have not tested it.

**Comment by vernard** [comment]
@dkulyk Is there a documented way to do this?

I wanted to create a link on my dashboard which automatically applies the filter on my intended resource. This would save a lot of clicks.
