### ISSUE TITLE
[FR] Fields as invokables

### ISSUE THREAD

**Issue by m-lotze** [laravel/nova-issues#1077]
In our current app we have a lot of fields that are the same for many resources, e.g. a description or a name field. So i think it would be nice, to have the ability to define fields as an invokable. This is already possible right now like this:

```
public function fields(Request $request) {
    return [
        (new invokableField)()
        ...
    ]
}
```

But this does not work with computed fields, except maybe like `(new invokableField)($this)`. 

My proposal would be something like this:

Allow fields to be invokables. The `__invoke()` method should receive the resource as a parameter, so we can use computed fields and should return either a field or an array of fields (different definitions for index, detail and form..) that is merged into fields()

Maybe with an artisan command that generates a stub, e.g. in `app/Nova/Fields`

```
class Field
{
    public function __invoke(Laravel\Nova\Resource $resource)
    {
        // return a Field or an array of Fields
        // in computed fields use $resource instead of $this
    }
}
```

I think this would be very helpful and would reduce a lot of repetition for fields.

**Comment by dkulyk** [comment]
You can try to use MergeValue class like as Panel. 
```php
class MyFieldCollection extends \Illuminate\Http\Resources\MergeValue
{
    public function __construct()
    {
        parent::__construct([
            Text::make(...), 
            //...
        ]);
    }
}
```

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
