### ISSUE TITLE
Failed to download laravel/nova from dist - when deploying to production

### ISSUE THREAD

**Issue by kombimedia** [laravel/nova-issues#1078]
When deploying via Forge to a production server the process is failing when attempting to install Nova. I have see an identical issue #705 but the solution there has not fixed mine. Any ideas on how this may be resolved?

- Laravel Version: 5.6.39
- Nova Version: 1.2.0
- PHP Version: 7.2

### Description:
I am installing Nova with composer and there are no issues on my dev site. Potentially an auth issue, however I have not been prompted to enter my Nova account creds, as I was the last time I deployed a Nova app to production.

composer.json require:
`"laravel/nova": "~1.0",` 

composer.json repositories:
`"type": "composer",
"url": "https://nova.laravel.com"`

Forge Error Message:
Installing laravel/nova (v1.2.0): Downloading (connecting...)    Failed to download laravel/nova from dist: The 'https://nova.laravel.com/dist/laravel/nova/laravel-nova-[key]-zip-aadcfe.zip' URL could not be accessed: HTTP/1.1 403 Forbidden
    Now trying to download from source
  Installing laravel/nova (v1.2.0): Cloning [key]

  [RuntimeException]
  Failed to execute git clone --no-checkout 'git@github.com:laravel/nova.git' '/home/forge/[domain]/vendor/laravel/nova' && cd '/home/forge/[domain]/vendor/laravel/nova' && git remote add composer 'git@github.com:laravel/nova.git' && git fetch composer

### Steps To Reproduce:
Deploy dev site to production

**Comment by bonzai** [comment]
You need to provide your credentials in the `auth.json` file (`~/.config/composer/auth.json` or in `COMPOSER_HOME`):

```json
{
    "http-basic": {
        "nova.laravel.com": {
            "username": "xxx",
            "password": "yyy"
        }
    }
}
```

- https://nova.laravel.com/docs/1.0/installation.html#installing-nova-via-composer
- https://getcomposer.org/doc/articles/http-basic-authentication.md

**Comment by kombimedia** [comment]
@bonzai  Awesome! That did the trick.. Best I read the docs a little better in future... Thank you so much!

**Comment by ChristopherDosin** [comment]
For forge the credentials are actually saved within `/home/forge/.composer/auth.json` just in case someone has the same issue with laravel forge :)

**Comment by lukeraymonddowning** [comment]
> For forge the credentials are actually saved within `/home/forge/.composer/auth.json` just in case someone has the same issue with laravel forge :)

To add to this: if you're using locked off users on Forge, make sure to replace '/forge/' with the name of your user (eg: `/home/staging/.composer/auth.json`)

**Comment by monaye** [comment]
I use forge with envoyer and didn't find `/home/forge/.composer/` directory.  
Instead I did ssh to the forge server and `composer install` manually, then it will prompt you like follow: 
```
Do you want to store credentials for nova.laravel.com in /home/forge/.config/composer/auth.json ? [Yn] y
```

**Comment by izshreyansh** [comment]
Remove `composer.lock` file and try `composer install`

This fixed issue on my case.

**Comment by gTerrusa** [comment]
@izshreyansh thank you! this saved me today

**Comment by voicecode-bv** [comment]
For people having problems upgrading to Laravel Nova 4 on Forge, the auth.json file is located at:

/home/forge/.config/composer/auth.json

Might replace "forge" with another user if needed.

**Comment by ashokgelal** [comment]
And for people having problems on [Cleavr](https://cleavr.io), the auth.json file is located at:

`/home/cleavr/.config/composer/auth.json`

Actually, on any system, the best way to find the actual location is to run: `composer global config --list` and check the `[home]` key.

**Comment by hilmanski** [comment]
Here is how I solve it.
For fresh laravel project on Forge, 
- add repo first without install composer
- add auth basic  (on packages tab)
- isntall composer
detail: https://onebite.dev/deploy-nova-at-laravel-forge
