### ISSUE TITLE
Trend count query not using custom column

### ISSUE THREAD

**Issue by SeoFood** [laravel/nova-issues#108]
`\Laravel\Nova\Metrics\Trend::count`

should be returning 

`return $this->aggregate($request, $model, $unit, 'count', $keyName, $column);`

instead of

`return $this->aggregate($request, $model, $unit, 'count', $keyName);`

**Comment by vmitchell85** [comment]
I've confirmed this as well. It's also mentioned in #95

**Comment by taylorotwell** [comment]
Fixed in upcoming release.
