### ISSUE TITLE
Default lang files gave me an error

### ISSUE THREAD

**Issue by nicolaslaurent123** [laravel/nova-issues#1084]
- Laravel Version: 5.7
- Nova Version: 1.0
- PHP Version: 7.2

### Description:
When installing Laravel Nova the default install route for the lang file is 'resources/lang/vendor/nova'
while for it to work it has to be in 'resources/lang/vendor' because else I got an error in login.blade.php.

### Steps To Reproduce:
1. Installed Laravel Nova
2. Then I got this error: htmlspecialchars() expects parameter 1 to be string, array given.
3. Fixed the problem by moving the en.json from 'resources/lang/vendor/nova' to resources/lang/vendor'

**Comment by Lupinity** [comment]
Relates to [Translations should be namespaced #475](https://github.com/laravel/nova-issues/issues/475)

**Comment by fgilio** [comment]
I shared a way to patch part of the problem here: https://github.com/laravel/nova-issues/issues/475#issuecomment-674943592
