### ISSUE TITLE
Customize Tool: axios results to false request URL

### ISSUE THREAD

**Issue by pmochine** [laravel/nova-issues#1086]
- Laravel Version: 5.7.15
- Nova Version: 1.2.0
- PHP Version: 7.2.7

### Description:

**Short Version**
Somehow axios (or Nova.request()) is buggy. 
`Nova.request().get(this.url)` should call this url: 

`https://nova.mydomain.test/nova-vendor/swipe-offer/nova/waitingforreview`

 but instead it calls this URL: 

`https://nova.mydomain.test/dashboard/nova-vendor/swipe-offer/nova/waitingforreview` 

**Long Version**

1. I created a custom tool
2. And fetching the API I get somehow "dashboard" added to the url

*Tool.vue*

```
<script>
    export default {
        computed:{
            url(){
                return 'nova-vendor/swipe-offer/nova/waitingforreview';
            }
        },
        methods:{
            fetchOffers(){
                Nova.request()
                    .get(this.url)
                    .then(this.setOffers)
                    .finally(this.setLoading);
            },

```

Now comes the funny part. I've written a custom card and the code is nearly identical 

*Card.vue*
```
<script>
    export default {
        computed:{
            url(){
                return '/nova-vendor/laravel-nova-hashids/hashids';
            }
        },
        methods:{
            config(){
                Nova.request()
                    .get(this.url)
                    .then(this.setConfig)
                    .catch(this.setError)
                    .finally(this.setLoading);
            },
```

Everything works fine here. Another funny part is that when I write in Chrome's console this:
`axios.get('nova-vendor/swipe-offer/nova/waitingforreview')` the request URL is wrong as stated in the beginning.

Now if I write this: 
`axios.get('/nova-vendor/laravel-nova-hashids/hashids')`  everything is fine...

What could be wrong?

In `config/nova.php`
I have added those two lines:

    'domain' => 'nova'.env('SESSION_DOMAIN'),
    'path' => '/dashboard',

Everythingelse works super fine, I can viewAny, update, store, create etc. 
 
If something is not clear, I'm happy to answer right back. 

Thank you for your help & time.

#### Edit

When I leave nova and go to mydomain.test and call the axios in the console, everything works as expected.

**Comment by dillingham** [comment]
You're returning ` return '/nova-vendor/` in the card and ` return 'nova-vendor/`

Relative urls starting with a slash mean start from domain. 
Relative urls without the slash in the beginning mean start from the current path.

This isn't a bug in nova. Please use [chat](https://discord.gg/FDzEUYP) for questions

**Comment by pmochine** [comment]
@dillingham omg I feel like overworked.... sorry about the issue
