### ISSUE TITLE
How do you add vuex to Laravel Nova

### ISSUE THREAD

**Issue by uwascan** [laravel/nova-issues#1088]
I am working on a Tool for Nova, and I need to use Vuex . Is there a way to add Vuex to Laravel Nova Tool,  considering the fact that Nova already uses Vuex for its filter implementation?

**Comment by noahlocke** [comment]
@uwascan it's not available globally (I don't think...) so just add it to your Tool's `package.json`

**Comment by uwascan** [comment]
@noahlocke I think doing that will conflict with Nova's filter implementation on Index pages because Vuex has been registered already in nova. I am looking at using mobx until there is an official way to do it with Vuex that is already in Nova

**Comment by bonzai** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://larachat.co/).
