### ISSUE TITLE
Unwanted new lines in Trix resource field 

### ISSUE THREAD

**Issue by Youniteus** [laravel/nova-issues#1089]
- Laravel Version: 5.7.15
- Nova Version: 1.2.0
- PHP Version: 7.2.11

### Description:
Every time I save the Trix field an additional trailing new line is added.
In html it adds `<div><!--block--><br></div>`

### Steps To Reproduce:
1. Have a resource item with a Trix text field.
2. The first line in the Trix field should be a header.
3. Add some other text.
4. Save, edit, save the resource a couple of times.
5. Everytime you save, a trailing new line gets added.

Any ideas how to solve this?

**Comment by Youniteus** [comment]
my fix for now is to strip it before saving the model:
```
    public static function boot()
    {
        parent::boot();

        self::saving(function ($model) {
            [...]
        });
    }
```

**Comment by virp** [comment]
The same problem, if the first line is a header, then a new line is added after each save.

**Comment by InfinityWebMe** [comment]
Still present in the latest v2.0.3 release.

Any news on this ?

**Comment by jgile** [comment]
bump.  same issue

**Comment by jbrooksuk** [comment]
I've tested this in Nova v2.0.9 and I did not get any extra HTML added to the data.

**Comment by flexchar** [comment]
I have laid off the client but the circumstances are that if you have Trix field, it will automatically get focus, thus creating new empty line (don't remember if it's <p> or <span>), even thou if the editor refers to editing another field.

**Comment by jbrooksuk** [comment]
@flexchar in what version of Nova is this?

**Comment by flexchar** [comment]
Also in the latest 2.0.9

**Comment by jbrooksuk** [comment]
What browser are you seeing this in? I'm testing in Chrome and Safari on MacOS and I don't get any new lines or content created in the Trix field unless I type something in it.

I can however, see that the Trix field is first to gain focus.

**Comment by flexchar** [comment]
Firefox Developer. Version 69, I believe. On Windows 10 latest.

I'll follow later today with Chrome.

**Comment by jbrooksuk** [comment]
I'll test on Firefox now.

**Comment by jbrooksuk** [comment]
Hmm, I can't replicate this on Firefox either.

**Comment by flexchar** [comment]
Wait, what we use trix field is for the unordered list. What if you create
one yourself?

**Comment by jbrooksuk** [comment]
I'm not sure what you mean, sorry. Could you please clarify? :)

**Comment by flexchar** [comment]
Sure, no worries!

The field's sole purpose is listing ingredients (for recipe) so it only
contains a list of ingredients such as bullet points in Word.

- milk
- specially prepared dough
- and so on.

I'm currently behind my phone, could follow later with more precise
example.

**Comment by jbrooksuk** [comment]
Ah, I've managed to recreate it simply with the header as the first line.

**Comment by jbrooksuk** [comment]
It seems that this is an issue with Trix itself and not Nova, https://github.com/basecamp/trix/issues/291 (this is from 2016 but still relevant).

I've just tested upgrading Trix to v1.2.0 but that hasn't resolved the issue. Javan suggested doing the same thing as @Youniteus and trimming this out as you save it. That's all we have, I'm afraid.

**Comment by flexchar** [comment]
Yep, sounds around right. I've done some research around Christmas time and
I remember reading the same stuff.

So it's a Trix issue and probably nothing Nova can do at a time,
unfortunately. Besides doing manual stripping on-save.

But thanks for your time for looking into this.:)

**Comment by voidgraphics** [comment]
Sorry to revive this, but are we sure it's really linked to that trix issue? They only refer to new lines added manually to create more writing room I think. This one is a new line that is automatically added as per @flexchar's comment 
> I have laid off the client but the circumstances are that if you have Trix field, it will automatically get focus, thus creating new empty line (don't remember if it's `<p />` or `<span />`), even thou if the editor refers to editing another field.

The hack to trim the data when saving works, but we should not have to do that every time we use a trix field, right? Should we try to find ways to integrate the fix into Nova instead?

Thanks for the help, it is always appreciated. :+1:
