### ISSUE TITLE
Relationship Fields don't consider foreign keys

### ISSUE THREAD

**Issue by rcknr** [laravel/nova-issues#109]
When you try to make relationship field sortable it uses the same attribute name for SQL query. Eloquent's convention is to have foreign keys named after the model name plus `_id` suffix and this could be customized as well. It'd be great if Nova figured out the name of the foreign key or let it set manually.

**Comment by rafaellupo** [comment]
Guys, any workaround here? I've bought Nova today to speed up my Job but what I got is getting stuck at such a basic thing like this.  At the current scenario I'll need to do a huge refactor, what is worth much more than I've paid... Sad.

**Comment by CJDennis** [comment]
I've had a quick look at the code. When you create a Nova `BelongsTo` or `BelongsToMany`, the foreign table can't be specified. It has no idea which resource is requesting the other resource. Also, when the AJAX call is made from the Nova page, no foreign key is passed, which could be dependant on which resource you're viewing it from. It just assumes that the key is always the primary key.

It seems that you'd need to pass the foreign key column name within the AJAX call for this to work properly.

**Comment by braceyourself** [comment]
Easy workaround:

Create an action for that resource that collects the information you need, creates the model and attaches it to the selected models.

    public function handle(ActionFields $fields, Collection $models)
    {
        $answer = Answer::create([
            'body' => $fields->answer_text,
        ]);

        foreach ($models as $question){
            $question->answers()->attach($answer);
        }
    }

**Comment by ians88** [comment]
Any info on if this will be fixed? Is it on the roadmap?

**Comment by davidhemphill** [comment]
Sorry, but we are unable to debug your issue without a reproducible code example. Once you provide that we can open this up again.
