### ISSUE TITLE
Add buttons in metrics

### ISSUE THREAD

**Issue by AbeNalee** [laravel/nova-issues#1090]
It would be nice if there could be an option to include buttons within metric cards. This would be especially useful if, for example, a user wanted to  navigate to the metric being analyzed directly from the metric itself.

**Comment by davidhemphill** [comment]
This is why you can create your own custom cards. It'd be impossible to anticipate everyone's pet features. 😄

**Comment by davidhemphill** [comment]
If enough stuff gets sent into official support or gets reactions here, I take notice. 👍

**Comment by christophrumpel** [comment]
+1 for linkable cards/metrics

**Comment by cord** [comment]
+1 for linkable cards/metrics

**Comment by cord** [comment]
see https://novapackages.com/packages/saintsystems/nova-linkable-metrics (currently not compatible with Nova 3.*)

**Comment by mstaack** [comment]
oh yes please!
