### ISSUE TITLE
Add listing table in new panel for detail view

### ISSUE THREAD

**Issue by Ange7** [laravel/nova-issues#1091]
hello, 

I think it would be cool if we can add listing table in new panel for detail view. 

Example: I have item parent detail with panel which contains all children's 

Thank you guys

**Comment by dillingham** [comment]
Like a hasMany on a self referencing eloquent relation?

**Comment by Ange7** [comment]
yes.

**Comment by dillingham** [comment]
That’s already possible. HasMany field displays on detail pages. You should ask in chat

**Comment by Ange7** [comment]
WoW ok, i'm sorry so.
