### ISSUE TITLE
Error in tool.scss 

### ISSUE THREAD

**Issue by DianaR19** [laravel/nova-issues#1092]
Create a Tool and when I run `npm run watch` it shows me the following error and the page is displayed without styles.

![image](https://user-images.githubusercontent.com/35699310/49527440-891d5e00-f877-11e8-859e-bc72ac91b27f.png)

I am using Tailwind CSS.

**Comment by bonzai** [comment]
You have a missing `}` in `nova-components/season/resources/sass/tool.scss`.
