### ISSUE TITLE
Changing FIlter Titles

### ISSUE THREAD

**Issue by thegregthomp** [laravel/nova-issues#1093]
Is it possible to change the title of a filter, or how it displays? I like using a more literal file/class name but that showing in the UI is too much. 
<img width="288" alt="screen shot on 2018-12-05 at 19_29_29" src="https://user-images.githubusercontent.com/1554124/49553106-21413480-f8c4-11e8-97d9-a2c7384d5af8.png">

**Comment by dkulyk** [comment]
```php
public $name = 'Filter name';
//or
public function name()
{
    return __('Filter name');
}
```

**Comment by tsn-Sergey** [comment]
How can I dynamically change the name of a filter?
For example, I pass the column name in the constructor. And I want the filter to be named according to the column.

```php
public function filters(Request $request)
{
     return [
         new DateRangeFilter('created_at'),
         new DateRangeFilter('started_at'),
         new DateRangeFilter('finished_at')
     ];
}
```
The name is set only the first time a `new DateRangeFilter('created_at')` is created.

**Comment by tsn-Sergey** [comment]
> ```
> public $name = 'Filter name';
> //or
> public function name()
> {
>     return __('Filter name');
> }
> ```

How can I dynamically change the name of a filter?
For example, I pass the column name in the constructor. And I want the filter to be named according to the column.

```php
public function filters(Request $request)
{
     return [
         new DateRangeFilter('created_at'),
         new DateRangeFilter('started_at'),
         new DateRangeFilter('finished_at')
     ];
}
```
The name is set only the first time a `new DateRangeFilter('created_at')` is created.
