### ISSUE TITLE
Clicking Select All Matching checks both checkboxes

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#1094]
- Laravel Version: 5.7
- Nova Version: 1.2.0

### Description:
When you click "Select all matching" it checks "Select All" also

![bug](https://user-images.githubusercontent.com/29180903/49553164-606f8580-f8c4-11e8-8e8b-4be67203554a.png)

**Comment by dkulyk** [comment]
Select All is part of Select All Matching

**Comment by dillingham** [comment]
@dkulyk that doesn't make sense to me

**Comment by davidhemphill** [comment]
Why do you think this is a bug? If you select all the resources matching the current query/filter/etc you are selecting all of the visible ones as well as the ones that can't be seen due to pagination.

**Comment by davidhemphill** [comment]
No worries! We could maybe display it better.
