### ISSUE TITLE
[Feature Request] Remove "Select All Matching"

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#1095]
- Laravel Version: 5.7
- Nova Version: 1.2.0

### Description:

Defaulting to "Select All" then meaning select all in the filtered set

![select-all](https://user-images.githubusercontent.com/29180903/49553432-a547ec00-f8c5-11e8-86c1-bb1d9313e7e2.png)

Remove drop down and add filtered count to title for clear indication 
I do see in cases like gmail that select all and select all total are a thing
I just have yet to want to select just the current page

**Comment by dillingham** [comment]
https://github.com/laravel/nova-issues/issues/322 
https://github.com/laravel/nova-issues/issues/755 
https://github.com/laravel/nova-issues/issues/1094 
https://github.com/laravel/nova-issues/issues/326 
https://github.com/laravel/nova-issues/issues/194

**Comment by dwyer14** [comment]
Adding filtered count to title is a nice touch. 🔥 +1 for this change in general.

**Comment by davidhemphill** [comment]
I'm not really opposed to this in principle, but I personally have situations where I want to baby a really destructive action page by page. 

Contrived example: You have 100k+ users and want to move their address from columns on each row to a related model. It deletes the value in the column after migrating it to an object. 

This is the kind of thing where it's nice to select all (on the page), run the action as test for a couple of pages and then run the action on the rest of the matching ones.

**Comment by dillingham** [comment]
@davidhemphill you’re right. Makes sense to keep as is. Even wanting to select the majority of the visible page it comes in handy to select all and deselect a few manually.

**Comment by dwyer14** [comment]
@davidhemphill that makes sense. Maybe a nice addition, to have a `disableSelectAllPage` property (or something similar) on the resource. Can definitely see how that's not something you want to blow away entirely, though. 👍

**Comment by baykier** [comment]
@dillingham does this feature has published ? thx

**Comment by dillingham** [comment]
@baykier no, select all matching still exists

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
