### ISSUE TITLE
Remove filter scrollbar unless overflowed

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#1098]
- Laravel Version:5.7
- Nova Version: 1.2.0
- Browser: Chrome  71.

### Description:

Filter dropdown has scrollbar when height isnt maxed out

Change `overflow-y-scroll` to `overflow-y-auto`

### Steps To Reproduce:
View resource with no filters

![no-scoll-needed-until-height-hit](https://user-images.githubusercontent.com/29180903/49554487-708a6380-f8ca-11e8-85b8-1d0a252f976d.png)

**Comment by dwyer14** [comment]
I'm seeing this as well. Nova v1.2.0 and Chrome (Windows) 70.0.3538.110.

**Comment by dkulyk** [comment]
This has been fixed and will be included in the next release.
