### ISSUE TITLE
HasOne and MorphOne fields allow the user to create more than one related record

### ISSUE THREAD

**Issue by jnorms** [laravel/nova-issues#1099]
- Laravel Version: 5.7.15
- Nova Version: 1.2.0
- PHP Version:

### Description:
When using the HasOne and MorphOne fields it should be prohibited to add another record, starting from the presumption that we should only have one record.

### Steps To Reproduce:

1 - Add a HasOne or MorphOne field and click on "Create Resource"

2 - When filling in the fields click on "Create & Add Another"

And you will see that it is allowed to add another record

**Comment by wemersonrv** [comment]
Yep. In nova 2.0.3 It happens with me too.

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
