### ISSUE TITLE
Gravatar for related model

### ISSUE THREAD

**Issue by antonkomarev** [laravel/nova-issues#11]
Gravatar generates local link to avatar when trying to resolve email attribute via closure.

```php
Gravatar::make('Avatar', function () {
    return $this->user->email;
}),
```

Current output:
`http://localhost:8000/storage/my@email.com`

**Comment by devmsh** [comment]
I don't know what is your exact use case, but here is a quick solution

In the related resource
```
     Gravatar::make('Avatar', 'user_photo'),
```

In the related model 
```
public function getUserPhotoAttribute()
{
    return $this->user->email;
}
```

Don't miss to add `User` to the `with` array to prevent n+1 query problem

**Comment by davidhemphill** [comment]
This is a good solution. :-)
