### ISSUE TITLE
[Feature Request] Grouping table head

### ISSUE THREAD

**Issue by rodrigore** [laravel/nova-issues#1102]
It would be cool to have grouping table head, something like this:

![screen shot 2018-12-06 at 14 18 31](https://user-images.githubusercontent.com/1557305/49600383-daa21780-f961-11e8-8e68-f74eb27ae838.png)

**Comment by dillingham** [comment]
I made something for a similar need
https://github.com/dillingham/nova-grouped-field
Doesn’t add separate headers though.

**Comment by albalooshi** [comment]
@dillingham Awesome package, I was looking for something like this few days ago at novapackages.com but couldn't find it, Why don't you submit it there?

**Comment by dillingham** [comment]
@albalooshi thanks :) wanted to catch any bugs while using it in my own project first. Will put it on there soon

**Comment by davidhemphill** [comment]
I think there are better solutions to this...one being creating a custom field that shows multiple items per line. The grouped header just looks bad too.
