### ISSUE TITLE
->alwaysShow() on a Textarea should format the display properly

### ISSUE THREAD

**Issue by fbingha** [laravel/nova-issues#1103]
When using ->alwaysShow() on a Textarea, the Display view does not display the formatting. I suggest adding something that will display carriage returns and white space such as the white-space:pre css.

**Comment by ceejayoz** [comment]
I'd think you'd want to use `displayUsing` for this - run it through `nl2br` or something. Nova shouldn't make guesses about how it's supposed to be displayed - for all it knows, you could be running it through a Markdown/BBCode processor on the front-end.

**Comment by fbingha** [comment]
It's a class suggestion, it isn't changing the output. You can still do whatever you want with your Markdown/BBCode processor.
