### ISSUE TITLE
Checkbox checked by default

### ISSUE THREAD

**Issue by larsjanssen6** [laravel/nova-issues#1105]
Hi,

I don't know if this is already possible but can checkboxes be checked by default?

Something like:

```
 Boolean::make('Actief', 'active')
                ->checked(true);
```

**Comment by larsjanssen6** [comment]
@dkulyk thanks!

**Comment by eugenevdm** [comment]
I tried this - doesn't seem to work for a checkbox. Does work for Select though.

**Comment by mortezarajabi** [comment]
If you need your checkbox be check by default
you can do the following

```
Boolean::make('Active', 'active')
                ->withMeta(["value" => 1])
```

**Comment by dkulyk** [comment]
@mortezarajabi 
This checkbox will be checked always.
No need to give bad tips.

**Comment by larsjanssen6** [comment]
@dkulyk not true.

**Comment by dkulyk** [comment]
On edit view checkbox will be checked always.

**Comment by larsjanssen6** [comment]
@dkulyk yes but on create not that's why @mortezarajabi is saying this.

**Comment by vguerrerobosch** [comment]
Hi there,

What is working for me is
```php
Boolean::make('Active')
    ->withMeta(['value' => $this->active ?? true])
```

**Comment by gekkedev** [comment]
If anyone is still looking, this package does pretty much the same as @vguerrerobosch suggested:
https://github.com/inspheric/nova-defaultable-fields

**Comment by scofieldmikel** [comment]
`Boolean::make('Active')->default(function ($request) {
                return true;
            }),`
