### ISSUE TITLE
BelongsTo Dropdown label multiple values

### ISSUE THREAD

**Issue by larsjanssen6** [laravel/nova-issues#1106]
Hi,

I don't know if this is already possible but couldn't find it in the docs. Also contacted
Nova support but got no reaction. 

I have a `BelongsTo` dropdown where I would like to have 2 values in the label. 

```php
 BelongsTo::make('Person', 'person', Person::class);
```

Person class:

```php
  /**
     * The single value that should be used to represent the resource when being displayed.
     *
     * @var string
     */
    public static $title = 'firstname';
```
Currently only the Person `firstname` is visible in the dropdown. I would like to 
show the `lastname `aswel. 

So now It shows:

`James`

But I want:

`James Egen`

Is this possible?

**Comment by dillingham** [comment]
https://nova.laravel.com/docs/1.0/search/global-search.html#title-subtitle-attributes
