### ISSUE TITLE
Styling is broken after update

### ISSUE THREAD

**Issue by mdavis1982** [laravel/nova-issues#1107]
- Laravel Version: 5.6.39
- Nova Version: 1.2.0
- PHP Version: 7.2.12

### Description:
The empty resource listing pages have broken CSS after updating to 1.2.0:

<img width="277" alt="image" src="https://user-images.githubusercontent.com/199807/49650444-1ac9ce80-fa24-11e8-8365-02b99c75f3dc.png">

This happens everywhere that these buttons are used.

### Steps To Reproduce:
Go to a page where there is an empty resource.

**Comment by dkulyk** [comment]
Duplicate of #1081
