### ISSUE TITLE
Nova removing user related class from Morph results when displaying results on the user detail

### ISSUE THREAD

**Issue by fbingha** [laravel/nova-issues#1111]
I have set up spatie/laravel-activitylog and integrated it with Nova.

My Morph relationships return various models, one of which is the User model.

When viewing the activity index, everything works correctly, when the model relates to the user, I see the user's name and a link to the user's profile.

Ok, move over to the user detail page where I am trying to just view the activity of the user. I have two Morph relationships setup as fields, one to display the activity caused by the user and one to display the activity done to the user.

All of the results in my set that pertain to the user model will have the user name/link removed from the result set. The other results that aren't User still have their model displayed and linked. So I end up with a table cell missing in my rows that pertain to the user model.

Secondly,  when my result set begins with a model that pertains to the user model, the table does not contain the "Subject" header. Subject refers to the model that the action pertains to.

When my result set begins with a model that is not the user model, the table will have the "Subject" header.

So my suspicion is that when returning a MorphOne field, behind the scenes Nova looks at the first record of the resultset and if it is the same model as the model that is displaying the results on its details page, it removes that field from the result set.

I need to be able to tell the MorphOne field to not exclude model columns that match the model that is displaying the results.

**Comment by fbingha** [comment]
This is the output when the first record doesn't pertain to the User model. You can see that still, a record in the set pertains to the user model so it is missing a column:

![](https://i.ibb.co/1qtZSnM/chrome-2018-12-07-20-45-47.png)

This is the output when the first record does pertain to the User model.

![](https://i.ibb.co/T8t8DC7/chrome-2018-12-07-20-44-58.png)

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
