### ISSUE TITLE
Action::redirect method not working properly

### ISSUE THREAD

**Issue by tufankilicaslan** [laravel/nova-issues#1112]
- Laravel Version: 5.7.16
- Nova Version: 1.2.0
- PHP Version: 7.2.10

### Description:

When running an action (not queued ofcourse) , Action:redirect method not works if you select "Select All Matching" option from resource index. It only shows "Action run sucessfully" message.

If you select "Select All" or some records, then the redirect works.

### Steps To Reproduce:

- Create a simple model / resource file.  you can insert only 1 db record ( number is not important) 
- Create a simple action ( not queued action ofcourse),

```
    /**
     * Perform the action on the given models.
     *
     * @param  \Laravel\Nova\Fields\ActionFields  $fields
     * @param  \Illuminate\Support\Collection  $models
     * @return mixed
     */
    public function handle(ActionFields $fields, Collection $models)
    {
        return Action::redirect("https://www.google.com");
    }
```
- On resource index select "Select All Matching" and try to run Action.

![screen-shot2](https://user-images.githubusercontent.com/701360/49688229-e6d3d380-fb1f-11e8-98e0-2824d4ded1b0.png)
![screen-shot1](https://user-images.githubusercontent.com/701360/49688230-e6d3d380-fb1f-11e8-9baf-ebec35d9f8d0.png)

**Comment by webhealer** [comment]
This may have a relation with the issue : https://github.com/laravel/nova-issues/issues/1113

**Comment by webhealer** [comment]
@dkulyk  thanks for the information,  that worked for me.

**Comment by dkulyk** [comment]
It works from v1.3.2. Result from last chunk will be passed to frontend. Also you can handle all results in `handleResults` and return one result.
