### ISSUE TITLE
date field must cast to 'date' in eloquent model with a mysql date field

### ISSUE THREAD

**Issue by Gil-1** [laravel/nova-issues#1114]
- Laravel Version: 5.7.15
- Nova Version: 1.2.0
- PHP Version: 7.2.12

### Description:

When wanting to display a date (not a datetime) field I have the following error 
```sh
date field must cast to 'date' in eloquent model
```

I already posted in laracasts nova's channel but there is no solution right now
[https://laracasts.com/discuss/channels/nova/date-field-must-cast-to-date-in-eloquent-model-and-it-is](https://laracasts.com/discuss/channels/nova/date-field-must-cast-to-date-in-eloquent-model-and-it-is)

### Steps To Reproduce:

I cast the date fields as this in the eloquent model :

```php
protected $dates = [
        'created_at' => 'datetime:Y-m-d H:i:s',
        'updated_at' => 'datetime:Y-m-d H:i:s',
        'deleted_at' => 'datetime:Y-m-d H:i:s',
        'billed_at' => 'date:Y-m-d',
        'payed_at' => 'date:Y-m-d',
        'due_date' => 'date:Y-m-d',
    ];
```

I also tested 

```php
protected $casts = [,
        'billed_at' => 'date',
        'payed_at' => 'date',
        'due_date' => 'date',
    ];
```

- `created_at`, `updated_at` and `deleted_at` are stored as TIMESTAMP (no issue)
- `billed_at`, `payed_at` and `due_date` are stored as DATE in Mysql

In my Nova Resource, if I use the Date field I have the error
```sh
date field must cast to 'date' in eloquent model
```

And this is how the fields are set

```php
Date::make('Billed At', 'billed_at'),
Date::make('Payed At', 'payed_at'),
Date::make('Due Date', 'due_date'),
```

**Comment by dkulyk** [comment]
In the `dates` field must be specified only property names:
```php
protected $dates = [
    'billed_at', 'payed_at', 'due_date'
]
```

But `casts` must be work.

**Comment by Gil-1** [comment]
I just tried and that don't work.

Here is what I tried

```php
protected $casts = [
        'amount' => 'float(10,2)',
        'reference' => 'integer',
        'billed_at' => 'date',
        'payed_at' => 'date',
        'due_date' => 'date',
    ];
    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];
```

**Comment by bonzai** [comment]
I can't confirm.

## Migration

```php
Schema::create('users', function (Blueprint $table) {
    $table->increments('id');
    $table->date('premium_expired_at')->nullable();
    $table->timestamps();
});
```

## Model

```php
class User extends Model
{
    protected $fillable = ['premium_expired_at'];
    protected $casts = ['premium_expired_at' => 'date'];
}
```

## Resource

```php
class User extends Resource
{
    public static $model = \App\User::class;

    public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
            Date::make('Subscription', 'premium_expired_at')->nullable(),
        ];
    }
}
```

**Comment by dkulyk** [comment]
Maybe you used mutators for this fields. Attribute casting doesn't work with mutators.

**Comment by Gil-1** [comment]
That was it. I used mutators and that messed everything.
Thank you !

**Comment by GingerNinjaNicko** [comment]
I came across this issue whilst working on some data importers.
I wanted to default the value of published_at to the value of created_at and I found that you can use mutators providing you return a Carbon instance like so:

```php
public function getPublishedAtAttribute($value)
{
    return \Carbon\Carbon::create($value ?? $this->attributes['created_at']);
}`
