### ISSUE TITLE
DefaultField width customisation

### ISSUE THREAD

**Issue by maslauskas** [laravel/nova-issues#1115]
Can there be an option to set default field width to full width by default? Seems to me that there is unused space in forms, and the buttons don't align to the fields:

![image](https://user-images.githubusercontent.com/12841532/49723965-ded77900-fc70-11e8-8036-c44a82c4a399.png)

Or at least provide documentation how to change this behaviour without creating custom fields for each input type. Thanks.

**Comment by davidhemphill** [comment]
We're not going to provide an option for this at this time. Arbitrarily-long fields look awkward. Remember we had a highly-regraded designer on the project. 😄

**Comment by davidhemphill** [comment]
If you want, you can create a component in a tool that overrides `default-field` with the width you want.
