### ISSUE TITLE
Disable "Another user has updated this resource..."

### ISSUE THREAD

**Issue by Enmaboya** [laravel/nova-issues#1117]
Already known error.
'Another user has updated this resource since this page was loaded. Please refresh the page and try again. '
The time on the server changed and config changed, nothing helps.
I'm fine, but a person with a different time zone has this error.

Can I disable this check completely? Those. in any case, edit the value regardless of the time?

**Comment by Youniteus** [comment]
I guess you can disable it completely bij always returning false in the function modelHasBeenUpdatedSinceRetrieval in "nova/src/Http/Controllers/ResourceUpdateController.php", though that's just a hacky fix that could cause overwriting issues.

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
