### ISSUE TITLE
Eager Loading not working with BelongsTo

### ISSUE THREAD

**Issue by SeoFood** [laravel/nova-issues#112]
Resource:

```php
public static $with = [ 'address'];

public function fields(Request $request)
{
  BelongsTo::make('Address')->searchable(),
}
```

Result:

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/2766011/44574474-cb6bd500-a789-11e8-8400-811f1aadd473.png">

If I use computed fields manually its working.

**Comment by Quinndark** [comment]
I had the same problem.

**Comment by Livijn** [comment]
+1

**Comment by urtzi88** [comment]
+1

**Comment by ragingdave** [comment]
This is also found on morphTo as well

**Comment by taylorotwell** [comment]
I need you to describe your resource / table structure a bit more. Your code snippet is really out of context so it's hard for me to tell how to recreate things.

**Comment by BengtHagemeister** [comment]
I have a simulier issue with the following output from debugbar:

Page URL: `http://nova.test/resources/coupling-equipments?coupling-equipments_page=2`

API URL: `http://nova.test/nova-api/coupling-equipments?search=&filters=&orderBy=&orderByDirection=desc&perPage=25&trashed=&page=2&viaResource=&viaResourceId=&viaRelationship=&relationshipType=`


<img width="1383" alt="bildschirmfoto 2018-09-23 um 17 13 59" src="https://user-images.githubusercontent.com/30391176/45929586-19742400-bf54-11e8-9a53-3f94d4e9abaa.png">


**Nove Resource CouplingEquipment:**

```php

class CouplingEquipment extends Resource {
 
     ....

     public static $with = ['couplingSize'];

     public function fields(Request $request)
         {
             return [
                 BelongsTo::make('Kupplung', 'couplingSize', CouplingSize::class),
             ];
         }

     ....

}
```

**Nova Resource CouplingSize:**

```php

class CouplingSize extends Resource {

     ....

     public function fields(Request $request)
     {

          return [
               HasMany::make('couplingEquipment'),
          ]
     }

     ....

}

```


**Model CouplingEquipment:**

```php

class CouplingEquipment extends Model {

     public function couplingSize()
         {
             return $this->belongsTo(CouplingSize::class);
         }
}

```

**Model CouplingSize:**

```php

class CouplingSize extends Model {

     public function couplingEquipment()
    {
        return $this->hasMany(CouplingEquipment::class);
    }

}

```


**Table structure:**

- coupling_equipment
   - id (int)
   - coupling_size_id (int) -> relationship to coupling_size

- coupling_sizes
   - id (int)

**Comment by dwyer14** [comment]
We're seeing this issue as well. One note, it doesn't appear to be an issue on initial index page-load. 

For example, we have a School model & resource, that's a simple BelongsTo relationship with StudentOrganization. There are ~250 Schools and ~250 StudentOrganizations. When visiting the Schools resource page initially (`/resources/schools`), it loads quickly, without unnecessary queries (analyzing with Laravel Debugbar).

When that URL gains any parameter, though, it starts running several hundred queries, many duplicate. This includes pagination, filter, sorting and search parameters. Hope that helps.

**Comment by abordage** [comment]
> When that URL gains any parameter, though, it starts running several hundred queries, many duplicate. This includes pagination, filter, sorting and search parameters. Hope that helps.

+1, same problem

**Comment by mikebouwmans** [comment]
I'm actually having the same problem, but for me all pages won't load anymore when eager loading with all relations.

**Comment by markgp** [comment]
We made the following changes to `/nova/src/Fields/BelongsTo.php` which solved the issue for us.

You still need to [define your relationships](https://nova.laravel.com/docs/1.0/resources/#eager-loading) using the `$with` property, obviously.

```diff
--- a/BelongsTo.php     2018-10-26 13:54:48.552145700 +1100
+++ b/BelongsTo.php     2018-10-26 13:53:20.778856800 +1100
@@ -144,7 +144,7 @@
      */
     public function resolve($resource, $attribute = null)
     {
-        $value = $resource->{$this->attribute}()->withoutGlobalScopes()->first();
+        $value = $resource->{$this->attribute};

         if ($value) {
             $this->belongsToId = $value->getKey();
```

**Comment by abordage** [comment]
@markgp , https://github.com/laravel/nova-issues/issues/246#issuecomment-420939582

**Comment by jasonlav** [comment]
Also able to verify issue. Belongs to will eager load and proceed to query each relationship.

**Comment by dillingham** [comment]
Just noticed this also, any updates?
```php
$value = $resource->{$this->attribute}()->withoutGlobalScopes()->first();
```
being changed to the following does seem to work as stated above
```php
$value = $resource->{$this->attribute};
```

**Comment by huoding** [comment]
+1, I have the same question.

**Comment by dkulyk** [comment]
PR was sent to upstream.

**Comment by fedeisas** [comment]
@dkulyk ETA for the next release, please. Thanks.

**Comment by Quinndark** [comment]
您好，邮件已收到，谢谢。。
