### ISSUE TITLE
add event listener to reload resources in index view

### ISSUE THREAD

**Issue by plakhin** [laravel/nova-issues#1120]
It would be nice to have 
```
        Nova.$on('refresh-resources', () => {
            this.getResources()
        })
```
this listener in `Index.vue` to be able to refresh resource index from custom cards.

**Comment by bayareawebpro** [comment]
Second, there's needs be some common API's available so we can work with parent views.

**Comment by tylernathanreed** [comment]
I could definitely use this too. I'm currently having to write code like this:

```javascipt
/**
 * Returns the closest resource index in the parent tree.
 *
 * @return {VueComponent|null}
 */
getResourceIndex() {

    // Walk up the parent tree
    for(let parent = this.$parent; typeof parent !== 'undefined'; parent = parent.$parent) {

        // Return the eparent if it is a resource index
        if(parent.$options.name === 'resource-index') {
            return parent;
        }

    }

    // Failed to find resource index
    return null;

},

/**
 * Updates the index resources.
 *
 * @return {void}
 */
updateIndexResources() {

    // Determine the resource index
    var index = this.getResourceIndex();

    // Stop if we couldn't find the resource index
    if(index == null) {
        return;
    }

    // Call the resource updater
    index.getResources();

},
```

It gets the job done, but boy does that feel hacky.

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by zagreusinoz** [comment]
I show or hide resources in my policy based on the data, e.g. if the user has a current account field then show certain resources, or hide if that field is null.

The trouble is, when deleting the current account, I haven't found a way to refresh the whole page to refresh the resources are available.  I tried redirecting from an observer, however I guess that's only redirecting the ajax call and doesn't do anything on the main interface.

Would be good to be able to call a redirect or refresh from within an ajax call.

**Comment by nickkuijpers** [comment]
Hi,

Any updates on this? I would love to have a feature to listen to events to refresh the page. I have a toolbar tool which needs to listen to the delete event of a record. Any ideas?

**Comment by davidhemphill** [comment]
Would welcome a PR that adds this. Otherwise it's down on the list of things to get done. Thanks!

**Comment by phoenixg** [comment]
I want this feature added too, please don't close this feature request.

**Comment by encomienda** [comment]
Silly solution but works for me 😄 
`this.$parent.$parent.$parent.$parent.$parent.$parent.getResources()`
But hoping for the event listener in Index.vue 😄

**Comment by phoenixg** [comment]
@encomienda Why six `$parent` ?

**Comment by nickkuijpers** [comment]
Ah nice haha. Maybe we can go from the top to the bottom instead? Target parent so we have a fixed position from the top as the bottom could change very easily if for example we create a component in a component.

**Comment by encomienda** [comment]
Why six? because the index component of nova is at 6 level from the fields components. So after that we can access the index methods, state, etc.

**Comment by Dontorpedo** [comment]
instead of reloading the whole index it would be nice to reload just the changed row..

**Comment by Pamposgsk** [comment]
> Silly solution but works for me 😄
> 
> `this.$parent.$parent.$parent.$parent.$parent.$parent.getResources()`
> 
> But hoping for the event listener in Index.vue 😄

Hi i tried your solution but getting error “cannot read property $parent of unfifined

**Comment by tanmuhittin** [comment]
I prepared a Nova Card for that. It is not a fancy solution but it works :)

https://github.com/tanmuhittin/nova-reload-resources

https://github.com/tanmuhittin/nova-reload-resources/blob/f27da9507a97696b7aca0e9bd7e5afd3001f0891/resources/js/components/Card.vue#L21

It basicly changes and reverts index filters so that getResources() method is fired because it watches for changes in index filters via $store

<img src="http://muhittintan.com/nova-reload-resources.png" alt="nova-reload-resources" />

**Comment by killua99** [comment]
thanks @tanmuhittin I was looking for something like this to be use on the card. 🤔 Would be nice to point this more on documentation or something (on a Vue index snippet or something)

**Comment by vesper8** [comment]
> Would welcome a PR that adds this. Otherwise it's down on the list of things to get done. Thanks!

@davidhemphill wish you would have merged https://github.com/laravel/nova/pull/944. The auto-polling is a nice addition but it doesn't quite do what was requested here which is to allow us to emit a resource-refresh request from anywhere in the code, on demand.. this is what I need and the auto-polling does not address this.. and it creates the potential to do lots of unnecessary refreshes
