### ISSUE TITLE
[Bug] If a model's array representation does not contain a correct ID key/value pair, Nova 404s after creating the resource

### ISSUE THREAD

**Issue by corazzi** [laravel/nova-issues#1124]
- Laravel Version: 5.7.15
- Nova Version: 1.2.0
- PHP Version: 7.2

### Description:
If you define a custom `toArray()` array in a model but don't explicitly include `'id' => $this->id`, then Nova will 404 after creating the resource because it cannot determine the model's ID.

If you include (for example) `'id' => 0` in the array representation, it will attempt to redirect you to `/nova/resources/resource_name/0`, indicating it is indeed using this value to determine the model's ID for the redirect.

### Steps To Reproduce:

* Create a model and associated table

* Create the associated Nova resource

* In the model, add a `toArray()` method that does NOT include an `id` index
  * Alternatively, include an `id` index but make the value obviously incorrect

* Create a resource and click "Create <Resource>" (not "Create & Add Another")

* Nova will 404

**Comment by paras-malhotra** [comment]
Created a PR in the Nova repo to fix this.

**Comment by dkulyk** [comment]
This has been fixed and will be included in the next release.
