### ISSUE TITLE
Cannot close Action popup on Firefox

### ISSUE THREAD

**Issue by webhealer** [laravel/nova-issues#1125]
- Laravel Version: 5.7.16
- Nova Version: 1.2.1
- PHP Version: 7.2.10
- Browser: Firefox 63.0.3 (64-bit For Ubuntu)

### Description:

After last nova update,  can not close the "action" popup, it throws a "ReferenceError" if you click "cancel" button or outside the popup window.  

```
ReferenceError: "event is not defined"
	handleClose http://tam.local/vendor/nova/app.js?id=f1809770ce8acfb0a3ac:1:424794
	Ge http://tam.local/vendor/nova/vendor.js?id=9acde073472c5725344b:1:810570
	filter http://tam.local/vendor/nova/vendor.js?id=9acde073472c5725344b:1:855933
	handleClose http://tam.local/vendor/nova/app.js?id=f1809770ce8acfb0a3ac:1:424750
	e http://tam.local/vendor/nova/vendor.js?id=9acde073472c5725344b:1:485986
	emit http://tam.local/vendor/nova/vendor.js?id=9acde073472c5725344b:1:505222
	close http://tam.local/vendor/nova/app.js?id=f1809770ce8acfb0a3ac:1:88155
	i http://tam.local/vendor/nova/vendor.js?id=9acde073472c5725344b:1:1006110
```

### Steps To Reproduce:

- Try to run an action and close the window

![screenshot from 2018-12-13 00-43-52](https://user-images.githubusercontent.com/701360/49901932-9b992800-fe73-11e8-8333-4ca71ecd1196.png)

**Comment by webhealer** [comment]
I think i fixed it from the nova core code. If its helps here is the solution: @bonzai @davidhemphill 

**Modal.vue** : ( need to add "e" parameter for method and emit call)
```
        close(e) {
            this.$emit('modal-close',e)
        },
```
**ConfirmActionModal.vue** ( need to add "event" parameter for method "handleClose")

`handleClose(event)`

**Comment by dkulyk** [comment]
PR was sent to upstream.

**Comment by dkulyk** [comment]
This has been fixed and will be included in an upcoming release.
