### ISSUE TITLE
Error create relationship with grandchild

### ISSUE THREAD

**Issue by rexliu0715** [laravel/nova-issues#1127]
- Laravel Version: 5.7.17
- Nova Version: 1.2.1
- PHP Version: 7.2

### Description:
In Nova Orders detail page has many packages(inventories). used by belongsToMany link with relationships. it was no error on detail page. It occurs below error msg after I create "Create Packages" in detail page.

Error: 
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'inventories.transaction_id' in 'where clause' (SQL: select * from `inventories` where `inventories`.`transaction_id` is null limit 1)
```

3 tables, 

Order table
=========
- id
- receipt_id

Transaction table
============
- id
- receipt_id
- transaction_id

Inventory table
============
- id
- packageable_id (transaction_id)
- packageable_type (transaction)

### Steps To Reproduce:

Order Model (Model)

```php
public function packages()
{
    return $this->belongsToMany('App\Models\Inventory', 'transactions', 'receipt_id', 'transaction_id', 'receipt_id', 'packageable_id');
}
```

Order Resource (Nova Resource)

```php
function fields (Request request){
      return [HasMany::make('Packages', 'packages', Inventory::class)]
}
```

**Comment by bonzai** [comment]
You're using the wrong relationship field in your resource. Replace `HasMany` with `BelongsToMany`.

**Comment by rexliu0715** [comment]
there are no receipt_id in inventories table, is it use hasManyThrough will be better?

order has many transactions then transaction has many inventories.

I try this code on Order model. it was work on order detail page and show inventories record. but it does not work on after I click the "Create Inventory" button..

    public function packages()
    {
        return $this->hasManyThrough('App\Models\Inventory', 'App\Models\Transaction', 'receipt_id', 'packageable_id', 'receipt_id', 'transaction_id');
    }

Same error:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'inventories.transaction_id' in 'where clause' (SQL: select * from `inventories` where `inventories`.`transaction_id` is null limit 1)

my inventory model

    public function packageable()
    {
        return $this->morphTo(null, null, null, 'transaction_id');
    }

when I open inventory detail. it was success if the record has package_type and package_id value. but fail on pacakge_type and package_id was null.

It make inventory list page error.

**Comment by rexliu0715** [comment]
I found that change transaction_id to id, everything was smooth with no error. I can not use transaction_id as a custom ownerkey

**Comment by davidhemphill** [comment]
Closing as it seems you've solved this.

**Comment by rexliu0715** [comment]
> Closing as it seems you've solved this.

No. I still can not use transaction_id for the ownerkey in transaction model. it makes error:

> SQLSTATE[42S22]:

 Column not found: 1054 Unknown column 'inventories.transaction_id' in 'where clause' (SQL: select * from `inventories` where `inventories`.`transaction_id` is null limit 1)
