### ISSUE TITLE
ActionEvent::defaultAttributes() assumes user is an Eloquent model instance

### ISSUE THREAD

**Issue by StanAngeloff** [laravel/nova-issues#1130]
- Laravel Version: 5.7.12
- Nova Version: 1.2.1
- PHP Version: 7.2.11

### Description:

The `Laravel\Nova\Actions\ActionEvent::defaultAttributes()` method incorrectly assumes the user associated with the request is an Eloquent model by calling `getKey()`.

The correct method is `getAuthIdentifier()` which has been used throughout the `ActionEvent` class already in a couple of places: `forAttachedResourceUpdate`, `forSoftDeleteAction`, `forResourceDetach`.

### Steps To Reproduce:

1. Install Nova in a Laravel installation where the user is not an Eloquent model.
2. Register a custom action for any Laravel Nova resource
3. Attempt to call registered action

This results in a `Call to undefined method App\Entities\ForeignUser::getKey()` exception.

### Patch

```diff
diff --git a/nova/src/Actions/ActionEvent.php b/nova/src/Actions/ActionEvent.php
index 416c523..acc557f 100644
--- a/nova/src/Actions/ActionEvent.php
+++ b/nova/src/Actions/ActionEvent.php
@@ -218,7 +218,7 @@ class ActionEvent extends Model
     {
         return [
             'batch_id' => $batchId,
-            'user_id' => $request->user()->getKey(),
+            'user_id' => $request->user()->getAuthIdentifier(),
             'name' => $action->name(),
             'actionable_type' => $request->actionableModel()->getMorphClass(),
             'target_type' => get_class($request->model()),
```

**Comment by bonzai** [comment]
This has been fixed and will be included in the next release.
