### ISSUE TITLE
[Bug] UI Allows you to keep adding duplicate relationships

### ISSUE THREAD

**Issue by OwenMelbz** [laravel/nova-issues#1131]
- Laravel Version: 5.7.17
- Nova Version: 1.2.1
- PHP Version: 7.2.10

### Description:
When defining a relationship such as 

```php
BelongsToMany::make('User Group', 'groups', UserGroup::class),
```

The "Attach User Group" dropdown menu allows you to repeatedly pick the same relationship rather than only showing the unattached.

![al_shirawi](https://user-images.githubusercontent.com/1094740/50007184-06e41680-ffa8-11e8-899a-73bd26561aba.png)

### Steps To Reproduce:
Define a relationship
Attach it
Attach it again
Attach it again
Attach it again
Implode

**Comment by dillingham** [comment]
Could make a scope

**Comment by dkulyk** [comment]
You can check it in the policy and disallow to attach some records.

**Comment by davidhemphill** [comment]
Not a bug. There are valid use cases for having duplicate relations in apps. Use validation to avoid having duplicates.

**Comment by OwenMelbz** [comment]
@davidhemphill If thats the case, you would assume that the dev console wouldn't throw up errors when you do it...

![laravel](https://user-images.githubusercontent.com/1094740/50179064-04622380-02fe-11e9-8b64-88638d65f495.jpg)

**Comment by dillingham** [comment]
I would assume a syncing behavior by default or an option `->sync()`

> Syncing Associations
You may also use the sync method to construct many-to-many associations. The sync method accepts an array of IDs to place on the intermediate table. Any IDs that are not in the given array will be removed from the intermediate table. So, after this operation is complete, only the IDs in the given array will exist in the intermediate table:

**Comment by dillingham** [comment]
@davidhemphill might be nice to add a ->unique() flag, more often than not ive wanted that

For anyone here looking for a workaround

```php

// Assuming a team_user
// Not wanting a user to be added to a team more than once
// Scope the relatable within your user resource 

// I needed it for more than 1 table
// so $table is dynamically retrieved 
// feel free to replace with "team_user" etc

public static function relatableQuery(NovaRequest $request, $query)
{
    $query = parent::relatableQuery($request, $query);

    $parent = str_singular(request()->segment(2));

    if(in_array($parent, ['team'])
    {
        $parentId = request()->segment(3);

        $table = app("App\\$parent")->users()->getTable(); 

        $query->whereRaw("id NOT IN (SELECT user_id from $table WHERE {$parent}_id = $parentId)");
	return $query;
    }
}

**Comment by bradenkeith** [comment]
@davidhemphill Definitely a use case for having multiple attachments, however it does have some problematic issues in the implementation, mainly:

- It doesn't seem like we can add validation rules to the BelongsToMany field, it would most likely require some hacking on the model instance like @dillingham shows above. A simple rules() method will not alter the creation functionality.

- Deleting an attachment on belongsToMany will delete all relationships that have the corresponding ID's in common. IE: Attachment for ID1->ID2, ID1->ID2... Detach one of them and it will detach both.

Shall we keep this issue open until resolved or open a separate? cc @dkulyk

**Comment by OwenMelbz** [comment]
@themsaid do you have any ideas about what we could do here?

**Comment by christophrumpel** [comment]
I made it work with overriding the `relatableQuery` like mentioned above in my related nova resources. (product in my case.

```
public static function relatableQuery(NovaRequest $request, $query)
    {
        $query = parent::relatableQuery($request, $query);

        if (request()->segment(2) == 'events') {

            $event_id = request()->segment(3);

            $query->select('products.*');

            $query->whereRaw("products.id NOT IN (SELECT product_id from event_product WHERE event_id = $event_id)");
        }

        return $query;
    }
```

Still, a problem is that you will end up with an empty select field after all items have been used. Here it would be great if we can have a solution that points out when there are no items left.

**Comment by dillingham** [comment]
@christophrumpel technically, I made it work :)

**Comment by christophrumpel** [comment]
@dillingham haha right, you did. Now I also noticed you are already in the discussions :-) Again, thanks!

**Comment by dkulyk** [comment]
```php
    public static function relatableGroups(NovaRequest $request, $query)
    {
        $key = $query->getModel()->getQualifiedKeyName();
        
        return $query->whereNotIn($key, function ($subQuery) use ($key, $query, $request) {
            $subQuery->fromSub(
                $request->findModelOrFail()->{$request->field}()->select($key)->getQuery(), 'tmp'
            );
        });
    }
```

**Comment by dillingham** [comment]
^ he knows the framework

**Comment by christophrumpel** [comment]
Nice solution 👍

**Comment by ppisecky** [comment]
Here's another tip. When filtering attachable resources Nova first looks up a `relatable{Mode}` function on the parent model and if not found it will call `relatableQuery`. So if your teams can have many members but your members cannot belong to the same club multiple times you should be able to do this on the `Team` resource:

```php
    /**
     * Build a "relatable" query for the given resource.
     *
     * This query determines which instances of the User model may be attached to the Team.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public static function relatableUser(NovaRequest $request, $query)
    {
        $team= \App\Team::find($request->resourceId);
        $memberIds = $team->members->pluck('id');

        return $query->whereNotIn('id', $memberIds);
    }
```

Here's a more advanced use-case. Each `Project` has several `Tasks`s. Each `Task` can have many related subtasks. But tasks can be attached according to some rules:

- related tasks have to be from the same project
- you cannot attach a task to itself
- cannot already be attached to the same task

So on the `Task` resource you can do:
```php
    public static function relatableTasks(NovaRequest $request, $query)
    {
        $task = \App\Task::find($request->resourceId);
        $relatedTaskIds = $task ->relatedTasks->pluck('id');

        return $query->where('project_id', $task->project_id) //restrict to same project
            ->where('id', '!=', $task->id) // don't allow attaching to self
            ->whereNotIn('id', $relatedTaskIds); //filter already attached tasks
    }
```

Lastly you might want to prevent displaying of the `Attach` resource button if there is for example only task on the project in the example above (due to the constraints there is nothing to attach as you cannot attach a task to itself). You can use authorization to handle this in a `TaskPolicy`:

```php
    /**
     * Determine whether the user can attach any Task
     *
     * @param  \App\User $user
     * @param  \App\OrderItem $orderItem
     * @return mixed
     */
    public function attachAnyTask(User $user, Task $task) {
        if ($task->project->tasks()->count() <= 1) {
            return false;
        }

        return null;
    }
```

**Comment by bakerkretzmar** [comment]
@ppisecky I'm set up exactly as you suggest:

```
public static function relatablePages(NovaRequest $request, $query)
{
    $page = \App\Page::find($request->resourceId);

    return $query->where('province_id', $page->province_id);
}
```

But the `resourceId` is always null. Am I missing something here?

**Comment by randelsr** [comment]
@bakerkretzmar , late to the game but for Attachable resources, you can use 

`$request->viaResourceId`

**Comment by OliOnline** [comment]
> @davidhemphill Definitely a use case for having multiple attachments, however it does have some problematic issues in the implementation, mainly:
> 
>     * It doesn't seem like we can add validation rules to the BelongsToMany field, it would most likely require some hacking on the model instance like @dillingham shows above. A simple rules() method will not alter the creation functionality.
> 
>     * Deleting an attachment on belongsToMany will delete all relationships that have the corresponding ID's in common. IE: Attachment for ID1->ID2, ID1->ID2... Detach one of them and it will detach both.
> 
> 
> Shall we keep this issue open until resolved or open a separate? cc @dkulyk

Anyone being able to fix this issue ? Laravel 8 and Nova 3 still experiencing this issue..
