### ISSUE TITLE
Switchable Language

### ISSUE THREAD

**Issue by robov** [laravel/nova-issues#1132]
In my setup I want to have a switchable language in the url (en/admin , de/admin etc)
However in the nova config the admin directory is hardcoded to "/admin"
When I change this to "/en/admin" everything works... except the switching ofcourse
I have middleware that switches my other routes, so I could add all nova routes in my routes web.php, but I rather do do that duplication

Any suggesitons ?

**Comment by bonzai** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://larachat.co/).

**Comment by nemrutco** [comment]
+1
