### ISSUE TITLE
ActionEvent assumes wrong user() relationship when custom guard is defined

### ISSUE THREAD

**Issue by chrisbjr** [laravel/nova-issues#1133]
- Laravel Version: 5.7.17
- Nova Version: 1.2.0
- PHP Version: 7.1.22

### Description:
When a custom `NOVA_GUARD` is defined, the `user()` relationship of the `ActionEvent` model returns the wrong model. Upon investigating, the `user()` method assumes the model from the default user guard `config('auth.providers.users.model')`.

### Steps To Reproduce:
1. Create a custom guard in `auth.php` like:

```php
    'guards' => [
        ....
        'backend' => [
            'driver' => 'session',
            'provider' => 'backend_users',
        ],
        ...
```

2. Define user provider in the same file (`auth.php`) like:

```php
'providers' => [
        ...
        'backend_users' => [
            'driver' => 'eloquent',
            'model' => App\BackendUser::class,
        ],
        ...
``` 

3. Tell Nova to use this guard through the `NOVA_GUARD` .env variable like: `NOVA_GUARD=backend`

4. Create a Nova Action and attach the `Actionable` trait to the related model and execute the action.

5. Result: Action Event table will not be able to resolve the user.

### Patch:

Here is my patch to fix it:

```diff
diff --git a/src/Actions/ActionEvent.php b/src/Actions/ActionEvent.php
index 8f7cd60..1a1f6f2 100755
--- a/src/Actions/ActionEvent.php
+++ b/src/Actions/ActionEvent.php
@@ -24,7 +24,10 @@ class ActionEvent extends Model
      */
     public function user()
     {
-        return $this->belongsTo(config('auth.providers.users.model'), 'user_id');
+        // Get the correct provider first
+        $authProvider = config('auth.guards.' . config('nova.guard') . '.provider');
+
+        return $this->belongsTo(config('auth.providers.' . $authProvider . '.model'), 'user_id');
     }
 
     /**

```

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!

**Comment by irisashubin** [comment]
@jbrooksuk  same for v2.0 
why you cannot reopen this issue?

**Comment by kanchanarandika** [comment]
I faced the same issue with v3.8.2 and had to make the following change. Please suggest if there is a better way to do it.

```
Laravel\Nova\Actions\ActionEvent.php

public function user()
    {
        return $this->belongsTo(config('auth.providers.admins.model'), 'user_id');
    }
```

**Comment by vipulasa** [comment]
Created a fresh installation today and experiencing this problem for the first time. @kanchanarandika any luck with a different solution?

**Comment by kanchanarandika** [comment]
@vipulasa nope! I could not find any other way.

**Comment by joostvanhoof** [comment]
This is still there. @jbrooksuk I'm not familiar with the workflow regarding tickets here, but [my ticket describing the same issue](https://github.com/laravel/nova-issues/issues/3032) got the label `bug` and was then closed (recently). Does that mean it's a known bug that will be fixed in a future version?

**Comment by joostvanhoof** [comment]
After some more digging around I found why this issue is still there while the described bug was actually fixed. See the comment in my ticket [here](https://github.com/laravel/nova-issues/issues/3032).
