### ISSUE TITLE
Do not load Nunito font

### ISSUE THREAD

**Issue by webbie** [laravel/nova-issues#1134]
Would be good to change templates to not load Nunito font:
```
<link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">
```

Instead, use default system fonts, like:
```
html, body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
}
```

The reason is that we should allow maximum theme customization. Currently, you can't avoid loading Nunito font, even if it's not used at all.

**Comment by FaridAghili** [comment]
It makes total sense for me.

**Comment by davidhemphill** [comment]
Nunito is the currently the font for the system, and there are no plans to change it. This is why the layout is published, so you can customize this behavior for yourself if you like. 😄

**Comment by msnegurski** [comment]
Since layout is no longer publishable, would be nice to have ability to change font, or at least disable Nunito and use system fonts

**Comment by davidhemphill** [comment]
> Since layout is no longer publishable, would be nice to have ability to change font, or at least disable Nunito and use system fonts

The layout is still publishable in the Orion series.

**Comment by FaridAghili** [comment]
@davidhemphill  
Am I missing something? Is there any series other than "Orion"?

**Comment by davidhemphill** [comment]
That's still the only series.
