### ISSUE TITLE
`date-filter` component rendering as a `select` component

### ISSUE THREAD

**Issue by TonnyORG** [laravel/nova-issues#1135]
- Laravel Version: 5.7.17
- Nova Version: 1.2.1
- PHP Version: 7.2.9

### Description:
Hello guys, I am using a Lens and inside of it I do also have a few filters, 1 of them is a select and the other 2 are dates.

This is what I have in my lens class:
```php
    /**
     * Get the filters available for the lens.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function filters(Request $request)
    {
        return [
            new \App\Nova\Filters\Type,
            new \App\Nova\Filters\FromDay,
            new \App\Nova\Filters\ToDay,
        ];
    }
```

And the classes `FromDay` and `ToDay` extends of `DateFilter` class, the only method inside of them is `apply()` so the $component property should extend as `date-filter` however is rendering a select instead of a date picker.

### Steps To Reproduce:
1. Create a Lens through `php artisan nova:lens Test`
2. Create a drop down Filter `php artisan nova:filter Type`
3. Create a Filter  through `php artisan nova:filter FromDay --date`
4. Create a Filter  through `php artisan nova:filter ToDay --date`
5. Assign these 3 filters to the Lens.

**Comment by TonnyORG** [comment]
Actually NVM, seems like it's working fine now (after closing the browser and open a new session).

**Comment by beausif** [comment]
For anyone else that stumbles across this issue. 
My issue was that I had not correctly published the updated files. 
Running the publish command : `php artisan nova:publish` fixed this for me.

**Comment by bryangruneberg** [comment]
> For anyone else that stumbles across this issue.
> My issue was that I had not correctly published the updated files.
> Running the publish command : `php artisan nova:publish` fixed this for me.

Fixed worked for me as well - thanks @beausif
