### ISSUE TITLE
Error: Eager Loading

### ISSUE THREAD

**Issue by rexliu0715** [laravel/nova-issues#1139]
- Laravel Version: 5.7.17
- Nova Version: 1.2.1
- PHP Version: 7.2

### Description:

Goblal search or resource search error: 

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'item.sku' in 'where clause' (SQL: select * from `inventories` where (`inventories`.`id` like %asdf% or `item`.`sku` like %asdf%) and `inventories`.`deleted_at` is null order by `inventories`.`id` desc limit 5)

### Steps To Reproduce:

inventory resource:

    public static $search = [
        'id',
        'item.sku'
    ];

    public static $with = ['item'];

    public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),

            BelongsTo::make('Item')->searchable(),
       ]
    }

inventory model: 

    public function item()
    {
        return $this->belongsTo('App\Models\Item');
    }

**Comment by davidhemphill** [comment]
You cannot currently search relations inside of Nova.

**Comment by rexliu0715** [comment]
@davidhemphill does it have any solution for search relations? thx~

**Comment by dillingham** [comment]
https://novapackages.com/packages/titasgailius/search-relations

That package works nicely

**Comment by rexliu0715** [comment]
thanks~~!!
