### ISSUE TITLE
add action but doesn't show in resource list page

### ISSUE THREAD

**Issue by BruceGujinhe** [laravel/nova-issues#1140]
- Laravel Version: 5.7.*
- Nova Version: 1.2.1
- PHP Version:7.1.3

### Description:
Can't see the action button in the list page of the resource.

### Steps To Reproduce:
- php artisan nova:action EmailAccountProfile
- add some code in the action file
```
    public function handle(ActionFields $fields, Collection $models)
    {
        return Action::message('It worked!');
    }
``` 
- add the action in resource's actions method
```
    public function actions(Request $request)
    {
        return [
            // new DownloadExcel,
            new EmailAccountProfile()
        ];
    }
```

**Comment by davidhemphill** [comment]
Actions are working. Make sure you've selected a resource or provide more information demonstrating the issue.
