### ISSUE TITLE
Waterfall pagination needed for large resource dataset

### ISSUE THREAD

**Issue by phoenixg** [laravel/nova-issues#1141]
Like if I have a table having 1 Billion records, the `count()` is too slow.

**Comment by andrew-belac** [comment]
This is from a long time ago.  But I have just run into this problem.  there are 365000 rows in the table and the database is a staging instance but has 200Gb on AWS RDS MySQL.  But the count(*) query takes a little less than 30 seconds to execute.  But this is deployed on Vapor so the default is 10 seconds to timeout.  But 30 seconds is painfully slow anyway.  I added a scope to the query to used the created_at field. This instantly makes the query lightening.  But then when adding additional filters the query is 30 seconds again.  If your DB has 100000 records in in it people don't need to see the total count. They just need to be able to step through a few pages.  Anything else requires a filter.  So I would really like the ability to remove the total row count.

**Comment by tom-it** [comment]
I agree, we are also facing issues with 300k+ records table, where it's just slowing down the whole experience
