### ISSUE TITLE
My images won't show. 404 error.

### ISSUE THREAD

**Issue by Daveke7** [laravel/nova-issues#1142]
- Laravel Version: 5.7
- Nova Version: 1.21
- PHP Version: 7.1.19

Description: Whenever i try to add a image it won't load, and it won't be displayed.

Steps To Reproduce:
I am using Spatie Media Library, and some Nova Packages. Like this one: https://novapackages.com/packages/infinety-es/nova-filemanager.

In Nova:
<img width="1078" alt="schermafbeelding 2018-12-18 om 09 21 05" src="https://user-images.githubusercontent.com/25744071/50140993-a22a0400-02a6-11e9-999b-fa36f4a1c06f.png">

Console error:
<img width="468" alt="schermafbeelding 2018-12-18 om 09 21 36" src="https://user-images.githubusercontent.com/25744071/50141018-b0782000-02a6-11e9-847c-b6ac14692403.png">

In Model:
<img width="810" alt="schermafbeelding 2018-12-18 om 09 22 02" src="https://user-images.githubusercontent.com/25744071/50141051-bf5ed280-02a6-11e9-97bb-770b6e54ae31.png">

In Filesystems.php:
<img width="605" alt="schermafbeelding 2018-12-18 om 09 22 19" src="https://user-images.githubusercontent.com/25744071/50141076-d7ceed00-02a6-11e9-9e6c-f91f20243974.png">

In Medialibrary.php:
<img width="880" alt="schermafbeelding 2018-12-18 om 09 22 32" src="https://user-images.githubusercontent.com/25744071/50141084-ddc4ce00-02a6-11e9-9d32-3ad426729843.png">

**Comment by dillingham** [comment]
File the issue in the package repository

**Comment by Daveke7** [comment]
This is not a problem with the package because it also happens with the standard image:make

**Comment by bonzai** [comment]
I can't confirm.

Which disk are you using to store images? What's the current and expected URL to the image?

**Comment by bonzai** [comment]
Did you create a symbolic link from `public/media` to `storage/app/media`?

**Comment by Daveke7** [comment]
Hello i changed everything to public and made the symbolic link and now it works like i wanted it to. Thanks!
