### ISSUE TITLE
Filters on related resources are the ones loaded last, not the correct ones

### ISSUE THREAD

**Issue by wfeller** [laravel/nova-issues#1143]
- Laravel Version: 5.7.17
- Nova Version: 1.2.1
- PHP Version: 7.2

### Description:
If I have multiple related resources in my resource, the filters displayed on related resources are the same. The filters shown are the ones loaded last.

### Steps To Reproduce:

In your main resource:

```
    public function fields(Request $request)
    {
        return [
            Text::make('Name'),

            HasMany::make('Relation 1', 'relation_one', RelationOne::class),
            HasMany::make('Relation 2', 'relation_two', RelationTwo::class),
        ];
    }
```

In RelationOne:
```
    public function filters(Request $request)
    {
        sleep(10);
        return [];
    }
```

In RelationTwo:
```
    public function filters(Request $request)
    {
        return [
              new SomeFilter,
        ];
    }
```

For 10 seconds, you'll have SomeFilter on both resources, then no filters anymore on both resources.

**Comment by stu-greenshoots** [comment]
I am suffering the same problem and was just about to open an issue

**Comment by dkulyk** [comment]
@davidhemphill is working on fixing this.

**Comment by dillingham** [comment]
Seems related https://github.com/laravel/nova-issues/issues/1181

**Comment by dillingham** [comment]
Seems like the only workaround is reverting back to 1.1.7 and missing all the latest fixes

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍

**Comment by gavinhoward100** [comment]
Still have this issue in 1.3.2

**Comment by campope** [comment]
I have this issue in 1.3.2 as well.

**Comment by chrisbjr** [comment]
Still not fixed in 2.0.0...........

**Comment by aozen** [comment]
Still waiting fix.

**Comment by threeaccents** [comment]
@davidhemphill I'm also having the same issues in 2.0. Maybe reopening this issue is not a bad idea.
