### ISSUE TITLE
Add possibility to has non lower case resource names when there is no results in index.

### ISSUE THREAD

**Issue by janicerar** [laravel/nova-issues#1144]
For example "No LDAP user matched the given criteria." LDAP can be the upper case now there is no possibility to make this uppercase because is converted to lowercase in Vue competent.

**Comment by davidhemphill** [comment]
Sorry, but we are unable to debug your issue without a reproducible code example. Once you provide that we can open this up again.

**Comment by pxlrbt** [comment]
@davidhemphill 
In the Vue component `laravel\nova\resources\js\views\Update.vue` inside function `updateResource()` (line 149) the resource name is transformed to lowercase. Similiar in all other messages referencing the resource. Therefore abbreviations like "LDAP" are lowercase. This also affects languages like German where nouns are capitalized.

**Comment by marcreichel** [comment]
@davidhemphill 
I would also need non lower case resource names as like @pxlrbt already mentioned in germany we have capitalized nouns and "Kein(e) benutzer gefunden." just looks weird...

**Comment by michaelklopf** [comment]
I just came across this behaviour too.

**Comment by pxlrbt** [comment]
@davidhemphill Would you please reopen this issue?

**Comment by jbrooksuk** [comment]
The solution here is in your custom language file to do:

```json
{
    "The resource :resource has been created!": "Die Ressource :Resource wurde erstellt!"
}
```

Laravel has a little known feature in translation strings that makes `:Resource` capitalised.

**Comment by schonhoff** [comment]
It is not working in the cases I wrote above.
My de.json:
`"No :resource matched the given criteria.": "Kein/e :Resource entspricht den angegebenen Kriterien.",`

![image](https://user-images.githubusercontent.com/42345405/87569056-e4a40480-c6c6-11ea-8110-79cab558d717.png)

My Resource Code:
```
/**
     * Get the displayable singular label of the resource.
     *
     * @return string
     */
    public static function singularLabel()
    {
        return __('Customer contact');
    }
```

It is because of the .toLowerCase() in this particular case.

**Comment by jbrooksuk** [comment]
After I posted this, I noticed that this will work for all server translations but not those which are made on the frontend. https://github.com/laravel/nova/pull/920 resolves this issue.

**Comment by michaelklopf** [comment]
@jbrooksuk Your link to issue #920 ends in a 404 page.

I can confirm that `:Resource` doesn't work.

**Comment by pxlrbt** [comment]
@michaelklopf That link should be correct. PR 920 will fix the issue but is awaiting review before being merged.

**Comment by schonhoff** [comment]
@michaelklopf You need to connect your github account with your laravel nova account. You are just possible to see the repository from nova if you have both accounts connected. That is why you are getting a 404 error.

**Comment by jbrooksuk** [comment]
This will be fixed in the next release.
