### ISSUE TITLE
Action applied on "Select all matching" skip every second chunk, when resource is filtered by field that changed in action

### ISSUE THREAD

**Issue by vmalyavin** [laravel/nova-issues#1145]
- Laravel Version: 5.6.39
- Nova Version: 1.2.1
- PHP Version: 7.2.11

### Description:
I have simple model and nova-resource with field called "status"(enum but it doesn't matter).
Resource have filter by "status" field(options is for example "new", "processing" and "payed").
Resource have action that change "status" value of all models to "payed".

I filtered all resources where **status="processing"**, and want to apply this action to "Select all matching".
Action, applied on "Select all matching" skip every second chunk, because "status" is changed for every model in every first chunk, and it's affecting filter-selection, while action is running.

I can solve this problem by rewrite `\Laravel\Nova\Actions\Action::handleRequest` for this action.
But anyway, it is seems better when action applied to "Select all matching" will be applied to all models that is matching selection, regardless of action logic.

**Comment by dkulyk** [comment]
Related to https://github.com/laravel/nova/issues/152

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
