### ISSUE TITLE
Tools styles/scripts should be cacheable by browser

### ISSUE THREAD

**Issue by m-lotze** [laravel/nova-issues#1146]
The routes `/nova-api/styles/*` and `/nova-api/scripts/*` should send HTTP headers like last-modified and etag, so these resources can be cached by a browser. right now they send `cache-control: no-cache, private`, which prevents caching.

Ideally they send just a 304 if the file has not changed.

Also it would be good, if these routes are registered without the whole middleware stack if possible. i dont think they need authorization and it would make the requests for these files a bit faster.

**Comment by webhealer** [comment]
I use google page speed module over apache ( https://developers.google.com/speed/pagespeed/module/)   to combine and reduce page requests. But i did not manage to combine nova tool scripts and styles using . It'S combining other css and scripts, but not includes nova tools.

 https://www.modpagespeed.com/doc/filter-js-combine https://www.modpagespeed.com/doc/filter-css-combine

These scripts makes the page load heavy if you have for example 20 and more components. That means 20 css file and 20 javascript file.  

Is anybody knows how i can include nova tools scripts/styles combining with page speed module?

**Comment by webhealer** [comment]
+1 your suggestion about cache control and css filesize check,but this control should not run everytime on page load, its using server resources while reading filesize.

**Comment by m-lotze** [comment]
Another way might be to comment out `Nova::style('{{ component }}', __DIR__.'/../dist/css/field.css');` in the `FieldServiceProvider.stub`.

**Comment by dillingham** [comment]
I started a package to compile 3rd party assets in nova but can’t seem to get access to the array of styles and scripts during the NovaServing event. Need a Loaded event to hook onto 

https://github.com/dillingham/nova-compile

**Comment by dillingham** [comment]
because each is an api call and the user isnt stored in a session
each script / stylesheet makes a db call vs assuming the same user.
![style](https://user-images.githubusercontent.com/29180903/50426509-50145000-085d-11e9-899e-71687727b6a9.png)

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by m-lotze** [comment]
I made this command to combine all nova 3rd party scripts and styles to one file:

```
class CombineNovaTools extends Command
{
    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Combines all nova tools scripts and styles in nova-tools.[js|css] in public/[js/css]';

    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'combine:nova-tools';

    /**
     * Create a new command instance.
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        Auth::login(User::role(['super-admin'])->first());

        $request = Request::create('/');

        app()->handle($request);

        $this->info('combining nova tools js and css');

        $this->combineTools();
    }

    private function combineTools(): void
    {
        foreach (['allScripts' => 'js', 'allStyles' => 'css'] as $method => $type) {
            $content = '';

            foreach (Nova::{$method}() as $file) {
                $this->info($file);
                $content .= \file_get_contents($file);
            }

            \file_put_contents(public_path($type . '/nova-tools.' . $type), $content);
        }
    }
}
```

Then i use laravel-mix to create versioned files and publsih and change novas layout.blade.php like this:

```
...
<!-- Tool Styles -->
<link rel="stylesheet" href="{{ mix('css/nova-tools.css') }}">
...
<!-- Tool Scripts -->
<script src="{{ mix('js/nova-tools.js') }}"></script>
...
```

This way the tools scripts and styles are cacheable by the browser and the loading speed increases quite significantly. This prevents requests for empty stylesheets and authenticating every tool asset.

**Comment by thaifani** [comment]
Unable to locate Mix file: /css/nova-tools.css

**Comment by atmediauk** [comment]
> Unable to locate Mix file: /css/nova-tools.css

@thaifani I ended up adding  asset() without mix 😬

It's surprising this has been overlooked by the Nova Team. If things are not rolled in to Nova core and we're encouraged to build out our own tools (which is cool) this subsequently leads to more custom tools within a single project. We're on 15 packages already and with that, easily hit 18 second load times locally. Production is worse.

The command above takes that down to 3 seconds!

**Comment by Pamposgsk** [comment]
hi,
could you please give more details on how to achieve the above.
I believe the above problem is very important to be fixed not only regarding speed but due to the fact that in production enviroment sometimes while loading the page it automatically redirecting to nova-api/scripts .
I tried the function abova but it creates empty js and css files
thanks in advanced

**Comment by thaifani** [comment]
I think that you must locate the app_url to the public folder  not the root
folder and make it as virtual host
this answer assumes I understand your question  !!

**Comment by Pamposgsk** [comment]
I created a js folder and css folder inside public folder  and then I run the function.Is that correct?

**Comment by atmediauk** [comment]
> I made this command to combine all nova 3rd party scripts and styles to one file:
> 
> ```
> class CombineNovaTools extends Command
> {
>     /**
>      * The console command description.
>      *
>      * @var string
>      */
>     protected $description = 'Combines all nova tools scripts and styles in nova-tools.[js|css] in public/[js/css]';
> 
>     /**
>      * The name and signature of the console command.
>      *
>      * @var string
>      */
>     protected $signature = 'combine:nova-tools';
> 
>     /**
>      * Create a new command instance.
>      */
>     public function __construct()
>     {
>         parent::__construct();
>     }
> 
>     /**
>      * Execute the console command.
>      *
>      * @return mixed
>      */
>     public function handle()
>     {
>         Auth::login(User::role(['admin'])->first()); // change to a user with full access to nova
> 
>         app()->handle(Request::create('/')); // or wthaever your nova root route is
> 
>         $this->info('combining nova tools js and css');
> 
>         $this->combineTools();
>     }
> 
>     private function combineTools(): void
>     {
>         foreach (['allScripts' => 'js', 'allStyles' => 'css'] as $method => $type) {
>             $content = '';
> 
>             foreach (Nova::{$method}() as $file) {
>                 $this->info($file);
>                 $content .= \file_get_contents($file);
>             }
> 
>             \file_put_contents(public_path($type . '/nova-tools.' . $type), $content);
>         }
>     }
> }
> ```
> 
> Then i use laravel-mix to create versioned files and publish and change novas layout.blade.php like this:
> 
> ```
> ...
> 
> <link rel="stylesheet" href="{{ mix('css/nova-tools.css') }}">
> ...
> 
> <script src="{{ mix('js/nova-tools.js') }}"></script>
> ...
> ```
> 
> This way the tools scripts and styles are cacheable by the browser and the loading speed increases quite significantly. This also prevents requests for empty stylesheets and authenticating every tool asset.

With the above has anyone else had issues with only some of the assets being loaded? When dumping ```Nova::allStyles()``` or ``Nova::allScripts()``` in an artisan command some assets are missing but when calling the same command in a http request e.g dumping in the boot method of the NovaServiceProvider results in all the assets being listed correctly.

Any ideas what could be causing this?
