### ISSUE TITLE
Laravel Nova Pagination doesnt increment counter when paginating

### ISSUE THREAD

**Issue by araeuchle** [laravel/nova-issues#1148]
- Laravel Version: 5.7.17
- Nova Version: 1.2.1
- PHP Version: 7.2.10

### Description:
When a resource has a HasMany relationship and has more than 5 results i can paginate through the resource list. This is working perfectly. But what i am expecting is that the counter in the table footer below is also incrementing.

So let's say we have 75 rows in total and 5 rows are being displayed. 
On the first page i see 5/75 resources. On the second page i would expect to either see something like 10/75 resources or 6-10/75 resources. It would be cool if this can be added. otherwise it is a bit confusing. 

### Steps To Reproduce:

Fresh laravel setup
Install nova
Add a User Model
Add a Post Model
Post has a user id  and a belongsTo User relationship
User has a posts relationship which is a hasMany
Now create the two nova resources for it
Navigate to a user and paginate through his posts
You should see now that the counter is not incrementing

**Comment by dillingham** [comment]
Agreed: related https://github.com/laravel/nova-issues/issues/316

**Comment by dkulyk** [comment]
It will be implemented with #316. (Probably in the next release)
