### ISSUE TITLE
[BUG] onlyOnForms did not hide the field in index and detail page in lenses.

### ISSUE THREAD

**Issue by nasrulhazim** [laravel/nova-issues#1149]
- Laravel Version: 5.7.17
- Nova Version: 1.2.1
- PHP Version: 7.2.13

### Description:

When using `onlyOnForms()` in lenses, the field is appeared on index and details page.

### Steps To Reproduce:

```php
Text::make('Name')->onlyOnForms(),
```

**Comment by dillingham** [comment]
Related https://github.com/laravel/nova-issues/issues/657 https://github.com/laravel/nova-issues/issues/894 https://github.com/laravel/nova-issues/issues/1149

**Comment by dillingham** [comment]
If you don't want it to show on a lens, don't include it in the lens class
