### ISSUE TITLE
Refer to the wrong table name for belongsToMany relationship

### ISSUE THREAD

**Issue by terasupernova** [laravel/nova-issues#1150]
- Laravel Version: 5.6.39
- Nova Version: 1.2.1
- PHP Version: 7.1

### Description:
I got one merchant table and one main_category table. The relationship between these two tables is belongsToMany. So i got a pivot table named **merchant_main_categories**

In App\Models\Merchant
```
    public function mainCategories()
    {
        return $this->belongsToMany(MainCategory::class);
    }
```
In App\Models\MainCategory
```
    public function merchants()
    {
        return $this->belongsToMany(Merchant::class);
    } 
```
In App\Nova\Merchant
```
    public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
            Text::make('name')->rules('required')->sortable(),
            BelongsToMany::make('MainCategories'),
        ];
    }
```
In App\Nova\MainCategory
   ```
 public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
            Text::make('name'),
            BelongsToMany::make('Merchants')
        ];
    }
```
When reload the page, error come out.
Base table or view not found. Table **main_category_merchant**  doesn't exist.

The table I created is merchant_main_categories, so it is possible to change the table name from **main_category_merchant** to the table name i want?

Thanks.

**Comment by webhealer** [comment]
Try to define pivot table in relations:

    public function mainCategories()
    {
        return $this->belongsToMany(MainCategory::class, 'merchant_main_categories');
    }

**Comment by dillingham** [comment]
Unrelated to Nova. 
Laravel has a table naming convention 
Alphabetical when pivoting.

**Comment by terasupernova** [comment]
Thanks @webhealer
