### ISSUE TITLE
how to set Nova.requst().post headers

### ISSUE THREAD

**Issue by BruceGujinhe** [laravel/nova-issues#1151]
- Laravel Version: 5.7.*
- Nova Version: 1.2.1
- PHP Version: 7.2

### Description:
how to set the config in the post request?
```
let config = {
    headers: {
          'Content-Type': 'multipart/form-data'
    }
}
let params = {
     'upload_file' : this.upload_file
}
Nova.request().post('/nova-vendor/resource-table-row/upload-data', params).then(({data}) => {
     console.log(data);
})
```

**Comment by dkulyk** [comment]
https://github.com/axios/axios/blob/master/README.md#axiosposturl-data-config
Third parameter is config

**Comment by BruceGujinhe** [comment]
I know why the backend can't get the value, just because we  set the  headers content-type with `multipart/form-data`, so that we must pass the second parameter with the instance of class FormData. 

thanks for your reply anyway.

**Comment by bonzai** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://larachat.co/).
