### ISSUE TITLE
Nova Components: No output with laravel-mix 4

### ISSUE THREAD

**Issue by chefhasteeth** [laravel/nova-issues#1153]
**Edit: See comment.**

- Laravel Version: 5.7.15
- Nova Version: 1.2.0
- PHP Version: 7.1.10

### Quick summary:
Updated main project package.json to use `laravel-mix: ^4.0.7` -> babel errors when compiling nova components -> updated nova component package.json to use `laravel-mix: ^4.0.7` -> component compiles, but has no output on page.

### Description:
We recently updated our project to use mix 4+ (which was recently bumped to the official laravel repo for new projects). That worked fine, but when I tried compiling one of my Nova components, I started getting errors that babel-core ^7.0.0-0 was required (it was using the default package.json file that's loaded with new components).

At first I tried to update whatever babel packages it was complaining about in the component directory, but that was a bit like following a rabbit trail of different errors. In the end, easiest solution seemed to be just updating laravel-mix in my component to match the rest of the project.

It compiled, which was awesome, but when I reloaded the page, the component yielded no output. I checked the source and there were several `<!-- -->` lines where the component markup should have been. The code for the component hasn't changed, I was just recompiling it. I've tried this with existing and brand new components.

### Steps To Reproduce:
1. Update to laravel-mix:^4.0.7 in your component and the main laravel project dir
2. `cd nova-components/YourComponent && npm run dev`
3. Should compile properly
4. Reload Nova and there should be nothing where your component was before

**Comment by judahnator** [comment]
I am seeing the same issue, but have no `.babelrc` in my project root.

**Comment by elbsurfer** [comment]
I have no .babelrc as well and see this issue.

**Comment by fbingha** [comment]
Same problem here.. Upgrade to Mix 4.0.0, my custom components have no output.

**Comment by fbingha** [comment]
Update, reading https://github.com/laravel/nova-issues/issues/1839

I noticed a note about add '.default' to component so I tried it, and IT WORKS.

So:

```
component: require('./views/product/Index')
```

becomes

```
component: require('./views/product/Index').default
````


and

```
Vue.component('subscription-tool', require('./components/subscription/ResourceTool'));
```

becomes

```
Vue.component('subscription-tool', require('./components/subscription/ResourceTool').default);
```

So now I am using Mix 4.0.0 and no more "this.setDynamic is not a function" and my tools are now loading.

**Comment by nghia-le** [comment]
@fbingha Excellent. this worked for me. Thank you very much.

**Comment by mcanvar** [comment]
@fbingha thank you for the hint. But I think this should be fixed ASAP. Here is the vulnerability report from npm: 
```
41 vulnerabilities (13 low, 7 moderate, 21 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```
