### ISSUE TITLE
Cumulative Growth Metrics

### ISSUE THREAD

**Issue by sonalmahajan01** [laravel/nova-issues#1154]
How to create cumulative growth metrics in Nova? Like what ha been the total growth users in the past week/month/year?

**Comment by bonzai** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://larachat.co/).
