### ISSUE TITLE
Request object is empty inside options method from custom filter

### ISSUE THREAD

**Issue by araeuchle** [laravel/nova-issues#1155]
- Laravel Version: 5.7.17
- Nova Version: 1.2.1
- PHP Version: 7.2.10

### Description:

When implementing a new custom filter in Nova, we sometimes need to have access to values of other filters. In the options method we get a request object which is empty. It means it has no queryString, an empty ParameterBag and so on. It would be awesome if we could easily access other filters attached to the same resource or lense to get their values. When you try to access the query parameters in the apply method, the request is filled. So somehow it gets cleaned up during the process and we lose access to it.

**Comment by dillingham** [comment]
I requested the same here https://github.com/laravel/nova-issues/issues/1070

**Comment by araeuchle** [comment]
ah really? sorry didnt recognize this :)

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
