### ISSUE TITLE
Deletes new file on upload when old one exists with prunable

### ISSUE THREAD

**Issue by Sparclex** [laravel/nova-issues#1156]
- Laravel Version: 5.7.19
- Nova Version: 1.2.1
- PHP Version: 7.3

### Description:

When using a custom delete and store method in combination with `prunable` for the file field, the delete method gets called _after_ the store method. By using the documentation example file deletion method the new file gets removed since the model attribute is already updated when calling the delete method.

### Steps To Reproduce:

Create an file field and follow the documentation for the store and delete method and mark it as prunable:
```php
File::make('Attachment')
    ->prunable()
    ->store(function (Request $request, $model) {
        return [
            'attachment' => $request->attachment->store('/'),
            'attachment_name' => $request->attachment->getClientOriginalName(),
            'attachment_size' => $request->attachment->getSize(),
        ];
    })
    ->delete(function (Request $request, $model) {
        if (! $model->attachment) {
            return;
        }

        Storage::disk($this->disk)->delete($model->attachment);

        return [
            'attachment' => null,
            'attachment_name' => null,
            'attachment_size' => null,
        ];
    });
```

**Comment by dkulyk** [comment]
`$request->attachment->store('/'),` $disk not specified.
`Storage::disk($this->disk)->delete($model->attachment);` $this is resource, not a field

**Comment by dkulyk** [comment]
I have caught it. If you specifying your own delete callback you do not know what was in `$model->{$attribute}` before.
Previous file is deleting when model already saved with new data.

**Comment by andriyPalko** [comment]
> PR was sent to upstream.
> 
> You will need to use additional arguments in callback.
> 
> ```
>     ->delete(function (Request $request, $model, $value, $disk) {
>         if (! $value) {
>             return;
>         }
> 
>         Storage::disk($disk)->delete($value);
> 
>         return [
>             'attachment' => null,
>             'attachment_name' => null,
>             'attachment_size' => null,
>         ];
>     });
> ```

But then I have error 
`Too few arguments to function App\\Nova\\Resources\\Example::App\\Nova\\Resources\\{closure}(), 2 passed and exactly 4 expected`

**Comment by dkulyk** [comment]
It has not applied yet

**Comment by pokono** [comment]
So, what was the solution? Behaviour still apply..
