### ISSUE TITLE
select * from `mx_users` where `id` = ? limit 1

### ISSUE THREAD

**Issue by robov** [laravel/nova-issues#1158]
When I install the basic nova with debugbar and telescope and I load the dashboard I see in telescope:
that the following query is executed 5 times.
`select * from `mx_users` where `id` = ? limit 1`

When I load more packages, this number of repeating this query is increased dramatically
Any ideas why this is being called 5times

Telescope notes that these queries originate from 
index.php
`$response = $kernel->handle(
    $request = Illuminate\Http\Request::capture()
);`

**Comment by webhealer** [comment]
Please check the eager load issue for BelongsTo field. https://github.com/laravel/nova-issues/issues/112

**Comment by webhealer** [comment]
What is **mx_users** table using for? Is this table belongs to a resource page / card or custom component? Need more details about loaded cards and packages to understand the issue.

**Comment by robov** [comment]
Sorry about the tablename. This is just the plain users resource out of the box, with a prefix

**Comment by dillingham** [comment]
Doesn't seem like a eager load issue, I am seeing it also

Seems like each script and stylesheet is doing some authorization and its calling users table

Still inspecting 🤔

**Comment by dillingham** [comment]
![sad](https://user-images.githubusercontent.com/29180903/50407768-c0629900-07ab-11e9-9a44-f2164f42b051.png)

**Comment by webhealer** [comment]
I just checked with telescope. Same for me.

**Comment by dillingham** [comment]
@bonzai why did you close this?

**Comment by bonzai** [comment]
@dillingham:

> Seems like each script and stylesheet is doing some authorization and its calling users table

This is a normal behavior because assets, data and cards are loaded via ajax. As for now I can't debug and confirm this issue (= I don't have any duplicated requests or queries on the dashboard).

If you have a problem with eager loading then I suggest looking at the following issues:

- #112
- #246

**Comment by dillingham** [comment]
@bonzai thanks :)

I do think the auth user should be stored in the session to prevent many database checks. I’m still confused why there is authorization per style and script and individually, I’ll think on it though
