### ISSUE TITLE
First set meta through `withMeta` on Trend Metrics is always returned on `calculate`

### ISSUE THREAD

**Issue by beNjiox** [laravel/nova-issues#1159]
- Laravel Version: v5.6.39
- Nova Version: 1.2.1
- PHP Version: 7.1

### Description:

Hello,

To avoid creating many time the same Metric class with just one modification (what range I want to sum on), I thought I would leverage withMeta, doing something like this

```php
// app/Providers/NovaServiceProvider.php
class NovaServiceProvider extends NovaApplicationServiceProvider {
   ...

   protected function cards()
    {
        return [
          (new OrdersCountRange())->width(‘1/3’)->withMeta([‘typeOfRange’ => ‘week’]),
          (new OrdersCountRange())->width(‘1/3’)->withMeta([‘typeOfRange’ => ‘month’]),
          (new OrdersCountRange())->width(‘1/3’)->withMeta([‘typeOfRange’ => ‘day’]),
        ];
    }
}
```

```php
// app/Nova/Metrics/OrdersCountRange.php
class OrdersCountRange extends Trend {
    ...

    private function typeOfRange()
    {
       return $this->meta()['typeOfRange'];
    }

    public function calculate(Request $request)
    {
        if ($this->typeOfRange() == 'day') {
            $calculatedData = $this->countByDays($request, Order::notCancelled());
        } elseif ($this->typeOfRange() == 'week') {
            $calculatedData = $this->countByWeeks($request, Order::notCancelled());
        } else {
            $calculatedData = $this->countByMonths($request, Order::notCancelled());
        }

        return $calculatedData
          ->suffix('commande')
          ->showLatestValue();
    }
}
```

However this does not work.
From what I understand, `meta()` , from the `calculate` method will always return the first value being set in my key `typeOfRange`.

This is surprising as it works perfectly with the `name()` method for example

```php
public function name()
{
    if ($this->typeOfRange() == ‘week’) {
        return “Commandes par semaine”;
    } elseif ($this->typeOfRange() == ‘month’) {
        return “Commandes par mois”;
    } else {
        return “Commandes par jours”;
    }
}
```

This will indeed attach the right title to my metrics card, as you can see here https://cl.ly/1f612ee95682

After further investigation, I went in `vendor/laravel/nova/src/Metrics/Metric.php:26` and simply `Log::info($this->meta())` at the beginning of the method and have been able to show the issue here, with the code showed above, the log will look like this.

```
[2018-12-22 20:16:54] dev.INFO: array (
  'typeOfRange' => 'week',
)
[2018-12-22 20:16:54] dev.INFO: array (
  'typeOfRange' => 'week',
)
[2018-12-22 20:16:54] dev.INFO: array (
  'typeOfRange' => 'week',
)
```

is this behaviour intended? Would there be a simple fix to allow leveraging `withMeta` with Metrics?

I’m fully aware I could solve this issue by simply creating 3 classes, one for Weeks, one for Months, one for Days, but I just thought my solution would be cool to have, as I intended to do such thing for 4-5 metric cards and could benefit avoiding from ending up with 15+ classes down the road.

Thanks for reading and Thanks for Nova!

### Steps To Reproduce:

- Create a `Metrics\Trend` class
- Use it twice as part of your dashboard `app/Providers/NovaServiceProvider.php`
- When instantiating your Trend class, pass 2 different value for the same meta (See example in description)
- `Log::info` in the `calculate` method of your newly created `Metrics\Trend` class to realize only first value passed is always returned

**Comment by nCuXaP** [comment]
@beNjiox I tried everything ... also with the uriKey but didn`t add the '-' and it didn`t work.
You saved me a lot of time with this.
Thank you my friend!

**Comment by terasupernova** [comment]
@beNjiox Do you know how to insert the login user data into the meta in NovaServiceProvider? Because the cards function in NovaServiceProvider is without the request parameter.
```
protected function cards()
    {
        return [
            (new NewTransactions())->width('1/2')->withMeta(['merchantId' => $request->user()->merchant_id]),
        ];
    }
```

I can get the user's merchant_id in authorization function, but the cards function will run first, then only run authorization function
````
protected function authorization()
    {
        $this->gate();

        Nova::auth(function ($request) {
            var_dump($request->user()->merchant_id);
            return app()->environment('local') ||
                   Gate::check('viewNova', [$request->user()]);
        });
    }
````

Please help, thank you.
