### ISSUE TITLE
Multiple Relations on same Model

### ISSUE THREAD

**Issue by jonnyfinlay99** [laravel/nova-issues#116]
I have a Job Model which has multiple BelongsToMany Relationships to User
```
    public function users()
    {
        return $this->belongsToMany(User::class, 'job_users', 'job_id', 'user_id');
        
    }
    public function owners()
    {
        return $this->belongsToMany(User::class, 'job_owners', 'job_id', 'owner_id');
    }
```

As a Job can have a user who is assigned to the job and a user who is the owner of the job.

```
      BelongsToMany::make('Users', 'users')
                ->searchable(),
      BelongsToMany::make('Users','owners')
                ->searchable(),
```

The resource only renders the last BelongsToMany, Im assuming this is because they both reference the User Model.

Is there anyway around this so that I can update multiple relations that use the same model.

**Comment by fletch3555** [comment]
The first argument is just the name of the field, right? Can't you change that to "Owners"? That should allow both fields to show. (untested)

**Comment by jonnyfinlay99** [comment]
App\Owner Model not found

**Comment by jsiebach** [comment]
@jonnyfinlay99 use the third argument

      BelongsToMany::make('Owners','owners', User::class)
                ->searchable(),

**Comment by jonnyfinlay99** [comment]
@jsiebach Thats working now brilliant, the only problem is both panels show up with the label of Users, is there a method of renaming the BelongsToMany panel titles

**Comment by jsiebach** [comment]
@jonnyfinlay99 These are the functions on your User resource you can overwrite to change the label:


    /**
     * Get the displayble label of the resource.
     *
     * @return string
     */
    public static function label()
    {
        return Str::plural(class_basename(get_called_class()));
    }

    /**
     * Get the displayble singular label of the resource.
     *
     * @return string
     */
    public static function singularLabel()
    {
        return Str::singular(static::label());
    }

I am not sure how you would return "Referrals" in this context and "Users" in a different context, though. But those are the place to be looking I think.

**Comment by dillingham** [comment]
@alexbowers related to https://github.com/laravel/nova-issues/issues/139

**Comment by davidhemphill** [comment]
The label issue is fixed in the current release.
