### ISSUE TITLE
Code field doesn't expand unless focused and caret moved to wrongly cropped code 

### ISSUE THREAD

**Issue by cjke** [laravel/nova-issues#1160]
- Laravel Version: 5.7
- Nova Version: 1.2.1
- PHP Version: 7.2.4

### Description:

Using a code field such as:

`Code::make('Config')->json(),`

Leads to a cropped section not appearing in view or edit mode unless focused and caret moved to lower, hidden area (see screenshots for better explanation):

Before clicking (doesn't render past line 12):

![screen shot 2018-12-23 at 5 18 42 pm](https://user-images.githubusercontent.com/884065/50381293-7dcf8c80-06d7-11e9-8429-4759017665d0.png)

After clicking and moving caret down (now renders the remaining lines):

![screen shot 2018-12-23 at 5 18 49 pm](https://user-images.githubusercontent.com/884065/50381299-8e800280-06d7-11e9-8955-351b0f17f6b8.png)

### Steps To Reproduce:

Create a code field and add a snippet of code longer than 12 lines long

**Comment by bonzai** [comment]
This was fixed in 1.2.1 and I can't confirm on fresh installation.

Make sure you republish your assets:

```
$ php artisan nova:publish --force
```

**Comment by ralphschindler** [comment]
Confirmed, re-publishing assets fixed it, Thanks!
