### ISSUE TITLE
Excessive queries from cards in service provider

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#1162]
- Laravel Version: 5.7
- Nova Version: 1.2.1

### Description:

When I search while attaching a belongsToMany it triggers the NovaServiceProvider / dashboard cards, I pass data to vue withMeta so it’s triggering like 10 queries each character searched. The cards on the dashboard should not be triggered when I perform a relation search.

### Steps To Reproduce:

- add queries to custom cards classes / pass to vue withMeta
- add cards to NovaServiceProvider for dashboard
- have a belongsToMany relationship on resource ie account_user
- click attach & search a user
- see card queries along with your search in telescope

### Workaround

Solved by adding this within the `cards()` method

```php
// NovaServiceProvider

protected function cards()
{
    if ($_SERVER['REQUEST_URI'] != "/nova-api/cards") {
        return [];
    }

    return [
        new \App\Nova\Cards\CardWithQuery1,
        new \App\Nova\Cards\CardWithQuery2,
        new \App\Nova\Cards\CardWithQuery3,
    ];
}

```

**Comment by LorenzoSapora** [comment]
Can confirm this actually works. Good job, Brian.

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!

**Comment by SerjoA** [comment]
this is still hapening in latest nova version, i used brians method to overcome this
