### ISSUE TITLE
a few minor issues

### ISSUE THREAD

**Issue by lilianjin** [laravel/nova-issues#1163]
The nova, laravel lineage nova is a great component. I have a few questions to ask; seek a better solution; thanks!
1. In resources such as users, can I delete myself?
2. Is the row action in resources fixed? Can't customize?
3. In the one-to-many details display page of resources? If I don't need to add, or how to add new ones, how do I hide the new button?
4. In the resources index, I want to render a different type of view. Obviously they are all in one model. Limited to different field types? Is it using lens?

**Comment by dillingham** [comment]
This is not the appropriate channel for questions. This is bug tracking
Ask questions on [discord #nova chat ](https://discord.gg/FDzEUYP)
Please only report bugs specific to Nova here

**Comment by lilianjin** [comment]
@dillingham page can not open

**Comment by bonzai** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://larachat.co/).
