### ISSUE TITLE
Excessive queries from filters / nested relationships

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#1165]
- Laravel Version: 5.7
- Nova Version: 1.2.1

### Description:
Need to trigger filter rendering / queries on filter menu open. Doing so on resource index load is creating a large overhead. I have 7 or so filters on each nested resource. That's 7 filter queries x 5 nested tables. Viewing 1 user results in 40+ queries, mostly because of filters that may not get used until specific scenarios. 

### Steps To Reproduce:
- Add 3 or more HasMany::make('Resources'); to User resource
- Add 3 or more filters with queries to those HasMany resources
- View 1 user and see all the queries for the relationships and their filters

A loading state on filters menu will solve this.

**Comment by dkulyk** [comment]
In 1.3.0 filters loaded before resources for applying default filter values.

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
