### ISSUE TITLE
Filter Options not working when providing array

### ISSUE THREAD

**Issue by ack202** [laravel/nova-issues#1166]
- Laravel Version: 5.7.1
- Nova Version: 1.2.1
- PHP Version: 7.1.3

### Description:
Providing an array to filter options returns an entry with value 0.

![screenshot 2018-12-25 at 19 30 23](https://user-images.githubusercontent.com/2745837/50425691-130b8600-087c-11e9-8c98-de0d165d2923.png)

### Working:

```
    public function options(Request $request)
    {
        return [
            'Germany' => 'DE',
            'France' => 'FR',
        ];
    }
```

### Not working:

```
 public function options(Request $request)
    {
        $countries = array('Germany' => 'DE', 'France' => 'FR');
        return [
            $countries
        ];
    }
```

**Comment by dillingham** [comment]
return $countries;

You’re wrapping it in another array [] is array()

**Comment by ack202** [comment]
my bad...thanks man!
