### ISSUE TITLE
Remove un-needed action button

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#1167]
- Laravel Version: 5.7
- Nova Version: 1.2.1

### Description:

Because actions with & without fields have a confirmation modal
We can do without the button and instead trigger on dropdown item click.
Will reduce toolbar visual debt & save a step, 

**Before** `click item, click arrow button, click confirm`

![action-before](https://user-images.githubusercontent.com/29180903/50433447-3ea36600-08a6-11e9-8a40-60a407b4c7c6.png)

**After** `click item, click confirm`

![action-after](https://user-images.githubusercontent.com/29180903/50453789-1a30a380-0911-11e9-8e8c-a7c0cffa0071.png)

Note: close modal & new row select would reset the dropdown selection to none

**Comment by aozen** [comment]
I am waiting this too. I need that. 
Select dropdown + click arrow button and action done. This is what i looking for. Looks like same. Modal is unnecessary actually. I tried to change something to do but didn't worked out. Still wondering the cool solution.

**Comment by dillingham** [comment]
@aozen 
>Modal is unnecessary actually.
Depends, I'd be too nervous that someone would perform the wrong bulk action.
The confirmation insures someone didn't click the wrong action menu item.

**Comment by davidhemphill** [comment]
I get what you're saying, but I envision a future where actions are searchable and I'd want the button there in that case too. I've never thought select boxes that do something automatically on change are good UX either.

**Comment by vesper8** [comment]
@aozen did you ever figure out a way to have actions activate immediately? Without displaying a confirmation modal

**Comment by vesper8** [comment]
@aozen not sure when this was added, and it isn't documented as of today, but there is a hidden method you can use on actions called `->withoutConfirmation()` which does what you want
