### ISSUE TITLE
Cannot change resource name

### ISSUE THREAD

**Issue by olsp** [laravel/nova-issues#1169]
- Laravel Version: 5.7.19
- Nova Version: 1.2.1
- PHP Version: 7.2

### Description:
I created a model + migration called "people" and also a Nova resource for it. I then decided to rename it to "person" so I renamed everything in the files and also the filenames. But in the Nova sidebar "People" keeps appearing with the error message, that this database table does not exist.
I already deleted the resource and created a new one, but it still keeps the old name.
I cleared the cache and dumped the autoload, which didn't make any difference.

**Comment by dkulyk** [comment]
You can override `label` and `sigularLabel` methods in the resource.

**Comment by olsp** [comment]
Yes, but this shouldn't be necessary. And it still won't choose the right database table.

**Comment by olsp** [comment]
I found out that Laravel uses "People" as plural for "Person", I expected it to be "Persons".

**Comment by priceluke** [comment]
> You can override `label` and `sigularLabel` methods in the resource.

should be very obvious but `sigularLabel` should be `singularLabel`

**Comment by priceluke** [comment]
furthermore, this may be of use to future visitors:

```
public static function label()
    {
        return 'Restaurants';
    }

public static function singularLabel()
    {
        return 'Restaurant';
    }
```
