### ISSUE TITLE
Deleting a record that contains Image or Avatar gives error

### ISSUE THREAD

**Issue by webhealer** [laravel/nova-issues#1171]
- Laravel Version: 5.7.16
- Nova Version: 1.2.1
- PHP Version: 7.2.10

### Description:

When deleting a record from a resource, if it contains  "Avatar" or "Image" field (prunable),  giving "sql" error if the field is not "nullable" in database table (mysql). 

> Integrity constraint violation: 1048 Column 'picture' cannot be null (SQL: update `pictures` set `picture` = , `updated_at` = 2018-12-27 01:24:38 where `id` = 24) at

After that error, record not deleting from database, however it deletes picture from storage. 

If the "picture" field in database is "nullable", then it's successfully deletes the db record and the file.

### Steps To Reproduce:
- Create a simple resource that contains "Avatar" or "Image" Field with "prunable" method.
- Create database table with "picture" field ( not nullable).
- Create a new picture and save record.
- Try to delete the record from resource.

![pic1](https://user-images.githubusercontent.com/701360/50458769-b93bb680-0976-11e9-987b-21b51d042692.png)

![pic2](https://user-images.githubusercontent.com/701360/50458768-b8a32000-0976-11e9-861c-abefb2732a12.png)

![pic3](https://user-images.githubusercontent.com/701360/50458766-b8a32000-0976-11e9-92ff-b87e26357dc9.png)

**Comment by MarouaneSH** [comment]
Make sur to use this on your fields function `Avatar::make('Photo',"avatar")->thumbnail(function () {
                return $this->avatar;
            })->rules('required', 'max:255'),
`

**Comment by dkulyk** [comment]
PR was sent to upstream.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍

**Comment by dkulyk** [comment]
It will be in the next release after 1.3.0
