### ISSUE TITLE
Model prop updates should propagate on all field component instances referencing the same prop?

### ISSUE THREAD

**Issue by huenisys** [laravel/nova-issues#1172]
- Laravel Version: 5.7.19
- Nova Version: 1.2.1
- PHP Version: 7.2.4

### Description:

```
            Trix::make('Content')->alwaysShow(),
            Code::make('Content')->hideFromDetail(),
```

When a model property is shown in 2 fields, say code and trix, then go edit mode, changes only take effect on the field with higher index. Don't we have state management here? When you edit the content property, shouldn't we propagate in all fields? In the order above, whatever the value found on Code field will take effect.

### Steps To Reproduce:

1. Add 2 fields referencing same model prop. e.g. Code and Trix for a 'content' prop
2. Put in the order Trix, then Code.
3. Edit Trix.
4. Submit.

Result: No changes.

Expectation: When we edit a model prop, it should propagate to all components. Agree?

**Comment by huenisys** [comment]
Sorry @dillingham

The last one in the list of fields actually does save. I'm just reporting what I think is a bug. No time yet to investigate but I think Vue was used here so I got this expectation that we use objects as source of truth in the UI. Updates on a dependent component, most of the time, should propagate to other components using the same object.

**Comment by webhealer** [comment]
But when you need to populate same field name  with using 2 different field type on forms? If you want to show same field with different field types on detail or index, that's possible. You just need to hide 1 of the same field from forms.

**Comment by huenisys** [comment]
> Two inputs for the same column can't be saved on a form

I agree and nobody wants that. Imagine 2 fields referring to the same prop which is the scenario right now, aren't you expecting that when you update one(on the client), it auto updates the other? This way, when state is saved, we get what the common expectation is?

**Comment by webhealer** [comment]
Ok,  I got what you mean by prop same data when using same field  but but with the current structure,  when you do this Trix::make('Content')->alwaysShow(),
If you look for the rendered page content, it assigns "content" as an id attribute of form element. And it uses this "id" for form validations and for preparing the post data.  So it's not possible to put same 2 fields with same "id" on page, it will ignore one.

**Comment by davidhemphill** [comment]
I believe this is just a misunderstanding of how Nova manages and submits form state. Form state isn't managed in a central place, it's managed per-field. 

Right now, I can't see a good-enough reason to change the behavior unless there's a good reason to have multiple fields showing (and allowing edits to) the same data.
