### ISSUE TITLE
Relationships not unique to vue cause searching two tables

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#1173]
- Laravel Version: 5.7
- Nova Version: 1.2.1

### Description:

If a table is rendered twice for different relationships it will not be treated uniquely by vue
Searching one table results in search in another.
Many issues on here illustrate the need for the same relationships with different model methods

### Steps To Reproduce:

```php
HasMany::make('Teams', 'teams', 'App\Nova\Team'),
HasMany::make('Special Teams', 'specialTeams', 'App\Nova\Team'),
```

^ search or filter one of those tables and see that the other table does the same

**Comment by jbrooksuk** [comment]
Replicated in Nova v2.0.9

**Comment by jbrooksuk** [comment]
I've made a PR upstream.
