### ISSUE TITLE
How can I add button with the belongs to dropdown

### ISSUE THREAD

**Issue by yatin13490** [laravel/nova-issues#1175]
Hey @davidhemphill,

1.  I need the button with the belongs to the dropdown, for by clicking on the button I can create new entry directly into that relationship modal, but how can I set this?

2. I don't want to show the checkbox with the message "with trashed" so how can I hide that button.

I check the Vue file for that checkbox shows under the condition isLocked, but how can I override it.

I am stuck in my project due to these two things only. Can you please guide me on this

thanks

**Comment by bonzai** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://larachat.co/).
