### ISSUE TITLE
&amp; is shown instead of &

### ISSUE THREAD

**Issue by wiwa1978** [laravel/nova-issues#1177]
- Laravel Version: 5.7.19
- Nova Version: 2.1.2
- PHP Version: 7.1.19

Description:

Brand new install shows the '&' character as '&amp;'

![image](https://user-images.githubusercontent.com/4012455/50511021-3278fd80-0a8c-11e9-999b-dbf10414ec6d.png)

**Comment by bonzai** [comment]
This was fixed long time ago. Try running:

```sh
$ php artisan nova:publish --force
```
