### ISSUE TITLE
Global Search shows no result, it was working before.

### ISSUE THREAD

**Issue by arditokshtuni** [laravel/nova-issues#1178]
- Laravel Version: 5.7.19
- Nova Version: 1.2.1
- PHP Version: 7.2.5

### Description:
It shows: NO RESULTS FOUND.
It was working before..
I tried php artisan cache:clear, config:clear, vew:clear ... composer update ... npm update... npm run dev.. and i have not fixed it

In network the request shows 404 error

**Comment by Fawzanm** [comment]
Can you share the code for the corresponding Nova `Resource`?

**Comment by arditokshtuni** [comment]
@Fawzanm thanks for the comment, the error was in my code, in a call of:
$request->findResourceOrFail($request->resourceId)
I think i was calling that for example for finding a User resource in Role resource class
