### ISSUE TITLE
invalid Action log data

### ISSUE THREAD

**Issue by huoding** [laravel/nova-issues#1179]
- Laravel Version: 5.7.0
- Nova Version: 1.2.1
- PHP Version: 7.3

### Description:
get_class should be getMorphClass in methods (ActionEvent.php):
forSoftDeleteAction, forResourceDetach, defaultAttributes 

`      Relation::morphMap([
            'users' => User::class,
        ]);`

![a](https://user-images.githubusercontent.com/3479812/50535254-2328ab80-0b83-11e9-8858-e81586cfe528.png)

**Comment by bonzai** [comment]
This has been fixed and will be included in the next release.
