### ISSUE TITLE
Feature request: URL slug field

### ISSUE THREAD

**Issue by FreekVR** [laravel/nova-issues#118]
I think it'd be awesome if Nova came with a special "slug" field which would generate a url slug based on another field. And has a possibility to override it if you want to. (basically the same as for example Wordpress).

 I'd imagine you could construct it something like this:

`Slug::make('Slug')->basedOn('Title')->makeEditable()`

**Comment by ians88** [comment]
This could be made by the community as an _custom field_.

Though what I do is that I use a `resolveUsing()` method on the _slug field_

It looks like this:
```php
Text::make('Slug')
    ->resolveUsing(function ($slug) {
        return str_slug($slug);
    })
```

This converts the string that the user inserted to a URL save slug.

**Comment by kombimedia** [comment]
@FreekVR 
Found this little package today. Works nicely, exactly as you suggest.

https://packagist.org/packages/benjaminhirsch/nova-slug-field

**Comment by laurencei** [comment]
Yeah - the package listed above works *perfectly*.

**Comment by alexbowers** [comment]
Solved by a community plugin

**Comment by nezaboravi** [comment]
Comunity package does not makes slug unique. Whats the point of slug if not unique? 
Any suggestion how to achieve this with premium Nova package?
