### ISSUE TITLE
ressource inline editing

### ISSUE THREAD

**Issue by Dontorpedo** [laravel/nova-issues#1180]
A feature to make the ressource editable inline would be supercool..

like fieldoption ->editableOnIndex() or something..

some columns need to be editet quickly, opening, editing and saving is a bit waste of time if one wants to edit several ressources..

**Comment by dillingham** [comment]
@Dontorpedo interesting idea

I could see pencil icon & a controller updating single columns via ajax
I suspect proposing a package might be a better medium
https://github.com/tightenco/nova-package-development/issues

**Comment by Dontorpedo** [comment]
ok, i did it ;) 

https://github.com/tightenco/nova-package-development/issues/62

**Comment by davidhemphill** [comment]
Closing as you made a package to do this. 👍

**Comment by vesper8** [comment]
He didn't make a package to add inline editing.. he just made a repo for discussing new nova packages

Here are three plugins that add inline editing.. I really wish this was built-in, or maybe it is by now

https://github.com/markrassamni/inline-boolean
https://github.com/wehaa/inline-field-update
https://github.com/kirschbaum-development/nova-inline-select
