### ISSUE TITLE
Filters broken: updateFilterState: TypeError: Cannot set property 'currentValue' of undefined

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#1181]
- Laravel Version: 5.7
- Nova Version: 1.2.1
- Chrome Latest

### Description:

Fatal error: all relationship's filters are duplicates of one other relationship’s table. 
Opening filter menu results in seeing the same filter menu for each relationship. 

### Steps To Reproduce:

- View resource with multiple relationships
- Filter a relationship table
- See wrong menus
- View console and see error

### Attempted
- I disabled every package to debug this: **didn't work**
- I reverted to 1.2.0 nova:publish --force: **didnt work**
- I reverted to 1.1.9 nova:publish --force: **didnt work**
- I reverted to 1.1.8 nova:publish --force: **didnt work**
- I reverted to 1.1.7 nova:publish --force: **WORKED**

![error](https://user-images.githubusercontent.com/29180903/50543274-65f97c00-0ba1-11e9-9975-07d5196f1afd.PNG)

**Comment by dillingham** [comment]
Seems related https://github.com/laravel/nova-issues/issues/1143

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
