### ISSUE TITLE
Laravel Nova ScriptController undefined index 

### ISSUE THREAD

**Issue by araeuchle** [laravel/nova-issues#1182]
- Laravel Version: 5.7.17
- Nova Version: 1.2.1
- PHP Version: 7.2.10

### Description:

When you have external packages installed and they have no .common.js.map file, the ScriptController of Nova fires Exceptions on every request because of undefined Index call. 

(ErrorException(code: 0): Undefined index: vue-zondicons.common.js.map at /Users/myUser/projects/myProject/vendor/laravel/nova/src/Http/Controllers/ScriptController.php:21)

This is the call, where the error occurs: 

`file_get_contents(Nova::allScripts()[$request->script])`

Maybe it would be more safe here to add an isset check before using file_get_contents like so:

     if (isset(Nova::allScripts()[$request->script])) {
        file_get_contents(Nova::allScripts()[$request->script]);
     } 

This should prevent the error.

**Comment by dkulyk** [comment]
This has been fixed and will be included in an upcoming release.

**Comment by araeuchle** [comment]
Awesome! :)
