### ISSUE TITLE
Morph type selection error

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#1184]
- Laravel Version: 5.7
- Nova Version: 1.2.1

### Description:
When morphTo is **searchable** & with no type selected, 
You get the following missing type error when searching
Search the second field before selecting a type.

### Easy fix options

- hide the second row until a selection is made
- could default to first & insure the second select box has a type
- could disable the second field until type is selected

```js
<default-field v-if="resourceType" 
```

![type-error](https://user-images.githubusercontent.com/29180903/50594837-21553580-0e6c-11e9-9bbf-8c68243669cd.png)

![nova-error](https://user-images.githubusercontent.com/29180903/50594931-7ee98200-0e6c-11e9-895f-e5436bf62f6b.PNG)

**Comment by dkulyk** [comment]
PR was sent to upstream.
