### ISSUE TITLE
Could not update nova version via composer

### ISSUE THREAD

**Issue by pavinthan** [laravel/nova-issues#1185]
Could not update `laravel/nova` version via composer

- Laravel Version: 5.7.19
- Nova Version: v1.2.0.1
- PHP Version: PHP 7.3.0 (cli) (built: Dec  7 2018 11:00:11) ( NTS )

### Description:
Could not update `laravel/nova` latest release (https://nova.laravel.com/releases/35) via composer 

```  
  [InvalidArgumentException]                                       
  Could not find package laravel/nova in a version matching 1.2.1                                       
```

### Steps To Reproduce:
`composer require laravel/nova:1.2.1` || `composer update`  ( It won't throw any errors )

**Comment by beerbuddha** [comment]
@pavinthan 
- Nova release version that you download vs the nova within composer i believe are two different things.

I have updated effectively to 1.2.1 by doing the typical upgrade of downloading the ZIP then composer update:
https://nova.laravel.com/docs/1.0/installation.html#updating-nova

within composer.json it self:
```
 "laravel/nova": "*",
```
within composer.lock:
```
            "name": "laravel/nova",
            "version": "dev-master",
            "dist": {
                "type": "path",
                "url": "./nova",
                "reference": "6b34fd3882e3cff2dc99d288393e92025bc93094",
                "shasum": null
            },
```

**Comment by pavinthan** [comment]
It's working now
