### ISSUE TITLE
How to display custom value in resource

### ISSUE THREAD

**Issue by aozen** [laravel/nova-issues#1187]
For example i have expire_time column. In the admin panel, clicking user resource, expire_time column looks like "2020-01-03 00:00:00" because its date time format.
But i need to display this like 1 year left, 180 day left. I need my own query when displaying. Can we do that right now? Can't found yet. I search issues too. 
I hope somebody can help me. Thanks in advance :)

**Comment by bonzai** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://larachat.co/).
