### ISSUE TITLE
Problem in localization: ta -> tum

### ISSUE THREAD

**Issue by rapitkan** [laravel/nova-issues#1189]
- Laravel Version: 5.7.19
- Nova Version: 1.2.1
- PHP Version: 7.2.4

### Description:
Text `ta` somehow turns into text `tum`.

### Steps To Reproduce:
* Create a localization file under resources/lang/[language you use]/ folder (e.g. resources/lang/fi)
* Add a localization line `'list_of_flaws' => 'ta'`
* Use localization in a create button of a resource

RESULT: There's a text `Tum` on the button instead of text `Ta`.

**Comment by jbrooksuk** [comment]
@rapitkan can you please provide a more details reproduction guide please?

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
