### ISSUE TITLE
Nova resource update/create bypasses alternative model connection

### ISSUE THREAD

**Issue by mattgriff1995** [laravel/nova-issues#1190]
- Laravel Version: 5.7.19
- Nova Version: 1.2.1
- PHP Version:  7.2.12

### Description: 
When a resource is using a model with an alternative database connection than the application default only the index page works. When trying to update a record or create one it tries to use the default application database causing an error as the table does not exist. This bypasses the one specified on the corresponding model.

### Steps To Reproduce: 

1. Create model and resource and specify an alternative database connection on the model. `protected $connection = 'another_database';`

2. When updating any resource in nova it will bypass this connection and try to insert/update using the application default connection instead of the `$connection` property set on the model

### UPDATE
This only seems to be occurring when I have the following BelongsTo field on my resource

`BelongsTo::make('Assigned', 'assigned', 'App\Nova\Admin')->onlyOnIndex()->sortable(),`

This is using an admin table which uses a different connection to the resource itself, however I do not understand why when this is present the specified connection is ignored

**Comment by sjess** [comment]
Hi there,

same Problem here ... but I have no BelongsTo anywhere.

Just a plain Model:


```
class Movie extends Model
{
    protected $connection = 'umdb';
    protected $table = 'umdb_movies';
    protected $primaryKey = 'movie_id';
    public $timestamps = false;

    protected $guarded = [];
}
```



```
class Movies extends Resource
{
    public static $displayInNavigation = false;
    //public static $with = ['labels'];
    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static $model = 'Novagraphix\Filmpflege\Models\Movie';

    /**
     * The single value that should be used to represent the resource when being displayed.
     *
     * @var string
     */
    public static $title = 'title_product';

    public function subtitle()
    {
        return ""; //"LID: {$this->labels->label_id}";
    }
    /**
     * The columns that should be searched.
     *
     * @var array
     */
    public static $search = [
        'title_product',
    ];

    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [
            ID::make('Movie ID', 'movie_id')->sortable(),

            Heading::make('Film Kopfdaten'),

            Text::make('Sortierungstitel', 'title')->hideFromIndex(),

            Text::make('Deutscher Titel', 'title_product')->sortable(),

            Text::make('Original Titel', 'title_orginal')->hideFromIndex(),

            Number::make('Fame', 'fame'),

            Text::make('Dateipfad', 'filepath')->hideFromIndex(),

            Youtube::make('Youtube-Link', 'yt_link'),
        ];
    } ...
```

The alternative database connection is the model gets ignored ... any suggestions?

**Comment by sjess** [comment]
#1302 

That helped

**Comment by ibrunotome** [comment]
@mattgriff1995 I can confirm that. This type of bug restricts many features of the admin panel @taylorotwell @davidhemphill

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!

**Comment by shineirvin** [comment]
Could you please mention here the patch to fix this issue in lower version ? @jbrooksuk
