### ISSUE TITLE
Actions do not give response

### ISSUE THREAD

**Issue by woutermoelker** [laravel/nova-issues#1191]
- Laravel Version: 5.7.19
- Nova Version: ~1.0.0
- PHP Version: 7.2.9

### Description:
When the action is triggered the black opacity screen triggers but the action its self does not get triggered. Therefore the actions dont work. Nothing shows up in the console or network tab on inspecting the page. No error logs or errors. 

No idea what triggered this or why this happened. 

See the image below for the output of the action button:

![knipsel](https://user-images.githubusercontent.com/7361523/50633132-867f5880-0f4a-11e9-99b0-f260e41ed08a.PNG)

**Comment by bonzai** [comment]
We are unable to debug your issue without a reproducible code example.
