### ISSUE TITLE
BigInt fields are not searchable

### ISSUE THREAD

**Issue by beerbuddha** [laravel/nova-issues#1192]
- Laravel Version: 5.7.19
- Nova Version: 1.2.1
- PHP Version: 7.2

### Description:

If a resource has as primary key bigInt - the result will be displayed in drop box - but when clicked - page will be redirected to 404.

### Steps To Reproduce:

1. create a resource where the primary key of the model is a bigInt
2. add the id as searchable
3. resolve it as a bigInt (only available during the latest release) for field
4. search for item in global search (it will be found)
5. click on resource item from search result
6. get 404 page.

####NOTE:
- While running telescope - it was found that nova-api/resource was receiving the incorrect ID from the front end. Display wise everything is correct as it should with bigInt. For some reason - the bigInt field that was fixed in order to access the resource properly during lists is not being respected during search.
- I have tried to CAST the ID within the model as a string - did not work

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
