### ISSUE TITLE
Login stuck in javascript file after session timeout

### ISSUE THREAD

**Issue by Fawzanm** [laravel/nova-issues#1193]
- Laravel Version: 5.7.*
- Nova Version: 1.2.1
- PHP Version: 7.2

### Description:
I have faced this issue 7-8 times in last couple of weeks. First I thout it's accidental and I may have done a mistake but now it is  kind of annoying. 

When I try to click on a resource after a session time out it takes me back to the nova login page. When give my credentials and submit the page stops in a text/js page. Refer the screenshot below..

### Steps To Reproduce:
Login to nova dashboard
Let the page session timeout
Click on a resource
Once redirected to nova login page, enter the credentials

<img width="1257" alt="screen shot 2019-01-04 at 5 16 40 am" src="https://user-images.githubusercontent.com/2080551/50668015-63a08300-0fe2-11e9-9652-490a56a0a1f2.png">
<img width="340" alt="screen shot 2019-01-04 at 5 16 48 am" src="https://user-images.githubusercontent.com/2080551/50668019-6ac79100-0fe2-11e9-96ab-a77b7b3d1837.png">

**Comment by jbrooksuk** [comment]
I've not been able to replicate this in Nova 2.0.9.
