### ISSUE TITLE
ScrollTo top for navigation & validation errors

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#1194]
- Laravel Version: 5.7
- Nova Version: 1.2.1

### Description:
When you're viewing a resource a few relationships down and click to another resource, you end up in the middle of the page of the next resource. If you trigger validation errors the page stays still with no indication of an error if its the first few fields on a long form.

### Proposed Fixes

add default vue router setting for navigation
```js
export default new Router({
  scrollBehavior() {
    return { x: 0, y: 0 };
  },
```
add scrollTo when errors change in **ValidationErrors.vue**
```html
<script>
    export default {
        props: ['errors'],
        watch: {
            errors: {
                immediate: true, 
                handler (val, oldVal) {
                   window.scrollTo(0, 0);
                }
            }
        }
    }
</script>
```

additionally a error message above the form

```html
<div class="bg-20 text-danger p-6 border-b border-40" v-if="validationErrors.length">
    <p>Form contains errors</p>
</div>
```
**^ Screenshot**
![errors](https://user-images.githubusercontent.com/29180903/50695319-50091280-100a-11e9-9b55-bb528b780ebe.png)

related https://github.com/laravel/nova-issues/issues/416

**Comment by noahlocke** [comment]
This is also especially problematic when creating a resource with many fields where many required fields are at the top of the form. The user has zero indication of any client-side validation errors.

**Comment by noahlocke** [comment]
@dillingham where would you place the first snippet within the 1router/index.js`?

**Comment by dillingham** [comment]
@noahlocke router/index.js yeah
```js
function createRouter({ base }) {
    const router = new Router({
        // scrollBehavior,
        base,
        mode: 'history',
        routes,
    })
```

**Comment by chescos** [comment]
That would be a great UX improvement! The current behavior is annoying in different scenarios. When you have many resources and want to navigate to a resource that is at the bottom of the sidebar, you also need to manually scroll up to the top again after clicking on it.

**Comment by dillingham** [comment]
Pagination would benefit from this also, odd when hitting next and staying at the bottom.

**Comment by chescos** [comment]
I wonder if not implementing this was an active design decision because it seems a no-brainer. Maybe there's a reason it hasn't been done? @davidhemphill could you comment on this?

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by fbingha** [comment]
If I make a sidebar choice and then nothing appears to change, because the page doesn't scroll back up, that is a bug.

**Comment by jtallant** [comment]
Yeah it would be great if this was the default behavior. Users complain about it and I understand why.

You can do it yourself until it's in core by creating a custom asset and putting this in the asset.js

`artisan nova:asset acme/route-middleware`

```js
// nova-components/RouteMiddleware/resources/js/asset.js
Nova.booting((Vue, router, store) => {
    // Force scroll to top on "page load"
    router.afterEach((to, from) => {
        window.scrollTo(0, 0);
    })
});
```

**Comment by tanmuhittin** [comment]
I prepared a small package for that https://github.com/tanmuhittin/nova-scroll-top

**Comment by yehudahkay** [comment]
+1 this should be part of the framework

**Comment by aviuz80** [comment]
I tried to solution proposed by @dillingham and it works.
The side-effect is that the scrollTo top is applied also when filters or pagination are used in resource detail's relationships components
Any idea how to fix/prevent it ?

Thanx

**Comment by dillingham** [comment]
@dillingham this is a bug

**Comment by aviuz80** [comment]
I resolved the issues reported in the previous message by modifying the scrollBehaviour() function as following:

```js
/**
 * The router factory
 */
function createRouter({base}) {
    const router = new Router({
        scrollBehavior(to, from, savedPosition) {
            if (savedPosition) {
                return savedPosition;
            }

            if (from.name !== to.name) {
                return { x: 0, y: 0 };
            }

            if (from.params.resourceName !== to.params.resourceName) {
                return { x: 0, y: 0 };
            }

            return {};
        },
        base,
        mode: 'history',
        routes,
    })

    router.beforeEach(beforeEach)
    router.afterEach(afterEach)

    return router
}
```

I don't know if this quickly solution coverage all the possible use cases, but maybe it could be a starting point for who experienced the same problem.

**Comment by phuclh** [comment]
Does it get fixed in Nova 2.0? I still have this problem.

**Comment by goyote** [comment]
why is this closed with no solution?

**Comment by henryavila** [comment]
@davidhemphill it's no a feature request, it's a bug because it compormise the User experience if the page has many relationships.

Please, consider reopen and fix it!.

**Comment by chescos** [comment]
Sad that this is still an issue

**Comment by gldrenthe89** [comment]
Please fix this.

**Comment by rikless** [comment]
+1

**Comment by bredisvictor** [comment]
Issue is still there, nova 3.0.
This is bug, please fix it!!!

**Comment by jonasbrenig** [comment]
This should really be a core functionality...

**Comment by ragingdave** [comment]
The way this was "fixed" is sort of halfway fix. On a page where there are many fields and the user had a validation error midway through, scrolling to the top is still not the best fix as the user still has to to re-review the entire form to find the error. 

Constructively, I really don't think this was a fix to actually best solve the issue, but (and I could be wrong about this as it's just my opinion) is just a fix to stop the +1/pinging from this issue.

**Comment by jberculo** [comment]
This is no feature request, but a bug. It is really confusing for my users

**Comment by dillingham** [comment]
Ive used this package on a few projects:
https://github.com/dillingham/nova-errors
scrolls to top and modal displays all errors.

**Comment by ragingdave** [comment]
Great alternative! It's still not the best UX IMHO, because on larger forms that approach breaks down as the user has to hunt for the errors. At least scrolling to the first one would get the user to the first error, and really they could "hack" it by just keep trying to submit the form and the app would keep scrolling to the next one. Also, might be alone on this one but never been a fan of modals but that's justmy personal opinion. Either way scrolling to the top is more my issue than the display of the errors up front.

**Comment by dillingham** [comment]
@ragingdave I found it useful on long forms (10+ fields) to see an overview of all the errors. This scrolls to the top and shows all the errors so you can drill down and fix them. The workflow worked nicely for me. Wasn't making any claims as to what the best ux is. Scrolling to the first one sounds pretty logical

**Comment by jberculo** [comment]
Thanks for the response @dillingham! It's an incomplete fix, as the problem with the sidebar and no scrolling up remains, but I'll check it out.
