### ISSUE TITLE
Resource-tool Vue component padding

### ISSUE THREAD

**Issue by LevFlavien** [laravel/nova-issues#1196]
- Laravel Version: 5.7.19
- Nova Version: 1.2.1
- PHP Version: 7.2.13

### Description:

The resource tool Vue component is rendered with some annoying padding. I'd like to display the same table as any resource, but it's made impossible:

![image](https://user-images.githubusercontent.com/14220609/50699024-ef4bfb00-1046-11e9-993b-8d4994556bea.png)

### Steps To Reproduce:

- Create and register a resource tool following the Nova [documentation](https://nova.laravel.com/docs/1.0/customization/resource-tools.html).
- Write `Tool.vue` component template. You can try with the following: 
```vue
<template>
    <div style="border: 2px solid red">
        This is the template's div.
    </div>
</template>
```
- Access resource details. This should be the result:

![image](https://user-images.githubusercontent.com/14220609/50699926-831ec680-1049-11e9-882a-c98fd37c2a23.png)

Rendered HTML:
```html
<div dusk="claims-detail-component" class="mb-8">
    <div>
        <h4 class="text-90 font-normal text-2xl mb-3">Pick products for this claim</h4>
        <div class="card mb-6 py-3 px-6">
            <div resource="[object Object]" class="remove-bottom-border" style="border: 2px solid red;">
                This is the template's div.
            </div>
        </div>
    </div>
</div>
```

**Comment by bonzai** [comment]
You can add negative margins to your template:

```html
<template>
    <div class="-my-3 -mx-6 py-3 px-6" style="border: 2px solid red">
        This is the template's div.
    </div>
</template>
```
