### ISSUE TITLE
EventResource's singular label is not translatable

### ISSUE THREAD

**Issue by weslal** [laravel/nova-issues#1198]
- Laravel Version: 5.7.19
- Nova Version: 1.2.1
- PHP Version: 7.2.4

### Description:
The Action Log shows the wrong singular label in some locales other then English. In Dutch the translation for \`Actions\` is \`Acties\`, but on the ActionResource details page it is converted to a singular version of \`Acties\`, displayed as \`Acty\`, but in Dutch this should be \`Actie\`.

### Steps To Reproduce:
- Create a resource
- Add the Actionable trait to it's model
- Download/make the Dutch translations for Laravel Nova from for example `coderello/laravel-nova-lang`
- Publish the language
- Do an action on the User (like changing it's name)
- Check the User details page and scroll down to view the Actions
- Show an Action
- The title is now showing \`Acty Details\`, which should be \`Actie Details\`

### Possible Solution:
To make the singular version of \`Actions\` also translatable, override the singularLabel() method in the `\Laravel\Nova\Actions\ActionResource` class, with the following line in it:
`return __('Action');`

**Comment by bonzai** [comment]
This has been fixed and will be included in the next release.

**Comment by wessel2105** [comment]
@bonzai 

Laravel: v5.8.34
Nova: v2.1.1

If there are no actions it is still displayed as 'acty'.

In dutch: "Geen acty komt overeen met de opgegeven criteria."
Which in english is: "No action matched the given criteria."

And (to be complete) it should be: "Geen actie komt overeen met de opgegeven criteria."

**Comment by PMassoels** [comment]
I am encountering the same issue. If I extend the Action resource and add it to the same namespace as my regular resources I see the label has been changed. (The config file is updated accordingly)

```
<?php

namespace App\Nova\Resources;

use Laravel\Nova\Actions\ActionResource as BaseActionResource;

class Action extends BaseActionResource
{
    public static function label()
    {
        return 'Test label';
    }

    public static function singularLabel()
    {
        return 'Test label';
    }
}
```

Surfing to '/resources/action-events' gives me the result I would expect, 'Test label'

However, when I go to the detail of an other resource where no actions where executed before I get the following text : 'Geen **acty** komt overeen met de opgegeven criteria.'

@davidhemphill : could you reopen this ticket?
