### ISSUE TITLE
Receiving previous resource filter

### ISSUE THREAD

**Issue by guratr** [laravel/nova-issues#1199]
- Laravel Version: 5.7.19
- Nova Version: 1.2.1
- PHP Version: 7.2.0

### Description:
When navigating from one resource to another, "filters" parameter is not cleared in ajax request(although it disappears from browser window URL). 
It causing problem when you have common Filter for resources A and B, and you choose some options on A, and then navigate to B, you will see filtered result for B, even though there is no indication that some filters have been applied.

### Steps To Reproduce:

- Create resources "A" and "B"
- Create BooleanFilter  "F" with options ['downloaded' => 'Downloaded']
- Include this filter on both resources.
- Go to resource "A", select "Downloaded"
- Go to resource "B" and you will get result filtered "downloaded".

**Comment by dkulyk** [comment]
I think it will be fixed in next release. Filters will retrieved before resources are retrieving.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
