### ISSUE TITLE
Editing Relations: Field doesn't revert to current value when cancelling the dropdown

### ISSUE THREAD

**Issue by carnevalle** [laravel/nova-issues#120]
Nova version: v1.0.5

**How to reproduce**

1. Click edit on a model with a searchable relationship field.
2. Start searching for a value
3. Cancel the search by clicking outside of the input field

**Expected behavior**
The field should revert to the current value

**Actual Behavior**
It leaves the field in an unknown / unselected state. 

<img width="1083" alt="skaermbillede 2018-08-24 kl 11 42 18" src="https://user-images.githubusercontent.com/54747/44578120-176f4780-a793-11e8-8cb7-d4d6f91786df.png">
<img width="1082" alt="skaermbillede 2018-08-24 kl 11 42 44" src="https://user-images.githubusercontent.com/54747/44578122-176f4780-a793-11e8-93da-4a56d414d88b.png">
<img width="1087" alt="skaermbillede 2018-08-24 kl 11 42 48" src="https://user-images.githubusercontent.com/54747/44578123-176f4780-a793-11e8-8bb9-f10c5afdcc8b.png">

**Comment by davidhemphill** [comment]
Not a bug. You wouldn't be able to null out the relationship otherwise.
