### ISSUE TITLE
Update button not display correct

### ISSUE THREAD

**Issue by wefixit-tech** [laravel/nova-issues#1200]
- Laravel Version: 5.7.19
- Nova Version: 1.2.1
- PHP Version: 7.2

### Description:
The buttons not appear correct when update or create a new resource, it shows like without a format and style and dont even work.

![bug](https://user-images.githubusercontent.com/3880643/50731212-2cd28600-1124-11e9-8eec-21e997c05be9.png)

### Steps To Reproduce:
update from version 1.2 to 1.2.1

**Comment by bonzai** [comment]
Make sure you republish your assets:

```
$ php artisan nova:publish --force
```
