### ISSUE TITLE
Lens withMeta missing values in field prop

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#1201]
- Laravel Version: 5.7
- Nova Version: 1.2.1

### Description:

Lenses don't pass withMeta data to the field prop accessible within vue.
This makes it impossible to view a field on a lens and index.
The field renders but doesn't have any of the settings from withMeta

### Steps To Reproduce:

- make a custom field
- pass data ->withMeta(['key' => 'value'])
- console.log(this.field) within mounted within IndexField.vue
- inspect console on index route, see `key`
- inspect console on lens route, **do not see** `key`

### More detail

Im working on a custom button package
I want to suggest to make lens with buttons to keep the main index clutter free. 
"Users Without Confirmation" whereNull confirmed at, show confirm button
It doesn't render the button because I make use of withMeta

**Comment by dkulyk** [comment]
I cannot to reproduce the bug. All meta passed to components.

**Comment by dillingham** [comment]
@dkulyk I was passing withMeta in resolveForDisplay. Sorry
