### ISSUE TITLE
Action Update row

### ISSUE THREAD

**Issue by xerk** [laravel/nova-issues#1202]
- Laravel Version: 5.7
- Nova Version: 1.2.1
- PHP Version: 7.1.3

### Description:
When i update in action i get this error when i use this i got nor error
```
foreach ($models as $model) {
            $model->printed = true;
            $model->save();
}
```
**Error**
`Add [printed] to fillable property to allow mass assignment on [App\Order].`

```
foreach ($models as $model) {
      $model->update(['printed' => true]); 
}
```

**Comment by bonzai** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://larachat.co/).
