### ISSUE TITLE
Filters bar not disabling in detail page relationship

### ISSUE THREAD

**Issue by AhsanAbrar** [laravel/nova-issues#1205]
![Laravel Nova](https://i.imgur.com/4UOyBmB.png)

why showing this extra space?

in fields:
```
BelongsToMany::make('Servers')
```

and in policy:

```
	public function attachAnyServer()
	{
		return false;
	}
```

is this bug or i'm doing something wrong?

**Comment by jbrooksuk** [comment]
This is by design. The padding isn't removed because you've disabled the button.
