### ISSUE TITLE
Class 'Laravel\Nova\NovaApplicationServiceProvider' not found

### ISSUE THREAD

**Issue by sjess** [laravel/nova-issues#1206]
- Laravel Version: 5.7.19
- Nova Version: 1.2.1
- PHP Version: 7.1

### Description:

After `php artisan nova:tool novagraphix/sometool` it blew up the whole app:

```
PHP Fatal error:  Class 'Laravel\Nova\NovaApplicationServiceProvider' not found in D:\repositories\GITLAB\universal\universal_multi_tool - Kopie\app\Providers\NovaServiceProvider.php on line 10

In NovaServiceProvider.php line 10:

  Class 'Laravel\Nova\NovaApplicationServiceProvider' not found
```

It's a known prob i think, saw a thread from last september ....

**Comment by sjess** [comment]
Still there ;)

**Comment by pmochine** [comment]
#169 unfortunately you need to delete the folder nova in vendor/laravel and then composer update

**Comment by webspilka** [comment]
After copying files via FTP to the server, I had the same problem. 
Decided to create symlink from 
vendor/laravel/nova 
to -> {nova files folder}

**Comment by bjolbordi** [comment]
@pmochine Saved my day<3.

**Comment by solarengineering** [comment]
I am still having this issue after  ->composer update  ..  Itblows up for me with the same error " Class 'Laravel\Nova\NovaApplicationServiceProvider' not found" after a fresh install of a card.

**Comment by solarengineering** [comment]
Yeah this is real irritating guys: After laravel blows up after whipping up a new card with -> php artisan nova:card , I got this same issue as OP.      vender/laravel/nova/ doesnt exist and I tried running ->composer update and got the SAME error.
Now I deleted the /nova-components folder as well as the vendor/<new-card>/ folder. Removed the content from the composer.json file and the lock file.

Where else is this card registered from? Im looking for the manifest info but cant find it...

Can anyone tell me where to go to get this newly generated card outta my project completely?

THANK YOU!

**Comment by solarengineering** [comment]
Update from me: I did a few things, but essentially what I was looking for was
-> php artisan cache:clear
-> php artisan config:clear
-> php artisan view:clear

and I got myself back to square one...

Dare I try a card or tool again?!

**Comment by tylernathanreed** [comment]
@solarengineering How have you installed your Nova instance? Was it through GitHub, or locally saved project?

Additionally, have you tried this on the latest version of Nova?

**Comment by badrshs** [comment]
I have same issue here 
I was following the tutorial from  [laracast ](https://laracasts.com/series/laravel-nova-mastery/episodes/12 ) and everything was fine 
until  `php artisan nova:tool  beycode/viewcache ` this error appear 

```
 PHP Fatal error:  Class 'Laravel\Nova\NovaApplicationServiceProvider' not found in C:\Users\bader\Desktop\nova\app\Providers\NovaServiceProvider.php on line 10

In NovaServiceProvider.php line 10:
                                                                 
  Class 'Laravel\Nova\NovaApplicationServiceProvider' not found  
                                                                 

```




`can't do anything now , NovaApplicationServiceProvider exists and there is no problem with that 
any help please ? 
I removed vendor folder and re install everything again , but it didnt work

**Comment by RicLeP** [comment]
Same issue here, fresh Nova 2.0 + Laravel 5.8 install. 404 page on /nova and if I add the service provider it says it can’t find it. I deleted the nova folder, cleared the caches and all the other suggestions but no luck.

**Comment by dkulyk** [comment]
```sh
laravel new test-nova
cd test-nova
composer require laravel/nova
php artisan nova:install
php artisan nova:publish
php artisan migrate:fresh
php artisan nova:user
valet link
open http://test-nova.local/nova
```
It works well.
```sh
$ composer show | grep laravel/
laravel/framework                     v5.8.2   The Laravel Framework.
laravel/nova                          v2.0.0   A wonderful administration interface for Laravel.
laravel/tinker                        v1.0.8   Powerful REPL for the Laravel framework.
```

**Comment by davidhemphill** [comment]
Sorry, but we are unable to debug your issue without a reproducible code example. Once you provide that we can open this up again.

**Comment by Ji20on** [comment]
> 

> `jknbjkbjkbj`

**Comment by massiws** [comment]
Maybe later, but I face the same issue just now.

I used Nova into my project, so I download and unzip Nova into my project but I saw wrong permissions on Nova directories.
A simple solution was changing permissions on all directories: 

`find nova/ -type d -exec chmod 755 {} \;`

and also comment NovaServiceProvider reference in `config/app.php`:

```php
 /*
  * Application Service Providers...
  */
  # ...
  // App\Providers\NovaServiceProvider::class,
```

Hope this helps.
Max

**Comment by arifulhb** [comment]
> #169 unfortunately you need to delete the folder nova in vendor/laravel and then composer update

Surprisingly this worked for me. Thanks.

**Comment by modstore** [comment]
I put "laravel/nova" in "required-dev" instead of "require" and found this issue before I realised what I'd done. Just in case anyone else happens to do the same!

**Comment by elmehdiabdi-src** [comment]
remove the line NovaServiceProvider in config/app.php then composer update

**Comment by mouhradBendjillali** [comment]
i had the same error, check your namespace (it's sensitive...).
