### ISSUE TITLE
Unable to translate 403 error

### ISSUE THREAD

**Issue by FaridAghili** [laravel/nova-issues#1208]
- Laravel Version: 5.7.19
- Nova Version: 1.3.0
- PHP Version: 7.3.0

### Description:
The following string from `403` error page can't be translated:
`The government won't let us show you what's behind these doors…`

Tried this, but didn't work:
```json
"The government won't let us show you what's behind these doors…": "translated-string-here"
````

I was able to translate 404 error page though.

**Comment by bonzai** [comment]
This has been fixed and will be included in the next release.

**Comment by carloshc** [comment]
Please, include the _GO HOME_ button as well.

**Comment by FaridAghili** [comment]
@carloshc 
It's already translatable. You just need to add the `"Go Home": "translation-goes-here"` key to your json file.

**Comment by carloshc** [comment]
@FaridAghili 
You're right, thank you!

This text in 404 page does not translate:

````
"We\\'re lost in space. The page you were trying to view does not exist.": "translated string",
```
 You said that's works, how did you make it?
