### ISSUE TITLE
Feature request: don't hide error notifications automatically

### ISSUE THREAD

**Issue by carnevalle** [laravel/nova-issues#121]
Nova Version: v1.0.5

I am trying to implement Nova and I am getting all sorts of errors in the frontend. 

It would be helpful if these errors didn't automatically disappear, so you could perhaps copy/paste them to seek more information.

**Comment by meyer59** [comment]
Maybe some `notification_hide_delay` in `config/nova.php` to ajust the number of seconds before hiding error/success notification ?

**Comment by davidhemphill** [comment]
I don't think this is something we want to put in Nova, especially now with the availability for debugging using Telescope.
