### ISSUE TITLE
Refreshing the page with a filter selected doesn't show the filtered results

### ISSUE THREAD

**Issue by robertvrabel** [laravel/nova-issues#1210]
- Laravel Version: 5.7.20
- Nova Version: 1.3.0
- PHP Version: 7.2

### Description:

If you a select a filter on a resource then refresh the page you see the full results, not the filtered results. I am doing some joining & a `groupBy('id')` inside my `indexQuery` just for reference. I am not sure if that has any relevance to this issue.

### Steps To Reproduce:

1. Goto a resource
2. Select a filter
3. Refresh the page
4. In my case, I see 4 results, but then the rest get appended after the page loads.

**Comment by dillingham** [comment]
Unable to reproduce

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
