### ISSUE TITLE
Lens support for totals row / rollup values

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#1212]
- Laravel Version: 5.7
- Nova Version: 1.3.0
- Issue Type: request

### Description:

When lenses are used like reports, a common business need will be to have a **totals row**:

| User   | Orders | Spent  | Taxes | Discounts |
|--------|--------|--------|-------|-----------|
| Taylor | 5      | 500.00 | 20.00 | 0.00      |
| David  | 10     | 299.00 | 10.00 | 100.00    |
| **Total**  | 15     | 799.00 | 30.00 | 100.00    |

^ Total row using mysql [with rollup](https://dev.mysql.com/doc/refman/8.0/en/group-by-modifiers.html) perhaps

Considerations:
- Possible need for totals() query on lens
- Possible need for unique conditional component 
- Should be entire total, not paginated total
- May not support non mysql database drivers
- Excluded from rows would be ideal for exporting

**Comment by dkulyk** [comment]
You can count all data in your own export.

**Comment by dillingham** [comment]
@dkulyk I agree assuming export is used. 

This would just save many steps, in nova and excel, for the user who just wants a quick summary total. 

More of an idea / wishlist item

**Comment by vernard** [comment]
+1 for having counts into a lens inside nova.

![image](https://user-images.githubusercontent.com/6733673/51102651-c849b200-181a-11e9-9230-4a40ecbb605c.png)

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
