### ISSUE TITLE
Listable field always preceeds panel

### ISSUE THREAD

**Issue by JapSeyz** [laravel/nova-issues#1213]
- Laravel Version: 5.7
- Nova Version: 1.3.0
- PHP Version: 7.2.10

### Description:
I have two fields defined for a resource, first a panel, and then a listable-field for a relationship.
No matter which order I define them in, the listable field will always be displayed first, however I wish for the panel to be displayed first, as it has the showToolbar method.

Part of Line 268 in ResolvesFields.php:
`$this->filter($this->fields($request))`

The first `$this->fields($request)` return the fields in the correct order, but as soon as they pass through the filter, the orders of the fields are reversed. It doesn't consequently reverse them, it always puts the listable field first, which makes the Panel & toolbar float half-way down the page.

### Steps To Reproduce:
1) Have a resource with a listable field & a panel
2) Try to get the panel with the toolbar to be the first item in the UI.

**Comment by JapSeyz** [comment]
Here's an image of the Fields being defined:

![1](https://user-images.githubusercontent.com/2234034/50871037-a2578400-13ba-11e9-86f0-3ccab73c1d09.PNG)

And here's how it's being displayed:

![2](https://user-images.githubusercontent.com/2234034/50871051-a97e9200-13ba-11e9-85a3-5b881d248a6d.PNG)


The Tabs in the code is the Nova-tabs package: 
https://github.com/eminiarts/nova-tabs

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
