### ISSUE TITLE
npm run production/watch/dev doesn't work from root folder (/nova)

### ISSUE THREAD

**Issue by exzib** [laravel/nova-issues#1214]
> @ watch /home/forge/foxxy.net/nova
>  cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
> 
> internal/modules/cjs/loader.js:583
>     throw err;
>     ^
> 
> Error: Cannot find module '/home/forge/foxxy.net/nova/node_modules/laravel-mix/setup/webpack.config.js'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
>     at Module.require (internal/modules/cjs/loader.js:637:17)
>     at require (internal/modules/cjs/helpers.js:22:18)
>     at requireConfig (/home/forge/foxxy.net/nova/node_modules/webpack/bin/convert-argv.js:97:18)
>     at /home/forge/foxxy.net/nova/node_modules/webpack/bin/convert-argv.js:104:17
>     at Array.forEach (<anonymous>)
>     at module.exports (/home/forge/foxxy.net/nova/node_modules/webpack/bin/convert-argv.js:102:15)
>     at yargs.parse (/home/forge/foxxy.net/nova/node_modules/webpack/bin/webpack.js:171:41)
>     at Object.Yargs.self.parse (/home/forge/foxxy.net/nova/node_modules/webpack/node_modules/yargs/yargs.js:533:18)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! @ watch: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the @ watch script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/forge/.npm/_logs/2019-01-09T11_49_53_417Z-debug.log

After checking in node_modules, laravel-mix doesn't exist at all.

**Comment by exzib** [comment]
I've tried pretty much everything I know of now, without anything working.

**Comment by bonzai** [comment]
Which version of Nova are you using? Did you install the dependencies?

Try running:

```
$ rm -rf ./node_modules/
$ yarn install
```

and if the error persists, please paste the logs (`/home/forge/.npm/_logs/2019-xx-xxTxx_xx_xx_xxxZ-debug.log`).

**Comment by tylernathanreed** [comment]
@exzib 

This happens because the webpack file is intended for production use.

Try this command:

```bash
cd ./vendor/laravel/nova
mv webpack.mix.js.dist webpack.mix.js
```

**Comment by davidhemphill** [comment]
Closed for lack of details or follow-up. Please post a new issue if the issue persists.
