### ISSUE TITLE
Not all texts will be translated, while available in json file.

### ISSUE THREAD

**Issue by blyleven** [laravel/nova-issues#1215]
- Laravel Version: 5.7.20
- Nova Version: 1.3.0
- PHP Version: 7.1 & 7.2

### Description:
It looks like there is something wrong with translating just a couple of texts. Strange thing is: while the sidebar and topbar are actually translated well, some other texts like "Previous" and "Next", or buttons like "Create" are not being translated.

I've already re-installed Nova from scratch and this didn't help. Also I made sure the JSON file is valid. Even when I delete all contents of the translation file, and only add { "Next": "Volgende" } to see if the "Next" text will be replaced, it doesn't.

For clarification I've added some screenshots. 

![schermafbeelding 2019-01-09 om 15 11 10](https://user-images.githubusercontent.com/4598259/50904736-60155d80-1421-11e9-8fc1-5dc2fae094e1.png)

![schermafbeelding 2019-01-09 om 15 23 36](https://user-images.githubusercontent.com/4598259/50905266-ba62ee00-1422-11e9-979a-5c91dec51235.png)

![schermafbeelding 2019-01-09 om 15 25 23](https://user-images.githubusercontent.com/4598259/50905304-cf3f8180-1422-11e9-83b6-2dcea5907070.png)

**Comment by bonzai** [comment]
I can't confirm:

## 1

![zrzut ekranu 2019-01-09 16 17 57](https://user-images.githubusercontent.com/98191/50908516-27c64d00-142a-11e9-94fc-584c36b1884d.png)

## 2

![zrzut ekranu 2019-01-09 16 18 33](https://user-images.githubusercontent.com/98191/50908570-3d3b7700-142a-11e9-8905-a188f1a438a4.png)

**Comment by blyleven** [comment]
@bonzai Thanks. I noticed it had something to do with the middleware I used. 

For future references, when using a locale different than the main app locale set in the Laravel config file, use:

```
Nova::serving(function (ServingNova $event) {
    $this->app->setLocale('nl');
});
```
