### ISSUE TITLE
Broken Filters

### ISSUE THREAD

**Issue by guratr** [laravel/nova-issues#1217]
- Laravel Version: 5.7.19
- Nova Version: 1.3.0
- PHP Version: 7.2.0

Related to https://github.com/laravel/nova-issues/issues/1199

### Description:
In new version, at first there is one request with old filters ( 1 in screenshot), then after filters had been loaded, there is second request ( 2 in screenshot) with correct filters. but in some cases second request ends before first one (because request with empty filters doesn't have to search something in database), and as a result, for a moment you can see the correct result(from request 2), and then table updates again and incorrect results are shown.

![image](https://user-images.githubusercontent.com/1502853/50923219-e6539300-1465-11e9-9b2f-e266e9dd9aba.png)
  
And as you can see on screenshot, after 2 request there is also two identical requests (with correct filters) to retrieve count. It probably related to request 1 somehow. So if you remove redundant first request with incorrect filters, it will be fixed to.

### Steps To Reproduce:

- Create resources "A" and "B"
- Create "F" with options ['correct' => 1, 'incorrect'=>0]
- Include this filter on both resources.
- Go to resource "A", select "correct"
- Go to resource "B" and you will get result filtered with "correct".

**Comment by dillingham** [comment]
did you `php artisan nova:publish` ?

**Comment by guratr** [comment]
Oh, sorry. forgot about that.
