### ISSUE TITLE
Forgot password

### ISSUE THREAD

**Issue by caveoIT** [laravel/nova-issues#1218]
- Laravel Version: 5.7.20
- Nova Version: 1.3.0
- PHP Version: 7.3.0

### Description:
when try to send forgot password request, I've redirected to error 500 page

### Steps To Reproduce:
1- Go to **"https://domain.com/nova/password/reset"**
2- Enter your email address
3- Click on **"Send Password Reset Link"** button

redirected to error 500 page, also the error shows on log file is 

> Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required

**Comment by bonzai** [comment]
Looks like a problem with the SMTP server.
