### ISSUE TITLE
Number field interprets 0 as empty

### ISSUE THREAD

**Issue by andrewrollason** [laravel/nova-issues#122]
Number values of 0 are being displayed as "-" and the field is shown as empty when rendered in forms.

In my data tables I have integer columns such as as:

``` min_holding_months` int(10) unsigned NOT NULL,```

and 0 values are being stored as such.

The corresponding Nova field is simply:

```
Number::make('Minimum Holding Period (months)', 'min_holding_months')
                ->min(0)->max(120)->step(1)->hideFromIndex()
                ->rules('required'),
```

I've tried using a custom resolver to force a 0 but the value at that point is already 0 and it's later in the rendering processing that the 0 becomes "-" (display) or empty (form).  Is something wrongly interpreting 0 as false?

[1.0.3, Safari/Chrome]

**Comment by andrewrollason** [comment]
Possible culprit in nova/resources/js/components/PanelItem.vue ?

```
        <div class="w-3/4 py-4">
            <slot name="value">
                <p v-if="field.value" class="text-90">{{ field.value }}</p>
                <p v-else>&mdash;</p>
            </slot>
        </div>
```

Certainly I've been able to work around this by explicitly casting to string in a custom resolver.

```
            Number::make('Minimum Holding Period (months)', 'min_holding_months')
                ->min(0)->max(120)->step(1)->hideFromIndex()
                ->resolveUsing(function (int $value) {
                    return (string)$value;
                })
                ->rules('required'),
```

**Comment by liamcottle** [comment]
Have also been using the same hack by casting to a string inside of `resolveUsing` to get around this problem...

**Comment by bahamagician** [comment]
I upgraded to the latest v1.0.17 release of Nova and still have this issue.  Is there something else I should be doing to incorporate the latest changes from laravel/nova-js#4 ?

**Comment by dillingham** [comment]
confirmed / reproduced | related https://github.com/laravel/nova-issues/issues/562 https://github.com/laravel/nova-issues/issues/840 https://github.com/laravel/nova-issues/issues/500 https://github.com/laravel/nova-issues/issues/122 https://github.com/laravel/nova-issues/issues/951
