### ISSUE TITLE
Native polymorphic field 

### ISSUE THREAD

**Issue by alberto-bottarini** [laravel/nova-issues#1222]
I think this way of implementing morphable fields is very useful. I should implement natively on Nova:

https://github.com/michielkempen/nova-polymorphic-field

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
