### ISSUE TITLE
Search returns no result on models using Searchable

### ISSUE THREAD

**Issue by NSpehler** [laravel/nova-issues#1223]
- Laravel Version: 5.7.7
- Nova Version: 1.3.0
- PHP Version: 7.1.3

### Description:
When searching a resource associated with a Scout model, Nova always returns no result.

There is no error, all I get is a `{"count":0}` from the request URL https://example.com/nova-api/:model/count in my console.

I've tried querying the model manually with the following, which returned the results successfully, so it seems that it's not a problem with my Scout implementation:
`App\Model::search('Lorem')->first();`

### Steps To Reproduce:
1. Create a model using `use Laravel\Scout\Searchable;` and `use Searchable;`.
2. Create an associated Nova resource and try searching the resource.
3. You should see the message `No :model matched the given criteria.`

**Comment by dkulyk** [comment]
Duplicate of https://github.com/laravel/nova-issues/issues/1188

**Comment by NSpehler** [comment]
Sorry, missed that one. Thanks!
