### ISSUE TITLE
BelongToMany Relationship not working with Pivot Table

### ISSUE THREAD

**Issue by devops-drop** [laravel/nova-issues#1226]
Hello All, 

- Laravel Version: 5.7.20
- Nova Version: 1.3.0
- PHP Version: 7.2

### Description:

When I am using BelongsToMany Relationship in Nova for category and recipe with pivot table, relationship is not showing in list as well as at the time new Recipe create `category field` is not appearing on create recipe page. 

Category Model: App\Category
` 
    public function recipes()
    {
        return $this->belongsToMany(Recipe::class);
    }
`

Recipe Model: App\Recipe.php
`
    public function categories()
    {
        return $this->belongsToMany(Category::class, 'category_recipes');
    }
`

Recipe Resource: App\Nova\Recipe.php

` public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
            BelongsToMany::make('categories')->sortable(),
        ];
    }`

Recipe Table: 
- id 
- name
- description

Category Table
- id
- name
- description

pivot table `category_recipe` Table: 
- id 
- recipe_id
- category_id

Any one can Help me on this? Please let me know.

**Comment by jnorms** [comment]
Hello, 
when working with many-to-many this kind of relationship only appears after it's created on the feature details page. In the case when you create a Recipe go to the details of the created resource and you will see the relationship with categories and you can relate it.

Hope this helps!

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
