### ISSUE TITLE
SUM total on footer

### ISSUE THREAD

**Issue by kokarat** [laravel/nova-issues#1228]
How to sum data specific column on resource footer.
please suggest me to do that.

Thanks!

**Comment by bonzai** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://larachat.co/).

**Comment by ahmed-m-hussain** [comment]
is resolved ?

**Comment by eAvio** [comment]
Is this feature already implemented in Nova 4?
