### ISSUE TITLE
How works the actions?

### ISSUE THREAD

**Issue by eullercdr** [laravel/nova-issues#123]
I created a action and was implementing the method handle, but i cant debug the data.

See code bellow, nothings happens.

`public function handle(ActionFields $fields, Collection $models)
    {

        return dd($models);
        dd($models);

        foreach ($models as $model) {
            dd($model);
        }

    }`

**Comment by Jam0r85** [comment]
What do you want it to do?

It gives you a collection of the models selected (even if its just one model), then just perform an action on each model when looping through?

**Comment by eullercdr** [comment]
@Jam0r85 I was trying to understand how actions works. So, i did try debug, to see date, but the laravel nova ignores dd() and other functions to debug in the method handle, i dont know why.

**Comment by danrichards** [comment]
The actions are being called asynchronously. Try opening chrome inspector and looking under `Network > XHR > Preview`.

<img width="695" alt="screen shot 2018-08-24 at 9 45 49 am" src="https://user-images.githubusercontent.com/470255/44588000-90b26e80-a782-11e8-8892-1d4ebdec1189.png">

**Comment by eullercdr** [comment]
@danrichards Thanks a lot. Its solve my doubt!
