### ISSUE TITLE
Seller Resource not showing only Seller Role Users with nova tool permission Dependencies

### ISSUE THREAD

**Issue by devops-drop** [laravel/nova-issues#1231]
I have created Seller and User Resource both has `App\User` Model I have implemented `NovatoolPermission: https://github.com/Silvanite/novatoolpermissions` to create Roles and Permission, role_user pivot table with `role_id` , `user_id` 

I have created method `indexQuery` in `Seller Resource`
`Seller Resource`:
` public static function indexQuery(NovaRequest $request, $query)
    {
        return $query->join('role_user', 'users.id', 'role_user.user_id')->join('roles', 'role_user.role_id', 'roles.id')->where('roles.slug', 'seller'); // or user 
    }` 

Fetch works properly I am getting all users who has role `seller` but at the time of new seller creation and Role assignment i am getting this: 

`"message": "SQLSTATE[42712]: Duplicate alias: 7 ERROR:  table name \"role_user\" specified more than once (SQL: select \"users\".*, \"role_user\".\"role_id\" as \"pivot_role_id\", \"role_user\".\"user_id\" as \"pivot_user_id\" from \"users\" inner join \"role_user\" on \"users\".\"id\" = \"role_user\".\"user_id\" inner join \"role_user\" on \"users\".\"id\" = \"role_user\".\"user_id\" inner join \"roles\" on \"role_user\".\"role_id\" = \"roles\".\"id\" where \"role_user\".\"role_id\" = 3 and \"roles\".\"slug\" = user order by \"users\".\"id\" desc limit 6 offset 0)",
    "exception": "Illuminate\\Database\\QueryException",`

can Anyone suggest me How to overcome from this issue.

**Comment by devops-drop** [comment]
@dkulyk - Thanks for your answer,this solves the problem.However Role assignment and User Searching is not working for assignment the role to new users

**Comment by bonzai** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://larachat.co/).
