### ISSUE TITLE
Add info text to action modal

### ISSUE THREAD

**Issue by christophrumpel** [laravel/nova-issues#1232]
From what I've seen from the action modal implementation, it is right now not easily possible to add some info text to the action modal. (before the fields)

This would be very useful to explain more what an action does. Sometimes it is not enough to give the action a good name.

![action](https://user-images.githubusercontent.com/1394539/51119938-52dae300-1814-11e9-927b-dabad2ced827.png)

Maybe we can add an `info` property to the Action class.

**Comment by dillingham** [comment]
`->help('Help Text Exists')` but displays after

**Comment by christophrumpel** [comment]
You mean the `field` help method right? Yeah that works, but the purpose is different. I don't want to explain the field, I would want to explain the overall purpose of an action. Like in my example I am approving an event with an action. When the user approves the event, there will be sent out some emails etc. This is what I want to explain to the user.

**Comment by davidhemphill** [comment]
What if there was another field type you could also use inside normal forms?

![Action Heading](https://user-images.githubusercontent.com/58970/51204189-94c56100-18c8-11e9-818c-cd651bb03be3.png)

![Multiple Action Headings](https://user-images.githubusercontent.com/58970/51204077-5760d380-18c8-11e9-8f9a-3c76766e4a30.png)

```php
Heading::make()->content('Some informational text here')
Heading::make()->content('<h3>Section Label</h3>')->asHtml()
```

**Comment by christophrumpel** [comment]
That would be perfect David👌

**Comment by noahlocke** [comment]
Yes please. :)

**Comment by davidhemphill** [comment]
This has been added and will be included in the next release. 👍

**Comment by christophrumpel** [comment]
thx!

**Comment by remipou** [comment]
does it really work in the action modal? doesn't show here (1.3.2)

**Comment by christophrumpel** [comment]
Yes it already works.
![Screen Shot 2019-03-27 at 5 32 27 PM](https://user-images.githubusercontent.com/1394539/55094253-557c7300-50b6-11e9-90c7-b93afffda6a9.png)
