### ISSUE TITLE
Change routeKeyName()

### ISSUE THREAD

**Issue by StanBarrows** [laravel/nova-issues#1233]
### Version:

- Laravel Version: 5.7.*
- Nova Version: 1.3.0
- PHP Version: 7.2

### Opened Requests:

- Support E-Mail via Nova Website
- [Issue on Stackoverflow](https://stackoverflow.com/questions/54086217/laravel-nova-change-routekeyname-to-uuid)

### Description:
Is there a way to change the default RouteKey Name from ID to for example an UUID within Laravel Nova? I did not found anything inside the current documentation.

### Steps To Reproduce:

Default Model-RoutKey is already set to UUID

```
public function getRouteKeyName()
{
 return 'uuid';
}
```

**Comment by bonzai** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://larachat.co/).

**Comment by StanBarrows** [comment]
Thanks, I wrote a Email many days ago & asked on Stackoverflow. No results.

**Comment by dkulyk** [comment]
Only Primary Key used in Nova. If you need to use uuid you need to change PK name in the model.
