### ISSUE TITLE
nova shows server error after uploading my application on server working fine on local enviroment

### ISSUE THREAD

**Issue by ahmed-klabs** [laravel/nova-issues#1234]
my application is running fine in local development environment but when i upload it on server and try to open a view its shows server error

![untitled](https://user-images.githubusercontent.com/46212096/51236272-9019af00-1993-11e9-953e-3ebb0538ba4a.png)

**Comment by webhealer** [comment]
Enable APP_DEBUG=true  from .env file, and check laravel.log for more details. This is not a laravel nova issue, it's related about server configuration.

**Comment by bonzai** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://larachat.co/).
