### ISSUE TITLE
Partition Metric shows above search

### ISSUE THREAD

**Issue by vmitchell85** [laravel/nova-issues#1235]
- Laravel Version: 5.7.16
- Nova Version: 1.3.0
- PHP Version: N/A

### Description:
If you have a partition metric and are using global search the metric graph shows above the search results.

![image](https://user-images.githubusercontent.com/1248035/51246563-b4a46580-1958-11e9-983e-213a02efd977.png)

### Steps To Reproduce:
1. Create metric
2. Search

**Comment by bonzai** [comment]
```
$ php artisan nova:publish --force
```

**Comment by vmitchell85** [comment]
Thought I ran it.. but apparently didn't... fixed me right up...
