### ISSUE TITLE
[Bug] MorphToMany: "Edit Attached" view doesn't get filled with pivot data (with potential fix)

### ISSUE THREAD

**Issue by wfeller** [laravel/nova-issues#1236]
- Laravel Version: 5.7.21
- Nova Version: 1.3.0
- PHP Version: 7.2
- Operating System and Version: Ubuntu 18.04

### Description:
I've got a MorphToMany relation on my model, using a custom `->as()`.

The pivot data is correctly displayed on the index view, but if I want to edit my pivot ("Edit Attached"), then the fields are empty.

### Steps To Reproduce:

Define a MorphToMany on your model using as custom `->as()`, and then add that relation to your Resource.

It will show the pivot fields correctly when you're on the detail page of your parent model, but it won't show them if you click "Edit Attached".

The `->referToPivotAs()` method on the MorphToMany resource doesn't change this behaviour.

### Potential Fix ?
I've managed to make it work by doing the following.

In `Laravel\Nova\Http\Controllers\UpdatePivotFieldController`:

Change this:
```
$model->setRelation(
    $model->{$request->viaRelationship}()->getPivotAccessor(),
    $model->{$request->viaRelationship}()->withoutGlobalScopes()->findOrFail($request->relatedResourceId)->pivot
);
```

To this:
```
$pivotAccessor = $model->{$request->viaRelationship}()->getPivotAccessor();
$model->setRelation(
    $pivotAccessor,
    $model->{$request->viaRelationship}()->withoutGlobalScopes()->findOrFail($request->relatedResourceId)->{$pivotAccessor}
);
```

The `->pivot` instead of `->{$pivotAccessor}` is what's making it fail.

I think the same happens for BelongsToMany relations (see #919)

**Comment by loekwetzels** [comment]
See my [comment](https://github.com/laravel/nova-issues/issues/919#issuecomment-487083814) in #919 
You have to use `withPivot` in your model

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!

**Comment by wfeller** [comment]
Hey @jbrooksuk,

It hasn't changed in Nova 2.0.6.

**Comment by jbrooksuk** [comment]
@wfeller could you please open a new issue.
