### ISSUE TITLE
Ability to Collapse Panel 

### ISSUE THREAD

**Issue by ronnytorresmtz** [laravel/nova-issues#1238]
Hi,
Sometime the panels have secondary information so will be nice to have the ability to collapse them so you can set one or two panels expanded and the other collapsed so the page get shorter and the tables added  like the one created by a relation hasMany are not too deep in the bottom of the page.

**Comment by dmitriytretyakov** [comment]
Why you close this? You added this feature?

**Comment by demency** [comment]
@dmitriytretyakov this repo isnt for features request.
