### ISSUE TITLE
Code field JSON error UTF-8

### ISSUE THREAD

**Issue by Giactan** [laravel/nova-issues#1239]
- Laravel Version: #.#.#
- Nova Version: #.#.#
- PHP Version: #.#
- Operating System and Version: #.#

### Description:
Code field encode error on json.
### Steps To Reproduce:

My Model.php

`class Exam extends Model
{
	public function setConfigAttribute($value)
    {
    	$this->attributes['config'] = json_encode($value,JSON_UNESCAPED_UNICODE);
    }

	public function getConfigAttribute($value)
    {
    	return array_merge(
    		$this->_config,
		    (array) json_decode($value,true)
	    );
    }
}`

Nova/MyModel.php
`Code::make(__('Config'),'config')->language('javascript')->json()`

Result:
![screen shot 2019-01-17 at 4 23 17 pm](https://user-images.githubusercontent.com/31847606/51308292-62586700-1a74-11e9-9558-781bd68ea73a.png)

**Comment by dkulyk** [comment]
```->json(JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE)```

**Comment by jbrooksuk** [comment]
We can apply `JSON_UNESCAPED_UNICODE` flag in the default options, so I've pushed a PR upstream.
