### ISSUE TITLE
[Feature request] Sort relation fields by column (BelongsTo, HasMany etc.)

### ISSUE THREAD

**Issue by StoyanPenev** [laravel/nova-issues#1241]
Hi there!

Currently there is no control over how the related fields are sorted when displayed in the select dropdown lists.
My proposal is to expose a sortBy method on all relation fields and then also update the AssociatableController::index() that prepares the resources listing.
Like so:
```php
BelongsTo::make('Product', null, Product::class)
            ->sortBy('updated_at', 'asc')
```
So in the AssociatableController::index() method instead of getting resources like
```php
'resources' => $field->buildAssociatableQuery($request, $withTrashed)->get()
                        ->mapInto($field->resourceClass)
                        ->filter->authorizedToAdd($request, $request->model())
                        ->map(function ($resource) use ($request, $field) {
                            return $field->formatAssociatableResource($request, $resource);
                        })->sortBy('display')->values(),
```
See we have a hardcoded ``` ->sortBy('display')->values()``` as default ordering, what if we want to display latest updated records first?

A better approach is to perform the ordering based on column and direction (taken from above)
so AssociatableController::index() should perform ordering like:
```php
'resources' => $field->buildAssociatableQuery($request, $withTrashed)->get()
                        ->mapInto($field->resourceClass)
                        ->filter->authorizedToAdd($request, $request->model())
                        ->{$field->sortByMethod}($field->sortByColumn)
                        ->map(function ($resource) use ($request, $field) {
                            return $field->formatAssociatableResource($request, $resource);
                        })->values(),
```
So all changes that need to be done are in the controller index method and probably a shared Sortable trait for the relation fields.
```php
public function sortBy(string $column, string $sortBy = 'desc')
    {
        $this->sortByColumn = $column;
        $this->sortByMethod = $sortBy != 'desc' ? 'sortBy' : 'sortByDesc';

        return $this;
    }
```

finally we can have a default sortByColumn taken from the related $resource::title
so all relation fields should have or this can be defaulted in the controller (not very clear though)
```php
public function __construct($name, $attribute = null, $resource = null)
    {
        parent::__construct($name, $attribute);

        $resource = $resource ?? ResourceRelationshipGuesser::guessResource($name);

        $this->resourceClass = $resource;
        $this->sortByColumn = $resource::$title;
        $this->resourceName = $resource::uriKey();
        $this->belongsToRelationship = $this->attribute;
    }
``` 
I think this can be a great addition to the otherwise awesome Laravel Nova.

It will also resolve one of the closed issues
https://github.com/laravel/nova-issues/issues/156#issuecomment-416018676

Greetings,
Stoyan

**Comment by didix16** [comment]
Hello, have this functionality been implemented yet?

Thanks

**Comment by larshanskrause** [comment]
@didix16 As far as I can tell this hasn't been implemented as of version 3.0.2. I'd really like this feature, too.

**Comment by didix16** [comment]
Oh, ok. Thanks @larshanskrause . We will keep waiting then.

**Comment by bhavinzwt** [comment]
Is there any update on this from Nova?

**Comment by crynobone** [comment]
Implemented: https://nova.laravel.com/docs/3.0/resources/relationships.html#disable-ordering-by-title
