### ISSUE TITLE
scoutQuery() filter returns "no posts found" when filtering on user_id

### ISSUE THREAD

**Issue by tanthammar** [laravel/nova-issues#1242]
- Laravel Version: 5.7.21
- Laravel Scout: 6.1.3
- Nova Version: 1.3.0
- PHP Version: 7.3.0

### Description:
Applying the filter from the documentation returns "no posts found" in the global search.
Using the generated query directly in DB returns 1 post (correct result).

### Steps To Reproduce:
````
public static function scoutQuery(NovaRequest $request, $query)
{
      return $query->where('user_id', $request->user()->id);
}
````

The generated query:
````
select
  *
from
  `companies`
where
  (
    `companies`.`name` like "%Ziemann-Bahringer%"
    or `companies`.`first_name` like "%Ziemann-Bahringer%"
    or `companies`.`last_name` like "%Ziemann-Bahringer%"
    or `companies`.`email` like "%Ziemann-Bahringer%"
  )
  and `user_id` = 1
  and `companies`.`deleted_at` is null
order by
  `companies`.`id` desc
limit
  5
````
<img width="446" alt="scoutqueryindb" src="https://user-images.githubusercontent.com/21239634/51343668-2b477d00-1a97-11e9-8f7f-f06c3df6cfba.png">

![scoutqueryresult](https://user-images.githubusercontent.com/21239634/51343840-9abd6c80-1a97-11e9-8499-acfc465599f5.png)

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
