### ISSUE TITLE
indexQuery() overrides scoutQuery()

### ISSUE THREAD

**Issue by tanthammar** [laravel/nova-issues#1243]
- Laravel Version: 5.7.21
- Laravel Scout: 6.1.3
- Nova Version: 1.3.0
- PHP Version: 7.3.0

### Description:
If I apply any filter to the indexQuery() of a resource, the scoutQuery() is completely overridden/ignored.

### Steps To Reproduce:

````
public static function indexQuery(NovaRequest $request, $query)
{
        // what ever I do here;
 }
public static function scoutQuery(NovaRequest $request, $query)
{
       // overrides any filter I try to apply here;
}
````

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
