### ISSUE TITLE
"Attach & Attach Another" - Select box doesn't reset after attaching

### ISSUE THREAD

**Issue by chrispelzer** [laravel/nova-issues#1244]
- Laravel Version: v5.7.21
- Nova Version: v1.3.0
- PHP Version: 7.2

### Description:
When I attach a resource to another resource using the "Attach & Attach Another" option. It saves the relationship correctly, but the select box will have the option for the resource that I just attached still selected. 

If I click "Attach & Attach Another" or "Attach" then it will say "The {resource} field is required." instead of "This {resource} is already attached.". 

I would need to select a different option in the select box then select the option I just attached for it to realize that an option is selected again to say "This {resource}  is already attached."

### Steps To Reproduce:
1. Create a resource A with an association of resource B
1. Create 1 A resource record and Create 2 B resource records
1. "Attach & Attach Another" B resource record to A resource
1. You'll now see the same B resource record just attached as still selected. Clicking "Attach & Attach Another" or "Attach B" will display the error "The B field is required.".
1. Select the other B resource record not attached yet, then re-select the B resource record you already attached, clicking either "Attach & Attach Another" or "Attach B" will now display "This B is already attached."

**Comment by kirya-dev** [comment]
+1

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
