### ISSUE TITLE
File field's delete button is hidden when file name is quite big

### ISSUE THREAD

**Issue by 4unkur** [laravel/nova-issues#1245]
- Laravel Version: 5.7.21
- Nova Version: 1.3.0
- PHP Version: 7.3
- Operating System and Version: Mac OS Mojave 10.14.2

### Description:

I have a field:
 
```
            File::make('CV File', 'cv_file')->hideFromIndex()->disk('public')->prunable(),
````

![image](https://user-images.githubusercontent.com/7892851/51363717-90d15300-1b03-11e9-9368-1db1be39f2a9.png)

If file name is longer, delete button is not visible at all

**Comment by bonzai** [comment]
This has been fixed and will be included in the next release.
