### ISSUE TITLE
User auth dropdown showing dropdown items on page load

### ISSUE THREAD

**Issue by Jam0r85** [laravel/nova-issues#1246]
On page load, any list items in the logged in user's dropdown menu (top right corner) are visible before the component finishes loading.

Not sure if this is meant to be like this but if, using the vendor view file, you add multiple links to various parts, it soon starts to look a bit odd.

**Comment by jpscharf** [comment]
I have the same issue, if these [v-cloak styles](https://gist.github.com/adamwathan/3584d1904e4f4c36096f]) could be added to the base CSS, or a way to extend the base CSS.

**Comment by bonzai** [comment]
This has been fixed and will be included in the next release.

**Comment by jpscharf** [comment]
I found a way to add v-cloak styles by creating a nova tool:

1. Create a custom Nova tool: `php artisan nova:tool acme/vue-cloak`
2. Open the tool `cd nova-components/VueCloak`.
3. Open the `resources/sass/tool.scss`.
4. Paste in the CSS from [v-cloak styles](https://gist.github.com/adamwathan/3584d1904e4f4c36096f).
5. Open `src/VueCloak.php`, and copy the `Nova::serving(func`… statement.
6. Open `src/ToolServiceProvider.php` and delete everything but the `boot` method.
7. In the `boot` method, delete everything, and paste in the code from step 5, deleting the line referencing `tool.js`.
8. Open `webpack.mix.js` and delete the `js` compilation line.
9. Now run `npm run prod`
10. You can trash the following: `resources/js`, `resources/views`, `routes`, `src/VueCloak.php`, and `src/Http`.
11. Now that the styles have been included, you can update: `resources/views/vendor/nova/partials/user.blade.php` with the v-cloak styles, just add the style `v-cloak--hidden` to whatever elements you would like hidden while Vue is loading.
