### ISSUE TITLE
CSS: Long list of filter options leads to scrollbar in chrome

### ISSUE THREAD

**Issue by m-lotze** [laravel/nova-issues#1247]
### Description:

If you have a long list of filter options a scrollbar appears in chrome when the filter is opened:

![image](https://user-images.githubusercontent.com/7899692/51381989-e878ba00-1b15-11e9-9599-c556b66e1c6f.png)

The whole page is then scrollable beyond the footer. And when you select an option at the bottom, the page scrolls to that position and you have to scroll to the top to see the results.

This can be prevented by adding `position: relative` for the `div` enclosing the filter options.

**Comment by beerwin** [comment]
This also causes the page to jump down when clicking on the filter checkboxes.


* Laravel 5.7.27,
* Nova 1.x
* Chrome latest


**Example steps:** 
1. boolean filters with many values
2. open filters
3. scroll down a bit in the filter dropdown
4. click on one of the newly revealed checkboxes
5. the page jumps down to the clicked item's static offset position (where it would be if the filter dropdown wouldn't have a fixed size)

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
