### ISSUE TITLE
Navigation bar with bug

### ISSUE THREAD

**Issue by jnorms** [laravel/nova-issues#1249]
- Laravel Version: 5.7.21
- Nova Version: 1.3.0
- PHP Version: 7.3
- Operating System and Version: Windows 10

### Description:
Navigation bar appears when zooming in on error pages (404, 403) for example.

### Steps To Reproduce:

1 - Enter a page that does not exist to get the 404 error.

2 - Zoom in the page and you will see on the right side in the lower part the navigation bar.

![image](https://user-images.githubusercontent.com/41594376/51433252-f2d1ab80-1c1c-11e9-8dda-9261790c5bc1.png)

**Comment by davidhemphill** [comment]
Not able to replicate this using the steps you listed.
