### ISSUE TITLE
Not able to save BelongsTo field data

### ISSUE THREAD

**Issue by vnshah** [laravel/nova-issues#125]
I get following error (screenshot attached) when I try to update BelongsTo field. Not sure if I am doing something wrong or if it's an issue in Nova?

Anyone having this issue?

<img width="1186" alt="screen shot 2018-08-24 at 12 38 53 pm" src="https://user-images.githubusercontent.com/272269/44583278-6372ba00-a79c-11e8-99f6-fcbd542a0e26.png">

**Comment by carnevalle** [comment]
I have a similar issue, but this is related to adding a HasMany to a ressource. It gives me the following error.

![Uploading Skærmbillede 2018-08-24 kl. 16.30.15.png…]()

**Comment by vnshah** [comment]
Anyone else having this?

**Comment by carnevalle** [comment]
Mine was apparently related to doing 

`HasMany::make('Post')`

instead of 

`HasMany::make('Posts')`
