### ISSUE TITLE
BelongsTo ->nullable cannot be cleared (option is disabled)

### ISSUE THREAD

**Issue by jarda256sparktech** [laravel/nova-issues#1250]
- Laravel Version: 5.7.31
- Nova Version: 1.3.0
- PHP Version: 7.2

### Description:
If BelongsTo field is nullable. Empty option should be enabled, but it is not.

### Steps To Reproduce:
 BelongsTo::make('User','user',User::class)->nullable(),

**Comment by jnorms** [comment]
did you state in your migration that this relationship could be null?

**Comment by jarda256sparktech** [comment]
yes my field can be null

**Comment by niladam** [comment]
I'm also affected by this. I'm however, using:

Laravel: 5.7.22
Nova: 1.3.2
PHP: 7.2.15.

**Comment by ahmedkandel** [comment]
Me too, On edit page if the BelongsTo is nullable() and searchable() the clear button is present but clearing the relationship **doesn't** affect the database "**set field to null**". While if only nullable() the empty option is **disabled**.

Laravel: 5.7.27
Nova: 1.3.2
PHP: 7.2.10

**Comment by ahmedkandel** [comment]
As a workaround until fixing in next release, set the field to be nullable() and searchable() then as the fillUsing method as following
```
->fillUsing(function (NovaRequest $request, $model, $attribute, $requestAttribute) {
    $model->{$attribute} = $request->{$requestAttribute} ? $request[$requestAttribute] : null;
})
```

**Comment by LorensoD** [comment]
Thanks @ahmedkandel! This temporarily fixed it for me. #89 Was supposed to fix this just by adding `->nullable()` but that still doesn't work for me.

Laravel: 5.7.28
Nova: 1.3.2
PHP: 7.2.12

**Comment by dkulyk** [comment]
This has been fixed and will be included in the next release.

**Comment by JoshMoreno** [comment]
@davidhemphill This should be reopened. There seems to have been a regression.

```php
BelongsTo::make('User')->nullable(),
```

And in my migration
```php
$table->unsignedBigInteger('user_id')->nullable();
```

When you don't chain `->searchable()` you can't deselect the chosen option to make it null. The first option is disabled.
```html
<option value="" disabled="disabled" selected="selected">Choose User</option>
```
The easiest way to get around this is to make it searchable, but this is still a bug.

**Comment by JoshMoreno** [comment]
@davidhemphill Sorry, not a nova issue! 🤦‍♂️
It's an issue with https://github.com/alexbowers/nova-prepopulate-searchable/

And it looks like there is already an issue related to nullable relations - https://github.com/alexbowers/nova-prepopulate-searchable/issues/16
