### ISSUE TITLE
Render edit/detail view using custom javascript

### ISSUE THREAD

**Issue by Rockson** [laravel/nova-issues#1251]
I would like to render the index of the resource using a custom Vue component but I would keep the same edit/detail views.
Something like Nova.#resource name#.editResource(Id).
Is it possible with the latest version(1.3)?

**Comment by bonzai** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://larachat.co/).
