### ISSUE TITLE
Spark and Nova "Teams" label translation conflict?

### ISSUE THREAD

**Issue by tanthammar** [laravel/nova-issues#1253]
- Laravel Version: 5.7.21
- Nova Version: 7.1.3
- PHP Version: 7.3
- Spark 7.1.4

### Description:
I am using Laravel Spark and Laravel Nova in a project with multiple languages.
If I try to translate the "Team" label, in Nova I get an error.

Did double check the json language files for duplicate key/value pairs.

If I use another $key than "Team", for the label(), function in Nova the error is gone.
(No problem with the singularLabel function.)

### Steps To Reproduce:
Code in nova Team resource that causes the error:
```
class Team extends Resource
{
    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static $model = 'App\Team';
    public static $group = 'User';
    public static function singularLabel() {
         //no problem
         return __('Team'); 
     }
    public static function label() {
        //error, if I change this to another key like 'lang_teams' = no error
         return __('Teams');
     }
```

**Error:**

Symfony\Component\Debug\Exception\FatalErrorException thrown with message "Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: htmlspecialchars() expects parameter 1 to be string, array given (View: /private/var/tmp/nova::resources.navigationfHSRGy)"

Stacktrace:
#0 Symfony\Component\Debug\Exception\FatalErrorException in /Users/tina/Sites/bookons/storage/framework/views/cf5a7b20d748dfa876cb508eb9a27612c737b188.php:0

**Comment by jbrooksuk** [comment]
I've just setup Nova and installed Spark as well, but was not able to reproduce this in Nova v2.0.9.

**Comment by telkins** [comment]
@tanthammar @jbrooksuk I'm getting the same error.

```bash
laravel/nova                             v3.8.2    A wonderful administration interface for Laravel.
laravel/spark-aurelius                   v10.1.1   Laravel Spark provides scaffolding for Laravel SaaS applications.
```

I get it for `team`/`teams` as well as for another resource that I made that is similar to teams and has the same kind of language file(s).
