### ISSUE TITLE
Add a streamDownload response to custom Actions

### ISSUE THREAD

**Issue by thechrisroberts** [laravel/nova-issues#1256]
Similar to the Laravel HTTP Response streamDownload method, I'd like to see streamDownload in Nova. My custom action creates a CSV from resource data and I'm wanting to push the csv string to a file download without having to first create a file for it on the server.

**Comment by lucasromanojf** [comment]
I've achieved this by creating a route that uses streamDownload and then doing Action::redirect to this route.
But of course this is a workaround and having this in core would be a lot better.
