### ISSUE TITLE
Upload File Size Error not communicated

### ISSUE THREAD

**Issue by vmitchell85** [laravel/nova-issues#1257]
- Laravel Version: 5.7.16
- Nova Version: 1.3.0
- PHP Version: 7.2
- Operating System and Version: Ubuntu 18

### Description:
When uploading a file that is too large for the settings in php.ini it throws an error indicating the field value was not provided.

It seems Nova isn't checking to ensure the file uploaded or something.

```
SQLSTATE[HY000]: General error: 1364 Field 'path' doesn't have a default value (SQL: insert into `files` (`name`, `description`, `ticket_id`, `client_id`, `created_by`, `updated_at`, `created_at`) values (my_large_excel_file.xlsx, , 1, 4, 1, 2019-01-21 20:46:35, 2019-01-21 20:46:35))
```

### Steps To Reproduce:
1. Have a low max upload
2. Upload a file larger than that.

**Comment by unlikenesses** [comment]
I have a similar problem, except that when I upload a file (actually 2 files) whose combined size is greater than the prescribed limit, it doesn't throw an error. Nothing happens. If I look in the Network tab I see that Laravel throws a `PostTooLargeException`, but this is not reflected in Nova.

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!

**Comment by m2jobe** [comment]
I just ran into this issue on Nova ~2.0

**Comment by jbrooksuk** [comment]
> I just ran into this issue on Nova ~2.0

Please open a new ticket @m2jobe.

**Comment by LucileDT** [comment]
New ticket opened at #3422
