### ISSUE TITLE
Count not using non-default connection

### ISSUE THREAD

**Issue by leigeber** [laravel/nova-issues#1258]
- Laravel Version: 5.7.21
- Nova Version: 1.3.1
- PHP Version: 7.3
- Operating System and Version: Ubuntu 18

### Description:

Just introduced in the latest release, the CountsResources trait is constructing a query based on another without accounting for the original connection. So if that database happened to be something besides the default the request will blow up with an undefined table error. Passing the connection to the DB call resolves the issue.

### Steps To Reproduce:

Load any resource page with a non-default connection. The /nova-api/events/count request will error.

**Comment by Krato** [comment]
I can reproduce this bug.

**Comment by webhealer** [comment]
Same problem  for me. My mongodb  "hasmany" relational data, started give error after last release (Nova Version: 1.3.1) , it's now using default Mysql db connection while counting records. 

`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the `

On the other hand,  non integer primary key problem solved after last release, that's good news.

**Comment by gvsrepins** [comment]
I'm having the same problem after the latest release.

**Comment by bonzai** [comment]
This has been fixed and will be included in the next release.
