### ISSUE TITLE
Dynamic form fields

### ISSUE THREAD

**Issue by lucasromanojf** [laravel/nova-issues#1263]
This feature has been requested in #300 and #355, but I'd like to appeal for it to be implemented again.

This is a very common use case, and should be in core. I know that a lot of people need this too.

I know there is this package: https://novapackages.com/packages/epartment/nova-dependency-container, but it looks like it is abandoned since October 2018. Also, I tested it myself and it does not work properly, it has impeditive issues.

Please, could you add this to core? This is really a must-have feature.

**Comment by ephraimlambarte** [comment]
Is this already implemented? i dont see this in the documentation

**Comment by d0null** [comment]
any news?

**Comment by jaap** [comment]
You can easily do something like this in your Nova Resource;

```
    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function fields(Request $request)
    {
        $standardFields = [
            Text::make('Title'),
            Textarea::make('Content')->required(),
        ];

        // Conditionally add SEO fields if it's a parent item
        if($this->parent_id == null){
            return array_merge($standardFields, [new Panel('SEO details', $this->metaFields())]);
        }

        // Else, return only standard fields
        return $standardFields;
    }

    /**
     * Get the SEO meta fields for the resource.
     *
     * @return array
     */
    protected function metaFields()
    {
        return [
            Text::make('seo_title')->hideFromIndex(),
            Textarea::make('seo_description')->help('Keep it between 50–160 characters')->hideFromIndex(),
            Textarea::make('seo_keywords')->help('Comma separated i.e. "keywordA,keywordB,anotherKeyword"')->hideFromIndex()
        ];
    }
```

**Comment by pokono** [comment]
@jaap You are right, but there is no way to make anything dynamic based on current selections. It's really limiting.

**Comment by Payetus** [comment]
Agree with @pokono
