### ISSUE TITLE
Index Pagination Loading Indicator

### ISSUE THREAD

**Issue by ahmedkandel** [laravel/nova-issues#1264]
Hello, The resource index page doesn't show loading indicator when clicking the pagination links which mislead the user as he doesn't know what is happening. the same issue when searching dropdown BelongsTo relation when searchable(). #220 #365 #594

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
