### ISSUE TITLE
Receiving Models in Action Handle method does not work as stated in the docs

### ISSUE THREAD

**Issue by Naoray** [laravel/nova-issues#1266]
In multiple locations the documentation for `actions` states, that the following works:

```php
public function handle(ActionFields $fields, Collection $models)
{
    foreach ($models as $model) {
        (new AccountData($model))->send($fields->subject);
    }
}
```

Because the `$models` Collection comes back as JSON data only the following approach worked for me:

```php
public function handle(ActionFields $fields, Collection $models)
{
    AccountData::hydrate(json_decode($models, true))
            ->each(function ($accountData) {
                $accountData->send();
            });
}
```

EDIT: Getting the following error when trying to do it like in the docu:
![image](https://user-images.githubusercontent.com/10154100/50653406-b568ef00-0f89-11e9-8d92-3bda131e6743.png)

Can you confirm this issue? Want to have a confirmation before making a PR on this

**Comment by davidhemphill** [comment]
In every scenario I've tested, the Collection $models is working as the documentation states. Can post a configuration that is not working?

**Comment by dkulyk** [comment]
`$models` already is collection of models. In this case `json_decode(Collection, true)` will return `null`
If you need to call `send` for each model you can use
```
$models->each->send();
```

**Comment by Naoray** [comment]
Don't know why it didn't work in the first place. Tested it again and now it worked!

Sorry!
