### ISSUE TITLE
Values equal or lower to 1000 are not being formatted

### ISSUE THREAD

**Issue by dtannen** [laravel/nova-issues#1267]
I used the new ->format option on a value metric.  This is the returned value:
{"value": {"value":100,"previous":86,"previousLabel":null,"prefix":null,"suffix":null,"format":"0%"}}

However, the number shows up as 100 instead of 100% as I expected.    

Am I missing something?

**Comment by bonzai** [comment]
I sent a PR that fixes the issue with formatting but in your case, if you want to use percentage formatting you should provide value in the range of `[0, 1]`:


Number | Format | String
-- | -- | --
1 | '0%' | 100%
0.974878234 | '0.000%' | 97.488%
-0.43 | '0 %' | -43 %
0.43 | '(0.000 %)' | 43.000 %

- http://numeraljs.com/#format

**Comment by dtannen** [comment]
{"value":{"value":1,"previous":1,"previousLabel":null,"prefix":null,"suffix":null,"format":"0%"}}

This still only shows "1" instead of "100%".

**Comment by bonzai** [comment]
My PR hasn't been merged yet (it should be included in the next release). :P

**Comment by dkulyk** [comment]
This has been fixed and will be included in the next release.
