### ISSUE TITLE
Shared Model: Class not found when using Model from different namespace in Resource

### ISSUE THREAD

**Issue by saltbieb** [laravel/nova-issues#1268]
Hey,

I've got a small problem with nova. I would like to share my laravel models over more than one laravel installation. One installation manages the data with Nova. Now I have put my models into an extra composer package which I'm referencing and loading in my laravel projects.

And then I need to connect my models with my Nova resources. Before I have used this line inside my custom resource class:
`public static $model = 'App\Customer';`

And now as I changed the namespace of the models into "{VendorName}/{RepositoryName}" and I try to connect the resource with my model like this:
`public static $model = '{VendorName}\{RepositoryName}\Customer';`

or like this:
`public static $model = {VendorName}\{RepositoryName}\Customer::class;`

then I get the error: Class '{VendorName}\{RepositoryName}\Customer' not found from following file:
vendor/laravel/nova/src/Resource.php

How could I fix this? Is there any need to register my custom namespace?

Thank you in advance!

**Comment by bonzai** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://larachat.co/).
