### ISSUE TITLE
How to hide Field from form only

### ISSUE THREAD

**Issue by devops-drop** [laravel/nova-issues#1269]
I tried to set default value for password and hide field from form. but unable to add user without that,

```
Password::make('Password')->withMeta(['value' => 'secret'])
                ->onlyOnForms()->hideWhenCreating()->hideWhenUpdating()
                ->creationRules('required', 'string', 'min:6')
                ->updateRules('nullable', 'string', 'min:6'),

```
this returns me SQL error because password could  not be` null `

**Comment by noahlocke** [comment]
I think you are misunderstanding `hideWhenCreating`. That means it’s literally absent from the form, not a hidden field. To do what you want you’ll need the hidden field package here:

https://novapackages.com/packages/outhebox/nova-hidden-field

**Comment by devops-drop** [comment]
I have added hiddenfield using nova-hidden-field package. but the concern is when I am submitting form i cannot get hidden field value weather i can perform other action to insert user into `user details table `

**Comment by zainmalonga** [comment]
If you want to automatically set a default password on all created users, You can set the password default value on your database migration like so,

`Schema::create('users', function (Blueprint $table) {
            ...
            $table->string('password')->default(Hash::make('secret'));
            ...
        });`

Then remove the Password::make(...)... field on your resource entirely. 

Each created user will be automatically given the hashed default password

**Comment by bonzai** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://larachat.co/).
