### ISSUE TITLE
Image field - unable to change URL

### ISSUE THREAD

**Issue by johanvanhelden** [laravel/nova-issues#127]
My seeded users have an image, in order to make that editable I am using an image field like this:

```
Image::make(trans('user.attributes.avatar'), 'avatar')
    ->disk('public')
    ->path('users')
    ->storeOriginalName('image_filename_original')
    ->prunable(),
```
The images are stored on the public disk, for example: `/var/www/project/public/uploads`
And in the `users` folder. Like so: `/var/www/project/public/uploads/users`

But whatever I do, it ignores the `path`. It keeps looking at the root of the `public` disk. So the URL comes out like this: `http://project.dev/uploads/filename.jpg` instead of `http://project.dev/uploads/users/filename.jpg`

I've tried implementing the preview method, like so:
```
            Image::make(trans('user.attributes.image'), 'image_filename')
                ->disk('public')
                ->path('users')
                ->preview(function () {
                    return $this->value
                        ? Storage::disk($this->disk)->url('users/' . $this->value)
                        : null;
                })
                ->storeOriginalName('image_filename_original')
                ->prunable(),
```
I've even tried this:
```
            Image::make(trans('user.attributes.image'), 'image_filename')
                ->disk('public')
                ->path('users')
                ->preview(function () {
                    if (empty($this)) {
                        return;
                    }

                    return '/uploads/users.' . $this->image_filename;
                })
                ->storeOriginalName('image_filename_original')
                ->prunable(),
```

But nothing works, it just looks at the `/uploads`.

`$this->value` is also always null, since `$this` contains the Nova resource.

**Comment by parasume** [comment]
Have you tried `$this->$name_of_column_for_image_url>` instead of `$this->value`?

**Comment by johanvanhelden** [comment]
Yes, that works to retrieve the value (see my last code sample) (using dump-server to test it), but it does not affect the actual preview URL. That remains unchanged.

**Comment by sijones-uk** [comment]
Try something like this:

```
Avatar::make(trans('user.attributes.avatar'), 'avatar')
	->disk('public')
	->path('users')
	->thumbnail(function () {
	  return $this->avatar ? Storage::disk('public')->url("users/{$this->avatar}"); : null;
	})
	->preview(function () {
	  return $this->avatar ? Storage::disk('public')->url("users/{$this->avatar}"); : null;
	})
	->storeOriginalName('image_filename_original')
	->delete(function () {
	  Storage::disk('public')->delete("users/{$this->avatar}");
	})
	->prunable(),
```

**Comment by bironeaj** [comment]
I also can confirm this issue. Totally ignoring `->path()` setting.

**Comment by Navi2016** [comment]
Can confirm having the same problem. v1.0.16

**Comment by taylorotwell** [comment]
Hmm, I can't recreate this on my end. What storage driver are you using?

**Comment by johanvanhelden** [comment]
I am using the local driver.

**Comment by Navi2016** [comment]
I'm using local too. Also, try Firefox, the image field has much more issues there than in Chrome.

**Comment by taylorotwell** [comment]
I can't recreate this with the local driver at all. My path is correctly used in the image preview URLs.

```php
            Image::make('Photo')
                    ->disk('public')
                    ->path('photos')
                    ->storeOriginalName('original_name')
                    ->prunable(),
```

![image](https://user-images.githubusercontent.com/463230/45760771-738d8600-bbf0-11e8-9680-7fd5c718d1b0.png)


Image URL: `http://laracon-nova.test/storage/photos/mKCANAGUKer3bnmVMAEoUnRzr7K0gIPHf41Ou1C6.jpeg`

**Comment by sharmaanil8866** [comment]
hello 

i have this code but this code are create this type link 

http://localhost/storage/User-1551607038.jpeg

and my folder location are 

public\uploads\user

Image::make('image')
                    ->disk('public')
                    ->storeOriginalName('original_name')
                    ->prunable()
