### ISSUE TITLE
withMeta doesn't work for Cards

### ISSUE THREAD

**Issue by 4unkur** [laravel/nova-issues#1270]
- Laravel Version: 5.7.22
- Nova Version: 1.3.1
- PHP Version: 7.3
- Operating System and Version: Mojave

I was trying to pass some data to `Card.vue` like it was described in the docs: https://nova.laravel.com/docs/1.0/customization/cards.html#registering-cards

But that didn't work, so I found a workaround: 

I passed my data vie `withMeta` in `NovaServiceProvider.php`

```php
    protected function cards()
    {
        return [
            (new Home)->withMeta(['key' => 'value']),
        ];
    }
```
and this did work. I'm not sure, maybe it's a bug in the docs?

**Comment by 4unkur** [comment]
I reported a bug, this is not a question. `withMeta` is not working with cards like it is described in the docs.  Check https://nova.laravel.com/docs/1.0/customization/cards.html#card-options

There is a method which passes some data via `withMeta`:
```php
    public function currentVisitors()
    {
        return $this->withMeta(['currentVisitors' => true]);
    }
```

in the `Card.vue` I was not able to get `currentVisitors`, but was able to get it only when I passed it in NovaServiceProvider (described in the comment above)

**Comment by bonzai** [comment]
I can't confirm, so I don't think this is a bug.

## 1.

```
$ php artisan nova:card vendor/test-card
```

## 2. TestCard.php

```php
<?php

class TestCard extends Card
{
	// (...)

    public function currentVisitors()
    {
        return $this->withMeta(['currentVisitors' => 9943]);
    }
}
```

## 3. User.php (resource)

```php
public function cards(Request $request)
{
    return [
        (new TestCard)->currentVisitors(),
    ];
}
```

## 4. Card.vue

```js
export default {
    props: [
        'card',
    ],

    mounted() {
        console.log(this.card.currentVisitors)
    },
}
```

## 5.

![zrzut ekranu 2019-01-24 10 38 58](https://user-images.githubusercontent.com/98191/51669203-4567ea80-1fc4-11e9-89dc-b8bdedb1c5c0.png)

**Comment by bucksterbuck** [comment]
Should totally include the part in the docs, where you call the function when you instantiate the class. I got caught up on this for a while too.

**Comment by kopiaman** [comment]
seriously this important part 

`public function cards(Request $request)
{
    return [
        (new TestCard)->currentVisitors(),
    ];
}`

never mention in documentation! i scratched my head for many days for this thing

**Comment by riddla** [comment]
I ended up setting the meta data in the constructor of my custom card as follows:

```php
    public function __construct()
    {
        parent::__construct();
        $this->withMeta(['currentVisitors' => true]);
    }
```

And i second (third ;)) that this should be added to the documentation.

**Comment by mikoop79** [comment]
is this the same for Tools?  not much in the docs about inserting data here

**Comment by jbrooksuk** [comment]
https://github.com/laravel/nova-docs/pull/224

**Comment by cameron-elliott** [comment]
> I ended up setting the meta data in the constructor of my custom card as follows:
> 
> ```
>     public function __construct()
>     {
>         parent::__construct();
>         $this->withMeta(['currentVisitors' => true]);
>     }
> ```
> 
> And i second (third ;)) that this should be added to the documentation.

I don't think I can thank you enough for sharing this tip. I would have been lost trying to figure out how to pass this stuff for cards which are not associated with resources, ie User. Thank you!

**Comment by jbrooksuk** [comment]
The Nova documentation is open source, if you'd like to contribute :) https://github.com/laravel/nova-docs

**Comment by LiamKarlMitchell** [comment]
In vue template I had to put card. in front of the meta keys then I was able to use it.
```
v-if="card.shouldShowSomething"
{{card.something}}
```

**Comment by dmarozau-hot** [comment]
божа якая хуета

**Comment by estiboa** [comment]
I did everything here and i keep getting the data as [object object] as string, and cannot access card from vue. i do see the card data in the cards file at the xhr response tab in console, please help me here?

**Comment by monica-mateu-trioteca** [comment]
> is this the same for Tools? not much in the docs about inserting data here

I supose is the samae for tools, also for Dashboard (I will try it now)..
