### ISSUE TITLE
Global Scope not applied to individual resource

### ISSUE THREAD

**Issue by warksit** [laravel/nova-issues#1271]
- Laravel Version: 5.7.21
- Nova Version: 1.3.0
- PHP Version: 7.2

### Description:
I have global scopes applied to some models (both soft_deletes and custom). These are being applied correctly to the queries for the index pages. They are not being applied when viewing a single resource.

Query generated for index view
```
select
  *
from
  `tickets`
where
  `tickets`.`company_id` = 1
  and `tickets`.`deleted_at` is null
order by
  `tickets`.`id` desc
limit
  26 offset 0
```
Query generated for single resource view
```
select
  *
from
  `tickets`
where
  `tickets`.`id` = "12"
limit
  1
```
I expected the query scopes to be applied to the individual resourse too.

**Comment by dkulyk** [comment]
In detail view used `newQueryWithoutScopes`
If you need to check accessibility for resource you need to use `view` policy for resource.

**Comment by warksit** [comment]
Why does detail view use `newQueryWithoutScopes` rather than respecting the global scopes?

**Comment by dkulyk** [comment]
Global scopes can be used for default filtering(like SoftDeletes).
In this case details pages will be inaccessible.

**Comment by warksit** [comment]
What I think I will do if overide the `detailQuery` fucntion in the resourse. This effectively adds back the where clause from the global scope so the user would see a 404 rather than a 403 (if I used a Policy).
   ```
 public static function detailQuery(NovaRequest $request, $query)
    {
        return $query->where('company_id', $request->user()->company_id);
    }
```

**Comment by warksit** [comment]
> Global scopes can be used for default filtering(like SoftDeletes).
> In this case details pages will be inaccessible.

How would I apply global scope as a default filter?

**Comment by dkulyk** [comment]
See SoftDeletes. By default it added `deleted_at is NULL` to queries.

**Comment by warksit** [comment]
Yes, as did my own global scope. I meant for the detail query.

**Comment by devfrey** [comment]
I'm facing the same issues.

Even if you override the `detailQuery()` method, you'll still be able to update (and view the update page) of the resource **without** a model policy. I've opted to implement both options, but I'm still curious as to why Nova disables all global scopes for its detail/update/delete queries (@dkulyk)?

**Comment by warksit** [comment]
I ended up with a trait that I pull into the Nova resource if I want the detailQuery filtered:
 ````
<?php

namespace App\Nova;

use Laravel\Nova\Http\Requests\NovaRequest;

trait FilterByTenant
{
    public static function detailQuery(NovaRequest $request, $query)
    {
        return $query->where('company_id', $request->user()->company_id);
    }
}
````

I still think the detail query should respect global scopes but will close for now.

**Comment by ralphschindler** [comment]
Feels like this should be re-opened. Global scopes should be respected, and specific behaviors (like soft deletes) should be the exceptional path in the UI.

**Comment by nickkuijpers** [comment]
I would also like to have the global scopes be respected. Every Nova update i download, i do a search and replace of the following:

->newQueryWithoutScopes
with:
->newQuery

I have not found anything not working after this. Do i miss something?

**Comment by matthewjumpsoffbuildings** [comment]
@crynobone please take a look at this, i just ran into the same issue, this is ridiculous, what is the justification for ignoring global scopes in the detail/update views?
