### ISSUE TITLE
BIGINT issues with ->asBigInt()->hideFromIndex()

### ISSUE THREAD

**Issue by web64** [laravel/nova-issues#1275]
- Laravel Version: 5.6.39
- Nova Version:  1.3.1
- PHP Version: 7.2.9
- Operating System and Version: Ubuntu 18.04.1 LTS (Homestead)

### Description:
Clicking view/edit works when using:
```ID::make('Id')->asBigInt()```
but IDs are broken when using:
```ID::make('Id')->asBigInt()->hideFromIndex()```

As the BIGINT IDs are long and take up a lot of space, and I don't really need to see them in the index view I would prefer to hide them.

### Steps To Reproduce:
Create a record with ID higher than 9007199254740991 and click View or Edit for that record in Nova using:
```
ID::make('Id')->asBigInt()->hideFromIndex()
```

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
