### ISSUE TITLE
Resource names partially translated, both singular/plural (language switching)

### ISSUE THREAD

**Issue by tanthammar** [laravel/nova-issues#1276]
Nova 1.3.1
Laravel 5.7.22

I use cookies for language switching.
Singular and plural resource labels are only partially translated.
In the side-menu it is correct but on detail view it is not.

<img width="1422" alt="translated" src="https://user-images.githubusercontent.com/21239634/51737824-d8208c00-208d-11e9-9d20-5ac5c40c16ca.png">
<img width="1407" alt="not-translated" src="https://user-images.githubusercontent.com/21239634/51739036-cd1b2b00-2090-11e9-9c84-a3f2991811ab.png">

Example nova resource:

```
    public static function singularLabel() {return __('Company');}
    public static function label() {return __('Companies');}

```

sv.json
````

    "Company": "Företag",
    "Companies": "Företag",

````

AppServiceProvider.php

`````
public function boot()
{
       if (\Cookie::get('language')) {
             \App::setLocale(\Crypt::decrypt(\Cookie::get('language'), false));
        }
}
`````

Route in web.php

`````

Route::get('language/{lang}', function ($lang) {
    if (array_key_exists($lang, config('app.languages'))) {
        return redirect()->back()->withCookie(cookie()->forever('language', $lang));
    }
    return redirect()->back();
})->name('language');

`````

config/app.php

````

'locale' => 'en',
'languages' => [
        'en' => 'English',
        'sv' => 'Svenska',
    ],
'fallback_locale' => 'en',

````

**Comment by bonzai** [comment]
Nova doesn't use `label` and `singularLabel` for relations.

Try something like this:

```php
SomeRelation::make(__('Users'), 'users', User::class)
    ->singularLabel(__('User')),
```

**Comment by brunogaspar** [comment]
@bonzai 

> Nova don't use label and singularLabel for relations.

Not true though, on Nova 1.1.0, the prior version i have, the relations used to respect what the `label()` returned.

I'm on 1.3.0 at the moment, but i assume that bumping to 1.3.1 will have the same effect.

By the way, your suggestion doesn't work for me, but in all honesty, doesn't makes much sense the need to call `singularLabel()` at runtime like that, as we would end up with a lot of repetition for no reason when this was not happening before.

**Comment by bonzai** [comment]
@brunogaspar: Without using `singularLabel` on relation you will end up with some weird word because Nova will use relation name to create a singular form.

## CityTranslation Resource

```php
public static function singularLabel()
{
    return __('Translation');
}
```

## Without `singularLabel`

```php
HasMany::make(__('Translations'), 'translations', CityTranslation::class)
```

![zrzut ekranu 2019-01-25 18 56 59](https://user-images.githubusercontent.com/98191/51763528-1e4c0e80-20d3-11e9-864b-7b6c3f12bccc.png)

## With `singularLabel`

```php
HasMany::make(__('Translations'), 'translations', CityTranslation::class)
    ->singularLabel(__('Translation'))
```

![zrzut ekranu 2019-01-25 18 58 16](https://user-images.githubusercontent.com/98191/51763558-30c64800-20d3-11e9-8c69-c3c5c5669ca2.png)

So, yeah... "not true though".

**Comment by brunogaspar** [comment]
Seems a breaking change to me.
