### ISSUE TITLE
Add beforeRouteLeave() to Create.vue and Update.vue 

### ISSUE THREAD

**Issue by noahlocke** [laravel/nova-issues#1279]
Right now, there is no fail-safe for a user leaving a half-filled form with unsaved changes. The standard convention for this is to prompt the user by way of `window.onbeforeunload`, or in this case, `beforeRouteLeave`.

**Comment by 4unkur** [comment]
@bonzai will it be added someday?

**Comment by noahlocke** [comment]
@4unkur David asked me to put in a PR for this, so he's totally willing to add it to core. I've been insanely busy and haven't had the time. Feel free to take this one over if you like :)
