### ISSUE TITLE
Search not working with pgsql database

### ISSUE THREAD

**Issue by aemaddin** [laravel/nova-issues#128]
When I try to search on global search or User search there is an error occurred,
<img width="1372" alt="screen shot 2018-08-24 at 2 15 58 pm" src="https://user-images.githubusercontent.com/11630742/44584158-4c39c980-a7a8-11e8-8def-5cbef6dedde0.png">

**Comment by MattMangoni** [comment]
For the time being, you can just remove any ID from the $searchable array of every resource :)
