### ISSUE TITLE
Resource index fetches table contents twice

### ISSUE THREAD

**Issue by kberzinch** [laravel/nova-issues#1281]
- Laravel Version: v5.6.39
- Nova Version: v1.2.1
- PHP Version: 7.2.10
- Operating System and Version: Ubuntu 18.04.1 LTS

### Description:
Nova appears to make two (slightly different) API calls when loading the resource index table contents. Here's a quick screenshot from chrome devtools (running in a prod-identical environment):

![image](https://user-images.githubusercontent.com/10482109/51791870-d4693400-2177-11e9-83b2-96d4ab6c23d9.png)

The two `users` calls are http://hostname/nova-api/users?search=&filters=W10%3D&orderBy=&orderByDirection=desc&perPage=25&trashed=&page=1&viaResource=&viaResourceId=&viaRelationship=&relationshipType= and http://hostname/nova-api/users?search=&filters=W3siY2xhc3MiOiJBcHBcXE5vdmFcXEZpbHRlcnNcXFVzZXJBY3RpdmUiLCJ2YWx1ZSI6IiJ9LHsiY2xhc3MiOiJBcHBcXE5vdmFcXEZpbHRlcnNcXFVzZXJUeXBlIiwidmFsdWUiOiIifSx7ImNsYXNzIjoiQXBwXFxOb3ZhXFxGaWx0ZXJzXFxVc2VyVGVhbSIsInZhbHVlIjoiIn1d&orderBy=&orderByDirection=desc&perPage=25&trashed=&page=1&viaResource=&viaResourceId=&viaRelationship=&relationshipType= in case that's meaningful to anyone.

The performance for this particular table is bad as one of the Nova fields is computed in the model PHP, but making two calls to get that data makes it worse.

This is the only application I have with Nova at the moment, so I don't know if it's something about this code, but it does this on every resource index in every environment.

As I was writing this up, I noticed that our production environment (running an older version of the app for unrelated reasons, with Nova v1.0.19) does not have this issue.

### Steps To Reproduce:

I'll try to reproduce this on a fresh Nova install this weekend if I have a chance, but I wanted to post here in case it's something obvious I'm missing.

**Comment by dkulyk** [comment]
You need to use latest(1.3.0) version of Nova

**Comment by kberzinch** [comment]
I'm still seeing this behavior with Nova 1.3.1 on my local machine. I ran `composer upgrade`, `npm install`, `npm run production`.

**Comment by dkulyk** [comment]
`php artisan nova:publish` ?

**Comment by kberzinch** [comment]
Ah, looks like that fixed it. Thanks!
