### ISSUE TITLE
Use Accessor as column for Trend Metric

### ISSUE THREAD

**Issue by lexdewilligen** [laravel/nova-issues#1282]
Hi! I'm having a One-to-Many relation between Order and Sellable. I've created an accessor to get the total_price for the order (which is the sum of all the sellable prices).

```
    /**
     * Get the orders price.
     *
     * @return string
     */
    public function getTotalPriceAttribute()
    {
        return $this->sellables()->sum('sellables.price');
    }
```

It works fine to display this field in Nova, however, I can't use it as column for a trend metric like for example "Revenue per day".

```
    /**
     * Calculate the value of the metric.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return mixed
     */
    public function calculate(Request $request)
    {
        return $this->sumByDays($request, Order::class, 'total_price');
    }
```

However, Nova returns that the column 'total_price' is not found.

**Comment by bonzai** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://larachat.co/).

**Comment by schmidtflo** [comment]
I have exactly the same issue. For me, this is not a development question, but a bug. When a field is available as a normal Nova field (so just as simple `Number::make('total_price')`, I expect it to be also usable within a metric.

**Comment by jbrooksuk** [comment]
You can build your own results. https://nova.laravel.com/docs/3.0/metrics/defining-metrics.html#manually-building-value-results

**Comment by jonasbrenig** [comment]
I understand that this is not a bug, but a feature.

But it would be a very powerful one since it would allow to make use of all the pre-built functions for metrics.

Maybe you can add this to your backlog.

All the best
- Jonas

**Comment by jonasbrenig** [comment]
I just had the idea of creating an SQL View, using it in a Model and then using that Model for the trend metric.
This way the acessor is defined in SQL but if you get this to work, you can happily use the trend metric.

I just tested this and it works fine.

Still this is a good feature :smile:
