### ISSUE TITLE
Combine unique key validation not respected

### ISSUE THREAD

**Issue by doriandigital** [laravel/nova-issues#1283]
Hi there,

The unique validation rule is not respected when using an additional where clause:

Slug::make('Slug')->rules('required', 'alpha_dash')->creationRules("unique:filters,slug,NULL,id,type,$this->type")->updateRules("unique:filters,slug,{{resourceId}},id,type,$this->type")

https://laravel.com/docs/5.7/validation#rule-unique

**Comment by dkulyk** [comment]
On creationRules you cannot use $this->type.
On updateRules try it:
```php
->updateRules(function ($request) {
    $model = $request->findModelOrFail();
    return [
        "unique:filters,slug,NULL,id,type,{$model->type}"
    ];
})
```

**Comment by doriandigital** [comment]
Hi dkulyk,

Thank you for your quick reply.

How would the creation rule look like without the $this->type? don't you need to specify the value of the additional unique where clause?

**Comment by dkulyk** [comment]
You cat get value from $request['type'] if it is field

**Comment by doriandigital** [comment]
Thank you for all your help!

I managed to get it working with the following code:

`Text::make('Slug')->rules('required', 'alpha_dash', 'max:32')->creationRules("unique:filters,slug,NULL,id,type,$request->type")->updateRules("unique:filters,slug,{{resourceId}},id,type,$request->type")`
