### ISSUE TITLE
belongsToMany using a pivot class has broken in an upgrade to Nova 1.3.1 / Laravel 5.7.22

### ISSUE THREAD

**Issue by greggh** [laravel/nova-issues#1284]
- Laravel Version: 5.7.22
- Nova Version: 1.3.1
- PHP Version: 7.2
- Operating System and Version: OSX 10.14

### Description:
This was working before the upgrade to 1.3.1.

The error happens when attempting to view the detail view of my nova resource. In this case it is named Website / Websites.

The error message:
**Call to Undefined method Illuminate\Database\Eloquent\Relations\BelongsToMany::getForeignKey()**

I have a pivot that requires extra information. To accomplish this I have a class that extends Pivot and provides the belongsTo relationship for that extra field. It has worked fine in Nova and Laravel until this morning when I upgraded to 1.3.1 and 5.7.22 (from 1.3.1 and 5.7.19).

### Steps To Reproduce:
1. Create a belongsToMany relationship between 2 tables.
2. Add an extra column to the pivot table. Make it an ID from another table.
3. Add a Pivot class, and include a belongsTo on it.
4. In Nova, add the BelongsToMany field to the Fields on both models nova resources.
5. Add some data and attempt to view the detail for one of your records.

The code for the belongsToMany relationship:
```
    public function impliedTechnologies()
    {
        return $this->belongsToMany('App\ImpliedTechnology')
            ->using('App\ImpliedTechnologyWebsite')
            ->withPivot(['confidence', 'technology_id'])
            ->withTimestamps();
    }
```

The code for the field looks like this for me:
```
            BelongsToMany::make('Implied Technologies', 'ImpliedTechnologies')
                ->fields(function () {
                    return [
                        Text::make('Confidence', 'confidence')->sortable(),
                        BelongsTo::make('Technology')->sortable(),
                    ];
                })->sortable(),
```

**Comment by dkulyk** [comment]
in 1.3.2 it will be fixed. Also you can specify `reverseRelation` for BelongsTo relations on ImpliedTechnologies resource:
```php
            tap(
                BelongsTo::make(...),
                function ($field) {
                    $field->reverseRelation = 'variations';
                }
            ),
```

**Comment by greggh** [comment]
@dkulyk Thank you! Glad to hear it will be fixed in 1.3.2. I am diving in pretty deep here with this bug report. I've only been really building with Laravel and specifically Nova for a couple months. Tap has been on my list of to-learn functions, along with "with". Time to go familiarize myself with it.

reverseRelation?  I haven't seen that used anywhere, and I can't find documentation on it. What is it doing?

**Comment by dkulyk** [comment]
It has auto detection. Bug in detection. If you specify it - autodetection will be disabled

**Comment by vittorioe** [comment]
any workarounds?

**Comment by robertvrabel** [comment]
Having a similar problem and it used to work in v1.3.1. Can't figure out a workaround.

I have the following code that is reporting `**Call to Undefined method Illuminate\Database\Eloquent\Relations\BelongsToMany::getForeignKey()**`

The reason I have HasMany is because I want a user to create files not attach them in the nova interface.

```
HasMany::make('Files'),
```

Where the relationship is:

```
    /**
     * Get the files associated with the article.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function files()
    {
        return $this->belongsToMany('App\File')->withTimestamps();
    }
```

**Comment by robertvrabel** [comment]
Follow up to my previous post. I figured out the relationship that was wrong for me, however it was working in 1.3.1. Looks like the Nova field needs to match the relationship specified exactly. I had a situtation where I wanted the UI to act as a BelongsTo but my database allows for files to be associated to multiple articles (BelongsToMany). I'll just use a BelongsToMany for now.

```
            BelongsTo::make('Articles')
                ->exceptOnForms(),
```

```
    /**
     * Get the files for articles
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function articles()
    {
        return $this->belongsToMany('App\Article')->withTimestamps();
    }
```

**Comment by vmitchell85** [comment]
Got the same error **"Call to Undefined method Illuminate\Database\Eloquent\Relations\BelongsToMany::getForeignKey()"**

My case was a bit different...

In my Nova Class:

```php
BelongsTo::make('Created By', 'creator', 'App\Nova\User')->hideWhenCreating()->hideWhenUpdating()
```

In my Model:

```php
public function creator()
{
    return $this->belongsTo(User::class, 'created_by');
}
```

**Comment by jbrooksuk** [comment]
You'll also need to make sure you're on Laravel v5.7.15 for the `getForeignKey` method to work.

**Comment by dkulyk** [comment]
It has fixed in v1.3.2

**Comment by jbrooksuk** [comment]
Yes, but only if you're on v5.7.15 otherwise the methods it uses doesn't exist.

**Comment by calvinmuller** [comment]
dafuq

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
