### ISSUE TITLE
Deleting a child resource does not redirect to parent details page

### ISSUE THREAD

**Issue by unlikenesses** [laravel/nova-issues#1285]
- Laravel Version: 5.7.20
- Nova Version: 1.3.0
- PHP Version: 7.1
- Operating System and Version: Mac Os 10.13.4

### Description:

I have a resource `Foo`:

```
public function fields(Request $request)
{
    return [
        HasMany::make('Bars')
    ];
}
```

and a resource `Bar`:

```
public function fields(Request $request)
{
    return [
        BelongsTo::make('Foo'),
        Text::make('Title')
    ];
}
```

In my Nova admin, I can go to the a particular `Foo`, click "Create Bar", and on the "New Bar" page enter a `title` and click "Create Bar". The `Bar` is then created and associated with the `Foo` correctly. I am then on the "Details" page for the newly created `Bar`. If I now click the "Delete" button, the `Bar` is deleted but instead of being returned to its parent `Foo` page, it returns me to a list page for all `Bars`. Since `Bars` only make sense in relation to their parent, this page should never really be seen.

**Expected:** After deleting a child resource, I should be redirected to the parent's detail page.

**Actual:** After deleting a child resource, I am redirected to a listings page for that resource.

**Comment by tylernathanreed** [comment]
@unlikenesses 

What if `Bar` also belonged to a separate resource, `Baz`, where the parent relationship is not a cleanly determined? What would the expected functionality be then?

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
