### ISSUE TITLE
create only a field for ID (Not for Type) using MorphTo::make

### ISSUE THREAD

**Issue by shradhabanerjee** [laravel/nova-issues#1286]
- Laravel Version: 5.7
- Nova Version: 1.3.0 
- PHP Version: 7.1.19
- Operating System and Version: MacOS Mojave 10.14.2

### Description:

When I use MorphTo::make to make the fields in resource page, it creates 2 fields:

1. Field for "Type" column
2. Field for "ID" column

For some reason, I just a field for ID column to be generated. When I remove the MorphTo::make both the fields disappear.

### Steps To Reproduce:

`MorphTo::make('Rentable', 'rentable')->types([Home::class])->hideWhenUpdating(),`

I have the above code in my resource file, this creates 2 fields, one for the rentable_type, which is home and another for rentable_id which has the id for the home. I do not want this rentable_type, want only rentable_id on my form. 

I am adding this rent resource from home resource page, so again specifically do no want this repetition of type. Also in future I can have shops to rent, so I have it as MorphMany relation.

Below is the screenshot of what I have,

<img width="961" alt="screenshot 2019-01-28 at 4 07 17 pm" src="https://user-images.githubusercontent.com/46675689/51831111-5ba0de00-2317-11e9-913c-cd6830eaa727.png">

Thanks in advance !

**Comment by dkulyk** [comment]
If you have only one related type you can use BelongsTo field.

**Comment by shradhabanerjee** [comment]
Thanks for the reply @dkulyk .

I have this the Rent resource associated with Homes, Shops, Gymnasium, etc. It's not only Home. I just do not want the first select box which says "rentable" and "home" value in it selected. This is because on **Home resource page**, I have `HasMany::make('Rents', 'rents', Rent::class)`. Hence there is no reason for having the select box for rentable again, as the user already knows he is on the page of home to rent. 

Thanks!

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
