### ISSUE TITLE
Table doesn't exist on multiple database connections on 1.3.1

### ISSUE THREAD

**Issue by regiszanandrea** [laravel/nova-issues#1288]
- Laravel Version: 5.6.39
- Nova Version: 1.3.1
- PHP Version: 7.2
- Operating System and Version: MacOs 10.13.5

### Description:

I got this error below on index page from a Resource that has other database connection.

```
Base table or view not found: 1146 Table 'calisto.banners' doesn't exist (SQL: select count(*) as aggregate from (select 1 from `banners`) as `count_temp`)
```

The content from the other database show correctly, but after the load this error appers.

Printscreen:
![screen shot 2019-01-28 at 11 30 29](https://user-images.githubusercontent.com/2692748/51839388-3ea4e480-22f0-11e9-997f-d2ecc740204f.png)

### Steps To Reproduce:
1. Create a Model and set the $connection variable to other database connection
2. Create a Resource
2. Go to Resource's index page

**Comment by webhealer** [comment]
I am experiencing same issue, referenced here:
https://github.com/laravel/nova-issues/issues/1272

Waiting for next release.

**Comment by bonzai** [comment]
👆

**Comment by tamilps2** [comment]
Hi,

I am having the same issue while using non-default database connection on models. I have the latest versions of all the packages and laravel.

- Nova - v2.0.1
- Laravel - 5.8.13
- PHP - 7.2

Same as #1258, #1302 and #1272

Any help/pointers would be really appreciated.

Thanks.
