### ISSUE TITLE
ResetPassword not not using nova guard but laravel provider. Specialy tricky if you change laravel default provider

### ISSUE THREAD

**Issue by nenads** [laravel/nova-issues#1292]
- Laravel Version: 5.6.#
- Nova Version: 1.31.#
- PHP Version: 7.1.9
- Operating System and Version: WIndows 10
- Browser type and version: Chrome

### Description:

When we change defualt auth in laravel and define diff nova guard.

in laravel
`
    'defaults' => [
        'guard' => 'client-web',
        'passwords' => 'clients',
    ],
`

`
'passwords' => [
        'users' => [
            'provider' => 'users',
            'table' => 'password_resets',
            'expire' => 60,
        ],
        'admins' => [
            'provider' => 'admins',
            'table' => 'password_resets',
            'expire' => 60,
        ]
    ],
`

in nova:

`guard' => env('NOVA_GUARD', 'web'),`

nova will try to use laravel gate

InvalidArgumentException Password resetter [clients] is not defined.

### Steps To Reproduce:

1. go to nova login
2. select reset password
3. enter email
4. submit.

**Comment by nenads** [comment]
if i define client it will just look in diff place.

`'clients' => [
            'provider' => 'clients',
            'table' => 'password_resets',
            'expire' => 60,
        ],`

**Comment by nenads** [comment]
Ignore this refers to having diff password for nova and laravel #1051

**Comment by ChrisReid** [comment]
I've just created a fix for this:

```

**Comment by ChrisReid** [comment]
I've just created a fix for this:

Override Nova's `ResetPasswordController` by creating a new file at `app/Http/Controllers/Auth/NovaResetPasswordController.php`


```
<?php

namespace App\Http\Controllers\Auth;

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Config;

class NovaResetPasswordController extends \Laravel\Nova\Http\Controllers\ResetPasswordController
{
    /**
     * Get the guard to be used during password reset.
     *
     * @return \Illuminate\Contracts\Auth\StatefulGuard
     */
    protected function guard()
    {
        return Auth::guard(Config::get('nova.guard'));
    }
}
```

Then to call this password reset controller in place of Nova's default controller, by adding this to the register method of `App\Providers\NovaServiceProvider`

```
   /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        $this->app->bind(ResetPasswordController::class, NovaResetPasswordController::class);
    }
```

Don't forget to import the classes.

```
use App\Http\Controllers\Auth\NovaResetPasswordController;
use Laravel\Nova\Http\Controllers\ResetPasswordController;
```

Now the guard is used according to the selection in the `config/nova.php` file.

I vote to accept a PR to include this in the packages controller.

Thoughts?
