### ISSUE TITLE
Environment File not loading consistently

### ISSUE THREAD

**Issue by tylernathanreed** [laravel/nova-issues#1294]
### Setup:
- Laravel Version: 5.7.22
- Nova Version: 1.3.1
- PHP Version: 7.1.7
- Operating System and Version: Windows 7 Professional
- Browser type and version: Chrome 71.0.3578.98 (Official Build) (64-bit)
- Server: Hosted locally via WAMP

### Description:

There are times when I am loading a page (not one specifically, but really any page that makes a database call), and sometimes (not always), I'll see the following error:

```
Access denied for user 'forge'@'localhost' (using password: NO) (SQL: select * from `users` where `id` = 1 limit 1)
```

I know what you're thinking, and yes, I've set up my environment file. The only database variable I have in my environment is `DB_CONNECTION = "sqlite"`, meaning I'm using a SQLite database. Additionally, I don't believe that I've changed the database config file either:

```
        'sqlite' => [
            'driver' => 'sqlite',
            'database' => env('APP_ENV') === 'testing'
                ? database_path('testing.sqlite')
                : env('DB_DATABASE', database_path('database.sqlite')),
            'prefix' => '',
        ],
```

Essentially, it looks like Laravel is somehow forgetting about my environment file, and is instead deferring to the default settings (mysql, forge@localhost). What's unusual about this is that it doesn't happen all of the time. My guess is that a bucket load of ajax requests are trying to load various relations, and perhaps the request locks the .env file, forcing other ajax requests to use the default settings.

For now, I can probably get away with changing the fallback settings to use sqlite as well, but that won't fix the second error I'm seeing:

```
No application encryption key has been specified
```

This again points to the fact that Laravel is somehow unable to read my environment file at all times.

I'm not certain if this is because of Nova's heavy use of ajax requests, or if there's something else going on within the Laravel framework.

Additionally, I've tried this with a local copy of the "nova-dusk-suite" project. I'm seeing this error happen more consistently on the user detail page, as that one seems to load the most relationships (and therefore ajax requests).

Also, I tried caching my configuration, as I believe that bypasses the .env file. When cached, I am unable to produce this error.

### Steps To Reproduce:

Go to a page that makes use of several ajax requests, and refresh the page until this error appears.

**Note:** The error may not always appear in the UI. I've seen cases where the error goes to the log file, and doesn't appear in the UI.

**Comment by dillingham** [comment]
I saw someone else mention this recently. I’ve never experienced this, but maybe it’s related to sqlite too.. which I don’t use.

**Comment by dillingham** [comment]
Here is a thread on the topic with lots of links to other threads. https://github.com/laravel/framework/issues/24510#issuecomment-395865724

**Comment by tylernathanreed** [comment]
@dillingham Thanks, that was really insightful.

However, that issue appears to be closed. Was a solution ever proposed?

I imagine that this is more of an issue with the DovEnv library, and not Nova or Laravel.

**Comment by davidhemphill** [comment]
Closing as this is an issue higher up in the chain and not really something we could patch in the meantime.
