### ISSUE TITLE
(SQL Server) Error in generated sql aggregate count query after update to v1.3.1

### ISSUE THREAD

**Issue by klepak** [laravel/nova-issues#1295]
I'm getting an error "No column name was specified for column 1 of 'count_temp'" on all my resources after updating to v1.3.1.

Looks like SQL Server doesn't like the syntax of the generated SQL command: "select count(*) as aggregate from (select 1 from [table]) as [count_temp]"

If I try to run the command manually, I have to add a column alias to the select 1 statement, to make the query run.
"select count(*) as aggregate from (select 1 as aliascol from [table]) as [count_temp]"

**Comment by dkulyk** [comment]
@bonzai
