### ISSUE TITLE
BelongsTo field, chrome error

### ISSUE THREAD

**Issue by tanthammar** [laravel/nova-issues#1296]
Nova v 1.3.2
Chrome 71.0.3578.98

If I add the **belongsTo** field to a resource I get an error in chrome. (Same error in Firefox)
- All views, index, detail, form ...
-

````
vendor.js?id=b30263b2f9d68433c3ce:1 [Deprecation] Using unescaped '#' characters in a data URI body is deprecated and will be removed in M71, around December 2018. Please use '%23' instead. See https://www.chromestatus.com/features/5656049583390720 for more details.

````

**Comment by davidhemphill** [comment]
That error doesn't affect the BelongsTo field. Also make sure you've published the latest Nova assets in your project: `php artisan nova:publish --force`.

Without more information or error output, we're unable to debug this with you.
