### ISSUE TITLE
Show Nova Card on Resource Detail view

### ISSUE THREAD

**Issue by tanthammar** [laravel/nova-issues#1298]
I feel very stupid but I can't figure out how to get the card to show on the detail view.
It is automatically showing on the resource index view.

The Nova docs does not describe how, only this:

> Cards are similar to resource tools, but are small, miniature tools that are typically displayed at the top of your dashboard, resource index, or **resource detail screens**.

And in the card stub:

```
props:
 [
        'card',

        // The following props are only available on resource detail cards...
        // 'resource',
        // 'resourceId',
        // 'resourceName',
    ],

```
Must be something missing in the docs.

**Comment by Fawzanm** [comment]
Nova card'c cannot be displayed in the detail view page AFAIK. If you really want to do it `resource-tool` is the way to do it. That's how I got around the issue.

**Comment by tanthammar** [comment]
I found it:
The Card extends Element where the $onlyOnDetail boolean is defined, just like any field.
In resource:
```
public function cards(Request $request)
    {
        return [
            (new YourCardClass)->onlyOnDetail(),
        ];
    }

```

**Comment by tanthammar** [comment]
Closing as it is solved.

**Comment by dillingham** [comment]
@Fawzanm can you share your code?

**Comment by 93gaurav93** [comment]
@tanthammar  You saved my life. Thank you do much. 😊
