### ISSUE TITLE
Computed field closure should not be called on pages that the field is set not to show on

### ISSUE THREAD

**Issue by jtallant** [laravel/nova-issues#1299]
- Laravel Version: "v5.7.22"
- Nova Version: 1.3.1
- PHP Version: 7.3.0
- Operating System and Version: mojave 10.14.2
- Browser type and version: Chrome Version 71.0.3578.98 (Official Build) (64-bit)

### Description:
Computed field closure should not be called on
pages that the field is set not to show on.

## Computed Field Closure called when it shouldn't be
```php
// app\nova\SomeResource.php
Boolean::make('Own Residence?', function() {
    return $this->property->ownedByApplicant();
})->onlyOnDetail()
```
1. Define a computed field that accesses a property of `$this`
1. Visit resource create page
1. See error "Call to a member function ownedByApplicant() on null

**Comment by davidhemphill** [comment]
You should check for the existence of a `property` as the underlying model instance might not be hydrated from the database.

**Comment by jtallant** [comment]
@davidhemphill Yeah that's what I'm doing now but it leads to a bunch of nasty "isset" style code in closures that shouldn't even be called unless the property is set anyway since it's onlyOnDetail. When you have a lot of fields all that existence checking adds up to some ugly code. It's just not what I want my laravel or nova codebase to look like. Seems like somewhere along the line these fields should be filtered out from pages they won't be displayed on resulting in the closure not being called.

**Comment by kirya-dev** [comment]
Im agree with 

> @davidhemphill Yeah that's what ...

Problem realy exists!
For fix this problem need use "resolve" methods in nonCreationFields... & nonUpdationFields...
