### ISSUE TITLE
UUIDs getting converted to zeroes.

### ISSUE THREAD

**Issue by koomai** [laravel/nova-issues#13]
To reproduce, create a table with the id column as below.

`id char(36) NOT NULL`

Then create a model and corresponding Nova resource and load the index view.

The links on the details or edit icons will all look like this `.../resource-name/0`

**Comment by Stiropor** [comment]
You need to set `public $incrementing = false;` in your model, had the same issue

**Comment by koomai** [comment]
@Stiropor D'oh!  Thanks 👍🏼
