### ISSUE TITLE
Add multiple Trend Metrics in one card

### ISSUE THREAD

**Issue by Gil-1** [laravel/nova-issues#1301]
Allow to compare trends and have multiple lines drawed.

Example :
```php
        return $this->sumByMonths($request, Model::where('created_at', '>', Carbon::now()->subMonths(6)), 'amount')
            ->compareWith(Model::where('created_at', '>', Carbon::now()->subMonths(12)), 'amount');
```

The purpose would be to have multiple lines in the card with different colors to be able to compare easily different trends.

**Comment by fgilio** [comment]
@bonzai was this issue closed by any particular reason? I think this would be a pretty useful thing to have

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by fgilio** [comment]
Thanks for explaining David 👍

**Comment by bolechen** [comment]
+1

**Comment by vesper8** [comment]
Is it at all possible to do multi-dataset line charts with the built-in nova trend metrics? or can this only be accomplished by using a 3rd party plugin?
