### ISSUE TITLE
Adding a cap on the HasMany field

### ISSUE THREAD

**Issue by beerwin** [laravel/nova-issues#1303]
Hi David,
I have a use case which is rather odd, but still legit:
This is not about limiting the HasMany field count on listings, it is about preventing to add more items to a HasMany relationship (even, if it's only by hiding the create button when the cap is reached).

Consider a model, which has a HasMany relationship with another model, but there should be a cap on how many owned items can be added to the owner.

**Context:** We have some IoT devices, which send telemetry to our system. The telemetry has one particular data for which our system needs to send notifications. Notifications should be sent for two distinct values. So we created a HasMany relationship to create alerts for these values. This limit is bound to change in the future.

Currently, I solved the problem by adding a listener on the creating event of the owned model, so if the owner already has the maximum number of alerts added, it will prevent adding more, and a toast message is returned. However, it looks odd, to have a create button when the user isn't allowed to add more.

Authorization policies for the owned models are not a good fit, as they don't provide access to the model on the create method (since there is no model instance at this point yet).

**Workflow and expected behavior:**
1. User adds items to the HasMany field
2. Supposed cap reached
3. Create button no longer visible (it is not required to put a limit on the HasMany relationship itself, as that already can be done with events/listeners)

**So, two questions:**
- is there already any way to add a cap to the HasMany field?
- if not, may I ask to consider this as a feature to be added, such as
```
HasMany::make('Field Name', 'field_name', OwnedModel::class)
    ->cap(2)
```
Kind regards,

**Comment by jasonmccuen** [comment]
I have a similar need. My use case is:

* I have a tutor who can have multiple students, but each student can only have one tutor.
* I need to select a tutor and assign multiple students
* I need to select a student and select their tutor.

Am I missing something in the documentation or am I just thinking about this wrong?

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
