### ISSUE TITLE
Refactor Nova::resourceInformation to defer to Resource class

### ISSUE THREAD

**Issue by tylernathanreed** [laravel/nova-issues#1304]
As the title suggests, I would like the `Nova::resourceInformation` to be changed in such a way that I can override it from the Resource class, rather than having to replace the entire Nova class definition. This method currently adds a fixed set of keys and values, and I would like to be able to append to this list. I would propose having a static `Resource::information` method that simply returns the current implementation.

As an example, I'm working on associating icons with all of my resources. This was easy to do on all of the blade templates, since I have a PHP instance of the resource. However, I'm also overriding some of the Vue components, and being able to access the icon from the resource information would be extremely helpful (essentially, anything with the `InteractsWithResourceInformation` mixin would have access to this information).

As I continue to expand my application, I'll likely be adding more top-level information that will be relevant for all resources, and I'll need the information in my Vue components.

I suspect that this change would easily take less than an hour to do. I'd do it myself, but we can't exactly make PRs for Nova.

**Comment by davidhemphill** [comment]
Sure you can. Head to https://nova.laravel.com/settings#github and connect your GitHub account, fork the repo and make a PR. 👍

**Comment by tylernathanreed** [comment]
@davidhemphill Amazing! Thanks for that.

I'll start working on that PR.

**Comment by dkulyk** [comment]
This has been added and will be included in the next release. 👍
