### ISSUE TITLE
Allow displayUsing on forms

### ISSUE THREAD

**Issue by Livijn** [laravel/nova-issues#1305]
Can you please add support for `displayUsing()` when editing/creating. I have a `BelongsTo`-field and when selecting a relation I need to show additional information.

https://nova.laravel.com/docs/1.0/resources/fields.html#field-resolution-formatting

**Comment by kemhwd** [comment]
You can do exactly the same thing with resolveUsing() function.
https://nova.laravel.com/docs/1.0/resources/fields.html#field-resolution-formatting

**Comment by davidhemphill** [comment]
Use `resolveUsing` for this use-case.
