### ISSUE TITLE
BelongsToMany Field ignores the relatedKey

### ISSUE THREAD

**Issue by Grafikart** [laravel/nova-issues#1306]
## The issue

I have a relation based on a non conventional key

```php
public function posts () 
{
    return $this->belongsToMany(Post::class, null, null, 'post_uuid', 'id', 'uuid');
}
```

I create a belongstoMany field but when I want to attach the Post to my content the select uses the primary key instead of my uuid key. 
The problem comes from the method [formatAttachableResource](https://github.com/laravel/nova/blob/master/src/Fields/BelongsToMany.php#L233)

```php
    public function formatAttachableResource(NovaRequest $request, $resource)
    {
        return array_filter([
            'avatar' => $resource->resolveAvatarUrl($request),
            'display' => $this->formatDisplayValue($resource),
            'value' => $resource->getKey(), // This doesn't uses the relatedKey from the association
        ]);
    }
```

I tried to solve this issue myself but I can't find a way to resolve the relationship to get the relatedKey. I can't change the primaryKey from the model since it's used for something else.

## Clues

The problem could be solved resolving the relation on the fly when formating the resource, but I can't find a way to retried the attachable parameter from this url ` http://dev.local/nova-api/comments/93/attachable/posts`

```php
    public function formatAttachableResource(NovaRequest $request, $resource)
    {
        $relationShip = $request->getAttachable() // This method doesn't exists unfortunately
        $relatedKey = $request->model()->$relationShip()->relatedKey;
        return array_filter([
            'avatar' => $resource->resolveAvatarUrl($request),
            'display' => $this->formatDisplayValue($resource),
            'value' => $resource->$relatedKey, 
        ]);
    }
```

An easier way would be to add a new parameter to the constructor (if you like this solution I could do the PR myself)

```php
    public function __construct($name, $attribute = null, $resource = null, $relatedKey = null)
```

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
