### ISSUE TITLE
Unable to queue actions that have custom canSee / canRun methods

### ISSUE THREAD

**Issue by mpociot** [laravel/nova-issues#1309]
When you try to queue an action that has a custom `canSee` or `canRun` method, you'll get an error saying:

> Serialization of 'Closure' is not allowed

That's because both closure properties of the action (`$runCallback` and `$seeCallback`) are being serialized by the `SerializesModels` trait.

As these properties are not needed at the time the action is put onto a queue, they do not need to be serialized.

**Comment by bolechen** [comment]
Issue still present in v1.3.2 @davidhemphill

**Comment by dkulyk** [comment]
You need to override `authorizedToRun` method in the action for queued actions.

**Comment by dkulyk** [comment]
Duplicate of https://github.com/laravel/nova-issues/issues/194
