### ISSUE TITLE
Metrics without ranges still use ranges for queries

### ISSUE THREAD

**Issue by mpociot** [laravel/nova-issues#1313]
When I define a Value metric without ranges, I get 0 as a result, instead of the total modal count. 
Of course, I can make it work by using

 ```
return $this->result(User::count());
```

 but that feels like working against Nova.

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
