### ISSUE TITLE
Reverse chunk order for action requests.

### ISSUE THREAD

**Issue by dkulyk** [laravel/nova-issues#1314]
If you delete records more than chunk size you have wrong offset on second and further chunks because second query have offset 150 but deleted records don't exists into query set.
So we lose the whole chunk. Totally we lost about 50% records for processing.

If we will use reverse chunk ordering we will get rid of this problem.

Related issue https://github.com/laravel/nova-issues/issues/993

- [x] Delete resources https://github.com/laravel/nova/pull/180
- [x] Restore resources https://github.com/laravel/nova/pull/180
- [ ] Detach BelongsToMany
- [ ] Detach MorphToMany
- [ ] Actions

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
