### ISSUE TITLE
Error message for attached item update stays after successful update

### ISSUE THREAD

**Issue by christophrumpel** [laravel/nova-issues#1317]
- Laravel Version: 5.7.24
- Nova Version: 1.3.1
- PHP Version: 7.1
- Operating System and Version: MacOS 10.14.2
- Browser type and version: Chrome 71.0.3578.98

### Description:

This is a similar issue to #748 or #512 but I'm facing it on the update on an attached item page.

I have a validation rule for a text field of a BelongsToMany relationship which is working fine.
When I try to `update` an attached item, the error message stays on the page, even if the update was successful. I'm using a custom validation rule in the gif, but it is the same problem with a default rule like `required`.

### Steps To Reproduce:

- Use a resource with a many-to-many relationship
- Use a belongstomany field on the resource
- Add a validation rule to a pivot field of this relation
- Attach an item to a resource
- Try to update the attache with `false` input (the validation error is shown)
- Try a valid input. It will show a success message, but the validation error stays on the page

![nova_attached_update_error](https://user-images.githubusercontent.com/1394539/52116720-2693d480-2612-11e9-9ab0-ae923c6b6340.gif)

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
