### ISSUE TITLE
[Nova 1.3.1] Need a way to provide a field from a BelongsTo relationship to a subresource

### ISSUE THREAD

**Issue by rk** [laravel/nova-issues#1318]
Hello,

Our DB is modeled with relationships like:

```
Product -> (HasMany) -> Variants
Variant -> (BelongsTo) -> Product
```

I'm using a [3rd party component](https://github.com/epartment/nova-dependency-container) to show/hide groups of fields, based on certain choices. (Mainly toggling specification-related fields related to a specification attribute.)

But, as the requirements become more complex we now need to depend upon a field from the Product when creating/updating Variants. For example:

```
Product
  - Type (default, A, B, C)
```

I've created a "field" on the Variant...

```php
    public function getProductTypeAttribute()
    {
        if ($this->product_id) {
            return optional($this->product)->type ?? 'default';
        }

        return 'default';
    }
```

This works for the details view, as I presume the whole model is available (and I added it to `$appends`). But it doesn't work on the Create or Update views, because I don't have a corresponding field.

I need a way to provide a derived/informational field from a `BelongsTo` component to the view, somehow. Like a hidden field on a regular form. For now I'm solving this like:

```php
            BelongsTo::make('Product')
                ->sortable()
                ->searchable()
                ->rules('required'),

            Text::make('Product Type', 'product_type')
                ->help('This field is <strong>informational only</strong> and is used for field visibility, this value is inherited from the Product above.')
                ->withMeta(['extraAttributes' => ['disabled' => 'disabled']])
                ->onlyOnForms(),

            NovaDependencyContainer::make([
                Text::make('Height (without Stand)', 'meta->height')
                    ->hideFromIndex(),

                Text::make('Height (with Stand)', 'meta->height_stand')
                    ->hideFromIndex(),
            ])
                ->dependsOn('product_type', 'A'),
```

But it doesn't work so well when directly creating fields, as the Product Type field doesn't update. Plus, I can't hide it so I have to provide a help label. I can't find another way to provide it to the Variant resource.

I'm sort-of at a dead end. Any suggestions for implementing this better, or supporting my use-case?

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).

**Comment by rk** [comment]
> I need a way to provide a derived/informational field from a `BelongsTo` component to the view, somehow.

Right now, only visible/instantiated fields provide their values to the form, and a BelongsTo relation doesn't update associated fields. This sounds like a bug or feature request to me.

@davidhemphill The only reason I threw the last paragraph in is in case someone reviewing caught an obvious answer.

**Comment by joelvh** [comment]
@rk did you come up with a solution for this?

**Comment by rk** [comment]
@joelvh I did come up with **a** solution that works for our use-case, with a limited number of subresource types.

For a little background, we have Products (1) -> (n) Variants representing our client's breadth of products. There's a lot of similarity, which we provide in the main Variant resource. What we did, instead of having the variant with a lot of dependency containers, is to subclass the Variant resource.

After testing, I found this to be stable and a nice UX improvement without custom components. It even makes more sense, as the typed variant can now have its own navigation item for adding in exclusion.

Some code examples might help you figure out how I did it. ;)

```php
class Product extends Resource
{

    // [... going down ...]

    public static function relatableQuery(NovaRequest $request, $query)
    {
        parent::relatableQuery($request, $query);

        $resource = $request->resource();

        // If the searching class wants to scope by product type, use its
        // PRODUCT_TYPE constant. Used for dynamic relation fields.
        if (defined("{$resource}::PRODUCT_TYPE")) {
            $query->where('products.type', constant("{$resource}::PRODUCT_TYPE"));
        }

        return $query;
    }

    public function fields(Request $request)
    {
        $variantClass = Variant::class;

        // Yeah, this is all it really took...
        switch ($this['type']) {
            case 'car':
                $variantClass = CarVariant::class;
                break;

            case 'truck':
                $variantClass = TruckVariant::class;
                break;

            case 'semi':
                $variantClass = SemiVariant::class;
                break;
        }

        return [
            ID::make()->sortable(),

            TextWithSlug::make('Name')
                ->slug()
                ->rules('required', 'max:255')
                ->sortable(),

            Select::make('Type')
                ->options(\App\Models\Product::TYPES)
                ->displayUsingLabels()
                ->rules('required')
                ->sortable(),

            HasMany::make('Variants', 'variants', $variantClass),
        ];
    }
}
```

This code lets us have only Car variants associated with a Car type. Truck with Truck, etc. Pretty simple, but very helpful. On the variant, I use an abstract parent class, I then define a few things:

```php
abstract class VariantResource extends Resource
{

    // Override in your variant class
    public const PRODUCT_TYPE      = '';
    public const RESOURCE_SINGULAR = 'Variant';
    public const RESOURCE_PLURAL   = 'Variants';

    public static $group = 'Variants';

    public static $search = [
        'id',
        'name',
        'sku',
    ];

    public static $with = ['product'];

    // This is where the query changes happen: scoping to the product_type
    // column we "clone" from the parent. Together with newModel() it might
    // duplicate a little data, but it makes the common Variant class be
    // possible...

    public static function indexQuery(NovaRequest $request, $query)
    {
        if (static::PRODUCT_TYPE) {
            $query->where('product_type', static::PRODUCT_TYPE);
        }

        return $query;
    }

    public static function scoutQuery(NovaRequest $request, $query)
    {
        if (static::PRODUCT_TYPE) {
            $query->where('product_type', static::PRODUCT_TYPE);
        }

        return $query;
    }

    public static function detailQuery(NovaRequest $request, $query)
    {
        if (static::PRODUCT_TYPE) {
            $query->where('product_type', static::PRODUCT_TYPE);
        }

        return $query;
    }

    public static function newModel()
    {
        $model = parent::newModel();

        $model->product_type = static::PRODUCT_TYPE;

        return $model;
    }

    public static function label()
    {
        return static::RESOURCE_PLURAL;
    }

    public static function singularLabel()
    {
        return static::RESOURCE_SINGULAR;
    }

    public function fields(Request $request)
    {
        return [
            ID::make()
                ->sortable(),

            BelongsTo::make('Product')
                ->sortable()
                ->searchable()
                ->rules('required'),

            // Common fields to all variants go here...

            // And fields unique to the variant type go here:
            static::variantTypeFields(),
        ];
    }

    public static function variantTypeFields()
    {
        return [/* Override me! */];
    }
}
```

The benefit of this design is that you can use the Dependency Container (the 3rd party dependency I mentioned in the original post) in the main Variant class (or skip it) to have field groups based on your types. Then someone can create a wholly generic variant and assign a type—with the same fields.

Hope this points you in the right direction.
