### ISSUE TITLE
Nova not working on Windows

### ISSUE THREAD

**Issue by mortenscheel** [laravel/nova-issues#132]
After installing Nova v1.0.5 in a fresh Laravel project (without any issues or errors thrown), the /nova route doesn't exist.

According to `artisan route:list --name nova`, only the API routes show up, and they're all named nova.api. (not followed by the name of the action).

Environment: Laragon dev environment with Apache 2.4.27 and PHP 7.1.20 on Windows 10.

**Comment by adamthehutt** [comment]
I had this same problem. You may need to manually register the NovaServiceProvider in your config/app.php file. That fixed this particular issue for me (although there's still some other weirdness that seems to be Windows-related).

**Comment by mortenscheel** [comment]
Thanks, that fixed it. I'm closing the issue
