### ISSUE TITLE
[💡 Feature Request] Show textarea field on index

### ISSUE THREAD

**Issue by sadekd** [laravel/nova-issues#1320]
Hi, is possible to show preview of textarea field on index page?

Textarea not react to `Textarea::make('Comment', 'comment')->alwaysShow()->showOnIndex(),`

Currently using as hack:

```php
            Text::make('Comment', function () {
                return str_limit($this->comment);
            })->onlyOnIndex(),
            Textarea::make('Comment', 'comment')->alwaysShow(),
```

**Comment by davidhemphill** [comment]
We're not going to support this out of the box. It's our intention to have `Textarea` fields not show in the index views.

**Comment by yarbala** [comment]
@davidhemphill  I think it will be useful. Example: we have resource with only 2 fields phone+comments. We making search of comment contents and didn't see content in the index. But user is interested to find appropriate resource, but he should open every single resource in the result-set.

**Comment by dillingham** [comment]
@sadekd / @yarbala I needed this too, made a package for it 👍 

https://github.com/dillingham/nova-index-textarea

**Comment by yuqinghong** [comment]
可以尝试继承原有的方法， 然后修改`showOnIndex`的值，
```php
Textarea::macro('showOnIndex', function($bool = false){
    $this->showOnIndex = $bool;
    return $this;
});
```
然后就可以这么用：
```PHP
Textarea::make('Comment', 'comment')->alwaysShow()->showOnIndex(true)
```

**Comment by chinleung** [comment]
> 可以尝试继承原有的方法， 然后修改`showOnIndex`的值，
> 
> ```
> Textarea::macro('showOnIndex', function($bool = false){
>     $this->showOnIndex = $bool;
>     return $this;
> });
> ```
> 
> 然后就可以这么用：
> 
> ```
> Textarea::make('Comment', 'comment')->alwaysShow()->showOnIndex(true)
> ```

You don't need to add a macro, the `Textarea` class already has the `showOnIndex` method from it's parent.

**Comment by dillingham** [comment]
Good note, but at the time it didn’t.
