### ISSUE TITLE
Attributes not available in custom accessors when updating model

### ISSUE THREAD

**Issue by WouterFlorijn** [laravel/nova-issues#1321]
- Laravel Version: 5.7.22
- Nova Version: 1.3.1 & 2.0.0
- PHP Version: 7.1.23
- Operating System and Version: Debian 4.9.65-3+deb9u2
- Browser type and version: Irrelevant

### Description:

When trying to update a model that has a custom accessor that references any other attribute, an exception is thrown.

Example:

Accessor:

```php
public function getSlugAttribute()
{
    return strtolower($this->name); // Also tried $this->attributes['name']
}
```

Exception:

> Undefined index: name

It seems attributes aren't loaded. Indeed, `var_dump`ing `$this->attributes` gives an empty array right before the error.

### Steps To Reproduce:

1. Have a model with a custom accessor.
2. Update the model through Nova.

**Comment by dillingham** [comment]
https://github.com/laravel/nova-issues/issues/1123

**Comment by reppair** [comment]
Yeah, absolutely same issue here. Any idea why?

**Comment by ludo237** [comment]
Can confirm also on v2.0.0

**Comment by fede91it** [comment]
Same for me on

PHP: 7.3.0
Laravel: 5.8.14
Nova: 2.0.1

**Comment by afik-d** [comment]
Any idea on how to solve (or workaround) this?

**Comment by AfikDeri** [comment]
Here is a very very dumb and temporary solution for anyone need to still use accessors.

```php
public function getSlugAttribute($value)
{
    // Nova expect the same initial value, without mutations.
    if (str_contains(request()->getUri(), 'nova-api')) {
        return $value;
    }

    // Do whatever you need with your data.
    // This is for Laravel use only, not Nova.
    return strtolower($value);
}
```

**Comment by reppair** [comment]
So, any ideas why is that happening in general?

**Comment by jbrooksuk** [comment]
Sorry, but we are unable to debug your issue without a reproducible code example. Once you provide that we can open this up again.

**Comment by reppair** [comment]
You gotta be kidding us! Let me reproduce it and update the issue.

**Comment by reppair** [comment]
Crap, I can't reproduce it either (nova: _v2.0.9_, laravel: _v5.8.29_, php: _v7.3.7_) and I had this problem 6 months ago. It looks like it was fixed but we do not know when and which release fixed it. If you go back and test it with actual nova version from when the issue was created it won't work. However I'm good not knowing exactly why it was failing if it does not break again.. :)

**Comment by jbrooksuk** [comment]
🤙

**Comment by martinpotel** [comment]
I'm getting the same issue when using a custom accessor.

- Laravel 8.8.35
- Nova 2.20
- Spatie/Enum 2.3.1
- Php 7.2

Accessor:

`/**
     * @return CarrierTypeEnum
     */
    public function getTypeAttribute()
    {
        return CarrierTypeEnum::make($this->attributes['type']);
    }
`

Error:

`Undefined index: name`

Loggin `$this->attributes` gives an empty array.

**Comment by FutureFutureTo** [comment]
Any ideas on why this was marked as closed?

Looks like the only solution right now is just a workaround...

**Comment by reppair** [comment]
Be cause it worked at some point and it still does for me. Laravel `8.26.1`, Nova `3.20.0` and PHP `7.4.14`.

Consider this example that I just tested:

```
// model
    public function getSomethingAttribute()
    {
        dump($this->attributes);
        return 'something';
    }

// Nova
    public function fields(Request $request)
    {
        return [
            Text::make('something', fn() => $this->something),
        ];
    }
```
That added the "something" column and populated it with 'something'.. also the attributes show up in the dump.
