### ISSUE TITLE
Expired session redirect to dashboard vs intended

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#1323]
- Laravel Version: 5.7
- Nova Version: 1.3.0

### Description:

When a session expires, the redirect upon login is the dashboard.
The intended url that triggered the login page is the desired redirect.
Flow breaks the most from email notification to expired session to dashboard vs intended link.

### Steps

- Be logged in
- Let session expire
- Click something / visit url
- Be instructed to log in
- Redirect to dashboard
- Wag your finger and say "oh no you didn't"

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
