### ISSUE TITLE
Can't display field from HasOne relation interface

### ISSUE THREAD

**Issue by Ange7** [laravel/nova-issues#1326]
- Laravel Version: 5.7
- Nova Version: 1.3.1
- PHP Version: 7.1

### Description:

Hello,

I have one main table with common data :

+-------------------+
| common_table |
|--------------------|
|          id            |
+-------------------+

and one other table with hasOne relation 

+-------------------+
|extended_table |
|--------------------|
|  idCommon      |
|  value              |
+-------------------+

in my nova resource « COMMON_TABLE » i want display / update the Value from extended_table

But not working

**Comment by davidhemphill** [comment]
This is not enough details to diagnose.
