### ISSUE TITLE
Validation rules on related relation field don't work

### ISSUE THREAD

**Issue by Naoray** [laravel/nova-issues#1327]
- Laravel Version: 5.7.25
- Nova Version: 1.3.1
- PHP Version: 7.2
- Operating System and Version: Ubuntu 18.10
- Browser type and version: Chrome Version 72.0.3626.81

### Description:
Related fields of a resource can be displayed using the dot notation but validation does not work since it replaces the `.` with `_` in the `NovaRequest`. Therefore all validations on this field fail because it is referenced with the dot notation.

```php
Text::make('Email', 'user.email'), // user_email in NovaRequest

    ->rules('required'), // fails since it looks for user.email in the request

    // this is working - just to demonstrate the user_email is being used in the request
    ->fillUsing(function ($request, $model) {
                    if ($user = $model->user) {
                        $user->email = $request->user_email;
                        $user->save();
                    }
                }),
```

Adding a `str_replace` to `Field''s 'getRules()` method makes the validation pass:
```php
/**
     * Get the validation rules for this field.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @return array
     */
    public function getRules(NovaRequest $request)
    {
        return [str_replace('.', '_', $this->attribute) => is_callable($this->rules)
                            ? call_user_func($this->rules, $request)
                            : $this->rules, ];
    }
```

### Steps To Reproduce:
1. Add BelongsTo `user()` relationsship to you resources' model
```php
public function user()
    {
        return $this->belongsTo(User::class);
    }
```

2. Add a related field with dot notation & validation
```php
Text::make('Email', 'user.email'),
    ->rules('required'),
```

3. Try to create a new resource

Not sure if this is a bug or it's just not supposed to work like this...

**Comment by umarakber** [comment]
Hello,

Any solution for dot notation validation ?

**Comment by dkulyk** [comment]
You need to use arrow notation `'user->email'`.
But it doesn't store related resource automatically.

**Comment by umarakber** [comment]
Now i am getting error 

> Integrity constraint violation: 1048 Column 'entity_id' cannot be null (SQL: insert into `assigned_roles` (`entity_id`, `entity_type`, `role_id`) values (, App\\User, 3))

here is my code 

` Select::make('Role', 'role->name')->rules('required')->options($roles)->fillUsing(function ($request, $model) {
                            $model->assign($request->get("role->name"));
                            $model->save();
                    }),`

can you please help me

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
