### ISSUE TITLE
Error on adding custom tool in Nova. Error: Class not found.

### ISSUE THREAD

**Issue by swapnilmonad** [laravel/nova-issues#1329]
- Laravel Version: 5.7
- Nova Version: 1.3.0
- PHP Version: 7.1
- Operating System and Version: Ubuntu16
- Browser type and version: chrome

### Description:
While adding [a custom tool into the Nova](https://nova.laravel.com/docs/1.0/customization/tools.html#overview), 
Found an error after register a class into NovaServiceProvider.

Error Type: fatal error
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
**Class 'Admin\NotificationManager\NotificationManager' not found**
Symfony\Component\Debug\Exception\FatalThrowableError 
…/app/Providers/NovaServiceProvider.php75

### Steps To Reproduce:
1.` php artisan nova:tool admin/notification-manager`
2. In App\Providers\NovaServiceProvider file added newly added tool
```
public function tools() {
    return [ new \Admin\NotificationManager\NotificationManager ]; 
}
```
 3. Visit browser

**Comment by swapnilmonad** [comment]
There were multiple entries happened for the same notification package with different namespaces into composer.json.

**Comment by bucksterbuck** [comment]
I am having the same problem

**Comment by swapnilmonad** [comment]
> I am having the same problem

@bucksterbuck Your problem is solved or still facing the same issue?

**Comment by bucksterbuck** [comment]
I am still facing the same issue, generated tool via CLI and get the same
error and problem

**Comment by bucksterbuck** [comment]
Correction: Running composer update fixed this, for some reason when it does on via the CLI it doesn't register...

**Comment by swapnilmonad** [comment]
@bucksterbuck After composer update, run ` composer dump autoload -o` &
php artisan cache:clear
While generating new tool use YES for all Questions to build composer, package

**Comment by rudiullon** [comment]
Same issue here.. nothing from the above worked

**Comment by genesiscz** [comment]
> Same issue here.. nothing from the above worked

@rudiullon try running composer dump-autoload after composer require yourvendor/yourpackage

**Comment by rudiullon** [comment]
Thanks @genesiscz but I ended up taking another approach to solve my problem.

**Comment by genesiscz** [comment]
what is that

**Comment by rudiullon** [comment]
I wanted to create a new tool so I could add a custom view to Nova, but what I ended up doing was just overriding the navigation template to add a link to the custom view, that one made with blade. Not elegant at all, but it solved my problem.

**Comment by gbrits** [comment]
1.) Update your composer:
`composer self-update`

2.) And then update your composer, this command instructs your PHP to override any memory issues and just get it done:
`php -d memory_limit=-1 /usr/local/bin/composer update`

This will automatically find all new packages and dump-autoload when done.

**Comment by genesiscz** [comment]
@gbrits that updates all packages which you simply dont want to in this case

just require the package, that's all you need
