### ISSUE TITLE
Better localization support

### ISSUE THREAD

**Issue by HenriqueSPin** [laravel/nova-issues#1334]
Eg.: (Not actual code)
```php
{{ $resource->name }} {{ __('Details') }}
```
This leads to pour localization in latin and others languages because the translated "details" should be in the start of the sentence. Like:  "Detalhes do :resource"

So, the suggestion is to never split sentences like this. Always use:
 ```__(":var bar", [ "var" => "foo" ])```

**Comment by FaridAghili** [comment]
https://github.com/laravel/nova-issues/issues/203
