### ISSUE TITLE
Image field not uploading to database 

### ISSUE THREAD

**Issue by Alrektii** [laravel/nova-issues#1335]
Hello I am using this to add images to my field but for some reason the value does not seem to get saved in the input , when I try to create a new one it gives me an error that the _"subscription_photo"_ field does not have a default value. Even when it has a image inside. 

this is my code: 
` Image::make('Photo' ,'subscription_photo')->disk('public'),`

This is the value in the database 
![image](https://user-images.githubusercontent.com/29793158/52481324-80fed900-2bae-11e9-8c16-bc29d00db1a4.png)

The exact code worked on a different PC with the exact files. 
Tried to search for the issue online did not have any luck. 

Thanks!

**Comment by Alrektii** [comment]
Edit: I found out what the problem was! 

If you try to upload a 4k photo the Image::make ignores it , havent found a way to fix it but if I use non 4k pictures it works perfectly fine

**Comment by dungamichael** [comment]
This is for others who need help with this, just go to php.ini in xampp and change the following to this:

upload file size max:
- upload_max_filesize = 50M
- post_max_size = 50M
- max_input_time = 300 
- max_execution_time = 300
