### ISSUE TITLE
Custom text on resource button 

### ISSUE THREAD

**Issue by kokarat** [laravel/nova-issues#1336]
Please add custom text on the resource button.
 Eg. Create, Create & Add Another

**Comment by tomthetux** [comment]
This would help everyone to translate it to another language. 
1. Depending on the language, a different text on the index, detail, creating, and updating page is required for resource buttons. 
2. "create resourcename" makes sense in English, but in German "resourcename erstellen" ("resourcename create") is the correct word order.

**Comment by bonzai** [comment]
#203
