### ISSUE TITLE
Heading Field Padding On Detail View is wrong.

### ISSUE THREAD

**Issue by jpscharf** [laravel/nova-issues#1337]
- Laravel Version: 5.7.22
- Nova Version: 1.3.1
- PHP Version: 7.2.14
- Operating System and Version: macOS High Sierra
- Browser type and version: Chrome 72

### Description:
The heading field on the form aligned with the edge of the card, but on the detail view the cards padding pushes it int.
![2019-02-08_18-41-16](https://user-images.githubusercontent.com/1039984/52512139-4fe3d000-2bd1-11e9-993f-87faf7c56aa7.png)

**Comment by jpscharf** [comment]
The quick fix would be to modify `resources/js/components/Detail/HeadingField`

```html
<template>
    <div class="bg-20 flex border-b border-40">
        <div class="w-full py-4 px-4">
```

Updating the the first div, adding a negative x-margin of six, and x-padding of two: `-mx-6 px-2`.  **_(see below)_**

```html
<template>
    <div class="bg-20 flex border-b border-40 -mx-6 px-2">
        <div class="w-full py-4 px-4">

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
