### ISSUE TITLE
Cursor initially placed in wrong position inside long Markdown field after previewing

### ISSUE THREAD

**Issue by bakerkretzmar** [laravel/nova-issues#1338]
- Laravel Version: 5.7.25
- Nova Version: 1.3.1
- PHP Version: 7.2.13
- Operating System and Version: macOS High Sierra 10.13.6
- Browser type and version: Chrome 71.0, Firefox 65.0

### Description:

After previewing a markdown field, and then switching back to writing mode, upon focusing the field by clicking inside it, the cursor is placed not where the field was clicked but several lines lower. Weirdly, it seems to skip down proportional to the click's position inside the field—clicking somewhere in the first line of text appears to work normally, clicking in the second or third might place the cursor in the fifth to tenth, and clicking 10 or more lines down in the field usually causes the cursor to jump to the very bottom and scroll the browser down too.

Subsequent clicks function normally. Clicking in the field immediately after the initial page load works fine too—the jumpiness only happens after previewing and then switching back to writing mode.

### Steps To Reproduce:

Fresh Laravel site, fresh Nova install from Composer, create a Markdown field on any resource, edit or create a resource, enter 10+ lines of text in the Markdown field, preview it, then switch back to writing mode and click somewhere below the second line of text in the field. Reproduced in Firefox and Chrome, in different sites and Nova installs, and on different Nova resources.

### Possible solution?

FWIW, in a fresh custom field component copied and pasted from Nova's own Markdown field, commenting out `this.codemirror.refresh()` in the `write()` method of the component appears to resolve this issue without affecting any other functionality. So does just wrapping it in a `$nextTick(...)`. Not sure why, or what implications that could have. If that's the fix I'm happy to PR it to the Nova repo.

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
