### ISSUE TITLE
Resource labels should have spaces

### ISSUE THREAD

**Issue by adamthehutt** [laravel/nova-issues#134]
When a resource is named something like "ModelTrain" it should display in the UI as "Model Train" with a space between the words.

**Comment by reganjohnson** [comment]
You can customize this using the `label()` and `labelSingular()` methods on the resources, and when defining the relationships....

```
HasOne::make('Custom Resource Name', 'relationshipMethodOnModel`, NovaResource::class);
```

**Comment by ok200paul** [comment]
Rather than needing to add methods around the place, possibly an update to the `label()` function in `/nova/src/Resource.php`?

```
public static function label()
{
    return Str::plural(ucwords(Str::snake(class_basename(get_called_class()), ' ')));
}
```

or possibly something like:

```
public static function label()
{
    return self::uriKey(' ');
}

// along with

public static function uriKey($delimiter = '-')
{
    return Str::plural(Str::snake(class_basename(get_called_class()), $delimiter));
}
```
.. but I see the second suggestion causes a wider issue

**Comment by paras-malhotra** [comment]
+1 @ok200paul your 1st solution works well!

**Comment by bironeaj** [comment]
+1 to having this implemented by default

**Comment by davidhemphill** [comment]
Specify the first argument to the relation with spaces, and then define the 2nd and 3rd argument.
