### ISSUE TITLE
Question: How to '/nova' Remove URL prefix

### ISSUE THREAD

**Issue by MojoJojo** [laravel/nova-issues#1340]
Hi,
I just bought Nova and started customizing for my requirements. I had an admin application that I would like to expose as the default application at certain domain e.g. mypp-admin.com. Is it possible to serve Nova as the default application at the domain i.e. not have the /nova prefix. When I browser to my-appadmin.com I want to see the Nova login screen.
What I've tried so far:
I've tried adding a `domain` property in nova/config.php and setting the path to '/' but it doesn't seem to work.
Any ideas/suggestions would be appreciated.

**Comment by karlozadro** [comment]
There's an entry in the `app/config/nova.php` file called `path` which you can change to update the URI path that Nova is accessible from.

It defaults to `'path' => '/nova'`, but if you change it to `'path' => '/'`, that should get you what you're looking for.

**Comment by WebZenitude** [comment]
Hi,
Laravel version = 5.8.12
Nova version = 2.0.0
I changed to 'path' => '/'
But the path stays in the app at '/nova/ and gives a 404/ Not found error when trying to use the path'/'.
Anything else to change apart the app/config/nova.php file?
Any ideas/suggestions would be also appreciated.

**Comment by Grunkhead** [comment]
I fixed this problem by checking the REQUEST_URI. If the URI has the word '/nova' in it. It will skip the route.

![image](https://user-images.githubusercontent.com/746279/58271679-e016e100-7d8c-11e9-8d2b-00cecacffa83.png)

**Comment by WebZenitude** [comment]
Thanks @Grunkhead ! :-)
It works!
NB1 : has to be added here = routes/web.php
NB2 : Here is the code to copy/paste:
`if ($_SERVER['REQUEST_URI'] != '/nova') {
    Route::get('/{page}', function($page) {
        return view("pages.{$page}");
    });
}`

**Comment by sleicester** [comment]
Here is an alternative that I use in this situation:
```
if ( ! Request::is('admin*')) {
    Route::get('/{page}', 'PageController')->name('pages.show');
}
```

**Comment by WebZenitude** [comment]
Thanks @sleicester , but when I try your solution, I receive an error at login and at logout:

UnexpectedValueException
Invalid route action: [App\Http\Controllers\PageController].

But if I log in using @Grunkhead solution and switch after to your solution, the navigation inside the Nova site works.

**Comment by WebZenitude** [comment]
Some feed-back @Grunkhead : I have to comment your solution before each migration to be done (and to recomment it after) or I receive this error:
For example:
➜  xxxxx git:(master) ✗ php artisan make:migration:pivot attachments files
In web.php line 24:                      
  Undefined index: REQUEST_URI  
➜  xxxxx git:(master)

**Comment by Grunkhead** [comment]
![image](https://user-images.githubusercontent.com/746279/62138942-ce037280-b2e8-11e9-83d1-01b41d1b38fc.png)

This is a better way to solve the issue. By fetching the Request object. There is some code in the middle which you can ignore.

**Comment by Grunkhead** [comment]
> Some feed-back @Grunkhead : I have to comment your solution before each migration to be done (and to recomment it after) or I receive this error:
> For example:
> ➜ xxxxx git:(master) ✗ php artisan make:migration:pivot attachments files
> In web.php line 24:
> Undefined index: REQUEST_URI
> ➜ xxxxx git:(master)

![image](https://user-images.githubusercontent.com/746279/62138942-ce037280-b2e8-11e9-83d1-01b41d1b38fc.png)

This is a better way to solve the issue. By fetching the Request object. There is some code in the middle which you can ignore.

**Comment by WebZenitude** [comment]
Thanks @Grunkhead ! It works now smoothly.

`
if (!\Request::is(
    'nova')) {

    Route::get('{criteria}', function ($criteria) {

        $page = \App\Page::where('slug', $criteria)->first();

        if (!$page)
            return abort(404);

        return view('page.show', ['page' => $page]);

    });

}
`

**Comment by nickbluestone98** [comment]
After changing the path in  `app/config/nova.php`. I found by simply running the following it solved my issues without needing to add any code like the above examples.

```
php artisan config:cache
php artisan route:cache
```

**Comment by dendyaziz** [comment]
Complete steps:

1. In config/nova.php, change path from `'path' => '/nova'` to `'path' => '/'`
2. Clear your cached route by executing:
```
php artisan route:clear
```
3. In web.php remove `'/'` route. In my case(fresh laravel project):
```
// remove all three rows below
Route::get('/', function () {
    return view('welcome');
});
```
