### ISSUE TITLE
How to make Nova aware of X-Forwarded-Path. 

### ISSUE THREAD

**Issue by raviskiran** [laravel/nova-issues#1341]
I've a Reverse Proxy set up to access my app. My app is hosted on **example.com** but I want to proxy it through 
**mycompany.com/example**. 

I've trusted proxy set up in the laravel app, and forcing root url to X-FORWARDED-PATH, so the urls getting generated start with **mycompany.com/example** 
The general app URLs like css, js etc are being generated as desired, but Nova app/api/Vue routing is not getting affected. So the end result is I see
**mycompany.com/example/js**.
**mycompany.com/nova-api**.
Can anyone help me?

**Comment by bonzai** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://larachat.co/).

**Comment by ravikirancopart** [comment]
I thought this was an issue with Nova not updating paths. Anyway, I will email for support.
