### ISSUE TITLE
Algolia index not updating

### ISSUE THREAD

**Issue by abzalzhumabaev** [laravel/nova-issues#1343]
- Laravel Version: 5.7.25
- Nova Version: 1.3.1
- PHP Version: 7.3
- Operating System and Version: Mac 10.14
- Browser type and version: Chrome 72.0

### Description:
When create or update 'Searchable' model from nova, model not syncing with algolia index, instead deleting this record from index of algolia, but work if use 'update' function in Controller.

#### Example Model:

```php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;
use Laravel\Scout\Searchable;

class Category extends Model
{
    use Searchable, Sluggable;

    protected $fillable = [
        'name',
        'slug',
        'is_publish',
    ];

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }

    public function isPublished()
    {
        return $this->is_publish === 1;
    }

    public function searchableAs()
    {
        return 'categories_index';
    }

    public function shouldBeSearchable()
    {
        return $this->isPublished();
    }

    public function toSearchableArray()
    {
        return array_only($this->toArray(), ['name', 'slug']);
    }
}
```

**Comment by sam-g-roberts** [comment]
+1 we have been recieving the exact same issue with laravel nova

**Comment by davidhemphill** [comment]
Sorry, but we are unable to debug your issue without a reproducible code example. Once you provide that we can open this up again.
