### ISSUE TITLE
Add "accept" attribute option to File field

### ISSUE THREAD

**Issue by FrittenKeeZ** [laravel/nova-issues#1345]
By default the `File` field accepts any file formats, but it would be nice to be able to restrict that to fx. zip files using the `accept` attribute: `<input type="file" accept=".zip" />`.

I'm thinking it could be implemented like any other method:
```php
File::make('Archive')
    ->accept('.zip')
    ->rules('file', 'mimes:zip')
```

It would make sense to have `Image` call this in its constructor: `parent::accept('image/*')`.
Same goes for an audio or video field if they ever appear - again all about convenience.

**Comment by Krato** [comment]
@bonzai If this is not accepted, there's another way to restrict the type of file is uploading. Cause you can have an Image field, but the user can upload a zip file.
