### ISSUE TITLE
Customize favicon

### ISSUE THREAD

**Issue by klimov-paul** [laravel/nova-issues#1346]
The Nova pages lack the favicon.
Favicon is is very useful, for example, while distinguish several different projects opened in the browser tabs.
At the present state there is no quick way to setup own custom favicon.
Obviously, the one may override the entire `resources/views/layout.blade.php` adding `<link rel="icon" ...>` at the head, but this is an overkill.

There should be separated view for the favicon setup in the same manner as it is for logo. E.g. file `resources/views/partials/favicon.blade.php` with content like following:

```
{{--<link rel="icon" type="image/png" href="/img/favicon.png">--}}
```

**Comment by Anopetia** [comment]
Absolutetly, need this too.

**Comment by wemersonrv** [comment]
Yep. I need this too... it will good if we can change the favicon in a more firendly command

**Comment by terasupernova** [comment]
No update on this?

**Comment by jbrooksuk** [comment]
I've sent a PR that adds this feature :)

**Comment by marezelej** [comment]
It can be customized using meta view (partials/meta.blade.php)

**Comment by cweiske** [comment]
@davidhemphill Why do such requests get closed without any comment or explanation if and how the problem has been solved?
