### ISSUE TITLE
MorphTo relation resources

### ISSUE THREAD

**Issue by davileichsenring** [laravel/nova-issues#1348]
- Laravel Version: 5.7.25
- Nova Version: 1.3/1
- PHP Version: 7.2

### Description:
When using MorphTo, I saw, while debugging, this Class relations use all fields resources related 

### Steps To Reproduce:

Let's get the example

use App\Nova\Post;
use App\Nova\Video;

MorphTo::make('Commentable')->types([
    Post::class,
    Video::class,
])

The point is, when The Morph load Post and Video, it loads all fields that belongs to that Resource class. The problem is, when you have a huge resource, with some BelongsTo and HasMany, etc, the simple select field (that generated from MorphTo) loads each resources with all fields inside, taking long time when there is a huge record. Since the select field only needs the name and ID, why it loads all Resource fields together?

I did some workaround to prevent that, creating a new Resource returning only one field, the name, to prevent all other fields that is not used for this moment.

return  = [
            Text::make('name'),
        ];

**Comment by dkulyk** [comment]
Maybe need to add `searchable()`?
```php
MorphTo::make('Commentable')
    ->types([
        Post::class,
        Video::class,
    ])
    ->searchable()
```

**Comment by davileichsenring** [comment]
> Maybe need to add `searchable()`?
> 
> ```
> MorphTo::make('Commentable')
>     ->types([
>         Post::class,
>         Video::class,
>     ])
>     ->searchable()
> ```

Well, it is solve my problem instead using bad workaround :). But even the searchable uses the resource fields, at this point it is not more a problem for me, but, since I have around 5.000 records at least, it seems a just little bit 'lag' when I search for a record. I would like to avoid the php loading non necessary resources, but since the searchable works, I think it is more a feature than bug.

Thanks.

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!

**Comment by ammardaana** [comment]
wedfwe
