### ISSUE TITLE
Updating a resource having an Image field without selecting a file is not working

### ISSUE THREAD

**Issue by helori** [laravel/nova-issues#135]
Editing a resource with an Image field without selecting a file for it prevents the "Update" button from working correctly. Clicking "Update" doesn't trigger any request because of a javascript error (screenshot attached). This issue does not depend on if an image has been previously set or not.
<img width="1423" alt="screenshot image update" src="https://user-images.githubusercontent.com/8065958/44587709-100c6600-a7b4-11e8-94b0-3573f922c53c.png">

**Comment by bonzai** [comment]
Can you try upgrading to the newest version?

Feel free to post this issue again if the problem persists.
