### ISSUE TITLE
Mongodb: Call to a member function prepare() on null

### ISSUE THREAD

**Issue by simonschaufi** [laravel/nova-issues#1350]
- Laravel Version: 5.6
- Nova Version: 1.3.2
- PHP Version: 7.2
- Operating System and Version: Ubuntu 16 LTS
- Browser type and version: -

### Description:

The resource list works well except the pagination counter where at the bottom of the list it is displayed as: `25/0 resources`. The reason behind is that Mongodb doesn't work with PDO:
`Call to a member function prepare() on null` in 
`/home/vagrant/Code/xxx/vendor/laravel/framework/src/Illuminate/Database/Connection.php`.

This is the exact location where it crashes:

`src/packages/laravel-nova/src/Http/Requests/CountsResources.php`

The problem is that the subQuery is raw SQL instead of a query object which could be handled by mongodb but mongo's SQL syntax is a little bit different.

### Steps To Reproduce:

1. Install mongodb php extension
1. `composer req jenssegers/mongodb`
1. Go to `/nova/resources/users`
1. Wait until the list is loaded
1. An error message appears at the bottom right with: `Call to a member function prepare() on null`

### Solution:

Use the Database API (QueryBuilder) for calculating the total amount of records!

**Comment by tufankilicaslan** [comment]
having same issue, after switched to : Nova Version: 1.3.2

I sticked to version 1.3.0  because 1.3.1 have issue with count statement..

**Comment by tufankilicaslan** [comment]
it works if i just return:

`return $query;`

for the function  **buildCountQuery**

but not sure if this breaks any other sections.

**Comment by simonschaufi** [comment]
yes, can confirm that with 1.3.0 it works fine.

**Comment by dkulyk** [comment]
@bonzai Maybe need to wrap query only if it has `groupBy`?

**Comment by bonzai** [comment]
@dkulyk: https://github.com/laravel/nova-issues/issues/1351#issuecomment-462859893

**Comment by tufankilicaslan** [comment]
@simonschaufi ,

I think the following code solves the problem.  ( it's not clean but at least works)

`src/packages/laravel-nova/src/Http/Requests/CountsResources.php`

```
        $baseQuery = $query->toBase();
        if ($baseQuery instanceof \Jenssegers\Mongodb\Query\Builder) {
            $baseQuery->columns = null;
            $baseQuery->orders = null;
            $baseQuery->limit = null;
            $baseQuery->offset = null;
            $baseQuery->bindings["select"] = [];
            $baseQuery->bindings["order"] = [];
            return $query;
        }
```

**Comment by nbyloff** [comment]
So based on the comments here and in #1351 do we assume the nova team will not be doing any PRs for mongodb issue themselves, or they won't do any PRs for mongodb, period?

I also paid for a license; using a mysql/mongodb hybrid and everything works great on every package I use except nova. I'd love at least enough flexibility in the library where we can find a way to make it work without altering vendor source code.
