### ISSUE TITLE
Mongodb: Broken search

### ISSUE THREAD

**Issue by simonschaufi** [laravel/nova-issues#1351]
- Laravel Version: 5.6
- Nova Version: 1.3.2
- PHP Version: 7.2
- Operating System and Version: Ubuntu 16 LTS
- Browser type and version: -

### Description:

Mongodb doesn't allow table prefixes for search, so in `\Laravel\Nova\PerformsQueries::applySearch` it needs to be like this:
```php
foreach (static::searchableColumns() as $column) {
    $query->orWhere($column, $likeOperator, '%'.$search.'%');
}
```

### Steps To Reproduce:

1. Install mongodb php extension
1. `composer req jenssegers/mongodb`
1. Go to `/nova/resources/users?users_page=1&users_search=David`

**Comment by davidhemphill** [comment]
MongoDB is not an official Laravel database driver.

**Comment by simonschaufi** [comment]
Well, I just bought a license because I wanted to use Nova in a MongoDB project and with just 2 broken things everything works quite well. It would be really nice to make it compatible with MongoDB as well.

**Comment by tufankilicaslan** [comment]
I am sure there are more people using Nova with MongoDB. as you said @simonschaufi , nova working great with MongoDB, just 2 issues left.  I hope this https://github.com/laravel/nova-issues/issues/1350  would be solved, first .  This is more important for me than the search problem. i have to find a way to override or modify core Nova code , if this is not going to be solve.

**Comment by simonschaufi** [comment]
@tufankilicaslan would you be willing to make a MongoDB fork of Nova with me together? I have the feeling the core team is not willing to make Nova compatible with MongoDB. I don't expect everything to work but at least the basic features should work (display and edit data). Editing is also broken as they use transactions.

**Comment by dillingham** [comment]
@simonschaufi you can’t publish a version of nova. You’re better off submitting PRs to the main repo. You can grant yourself access in your nova account settings.

**Comment by tufankilicaslan** [comment]
yes, i agree with @dillingham . since this is not free and public project, can't publish own version.

@simonschaufi   for editing and deleting,  it's creating records on action_events table. and table not supports non integer fields,  you can create a migration file to fix this.

```
          Schema::table('action_events', function ($table) {
            
            $table->string('actionable_id',42)->change();
            $table->string('target_id',42)->change();
            $table->string('model_id',42)->change();
```

**Comment by dillingham** [comment]
You can also turn off action log on the resource

**Comment by tufankilicaslan** [comment]
@dillingham  cant' switch version 1.3.2,  because of this issue: https://github.com/laravel/nova-issues/issues/1350   .  need to edit core nova code to fix the issue.

**Comment by simonschaufi** [comment]
@dillingham How can I submit MRs if my issues are just ignored with the words: Sorry, we don't care and Nova doesn't support Mongodb?

**Comment by dillingham** [comment]
@simonschaufi ok? I mean it’s a bit absurd to assume a laravel eloquent admin panel project can support every non supported database driver. It is equally absurd  to suggest you switch to MySQL. Which is what I’m suggesting :)

**Comment by mstaack** [comment]
its possible to overwrite the qualifyColumn Method:
```
    // fixes nova search
    public function qualifyColumn($column)
    {
        return $column;
    }
```

**Comment by WelaurS** [comment]
MongoDB, of course, is not the core of Laravel. But nevertheless a lot of people use it and a lot of people make dirty tricks to make it work with Nova (at least me and 3 other people I know). It would be very cool if you could add the ability to use Nova with laravel-mongodb

**Comment by davidhemphill** [comment]
Your best course of action is to take it up with https://github.com/laravel/framework. We only plan on supporting Laravel's official database drivers for the foreseeable future. If Mongo makes it into core, we'd be glad to make whatever changes we need to make it work with Nova. 👍
