### ISSUE TITLE
CountsResources trait cannot select correct database  connection after upgrading Nova to v1.3.1 from v1.3.0

### ISSUE THREAD

**Issue by phoenixg** [laravel/nova-issues#1352]
- Laravel Version: 5.7.*
- Nova Version: v1.3.1
- PHP Version: 7.2.0
- Operating System and Version: mac os
- Browser type and version: chrome

### Description:

Database cannot select correct after upgrading Nova to v1.3.1 from v1.3.0.

`Base table or view not found 1146: adm.mytable .... doesn't exist.` error occurred.

 Actually , before I use v1.3.1, it's all OK, my default database connection is `adm` not `dash`, but this `mytable` is in `dash`. But why it cannot locate to the correct database connection after upgrading to v1.3.1?

I use `protected static $connection_name='dash';` in base model class to specify the connection.

### Steps To Reproduce:

I find the v1.3.1 had added a new trait called:  `nova/src/Http/Requests/ResourceIndexRequest.php`

After I Changed this line:

```php
use CountsResources, QueriesResources;

public function toCount()
{
  return $this->buildCountQuery($this->toQuery())->count();
}
```

into:

```php
use QueriesResources;

public function toCount()
{
  return 10000;
}
```

The problem will solve. So the problem is the new trait does not support multi-database connection well.

**Comment by dkulyk** [comment]
Try v1.3.2
