### ISSUE TITLE
Refreshing specified relations after action execution.

### ISSUE THREAD

**Issue by dkulyk** [laravel/nova-issues#1354]
- Laravel Version: 5.7.*
- Nova Version: 1.3.*
- PHP Version: 7.2/7.3
- Operating System and Version: macOS 10.14.3
- Browser type and version: Chrome 72

### Description:
When I execute action for resource I need to update view of relation. But refreshing whole view. After this state of the resource tools or current tab is lost.

Would be good to add ability for refresh only specified views of relation.

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
