### ISSUE TITLE
Trix within action non editable in Safari

### ISSUE THREAD

**Issue by simonedelmann** [laravel/nova-issues#1358]
- Laravel Version: 5.7.24
- Nova Version: 1.3.1
- Browser type and version: Safari 12.0.3

### Description:
I added a **trix** field to my action. Everything is working as excepted in Firefox/Chrome, but in **Safari** the content is not clickable.

Seems to be related to this issue:
[https://github.com/basecamp/trix/issues/444](https://github.com/basecamp/trix/issues/444)

### Steps To Reproduce:
Just add an action and a trix field within. Try to use in Safari.

### Possible solution
As suggested [here](https://github.com/basecamp/trix/issues/444#issuecomment-431283651) I've added the following code to my nova-theme. It's working now.
```
[contenteditable] {
    -webkit-user-select: text;
    user-select: text;
}
```

**Comment by jbrooksuk** [comment]
I've not been able to replicate this issue in Nova v2.0.9
