### ISSUE TITLE
The actions can't run when the names are Chinese

### ISSUE THREAD

**Issue by zhouzishu** [laravel/nova-issues#1359]
In actions, when the labels are English, they can click and run.
But when I use Chinese language, the running button is disabled.

Code:
`public function name()
{
    return '封禁用户';
}`

**Comment by dkulyk** [comment]
You need to specify action key:
```php
public function uriKey()
{
    return 'my-unique-action-name';
}
```

**Comment by zhouzishu** [comment]
> You need to specify action key:
> 
> ```
> public function uriKey()
> {
>     return 'ban-user';
> }
> ```

Right! Thanks!
