### ISSUE TITLE
Session data lost on Nova routes

### ISSUE THREAD

**Issue by parasume** [laravel/nova-issues#136]
I'm trying to build a user impersonation Nova tool. When we impersonate a user, the code adds a session key value pair to identify the original user. But on Nova API routes, for some reason, those values dont show (inspected on Laravel debugbar). When I navigate to non-Nova routes, I see the same values.

Am I missing something here? Do we need to add any middleware? I see that the `web` middleware group is already added out of the box, so I'm assuming the session is created but somehow I'm unable to access the session values on Nova routes.

**Comment by danrichards** [comment]
I'm not totally clear on the context of where you're impersonating...

another user in Nova?
another user in your app?

But I did test saving to the session with a Nova action, then fetching with my app (non Nova route) and it worked fine.

<img width="651" alt="screen shot 2018-08-24 at 10 16 48 am" src="https://user-images.githubusercontent.com/470255/44589680-29e38400-a787-11e8-8898-792ae949e71f.png">
<img width="591" alt="screen shot 2018-08-24 at 10 16 57 am" src="https://user-images.githubusercontent.com/470255/44589685-2cde7480-a787-11e8-842a-8471becf6950.png">
<img width="377" alt="screen shot 2018-08-24 at 10 19 06 am" src="https://user-images.githubusercontent.com/470255/44589686-2fd96500-a787-11e8-9fe1-3cf266b7fd37.png">

**Comment by parasume** [comment]
I was impersonating another user in the app (not Nova) from Nova, but the session data did not transfer to Nova routes. I will try and come back with some code to reproduce the error and if not, we can close this issue

**Comment by taylorotwell** [comment]
We are unable to debug your issue without a recreatable code example.
