### ISSUE TITLE
nova lens actions not visible

### ISSUE THREAD

**Issue by Dontorpedo** [laravel/nova-issues#1361]
- Laravel Version: 5.7.26
- Nova Version: 1.3.0
- PHP Version: 7.2
- Operating System and Version: #.#
- Browser type and version: #.#

### Description:

I have defined a lens for a resource, and added a action in the lens, but the added action is not visible after checking the models..

only the actions from the normal resource/index are visible...

### Steps To Reproduce:

nothing special

created the lens with artisan and added the action like in the nova doc.

**Comment by davidhemphill** [comment]
You're on the wrong version of Nova. This landed in 1.3.2
