### ISSUE TITLE
Get Resource Name

### ISSUE THREAD

**Issue by Milkhan** [laravel/nova-issues#1362]
How one gets the resource name? I just want to show the resource name on a custom element outside the resource on layaout.php. I made a thorough search on documentation and on issues but couldnt find how to get the name attribute of the current research.
Thank you

**Comment by tylernathanreed** [comment]
@Milkhan 

Are you talking about `Resource::label()` ?

**Comment by Milkhan** [comment]
@tylernathanreed Yes but I would like to reach it from layout.blade.php, anyway from outside the resource.

**Comment by tylernathanreed** [comment]
@Milkhan 

That's a static method, so as long as you know the name of the resource, you can access it. Trying doing this:

`\App\Nova\User::label()`

**Comment by Milkhan** [comment]
@tylernathanreed First of all thank you so much for your replies, I think I should give more information about my case. Currently on Nova we have label on the resource view. But i am trying to get the resource name on a different part of the page (near the global search). There should be a way to get the current resource id/name outside of the resource because the navigation blade for example gets the current resource and changes the current resource's link's class to 'router-link-exact-active'.

**Comment by tylernathanreed** [comment]
@Milkhan

So that I completely understand, you're trying to obtain the name of the resource on the PHP side, but the resource you need is context sensitive (ex. name of the resource on a detail page).

If the resource name is in the URL, then you can use Nova to obtain the resource like so:

```php
Nova::resourceForKey(request()->resource)
```

**Comment by Milkhan** [comment]
@tylernathanreed  Thank you again so much, I've tried your suggestion but, request seems like doesnt have a resource property. I think all we can get from the request is path "request()->path()" and it doesnt work for $key. And I've noticed that layout.blade.php doesn't refresh.

**Comment by tylernathanreed** [comment]
@Milkhan

The request would only have a resource property on a resource page (index, detail, edit, etc.). It would have one on the dashboard.

As far as "refreshing" goes, you may want to consider using a Vue component instead.

Are you trying have the name of the resource in the header or something, like for a context menu dropdown?

**Comment by Milkhan** [comment]
@tylernathanreed Thank you for your help. Yes I was trying to build a custom menu on the header. If I understand you correctly, it's not possible with this approach and I have to build a custom vue component for this. In this case I should close this issue I guess.

**Comment by tylernathanreed** [comment]
@Milkhan

Yeah, that's probably true.

Out of my own personal curiosity, what is your motivation for adding a custom menu to the header? Are you wanting to create a context menu with actions?

**Comment by Milkhan** [comment]
@tylernathanreed It's just a custom breadcrumb on header, nothing fancy, we are just trying to make Nova look like client's design. Thank you again for your help.

**Comment by vayurobins** [comment]
> @tylernathanreed Thank you for your help. Yes I was trying to build a custom menu on the header. If I understand you correctly, it's not possible with this approach and I have to build a custom vue component for this. In this case I should close this issue I guess.

Hi @Milkhan did you manage to get this working with a Vue component? I am curious to how it can be done in Nova
