### ISSUE TITLE
Nova actions redirect in new tab

### ISSUE THREAD

**Issue by Dontorpedo** [laravel/nova-issues#1363]
Nova Actions should have also a method to redirect the user to a new tab.. maybe it could be possible trough the vue component....

````
return Action::redirect('https://example.com');

````

opens in same tab.. but if the redirect is a path of a generated pdf, its a bit annoying i think :(

is there allready a way to open in a new tab?

**Comment by tylernathanreed** [comment]
@Dontorpedo 

Nova currently changes the `window.location` setting to redirect the user. As it stands today, I don't believe this is possible.

However, something like this wouldn't be difficult to implement, I imagine.

**Comment by tylernathanreed** [comment]
@Dontorpedo 

I've created a PR to solve this problem.

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
