### ISSUE TITLE
Code field with empty value is displaying code editor on details page

### ISSUE THREAD

**Issue by tpetry** [laravel/nova-issues#1364]
- Laravel Version: 5.7.26
- Nova Version: 1.3.2
- PHP Version: 7.2.15
- Operating System and Version: Alpine Linux 3.9
- Browser type and version: Google Chrome 72.0.3626.109 (64-Bit)

### Description:
When a fields has an empty value in the database laravel nova is showing a dash on the details page to indicate that the field has no value. But for code fields an empty code editor is shown.

### Steps To Reproduce:
1. Create a `Text` and a `Code`fields
2. Save both in database with an empty value
3. The text field is displayed with a dash but the code field is showing the code editor

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
