### ISSUE TITLE
Eager Loading not working with MorphTo

### ISSUE THREAD

**Issue by chescos** [laravel/nova-issues#1365]
See [#112](https://github.com/laravel/nova-issues/issues/112), the same issue still exists with `MorphTo` relations.

**Comment by bartabel** [comment]
Same holds for the belongsToMany relation (PR mentioned under #112 only addresses belongsTo for as far as I can see).

**Comment by dkulyk** [comment]
PR was sent to upstream.

**Comment by dkulyk** [comment]
This has been fixed and will be included in the next release.

**Comment by PeteJStewart** [comment]
This also seems to be an issue for `HasMany`

**Comment by PeteJStewart** [comment]
And `BelongsToMany` | many to many relationship
