### ISSUE TITLE
Coordinate fields are not filled in by Place field

### ISSUE THREAD

**Issue by fede91it** [laravel/nova-issues#1366]
- Laravel Version: 5.7
- Nova Version:  1.3.1
- PHP Version: 7.3
- Operating System and Version: Win 10 x64
- Browser type and version: Chrome

### Description:

The Place field does not automatically fill in the longitude and latitude fields, but it does fill in the other fields (such as Country)

### Steps To Reproduce:

```php
public function fields(Request $request)
{
    return [
        Place::make('Place')
             ->latitude('lat')
             ->longitude('lng')
             ->onlyOnForms(),

        Country::make('Country')
               ->onlyOnForms()
               ->rules('required'),

        Text::make('Latitude', 'lat')
            ->onlyOnForms(),

        Text::make('Longitude', 'lng')
            ->onlyOnForms(),
    ];
}
```

The coordinate fields are not filled in.

**Comment by nickfla1** [comment]
Same issue, i'm also using Place with `onlyCities`

**Comment by davidhemphill** [comment]
I'm not able to reproduce this issue.
