### ISSUE TITLE
Image field: previewUrlCallback is not being used

### ISSUE THREAD

**Issue by ctessier** [laravel/nova-issues#1368]
- Laravel Version: 5.7.12
- Nova Version: 1.1.7
- PHP Version: 7.2
- Operating System and Version: macOS High Sierra 10.13.6
- Browser type and version: Chrome 71.0.3578.98 64bits

### Description:

The `previewUrl` meta is not being used in the Vue components. However, the thumbnailUrl is used for the rounded preview in the index lists, the details page and the form contrary to what the documentation says:
 
> By default, Nova will use the Storage::url method to determine the URL that should be used to display image previews on the resource detail screen and edit form.

(https://nova.laravel.com/docs/1.0/resources/file-fields.html#customization)

### Steps To Reproduce:

When trying to set the preview url for an image field like so, the image can never be seen.

```php
Image::make('photo')
  ->preview(function () {
    return 'https://avatars3.githubusercontent.com/u/4518186';
  }),
```

**Comment by mikebronner** [comment]
I can confirm this, just ran into this as well.
