### ISSUE TITLE
BelongsTo field increases response times significantly

### ISSUE THREAD

**Issue by chescos** [laravel/nova-issues#1369]
- Laravel Version: 5.7.5
- Nova Version: 1.3.2
- PHP Version: 7.2.5
- Operating System and Version: Ubuntu 18.04.1
- Browser type and version: Chrome 72.0.3626.96

### Description:

Let's assume I have a `User` resource and an `Invoice` resource. The `User` resource has a `HasMany` field for the `Invoice` resource and the `Invoice` resource has a `BelongsTo` field for the `User` resource.

When visiting a user's details view (`/nova/resources/users/1`), the loading time for the related `Invoice` index view increases immensely when displaying more resources via `perPageViaRelationship`. Database queries are not the issue, I am eager loading the `BelongsTo` field and I observed the database queries, all of them are fast.

From my tests, setting `perPageViaRelationship` to `5` results in an average response time of **500ms**. Setting `perPageViaRelationship` to `500` results in an average response time of **4000ms**.

Also, this seems to get worse when both resources have more fields (e.g 10 fields instead of just 2), response times for me then increased from **1000ms** to **9000ms**.

### Steps To Reproduce:

1. Create a `User` resource with a `HasMany` field, e.g:

```
// App/Nova/User.php

public function fields(Request $request)
{
  return [
    ID::make('ID', 'id'),
    HasMany::make('Invoices', 'invoices', Invoice::class),
  ];
}
```

2. Create the resource for the `HasMany` relationship with the corresponding `BelongsTo` relationship. Also, make sure you set the property `$perPageViaRelationship` to `5`, e.g:

```
// App/Nova/Invoice.php

public static $with = ['user'];

public static $perPageViaRelationship = 5;

public function fields(Request $request)
{
  return [
    ID::make('ID', 'id'),
    BelongsTo::make('User', 'user', User::class)->searchable(),
  ];
}
```

3. Create a `User` model that is related to at least 500 `Invoice` models, e.g:

```
$user = factory(\App\User::class)->create();

$invoices = factory(\App\Invoice::class, 500)->create([
  'user_id' => $user->id,
]);
```

4. Visit `/nova/resources/users/1` and observe how fast the index view of the related invoices loads.

5. Now change `$perPageViaRelationship` to `500`:

```
// App/Nova/Invoice.php

public static $perPageViaRelationship = 500;
```

6. Repeat step 4. and compare the response times.

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
