### ISSUE TITLE
Nova route not available

### ISSUE THREAD

**Issue by unlikenesses** [laravel/nova-issues#137]
I've installed Nova 1.0.5 on an existing Laravel 5.6 app. The `/nova` route returns a `404`. 

I have run `nova:install`, so I do have `App\Providers\NovaServiceProvider::class` in my `config/app.php`. 

Strangely it doesn't seem to have copied the migration across (when I run `migrate` I get the message "Nothing to migrate").

EDIT: If it makes a difference, the existing app uses Laravel Passport.

**Comment by RicardoRamirezR** [comment]
Does the app's namespace is other than *App*?

**Comment by unlikenesses** [comment]
Solved it: `php artisan config:clear`.
