### ISSUE TITLE
Customisable global search input field focus shortcut

### ISSUE THREAD

**Issue by lasseeee** [laravel/nova-issues#1370]
It would be nice to be able to customise the shortcut used to focus on the global search input field, as the current key (<kbd>/</kbd>) is not as easy to input on some international keyboard layouts as on the US layout.

**Comment by itsnunolemos** [comment]
The biggest problem is in the Portuguese language. 
The keycode used on the Portuguese keyboard belongs to a symbol very used in writing. 
It's practically impossible to create a text.

**Comment by stephenlake** [comment]
Would be great. When using custom fields in custom tools, the input loses focus whenever the `/` is pressed, very annoying.

**Comment by davidhemphill** [comment]
No plans to change this as its a very common shortcut used in many apps. What do y'all use to type forward slashes in URLs?

**Comment by davidhemphill** [comment]
@stephenlake The custom field must handle the event and prevent it from bubbling up to the document where the search will be focused.

**Comment by stephenlake** [comment]
@davidhemphill Figured, eventually. Codemirror's editors handle this quite well, which was my replacement dependency at the end of the day. Thanks for the feedback.

**Comment by itsnunolemos** [comment]
@stephenlake to make forward slashes  I use `shift + 7` (keycode 55)

**Comment by checkerschaf** [comment]
> No plans to change this as its a very common shortcut used in many apps. What do y'all use to type forward slashes in URLs?

Why don't you make it customizable? Using the german keyboard it's impossible to enter the search bar as I have to use `SHIFT + 7` to write slashes too. Please implement this feature and fallback to the `/` character for US keyboards.

**Comment by lasseeee** [comment]
Since Nova supports localisation, and is this is sort of a localisation issue, I'm hoping it gets added in a future release. Fingers crossed.

**Comment by matkovsky** [comment]
It may very well be a common keyboard shortcut to use, but Nova's implementation is disregarding non-US keyboard users.

Here, on GitHub, I can use my Shift+6 combo to trigger the search _(the shortcut for the slash `/` character on my Hungarian layout)_, and it works. My full-sized keyboard also has a numpad, so I can also hit the `/` there to focus GitHub's search input… and that works too.

None of these work in Nova. Am I missing something? 🤔

**Comment by itsnunolemos** [comment]
@matkovsky forget... The Laravel Nova is only for US keyboard users.
I love this quote by @davidhemphill:

> is a very common shortcut used

Used by who? You tested this in others keyboards languages? 
We are not talking about free software. We pay 99$. I'm upset with this arrogance!

**Comment by leovalen** [comment]
+1, this is a localization issue and it should be possible to customize the shortcut.

**Comment by jordanpartridge** [comment]
It would be nice to be able to customize the binding. I'd love it to be cmd k to be compatible with command palettes that sites like github seem to have.
