### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by sharmaanil8866** [laravel/nova-issues#1371]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to still post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

in nova nova-components  router are not found controller class

**Comment by dkulyk** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](https://larachat.co/).
