### ISSUE TITLE
Action Log polling never stops

### ISSUE THREAD

**Issue by chescos** [laravel/nova-issues#1372]
- Laravel Version: 5.7.5
- Nova Version: 1.3.2
- PHP Version: 7.2.5
- Operating System and Version: Ubuntu 18.04.1
- Browser type and version: Chrome 72.0.3626.96

### Description:

When the Action Log is enabled for a resoruce and you open the details view of the resource, Nova will send 2 requests every 15 seconds to update the Action Log. The polling never stops, even if the tab/window is inactive. So if you have 10 tabs open, your browser sends 20 requests to your app every 15 seconds - indefinitely. I don't think it's supposed to be like that, it's a huge waste of resources.

### Steps To Reproduce:

1. Enable the Action Log on a resource
2. Open the details view of the resource in multiple tabs
3. Minimize your browser and observe the requests that are being made to your app

**Comment by dillingham** [comment]
https://github.com/laravel/nova/blob/e6cf274dc130a20c617b9069ab3c4cb5a0455a10/resources/js/views/Index.vue#L414

If document.hasFocus

https://developer.mozilla.org/en-US/docs/Web/API/Document/hasFocus

**Comment by tufankilicaslan** [comment]
I am using this  https://github.com/serkanyersen/ifvisible.js  tool for refreshing metrics only  if document is active. it's really good, and cross browser supported. I think similar tools needs to implement for action logs.

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
