### ISSUE TITLE
attribute name for validation rule

### ISSUE THREAD

**Issue by dormadekhin** [laravel/nova-issues#1374]
how to set attribute name for validation rule message?
on text field used label and not always right, but for Select displaying  column name from db
![image](https://user-images.githubusercontent.com/32381310/52916283-f6397f00-330f-11e9-87c3-33e5b3f6bfe1.png)

**Comment by kirya-dev** [comment]
+1

**Comment by davidhemphill** [comment]
Duplicate of #556

**Comment by davidhemphill** [comment]
Duplicate of #346

**Comment by dev-lav** [comment]
@dormadekhin @kirya-dev  You can override method `validatorForCreation` and `validatorForUpdate` in your resource.
reference:  https://medium.com/dot-lab/my-first-project-using-laravel-nova-9b24ddf19d7b
