### ISSUE TITLE
Customize metrics cache key, trend/value metrics label.

### ISSUE THREAD

**Issue by tolawho** [laravel/nova-issues#1377]
Sometime with one metrics, I want show the report for many user type. If the cache made for someone before then the metrics is no longer true for others.

Example: I have three user type with same metrics
![image](https://user-images.githubusercontent.com/12527881/52990404-a3a8b180-343a-11e9-99a1-ccc50155d46a.png)

Same with the cache key, name of the metrics with different user types, there will be different name.

![image](https://user-images.githubusercontent.com/12527881/52990757-4ada1880-343c-11e9-8c9b-af8aa3a6baa6.png)

Hope this will implement in the feature.

**Comment by dkulyk** [comment]
You can override `getCacheKey` method:
```php
protected function getCacheKey(NovaRequest $request)
{
    return parent::getCacheKey($request) . '.my_key';
}
```
