### ISSUE TITLE
Date filter between start and end date

### ISSUE THREAD

**Issue by kokarat** [laravel/nova-issues#1378]
Date filter between start and end date like this package but this package is DEPRECATED
Since Nova 1.1.8 
![7sg50yef7o](https://user-images.githubusercontent.com/147563/53030426-59a4e780-349d-11e9-9a4c-d9e94cb0239e.gif)

https://novapackages.com/packages/64robots/nova-date-filter

**Comment by dillingham** [comment]
@kokarat just make [two date filters](https://nova.laravel.com/docs/1.0/filters/defining-filters.html#date-filters), one "DateFrom" and one "DateTo"

from 
```php
$query->where('created_at', '>=', $value);
```
to
```php
$query->where('items.run_at', '<=', $value);
```

**Comment by dkulyk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by Vusys** [comment]
For the benefit of anyone finding this from Google as I did, here are two filters that you can just copy and paste into your filters directory.

https://gist.github.com/Vusys/31bc0389e39fb284914f0de81af626ea

**Comment by crynobone** [comment]
Nova 4 new filterable feature solves this.
