### ISSUE TITLE
HasMany Relation only showing 5 Resources

### ISSUE THREAD

**Issue by StanBarrows** [laravel/nova-issues#1382]
- Laravel Version: 5.7.*
- Nova Version: 1.3.2
- PHP Version: 7.1

### Description:

I defined a HasMany relation on a model, but within Nova it's only showing 5 Resources before i have to paginate. Is this normal? How can I increase the limit of the results?

### Steps To Reproduce:

`HasMany::make('Messages'),`

<img width="1290" alt="image" src="https://user-images.githubusercontent.com/10268813/53235129-625e0f00-3691-11e9-919c-617f7800a88b.png">

**Comment by dillingham** [comment]
Look in the resource class and see the setting for changing the perPage for relationships

**Comment by StanBarrows** [comment]
Thanks for the reply, is there any documentation of how to set the settings? The Ressource is empty beside my code.

**Comment by dillingham** [comment]
Not currently, and I meant the resource class it extends. This isn’t a place for personal questions though. Use discord :)

**Comment by dillingham** [comment]
@StanBarrows `$perPageViaRelationship = 10`

**Comment by ammarax** [comment]
you must add to related Nova entity class ( hasMany::make(RelNovaEntity) )
public static $perPageViaRelationship = 10;

**Comment by patrickgilmour** [comment]
If your resource class is "Comments", for example, and you want 10 Comments to appear on your Posts resource page (where Posts hasMany Comments), add this to your `app/Nova/Comments` class:

`public static $perPageViaRelationship = 10;`

**Comment by Jonathan-Bryan** [comment]
It would be nice to have the same pagination flexibility on relationship fields as we do on resource pages. Especially for the user to be able to change the number of results. The use case being when you only want to look at the details of the resource it makes sense to have a small number of results in relationship fields, like the default of 5, but when the user comes to the page particularly to look at the related results, they might wish to expand the size of the result set significantly.

**Comment by gustav1105** [comment]
Please provide support for the request that the per page filter on resource is exposed on the relationship of that resource as well

**Comment by emjayess** [comment]
> Thanks for the reply, is there any documentation of how to set the settings? The Ressource is empty beside my code.

Still not documented. 

![stillnotdoc](https://user-images.githubusercontent.com/194904/111857491-c8183600-88ff-11eb-8b68-175574787470.png)

---

*I love spending 63% of my day googling solutions for a commercial software package.*

**Comment by dan-lutd** [comment]
> Thanks for the reply, is there any documentation of how to set the settings? The Ressource is empty beside my code.

look in the abstract class nova/src/Resource.php

for a few more options.

**Comment by xdubois** [comment]
Just bump up into the same issue, it's still not documented

**Comment by connecteev** [comment]
+1, this needs to be documented

**Comment by vedmant** [comment]
> public static $perPageViaRelationship = 10;

This sets value for all relationships, but if I want to set different values for different relationships in the resource?

It makes much more sense to do something like:

```
HasMany::make('Events')->collapsedByDefault()->perPage(25),
```
