### ISSUE TITLE
Route [nova.login] not defined.

### ISSUE THREAD

**Issue by jcalosor** [laravel/nova-issues#1385]
- Laravel Version: 5.7.27
- Nova Version: 1.2
- PHP Version: 7.2.12 
- Operating System and Version: MacOS 10.13.6 
- Browser type and version: Chrome (Latest) FireFox (Latest)

### Description:
Whenever I access my nova route in /admin <-- (this is where my nova resides) I get this exception thrown from`/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php` line 389, `throw new InvalidArgumentException("Route [{$name}] not defined.")`, my nova was installled correctly and currently I don't have any other existing app routes this is a fresh install of laravel and fresh install of nova.

It was working fine until I introduced the custom path.

### Steps To Reproduce:
1. Change the `'path' => '/admin'` 
2. Run `php artisan config:clear` or `php artisan config:cache`

**Comment by jcalosor** [comment]
Anyone? This has been a huge blocker in our project, any info bout this is greatly appreciated.

**Comment by dkulyk** [comment]
Did you try run `php artisan route:clear`?

**Comment by Peter-Mulligan** [comment]
Try running `php artisan route:list` and make sure all the routes are there.
If not, they can be manually added in `routes/web.php`, then run the php artisan config/cache/route cleaning commands.
Short of that, check your 404 route handling and any `*` wildcard routes that could be catching the request before it hits nova.

**Comment by davidhemphill** [comment]
Sorry, but we are unable to debug your issue without a reproducible code example. Once you provide that we can open this up again.

**Comment by chinleung** [comment]
> Anyone? This has been a huge blocker in our project, any info bout this is greatly appreciated.

You need to make sure you have a `RouteServiceProvider` in your `config/app.php`.
