### ISSUE TITLE
Create new "Resource Panel" Vue Component

### ISSUE THREAD

**Issue by tylernathanreed** [laravel/nova-issues#1386]
I'm asking for this, as I'm working on a package that will modify some of the tools that appear above the resource table, but my changes would not be isolated to the scope I would like.

Modifying the tools above the resource table is technically doable, but it requires me to override the Index, Lens, and Detail pages, which is more than I bargained for. I don't want to become subject to updates to the Index, Lens, and Detail pages for changes outside of the scope of what I'm working with.

All of my changes could be isolated within a new "Resource Panel" component, which would appear on all three landing pages. Personally, I believe that this would normalize the appearance and functionality behind the resource panel, as currently I'm seeing a lot of copy/pasted code in each landing page.

If this is something you'd be on board with, I'm willing to implement this myself with a pull request. I just don't want to get started on this if it's going to get shot down once completed.

**Comment by davidhemphill** [comment]
Either way, you'd still would have to keep in check with the REST API as it changes. I'm also not a huge fan of "optimization" type PR's, as they tend to introduce unforseen bugs that the Nova team has to maintain when removing the duplicated code.

**Comment by tylernathanreed** [comment]
@davidhemphill So then my only way to augment the tools that appear above the resource panel is to override the Index, Detail, and Lens pages? I'm fine with this solution, but I found great difficulty in actually pulling this off. I know that I can override the vue components, but they way they're registered in the routing layer doesn't allow for this to be sufficient.

Is there something that I'm missing, or is this sort of end-user change not something that the Nova teams plans to support?
