### ISSUE TITLE
Package cannot install to "/app/nova-components/ToolName" inside its source

### ISSUE THREAD

**Issue by unlikenesses** [laravel/nova-issues#1389]
- Laravel Version: 5.7.27
- Nova Version: 1.3.0
- PHP Version: 7.1
- Operating System and Version: macOS High Sierra

### Description:

When I create a resource with `php artisan nova:resource-tool test/tool-name`, and enter No to the npm questions, and Yes to updating the Composer packages, I get this error:

> Package test/tool-name cannot install to "/app/nova-components/ToolName" inside its source at "/app/nova-components/ToolName"

I did previously create and remove a tool of the same name. But I've scoured the codebase and removed all references to the previous tool. I've run `composer update`, `composer dump-autoload` and `php artisan cache:clear` and `config:clear`.

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).

**Comment by webornottoweb** [comment]
@davidhemphill and? Your chats only compose questions wo any support

**Comment by atoff** [comment]
Also have this issue on Nova 1.0, Laravel 5.7. Seeing as this isn't visibly documented anywhere that I could find, I wouldn't really regard it as a general question, especially as it happens when following the tool creation advice...

**Comment by davidhemphill** [comment]
@webornottoweb This issues board is not a support channel, it's a place to report and discuss bugs and feature requests. I ran `art nova:resource-tool test/tool-name` and was able to `composer install`. Make sure you try removing your vendor folder.

Without anything else to diagnose, I'm going to close this. Feel free to reply with any other information I can use to demonstrate a bug.

**Comment by webornottoweb** [comment]
@davidhemphill  Accept my sincere apologies - removing vendor folder and re-installing all dependencies solved my problem. Also marked as solved in discord channel for other people
