### ISSUE TITLE
HasMany Name is ignored, and Label of associated Model used.

### ISSUE THREAD

**Issue by liamcottle** [laravel/nova-issues#139]
When adding a `HasMany` field to a Nova Resource, the `name` value passed into the `make` method is ignored, and instead the label of the associated model is used in the UI.

Example: `HasMany::make('Referrals', 'referrals', User::class)`.

When viewing the `User` resource in Nova, from the screenshot below you can see that the `User` resource label is being shown.

I would assume this should be the name passed into the `HasMany` call, thus display `Referrals` instead of `Users` (in the top left).

The buttons to `Create User` seem fine in this context, since that is what they are, but the title of should be the name rather than label? As currently it's not possible to customise it.

<img width="994" alt="screen shot 2018-08-25 at 2 12 30 am" src="https://user-images.githubusercontent.com/3173581/44589436-b1270b00-a80c-11e8-8ad7-fc476c67bd21.png">

Here's a full page screenshot (zoomed out)

<img width="1168" alt="screen shot 2018-08-25 at 2 16 17 am" src="https://user-images.githubusercontent.com/3173581/44589548-f1868900-a80c-11e8-806d-32b642b860fc.png">

The `Referred By` field is just `BelongsTo::make('Referred By', 'referredBy', User::class)` if that's relevant at all.

**Comment by jsiebach** [comment]
The relevant functions to overwrite on your resource class are these:


```
    /**
     * Get the displayble label of the resource.
     *
     * @return string
     */
    public static function label()
    {
        return Str::plural(class_basename(get_called_class()));
    }

    /**
     * Get the displayble singular label of the resource.
     *
     * @return string
     */
    public static function singularLabel()
    {
        return Str::singular(static::label());
    }

```

**Comment by liamcottle** [comment]
Yes, I mentioned that. However in this case, the label shouldn't be used, and the field name should be.

**Comment by liamcottle** [comment]
Here's another example.

Let's say I have three `HasMany` fields on my `User` resource, which all refer to the `User` resource itself... Since the `User` resource would return `Users` for the `label` method, all of the `HasMany` fields show `Users` as the title.

Which really, they should show the name value passed into the `make` method of `HasMany`.

```
HasMany::make('Referrals', 'referrals', User::class)
HasMany::make('Another One', 'anotherOne', User::class)
HasMany::make('Something Else', 'somethingElse', User::class)
```

All three of these panels show up on the `User` resource page, and all have the title `Users`, whereas what they should show is, `Referrals`, `Another One` and `Something Else`.

<img width="1188" alt="screen shot 2018-08-25 at 2 51 24 am" src="https://user-images.githubusercontent.com/3173581/44591720-99eb1c00-a812-11e8-8753-70172736906b.png">

**Comment by ok200paul** [comment]
This is the same for `BelongsToMany`, it'd be just dandy if it was fixed there too 👍

**Comment by pr-baernholdt** [comment]
The same issue.

Using this code in resources, it shows `Somes` and `Others` as title instead of `Some reviews` and `Other reviews`
```
            BelongsToMany::make('Some reviews', 'someReviews', Some::class),
            BelongsToMany::make('Other reviews', 'otherReviews', Other::class),
```
There seems to be a missing check in the `label` method of the parent `Resource` class to see if the name is already overwritten instead of just displaying the default value.

**Comment by liamcottle** [comment]
Fixed in v1.1.4, Thanks! :)

**Comment by ok200paul** [comment]
Hey @liamcottle is it really fixed in 1.1.4? I'm seeing the same behaviour. 
![image](https://user-images.githubusercontent.com/22406523/46899210-3c9f4d00-cedc-11e8-8b23-1a0b567cb58c.png)
![image](https://user-images.githubusercontent.com/22406523/46899216-4e80f000-cedc-11e8-9d8e-35cc2212f8f9.png)

**Comment by abordage** [comment]
>is it really fixed in 1.1.4?
Fixed, yes

**Comment by liamcottle** [comment]
@ok200paul Make sure to run `php artisan nova:publish`.
https://nova.laravel.com/docs/1.0/installation.html#updating-nova

**Comment by pr-baernholdt** [comment]
Fixed for me as well. Thanks.

**Comment by masardee** [comment]
@liamcottle 
I used "fresh" Nova 1.1.4, but still got a little issue.

![image](https://user-images.githubusercontent.com/11531017/47234627-a5b52200-d400-11e8-8f0a-c287a99ef2fe.png)

![image](https://user-images.githubusercontent.com/11531017/47234527-5838b500-d400-11e8-8b61-d6563afa2a66.png)
