### ISSUE TITLE
Correction of the conditional to apply styles.

### ISSUE THREAD

**Issue by jmmendozamix** [laravel/nova-issues#1390]
- Laravel Version: 5.7.19
- Nova Version: 1.3.2
- PHP Version: 7.2
- Operating System and Version: Windows 10
- Browser type and version: Chrome

### Description: Please, correct the conditional to add styles from NovaServiceProvider

```
@foreach(Nova::availableStyles(request()) as $name => $path)
    @if (starts_with($path, ['http://', 'https://']))
        <link rel="stylesheet" href="{!! $path !!}">
    @else
        <link rel="stylesheet" href="/nova-api/styles/{{ $name }}">
    @endif
@endforeach
```

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
