### ISSUE TITLE
How to install Nova through composer in a team/CI

### ISSUE THREAD

**Issue by maarten00** [laravel/nova-issues#1391]
Hi,

We have a team working on a project with Nova. I have followed the [installating via Composer](https://nova.laravel.com/docs/1.0/installation.html#installing-nova-via-composer) section. This gave me an error that the Nova github repository could not be found. After connection my Github account on nova.laravel.com I now have access to the Nova repo and I can run `composer install` without any problems. However, my teammates do not have access so they cannot run `composer install`. How should I give my teammates and our CI server access to the Github repo?

**Comment by jordyvandomselaar** [comment]
Bump

**Comment by jordyvandomselaar** [comment]
We currently sorta solved it by sending `vendor/` to every team member. Hoping for an official fix though.

**Comment by dillingham** [comment]
Give them the api token

**Comment by jordyvandomselaar** [comment]
Where do they put it though? @dillingham 

ps: Thanks for the reply!

**Comment by dillingham** [comment]
As the password for the http basic password in auth.json

**Comment by dillingham** [comment]
I think there was a env approach floating around too but I don’t recall

**Comment by jordyvandomselaar** [comment]
The Github or the Nova api key? We currently have the Nova key in there and it doesn't seem to work.

**Comment by dillingham** [comment]
Nova. Works for me 🤷‍♂️

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).

Also: use an auth.json file and place the license accounts credentials in there. Email support if you need some more help in that.
