### ISSUE TITLE
Add Relationship Type to getActions() in Index and Lens

### ISSUE THREAD

**Issue by tylernathanreed** [laravel/nova-issues#1392]
I would like to be able to have actions for a resource that do not appear when that model is presented as a resource.

However, doing so would require that the relationshipType parameter is passed to the request made in "getActions()" on both the Index and Lens pages.

Right now, this is my "authorizedToSee":

```php
/**
 * Determine if the action should be available for the given request.
 *
 * @param  \Illuminate\Http\Request  $request
 *
 * @return boolean
 */
public function authorizedToSee(Request $request)
{
    // Make sure the relationship is not many to many
    if($request->relationshipType == 'belongsToMany' || $request->relationshipType == 'morphToMany') {
        return false;
    }

    // Return the parent result
    return parent::authorizedToSee($request);
}
```

I've overridden the main "authorizedToSee" method, as I'm trying to create a subclass of "Non Pivot Actions".

**Comment by davidhemphill** [comment]
Can you explain your use-case in more concrete terms? Like what specifically are you trying to do?

**Comment by tylernathanreed** [comment]
@davidhemphill 

I would like to have this so that I can define an action on a resource, and that action is _not_ executable when shown through a pivot.

An equivalent example already present in Nova is "Delete". If a User belongs to many Roles (and vice-versa), when displaying the User's Roles on the User's detail page, the "Delete Role" action does not appear. However, if you navigate to the Role's Index or Detail page, the "Delete Role" action then appears.

Essentially, there are certain actions that only make contextual sense to appear on the Index/Detail page for that resource. When the resource is being displayed through a pivot (via belongs/morph to many), while the action would _technically_ work (i.e. deleting the role), it may not make contextual sense for the action to appear there.

**Comment by davidhemphill** [comment]
Closed in http://github.com/laravel/nova#498233c07088405ec063884dbf39fbd69822b1d1
