### ISSUE TITLE
ESC key does not close modal

### ISSUE THREAD

**Issue by m-lotze** [laravel/nova-issues#1393]
- Laravel Version: 5.7
- Nova Version: 1.3.2

### Description:

I created a tool and used some of the components of nova. The `modal` component produces a javascript error if you press ESC:

```
Uncaught TypeError: Cannot read property 'composedPath' of undefined
```

### Steps To Reproduce:
Press ESC key on any modal to close it.

### BTW:

It would be really nice if you could include all nova vue components in the documentation. So people can reuse them in their own components instead of recreating things like modals, pagination etc.

**Comment by davidhemphill** [comment]
This isn't enough information to reproduce your issue. Closing until you provide more information (browser, etc)

Nova's components, while possibly reusable are for internal use. We can (and do) break them from time to time, and thus don't want to commit to a public API.

**Comment by m-lotze** [comment]
Browser: Chrome

Open e.g. the confirm modal and press ESC.

**Comment by Noogic** [comment]
@m-lotze have yo found a fix for this? I have the same issue and can't find a solution.

I've tried with nova 1.3.2 and 1.3.1, both with laravel 5.7 and tried installing from repository and with the zip directly. In all the cases I get the same error

```
app.js?id=7319bf5027431449796c:1 Uncaught TypeError: Cannot read property 'composedPath' of undefined
    at t.default (app.js?id=7319bf5027431449796c:1)
    at app.js?id=7319bf5027431449796c:1
    at app.js?id=7319bf5027431449796c:1
    at Ge (vendor.js?id=b30263b2f9d68433c3ce:1)
    at Function.hr.filter (vendor.js?id=b30263b2f9d68433c3ce:1)
    at a.close (app.js?id=7319bf5027431449796c:1)
    at a.handleEscape (app.js?id=7319bf5027431449796c:1)
```

Browser: Chrome 72
Process: in `nova/resources/users` I click on _delete button_ and then, with the modal open, press *ESC* key. The modal keeps open and the console show this error.

**Comment by m-lotze** [comment]
No. It is a bug in nova. Unfortunately it has not been addressed yet. For a paid software the maintainers are quite slow in response and obvious issues get just closed instead of fixed.

**Comment by bolechen** [comment]
confirmed is a bug !
