### ISSUE TITLE
Nova not working on Windows 2016

### ISSUE THREAD

**Issue by TWG-Matt** [laravel/nova-issues#1394]
- Laravel Version: 5.7.28
- Nova Version: 2.0.0
- PHP Version: 7.3
- Operating System and Version: Windows Server 2016
- Browser type and version: Google Chrome 72.0.3626.109

### Description:
I'm having a few issues with running nova on a dev server locally.  

1.  When I try to load the dashboard, none of the styling is being loaded using ```{{ mix('app.scss', 'vendor/nova') }}```.  If I change it to ```{{ asset('/vendor/nova/app.css') }}```, the styling loads just fine.

2.  When I try to go to `mysite.test/test/application/nova` and login, it takes me to `mysite.test/nova` .  I can't figure out why.

3.  When I look at the inspector when any pages in the admin area load, I get numerous errors when it tries to load the nova-api.  The calls keep going to `mysite.test/nova-api` instead of `mysite.test/test/application/nova-api`.

**Comment by markgp** [comment]
Nova is not designed to run in a subfolder. Your application needs to be on the root of your server. If you absolutely need your app to be in a subfolder, you could set up a server alias from `/test/application/nova-api` to `/nova-api`.

See #471 for discussion.

**Comment by TWG-Matt** [comment]
Man that really stinks.  My application has to be in a sub directory so I guess I'm just going to have to scrap Nova and request a refund.  Kinda sad that Nova isn't as flexible as the Laravel package is on where it's installed.  Would have loved to have used it for this project.  Off to one of the free admin packages.
