### ISSUE TITLE
Nova::provideToScript => array_merge_recursive

### ISSUE THREAD

**Issue by m-lotze** [laravel/nova-issues#1395]
Please change `array_merge` to `array_merge_recursive` in the method `provideToScript` in `Nova.php`. 
This change would make it easy e.g. to add custom translations in the `NovaServiceProvider`

```
Nova::serving(function (ServingNova $event) {
            Nova::provideToScript([
                'user' => $event->request->user()->toArray(),
                'translations' => [...]
            ]);
        });
```

**Comment by jbrooksuk** [comment]
Duplicate of https://github.com/laravel/nova-issues/issues/665
