### ISSUE TITLE
FR: Update Action::canSee callback to include model on detail view

### ISSUE THREAD

**Issue by FrittenKeeZ** [laravel/nova-issues#1397]
If you have an action which should be hidden on detail view, depending on the specific model state, you currently have to do this to grab the request model:
```php
(new MyAction)->canSee(function ($request) {
    $model = $request->findModelQuery()->first(); // Will return NULL when running the action.
    return empty($model) || $model->myActionIsAllowed();
})
```
I propose to include the model on detail view to make this easier:
```php
(new MyAction)->canSee(function ($request, $model) {
    return empty($model) || $model->myActionIsAllowed();
})
```

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by MohammadAbusaleh** [comment]
@FrittenKeeZ bless your soul! I spent the last 7 hours trying to figure out what did I do wrong and why is it returning null then I found this gym!

**Comment by davidhemphill** [comment]
After looking into this, I don't think it makes sense to add this since it's so easy to get the model from the request data.

**Comment by SquareBeard** [comment]
@davidhemphill I don't think it's that easy.

If I want to display the action on each row in the index view (no multi select support) and on the detail page, here are all the steps I need to do to be able to conditionally display the action:
```
(new Actions\Action)
    ->canSee(function ($request) {
        if ($this->resource->id !== null) {
            // Recover the model for the detail page request
            $model= $this->resource;
        } elseif ($request->resourceId !== null) {
            // Recover the model for the index page ajax request (called for each row)
            $model= $request->findModelQuery()->first();
        } else {
            // If the request contains 'resources', it means the action was excecuted and we must return true or we'll get a 403
            // Otherwise just return false to hide the action (that's the multiselect on the index page)
            return $request->has('resources');
        }

        return $model->my_condition;
    })
    ->canRun(function ($request, $model) {
        return $model->my_condition;
    })
```

Passing the model to the `canSee` method, even if it is `null` sometimes, would be a lot cleaner imho.

**Comment by crynobone** [comment]
@SquareBeard 

In latest Laravel Nova you can simplify this to:

```php
(new Actions\Action)
    ->canSee(function ($request) {
        // The action was excecuted and we must return true
        if ($request instanceof \Laravel\Nova\Http\Requests\ActionRequest) {
            return true;
        }

        return $this->request->my_condition;
    })
    ->canRun(function ($request, $model) {
        return $model->my_condition;
    })
```
