### ISSUE TITLE
Rules & canSee that depends on model

### ISSUE THREAD

**Issue by ahmedkandel** [laravel/nova-issues#1398]
- Laravel Version: 5.7.27
- Nova Version: 1.3.2
- PHP Version: 7.2
- Operating System and Version: Windows 10
- Browser type and version: Chrome 72.0.3626.119

### Description:
Field rules have no effect When using field authorization "canSee" that depends on the model properties.

The authorization is working while the rules no.

### Steps To Reproduce:
```
Text::make('Name')
    ->hideFromIndex()
    ->hideWhenCreating()
    ->rules('required')
    ->canSee(function ($request) {
        return $this->age > 18;
     }),
```

**Comment by dkulyk** [comment]
Try it:
```php
    ->canSee(function ($request) {
        $model = $request->findModelOrFail();

        return $$model->age > 18;
     }),
```

**Comment by ahmedkandel** [comment]
@dkulyk Thanks for the swift reply, It didn't work as the response gives 404 in browser console, Maybe the reason is in the definition of  findModelOrFail in `nova/src/Http/Requests/InteractsWithResources.php` as it gets the first model of findModelQuery or fails which may be the reason of 404, While the following works:
```
->canSee(function ($request) {
    return optional($request->findModelQuery()->first())->has_rr;
})
```
but as long as I have many fields that need the same logic querying the DB for the model for each field will results in many duplicated queries, Your answer using findModelOrFail which make use of spatie/once.

Any ideas?

**Comment by ahmedkandel** [comment]
As a workaround for the moment will use `$request->findModelQuery()->first()` and cache the model for the current request to avoid performance issues.

@davidhemphill 
I would suggest passing the `$model` as a variable to fields method like `$request`.
Another suggestion " I don't know where can I leave suggestions ":
Add indexFields() method to the resource that returns only fields for index view "sort of a lens" simple fields without many chaining methods e.g. ->rules()->fillUsing() in order to avoid elaboration of all fields and enhance performance.

Thanks.

**Comment by davidhemphill** [comment]
Sometimes the resource is spun up without a model instance, which leads to errors like this where you're relying on a model instance. Using `optional` like you have there is the correct approach. If you're concerned about queries then use something like the `once` helper to limit the call to one model.

**Comment by bkuhl** [comment]
> Using optional like you have there is the correct approach.
I'm encountering this as I'm trying to hide the action when it's not needed on the model itself (I have 1 action to setup a trial, 1 to remove the trial, don't want both visible at the same time).  Using `canSee()` I can toggle the menu option, but the action execution causes a 404 when an empty model is produced rather than querying it from the database.  `optional()` doesn't help such a situation.

I've had to work around it with this...

```
            SetupPremiumTrial::make()
                ->onlyOnDetail()
                ->canSee(function (NovaRequest $request) {
                    return !$this->resource->isPremium() && $request->user()->can(Ability::MANAGE_PREMIUM);
                }),
            CancelPremiumTrial::make()
                ->onlyOnDetail()
                ->canSee(function (NovaRequest $request) {
                    if (!$this->resource->exists) {
                        return $request->user()->can(Ability::MANAGE_PREMIUM);
                    }
                    return  $this->resource->isOnTrial() && $request->user()->can(Ability::MANAGE_PREMIUM);
                }),
```
