### ISSUE TITLE
Undefined when trying to access field within ResourceTool

### ISSUE THREAD

**Issue by Jam0r85** [laravel/nova-issues#1399]
- Laravel Version: 5.8.2
- Nova Version: 2.0

Within a custom resource tool which was working prior to updating laravel & nova i'm now getting 'undefined' when console.log(this.field) within my tool.js file.

```
<script>
    export default {
        props: ['resourceName', 'resourceId', 'field'],

        data() {
            return {
                loading: true,
                notes: [],

                form: {
                    body: null
                }
            }
        },

        mounted() {
            console.log(this.field);
            this.loadNotes();
        },
```

Some background info, I was accessing parent through the field variable to retrieve notes from a polymorphic table eg.

```
            loadNotes() {
                Nova.request().post('/nova-vendor/nova-notes/index', {
                    parent_id: this.resourceId,
                    parent_type: this.field.parent
                }).then(response => {
                    this.notes = response.data.data;
                    this.loading = false;
                })
            },
```

With my NovaNotes resource tool as follows

```
    /**
     * The parent model to be used when looking for notes.
     *
     * @param  string  $parent
     * @return \Jam0r85\NovaNotes\NovaNotes
     */
    public function parent($parent)
    {
        return $this->withMeta([
            'parent' => $parent
        ]);
    }
```

**Comment by Jam0r85** [comment]
Forgot to add resourceName and resourceId appear in the console fine when logging them.

Just cannot find field.

**Comment by Jam0r85** [comment]
I also have another resource tool that’s working fine so slightly confused here.

There’s no obviously differences between the tools either.

**Comment by beebmx** [comment]
I have the same issue.
I think this problem is with Nova 2.0 and Laravel 5.8, because in an early version it works fine.

The **field** prop it doesn't fill with data.

**Comment by beebmx** [comment]
I think this is the problem.

In previous version the panel was generated with this code:

```
public function jsonSerialize()
    {
        return [
            'component' => 'panel',
            'name' => $this->name,
            'showToolbar' => $this->showToolbar,
        ];
    }
```

And in the new version the `component` is what the resource-tool defines:

```
public function jsonSerialize()
    {
        return array_merge([
            'component' => $this->component(),
            'name' => $this->name,
            'showToolbar' => $this->showToolbar,
        ], $this->meta());
    }
```

The problem with this is than the Panel.vue inject the **field** value, and if is not a panel, the **field** prop is never in the resource-tool.

**Comment by Jam0r85** [comment]
@beebmx seems like you're correct.

I've put the following into my NovaNotes resource tool and its now working.

```
    /**
     * Prepare the panel for JSON serialization.
     *
     * @return array
     */
    public function jsonSerialize()
    {
        return array_merge([
            'component' => 'panel',
            'name' => $this->name,
            'showToolbar' => $this->showToolbar,
        ], $this->meta());
    }
```

**Comment by dkulyk** [comment]
PR was sent to upstream.

**Comment by greggh** [comment]
I am having this same problem. Can't pass in values via field because it is 'undefined'.

**Comment by greggh** [comment]
I would like to add that the solution of adding jsonSerialize to my resource tool did not solve it for me.

**Comment by dkulyk** [comment]
This has been fixed and will be included in the next release.

**Comment by greggh** [comment]
@dkulyk just upgraded to 2.0.2, this error is still happening. this.field is still undefined.

**Comment by dkulyk** [comment]
@greggh Make a new issue and describe what is wrong.

**Comment by gwleuverink** [comment]
I can confirm this issue still exists in v2.1.0 on L5.8. 

Like @Jam0r85 suggested, after adding jsonSerialize method to my resource tool class the field prop in the tool component is populated as expected again.

**Comment by glebihan** [comment]
@greggh @gwleuverink I was having the same issue until I noticed a change in the implementation of `ResourceTool`. I was defining the of the custom component used by the resource tool the way it is described in the documentation, ie :+1: 
```php
public function component()
{
    return "component-name";
}
```

 I replaced that with :

```php
public $toolComponent = 'component-name';
```
Everything is now working.

@dkulyk Shouldn't the documentation be updated and a note added to the release notes ?

**Comment by alberto-bottarini** [comment]
2.0.9 and still exists.
I solved using `const field = this.panel.fields[0]`

**Comment by penguinblanket** [comment]
> 2.0.9 and still exists.
> I solved using `const field = this.panel.fields[0]`

Could you elaborate on where you put this please, and whether you did this in conjunction with the other changed mentioned above or just by itself? The other above suggestions haven't helped me.

I have the same issue on the latest version of Nova. It's simply rendering:

```<div class="vue-portal-target   "><!----><!----><!----></div>```

or a "Card" div containing:

```<!--function(e,n,o,r){return Fe(t,e,n,o,r,!0)}-->```

depending on whether or not I include the jsonSerialize above.

**Comment by alberto-bottarini** [comment]
You have to put everywhere you need to access `field` object. 
You can use as a computed in Vue or in a method: there is not a specific place.

Here's an example:

    export default {
        props: ['resourceName', 'resourceId', 'panel'],

        mounted() {
            console.log(this.panel.fields[0]);
        },

**Comment by Krato** [comment]
Yes. Still happening with v2.4.0
