### ISSUE TITLE
Introduce Tabs

### ISSUE THREAD

**Issue by johannitsa** [laravel/nova-issues#14]
Hey,

Nova is a great product!

I was thinking that we can do something better to group fields.

```php
public function fields(Request $request)
{
    return [
        ID::make()->sortable(),

        new Panel('Information', [
               new Tab('Personal Information', $this->personalFields(),
               new Tab('Progress', $this->progressFields())
        ]),
    ];
}
```

We can use the same idea to group/navigate through relationships.

I believe that this may improve the UX.

Regards!

**Comment by dwyer14** [comment]
+1 for this. Especially valuable for models that have many relationships defined, as those detail pages can get lengthy. Personally, I'd like to see tabs at the page level instead of (or in addition to) panel tabs. Any fields outside a `Tab` could fall on the initial/default tab (eg, ID and name).

```
public function fields(Request $request)
{
    return [
        ID::make()->sortable(),
        Text::make('Name')->sortable(),

        new Tab('Academics', [
               new Panel('Degrees', $this->degreeFields(),
               new Panel('Courses', $this->courseFields()),
               new Panel('Terms', $this->termFields())
        ]),
    ];
}
```

**Comment by anderly** [comment]
+1 as well for tabs. Sometimes, there are multiple levels nested resources and you just need to be able to quickly drill into the related resources via a link vs displaying them on the parent. This should be great to have as any option on the HasMany, etc.-type relationship fields. Similarly, it would be great to be able to define a right-sidebar/panel where certains Actions, Report links, or Even cards could live. 

Love Nova so far and can't wait to see where it goes from here!

**Comment by disitec** [comment]
+1 to this. When you have a bunch of relations in a model easily becomes infinite.

**Comment by shabbirbharmal** [comment]
We just published a basic tab package in case anyone's interested:

https://novapackages.com/packages/arsenaltech/nova-tab

**Comment by vootrunner** [comment]
FYI - When using nova-tabs as a replacement for panels it breaks the HasMany field, causing it to return every row in the database instead of the related rows. Reverting back to the Nova supplied field panel restores the expected behavior. I've created an issue for on the nova-tabs repo.

**Comment by sasafister** [comment]
Also, updating date's is not working.

**Comment by manojhl** [comment]
I would like to add another case for Tabs. Tabs can also be used for listing rows with predefined filters. Something similar to the screenshot below.

![Stripes' billing invoices section](https://user-images.githubusercontent.com/4166764/48823669-a7c22600-ed9c-11e8-92ee-49f101c12dba.png)

I was thinking of using a method to create tabs with predefined filter view

```php
/**
     * Get the tabs available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function tabs(Request $request)
    {
        return [];
    }
```

**Comment by dkulyk** [comment]
@johannitsa In https://github.com/dkulyk/nova-tabs you can use Tabs like @dwyer14 says.
```
public function fields(Request $request)
{
    return [
        ID::make()->sortable(),

        new Tabs('Information', [
               new Panel('Personal Information', $this->personalFields(),
               new Panel('Progress', $this->progressFields()),
               BelongsToMany::make('Relations'),
        ]),
    ];
}```

**Comment by dwyer14** [comment]
@dkulyk Yo, that is slick as h*ck. Nice work! Would love to see something like that in the core.

**Comment by niladam** [comment]
I think this should get some attention, right @davidhemphill ?:)

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by dkulyk** [comment]
Packages providing tabs for Nova:
https://github.com/eminiarts/nova-tabs
https://github.com/dkulyk/nova-tabs
https://novapackages.com/packages/arsenaltech/nova-tab

**Comment by robclancy** [comment]
I have reached so many dead ends because "this repository is focused on bugs". And this specific one is also saying to post feature requests as well?

**Comment by davidhemphill** [comment]
> I have reached so many dead ends because "this repository is focused on bugs". And this specific one is also saying to post feature requests as well?

Most of the ones from the last year or so have the same message above. 😄
