### ISSUE TITLE
Gravatar not working for e-mailadress with capitals

### ISSUE THREAD

**Issue by Dries-Vandenneucker** [laravel/nova-issues#140]
When adding an e-mail to gravatar.com with capital letters (for example: "Firstname.Lastname@example.com") it is converted to "firstname.lastname@example.com". Gravatar converts every e-mail to lowercase.

In Nova the e-mail "Firstname.Lastname@example.com" is not recognised as a correct gravatar. 
Gravatars api's should be called with the e-mail converted to lowercase to fix this.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in an upcoming release.
