### ISSUE TITLE
Collapsable Sidebar

### ISSUE THREAD

**Issue by stezani** [laravel/nova-issues#1400]
Hi all! Is very difficult to integrate in nova main package the left sidebar collapsable with a button to show/hide bar like in admin lte? Thank you

**Comment by davidhemphill** [comment]
Sorry, but there's no plans to do this.

**Comment by dillingham** [comment]
I hate when decent ideas get shut down
Like literally every admin panel does that 
It’s like “no” is enjoyable to say for David lol

**Comment by cord** [comment]
the package [Laravel Nova Responsive Theme](https://novapackages.com/packages/gregoriohc/laravel-nova-theme-responsive) supports this with hitting the ECS button
