### ISSUE TITLE
Laravel NOVA without a primary key makes an error

### ISSUE THREAD

**Issue by davidgabbay** [laravel/nova-issues#1401]
- Laravel Version: 5.7.27
- Nova Version: 1.3.2
- PHP Version: 7.2.9
- Operating System and Version: windows10
- Browser type and version: all

### Description:

I have a database that I can't change. When one of the tables has no primary key. this is the module of the table:

`<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
class t_hendtl extends Model
{
    //
    //protected $primaryKey = 'hen_num';

    protected $table = 't_hendtl';

    public $timestamps = false;  

    public $incrementing = false;

    protected $primaryKey = null;

}
On the nova side I just dont use the ID field. It looks like that:
public function fields(Request $request)

 {
        return [
            //ID::make()->sortable(),
            Text::make('Inv number', 'hen_num'),
            Text::make('Inv type', 'hen_type'),
        ];
    }

`

However I get this error:
 
`SQLSTATE[42000]:[Microsoft][ODBC Driver 13 for SQL Server][SQL Server] An object or column name is missing or empty. For SELECT INTO statements, verify each column has a name. For other statements, look for empty alias names. Aliases defined as "" or [] are not alowed. Chane the alias to a valid name. (SQL:select top 26*from[t_hendtl]order by [t_hendtl].[] desc).
 `
 what do you recommend to do ?
 notice that the field hen_num cant be primary key since there are multiple rows with the same number

**Comment by kirya-dev** [comment]
Hmm, How you think nova determine what resource need handle?
For this exists primary key. Its simple logic (:

**Comment by kirya-dev** [comment]
You can use ? 
`protected $primaryKey = 'hen_num';`

**Comment by davidhemphill** [comment]
Nova requires some sort of unique ID key to route resources. It doesn't necessarily need to be auto-incrementing (as you can handle that yourself on your end), but there has to be an ID available in the JSON payload for Nova to do its thing.

**Comment by braceyourself** [comment]
Actually, Nova is flexible enough to allow for querying tables that don't have a primary key. This is hackish, but it works for me. It's my workaround for working with tables that use composite keys.

1. set the ID, but use a callback to compute the value manually and add a query parameter to the output:
``` 
ID::make('some_field', function () {
    return $this->some_field.'?another_field='.$this->another_field;
})->hideFromDetail()->hideWhenCreating()->hideWhenUpdating()
```

2. then, modify the query in the detailQuery method of the resource:
```
    public static function detailQuery(NovaRequest $request, $query)
    {
        return parent::detailQuery($request, $query->where([
            ['another_field', $request->query('another_field')],
        ]));
    }
```

**Comment by vodnicearv** [comment]
@davidhemphill the problem has not been solved

maybe you should reopen the issue?

**Comment by davidhemphill** [comment]
Nova still needs a unique identifier for the purpose of routing resources. This hasn't changed. It doesn't have to be auto-incrementing, but it does have to be unique.
