### ISSUE TITLE
lens action not visible

### ISSUE THREAD

**Issue by Naoray** [laravel/nova-issues#1402]
- Laravel Version: 5.7.28
- Nova Version: 1.3.2
- PHP Version: 7.2.15
- Operating System and Version: Ubuntu 18.10
- Browser type and version: Chrome v72.0.3626.119

### Description:
I have a `Student` Resource with actions and created a `StudentWallet` lens with own actions. When I go to the lens I only see the actions of the `Student` Resource appearing. I can't find the `lens/student-wallets/actions` url in the browser's network tab either, only the resource's `students/actions` link.

![image](https://user-images.githubusercontent.com/10154100/53625808-609dc980-3c04-11e9-93a9-7aab9306de13.png)

```php
// App\Nova\Student.php
    public function lenses(Request $request)
    {
        return [
            new Lenses\StudentWallets,
        ];
    }

    public function actions(Request $request)
    {
        return [
            (new DownloadExcel)->withHeadings(),
        ];
    }

// App\Nova\Lenses\StudentWallets.php
public function actions(Request $request)
    {
        return [
            new SendPaymentReminder,
        ];
    }
```

### Steps To Reproduce:
- Create a `resource` and register some actions
- Create a `lens` and register it within the prior created `resource`
- Register a different `action` on the lens
- go to the lens view & select a record
=> only actions from the resource will appear

**Comment by davidhemphill** [comment]
This feature was added in a later version of Nova I believe. Maker sure you're on the latest.
