### ISSUE TITLE
Multiple selects

### ISSUE THREAD

**Issue by mikkelbfriis** [laravel/nova-issues#1403]
I reckon a feature missing would be arrayable selects, so that we can have that functionality with Nova.

```
<select multiple name="countries[]">
<option value="Afghanistan" selected>Afghanistan</option>
<option value="USA" selected>USA</option>
<option value="Canada">Canada</option>
</select>
```

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
