### ISSUE TITLE
Error when field only have one rule which is a Closure

### ISSUE THREAD

**Issue by Bherivy** [laravel/nova-issues#1404]
- Laravel Version: `5.8.2`
- Nova Version: `2.0`
- PHP Version: `7.3`
- Operating System and Version: `Arch Linux 4.20.12-arch1-1`
- Browser type and version: `Firefox 65.0.1`

### Description:

In the Nova document it says that we can use Closure in the `Element::rules()` method with following example:

```php
<?php

Text::make('State')
    ->sortable()
    ->rules('required', function($attribute, $value, $fail) {
        if (strtoupper($value) !== $value) {
            return $fail('The '.$attribute.' field must be uppercase.');
        }
    })
```

When I tried with following code:

```php
<?php

Text::make('Cellphone')
    ->rules(function ($attr, $value, $fail) {
        if (empty($value)) return;

        if (!is_numeric($value)) {
            $fail(__('validation.numeric', ['attribute' => $attr]));
        }
    }),
```

Then I have got a error said that this closure only accept one parameter but except 3.

### Steps To Reproduce:

1. Create a resource
2. Defined a field with a single rule, which is a closure that except 3 parameters. (which is as same as [discovered in Laravel/Framework doc](https://laravel.com/docs/5.8/validation#using-closures))

**Comment by dkulyk** [comment]
```php
->rules([function (...) {...}])
```

**Comment by Bherivy** [comment]
@dkulyk thanks for replying

I have did that for a workaround. But I think this should be covered in document if it is designed to works like that.

I known that in this case Nova when we call `getRules`, nova will try to trigger that closure with one parameter (which is NovaRequest), and use the result as the actual rules. It looks like this is a feature that have not been documented.

**Comment by dkulyk** [comment]
If your first attribute is Closure then it is expected to define rules like this:
```
->rules(function ($request) {
    return ['required'];
})```

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).
