### ISSUE TITLE
JavaScript error when creating resource instance with null polymorphic relationship

### ISSUE THREAD

**Issue by duncmc** [laravel/nova-issues#1406]
- Laravel Version: 5.8.0
- Nova Version: 2.0
- PHP Version: 7.2.10
- Operating System and Version: MacOS 10.14.3
- Browser type and version: Chrome 72.0.3626.119

### Description:

Displaying a create form for a resource with a null `MorphTo` relationship throws the following JavaScript error:

    `TypeError: Cannot read property 'singularLabel' of undefined`.

The error is thrown when when the create form is accessed via the resource’s `BelongsTo` relationship.

### Steps To Reproduce:

My web application includes the following resources:

* Member
* Claim
* Order
* Award

Application’s users can grant Awards to Members, and the Award may or may not be associated with either a Claim or an Order. In summary the relationships are as follows.

#### Member

Member has a one to many relationship with Award.

On the Member model this is defined like so.

    class Member extends Model
    {
        public function awards()
        {
            return $this->hasMany('App\Models\Award');
        }
    }

On Nova’s Member resource this is defined like so.

    class Member extends Resource
    {
        public static $model = 'App\Models\Member';
        
        public function fields(Request $request)
        {
            return [
                ID::make()->sortable(),
                
                // A bunch of other fields are defined here
                
                HasMany::make('Awards'),
            ];
        }
    }

#### Claim

Claim has a one to many polymorphic relationship with Award.

On the Claim model this is defined like so.

    class Claim extends Model
    {
        public function awards()
        {
            return $this->morphMany('App\Models\Award', 'awardable');
        }
    }

On Nova’s Claim resource this is defined like so.

    class Claim extends Resource
    {
        public static $model = 'App\Models\Claim';
        
        public function fields(Request $request)
        {
            return [
                ID::make()->sortable(),
                
                // A bunch of other fields are defined here
                
                MorphMany::make('Awards'),
            ];
        }
        
    }

#### Order

Order has a one to many polymorphic relationship with Award.

On the Order model this is defined like so.

    class Order extends Model
    {
        public function awards()
        {
            return $this->morphMany('App\Models\Award', 'awardable');
        }
    }

On Nova’s Order resource this is defined like so.

    class Order extends Resource
    {
        public static $model = 'App\Models\Order';
        
        public function fields(Request $request)
        {
            return [
                ID::make()->sortable(),
                
                // A bunch of other fields are defined here
                
                MorphMany::make('Awards'),
            ];
        }
        
    }

#### Award

Award has a conventional inverse one to many relationship with Member. Award also has an inverse one to many polymorphic relationship with Claim and Order.

The Award model looks like this.

    class Award extends Model
    {
        public function member()
        {
            return $this->belongsTo('App\Models\Member');
        }
        
        public function awardable()
        {
            return $this->morphTo();
        }
    }

Nova’s Award resource looks like this.

    class Award extends Resource
    {
        public static $model = 'App\Models\Award';
        
        public function fields(Request $request)
        {
            return [
                ID::make()->sortable(),
                
                // A bunch of other fields are defined here
                
                BelongsTo::make('Member'),
            
                MorphTo::make('Awardable')->types([
                        Claim::class,
                        Order::class,
                    ])
                    ->nullable(),
            ];
        }
    }

Sometimes a Member can be granted an Award without there being a related Claim or Order, so the MorphTo relationship is optional.

To that end the corresponding `awardable_id` and `awardable_type` fields in the `awards` table can accept a null value and the Award’s MorphTo field is declared as nullable.

#### Create an Award via the Award index page

Browsing to the Award resource index page in Nova shows a list of Awards with a `Create Award` button. Clicking `Create Award` displays a form to create a new Award.

* The Member field appears as an HTML `select` element comprising a list of Members.
* The Awardable field appears as an HTML `select` element comprising Claim and Order options.
* The Awardable Type field appears as an empty disabled HTML `select` element until the Awardable selection is made.

From here it is possible to create a new Award, with or without either a Claim or Order selected. This behaviour is entirely as expected and it is possible to create an Award that is associated with a Member but has no relationship with either a Claim or an Order.

All good :)

#### Create an Award via the Member detail page

Browsing to a Member detail page shows the Member’s properties beneath which is a list of their Awards. This Award index view includes a `Create Award` button. Clicking `Create Award` displays a form to create a new Award.

* The Member field appears as an HTML `select` element. The related Member is preselected and the field is disabled.
* The Awardable field appears as an empyty HTML `select` element. The field is disabled.
* The Awardable Type field appears as an empty HTML `select` element. The field is disabled.

Inspecting the DOM reveals that the Awardable `select` element contains the Claim and Order options.

However on page load the console shows the following JavaScript error.

    TypeError: Cannot read property 'singularLabel' of undefined

Attempting to continue by clicking `Create Award` has no effect. The console displays a further error.

    POST http://app-url/nova-api/awards 422 (Unprocessable Entity)

**Comment by jbrooksuk** [comment]
This issue relates to an older version of Nova. It's possible that this bug has been fixed in recent versions. If you're still experiencing this in the latest version of Nova, please re-open this ticket, thanks!

**Comment by dannylepage** [comment]
I'm experiencing the same issue on Nova 2.3.1. My steps to reproduce are identical to @duncmc.  @duncmc, did you find a workaround or did a later version of Nova resolve your problem in this instance?

**Comment by duncmc** [comment]
@dannylepage The site in question is still running v2.0.0. I didn’t find a workaround. Given that there was a different way for the end user to come at the data and achieve the desired result, I ended up not including the approach that was throwing the error.

**Comment by duncmc** [comment]
I’ll be working on the site over the next week or so so I’ll update Nova. Id the problem persists I will reopen the issue.

**Comment by dannylepage** [comment]
Thanks @duncmc. @jbrooksuk, just flagging this as replicable on 2.3.1, cheers.
