### ISSUE TITLE
auto populate the relationship field

### ISSUE THREAD

**Issue by aungyee** [laravel/nova-issues#1407]
Hey guys, is there any way to auto populate the relationship field like this?
I have a relationship field in my `ProductSku` resource file defined as `HasMany::make('Product Image', 'image','App\Nova\ProductImage)`, when i create a ProductImage from ProductSku detail page, the productsku field is populated automatically, is there any way to auto populate another relationship field - `Product` , since `ProductSku belongsTo Product`?

**Comment by kirya-dev** [comment]
see here https://github.com/kirya-dev/nova-polymorphic-field

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).
