### ISSUE TITLE
Issue with page load and js files

### ISSUE THREAD

**Issue by keyur5390** [laravel/nova-issues#1409]
- Laravel Version: 5.7.17
- Nova Version: 1.1.3
- PHP Version: 7.1.23

### Description:
Nova admin is getting too much load time. Once login to nova admin vendor.js and app.js file get more than 2 minute to load and that's the reason my dashboard page is getting approximately 2-3 minutes to be loaded properly. Once these files are loaded then other manager is loaded within 10-15 seconds. And again Nova resources is taking 5-6 minutes to be load. 

### Steps To Reproduce:
1. Login to Nova Admin
2. Check for the network to inspect the loaded files 
3. Got vendor.js and app.js which is taking more than 1 minute to load.
4. Check to any other modules, resources are taking 5-6 seconds to load and that looks like panel performance is poor.

**Comment by davidhemphill** [comment]
You've got a configuration issue, or there is something else going on. Without more information on your project or an actual reproducible example, there's no way to confirm it.
