### ISSUE TITLE
php artisan nova:card --private

### ISSUE THREAD

**Issue by lichtner** [laravel/nova-issues#1411]
Hello guys, 
sometimes I know I want to create a private card which will be never ever published. I don't need composer.json, package.json node_modules with 1500 packages. I want to create a simple card in `app/Nova/Cards` like Filters or Metrics. I tried to do it, but I was not successful. Will be awesome if nova supports it out of the box via artisan command.

**Comment by davidhemphill** [comment]
You can already do this. Simple move the components to your own project and wire them up manually.

**Comment by lichtner** [comment]
how?
