### ISSUE TITLE
BelongsTo similar to Select2 (autocomplete, minimum search character)

### ISSUE THREAD

**Issue by aronquiray** [laravel/nova-issues#1412]
Hi everyone! 
It would be nice if the belongsTo option will have like a default selection box with like minimum characters to search on (if none) or auto select it if there is a relationship. 
As I've tested out with 2k users. it loads quite slow (a delay)

**Comment by FrittenKeeZ** [comment]
What's wrong with `BelongsTo('User')->searchable()`?
https://nova.laravel.com/docs/1.0/resources/relationships.html#searchable-relations

**Comment by aronquiray** [comment]
omg stupid me. didn't noticed that. sorry.

**Comment by yehudahkay** [comment]
It would still be nice to have a searchable similar to select2
