### ISSUE TITLE
It's not possible to specify viewAny permission for ActionEvent log

### ISSUE THREAD

**Issue by FrittenKeeZ** [laravel/nova-issues#1413]
- Laravel Version: 5.6.39
- Nova Version: 1.3.2
- PHP Version: 7.2.8
- Operating System and Version: Alpine Linux 3.8
- Browser type and version: Chrome 72

### Description:
Adding `Laravel\Nova\Actions\Actionable` to a model adds the action event log as expected, but if you only want the log to show for certain users, like super admins, this is not possible.
If you add a custom policy (like the one provided just below) for `Laravel\Nova\Actions\ActionEvent`, you end up with a 403 permission error.

```php
<?php

namespace App\Policies\Nova;

use App\Models\User;
use Illuminate\Auth\Access\HandlesAuthorization;

class ActionEventPolicy
{
    use HandlesAuthorization;

    /**
     * Determine whether the user can view any action events.
     *
     * @param  \App\Models\User  $user
     * @return bool
     */
    public function viewAny(User $user)
    {
        return $user->isSuperAdmin();
    }
}
```

### Steps To Reproduce:
1. Add `Actionable` trait to a model.
2. Add a custom policy for `ActionEvent` model, limiting certain users `viewAny` permission.
3. Access detail view for actionable model and receive 403 permission error.

### Temporary fix.
In your `App\Nova\Resource` override the `Laravel\Nova\ResolvesFields::detailFields()` method:
```php
/**
 * Resolve the detail fields.
 *
 * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
 * @return \Illuminate\Support\Collection
 */
public function detailFields(NovaRequest $request)
{
    return $this->resolveFields($request)->reject(function ($field) use ($request) {
        return ! $field->showOnDetail || ! $field->authorize($request);
    })->when(in_array(Actionable::class, class_uses_recursive(static::newModel()))
        && ActionResource::authorizedToViewAny($request), function ($fields) {
        return $fields->push(MorphMany::make(__('Actions'), 'actions', ActionResource::class));
    })->each(function ($field) use ($request) {
        if ($field instanceof Resolvable && ! $field->pivot) {
            $field->resolveForDisplay($this->resource);
        }
        if ($field instanceof Resolvable && $field->pivot) {
            $accessor = $this->pivotAccessorFor($request, $request->viaResource);

            $field->resolveForDisplay($this->{$accessor} ?? new Pivot);
        }
    });
}
```
The key is to add the `ActionResource::authorizedToViewAny($request)` check.

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by 4n70w4** [comment]
The same problem! @FrittenKeeZ were you able to solve the problem?

**Comment by FrittenKeeZ** [comment]
@4n70w4 yes, use the override described above.

**Comment by 4n70w4** [comment]
@FrittenKeeZ okay! For 1.3.2 patch like this:

```patch
Index: src/ResolvesFields.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/ResolvesFields.php	(date 1565704623094)
+++ src/ResolvesFields.php	(date 1565704623094)
@@ -55,7 +55,7 @@
     {
         return $this->resolveFields($request)->reject(function ($field) use ($request) {
             return ! $field->showOnDetail || ! $field->authorize($request);
-        })->when(in_array(Actionable::class, class_uses_recursive(static::newModel())), function ($fields) {
+        })->when(in_array(Actionable::class, class_uses_recursive(static::newModel())) && ActionResource::authorizedToViewAny($request), function ($fields) {
             return $fields->push(MorphMany::make(__('Actions'), 'actions', ActionResource::class));
         })->each(function ($field) use ($request) {
             if ($field instanceof Resolvable && ! $field->pivot) {
```


For 2.0.7 like this:

```patch
Index: vendor/laravel/nova/src/ResolvesFields.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- vendor/laravel/nova/src/ResolvesFields.php	(date 1565704728616)
+++ vendor/laravel/nova/src/ResolvesFields.php	(date 1565704728616)
@@ -56,7 +56,7 @@
     {
         return $this->resolveFields($request, function (Collection $fields) {
             return $fields->filter->showOnDetail;
-        })->when(in_array(Actionable::class, class_uses_recursive(static::newModel())), function ($fields) {
+        })->when(in_array(Actionable::class, class_uses_recursive(static::newModel())) && ActionResource::authorizedToViewAny($request), function ($fields) {
             return $fields->push(MorphMany::make(__('Actions'), 'actions', ActionResource::class));
         })->each(function ($field) use ($request) {
             if ($field instanceof ListableField || ! $field instanceof Resolvable) {
```

But this is still a bad solution - edit trait in vendor.....

**Comment by FrittenKeeZ** [comment]
@4n70w4 no, make the method override in your `App\Nova\Resource`. Just copy/paste the content of `Laravel\Nova\ResolvesFields::detailFields()` to your base resource class and make the changes.

**Comment by 4n70w4** [comment]
@FrittenKeeZ thanks. But if need override then it is better to do without copy-paste. Something like this. Will work for both version 1.3.2 and 2.0.7

```
    /**
     * Resolve the detail fields.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @return \Illuminate\Support\Collection
     */
    public function detailFields(NovaRequest $request) {
        $fields =  parent::detailFields($request)->filter(function (Field $value, $key) use($request) {
            return $value->attribute !== 'actions' || ActionResource::authorizedToViewAny($request);
        });

        return $fields;
    }
```

**Comment by dgoldstein89** [comment]
@4n70w4 your solution won't work if you have any Resource Tools

**Comment by oheck** [comment]
Adding another Policy and registering it in AuthServiceProvider for ActionEvent::class works for me.

**Comment by vayurobins** [comment]
> Adding another Policy and registering it in AuthServiceProvider for ActionEvent::class works for me.

Is that not the same as what @FrittenKeeZ did, which did not work and returned an 403? What is the difference between what FrittenKeeZ did and what you are suggesting?

**Comment by vayurobins** [comment]
The solutions above did not work for me, so I did this, but am not exited about having to copy and overwrite Nova functions.
```
public function detailFields(NovaRequest $request)
    {
        return $this->resolveFields($request, function (FieldCollection $fields) use ($request) {
            return $fields->filter->isShownOnDetail($request, $this->resource);
        })->when(in_array(Actionable::class, class_uses_recursive(static::newModel())), function ($fields) {
            if (request()->user()->isAdmin()) {
                return $fields->push(MorphMany::make(__('Actions'), 'actions', config('nova.actions.resource')));
            }
            return $fields;
        })->each(function ($field) use ($request) {
            if ($field instanceof ListableField || ! $field instanceof Resolvable) {
                return;
            }

            if ($field->pivot) {
                $accessor = $this->pivotAccessorFor($request, $request->viaResource);

                $field->resolveForDisplay($this->{$accessor} ?? new Pivot);
            } else {
                $field->resolveForDisplay($this->resource);
            }
        });
    }
```
So what I added is this:
```
if (request()->user()->isAdmin()) {
   return $fields->push(MorphMany::make(__('Actions'), 'actions', config('nova.actions.resource')));
}
return $fields;
```

**Comment by barreirinha** [comment]
It was fixed in V2.9.0 Released December 10, 2019, but after that I took a time to get what was wrong in my code... ActionEventPolicy was not working. So, here it goes, somebody may have same trouble.

Laravel 7 auto registers all Policies located in **App/Policies**  folder. But it is only for models with the **namespace App;**. In other words, if you have a model named **FooBar** in the folder **App** (or _App/Models_) all you have to do is to create a class named **FooBarPolicy** in the folder **App/Policies**. There is no need do _register_ it.

It does not happens to **ActionEvent** Model, because it is located in other folder ( _Laravel\Nova\Actions_ ). 

So, to use the ActionEventPolicy, it must be manually registered in the **AuthServiceProvider**.

Like this:

```php
<?php

namespace App\Providers;

use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Gate;

class AuthServiceProvider extends ServiceProvider
{
  
    protected $policies = [
         'Laravel\Nova\Actions\ActionEvent' => 'App\Policies\ActionEventPolicy',
    ];

...

```

**Comment by pokono** [comment]
@barreirinha This is the way to go!! Works amazingly, especially in situations where you want the Action Log to show only for super admins. Thank you!

**Comment by otrsw** [comment]
I know this issue is closed - but it feels wrong that the "default" behaviour on Nova is to essentially allow anyone with the "/resources/action-events"  URL access to the full details in the audit trail.  My understanding is that without applying the policy (as suggested by @barreirinha) any Nova project essentially has a bit of an open "back door" with full access to sensitive data?
