### ISSUE TITLE
Add new button " Return to detail" or "Return to list"

### ISSUE THREAD

**Issue by cwplus** [laravel/nova-issues#1414]
Is there anyone, who has an idea, to add a button "back to ..." in "detail"  or "Attach" view, without modifying them directly in "nova"

Or for example, another way to override views that are in the folder /vendor/laravel/nova/resources/views/*

<img width="1759" alt="return to" src="https://user-images.githubusercontent.com/5727109/53898566-9bef2c80-4038-11e9-947a-af6f9a068405.png">
<img width="1759" alt="return to 2" src="https://user-images.githubusercontent.com/5727109/53898568-9bef2c80-4038-11e9-8af2-86cc9534b0be.png">

 A big thanks for you

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
