### ISSUE TITLE
Is "Impression" a reserved keyword for Resources?

### ISSUE THREAD

**Issue by crash13override** [laravel/nova-issues#1415]
I have a model called "Impression" but when I try to add it to the Nova Resources I get this error in the console and it doesn't even try to load the data.

> Unhandled promise rejection TypeError: "e.response is undefined"

After trying to debug it in all kind of ways, I tried to just copy the file and rename it to "Test". To my surprise it worked just fine!

Do you have any idea why the work "Impression" might be causing this issue?

Thanks

Luca

![screenshot 2019-03-07 at 02 00 04](https://user-images.githubusercontent.com/1100260/53924564-cd89e700-407c-11e9-9b7c-38602f5f312e.png)

**Comment by davidhemphill** [comment]
I'm not able to replicate this on a new Nova instance. Feel free to post more details of your app's setup which might be causing this. Can you try on a new Nova instance yourself?
