### ISSUE TITLE
ResourceTools and Cards on forms

### ISSUE THREAD

**Issue by m-lotze** [laravel/nova-issues#1416]
Please make cards and resource tools possible on forms. Some tools make more sense on the edit screen than the detail screen. E.g. showing the last changes of an resource or a card with some instructions for editing a resource.

related: #1157

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by artisaninweb** [comment]
I really need this feature to add cards on the create/edit pages.

**Comment by monaye** [comment]
For the resources tool, you can override the `removeNonUpdateFields` in your resources class. 

following is the original function Nova shipped with: 
```
    protected function removeNonUpdateFields(NovaRequest $request, FieldCollection $fields)
    {
        return $fields->reject(function ($field) use ($request) {
            return $field instanceof ListableField ||
                   $field instanceof ResourceToolElement ||
                   $field->attribute === 'ComputedField' ||
                   ($field instanceof ID && $field->attribute === $this->resource->getKeyName()) ||
                   ! $field->isShownOnUpdate($request, $this->resource);
        });
    }
  ```
  and you can overwrite it to allow `ResourceToolElement`,  something like this:   
  ```
  protected function removeNonUpdateFields(NovaRequest $request, FieldCollection $fields)
    {

        return $fields->reject(function ($field) use ($request) {
            return $field instanceof ListableField ||
                (isset($field->attribute) && $field->attribute === 'ComputedField') ||
                ($field instanceof ID && $field->attribute === $this->resource->getKeyName()) ||
                (!$field instanceof ResourceToolElement && !$field->isShownOnUpdate($request, $this->resource));
        });
    }
 ```
 
 but `ResourceTool` extends `ResourceToolElement` and is construct with following 
 ```
 namespace Laravel\Nova;

use Laravel\Nova\Fields\FieldElement;

class ResourceToolElement extends FieldElement
{
    /**
     * Create a new resource tool.
     *
     * @param  string  $component
     * @return void
     */
    public function __construct($component)
    {
        parent::__construct($component);

        $this->onlyOnDetail();
    }
}
``` 

so, you also need to create your own class (I wasn't sure best way to overwrite it) and change it to `onlyOnForms` or whatever your needs. 

Once those are done, Nova tries to register the Vue component correspond to your page for example, if you are on `create` or `update`, you will need to register the Vue component as follow: 

```
import SimplePanel from './components/SimplePanel.vue'

Nova.booting((Vue, router, store) => {
  Vue.component('form-nova-simple-panel', SimplePanel)   // <= prefix with `form` for create and update
})
```
you might also need to handle or overwrite some of the core functions, but this will get you to show something on the form with your own `Card`.
