### ISSUE TITLE
Can't using properly a belongsTo field on mobile device (value not taken)

### ISSUE THREAD

**Issue by tghpow** [laravel/nova-issues#1417]
- Laravel Version: 5.7
- Nova Version: 1.3
- PHP Version: 7.2.8
- Operating System and Version: Android
- Browser type and version: Test en chrome & firefox

### Description:
Hi, i have a little bug in mobile device with select searchable like a BelongsTo field.
When i touch (or click with the developer console) a value:
- The value is taken
- Just after, it's disappeared

But, if i remove the mobile keyboard before select a value and if i am in horizontal mode, it's ok.

I made a little gif to show (using "remote device" on chrome inspector)

![bugmobilepwanova](https://user-images.githubusercontent.com/6094280/53960247-0dd17f80-40e6-11e9-97e8-b118397076b6.gif)

### Steps To Reproduce:
- Connect to nova with a phone
- Pick a value in a belongsTo field

--

Any ideas how to fix this ?

Thanks all for your help

**Comment by hs00** [comment]
I have a same problem.

**Comment by davidhemphill** [comment]
You're using Nova with a 3rd-party theme. Remove the theme and post here if your issue resolves itself.

**Comment by tghpow** [comment]
Hi,

I removed the theme and i use the \Laravel\Nova\Fields\BelongsTo fields. Same problem here unfortunately

![novabugmobile](https://user-images.githubusercontent.com/6094280/54141476-0ed81900-4426-11e9-8fd3-f32d56ea2149.gif)
