### ISSUE TITLE
Unhandled Promise Rejection (Safari)

### ISSUE THREAD

**Issue by S-anasol** [laravel/nova-issues#1419]
- Nova Version: 1.3.2
- Operating System and Version: MacOS Mojave
- Browser type and version: Safari 12.0.3

https://github.com/laravel/nova-issues/issues/378
Same error again.

Form with Image/Avatar field - throws exception.
Without Image/Avatar field - no errors.

**Comment by davidhemphill** [comment]
This is not enough information to reproduce. Simply reposting a closed (and fixed) issue is not a bug report.

**Comment by pvdptje** [comment]
Got the same issue...
