### ISSUE TITLE
Custom component inside forms and detail screens

### ISSUE THREAD

**Issue by lucasromanojf** [laravel/nova-issues#142]
I want to create, for example, a "Back" button for all detail and form screens. Is there a way to achieve this without creating a tool, since I want to use the default resource screens but only add a button instead of creating all screens again?

**Comment by Andy-Baker** [comment]
Custom buttons is something I've been missing as well.

There are some generic actions (not tied to any specific ids, but related to a model) that would go perfectly with a button on the model's page.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in an upcoming release.

**Comment by yatin13490** [comment]
Hey @davidhemphill,

I have the same requirement, I like to set the back button with the details and the form, is there any component, Is this fixed?

I installed the latest update 1.1.9,
