### ISSUE TITLE
Redundant `v-if` in FileField detail component

### ISSUE THREAD

**Issue by markwalet** [laravel/nova-issues#1420]
- Laravel Version: 5.8.*
- Nova Version: ~2.0
- PHP Version: 7.2.13

### Description:
The `v-if="field.downloadable"` directive in `resources/js/components/Detail/FileField.vue` on line 20 is redundant.
The parent paragraph tag already has a `v-if` check on the computed property `shouldShowToolbar`. This computed property's value is determined with the following expression: `this.field.downloadable && this.hasValue`.

This means that the child's `v-if` will never be false. 

```html
<p v-if="shouldShowToolbar" class="flex items-center text-sm mt-3">
    <a
        v-if="field.downloadable" <!-- This line can be removed -->
        :dusk="field.attribute + '-download-link'"
        <!-- ... -->
    >
        <!-- ... -->
    </a>
</p>
```

### Steps To Reproduce:
None

### Steps To Fix:
Remove line 20 in `FileField.vue`.

**Comment by davidhemphill** [comment]
Thanks for the heads-up.
