### ISSUE TITLE
number_format Partition metric doesnt sum result

### ISSUE THREAD

**Issue by Naphyrion** [laravel/nova-issues#1422]
I change the format to display result in partition metrics with number_format function, but the total result doesn't sum.
```
protected function formatAggregateResult($result, $groupBy)
    {
        $key = $result->{last(explode('.', $groupBy))};

        return [$key => number_format(round($result->aggregate, 0),0,',', '.')];
        
    }
 ```
![metric](https://user-images.githubusercontent.com/13350727/54050904-2feb0080-41bf-11e9-9a9c-8468a49c8991.png)

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).
