### ISSUE TITLE
Add viaResourceId to queryParams in Form/BelongsToFied.vue

### ISSUE THREAD

**Issue by cwplus** [laravel/nova-issues#1426]
Hello everyone, is it possible to add viaResourceId to queryParams in laravel/nova/resources/js/components/Form/BelongsToFied.vue , in the next version of nova ???

vendor/laravel/nova/resources/js/components/Form/BelongsToField.vue	

        /**
         * Get the query params for getting available resources
         */
        queryParams() {
            return {
                params: {
                    current: this.selectedResourceId,
                    first: this.initializingWithExistingResource,
                    search: this.search,
                    withTrashed: this.withTrashed,
                    viaResourceId: this.viaResourceId
                },
            }
        },

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by dkulyk** [comment]
@cwplus Why do you need `viaResourceId`?

`viaResourceId` is attribute when you create resource via relationship. It doesn't have matter without other `via*` attributes.

Maybe do you mean resourceId - current edited resource?

**Comment by cwplus** [comment]
@dkulyk thinks 👍
