### ISSUE TITLE
Resource index page is unresponsive

### ISSUE THREAD

**Issue by jangidgirish** [laravel/nova-issues#1427]
- Laravel Version: 5.7.28
- Nova Version: 1.3.2 
- PHP Version: 7.2.16
- Operating System and Version: Ubuntu 16.04 LTS
- Browser type and version: Chrome 70.0.3538.110 (Official Build) (64-bit)

### Description:
The resource page is unresponsive on 50 / 100 pagination, the page is also slightly stuck on 25 records, this is mostly looking like front-end Dom manipulation issue.
![image](https://user-images.githubusercontent.com/4018017/54073068-ee368480-42a8-11e9-95bb-1507fe97f987.png)

I have checked API response time, the search APi is responding ~1.2second, although, index page have only total 6 columns with 3 belongsTo and each col has only small text info
![image](https://user-images.githubusercontent.com/4018017/54073132-a401d300-42a9-11e9-9e43-7f383674efbf.png)
Can you please suggest, how we can fix browser performance issue

### Steps To Reproduce:
No certain

**Comment by davidhemphill** [comment]
Sorry, but we are unable to debug your issue without a reproducible code example. Once you provide that we can open this up again.
