### ISSUE TITLE
Partition metric concatenating the total value

### ISSUE THREAD

**Issue by rodrigo-spb** [laravel/nova-issues#1428]
- Laravel Version: 5.8
- Nova Version: 2.0

### Description:
It only occurs in linux hosting, in my local station (W10) it works perfectly

My local result:

![image](https://user-images.githubusercontent.com/47005186/54087948-25537700-4337-11e9-912c-59b55272850f.png)

Result in linux hosting:

![image](https://user-images.githubusercontent.com/47005186/54087954-38fedd80-4337-11e9-9783-ad4a2080d489.png)

My code:

![image](https://user-images.githubusercontent.com/47005186/54087960-4fa53480-4337-11e9-8d25-88ffa4e141c3.png)

**Comment by dkulyk** [comment]
Try to add typecasting to int/float for `premio_format` field.

**Comment by rodrigo-spb** [comment]
> Try to add typecasting to int/float for `premio_format` field.

Yes! Work it!

![image](https://user-images.githubusercontent.com/47005186/54125741-92711600-43e4-11e9-90d7-c7f6d5e503f5.png)

![image](https://user-images.githubusercontent.com/47005186/54125810-ca785900-43e4-11e9-9152-97a5fb02e987.png)

**Comment by henryavila** [comment]
This problem still happening.
 I could fix it with info provided, but this cast should be made by laravel nova itself.
