### ISSUE TITLE
Feature Request: Allow search on Lens view.

### ISSUE THREAD

**Issue by anderly** [laravel/nova-issues#1429]
I use an "All" Lens to show active and inactive records (active = false in DB) or active records and soft-deleted records. I use a Lens and not just a filter because I add the display of the active column or deleted_at date that I don't want to show on the default index view which only contains active/non-deleted records.

It would be nice if I could also search on a Lens view just like on a normal index view. Is this possible?

If not, this would be a great feature to bake-in!

**Comment by anderly** [comment]
Closing since it's a feature request. Just wanted to add it to the wishlist.

**Comment by skoyah** [comment]
@anderly You're welcome to share your ideas on this subject here: https://github.com/laravel/nova/pull/706
