### ISSUE TITLE
Error while running nova:card command

### ISSUE THREAD

**Issue by julianpoma** [laravel/nova-issues#143]
Nova 1.0.4

I'm trying to create a card, but I get the following error message

![image](https://user-images.githubusercontent.com/19490445/44592086-e93f3700-a795-11e8-9569-d8e020a7d774.png)

Windows 10, Node v10.7.0 and npm v6.1.0. 

Edit: The same is happening with other commands, like nova:field

Any help is appreciated

**Comment by jwjcmw** [comment]
This looks like the same thing as what I just entered for nova:tool #147 
I'm betting on it being a windows issue.

**Comment by GuidoHendriks** [comment]
Seems to work fine on Nova 1.0.5 on macOS.

**Comment by julianpoma** [comment]
Decided to comment that line on the CardCommand.php. Was able to install the cards npm dependencies, but then the command got stuck while compiling the assets.

**Comment by jwjcmw** [comment]
Compiling the assets also hung for me when I tried to do it manually on a tool directory where the npm install had completed but then thrown the undefined property error.

**Comment by julianpoma** [comment]
Yes I tried the same thing. I was going to setup laravel homestand, until I realised that I will still have to run this artisan commands from Windows.

Hopefully the devs can help us here.

**Comment by DonDiegoAA** [comment]
Same problem for me with nova:card, nova:field or nova:tool.
Win10, Laragon, Laravel 5.6, NPM version 3.10.10.

Very frustating, can't wait to try this ;-)

**Comment by julianpoma** [comment]
**Update:**

**Nova 1.0.7** fixed the problem with the command line. Now its working fine.

But, at least on my machine, it still needs a hack to work properly, as shown in #147 

So, the follow this steps:

1. Run the command
2. **Before** answering the prompt: `Would you like to install the field's NPM dependencies? (yes/no)`, head to `nova-components/your-package` and open the `webpack.mix.js` file and edit it like this:

```
let mix = require('laravel-mix')

mix.js('resources/js/field.js', __dirname + 'dist/js')
   .sass('resources/sass/field.scss', __dirname + 'dist/css')
    .webpackConfig({
        resolve: {
            symlinks: false
        }
    })

```
3. Keep installing and answering yes or no to the commands prompts at your will.

**Comment by davidhemphill** [comment]
Just pushed a fix for Windows when compiling assets. 🚀 This has been fixed and will be included in an upcoming release.
