### ISSUE TITLE
[Feature request] Time field

### ISSUE THREAD

**Issue by markwalet** [laravel/nova-issues#1430]
I am searching for a time field. I found one on https://novapackages.com/ but the 2.0 update broke the plugin.

I know we can wait until the package supports Nova 2.0. But I think that native support is always better.

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
