### ISSUE TITLE
Select field using groups are not displaying them using optgroup

### ISSUE THREAD

**Issue by robertvrabel** [laravel/nova-issues#1432]
- Laravel Version: 5.8.3
- Nova Version: 2.0.0
- PHP Version: 7.2
- Operating System and Version: Mojave 10.14.3
- Browser type and version: Chrome 72.0.3626.121

### Description:

Select field using groups does not create expected `optgroup` options.

### Steps To Reproduce:

https://nova.laravel.com/docs/2.0/resources/fields.html#field-types

The documentation says to use

```
Select::make('Size')->options([
    'MS' => ['label' => 'Small', 'group' => 'Men Sizes'],
    'MM' => ['label' => 'Medium', 'group' => 'Men Sizes'],
    'WS' => ['label' => 'Small', 'group' => 'Women Sizes'],
    'WM' => ['label' => 'Medium', 'group' => 'Women Sizes'],
])->displayUsingLabels()
```

When doing so, they are not truly grouped though. This is the result I get:

<img width="799" alt="Screen Shot 2019-03-11 at 9 18 37 AM" src="https://user-images.githubusercontent.com/634788/54126758-afa2e600-43de-11e9-90e8-0a956fec56ae.png">

Shouldn't this use optgroup? https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup

**Comment by dkulyk** [comment]
See [Updating Nova](https://nova.laravel.com/docs/2.0/installation.html#updating-nova) documentation

**Comment by robertvrabel** [comment]
That worked. Thank you!
