### ISSUE TITLE
Design Proposal: Group Items column

### ISSUE THREAD

**Issue by cord** [laravel/nova-issues#1433]
The current admin layout concept has limitations, as it does not support larger number of resources / tools.

By introducing a "group items" column as implemented in many products it would be possible to have a more user friendly admin interface (example taken from bagisto):

![Products 2019-03-11 16-02-33](https://user-images.githubusercontent.com/158588/54135062-69b74380-4419-11e9-9888-f0e9832d0e4b.png)

Groups:
- internal id `public static $group = 'catalog';`
- translatable name `$group_name= __('Catalog'); `
- icon `$group_icon = 'myIcon';`
- icon color `$group_icon_color = '#f00';`
- sort order `$group_sort_order='1';`
- support resources, tools and resource tools, mixable

Group Items:
- internal id `public static $group_item = 'products';`
- translatable name `$group_item_name= __('products');`
- icon `$group_item_icon = 'myIcon';`
- icon color `$group_item_icon_color = '#f00';`
- sort order `$group_item_sort_order='1';`

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
