### ISSUE TITLE
Pagination not working on Lenses when compiling app.js

### ISSUE THREAD

**Issue by eithed** [laravel/nova-issues#1434]
- Laravel Version: 5.8.2
- Nova Version: 2.0
- PHP Version: 7.2.13
- Operating System and Version: macOS Mojave 10.14.3
- Browser type and version: Chrome 72

### Description:

I was given a requirement to add an additional pagination value to already existing ones. Unfortunately, after recompiling the app.js using yarn the entire pagination stops working altogether and displays the links one (even though I've not explicitly specified it). This happens only on lens screen.

### Steps To Reproduce:

1. Go to [project]/vendor/laravel/nova
2. Run `cp webpack.mix.js.dist webpack.mix.js`
3. Run `yarn`
4. Run `yarn run dev` (doesn't matter if it's dev or prod for the end result)
5. Go to [project]/
6. Run `php artisan nova:publish`

**Comment by dkulyk** [comment]
This has been fixed and will be included in the next release.
