### ISSUE TITLE
Nova on a subdomain 

### ISSUE THREAD

**Issue by TomBrouwer** [laravel/nova-issues#1435]
Is it possible to run Laravel Nova on a subdomain? I readed about the domain var in de config file, but it isn't working:
'domain' => "subdomain.domain.test",

I get a Laravel 404.

mvg Tom

**Comment by anderly** [comment]
@TomBrouwer,

Yes, this is possible.

I'm using it with multi-tenant sub-domain routing using `'domain' => '{tenant}.domain.test,`.

And I have my nova root URL set to `'/'`.

What's the out put if you run `php artisan route:list`?

**Comment by salvisb** [comment]
Hi,
I'm keep getting this error: "Missing required parameters for [Route: nova.login] [URI: login]".

I've set `domain` parameter in `config/nova.php` to `{tenant}.my-domain.local` and added entry to `vhosts` file. I'm running Laravel using `php artisan serve`.

Any help would be appreciated.

**Comment by Brotzka** [comment]
Me too... diid you found a solution @salvisb ?

**Comment by antlusher** [comment]
I've got this.on.my list of things to do. Nice one guys. Saved me thinking time
