### ISSUE TITLE
Cannot "attach" a hasOne relationship.  Only "create"

### ISSUE THREAD

**Issue by cjf** [laravel/nova-issues#1436]
- Laravel Version: 5.8.3
- Nova Version: 2.0.0
- PHP Version: 7.3.1
- Operating System and Version: macOS 10.14.3
- Browser type and version: Chrome 72.0.3626.121 (Official Build) (64-bit)

### Description:

I have a model "A" that has a hasOne relationship with "B".  "B" has a belongsTo with "A".

Upon creating a new "A" object, one can view it and the submodule to view the attached "B" appears.  From there, one can create a new "B" and it will be attached to the current "A" object.  However, one cannot attach an existing "B" object.  The only option is to create a new "B" object.   

I believe this to be a bug as other relationship types support create and attach operations.

### Steps To Reproduce:

```
class A extends Model
{
    protected $table = 'a';

    public function b()
    {
        return $this->hasOne('App\B');
    }
}
```

```
class B extends Model
{
    protected $table = 'b';

    public function a()
    {
        return $this->belongsTo('App\A');
    }
}
```

in app\Nova\B.php
```
public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),            
            BelongsTo::make('A', 'a', 'App\Nova\A')->nullable()
        ];
    }
```

in app\Nova\A.php
```
public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
            HasOne::make('Book', 'b', 'App\Nova\B')->nullable()
        ];
    }
```

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by BobbyBorisov** [comment]
@davidhemphill hey, have you addressed this issue? ; ))))

**Comment by JJWesterkamp** [comment]
@davidhemphill Could you explain why this is not considered a bug? I have a nullable `BelongsTo` where it is convenient to set that relationship from the `HasOne` side in Nova.
