### ISSUE TITLE
Email and password fields autocompleted in chrome

### ISSUE THREAD

**Issue by yehudahkay** [laravel/nova-issues#1438]
- Laravel Version: 5.8
- Nova Version: 2.0
- PHP Version: 7.2
- Operating System and Version: windows 10
- Browser type and version: chrome 72

### Description:
Email and password fields are autocompleted for create new user, please see image

![image](https://user-images.githubusercontent.com/9964988/54198935-5d41f200-44d0-11e9-93bf-742d75657667.png)

**Comment by yehudahkay** [comment]
There are several solutions listed here:

https://stackoverflow.com/questions/15738259/disabling-chrome-autofill

Thank you!

**Comment by FrittenKeeZ** [comment]
Changing to `autocomplete="new-password"` for password fields does the trick.
Manually edited in the `app.js` Nova script:
```
{id:e.field.attribute,dusk:e.field.attribute,type:"password",placeholder:e.field.name,autocomplete:"new-password"}
```

**Comment by davidhemphill** [comment]
There doesn't seem to be a good solution that works for Nova at the moment with regards to the email autofilling. However, I've updated the Password field to use the new `autocomplete=new-password` syntax. This should work until Chrome decides to change it again.
