### ISSUE TITLE
Nova Action not saving File fields

### ISSUE THREAD

**Issue by oluomotoso** [laravel/nova-issues#1439]
- Laravel Version: 5.7
- Nova Version: 1.3
- PHP Version: 7.2
- Operating System and Version: Ubuntu
- Browser type and version: #.#

### Description:

I'm trying to upload a file through the Laravel nova action. I'm unable to save the file on the handle

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).

**Comment by dillingham** [comment]
@davidhemphill are files supported in actions?

**Comment by dillingham** [comment]
@oluomotoso 

```php
Image::make('Logo'),
```
```php
$fields->logo->store('uploads');
```

https://laravel.com/docs/5.8/filesystem#file-uploads

More info can be extracted  from `$_FILES`
