### ISSUE TITLE
Cannot associate belongsTo on existing entity.  Relatable::relationshipIsFull to blame.

### ISSUE THREAD

**Issue by cjf** [laravel/nova-issues#1440]
- Laravel Version: 5.8.3
- Nova Version: 2.0.0
- PHP Version: 7.3.1
- Operating System and Version: macOS 10.14.3
- Browser type and version: Chrome 72.0.3626.121 (Official Build) (64-bit)

### Description:
Below is the current problem and a potential solution.

I have a model "A" that has a hasOne relationship with "B".  "B" has a belongsTo with "A".

One may attach an existing "A" object at the time that a "B" object is created.  This works fine.  However, if no "A" object is attached at that time, editing said "B" object to attach an existing "A" throws an exception...

``` 
local.ERROR: Call to a member function getKey() on null {"userId":2,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getKey() on null at /Users/person/testproject/vendor/laravel/nova/src/Rules/Relatable.php:84)
```
The problem in line 84 is that `$modelBeingUpdated->{$attribute}` returns null in this case (since no "A" object is attached yet) and `null->getKey()` throws the exception.  The function in question is below...

```
protected function relationshipIsFull($model, $attribute, $value)
    {
        $inverseRelation = $this->request->newResource()
                    ->resolveInverseFieldsForAttribute($this->request, $attribute)->first(function ($field) {
                        return $field instanceof HasOne || $field instanceof MorphOne;
                    });

        if ($inverseRelation && $this->request->resourceId) {
            $modelBeingUpdated = $this->request->findModelOrFail();

            if ($modelBeingUpdated->{$attribute}->getKey() == $value) { // line #84
                return false;
            }
        }

        return $inverseRelation &&
               $model->{$inverseRelation->attribute}()->count() > 0;
    }
```

I propose a change as illustrated below.  It is just a simple check to see if the attribute is null before doing the comparison to `$value`.

```
protected function relationshipIsFull($model, $attribute, $value)
    {
        $inverseRelation = $this->request->newResource()
                    ->resolveInverseFieldsForAttribute($this->request, $attribute)->first(function ($field) {
                        return $field instanceof HasOne || $field instanceof MorphOne;
                    });

        if ($inverseRelation && $this->request->resourceId) {
            $modelBeingUpdated = $this->request->findModelOrFail();

            $modelValueToCheck = $modelBeingUpdated->{$attribute} ? $modelBeingUpdated->{$attribute}->getKey() : null;
            
            if ($modelValueToCheck == $value) {
                return false;
            }
        }
```

### Steps To Reproduce:

```
class A extends Model
{
    protected $table = 'a';

    public function b()
    {
        return $this->hasOne('App\B');
    }
}
```

```
class B extends Model
{
    protected $table = 'b';

    public function a()
    {
        return $this->belongsTo('App\A');
    }
}
```

in app\Nova\B.php
```
public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),            
            BelongsTo::make('A', 'a', 'App\Nova\A')->nullable()
        ];
    }
```

in app\Nova\A.php
```
public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
            HasOne::make('Book', 'b', 'App\Nova\B')->nullable()
        ];
    }
```

**Comment by hcancelik** [comment]
This issue is related with #1058.

Once you save to belongsTo relation to null you won't be able to update to any other value.

**Comment by h-zone** [comment]
Same troubles. This is a crytical bug.

**Comment by cjf** [comment]
> Same troubles. This is a crytical bug.

You can apply my proposed fix for now.  It works in my case at least.  I don't have a full test suite to run against however.

**Comment by victorpfm** [comment]
> > Same troubles. This is a crytical bug.
> 
> You can apply my proposed fix for now. It works in my case at least. I don't have a full test suite to run against however.

Thanks @cjf for that fix. It has worked for me as well.

**Comment by tumispro** [comment]
Any news on this? Seems weird that such a simple bug can exist for so long.

**Comment by Frozire** [comment]
Running into the same issue on `v2.0.6`

If anyone found any other workarounds do feel free to share while we wait for a fix.

**Comment by georgekcx** [comment]
We Circumvented this problem, by doing: 
```php 

    /**
     * Determine if the relationship is "full".
     *
     * @param  \Illuminate\Database\Eloquent\Model  $model
     * @param  string  $attribute
     * @param  mixed  $value
     * @return bool
     */
    protected function relationshipIsFull($model, $attribute, $value)
    {

        $inverseRelation = $this->request->newResource()
                    ->resolveInverseFieldsForAttribute($this->request, $attribute)->first(function ($field) {
                        return $field instanceof HasOne || $field instanceof MorphOne;
                    });

        if ($inverseRelation && $this->request->resourceId) {
            $modelBeingUpdated = $this->request->findModelOrFail();

            if (optional($modelBeingUpdated->{$attribute})->getKey() == $value) {
                return false;
            }
        }

        return $inverseRelation &&
               $model->{$inverseRelation->attribute}()->count() > 0;
    }

```

**Comment by MohammadAbusaleh** [comment]
Any update on when this will be resolved ?

**Comment by tumispro** [comment]
I am still experiencing this issue in the latest version (v2.6.1). The proposed fix from @cjf in his original post works.

```
protected function relationshipIsFull($model, $attribute, $value)
    {
        $inverseRelation = $this->request->newResource()
                    ->resolveInverseFieldsForAttribute($this->request, $attribute)->first(function ($field) {
                        return $field instanceof HasOne || $field instanceof MorphOne;
                    });

        if ($inverseRelation && $this->request->resourceId) {
            $modelBeingUpdated = $this->request->findModelOrFail();

            $modelValueToCheck = $modelBeingUpdated->{$attribute} ? $modelBeingUpdated->{$attribute}->getKey() : null;
            
            if ($modelValueToCheck == $value) {
                return false;
            }
        }
```

**Comment by davidhemphill** [comment]
The fix hasn't been released yet.

**Comment by cjf** [comment]
> The fix hasn't been released yet.

Are there plans to?

**Comment by davidhemphill** [comment]
What do you think?

**Comment by cjf** [comment]
Wow.   

The associated bug was opened over a year ago.  A fix was proposed 8 months ago.  Maybe dial back the snark a bit and consider that it is an honest question.  There has never been any evidence you were interested in a fix.

So if I'm being honest, no.  I think you have no plans to release a fix to this.  Prove me wrong.

**Comment by davidhemphill** [comment]
The fix is already deployed. 😅

**Comment by cjf** [comment]
Your attitude is amazing.  

You all have a serious communication problem.  You should spin this thread off as a bug report on that.  This customer service should be embarrassing for you.

Pull your team (@davidhemphill @jbrooksuk @taylorotwell ) in and have a talk.

**Comment by davidhemphill** [comment]
@cjf I was short, yes, but your comment, "Are there plans to?" came off snarky and rhetorical so I returned the same. I told you the fix wasn't released **yet**. The commit that fixes the issue is listed previously in the feed. We release every two weeks. It seems obvious that it'd get deployed in the next release, but I realize that you don't think so. If you'd like to continue this further, please feel free to email us at nova@laravel.com.

**Comment by nick-jansen** [comment]
If somebody is interested in a workaround to disable the `Relatable` validation rule on a `BelongsTo` field:

```php
<?php
# file: app/Nova/Fields/BelongsTo

namespace App\Nova\Fields;

use Laravel\Nova\Rules\Relatable;
use Laravel\Nova\Http\Requests\NovaRequest;
use Laravel\Nova\Fields\BelongsTo as NovaBelongsTo;

class BelongsTo extends NovaBelongsTo
{
    /**
     * Get the validation rules for this field.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @return array
     */
    public function getRules(NovaRequest $request)
    {
        $rules = parent::getRules($request);

        foreach ($rules as $key => $rule) {
            $rules[$key] = array_filter($rule, function ($value) {
                return !is_object($value) || get_class($value) !== Relatable::class;
            });
        }

        return $rules;
    }
}
```
And use the field in your resource:
```php
<?php
# file: app/Nova/MyResource.php

use App\Nova\Fields\BelongsTo;

class MyResource extends Resource
{
    public function fields(Request $request) {
        return [
            BelongsTo::make(__('Owner'), 'owner', User::class)
        ];
    }
}
```
