### ISSUE TITLE
Add viaRelationship in Relatable{Model} Query

### ISSUE THREAD

**Issue by arditokshtuni** [laravel/nova-issues#1442]
- Laravel Version: 5.8.*
- Nova Version: 2.0.*
- PHP Version: 7.2
- Operating System and Version: #.#
- Browser type and version: #.#

### Description:
I have two models that share 2 BelongsToMany relationships.
User and Role for example.
--------------
User Model:
```
function acticeRoles () {
    return $this->belongsToMany(Role::class, 'role_user_active', 'user_id', 'role_id');
}
function inacticeRoles () {
    return $this->belongsToMany(Role::class, 'role_user_inactive', 'user_id', 'role_id');
}
```
--------------
Role Model:
```
function acticeUsers () {
    return $this->belongsToMany(Role::class, 'role_user_active', 'role_id', 'user_id');
}
function inacticeUsers () {
    return $this->belongsToMany(Role::class, 'role_user_inactive', 'role_id', 'user_id');
}
```
--------

I have added 2 BelongsToMany in Role Resource in Nova.
In Role Resource relatableQuery for example relatableUsers we need to access viaRelationship parameter so we can show different values (Users) to attach to that Role based on viaRelationship function.
For example i need to show Users where status = 1 when viaRelationship is activeUsers
and i want to show Users where status = 0 when viaRelationship is inactiveUsers

Something like this in Role Resource, Nova:

```
function relatableUsers (NovaRequest $request, $query) {
    $viaRelationship = $request->input('viaRelationship);
    if ($viaRelationship == 'activeUsers') {
        return $query->where('status', 1);
    } elseif ($viaRelationship == 'inactiveUsers') {
        return $query->where('status', 0);
    }
}
```
Maybe this is related to #988 #1441

**Comment by dkulyk** [comment]
For `associatable`, `attachable` and `morphable` requests you can use `$request->field` for retrieving field attribute

**Comment by arditokshtuni** [comment]
@dkulyk 
I do not know if you got my problem, but can you show me an example, how can i solve my problem?
`$request->field` is used for pivots? right?
I have no Pivot columns in many_to_many tables.
I just need to know which is currently `viaRelationship` called in relatableUsers

I saw this comment in #337 , the second last one.
But it can be done only if viaRelationship can be accessed in indexQuery, i haven't try that yet, i will ASAP

**Comment by arditokshtuni** [comment]
@dkulyk 
I solved this situation by using Sessions/Cookies in fields() function of Nova Resource, because there i can get which Relationship was loaded so i put viaRelationship in a Session and than i get this Session value in relatableQuery Method in the other Resource where i do If() elseif() else check, and than i know which resource to load in the DropDown of Attaching method.
This can be used also when Two Resources Share more than one Relation, and they should have different possible values to attach or to have or to belong to.

But it will be nice to access viaRelationship value directly in relatableQuery or indexQuery just to not use kind of solutions like i used, so leaving this issue OPEN.

If anyone will be in same situation, just leave a comment and i  will put the code example.

**Comment by Naphyrion** [comment]
> 
> 
> @dkulyk
> I solved this situation by using Sessions/Cookies in fields() function of Nova Resource, because there i can get which Relationship was loaded so i put viaRelationship in a Session and than i get this Session value in relatableQuery Method in the other Resource where i do If() elseif() else check, and than i know which resource to load in the DropDown of Attaching method.
> This can be used also when Two Resources Share more than one Relation, and they should have different possible values to attach or to have or to belong to.
> 
> But it will be nice to access viaRelationship value directly in relatableQuery or indexQuery just to not use kind of solutions like i used, so leaving this issue OPEN.
> 
> If anyone will be in same situation, just leave a comment and i will put the code example.

Hi, i have the same problem, please put the example code for make me an idea to how find  a solution. Thx

**Comment by imran-concise** [comment]
@Naphyrion 

Here's a crazy solution:

`app/Providers/AppServiceProvider.php`

in the boot method register new js file

eg `Nova::script('admin', __DIR__.'/../../public/js/admin.js');`

Create a new JS file you compile to the public js folder 

eg `resources/js/admin.js`

append the parent path to the request:

(you can add some conditionals here if you want to add this to only some resources)
```
Nova.request().defaults.params = {}
Nova.request().defaults.params['path'] = window.location.pathname
```
Now you have access to the parent path on the associatable ajax queries.

Given a **Feature** resource with a **Theme** relationship

`app/Nova/Feature.php`

```
public static function relatableThemes(NovaRequest $request, $query)
{
    $parent = NovaRequest::create($request->path);
    $model = \App\Feature::findOrFail($parent->segment(4));

    return $query->where('project_id', $model->project->id);
}
```
Hopefully gives you an alternative than using sessions.
