### ISSUE TITLE
belongsTo cannot update relation

### ISSUE THREAD

**Issue by jordyvandomselaar** [laravel/nova-issues#1443]
When trying to edit an existing `belongsTo` relationship the dropdown is disabled. 

![image](https://user-images.githubusercontent.com/12712484/54272663-69878700-4584-11e9-8bf3-1bf9c5ea1ab0.png)

**Comment by dkulyk** [comment]
You cannot to update attached resource. You need to detach it and attach other resource.

**Comment by jordyvandomselaar** [comment]
But, why is the drop-down there then?

**Comment by jordyvandomselaar** [comment]
@davidhemphill Why did you close this issue? It's not resolved and it looks like a bug to me…
