### ISSUE TITLE
Nova select field in view doesn't show translations

### ISSUE THREAD

**Issue by lichtner** [laravel/nova-issues#1445]
- Laravel Version: 5.7.28
- Nova Version: 1.3.2
- PHP Version: 7.3
- Operating System and Version: Ubuntu 18.4
- Browser type and version: all

### Description:

Nova select field definition: 

```php
Select::make(__('Sex'), 'sex')->options([
    'male' => __('male'),
    'female' => __('female'),
]),
```
this select show translated string in select form control, but in view show only values stored in db `male` or `female` and ignore translations.

**Comment by dkulyk** [comment]
You need to use [`displayUsingLabels()`](https://nova.laravel.com/docs/2.0/resources/fields.html#select-field).

**Comment by lichtner** [comment]
thanks @dkulyk, I haven't noticed it.
