### ISSUE TITLE
Click next so much time will exceed pagination

### ISSUE THREAD

**Issue by ahmedkandel** [laravel/nova-issues#1446]
- Laravel Version: 5.7.28
- Nova Version: 1.3.2
- PHP Version: 7.2
- Operating System and Version: Windows 10
- Browser type and version: Chrome 72

### Description:
When clicking next button on resource index, the end user is waiting for the new resources so he may click next again and again which will go to pages that exceed the correct pagination.

### Steps To Reproduce:
If the resource has 40 items and is viewing 25 per page when in the first-page click next twice it will go to the third page which is not correct as max it there are two pages. even when he refreshed the page the current page parameter in the query string remains which is good but in this case, the user will have no resource to view

Possible solution: disable the next button until the new resource is loaded. also, show loading indicator like in the initial resource page.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
