### ISSUE TITLE
Bug: Validation translation strings ignore label

### ISSUE THREAD

**Issue by lichtner** [laravel/nova-issues#1447]
- Laravel Version: 5.7.28
- Nova Version: 1.3.2
- PHP Version: 7.3
- Operating System and Version: Ubuntu 18.4
- Browser type and version: all

### Description:

nova field definition:
```php
  Text::make(__('First Name'), 'fname')->rules(['required']),
```
`resources/lang/en/validation.php` contains e.g. this:
```php
    'required' => 'The :attribute field is required.',
```
I add translation for my language, but after submitting empty first name this appears:
```
The fname field is required.
```
Only database table column name appears, but I expect:
```
The First Name field is required.
```
label of field should be used and translation of this after I switch app into my language.

**Comment by markwalet** [comment]
This is expected i guess? If you want to translate validation fields you normally do that in `validation.attributes.*` right?

**Comment by lichtner** [comment]
@markwalet sorry I don't understand. I expect in validation strings is used label not the field's name. 

E.g. if you have table column `users.dob` and user will see `The dob field is required.` it is confusing IMHO. I expect this: `The day of birth field is required`. End users don't care how field is stored in db.

**Comment by markwalet** [comment]
This is not a Nova feature but a Laravel feature. When throwing validation errors. Laravel checks if the column name is present in your `validation.php` translation file. If it is, it will replace the column name with the custom attribute name that you configured.

Documentation: https://laravel.com/docs/5.8/validation (Search for `Specifying Custom Attributes In Language Files`)

**Comment by lichtner** [comment]
:+1: @markwalet excellent! I didn't know about it. You saved my life :smile: thanks a lot.
