### ISSUE TITLE
How can I set ActionEvent 's $connection property on loading the ActionEvent?

### ISSUE THREAD

**Issue by phoenixg** [laravel/nova-issues#1449]
- Laravel Version: 5.8
- Nova Version: 2.0.0
- PHP Version: 7.2
- Operating System and Version: mac os
- Browser type and version: chrome latest

### Description:

If `action_event` is in another database, then will trigger an error said table or view not found. After I set `$connection` property in `ActionEvent` then problem solved, but this will make the sourcecode change.

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).
