### ISSUE TITLE
Problem adding BelongsTo field to an Action

### ISSUE THREAD

**Issue by eoghanobrien** [laravel/nova-issues#145]
Laravel Version: 5.6.34
Nova Version: 1.0.5

**Background**
I was trying to create an action that pops-up a form where the user can assign an auction to an auction lot.

So I set up an action as follows:
```php
<?php

namespace App\Nova\Actions;

use Illuminate\Bus\Queueable;
use Laravel\Nova\Actions\Action;
use Illuminate\Support\Collection;
use Laravel\Nova\Fields\ActionFields;
use Illuminate\Queue\SerializesModels;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;
use Laravel\Nova\Fields\BelongsTo;

class AssignAuction extends Action
{
    use InteractsWithQueue, Queueable, SerializesModels;

    /**
     * Perform the action on the given models.
     *
     * @param  \Laravel\Nova\Fields\ActionFields  $fields
     * @param  \Illuminate\Support\Collection  $models
     * @return mixed
     */
    public function handle(ActionFields $fields, Collection $models)
    {
        // removed for brevity
    }

    /**
     * Get the fields available on the action.
     *
     * @return array
     */
    public function fields()
    {
        return [
            BelongsTo::make('Auction'),
        ];
    }
}

```

However, I got the following error:

> Class 'App\Nova\Actions\Auctions' not found

So, I added the FQCN of the `Auction` resource instead

```php
...
    public function fields()
    {
        return [
            BelongsTo::make('Auction', null, '\App\Nova\Auction'),
        ];
    }
...
```

That gave me a new error:

> Call to undefined method class@anonymous::auction()

Digging in a little deeper, I found that the `Action` class does in fact pass an anonymous function to the `resolve` method on each `Field` class in the `Action::jsonSerialize()` method.

```php
    /**
     * Prepare the action for JSON serialization.
     *
     * @return array
     */
    public function jsonSerialize()
    {
        return [
            'class' => get_class($this),
            'destructive' => $this instanceof DestructiveAction,
            'name' => $this->name(),
            'uriKey' => $this->uriKey(),
            'fields' => collect($this->fields())->each->resolve(new class {
            })->all(),
            'availableForEntireResource' => $this->availableForEntireResource,
            'onlyOnDetail' => $this->onlyOnDetail,
        ];
    }
```

For the `BelongsTo` field, the `resolve()` method takes two arguments, the `$resource` and an optional `$attribute`.

```php
    /**
     * Resolve the field's value.
     *
     * @param  mixed  $resource
     * @param  string|null  $attribute
     * @return void
     */
    public function resolve($resource, $attribute = null)
    {
        $value = $resource->{$this->attribute}()->withoutGlobalScopes()->first();

        if ($value) {
            $this->belongsToId = $value->getKey();

            $this->value = $this->formatDisplayValue($value);
        }
    }
```

The error above seems to occur when trying to resolve the `$value` from the resource but is not able to do so from the anonymous class.

> Call to undefined method class@anonymous::auction()

I'm not sure if I just went down an unnecessary rabbit hole here, perhaps I could have passed the parameters to the `BelongsTo::make()` method in a different way, or maybe this is intended behavior and `BelongsTo` fields aren't supported on actions just yet. Or this is an actual bug. In any case, I figured I would report and see if there is an official approach/answer.

F.Y.I. My relationships are correctly set up on my models and work on regular Nova forms perfectly.

**Comment by lucasromanojf** [comment]
I have the same need.

**Comment by DonDiegoAA** [comment]
Here is how I resolved this case:

```
public function handle(ActionFields $fields, Collection $models)
{
  $auction = Auction::find($fields->auction);
  $count = 0;
  foreach ($models as $model) {
    if (! $model->auctions->contains($fields->auction)) {
      $model->auctions()->attach($fields->auction);
      $count++;
    }
  }
  return Action::message($count.' item(s) have been attached to '.$auction->title);
}

public function fields()
{
  $auctions = Auction::all()->pluck('id','title'); //Assuming there is a Title field in Auction
  return [
     Select::make('Auction')->options($auctions)
  ];
}
```

**Comment by ardyn** [comment]
Same issue. I have a model which can subscribe to any number of services. A simple \App\Service::all() returns all services, no problem.

But this model can only subscribe to one of a limited number of locations. I can't return all of them! I need to be able to return all locations where model_id is equal to the current model I am running the action on. But requests to /nova-api/model/actions does not include the id of the current model. This is because the action can be ran on a collection, so why send model id?

**Comment by ardyn** [comment]
I need to know which resource id is calling the action. There is no information in the request when hitting nova-api/model/actions . So the Action controller has no idea which model resource id is calling it.

**Comment by ardyn** [comment]
Here is my solution:

```
// In MyActionClass
  private $id;

    /**
     * Class constructor
     *
     * @param \App\Models\Customer $customer
     */
    public function __construct(\Illuminate\Http\Request $request)
    {
        if (preg_match('/\d+$/', $request->headers->get('referer'), $matches))
            $this->id = $matches[0];
    }

// In the Nova Resource

    public function actions(Request $request)
    {

        return [
            new MyActionClass($request),
        ];
    }
```
Now i know resource id who is calling the action. Also     public $onlyOnDetail = true; in Action class

**Comment by taylorotwell** [comment]
This repository is for tracking bugs. Feature requests may be emailed to Nova customer support.

**Comment by dongkaipo** [comment]
When i add that to action
```
public function uriKey()
    {
        return str_slug(Nova::humanize($this));
    }
```
it works~
But i cant remember where i found the code

**Comment by BobbyBorisov** [comment]
@ardyn I tried your solution and it does not work. it still gives Undefined property: class@anonymous::$something

**Comment by FrittenKeeZ** [comment]
I used the same approach as @DonDiegoAA, but using the resource class instead of the model.
```php
use App\Nova\Subscription;

/**
 * Get the fields available on the action.
 *
 * @return array
 */
public function fields(): array
{
    $options = with(Subscription::newModel()->newQuery(), function ($query) {
        foreach (Subscription::$orderBy as $property => $direction) {
            $query->orderBy($property, $direction);
        }

        return $query->get()->pluck(Subscription::$title, 'id');
    });

    return [
        Select::make('Subscription')
            ->options($options)
            ->rules('required', 'exists:subscriptions,id'),
    ];
}
```

**Comment by massimodellarovere** [comment]
> This repository is for tracking bugs. Feature requests may be emailed to Nova customer support.

This is the most common phrase in the repository :D
You have chosen a difficult job ... :+1:

**Comment by hello-liang-shan** [comment]
```php
<?php

namespace App\Nova\Fields;

use Laravel\Nova\Fields\BelongsTo;
use Laravel\Nova\Http\Requests\NovaRequest;

class BelongsToForActionField extends BelongsTo
{
    public function fillForAction(NovaRequest $request, $model)
    {
        $attribute = $this->attribute;

        if ($request->exists($attribute)) {
            $value = $request[ $attribute ];

            $model->{$attribute} = $this->isNullValue($value) ? null : $value;
        }
    }
}
```

**Comment by pelmered** [comment]
Thank you @hello-liang-shan! 
But this really shouldn't be necessary. How can this be in Nova?
