### ISSUE TITLE
<validation-errors> component does not work

### ISSUE THREAD

**Issue by jyrkidn** [laravel/nova-issues#1451]
- Laravel Version: 5.8.4
- Nova Version: v2.0.0
- PHP Version: 7.3.3

### Description:
I'm writing a tool with my own validation, I wanted to use the `<validation-errors>` component, since it's also used in the Update and Create views, but it does not display the errors.

### Steps To Reproduce:
In my Vue template:
```vue
<validation-errors :errors="validationErrors" />
```

In the script data (as defined here):
```js
import { Errors } from 'laravel-nova'

export default {
    data: () => ({
        validationErrors: new Errors({
            errors: {
                field1: ['Value is required'],
                field2: ['Value is required']
            }
        })
    })
}
```

### Fix
If I use my own component with this html it works (had to update the class as well, since there were bootstrap classes used). If it won't be fixed, maybe better to remove it?

```vue
<div
    v-if="modal.error.any()"
    class="row"
>
    <div class="bg-danger">
        <strong>{{ __('Whoops!') }}</strong> {{ __('Something went wrong.') }}

        <br><br>

        <!-- Error Listing -->
        <ul style="margin-bottom: 0;">
            <li
                v-for="(error, key) in modal.error"
                :key="key"
            >
                {{ Object.values(error).join(', ') }}
            </li>
        </ul>
    </div>
</div>
```

**Comment by davidhemphill** [comment]
Make sure your `errors` prop is an instance of Errors from `backend-form-validation`. 

This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).

**Comment by jyrkidn** [comment]
@davidhemphill I pass an instance of Errors to the component (as you can see in my example)
