### ISSUE TITLE
Vue Router

### ISSUE THREAD

**Issue by xerk** [laravel/nova-issues#1453]
- Laravel Version: 5.8.*
- Nova Version: 2.0.*
- PHP Version: 7.1

How I can make VueRouter in my frontend is no find admin page?

```
Route::get('/{vue_capture?}', function () {
    return view('home');
})->where('vue_capture', '[\/\w\.-]*');
```

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).
