### ISSUE TITLE
Default value 0 (zero) goes empty to the query

### ISSUE THREAD

**Issue by msassa** [laravel/nova-issues#1454]
- Laravel Version: 5.7
- Nova Version: 1.3.2
- PHP Version: 7.1

### Description:
When I set a default value of 0 in model attributes, goes to the query as an empty value, and get an error like: `SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'prices_avg'`

### Steps To Reproduce:

Set the attributes in the model

![image](https://user-images.githubusercontent.com/570080/54390090-6a9dde80-4680-11e9-96c3-bc60648894a3.png)

Set the field in Nova resource

![image](https://user-images.githubusercontent.com/570080/54390152-90c37e80-4680-11e9-96bc-d6be51d54281.png)

Go to add form, and I get this:

![image](https://user-images.githubusercontent.com/570080/54390185-a5077b80-4680-11e9-97e0-a139f69b3270.png)

Should be ok, but when I submit the form:

![image](https://user-images.githubusercontent.com/570080/54390267-d41ded00-4680-11e9-8953-f7ba85f4a2cb.png)

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
