### ISSUE TITLE
Select parent child

### ISSUE THREAD

**Issue by cwplus** [laravel/nova-issues#1455]
I have 

Category model:
- id
- name
- parent_id

property model
- id
- title
- category_id
....

in the form property view, I would like to display a list (Selectbox)
parent categories, and after, a selectbox of categories,

When a parent category is selected, the categories field displays the child categories of the parent category.

I wanted to create a new custom field, to manage the communication between the component "parent category" and the component "category by child" with Vuejs, but, unfortunately, I did not find the way to listen to this component " parent category "in the" category "component

If you have an idea or an example?

Thank you

<img width="1759" alt="Capture d’écran 2019-03-14 à 23 31 27" src="https://user-images.githubusercontent.com/5727109/54395916-81105e00-46b1-11e9-9a2e-3165c35bcae6.png">

**Comment by davidhemphill** [comment]
You can fire events on the Nova Event Bus and listen to them in your custom fields: https://nova.laravel.com/docs/2.0/nova-js/event-bus.html

**Comment by cwplus** [comment]
t can be used in custom components, but not existing components, such as BelongsToField, or Select ?

**Comment by sabid** [comment]
[https://novapackages.com/packages/alvinhu/nova-child-select](url)

**Comment by cwplus** [comment]
Very thinks @sabid 👍
