### ISSUE TITLE
Unable to use add{Model} policy if "create" policy on relationship returns false

### ISSUE THREAD

**Issue by hotmeteor** [laravel/nova-issues#1457]
- Laravel Version: 5.7.28
- Nova Version: 1.3.2
- PHP Version: 7.2.15
- Operating System and Version: macOS Mojave
- Browser type and version: Firefox 65

### Description:

I am unable to control the addition of related models solely using a `add{Model}` style policy, without also enabling a `create` policy on the related model. For example:

- `Post` has many `Comment`s.
- I create a `create` policy for `Comment`s that is `false`, because I don't want users creating parent-less comments.
- I create a `addComment` policy that returns `true` for `Post`s
- View a `Post` detail to add a new comment and... nothing. No button.
- Change the `CommentPolicy@create` method to return `true`
- "Create Comment" button is visible on Post detail, but also on the Comment index

This is not desirable. I feel like I must be doing something wrong, because this seems straightforward in the docs, but it's not working.

Related to:
https://github.com/laravel/nova-issues/issues/111
https://github.com/laravel/nova-issues/issues/247
https://github.com/laravel/nova-issues/issues/567

### Steps To Reproduce:

See above.

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!

**Comment by tainmar** [comment]
This bug is still present in v2.0. Shall I open a new issue @jbrooksuk ?

**Comment by aoderinde** [comment]
I'm on v3.8.1 and still have this same behaviour - there is no button "Add {model}" even though I use the add{Model} policy correctly. 
Was this really fixed?

**Comment by groax** [comment]
I have this problem as well.. Is there a fix?
