### ISSUE TITLE
Next / Previous buttons on resource detail, at the top, next to actions/delete/edit.

### ISSUE THREAD

**Issue by greggh** [laravel/nova-issues#1458]
I need to move through some detail pages a bit faster, reviewing a data set. For this I need to have a couple buttons for previous and next at the top of the detail, right next to the actions, delete, and edit buttons.

Can this already be accomplished? Does anyone have example code yet? Is this a feature thats coming soon?

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by greggh** [comment]
This post seems to give a good way to get next and previous IDs:

[https://daveismyname.blog/laravel-get-previous-and-next-record](https://daveismyname.blog/laravel-get-previous-and-next-record)

I'm having trouble passing data in from a resource tool.
