### ISSUE TITLE
Global Search Avatar Style Missing

### ISSUE THREAD

**Issue by wcjonathan** [laravel/nova-issues#1459]
The avatar used in the global search is missing the following style attribute on the image.

style="object-fit: cover;"

This will allow any uploaded avatar to display correctly, the same as an Avatar does when being listed.

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
