### ISSUE TITLE
[Request] Add subtitle to relations search results

### ISSUE THREAD

**Issue by mrmonat** [laravel/nova-issues#146]
This is a idea / request to add the subtitle to the search results when searching while attaching relations. It could be displayed in the same way like in global search.

**Comment by v1nk0** [comment]
+1

For example a database of artists, shows, fixtures and venues:
Artist _hasMany_ Shows
Show _belongsTo_ Artist.
Fixture _belongsTo_ Show and Venue. 
Show _hasMany_ Fixtures.

Let's say there are 500 artists. Some of them will have a show with the same name (e.g. "Best of")
When I try to attach a _Show_ to a _Fixture_, I search for "Best of" (the Show relation has `searchable()`) and I get a list of Best of shows, without knowing what artist the show belongs to (which is crucial here) When I enter "Best of" in the global search, it nicely adds the artist as `subtitle` as I've configured this on the Show resource.

**Comment by taylorotwell** [comment]
This repository is for tracking bugs. Feature requests may be emailed to Nova customer support.
