### ISSUE TITLE
Laravel Nova validation not showing on dot notation

### ISSUE THREAD

**Issue by umarakber** [laravel/nova-issues#1461]
- Laravel Version: 5.7
- Nova Version: 1.3.2
- PHP Version: 7.2
- Operating System and Version: Ubuntu
- Browser type and version: Chrome (latest)

### Description:
With ref [this](https://github.com/laravel/nova-issues/issues/1327) i am replacing dot with 
 "_"  for validation on dot notation but validation on showing on form field, it is showing on console can any one please help me it is very urgent

**Comment by davidhemphill** [comment]
Sorry, but we are unable to debug your issue without a reproducible code example. Once you provide that we can open this up again.
