### ISSUE TITLE
with displayUsingLabels, labels are not searched

### ISSUE THREAD

**Issue by yehudahkay** [laravel/nova-issues#1464]
- Laravel Version: 5.8
- Nova Version: 2.0
- PHP Version: 7.2

### Description:
If you use a select with the option displayUsingLabels, the labels are displayed in the index, however they are not searchable in the index search. This is because the labels are not in the database. However this is very confusing because you can see them in the list. 

One way I can think of fixing this in the code is including any keys from the select array that match the search term. 

Thank you!

**Comment by devfrey** [comment]
I don't think this qualifies as an 'issue'. It's a technical limitation that is hard to get around.

**Comment by yehudahkay** [comment]
In my code I've gotten around it by adding the following function to indexQuery. But this isn't ideal as the or where really needs to be in the parentheses and it may affect other aspects of the query that I haven't thought of. Maybe I could overwrite the entire function but I think this should be dealt with as it is very confusing for the end user to see data but not find it in search.

```
if ($request->get('search')) {
            foreach (self::privileges() as $key => $value) {
                if (strpos(strtolower($value), strtolower($request->get('search'))) > -1) {
                    $query->orWhere('privileges', $key);
                }
            }
        }
```

**Comment by davidhemphill** [comment]
The search functionality is built to only search values that are actually in the database. If you'd like to filter by values in a select field, the recommended approach is to use a filter: https://nova.laravel.com/docs/2.0/filters/defining-filters.html#select-filters
