### ISSUE TITLE
No automatically adding the id on HasMany relationship 

### ISSUE THREAD

**Issue by phuclh** [laravel/nova-issues#1465]
- Laravel Version: 5.8.5
- Nova Version: 2.0.0
- PHP Version: 7.1
- Operating System and Version: MacOS Mojave 10.14.3
- Browser type and version: Google Chrome 72.0.3626.121

### Description:
I have 2 models: Product (Table: products) and ProductVariety (Table: product_varieties) (A product has many product varieties).

I have a Text Filed with the `fillUsing` method to save data of ProductVariety on Product Resource like this:

```

// Product Resource
Text::make('Ram')->fillUsing(function ($request, $model) {
                    $model->productVarieties()->create([
                        'ram' => '8GB'
                    ]);
                })

// Or even I tried the save method like this

$variaties = new ProductVariety([
                        'ram' => '8GB'
                    ]);
                    
                    $model->productVarieties()->save($variaties);

```
But it doesn't attach the product ID into the saving query, so I got the error: The `product_id` cannot be null.

### Steps To Reproduce:
1. Using the `fillUsing` method to save data on HasMany relationship
2. The id isn't attached to the query automatically.

**Comment by dkulyk** [comment]
You product hasn't saved yet. But you can return closure:
```php
Text::make('Ram')->fillUsing(function ($request, $model, $attribute, $requestAttribute) {
    return function () use ($model, $request, $requestAttribute) {
        $model->productVarieties()->create([
            'ram' => $request->post($requestAttribute)
        ]);
    }
})
```

**Comment by phuclh** [comment]
@dkulyk Thank you so much, it works :D. However, I don't understand what does the 3rd parameter of `fillUsing` method ($attribute) stand for?

Moreover, I try to generate the Nova Field by getting a Field list from database like this:

```
foreach ($attributeGroup->attributes as $attribute)
            {
                $class = 'Laravel\\Nova\\Fields\\' . ucfirst($attribute->type);
                $field = $class::make($attribute->name, $attribute->code)->fillUsing(function ($request, $model, $requestAttribute) use ($attribute) {
                    return function () use ($model, $request, $requestAttribute, $attribute) {
                        $model->productVarieties()->create([
                            $attribute->code => $request->post($requestAttribute)
                        ]);
                    };
                });

                // Only select dropdown menu has options
                if ($attribute->type == 'select')
                {
                    $field->options($attribute->getOption());
                }

                $attribute->setValidation($field);
            }
```

For example, I have 2 fields RAM and HDD, but it only adds the RAM field to the query, the HDD doesn't. How can I add both of them into the query and save them 1 time? Thank you in advance!!!

**Comment by dkulyk** [comment]
You need to isolate each loop. something like:
```php
$fields = collect($attributeGroup->attributes)->map(function ($attribute) {
    //your code

    return $field;
})->filter()->all()
```

**Comment by phuclh** [comment]
@dkulyk It doesn't work :(

Here is my code:
```
foreach ($attributeGroups as $attributeGroup)
        {
            $fields = collect($attributeGroup->attributes)->map(function ($attribute) {
                $class = 'Laravel\\Nova\\Fields\\' . ucfirst($attribute->type);
                $field = $class::make($attribute->name, $attribute->code)->fillUsing(function ($request, $model, $requestAttribute) use ($attribute) {
                    return function () use ($model, $request, $requestAttribute, $attribute) {
                        $model->productVarieties()->create([
                            $attribute->code => $request->post($requestAttribute)
                        ]);
                    };
                });

                // Only select dropdown menu has options
                if ($attribute->type == 'select')
                {
                    $field->options($attribute->getOption());
                }

                $attribute->setValidation($field);


                return $field;
            })->filter()->all();

            $tabs[ $attributeGroup->name ] = $fields;
        }
```

**Comment by phuclh** [comment]
@dkulyk can you help me out this problem?

**Comment by philipbaginski** [comment]
> ```
> Text::make('Ram')->fillUsing(function ($request, $model, $attribute, $requestAttribute) {
>     return function () use ($model, $request, $requestAttribute) {
>         $model->productVarieties()->create([
>             'ram' => $request->post($requestAttribute)
>         ]);
>     }
> })
> ```

How it goes for you, are you done with this problem?

**Comment by philipbaginski** [comment]
> @dkulyk can you help me out this problem? Thank you so much!!!
> 
> The above code will create 2 rows in the database like that, how can I combine data into a array and just save 1 time.
> 
> <img alt="Screen Shot 2019-03-22 at 12 24 50 AM" width="220" src="https://user-images.githubusercontent.com/6707194/54807013-1aeb8400-4c39-11e9-9a73-c3b2478ebc7d.png">

How it goes for you, are you done with this problem?
