### ISSUE TITLE
PHPDoc: Incorrect return type for InteractsWithResources::findModelQuery()

### ISSUE THREAD

**Issue by devfrey** [laravel/nova-issues#1467]
- Laravel Version: 5.8.5
- Nova Version: 2.0.0
- PHP Version: N/A
- Operating System and Version: N/A
- Browser type and version: N/A

### Description:
The `findModelQuery()` method in the `InteractsWithResources` trait is documented to return an instance of `Illuminate\Database\Eloquent\Model`, but it actually returns an instance of `Illuminate\Database\Eloquent\Builder`. This causes autocomplete issues.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
