### ISSUE TITLE
Date filter not displaying calendar

### ISSUE THREAD

**Issue by sijones-uk** [laravel/nova-issues#1469]
- Laravel Version: 5.7.28
- Nova Version: 1.3.2
- PHP Version: 7.1.27
- Operating System and Version: Ubuntu 18.04.2
- Browser type and version: Firefox (PC) 65.0.2

### Description:
When creating a date filter, following the [instructions here](https://nova.laravel.com/docs/1.0/filters/defining-filters.html#date-filters), the resulting filter is displayed as a select box, and doesn't trigger a calendar when clicked. The select box contains only the default "empty" option. A similar issue was previously reported in #1135 but running `php artisan nova:publish` did not fix it for me.

### Steps To Reproduce:
1. Create a date filter, e.g. `php artisan nova:filter TestDateFilter --date` and add it to the filters  array for a resource
2. View the list page for that resource. The filter displays as an empty select box and doesn't trigger the calendar

**Comment by davidhemphill** [comment]
Just tested this on 1.3.2 and DateFilters are displaying correctly. Please make sure you've ran `php artisan nova:publish --force` to ensure you have the latest compiled assets.

**Comment by danielbachhuber** [comment]
> Please make sure you've ran `php artisan nova:publish --force` to ensure you have the latest compiled assets.

This was an important missing step for me 😄
