### ISSUE TITLE
Error when running artisan nova:tool command

### ISSUE THREAD

**Issue by jwjcmw** [laravel/nova-issues#147]
I'm getting an error when creating a new tool using `artisan nova:tool`.  
![image](https://user-images.githubusercontent.com/2118746/44594784-222adc00-a795-11e8-982d-fb4cadad2ab2.png)
This is using Nova v1.0.6 on Windows 10 with PHP 7.1.13

The same error is received if I say "no" to the first question and then say "yes" to either the compiling or composer update questions (and why are those even being asked if you say no to the first one).

If I say yes to the first question, it does do a `npm install` before the error is thrown.  I don't think either of the subsequent operations get attempted, however.

**Comment by DonDiegoAA** [comment]
Same problem for me with nova:card or nova:field.

Win10, Laragon, Laravel 5.6, NPM version 3.10.10.

![nova-error](https://user-images.githubusercontent.com/6011568/44605797-f1759180-a7ea-11e8-9162-7989b9abf29a.PNG)

**Comment by jwjcmw** [comment]
By commenting out the line in question (which looked like it was probably just spitting out whatever text the command produced), and then editing the webpack.mix.js as shown in #245, I was able to get this to run.

**Comment by julianpoma** [comment]
@jwjcmw I will try this later. Did you say yes when asked to install dependencies, and compiling the assets?

**Comment by jwjcmw** [comment]
I did say yes, AFTER editing the webpack.mix.js file that is in the new folder that was just created (nova-components/whatever).  Just leave your command window hanging in the background while you edit.

**Comment by julianpoma** [comment]
@jwjcmw Nova 1.0.7 is out and fixed the command issue. Now, you still have to make the __dirname + hack, because if you don't npm stucks at 95% while compiling assets.

**Comment by DonDiegoAA** [comment]
Thank you jwjcmw, I just tried that, and it works perfectly !

**Comment by jwjcmw** [comment]
Thanks, @julianpoma ...it would be nice if they notified us of new releases!

**Comment by davidhemphill** [comment]
Just pushed a fix for Windows when compiling assets. 🚀
