### ISSUE TITLE
Nullable text fields

### ISSUE THREAD

**Issue by sijones-uk** [laravel/nova-issues#1471]
- Laravel Version: 5.7.28
- Nova Version: 1.3.2
- PHP Version: 7.1.27
- Operating System and Version: Ubuntu 18.04.2
- Browser type and version: Firefox (PC) 65.0.2

### Description:
The documentation states that [Text fields can be made nullable](https://nova.laravel.com/docs/1.0/resources/fields.html#nullable-fileds) like this:

```
Text::make('Position')->nullable();
```

However, this doesn't seem to be supported. When the `nullable()` method is used, the list view shows an error:

```
Method Laravel\Nova\Fields\Text::nullable does not exist.
```

In addition, the `nullValues()` method isn't available.

### Steps To Reproduce:

As above, add the `nullable()` method to a Text field and load the corresponding view. The above error is displayed.

**Comment by devfrey** [comment]
Nullable text fields are not in Nova 1.x. I actually mentioned this a month ago in the PR that added it to the docs: https://github.com/laravel/nova-docs/pull/142.

**Comment by davidhemphill** [comment]
Nullable fields are supported in via #e667f85bb4c32cbd2ea1f7098b395e3b3028eaea. Just tested this on 1.3.2.

**Comment by ievgenklymenko** [comment]
I'm on 1.3.2 and having the same issues as @sijones-uk.
By the code it looks like, only few field types have 'nullable' methods. Namely, 'Date', 'DateTime', 'BelongsTo', 'MorphTo'.
So using it on Test results in:
> Method Laravel\Nova\Fields\Text::nullable does not exist.
