### ISSUE TITLE
Metrics value format isn't formatted with correct locale

### ISSUE THREAD

**Issue by rafaels-dev** [laravel/nova-issues#1472]
- Laravel Version: 5.8
- Nova Version: 2.0.0
- PHP Version: 7.2
- Browser type and version: Chrome

### Description:

I'm creating some metrics using `format("0,0")`, but NumeralJS on client side isn't using i18n and is formatting everything using default 'en' language.

As you can see below, the number '4,440' is in `en` language, but in `pt-br`, it would be '4.440'.
<img width="389" alt="Captura de Tela 2019-03-22 às 17 53 14" src="https://user-images.githubusercontent.com/5066597/54852679-4cf9f600-4ccc-11e9-934f-ded785b00fe1.png">

My computer and my Laravel Nova application is configured for `pt-BR` _locale_. This value is defined on `config/app.php` and tag `<html lang="...">` on `layout.blade.php`.

**Comment by ajhansen** [comment]
I'm having the same issue,.

**Comment by henryavila** [comment]
Same problem here. Anyone solved it?

**Comment by jbrooksuk** [comment]
This is because we don't import or use the locales. Numeral itself doesn't do any automatic conversions for us.

**Comment by jbrooksuk** [comment]
I've sent a PR to be reviewed that will address this.
