### ISSUE TITLE
How to customize the trix toolbar

### ISSUE THREAD

**Issue by olivM** [laravel/nova-issues#1475]
Is there a way to customize the trix toolbar ?

**Comment by stuartcusackie** [comment]
I emailed nova support about this a long time ago. Never heard back.

**Comment by davidhemphill** [comment]
You can't customize the internals of the Trix toolbar, but you can make your own using the instructions here: https://github.com/basecamp/trix/issues/28

There be dragons!

**Comment by allantatter** [comment]
Looks like it actually is possible to customize the toolbar https://github.com/basecamp/trix/issues/368.

**Comment by Jaspur** [comment]
@allantatter but how to fix that in nova? ;-)

**Comment by allantatter** [comment]
@Jaspur If I remember correctly, this couldn't be done in Nova at that point and you may need to make a PR to Nova itself and pray it will be merged :)

**Comment by stuartcusackie** [comment]
I gave up on this one. Trix seems a bit hard to work with.

I much prefer tiptap (https://tiptap.scrumpy.io/). Somebody's already made a nova component for it: https://github.com/manogi/nova-tiptap

**Comment by priceluke** [comment]
I found this package useful too:
[Nova Froala WYSIWYG Field](https://novapackages.com/packages/froala/nova-froala-field)

**Comment by nasrulhazim** [comment]
> I found this package useful too:
> [Nova Froala WYSIWYG Field](https://novapackages.com/packages/froala/nova-froala-field)

This one require purchasing of Froala product.

**Comment by gazben** [comment]
> > I found this package useful too:
> > [Nova Froala WYSIWYG Field](https://novapackages.com/packages/froala/nova-froala-field)
> 
> This one require purchasing of Froala product.

Yes, and you should avoid it at any cost. I've used it, and I'm not satisfied.

**Comment by mvanroon** [comment]
> > > I found this package useful too:
> > > [Nova Froala WYSIWYG Field](https://novapackages.com/packages/froala/nova-froala-field)
> > 
> > 
> > This one require purchasing of Froala product.
> 
> Yes, and you should avoid it at any cost. I've used it, and I'm not satisfied.

Also, these guys are crooks:
 - They add a 'Powered by Froala' message to your content even when you've purchased a license
 - They licensing is unclear. According to the pricing on their website, a 'basic license' should suffice for ecommerce websites. But we were contacted by their 'anti-privacy team' saying in their terms and conditions it is stated that 'any website that accepts payments' should upgrade to a much more expensive Pro license (USD 899/year!!)

**Comment by benedict-w** [comment]
+1 for being able to customize the trix toolbar

**Comment by riptin** [comment]
I mean how hard is it to make the Trix field take the names of the fields that you want to hide?

**Comment by jringeisen** [comment]
I recently wrote a blog article on how to do this. I needed the ability to use h2 subheadings so I went the Custom Tool route.

https://jonathonringeisen.com/blogs/customizing-the-trix-toolbar-in-laravel-nova-to-add-h2-subheadings
