### ISSUE TITLE
Delete a resource > translate resource name

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#1476]
Would like to see the possibility to translate the resource name when deleting it. Right nog when a user selects one or more resources to delete, the modal shows a generic:

**Delete resource**
"Are you sure you want to delete this resource?" /
"Are you sure you want to delete the selected resources?"

Would be great if it was something like this:

**Delete :resource(s)**
"Are you sure you want to delete this :resource?" /
"Are you sure you want to delete the selected :resources?"

Singular and plural names are already in the resource and a fallback could be provided to the generic words resource /resources if needed. I understand it can create problems with some resources with a strange sentence, but this can be avoided by using the generic form.

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
