### ISSUE TITLE
Place coordinates are only 4 digits long

### ISSUE THREAD

**Issue by LorensoD** [laravel/nova-issues#1477]
Place field coordinates are only 4 digits long. I require more accuracy in my project and want them to be at least 6 digits in length.

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by pzmarzly** [comment]
4 digits accuracy means that the error is [less than 12 meters](https://en.wikipedia.org/wiki/Decimal_degrees). But that probably doesn't matter, as Algolia Places [accuracy is much worse](https://github.com/algolia/places/issues/500) (about 1 km of error). You can test it [on this demo page](https://community.algolia.com/places/examples.html#displaying-on-a-map).
