### ISSUE TITLE
Custom resource views 

### ISSUE THREAD

**Issue by Pamposgsk** [laravel/nova-issues#1478]
Hi,
Is there a possibility to hide or delete the details card in a resource detail page.I would like only to display the related table...
Thanks in advanced

**Comment by devfrey** [comment]
If you want to hide the view button, create a model policy:

```php
class MyModelPolicy
{
    public function view(User $user, MyModel $model)
    {
        return false; // This hides the 'view' button
    }
}
```

**Comment by davidhemphill** [comment]
@Pamposgsk Sorry, not at this time.
