### ISSUE TITLE
Npm run dev error

### ISSUE THREAD

**Issue by rosen91** [laravel/nova-issues#1481]
- Laravel Version: 5.8
- Nova Version: 2.0
- Operating System and Version: Mac OSX Mojave

### Description:
When i run `npm run dev` in the "Nova" folder (To enable dev-tools) i get a Unexpected token error, i've seen other users have the same issue but no solution or fix?

### Steps To Reproduce:
cd ./vendor/laravel/nova
mv webpack.mix.js.dist webpack.mix.js
npm install
npm run dev

![image](https://user-images.githubusercontent.com/7423103/55100879-2e786e00-50c3-11e9-8bf0-4bebb0bdb9e8.png)

Note: It works when run outside the Laravel project, but as soon as it's moved into the Laravel project and setup accordingly i get this error

**Comment by davidhemphill** [comment]
I'm sorry, but I don't have enough information to reproduce your issue.

**Comment by VAMPIIRE** [comment]
Same problem. Did you found how to fix it?
