### ISSUE TITLE
Update latest Nova v2.0.1 didn't take effect

### ISSUE THREAD

**Issue by akmalelias** [laravel/nova-issues#1482]
- Laravel Version: 5.8.8
- Nova Version: 2.0.0
- PHP Version: 7.3.1
- Operating System and Version: Windows 10 Enterprise
- Browser type and version: Google Chrome v73.0.3683.86

### Description:
I tried to update my Laravel Nova by running these commands:
1. `composer update` (can see this message v2.0.0 => v2.0.1)
2. `php artisan nova:publish`

But when I log in to my Nova application, at the footer still showing v2.0.0 and when I try run this `Nova::version();` in the tinker also still showing v2.0.0.

And I have tried with `php artisan nova:publish --force` follow by `php artisan view:clear` as well but still v2.0.1 didn't take effect.

Any idea?

### Steps To Reproduce:
1. Using Laravel v5.8.8 & Nova v2.0.0
2. Run `composer update`
3. Run `php artisan nova:publish`
4. Verify from the footer in the Nova admin panel or php artisan tinker

**Comment by gjsman** [comment]
I think that either the download link is pointing to 2.0.0 or that 2.0.1 did take effect but that the developer forgot to up the version number. I’m going to do a git comparison soon.

**Comment by devfrey** [comment]
I can confirm the version constant in the `Nova` class wasn't updated. It still says `2.0.0` in the `2.0.1.` source.

**Comment by gjsman** [comment]
Okay... he's released a new 2.0.1. With changes. Which still says it is 2.0.0. 😕

**Comment by davidhemphill** [comment]
This was an oversight with the release. Fixed in the next version. 👍
