### ISSUE TITLE
Get Started View Typo

### ISSUE THREAD

**Issue by liakos21** [laravel/nova-issues#1483]
- Laravel Version: 5.8.*
- Nova Version: 2.0.1
- PHP Version: 7.2
- Operating System and Version: Windows.10
- Browser type and version: Google Chrome.73

### Description:
At Get Started section, under Lenses there is a typo in "Need to customize a resource list a little more than a filter can provider?"
-provider should be provide

### Steps To Reproduce:
Just follow Nova documentation and install Nova Application.

**Comment by devfrey** [comment]
You can submit a PR to Nova's documentation: https://github.com/laravel/nova-docs

**Comment by liakos21** [comment]
But this is not in the docs. It is in the app

![image](https://user-images.githubusercontent.com/37932066/55239689-dfa41300-523f-11e9-81d5-10158bed1eb7.png)

**Comment by devfrey** [comment]
Ah, but you said 'follow Nova documentation' :)

Yes, there's definitely a typo there.

**Comment by liakos21** [comment]
Yeah I meant to say, follow the documentation to install the application. Will edit this in case it is confusing.

**Comment by davidhemphill** [comment]
Thanks for the heads up. Fixed in next verion. 👍
