### ISSUE TITLE
Order By on Relatable Query

### ISSUE THREAD

**Issue by JordanDinsdale** [laravel/nova-issues#1484]
Hi, I need to apply an order on a relatable query in Laravel Nova.

I've tried everything on this page [https://github.com/laravel/nova-issues/issues/156](https://github.com/laravel/nova-issues/issues/156) and can't get any of the methods detailed to work with my application.

I have 3 models significant to this problem; Event, Brand and Vehicle.

Events Belong To Many Brands | Brands Belong To Many Events
Brand Has Many Vehicles | Vehicles Belong To a Brand
Event Belongs To Many Vehicles | Vehicles Belong To Many Events

When a user creates an Event, they then go on to choose Brands associated with that Event.

This is facilitated by putting the below line in the fields function in my Nova Event Resource.

`BelongsToMany::make('Brand')->sortable(),`

Once a user has attached associated Brands, they then go on to attach associated Vehicles.

The list of Vehicles is populated using a relatable query that I have in my Nova Event Resource;

```
public static function relatableVehicles(NovaRequest $request, $query)
{

    $event = $request->findResourceOrFail();

    $brand_ids = [];

    foreach($event->brand as $brand) {
        $brand_ids[] = $brand['id'];
    }

    return $query->whereIn('brand_id', $brand_ids);

}
```

Now when I go to attach a Vehicle, it is populated only by Vehicles that are related to the Brands attached to the Event.

The problem is that the options in the select box provided are ordered by the title. 

I have the below in my Vehicle resource, which I think is where the problem stems from;

`public static $title = 'model';`

But obviously I need that in the Resource so that the select box displays appropriately.

Does anyone know how I can order by something other than title instead? I'm trying to order by brand_id.

**Comment by devfrey** [comment]
What's wrong with applying an `orderBy` to the query in your relatable query? That should work, really.

**Comment by JordanDinsdale** [comment]
It doesn't.

I've tried changing the above code to;

`public static function relatableVehicles(NovaRequest $request, $query)
    {

        $event = $request->findResourceOrFail();

        $brand_ids = [];

        foreach($event->brands as $brand) {
            $brand_ids[] = $brand['id'];
        }

        return $query->whereIn('brand_id', $brand_ids)->orderBy('brand_id','asc');

    }`

I also changed `public static $title = 'model';`

to

`public function title()
    {
        return $this->model . ' - ' . $this->brand_id;
    }`

just to illustrate how it isn't working. I've attached the result below;

![Screen Shot 2019-04-03 at 17 36 39](https://user-images.githubusercontent.com/24391738/55496535-3a21e280-5637-11e9-8551-401538e7e766.png)

**Comment by christophrumpel** [comment]
Anything new here? I'm facing the same problem.: `orderBy()` is not working when overriding the `relatableQuery` method. I guess the order from there is being overwritten later?

Also tried to override the `applyOrderings` method, but still no ordering.

**Comment by christophrumpel** [comment]
@dillingham showed me that the order is set in the `AttachableController`. So setting the `order` inside the relatableQuery method does not work =/ I'm also looking for a solution since this is very important for my client. Haven't found a good one yet.

**Comment by jbrooksuk** [comment]
This issue relates to an older version of Nova. It's possible that this bug has been fixed in recent versions. If you're still experiencing this in the latest version of Nova, please re-open this ticket, thanks!

**Comment by winter-ice** [comment]
Have same issue.I think is because of Nova re-sorted related resource by hard code.

See 

**Laravel\Nova\Http\Controllers\AssociatableController**
```
 public function index(NovaRequest $request)
    {
        $field = $request->newResource()
                    ->availableFields($request)
                    ->firstWhere('attribute', $request->field);

        $withTrashed = $this->shouldIncludeTrashed(
            $request, $associatedResource = $field->resourceClass
        );

        return [
            'resources' => $field->buildAssociatableQuery($request, $withTrashed)->get()
                        ->mapInto($field->resourceClass)
                        ->filter->authorizedToAdd($request, $request->model())
                        ->map(function ($resource) use ($request, $field) {
                            return $field->formatAssociatableResource($request, $resource);
                        })->sortBy('display')->values(),
            'softDeletes' => $associatedResource::softDeletes(),
            'withTrashed' => $withTrashed,
        ];
    }
```

**Comment by lab08tonci** [comment]
@JordanDinsdale, Can you reopen this bug, as it is still valid at the latest Nova version (v2.6.1)
The reason is what @winter-ice have stated in the previous comment.

The order is hardcoded and no mater what we do, it will not change.

**Comment by JordanDinsdale** [comment]
> This issue relates to an older version of Nova. It's possible that this bug has been fixed in recent versions. If you're still experiencing this in the latest version of Nova, please re-open this ticket, thanks!

Hi, I don't really think "It's possible that this bug has been fixed in recent versions" is a good enough reason to close a ticket that's occuring in software that has been bought and paid for. 

Why didn't you check if it had been fixed, then report back...? 

@lab08tonci, @jbrooksuk, or anyone else;
How do I reopen a ticket? This thread seems to suggest I can't...
https://github.com/isaacs/github/issues/583

**Comment by jbrooksuk** [comment]
@JordanDinsdale we get a lot of tickets and they take a lot of time. Help us, help you.

**Comment by JordanDinsdale** [comment]
> @JordanDinsdale we get a lot of tickets and they take a lot of time. Help us, help you.

I am really trying, but people are closing tickets without good reason, and not telling me how I can reopen them when asked... What exactly is it that you're suggesting I should do about these things?

**Comment by jbrooksuk** [comment]
@JordanDinsdale until you said that you were unable to reopen the issue, I was unaware that it was the case. We reserve the right to manage the issues at our discretion. As with all tickets, we're always reading them and keeping an eye on them.

**Comment by JordanDinsdale** [comment]
@jbrooksuk Thanks James, I look forward to seeing what progress you can make regarding this

**Comment by reppair** [comment]
Yeah, I also can't apply my custom `orderBy` to the relatable query.. :(

**Comment by schakko** [comment]
# Quick fix
As a quick fix I am doing the following:

1. Copy *nova\src\Http\Controllers\AttachableController.php* to *app\Http\Controllers\Nova\AttachableController.php*, don't forget to update the namespace of the copied *AttachableController*
2. Simply remove the sortBy statement in *app\Http\Controllers\Nova\AttachableController.php*:
```
        return [
            'resources' => $field->buildAttachableQuery($request, $withTrashed)->get()
                        ->mapInto($field->resourceClass)
                        ->filter(function ($resource) use ($request, $parentResource) {
                            return $parentResource->authorizedToAttach($request, $resource->resource);
                        })
                        ->map(function ($resource) use ($request, $field) {
                            return $field->formatAttachableResource($request, $resource);
                        })

                // ignore Laravel's Collecting::sortBy, @see https://github.com/laravel/nova-issues/issues/1484
                //->sortBy('display', SORT_NATURAL | SORT_FLAG_CASE)
                ->values(),
            'withTrashed' => $withTrashed,
            'softDeletes' => $associatedResource::softDeletes(),
        ];
```
3. In your *app\Providers\NovaServiceProvider.php*, set an alias for your own *AttachableController*:
```
class NovaServiceProvider extends NovaApplicationServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {

        parent::boot();

        // map Nova's AttachableController to our own instnace
        $this->app->alias(
            \App\Http\Controllers\Nova\AttachableController::class,
            \Laravel\Nova\Http\Controllers\AttachableController::class
        );
    }
}
```

4. In your *relatableQuery*, define the sorting columns:
```
    public static function relatableQuery(NovaRequest $request, $query) {
        $query->getQuery()->orders = [['column' => 'type', 'direction' => 'asc'], ['column' => 'name', 'direction'  => 'asc']];

        return $query;
    }
```

# Possible long term fix
As a reasonable fix I suggest to wrap the 
```
$field->buildMorphableQuery() 
```
into a fascade like
```
MorphableCollection::sort($field->buildMorphableQuery()....)
```
and
```
AssociatableCollection::sort($field->buildMorphableQuery()....)
```
The developer can either use the default sorting algorithm (*sortBy('display')*) or overwrite the sorting algorithm.

**Comment by elijahworkz** [comment]
This issue still exists (Nova 2.9.4)
adding ->orderBy() makes no difference and in my case - creates an error of ambiguous column name

I'm trying to create a filter like this:
`return $query->join('campaigns', 'campaigns.id', '=', 'campaign_id')->where('campaigns.brand_id', $value);`
this throws an error
`return $query->join('campaigns', 'campaigns.id', '=', 'campaign_id')->where('campaigns.brand_id', $value)->orderBy('pages.id');` makes no difference

**Comment by tushar-kharmate** [comment]
Hello @jbrooksuk, This issue still exists in Nova v3.6. 

`public static function relatableQuery(NovaRequest $request, $query)
    {
        return $query->orderBy('sort_order','asc');
    }`

Can you Provide any updates on this issue? It will be helpful.

**Comment by jbrooksuk** [comment]
Sorry for the lack of updates.

In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by joselara** [comment]
Hey can we get an update on sorting relatable queries. I don't think it's a new feature but a bug.  Thanks.

**Comment by webwizard0822** [comment]
Have same issue. unfortunately not found a solution yet. 
/**
     * Apply the filter to the given query.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @param  mixed  $value
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function apply(Request $request, $query, $value)
    {
        
        if($value == 1){
            return $query->orderBy('xxx', 'ASC');
        }else{
            return $query->orderBy('xxx', 'DESC');
        }
    }
Filter is not working in all. 

Any solution for that?

**Comment by latwelve** [comment]
Is there any progress on this bug please?

**Comment by reppair** [comment]
I could get rid of all the custom BS queries I've wrote in order to achieve my sorting in several resources.. getting used to it. :)

**Comment by crynobone** [comment]
https://nova.laravel.com/docs/3.0/resources/relationships.html#disable-ordering-by-title

**Comment by reppair** [comment]
> https://nova.laravel.com/docs/3.0/resources/relationships.html#disable-ordering-by-title

Hi @crynobone, seems like there is no `#disable-ordering-by-title` section on that page.

**Comment by crynobone** [comment]
![Screenshot_20210609-181953.jpg](https://user-images.githubusercontent.com/172966/121337622-50cacf00-c94f-11eb-8002-f6ace3c06ff0.jpg)
