### ISSUE TITLE
Computed fields callback is executed on edition

### ISSUE THREAD

**Issue by oliverpool** [laravel/nova-issues#1485]
- Laravel Version: v5.8.4
- Nova Version: v2.0.1
- PHP Version: 7.3.3
- Operating System and Version: Archlinux
- Browser type and version: Chromium

### Description:

This is issue is related to #902.

I have the following computed field in my Unit resource:

```php
public function fields(Request $request)
{
    return [
        ID::make()->sortable(),

        BelongsTo::make(__('Building'), 'building', Building::class),

        Text::make(__('Address'), function () {
            return $this->building->address;
        })->onlyOnDetail(),
    ];
}
```

Such Units are created by my users. When I want to **modify** it in Nova, I get the following error:

> Trying to get property 'address' of non-object.

When I comment out the line in my callback every thing works fine.

## Issues

- The relationship does not seem to be resolved on edition (making the computed property fail)
- Why is Nova trying to resolve a computed field's callback in the creation/edition form even though it's not used?

**Comment by dkulyk** [comment]
It must be fixed in 2.0.1

**Comment by rikless** [comment]
@dkulyk In the release note, 2.0.1 is only security release

**Comment by dkulyk** [comment]
Not only.
https://twitter.com/laravelphp/status/1110947519599538176

**Comment by rikless** [comment]
Don't know why it's not in the release note, this is unbelievable.

I was waiting for all you PR to be released.

Thank you for all your work and support on Nova @dkulyk 

Really appreciate.

**Comment by oliverpool** [comment]
@dkulyk thanks, I will try to update next week and close this issue if the new release fixed it!

**Comment by oliverpool** [comment]
@dkulyk unfortunately, I still have the same error

**Comment by dkulyk** [comment]
Worked on it.

**Comment by devfrey** [comment]
This bug is still present in 2.0.1. Using a computed field to display an attribute from a relationship breaks the code, because it's somehow executed before the created model is saved for the first time.

**Comment by davidhemphill** [comment]
You always need to check for the existence of the resource before using a value from it. The resource is now passed to the Computed fields callback for your convenience.

**Comment by oliverpool** [comment]
@davidhemphill So you mean that it is totally normal, that Nova calls the computed fields on Model update? (even when this computed field is not used at any point during the update)

And then it is also normal, that the relationships are not resolved before the computed fields is called, on Model update ?

**Comment by gerardnll** [comment]
> You always need to check for the existence of the resource before using a value from it. The resource is now passed to the Computed fields callback for your convenience.

That should be in the docs. I don't expect a computed property to receive an empty model, less in the updating step.
