### ISSUE TITLE
Nova guard not registered when nova is not serving

### ISSUE THREAD

**Issue by markwalet** [laravel/nova-issues#1487]
The `authorization()` method is only called in a `Nova::serving()` callback in `NovaServiceProvider`.

This doesn't make it possible to use this gate to determine if I should show the user a link to Nova.

I compared it with Laravel Horizon. The service provider of Laravel Horizon does alway call the `authorization()` method on boot. I think this should also be the case with Nova.

Just for the record, I know how to change it myself. I'm currently just overriding the method. But I think the default behaviour for nova should change.

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by pramanikriju** [comment]
@markwalet can you elaborate on how you used the Gate elsewhere?

**Comment by markwalet** [comment]
Somewhere in my navigation blade file:

```
@can('viewNova')
    <a href="/nova">Nova Dashboard</a>
@endcan
```
