### ISSUE TITLE
Using computed value on Currency is comflicted with Currency::format

### ISSUE THREAD

**Issue by BinotaLIU** [laravel/nova-issues#1488]
- Laravel Version: `5.8.8`
- Nova Version: `2.0.1`
- PHP Version: `7.3`
- Operating System and Version: `5.0.4-arch1-1-ARCH`
- Browser type and version: `Firefox 66`

### Description:

Using computed value on a Currency field will make the `format` method stop working.

### Steps To Reproduce:

Define the following field:

```php
<?php

return [
    Currency::make('Currency Test', function () { return 1.7; })->format('$%.0n'),
];
```

expected shows `$1`, shows `1.7`

**Comment by dkulyk** [comment]
Format don't work on computed fields. You need to prepare value by yourself.
