### ISSUE TITLE
Image Field not showing image in public/storage folder.

### ISSUE THREAD

**Issue by wemersonrv** [laravel/nova-issues#1490]
- Laravel Version: 5.8.8
- Nova Version: 2.0.1
- PHP Version: 7.2.11
- Operating System and Version: Windows 10 64 Bits
- Browser type and version: Google Chrome 73.0.3683.86 64 bits

### Description:
Image field not show on browser even after link storage folder to public folder.

### Steps To Reproduce:
1. Create an Image Field on resource: `Image::make('Featured Image')->disk('public'),` and upload first image.
2. Link storage to public folder: `php artisan storage:link`

If you see here: https://prnt.sc/n6dgmw it shows the image exists on both private and public storage folders... but image address is not showed. See here: https://prnt.sc/n6dhct

**Comment by davidhemphill** [comment]
There's not enough information here to accurately reproduce your issue. Feel free to post again when there's more specific instructions to replicate your problem.
