### ISSUE TITLE
translation with params in card vue files

### ISSUE THREAD

**Issue by lichtner** [laravel/nova-issues#1492]
maybe this is bug, I am not sure...

in `Card.vue` this works:
```
{{ __('Welcome') }}
```

but in `Card.vue` neither of these works:
```
{{ __('Welcome, :NAME', ['name' => 'John']) }}
{{ __('Welcome, :NAME', {'name': 'John'}) }}

```
Is it possible to use params in translation strings in `Card.vue` files? How?

**Comment by davidhemphill** [comment]
Nova will only use the parameters if there's an existing entry in `en.json` that matches.
