### ISSUE TITLE
Pagination stays disabled

### ISSUE THREAD

**Issue by Cannonb4ll** [laravel/nova-issues#1494]
- Laravel Version: 5.8.9
- Nova Version: 2.0.1
- PHP Version: 7.2
- Operating System and Version: Ubuntu 16
- Browser type and version: Chrome 73.0.3683.86

### Description:
Since the new update (2.0.*) my pagination stays disabled, this has happend for each resource I have in Nova. I have not changed any logic in my code and followed the upgrade guide accordlingly.

![img](https://imgshare.io/images/2019/04/03/Screen-Shot-2019-04-03-17-50-14.24.png)

I have tried to reinstall nova, and forcing the assets to be published. 

Even more strange is that I have `'pagination' => 'simple',` pagination set to **simple** in nova.php config file, and it is still rendering links. The config file has not been cached, I have cleared it.

**Comment by jesperlindstrom** [comment]
Experiencing the same.

**Comment by dkulyk** [comment]
`php artisan nova:publish`

**Comment by Cannonb4ll** [comment]
@dkulyk Please read my initial issue better:

```
I have tried to reinstall nova, and forcing the assets to be published.
```

**Comment by dkulyk** [comment]
Compare your nova assets with package assets.

**Comment by Cannonb4ll** [comment]
I have even copied over the assets from the private repository manually, no dice.

**Comment by dkulyk** [comment]
Has mix-manifest.json similar content?
```json
{
    "/app.js": "/app.js?id=19fb4a6ed48aba1680e2",
    "/app.css": "/app.css?id=79e1b8e6ee9adbd75e7b",
    "/vendor.js": "/vendor.js?id=9e454f3261418eb9bca1",
    "/manifest.js": "/manifest.js?id=2d315777967b6001bcf1"
}
```

**Comment by Cannonb4ll** [comment]
```
{
    "/app.js": "/app.js?id=19fb4a6ed48aba1680e2",
    "/app.css": "/app.css?id=79e1b8e6ee9adbd75e7b",
    "/vendor.js": "/vendor.js?id=9e454f3261418eb9bca1",
    "/manifest.js": "/manifest.js?id=2d315777967b6001bcf1"
}
```

This is from my project copied, so yes it matches.

**Comment by dkulyk** [comment]
It's strange. I have pagination in resources and lenses. Pagination need to retrieve quantity of resources for working. 
Does `/nova-api/resource/count` work well?

**Comment by Cannonb4ll** [comment]
Yes, I checked network tab and it is returning the result that its displaying in the footer of the table.

What even more strange is, I have lenses as wel and that resource displays the 'simple' pagination, and not the links as the main is displaying.

**Comment by dkulyk** [comment]
You have assets from 2.0.0. In 2.0.0 lenses did not have pagination type. Try to rebuild assets.

**Comment by Cannonb4ll** [comment]
How do you suggest I rebuild assets? I just copied over the newest public assets and put them inside vendor/nova folder. Still the same result.

**Comment by davidhemphill** [comment]
Make sure you've republished your assets using `artisan nova:publish --force` and check back in after that.

**Comment by jesperlindstrom** [comment]
The issue remains after force publishing for me.

**Comment by Cannonb4ll** [comment]
@davidhemphill Still experiencing the same, even forcing them. Same as @jesperlindstrom

**Comment by Cannonb4ll** [comment]
Have also tried to re-install nova completely, no dice. Should I re-create this issue since its closed?

**Comment by jesperlindstrom** [comment]
@Cannonb4ll I found the cause for me at least. It was the [nova-breadcrumbs](https://github.com/chris-ware/nova-breadcrumbs) package. Do you happen to use it? Everything works when I disable the tool, so not an issue with Nova itself. They have an issue about it here: https://github.com/chris-ware/nova-breadcrumbs/issues/16, and seems like there's an update that fixes it.

**Comment by Cannonb4ll** [comment]
@jesperlindstrom Amazing, this is why the community is so important. Thank you, it indeed completely solved it after updating to v1. 🎉
