### ISSUE TITLE
Is it intentional that readonly() requires a parameter? 

### ISSUE THREAD

**Issue by yehudahkay** [laravel/nova-issues#1495]
If readonly() is passed without an argument could it receive true? That would make it work like the other methods in the framework. This wasn't immediately clear to me from the documentation for readonly().

Thank you!

**Comment by dkulyk** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to #nova on Laravel's Discord or #nova on the Larachat Slack Channel.

**Comment by yehudahkay** [comment]
Well it seems like a bug...You guys are very aggressive closing issues

**Comment by yehudahkay** [comment]
Not clear why need to call readonly(true) no other methods require that

**Comment by yehudahkay** [comment]
And its not really written in the documentation clearly

**Comment by dkulyk** [comment]
This has been fixed and will be included in the next release.
