### ISSUE TITLE
Incorrect relationship pagination behaviour

### ISSUE THREAD

**Issue by rdarcy1** [laravel/nova-issues#1496]
- Laravel Version: 5.8.8
- Nova Version: 2.0.1
- PHP Version: 7.2
- Operating System and Version: MacOS 10.14.3
- Browser type and version: Firefox 66.0.2

### Description:
Possibly a recurrence of #1408, relationship pagination is not appearing correctly for HasMany relationships.

For `simple` pagination, the content of the table appears correctly but the numbering is not:

Page 1

<img width="1169" alt="Screenshot 2019-04-04 at 21 32 31" src="https://user-images.githubusercontent.com/15962421/55586578-37032100-5721-11e9-9c99-ca90a3b60029.png">

Page 2

<img width="1168" alt="Screenshot 2019-04-04 at 21 32 38" src="https://user-images.githubusercontent.com/15962421/55586590-3cf90200-5721-11e9-9c57-72c97826083b.png">

Page 3

<img width="1171" alt="Screenshot 2019-04-04 at 21 32 45" src="https://user-images.githubusercontent.com/15962421/55586598-41251f80-5721-11e9-80f3-ae8b168b90e7.png">

For `links` pagination, no pages are available and I'm stuck viewing the first page only:

<img width="1165" alt="Screenshot 2019-04-04 at 21 29 08" src="https://user-images.githubusercontent.com/15962421/55586425-ceb43f80-5720-11e9-8d3f-bdfe443aa3c6.png">

### Steps To Reproduce:
Within Nova resource use default HasMany field:
```php
public function fields(Request $request)
{
    return [
        HasMany::make('Versions'),
    ];
}
```

#### Edit

Looks like it's got something to do with the AJAX call coming from Vue, where the `perPage` value differs between the front and back end.

On my resource class the page size is set to 5. However, the request from Vue shows 25:

<img width="213" alt="Screenshot 2019-04-05 at 10 40 48" src="https://user-images.githubusercontent.com/15962421/55618862-723c3900-578f-11e9-8099-62f78a374d3a.png">

**Comment by marcreichel** [comment]
+1 I'm having the same issue with the links pagination

**Comment by tumispro** [comment]
This was fixed in https://github.com/laravel/nova-issues/issues/1408 and should be closed. 

If it still doesn't work in 2.0.1 this should do the trick:

`artisan nova:publish --force`

**Comment by rdarcy1** [comment]
Re-publishing solved it, thanks.
