### ISSUE TITLE
[Bug] Action selector is not shown on details view of resource when all fields are hidden

### ISSUE THREAD

**Issue by chescos** [laravel/nova-issues#1497]
### Description:

The action selector is not shown on the details view of a resource when all fields are hidden through `hideFromDetail()`.

### Steps To Reproduce:

1. Hide all fields of a resource through `hideFromDetail()`
2. Add an Action to the resource
3. Visit the details view of the resource
4. There's no Action selector

**Comment by davidhemphill** [comment]
I'm not sure I'd consider this a bug. If you don't want any fields to show, then the detail panel (with its toolbar, etc) won't show. That's by design. It seems like you'd need at least one field to know what resource you're on anyways. Show at least one field and get the action bar back. :-)

**Comment by chescos** [comment]
@davidhemphill I'm showing one field just to get the action bar back but it's just a waste of space. I made a resource tool for more advanced user profiles, so I don't need that one field. Take a look at this example:

![Selection_639](https://user-images.githubusercontent.com/12296880/55642451-c9163280-57d0-11e9-8a0a-caf1b549ebbb.png)

**Comment by chescos** [comment]
If it's by design, how about still showing the action bar as long as the resource has a resource tool?
