### ISSUE TITLE
404 page has a scrollbar that reveals sidebar content

### ISSUE THREAD

**Issue by chescos** [laravel/nova-issues#1498]
### Description:

The 404 page has a scrollbar if the sidebar has enough resources, you can just scroll down and see the sidebar content.

Screenshot:

![Selection_640](https://user-images.githubusercontent.com/12296880/55642768-b6502d80-57d1-11e9-8a63-716464637ffe.png)

### Steps To Reproduce:

1. Add enough resources to the sidebar to get scrolling.
2. Navigate to http://your.app/nova/404
3. Scroll down

**Comment by SerjoA** [comment]
also have same issue

**Comment by tharindu-abans** [comment]
Same for the 403 page as well

![workflow test](https://user-images.githubusercontent.com/48512374/57347123-d6776180-716e-11e9-89e2-166fc1e6fd29.png)

**Comment by jbrooksuk** [comment]
Sorry, but we are unable to debug your issue without a reproducible code example. Once you provide that we can open this up again.

**Comment by chescos** [comment]
@jbrooksuk You just need to add enough Resources to the sidebar so that the page gets a scrollbar. This gets much easier when you simply make your browser window smaller (reduce the height). Then navigate to a Nova URL that doesn't exist (e.g `http://your.app/nova/does-not-exist`). On the 404 page that shows up, you'll still be able to scroll down and when you do so, then you'll see the sidebar.

**Comment by jbrooksuk** [comment]
Got it, thanks for explaining.

**Comment by jbrooksuk** [comment]
I've pushed a fix for this.
