### ISSUE TITLE
database queue with nova project. Not works

### ISSUE THREAD

**Issue by wemersonrv** [laravel/nova-issues#1500]
- Laravel Version: 5.8
- Nova Version: 2.0.1
- PHP Version: 7.2
- Operating System and Version: Windows 10 64 bits
- Browser type and version: Chrome 73.0.3683.86

### Description:
Whn crate and send email notifications it works fine. But when try to implements ShouldQueue in notifications and configure queue database not works. when a job is fired, the **jobs** table in project database is filled with the notifications messages, but they was not sent the email... and if i just change ,env `QUEUE_CONNECTION` from **database** back to **sync** it works.

Test with **redis** too and get same problem.

### Steps To Reproduce:
Just configure a database queue and make some notification to implements ShouldQueue and make queues works.

**Comment by davidhemphill** [comment]
Closing because there's nothing specific to Nova here. 

Hint: you have to be running a queue worker for the database queue driver to work.

**Comment by dkulyk** [comment]
@wemersonrv You need to [run queue worker](https://laravel.com/docs/5.8/queues#running-the-queue-worker)

**Comment by wemersonrv** [comment]
Hi, yep i used it.. but not works.

Today i've tried a couple of times and not works... and create a new project and start first with queues and works. So reimplements my features and now works. Tx!
