### ISSUE TITLE
Actions: "select all" vs "select all matching" different attributes per model

### ISSUE THREAD

**Issue by TonnyORG** [laravel/nova-issues#1501]
- Laravel Version: 5.7.28
- Nova Version: 2.0.1
- PHP Version: 7.2.9
- Operating System and Version: Ubuntu 18.04.1 LTS
- Browser type and version: Chrome 73

### Description:

I am using a **Lens** which has an **Action** and the main problem happens trying to perform an action selecting all items of the current page VS all items matching.
![Imgur](https://i.imgur.com/fPpsTsl.png)

Tthe main problem is the `attributes` array on each resulting model. If you click on "`Select All Matching`" instead, the available `attributes` array is only scoped with the fileds defined in the Lens (which is **the expected result**). In addition to this, there is an small issue here which is that it doesn't return the whole collection, instead only about 20 records are returned.
![Imgur](https://i.imgur.com/GpISFhl.png)

However, when you have "`Select All`" checked it does not work properly, the attributes available on each model are the actual model attributes instead of the "fields" defined in your Lens class.
![Imgur](https://i.imgur.com/IMnz7qU.png)

### Steps To Reproduce:

1- Create a Lens with custom fields:
```
class Amazing extends Lens
{
    public $name = 'Amazing';

    protected static function columns()
    {
        return [
            'main.id',
            'main.descripcion',
            DB::raw('SUM(main.cantidad) as cantidad'),
            DB::raw('SUM(main.cantidad * main.precio_unitario) as venta'),
        ];
    }

    public static function query(LensRequest $request, $query)
    {
        return $request->withOrdering($request->withFilters(
            $query->select(self::columns())
                  ->join(...)
                  ->join('...')
                  ->orderBy('...', 'desc')
                  ->groupBy('...')
        ));
    }

    public function fields(Request $request)
    {
        return [
            ID::make('ID')->sortable(),
            Text::make('Descripcion'),
            Number::make('Cantidad'),
            Number::make('Venta', 'venta', function ($value) {
                    return '$'.number_format($value, 2);
                }),
        ];
    }

    public function filters(Request $request)
    {
        return [
            // All your filters...
        ];
    }

    public function actions(Request $request)
    {
        return [
            new \App\Nova\Actions\ExportAsPdf,
        ];
    }
}
```

2- Create your `Action`:
```
class ExportAsPdf extends Action
{
    use InteractsWithQueue, Queueable, SerializesModels;

    public function handle(ActionFields $fields, Collection $models)
    {
dd(array_keys($models->first()->getAttributes()));
    }

    public function fields()
    {
        return [];
    }
```

3- Play around the lens action checking "Select All" vs "Select All Matching".

**Comment by davidhemphill** [comment]
I don't understand what your issue is. What problem is this actually causing in your code?

**Comment by milewski** [comment]
I guess what he was trying to do was to export the model as PDF, but when the data came from `select all` it would include some columns that were included from his `->joins()` vs the whole model data disregarding his `joins` when selecting from `select all matching` so his export would look very different depending on how he selected the resources
