### ISSUE TITLE
NovaRequest $request on appending file to formdata ,request has no fileon nova custom field

### ISSUE THREAD

**Issue by DERYKO** [laravel/nova-issues#1502]
- Laravel Version: #.#.#
- Nova Version: #.#.#
- PHP Version: #.#
- Operating System and Version: #.#
- Browser type and version: #.#

**Comment by DERYKO** [comment]
I have a nova custom field in  nova-components and on the formfield.vue i have an input for a file that i append to a formdata and in the fillAttributeFromrequest method i try to access the file but the NovaRequest does not have a file?

**Comment by jbrooksuk** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](https://larachat.co/).
