### ISSUE TITLE
Microsoft Edge Comparability: Select checkboxes

### ISSUE THREAD

**Issue by otrsw** [laravel/nova-issues#1505]
- Laravel Version: 5.7
- Nova Version: 1.3.2
- PHP Version: 7.2.2
- Operating System and Version: #.#
Windows 10 Home
- Browser type and version: 
Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134

### Description:
I am experiencing some Microsft Edge compatibility issues.  Some are marked as closed (#170) on Safari, but still is an issue on Edge. Specifically - the select checkboxes on the index view.

### Steps To Reproduce:
An index view with more than one resource. Click the down arrow to reveal the "Select All" and "Select All Matching" options.  When clicking the checkbox they are not selected.
(So desired functionality not working)

![image](https://user-images.githubusercontent.com/15993272/55792001-03791b80-5ac0-11e9-94d7-b357f19baf31.png)

Counter test by viewing the same page in Chrome and desired effect is achieved

![image](https://user-images.githubusercontent.com/15993272/55792120-3cb18b80-5ac0-11e9-9d01-2922b300ea9a.png)

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
