### ISSUE TITLE
Selected option on Select not registering. Validation keeps failing

### ISSUE THREAD

**Issue by otrsw** [laravel/nova-issues#1506]
Laravel Version: 5.7
Nova Version: 1.3.2
PHP Version: 7.2.2
Operating System and Version: #.#
Windows 10 Home
Browser type and version:
Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134
### Description:
I am experiencing some Microsft Edge compatibility issues. Specifically - the values selected in a Select field are not honored when creating/editing the resource.

### Steps To Reproduce:
Create any resource and add a Select field.
Add the required rule

```
 /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [

            Select::make('Client surname')->options([
                'bond' => 'Bond',
                'doe' => 'Doe',
                'Dont care' => 'Dont care',
            ])->rules('required'),

            ];
    }

```
Go to admin portal and Create a new resource.
Select an option in the field (selected "Doe" in the screenshot below)
Click "Create [Model name]"  button 
The required rule still fires and we are stuck...

![image](https://user-images.githubusercontent.com/15993272/55793449-37097500-5ac3-11e9-9190-85bfb43bc308.png)

To confirm this is a browser issue - repeat all steps in Chrome and all works as expected.

**Comment by tiagoraposeiraff** [comment]
I have detected the same issue. Works fine in Chrome but it's failing on Edge. 

My specs:
Laravel 5.8
Nova 2.0.1
PHP 7.1.23

**Comment by davidhemphill** [comment]
Thanks, will take a look.

**Comment by upopovic** [comment]
I had the same issue. It looks like the problem is in SelectControl.vue  
It listens for input, that not works in edge. When changed to listen for change it works fine.

**Comment by devfrey** [comment]
I'm experiencing the same problem in the Chrome test browser used by Dusk. Nova 2.0.1.

**Comment by victorpfm** [comment]
I've tried to fix it like here: https://github.com/laravel/nova-issues/issues/1578 but Nova stil isn't updating the select field value after being selected by Dusk.

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
