### ISSUE TITLE
BelongsTo in fields() on a MorphToMany

### ISSUE THREAD

**Issue by d8vjork** [laravel/nova-issues#1507]
- Laravel Version: 5.8.9
- Nova Version: 2.0.1
- PHP Version: 7.1
- Operating System and Version: Mac OS X Mojave
- Browser type and version: Chrome 73

### Description:
A short explanation about the problem, I need to relate the pivot table with a belongsTo relationship to evade all the enums (as much as possible) and being more flexible on this. 

I've a Media table which can be related to Video/Audio/etc (polymorphic one-to-many, which is called MediaRelatableRelationType), where I want to have a relation to MediaRelationType which is another table, this is all the code from the models:

**MediaRelationType:**

```
class MediaRelationType extends Model
{
    /**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = ['name'];
}
```

**Media:**

```
public function videos()
    {
        return $this->morphedByMany(Video::class, 'relatable', 'media_relations')
            ->using(MediaRelatableRelationType::class)
            ->withPivot(['relation_type_id']);
    }
```

**MediaRelatableRelationType:**

```
class MediaRelatableRelationType extends MorphPivot
{
    public function relation_type()
    {
        return $this->belongsTo(MediaRelationType::class);
    }
}
```

Finally get a error on attach page on Nova:

> Call to undefined method Illuminate\Database\Eloquent\Relations\Pivot::relation_type()

### Steps To Reproduce:

Going to attach a relation (the page to create/edit relations).

**Comment by jbrooksuk** [comment]
This issue relates to an older version of Nova. It's possible that this bug has been fixed in recent versions. If you're still experiencing this in the latest version of Nova, please re-open this ticket, thanks!
