### ISSUE TITLE
displayUsing() on BelongsTo field to doesn't seem to work with Laravel 5.8.11 and Nova 2.0.1

### ISSUE THREAD

**Issue by mikecornille** [laravel/nova-issues#1511]
Its works with 5.8.11 and Nova 2.0.0.   

When I try to use: 
`BelongsTo::make('Location')->displayUsing(function ($location_id) {
            return $location_id['city'];
}),`

...with nova 2.0.1 it doesn't work, 2.0.0 it worked.

**Comment by LorenzoSapora** [comment]
I just hit this, after upgrading. Very odd, considering 2.0.1 is only a minor bug fix, and from the changelog doesn't touch belongsto.

**Comment by jbrooksuk** [comment]
Confirmed in v2.0.9. This is because the `resolveForDisplay` method is overwritten to do nothing. I don't know why this is the case though.

**Comment by kgp43** [comment]
What is the status on this? It's still an issue.

**Comment by jbrooksuk** [comment]
The PR hasn't yet been merged. There's an outstanding query.
