### ISSUE TITLE
Attach model policy disables edit button for pivot

### ISSUE THREAD

**Issue by lpluto** [laravel/nova-issues#1512]
- Laravel Version: 5.8.11
- Nova Version: 2.0.1
- PHP Version: 7.3
- Operating System and Version: MacOS.10.14.2
- Browser type and version: Chrome 73

### Description:
I have a model with BelongsToMany relationship and pivot fields. I'm using a policy to attach only new elements (attachSubModel method). So when some subModel is already attached I will not display it on the list. 

The issue is that when I'm using this that way the edit button is not being displayed for this element on the model page, so that I can't edit pivot fields.

**Comment by jbrooksuk** [comment]
This issue relates to an older version of Nova. If you're still experiencing this in the latest version of Nova, please re-open this ticket, thanks!
