### ISSUE TITLE
Tabbed relations in details view

### ISSUE THREAD

**Issue by h-zone** [laravel/nova-issues#1516]
In example, i have a many relations in my model. I believe im not alone.
It is makes a many screens down of related data. A very much rows at each relation.
This is uncomfortable to view or operate with data.
I asking to implement a tabs for relations in details view.
Need more info?

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by h-zone** [comment]
Some additional request...

May be able to declare Panel as Tab ?
I think it is simplify development...

Today i have 6 relations and 4 panels at my detail page :)
It is terrible to scroll down this great cheneese wall.

If we have tabbed view, we will be able to minimize view this wall

**Comment by dkulyk** [comment]
https://github.com/dkulyk/nova-tabs

**Comment by h-zone** [comment]
> 
> 
> https://github.com/dkulyk/nova-tabs

RESPECT!

**Comment by h-zone** [comment]
> 
> 
> https://github.com/dkulyk/nova-tabs

i try it. partial functionality. but tnx.

**Comment by dkulyk** [comment]
https://novapackages.com/search?q=tab

**Comment by h-zone** [comment]
I resume issue.
In addition will be good if relation without tabView may be collapsible by clicking on relation name
