### ISSUE TITLE
Numer Size Validation Error

### ISSUE THREAD

**Issue by marcopscl** [laravel/nova-issues#1517]
- Laravel Version: 5.8.11
- Nova Version: 2.0.1
- PHP Version: 7.2.11
- Operating System and Version: Windows 10
- Browser type and version: Firefox 67.0b9

Hi, I have a Number Field with a size validator:

`Number::make('Price')->sortable()->rules('required', 'size:5'),`

it is a Integer in the Database
![imagen](https://user-images.githubusercontent.com/9339597/56061639-fb2b1580-5d37-11e9-94c3-d8b2d44d3bc7.png)

And I get a String validation
![imagen](https://user-images.githubusercontent.com/9339597/56061508-9ec7f600-5d37-11e9-9870-5eb9534af5c0.png)

Laravel Documentation say:

> size:value
> The field under validation must have a size matching the given value. For string data, value corresponds to the number of characters. **For numeric data, value corresponds to a given integer value**. For an array, size corresponds to the count of the array. For files, size corresponds to the file size in kilobytes.

[](https://laravel.com/docs/5.8/validation#rule-size)

I Think it is a Bug

**Comment by devfrey** [comment]
This is not a bug. Add the 'numeric' rule before the 'size'.

**Comment by davidhemphill** [comment]
Not a bug.

This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).
