### ISSUE TITLE
Remove With Deleted Checkbox

### ISSUE THREAD

**Issue by krunaldevs** [laravel/nova-issues#1518]
I want to remove this **With Deleted** Checkbox.
Can anyone having idea about this?

<img width="1363" alt="SS" src="https://user-images.githubusercontent.com/47715249/56081782-c6e65080-5e2e-11e9-826b-703e4ddc9ed7.png">

```
BelongsTo::make(__('Survey to Send'), 'survey', 'App\Nova\Survey')
                ->rules('required')
                ->searchable(),
```

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).
