### ISSUE TITLE
Computed fields haven't loaded the `$with` relations defined in the Nova resource on detail-page.

### ISSUE THREAD

**Issue by Livijn** [laravel/nova-issues#1519]
- Laravel Version: 5.8.11
- Nova Version: 2.0.1
- PHP Version: 7.3

### Description:
I am Using an accessor that depends on a relation. However fields haven't loaded the `$with` relations defined in the Nova resource on detail-page. They are loaded in the index-page.

### Steps To Reproduce:
Add `public static $with = ['media'];` to the Resource. Then add a computed field:
```
Text::make('Is relation loaded?', 'id')
    ->resolveUsing(function () {
        return $this->relationLoaded('media') ? 'yup': 'nah';
    }),
```

**Comment by jbrooksuk** [comment]
This issue relates to an older version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
