### ISSUE TITLE
Element UI  components for Laravel Nova

### ISSUE THREAD

**Issue by fat4lix** [laravel/nova-issues#152]
Hi there! I made some binding to Element UI for Nova.
I'm sorry I write about it here, just hope this will help someone

https://github.com/fat4lix/nova-element-ui

**Comment by zeroseed** [comment]
Maybe you want to publish it on novapackages.com ?
https://novapackages.com/

Btw great job ! 😃

**Comment by fat4lix** [comment]
@zeroseed Thanks!
Yes, i did https://novapackages.com/packages/nightkit/nova-element-ui

**Comment by clipvui2512** [comment]
What do you think about ant design  ?
https://ant.design/
32k star on github

**Comment by taylorotwell** [comment]
This repository is for tracking bugs. Feature requests may be emailed to Nova customer support.
