### ISSUE TITLE
Updating resource with attached photos - field is required error

### ISSUE THREAD

**Issue by elrufoelrufo** [laravel/nova-issues#1520]
- Laravel Framework 5.8.11
- Nova Version: 2.0.1
- PHP Version: PHP 7.2.15
- Operating System and Version: Mac
- Browser type and version: Google Chrome Versión 73.0.3683.103 

Hello,

When I try to update a resource that has an image previously attached to it, it gives an error saying "field is required."

The update form shows the thumbnail of image, but says "no file selected".

I'm able to access the resource image in my views and the file name is stored in the database, so I'm not sure why I am getting these errors. Am I missing something?

Please see screenshots:
### Steps To Reproduce: Update a laravel model with image which is required. 

![image](https://user-images.githubusercontent.com/14137306/56084578-38290200-5e35-11e9-8bde-8811bb89b4cc.png)

The issue #353 has not been resolved. 

Please. could you have a look into this?

Thanks. Regards.

**Comment by strebl** [comment]
I have the same problem.

**Comment by davidhemphill** [comment]
Please post the specific code that would trigger this error. There's not enough information to reproduce here.

**Comment by dkulyk** [comment]
You added 'required' to rules without checking current value. It's correct behavior. 
Validation checks only form data and doesn't know about current value.

If Image required you should to add 'required' to [creationRules](https://nova.laravel.com/docs/2.0/resources/validation.html#creation-rules)

**Comment by strebl** [comment]
@dkulyk I think thats not true.
That would allow you to remove the image on update.

@davidhemphill My code:
```php
Avatar::make('Bild', 'image')
    ->rules('required'),
```
If I edit a user without reuploading the image, I cant save.

**Comment by dkulyk** [comment]
@strebl All rules applied to the form. It is standard behavior on Laravel.

**Comment by bakerkretzmar** [comment]
@davidhemphill any particular code examples you want that would be helpful here? This is enough to do it for me on a blank new Nova install:

```php
Image::make('Image')->rules('required')
```

Upload an image, click "Update & Continue Editing," the resource saves normally, the page refreshes, and the image preview is displayed. Immediately click "Update & Continue Editing" again and the form is rejected with an error that the image field is required.

As described in #353, the field is submitted empty (actually as far as I can tell, isn't submitted at all) unless you click "Choose File" and upload an image. So if an image was uploaded previously, the form will be rejected even though the resource does actually already have the required image attached to it.

@dkulyk you're totally right this is standard in Laravel, but I don't think it's standard in Nova. In Nova, edit forms are usually pre-filled. When you edit a resource that already has a value for a given field, the value is pre-filled in the edit form and you can leave it there and submit right away with no errors, you don't have to re-fill every field on the resource from scratch on each update.

I think it makes sense to expect the same behaviour from the Image field: if a value (file) exists, it should be possible to update other values in the form and re-submit it without errors. As it stands, if an Image field is required the image file must be re-uploaded every time the resource is edited.

I might try to put together a PR that addresses this, it may be a bit beyond me though.

**Comment by dkulyk** [comment]
File field cannot be pre-filled.

**Comment by davidhemphill** [comment]
This doesn't seem like a bug. If you have an Image field with `rules('required')`, you are implicitly setting that for both create and update. You need to use the separate `createRules` and `updateRules` methods for this kind of validation.

**Comment by strebl** [comment]
@davidhemphill  So there is no way to prevent the deletion of an image unless I make an update rule that causes the image to have to be uploaded again and again?

**Comment by dkulyk** [comment]
@strebl Image does not delete if you not send image again.

**Comment by strebl** [comment]
I didn't say that. But I cant validate that the image is still there. You are able to delete it on edit, because there is a delete button under the image.

**Comment by dkulyk** [comment]
See https://github.com/laravel/nova-issues/issues/1520#issuecomment-489925222

**Comment by bakerkretzmar** [comment]
@dkulyk thanks for your help with this. The example in your comment doesn't work.

If the column storing the image URL is not nullable and you click "Delete" on the resource update form, Nova immediately displays an error about the `NOT NULL` constraint and the field remains filled—but the file is deleted, so the resource can be saved with an image link that is broken.

@davidhemphill sorry if we're missing something obvious here. Could you give an example of how we would set up an image field that (a) is required, so the resource cannot be saved/updated if the field is empty OR there's no existing image file, and (b) doesn't require the user to re-upload the image file, or touch the field at all, when updating other fields on a resource with an existing image? What would your `updateRules` look like? Or is this behaviour explicitly not supported?

Thanks!

**Comment by dkulyk** [comment]
@bakerkretzmar This is normal behavior. You are deleting an image - the field set to null.
You should to deny deleting an image.
```php
Image::make()
    ->deletable(false) // deny deleting
    ->prunable() // allow deleting old files on update/delete
```

**Comment by bakerkretzmar** [comment]
@dkulyk I didn't know about `->deletable()`, combined with `->creationRules('required')` that works perfectly. Thanks again for your help!

cc @strebl

**Comment by dkulyk** [comment]
@davidhemphill File fields are deletable by default. Should to add information to documentation about this. https://nova.laravel.com/docs/2.0/resources/file-fields.html#pruning-deletion

**Comment by dyxxxyd** [comment]
Using this code still doesn't work.

->creationRules('required', 'image', 'mimes:jpg,jpeg,png,gif')
->updateRules('nullable')
