### ISSUE TITLE
Wrong docblock return type in Field.php for readonly method

### ISSUE THREAD

**Issue by BostjanOb** [laravel/nova-issues#1522]
- Nova Version: 2.0.1

In Fields/Field.php there is wrong return type specified in docblock for readonly method.

In docblock is `@return void` but then in code is `return $this`.

This is not even a minor problem, but I don't like that PhpStorm is screaming at me :)

**Comment by dkulyk** [comment]
Duplicate of https://github.com/laravel/nova-issues/issues/1486
