### ISSUE TITLE
is there a way to display resource table on dashboard home page?

### ISSUE THREAD

**Issue by SerjoA** [laravel/nova-issues#1523]
i am trying to display resource table on dashboard page without redirecting on load to resource itself
is there a way for that?

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).

**Comment by SerjoA** [comment]
thanks
