### ISSUE TITLE
Better Localization

### ISSUE THREAD

**Issue by h-zone** [laravel/nova-issues#1524]
Good Time of Day! :)

Dear Developers !

I ask to add entire laravel localization variables to the dom.

Need more info?

**Comment by goyote** [comment]
I second this, meaning localization in vue.

**Comment by davidhemphill** [comment]
Sorry, but we are unable to debug your issue without a reproducible code example. Once you provide that we can open this up again.

**Comment by h-zone** [comment]
NP!
i will make package for this (compiling .json with localization)
it will check for already compiled file and load it.
if used fileinfo, we will able to check compile date and manage cache accurracy.

:-)

**Comment by h-zone** [comment]
at this time - gist for localisation json compiler
https://gist.github.com/h-zone/d93fb05fe12047dd25c70907c7c555cf

**Comment by h-zone** [comment]
so, i have only one question - how to obtain entirely system-wide lang files.
i.e. - files which in vendor/packages...
@taylorotwell - it's a cant :-))))))))
