### ISSUE TITLE
Removing a nova card directory cause CardServiceProvider not found error

### ISSUE THREAD

**Issue by sdebarun** [laravel/nova-issues#1527]
I have created a nova card by usual command. Once I delete the directory of the card it shows me a error each time I try to work in composer or artisan, myapp\CurrentUser\CardServiceProvider not found. Can you tell me how to solve the issue. Seems like it has registered itself in many places that I cannot find.

**Comment by davidhemphill** [comment]
It's added to your `composer.json` as a path repo. You need to remove the reference from there.

This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).
