### ISSUE TITLE
Resource option to disable row buttons

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#1531]
### Description:
Im going to make the title linked, and would like to not not clutter the row
But could also be useful for resource display without editing / detail / deleting
```php
class Task extends Resource 
{
    public $rowButtons = false;
}
```
### Outcome
![removed](https://user-images.githubusercontent.com/29180903/56314787-07421900-6124-11e9-8466-5d796b7a9f03.png)

### Current
![not-removed](https://user-images.githubusercontent.com/29180903/56314801-0e692700-6124-11e9-91cc-7e6cbc437579.png)

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by fbingha** [comment]
Yes, this is needed.
