### ISSUE TITLE
Seperate the locale.json of nova components. Fixed.

### ISSUE THREAD

**Issue by vFire** [laravel/nova-issues#1532]
Is it possible to seperate the locale.json files since there are a huge strings need to be translated, each component has a seperate locale.json file will be better, I know if I emerg all of the translate into one file under nova will take effect.
Also I dig into the nova notification component, just find 

> $this->loadJsonTranslationsFrom(resource_path('lang/vendor/nova-notifications'));

It only work for navigation's locale, won't affect the main page of component.

I need some suggestion. Thanks.

**Comment by vFire** [comment]
I hack into nova code, hope it will be helpful for you.

File:\nova\nova\src\NovaServiceProvider.php


`    /**
     * Get the translation keys from file.
     *
     * @return array
     */
    private static function getTranslations()
    {
        $translations = [];
        $dirs = File::directories(resource_path('lang/vendor'));
        foreach($dirs as $dir){
            $translationFile = $dir.'/'.app()->getLocale().'.json';
            if (is_readable($translationFile)) {
                $translations = array_merge($translations, json_decode(file_get_contents($translationFile), true));
            }
        }

        return $translations;
    }`

**Comment by vFire** [comment]
and I am not sure should I also fix the following function in this file, seemed also used to get translation, I havn't dig into it, maybe someone can help me.

>     /**
     * Register the package resources such as routes, templates, etc.
     *
     * @return void
     */
    protected function registerResources()
    {
        $this->loadViewsFrom(__DIR__.'/../resources/views', 'nova');
        $this->loadTranslationsFrom(__DIR__.'/../resources/lang', 'nova');
        $dirs = File::directories(resource_path('lang/vendor'));
        foreach($dirs as $dir){
            $this->loadJsonTranslationsFrom($dir);
        }

        if (Nova::runsMigrations()) {
            $this->loadMigrationsFrom(__DIR__.'/../database/migrations');
        }

        $this->registerRoutes();
    }

**Comment by vFire** [comment]
Maybe in the future, Nova could read component language package when the component is called. So it could largely reduce the bandwith, and in my opinion it will be perfect if we can limit each language pack only affect in its own UI, not overide others or global UI/View.

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
Since Nova 4 uses Inertia, you can assign middleware to add tool translations.
