### ISSUE TITLE
Running action on pivot table doesn't set model_id in action_events

### ISSUE THREAD

**Issue by lpluto** [laravel/nova-issues#1534]
- Laravel Version: 5.8.11
- Nova Version: 2.0.1
- PHP Version: 7.3
- Operating System and Version: MacOS.10.14.2
- Browser type and version: Chrome 73

### Description:
When I run action on pivot table the model_id is set to NULL in action_events table. And then when I try to call markAsFailed on this model, the model_id with correct value is used to find this row in table. It can't be found, because model_id is set to NULL in database.

### Steps To Reproduce:
1. Run action on pivot table
2. Try to markAsFailed this model
3. It is not set to failed

**Comment by jbrooksuk** [comment]
This issue relates to an older version of Nova. It's possible that this bug has been fixed in recent versions. If you're still experiencing this in the latest version of Nova, please re-open this ticket, thanks!
