### ISSUE TITLE
Version not updated for 2.0.1

### ISSUE THREAD

**Issue by mdavis1982** [laravel/nova-issues#1535]
- Laravel Version: 5.8.12
- Nova Version: 2.0.1
- PHP Version: 7.3

### Description:
The Nova version hasn't been updated to 2.0.1. When using `Nova::version()` it still returns `2.0.0`

**Comment by vFire** [comment]
I also found this problem, just fixed it manually in /src/Nova.php in the NOVA directory.

>     /**
     * Indicates if Nova should register its migrations.
     *
     * @var bool
     */
    public static $runsMigrations = true;
    /**
     * Get the current Nova version.
     *
     * @return string
     */
    public static function version()
    {
        return '2.0.1';
    }

**Comment by phoenixg** [comment]
I find this problem too.

**Comment by davidhemphill** [comment]
This is fixed in next release.
