### ISSUE TITLE
attach Policy with BelongsToMany works but button Attach related resource is visible

### ISSUE THREAD

**Issue by wemersonrv** [laravel/nova-issues#1536]
- Laravel Version: 5.8.12
- Nova Version: 2.0.1
- PHP Version: 7.2.11
- Operating System and Version: Windows 10 64 Bits LTSC
- Browser type and version: Google Chrome 73.0.3683.103 64 Bits

### Description:
When returns **false** in a Pollicy Rule for `BelongsToMany` resource relationship it's works but with an issue: The button **Attach Resource** is visible, and allow to enter on screen to attach related resource. The good news is that no resource is displayed to attach, so in this point the Policy works.

It would be more interesting if even the button were not displayed in that case policy deny the action:.

### Steps To Reproduce:
1. Add a belongsToMany Field to other resource.
2. Create a Policy rule resource with belongsToMany to deny attaching related resource.
3. Go to resource screen and try to attach.

### My case.

I have a Resource named **Abastecimento** that has a `BelongsToMany` relationship field to other resource named **Cartao**

#### 1. Model Abastecimento relationship to Cartao
```php
public function cartoes()
{
  return $this->belongsToMany('MaisControl\Models\Cartao', 'abastecimento_cartoes');
}
```

#### 2. Resource Abastecimento relationship field to Cartao
```php
BelongsToMany::make('TAGs', 'cartoes', 'MaisControl\Nova\Cartao'),
```

#### 3. Policy rules in AbastecimentoPolicy
```php
    /**
     * Determine whether the user can attach a Cartao to Abastecimento.
     *
     * @param  \MaisControl\Models\User  $user
     * @param  \MaisControl\Models\Abastecimento  $abastecimento
     * @param  \MaisControl\Models\Cartao  $cartao
     * @return mixed
     */
    public function attachCartao(User $user, Abastecimento $abastecimento, Cartao $cartao)
    {
        return false;
    }

    /**
     * Determine whether the user can detach a Cartao from Abastecimento.
     *
     * @param  \MaisControl\Models\User  $user
     * @param  \MaisControl\Models\Abastecimento  $abastecimento
     * @param  \MaisControl\Models\Cartao  $cartao
     * @return mixed
     */
    public function detachCartao(User $user, Abastecimento $abastecimento, Cartao $cartao)
    {
        return false;
    }
```

#### 4. And of course, the Model Cartao relationship to Abastecimento
```php
public function abastecimentos()
{
        return $this->belongsToMany('MaisControl\Models\Abastecimento', 'abastecimento_cartoes');
}
```

**Comment by krunaldevs** [comment]
I am also struggling with same issue.

**Comment by wemersonrv** [comment]
> I am also struggling with same issue.

Yeah, this is anoying. 

Many may say that this is not a problem because despite displaying the `Attach button`, no related resource is displayed when trying to attach and of course, will not attach anything. But it generates an dangerous error message.

Look here: https://prnt.sc/nf8fej

**Comment by wemersonrv** [comment]
Found it in docs. Realize now that isn't a bug, but a wrong use of `attach` policy. Just need to use `attachAny{Model} `, so above, in my `attachCartao` policy, change the method to:

```php
/**
     * Determine whether the user can attach any Cartao to Abastecimento.
     *
     * @param  \MaisControl\Models\User  $user
     * @param  \MaisControl\Models\Empresa $empresa
     * @return mixed
     */
    public function attachAnyCartao(User $user, Empresa $empresa)
    {
        // My logic
    }
```

So the secret is how to interpret the rule... `attachAny{Model}` to other model... so we have `attahcAnyCartao` policy that will allow a specific User to attach Cartao to Empresa... i think is that right?



@krunaldevs

**Comment by jbrooksuk** [comment]
This issue relates to an older version of Nova. It's possible that this bug has been fixed in recent versions. If you're still experiencing this in the latest version of Nova, please re-open this ticket, thanks!

**Comment by achalj09** [comment]
It is the issue with model name while attach{model} or attachAny{model} working fine, but due to model name it might not working, you can check your mode name by

use Illuminate\Support\Str;

Str::singular(class_basename('ModelName'));

and then you can see what function name should be.
