### ISSUE TITLE
Alphabetical ordering incorrect on relation select field

### ISSUE THREAD

**Issue by robertvrabel** [laravel/nova-issues#1537]
- Laravel Version: 5.8.11
- Nova Version: 2.0.1
- PHP Version: 7.2
- Operating System and Version: MacOS Mojave
- Browser type and version: Chrome 73.0.3683.86

### Description:

If the select field has a mixture of lowercase and uppercase characters it does not sort it properly in alphabetical order.

<img width="1219" alt="Screen Shot 2019-04-18 at 9 08 30 AM" src="https://user-images.githubusercontent.com/634788/56363335-f512ba00-61b9-11e9-87db-8203a43c35ac.png">

### Steps To Reproduce:

Create a BelongsToMany relationship with mixed uppercase and lowercase starting characters.

**Comment by jbrooksuk** [comment]
Confirmed.

**Comment by jbrooksuk** [comment]
PR made.
