### ISSUE TITLE
Password confirm field

### ISSUE THREAD

**Issue by daguilarm** [laravel/nova-issues#154]
Will be nice a password confirm field, because right now nova try to store the value in the DB. Any way to avoid this?

**Comment by fat4lix** [comment]
Maybe you need Laravel\Nova\Fields\Password? It's hash password before store in the DB

**Comment by crnkovic** [comment]
So, if the User model has ‘setPasswordAttribute’, the default Nova’s Password field would fuck up? Maybe it would be nice if Nova could check if password is hashed once attribute is set, and if is not, hash it.

**Comment by Jam0r85** [comment]
@crnkovic yes, the Password field uses 'Hash::make' on the value entered so no need to have the setPasswordAttribute on the model.

**Comment by crnkovic** [comment]
@Jam0r85 yeah but I’ve been using setPasswordAttribute for a long time and my app is built with that in mind and IMHO Nova should adjust to me and not I to it :-) hopefully this gets fixed, no biggie :)

**Comment by daguilarm** [comment]
Hi, I'm sorry I did not explain myself well. Imagine you have this code:

```
Password::make('Password', 'password')
 ->onlyOnForms()
->creationRules('required', 'string', 'min:6')
->updateRules('nullable', 'string', 'min:6'),

Password::make('Password confirmation', 'password_confirmation')
->onlyOnForms()
->creationRules('required', 'required_with:password', 'string', 'min:6')
->updateRules('nullable', 'required_with:password', 'string', 'min:6'),
```

When in the form you enter the new password and send it, Nova will try to store the 'password_confirmation' field in the DB. The problem is that this field does not exist... and create and error.

Will be nice a method to tell Nova to ignore this field...

**Comment by lucasromanojf** [comment]
I figured out a way too:

```
public static function fill(NovaRequest $request, $model)
{
    if ($request->input('password_confirmation')) {
        $request->offsetUnset('password_confirmation');
    }
    return parent::fill($request, $model);
}
```

**Comment by EmanueleCoppola** [comment]
@lucasromanojf Doesn't work for me, it's like ignoring completely the method override...

**Comment by matteo-rigon** [comment]
I've got it working like this

```php
public function fields(Request $request)
{
	// other fields
	Password::make('Password')
                ->onlyOnForms()
                ->creationRules('required', 'string', 'min:6', 'confirmed')
                ->updateRules('nullable', 'string', 'min:6', 'confirmed'),

	Password::make('Password confirmation', 'password_confirmation')
                ->onlyOnForms()
		->creationRules('required', 'required_with:password', 'string', 'min:6')
		->updateRules('nullable', 'required_with:password'),
}

protected static function fillFields(NovaRequest $request, $model, $fields)
{
	return parent::fillFields($request, $model, $fields->filter(function($field) {
		return $field->attribute != 'password_confirmation';
	}));
}
```

**Comment by davidhemphill** [comment]
In the next release we'll have a `PasswordConfirm` field you can use like this:

```php
Password::make('Password')
    ->onlyOnForms()
    ->creationRules('required', 'confirmed', 'string', 'min:6')
    ->updateRules('nullable', 'string', 'min:6'),

PasswordConfirm::make('Password Confirmation'),
```

**Comment by nickels** [comment]
release class name is: `PasswordConfirmation`

```
PasswordConfirmation::make('Password Confirmation'),
```

@davidhemphill thank you for this feature.

**Comment by ChristianKuri** [comment]
@crnkovic
If the User model has ‘setPasswordAttribute’ that hashes the password by default use this:

`Password::make('Password')
     ->onlyOnForms()
     ->creationRules('required', 'string', 'min:6')
     ->updateRules('nullable', 'string', 'min:6')
     ->fillUsing(function (NovaRequest $request, $model, $attribute, $requestAttribute) {
         if (! empty($request->{$requestAttribute})) {
             $model->{$attribute} = $request[$requestAttribute];
         }
     }),`

**Comment by dkulyk** [comment]
In upcoming(>1.3.0) release you will be able to use fillUsing for password field.

**Comment by chbbc** [comment]
It looks like obvious, but if you'll use the **Password Confirmation** field, it's necessary to put ``confirmed`` in the **Password** field rules and it's not documented.

Example:

```php
        Password::make('Password','password')
            ->onlyOnForms()
            ->creationRules('required', 'string', 'min:6', 'confirmed')
            ->updateRules('nullable', 'string', 'min:6', 'confirmed'),

        PasswordConfirmation::make('Password Confirmation'),

```

**Comment by chbbc** [comment]
One more thing: If uses another text than _Password Confirmation_ (translated, e.g.) it's necessary to declare ``password_confirmation`` as second argument. Like this:

```php
    PasswordConfirmation::make('Confirmação da senha', 'password_confirmation'),
```

I think it's a good ideia to put this information on documentation.

**Comment by ChristianKuri** [comment]
> In upcoming(>1.3.0) release you will be able to use fillUsing for password field.

Are we able to use fillUsing for password field now? Nova 1.3.2 was released

**Comment by dkulyk** [comment]
Yes. It was fixed.

**Comment by nemrutco** [comment]
Why it doesn't has error status when password confirmation not matching? i think it will be good to give error status on both fields.

**Comment by jonmenard** [comment]
Adding the 'confirmed' rule ensure the password confirmation field must match the provided password.

```php
Password::make(__('Password'))
    ->onlyOnForms()
    ->creationRules('required', 'confirmed', Rules\Password::defaults())
    ->updateRules('nullable', 'confirmed', Rules\Password::defaults()),
```
