### ISSUE TITLE
video javascript not display in detail page

### ISSUE THREAD

**Issue by Jignasa10** [laravel/nova-issues#1540]
Hello, 

I have one javascript to display video, but it's not display in nova resource details page. It's display in laravel blade file.

my script code as below:

<div id="boxcast-widget-bkbwwwmnmhbhb2ai5xwv"></div><script type="text/javascript" charset="utf-8">(function(d, s, c, o) {var js = d.createElement(s), fjs = d.getElementsByTagName(s)[0];var h = (('https:' == document.location.protocol) ? 'https:' : 'http:');js.src = h + '//js.boxcast.com/v3.min.js';js.onload = function() { boxcast.noConflict()('#boxcast-widget-'+c).loadChannel(c, o); };js.charset = 'utf-8';fjs.parentNode.insertBefore(js, fjs);}(document, 'script', 'bkbwwwmnmhbhb2ai5xwv', {"showTitle":0,"showDescription":0,"showHighlights":0,"showRelated":false,"defaultVideo":"next","market":"church","autoplay":true,"showCountdown":false,"hidePreBroadcastTextOverlay":true,"customPreroll":"https://uploads.boxcast.com/natkzaz3n7tyljeogaro/2018-11/qm6nyojakbafgb8jgyel/KH-Final-480sm.mp4","dvr":false}));</script>
 

Thanks!

**Comment by vFire** [comment]
You'd better use vue.js component not operate in DOM.

**Comment by davidhemphill** [comment]
You should implement this using the custom field generator that ships with Nova.
