### ISSUE TITLE
On a resource detail screen, when using PANELS the ACTIONS are not shown.

### ISSUE THREAD

**Issue by HenriqueSPin** [laravel/nova-issues#1542]
- Laravel Version: 5.8.13
- Nova Version: 2.0.0
- PHP Version: 7.1.3
- Operating System and Version: macOS 10.14.4
- Browser type and version: Chrome 73.0.3683.103

### Description:

On a resource detail screen, when using PANELS the ACTIONS are not shown.

### Steps To Reproduce:

Just add a panel to a resource that has actions and enter in detail screen.

**Comment by AnthonyLedru** [comment]
Try with:

`(new Panel('Test'))->withToolbar()`
