### ISSUE TITLE
Actions that extends destructive action doesn't properly register "canRun" closure.

### ISSUE THREAD

**Issue by HenriqueSPin** [laravel/nova-issues#1543]
- Laravel Version: 5.8.13
- Nova Version: 2.0.0
- PHP Version: 7.1.3
- Operating System and Version: macOS 10.14.4
- Browser type and version: Chrome 73.0.3683.103

### Description:

Actions that extends destructive action doesn't properly register "canRun" closure.

### Steps To Reproduce:

Just add a canRun closure to an action that extends DestructiveAction and try to call it from index ou detail.

**Comment by jbrooksuk** [comment]
Confirmed in v2.0.9

**Comment by bredmor** [comment]
This issue is still present in 2.3.1, is there a fix on the way?
