### ISSUE TITLE
Date field must cast to 'date' in Eloquent model.

### ISSUE THREAD

**Issue by RomaGilyov** [laravel/nova-issues#1545]
Hi, have got a small issue with `morthToMany()` relation and a pivot date value:

`
public function subscriptions()
    {
        return $this->morphedByMany(Subscription::class, 'subscription', 'user_subscription')
            ->withPivot(['from_date', 'to_date']);
    }
`

And 
    
`
    public function users()
    {
        return $this->morphToMany(User::class, 'subscription', 'user_participation')
            ->withPivot(['from_date', 'to_date']);
    }
`
And inside my Nova models I have this:
`
MorphedByMany::make('Subscriptions')
                    ->fields(function () {
                        return [
                            Date::make('To date')->nullable(),
                            Date::make('From date')->nullable(),
                        ];
                    }),
`

It works fine until the details page inside of which I'm getting this error:

`Date field must cast to 'date' in Eloquent model.`

So, I have two questions:

1. How does Nova understand that the fields related to the pivot table and set it correctly with the attach page?
2. Why doesn't Nova able to recognize and get the values from the pivot table for the details page?

**Comment by RomaGilyov** [comment]
Fixed with https://laravel.com/docs/5.7/eloquent-relationships#many-to-many

But it wasn't intuitive at all, is there any way to parse string date in the Nova template to avoid such manipulation?

For example like so: 
`
if (typeof field.value === 'string') {
    let date = moment(field.value, field.format);     
}
`

**Comment by devfrey** [comment]
It should be as simple as adding a pivot model (disclaimer: not tested):

```
public function users()
{
    return $this->morphToMany(User::class, 'subscription', 'user_participation')
        ->using(Subscription::class) // Don't forget this line
        ->withPivot(['from_date', 'to_date']);
}
```

```
class Subscription extends MorphPivot
{
    //
    protected $dates = ['from_date', 'to_date'];
}
```

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).
