### ISSUE TITLE
Request: Support for HTTP Response codes (404, 500)

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#1547]
Currrently the only fullproof Nova method is to abort with a 403 status code. This works in all resources and/or metrics.

But i would also like the possibilty to return 404 and 500 codes. Right now i have several exceptions that Log and Render differently. It would be nice if i could just send a 404 / 500 and the frontend responds to them by showing a generic 404 / 500 page.

**Exception at frontend when trying to abort with 404:**
```
vendor.js?id=b30263b2f9d68433c3ce:1 Uncaught (in promise) Error: Request failed with status code 404
    at FtD3.t.exports (vendor.js?id=b30263b2f9d68433c3ce:1)
    at t.exports (vendor.js?id=b30263b2f9d68433c3ce:1)
    at XMLHttpRequest.f.(anonymous function) (<path-to-project>/vendor/nova/vendor.js?id=b30263b2f9d68433c3ce:1:150007)
```

**Comment by preliot** [comment]
@davidhemphill Does you closing this request means this is added in a new release?

**Comment by preliot** [comment]
Just tested this old request, no support for anything other then a 403.

**Comment by jbrooksuk** [comment]
We normally post this comment when closing feature requests.

In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
