### ISSUE TITLE
[Bug?]Action Event saves an empty string  when performing an update

### ISSUE THREAD

**Issue by plfauchergdg** [laravel/nova-issues#1548]
- Laravel Version: 5.8.14
- Nova Version: 2.0.1
- PHP Version: 7.3

### Description:

I do not know if it is intended behaviour or if this is truly a bug but here it goes

src/nova/Actions/ActionEvent::forResourceUpdate($user, $model) has the following code
```
return new static([
            'batch_id' => (string) Str::orderedUuid(),
            'user_id' => $user->getAuthIdentifier(),
            'name' => 'Update',
            'actionable_type' => $model->getMorphClass(),
            'actionable_id' => $model->getKey(),
            'target_type' => $model->getMorphClass(),
            'target_id' => $model->getKey(),
            'model_type' => $model->getMorphClass(),
            'model_id' => $model->getKey(),
            'fields' => '',
            'status' => 'finished',
            'exception' => '',
        ]);
```

Changing the `'fields' => '',` to `'fields' => json_encode($model->getChanges()),` (or something similar but without a hard requirement into ext-json) allows us to see which fields were updated.

### Steps To Reproduce:

1. Perform an update on a request
1. in the action_events table, column "fields" is set to an empty string

**Comment by davidhemphill** [comment]
Not technically a bug, but we're just not doing anything with the `fields` column at the moment. I'm exploring how we might save the original and update attributes in a way that could be secured if needed.
