### ISSUE TITLE
conditional actions

### ISSUE THREAD

**Issue by Dontorpedo** [laravel/nova-issues#1549]
is it possible to make the actions depend on some conditions?

like show the action on detailpage only if the resource has a status like active or is there a workaround for this?

thanks
Denis

**Comment by dkulyk** [comment]
You should use `canSee` or override `authorizedToSee` in the action class.
```php
(new MyAction())->canSee(function () {
    return $this->resource->status !== 'DONE';
})
```

**Comment by greatwitenorth** [comment]
@dkulyk How would we go about loading related resources for our condition? It seems like `$this->resource` only contains the immediate resource it's on. For example this will not work:

```php
(new PublishPost())->canSee(function () {
    return $this->resource->author->name;
}),
```

**Comment by alberto-bottarini** [comment]
What about index views? 
It should be coll if action will become available if every selected resource match the canSee condition.

**Comment by provydon** [comment]
> @dkulyk How would we go about loading related resources for our condition? It seems like `$this->resource` only contains the immediate resource it's on. For example this will not work:
> 
> ```
> (new PublishPost())->canSee(function () {
>     return $this->resource->author->name;
> }),
> ```

ll

**Comment by provydon** [comment]
`->canSee(function () {
           return $this->first()->status == 'pending';
     })`

**Comment by provydon** [comment]
This worked for me guys!
 
> ```
> ->canSee(function () {      
>     return $this->first()->status == 'pending';
>  }),
> ```

**Comment by provydon** [comment]
This worked for me guys!

` ->canSee(function () {
         return $this->first()->status == 'pending';
     })
`

**Comment by omarmatijas** [comment]
I've been printing some values to Log. What I've found is that sometimes canSee is called with a row loaded into the model but sometimes not; its like it's just to check permission.
So to my condition I added **_!$this->resource->exists ||_**

For example:
```

(new Actions\MarkAsInactive)
            ->confirmText('Are you sure you want to deactivate this page?')
                ->confirmButtonText('Deactivate')
                ->cancelButtonText("Leave it active")
                ->canSee(function ($request) {
                    return !$this->resource->exists || $this->resource->enabled;
                })
```

**Comment by ekpono** [comment]
> You should use `canSee` or override `authorizedToSee` in the action class.
> 
> ```
> (new MyAction())->canSee(function () {
>     return $this->resource->status !== 'DONE';
> })
> ```

This redirects me to 403 page when I run the action

**Comment by crynobone** [comment]
Please refer to the documentation: https://nova.laravel.com/docs/3.0/actions/registering-actions.html#authorizing-actions-per-resource

**Comment by ekpono** [comment]
```
 return [
        (new Actions\CancelTrial)->canSee(function ($request) {
            if ($request instanceof ActionRequest) {
                return true;  
            }

            return $this->resource instanceof Model && $this->resource->isOnTrial();
        }),
    ];
```

Thanks @crynobone
