### ISSUE TITLE
BelongsToMany pivot fields and actions not showing

### ISSUE THREAD

**Issue by alexjose** [laravel/nova-issues#155]
I am not able to show the pivot fields in the BelongsToMany relation and the actions on the pivot table is also not showing up.
```php
BelongsToMany::make('Sectors')
     ->fields(function () {
                    return [
                        Boolean::make('Status'),
                    ];
                })
       ->actions(function () {
                    return [
                        new App\Nova\Actions\ESector\Approve,
                    ];
                }),
```

**Comment by arnordhaenens** [comment]
@alexjose what exactly isn't working? Do you receive an error?

**Comment by alexjose** [comment]
@arnordhaenens No errors at all. The pivot field and pivot action are not showing in the relation index. But pivot field is shown in the edit and attach views.

**Comment by arnordhaenens** [comment]
Same request is being referenced here in #40 and #186

**Comment by alexjose** [comment]
@arnordhaenens #40 was different, he was expecting the related model's field to be displayed in the parent resource index view. I am taking about the parent resource detail view where we can see the related records.  #186 is similar but just taking about the pivot fields. 

For me nor the pivot fields neither the pivot actions are getting displayed.

**Comment by patrickbrouwers** [comment]
@alexjose I had the same problem with pivot actions. It turns out you need to define the `BelongsToMany` field on both resources for it to work.

**Comment by prolonginc** [comment]
i got this working by defining` ->withPivot('filed name)'` on the relationship it drove me insane for a long time.

**Comment by alexjose** [comment]
@patrickbrouwers you are right. Needs to add the pivot fields and the actions in both resources.

**Comment by jsphpl** [comment]
> @patrickbrouwers you are right. Needs to add the pivot fields and the actions in both resources.

@alexjose please don't close the issue unless this is either fixed or clearly stated in the docs

**Comment by LaravelFreelancerNL** [comment]
I ran into this exact bug and am, finally, able to reproduce it. Its in a commercial project so I'll contact the Nova team after the weekend. For now I don't even want to think about for the coming days ;)

**Comment by osteel** [comment]
> i got this working by defining` ->withPivot('filed name)'` on the relationship it drove me insane for a long time.

Just to be clear, `->withPivot(... fields ...)` must be defined on the relationship in the _model_, not the Nova resource.

**Comment by chrisvasey** [comment]
> @alexjose I had the same problem with pivot actions. It turns out you need to define the `BelongsToMany` field on both resources for it to work.

I found the only way to sort this is to define the action and field array on both Nova models... otherwise, the action does not show up.
You also need the `->withPivot('field')` on both standard models.

Hopefully, no one is facing this issue anymore, but I still hit this issue every time I try to use BelongsToMany actions!
It might be worth updating the docs.

**Comment by mathieufrh** [comment]
This behaviour is really strange and according to me, this is a real bug.

I am using fields, fieldsForIndex and fieldsForDetails. When defining a BelongsToMany with a fields method to add pivot fields, it is ONLY working if I add it to fields, fieldsForIndex and fieldsForDetails. I understand that showing many related resources of type A from the details page of a resource B is using the index view of A, but why requiring A to exists in the fieldsForIndex of resource B ? It does not really make sense.
