### ISSUE TITLE
Related model create inside modal

### ISSUE THREAD

**Issue by Pamposgsk** [laravel/nova-issues#1550]
Hi,
Is there a possibility to view resource relation create view inside with a button.
For example i have a resource Customer wich hasmany Orders .In customer detail page i can see the table of the orders related for the selected customer.
So what i actually need is to create new order  inside a modal when i click a button  and not to see the entire order resource inside customer detail page
Thanks

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
