### ISSUE TITLE
This survey may not be associated with this resource.

### ISSUE THREAD

**Issue by krunaldevs** [laravel/nova-issues#1552]
Hello,

Well I am struggling with this error while I update the data.

![image](https://user-images.githubusercontent.com/47715249/56815189-5132a980-685e-11e9-9dbb-d54fe3e3747e.png)

Below is resource code:

```
BelongsTo::make(__('Survey to Send'), 'survey', 'App\Nova\Survey')
                ->rules('required')
                ->searchable(),
```

Can anyone know about this?

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).
