### ISSUE TITLE
Unable to create "Style" resource

### ISSUE THREAD

**Issue by rez1dent3** [laravel/nova-issues#1553]
- Laravel Version: 5.8.*
- Nova Version: 2.0.1
- PHP Version: 7.3
- Operating System and Version: ArchLinux / Ubuntu 18.04
- Browser type and version: Opera last version

### Description:
Hello. When creating a resource Nova named "Style" falls admin panel when viewing, editing, etc. Go to the address "/nova/resources/styles" does not come out.

### Steps To Reproduce:
1. Create a resource
```bash
./artisan nova:resource Style
```
2. Go to the admin panel

![Снимок экрана от 2019-04-28 20-43-50](https://user-images.githubusercontent.com/5111255/56868075-64787d00-69f6-11e9-880c-56dfe6b1ec09.png)

**Comment by davidhemphill** [comment]
I am able to create a `Style` resource using Nova's `nova:resource` command. Sorry, but we are unable to debug your issue without a reproducible code example. Once you provide that we can open this up again.

**Comment by rez1dent3** [comment]
@davidhemphill to create a resource is obtained, but to see it in the admin panel - no

**Comment by rez1dent3** [comment]
1.
```bash
./artisan nova:resource Style
```

2.
```php
namespace App\Nova;

use Laravel\Nova\Fields\ID;
use Illuminate\Http\Request;
use Laravel\Nova\Http\Requests\NovaRequest;

class Style extends Resource
{
    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static $model = \App\Models\Style::class;

    /**
     * The single value that should be used to represent the resource when being displayed.
     *
     * @var string
     */
    public static $title = 'id';

    /**
     * The columns that should be searched.
     *
     * @var array
     */
    public static $search = [
        'id',
    ];

    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
        ];
    }

    /**
     * Get the cards available for the request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function cards(Request $request)
    {
        return [];
    }

    /**
     * Get the filters available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function filters(Request $request)
    {
        return [];
    }

    /**
     * Get the lenses available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function lenses(Request $request)
    {
        return [];
    }

    /**
     * Get the actions available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function actions(Request $request)
    {
        return [];
    }
}
```

3. 
![image](https://user-images.githubusercontent.com/5111255/57228133-c0a55780-701b-11e9-8f06-8abe6a85385e.png)
![image](https://user-images.githubusercontent.com/5111255/57228148-c9962900-701b-11e9-84f4-937f49faf415.png)
![image](https://user-images.githubusercontent.com/5111255/57228160-d31f9100-701b-11e9-8371-6315c76b38ee.png)

**Comment by davidhemphill** [comment]
Thanks for the screenshots, I am able to replicate your issue. However, while annoying, this is not a common issue, and so it's not going to get a fix soon. As a short-term fix, you could override the `uriKey` method on your resource and set it to a nonconflicting URI key.

```php
    /**
     * Get the URI key for the resource.
     *
     * @return string
     */
    public static function uriKey()
    {
        return 'custom-styles';
    }
```

**Comment by crnkovic** [comment]
Same thing with the Script resource. I have a Script resource and cannot access it from Nova dashboard for the same reason. Probably just issue with priority in routing.

**Comment by rez1dent3** [comment]
@davidhemphill спасибо

**Comment by packytagliaferro** [comment]
@davidhemphill your solution worked for me, but just wanted to note I have a few different sites that use a "styles" table

**Comment by jbrooksuk** [comment]
Pushed a PR that addresses this.

**Comment by jbrooksuk** [comment]
@hafezdivandari this is no longer an issue. We raise a warning when you create a resource with a restricted name:

![image](https://user-images.githubusercontent.com/246103/66383873-aea65700-e9b5-11e9-9310-ceeeceabfbf9.png)
