### ISSUE TITLE
Extreme amount of requests on detail resource page with relationship after updating to 2.0.2

### ISSUE THREAD

**Issue by edwwaarrdd** [laravel/nova-issues#1555]
- Laravel Version: 5.8
- Nova Version: 2.0.2
- PHP Version: 7.2

### Description:
When on a detail page of a resource with a relationship, there are a lot (and never ending) requests to the api endpoints `/nova-api/RESOURCENAME` and `/nova-api/RESOURCENAME/count`. Multiple requests per second.
The RESOURCENAME are the names of the relationships.
I think it has to do with the regression of the per page that should have fixed the pagination issues.
- I do not have these issues when I downgrade to nova 2.0.1
- only on nova 2.0.2

### Steps To Reproduce:
Update to nova 2.0.2
Go to a resource detail with a belongsToMany or hasMany relationship

**Comment by dillingham** [comment]
just experienced this.. happens a few seconds after creating a resource

<img width="905" alt="Screen Shot 2019-04-30 at 3 37 29 PM" src="https://user-images.githubusercontent.com/29180903/56988382-e33bfa00-6b5d-11e9-8ade-feb194ea8881.png">

**Comment by dillingham** [comment]
here are some console errors

<img width="905" alt="Screen Shot 2019-04-30 at 3 38 23 PM" src="https://user-images.githubusercontent.com/29180903/56988431-0666a980-6b5e-11e9-8546-107d8579f62b.png">

**Comment by tobz-nz** [comment]
`BelongsTo` relation seems fine. `HasOne` and `MorphToMany` both trigger it. haven't checked others.

**Comment by andymswick** [comment]
I've also experienced this. Also I can not select records to run actions.

**Comment by the-great-tao** [comment]
I also got this problem after upgrading to 2.0.2

![Untitled](https://user-images.githubusercontent.com/26620857/57019490-e19f2e80-6c50-11e9-99aa-a3cd0054426e.png)

**Comment by davidhemphill** [comment]
I saw this in development before I ran `php artisan nova:publish --force` to update the assets. Are you certain you've done this and the issue persists? I'm not seeing it on any of my updated Nova apps.

**Comment by mvdnbrk** [comment]
I did run `php artisan nova:publish --force`.

**Comment by davidhemphill** [comment]
Ok, was able to replicate this on a new app. Looking into it.

**Comment by mattsmithies** [comment]
I have the same multiple request issue with `HasMany` and `HasOne`, after running the force command.

**Comment by davidhemphill** [comment]
I've reverted the PR that introduced this error. Will draft a release today.
