### ISSUE TITLE
show resources views in a modal

### ISSUE THREAD

**Issue by Pamposgsk** [laravel/nova-issues#1556]
Hi,
I think laravel nova is a great solution!At the begining i thought that it was not easy to customize but i realized that with power of vuejs along with nova tools you can do almost everything.
There is only one feature that is missing and is a big limitation:
To be able to access resources views from a custom tool.For example to click a button in my tool and open a modal showing an existing nova created resource form ,to create a new record..
Now you can do it but you need to design the entire resource functionality from scratch.
Is that correct?
If yes do you plan to include this functionality in a future update?

**Comment by davidhemphill** [comment]
There are no plans to implement anything like this at this time.

**Comment by freshway** [comment]
Hi
I think it would be a very interesting feature.
Moreover, I plan to create a small component (Package) that allows generating a modal with the rendering of a view.
I think it may not best way, but there are many situations that I would like to extend information without open resource req.

**Comment by komisia** [comment]
yes, please.
we need it :'(
