### ISSUE TITLE
New problem with Partition metric and colors in 2.0.2/2.0.3, "Call to a member function get() on array"

### ISSUE THREAD

**Issue by greggh** [laravel/nova-issues#1558]
- Laravel Version: 5.8.15
- Nova Version: 2.0.3
- PHP Version: 7..2.17
- Operating System and Version: Mac, Mojave
- Browser type and version: Chrome 73

### Description:
A metric that was working fine is now throwing an error, "Call to a member function get() on array". This is happening on line 74 of ./vendor/laravel/nova/src/Metrics/PartitionResult.php

![Screen Shot 2019-05-01 at 1 36 53 PM](https://user-images.githubusercontent.com/90286/57031853-c6173200-6c16-11e9-8279-c87b20b36526.png)

### Steps To Reproduce:

It doesn't happen to every metric, on both screens that I have it happening on there are 4 metrics, and its only happening with one on each.

1. Have a partition metric.
2. Load the resource that shows that metric.

The error is happening in this code, 'color' => $this->colors->get($label),

```
   /**
     * Prepare the metric result for JSON serialization.
     *
     * @return array
     */
    public function jsonSerialize()
    {
        return [
            'value' => collect($this->value ?? [])->map(function ($value, $label) {
                return array_filter([
                    'color' => $this->colors->get($label),
                    'label' => $label,
                    'value' => $value,
                ], function ($value) {
                    return ! is_null($value);
                });
            })->values()->all(),
        ];
    }
```

I do not call the colors function, I have not looked into the custom colors stuff at all, and this metric was working before the upgrade to 2.0.2.

My metric is pretty standard. It is part of a CRM and specifically showing the our clients websites by their language. I am sure I could whip up some pluck and toArray magic to make it a little cleaner, but this works fine for now:

```
<?php

namespace App\Nova\Metrics;

use App\Language;
use Illuminate\Http\Request;
use Laravel\Nova\Metrics\Partition;

class WebsitesByLanguages extends Partition
{
    public $name = 'Websites by Languages';

    /**
     * Calculate the value of the metric.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return mixed
     */
    public function calculate(Request $request)
    {
        $languages = Language::withCount('websites')->orderBy('websites_count', 'desc')->take(5)->get();
        $data = [];

        foreach ($languages as $language) {
            $data[$language->name] = $language->websites_count;
        }

        return $this->result($data);
    }

    /**
     * Determine for how many minutes the metric should be cached.
     *
     * @return  \DateTimeInterface|\DateInterval|float|int
     */
    public function cacheFor()
    {
        return now()->addHours(6);
    }

    /**
     * Get the URI key for the metric.
     *
     * @return string
     */
    public function uriKey()
    {
        return 'website-languages';
    }
}
```

**Comment by JacobBennett** [comment]
Can you provide a copy of the result you are getting in `$languages`? Would love to dig into this one for you as I wrote the portion that allows for flexibility in the colors portion of the code.

**Comment by greggh** [comment]
@JacobBennett thanks!  I can't actually provide it because it never gets there. I am in phpStorm + xdebug. With the breakpoint set right on the $languages = line in the calculate function, it never runs. The "Call to a member function get() on array" happens before that code ever executes.

To find it I actually ended up starting off my breakpoint in index.php, right at boot and stepping through until I get to the point that it happens in PartitionResult.php.

Now for the fun part. It stopped happening. It's been happening all day, I upgraded to 2.0.2 right after the notice went out that it had been tagged. So I've seen this bug for hours. About 5 minutes ago it stopped happening and I can't reproduce it.

I would write this off to some kind of caching or other problems, but I had cleared browser cache, laravel's various caches, redis (flushall) and opcache. So I really am lost as to why it was happening. If it happens again I will update here.

**Comment by JacobBennett** [comment]
This is super odd behavior. The only way that `colors` could be set to an array was if the $colors wasn't set to an instance of`PartitionColors` in the constructor of the `PartitionResult` which is created in the `$this->result()` call in your `calculate` method.

That being said, it sure seems like your cache must have been the offending member on this one. Glad to hear its cleared up!
