### ISSUE TITLE
On custom-detail-toolbar resource tools, field is undefined.

### ISSUE THREAD

**Issue by greggh** [laravel/nova-issues#1559]
- Laravel Version: 5.8.15
- Nova Version: 2.0.3
- PHP Version: 7.2
- Operating System and Version: Mac OSX Mojave
- Browser type and version: Chrome 73

### Description:
I wanted to put Next/Previous buttons on the detail view right next to the actions dropdown box. To accomplish this I need access to the field property so I can get the correct nextId and previousId (because deletes make them non-sequential).

I cannot access this.field from my CustomDetailToolbar.vue. It is undefined. resourceName and resourceId are set fine.

![Screen Shot 2019-05-01 at 9 15 08 PM](https://user-images.githubusercontent.com/90286/57052579-3d1feb00-6c56-11e9-90f5-24eb35992fb4.png)

### Steps To Reproduce:

1. Create a resource tool and register it as custom-detail-toolbar:

```
Nova.booting((Vue, router) => {
    Vue.component('custom-detail-toolbar', require('./components/CustomDetailToolbar'));
    Vue.component('countries-detail-toolbar', require('./components/CountriesDetailToolbar'));
})
```

2. Here is the actual resource tool's CustomDetailToolbar.vue

```
<template>
    <div class="flex w-full justify-end items-center mx-3">
        <div class="flex w-full justify-end items-center">
            <a
                    class="btn btn-default btn-icon btn-white"
                    :href="'/nova/resources/' + this.resourceName + '/' + this.previous"
                    style="background-color: var(--primary); color: white; margin-right: 15px;">
                Previous
            </a>
            <a
                    class="btn btn-default btn-icon btn-white"
                    :href="'/nova/resources/' + this.resourceName + '/' + this.next"
                    style="background-color: var(--primary); color: white;">
                Next
            </a>
        </div>
        <component v-if="hasComponent" :is="component" />
    </div>
</template>

<script>
    export default {
        props: ['resourceName', 'resourceId', 'field'],
        computed: {
            component(){
                return this.resourceName + '-detail-toolbar';
            },
            hasComponent()
            {
                return this.component in this.$options.components;
            },
            previous() {
                //return parseInt(this.resourceId) - 1;
                return this.field.previousId;
            },
            next() {
                //return parseInt(this.resourceId) + 1;
                return this.field.nextId;
            }
        }
    }
</script>
```

The commented out lines in previous() and next() are simplified versions that work when the IDs are sequential. And with those uncommented, and the this.field.* lines commented out, I get the buttons:

![Screen Shot 2019-05-01 at 9 19 57 PM](https://user-images.githubusercontent.com/90286/57052681-ec5cc200-6c56-11e9-91dd-5cb92b34427f.png)

With the simplified lines commented out, and the 'return this.field.previousId' and nextId lines uncommented I get this:

![Screen Shot 2019-05-01 at 9 19 17 PM](https://user-images.githubusercontent.com/90286/57052701-03031900-6c57-11e9-9342-6094fd319726.png)

And in the console I get the error up above, showing me that this.field is 'undefined'

My NextPreviousToolbar.php (the actual name of the resource tool) looks like this right now:

```
<?php

namespace Greggh\NextPreviousToolbar;

use Laravel\Nova\ResourceTool;

class NextPreviousToolbar extends ResourceTool
{
    /**
     * Get the displayable name of the resource tool.
     *
     * @return string
     */
    public function name()
    {
        return 'Next Previous Toolbar';
    }

    /**
     * Get the component name for the resource tool.
     *
     * @return string
     */
    public function component()
    {
        return 'next-previous-toolbar';
    }

    public function nextId()
    {
        return $this->withMeta(['nextId' => 1]);
    }

    public function previousId()
    {
        return $this->withMeta(['previousId' => 2]);
    }
}
```

Currently you can see I just set the IDs to 1 and 2, i'll calculate them right later, first the this.field just needs to be figured out.

Any ideas here? Is the field property just not filled out for custom-detail-toolbar?

**Comment by dkulyk** [comment]
You should use `resource` property instead `field`.

**Comment by greggh** [comment]
@dkulyk That doesn't seem to be documented anywhere on the page for resource tools, it also returns undefined as well. The only real change to the docs from 1.0 to 2.0 related to this is accessing via this.panel.fields[] instead of this.fields?

[https://nova.laravel.com/docs/2.0/customization/resource-tools.html#assets](https://nova.laravel.com/docs/2.0/customization/resource-tools.html#assets)

**Comment by dkulyk** [comment]
Resource tool is not a detail toolbar

**Comment by greggh** [comment]
Following the new 2.0 documentation for this.panel.fields[], I still get the same undefined, just for panel instead of field now.

![Screen Shot 2019-05-01 at 10 04 46 PM](https://user-images.githubusercontent.com/90286/57053615-347ee300-6c5d-11e9-854f-c1680c7bcda8.png)

I changed my next() and previous() like so:
```
           previous() {
                return this.panel.fields[0].previousId;
            },
            next() {
                return this.panel.fields[0].nextId;
            }
```

**Comment by greggh** [comment]
@dkulyk all of the tutorials, and issues here and on the web show creating a custom-detail-toolbar as a resource tool and registering it with custom-detail-toolbar.

Here is @davidhemphill explaining it for an index toolbar:

[https://github.com/laravel/nova-issues/issues/786#issuecomment-427212772](https://github.com/laravel/nova-issues/issues/786#issuecomment-427212772)

And here is the tutorial I originally followed:

[https://dev.to/jake/laravel-nova-adding-custom-buttons-to-resource-toolbars-1ob5](https://dev.to/jake/laravel-nova-adding-custom-buttons-to-resource-toolbars-1ob5)

Everything I can find shows me how to create a custom toolbar for the index and the detail page via a resource tool and:

```
Vue.component('custom-detail-toolbar', require('./components/CustomDetailToolbar'));
```

field, panel, and resource are all 'undefined' in the vue component there.
