### ISSUE TITLE
Show total resource records count

### ISSUE THREAD

**Issue by solmel** [laravel/nova-issues#1560]
https://github.com/laravel/nova-issues/issues/470

Was told it's already in Nova but can't find it anywhere in the docs

**Comment by dillingham** [comment]
![count](https://user-images.githubusercontent.com/29180903/57226673-84530680-6fdd-11e9-9502-421db60ae8b4.png)

**Comment by solmel** [comment]
I meant a way to show it at the top

**Comment by davidhemphill** [comment]
You didn't specify that and it's already in the table. No need to add it to more places.
