### ISSUE TITLE
ViewAny not hiding from sidebar menu

### ISSUE THREAD

**Issue by yehudahkay** [laravel/nova-issues#1563]
The viewAny policy doesn't hide the resource from the sidebar menu

**Comment by bolechen** [comment]
u can rewrite the  `availableForNavigation` method like this

```
    public static function availableForNavigation(Request $request)
    {
        return $request->user()->isSuperAdmin();
    }
```

**Comment by yehudahkay** [comment]
HI shouldn't viewany hide from the sidebar? Why should a user see the menu item if he can't see any items there?

**Comment by jbrooksuk** [comment]
Nova gives you the flexibility to finely control what is displayed and where. There may be times when you want to show metrics or other cards but none of the data for instance.

**Comment by abr4xas** [comment]
You can also add something like this in your `NovaServiceProvider.php` file:

```php
(new Foo)->canSee(function () {
    // stuff
})
```

**Comment by farzadjafari** [comment]
You can use this in your resource:
`public static $displayInNavigation = false;`
