### ISSUE TITLE
Value Metric range disappeared in 2.0.3

### ISSUE THREAD

**Issue by yehudahkay** [laravel/nova-issues#1564]
My value metric looked like this

![image](https://user-images.githubusercontent.com/9964988/57064923-890f7600-6cd0-11e9-91ca-649f8e301c0f.png)

After running update to 2.0.3 I get this

![image](https://user-images.githubusercontent.com/9964988/57065060-e4d9ff00-6cd0-11e9-9b57-a13bf9e915df.png)

Reverting to 2.0.2 solved the issue

I also tested upgrading to 2.0.3 without running php artisan nova:publish and this solves the issue

**Comment by bolechen** [comment]
php nova:publish

**Comment by yehudahkay** [comment]
That is what causes the problem

**Comment by vDk3** [comment]
https://github.com/laravel/nova-issues/issues/1466#issuecomment-485404252

**Comment by akmalelias** [comment]
I hit the same issue after upgrade from Nova v2.0.2 to v2.0.3

**Comment by rikless** [comment]
+1

**Comment by mattsmithies** [comment]
Having this issue too on v2.0.3 :-)

**Comment by eimantaaas** [comment]
Also can confirm the issue

**Comment by fkallevik** [comment]
I can also confirm the issue on v2.0.3.

**Comment by davidhemphill** [comment]
There was a regression regarding how select controls were rendered. Not sure what the underlying issue is exactly, but I've reverted those select elements back to their native type. This has been fixed and will be included in the next release. 👍
