### ISSUE TITLE
BelongsTo field when using namespaced model

### ISSUE THREAD

**Issue by misotrnka** [laravel/nova-issues#1565]
- Laravel Version: 5.8.15
- Nova Version: 2.0.2
- PHP Version: 7.3
- Operating System and Version: MacOS Mojave 10.14.4
- Browser type and version: Safari 12.1

### Description:

I have a resource called `Hit` that has a `BelongsTo` field referencing another resource called `UserAgent`:

```php
namespace App\Nova;

use Laravel\Nova\Fields\BelongsTo;
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Http\Requests\NovaRequest;
use Illuminate\Http\Request;

...

public function fields(Request $request)
    {
        return [
            ID::make('Id')->sortable(),
            BelongsTo::make('User Agent', 'userAgent', 'App\Nova\UserAgent'),
        ];
    }
```

The referenced `UserAgent` resource looks like this:

```php
namespace App\Nova;

use Laravel\Nova\Fields\ID;
use Illuminate\Http\Request;
use Laravel\Nova\Http\Requests\NovaRequest;

...

public static $model = 'App\Models\UserAgent';

public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
        ];
    }
```

As you can see, the corresponding model is in `App\Models` namespace. I suspect this is the cause of the problem.

When accessing the Hit's create page, Nova throws error `Class 'UserAgent' not found`.

<img width="1063" alt="Screenshot 2019-05-02 at 10 55 40" src="https://user-images.githubusercontent.com/2571856/57065155-dc7dc600-6cc8-11e9-86bb-f1a4ce3e0003.png">

**Is this a bug? How can I use the BelongsTo field when the referenced resources's model is in a custom namespace? Or perhaps this is not a problem with namespaces but something else?**

Any help greatly appreciated.

**Comment by jbrooksuk** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to #nova on Laravel's Discord or #nova on the Larachat Slack Channel.
