### ISSUE TITLE
Metric cached for all users

### ISSUE THREAD

**Issue by yehudahkay** [laravel/nova-issues#1566]
If I use cache on a metric and then log in as different users I see the same report for all users

**Comment by bolechen** [comment]
rewrite the getCacheKey method include userid

**Comment by davidhemphill** [comment]
This is intended behavior. If you need to customize how the caching overwrite `getCacheKey` like was suggested above:

```php
/**
 * Get the appropriate cache key for the metric.
 *
 * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
 * @return string
 */
protected function getCacheKey(NovaRequest $request)
{
    return sprintf(
        'nova.metric.%s.%s.%s.%s.%s',
        $this->uriKey(),
        $request->input('range', 'no-range'),
        $request->input('timezone', 'no-timezone'),
        $request->input('twelveHourTime', 'no-12-hour-time'),
        $request->user()->id
    );
}
```

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).
