### ISSUE TITLE
Improvement to UX on slow resource (ordering column, searching, pagination)

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#1567]
When a resource is loading you get a loading animation of three dots. Would be nice if this would also be visible when:

* ordering column
* searching resource
* using pagination

Right now a 'fast' load bar is visible (in top op website), but on my slower dev development there is no indication that there's something about to happen. 

Would be better UX to indicate something is going on with a (delayed) loading animation.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍

**Comment by preliot** [comment]
Just updated to 2.0.5 (Followed manual).

I'm not seeing any loading indicators as stated in the changelog:

>  Nova will now show loading indicators for the resource table when fetching new records.

What am i missing? Have some custom views (/resources/vendor/nova/*). Should i add something there?

**Comment by preliot** [comment]
Fixed: Was an issue with nova breadcrumbs package from chris-ware. When package is disabled, all works as expected!

chris-ware/nova-breadcrumbs#14
