### ISSUE TITLE
Panel also on updating screen

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#1568]
I use panels to seperate information, looks great on a detail screen. When i try to edit this information, Panels are _ignored_ and one big screen is shown.

This is troublesome, because i group information with a title. This is what i mean:

**Variable Orgizational Structure**

...
Locations: true
Departments: true
...

On my detailscreen this works perfectly. However when i edit this information, the panel (with header) is missing and the options as standalone items don't make any sense.

**Proposal**

Use panels on edit screen or give developer an option to do so (->withPanels()).

**Comment by christophrumpel** [comment]
Duplicate of #29

**Comment by preliot** [comment]
Did not find that one, thanks. Will add my info there.
