### ISSUE TITLE
Nova Vue component overwrite issue

### ISSUE THREAD

**Issue by Jignasa10** [laravel/nova-issues#1569]
I'm facing issue to overwrite vue component in vendor/laravel/nova folder
For that i'm doing following step
-> Change in vendor/laravel/nova/resources/js/views/ folder's Create.vue file
->run command npm run watch
->laravel mix build successfully
But component have no changes reflects.

Please give me any solutions or suggestions

**Comment by davidhemphill** [comment]
Overwriting Nova's internal components while technically possible, is not supported.
