### ISSUE TITLE
Search and sort by fields of relation is not possible on the index-page

### ISSUE THREAD

**Issue by v1nk0** [laravel/nova-issues#157]
At this moment, the query to select the records on a index-page of a resource does not include any relations that are configured. Due to this, it's not possible to search through fields of relations or sort on fields of relations that are shown in the list.

Simple example: 
I have a `Post` and a `User` resource.
`Post` belongs to `User`.
`User` hasMany `Post`.
The models and Nova resources are set-up correctly. 

When on the index-page of a the posts, I can't search for a post by the name of the user, nor can a sort the list of posts by the name of the user (as a matter of fact, you can add `sortable` to the user-relation, but it will not work as Nova will look for a field 'user' in the posts table and not for the field 'name' within the users table, again the issue with the index-query not containing relations)

I've added the user relation for the `Post` resource as follows, but it does not change anything:
`public static $with = ['user'];`
User is of course the name of the function that I use in the `Post` model to configure the belongsTo user. 

Of course you could 'just' go the `User` resource index-page, search for the user here, open the user's detail-page and look (and search) into the `Posts` there, but as this is just a simplified example there are real-life applications where it makes a lot of sense to be able to search on fields of relations as well. Also, this does not cover the "can't sort by relation field" problem.

I have managed to make it work by overriding the indexQuery of the `Post` resource and add a join with the users table here, but this doesn't feel right as I needed workarounds to avoid problems like "SQL: Not unique table/alias" as Nova DOES automatically make a join when the posts are listed (which is more-or-less also an index for posts) on the `User` resource detail-page. It's also really slow!

**Comment by danrichards** [comment]
You can work around the order as well. https://github.com/laravel/nova-issues/issues/156

**Comment by v1nk0** [comment]
@danrichards this work-around can't be used here.

As soon as you set a certain sorting, Nova automatically adds this to the query. 
If I would use this work-around to sort on the name of a user when in the index-list of the `Post` resource, the query will end up sorting on the `user` field (that does not exists for the `Post` resource) **AND** the sorting that I manually add to `indexQuery` pointing to the `name` field on the `users` table.
This is the main difference with the work-around you are referring to (which adds a certain sorting to the query if NO sorting is set -> **default** sorting)
It would only work if you are able to delete any sorting already set on the query object before adding the custom sorting to the query object.

**Comment by stonkeep** [comment]
Some solution?

**Comment by araeuchle** [comment]
For everybody who wants to achieve this you can use this package: https://github.com/TitasGailius/nova-search-relations. i had the same use case and figured out this was the best way to go as it is not possible in the core

**Comment by Cosmin-Parvulescu** [comment]
> For everybody who wants to achieve this you can use this package: https://github.com/TitasGailius/nova-search-relations. i had the same use case and figured out this was the best way to go as it is not possible in the core

Does it preserve sort options?

**Comment by fico7489** [comment]
take a look at this package https://github.com/fico7489/laravel-eloquent-join
it should help you...

**Comment by josephxwf** [comment]
I really think this should be documented ;)

**Comment by FrittenKeeZ** [comment]
I added this to my `App\Nova\Resource` to enable `BelongsTo` sorting.
```php
/**
 * Apply any applicable orderings to the query.
 *
 * @param  \Illuminate\Database\Eloquent\Builder  $query
 * @param  array                                  $orderings
 * @return \Illuminate\Database\Eloquent\Builder
 */
protected static function applyOrderings($query, array $orderings)
{
    // Fix sort for BelongsTo relations.
    if (!empty($orderings)) {
        $orders = [];
        $model = static::newModel();
        foreach ($orderings as $property => $direction) {
            if (method_exists($model, $property)) {
                $resource = __NAMESPACE__ . '\\' . Str::studly(Str::singular($property));
                if (class_exists($resource)) {
                    $relationship = $model->$property();
                    if ($relationship instanceof BelongsTo) {
                        $related = $relationship->getRelated();
                        $table = $related->getTable();
                        $query->leftJoin(
                            $table,
                            $relationship->getQualifiedForeignKeyName(),
                            '=',
                            $relationship->getQualifiedOwnerKeyName()
                        );
                        $orders[$table . '.' . $resource::$title] = $direction;
                    }
                }
            } else {
                $orders[$property] = $direction;
            }
        }
        $orderings = $orders;
    }

    // Default sorting.
    if (empty($orderings) && property_exists(static::class, 'orderBy')) {
        $orderings = static::$orderBy;
    }

    return parent::applyOrderings($query, $orderings);
}
```

**Comment by iHazzam** [comment]
Thanks

**Comment by davidhemphill** [comment]
There will likely be no plans to implement this feature.

**Comment by mfodor** [comment]
> > For everybody who wants to achieve this you can use this package: https://github.com/TitasGailius/nova-search-relations. i had the same use case and figured out this was the best way to go as it is not possible in the core
> 
> Does it preserve sort options?

Yes it does. Works perfectly for me.

**Comment by stephan-v** [comment]
Please don't just state it won't be implemented, but actually provide a reason as to why not.

**Comment by rodrigopaco1986** [comment]
For those with the sort problem (in a lens in this case), you just need to add the alias name to your joined table(s), and disable the order prefix. I guess for resources it's something similar:
`public static function query(LensRequest $request, $query)
    {
        return $request
            ->withoutTableOrderPrefix()
            ->withOrdering($request->withFilters(
            $query
                ->select(self::columns())
                ->leftJoin('lead_debts', 'lead_debts.lead_id', '=', 'leads.id')
                ->where('vertical_id', LeadType::DEBT)
                ->where('affiliate_name', self::ESSENTIAL_DEBT_AFFILIATE_NAME)
        ));
    }`

`protected static function columns()
    {
        return [
            'leads.*',
            'lead_debts.debt_amount as debt_amount'
        ];
    }`

`Currency::make('Debt Amount', 'debt_amount')
                ->sortable(),`
