### ISSUE TITLE
Overriden Carbon timestamps not saving

### ISSUE THREAD

**Issue by jradtilbrook** [laravel/nova-issues#1572]
- Laravel Version: 5.8
- Nova Version: 2.0.1
- PHP Version: 7.2
- Operating System and Version: Debian
- Browser type and version: Chrome 73.0.3683.103
- Reproduction Repository: N/A

### Description:

When using a model that has changed the default Carbon timestamps to Chronos, trying to update a resource in the Nova UI fails because it tries to pass a Carbon instance into a method requiring a Cake\Chronos\ChronosInterface.

### Steps To Reproduce:

Install [healthengine/laravel-chronos](https://github.com/HealthEngineAU/laravel-chronos) and attach the trait to a model.  
Try to edit/update the resource in Nova results in the error.

I'm not sure how much information is IP so please let me know if you want me to post the line the error occurs on within Nova source code.

I believe the best approach would be to use the eloquent models `asDateTime()` method but this is protected. The next best would be to use the `freshTimestamp()` method and modify the returned object - although for both of these approaches you would need to know the type.

**Comment by dkulyk** [comment]
I don't see methods what required [`Cake\Chronos\ChronosInterface`](https://github.com/cakephp/chronos/blob/master/src/ChronosInterface.php#L23) in `healthengine/laravel-chronos`. Standard for php is `DateTimeInterface`, use it for method typehinting instead `ChronosInterface`. 
Nova always store raw value for date/datetime without convertation to DateTimeInterface implementation.

**Comment by jradtilbrook** [comment]
Yeah the error is that Nova source code uses the models timestamps `gt()` method, and that is the method that always expects a `ChronosInterface` per https://github.com/cakephp/chronos/blob/master/src/ChronosInterface.php#L306. To be honest, I'm not sure this is resolvable but thought I'd raise this issue to see if anyone has ideas how to fix or other options.

**Comment by dkulyk** [comment]
PR was sent to upstream

**Comment by jradtilbrook** [comment]
I'm not following. Have you already made a PR and sent it somewhere, or just an issue? Where did you send it - can you post the link?

**Comment by devfrey** [comment]
@jradtilbrook https://github.com/laravel/nova/pull/398 You can request access via your Laravel Nova account.

**Comment by jbrooksuk** [comment]
This PR was closed as:

> Closing as we don't want to make or maintain changes to accommodate 3rd-party packages that change Laravel core functionality.
