### ISSUE TITLE
Translation key missing

### ISSUE THREAD

**Issue by FaridAghili** [laravel/nova-issues#1574]
- Laravel Version: 5.8.15
- Nova Version: 2.0.3
- PHP Version: -
- Operating System and Version: -
- Browser type and version: -
- Reproduction Repository: -

Description:
Following translation keys are missing in `en.json` file:
```
"The :resource was deleted!"

"The :resource was restored!"
```

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
