### ISSUE TITLE
Trends with MS-SQL: Trend metric helpers are not supported for this database.

### ISSUE THREAD

**Issue by swapnilmonad** [laravel/nova-issues#1577]
- Laravel Version: 5.7
- Nova Version: 1.3.2
- PHP Version: 7.2
- Operating System and Version: Ubuntu 16
- Browser type and version: Chrome 73
- Reproduction Repository: -

### Description:
Error: Trend metric helpers are not supported for this database.
There is no support for MS-SQL in` nova/src/Metrics/TrendDateExpressionFactory.php`

`switch ($query->getConnection()->getDriverName()) {
    case 'sqlite':
        return new SqliteTrendDateExpression($query, $column, $unit, $timezone);
    case 'mysql':
    case 'mariadb':
        return new MySqlTrendDateExpression($query, $column, $unit, $timezone);
    case 'pgsql':
        return new PostgresTrendDateExpression($query, $column, $unit, $timezone);
    default:
          throw new InvalidArgumentException('Trend metric helpers are not supported for this database.');
}`

Reference from  [Mariadb](https://github.com/laravel/nova-issues/issues/162) But similarly not working for MS-SQL.

Issue:  "SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near '5.5'. (SQL: select date_format([created_at] + INTERVAL 5.5 HOUR, '%Y-%m-%d') as date_result, count([users].[user_id]) as aggregate from [users] where [created_at] between 2019-04-09 00:00:00.000 and 2019-05-08 05:23:21.860 group by date_format([created_at] + INTERVAL 5.5 HOUR, '%Y-%m-%d') order by [date_result] asc)"

### Steps To Reproduce:
Just created a Metrics using [Laravel Nova Metrics](https://nova.laravel.com/docs/1.0/metrics/defining-metrics.html#value-metrics)

**Comment by swapnilmonad** [comment]
@davidhemphill Please help with this issue.

**Comment by davidhemphill** [comment]
Sorry, but we've no plans to implement these helpers for MSSQL.
