### ISSUE TITLE
SelectControl dont change value on IE Edge

### ISSUE THREAD

**Issue by AndreasGJ** [laravel/nova-issues#1578]
- Laravel Version: v5.8.*
- Nova Version: v2.0.3
- PHP Version: v7.1.3
- Browser type and version: IE Edge v18

### Description:
The `select-control` component is not catching the `input` event on `<select>` tags. It will only catch `change` events, and all browsers will catch that, so I had to change the `inputListeners` computed value to return an object with `change` instead of `input`.

### Steps To Reproduce:
Open a nova Resource which uses the `Select` field in IE Edge, and then try to change the `Select` field, and save. Then you will see that the value isn't changed.

### How to fix it:
Change the file in the nova package (or just overwrite the `select-control` component) `resources/js/components/Controls/SelectControl.vue`, starting at line 37 to 43:
```javascript
      inputListeners() {
            return _.assign({}, this.$listeners, {
                change: event => {
                    this.$emit('input', event.target.value)
                },
            })
        },
```
where the old code was:
```javascript
      inputListeners() {
            return _.assign({}, this.$listeners, {
                input: event => {
                    this.$emit('input', event.target.value)
                },
            })
        },
```

**Comment by victorpfm** [comment]
Just realized this edit breaks select-filters.
Added this:
```
putListeners() {
            return _.assign({}, this.$listeners, {
                change: event => {
                    this.$emit('input', event.target.value)
                    this.$emit('change'), event)
                },
            })
        },
```

And select filters are working properly now.

**Comment by pvdptje** [comment]
Your fix has syntax errors.

**Comment by jbrooksuk** [comment]
Thanks @pvdptje, I've made a PR with your change in it.

**Comment by halah-m** [comment]
@jbrooksuk I want to ask if the bug fix was rejected ? because I'm facing this issue while using Dusk for my tests and I want to know if I should hardcode the fix to nova main folder or I should wait for the fix to be merge..

thank you

**Comment by jbrooksuk** [comment]
The fix went in a couple of versions ago.

**Comment by MuhammadSulman** [comment]
@pvdptje thanks for your contribution. But, I am facing another issue.Your implemented change has been updated in new version, but, I am on old one.
