### ISSUE TITLE
Laravel Nova Metrics Value format not working

### ISSUE THREAD

**Issue by ricardomiguelvieira** [laravel/nova-issues#1579]
I can't seem to get Nova's formatting for the Value Metrics to work. Simply nothing happens when I add the property to my return. The format remains as Nova's default.

Any hints on what might be wrong?

```
$total = DB::table(hello')->sum(DB::raw('bye'));
return $this->result($total)->format("0,0");
```

**Comment by davidhemphill** [comment]
Sorry, but we are unable to debug your issue without a reproducible code example. I'm able to format integer values from database results in the current version.

**Comment by TiGR** [comment]
@ricardomiguelvieira see #620
