### ISSUE TITLE
Click row to select

### ISSUE THREAD

**Issue by jsiebach** [laravel/nova-issues#158]
It would be nice to select records by clicking on the row in the index view.

**Comment by reganjohnson** [comment]
Maybe a double click to prevent unintended clicks when trying to copy something from the index.

**Comment by jsiebach** [comment]
@reganjohnson yes, maybe some UX testing to make sure it feels right, and/or just configurable in the nova config. Currently I've been clicking them feeling like it should be selecting them.

**Comment by noahlocke** [comment]
+1

**Comment by Andy-Baker** [comment]
Yep it feels a bit weird without this.

**Comment by taylorotwell** [comment]
This repository is for tracking bugs. Feature requests may be emailed to Nova customer support.

**Comment by aurawindsurfing** [comment]
Anyone got a simple way to get it to work? @taylorotwell where should we ask each other, please? Is there a proper repository for asking for features and support? It feels a bit weird to email support with each question that people might have. Thanks!

**Comment by hsharghi** [comment]
Found this package [Nova clickable row](https://packagist.org/packages/ryanw3b3r/nova-clickable-row) but it seems the package is now abandoned. Does anyone know the author?

**Comment by tom-it** [comment]
> Found this package [Nova clickable row](https://packagist.org/packages/ryanw3b3r/nova-clickable-row) but it seems the package is now abandoned. Does anyone know the author?

Hi, I found a fork of it right here: https://packagist.org/packages/ibilcu/nova-clickable-row

**Comment by jordyvandomselaar** [comment]
The fork doesn't seem to work :(
