### ISSUE TITLE
Nova Version - cant know current version of the Nova

### ISSUE THREAD

**Issue by h-zone** [laravel/nova-issues#1581]
Hi!

Due to the fact that the Nova version is not registered anywhere, I consider it impossible to identify the version of this Nova.

Please, add `/VERSION` file with version number as content.

**Comment by bolechen** [comment]
`Laravel\Nova\Nova::version()` can get current version.

**Comment by h-zone** [comment]
yes, if we in the framework.
and how to otherwise..?

**Comment by davidhemphill** [comment]
What problem are you trying to solve by asking us to add this?

**Comment by h-zone** [comment]
I'm just lost in the vendor / laravel / nova directory
trying to determine which version is installed

**Comment by davidhemphill** [comment]
There will likely be no plans to implement this feature.

**Comment by jeffsrepoaccount** [comment]
For reference you should be able to see what version is installed for edification purposes by just looking into the composer.json file. HTH

**Comment by ivanderbu2** [comment]
Why don't you use tinker?

`php artisan tinker` and then `Laravel\Nova\Nova::version();`

**Comment by dkulyk** [comment]
https://nova.laravel.com/docs/2.0/installation.html#installing-nova-via-composer

**Comment by maninchiev** [comment]
> Why don't you use tinker?
> 
> `php artisan tinker` and then `Laravel\Nova\Nova::version();`

Thanks, @ivanderbu2
