### ISSUE TITLE
Column 'id' in order clause is ambiguous.

### ISSUE THREAD

**Issue by covobo** [laravel/nova-issues#1582]
- Laravel Version: 5.8.15
- Nova Version: 2.0.3
- PHP Version: 7.2.12
- Operating System and Version: CentOS 7, MySQL 8
- Browser type and version: any

### Description:

When you join other tables to resource (for example inner join as a filter) and you sort resource by ID then you get an exception "Column 'id' in order clause is ambiguous"

### Steps To Reproduce:

Create some resource with ID field

```
public function fields(Request $request)
{
  return [
    ID::make()->sortable(),
  ];
}
```

Add some join in filter
```
public function apply(Request $request, $query, $value)
{
        if (!empty($value['filter_is_active'])) {
            $query->join('other_table', 'other_table.foreign_key', '=', 'resource.id'));
        }
}
```

Open browser and try to sort resource by ID

### Idea to fix:

Column ID is ambiguous so I'd like to concrete column name by table reference
```ID::make()->sortable('resource.id')```

**Comment by covobo** [comment]
I can concrete attribute by second argument

```
ID::make('ID', 'resource.id')->sortable(),
```

sorting works but I can't see the ID of entity, it's just empty

![screenshot](https://user-images.githubusercontent.com/6328862/57408749-2c8be980-71ef-11e9-9bab-38f788e384b5.png)

**Comment by dillingham** [comment]
That’s not a bug just a non explicit join. 

Add your selects manually and make sure the main resource is id as nova would expect and make the joined tables id an alias.

**Comment by Raminsadeghi** [comment]
I solve the problem this way:
In problematic resource (here Nova\User) we can override method like this:
```
    public static function applyOrderings($query, array $orderings)
    {
        if (empty($orderings) && property_exists(static::class, 'orderBy')) {
            $orderings = static::$orderBy;
        }

        if(array_key_exists('id', $orderings)) {
            $orderings['users.id'] = $orderings['id'];
            unset($orderings['id']);
        }

        return parent::applyOrderings($query, $orderings);
    }

```

**Comment by robclancy** [comment]
If anyone comes across this issue I updated my base classes `indexQuery` to...
```php
public static function indexQuery(NovaRequest $request, $query)
    {
        return $query->select($query->getModel()->getTable() . '.*');
    }
````
