### ISSUE TITLE
Editable header for KeyValue Field

### ISSUE THREAD

**Issue by gkermer** [laravel/nova-issues#1583]
Hello,
is it possible to make the header/label for the KeyValue Field editable?
![grafik](https://user-images.githubusercontent.com/8224376/57437739-aef1c900-7242-11e9-9f7a-415e43e75fd0.png)

Maybe by extending the KeyValue class?
`KeyValue::make('Field')->labelKey('Custom Key')->labelValue('Custom Value')`

**Comment by davidhemphill** [comment]
In the next release, you'll be able to do the following:

```php
KeyValue::make('Meta')
    ->keyLabel('Item') // Customize the key heading
    ->valueLabel('Label') // Customize the value heading
    ->actionText('Add Item'), // Customize the "add row" button text
```

**Comment by pleone** [comment]
@davidhemphill would be nice to have that in the docs ;)

**Comment by davidhemphill** [comment]
https://nova.laravel.com/docs/2.0/resources/fields.html#keyvalue-field

**Comment by pleone** [comment]
@davidhemphill thansk, maybe i'm blind, but i can't see any mention to actionText(), keyKabek() or valueLabel()

Am i missing something ?

**Comment by davidhemphill** [comment]
<img width="906" alt="image" src="https://user-images.githubusercontent.com/58970/67692810-b7fc6100-f96e-11e9-941c-7c58c7e4e7a5.png">

**Comment by pleone** [comment]
LoL. did you just changed it? :dagger:
