### ISSUE TITLE
Feature Request: Please add User Profile edit in user menu near to Log out

### ISSUE THREAD

**Issue by wemersonrv** [laravel/nova-issues#1584]
Hello, 

Please add User Profile feature, so logged users can update their own stored data, without access it in User resource, and in this profile we can decide if we will remove password field from profile.

How do you think about it ?

This feature can be added in user Menu near to Logout Menu.

**Comment by bolechen** [comment]
u can modify `user.blade.php` self like this

```php
        <li>
            <router-link :to="{
                name: 'detail',
                params: {
                    resourceName: 'members',
                    resourceId: '{{ $user->id }}'
                }
            }" class="block no-underline text-90 hover:bg-30 p-3">
            Profile
            </router-link>
        </li>
```

**Comment by wemersonrv** [comment]
> u can modify `user.blade.php` self like this
> 
> ```
>         <li>
>             <router-link :to="{
>                 name: 'detail',
>                 params: {
>                     resourceName: 'members',
>                     resourceId: '{{ $user->id }}'
>                 }
>             }" class="block no-underline text-90 hover:bg-30 p-3">
>             Profile
>             </router-link>
>         </li>
> ```

Tx my friend. It works.

**Comment by wemersonrv** [comment]
Tx my friend. It works.

**Comment by JoshMoreno** [comment]
Little correction for out of the box laravel - change `members` to `users`

```html
<li>
            <router-link :to="{
                name: 'detail',
                params: {
                    resourceName: 'users',
                    resourceId: '{{ $user->id }}'
                }
            }" class="block no-underline text-90 hover:bg-30 p-3">
            Profile
            </router-link>
        </li>
```

**Comment by RehmanAkbar** [comment]
Hi, I needed the same functionality and  @bolechen  your solution work, I just want to know is there is a why to hide some fields on details page

**Comment by jonmenard** [comment]
You can now use the NovaServiceProvider to customize the user menu:


```php
  Nova::userMenu(function (Request $request, Menu $menu) {
        return $menu
            ->append(
                MenuItem::make(
                    'My Profile',
                   "/resources/users/{$request->user()->getKey()}"
                )
           );
   });
```
