### ISSUE TITLE
Infinite request loading still occurs in v2.0.3 on resource detail page

### ISSUE THREAD

**Issue by phoenixg** [laravel/nova-issues#1586]
- Laravel Version: 5.7.0
- Nova Version: 2.0.3
- PHP Version: 7.2
- Operating System and Version: MaxOS Mojave
- Browser type and version: Chrome

**Comment by bolechen** [comment]
you need run `nova:publish`

**Comment by davidhemphill** [comment]
Make sure to republish your assets. This was definitely fixed in the latest version. Use the `--force` flag if needed.

`php artisan nova:publish --force`
