### ISSUE TITLE
Package localization in .vue

### ISSUE THREAD

**Issue by InfinityWebMe** [laravel/nova-issues#1587]
- Laravel Version: 5.8.15
- Nova Version: 2.0.3
- PHP Version: 7.3.4
- Operating System and Version: macOS 10.14.4
- Browser type and version: Firefox Dev 67b014

### Description:

The localization of the packages for the resources such as .vue files doesn't work with the "resources/lang/vendor/{package}/{locale}" structure, while for php files it works.

The localizations of the .vue must be placed in resources/lang/vendor/nova/{locale}.json

Is it planned that .vue files can use the vendor structure too ?

Thanks

**Comment by davidhemphill** [comment]
I'm not sure what you're asking exactly, but you should be able to translate your Vue files using the same mechanism as Nova's built-in components.

**Comment by InfinityWebMe** [comment]
@davidhemphill 

It's not working for Vue file if i use the path of my package, example : __("nova-tool::Update") in /resources/lang/vendor/nova-tool/en.json
