### ISSUE TITLE
Relation name should be singularLabel

### ISSUE THREAD

**Issue by disitec** [laravel/nova-issues#159]
Relation name is being singularized instead of using the resource singularLabel. See attached screenshots.

![image](https://user-images.githubusercontent.com/12644599/44605150-8f1b9180-a7e8-11e8-91e0-70b9450e2021.png)

![image](https://user-images.githubusercontent.com/12644599/44605184-a78bac00-a7e8-11e8-8f2b-a803102f3edb.png)

![image](https://user-images.githubusercontent.com/12644599/44605204-ba05e580-a7e8-11e8-902f-1ee21d20bed5.png)

![image](https://user-images.githubusercontent.com/12644599/44605503-e40bd780-a7e9-11e8-9351-aaf34042cbe4.png)

**Comment by taylorotwell** [comment]
Looks correct to me.

**Comment by disitec** [comment]
@taylorotwell I think this actually a bug. I was referring to singularLabel method in the resource.

if you do this

```php

    /**
     * Get the displayble label of the resource.
     *
     * @return string
     */
    public static function label()
    {
        return 'Clientes';
    }

    /**
     * Get the displayble singular label of the resource.
     *
     * @return string
     */
    public static function singularLabel()
    {
        return 'Cliente';
    }
```

Nothing changes in the BelongsTo Field. 

![image](https://user-images.githubusercontent.com/12644599/45175782-7f4f7480-b20e-11e8-9642-287fd82173d5.png)

Other ones have been already fixed.

Thanks!
