### ISSUE TITLE
Global search limit configurable

### ISSUE THREAD

**Issue by artisaninweb** [laravel/nova-issues#1590]
The global search has a limit of 5 items per resource.
A client of mine want's to override this limit by a custom limit.
Is it possible to make this configurable so we can override the limit?

(I know this will have impact on the speed of the search).

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

Also, not a bad feature really. ;-)
