### ISSUE TITLE
Filter resets on field sorting

### ISSUE THREAD

**Issue by HenriqueSPin** [laravel/nova-issues#1591]
- Laravel Version: 5.8.15
- Nova Version: 2.0.3
- PHP Version: 7.1.4
- Operating System and Version: Ubuntu 18
- Browser type and version: Chrome

### Description:

When a resource has a filter with a default value, when click on a sortable column (field) it always resets to default filter value.

**Comment by wvervuurt** [comment]
I just checked this, it works fine for me under Laraval 5.8.17 and Nova 2.0.4.
Perhaps it was fixed in a recent update.
I suggest you do a composer update to see if the problem persists.

**Comment by HenriqueSPin** [comment]
Nope. Just updated Nova to 2.0.4, it persists.

Let's say you have a category filter (select). If you select one of the list and then clicks in some sortable field column header, the filter vanishes.

If you have a default() in your filter class, the filter gets back to this value.

**Comment by wvervuurt** [comment]
Doing just that but I can't reproduce the problem.
Can you post your Filter implementation?

**Comment by HenriqueSPin** [comment]
```php
class StockOrderStatus extends Filter
{
    /**
     * Apply the filter to the given query.
     *
     * @param Request $request
     * @param  Builder|StockOrder $query
     * @param int  $value
     * @return Builder
     */
    public function apply(Request $request,  $query, $value): Builder
    {
        if ($value && $value !== 'all') {
            return $query->whereStockOrderStatusId($value);
        }
        return $query;
    }

    /**
     * Get the filter's available options.
     *
     * @param Request $request
     * @return array
     */
    public function options(Request $request): array
    {
        $options = StockOrderStatusModel::pluck('description', 'id');

        $options->prepend( __('All'), 'all');

        return $options->flip()->all();
    }

    /**
     * Set the default options for the filter.
     *
     */
    public function default()
    {
        return StockOrderStatusModel::PENDING;
    }
}
```

**Comment by HenriqueSPin** [comment]
Sorry... the default filter work just fine. I'm using a package, and the package has the problem. I'm making a PR to their repo. 

[Filter Card](https://novapackages.com/packages/awesome-nova/filter-card)
