### ISSUE TITLE
Customizing Partition Colors

### ISSUE THREAD

**Issue by oleksiyPetlyuk** [laravel/nova-issues#1592]
- Laravel Version: 5.8.16
- Nova Version: 2.0.3
- PHP Version: 7.2.17
- Operating System and Version: Ubuntu 16.04
- Browser type and version: Chrome

### Description:
It's impossible to customize partition metric colors only for some of returning types.
http://prntscr.com/nnzams
Seems that Laravel\Nova\Metrics\PartitionColors::next() trying to get value in $this->colors by undefined index $this->pointer % count($this->colors).
http://prntscr.com/nnzdk8
### Steps To Reproduce:
1. Create a new Partition Metric
2. Try to customize the color for some of the returning type

**Comment by davidhemphill** [comment]
This is not a bug. Nova expects a full list of colors matching the keys for situations when you know the keys. If you don't know the keys until runtime, you should use a simple list.

**Comment by Donkfather** [comment]
How do you set the keys ?

**Comment by Donkfather** [comment]
ah.. the keys are actually the labels.. https://github.com/laravel/nova/pull/115

**Comment by TylerMitton** [comment]
According to this documentation, you can just provide a list of colors for some of the values and it should use the default colors for the rest:

[https://nova.laravel.com/docs/2.0/metrics/defining-metrics.html#customizing-partition-colors](https://nova.laravel.com/docs/2.0/metrics/defining-metrics.html#customizing-partition-colors)

But it doesn't work like that for me. Am I doing something wrong, or is that documentation not correct?
