### ISSUE TITLE
Column 'actionable_id' cannot be null

### ISSUE THREAD

**Issue by fede91it** [laravel/nova-issues#1595]
- Laravel Version: 5.8.16
- Nova Version: 2.0.3
- PHP Version: 7.3.0

### Description:

I got this error trying to save a new record for a model:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'actionable_id' cannot be null (SQL: insert into `action_events` (`batch_id`, `user_id`, `name`, `actionable_type`, `actionable_id`, `target_type`, `target_id`, `model_type`, `model_id`, `fields`, `status`, `exception`, `updated_at`, `created_at`) values (8daef794-77ee-4a63-829f-3387ae8be0a4, 1, Create, App\Models\LocationSupplier, ?, App\Models\LocationSupplier, ?, App\Models\LocationSupplier, ?, , finished, , 2019-05-14 09:29:35, 2019-05-14 09:29:35))

**Comment by agilasadi** [comment]
Got any luck so far?

**Comment by vDk3** [comment]
This error happens if you return false inside model observer "creating" event.

**Comment by fede91it** [comment]
No, there's no observer coming in here.

I noticed something very strange. I started using Nova from version 1.x and now we're at 2.0.3 but I never launched the command `php artisan nova:publish --force` to recreate Nova's js and css assets.

The above problem only occurs with updated assets. If I use the old one everything goes smoothly.

How is that possible? What do assets have to do with it?

**Comment by fede91it** [comment]
This error occurs when the model for the nova  resource is an instance of \Illuminate\Database\Eloquent\Relations\Pivot instead of \Illuminate\Database\Eloquent\Model

Why?

**Comment by fede91it** [comment]
Overriding `public $incrementing = true` it solves the problem.

**Comment by hubtraum** [comment]
This happened to me as well. The problem was a belongsTo relationship with mixed up column definitions in the laravel model (swapped 'foreign_key', 'owner_key' by mistake).
