### ISSUE TITLE
[2.0.4] nova.logout route is not defined

### ISSUE THREAD

**Issue by Cannonb4ll** [laravel/nova-issues#1596]
- Laravel Version: 5.8.17
- Nova Version: 2.0.4
- PHP Version: 7.2
- Operating System and Version: MacOS
- Browser type and version: Chrome

### Description:
After upgrading to Nova 2.0.4 I keep getting this error:

```
Route [nova.logout] not defined. (View: /Users/***/Workspace/project/resources/views/vendor/nova/partials/user.blade.php) (View: /Users/***/Workspace/project/resources/views/vendor/nova/partials/user.blade.php) (View: /Users/***/Workspace/project/resources/views/vendor/nova/partials/user.blade.php)
```

When I enable registration routes it is all fine, but I do not want these:

```php
        Nova::routes()
//                ->withAuthenticationRoutes()
//                ->withPasswordResetRoutes()
                ->register();
```

**Comment by Cannonb4ll** [comment]
My own user.blade.php partial had this, solved now.

**Comment by devfrey** [comment]
Honestly, why was this change introduced in a patch version? I have the same problem.

**Comment by elijahworkz** [comment]
I have the same issue, but I don't want to enable Nova AuthenticationRoutes() - we have login page that needs to be used both for frontend and nova.

So the only solution is to change the user.blade.php but since Auth::routes registers logout as POST

So how can native Auth::routes be used with Nova?

**Comment by ahmedkandel** [comment]
@elijahworkz if you don't want to use Nova routes and will override user.blade.php use can replace:
```
<li>
        <a href="{{ route('nova.logout') }}" class="block no-underline text-90 hover:bg-30 p-3">
                {{ __('Logout') }}
        </a>
</li>
```
with:
```
<li>
    <form id="logout-form" method="POST" action="{{ route('logout') }}" style="display: none;">
        @csrf
    </form>
    <a href="#" class="block no-underline text-90 hover:bg-30 p-3" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
        {{ __('Logout') }}
    </a>
</li>
```

**Comment by elijahworkz** [comment]
@ahmedkandel  Thanks. That's what I ended up doing. It just seems that this should be a breaking change.

**Comment by jankremlacek** [comment]
same issue here, not complaining, @davidhemphill vendor files (`user.blade.php`) should not use the route if not enabled in NovaServiceProvider, it's confusing, thank you.
