### ISSUE TITLE
Any plan to update Nova to use tailwind 1.x ?

### ISSUE THREAD

**Issue by haoyuguo** [laravel/nova-issues#1597]
Tailwind 1.0 is out, and the changes seem to be significant.  I wonder if there's any plan to update Nova to use Tailwind 1.x in the near future ?  Thanks!

**Comment by dkulyk** [comment]
See https://github.com/laravel/nova/pull/419

**Comment by davidhemphill** [comment]
There is planning and work done to maybe do this, but doing so could affect a lot of 3rd-party packages, and so we'll definitely hold off until we're ready to do that breaking change.

**Comment by vesper8** [comment]
Looking forward to an updated Nova with Tailwind 2.x support =D
