### ISSUE TITLE
Unable to interpret update XXX in Multilingualism

### ISSUE THREAD

**Issue by xiyixia** [laravel/nova-issues#1598]
- Laravel Version: 5.8.16
- Nova Version: 2.0.4
- PHP Version: 7.2

### Description:
when i upgrade to nova 2.0.4 the Multilingualism has no effect , 
eg: 
- 1.  Set the default language to zh-CN
- 2.  Set resource singularLable is  "你好，世界" 
- 3. The resource button's Translate into ”Update 你好，世界“  on form

i thougth maybe something wrong  with the function __(key,replace) in resource/js/base.js 

hope to fix it !

**Comment by bolechen** [comment]
add the new translate string to `zh_CN.json` file

```javascript
    "New :resource": "新建 :resource",
    "Update :resource": "更新 :resource",
```

**Comment by xiyixia** [comment]
> add the new translate string to `zh_CN.json` file
> 
> ```js
>     "New :resource": "新建 :resource",
>     "Update :resource": "更新 :resource",
> ```

it's done ! thanks !

by the way the en.json file has no the keys 'New :resource', 'Edit :resource', 'Update :resource'

**Comment by bolechen** [comment]
cc @davidhemphill

**Comment by bolechen** [comment]
2.0.5 fixed this issue

**Comment by davidhemphill** [comment]
This should be fixed in the latest release.
