### ISSUE TITLE
resolveUsing not called on empty attribute

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#1599]
- Laravel Version: 5.8.16
- Nova Version: 2.0.3
- PHP Version: 7.2.10
- Operating System and Version: Windows 10
- Browser type and version: Chrome 74 (64 bits)

### Description:

Because of an external package, i need the possibility to change the $id. In my simplified example i add the parent_id. However, resolveUsing is not called on an empty parameter, which causes my code to fail.

### Steps To Reproduce:

1. Create a Nova field
2. Add method resolveUsing() to field.

**Simplified** example:

`->resolveUsing(function($id) {`
`   $parent_id = $this->model()->parent_id;`
`   return $parent_id .  ':' . $id;`
`});`

3. Open resource in browser (or check breakpoint in ide) and see resourceUsing was not called.

**Comment by preliot** [comment]
Seems related to #1277

**Comment by jbrooksuk** [comment]
This issue relates to an older version of Nova. It's possible that this bug has been fixed in recent versions. If you're still experiencing this in the latest version of Nova, please re-open this ticket, thanks!
