### ISSUE TITLE
Converting dates to application's timezone

### ISSUE THREAD

**Issue by bonzai** [laravel/nova-issues#16]
- Nova Version: 1.0.5

### Description:

Converting the value of the `DateTime` from the user's timezone to application's timezone doesn't work if the time after converting is midnight.

### Steps To Reproduce:

1. Create a `DateTime` field in the resource.
2. Force the user's timezone in the `NovaServiceProvider::boot()` method to `Europe/Warsaw` (UTC+02:00):

```php
Nova::userTimezone(function (Request $request) {
    // app.timezone = 'UTC'
    return 'Europe/Warsaw';
});
```

3. Set the value of the field to `2018-08-21 02:00:00`.
4. Save the resource.

Nova's trying to save it as `2018-08-21 24:00:00` instead of `2018-08-21 00:00:00`:

![nova_date_converting_bug](https://user-images.githubusercontent.com/98191/44531649-9ca22000-a6f1-11e8-92c3-138ef3be52d7.png)

**Comment by themsaid** [comment]
@davidhemphill can you take a look?
