### ISSUE TITLE
If else condition in belongsto field

### ISSUE THREAD

**Issue by aozen** [laravel/nova-issues#1600]
Hello everyone, 
I need to add if else condition on belongsto field, like this: 

if($post->category = "A") {
BelongsTo::make('Post', 'post', 'App\Nova\A')
} elseif($post->category = "B") {
BelongsTo::make('Post', 'post', 'App\Nova\B')
}

Posts call models from it category, our structure is dynamic in here. There is 4 category actually. Each post has one category. So i can't just say:

BelongsTo::make('Post', 'post', 'App\Nova\A')

because each category is different. 

How can i handle this? Any idea would be great, thanks in advance.

**Comment by skalero01** [comment]
You can add logic on the nova resource, have you tried the next code?

```
    public function fields(Request $request)
    {
        $inputs = [
            // Your fields
        ];
        if($this->category = "A") {
                $inputs[] = BelongsTo::make('Post', 'post', 'App\Nova\A')
        } elseif($this->category = "B") {
                $inputs[] = BelongsTo::make('Post', 'post', 'App\Nova\B')
        }
        return $inputs;
    }
```

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).
