### ISSUE TITLE
Cannot show the pivot attributes of a BelongsToMany

### ISSUE THREAD

**Issue by fede91it** [laravel/nova-issues#1601]
- Laravel Version: 5.8.16
- Nova Version: 2.0.3
- PHP Version: 7.3.0

### Description:

Here in the screenshot is the resource linked to the Location model (locations table), which shows the BelongsToMany field of the Supplier model (suppliers table).

The problem is that where there is the arrow in the screenshot I would like to show the fields of the pivot table (location_supplier table) and it seems that this on Nova is not possible, but why? It should make sense to be able to display the pivot fields here, in a detail page. Is there a way to do this?

![image](https://user-images.githubusercontent.com/346224/57778912-5ed4a400-7725-11e9-909b-5ba0687c30b1.png)

**Comment by wvervuurt** [comment]
Hey, did you check [the docs](https://nova.laravel.com/docs/2.0/resources/relationships.html#belongstomany)?

Check out the part that describes passing an invokable object to the `fields` method

**Comment by fede91it** [comment]
I can only see the pivot fields if, from both resources, I show the BelongsToMany field in the index and use the fields method.

Why can't I show fields from one resource and hide them from the other? Why do I have to declare the BelongsToMany field in both resources? Maybe this is a bit of a strange forcing, don't you think?

**Comment by jbrooksuk** [comment]
This issue relates to an older version of Nova. It's possible that this bug has been fixed in recent versions. If you're still experiencing this in the latest version of Nova, please re-open this ticket, thanks!

**Comment by fede91it** [comment]
Which commit is the one that solves this issue?


Federico. On Fri, Aug 09, 2019 at 11:37am, James Brooks < notifications@github.com [notifications@github.com] > wrote:
This issue relates to an older version of Nova. It's possible that this bug has been fixed in recent versions. If you're still experiencing this in the latest version of Nova, please re-open this ticket, thanks!
