### ISSUE TITLE
Unable to get KeyValue Field to work.

### ISSUE THREAD

**Issue by tanthammar** [laravel/nova-issues#1602]
- Laravel Version: v5.8.17
- Nova Version: v2.0.4
- PHP Version: 7.3.2

### Description:
Trying to use KeyValue Field as documented.
- The field does not show either on Edit or Detail.
- Unable to save the Resource on Edit 
-- (I can save/update if I remove the KeyValue field)
- I have existing values in DB.

### Steps To Reproduce:
Existing data stored in `meta`, MySql type `JSON` field:
```json
{
	"stripe_id": "xxxxxxxxx",
	"approved_terms": "1",
	"active_subscriber": "1",
	"approved_terms_at": "2018-05-30 06:05:43",
	"created_exhibitor": "1",
	"weekly_billing_id": "xxxxxxxxxxxx",
	"subscription_plan_id": "xxxxxxxx",
	"subscription_plan_name": "xxxxxx",
	"managed_account_plan_id": "xxxxxxxxx"
}
```
On Model
```js
//tried this
protected $casts = [
   'meta' => 'array',
];
//and this
protected $casts = [
   'meta' => 'json',
];
//and this
protected $casts = [
];
```
On Nova Resource
```js
use Laravel\Nova\Fields\KeyValue;
KeyValue::make('Meta')->rules('json'),
```

**Comment by wvervuurt** [comment]
What error message do you get when trying to save with the KeyValue field present on the Nova resource?

**Comment by davidhemphill** [comment]
I was not able to reproduce your issue. I have a KeyValue field, with a nullable json column type, cast as `array`, filled with your example JSON, and the field is working correctly. Make sure you assets are updated using `php artisan nova:publish --force`. If you find out a way to reproduce this, please open another issue. Thanks!

**Comment by WhitePolice** [comment]
Throws "Array to string conversion" when used with "Many-to-Many" relationship.

```
// Roles
protected $casts = [
  'meta' => 'array',
];

public function users()
{
  return $this->belongsToMany(User::class)->withPivot('meta');
}

// Users
protected $casts = [
  'meta' => 'array',
];

public function roles()
{
  return $this->belongsToMany(Role::class)->withPivot('meta');
}

// Nova User Resource
BelongsToMany::make('Roles')
  ->fields(function () {
    return [
      KeyValue::make('Meta')->rules('json'),
    ]
  });
```

**Comment by AbhishekpandeyNexio** [comment]
I have also same

> * Laravel Version: v5.8.17
> * Nova Version: v2.0.4
> * PHP Version: 7.3.2
> 
> ### Description:
> Trying to use KeyValue Field as documented.
> 
> * The field does not show either on Edit or Detail.
> * Unable to save the Resource on Edit
>   -- (I can save/update if I remove the KeyValue field)
> * I have existing values in DB.
> 
> ### Steps To Reproduce:
> Existing data stored in `meta`, MySql type `JSON` field:
> 
> ```json
> {
> 	"stripe_id": "xxxxxxxxx",
> 	"approved_terms": "1",
> 	"active_subscriber": "1",
> 	"approved_terms_at": "2018-05-30 06:05:43",
> 	"created_exhibitor": "1",
> 	"weekly_billing_id": "xxxxxxxxxxxx",
> 	"subscription_plan_id": "xxxxxxxx",
> 	"subscription_plan_name": "xxxxxx",
> 	"managed_account_plan_id": "xxxxxxxxx"
> }
> ```
> 
> On Model
> 
> ```js
> //tried this
> protected $casts = [
>    'meta' => 'array',
> ];
> //and this
> protected $casts = [
>    'meta' => 'json',
> ];
> //and this
> protected $casts = [
> ];
> ```
> 
> On Nova Resource
> 
> ```js
> use Laravel\Nova\Fields\KeyValue;
> KeyValue::make('Meta')->rules('json'),
> ```
I have also same issue i unable to get value in KeyValue.

**Comment by sirikkoster** [comment]
Try

```php
protected $casts = [
  'meta' => 'collection',
];
```

**Comment by kumarkishan070997** [comment]
tried everything but still getting the same error -- array to string conversion

**Comment by yazeed** [comment]
Same here, tried collection, array, and AsArrayObject::class casting on the pivot model, still won't work. Latest Nova version, and Laravel 9+
