### ISSUE TITLE
Partition Metrics - No color in legend on scrolling if result > 55

### ISSUE THREAD

**Issue by sidorenkoda** [laravel/nova-issues#1605]
- Laravel Version: 5.8.16
- Nova Version: 2.0.5
- PHP Version: 7.2.9
- Operating System and Version: macOs Mojave
- Browser type and version: 73.0.3683.103
- Reproduction Repository: https://github.com/###/###

### Description:

No color in legend of Partition Metrics on scrolling if result > 55
http://prntscr.com/np77o6
### Steps To Reproduce:

php artisan nova:partition CarBrandsPercents

**Comment by jbrooksuk** [comment]
This is because the `PartitionMetric` only has 10 colours configured so that they can deterministically generated per-index.

It may be possible for you to [override the colours](https://nova.laravel.com/docs/2.0/metrics/defining-metrics.html#customizing-partition-colors) though.
