### ISSUE TITLE
Javascript error on datepicker

### ISSUE THREAD

**Issue by Xpedigo** [laravel/nova-issues#1609]
- Laravel Version: 5.8
- Nova Version: 2.0.5
- PHP Version: 7.2
- Operating System and Version: Ubuntu 18
- Browser type and version: Chrome  Version 74.0.3729.157 (Build officiel) (64 bits)

### Description:

Hi,

Here is the bug discovered on datepicker calender on list : 

http://bit.ly/2LMeqVv

Thank you.

**Comment by davidhemphill** [comment]
Sorry, but we are unable to debug your issue without a reproducible code example. Once you provide that we can open this up again.
