### ISSUE TITLE
Take app/Models directory into account

### ISSUE THREAD

**Issue by dsampaolo** [laravel/nova-issues#161]
My Models are located in a app/Models directory. 

It would be nice if I could specify the basepath to my models to Nova in order for it to reference the right namespace when I create Resources.

Actullay I have to edit each Resource I create. It works but it can be a bit cumbersome.

What do you think ?

**Comment by telkins** [comment]
This would be a nice feature for Laravel, in general....imho.  :-)

**Comment by fletch3555** [comment]
That's a common pattern in Laravel.  If you do something different than the default/standard, then you have to do work to account for that.  I doubt it'll change, but I wouldn't mind seeing a "model namespace" config option

**Comment by davidhemphill** [comment]
Sorry all, no plans to change this behavior
