### ISSUE TITLE
Can't run destructive action without delete authorization

### ISSUE THREAD

**Issue by chescos** [laravel/nova-issues#1611]
- Laravel Version: 5.7.28
- Nova Version: 2.0.9
- PHP Version: 7.2.5
- Operating System and Version: Ubuntu 18.04
- Browser type and version: Chrome 74.0.3729.131

### Description:

Users are currently not able to execute actions that extend the `Laravel\Nova\Actions\DestructiveAction` class if they don't have the `delete` authorization.

This seems to be a bug as it is possible to run non-destructive actions while not having the `update` authorization.

### Steps To Reproduce:

1. Create an Action that extends the `Laravel\Nova\Actions\DestructiveAction` class
2. Create a Resource and attach the Action to it
3. Create a Policy for the Model of the Resource and return `false` from its `delete()` method.
4. Try to run the action

**Comment by jbrooksuk** [comment]
I see this more as protection against blindly creating destructive actions and I'd personally be against changing that.

This does need documenting in https://nova.laravel.com/docs/2.0/actions/defining-actions.html#destructive-actions though. I'll add this now.

**Comment by jbrooksuk** [comment]
The documentation sort of alludes to this fact at https://nova.laravel.com/docs/2.0/resources/authorization.html#policies

> **Undefined Policy Methods**
> If a policy exists but is missing a method for a particular action, the user will not be allowed to perform that action. So, if you have defined a policy, don't forget to define all of its relevant authorization methods.

Still, I'll add an explicit note in the **Destruction Actions** section.

**Comment by jbrooksuk** [comment]
PR opened.

**Comment by chescos** [comment]
@jbrooksuk I feel like there should be some way to allow a user to run a Destructive Action but don't allow him to delete a Resource.

My reasoning is that you can have a Resource where rows can't or shouldn't ever be deleted. But at the same time, you can have a Destructive Action on the Resource which doesn't delete any data in our database but performs an irreversible task. Examples for this are:

- Sending a third party payout to a user (e.g PayPal, Bitcoin)
- Delete a user's data from an external service
- Start the shipment process for an order

**Comment by jbrooksuk** [comment]
@chescos I think that'd be a new (and decent) addition to Nova. Could you please open a new issue.

**Comment by christophrumpel** [comment]
Hey. Is there already a new issue for this? I would like to discuss this in more detail :-)

I just ran into this situation and I see no reason why an action should be connected to the resource's policy. Neither the default action nor the destructive one. The "destructive action" just changes the color of the button, by no means it tells something about what happens inside the action, besides that it is connected to the resource. It just tells the user to be careful when hitting the button. But that's it. I think it would be a good idea to decouple actions from the resource's policy. What do you think @jbrooksuk?

**Comment by jbrooksuk** [comment]
@christophrumpel I don't remember seeing an issue opened for this, so please go ahead :)

**Comment by medteck** [comment]
If you want to delete records only throught defined actions, you can just edit your authorization rule like this:

```
use Laravel\Nova\Http\Requests\ActionRequest;

class YourResource extends Resource
{
    public function authorizedToDelete(Request $request)
    {
        return $request instanceof ActionRequest;
    }

    public function authorizedToForceDelete(Request $request)
    {
        return $request instanceof ActionRequest;
    }
}
```

**Comment by krystianlaubach** [comment]
I have faced the same issue with DestructiveAction relying on delete action policy. In my case I do not delete records, first because they are used as a foreign key in other records / tables, second because we want to keep full historical data. So, we have a concept of "active" / "inactive" record. Basically, there is boolean column "active". Then I have an actions "Activate"  (active = true) and "Deactivate" (active = false). I want "Deactivate to be a Destructive Action, basically for the styling / visual purpose. I have policy for "activate" and "deactivate" methods. However, because Destructive Action relies on "delete" policy, my "deactivate" policy is being ignored and "delete" policy returns false.

Any idea how to achieve my requirement? Is custom style / blade template the only solution? That would be great to have destructive action that doesn't rely on delete policy.

**Comment by krystianlaubach** [comment]
I have just found the solution. My action class extends `Laravel\Nova\Actions\Action`, so I can use any policy I want. Then I can override this method:

```
    /**
     * Return the CSS classes for the Action.
     *
     * @return string
     */
    public function actionClass()
    {
        return $this instanceof DestructiveAction
            ? 'btn-danger'
            : 'btn-primary';
    }

```

**Comment by krystianlaubach** [comment]
```
<?php

namespace App\Nova\Actions;

use Laravel\Nova\Actions\Action;

class SoftDestructiveAction extends Action
{
    /**
     * Return the CSS classes for the Action.
     *
     * @return string
     */
    public function actionClass(): string
    {
        return 'btn-danger';
    }
}

```

Then my action:

```
<?php

namespace App\Nova\Actions;

use App\Models\Interfaces\ActiveRecordInterface;
use App\Models\Interfaces\EditableInterface;
use App\Models\User;
use Illuminate\Bus\Queueable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Auth;
use Laravel\Nova\Fields\ActionFields;

class DeactivateRecord extends SoftDestructiveAction
{
    use InteractsWithQueue, Queueable;

    /**
     * The displayable name of the action.
     *
     * @var string
     */
    public $name = 'Deactivate';

    /**
     * Perform the action on the given models.
     *
     * @param ActionFields $fields
     * @param Collection $models
     *
     * @return string[]
     */
    public function handle(ActionFields $fields, Collection $models): array
    {
        /** @var User $loggedInUser */
        $loggedInUser = Auth::user();

        /** @var ActiveRecordInterface|EditableInterface $model */
        foreach ($models as $model) {
            if ($model instanceof ActiveRecordInterface) {
                $model->deactivate();
            }

            if ($model instanceof EditableInterface) {
                $model->setUpdatedBy($loggedInUser);
            }

            $model->save();
        }

        return SoftDestructiveAction::danger('Selected records have been successfully deactivated!');
    }

    /**
     * Get the fields available on the action.
     *
     * @return array
     */
    public function fields(): array
    {
        return [];
    }
}
```
