### ISSUE TITLE
Queued actions throw exception: "Serialization of 'Closure' is not allowed"

### ISSUE THREAD

**Issue by chescos** [laravel/nova-issues#1612]
- Laravel Version: 5.7.28
- Nova Version: 2.0.9
- PHP Version: 7.2.5
- Operating System and Version: Ubuntu 18.04
- Browser type and version: Chrome 74.0.3729.131

### Description:

Queued actions throw this exception when using the `canSee` and `canRun` methods:

`Serialization of 'Closure' is not allowed at /home/vagrant/code/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:138`

### Steps To Reproduce:

1. Create a queued Action
2. Create a Resource and attach the Action to it with the `canSee` and `canRun` methods
3. Try to run the Action

**Comment by conormx** [comment]
Hi @chescos this is likely due to using the canRun closure on your Resource, if you remove the canRun closure on the instantiation of the Action and instead implement the answer [here](https://github.com/laravel/nova-issues/issues/558#issuecomment-466939080) you'll be able to get that running.

**Comment by chescos** [comment]
@conormx This doesn't work in my case because the user doesn't have the `update` permission for the Resource (specified in the Policy for the Model). That's not an issue with `canRun`. But if I use `authorizedToRun` instead of `canRun`, the user suddenly isn't authorized to run the action anymore.

**Comment by jbrooksuk** [comment]
@chescos can you provide a repository which replicates this, please.

**Comment by chescos** [comment]
@jbrooksuk I hope it's enough if I provide more detailed steps to reproduce the issue:

#### 1. Create a queued Action

Run `php artisan nova:action SomeAction` to create a new Nova Action. Then implement the `ShouldQueue` class on the Action like this:

```
class SomeAction extends Action implements ShouldQueue
```

#### 2. Attach the Action to the User resource with the canSee and canRun methods

Attach the Action to the `User` resource inside of the `actions()` method like this:

```
    /**
     * Get the actions available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function actions(Request $request)
    {
        return [
            (new Actions\SomeAction)->canSee(function ($request) {
                return true;
            })->canRun(function ($request, $user) {
                return true;
            }),
        ];
    }
```

#### 3. Run the Action

Go to your Nova dashboard and run the action on a `Use`r resource. An exception will be thrown:

```
Serialization of 'Closure' is not allowed
```

Please let me know if you're still having troubles to reproduce this issue.

**Comment by jbrooksuk** [comment]
@chescos thanks! I've replicated the issue and will look into it.

**Comment by dkulyk** [comment]
@jbrooksuk Callback no more need for execution and should be cleaned  in `__sleep()`.

**Comment by dkulyk** [comment]
```php
    public function __sleep()
    {
        $ignored = ['runCallback'];
        
        $properties = (new ReflectionClass($this))->getProperties();

        return array_values(array_filter(array_map(function ($p) use ($ignored) {
            return ($p->isStatic() || in_array($name = $p->getName(), $ignored)) ? null : $name;
        }, $properties)));
    }
```

**Comment by EpocSquadron** [comment]
@dkulyk Thank you for posting the pending code here. I was able to add it to my action and get past this issue. However, I needed to also add `'seeCallback'` to the list of ignored properties, as I am using `canSee` rather than `canRun`. Thought you ought to know when you go to implement the fix.

**Comment by dkulyk** [comment]
`seeCallback` already ignored in PR. Above is only example of implementation.
