### ISSUE TITLE
Trends by weeks issue across different database drivers

### ISSUE THREAD

**Issue by arcanedev-maroc** [laravel/nova-issues#1614]
- Laravel Version: 5.8
- Nova Version: 2.0.5
- PHP Version: 7.2

### Description:

This issue is related to the date format functions used by each database and the tests are failing because of the inconsistency of the results.

### SQLITE
`%W - week of year: 00-53`

> Source: https://www.sqlite.org/lang_datefunc.html

### MYSQL
`%v - Week (01..53), where Monday is the first day of the week; WEEK() mode 3; used with %x`

> Source: https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html

### POSTGRES

`IW - week number of ISO 8601 week-numbering year (01-53; the first Thursday of the year is in week 1)`

> Source: https://www.postgresql.org/docs/9.6/functions-formatting.html

### Steps To Reproduce:

Create records with dates like 2019-05-01 (beginning of a month) and compare the results between the databases (especially with sqlite)

**Comment by devfrey** [comment]
Could you create a repository with sample code?

**Comment by arcanedev-maroc** [comment]
Hi @devfrey, i think the easiest way to explain the issue is by using `sqlfiddle`

**MYSQL:** 
http://sqlfiddle.com/#!9/12701f/1

**POSTGRESQL:** 
http://sqlfiddle.com/#!17/53e7f/1

**SQLITE:** 
http://sqlfiddle.com/#!7/e09c9/1

**REASON N°1:** 
The results are the same for `mysql` and `postgres`, showing the same week number. But sqlite has an offset with the others.

I think the date format used in `Laravel\Nova\Metrics\SqliteTrendDateExpression` for `week` should be changed to the *ISO week date standard (ISO-8601)*.

**REASON N°2:** 
`(new DateTime)->setISODate($year, $week)->setTime(0, 0)` in `Laravel\Nova\Metrics\Trend::formatAggregateWeekDate()`

> DateTime::setISODate
> Set a date according to the ISO 8601 standard - using weeks and day offsets rather than specific dates.
> Source: https://www.php.net/manual/en/datetime.setisodate.php

**Comment by jbrooksuk** [comment]
I've made a PR which should fix this issue.
