### ISSUE TITLE
Namespace of api.php in package

### ISSUE THREAD

**Issue by nickkuijpers** [laravel/nova-issues#1616]
Hello,

Maybe it is nice to add the namespace to the registration of the api routes in a package in the ToolServiceProvider.php.

Can imagine that it might be a issue when changing the directory name when putting it in hardcoded but so is other stuff. 

Like this:

```
Route::middleware(['nova', Authorize::class])
                ->prefix('nova-vendor/cameras')
                ->namespace('Niku\Cameras\Controllers')
                ->group(__DIR__.'/../routes/api.php');
```

Instead of this:

```
Route::middleware(['nova', Authorize::class])
                ->prefix('nova-vendor/cameras')
                ->group(__DIR__.'/../routes/api.php');
```

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
