### ISSUE TITLE
Translatable Download in resources\js\components\Detail\FileField.vue

### ISSUE THREAD

**Issue by 4n70w4** [laravel/nova-issues#1617]
`vendor/laravel/nova/resources/js/components/Detail/FileField.vue:34`

Need to translatable:

![image](https://user-images.githubusercontent.com/38257723/58088008-6d5e0800-7bca-11e9-8112-855138cf8e8a.png)

**Comment by FaridAghili** [comment]
Duplicate of #1630, already fixed.

**Comment by dkulyk** [comment]
Duplicate of #1630
