### ISSUE TITLE
[Bug] Date field within action will randomly dismiss modal when focused

### ISSUE THREAD

**Issue by FrittenKeeZ** [laravel/nova-issues#1618]
- Laravel Version: 5.8.17
- Nova Version: 2.0.5
- PHP Version: 7.2
- Operating System and Version: Alpine Linux 3.8
- Browser type and version: Chrome 74.0.3729.131

### Description:
When focusing a date field with an action modal, it will sometimes dismiss the modal while leaving the date picker modal visible.

### Steps To Reproduce:
1. Create an action with a date field.
2. Prompt the action and focus the date field.
3. Re-focus the date field until the modal is dismissed.

### Screenshots:
![action-modal-date-default](https://user-images.githubusercontent.com/1186125/58092516-941d3e00-7bcc-11e9-98d4-e26ae5963bd3.png)
![action-modal-date-focused](https://user-images.githubusercontent.com/1186125/58092527-9c757900-7bcc-11e9-97dd-21619c2e9504.png)
![action-modal-date-dismissed](https://user-images.githubusercontent.com/1186125/58092532-a0090000-7bcc-11e9-80c8-f68b7716e60d.png)

**Comment by jbrooksuk** [comment]
Sorry, but we are unable to debug your issue without a reproducible code example. Once you provide that we can open this up again.

**Comment by czemu** [comment]
I had the same problem and I solved it by adding the main flatpickr container class name to the `classWhitelist` attribute of the modal component.

Full example:
`
<modal classWhitelist="flatpickr-calendar">
   // Your modal content here
</modal>
`
