### ISSUE TITLE
Date::make cannot show a date field in a hasOne relation

### ISSUE THREAD

**Issue by horaceho** [laravel/nova-issues#1619]
- Laravel Version: 5.7
- Nova Version: 1.3.2
- PHP Version: 7.3.5
- Operating System and Version: MacOS 10.14.5
- Browser type and version: Chrome 74.0.3729.157
- Reproduction Repository: https://github.com/###/###

### Description:

`Date::make` returns either `"Invalid Date"` or `"{ "date": "2019-05-18 00:00:00.000000", "timezone_type": 3, "timezone": "UTC" }"`

### Steps To Reproduce:
`casefile` model:
```
    public function billings()
    {
        return $this->hasMany('App\Billing');
    }

    public function lastBilling()
    {
        return $this->hasOne('App\Billing')->orderBy('billing_date','desc');
    }
```
```
php artisan tinker
$casefile = App\Casefile::find(154);
>>> $casefile->lastBilling->billing_date;
=> Illuminate\Support\Carbon @1558137600 {#3131
     date: 2019-05-18 00:00:00.0 UTC (+00:00),
   }
>>> $casefile->lastBilling->billing_date->format('Y-m-d')
=> "2019-05-18"
```
In Nova
```
            Date::make('Last Billing', function () {
                return optional($this->lastBilling)->billing_date;
            })->onlyOnIndex(),
```
gives `{ "date": "2019-05-18 00:00:00.000000", "timezone_type": 3, "timezone": "UTC" }`

![Screen Shot 2019-05-22 at 4 59 09 PM](https://user-images.githubusercontent.com/6657/58161698-50e9ca80-7cb3-11e9-85d9-6ac07b9e40e0.png)

add `->format('Y-m-d')` in Nova:
```
            Date::make('Last Billing', function () {
                return optional($this->lastBilling)->billing_date;
            })->format('Y-m-d')->onlyOnIndex(),

```
gives `Invalid date`

![Screen Shot 2019-05-22 at 5 01 09 PM](https://user-images.githubusercontent.com/6657/58161735-6232d700-7cb3-11e9-90ef-c0ec33803ed9.png)

How can I show a `hasOne` date field properly?

Update, here is temp solution:
```
            Text::make('Last Billing', function () {
                return optional(optional($this->lastBilling)->billing_date)->format('Y-m-d');
            })->onlyOnIndex(),
```
![Screen Shot 2019-05-22 at 5 16 29 PM](https://user-images.githubusercontent.com/6657/58162804-6cee6b80-7cb5-11e9-8ec3-a8943050f7d2.png)

**Comment by dkulyk** [comment]
Computed values passed as is.
You should to pass formatted value like in temporary solution.
