### ISSUE TITLE
Trends with Mariadb

### ISSUE THREAD

**Issue by jkudish** [laravel/nova-issues#162]
Hey 👋

I use https://github.com/ybr-nx/laravel-mariadb instead of the default mysql DB driver, with mariadb to get proper json support with mariadb.
In nova, I'm getting a "Trend metric helpers are not supported for this database." when attempting to use trends. 

This is easily fixed in `nova/src/Metrics/TrendDateExpressionFactory.php` by adding `case 'mariadb':` together with the mysql case.

```php
 switch ($query->getConnection()->getDriverName()) {
            case 'sqlite':
                return new SqliteTrendDateExpression($query, $column, $unit, $timezone);
            case 'mysql':
            case 'mariadb':
                return new MySqlTrendDateExpression($query, $column, $unit, $timezone);
            case 'pgsql':
                return new PostgresTrendDateExpression($query, $column, $unit, $timezone);
            default:
                throw new InvalidArgumentException('Trend metric helpers are not supported for this database.');
        }
```

**Comment by guoxiangke** [comment]
in config/databases.php
'mysql' => [
            'driver' => 'mariadb',
have a try.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍

**Comment by jkudish** [comment]
Thank you!

**Comment by davidgabbay** [comment]
so trends does not support sql server ?
it is not on the list of supported servers.
and i get same -  "Trend metric helpers are not supported for this database."

**Comment by swapnilmonad** [comment]
> so trends does not support sql server ?
> it is not on the list of supported servers.
> and i get same - "Trend metric helpers are not supported for this database."

Hello @davidgabbay This issue is related to MariaDB and closed so I have added new for MS-SQL
[Trends with MS-SQL](https://github.com/laravel/nova-issues/issues/1577)
