### ISSUE TITLE
Ability to hide “Create & Add Another” button by condition

### ISSUE THREAD

**Issue by 4n70w4** [laravel/nova-issues#1620]
![image](https://user-images.githubusercontent.com/38257723/58245100-bba31080-7d5c-11e9-8f76-b183f74bd0b3.png)

**Comment by jangidgirish** [comment]
I also see, can it be deleted?

**Comment by Lotfull** [comment]
@4n70w4 @jangidgirish, this can be easily done using custom CSS:

1.  Create `public/css/custom.css` with next lines: 
```
button[dusk='update-and-continue-editing-button'], button[dusk='create-and-add-another-button'] {
    display: none;
}
```

2.  Install `custom.css` in `NovaServiceProvider.php`:
```
public function boot()
    {
        parent::boot();
        Nova::style('custom-fields-css', public_path('css/custom.css'));
    }
```

3. ENJOY!

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by bcoelhodev** [comment]
How can I hide "Create & Add Another" only a specific resource?
