### ISSUE TITLE
Select All Matching causes sql error for SQL Server with actions

### ISSUE THREAD

**Issue by FrittenKeeZ** [laravel/nova-issues#1621]
- Laravel Version: 5.8.17
- Nova Version: 2.0.5
- PHP Version: 7.2
- Operating System and Version: Ubuntu 16.04.5 LTS
- Browser type and version: Chrome 74

### Description:
Using "Select All Matching" and running an action, will result in a query where `id` is sorted twice. Looking at the queries from Telescope I see the following:

SQL Server
```sql
select top 200 * from [jobs] where [jobs].[deleted_at] is null order by [id] desc, [id] desc
```
MySQL
```sql
select * from `jobs` where `jobs`.`deleted_at` is null order by `jobs`.`id` desc, `id` desc limit 200 offset 0
```

This works fine on MySQL but throws an exception for SQL Server:
```
SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]A column has been specified more than once in the order by list. Columns in the order by list must be unique. (SQL: select top 200 * from [jobs] where [jobs].[deleted_at] is null order by [id] desc, [id] desc)
```

Backtracing reveal that it's caused by using `latest()` in `Laravel\Nova\Http\Requests\ActionRequest::chunks()`.

There's also an error in `Laravel\Nova\PerformsQueries::applyOrderings()` on line 143, where `empty($query->orders)` should be `empty($query->getQuery()->orders)`.

### Steps To Reproduce:
1. Create any action and apply it to a resource.
2. Use "Select All Matching" and run the action.
3. See that the sql query is generated with the same ordering twice.

**Comment by klepak** [comment]
I am also having this issue
