### ISSUE TITLE
Required field's name are not marked

### ISSUE THREAD

**Issue by SmbatPoghosyan** [laravel/nova-issues#1623]
When I mark the name of field with an asterisk, it is shown both in the table and in the placeholder.
How can I do it only for field name?

**Comment by davidhemphill** [comment]
Nova currently doesn't have a way to indicate that a field is required.

**Comment by maarten00** [comment]
Are there any plans to implement this?

**Comment by davidhemphill** [comment]
Well, Nova is not a CMS. In addition, since Laravel supports several ways of dynamically determining a field's "requiredness", it's nearly impossible for us to know that ahead of time to display a required indicator.

Example: https://laravel.com/docs/5.8/validation#rule-required-if

**Comment by timcv** [comment]
@davidhemphill Would it be possible for you to add an asterisk if the default "required" rule is used?

I think that would solve a lot of use cases.

//Tim
