### ISSUE TITLE
Bug [Authorization] Value & Trend have trait AuthorizedToSee but not called canSee()

### ISSUE THREAD

**Issue by 4n70w4** [laravel/nova-issues#1625]
- Nova Version: 2.0.3 (looking code and in 2.0.5)

### Description:

`Liskov Substitution Principle` violation: `Laravel\Nova\Metrics\Value` is child of `\Laravel\Nova\Element` which `use AuthorizedToSee` containing `canSee()` method. But this method is not called.

### Steps To Reproduce:

```
use Laravel\Nova\Metrics\Value;

class NewUsers extends Value {

    public function canSee(Closure $callback) {
        return false;
    }
```

**Comment by dkulyk** [comment]
Use `public function authorize(Request $request)` instead. CanSee only set a callback for authorization.

**Comment by 4n70w4** [comment]
@dkulyk thanks, it's works. But it's not documented and not userfriendly.

**Comment by eugenevdm** [comment]
@4n70w4 The Laravel Nova documentation is open source. I've found a few missing items, created some pull requests, and updated the docs. Perhaps if you feel it should be documented give it a try! :-)
