### ISSUE TITLE
Can't update model with encrypted attribute

### ISSUE THREAD

**Issue by regiszanandrea** [laravel/nova-issues#1626]
- Laravel Version: 5.8
- Nova Version: 2.0.4
- PHP Version: 7.2
- Operating System and Version: Mac OS High Sierra V.10.13.5
- Browser type and version: Google Chrome 74

### Description:
When you have encrypted attribute in your model, laravel nova not let you update the model even with `onlyOnDetail()`,`hideWhenUpdating()` and `hideWhenCreating()` in your Resource.

### Steps To Reproduce:
1. Have an attribute that is encrypted.
2. Put it in your Resource:
```
Currency::make('Money')->onlyOnDetail()->hideWhenUpdating()->hideWhenCreating()
```
3. Try to update a field from model
4. Message returned: 'The payload is invalid'

**Comment by davidhemphill** [comment]
Sorry, but we are unable to debug your issue without a reproducible code example. You have not provided sample code to show how you are "encrypting" this data or any other details that would allow us to reproduce this in our local environments.

**Comment by regiszanandrea** [comment]
Ok:

Model:
```
class Wallet extends Model
{
    use Encryptable;

    /**
     * Fields encryptable
     * @var array
     */
    protected $encryptable = [
        'money',
    ];
}
````
#Trait:
````
trait Encryptable
{
    public function getAttribute($key)
    {
        $value = parent::getAttribute($key);

        if (in_array($key, $this->encryptable)) {
            $value = decrypt($value);
        }

        return $value;
    }

    public function setAttribute($key, $value)
    {
        if (in_array($key, $this->encryptable)) {
            $value = encrypt($value);
        }

        return parent::setAttribute($key, $value);
    }
}
````
