### ISSUE TITLE
Improve Action::danger and Action::message

### ISSUE THREAD

**Issue by LaurensDorival** [laravel/nova-issues#1627]
I have a situation where I have quite long Action::danger messages.

At this moment these danger messages disappear after six seconds. This is not enough time for the users to read them.

Therefor I suggest the following, either:

1. Action::danger messages never disappear: the user must click a cross to close it.
Action::message keeps its current behavior.
2.	Add an extra default parameter $duration = null to both Action::danger and Action::message.
When the $duration is set to:
•	null then the current behavior is used
•	0 then the message will never disappear
•	> 0 then the message will disappear after $duration seconds 

It’s also possible to implement both features.

**Comment by devfrey** [comment]
Great idea! I have one tiny suggestion, and that is to use seconds instead of milliseconds for the duration.

**Comment by LaurensDorival** [comment]
Yeah, that makes more sense! I'll change it in the original post.

**Comment by PatricNox** [comment]
As additional I suppose an included check could be added. 
A check that looks if the duration variable is set (not null) then a "X" (close) button should appear upon the message box.

Should be logical enough to have included, no?

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
