### ISSUE TITLE
HasOne field only using Name to look for model

### ISSUE THREAD

**Issue by njsoria** [laravel/nova-issues#1628]
- Laravel Version: 5.8.17
- Nova Version: 2.0.5
- PHP Version: 7.3.4-1
- Operating System and Version: Ubuntu 18.04
- Browser type and version: Chrome 74.0
- Reproduction Repository: none..

### Steps To Reproduce:
public function fields(Request $request)
{
    HasOne::make('Project Assignment','project_task_assignment'),
}

this looks for the snake case version of the first argument in the Task model rather than the override value provided in the second argument.

See video link: https://youtu.be/fJMDl3uP_4c

**Comment by dkulyk** [comment]
You should pass third argument with resource's class name.

**Comment by njsoria** [comment]
I still can't figure out how to amend the above to work correctly..

HasMany::make ('Project-Task-User Mappings','project_task_user_mappings','project_task_user_mappings')

This doesn't work.

Or modifying the above similarly didn't work. I get an error saying the class in the third argument doesn't exist regardless of what I change it to. I've tried ProjectTaskUserMapping, project_task_user_mapping and project_task_user_mappings. Only having the first argument correct works.

I appreciate your help @dkulyk

**Comment by fobin** [comment]
`HasOne::make('Project Assignment','project_task_assignment',ProjectTaskAssignmentResource::class)`
