### ISSUE TITLE
Search for string field that contains only numbers doesn't work

### ISSUE THREAD

**Issue by lucasromanojf** [laravel/nova-issues#163]
I have a model that has a string column. This column will mostly contain only numbers.

When I try to search in the search field (either global search or index search) by numbers contained in that field for some record, nothing is found. But if I search by text, the records that contain that text appear as expected.

Examples:

Record 1:
Field value: "43232424"
Searching: "4323" or "43232" or "43232424" -> nothing is found

Record 2:
Field value: "mock_terminal"
Search: "mock" or "mock_" or "mock_terminal" -> found as expected

**Comment by michaelchunn** [comment]
The resource 'users' has 'name' and 'email' searchable
`
    public static $search = [
        'name', 'email',
    ];

`

If you search for '1' it generates this query.

select count(*) as aggregate from `users` where `users`.`id` = ? and (`users`.`name` like ? or `users`.`email` like ?) ["1","%1%","%1%"]

**Comment by lucasromanojf** [comment]
@michaelchunn try to add only numbers to the user's name for example (ex.: "252525") and then try to search "252525". Nothing will be found.

**Comment by Jam0r85** [comment]
Another example of this is an address.

Storing the first line of an address eg. '123 Smith Street' and searching for '123' returns no results. However typing 'smi' gets the value no problem.

**Comment by mrmonat** [comment]
Already mentioned in #23

**Comment by davidhemphill** [comment]
This has been fixed in 1.0.15.
