### ISSUE TITLE
Readonly fields aren't removed from request readers when update a resource.

### ISSUE THREAD

**Issue by wemersonrv** [laravel/nova-issues#1631]
- Laravel Version: 5.8.17
- Nova Version: 2.0.5
- PHP Version: 7.2.11
- Operating System and Version: Windows 10 64 bits
- Browser type and version: Google Chrome 74.0.3729.157

### Description:
Readonly fields aren't removed from request headers when update a resource. I think this is wrong because if i'm making it readonly is because don't want changes on them. But users can inspect page and remove readonly/disable directives and change values... and the changed value are sent.

### Steps To Reproduce:
1. Add `readOnly()` to a Field
2. In browser, inspect html and remove readonly/disable directives
3. Change field value
4. Send update.
5. Inspect the request headers and check the changes in readonly fields.

**Comment by davidhemphill** [comment]
https://github.com/laravel/nova/pull/387

**Comment by wemersonrv** [comment]
> [laravel/nova#387](https://github.com/laravel/nova/pull/387)

This link is broken.

**Comment by davidhemphill** [comment]
It's not broken. It's available if you've connected your Nova to the private GitHub repository via the Nova website.

**Comment by SebastianMueller87** [comment]
I also noticed that unacceptable behaviour. :/

**Comment by davidhemphill** [comment]
There's an open PR to remove it from validation.

**Comment by davidhemphill** [comment]
This has been fixed. 👍
