### ISSUE TITLE
Customize default per page value for specific resource

### ISSUE THREAD

**Issue by 4n70w4** [laravel/nova-issues#1632]
![image](https://user-images.githubusercontent.com/38257723/58407653-f8c91480-8074-11e9-91d8-0a7910e2e705.png)

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
