### ISSUE TITLE
Cannot return to login screen after hitting 403 Forbidden page

### ISSUE THREAD

**Issue by unlikenesses** [laravel/nova-issues#1633]
- Laravel Version: 5.8.17
- Nova Version: 2.0.3
- PHP Version: 7.1
- Operating System and Version: MacOS High Sierra
- Browser type and version: Chrome

### Description:

After hitting a 403 Forbidden page, it is not possible to return to the login screen. The only way to return to the login screen is to clear the app cache in Chrome devtools.

### Steps To Reproduce:

1. Visit the Nova login page.
2. Login as a user who does not have permission to login to Nova.
3. Nova correctly displays the 403 Forbidden page.
4. Return to the Nova login page.
5. Nova incorrectly displays the 403 Forbidden page.

**Comment by PatricNox** [comment]
This seems to be default behavior as Nova is a package and not core, like Laravel.
The session as an authenticated user is started and therefore you'd remain "logged in".

I believe this is logical and should remain, since what if you use Laravel Nova as addition to your website? (which its intention is)

Else this bug would appear:

* Login to http://myLaravelwebsite.com
* Attempt to go to Admin panel (this is Nova) http://myLaravelwebsite.com/nova 
* Get 403 redirected
* Got logged out from website (<- oops!)

**Comment by unlikenesses** [comment]
I see what you're saying, but it just seems a tad strange to me (and to any potential clients) that if you attempt to log in with the wrong user you can effectively *never* log in again!

**Comment by PatricNox** [comment]
@unlikenesses Indeed, however you can change this behaviour through the Authorize middleware.



```
<?php

namespace Laravel\Nova\Http\Middleware;

use Illuminate\Support\Facades\Auth;
use Laravel\Nova\Nova;

class Authorize
{
    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return \Illuminate\Http\Response
     */
    public function handle($request, $next)
    {
        if (Nova::check($request)) {
            return next($request);
        }

        Auth::logout();
        return abort(403);
    }
}
```

**Comment by PatricNox** [comment]
Actually, I realized, don't use the above code, that causes a bug for logged in people with no access to specific sites. What you want is to logout on failed gate, which is achieved like so:

```
    /**
     * Register the Nova gate.
     *
     * This gate determines who can access Nova in non-local environments.
     *
     * @return void
     */
    protected function gate()
    {
        Gate::define('viewNova', function ($user) {
            if ($user->hasAnyRole(['supersadmin', 'course_manager'])) {
                return true;
            }

            // If user doesn't have access to nova, log them out.
            // This prevents them for being stuck in 403 page.
            Auth::logout();
        });
    }
```

**Comment by unlikenesses** [comment]
Works perfectly, thanks!

**Comment by Archvist** [comment]
I had the exact same issue, but I found that changing the `Authorize` middleware produced a further cookies error. 

`ErrorException
Trying to get property of non-object
http://nova.test/nova`

'Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
:185
vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:185'

'$response->headers->setCookie('

Could someone please advise why this fix isn't now working? @PatricNox

**Comment by PatricNox** [comment]
@Archvist seems like something else is failing gate-wise.
