### ISSUE TITLE
[Solution] to switch locale in Nova.

### ISSUE THREAD

**Issue by h-zone** [laravel/nova-issues#1635]
GIST https://gist.github.com/h-zone/052724a1d2c030cb2207133c289150e4
Dear devs!
Do you update Nova with this solution?

**Comment by h-zone** [comment]
So, **next** closure :) is content from selected locale. I mean app/Nova/{LOCALE} directory for separate resource sets

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).

**Comment by h-zone** [comment]
@davidhemphill 

Sometimes it seems to me that I communicate with the bot. Sorry, but it is. I do not understand your replicas for many issues, here, on the tracker, for suggestions or improvements.
Where are you saw the general discussion, - I'm suggest you implementation. The solution is almost ready, and many people will be glad to use it.
If you have a high employment, then find people who are ready to help you.
Nova's functional suffers from insufficiency, and you turn away.
