### ISSUE TITLE
Resource view table names is disappeared

### ISSUE THREAD

**Issue by yiitinki** [laravel/nova-issues#1636]
Laravel Version: 5.7
Nova Version:  v1.3.2

Hi,

As you can see on below table names on resource view has disappeared. Could you suggest me possible solutions?

![Image of screen](https://i.ibb.co/jb25QCZ/Screen-Shot-2019-05-28-at-12-31-22.png)

Thank you

**Comment by davidhemphill** [comment]
Update your Nova version to the latest assets.

**Comment by thistehneisen** [comment]
@davidhemphill having the same issue with Nova 2.0.6 and L 5.8, should we run any command for this, maybe?
