### ISSUE TITLE
Operations quota exceeded, change plan to get more Operations

### ISSUE THREAD

**Issue by nezaboravi** [laravel/nova-issues#1639]
- Laravel Version: Laravel Framework 5.8.19
- Nova Version: i am not sure how to get the version.  Suppose its latest, i have iot for baout 2 months
- PHP Version: PHP 7.3.1 (cli) (built: Jan 10 2019 13:15:37) ( NTS )
- Operating System and Version: MAcOs Mojave Version 10.14.5
- Browser type and version: Google Chrome is up to date
Version 74.0.3729.169 (Official Build) (64-bit)
- Reproduction Repository: https://bitbucket.org/vladimir_nikolic/cmp/src/develop/

### Description:
I am getting a message that Operations quota exceeded, change plan to get more Operations.
So, when i try to add a Post in nova, after clicking on Update post, i get that error message and post is not updated. 
Here is a photo:
https://www.dropbox.com/s/91zlxec2abj7w9q/Screenshot%202019-05-29%2016.19.55.png?dl=0

### Steps To Reproduce:
Create post and update a photo

**Comment by davidhemphill** [comment]
You've run out of Operations on Algolia.
