### ISSUE TITLE
Translation "Create", "New", "Edit"

### ISSUE THREAD

**Issue by demency** [laravel/nova-issues#1640]
- Laravel Version: 5.8
- Nova Version: 2.0
- PHP Version: 7.3
- Operating System and Version: Ubuntu 16.04
- Browser type and version: Chrome

### Description:

Translations doesn't work properly. So, if you change

/nova/resources/js/views/Detail.vue line 411
`__('The :resource was deleted!'`

To
`__('The')+' '+__(':resource')+' '+__('was deleted!'`

You should translate only "The" and "was deleted!".

I use this solution to translate others things like "Create", "New" and "Edit"

Thanks,

**Comment by davidhemphill** [comment]
Sorry, but we are unable to debug your issue without a reproducible code example. Once you provide that we can open this up again.
