### ISSUE TITLE
Field hideWhenUpdating doesn't hide in creation form

### ISSUE THREAD

**Issue by wemersonrv** [laravel/nova-issues#1643]
- Laravel Version: 5.8.17
- Nova Version: 2.0.5
- PHP Version: 7.2.11
- Operating System and Version: Windows 10 64 bits e Ubuntu Server 18.04 64 bits
- Browser type and version: Google Crome 74.0.3729.169

### Description:
`hideWhenCreating` is not hiding the field when creating resource. `hideWhenUpdate` works fine.

![image](https://user-images.githubusercontent.com/2028673/58628570-69a84080-82b0-11e9-9e0f-da49d217ce5e.png)

### Steps To Reproduce:
1. Add two Texts fields for same column. In one add `hideWhenCreating()`, and other `hideWhenUpdating()`
2. Try to ADD new resource

**Comment by dkulyk** [comment]
[`onlyOnForms`](https://github.com/laravel/nova/blob/2.0/src/Fields/FieldElement.php#L133) overwrite `hideWhenCreating`
