### ISSUE TITLE
Translation issue to display default parameter value if in language file has  not found this parameter

### ISSUE THREAD

**Issue by Jignasa10** [laravel/nova-issues#1644]
Laravel v 5.7
Nova v 1.0

I have two language file en.json and de.json

In en.json file has below parameter.
{
"name":"My name",
"Address":"Address line",
"Country":"US"
}

In de.json file has below parameter.
{
"name":"My name",
"Country":"US"
}

When i set language as de , Address will display from en.json file because en is my default language and this parameter not found in de.json

But in my project it is nor working, If you have any solution please let me know

Thank you!

**Comment by davidhemphill** [comment]
Closing as this doesn't have anything to do with Nova.
