### ISSUE TITLE
Uncaught Error: A DOM element reference is required

### ISSUE THREAD

**Issue by horaceho** [laravel/nova-issues#1647]
- Laravel Version: 5.7
- Nova Version: 1.3.2
- PHP Version: 7.3.5
- Operating System and Version: Mac 10.14.5
- Browser type and version: Chrome 74.0.3729.169 
- Reproduction Repository: https://github.com/horaceho/laravel-nova-agenda-demo

### Description:

[ant-design-vue calendar](https://vue.ant.design/components/calendar/) runs well as a standalone component:

[![Edit Vue Antd Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-vvise?fontsize=14)

but got an "Uncaught Error: A DOM element reference is required" in my Nova tool:

- [laravel-nova-agenda](https://github.com/horaceho/laravel-nova-agenda)

![agenda-nova](https://user-images.githubusercontent.com/6657/58789679-4ddeca80-8621-11e9-810d-d0602fe88247.png)

Any help is appreciated.

### Steps To Reproduce:

- install the demo project
- install nova
- install laravel-nova-agenda tool
- click "Agenda" on Nova sidebar
- click  "year" dropdown (2019) on calendar header
- got error as shown in above scree shot

**Comment by davidhemphill** [comment]
This is not the place to get community help on your own custom tools.

This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).

**Comment by Sohail-purelogics** [comment]
@horaceho Have you find a solution for this?
