### ISSUE TITLE
Image Orientation Meta Ignored

### ISSUE THREAD

**Issue by ievgenklymenko** [laravel/nova-issues#1648]
- Laravel Version: 5.7.28
- Nova Version: 1.3.2
- PHP Version: 7.2.2
- Operating System and Version: macOS Mojave 10.14.5
- Browser type and version: Google Chrome 74.0.3729.157 (Official Build) (64-bit)

### Description:

Some image fields are displaying thumbnails and previews in incorrect orientation. It looks like metadata tags (like `exif` from digital cameras, which usually includes orientation) are being ignored

### Steps To Reproduce:

If you try to use a file with vertical orientation taken by mobile camera as an Image nova field value, you can see Nova will display it horizontally, while browser and all other devices will display it with correct orientation

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!

**Comment by intositeme** [comment]
I'm having this issue as well.
Nova v3.1.0
