### ISSUE TITLE
Remove update icon on related resource

### ISSUE THREAD

**Issue by JordanDinsdale** [laravel/nova-issues#1649]
- Laravel Version: 5.8
- Nova Version: 2.0.0
- PHP Version: 7.2.1
- Operating System and Version: Mac OS High Sierra 10.13.6
- Browser type and version: Firefox 67

Does anyone know how I get rid of the update icon on a related resource's details page?

I'm talking about the icons on the right here;

[![Nova Backend][1]][1]

Events and  Time Slots have a many to many relationship.

They are related like so;

App/TimeSlot.php
```
public function events()
{
    return $this->belongsToMany('App\Event');
}
```
  
App/Event.php
```
public function timeSlots()
{
    return $this->belongsToMany('App\TimeSlot');
}
```

I have Nova resources and policies for each of those models too. 

In my Time Slot policy, update is set to return false.

App/Nova/Policies/TimeSlotPolicy.php
```
/**
 * Determine whether the user can update the time slot.
 *
 * @param  \App\User  $user
 * @param  \App\TimeSlot  $timeSlot
 * @return mixed
 */
public function update(User $user, TimeSlot $timeSlot)
{
    return false;
}
```
and in my Event policy attachAnyTimeSlot and detachTimeSlot are both set to return false;

App/Nova/Policies/EventPolicy.php
```
/**
 * Determine whether the user can attach a time slot to an event.
 *
 * @param  \App\User  $user
 * @param  \App\Event $event
 * @return mixed
 */
public function attachAnyTimeSlot(User $user, Event $event)
{
   return false;
}

/**
 * Determine whether the user can detach a time slot from an event.
 *
 * @param  \App\User  $user
 * @param  \App\Event $event
 * @param  \App\TimeSlot $timeSlot
 * @return mixed
*/
public function detachTimeSlot(User $user, Event $event, TimeSlot $timeSlot)
{
    return false;
}
```
The latter gets rid of the trash can icon that detaches the associated resource. 

Nothing seems to get rid of the edit icon. 

When I click it I can't do anything. 

[![Nova Backend 2][2]][2]

For obvious reasons, I don't want it to appear at all.

Does anyone know how to remove it?

I've consulted various people and the consensus seems to be that it cannot be done using any of the methods currently supplied.

Do I have to resort to CSS and simply hide the icon?

Was it the intention of the creators of Nova that this be done like so? Or is it the case that the absence of a method that can deal with this is an oversight that will be remedied in future versions?

  [1]: https://i.stack.imgur.com/y0kE5.png
  [2]: https://i.stack.imgur.com/uSwJH.png

**Comment by ElectroBuddha** [comment]
Explained here: #1003
