### ISSUE TITLE
Database (Postgres) strict types fields search

### ISSUE THREAD

**Issue by malyusha** [laravel/nova-issues#165]
I have a model (currently any of them), that have the `id` field. Mostly, this `id` field is integer. When I run search on model, Nova starts search using `like` constraint. But if you run search query against Postgres query it will throw the exception, because you trying to search integer field as string... how can this be fixed?

**Comment by bonzai** [comment]
#46

**Comment by Gnative** [comment]
A temporary solution is to remove 'id' from the resources $search array, until a fix is supplied..

**Comment by malyusha** [comment]
@bonzai thank you, missed it..
Closing due to duplicate
