### ISSUE TITLE
Pass get variables to a filter

### ISSUE THREAD

**Issue by skalero01** [laravel/nova-issues#1650]
I am trying to be able to use a filter based on the get parameters on the url, for example i have the next url: `/admin/resources/reservations?tour_id=2`, on the filter i want to be able to use the `tour_id` variable, right now this is not possible (suppose that is because its done on Vue)

The idea is to be able to use it on the filter the next way or something similar

```
<?php 

namespace App\Nova\Filters;

use Illuminate\Http\Request;
use Laravel\Nova\Filters\Filter;
use App\Tour as Model;

class Tour extends Filter
{
/**
* The filter's component.
*
* @var string
*/
public $component = 'select-filter';

/**
* Apply the filter to the given query.
*
* @param \Illuminate\Http\Request $request
* @param \Illuminate\Database\Eloquent\Builder $query
* @param mixed $value
* @return \Illuminate\Database\Eloquent\Builder
*/
public function apply(Request $request, $query, $value)
{
return $query->where('tour_id', $request->tour_id);
}

/**
* Get the filter's available options.
*
* @param \Illuminate\Http\Request $request
* @return array
*/
public function options(Request $request)
{
return Model::pluck('id', 'name');
}
}
```

I am sure you can pass the request to be gotten on the filter, can you make it happen?

In other way i dont get why there is the request object if cannot be used :/

PD: The idea of this is to use it on my tour detail page and add a button to see all the reservations for this tour, i looked for any other way to make this happen but on the support email didnt help me any little

**Comment by davidhemphill** [comment]
The request object is the one from when the filter is _applied_, not the initial page load's. 

If you absolutely need this, consider modifying your `indexQuery` to use the request parameter. I don't think we want to change how filters work at this time as filters are already encoded in the URL in a separate process.

**Comment by skalero01** [comment]
> The request object is the one from when the filter is _applied_, not the initial page load's.
> 
> If you absolutely need this, consider modifying your `indexQuery` to use the request parameter. I don't think we want to change how filters work at this time as filters are already encoded in the URL in a separate process.

That don't even work...

I am calling the website something like this: `/nova/resources/email-sents?tour_id=2`, and added the next code on the nova model

```
public static function indexQuery(NovaRequest $request, $query)
    {
        \Log::info(request()->all());
        if($request->filled('tour_id')) {
            return $query->where('emailable_type', 'App\Tour')->where('emailable_id', $request->tour_id);
        }
        return $query;
    }
```

And i am receiving on the log the next information

```
array (
  'search' => NULL,
  'filters' => 'W10=',
  'orderBy' => NULL,
  'orderByDirection' => 'desc',
  'perPage' => '25',
  'trashed' => NULL,
  'page' => '1',
  'viaResource' => NULL,
  'viaResourceId' => NULL,
  'viaRelationship' => NULL,
  'relationshipType' => NULL,
)  
```

This mean that the $_GET variables i am sending to the website are not sent to the Nova model.. So, what should i do?

**Comment by alex38** [comment]
Is there no way to create a url that loads a list page with a filter applied?  Seems like this must be possible (e.g. for a "show all unapproved content" link on a dashboard card).  I can't find any references in the documentation on how the base64 encoding is supposed to be done.

**Comment by yurii-github** [comment]
> Is there no way to create a url that loads a list page with a filter applied? Seems like this must be possible (e.g. for a "show all unapproved content" link on a dashboard card). I can't find any references in the documentation on how the base64 encoding is supposed to be done.

I did something like below
```
            Number::make(__('Users'), function () {
                $filter = base64_encode(json_encode([['class' => UserCompanyFilter::class, 'value' => $this->id]]));
                $companyLinkWithFilter = Nova::path() . '/resources/users?users_filter='.urlencode($filter);

                return "<a href=\"{$companyLinkWithFilter}\">{$this->users_count}</a>";
            })
                ->asHtml()
                ->onlyOnIndex(),
```
but i guess Nova expects you to build urls on frontend via js components

my current problem now is that i want to send extra GET param to resource creation form but it doesn't work as I want 

`new?viaResource=&viaResourceId=&viaRelationship=&aaaaaaa=123`

i cannot get my '123' value in `public function fields(Request $request)`

regards

**Comment by mcsystemen** [comment]
Is there a way to work around the nova-api calls to get the values of given parameters like so: 

?param=123

**Comment by kidereo** [comment]
An old thread but if someone comes across this as I did the following might help. I had a challenge of passing a bunch of parameters from an action to a lens. In Nova action, you can push parameters to a url but they do not form part of the `$request` so you cannot retrieve them in the usual way. 
Luckily, they are still sent in the url i.e. `?category=1&item=2`. 
What I did on the receiving end was to get url from the referer (`$url = $request->headers->get('referer');`) , parse the url to get its query string (`$str = parse_url($url, PHP_URL_QUERY);`), and then parse that string to get output (`parse_str($str, $output);`). Finally, I was able to get my `$categoryId = $output['category']; //1 `and `$itemId = $output['item'];//2` to plug into the lens query.
Lots of parsing but it worked for me. Relevant php manuals here: [parse_url ](https://www.php.net/manual/en/function.parse-url.php) and [parse_str](https://www.php.net/manual/en/function.parse-str.php).

**Comment by MaciejLoj** [comment]
@kidereo 
Works great, thx !!

**Comment by simpsons310** [comment]
@kidereo Brilliant! You've saved my life. Thanks

**Comment by arishvns** [comment]
@kidereo Brilliant! You've saved my life. Thanks
