### ISSUE TITLE
Internationalization of Name in ActionEvent Model

### ISSUE THREAD

**Issue by gustavowiller** [laravel/nova-issues#1653]
**Nova Version:** 2.0

**Problem:** The ActionEvent Model save the name of actions only in English, and dont provide the internationalization of the names.
`'name' => 'Update'`

**Proposed Solution:** Add the internationalization `__()` for default actions name in ActionEvent Model. 
`'name' => __('Update')`

**Comment by jbrooksuk** [comment]
Closing. See https://github.com/laravel/nova/pull/473#issuecomment-517942190

**Comment by huoding** [comment]
I have the same question.
