### ISSUE TITLE
Global Search Results Overlap Chart

### ISSUE THREAD

**Issue by mikebronner** [laravel/nova-issues#1656]
- Laravel Version: 5.8.21
- Nova Version: 2.0.5
- PHP Version: 7.2
- Operating System and Version: macOS 10.14.5
- Browser type and version: Safari 12.1.1
- Reproduction Repository: n/a

### Description:
Line chart overlaps global search results, as demonstrated in the screenshot:

<img width="867" alt="Screen Shot 2019-06-06 at 10 47 04 AM" src="https://user-images.githubusercontent.com/1791050/59054529-be1b6500-8848-11e9-9790-4f2ce1a30821.png">

**Comment by mvdnbrk** [comment]
macOS: 10.14.5
Safari: 12.1.1

Can't reproduce this. See my screenshot.

<img width="566" alt="screenshot-nova" src="https://user-images.githubusercontent.com/802681/60455523-dc516680-9c36-11e9-89bc-0791cc196a97.png">

**Comment by mikebronner** [comment]
@mvdnbrk Try it on a full-width graph, maybe there's a difference in CSS there? I've worked around it for now by adding the following CSS:

```css
.ct-chart {
    z-index: 1 !important;
}
```

**Comment by mvdnbrk** [comment]
@mikebronner see screenshot.

<img width="571" alt="screenshot-nova-2" src="https://user-images.githubusercontent.com/802681/60456259-13287c00-9c39-11e9-89e0-b50f05d8c947.png">

**Comment by jbrooksuk** [comment]
I'm unable to replicate this in Chrome, Safari or Firefox on MacOS and using Nova v2.0.9
