### ISSUE TITLE
Custom accessor cause Sql error in search

### ISSUE THREAD

**Issue by cord** [laravel/nova-issues#1658]
- Laravel Version: 5.8
- Nova Version: 2.0.5
- PHP Version: 7.3

### Description:

Model with custom accessor as search field causes SQL error as the database does not have a corresponding column.

SQLSTATE[42S22]: Column not found: 1054 Unknown column '<model>.<custom-fields>' in 'where clause' (SQL: select * from `<model>` where (`<model>`.`<custom-fields>` like %<search-string>%) order by `<model>`.`id` desc limit 5)

### Steps To Reproduce:

- setup an a model with custom accessor (add to protected $appends to use in Nova)
- define a Nova resource using this model with $search pointing to the custom field
- perform a search

**Comment by davidhemphill** [comment]
Search is only designed to work on real columns in the database.
