### ISSUE TITLE
File not getting updated when storeAs generates same file name

### ISSUE THREAD

**Issue by drsdre** [laravel/nova-issues#1659]
- Laravel Version: 5.8.19
- Nova Version: 2.0.5
- PHP Version: 7.2.13
- Operating System and Version: OSX 10.14.5
- Browser type and version: Chrome 74.0.3729.169

### Description:
When setting up a Nova File/Image field and using the storeAs, it ignores the upload and does not store the changed content when the generated file name is equal to what was set previously (in the database). When not using storeAs and uploading a file with changed content using the same file name, the new content is getting stored. 

### Steps To Reproduce:
1. Create the following field in a resource which contains a selection_image field (text) and id:
```
Image::make( 'Selection Image', 'selection_image' )
			     ->prunable()
			     ->disk( 'public' )
			     ->storeAs( function ( Request $request ) {
				     return $request->id . '_selection.' . $request->file( 'selection_image' )->getClientOriginalExtension();
			     } ),
```

2. Using the Nova form upload an image and save the form. The image is saved as <id>_selection.<extension>

3. Open the form again and upload a different image and save the form. 

4. The image saved in step 2 is still being show. When tracking the queries in Telescope, no update has taken place.

My assumption is that because the generated image name from storeAs in step 2 and 3 is the same, Nova assumes that the image did not change and skips storing it.

**Comment by jbrooksuk** [comment]
Confirmed in v2.0.9.

Removing your custom `storeAs` method does fix the file replacement issues, but I've not dug deep enough to know why.

**Comment by jbrooksuk** [comment]
I've _just_ figured this out. The `id` doesn't exist when a resource is first being created.
