### ISSUE TITLE
Customize resource label

### ISSUE THREAD

**Issue by nicknick-io** [laravel/nova-issues#166]
We need support for adding a custom label for the resources in the sidebar.

I found out that i could hack it by redefining the 'public static label()' method inside the resource class, but that ain't clean at all.
We need a customizable label that can override the content of  'Resource::label()'.
__Example:__
```php 
class User extends Resource
{
    public static $label = 'Custom name';
}
``` 
It would be a good idea to make it fall back to the default method, where we get the class name of a resource.  *This literally took me 2 seconds to add to my local copy of Nova.*

**Comment by eullercdr** [comment]
+1 Excelente Idea

**Comment by v1nk0** [comment]
Overriding the `label` and `singularLabel` methods is also the way to localize the labels according to the documentation [(link)](https://nova.laravel.com/docs/1.0/customization/localization.html#overview), so I doubt if you should consider your solution a hack.

**Comment by nicknick-io** [comment]
v1nk0 Well, I think it's bad code if i have to override a method to localize stuff - for every resource.
 
Most of us aren't from a country where English is the spoken language, we don't care about singular strings, as the framework doesn't support that.

All i'm trying to say here, my damn change does not break anything.

**Comment by ralphschindler** [comment]
In the latest versions, there is a `public static function label()` that produces the label you could override.

My suggestion to @davidhemphill might be to add enhance that function as such:

```php
    public static function label()
    {
        if (property_exists(get_called_class(), 'label') && !static::$label != null) {
            return static::$label;
        }
        return Str::plural(title_case(str_replace('_', ' ', snake_case(class_basename(get_called_class())))));
    }
```

**Comment by nicknick-io** [comment]
@ralphschindler Only english is supported by Laravels str_plural, this thing does not fix my issue. (I need Danish, not every customer speaks the english)
I know as i state in my initial issue, that i'm aware that the  public static function label() can be overwritten - But that makes no sense if i only have to set a static string, dammit.

**Comment by taylorotwell** [comment]
It's perfectly clean to override the method.

**Comment by nicknick-io** [comment]
I will never understand what you describe as clean code, Taylor. Good thing
i decide what happens to my own copy - i have to fork it a private repo and
run that, Christ.

tor. 6. sep. 2018 kl. 19.10 skrev Taylor Otwell <notifications@github.com>:
