### ISSUE TITLE
Action::redirect and Action::openInNewTab with headers [request]

### ISSUE THREAD

**Issue by tiagoraposeiraff** [laravel/nova-issues#1660]
It would be good if the action redirect responses could include passing in header params.
Something like 
`return Action::openInNewTab($url)->with('MyHeader', $myHeaderValue)`
This would make it much more helpful when switching between different parts of the application.

**Comment by davidhemphill** [comment]
I'm not following. What do you mean specifically by "This would make it much more helpful when switching between different parts of the application." 

What are you trying to do that you can't?

**Comment by tiagoraposeiraff** [comment]
I'm trying to redirect the user to be logged in in our app from Nova.
Since our public facing app in not on Laravel (it's a separate React app with authenticates via jwt), redirecting the user to url doesn't do much.

This is my use case, but I believe it could be helpful in many ways, with or without monolith applications.

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
This doesn't seem to be possible, we're making a browser redirection and not an XHR or cURL request where we can extend the headers. 

That being said I'm removing the `request` label for now.

**Comment by lk77** [comment]
yeah i agree, be able to set a bearer token for example when redirecting will be awesome.
