### ISSUE TITLE
Nova routes localization

### ISSUE THREAD

**Issue by applyACS** [laravel/nova-issues#1662]
How can I change nova routes to include locale?
I tried adding middleware and it's not working

Setting path to 
`'path' => 'en/nova',`
works on en.

What I want is to access
`mydomain.com/en/nova`
`mydomain.com/de/nova`
`mydomain.com/fr/nova`
and so on...

Could not find a solution in documentation or in other issues

**Comment by h-zone** [comment]
try my another way:
https://gist.github.com/h-zone/052724a1d2c030cb2207133c289150e4

**Comment by applyACS** [comment]
I was hoping for a much more easier way.
I think nova should support localization in path...

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
