### ISSUE TITLE
Reorder left navigation items

### ISSUE THREAD

**Issue by skalero01** [laravel/nova-issues#1663]
Hi there, i got request for a client to reorder the menu, first i research and found that we could add the resources via `NovaServiceProvider` and the `resources` method and that would help ordering the menu and it did.

But it happens that i just respected the menu items inside a group, but not the groups order.

I have the next code on the provider

```
        Nova::resources([
            \App\Nova\Reservation::class,
            \App\Nova\Client::class,
            \App\Nova\EmailSent::class,
            \App\Nova\Location::class,
            \App\Nova\Tour::class,
            \App\Nova\TourOperator::class,
            \App\Nova\User::class,
        ]);
```

And i am getting the next view

![Screenshot_2](https://user-images.githubusercontent.com/2976641/59141709-a0005280-8977-11e9-898b-5c038151f7bb.png)

But i am waiting to show the reservations group first because was the first i added on `Nova::resources()`

How should i do it to ordering correctly? I saw that on Nova.php file line 544 there is the code that order the groups, if i remove sortKeys() it fix it. 

![Screenshot_1](https://user-images.githubusercontent.com/2976641/59141654-05077880-8977-11e9-81aa-3ccee7824e8f.png)

I will use this fix but dont want to have problems later when i update the laravel nova versions, so its something you could fix?

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).

**Comment by wbemanuel** [comment]
Here's how I sort resource groups without publishing any Nova resources by using View Composers:

```php
namespace App\Providers;

use ...
use App\Http\View\Composers\NovaNavigationComposer;

class NovaServiceProvider extends NovaApplicationServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        parent::boot();

        View::composer('nova::resources.navigation', NovaNavigationComposer::class);
...
```

This view composer sorts the grouped resources passed to `nova::resources.navigation`:
```php
namespace App\Http\View\Composers;

use Illuminate\Support\Collection;
use Illuminate\View\View;

class NovaNavigationComposer
{
    public const resourceGroupPriorities = [
        'Admin' => 10,
        'Group 1' => 20,
        'Group 2' => 20,
        'Other' => 9999,
    ];

    /**
     * Bind data to the view.
     *
     * @param View $view
     * @return void
     */
    public function compose(View $view)
    {
        $navigation = $this->sortGroups($view->navigation);
        $view->with('navigation', $navigation);
    }

    /**
     * @param Collection $navigation
     *
     * @return Collection
     */
    protected function sortGroups(Collection $navigation)
    {
        return collect($navigation)
            ->keys()
            ->sortBy(function ($group) {
                return self::resourceGroupPriorities[$group] ?? self::resourceGroupPriorities['Other'];
            })
            ->mapWithKeys(function ($group) use ($navigation) {
                return [$group => $navigation[$group]];
            });
    }
}

```
