### ISSUE TITLE
Abilyty to don't hash Password field

### ISSUE THREAD

**Issue by 4n70w4** [laravel/nova-issues#1664]
Case: need to save password for extertal integration.

Need show dots on index and details:
![image](https://user-images.githubusercontent.com/38257723/59189776-b2e77280-8b83-11e9-9e15-5eef294686e8.png)
and forms:
![image](https://user-images.githubusercontent.com/38257723/59189916-11acec00-8b84-11e9-9f18-a9cc235bc251.png)

But don't hash before save to DB:
![image](https://user-images.githubusercontent.com/38257723/59189877-f17d2d00-8b83-11e9-9df5-c0ce7db9ef2e.png)

And for internal authorization that hashing keeps.

**Comment by davidhemphill** [comment]
Use a `Text` field.

```php
Text::make('Password')->withMeta(['extraAttributes' => ['type' => 'password']])
```

**Comment by dkulyk** [comment]
```php
Password::make('Password')
    ->fillUsing(function($request, $model, $attribute, $requestAttribute) {
        $model->setPassword($request[$requestAttribute]);
    })
```
If you need store password when model will saved
```php
Password::make('Password')
    ->fillUsing(function($request, $model, $attribute, $requestAttribute) {
        return function() use ($request, $model, $requestAttribute) {
            $model->setPassword($request[$requestAttribute]);
        }
    })
```

**Comment by 4n70w4** [comment]
@davidhemphill not right. In the index and details password will be show as text.

**Comment by ziming** [comment]
@dkulyk What's the difference between your 1st and 2nd example? Trying to understand

**Comment by dkulyk** [comment]
Second code returns closure what will executed after saving the model.

**Comment by bilogic** [comment]
> Second code returns closure what will executed after saving the model.

Is there a use case for this?
