### ISSUE TITLE
Relationship attribute by relationship + name

### ISSUE THREAD

**Issue by nickkuijpers** [laravel/nova-issues#1665]
Hello,

This would be nice;

Text::make('Longitude', 'gpslocations.longitude');

Where gpslocations is the relation, and longitude is the field as it normally would be to target a value by the relationship.

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
