### ISSUE TITLE
Composer repository not been updated with 2.0.6

### ISSUE THREAD

**Issue by jakew009** [laravel/nova-issues#1666]
When trying to update to Nova 2.0.6 via Composer, there is an error.
Updating to 2.0.5 and previous versions works fine?

Please can it be updated :)

**Comment by pehbehbeh** [comment]
Satis doesn't seem to be up to date.  🤔 The tag is present [in the repository](https://github.com/laravel/nova/tree/v2.0.6) but not [via Satis](https://nova.laravel.com/include/all$01caa3f6cd1a31b460645694ccfce3d8ac813715.json):

<img width="200" alt="Bildschirmfoto 2019-06-11 um 14 05 08" src="https://user-images.githubusercontent.com/133831/59271009-39b75080-8c53-11e9-863b-72a82979de4e.png">

**Comment by pehbehbeh** [comment]
FYI: Taylor [is aware of the problem](https://twitter.com/taylorotwell/status/1138410206927286272).

**Comment by FaridAghili** [comment]
Looking forward to it...

**Comment by mvdnbrk** [comment]
@taylorotwell @davidhemphill any update on this?

Thanks!

**Comment by pehbehbeh** [comment]
2.0.6 is available now. Issue can be closed.
