### ISSUE TITLE
Sortable icon decreases in size

### ISSUE THREAD

**Issue by skoyah** [laravel/nova-issues#1668]
- Laravel Version: 5.8.18
- Nova Version: 2.0.4
- PHP Version: 7.3
- Operating System and Version: macOS Mojave.10.14.5
- Browser type and version: Chrome. 74.0.3729.169

### Description:
Sortable icon gets smaller if field name has more than one word.

### Steps To Reproduce:
When creating a new field for a resource and make it sortable, on the resource's index page the sortable icon becomes smaller if the column name contains multiple words. On higher resolution screens this becomes an issue for the user as the icons is barely perceptible.

<img width="439" alt="Screenshot 2019-06-12 at 18 34 31" src="https://user-images.githubusercontent.com/36083448/59373069-c7249e80-8d40-11e9-8b2f-442d298842b8.png">

**Comment by skoyah** [comment]
Hey @davidhemphill could you give me your feedback on why did you close the issue? :)

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍

**Comment by skoyah** [comment]
Thanks @davidhemphill!!!
