### ISSUE TITLE
How to customise resource index view

### ISSUE THREAD

**Issue by najaram** [laravel/nova-issues#1669]
I have created a resource and I need to customise it, need to add additional table at the bottom. 

So for example on my SessionResource index page, I need to add the records from TalentResource, by adding a separate table at the bottom.

I believe the default index resource page only shows 1 table.

Is there any way to do this?

Thank you.

**Comment by najaram** [comment]
It seems this would work, https://github.com/DigitalCloud/nova-custom-views

**Comment by vayurobins** [comment]
> It seems this would work, https://github.com/DigitalCloud/nova-custom-views

Please note that the package Nova Custom Views does not work work with Nova 2.8.0, so please check first.

**Comment by niunaiyi** [comment]
> > It seems this would work, https://github.com/DigitalCloud/nova-custom-views
> 
> Please note that the package Nova Custom Views does not work work with Nova 2.8.0, so please check first.

so what can I do?
