### ISSUE TITLE
SQL error after upgrading to 2.0.6

### ISSUE THREAD

**Issue by unlikenesses** [laravel/nova-issues#1670]
- Laravel Version: 5.8
- Nova Version: 2.0.6
- PHP Version: 7.1
- Operating System and Version: MacOS High Sierra
- Browser type and version: Chrome

### Description:

After upgrading to Nova 2.0.6, when I attempt to create a new item in a resource page, I get this error:

> Column not found: 1054 Unknown column 'original' in 'field list'

**Comment by unlikenesses** [comment]
The solution is to run migrations after upgrade:

```php
php artisan migrate
```

**Comment by audetcameron** [comment]
Same thing happened here, rand a composer update but the 2.0.6 nova has migrations to run.
php artisan migrate

**Comment by yehudahkay** [comment]
Perhaps mention to run php artisan migrate in update documentation
