### ISSUE TITLE
v2.0.6 doesn't support MySQL 5.6 or older because of new json field type in migration

### ISSUE THREAD

**Issue by peterchrjoergensen** [laravel/nova-issues#1671]
- Laravel Version: 5.8.22
- Nova Version: 2.0.6
- PHP Version: 7.2

### Description:

After updating to 2.0.6, I am having trouble with migrating.

`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json null, add `changes` json null' at line 1 (SQL: alter table `action_events` add `original` json null, add `changes` json null)`

The error appears to be happening because fields were changed from a text type to a json type.

I am using Amazon's optimized version of MySQL 5.6 for serverless infrastructure, which means that I can't upgrade to MySQL 5.7, which is the earliest version with support for the json type.

Doesn't this break semver? Can we update requirements in documentation? Revert the change?

**Comment by derrickschoen** [comment]
Laravel Version: 5.8.23
Nova Version: 2.0.6
PHP Version: 7.3

I am having the same problem

I had to change the field from "json" to "text" in:
vendor/laravel/nova/database/migrations/2019_05_10_000000_add_fields_to_action_events_table.php

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
