### ISSUE TITLE
FEATURE REQUEST: Order for key value field

### ISSUE THREAD

**Issue by yehudahkay** [laravel/nova-issues#1672]
FEATURE REQUEST 

It would be very helpful if the user could change the order of the key value pairs by dragging or arrows and then save. Thanks!

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by yehudahkay** [comment]
Thanks! Can you add the feature label? I can't add it.
