### ISSUE TITLE
MorphTo > UX improvement when there's no result

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#1675]
Laravel Version: 5.8.23
Nova Version: 2.0.6
PHP Version: 7.2.10
Operating System and Version: Windows 10
Browser type and version: Chrome 74 (64 bits)

### Description:

When i use a MorphTo field and some type does not has any results, there is no indication when there is no result. It just shows the same grayed-out 'Choose xxx' and nothing happens.

Browser console, json response:

```json
{"resources":[],"withTrashed":false,"softDeletes":true}
```
So there is an actual response, but the user will never now it the resource is still loading or ready (and no result).

### Steps To Reproduce:

```php
 Fields\MorphTo::make('org_level')
                ->types([\App\Nova\OrgLevel\Client::class, \App\Nova\OrgLevel\Department:class]);
//Some example types
```

**Comment by jbrooksuk** [comment]
This is sort of a bug, but more of a UX one, so I removed the `bug` label. I've pushed a PR which addresses this:

![image](https://user-images.githubusercontent.com/246103/62769094-3a703580-ba90-11e9-8f4b-b445dfe6dafd.png)
