### ISSUE TITLE
HasMany with specific Resource fails on related create

### ISSUE THREAD

**Issue by ragingdave** [laravel/nova-issues#1676]
- Laravel Version: 5.8.23
- Nova Version: 2.0.6
- PHP Version: 7.2
- Operating System and Version: CentOS7
- Browser type and version: Chrome

### Description:

When defining a `HasMany` relation on a resource, there is the ability to specify the resource as the third param like:

```php
HasMany::make('Name', 'relation', Resource::class)
```

It seems that if the resource class specified differs from the what nova auto-detects as the resource for that relation, the resource passed as no effect except when listing on a detail page.

While this is due to dealing with legacy data structures/systems, it's definitely unexpected as it's seemingly ignoring what I configured.

### Steps To Reproduce:

Pardon the Contrived Example here:

Models:

**Product:**

```php
function productLines() {
    return $this->belongsTo()->where('type', '!=', 'Book');
}
```

**Book extends Product**

**ProductLine**

products(): hasMany()

Resources:
**ProductLine**

```
HasMany('Products', 'products', Product::class)
HasMany('Books', 'products', Book::class)
```

The `Book` has many on the `ProductLine` resource is shown correctly, listed correctly, and overall looks correct, but then clicking the "Create Book" ends up only going to the `ProductResource` even though the Resource is explicitly configured differently.

**Comment by jbrooksuk** [comment]
@ragingdave can you please provide a link that reproduces this issue.

**Comment by jbrooksuk** [comment]
Sorry, but there's not enough information to go off of here. If the issue you have still persists, please feel free to open a new issue with all the details of what you're trying, what you expect to happen, what's happening, and how to reproduce it. Thanks!
