### ISSUE TITLE
Boolean + readonly does not work.

### ISSUE THREAD

**Issue by riddla** [laravel/nova-issues#1677]
- Laravel Version: 2.0.6
- Nova Version: 2.0.6
- PHP Version: 7.3.1
- Operating System and Version: macOS 10.14.4
- Browser type and version: Chrome Canary 77.0.3824.0

### Description:

I'm trying to disable a Boolean field, but it is displayed without a readonly attribute and therefore still toggleable/usable.

<img width="781" alt="Screenshot 2019-06-15 at 15 49 19" src="https://user-images.githubusercontent.com/174157/59552331-c761ab80-8f85-11e9-9ec5-c089cd64e05c.png">

### Steps To Reproduce:

```
Boolean::make(__('New'), 'status')
    ->onlyOnForms()
    ->readonly()
```

**Comment by davidhemphill** [comment]
Hey there, I was unable to reproduce this using the steps you provided. Everything seems to be working. As always, make sure you have the latest assets using `artisan nova:publish` passing the  `--force` option if necessary. If you find a way to reproduce this reliably on a new Nova install, please feel free to open a new issue.

**Comment by mustafatoker** [comment]
> Hey there, I was unable to reproduce this using the steps you provided. Everything seems to be working. As always, make sure you have the latest assets using `artisan nova:publish` passing the `--force` option if necessary. If you find a way to reproduce this reliably on a new Nova install, please feel free to open a new issue.

it's works, thanks :)
