### ISSUE TITLE
BelongsTo field cause Exception and record is not updated

### ISSUE THREAD

**Issue by lichtner** [laravel/nova-issues#1678]
- Laravel Version: 5.8.23
- Nova Version: 2.0.6 (only in 2.0.6)
- PHP Version: 7.3.6
- Operating System and Version: Ubuntu 18.04
- Browser type and version: Chrome
- Reproduction Repository: https://github.com/###/###

### Description:

After I try to update any record via Edit form of Resource every BelongsTo fields (select field) is not updated and I see this red Exception:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'original' in 'field list' (SQL: insert into `action_events` (`batch_id`, `user_id`, `name`, `actionable_type`, `actionable_id`, `target_type`, `target_id`, `model_type`, `model_id`, `fields`, `original`, `changes`, `status`, `exception`, `updated_at`, `created_at`) values (8df17d2a-6f2e-496f-9b67-87baf7ef0aed, 1, Update, App\DiaryRow, 65, App\DiaryRow, 65, App\DiaryRow, 65, , {"patient_id":1}, {"patient_id":5}, finished, , 2019-06-16 11:07:45, 2019-06-16 11:07:45))

But after downgrade to Nova 2.0.5 updating process is correct. I think this is a big issue.

**Comment by leigeber** [comment]
It appears this last release has migrations that have to be run to add a couple columns, original being one of them. Verify with ```php artisan migrate --pretend``` and then ```php artisan migrate``` to apply.

**Comment by lichtner** [comment]
Thanks, @leigeber, it was the issue. I don't know why but this migration `add_fields_to_action_events_table` was not applied on the server. I have a script for automatic deployment with migration (I use deployer) so now I run in manually and now it is working again. 

Thank you, you helped me a lot.
