### ISSUE TITLE
Display instance title on Attach Page

### ISSUE THREAD

**Issue by SuecoMarcus** [laravel/nova-issues#1680]
I'm trying to attach a `Permission` to a `Role`.

![Screen Shot 2019-06-16 at 2 13 25 PM](https://user-images.githubusercontent.com/6123682/59567237-6ac3c680-9041-11e9-9c4e-8b8f1121c85c.png)

The problem is that it's not clear which `Role` I am attaching the `Permission` to.

It would be really nice if Nova could display the `title` of the instance. In this example: the **Administrator** `Role`.

Thanks!

**Comment by davidhemphill** [comment]
As I'm not able to read the language in the example, can you tell me what is being displayed instead? By default it should use whatever is in the `title` column on the `Resource` class.

**Comment by SuecoMarcus** [comment]
Thanks for your reply @davidhemphill !

I have a Many-To-Many relationship between `Permission` and `Role`.

In the following screenshot, I'm trying to attach a `Permission` to a `Role` (called **Administrator**).
<img width="915" alt="Screen Shot 2019-06-28 at 7 11 52 PM" src="https://user-images.githubusercontent.com/6123682/60373984-a0b96100-99d8-11e9-909a-590515af0c8a.png">

The "problem" with that screen is that it's not clear which `Role` I am attaching the `Permission` to. In other words, it's not clear I'm trying to attach a `Permission` to the **Administrator**.

Does it makes sense?

Thanks!

**Comment by davidhemphill** [comment]
Thanks for explaining it. So basically the UX is such that you're not sure for which resource the permission is being attached. That right?

**Comment by SuecoMarcus** [comment]
@davidhemphill That's right!

I could be attaching the `Permission` to an **Editor**, an **Administrator** or some other `Role`.

**Comment by MCuello17** [comment]
I'm having the exact same problem. Is there any update on this or plans on implementing it? 👀

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
The feature has been added to v3.21.0
