### ISSUE TITLE
[BUG] BelongsToMany keeps loading when relationship returns empty array

### ISSUE THREAD

**Issue by bobbybouwmann** [laravel/nova-issues#1681]
- Laravel Version: 5.8.22
- Nova Version: 2.0.6
- PHP Version: 7.2
- Operating System and Version: alpine 3.9 (docker)
- Browser type and version: Chrome
- Reproduction Repository: none

### Description:
I have a relationship between mobility-cards and users. However some users don't have a mobility-card connected. Whenever this is the case the panel with the related cards for the users stays empty and keeps loading. THis is really confusing for the end users. 

<img width="1277" alt="Screenshot 2019-06-17 at 09 28 48" src="https://user-images.githubusercontent.com/5872362/59586477-56d0a100-90e3-11e9-8d77-830bab93faf6.png">

It seems that the backend gives the correct response, but the frontend is not handling this correctly
```
label: "Mobility Cards"
next_page_url: null
per_page: 5
prev_page_url: null
resources: []
softDeletes: false
```
The resources array is empty, so I would expect it would stop loading at this point.

### Steps To Reproduce:
* Create a one-to-many relationship between user and some model
* On the user resource load the belongs-to-many field (`BelongsToMany::make('MobilityCard', 'cards')`)
* See that the panel keeps loading (see screenshot from above)

Let me know if you need more information!

**Comment by richvida** [comment]
I'm also running into this issue.

**Comment by jbrooksuk** [comment]
I've tested this in Nova v2.0.9 and am unable to reproduce. The `HasMany` field correctly shows as empty.

![image](https://user-images.githubusercontent.com/246103/62222367-1e430900-b3ab-11e9-9a9f-8034c5bf8c14.png)
