### ISSUE TITLE
relatableQuery issue

### ISSUE THREAD

**Issue by bsormagec** [laravel/nova-issues#1682]
- Laravel Version: 5.8.23
- Nova Version: 2.0.6
- PHP Version: 7.3
- Operating System and Version: OSX
- Browser type and version: Chrome

### Description:

When i using BelongsTo field with same model and different fields i got problem to inject it with relatedQuery

**For Example**

```
BelongsTo::make(__('Manufacturer'), 'manufacturer', Vendor::class),
BelongsTo::make(__('Supplier'), 'supplier', Vendor::class),

public static function relatableManufacturers(NovaRequest $request, $query)
{
    return $query->whereHas('types', function ($q) {
        $q->where('vendors_types.type_id', 8);
    });
}

public static function relatableSuppliers(NovaRequest $request, $query)
{
    return $query->whereHas('types', function ($q) {
        $q->where('vendors_types.type_id', 8);
    });
}
```

But it works with only

```
public static function relatableVendors(NovaRequest $request, $query)
{
    return $query->whereHas('types', function ($q) {
        $q->where('vendors_types.type_id', 8);
    });
}
```

But i dont know how to understand which model trying to access this related query.

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).
