### ISSUE TITLE
npm run dev throws error on Ubuntu

### ISSUE THREAD

**Issue by bambamboole** [laravel/nova-issues#1684]
- Laravel Version: 5.8.23
- Nova Version: 2.0.6
- PHP Version: 7.2
- Operating System and Version: Ubuntu 19.04
- Browser type and version: irrelevant
- Reproduction Repository: irrelevant

### Description:
If your are using a case sensitive operating system like Ubuntu, the execution of `npm run dev` will fail with the following error
```
Module not found: Error: Can't resolve '../badge' in '/home/bambamboole/local_projects/layout/vendor/laravel/nova/resources/js/components/Detail'
 @ ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}],["env"]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}],"transform-runtime","transform-vue-jsx","syntax-jsx","transform-object-rest-spread"],"env":{"test":{"presets":[["env",{"targets":{"node":"current"}}]]}}}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources/js/components/Detail/BadgeField.vue 7:13-32
 @ ./resources/js/components/Detail/BadgeField.vue
 @ ./resources/js/fields.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/css/app.css
```

### Steps To Reproduce:
* Install a fresh Laravel with Nova
* cd ./vendor/laravel/nova
* mv webpack.mix.js.dist webpack.mix.js
* npm install
* npm run dev

### Steps To fix this bug:
Change the following:  
* vendor/laravel/nova/resources/js/components/Index/BadgeField.vue:8
* vendor/laravel/nova/resources/js/components/Detail/BadgeField.vue:10  

From  
```
import Badge from '../badge'
```
to  
```
import Badge from '../Badge'
```

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
