### ISSUE TITLE
ActionEvent configurable connection

### ISSUE THREAD

**Issue by drsdre** [laravel/nova-issues#1685]
It would be of great help to specify on which connection ActionEvent model and migration should work. For example in nova.php config (like Telescope):

```
 'database' => [
            'connection' => env('DB_NOVA_CONNECTION', 'default'),
        ],
```

P.s. right now 'Actionable' fails with SQL errors if the Model to which it was applied lives in a different database than ActionEvent table.

**Comment by drsdre** [comment]
Added a PR to handle this https://github.com/laravel/nova/pull/432

**Comment by alberto-bottarini** [comment]
I found a workaround. You can override `Actions()` method injected by `Actionable` trait in this way:

```
public function actions()
    {
        return $this->setConnection('myConnection')->morphMany(ActionEvent::class, 'actionable');
    }
```

**Comment by vpratfr** [comment]
Hi,

@davidhemphill would it be possible to know the status of this one? We would need this too, running a multi-tenant app, action events should be forced on system connection.

PR is not accessible as the repo is private.

Thanks.

**Comment by drsdre** [comment]
@vpratfr to get you started, the PR add this to config/nova.php:
```

	/*
	|--------------------------------------------------------------------------
	| Nova Storage
	|--------------------------------------------------------------------------
	|
	| This configuration options determines the storage that will be used to
	| store ActionEvent data.
	|
	*/
    'storage' => [
	    'database' => [
		    'connection' => env('DB_NOVA_CONNECTION'),
	    ],
    ],
```

To database/migrations/2018_01_01_000000_create_action_events_table.php and database/migrations/2019_05_10_000000_add_fields_to_action_events_table.php:
```
	/**
	 * The database schema.
	 *
	 * @var Schema
	 */
	protected $schema;
	/**
	 * Create a new migration instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
		$this->schema = Schema::connection(
			config('nova.storage.database.connection')
		);
	}
```

To src/Actions/ActionEvent.php it adds and replaces the user function:
```
	/**
	 * Get the current connection name for the model.
	 *
	 * @return string
	 */
	public function getConnectionName()
	{
		return config('nova.storage.database.connection');
	}
    /**
     * Get the user that initiated the action.
     */
    public function user()
    {
        return $this->belongsTo(config('auth.providers.'.config('nova.users.provider', 'admin').'.model'), 'user_id');
    }
```

And finally to tests/Controller/AuthenticationTest.php on line 40:
`config(['auth.providers.users.model' => User::class]);`

**Comment by vpratfr** [comment]
Ok. but is your PR going to be merged, or rejected? We import Nova via composer so our whole vendor folder is ignored, I cannot really change anything in there.

**Comment by JefferySJones** [comment]
Curious on the status of this as well :)

**Comment by davidhemphill** [comment]
Check out https://github.com/laravel/nova/pull/694

**Comment by vpratfr** [comment]
@davidhemphill As I said in the initial comment, PR 694 is not accessible to most of us as the repo is private...

![image](https://user-images.githubusercontent.com/2526465/68042677-c41c5180-fcd3-11e9-8200-754804a1c789.png)

**Comment by davidhemphill** [comment]
You can connect your account to the private GitHub repo: https://nova.laravel.com/settings#github

**Comment by vpratfr** [comment]
Cool. Sorry I did not know about that :) Thanks a lot.
