### ISSUE TITLE
Trix Field. Disable uploads\deletes files?

### ISSUE THREAD

**Issue by ps-hidden** [laravel/nova-issues#1686]
- Laravel Version: 5.8
- Nova Version: 2.0.5
- PHP Version: 7.2
- Operating System and Version: Windows 10
- Browser type and version: Chrome 75

### Description:
I use custom media library which can insert images to trix editor in laravel nova. But when i want to save post, Nova is tries upload inserted images to trix database, but i have not this db. And I always get error. The same situation when I try remove image from editor.

How can I disable work with database for trix editor

### Steps To Reproduce:
Added field Trix::make('Content')

**Comment by jbrooksuk** [comment]
Sorry, but we are unable to debug your issue without a reproducible code example. Once you provide that we can open this up again.

**Comment by ps-hidden** [comment]
I asked only about the possibility of disabling the download function. Is it possible?
Which reproducible code do you need?

**Comment by jbrooksuk** [comment]
By default the Trix field doesn't upload files if you drag the file onto the field. I'm unsure how to replicate the issue you're seeing based on the information you gave us.

**Comment by ps-hidden** [comment]
Okey:
1. In resourse set field:
`Trix::make('Content')->withMeta([ 'extraAttributes' => [ 'trix-nml' => 'unique_id' ] ])`
2. On Frontend add image to this editor
`let trix = document.querySelector('[trix-nml="unique_id"]');`
`trix.editor.insertHTML(<img src="url">)`
3. And when I want to save the post - Trix try to upload this images to the backend

Now I use it, to disable uploads:
`trix.editor.composition.attachments = [];`
Do you have a better way?
