### ISSUE TITLE
Laravel nova ignoring locale in HTML.

### ISSUE THREAD

**Issue by acubino** [laravel/nova-issues#1692]
In NOVA 2.0.6 is ignoring locale in HTML. Producing conflict with bundled translators (like google chrome).

vendor/laravel/nova/resources/router.blade.php
vendor/laravel/nova/resources/auth/router.blade.php

Have Html language hardcoded to english.

`<html lang="en" class="h-full font-sans antialiased">`

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
