### ISSUE TITLE
Pivot fields display blank when editing BelongsToMany relationships with non-standard pivot keys

### ISSUE THREAD

**Issue by mdpoulter** [laravel/nova-issues#1694]
- Laravel Version: 5.8.24
- Nova Version: 2.0.6
- PHP Version: 7.2.17
- Operating System and Version: Windows 10.0.18362 x64
- Browser type and version: Google Chrome 74.0.3729.169

### Description:
It seems that the Pull Request [laravel/nova#430](https://github.com/laravel/nova/pull/430) does not entirely fix the issue of attaching BelongsToMany relationships with non-standard pivot keys. Specifically, when editing an attached resource where the BelongsToMany relationship uses a non-standard pivot key, all the pivot fields display as empty.

From inspection, it appears that the problem may be emanating from line 22 in the `vendor/laravel/nova/src/Http/Controllers/UpdatePivotFieldController.php` file.

### Steps To Reproduce:
1. Create two models with a BelongsToMany relationship between them.
2. Define a non-standard pivot key for the relationship and include at least one pivot field e.g.
```
return $this->belongsToMany('App\Location')
            ->as('inventory')
            ->withPivot('quantity');
```
3. Create Nova resources for the two models with a BelongsToMany field and include the pivot field using the `->fields()` method.
4. Within the details pages of each resource, the pivot fields display correctly, however when clicking to edit any of the attached resources, the pivot fields all display as empty, regardless of their current value.

### Screenshots:
![nova-belongstomany-1](https://user-images.githubusercontent.com/1091085/59969010-45085700-9544-11e9-9330-dfbfa4671f4f.PNG)

![nova-belongstomany-2](https://user-images.githubusercontent.com/1091085/59969012-49cd0b00-9544-11e9-8a3d-b6308948db20.PNG)

**Comment by jaejamesdev** [comment]
+1
I'm also having this issue! A fix or work around would be great

**Comment by DSpeichert** [comment]
Same here, it clearly needs more comments to bump importance.

**Comment by tomaswisten** [comment]
This seems to still be unsolved in Nova 2.5.0! Any workarounds?

**Comment by mdpoulter** [comment]
Indeed, this is still unresolved as at

Laravel Version: 6.3.0
Nova Version: 2.5.0

Only workaround has been to remove all non-standard pivot attribute names from my models (all `->as('something')`) .

**Comment by mdpoulter** [comment]
Still unresolved in Nova 2.6.1 and not even a `bug` label yet, @jbrooksuk?

**Comment by matthewjumpsoffbuildings** [comment]
Its worse for me, the pivot fields arent even showing up at all in the form... 

For example I have this

![image](https://user-images.githubusercontent.com/41524/69262975-526d5e80-0c14-11ea-857d-86b9115872e9.png)

But when I click `Attach Artist` I get this

![image](https://user-images.githubusercontent.com/41524/69262900-31a50900-0c14-11ea-83a8-c6a5caf2945f.png)

I opened an issue #2161 before I saw this issue, I guess mine is slightly different since the fields arent even showing up for me...

**Comment by gavinhewitt** [comment]
> Im on Nova 2.7.1 and its worse for me, the pivot fields arent even showing up at all in the form...
> 
> For example I have this
> 
> ![image](https://user-images.githubusercontent.com/41524/69262975-526d5e80-0c14-11ea-857d-86b9115872e9.png)
> 
> But when I click `Attach Artist` I get this
> 
> ![image](https://user-images.githubusercontent.com/41524/69262900-31a50900-0c14-11ea-83a8-c6a5caf2945f.png)
> 
> I opened an issue #2161 before I saw this issue, I guess mine is slightly different since the fields arent even showing up for me...

Having the same issue, Nova 2.7.1

**Comment by zaiderikat** [comment]
This worked for me:
You can assign the pivot columns with the relationship like this
`
public function businesses()
    {
        return $this->belongsToMany(Business::class, 'area_business', 'area_id', 'business_id')->withPivot('summery');
    }
`

Just add `withPivot('summery')` in the Eloquent model alongside the relation, then you can call it in Nova fields.

**Comment by matthewjumpsoffbuildings** [comment]
@zaiderikat Did you not read the steps to reproduce section of the original post???
```
return $this->belongsToMany('App\Location')
            ->as('inventory')
            ->withPivot('quantity'); <--------
```
We have all been using `withPivot()`, its still not working correctly

**Comment by gillidandaweb** [comment]
Ran into similar issues, and whilst not an ideal solution, was at least able to get the pivot field working by removing `->as('...')` from the relationship.

**Comment by gillidandaweb** [comment]
As mentioned by @mdpoulter above, having `->as()` on a relationship stops Nova pulling pivot field data, still as of Nova 2.9.3:

**Works**

`    public function teams() {
        return $this->belongsToMany(Team::class)
            ->withPivot('squad_number');
    }`

![FireShot Pro Screen Capture #189 - 'SMSTC' - admin_2018_smstc_test_resources_teams_1](https://user-images.githubusercontent.com/7722146/72720025-f8840900-3b70-11ea-8a0b-18e00a7e8f55.png)

![FireShot Pro Screen Capture #193 - 'SMSTC' - admin_2018_smstc_test_resources_players_3](https://user-images.githubusercontent.com/7722146/72720039-0043ad80-3b71-11ea-82f8-2e1d47919a66.png)

![FireShot Pro Screen Capture #194 - 'SMSTC' - admin_2018_smstc_test_resources_players_3_edit-attached_teams_1_viaRelationship=teams](https://user-images.githubusercontent.com/7722146/72720051-020d7100-3b71-11ea-8da1-11073cd46868.png)

**Doesn't work**

`    public function teams() {
        return $this->belongsToMany(Team::class)
            ->withPivot('squad_number')
            ->as('squad_members');
    }`

![FireShot Pro Screen Capture #191 - 'SMSTC' - admin_2018_smstc_test_resources_teams_1](https://user-images.githubusercontent.com/7722146/72720073-0fc2f680-3b71-11ea-97c8-d98b9eb34200.png)

![FireShot Pro Screen Capture #192 - 'SMSTC' - admin_2018_smstc_test_resources_players_3](https://user-images.githubusercontent.com/7722146/72720084-15204100-3b71-11ea-874c-ce8b7523a8e0.png)

![FireShot Pro Screen Capture #195 - 'SMSTC' - admin_2018_smstc_test_resources_players_3_edit-attached_teams_1_viaRelationship=teams](https://user-images.githubusercontent.com/7722146/72720091-18b3c800-3b71-11ea-940b-6ddea1fbd9c6.png)

**Comment by ilvalerione** [comment]
Hi, using `->as()` in a BelongsToMany relationship seems to cause the same problem.

![Immagine](https://user-images.githubusercontent.com/13559278/73257887-dcade200-41c4-11ea-8479-ddd03e2a4d56.png)

Nova 2.9.4
Laravel 6.12

**Comment by alshf89** [comment]
this bug happen in `UpdatePivotFieldController` on index Method:
it's trying to access `pivot` variable hardcoded on `setRelation` method.

```php
class UpdatePivotFieldController extends Controller
{
    /**
     * List the pivot fields for the given resource and relation.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function index(NovaRequest $request)
    {
        $model = $request->findModelOrFail();
        
        $model->setRelation(
            $model->{$request->viaRelationship}()->getPivotAccessor(),
            $model->{$request->viaRelationship}()->withoutGlobalScopes()->findOrFail($request->relatedResourceId)->pivot
        );

        return response()->json(
            $request->newResourceWith($model)->updatePivotFields(
                $request,
                $request->relatedResource
            )->all()
        );
    }
}
```
I dont know how to send PR on Nova repo but it can be fix like this:

```php
class UpdatePivotFieldController extends Controller
{
    /**
     * List the pivot fields for the given resource and relation.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function index(NovaRequest $request)
    {
        $model = $request->findModelOrFail();
        $pivot = $model->{$request->viaRelationship}()->getPivotAccessor();
        
        $model->setRelation(
            $pivot,
            $model->{$request->viaRelationship}()
                ->withoutGlobalScopes()
                ->findOrFail($request->relatedResourceId)
                ->{$pivot}
        );

        return response()->json(
            $request->newResourceWith($model)->updatePivotFields(
                $request,
                $request->relatedResource
            )->all()
        );
    }
}
```
