### ISSUE TITLE
Queued Action __construct will run twice, and Override handleRequest will run before handle function 

### ISSUE THREAD

**Issue by cchsu23** [laravel/nova-issues#1696]
- Laravel Version: 5.8.17
- Nova Version: 2.0.6 
- PHP Version: 7.3.6

### Description:
1.Queued Action __construct will run twice,
=>should be once.
2.Override handleRequest will run before handle function 
=> should be run after last handle function which is queue.
### Steps To Reproduce:

Test Code
    public function __construct() 
    {
        $this->total = 0;
        info('====== __construct'.$this->total);
    }

    public function handle(ActionFields $fields, Collection $models)
    {
        $count = 0;
        foreach ($models as $model) {
            ++$count;
        }
        $this->total += $count;
        info('====== handle'.$this->total);
    }

    public function handleRequest(\Laravel\Nova\Http\Requests\ActionRequest $request)
    {
        parent::handleRequest($request);
        info('====== handleRequest'. $this->total);
    }

Input: Select 651 data for execute action
Log:

[2019-06-25 14:02:01] local.INFO: ====== __construct0  
[2019-06-25 14:02:07] local.INFO: ====== __construct0  
[2019-06-25 14:02:08] local.INFO: ====== handleRequest0  
[2019-06-25 14:02:10] local.INFO: ====== handle200  
[2019-06-25 14:02:10] local.INFO: ====== handle200  
[2019-06-25 14:02:10] local.INFO: ====== handle200  
[2019-06-25 14:02:10] local.INFO: ====== handle51

**Comment by davidhemphill** [comment]
Please describe what you're trying to do that requires overriding the `handleRequest` method.
