### ISSUE TITLE
Showing / Hiding Fields on relations

### ISSUE THREAD

**Issue by jacenre** [laravel/nova-issues#1697]
There is [no direct option](https://nova.laravel.com/docs/1.0/resources/fields.html#field-column-conventions) for Nova to only display certain fields on the main resources page, but leave those fields out when viewing the relation on the details page of another resource. Using onlyOnIndex will have the Field appear in both tables.
There should be an option to onlyOnRelation, since hideFromIndex also removes the option from the relation on the resource details page.

## Example
I have a Questions and Steps resource, in which a Question belongsTo a Step and a Step hasMany Questions. Question has an order field that is based on the order of set of questions belonging to a Step. On the Step details page, the HasMany relation to Questions is shown using `HasMany::make('Questions')`. Currently, the order field appears on the details page and on the main Question resource page.

`/nova/resources/steps/2`
![The order field displaying on the HasMany relation](https://i.ibb.co/bHQd63V/order.png)

Only, this order field is useless on the Question resource page, as the order field is calculated based on the order of the question _within_ a Step.

`/nova/resources/questions`
![The order field displaying on the Question resource page](https://i.ibb.co/DMQNBGd/order2.png)

There only is currently no way to display this Order Field on the Step Details page, but not on the Question resource page using methods described [here](https://nova.laravel.com/docs/1.0/resources/fields.html#field-column-conventions).

**Comment by LorensoD** [comment]
You could do something like this:

```
public function fields(Request $request)
{
    return [
        ...
        $request['viaResource'] === 'questions' ? OrderField::make('Order'):
        ...
    ];
}
```

Now the field won't show up in any relation table 😊

**Comment by p4rz1val** [comment]
A `->hideOnResource()` method would be a cleaner solution in this scenario, so bumping this issue.

**Comment by stancl** [comment]
If you want to hide something from all relationships, you may use:

```php
->hideFromIndex(function (ResourceIndexRequest $request) {
    return $request->viaRelationship();
}),
```

**Comment by madsem** [comment]
You can also use the request, like so:

```php
/**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     *
     * @return array
     */
    public function fields(Request $request)
    {
        if ($request->exists('viaRelationship')) {
            return $this->buildFieldsForRelationshipIndex();
        }

        return $this->buildFields();
    }
```

**Comment by samrap** [comment]
Nova fields are macroable, so you can actually define these in your service provider:

```php
    Field::macro('hideFromRelationshipsDetail', function () {
            /** @var \Laravel\Nova\Fields\Field $this */
            return $this->hideFromDetail(function (ResourceDetailRequest $request) {
                return $request->viaRelationship();
            });
        });

        Field::macro('hideFromRelationshipsIndex', function () {
            /** @var \Laravel\Nova\Fields\Field $this */
            return $this->hideFromIndex(function (ResourceIndexRequest $request) {
                return $request->viaRelationship();
            });
        });
```

And then use them on your fields like regular methods:

```
Text::make('Name')->hideFromRelationshipsIndex(),
```

**Comment by cweiske** [comment]
The macro needs to be added in `app/Providers/NovaServiceProvider.php::register()` with the following imports:
```
use Laravel\Nova\Fields\Field;
use Laravel\Nova\Http\Requests\ResourceIndexRequest;
```
