### ISSUE TITLE
full width metrics getting cropped

### ISSUE THREAD

**Issue by robinstraub** [laravel/nova-issues#1698]
Metrics with full width are getting cropped.

### Versions:
- Laravel Version: 5.8.23
- Nova Version: 2.0.6
- PHP Version: 7.3
- Operating System and Version: MacOS 10.14.5
- Browser type and version: Chrome 75.0.3770.100

### Description:
When I define a metric width (`(new CustomMetric)->width('full'),`) and set it as `full`, the rendering gets cropped.

![image](https://user-images.githubusercontent.com/17799181/60084193-5bc2cf80-9737-11e9-918e-97351a6486c1.png)

On the other side it is fine on other sizes (`1/2` or `1/3`). After looking at the DOM, the `card-panel` class appears missing. Is this an expected behavior ?

### Steps To Reproduce:
 - Create a custom metric
 - Set the width to `full`

**Comment by cwcrawley** [comment]
Subscribing to this as I'm experiencing the same behaviour.

Laravel Version: 5.8.29
Nova Version: 2.0.9
PHP Version: 7.1.19
Operating System and Version : MacOS 10.14.5
Browser: Firefox Developer Edition 69.0b5

**Comment by jbrooksuk** [comment]
Confirmed in v2.0.9 

If you resize the window, the chart redraws and stops cutting off.

**Comment by dillingham** [comment]
Card has a height vs min height

**Comment by jbrooksuk** [comment]
This no longer happens in v2.0.10:

![image](https://user-images.githubusercontent.com/246103/62766547-a2bc1880-ba8a-11e9-813b-658185d41b55.png)

**Comment by mvdnbrk** [comment]
@jbrooksuk This issue does not seem to be resolved.

Nova v2.0.11

**Comment by jbrooksuk** [comment]
@mvdnbrk have you ran `php artisan nova:publish`? Again, this isn't happening on v2.0.11 for me:

![image](https://user-images.githubusercontent.com/246103/63100546-32703400-bf6f-11e9-8faa-ef0ba33439e3.png)

**Comment by Ahmed-creatify** [comment]
the same issue here

**Comment by MorganeMeganck** [comment]
I have the same issue :( on v2.10.0

**Comment by jbrooksuk** [comment]
What happens if you select a different timeframe and then switch back, does it correct itself?

**Comment by MorganeMeganck** [comment]
Yes it does

**Comment by mvdnbrk** [comment]
Setting width to `full` results is the following HTML:

```html
<div class="px-3 mb-6 w-full">
    <div class="card relative px-6 py-4">
        ....
    <div>
</div>
``` 
Like @robinstraub mentioned earlier the `card-panel` class is missing.
The `card-panel` class sets the height to 150px.

```html
<div class="px-3 mb-6 w-full">
    <div class="card relative px-6 py-4 card-panel">
        ....
    <div>
</div>
```
