### ISSUE TITLE
Need a way to set the resource gender

### ISSUE THREAD

**Issue by disitec** [laravel/nova-issues#17]
In languages such Spanish we need a way to tell Nova how to translate a certain sentence. For example:

`"The :resource was created!": ":resource creado con éxito!",`

A dog is `Perro creado con éxito`

A house is `Casa creada con éxito`

**Comment by themsaid** [comment]
planned for an upcoming release

**Comment by atehnix** [comment]
Plans have changed?

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by atehnix** [comment]
Open or closed is not important.
It is important that at least sometimes they come in without leaving the question unanswered.

Already half a year ago "planned for an upcoming release".
It seems to be not entirely true.
