### ISSUE TITLE
"Select All" Buttons in index view not working (Safari only)

### ISSUE THREAD

**Issue by mrmonat** [laravel/nova-issues#170]
As seen in the Image the "Select all" Dropdown Buttons don't work in Safari (v11.1.2) when clicking. They will work if you press space key.

Nova Version is 1.0.6

![dropdown bug_1](https://user-images.githubusercontent.com/17597850/44612816-f26aeb00-a80b-11e8-9318-6a46a0f73f94.gif)

**Comment by sabid** [comment]
the same problem.

**Comment by kotfire** [comment]
+1 Same problem on Google Chrome Linux

**Comment by erhansogut** [comment]
+1 Same problem

**Comment by vootrunner** [comment]
Same issue. Nova v1.0.12. Nothing logged in the laravel log or in the JS console.

**Comment by cloudkserg** [comment]
Same issue. Chrome Linux

**Comment by krisons** [comment]
Same issue. Safari Mac

**Comment by desthercz** [comment]
Same problem with Microsoft Edge

**Comment by jasonmccallister** [comment]
Having the same issue on the latest version of Nova (v1.1.4)

**Comment by dillingham** [comment]
Related: https://github.com/laravel/nova-issues/issues/86 https://github.com/laravel/nova-issues/issues/170 https://github.com/laravel/nova-issues/issues/533

**Comment by davidhemphill** [comment]
This has been fixed and will be included in an upcoming release.

**Comment by S-anasol** [comment]
v1.3.2 
dont work again

**Comment by dkulyk** [comment]
@S-anasol Make new PR for it.
