### ISSUE TITLE
Feature: hide upload button for image on forms

### ISSUE THREAD

**Issue by 4n70w4** [laravel/nova-issues#1700]
Case: I want just show captcha image on form without delete and upload button.

Current:

![image](https://user-images.githubusercontent.com/38257723/60115817-76209b80-977f-11e9-9b87-f1bc824fc32f.png)

I want:

![image](https://user-images.githubusercontent.com/38257723/60115902-a36d4980-977f-11e9-9b70-bc20f584df5d.png)

Currently I cat set `readonly()` for Image.
But this is just disable upload, but shows those elements.
Also delete button works for readonly image...

**Comment by baykier** [comment]
same demands for me!

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
