### ISSUE TITLE
Feature: Add support for suburb field for "Place" field

### ISSUE THREAD

**Issue by webaction** [laravel/nova-issues#1701]
Case: As a user I want to set the suburb from the Algolia places suggestions object into a Text field when I edit a resource.

![seaworld](https://user-images.githubusercontent.com/2551285/60155527-c6eecd80-982d-11e9-9769-8f4958e885d8.png)

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
