### ISSUE TITLE
Feature: translations with support for declension and the number of nouns

### ISSUE THREAD

**Issue by 4n70w4** [laravel/nova-issues#1702]
Hi, I'm trying to translate the application into Russian, but I have a lot of problems. The translation looks crooked. The main problem: I need to change the endings of words depending on the action and gender of world. For example:

Create Organization => Создать Организаци**я**; but need Создать организаци**ю**

Also the name of the resource must be written without a capital letter.

Also need to maintain the gender of word.

In this case need change adjective form depending on the kind of word:

`New :resource` -- `new` must have 3 translations variations depends on the gender of word:

male form: Нов**ый**
female form: Нов**ая**
neuter form: Нов**ое**

Case:

`Create & Add Another` => `Создать & Добавить другой`.

But depending on the gender of the word, variations must be considered:

male form: Создать & Добавить друг**ой**
female form: Создать & Добавить друг**ую**
neuter form: Создать & Добавить друг**ое**

But the plurar one for for all genders of world:

Создать & Добавить друг**ие**

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
