### ISSUE TITLE
Unable to get parent resources’s id on relatioship’s filter

### ISSUE THREAD

**Issue by RicLeP** [laravel/nova-issues#1704]
- Laravel Version: 5.8.26
- Nova Version: 2.0.7
- PHP Version: 7.1.28

I have the resources Bookings and BookingUsers. A Booking can have many BookingUsers. A Booking will only every contain a subset of all the Users in the system so I want to be able to filter by only those Users who are linked to the Booking.

```
// Nova/Booking.php

public function fields(Request $request)
{
    HasMany::make(\BookingUser::class, 'attendees'),
}
```

I can find no way to find/pass the Booking’s ID to a filter on the relationship.

```
// Nova/filters/BookingUser.php

public function options(Request $request)
    {
    	$users = \App\BookingUser::whereBookingId($bookingId)->with('user')->get();

        return $users->pluck('user_id', 'user.fullname')->toArray();
    }
```

This would be required to limit the users in the filter selectbox to only those who have booked this event. Wihthout it all users in the system need to be displayed.

**Comment by jbrooksuk** [comment]
I believe that the value you're looking for is in the request, either as `resourceId`, `viaResourceId` or it may be in the segment.
