### ISSUE TITLE
Change field's value based on value of another field  dynamically

### ISSUE THREAD

**Issue by FofanaAmara** [laravel/nova-issues#1705]
Hello everybody , 

here is my issue , i have two fields . In one field i have to enter an amount and on the second field i need to automatically dispaly a discounted amount( amount of first field - 10% discount) .

In a normal project i would use the javascript on change event of the first field and update the second field  value at this moment . 

Is there any way to add a custom script to my nova form so that i can achieve that ? 

<img width="877" alt="nova issue" src="https://user-images.githubusercontent.com/13106136/60250634-4ed4e600-98c7-11e9-89d1-09c15dc92c0f.PNG">

**Comment by davidhemphill** [comment]
Yes, you can create a custom field to handle the necessary logic for your use-case: https://nova.laravel.com/docs/2.0/customization/fields.html

**Comment by threeaccents** [comment]
@FofanaAmara Have you figured out how to do this? I checked out the docs but couldn't see how to grab other fields values in my custom field.

**Comment by TonnyORG** [comment]
@threeaccents @FofanaAmara davidhemphill anyone made this at the end? I don't find references to pull values from another fields while creating my custom field, any advice?

**Comment by Payetus** [comment]
+1

**Comment by evidencefrank** [comment]
+1

**Comment by jhayg12** [comment]
+1

**Comment by leonakaodev** [comment]
Only a way for those who join here in the future, you can create a method inside your VueCompoenent:

```
findFieldByAttribute (attribute) {
    return this.$parent.$children.find(brotherField =>
        brotherField.field.attribute === attribute,
    );
}
```

**Usage:**

```
const amountField = this.findFieldByAttribute('amount');
const amountToRecharge = amountField.value;
```
