### ISSUE TITLE
BelongsTo user field value back to null after click add button

### ISSUE THREAD

**Issue by opanegro** [laravel/nova-issues#1707]
- Laravel Version: 5.8
- Nova Version: 2.0.7
- PHP Version: 7.3
- Operating System and Version: Mojave 10.14
- Browser type and version: 75.0

### Description:
BelongsTo value back to null after click add button if another input is required
### Steps To Reproduce:
![Before Created](https://user-images.githubusercontent.com/41967704/60347195-fac12300-99e6-11e9-9d33-427ef9f493e1.png)
![After Click Add Button](https://user-images.githubusercontent.com/41967704/60347212-044a8b00-99e7-11e9-9d91-f10a720719b6.png)

**Comment by MattHall10** [comment]
I've also encountered the same issue, it is not just with inputs being required where they have an empty value but where a validation error is returned for any other field. 

This happens for me both when you go to the Resource, in this case Users, and create a post from there, and when you go directly to the Posts resource and have set a default value using withMeta and then set the field to be read only.

Does anyone have any resolutions to this as the only way around i've found so far is to refresh the page so the default value is set again meaning that all previously entered data is gone, which on longer forms is annoying.

**Comment by depsimon** [comment]
Also have this issue, when another field is invalid or the `BelongsTo` field itself.

Using v2.0.9

**Comment by dillingham** [comment]
duplicate https://github.com/laravel/nova-issues/issues/1576

**Comment by jbrooksuk** [comment]
Closed as duplicate.
