### ISSUE TITLE
Username and Avatar do not update

### ISSUE THREAD

**Issue by AlexanderRobb** [laravel/nova-issues#1708]
- Laravel Version: 5.8.26
- Nova Version: 2.0.5
- PHP Version: 7.3.1
- Operating System and Version: MacOS 10.14.3
- Browser type and version: Chrome 75.0.3770.100

### Description: I noticed after updating the currently logged in user's Username and Avatar, the username and avatar in the top right corner do not update to the new data.

I know refreshing the page updates the username and avatar in the top right corner, but is there a way to have them automatically update when the user's information is updated?

### Steps To Reproduce:

1) Login 
2) Go to the Users resource page
3) Edit the user that is currently logged in 
3) Edit the Username and the Avatar image
5) Click `Update User'

![Screen Shot 2019-06-28 at 10 09 40 AM](https://user-images.githubusercontent.com/44243981/60354899-ece1b280-9992-11e9-991b-272815f529c3.png)

**Comment by mvdnbrk** [comment]
The username and avatar is in the `/resources/views/vendor/nova/partials/user.blade.php` file.

This is not a reactive vue component so it does not stay in sync when you update the current user.

At the moment only a full page reload will refresh the data.

**Comment by davidhemphill** [comment]
Not a bug, but we might do something with this as a feature request.

**Comment by mvdnbrk** [comment]
This may not be a bug on the backend, however from a users perspective this might be considered as a bug. 

Updating user data does not get reflected since we left it over to the `user.blade.php` file.

I got this question as well and had to reply with "do a hard refresh".
