### ISSUE TITLE
Filter indexquery with belongstomany relationship

### ISSUE THREAD

**Issue by aozen** [laravel/nova-issues#1709]
Hello there, i have a question about **indexQuery** function. In my situation there are users and tasks table. A task may have many users. And each users must saw own tasks. Not other ones. So i need the edit **indexQuery** function. 
Default one is: 

```
public static function indexQuery(NovaRequest $request, $query)
{
return $query;
}
```

I changed it like that: 
```
public static function indexQuery(NovaRequest $request, $query)
{
return $query->whereHas('users');
}
```

users() is my has many relationship function in Task model.

```
public function users() {
        return $this->belongsToMany(User::class);
    }
```

But $query->whereHas('users') is not return related rows. It returns all rows. I just want to return "related with users"  rows. 

I have **task_user** pivot table. Saving just **task_id** and **user_id** Relations are in there. How can i run this with right way?

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).

**Comment by 949mac** [comment]
Super old, I know... but I stumbled upon this issue via Google.

Have a look at relatableQueries: https://stackoverflow.com/questions/53180510/nova-relatable-filtering-how-to-filter-users-whose-company-id-matches-location
