### ISSUE TITLE
Customizing views, simple but powerful improvements

### ISSUE THREAD

**Issue by freshway** [laravel/nova-issues#1710]
Hi.

I think that it would be really important to allow override labels (header and buttons) and their visibility in the form of each resource.

There are many situations in which the actions and purpose of the forms (and their visibility) must be indicated more user friendly.

Another improvement could help developers and designers could be the inclusion of a class with the name of the resource at the level of the body or div.content that would allow customizing colors, visibilities, etc. at the resource level.

- Allow override resource labels. "Add User" could be changed by "User Registration"
- Hide labels at resource view. Instead "Add user", I would like to have the option to add a "computed field" with a view content.
- Hide "add and create new" button
- Override "Create <resource>" button by resource. "Create User" could be changed by "complete user registration". "Cancel" to "Discard".
- Add css class to all resources based on resource-singular-label at view and creation and resource-plural-label on index

I feel that, it may seem like a lot of changes, but all associated to the sending of options through InteractsWithResourceInformation that would allow a high personalization level and improvements from the Nova core.

**Comment by davidhemphill** [comment]
Help me understand :-D

1. You can already do this with translation.
2. I'm not sure what this means.
3. What are you trying to do that you need to remove this from the admin tool?
4. Again you can already do this with built-in translation abilities.
5. Again, what are you trying to do that you need to be able to style each form uniquely?
