### ISSUE TITLE
Tweak login procedure to store data while the user login to Nova

### ISSUE THREAD

**Issue by edward-sakamoto** [laravel/nova-issues#1711]
Hello, I am currently implementing Laravel Nova in my application and wanted to tweak the login procedure a bit by also enabling saving of, lets say Ip address and login time to last_login for analysis purposes . May I know how that can be achieved?

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).

**Comment by edward-sakamoto** [comment]
I have tried that but no response on the same. Hope to get some information on how to achieve it.
