### ISSUE TITLE
How to reuse nova views?

### ISSUE THREAD

**Issue by Dontorpedo** [laravel/nova-issues#1712]
Hello,

Is it possible to reuse the Nova views (Index, create etc.) in a tool instead of writing the same functionality twice?

if its possible, is there any documentation for this or can anyone give me a hint?

thanks.
D

**Comment by davidhemphill** [comment]
In theory, yes, if your data model matched Nova's perfectly. In practice, it's not that practical.

Also, this issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).
