### ISSUE TITLE
Action log on external model doesn't work

### ISSUE THREAD

**Issue by maede-a** [laravel/nova-issues#1713]
- Laravel Version: 5.8.26
- Nova Version: 2.0.7
- PHP Version: 7.1.30
- Operating System and Version: Ubuntu 18.04
- Browser type and version: chrome  75.0.3770.100 

### Description:
I'm writing admin panel with nova. for decoupling from the main app, we are using 2 databases, the first one for the main project and the second one has an admin table contains nova users' data. 
I've created a user model that refers to the user table in my main database and I define action on user resource. I want to queue this action and see action log for that so I add actionable trait to the user model. when I've tried to run this action, I get this error:
SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "action_events" does not exist
I think it's because of nova is trying to write action log data in the first database, because the user table is in that, but I want to save action logs in admin panel database. is there any way that is can set db connection for saving action log directly?
### Steps To Reproduce:
1- change authenticable model name to admin
2- define user model and resource with a specific database connection
3- define an action and add that to user resource actions
4- run action

**Comment by davidhemphill** [comment]
Not really a bug, but I get why it's inconvenient. There's an update in the works to support this.

**Comment by maede-a** [comment]
@davidhemphill any plan on release date?

**Comment by JefferySJones** [comment]
@davidhemphill Would be great to hear where this update is at, as I'm experiencing the same issue

**Comment by davidhemphill** [comment]
Check out https://github.com/laravel/nova/pull/694

**Comment by pjhartin** [comment]
@davidhemphill - I think the issue or PR you linked is private. 

I'm also having a similar problem where an artisan command being called via a HTTP request tries to write an action_event entry, despite no tables existing yet. i.e. scenario is fresh deploy and a HTTPS call to migrate databases.

Results in the following:
```
SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "action_events" does not exist
LINE 1: SELECT obj_description('action_events'::regclass) AS table_c...
                               ^ {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT obj_description('action_events'::regclass) AS table_comment;':
```
