### ISSUE TITLE
BelongsToMany must appear before BelongsTo of the same relation in order for pivot fields to show.

### ISSUE THREAD

**Issue by rickmacgillis** [laravel/nova-issues#1714]
- Laravel Version: 5.8.27
- Nova Version: 2.0.8
- PHP Version: 7.3.6
- Operating System and Version: Linux Mint 19.1 Tessa
- Browser type and version: Chrome 75

### Description:
In order to use the pivot fields for `BelongsToMany` when you have the same related model in a `BelongsTo` relationship, the `BelongsToMany` must come first in order for Nova to find the callback. It also begs the question as to what would happen if you had multiple `BelongsToMany` relationships on the same Nova Resource.

My guess is that somewhere there's a hashmap mapping models to the `fieldsCallback`. It needs to be expanded to look at the relationship method as well. (Ex. `$map[$modelName][$relationshipMethodName] = $fieldsCallback;`)

### Steps To Reproduce:
1. Install Laravel Nova
2. Create a model to map users to. (Ex. `Roles` as in the docs.)
3. Create a pivot table with a custom pivot field.
4. Create a `BelongsTo` relationship for the `Role` to show who created it.
5. Create a `BelongsToMany` relationship to whis `User`s are assigned that role.
6. Make the Nova Resources to reflect those models. Use the following code to demonstrate the problem.

```
BelongsTo::make(__('Created By'), 'creator', User::class)

BelongsToMany::make(__('Users assigned to role'), 'users', User::class)
->fields(function () {
    return [
        Text::make('Custom');
    ];
}),
```
Try attaching the `User` to the `Role` and you won't see your custom field. Now flip that around and you'll see the fields when you attach the `User` to the `Role`.

**Comment by DSpeichert** [comment]
I seem to have the same problem with a twist. In my case, the fields do not show on the OTHER model's index.

So I when i swap the order in `App\Nova\Role.php` to have `BelongsToMany(..., User::class)`, I can see the fields in the index user_roles shown the the User's detail page.

**Comment by stevelacey** [comment]
@DSpeichert yep that's a feature of the same problem; I imagine @rickmacgillis just didn't notice – I'm here because this impacts any Laravel Spark user who chucks the Team model into Nova and puts `owner` and `users` the logical way around – sad times, hope this gets fixed, I've lost hours and hours to this hacking around the problems it causes with policies to show/hide the attach links.
