### ISSUE TITLE
Laravel Nova 2.0.8 Don't show fields in Create and Update Views

### ISSUE THREAD

**Issue by henryavila** [laravel/nova-issues#1715]
- Laravel Version: 5.8.27
- Nova Version: 2.0.8
- PHP Version: 7.3.6
- Operating System and Version: Mac OS 10.14.5 on Dock Image (hitalos/php:latest) (Alphine Distro)
- Browser type and version: Google Chrome 75 or Safari 21.1.1

### Description:
With the new version of Laravel Nova (2.0.8), in all my resources, the Create and Update view show no fields, just the buttons.
There`s no error in the HTTP request. 
The error happen in all Resources. Even in Third Party Tools

As example, The creation-fields request, return the data, as usual:
```
{
    "fields": [
        {
            "component": "text-field",
            "prefixComponent": true,
            "indexName": "Nome",
            "name": "Nome",
            "attribute": "name",
            "value": null,
            "panel": "Criar Setor",
            "sortable": true,
            "nullable": false,
            "readonly": false,
            "textAlign": "left"
        },
        {
            "component": "trix-field",
            "prefixComponent": true,
            "indexName": "Descrição",
            "name": "Descrição",
            "attribute": "description",
            "value": null,
            "panel": "Criar Setor",
            "sortable": false,
            "nullable": false,
            "readonly": false,
            "textAlign": "left",
            "shouldShow": false,
            "withFiles": false
        },
        {
            "component": "text-field",
            "prefixComponent": true,
            "indexName": "Local",
            "name": "Local",
            "attribute": "place",
            "value": null,
            "panel": "Criar Setor",
            "sortable": true,
            "nullable": false,
            "readonly": false,
            "textAlign": "left"
        }
    ],
    "panels": [
        {
            "component": "panel",
            "name": "Criar Setor",
            "showToolbar": true
        }
    ]
}
```

### Steps To Reproduce:
A single composer update run trigged this error for me.

**Comment by augmentspace** [comment]
Same issue here. No fields are showing on the create/edit pages.

**Comment by KevFinn** [comment]
I'm having the same issue as well. No fields, just the 2 Update buttons.

**Comment by davidhemphill** [comment]
Make sure you've published the latest Nova assets:

`php artisan nova:publish --force`

**Comment by KevFinn** [comment]
That worked for me. Thanks!

**Comment by Frozire** [comment]
Warning to others; running `php artisan nova:publish --force` will override any changes you have done to config.

**Comment by henryavila** [comment]
It works, Thanks.

ps: I believe this information should be in Release notes.

**Comment by peterbrinck** [comment]
It's already in the docs: https://nova.laravel.com/docs/2.0/installation.html#updating-nova

**Comment by henryavila** [comment]
Thanks @peterbrinck !

**Comment by naro-code-lab** [comment]
This 

> Make sure you've published the latest Nova assets:
> 
> `php artisan nova:publish --force`

This worked for me
