### ISSUE TITLE
Update view fields do not have the resourceId prop as of 2.0.8

### ISSUE THREAD

**Issue by Tarpsvo** [laravel/nova-issues#1718]
- Laravel Version: 5.8.27
- Nova Version: 2.0.8
- PHP Version: 7.3.4
- Operating System and Version: MacOS 10.14.4
- Browser type and version: Chrome 75
- Reproduction Repository: N/A

### Description:

Is the removal of resourceId prop from Vue fields in the Update view intentional or a bug in Nova 2.0.8? One of my packages depended on it and as the code rendering the fields was changed, the resourceId has been removed from the fields.

js/views/Update.vue form panel loop is missing :resource-id="resourceId" and js/components/Form/Panel.vue would need the resourceId prop definition and the field rendering loop should pass the resourceId prop along.

Detail view panels and fields currently have the `resourceId` prop. It also appears fields such as `FileField` and `BelongsToField` still depend on `resourceId`.

Would it be possible to add that "feature" back?

**Comment by davidhemphill** [comment]
Try updating to the latest 2.0.9 version which has a fix for passing the `resourceId` to the Panels, and thus the underlying Fields.

**Comment by Tarpsvo** [comment]
Thank you! Remarkably swift reaction!

**Comment by iamoat** [comment]
Updated to 2.0.9 but got this warning message in console. 

[Vue warn]: Invalid prop: type check failed for prop "resourceId". Expected String with value "1000", got Number with value 1000.

Noticed that in Panel.vue the resourceId's type must be String. 

However all my ids are in integer. What should I do? Shouldn't Nova automatically cast the id to String for me? 

Best Regrards, 

![image](https://user-images.githubusercontent.com/1286835/61880480-2caea200-af1f-11e9-8e1d-8c451f8f5afc.png)

**Comment by techouse** [comment]
I can confirm this issue with **v2.0.9**

**Comment by jbrooksuk** [comment]
@techouse could you please open a new ticket with a reproducible code sample?
