### ISSUE TITLE
Panels depending on existing resource data do not work as of 2.0.8

### ISSUE THREAD

**Issue by Tarpsvo** [laravel/nova-issues#1719]
- Laravel Version: 5.8.27
- Nova Version: 2.0.8
- PHP Version: 7.3.4
- Operating System and Version: MacOS 10.14.4
- Browser type and version: Chrome 75
- Reproduction Repository: N/A

### Description:

I have a bunch of panels that depend on a `Select` field's value on a resource. As of Nova 2.0.8 and the introduction of panels to Update and Create views, the panels are no longer displayed at all.

This is due to how `UpdateFieldController.php` works.

`UpdateFieldController.php - Lines 22-25`
```
return response()->json([
  'fields' => $resource->updateFieldsWithinPanels($request),
  'panels' => $request->newResource()->availablePanelsForUpdate($request),
  ]);
```

When querying panels, a brand new resource is used, even though we have access to an existing one. Would it not make sense to use the existing resource here?

Using the existing resource `'panels' => $resource->availablePanelsForUpdate($request),` would fix my `nova-page-manager` package which displays fields and panels according to the current model state.

Is this an intended feature or a bug?

**Comment by davidhemphill** [comment]
Hi there, it would help if you could post some code showing how to replicate the issue.

**Comment by Tarpsvo** [comment]
Hey. The issue is breaking for my package `nova-page-manager`, which manages two resources: `Page` and `Region`.

Each of the two resources have their own fixed fields (ie ID, name, slug etc) including a `template` field of string type and a `data` field of JSON type (more on these two in a second).

Now, the template column essentially references a user-created class that has a `fields()` function which returns an array of fields. These fields are appended to the fixed fields of the `Page` and `Region` resource and their data is stored in the `data` JSON column mentioned earlier.

So the UI flow (for a `Page`) goes like this:
- User goes to `Page` index view
- User presses `Create a Page` and is presented with ONLY the fixed fields (including `template`)
- User fills out the fixed fields and presses save
- Nova reloads the resource, notices that the `Page` has a template and now also returns the custom fields from the template
- User can now, after the initial save, see and edit the custom fields

The issue is that a plain (brand new) `Page` and `Region` resources do not have a template, therefore they do not know which fields to return. This sadly breaks the logic `nova-page-manager` relies on.

In the `nova-page-manager`'s code itself, the important bits to see are:

[Querying of the Template fields (TemplateResource.php#L66)](https://github.com/optimistdigital/nova-page-manager/blob/master/src/Nova/TemplateResource.php#L66)
and
[Appending the Template fields and panels to the Page resource (Page.php#L69)](https://github.com/optimistdigital/nova-page-manager/blob/master/src/Nova/Page.php#L69)

I'm horrible at explaining things, but I hope it made at least some sense and gave an overview of how and why 2.0.8's current approach stops the page manager package from functioning.

**Comment by davidhemphill** [comment]
Thanks for the explanation. I've updated the code to call the method on the existing resource instance, instead of using a new one. This will go out in the next update. 👍

**Comment by Tarpsvo** [comment]
Thank you!

**Comment by bolechen** [comment]
the `eminiarts/nova-tabs` package have "Trying to get property 'panel' of non-object" error when upgrade to nova 2.0.8

is the same issue? @davidhemphill 

ref https://github.com/eminiarts/nova-tabs/issues/43

**Comment by bolechen** [comment]
> the `eminiarts/nova-tabs` package have "Trying to get property 'panel' of non-object" error when upgrade to nova 2.0.8
> 
> is the same issue? @davidhemphill
> 
> ref [eminiarts/nova-tabs#43](https://github.com/eminiarts/nova-tabs/issues/43)

i  change line 518 in file `ResolvesFields.php` to 

```php
 if (isset($field->panel)) {
```

will temporary fix it

**Comment by cord** [comment]
same issue here with 2.0.9 and 

use TabsOnEdit; 

Trait on edit view (detail view is ok), however the quickfix causes vue error

**Comment by XternalSoft** [comment]
This issue is embarrassing :-(

**Comment by WebZenitude** [comment]
Same issue than you @bolechen with eminiarts/nova-tabs.
In my app, the proposed temporary fix in line 518 makes the list of concerned ressource appears empty when it is not.

**Comment by bkilshaw** [comment]
@davidhemphill Still experiencing this issue on v2.0.9 and eminiarts/nova-tabs eminiarts/nova-tabs#43 

Has the fix been pushed out yet?

**Comment by mcorkum** [comment]
@davidhemphill Also looking for a fix on v2.0.9

**Comment by davidhemphill** [comment]
I can't comment on any issues 3rd-party packages are having with the latest updates, but if there's something the package owner needs to enable their package to work again, they can send a PR to the repository and we'll take a look.

**Comment by bkilshaw** [comment]
Yeah just curious because up above you said that you pushed a fix, but we're still running into issues.

**Comment by Tarpsvo** [comment]
@davidhemphill 

Hey! When can we expect another release? I'm eagerly waiting for the fix to go live.
