### ISSUE TITLE
Cannot Edit / Create a Resource

### ISSUE THREAD

**Issue by zachgarcia1** [laravel/nova-issues#1720]
- Laravel Version: 5.8.27
- Nova Version: 2.0.8 / 2.0.9
- PHP Version: 7.3.6
- Operating System and Version: Bionic / 18.04
- Browser type and version: Chrome / latest
- Reproduction Repository: n/a

### Description:
I'm not sure whats going on but when i go to create a new resource or edit an existing resource 
non of my panels / inputs are showing, this happens on 2.0.8 and 2.0.9 but not 2.0.7 will revert back for now

### Steps To Reproduce:
bump to version 2.0.8 / 2.0.9 and edit / create a resource.

<img width="1464" alt="Screen Shot 2019-07-03 at 8 13 02 AM" src="https://user-images.githubusercontent.com/12938920/60603364-7b2aaf80-9d6a-11e9-898d-9a7905b60a09.png">

<img width="1463" alt="Screen Shot 2019-07-03 at 8 13 11 AM" src="https://user-images.githubusercontent.com/12938920/60603365-7b2aaf80-9d6a-11e9-8b72-8e8915ed5d8c.png">

however on 2.0.7 it seems to work fine.

<img width="1458" alt="Screen Shot 2019-07-03 at 8 15 46 AM" src="https://user-images.githubusercontent.com/12938920/60603540-d2c91b00-9d6a-11e9-9085-0b54cbaac4ed.png">
<img width="1462" alt="Screen Shot 2019-07-03 at 8 15 53 AM" src="https://user-images.githubusercontent.com/12938920/60603541-d2c91b00-9d6a-11e9-93b8-237d0af7ee32.png">

**Comment by davidhemphill** [comment]
As with all Nova releases, make sure you've updated your Nova assets to the latest version.

`php artisan nova:publish --force`

**Comment by Tarpsvo** [comment]
Did you force publish the assets after updating?

```
php artisan nova:publish --force
```

**Comment by zachgarcia1** [comment]
I must of missed that in the docs, thank you for your time.
