### ISSUE TITLE
resolveUsing() on ID field breaks detail view url

### ISSUE THREAD

**Issue by rieves** [laravel/nova-issues#1721]
- Laravel Version: v5.8.24
- Nova Version: v2.0.9
- PHP Version: 7.2.19

### Description:
I would like to prefix my ids of a resource with a # using the `resolveUsing` method. However, this is causing the view, edit and delete buttons for each resource on the resource index page to use the prefix too.

### Steps To Reproduce:
```
ID::make()
    ->resolveUsing(function ($id) {
        return '#' . $id;
    })
    ->sortable(),
```

Changes the detail view button uri to `/nova/resources/posts/%2313`

Thanks
Bradley

**Comment by davidhemphill** [comment]
`resolveUsing` is for resolving the value to be used by fields. You might be looking for the `displayUsing` method: https://nova.laravel.com/docs/2.0/resources/fields.html#field-resolution-formatting

**Comment by rieves** [comment]
Ok, thank you!

**Comment by rieves** [comment]
@davidhemphill I changed it to the `displayUsing` method and it's still doing the same thing.
