### ISSUE TITLE
Bug when Tool registers Resource and needs authorization

### ISSUE THREAD

**Issue by Jubeki** [laravel/nova-issues#1722]
- Laravel Version: v5.8.27
- Nova Version: v2.0.9
- PHP Version: 7.2.2 / 7.3.1
- Operating System and Version: Windows 10 / Ubuntu 18.04
- Browser type and version: Google Chrome v75.0.3770.100
- Reproduction Repository: https://github.com/Jubeki/NovaBugReport

### Description:
if a Tool (like [Vyuldashev NovaPermissionTool](https://github.com/vyuldashev/nova-permission)) is registered inside the NovaServiceProvider and needs some kind of authorization which a user doesn't have then there will a 404 error be shown when it will be accessed through a relationship.

### Steps To Reproduce:
1. Install a Tool which registers a resource (like [Vyuldashev NovaPermissionTool](https://github.com/vyuldashev/nova-permission))
2. Add an authorization inside the NovaServiceProvider for this tool
3. Add a relationship to the User-Resource for example which links to a resource of the tool.
4. Open the detail view of a user with an account which isn't authorized to view the resource of the tool

**Comment by jbrooksuk** [comment]
Thanks for the report and the reproduction repo, @Jubeki. I've confirmed this issue.

**Comment by crynobone** [comment]
We currently run <https://github.com/laravel/nova/blob/3.0/tests/Browser/ToolAuthorizationTest.php> and verify that the issue no longer exists in Laravel Nova 3.
