### ISSUE TITLE
Create Forms are no longer displaying fields.

### ISSUE THREAD

**Issue by mikebronner** [laravel/nova-issues#1723]
- Laravel Version: 5.8.27
- Nova Version: 2.0.9
- PHP Version: 7.2
- Operating System and Version: Ubuntu 18.04 (Homestead)
- Browser type and version: Safari 13.0
- Reproduction Repository: n/a

### Description:
After upgrading from 2.0.7 to 2.0.9 the create forms no longer display. Reverting back to 2.0.7 fixed the issue. It seems to have first started in 2.0.8 -- I tested each version from 2.0.7 to 2.0.9.

<img width="1234" alt="Screen Shot 2019-07-03 at 10 19 12 AM" src="https://user-images.githubusercontent.com/1791050/60611787-03658080-9d7c-11e9-863c-2ff3dd4391e5.png">

Here's the associated Nova resource file (this happens on all Nova resources, but this example correlates with the screenshot):
```php
<?php namespace App\Nova;

use Illuminate\Http\Request;
use Laravel\Nova\Fields\HasMany;
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Fields\MorphOne;
use Laravel\Nova\Fields\Number;
use Laravel\Nova\Fields\Text;

class Blog extends Resource
{
    public static $model = 'App\\Blog';
    public static $title = 'name';
    public static $search = [
        'id',
        'name',
    ];

    public function fields(Request $request) : array
    {
        return [
            ID::make()
                ->sortable(),
            Text::make('Name')
                ->sortable()
                ->rules('required', 'max:255'),
            Number::make("Default Months Shown")
                ->rules("required", "min:1")
                ->onlyOnForms(),
            Number::make("Default Posts Per Page")
                ->rules("required", "min:1", "max:50")
                ->onlyOnForms(),
            MorphOne::make("Page Settings", "pageSetting", "App\Nova\PageSetting"),
            MorphOne::make("Menu Settings", "menuSetting", "App\Nova\MenuSetting"),
            HasMany::make("Categories", "categories", "App\Nova\BlogCategory"),
            HasMany::make("Posts", "posts", "App\Nova\BlogPost"),
        ];
    }

    public function cards(Request $request) : array
    {
        return [];
    }

    public function filters(Request $request) : array
    {
        return [];
    }

    public function lenses(Request $request) : array
    {
        return [];
    }

    public function actions(Request $request) : array
    {
        return [];
    }
}
```

**Comment by acewebsa** [comment]
I can confirm that I have this issue also.

**Comment by davidhemphill** [comment]
When you update Nova, you need to make sure and run the following command to update its assets:

```bash
php artisan nova:publish
```

[Update Nova Documentation](https://nova.laravel.com/docs/2.0/installation.html#updating-nova)

**Comment by mikebronner** [comment]
@davidhemphill Thanks for the tip. :) Would you consider marking breaking changes with a minor version bump, instead of a patch bump? That would help indicate that we need to read the docs. :) Thanks!

**Comment by mikebronner** [comment]
Reporting back after publishing the assets: that fixed it. 👍

**Comment by bsormagec** [comment]
Its not fixed on my @dillingham can you give me another way :(

**Comment by christianmarth** [comment]
I still had this issue after running 

```php artisan nova:publish```

When I restarted my NGINX server the issue seems to be resolved

**Comment by bolechen** [comment]
Also need clear browser local cache.
