### ISSUE TITLE
Translations missing

### ISSUE THREAD

**Issue by FaridAghili** [laravel/nova-issues#1724]
- Laravel Version: 5.8.27
- Nova Version: 2.0.9
- PHP Version: 7.3.0
- Operating System and Version: Windows 10 1903
- Browser type and version: Google Chrome 75

In resource detail view:
```
:resource Details
```

In Action event:
```
Action
ID
Create
Update
Finished
Original
Changes
```

![image](https://user-images.githubusercontent.com/8607021/60615825-4f004480-9de5-11e9-9873-40db8d0220ed.png)

**Comment by davidhemphill** [comment]
All of these fields are translatable in user-land using Nova's translation capabilities. This is not a bug.

**Comment by FaridAghili** [comment]
@davidhemphill 
There is no keys available for them in `en.json` file deployed by Nova.
Should we guess the proper translation keys?
