### ISSUE TITLE
displayUsing() on ID field manipulates the show and edit urls and delete button id

### ISSUE THREAD

**Issue by rieves** [laravel/nova-issues#1725]
- Laravel Version: v5.8.24
- Nova Version: v2.0.9
- PHP Version: 7.2.19

### Description:
I would like to prefix my ids of a resource with a # using the `displayUsing` method. However, this is causing the view, edit and delete buttons for each resource on the resource index page to use the prefix too.

NOTE: Originally I was using the `resolveUsing()` method, but swapped over to the `displayUsing()` method as suggested here #1721, but the issue still persists.

### Steps To Reproduce:
```
ID::make()
    ->displayUsing(function ($id) {
        return '#' . $id;
    })
    ->sortable(),
```

Changes the detail view button uri to `/nova/resources/posts/%2313`

Thanks
Bradley

**Comment by davidhemphill** [comment]
The ID field doesn't support `displayUsing` in that way. You can get around this by doing something like this: 

```php
ID::make()->sortable()->onlyOnForms(),

Text::make('ID')->displayUsing(function ($value) {
    return sprintf("ID-%s", $value);
})->onlyOnIndex(),
```

**Comment by rieves** [comment]
Ok thanks @davidhemphill, I'll try that.

**Comment by kevariable** [comment]
@davidhemphill 
![image](https://user-images.githubusercontent.com/56016477/130243637-60b13083-db52-4d48-8be3-3279e727e9f3.png)

HI i need to help, how can i add some query ?foo=bar without displaying in id table?

![image](https://user-images.githubusercontent.com/56016477/130243768-6f1b67cc-b709-4bbb-8038-ad4891560a26.png)
