### ISSUE TITLE
isUpdateOrUpdateAttachedRequest returns false on update / Readonly field still store values in DB 

### ISSUE THREAD

**Issue by SebastianMueller87** [laravel/nova-issues#1727]
- Laravel Version: v5.8.27
- Nova Version: v2.0.9
- PHP Version: 7.3.6

**follows**
#1631
https://github.com/laravel/nova/pull/387

### Description:
Readonly fields still get stored when you use 
`return $request->isUpdateOrUpdateAttachedRequest();` within the closure.

Debugging shows that `$request->isUpdateOrUpdateAttachedRequest()` is false during the update request. (`XX?viaResource=&viaResourceId=&viaRelationship=`)

So it seems that `isUpdateOrUpdateAttachedRequest()` just returns the wrong value during the update request.

### Steps To Reproduce:

Remove `readonly` and `disable` attributes from the DOM element and update.

**still get stored:**
```
 Number::make('number', 'number')
     ->readonly(static function ($request) {
          return $request->isUpdateOrUpdateAttachedRequest();
     })
```

**does not get stored:**
```
 Number::make('number', 'number')
     ->readonly(static function ($request) {
          return true;
     })
```

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
