### ISSUE TITLE
Global Search '/' Key

### ISSUE THREAD

**Issue by kingga** [laravel/nova-issues#1729]
- Laravel Version: 5.8.27
- Nova Version: dev-master (^2.0@dev)
- PHP Version: 7.2.5
- Operating System and Version: Microsoft Windows 10 Pro (10.0.17763 Build 17763)
- Browser type and version: Google Chrome Version 75.0.3770.100 (Official Build) (64-bit)
- Reproduction Repository: private/no repo

### Description:
When using https://github.com/advoor/nova-editor-js `NovaEditorJs::make('Content')->hideFromIndex(),` if I try to write a URL of course using the '/' character:
![image](https://user-images.githubusercontent.com/20036047/60748661-504b9000-9fe4-11e9-86d1-246f8933ee79.png)
it jumps me to the 'press / to search' (global search) text box. I don't want to completely disable global search but if we could get an option to change the key bind or even just disable the key bind all together please.

I can see in your `GlobalSearch.vue` file you have the following method:
```js
handleKeydown(event) {
    if (this.isNotInputElement(event) && event.keyCode == 191) {
        event.preventDefault()
        event.stopPropagation()
        this.openSearch()
    }
}

// And label :placeholder="__('Press / to search')"
```

Maybe you could do something like:
```js
methods: {
    // ...
    handleKeydown(event) {
        // NOTE: keyCode is deprecated - https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode (191 becomes '/').
        // Perhaps even better, https://www.npmjs.com/package/keycode
        if (this.isNotInputElement(event) && this.openSearchKeyEnabled && event.key == this.openSearchKey) {
            event.preventDefault()
            event.stopPropagation()
            this.openSearch()
        }
    },
    // ...
},

computed: {
    // ...
    searchPlaceholder: {
        if (this.openSearchKeyEnabled) {
            // Unsure where '__' is coming from, does this need to be 'this.__'?
            return __(`Press ${this.openSearchKey} to search`);
        }
    },
    // ...
},
```

Or

```js
methods: {
    // ...
    isNotInputElement(event) {
        const tagName = event.target.tagName;
        const editable = event.target.isContentEditable;
        return Boolean(tagName !== 'INPUT' && tagName !== 'TEXTAREA' && !editable);
    },
    // ... + code snippet from above.
},
```

### Steps To Reproduce:
1. Install `advoor/nova-editor-js`
2. Type '/' into the editor

**Comment by davidhemphill** [comment]
This is not a bug in Nova. You need to create an issue on the package's repository and let them know to cancel the event from bubbling up.
