### ISSUE TITLE
Downloading only one file instead of downloading all selected

### ISSUE THREAD

**Issue by PrafullaKumarSahu** [laravel/nova-issues#1731]
- Laravel Version: 5.8.27
- Nova Version: 2.0.0
- PHP Version: 7.3.5
- Operating System and Version: Windows 10 pro
- Browser type and version: Chrome 75.0

### Description:
I have one resource having links of downloadable files, now with action, I am just downloading the files, now if I am selecting all/multiple files and running the action, it is down loading only one.
### Steps To Reproduce:

Action handle function code

```
  public function handle(ActionFields $fields, Collection $models)
    {
        foreach ( $models as $model ) {
            return Action::download($model->document_link, $model->document_title);
        }
    }
```
if you need more information, please let me know, also I would like to know if I can change the confirm action message from "Are you sure you want to run this action?" to "Are you sure, you want to download all the selected files for multiple selections and for single, just do not want to show this dialog, how it is possible?"

**Comment by Dontorpedo** [comment]
its not the best way to download multiple files like this, better solution is to use something like Zipper etc.

**Comment by PrafullaKumarSahu** [comment]
@Dontorpedo is there nothing like queuing? will be good to download a single file using zipper, will it be inefficient, I want both single and multiple based on user's preference?

**Comment by davidhemphill** [comment]
You're returning on the first iteration of the models. If you want multiple downloads you'll have to somehow compile it yourself and send to the user after you iterate through them.

This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).
