### ISSUE TITLE
Queued Action Timeout gets ignored is set using `$timeout` property in Action class

### ISSUE THREAD

**Issue by alberto-bottarini** [laravel/nova-issues#1732]
- Laravel Version: I guess all
- Nova Version: I guess all
- PHP Version: I guess all

### Description:

Queued action should reproduce all laravel jobs features including timeout. If I set `$timeout` property on my job it gets ignored because `CallQueuedAction` ignore it. I think it should be managed as `failed` method that wraps action `failed` method.

### Steps To Reproduce:
- create a new Action
- set `sleep(61)` as handle method body
- create a `timeout` property with 120 as value

This action will be killed because 120 gets ignored and 60 is used as timeout.

**Comment by jbrooksuk** [comment]
Can you confirm that you're not seeing your web server timing out?

**Comment by alberto-bottarini** [comment]
Why closed?

**Comment by fedeisas** [comment]
@alberto-bottarini any luck fixing this? Thanks.

**Comment by davi5e** [comment]
Not only `timeout`, but `retries`, `tags()` and I did not try to set up a middleware, but would not be surprised if it wouldn't work too...

Does Nova uses a different queue class for its actions? If so, why?

**Comment by oscarpan** [comment]
@jbrooksuk I'm also running into this issue

**Comment by Radiergummi** [comment]
Huh, interesting this got no responses. I have the same problem, `$tries` and `$timeout` get ignored, completely shattering my customer data import action (which is neither happy to get interrupted nor to be retried on partially inserted records)...

**Comment by crynobone** [comment]
Submit a new bug report with full reproducing code if you still have this issue.
