### ISSUE TITLE
Global search shortcuts : Disable on contentEditable

### ISSUE THREAD

**Issue by MarceauKa** [laravel/nova-issues#1733]
- Laravel Version: 5.8.27
- Nova Version: 2.0.9
- PHP Version: 7.2

### Description:

Hi, some of custom nova fields don't use input or textarea but tags with `contenteditable="true"`. Unfortunatly, the `GlobalSearch` component binds `?` and `/` and don't focus search when typing in an input or in a textarea but focus when typing in a  `contenteditable`.

This behavior is in the `isNotInputElement` method on `GlobalSearch.vue` at line 121 (2.0.9):
```js
isNotInputElement(event) {
    const tagName = event.target.tagName
    return Boolean(tagName !== 'INPUT' && tagName !== 'TEXTAREA')
},
```

**Comment by MarceauKa** [comment]
Issue opened in a custom field: https://github.com/advoor/nova-editor-js/issues/18

**Comment by davidhemphill** [comment]
The custom field needs to capture the input and change events and prevent them from bubbling up. This is not a Nova issue, but something that has to be handled on the custom field's end.
