### ISSUE TITLE
Edit -> save or cancel falls to 404 with generated link `/nova-api/undefined/undefined`

### ISSUE THREAD

**Issue by h-zone** [laravel/nova-issues#1734]
- Laravel Version: 5.8.27
- Nova Version: 2.0.9
- PHP Version: 7.3.6
- Operating System and Version: Debian 9.9
- Browser type and version: Firefox 67.0.4

### Description:
When editing any object from detail page, `cancel` link and `update` button (which returns to detail) will falls to 404 with generated link `/nova-api/undefined/undefined`, `/nova-api/undefined/card` etc
Editing from the index works fine.

Catching your questions: Primary Key is 'id' and ID is integer/bigInteger.

### Steps To Reproduce:
Clean install works fine

May be somebody solve this issue?
(Hard to work to create reproduceable situation)

**Comment by h-zone** [comment]
I know, its my fault, but cant find where. My relations and output in nova very complex.
Looking for someone who solved this problem

**Comment by h-zone** [comment]
request log

![2019-07-09_17-50-03](https://user-images.githubusercontent.com/1150044/60899098-8ef67a00-a272-11e9-9231-63b567f8023c.png)

there is response of post request

![2019-07-09_17-51-07](https://user-images.githubusercontent.com/1150044/60899099-8ef67a00-a272-11e9-989c-c59225fca678.png)

**Comment by davidhemphill** [comment]
It looks like you might have overridden `redirectOnCreate` or something similar.

This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).

**Comment by h-zone** [comment]
after ten hours i found problem - nova conflicting with my my spa application on
1. routes (excluding nova routes by `catchall` not helps me
2. middleeware (different logics)

solved by carry out the nova on different domain (differences only at `.env` file->`app_url`
works fine

**Comment by h-zone** [comment]
bug appear again.
when i change `resources/views/vendor/nova/layout.blade.php` and partials
helps `*:clean` commands + `composer autoload-dump`
