### ISSUE TITLE
faulty badge import in BadgeField.vue

### ISSUE THREAD

**Issue by Anticom** [laravel/nova-issues#1736]
- Laravel Version: 5.8.27
- Nova Version: 2.0.6
- PHP Version: 7.3.6
- Operating System and Version: Linux 4.15.0-54-generic #58~16.04.1-Ubuntu SMP Mon Jun 24 13:21:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Browser type and version: 74.0.3729.169 (Offizieller Build) Built on Ubuntu , running on Ubuntu 16.04 (64-Bit)
- Reproduction Repository: ~~https://github.com/###/###~~

### Description:
When trying to put vue into dev mode according to [this](https://github.com/laravel/nova-issues/issues/33#issuecomment-415506864) description, two errors get thrown in
 * `resources/js/components/Detail/BadgeField.vue`
 * `resources/js/components/Index/BadgeField.vue`

Since `resources/js/components/Bade.vue` is imported via `../badge` and not `../Badge`.
On Linux the imports are not case-insensitive. Fixing the imports also fixed `npm run dev`.

### Steps To Reproduce:
See [this](https://github.com/laravel/nova-issues/issues/33#issuecomment-415506864) description.

**Comment by davidhemphill** [comment]
This has already been fixed in a later version. https://github.com/laravel/nova/commit/97a0983f54f9f811305bb6694614e3abc28e0bb0

**Comment by Anticom** [comment]
ty
