### ISSUE TITLE
Trying to get property 'panel' of non-object

### ISSUE THREAD

**Issue by phuclh** [laravel/nova-issues#1737]
- Laravel Version: 5.8
- Nova Version: 2.0.9
- PHP Version: 7.3
- Operating System and Version: MacOS Majave
- Browser type and version: 10.14.5

### Description:
When I update to Nova 2.0.9, I got this error when entering a creating page.
```
file: "/nova/src/ResolvesFields.php"
line: 518
message: "Trying to get property 'panel' of non-object"
```

**Comment by davidhemphill** [comment]
Republish Nova's assets. https://nova.laravel.com/docs/2.0/installation.html#updating-nova-s-assets

**Comment by gonzunigad** [comment]
Republishing Nova's Assets did not work for me.

**Comment by wize-wiz** [comment]
Same here after update 2.0.9. The problem with my Resource was using the trait `TabsOnEdit` from 
[eminiarts/nova-tabs](https://github.com/eminiarts/nova-tabs). Everything is as expected when removing the trait.
