### ISSUE TITLE
Several computed fields inside ACTION overwrites each other

### ISSUE THREAD

**Issue by xUJYx** [laravel/nova-issues#1739]
- Laravel Version: 5.8.21
- Nova Version: 2.0.3
- PHP Version: 7.3.5
- Operating System and Version: CentOS 6.8
- Browser type and version: Crome 64.0.3282.186

### Description:
When I create Action and use Several different fields with computed data, than running this action - only last computed field and it`s data are transferred inside handle method...

### Steps To Reproduce:
Create any action and add Several computed fields. Than run your action. 
![computed_field_error](https://user-images.githubusercontent.com/25051595/60984731-dea57600-a344-11e9-836b-20440362e172.jpg)

**Comment by davidhemphill** [comment]
Computed fields are for displaying extra information on the index view, not for use in actions.
