### ISSUE TITLE
Changing route configuration

### ISSUE THREAD

**Issue by fletch3555** [laravel/nova-issues#174]
I'm looking to host my admin panel on a subdomain.  Is there a way to change the Nova route configuration so it'll use my subdomain?  I know I could wrap the call to `Nova::routes()......register()` in a `Route::group()` defining my subdomain, but that doesn't apply to `nova-api` routes.

Any thoughts?  Anyone else get this working?

**Comment by fletch3555** [comment]
Any update on this? It's been over 3 weeks now.  I don't expect it to work tomorrow, but a note saying it's in progress or "planned" would be nice.

**Comment by davidhemphill** [comment]
Can you try setting `nova.domain` in your Nova config file and see if that gets you what you want?

**Comment by fletch3555** [comment]
Is that a newer config option? I don't remember seeing anything like that in the version I was using when originally reporting this (1.0.3 I think...?)

I'll give it a shot later when I get home.

**Comment by dwyer14** [comment]
@davidhemphill that seemed to work as expected for me, thanks! @fletch3555 - I added `domain` above the `path` option, in config/nova.php— eg:
```
'domain' => 'admin.my-application.test',
'path' => '/',
```
For handling local/dev vs. production URL, based on my `.env`, I would update like this:
```
'domain' => 'admin.' . env('APP_URL'),
'path' => '/',
```

**Comment by davidhemphill** [comment]
@dwyer14 Nice!

**Comment by salvisb** [comment]
Hi,
I'm keep getting this error: "Missing required parameters for [Route: nova.login] [URI: login]".

I've set domain parameter in config/nova.php to {tenant}.my-domain.local and added entry to vhosts file. I'm running Laravel using php artisan serve.

Any help would be appreciated.

**Comment by Brotzka** [comment]
Just in case someone faces the same problem like @salvisb :

You have to use the ``url`` option instead of the ``domain`` option in Novas config file.

Example:

- for multi-tenancy`'url' => '{client}.' . env('APP_DOMAIN', '/'),` 
- for a specific subdomain: `'url' => 'admin.' . env('APP_DOMAIN', '/')`,

Note that I've added the `APP_DOMAIN` key to my env-file and my app.php-config-file because you need the domainname without http/https.
