### ISSUE TITLE
419 error when POSTing to /nova/login

### ISSUE THREAD

**Issue by wwwroth** [laravel/nova-issues#1740]
Getting a 419 err when posting to the login endpoint after deploying to my staging server on Azure..

- Laravel Version: 5.8.28
- Nova Version: 2.0.9
- PHP Version: 7.2
- Browser type and version: Chrome 75

* Works locally, once I deploy and composer install I can see the /nova login page but when I submit the login the POST req 419's.

<img width="1440" alt="Screen Shot 2019-07-10 at 4 33 34 PM" src="https://user-images.githubusercontent.com/3310210/61003036-efe48780-a330-11e9-9763-01c780dfd4aa.png">

**Comment by davidhemphill** [comment]
Sorry, but we are unable to debug your issue without a reproducible code example. Once you provide that we feel free to open a new issue.

**Comment by BenySLO** [comment]
check your .env file, i had the same problem

**Comment by wwwroth** [comment]
@BenySLO what key/value pair was the issue?

**Comment by BenySLO** [comment]
@wwwroth dont remember what it was, but im pretty sure that I've had a syntax error, I've had multiple instances and all worked except for this one, with the error 419, could not find the error so i copied the .env from my other instance and ran
 ```
php artisan config:clear
php artisan cache:clear
```

atleast worked for me, I must add that the front end without "**/nova**" in url worked fine

**Comment by adrian-schnell** [comment]
@wwwroth did you fix the issue inside your project?
I'm having the same issue - but my .env seems to be fine

**Comment by Essam34ML** [comment]
Did anyone find a solution?

**Comment by stickeegreg** [comment]
One thing to check is that your sessions are working properly

- Make sure the session directory (usually storage/framework/sessions) is writable by the app
- Check if you have config('session.secure') == true then you are trying over HTTPS

**Comment by provydon** [comment]
It's probably from your config/session.php file

make sure u set the correct domain

like this

on local
'domain' => env('SESSION_DOMAIN', null),

for production
'domain' => env('SESSION_DOMAIN', "yourdomain.com"),

**Comment by MladenJanjetovic** [comment]
It was up to SSL in my case. In local development I wasn't using SSL URL so adding this line to my local .env file made it work:

`SESSION_SECURE_COOKIE=false`

**Comment by PeteJStewart** [comment]
I found that this issue was happening for us on our local environment when accessing via php artisan serve.
It was due to going to http://127.0.0.1:8000 instead of http://localhost:8000

As @provydon pointed out above, you have to match the domain stated in you .env file.

**Comment by Muetze42** [comment]
Is there a solution for this in the meantime? The problem is still partly local and in production.

**Comment by Muetze42** [comment]
`SESSION_DRIVER=file` works and `SESSION_DRIVER=database` work not.

**Comment by haythembenkhlifa** [comment]
In my case, the SESSION_DOMAIN was different than APP_URL I make them the same, and the issue is fixed.
I hope my comment can help.
