### ISSUE TITLE
Nova not render edit/update view page

### ISSUE THREAD

**Issue by iamoat** [laravel/nova-issues#1741]
- Laravel Version: 5.8.26 - 5.8.28
- Nova Version: 2.0.7 - 2.0.9
- PHP Version: 7.2
- Operating System and Version: OSx and Ubuntu
- Browser type and version: Chrome

### Description:
After upgraded to latest Laravel and Nova, I performed necessary commands to update as follows

![image](https://user-images.githubusercontent.com/1286835/61035034-9a6faf80-a3f0-11e9-9f7e-e41881ba8a70.png)

After re-login, all index and detail views work just fine but create / update views. 

![image](https://user-images.githubusercontent.com/1286835/61035143-cf7c0200-a3f0-11e9-8481-9aef3b857798.png)

It just rendered empty area. I couldn't find any error message both in console and logs.

**Comment by davidhemphill** [comment]
You did not publish new CSS and JS or a 3rd-party package isn't compatible with the latest version.

**Comment by iamoat** [comment]
> You did not publish new CSS and JS or a 3rd-party package isn't compatible with the latest version.

Thank you. It was really a 3rd-party that caused the problem. Upgraded the 3rd-party package, in this case "BreadCrumb" and ran "npm run dev" on both nova and the 3rd-party package fixed the problem.

**Comment by CyrilBlankaert** [comment]
I can't resolve this problem too ! 

In my console, i have these messages : 

- edit?viaResource=&viaResourceId=&viaRelationship=:220 GET http://project.dv/nova-api/scripts/analytics net::ERR_ABORTED 500 (Internal Server Error)

- http://project.dv/nova-api/styles/analytics net::ERR_ABORTED 500 (Internal Server Error)

**Comment by CyrilBlankaert** [comment]
I found the solution 👍 

ADD in composer.json :

"scripts": {
    "post-update-cmd": [
        "@php artisan nova:publish"
    ]
}
