### ISSUE TITLE
Localize displayed timezone next to Date field

### ISSUE THREAD

**Issue by nysso** [laravel/nova-issues#1742]
- Laravel Version: 5.8.28
- Nova Version: 2.0.6
- PHP Version: 7.3.1
- Operating System and Version: Windows 10 build 1903 version 18362.175
- Browser type and version: Google Chrome 75.0.3770.100 64bits

### Description:
I wasn't able to find how to translate the displayed {{timezone}} next to Date field (the one in the attached image)
Or if there is a possibility to hide it.
timezone in image should be (Pacifique / Marquises)
I tried adding it to fr.json, but nothing.

### Steps To Reproduce:
- Set app locale to french
- Add a date field to a form
- Displayed timezone (next to date field) is not translated with the rest of the app.

![image](https://user-images.githubusercontent.com/13627474/61042339-eaf4f780-a373-11e9-94ab-d709be2b06f6.png)

**Comment by numyss** [comment]
I'm having the same problem
any solutions ?

**Comment by aezur** [comment]
Same here. Also wondering how to translate the 'name' field in the nova config, since config's are loaded before the translator is.

**Comment by jbrooksuk** [comment]
You can override how Nova resolves the timezone by adding this to the `boot` method of your `NovaServiceProvider`:

```php
Nova::userTimezone(function (Request $request) {
        return __(config('app.timezone'));
});
```

Now you should be able to translate the timezone strings.
