### ISSUE TITLE
Limit / Expand Panel Feature Proposal

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#1743]
![subtle](https://user-images.githubusercontent.com/29180903/61102709-08da5f00-a43d-11e9-8899-cd20781a55e2.png)

Beneficial for panels with a large amount of items: proposing a `->limit(5)` method

```php

(new Panel('Images', [
    Image::make('Icon'),
    Image::make('Image'),
    Image::make('Banner'),
    Image::make('Twitter'),
    // 5 more 
]))->limit(5),
```

Wanted feedback before spending time making a PR
It seems like maybe it would be a computed property tucked in the panel mixin
And not sure if you'd want that on forms also
v-for field in fieldsLimited and panel.fields in forms maybe

**Comment by jbrooksuk** [comment]
I think this would be a nice addition to panels, feel free to make a PR and I'll review it.
