### ISSUE TITLE
No failure messages when edit/update screen stops working

### ISSUE THREAD

**Issue by drsdre** [laravel/nova-issues#1744]
- Laravel Version: 2.0.8
- Nova Version: 2.0.8
- PHP Version: 7.2.13
- Operating System and Version: OSX
- Browser type and version: Chrome 75.0.3770.100

### Description:
After Laravel Nova got upgraded from 2.0.6 to 2.0.8/2.0.9, the create/edit screen failed without any message in the front end or Telescope.

![Schermafbeelding-2019-07-12-om-15 41 07](https://user-images.githubusercontent.com/809827/61133220-47aff980-a4bd-11e9-8327-c677217259a3.jpg)

This Nova setup has a lot of plugins installed to make it work. It takes a lot of time to redo the plugin installation to find out which one fails. Please add JS error logs in critical places to have a starting point to debug issues.

**Comment by sabid** [comment]
[Vue DevTools](https://nova.laravel.com/docs/2.0/customization/frontend.html#vue-devtools)

By default, Nova's JavaScript is compiled for production. As such, you will not be able to access the Vue DevTools out of the box without compiling Nova's JavaScript for development. To accomplish this, you may use the following terminal commands from the root of your Nova project:

`cd ./vendor/laravel/nova`
`mv webpack.mix.js.dist webpack.mix.js`
`npm install`
`npm run dev`
`rm -rf node_modules`
`cd -`
`php artisan nova:publish`

[Updating Nova](https://nova.laravel.com/docs/2.0/installation.html#updating-nova)

`composer update`

[Updating Nova's assets](https://nova.laravel.com/docs/2.0/installation.html#updating-nova-s-assets)

`php artisan nova:publish`
`php artisan view:clear`

The nova:publish command will re-publish Nova's public assets, configuration, views, and language files. This command will not overwrite any existing configuration, views, or language files. If you would like the command to overwrite existing files, you may use the --force flag when executing the command:

`php artisan nova:publish --force`

**Comment by ElectroBuddha** [comment]
I'm having the same issue, have you find the solution?

**Comment by francoisauclair911** [comment]
Thank you guys for your help
`php artisan nova:publish ` solved it too

**Comment by davidhemphill** [comment]
Update Nova's assets per the documentation: https://nova.laravel.com/docs/2.0/installation.html#updating-nova-s-assets
