### ISSUE TITLE
Theme Documentation Is Incorrect?

### ISSUE THREAD

**Issue by loonpwn** [laravel/nova-issues#1746]
- Laravel Version: 5.8.28
- Nova Version: 2.0.9

### Description:

The nova documentation states that the `php artisan nova:theme` will generate a webpack.mix.js file for you. https://nova.laravel.com/docs/2.0/customization/themes.html#compiling-assets

Running the command does not produce that file and looking through the code around the `ThemeCommand` I can't see anything that would.

Ideally the behavior of this command would operate in a similar way to the `ToolCommand` where it will offer to compile the assets and generate the relevant files and amend your package.json.

**Comment by jbrooksuk** [comment]
I've labelled this as documentation, but I agree, the command should work the same. Leave it with me, I'll get a PR sent upstream to do this.

**Comment by jbrooksuk** [comment]
Done.

**Comment by loonpwn** [comment]
Thanks James!

**Comment by jbrooksuk** [comment]
We've decided to update the docs rather than modify the theme command. PR pending.

**Comment by ephraimlambarte** [comment]
How can we compile the theme then?
