### ISSUE TITLE
Gravatar in searchable fields

### ISSUE THREAD

**Issue by artisaninweb** [laravel/nova-issues#1747]
If i'm using a searchable on a 'user' field, the gravatar image appears.
I want to be able to disable the gravatar so it will not be shown.

`BelongsTo::make('Gebruiker', 'user', User::class)->searchable(),`

![image](https://user-images.githubusercontent.com/6005094/61199562-b7e99580-a6de-11e9-82c2-319d1da4ca3d.png)

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).

**Comment by sanderbaas** [comment]
@notfalsedev Did you ever find a solution for this problem?

**Comment by sanderbaas** [comment]
Found it myself: add a `resolveAvatarUrl` to the target resource of the BelongsTo relation that returns `null`

```
public function resolveAvatarUrl(NovaRequest $request)
{
    return null;
}
```
