### ISSUE TITLE
addScriptsToNpmPackage() fails if there is no package.json in root of the project

### ISSUE THREAD

**Issue by Gavrisimo** [laravel/nova-issues#1748]
- Laravel Version: v5.8.28
- Nova Version: v2.0.9
- PHP Version: 7.1.30

### Description:

When running `php artisan nova:resource-tool acme/stripe-inspector` in a Laravel project that does not have `package.json` file in the root directory - the script fails:

```
→ php artisan nova:resource-tool acme/stripe-inspector

   ErrorException  : file_get_contents(/Users/geeman/work/test/package.json): failed to open stream: No such file or directory

  at /Users/geeman/work/test/vendor/laravel/nova/src/Console/ResourceToolCommand.php:153
    149|      * @return void
    150|      */
    151|     protected function addScriptsToNpmPackage()
    152|     {
  > 153|         $package = json_decode(file_get_contents(base_path('package.json')), true);
    154|
    155|         $package['scripts']['build-'.$this->toolName()] = 'cd '.$this->relativeToolPath().' && npm run dev';
    156|         $package['scripts']['build-'.$this->toolName().'-prod'] = 'cd '.$this->relativeToolPath().' && npm run prod';
    157|

  Exception trace:

  1   file_get_contents("/Users/geeman/work/test/package.json")
      /Users/geeman/work/test/vendor/laravel/nova/src/Console/ResourceToolCommand.php:153

  2   Laravel\Nova\Console\ResourceToolCommand::addScriptsToNpmPackage()
      /Users/geeman/work/test/vendor/laravel/nova/src/Console/ResourceToolCommand.php:77

  Please use the argument -v to see more details.
```

### Steps To Reproduce:

1. install Laravel
2. install Nova
3. get rid of package.json
4. run `php artisan nova:resource-tool acme/stripe-inspector`

**Comment by Gavrisimo** [comment]
By looking at the source code I see that the idea is to run `npm run dev|prod` from root and to automatically run same command for each tool I have defined, which I totally agree is the best thing to do with tools.

I'd like to propose to just handle this error and maybe show some message back to the user like:

> Would you like to add package.json so you can update your tool(s) by `npm run dev|prod` from the root of the project?

The reason we do not have a `package.json` in the root is because we do not have any frontend stuff in this project, it's an API project and we are now adding admin panel via Laravel Nova.

I'll add some minimal `package.json` file just so updating tools would work as expected, but it would still be cool to handle this kinda error.

**Comment by jbrooksuk** [comment]
I agree that we could do better here, even if we just notify you that you need a `package.json` file rather than creating one.
