### ISSUE TITLE
Detail icon in lenses

### ISSUE THREAD

**Issue by alberto-bottarini** [laravel/nova-issues#1749]
There are some other issues about this topic but I think it need some clarification.

Initially Lenses represented a "custom query" that returned a list of resources with some custom calculated fields. But some is use cases, we need to show some "custom views" that are not strictly referred to a resource list. For example I use a lot of lenses to show data aggregations by particular columns using groupBy query.

What about disabling "detail icon" when id is not included?

**Comment by davidhemphill** [comment]
This is out of the scope of what we designed Lenses to be. They are primarily for showing prefiltered resource listings and there are no plans to change that.

**Comment by alberto-bottarini** [comment]
So why update/delete icons can be disabled?
