### ISSUE TITLE
Date filter

### ISSUE THREAD

**Issue by lucasromanojf** [laravel/nova-issues#175]
Would be great if we could have other filter types than selects. For example, a date filter, so we can filter by intervals.

**Comment by squierll** [comment]
+ 1

**Comment by lucasromanojf** [comment]
Another feature I think is very important for filter is default value. Is there a way of doing this already?

**Comment by mortenscheel** [comment]
This is feature is absolutely crucial in just about every use case I can think of.
Wouldn't it make sense to allow the Filter class to define which Field type should be used? For some filters, a simple checkbox would be sufficient. For others, a radio button group.

**Comment by v1nk0** [comment]
+1

**Comment by disitec** [comment]
+1

**Comment by hubertnnn** [comment]
+1

**Comment by rodwin** [comment]
+1
Please have this feature

**Comment by taylorotwell** [comment]
This repository is for tracking bugs. Feature requests may be emailed to Nova customer support.

**Comment by disitec** [comment]
Just published this package https://github.com/64robots/nova-date-filter

@davidhemphill @taylorotwell feel free to merge it to core if it fits.
