### ISSUE TITLE
Search Functionality In Lenses

### ISSUE THREAD

**Issue by MannikJ** [laravel/nova-issues#1750]
Is there no possibility to add searching capabilities to nova lenses? I am surprised I couldn't even even find a filter type that allows to enter a search text instead of predefined options.

**Comment by davidhemphill** [comment]
Lenses support filters but do not support searching as the user defines the query ahead of time.

**Comment by MannikJ** [comment]
@davidhemphill I don't understand why that should suit for keeping you away from adding some kind of designated way to hook in search logic.
Of course in most cases you will need to implement the query yourself, but what's wrong with that?

**Comment by tainmar** [comment]
I do not get it either @MannikJ 😒 
Did you find a workaround or a package that does the trick ?
Thanks

**Comment by tylernathanreed** [comment]
I'm not certain as to why this was closed. Shouldn't this have been labelled as a feature request? I'd like to see this functionality as well, and I am unable to find a suitable alternative.

**Comment by tylernathanreed** [comment]
@tainmar I just created a package for my project: [reedware/nova-text-filter](https://github.com/tylernathanreed/nova-text-filter), and this appears to do everything we'd like it to.

This was so simple to add, I'm kind of surprised that this didn't come out of the box with Nova.

**Comment by jbrooksuk** [comment]
Feel free to PR this into the core of Nova :)

**Comment by skoyah** [comment]
For anyone that might be interesting in share your thoughts: https://github.com/laravel/nova/pull/706
