### ISSUE TITLE
Forms not shown on 2.0.9 

### ISSUE THREAD

**Issue by nabeel-alalmai** [laravel/nova-issues#1751]
- Laravel Version: 5.8.28
- Nova Version: 2.0.9
- PHP Version: 7.2
- Operating System and Version: Ubuntu 18.4 
- Browser type and version: Google Chrome

### Description:
No from shown when I click on create [resource]

This issue happened after I run composer update on my server. it updated nova from 2.0.6 to 2.0.9 and updated laravel from 5.8.23 to 5.8.28

The form for update and create is not showing. sometimes it shows the three dots (spinner) then show nothing as per the below screenshot 

![Screenshot_1](https://user-images.githubusercontent.com/6444894/61308348-c2984d80-a7f8-11e9-9709-83c7a924cd51.png)

### Steps To Reproduce:
run composer update

**Comment by ElectroBuddha** [comment]
Check this issue https://github.com/laravel/nova-issues/issues/1744

**Comment by davidhemphill** [comment]
Update Nova's assets per the documentation: https://nova.laravel.com/docs/2.0/installation.html#updating-nova-s-assets
