### ISSUE TITLE
Hide soft delete checkbox in BelongsTo

### ISSUE THREAD

**Issue by gkermer** [laravel/nova-issues#1753]
Hello,

when soft delete for a BelongsTo field is active, the "With Trashed" checkbox is displayed.

![grafik](https://user-images.githubusercontent.com/8224376/61360148-1ac56300-a87e-11e9-895e-5fde4e236a54.png)

Even if soft delete for the Model is active, I don't want to see this checkbox. Maybe you can add this function:
`BelongsTo::make('Organization')->hideSoftDeleteCheckbox()`

Thank you

**Comment by ArroWsGM** [comment]
I think is a must-have feature, but it should be hidden by default:

`BelongsTo::make('Organization')->showSoftDeleteCheckbox()`
