### ISSUE TITLE
Laravel Nova can't live/work with JWT Auth.

### ISSUE THREAD

**Issue by colemvn** [laravel/nova-issues#1754]
- Laravel Version: 5.8
- Nova Version: 2.0
- PHP Version: 7.1.3
- Operating System and Version: OSX Mojave

### Description:
I am re-opening a long going issue with Laravel Nova and JWT Authentification. I have not found any **logical** way or drafts explaining the possibility of using JWT(or multiple guards) with Laravel Nova.

I found 2 issues, #43  and #341 which have totally died and left untouched. 

Has anyone, been able to make JWT Auth. work with Laravel Nova peacefully.

**Comment by h-zone** [comment]
confirm.
im using https://github.com/cretueusebiu/laravel-vue-spa setup
conflicting with routes (`catchall?` not helps), middleware and some configuration values.
helps:
moving nova to separate domain, if-else as routes and config files (not ideal, but works ...and no hardcoding)

**Comment by colemvn** [comment]
> confirm.
> im using https://github.com/cretueusebiu/laravel-vue-spa setup
> conflicting with routes (`catchall?` not helps), middleware and some configuration values.
> helps:
> moving nova to separate domain, if-else at routes and config files (not ideal, but works ...and no hardcoding)

Are you using it because you weren't able to make Nova live with the "basic/default" JWT configuration? I just don't want to jump to a conclusion this fast.

Thanks for the tip, i'll look into it. It looks interesting. Basically is an "independant" login

**Comment by h-zone** [comment]
> Are you using it because you weren't able to make Nova live with the "basic/default" JWT configuration? I just don't want to jump to a conclusion this fast.
> 
> Thanks for the tip, i'll look into it. It looks interesting. Basically is an "independant" login

No, if U separate routes and configuration with if-else, - it works.

for the first step - separate `config/auth.php` content. its different for nova and jwt
for second step - separate `routes/` [`api.php`|`web.php`]

therefore you will be get 404 for editing resources at nova with update button

**Comment by h-zone** [comment]
at the Nova some moments is hardcoded.
cool programmers, блин

**Comment by colemvn** [comment]
> at the Nova some moments is hardcoded.
> cool programmers, блин

I don't quite understand what you mean.

You separated the auth.php content. I guess you created 2 differents guards, one for Nova and one for the client/user.

Then you wrote the api routes in the api, but finish with a 404?

**Comment by h-zone** [comment]
re-read carefully
https://github.com/laravel/nova-issues/issues/1754#issuecomment-512344935

**Comment by colemvn** [comment]
Seems like Nova's support has been lacking a bit. Reddit is the place to go for anyone with issues I guess.

We figured it out here; changed the (nova_guard) variable in the .env file to 'web' since JWT asks you to change the default one to 'api' which messes up the nova configuration.

https://www.reddit.com/r/laravel/comments/cee9oa/nova_jwt_auth/

**Comment by 949mac** [comment]
Just confirming with jwt-auth 1.x, following https://jwt-auth.readthedocs.io/en/develop/quick-start/

If you add `NOVA_GUARD=web` to your .env and flush your env/config cache, Nova authentication works and so does api auth via JWT. Thank you!
