### ISSUE TITLE
Nova v2.0.9: not picking up model primary key properly?

### ISSUE THREAD

**Issue by zack6849** [laravel/nova-issues#1756]
- Laravel Version: 5.8.29
- Nova Version: 2.0.9
- PHP Version: 7.3.61
- Operating System and Version: Homestead Vagrant Box (Ubuntu 18.04.2 LTS)
- Browser type and version: Mozilla Firefox v69.0b4 

### Description:

Nova seems to not pick up primary keys from my model and tries to use "id" specifically, for no clear reason, at least for an ID Field.

I've seen other issues (#348, #38 etc) that mention issues with primary keys, and also saw comments saying that ID::make respects the user's preference, but either i'm missing something, or that's no longer the case.

With the following models:
https://gist.github.com/zack6849/0ca2b7f4de12e8233a734bf781796e99

Loading the "invoices" tab shows me this, and if you try clicking anything it 404s, or try sorting by the ID you get the following error:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'order clause' (SQL: select * from `invoice_header` order by `id` asc limit 26 offset 0)

I noticed the URL generated when I click the sorting, Is the following:

http://homestead.local/nova-api/invoices?search=&filters=W10%3D&orderBy=id&orderByDirection=asc&trashed=&page=1&viaResource=&viaResourceId=&viaRelationship=&relationshipType=

It's trying to order by ID, and i'm still not sure why, if you change that to the primary key of the model (id_header_invoice) it works

This seems like a front-end and back-end mismatch sorta thing, I can still make my nova models work if i dont show the ID in id::make, but that's not ideal.

### Steps To Reproduce:

Create the models from the gist link, load the resource for invoices, try and sort by an id.

**Comment by zack6849** [comment]
Note: i am aware per the docs that I can just use the following: 

```
            ID::make('ID', 'id_invoice_header')->sortable(),
```

However it looks like a bug to me that ID::make isn't picking up on my model's primary key

**Comment by davidhemphill** [comment]
This is why there's an option for a second argument, so you can pass the column name if it differs from the one Nova will guess.

**Comment by zack6849** [comment]
@davidhemphill it's not a bug that id::make is making a blind assumption at the id column and doesn't even attempt to use the primary key?
