### ISSUE TITLE
trigger event on resource index change (filters/search/pagination) for being able to update a resource index tool content

### ISSUE THREAD

**Issue by olivM** [laravel/nova-issues#1758]
Hi,

We need some events triggered :
 - when search/filters/pagination change
 - when ResourceTable's prop 'resources' change
and a way to access these props

Context : 
I'm currently trying to develop a resource index tool which will show items on a map
So i'm looking for a way to update the map's items accordingly to the current filters/search/pagination

thanks

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
