### ISSUE TITLE
Image Download button not working

### ISSUE THREAD

**Issue by zeroseed** [laravel/nova-issues#176]
Hi , so image download button on module that have an images can't be downloaded,
I'm using public storage , the image showing correctly , but the download button doesn't work, no error console , just problem with download button (no effect)
See below .gif for demo
![nova_download_img](https://user-images.githubusercontent.com/2689790/44616133-82dd1600-a874-11e8-84fa-40def0597ace.gif)

**Comment by Andy-Baker** [comment]
I'm seeing the same problem.

**Comment by taylorotwell** [comment]
We are unable to debug your issue without a recreatable code example.
