### ISSUE TITLE
When selected, long text string appear out of SearchInput box on "Attach" page

### ISSUE THREAD

**Issue by good-system** [laravel/nova-issues#1760]
- Laravel Version: 5.8.17
- Nova Version: 2.0.5
- PHP Version: 7.1
- Operating System and Version: Ubuntu 16
- Browser type and version: All major browsers
- Reproduction Repository: N/A

### Description:

On "Attach" page, when selected a related record, and the record title value is a rather long string (60 or so characters), text display would appear outside of the SearchInput box.

**Comment by good-system** [comment]
Adding "h-full" here would make the text fit in the box.  But I understand there may be other considerations.

```
<div class="relative">
            <div

                class="flex items-center form-control form-input form-input-bordered pr-6"
      
            >
```

**Comment by jbrooksuk** [comment]
Can you post a screenshot please.

**Comment by jbrooksuk** [comment]
I'm unable to replicate this in v2.0.9

![image](https://user-images.githubusercontent.com/246103/62543350-b16dba00-b855-11e9-8ab9-ab001943663e.png)
