### ISSUE TITLE
bootstrap-vue not working in Laravel Nova

### ISSUE THREAD

**Issue by nibri10** [laravel/nova-issues#1761]
**I'm trying to use bootstrap-vue for building a tool in Laravel Nova but it does not work like I can to configure it?**

### **already tried to configure however it does not work**

My Tools.vue 

<template>
    <div>
        <heading class="mb-6">Client Contract</heading>

        <card class="bg-10 flex flex-col items-center justify-center" style="min-height: 300px">
            <div>
                <b-alert show>Default Alert</b-alert>

                <b-alert variant="success" show>Success Alert</b-alert>

                <b-alert v-model="showDismissibleAlert" variant="danger" dismissible>
                    Dismissible Alert!
                </b-alert>

                <b-alert
                    :show="dismissCountDown"
                    dismissible
                    variant="warning"
                    @dismissed="dismissCountDown=0"
                    @dismiss-count-down="countDownChanged"
                >
                    <p>This alert will dismiss after {{ dismissCountDown }} seconds...</p>
                    <b-progress
                        variant="warning"
                        :max="dismissSecs"
                        :value="dismissCountDown"
                        height="4px"
                    ></b-progress>
                </b-alert>

                <b-button @click="showAlert" variant="info" class="m-1">
                    Show alert with count-down timer
                </b-button>
                <b-button @click="showDismissibleAlert=true" variant="info" class="m-1">
                    Show dismissible alert ({{ showDismissibleAlert ? 'visible' : 'hidden' }})
                </b-button>
            </div>
        </card>
    </div>
</template>

<script>
    export default {
       
    mounted() {

    },
    data() {
        return {
            dismissSecs: 10,
            dismissCountDown: 0,
            showDismissibleAlert: false
        }
    },
    methods: {
        countDownChanged(dismissCountDown) {
            this.dismissCountDown = dismissCountDown
        },
        showAlert() {
            this.dismissCountDown = this.dismissSecs
        }
    }
}
</script>

<style>
/* Scoped Styles */
</style>

**Thanks!!!**

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).
