### ISSUE TITLE
My account disappeared !!! SOS!!! composer update error with auth.json.

### ISSUE THREAD

**Issue by guoxiangke** [laravel/nova-issues#1763]
today when I composer update my project I met blow error:
![image](https://user-images.githubusercontent.com/1160703/61574141-72b5d100-aaed-11e9-95b4-3e1d49827d2f.png)

my email is  dale404200@gmail.com
![image](https://user-images.githubusercontent.com/1160703/61574142-78131b80-aaed-11e9-8171-ac6c37839820.png)

**Comment by davidhemphill** [comment]
Please contact support at nova@laravel.com for help with account issues.
