### ISSUE TITLE
Nova Image url has storage/storage instead of only one storage

### ISSUE THREAD

**Issue by popescumarian** [laravel/nova-issues#1764]
- Laravel Version: 5.8
- Nova Version: 2.0.9
- PHP Version: 7.1
- Operating System and Version: W10

### Description:
I use this code to upload a banner and is storage fine in DB
`Image::make('banner')->disk('public')->path('banners'),`
but the image is not displayed in the preview or on the nova index (it shows broken image). The bug is because the image url has 2 storage strings, like this: **storage**/**storage**/banners/as4446adasda.jpeg

**Comment by davidhemphill** [comment]
Sorry, but we are unable to debug your issue without a reproducible code example. When you're able to demonstrate the issue with an example, feel free to open a new issue.
