### ISSUE TITLE
Lost checkbox when use action and indexQuery at the same time

### ISSUE THREAD

**Issue by JeasonZuo** [laravel/nova-issues#1765]
- Laravel Version: 5.6.39
- Nova Version: 1.2.1
- PHP Version: 7.2.4
- Operating System and Version: ubuntu 18.04
- Browser type and version: Google Chrome 

### Description:
When I use `action` and `indexQuery()` at a same time . The checkbox in index list will lost.
It will work normally if I add `sleep(1)` to indexQuery() function.
![image](https://user-images.githubusercontent.com/23731650/61630903-84e56a00-acbb-11e9-9511-b3d6665c4ac2.png)

### Steps To Reproduce:
1.create a resource and use indexQuery() 
2.add an action to the resource

indexQuery in resource
```
public static function indexQuery(NovaRequest $request, $query)
    {
        $query->with('user')->isRefundDone();
        // custom search
        $searchQuery = $request->get('search');
        $appLocale = app()->getLocale();

        if ($searchQuery) {
            $query->orWhere(function ($subQuery) use ($searchQuery, $appLocale) {
                $subQuery->isRefundDone();
                static::customSearch($subQuery, $searchQuery, $appLocale);
            });
        }

        if (empty($request->get('orderBy'))) {
            $query->getQuery()->orders = [];
            $query->orderBy(key(static::$indexDefaultOrder), reset(static::$indexDefaultOrder));
        }

        // sleep(1);
        
        return $query;
    }
```

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
