### ISSUE TITLE
Is there a way to set KeyValue Field default value at create form

### ISSUE THREAD

**Issue by bolechen** [laravel/nova-issues#1766]
Is there a way to set KeyValue default value at the create form view?
thx.

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).

**Comment by bolechen** [comment]
I solved this questions flow below method:

in your Model file.
```php
    public function __construct(array $attributes = [])
    {
        $payload = [
            'first' => '',
            'keyword1' => '',
            'keyword2' => '',
            'keyword3' => '',
            'keyword4' => '',
            'remark' => '',
        ];

        $this->setAttribute('payload', $payload);

        parent::__construct($attributes);
    }
```

Hope helpful for others.

**Comment by sarin-dotin** [comment]
You can use withMeta for this
```php
KeyValue::make('data')
    ->withMeta([
        'value' => $this->name ?? [
            'price' => '',
            'quantity' => ''
        ]
    ])
```
It will use the default value if the item doesn't have a value
