### ISSUE TITLE
in a date filter, how can i reset the selected date ? 

### ISSUE THREAD

**Issue by baykier** [laravel/nova-issues#1768]
![213B2D15-C493-4fa8-9AC3-086505728905](https://user-images.githubusercontent.com/12169649/61677366-f4963c00-ad31-11e9-8c44-148c6a3d69d5.png)
anyway could i reset the selected date?

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).

**Comment by SuhaibKotb** [comment]
Hey baykier, are there any updates about this feature request?
