### ISSUE TITLE
`npm run watch` doesn't work

### ISSUE THREAD

**Issue by partyka1** [laravel/nova-issues#1769]
HOW TO RUN WATCH/HOT ON THESE JS FILES GUYS

people are paying 100 bucks for this, instructions on how to compile or just solution-out-of-the-box(npm run dev/watch/hot doesn't work) would be nice

**Comment by Jubeki** [comment]
What do you mean with it doesn't work?  
If your JS-files are not being compiled you maybe forgot to add these files to `your webpack.mix.js`

If you want to use laravel nova with VueDevTools you need to look at these instructions:  
[https://nova.laravel.com/docs/2.0/customization/frontend.html#vue-devtools](https://nova.laravel.com/docs/2.0/customization/frontend.html#vue-devtools)

**Comment by partyka1** [comment]
Instructions you provided only tell how to make dev build, and not run webpack in hot/watch mode. What I mean, it doesn't work, when you run `npm run hot` laravel doesn't detect mix is running in `hot` mode, because it's creating `hot` lock file in wrong directory(one way to address it is having symbolic link `ln -s ../public/vendor/nova ./public` in main nova directory), but even when you resolve that issue, I couldn't get through compiling scss/css files with tailwind support(I have pretty good knowledge of webpack, but not of laravel mix, so probably someone could make it work easily, because I find it troublesome, just for example you cannot install official plugins https://laravel-mix.com/extensions/postcss-config, because you get error `mix.extend is undefined`). So my question is, how can you run `npm run hot` on nova files, so you can actively work/develop these css/js files

**Comment by partyka1** [comment]
Another problem is, when running `npm run hot`, you edit vue file, npm crashes with following error: 
![image](https://user-images.githubusercontent.com/19314216/61901380-ec9bef00-af1f-11e9-9186-099c5e736988.png)
So it just doesn't work out-of-the-box

**Comment by partyka1** [comment]
I got js AND css hot reloading to work, but I used my custom webpack config (slightly modified version of https://github.com/vuejs-templates/webpack ), as I figured it's problem with your mix configuration that caused problems. Would be nice anyway to get to know how to configure it with laravel mix.

**Comment by Jubeki** [comment]
Do you have a public repository, where I can find an example config and files to work with?

**Comment by partyka1** [comment]
As it contains nova files, i cannot share it publicly, ive added you to the private repo to check the configs. Currently when you do `import 'test.scss'` in js/vue files in nova, it doesn't work properly. With my config, you can do that, and have hot reloading working. Run `npm run dev` from nova directory and edit `nova/resources/css/app.css` to see how i expect it to work out-of-the-box

**Comment by partyka1** [comment]
As it contains nova files, I cannot share it publicly, Ive added you to the private repo to check the configs. Currently when you do import `test.scss` in js/vue files in nova, it doesn't work properly. With my config, you can do that, and have hot reloading working. Run `npm run dev` from nova directory and edit `nova/resources/css/app.css` to see how I expect it to work out-of-the-box

**Comment by Jubeki** [comment]
I looked into it and what I found was this comment in a laravel-mix issue:  
[https://github.com/JeffreyWay/laravel-mix/issues/92#issuecomment-273558018](https://github.com/JeffreyWay/laravel-mix/issues/92#issuecomment-273558018)

There it says:  

> It won't work right now for regular Sass files. The HMR feature is specifically for Vue and .vue components.

**Comment by partyka1** [comment]
thanks for the help! it would be nice if laravel mix did support it, but fortunately applying custom webpack config isn't that cumbersome(and for me actually preferred option)

**Comment by francoisauclair911** [comment]
Could I get access to your webpack config to see how you managed to do this @partyka1 ?

**Comment by partyka1** [comment]
@taylorotwell @davidhemphill @jbrooksuk could we provide some docs to people that want to run Nova the way I described? That is:
- running `npm watch` from app root directory
- being able to edit Nova js files with HMR support
- being able to create your own webpack outputs that use your own JS files that also use Nova js/css files

I guess, with some more steps and work, Nova could be run that way out-of-the-box, probably by default opt-out, without any custom config or hacking. I think it may be desirable, as Nova backend is highly customizable, but frontend is closed black box that's hard to extend.

**Comment by partyka1** [comment]
@francoisauclair911 I don't want to pirate Nova and redistribute it to people that didn't pay for it, if you could prove somehow you obtained nova license key I can give you access to the repo

**Comment by Sunhat** [comment]
This should work out the box. Laravel Nova is the slowest, least supported, least documented, and longest to develop for CMS I've used in my 15 years of web development.

**Comment by davidhemphill** [comment]
> This should work out the box. Laravel Nova is the slowest, least supported, least documented, and longest to develop for CMS I've used in my 15 years of web development.

You're ridiculous. Shitposting on a thread from 3 years ago? LOL
