### ISSUE TITLE
[Vue warn]: Invalid prop: type check failed for prop "resourceId". Expected String with value "1000", got Number with value 1000.

### ISSUE THREAD

**Issue by iamoat** [laravel/nova-issues#1772]
- Laravel Version: 5.8.29
- Nova Version: 2.0.9
- PHP Version: 7.1.23
- Operating System and Version: Mac OS X 10.14.5
- Browser type and version: Chrome 75.0.3770.100

### Description:

Got the following warning

[Vue warn]: Invalid prop: type check failed for prop "resourceId". Expected String with value "1000", got Number with value 1000.

when clicked on "Edit" icon from the index page. 

### Steps To Reproduce:

1. Login
2. Goto the index page of any nova resource
3. Click on the "Edit" icon of a resource

![image](https://user-images.githubusercontent.com/1286835/61880919-f6255700-af1f-11e9-912c-b9172fc74984.png)

**Comment by mvdnbrk** [comment]
@iamoat I have submitted a PR to fix this issue.

**Comment by iamoat** [comment]
> @iamoat I have submitted a PR to fix this issue.

Thank you. When will it be in an official release?

**Comment by jbrooksuk** [comment]
There’s no timeframe for another release yet.

**Comment by jbrooksuk** [comment]
Fixed in https://github.com/laravel/nova/pull/474
