### ISSUE TITLE
allow ViaResource,ViaResourceId,viaRelationship props on  /resources/:resourceName route

### ISSUE THREAD

**Issue by olivM** [laravel/nova-issues#1775]
routes.js define the resourceIndex route as : 
```js    
{
  name: 'index',
  path: '/resources/:resourceName',
  component: ResourceIndex,
  props: true,
},
```

so we can't use querystring to filter by a relationship. ( eg : i only want to display the Posts from Author#123 )

but with just a little change we could use this type of url :

/nova/resources/posts?viaResource=authors&viaResourceId=123&viaRelationship=posts&relationshipType=hasMany

```js    
{
  name: 'index',
  path: '/resources/:resourceName',
  component: ResourceIndex,
  props: route => {
    return {
      resourceName: route.params.resourceName,
      viaResource: route.query.viaResource,
      viaResourceId: route.query.viaResourceId,
      viaRelationship: route.query.viaRelationship,
    }
  },
},
```

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
