### ISSUE TITLE
[Feature request] Push notifications

### ISSUE THREAD

**Issue by h-zone** [laravel/nova-issues#1776]
Hello, dear devs!

Unforgivably forgotten notifications.

Notifications, such as pusher, redis, etc.

Avaible from the Box for Laravel, but not for Nova.

I'm not found any appropriate package for pusher notifications.

**Comment by wvervuurt** [comment]
Can't you just use Laravel's notification features?

**Comment by h-zone** [comment]
> 
> 
> Can't you just use Laravel's notification features?

through crutches

just created and included at layout.blade.php additional js/css files, which handle the push notifications.

but this is not good idea, whn we have notifications from the box.

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
