### ISSUE TITLE
"table not found" error on multiple database connections

### ISSUE THREAD

**Issue by Teox76** [laravel/nova-issues#1777]
- Laravel Version: 5.8.29
- Nova Version: 2.0.9
- PHP Version: 7.2
- Operating System and Version: MacOs X 10.13
- Browser type and version: Multiple

### Description:
I get the following error message when accessing Resources based on a Model with another DB connection than the default one:

<img width="1308" alt="Screen Shot 2019-07-26 at 16 24 02" src="https://user-images.githubusercontent.com/5430923/61959680-363e1580-afc4-11e9-9f74-b1e9ce3abae2.png">

Many thanks for any suggestions. Doing some research I have seen that this error did already happen (#1288, #1272, etc.) and it has been marked as fixed.  But clearly there is still something not working properly.

### Steps To Reproduce:

1. Add another DB connection to config/database.php
2. Create a Model and set the $connection variable to the other database connection
2. Create a Resource based on the previously created Model
3. Go to Resource's index page

**Comment by DannyBytific** [comment]
Heppns to me also with my authenticable model. Does not get the default connection / table.

**Comment by jbrooksuk** [comment]
Does the connection have to be to another server altogether? I've just tested with a different database (not a different server) and was unable to replicate.

**Comment by Teox76** [comment]
Hello,
yes to add another piece of information the main Nova instance is in a local docker image on my laptop, and the non-default DB connection points to another docker instance (local on my laptop too). 
The two images are in the same network and can see each other correctly (ping between the two works both ways, and host names are resolved correctly by docker). Sorry I should have mentioned it before.

**Comment by dkulyk** [comment]
Also can make different users with access to different DB

**Comment by jbrooksuk** [comment]
I've just tested this with two connections configured in Nova; MSSQL and MySQL. I was able to have resources setup from a different DB without a problem.

**Comment by Teox76** [comment]
I tried with multiple connections on the same docker image and everything works fine. The issue present itself when the connections are on different docker images (on the same docker network). Has anyone tried this particular case ?

**Comment by prey87** [comment]
Same happens for me with two MySQL connections. I can see the table content in the dashboard but can't add an entry.
