### ISSUE TITLE
apply Expandable trait to Code field

### ISSUE THREAD

**Issue by olivM** [laravel/nova-issues#1781]
as Code fields might contains some pretty big json/xml/... stuff, it might be useful to use the same Expand as for Text/Markdown/Trix fields

thanks !

**Comment by tylersatre** [comment]
Is this something that won't be added?

**Comment by olivM** [comment]
now that i'm more familiar with vuejs, i'll try to create a nova package adding this option
( probably just by forking the code field )

**Comment by tylersatre** [comment]
Let me know if you want any help on that... I was looking for the lazy option, but am happy to help out on something I will definitely use!
