### ISSUE TITLE
Edit a manyToMany relation

### ISSUE THREAD

**Issue by vayurobins** [laravel/nova-issues#1782]
- Laravel Version: 5.8.26
- Nova Version: 2.0.7
- PHP Version: 7.2.9
- Operating System and Version: MacOS Mojave 10.14.5
- Browser type and version: Chrome 75.0.3770.142

### Description:
I have a Company and a Plan resource with manyToMany Relation.
For instance: I have a company that is attached to a "Gold" subscription plan. If I want to change the plan to "Silver", I cannot because the dropdown is disabled. It should be possible to edit this or is there a reason why this is locked? If this is intentional and not a "bug", would someone please explain to me why this and maybe help me with an alternative solution?

I have created a post at Stock Exchange about this. https://stackoverflow.com/questions/56902462/allow-edit-resource-on-manytomany-relations-dropdown-is-disabled

![CloudCollect-3](https://user-images.githubusercontent.com/1386354/62045163-f619a580-b204-11e9-85bd-cbb2fc06e46d.png)
<img width="1591" alt="CloudCollect-2" src="https://user-images.githubusercontent.com/1386354/62045164-f619a580-b204-11e9-9e3a-5122eece4d4b.png">

**Comment by jbrooksuk** [comment]
Are you not using the wrong relationship type there? A company has one subscription.

**Comment by vayurobins** [comment]
I have thought of that, but I would like to have extra data on the pivot table, like price and renewal_frequency, which is on that specific company-subscription relation. I haven't found out how to do that yet though. I haven't gotten my head around the withPivot() method. It doesn't add any data to those fields.

**Comment by briavers** [comment]
Hey @vayurobins  Have you found a way to make it editable or just hide the edit button? (still an issue in v4)
