### ISSUE TITLE
Changing Trashed filter option doesn't reset page parameter to page 1

### ISSUE THREAD

**Issue by Frozire** [laravel/nova-issues#1784]
- Laravel Version: Any
- Nova Version: Any

### Description: 
Changing a filter ex. `Trashed` to `Only Trashed` will not reset the current page number. This means that if you are on page 2, but the new `Only Trashed` query has fewer results, you will be shown a `No [model] matched the given criteria.` since you are still on page 2 with results only being shown on page 1.

### Steps To Reproduce:
1. Create 50 of any model.
2. Add SoftDeletes to the model.
3. Soft Delete a single Model.
4. Navigate to page 2 on the models index view.
5. Set filter `Trashed` to `Only Trashed`

**Comment by jbrooksuk** [comment]
Confirmed in v2.0.9.

**Comment by jbrooksuk** [comment]
https://github.com/laravel/nova/pull/484#issuecomment-518818666

> This only really happens when the user manually types in a overflowing page number or chooses a filter while on a page that will eventually be greater than the number of results. We currently leave the filter menu in place to combat this, so the user can reset it manually (previously they had to edit the uri 😱).

**Comment by Frozire** [comment]
@jbrooksuk 

I don't think this should be closed. This is still an issue; it is not normal filter behaviour to not reset the page when changing the filter criteria.

https://github.com/laravel/nova/pull/484#issuecomment-519398028
