### ISSUE TITLE
Configurability of `authorizedToRun` and `canRun` message

### ISSUE THREAD

**Issue by alberto-bottarini** [laravel/nova-issues#1785]
I often use actions' `authorizedToRun`method (or `canUse` closure) to have some checks if resources can be target of a action, for example looking through its `status` field or similar.

If users try to run action on not valid resources they get a `Sorry! You are not authorized to perform this action.` message that is not very clear because it references to ACL while it's not.

It will be nice if this message will be editable in order to be more clear to the users.

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by stonkeep** [comment]
it would be very useful
