### ISSUE TITLE
firstDayOfPreviousQuarter returns wrong month

### ISSUE THREAD

**Issue by koenvu** [laravel/nova-issues#1786]
- Laravel Version: 5.8.28
- Nova Version: 2.0.9
- PHP Version: 7.1.6
- Operating System and Version: macOS 10.13.6
- Browser type and version: Safari 12.0.3
- Reproduction Repository: N/A

### Description:

In the `FirstDayOfPreviousQuarter` class the result for months 10, 11 and 12 are not correct. For example, for `2019-11-15` it returns `2019-04-01` on line 25.

### Steps To Reproduce:

```
Carbon::setTestNow('2019-11-15');

Carbon::firstDayOfPreviousQuarter();
// 2019-04-01, expected 2019-07-01
```

### Steps To Fix:

Change:
```
} elseif (in_array($month, [10, 11, 12])) {
    return Carbon::create($year, 4, 1)->setTime(0, 0);
}
```

To:

```
} elseif (in_array($month, [10, 11, 12])) {
    return Carbon::create($year, 7, 1)->setTime(0, 0);
}
```

In `src/Macros/FirstDayOfPreviousQuarter.php`

**Comment by jbrooksuk** [comment]
@koenvu I've submitted a PR with a fix for this.
