### ISSUE TITLE
bug BelongsToMany / ManyToMany when deleting resource it would not delete relation in pivot table

### ISSUE THREAD

**Issue by davidgabbay** [laravel/nova-issues#1787]
- Laravel Version: 5.8.26
- Nova Version: 2.0.6
- PHP Version: 7.2.11
- Operating System and Version: win10
- Browser type and version: chrom 
- Reproduction Repository: https://github.com/###/###

### Description:
bug BelongsToMany / ManyToMany when deleting resource it would not delete relation in pivot table
### Steps To Reproduce:

make task and belong it to many customers
then delete the task
the pivot table will still have the entries, so if you make a new task, it will automatically get the same id of the old task and then  it will connect automatically to the same customers

**Comment by davidhemphill** [comment]
This is not a bug in Nova as that's how Laravel's relations work. You can clean up the relations by using Model Event Observers on your Model.
