### ISSUE TITLE
Ability to use a CustomFilter multiple times on the same resource

### ISSUE THREAD

**Issue by olivM** [laravel/nova-issues#1788]
i built a NovaDateRangeFilter and i want to use it on Post->created_at and Post->published_at
so i defined : 

```php
    public function filters(Request $request)
    {
        return [
            new NovaDateRangeFilter('created_at'),
            new NovaDateRangeFilter('published_at'),
        ];
    }
```

but in vueX, the storage key in the name of the class, so the value of created_at filter and published_at filter are merged

i can't find a way to define a different storage key/method

**Comment by jbrooksuk** [comment]
Hi @olivM can you confirm which version of Nova you're using, please?

**Comment by olivM** [comment]
i use the latest 2.0.9

**Comment by jbrooksuk** [comment]
Yep, confirmed in v2.0.9.

I'm thinking maybe we could implement something similar to the metrics `uriKey` method.

**Comment by jbrooksuk** [comment]
in the mean time, you'll need to create a new filter for each field.

**Comment by jbrooksuk** [comment]
Sorry about this @olivM, I've been testing a lot of different issues and was confused that this wasn't working.

You can override the `key()` method in your `NovaDateRangeFilter` class:

```php
public function key()
{
    return 'date_'.$this->column;
}
```

Where `$this->column` is whatever property you're using in the `__construct` method.

I'm going to remove the `bug` label and instead assign `documentation` and get this documented next week 👍

**Comment by jbrooksuk** [comment]
I've sent a PR that documents this.

**Comment by jbrooksuk** [comment]
Documented at https://nova.laravel.com/docs/2.0/filters/defining-filters.html#dynamic-filters
