### ISSUE TITLE
How to hide model itself on self referencing model structure at Select input

### ISSUE THREAD

**Issue by Mirivhbv** [laravel/nova-issues#1789]
Hi, I want to know is there any way to hide self entity on self-referencing model structure. E.g. category table possess a nullable parent_id field, with this model on Category model:

```
public function parent()
{
    return $this->belongsTo(Category::class);
}
```

And for selection, using this on the resource model:
```
    public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
            ....
            BelongsTo::make('Category', 'parent')
        ];
    }
```

It shows self in the select list like that (edit page):
![nova-cat-self](https://user-images.githubusercontent.com/10003520/62232073-6deafa00-b3d6-11e9-8ab7-e4200db7d342.png)

**Comment by jbrooksuk** [comment]
As in, you want to filter out the options within the Category dropdown or you want to hide the Category field?

**Comment by frddl** [comment]
@jbrooksuk we have the structure where category can have sub-categories. So we want to hide the category itself in its "child" category field.

**Comment by dkulyk** [comment]
https://nova.laravel.com/docs/2.0/resources/authorization.html#relatable-filtering

**Comment by Mirivhbv** [comment]
Thanks for the help. Solved via Relatable Filtering.
