### ISSUE TITLE
Display name for relationships 

### ISSUE THREAD

**Issue by albalooshi** [laravel/nova-issues#179]
I am trying to set a name for a relationship column, For normal fields we can do the following:
`Text::make('F. Name', 'first_name')`

However I can not do the same thing with relationships (The class name is `Club` )
`BelongsTo::make('Home Club', 'homeClub') // this gives an error`

Where the following code works
`BelongsTo::make('Club', 'homeClub')`

Is there are a way to do this?

**Comment by v1nk0** [comment]
You'll need a third argument:
Argument 1. Name to display (e.g. Home Club)
Argument 2. Name of the relationship as used in the model (e.g. club)
Argument 3. The Nova Resource (e.g. App\Nova\Club)

```php
BelongsTo::make('Home Club', 'homeClub', 'App\Nova\Club');
```

**Comment by albalooshi** [comment]
@v1nk0 
Thank you very much! it works.

**Comment by bradders** [comment]
Thanks for that, @v1nk0 

Are those arguments documented anywhere?

**Comment by EdanBrooke** [comment]
> @albalooshi You'll need a third argument:
> Argument 1. Name to display (e.g. Home Club)
> Argument 2. Name of the relationship as used in the model (e.g. club)
> Argument 3. The Nova Resource (e.g. App\Nova\Club)
> 
> ```
> BelongsTo::make('Home Club', 'homeClub', 'App\Nova\Club');
> ```

Does not work.
`Call to undefined method App\Model::uriKey()`

**Comment by EdanBrooke** [comment]
> > @albalooshi You'll need a third argument:
> > Argument 1. Name to display (e.g. Home Club)
> > Argument 2. Name of the relationship as used in the model (e.g. club)
> > Argument 3. The Nova Resource (e.g. App\Nova\Club)
> > ```
> > BelongsTo::make('Home Club', 'homeClub', 'App\Nova\Club');
> > ```
> 
> Does not work.
> `Call to undefined method App\Model::uriKey()`

Okay - does work. You need to use `App\Nova\Model`. However, it only changes the display in the dropdown and not to the left of it.
