### ISSUE TITLE
Pagination and count of records for hasMany relationship

### ISSUE THREAD

**Issue by PrafullaKumarSahu** [laravel/nova-issues#1790]
- Laravel Version: 5.8.30
- Nova Version: 2.0.0
- PHP Version: 7.3.5
- Operating System and Version: Windows 10 pro
- Browser type and version: 75.0.0

### Description:
Page 1
![pagination issue-check-url-and-page-item-counts-page-1](https://user-images.githubusercontent.com/2470646/62284358-19e12380-b471-11e9-899e-8365a3800ae4.PNG)

You can notice pagination is disabled and in 

Page 2
![pagination issue-check-url-and-page-item-counts2](https://user-images.githubusercontent.com/2470646/62284137-b48d3280-b470-11e9-9c7b-328286942e3e.PNG)

Now look at URL, page number and count of items.

### Steps To Reproduce:

Quote and QuoteItems shares has-Many belongsTo relation. and in QuoteResource 

` HasMany::make('Quote Items', 'quoteItems'),`

**Comment by jbrooksuk** [comment]
I can't replicate this in Nova v2.0.9.
