### ISSUE TITLE
Native support for max width fields in index (ellipses)

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#1791]
I have some resources with multiple required columns. Sometimes big text fields (or textarea and perhaps computable fields) stretch way to long.

Would be nice if a field had a max width or easier, max charachters with ellipses as suffix.

Something like:

`public function maxCharsIndex(maxChars = 25, suffix = '...') {}`

**Comment by jbrooksuk** [comment]
Do you mean on the detail pages?

**Comment by preliot** [comment]
I mean on the index page, where all information is displayed in a table

**Comment by jbrooksuk** [comment]
This is doable using the `displayUsing` method on a field:

```
Text::make('Name')->displayUsing(function ($name) {
    return Str::limit($name, 5);
}),
```

Before:

![image](https://user-images.githubusercontent.com/246103/62363855-05a43180-b518-11e9-98de-fb2ca7c5b7b7.png)

After:

![image](https://user-images.githubusercontent.com/246103/62363835-fd4bf680-b517-11e9-9eef-b6b9b2d0db59.png)
