### ISSUE TITLE
Change "Choose an option" on Select Field

### ISSUE THREAD

**Issue by mrvnklm** [laravel/nova-issues#1793]
Hey guys, is there a way to change the 

> "Choose an option"

 on Select fields?
Think this would be really useful in order to avoid misunderstandings in case the field is nullable, the user might think that it is necessary to select something.

Cheers

**Comment by davidhemphill** [comment]
You can change this value by editing your translations.

**Comment by mrvnklm** [comment]
Sorry I didn't point out that I was talking about specific fields, not all at together.

**Comment by drjekyll** [comment]
I would like to add support for this - a field specific option for changing the select placeholder. I find it more helpful if the placeholder can read something specific, such as "Choose a cast member" or "Choose a character" etc.

**Comment by davidhemphill** [comment]
You can set the placeholder using `$field->withMeta(['placeholder' => 'My Placeholder')`.

**Comment by davidhemphill** [comment]
Actually, strike that, this doesn't currently work on the Select field, but I've just added it and it'll go out in the next release. 👍

**Comment by Milkhan** [comment]
> Actually, strike that, this doesn't currently work on the Select field, but I've just added it and it'll go out in the next release. 👍

@davidhemphill  Still, waiting, any progress about this?

**Comment by jbrooksuk** [comment]
You need to override the translation for `Choose an option`.

**Comment by Milkhan** [comment]
@jbrooksuk Thank you but I was asking about a placeholder for every individual field, I don't want all the fields to show the same placeholder.

**Comment by davidhemphill** [comment]
You can use `$field->withMeta(['placeholder' => 'My Placeholder')` to set the placeholder on the `Select` field.

**Comment by Milkhan** [comment]
> You can use `$field->withMeta(['placeholder' => 'My Placeholder'])` to set the placeholder on the `Select` field.

@davidhemphill Thank you, I hope you add this option to  BelongsTo too.

**Comment by jbrooksuk** [comment]
@Milkhan see https://github.com/laravel/nova/pull/815
