### ISSUE TITLE
Let Nova Actions receive the entity being actioned in Detail mode. (or build something similar which could)

### ISSUE THREAD

**Issue by dylanharbour** [laravel/nova-issues#1794]
Feature Request:

Nova Actions do not go far enough to be useable in most situations for us. 

This is because they are run with Fields/Options that are not specific to a single entity. I do understand why this is the case (both because they're run on collections instead of on single models and because of when the field options are generated in the lifecycle of running an action)

However, I think a feature similar to Actions that can be attached to a Detail view only but have scope of the exact Model that is being actioned on would be much more useful. 

Take for example an `Upgrade Subscription` Action. Lets assume that this is more complicated than just a single linking table / field value but not too complicated that it can't be actioned with a single modal pop-up and a few field options. This could be accomplished with the current Actions feature but has one issue: Action Fields do not have scope of the entity that they're being run against. i.e. You cannot generate reasonable options for the user because you don't know the current value of the User. The only option to do this with actions is to have very generic field values that could be vague and frustrating. 

I know this could be achieved with Tools or Resource Tools feature but there's 2 reasons why I think they're also not the ideal tools for the job. 
 
1. Needing to generating a custom Resource Tool seems overly complicated for requirements like this. They are basic action, with basic input fields and should be quicker to roll out

2. Resource Tools sit above the detail view, and don't easily give you a way of injecting your tool into the "Actions" drop-down. Therefore, users will be presented with some actions that are in the dropdown and other actions that are above the detail view. This isn't a great user experience. 

I think this would be a great addition to the Nova Admin framework. 👍

**Comment by m-lotze** [comment]
Not only on the details page please. The fields method of an Action should know about the selected models, so we can generate fields based on that. see also here: https://github.com/laravel/nova-issues/issues/1029

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by GDanielRG** [comment]
Whats the feedback on this? I believe this would be an extremely great addition.
