### ISSUE TITLE
Date and DateTime Field requires an localization feature

### ISSUE THREAD

**Issue by h-zone** [laravel/nova-issues#1795]
Hi.
Will be good to use Carbon's `->locale()` method
Or better
third param for Date/DateTime Field to specify locale, where default (empty) value is `app()->getLocale()` or `config('app.locale')`

**Comment by jbrooksuk** [comment]
Recently I've seen someone use localisation strings like `__("Y-m-d")`  which allows translation of dates, without relying on the locale.

I thought this was a pretty neat use-case of translation strings.

**Comment by jbrooksuk** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
