### ISSUE TITLE
Icon styling

### ISSUE THREAD

**Issue by nilsE** [laravel/nova-issues#1797]
I get the following display of the icons and have no idea why this is so. Does anyone have an idea?
There's nothing special in CSS or so; i compared it to a working Nova instance and can't see any differences in CSS.

<img width="1378" alt="screenshot_842" src="https://user-images.githubusercontent.com/1436929/62517853-89b42d00-b828-11e9-9b1c-baefcf63d64d.png">

**Comment by jbrooksuk** [comment]
What browser are you using? Have you modified the CSS in any way? The font looks different to me too, has that changed?

**Comment by nilsE** [comment]
i'm using the latest chrome, but it's also stuck on other browsers. no css modifications, no other fonts ;-(

**Comment by jbrooksuk** [comment]
What operating system?

**Comment by nilsE** [comment]
mac os 10.14.6, but i don't think that's the point. Another nova instance works with no problems (same mac, same browser, same everything). Unfortunately i can't find a starting point. I will now deactivate some third party nova packages, maybe one of these injects something.

**Comment by jbrooksuk** [comment]
It's important to work out if it's a Nova rendering issue or not. Yes, if you have third-party packages, disable them and see what happens.

**Comment by nilsE** [comment]
@jbrooksuk ok, i finally found it! i was importing the full tailwind css in my tool.scss because i need some classes that have not been provided within the nova's tailwind. if i remove this, all is fine again - except my tool that needs these classes ;-( 
is there any official way to use/include the full tailwind framework? 
thanks for your help.

**Comment by jbrooksuk** [comment]
I don't think so. We use a customised version of Tailwind 0.6.0 so this could also be clashing. You could customise the class names in your config though.
