### ISSUE TITLE
im catch situation [events]

### ISSUE THREAD

**Issue by h-zone** [laravel/nova-issues#1798]
My situation.
Detail page have some computed fields (its Order)

I need, when i delete related table's row (Goods) refresh Detail page and if page have cards|tools - refresh it too.

So, we need events on relationship fields like
```
HasMany(....)->onDelete(function()
{
    //.... interact with vue components (?)
})->onUpdate(...)->onCreate(....)
```
I hope the idea is clear...

`location.reload` do not offer, tons of external services, like pusher/fonts ... tons of materials to download is also not good

**Comment by jbrooksuk** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](https://larachat.co/).

**Comment by h-zone** [comment]
@jbrooksuk if you read this topic, - its not a gq.
its a feature request. yes with a lyrics, but f.r.

**Comment by jbrooksuk** [comment]
To clarify, what you're asking for are hooks on fields so you can see when something has changed?

**Comment by h-zone** [comment]
yes, field hooks is a way to control page content and see valid data.

**Comment by jbrooksuk** [comment]
Apologies for the confusion.

In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
