### ISSUE TITLE
Partition Metrics display incorrect numbers

### ISSUE THREAD

**Issue by rcknr** [laravel/nova-issues#18]
I was getting weird numbers with Partition metrics and narrowed down the problem to the following line (src/Metrics/Partition.php:125):
```
return [$key => (int) number_format($result->aggregate, 0)];
```
So, when you have a large number over 1000 it formatted with thousands separator like "1,000" and then integer cast turns it into 1. If the point is to get rid of decimals, possible fix could be the following:
```
return [$key => (int) $result->aggregate;
```

**Comment by themsaid** [comment]
yes we're fixing that.

**Comment by rcknr** [comment]
By the way, Partition metrics only display colors for the first ten results!
