### ISSUE TITLE
Cursor jumps to wrong position in Markdown field after previewing

### ISSUE THREAD

**Issue by bakerkretzmar** [laravel/nova-issues#1800]
As requested, resubmitting #1338 as it still applies to the latest version of Nova.

- Laravel Version: 5.8.31
- Nova Version: 2.0.9
- PHP Version: 7.2.19
- Operating System and Version: macOS High Sierra 10.13.6
- Browser type and version: Chrome 76.0.3809.100 and Firefox 68.0.1

### Description:

After previewing a markdown field and then switching back to writing mode, upon clicking inside the field the cursor appears several lines below the spot that was clicked. It appears to jump down proportionally to the clicked position inside the field—clicking somewhere in the first line of text appears to work normally, clicking in the second or third line might place the cursor near the tenth line, and clicking 10 or more lines down in the field usually causes the cursor to jump to the very bottom of the field and cause the browser to scroll down too.

Subsequent clicks function normally. Clicking in the field immediately after the initial page load works fine too—the jumpiness only happens after previewing and then switching back to writing mode.

### Steps To Reproduce:

- fresh Laravel site with `laravel new`
- fresh Nova install from Composer
- create a Markdown field on any resource
- edit or create one of that resource
- enter 10+ lines of text in the Markdown field
- preview it
- switch back to 'write' mode
- click somewhere inside the Markdown field

Reproduced in Firefox and Chrome, in different sites and Nova installations, and on different Nova resources.

#### Troubleshooting

Commenting out `this.codemirror.refresh()` on [line 186 of MarkdownField.vue](https://github.com/laravel/nova/blob/2.0/resources/js/components/Form/MarkdownField.vue#L186) or wrapping it in a `this.$nextTick()`, and recompiling Nova's assets, appears to resolve this issue without affecting any other functionality.

If that's an acceptable fix I'm happy to send over a PR to the Nova repo, but I don't understand why that fixes it or what other implications it could have.

**Comment by jbrooksuk** [comment]
Confirmed! Pushing a fix now.
