### ISSUE TITLE
Method Illuminate\\Database\\Eloquent\\Collection::getKey does not exist.

### ISSUE THREAD

**Issue by 4n70w4** [laravel/nova-issues#1805]
- Laravel Version: 5.8.30
- Nova Version: 2.0.7 (I can't upgrade to 2.0.9. besause you broken back compability https://github.com/laravel/nova-issues/issues/1735)
- PHP Version: 7.3.7

In resourse fields:

```php
 MorphedByMany::make(__('Employes'), 'employes', User::class)->searchable(),
MorphedByMany::make(__('Users'), 'users', User::class)->searchable(),
```

In model:

```php
    public function users() {
        return $this->morphedByMany(User::class, 'organizable');
    }

    public function employes() {
        return $this->morphedByMany(User::class, 'organizable');
    }
```

As you can see — in my code the user and employee are 100% identical in logic and data source.

Go to

```
/resources/organizations/99/attach/users?viaRelationship=users&polymorphic=1
/resources/organizations/99/attach/users?viaRelationship=employes&polymorphic=1
```

If I attach Users — I take exception. But if I attach Employes — all ok.

I make small debug and I found out that Nova adds some of its own validation rules if the field is called `users`. This leads to an exception.

This also works:

```php
MorphedByMany::make(__('Users'), 'employes', User::class)->searchable(),
```

**Comment by jbrooksuk** [comment]
> (I can't upgrade to 2.0.9. besause you broken back compability #1735)

FWIW, I don't think that's accurate. https://github.com/yassipad/laravel-nova-nested-form/pull/68/ would fix the package on newer versions of Nova.

**Comment by 4n70w4** [comment]
@jbrooksuk https://semver.org/

```
MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards compatible manner, and
PATCH version when you make backwards compatible bug fixes.
Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.
```

Nova broke backwards compatibility in patch =)

**Comment by jbrooksuk** [comment]
The nested form package is broken.

I've tested with other custom fields (such as Gutenberg) and within the Nova Dusk Suite and they work okay.

**Comment by 4n70w4** [comment]
@jbrooksuk explain why you closed issue.
This issue has nothing to do with the nested form package.
This issue about a bug in the Nova MorphedByMany field.

I can test only on 2.0.7 version.

**Comment by jbrooksuk** [comment]
I have tested this in a fresh v2.0.10 project by adding tags to Users, Images and Posts. I'm able to tag things as expected.
