### ISSUE TITLE
Vue error rendering with Value Metric

### ISSUE THREAD

**Issue by mvdnbrk** [laravel/nova-issues#1806]
This [PR #490](https://github.com/laravel/nova/pull/490) configured Numeral to use the app locale.

This results in a render error if the locale is set to a non supported Numeral locale.
List of supported locales by Numeral can be found here:
https://github.com/adamwdraper/Numeral-js/tree/master/locales

This is related to this [issue](https://github.com/adamwdraper/Numeral-js/issues/497) with Numeral.

This will also occur if you have set your locale -for example- to `en_GB` for UK english.
You should then use a dash instead of an underscore to set the locale:
```js
numeral.locale('en-gb')
```

**Comment by mvdnbrk** [comment]
Looks like Numeral is kind of outdated.
It has over a hundred issues and pull requests and didn't get updated in the last two years.

Should we even depend on this at all? Maybe we should consider a better solution. 😉

**Comment by xiyixia** [comment]
the same issues in my project..

**Comment by jbrooksuk** [comment]
Given that Numeral seems a bit dated, I'm inclined to look for a maintained fork or an alternative.

**Comment by mvdnbrk** [comment]
[Numbro](https://github.com/BenjaminVanRyseghem/numbro) might be an alternative.

**Comment by voicecode-bv** [comment]
Same issue here, it's messing up the entire dashboard. Hope there will be a fix soon.
