### ISSUE TITLE
Call to undefined method Illuminate\Database\Eloquent\Builder::onlyTrashed()

### ISSUE THREAD

**Issue by fabianpnke** [laravel/nova-issues#1807]
- Laravel Version: 5.8.31
- Nova Version: 2.0.10
- PHP Version: 7.3
- Database Driver and Version: MySQL 8.0.17
- Operating System and Version: Ubuntu 18.04.1
- Browser type and version: Chrome 75.0.3770.142

### Description

When a _Trashed Filter_ is applied to a Laravel Model with _SoftDeletes_ the following Error is thrown: `Call to undefined method Illuminate\Database\Eloquent\Builder::onlyTrashed()`

![image](https://user-images.githubusercontent.com/36986615/62651542-7b196300-b959-11e9-9c97-01fb473fb2ea.png)

### Steps To Reproduce

Setup an Laravel Model with _SoftDeletes_ and apply an _Trashed Filter_ in Nova.

**Thanks for your Help!**

**Comment by mvdnbrk** [comment]
I can not reproduce this. 

You have another `Posts` filter, maybe it is related to that?

**Comment by fabianpnke** [comment]
A `__construct()` Function in my Post Model was causing this issue.
