### ISSUE TITLE
Inconsistent Composer/Satis version name in 2.0.10 release

### ISSUE THREAD

**Issue by pehbehbeh** [laravel/nova-issues#1808]
Nova Version `2.0.10` does not have a `v` prefix for the version available via Satis. This is inconsistent to all previous versions and also breaks our update logic.

<img width="243" alt="Bildschirmfoto 2019-08-08 um 09 23 05" src="https://user-images.githubusercontent.com/133831/62683367-85ba1380-b9be-11e9-8735-2921ebbc6d99.png">

[[Source](https://nova.laravel.com/include/all$05c505bf7d6d691830286f7f7b3327d5fb10ee51.json)]

**Comment by jbrooksuk** [comment]
I've let David know.

**Comment by jbrooksuk** [comment]
https://github.com/laravel/nova/releases/tag/v2.0.10 has been re-released.

**Comment by pehbehbeh** [comment]
Thanks!
