### ISSUE TITLE
Buggy mechanism validating fields of resource

### ISSUE THREAD

**Issue by acubino** [laravel/nova-issues#1809]
Dear.

I think form validate fields are somme buggy.
If I use TAB for go next field. Errors will not validate.
If I click on another field. Errors will not validate.

Errors only validate when pressing Enter or when i submit the form

Also. I think the system have another big issue for large forms (mine are more than 30 fields and require some minutes).
When you press to save, only see a danger icon a very little of the time. I think if window focus on the first error appeared, can be more usefull for all.

**Comment by jbrooksuk** [comment]
These are not bugs.

**Comment by acubino** [comment]
Ok. Can you give me an advice for try to modify myself?
