### ISSUE TITLE
Apache root's subfolder

### ISSUE THREAD

**Issue by num3r06** [laravel/nova-issues#181]
Hi
I've tested nova on Mac with valet and all work fine.
In windows my development environment it's a bitnami wampstack with apache.
My laravel app it's in a root subfolder's http://localhost/ater/public and work fine.
When I've installed nova the admin panel search the asset on root folder's and obviusly not found.
with php artisan serve works
There's a way for using nova in this mode?
With another app I've using mix.SetPublicRoot in webpack config and with run dev all works fine, but with nova I don't know if it's possible.
Thx

**Comment by taylorotwell** [comment]
We are unable to debug your issue without a recreatable code example.
