### ISSUE TITLE
Error while return false in Observer in creating method

### ISSUE THREAD

**Issue by Jedajcz** [laravel/nova-issues#1814]
if I don't want to save the request to the database. I create e.g. VoucherObserver and method creating, where I put return false.

`public function creating(Voucher $voucher) ` 
`{ ` 
`     return false; ` 
` } ` 

Then laravel nova have error.
``Integrity constraint violation: 1048 Column 'actionable_id' cannot be null (SQL: insert into `action_events` (`batch_id`, `user_id`, `name`, `actionable_type`, `actionable_id`, `target_type`, `target_id`, `model_type`, `model_id`, `fields`, `original`, `changes`, `status`, `exception`, `updated_at`, `created_at`) values (8e60bad5-2461-44cc-bd0b-ab168e3a1748, 1, Create, App\Models\Voucher\Voucher, ?, App\Models\Voucher\Voucher, ?, App\Models\Voucher\Voucher, ?, , ?, {"price":20,"partner_id":75,"key":20}, finished, , 2019-08-10 18:17:05, 2019-08-10 18:17:05))``

**Comment by dillingham** [comment]
The ActionEvent is saved when your resource is saved
It doesn't check if you save a resource in the UI but early terminate the save
https://nova.laravel.com/docs/2.0/actions/defining-actions.html#action-log
If you have logic to determine it shouldn't save the Voucher, do it in validation 
If you need custom, ->rules() accept rule objects https://laravel.com/docs/5.8/validation#using-rule-objects

**Comment by Jedajcz** [comment]
> The [ActionEvent](https://nova.laravel.com/docs/2.0/actions/defining-actions.html#action-log) is saved when your resource is saved
> It doesn't check if you save a resource in the UI but early terminate the save
> If you have logic to determine it shouldn't save the Voucher, do it in validation
> If you need custom, ->rules() accept [rule objects](https://laravel.com/docs/5.8/validation#using-rule-objects)

Ohh i see this now. Im sorry and thank you.

**Comment by AshleyMinshall** [comment]
Hi I'm having the same problem, however I cannot prevent the model from being created in validation. 

I have effectively 2 forms in 1 resource, and the data for the one model. Because nova does not let you interrupt the saving process I decided to do it in a model observer and then return false.

Is there a better way to do this?

Thanks
Ashley
