### ISSUE TITLE
One missing FQCN in the layout view, forcing to use Laravel's alias feature

### ISSUE THREAD

**Issue by florentpoujol** [laravel/nova-issues#1817]
Hello there, this is neither really a feature nor a bug report

We are using Nova at my company, and we really like it, but we have one small issue.

We don't like Laravel's aliases system and we like to keep our list of aliases empty, but Nova is missing a proper use statement or a FQCN for the Config facade that is used in `/resources/views/layout.blade.php` (line 40 in v2.0.10).

It would be ace if you could get around to add it for a next version

Thanks for your time !

**Comment by jbrooksuk** [comment]
I've made a PR which addresses this :)
