### ISSUE TITLE
Change `Create Resource` button title

### ISSUE THREAD

**Issue by hsharghi** [laravel/nova-issues#1818]
Not always every thing is going to be created! 
In a project that I'm currently working on I've faced these issues
- In a `Project` resource I have `HasMany` relation to `Model` resource, a `Model` is a file to be uploaded. So I want the create button title to be **Upload model** not **Create model**.

- An invitation can be send to other users to collaborate on a `Project`, so when I'm trying to create an invitation (with some properties attached, so it's not a simple action to send an email), I want the create button title to be **Send invitation** not **Create invitation**

- Many more examples to show **Create something** is not always the correct title, 
**Add Payment Mehtod** instead of **Create Payment Method**,
**Add Comment** instead of **Create Comment**
...

So why button title is not changeable?

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
