### ISSUE TITLE
attaching model in many to many relation - Searchable Relations

### ISSUE THREAD

**Issue by nirav-prajapati-indianic** [laravel/nova-issues#182]
I was trying to make relation working on model categories and products

`BelongsToMany::make('categories')->searchable()`

`BelongsToMany::make('products')->searchable()`

But when i got to view page of product and try to attach category and try to search but no result comes up.

Anyone has idea?

**Comment by v1nk0** [comment]
@nirav-prajapati-indianic do you have an intermediate table `category_product` with `category_id` and `product_id` columns? Did you configure the relationship on both models as well?

**Comment by nirav-prajapati-indianic** [comment]
@v1nk0 
Thanks for your answer, I have defined my relation and all things but i found my problem,
I have to add field name in search property as below,

` public static $search = [
        'id', 'name'
    ];`
