### ISSUE TITLE
sortable() on belongsto field not working

### ISSUE THREAD

**Issue by m-lotze** [laravel/nova-issues#1821]
Using `sortable()`on e.g. a BelongsTo field is not working.

```
BelongsTo::make('name', 'relation_method', 'relatedResource')->sortable()
```
nova generates a query like this:
```
select * from resource order by relation_method
```
To make it work, nova would need to generate a query like this:
```
select (select title_column from related_resource_table) as order_column, resource_table.* from resource order by order_column
```

If something like this will not be implemented, the documentation should state that relation fields are never sortable and the fields should not allow to set the property sortable.

related #1728 #157

**Comment by skoyah** [comment]
@jbrooksuk It seems that this issue persists for Lenses. I am not able to sort a belongsTo relation through lens view.

**Comment by bakerkretzmar** [comment]
@jbrooksuk are there plans to implement this for Lenses too?
