### ISSUE TITLE
Documentation of deletable() just tells how to keep the default the same.

### ISSUE THREAD

**Issue by orrd** [laravel/nova-issues#1822]
Regarding this section of the documentation on using `deletable()` for File fields: https://nova.laravel.com/docs/2.0/resources/file-fields.html#pruning-deletion

The documentation says that you have to call `->deletable()` to make the file deletable, but I believe the opposite is actually the case.  Deletable seems to be enabled by default.  But if we want to disable that ability, we have to call `->deletable(false)`. So using `->deletable()` doesn't actually do anything because deletable is on by default.

**Comment by jbrooksuk** [comment]
Confirmed!

The `Deletable` trait sets `$deletable = true`, so you're right, we need to update this. I believe the confusion came that `prunable` is `false` by default.
