### ISSUE TITLE
How to override create method in laravel nova?

### ISSUE THREAD

**Issue by muhghazaliakbar** [laravel/nova-issues#1824]
Hi, I'm actually want to use `DB::transaction()` method when creating resource in nova to do some stuff, but i don't know what's the best way to doing this.

Here the example I have tried this in my model but seems doesn't work. :/
```php
    /**
     * @param $attributes
     *
     * @throws \Throwable
     */
    public static function create($attributes)
    {
        DB::transaction(function () use ($attributes) {
            (new static)->newQuery()->create($attributes);

            \Log::info('Coupon created');

            \Stripe\Coupon::create([
                'duration'    => 'once',
                'id'          => 'free-period',
                'percent_off' => $attributes['percent_off'],
            ]);
        });
    }
```

Anyone can help?

**Comment by jbrooksuk** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](https://larachat.co/).
