### ISSUE TITLE
Form input/button alignment issue in Firefox

### ISSUE THREAD

**Issue by rdarcy1** [laravel/nova-issues#1825]
- Laravel Version: 5.8.32
- Nova Version: 2.0.11
- PHP Version: 7.2
- Database Driver and Version: MySQL 5.7
- Operating System and Version: MacOS 10.14.5
- Browser type and version: Firefox 68.0.1

### Description

Minor visual bug in Firefox – form inputs and buttons have their text offset towards the bottom of the element.

#### Firefox
<img width="873" alt="Screenshot 2019-08-15 at 15 22 54" src="https://user-images.githubusercontent.com/15962421/63101921-01ddc980-bf72-11e9-9c2d-36efb04dbb1d.png">

#### Chrome
<img width="1172" alt="Screenshot 2019-08-15 at 15 33 59" src="https://user-images.githubusercontent.com/15962421/63101987-2174f200-bf72-11e9-92c2-12e86d257214.png">

**Comment by jbrooksuk** [comment]
I don't see this in Firefox v68.0.1, v68.0.2 or v69.0b13

![image](https://user-images.githubusercontent.com/246103/63337222-821c7a00-c338-11e9-8831-3cd935193941.png)

**Comment by jbrooksuk** [comment]
I'd check that you've not overwritten any CSS.
