### ISSUE TITLE
On server nova is looking for uppercase table name instead of lowercase

### ISSUE THREAD

**Issue by desaintflorent** [laravel/nova-issues#1826]
- Laravel Version: 5.8.32
- Nova Version: 2.0.11
- PHP Version: 7.2
- Database Driver and Version: MySQL 5.7
- Operating System and Version: MacOS 10.14.5

### Description

I have a model who throw an error when creating a new element. It's working well on my local machine but produce a bug on the server. 
The error I get is :

`QLSTATE[42S02]: Base table or view not found: 1146 Table 'bijglojshycmznnftjtc.StoresTitles' doesn't exist...`

The problem is concerning the table name ( the table name is "storesTitles" not "StoresTitles"). Nova use an uppercase for the first letter on the server instead of a lowercase.

Of course in the model I declared :

` protected $table = 'storesTitles';
`

It's working well in my application but not with nova on my production server.
It was working well a couple of months ago so it seems that's it's related to a recent update of Nova or Laravel ?

### Migration file :

```
Schema::create('storesTitles', function (Blueprint $table) {
              $table->increments('id');
              $table->string('name');
              $table->string('slug');
        }); 
``` 

I would love to get some idea about this bug...

**Comment by jbrooksuk** [comment]
I'm not convinced that this is a Nova issue, but instead related to something your side. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](https://larachat.co/).

**Comment by mehmetalikus** [comment]
I had this issue too. Works on my local development but in production table names are capitalized on query
