### ISSUE TITLE
cards do not display when locale is zh_CN

### ISSUE THREAD

**Issue by huoding** [laravel/nova-issues#1828]
- Laravel Version: #.#.#
- Nova Version: #.#.#
- PHP Version: #.#
- Database Driver and Version: #.#
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description

cards do not display when locale is zh_CN,
there are error msgs in chrome console:
TypeError: Cannot read property 'delimiters' of undefined

if locale is en, cards is work.

### Steps To Reproduce

change locale from en to zh_CN

**Comment by huoding** [comment]
https://github.com/laravel/nova-issues/issues/1806

**Comment by jbrooksuk** [comment]
@huoding you've not filled in any information regarding your setup. What version of Nova are you using?

**Comment by jbrooksuk** [comment]
Sorry, but there's not enough information to go off of here. If the issue you have still persists, please feel free to open a new issue with all the details of what you're trying, what you expect to happen, what's happening, and how to reproduce it. Thanks!

**Comment by KaptinLin** [comment]
I have this issue too.
With Nova v2.0.11

When set locale to another language.

The Value Metrics not working any more.

![image](https://user-images.githubusercontent.com/999331/63215978-c6552200-c160-11e9-96bb-7218d2f9137b.png)

This may related to this [issue](https://github.com/adamwdraper/Numeral-js/issues/497) with Numeral.

**Comment by bolechen** [comment]
> I have this issue too.
> With Nova v2.0.11
> 
> When set locale to another language (e.g. zh-CN).
> 
> The Value Metrics not working any more.
> 
> ![image](https://user-images.githubusercontent.com/999331/63215978-c6552200-c160-11e9-96bb-7218d2f9137b.png)
> 
> This may related to this [issue](https://github.com/adamwdraper/Numeral-js/issues/497) with Numeral.

Wait this pull merged: https://github.com/laravel/nova/pull/506
