### ISSUE TITLE
Remove blank space in Actions list

### ISSUE THREAD

**Issue by jbrooksuk** [laravel/nova-issues#1829]
![image](https://user-images.githubusercontent.com/246103/63171485-9825f400-c033-11e9-84e8-bdb892347766.png)

The blank space appears when there are no actions available.

**Comment by dillingham** [comment]
![extra-space](https://user-images.githubusercontent.com/29180903/63219416-9d706500-c13f-11e9-9931-8e6dda8a26c1.png)

There's also extra space when search is not displayed
