### ISSUE TITLE
Weird result in Value Metric (New Users)

### ISSUE THREAD

**Issue by carnevalle** [laravel/nova-issues#183]
Laravel Nova: v1.0.6

I just tried adding a NewUsers value metric to my index page.

Calculation
`
return $this->count($request, User::class);
`

The values returned are these
`
(
    [value] => 1109
    [previous] => 367
    [previousLabel] => 
    [prefix] => 
    [suffix] => 
)
`

This results in the following card
<img width="364" alt="skaermbillede 2018-08-25 kl 13 33 26" src="https://user-images.githubusercontent.com/54747/44617877-c8491580-a86b-11e8-9724-becdedadda7c.png">

If I understand this correct, it returns 1.11 thousands. This doesn't seem like the most accurate or readable way to write 1109 users. 

Anyway I can control this?

**Comment by Andy-Baker** [comment]
It's done client side with Vue, so for now you'd need to make your own card to get it exactly as required.

Some formatting options would be nice for the built-in cards though I agree.

**Comment by davidhemphill** [comment]
Sorry, no plans to change how the labeling works. Feel free to create a customized version of the metric if you'd like.
