### ISSUE TITLE
Exceptions do not appear in Telescope

### ISSUE THREAD

**Issue by mrvnklm** [laravel/nova-issues#1830]
Exceptions thrown by Nova are shown as Toast notification, but don't appear in Laravel Telescope.
Is there a way to keep the default exception behaviour in addition to the native Nova exception handling?

**Comment by jbrooksuk** [comment]
Exceptions log into Telescope for me:

![image](https://user-images.githubusercontent.com/246103/63250832-72cbfc80-c264-11e9-939c-494ae378c3eb.png)

This is based on an action where the `handle` method is:

```php
throw new Exception('Sike!');
```
