### ISSUE TITLE
Title of Resource Attach show undefined

### ISSUE THREAD

**Issue by gustavowiller** [laravel/nova-issues#1831]
- Laravel Version: 5.8.32
- Nova Version: 2.0.11
- PHP Version: 7.1
- Database Driver and Version: mysql 5.7

### Description

When I declare any field with same `attribute`  before the field `BelongsToMany`, then the title of  
"Attach :Resource" is undefined

![Captura de tela de 2019-08-16 14-57-42](https://user-images.githubusercontent.com/690672/63187983-91e54700-c036-11e9-90ac-582692889c4a.png)

I guess the specify problem is because the method `findFieldByAttribute` of class `FieldCollection` return only the first component of Resource.
If I change the order of fields and declare de `BelongToMany` first, then the title is rendered.

### Steps To Reproduce
1 - Create a Resource
2 - Define any field with any attribute, lets call `example_attribute`.
3 - Then, Define the field "BelongsToMany" with same attribute `example_attribute` **after** the "any field" 
4 - Access at browser the attach view render by BelongsToMany.
5 - Then, note that the title of resource is "undefined"

```
<?php

namespace App\Nova;

...
use Laravel\Nova\Fields\BelongsToMany;

class ExampleResource extends Resource
{
    ...
    public function fields(Request $request)
    {
        return [
            ...
            Text::make('Any Text', 'example_attribute'),
            BelongsToMany::make('Title', 'example_attribute', ResourceRelation::class)
            ...
        ];               
    }
    ...
}
```

**Comment by jbrooksuk** [comment]
Confirmed. Thanks

**Comment by dkulyk** [comment]
Need to check field type. This check ignored in a lot places :(

**Comment by davidhemphill** [comment]
I'm not understanding how this is a bug you would encounter in a real-life situation. Someone care to explain how this isn't just one of those "if you configure Nova wrong it does weird things" type of issues?

**Comment by henryavila** [comment]
Hi, I'm facing the same situation. In my case, I use `dillingham/nova-attach-many` to attach many in create/edit screen (since Nova don't provide this funcionality)

Here's a sample code

```
<?php

namespace App\Nova;

...
use NovaAttachMany\AttachMany;
use Laravel\Nova\Fields\BelongsToMany;

class ExampleResource extends Resource
{
    ...
    public function fields(Request $request)
    {
        return [
            ...
            AttachMany::make('Title', 'example_attribute', ResourceRelation::class),
            BelongsToMany::make('Title', 'example_attribute', ResourceRelation::class)
                   ->exceptOnForms(),
            ...
        ];               
    }
    ...
}
```


Now I know that if I move BelongsToMany before AttachMany I fix the undefined error, but it's certanly a bug. may be not a critical (when dsicover how to fix), but is a bug, because we can't release the app in production with the undefined error.

And it will take a lot of time until someone discover the reason of the unbdefined. If you plan to not resolve this for now, should at least add in doc the information that if using BelongsToMany with any other field with the same attribute, the BelongsToMany  should go first. It will save a lot of time to many people.

**Comment by jaapboerma** [comment]
> Now I know that if I move BelongsToMany before AttachMany I fix the undefined error, but it's certanly a bug. may be not a critical (when dsicover how to fix), but is a bug, because we can't release the app in production with the undefined error.
> 
> And it will take a lot of time until someone discover the reason of the unbdefined. If you plan to not resolve this for now, should at least add in doc the information that if using BelongsToMany with any other field with the same attribute, the BelongsToMany should go first. It will save a lot of time to many people.

Same situation here, also using `dillingham/nova-attach-many`.

Thank you very much for your comment. This resolved my issue, at least from the clients perspective. I know this is not a fix, but it's totally acceptable.

**Comment by davidhemphill** [comment]
Closed due to inactivity. If the issue still persists, feel free to post a new issue with the requested information above. Thanks!

**Comment by marijnhurkens** [comment]
@davidhemphill What do you mean with "the requested information above"? This bug is still there..

**Comment by riddla** [comment]
@davidhemphill: Same for me, in conjunction with  `Techouse\SelectAutoComplete\SelectAutoComplete` and Nova `3.0.1`.

**Comment by genesiscz** [comment]
@davidhemphill Care to maybe reopen this, considering @jaapboerma shown a real life example?

**Comment by davidhemphill** [comment]
If someone can reproduce this without using a 3rd-party package, then I'll open it back up.

**Comment by genesiscz** [comment]
Why is it problem it gets reproduced only with 3rd party packages? It's an issue neverthless

**Comment by davidhemphill** [comment]
Because you can't expect us to be responsible for fixing an issue with a 3rd-party package. :-)

**Comment by genesiscz** [comment]
I dig deeper to make our life a bit easier:

Nova makes request to nova-api/<resource>/field/<relatableDuplicatedField>

FieldController take all available fields without filtering them by RelatableField 

```
$request->newResource()
                    ->availableFields($request)
                    ->findFieldByAttribute($request->field, function () {
                        abort(404);
                    })
```

While for example AssociatableController filters them first:

```
        $field = $request->newResource()
                    ->availableFields($request)
                    ->whereInstanceOf(RelatableField::class)
                    ->findFieldByAttribute($request->field);
```

So it kinda looks like an issue with nova taking the first field of that attribute name without making sure it is the RelatableField. Yes, it is kind of unexpected edge case, which can, in these situations, happen. I can confirm that adding `->whereInstanceOf(RelatableField::class)` after availableFields fixed this issue.

**Comment by genesiscz** [comment]
I am sorry to bother you again but I want to keep nova update and I'd like to not have to fix this in place all the time. 
@davidhemphill  

I can even send a PR if you confirm this

**Comment by jbrooksuk** [comment]
We'd love a PR, @genesiscz :)

**Comment by genesiscz** [comment]
@gustavowiller @riddla @marijnhurkens @jaapboerma @henryavila
Guys this issue has actually been resolved by my PR. I guess it's gonna get into release soon! :)

**Comment by davidhemphill** [comment]
Had to revert the PR because it broke fetching details about non-relatable fields. :-(

**Comment by genesiscz** [comment]
Not on PC right now so I can't look into this more deeply, but what's the other usages for this controller other than relatable?

**Comment by davidhemphill** [comment]
It's also used in removing `File` fields.

**Comment by genesiscz** [comment]
Could new API endpoint field-relatable be an option, given its non-breaking change?

**Comment by davidhemphill** [comment]
Sure :-)

**Comment by rmsj** [comment]
Latest version still have this problem.
Made it working creating a second relationship method on the model, with different name, of course. Not beautiful, but need both fields, can't have one as "undefined"

**Comment by genesiscz** [comment]
I haven't have time to move up with this, but feel free to take my pull and add the required api endpoint for that

https://github.com/laravel/nova/pull/871

**Comment by midorikocak** [comment]
any updates on this?

**Comment by alberto-bottarini** [comment]
Any news? It's so annoying...

**Comment by genesiscz** [comment]
@alberto-bottarini Make it less annoying and create a pull request, based on mine. https://github.com/laravel/nova/pull/871

**Comment by alberto-bottarini** [comment]
I'll take a look

**Comment by infostreams** [comment]
This is still an issue. Re-open please!

**Comment by crynobone** [comment]
We no longer releasing bugfixes for Laravel Nova 2, please upgrade to Nova 3. 

If you still have the issue on Laravel Nova 3 please create a new issue with full description on how to reproduce the issue.

**Comment by infostreams** [comment]
It's unfortunately still an issue on 3.15

However, I'm not sure anymore if it's related to Nova or to a plugin. I have the BelongsToManyField plugin installed, and if I remove the one field that is using it (even though I'm only displaying it on the index), then this behavior doesn't occur. If I remove the field with the BelongsToManyField, it doesn't show "attach undefined". Hrmpf. Close?

**Comment by crynobone** [comment]
> I have the BelongsToManyField plugin installed, and if I remove the one field that is using it (even though I'm only displaying it on the index), then this behavior doesn't occur. If I remove the field with the BelongsToManyField, it doesn't show "attach undefined". Hrmpf. Close?

We recently solved few issues on 3.x regarding "Undefined" title so I could be integration issue with 3rd party. But if you can recreate the issue on a fresh Laravel Nova 3 I will relook at the issue again.

**Comment by infostreams** [comment]
I first installed Nova last Tuesday, fairly fresh I'd say ;-) I also just updated to 3.15. My Laravel is still 7.x though, but I'd be surprised if that's the issue.

If I were to guess you could reproduce by installing Nova 3.15 and `benjacho/belongs-to-many-field:1.8`, and then having the following fields:

Lessoncomponent resource:
```php
<?php

namespace App\Nova;

use Benjacho\BelongsToManyField\BelongsToManyField;
use Illuminate\Http\Request;
use Laravel\Nova\Fields\BelongsToMany;
use Laravel\Nova\Fields\ID;

class Lessoncomponent extends Resource
{
    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static $model = \App\Models\Lessoncomponent::class;

    /**
     * The single value that should be used to represent the resource when being displayed.
     *
     * @var string
     */
    public static $title = 'title';

    /**
     * The columns that should be searched.
     *
     * @var array
     */
    public static $search = [
        'id', 'title',
    ];

    /**
     * Get the displayable label of the resource.
     *
     * @return string
     */
    public static function label() {
        return 'Lesonderdelen';
    }

    /**
     * Get the displayable singular label of the resource.
     *
     * @return string
     */
    public static function singularLabel() {
        return 'Lesonderdeel';
    }

    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [
            ID::make(__('ID'), 'id')->sortable(),

            BelongsToManyField::make('Oefeningen', 'exercises', Exercise::class)->optionsLabel('title')->onlyOnIndex(),

            BelongsToMany::make('Oefeningen', 'exercises', Exercise::class)->hideFromIndex(true),
        ];
    }
}
```


And then the Exercises resource:
```php
<?php

namespace App\Nova;

use Illuminate\Http\Request;
use Laravel\Nova\Fields\ID;

class Exercise extends Resource
{
    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static $model = \App\Models\Exercise::class;

    /**
     * The single value that should be used to represent the resource when being displayed.
     *
     * @var string
     */
    public static $title = 'nova_title';

    /**
     * The columns that should be searched.
     *
     * @var array
     */
    public static $search = [
        'id', 'title', 'description',
    ];

    /**
     * Get the displayable label of the resource.
     *
     * @return string
     */
    public static function label()
    {
        return 'Oefeningen';
    }

    /**
     * Get the displayable singular label of the resource.
     *
     * @return string
     */
    public static function singularLabel()
    {
        return 'Oefening';
    }

    /**
     * Get the fields displayed by the resource.
     *
     * @param \Illuminate\Http\Request $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [
            ID::make(__('ID'), 'id')->sortable(),
        ];
    }
}
```

I just confirmed that in this very minimal setup, the problem occurs for me.

**Comment by infostreams** [comment]
So it seems to me that it's a bug that is IN Nova, but triggered by an external plugin.

**Comment by genesiscz** [comment]
Try to swap the lines :)

**Comment by infostreams** [comment]
That's ridiculous, and bizarre, and it's still a bug - but it works.

**Comment by crynobone** [comment]
> That's ridiculous, and bizarre, and it's still a bug - but it works.

As mention earlier, Please create new issue if you have the problem.
