### ISSUE TITLE
How can I disable action log when creating or updating.

### ISSUE THREAD

**Issue by zhouzishu** [laravel/nova-issues#1832]
I have already use spatie/laravel-activitylog to log model changes. How can I disable Nova action log when creating or updating.

**Comment by dillingham** [comment]
Try adding this to your NovaServiceProvider
```php
use Laravel\Nova\Actions\ActionEvent;
```
```php
ActionEvent::saving(function ($actionEvent) {
    if(in_array($actionEvent->name, ['Create', 'Update']) {
        return false;
    }
});
```

**Comment by zhouzishu** [comment]
> Try adding this to your NovaServiceProvider
> 
> ```
> use Laravel\Nova\Actions\ActionEvent;
> ```
> 
> ```
> ActionEvent::saving(function ($actionEvent) {
>     if(in_array($actionEvent->name, ['Create', 'Update']) {
>         return false;
>     }
> });
> ```
> 
> Ps.. other model related events can be found in ActionEvent model

Thank you so much!

**Comment by vesper8** [comment]
did something change? Adding the above to my NovaServiceProvider inside the boot method has no effect.. it continues to try and insert into the action_events table and produces an error because I'm using a uuid as primary key

**Comment by gustav1105** [comment]
This is still an issue

**Comment by sreenia806** [comment]
for me too, It didn't work. I tried adding an observer for action_events model.

**Comment by flytedan** [comment]
Also having an issue. UUIDs are not compatible w/ the action event logging. Very annoying.

**Comment by askorad** [comment]
@flytedan if you don't care about recording the log, you can disable it in the controller itself :
1. Open  `ResourceUpdateController` in `Laravel\Nova\Http\Controllers`
2. Disable action log by removing or commenting  the line 
` Nova::actionEvent()->forResourceUpdate($request->user(), $model)->save();`
Repeat this for each controller you wish

**Comment by vrajroham** [comment]
@askorad You can just return `false` saving and it will stop logging.

```php
ActionEvent::saving(function ($actionEvent) {
    return false;
});
```

**Comment by dmlogic** [comment]
I have also come across this problem when deleting resources and consider it closer to a bug that a feature request. I would prefer not to have the `action_events` data table in my schema at all.

I can see that the `ResourceDestroyController` accesses the `action_events` table directly using the DB facade, so I have no way to disable the event handlers on the `ActionEvent` model

**Comment by roelgeelen** [comment]
@dmlogic I had the same problem. I fixed it with overriding the `ResourceDestroyController` with my new controller where i removed the code where the `actionEvent` is used.

`
$this->app->bind(
   ResourceDestroyController::class, 
   YourNewController::class
);
`

**Comment by mmerlijn** [comment]
You can disable the log in action_events in config nova.php
`    'actions' => [
        'resource' => null, //ActionResource::class,
    ],`

**Comment by theGC** [comment]
The current version (4.0) of Nova's migrations test for your `Builder::$defaultMorphKeyType` and set `actionable_id` `target_id` and `model_id` column types based on this:

```
...
$table->morphs('actionable');
$table->morphs('target');
...
if (Builder::$defaultMorphKeyType === 'uuid') {
    $table->uuid('model_id')->nullable();
} elseif (Builder::$defaultMorphKeyType === 'ulid') {
    $table->ulid('model_id')->nullable();
} else {
    $table->unsignedBigInteger('model_id')->nullable();
}
```

Therefore, you can update your `defaultMorphKeyType` within AppServiceProvider:

_AppServiceProvider_
```
public function boot()
{
    ...
    //  User UUIDs
    Builder::morphUsingUuids();

    //  OR User ULIDs
    // Builder::morphUsingUlids();
    ...
}
```

For mySQL `morphUsingUuids` generates char(36) columns for `actionable_id` `target_id` and `model_id` which will store both UUIDs and autoincrementing IDs (only it'll do so as a string, not as integers). I haven't seen any issues with it, but am still testing, hope it helps.

**Comment by alfhh** [comment]
Thanks @theGC that worked!

Just wanted to shared that I had to publish Nova's migrations and then migrate for this to work:

```
php artisan vendor:publish --tag=nova-migrations
php artisan migrate

```
