### ISSUE TITLE
Resource label is being changed into something else

### ISSUE THREAD

**Issue by gavinhewitt** [laravel/nova-issues#1833]
- Laravel Version: 5.7
- Nova Version: 2.0.11
- PHP Version: 7.3

### Description

When you add a label to a resource it somehow gets changed, I'm guessing because of automatic pluralization. I would expect anything being set 'hard' as label not to be changed. In this case I've added the Dutch word for 'terms'. The navigation gets it right however.

Edit: it looks to be happening only on detail and edit page, index is fine.

### Steps To Reproduce
Add this label to a resource. 
```
public static function label() {
        return 'Termen';
    }
```

![image](https://user-images.githubusercontent.com/1969103/63212659-4733ff80-c108-11e9-980b-d3962307b333.png)

**Comment by jbrooksuk** [comment]
You need to override the `singularLabel` method too:

```php
/**
 * Get the displayable singular label of the resource.
 *
 * @return string
 */
public static function singularLabel()
{
    return Str::singular(static::label());
}
```
