### ISSUE TITLE
Is it possible to separate a Resource into two different resource view by their types

### ISSUE THREAD

**Issue by shingsoso** [laravel/nova-issues#1838]
I have a User Model with three types , I want to separate Users into three resources Panel to manage , For Example : 

1. Customers 
2. Staff 
3. Manager

instead of one single User Resource View . 

p.s I do not want solution like adding a filtering onto User Resource

**Comment by jbrooksuk** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](https://larachat.co/).
