### ISSUE TITLE
Rule::unique() doesn't work with ->ignore()

### ISSUE THREAD

**Issue by hivokas** [laravel/nova-issues#184]
`->updateRules(['unique:configs,name,{{resourceId}}'])` - works like a charm.
`->updateRules([Rule::unique('configs', 'name')->ignore('{{resourceId}}')])` - ignores `->ignore('{{resourceId}}')` part.

**Comment by tillkruss** [comment]
This works for me:

```php
->creationRules("unique:configs,slug,NULL,id,site_id,{$request->site}")
->updateRules("unique:products,slug,{{resourceId}},id,site_id,{$request->site}"),
```

**Comment by davidhemphill** [comment]
You will have to manually pass the parameter into any Rule objects.

**Comment by jhm-ciberman** [comment]
This keeps failing.

I have tried both:

```php
Text::make('Sku')->sortable()->rules([
    'max:255', 
    "unique:products,sku,$this->resource->id",
]),
```
and: 
```php
use Illuminate\Validation\Rule;

Text::make('Sku')->sortable()->rules([
    'max:255', 
    Rule::unique('products', 'sku')->ignore($this->resource->id),
]),
```
And none of them works. Also, I've tried other combinations. But the validation keeps ignoring the `->ignore($this->resource->id)` part. 

Any suggestion?

**Comment by jhm-ciberman** [comment]
Update:

It seems you need to use the exact string:
```php
->rules('unique:products,sku,{{resourceId}}')
```

**Comment by krns** [comment]
@jhm-ciberman it's already documented: https://nova.laravel.com/docs/2.0/resources/validation.html#update-rules

**Comment by jhm-ciberman** [comment]
Oh, sorry. I miss that. Thanks! 😄

**Comment by sijones-uk** [comment]
In case anyone else needs to use the `Rule` class as per the OP, in the `updateRules` method, the `Rule` class should be chained with an `ignore` method looking like this:

```
Rule::unique('configs', 'name')
    ->ignore($request->resourceId)
```
