### ISSUE TITLE
Cannot read property 'delimiters' of undefined after upgraded to v2.0.10 from v2.0.09

### ISSUE THREAD

**Issue by phoenixg** [laravel/nova-issues#1840]
- Laravel Version: 5.8.*
- Nova Version: 2.0.10
- PHP Version: 7.1
- Browser type and version: Chrome 76.0.3809.100

![image](https://user-images.githubusercontent.com/990040/63313551-767c8380-c337-11e9-86df-03c1060f6de4.png)

After I changed `config/app.php`:

```php
'locale' => 'zh-CN',
```

to 

```php
'locale' => 'en',
```

problem solved. But I still want my locale back to `zh-CN`.

**Comment by jbrooksuk** [comment]
This should be fixed in the next release.

**Comment by pelmered** [comment]
It's not fixed in `v2.0.11`. When is the next version?
All my metrics are broken...

**Comment by jbrooksuk** [comment]
v2.1.0 is out from yesterday.

**Comment by pelmered** [comment]
Ah, thanks!

**Comment by phoenixg** [comment]
Problem resolved in `v2.1.0`, confirmed.
