### ISSUE TITLE
Split username in firstname & lastname

### ISSUE THREAD

**Issue by Bux666** [laravel/nova-issues#1841]
- Laravel version: 5.8.21
- Nova version: 2.0.11
- PHP version: 7.3

### Description

Please split the **username** in **firstname** and **lastname**. This makes it possible e.g. to sort on the lastname column.
I altered my Nova installation to have this feature but because it needs changes in the Nova core, every Nova update makes the work come back.

The changes need to be done in the Laravel User Migration, in the Laravel User Model, in the Nova User Resource and in the core Nova Class (defaultCreateUserCommandCallback() & defaultCreateUserCallback()).

**Comment by jbrooksuk** [comment]
Nova (and Laravel) comes packaged with defaults that you are free to change.
