### ISSUE TITLE
Deleting a child resource does not redirect to parent details page

### ISSUE THREAD

**Issue by unlikenesses** [laravel/nova-issues#1842]
- Laravel Version: 5.8.22
- Nova Version: 2.0.11
- PHP Version: 7.1
- Operating System and Version: Mac Os 10.13.6

As [requested](https://github.com/laravel/nova-issues/issues/1285#issuecomment-517170243) by @jbrooksuk, I am creating a new ticket for this old issue.

### Description:

I have a resource `Foo`:

```
public function fields(Request $request)
{
    return [
        HasMany::make('Bars')
    ];
}
```

and a resource `Bar`:

```
public function fields(Request $request)
{
    return [
        BelongsTo::make('Foo'),
        Text::make('Title')
    ];
}
```

In my Nova admin, I can go to the a particular `Foo`, click "Create Bar", and on the "New Bar" page enter a `title` and click "Create Bar". The `Bar` is then created and associated with the `Foo` correctly. I am then on the "Details" page for the newly created `Bar`. If I now click the "Delete" button, the `Bar` is deleted but instead of being returned to its parent `Foo` page, it returns me to a list page for all `Bars`. Since `Bars` only make sense in relation to their parent, this page should never really be seen.

**Expected:** After deleting a child resource, I should be redirected to the parent's detail page.

**Actual:** After deleting a child resource, I am redirected to a listings page for that resource.

**Comment by jbrooksuk** [comment]
Thanks for opening the issue, @unlikenesses. I've had a look into this and this is not an issue.

Nova doesn't know that the `Bar` resource is exclusive to `Foo`, so wouldn't know that it should redirect back to the detail page instead of the `Bar` index.
