### ISSUE TITLE
Nova Docs Site - No version displayed in search results

### ISSUE THREAD

**Issue by king724** [laravel/nova-issues#1843]
When searching the Nova documentation website, the search results don't show the Nova version in the result. Unfortunately, this makes it easy to jump from v2.0 to v1.0 of the docs inadvertently.

I would prefer to have the search only show the results from the version of Nova you're browsing. e.g. v2.0 results only show up when you're browsing `https://nova.laravel.com/docs/2.0/`

<img width="1076" alt="Screenshot 2019-08-20 13 41 02" src="https://user-images.githubusercontent.com/350488/63383232-44781b00-c351-11e9-93e3-e6e627b24171.png">

**Comment by jbrooksuk** [comment]
Funnily enough, @davidhemphill and I were talking about the docs and this exact issue only yesterday.

**Comment by jbrooksuk** [comment]
The documentation search now only searches v2.0 documentation.
