### ISSUE TITLE
Call to member function getForeignKeyName() on string when BelongsTo named "group"

### ISSUE THREAD

**Issue by bcorcoran** [laravel/nova-issues#1845]
- Laravel Version: 5.8.33
- Nova Version: 2.1.0
- PHP Version: 7.3

### Description

As the title says, I am getting `Call to member function getForeignKeyName() on string` when attempting to use a relationship named "group".

The error appears to be occurring in nova/src/Fields/Field.php at line ~492

```php
public function sortableUriKey()
    {
        $request = app(NovaRequest::class);
 
        switch (get_class($this)) {
            case BelongsTo::class:
/*492*/         return $request->newResource()->{$this->attribute}()->getForeignKeyName();
            default:
                return $this->attribute;
        }
    }
```

### Steps To Reproduce

Have two models with a BelongsTo relationship. Use the method name "group" to access said relationship, i.e.:

```php
// Model A
public function group()
{
   return $this->belongsTo('Path\To\Other\Model\Group');
}
```

```php
// Nova/Modal A
...
BelongsTo::make('Group', 'group', \Path\To\Nova\Group::class),
...
```

### Steps I took to test

I renamed 'group' to 'groupa' (or literally anything else, even "groups") and it starts working immediately. I have no field named 'group' so there are no collisions with the method name in my model.

**Comment by jbrooksuk** [comment]
Ah, yes, I believe this is now fixed in https://github.com/laravel/nova/commit/96b1e32485f7173f98c192d0f565cdf5dc29b299

I'll see about getting a patch release out later today.

**Comment by ArmChaCib** [comment]
@bcorcoran HI, did you find the solution? I´ve the same issue
