### ISSUE TITLE
Cannot create/edit resources

### ISSUE THREAD

**Issue by adrenaxus** [laravel/nova-issues#1846]
I cannot create / edit resources anymore, the field list is completely empty. It is exactly this issue: https://github.com/laravel/nova-issues/issues/1720

I already force-published all of the assets and it still doesn't work, so I guess it must indeed be a 3rd party package but I updated all of them and didnt find any outdated ones. There is no debug information in network panel, I even tried removing every field from my Resource but still no luck... How can I find out which package is causing the error?

Thanks!

**Comment by bcorcoran** [comment]
Are you sure your browser has not cached the assets?

Aside from that, unfortunately, the quickest thing to do is disable all custom plugins and re-enable each one until you isolate which one it is...

**Comment by adrenaxus** [comment]
Thanks for your reply! I'm sure the browser has not cached the views because I just tried from a different workplace and the issue persists. How exactly would you "disable" a plugin? By removing it from composer.json and running `composer update`?

**Comment by jbrooksuk** [comment]
You need to remove your Nova plugins, typically from the NovaServiceProvider.

**Comment by jbrooksuk** [comment]
Since we know that resource management is working, we believe it’ll be a plug-in issue, so I’m going to close as a support question. If you find the offending plugin please open an issue on that project. 

This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](https://larachat.co/).

**Comment by adrenaxus** [comment]
I do not have any special plugins in NovaServiceProvider besides the Dnicuum/CustomEmailSender plugin which I'm pretty sure is not causing the issue because it is working fine. My question: is there no logfile or something where I can get a hint to what is causing the error. Having absolutely no kind of debug information is pretty brutal,especially if I have to manually disable every plugin because just removing it from composer.json will crash the app anyway and I have to remove every reference to the disabled plugin in my code.

**Comment by jbrooksuk** [comment]
You can check the browser console and the Laravel logs?

**Comment by adrenaxus** [comment]
I was not able to isolate the issue even trying to meticolously deactivate every plugin and removing every reference from my code. The lack of any proper error message and/or debug information forced me to revert to an earlier Version. No information in console, no errors in laravel logs. I would suggest to provide at least some feedback/error message if a 3rd party plugin fails to load properly. Thanks for the help tho.
