### ISSUE TITLE
Custom nova card  doesnt show up in the dashboard after visit other resource

### ISSUE THREAD

**Issue by abr4xas** [laravel/nova-issues#1848]
- Laravel Version:  5.8.33
- Nova Version: 2.1.0
- PHP Version: 7.2
- Database Driver and Version: #.#
- Operating System and Version: Ubuntu 18.04.3 LTS
- Browser type and version: Version 76.0.3809.100 (Official Build) (64-bit)

### Description

I have a small custom [nova card](https://novapackages.com/packages/abr4xas/nova-hello-dolly) this card it is shown the first time on the dashboard then, if I enter some other resource and go to the dashboard it is not shown

```
Request URL: https://livesite.tld/nova-api/cards
Request Method: GET
Status Code: 200 
``` 
```json

// response

[
    {
        "width":"1\/3",
        "component":"nova-hello-dolly",
        "prefixComponent":false,
        "onlyOnDetail":false
    }
]
```

### Steps To Reproduce

IDK, maybe installing my custon nova card and test?

**Comment by jbrooksuk** [comment]
I was unable to replicate this issue.

This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](https://larachat.co/).

**Comment by abr4xas** [comment]
Hey @jbrooksuk I wasn't asking for general development questions but thanks anyways

**Comment by jbrooksuk** [comment]
I don't believe the issue to be within Nova as I was unable to replicate it is all :)

**Comment by tumainimosha** [comment]
Hello @abr4xas facing similar issue. Did you get any success with this.

For my case I do not have any custom card on my dashboard. 

When I navigate away from dashboard and back, no content is rendered on dashboard.

**Comment by abr4xas** [comment]
Hey @tumainimosha I just update my project to the latest version and works

**Comment by tumainimosha** [comment]
@abr4xas Thanks for tip. 

After I updated to latest version and it solved the issue.

Thank again.
