### ISSUE TITLE
Fields/HasMany.php: PHPDoc tag @return has wrong type-hint

### ISSUE THREAD

**Issue by VTumanov** [laravel/nova-issues#1849]
- Nova Version: master

### Description
code:analyse generate error, need change return type to $this

```
    /**
     * Set the displayable singular label of the resource.
     *
     * @return string
     */
    public function singularLabel($singularLabel)
    {
        $this->singularLabel = $singularLabel;
        return $this;
    }
```

### Steps To Reproduce

https://github.com/laravel/nova/blob/2.0/src/Fields/HasMany.php 
Look at line 93

**Comment by mvdnbrk** [comment]
I've made a PR to fix this.
