### ISSUE TITLE
Tinker now aliases to App\Nova\User instead of App\User

### ISSUE THREAD

**Issue by m2de** [laravel/nova-issues#185]
I realise this isn't really an issue but more of a very minor annoyance. After installing Nova, Tinker will default to binding `User` to `App\Nova\User` instead of the expected `App\User`.

```sh
Psy Shell v0.9.7 (PHP 7.1.14 — cli) by Justin Hileman
>>> User::first()
[!] Aliasing 'User' to 'App\Nova\User' for this Tinker session.
```

**Comment by davidhemphill** [comment]
Tinker uses whatever comes first in the composer autoloader so we don't really have any control over that.
