### ISSUE TITLE
BelongsTo('Media') causes unexpected error

### ISSUE THREAD

**Issue by wlarch** [laravel/nova-issues#1850]
- Laravel Version: v5.8.33
- Nova Version: v2.0.11
- PHP Version: PHP 7.2.21
- Database Driver and Version: MySQL 5.7.27
- Operating System and Version: Linux centiva 4.4.0-75-generic #96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Browser type and version: Chrome Version 76.0.3809.100

### Description

When having a ``BelongsTo::make('Media')`` field Nova returns a ``Class 'App\Nova\Medium' not found``. I understand this problem is related to Media/Medium translation. See the following related issue : 

https://github.com/laravel/framework/issues/8673

The table name was already added to the Media.php model : ``protected $table = 'medias';``

Still we get this error by Nova. The problem does not happen when we use : 
``BelongsTo::make('Picture', 'media', 'App\Nova\Media')``

Bug or misunderstanding ?

### Steps To Reproduce

1. Database has a "medias" table for which another table relate to and Media.php model exist.
Example : products table with media_id column

1.1 Create relationship : 
``public function media()
{
        return $this->belongsTo('App\Media');
}``

2. Create a Product resource with ``BelongsTo::make('Media')`` field.

**Comment by dillingham** [comment]
Media is plural form of Medium to the pluralizer

**Comment by jbrooksuk** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](https://larachat.co/).
