### ISSUE TITLE
Results per page doesn't respect first value of perPageOptions resource property

### ISSUE THREAD

**Issue by demency** [laravel/nova-issues#1851]
- Laravel Version: 5.8.33
- Nova Version: 2.1.0
- PHP Version: 7.3.8
- Database Driver and Version: MySQL 5.7
- Operating System and Version: Ubuntu 18.04.1
- Browser type and version: Chrome Version 76.0.3809.100
- Reproduction Repository: -

### Description

By setting $perPageOptions = [10, 20, 40] in a Nova resource, the default pagination doesn't respect the first value. So, always use 25 per page. 

### Steps To Reproduce

- Create a fresh project and add nova
- Create a nova resource and set the perPageOptions static property with the an first value different of 25.
- Go to resource listing and see the per page result is 25.

**Comment by jbrooksuk** [comment]
This is the case because the pagination options come back from the resource itself, and so we wouldn't know how many to fetch until we've fetched the resource, so the 25 is fixed so that we're able to fetch something.

**Comment by demency** [comment]
This should be configurable per resource 🤔

**Comment by jbrooksuk** [comment]
I'm unsure how we could make this work though, not without adding an extra request.

The problem is that until we've fetched the resources, Nova doesn't know how many to have fetched. When you click on a resource in the sidebar, the following happens:

1. Fetch the resource data, this includes fields and any data that comes with it. This data is paginated at 25 results per page by default.
2. Fetch the lens
3. Fetch the cards
4. Populate the UI with the data we've fetched (including the per page options)

Essentially, we don't know how many resources Nova should fetch until it's returned something.

**Comment by demency** [comment]
Well, modifying the ResourceIndexController on line 45:

### Original

```php
    protected function paginator(ResourceIndexRequest $request, $resource)
    {
        return $request->toQuery()->simplePaginate(
            $request->viaRelationship()
                        ? $resource::$perPageViaRelationship
                        : ($request->perPage ?? $resource::perPageOptions()[0]) // Line 45
        );
    }
```

### Patched

```
    protected function paginator(ResourceIndexRequest $request, $resource)
    {
        return $request->toQuery()->simplePaginate(
            $request->viaRelationship()
                        ? $resource::$perPageViaRelationship
                        : ($request->perPage > $resource::perPageOptions()[0] 
                            ? $resource::perPageOptions()[0] 
                            : $request->perPage)
        );
    }

```

This will be respect the first perPageOptions.

**Comment by m-triassi** [comment]
Noticed this bug in my project as well, and came to the same conclusion @demency has. @jbrooksuk May he or i just submit a PR containing that fix?

**Comment by jbrooksuk** [comment]
Please submit a PR if you can!

**Comment by demency** [comment]
PR created +1

**Comment by demency** [comment]
To solve this issue a change must be made in nova-js repository. Related to the [PerPageable.js](https://github.com/laravel/nova-js/blob/master/src/mixins/PerPageable.js) file of the mixins. There you can find that the number 25 is by default. If you assign it by default as null, the nova-api can be assigned as the first value of resources per page. Ideally checking that the value exists in the list.

**Comment by demency** [comment]
This will be fixed by https://github.com/laravel/nova/pull/625 🎉🎉🎉🤙
