### ISSUE TITLE
Defining the displayable name in relationships fields fails

### ISSUE THREAD

**Issue by salomonsanz** [laravel/nova-issues#1856]
- Laravel Version: 5.8.33
- Nova Version: 2.1.1
- PHP Version: 7.1.23

### Description

When i define the displayable name of the field in the relationships fields, always throws error.
Should be pretty simple, like the example in the docs:

<img width="763" alt="Captura de pantalla 2019-08-25 a las 21 22 22" src="https://user-images.githubusercontent.com/24811202/63654709-81dc0e80-c77e-11e9-8d72-767785f144bc.png">

I am already using this feature in other types of fields without problems, but in relationship fields i always have the same problem:

<img width="304" alt="Captura de pantalla 2019-08-25 a las 21 28 42" src="https://user-images.githubusercontent.com/24811202/63654800-763d1780-c77f-11e9-9bff-14923dbb5900.png">
<img width="299" alt="Captura de pantalla 2019-08-25 a las 21 28 58" src="https://user-images.githubusercontent.com/24811202/63654802-763d1780-c77f-11e9-87c7-60027e60d267.png">

I tried with all relation types (hasOne, hasMany, etc) with the same result.

### Steps To Reproduce

1. Create a Relationship field
2. Define two parameters, the first, the display name diferent from second (the relation).

**Comment by m-lotze** [comment]
If your related class is not named Curso, you need to define the classname as the third parameter:

```
BelongsTo::make('Curso', 'grade', Related::class)
```

**Comment by salomonsanz** [comment]
perfect! Thanks, i missed this part.
