### ISSUE TITLE
Method Trix::stacked does not exist

### ISSUE THREAD

**Issue by PsyLogic** [laravel/nova-issues#1857]
- Laravel Version: 5.8.33
- Nova Version: 2.1.0
- PHP Version: 7.2

### Description

got an exception when calling ```stacked()``` method on ```Trix``` Field

``` Method Laravel\Nova\Fields\Trix::stacked does not exist ```

### Steps To Reproduce

```php
//...
Trix::make('Content')->stacked(),
```

**Comment by jbrooksuk** [comment]
Stacked elements came in v2.1.1 - https://nova.laravel.com/releases/2.1.1
