### ISSUE TITLE
Bootstrap Theme/Framework Support

### ISSUE THREAD

**Issue by vbasky** [laravel/nova-issues#1859]
Its great that Laravel Nova is using Tailwind while the Laravel Framework itself uses Bootstrap by default. though there is an option to use presets in the framework to switch to Tailwind there isn't a similar option on Nova. 

I want to give a consistent UX to the users hence the request to have a default Bootstrap theme for Nova

Laravel Nova v2.1.1

**Comment by jbrooksuk** [comment]
You are free to override the views and components using whatever framework you like.
