### ISSUE TITLE
Prevent exception messages when using relations in computed fields

### ISSUE THREAD

**Issue by mrvnklm** [laravel/nova-issues#1860]
When using computed field values with relations like this
 `                Text::make('New Value', function () {
                    return $this->product_change->previous_value;
                })->onlyOnDetail()->asHtml(),`
exceptions are thrown when relational views are loaded, because they are loaded without the relations of the actual model.

**Comment by jbrooksuk** [comment]
You need to use the `optional` method:

```
Text::make('New Value', function () { return optional($this->product_change)->previous_value; })->onlyOnDetail()->asHtml()
```
