### ISSUE TITLE
Trix File Uploads and Filestystem Disks - Support sub folders please

### ISSUE THREAD

**Issue by cdrum** [laravel/nova-issues#1862]
Hi,

We use S3 to store asset files, and the Trix plugin for Nova works fine with the Disks config. But, it doesn't seem like we're able to add subfolders so we can keep our s3 (or any destination) clean by putting certain files in different folders. 

It could be great if Nova would allow us to specify a path for Trix file uploads. 
Thanks!

**Comment by dkulyk** [comment]
This has been fixed and will be included in the next release. 👍

**Comment by hilmanski** [comment]
Hi any reference where should we tell the subdirectory? what method to use?
