### ISSUE TITLE
Lens without ID field does not show checkboxes and behaves like everything is checked

### ISSUE THREAD

**Issue by johanvanhelden** [laravel/nova-issues#1863]
- Laravel Version: 5.8.33
- Nova Version: 2.1.0
- PHP Version: 7.2.21
- Database Driver and Version: MySQL 5.7
- Operating System and Version: Ubuntu 18.04.3 LTS
- Browser type and version: Firefox 68.0.2 (64-bit) and Chrome 76.0.3809.132 (64-bit)
- Reproduction Repository: n.a.

### Description

After upgrading to Nova 2.0 we noticed the behaviour of Lenses changed. Our lense did not contain an ID column because our customer did not find that relevant. He was interested in different fields. This was not a problem before. Check-boxes to execute actions still showed up. After upgrading to Nova 2.0 (2.1.0 to be precise) the check-boxes disappeared, the actions showed up in the action drop-down and upon executing actions we noticed the action was executed for all resources in the lens. After debugging this for to long, I noticed that when I added a ID field, everything worked again.

But, like before, I believe lenses should still function properly without an ID column.

### Steps To Reproduce

1. Create the default MostValueableUsers lens: `php artisan nova:lens MostValuableUsers`
2. Add the lens to the Nova `User` Resource.
3. Add a `name` Text field.
4. Note that it works perfectly, all check-boxes still show up:

![Screenshot from 2019-08-28 13-54-09](https://user-images.githubusercontent.com/19389981/63853628-7e719e80-c99b-11e9-8767-e98b3dbe3035.png)

5. Remove the ID field from the lens.
6. Note that the check-boxes disappear now and that, if you have an action attached to the Lens, the action shows up without selecting anything, and if you submit the action, all models are in the collection of the action handle method.

![Screenshot from 2019-08-28 13-54-41](https://user-images.githubusercontent.com/19389981/63853639-83365280-c99b-11e9-85a8-e6641dea08e7.png)

**Comment by dkulyk** [comment]
Without ID you cannot execute actions on selected rows on lenses. Without ID SelectAllMatching activated by default.

**Comment by johanvanhelden** [comment]
That's right, because you can not select rows.

It does work fine on the general resource index, so only on lenses it is broken. 
And also on Nova 1.x it worked fine in the lenses without ID.

**Comment by dkulyk** [comment]
You can try to add ID and hide it from index.

**Comment by jbrooksuk** [comment]
I believe @dkulyk is correct. Nova needs an ID to act on.

**Comment by johanvanhelden** [comment]
@jbrooksuk but why does it work fine on the index itself and only breaks in a lens? It still smells like a bug to me.

**Comment by mdavis1982** [comment]
@jbrooksuk I agree with @johanvanhelden here.

IDs aren't relevant to a user in my case, and showing them would be confusing. I don't show them on the resource index listing and the Select / Select All Matching work properly without needing it.

I believe this is a bug and should be fixed to maintain consistency between resource index listings everywhere else in a Nova app and a lens.

As an aside, if this is not going to be fixed, there is a visual bug whereby the left padding is too big because of the missing checkbox column, so either way, this should be investigated.

**Comment by mdavis1982** [comment]
@jbrooksuk In addition to the above, adding an ID column and attempting to hide it with any of the modifiers doesn't work. For example, the following does not hide the field:

```
ID::make('ID', 'id')->hideFromIndex()
```

None of the following methods make any difference:

```
->hideFromIndex()
->hideFromDetail()
->hideWhenCreating()
->hideWhenUpdating()
->onlyOnIndex()
->onlyOnDetail()
->onlyOnForms()
->exceptOnForms()
```

Something is amiss and it would be really appreciated if this could be reopened and investigated. 😄

**Comment by gbrits** [comment]
Also seeing this minor issue that @jbrooksuk is seeing - ID field cannot be hidden on Lenses with `hideFromIndex()` it can only be omitted. Regular (non-lens) indexes can have IDs hidden.

**Comment by matthewjumpsoffbuildings** [comment]
im also facing this issue - it doesnt make sense to have ids on lenses that are aggregates, but the behaviour of when the actions menu appears is different between a lens and a resource index.

personally i think the actions dropdown should appear at all times if actions are available, and if you run the action without making a selection it should prompt asking if you want to run the action on all entries.

for example im using the DownloadExcel addon, which works on both resource index and lens, but it behaves differently.

**Comment by dkulyk** [comment]
Actions cannot work with selected records if ID is not present.

**Comment by matthewjumpsoffbuildings** [comment]
Yes Im aware of this - but the actions work on _all_ records if ID is not present, the issue I have is that the action menu visibility behaviour is different

For example the DownloadExcel action works on both resource views with IDs, and resource lenses without IDs, however, on the views with IDs the action menu doesnt appear until you select something, wheras on the lense without IDs the action menu is always present. This behaviour is confusing to users, who may visit the lens first, and see the action menu, then visit the resource and the action menu is not there (since they havent selected anything)

**Comment by bakerkretzmar** [comment]
I'm bumping into this issue as well. My users don't need/care about the IDs at all, so I have them hidden everywhere from everyone except me, which works fine everywhere except lenses.

@dkulyk the ID _is_ ‘present’ somewhere—the view/edit/delete buttons at the end of each item's row know what the ID is and work correctly even when the lens has no `ID` field.

**Comment by jbrooksuk** [comment]
If someone is able to test it, I've made some fixes in https://github.com/laravel/nova/pull/745

**Comment by johanvanhelden** [comment]
I'm sorry for the late reply, but I was unable to test it earlier. 

Today I've updated Nova to v2.9.2 but without the ID field, the select all option and the checkboxes are not visible. 

All the assets have been published of course.

**Comment by jbrooksuk** [comment]
The fix has not been released yet, sorry!

**Comment by johanvanhelden** [comment]
Ah, okey @jbrooksuk - no worries. Any indication when this would go live? Because this week it's easy for me to test since I'm working on the project with that issue.

**Comment by jbrooksuk** [comment]
Likely today or next Tuesday :)
