### ISSUE TITLE
UserExperience bug with errors in form submits

### ISSUE THREAD

**Issue by PatricNox** [laravel/nova-issues#1864]
- Laravel Version: 5.8
- Nova Version:  2.0.10
- PHP Version: 7.1
- Operating System and Version: MacOS Mojave
- Browser type and version: Chrome 76

### Description

When getting errors in a resource creation view and the errors are due to fields at the upper side of the page, then the user leaves hanging without any indication of results when hitting submit.

_Example:_
A detail view, you have 10 fields.

Field 3 is required, but has no data.

--> The user is at the bottom, hitting submit.
-----> Nothing happends. 
-------> You scroll up, and see this error.

### Steps To Reproduce

Create a model with plenty of fields.
Make one of those fields required and put at top.

Go to Nova and create a new resource.
Hit submit without inserting any data into the fields.

Notice how you cannot directly see what went wrong, or that something went wrong at all.

### Suggestion of fix

A huge UX boost would be to have the submit button turning red and shaking followed by a little status message saying something went wrong, or just plainly the real error message(s).

#### Why bug?
Any client that has no web experience will raise this as an issue. I feel that this severity is high enough to be treated as a bug, instead of a feature request.

**Comment by jbrooksuk** [comment]
I think that simply scrolling to the first error is a better idea.

**Comment by ArroWsGM** [comment]
@jbrooksuk, it's good, but you use toasted for success messages, and I think error message also must be thrown because scrolling not always necessary. Or it's can be customizable: `$onFormError = 'toasted|scroll|both'`.

Also, there is no way to reset ordering. It's really inconvenient, especially when using overridden `applyOrderings` method with filters/search applied.

**Comment by PatricNox** [comment]
@jbrooksuk it's how you find the errors, indeed. But it's not a good UX thing. 

Imagine Jens on 64. He gets an erroring form, with no implications of any faultiness or similar.

**Comment by davidhemphill** [comment]
I've added some code to notify the user via a toast message when form submissions fail because of validation. This should solve the issue in the meantime. In a future revision, we'll also look into scrolling to the first view.
