### ISSUE TITLE
Please add FormRequests

### ISSUE THREAD

**Issue by m-lotze** [laravel/nova-issues#1865]
I know that this has been requested several times. I think this would be very useful and therefore inspected novas code a bit and imho found a quite easy approach to allow the use of exisiting form requests in nova.

If you could add two properties to a resource `formRequestForCreation` and `formRequestForUpdate` and then change e.g. the handle method of the `ResourceUpdateController` like this it could work:

```
public function handle(UpdateResourceRequest $request)
    {
        $request->findResourceOrFail()->authorizeToUpdate($request);

        $resource = $request->resource();

        if ($resource->formRequestForUpdate 
          && SomeCheckForFormRequestExistsAndIsInstanceOfFormRequest()) {
             app($resource->formRequestForUpdate);
        } else {
             $resource::validateForUpdate($request);
        }

...
```

`app('FormRequest')` throws the same `ValidationException` as `Validator::make(...)->validate()`. So the nova frontend should not require any changes.

This way we could use existing FormRequests and also the customization of messages and attributes is much easier than managing it all in our language files. 

Some rules like ignore would propably require changes to work with nova and also route model binding, but since the nova resource is attached to the request, this should be quite easy.

**Comment by davidhemphill** [comment]
I've not actually seen this requested before. :-D 

I've tested this locally, and the basic idea works.

**Comment by fbingha** [comment]
Memory is fleeting :)

https://github.com/laravel/nova-issues/issues/106

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by chrisanalog** [comment]
@davidhemphill @jbrooksuk Do you know if this is something that is being thought about? I would happily create the PR for it, if it weren't for the closed source...

**Comment by chrisneal** [comment]
@davidhemphill @jbrooksuk Do you know if this is something that is being thought about? I would happily create the PR for it, if it weren't for the closed source...

**Comment by davidhemphill** [comment]
You can join the private repository by connecting your GitHub account here: https://nova.laravel.com/settings#github

**Comment by chrisanalog** [comment]
@davidhemphill I had no idea! Thank you!

**Comment by chrisneal** [comment]
@davidhemphill I had no idea! Thank you!
