### ISSUE TITLE
Executing nova:install multiple times duplicate the ServiceProvider in app config

### ISSUE THREAD

**Issue by danielbriffa** [laravel/nova-issues#1866]
- Laravel Version: 5.8.32
- Nova Version: 2.1.1
- PHP Version: 7.3
- Operating System and Version: MacOs Mojave.10.14.6

### Description

Executing php artisan nova:install adds a NovaServiceProvider entry in config/app.php. this can lead to repeated entries if the command was executed already.

**Scenario** - During development the entry in app.php needs to be pushed to repo & deployed. Else there is a risk that on next deployment (after php artisan nova:install is executed on server) that it is overwritted.

**Issue is coming** 
-from the following class - InstallCommand (namespace Laravel\Nova\Console)
-from the following method- registerNovaServiceProvider

```
protected function registerNovaServiceProvider()
    {
        $namespace = Str::replaceLast('\\', '', $this->getAppNamespace());

        file_put_contents(config_path('app.php'), str_replace(
            "{$namespace}\\Providers\EventServiceProvider::class,".PHP_EOL,
            "{$namespace}\\Providers\EventServiceProvider::class,".PHP_EOL."        {$namespace}\Providers\NovaServiceProvider::class,".PHP_EOL,
            file_get_contents(config_path('app.php'))
        ));
    }
```

**Potential Fix**

```
protected function registerNovaServiceProvider()
    {
        $namespace = str_replace_last('\\', '', $this->getAppNamespace());

        $content = file_get_contents(config_path('app.php'));

        //is the service imported already ?
        if (false === strpos($content, "{$namespace}\Providers\NovaServiceProvider::class")) {
            file_put_contents(config_path('app.php'), str_replace(
                "{$namespace}\\Providers\EventServiceProvider::class,".PHP_EOL,
                "{$namespace}\\Providers\EventServiceProvider::class,".PHP_EOL."        {$namespace}\Providers\NovaServiceProvider::class,".PHP_EOL,
                $content
            ));
        }
    }
```

**code smell**
There is a dependency on EventServiceProvider : if for any reason that is not there, it would not be added. A solution might be parsing the file to an array and pushing into 'providers' if array value does not exist

### Steps To Reproduce

Execute the following multiple times
php artisan nova:install

Check config/app.php providers section
Multiple entries of App\Providers\NovaServiceProvider::class, would be seen

**Comment by davidhemphill** [comment]
Why are you running nova:install multiple times?

**Comment by danielbriffa** [comment]
This was 1st executed locally for setup, and 2nd on server after 1st deploy. 

We managed to get around it by executing locally and including all vendor files which where created from nova:install. The same happened with the default Nova resource 'User'

**Comment by jbrooksuk** [comment]
In regards to the vendor files, why don't you use `artisan nova:publish`?
