### ISSUE TITLE
Trend on Relationships?

### ISSUE THREAD

**Issue by MCKLtech** [laravel/nova-issues#1868]
(This may possible so I'm not sure if this is a feature request or support ticket)

Let's assume I have two models:

- Users
- Bank Account Transactions

Users are connected to their Bank Transactions by id (One to Many). However, let's assume that Bank Transactions can be domestic and international, and they have a 'type' column that indicates this.

How can I produce a trend that shows the count of transactions that are domestic? In pseudo-code as per the Trend Metrics Docs:

`return $this->countByDays($request, BankTransactions::where('type', 'domestic'));`

Is this possible? I've tried it myself and no errors are being reported, but I can't say for sure it is correct.

**Comment by jbrooksuk** [comment]
https://nova.laravel.com/docs/2.0/metrics/defining-metrics.html#manually-building-trend-results

This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](https://larachat.co/).
