### ISSUE TITLE
Cannot add relation from subfolder.

### ISSUE THREAD

**Issue by wotta** [laravel/nova-issues#187]
I am having the following issue.

I have setup my resources like my models (grouped in subfolders) but my resource can't be found when I want to add an `BelongsTo` relation to a resource in another subfolder.

Is there a way to make this work or is this already working?

Greetings.

**Comment by wa7eedem** [comment]
hi , did you find a solution for this ?

**Comment by wotta** [comment]
No I did not.

**Comment by StanBarrows** [comment]
Same here :$

**Comment by wa7eedem** [comment]
make sure your Nova Resources have the correct namespace then use the Resource like : 

`BelongsTo::make('Select User', 'user_relation_name', \App\Nova\Resources\full-path\User::class),`

**Comment by StanBarrows** [comment]
Thanks for your response!
It's not only Relations, The whole Resource is not showing within the navigation.

**Comment by wa7eedem** [comment]
for me , in my NovaServiceProvider , I removed the `function resources` , 
so nova will load any Resources within the folder `Nova` , 
don't  register them manually with `Nova::resources` .

**Comment by StanBarrows** [comment]
Thanks, that made it working!
