### ISSUE TITLE
Press / to search international keyCode

### ISSUE THREAD

**Issue by exodusanto** [laravel/nova-issues#1871]
- Laravel Version: 5.8.32
- Nova Version: 2.1.0
- PHP Version: 7.2
- Database Driver and Version: Mysql 5.7
- Operating System and Version: 10.14
- Browser type and version: Chrome 76

### Description

I can't use the feature "Press / to search" with the Italian keyboard layout.
I see that the code to identify the `/` is `191` but on my layout is `47` ([this](https://blogs.longwin.com.tw/lifetype/key_codes.html) is a Danish keyboard for example)

### Steps To Reproduce

Add an event listener and map keypress event on the Italian keyboard layout.

**Comment by tswonke** [comment]
Same for German layout - I don't know how to trigger the search.

A (dynamic) setting for all shortcuts would be nice - so that we can easily define them for example based on location.

**Comment by mrmonat** [comment]
> Same for German layout - I don't know how to trigger the search.

You can trigger it by typing "/" for example "shift+7" on a german macbook keyboard

**Comment by m-lotze** [comment]
Shift+7 does not work for me on Chrome + Windows 10.

**Comment by tswonke** [comment]
Shift+7 was my first attempt - did not work.
Now I rechecked it and I have to say that it does work, but only in Safari. Does not work in Chrome.

Nevertheless a configuration of all shortcuts would be really great!

**Comment by jbrooksuk** [comment]
Could someone please test https://github.com/laravel/nova/pull/576

**Comment by tswonke** [comment]
I don't have access on that ;-)

**Comment by programmende** [comment]
On german keyboards 

> SHIFT+ALT+#

 or 

> AltGr+#

 works

**Comment by m-lotze** [comment]
Any updates here?

I just created a custom field with a ckeditor 5 instance in it and when trying to type the character ' in the editor on a german keyboard it jumps to the global search. this is not good.

i think an option to just disable all shortcuts would be nice. they are not really useful after all.

**Comment by jbrooksuk** [comment]
If anyone has the time and ability, could you please try out [this PR](https://github.com/laravel/nova/pull/712)? You'll need to compile the Nova assets yourself, so run `yarn install` and `yarn run prod`.

I've tested on a German keyboard setting and <kbd>Shift</kbd> + <kbd>7</kbd> worked.

**Comment by exodusanto** [comment]
@jbrooksuk I can't because I don't have access to [this repo](laravel/nova)

**Comment by jbrooksuk** [comment]
@exodusanto you'll need to link Nova to your GitHub account (you can do that from https://nova.laravel.com)

**Comment by exodusanto** [comment]
@jbrooksuk It works 🎉 I tried with Italian keyboard!

**Comment by jbrooksuk** [comment]
Thank you @exodusanto!

**Comment by exodusanto** [comment]
I notice that when I press `/` the search input is filled with that char 😕

**Comment by jbrooksuk** [comment]
Ah yes, I can confirm this. Will fix now.

**Comment by jbrooksuk** [comment]
I've pushed a fix for that.
