### ISSUE TITLE
Please allow long texts without spaces to fit it's view area.

### ISSUE THREAD

**Issue by wemersonrv** [laravel/nova-issues#1872]
Hi, please allow long texts without spaces to fit it's view area, See the image below. I have this long string and as it's too long, i cannot see it right. It can be in a Text or Textarea...

![image](https://user-images.githubusercontent.com/2028673/63959798-61a09e00-ca63-11e9-9271-13f4149e14e4.png)

**Comment by dillingham** [comment]
needs tailwinds `break-all` css class

**Comment by wemersonrv** [comment]
Ok, tx @dillingham
