### ISSUE TITLE
Global css variable enhancement.

### ISSUE THREAD

**Issue by winter-ice** [laravel/nova-issues#1873]
- Laravel Version: 5.8.34
- Nova Version: 2.1.1
- PHP Version: 7.2
- Database Driver and Version: #.#
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description
https://github.com/sass/sass/issues/2738
Recommended renaming global number variable.It's not standard usage.
Now in app.css
```
  --20: #f6fbff;
  --30: #f4f7fa;
  --40: #eef1f4;
  --50: #e3e7eb;
  --60: #bacad6;
  --70: #b3b9bf;
  --80: #7c858e;
  --90: #3c4b5f;
  --90-half: rgba(40, 54, 61, 0.5);
```

Recommended
```
--neutral-20
```

**Comment by davidhemphill** [comment]
No plans to implement this at this time. There's no problem with the current approach.

**Comment by winter-ice** [comment]
Did you checked  the issue that I referenced in description?I think the usage now is not standard

**Comment by davidhemphill** [comment]
This allowable according to CSS spec. This an issue with Sass.
