### ISSUE TITLE
TrendMetric can not show value "0"

### ISSUE THREAD

**Issue by mrmonat** [laravel/nova-issues#1874]
- Nova Version: 2.1.1

### Description

TrendMetrics don't show a value (with ```->showLatestValue()```), if the latest value is 0.

<img width="368" alt="Bildschirmfoto 2019-08-30 um 12 46 03" src="https://user-images.githubusercontent.com/17597850/64015517-fc14e600-cb24-11e9-83ba-a0ad54cc8c7e.png">

### Steps To Reproduce

- use TrendMetric with ```showLatestValue()```
- latest value must be 0

**Comment by jbrooksuk** [comment]
Confirmed.

**Comment by CitizenBeta** [comment]
I can still reproduce this on 2.4.0
