### ISSUE TITLE
Custom Header support for all views

### ISSUE THREAD

**Issue by chris-ware** [laravel/nova-issues#1875]
Currently, both the Index and Detail views have support for custom headers. I use these for my package [Nova Breadcrumbs](https://github.com/chris-ware/nova-breadcrumbs), which has over 10k downloads. At the moment however, on any other views, I have to overwrite and include the view itself, which means a full recompile for every new version of Nova. Whilst I don't mind that, a lot of users don't seem to understand why version constraints are applied. If custom headers were available on every view, I could just inject the breadcrumbs as needed on those instead of having to overwrite the default views, therefore meaning I should be able to unlock the version constraints.

Or, if you'd prefer, add breadcrumbs to Nova itself... there is a lot of people wanting it.

**Comment by gavinhewitt** [comment]
+1 Yes, breadcrumbs in core please!

**Comment by jbrooksuk** [comment]
I can see why this would be useful and we've only done half of the work here.

**Comment by rodrigo-spb** [comment]
+ 1, breadcrumbs in core is great!

**Comment by CitizenBeta** [comment]
Super important feature :)

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
