### ISSUE TITLE
New custom dashboard not working 

### ISSUE THREAD

**Issue by amahmoud92** [laravel/nova-issues#1877]
Hello guys,

I am using nova version v2.1.1, everything working perfectly and I like it.
After I read this article [https://nova.laravel.com/docs/2.0/customization/dashboards.html](url) and apply it I think I found an issue and I hope I am wrong :

when I click on the new dashboard button it does not redirect me to the newly created dashboard.
![Screenshot from 2019-09-01 12-53-26](https://user-images.githubusercontent.com/52914308/64074716-bd636500-ccb7-11e9-8e63-120201f7478e.png)
The button has this link **http://127.0.0.1:8000/admin/** 
now after debugging I found that the **cards method** not loaded also (its not reachable)

here is my code :

1. I hit this command 
 ```bash 
artisan nova:dashboard Test
```

2. I modify the card method 

```php 

namespace App\Nova\Dashboards;

use App\Nova\Metrics\JobCount;
use Laravel\Nova\Dashboard;

class Test extends Dashboard
{
    /**
     * Get the cards for the dashboard.
     *
     * @return array
     */
    public function cards()
    {
        return [
            new JobCount
        ];
    }

    /**
     * Get the URI key for the dashboard.
     *
     * @return string
     */
    public static function uriKey()
    {
        return 'test';
    }
}
```
3. I modify **App\Providers\NovaServiceProvider**

```php
use App\Nova\Dashboards\Test;

    /**
     * Get the cards that should be displayed on the Nova dashboard.
     *
     * @return array
     */
    protected function dashboards()
    {
        return [
            new Test
        ];
    }
```
**Note: I Clear all cach type in laravel :)**

**Comment by reyberyturiaga** [comment]
I can confirm that this issue exists. The href of the custom dashboard link is set to "/" instead of the defined uri key in the class.

**Comment by jbrooksuk** [comment]
I'm unable to confirm this issue. At first, I thought that it was because you'd customised the `nova` endpoint to be `admin`, but even once I did that, the dashboard still had the correct link.

Have you published assets correctly? `php artisan nova:publish --force`

**Comment by amahmoud92** [comment]
@jbrooksuk 
Yes this is **not a bug**
after I ran this command my issue fixed.
```bash
php artisan nova:publish --force
```

Thank you

**Comment by reyberyturiaga** [comment]
@jbrooksuk Thanks for the quick response! Fixed on my side as well.
