### ISSUE TITLE
Adding actions in the resources row

### ISSUE THREAD

**Issue by albalooshi** [laravel/nova-issues#188]
Is it possible to add specific actions in a row next to the the three current icons? Please see the attached image for an example

![buttons](https://user-images.githubusercontent.com/13213888/44619459-5387d280-a88f-11e8-8fab-f75403634016.jpg)
 

If not can I request this feature?

**Comment by Andy-Baker** [comment]
The current solution for this is to create an action, check that row's box and run the action.

What type of actions would make sense in-line, but not with the checkbox-then-run-action flow?

**Comment by andypa** [comment]
@Andy-Baker as an example: I created a Page Model and would like to sort the models directly from the index view.

**Comment by ardyn** [comment]
@Andy-Baker Another example: I have list of customers. I need to create an appointment for Customer #1. I open the action, input the appointment time and run the action. Being that I cannot have two customers scheduled for the same appointment time, this action only runs on a specific Customer record. Right now I have to navigate to the customer record, click actions, select action. That's 3 clicks and a page load when I could do the action with one click.

**Comment by dillingham** [comment]
On second thought, its a great idea lol but as a field 

https://github.com/tightenco/nova-package-development/issues/44

**Comment by davidhemphill** [comment]
This is currently not supported. You can add your own customized version of the resource's table row component if you absolutely need this.

**Comment by aozen** [comment]
Is there any post or package for this?

**Comment by matthiggins** [comment]
In the most recent release notes for `v2.4.0` it says 

> "Inline Actions": added ability to show Actions inline in their own menu on individual resource table rows.

But I can't find any documentation on that.  Has anyone figured out how to do it?  

Can we get the documentation to update when releases go out as well?

**Comment by davidhemphill** [comment]
The docs were updated at the same time as release. Here's the relevant section: https://nova.laravel.com/docs/2.0/actions/defining-actions.html#action-visibility

**Comment by umairtariq1021** [comment]
![impersonate_icon](https://github.com/laravel/nova-issues/assets/40889006/092f689f-da00-47a1-b694-66dfce6d2fa0)
I want to add a new icon just like the view or edit icon.
I want to add this in front of the view icon.
How i can do this?
