### ISSUE TITLE
Union doesn't display all results

### ISSUE THREAD

**Issue by iHwy** [laravel/nova-issues#1880]
- Laravel Version: 5.8.33
- Nova Version: 2.1.1
- PHP Version: 7.2

I'm using a union to join multiple forien keys. When viewing a resopurce the HasMany query returns the proper number of records but both columns are not displayed. One of the columns, either home_team_id or visiting_team_id, is not shown. The column that is not shown depends on the order of the union.

The union below will show the visiting_team_id columm. The home_team_id is not shown. If I switch the order of the union the opposite occurs. The home_team_id shows and the visiting_team_id is not shown.  

I'm assuming both columns would display since both columns are in the result set. In all cases the single team can be the home_team_id or the visiting_team_id. Is this a bug or am I doing something
wrong? Is it better to have a a pivot table?

Team
----------

id
Name

Game
----------

id
home_team_id
visiting_team_id

In Team Model
----------

    public function games()
    {
        return $this->home_games()->union($this->visiting_games()->toBase());
    }
    
    public function home_games()
    {
        return $this->hasMany('App\Game', 'home_team_id', 'id');
    }

    public function visiting_games()
    {
        return $this->hasMany('App\Game', 'visiting_team_id', 'id');
    }

Team Field
--------------------

    HasMany::make('Games')

In Game Model
----------

	public function home_teams()
	{
		return $this->belongsTo('App\Team', 'home_team_id', 'id');
	}

	public function visiting_teams()
	{
	   return $this->belongsTo('App\Team', 'visiting_team_id', 'id');
	}

Game Fields
--------------------

    BelongsTo::make('Home Team','home_teams','App\Nova\Team')
        ->rules('required'),

    BelongsTo::make('Visiting Team','visiting_teams','App\Nova\Team')
        ->rules('required'),

**Comment by jbrooksuk** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](https://larachat.co/).

**Comment by iHwy** [comment]
@jbrooksuk Wouldn't this be a bug if Nova wasn't displaying all of the columns returned from a union query?

**Comment by dkulyk** [comment]
HasMany is relation. Not a query.

**Comment by iHwy** [comment]
@dkulyk Thank you. I misspoke. The results from the union are not being displayed correctly.
