### ISSUE TITLE
Validation translation fails on related resource (dot and arrow notation)

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#1882]
- Laravel Version: 5.8.24
- Nova Version: 2.0.6
- PHP Version: 7.2.10
- Database Driver and Version: MySQL 5.7.23
- Operating System and Version: Windows 10 (64 bits)
- Browser type and version: Chrome 76 (64 bits)

### Description

When i try to show a related resource, i can use a **. dot** or **->arrow** notation to get the related field. 

When i use a dot notation, validation rules won't work, but translation should work.

When i use a -> notation, validation rules do work. However, now it seems impossible to get a translation for the field name.

Goal is related fields with working validation rules and translatable field names

### Steps To Reproduce

app/nova/someResource.php

```php 
...
$fields[] = Fields\Text::make(ucfirst(__('Name')), 'user->name')
            })->rules('required', 'min:3', 'max:255');
....
```
resources/lang/<lang id>/validation.php

```php

return [
 /*
    |--------------------------------------------------------------------------
    | Custom Validation Attributes
    |--------------------------------------------------------------------------
    |
    | The following language lines are used to swap attribute place-holders
    | with something more reader friendly such as E-Mail Address instead
    | of "email". This simply helps us make messages a little cleaner.
    |
    */

    'attributes' => [
        'wearerUser->name' => 'name',  //wearerUser.name also fails
    ],
];

```

**Comment by davidhemphill** [comment]
Nova's fields do not explicitly support writing to relations. This is only supported in computed fields. As such there's no support for validating relations at this time.
