### ISSUE TITLE
Some actions doesnt work after upload project with Forge

### ISSUE THREAD

**Issue by seoanalyze** [laravel/nova-issues#1884]
Hey,
I've uploaded my project to my digitalocean Server with Forge but some actions doesn't work now.
It seems that nothing is executed. I have no database entry in my actions table and if I check my XHR network tab in the developer tools I have no output on the action, even if I leave the handle function empty and just echo out a string.

The mysterious thing is that some actions are working? But if I copy the complete source into my broken actions, nothing happens again.

I don't know how to solve this and I'm very thankful for any advice.

**Comment by jbrooksuk** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](https://larachat.co/).
