### ISSUE TITLE
New Nova Tool, NPM Fails

### ISSUE THREAD

**Issue by marky291** [laravel/nova-issues#1885]
- Laravel Version: 5.8
- Nova Version: v2.1.1

### Description

Node is failing to run development, documentation is unclear.

### Steps To Reproduce

php artisan nova:tool Navigation
cd /nova-component/navigation
npm run dev

<img width="1089" alt="Screenshot 2019-09-03 at 21 42 59" src="https://user-images.githubusercontent.com/5384515/64207244-27386600-ce94-11e9-95cb-f9062f3cfbe6.png">

**Comment by davidhemphill** [comment]
according to these steps and common errors received when you don't, it seems you didn't install the node modules. You'll need these for the package to work.
