### ISSUE TITLE
AM/PM DateTime

### ISSUE THREAD

**Issue by wefixit-tech** [laravel/nova-issues#1887]
- Laravel Version: 6.0
- Nova Version: 2.2.0
- PHP Version: 7.2

### Description

I cant get to show the AM/PM in the DateTime or is a way to set 12 hours format.

**Comment by jbrooksuk** [comment]
If you're using the `format` method on the `DateTime` field, you need to use the Moment.js formatting syntax. https://momentjs.com/docs/#/displaying/

**Comment by wefixit-tech** [comment]
Maybe i dont explain me well, i want to show in the datetime field the AM/PM when im selecting a date, not in the index.

![Sin título](https://user-images.githubusercontent.com/3880643/64272954-ff81e600-cf05-11e9-90de-40709525e5cd.png)

**Comment by jbrooksuk** [comment]
Apologies.

It looks like we'd need to be able to pass through the `time_24hr` and `no_calendar` properties to the datetimepicker component. https://flatpickr.js.org/examples/#time-picker

**Comment by Inquisitor** [comment]
Wait, what?
In my project, I **can't get rid of** this pesky am/pm format.
![Screenshot](https://i.imgur.com/BqCEXnA.png)

**Comment by jbrooksuk** [comment]
@Inquisitor I believe this is because Nova looks to see if the locale of the computer uses 24 hour or not. I can see that the `DateTimePicker` component already sets the `time_24hr` config but this comes from https://github.com/laravel/nova-js/blob/ef64432f24c68d12602d1b015abc954da3943b37/src/mixins/InteractsWithDates.js#L85-L90 which is detecting automatically.

**Comment by Inquisitor** [comment]
>  I believe this is because Nova looks to see if the locale of the computer uses 24 hour or not. 
Well, then it works vice versa, because I do have 24h setting on my computer.

Probably, @wefixit-tech has am/pm on their computer?

**Comment by wefixit-tech** [comment]
im using in my Windows pc 12 hours and am/pm format i live in México and the timezone im using is America/Mexico_City but in the original UTC im getting the same problem.

**Comment by ahmedmaazin** [comment]
Would it be possible to pass through an option to disable 24hr even though the local system is set as 24hr? @driesvints

**Comment by driesvints** [comment]
@ahmedmaazin best to ping @jbrooksuk as I don't maintain Nova.

**Comment by aghayeff** [comment]
How to switch to 24 hours format in dateTime picker?
