### ISSUE TITLE
Dynamic construction of searchable fields

### ISSUE THREAD

**Issue by skoyah** [laravel/nova-issues#1888]
It would be nice to be able to conditionally build the array of searchable fields.

I'll give you my current example from a project:

The App will be used in different markets (i.e. countries). We are currently loading the resource fields based on those markets. Furthermore, the same fields might be searchable for some markets only.

I was thinking over this problem for a while and it seems that there 2 ways of setting the searchable fields, either setting them on `$search` or by overriding the `searchableColumns()` method; they're both static.

Is this a nice feature to implement on Nova codebase? If so, anyone got some ideas how implement this?

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by skoyah** [comment]
Thanks for adding the request label @jbrooksuk .  What's your opinion on this proposal? Does it make sense?

**Comment by jbrooksuk** [comment]
Yep! I can see this being a useful enhancement. I’m not familiar with the searchable code, but I can’t imagine it being too complicated.

**Comment by skoyah** [comment]
Another thing I found useful IMHO is to be able to distinguish between globally searchable fields and the ones that can only be searchable within the resource index page. 

Thanks for your feedback @jbrooksuk !
