### ISSUE TITLE
vendor/nova/app.js & vendor/nova/vendor.js too large 

### ISSUE THREAD

**Issue by Duohao** [laravel/nova-issues#1890]
files too large (after run `npm run production`):  
- vendor/nova/app.js 
-  vendor/nova/vendor.js 

![image](https://user-images.githubusercontent.com/46482051/64294860-67860a00-cfa2-11e9-9c8f-49ef9552a8e6.png)

**Comment by demency** [comment]
That time corresponds to the download time. Use a CDN to reduce that indicator.

**Comment by thaifani** [comment]
> That time corresponds to the download time. Use a CDN to reduce that indicator.

no ,
it so large , this is problem even when use CDN
so ,please any solution

**Comment by demency** [comment]
@thaifani the blue color is download time, green color is execution time of code. See chrome dev tools docs about that graph. Using CDN can make goes down that metric. Can you share your results using CDN or more details?

**Comment by thaifani** [comment]
but the size is more then 2 MB
