### ISSUE TITLE
Missing padding/margin between Card and Filter under certain conditions

### ISSUE THREAD

**Issue by chescos** [laravel/nova-issues#1891]
- Laravel Version: 5.8
- Nova Version: 2.2.0
- PHP Version: 7.3
- Browser type and version: Chrome

### Description

Under certain conditions, the Filter icon seems to be missing margin/padding. Here's an example condition:

1. We have a `User` resource that has a `HasMany` relationship with a `Transaction` resource
2. The `Transaction` resource has a filter
3. The `Transaction` resource has a policy which denies create, update, and delete actions

In that scenario, the details view of a `User` resource will have an issue with the margin/padding for the Filter icon on the `Transaction` relationship:

![Selection_881](https://user-images.githubusercontent.com/12296880/64343353-b0fb4700-cfec-11e9-8c84-1dd3d068f046.png)

### Steps To Reproduce

1. Create a `User` resource and a `Transaction` resource
2. Attach the `Transaction` resource to the `User` resource as a `HasMany` field
3. Create a filter and attach it to the `Transaction` resource
4. Create a `TransactionPolicy` policy for the `Transaction` model and return `false` from all methods except the `view` method
5. Go to the details view of a User and look at the `HasMany` relationship for the `Transaction` resource, the margin/padding for the Filter icon is missing (see screenshot above)

**Comment by jbrooksuk** [comment]
Could you please provide a repository that reproduces this issue?

**Comment by chescos** [comment]
@jbrooksuk The steps to reproduce are pretty straightforward. If anything is unclear I can give more instructions. The issue comes from [this line](https://github.com/laravel/nova/blob/20e9e67c451e8db8113903c343b7a4df15ce49d4/resources/js/views/Index.vue#L66), the conditional class doesn't meet all the required conditions.

**Comment by davidhemphill** [comment]
I believe we forgot to close this issue after we fixed it, as I was not able to replicate the issue anymore. If the problem still persists, please feel free to respond and we'll open the issue up again (and fix it!) Thanks!
