### ISSUE TITLE
Vue component name for CSS

### ISSUE THREAD

**Issue by gaabora** [laravel/nova-issues#1892]
For easier styling and making themes. It would be nice if each nova's vue component and view have it's name in a root element's class list (or in a dusk, or some other attribute).

For example **components/PanelItem.vue** instead of 
```
<template>
    <div class="flex border-b border-40">
...
```
we got
```
<template>
    <div class="panel-item flex border-b border-40">
...
```
or even
```
<template>
    <div class="flex border-b border-40" nova-component="panel-item">
...
```

**Comment by Dontorpedo** [comment]
its not perfect but its usable

https://novapackages.com/packages/gregoriohc/laravel-nova-theme-classify

**Comment by davidhemphill** [comment]
There's no plans to do this at the moment, since we don't currently support theming all aspects of the admin beyond setting basic colors and such.
