### ISSUE TITLE
authorizedToCreate not working after creation

### ISSUE THREAD

**Issue by bsormagec** [laravel/nova-issues#1893]
- Laravel Version: 5.8.35
- Nova Version: 2.2.0
- PHP Version: 7.3.9

### Description

We are using usage limits for resources by user when user reached limit about resource we want to hide button. We are using it on Policy by authorizedToSee but after creation ResourceTable reloading but Index is not reloading. I think on create nova must check has authorizedToCreate for this resource. Can you find a way to fix this ?

**Comment by bsormagec** [comment]
Is there any way to fix this ? @davidhemphill

**Comment by jbrooksuk** [comment]
It looks to me that the `authorizedToCreate` result is not refreshed when a new resource has been created.

I believe we could fix this with some events, @davidhemphill?

**Comment by bsormagec** [comment]
Yes its true @jbrooksuk thanks for your reply

**Comment by jbrooksuk** [comment]
Basically, what's happening here is that the initial resource state is stored in `Nova.config.resources`. This is set when you land on any Nova page and is rendered via Blade (not fetched over the Nova API).

For this to be fixed, we'd need to implement a method of refreshing the Nova resources.

**Comment by bsormagec** [comment]
I checked all states and this states changing only when page reload i cant find what i need to do checked in Vue console and states its not returning in resource layer its returning authorizedToCreate: true but in backend its already false. States not reloading after this. I think it will implement on save action to return last policy updates with correct values.

**Comment by jbrooksuk** [comment]
That's the expected current behaviour. The only thing that'll refresh the resource state is to refresh.

**Comment by bsormagec** [comment]
@jbrooksuk whats your idea about this i got this problem on my policy designed application. I need to fix this

**Comment by bsormagec** [comment]
is there any update @jbrooksuk @davidhemphill ?

**Comment by davidhemphill** [comment]
I've worked a bit on a solution for this, but it'll currently break third-party tools and lots of changes inside Nova would need to happen.

**Comment by bsormagec** [comment]
Its really broking many things when we use policies in our applications. We are taking limits by user and when user limit reached then  button needs to hide but its looking and giving error when click. Because backend is working but frontend not know it yet.

**Comment by bsormagec** [comment]
Is there any update about this @davidhemphill ?

**Comment by bsormagec** [comment]
Any plan for update for this ?

**Comment by davidhemphill** [comment]
It's kind a tough thing to do elegantly in the current version without breaking changes or maintaining two separate authorization methods. Would require constant extra network requests and would break current tools that rely on it.

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
