### ISSUE TITLE
MorphTo fields stay empty when editing through parent resource / viaResource

### ISSUE THREAD

**Issue by loekwetzels** [laravel/nova-issues#1897]
- Laravel Version: 5.8.35
- Nova Version: 2.2.0
- PHP Version: 7.3.6
- Database Driver and Version: MySQL 5.7

### Description

**How my models are set up:**
- I have a Nova resource  _Reservations_ that:
  - `HasMany` _Reservationitems_, each _Reservationitems_  has a
    - `MorphTo` relationship to _Sellables_

I'm not using a `morphMap`

See code below (Steps To Reproduce)

**Bug description**
- :white_check_mark: When I view a _Reservation_ I see a list of _Reservationitems_. 
  - :white_check_mark: When I click the view icon on a _Reservationitem_ in this list, I'm redirect to `resources/reservationitems/1`.
    - :white_check_mark: When I click the edit Icon on this detail view, I'm redirected to `resources/reservationitems/1/edit`.
      - :white_check_mark: All fields are filled in as aspected.
  - :white_check_mark: When I click the edit icon on a _Reservationitem_ in this list (indicated with :exclamation: in screenshot), I'm redirect to `resources/reservationitems/1/edit?viaResource=reservations&viaResourceId=100&viaRelationship=reservationitems`
    - :sos: BUG: the `MorphTo` fields (of my _Sellable_) are empty

![1-reservation-detail](https://user-images.githubusercontent.com/867536/64420329-553dc600-d09f-11e9-99a4-6d59eb2ae9c2.jpg)
![2-reservationitem-detail](https://user-images.githubusercontent.com/867536/64420332-58d14d00-d09f-11e9-8f03-355e12686430.jpg)
![3-reservationitem-edit](https://user-images.githubusercontent.com/867536/64420334-5b33a700-d09f-11e9-9342-617c21c306bc.jpg)
![4-resevationitem-edit-viaresource-bug](https://user-images.githubusercontent.com/867536/64420339-5cfd6a80-d09f-11e9-9674-3d0e2fb63667.jpg)

### Steps To Reproduce

```php
// App/Reservation.php
public function reservationitems()
{
  return $this->hasMany(Reservationitem::class);
}
```

```php
// App/Nova/Reservation.php
public function fields(Request $request)
{
  return [
     // more fields
      HasMany::make('Items', 'reservationitems', 'App\Nova\Reservationitem'),
  ];
}
```

```php
// App/Reservationitem.php
public function sellable(): MorphTo
{
  return $this->morphTo();
}
```

```php
// App/Nova/Reservationitem.php
public function fields(Request $request)
{
  return [
     // more fields
    MorphTo::make('Sellable')->types([
      Product::class,
      SubProduct::class,
    ])->searchable(),
  ];
}
```

**Comment by loekwetzels** [comment]
I think this is related to:
#1801 
#1819

**Comment by stwinnie** [comment]
same problem here

**Comment by stwinnie** [comment]
Anybody? This is a critical issue for me.

**Comment by stwinnie** [comment]
@davidhemphill @jbrooksuk

**Comment by jbrooksuk** [comment]
@loekwetzels thank you for the in-depth reproduction details, but would it be possible to provide us with a repository which reproduces this issue **with** a seeder for the tables, please?

**Comment by loekwetzels** [comment]
@jbrooksuk I invited you to a stripped down private repo with a seeder.

**Comment by loekwetzels** [comment]
@jbrooksuk Did you see the invite? I'm still seeing "Awaiting jbrooksuk’s response" in the private repo

**Comment by stwinnie** [comment]
@jbrooksuk it's still a critical issue that is ignored for more than 2 months, please help

**Comment by loekwetzels** [comment]
Just a reminder that this is still broken in Nova 2.10.1

**Comment by Pamposgsk** [comment]
Not working viaResource.
While trying to edit an existing record MorphTo field become empty

**Comment by tmaslov22** [comment]
This is still a pressing issue for me in nova 3.x

**Comment by Pamposgsk** [comment]
Are there any plans to fix this very important bug?

**Comment by erhuz** [comment]
@jbrooksuk Any update?

**Comment by loekwetzels** [comment]
@jbrooksuk @davidhemphill @taylorotwell 😬

**Comment by morphsteve** [comment]
@jbrooksuk @davidhemphill To try to help move this along, a glance through `MorphToField.vue` suggests there is a logical issue in the `mounted` hook and the `creatingViaRelatedResource` computed property.

`creatingViaRelatedResource` is a misnomer - it's still true when _editing_ a resource. Hence this block in the `mounted` hook will overwrite the current value when editing:

```js
if (this.editingExistingResource) {
  this.initializingWithExistingResource = true
  this.resourceType = this.field.morphToType
  this.selectedResourceId = this.field.morphToId
}

if (this.creatingViaRelatedResource) {
  this.initializingWithExistingResource = true
  this.resourceType = this.viaResource
  this.selectedResourceId = this.viaResourceId
}
```

This logic makes perfect sense as a user convenience when _creating_ a resource, but I can't think of any situation to overwrite the current value when _editing_ a resource - the user should see the actual value here. This can create a situation where a user updates the relationship without intending to.

The further issue in @loekwetzels' scenario (and I have a similar issue) is a result of the default value is being set to the `Reservation` resource, which isn't one of the allowed resource types (`Product` or `Subproduct`), so the field appears blank.

Suggestions:
1. Enhance `creatingViaRelatedResource` to determine if the resource is actually being created, not edited, or:
2. Overwrite the value only if `editingExistingResource` is false, i.e.

```js
if (this.editingExistingResource) {
  // ...
} else if (this.creatingViaRelatedResource) {
  // ...
}
```

This would be sufficient to handle both issues. As a further enhancement, the default value could be overwritten only `viaResource` is one of the allowed resource types - something like this:

```js
mounted() {

  // ...

  if (this.editingExistingResource) {
    // ...
  } else if (this.viaResourceIsMorphToType) {
    // ...
  }
},

computed: {

  // ...

  viaResourceIsMorphToType() {
    return this.viaResource && this.field.morphToTypes.map(type => type.value).includes(this.viaResource);
  },
},
```
