### ISSUE TITLE
BelongsTo field remove selection when save failed

### ISSUE THREAD

**Issue by yevgentyshchenko** [laravel/nova-issues#1898]
- Laravel Version: 6.0.1
- Nova Version: 2.2.0
- PHP Version: 7.2
- Database Driver and Version: #.#
- Operating System and Version: MacOS Mojave 10.14.5
- Browser type and version: Chrome 76.0.3809.132

### Description

The BelongsTo field clears selected option at UI when save is failed due to validation rules.

### Steps To Reproduce

1. Create a resource with several required fields and several BelongsTo fields.
2. At the creation form fill BelongsTo fields and click on the create button.
Selected options at BelongsTo now will be "-".

**Comment by davidhemphill** [comment]
I was not able to replicate this on the latest version of Nova (v3.12.1). Please post a new issue with details on how to reproduce it on the latest version. 👍
