### ISSUE TITLE
Move hardcoded logic from hooks for views

### ISSUE THREAD

**Issue by gaabora** [laravel/nova-issues#1899]
If you want to extend some Nova's view, when using it as a mixin, there some hardcoded logic might be executed in those hooks.

for example:
When using Updade.vue (or any other) as a mixin you get
```
async created() {
    if (Nova.missingResource(this.resourceName)) return this.$router.push({ name: '404' })
...
```
and you can not override this behaviour.
I suggest to move all code from hooks to separate functions, so it became something like
```
async created() {
    this.initializeComponent()
},
methods: {
    initializeComponent() {
        if (Nova.missingResource(this.resourceName)) return this.$router.push({ name: '404' })
...
```

Also I can make a PR.

**Comment by davidhemphill** [comment]
Extending Nova's internals like this isn't supported and there's no plans to facilitate this sort of use-case.
