### ISSUE TITLE
HttpException when APP_ENV=production

### ISSUE THREAD

**Issue by AdamKeen** [laravel/nova-issues#190]
I just changed the app_env from 'local' to 'production' on a fresh laravel copy then i got that HttpException when i'm authenticated (already signed in) or trying to authenticate

**Comment by crnkovic** [comment]
Did you add auth check in Nova's service provider?

https://nova.laravel.com/docs/1.0/installation.html#authorizing-nova

**Comment by AdamKeen** [comment]
ah that was it, thank you

**Comment by longvireak** [comment]
or you can write it like this 
Gate::define('viewNova', function ($user) {
            return true;
 });
