### ISSUE TITLE
Can't specify attribute name for JSON column using dot notation

### ISSUE THREAD

**Issue by bakerkretzmar** [laravel/nova-issues#1900]
- Laravel Version: 5.8.35
- Nova Version: 2.2.0
- PHP Version: 7.2
- Database Driver and Version: MySQL 8.0.16
- Operating System and Version: macOS 10.13.6
- Browser type and version: Firefox 68

### Description

Values stored in JSON columns in the database can't be saved using dot notation.

```php
// This works
Text::make('English name', 'name->en')

// This doesn't
Text::make('English name', 'name.en')
```

Nova resolves the value of the field fine if it's already set, but can't set it when saving the resource.

Nova appears to be [converting the arrow to a dot internally anyway](https://github.com/laravel/nova/blob/90484421d0967aa4a10e136d64d36346434c16b5/src/Fields/Field.php#L253), so I'm not really sure why this doesn't work.

### Steps To Reproduce

Add the following to a Nova resource whose underlying model has a `name` JSON column:

```php
Text::make('English name', 'name.en')->rules(['required_without:name.fr']),

Text::make('French name', 'name.fr')->rules(['required_without:name.en']),
```

The resource will not save: no matter what's entered in either field, it thinks both of them are empty.

**Comment by davidhemphill** [comment]
The issue here is if an incoming field attribute has a dot in it, then Laravel's validator thinks it's validating an array of some sort. Since we can't change that behavior for Nova, I'm closing this since you can also just use the arrow syntax.
