### ISSUE TITLE
Action Log detail page bug with translations

### ISSUE THREAD

**Issue by gabrielesbaiz** [laravel/nova-issues#1902]
- Laravel Version: v5.8.35
- Nova Version: v2.2.0
- PHP Version: 7.3.4
- Database Driver and Version: #.#
- Operating System and Version: MacOS Mojave 10.14.5
- Browser type and version: Chrome 76.0.3809.132

### Description

After setting translations for "Original" and "Changes" the tables are empty on detail page.

Without translation
<img width="774" alt="Schermata 2019-09-07 alle 10 09 48" src="https://user-images.githubusercontent.com/22818698/64472021-a9f14780-d158-11e9-8487-4025b3b62ba7.png">

With translation
<img width="718" alt="Schermata 2019-09-07 alle 10 09 23" src="https://user-images.githubusercontent.com/22818698/64472033-c68d7f80-d158-11e9-9b18-75a9c15b1209.png">

### Steps To Reproduce
- use any non-English locale
- add translations for "Original" and "Changes" on .json

**Comment by jbrooksuk** [comment]
I'm unable to replicate this issue with a French locale on Nova v2.3.0

![image](https://user-images.githubusercontent.com/246103/65244452-79a79280-dae2-11e9-88a8-bbfc9beef141.png)
