### ISSUE TITLE
Vapor File Upload Compatibility

### ISSUE THREAD

**Issue by mikebronner** [laravel/nova-issues#1903]
Now that Vapor is close to coming out, what are your thoughts on making Nova compatible? I think the only pain-point that comes to mind is file-upload functionality? Or is there already a work-around in place to manage this? Thanks!

Uploading to the S3 storage disk works just fine. The problem is that it doesn't appear to register it with Vapor's CDN, so that any images rendered using the `asset()` helper result in broken links.

This is the response I get when pasting a Nova-uploaded image url from the front-end into the browser:
https://d3ockv9jcyrgaw.cloudfront.net/da92a834-7d56-4e47-8284-47c2ae881c0d/photos/6ReyITp2eGmnkJVIZXAAhkwcXMB79BAENrb1zUM8.png
```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
da92a834-7d56-4e47-8284-47c2ae881c0d/photos/6ReyITp2eGmnkJVIZXAAhkwcXMB79BAENrb1zUM8.png
</Key>
<RequestId>0A7763F363963A8A</RequestId>
<HostId>
eALmvKmwbik/cHkEv2faV3nSuaaiUf3/EmJOYfb0bxWynadVNfj2KYiciAJQcpiLM3KC1sCIdfI=
</HostId>
</Error>
```

Another aspect is that Nova is not rendering the previews using the CloudFront URL, meaning that all images are broken when viewed in Nova.

**Comment by benjamincrozat** [comment]
Direct upload to S3 would be great, yes.

**Comment by nickkuijpers** [comment]
Hi,

Maybe to give some direction, i have got it working by doing this.

```
Image::make('Logo', 'logo')                
                ->store(function (Request $request, $model) {                    
                    $name = $request->logo->getClientOriginalName();                    
                    $savedName = Storage::disk('s3')->putFileAs('/assets/platforms', $request->logo, $name, 'public');                    
                    return [
                        'logo' => $savedName,
                    ];
                }),       
```

Currently not doing anything with the asset() function, wil do that when creating the frontend. I got it working in the nova backend atm.

Just fill in the default driver S3 of laravel, default docs.

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by khaledzag** [comment]
Any new updates ?

**Comment by cwilby** [comment]
Closing the issue seems like overzealous automation.  This was a feature request until the label was removed.
