### ISSUE TITLE
Account settings on website links to v1.0 documentation

### ISSUE THREAD

**Issue by bradenkeith** [laravel/nova-issues#1904]
On page: https://nova.laravel.com/settings#password
The link for: `installing Nova via composer`
Resolves to: https://nova.laravel.com/docs/1.0/installation.html#installing-nova-via-composer

Which is 1.0 documentation and would have folks installing an outdated version off the bat.

Correct URL resolution is: https://nova.laravel.com/docs/2.0/installation.html#installing-nova-via-composer

**Comment by davidhemphill** [comment]
This has been fixed. Thanks!
