### ISSUE TITLE
Error with `starts_with` after upgrading to Laravel 6.0

### ISSUE THREAD

**Issue by unlikenesses** [laravel/nova-issues#1905]
- Laravel Version: 6.0.1
- Nova Version: 2.2.0
- PHP Version: 7.2

### Description

After upgrading from Laravel 5.8 to 6.0 (and therefore removing the string helpers), upgrading Nova to 2.2.0, and running 

```bash
php artisan nova:publish
php artisan view:clear
```

I get this error in my browser:

> Call to undefined function starts_with() (View: /app/resources/views/vendor/nova/layout.blade.php)

**Comment by lizhineng** [comment]
According to the giving path, maybe you overrode the Nova layout.blade.php?

**Comment by davidhemphill** [comment]
The string helpers in Laravel were removed in version 6. If you've customized your layout and it uses this, you'll need to change it to use `Str::starts_with()`. One way of seeing what's changed in the layout is publishing the new Nova assets with `php artisan nova:publish --force` and checking the diff.

**Comment by ryanpaulfyfe** [comment]
I ran into this same issue, and the above solution *almost* fixed it, looks like the naming convention has also changed from snake to camel.

https://laravel.com/docs/5.7/helpers#method-starts-with

Should be:

Str::startsWith()

**Comment by PatricNox** [comment]
str for me was just the sole fix. I had to apply the namespace as well, within the blade. 
Is there a better way for this?

`Illuminate\Support\Str::startsWith()`

**Comment by bolechen** [comment]
> just `str` for me was not just the sole fix. I had to apply the namespace as well, within the blade.
> Is there a better way for this?
> 
> `Illuminate\Support\Str::startsWith()`

You need add the Str aliases line to `config/app.php`

```php
    'aliases' => [
        'App' => Illuminate\Support\Facades\App::class,
        'Str' => Illuminate\Support\Str::class,
//...
```

**Comment by saber13812002** [comment]
i use this solution 

You can pull them in with composer require laravel/helpers

https://github.com/UniSharp/laravel-filemanager/issues/834#issuecomment-535051351

**Comment by MxGutierrez** [comment]
Use Str::startsWith()
https://laravel.com/docs/7.x/helpers#method-starts-with
