### ISSUE TITLE
Make lenses attachable to dashboards

### ISSUE THREAD

**Issue by rodrigoreyes79** [laravel/nova-issues#1909]
As it is right now, only metrics and general cards are attachable to dashboards. It would be great if lenses could be attached too. 

Another way this could be done is to provide a full width Lens card that could be attached to the dashboard.

**Comment by cdbeaton** [comment]
I agree, this would be really useful.

**Comment by davidhemphill** [comment]
Seems like a decent idea to me.

In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
