### ISSUE TITLE
Viewing details of a failed action does not display the error message

### ISSUE THREAD

**Issue by adamthehutt** [laravel/nova-issues#191]
When running an action, Nova allows you to log a failure with: 

$this->markAsFailed($model, $exception);

The error message from the exception is being captured in the action_events table, but it is not displayed anywhere in the action log details screen.

**Comment by jaibrosa** [comment]
I ran into the same issue, but if you need you can overwrite the method of the class .

eg :` class ActionResource extends AR` ( is  the Actual resource )  this class has fields method  you can define any field here in your case may be ` Text::make('Error Msg','exception') `  

and  in Nova serviceprovider 
```
 Nova::resources([
        ActionResource::class ( this is the new class )
    ]);
```
dont forget to use __construct () in class .

May be taylor will provide a better way.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
