### ISSUE TITLE
Deleting file results in 404 error

### ISSUE THREAD

**Issue by lefuex** [laravel/nova-issues#1912]
When deleting a file this error shows up:

`Method Illuminate\Support\Collection::findFieldByAttribute does not exist.`

I think it refers to `FieldDestroyController` 
```
$field = $resource->updateFields($request)
                    ->whereInstanceOf(File::class)
                    ->findFieldByAttribute($request->field, function () {
                        abort(404);
                    });
```

**Comment by davidhemphill** [comment]
Sorry, but we are unable to debug your issue without a reproducible example. When you're able to demonstrate the issue, feel free to open a new issue.
