### ISSUE TITLE
How can I reach Nova dashboard?

### ISSUE THREAD

**Issue by for-ashraf** [laravel/nova-issues#1916]
![directorystructure](https://user-images.githubusercontent.com/46405183/64632438-7f321800-d412-11e9-9170-8731e5594ff4.png)
![phpmyadmin](https://user-images.githubusercontent.com/46405183/64632439-7fcaae80-d412-11e9-840b-67768a654273.png)
![composer json file](https://user-images.githubusercontent.com/46405183/64632664-f1a2f800-d412-11e9-8875-6fbc9da42fa6.png)
![env file](https://user-images.githubusercontent.com/46405183/64632665-f23b8e80-d412-11e9-9ef8-7b5f8606c296.png)

I have installed fresh laravel project and followed all the instructions provided at https://nova.laravel.com/docs/1.0/installation.html#installing-nova. Every thing goes fine. But still I am unable to view nova dashboard. Find enclosed herewith my directory structure, composer, .env and a screenshot of database. Kindly guide/resolve, please.

**Comment by Jubeki** [comment]
Did you look into `config/app.php` and if there is the NovaServiceProvider registered?

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).

**Comment by for-ashraf** [comment]
> Did you look into `config/app.php` and if there is the NovaServiceProvider registered?

![image](https://user-images.githubusercontent.com/46405183/64719452-b7545c00-d4e1-11e9-8ada-b88e69d36a3f.png)
Yes dear, it is registered.

**Comment by Tomizzi** [comment]
Hello,

Could you please take a look at ./config/nova.php ?
There's a nova path. :)

Regards,

**Comment by for-ashraf** [comment]
Dear, problem resolved. It was a port issue. Thanks


Sent from Yahoo Mail for iPhone


On Wednesday, September 11, 2019, 5:01 PM, Julius Kiekbusch <notifications@github.com> wrote:


Did you look into config/app.php and if there is the NovaServiceProvider registered?
