### ISSUE TITLE
Git PrePush Hook failing on Laravel\Nova\Tests\IntegrationTest

### ISSUE THREAD

**Issue by vbasky** [laravel/nova-issues#1918]
- Laravel Version: 6.0.3
- Nova Version: 2.3.0
- PHP Version: 7.3.9
- Database Driver and Version: 5.8 Mysql
- Operating System and Version: Mac Mojave 10.14.6
- Browser type and version: Safari

Nova Upgrade causing failure in pre-push hook scripts

`PHP Fatal error:  Uncaught Error: Class 'Laravel\Nova\Tests\IntegrationTest' not found in /Users/vikram/Sites/.../nova/tests/Controller/ActionControllerTest.php:36
Stack trace:
#0 /Users/vikram/Sites/.../vendor/phpunit/phpunit/src/Util/FileLoader.php(59): include_once()
#1 /Users/vikram/Sites/.../vendor/phpunit/phpunit/src/Util/FileLoader.php(47): `PHPUnit\Util\FileLoader::load('/Users/vikram/S...')`

### Steps To Reproduce

- Composer Upgrade to Nova 2.3.0
- Also performed `php artisan nova:publish`

I have cleared `vendor/laravel/nova` and done a `composer install` again just in case to be sure. 

`composer.json` has the entry

 `"laravel/nova": "*",`

**Comment by davidhemphill** [comment]
I'm sorry, but we can't help you debug anything not related to Nova specifically. This seems like an issue with Git. If you can demonstrate the issue only exists within Nova, please feel free to post a new issue.
