### ISSUE TITLE
Support for dynamic Dashboards Labels

### ISSUE THREAD

**Issue by cord** [laravel/nova-issues#1919]
Am able to use a custom dashboard multiple times using meta parameter:

```
(new kpi())->withMeta(['myScope' => 'Cars']),
(new kpi())->withMeta(['myScope' => 'Bikes'])
```

and in the dashboard class accessing the parameter with

`$this->meta`

great to dynamically generate Dashboards.

However the static functions:

    public static function label()

    public static function uriKey()

prohibit to customize the label and uriKey based on the parameters.

Any workaround for this? If not would be great to support dynamic labels

**Comment by cord** [comment]
my current workaround is to copy the view 

`dashboard/navigation.blade.php`

to published views and use a custom method to generate the label:

`{{ $dashboard->customLabel() }}`

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
