### ISSUE TITLE
Allow to serve fonts and images

### ISSUE THREAD

**Issue by alfonsobries** [laravel/nova-issues#192]
Just created two Nova packages one for a Froala editor and the second one for a Trumbowyg editor, in both cases, I need access to the fonts icons (in the case of the Froala editor) and to the SVG icons in the case of the Trumbowyg editor.

Currently is not possible to access to this assets through the Nova API so I created a publish method to copy the images and the fonts to the public folder.

I think that will be great if we have a FontController and ImagesController to instead serve these assets through the API.

Bonus question: It`s possible to contribute to Nova through a private repository or something?

**Comment by davidhemphill** [comment]
I think your package should just publish the assets as needed like other packages do.

**Comment by winter-ice** [comment]
same issue.
