### ISSUE TITLE
Metric Today range starts at Yesterday

### ISSUE THREAD

**Issue by timboozle** [laravel/nova-issues#1927]
- Laravel Version: 6.0.3
- Nova Version: 2.3.0
- PHP Version: 7.3.9

### Description

If I'm not mistaking the start date for the Today range should be `today()` but right now it is `now()->yesterday()` 

Code is in `currentRange()` in `src/Metrics/Value.php` on line 172

**Comment by rodrigoo-csantos** [comment]
+1

**Comment by jbrooksuk** [comment]
I'm looking at this now.
