### ISSUE TITLE
Nova resource double loading

### ISSUE THREAD

**Issue by ArroWsGM** [laravel/nova-issues#1928]
- Laravel Version: 5.8.35
- Nova Version: 2.3.0
- PHP Version: 7.3.5
- Database Driver and Version: 10.3.15-MariaDB
- Any
- Browser type and version: Chrome 76+
- Reproduction Repository: https://github.com/ArroWsGM/nova-bug

### Description

When using nova packages with customizable resource controller, placing resource in App\Nova or creating it with nova:resource command causing `[vuex] duplicate getter key:` error and possible sidebar menu item duplication.

### Steps To Reproduce
Install laravel with nova, install any package with customizable resource:
```bash
composer require optimistdigital/nova-menu-builder
php artisan vendor:publish --tag=nova-menu-builder-config
php artisan vendor:publish --tag=nova-menu-builder-migrations
php artisan migrate
```
Create resource
```bash
php artisan nova:resource Menu -m \OptimistDigital\MenuBuilder\Models\Menu
```
Adjus configuration
```php
//config/nova-menu.php:
use App\Nova\Menu;

return [
    'resource' => Menu::class,
];
```

Placing resource outside of `App\Nova` directory solves this problem, but breaks application structure.

**Comment by ArroWsGM** [comment]
Oh my. Maybe my english even worse than I thought. I try to explain one more time. We have some 3rd-party package. It loads their own resource(s) controller from own directory. For example,
nova-menu-builder:
```php
//MenuBuilderServiceProvider.php
...
public function boot() {
    ...
    Nova::resources([
       config('nova-menu.resource', MenuResource::class),
    ]);
}
...
```
nova-permission:
```php
//NovaPermissionTool.php
...
public function boot()
{
    Nova::resources([
        //this properties you can override when you register a tool with NovaServiceProvider->tools()
        $this->roleResource,
        $this->permissionResource,
    ]);
}
...
````
As you can see, both packages let us use custom resource class.
If I create some class outside of App\Nova directory and do all appropriate changes to attach this class to package, they still working fine at this point, but, this class is a resource controller, and to keep application structure as clean as possible, I need to place it into App\Nova directory. And if I do that, Nova automatically add this class to `$resources` property, and package does the same:
```
[2019-09-13 10:14:45] local.DEBUG: Array
(
    [0] => App\Nova\Test
    [1] => Laravel\Nova\Actions\ActionResource
    [2] => App\Nova\Test // <- duplicated element
    [3] => App\Nova\User
)
```
and all you needs to do is to get rid of this duplicates:
```php
//Nova.php
public static function resources(array $resources)
{
    static::$resources = array_unique(array_merge(static::$resources, $resources));

    return new static;
}
```
or maybe you can find a better solution.

**Comment by Ragash** [comment]
+1 it's annoying, and if resolution is that simple it's a shame to not have built-in
