### ISSUE TITLE
Trend metric by month shows current month inconsistently

### ISSUE THREAD

**Issue by CitizenBeta** [laravel/nova-issues#1929]
- Laravel Version: 5.8.35
- Nova Version: 2.3
- PHP Version: 7.2
- Database Driver and Version: mysql Ver 15.1 Distrib 10.3.17-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- Operating System and Version: Ubuntu 19.04
- Browser type and version: 76.0.3809.132 (Official Build) (64-bit)

### Description

$this->countByMonths($request, Order::where('brand_id', $this->brandId) returns this month as a value sometimes, not others. From what I can tell, this may be happening only when there's zero records for the current month. This seems unintended since zero value results are displayed for other months.

### Steps To Reproduce

$this->countByMonths($request, Order::where('brand_id', $this->brandId) for multiple brands, ones with no records this month don't display the current month, confusing comparisons between graphs, especially since it appears that showing zero record months is the intended outcome and does happen for months in the past within the time frame.

**Comment by jbrooksuk** [comment]
Sorry, but there's not enough information to go off of here. If the issue you have still persists, please feel free to open a new issue with all the details of what you're trying, what you expect to happen, what's happening, and how to reproduce it. Thanks!

**Comment by CitizenBeta** [comment]
This is resolved in v2.4
