### ISSUE TITLE
Feature Request: Allow create new records from belongsToMany attach screen

### ISSUE THREAD

**Issue by disitec** [laravel/nova-issues#193]
My proposal is having the ability to whether opening a modal or simply in a unsuccessful search (when searchable) hitting enter. Add a new record to the related table.

This way we avoid stop the process of attachment.

**Comment by dillingham** [comment]
https://github.com/tightenco/nova-package-development/issues/47

**Comment by dillingham** [comment]
@disitec great idea and implementation!

https://github.com/tightenco/nova-package-development/issues/47#issuecomment-424355256

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
