### ISSUE TITLE
Multiple Dashboards - support for parameters

### ISSUE THREAD

**Issue by cord** [laravel/nova-issues#1932]
referring to:
https://github.com/laravel/nova/pull/520

The requested enhancement would allow us to use custom dashboard with parameters, so in NovaServiceProvider.php we could do something like this:

(new kpi())->withMeta(['myScope' => 'Cars']),
(new kpi())->withMeta(['myScope' => 'Bikes'])

which would output two custom dashboard.

Necessary development:

- support for meta options to be transfered through the dashboard menu link as query parameter.
- access to the query parameters from within the dashboard class (label, cards..)

This would even allow us the build fully user customizable dashboards as the cards / metrics can be added programmatically. In combination with https://github.com/laravel/nova/pull/596 it would open up a lot of options to build nice dashboards with highly reusable components.

**Comment by vincenzoraco** [comment]
You can still achieve this outcome with a [custom tool](https://nova.laravel.com/docs/2.0/customization/tools.html#overview).

To return the data based on the scope, you can add a GET parameter to your route links:

```
<router-link tag="h3" :to="{name: 'my-custom-tool', query: {myScope: 'cars'}}">
    <span class="sidebar-label">
        My Cars Report
    </span>
</router-link>
<router-link tag="h3" :to="{name: 'my-custom-tool', query: {myScope: 'bikes'}}">
    <span class="sidebar-label">
        My Bikes Report
    </span>
</router-link>
```

You can then use the [tool routes](https://nova.laravel.com/docs/2.0/customization/tools.html#routing) to access the scope using the helper `request('myScope')` from the backend, and `{{ $route.query.myScope }}` from the VueJS component.

You will use the same template but you will generate the data based on the GET parameter.
