### ISSUE TITLE
Deleting file results in 500 server error

### ISSUE THREAD

**Issue by programmende** [laravel/nova-issues#1936]
- Laravel Version: 6.0.3
- Nova Version: 2.3.0
- PHP Version: 7.3
- Reproduction Repository: https://github.com/programmende/handmade (i have send you a invite @davidhemphill )
- Branch: feature/add-products

### Description

If i use the following field, i recive an 500 server error when i try to deleting the file with the generated delete button from field.

URL: 
/nova/resources/products/50/edit?viaResource=&viaResourceId=&viaRelationship=

Field: 
Avatar::make('Photo')->disk('public')->deletable()->prunable(),

Error response:
```json
{
   "message":"Method Illuminate\\Support\\Collection::findFieldByAttribute does not exist.",
   "exception":"BadMethodCallException",
   "file":"/home/forge/DOMAINFOLDER/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php",
   "line":104,
   "trace":[
      {
         "file":"/home/forge/DOMAINFOLDER/nova/src/Http/Controllers/FieldDestroyController.php",
         "line":29,
         "function":"__call",
         "class":"Illuminate\\Support\\Collection",
         "type":"->"
      },
      {
         "function":"handle",
         "class":"Laravel\\Nova\\Http\\Controllers\\FieldDestroyController",
         "type":"->"
      }
   ]
}
```

**Comment by king724** [comment]
Similar to #1819

**Comment by chinleung** [comment]
I did an investigation and found out that the issue comes from `Eminiarts\Tabs\TabsOnEdit`.

The trait has a method which returns `Illuminate\Support\Collection` instead of a `Laravel\Nova\Fields\FieldCollection`:

```
/**
 * Resolve the update fields.
 *
 * @param  \Laravel\Nova\Http\Requests\NovaRequest $request
 * @return \Illuminate\Support\Collection
 */
public function updateFields(NovaRequest $request)
{
    return collect(
        [
            'Tabs' => [
                'component' => 'tabs',
                'fields'    => $this->removeNonUpdateFields($request, $this->resolveFields($request)),
                'panel'     => Panel::defaultNameForUpdate($request->newResource()),
            ],
        ]
    );
}
```

Hence the method `findFieldByAttribute` doesn't exist.

**Comment by dkulyk** [comment]
This has been fixed and will be included in the next release. 👍
