### ISSUE TITLE
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'changes' at row 1 (SQL: insert into `action_events`

### ISSUE THREAD

**Issue by lilianjin** [laravel/nova-issues#1937]
- Laravel Version: 6.0
- Nova Version: 2.3
- PHP Version: 7.3
- Database Driver and Version:8.0
- Operating System and Version: Mac OS

### Description

SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'changes' at row 1 (SQL: insert into `action_events`

> If hiding this field is stored in the action event ?

**Comment by davidhemphill** [comment]
There's no information to debug an issue here.
