### ISSUE TITLE
Nova login page error "Failed to load resource: the server responded with a status of 404 (Not Found)"

### ISSUE THREAD

**Issue by for-ashraf** [laravel/nova-issues#1938]
Laravel version:6.0.3
Nov Verson: 2.3.0
PHP Version: 7.2.18
phpmysql
Windows 10 Home
Chrome (latest)

Im stuck since I have purchased nova licence. I am unable to view nova login page correctly(Even after a thousand tries). Kindly help me out, please.

I have followed all the steps mentioned at (https://nova.laravel.com/docs/2.0/installation.html) .
![1](https://user-images.githubusercontent.com/46405183/64908761-85c7d480-d71d-11e9-93c5-f146e13f2581.png)
![2](https://user-images.githubusercontent.com/46405183/64908787-b90a6380-d71d-11e9-8237-ac89815aa61f.png)

**Comment by gtrant** [comment]
I fixed this issue by creating a .htaccess file in public and added redirection. This assumes you are using apache.

Example:
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
       Options -MultiViews
   </IfModule>
   Options +FollowSymlinks
   RewriteEngine On

   # Redirect Trailing Slashes...
   RewriteRule ^(.*)/$ /$1 [L,R=301]

   # Handle Front Controller...
   RewriteCond %{REQUEST_FILENAME} !-d
   RewriteCond %{REQUEST_FILENAME} !-f
   RewriteRule ^ index.php [L]
</IfModule>
