### ISSUE TITLE
Minimum password length in tests still at 6 instead of 8

### ISSUE THREAD

**Issue by lasseeee** [laravel/nova-issues#1939]
- Laravel Version: 5.8.35
- Nova Version: 2.3.0
- PHP Version: 7.3
- Database Driver and Version: N/A
- Operating System and Version: N/A
- Browser type and version: N/A
- Reproduction Repository: N/A

### Description

The `vendor/laravel/nova/tests/Fixtures/UserResource.php` reads:

```
Text::make('Password')
                                ->onlyOnForms()
                                ->rules('required', 'string', 'min:6'),
```

According to the [Laravel 5.8 password length standard](https://laravel.com/docs/5.8/upgrade#authentication) it should be `min:8` instead of `min:6`.

### Steps To Reproduce

Install Nova `v2.3.0` and open `vendor/laravel/nova/tests/Fixtures/UserResource.php`.

**Comment by davidhemphill** [comment]
This isn't a bug.

**Comment by lasseeee** [comment]
Still a logical discrepancy between Nova and the framework at versions numbers which ought to match.
