### ISSUE TITLE
Singular label is not used on "Has Many" field

### ISSUE THREAD

**Issue by rodrigoreyes79** [laravel/nova-issues#1940]
- Laravel Version: 5.8.35
- Nova Version: 2.2.0
- PHP Version: 7.2.19-1
- Operating System and Version: ubuntu18.04.1
- Browser type and version: Chrome (Mac) 76.0.3809.100

### Description

Singular label is not used on "Has Many" field. 

Ex. In this case, singular label is "Comentario Médico". Instead, Nova is taking the plural form ("Comentarios Médicos") and removing the last "s".

![Captura de Pantalla 2019-09-14 a la(s) 15 54 16](https://user-images.githubusercontent.com/3924426/64913594-84d87800-d708-11e9-8d71-fabd94467591.png)

### Steps To Reproduce

Create a Has Many relationship to an object whose plural label ends in "s" but whose singular form cannot be created by taking the ending "s" of the plural label.

**Comment by davidhemphill** [comment]
Since your example uses a language other than English, please post the code that fails using your language, please.

**Comment by p4rz1val** [comment]
You can set the singuralLabel in your HasMany field like so:
```
HasMany::make('Aviones', 'airplanes', 'App\Nova\Avion')
    ->singularLabel('Aviones'),
```
