### ISSUE TITLE
BelongsTo readonly has no affect

### ISSUE THREAD

**Issue by davidgabbay** [laravel/nova-issues#1941]
does not work on nova 2.3.0

- Laravel Version:5.8.35
- Nova Version: 2.3.0
- PHP Version: 7.2.11
- Database Driver and Version: sqlsrv
- Operating System and Version: win10
- Browser type and version: chrom

### Description

->readonly(true)

Does not work on nova 2.3.0 and it worked on earlier version.

### Steps To Reproduce

BelongsTo::make('user', 'User', 'App\Nova\User')->sortable()->withMeta(['textAlign' => 'right'])->default(function(NovaRequest $request) {
                return $request->user()->id ; })->readonly(true),

**Comment by davidgabbay** [comment]
sorry, you can close it
i see that if i remove the 
->searchable()
it works fine

**Comment by jbrooksuk** [comment]
I've updated the title of this issue to better reflect the actual issue here :)

**Comment by jbrooksuk** [comment]
I've investigated this and there are two things:

1. `readonly` **does** work on the `BelongsTo` field.
2. The `BelongsTo` field does not have a `default` method, which suggest that you're using a third-party package to replace `BelongsTo` field. Please open this issue on the package repository.
