### ISSUE TITLE
Action gets Symfony\Component\HttpKernel\Exception\HttpException with No Message

### ISSUE THREAD

**Issue by bongnaval04** [laravel/nova-issues#1943]
- Laravel Version: 5.8
- Nova Version: 2.2
- PHP Version: 7.2
- Database Driver and Version: MySQL 5.7.24
- Operating System and Version: win10
- Browser type and version: Chrome

### Description

I have this Order Resource and added two actions, first you have to set the order as in transit using the OrderInTransit Action and then if it is delivered use the OrderDelivered Action.

In my `App\Nova\Actions\OrderInTransit` I have this

```
public function handle(ActionFields $fields, Collection $models)
{
    return DB::transaction(function() use ($fields, $models) {
        $delivery_cost = $fields->delivery_cost * 100;
        foreach ($models as $model) {
            // set as in transit
            // set reference number and courrier
            $model->update([
                'delivered' => 1,
                'remarks' => 'Courrier: ' . $fields->courrier . ', Reference: ' . $fields->reference,
                'delivery_cost' => $delivery_cost,
                'processed_at' => now()
            ]);
            // create notification
        }
        return Action::message('Order is in transit!');
    });
}
```

Once the order is now in transit, I have to update it if the client have received the order using `App\Nova\Actions\OrderDelivered`. `OrderDelivered` still has nothing in it, it is freshly created with an empty `handle()` and `fields()`.

And here is the `App\Nova\Order` Resource action,

```
public function actions(Request $request)
{
    return [
        (new OrderInTransit)
            ->canSee(function($request) {
                return (optional($request->findModelQuery()->first())->delivered == 0) ? true : false;
            })
            ->canRun(function($request, $user) {
                return true;
            }),
        (new OrderDelivered)
            ->canSee(function($request) {
                return (optional($request->findModelQuery()->first())->delivered == 1) ? true : false;
            })
            ->canRun(function($request, $user) {
                return true;
            }),
    ];
}
```

OrderInTransit works well and it updates the Model. But when I try using the `OrderDelivered` Action it redirects me to `nova 403`.

Inspecting my Browser Network Activities i got this,

> message: "", exception: "Symfony\Component\HttpKernel\Exception\HttpException"

from 

> /nova-api/orders/action?action=order-delivered&pivotAction=false&search=&trashed=&viaResource=&viaResourceId=&viaRelationship=

I also have my policies set

```
protected $policies = [
    'App\Payment' => 'App\Policies\PaymentPolicy',
    'App\Order' => 'App\Policies\OrderPolicy',
];
```

Its weird because the first action runs and the second action becomes `403 Forbidden`

**Comment by bongnaval04** [comment]
If I set my order delivered `canSee()` into `true` the action proceeds

```
(new OrderDelivered)
            ->canSee(function($request) {
                return true;
            })
            ->canRun(function($request, $user) {
                return true;
            }),
```

**Comment by khalil-htme** [comment]
confirmed i have the same error, its why i deleted mine and going to bump here

**Comment by khalil-htme** [comment]
[https://imgur.com/EMJjLeY](https://imgur.com/EMJjLeY) for image of the console

**Comment by skoyah** [comment]
> * Laravel Version: 5.8
> * Nova Version: 2.2
> * PHP Version: 7.2
> * Database Driver and Version: MySQL 5.7.24
> * Operating System and Version: win10
> * Browser type and version: Chrome
> 
> ### Description
> I have this Order Resource and added two actions, first you have to set the order as in transit using the OrderInTransit Action and then if it is delivered use the OrderDelivered Action.
> 
> In my `App\Nova\Actions\OrderInTransit` I have this
> 
> ```
> public function handle(ActionFields $fields, Collection $models)
> {
>     return DB::transaction(function() use ($fields, $models) {
>         $delivery_cost = $fields->delivery_cost * 100;
>         foreach ($models as $model) {
>             // set as in transit
>             // set reference number and courrier
>             $model->update([
>                 'delivered' => 1,
>                 'remarks' => 'Courrier: ' . $fields->courrier . ', Reference: ' . $fields->reference,
>                 'delivery_cost' => $delivery_cost,
>                 'processed_at' => now()
>             ]);
>             // create notification
>         }
>         return Action::message('Order is in transit!');
>     });
> }
> ```
> 
> Once the order is now in transit, I have to update it if the client have received the order using `App\Nova\Actions\OrderDelivered`. `OrderDelivered` still has nothing in it, it is freshly created with an empty `handle()` and `fields()`.
> 
> And here is the `App\Nova\Order` Resource action,
> 
> ```
> public function actions(Request $request)
> {
>     return [
>         (new OrderInTransit)
>             ->canSee(function($request) {
>                 return (optional($request->findModelQuery()->first())->delivered == 0) ? true : false;
>             })
>             ->canRun(function($request, $user) {
>                 return true;
>             }),
>         (new OrderDelivered)
>             ->canSee(function($request) {
>                 return (optional($request->findModelQuery()->first())->delivered == 1) ? true : false;
>             })
>             ->canRun(function($request, $user) {
>                 return true;
>             }),
>     ];
> }
> ```
> 
> OrderInTransit works well and it updates the Model. But when I try using the `OrderDelivered` Action it redirects me to `nova 403`.
> 
> Inspecting my Browser Network Activities i got this,
> 
> > message: "", exception: "Symfony\Component\HttpKernel\Exception\HttpException"
> 
> from
> 
> > /nova-api/orders/action?action=order-delivered&pivotAction=false&search=&trashed=&viaResource=&viaResourceId=&viaRelationship=
> 
> I also have my policies set
> 
> ```
> protected $policies = [
>     'App\Payment' => 'App\Policies\PaymentPolicy',
>     'App\Order' => 'App\Policies\OrderPolicy',
> ];
> ```
> 
> Its weird because the first action runs and the second action becomes `403 Forbidden`

Check if when using the second action it updates the model as well.

I'm running in the same issue and I think there is some redirect behind the scenes that passes conflicts with the action.

My theory is that it updates the model than the redirect passes again through the `canSee` and returns forbidden because now, after the update , it returns false.

Is that the case? Can you confirm if updates the model after running OrderDevlivered?

**Comment by bongnaval04** [comment]
> > * Laravel Version: 5.8
> > * Nova Version: 2.2
> > * PHP Version: 7.2
> > * Database Driver and Version: MySQL 5.7.24
> > * Operating System and Version: win10
> > * Browser type and version: Chrome
> > 
> > ### Description
> > I have this Order Resource and added two actions, first you have to set the order as in transit using the OrderInTransit Action and then if it is delivered use the OrderDelivered Action.
> > In my `App\Nova\Actions\OrderInTransit` I have this
> > ```
> > public function handle(ActionFields $fields, Collection $models)
> > {
> >     return DB::transaction(function() use ($fields, $models) {
> >         $delivery_cost = $fields->delivery_cost * 100;
> >         foreach ($models as $model) {
> >             // set as in transit
> >             // set reference number and courrier
> >             $model->update([
> >                 'delivered' => 1,
> >                 'remarks' => 'Courrier: ' . $fields->courrier . ', Reference: ' . $fields->reference,
> >                 'delivery_cost' => $delivery_cost,
> >                 'processed_at' => now()
> >             ]);
> >             // create notification
> >         }
> >         return Action::message('Order is in transit!');
> >     });
> > }
> > ```
> > 
> > 
> > Once the order is now in transit, I have to update it if the client have received the order using `App\Nova\Actions\OrderDelivered`. `OrderDelivered` still has nothing in it, it is freshly created with an empty `handle()` and `fields()`.
> > And here is the `App\Nova\Order` Resource action,
> > ```
> > public function actions(Request $request)
> > {
> >     return [
> >         (new OrderInTransit)
> >             ->canSee(function($request) {
> >                 return (optional($request->findModelQuery()->first())->delivered == 0) ? true : false;
> >             })
> >             ->canRun(function($request, $user) {
> >                 return true;
> >             }),
> >         (new OrderDelivered)
> >             ->canSee(function($request) {
> >                 return (optional($request->findModelQuery()->first())->delivered == 1) ? true : false;
> >             })
> >             ->canRun(function($request, $user) {
> >                 return true;
> >             }),
> >     ];
> > }
> > ```
> > 
> > 
> > OrderInTransit works well and it updates the Model. But when I try using the `OrderDelivered` Action it redirects me to `nova 403`.
> > Inspecting my Browser Network Activities i got this,
> > > message: "", exception: "Symfony\Component\HttpKernel\Exception\HttpException"
> > 
> > 
> > from
> > > /nova-api/orders/action?action=order-delivered&pivotAction=false&search=&trashed=&viaResource=&viaResourceId=&viaRelationship=
> > 
> > 
> > I also have my policies set
> > ```
> > protected $policies = [
> >     'App\Payment' => 'App\Policies\PaymentPolicy',
> >     'App\Order' => 'App\Policies\OrderPolicy',
> > ];
> > ```
> > 
> > 
> > Its weird because the first action runs and the second action becomes `403 Forbidden`
> 
> Check if when using the second action it updates the model as well.
> 
> I'm running in the same issue and I think there is some redirect behind the scenes that passes conflicts with the action.
> 
> My theory is that it updates the model than the redirect passes again through the `canSee` and returns forbidden because now, after the update , it returns false.
> 
> Is that the case? Can you confirm if updates the model after running OrderDevlivered?

It does not update my model.

**Comment by bongnaval04** [comment]
I used this as a workaround 

```
->canSee(function($request) {
     if ($request->has('resourceId')) {
          return (optional($request->findModelQuery()->first())->delivered == 1) ? true : false;
     }

     return true;
})
```

**Comment by skoyah** [comment]
yep. That's what I ended up doing too.

**Comment by dkulyk** [comment]
I've add PR for using canRun for resolving actions for detail page:
```php
public function actions(Request $request)
{
    return [
        (new OrderInTransit)
            ->canRun(function($request, $order) {
                return $order->delivered == 0;
            }),
        (new OrderDelivered)
            ->canRun(function($request, $user) {
                return $order->delivered == 1;
            }),
    ];
}
```

**Comment by janverhulst** [comment]
Can confirm this issue and I used the same workaround as described in one of the comments.
