### ISSUE TITLE
Http response to work with Vapor hosting

### ISSUE THREAD

**Issue by matthewhutchings** [laravel/nova-issues#1944]
- Laravel Version: 6.0
- Nova Version: 2
- PHP Version: 7.3
- Database Driver and Version: AWS RDS 

### Description

I have switched over to Vapor and unable to download a file from S3. Download file just shows "Server Error" with no logs. 

I suspect Nova this is what is needed 

```
return $response->withHeaders([
    'X-Vapor-Base64-Encode' => 'True',
]);
```

I do not believe there is a way to attach a Header response to the file download. Could this be fixed to enable downloads?

**Comment by benjamincrozat** [comment]
Would be great!

**Comment by jbrooksuk** [comment]
I've not confirmed this, but I believe you could specify the `download` method on your field:

```
File::make('File')->download(function ($resource) {
    return Storage::disk('s3')->download('attribute', 'name', [
            'X-Vapor-Base64-Encode' => 'True',
    ])
}),
```

https://laravel.com/docs/5.8/filesystem#downloading-files
