### ISSUE TITLE
There was a problem submitting the form is not translatable to other languages

### ISSUE THREAD

**Issue by wemersonrv** [laravel/nova-issues#1946]
- Laravel Version: 6.0.3
- Nova Version: 2.3.0
- PHP Version: 7.3.9
- Database Driver and Version:  MySQL 5.7.24 Community Server
- Operating System and Version: Windows 10 64 Bits
- Browser type and version: Google Chrome 76.0.3809.132 64 bits

### Description

The validation error message at form bottom is not in translation files.. i try to add it there in `resources/lang/vendor/nova/pt-br.json` to translate it to my language but not works.

See in image below i am using `pt-br` translation but not works... and of course, i've manually added the message entry to localization json files...

![image](https://user-images.githubusercontent.com/2028673/65075432-47285900-d96d-11e9-9d9a-3eda81d68a01.png)

### Steps To Reproduce

Just use other language instead english and force a validation error when save resources...

**Comment by bolechen** [comment]
+1

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍

**Comment by Kczmrk** [comment]
Is it fixed? I still have that issue.

**Comment by jbrooksuk** [comment]
Yes, the `There was a problem submitting the form.` string is translatable.
