### ISSUE TITLE
Actionable error: Class name must be a valid object or a string

### ISSUE THREAD

**Issue by AminulBD** [laravel/nova-issues#1947]
- Laravel Version: 6.0.2
- Nova Version: 2.3.1
- PHP Version: 7.3.9
- Database Driver and Version:  8.0.17
- Operating System and Version: MacOS Mojave (With Laravel Valet Latest)
- Browser type and version: Chrome 77.0.3865.75
- Reproduction Repository: N/A

### Description

I'm trying to display the Actionable Log in the specific model but the resource is throwing an error with message `Class name must be a valid object or a string`.

I didn't create any extra action for the model I just want to show the log for default events like `created`, `updated`, `deleted`, `restored` etc.

### Steps To Reproduce

Generated a nova resource by cli `php artisan nova:resource Post` and added `Actionable` trait as below.

````
<?php

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Laravel\Nova\Actions\Actionable;

class Order extends Model
{
    use Actionable, SoftDeletes;
````
MySQL data (Some columns are removed for github)
````
+----+--------------------------------------+---------+--------+-----------------+---------------+-------------+-----------+------------+----------+--------+----------+
| id | batch_id                             | user_id | name   | actionable_type | actionable_id | target_type | target_id | model_type | model_id | fields | status   |
+----+--------------------------------------+---------+--------+-----------------+---------------+-------------+-----------+------------+----------+--------+----------+
|  1 | 8eae8ac4-cdf9-4523-a64e-c0ba6e200c1c |       1 | Create | App\Post        |           101 | App\Post    |       101 | App\Post   |      101 |        | finished |
+----+--------------------------------------+---------+--------+-----------------+---------------+-------------+-----------+------------+----------+--------+----------+
````

Just browsing the Post resource and add, edit or delete any item of them.

### Error Details
![Screenshot 2019-09-18 at 4 50 17 PM](https://user-images.githubusercontent.com/5006546/65142406-748c0a00-da34-11e9-8130-55fc6a8cffe3.png)

**Comment by AminulBD** [comment]
Hello folks,

I changed the name of guard provider in the `auth.php` config file and that causes the issue.

**Comment by barreirinha** [comment]
> Hello folks,
> 
> I changed the name of guard provider in the `auth.php` config file and that causes the issue.
> 
> Maybe related with #949

Thanks, this comment gave-me a light. Same thing happened to me and a did not know why. I fixed it easily adding a single line in my auth.php

Was like this

```php
'providers' => [

        'users' => [
            'driver' => 'mycustomprovider',
        ],
```

now:
```php
'providers' => [

        'users' => [
            'driver' => 'mycustomprovider',
            'model' => App\User::class,
        ],
```
