### ISSUE TITLE
Create Resource Without Table And Model In Nova

### ISSUE THREAD

**Issue by jahid56** [laravel/nova-issues#1948]
I want To Create A resource Called Settings Where There are Tag, Brand exists In The Settings Resource. But I could not able to create a Resource Without Table and Model. I also need two seperate Menu In Setting Which Use Same table called `tags`. For Example I need to Name a Menu Brand for `tags` table which `type is 0` & Tag Menu Which `type is 1`. But Could not able to create this. I am using NOVA Version 1

**Comment by mayur99092** [comment]
Is possible to create nova resource without table and model?
