### ISSUE TITLE
Resource detail metric doesn't refresh when underlying values change

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#1949]
Laravel Version: 5.8.24
Nova Version: 2.0.6
PHP Version: 7.2.10
Database Driver and Version: MySQL 5.7.23
Operating System and Version: Windows 10 (64 bits)
Browser type and version: Chrome 76 (64 bits)

Description
I've got a trend metric on a user page which shows points per day. When i adjust points with an action, the related resource is refreshed, but not the metric. 

Seems to me this should be done or at least possible with some method.

Steps To Reproduce
Create metric on resource detail
Use action to change value shown in metric & perform action
Nothing happens in the metric

**Comment by jbrooksuk** [comment]
Metrics may cache their results. Run `php artisan cache:clear` or disable caching on the metric.

**Comment by preliot** [comment]
@jbrooksuk I'm aware that metrics can cache results, but it's disabled. 

I'm still seeing this bug, i will try it again:

It's about a metric on a resource **detail** page. When i use an action on that same resource detail page, the metric is not refreshed. Resource details are refreshed, related resources are refreshed, but nothing happens to the metric.

Is this a bug and should a metric on a detail page be refreshed? Or is this not implemented yet?

**Comment by jbrooksuk** [comment]
Thanks for clarifying. This is not implemented in Nova. Actions do not refresh a metric.

**Comment by preliot** [comment]
And now they do, thanks @jbrooksuk!

Nova 2.5.0 adds abbility to refresh metrics when needed. 

`->refreshWhenActionRuns()`

**Comment by JoshMoreno** [comment]
Are detail cards suppose to refresh too? If so, there may be a bug. 

On route change to another model, my card persists. I had to refactor  to fetching the data in my component rather than letting php pass it to js `this.card.myMeta`
