### ISSUE TITLE
Question: Access to nova Excerpt component from a custom field

### ISSUE THREAD

**Issue by alfonsobries** [laravel/nova-issues#195]
Im creating a custom field but in the `DetailField` i want to use the Excerpt component that is already in the nova components, is there any way to get the user paths for the Nova package (the one defined in `config/nova.php` to make a dynamic route to import the component?

**Comment by noahlocke** [comment]
In your DetailField.vue file:
```
import Excerpt from '../../../../../nova/resources/js/components/Excerpt.vue'
```

**Comment by fdabek1** [comment]
@noahlocke I tried to do something similar for the FakeCheckbox.vue and got an error:

> =0!E:/project/nova/resources/js/components/Index/FakeCheckbox.vue
> Module build failed: ReferenceError: Unknown plugin "transform-vue-jsx" specified in "E:\\project\\nova\\.babelrc" at 1, attempted to resolve relative to "E:\\project\\nova"

I tried to install the babel-plugin-transform-vue-jsx using the below link, but the error still comes up:

https://github.com/vuejs/babel-plugin-transform-vue-jsx

**Comment by davidhemphill** [comment]
I'll make the excerpt component globally available so you can just use that instead of messing with the /nova directory. Should come in the next release.

**Comment by davidhemphill** [comment]
Yep it did make it in. Should just need to use it like so: `<excerpt>` and then define the props you need.
