### ISSUE TITLE
Trend graph tooltip positioning is misaligned on first hover

### ISSUE THREAD

**Issue by matthiggins** [laravel/nova-issues#1950]
- Laravel Version: 5.8.35
- Nova Version: v2.3.1
- Browser type and version: Chrome 76.0.3809.132 | Safari 12.1.2

### Description
When hovering over a specific point on a Trend Metric graph the tooltip is offset to the right and down a bit.  This only happens on the first hover interaction.  All hover interactions after the first one appear to function as expected.  After a page refresh the issue shows up again.

### Steps To Reproduce

- Generate a Trend metric with a populated graph
- Mouse over a single point in the graph.  The tooltip is not positioned centered and above the point.
- Mouse out of the single point to hide the tooltip.
- Mouse over the single point again (the same point or any other point) and the tooltip is correctly positioned.

### Screenshots

First mouse over (unexpected behavior)
![image](https://user-images.githubusercontent.com/422780/65179042-a34bb580-da1f-11e9-9abe-1536145f14f8.png)

All subsequent mouse overs (expected behavior)
![image](https://user-images.githubusercontent.com/422780/65179151-d8f09e80-da1f-11e9-92f0-52d0538f4ffd.png)

If there is any more information that I can provide just let me know!

Thanks for the wonderful tool.  It's been very valuable for many of my projects.

**Comment by jbrooksuk** [comment]
Confirmed.

**Comment by jbrooksuk** [comment]
Hmm, toggling some options around works:

```
anchorToPoint: false,
appendToBody: true,
```

But then you end up with the tooltip not fixing itself to each point, which is strange behaviour.
