### ISSUE TITLE
->asHtml() is not working well on nova V2.3.0

### ISSUE THREAD

**Issue by davidgabbay** [laravel/nova-issues#1951]
->asHtml() is not working well on nova V2.3.0

does not work on nova 2.3.0

Laravel Version:5.8.35
Nova Version: 2.3.0
PHP Version: 7.2.11
Database Driver and Version: sqlsrv
Operating System and Version: win10
Browser type and version: chrom

### Description

using {$tracking_number} in a link does not convert to its value

### Steps To Reproduce

                Text::make('Tracking number', function () {

                $tracking_number = $this->tracking_number;

                return '<a href="https://www.parcelmonitor.com/track-israel-post/track-it-online/?pParcelIds={$tracking_number}">@{$tracking_number}</a>';
                
            })->asHtml(),

================================
the page changes the source code i wrote above.
Making it in quote or as code does not help.

i do it exactly like

https://nova.laravel.com/docs/2.0/resources/fields.html#text-field

#Formatting Text As Links

**Comment by matthiggins** [comment]
It should just be 
`return $tracking_number;`

If you use 
`return '@{$tracking_number}` it's going to output **@{$tracking_number}**.

**Comment by dkulyk** [comment]
Interpolation works only with double quotes: "@{$tracking_number}"

**Comment by davidgabbay** [comment]
the page changed the source code i wrote.

here is the source code:

/*
Text::make('Tracking number', function () {
                $tracking_number = $this->tracking_number;
                return '<a href="https://www.parcelmonitor.com/track-israel-post/track-it-online/?pParcelIds={$tracking_number}">@{$tracking_number}</a>';
                
            })->asHtml(),
*/

**Comment by davidgabbay** [comment]
> Interpolation works only with double quotes: "@{$tracking_number}"
