### ISSUE TITLE
Nova routes not exist

### ISSUE THREAD

**Issue by alexelev** [laravel/nova-issues#1952]
- Laravel Version: 6.0.3
- Nova Version: 2.3.1
- PHP Version: 7.3.2
- Database Driver and Version: MySQL 5.7-x64
- Operating System and Version: Windows 10 (1903 Build 18362.356)

### Description

After creating new laravel project and adding to it nova package [step by step](https://nova.laravel.com/docs/2.0/installation.html#installing-nova-via-composer) I get 404 on `/nova` route. I checked `php artisan route:list` and got this

- _ignition/assets
- _ignition/execute-solution
- nova-api/{resource}
- nova-api/{resource}/action
- nova-api/{resource}/actions
- nova-api/{resource}/associatable/{field}
- nova-api/{resource}/cards
- nova-api/{resource}/count
- nova-api/{resource}/creation-fields
- nova-api/{resource}/creation-pivot-fields/{relatedResource}
- nova-api/{resource}/detach
- nova-api/{resource}/field/{field}
- nova-api/{resource}/filters
- nova-api/{resource}/force
- nova-api/{resource}/lens/{lens}
- nova-api/{resource}/lens/{lens}/action
- nova-api/{resource}/lens/{lens}/actions
- nova-api/{resource}/lens/{lens}/cards
- nova-api/{resource}/lens/{lens}/count
- nova-api/{resource}/lens/{lens}/filters
- nova-api/{resource}/lens/{lens}/force
- nova-api/{resource}/lens/{lens}/metrics
- nova-api/{resource}/lens/{lens}/metrics/{metric}
- nova-api/{resource}/lens/{lens}/restore
- nova-api/{resource}/lenses
- nova-api/{resource}/metrics
- nova-api/{resource}/metrics/{metric}
- nova-api/{resource}/morphable/{field}
- nova-api/{resource}/relate-authorization
- nova-api/{resource}/restore
- nova-api/{resource}/soft-deletes
- nova-api/{resource}/trix-attachment/{field}
- nova-api/{resource}/trix-attachment/{field}/{draftId}
- nova-api/{resource}/{resourceId}
- nova-api/{resource}/{resourceId}/attach-morphed/{relatedResource}
- nova-api/{resource}/{resourceId}/attach/{relatedResource}
- nova-api/{resource}/{resourceId}/attachable/{field}
- nova-api/{resource}/{resourceId}/download/{field}
- nova-api/{resource}/{resourceId}/field/{field}
- nova-api/{resource}/{resourceId}/metrics/{metric}
- nova-api/{resource}/{resourceId}/update-attached/{relatedResource}/{relatedResourceId}
- nova-api/{resource}/{resourceId}/update-fields
- nova-api/{resource}/{resourceId}/update-pivot-fields/{relatedResource}/{relatedResourceId}
- nova-api/{resource}/{resourceId}/{relatedResource}/{relatedResourceId}/field/{field}

As you can see there is no routes such as `nova/login` or `nova/logout` in this list. Is this an issue or am I doing something wrong?

### Steps To Reproduce

1. Create new laravel project
2. Install `laravel/nova` package by composer
3. Go to `/nova` in your browser

**Comment by S-Arba** [comment]
Did you add the /admin path on your config/nova.php

**Comment by alexelev** [comment]
> Did you add the /admin path on your config/nova.php

No. What for? All works perfectly on Ubuntu 18.04 and 19.04. If you mean `path` in `config/nova.php` then its value `/nova` - I did not change default config.

**Comment by jbrooksuk** [comment]
@alexelev just to confirm, did you register `App\Providers\NovaServiceProvider::class` in your `app.providers` array?

**Comment by alexelev** [comment]
> @alexelev just to confirm, did you register `App\Providers\NovaServiceProvider::class` in your `app.providers` array?

![Screenshot_105](https://user-images.githubusercontent.com/3392106/65277646-0712d300-db33-11e9-8ca1-295a4eb48c6e.jpg)

**Comment by rasmustaarnby** [comment]
@alexelev I had the same issue but fixed it by running `php artisan optimize`, effectively clearing caches. Guessing you just need to clear the different caches.

**Comment by jbrooksuk** [comment]
Try running `php artisan config:cache`.
