### ISSUE TITLE
GROUP BY-related error when using Postgres

### ISSUE THREAD

**Issue by BrekiTomasson** [laravel/nova-issues#1954]
- Laravel Version: 5.8.33
- Nova Version: 2.3.1
- PHP Version: 7.3.9
- Database Driver and Version: Laravel's native Postgres driver.
- Operating System and Version: Alpine Linux (via Docker)
- Browser type and version: Not relevant.
- Reproduction Repository: Not public.

### Description

This error was already submitted in #376, which was closed without further comment. I can, however, confirm that the problem remains in the most recent version of Nova.

The error presents itself as "Grouping error: 7 ERROR: column "blog_entries.id" must appear in the GROUP BY clause or be used in an aggregate function" when browsing any of my Nova resources, even when they do not have any aggregation defined in the resource file. 

The error is generated in `Laravel\Nova\Http\Controllers\ResourceCountController@show`, with the query being generated, in this particular case, looking something like:

`select count(*) as aggregate from "blog_entries" order by "blog_entries"."id" desc`

I really don't understand this query. If you're selecting a count, then why are you defining an `order by`? The query works just fine if you remove the `order by`, and makes a whole lot more sense that way, too.

**Comment by jbrooksuk** [comment]
Strange. Using latest Nova, MySQL and Telescope, then browsing to a resource, I see this for the `count` endpoint:

![image](https://user-images.githubusercontent.com/246103/65508286-c8c93b00-dec7-11e9-96cf-4ebd656610d0.png)

So you can see that the order by is not applied and I confirmed that this is the same no matter the order.

Do you have any scopes on your models?

**Comment by jbrooksuk** [comment]
Sorry, but there's not enough information to go off of here. If the issue you have still persists, please feel free to open a new issue with all the details of what you're trying, what you expect to happen, what's happening, and how to reproduce it. Thanks!

**Comment by BrekiTomasson** [comment]
Sorry; completely forgot to update this. But if somebody comes across this issue while encountering the same problem, my problem was this: I was using the `Eloquence` package to enhance some of the default methods available in `Eloquent`'s `Builder` class, and apparently it was injecting an `ORDER BY` automatically into all queries. As soon as I stopped extending this model with `Eloquence`, everything started working as intended again.
