### ISSUE TITLE
Cancel button alignment across views

### ISSUE THREAD

**Issue by beatwiz** [laravel/nova-issues#1956]
- Laravel Version: Latest
- Nova Version: Latest
- PHP Version: 7.3

All form views that have the `<cancel-button />` are contained inside a div that has `class="flex items-center"`. Except on `Attach.vue` and `UpdateAttached.vue` where its missing the `items-center` class, so the cancel button becomes aligned to the top.

![image](https://user-images.githubusercontent.com/8360167/65286934-39273380-db39-11e9-922c-a8fef8d47660.png)

Adding the items-center class to the div on UpdateAttached.vue fixes the issue.

**Comment by jbrooksuk** [comment]
This was fixed back in v2.2.0 - https://github.com/laravel/nova/commit/8bea363766023e0bcd91f916e58593d5bdbeda88 

Please upgrade.
