### ISSUE TITLE
Default Field layout customisation

### ISSUE THREAD

**Issue by kohutovic** [laravel/nova-issues#1957]
Hi, 
currently, it's not possible to change the layout of defaultField component. For a `text-area` it gets `fullWidthContent` property but for others (like text) the fullWidthContent is set to default false. It would be nice if we have better control over the value/label layout. 
Now for all text fields, it has `w-1/2` and I cannot force it to have `w-full`. The only way now is to create a custom component which is not very convenient. Thanks

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
