### ISSUE TITLE
pickerFormat method is not found on Date or DateTime fields

### ISSUE THREAD

**Issue by rodrigoreyes79** [laravel/nova-issues#1958]
- Laravel Version: 5.8.35
- Nova Version: 2.2.0
- PHP Version: 7.2.19-1
- Operating System and Version: ubuntu18.04.1
- Browser type and version: Chrome (Mac) 76.0.3809.100

### Description

pickerFormat method is not defined either on Date or DateTime fields.

**Comment by jbrooksuk** [comment]
It looks like these methods may have made it in to v2.3.0/1, can you upgrade and try again, please.
