### ISSUE TITLE
BelongsToMany Resource Relationship generate ActionEvent with wrong attributes

### ISSUE THREAD

**Issue by yaim** [laravel/nova-issues#1959]
- Laravel Version: v5.8.35
- Nova Version: v2.3.1
- PHP Version: v7.2.19
- Database Driver and Version: Postgres v10.8
- Operating System and Version: CentOS v7
- Browser type and version: Chrome v73.0.3683.75

### Description

After attaching a BelongsToMany Nova Resource, I keep getting error toast of `"SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type id: "2574" (SQL: select * from "tags" where "tags"."id" = 2574 limit 1)"`, which is thrown by `/action-events` route:
![Screenshot_2](https://user-images.githubusercontent.com/2439084/65374982-347f8e00-dca5-11e9-87c1-84ecf3e75ae9.png)

I digged into the code and found out that in `ActionEvent` model in `forAttachedResource` method, target (relation model) ID is being set as same as actionable (resource model) ID:
![Screenshot_3](https://user-images.githubusercontent.com/2439084/65375099-d18ef680-dca6-11e9-9b5b-b70c532bd8ee.png)

I changed the line to `'target_id' => $request->{$request->relatedResource},` and everything seems to work now.

### Steps To Reproduce

1 - Setup Nova
2 - Make 2 models with BelongsToMany relationship and setup their nova resource
3 - Attach the model to another

**Comment by MehdiNosrati** [comment]
Same problem! Could you help please?

**Comment by MehdiNosrati** [comment]
Same problem! Would you help, please?

**Comment by TheSETJ** [comment]
It'll be nice if we see a response from you guys here. Any ETA for fixing this? Any workaround except messing with vendor packages manually?
@taylorotwell @davidhemphill

**Comment by jcarouth** [comment]
Currently experiencing this same issue.

**Comment by jbrooksuk** [comment]
Could somebody please provide a repo that reproduces this issue in a real world example? Thanks!

**Comment by TheSETJ** [comment]
@jbrooksuk I think the wrong code is more important than the issue itself. If you look at `forAttachedResource`'s implementation in the `ActionEvent` model, you'll notice that both `actionable_id` and `target_id` is being got from `$parent` object while their types are being got from 2 different objects.

**Comment by demency** [comment]
@yaim Just for ask... Is Key a UUID?

**Comment by chaseconey** [comment]
I am experiencing this same issue is seems on latest version (`2.8.0`).

**Comment by AlbinoDrought** [comment]
I experienced https://github.com/laravel/nova-issues/issues/2106 as well. Here is my attempt at a repro, code + steps + pictures:

https://github.com/AlbinoDrought/repro-nova-1959

**Comment by jeffreydevreede** [comment]
I am experiencing exactly the same on Nova 3.5.0.

**Comment by pa-bouly** [comment]
Same issue on Nova 3.6.0

**Comment by alex-osborn** [comment]
Running into a similar issue, Nova 3.5.0.

<img width="1076" alt="Screen Shot 2020-06-09 at 4 46 02 PM" src="https://user-images.githubusercontent.com/880420/84107042-d97b0a80-aa70-11ea-9a20-338cc261c5f8.png">

Screenshot example of this in the wild.

- I attached two resources, IDs 43 & 45.
- The action log is incorrect and references resource ID 48 for both rows.

The ID of the resource I am working with is 48 (User model).

**Comment by AlbinoDrought** [comment]
Still occurs in the latest `laravel/nova:3.7.0`. I have added a reproducing feature test at https://github.com/AlbinoDrought/repro-nova-1959/blob/master/tests/Feature/ReproduceNova1959Test.php

**Comment by jeffreydevreede** [comment]
Im still having this issue in Nova 3.8.4.

**Comment by AlbinoDrought** [comment]
Still occurs in the latest `laravel/nova:3.8.4`, updated repro: https://github.com/AlbinoDrought/repro-nova-1959

**Comment by crynobone** [comment]
Submitted a PR to Nova 2.x, should be applicable to 3.x once merged.

**Comment by crynobone** [comment]
Fixed in `v3.12.0` via laravel/nova#991
