### ISSUE TITLE
Select Down Arrow Missing in Firefox

### ISSUE THREAD

**Issue by loren138** [laravel/nova-issues#196]
The down arrow for select boxes is missing in Firefox. (I can see it in Chrome.)

I'm running the latest Firefox (v61.0.2).

![screen shot 2018-08-25 at 2 33 15 pm](https://user-images.githubusercontent.com/1224505/44621402-d864f300-a873-11e8-936d-1ca6a7e3825f.png)

**Comment by zeroseed** [comment]
+1 Just realized it missing 😅

**Comment by webhealer** [comment]
+1  ( Firefox version 62.0 (64-bit) for Ubuntu) , arrow is missing.

**Comment by dillingham** [comment]
Related: https://github.com/laravel/nova-issues/issues/86 https://github.com/laravel/nova-issues/issues/170 https://github.com/laravel/nova-issues/issues/533

**Comment by dillingham** [comment]
Related: https://github.com/laravel/nova-issues/issues/86 https://github.com/laravel/nova-issues/issues/170 https://github.com/laravel/nova-issues/issues/533 https://github.com/laravel/nova-issues/issues/196 https://github.com/laravel/nova-issues/issues/952

**Comment by davidhemphill** [comment]
This has been fixed and will be included in an upcoming release.
