### ISSUE TITLE
Detailed help messages

### ISSUE THREAD

**Issue by VTumanov** [laravel/nova-issues#1960]
Hi! We have on the resource page a lot of fields for data entry, and for each of them you need to display a description of the rules of filling. Some of these rules can reach 3-5 lines, and in general they do not need to constantly show disclosed.

My suggestion is to add to the help method, the second argument to which a detailed message is passed, and use show/hide link for display text.

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
