### ISSUE TITLE
Return message along with redirect from action

### ISSUE THREAD

**Issue by dgoldstein89** [laravel/nova-issues#1961]
I'd like to redirect the user with a message when they run an action. From the documentation it seems that it can be either, but not both. Did I miss something or is this not possible?

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by dgoldstein89** [comment]
Thanks
