### ISSUE TITLE
Action Log Authorization

### ISSUE THREAD

**Issue by dgoldstein89** [laravel/nova-issues#1963]
Nova version: 2.0.9

Is there a way to hide the action events log from some users?
I can create an ActionEventPolicy, but then if viewAny() returns false the user is redirected to a 403 page.

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by kidereo** [comment]
+1. Yes, please, this would be very useful!

**Comment by dgoldstein89** [comment]
I guess I didn't look hard enough before creating the issue. See #1413

**Comment by oheck** [comment]
Adding another Policy and registering it in AuthServiceProvider for ActionEvent::class works for me.

**Comment by issour** [comment]
Hi @oheck can you please provide an example many thx !!!

**Comment by oheck** [comment]
@issour https://github.com/oheck/example-action-log-authorization

- admin can view ActionEvents
- user cannot view ActionEvents

**Comment by issour** [comment]
@oheck 
fabulous ! Big big thank you !!! 💯

**Comment by dblumenau** [comment]
> @issour https://github.com/oheck/example-action-log-authorization
> 
> * admin can view ActionEvents
> * user cannot view ActionEvents

Huge thank you for this. You saved me hours of googling. I used it to set up a preference based on each user if they want to see the action log as it was confusing some users.

**Comment by stonkeep** [comment]
> @issour https://github.com/oheck/example-action-log-authorization
> 
> * admin can view ActionEvents
> * user cannot view ActionEvents

Saved my life
