### ISSUE TITLE
Pagination Next/Previous buttons on Lenses not clickable after first page

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [laravel/nova-issues#1966]
- Laravel Version: 5.8.35
- Nova Version: 2.0-dev (not sure how to check, just looked in my composer.lock)
- PHP Version: 7.3.6
- Database Driver and Version: Mysql 5.7
- Operating System and Version: MacOS 10.14.3
- Browser type and version: Chrome 77.0

### Description

When using a Lens, Im finding that after clicking the Next button the first time, to show the 2nd page of results, the Next/Previous buttons are in `disabled` mode and I can no longer click them to go to page 3. However if I manually enter 3 into the pagination query string, it loads the 3rd 
page fine.

It appears that even though page 2 loads in successfully, the `disabled` prop of the component is not removed?

**Comment by davidhemphill** [comment]
There was an issue similar to this fixed in 2.0.4. I'm almost certain it's that. Try upgrading to that version, republish Nova's assets, and post a new issue if the issue persists.
