### ISSUE TITLE
Metric formatting fails / does nothing

### ISSUE THREAD

**Issue by ksorbo** [laravel/nova-issues#1967]
### Description

I am not able to get any format of metric values to work. I have tried several
`        return $this->sum($request, StripeTransaction::class,'amount')->dollars();`
or 
`         return $this->sum($request, StripeTransaction::class,'amount')->format('$0,0.00');`

This is the same as 
https://github.com/laravel/nova-issues/issues/1579
Issue is closed with no resolution.

- Laravel Version: 5.8.29
- Nova Version: 2.0.9
- PHP Version: 7.3.6
Using homestead latest
- Browser type and version: Chome & Firefox
- Reproduction Repository: https://github.com/###/###

### Steps To Reproduce
Create value metric with the above code in the calculate method.
Add to dashboard
Value displays but as a whole number (integer)

![image](https://user-images.githubusercontent.com/1436884/65601287-6889d600-df67-11e9-8289-faf5f09614b5.png)

### Update
I did a php artisan nova:publish and cleared the cache. Fixes the problem for ->dollar()
However, whether I use ->dollar() or ->format('0,0.00'), the amount gets rounded and does not show the cents. 

Investigating the aggregate function in Value.php, it appears as if the Nova system always forces a round to 0 places when using the sum method. **WHY??**

**Comment by jbrooksuk** [comment]
You're using an outdated version of Nova. I've confirmed that the `dollars` method does work:

![image](https://user-images.githubusercontent.com/246103/65606039-10bc9080-dfa2-11e9-9e8c-7f118514df61.png)

v2.3.1 is the [latest version](http://nova.laravel.com/releases).
