### ISSUE TITLE
404 error on show/edit when ID is too big

### ISSUE THREAD

**Issue by JacobDelcroix** [laravel/nova-issues#1968]
- Laravel Version: 5.8.35
- Nova Version: 2.2.0
- PHP Version: 7.2
- Database Driver and Version: PostgreSQL (10.6)
- Operating System and Version: All
- Browser type and version: All

### Description

When ID is too big (here is one exemple from my DB 20190928153012113) edit/show and delete route are not working properly. (404 error)
ID field is an integer.

### Steps To Reproduce

Just insert a big integer as a primary key for a record.

**Comment by jbrooksuk** [comment]
Confirmed.

**Comment by jbrooksuk** [comment]
Can you please try casting your `id` to a `string` within your model?

**Comment by JacobDelcroix** [comment]
@jbrooksuk Yes it works. But of course I don't want to do that in my application.

**Comment by jbrooksuk** [comment]
Of course, I’m just checking something so we can implement a fix.

**Comment by dkulyk** [comment]
20190928153012113 looks like ISO 8601 without non digit chars. This cannot to be int.
