### ISSUE TITLE
Documentation for tools, missing `php`

### ISSUE THREAD

**Issue by itainathaniel** [laravel/nova-issues#197]
On the **Defining Tools** [documentation section](https://nova.laravel.com/docs/1.0/customization/tools.html#defining-tools), the .sh code example is
`artisan nova:tool acme/price-tracker` when is should be `php artisan nova:tool acme/price-tracker`

**Comment by Andy-Baker** [comment]
I think it's because Homestead has an alias for it, but you're right.

**Comment by GuidoHendriks** [comment]
I think this is the wrong place for documentation issues. Docs are over at https://github.com/laravel/nova-docs.

**Comment by itainathaniel** [comment]
Fixed on https://github.com/laravel/nova-docs/commit/b23a29ac4997b63aa55f1c986449960419b641e3
