### ISSUE TITLE
Using an apostrophe in Nova site name gives blank screen

### ISSUE THREAD

**Issue by king724** [laravel/nova-issues#1970]
- Laravel Version: 5.8.35
- Nova Version: 2.3.1
- PHP Version: 7.3.9
- Database Driver and Version: MySQL 5.7
- Operating System and Version: Ubuntu 18.04
- Browser type and version: Chrome 77

### Description

Updating the `'name'` field in `config/nova.php` to include an apostrophe causes a blank screen on all Nova pages.

### Steps To Reproduce
In `config/nova.php`, put either of the following

```
'name' => 'O\'Rielly Auto Parts',

// or

'name' => "O'Rielly Auto Parts",
```

**Comment by dkulyk** [comment]
https://github.com/laravel/nova/blob/68e6b60afe6cf4ec29f635e3184daf7094c91258/resources/views/layout.blade.php#L48 @jbrooksuk i think need to use @json instead '{{...}}'

**Comment by dkulyk** [comment]
Confirmed. 
@jbrooksuk Issue in [layout.blade.php:48](https://github.com/laravel/nova/blob/2.0/resources/views/layout.blade.php#L48)
