### ISSUE TITLE
MorphTo field unwanted "shouldSelectInitialResource"

### ISSUE THREAD

**Issue by janverhulst** [laravel/nova-issues#1971]
- Nova version: v2.3.1
- Laravel version: v5.8

I have a MorphTo field defined for my Page resource. It's meant to add a relatable item, which could be something like a Product or Article resource.

This is the MorphTo field definition:
```
MorphTo::make('Related item', 'relateable')
                ->types([
                    Text::class,
                    Contest::class,
                    Course::class,
                    Activity::class,
                    Product::class,
                ])
                ->nullable()
                ->hideFromIndex(),
```

This Page can also be a subpage of another Page (through a parent_page_id, another relationship). This is where things go wrong. I create a subpage from the detailpage of another Page, which triggers the viaRelationship, which triggers the MorphTo field to be prefilled with the viaRelationship (see vue code below). This is not helpful in this case, since Page cannot even be selected as a type for the relateable morphTo relationship. This causes the form validation to fail without it being clear what's going wrong, since the user didn't select anything for the relationship.

```
if (this.creatingViaRelatedResource) {
            this.initializingWithExistingResource = true
            this.resourceType = this.viaResource
            this.selectedResourceId = this.viaResourceId
        }

        if (this.shouldSelectInitialResource && !this.isSearchable) {
            this.getAvailableResources().then(() => this.selectInitialResource())
        } else if (this.shouldSelectInitialResource && this.isSearchable) {
            this.getAvailableResources().then(() => this.selectInitialResource())
        }
```

So, the prefilling of the MorphTo field should be configurable.

Hope this is clear. If you need any more input, do ask!

**Comment by KevinKodamera** [comment]
I'm having the same issue. 
The viaResource, viaRelationship, viaResourceId are actually used by another field (belongsTo), but the morphTo field is picking them up as well.

Both the model related via belongsTo and the models related via morphTo use the same name for their relationship (which I'm guessing is the source of the problem).

Perhaps a viaField would be necessary?

**Comment by Pamposgsk** [comment]
The above error is very important!I cannot go live with my project if this bug not fixed.Do we have any update on this?Maybe if you give some instructions to solve the problems manually?
If not possible can I send payment to fix the issue and how much will cost!

**Comment by crynobone** [comment]
Hello @janverhulst

I'm having a hard time reproducing the code exactly as you described. Would appreciated if you can share the full reproducing code (especially the relation) to build the issue from `Page` with morphs to `Related`.
