### ISSUE TITLE
Boolean field does not post explicitly set true/false values

### ISSUE THREAD

**Issue by gavinhewitt** [laravel/nova-issues#1972]
- Laravel Version: 5.8.*
- Nova Version: 2.3.1

### Description
The values set are not being posted. I'm expecting to get either 'i_am_true' or 'i_am_false', but whatever I do it's 0 or 1.

```php
Boolean::make('Something')
    ->trueValue('i_am_true')
    ->falseValue('i_am_false')
```

**Comment by jbrooksuk** [comment]
Hey, I've tried to replicate this, but was unable to do so.

Sorry, but we are unable to debug your issue without a reproducible code example. Once you provide that we can open this up again.
