### ISSUE TITLE
Change the label on the Lens filter button

### ISSUE THREAD

**Issue by vayurobins** [laravel/nova-issues#1975]
Nova version: 2.3.0 | Laravel version: 5.8.35

Is it possible to change the label on the Lens filter button and maybe also translate it?
![Screenshot 2019-09-26 at 21 05 31](https://user-images.githubusercontent.com/1386354/65717358-6b88e180-e0a1-11e9-8f82-7aa428862cf8.png)

**Comment by jbrooksuk** [comment]
What’s the purpose here? Are you looking to replace all Lens text with something else or on a per-resource basis?

**Comment by vayurobins** [comment]
Good question. Actually I am looking for at per-resource basis solution. :-)

**Comment by jbrooksuk** [comment]
Out of interest, for what reason would this be? _I'm closing this due to how this repo works, but please continue the discussion._

In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by vayurobins** [comment]
In my opinion, is the word "Lens" not so "userfriendly" and might not be obvious for some users. "Filter" might be better? But it would be nice if it was possible to modify it on a resource basis and also be able to translate it. :-)

**Comment by jbrooksuk** [comment]
To clarify, why would you want to change this per-resource?

**Comment by vayurobins** [comment]
Sure, I'm just thinking that maybe it would be nice to have a label that reads "Archive" on a certain resource type, and then a different label named "Filter" on another and maybe "User Roles" on a third resource. To me, it would make sense to be able to set the button label when building the resource. That's is what I did before posting here. ;-)

**Comment by noahlocke** [comment]
@jbrooksuk @vayurobins I totally agree here. `Lens` makes sense to me, but not to my client. In my use case, I uses `Lenses` to return resources grouped by week/month/day, etc. So I'd rather call it `View` or `Group`. To answer your question @jbrooksuk, each `Lens` is really specific to the resource, so having the ability to give it a label would be nice.

**Comment by keironwaites** [comment]
I would like to change Lens to something else as well, although I am not concerned with it being per-resource.

**Comment by alexagui** [comment]
I'm not sure where supposed to open feature requests for Nova. But attached is an example of how I'd like to change the default lens label to something that'd makes more sense for a client.  

In the screenshot, the lenses we've setup are "quick reports" to see which records still missing data for specific sections.

![Image 2021-05-12 at 8 40 43 AM](https://user-images.githubusercontent.com/685/118057974-10316300-b35b-11eb-8d28-e5b557887313.png)

**Comment by bitclaw** [comment]
To change it globally, you can change it in the translation file. See resources/lang/vendor/nova/en.json.
