### ISSUE TITLE
Chunk disable in actions

### ISSUE THREAD

**Issue by approached** [laravel/nova-issues#1976]
Hi @ all

It would be nice if i can disable chunk size in actions. Currently there are one parameter in Action.php to control. But it isn't possible to disable.

```php
    /**
     * The number of models that should be included in each chunk.
     *
     * @var int
     */
    public static $chunkCount = 200;
```

**Comment by jbrooksuk** [comment]
Why would you disable chunking?

**Comment by jbrooksuk** [comment]
Also, if you wanted to disable chunking, you could just set a large `chunkCount`.

**Comment by approached** [comment]
> Why would you disable chunking?
I created a excel export in a action. For the export i'm managing chunking self.

> Also, if you wanted to disable chunking, you could just set a large `chunkCount`.

I know but this is a shitty way. I'm afraid how nova issues are handled here.

**Comment by davidhemphill** [comment]
Nothing to be afraid of. Setting a high chunk count is perfectly acceptable here. Feel free to PR a change of it really bothers you.
