### ISSUE TITLE
Place field merge method documentation

### ISSUE THREAD

**Issue by haidarzhy** [laravel/nova-issues#1977]
There is merge method in https://nova.laravel.com/docs/2.0/resources/fields.html#place-field which is not documented.

Some docs would be helpful

**Comment by jbrooksuk** [comment]
Are you referring to the `merge` method used within `addressFields`?

**Comment by jbrooksuk** [comment]
This method is from the `ConditionallyLoadsAttributes` trait from the Laravel Illuminate framework, see https://laravel.com/api/5.8/Illuminate/Http/Resources/ConditionallyLoadsAttributes.html#method_merge
