### ISSUE TITLE
Field Stacking Not Working On Detail Page

### ISSUE THREAD

**Issue by ifaniqbal** [laravel/nova-issues#1978]
- Laravel Version: 6.0.4
- Nova Version: 2.3.1
- PHP Version: 7.2.14
- Database Driver and Version: sqlsrv
- Operating System and Version: Windows 10
- Browser type and version: Chrome 77

### Description

Tried `Trix::make('Content')->stacked()` but got no stack.

**Comment by jbrooksuk** [comment]
I can confirm that field stacking does work in v2.3.1:

![image](https://user-images.githubusercontent.com/246103/65814393-00422b00-e1d9-11e9-8536-99c318dafe5f.png)

Have you re-published assets? `php artisan nova:publish --force`.

**Comment by ifaniqbal** [comment]
So, it does work on create/edit page only. Got it.

**Comment by 0x15f** [comment]
@jbrooksuk Can you re-open this. I can confirm it doesn't work on detail pages inside of a Panel.

**Comment by jbrooksuk** [comment]
> @jbrooksuk Can you re-open this. I can confirm it doesn't work on detail pages inside of a Panel.

Can you please open this as a new issue.
