### ISSUE TITLE
Typo in the Theme documentation

### ISSUE THREAD

**Issue by markbiek** [laravel/nova-issues#1979]
- Laravel Version: 6.x
- Nova Version: 2.3.1
- PHP Version: 7.3

<img width="217" alt="image" src="https://user-images.githubusercontent.com/917632/65818494-d5a7a080-e1df-11e9-97a2-937d6cf59ebd.png">

<img width="385" alt="image" src="https://user-images.githubusercontent.com/917632/65818496-dc361800-e1df-11e9-82d4-95baac085947.png">

It should be **Themes** and not **Theme's**

**Comment by jbrooksuk** [comment]
https://nova.laravel.com/docs/2.0/customization/themes.html#publishing-your-themes
