### ISSUE TITLE
MarkDown and WYSIWYG Rendering HTML on Index or (Show Content)

### ISSUE THREAD

**Issue by khalil-htme** [laravel/nova-issues#1981]
Hello, I am trying to display the MarkDown field as "show content" or full-html viewable on index.

currently it will just show raw data like:
`**asasasasa** *asasasa*`

or in other alternatives to MarkDown editor like:
`<p><strong>Testing instructions:</strong></p><p><ul><li>Part A</li><li>Part B</li><li>Part c</li></ul></p>`

Link to image showing the issue: [https://imgur.com/rKVJiS0](https://imgur.com/rKVJiS0)

What I'm searching for is how can I display "(Show Content)" with rendering like what is happening once you go in the details section!

**Comment by davidhemphill** [comment]
Textarea type fields are not designed to be shown on the index as it's impractical to have them there. And even if you use `showOnIndex` and they were to show their HTML content, it wouldn't have the excerpt functionality either. Your best bet is to create a custom field that does exactly what you want for this use-case.
