### ISSUE TITLE
[Feature Request] Make action more visible

### ISSUE THREAD

**Issue by duderion** [laravel/nova-issues#1983]
Hi @all,

First of all, Nova is a cool project. But some things make it a little hard to handle for the (backend) user:

One thing is, that the Nova Actions are always "hidden" in the dropdown, top right, even if there is one single action, the user doesn't see it without clicking it.

It would be nicer if the actions could be optionally displayed as buttons (e.g. on top)

or at least

if there is only one action, show it as default. Or let the developer chose, which option should be shown by default.

Greets,
Adrian

**Comment by jbrooksuk** [comment]
@davidhemphill has been working on this https://github.com/laravel/nova/pull/612
