### ISSUE TITLE
Extra details for errors

### ISSUE THREAD

**Issue by j-shelfwood** [laravel/nova-issues#1984]
Hi Nova maintainers!

First of all, loving the product! We've been using it at our company and it's made development for CRUD oriented UI's so much more fun and integrated with Laravel!

One of the things I'd love to see added is the ability to see an error page for errors that come through whenever one pops up in Nova. Right now it shows the basic error message in a modal but without any extra details.

You can view more details by opening the network tab and triggering the error again. However I'd love to see something like a 'View error page' button in the modal. This could for example open an ignition error page in a new tab allowing easy access to the stack trace.

Let me know if you guys would love to see this or if I'm missing some kind of handy trick ^^

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
