### ISSUE TITLE
Tool-Tips for Metrics

### ISSUE THREAD

**Issue by tylernathanreed** [laravel/nova-issues#1986]
Often my metrics seem fairly straight forwards, but there's a small audience that requests additional explanation, or the title is considered ambiguous to them.

I think that I great way to clarify this information would be to add tool-tips to the metrics. These could appear to the right of the title (logistically next to, not floating in the top right, as that would compete with ranges) as an "(i)" icon, where hovering over it could provide more explanation.

We already have the "`->help(...)`" method for fields, so I don't think it's that much of a stretch to offer the same method for metrics.

**Comment by FaridAghili** [comment]
Makes sense to me, looking forward to it.

**Comment by davidhemphill** [comment]
Closed by laravel/nova#667
