### ISSUE TITLE
Cancel button on detail view page

### ISSUE THREAD

**Issue by ratno** [laravel/nova-issues#1987]
Cancel button is already available for create and update, i would love to have it on view detail too, and also the detail view page url should incorporate viaResource/viaResourceId/viaRelationship and need new method maybe 'redirectAfterDetailView' just like redirectAfterUpdate or redirectAfterCreate so that we can customize redirecting.

thanks very much,,

**Comment by FaridAghili** [comment]
It can be "Back", instead of "Cancel"

**Comment by ratno** [comment]
it is the same argumentation why cancel was there in create or edit form, you guys said it can be 'back' but apparently the cancel button is there, because there is use case for that,, please add cancel in the view also.
thanks,,

**Comment by ratno** [comment]
@jbrooksuk is this simple feature implemented?
i have case like this:
- view detail on roles, then attach ability to it, then save, back to detail view page, if i hit back button on browser it would not go to roles/index but it will go to attach ability form
- view detail on roles, then edit roles, save it, back to detail page, if i hit back button on browser it would not go to roles index page, but it will go to edit roles form

thanks

![need_cancel_button_in_view](https://user-images.githubusercontent.com/570893/68829393-514fa500-06db-11ea-9858-eea19d61c172.gif)
