### ISSUE TITLE
Changing Nova Guard Doesn't Affect Password Reset Functionality

### ISSUE THREAD

**Issue by mdavis1982** [laravel/nova-issues#1989]
- Laravel Version: 6.0.4
- Nova Version: 2.3.1
- PHP Version: 7.3.8
- Database Driver and Version: N/A
- Operating System and Version: macOS 10.14.6
- Browser type and version: Safari 12.1.2 & Chrome 77.0.3865.90
- Reproduction Repository: N/A

### Description
When changing the default Nova guard, the password reset functionality still uses the Laravel default guard.

### Steps To Reproduce
Add a new guard to `config/auth.php`:

```php
'guards' => [
    'web' => [
        'driver' => 'session',
        'provider' => 'users',
    ],

    'nova' => [
        'driver' => 'session',
        'provider' => 'admins',
    ],

    'api' => [
        'driver' => 'token',
        'provider' => 'users',
        'hash' => false,
    ],
],
```

Add a new provider to `config/auth.php`:

```php
'providers' => [
    'users' => [
        'driver' => 'eloquent',
        'model' => App\Models\User::class,
    ],

    'admins' => [
        'driver' => 'eloquent',
        'model' => App\Models\Admin::class,
    ],

    // 'users' => [
    //     'driver' => 'database',
    //     'table' => 'users',
    // ],
],
```

Add a new password reset configuration to `config/auth.php`:

```php
'passwords' => [
    'users' => [
        'provider' => 'users',
        'table' => 'password_resets',
        'expire' => 60,
    ],

    'admins' => [
        'provider' => 'admins',
        'table' => 'password_resets',
        'expire' => 60,
    ],
],
```

Add a new `Admin` model in `app/Models/Admin.php`:

```php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Admin extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}
```

Add a new migration for the `admins` table:

```php
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateAdminsTable extends Migration
{
    /**
     * Run the migrations.
     */
    public function up()
    {
        Schema::create('admins', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('name');
            $table->string('email')->unique();
            $table->timestamp('email_verified_at')->nullable();
            $table->string('password');
            $table->rememberToken();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down()
    {
        Schema::dropIfExists('admins');
    }
}
```

Add a new factory for the `Admin` class:

```php
<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */
use App\Models\Admin;
use Illuminate\Support\Str;
use Faker\Generator as Faker;

/*
|--------------------------------------------------------------------------
| Model Factories
|--------------------------------------------------------------------------
|
| This directory should contain each of the model factory definitions for
| your application. Factories provide a convenient way to generate new
| model instances for testing / seeding your application's database.
|
*/

$factory->define(Admin::class, function (Faker $faker) {
    return [
        'name' => $faker->name,
        'email' => $faker->unique()->safeEmail,
        'email_verified_at' => now(),
        'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', // password
        'remember_token' => Str::random(10),
    ];
});
```

Migrate the database, and add a new `Admin` to the database:

```bash
$ php artisan tinker

>>> factory(App\Models\Admin::class)->create(['name' => 'Demo Admin', 'email' => 'admin@example.com']);
```

Customise the guard used by Nova in `.env`:

```env
# Nova
NOVA_GUARD=nova
```

When you now try to reset your password from the reset password screen provided by Nova, when filling out the email address as `admin@example.com` there is an error:

```
We can't find a user with that e-mail address.
```

If I have a user in my `users` table, and use that email address, it works. It seems as though Nova is using the default Laravel password broker and guard.

**Comment by jbrooksuk** [comment]
I've not properly looked into this yet, so bear with me @mdavis1982 (👋 hi btw!) but the `ResetPasswordController` is using the `ResetsPasswords` trait and does not override the `guard` method anywhere, so it may be that we need to return the `NOVA_GUARD` instead here.

**Comment by jbrooksuk** [comment]
@mdavis1982 if you can update `ResetPasswordController to add this to the end:

```php
protected function guard()
{
    return Auth::guard(config('nova.guard'));
}
```

Does this fix your problem?

**Comment by mdavis1982** [comment]
@jbrooksuk Thanks for looking into this so quickly.

It doesn't appear to fix my issue. I also tried overriding the `broker()` method:

```php
protected function guard()
{
    return Auth::guard(config('nova.guard'));
}

public function broker()
{
    return Password::broker('admins');
}
```

But I'm still getting the "We can't find a user with this email address" error.

**Comment by mdavis1982** [comment]
@jbrooksuk Okay... I think I've worked out why that doesn't work! 😄 It also seems like the `SendsPasswordResetEmails` trait needs its `broker()` method to be overridden.

So the Nova `ForgotPasswordController` also needs the above broker method adding.

I think, we should add a new Nova config option for the broker to use. Maybe something like the following in `config/nova.php`:

```php
'auth' => [
    'guard' => env('NOVA_GUARD', null),
    'passwords' => env('NOVA_PASSWORDS', null),
],
```

Then, in the `ResetPasswordController` and the `ForgotPasswordController`, we need to override the `guard()` and `broker()` methods. This should fix the issue 😄 

Also, Hi! 👋

**Comment by jbrooksuk** [comment]
Yep, that makes sense to me. Are you able to make a PR with this?

**Comment by mdavis1982** [comment]
@jbrooksuk I could definitely do that! Is there a nova repository for me to make a PR to?

**Comment by jbrooksuk** [comment]
There is, but you'll need to link Nova to your GitHub account (you can do that from https://nova.laravel.com)

**Comment by mdavis1982** [comment]
@jbrooksuk Ah I see... My Nova license is a work one. I'll buy myself another one and then PR it 😄

**Comment by mdavis1982** [comment]
@jbrooksuk Even better! I'll do that now then! 😄

**Comment by mdavis1982** [comment]
@jbrooksuk I've added a PR to the nova repository which fixes this issue 😄

**Comment by jbrooksuk** [comment]
Thanks!

_Give us a follow on Twitter and I'll send you a message!_

**Comment by mdavis1982** [comment]
@jbrooksuk Done! 😄
