### ISSUE TITLE
HttpException Error on Initial Login

### ISSUE THREAD

**Issue by Sovjetskii** [laravel/nova-issues#199]
Clean install of Laravel 5.6.34 on local (Homestead).

Followed installation instructions on: https://nova.laravel.com/docs/1.0/installation.html

Created a new user and successfully logged in at http://{localhost}/nova/login. On login, redirected to /nova/ and presented with the following error:

> Symfony \ Component \ HttpKernel \ Exception \ HttpException
No message

```
<?php
 
namespace Laravel\Nova\Http\Middleware;
 
use Laravel\Nova\Nova;
 
class Authorize
{
    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return \Illuminate\Http\Response
     */
    public function handle($request, $next)
    {
        return Nova::check($request) ? $next($request) : abort(403);
    }
}
```

> Arguments: 403

![temp](https://user-images.githubusercontent.com/12053407/44621878-3990c480-a87c-11e8-8055-3d45f1a920b8.PNG)

**Comment by GuidoHendriks** [comment]
I’d say that this part of the docs might help:

https://nova.laravel.com/docs/1.0/installation.html#authorizing-nova

**Comment by Sovjetskii** [comment]
Yes, despite having my environment variables set as APP_ENV=local, Nova for some reason implemented the gate.

Fixed by including an authorized permission into the NovaServiceProvider.php's Gate call.
