### ISSUE TITLE
Trend metrics UI style bug after upgarde to v2.4.0

### ISSUE THREAD

**Issue by turzaizsolt** [laravel/nova-issues#1990]
Hi,
After I upgraded the nova version to v2.4.0 the trend metrics UI is showing as in the image below:
<img width="740" alt="Screenshot 2019-10-01 21 46 28" src="https://user-images.githubusercontent.com/196773/65991112-7d99c400-e495-11e9-9b68-2b35d82b8d2b.png">

I did run the `php artisan nova:publish` command after upgrading.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
