### ISSUE TITLE
Many Packages make many Database Queries before loading the dashboard

### ISSUE THREAD

**Issue by encomienda** [laravel/nova-issues#1992]
- Laravel Version: 6.1.0
- Nova Version: 2.3.0
- PHP Version: 7.2.19

### Description

In our app, we have nova and has more than 5 packages installed and when loading the dashboard I've log the database queries happened it is more than 500 queries before loading the dashboard. I found the issue and that is because the styles/scripts of the packages are doing the authorization queries. So everytime i add new package it will be added in authorization (another query if authenticated).

### Steps To Reproduce

Install Packages and see the database queries.

I'm using this in boot method in AppServiceProvider

`
        \Illuminate\Support\Facades\DB::listen(function ($query) {
            logger($query->sql);
        });
`

**Comment by davidhemphill** [comment]
A package usually has 2 assets...a CSS file, and a JavaScript file...which would normally be 1 DB authentication query each. Without more concrete details, I'm not able to see how this would result in 500 queries for 5 packages. There seems to be something else going on. 

Also, if 3rd party packages do not require style/script authorization, they don't have to use it. If not, they should be modified to publish their assets like a normal Laravel package and provide instructions on installing it within Nova. I think we could probably make that a bit nicer (something similar to the newly-released theme updates), but there's nothing in place at this time.

**Comment by encomienda** [comment]
is there way to cache the nova styles/scripts?
