### ISSUE TITLE
showOnTableRow not working with Action has Fields.

### ISSUE THREAD

**Issue by bsormagec** [laravel/nova-issues#1993]
- Laravel Version: 5.8
- Nova Version: 2.4.0
- PHP Version: 7.3
- Database Driver and Version: Mysql 5.7
- Operating System and Version: OSX
- Browser type and version: Chrome

### Description

When i use showOnTableRow with Action has fields, its not loading fields on run only asking for confirmation.

### Steps To Reproduce

Must move method from detail to index view to run same view and actions.

**Comment by davidhemphill** [comment]
I'm not able to replicate your issue. I can use fields on inline actions and they work correctly: 

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/58970/66060310-0bf85f00-e503-11e9-8116-59e6a2001ace.png">

If you find a way to reproduce your issue in a fresh install of Nova, please post a new issue so we can take another look.
