### ISSUE TITLE
Duplicating POST in any form view when saving

### ISSUE THREAD

**Issue by gaabora** [laravel/nova-issues#1994]
https://github.com/laravel/nova/pull/641

**Comment by bakerkretzmar** [comment]
Same here.

From what I can see, two identical POST requests fired at the same time, the first one succeeds and the second returns a 409, so every update I get a green success toast and a red 'another user has updated...' toast at the same time.

**Comment by wildwestriverrider** [comment]
Also seeing this issue.

**Comment by davidhemphill** [comment]
I'm not able to replicate this behavior on the update view as the PR suggests, using either button: 

![image](https://user-images.githubusercontent.com/58970/66083011-09acf980-e531-11e9-967c-1b89604b47ab.png)

Are you certain you've updated Nova's assets according to the upgrade guide? https://nova.laravel.com/docs/2.0/installation.html#updating-nova-s-assets

If after updating this behavior is still happening, please post a new issue, making sure to fill out all of the issue template details so we can best diagnose the issue.

**Comment by gaabora** [comment]
![image](https://user-images.githubusercontent.com/10756170/66090418-fda25580-e58b-11e9-93c4-411868884ed3.png)
firefox with vanila 2.4 @davidhemphill

**Comment by zippoxer** [comment]
I get the same issue with the latest firefox and Nova v2.4.0 as well. Even after `php artisan nova:publish --force`.

**Comment by jbrooksuk** [comment]
The fix is not out yet, we should have a release tomorrow.
