### ISSUE TITLE
Inline Action not shown for pivot actions

### ISSUE THREAD

**Issue by timwachsener** [laravel/nova-issues#1995]
- Laravel Version: 6.1.0
- Nova Version: 2.4.0
- PHP Version: 7.3
- Database Driver and Version: MySQL 8.0
- Operating System and Version: macOS 10.13.6
- Browser type and version: Chrome 77.0.3865.90

### Description

When adding `showOnTableRow()` to actions on a pivot action the "Actions" button won't display.

### Steps To Reproduce

```
BelongsToMany::make('Products')->actions([
    (new TestAction)->showOnTableRow(),
]),
```

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by timwachsener** [comment]
This looks clearly like a bug to me: the inline actions feature doesn't work on many to many relations.

**Comment by davidhemphill** [comment]
Not a bug, just haven’t implemented this aspect yet.
