### ISSUE TITLE
Wider "global" search input

### ISSUE THREAD

**Issue by epalmans** [laravel/nova-issues#1996]
the dropdown shown after a global search seems a bit narrow to accomodate slightly longer resource titles.
Suggesting to change the max-w-xs class on the parent container to (at least) max-w-sm

Alternatively add unique classnames to components (such as this search), so anyone could easily override css with their own specific theme styling

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
