### ISSUE TITLE
Inline Actions not showing up on table row

### ISSUE THREAD

**Issue by dtannen** [laravel/nova-issues#1997]
(new Action)->onlyOnTableRow()

I added onlyOnTableRow() to an action for a resource.  I expected a dropdown with the action to be available on each resource row.  However, the dropdown doesn't show up although the action is removed from the action drop down.

Nova 2.4.0 
Laravel Framework 5.8.35

**Comment by davidhemphill** [comment]
Make sure you've updated to the latest Nova assets as outlined in the documentation: https://nova.laravel.com/docs/2.0/installation.html#updating-nova-s-assets

Feel free to post a new issue if you have a reproducible example of an action that doesn't show in a dropdown.

**Comment by dtannen** [comment]
@davidhemphill maybe it's not clear in the documentation?

I tried both: (new TestReport)->onlyOnTableRow() and (new TestReport)->showOnTableRow()

and neither are showing up as a row in the table.   I know that my Nova assets are updated because I'm getting the [ Load 25 More ] functionality and it's working properly.

Is there something else I need to do besides add either onlyOnTableRow() or showOnTableRow() when defining the action?

**Comment by AshutoshJha15** [comment]
i am facing the same issue

**Comment by dtannen** [comment]
@AshutoshJha15 how did you wind up getting the action dropdown to show up?

**Comment by chimit** [comment]
Probably, it's because the `replicate` permission was `false`. If it's not set specifically in falls back to `create` and `update`. When both are `true` the inline dropdown button appears.

https://nova.laravel.com/docs/resources/authorization.html#undefined-policy-methods
