### ISSUE TITLE
Catch 413 error on resource save and update

### ISSUE THREAD

**Issue by bgeree** [laravel/nova-issues#1998]
- Laravel Version: 5.8.35
- Nova Version: 2.4.0

### Description
If the request body is too large (eg. big file upload) the error remains completely invisible. This is especially problematic on "Update & Continue Editing".

**Comment by jbrooksuk** [comment]
If you use the `rules` method on your `Image` field, you can specify a [max file size](https://laravel.com/docs/5.8/validation#rule-size) which will throw an appropriate validation error.

![image](https://user-images.githubusercontent.com/246103/66113935-ae791680-e5c5-11e9-8efa-251f28a07381.png)

**Comment by bgeree** [comment]
That's not how it works...
The request gets rejected before it reaches the entry point of the application.

**Comment by bgeree** [comment]
@jbrooksuk
Any chance of fixing this?

**Comment by Jun-ocx** [comment]
Any update?

**Comment by riddla** [comment]
I agree, that this error should be catched.

Meanwhile we ended up increasing the upload limits of our web server. In our case Nginx' `client_max_body_size`, https://www.daveperrett.com/articles/2009/11/18/nginx-error-413-request-entity-too-large/.

**Comment by nathan-io** [comment]
Another vote to address this. In our case, image upload was failing without a specific error message, leaving the end users confused.

**Comment by riddla** [comment]
I had a look into the source code and it seems that currently only validation errors (error code 422) are catched:

```
// [...]
} catch (error) {
    this.submittedViaCreateAndAddAnother = false
    this.submittedViaCreateResource = true
    this.isWorking = false

    if (error.response.status == 422) {
        this.validationErrors = new Errors(error.response.data.errors)
        Nova.error(this.__('There was a problem submitting the form.'))
    }
}
```

I don't know the internals, but throwing a `Nova.error` in general for other errors in the catch block seems necessary.

@jbrooksuk, can you speak to this?

@nathan-io, I've got a working solution on my local machine and will work on a pull request, when @jbrooksuk is interested.

**Comment by riddla** [comment]
For a quick local fix you can try:

1. Copy `vendor/laravel/nova/webpack.mix.js.dist` to `vendor/laravel/nova/webpack.mix.js`
2. Alter `vendor/laravel/nova/resources/js/components/CreateForm.vue`:
```
// [...]
} catch (error) {
    this.submittedViaCreateAndAddAnother = false
    this.submittedViaCreateResource = true
    this.isWorking = false

    if (error.response.status == 422) {
        this.validationErrors = new Errors(error.response.data.errors)
        Nova.error(this.__('There was a problem submitting the form.'))
    }
    else {
        Nova.error(this.__('There was a problem submitting the form') + ': ' + error.response.statusText)
    }
}
```
3. Run `npm run prod` from the `vendor/laravel/nova/` directory.
4. Run `php artisan nova:publish` from your project root.

**Comment by riddla** [comment]
I made a pull request over at https://github.com/laravel/nova/pull/897.
