### ISSUE TITLE
Grouping resources

### ISSUE THREAD

**Issue by vyuldashev** [laravel/nova-issues#2]
Very desired feature is to group resources into categories. So we could achieve something like on the screenshot.

<img width="229" alt="screen shot 2018-08-23 at 17 15 12" src="https://user-images.githubusercontent.com/1809081/44530891-281eaf80-a6f8-11e8-9768-8fa9e31f4fc5.png">

**Comment by lucasromanojf** [comment]
I think this should be applied to Tools too.

**Comment by MattMangoni** [comment]
Definitely needed :)

**Comment by anderly** [comment]
Make categories collapsible/expandable, too. Needed to reduce the UI clutter with large apps with lots of resources.

**Comment by thatleeguy** [comment]
It would be great if we could define the name/title in the resource to override the automatic naming. 

$title = 'Library Items';

**Comment by MattMangoni** [comment]
@thatleeguy isn't that already possible? You can define a `label` property if I'm not mistaken :)

**Comment by thatleeguy** [comment]
@MattMangoni I might be doing something incorrectly then.
![screenshot 2018-08-25 14 05 42](https://user-images.githubusercontent.com/93346/44622137-1f50e980-a870-11e8-89d8-f8d4e3f05476.png)

**Comment by thatleeguy** [comment]
@MattMangoni Yeah, you are correct. I figured it out. 

`public static function label() {
    return 'Library Items';
}`

Thanks!

**Comment by vyuldashev** [comment]
@davidhemphill Any ETA on this?

**Comment by shirshak55** [comment]
installed 5-6 tools and created own tools now the sidebar looks so messy :( I hope this feature arrvies soon .

**Comment by davidhemphill** [comment]
Grouped resources landed in the release today.

**Comment by laraning** [comment]
Hi @davidhemphill , thanks for that ! Can you give us a gist / example how we can work with them?

Thanks.

**Comment by rocramer** [comment]
Is there an easy way to collapse these groups?

**Comment by 949mac** [comment]
> Is there an easy way to collapse these groups?

@rocramer, I haven't tried this, but checkout https://novapackages.com/packages/alexbowers/nova-categorise-resources

**Comment by ShinHyungJune** [comment]
I want it too.

**Comment by chescos** [comment]
Are there plans to make the groups collapsable? Right now it's a bad UX with 30+ resources since you need to scroll down too much, and then even manually scroll up again after selecting a resource from the bottom.

**Comment by fbingha** [comment]
(1) Allow us to create other menu items at the same level as Dashboard and Resources.
(2) Allow us to collapse these menu items.

**Comment by fiftysoft** [comment]
@taylorotwell any update on this?

**Comment by tpetry** [comment]
You can already group resources by setting the `public static $group` variable on a resource.

**Comment by tanmuhittin** [comment]
For collapsing groups you can use this simple package 👍 
https://github.com/tanmuhittin/nova-collapsible-groups

**Comment by dzymail** [comment]
if not override blade template, How to make custom resources menu not as 'Resources' submenu, but as a top level menu? maybe override  some variable to do it?

**Comment by vesper8** [comment]
Is there a way to add an icon to either resources or resource groups ? Can't find anything about this

**Comment by rmsj** [comment]
> Is there a way to add an icon to either resources or resource groups ? Can't find anything about this

Maybe this one: https://github.com/anaseqal/nova-sidebar-icons

**Comment by masweb** [comment]
https://novapackages.com/packages/alexbowers/nova-categorise-resources

**Comment by omajoor** [comment]
is there a way to use the `public static $group` on a custom tool as well?

**Comment by vesper8** [comment]
I've been using this package https://github.com/dcasia/collapsible-resource-manager

It gives you absolute control over the sidebar, you can add anything you want.. groups, resources, lens, tools, and arrange them exactly how you want
