### ISSUE TITLE
Inline Actions

### ISSUE THREAD

**Issue by AshutoshJha15** [laravel/nova-issues#2000]
How to use inline actions ?
![image](https://user-images.githubusercontent.com/50516423/66097109-dadb6580-e5ba-11e9-9649-44d1a4b30825.png)

**Comment by p4rz1val** [comment]
![Imgur](https://i.imgur.com/s2AH2oC.png)

```
class RefundClient extends Action
{
    use InteractsWithQueue, Queueable, SerializesModels;

    /**
     * Indicates if this action is available on the resource's table row.
     *
     * @var bool
     */
    public $showOnTableRow = true;
```

**Comment by AshutoshJha15** [comment]
![image](https://user-images.githubusercontent.com/50516423/66100029-ee8cc900-e5c6-11e9-8305-d48c398e9bbc.png)
 dropdown is not working

**Comment by AshutoshJha15** [comment]
`<?php

namespace App\Nova\Actions;

use App\Http\Resources\Room as RoomResource;
use App\Providers\AppServiceProvider;
use App\Repository\RoomRepository;
use App\Traits\AuthGuardHelpers;
use Illuminate\Bus\Queueable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Support\Collection;
use Laravel\Nova\Actions\Action;
use Laravel\Nova\Fields\ActionFields;


class CreateChatRoom extends Action
{
    use InteractsWithQueue, Queueable, AuthGuardHelpers;
    /** @var RoomRepository */
    private $repository;
    public $showOnTableRow = true;


    /**
     * @param RoomRepository $repository
     */
    public function __construct(RoomRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * Perform the action on the given models.
     *
     * @param  \Laravel\Nova\Fields\ActionFields $fields
     * @param  \Illuminate\Support\Collection $models
     *
     * @return mixed
     */
    public function handle(ActionFields $fields, Collection $models)
    {

        $user = auth()->user();
        if (self::isProvider($user)) {
            $user = $user->provider;
        }
        foreach ($models as $model) {
            $participants = [];
            array_push($participants, ['id' => $model->user_id, 'type' => 'user']);
            $participants = collect($participants)->add([
                'type' => array_search(get_class(
                    $user
                ), AppServiceProvider::getMorphMap()),
                'id' => $user->id,
            ]);
            $rooms = $this->repository->getRoomForParticipants($participants);
            if (count($rooms)) {
                return RoomResource::make($rooms->first());
            }
            $room = $this->repository->createRoomForParticipants($participants);

            return RoomResource::make($room);
            //

        }
    }

    /**
     * Get the fields available on the action.
     *
     * @return array
     */
    public function fields()
    {
        return [];
    }
}`
@p4rz1val

**Comment by p4rz1val** [comment]
![Imgur](https://i.imgur.com/LjnWqvQ.png)

**Comment by AshutoshJha15** [comment]
i have done that. i got this error in console when i click on the action button
![image](https://user-images.githubusercontent.com/50516423/66100519-ee8dc880-e5c8-11e9-99ee-82825029e0d1.png)

**Comment by jbrooksuk** [comment]
https://nova.laravel.com/docs/2.0/actions/defining-actions.html#defining-actions

This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](https://larachat.co/).
