### ISSUE TITLE
Metric number formatting in tooltips

### ISSUE THREAD

**Issue by jbrooksuk** [laravel/nova-issues#2001]
@jbrooksuk The number formatting isn't working in the tooltip neither. 
![Screenshot 2019-09-23 12 47 40](https://user-images.githubusercontent.com/680058/65420101-99033000-de00-11e9-87f7-341bf245bcac.png)

_Originally posted by @pelmered in https://github.com/laravel/nova-issues/issues/1847#issuecomment-534048697_

**Comment by pelmered** [comment]
Works good in Nova 2.5.0.
Thanks!

**Comment by xoco70** [comment]
I'm still having this issue with Nova 3.8.2

![Screenshot from 2020-07-30 12-14-16](https://user-images.githubusercontent.com/5855577/88911586-5307cb80-d25e-11ea-9607-56a5306d629c.png)


I have used: 

        return (new TrendResult)
            ->trend($actual)
            ->showLatestValue()
            ->suffix("%")
            ->withoutSuffixInflection();

As you can see, it work for the value, but not for the tooltip.
