### ISSUE TITLE
VueJs templates for components (DevExtreme)

### ISSUE THREAD

**Issue by kohutovic** [laravel/nova-issues#2002]
Hi, Vue components from devExtreme library do not work properly with Nova. I do not know why but templates there are not replaces with real content. Example: 
dependencies in package.json
``` 
"devextreme-vue": "19.1",
"devextreme": "19.1",
"devexpress-diagram": "latest"
```

component.js:
```<template>
    <dx-list
             :data-source="listData"
             itemTemplate="item">
        <template #item="{ data, index }">
            {{ index }} - {{ data.itemProperty }}
        </template>
    </dx-list>
</template>

<script>
    import 'devextreme/dist/css/dx.common.css';
    import 'devextreme/dist/css/dx.light.css';

    import DxList from 'devextreme-vue/list';

    export default {
        components: {
            DxList
        },
        data() {
            return {
                listData: [
                    { itemProperty: 'someValue' },
                    { itemProperty: 'someValue2' },
                ]
            }
        }
    }
</script>
```
List is renderer and each item should use template but all items are empty. This works withou an issue in empty project without Nova. Is there anything blocking nova to render templates properly? It completely blocks me to use while DevExpress library with our Nova project. Thanks.
Docs: https://js.devexpress.com/Documentation/Guide/Widgets/Common/Templates/

**Comment by jbrooksuk** [comment]
This looks to be a problem with DevExpress and not Nova.

**Comment by kohutovic** [comment]
> This looks to be a problem with DevExpress and not Nova.

It works outside the Nova. Don't you have an idea what can cause the problem?
