### ISSUE TITLE
HasOne/HasMany Child Field on Parent Index view

### ISSUE THREAD

**Issue by khalil-htme** [laravel/nova-issues#2003]
I Apologize in advance if this has been asked, I promise that I searched for the best of my ability.

I'm trying to display on Index a field inside of a HasOne/HasMany relationship:

HasMany::make('Posts');

Can i show a field like "Content" on the parent index by chance? I'm just giving an example for learning purposes.

I think this can be done easily from the Model, by calling a function "getSingleContent($request)" but how would I be able to display that content in the Resource?

**Comment by khalil-htme** [comment]
Idk... this could qualify as a solution.

1- You make a field in both parent and child
2- set the parent field = child field onRetreiving event

` 
public static function boot()
    {
        parent::boot();
        
        static::retrieved(function($request){
            $request->status = $request->approvalDetails()->first()->level;
        });
    }
`

**Comment by jbrooksuk** [comment]
A nicer solution may be to create a `Text` field which is only visible on the index. You can pull in and format the content from your relationships as you wish.
