### ISSUE TITLE
Actionable resources too fast/jarring

### ISSUE THREAD

**Issue by LorenzoSapora** [laravel/nova-issues#2006]
- Laravel Version: 5.8+
- Nova Version: 2.4.0
- PHP Version: 7.3
- Database Driver and Version: Mysql 5.8
- Operating System and Version: Ubuntu 19~
- Browser type and version: Firefox (69.0.2)

### Description

When a resource has the actionable trait, refreshes are distracting, and overly too fast. Even on localhost, I see it flash a refresh every 15 seconds. I understand the need for UI consistency, but having something update that jarringly isn't good UX.

### Steps To Reproduce

- Add `use Laravel\Nova\Actions\Actionable;` and `use Actionable` to model
- View resource detail

A fix might be allowing disabling of refresh? Or overlaying an opacity of the loading div on the existing rows?

Below is a 25 second gif of it happening

![Peek 2019-10-04 11-15](https://user-images.githubusercontent.com/25519274/66201213-b8b91480-e69a-11e9-9a62-232aa6adc690.gif)

**Comment by jbrooksuk** [comment]
We won't be adding a feature to disable the refresh as the primary use case is so that people can see when actions have completed which is valuable information.

**Comment by LorenzoSapora** [comment]
Sure, I wasn't expecting that functionality explicitly, but more along the lines of allowing, or changing, the visibility of refreshes, as jumping from a set table height of actions every 15 seconds can be jarring, but avoidable. 

I'd like to push more towards my second idea of an overlay, instead of changing the height of the card itself.

**Comment by jbrooksuk** [comment]
Okay, let's convert this to a feature request.

In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
You should be able to do the following from `NovaServiceProvider`.

```php
Laravel\Nova\Actions\ActionResource::$pollingInterval = 30;
```
