### ISSUE TITLE
Doesnt work delete button on nova 2.4.0

### ISSUE THREAD

**Issue by ganduras** [laravel/nova-issues#2007]
- Laravel Version: 5.8.35
- Nova Version: 2.4.0
- PHP Version: 7.3
- Database Driver and Version: mysql
<img width="1125" alt="Schermata 2019-10-04 alle 20 05 39" src="https://user-images.githubusercontent.com/19509631/66229727-c4302e00-e6e2-11e9-9bcf-6369143aca6f.png">

- Operating System and Version: mac
- Browser type and version: Chrome.77
- Reproduction Repository: https://github.com/###/###

### Description

Before 2.4.0 I had 2.1.1 
I migrated to 2.4.0 and now the opening on modal after click delete button doesnt work

**Comment by m2jobe** [comment]
Facing this same issue on 2.4.1

**Comment by m2jobe** [comment]
@ganduras Did you figure out why this was occurring?

**Comment by ganduras** [comment]
php artisan nova:publish

**Comment by notflip** [comment]
Has this been fixed already? We're still running on 2.3.1 because of this.

**Comment by stephanvd** [comment]
Having the same problem in version 2.5. Delete button in the list view is broken. Works in the details view.

In a list view the last item can still be deleted, all others are broken.

Tried republishing but not working.

Any ideas?

**Comment by valentinfily** [comment]
Same issue here even after republishing the assets

**Comment by notflip** [comment]
Having this issue on 2.5 as well.

**Comment by KangYoosam** [comment]
In my case, problem was fixed with firing `php artisan nova:publish`.

Nova version: 2.5.0

**Comment by applyACS** [comment]
this is not fixed with `php artisan nova:publish`
laravel: 6.4.1
nova: 2.6.1

any solutions?

**Comment by jbrooksuk** [comment]
@applyACS try using the `--force` parameter: `php artisan nova:publish --force`.

**Comment by tumispro** [comment]
I'm on 2.10.1 and the delete button isn't working for me either. `php artisan nova:publish --force` doesn't work for me either. The button doesn't have an anchor tag around it while the edit and view button do, not sure if that's by design.

**Comment by stephanvd** [comment]
Just upgraded after being locked at 2.1 all this time.

Our problem was due to the package [nova-left-resource-index-links](https://novapackages.com/packages/tanmuhittin/nova-left-resource-index-links) using a variation on an old version of Nova's views. Removing the package fixed it for us.

You might want to check if any of your installed packages overwrite Nova views.

**Comment by tumispro** [comment]
Ah, for me the problem was the [nova-nested-form](https://packagist.org/packages/yassi/nova-nested-form) package. Thanks!

Steps:
* Removed all packages -> delete button worked
* Reinstalled them in batches until delete button broke again

**Comment by cr8tpro** [comment]
Delete button is not working on my side as well! it works in Windows but not in ubuntu
I give up to use this.

**Comment by jasonlav** [comment]
Having this issue as well. Any solutions besides what has been mentioned?

**Comment by bostnis** [comment]
Previously, I met same issue and solved by configuring nginx configuration file. The project baseurl was incorrect so delete button URL was not working correctly. Please check your server configuration file.

**Comment by jasonlav** [comment]
This does not appear to be the issue in this case. There is a delete `button` element, but clicking it does nothing. As previously reported above, only the last row on the index page can be deleted with the button. This would not indicate any issues with nginx.
