### ISSUE TITLE
DB error when performing an action on model with morphMany relationship

### ISSUE THREAD

**Issue by brain82** [laravel/nova-issues#2008]
- Laravel Version: 5.8
- Nova Version: 2.3.1
- PHP Version: 7.3
- Database Driver and Version: 5.7
- Operating System and Version: Centos 6.1
- Browser type and version: Chrome 77

### Description

DB error when performing an action on model with morphMany relationship.

Due to the morphMany relationship in my model, the value of the **actionable_type** field in the **action_events** table is a numeric value (in my case 1) stored in a varchar field. Whenever I try to execute an action on any **User** that has an id similar to any other model (which already has an action in the action events table) that doesn't have a morphMany relationship, I get the error below. 

> Data truncation: Truncated incorrect DOUBLE value: 'App\Models\Request'

This is caused by this query

```
delete from `action_events` where `actionable_id` = 157 and `actionable_type` = 1 and `id` not in (select `id` from (select `id` from `action_events` where `actionable_id` = 157 and `actionable_type` = 1 order by `id` desc limit 25) as `action_events_temp`)
```

I did a quick Google search and found this

> This message means you're trying to compare a number and a string in a WHERE or ON clause.

I tried running the query with single quotes around the actionable_type values and the query error disappeared. 

```
delete from `action_events` where `actionable_id` = 157 and `actionable_type` = '1' and `id` not in (select `id` from (select `id` from `action_events` where `actionable_id` = 157 and `actionable_type` = '1' order by `id` desc limit 25) as `action_events_temp`)
```

So in the src (/nova/src/Actions/ActionEvent.php), I did a cast to string on the value of actionable_type 

```
/**
     * Prune the action events for the given types.
     *
     * @param  \Illuminate\Support\Collection  $models
     * @param  int  $limit
     */
    public static function prune($models, $limit = 25)
    {
        $models->each(function ($model) use ($limit) {
            static::where('actionable_id', $model['actionable_id'])
                ->where('actionable_type', (string) $model['actionable_type'])
                ->whereNotIn('id', function ($query) use ($model, $limit) {
                    $query->select('id')->fromSub(
                        static::select('id')->orderBy('id', 'desc')
                                ->where('actionable_id', $model['actionable_id'])
                                ->where('actionable_type', (string) $model['actionable_type'])
                                ->limit($limit)->toBase(),
                        'action_events_temp'
                    );
                })->delete();
        });
    }
```

### Steps To Reproduce

```php
class User extends Authenticatable implements MustVerifyEmail, CanResetPassword
{
	use Actionable, Notifiable;

	public $timestamps = false;

	public function events()
	{
		return $this->morphMany(Event::class, 'relatesTo', 'relates_to_type', 'relates_to_id')->orderBy('date_occured', 'desc');
	}
}
```

```php
class Product extends PCModel
{
    use Actionable, Notifiable;

	public $timestamps = false;

	public function events()
	{
		return $this->morphMany(Event::class, 'relatesTo', 'relates_to_type', 'relates_to_id')->orderBy('date_occured', 'desc');
	}
}
```

![db extract](https://user-images.githubusercontent.com/6013683/66246585-15edae00-e70d-11e9-9907-89917206915d.png)

**Comment by rasmuscnielsen** [comment]
I can second this issue. In my case it is not the 'type' that's a string but the id. I changed the migration to allow for strings, but ran into this issue when running actions

When reproducing this in sequel pro I found that changing

```
delete from `action_events` 
where `actionable_id` = 2 and `actionable_type` = 'Team' and `id` not in (
	select `id` from (select `id` from `action_events` where `actionable_id` = 2 and `actionable_type` = 'Team' order by `id` desc limit 25) as `action_events_temp`
);
```

to

```
delete from `action_events` 
where `actionable_id` = 2 and `actionable_type` = 'Team' and `id` not in (
	select `id` from (select `id` from `action_events` where `actionable_id` = '2' and `actionable_type` = 'Team' order by `id` desc limit 25) as `action_events_temp`
);
```

resolved the issue. Same fix as @brain82 .

Furthermore I found it may be related to this open MySQL 8 issue https://bugs.mysql.com/bug.php?id=95997

Basically the issue is a result of the way the prune deletion query relies on subqueries and compares strings with integers.

**Comment by umimehar** [comment]
Any update on this issue?

**Comment by zeeshanliaqat313** [comment]
facing the same issue? any solution for this issue?

**Comment by rasmuscnielsen** [comment]
@zeeshanliaqat313 Personally I ended up turning off events when running actions:

```php
class SomeAction extends \Laravel\Nova\Actions\Action
{
    public $withoutActionEvents = true;

    public function handle(...) { ... }
}
```

However even this seems like only half a solution. I've found siimilar MySQL errors to occur when deleting models as this will also attempt to delete related events. So far I've found no real fix on that except just not use Actionable on models with string ids...

See related issue: https://github.com/laravel/nova-issues/issues/141
