### ISSUE TITLE
Resource fields HasMany not honoring column name

### ISSUE THREAD

**Issue by anditsung** [laravel/nova-issues#2009]
- Laravel Version: "^6.0",
- Nova Version: 2.4.0
- PHP Version: "^7.2",

### Description

Formula Resource 
```
public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),

            Text::make("Materials", "name"),

            HasMany::make("Materials", "formula_material"),

            HasMany::make('formula_tanks'),
        ];
    }
```
Formula Model
```
public function formula_material() : HasMany
    {
        return $this->hasMany(FormulaMaterial::class);
    }
```

"Text" will honor column_name and create the label "Material"
"HasMany" will not honor column name but will return materials resource instead of formula_material

**Comment by jbrooksuk** [comment]
It looks like you're using the same column name for both the `Text` and `HasMany` field. This is not what Nova expects or allows.

**Comment by agrinceac** [comment]
I have the same problem.

public function grades(): HasMany
    {
        return $this->hasMany(RawGrade::class, 'deal_id', 'id');
    }

Code below gives me resutl form the server but does not display Grades relation table:
public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
           // HasMany::make('Grades', 'grades'),
            HasMany::make('Grades'),
        ];
    }

The next one gives me result from the server and display in text field Grades the following: [object Object],[object Object],[object Object],[object Object],[object Object]
public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
            HasMany::make('Grades', 'grades'),
            // HasMany::make('Grades'),
        ];
    }
