### ISSUE TITLE
Unable to upgrade per documentation instructions

### ISSUE THREAD

**Issue by adamthehutt** [laravel/nova-issues#201]
I'm following the instructions in the Nova documentation to update, but "composer update" doesn't seem to do anything. My best guess is that this is because I'm on a Windows filesystem, so composer was unable to create a symlink  at ./vendor/laravel/nova pointing to ./nova (it uses "mirroring" instead).

What's the best way to handle this?

**Comment by Andy-Baker** [comment]
I did a composer remove, deleted the vendor/laravel/nova directory and reinstalled.

**Comment by adamthehutt** [comment]
Yeah, that's what I ended up doing too. Really not a great long-term solution, though. 

I'm surprised there isn't any easy way to have a license-enforcing remote Git repo. Like maybe the license would come with an ssh key?

**Comment by davidhemphill** [comment]
You should be able to use Nova as a normal Composer dependency now to fix this.
