### ISSUE TITLE
An alternative way to get the model in action

### ISSUE THREAD

**Issue by khalil-htme** [laravel/nova-issues#2012]
What is the proper way to get the model from within the Action, I keep getting 403 [#1943 1943](https://github.com/laravel/nova-issues/issues/1943) 

If someone can point me to a better way to get the request data, or ID of the current request or any useful information and i will reverse the process that way.

The only current way I'm doing it, "which defeats the purpose of Laravel & Nova" is getting the ID that is passed in the URL and looking up the model, then looking up permissions associated with the model, then displaying the action :(

> After looking into this, I don't think it makes sense to add this since it's so easy to get the model from the request data.

[#1397 ](https://github.com/laravel/nova-issues/issues/1397)

Mentions an easy way to do so? how? 

[https://imgur.com/EMJjLeY](https://imgur.com/EMJjLeY) for image of the console

**Comment by jbrooksuk** [comment]
I'm afraid that I'm unsure what you mean. Can you provide me with some more information to help diagnose this issue please. A code example of what you'd like to achieve would be very helpful.

**Comment by dkulyk** [comment]
https://github.com/laravel/nova-issues/issues/1943#issuecomment-540455481 this is what you mean?
