### ISSUE TITLE
->asHtml() is not working well on nova V2.3.0

### ISSUE THREAD

**Issue by davidgabbay** [laravel/nova-issues#2013]
I posted this issue at the past, it was not posted it right.
Thus it was closed by a mistake.
Please recheck:

->asHtml() is not working well on nova V2.3.0

does not work on nova 2.3.0

Laravel Version:5.8.35
Nova Version: 2.3.0
PHP Version: 7.2.11
Database Driver and Version: sqlsrv
Operating System and Version: win10
Browser type and version: chrom

Description
using {$tracking_number} in a link does not convert to its value

Steps To Reproduce

            Text::make('Tracking number', function () {

            $tracking_number = $this->tracking_number;

            return '<a href="https://www.parcelmonitor.com/track-israel-post/track-it-online/?pParcelIds={$tracking_number}">@{$tracking_number}</a>';
            
        })->asHtml(),
================================

i do it exactly like

https://nova.laravel.com/docs/2.0/resources/fields.html#text-field

**Comment by jbrooksuk** [comment]
You're using [string interpolation](https://www.php.net/manual/en/language.types.string.php) incorrectly.

```php
Text::make('Tracking number', function () {
    $tracking_number = $this->tracking_number;

    return "<a href='https://www.parcelmonitor.com/track-israel-post/track-it-online/?pParcelIds={$tracking_number}'>@{$tracking_number}</a>";
})->asHtml(),
```

**Comment by davidgabbay** [comment]
> You're using [string interpolation](https://www.php.net/manual/en/language.types.string.php) incorrectly.
> 
> ```
> Text::make('Tracking number', function () {
>     $tracking_number = $this->tracking_number;
> 
>     return "<a href='https://www.parcelmonitor.com/track-israel-post/track-it-online/?pParcelIds={$tracking_number}'>@{$tracking_number}</a>";
> })->asHtml(),
> ```

what you wrote is not working

**Comment by jbrooksuk** [comment]
It works for me. To clarify, this issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](https://larachat.co/).

**Comment by davidgabbay** [comment]
> It works for me. To clarify, this issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](https://larachat.co/).

Its working without the @
meaning:
```
Text::make('Tracking number', function () {
    $tracking_number = $this->tracking_number;

    return "<a href='https://www.parcelmonitor.com/track-israel-post/track-it-online/?pParcelIds={$tracking_number}'>@{$tracking_number}</a>";
})->asHtml(),
```
