### ISSUE TITLE
Metric Cards reacting on Filter and Lense changes

### ISSUE THREAD

**Issue by cord** [laravel/nova-issues#2014]
For building interactive analytics dashboards there should be the option to use Filter and Lenses on Dashboards / Resources connected to the metrics. The selected parameters should be propagated into all defined metric cards on the Dashboard / Resources.

So when changing a filter the metrics are updated having the filter parameters added to their metric routes. Within the metric `calculate()` method the selected filter parameters can be applied.

**Comment by cord** [comment]
to be more precise:
metrics need to catch the `filter-changed` event

**Comment by jbrooksuk** [comment]
You should build a custom [card](https://nova.laravel.com/docs/2.0/customization/cards.html) component for this instead of Nova reacting to the events as there is no guarantee that the metric is setup to filter the same.

**Comment by cord** [comment]
> as there is no guarantee that the metric is setup to filter the same
I see, but the developer would only add metrics that make sense in the current context?

Would be great to get the option to access the current filter within the metrics and having metrics refreshed with filter changes.

**Comment by potsky** [comment]
Hi @cord !
Have you finally found a way to do this?

**Comment by cord** [comment]
@potsky not yet, but I think it could be solved through vue catching the filter-changed event.

**Comment by cord** [comment]
Some progress here: https://github.com/nemrutco/nova-filterable-metrics/issues/1

**Comment by glyphde** [comment]
Here's a hack:
  ```
 public function calculate(NovaRequest $request)

  {
        $model = Transaction::make();
        $queries = array();
        parse_str(parse_url(request()->headers->get('referer'),PHP_URL_QUERY), $queries);
        file_put_contents('debug.txt', print_r($queries,true));

        //        Laravel\Nova\Http\Requests\DecodesFilters

            // Get the decoded list of filters
            $filters = json_decode(base64_decode($queries['transactions_filter']));

```

**Comment by cord** [comment]
FYI: https://github.com/Nova-BI/nova-databoards

**Comment by ljmoleiro** [comment]
> Here's a hack, though you have to refresh the page:
> 
> ```
>   public function calculate(NovaRequest $request) {
>       $model = Transaction::make();
>       $queries = [];
>       parse_str(parse_url(request()->headers->get('referer'), PHP_URL_QUERY), $queries);
>       $filters = json_decode(base64_decode($queries['transactions_filter']));
>       foreach ($filters as $filter) {
>           if (empty($filter->value)) {
>               continue;
>           }
>           $model = (new $filter->class)->apply($request, $model, $filter->value);
>       }
> 
>       return $this->count($request, $model)->format('0,0');
>   }
> ```

How do you refresh de page?

**Comment by gbrits** [comment]
Thanks @glyphde, I modified your example slightly for my use-case, but was exactly what I needed. :)
RE the refreshing - you can make links that go directly to that filtered GET variable with the encoded data in it. In my instance I used jQuery to create links in the DOM.
