### ISSUE TITLE
css/js assets 404 when nova installed at non root of domain

### ISSUE THREAD

**Issue by blasto333** [laravel/nova-issues#2015]
- Laravel Version: 6
- Nova Version:2.4.0
- PHP Version: 7.2
- Database Driver and Version: mysql 6
- Operating System and Version: mac
- Browser type and version: safari
- Reproduction Repository: not sure

### Steps To Reproduce

In my development environment I install laravel and nova inside a folder

When I go to:
http://localhost/track-and-field-records/public/nova/login

css isn't loaded as it gives a 404....Do you know of a way to fix it without modifing core files?

This can be fixed by doing

FIND:
    <link rel="stylesheet" href="{{ mix('app.css', 'vendor/nova') }}">

REPLACE:

    <link rel="stylesheet" href="{{ asset(mix('app.css', 'vendor/nova')) }}">

**Comment by jbrooksuk** [comment]
Hi! Laravel is not designed to be installed under a sub-directory and will result in an insecure application. This is not something we will support.

**Comment by hlorofos** [comment]
Why on earth people decide what we would need and what we don't? At the end of the day its paid product, but lara guys way too often say they don't give a shit
