### ISSUE TITLE
Global Search for Resource Tool

### ISSUE THREAD

**Issue by miharbi** [laravel/nova-issues#2016]
Is there a way to use the global search for a tool? I mean, there is a Resource Tool where is the edit view for that case.

**Comment by jbrooksuk** [comment]
It's not yet possible for resource tools to hook into and display results in the global search.

What use do you have for this?

**Comment by miharbi** [comment]
Hi, it is a Resource Tool with a complex edit form, is like the main resource in the project

**Comment by miharbi** [comment]
I'm going to mix the current search with a custom only for my Resource Tools and replace it in resources/views/vendor/nova/layout.blade.php
