### ISSUE TITLE
Installing Nova without updating all composer dependencies?

### ISSUE THREAD

**Issue by chescos** [laravel/nova-issues#202]
I tried to install Nova only by running `composer update laravel/framework` and `composer update laravel/nova` instead of `composer update`, because I don't want to update all my dependencies.

This approach doesn't seem to work though (I am not sure why), as I get a `Method whereInstanceOf does not exist` exception when trying to access the `User` resource.

Tried to install it with `composer update` and the exception was gone.

Does anybody how to install Nova without updating all dependencies?

**Comment by rovansteen** [comment]
`composer update laravel/nova` is the correct way to only update Nova. The error you are describing is unrelated to the fact how you update Nova to the latest version. So you should try to figure out what that error exactly is and if it's related to Nova post that here.
