### ISSUE TITLE
Bug in SqlSrvTrendDateExpression when timezone offset is 0.

### ISSUE THREAD

**Issue by anderly** [laravel/nova-issues#2020]
- Laravel Version: 6.1.0
- Nova Version: 2.3.1
- PHP Version: 7.2
- Database Driver and Version: SQL Server 2016 (SP1-GDR) (KB4505219) - 13.0.4259.0 (X64)
- Operating System and Version: Windows 10
- Browser type and version: Chrome 77.0.3865.90
- Reproduction Repository: https://github.com/laravel/nova/blob/243432a3d5ae9f53a3c0927359f65c234390f1ef/src/Metrics/SqlSrvTrendDateExpression.php#L20

### Description

[Line 20](https://github.com/laravel/nova/blob/243432a3d5ae9f53a3c0927359f65c234390f1ef/src/Metrics/SqlSrvTrendDateExpression.php#L20) of the [SqlSrvTrendDateExpression](https://github.com/laravel/nova/blob/243432a3d5ae9f53a3c0927359f65c234390f1ef/src/Metrics/SqlSrvTrendDateExpression.php) sets an empty string as the interval when the timezone offset is 0. This breaks Trend Metrics because you end up with a SQL Expression like this:

```sql
FORMAT(DATEADD(hour, '', [column]), 'yyyy-MM-dd')
```

This breaks since the SQL Server DATEADD function can't add an empty string to a date.

Line 20 should either be changed to match [Line 18](https://github.com/laravel/nova/blob/243432a3d5ae9f53a3c0927359f65c234390f1ef/src/Metrics/SqlSrvTrendDateExpression.php#L18) as follows:

```sql
$interval = $offset;
```

**OR**, the first two conditions should be combined like so:

```sql
    if ($offset > 0 || $offset === 0) {
        $interval = $offset;
    } else {
        $interval = '-'.($offset * -1);
    }
```

**Comment by jbrooksuk** [comment]
Thanks! Sorry about that.
