### ISSUE TITLE
Fields are not shown on the edit page

### ISSUE THREAD

**Issue by plehanov** [laravel/nova-issues#2021]
- Laravel Version: 5.8.35
- Nova Version: 2.4.0
- PHP Version: 7.2
- Database Driver and Version: MySQL (ver. 5.7.27-0ubuntu0.18.04.1)
- Operating System and Version: Ubuntu 18.04.3 LTS
- Browser type and version: Chrome Version 77.0.3865.90

### Description

The form with the margins looks like this

```
public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),

            Text::make(__('Name'), 'name')
                ->sortable()
                ->rules('required', 'max:191'),

            Text::make(__('Email'), 'email')
                ->sortable()
                ->rules('required', 'email', 'max:191')
                ->creationRules('unique:users,email')
                ->updateRules('unique:users,email,{{resourceId}}'),

            Select::make(__('Role'), 'role')
                ->options(['USER' => __('User'), 'ADMIN' => __('Admin')])
                ->displayUsingLabels(),

            Password::make(__('Password'), 'password')
                ->creationRules('required', 'string', 'min:6')
                ->updateRules('nullable', 'string', 'min:6'),
        ];
    }
```
The list shows correctly the view page too. The edit page contains only save buttons - no fields presents.
I performed commands `php artisan nova:publish --force`, `php artisan view:clear` and `npm run prod`

### Steps To Reproduce
1. Setup Nova `php artisan nova:publish --force`
2.  `npm run prod`
3. go to Users
4. Open User edit page

**Comment by davidhemphill** [comment]
I was not able to replicate your issue. If you can find a way to reproduce this issue on a fresh instance of Nova, please post a new issue.

This is usually because Nova's assets were updated correctly, so I'd make sure and double-check that by deleting the published assets manually and running the command again. Also, check the console output for any errors.
