### ISSUE TITLE
Deleting a resource with an uuid column as primary key, produces SQL error with action_events table

### ISSUE THREAD

**Issue by jhm-ciberman** [laravel/nova-issues#2022]
- Laravel Version: `v6.0.3`
- Nova Version: `v2.3.1`
- PHP Version: v3.3.1
- Database Driver and Version: mysql 5.7.25
- Operating System and Version: homestead/any ubuntu
- Browser type and version: Any
- Reproduction Repository: https://github.com/###/### (I can create one if you need, but I don't think is necesary)

### Description

Trying to deleting a model with a long field as primary key (i.e. an UUID field) produces an SQL error.

For example: 
```
SQLSTATE[01000]: Warning: 1265 Data truncated for column 'actionable_id' at row 1 (SQL: 

insert into `action_events` (`actionable_id`, `actionable_type`, `batch_id`, `changes`, `created_at`, `exception`, `fields`, `model_id`, `model_type`, `name`, `original`, `status`, `target_id`, `target_type`, `updated_at`, `user_id`) values (5422416b-a3eb-48ba-9402-fe0372f024b9, App\ContactMessage, 8ed858c9-d325-45ce-9536-7297a7de2e90, ?, 2019-10-09 02:22:17, , , 5422416b-a3eb-48ba-9402-fe0372f024b9, App\ContactMessage, Delete, ?, finished, 5422416b-a3eb-48ba-9402-fe0372f024b9, App\ContactMessage, 2019-10-09 02:22:17, 1))
```

The problem seems to be in this line of code:  (At `ResourceDestroyController.php:35`)

```php
DB::table('action_events')->insert(
    ActionEvent::forResourceDelete($request->user(), collect([$model]))
        ->map->getAttributes()->all()
);
```
And then, when the data to be inserted in the ActionEvent model is build:
```php
'actionable_id' => $model->getKey(),
````
The problem is that `actionable_id` is defined as an:
```php
$table->unsignedInteger('actionable_id');
```
But my model primary key is defined as:
```php
$table->uuid('id')->primary();
```

Is there any way to disable event logging for those models? As far as I understand reading the Nova documentation, ActionEvents should only be logged for Models that use the `Laravel\Nova\Actions\Actionable` trait (and my model is not). Or should **every** model be logged? 

### Steps To Reproduce

1 - Create a model with a table that uses an UUID (or any long field). Example:
```php
        Schema::create('contact_messages', function (Blueprint $table) {
            $table->uuid('id')->primary(); // <== IMPORTANT 
            $table->text('message'); // etc
            $table->timestamp('created_at')->nullable();
        });
```
2 - Create a nova resource for that model
3 - Enter to the nova admin panel and try to delete a model

**Comment by jbrooksuk** [comment]
Yep, you can [disable the Action Log](https://nova.laravel.com/docs/2.0/actions/defining-actions.html#disabling-the-action-log).

**Comment by jhm-ciberman** [comment]
Yes, but according to the documentation, that is only for Action classes.
But this is not an action class, is a simple Eloquent Model.

**Comment by jbrooksuk** [comment]
Apologies!

https://github.com/laravel/nova-issues/issues/1832#issuecomment-522207118 has an example of how to do this.

**Comment by jbrooksuk** [comment]
If you're using UUID, you'll need to create a migration to change the `action_events.id` column to a string.

**Comment by bkintanar** [comment]
@jbrooksuk that solution wont work since the delete resource controller uses DB::insert not the ActionEvent model.

see #2379

**Comment by alfhh** [comment]
This solution worked for me using Nova 4: https://github.com/laravel/nova-issues/issues/1832#issuecomment-1434760923
