### ISSUE TITLE
Missing Thead because of Javascript dependencies

### ISSUE THREAD

**Issue by woutermoelker** [laravel/nova-issues#2024]
- Laravel Version: 5.7
- Nova Version: ~1.3
- PHP Version: 7.2.9

### Description

I wanted to add Bootstrap to a Tool's packages. But when i did this, the theads of every table in nova's automatically generated tables stopped working. These now are empty and do not show any data. (see file). 

After deleting bootstrap and other dependecies  this problem still occured and I cant seem to find a way to fix the theads. 

### Steps To Reproduce

add bootstrap to your custom nova component with NPM.
![missing Thead](https://user-images.githubusercontent.com/7361523/66465284-db737080-ea80-11e9-85be-025c63a7e7f1.PNG)

**Comment by jbrooksuk** [comment]
Likely, you'll need to remove the tool that you've registered.

**Comment by jbrooksuk** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](https://larachat.co/).
