### ISSUE TITLE
Read-only date fields show current date in edit screen

### ISSUE THREAD

**Issue by unlikenesses** [laravel/nova-issues#2025]
- Laravel Version: 6.0.2
- Nova Version: 2.2.0
- PHP Version: 7.2

### Description

I have a resource with a nullable read-only datetime field:

```php
public function fields(Request $request)
{
    return [
        DateTime::make('foobar')->nullable()->readonly(),
    ];
}
```

When I click "View" on a row which has a null value for `foobar`, it correctly shows a dash for that field. But when I click "Edit" on the same row, the field is apparently populated with the current date/time. It's not *really* populated with it, since when you update it correctly does not fill it in. But the appearance is still confusing.

**Comment by jbrooksuk** [comment]
What you're seeing there is the placeholder value, not an actual value. If the field is `nullable` and `readonly` we could hide the placeholder. Alternatively, if the field is readonly, maybe you could hide it from forms?

**Comment by jbrooksuk** [comment]
Yep! See the [Fields docs](https://nova.laravel.com/docs/2.0/resources/fields.html#showing-hiding-fields).

**Comment by jbrooksuk** [comment]
I'm inclined to close this as "no bug". It's a placeholder that you're seeing and you have the option to hide it.
