### ISSUE TITLE
Actionable issues with SQL Server due to dateFormat in ActionEvent

### ISSUE THREAD

**Issue by henryavila** [laravel/nova-issues#2027]
- Laravel Version: 6.1.0
- Nova Version: 2.4.0
- PHP Version: 7.3
- Database Driver and Version: MSSQL 5.6
- Operating System and Version: Ubuntu 18.04
- Browser type and version: All Browser

### Description

When using Actionable Trait, I always get Trailing Data on SqlServer.
Everything else, is working fine with the DateTime in SQL Server.

This happens because the only solution I found to work with SQL Server is use PRECISION = 3 in migration: `$table->timestamps(3)`. This will create a `DateTime2(3)` column in DB and all my app and all packages are working fine with it.

The solution to set `$dateFormat = 'Y-m-d H:i:s';` don't works in Nova and a lot of pacake brake it.

the problem is that the trait `Laravel\Nova\Actions\Actionable` uses `Laravel\Nova\Actions\ActionEvent` wich has harcoded: `protected $dateFormat = 'Y-m-d H:i:s';`

This completly breaks the actionable function. I always get 'trailling data'.

I Tried to Create Trait that uses a extended version of `\Laravel\Nova\Actions\ActionEvent` to overwrite the `$dateFormat` attribute, but when I did this, the actionable simple don't work (no relationship on Model)

**So I believe it's a Bug and the actionable should use the default dateFormat**

### Steps To Reproduce
- Laravel Nova with SqlServer using the default dateFormat (not changing it in anywhere)
- Add the Trait Laravel\Nova\Actions\Actionable to a model
- When load the model detail page, We get the Trilling Data error (because of the actions relation

**Comment by jbrooksuk** [comment]
I think I have a solution for you. You can customise the `ActionResource` class (see `./config/nova.php`) and specify a custom `$model`.

**Comment by henryavila** [comment]
Hi @jbrooksuk  unfortunately it don't solve the problem.

I created a new Resource Class extending the original, Created also a class to extend the `Laravel\Nova\Actions\ActionEvent` and then overwrite the `$dateFormat` attribute, but it not solved the problem.

For some reason, the overwrited `$dateFormat` attribute is not been used in Laravel nova.

here is my overwritten classes:

```
// Resource Class
use \Laravel\Nova\Actions\ActionResource as DefaultActionResource;
class ActionResource extends  DefaultActionResource
{

    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static $model = ActionEvent::class;
}

```

```
// Model Class
use \Laravel\Nova\Actions\ActionEvent as Model;

class ActionEvent extends Model
{

    /**
     * The storage format of the model's date columns.
     *
     * @var string
     */
    protected $dateFormat = 'Y-m-d H:i:s.000';

}
```
