### ISSUE TITLE
Nova Actions Should NOT depend on resource policies

### ISSUE THREAD

**Issue by christophrumpel** [laravel/nova-issues#2028]
I just ran into such a situation (#1611) and found out that Nova Actions are connected to the policy of the resource where you use your actions.

So right now you can only use an action when:

- there is no policy defined
- when the policy update method returns true
- when the policy delete method returns true (only for destructive actions)

I see no reason why an action should be connected to the resource's policy. Neither the default action nor the destructive one. For example, the "destructive action" just changes the color of the button, by no means it tells something about what happens inside the action or if it is connected to the deleting the resource itself. It just tells the user to be careful when hitting the button. But that's it.

If you want to define who can run the action, you should use the `canSee` method like that (for example):

```
public function actions(Request $request)
{
    return [
        (new MyNewAction)->canSee(function (Request $request) {
            $user = $request->user();

            return $user->isAdmin();
        }),
    ];
}
```

I think it would be a good idea to decouple actions from the resource's policy at all. Let me know what you think about that.

**Comment by julienbourdeau** [comment]
> For example, the "destructive action" just changes the color of the button, by no means it tells something about what happens inside the action or if it is connected to the deleting the resource itself.

I'm guess you could also see it as _"Destructive action should only be used when you delete resources, and it happens to change the color of the button"_.

Is there an easy way to create a new action type and change the frontend style? 🤔 

Using policies seems like a great feature (but I don't have as much context as you).

**Comment by christophrumpel** [comment]
Policies are great :-) But I don't see why the should be connected to the resource policy. There are so many things you can do with actions. Maybe you don't want a user to update the resource, but still, let him run an action on the resource?

Or you want to delete some related or connected data through an action, but don't want to let the user delete the resource itself? Yeah, you could use a "normal" action, but still, you want the user to be alarmed. So for me, a destructive action is just a highlighted version of it to alarm the user. It does not tell about what the action does and if it should be connected to deleting a resource.

There endless examples where the current implementation limits you a lot.

**Comment by chescos** [comment]
There have already been like 5 separate issues about this, many people are requesting this change. I don't see any reason why an Action should depend on a Policy either, it's so restrictive. Sometimes you just can't allow a Resource to be edited or deleted, so you use a Policy to prevent that. Great, now users can't run any Actions on the Resource anymore. Those two things really shouldn't be connected.

**Comment by epalmans** [comment]
First of all.... I totally agree that the update/delete policy shouldn't be checked on actions!

However, you could easily bypass the policy-checking by setting the Action runCallback by chaining the canRun method:

```php
public function actions(Request $request)
{
    return [
        (new MyNewAction)->canRun(function (Request $request) {
            return true;
        }),
    ];
}
```
(see bypass at ```Laravel\Nova\Actions\ActionModelCollection``` ```filterByResourceAuthorization()``` method)

or directly in the Action itself ofcourse:

```php
class MyNewAction extends Action
{
    use InteractsWithQueue, Queueable, SerializesModels;
    
    public function __construct()
    {
        $this->runCallback = function (Request $request) {
            return false;
        };
    }

    //
}
```

**Comment by christophrumpel** [comment]
Thanks for the workaround. I didn't know about that. Still, the main point here is about improving the implementation for everyone and prevent users from running in these situations.

**Comment by epalmans** [comment]
agree! Especially checking for ```update``` ability makes no sense at all imho.
I'd rather see it check for an ability that's not standard for policies (defaulting to true); e.g. like ```runAction```/```handleNovaAction```/```execute```

**Comment by davidhemphill** [comment]
Hey all,

We've discussed this many times before in previous issues. This might be the third time I've seen something related to this this week. :-)

First off, this would be a breaking change to disable this functionality and I'm not sure it makes sense. The primary use-case for Actions is to run updates/deletes on one or more resources, and this is the reason we delegate to the resource's underlying policy for whether it's visible/runnable by the user. This makes the most sense to us from a default perspective. 

I get folks use them to do tangentially-related functions to the resource (we refund licenses via API for example), and that's why the `canRun` and `canSee` methods are available to override this kind of thing.

Don't forget that you are able to create a base class that disables this similar to what @epalmans posted. Either way, I don't see how this is a show-stopper for anyone. Can someone explain that

**Comment by christophrumpel** [comment]
Hey David,

@jbrooksuk mentioned to open a new issue about it, this is why I did that :-) The other issues were about "bugs" / misunderstanding of the behavior. This one is about an `open discussion about the current implementation`.

Also, there are multiple issues related already, because the current behavior is not obvious. Don't get me wrong. This is not me trying to force a change because I want so. As you mentioned there are workarounds and I'm using them already. My goal here is to discuss if the current implementation is the best for Nova and its future.

"`The primary use-case for Actions is to run updates/deletes on one or more resources`". (Nova Docs) I'm not so sure about that. At least for my Nova projects in the last year, this is not the case. Most actions I use depend on someking of user roles or permissions and not the resource policy. But of course, the are lots of use-cases out there for actions.

Even the examples in the docs are about actions that are not really tight to the resource:

`Nova actions allow you to perform custom tasks on one or more Eloquent models. For example, you might write an action that sends an email to a user containing account data they have requested. Or, you might write an action to transfer a group of records to another user.`

- Sending an email with account data is not something that would make sense to prevent it through an update-policy on the resource
- Or transfer a group of records, also not connected to updating a resource. Maybe a user is not allowed to delete a resource but still allowed to transfer a group. Not possible right now with a destructive action without a workaround.

I would guess, in most cases, actions are not connected to the resource's policy. They have their own restrictions on who and when they can be used. I know it is a breaking change and this is always hard for a project, but details matter and I think Nova would benefit from it and it will give users more possibilities, more flexibility and fewer problems with actions out of the box.

It is just my opinion and maybe it is helpful. Maybe it is not, no worries :-) That's why it is an open discussion.

**Comment by demency** [comment]
I think that Nova Actions should depend on policies. Understanding that, you should have certain authorizations to create / view / update or delete a resource/model.

If you want to send an email there should be no problem. But if the email contains Eloquent models, you should have permissions to retrieve them.

If you want to change a resource group, depending on the database structure and relationships. You should check the policies. For example, if the group is given by the group_id column of resource table and a group change requires an update to a model, then the use of the policies is correct. But if the model in question is not updated and an intermediary table is used and the model is being updated by a relationship, the policies should also be used. 

```
$user->update(["group_id" => 1]); // Check update policy of user
$user->group()->associate($group); // Check update policy of user.... group too?
$group->users()->save($user) // Group and user update policy ?
```

Otherwise, you could consult, modify or delete resources for which you do not have permissions.

**Comment by davidhemphill** [comment]
@christophrumpel I appreciate your point of view. I think @demency's explanation reflects the thinking of both Taylor and I on this. While (perhaps) not 100% intuitive, we believe it's a better default and more in-keeping with what we had in mind originally. For just as many resource "tangentially-related" actions, I can think of an equal amount of potentially destructive ones.

Clearly people run into this a lot so maybe we'll change it in the next series. For the time being, is there a way you can see that we can better document it to make it more clear?

**Comment by christophrumpel** [comment]
Good points @demency and @davidhemphill. I probably disagree because of the way I use Nova and the actions I haven using so far. This way the current implementation is inconvenient. But probably the biggest point problem I see right now is that it is not clear to users.

So to answer your question, it probably would help to mention the connection to policies right at the beginning of the documentation section for actions. (not only for destructive actions) Or maybe adding an `Authorization` section to action could also help.

Thanks for taking the time to discuss this even if it was already discussed before.
