### ISSUE TITLE
Nova event 'resources-loaded' not emitted on resource edit

### ISSUE THREAD

**Issue by tanthammar** [laravel/nova-issues#2029]
The Nova event 'resources-loaded' is emitted on list-view, detail-view but not the edit view.
Need an event in order to execute js after Nova is done rendering.

(to use within a Nova Theme, vanilla js script file)

Currently using a setTimeout function on document.readyState, not an optimal solution.

**Comment by jbrooksuk** [comment]
Thanks for reporting this @tanthammar. I think that we should emit the singular event: `resource-loaded` here, would you agree?

**Comment by tanthammar** [comment]
Totally agreed :)

**Comment by tanthammar** [comment]
I can see that the event is inconsistently emitted. Sometimes it is triggered when I change resource index view and sometimes not, the same goes for detail view. Form view does never fire (not that I have seen).
To be fully useful, it "should" be emitted on every view load when Nova is complete.

**Comment by tanthammar** [comment]
Recording events:
https://www.dropbox.com/s/z9ft4o0vs55ut6r/Sk%C3%A4rminspelning%202019-10-10%20kl.%2017.37.16.mov?dl=0

**Comment by davidhemphill** [comment]
What's the theme do that an event is needed?

**Comment by tanthammar** [comment]
It adds css classes to items on the page for styling and a click event.

**Comment by tanthammar** [comment]
I tried document.onreadystatechange() but that is to early.
Simplified Example:
```js
var acc = document.getElementsByClassName("mb-3 text-90 font-normal text-2xl");
var i;
for (i = 0; i < acc.length; i++) {
    acc[i].classList.add('my-special-style');
    acc[i].addEventListener("click", function () {
      // perform magic stuff
    }
}
```
