### ISSUE TITLE
UpdateAttached.vue Update button localization improvement

### ISSUE THREAD

**Issue by YassineGherbi** [laravel/nova-issues#203]
When updating a resource the Update button text is prefixed by the (translated) Update word. In English, this makes total sense. (Update Article, Update Post, etc.)

In, for example, Dutch, not so much. The word 'Update' is translated to 'Bijwerken'. But appending a resource name to it doesn't make sense. (Bijwerken Artikel should actually be Werk Artikel Bij or Artikel Bijwerken). 

I think this would also be a problem in other languages. I checked the docs but couldn't find a way to completely overwrite this update string.

<img width="1396" alt="screen shot 2018-08-25 at 11 11 03 pm" src="https://user-images.githubusercontent.com/15906337/44623053-1e927480-a8bd-11e8-8383-c1a3fe3ea414.png">

Maybe provide a method in the Resource class that can return the desired Update button text. I would like to make a pull request but didn't find the project on GitHub.

**Comment by v1nk0** [comment]
+1 this is the case for other languages as well

**Comment by cannect** [comment]
+1 need this soon for Dutch

**Comment by Sciscitator** [comment]
+1
Having same problem with german translation

**Comment by bonzai** [comment]
It's hard to fix translations with a `:resource` variable.

Let's use Polish as an example:

## Resources

### User

- singulal - `Użytkownik`
- plural - `Użytkownicy`

### Payout

- singulal - `Wypłata`
- plural - `Wypłaty`

## Views

### Create

#### Headers (`New :singularName`)

- `New User` - `Nowy użytkownik` (👍)
- `New Payout` - `Nowy wypłata` (😡, should be - ~~`Nowy`~~ `Nowa wypłata`)

#### Buttons (`Create :singularName`)

- `Create User` - `Dodaj użytkownik` (😡, should be - `Dodaj` ~~`użytkownik`~~ `użytkownika`)
- `Create Payout` - `Dodaj wypłata` (😡, should be - `Dodaj` ~~`wypłata`~~ `wypłatę`)

**Comment by FaridAghili** [comment]
This issue applies on Persian language as well:

For example:
New = جدید
New Post = پست جدید

**Comment by Insolita** [comment]
+1 Same issue for Ukrainian, Polish and Russian; There are many languages with more complex grammatical cases, than English, and only plural and singular labels are not enough;  
In english for variants
     - The User,  Add User, Show User, For User, Details of User, ByUser  - "User" word not modified, and its in singular form
     - All Users, Delete Users...  "Users" word also not modified, as plural form

In many other languages, for previous cases words "User/Users" have modifications  in each case;
https://en.wikipedia.org/wiki/Grammatical_case

User - Пользователь, 
Users - Пользователи, 
Add User - Добавить Пользователя, 
For User - Пользователю,
By User - Пользователем
Delete Users - Удалить Пользователей

**Comment by rapitkan** [comment]
+1 Same problem with Finnish language too.

**Comment by Senexis** [comment]
+1, would like to see something like "Create :model" used in strings instead of "Create" and "Model" as separate strings.  Would also make capitalization easier, as some language don't display action text in "Title Case", but instead in "Sentence case". Finally, please do make use of Laravel's `trans_choice()` function instead of static functionality, as some language distinguish between different amounts of an item.

**Comment by ppisecky** [comment]
Declension is the biggest problem I see currently. In a lot of languages nouns and their suffixes have to be modified based on the context in which they are used. So for example in Slovak:

- `Order` = Objednávk`a`
- `New order` = Nová objednávka (this is fine so far)
- `Create order` = Vytvoriť objednávk`u`
- `Order details` = Detaily objednávk`y`

This is the case for several languages. [Wikipedia](https://en.wikipedia.org/wiki/Declension) currently lists  some 15 languages that use declension, including German, Finnish, Czech, Dutch, Greek, Polish and Russian. I'm honestly not sure though how this could be implemented.

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by mathieutu** [comment]
Hi @davidhemphill.
As you can see, for lot of people this issue is a real bug.
This is about the Nova translations not working "properly".

**Comment by dillingham** [comment]
Yeah this seems like a bug not a request

**Comment by Senexis** [comment]
This seems to be an issue people have which has been referenced multiple times and reacted to by multiple people over a period of 6 months. Please keep this open and solve it. It is a problem for people not using Nova in English and it seems that the development interest in this is zero to none, while I, and judging by the response time of these other reactions others as well, feel this is an important issue to fix.

**Comment by v1nk0** [comment]
Bad thing, that after 6 months we're still waiting without any feedback. I'd at least like to know if this is something that the developers want to fix/solve and if so, where this thing is on the priority list.
I think it's keeping a lot of people from using Nova for real projects because it's just painful to "ship" something with such basic grammar-/language- mistakes (if the backend language is not english of course)

**Comment by bonzai** [comment]
I'm working on this issue, but no ETA (I do that in my free time).

laravel/nova#185

**Comment by ppisecky** [comment]
@bonzai Do you need any help with that?

**Comment by bonzai** [comment]
No, there's only one thing missing, and I'll try to finish it in a week or two.

**Comment by mathieutu** [comment]
@bonzai you posted us a link to the PR in the nova repo. 
Is it accessible in any way, or do you just have a private access to it?

**Comment by bonzai** [comment]
@mathieutu: You can get access to the repository here:

https://nova.laravel.com/settings#github

**Comment by mathieutu** [comment]
@bonzai oh thanks, I didn't see that coming!

**Comment by dakira** [comment]
@davidhemphill This is about an existing feature (localizable nova) not working. So i'd argue it's a bug. :)

**Comment by wvervuurt** [comment]
> Bad thing, that after 6 months we're still waiting without any feedback.

> it's just painful to "ship" something with such basic grammar-/language- mistakes (if the backend language is not english of course)

Absolutely. At least give us the option to use configurable static button labels (New, Save, Close) so we can ship without painful grammatical errors.

**Comment by wvervuurt** [comment]
@davidhemphill Can you guys please respond to this? Is the official stance that Nova only supports projects in English or can we expect to be able to release projects in different languages as well?

**Comment by Insolita** [comment]
@davidhemphill  i join to previous question. If nova will not officially support non-english  localizations with it specific, we will switch to sharp project https://github.com/code16/sharp

**Comment by wvervuurt** [comment]
I advise anyone who paid for Nova and is suffering from this issue to send a message through nova.laravel.com (click the Help icon in the bottom-right corner). They should either acknowledge this as a bug so we can expect a fix, or give us our money back.

@bonzai Did you make any progress on the PR for this feature? I'm sure there are people willing to help if need be. Thanks!

**Comment by bonzai** [comment]
@wvervuurt: I don't work on Nova anymore.

**Comment by davidhemphill** [comment]
This should be fixed in https://github.com/laravel/nova/commit/3d638799c89be10563a6c73913d1da544b88d080. Will ship in the next release.

**Comment by ArroWsGM** [comment]
@davidhemphill, maybe I miss something, but how can this help to fix the issue? We still having Yoda-talking buttons in Ukrainian

**Comment by kgp43** [comment]
Any update on this? Has it been added? Can't find it in the documentation.
