### ISSUE TITLE
laravel nova login page

### ISSUE THREAD

**Issue by anditsung** [laravel/nova-issues#2030]
can nova add to check login page from local resource first?
i dont want to make any change on the actual code on nova..

**Comment by jbrooksuk** [comment]
I'm sorry, but I don't fully understand your question?

**Comment by anditsung** [comment]
If app/resource/view/auth/* exist load this than nova/resources/view/auth/*

**Comment by jbrooksuk** [comment]
Are you referring to the Nova login view?

**Comment by anditsung** [comment]
yes. can we customise it?

**Comment by jbrooksuk** [comment]
Yes, you can customise it.

You'll need to publish the assets provided by Nova and then edit the one found in `./resources/vendor/nova/.

This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](https://larachat.co/).
