### ISSUE TITLE
DatePicker stays on the screen when clicking back on browser

### ISSUE THREAD

**Issue by koss-shtukert** [laravel/nova-issues#2033]
- Laravel Version: 5.8
- Nova Version: 2.4.0
- PHP Version: 7.1
- Operating System and Version: Windows 10 (64 bits)
- Browser type and version: Version 77.0.3865.90 (Official Build) (64-bit)

### Description

When I open a date input on the edit/create a page and after click back in the browser, the calendar still stays on the screen 

### Steps To Reproduce

- Open the edit/create page
- Click to the date input (Open calendar picker)
- Click back button on the browser

![image](https://user-images.githubusercontent.com/709096/66637074-0b567b80-ec1b-11e9-89e8-a651927d2981.png)

![image](https://user-images.githubusercontent.com/709096/66637232-4bb5f980-ec1b-11e9-8a07-b91d461fdfb4.png)

I think it's happening because the component doesn't have a  `beforeDestroy` method, like this:

```
        ...
        beforeDestroy() {
            this.destroyDateTime()
        },
        ...
```

**Comment by jbrooksuk** [comment]
Confirmed.

**Comment by koss-shtukert** [comment]
@davidhemphill 
In which reason this issue was closed?

**Comment by jbrooksuk** [comment]
@koss-shtukert the issue was closed because the fix has since been implemented however, the fix is not yet released.
