### ISSUE TITLE
Exceptions are not reported

### ISSUE THREAD

**Issue by davealberon** [laravel/nova-issues#2034]
The exception handler is changed to `Laravel\Nova\Exceptions\NovaExceptionHandler` instead of `App\Exceptions\Handler`. I think this is to fix #1261 by ignoring a custom `render()` method.

However, this means the `report()` method is also ignored, so exceptions are not reported to [Sentry](https://docs.sentry.io/clients/php/integrations/#laravel-5-x), for example.

I'm not 100% sure if this is a bug or by design, or if there's another mechanism the Sentry package could be using to capture exceptions, but it was certainly unexpected for us that users were seeing exceptions ("Server Error" messages) that weren't being reported.

**Comment by demency** [comment]
You can bind your own Handler implementation by adding the following code in your `NovaServiceProvider`:

````
<?php

namespace App\Providers;

use Laravel\Nova\Exceptions\NovaExceptionHandler;
use App\Exceptions\Handler;

class NovaServiceProvider extends NovaApplicationServiceProvider
{
    /**
     * Register Nova's custom exception handler.
     *
     * @return void
     */
    protected function registerExceptionHandler()
    {
        $this->app->bind(NovaExceptionHandler::class, Handler::class);
    }
````

Good luck!

**Comment by davealberon** [comment]
Yeah, that's my current workaround.

**Comment by demency** [comment]
I just tested if I can report an error and after throwing an exception, the event came to sentry.

How is your Handler class?

**Comment by davealberon** [comment]
When you say "after throwing an exception", was that testing in a Nova API route? Sentry still works fine outside Nova, but wasn't reporting anything when Nova threw an exception.

In my case, I forgot a "required" validation rule, and MySQL is in strict mode, so it threw this exception when the field was left blank:

> URL: /nova-api/applications?editMode=create&editing=true
> Illuminate\Database\QueryException
> SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null (SQL: insert into ...

My handler, used by non-Nova pages is exactly what the Sentry docs linked say it should be:

```php
<?php

namespace App\Exceptions;

use Asset;
use Exception;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Str;
use Throwable;

class Handler extends ExceptionHandler
{
    ...

    public function report(Exception $exception)
    {
        // Sentry - https://docs.sentry.io/platforms/php/laravel/#laravel-5x
        if (app()->bound('sentry') && $this->shouldReport($exception)) {
            app('sentry')->captureException($exception);
        }

        parent::report($exception);
    }

    ...
}
```

This is the custom handler I added for Nova only (I can't use the same one because the render() method is also customised - not included above - and I haven't bothered to pull out the Sentry part into a trait / helper method for now):

```php
<?php

namespace App\Exceptions;

use Exception;
use Laravel\Nova\Exceptions\NovaExceptionHandler;

class NovaHandler extends NovaExceptionHandler
{
    public function report(Exception $exception)
    {
        // Sentry - https://docs.sentry.io/platforms/php/laravel/#laravel-5x
        if (app()->bound('sentry') && $this->shouldReport($exception)) {
            app('sentry')->captureException($exception);
        }

        parent::report($exception);
    }
}
```

And the change to the service provider:

```php
<?php

namespace App\Providers;

use App\Exceptions\NovaHandler;
...
use Illuminate\Contracts\Debug\ExceptionHandler;
use Illuminate\Support\Facades\Gate;
use Laravel\Nova\Nova;
use Laravel\Nova\NovaApplicationServiceProvider;

class NovaServiceProvider extends NovaApplicationServiceProvider
{
    ...

    public function boot()
    {
        parent::boot();

        Nova::serving(function () {
            ...

            // Report Nova exceptions to Sentry
            // Overrides NovaApplicationServiceProvider::registerExceptionHandler()
            $this->app->bind(ExceptionHandler::class, NovaHandler::class);
        });
    }

    ...
}
```

My preferred solution would be for Nova to use the standard `report()` method and only override the `render()` method... But I don't know if that's technically feasible, so second preference would be for it to be simpler to override the Nova-specific `report()` method, or at least documented by Nova (and/or Sentry) that the `report()` function will be ignored by Nova unless you do the above.

**Comment by demency** [comment]
Your binding doesnt work. 

$this->app->bind(NovaExceptionHandler::class, YourHandler::class)

First argument must be NovaExceptionHandler. By using 'throw new Exception()' you can test it. Even more, doesnt use nova serving. Use registerExceptionHandler method.

**Comment by davealberon** [comment]
Yes, it does work.

**Comment by demency** [comment]
🤔 In your third paste, you are binding a contract. How it can work?

**Comment by davealberon** [comment]
I am binding a contract (first param) to a class (second param), exactly as designed.

**Comment by davealberon** [comment]
No, it uses the `ExceptionHandler` contract, and `NovaExceptionHandler` is the implementation. I literally copied it from the core code. You are right when you said I could override `registerExceptionHandler()`, which would simplify it a fraction perhaps, but the result is *exactly* the same.

**Comment by demency** [comment]
Yes, and you should replace the implementation with your own, otherwise you would never report exceptions to sentry.

**Comment by davealberon** [comment]
Trust me, my code works just fine. But in any case, it's not important to this issue.

To reiterate, the issue I wanted to report is (a) without us adding a custom exception handler like this it's not reported to Sentry, and (b) I couldn't find that explained anywhere so it was unexpected and caused real bugs to go unreported.

**Comment by eithed** [comment]
I've noticed the same thing as OP - default Laravel exception handler is ignored by Nova, thus Sentry doesn't get notified.

I've noticed that simply binding standard handler works

```
use App\Exceptions\Handler;

class NovaServiceProvider extends NovaApplicationServiceProvider
{
    /**
     * Register Nova's custom exception handler.
     *
     * @return void
     */
    protected function registerExceptionHandler()
    {
        $this->app->bind(NovaExceptionHandler::class, Handler::class);
    }
}
```

but that begs the question why Nova isn't using it by default

**Comment by davealberon** [comment]
@eithed I believe it's because they don't want to use the default handler's `render()` method in case it has been overridden - see #1261. It's just a shame they ignore the `report()` method too.

**Comment by SadeghPM** [comment]
This behavior must be clarify in Nova documentation.

**Comment by stephan-v** [comment]
+1 Please document this. Also why is Nova not using the default handler what are the downsides of implementing your own so Sentry actually works?

**Comment by bkuhl** [comment]
Was hoping that something simple like below would do it... but locally I end up with a `502 Bad Gateway` and no errors, so I'm falling back to the `if($prod) { //send to bugsnag }` approach.

```
Nova::report(function ($exception) {
    report($exception);
});
```
