### ISSUE TITLE
Value Metric add yesterday key

### ISSUE THREAD

**Issue by ndberg** [laravel/nova-issues#2035]
There are four special Ranges in the value metric
```
        return [
            'TODAY' => 'Today',
            'MTD' => 'Month To Date',
            'QTD' => 'Quarter To Date',
            'YTD' => 'Year To Date',
        ];
```

It would be great to have another one for 'YESTERDAY'.

OR, it would be even better to have the ability to disable the time in the ranges, when used with values, like:
```
    return [
        5 => '5 Days',
        10 => '10 Days',
        15 => '15 Days',
    ];
```

Now they're not usable for me as I never want to see half days in past.

By the way, the 'TODAY' key lacks in the documentation: [https://nova.laravel.com/docs/2.0/metrics/defining-metrics.html#value-ranges](https://nova.laravel.com/docs/2.0/metrics/defining-metrics.html#value-ranges)

**Comment by jbrooksuk** [comment]
> By the way, the 'TODAY' key lacks in the documentation: https://nova.laravel.com/docs/2.0/metrics/defining-metrics.html#value-ranges

Thanks! I've added this to the docs.

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
