### ISSUE TITLE
Login route does not respect the middleware stack

### ISSUE THREAD

**Issue by stancl** [laravel/nova-issues#2036]
- Laravel Version: 6.2.0
- Nova Version: 2.4.0
- PHP Version: 7.2

### Description

The `/nova/login` route does not use the `nova.middleware` middleware stack. It uses only the `web` group.

I added a middleware to the `web` group to do some debugging:
```php
dd($request->route()->uri, $request->route()->middleware());
```

`/nova` works correctly:

![Screenshot from 2019-10-12 16-05-29](https://user-images.githubusercontent.com/33033094/66702681-7fbc1800-ed0a-11e9-84fe-55d6c585c67f.png)

However, `/nova/login`:

![Screenshot from 2019-10-12 16-05-19](https://user-images.githubusercontent.com/33033094/66702682-8054ae80-ed0a-11e9-9fbf-bb78f482efc4.png)

**Comment by jbrooksuk** [comment]
I believe this is the expected behaviour. We don't want to make the login route require authentication otherwise we'll end up with an infinite redirect.

If you need to customise the the middleware on the login routes, you can override these within your `NovaServiceProvider`:

```php
/**
    * Register the Nova routes.
    *
    * @return void
    */
protected function routes()
{
    Nova::routes()
            ->withAuthenticationRoutes(['web', App\Http\Middleware\MyMiddleware::class])
            ->withPasswordResetRoutes()
            ->register();
}
```

**Comment by stancl** [comment]
I see, makes sense. I'll try the service provider solution, thanks.

**Comment by rvvincelli** [comment]
Hi @jbrooksuk , thank you for this solution.

Today we had to add the same middleware both on a Nova 2 and a Nova 4 codebase, and indeed on Nova 2 stacking the entry in the `middleware` array does not work - the middleware does not get picked up at all. Adding it to the service provider works though. On Nova 4, adding it to the `middleware` and `middleware_api` entries works though.

Why this difference? In particular, the same configuration yields two different behaviors in the two majors? Thanks,
