### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by lucasromanojf** [laravel/nova-issues#204]
It would be good to add breadcrumbs to the screens after index, sometimes we get a bit lost.

**Comment by yaserzizo** [comment]
+1

**Comment by disitec** [comment]
I miss the ability to going bak to main resource when you add / edit a relation

**Comment by meyer59** [comment]
For breadcrumbs check #90

**Comment by disitec** [comment]
@meyer59 That issue has been closed for the highlighting of the active resource.

**Comment by robmpreston** [comment]
This one absolutely HAS to happen. It's totally unusable for nested models right now. Testing this out for a client site and it will be a mess if they go 3 levels down with no breadcrumbs.

@davidhemphill Thoughts?

**Comment by taylorotwell** [comment]
Hit the back button in your browser.

**Comment by taylorotwell** [comment]
I'm sorry if this sounds harsh but this sort of functionality is literally built into your browser. A mechanism for going back to where you were. There should be no concept of "getting lost". You can just hit the "back" button.

**Comment by disitec** [comment]
@taylorotwell @davidhemphill has tagged this as request planned. This is going to be addressed or the solution is hitting the back button?

**Comment by taylorotwell** [comment]
We talked about it a bit. We just don't see it as high priority right now.

**Comment by robmpreston** [comment]
Wow, the back button, how did I never think of that?

**Comment by lucasromanojf** [comment]
Taylor, I am sorry but you live in another reality. If you are selling something for worldwide, you should consider different kinds of users and cultures. There in USA, people are habituated to this kind of system as I am understanding. Here, we have some kinds of clients that almost cant read and write their native language. I used to think like you and I would love if everyone could use the apps the way we think is ok, but unfortunately this does not happen. It is very different when we build things for developers and for end users. But if you say that Nova is not built for end users but for the developers, that's another story.

**Comment by laurencei** [comment]
The problem is the "back" button is not always the answer, especially with relationships.

Example;

I have a resource of `user` with many `posts`, I go to User A and "create new post". I enter some post details and click "Create Post". I am now on Post 1 page. If I press back - I dont end up at User A - I end up back at the "create post" screen.

So this is where you need to be able to navigate to a "parent" or similar relationship...?

**Comment by davidhemphill** [comment]
If you create a post via a user, you will get redirected to the post's "detail" screen which already has a link to the user.

**Comment by robmpreston** [comment]
@davidhemphill Just give us enough customization within Nova that we can build this ourselves if we want without having to modify core Nova. That way we don't have to agree or disagree over what does or doesn't make sense and teams like ours can just build out things that are missing.

**Comment by davidhemphill** [comment]
I've got a PR in to add overridable custom vue components one could make a breadcrumbs package for.

**Comment by davidhemphill** [comment]
Just merged! Should go out in the next release.

**Comment by disitec** [comment]
Looking forward to see this! We are currently working on a date filter.

This is going to help a lot. Thanks.

**Comment by laurencei** [comment]
@davidhemphill 

> If you create a post via a user, you will get redirected to the post's "detail" screen which already has a link to the user.

Maybe I'm missing something - but I dont see a "link to the user" on the post "detail" screen? Can you clarify where this should be?

**Comment by dillingham** [comment]
package development proposal
https://github.com/tightenco/nova-package-development/issues/48

**Comment by laurencei** [comment]
Ok - so for those coming here - I think I worked out what @davidhemphill was trying to say.

If you always add the relationship to your `fields()` - then the relationship can act as the breadcrumb on your page.

So I've been adding something like this: 

            new Panel('Post', [
                BelongsTo::make('Post')->onlyOnDetail()
            ]),

Which then always gives me a link to the "parent".

**Comment by bernhardh** [comment]
@davidhemphill:
>I've got a PR in to add overridable custom vue components one could make a breadcrumbs package for.

Is there also a documentation for this, so I can start making a package for it? Nova is such a great product and you are working hard, implementing missing features, but documentation on changes and features is really poor.

@taylorotwell 
>Hit the back button in your browser.

Just to mention two other usecases for breadcrumb, where your "hit back button" suggestion is useless: 
- If you get a deeplink on a resource (via skype, mail or if a resource detail is mentioned somewhere in a wiki, documentation, etc.) you literally can't use your back button. 
- If you clicked on index view on edit button, changed some of the content, but don't want to save the changes you can't directly access the detail view. You have to hit the back button and then search for the row you just saw and click on view button.
- Using tab-package, you would need to hit as often the back button, as often you changed tabs
- etc.

**Comment by OwenMelbz** [comment]
I think other people have also pointed this out, but in addition to why the argument of "use the back button"

1. When creating multiple relationships etc you get taken away several places, which makes it terrible UX to get back to the resource your on.

2. You'll then say - right click on the back button and jump to the page, which again would be an idea, if the page title for every page wasn't the same.

So theoretically yeah use the back button, but for this to be a solution you need to make the back button work as expected, which in this case, it does not :(

**Comment by dillingham** [comment]
Someone made a package for this. 

https://packagist.org/packages/chris-ware/nova-breadcrumbs

**Comment by josephxwf** [comment]
> We talked about it a bit. We just don't see it as high priority right now.

Because our staff do not know how to get back to previous page, that's only easy for developer!!!!

**Comment by nasrulhazim** [comment]
Yeah, my client still insist want to have the back button.

Any workaround for this? or any ideas to solve this? Breadcrumb seems to be a second choice, the client want back button.

**Comment by dillingham** [comment]
No one here works for your clients 

Tell them there is a back button on the browser 🙄

**Comment by encomienda** [comment]
it’s essential to have back button on the page itself somehow it makes the workflow faster rather than dragging up your mouse to hit the back button imo 🙂.

**Comment by immersiontravis** [comment]
+1

IMO, this is an essential feature.

It simply isn't true that the browser's built-in functionality makes breadcrumbs redundant.

Breadcrumbs provide humans with at-a-glance context for their current location in a (potentially complex) object hierarchy. (This becomes especially critical when you're working in multiple tabs, and can easily forget the context for each individual tab.) It also helps to _reinforce_ a mental model of the object hierarchy in the user's brain. Nothing in the browser does that.

Breadcrumbs also allow the user to navigate directly to any ancestor of the current object. Sure, you can do the same thing by clicking and holding on the "Back" button and selecting a previous page in your history – but who actually does that? No one that I know. It's awkward and unintuitive. The order of the browser history is unrelated to the hierarchical order of the objects. And many less-technical users, despite what you might wish, don't even know that this feature exists.

This is why breadcrumbs are an absolutely standard feature in web interfaces which present complex hierarchies.

**Comment by gavinhewitt** [comment]
Wow, I was looking for why breadcrumbs are not part of the core and then I found this:

> Hit the back button in your browser.

That is an extremely arrogant attitude towards the people that are paying for your product. I love Laravel/Nova and I love what you guys have done, but this, just wow

👎

**Comment by lucasromanojf** [comment]
> Wow, I was looking for why breadcrumbs are not part of the core and then I found this:
> 
> > Hit the back button in your browser.
> 
> That is an extremely arrogant attitude towards the people that are paying for your product. I love Laravel/Nova and I love what you guys have done, but this, just wow

@gavinhewitt nevermind, I had one from Taylor one of these days that was worse. Not sure if I should copy and paste here.

**Comment by dillingham** [comment]
When “hit the back button” with a considerable explanation is treated as insulting, it’s time to step back and realize you’re being a little sensitive :)

**Comment by gavinhewitt** [comment]
@dillingham I have sensitive skin, that is correct! ;-)

Not exactly sure what you mean with 'especially from someone who seems to be using a wrongfully published repo'. Where did you get the idea I did not pay for Nova??

**Comment by jbrooksuk** [comment]
> Edit: I think you're referring to the fork of nova. Yes, I forked an unauthorized nova to be able to check it out. The thing with nova is that there is no way of testdriving before you buy. And after the testdrive I bought a license like a good citizen. Sooo...

That does not make it okay. Nova is a licensed piece of software and is not available for redistribution.

Internally, we have discussed making a demo of Nova available.

**Comment by gavinhewitt** [comment]
@jbrooksuk A demo would definitely help. I'm pretty sure people are hesitant to get a license because they have no idea what they are getting, even if it's only $99 and made by Taylor.

**Comment by jbrooksuk** [comment]
I think that the [Nova website](https://nova.laravel.com) does a very good job of explaining what you get, but we're definitely looking into providing a demo site at some point.

**Comment by norotaro** [comment]
I paid Nova's license to develop a small project, I ended up migrating to [OctoberCMS](https://octobercms.com/) because the user was confused when navigating between the views of the models that were related (I had relationships of up to 3 levels). Now I have a useless license.

**Comment by robmpreston** [comment]
> I paid Nova's license to develop a small project, I ended up migrating to [OctoberCMS](https://octobercms.com/) because the user was confused when navigating between the views of the models that were related (I had relationships of up to 3 levels). Now I have a useless license.

Or you can just use it for something else in the future. (or used the nova-breadcrumbs package above)

**Comment by norotaro** [comment]
> > I paid Nova's license to develop a small project, I ended up migrating to [OctoberCMS](https://octobercms.com/) because the user was confused when navigating between the views of the models that were related (I had relationships of up to 3 levels). Now I have a useless license.
> 
> Or you can just use it for something else in the future. (or used the nova-breadcrumbs package above)

At the time I was developing I looked a lot for a package with Breadcrums but I did not find.

**Comment by jbrooksuk** [comment]
This is something we’re now actively exploring.

**Comment by hackerboydotcom** [comment]
+1 for this, I'm building a logistic management system for my company and all employees yelling about the UX

**Comment by genesiscz** [comment]
Is this getting any update?

**Comment by IVNtech** [comment]
got an errror with breadcrums package from 

  Problem 1                                                                                                                                            
    - chris-ware/nova-breadcrumbs 1.3.7 requires laravel/nova 3.7.* -> no matching package found.                                                      
    - chris-ware/nova-breadcrumbs 1.3.6 requires laravel/nova 3.6.* -> no matching package found.                                                      
    - chris-ware/nova-breadcrumbs 1.3.5 requires laravel/nova 3.5.* -> no matching package found.                                                      
    - chris-ware/nova-breadcrumbs 1.3.4 requires laravel/nova 3.4.* -> no matching package found.                                                      
    - chris-ware/nova-breadcrumbs 1.3.3 requires laravel/nova 3.3.* -> no matching package found.                                                      
    - chris-ware/nova-breadcrumbs 1.3.2 requires laravel/nova 3.2.* -> no matching package found.                                                      
    - chris-ware/nova-breadcrumbs 1.3.1 requires laravel/nova 3.1.* -> no matching package found.                                                      
    - chris-ware/nova-breadcrumbs 1.3 requires laravel/nova 3.0.* -> no matching package found.                                                        
    - Installation request for chris-ware/nova-breadcrumbs ^1.3 -> satisfiable by chris-ware/nova-breadcrumbs[1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7].                                                                                                                                          
                                                                                                                                                       
Potential causes:                                                                                                                                      
 - A typo in the package name                                                                                                                          
 - The package is not available in a stable-enough version according to your minimum-stability setting                                                 
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.                                                                  
 - It's a private package and you forgot to add a custom repository to find it                       

Some idea to fix it?

**Comment by stephan-v** [comment]
I'm pretty shocked to read what has been said in this issue by developers of Laravel Nova. A large amount of the community is asking for this feature and you tell people to use the back button on the browser and you deem it unnecessary.

> Hit the back button in your browser.

It's clear you absolutely don't care about what your end users have to say as long as they continue paying for mediocre software.

**Comment by Carlo-DE** [comment]
2021 and still hoping for some UX updates, back buttons to parent resources, breadcrumbs, ability to view relationships on edit.. basic functionality for a content management system.

**Comment by lucasromanojf** [comment]
> 2021 and still hoping for some UX updates, back buttons to parent resources, breadcrumbs, ability to view relationships on edit.. basic functionality for a content management system.

Stopped using Nova for any new projects. Gave up. It's a good idea, but badly executed, unfortunately.

**Comment by tysonlt** [comment]
@lucasromanojf what did you migrate to?

**Comment by lucasromanojf** [comment]
> @lucasromanojf what did you migrate to?

Currently we are building using Inertia and Vuejs with quasar framework and we are being happy

**Comment by dillingham** [comment]
@lucasromanojf sounds like you were trying to use Nova to build a custom interface if ultimately where you ended up was building a custom interface. Not fair to say its badly executed if its not used as intended.. an admin panel.

**Comment by lucasromanojf** [comment]
> @lucasromanojf sounds like you were trying to use Nova to build a custom interface if ultimately where you ended up was building a custom interface. Not fair to say its badly executed if its not used as intended.. an admin panel.

The stack I mentioned is being used for building admin panels with mostly cruds, nothing too different of what Nova is intended. Breadcrumbs are basic functionality for admin panels, I think that lots of people agree with me as you can see in this issue history and comments. If hit the back button on the browser is the best solution, why Vapor interface has breadcrumbs then?

**Comment by hackerboydotcom** [comment]
I can't understand how the f*k can @taylorotwell  told us to just "hit the back button" and the breadcrumb isn't an important thing.
It feels like when you're in a restaurant and asks for a tissue, then the waiter said: "just wipe with your shirt, it will work too".

**Comment by genesiscz** [comment]
> @lucasromanojf sounds like you were trying to use Nova to build a custom interface if ultimately where you ended up was building a custom interface. Not fair to say its badly executed if its not used as intended.. an admin panel.

The things he says are pretty essential for such an admin panel and I feel they should be included in the package
