### ISSUE TITLE
Auto refresh the CSRF Token after expired of the page

### ISSUE THREAD

**Issue by vFire** [laravel/nova-issues#2040]
Think about it, after you input a lot of text, graphic ... when you push submit, the page is expired prompted, you have to refesh the whole page but lost all of these changes, it's not a big problem but obviously not User Friendly, is it possible to auto set the CSRF Token in meta tags once the expired session is detected. No need to manually refresh the whole page.

**Comment by jbrooksuk** [comment]
This isn't something we'll likely bake into Nova, but you could look at a package such as [Caffeine for Laravel](https://genealabs.com/docs/laravel-caffeine/).
