### ISSUE TITLE
Metrics values are sent rounded with zero precision to front-end

### ISSUE THREAD

**Issue by zedix** [laravel/nova-issues#2042]
- Laravel Version: 6.1.0
- Nova Version: 2.4.0
- PHP Version: 7.3

### Description

Today, metrics values are sent by `nova-api/metrics` api to front-end rounded with _zero_ precision.

### Steps To Reproduce

Create a Value metric card displaying an average value.

```php
<?php

namespace App\Nova\Metrics;

use Illuminate\Http\Request;
use Laravel\Nova\Metrics\Value;
use App\SomeModel;

class AverageNights extends Value
{
    /**
     * Calculate the value of the metric.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return mixed
     */
    public function calculate(Request $request)
    {
        return $this
            ->average($request, SomeModel::class, 'nights')
            ->format([ 'mantissa' => 2 ]);
    }
}
```

![image](https://user-images.githubusercontent.com/27975/66769887-8a1b1500-eeb6-11e9-91ae-48488d33195d.png)

**Actual result**: display "2"

**Expected result:** display "2.62"

In order to achieve the simple result above, we currently must override the `Laravel\Nova\Metrics\Value` class like this:

```php
<?php

namespace App\Nova\Metrics;

use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\Builder;
use Laravel\Nova\Metrics\Value as NovaValue;

class Value extends NovaValue
{
   // This is the protected method to add to allow customization
   // of the `round` precision used in the `aggregate` method
    protected function getRoundPrecision()
    {
        return 2;
    }

    /**
     * Return a value result showing the growth of a model over a given time frame.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Illuminate\Database\Eloquent\Builder|string  $model
     * @param  string  $function
     * @param  string|null  $column
     * @param  string|null  $dateColumn
     * @return \Laravel\Nova\Metrics\ValueResult
     */
    protected function aggregate($request, $model, $function, $column = null, $dateColumn = null)
    {
        $query = $model instanceof Builder ? $model : (new $model)->newQuery();

        $column = $column ?? $query->getModel()->getQualifiedKeyName();

        $previousValue = round(with(clone $query)->whereBetween(
            $dateColumn ?? $query->getModel()->getCreatedAtColumn(), $this->previousRange($request->range)
        )->{$function}($column), $this->getRoundPrecision());

        return $this->result(
            round(with(clone $query)->whereBetween(
                $dateColumn ?? $query->getModel()->getCreatedAtColumn(), $this->currentRange($request->range)
            )->{$function}($column), $this->getRoundPrecision())
        )->previous($previousValue);
    }
```

This would be a great fix/addition.

**Comment by mrpritchett** [comment]
Was this actually fixed or just closed?

**Comment by zedix** [comment]
@mrpritchett It was actually fixed in Nova [v2.8.0](https://nova.laravel.com/releases/2.8.0).

You can now change the `precision` property like:

```php
use Laravel\Nova\Metrics\Value;

class AverageNights extends Value
{
    /**
     * The value's precision when rounding.
     *
     * @var int
     */
    public $precision = 2;
}
```

**Comment by mrpritchett** [comment]
Does this work for Trend metrics?

**Comment by gpressutto5** [comment]
@mrpritchett I guess you already figured that out, but for anyone coming into this issue now, it doesn't work for trends.

**Comment by jonasbrenig** [comment]
> that out, but for anyo

Well since you fixed it, it does now :-)

https://github.com/laravel/nova/pull/891

**Comment by mrpritchett** [comment]
Thanks, y'all!

**Comment by rderks88** [comment]
> ```
> public $precision = 2;
> ```

Since I'm guessing Nova 4.0 this value changed its name to "roundingPrecision"

> ```
> public $roundingPrecision = 2;
> ```

**Comment by schwindy** [comment]
> @mrpritchett I guess you already figured that out, but for anyone coming into this issue now, it doesn't work for trends.

Tested today on latest Nova - it does now work for Trend Metrics :monkey:

This issue is the only place I found to use $roundingPrecision - thanks @rderks88
