### ISSUE TITLE
Badge Field

### ISSUE THREAD

**Issue by wefixit-tech** [laravel/nova-issues#2045]
Hi i want to ask if anyone can help me on how to declare a custom classes

Badge::make('Status')->types([
    'draft' => 'custom classes', // Classes can be a string <------
    'published' => ['custom', 'class',] // Classes can also be an array
]);

i already try differents methods by every time i get black text, i would appriciated so much.

For extra info i have nova 2.5.0 and laravel 6.3 on windows.

![We Fix It](https://user-images.githubusercontent.com/3880643/66885170-100f8c80-ef99-11e9-80a9-cca1ddb32be4.png)

Thank you!

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).

**Comment by wefixit-tech** [comment]
This issue was solve in laravel nova 2.6 but in version 3.0 it has return, can anyone else has this issue?
