### ISSUE TITLE
Error in declaration of BelongsTo::displayUsing - missing callable type

### ISSUE THREAD

**Issue by q30t** [laravel/nova-issues#2046]
- Laravel Version: 5.8.35
- Nova Version: 2.5.0
- PHP Version: 7.2

### Description

Declaration of Laravel\Nova\Fields\BelongsTo::displayUsing($callback) should be compatible with Laravel\Nova\Fields\Field::displayUsing(callable $displayCallback)

**Comment by halah-m** [comment]
I have the same issue since I updated to nova 2.5.0

Laravel Version: 6.2
Nova Version: 2.5.0
PHP Version: 7.3.9

**Comment by alexandrecruz** [comment]
Same here:

Laravel Version: 5.8.35
Nova Version: 2.5.0
PHP Version: 7.1.26

**Comment by huoding** [comment]
same

**Comment by msassa** [comment]
Same

**Comment by halah-m** [comment]
@davidhemphill can I ask why did you closed it ?

**Comment by codetay** [comment]
Yeah i got same issue, so i must rollback to 2.4.0 then the problem gone. But what's the problem ?

**Comment by q30t** [comment]
If you want to temp fix it, just add the type **callable** to the function **displayUsing** in _your_app\vendor\laravel\nova\src\Fields\BelongsTo.php_ 

```php
public function displayUsing(callable $callback)
{
    return $this->display($callback);
}
```

**Comment by Krato** [comment]
> @davidhemphill can I ask why did you closed it ? and how can we solve this issue

Is merged. We just need to wait the next release.

**Comment by davidhemphill** [comment]
@halah-m Because it's fixed:
<img width="533" alt="image" src="https://user-images.githubusercontent.com/58970/67021101-c754f200-f0c4-11e9-8301-2d1bd5621381.png">
