### ISSUE TITLE
missing translation keys

### ISSUE THREAD

**Issue by FaridAghili** [laravel/nova-issues#2047]
- Laravel Version: 6.2.0
- Nova Version: 2.5
- PHP Version: 7.3

translation for `Exception` and `Finished` are missing.
Both of them are used inside Action events view.

**Comment by davidhemphill** [comment]
Both the `Exception` and `Finished` keys are available to be translated. Simply place the translations in the desired language file and they will be displayed correctly.

**Comment by m-lotze** [comment]
@davidhemphill 

the keys are missing from en.json, as do other translations like:

There was a problem executing the action.
There was a problem submitting the form.
This resource no longer exists

nova should provide a complete translation file with all used strings in __(...). 

third party packages like https://github.com/franzdumfart/laravel-nova-localizations probably rely on en.json for other translations and dont search the nova files like i just did.
