### ISSUE TITLE
Nova Route 404

### ISSUE THREAD

**Issue by bradders** [laravel/nova-issues#205]
I've installed Nova, and when I view a resource index (the Users one, for example) the list never populates.

Dev console shows me a 404 on the following route:

`https://project.localhost/nova-api/users?search=&filters=&orderBy=&orderByDirection=desc&perPage=25&trashed=&page=1&viaResource=&viaResourceId=&viaRelationship=&relationshipType=`

That error is fired from `https://project.localhost/nova-assets/vendor.js?id=b7f746c0bceb492a9264`

When I list routes using `php artisan route:list` I see a bunch of nova routes. Any clues?

**Comment by bradders** [comment]
Turns out this 404 was because I had some greedy route naming in my app:

`Route::get("{country_url}/{region_url}", ["uses" => "RegionController@view", "as" => "regions.view"]);`

**Comment by pnj131** [comment]
I solved out this issue easily,,
add on app/config file..
 App\Providers\NovaServiceProvider::class,

**Comment by tripex** [comment]
What is the solution to this wildcard class issues? As i'm experiencing this myself.
