### ISSUE TITLE
Float values in partition metrics have no precision hence really long values

### ISSUE THREAD

**Issue by introwit** [laravel/nova-issues#2050]
- Laravel Version: 6.1
- Nova Version: 2.5.0
- PHP Version: 7.3

### Description

If the partition metrics have values of float type i.e. with a decimal, there is no way to set a precision hence they end up being really long making the UI and UX a bit odd. Screenshot for reference:

![IMG_20191016_183808](https://user-images.githubusercontent.com/11228182/66922151-232b6680-f044-11e9-9cdf-406b45767c19.jpg)

### Steps To Reproduce

- Create a partition metric.
- Pass values with a decimal.

If there can be a way to specify the precision, it would be helpful :) Thank you ♥️

**Comment by jbrooksuk** [comment]
This should be fixed.

**Comment by tott** [comment]
Hi, I'm still running into this issue with Nova 3.22.0 - any pointers as how to fix this?

**Comment by introwit** [comment]
@tott you can override the rounding precision and mode properties, just [sent a PR](https://github.com/laravel/nova-docs/pull/312) to include it in the nova docs.
