### ISSUE TITLE
Profile menu missing after upgrading to 2.5.0

### ISSUE THREAD

**Issue by lesaff** [laravel/nova-issues#2054]
- Laravel Version: 5.8.35
- Nova Version: 2.5.0
- PHP Version: 7.3
- Database Driver and Version: MariaDB
- Operating System and Version: Latest Homestead (Ubuntu)
- Browser type and version: Chrome 77.x

### Description

I noticed that the profile gravatar menu on the top right is missing after upgrading to 2.5.0 (from 2.2.0)

### Steps To Reproduce

Upgrade Nova to 2.5.0

**Comment by davidhemphill** [comment]
Sounds like you need to republish Nova's assets. The gravatars seem to be loading on all of the installs I manage.

**Comment by bolechen** [comment]
+1 for this, republish asserts not work

**Comment by lesaff** [comment]
Update:
I managed to get my profile menu back by:
- deleting `vendor` folder and `composer.lock` file
- run `composer install`
- run `php artisan nova:publish`
- run `php artisan optimize`

**Comment by bolechen** [comment]
If used the  `stephenlake/nova-fixed-bars` package, may be see this issue below
https://github.com/stephenlake/nova-snowball/issues/3

**Comment by iMuMz** [comment]
I managed to get the profile menu to appear again by removing :  

`slot-scope="{toggle}" :handle-click="toggle"`

from 

`<dropdown-trigger class="h-9 flex items-center" slot-scope="{toggle}" :handle-click="toggle">`

in views/vendor/nova/partials/user.blade.php
