### ISSUE TITLE
When placing a DateTime field in an action, the DateTime popup fails to close

### ISSUE THREAD

**Issue by pidgebob** [laravel/nova-issues#2055]
- Laravel Version: 5.8.35
- Nova Version: 2.4.0
- PHP Version: 7.3
- Browser type and version: Chrome v77

### Description

When there is a DateTime field in an action window, after running the action, the DateTime popup sticks around and fails to close.

![Screenshot 2019-10-17 at 08 35 41](https://user-images.githubusercontent.com/14075703/66987857-6a077380-f0b9-11e9-972c-a50faa1ac71e.png)

### Steps To Reproduce

1. Create an action
2. Add a DateTime field to the action
```
use Laravel\Nova\Fields\DateTime;

/**
     * Get the fields available on the action.
     *
     * @return array
     */
    public function fields()
    {
        return [
            DateTime::make('Start Date/Time', 'start_date')
                ->hideFromIndex()
                ->nullable(),

            DateTime::make('End Date/Time', 'end_date')
                ->hideFromIndex()
                ->nullable(),
        ];
    }
```
3. Run action

**Comment by jbrooksuk** [comment]
Can you update to v2.5.0 please.
