### ISSUE TITLE
Metrics only work with DATETIME columns

### ISSUE THREAD

**Issue by sgittel** [laravel/nova-issues#2056]
- Laravel Version: 5.8.35
- Nova Version: 2.4.0
- PHP Version: 7.2
- Database Driver and Version: MariaDB 10.1

### Description
Metrics use Carbon objects to query a date/time range. The generated query always uses DATETIME format. The query will be something like this:
`select ... where created_at between '2019-10-16 09:58:38' and '2019-10-17 09:58:38'`

If the database column uses unix timestamps instead, no results will be returned because no DATETIME will ever match a unix timestamp.

A solution would be to respect the model's $dateFormat variable, if given (which is 'U' in our case). Since that is used for writing to date/time columns, the format when querying those columns should be the same anyways. Calling `format($model->getDateFormat())` on the Carbon instances passed to the Eloquent `whereBetween()` method solves the issue.

### Steps To Reproduce

Have a database table with a date column containing unix timestamps, create a value metric and call an arbitrary aggregate method using that date column for the range. Our legacy database uses int(10) where storing unix timestamps.

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
