### ISSUE TITLE
Fields within actions don't respect validation rules

### ISSUE THREAD

**Issue by eithed** [laravel/nova-issues#2057]
- Laravel Version: 5.8.30
- Nova Version: 2.0.9
- PHP Version: 7.2

### Description

On https://nova.laravel.com/docs/2.0/resources/fields.html#customization documentation states that Fields support validation. On https://nova.laravel.com/docs/2.0/actions/defining-actions.html#action-fields Fields are the same models - as such, one assumes that validation is supported in this case as well. Trying to set any rules will not reflect in the UI, nor any validation will be performed when handling given action.

As such validation in this code:

```
public function fields()
{
        return [
            Text::make('Reference')->rules('required'),
            Select::make('Status')->options(\App\Invoice::getAvailableStatuses())->rules('required'),
            Select::make('Type')->options(\App\Invoice::getAvailableTypes())->rules('required'),
            DateTime::make('Invoice Date', 'effective_date')->format('DD/MM/YY')
        ];
}
```
will be respected when used in Resource, but not in Action.

This is especially puzzling, when, trying to apply a workaround (I was intending to use `Action::message` to handle this) I do encounter correct behaviour:

```
public function handle(ActionFields $fields, Collection $models)
{
        $request = request();

        $rules = [];
        foreach($this->fields() as $field) {
            $rules[$field->attribute] = $field->rules;
        }

        $request->validate($rules);
```

is handled correctly:
![Screenshot 2019-10-17 at 12 23 29](https://user-images.githubusercontent.com/795678/67004782-f6755e80-f0d8-11e9-80fe-2242cc2f2695.png)

**Comment by davidhemphill** [comment]
I'm not able to reproduce your issue. Here's an example of an Action with fields and validation working correctly:

```php
public function actions(Request $request)
{
    return [
        (new class extends Action {
            public $name = 'Toggle Activation';

            public function handle($fields, $models)
            {
                // ...
                return Action::message("The users's activation state was toggled!");
            }

            public function fields()
            {
                return [
                    (new DateTime("Invited At"))->rules('required')
                ];
            }
        }),
    ];
}
```

Please try this and if you can find a reproducible example of action fields not validating, please post here or post a new issue.  Thanks!

**Comment by ThaDaVos** [comment]
Hey,

Sorry for commenting on an old issue, but this seems to be the only issue I could find about this.

For me I cannot get it to work, it always seems to just post to the Action's Controller instead of handling it inside the Action's component and prevent the sent, I've tried `->required()`, `->required(true)` and `->rules(`required`)` and they all don't work

**Comment by ThaDaVos** [comment]
Nvm... your example works, but when I use the following action it doesn't
https://github.com/ThaDaVos/Laravel-Nova-Excel/blob/2.0/src/Actions/ImportExcel.php

**Comment by ThaDaVos** [comment]
Nvm... my comments - the issue is inside that package... they apparently override the index-toolbar and just without validating call the API

**Comment by bkuhl** [comment]
`->rules('required')` works as expected for a `Select` field for me as of v4, however `->required()` only adds the `*` next to the field, it does not actually require it.
