### ISSUE TITLE
Feature Request: Display fields on Action Log

### ISSUE THREAD

**Issue by noahlocke** [laravel/nova-issues#206]
First off, thank you for the Actions Log, so incredibly useful and awesome.

When performing certain Actions, I'd like to have the option to pass a 'Comment' field along with the action to be displayed out with the log. Since Nova is already serializing `$this->fields()` on the `action_events` table, it's super easy to throw in a 'Comment' field when applicable and, if present, onto the Action Log index/details view. 

I modified the current `ActionResource.php` to include this field, but would like a more reusable method if anyone has a better suggestion (or better yet, add this into Nova core :)).

```
protected function commentField() {
  return Text::make('Comment', function() {
    if(! $this->fields) {
      return '—';
    }
    $arr = unserialize($this->fields);
    if(array_filter($arr)) {
      if(array_key_exists('comment',$arr)) {
        $comment = $arr['comment'];
        if(strlen($comment) > 24) {
          return $result = mb_substr($comment, 0, 25).'...';
        } else {
          return $comment;
        }
      }     
    } else {
      return '—';
    }               
  });
}

**Comment by noahlocke** [comment]
<img width="1271" alt="screen shot 2018-08-25 at 9 10 08 pm" src="https://user-images.githubusercontent.com/6596677/44624146-5f818d80-a8ab-11e8-95df-75b41cd64c3a.png">

**Comment by noahlocke** [comment]
@ceejayoz I just now realized that you can place your own `ActionResource.php` in your app/Nova folder and override the standard one. :)

**Comment by davidhemphill** [comment]
The ActionResource is now customizable so should provide everything you need.
