### ISSUE TITLE
Laravel nova cannot find css file for generated theme

### ISSUE THREAD

**Issue by matovu-ronald** [laravel/nova-issues#2061]
- Laravel Version: 6.2
- Nova Version: 2.5
- PHP Version: 7.2
- Database Driver and Version: mysql
- Operating System and Version: ubuntu 19.04
- Browser type and version: chrome
- Reproduction Repository: https://github.com/matovu-ronald/Understanding-Laravel-Nova-Administration-Panel.git

### Description

I have generated nova themes twice but could not see any change and an error is thrown in console browser 
***GET http://127.0.0.1:8000/hackshadetechs/matovu-ronald-theme/theme.css net::ERR_ABORTED 404 (Not Found)***

### Steps To Reproduce

- Install laravel nova.
- Run php artisan nova:theme {package name}.

**Comment by jbrooksuk** [comment]
I'm not able to replicate this:

![image](https://user-images.githubusercontent.com/246103/67078130-9807b900-f188-11e9-870b-19bf1b04845f.png)

Make sure that you register the service provider that is generated by the `nova:theme` command. https://nova.laravel.com/docs/2.0/customization/themes.html#overview

**Comment by matovu-ronald** [comment]
Hello, sorry that I am still on this issue but unless when am not doing something right but I have run about 3 new projects of laravel nova but theme.css cannot be found, 
registetering ThemeServiceProvider manually as below but no success in loading the theme,
This used to very basic loading the theme its failed must be something not right going on
` Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,

        /*
         * Package Service Providers...
         */
        \Nilesource\Spena\ThemeServiceProvider::class,

        /*
         * Application Service Providers...
         */
        App\Providers\AppServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        // App\Providers\BroadcastServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\NovaServiceProvider::class,
        App\Providers\RouteServiceProvider::class,`

**Comment by matovu-ronald** [comment]
I managed to get it to work thanks was missing out this
php artisan vendor:publish
