### ISSUE TITLE
authorizedToAttach function?

### ISSUE THREAD

**Issue by anditsung** [laravel/nova-issues#2062]
```
public function authorizedToAttach(NovaRequest $request, $model)
    {
        return false;
    }
```

this will not disable attach button but disable edit button on the attach index

but when try to attach an item cannot see any selection to attach

**Comment by jbrooksuk** [comment]
I believe this is because you may be able to attach 1 or more of `x` resources, which means that there isn't a simple way of saying "can a user attach anything". I believe though you can use policies to hide this?

**Comment by jbrooksuk** [comment]
I've just tested this and can confirm that you need to use a policy with `attachAnyUser` (or whatever model you're attaching).
