### ISSUE TITLE
Searching for numeric values >2147483647 throws exception with PostgreSQL

### ISSUE THREAD

**Issue by chescos** [laravel/nova-issues#2063]
- Laravel Version: 5.8
- Nova Version: 2.5.0
- PHP Version: 7.3

### Description

[This commit](https://github.com/laravel/nova/commit/e7e13bc287b5170f9d14aa939f2b84f774295d72) introduces a bug that causes an SQL exception to be thrown when using PostgreSQL. This issue has been fixed before (#680) but it's now back.

The issue is that `PHP_INT_MAX` is now being used to determine the maximum integer that we can use to search the primary key of a table. The value of `PHP_INT_MAX` depends on whether a 64-bit or 32-bit system is being used. On 64-bit systems, `PHP_INT_MAX` will have the value `9223372036854775807`. But default migrations that were created before L5.8 used `increments()` for the primary key and this method uses the [integer data type](https://www.postgresql.org/docs/12/datatype-numeric.html) in PostgreSQL. The integer data type can only store numbers up to `2147483647` and when you search a column of this type for a larger number, an SQL error is thrown.

Effectively, when you search for a number that is `2147483648` or higher using a 64-bit system on a table which was created from a migration prior to L5.8, an SQL error will be thrown.

### Steps To Reproduce

1. Use a 64-bit system
2. Use PostgreSQL as database driver
3. Create a `users` table which uses `increments()` instead of `bigIncrements()` for the `id` column
4. Create a `User` resource
5. Go to the URL `your.app/nova/resources/users` in your browser and type `2147483648` into the search field
6. An exception will be thrown

**Comment by jbrooksuk** [comment]
I don't see a win-win here. If we have a larger number, then it's not right, if we have a lower number, then people who making post 5.8 migrations will not be able to search for their higher records either.

Any suggestions?

**Comment by chescos** [comment]
@jbrooksuk I'd argue that the number of people who have 5.7 migrations is far higher than the number of people with >5.7 migrations who have tables with over 2 billion rows. I'm sure that there are some projects that have over 2 billion rows in a single table but I'm pretty certain 99.9% of projects don't.
