### ISSUE TITLE
Trix not displayed on relationship index

### ISSUE THREAD

**Issue by stancl** [laravel/nova-issues#2064]
- Laravel Version: 6.2.0
- Nova Version: 2.5.0
- PHP Version: 7.2
- Database Driver and Version: sqlite
- Operating System and Version: Ubuntu 19.04
- Browser type and version: Chrome

### Description

A `Trix` pivot field doesn't render in the relationship index (= resource detail).

Order:
```php
BelongsToMany::make('Statuses', 'statuses', Status::class)->fields(function () {
    return [
        Trix::make('Message'),
    ];
}),
```

Status:
```php
BelongsToMany::make('Orders', 'orders', Order::class)->fields(function () {
    return [
        Trix::make('Message'),
    ];
}),
```

Result:
![Screenshot from 2019-10-18 19-26-14](https://user-images.githubusercontent.com/33033094/67114884-2efe6080-f1dd-11e9-957a-cc33225d5e8a.png)

Changing `Trix` to `Text` works:
![Screenshot from 2019-10-18 19-25-57](https://user-images.githubusercontent.com/33033094/67114894-358cd800-f1dd-11e9-8c56-7463252d061f.png)

**Comment by davidhemphill** [comment]
Trix fields are set to not show on any index view by design.

**Comment by stancl** [comment]
@davidhemphill Why does the column name show up then?

**Comment by johnpuddephatt** [comment]
@ikramooe and anyone else, you can just output the content with a Text field that is set to only show on the index:

```
Trix::make('Content'),
Text::make('Content')->onlyOnIndex()->asHtml(),
```
