### ISSUE TITLE
Display only connected users resources

### ISSUE THREAD

**Issue by christophe-44-27** [laravel/nova-issues#2065]
Hi,

I've a question about filtering by default the results from a query. I don't understand the mechanism. Well, here my question and the situation.

Some teachers are adding online courses onto my platform. I would like to add them into my nova dashboard, but i don't want that they see some others teacher's courses. I just want to display (except for the admin role) resources owned by the connected user.

I don't see how i can do this :/ . I've search with the filters, dynamic filters, and also lens, but i think that actually, Nova can't allow this behavior, am i right ?

Regards,
Christophe

**Comment by davidhemphill** [comment]
You're looking for [Laravel's Global Query Scopes](https://laravel.com/docs/6.x/eloquent#global-scopes).

**Comment by christophe-44-27** [comment]
Hi, yes great clue ! But when i use laravel global query scope the entire model use it and apply the restriction.

Well, this is my situation. I have a frontend for guest, members, etc. It display collections of online courses. With that, i have a backend where my teachers can add, edit, well, manage their courses. So in this backend, managed by Nova, i want that a connected professor see his courses. (And as administrator, i want to see everything).

But i can't add scope, on nova middleware, or routes, because we can't customize them, right ? 

With theses informations, could you tell me if Nova could be a good solution for my needs or i have to do this on my own ?
