### ISSUE TITLE
Actions visibility is not working

### ISSUE THREAD

**Issue by chinleung** [laravel/nova-issues#2067]
- Laravel Version: 5.8.35
- Nova Version: 2.5.0
- PHP Version: 7.3
- Database Driver and Version: MySQL 5.7
- Operating System and Version: MacOS
- Browser type and version: Google Chrome Version 77.0.3865.120 (Official Build) (64-bit)

### Description

Registering an action with `onlyOnDetail` but it is still rendered in the index. I have provided a screenshot where I can see that the `showOnIndex` and `showOnTableRow` is set to `false`, yet it is still showing up in the list of actions.

### Steps To Reproduce

``` php
public function actions(Request $request)
{
    return [
        (new RefundInvoice)->onlyOnDetail(),
    ];
}
```

### Screenshot

![image](https://user-images.githubusercontent.com/19669331/67152674-9a156900-f2a9-11e9-8187-e0b33ac83013.png)

**Comment by jbrooksuk** [comment]
I was able to replicate this, but after re-publishing the Nova assets, the issue was fine.

**Comment by chinleung** [comment]
> I was able to replicate this, but after re-publishing the Nova assets, the issue was fixed.

Thanks it worked. For those who are wondering, you can republish the assets with:

```
php artisan nova:publish
```
