### ISSUE TITLE
Tables with non-integer primary keys action events error

### ISSUE THREAD

**Issue by emperorjm** [laravel/nova-issues#2069]
I have quite a few tables that do not use an **Integer** or **BigInter** id as primary key and use a Varchar field. This seems to be problematic to Nova's action_events table that tracks changes within models as the **actionable_id**, **target_id** and **model_id** columns are Integers as opposed to a String which could account for any type of Primary key.

The following error was thrown when trying to update a record in my "countries" table:

SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'ZW' for column 'actionable_id' at row 1 (SQL: insert into `action_events` (`batch_id`, `user_id`, `name`, `actionable_type`, `actionable_id`, `target_type`, `target_id`, `model_type`, `model_id`, `fields`, `original`, `changes`, `status`, `exception`, `updated_at`, `created_at`) values (8ef0523a-0b1b-4eb8-b96f-7aa866ce451f, 1, Update, App\Models\Country, ZW, App\Models\Country, ZW, App\Models\Country, ZW, , {"status_code":"active"}, {"status_code":"disabled"}, finished, , 2019-10-21 03:23:48, 2019-10-21 03:23:48))

**Comment by jbrooksuk** [comment]
You need to customise the `action_events` table migration to work with your table structure.
