### ISSUE TITLE
Publish login view

### ISSUE THREAD

**Issue by sicbe** [laravel/nova-issues#2072]
I am using nova with our school database. The users are able to login with their unique School-ID or Email address using a custom UserProvider / Guard.

The problem is that the Nova login view has the email field set at "email" type. I also don't need the "remember me" or "password reset" buttons so I removed them. I changed the HTML for the Login view in the nova folder, no problem. But every time there is an update I have to make the same changes. 

Would it not be better to also publish the login.blade to /resources/views/vendor/nova along with the other templates? The login screen seems important for a lot of businesses to customise...

**Comment by jbrooksuk** [comment]
You can create a `/resources/views/vendor/nova/auth/login.blade.php` view and customise it.

**Comment by stonkeep** [comment]
How I do in Laravel Nova 4?

**Comment by scramatte** [comment]
Hi,

Same problem here

**Comment by afshiney** [comment]
It seems like after Nova 4 blades has moved to vue files.
Appreciate if anyone can help about how vue files can be registered and customized now.

**Comment by chrillep** [comment]
https://github.com/laravel/nova-issues/issues/3952
