### ISSUE TITLE
File Field should be async

### ISSUE THREAD

**Issue by vayurobins** [laravel/nova-issues#2075]
Hi.
It would be really coherent with modern web apps and Nova if the File Field was loading files async. Could this maybe be integrated into future versions?
Thanks a great platform!

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
