### ISSUE TITLE
Date field - flatpickr.js: Show weeks functionality

### ISSUE THREAD

**Issue by PatricNox** [laravel/nova-issues#2076]
In flatpickr you can enable to show week number at the left side of the datepicker.
(https://flatpickr.js.org/examples/#display-week-numbers) 

Today this doesn't seem to be supported in Nova, `nova/src/Fields/Date.php`. 

Is this possible without a method or is it time to open a feature request?

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by sedlatschek** [comment]
I'm also interested in this feature.

In the meantime I'm going to use the default config to achieve week numbers (applies globally).
```js
window.flatpickr.defaultConfig.weekNumbers = true
```
