### ISSUE TITLE
sort resources in sidebar by label or property

### ISSUE THREAD

**Issue by m-lotze** [laravel/nova-issues#2078]
Right now the resources in the sidebar are sorted by class name and third party package resources are appended unsorted. please change the function groupedResources in Nova.php like this:

```
     /**
     * Get the grouped resources available for the given request.
     *
     * @param Request $request
     *
     * @return array
     */
    public static function groupedResources(Request $request)
    {
        return collect(static::availableResources($request))
            ->sortBy(function ($item) {
                return $item::$sidebarOrder ?? $item::label();
            })
            ->groupBy(function ($item, $key) {
                return $item::group();
            })->sortKeys()->all();
    }
```

This way the sidebar resources are sorted alphabetically in any language by default or by a custom order if you set a static property `$sidebarOrder` on all your resources.

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by h-zone** [comment]
Why so long time to implement 10 lines of code ?
im crying

**Comment by jbrooksuk** [comment]
You're welcome to submit a PR with these changes :)

**Comment by h-zone** [comment]
wanna from the box ;-)
optional/turnable on/off
