### ISSUE TITLE
Redirect for nova-api routes

### ISSUE THREAD

**Issue by kotfire** [laravel/nova-issues#208]
Version: v1.0.6

I have a middleware that redirects to another page when certain conditions are met. This works fine when loading the page via http, but when clicking on a link in the sidebar the vue-router does not follow the redirect response.

**Comment by tillkruss** [comment]
It's SPA, so your middleware will only be called once when rendering Nova.

**Comment by kotfire** [comment]
No, the middleware is called. I can see the 302 response to the request in the inspector, but as I said Nova doesn't follow it.

**Comment by GuidoHendriks** [comment]
Redirecting Nova API calls might not be the way to redirect the users, I guess?

**Comment by kotfire** [comment]
I think it should. In fact there is a way to tell nova to redirect when an action is completed and I assume it's using the nova api.

I'm open to a different approach to achieve it of someone has one.

**Comment by GuidoHendriks** [comment]
If you want to redirect from an `Action`, you call the redirect method. What that does is a returning an array with the redirection url, like this:

    ['redirect' => 'https://example.com']

Not sure if this is globally applicable, but it makes way more sense than redirecting the user to whatever the API calls redirected to.

**Comment by kotfire** [comment]
No, it's not. That's why I've created this issue. I don't mind using a custom response like the actions one, but there should be a way to do a redirect.

**Comment by dillingham** [comment]
There is also js redirecting if nova tries to perform routing when session times out

**Comment by dillingham** [comment]
Maybe some logic could be included to allow api responses to dictate redirect

Would satisfy this issue https://github.com/laravel/nova-issues/issues/538

**Comment by davidhemphill** [comment]
Sorry all, we're not gonna add a way to redirect our own api calls. If you can post a use case that makes sense, I might open this up again, but closing for now

**Comment by edanisko** [comment]
This works for me through an amazon Application Load Balancer.
Need Trusted Proxy setup properly to determine client IPs.

in /etc/nginx/sites-enabled/yoursite.conf
...
server_name yoursite.com
    if ($http_x_forwarded_proto = 'http') {
      return 301 https://$http_host$request_uri;
    }
...

The only way I have been able to force a laravel site to consistently secure is at the web server layer.

gl
-Ed

**Comment by ristlin** [comment]
> Sorry all, we're not gonna add a way to redirect our own api calls. If you can post a use case that makes sense, I might open this up again, but closing for now

I've run into a potential use case:

I've created an Action on Nova that returns a controller action to impersonate the passed through user. Once I've triggered the action, I am logged in as the selected user and run into Nova authentication and reach the 403. In this situation, I'd love a way to redirect and avoid that 403.

**Comment by jolora** [comment]
I have another use case. My nova application requires a connection to an oauth connection to an external service. When the server is not connected I need to redirect the user to the custom tool we have for connecting to the service.

Initially wrote a middleare which works fine on a HTTP request... but I then realised as Nova is an SPA it doesn't usually check this middleware.
