### ISSUE TITLE
Dashboard Metrics disappears when also used in resource detail 

### ISSUE THREAD

**Issue by ahawlitschek** [laravel/nova-issues#2080]
- Laravel Version: 5.8.35
- Nova Version: 2.5.0
- PHP Version: 7.2.12
- Database Driver and Version: postgres
- Operating System and Version: macOS 10.14.5
- Browser type and version: Chrome 77.0.3865.120

### Description
When using a metric on the dashboard and in resource->onlyOnDetail(), the metrics disappears when returning to the dashboard.
A full page reload shows the metrics again.

### Steps To Reproduce

![nova_issue](https://user-images.githubusercontent.com/53199186/67428558-a9185600-f5de-11e9-92cf-584fb83194cd.gif)

**Comment by jbrooksuk** [comment]
I've just tested this with v2.6.1 and am not able to replicate the issue.
