### ISSUE TITLE
The filter menu closes when you press the <button> or <a>

### ISSUE THREAD

**Issue by dddeeemmmooonnn** [laravel/nova-issues#2083]
- Nova Version: 2.4.0

### Description

In Nova 2.4.0 [9094ece commit](https://github.com/laravel/nova/commit/9094ecef4b9bfad4e6582fc105ab089395de3131#diff-2486c9c203e15455b091c3c07b7aea1e) in `nova/resources/js/components/DropdownMenu.vue` added code
```
    mounted() {
        // If we recieve a click event from an anchor or button element, let's make sure
        // and close the dropdown's menu so it doesn't stay visible if we toggle a modal.
        this.$refs.menu.addEventListener('click', event => {
            if (event.target.tagName != 'A' && event.target.tagName != 'BUTTON') return
            Nova.$emit('close-dropdowns')
        })
    },
```
Therefore, when using buttons in custom filter, it closes filter menu.
So you have to use not \<button\> or \<a\> elements in custom filter.

### Steps To Reproduce

Use \<a\> or \<button\> in filter

**Comment by davidhemphill** [comment]
I wasn't able to replicate your issue using a new filter with a button element.
