### ISSUE TITLE
Markdown field, index using Detail/TextField.vue

### ISSUE THREAD

**Issue by JBAHapp** [laravel/nova-issues#2086]
I noticed after trying to display my markdown on the index page, that it's using the component from TextField details. On the same note a field such as Trix doesn't have a index component.

I'm not sure if this is intended, but seeing that Textarea uses TextField index component, I would imagine that both Trix and Markdown should do the same?

`// Markdown Field
Vue.component(
    'index-markdown-field',
    require('./components/Detail/TextField.vue')
)`

Should this be intended however, how would one go by getting Markdown or Trix to display on Index page as a TextField?

**Comment by jbrooksuk** [comment]
Markdown and Trix do not display on the index pages.

**Comment by JBAHapp** [comment]
That I know, but overrideing with showOnIndex() does show for Markdown. Though, it uses the wrong component. It shows using a Detail component for TextFields rather than the Index for TextFields.
