### ISSUE TITLE
Nova Docs - assets

### ISSUE THREAD

**Issue by skoyah** [laravel/nova-issues#2088]
Hi. I'm currently writing a lot of nova assets using the artisan command `php artisan nova:asset`.

I'm not sure that the Nova docs currently have anything regarding this functionality. If  not, would be nice to  have it on the documentation.

**Comment by jbrooksuk** [comment]
You're right, we don't have any docs on this command / feature yet.

**Comment by davidhemphill** [comment]
@skoyah What sort of assets are you creating? Trying to find a good example to use for documentation.

**Comment by skoyah** [comment]
One of my usecases was to be able to use an external API to fetch some user points and update them on the local database.

To do that I intercepted the vue router to check if the user is trying to visit the detail view. If so, then an axios request should be fired to update that user column. 

Like so:

```javascript
Nova.booting((Vue, router, store) => {
  router.beforeEach((to, from, next) => {

    if (to.params.resourceName === 'users' && to.params.resourceId) {
      let user = to.params.resourceId;

      return Nova.request().put(`/nova-vendor/refresh-user-points/${user}`)
        .then(response => next())
        .catch(errors => next())
    }

    next();
  });
});
```

**Comment by skoyah** [comment]
Another example was to override the `custom-detail-header` component to add a back button to lenses.

**Comment by skoyah** [comment]
In the previous example the `previousRoute` is just a global helper I've created to able to have an easy access to the previous route:

```javascript
Nova.app._router.beforeEach((to, from, next) => {
            window.previousRoute = from;
            next();
        });
```

**Comment by skoyah** [comment]
Hope this examples might help you @davidhemphill ! :)
