### ISSUE TITLE
This image could not be found.

### ISSUE THREAD

**Issue by MustafaWIthA** [laravel/nova-issues#209]
This image couldn't be found, The images will not show up and the console shows, no access control allow origin, the image elements shows localhost/storage instead of my valet domain.

my valet domain is this: http://thenova.devs/nova/resources/users/14
`Failed to load http://localhost/storage/YsjCTVgI3Savg6WUYg5Rg50z1xok7r4jK03JLKDZ.jpeg: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://thebackendnova.devs' is therefore not allowed access. The response had HTTP status code 404.`
if i got directly to my actual domain and change the localhost to thenova.devs/storage/... it works

`<a data-v-a7871de4="" href="http://localhost/storage/YsjCTVgI3Savg6WUYg5Rg50z1xok7r4jK03JLKDZ.jpeg" target="_blank" class="text-primary dim">This image</a>`
<img width="1204" alt="screen shot 2018-08-26 at 10 26 24" src="https://user-images.githubusercontent.com/26868012/44625844-b2def480-a91a-11e8-97da-603823341d61.png">
<img width="439" alt="screen shot 2018-08-26 at 10 25 54" src="https://user-images.githubusercontent.com/26868012/44625849-c12d1080-a91a-11e8-9898-c2b7c34752c9.png">

**Comment by liamcottle** [comment]
I think you need to update the `APP_URL` value in your `.env` file.

**Comment by MustafaWIthA** [comment]
it worked thanks

**Comment by atmacoder** [comment]
I have problem with this error, nova not uploading image file...

![default](https://user-images.githubusercontent.com/43233531/45475655-b4dfea80-b745-11e8-966e-fe3d07a35ed1.png)
![default](https://user-images.githubusercontent.com/43233531/45475689-ca551480-b745-11e8-8ee6-c920cae68dcf.png)

**Comment by garrettbland** [comment]
I seemed to resolve this issue (for amazon s3) by following the accepted answer here. 

[https://stackoverflow.com/questions/17533888/s3-access-control-allow-origin-header](https://stackoverflow.com/questions/17533888/s3-access-control-allow-origin-header)

**Comment by tholder** [comment]
Just to help anyone that is having similar problem related to this same error message. I was getting a double URL after upgrading. My DB had absolute URLs but the thumbnail was outputting the APP_URL before the absolute URL. Turns out it was related issue #42 which has subsequently been fixed and I didn't have a ->preview callback. Just needed to change my code to:

```php
            Avatar::make(str_repeat(' ', 8), 'photo_url')
                ->disk('public')
                ->thumbnail(function () {
                    return $this->photo_url;
                })
                ->preview(function () {
                    return $this->photo_url;
                }),
```
