### ISSUE TITLE
No hint path defined for when create custom Tools

### ISSUE THREAD

**Issue by archisova** [laravel/nova-issues#2090]
Error while creating a Nova Tool. All steps were performed according to the instructions.

1. php artisan nova:tool uu/resources-centers
2. Set options on default [yes]
3. Add providers into NovaProviders.
4. Go to browser and refresh page.
5. Sow an error:

`Facade\Ignition\Exceptions\ViewException No hint path defined for [resources-centers]. (View: /var/www/portal.u.university/vendor/laravel/nova/resources/views/layout.blade.php)`

**Comment by archisova** [comment]
I finded a solution, and it helped for me.

**What I did:**
1. composer self-update --snapshot
2. php artisan nova:tool uu/resourcescenters
3. Would you like to install the tool's NPM dependencies? (yes/no) [yes]: > no
4. Would you like to compile the tool's assets? (yes/no) [yes]: > no
5. Would you like to update your Composer packages? (yes/no) [yes]: > 

And it`s worked!

**Comment by davidhemphill** [comment]
Glad you were able to get it working. 👍

**Comment by ginlove0** [comment]
I have the same problem. But this solution is not working for me. Does anyone have the same????
