### ISSUE TITLE
Missing user menu after upgrading to 2.6.0

### ISSUE THREAD

**Issue by mxm1070** [laravel/nova-issues#2091]
- Laravel Version: 5.8.35
- Nova Version: 2.6.0
- PHP Version: 7.3

### Description

I just updated to Nova 2.6.0 to fix the tool compilation bug and I realized my user menu is just gone. The entire top right is empty. I tried republishing the assets with php artisan nova:publish and clearing the cache with php artisan view:clear and nothing. I even tried php artisan nova:publish --force and nothing.

**Comment by davidhemphill** [comment]
I just noticed this and fixed it in v2.6.1 which is available now.

**Comment by mxm1070** [comment]
I updated to 2.6.1 and it didn't seem to fix the problem. I tried rerunning the commands above again with no change. Is there something else I can do?

**Comment by mvdnbrk** [comment]
@mxm1070 use the `--force` flag: `php artisan nova:publish --force`.

**Comment by ErikRobles** [comment]
@mxm1070 What did you change in user.blade.php? I am using nova as root so my url is localhost;8000/dashboards/main and when I logout, I get localhost:8000/logout but that just gives me a 404 not found. Thank you.
