### ISSUE TITLE
Nova Themes applied to Login but not to dashboard

### ISSUE THREAD

**Issue by ITango** [laravel/nova-issues#2093]
- Laravel Version: 5.8.34
- Nova Version: 2.6.1
- PHP Version: 7.2.22
- Database Driver and Version: MySQL
- Browser type and version: Chrome

### Description

I have generated a nova theme, I can see the theme CSS is applied to the login, but not to the dashboard.

### Steps To Reproduce

- Run php artisan nova:theme {package name}
- Register the theme in config/app.php, Itango\AdminTheme\ThemeServiceProvider::class
- Run php artisan vendor:publish

**Comment by jbrooksuk** [comment]
I'm unable to replicate this on v2.6.1:

![image](https://user-images.githubusercontent.com/246103/67845275-210ee080-faf7-11e9-942f-f5d33caeee70.png)

I _think_ you need to re-publish the Nova views.

**Comment by avfigueredo** [comment]
Hey @ITango, Do you removed the laravel nova from your compose.json?
I tried but doesn't works for me. I'm having the same problem, login page OK, but dashboard doesn't update.

**Comment by ITango** [comment]
Hey @avfigueredo, I manually removed all nova files, re-install it as a new installation, then copied back app/Nova files.

**Comment by avfigueredo** [comment]
> Hey @avfigueredo, I manually removed all nova files, re-install it as a new installation, then copied back app/Nova files.

Thanks @ITango , I removed some files from resources/vendor/nova and done!
