### ISSUE TITLE
User menu gone after upgrade to 2.6.1 from 2.5

### ISSUE THREAD

**Issue by gldrenthe89** [laravel/nova-issues#2095]
- Laravel Version: 6.4.1
- Nova Version: 2.6.1
- PHP Version: 7.3.8
- Database Driver and Version: MySQL 5.7.24
- Operating System and Version: Windows 10 (latest) and Ubuntu from Laravel Forge
- Browser type and version: Chrome latest

### Description

User menu gone after upgrading from 2.5 to 2.6.1

I do not have a Users table but a Admins table. The guards used for this are set up correctly. As this worked fine before the upgrade.

i have the publish script in composor file 
```
"scripts": {
    "post-update-cmd": [
        "@php artisan nova:publish"
    ]
}
```
i have run:
php artisan nova:publish 
php artisan vendor:publish 
php artisan view:clear
php artisan cache:clear .. etc

### Steps To Reproduce

composer update from 2.5 to 2.6.1

!!!! dont just close this issue. let people react !!!!

**Comment by jbrooksuk** [comment]
Duplicate to https://github.com/laravel/nova-issues/issues/2094 - please don't create a new issue. You're free to continue the conversation on the closed issue.

**Comment by gldrenthe89** [comment]
> Duplicate to #2094 - please don't create a new issue. You're free to continue the conversation on the closed issue.

please reopen #2094 then
