### ISSUE TITLE
duplicate queries on detail for HasMany field.

### ISSUE THREAD

**Issue by vDk3** [laravel/nova-issues#2096]
- Laravel Version: 5.8
- Nova Version: 2.6.1

### Description

I guess its related to:
https://github.com/laravel/nova-issues/issues/1810

Same thing happens on detail view when using HasMany field:
```
/nova-api/payouts?search=&filters=&orderBy=&orderByDirection=desc&perPage=25&trashed=&page=1&viaResource=users&viaResourceId=1&viaRelationship=payouts&relationshipType=hasMany

/nova-api/payouts?search=&filters=&orderBy=&orderByDirection=desc&perPage=5&trashed=&page=1&viaResource=users&viaResourceId=1&viaRelationship=payouts&relationshipType=hasMany
```

**Comment by davidhemphill** [comment]
Doesn't seem related to #1810, since that was resolved some time ago. Also, I know it's hard to see but those aren't the same query strings. Going to close, but feel free to post when you fill out all the information so we can actually debug it.

**Comment by vDk3** [comment]
Yeah w/e, nova firstly fetch resource with param perPage=25 and then same resource with param perPage=5

Steps to reproduce:
1. Add any MorphTo/HasMany/BelongsTo field to your resource or just enable Action Events 
2. Go to detail view
3. Check networks tab in your browser

`http://127.0.0.1:8000/nova-api/action-events?search=&filters=W10%3D&orderBy=&orderByDirection=desc&perPage=25&trashed=&page=1&viaResource=users&viaResourceId=34727&viaRelationship=actions&relationshipType=hasMany
http://127.0.0.1:8000/nova-api/action-events?search=&filters=W10%3D&orderBy=&orderByDirection=desc&perPage=5&trashed=&page=1&viaResource=users&viaResourceId=34727&viaRelationship=actions&relationshipType=hasMany`
