### ISSUE TITLE
Redirecting to Nova resource from Laravel login

### ISSUE THREAD

**Issue by whiteDigitalAI** [laravel/nova-issues#2098]
Hello Guys,

Our requirement is to login to 4 different tables and redirect users to Nova dashboards according to the roles. The login controllers are in Laravel as Nova supports only single Auth(Table). We are trying this for the past two days, played around with middleware,routes, redirects etc. but no luck. Any guidance is appreciated. Thanks in advance

**Comment by demency** [comment]
Hi @whiteDigitalAI 

To solve the users redirect you should:

1. Add your own LoginController extending the base Nova LoginController overwritting the authenticated method:

```php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class LoginController extends \Laravel\Nova\Http\Controllers\LoginController {
    /**
     * The user has been authenticated.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  mixed  $user
     * @return mixed
     */
    protected function authenticated(Request $request, $user)
    {
        // You're authenticated!
        return redirect('/');
    }
}
```

And bind this extension on NovaServiceProvider:

```php
<?php

namespace App\Providers;

use Laravel\Nova\Http\Controllers\LoginController;

...

class NovaServiceProvider extends NovaApplicationServiceProvider {

    ...

    public function register()
    {
        $this->app->bind(LoginController::class, \App\Http\Controllers\LoginController::class);
    }
}
```

And to solve multiple authentication tables is other issue. The before code solve the redirecting.

**Comment by whiteDigitalAI** [comment]
Many Thanks for the quick guidance Demency.. Will try this and revert back..

Take care

**Comment by davidhemphill** [comment]
Alternatively, just build the login flow as your project requires. We realize Nova's conventions may not work for everyone and expect there to be some customization from time to time.

**Comment by iBet7o** [comment]
I fixed it like this, in a component add the following and it works.

```js
  router.beforeEach((to, from, next) => {
      if (to.name == 'dashboard.custom') {
          next({
              name: 'index',
              params: {
                  resourceName: 'orders'
              }
          })
      } else {
          next()
      }
  })
```

**Comment by whiteDigitalAI** [comment]
Thank you iBet7o 

Best
Guna

**Comment by mrimran** [comment]
The clean solution for `Nova 4` is here, I've not tested that on `Nova 3` or below.

Inside `NovaServiceProvider` update the below method

```
public function register()
{
    \Laravel\Nova\Nova::$initialPath = '/resources/users'; //update it to any valid nova path
}
```

Happy coding :)
