### ISSUE TITLE
Boolean values get changed from 1 to true making ActionEvent logs less useful

### ISSUE THREAD

**Issue by CitizenBeta** [laravel/nova-issues#2099]
- Laravel Version: 5.8
- Nova Version: 2.6.1
- PHP Version: 7.3
- Database Driver and Version: mysql Ver 15.1 Distrib 10.3.17-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- Operating System and Version: Ubuntu 9.10

### Description

Boolean values get changed from 1 to true, and vice versa in nova, making ActionEvent logs less useful. This is especially annoying for large models with lots of boolean fields and you want to see what was changed.

See it in glorious action here: https://imgur.com/ob3Xf2v

### Steps To Reproduce

Create a model that has at least one boolean field. Open in Nova and make no changes. Click save. ActionEvent log will show that your boolean has changed when in fact it has not.

**Comment by jbrooksuk** [comment]
I might be mis-understanding, but I don't see the boolean field changing if I've not made any changes to it.

However, I do see that checking and un-checking the field does result in true = 1 and false = 0, which is a bit confusing, for sure.
