### ISSUE TITLE
Call to undefined method BelongsToMany::getForeignKey()

### ISSUE THREAD

**Issue by Jaspur** [laravel/nova-issues#2100]
- Laravel Version: v6.4.1
- Nova Version: v2.6.1
- PHP Version: PHP 7.3.1
- Database Driver and Version: psql (PostgreSQL) 10.6 
- Operating System and Version: Ubuntu 10.6-0ubuntu0.18.04.1)
- Browser type and version: Safari  13.0.2 (

### Description
BelongsToMany not showing/saving in Nova. Because it's missing an ID, but Pivot tables are without IDs'.

### Steps To Reproduce
Migration:
```
Schema::create('question_condition', function (Blueprint $table) {
    $table->integer('question_id')->unsigned()->index();
    $table->foreign('question_id')->references('id')->on('questions')->onDelete('cascade');
    $table->integer('condition_id')->unsigned()->index();
    $table->foreign('condition_id')->references('id')->on('conditions')->onDelete('cascade');
    $table->timestamps();
    $table->primary(['condition_id', 'question_id']);
});
```

Model **Question**
```
class Question extends Model
{
   public function conditions()
    {
        return $this->belongsToMany(Condition::class, 'question_condition')->withTimestamps()->using(QuestionCondition::class);
    }
}
```
Model **Condition**
```
class Condition extends Model
{

    public function questions()
    {
        return $this->belongsToMany(Question::class, 'question_condition')->withTimestamps()->using(QuestionCondition::class);
    }
}
```
Model **QuestionCondition**
```
use Illuminate\Database\Eloquent\Relations\Pivot;
class QuestionCondition extends Pivot
{
    public $incrementing = false;
}
```

That all looks fine for the BelongsToMany relationships.

Now the Nova-part:
**Condition** > THIS WORKS
```
 return [
            ID::make()->sortable(),
            BelongsToMany::make('Questions')->searchable(),
        ];
```
**Question** > _This fails.._
```
BelongsToMany::make('Conditions', 'Conditions')
```
And also this is not working:
```
BelongsToMany::make('Conditions', 'Conditions')
                ->fields(function () {
                    return [
                        BelongsTo::make('Question')->searchable(),
                    ];
                })->sortable(),
```

That results in this error when trying to Show the Question which has a Condition attached:

> [2019-10-31 10:22:46] local.ERROR: Call to undefined method Illuminate\Database\Eloquent\Relations\BelongsToMany::getForeignKey() {"userId":1,"exception":"[object] (BadMethodCallException(code: 0): Call to undefined method Illuminate\\Database\\Eloquent\\Relations\\BelongsToMany::getForeignKey() at /home/vagrant/code/the-app/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:50)
> [stacktrace]
> #0 /home/vagrant/code/the-app/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(36): Illuminate\\Database\\Eloquent\\Relations\\Relation::throwBadMethodCallException('getForeignKey')
> #1 /home/vagrant/code/the-app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(385): Illuminate\\Database\\Eloquent\\Relations\\Relation->forwardCallTo(Object(Illuminate\\Database\\Eloquent\\Builder), 'getForeignKey', Array)
> #2 /home/vagrant/code/the-app/vendor/laravel/nova/src/Fields/ResolvesReverseRelation.php(83): Illuminate\\Database\\Eloquent\\Relations\\Relation->__call('getForeignKey', Array)
> #3 /home/vagrant/code/the-app/vendor/laravel/nova/src/Fields/ResolvesReverseRelation.php(64): Laravel\\Nova\\Fields\\BelongsTo->getRelationForeignKeyName(Object(Illuminate\\Database\\Eloquent\\Relations\\BelongsToMany))
> #4 /home/vagrant/code/the-app/vendor/laravel/framework/src/Illuminate/Support/Arr.php(175): Laravel\\Nova\\Fields\\BelongsTo->Laravel\\Nova\\Fields\\{closure}(Object(Benjacho\\BelongsToManyField\\BelongsToManyField), 7)
> #5 /home/vagrant/code/the-app/vendor/laravel/framework/src/Illuminate/Support/Collection.php(367): Illuminate\\Support\\Arr::first(Array, Object(Closure), NULL)
> #6 /home/vagrant/code/the-app/vendor/laravel/nova/src/Fields/ResolvesReverseRelation.php(67): Illuminate\\Support\\Collection->first(Object(Closure))
> #7 /home/vagrant/code/the-app/vendor/laravel/nova/src/Fields/ResolvesReverseRelation.php(30): Laravel\\Nova\\Fields\\BelongsTo->getReverseRelation(Object(Laravel\\Nova\\Http\\Requests\\ResourceIndexRequest))
> #8 /home/vagrant/code/the-app/vendor/laravel/nova/src/Fields/BelongsTo.php(138): Laravel\\Nova\\Fields\\BelongsTo->isReverseRelation(Object(Laravel\\Nova\\Http\\Requests\\ResourceIndexRequest))
> #9 /home/vagrant/code/the-app/vendor/laravel/nova/src/Fields/BelongsTo.php(123): Laravel\\Nova\\Fields\\BelongsTo->isNotRedundant(Object(Laravel\\Nova\\Http\\Requests\\ResourceIndexRequest))
> #10 /home/vagrant/code/the-app/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php(60): Laravel\\Nova\\Fields\\BelongsTo->authorize(Object(Laravel\\Nova\\Http\\Requests\\ResourceIndexRequest))

**Comment by dkulyk** [comment]
You are using 3rd party [package](https://github.com/Benjacho/belongs-to-many-field-nova) with custom BelongsToMany field.
