### ISSUE TITLE
Global search - override initial number of results displayed

### ISSUE THREAD

**Issue by skoyah** [laravel/nova-issues#2103]
Would be nice to be able to override the amount of results displayed on the global search.

Maybe overriding the current number set by default on the GlobalSearch class:

```php
if (count($models = $query->limit(5)->get()) > 0) {
        $results[$resource] = $models;
}
```

Would be more than happy to contribute with this feature if it shows appealing.

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by davidhemphill** [comment]
I'd be fine with adding it if it was per-resource and fell back to the base class value.

**Comment by skoyah** [comment]
Yeah. I was thinking on setting a default at the Resource class and only overriding it if needed on the actually resource.

**Comment by davidhemphill** [comment]
@jbrooksuk might have beat you to it: https://github.com/laravel/nova/pull/696

**Comment by skoyah** [comment]
Damn you @jbrooksuk ! :)

But IMHO I would rather prefer to be able to override it on a per resource basis. His changes will be applied for all resources. 

What do you think @jbrooksuk ?

**Comment by jbrooksuk** [comment]
Yep. Will make it happen tomorrow.
