### ISSUE TITLE
[Docs] - Boolean Filter

### ISSUE THREAD

**Issue by skoyah** [laravel/nova-issues#2104]
Was looking at the docs about Boolean filters, and noticed that the example as commented code.

Not sure if this was intended. Just to let you know:

![Screenshot 2019-10-31 at 17 27 30](https://user-images.githubusercontent.com/36083448/67966313-f9596e80-fc03-11e9-85c9-26dc738e20ef.png)

**Comment by davidhemphill** [comment]
This is intentional to show the user what kind of value could come back in that example.
