### ISSUE TITLE
Password confirmation

### ISSUE THREAD

**Issue by mdpoulter** [laravel/nova-issues#2105]
Will the new Laravel password confirmation feature (laravel/framework#30214) be coming to Nova? If so, would it be on a per-resource basis? This would give the ability for a password to be re-entered before seeing more sensitive resources.

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
