### ISSUE TITLE
lenses

### ISSUE THREAD

**Issue by anditsung** [laravel/nova-issues#2107]
- Laravel Version: 6
- Nova Version: 2.6.1
- PHP Version: 7.2

### Description

```
/**
     * Get the actions available on the lens.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function actions(Request $request)
    {
        return parent::actions($request);
    }
```

actions on lenses will always return parent::actions event already set return []

**Comment by davidhemphill** [comment]
I'm not able to replicate your issue. If you have more specific steps we can use to demonstrate the issue, please post a new issue. Thanks!
