### ISSUE TITLE
Belongs to doesn't work when relation name is same as the foreign_key name

### ISSUE THREAD

**Issue by moeen-basra** [laravel/nova-issues#2108]
- Laravel Version: 6.4.1
- Nova Version: dev-master
- PHP Version: 7.3
- Database Driver and Version: pgsql 11
- Operating System and Version: Docker Alpine
- Browser type and version: Chrome 78
- Reproduction Repository: https://github.com/###/###

### Description

When the relation name is same as the foreign_key name, nova throughs exception field not found

### Steps To Reproduce

1. create a class with the name Country (id: increment, name: string)
2. create a class with the name Profile (user's profile) with fields (id: increment, nationality: string)
3. create relation on the profile table with country

My Profile Model code is as following
```
public function nationality(): BelongsTo
{
    return $this->belongsTo(Country::class, 'nationality', 'name');
}
```

My Nova Resource Profile Belongs to code is as following 
```
BelongsTo::make('Nationality', 'nationality', 'App\Nova\Country')
                ->onlyOnForms()
                ->searchable()
                ->rules(['nullable', 'max:50']),
```

Here is the exception message

```
Undefined property: App\Data\Models\User\Profile::$nationality
```

**Comment by jbrooksuk** [comment]
`dev-master` is **very** outdated. You should be using the `2.0` branch. https://github.com/laravel/nova

**Comment by moeen-basra** [comment]
@jbrooksuk its same for the version 2.0 as well.
