### ISSUE TITLE
Transalte resource label on the panel

### ISSUE THREAD

**Issue by zareismail** [laravel/nova-issues#2109]
- Laravel Version: 6.4.0
- Nova Version: 2.6.1 

### Description

Hi;
I think making name for the `Panel` is wrong; because, the panel just translating self string and don't translate `resource label`. see below:

At the moment the panel label is this:

```
 public static function defaultNameFor*(Resource $resource)
    {
        return __('Update :resource', [
            'resource' => $resource->singularLabel(),
        ]);
    }
``` 

ََََAnd should be something like this:

```
 public static function defaultNameFor*(Resource $resource)
    {
        return __('Update :resource', [
            'resource' => __($resource->singularLabel()),
        ]);
    }
```

**Comment by jbrooksuk** [comment]
You can translate the resource name within the `singularLabel` method.

**Comment by zareismail** [comment]
> You can translate the resource name within the `singularLabel` method.

I know, but I think this is not a good idea
