### ISSUE TITLE
[Feature request] Notifications

### ISSUE THREAD

**Issue by patrickbrouwers** [laravel/nova-issues#211]
Really loving Nova so far! Makes dealing with admin panels a true breeze.

It would be great if we had (database) notifications (https://laravel.com/docs/5.6/notifications) support baked in, like Laravel Spark does. Could be either a simple dropdown list of notifications or a right-sidebar like Spark. This would be especially awesome for queued actions, so we could let the user know when the action is fully completed.

**Comment by dillingham** [comment]
Also proposed as package ideas
https://github.com/tightenco/nova-package-development/issues/10
https://github.com/tightenco/nova-package-development/issues/26

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
