### ISSUE TITLE
Select All and Select All Matching from lens do nothing

### ISSUE THREAD

**Issue by fgilio** [laravel/nova-issues#2111]
- Laravel Version: 6.4.1
- Nova Version: 2.6.1
- PHP Version: 7.3
- Database Driver and Version: MySQL 5.7
- Operating System and Version: macOS Catalina
- Browser type and version: Chrome 78.0.3904.70 (Official Build) (64-bit)
- Reproduction Repository: Don't have any

### Description

When inside a Lens, the "Select All" and "Select All Matching" checkboxes do nothing. The individual rows are not selected and the actions menu is not visible.
There's no error in the console.

### Steps To Reproduce

Here's a recording of the bug:
![Kapture 2019-11-05 at 20 08 46](https://user-images.githubusercontent.com/6857732/68254003-2c3aa280-0008-11ea-8f8f-d4e54dfd850a.gif)

Tell me if there's anything else I can do, or if you need more information.

Thanks!

**Comment by fgilio** [comment]
I guess the fallback I'll try is to just use a resource for that lens.

**Comment by davidhemphill** [comment]
Fixed this in the upcoming release.

**Comment by fgilio** [comment]
Thanks!
