### ISSUE TITLE
BooleanGroup Field can't update  or create on Eloquent ORM 

### ISSUE THREAD

**Issue by xiyixia** [laravel/nova-issues#2112]
- Laravel Version: 6.4.1
- Nova Version: 2.6.1
- PHP Version: 7.2
- Database Driver and Version: mysql 5.7
- Operating System and Version: ubuntu 18.04

### Description

I use BooleanGoup Field to attach roles but failed !
```
message: "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'roles' in 'field list' (SQL: update `admins` set `roles` = {"1":false,"2":false}, `permissions` = {"1":false}, `admins`.`updated_at` = 2019-11-06 15:33:19 where `id` = 1)",
```

### Steps To Reproduce
1. create Admin model 
2. install laravel-permission
3.  add the Spatie\Permission\Traits\HasRoles trait to Admin model
```
   class Admin extends Authenticatable
{
    use HasRoles;

    // ...
}
```

**Comment by jbrooksuk** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](https://larachat.co/).

**Comment by xiyixia** [comment]
ok! thanks !&nbsp;



小小夏
程序开发

广州冰茶派信息技术有限公司
广州天河区中山大道89号华景软件园C栋108
18613133078





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "James Brooks"<notifications@github.com&gt;; 
发送时间: 2019年11月6日(星期三) 下午4:48
收件人: "laravel/nova-issues"<nova-issues@noreply.github.com&gt;; 
抄送: "小小夏"<458007508@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [laravel/nova-issues] BooleanGroup Field can&#39;t update  or create on Eloquent ORM  (#2112)




This issue board is for tracking bugs, not general development questions. Please direct general questions to #nova on Laravel's Discord or #nova on the Larachat Slack Channel.
 
&mdash;
