### ISSUE TITLE
BooleanGroup::options does not match Select::options 

### ISSUE THREAD

**Issue by bmichotte** [laravel/nova-issues#2113]
Hi there,

- Nova Version: 2.6.1

### Description

`Select::options` accept an `array` as well as a `Collection`
`BooleanGroup::options` only accept an `array`

`BooleanGroup` should also accept a `Collection`

### Steps To Reproduce

```php
class Bar extends Resource
{
    public function fields(Request $request)
    {
        return [
            Select::make('Foo')
                ->options(\App\Foo::pluck('name', 'id')) // a collection
                ->displayUsingLabels(),

            BooleanGroup::make('Foo')
                ->options(\App\Foo::pluck('name', 'id')->toArray()), // only array
        ];
    }
}
```

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by davidhemphill** [comment]
This has been added and will be included in the next release. 👍
