### ISSUE TITLE
Allowing filters to filter post-query collection

### ISSUE THREAD

**Issue by coryrose1** [laravel/nova-issues#2114]
I hope this has not already been suggested but couldn't find a related issue other than https://github.com/laravel/nova-issues/issues/2041

Filters currently allow you access to the query builder, which is great when you want to filter by any database query.

However, it does not look like you are able to filter the post-database query collection returned by the builder, meaning one cannot filter results by a derived attribute.

Think about this in an application that uses Laravel Cashier and has a subscription model. Users of this application might have a `getSubscriptionStatusAttribute()` that uses Cashier's methods to determine the status and returns a string like 'Trialing', 'Active', 'Cancelled', etc.

There is currently no way to use Filters with this derived attribute whereas it seems like a natural thing to want to do on the Users table. 

I see that Lenses may be an option, but again, we would be working with the base query and not the methods Cashier provides to check status. Even outside of subscriptions, status is often a derived attribute versus a database column.

If anyone can point me towards a solution for this, I'd be grateful. Otherwise it'd be great to see the Filter class extended to allow you to filter the returned collection, post query.

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by gillidandaweb** [comment]
Would be helpful for working with encrypted data.
