### ISSUE TITLE
MorphTo field, required * > style issue

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#2115]
- Laravel Version: 5.8.35
- Nova Version: 2.6.1
- PHP Version: 7.2.19

### Description

A morphto field has two fields. The second field is not selectable, until a selection is made in the first one. However, the 'required' star is already shown in the second field.

![nova-style-bug](https://user-images.githubusercontent.com/5418196/68304868-ef71b880-00a6-11ea-80b9-694307bbee7d.jpg)

The first to select a type
### Steps To Reproduce

1) Create morphto field
2) See required star (without any label in front of it)

**Comment by jbrooksuk** [comment]
Granted, it's slightly weird, but it's also the expected behaviour. This field _is_ required and until you pick the type, we don't know what the field is yet.

I'm going to label this as a feature request because nothing is broken here.

**Comment by preliot** [comment]
My two cents: From a UX point of view I think showing the star once the label is there, would make more sense.

**Comment by jbrooksuk** [comment]
It's just as confusing, I tried it :)

**Comment by preliot** [comment]
Let's agree to disagree then :-) Thanks for your input!
