### ISSUE TITLE
Boolean fields stop working

### ISSUE THREAD

**Issue by kikoseijo** [laravel/nova-issues#2116]
- Laravel Version: 5.8.*
- Nova Version: 2.6.1
- PHP Version: 7.2
- MAC OS 10.13.6
- Safari Version 11.1.2 (13605.3.8)

### Description

Since recent update the boolean fields stoped working. 
They basically don't change it values.

Seems its only happening in SAFARI
Version 11.1.2 (13605.3.8)

**Comment by davidhemphill** [comment]
Sorry, but we are unable to debug your issue without a reproducible code example. Everything seems to be working for me on that end, but maybe you have a simple example I can use to reproduce it?

**Comment by kikoseijo** [comment]
Hi,

Sorry, but after I created I realised that this only happens on safari, on chrome it does not happen.
This is why I updated the safari and Mac version.

Its a browser issue, but was working fine before, no need to reproduce the error with code.

Thanks again.

**Comment by davidhemphill** [comment]
I tested this earlier and was not able to reproduce your issue. The boolean fields are working and storing correctly in my test repos. That's why I asked for a code example...maybe there was something unique on your end. :-)
