### ISSUE TITLE
Nova api scripts/styles very slow

### ISSUE THREAD

**Issue by sweebee** [laravel/nova-issues#2117]
- Laravel Version: 6.5.0
- Nova Version: 2.6.1
- PHP Version: 7.3
- Database Driver and Version: Mysql 5.7
- Operating System and Version: Ubuntu 18
- Browser type and version: Chrome 78

### Description

All nova api styles/scripts load very slow. This are the loading times on my DO VPS (10 dollar). It also seems that these urls are not cached.

<img width="795" alt="Schermafbeelding 2019-11-06 om 18 40 49" src="https://user-images.githubusercontent.com/10496485/68323378-9d8c5b00-00c5-11ea-9af5-975c7d2d229f.png">
<img width="799" alt="Schermafbeelding 2019-11-06 om 18 41 08" src="https://user-images.githubusercontent.com/10496485/68323388-9feeb500-00c5-11ea-80db-e3157627433f.png">

**Comment by jbrooksuk** [comment]
I know that this doesn't resolve the core of the issue, but you could always cache these endpoints on your server / Cloudflare (if you're using it).

**Comment by m-lotze** [comment]
@sweebee https://github.com/laravel/nova-issues/issues/1146 ... look at my last comment

**Comment by rikless** [comment]
@jbrooksuk @sweebee @m-lotze In my case, I've created a middleware to avoid this : 

```php
<?php

namespace App\Http\Middleware;

use Closure;

class NovaStaticsMiddleware
{
    /**
     * Handle an incoming request.
     *
     * @param \Illuminate\Http\Request $request
     * @param \Closure                 $next
     *
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        if ($request->getMethod() === 'GET') {
            $routes = [
                //here your scripts routes
                '/nova-api/scripts/test',
                //here your styles routes
                '/nova-api/styles/test',
               
            ];
            if (\in_array($request->getRequestUri(), $routes, true)) {
                return app(SetCacheControl::class)
                    ->handle($request, static function ($request) use ($next) {
                        return $next($request);
                    }, 'private;max_age=3600;etag');
            }
        }

        return $next($request);
    }
}
 
```

**Comment by jbrooksuk** [comment]
Can I just check a few things about this issue:

1. Have you compiled these assets using the `prod` command?
2. What server setup are you serving these from? We use a custom Resource Tool in Laravel Forge and we do not have any issues with performance.

**Comment by rikless** [comment]
@jbrooksuk it's not about compiling. It's just because it's not a real asset, and it's generated on the fly by a request on your laravel app, so this load all the core framework, build the response, and send the asset content. You don't load the compiled assets, you hit the api endpoint where the assets content will be served.

You'll start to have issue when you will have lots of custom resource, and the first time you load the page. If you don't close the tab, assets are not loaded again. But if you open a new tab, load the page, you'll have the issue. Close the tab, open it again, and you'll have it again. Use a resource link to change the page, you'll not have any issue (SPA).

I hope you better understand the issue !
My workaround was to add some cache in the response headers.

Here is the _SetCacheControl_ I use from my previous middleware : 

```php
<?php

namespace App\Http\Middleware;

use Closure;

class SetCacheControl
{
    /**
     * Add cache related HTTP headers.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @param  string|array  $options
     * @return \Symfony\Component\HttpFoundation\Response
     *
     * @throws \InvalidArgumentException
     */
    public function handle($request, Closure $next, $options = [])
    {
        $response = $next($request);

        if (is_string($options)) {
            $options = $this->parseOptions($options);
        }

        if (isset($options['etag']) && $options['etag'] === true) {
            $options['etag'] = md5($response->getContent());
        }

        $response->setCache($options);
        $response->isNotModified($request);

        return $response;
    }

    /**
     * Parse the given header options.
     *
     * @param  string  $options
     * @return array
     */
    protected function parseOptions($options)
    {
        return collect(explode(';', $options))->mapWithKeys(function ($option) {
            $data = explode('=', $option, 2);

            return [$data[0] => $data[1] ?? true];
        })->all();
    }
}

```

**Comment by jbrooksuk** [comment]
> @jbrooksuk it's not about compiling. It's just because it's not a real asset, and it's generated on the fly by a request on your laravel app, so this load all the core framework, build the response, and send the asset content. You don't load the compiled assets, you hit the api endpoint where the assets content will be served.

I get this, but I'm asking whether the assets are compiled. The size of the response will still be a factor in this.

**Comment by m-lotze** [comment]
@jbrooksuk thats visible in the screenshots in the original post. you see the compressed/compiled asset size and the parsed size.

**Comment by dkulyk** [comment]
This has been fixed and will be included in the next release. 👍

Added support of resources check for Last-Modified.

**Comment by rikless** [comment]
I may be wrong, but I think even if it's better, it will still have to hit the server, and make the response. So it will still be slow because it's on multiple "static" resources.

**Comment by sweebee** [comment]
@dkulyk is this fixed in ```2.7.0```? If so, it doesn't seem to help.

**Comment by dkulyk** [comment]
This PR adds checking resource for modification. Browser is using cache if resource is not modified.
Uncheck "Disable cache" on you dev console.

**Comment by sweebee** [comment]
doesn't seem to do anything here?

<img width="741" alt="Schermafbeelding 2019-11-13 om 10 12 57" src="https://user-images.githubusercontent.com/10496485/68749249-35c29c80-05fe-11ea-9f3d-57fafd068a5f.png">

**Comment by rikless** [comment]
@sweebee did you tried my solution ?

**Comment by sweebee** [comment]
@rikless thats better

<img width="372" alt="Schermafbeelding 2019-11-13 om 10 24 02" src="https://user-images.githubusercontent.com/10496485/68750180-c188f880-05ff-11ea-8f75-6226c5006206.png">

**Comment by genesiscz** [comment]
So I know this is closed, but I still see this problem with third party scripts


![image](https://user-images.githubusercontent.com/1512353/78859530-e313d200-7a2f-11ea-86db-6c50e4323472.png)

It still does the long process of booting the framework and just getting the 304 afterwards.

Am I doing something wrong?

**Comment by genesiscz** [comment]
> @jbrooksuk it's not about compiling. It's just because it's not a real asset, and it's generated on the fly by a request on your laravel app, so this load all the core framework, build the response, and send the asset content. You don't load the compiled assets, you hit the api endpoint where the assets content will be served.
> 
> You'll start to have issue when you will have lots of custom resource, and the first time you load the page. If you don't close the tab, assets are not loaded again. But if you open a new tab, load the page, you'll have the issue. Close the tab, open it again, and you'll have it again. Use a resource link to change the page, you'll not have any issue (SPA).
> 
> I hope you better understand the issue !
> My workaround was to add some cache in the response headers.
> 
> Here is the _SetCacheControl_ I use from my previous middleware :
> 
> ```
> <?php
> 
> namespace App\Http\Middleware;
> 
> use Closure;
> 
> class SetCacheControl
> {
>     /**
>      * Add cache related HTTP headers.
>      *
>      * @param  \Illuminate\Http\Request  $request
>      * @param  \Closure  $next
>      * @param  string|array  $options
>      * @return \Symfony\Component\HttpFoundation\Response
>      *
>      * @throws \InvalidArgumentException
>      */
>     public function handle($request, Closure $next, $options = [])
>     {
>         $response = $next($request);
> 
>         if (is_string($options)) {
>             $options = $this->parseOptions($options);
>         }
> 
>         if (isset($options['etag']) && $options['etag'] === true) {
>             $options['etag'] = md5($response->getContent());
>         }
> 
>         $response->setCache($options);
>         $response->isNotModified($request);
> 
>         return $response;
>     }
> 
>     /**
>      * Parse the given header options.
>      *
>      * @param  string  $options
>      * @return array
>      */
>     protected function parseOptions($options)
>     {
>         return collect(explode(';', $options))->mapWithKeys(function ($option) {
>             $data = explode('=', $option, 2);
> 
>             return [$data[0] => $data[1] ?? true];
>         })->all();
>     }
> }
> ```

This actually worked for scripts, but not for styles. @rikless Did you make it work even for styles?

**Comment by edgarnadal** [comment]
> @jbrooksuk @sweebee @m-lotze In my case, I've created a middleware to avoid this :
> 
> ```
> <?php
> 
> namespace App\Http\Middleware;
> 
> use Closure;
> 
> class NovaStaticsMiddleware
> {
>     /**
>      * Handle an incoming request.
>      *
>      * @param \Illuminate\Http\Request $request
>      * @param \Closure                 $next
>      *
>      * @return mixed
>      */
>     public function handle($request, Closure $next)
>     {
>         if ($request->getMethod() === 'GET') {
>             $routes = [
>                 //here your scripts routes
>                 '/nova-api/scripts/test',
>                 //here your styles routes
>                 '/nova-api/styles/test',
>                
>             ];
>             if (\in_array($request->getRequestUri(), $routes, true)) {
>                 return app(SetCacheControl::class)
>                     ->handle($request, static function ($request) use ($next) {
>                         return $next($request);
>                     }, 'private;max_age=3600;etag');
>             }
>         }
> 
>         return $next($request);
>     }
> }
>  
> ```

I updated the middleware so I don't have to declare every other route FYI.

```
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Support\Str;
use Core\Foundation\Http\Middleware\SetCacheControl;

class NovaStaticsMiddleware
{
    /**
     * Handle an incoming request.
     *
     * @param \Illuminate\Http\Request $request
     * @param \Closure                 $next
     *
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        if ($request->getMethod() === 'GET') {

            $routes = [
                '/nova-api/scripts/',
                '/nova-api/styles/',
            ];

            if (Str::of($request->getRequestUri())->startsWith($routes)) {
                return app(SetCacheControl::class)
                    ->handle($request, static function ($request) use ($next) {
                        return $next($request);
                    }, 'private;max_age=3600;etag');
            }
        }

        return $next($request);
    }
}
```

**Comment by genesiscz** [comment]
@edgarnadal what is this good for if you already use the SetCacheControl class stated earlier in this thread?
