### ISSUE TITLE
Resource Tool Stubs using field instead of panel

### ISSUE THREAD

**Issue by MohammadAbusaleh** [laravel/nova-issues#2119]
- Laravel Version: 6.5.0
- Nova Version: 2.6.1
- PHP Version: 7.3

### Description

When generating a Resource Tool, the Tool.vue file comes with the following props:
`props: ['resourceName', 'resourceId', 'field'],`

while it should be:
`props: ['resourceName', 'resourceId', 'panel'],`

as per the documentation, to allow us to use the panel to fetch withMeta.

### Steps To Reproduce

Generate a new nova resource-tool.

`php artisan nova:resource-tool acme/stripe-inspector`

**Comment by davidhemphill** [comment]
Fixed laravel/nova@ad9056628f9d3aa331cde7124da34b4fbc7d163f
