### ISSUE TITLE
[Feature request] crop image

### ISSUE THREAD

**Issue by devmsh** [laravel/nova-issues#212]
Did anyone plan to develop a image cropper field?

**Comment by disitec** [comment]
FYI just released this package. Hope it helps!

https://novapackages.com/packages/r64/nova-image-cropper

**Comment by devmsh** [comment]
@disitec I will give it a try, did you support english locale?

**Comment by disitec** [comment]
Sure. English is the default locale. Im changing the demo gif to english.
