### ISSUE TITLE
Unexpected data found. Unexpected data found. Data missing

### ISSUE THREAD

**Issue by JR0122** [laravel/nova-issues#2120]

**Comment by jbrooksuk** [comment]
Sorry, but there's not enough information to go off of here. If the issue you have still persists, please feel free to open a new issue with all the details of what you're trying, what you expect to happen, what's happening, and how to reproduce it. Thanks!

**Comment by Stiropor** [comment]
@jbrooksuk I was just searching issues about this same problem, I get it when I try updating a record with a date field (date_rated):

`Date::make('Rating date, 'date_rated')->format('DD.MM.YYYY')->pickerFormat('d.m.Y')`
