### ISSUE TITLE
Attach BelongsToMany relationships using checkboxes

### ISSUE THREAD

**Issue by pdolinaj** [laravel/nova-issues#2121]
- Laravel Version: 5.7.27
- Nova Version: 1.3.2

**Description**

Currently the ATTACH screen with related entity is shown as SELECT field where I can select only 1 value. I need this to be customisable to use multi CHECKBOXES. How could I achieve this?

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
