### ISSUE TITLE
ErrorException - no failed method

### ISSUE THREAD

**Issue by judahnator** [laravel/nova-issues#2123]
- Laravel Version: 6.4.1
- Nova Version: 2.6.1
- PHP Version: 7.3

### Description

If an action fails, but has no failed method, Nova will attempt to call the nonexistent 'failed' method in error.

### Steps To Reproduce

Write an action with no 'failed' method that will fail, and call it. You will see an exception that looks like this:

```
call_user_func() expects parameter 1 to be a valid callback, class 'App\Nova\Actions\MyAction' does not have a method 'failed'
```

The reason for this seems to be a typo, see this screenshot of the `vendor/laravel/nova/src/Actions/CallQueuedAction.php` file:
![image](https://user-images.githubusercontent.com/8620392/68493790-5bb8fd00-020a-11ea-8301-ae2bbf0752c8.png)

Line 78 checks to see if the `failed` method exists in `$this`, which will evalueate to 'true' as it has been defined on L57. However, L62 calls the result of the `failedMethodName()` method not in the `$this` context but in the context of `$this->action`.

If L78 is changed from `return method_exists($this, 'failed')` to `return method_exists($this->action, 'failed')` then it should work.

**Comment by jbrooksuk** [comment]
I can confirm the bug, but changing line 78 does not fix this for me. Requires more investigation.

**Comment by davi5e** [comment]
Same here, using Nova 3.0.2.

Is there any workaround while the bug persists?

**Comment by judahnator** [comment]
I put this in my base "Action" class:

```php
    use Illuminate\Database\Eloquent\Collection as EloquentCollection;
    use Laravel\Nova\Fields\ActionFields;

    /**
     * Not necessary, but prevents an upstream issue that would attempt to call this method regardless of it existed.
     *
     * @param ActionFields $fields
     * @param EloquentCollection $models
     * @param Exception $e
     */
    public function failed(ActionFields $fields, EloquentCollection $models, Exception $e): void
    {
        // just some internal logging, customize for your own application
        $this->log()->error($e->getMessage(), [
            'fields' => $fields->toArray(),
            'models' => $models->toArray(),
            'exception' => $e,
        ]);
    }
```

**Comment by phuclh** [comment]
I am facing the same issue.
