### ISSUE TITLE
BelongsTo sortable() should sort by label

### ISSUE THREAD

**Issue by cotrudel** [laravel/nova-issues#2124]
It's nice that belongsTo now sorts on index when sortable() is set, but it currently sorts by the belongsTo resource ID. Normal users will expect that if they sort by a column, they'll be sorting by the visible value (the label).

If there's genuine interest in merging this, I'd be happy to put together a PR, since it's something that comes up in multiple places on our projects.

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
