### ISSUE TITLE
Asterisk not Shown to indicate a field is required

### ISSUE THREAD

**Issue by jahid56** [laravel/nova-issues#2125]
- Laravel Version: 5.8
- Nova Version: 2.2.0
- PHP Version: 7.1.3

### Description

Asterisk not Shown to indicate a field is required. In Nova Documentation it is said that 
`By default, Nova will use a red asterisk to indicate a field is required:`
I am using this
`Text::make('Email')->rules('required'),`
But No Asterisk is shown. I can't get where the problem is.

**Comment by dkulyk** [comment]
This is available since v2.5.0

**Comment by trollfalgar** [comment]
I'm with this problem.

-     Laravel Version: 6.10.1
-     Nova Version: 2.9.3
-     PHP Version: 7.3.13

Someone knows how to fix?

**Comment by abdallah84** [comment]
also me the same problem,
did anyone fix it ?
