### ISSUE TITLE
Incorrect pivot fields on belongsToMany relationship.

### ISSUE THREAD

**Issue by nemanjamar** [laravel/nova-issues#2128]
- Laravel Version: 6.0
- Nova Version: 2.3.1 and 2.6.1
- PHP Version: 7.2
- Database Driver and Version: mysql 10.3.15-MariaDB
- Operating System and Version: Windows 10 Pro
- Browser type and version: Mozilla Firefox 70.0.1, Google Chrome 78.0.3904.97

### Description
I have created two laravel models and two belongsToMany relationships beetween them.
Those 2 pivot tables have custom names and different pivot columns.
Relations are tested and work fine in laravel, but when I use those relations in laravel nova index view, utilizing nova BelongsToMany field, for both relations the same pivot columns are displayed, pivot columns from first defined relationship.
When I remove one of them, from both of nova resources, relationship display correct fields.

![bug report](https://user-images.githubusercontent.com/55561826/68592795-30494300-0494-11ea-89ba-d7a5941f5669.png)

When both belongsToMany relationships are present:
![bug report 2](https://user-images.githubusercontent.com/55561826/68593465-d0539c00-0495-11ea-9a24-3697fd111132.png)

When first belongsToMany relationship is removed.
![image](https://user-images.githubusercontent.com/55561826/68593967-d8600b80-0496-11ea-8c3f-e920296b014c.png)

**Comment by drewwbctz** [comment]
Can confirm issue persists in Nova 2.12.0

**Comment by buttjer** [comment]
Can confirm issue persists in Nova 3.6 #2636 2625

**Comment by sgerritsen** [comment]
Can confirm the issue persists in Nova 3.29

**Comment by crynobone** [comment]
Can someone share a full repository with example on how to reproduce this issue?  I wasn't able to reproduce this issue.

**Comment by sgerritsen** [comment]
@crynobone I've tried to be as detailed as I can in my description of the issue and how to recreate it #3533
