### ISSUE TITLE
Non-profit license

### ISSUE THREAD

**Issue by Navi2016** [laravel/nova-issues#213]
Hi,

Don't see any contact info on the Nova website so trying it here.

Do you have a special license / discount available for non-profit organizations?

Thanks!

**Comment by thannaske** [comment]
99$ is a fair price, even for NPOs. To scaffold a CRUD-backend in this high quality you would need hours of developing and you got all of this done for not even 100 US-Dollars.

**Comment by Navi2016** [comment]
Yes, but the license woulden't be valid because revenue > 20k.

If it would be allowed to use the Solo license for non-profit that would be nice.

**Comment by Navi2016** [comment]
I know it isn't much, but non-profit is non-profit, we have to save where we can! Just asking :)

**Comment by kohenkatz** [comment]
@Navi2016 I would like an official answer to this too, so can you reopen it?

**Comment by davidhemphill** [comment]
Contact support about licensing questions. :-)
