### ISSUE TITLE
Search input disappears from index with dynamic searchable columns array

### ISSUE THREAD

**Issue by skoyah** [laravel/nova-issues#2130]
- Laravel Version: 5.8
- Nova Version: 2.1.0
- PHP Version: 7.3

### Description
When overriding the resource method `searchableColumns()` to dynamically build the searchable fields array, the index search input disappears although we can still perform a global search. The only way to fix this bug is by overriding another method, `searchable()` to return `true`.

This happens because the current implementation of this method returns true only if the `$search` property is  not empty or if it uses `Scout`.

**Comment by jbrooksuk** [comment]
I've just tested this and am unable to replicate the issue.

I added:

```php
/**
* Get the searchable columns for the resource.
*
* @return array
*/
public static function searchableColumns()
{
    return ['id', 'name', 'email'];
}
```

To my `User` resource and the search input remains.

If you look at the [`Resource`](https://github.com/laravel/nova/blob/bb3d0fe25ac7dc7d712bbd51dd7ed8a317002459/src/Resource.php#L207-L212) class, the `searchableColumns` method does not look at the `searchable` method.

**Comment by skoyah** [comment]
Maybe I didn't explained myself right. :)

Besides adding that function, try to remove the `$search` array from the resource. The method is overriding that so there's no need to use it on the resource.

That way, if you still can't replicate it, just let me know.

**Comment by skoyah** [comment]
This is what is expecting on the Resource:

<img width="505" alt="Screenshot 2019-11-12 at 20 22 25" src="https://user-images.githubusercontent.com/36083448/68703117-3cafc780-058a-11ea-8757-73e9bb514b3d.png">


This is what's being expected on `Index.vue`:

<img width="732" alt="Screenshot 2019-11-12 at 20 24 34" src="https://user-images.githubusercontent.com/36083448/68703258-8b5d6180-058a-11ea-8eda-0bde282a5266.png">


So as you can see, the component expects `resourceInformation.searchable` to be true.

But since you are not using the `$search`  property, but overriding it instead, this will return false:

<img width="526" alt="Screenshot 2019-11-12 at 20 26 17" src="https://user-images.githubusercontent.com/36083448/68703415-e727ea80-058a-11ea-814a-e3af3eb7f385.png">

Do you see my point @jbrooksuk ?

**Comment by jbrooksuk** [comment]
Got it.

**Comment by skoyah** [comment]
Thanks mate!
