### ISSUE TITLE
Nova Themes applied to Login but not to dashboard 

### ISSUE THREAD

**Issue by avfigueredo** [laravel/nova-issues#2131]
- Laravel Version: 5.8.35
- Nova Version: 2.6.1
- PHP Version: 7.2.19

### Description

I have generated a nova theme, I can see the theme CSS is applied to the login, but not to the dashboard. I removed the laravel nova and re-installing but the problems continues. It's the same problem as https://github.com/laravel/nova-issues/issues/2093.

I look for the theme file in dashboard source code and i can't find him, but I can see in the login page.

### Steps To Reproduce

    Run php artisan nova:theme {package name}
    Run php artisan vendor:publish

<img width="1403" alt="Screen Shot 2019-11-11 at 11 59 54" src="https://user-images.githubusercontent.com/8737136/68597018-ff104900-047a-11ea-8664-82acf4c89b93.png">
<img width="1395" alt="Screen Shot 2019-11-11 at 12 01 08" src="https://user-images.githubusercontent.com/8737136/68597019-ffa8df80-047a-11ea-817b-abcda4be943d.png">

**Comment by jbrooksuk** [comment]
You've likely published the Nova views. Remove these from `./resources/vendors/nova`.

**Comment by avfigueredo** [comment]
Thanks you!
