### ISSUE TITLE
requesting help text for relations (viewable at details page under title of relation)

### ISSUE THREAD

**Issue by h-zone** [laravel/nova-issues#2133]
Dear devs!

It is possible to implement helpText for relation Belongs/Has/Morph to inform users what is this related data?

Some users in some cases is not understand what they see because, in my  case, i have too many relations. Sometimes similar in name or set of fields...

Thank you!

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
