### ISSUE TITLE
Custom label on Create/Edit resource button

### ISSUE THREAD

**Issue by vayurobins** [laravel/nova-issues#2134]
Hi.
I would really like it if it was possible to write your own custom label on the save button on the create/edit resource page.
I realize there have been improvements here: https://github.com/laravel/nova-issues/issues/203
But I don't need it to read: "Create Invoice" or "Invoice Create". I just need it to say "Save" or "Send" something else that is useful for the case.
Furthermore, I wish it was possible to disable/hide the "Create & Add Another" button.
If anyone has an idea of how I could fix these issues, if they are not implemented in a future version, then I would be very happy. :-)
<img width="559" alt="Screenshot 2019-11-12 at 18 37 12" src="https://user-images.githubusercontent.com/1386354/68668995-053a1e80-057c-11ea-8966-f08006d50f9a.png">

**Comment by jbrooksuk** [comment]
You can customise the translations by editing `resources/vendor/nova/en.json`. But be careful when new translations are published, you'll need to diff them first.

> Furthermore, I wish it was possible to disable/hide the "Create & Add Another" button.

https://github.com/laravel/nova-issues/issues/1620

**Comment by vayurobins** [comment]
Thanks @jbrooksuk, I do realize it is possible to do it as you mention, but that will be global and not only on Invoices. So other resources will be hit by this too, which it should not the intention.
It would be nice to have a unique css class in the body tag for each resource. Like if on the edit invoice resource page, then in the <body class="invoice edit-invoice">, so then one could target css to specific resources.

**Comment by phpMuhammed** [comment]
@vayurobins i look for the same thing if there is any solution
