### ISSUE TITLE
Custom Label for Inline Action Button

### ISSUE THREAD

**Issue by felixgoldstein** [laravel/nova-issues#2135]
Is there a possibility to set a custom label for the action button, specially for the inline action button?
Would make sense in some cases

**Comment by jbrooksuk** [comment]
Are you referring to the `Actions` text or the label of the action itself?

![image](https://user-images.githubusercontent.com/246103/68671133-837bce00-0546-11ea-82e3-dbf1e1c6218e.png)

**Comment by felixgoldstein** [comment]
@jbrooksuk i'm referring to the `Actions` text

**Comment by jbrooksuk** [comment]
You can override the `resources/lang/vendor/nova/en.json` file.

**Comment by felixgoldstein** [comment]
okay, but this will change the label of all action buttons, i'm lookin for a solution for single nova models
