### ISSUE TITLE
Nova not working in subdirectory.

### ISSUE THREAD

**Issue by timersys** [laravel/nova-issues#2136]
I have my laravel app inside a subdirectory like this:
mydomain.com/app/ and nova installed in mydomain.com/app/nova/

I tried changing path to 'app/nova/' in nova config and also tried adding 'domain' => 'app' and I can't make it work. All the routes return 404 no matter which variation I try.

It's possible to use it on a subdirectory?

- Laravel Version: 6.0
- Nova Version: 2.0
- PHP Version: 7.2

**Comment by jbrooksuk** [comment]
Sub-directories are not supported officially.

**Comment by timersys** [comment]
It would be nice to specify it in the docs so we don't spend hours trying.

**Comment by RobbeReygel** [comment]
Are there any plans to support this in Nova 4? Or is there a patch available anywhere like [this one for Nova 3](https://gist.github.com/chinleung/2e9f6a9496ded8cd6fadc829b0030229)

**Comment by crynobone** [comment]
There is no plan to support this when Laravel itself doesn't support such feature officially. https://laravel.com/docs/10.x/installation#directory-configuration
