### ISSUE TITLE
->required() not working on fields in actions

### ISSUE THREAD

**Issue by timcv** [laravel/nova-issues#2137]
- Laravel Version: 6.5.1
- Nova Version: 2.7.0

### Description

The ->required() method is not working on fields in actions

->rules('required') is working.

### Steps To Reproduce

```
Textarea::make('Field 1', 'field_1')
    ->rules('required'),
Textarea::make('Field 2', 'field_2')
                ->required(),
```

Field 2 will not trigger the field validation.

**Comment by jbrooksuk** [comment]
The `required` method adds a visual indicator to the field (the * that you're seeing by the field name). You need to combine this with the `rules('required')` as in your first field.

See the [original PR](https://github.com/laravel/nova/pull/659) for more info.
