### ISSUE TITLE
Method Illuminate\Database\Query\Builder::getPivotClass does not exist.

### ISSUE THREAD

**Issue by ack202** [laravel/nova-issues#214]
Hello,

I am struggling to get the Role Model working. User and Role Classes are defined. 
There is a "users" table, "roles" table and "role_user" table to match the user_id and role_id.
The User is "BelongsToMany::make('Roles')," and the Role "BelongsToMany::make('Users'),".
Whenever I load the detail view of a User or Role the following error appears: 
**Method Illuminate\Database\Query\Builder::getPivotClass does not exist.**
Any idea?

**Comment by drehimself** [comment]
Try setting both relationships in your models.

An example between Orders and Products (Belongs to many relationships)

Order.php
```php
public function products()
{
    return $this->belongsToMany('App\Product')->withPivot('quantity_item');
}
```

Product.php
```php
public function orders()
{
    return $this->belongsToMany('App\Order')->withPivot('quantity_item');
}
```

**Comment by ack202** [comment]
Solved it! Thank you 👍
