### ISSUE TITLE
Make any file based field cloneable

### ISSUE THREAD

**Issue by addgod** [laravel/nova-issues#2141]
- Laravel Version: 6.5.1
- Nova Version: 2.7.0
- PHP Version: 7.2.24

### Description:
Any file based field, is not cloneable. So they cannot be used with any dynamic content field ( eg. spaties translation field, whitecubes Flexible Content and so forth )

### Steps To Reproduce:
Create an image field, then clone it. After the thumbnail image will not be visible, since the value is referenced in a closure, that is created on construction, that then references the original fields value.

### Note:
I have a solution, and will create a PR shortly.

**Comment by jbrooksuk** [comment]
@addgod thanks, but why are you cloning fields? What's the use case here?

**Comment by davidhemphill** [comment]
Closed due to inactivity. If the issue still persists, feel free to post a new issue with the requested information above. Thanks!
