### ISSUE TITLE
Reset ordering/sorting

### ISSUE THREAD

**Issue by Sinnbeck** [laravel/nova-issues#2142]
Maybe I am missing something obvious, but is there a way to make it possible to clear the sorting after it has been set? Clicking on the column name multiple times just flips the sorting.

If this isn't possible out of the box I will send it in as suggested feature. 

Using something like https://github.com/optimistdigital/nova-sortable requires the table to not be sorted, but there is no way of resetting the sorting without clicking the menu again.

**Comment by AforDesign** [comment]
According to crynobone the reset should be implemented, but how does it work?

I don't see any reset button and can't find anything in Nova's documentation.

**Comment by crynobone** [comment]
> Maybe I am missing something obvious, but is there a way to make it possible to clear the sorting after it has been set? Clicking on the column name multiple times just flips the sorting.

What's requested has been implemented.

------ 

First click sort by ascending

![image](https://user-images.githubusercontent.com/172966/114165137-b35b1b00-995e-11eb-94c1-bdaa0dffac94.png)

Second click sort by descending

![image](https://user-images.githubusercontent.com/172966/114165190-c372fa80-995e-11eb-99f5-316c1eae1227.png)

The third click reset the sort

![image](https://user-images.githubusercontent.com/172966/114165269-d7b6f780-995e-11eb-92d2-ceda4360e912.png)

**Comment by AforDesign** [comment]
Thanks for the quick reply, crynobone.

The third click only removes the sorting direction, not the sorting itself.
If you check the url, you'll find that the sorting is still active (in a way).
