### ISSUE TITLE
Cannot update with Sparkline

### ISSUE THREAD

**Issue by Sinnbeck** [laravel/nova-issues#2143]
- Laravel Version: 6.5.1
- Nova Version: 2.7.1
- PHP Version: 7.3
- Database Driver & Version:
- Operating System and Version: Homestead
- Browser type and version:Chrome

### Description:
Cannot update a resource when Sparkline is added

### Steps To Reproduce:
Add Sparkline to a resource and try to save in Nove. 
This is my Sparkline test
```
Sparkline::make('Post Views')->data([1, 2, 3, 4, 4, 6]),
```
It throws this error in the console.
```
Cannot read property 'status' of undefined
```
I have run `php artisan nova:publish --force`

**Comment by jbrooksuk** [comment]
Confirmed.

I'm pushing a fix now which will set the field to be hidden on the create and update forms.

Temporary fix is to do this:

```php
Sparkline::make('Post Views')->data([1, 2, 3, 4, 4, 6])
                ->hideWhenCreating()
                ->hideWhenUpdating(),
```
