### ISSUE TITLE
Style can't be found

### ISSUE THREAD

**Issue by gizburdt** [laravel/nova-issues#2144]
- Laravel Version: 6.5.1
- Nova Version: 2.7.1
- PHP Version: 7.3
- Database Driver & Version: Mysql (valet)
- Operating System and Version: macOS 10.13
- Browser type and version: Chrome 78.0.3904
- Reproduction Repository: https://github.com/###/###

### Description:

Since I updated from 2.6 to 2.7.1, the custom styles cannot be found. I use this code:

`Nova::style('extra', asset('css/extra.css'));`

Then I get this error in the browser:

`GET http://project.test/nova-api/styles/nova net::ERR_ABORTED 500 (Internal Server Error)`
`The file "http://project.test/css/extra.css" does not exist`

I ran `nova:publish` ;)

Thanks, and very nice work on Nova!! :)

**Comment by jbrooksuk** [comment]
You should probably be using:

```php
Nova::style('extra', public_path('css/extra.css'));
```

**Comment by gizburdt** [comment]
Thanks, worked! :)
