### ISSUE TITLE
Error When Creating Nova Admin Using nova:user

### ISSUE THREAD

**Issue by rehamwalid** [laravel/nova-issues#2145]
- Laravel Version: 5.8.*
- Nova Version: 2.0.9
- PHP Version: 7.3
- Operating System and Version: Linux Mint 

### Description:
I am trying to create Nova Admin with command 'php artisan nova:user' but it gives me this error 

< Too few arguments to function Illuminate\Database\Eloquent\Model::setAttribute(), 1 passed in /var/www/new-avenue/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php on line 617 and exactly 2 expected >

Any idea why this happens 

Thank you

**Comment by jbrooksuk** [comment]
@rehamwalid did you solve this? P.s. you're using an out=dated version of Nova.
