### ISSUE TITLE
Change custom dashboard title

### ISSUE THREAD

**Issue by drashoor** [laravel/nova-issues#2146]
I need to change the title of custom dashboard..

![image](https://user-images.githubusercontent.com/6551562/68864931-946d4080-06fa-11ea-9d81-dc118ef0852d.png)

**Comment by jbrooksuk** [comment]
You can override the `label` method on your Dashboard class.

**Comment by ekandreas** [comment]
Custom dashboards will still use the word "Panel" in Laravel Nova 2.7.1

**Comment by jbrooksuk** [comment]
You can override the translation for it.
