### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by slavarazum** [laravel/nova-issues#2147]
- Laravel Version: 5-6
- Nova Version: 2.7, 2.1, 2.0.1

### Description:

Related to this question - https://twitter.com/razumartisan/status/1194947387002933248

I'm developer of https://github.com/froala/nova-froala-field and already have 3 cases when Nova updates has BC in minor and patch releases:

1. https://github.com/froala/nova-froala-field/issues/44 `Trix::withFiles` method signature has been changed in 2.7 version

2. https://github.com/froala/nova-froala-field/issues/31
In Nova 2.1 added `FieldElement::showOnIndex` method with new signature

3. https://github.com/froala/nova-froala-field/issues/18
In 2.0.1 version, getting of resource name changed from `$this->resource` to `$this->route('resource')` which breaks behavior when sending resource name as parameter

**Comment by davidhemphill** [comment]
Extending a field and then its internals changing to fix bugs does not qualify as breaking changes. There is no contract provided to extend Nova's built-in fields.

**Comment by pelmered** [comment]
@davidhemphill I definitely consider changing method signatures for protected methods and properties on classes that you are supposed to extend to be breaking changes. The fact that you document that you should extend the fields by extending the classes should be considered a contract. If you want to be able the change these signatures without a new major version you should make them private.  

I have had similar problems on multiple occasions and it should be considered a BC. There is nothing weird in the code, we are just using the methods and properties that you provide when we are extending Nova.
