### ISSUE TITLE
Global search - send to "Edit" screen

### ISSUE THREAD

**Issue by ethanclevenger91** [laravel/nova-issues#2148]
The global search goes to the "View" screen for a resource by default with no option for configuration. I imagine for some Nova applications, the "View" screen is fairly inconsequential / never used, and most users are spending 99% of their time editing resources. It'd be great to configure this to go to the "Edit" screen instead for such cases.

**Comment by dillingham** [comment]
https://github.com/dillingham/nova-redirect-detail

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
