### ISSUE TITLE
Relational metadata is no longer merged during serialization

### ISSUE THREAD

**Issue by ralphschindler** [laravel/nova-issues#2149]
- Laravel Version: 5.8.35
- Nova Version: 2.7.1
- PHP Version: 7.3.11
- Database Driver & Version:
- Operating System and Version: n/a
- Browser type and version: n/a
- Reproduction Repository: https://github.com/###/###

### Description:

Between 2.6.0 and 2.7.x, a change was made to the Relational fields where the meta() was changed to a jsonSerialize(). In this change, the ability to merge overrides or arbitrary meta[] was lost.

This was found as a result of this issue in a 3rd party package:
https://github.com/eminiarts/nova-tabs/issues/69

### Steps To Reproduce:

Try to use nova-tabs.

### Patch

[fix-relational-meta.patch.txt](https://github.com/laravel/nova-issues/files/3849120/fix-relational-meta.patch.txt)

**Comment by ralphschindler** [comment]
In the case of the `nova-tabs` package, it takes advantage of the ability to override `listable` and make the value `false` instead of the default of `true`. This is the required thing to delegate handling of table to the nova-tabs `DetailTabs` component.

**Comment by davidhemphill** [comment]
I think this is fixed in the recently merge laravel/nova#718.

**Comment by ralphschindler** [comment]
@davidhemphill when do you feel like there might be a new release being cut? 😁
