### ISSUE TITLE
The name attribute in Nova's action cannot be Chinese

### ISSUE THREAD

**Issue by alex-liu-sudo** [laravel/nova-issues#2150]
- Laravel Version: 5.8
- Nova Version: 2.6.1
- PHP Version: 7.3

### Description:
When the name attribute of my action is Chinese, triggering this method will generate an exception, as shown in the figure below：
![image](https://user-images.githubusercontent.com/32171158/68912286-af8b8f00-0792-11ea-998c-11ef56eb05d3.png)
![image](https://user-images.githubusercontent.com/32171158/68912295-bb775100-0792-11ea-8528-cb872755c632.png)
![image](https://user-images.githubusercontent.com/32171158/68912300-bf0ad800-0792-11ea-9a61-3a438c52a11c.png)

**Comment by davidhemphill** [comment]
Try overriding the `uriKey` method of the `Action` to return an English label and see if that helps. Interested to see what's going on there.

**Comment by jbrooksuk** [comment]
Found the bug! Making a PR now.
