### ISSUE TITLE
Reduce auto-load all scripts by third-party packages in Nova

### ISSUE THREAD

**Issue by phoenixg** [laravel/nova-issues#2151]
Laravel Version: 5.8
Nova Version: 2.7.1
PHP Version: 7.1

Each time when page loads, Nova loads all scripts, no matter if is used.

![image](https://user-images.githubusercontent.com/990040/68927516-e6799900-07c2-11ea-8149-0902b8494a1f.png)

**Comment by rikless** [comment]
You can add cache management on the server side.

**Comment by jbrooksuk** [comment]
In v2.7.1 scripts and styles are now cached via the `CheckResponseForModifications` middleware.

**Comment by rikless** [comment]
@jbrooksuk In the issue description (this one), you can see it's on nova 2.7.1.

You should have a look at this : https://github.com/laravel/nova-issues/issues/2117#issuecomment-553310302
