### ISSUE TITLE
Place Field Language

### ISSUE THREAD

**Issue by ChrisEbner** [laravel/nova-issues#2152]
Hello everyone. I'm posting this as a feature request in hope it can be added without a lot of effort as it is part of the algolia places api.

Please add the option to define the language usage, so that algolia can return the place in the language that is needed in the application.

**Comment by jbrooksuk** [comment]
Labelled as a bug because Nova can be translated, so this field should be too.

**Comment by m-lotze** [comment]
@jbrooksuk it should default to the app.locale, not just have the ability to set the language. also the date field is missing translations completely: https://github.com/laravel/nova-issues/issues/1889#issuecomment-542624332
