### ISSUE TITLE
Resource index query doesnt play nice with filter joins

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [laravel/nova-issues#2153]
- Laravel Version: 5.8.35
- Nova Version: 2.3.2 ?
- PHP Version: 7.3
- Operating System and Version: MacOS 10.14.3
- Browser type and version: Chrome 77

### Description:
Im finding that since the index query of resources appears to be a simple `SELECT * FROM table`, if any of my filters have a join on them, I end up with 2 `id` columns in my result set, the `id` from the resources table, and the `id` from the joined table. This messes up the IDs in the resources index view, including the edit/view/delete buttons

Wouldnt it be safer to make the default resource index query `SELECT table.* FROM table`?

**Comment by dkulyk** [comment]
If you are filtering by relation best way is using whereHas

**Comment by matthewjumpsoffbuildings** [comment]
I understand that is an option, but when you have a large number of filters that rely on a related table, performance wise it makes more sense to do a single join and filter based on that.
