### ISSUE TITLE
BelongsTo Relationship isCallableArray on Select Field Returning Object Error

### ISSUE THREAD

**Issue by DerekBuntin** [laravel/nova-issues#2154]
- Laravel Version: 6.5.1
- Nova Version: 2.7.1
- PHP Version: 7.3
- Database Driver & Version: MySQL
- Operating System and Version: Mac Catalina
- Browser type and version: Chrome

### Description:
After upgrading Nova from 2.6.1 to 2.7.1 there was a new method added to the select field:

`protected function isCallableArray($options)
    {
        return $this->isCountable($options) && ! Arr::isAssoc($options) && method_exists($options[0], $options[1]);
    }`

This has caused the BelongsTo Nova Field and select fields to return an error:

> [2019-11-17 06:10:40] local.ERROR: Argument 1 passed to Illuminate\Support\Arr::isAssoc() must be of the type array, object given, called in /xxxxx/vendor/laravel/nova/src/Fields/Select.php on line 37 {"userId":1,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 1 passed to Illuminate\\Support\\Arr::isAssoc() must be of the type array, object given, called in /xxxxx/vendor/laravel/nova/src/Fields/Select.php on line 37 at /xxxxx/vendor/laravel/framework/src/Illuminate/Support/Arr.php:353)

Nothing has changed with exception to this addition and when I comment out the return value everything works as expected.

### Steps To Reproduce:
Update Nova to 2.7.1 and visit a nova resource that has either a select or BelongsTo field that populates the field values.

**Comment by davidhemphill** [comment]
Can you provide the exact code example that causes the error for you? That will help us diagnose the issue.

**Comment by DerekBuntin** [comment]
Hi David,

On my Nova resource App\Nova\Article I have a BelongsTo field which allows the selection of a category:

`BelongsTo::make('Category', 'category', 'App\Nova\Category')
                ->viewable(false),`

On the Article model App\Article I have a 'category' method, which is referenced in the above belongsTo field:

`public function category(){
        return $this->belongsTo(Category::class);
    }`

Also, on the Category Nova resource, I have a select field that populates the select field values/names with a database call from the category, this also returns the same error:

`Select::make('Parent', 'parent_id')
                ->options(Category::all()->pluck('name', 'id'))
                ->nullable()
                ->onlyOnForms(),`

This all worked perfectly before the latest Nova update and I can see the new method added to the select field on the last update but doesn't work for me unless I comment out the return value of that method.

Does this help?

**Comment by davidhemphill** [comment]
I'm not able to replicate this bug using the code you've provided. Everything seems to work when using a `Collection` as the options. It does seem like you're using a third-party field (the `viewable` method is not defined in our `BelongsTo` or any base class), so I would disable those first.

**Comment by dkulyk** [comment]
Confirmed. @davidhemphill you catch this when collection have 2 items.

**Comment by davidhemphill** [comment]
Closed via laravel/nova@2065710843b790fbae605627ac6a7154ba7d1249
