### ISSUE TITLE
Active inactive user 

### ISSUE THREAD

**Issue by kephren226** [laravel/nova-issues#2155]
Hello 
Is there a way to deactivate a user in nova ?
Or modify the login controller to check if user is active

**Comment by jbrooksuk** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](https://larachat.co/).
