### ISSUE TITLE
Laravel Nova not work perfectly after uploaded in server

### ISSUE THREAD

**Issue by spamrepos** [laravel/nova-issues#2156]
- Laravel Version: 5.8
- Nova Version: 2.0
- PHP Version: 7.1.3
- Database Driver & Version: MySQL
- Operating System and Version: Win10 Home SL
- Browser type and version: Chrome

### Description:
Hi there, 
I have problem about this nova, after I uploaded in vps, nova not work perfectly
Sidebar link not work, the card not show up in the dashboard, and profile pics crash.
I tried to composer update, php artisan route:clear, but the problem still got there,

<img width="954" alt="kazana" src="https://user-images.githubusercontent.com/57053799/69003374-5d35a400-0933-11ea-9824-13f0c279cf90.png">

But fortunately, in local this app work perfectly, 
Please help me!

**Comment by jbrooksuk** [comment]
Make sure that the public assets have been uploaded too.

**Comment by jbrooksuk** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](https://larachat.co/).
