### ISSUE TITLE
Base table or view not found: 1146

### ISSUE THREAD

**Issue by dmgdwd** [laravel/nova-issues#2157]
- Laravel Version: 6.x
- Nova Version: 2.6.1
- PHP Version: 7.3
- Database Driver & Version:
- Operating System and Version: macOS 10.14.5
- Browser type and version: FireFox

### Description:
> Base table or view not found: 1146 Table
> 'newsim_yrpixakb.action_events' doesn't exist (SQL: insert into
> `action_events` (`batch_id`, `user_id`, `name`, `actionable_type`,
> `actionable_id`, `target_type`, `target_id`

Nova is trying to use the tenant database to add the action events informatiuon.

I have a multiple client app and it works like this
All clients login at example.com and based on their information they only see what they need to see.  In the system main database I have Users, Pages, etc where clients only see Users Resource and only users associated with their org_id

Each client has a different database to view their members, events, items tables. I change databases with this code in each model.  The auth()->user()->dbname is used here so super admins can move between clients for client support.

    public function __construct() {
        parent::__construct();
        if(auth()->user()->dbname) {
            Config::set('database.connections.tenant.database', auth()->user()->dbname);
            $this->connection = 'tenant';
        }
    }

Now I am trying to add a new client then add a database and migrate. I can do this from a custom artisan command but would like to use the add Client button in nova. So I've add this to the User model and all works except the error message.

    public static function boot()
    {
        parent::boot();
    
        static::creating(function($user){
            $user->active = 1;
            $user->org_id = self::nextOrgId();
            $user->dbname = $user->createNewDatabaseName();
            $user->aps_token = Str::random(32);
        });
        static::created(function($user) {
            $user->createNewClientDatabase();
        });
        static::updating(function($user) {
            $user->syncClientFields();
        });
    }

    public function createNewClientDatabase() {
        $systemDB = env('DB_DATABASE');
        $charset = config("database.connections.mysql.charset",'utf8mb4');
        $collation = config("database.connections.mysql.collation",'utf8mb4_unicode_ci');
        $query = "CREATE DATABASE IF NOT EXISTS $this->dbname CHARACTER SET $charset COLLATE $collation;";
        try {
            \DB::statement($query);
        }catch (\Exception $e) {
            return $e->getMessage();
            exit;
        }

        Config::set('database.connections.mysql.database', $systemDB);
        \DB::purge('mysql');

        Config::set('database.connections.tenant.database', $this->dbname);
        \DB::purge('tenant');
        Artisan::call('migrate', [
            '--database' => 'tenant',
            '--path' => 'database/NewClient'
        ]);
    
    }

**Comment by jbrooksuk** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](https://larachat.co/).
