### ISSUE TITLE
authorizedToCreate viaResource

### ISSUE THREAD

**Issue by anditsung** [laravel/nova-issues#2158]
```
public static function authorizedToCreate(Request $request)
    {
        if($request->get("viaResource")) {
            return false;
        }
        return true;
    }
```

if the resource is access viaResource it will return false but the button still showing. 

```
public static function authorizedToCreate(Request $request)
    {
        return false;
    }
```
if change to this, the create button will not show on resource and viaResource

**Comment by davidhemphill** [comment]
Please be more clear with what your problem is and steps to reproduce the issue. The issue template is there to guide you into providing the best information for us to help out. When you get that, feel free to post a new issue.

**Comment by DragoshDX** [comment]
I am having the same issue. 

I think it is valid, the problem OP has is that even though the function returns true, the system still doesn't correctly create the resource.

**Comment by crynobone** [comment]
@DragoshDX Please provide a full description as mention in the Issue guideline in order for us to understand the issue, best to create new issue.
