### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by Daafie** [laravel/nova-issues#216]
I am getting the validation error returned and can see them in the network tab, but they are not being displayed?

**Comment by smayzes** [comment]
Might be helpful to share how you are doing the validation in your Resource Fields.

**Comment by DSpeichert** [comment]
I am also not getting any feedback on the form about what went wrong. Using the regular Nova `->rules('max:10')` validation.

**Comment by smayzes** [comment]
@DSpeichert I think it expects an array? I've been doing `->rules(['max:10'])` 

Now I haven't tried max, yet. Just `required`

**Comment by DSpeichert** [comment]
I think it's not even important how the validation is done server-side.
The important part is how the errors are returned with the 422 Exception.

What I found out by inspecting Vue client-side code in Nova is that your `app\Exceptions\Handler.php` must have something like this in the `render()` function:

```php
/**
 * Render an exception into an HTTP response.
 *
 * @param  \Illuminate\Http\Request $request
 * @param  \Exception               $e
 * @return \Illuminate\Http\Response
 */
public function render($request, Exception $e)
{
    if ($request->wantsJson() || $request->isJson()) {
        if ($e instanceof ValidationException)
           // most important part -> errors returned under "errors" key!
           return response()->json(['message' => $e->getMessage(), 'errors' => $e->validator->getMessageBag()], 422);
        // ... all other cases cut from here
        else
            return response()->json(['message' => $e->getMessage()], 500);
    } elseif ($e instanceof HttpException) {
        // this is example
        if (view()->exists('errors.' . $e->getStatusCode()))
            return response()->view('errors.' . $e->getStatusCode(), ['exception' => $e], $e->getStatusCode());
    }

    return parent::render($request, $e);
}
```

Basically, the response JSON **MUST** include: ` 'errors' => $e->validator->getMessageBag()`

**Comment by davidhemphill** [comment]
We are unable to debug your issue without a reproducible code example.

**Comment by OwenMelbz** [comment]
@davidhemphill @taylorotwell @themsaid as @DSpeichert said - if you have a custom render method in your app for your frontend, then Nova breaks.

Nova relies on your frontend code having

```php
if ($request->wantsJson() || $request->isJson()) {
        if ($e instanceof ValidationException)
           // most important part -> errors returned under "errors" key!
           return response()->json(['message' => $e->getMessage(), 'errors' => $e->validator->getMessageBag()], 422);
        // ... all other cases cut from here
        else
            return response()->json(['message' => $e->getMessage()], 500);
    } elseif ($e instanceof HttpException) {
        // this is example
        if (view()->exists('errors.' . $e->getStatusCode()))
            return response()->view('errors.' . $e->getStatusCode(), ['exception' => $e], $e->getStatusCode());
    }

    return parent::render($request, $e);
```

If you have something which doesn't do the `return response()->json(['message' => $e->getMessage(), 'errors' => $e->validator->getMessageBag()], 422);` Then it errors.

Novas error handling should be separate from the frontend otherwise it defeats the point of "you can just drop it in"
