### ISSUE TITLE
Unable to edit pivot fields

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [laravel/nova-issues#2161]
- Laravel Version: 5.8.35
- Nova Version: 2.7.1
- PHP Version: 7.2.24
- Operating System and Version: MacOS 10.14.6
- Browser type and version: Chrome 78

### Description:
I have a `Track` resource with a belongsToMany relationship to `Artists` via a pivot table with an extra column `order`, set up in the model like so

```php
public function artists()
{
	return $this->belongsToMany(Artist::class)
		->withPivot('order')
		->orderBy('order');
}
```

In my `Track` resource I have the following in my `fields` definition
```php
BelongsToMany::make('Artists')->fields(function () {
	return [
		Number::make('Order', 'order')
	];
})->searchable(),
```
In the `Track` detail page, in the attached `Artist` section, the 'order' column does show up, and the attached items are correctly ordered by the `order` column. This is an example of my detail page

![image](https://user-images.githubusercontent.com/41524/69263055-7761d180-0c14-11ea-8c43-6795b3cca39b.png)

However, when I try and attach a new `Artist` to the `Track`, or edit an already attached one, the `order` field doesnt appear on the edit form? All I see is an input to pick the artist, eg

![image](https://user-images.githubusercontent.com/41524/69262640-c3f8dd00-0c13-11ea-93ee-20d79bd9fee8.png)

Surely the `order` value should appear for editing in the attach edit forms? Also why does the selection for which Artist to attach default to the dropdown? I will have thousands of Artists in the db, how do I change what field is shown for the Artist?

**Comment by matthewjumpsoffbuildings** [comment]
What should happen is something like this
![image](https://user-images.githubusercontent.com/41524/69092709-e74d4c00-0a9c-11ea-9491-78b7e9f688e1.png)
![image](https://user-images.githubusercontent.com/41524/69092744-f8965880-0a9c-11ea-976b-e5cc6ce5f9b6.png)

I showed both the Attach and Create options in the detail view by removing the `v-else-if` in the `CreateResourceButton.vue` component, and turns out the Create view when accessed via that relationship DOES show the pivot field, but saving fails because it attempts to save the `order` field to the `Artist` model, instead of the pivot table.

**Comment by jbrooksuk** [comment]
@davidhemphill has already started to implement this in https://github.com/laravel/nova/pull/697
