### ISSUE TITLE
Misleading docs, terrible implementation regarding belongsToMany relationships

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [laravel/nova-issues#2162]
- Laravel Version: 5.8.35
- Nova Version: 2.7.1
- PHP Version: 7.2.24
- Operating System and Version: MacOS 10.14.6
- Browser type and version: Chrome 78

### Description:
The docs on relationships show this image

![image](https://nova.laravel.com/docs/assets/img/detail-relationships.92c1ded1.png)

Which make it seem like you can easily create AND attach a resource

In reality it seems that the `CreateResourceButton.vue` is set up to only show the Attach button for relationships on the detail view. Which sends you to the Attach view, which doesnt allow creating a new resource.

Currently if I want to attach a related resource and it doesnt exist, I have to leave the detail page of the resource Im viewing, go to the index page of the other resource, create it, go back and find the resource I want to attach it to, click the attach button, and find the newly created resource to attach. This is so ridiculously long-winded, and there are no decent addons for this. In reality there shouldnt have to be addons.

Issue https://github.com/laravel/nova-issues/issues/2161#issuecomment-555205385 shows some images of what SHOULD happen, a Create button which takes you to a Create view with both the related resources fields, and any pivot fields

Or is it the case that the docs are not misleading and my version of Nova is outdated?

**Comment by matthewjumpsoffbuildings** [comment]
Ok so, if a BelongsToMany relationship _doesnt_ have any pivot fields on the related model, simply replacing the `CreateResourceButton.vue` `v-else-if="shouldShowCreateButton"` with a `v-if="shouldShowCreateButton"`, works perfectly.

Eg on a resources detail view, next to the Attach button, is a Create button, which when clicked takes you to the form view for the related resource, and on submission, not only does it create and attach the new related resource, but it also redirects you back to the original resource...

**Comment by michaelsabatino** [comment]
This would be a hugely valuable change and it's disappointing that belongsToMany is so awkward. There are so many setups where this would benefit. My situation is a classic User/Role setup which is about as common as it gets. It's a no-brainer that we should be able to select/attach a Role when creating a User.

**Comment by FaridAghili** [comment]
It's a pain to to work with ManyToMany relations in Nova, honestly :|

**Comment by martinhummer** [comment]
This package helped me a lot:
https://novapackages.com/packages/benjacho/belongs-to-many-field

Thanks to @Benjacho

**Comment by matthewjumpsoffbuildings** [comment]
@martinhummer that package does resolve some of the pain points working with relations in nova, but really the core issues of confusing implementation and docs still persist

**Comment by Benjacho** [comment]
@matthewjumpsoffbuildings i already updated docs, but isn't the best docs by far.
