### ISSUE TITLE
Fail to sort field when using pivot data

### ISSUE THREAD

**Issue by milewski** [laravel/nova-issues#2163]
Hello, making any column sortable fails when using a pivot field:

```php
Text::make('Date', 'pivot->created_at')
    ->sortable()
    ->displayUsing(function (Carbon $date) {
        return $date->toDateString();
    }),
```

When clicking on the sortable icons it tries to access this url:

![image](https://user-images.githubusercontent.com/2874967/69116185-5d19dd80-0ac6-11ea-9c0e-8100247c20d3.png)

```
https://nova.docker.localhost/resources/clients/1?triedOn_order=pivot-%3Ecreated_at&triedOn_direction=asc
```

And the db fail because it tries to lookup a field called `Pivot`

![image](https://user-images.githubusercontent.com/2874967/69116123-2348d700-0ac6-11ea-8aa7-53d212b7344f.png)

**Comment by davidhemphill** [comment]
Sorting via a pivot column is not supported at this time.
