### ISSUE TITLE
Resource relation PopOver

### ISSUE THREAD

**Issue by sirikkoster** [laravel/nova-issues#2164]
It would be nice to define a Popover functionality when hovering the name of a relation.

- Popover title (optional)
- Popover content

**Comment by jbrooksuk** [comment]
@sirikkoster can you please give some more information here? What would you want to display in the tooltip and why?

**Comment by sirikkoster** [comment]
> @sirikkoster can you please give some more information here? What would you want to display in the tooltip and why?

@jbrooksuk I'll Explain
In my application I have records with rules and regulations. in the resource overview you'll have a list with records with for example a regulation code like 'CD808', now I must click each "relation" to see is the regulation is applicable.

It  would be awesome tot mouseover of whatever the action trigger would be to show the popover to see quickly if the regulation is applicable. It would save a lot of time, and makes the application more user friendly.

**Comment by sirikkoster** [comment]
Is there any progress on this?
