### ISSUE TITLE
Response class of asset endpoints break middleware

### ISSUE THREAD

**Issue by gerardnll** [laravel/nova-issues#2165]
- Laravel Version: 6.5.1
- Nova Version: >=2.7.0
- PHP Version: 7.3.11
- Database Driver & Version: PostgreSQL
- Operating System and Version: macOS 10.15.1 and Debian 9
- Browser type and version: Chrome 78
- Reproduction Repository: 

### Description:

[This pull request](https://github.com/laravel/nova/pull/701) broke the 'withHeaders()' function I have in a Middleware because the ResponseTrait is not in the `Symfony\Component\HttpFoundation\BinaryFileResponse` but in the `Illuminate\Http\Request`.

This function is expected to exist as documented in https://laravel.com/docs/6.x/responses#attaching-headers-to-responses

### Steps To Reproduce:

Put this code in a Middleware that runs when an asset URL like 'hxxps://backend.website.com/nova-api/scripts/tool-name' is called:

```
return $next($request)->withHeaders([
    'X-Throw-Exception' => 'true'
]);
```

It will break because response is an object of class `Symfony\Component\HttpFoundation\BinaryFileResponse`.

**Comment by dkulyk** [comment]
You should use `$response->headers->set('X-Throw-Exception', 'true');`

**Comment by gerardnll** [comment]
I know how to fix it. I just don't understand if AFAIK all Laravel middleware return an object of class 'Illuminate\Http\Request' why this route doesn't. As I point out, this way of handling headers is documented in the Laravel docs.
