### ISSUE TITLE
ActionEvent : database error (wrong columns' types)

### ISSUE THREAD

**Issue by tonyyb** [laravel/nova-issues#2166]
- Laravel Version: v5.8.35
- Nova Version: v2.6.1 (and more)
- PHP Version: 7.3.2
- Database Driver & Version: Mysql 5.7

### Description:
`action_events` table has `original` and `changes` columns with `text` format.

If a model has an attribute with `longtext` you can have following error : 

`SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'original' at row 1 (SQL: insert into `action_events ...`

or

``SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'changes' at row 1 (SQL: insert into `action_events ...``

### Steps To Reproduce:

Create a resource and a model with a `foo` attribute with `longText` format in DB.
Update your resource with Nova Form and put a lot of content on `foo` field.

### Solutions :

* Alter `changes` and `original` columns types to `longtext`
* Add possibility to exclude some attributes in ActionEvent logging (and / or a Model ?)

**Comment by jbrooksuk** [comment]
It's advised that you run your own migrations for anything that is non-standard usage.

**Comment by tonyyb** [comment]
@jbrooksuk I don't understand .. Using a `longtext` type on an attribute is a non-standard practice ?

**Comment by jbrooksuk** [comment]
No, but the default `action_events` does not use `longText` and so you should write a custom migration that matches your needs.

**Comment by angauber** [comment]
:dancer:

**Comment by tonyyb** [comment]
So the code should at least throw an Exception ?

For the moment Nova doesn't supports longText and it's a bug.

Documentation should warns this point.

I can make a PR if needed ...

**Comment by jbrooksuk** [comment]
No, we provide "sane" defaults and you can customise as needed. This is the same as some people using UUIDs.

**Comment by gross-nvs** [comment]
Hi,

At least the ability to exclude some attributes/models would be a nice addition to keep these "sane" defaults and avoid a migration.

Truth is using `longtext` is indeed not a great idea as there is many cases where we just don't need to log every differences. 
For example, I would definitely like to avoid logging data/fields that may be subject to GDPR.

**Comment by yannisc** [comment]
I had the same problem. I think in my case the problem is that my db is in Greek and converting to unicode entities makes the content too big to contain in a test field. I changed manually the fields original and changes to LongText and is now working.

I agree that this is a bug that should be resolved.

**Comment by eugenevdm** [comment]
>  we provide "sane" defaults

Granted, but this problem can occur not because you have "pasted a lot of text" in a small field, but rather, you have an image in the field.
