### ISSUE TITLE
Select field with custom option doesn't bind selected value

### ISSUE THREAD

**Issue by meyer59** [laravel/nova-issues#2168]
- Laravel Version: 6.5.2
- Nova Version: 2.7.1
- PHP Version: 7.3.5
- Database Driver & Version: mysql 5.7.26
- Operating System and Version: debian
- Browser type and version: Chrome 78

### Description:
When i update/edit a resource with the select field with custom option list, nova does'nt bind the model value to the select. Nova should fill the actual value of the model
My `Select` field: 
` Select::make('menu_lock')->options([1 => 'enable', 0 => 'disable'])->displayUsingLabels()->nullable()`
The result when editing a resource: 
![image](https://user-images.githubusercontent.com/9505463/69342640-40b7a580-0c6c-11ea-95fd-a67d592b50e2.png)

### Steps To Reproduce:
-create a select field with custom options list 
-create a resource, save it
-edit the resource, save.
-try to edit the same resource again, the previous value is not `selected` int the select

**Comment by meyer59** [comment]
Found the solution. In my model i was casting the atttribut to `bool`, so the solution was to have `true` and `false` between quotes like that `->options(['true'=> 'enable', 'false' => 'disable'])`

**Comment by jbrooksuk** [comment]
Heh, I was just about to reply to this.

**Comment by meyer59** [comment]
Sorry but i thouth it was fixing my issue but nope i was wrong

**Comment by jbrooksuk** [comment]
Yeah, you need to cast it to a string or do this:

```php
Select::make('Active')->options(['1' => 'Enabled', '0' => 'Disabled'])->displayUsingLabels()->resolveUsing(function ($active) {
    return (string) $active;
})->nullable(),
```
