### ISSUE TITLE
How to create custom resource view for Group Menu in Tools

### ISSUE THREAD

**Issue by bartakke** [laravel/nova-issues#2171]
### Description:
hii,
My intended goal is to group multiple resource under one tool on the sidebar with customize name. i want multiple tools like this.
for that purpose I have used Nova Resource Group Menu to group. then i added my resources to this group. it works well as functionally for tool but it has some issues as I am facing
1. I want multiple tools on sidebar  with customize tool name on the side bar with different icons. currently it comes with only one name as "Other" on the sidebar.
2. also want to change view of subgroups. this has very weird view as my client never  accepts views like this . 

![Annotation 2019-11-23 115841](https://user-images.githubusercontent.com/10173406/69475396-87cfa300-0df2-11ea-95ea-776946159d2d.png)

**Comment by milewski** [comment]
@bartakke you can use this package: [collapsible-resource-manager](https://github.com/dcasia/collapsible-resource-manager) it allows you to group and customize the sidebar items whatever you like
