### ISSUE TITLE
Unable to empty a DateTime field with previous value

### ISSUE THREAD

**Issue by XternalSoft** [laravel/nova-issues#2172]
- Laravel Version: 5.8.35
- Nova Version: 2.7.1
- PHP Version: 7.3.11
- Database Driver & Version: MYSQL 8.0.11
- Browser type and version: All

### Description:
After settings a DateTime Field with value. Unable to erase for put an empty value (datetime field nullable) : the datepicker replace empty value with the old datetime value.

==> This does not happen with Date field 

### Steps To Reproduce:
Create a DateTime field and set the datetime (no need to save).

**Comment by jbrooksuk** [comment]
I'm not seeing this behaviour with the `DateTime` field. What you might be seeing instead of a value is the placeholder, which will always show the time at which you landed on the page.

![image](https://user-images.githubusercontent.com/246103/69713580-b0121700-10fc-11ea-9405-c523b5dfe79a.png)

The value is greyed out, which is a placeholder.

**Comment by XternalSoft** [comment]
Sorry, I know how to make a difference between value and placeholder.

Example :

![2019-11-27 11-24-56](https://user-images.githubusercontent.com/1142472/69716563-924bae80-110a-11ea-8674-29c974e5b7bf.gif)

**Comment by jbrooksuk** [comment]
What browser are you using?

**Comment by XternalSoft** [comment]
Brave (Chromium 78)
Same behaviour with Firefox 70

**Comment by ziming** [comment]
Can confirm after you clean the field, click another field or press enter and the old value is back (not placeholder grey). Still a bug

**Comment by MannikJ** [comment]
I can also confirm that it is not possible to clear a DateTime field when you have filled it with some value.

**Comment by mauricoder** [comment]
Same here. Is not possible to clear a DateTime field after it got a value.

**Comment by mikeerickson** [comment]
Awfully quick to close here, not always happy path, works for me, therefore close it
