### ISSUE TITLE
Upload/Attach file button in Trix always appears

### ISSUE THREAD

**Issue by XternalSoft** [laravel/nova-issues#2173]
- Laravel Version: 5.8.35
- Nova Version: 2.7.1
- PHP Version: 7.3.11
- Database Driver & Version:MySQL 8
- Browser type and version: all

### Description:
Unable to hide Attach/upload button in Trix despite "withFiles" is FALSE.
User can't upload file... but why displaying the button ??
 
### Steps To Reproduce:
Create an Trix field

thanks

**Comment by jbrooksuk** [comment]
`withFiles` is not meant to be passed `false`. Instead just don't chain the `withFiles` method as it's opt-in not opt-out.

**Comment by XternalSoft** [comment]
No... i don't chain anything...

Example :
`Trix::make('Texte', 'body')->rules('required'),`

**Comment by jbrooksuk** [comment]
Weirdly, I don't see any upload / attach button. Can you share a screenshot?

**Comment by XternalSoft** [comment]
![Capture d’écran de 2019-11-27 11-04-15](https://user-images.githubusercontent.com/1142472/69713919-b35dd080-1105-11ea-9363-3be218935085.png)

**Comment by jbrooksuk** [comment]
Try running `php artisan nova:publish --force`?

**Comment by XternalSoft** [comment]
I had already thought about it. I just redo it, it's the same :-(

**Comment by XternalSoft** [comment]
It's in my DEV env. 
On production (nova 2.6.0) no button appears (no change in Resource)

**Comment by XternalSoft** [comment]
In Nova 2.8.0 the button does not appear anymore !

So.. fixed ;-)

**Comment by jbrooksuk** [comment]
Ah, that'll be why I didn't see the button.

**Comment by renanpicanco** [comment]
Laravel **6.x**
Nova **2.9.3**

Attach buttons doesn't appear even i set withFiles = true.
How do I solve this?

```
Trix::make('Text')->withFiles('public')->required(),
```

**Comment by yevhenkoriakin** [comment]
Nova v3.5.0 
fresh install
Upload/Attach file button in Trix always appears
![image](https://user-images.githubusercontent.com/8833710/81291458-744b8800-9072-11ea-9ffb-3cbc14b44060.png)

Resourece:
![image](https://user-images.githubusercontent.com/8833710/81291486-8299a400-9072-11ea-8ecf-0b8a5d7766e7.png)

@jbrooksuk @davidhemphill

**Comment by DanielDarrenJones** [comment]
Im having the same issue using Nova `v3.27.0` with the Trix field being defined as `Trix::make('Description', 'description'),` the button always shows to upload assets.

**Comment by davidhemphill** [comment]
Please open a new issue and fill out the required details in the issue template. Thanks!
