### ISSUE TITLE
user head icon and logout can't display

### ISSUE THREAD

**Issue by e29denghy** [laravel/nova-issues#2174]
- Laravel Version: 6.5.2
- Nova Version: 2.7.1
- PHP Version: 7.2
- Database Driver & Version: MySQL 5.7
- Operating System and Version: Ubuntu 16.04
- Browser type and version: Chrome 78.0
- Reproduction Repository: https://github.com/e29denghy/jimei

### Description:

header view:  user head icon and logout can't display

already try  
```
php artisan nova:publish
php artisan view:clear
```

### Steps To Reproduce:

upgrade Nova 2.4 or 2.5 to 2.7

**Comment by tanthammar** [comment]
I had the same issue.
1. Backup any changes you've made to config/nova + any customized views.
2. run `php artisan nova:publish --force`
3. re-apply configs and customized views (the ones that don't break the user-menu :)

**Comment by jbrooksuk** [comment]
Thanks @tanthammar.
