### ISSUE TITLE
Model/resource with word 'Order' wont show in Nova

### ISSUE THREAD

**Issue by mforcer** [laravel/nova-issues#2175]
- Laravel Version: 6.2
- Nova Version: 2.7.1
- PHP Version: 7.2
- Database Driver & Version: mysql

### Description:

Whenever I create a resource with a model of `Order` it doesn't show in Nova. 

```
// app/Nova/Order.php

    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static $model = \App\Models\Order::class;
```

### Steps To Reproduce:

Create a model of `Order` and assign it to an `Order` resource.

**Comment by jbrooksuk** [comment]
I'm not able to re-create this:

![CleanShot 2019-11-27 at 09 49 38](https://user-images.githubusercontent.com/246103/69712773-4cd3b500-10fb-11ea-9e86-cf5cda70959f.png)

**Comment by rajathans** [comment]
hey @mforcer were you able to figure this out, I'm also facing a similar issue

**Comment by mforcer** [comment]
@rajathans Yeah, I was being stupid. My OrderPolicy was causing it to be removed.

I added this to my Order resource file:

```
    /**
     * Determine if the given resource is authorizable.
     *
     * @return bool
     */
    public static function authorizable()
    {
        return false;
    }
```
