### ISSUE TITLE
showOnTableRow not working

### ISSUE THREAD

**Issue by weileong17** [laravel/nova-issues#2176]
- Laravel Version: 5.7.15
- Nova Version: 2.0.5
- PHP Version: 7.3.10
- Database Driver & Version: Mysql 5.7
- Operating System and Version: OSX Catalina 10.15.1

### Description:
Registering an action with showOnTableRow but it is still does not get rendered in the table row. 

### Steps To Reproduce:

>     public function actions(Request $request)
>     {
>         return [
>             (new Actions\RewardSettlement)->showOnTableRow()
>         ];
>     }

### Screenshot:
![image](https://user-images.githubusercontent.com/52274545/69595049-51379980-1039-11ea-935a-f214aa9f72a1.png)

**Comment by anditsung** [comment]
maybe update to latest version of nova?

**Comment by jbrooksuk** [comment]
You need to upgrade Nova.
