### ISSUE TITLE
get .env variable From Laravel .env to Laravel Nova Components

### ISSUE THREAD

**Issue by fredroo** [laravel/nova-issues#2177]
Today I need to get a variable from LARAVEL default .env to a LARAVEL NOVA component called WelcomeCard, basically is the same Main Page of Laravel Nova after login with some changes like another icons and texts, but I need a change a URL on this page to dynamically get domain URL from a variable in .env for in the case my application change domain, subdomain or folder,

Today I don't find any way to this
all tutorials, questions about this neede on any location of results of google and any stuff like this return nothing to solve my problem

below have some links to exemplify and clarify this neede

https://stackoverflow.com/questions/57318022/getting-data-from-env-in-laravel-to-laravel-nova-card-vue-component

https://medium.com/@patrickcurl/using-laravel-env-variables-inside-vue-js-components-29faa9a344c5

https://laracasts.com/discuss/channels/vue/how-to-get-env-variable-in-nova-package?page=0

**Comment by jbrooksuk** [comment]
You can pass meta data through to a card using https://nova.laravel.com/docs/2.0/customization/cards.html#card-options

**Comment by fredroo** [comment]
@jbrooksuk quick question, in this way I can send this value to HTML in .vue?

**Comment by jbrooksuk** [comment]
You pass through the variable to Vue using the `withMeta` Function.

This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](https://larachat.co/).

**Comment by fredroo** [comment]
@jbrooksuk ok thanks by the way

**Comment by Israr22** [comment]
you can pass through the controller by using ` url` variable
