### ISSUE TITLE
ActionEvent user relationship

### ISSUE THREAD

**Issue by gaelreyrol** [laravel/nova-issues#2178]
- Laravel Version: 6.5.2
- Nova Version: 2.6.1
- PHP Version: 7.2.24

### Description:

Currently the ActionEvent model is related to user via the auth provider:
```php
/**
 * Get the user that initiated the action.
 */
public function user()
{
    return $this->belongsTo(config('auth.providers.users.model'), 'user_id');
}
```

Unfortunately if we don't use the default user provider for nova. It is not possible to log actions.
See this issue for the related behavior #1947.

What I suggest is to make use of nova config guard to get the model provider.
So it would look like this:
```php
/**
 * Get the user that initiated the action.
 */
public function user()
{
    $novaGuard = config('nova.guard');
    $guardProvider = config('auth.guards')[$novaGuard]['provider'];
    $userClass = config('auth.providers')[$guardProvider]['model'];

    return $this->belongsTo($userClass, 'user_id');
}
```
What do you think ?

Regards,

**Comment by davidhemphill** [comment]
You can specify a custom user provider by specifying the relationship on a custom `ActionEvent` model, and then using that in conjunction with a custom `ActionResource` specified in your Nova config.

**Comment by geneccx** [comment]
Custom ActionEvent models don't quite work properly, as a lot of Nova's resource controllers call static methods on `Laravel\Nova\Actions\ActionEvent`, so even customizing the `ActionResource` in the config and using `ActionEvent` class, the user can't be overridden properly.

Take a look at `nova/src/Http/Controllers/ResourceStoreController.php:39`:

```
            ActionEvent::forResourceCreate($request->user(), $model)->save();
```

**Comment by davidhemphill** [comment]
Your custom ActionEvent must be compatible. The easiest way to do this is to extend the existing one.

**Comment by davidhemphill** [comment]
Ah misunderstood. Yeah we would have to convert those calls to use whatever model is specified on the registered ActionResource.

**Comment by gaelreyrol** [comment]
The simplest thing is still to defaultly resolve the right provider, not laravel default's.
