### ISSUE TITLE
Place doesn't return Latitude and Longitude coordinates

### ISSUE THREAD

**Issue by m2de** [laravel/nova-issues#218]
I was really hoping that the `Place` field would include coordinates, `latitude` and `longitude` which are both returned from Algolia places. Looking at the source it wouldn't take a lot to add it?

**Comment by freshface** [comment]
Also an option to display them on a map would be nice!

**Comment by Jam0r85** [comment]
An addition to the Place field allowing you to map the algolia keys to the field names you want would be helpful.

eg. I've been using Zip in a project for the postcode and using Place wouldn't populate this field. Changing it to postal_code works fine.

**Comment by ovvessem** [comment]
@Jam0r85 have a look at this section in the documentation which describes how to map to your own table fields: https://nova.laravel.com/docs/1.0/resources/fields.html#configuring-field-auto-completion

**Comment by m2de** [comment]
Gone slightly off-topic here. This should be a relatively quick fix to implement and I think it makes sense to make all fields returned by Algolia accessible by the Place field?

**Comment by mhetreramesh** [comment]
I would also really appreciate to have this fix.

**Comment by alexbowers** [comment]
`request` flag added due to request for the longitude and latitude. If there is a separate issue that you think is a bug, could you create a separate issue so they can be tracked separately.

**Comment by m2de** [comment]
I have created an extended Place field type which will return the Latitude and Longitude values for anyone who needs this functionality.

You can grab it here [https://github.com/Silvanite/nova-field-place](https://github.com/Silvanite/nova-field-place) or 
[https://novapackages.com/packages/silvanite/nova-field-place](https://novapackages.com/packages/silvanite/nova-field-place) here

**Comment by julianpoma** [comment]
Why this was closed? Can't we have this feature by default without having to use a package?

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍

**Comment by geodeveloper** [comment]
@davidhemphill Was this fix included on v1.2.0 or it will be included on next one? Thank you.
