### ISSUE TITLE
Laravel Nova BelongsTo Field Appending Namespace To Current Namespace

### ISSUE THREAD

**Issue by DutchPrince** [laravel/nova-issues#2183]
- Laravel Version: 6.2
- Nova Version: *
- PHP Version: 7.3.9

### Description:

Laravel Nova returns

Cant find model _App\Nova\Actions\App\Nova\User_

The namespace exists in both User and the Action. The problem is only occuring to relation fields like BelongsTo and MorphOne.

This is my file:
```
Namespace App\Nova\Actions;

use App\Nova\User;
use Orlyapps\NovaBelongsToDepend\NovaBelongsToDepend;

class PlayerDD extends Action
{

    public $name = 'Spelers toekennen';

    /**
     * Perform the action on the given models.
     *
     * @param  \Laravel\Nova\Fields\ActionFields  $fields
     * @param  \Illuminate\Support\Collection  $models
     * @return mixed
     */
    public function handle()
    {
    }

    /**
     * Get the fields available on the action.
     *
     * @return array
     */
    public function fields()
    {        
        return [
            BelongsTo::make(User::class)
        ];
    }
}
```

**Comment by jbrooksuk** [comment]
You could try overriding the class name. https://nova.laravel.com/docs/2.0/resources/relationships.html#belongsto

**Comment by DutchPrince** [comment]
I got it working another way, it looks like relation fields just don't work in an Action. Thanks for responding though

**Comment by jbrooksuk** [comment]
I've just encountered this issue in Lenses too. Will look at what's causing it.
