### ISSUE TITLE
ErrorException (E_ERROR) Class name must be a valid object or a string (View: /Applications/MAMP/htdocs/my_nova_project/nova/resources/views/layout.blade.php) 

### ISSUE THREAD

**Issue by MsFoued** [laravel/nova-issues#2184]
- Laravel Version: 5.8.35
- Nova Version: 2.8.0
- PHP Version: 7.2.19

**composer.json:**
"require": {
        "php": "^7.1.3",
        "laravel/framework": "5.8.*",
        "laravel/nova": "*"
        ...
}

"repositories": [
        {
            "type": "path",
            "url": "./nova"
        }
]

**Description:**
After updating my nova project to the latest version (2.8.0), I got this exception

<img width="1135" alt="Screen Shot 2019-11-29 at 15 50 25" src="https://user-images.githubusercontent.com/15153313/69876803-d680af80-12c0-11ea-8fec-a06167eb537c.png">

**Comment by jbrooksuk** [comment]
Can you provide more information, please? Do you know what line this is occurring on?

**Comment by MsFoued** [comment]
@jbrooksuk 
As mentioned above the exception occurs in nova/resources/views/layout.blade.php

First I tried to dump **\Laravel\Nova\Nova::availableTools(request())** 
I got this :

<img width="358" alt="Screen Shot 2019-11-29 at 17 51 51" src="https://user-images.githubusercontent.com/15153313/69882654-2b2c2680-12d1-11ea-92c6-35a2cdb25700.png">

Then I moved to dump **$tool->renderNavigation()** inside the foreach

                @foreach (\Laravel\Nova\Nova::availableTools(request()) as $tool)
                    {!! $tool->renderNavigation() !!}
                @endforeach

and the exception was occured.

**Comment by jbrooksuk** [comment]
What happens if you disable the third party package?

**Comment by MsFoued** [comment]
I will give it a try on fresh laravel installation

**Comment by jbrooksuk** [comment]
Any luck?

**Comment by MsFoued** [comment]
Yes works like a charm on fresh Laravel installation

**Comment by jbrooksuk** [comment]
Okay, thanks for letting me know.
