### ISSUE TITLE
Setting readonly via method interferes with meta attributes and validation

### ISSUE THREAD

**Issue by bakerkretzmar** [laravel/nova-issues#2185]
- Laravel Version: 6.6.0
- Nova Version: 2.8.0
- PHP Version: 7.3.12
- Database Driver & Version: MySQL 8.0.18
- Operating System and Version: macOS 10.13.6
- Browser type and version: Firefox 70.0.1

### Description:

If a field is set to be read-only using the `readonly` method, the field will ignore a value passed to it using the `withMeta` method.

My understanding is that the recommended way to set a 'default' value on a `BelongsTo` field is using `withMeta`, like this:

```php
BelongsTo::make('Province', 'province', \App\Nova\Province::class)
    ->withMeta([
        'belongsToId' => $this->province_id ?? auth()->user()->province_id,
    ])
```

That works great. If I want that field to be read-only (e.g. only editable by certain user roles), I would think there would be two options:

```php
BelongsTo::make('Province', 'province', \App\Nova\Province::class)
    ->withMeta([
        'belongsToId' => $this->province_id ?? auth()->user()->province_id,
        'extraAttributes' => [
            'readonly' => ! $request->user()->isNationalAdmin(),
        ],
    ])
```

which works fine, or:

```php
BelongsTo::make('Province', 'province', \App\Nova\Province::class)
    ->withMeta([
        'belongsToId' => $this->province_id ?? auth()->user()->province_id,
    ])
    ->readonly(fn($request) => ! $request->user()->isNationalAdmin())
```

which doesn't work—the resolved `belongsToId` populates the form but isn't saved. In my case, users are only authorized to see resources in their province, so when they're creating a resource that field should be set to their province automatically, and disabled. However, using the second example above, as soon as they submit the form the resource's `province_id` is saved as `null` (no province, i.e. National, which they aren't authorized to see), and when they're redirected to the detail view they get a 403.

### Steps To Reproduce:

Create two `BelongsTo` fields similar to the examples above:

```php
BelongsTo::make('Thing', 'thing', \App\Nova\Thing::class)
    ->withMeta([
        'belongsToId' => $this->thing_id ?? config('app.default_thing_id'),
        'extraAttributes' => [
            'readonly' => true,
        ],
    ])
```

This works: on create the default `thing_id` is set, on update if a `thing_id` is already set it will be preserved, and the field is disabled/read-only.

```php
BelongsTo::make('Thing', 'thing', \App\Nova\Thing::class)
    ->withMeta([
        'belongsToId' => $this->thing_id ?? config('app.default_thing_id'),
    ])
    ->readonly()
```

This doesn't work: on the create form the field is disabled and appears to be filled in correctly, but when the resource is actually created the `thing_id` will be set to `null`. **Also, the resource will pass validation even if the `BelongsTo` field is _not_ nullable, but will be saved in the database with `thing_id` set to `null`.**

**Comment by bakerkretzmar** [comment]
Commenting again so "stale bot" goes away, I haven't re-tested this recently but I also haven't seen anything indicating it was fixed. Feel free to close this if it was!

**Comment by davidhemphill** [comment]
You should use the added `readonly` method on the field to specifically set that state.

**Comment by bakerkretzmar** [comment]
Just tested this again and the issue still exists as I described it above (now on Laravel 7.14.1, Nova 3.6.0).

This doesn't work:

```php
BelongsTo::make('Province', 'province', \App\Nova\Province::class)
    ->withMeta([
        'belongsToId' => $this->province_id ?? auth()->user()->province_id,
    ])
    ->readonly();
```

The Province field is disabled and _appears_ to be filled correctly on the form, but `province_id` is saved as `null`.

@davidhemphill can you reopen this or should I submit a new issue?
