### ISSUE TITLE
$this->merge() doesn't work for panels

### ISSUE THREAD

**Issue by stancl** [laravel/nova-issues#2186]
- Laravel Version: 6.6.0
- Nova Version: 2.8.0
- PHP Version: 7.2
- Database Driver & Version: sqlite
- Operating System and Version: Ubuntu 19
- Browser type and version: Chrome

### Description:

Using panels in methods that use `$this->merge()` returns in an infinite loading screen on resource detail.

### Steps To Reproduce:

Apply a trait like this to a Nova resource and call `$this->addressFields()` in `fields()`. Removing the `//` will result in the resource detail not loading.

```php
trait HasAddressFields
{
    protected function addressFields()
    {
        return $this->merge([
            // new Panel('Billing Address', [
                Text::make('Billing Person', 'billing_person'),
                /* ... shortened */
            // ]),

            // new Panel('Shipping Address', [
                Text::make('Shipping Person', 'shipping_person')->hideFromIndex(),
                /* ... shortened */
            // ]),
        ]);
    }
}

```

**Comment by davidhemphill** [comment]
I was not able to reproduce your issue using the example provided.
