### ISSUE TITLE
`Pivot Fields` don't have access to the selected resource id

### ISSUE THREAD

**Issue by zareismail** [laravel/nova-issues#2187]
Hi.
In the attaching form; nova doesn't send selected resource id. so. if anyone wants to filter pivot fields by the selected resource; it's impossible.

imagine this scenario:

I have the `homes` table and I want to attach to the homes many users by custom roles.
for the users that have the owner role; I want to show the `Text` field and for the users that have role `Admin` i want to show `Trix` field in the relation attaching view. this situation is impossible in the attach view because I don't access to selected user id.

thanks.

**Comment by brunocfalcao** [comment]
If I understood well your scenario you might need to create 2 different many-to-many relationships. One per each role type and then also the 2 different BelongsToMany Fields for both different relationship type.

**Comment by jbrooksuk** [comment]
I believe @brunocfalcao is right here. If this doesn't solve your issue, please re-open this issue.
