### ISSUE TITLE
KeyValue fields set to readonly are still editable

### ISSUE THREAD

**Issue by patrickgilmour** [laravel/nova-issues#2188]
- Laravel Version: 6.6.0
- Nova Version: 2.8.0
- PHP Version: 7.3.9
- Database Driver & Version: MySQL 5.7.27
- Operating System and Version: Ubuntu 18.04 (Homestead)
- Browser type and version: Safari Mac 13.0.3

### Description:

When fields of type `KeyValue` are set to `readonly` the content in the field can still be edited in the Edit view.

For example, in the following the 'Name' field is correctly disabled but the key/value pairs in the 'Preferences' field can be edited. On save, they are not saved, however.

```
Text::make('Name')->readonly(),
KeyValue::make('Preferences')->rules('json')->readonly(),
```

### Steps To Reproduce:

Create a JSON Column in database. Create a Nova resource for the Model/column, and create field as above.

<img width="1075" alt="nova-keyvalue-updates-2" src="https://user-images.githubusercontent.com/2692797/69924907-99ace800-147b-11ea-8a17-36e19c3f21d8.png">

(This is the first time I've submitted an Nova/GitHub Issue; apologies in advance if I've messed something up)

**Comment by jbrooksuk** [comment]
This is a perfect report, thanks! I'll get a fix ready for the next release.
