### ISSUE TITLE
UserCommand not working - operation aborted

### ISSUE THREAD

**Issue by nibri10** [laravel/nova-issues#2192]
- Laravel Version: 6.6.0
- Nova Version: 2.8.0
- PHP Version: 7.4.0
- Database Driver & Version:
- Operating System and Version: Windows 10 PRO
- Browser type and version: Google Chrome is up to date
Version 78.0.3904.108 (Official Build) (64-bit)
- Reproduction Repository: https://github.com/###/###

### Description:
php artisan nova:user operation is aborted

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/22533877/69961984-d1537880-14eb-11ea-93c3-436748610dab.png)

**Comment by jbrooksuk** [comment]
Can you confirm that your user model is not guarded?

**Comment by nibri10** [comment]
@jbrooksuk I did not make modification I am using the default

**Comment by jbrooksuk** [comment]
@nibri10 do other Artisan commands work okay?

**Comment by nibri10** [comment]
@jbrooksuk Yes, artisan migrate, artisan db:seed, artisan model:example, working normally

**Comment by jbrooksuk** [comment]
Have you modified the `$createUserCallback` property in the Nova class?

**Comment by nibri10** [comment]
I did not change @jbrooksuk

**Comment by nibri10** [comment]
Default Code:
`
    /**
     * Create a new user instance.
     *
     * @param  \Illuminate\Console\Command
     * @return mixed
     */
    public static function createUser($command)
    {
        if (! static::$createUserCallback) {
            static::createUserUsing();
        }

        return call_user_func(
            static::$createUserCallback,
            ...call_user_func(static::$createUserCommandCallback, $command)
        );
    }

    /**
     * Register the callbacks used to create a new user via the CLI.
     *
     * @param  \Closure  $createUserCommandCallback
     * @param  \Closure  $createUserCallback
     * @return static
     */
    public static function createUserUsing($createUserCommandCallback = null, $createUserCallback = null)
    {
        if (! $createUserCallback) {
            $createUserCallback = $createUserCommandCallback;
            $createUserCommandCallback = null;
        }

        static::$createUserCommandCallback = $createUserCommandCallback ??
                  static::defaultCreateUserCommandCallback();

        static::$createUserCallback = $createUserCallback ??
                  static::defaultCreateUserCallback();

        return new static;
    }

    /**
     * Get the default callback used for the create user command.
     *
     * @return \Closure
     */
    protected static function defaultCreateUserCommandCallback()
    {
        return function ($command) {
            return [
                $command->ask('Name'),
                $command->ask('Email Address'),
                $command->secret('Password'),
            ];
        };
    }

    /**
     * Get the default callback used for creating new Nova users.
     *
     * @return \Closure
     */
    protected static function defaultCreateUserCallback()
    {
        return function ($name, $email, $password) {
            $guard = config('nova.guard') ?: config('auth.defaults.guard');

            $provider = config("auth.guards.{$guard}.provider");

            $model = config("auth.providers.{$provider}.model");

            return tap((new $model)->forceFill([
                'name' => $name,
                'email' => $email,
                'password' => Hash::make($password),
            ]))->save();
        };
    }`

**Comment by nibri10** [comment]
code in my private Repository Nova.php
[](https://raw.githubusercontent.com/nibri10/sistema-financeira-nova/master/nova/src/Nova.php?token=AFL5N5L4OYMIFZ6LY24HPAS55Z43K)

**Comment by jbrooksuk** [comment]
Thanks. I'm wondering if it's just a Windows thing. I'll take a look.

**Comment by samdev97** [comment]
@jbrooksuk Any follow up on this? Still having this issue on Laravel 6.

**Comment by aiman1717a** [comment]
Im also having this issue. Any fix?

**Comment by aiman1717a** [comment]
I have a nova project(Laravel version: 6.18.7 and nova version: 2.11.1) which was working fine until i formatted my lap and when i installed everything back, this command is "aborted". i think its probably a php version problem which i updated from php 5 something to php 7.4.0. Or it could be MySQL version problem which i also updated

**Comment by aiman1717a** [comment]
Its a problem with 7.4.0 php version. i just updated and it is solved

**Comment by jbrooksuk** [comment]
Are you on Windows?

**Comment by aiman1717a** [comment]
Yes

**Comment by thaifani** [comment]
i have same problem 
window 10 
php : 7.4.0 
laravel 6.2

**Comment by danielguevarav91** [comment]
I got the same Error, I am on a windows system with PHP 7.4 and laravel 7 when I cmd the code NOVA:USER I get this nasty error called ABORTED and a dot. someone got a solutions for this??

**Comment by Conaire** [comment]
Downgrading to PHP 7.3.12 worked for me.

**Comment by aiman1717a** [comment]
Yes, i figured out that it is a problem of php version 7.4.0. I upgraded it and it works.

**Comment by aiman1717a** [comment]
> I got the same Error, I am on a windows system with PHP 7.4 and laravel 7 when I cmd the code NOVA:USER I get this nasty error called ABORTED and a dot. someone got a solutions for this??

**Comment by IVNtech** [comment]
@Conaire thanks, I will do it. Thanks a lot, @aiman1717a  thanks to for sharing your positive results

**Comment by davidhemphill** [comment]
Seems the solution is to avoid using PHP 7.4.0 specifically.
