### ISSUE TITLE
Route helper generate url with nova.domain

### ISSUE THREAD

**Issue by meyer59** [laravel/nova-issues#2194]
- Laravel Version: 6.6
- Nova Version: 2.8
- PHP Version: 7.3.1
- Database Driver & Version: Mysql 5.7.26
- Operating System and Version: Debian9
- Browser type and version: Chrome 78 

### Description:
I have a `Notification` which send an email to activate an user account. This notification class  use the `URL::temporarySignedRoute` to generate a signed url from a route name. 
When sending it through nova (through an `Action`)  the `nova.domain` is used instead of the `APP_URL` in the link.
So the activation link is not valid.
 Since it is a signed link, I cannot replace the domain on the fly because  the signature will be invalid.
in my `nova.php` i have a set up a different domain for nova with the `domain` key.
Is it a normal behavior ?

### Steps To Reproduce:
create a route with a name in `web.php`
run nova in a different domain (add `domain` key in `nova.php`)
try to generate an url with the `route()` helper from the nova dashboard.
The link is generated with `nova.domain` and not with `APP_URL`

Cordially

**Comment by jbrooksuk** [comment]
Well, I just learnt that Nova has a `domain` config option that's hidden! 🧠

From my brief investigation, this appears to be because of the Laravel framework itself and not Nova. It might be worth asking for support in Discord or Larachat on that.

**Comment by jbrooksuk** [comment]
@meyer59 I've discussed this with the Laravel team and the suggestion here is that **your** application web routes should be wrapped in a domain setting themselves.
