### ISSUE TITLE
Resources hidden by DetailQuery/IndexQuery are still editable

### ISSUE THREAD

**Issue by m-lotze** [laravel/nova-issues#2195]
- Laravel Version: 6.6.0
- Nova Version: 2.8.0
- PHP Version: 7.3.12
- Database Driver & Version: MySQL 7
- Operating System and Version: Ubuntu 18.04
- Browser type and version: Chrome

### Description:
I have a resource, where i only want to show a subset of models in nova. So i use detailQuery and IndexQuery to hide all resources with type != value:

```
public static function detailQuery(NovaRequest $request, $query)
{
    return $query->where('type', 'value');
}
```

`/resources/resource/{resourceId}` correctly returns a 404, but `/resources/resource/{resourceId}/edit` is available and the resource can be changed. 

there should be a method `formQuery` to prevent this and ideally there is a method `resourceQuery` or something similar, which is applied to index, form and detail.

**Comment by jbrooksuk** [comment]
You should use [Policies](https://nova.laravel.com/docs/2.0/resources/authorization.html#policies).

**Comment by m-lotze** [comment]
@jbrooksuk I want to use a subset of models as a nova resource and another subset as a different resource. a policy is not the solution for this. 

and quite frankly it makes no sense, that a route `/resources/resource/{resourceId}` returns a 404 and `/resources/resource/{resourceId}/edit` does not.

**Comment by jbrooksuk** [comment]
> I want to use a subset of models as a nova resource and another subset as a different resource. 

This is what [Lenses](https://nova.laravel.com/docs/2.0/lenses/defining-lenses.html#defining-lenses) are for.

**Comment by m-lotze** [comment]
it is not about lenses or policies. it is about having a detailQuery method and beeing able to hide a resource by that and beeing not able to do the same for the form view with a similar method. just seems illogical...
