### ISSUE TITLE
Display toast from backend

### ISSUE THREAD

**Issue by PatricNox** [laravel/nova-issues#2196]
> Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to  post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Feature request**

Is there currently a way to send toasts from backend? is it doable to implement in upcoming versions?

Scenario:

```
static::updating(function ($attendance) {
            if (!$attendance->canInteractWithApprovedAttendance(Auth()->user())) {
                return false;
            }
        });
```

instead of return false here, a toast could be benefitial. 

This boot updating override is for preventing [Inline-field-update](https://github.com/wehaa/inline-field-update) to show like if a column gets changed though a deeper permission control says otherwise.

Any ideas?

**Comment by PatricNox** [comment]
@kevinkodamera maybe have an insight here.

**Comment by bolechen** [comment]
can try 

```
abort(500,  'error msg');
```

**Comment by jbrooksuk** [comment]
Actions can send messages using `Action::message()` but this is not possible outside of actions, unless you do what @bolechen suggested.

**Comment by PatricNox** [comment]
@bolechen solution works, though it's a hackfix.
Thanks for milestoning this!
