### ISSUE TITLE
BooleanGroup field can't read the values from the request

### ISSUE THREAD

**Issue by DanielKaemmerling** [laravel/nova-issues#2197]
- Laravel Version: 6.6.1
- Nova Version: 2.8.0
- PHP Version: 7.3.9

### Description:

BooleanGroup can not read the set values from the request. If an option is checked, it will be saved correctly in the database. However, none of the options in nova are checked.

<img width="366" alt="Bildschirmfoto 2019-12-04 um 15 08 14" src="https://user-images.githubusercontent.com/4339392/70149292-145a4b00-16a8-11ea-99d5-c5338de04d4f.png">

### Steps To Reproduce:

Create a BooleanGroup field, click on an option and save. All options should be red (false). I used the example from the documentation: https://nova.laravel.com/docs/2.0/resources/fields.html#boolean-group-field

### Developer notes:

The problem is that Vue gets the values as a string (not as an object) from PHP and therefore the value is always false.

<img width="2305" alt="Bildschirmfoto 2019-12-04 um 15 07 56" src="https://user-images.githubusercontent.com/4339392/70149646-d6a9f200-16a8-11ea-85eb-81030b14e2ee.png">

One solution could be to replace the following:

```
this.field.value = this.field.value || {}
```

with 

```
this.field.value = JSON.parse(this.field.value) || {}
```

in 

resources/js/components/Index/BooleanGroupField.vue
resources/js/components/Form/BooleanGroupField.vue and
resources/js/components/Detail/BooleanGroupField.vue

and it works:

<img width="2311" alt="Bildschirmfoto 2019-12-04 um 15 12 06" src="https://user-images.githubusercontent.com/4339392/70149533-98143780-16a8-11ea-8064-d922e8fbd447.png">

**Comment by jbrooksuk** [comment]
@DanielKaemmerling sorry, can you explain this a bit more, please? I'm able to create a new "Role" with no items checked and update them as expected.

**Comment by DanielKaemmerling** [comment]
If you create a BooleanGroup as described in the documentation, you will get the four checkboxes in the index, form and detail. If you edit a dataset and check `Create`, then it will be stored correctly in the database. But Nova does not display an active option in the front-end. Normally, `Create` should be set.

This happens because `this.field.value` in the Vue Component is a string, but an object is expected. As long as `this.field.value` is a string, `checked: this.field.value [o.name] || false` always returns `false` because the expected object is not an object with values.

```
resources/js/components/Index/BooleanGroupField.vue Line 38 and 45
resources/js/components/Form/BooleanGroupField.vue Line 34 and 41
resources/js/components/Detail/BooleanGroupField.vue Line 32 and 39
```

**Comment by jbrooksuk** [comment]
What browser are you using? I'm not seeing this in Safari. If I create a new Role (for instance) and select "Create" then it's correctly shown as active.

**Comment by jbrooksuk** [comment]
Just to confirm, is your model casting the permissions to a string instead of JSON?

**Comment by jbrooksuk** [comment]
In my `Role` model, I have:

```php
protected $casts = [
        'permissions' => 'array'
];
```

**Comment by DanielKaemmerling** [comment]
Yes, with explicit casting it works. That should be included in the documentation I think.

**Comment by rhino-corey** [comment]
The documentation regarding casting was added into the 2.0 docs, but was not carried over into the 3.0 docs here:

https://nova.laravel.com/docs/3.0/resources/fields.html#boolean-group-field

Can you please update it there as well?
