### ISSUE TITLE
Form buttons don't have a loading state

### ISSUE THREAD

**Issue by disitec** [laravel/nova-issues#220]
Buttons for create and update form should have a loading state between click and response. Specially for uploading files. UX is not good enough. User could think that the action is not taking place and click the button several times

http://g.recordit.co/Xopf2GnD2P.gif

**Comment by Andy-Baker** [comment]
Similarly when navigating pagination. The blue loading bar at the top completes way too early. E.g if you're resizing model images for the first time, there's no indication that the page is still loading.

**Comment by lucasromanojf** [comment]
±1

**Comment by Jam0r85** [comment]
I'd imagine that it will have something like Spark does soon.

**Comment by albalooshi** [comment]
@davidhemphill 
Why is this closed? Requests are not allowed?

**Comment by davidhemphill** [comment]
Requests are allowed. Was just gonna mark them as request and close so it's easier to see, but just gonna leave them open now.

**Comment by poxin13** [comment]
Would also be nice to have loading state on the global search. Can't tell when a search is complete if there happens to be no results.

**Comment by davidhemphill** [comment]
@poxin13 Just added a loader to global search. Thanks for the suggestion. Should come in the next release.

**Comment by icaroce** [comment]
I also requested this improvement via support. Due to multplie double clicks and duplicate data.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍

**Comment by ahmedkandel** [comment]
Still, index pagination and searchable relations have no loading indicator. Shall I open a new issue or keep following here. I sent a request via support.

**Comment by Jam0r85** [comment]
@ahmedkandel This is working for me? Loading icon on buttons when creating, etc.

**Comment by ahmedkandel** [comment]
@Jam0r85 Yes for buttons it shows the loading indicator while as @Andy-Baker in the first comment stated it is not showing for pagination and searchable relations. I will create a new issue for this. thanks.
