### ISSUE TITLE
Filters do not show on index

### ISSUE THREAD

**Issue by odaiderawi** [laravel/nova-issues#2200]
- Laravel Version: 5.8
- Nova Version: 2
- PHP Version: 7.1.3
- Database Driver & Version: mysql
- Operating System and Version: windows
- Browser type and version: chrome 78

### Description:
 i have make filter for order status in my system 

```php
class OrderStatus extends Filter
{
    public $component = 'select-filter';
    public $name = 'Order Status';

    public function apply(Request $request, $query, $value)
    {
        return $query->where('status', $value);
    }
    public function options(Request $request)
    {
        return [
            'On review' => Order::STATUS_ON_REVIEW,
            'On preparation' => Order::STATUS_ON_PREPARATION,
            'On delivery' => Order::STATUS_ON_DELIVERY,
            'Done' => Order::STATUS_DONE,
            'Cancelled' => Order::STATUS_CANCELLED
        ];
    }
}
```

i also added it to the filters on Order Resource:

```    public function filters(Request $request)
    {
        return [
            new OrderStatus(),
        ];
    }
```

but i can not see the filter on index table

![image](https://user-images.githubusercontent.com/36736057/70240721-6bc6ec80-1776-11ea-848d-4969b6e1e8bf.png)

**Comment by jbrooksuk** [comment]
Can you give us the version number precisely, please?

**Comment by odaiderawi** [comment]
> Can you give us the version number precisely, please?

![image](https://user-images.githubusercontent.com/36736057/70389977-133e5c00-19cf-11ea-861d-655627e92c9c.png)

**Comment by jbrooksuk** [comment]
The full version number is shown at the bottom of the Nova dashboard. Can you share that please? It’s v2 something.

**Comment by odaiderawi** [comment]
> The full version number is shown at the bottom of the Nova dashboard. Can you share that please? It’s v2 something.

2.8.0

**Comment by jbrooksuk** [comment]
I'm not able to replicate this issue, as any filters I create and register on a resource are shown for me. It's possible that one of your installed packages is affecting this.

**Comment by odaiderawi** [comment]
I have make  a nova actions on the same resource and its work perfect but the problem just with filters

**Comment by oleksandr-roskovynskyi** [comment]
> I have make a nova actions on the same resource and its work perfect but the problem just with filters

Were you able to find the cause of the problem? Faced with similar (((

**Comment by paperscissors** [comment]
Did you folks try just emptying Laravel's caches and reloading? That's all it ended up being for me.

**Comment by SanderMuller** [comment]
For me it was the `component` property in the filter class that prevented the filter from being displayed.

**Comment by internetbug256** [comment]
Same problem here. The filter aren't showing on any of my resource pages, so the issue must be general, not in a particular resource view. They worked some time ago.
It is probably some new package I've installed. Who knows which. 
I will try to disable them one by one until the filters are back again.

**Comment by diegocaprioli** [comment]
> For me it was the `component` property in the filter class that prevented the filter from being displayed.

Same for me. I changed it accidentally from the original `public $component = 'select-filter';` to some other value, and that made it disapear from the HTML. Correcting this made it work again. Hope it helps someone else.
