### ISSUE TITLE
Router links to Lenses not updating Filters

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [laravel/nova-issues#2201]
- Laravel Version: 5.8.35
- Nova Version: 2.7.1
- PHP Version: 7.2.24
- Operating System and Version: MacOS 10.14.6
- Browser type and version: Chrome 78

### Description:
I have added some custom `<router-link>` elements to the main left navigation as shortcuts to a particular Resources most pertinent lenses. I followed the format from the core `LensSelector.vue` component, eg:
```html
<router-link
  :to="{
    name: 'lens',
    params: { resourceName: 'resource', lens: 'lense-uri' },
  }"
  class="dim block text-base text-90 no-underline leading-normal my-2"
>
  Lense Name
</router-link>
```
Each of these Lenses are for the same Resource, and have the same set of Filters, just different configurations of the Filters for each Lens.

What Im finding is when I click one of the custom Lens router links, the first time it works as expected, loads the Lens, and the correct Filters are applied.

However, if I then click another of the custom Lens router links, with a different set of Filters, the _old_ Filters from the first Lens are still applied.

If I leave the Resource entirely and view a different Resource, then go back to one of the custom Lens router links, the correct Filter is now applied. Also if I hard reload the page after clicking the second Lens router link for the same Resource, the correct Filter is applied.

It seems like upon navigating to a Lens via a router link, if you dont leave the current Resource being viewed and immediately hit another Lens for the same resource, the Filters arent updated properly?

**Comment by skoyah** [comment]
Same exact problem here. Som buttons on the navbar for different resource lens will maintain the same filters from the previous one.
