### ISSUE TITLE
Event execution finished than expected

### ISSUE THREAD

**Issue by weileong17** [laravel/nova-issues#2202]
- Laravel Version: 5.7.15
- Nova Version: 2.0.5
- PHP Version: 7.3.10
- Database Driver & Version: Mysql 5.7
- Operating System and Version: OSX Catalina 10.15.1

### Description:
>     public function fields(Request $request)
>     {
>         return [
>             ID::make('ID', 'id')->sortable(),
>             Date::make('Start Date', 'start_date'),
>             Date::make('End Date', 'end_date'),
>             BelongsTo::make('Executor', 'user', 'Zhiyi\Plus\Nova\User'),
>             Button::make('Process', 'process-settlement')
>             ->visible($this->status ==1)
>             ->event('Zhiyi\Plus\Events\NormalRewardSettlement')
>             ->loadingText('Processing...')
>             ->successText('Complete')
>             ->style('info'),
>         ];
>     }
In resource, there is a button to trigger an event.

I got the "Complete" successText after a while, after process button is clicked.
![image](https://user-images.githubusercontent.com/52274545/70296186-9bccc900-1824-11ea-961e-12c0f605197c.png)
But actually there are some remaining records to be processed, only 600 out 1058 records processed within 4 minutes, leftover 458 records. Why the event processing finish earlier than expected and return success? I did not see any error anywhere. 

![image](https://user-images.githubusercontent.com/52274545/70296759-6b862a00-1826-11ea-8d14-3c261f7ce12a.png)
I have tracked using laravel log, latest id: 4926, suppose there is a lot of records to be processed.

**Comment by jbrooksuk** [comment]
@weileong17 the `Button` field that you're having problems with is not provided by Nova. Please raise this issue with the package owner.
