### ISSUE TITLE
Add Support for Google Places API for PlaceField using Maps Javascript API

### ISSUE THREAD

**Issue by pixielabsco** [laravel/nova-issues#2203]

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by pxlrbt** [comment]
There is a package for this:
https://github.com/emilianotisato/nova-google-autocomplete-field
