### ISSUE TITLE
Delete action is showing on index even with policy 

### ISSUE THREAD

**Issue by ibrunotome** [laravel/nova-issues#2204]
- Laravel Version: 6.6.0
- Nova Version: 2.8.0
- PHP Version: 7.3.7
- Database Driver & Version: Mysql 5.7
- Operating System and Version: macOS, debian inside docker
- Browser type and version: Safari 13.0.3

### Description:
The policy restrict the delect action

```php
    public function delete(User $user, Order $order)
    {
        return false;
    }
```
It works on details screen and also with the "select all" option in the index
<img width="1104" alt="Screenshot 2019-12-07 20 24 48" src="https://user-images.githubusercontent.com/4256471/70381816-e8e99180-192f-11ea-9ae6-69c4ca73b91a.png">

But when I click in the "select all 33394 options" it shows the delete action:
<img width="1107" alt="Screenshot 2019-12-07 20 25 22" src="https://user-images.githubusercontent.com/4256471/70381830-20583e00-1930-11ea-91a9-d1ac9bc2e22e.png">

Luckily the action will not be executed, the screen reloads, but it would be better if the action was not visible.

**Comment by HenriqueSPin** [comment]
For now, I recompiled Nova with the following patch in `nova/resources/js/views/index.vue`. 

* Before:

```
    /**
     * Determine whether the user is authorized to perform actions on the delete menu
     */
    canShowDeleteMenu() {
      return Boolean(
        this.authorizedToDeleteSelectedResources ||
          this.authorizedToForceDeleteSelectedResources ||
          this.authorizedToRestoreSelectedResources ||
          this.selectAllMatchingChecked
      )
    },
```

* After:

```
    /**
     * Determine whether the user is authorized to perform actions on the delete menu
     */
    canShowDeleteMenu() {
      return Boolean(
        (this.authorizedToDeleteSelectedResources ||
          this.authorizedToForceDeleteSelectedResources ||
          this.authorizedToRestoreSelectedResources) &&
          this.selectAllMatchingChecked
      )
    },
```

**Comment by crynobone** [comment]
> Luckily the action will not be executed, the screen reloads, but it would be better if the action was not visible.

While it would be unfortunate we can't assume that that's the only possibility policy and always return `true` or `false` same as above.

Yes it would be based on your example.

```php
    public function delete(User $user, Order $order)
    {
        return false;
    }
```

But in scenario such as:

```php
    public function delete(User $user, Order $order)
    {
        return $order->user_id == $user->id;
    }
```

Then we still need to show the delete action button as a possible option, or we then need to execute and resolve 33,394 order model to verify that there's no action can be deleted. 

Based on this argument I'm closing the issue for now.
