### ISSUE TITLE
Website has legally problematic Terms of Service

### ISSUE THREAD

**Issue by gjsman** [laravel/nova-issues#2206]
Hi,

This is not strictly a Nova bug, but it is a major problem that needs to be solved and quickly. The Laravel Nova terms of service is quite bad as a legal document and for licensing reasons. IANAL, but I think a lot of this will be obvious.

1. The TOS does not have any definition of the term "site," which is a massive problem for a legally binding license. You would assume what a "site" is to be obvious to a developer, but to a lawyer, this could be bent all over the place. Professional companies and SaSS products define things like "sites" _very carefully_, but the Nova license leaves it open to interpretation.

For example, what if I have multiple subdomains, for multiple clients, on the same TLD. ("client1.example.com", "client2.example.com", "client3.example.com"). Yes, there is a comment in some Nova issue on GitHub I can't find that says this isn't allowed, but a lawyer or developer could bend this all over the place because what defines a "site"? Are subdomains on the same "site"?

Let's pull this further. What if I bought Laravel Nova once and set up a blogging service, which spun up a separate instance of Nova for each subdomain. Separate "sites"? It's the same TLD and company, so, should be allowed.

2. There are two Nova licenses, Solo and Pro. Pro costs $99 more and it says that this is for anyone who makes over 20K on the Nova Homepage. The Terms of Use has **no legal information on this requirement whatsoever**. I could buy a Solo license, make 20 Million dollars, and there is nothing in the Terms of Use which I could be sued from. The Terms of Use is the same for both licenses. Right now, the claim on the homepage that you need a Pro license for making over 20K has no legal teeth whatsoever and is pretty much running entirely on the honor system.

Not only that, but there is no definition for the 20K limit either - there is only "Gross Yearly Revenue < $20k". Does that mean 20K for _this one project_, 20K revenue for the company that hired me as a freelancer, 20K from the company that I was hired by as an employee? 20K of Gross Yearly Revenue from the finished product that I built with Nova? What about when my project makes more than 20K, do I have to upgrade?

The point is, Gross Yearly Revenue of _what_? Myself? The company I'm working for? The company I'm doing freelance work for? It's very vague and almost certainly has no legal teeth.

**Comment by gjsman** [comment]
https://nova.laravel.com/terms

**Comment by davidhemphill** [comment]
We're taking a look into this internally.

**Comment by rikless** [comment]
@gjsman on my side, I think I will not buy pro license again. Email support has almost never helped on my issues, and nowadays, I just have no response. Still using Nova because I think it's a great product, but pro license was not useful for my issues.

**Comment by davidhemphill** [comment]
Projects that meet the Pro license requirements are still required to adhere to them or the license will be refunded and voided.
