### ISSUE TITLE
Computed fields do not show

### ISSUE THREAD

**Issue by lmatab** [laravel/nova-issues#2209]
- Laravel Version: 6.6.2
- Nova Version: 2.8.
- PHP Version: 7.2.25
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:

I have tried to create a computed field  as shown in the docs:

Text::make('Name', function () {
    return $this->first_name.' '.$this->last_name;
}),

It just does not show when trying to created a resource.

Any thoughts ?

**Comment by jbrooksuk** [comment]
A computed field will not show during creation but will show on the index and detail page.

**Comment by lmatab** [comment]
Thanks for the clarification @jbrooksuk .

I need  to create a form that be able to calculate the total given a subtotal and tax info, what would be the way to go  to make it work in nova if it is not computed fields?

Thanks

**Comment by jbrooksuk** [comment]
@lmatab you could use something like https://novapackages.com/packages/codebykyle/calculated-field
