### ISSUE TITLE
Model-Independent Actions 

### ISSUE THREAD

**Issue by MannikJ** [laravel/nova-issues#2211]
It is often the case that actions belong to a specific resource but are not applied on a subset of records (models), but on the whole resource.

For those use cases it would be nice to have an action type that is always visible and executable no matter which models are selected. 

I found the property `$availableForEntireResource` on the action class and set it to `true`, because I thought this could be what I was searching for, but it apparently was not and I still have no clue what this property actually does :)

**Comment by davidhemphill** [comment]
I think this makes sense to add.

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by flexchar** [comment]
@davidhemphill This is actually a really good request. I find it confusing seeing your two comments - what is status on it? :)

**Comment by jbrooksuk** [comment]
@flexchar we always immediately close Feature Requests.
