### ISSUE TITLE
Discard old search request when new one is sent

### ISSUE THREAD

**Issue by WouterFlorijn** [laravel/nova-issues#2213]
- Laravel Version: 5.8.35
- Nova Version: 2.6.1
- PHP Version: 7.1.9

### Description:

With slow search queries, the results can get messed up if one request overtakes another. For example, say I want to search our users for "Wouter", this could happen chronologically:

- I start typing "W"
- Search request 1 is sent with the string "W".
- I continue to type "Wouter".
- Search request 2 is sent with the string "Wouter".
- Request 2 is completed (since it's a lot faster as many more users have "W" in there name than "Wouter").
- Search results for "Wouter" are briefly displayed.
- Request 1 is completed.
- Search results for "W" are now displayed, while the search bar shows "Wouter".

Now I can only update the results again by typing.

Once a new search request is sent, any previously sent requests should be cancelled/discarded.

This also goes for the initial request to display the first page.

### Steps To Reproduce:

1. Have a query that can take a while.
2. Follow scenario above or similar.

**Comment by davidhemphill** [comment]
Unfortunately [Promise Cancellation was killed](https://github.com/tc39/proposal-cancelable-promises), so there's no way using the current system to prevent the slow queries from happening. The only thing we could do here is probably add an option to require the user to click a button to submit a search.

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by WouterFlorijn** [comment]
@davidhemphill well the frontend could just keep track of the requests it sends out right? Just attach an id or timestamp to each request and keep track of the latest_id or latest_timestamp. Then when a promise for an older request resolves, ignore the response.

**Comment by WouterFlorijn** [comment]
Also, I wouldn't say this is a feature request. The search bar isn't functioning properly in some cases. Therefore, it's a bug.

**Comment by bcorcoran** [comment]
I'm running into this as well. I don't think this should be close as it is a solved problem.

@davidhemphill Can you implement debounce? I'm using this on my own SPA to query the same large table that I also use within Nova, and my SPA does not have this issue as a result.

The problem I tend to have is that most people aren't searching for a single letter, so it's best to let them finish typing (hence debounce) instead of searching after every keypress.

For now, I've told my client to type their search out somewhere else and then paste it to search, but this is bad UX at best.

**Comment by davidhemphill** [comment]
The search is already denounced.

**Comment by WouterFlorijn** [comment]
@davidhemphill what do you think about my previous comments? Do you agree that this is a bug and not a feature request? Why was the issue closed?

**Comment by flxsource** [comment]
@davidhemphill Axios does support the use of cancel tokens to discard previous requests (based upon the previously mentioned proposal). I've used this in other places to extend the debounce functionality past the point you send the request.
