### ISSUE TITLE
Show view/edit/delete buttons on the right side regardless of scrolling

### ISSUE THREAD

**Issue by WouterFlorijn** [laravel/nova-issues#2214]
When I have to edit a lot of models with wide tables, I constantly have to scroll right to get to the view/edit/delete buttons.

I think it would be great to either (A) make these sticky, or (B) make them show up when you hover a row.

I would prefer option B, since it would preserve the width of the table (more room for data). To clarify:

![image](https://user-images.githubusercontent.com/7816704/70569214-d1addc80-1b99-11ea-9c68-c637b403d198.png)

Hovering the second row from the bottom would in this case make the buttons show up in the red area.

This would save me a lot of scrolling in some cases. What do you guys think?

**Comment by davidhemphill** [comment]
I think the sticky buttons is a good idea as I run into this myself quite a bit on some of my Nova projects.

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by vesper8** [comment]
any update on this? any plugin that makes the buttons sticky?

or is there a way at least to make the buttons align on the left instead of the right?
