### ISSUE TITLE
Resource Index Select All / Select All Matching not working in Edge

### ISSUE THREAD

**Issue by npakatar** [laravel/nova-issues#2217]
- Laravel Version: 6.6.2
- Nova Version: 2.7.1
- PHP Version: 7.3.12
- Database Driver & Version: MySQL 5.7.22
- Operating System and Version:
Server: Ubuntu 18.04.3 LTS 
User: Windows Pro 10.0.18362
- Browser type and version: 
Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18362

### Description:
Unable to select all resources via the "Select All" or "Select All Matching" 

![SelectAllMatchingEdge](https://user-images.githubusercontent.com/34190637/70635127-60097900-1c01-11ea-944a-aa3dcfeb016b.png)

### Steps To Reproduce:
1. On Edge, navigate to resource index page.
2. Select "Select All Matching (###)" from checkbox drop-down.

Expect:
All resources should be selected and the "Actions" drop-down should appear

Actual:
No resources are selected, "Actions" drop-down fails to render.

**Comment by PKuebler** [comment]
The same problem is in the filters with checkbox.

`checkbox-with-label` don't trigger `@input` on Edge.

**Comment by PKuebler** [comment]
Related: https://github.com/laravel/nova-issues/issues/1505

**Comment by PKuebler** [comment]
Fix:

File `laravel/nova/resources/js/components/Index/Checkbox.vue`

```
<template>
  <input
    type="checkbox"
    class="checkbox"
    :disabled="disabled"
    :checked="checked"
    @input="$emit('input', $event)"
  />
</template>
```

to 

```
<template>
  <input
    type="checkbox"
    class="checkbox"
    :disabled="disabled"
    :checked="checked"
    @change="$emit('input', $event)"
  />
</template>
```
