### ISSUE TITLE
Download file from index view

### ISSUE THREAD

**Issue by disitec** [laravel/nova-issues#222]
It would be great that we could download a file from a relation index view. I can do it in the details view.

![image](https://user-images.githubusercontent.com/12644599/44631175-dcbf0800-a968-11e8-9e46-e71c34171d67.png)

![image](https://user-images.githubusercontent.com/12644599/44631172-d597fa00-a968-11e8-89d8-1fe971d5fa5b.png)

**Comment by disitec** [comment]
There are some fields such as textarea that are hidden by default (I think) There’s no documented way to force the showing of a field

**Comment by MustafaWIthA** [comment]
i think you can force by going to Nova/src/fields/FieldElement and add the below snippet or you can create your own or tweak the other functions
i created this function where you can see it both on index as well as on detail or averywhere 
`public function showeverywhere()
    {
        $this->showOnIndex = true;
        $this->showOnDetail = true;
        $this->showOnCreation = true;
        $this->showOnUpdate = true;
        return $this;
    }`

**Comment by taylorotwell** [comment]
This repository is for tracking bugs. Feature requests may be emailed to Nova customer support.
