### ISSUE TITLE
Null formatted Number field outputs 0

### ISSUE THREAD

**Issue by leigeber** [laravel/nova-issues#2220]
- Laravel Version: 6.7.0
- Nova Version: 2.9.2
- PHP Version: 7.4.0
- Database Driver & Version: PostgreSQL
- Operating System and Version: MacOS
- Browser type and version: Chrome 79

### Description:

The Number field outputs 0 now when the source value is null since the displayUsing callable is executed regardless and number_format on the null value returns 0.

**Comment by rikless** [comment]
There is already a wip PR for this afaik

**Comment by jbrooksuk** [comment]
@rikless which PR are you referring to?

**Comment by leigeber** [comment]
This issue also applies to Currency fields as you'd expect.
