### ISSUE TITLE
BooleanGroup doesn't handle zero-indexed arrays properly

### ISSUE THREAD

**Issue by FrittenKeeZ** [laravel/nova-issues#2222]
- Laravel Version: 5.8.35
- Nova Version: 2.9.0
- PHP Version: 7.3.7

### Description:
Providing a zero-indexed array, the field will use the labels as keys instead of the index.
This is an issue if you work with constants starting with 0.
Reversing or shuffling the keys around will make it work, but obviously not in the intended order.

### Steps To Reproduce:
Having options like
```php
BooleanGroup::make('Statuses')->options([
    0 => 'Status New',
    1 => 'Status Accepted',
    2 => 'Status In Progress',
    3 => 'Status Completed',
    4 => 'Status Cancelled',
])
```
Will be stored as
```json
{
    "Status New": false,
    "Status Accepted": false,
    "Status In Progress": false,
    "Status Completed": false,
    "Status Cancelled": false
}
```
Instead of expected
```json
[
    false,
    false,
    false,
    false,
    false
]
```

**Comment by jbrooksuk** [comment]
Hi @FrittenKeeZ, the `BooleanGroup` field isn't designed to store zero-indexed arrays.

**Comment by FrittenKeeZ** [comment]
Could it be extended with a simple setting?
I got it working by simply extending the `BooleanGroup` and overriding the `options` method.

**Comment by jbrooksuk** [comment]
@FrittenKeeZ by all means, please submit a PR :)

**Comment by emjayess** [comment]
> Hi @FrittenKeeZ, the `BooleanGroup` field isn't designed to store zero-indexed arrays.

🙄

**Comment by FrittenKeeZ** [comment]
For good measure, this is the override I use:
```php
<?php

namespace App\Nova\Fields;

use Laravel\Nova\Fields\BooleanGroup as BaseField;

class BooleanGroup extends BaseField
{
    /**
     * Set the options for the field.
     *
     * @param  array|\Closure|\Illuminate\Support\Collection
     * @return $this
     */
    public function options($options)
    {
        if (is_callable($options)) {
            $options = $options();
        }

        return $this->withMeta([
            'options' => with(collect($options), function ($options) {
                return $options->map(function ($label, $name) {
                    return ['label' => $label, 'name' => $name];
                })->values()->all();
            }),
        ]);
    }
}
```
