### ISSUE TITLE
Destructive actions can apply CanRun closures instead of relying on resources/policies

### ISSUE THREAD

**Issue by peterfox** [laravel/nova-issues#2223]
Nova Version: 2.0.9
Laravel: 6.0

This might be a duplicate of #1611. Essentially I don't understand why the logic for Destructive actions is different from regular actions in that if I add a `CanRun` closure to a destructive action, the closure is called but later code will override the result instead using the authorisation logic of the resources `authorizedToDelete` method instead.

I'm not sure if this is a bug or designed feature. As such I've classed it as a feature request to change this as personally I would like to have the visual look of the destructive action but I do not wish to show the Delete functionality of the resource to the end user, using the action instead to perform a kind of soft delete like functionality on the selected models.

The code for this can be found in `Laravel\Nova\Actions\ActionModelCollection`:

```php
/**
     * Remove models the user does not have permission to execute the action against.
     *
     * @param  \Laravel\Nova\Http\Requests\ActionRequest  $request
     * @return \Illuminate\Support\Collection
     */
    protected function filterByResourceAuthorization(ActionRequest $request)
    {
        if ($request->action()->runCallback) {
            $models = $this->mapInto($request->resource())->map->resource;
        } else {
            $models = $this->mapInto($request->resource())
                           ->filter->authorizedToUpdate($request)->map->resource;
        }

        $action = $request->action();

        if ($action instanceof DestructiveAction) {
            $models = $this->mapInto($request->resource())
                           ->filter->authorizedToDelete($request)->map->resource;
        }

        return $models;
    }
```

As you can see from above the `$models` variable will be set by the if statement for the destructive action instead of the runCallback closure. Instead the code could be something along the lines of:

```php
/**
     * Remove models the user does not have permission to execute the action against.
     *
     * @param  \Laravel\Nova\Http\Requests\ActionRequest  $request
     * @return \Illuminate\Support\Collection
     */
    protected function filterByResourceAuthorization(ActionRequest $request)
    {
        if ($request->action()->runCallback) {
            return $this->mapInto($request->resource())->map->resource;
        }  elseif ($request->action() instanceof DestructiveAction) {
            return $this->mapInto($request->resource())
                           ->filter->authorizedToDelete($request)->map->resource;
        }
       
        return $this->mapInto($request->resource())
                           ->filter->authorizedToUpdate($request)->map->resource;
    }
```

If this is not a bug or a feature request that can be applicable I would highly suggest updating the documentation to make it clear that the canRun closure for actions will not apply for destructive actions as my understanding from reading the documentation was that the destructive action was purely a visual difference and that I could apply my own authorisation logic.

**Comment by aozisik** [comment]
Just ran into this exact thing. Seems wrong to me that there's an exception for destructive actions.

I want to have a destructive action, which doesn't rely on the policy, but the callback passed with `canRun`. Currently, that appears to be impossible without altering Nova's source code.

**Comment by krystianlaubach** [comment]
Any update on this issue? I have faced exactly the same problem.

**Comment by krystianlaubach** [comment]
Just found solution
https://github.com/laravel/nova-issues/issues/1611#issuecomment-993333956
