### ISSUE TITLE
Query keeps pagination when using filters

### ISSUE THREAD

**Issue by dacastro4** [laravel/nova-issues#2224]
- Laravel Version: 6
- Nova Version: 2.4.0
- PHP Version: 7.3

### Steps to Reproduce:

- Open a resource
- Go to the second page
- Use a filter where you have less than the per-page limit but you know you should have results
- You have an empty table
When you use the filter, the query keeps the `limit 26 offset 25` from the pagination and returns an empty table even if you have results

**Comment by jbrooksuk** [comment]
@dacastro4 can you please provide the full Nova version that you're using?

**Comment by dacastro4** [comment]
Sorry about that @jbrooksuk I edited the question

**Comment by jbrooksuk** [comment]
@dacastro4 the latest version is 2.9.2 so you may want to upgrade.

I just did the following test and it worked as expected:

1. Three users in the system, two of which have an active column set to `true`, the other `false`. By default, all three users show in the Users index page.
2. I set the `perPageOptions` to `[1]` so each user displays on their own page.
3. I go to page 2, where I see the inactive user.
4. I enable a Filter to only show me the active users, and am jumped back to the first page.
