### ISSUE TITLE
Reflexive Relationship Creation Bug

### ISSUE THREAD

**Issue by priceluke** [laravel/nova-issues#2225]
- Laravel Version: 6.6.2
- Nova Version: 2.8.0
- PHP Version: 7.3.8
- Database Driver & Version: MySQL 5.7.26
- Operating System and Version: macOS 10.13.6

### Description:
Nova disables fields when creating a relationship. The issue I am having is when i created a 'related' relationship that links two items together it disables both of the drop-downs. I can inspect the element in browser and then it functions as required and the relationship can still be made. Is this a bug or is there a way of overriding it?

I have an observer set up to create and remove the reflexive version of these entries.

![Screen Shot 2019-12-13 at 17 55 30](https://user-images.githubusercontent.com/44372546/70821080-1ae87100-1dd2-11ea-8dbb-568860933baf.png)
![Screen Shot 2019-12-13 at 17 55 15](https://user-images.githubusercontent.com/44372546/70821091-220f7f00-1dd2-11ea-90a8-1c5436a08f95.png)

I think the issue is around the fact I have two of the same foreign keys in one table, both with the same relationship.

Thanks in advance.

## Schema:
```
venue:
    id
    etc

related_venues
    venue1_id
    venue2_id
```

### Model Relationships
```
RelatedVenue
________
    public function main_venue()
    {
        return $this->belongsTo('App\Venue', 'venue1_id');
    }
    public function sec_venue()
    {
        return $this->belongsTo('App\Venue', 'venue2_id');
    }
```

```
Venue
________
    public function relatedTo1()
    {        return $this->hasMany('App\RelatedVenue', 'venue1_id');
    }

    public function relatedTo2()
    {        return $this->hasMany('App\RelatedVenue', 'venue2_id');
    }
```
### Nova Resource
```
Venue
________
           HasMany::make('Related Venues', 'relatedTo1'),
```

```
Related Venue
________
            BelongsTo::make('Main Venue','main_venue', 'App\Nova\Venue')->prepopulate(),
            BelongsTo::make('Related Venue', 'sec_venue', 'App\Nova\Venue')->prepopulate(),
```

**Comment by priceluke** [comment]
**bump**

**Comment by davidhemphill** [comment]
Looks like you're using a third-party field which overrides Nova's default `BelongsTo` field. Please verify this issue presents itself with a completely stock Nova install and feel free to post again. 👍

**Comment by priceluke** [comment]
Tested with stock Nova - works fine. Must be an issue with package. Cheers
