### ISSUE TITLE
Filters doesn't work properly with indexQuery

### ISSUE THREAD

**Issue by tharindu-abans** [laravel/nova-issues#2227]
- Laravel Version: x6.7.0
- Nova Version: v2.9.2
- PHP Version: 7.3.9

### Description:
When I add the `indexQuery` to a resource, filtration doesn't seem to work properly as in additional rows are displayed which should have been filtered out. Filters work fine without the `indexQuery`. 

With `indexQuery`:
![image](https://user-images.githubusercontent.com/48512374/70991755-28fa0280-20ee-11ea-8099-27220438fe53.png)

Without `indexQuery`:
![image](https://user-images.githubusercontent.com/48512374/70991911-855d2200-20ee-11ea-87c9-98a789255d42.png)

### Steps To Reproduce:
My `indexQuery`  looks something like this:

```php
    public static function indexQuery(NovaRequest $request, $query)
    {
        if ($request->user()->hasPermissionTo('view change requests')) {
            return $query;
        }

        return $query->where('user_id', $request->user()->id)
            ->orWhereHas('uatUsers', function ($query) use ($request) {
                $query->where('user_id', $request->user()->id);
            });
    }
```

**Comment by dkulyk** [comment]
You should wrap OR condition.
```php
return $query->where(fn($builder) => $builder
    ->where(...)
    ->orWhereHas(...));

**Comment by tharindu-abans** [comment]
That worked. Thank you so much @dkulyk!

**Comment by dkulyk** [comment]
`condition1 OR condition2 AND filter_condition` interpreted as `condition1 OR (condition2 AND filter_condition)`
