### ISSUE TITLE
Resource index card not loading

### ISSUE THREAD

**Issue by cord** [laravel/nova-issues#2228]
After update to Nova 2.9.2 the resource index card does not load - the loader continues to show.

There are no PHP errors logged, no JS errors in the console and all network requests return status 200.

The nova-api/{resource} request is not triggered.

How can I debug?

**Comment by Gil-1** [comment]
The only way I found is to use Dusk and use waitFor with a sortable field
```
->waitFor('@sort-title')
```

**Comment by jbrooksuk** [comment]
![image](https://user-images.githubusercontent.com/246103/71067998-926d2600-216d-11ea-9844-cb01877aac7a.png)

Resource cards are loading okay for me.

Have you re-published assets etc?

**Comment by cord** [comment]
All resource index card stays like this:

![users 2019-12-20 13-53-03](https://user-images.githubusercontent.com/158588/71256083-140cb180-2330-11ea-8608-ac33053369ba.png)

as said w/o any JS / api / php error.

> Have you re-published assets etc?

Yes, I run these scripts as part of composer.json (I am working with Nova for more than a year):

````
        "pre-update-cmd": [
            "php artisan clear-compiled",
            "php artisan cache:clear",
            "php artisan config:clear"
        ],
        "post-update-cmd": [
            "@php artisan nova:publish"
        ],
````


> The only way I found is to use Dusk and use waitFor with a sortable field
> 
> ```
> ->waitFor('@sort-title')
> ```

Puh... looks to me like another rabbit hole...

Any hint would be appreciated where to start fixing this.

**Comment by cord** [comment]
still facing this situation - any idea how to debug?

**Comment by davidhemphill** [comment]
Closed since you're using a 3rd-party package and there's not been any other similar issues or comments on this.

**Comment by bernhardh** [comment]
@cord:
have you fixed your issue and/or which package does davidhemphill mean?

**Comment by cord** [comment]
@bernhardh the issue was caused by "Nova-Mega-Filter", see https://github.com/dcasia/nova-mega-filter/issues/9 so it was fixed after re-installing the package

**Comment by bernhardh** [comment]
Thank you very much. That solved my problem as well.
