### ISSUE TITLE
Feature Request: Dependent Filter

### ISSUE THREAD

**Issue by alexjose** [laravel/nova-issues#223]
Can we make a dependent filter option based on any other filter selection? For example State and District filters. Once I select any State, the District filter options should be updated with the districts under the selected state.

**Comment by lucasromanojf** [comment]
+1

**Comment by lucasromanojf** [comment]
Also would be great for select fields

**Comment by julianpoma** [comment]
+1

For example, you have an `Assets ` model and in your bussiness, an asset only should be assignable to a `Technician` (type of user). 

Now, the select field on the `asset` shows all users. It would be nice to attach a filter to the relationship, so it only shows the users with a ` Technician` type.

**Comment by alexjose** [comment]
@julianpoma Please see #241

**Comment by taylorotwell** [comment]
This repository is for tracking bugs. Feature requests may be emailed to Nova customer support.

**Comment by aurawindsurfing** [comment]
Did anyone figure how to do this, please?

**Comment by greggh** [comment]
For anyone looking to do this with fields on resources, this will do it:
[https://github.com/orlyapps/nova-belongsto-depend](https://github.com/orlyapps/nova-belongsto-depend)

**Comment by smcnepal** [comment]
Did anyone figure how to do this, please?
