### ISSUE TITLE
Can't load resource: Cannot create property 'currentValue' on string '<'

### ISSUE THREAD

**Issue by threeaccents** [laravel/nova-issues#2232]
- Laravel Version: 5.8.*
- Nova Version: 2.9.2
- PHP Version: 7.3

### Description:
Loading a plain nova dashboard with one resource. The dashboard page loads fine when I go to my resource I get this error:

```bash
TypeError: Cannot create property 'currentValue' on string '<'
    at l.updateFilterState (app.js?id=866a14858a4d8d105161:1)
    at app.js?id=866a14858a4d8d105161:1
    at app.js?id=866a14858a4d8d105161:1
    at Array.forEach (<anonymous>)
    at app.js?id=866a14858a4d8d105161:1
    at l._withCommit (app.js?id=866a14858a4d8d105161:1)
    at l.commit (app.js?id=866a14858a4d8d105161:1)
    at l.commit (app.js?id=866a14858a4d8d105161:1)
    at n.commit (app.js?id=866a14858a4d8d105161:1)
    at app.js?id=866a14858a4d8d105161:1
```

Just created the resource via `php artisan nova:resource` and tried to access it got that error.

### Steps To Reproduce:
1. Create a new laravel install
2. add nova
3. create a model
4. create a nova resource for the model
5. install npm packages and generate app.js file. `yarn install && yarn watch`
6. try to access the resource in the dashboard.

**Comment by bachhuberdesign** [comment]
@threeaccents I'm assuming you fixed this since you closed the issue, but how? I am encountering the same problem with Nova 2.9.3.

**Comment by riceming** [comment]
Same here, same issue in Nova 2.11.1

**Comment by riceming** [comment]
I found the reason why my issue happens.

I have set route starting with "nova-api" to other endpoint, does not point to Nova controller. 

Once I renamed my route to other name, let nova-api route back to Nova controller, issue fixed.
