### ISSUE TITLE
Custom Nova themes : php artisan vendor:publish does not overwrite theme.css file

### ISSUE THREAD

**Issue by zedee** [laravel/nova-issues#2235]
- Laravel Version: 6.8.0
- Nova Version: 2.9.2
- PHP Version: 7.2.24
- Database Driver & Version: mySQL 5.7 (on Docker)
- Operating System and Version: Ubuntu 16.04.06 (on Docker)
- Browser type and version: Chrome for linux latest (79.0.3945.88 x64)

### Description:
Once published theme assets for first time, the subsequent times the command `php artisan vendor:publish` is ran, does not overwrite the existing `theme.css` file on the `public/mynamespace/my-theme` folder.

### Steps To Reproduce:
* Create new theme with `php artisan nova:theme zedee/my-theme`
* Execute `php artisan vendor:publish`, select your number `[x]` which corresponds to your `ThemeServiceProvider` on the list. Reload your backend and you'll see new theme is applied.
* After that, modify the `theme.css` in the `nova-components/MyTheme/resources/css/` directory.
* And execute `php artisan vendor:publish`, select your `[x]` corresponding to your `ThemeServiceProvider` again
* Published `theme.css` file is not updated.

I've checked out already it's not a cache issue.

Only workaround I've tried is to delete the `public/zedee/my-theme/` folder.

**Comment by jbrooksuk** [comment]
Try using the `--force` flag.

**Comment by zedee** [comment]
> Try using the `--force` flag.

I tried but that didn't do the trick :(

**Comment by mattiaefesto** [comment]
Same error here, but with the --force flag it will update the theme.
Do I have to do the publish every time I edit my CSS?

**Comment by beneyraheem** [comment]
try php artisan clear

**Comment by nikans** [comment]
Still the same

**Comment by kylescousin** [comment]
This is still an issue.
