### ISSUE TITLE
Form text fields reset to a different user

### ISSUE THREAD

**Issue by heyaj19** [laravel/nova-issues#2237]
- Laravel Version: 5.8
- Nova Version: 2.0.9
- PHP Version: 7.2.
- Database Driver & Version: MySql

- Browser type and version: Mozilla, Chrome newest releases

### Description:
I am having an issue where if I pick to edit my user fields - when the page first loads it loads the correct fields but immediately loads a different user right after this is just the text fields as the profile picture is of the user I selected.

**Comment by jbrooksuk** [comment]
You're using an out of date version of Nova, we're now at v2.9.2. Can you please upgrade and try again. If you still have this issue, please feel free to re-open the issue.
