### ISSUE TITLE
Action giving timeout on bulk edit. 

### ISSUE THREAD

**Issue by gldrenthe89** [laravel/nova-issues#2238]
- Laravel Version: 6.8
- Nova Version: 2.9.2
- PHP Version: 7.3.12
- Database Driver & Version: MySQL 8.0.18
- Operating System and Version: macOS 10.15.2
- Browser type and version: Firefox 71.0
- Reproduction Repository: not available

### Description:
When running an queable action against all rows( 77k+)  it chunks this per 200 rows. The problem is that it is taking too long to queue al the chunks and the dialog is getting an time out en doesn't go away. 

the only thing i need are the ID's of the models. they wil be used in a many to many relation to create exports. I do not need the whole model. Just the ID's from the selection in an array so ik can use this in an Attach or Sync function.

**Comment by jbrooksuk** [comment]
There are a couple of things that you can do:

1. Within your `Action` class, you can override the `chunkCount` property to something else (this may require testing).

    ```php
    /**
      * The number of models that should be included in each chunk.
      *
      * @var int
       */
    public static $chunkCount = 200;
    ```

2. You can extend the timeout on your queue.

**Comment by gldrenthe89** [comment]
> There are a couple of things that you can do:
> 
> 1. Within your `Action` class, you can override the `chunkCount` property to something else (this may require testing).
>    ```
>    /**
>      * The number of models that should be included in each chunk.
>      *
>      * @var int
>       */
>    public static $chunkCount = 200;
>    ```
> 2. You can extend the timeout on your queue.

As stated. Chunking it takes too long. 80k of rows chunking with chunks of 100 (cause this is the max otherwise there are mem issues) takes to long. Now there are 80k of rows. But this wil be around the 250k in about a couple of months. 

There should be a better way. I also tried to overide handleRequest on the action.

**Comment by gldrenthe89** [comment]
> There are a couple of things that you can do:
> 
> 1. Within your `Action` class, you can override the `chunkCount` property to something else (this may require testing).
>    ```
>    /**
>      * The number of models that should be included in each chunk.
>      *
>      * @var int
>       */
>    public static $chunkCount = 200;
>    ```
> 2. You can extend the timeout on your queue.

Can you please reopen this. It is so stupid to close this while the problem stil persists.

**Comment by iSWORD** [comment]
This shouldn't be closed. Running any Nova actions on a large number of resources times out even if the action did absolutely nothing at all.

@themsaid could you please check this out and let me know if there's anything I can do on my end to run my actions efficiently? Thank you in advance.
