### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by maartendraijer** [laravel/nova-issues#224]
Hi! After installing Nova v1.0.6 I get the following error message at any resource page:

```
TypeError: Cannot read property 'length' of undefined
    at a.hasResources (app.js?id=963063089996631dabb8:1)
```

Is anyone else experiencing the same issue?

**Comment by mydnic** [comment]
I have the same issue and I believe it's related to having a VueJS SPA because somehow all requests from nova like `/nova-api/` responds with my VueJS 404 page of my SPA.

My routes/web.php is like this

```php
if (!request()->ajax()) {
    Route::get('/{any}', 'HomeController@index')->where('any', '.*');
}
```

It should work but it doesn't... don't know why..

**Comment by mydnic** [comment]
Found the solution

```php
Route::get('/{any}', 'HomeController@index')->where('any', '^(?!nova-api).*$');
```

https://mydnic.be/post/routing-issue-with-laravel-nova-and-a-vuejs-spa

**Comment by luceos** [comment]
Confirmed to fix it.
