### ISSUE TITLE
Class name must be a valid object or a string

### ISSUE THREAD

**Issue by atmacoder** [laravel/nova-issues#2240]
- Laravel Version: 6.9.0
- Nova Version: 2.9.2
- PHP Version: 7.3.10
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:

After fresh install 
error on

/vendor/laravel/nova/src/Nova.php224

return $resource::authorizedToViewAny($request)

```
ErrorException (E_ERROR)
Class name must be a valid object or a string (View: /var/www/cportal/data/www/mysite.com/vendor/laravel/nova/resources/views/layout.blade.php) (View: /var/www/cportal/data/www/mysite.com/vendor/laravel/nova/resources/views/layout.blade.php)
Previous exceptions
Class name must be a valid object or a string (View: /var/www/cportal/data/www/mysite.com/vendor/laravel/nova/resources/views/layout.blade.php) (0)
Class name must be a valid object or a string (0)
  
```
![Image of error](https://i111.fastpic.ru/big/2019/1222/5f/ae22d5b581f10c779b1408d16d6cdb5f.jpg)

**Comment by rapidtechsolutions** [comment]
Same issue, following

**Comment by atmacoder** [comment]
reinstall everything, and now it works...

**Comment by davidhemphill** [comment]
Make sure any customized layout is in sync with the current versions and this should fix the issue. 👍

**Comment by AlbinoDrought** [comment]
I encountered this issue as well. The error message is quite cryptic. Read-only views for the affected resource worked, but edit/attach/detach was not working.

We had this in our resource: `public static $model = '\App\Foo';`.

Changing it to `public static $model = 'App\Foo';` or `public static $model = Foo::class;` fixed this issue for us.

`Nova::resourceForModel` uses `get_class` if it's passed an object. `get_class` returns the class name without the leading slash and `\App\Foo` != `App\Foo`, so Nova wasn't able to find a resource for that model.
