### ISSUE TITLE
Multiple guards with separate table

### ISSUE THREAD

**Issue by zareismail** [laravel/nova-issues#2245]
Hi. I have a question.
Please explain that login by multiple guards is possible? 
If not; why?

**Comment by jbrooksuk** [comment]
Hey,

Can you give an example of why this is needed?

**Comment by zareismail** [comment]
Yes of course;

Because many of customer wants. on the other hand; many systems need multiple guards and multiple paths for user logins, like shopping system. some little system needs multiple logins but doesn't need ACL systems. some customers don't pay for ACL. and etc.

**Comment by davidhemphill** [comment]
Closed since this seem more like a sales question than a problem you've experienced inside Nova. Please feel free to direct sales/support questions to nova@laravel.com. 👍
