### ISSUE TITLE
How to add index column in index page 

### ISSUE THREAD

**Issue by odaiderawi** [laravel/nova-issues#2246]
How i can add column like this so i can see the number of each row "Not ID"
 1, 2, 3 and so on
and if i re sort the items the index column still on the same 

![image](https://user-images.githubusercontent.com/36736057/71470833-2f673900-27d6-11ea-9631-c1a47355e5ef.png)

**Comment by milewski** [comment]
You will need to do a custom package for that, for reference you could look into the source code of this package: https://github.com/michielkempen/nova-order-field it has some logic to detect when the entry is the first item of the resource list and the last one

**Comment by jbrooksuk** [comment]
Please see the package link above :)
