### ISSUE TITLE
Global search not working in production (for me, probably not a bug)

### ISSUE THREAD

**Issue by mikecornille** [laravel/nova-issues#2248]
- Laravel Version: 5.8.35
- Nova Version: 2.6.1
- PHP Version: 7.3.9

I'm using Algolia for my searches and they are working fine on individual resources. Global search is working well locally but not in production.  I get a "Server Error" on the front end when I attempt to search and below is the log.  I do use two different "apps" in Algolia, one for testing locally and one for production.  My env keys are correct.  I don't know how to go about fixing this.   

[2019-12-18 16:01:20] production.ERROR: Index deposits does not exist {"userId":1,"exception":"[object] (Algolia\AlgoliaSearch\Exceptions\NotFoundException(code: 404): Index deposits does not exist at /home/forge/xxxxx.com/vendor/algolia/algoliasearch-client-php/src/RetryStrategy/ApiWrapper.php:208) [stacktrace]

**Comment by daugaard47** [comment]
@mikecornille Having same issue. Global Search works on local, but not in development. Only error I get is "Server Error" when I try and search. No stack trace in log files either.. Very hard to trouble shoot.
Did you figure this out? If so, how?

**Comment by Pamposgsk** [comment]
> @mikecornille Having same issue. Global Search works on local, but not in development. Only error I get is "Server Error" when I try and search. No stack trace in log files either.. Very hard to trouble shoot.
> Did you figure this out? If so, how?

same problem here
did you find any solution for this?

**Comment by sofia-fischer** [comment]
In case somebody is having the same issue ;) 

A response in [this Article](https://bestofphp.com/repo/algolia-algoliasearch-client-php) gave me the hint 

> Some of our indexes don't have enough events to train models so they shouldn't be used for recommendations, but it's possible that we misconfigure this somewhere, or that the number of events drops for indexes that did have enough events at some point.

**The Solution**
In my case with the error you described I created an index by hand on the Algolia Web View (in your case one named `deposits`). The search was working again.
