### ISSUE TITLE
partition metric  errors with different widths

### ISSUE THREAD

**Issue by Artessan** [laravel/nova-issues#2249]
- Laravel Version: 6.9.0
- Nova Version: 2.9.2
- PHP Version: 7.4
- Database Driver & Version: pgsql 11
- Operating System and Version: windows 10
- Browser type and version: edge chromiun beta

### Description:
- when a partition metric card  with one item in count and full width is rendered the chart overflow the card body.
![Captura de pantalla (56)](https://user-images.githubusercontent.com/4217243/71514834-b4b72000-28a0-11ea-8037-9d68fc138709.png)

- if the text of the metric item is to long the chart is over the content.  (screen >= 1920 X 1080 )
![Captura de pantalla (57)](https://user-images.githubusercontent.com/4217243/71514977-5a6a8f00-28a1-11ea-953c-ff472eda00dd.png)

**Comment by mvdnbrk** [comment]
Related to #1698
