### ISSUE TITLE
Page expired

### ISSUE THREAD

**Issue by freshface** [laravel/nova-issues#225]
If a am not using Nova for a couple of hours and refresh the page i get a  " The page has expired due to inactivity. " message. If I refresh it does not work. After logout and login i get the same message.

I need to log out, clear the cache and logon again to work.

<img width="678" alt="screen shot 2018-08-26 at 23 03 20" src="https://user-images.githubusercontent.com/103913/44632972-88298600-a984-11e8-8648-eef0a59f4564.png">

**Comment by judge2020** [comment]
This is a feature with Laravel's CSRF protection, directly based off of the user's session. If the user's session is idle for too long, it will prevent form submissions to protect against CSRF attacks. The timeout for this can be changed via the env `SESSION_LIFETIME` or in `config/session.php`.

In general Laravel+Vue applications use CSRF via a header/cookie, so on reload everything should work again. See if you have any ad-blocking/privacy/etc settings/extensions that may be manipulating cookies (try another browser?). 

A temporary solution if you can't fix it is to increase that global `SESSION_LIFETIME` to 3/4 hours, however this will be a global change to your application that you may not want.

**Comment by freshface** [comment]
I use the latest firefox.
I will try in safari or chrome.

**Comment by taylorotwell** [comment]
We are unable to debug your issue without a recreatable code example.
