### ISSUE TITLE
money_format() used in Currency field is deprecated in PHP 7.4

### ISSUE THREAD

**Issue by rene0399** [laravel/nova-issues#2253]
- Laravel Version: n/a
- Nova Version: n/a
- PHP Version: 7.4

### Description:
The Currency field that uses PHP underlying money_format() function throws an error, because money_format() is deprecated.

https://www.php.net/manual/en/migration74.deprecated.php#migration74.deprecated.core.money-format

### Steps To Reproduce:
install php 7.4 and use a Currency field.

**Comment by jbrooksuk** [comment]
Duplicate.

**Comment by cotiga** [comment]
If there is a duplicate, please show us the original.
Google leads me on this issue

**Comment by jbrooksuk** [comment]
This is already fixed in https://github.com/laravel/nova/pull/747
