### ISSUE TITLE
Find resource go to 404 error when change model key name

### ISSUE THREAD

**Issue by zareismail** [laravel/nova-issues#2254]
- Laravel Version: 6.*
- Nova Version: 2.*
- PHP Version: 7.3 

Hi.
Changing the primary key name of a model; causes a 404 error. because nova uses the `id` for `CRUD` links.

example:

```
class Currency extends Model 
{


    /**
     * Get the primary key for the model.
     *
     * @return string
     */
    public function getKeyName()
    {
        return 'code';
    }
}
```

Mentioned example cause a 404 error.

**Comment by vesper8** [comment]
@zareismail did you find a solution? this is obviously not the right way to change the primary key but this seems like it's nowhere to be found in the docs

**Comment by crynobone** [comment]
I tried to replicate the issue and this seem to work. 

```php
class Currency extends Model
{
    /**
     * The primary key for the model.
     *
     * @var string
     */
    protected $primaryKey = 'code';

    /**
     * The "type" of the primary key ID.
     *
     * @var string
     */
    protected $keyType = 'string';
}
```

```php
/**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [
            ID::make('code'),
        ];
    }
```

Closing this for now, please create a new issue if you still having issue with this.
