### ISSUE TITLE
BelongsTo relation takes its name from resource and ignore renaming

### ISSUE THREAD

**Issue by davidgabbay** [laravel/nova-issues#2256]
BelongsTo::make('recipient', 't_customers', 'App\Nova\t_customers')->searchable()->sortable()->textAlign('right')

When on "form-Edit or Create"  it takes its name "customer" from the resource 

instead of "recipient" as described in the code.

in "view" its o.k

It was o.k on Nova Ver 2.7
Now i"m working on - Nova 2.9.2

**Comment by dsampaolo** [comment]
**Nova v2.9.2**

Same error here.

`BelongsTo::make('From', 'from', Page::class),`

On index, it displays "From", but on update/edit, it shows "Page".

**Comment by albalooshi** [comment]
Nova v2.9.2

Same issue.

**Comment by albalooshi** [comment]
Quick fix for now, change line 120 of this file `nova/src/Fields/BelongsTo.php` from this:
`$this->singularLabel = $resource::singularLabel();`
to this
`$this->singularLabel = $name;`

**Comment by mikebronner** [comment]
Thanks, created PR https://github.com/laravel/nova/pull/792

**Comment by davidhemphill** [comment]
Looks like this was fixed in laravel/nova#792 so closing.
