### ISSUE TITLE
Ranged Partition

### ISSUE THREAD

**Issue by judahnator** [laravel/nova-issues#2257]
A feature request that I got from one of my clients was to add support for a ranged partition, so they can see changes over time.

Unfortunately my Vue skills are not quite up to the challenge, so ill just leave this issue here to be approached when the developers of this fine project have time to consider it.

**Comment by fgilio** [comment]
Maybe this is helpful: https://github.com/beyondcode/nova-filterable-cards

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
