### ISSUE TITLE
Specified model in custom ActionResource class not used

### ISSUE THREAD

**Issue by j-shelfwood** [laravel/nova-issues#2258]
- Laravel Version: 6.6.2
- Nova Version: 2.9.2
- PHP Version: 7.3
- Database Driver & Version: MYSQL 5.8
- Operating System and Version: MacOS catalina
- Browser type and version: Chrome version 79

### Description:
Overwriting the action resource class as shown in the documentation does not have the expected effect when defining observers for the newly specified model in the resource. It ignores the observers defined by us, and only uses the model event handlers defined in the source code.

### Steps To Reproduce:

- Create your own action resource model that extends the nova action resource class
- Define your own ActionEvent model in the resource class (public static $model = YourOwnActionEvent::class)
- Define observers or model event handlers to mutate data before it is saved
    -In our specific case we wanted to change the id column to have a UID as value. So naturally we define a created() model event handler to supply it with the UID. This does not work as expected and our handlers are ignored.

In issue #2178 ResourceStoreController.php line 39 is mentioned; 
```
ActionEvent::forResourceCreate($request->user(), $model)->save();
```
If this change would be made in the source code, it would function properly. I doubt that this is the only place where changes have to be made though.
```
ActionResource::$model::forResourceCreate($request->user(), $model)->save();
```

**Comment by MadMikeyB** [comment]
Is this resolved?
