### ISSUE TITLE
Eloquent events cancelling creation should be handled better

### ISSUE THREAD

**Issue by stancl** [laravel/nova-issues#2259]
- Laravel Version: 6.9.0
- Nova Version: 2.9.2
- PHP Version: 7.4
- Database Driver & Version: sqlite
- Operating System and Version: Ubuntu 19.04
- Browser type and version: Chrome

### Description:

I use a `creating` event listener in my model's `boot` method to cancel the creation of the model if  a condition is met.

Creating a resource in Nova leads to this error:

```php
SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: action_events.actionable_id (SQL: insert into "action_events" ("batch_id", "user_id", "name", "actionable_type", "actionable_id", "target_type", "target_id", "model_type", "model_id", "fields", "original", "changes", "status", "exception", "updated_at", "created_at") values (8f845a78-cf6e-4771-b295-fdc4a369d0cc, 1, Create, App\Domain\Order\Models\OrderFee, ?, App\Domain\Order\Models\OrderFee, ?, App\Domain\Order\Models\OrderFee, ?, , ?, {"code":"payment_method","value":"cod","price":{},"order_id":16,"vat_rate":0.21}, finished, , 2020-01-02 17:29:23, 2020-01-02 17:29:23))
```

### Steps To Reproduce:

Try creating a resource whose model has a `creating` event listener like this:

```php
public static function boot()
{
    parent::boot();

    static::creating(function (OrderFee $orderFee) {
        return ! $orderFee->order->fees()->where('code', $orderFee->code)->exists();
    });
}
```

**Comment by blumtech** [comment]
Hi, 
I also faced this issue. 
My solution was to create a custom validation rule and use this rule to prevent the creation.

**Comment by stancl** [comment]
I see. I was also thinking about throwing an exception instead of return g false, because Nova seems to handle exceptions better.

Still reporting this due to the weird error about action_events table.

Thanks though. Custom validation rule is probably the cleanest solution.

**Comment by kakajansh** [comment]
Had similar issue, solved by [this comment](https://github.com/laravel/nova-issues/issues/1832#issuecomment-522207118)

```php
use Laravel\Nova\Actions\ActionEvent;
```
```php
ActionEvent::saving(function ($actionEvent) {
    if (is_null($actionEvent->actionable_id)) {
        return false;
    }
});

**Comment by davidhemphill** [comment]
@stancl This is probably something you should handling in a validation rule further up the stack.
