### ISSUE TITLE
Package laravel/nova cannot install after composer update

### ISSUE THREAD

**Issue by devmsh** [laravel/nova-issues#226]
After successful nova installation, and run composer update, must of time this error appear:

```
  Package laravel/nova cannot install to "/Volumes/Workspaces/projects/Sites/sport/nova" inside its source at "/Volumes/Workspaces/projects/Sites/sport/nova"  
```

**Comment by GuidoHendriks** [comment]
Remove the symbolic link named `nova` from `vendor/laravel`.

**Comment by devmsh** [comment]
Even if this trick works, it's not appear like a solution?

**Comment by GuidoHendriks** [comment]
Nope, not really... Wish there was a better way.

**Comment by DivineOmega** [comment]
I'm also experiencing this issue. Manually removing the symlink shouldn't be required.

**Comment by swilsdon** [comment]
I am also getting this problem. Anyone have any luck in finding a proper solution?

**Comment by davidhemphill** [comment]
Just added support for updating Nova via composer: https://nova.laravel.com/docs/1.0/installation.html#updating-nova

**Comment by DivineOmega** [comment]
@davidhemphill Thanks!

**Comment by Pi-George** [comment]
Hi, I'm having this same issue on a library of ours. Do you know the commit hash that fixed this so that I can have a look? @davidhemphill

**Comment by Pi-George** [comment]
Found the issue, it was a bug in composer, composer doesn't know how to unsymlink properly
