### ISSUE TITLE
Fail to apply filter when query uses subquery

### ISSUE THREAD

**Issue by milewski** [laravel/nova-issues#2260]
- Laravel Version: 6.9.0
- Nova Version: 2.9.2
- PHP Version: 7.4
- Database Driver & Version: MySQL 8

### Description:

If there is a subquery applied to the indexQuery and a filter tries to apply some extra filtering logic on top using the returned value of the subquery nova fails to issue the "count" request

### Steps To Reproduce:

Having a resource with a subquery like this:

```php
public static function indexQuery(NovaRequest $request, $query)
{
    return $query->addSelect([
        'total_spent' => SomeModel::whereColumn('client_id', 'clients.id')->selectRaw('SUM(price)')
    ]);
}
```

This works fine, it shows the resource on index as expected, then making use of any filter that interacts with the subquery like this:

```php
class TotalSpentFilter extends SliderFilter
{
    public function apply(Request $request, $query, $values)
    {
        return $query->havingBetween('total_spent', $values);
    }
}
```
Nova will issue an request to: 

```
https://nova.docker.localhost/nova-api/clients?filters=......
```

Which works fine for the main resource request, however nova does and extra request to get the count:

```
https://nova.docker.localhost/nova-api/clients/count?filters=.....
```

And it seems that this API doesn't use the same `$query` returned from `indexQuery( )` because it fails with the following error:

```
message: "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'total_spent' in 'having clause' (SQL: select count(*) as aggregate from `clients` having `total_spent` between 0 and 100)"
```

![image](https://user-images.githubusercontent.com/2874967/71734088-086bcf80-2e86-11ea-83b3-32a50e102694.png)

**Comment by akatche** [comment]
Hi, I´m having the same issue, there is some walkaround? Thanks in advance

**Comment by JJCLane** [comment]
Hey so I had this issue earlier today, the way I resolved it was instead of using selectRaw, I used fromRaw to wrap the subqueries so that Nova can calculate the count and apply where filters normally without dealing with aggregates.

**Comment by jbrooksuk** [comment]
@JJCLane has provided the solution :)
