### ISSUE TITLE
Select field is not working in the ui when using camelCase fields

### ISSUE THREAD

**Issue by avifatal** [laravel/nova-issues#2261]
- Laravel Version: 6.0
- Nova Version: 2.9.2
- PHP Version: 7.3
- Database mysql  5.7:
- Operating System and Version: Docker - Laradock
- Browser type and version: Crome

### Description:
I have a field that I named it in the database `postStatus`, it is now working in the UI, but is saved in the database.
it won't be displayed in the grid/view/edit screen.
When I changed it to `poststatus` it is working...

**Comment by antlusher** [comment]
I believe Nova/Laravel only supports snake case (underscores) - from docs

#Field Column Conventions
As noted above, Nova will "snake case" the displayable name of the field to determine the underlying database column. However, if necessary, you may pass the column name as the second argument to the field's make method:

**Comment by jbrooksuk** [comment]
@antlusher is correct here. You can pass it through as a second parameter as per the docs.
