### ISSUE TITLE
Metrics don't work if created_at is unix timestamp

### ISSUE THREAD

**Issue by BOR4** [laravel/nova-issues#2262]
- Laravel Version: 6.9.0
- Nova Version: 2.9.2
- PHP Version: 7.3
- Database Driver & Version: mysql 5.7.28
- Operating System and Version: ubuntu 16.0.4
- Browser type and version: mozilla
- Reproduction Repository: https://github.com/###/###

### Description:
I tried creating simple trend metric on my model which has created_at as unix timestamp. Widgets always show 0. Unix timestamp is converted to datetime in fields without any problem. However metrics don't work on this model.

### Steps To Reproduce:
Create an Eloquent model with:

    protected $timestamps = [
        "created_at"
    ];

    protected $dateFormat = "U";

Then try to create any metric with it and it will always show 0

**Comment by antlusher** [comment]
Morning - I believe you need to pass "X" for Unix. And also, from the docs, https://momentjs.com/docs/#/parsing/string-format/

I might be wrong tho

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
