### ISSUE TITLE
Duplicate ajax requests are sent when forms are submitted on firefox ESR.

### ISSUE THREAD

**Issue by masterwto** [laravel/nova-issues#2265]
- Laravel Version: 6.9.0
- Nova Version: 2.9.2
- PHP Version: 7.3.9 & 7.4.1
- Database Driver & Version: MariaDB 10.3.9
- Operating System and Version: Windows 7 64bit
- Browser type and version: Mozilla Firefox 68.1.0 ESR
- Reproduction Repository: https://github.com/###/###

### Description:
Duplicate ajax requests are sent when forms are submitted on firefox ESR.

### Steps To Reproduce:
I clicked the submit button on any Creation Form by nova, and duplicate ajax requsts are sent.

<img src="https://github.com/masterwto/nova-issues/blob/master/img/1.PNG?raw=true">
<img src="https://github.com/masterwto/nova-issues/blob/master/img/2.PNG?raw=true">

My Firefox is 68.1.0 ESR
<img src="https://github.com/masterwto/nova-issues/blob/master/img/3.PNG?raw=true">

**Comment by davidhemphill** [comment]
I'm not able to replicate this issue on the given version of your browser using the steps you've provided. Make sure your applications JavaScript assets are up-to-date. The screenshots show the version number of Nova as v2.5.0 not v2.9.2 as your description lists.
