### ISSUE TITLE
Actions: inconsistent behavior happening when selecting resources manually vs clicking on select all matching (n)

### ISSUE THREAD

**Issue by milewski** [laravel/nova-issues#2266]
- Laravel Version: 6.9
- Nova Version: 2.9.2
- PHP Version: 7.4

### Description:

If the resources were selected by clicking on the `Select All Matching (N)`: 

![image](https://user-images.githubusercontent.com/2874967/71762588-faf92880-2f0b-11ea-9186-aa5c8e0619cd.png)

Nova will send a request to the server when executing any actions with a payload:

```php
https://dashboard.docker.localhost/nova-api/clients/action?action=export-clients&........

{ resources: all }
```
Which then lands into an internal method that decides if its a match all resources etc..:

```php
// nova internal ActionRequest.php
protected function toSelectedResourceQuery()
{
    if ($this->forAllMatchingResources()) {
        return $this->toQuery();
    }

    return $this->viaRelationship()
                    ? $this->modelsViaRelationship()
                    : $this->newQueryWithoutScopes();
}
```

`->toQuery()` will then call `::buildIndexQuery()` therefore whatever the constrains written on the indexQuery() method are applied, all good.

However, the same thing doesn't happen when you manually select the resources and execute an action, it uses a new query instead of the one returned from the `indexQuery()` as it never calls `::buildIndexQuery()` which is leading to an inconsistent behavior... 

Essentially this fix this issue: 

```diff
// nova internal ActionRequest.php
public function chunks($count, Closure $callback)
    {
        $output = [];

        $this->toSelectedResourceQuery()->when(! $this->forAllMatchingResources(), function ($query) {

+            $resource = $this->resource();
+            $resource::buildIndexQuery(
+               $this, $query, $this->search,
+               $this->filters()->all(), $this->orderings(), $this->trashed()
+            );

            $query->whereKey(explode(',', $this->resources));

        })->latest($this->model()->getKeyName())->chunk($count, function ($chunk) use ($callback, &$output) {
            $output[] = $callback($this->mapChunk($chunk));
        });

        return $output;
    }
```

There is a similar issue: https://github.com/laravel/nova-issues/issues/1501 but was closed for lack of communication, but to complement this issue, 

What Im trying to do is on my indexQuery method I add a bunch of "subQuery" that add some extra properties and "pre-load" some relationship, which works in conjunction with another package I have developed here: https://github.com/dcasia/nova-mega-filter

![image](https://user-images.githubusercontent.com/2874967/71762895-8f658a00-2f10-11ea-9139-84dab105793e.png)

However, when executing an action with the `manually selected resources`, a lot of relationships and attributes appended/loaded from the indexQuery() are not present, leaving no way to re-add them back without re-querying the database again to bring all these attributes back!

**Comment by royduin** [comment]
I've got a similar issue, but I'm currently using a global scope on my model which modifies the query. Works great on index but is removed with actions. Applying the global scope in the `indexQuery()` has the same issue because `toSelectedResourceQuery()` removes the global scopes. I could change it to a local scope and use that in the `indexQuery()` but then I'm at the point where you are now that the `indexQuery()` is not used when selecting resources instead of using the "select all".

**Comment by fgilio** [comment]
We're having this same problem right now and also related to adding a bunch of `addSelect`. Any idea on how to solve it?
Will get back if we find any solution

**Comment by fgilio** [comment]
Hi @jbrooksuk! Is this in your radar? Anything we can do to help? I don't yet feel confortable with Nova's internals to propose a PR

**Comment by davidhemphill** [comment]
Will take a look at this issue this week. 👍

**Comment by davidhemphill** [comment]
What's the easiest way to show this issue in a fresh Nova instance?

**Comment by milewski** [comment]
@davidhemphill I think this gives more or less the good direction, applying the changes I proposed above would result in having the `injected_value` filled in when executing the action

```php

class Client extends Resource
{

    public static function indexQuery(NovaRequest $request, $query)
    {
        /**
         * Add something h
         */
        return $query->addSelect([
            'injected_value' => User::query()
                                  ->whereColumn('user_id', 'users.id')
                                  ->selectRaw('SUM(id)'),
        ]);
    }

    public function fields(Request $request)
    {
        return [
            Number::make('Injected Value', 'injected_value'),
        ];
    }

    public function actions(Request $request)
    {
        return [
           new class extends Action {
             
               public function handle(ActionFields $fields, Collection $models)
               {

                   /**
                    * This should be set
                    */
                   dd($models->first()->injected_value);
                   
               }
               
           }
        ];
    }

}
```

**Comment by davidhemphill** [comment]
@milewski Gave your fix a quick run and it broke some tests, so it looks like a fix will have to wait a bit longer.

**Comment by milewski** [comment]
Well that fix was done for an older version of nova perhaps even using nova V2 as this issue was open on January... Probably something has changed since then

**Comment by crynobone** [comment]
Made a PR to solve the issue:

* Only cater when `$this->viaRelationship()` is `false`. I'm not certain what would be the right behaviour when accessing `viaRelationship`, since it should be accessed from `ParentResource::relatedQuery()` and not `Resource::indexQuery()`.
* Use `Resource::indexQuery()` instead of `Resource::buildIndexQuery()` since we shouldn't need to care about filtering etc when accessing directly by ids.

**Comment by fgilio** [comment]
Thanks @crynobone, this works perfectly fine and allowed us to remove a way uglier patch that we had.
