### ISSUE TITLE
Moontoast/math abandoned

### ISSUE THREAD

**Issue by LorenzoSapora** [laravel/nova-issues#2270]
Composer recommends changing `moontoast/math` for `brick/math`.

https://packagist.org/packages/moontoast/math

Writing a PR for this now.

**Comment by crynobone** [comment]
Nova requires this because it is used via ramsey/uuid. has ramsey made the change yet?

**Comment by jbrooksuk** [comment]
Nope, it doesn't seem so :)

**Comment by syntafin** [comment]
Any updates on it?

**Comment by ItaloBC** [comment]
> For the 3.x series of ramsey/uuid, you may continue to use moontoast/math. It's not going anywhere—it just won't get anymore updates or features. Version 4.x of ramsey/uuid (alpha version coming soon 🤞) gets rid of the need for moontoast/math.

https://github.com/ramsey/uuid/issues/288

[There is already an alpha](https://github.com/ramsey/uuid/releases/tag/4.0.0-alpha1). Since Laravel also uses Ramsay's UUID under the hood, it may break some code, so the upgrade will be slow it seems.

**Comment by ramsey** [comment]
> it may break some code, so the upgrade will be slow it seems

For the standard, default usage of ramsey/uuid in Laravel, (mostly) nothing will break. If you are using the interfaces to customize ramsey/uuid with your own classes, then something might break because some of the interfaces are changing.

I will document all the changes in the changelog, and I'll provide highlights for upgrading in the readme. 😄

**Comment by likeadeckofcards** [comment]
@jbrooksuk Has there been any movement with this? Looking at Laravel/Framework the dependency for Ramsey/uuid has been updated to version 4.

**Comment by masterix21** [comment]
Hi guys, some news about it? I don't know if I'm wrong but seems there are no references to Moontoast in the Nova code: only on its composer.

![image](https://user-images.githubusercontent.com/6555012/135427600-52ce8808-fa7b-4154-ae5c-4ea42f5737de.png)

**Comment by rvanbaalen** [comment]
Still nothing? Updated to the latest laravel/nova and moontoast/math is still a dependency.

**Comment by ramsey** [comment]
After making some changes to the test files so that PHPUnit runs properly on PHP 8, all the tests for moontoast/math still pass on PHP 8, without needing changes to the actual library code. So, while I'm no longer maintaining it, it still works. "Abandoned" doesn't mean "broken." 😄
