### ISSUE TITLE
Use of undefined constant request - assumed 'request' (this will throw an Error in a future version of PHP)

### ISSUE THREAD

**Issue by atmacoder** [laravel/nova-issues#2271]
Laravel Version: 6.9.0
Nova Version: 2.9.2 
PHP Version: 7.3.10

When click detail view any resources
like example
http://mysite.com/nova/resources/users/1

```
Use of undefined constant request - assumed 'request' (this will throw an Error in a future version of PHP)
```

![image](https://i111.fastpic.ru/big/2020/0107/2a/4f1a61c4806be5eeefa8b569188c3f2a.png)

**Comment by davidhemphill** [comment]
This looks like a mistyped variable in one of your resource files.

**Comment by atmacoder** [comment]
> This looks like a mistyped variable in one of your resource files.

Everything is ok there, edit works, delete works, but when click detail error appears...

**Comment by atmacoder** [comment]
thx...
the error was here, I forgot that I modified

    public static function detailQuery(NovaRequest $request, $query)
    {
        return parent::detailQuery($request, $query);
    }
