### ISSUE TITLE
JSON Code field writes NULL for invalid JSON

### ISSUE THREAD

**Issue by sebsel** [laravel/nova-issues#2272]
- Laravel Version: 6.5.2
- Nova Version: 2.7.1
- PHP Version: 7.4.0
- Database Driver: Postgres 

### Description:
With a Code field, you can use the following:

```php
Code::make('Options')->json(),
```

This works great, until one puts in invalid JSON, like `["one", ...]`. In this case, the field is written as `null` (or results in a `SQLSTATE[23502]: Not null violation`, depending on your constraints in the database).

The following solves the issue:

```php
Code::make('Options')->json()->rules('json'),
```

Does it make sense for the `->json()` option to also add the rule that it should be valid JSON? In my mind, it does, as writing `null` for invalid JSON is odd behavior. (The better thing to do would be to not loose the data and write the invalid JSON in the database, which can lead to other database-level rejections, if the database understands the JSON type.)

If not, maybe update the example in the docs, so people are at least pointed in the right direction?

**Comment by jbrooksuk** [comment]
Thanks for the suggestion. 

We’re not going to implement this as Nova doesn’t typically get involved in validation such as this. The reason being that the behaviour is easier decided by the user land code.

**Comment by sebsel** [comment]
Again, maybe update the example in the docs then, because as-is, it's quite unusable.

**Comment by thomasaull** [comment]
I stumbled upon this multiple times and am really glad there is a solution outlined in this issue. Please make it part of the official documentation.

**Comment by davidhemphill** [comment]
I've added it to the documentation. Thanks for bringing it to our attention!

**Comment by pleone** [comment]
I'm glad i foud this!
Actually the docs just says:

>  "Note: Nova does not apply the json validation for Code fields automatically. It's up to the user to specify this rule."

That means " append **->rules('json')** to your field ". 
Hopefully this will help others as doc is not so clear imho.
