### ISSUE TITLE
Currency field

### ISSUE THREAD

**Issue by antlusher** [laravel/nova-issues#2275]
- Laravel Version: 6.x
- Nova Version: v2.9.2
- PHP Version: 7.2
- Database Driver & Version: 
- Operating System and Version: MacOS (valet)
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:

Use of PHPs money_format() in Currency::field is deprecated 

### Steps To Reproduce:
In my Nova\Investment class
use Laravel\Nova\Fields\Currency;
........
Currency::make('Value')->format('%.2n'),

<img width="432" alt="Screenshot 2020-01-11 at 18 57 17" src="https://user-images.githubusercontent.com/2495026/72209255-49766c00-34a4-11ea-8777-1e1fe093abfa.png">

Cheers all!

**Comment by jbrooksuk** [comment]
Duplicate.

**Comment by antlusher** [comment]
@jbrooksuk could you link to the dupe please.

Cheers!
