### ISSUE TITLE
Laravel Nova 404's are broken

### ISSUE THREAD

**Issue by LorenzoSapora** [laravel/nova-issues#2276]
This is specifically for the nova/nova docs, hosted at [https://nova.laravel.com](https://nova.laravel.com/).

If I go to any non-existing page (https://nova.laravel.com/do) for example, the 404 page is broken.

![image](https://user-images.githubusercontent.com/25519274/72209755-d112a980-34a9-11ea-97bf-05f58a79c817.png)

**Comment by davidhemphill** [comment]
Made 404's more clear. Thanks!
