### ISSUE TITLE
Asterisk not Shown to indicate a field is required

### ISSUE THREAD

**Issue by trollfalgar** [laravel/nova-issues#2277]
- Laravel Version: 6.10.1
- Nova Version: 2.9.3
- PHP Version: 7.3.13
- Database Driver & Version:
- Operating System and Version: Windows 10 1909
- Browser type and version: Firefox 73

### Description:
 Asterisk not Shown to indicate a field is required.
 This problem start yesterday.

### Steps To Reproduce:

 

    public function fields(Request $request)
    {
        return [
                    ID::make()->sortable(),
                    Text::make('Nome', 'name')->sortable()->rules('required'),
                    Text::make('Matrícula', 're')->sortable()->rules('required'),
        ];
    }

**Comment by milewski** [comment]
I have copied and pasted your example and it worked de boas

![image](https://user-images.githubusercontent.com/2874967/72214009-4e82fc00-3534-11ea-82c2-e2e2a3165bb8.png)

Im using the same nova version as you, maybe try to republish your nova with `php artisan nova:publish` do some cache cleaning etc..

**Comment by trollfalgar** [comment]
Didn't work.
Maybe some package is interfering. I'll try remove them.

**Comment by jbrooksuk** [comment]
I am unable to replicate this issue also. I would guess that it’s a package. Let us know otherwise.

**Comment by issour** [comment]
Same problem here!
Do you find what package was responsible?
Thx !!

**Comment by jesperbjoernandersen** [comment]
I know this is old, but in case someone stumble upon this post, NovaGrid is at least one package that interfere with this.

**Comment by michaelromero-grapelab** [comment]
> I know this is old, but in case someone stumble upon this post, NovaGrid is at least one package that interfere with this.

I had this issue with Nova. some of its features interfere with Nova Grid.
