### ISSUE TITLE
Send file through action is not working

### ISSUE THREAD

**Issue by trollfalgar** [laravel/nova-issues#2279]
- Laravel Version: 6.10.1
- Nova Version: .2.9.3
- PHP Version: 7.3.13

### Description:
I`m tring to attach a file through a action. The action update the database, but the file is not send to the correct path.

I saw on documentation this:

    public function handle(ActionFields $fields, Collection $models)
    {
        foreach ($models as $model) {
            (new DriverHasVehicle($model))->send($fields->documents_recall);
        }
    }

I tryed without success.

### Steps To Reproduce:

    <?php

    namespace App\Nova\Actions;

    use App\DriverHasVehicle;
    use Illuminate\Bus\Queueable;
    use Illuminate\Contracts\Queue\ShouldQueue;
    use Illuminate\Queue\InteractsWithQueue;
    use Illuminate\Queue\SerializesModels;
    use Illuminate\Support\Collection;
    use Laravel\Nova\Actions\Action;
    use Laravel\Nova\Actions\DestructiveAction;
    use Laravel\Nova\Fields\ActionFields;
    use Laravel\Nova\Fields\DateTime;
    use Laravel\Nova\Fields\File;

    class ReturnDriverHasVehicle extends DestructiveAction
    {
    use InteractsWithQueue, Queueable, SerializesModels;

    /**
     * @return string
     */
    public function name()
    {
        return 'Devolver Veículo';
    }

    /**
     * Perform the action on the given models.
     * @param ActionFields $fields
     * @param Collection   $models
     * @return mixed
     */
    public function handle(ActionFields $fields, Collection $models)
    {
        foreach ($models as $model) {
            $model->documents_recall = $fields->documents_recall;
            $model->save();
            $model->delete();
        }

        return Action::message('Associação desfeita!');
    }

    /**
     * Get the fields available on the action.
     * @return array
     */
    public function fields()
    {
        return [
            File::make('Documentos', 'documents_recall')
                ->path('/veiculos/associados/retorno')
                ->acceptedTypes('.pdf')
                ->rules('required')
                ->required(),

            DateTime::make('Data da Devolução', 'recall_date')
                ->format('DD/MM/YYYY - HH:mm')
                ->withMeta(['value' => now()])
                ->rules('required')
                ->required(),
        ];
    }
    }

Somebody knows why is not moving the file?

**Comment by jbrooksuk** [comment]
https://nova.laravel.com/docs/2.0/actions/defining-actions.html#queued-actions

![image](https://user-images.githubusercontent.com/246103/72297542-0c50dc00-3654-11ea-83fc-a50b07cd97bf.png)
