### ISSUE TITLE
Global format for Date and DateTime fields

### ISSUE THREAD

**Issue by ziming** [laravel/nova-issues#2280]
Can't find it anywhere in the docs, but it will be great if I can specify what string format all Date and DateTime field uses in all nova admin views (or just index view to save some screen space) in 1 place than to apply to each and every Date or DateTime field

If anyone knows how, would like to know, thanks!

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by 949mac** [comment]
+1 on this
