### ISSUE TITLE
Create new fields based on form type you attached.

### ISSUE THREAD

**Issue by latifiyll** [laravel/nova-issues#2281]
Can you create new fields based of type you attach. For ex: when I create a Post,  I want to attach to that post a field type Select. Then that attached form type, to appear as new Field on my resource.
Posts differ from one to another. A post can have 2 text fields, but another one can have 3 or 4 text fields, 1 select etc. Hope I was clear.

**Comment by zareismail** [comment]
Hi. i hope [this ](https://github.com/laravel/nova-issues/issues/2281#issue-549444845) help you

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by latifiyll** [comment]
> Hi. i hope [this ](https://github.com/epartment/nova-dependency-container) help you

@zareismail Im already using it , but can't find a way to use it dynamically
