### ISSUE TITLE
Autofocus issue when editing resource with Trix field

### ISSUE THREAD

**Issue by orkhanahmadov** [laravel/nova-issues#2282]
- Laravel Version: 6.11.0
- Nova Version: 2.9.3
- PHP Version: 7.4.1
- Database Driver & Version: MySQL 8.0
- Browser type and version: Firefox 72

### Description:

When editing resource with Trix field in it, every 1 or 2 seconds input focus automatically switches to Trix field.
It does not happen when creating a new resource, only when editing.

### Steps To Reproduce:

https://imgur.com/xEZWajw

**Comment by jbrooksuk** [comment]
I'm not able to replicate this in Nova v2.10.1 and Firefox 72.0.2.

**Comment by maxgpro** [comment]
> * Laravel Version: 6.11.0
> * Nova Version: 2.9.3
> * PHP Version: 7.4.1
> * Database Driver & Version: MySQL 8.0
> * Browser type and version: Firefox 72
> 
> ### Description:
> When editing resource with Trix field in it, every 1 or 2 seconds input focus automatically switches to Trix field. It does not happen when creating a new resource, only when editing.
> 
> ### Steps To Reproduce:
> https://imgur.com/xEZWajw

were you able to find a solution?

**Comment by Kenan-Kamel** [comment]
I'm facing a similar issue in Google Chrome, I'm using it with Node.js, and ejs. 
Did you find a solution?
