### ISSUE TITLE
The search does not work when the field has numbers only

### ISSUE THREAD

**Issue by s-fog** [laravel/nova-issues#2283]
- Laravel Version: 6.11.0
- Nova Version: 2.9.3
- PHP Version: 7.2.0
- Database Driver & Version:
- Operating System and Version: windows 10
- Browser type and version: google chrome last version

### Description:
Just i cant use just numbers in search. I search that this issue #23 fix this, but it is not working now. Maybe new features broke it.

**Comment by s-fog** [comment]
Can help someone?

**Comment by davidhemphill** [comment]
Without an example of your code that is working incorrectly, there's no way to determine how to produce the bug, if it exists.
