### ISSUE TITLE
Nova Error 403

### ISSUE THREAD

**Issue by zhiyicai** [laravel/nova-issues#2286]
- Laravel Version:6.8.0
- Nova Version: 2.93
- PHP Version: 7.2.20
- Nginx
- Database Driver & Version: mysql 5.7.26

### Description:
http://www.myweb.com/ 
Homepage can be accessed normally

http://www.myweb.com/nova
Can't log in to nova，
403 Forbidden

my nginx conf: 

`
server {
    listen 80;
    server_name http://www.myweb.com/ ;
    root /htdocs/victor;
    index index.html index.htm index.php;
    
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";
    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
    location /nova {
        try_files $uri $uri/ /index.php?$query_string;
    }
    location ~ \.php$ {
        try_files        $uri =404;
        fastcgi_pass     unix:/Applications/MAMP/Library/logs/fastcgi/nginxFastCGI_php7.2.20.sock;
        fastcgi_param    SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include          /Applications/MAMP/conf/nginx/fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
`

**Comment by PatricNox** [comment]
Maybe related to https://github.com/laravel/nova-issues/issues/1633#issuecomment-498134891

**Comment by 949mac** [comment]
Is your .env file set to production?

**Comment by jbrooksuk** [comment]
Doesn't look like a Nova issue.
