### ISSUE TITLE
Resource ordering in side menu

### ISSUE THREAD

**Issue by vpratfr** [laravel/nova-issues#2287]
All latest versions installed as of today.

### Description:

Resources are listed in the side menu by class name alphabetical order. However, when using a different language, the order is not logical anymore.

I have 4 resources: Coast (Côte), Region (Région), District (Département), Fishing Hub (Centre de pêche)

And here is the order presented in French language

![image](https://user-images.githubusercontent.com/2526465/72525067-98851e00-3863-11ea-828f-6e62b21a296a.png)

### Expected:

The order should be at least by alphabetical order of the translated resource name

### Huge bonus point:

In the above case, we are dealing with resources which have a hierarchy.

Coast contains Regions contains Districts contains Fishing Hubs

It would be very user-friendly to have them listed in order of importance instead of just alphabetical order. 

That could be done by providing a field in the resource class such as:

`protected $priority = 2`

We could then sort by priority + alphabetical order (in case of equal priorities).

**Comment by maherelgamil** [comment]
+1

**Comment by milewski** [comment]
Hi this package solves this issue: https://github.com/dcasia/collapsible-resource-manager

**Comment by vpratfr** [comment]
Good but in my opinion there is a bug (ordering by class name instead of real name) that should be solved at the root of the problem.

**Comment by m-lotze** [comment]
see: #2078 

raised this issue in october. sadly still no effort to address this.

**Comment by mattiaefesto** [comment]
@m-lotze great solution! Can you do a pull request so Nova can use this feature?
It's a must-have feature imho!
@davidhemphill do you think will be implemented something like this on the next releases?

**Comment by davidhemphill** [comment]
Check out the merged PR listed above. Users can specify their own strategy for sorting resources inside groups.

**Comment by 949mac** [comment]
@vpratfr, @m-lotze, @mattiaefesto,

You can see a sample implementation of the PR davidhemphill references here:

https://gist.github.com/jbrooksuk/c7c1ab6ea094a29d7dbb1fbdb17d05e1

**Comment by skoyah** [comment]
One thing that Nova currently does not allow is the option to group tools. :( Would be nice to heve this feature implemented

**Comment by vesper8** [comment]
I believe this `sortResourcesBy` is still undocumented

**Comment by zackAJ** [comment]
if you want to order by position in the Nova resources array use

```
        Nova::sortResourcesBy(function ($resource,$position) {
            return $position;
        });

```
