### ISSUE TITLE
Better support for UUID's 

### ISSUE THREAD

**Issue by kevinpijning** [laravel/nova-issues#229]
I'm using UUID's in all of my models, and i got it to work after publishing and modifying the Nova migration.
But the search functionality completely broke.

The when i try to search for something the following error comes up:
`SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: uuid ~~ unknown\nLINE 1: select * from \"clubs\" where (\"clubs\".\"id\" like $1) and \"club...\n                                                  ^\nHINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts. (SQL: select * from \"clubs\" where (\"clubs\".\"id\" like %foo%) and \"clubs\".\"deleted_at\" is null order by \"clubs\".\"id\" desc limit 5)`

I use a PostgresSQL database and my id columns are of type `uuid`
My version of Nova is **1.0.6**

Thanks! 🌻

**Comment by tillkruss** [comment]
Either switch to Algolia, or remove `id` from the searchable columns.

**Comment by LonnyX** [comment]
This issue is also on action_events table, if you use UUID for your User table, there will be an error when you try to add/update something

**Comment by tillkruss** [comment]
You need to publish your own migration `php artisan vendor:publish` and then use `Nova::ignoreMigrations();`.

**Comment by stevelacey** [comment]
I wrote this migration to allow uuids in the `action_events` tables, fixes saving any resource that acts on model with a uuid primary key

```php
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class ChangeActionEventsIdsToChars extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('action_events', function($table) {
            $table->string('actionable_id', 36)->change();
            $table->string('model_id', 36)->change();
            $table->string('target_id', 36)->change();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('action_events', function($table) {
            $table->integer('actionable_id')->unsigned()->change();
            $table->integer('model_id')->unsigned()->change();
            $table->integer('target_id')->unsigned()->change();
        });
    }
}
```

**Comment by geodeveloper** [comment]
Changing the fields to string breaks actions (which tries to log everything into `action_events`. It generates an error `Invalid datetime format: 1292 Truncated incorrect DOUBLE value`. because it's doing a `delete` query which MySQL tries to compare an `integer` with a `string`.

This is an example of a query which you can test this out:
`UPDATE action_events SET `status` = 'finished' WHERE `status` = 'finished' AND `actionable_id` = 1;`

**Comment by LonnyX** [comment]
@geodeveloper You can fix this by casting your id to string or by disabling the mysql strict mode

**Comment by geodeveloper** [comment]
@LonnyX thanks for your input. I actually did that (and it works fine), but still not an ideal solution.

**Comment by asheaheartcup** [comment]
@LonnyX bump

**Comment by johan-steffens** [comment]
@zek @LonnyX I ended up changing user_id to a string as well in the migration that @stevelacey posted above

```php
class ChangeActionEventIdsToUuids extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('action_events', function (Blueprint $table) {
            $table->string('actionable_id', 36)->change();
            $table->string('model_id', 36)->change();
            $table->string('target_id', 36)->change();
            $table->string('user_id', 36)->change();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('action_events', function (Blueprint $table) {
            $table->integer('actionable_id')->unsigned()->change();
            $table->integer('model_id')->unsigned()->change();
            $table->integer('target_id')->unsigned()->change();
            $table->integer('user_id')->unsigned()->change();
        });
    }
}
```

After this it worked fine and I didn't have to cast it anywhere.

Something to note with this approach is that it seems like you're forced to use uuids across the board with this.

**Comment by davidhemphill** [comment]
There will likely be no plans to implement this feature.

**Comment by WouterSioen** [comment]
I created a package which fixes this: https://github.com/madewithlove/laravel-nova-uuid-support

```bash
composer require madewithlove/laravel-nova-uuid-support
php artisan migrate
```

That's it!

**Comment by pjhartin** [comment]
One thing to note is that it seems you cannot rollback this migration, as casting from a string column type to an integer is not supported.

**Comment by WouterSioen** [comment]
I've tested this and as long as all values in the table are integer values, the rollback works. Once there is string data in there, it can indeed not be rolled back without cleaning up the table.

**Comment by georgewritescode** [comment]
Add a migration with this code to fix
```
        Schema::table('action_events', function (Blueprint $table) {
            $table->uuid('user_id', 36)->change();
            $table->uuid('actionable_id', 36)->change();
            $table->uuid('model_id', 36)->change();
            $table->uuid('target_id', 36)->change();
        });
```

**Comment by LiamKarlMitchell** [comment]
String seems to work good thanks @WouterSioen.
If you only ever use UUID in all tables then uuid is fine of course.
But if your DB has or could have a mixture of increments, uuid, varchar etc identifiers then you want string.

**Comment by saleh-mir** [comment]
Is there better support for this? Because in my project I have both Integer IDs and UUIDs for some other models Hence I cannot change my database table.
