### ISSUE TITLE
How to set the details of the record to be displayed in the popup below the row when clicked

### ISSUE THREAD

**Issue by oleksandr-roskovynskyi** [laravel/nova-issues#2290]
It is also necessary to foresee collapsing when clicking again on the same line, now, I am engaged in the development of this functionality. I will be very grateful for your help!
For example:
<img width="1276" alt="72664963-65ca5980-3a0c-11ea-8971-665e3cdf8341" src="https://user-images.githubusercontent.com/57599426/72678013-b7c1bc80-3aaa-11ea-9289-eab35eb8cd17.png">

This will improve the adaptability of the table to view the details of the record without losing sight of the current row.

There was an idea in a component to implement a hidden line with all details (div class = "hidden"> [Detail.vue] </div) at once, and at click to show/hide, I will try to implement...

Please help me to solve this problem!

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
