### ISSUE TITLE
Defining Actions Without Dedicated Class

### ISSUE THREAD

**Issue by MannikJ** [laravel/nova-issues#2291]
I would often like to be able to create actions on the fly by passing a callback etc. without creating a dedicated action class.
As far as I see this not possible at the moment or am I missing something?

**Comment by jbrooksuk** [comment]
You can absolutely do this! You can use an anonymous class to create an action without actually creating a new file. https://github.com/laravel/nova/blob/2.0/tests/Feature/ActionTest.php

**Comment by MannikJ** [comment]
Ok, good to hear! But unfortunately the link is broken...

**Comment by jbrooksuk** [comment]
You need to link your GitHub account to your Nova account. https://nova.laravel.com/settings#github but if you can't see that, then you can do:

```php
public function actions()
{
    $myAction = new class extends Action {
        // Action code...
    };

    return [
        $myAction,
    ];
}
```
