### ISSUE TITLE
Call To Undefined Method allowZeroResult

### ISSUE THREAD

**Issue by Aontaigh** [laravel/nova-issues#2292]
- Laravel Version: 5.8.36
- Nova Version: 2.3.1
- PHP Version: 7.2.16
- Database Driver & Version:
- Operating System and Version: Mac OS X 10.13.6
- Browser type and version: Chrome Version 79.0.3945.117

### Description:

These is a section in the documentation regarding [Zero Results Values](https://nova.laravel.com/docs/2.0/metrics/defining-metrics.html#zero-result-values) on Value Metrics.

### Steps To Reproduce:

```

<?php

namespace App\Nova\Metrics\TemplateDashboard;

use App\Template;

use Carbon\Carbon;

use Illuminate\Http\Request;
use Laravel\Nova\Metrics\Value;

class TemplatesImportedMonth extends Value
{
    /**
     * Get the displayable name of the metric.
     *
     * @return string
     */
    public function name()
    {
        return 'Templates Imported This Month';
    }

    /**
     * Calculate the value of the metric.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return mixed
     */
    public function calculate(Request $request)
    {
        $now = Carbon::now();

        return $this->result(Template::whereYear('created_at', '=', $now->year)->whereMonth('created_at', '=', $now->month)->count())->allowZeroResult();
    }

    /**
     * Get the ranges available for the metric.
     *
     * @return array
     */
    public function ranges()
    {

    }

    /**
     * Determine for how many minutes the metric should be cached.
     *
     * @return  \DateTimeInterface|\DateInterval|float|int
     */
    public function cacheFor()
    {
        // return now()->addMinutes(5);
    }

    /**
     * Get the URI key for the metric.
     *
     * @return string
     */
    public function uriKey()
    {
        return 'templates-imported-month';
    }
}


```
I get the following error:

> [15:50:51] LOG.error: Call to undefined method Laravel\Nova\Metrics\ValueResult::allowZeroResult() {"userId":1,"exception":{}}

Even using the exact code in the docs gives me the same error:

`return $this->result(0)->allowZeroResult();`

**Comment by jbrooksuk** [comment]
You're using an out of date version of Nova, which doesn't provide the `allowZeroResult` method.

**Comment by ziming** [comment]
I'm on the latest version, there is no allowZeroResult() too but it is mentioned in the docs
