### ISSUE TITLE
Class name must be a valid object or a string

### ISSUE THREAD

**Issue by Aontaigh** [laravel/nova-issues#2293]
- Laravel Version: 5.8.36
- Nova Version: 2.9.3
- PHP Version: 7.2.16
- Database Driver & Version:
- Operating System and Version: Mac OS X 10.13.6
- Browser type and version: Chrome Version 79.0.3945.117

### Description:

After upgrading from 2.3.1 to 2.9.3 the follow error appeared upon opening the application:

> Class name must be a valid object or a string (View: /Users/dev2/Development/onbrand-brandhub/nova/resources/views/layout.blade.php) (View: /Users/dev2/Development/onbrand-brandhub/nova/resources/views/layout.blade.php)

### Steps To Reproduce:

I downloaded the latest ZIP (2.9.3), extracted it, and replaced the contents on my nova folder with the extracted contents. I ran:

- composer update
- php artisan nova:publish
- php artisan view:clear
- php artisan nova:publish --force

**Comment by jbrooksuk** [comment]
Delete the files in `resources/views/vendor/nova` and re-publish.
