### ISSUE TITLE
Define BelongsTo field in BelongsToMany field (pivot) not working

### ISSUE THREAD

**Issue by isometriq** [laravel/nova-issues#2295]
- Laravel Version: 6.11.0
- Nova Version: 2.9.3
- PHP Version: 7.4.1
- Database Driver & Version: mysql  Ver 15.1 Distrib 10.4.11-MariaDB
- Operating System and Version: Windows 10
- Browser type and version: Chrome 79.0.3945.117

### Description:
I have `Sections` and `Journals` and they are related to each with `BelongsToMany`. Also their relation is a unique association to `SectionMemberType` and `JournalMemberType`, in the pivot. A pivot class `SectionJournal` defines these associations and is applied with `->using(SectionJournal::class)` on the corresponding models.

I'm trying to specify if the Section my nova resource these member type associations in the pivot of a `BelongsToMany` field. The pivot entries show up in the view mode, but...

- The list does not include pivot fields;
- When viewing (eye icon) the relation, it show me the Journal, but no pivot fields;
- When creating an assocation, I get an error: *Call to undefined method Illuminate\Database\Eloquent\Relations\Pivot::section()*
- When editing an assocation (created from a seed), I get an error: *Call to undefined method App\Models\Section::sectionMemberType*

I could create a `HasMany` field and wrap things up differently and does work to some extent, but I find this limitation lacking and it renders the `BelongsToMany` useless in many situations.

I checked the source code and could not find something useful. I would expect Nova to take into account the `->using()` definitions...

### Steps To Reproduce:
Stripped down many details to get only the essential.
```
class Section extends Model
{
    public function journals()
    {
        return $this->belongsToMany(Journal::class, 'sections_journals', 'section_id', 'journal_id')->using(SectionJournal::class);
    }
}

class Journal extends Model
{
    public function sections()
    {
        return $this->belongsToMany(Section::class, 'sections_journals', 'section_id', 'journal_id')->using(SectionJournal::class);
    }
}

class SectionMemberType extends Model
{
    // ...
}

class JournalMemberType extends Model
{
    // ...
}

class SectionJournal extends Model
{
    use AsPivot;

    protected $table = 'sections_journals';

    public function section()
    {
        return $this->belongsTo(Section::class);
    }

    public function sectionMemberType()
    {
        return $this->belongsTo(SectionMemberType::class);
    }

    public function journal()
    {
        return $this->belongsTo(Journal::class);
    }

    public function journalMemberType()
    {
        return $this->belongsTo(JournalMemberType::class);
    }
}

class Section extends Resource
{
    public static $model = \App\Models\Section::class;
    public static $title = 'name';
    public static $search = [
        'id',
        'code',
        'name',
    ];
	
    public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
            Text::make('code')->sortable(),
            Text::make('name')->sortable(),
            TextArea::make('Description')->hideFromIndex(),
            Avatar::make('Logo Small')->hideFromIndex(),
            Avatar::make('Logo Large')->hideFromIndex(),
            BelongsToMany::make('Journals')->hideFromIndex()
                ->fields(function(){
                    return [
                        BelongsTo::make('Section Member Type', 'sectionMemberType')->sortable(),
                        BelongsTo::make('Journal Member Type', 'journalMemberType')->sortable(),
                    ];
                }),
        ];
    }
}
```

**Comment by isometriq** [comment]
Found another workaround ..did not test yet
https://stackoverflow.com/questions/53723688/laravel-nova-belongstomany-belongsto-in-pivot

**Comment by aniket-magadum** [comment]
@isometriq  Did you find any other workaround ?

**Comment by isometriq** [comment]
Alas, nope

**Comment by aniket-magadum** [comment]
@isometriq #1585 is a similar issue

**Comment by bilfeldt** [comment]
@isometriq It looks to me like you forgot to set the `withPivot()` part on your models like so:

```php
class Section extends Model
{
    public function journals()
    {
        return $this->belongsToMany(Journal::class, 'sections_journals', 'section_id', 'journal_id')
                ->using(SectionJournal::class)
                ->withPivot('sectionMemberType', 'journalMemberType'); // This was missing
    }
}

class Journal extends Model
{
    public function sections()
    {
        return $this->belongsToMany(Section::class, 'sections_journals', 'section_id', 'journal_id')
                ->using(SectionJournal::class)
                ->withPivot('sectionMemberType', 'journalMemberType'); // This was missing
    }
}
```
See the [documentation](https://laravel.com/docs/6.x/eloquent-relationships#many-to-many) about this.

**Comment by ashestree87** [comment]
I am still having this issue, on the very latest version of laravel and nova and getting SQL error everytime. 

I have specified the column name everywhere possible and nothing I do changes it from inserting the function into the SQL.

![image](https://user-images.githubusercontent.com/65953295/83194109-2d205680-a149-11ea-8de8-18431d231412.png)

**Comment by trippo** [comment]
@ashestree87  @bilfeldt In withPivot method you can only set the table columns, not the relations.
Please see https://stackoverflow.com/questions/53723688/laravel-nova-belongstomany-belongsto-in-pivot for temporary fix.
This issue must be re-open.

**Comment by trippo** [comment]
Example:
`
BelongsToMany::make('Products')->fields(function () {
  $packages = \App\Models\Package->pluck('name', 'id');
   return [
            Select::make('Product package','package_id')->options($packages)->searchable()
            ->displayUsing(function ($package_id) use ($packages) {
                return $packages[$package_id];
            }),...
`

**Comment by bambamboole** [comment]
I have the same issue. can this be reopened?

**Comment by simpsons310** [comment]
@jbrooksuk 
Looks like this problem is still not fully resolved except using a temporary workaround using `Select`. Can you reopen this issue?
