### ISSUE TITLE
web.config for Nova on IIS Azure App Service

### ISSUE THREAD

**Issue by Manaf-Ibrahim** [laravel/nova-issues#2297]
- Laravel Version: 6.11.0
- Nova Version: 2.9.4
- PHP Version: 7.3.9
- Database Driver & Version: MySQL - 8.0

### Description:

Hello,

Not sure if anybody else has run into this issue before and could provide guidance on how they overcame they issue - I have a fresh application with Nova which I have been able to deploy to Azure via a Web App Service however whenever I attempt to access the Nova panel I am receiving a 403 for the /vendor/nova/app.css file and hence the no styling is being applied for Nova.

Any help would be greatly appreciated.

### Steps To Reproduce:

Navigate to /nova and view console to see 403 error - page displays with no styles.

**Comment by jbrooksuk** [comment]
Are the file permissions accepted by Azure?

**Comment by Manaf-Ibrahim** [comment]
Thanks James,

I am not sure where this would be configured?

Any further guidance would be much appreciated.

**Comment by Manaf-Ibrahim** [comment]
Issue is now resolved - for future reference if you deploy via the Azure App Service + MySQL bundle and use the Composer extension it sets the following rewrite within the applicationHost.xdt for the extension:

`<rewrite xdt:Transform="InsertIfMissing">
  <rules xdt:Transform="InsertIfMissing">
    <rule name="RequestBlockingRule1" xdt:Locator="Match(name)" xdt:Transform="InsertIfMissing" stopProcessing="true">
                <match url=".*" />
                <conditions>
                    <add input="{URL}" pattern="vendor/(.*)$" />
                </conditions>
                <action type="CustomResponse" statusCode="403" statusReason="Forbidden: Access is denied." statusDescription="You do not have permission to     view this directory or page using the credentials that you supplied." />
            </rule>
  </rules>
</rewrite>`

To overcome this you could remove the extension or also add a `<clear />` tag above your rules in the web.config file as such:

`<rules>
        <clear />
        <rule name="Laravel" stopProcessing="true">
        <match url="^" ignoreCase="false" />

        <conditions logicalGrouping="MatchAll">
          <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
          <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
        </conditions>

        <action type="Rewrite" url="index.php" appendQueryString="true" />

        </rule>
 </rules>`
