### ISSUE TITLE
Touch Model after attach belongsToMany object

### ISSUE THREAD

**Issue by h-zone** [laravel/nova-issues#2299]
Hello!

I ask you to implement the field directive, i.e. `-> touch ()`, which must be executed after attaching a belongsToMany object.

Or say me how to realize otside of Nova.

case: compile KPI activity

**Comment by jbrooksuk** [comment]
You could use a Model Observer to do this.

**Comment by benedict-w** [comment]
I have an model for a pivot table which touches it's parent timestamp (as described here: https://laravel.com/docs/6.x/eloquent-relationships#touching-parent-timestamps), however this is not working when the pivot is updated in Nova, is this a bug or deliberate behaviour? Is there a work around?
