### ISSUE TITLE
[Feature Request] Resource Actions Logs outside Nova

### ISSUE THREAD

**Issue by devmsh** [laravel/nova-issues#230]
Nova action logs is very powerful tool for auditing and reviewing changes, but it's only limited to the actions invoked from the Nova itself.

What about extending the Actions logs and make it logs all jobs related to the model even if it's invoked outside of Nova?

**Comment by taylorotwell** [comment]
This repository is for tracking bugs. Feature requests may be emailed to Nova customer support.
