### ISSUE TITLE
Nova 404 after updating (string) id column.

### ISSUE THREAD

**Issue by larsrbak** [laravel/nova-issues#2300]
- Laravel Version: 6.7.0
- Nova Version: 2.9.0
- PHP Version: 7.4
- Database Driver & Version: mysql:8.0
- Operating System and Version: ubuntu:18.04
- Browser type and version: chrome

### Description:
I receive a 404 error after updating the id of a resource with string id.

I have a table where
```
Schema::create('products', function (Blueprint $table) {
  $table->string('id')->primary();
}
```

I can **always** successfully update a record using the nova, but sometimes the error
"No query results for model [Services\Products\Product]" is produced causing a 404 page despite the update being successful.

### Steps To Reproduce:
1. create a product record
2. tab edit in nova
3. change id
4. submit form
5. repeat 1 - 4 until error

**Comment by jbrooksuk** [comment]
Can you please try on the latest version of Nova.
