### ISSUE TITLE
Resource Not Displayed If Model Property Points To "App\Posting"

### ISSUE THREAD

**Issue by MannikJ** [laravel/nova-issues#2301]
- Laravel Version: 6.12.0
- Nova Version: 2.9.4
- PHP Version: 7.3
- Database Driver & Version: MySQL 5.7
- Operating System and Version: Linux Mint 19.2
- Browser type and version: Chrome 69.0.3497.92 (Official Build) (64-bit)

### Description:
I found a very strange behavior in our app where our "Posting" resource suddenly disappeared in one of the version upgrades (not sure which exactly).
There is no error or anything it is just not displayed in the navigation and not reachable via direct route. If rename the model and change the reference in the resource everything works. It seems to have something to do with the name "Posting" actually. I have tinkered quite a lot now, but I am not sure if it is just a problem on my side. Would still be nice if someone could try to reproduce this issue.

### Steps To Reproduce:
Create an App\Posting eloquent model and a nova resource pointing to it
Look if the resource is displayed/reachable

**Comment by jbrooksuk** [comment]
I can't recreate this on v2.10.1.

![image](https://user-images.githubusercontent.com/246103/74738922-bc1afa00-524f-11ea-95c5-e388d6e9bb58.png)
