### ISSUE TITLE
Potentially unsafe disclosure of information about existing resources.

### ISSUE THREAD

**Issue by medvinator** [laravel/nova-issues#2303]
- Laravel Version: 6.12.0
- Nova Version: 2.9.4
- PHP Version: 7.4.0

### Description:
Global object window.Nova has information about existing resources regardless of authorization policies.

### Steps To Reproduce:
```js
console.table(Nova.config.resources);
```
----
In my opinion this is not safe.
I don’t want Nova users to know about all possible resources, including those to which they do not have access.

**Comment by davidhemphill** [comment]
Serious question: what is unsafe about a backend user knowing that a domain concept simply exists, when all access is disabled?
