### ISSUE TITLE
Lens fields always visible

### ISSUE THREAD

**Issue by sanasol** [laravel/nova-issues#2306]
- Laravel Version: 6.0
- Nova Version: 2.9.4
- PHP Version: 7.2.24

### Description:
Lense doesn't respect visibility on fields.
Lense fields always visible regardless `showOnIndex` option.

### Steps To Reproduce:

1. Create Resource with field X that uses `onlyOnDetail` or `hideFromIndex` or `onlyOnForms`
2. Create Lense for that resource.
3. Field X visible on Lense's index and hidden on Resource's index.

**Comment by sanasol** [comment]
Fixed temporary by overriding `resolveFields` in my Lenses. Added fields rejection through `isShownOnIndex`

```
    /**
     * Resolve the given fields to their values.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @return \Laravel\Nova\Fields\FieldCollection
     */
    public function resolveFields(NovaRequest $request)
    {
        return $this->availableFields($request)
            ->each->resolve($this->resource)
            ->filter->authorize($request)
            ->each->resolveForDisplay($this->resource)
+            ->reject(function ($field) use ($request) {
+                return $field instanceof ListableField || ! $field->isShownOnIndex($request, $this->resource);
+            })
            ->values();
    }
```

**Comment by davidhemphill** [comment]
This doesn't make sense as a feature since Lenses use their own separate field definitions from Resource classes. If you don't want the field to show on Lenses, then just remove it.

**Comment by sanasol** [comment]
@davidhemphill in my case I also use excel export from Lense with different field list, so to make it work I need add some additional fields that actually should be hidden from Lense itself but exported to file. So there is no way to handle field visibility... Except "create-one-more-lense" with 90% copy pasted code.
