### ISSUE TITLE
Timestamps false ignored when deleting image from input

### ISSUE THREAD

**Issue by aniplaylist** [laravel/nova-issues#2307]
- Laravel Version: 5.8.36
- Nova Version: 2.9.3
- PHP Version: 7.4.0
- Database Driver & Version: MySQL 5.7
- Operating System and Version: Ubuntu 18.04.3 LTS
- Browser type and version: Chrome 79.0.3945.130

### Description:

When deleting an image the `updated_at` field is updated even when timestamps is set to false. 

### Steps To Reproduce:

1. Add the following fields to one of your resources  
```
Text::make('Text'),
Image::make('Image'),
// Checkbox to avoid updating updated_at column, set to false by default
Boolean::make('Mark as updated', 'timestamps')->withMeta(['value' => false]),
```
2. Create an entry with a text and image, save it
3. Edit the entry, update text input only, `updated_at` field is not updated, which is the expected behaviour
4. Edit the entry once again, delete image and save, `updated_at` field is updated but shouldn't.

**Comment by crynobone** [comment]
I don't think that this approach is officially supported by Laravel Nova and currently work at random.
