### ISSUE TITLE
Refresh Card on Ressource index

### ISSUE THREAD

**Issue by thomasdominic** [laravel/nova-issues#2309]
Laravel Version: 6.10.1
    Nova Version: 2.9.3
    PHP Version: 7.3.7

I have a card with the total numbers of users.
If I delete a record, the card isn't updated and I don't have the right number of users. I nedd to refresh index page.

![Capture d’écran de 2020-01-28 12-52-52](https://user-images.githubusercontent.com/17202290/73261864-3914ff80-41cd-11ea-886b-95ab5d87b326.png)

**Comment by skoyah** [comment]
Would be nice to programmatically force the index or detail pages to refresh cards. maybe by emitting an event. In my example I have some functionality the navigates from one detail view to another detail view but the cards are still referring to the previous resource.

**Comment by thomasdominic** [comment]
I think it would be easier than custom card. 
And then, in custom card, we should do the same with the good process and the right method.
