### ISSUE TITLE
Mixed content prevents to login on SSL sites

### ISSUE THREAD

**Issue by Tmeister** [laravel/nova-issues#231]
**Bug description**

I'm testing Nova on a staging site that force SSL connections, in the login page I'm getting a `Mixed Content warning`.

The warning is because the login form is pointing to an insecure URL `http://site-url.com/admin/login` instead of `https://site-url.com/admin/login` and when the form is submitted and the redirection is made to `https://` the login flow breaks sending the user to the login form page again, making impossible to log in.

**Expected behavior**

The login action URL should respect the site main protocol, in this case, `https://`

**Code**

```php
<form
    class="bg-white shadow rounded-lg p-8 max-w-login mx-auto"
    method="POST"
    action="{{ route('nova.login') }}"
>
    {{ csrf_field() }}
...
```

![Console Output](https://d3vv6lp55qjaqc.cloudfront.net/items/1h2V2O1o0r2I2P3n1L1P/%5Ba56111c011627374d453632529d43a7d%5D_Image%25202018-08-26%2520at%25206.24.19%2520PM.png?X-CloudApp-Visitor-Id=1908589&v=8f77e1a7)

**Comment by liamcottle** [comment]
The `route` method will automatically prefix with `https` instead of `http` if you are connecting over `https`.

In your case, you might be serving behind a load balancer that is requesting nova over `http` but actually serving the page over `https`.

So Laravel will output `http` for the route URL.

If this is the case, you'll need to configure [Trusted Proxies](https://laravel.com/docs/5.6/requests#configuring-trusted-proxies) so Laravel knows to serve `https` even though the page was requested over `http`.

This is what I have to do when serving via a Dokku server.

**Comment by Tmeister** [comment]
Is not behind of a load balancer, actually, I'm using a DigitalOcean with Forge.

The only extra component is CloudFlare that provide the SSL and redirections will take a look at that.

**Comment by davidhemphill** [comment]
> `route()` will use the scheme that your framework detects. You need to set your trusted proxies.

👆

**Comment by munir131** [comment]
$proxies = '*' is no more working

**Comment by TolrenFrank** [comment]
I faced the issue also, and i have tried above solutions but everything no worked.

**Comment by patrickreck** [comment]
Did you find a solution for this?

**Comment by KostiaBenner** [comment]
To fix this behavior, you need to insert such a construction into the balancer config

`    location / {
        proxy_pass http://localhost:30021;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header HTTPS YES;
        fastcgi_param HTTPS on;
        fastcgi_param HTTP_HTTPS on;
        fastcgi_param REQUEST_SCHEME https;
        fastcgi_param SERVER_PORT 443;
    }
`

**Comment by Mugane** [comment]
Why does it use absolute URLs at all? :// would fix this. Please amend the app behavior accordingly.
