### ISSUE TITLE
Searchable not working in BelongsToMany when Attaching

### ISSUE THREAD

**Issue by manojo123** [laravel/nova-issues#2311]
- Laravel Version: 5.8
- Nova Version: 2.9.4
- PHP Version: PHP 7.2.24-0ubuntu0.18.04.2
- Database Driver & Version: Ver 14.14 Distrib 5.7.28
- Operating System and Version: Ubuntu 18.04.2 LTS
- Browser type and version: Google Chrome Version 79.0.3945.130 (Official Build) (64-bit)

### Description:
My Many to Many RelationShip between resources (Shop, Products) works perfectly in all tests and pages of my system.

I have a problem when I add ->searchable(); method in Nova Fields
```
BelongsToMany::make('Shops')->searchable()
```
or 

```
BelongsToMany::make('Shops', 'shops', Shop::class)->searchable()
```
where Shop::class is a Shop Nova Resource Class. In Shop Nova Resource File I also added the relationship as well.

When I try to attach a product in my shop I get an empty select box. It works fine if I remove the searchable();

I expect at least an error explaining why there is no products in attach list to know where to look at to try to fix it

### Steps to Reproduce
- Install Laravel UI with vue --auth
- Create Shop Model, Migration, Factory and Nova Resource Model

Model
```
protected $guarded = [];

	public function products(){
		return $this->belongsToMany(Product::class);
	}
```

Migration
```
Schema::create('shops', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('name');
            $table->timestamps();
        });
```

Factory
```
$factory->define(Shop::class, function (Faker $faker) {
    return [
    	'name' => $faker->word()
    ];
});
```

Nova Resource Model
```
public static $title = 'name';

    /**
     * The columns that should be searched.
     *
     * @var array
     */
    public static $search = [
        'id','name'
    ];

    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
            Text::make('Name'),

            BelongsToMany::make('Products')->searchable(),
        ];
    }
```
- Do the exactly Same thing to Product changing the class name of course
- Create pivot table migration 
```
Schema::create('product_shop', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->unsignedBigInteger('product_id');
            $table->unsignedBigInteger('shop_id');
            $table->timestamps();

            $table->foreign('product_id')->references('id')->on('products');
            $table->foreign('shop_id')->references('id')->on('shops');
        });
```
- Try to attach a product into a shop using nova Dashboard
- select input will be empty

**Comment by swapnilsarwe** [comment]
I know as per the documentation, searchable is not available on BelongsToMany relationship. 
Is there an alternative or a workaround where I can attach more than one records.

**Comment by NowakAdmin** [comment]
Starting from v3.8.0 
`The BelongsToMany is now searchable.`

https://nova.laravel.com/releases/3.8.0
