### ISSUE TITLE
where can add a account ?

### ISSUE THREAD

**Issue by lifeblood** [laravel/nova-issues#2312]
![image](https://user-images.githubusercontent.com/3621748/73327201-fd8f3980-428f-11ea-967d-9841fcaf1fbc.png)

where can add a account ?

**Comment by jbrooksuk** [comment]
Nova is sitting in front of your applications authentication system, so you use the same login details as your app does.

**Comment by flakerimi** [comment]
For sake of archive, 
run `php artisan nova:user` to create one.
