### ISSUE TITLE
Making an Avatar prunable breaks image uploads when custom delete() callback is used

### ISSUE THREAD

**Issue by stancl** [laravel/nova-issues#2314]
- Laravel Version: 6.13.1
- Nova Version: 2.9.4
- PHP Version: 7.4
- Database Driver & Version: sqlite
- Operating System and Version: Ubuntu 19
- Browser type and version: Chrome

### Description:

When both `prunable()` and a custom delete callback are used, it's not possible to create or edit Avatars for the resource.

I get this after submitting the form:

![Screenshot from 2020-01-30 21-20-42](https://user-images.githubusercontent.com/33033094/73487027-7d0f2c80-43a6-11ea-978b-9275e32b217f.png)

When I disable `prunable()`, I can upload the image normally, re-enable `prunable()` and have the files be pruned when the resource is deleted.

But uploading the images does not work while `prunable()` is enabled.

### Steps To Reproduce:

Create a resource with a field like this:
```php
Avatar::make(__('Obrázek'), 'image')
    ->prunable()
    ->delete(function (NovaRequest $request, ProductModel $product) {
        if (! $product->image) {
            return;
        }

        Storage::disk('public')->delete($product->image);

        PruneThumbnails::dispatch((string) $product->id);

        return [
            'image' => null,
        ];
    }),
```

If both `prunable()` and the custom `delete()` callbacks are set, it won't be possible to add images.

If only one is set, it will be possible to add images.

**Comment by dkulyk** [comment]
```php
Avatar::make(__('Obrázek'), 'image')
    ->prunable()
    ->delete(function (NovaRequest $request, ProductModel $product, $disk, $path) {
        if (! $path) {
            return;
        }

        Storage::disk($disk)->delete($path);

        PruneThumbnails::dispatch((string) $product->id);

        return [
            'image' => null,
        ];
    }),
```

**Comment by stancl** [comment]
My bad, I must have made a mistake during debugging because I thought the *presence* of the callback is the cause of the issue.

Thank you very much @dkulyk.
