### ISSUE TITLE
Is there a way to set background color per resource row?

### ISSUE THREAD

**Issue by bomshteyn** [laravel/nova-issues#2315]
I am working with a client who is very particular about how his admin panel needs to look and he wants to have the rows on one of the resource index tables have one of three different background colors based on certain conditions.

Is there a way to achieve this? If yes how?

**Comment by flakerimi** [comment]
You should ask this on Stackoverflow

**Comment by skoyah** [comment]
@bomshteyn What I did was to create a custom field to set the background:

<img width="942" alt="Screenshot 2020-02-03 at 13 20 21" src="https://user-images.githubusercontent.com/36083448/73652784-f4cfa680-4687-11ea-8fd3-6562b5c8e7a5.png">

<img width="597" alt="Screenshot 2020-02-03 at 13 21 04" src="https://user-images.githubusercontent.com/36083448/73652826-103ab180-4688-11ea-8cf1-dc238dad4342.png">

**Comment by bomshteyn** [comment]
@skoyah thanks.

Can you share the full code of the field. I don't understand how this is going to affect the row background color

**Comment by jbrooksuk** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](https://larachat.co/).

**Comment by flakerimi** [comment]
@bomshteyn https://laracasts.com/series/laravel-nova-mastery/episodes/14
