### ISSUE TITLE
KeyValue Field - Nested JSON data not rendering correctly

### ISSUE THREAD

**Issue by smartens80** [laravel/nova-issues#2316]
- Laravel Version: 6.13.1
- Nova Version: 2.9.4
- PHP Version: 7.4.0
- Database Driver & Version: mysql 5.7
- Operating System and Version: Ubuntu 18.04.3 LTS
- Browser type and version: Windows Google Chrome 79.0.3945.130 (Official Build) (64-bit)

### Description:

Nested JSON data doesn't render correctly / as expected.

JSON Data:
```
{
	"success": {
		"transactions": {
			"id": 55,
			"test": 1,
		}
	},
	"api_version": "0.70"
}
```

Renders as:

![keyvalue_nested_json_rendering_issue](https://user-images.githubusercontent.com/18694052/73508657-5bef2000-4428-11ea-94f8-f10a8476b7fd.png)

I'm not sure how I would expect it to render, however I would have expected at least the "id" and "test" key / values pairs be shown.

Expected Rendering (??): 

![keyvalue_nested_json_rendering_issue-correct](https://user-images.githubusercontent.com/18694052/73508897-1c750380-4429-11ea-9cc3-4a55645c118b.png)

**Comment by davidhemphill** [comment]
The `KeyValue` field is not intended to support nested data. It's recommended to use a `Code` field instead for multiple levels.
