### ISSUE TITLE
Attach Automatically when i create a resources in BelongsToMany

### ISSUE THREAD

**Issue by ArmChaCib** [laravel/nova-issues#2317]
I have the resource Supplier and BrandMaterial, and i have the pivot table brand_material_suppliers, because the Supplier has many brand materials.

But  i want to create a supplier, and in the supplier detail i want to create a BrandMaterial and  when i create a BrandMaterial i want to make the attach automatically to the table  brand_material_suppliers.

I don´t want to see the atach button, i want to see the create button, and automatically attach the brandMaterial to the Supplier

**Comment by sirikkoster** [comment]
This is exactly what observers are meant for.

https://laravel.com/docs/6.x/eloquent#observers

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).
