### ISSUE TITLE
Console error when clearing BelongsTo field

### ISSUE THREAD

**Issue by royduin** [laravel/nova-issues#2318]
- Nova Version: 2.9.4

### Description:

When I clear the BelongsTo field I'm getting a console error:
```
TypeError: Cannot read property 'offsetTop' of undefined
```

### Steps To Reproduce:

Create a `BelongsTo` relation which is "nullable" and "searchable".
```
BelongsTo::make('Relation')->nullable()->searchable(),
```
Search for a value, select it, clear it by clicking the cross and then try to search again.

In `SearchInput.vue` and the `updateScrollPosition` method it's checking for 
```
if (this.$refs.selected) {
```
But after clearing it seems like it's an array instead of `null`.

**Comment by jbrooksuk** [comment]
I couldn't replicate this in v2.10.1

**Comment by dgoldstein89** [comment]
Experiencing this in v2.12.0
