### ISSUE TITLE
Changing parameters in config/nova.php seems to have no effect?

### ISSUE THREAD

**Issue by Sovjetskii** [laravel/nova-issues#232]
I have attempted to modify the parameters in config/nova.php, including:

`'name' => 'Nova Site',`

and 

`'path' => '/nova',`

However, neither change appears to propagate. I'm sure I'm missing something simple, but couldn't find anything related to this in the documentation either.

**Comment by kevinpijning** [comment]
Have u tried php artisan config:clear?

**Comment by LonnyX** [comment]
You probably edited the wrong file. You don't have to edit your ./nova folder
you should edit this: `/<laravel-proect>/config/nova.php`
and **not** this: `/<laravel-proect>/nova/config/nova.php`

**Comment by Sovjetskii** [comment]
Thanks @LonnyX - that was my problem. Appreciate the help!
