### ISSUE TITLE
Is there any way to define multiple custom form fields in one package? Thanks

### ISSUE THREAD

**Issue by hasnatbabur** [laravel/nova-issues#2320]
I know it's a bug report area but not sure where to share my problem. I am in need to have many custom fields. I don't want to overwhelm my project with thousands of node_modules packages for each custom field. If yes then can anyone help me sending some info how to create multiple custom fields, tools etc. in just one one package.

Thanks.

**Comment by Jubeki** [comment]
You can take a look here in my project:  
https://github.com/Jubeki/Nova-Card-Linkable

These are not fields but it should be almost the same if you just alter the structure of one package.  
I hope it can help you.

**Comment by davidhemphill** [comment]
Sure, just register and link multiple fields in your `field.js`:

```php
Nova.booting((Vue, router, store) => {
  // Field 1
  Vue.component('index-{{ component }}', require('./components/IndexField'))
  Vue.component('detail-{{ component }}', require('./components/DetailField'))
  Vue.component('form-{{ component }}', require('./components/FormField'))

  // Field 2
  Vue.component('index-{{ component }}', require('./components/IndexField2'))
  Vue.component('detail-{{ component }}', require('./components/DetailField2'))
  Vue.component('form-{{ component }}', require('./components/FormField2'))
})
```

Then, create your `Field` classes and use them normally.
