### ISSUE TITLE
Problem with KeyValue

### ISSUE THREAD

**Issue by nuruder** [laravel/nova-issues#2321]
- Laravel Version: 6.13.1
- Nova Version: 2.9.4
- PHP Version: 7.2.24
- Database Driver & Version: PostgreSQL 11
- Operating System and Version: Ubuntu 18.04
- Browser type and version: Chrome

### Steps To Reproduce:
- Add resource with keyvalue
- Add key: 0 and value "test"
- Save
<img width="1098" alt="Снимок экрана 2020-02-03 в 15 22 20" src="https://user-images.githubusercontent.com/7907169/73652929-1b4a0d80-4699-11ea-99bf-e4fe174cf9b4.png">

**Comment by BenWalters** [comment]
@nuruder I'm not sure on your intended use case but here is an example of how to get this to work:

```
KeyValue::make('Test')
                ->withMeta([
                    'value' => [
                        'keyWithValue' => 'keyValue',
                        'keyWithNoValue' => null,
                    ]
                ]),
```

Will produce:
![image](https://user-images.githubusercontent.com/43746367/73777931-39d80380-4782-11ea-8900-fc1c3a8db497.png)

Be mindful that the information you set in the Meta overrides any values provided by the user.
Hope this helps.

**Comment by davidhemphill** [comment]
KeyValue fields use JSON as their storage mechanism. Numerically indexed keys don't work in this situation because that would be a plain array in JSON.

**Comment by nuruder** [comment]
No, numerically indexed keys is not a problem.
I trying key "one" and value "thing". In database i have {"one":"thing"} (its correct), but in Nova i see this
<img width="1109" alt="Снимок экрана 2020-02-04 в 22 38 32" src="https://user-images.githubusercontent.com/7907169/73780437-8978f800-479f-11ea-9042-76b1b6c04da9.png">

**Comment by BenWalters** [comment]
@nuruder can you share your code for the field? I don't get this issue using the same version of Nova

**Comment by nuruder** [comment]
`public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
            Text::make('Название','name'),
            KeyValue::make('kv'),
        ];
    }`

:(

**Comment by BenWalters** [comment]
@nuruder not sure what's wrong for you, I've got the following in my DB: 
![image](https://user-images.githubusercontent.com/43746367/73784607-b0c6c980-478d-11ea-8c82-b79a924bdd3c.png)

And my code:
```
KeyValue::make('Identifiers')
```

How it displays:
![image](https://user-images.githubusercontent.com/43746367/73784696-d3f17900-478d-11ea-946e-b5a6eb95c6f1.png)

**Comment by BenWalters** [comment]
@nuruder How is the JSON stored in your DB?

I've managed to replicate your issue by wrapping the JSON in quotes!

**Comment by nuruder** [comment]
@BenWalters {"one":"thing"} in TEXT field PostgreSQL..

**Comment by BenWalters** [comment]
@nuruder strange, I'm using MySQL and sorting it in a JSON field.

**Comment by nuruder** [comment]
@BenWalters with JSON field:
<img width="1470" alt="Снимок экрана 2020-02-07 в 18 25 49" src="https://user-images.githubusercontent.com/7907169/74041759-51f49080-49d7-11ea-929b-f010d06edb0d.png">
<img width="157" alt="Снимок экрана 2020-02-07 в 18 26 26" src="https://user-images.githubusercontent.com/7907169/74041789-6042ac80-49d7-11ea-98b9-3db1cfe21ce2.png">

**Comment by BenWalters** [comment]
@nuruder I think that your DB is return it as text. In your model try casting your value to type json like this:

```
protected $casts = [
    'kv' => 'json'
];
```

Hope this helps, else I'm out of ideas!

**Comment by nuruder** [comment]
@BenWalters it's work! thank you so much!

**Comment by BenWalters** [comment]
@nuruder no problem, glad I could help. 👍

**Comment by CaddyDz** [comment]
Casting to array also worked for me
```php
protected $casts = [
    'meta' => 'array',
    'accompanist' => 'array'
];
```

**Comment by HassanElshazlyEida** [comment]
try 
```
protected $casts = [
  'meta' => 'collection',
];
```
