### ISSUE TITLE
Custom Avatars

### ISSUE THREAD

**Issue by daugaard47** [laravel/nova-issues#2324]
I'm currently trying to get Nova to play nice with my existing website and existing `users table`. 

My issue is with the Gravatar. I already have an avatar field in my users table and would like to display those rather the auto generated Gravatars.

In my Nova/User class I have the following. (Also changed to first_name and last_name)
```
    public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),

           Gravatar::make('Avatar'),

            Text::make('First Name')
                ->sortable()
                ->rules('required', 'max:255'),

            Text::make('Last Name')
                ->sortable()
                ->rules('required', 'max:255'),

            Text::make('Email')
                ->sortable()
                ->rules('required', 'email', 'max:254')
                ->creationRules('unique:users,email')
                ->updateRules('unique:users,email,{{resourceId}}'),

            Password::make('Password')
                ->onlyOnForms()
                ->creationRules('required', 'string', 'min:8')
                ->updateRules('nullable', 'string', 'min:8'),
        ];
    }
```

When a user registers normally via the registration form, I'm doing the following with the avatar column from my auth > register controller. (I want to do the same in the Nova User Create)

RegisterController.php
```
    protected function create(array $data)
    {
        $hash = md5(strtolower(trim($data['email'])));
        $gravatar = 'http://www.gravatar.com/avatar/'.$hash.'??s=200&d=identicon';
        $user = User::create([
            'first_name' => $data['first_name'],
            'last_name' => $data['last_name'],
            'email' => $data['email'],
            'password' => Hash::make($data['password']),
            'avatar' => $gravatar, // user DB `avatar` is set to a default image (default-avatar.png)
            'role_id' => '0', // DB is set to default 0
        ]);
}
``` 

1. When I create a new user **Via Nova**, where/what is the form request that it is hitting?
2. Where can I change the Nova/User view to display my avatars from my users database?

**Comment by LorenzoSapora** [comment]
As mentioned in the discord:

`Avatar::make('Avatar')->disk('your-filesystem')` is all you need.

https://nova.laravel.com/docs/2.0/resources/file-fields.html#avatars

and depending on how your avatar column in the database is populated, you might not even need the `disk()` method.

And to answer your questions

1. it's dependent on your model/resource. Check your `app/Nova/User.php` and `app/Models/User.php` 
2. you don't need to modify anything, just use the methods on Avatar.

**Comment by davidhemphill** [comment]
Yeah, agree with @LorenzoSapora here, you should just use the `Avatar` field here since it seems like exactly what you want.

**Comment by daugaard47** [comment]
@LorenzoSapora Apologies for my lack of knowledge here.

This is my issue... I currently have 300+ existing users. 1/3 has uploaded their own Avatar image, everyone else is using the default image and the new users will be using a Gravatar.
In my `users table > avatar column` I have the following:

1. Default image like this: DefaultAvatar.png
2. A Gravatar string: https://www.gravatar.com/avatar/...?s=300&d=identicon 
3. Personal Uploaded image: https://mysite.org/storage/images/users/1/avatar/JohnSmith-855e212f.jpg

This is how I'm displaying the 3 optional avatars on the **front-end**:
```
    @php
    $userId = Auth::user()->id;
    $userAvatar = Auth::user()->avatar;
    @endphp

    // Option 1.
    // If User has 'DefaultAvatar.png' in the avatar column use this.
    @if (Auth::check() && (Auth::user()->avatar == 'DefaultAvatar.png'))
    <div class="..." style="background-image:url(/images/DefaultAvatar.png)"></div>

    // Option 2.
    // If User has 'Garavatar Link' in the avatar column use this.
    @elseif (strpos($userAvatar, 'gravatar') == true)
        <div class="..." style="background-image:url({{ $userAvatar }}"></div>

    @else
    // Option 3.
    // If User has 'Their Own Image' in the avatar column use this.
        <div class="..." style="background-image:url({{ asset("storage/images/users/$userId/avatar/$userAvatar") }}"></div>
    @endif
```

So how could I do this same logic in the Nova Users View?

How could I do something like this logic?

```
    $userId = User::user()->id;
    $userAvatar = User::user()->avatar;
 
    if ( $userAvatar == 'DefaultAvatar.png'){
    // Option 1.
    // If User has 'DefaultAvatar.png' in the avatar column use this.
    return 'https://mysite.com/images/DefaultAvatar.png';

    }elseif (strpos($userAvatar, 'gravatar') == true){
    // Option 2.
    // If User has 'Garavatar Link' in the avatar column use this.
       return  $userAvatar;

   }else{
    // Option 3.
    // If User has 'Their Own Image' in the avatar column use this.
    return 'https://mysite.com/images/users/'.$userId.'/'.$userAvatar;
    }
```

Is there a way to add this logic as a file system and then call it like this in Nova? 
`Avatar::make('Avatar')->disk('currentAvatars'),`

Looking at the `filesytem.php` file I don't see how that can be accomplished.

**Comment by LorenzoSapora** [comment]
No need to apologise, happy to help.

From what you've said here, do you mean that from now on, all new users will have Gravatars as their default? It's not wise to change methodology half way through. Either convert all the users who don't have avatars to the gravatar, or go with the default image all the time, and only have it changed when a user changes it.

Having the three options makes it very messy, and I would suggest trying to keep it as basic as possible. User has default image, until it's changed by the user. Adding the gravatar into the mix, really makes things overly complicated, when it's not required to be so.

**Comment by daugaard47** [comment]
> do you mean that from now on, all new users will have Gravatars as their default?

YES.

> Having the three options makes it very messy, and I would suggest trying to keep it as basic as possible.

Fair enough, and I agree.

------
So with that. I would then like to do the following.

Switch all over to gravatar and give the option to upload their own image.

Based on this I would still need to do the following:

 - Currently the database sets a default image on registration.
 - I should remove this and allow Null

1. Change all user to display a gravatar based on their emails.
2. Need to display users own avatar image

So something like...

If (avatar !== null)
Display Users personal avatar
Else
Display Gravatar.

Does that sound correct?

**Comment by LorenzoSapora** [comment]
Because you're going to be basing your avatars from your users email addresses, mixing the two options of gravatar OR user uploaded images.. is going to be rough time for you.

As a rough idea, you'd have to have some sort of boolean (database or code based) check usingCustomAvatar, and then check that every time you're dealing with avatars.

Honestly I'd suggest you either go full gravatar, or just have a default avatar + user uploaded avatar. Especially with using Nova.

**Comment by nicko170** [comment]
If anyone is still looking for this - Using Laravel 8 with Jetstream scaffolding,

`app/Nova/Fields/Avatar.php`
```php
<?php

namespace App\Nova\Fields;

use Illuminate\Support\Facades\Storage;
use Laravel\Nova\Contracts\Cover;
use Laravel\Nova\Fields\Image;

class Avatar extends Image implements Cover
{
    /**
     * Create a new field.
     *
     * @param string|null $name
     * @param string|null $attribute
     * @param string|null $disk
     * @param callable|null $storageCallback
     * @return void
     */
    public function __construct($name = 'Avatar', $attribute = null, $disk = 'public', $storageCallback = null)
    {
        parent::__construct($name, $attribute, $disk, $storageCallback);

        $this->rounded();
        $this->resolveUsing(fn($value, $resource, $attribute) => $resource->$attribute ?: $resource->profile_photo_url);

        $this->thumbnail(function () {
            if (filter_var($this->value, FILTER_VALIDATE_URL)) {
                $this->disableDownload();
                $this->deletable(false);
                return $this->value;
            }
            return $this->value ? Storage::disk($this->getStorageDisk())->url($this->value) : null;
        })->preview(function () {
            if (filter_var($this->value, FILTER_VALIDATE_URL)) {
                $this->disableDownload();
                $this->deletable(false);
                return $this->value;
            }
            return $this->value ? Storage::disk($this->getStorageDisk())->url($this->value) : null;
        });
    }
}
```

`app/Models/User.php`
```php

class User extends Authenticatable
{
    use HasProfilePhoto;

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];

    /**
     * Get the default profile photo URL if no profile photo has been uploaded.
     *
     * @return string
     */
    protected function defaultProfilePhotoUrl(): string
    {
        return 'https://www.gravatar.com/avatar/'.md5($this->email).'?d=robohash&s=256';
    }
}
```

Using in Nova:
`app/Nova/Resource.php`
```php
use App\Nova\Fields\Avatar;

class User extends Resource
{
    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [
            ID::make(__('ID'), 'id')->sortable()->readonly(true),

            Avatar::make()->maxWidth(50),

            Text::make('Name')
                ->sortable()
                ->rules('required', 'max:255'),
        ]
    }
}
```


![Screen Shot 2021-07-20 at 10 57 46 am](https://user-images.githubusercontent.com/9477420/126246265-916ea2ea-09b0-4355-97fb-c33fa33948f6.png)

![Screen Shot 2021-07-20 at 10 58 01 am](https://user-images.githubusercontent.com/9477420/126246286-8bee06f4-106d-459a-b868-9535757b9f80.png)

**Comment by Assurancedeserted80** [comment]
https://phps.space/questions/assigning-a-distinct-numerical-identifier-to-a-given-name



Examine this answer
