### ISSUE TITLE
Readonly BelongsTo field shows "+ Create"

### ISSUE THREAD

**Issue by sirikkoster** [laravel/nova-issues#2325]
- Laravel Version:v6.14.0
- Nova Version: v2.10.0

### Description:
I have an readonly belongsTo field and next to this it says "+ Create" if I accidentally add an relation I'm unable to change is to it's original value because it's read-only . 

This is an unwanted action.

Is it possible to hide/disable this button when a field is readonly or with an function callback?

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍

**Comment by sirikkoster** [comment]
Good work @davidhemphill, thnx
