### ISSUE TITLE
In nova is there any way i can select Multiple value from Select Filters

### ISSUE THREAD

**Issue by jigarhalani** [laravel/nova-issues#2327]
Hello, I am using laravel nova => 2.6.1...
I created select filter in nova but i want the user to select multiple values from select box...so is there any way I can achieve this requirement....

**Comment by BenWalters** [comment]
@jigarhalani I don't think there is functionality for this out of the box but there are some packages on the novapackages site. I had a quick look and found this one - https://novapackages.com/packages/rcknr/nova-multiselect-filter

**Comment by jigarhalani** [comment]
not working for me

**Comment by jbrooksuk** [comment]
This isn't a feature of Nova, but you should open an issue on the nova-multiselect-filter repo.
