### ISSUE TITLE
Back button on Detail page

### ISSUE THREAD

**Issue by vayurobins** [laravel/nova-issues#2328]
Hi.

It would be really useful to have a backlink on the detail page, just link on the Lens page. Is there a way I could add this somehow?

![Screenshot 2020-02-05 at 16 53 56](https://user-images.githubusercontent.com/1386354/73858171-4159e400-4838-11ea-96ba-32a9164a402b.png)

**Comment by davidhemphill** [comment]
Lenses having a back button was an oversight in the original Nova release that'll be removed in a future breaking change.

**Comment by vayurobins** [comment]
I can see that it's good that it's removed from Lenses, but it would still be nice to have on Detail page. :-)

**Comment by davidhemphill** [comment]
We've been down this familiar path before with laravel/nova#586 and decided this is not a problem we feel is worth the effort at this time.
