### ISSUE TITLE
Clicking a +create inside a modal breaks cancel button

### ISSUE THREAD

**Issue by LorenzoSapora** [laravel/nova-issues#2330]
Related to #2329 

When clicking a +create inside a modal window, it changes the 'create X' to 'create Y', but nothing else. Then breaks the cancel button.

It allows you to 'go back' to the original create modal, BUT doesn't let you close the modal using the cancel button, whatsoever.

**Comment by davidhemphill** [comment]
I'm not able to replicate this is our test repository. Canceling modals works correctly. Please make sure you've updated Nova's assets using `php artisan nova:publish` using the `--force` option if necessary. If you can replicate this, please provide the information requested in the issue template. Thanks!
