### ISSUE TITLE
Collection::isAssoc does not exist on /nova-vendor/* requests

### ISSUE THREAD

**Issue by dmitrybubyakin** [laravel/nova-issues#2332]
- Laravel Version: 6.13.1
- Nova Version: 2.9.4
- PHP Version: 7.3.9

### Description:

In my custom field I do some api calls (like `/nova-vendor/.../...`) and get this message:
```
Method Illuminate\Support\Collection::isAssoc does not exist.
/var/www/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php#104
```

### Steps To Reproduce:

The BooleanGroup field is within my resource. When I call `Resource::fields(...)` inside the `/nova-vendor/...` request I get the exception above.

**Comment by jbrooksuk** [comment]
Strange, the `isAssoc` Collection method is a macro that gets registered in the `NovaServiceProvider`. Can you check that the provider has been registered correctly?

**Comment by dmitrybubyakin** [comment]
@jbrooksuk the `NovaServiceProvider` is registered here https://github.com/laravel/nova/blob/2.0/src/Http/Middleware/ServeNova.php#L21, but the `isNovaRequest` method returns false in case the route path starts with `/nova-vendor/*`

**Comment by dmitrybubyakin** [comment]
@jbrooksuk And these macros are not registered too:
```php
Carbon::mixin(new Macros\FirstDayOfQuarter);
Carbon::mixin(new Macros\FirstDayOfPreviousQuarter);
```

**Comment by jbrooksuk** [comment]
@davidhemphill I think we could move these macros into a smaller service provider that always gets registered. What do you reckon?
