### ISSUE TITLE
Ignore some extra form fields while saving in model database

### ISSUE THREAD

**Issue by hasnatbabur** [laravel/nova-issues#2334]
We are using Nova for managing posts, comments, tags which comes from end users of our site.

At front end of our site in creating post form we pass some extra input fields those are not directly related to model attribute but for some other features for that post.

When we define extra interact-able input fields in Nova creation form, Nova tries to save those input fields in model table and causes 'column not found' type error. Please these are not 'Computed' field but real form input fields users can fill up.

I know I can use model observer to remove those extra fields before saving in database, but I don't want to mix up front end user actions and nova actions in that way.

Expecting Nova should have a function that will allow removing some extra form fields saving in model database at run time.

Is there any better solution for this case? Thanks in advance.

**Comment by davidhemphill** [comment]
You can pass an empty callback to the `fillUsing` helper on the field to keep it from filling the model.

**Comment by hasnatbabur** [comment]
@davidhemphill Thanks for your help but it does not work.
I am using Image/File field type and they overrides `fillForAction` method directly on src/Fields/File class.

```
    public function fillForAction(NovaRequest $request, $model)
    {
        if (isset($request[$this->attribute])) {
            $model->{$this->attribute} = $request[$this->attribute];
        }
    }
```

This directly ignores further setting custom `fullUsing` callback on a specific fields.

How I can handle this situation for Image/File field type? Thanks

**Comment by hasnatbabur** [comment]
I figured this overriding the fillFields method in resource class (i.e App\Nova\Post)

```
    protected static function fillFields(NovaRequest $request, $model, $fields)
    {
        $fillFields = parent::fillFields($request, $model, $fields);

        // first element should be model object
        $modelObject = $fillFields[0];

        // remove all attributes do not have relevant columns in model table
        unset($modelObject->featured_image);

        return $fillFields;
    }
```

Now it's not throwing 'column not found' type error for extra form fields.

I hope this can be helpful for others. Thanks

**Comment by marianne-fullstack** [comment]
>  protected static function fillFields(NovaRequest $request, $model, $fields)
>     {
>         $fillFields = parent::fillFields($request, $model, $fields);
> 
>         // first element should be model object
>         $modelObject = $fillFields[0];
> 
>         // remove all attributes do not have relevant columns in model table
>         unset($modelObject->featured_image);
> 
>         return $fillFields;
>     }

Hi @hasnatbabur , does the 'first element should be model object' means that i should put the field that represents the model on the top?? if so, can i adjust in any way?

**Comment by hasnatbabur** [comment]
@marianne-fullstack Without testing now, I believe the $model at parameter is coming from database model instance. But what we needed was to remove the extra attribute (those does not have database column) in the request data. As extra attribute was removed from request data, so further execution of the code does not throw 'column not error'! Hope this helps. Thanks

**Comment by tigusigalpa** [comment]
> I figured this overriding the fillFields method in resource class (i.e App\Nova\Post)
> 
> ```
>     protected static function fillFields(NovaRequest $request, $model, $fields)
>     {
>         $fillFields = parent::fillFields($request, $model, $fields);
> 
>         // first element should be model object
>         $modelObject = $fillFields[0];
> 
>         // remove all attributes do not have relevant columns in model table
>         unset($modelObject->featured_image);
> 
>         return $fillFields;
>     }
> ```
> 
> Now it's not throwing 'column not found' type error for extra form fields.
> 
> I hope this can be helpful for others. Thanks

good, but now when you call `fillUsing`, the field came ignored to the model, so if you want to make an own handler to save the field data, use something like this

`MyField::make('My Text', 'unique_name_for_model')->[...]->fullUsing(NovaRequest $request, $model, $attribute, $requestAttribute){/*your needle value is at $request->input('unique_name_for_model') and not at the $model object*/})`
