### ISSUE TITLE
"Create and add another" button only visible when viaRelationship is empty

### ISSUE THREAD

**Issue by timboozle** [laravel/nova-issues#2335]
- Nova Version: 2.10.0

The "create and add another" button is now only visible when you click Create on a "root" resource. 
I think the button should also be visible when creating a new resource from a relationship page. 

In our case the user finds an App\Product which has many App\ProductVariation. They need to be able to add multiple variations at once. The resource ProductVariation is not shown independently.

**Comment by BenWalters** [comment]
@timboozle What is the relationship between Product & ProductVariation, if it is BelongsToMany then the Create/Add Another should still be there. The reason it was removed can be found here - https://github.com/laravel/nova-issues/issues/1816
