### ISSUE TITLE
How use Nova v2.10.0 "Decoding filters values from the UI has been extracted to a helper class to enable use in calculating metrics and custom tools. #783" ?

### ISSUE THREAD

**Issue by oleksandr-roskovynskyi** [laravel/nova-issues#2336]
### Description:
Tell me, please, how to calculate and deduce the sum of the values from the dynamic number of resource columns? https://ibb.co/WvfZkRd

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).
