### ISSUE TITLE
About localization

### ISSUE THREAD

**Issue by savemydream** [laravel/nova-issues#2337]
- Laravel Version: 6.2.*
- Nova Version: 2.10.1
- PHP Version: 7.3.13
- Database Driver & Version: MySQL 8.0.17
- Operating System and Version: Ubuntu 16.04
- Browser type and version: Google Chrome 79.0.3945.130 (bit 64)
- Reproduction Repository: null

### Description:
I am a Laravel follower from Taiwan.
I found a very small bug.
I solved the problem by myself, but I hope it will be improved in the next version.
I changed these codes to translatable.

### Steps To Reproduce:
```
// /src/Panel.php
public static function defaultNameForDetail(Resource $resource)
{
    return __(':resource :Details', [
        'resource' => $resource->singularLabel(),
        'Details' => __('Details')
    ]);
}

public static function defaultNameForCreate(Resource $resource)
{
    return __(':Create :resource', [
        'resource' => $resource->singularLabel(),
        'Create' => __('Create')
    ]);
}

public static function defaultNameForUpdate(Resource $resource)
{
    return __(':Update :resource', [
        'resource' => $resource->singularLabel(),
        'Update' => __('Update')
    ]);
}
```

**Comment by jbrooksuk** [comment]
It looks like you configured your translations incorrectly. Here's how it's done.

Let's say we're using French as our language (ISO `fr`). Set the `app.locale` value to be `fr`. Create a `./resources/lang/fr.json` file with:

```json
{
    ":resource Details": ":resource Détails"
}
```

![image](https://user-images.githubusercontent.com/246103/74738314-89bccd00-524e-11ea-8171-8c0464fd013d.png)
