### ISSUE TITLE
Global search for numeric fields will ignore them

### ISSUE THREAD

**Issue by tpetry** [laravel/nova-issues#2338]
- Laravel Version: 6.14.0
- Nova Version: 2.10.1
- PHP Version: 7.4.2
- Database Driver & Version: PostgreSQL 12.1.1
- Operating System and Version: Debian 8.3

### Description:
No integer columns will be found in novas global search.

### Steps To Reproduce:
1. Add any integer field to novas global search
2. Search within the resource's local search -> row will be found
2. Search within the global search -> row will not be found

**Comment by jbrooksuk** [comment]
Not able to replicate that here?

![image](https://user-images.githubusercontent.com/246103/74737593-0cdd2380-524d-11ea-8b02-d27b267bb120.png)

**Comment by tpetry** [comment]
Are you using PostgreSQL?

**Comment by jbrooksuk** [comment]
MySQL.

**Comment by tpetry** [comment]
It's working on all our MySQL project but not on some of PostgreSQL project, i will update with more information as soon as i find out.
