### ISSUE TITLE
Login routes ignore middleware config

### ISSUE THREAD

**Issue by timwachsener** [laravel/nova-issues#2339]
- Laravel Version: 6.14.0
- Nova Version: 2.10.1
- PHP Version: 7.4.0

### Description:
When setting up a Laravel application that doesn't use sessions in it's default web middleware config the Nova login routes throw an exception `$errors is undefined` because they ignore the middleware set in `config/nova.php`.

### Steps To Reproduce:
1. Remove `ShareErrorsFromSession` from `web` middleware stack
2. Add `ShareErrorsFromSession` to middleware stack in `config/nova.php`
3. Exception on login

**Comment by jbrooksuk** [comment]
In your `NovaServiceProvider` class you can do:

```php
use Illuminate\View\Middleware\ShareErrorsFromSession;

// ...

protected function routes()
{
    Nova::routes()
            ->withAuthenticationRoutes([ShareErrorsFromSession::class])
            ->withPasswordResetRoutes()
            ->register();
}
```
