### ISSUE TITLE
Update event not firing for only changing extra form fields

### ISSUE THREAD

**Issue by hasnatbabur** [laravel/nova-issues#2342]
I feel nova will not attempt to update a resource if I do not change at least one form field.

How ever I have some extra form fields (Filepond Image, Boolean) for some business logic not directly related to Post model.

Changing only extra form fields does not trigger any real update request hence it does not reach to Model saving event.

How can I force Nova to send real update request always when we click on 'update' or 'update & continue' buttons?

This is very urgent and please help here.

Thanks

**Comment by jbrooksuk** [comment]
Sorry, but we are unable to debug your issue without a reproducible code example. Once you provide that we can open this up again.
