### ISSUE TITLE
Support for RTL

### ISSUE THREAD

**Issue by kfirba** [laravel/nova-issues#2346]
- Laravel Version:  6.14.0
- Nova Version: 2.10.1
- PHP Version: 7.3.14
- Browser type and version: Chrome

### Description:
Hey.

We need to use nova with RTL support. There is a [nice package](https://github.com/pishran/nova-rtl-theme) that helps to migrate nova's design to support RTL.

However, there are a few issues with Dropdown alignments. Some components' placement is "fixed" in the source code. For example, the `views/Index.vue` component declares a `SelectAll` dropdown (around line 87). The initiation of the dropdown states that the placement should be `bottom-end`, which makes the dropdown open from the `left` edge in RTL context:

![image](https://user-images.githubusercontent.com/8510486/74316310-fd0f9c00-4d81-11ea-83c5-21d12a7ebf14.png)

Ideally, the placement of the dropdown should be automatically calculated instead of being hard-coded. [The docs](https://www.npmjs.com/package/v-tooltip) for `v-tooltip` states that one of the possible placements is `bottom` which,*I guess* , will automatically calculate the `left/right` position.

Alternatively, it would be great if nova had an `isRtl` config (probably declared in the `config/nova.php` file which will cascade down to the frontend (and potentially will be embedded in every component through a mixin/vuex). Then in the components themselves, we can dynamically figure out what the alignment for the dropdowns should be.

I would open a PR but I don't think it is possible to PR Nova's source code?

**Comment by davidhemphill** [comment]
You can join the private repository by connecting your GitHub account here: https://nova.laravel.com/settings#github

**Comment by FaridAghili** [comment]
And we have an open issue about the dropdown's alignment:
https://github.com/pishran/nova-rtl-theme/issues/3

Couldn't fix it thu.

**Comment by kfirba** [comment]
@davidhemphill thanks. I’ll probably dedicate some time to it on weekend. 

@FaridAghili Have you tried what I mentioned in this issue 🤔? I’ll try to solve the positioning of the dropdown. Thanks for your work on the RTL fixes.

**Comment by FaridAghili** [comment]
@kfirba I didn't tried that, feel free to send a PR.

**Comment by kfirba** [comment]
@davidhemphill I'm struggling a bit with working with the frontend. What is the best way to make changes to the front end and see that reflected in the app? I currently have a `demo` app which I've installed Nova on using composer's `repositories` option to symlink nova to a local folder. This works great for PHP changes but it's not that convenient for the front-end changes.

Currently what I do is that every time I make a change I run `php artisan nove:publish --force` to see the changes. I thought that maybe I can solve this by overriding the `demo` project's `public/vendor/nova` directory to be a symlink to the local copy of nova.

Is this really the best way to do this or am I missing something?

**Comment by kfirba** [comment]
@davidhemphill @FaridAghili I've submitted a PR: https://github.com/laravel/nova/pull/793

**Comment by iBelit** [comment]
> 
> 
> You can join the private repository by connecting your GitHub account here: https://nova.laravel.com/settings#github

Hi, I cant join! what should I do? I am getting this error `"There was a problem adding you to the repository. We've been notified and we're on it!"`

**Comment by jbrooksuk** [comment]
@iBelit can you please email nova@laravel.com?

@kfirba when I work on Nova, I have a symlink in my demo app that points to Nova's public directory:

```
ln -sf /Users/james/Code/laravel/nova/public /Users/james/Code/laravel/nova-fresh/public/vendor/nova
```

**Comment by jbrooksuk** [comment]
@iBelit ignore me, I see you've emailed.

**Comment by kfirba** [comment]
@jbrooksuk Hey James.

It's almost been a month. Is there any progress with this? Did you manage to install an RTL theme in order to see the issue that this PR solves?

**Comment by jbrooksuk** [comment]
Afraid not!

Also, I forgot to close this, as we do all feature requests.

**Comment by kfirba** [comment]
@jbrooksuk What does it mean? Is there any plan for supporting RTL out of the box?

**Comment by FaridAghili** [comment]
Dropdown alignment problem has been fixed recently:

- Update to latest Laravel Nova (v3.8.4)
- Update to latest [nova-rtl-theme](https://github.com/pishran/nova-rtl-theme) (v1.5)
- Issue fixed
