### ISSUE TITLE
Mail sent from Nova actions does not appear in Telescope

### ISSUE THREAD

**Issue by stancl** [laravel/nova-issues#2347]
- Laravel Version: 6.13.1
- Nova Version: 2.9.4
- PHP Version: 7.4
- Database Driver & Version: sqlite
- Operating System and Version: Ubuntu 19.04
- Browser type and version: Chrome

### Description:

Mail sent from listeners to event triggered (indirectly) by Nova actions is not displayed in Telescope. When this event is triggered (indirectly) by something in non-Nova code, the mail is sent and can be inspected in Telescope.

@jbrooksuk [commented](https://github.com/laravel/nova-issues/issues/2274#issuecomment-574382139) on #2274 (*Cache do not appear in Telescope*):

> Nova requests are excluded by default because they’re not apart of *your* app as such.

However, Nova actions **are** part of my app, just like the events triggered by them.

### Steps To Reproduce:

Create a Nova action that sends a mail. You won't see it in Telescope.

**Comment by jbrooksuk** [comment]
You need to configure Telescope not to exclude the `nova-api` routes.

https://github.com/laravel/telescope/blob/ef6c64c39e3ae5bdae7263fd9e106ee8048d9188/src/Telescope.php#L188

**Comment by stancl** [comment]
@jbrooksuk It merges the Nova routes with the routes provided in that config though. So that wouldn't disable it, but mark it as ignored again?

**Comment by stancl** [comment]
Yes @jbrooksuk, it would only mark the route as ignored again. If this could be solved with config, it would look like this:

```php
protected static function handlingApprovedRequest($app)
{
    return ! $app->runningInConsole() && ! $app['request']->is(
        array_diff(array_merge([
            config('telescope.path').'*',
            'telescope-api*',
            'vendor/telescope*',
            'horizon*',
            'vendor/horizon*',
            'nova-api*',
        ], config('telescope.ignore_paths', [])), config('telescope.include_paths', []))
    );
}
```

So either this config key should be added or there should be some method that can be called from the action to explicitly enable Telescope.

**Comment by jbrooksuk** [comment]
https://github.com/laravel/telescope/pull/799
