### ISSUE TITLE
Force delete file prunable() issue

### ISSUE THREAD

**Issue by Jam0r85** [laravel/nova-issues#235]
When using prunable() on a file field and forceDeleting the record an error is given as it attempts to place null into the attachment field.

Surely if the record is being forceDeleted then there is no need for null and both the record and file should be removed?

Removing prunable fixes the issue but the actual file still remains in storage when forceDeleting.

Is prunable needed when your using softDeletes? Surely in 99.9% of cases when forceDeleting an attachment record you'd want the file to be removed as well.

**Comment by dkulyk** [comment]
What is your Nova version?

**Comment by dkulyk** [comment]
This has been fixed and will be included in the next release.
