### ISSUE TITLE
Resource Redirect After Delete

### ISSUE THREAD

**Issue by judahnator** [laravel/nova-issues#2350]
As a follow up to #538, it would be really handy if we could also have a "redirect after delete" method for resources.

There currently exists the following:

```
    public static function redirectAfterCreate(NovaRequest $request, $resource)
    {
        return '/resources/'.static::uriKey().'/'.$resource->getKey();
    }

    public static function redirectAfterUpdate(NovaRequest $request, $resource)
    {
        return '/resources/'.static::uriKey().'/'.$resource->getKey();
    }
```

It would be awesome if this could also be added:

```
    /**
     * Return the location to the redirect the user after deletion.
     *
     * @param \Laravel\Nova\Http\Requests\NovaRequest $request
     * @param  \Laravel\Nova\Resource  $resource
     * @return string
     */
    public static function redirectAfterDelete(NovaRequest $request, $resource)
    {
        return '/resources/'.static::uriKey();
    }
```

My use case is that my specific resource should only ever be accessed from its parent resource that it `belongsTo`.

Take for example a 'Business' model that has many 'Locations', that has many 'Supplies'. In this case if I delete a 'Supply' from the 'Location' model, I get redirected to the list of all supplies for all businesses/locations. This is a long list that does not mean much without the context of the parent models.

It would be ideal if a user could supply a route to give, so if I wanted to instead redirect back to the parent model 'Detail' page I could do so.

**Comment by jbrooksuk** [comment]
What happens when a user batch deletes a resource?

**Comment by judahnator** [comment]
The current behaviour for batch deletion is to remain on the same page you are looking at. I think this can remain unchanged.

However, if you are on the "detail" page of a resource and you delete it form there, the question is "where do we redirect the user, now that the resource they are looking at does not exist."

I am petitioning for a feature to allow the destination of this post-delete redirect to be configurable by the developer, in cases where redirecting back to the global resource index does not make much sense.

**Comment by lab08tonci** [comment]
Is this solved in any way?
Or can it be reopened?

**Comment by jbrooksuk** [comment]
This is solved and available in v3.2.1:

```php
/**
 * Return the location to redirect the user after deletion.
 *
 * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
 * @return string
 */
public static function redirectAfterDelete(NovaRequest $request)
{
    return '/resources/'.static::uriKey();
}
```

This will only work when you're deleting one resource.

**Comment by iBet7o** [comment]
Hello o/,

I am trying to make this work but have not been successful, I use version 3.6.0. Is it necessary to make other modifications besides adding the redirectAfterDelete method to the resource?

Another thing I noticed is that the viaResource and viaResourceId variables are not being sent and would be very helpful in redirecting to the main resource.

@judahnator has the method worked for you?

Regards,

**Comment by patrickleemsantos** [comment]
Tested also on 3.6.0 it does not work as expected and can't get the resourceID. Any solution here?

**Comment by stuartcusackie** [comment]
Also having problems with this. The resource I am deleting is not available in the sidebar - it can only be accessed through it's parent relationship. So deleting the resources should ideally bring me back to the parent, not the resource index, which should be innaccessible.

**Comment by warksit** [comment]
In case it works for anyone else, I worked round this as follows, in an observer for the resourse being deleted (obviously use your own Models!) I added the following:

  ```
public function deleting(PaymentPayee $paymentPayee)
{
    session()->flash('payment_of_deleted_payment_payee', $paymentPayee->payment_id);
}
```

and then in the Nova Resource:

```
public static function redirectAfterDelete(NovaRequest $request)
{
    return '/resources/payments/' . session('payment_of_deleted_payment_payee');
}
```
