### ISSUE TITLE
Issues with PostgreSQL connection pooling

### ISSUE THREAD

**Issue by henryavila** [laravel/nova-issues#2352]
- Laravel Version: 6.15
- Nova Version: 2.10.1
- PHP Version: 7.3
- Database Driver & Version: PostgreSQL 11

### Description:
PostgreSQL database clusters use PgBouncer for connection pooling and prepared statements are not supported in transaction pooling mode

### Steps To Reproduce:
Runing Laravel Nova with a PostgreSQL using connection pooling provided by PgBouncer, will throw erros like:
```
SQLSTATE[26000]: Invalid sql statement name: 7 ERROR: prepared statement "pdo_stmt_00000001" does not exist (SQL: select * from "users" where "id" = 1 and "users"."deleted_at" is null limit 1)
```

**Comment by jbrooksuk** [comment]
Nova heavily uses prepared statements and so we won't be able to support PgBouncer.

**Comment by JosephAdewole** [comment]
I know this is closed, however, a tip is to use **session pooling** instead of **transaction pooling** in the pgbouncer configuration.

**Comment by Gnative** [comment]
Alternative option, if someone is looking, is to run separate DB connection for Nova that is not via connection pooling and use a middleware to set this. The middleware can be added in the `config/nova.php` file.

```php
<?php

namespace App\Http\Middleware;

use Closure;

class NovaDatabase
{
    public function handle($request, Closure $next)
    {
        // Change database config for Nova routes
        config([
            'database.default' => env('NOVA_DATABASE', 'pgsql'),
        ]);

        return $next($request);
    }
}
```


```php
    /*
    |--------------------------------------------------------------------------
    | Nova Route Middleware
    |--------------------------------------------------------------------------
    |
    | These middleware will be assigned to every Nova route, giving you the
    | chance to add your own middleware to this stack or override any of
    | the existing middleware. Or, you can just stick with this stack.
    |
    */

    'middleware' => [
        'web',
        NovaDatabase::class,
        HandleInertiaRequests::class,
        DispatchServingNovaEvent::class,
        BootTools::class,
    ],

    'api_middleware' => [
        'nova',
        NovaDatabase::class,
        Authenticate::class,
        Authorize::class,
    ],
```
