### ISSUE TITLE
No hint path defined for [nova]

### ISSUE THREAD

**Issue by simonhamp** [laravel/nova-issues#2354]
- Laravel Version: 6.14.0
- Nova Version: 2.10.1
- PHP Version: 7.3.12
- Database Driver & Version: n/a
- Operating System and Version: macOS 10.14.6
- Browser type and version: n/a

### Description:
When trying to use the Nova layout (`vendor/laravel/nova/resources/views/layout.blade.php`) within a non-Nova view, I get this error.

### Steps To Reproduce:
`@extend('nova::layout')` from inside an app view e.g.`resources/views/test.blade.php`.

**Comment by jbrooksuk** [comment]
@simonhamp this is because the `ServeNova` middleware registers the service provider if the request is within the Nova endpoint (`/nova` for example).

You'll need to register the views manually in your `AppServiceProvider`:

```php
public function register()
{
    $this->loadViewsFrom(__DIR__.'/../resources/views', 'nova');
}
```

**Comment by cameron-elliott** [comment]
This issue saved my bacon! Thank goodness someone asked about it!

I did need this, rather than the path mentioned above: 
`$this->loadViewsFrom(__DIR__.'/../../nova/resources/views', 'nova');`

**Comment by georanma** [comment]
Had a similar issue after a deployment to my container based hosting company. Ended up being that I needed to run `php artisan clear-compiled` to resolve it.

**Comment by molbal** [comment]
> 
> 
> Had a similar issue after a deployment to my container based hosting company. Ended up being that I needed to run `php artisan clear-compiled` to resolve it.

Only this helped me. Thank you

**Comment by rossjcooper** [comment]
I also found that registering a Nova tool but not registering its service provider also caused a similar error

**Comment by nickbluestone98** [comment]
Running these two commands fixed the issue for me.

```
php artisan config:cache
php artisan route:cache
```
