### ISSUE TITLE
How can I remove(or hide) Show Icon of my related resource.

### ISSUE THREAD

**Issue by YarinceP** [laravel/nova-issues#2355]
I want to remove the view button from my related resource. I was reading the policies and did not find something related https://nova.laravel.com/docs/1.0/resources/authorization.html#relationships.
![Question Show button](https://user-images.githubusercontent.com/28911286/74551571-0d0db400-4f19-11ea-851e-6ad455e3af14.png)
Could you provide me with a solution for this?

**Comment by BenWalters** [comment]
@YarinceP I don't believe there is a way to hide the view icon. You can hide the record using policies but I don't think you can hide just the icon. 
What is the use case?

**Comment by jbrooksuk** [comment]
See https://nova.laravel.com/docs/2.0/resources/authorization.html#policies

**Comment by YarinceP** [comment]
@jbrooksuk did you read my issue?

I have a many-to-many relationship, and I am using a BelongsToMany field and I want to hide the view or show, edit and delete buttons.

I read the documentation and I don't see anything I'm looking for, which is simply hiding a button, in this case the view button or show button.

Here I show you what I found in the documentation:

attachModel - to hide the Edit button
detachModel -  This determines whether the "Detach" (rubbish bin) button is available for a particular record in the list.
attachAnyModel - This determines whether the "Attach Model" button appears at the top of the list.

but I don't see anything about the view button or show button.

Please could you help me?

**Comment by oleksandr-roskovynskyi** [comment]
> @jbrooksuk did you read my issue?
> 
> I have a many-to-many relationship, and I am using a BelongsToMany field and I want to hide the view or show button.
> 
> I read the documentation and I don't see anything I'm looking for, which is simply hiding a button, in this case the view button or show button.
> 
> Here I show you what I found in the documentation:
> 
> **attachModel** - to hide the Edit button
> **detachModel** - This determines whether the "Detach" (rubbish bin) button is available for a particular record in the list. (to hide the Delete button)
> **attachAnyModel** - This determines whether the "Attach Model" button appears at the top of the list.
> 
> but I don't see anything about the view button or show button.
> 
> Please could you help me?

public function view(Model $model) : bool
    {
        return false;
    }

**Comment by vesper8** [comment]
The above doesn't work

This actually does work:

```
    public function authorizedToView(Request $request)
    {
        return false;
    }
```
