### ISSUE TITLE
Add datalist (suggestions) option to Text field

### ISSUE THREAD

**Issue by adriaanzon** [laravel/nova-issues#2356]
The HTML spec has a native way to display suggestions, without any JavaScript: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist

It would be nice if Nova could leverage this. It might work something like this:

```php
Text::make('Ice Cream Flavour')
    ->suggestions([
        'Chocolate',
        'Coconut',
        'Mint',
        'Strawberry',
        'Vanilla',
    ])
```

Then, when any `suggestions` are present, it should make a `<datalist>` element in the form field containing the suggestions.

**Comment by jbrooksuk** [comment]
Presumably you're not using a `Select` field because they could add a new flavour?

**Comment by adriaanzon** [comment]
Indeed, users can input whatever they want. The datalist only adds suggestions.

**Comment by darkylmnx** [comment]
Any news on this? Is it in the current V3?

**Comment by davidhemphill** [comment]
This was added in 2.0.

**Comment by darkylmnx** [comment]
I do not see anything in the docs @davidhemphill but I indeed checked the source code and found the `->suggestions([])` method.
Thanks.

**Comment by davidhemphill** [comment]
I've added this to the docs. Thanks!
