### ISSUE TITLE
error with MorphTo field in related table

### ISSUE THREAD

**Issue by Pamposgsk** [laravel/nova-issues#2357]
![B3857939-CEEA-4154-96BF-E31F6097A8C8](https://user-images.githubusercontent.com/8403769/74683368-67389e80-51d1-11ea-89e7-40475a85697b.png)
![F4B1276F-8EC6-459C-9428-3744FEDE8BD2](https://user-images.githubusercontent.com/8403769/74683374-6bfd5280-51d1-11ea-9bff-eb86848ec921.png)
![408B7505-B61F-4C44-8F64-5025D1A6A665](https://user-images.githubusercontent.com/8403769/74683376-6ef84300-51d1-11ea-9e65-15b71daabd5a.png)
![ED5B2F02-A208-4979-99A7-21E47DBB412F](https://user-images.githubusercontent.com/8403769/74683380-70c20680-51d1-11ea-953c-62ba5b07376e.png)

When trying to update a form which contains MorphTo field from related resource the above error appears in the console.
Furthermore when trying to update ,the MorphTo field becomes empty and you need to fill it again.
Iam using the latest version of laravel nova and reproduce the error after fresh installation.
Are you aware about this issue?

**Comment by gnanakeethan** [comment]
I am facing the same issue at the moment.

**Comment by jnorms** [comment]
I have the same problem!

**Comment by pfried** [comment]
Since the edit action cannot be executed without reselecting the model this should be treated as a bug

**Comment by Pamposgsk** [comment]
Any update on this?
