### ISSUE TITLE
Request: A limit() or length() method to limit the column length in index view

### ISSUE THREAD

**Issue by ziming** [laravel/nova-issues#2359]
It will be great if something like this can be done:

```php
// If above 50 characters, truncate with ... in the index view
Text::make('Name')->limit(50),

// 123456789 becomes 12345...
Number::make('Random Num')->limit(5);
```

**Comment by jbrooksuk** [comment]
You can change how the value is displayed, like so:

```php
Text::make('Name')->displayUsing(function ($value) {
    return Str::truncate($value, 50);
});
```

**Comment by ziming** [comment]
I think just like nullable() or required() it will be a great convenience method to add. Since pretty much every column has a need to truncate

**Comment by LorenzoSapora** [comment]
Minor update to @jbrooksuk 's solution:

```php
Text::make('Name')->displayUsing(function ($value) {
    return Str::limit($value, 50);
})
```

(Laravel 8 doesn't have `Str::truncate()`, but `Str::limit` does the same job).

**Comment by jeff-h** [comment]
It would be great if this was implemented in CSS out-of-the-box in Nova. I personally would never want a table column with lots of content to extend full-width, thus pushing the rest of the table offscreen. And yet it appears that Nova hardcodes a "whitespace-no-wrap" class inside `TextField.vue`.

This is my second day with Nova so please excuse the ignorance :) but is there a neat way to add CSS classes using Nova's API somehow?

**Comment by shad0matic** [comment]
I found a workaround with extraattributes to force html maxlength :
Text::make( 'input1','col1')
                ->withMeta([
                    'extraAttributes' => [
                        'maxlength' => "9"
                    ]
                ])

**Comment by NessterGit** [comment]
> 

That's a clever idea. Though it doesn't seem to have any effect on the index page when I try it. Are you still using this with Nova 4 ?
