### ISSUE TITLE
Cannot update resource via Nova (page blocked by user)

### ISSUE THREAD

**Issue by apocalyarts** [laravel/nova-issues#236]
I'm currently making my first steps with Nova and I am trying to enhance the config for my User resource with avatars. When I wanted to test everything I ran into:

Another user has updated this resource since the page was loaded. Please refresh the page and try again.

Problem is: no matter how often I refresh, the error still occours. I tried to delete the session, manually changed the updated_at field of my model and ensured that the action_events table is empty, but still no luck. I always get this error.

**Comment by taylorotwell** [comment]
Since we can't recreate this, it is probably a system / server clock issue. Do you have a way to reliably recreate it on our end?
