### ISSUE TITLE
Method Laravel\Nova\Fields\Currency::format does not exist.

### ISSUE THREAD

**Issue by Stiropor** [laravel/nova-issues#2362]
- Laravel Version: 6.16.0
- Nova Version: 2.11.1
- PHP Version: 7.3.9

With last update Nova starts reporting:
`Method Laravel\Nova\Fields\Currency::format does not exist.`

Code is pretty simple:
`Currency::make('Price discount, 'price_discount')->format('%.2n%%')`

**Comment by jbrooksuk** [comment]
There is no `format` method on the `Currency` field from v2.11 - I need to update the docs on this. Bear with :)

**Comment by Stiropor** [comment]
> There is no `format` method on the `Currency` field from v2.11 - I need to update the docs on this. Bear with :)

Thank you for quick reply :) How can we format currency now?

**Comment by jbrooksuk** [comment]
I've updated the documentation. You should use the `locale` method.
