### ISSUE TITLE
Global search field empties when jumping between tabs

### ISSUE THREAD

**Issue by simonhamp** [laravel/nova-issues#2363]
- Laravel Version: 6.14.0
- Nova Version: 2.10.1
- PHP Version: 7.3
- Browser type and version: Chrome 79

### Description:
Global search field doesn't retain its contents when jumping between tabs. This is unexpected behaviour. Not strictly a bug, so kinda low priority.

Note that this behaviour is different for the per-resource search field which does not empty when switching between tabs.

### Steps To Reproduce:
1. Enter some text in the global search field
2. Switch to another browser tab
3. Switch back to the Nova tab
4. See text disappear and search ruined

**Comment by jbrooksuk** [comment]
> Note that this behaviour is different for the per-resource search field which does not empty when switching between tabs.

@simonhamp this isn't the case for me. When I switch tabs, the per-resource search is emptied.

**Comment by simonhamp** [comment]
Definitely inconsistent behaviour... if I tab out of the global search field before switching to another tab, when I tab back, the search stays in place.

The resource-level search behaves exactly as I'd expect.
![Global search emptying](https://user-images.githubusercontent.com/31628/74947903-7434d800-53f3-11ea-91f6-4b292481d09e.gif)

**Comment by jbrooksuk** [comment]
@simonhamp sorry, I just realised what meant. Browser tabs!

**Comment by jbrooksuk** [comment]
This is the correct behaviour. When leaving the field, it's emptied.

**Comment by simonhamp** [comment]
Sorry for not being clear about browser tabs.

I’m just curious as to why the two fields behave differently and if it’s possible to have the global search behave more like the resource index search.

Sometimes it’s nice to be able to flip between tabs knowing that the state of the page remains the same, i.e. in this case, the field still populated and the results list remaining open.
