### ISSUE TITLE
New Release Email Notification

### ISSUE THREAD

**Issue by davi5e** [laravel/nova-issues#2368]
I just spent an hour trying to figure out a solution to a problem that a newer version of Laravel Nova solves. This would never have happened if I knew in advance there were updates available...

Since it's not practical to keep going to the [releases page](https://nova.laravel.com/releases) every once in a while, I think a notification could help inform everyone and possibly avoid these kinds of problems...

Anyhow, alternative solutions are welcomed too!

**Comment by demency** [comment]
Check the nova repository to get wip changes. 👍

**Comment by jbrooksuk** [comment]
You can run `composer update` to check for updates and also the releases page. Recently we’ve been releasing every other Tuesday, with some patch releases if needed, so there has been some schedule to this. 

If you need something more, you could install https://novapackages.com/packages/skydiver/nova-update-card which sits in Nova itself.
