### ISSUE TITLE
Class 'Symfony\\Component\\Intl\\Currencies' not found

### ISSUE THREAD

**Issue by hotmeteor** [laravel/nova-issues#2369]
- Laravel Version: 5.8.37
- Nova Version: 2.11.1
- PHP Version: 7.2.22
- Database Driver & Version: Postgres 9.6
- Operating System and Version: macOS 10.14.6
- Browser type and version: Firefox 72.0.2
- Reproduction Repository: https://github.com/###/###

### Description:

I've just installed Nova 2.11.1 and now receiving this error when I log in:
```php
Class 'Symfony\\Component\\Intl\\Currencies' not found
```
Appears related to the changes to the `Currency` field, in particular:
```php
/Users/Adam/Web/spur/laravel/nova/src/Fields/Currency.php(143): Laravel\\Nova\\Fields\\Currency->resolveCurrencySymbol()
```

### Steps To Reproduce:

1. Install Nova 2.11.1
2. Log in
3. See error.

**Comment by demency** [comment]
Probably you dont hace symfony installed, maybe related required laravel compatible version.
Check your composer lock and share your symfony packages installed. 👍

**Comment by hotmeteor** [comment]
@demency Ya, that's clearly the issue. But shouldn't I be able to install the latest version of Nova and get all dependencies required?

**Comment by jbrooksuk** [comment]
[`symfony/intl`](https://github.com/laravel/nova/blob/ca9dc74b7f131ba4689ba1d09a7c112afe66cce3/composer.json#L24) is required in the `composer.json` file though...

**Comment by demency** [comment]
> @demency Ya, that's clearly the issue. But shouldn't I be able to install the latest version of Nova and get all dependencies required?

You are right 👈

**Comment by hotmeteor** [comment]
Ya, guys, I did that. Followed all the [upgrade instructions](https://nova.laravel.com/docs/2.0/installation.html#updating-nova) numerous times in two separate environments, and it never installed. I'm upgrading from v 2.0.10.

But ok, closed.

**Comment by preliot** [comment]
Similar issue here and a simple solution. Forgot to run the `composer update` command **after** downloading the zip file.

**Comment by remxcode** [comment]
Similar issue here and a simple solution. Though I have run the `composer update` command after downloading the zip file, the issue remain. Finally, after deleted composer.lock file, then run `composer install` command, the package successful installed.
