### ISSUE TITLE
[Feature] Ability to horizontally stack fields.

### ISSUE THREAD

**Issue by hailwood** [laravel/nova-issues#237]
Right now the detail screens can get huge if you have a lot of fields, panels go a short way to helping this, but if you have several fields that you know are going to be short it feels like a real waste of space to not be able to say "I want this field to be 1/3 the width" and stack three across.

Our clients feel the same way which means for us a Nova license isn't usable.

**Comment by taylorotwell** [comment]
This repository is for tracking bugs. Feature requests may be emailed to Nova customer support.
