### ISSUE TITLE
Nova Field Value Not Showing, When the Value Exists in the Database

### ISSUE THREAD

**Issue by Enijar** [laravel/nova-issues#2371]
- Laravel Version: ^6.2
- Nova Version: dev-master
- PHP Version: 7.2.26
- Database Driver & Version: MySQL 5.7.29 (utf8mb4 encoding)
- Operating System and Version: macOS Mojave (10.14.6)
- Browser type and version: Google Chrome 80.0.3987.106
- Reproduction Repository: I can't share my code

### Description:
My project has several fields defined for an `Entry` model in Nova, which looks like this:

```php
class Entry extends Resource
{
    public static $model = 'App\ED\Entities\Entry';

    public static $title = 'email';

    public function fields(Request $request): array
    {
        return [
            'file' => Image::make('file')->readonly(true)->preview(function (string $url) {
                return str_replace(env('APP_URL'), '', $url);
            })->hideFromIndex(),
            'firstName' => Text::make('First Name')->readonly(true),
            'email' => Text::make('Email Address')->readonly(true),
            // etc.
        ];
    }
}
```

All data shows except the `firstName` field. When I rename both the `firstName` field in the database and the fields array key `first_name` the value shows. I'm pretty confident this is a bug with Nova specifically, but I've not been able to look into this too deeply as of yet. Doing a call through Eloquent and dumping out the data also shows the correct key and value for `firstName`, so I think the issue lies within Nova.

### Steps To Reproduce:

Setup a MySQL database:

```sql
CREATE TABLE `entries` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `file` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL,
  `firstName` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

Define an `Entry` model:

```php
class Entry extends Model
{
    public $fillable = [
        'file',
        'firstName',
        'email',
    ];
}
```

Define an `Entry` Nova field (see description above).

**Comment by jbrooksuk** [comment]
You're defining your fields incorrectly, you do not need to return a key/value pair. https://nova.laravel.com/docs/2.0/resources/fields.html#defining-fields

**Comment by Enijar** [comment]
@jbrooksuk it's the same issue without key => value pairs. Just defining an array like this, still does not show values for database columns named with `camelCase`:

```php
class Entry extends Resource
{
    public static $model = 'App\ED\Entities\Entry';

    public static $title = 'email';

    public function fields(Request $request): array
    {
        return [
            Image::make('file')->readonly(true)->preview(function (string $url) {
                return str_replace(env('APP_URL'), '', $url);
            })->hideFromIndex(),
            Text::make('firstName')->readonly(true),
            Text::make('email')->readonly(true),
            // etc.
        ];
    }
}
```

**Comment by jbrooksuk** [comment]
Try:

```php
Text::make('First Name', 'firstName')->readonly(true),
```

Nova uses Laravel's default snake case.

**Comment by LibertiMarco** [comment]
@jbrooksuk Ha funzionato, grazie mille!
