### ISSUE TITLE
How to disable the default dashboard?

### ISSUE THREAD

**Issue by milewski** [laravel/nova-issues#2374]
Hi, is there any way to completely disable the default dashboard in Nova?

Currently, I hacked it around by unsetting it from `Nova::$tools` but I still get redirected to `/dashboards/main` right after login

```php
foreach (Nova::$tools as $index => $tool) {

    if ($tool instanceof Dashboard) {

        unset(Nova::$tools[ $index ]);

    }

}
```

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by vesper8** [comment]
@milewski did you ever figure it out?

I'm surprised there isn't an easy way to change the default landing route

**Comment by milewski** [comment]
@vesper8 no there is no way to disable.. the hack solution I found was making a card.. and setting it as the only card on the main dashboard wish the only purpose was to redirect to the page I want as soon as it loads..

**Comment by LoganTFox** [comment]
You can switch the `redirectPath` method in the nova `LoginController` to redirect to a custom page.

**Comment by stephan-v** [comment]
So where are people suppose to post their feature requests if not here? This seems like one of the first things you would want to do.

**Comment by vesper8** [comment]
@stephan-v this is the place to post them, but they get closed almost immediately as per their policy, that doesn't mean they won't consider filling them

**Comment by aurawindsurfing** [comment]
@davidhemphill this redirect should be included. I appreciate you marking it as a request. I love nova but this is a bit annoying. We pay for it. We would like to have this feature added to future release, thank you.
