### ISSUE TITLE
Image field: cannot delete or update image anymore

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#2375]
- Laravel Version: 5.8.37
- Nova Version: 2.11.1
- PHP Version: 7.2.19
- Operating System and Version: Windows 10 
- Browser type and version: Chrome 79 64-bits

### Description:

Although this used to work, now i am unable to delete or upload an image with the image field. I get errors in my browser console only:

Delete image:  <MY_URL>/nova-api/client-shops/20/field/image 404 (Not Found)

Upload image: POST <MY_URL>/nova-api/client-shops/20?viaResource=&viaResourceId=&viaRelationship=&editing=true&editMode=update 422 (Unprocessable Entity)

(Note i've replaced by url with <MY_URL>)

### Recreate issue

1. config/filesystems.php
```php
  'disks' => [
        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL') . '/storage',
            'visibility' => 'public',
        ],
```
1. php artisan storage:link
2. create nova resource with Image field

```php
 Fields\Image::make(ucfirst(__('my-image')), 'image')
            ->disk('public');
```
### Already tried

1. Delete and recreate symlink
2. Check filepath
3. Debug. When i delete an image, line 28 of `Laravel\Nova\Http\Controllers\FieldDestroyController.php
` aborts my attempt:

```php
//my delete attempt will end in the abort(404)
$field = $resource->updateFields($request)
                    ->whereInstanceOf(File::class)
                    ->findFieldByAttribute($request->field, function () {
                        abort(404);
                    });
```

**Comment by cgarofalo** [comment]
I have a similar issue where I cannot update/delete images with the Nova images field.
Laravel 5.8.36
Nova 2.9.4
PHP 7.2.16

**Comment by davidhemphill** [comment]
I was not able to reproduce this using your setup on a fresh Nova instance. Image uploading and deletion seems to be working normally. If you can find a way to reproduce this using a fresh Nova install in a fresh Laravel app, please open a new issue. Thanks!

**Comment by preliot** [comment]
Issue was due to package Eminiarts\Tabs\TabsOnEdit.
Similar to issue https://github.com/eminiarts/nova-tabs/issues/28

**Comment by AlexAzartsev** [comment]
is any way to fix this and keep nova-tabs?
