### ISSUE TITLE
Upgrade Tailwind

### ISSUE THREAD

**Issue by elvis888** [laravel/nova-issues#2377]
Hi, pls update tailwindcss to v1.2.0, thanks

**Comment by pzmarzly** [comment]
The copy of Tailwind that's included in Nova is not a full Tailwind anyway (it has many configuration flags disabled). But you can load a second copy of it. Here's how I do it:

```js
// webpack.mix.js
const mix = require('laravel-mix');
const tailwindcss = require('tailwindcss');

mix
    .setPublicPath('public')
    .sass('resources/sass/app.scss', 'css')
    .sass('resources/sass/preflight.scss', 'css')
    .options({
        processCssUrls: false,
        postCss: [tailwindcss('./tailwind.config.js')],
    })
    .disableNotifications();
```

```scss
// resources/sass/preflight.scss
@tailwind base;
```

```scss
// resources/sass/app.scss
@tailwind components;
@tailwind utilities;
// and all the other styles
```

```php
// NovaServiceProvider.php
// ...

class NovaServiceProvider extends NovaApplicationServiceProvider
{
    // ...
    
    public function boot()
    {

        Nova::serving(function (ServingNova $event) {
            Nova::style('app', __DIR__ . '/../../../public/css/app.css'); // you may need to change the number of dots here
        });

        parent::boot();
    }
    
    // ...
}
```

Using preflight will break Nova styles, but you probably want to use it on your non-Nova pages, like so:

```php
<link rel="stylesheet" href="{{ mix('/css/preflight.css') }}">
<link rel="stylesheet" href="{{ mix('/css/app.css') }}">
````

You can hit weird issues, like https://github.com/gregoriohc/laravel-nova-theme-responsive/pull/23

**Comment by davidhemphill** [comment]
Tailwind CSS is designed to be *customized* for your specific applications.

At any rate, the next series of Nova will probably use stock Tailwind CSS since it seems to bother so many people.

In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by mucyomiller** [comment]
> Tailwind CSS is designed to be _customized_ for your specific applications.
> 
> At any rate, the next series of Nova will probably use stock Tailwind CSS since it seems to bother so many people.
> 
> In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

That would be nicer! :+1:
