### ISSUE TITLE
Request: Fields\MorphTo method withoutTrashed()

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#2378]
I'm really glad with the BelongsTo method withoutTrashed(). It would be nice if this is also available on Fields\MorphTo.

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
