### ISSUE TITLE
Allow ActionEvent to be overrided via nova.php config file 

### ISSUE THREAD

**Issue by bkintanar** [laravel/nova-issues#2379]
- Laravel Version: 6.16.0
- Nova Version: 2.11.1
- PHP Version: 7.4.1
- Database Driver & Version: mysql 5.7.28
- Operating System and Version: Ubuntu 18.04.3 (homestead)
- Browser type and version: Google Chrome 79.0.3945.130

### Description:

Currently ResourceDestroyController is using DB::table('action_events') in lines 34-37.

```php
DB::table('action_events')->insert(
    Nova::actionEvent()->forResourceDelete($request->user(), collect([$model]))
                ->map->getAttributes()->all()
);
```

Can we allow this model to be overrided the same way as the Action Resource via the nova.php config file so that we can change the database connection?

**Comment by davidhemphill** [comment]
Specify a custom `ActionResource` class which has your custom `ActionEvent` in it's `model` property.

**Comment by bkintanar** [comment]
@davidhemphill that's what I did. but since it is calling the DB::table('action_events'). it is by passing the model set in the custom `ActionResource`.

**Comment by bkintanar** [comment]
@davidhemphill can we reopen this issue?

**Comment by bkintanar** [comment]
@davidhemphill 

Thank you for adding this in v2.12.0.

**Comment by vegadvarsha30** [comment]
There are still reference to "action_events" table directly in few places, for example:

1. LensResourceDestroyController.handle method
2. LensResourceForceDeleteController.handle method
3. ResourceDestroyController.handle method
4. ResourceDetachController.handle method
5. ResourceForceDeleteController.handle method
6. ResourceRestoreController.handle method

Can we fix these references?

**Comment by crynobone** [comment]
@vegadvarsha30 can you create a new bug report with why you need it/your use case.
