### ISSUE TITLE
No nova routes - /nova => page not found

### ISSUE THREAD

**Issue by lfleigl** [laravel/nova-issues#238]
Hi.

I played around with nova on a new app on Friday (1.0.3) and all "issues are fine and had resolved quickley".

So, I started to integrate Nova in my existing project with 1.0.6 and the nova-route doesn't exist 
=> nova.api.* exist, but normally nova.* has to be there, too. I use Passport in my project, and install Passport to the test-app, too - that is still working. I cleared the routes and updated composer, publish nova, ...

(compare routes: only nova.api. and both: nova.api.* + nova.* )
![bildschirmfoto 2018-08-27 um 10 49 18](https://user-images.githubusercontent.com/1787705/44651292-3bc46180-a9e9-11e8-99c0-3e9f49d0d492.png)
![bildschirmfoto 2018-08-27 um 10 49 04](https://user-images.githubusercontent.com/1787705/44651293-3bc46180-a9e9-11e8-9594-b00e3c89381d.png)

**Comment by Jam0r85** [comment]
Have you run

`php artisan route:clear`

?

**Comment by lfleigl** [comment]
Hi James.


yes - so many times - but this time is works. very strange. Maybe some cache? But I cleared all things many times.



[cid:7052df4c-f812-4dae-ac6e-6193901486aa].

[cid:51f92c84-7796-41c8-a1c0-e5a51c0406f1]

Lars Fleigl


[cid:SI_Logo_1zlg_B200px_27743731-5bc2-4fb9-bc9b-47c5a62139bb.png]

Sport Import GmbH | Industriestraße 39, D-26188 Edewecht
GF: Michael Müllmann, Alexander Müllmann, Ralf Fischer
Amtsgericht Oldenburg, HRB 120290

Tel: +49 (0)4405 928092
Mob:
Fax: +49 (0)4405 928051
www.sportimport.de<http://www.sportimport.de>

Unsere Hinweise zum Datenschutz findest Du hier:
Datenschutzhinweise<https://www.sportimport.de/datenschutzgrundsaetze/>



________________________________
Von: James Morris <notifications@github.com>
Gesendet: Montag, 27. August 2018 11:42:24
An: laravel/nova-issues
Cc: Lars Fleigl; Author
Betreff: Re: [laravel/nova-issues] No nova routes - /nova => page not found (#238)


Have you run

php artisan route:clear

?

**Comment by lfleigl** [comment]
`php artisan route:clear`

**Comment by Jam0r85** [comment]
I deleted my comment as I re-read your post and saw that you had already tried that!

Glad it's now working.

**Comment by o7n** [comment]
FWIW `php artisan route:clear` didn't fix this for me, `php artisan config:cache` did...

**Comment by bretto36** [comment]
I'm getting this same issue but route clear and config clear didn't change anything. I get the api routes but no standard routes

**Comment by franzdumfart** [comment]
Have the same problem. Route clear and config clear not fixing the problem. The /nova url isn't working. Getting a 404.

**Comment by robertotcestari** [comment]
Same here. Route clear and config clear not working.

**Comment by bretto36** [comment]
Hey guys I fixed it on mine by manually adding the nova service provider to the config/app.php.

On 5 Sep 2018, at 3:14 am, Franz Dumfart <notifications@github.com<mailto:notifications@github.com>> wrote:


Have the same problem. Route clear and config clear not fixing the problem. The /nova url isn't working. Getting a 404.

**Comment by monaye** [comment]
I was able to fix with `php artisan route:clear` not with `php artisan config:cache`

**Comment by janbager** [comment]
i have the same issue on a new laravel 5.7 app using homestead. Installation is fine, ServiceProvider is registered but calling /nova leads to an error 404 ... any ideas

**Comment by pnj131** [comment]
I solved out this issue easily,,
add on app/config file..
 App\Providers\NovaServiceProvider::class,

**Comment by huenisys** [comment]
Same thing as mine. I don't remember myself adding ``App\Providers\NovaServiceProvider::class,`` last time. I thought this is package discoverable. I checked my other installation and clearly, there's NovaServiceProvider in the config.

So just do the same and clear caches.

**Comment by saulomatias** [comment]
`App\Providers\NovaServiceProvider::class,` worked for me!

**Comment by borealsmith** [comment]
hi @saulomatias ,

did you found a fix  ? I have the exact same issue. Cheers

**Comment by bhensonweb** [comment]
I had forgotten to run

`php artisan nova:install`

**Comment by jigarakatidus** [comment]
All above solutions are valid, if you are still facing issue then its web server issue.

For apache:
- Make sure mod_rewrite is enabled.
- Your apache should be able to read .htaccess. 
  - For that, make sure for your in your Directory, AllowOverride should not be "None". Value "All" is safe for local.
