### ISSUE TITLE
Policy issue, when 2 Nova resources have the same name, the policy does not work.

### ISSUE THREAD

**Issue by nickkuijpers** [laravel/nova-issues#2380]
Issue is solved, but it might be interesting for someone else.

- Laravel Version: 6.16.0
- Nova Version: 2.11.1
- PHP Version: 7.4.1
- Reproduction Repository: https://github.com/###/###

### Description:
The structure of our code is as follows:

- Nova
-- Managers
--- Posts.php ( namespace: Nova\Managers\Posts)
-- Users
--- Posts.php ( namespace: Nova\Users\Posts)
- Models
-- Managers
--- Posts.php ( namespace: Models\Managers\Posts)
-- Users 
--- Posts.php ( namespace: Models\Managers\Posts)
- Policy
-- Managers
--- PostsPolicy.php ( namespace: Policies\Managers\Posts)
-- Users 
--- PostsPolicy.php ( namespace: Policies\Users\Posts)

Then in the boot function of the nova tool, the follows. Keep in mind, our structure allows a user entity, to take position in 2 roles. The default user showing his Posts, and the manager role where he sees all the posts of all the users because he is the manager.

```php
Gate::policy('Niku\Gps\Models\Users\Post', 'Niku\Gps\Policies\Users\PostPolicy');
Gate::policy('Niku\Gps\Models\Managers\Post', 'Niku\Gps\Policies\Managers\PostPoliciy');

Nova::resources([                
         ...\Nova\Users\Posts::class,           
]);

$isManager = request()->user()->hasPermission('is_manager');
if($isManager == true){
            Nova::resources([                
                   ...\Nova\Managers\Posts::class,           
            ]);
}
```

You have have a structure as above, the policy does not work. It will take the policy rules of the first registered item.

I have tried a combination of things and i found the issue to be in the name of the Nova resource. So if i change the above to this below, it will work. I have changed the Nova resource name to a unique value.

```php
- Nova
-- Managers
--- **ManagersPosts.php** ( namespace: Nova\Managers\**ManagersPosts**)
-- Users
--- **UsersPosts.php** ( namespace: Nova\Users\**UsersPosts**)
- Models
-- Managers
--- Posts.php ( namespace: Models\Managers\Posts)
-- Users 
--- Posts.php ( namespace: Models\Managers\Posts)
- Policy
-- Managers
--- PostsPolicy.php ( namespace: Policies\Managers\Posts)
-- Users 
--- PostsPolicy.php ( namespace: Policies\Users\Posts)
```

```php
Gate::policy('Niku\Gps\Models\Users\Post', 'Niku\Gps\Policies\Users\PostPolicy');
Gate::policy('Niku\Gps\Models\Managers\Post', 'Niku\Gps\Policies\Managers\PostPoliciy');

Nova::resources([                
         ...\Nova\Users\**UsersPosts::class**,           
]);

$isManager = request()->user()->hasPermission('is_manager');
if($isManager == true){
            Nova::resources([                
                   ...\Nova\Managers\**ManagersPosts::class**,           
            ]);
}
```

I don't like the structure as it repeats its name in all the files, while i have been writing this issue i found out that i missed a part of my code which solved another issue, which is duplicated Nova resource names to allow multi role access to the same Nova resource. I had to make the Nova resource unique by setting the following in the Nova resource class.

Nova\Managers\**Posts**:

```php
public static function uriKey()
{
    return 'managers-posts';
}
```

Nova\Users\**Posts**:

```php
public static function uriKey()
{
    return 'users-posts';
}
```

**Comment by jmverges** [comment]
I would say still is an issue. 
Why policy needs to be based in uriKey? 
I have other scenario where I need to use the same uriKey for different models because I need different policies for each model and those models are at the end the same model but in different relationship

**Comment by nickkuijpers** [comment]
Hi,

I think its not the policy we are passing but a unique identifier for the Nova resource. If you add:

```php
public static function uriKey()
{
    return 'users-posts';
}
```

to the Nova resource, you can open that in the url by doing this:

https://test.test/admin/resources/users-posts

So, the URL is the return value of the uriKey function.

If you dont do that, and the Nova resource is not unique, it cannot find the 'real' Nova resource as the URL resource identifier (https://test.test/admin/resources/***users-posts***) is the identifier which gets searched in a key value array. If you have multiple identifiers with the same name, it just returns the first one it finds and that model is the active one.

**Comment by jmverges** [comment]
Hi, 

I don't explain myself okey. I need to do a redirect from one fake model (just done for Policies in a Relation) to the real model when user clicks View in the table row.  This works okey if I put the same uriKey in the fake model (Duplicated Account) that in the real model (Account). However, as soon as I change the uriKey, the DuplicatedAccountPolicy, stops working.

**Comment by nickkuijpers** [comment]
Hmm, i don't really understand the issue, i am sorry. Could you maybe share some code?

**Comment by nenads** [comment]
@jmverges 

Can you confirm the issue

let's say there are two resources

App\Nova\User
App\Nova\Admin\User

with correct name space. for this to work you have setup key for admin to be /admin-users (for example)

now if you create two policy

App\Policy\UserPolicy
App\Policy\Admin\UserPolicy

issue accrues. all imports are correct.

it seems that gate resolver is not respecting name space.

**Comment by nenads** [comment]
It seems there is magic now

if you have model user and UserPolicy it try magicly to load and do injection.

rename policy to be ugly App\Policy\Admin\User

add it to 'App\Models\Admin\User' => 'App\Policies\Admin\User',

and it works.

Don't have time to go in details.

But issue is:

1. Two Resources with same name (namespaced)
2. Two policy respecting structure -> ModelPolicy in same structured  namespace

Gate injection fails.

**Comment by crynobone** [comment]
This issue has been closed by the author, if everyone else have similar issue please create a new issue will full details and reproducing steps.
