### ISSUE TITLE
Add an option to BooleanGroups to hide false items

### ISSUE THREAD

**Issue by Grayda** [laravel/nova-issues#2381]
I like the BooleanGroup field and I love the popup when you click View on the index page, but if I've got a bunch of options, it gets messy after a while.

It'd be nice to have an option to only show selected items on the Index or Detail page.

Something like `BooleanGroup::make('Features')->options([ /* ... */])->hideFalseOnIndex()` so I'd go from this:

![image](https://user-images.githubusercontent.com/4891563/75101276-438cb280-562e-11ea-890a-579e3b668340.png)

to this:

![image](https://user-images.githubusercontent.com/4891563/75101280-599a7300-562e-11ea-89df-f8f65f105639.png)

EDIT: Having a `hideTrueOnIndex()` would be good too, if you want to create a checklist-style field where you tick off completed items.

**Comment by davidhemphill** [comment]
I like it. @jbrooksuk 
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by jbrooksuk** [comment]
PR opened!

**Comment by issour** [comment]
When you have one checked boolean in BooleanGroups it's preferable to show it directly in index view without necessary clicking in VIEW link.
UI more intuitive.
Many Thx !!
