### ISSUE TITLE
custom filter reset filters

### ISSUE THREAD

**Issue by halah-m** [laravel/nova-issues#2384]
- Laravel Version: 5.8.37
- Nova Version: 2.11.1
- PHP Version: 7.3.9

### Description:

I created a custom filter using `vue-multiselect` component, and everything is working great, but when I click reset filters it reset the index page data, but the filter component still has the selected values.

**Comment by davidhemphill** [comment]
Your filter's state must be managed correctly using Nova's Vuex store as filter resetting is handled automatically by Nova. If you can provide an example that reliably breaks, feel free to open a new issue. Right now there's no information we could even try to debug your issue with.
