### ISSUE TITLE
When a resource is readonly, remove entire select column.

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#2386]
When a resource is readonly, the checkboxes disappear. However there is still an empty table cell in the first row. In my opnion this looks weird and is unwanted.

**Comment by preliot** [comment]
@davidhemphill Fixed? Ignored?

**Comment by jbrooksuk** [comment]
Merged.

**Comment by preliot** [comment]
Still there:

Resource with checkboxes:
![image](https://user-images.githubusercontent.com/5418196/82529698-e379af80-9b3b-11ea-8ae5-bce23f8a79c4.png)

Readonly resource:
![image](https://user-images.githubusercontent.com/5418196/82529790-0d32d680-9b3c-11ea-829c-d033fca0b486.png)

Note there's still an empty cell.
