### ISSUE TITLE
“Create and Add Another” Button Won’t Show

### ISSUE THREAD

**Issue by vincenzoraco** [laravel/nova-issues#2388]
- Laravel Version: 6.15.0
- Nova Version: 2.11.1
- PHP Version: 7.4.0

### Description:
I cannot see the Create and Add Another button on HasMany relationship creation. 

### Steps To Reproduce:
Create a model/resource that has an HasMany relationship, then try to create a child. The button won’t show.

**Comment by BenWalters** [comment]
@vincenzoraco I cannot recreate this.
![image](https://user-images.githubusercontent.com/43746367/75171609-ce030e00-5723-11ea-9b9f-f340f4b2e8cc.png)

![image](https://user-images.githubusercontent.com/43746367/75171639-dd825700-5723-11ea-8408-97681f821184.png)

**Comment by lab08tonci** [comment]
Same problem here.

**Comment by Stickmanv1** [comment]
Same problem but Why it is Closed?

**Comment by jbrooksuk** [comment]
Because it got fixed in a PR.

**Comment by ginlove0** [comment]
From version 2.12.0 nova will disable this button. However, anyone have an idea to bring it back???
