### ISSUE TITLE
Global search fails on resource with attribute accessor

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#2389]
- Laravel Version: 5.8.37
- Nova Version: 2.11.1
- PHP Version: 7.2.19
- Operating System and Version: Windows 10 
- Browser type and version: Chrome 79 64-bits

### Description:

I've got a resource 'Wearer' with a UserName attribute, which is retrieved from the User table. When i try to search on this attribute, i get an error.

### Steps To Reproduce:

- Create a model 'Wearer'
- Create a attribute accessor on this model, example:

```php
    public function getUserNameAttribute(): ?string
    {
        $user = $this->user()->first();
        return $user ? $user->name : null;
    }
```
- Add 'UserName' to Wearer Nova Resource $search

```php
 /**
     * The columns that should be searched.
     * @var array
     */
    public static $search = ['UserName'];
```

- Try to do a search on a name
- See this error:

```php
message: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'wearers.UserName' in 'where clause' (SQL: select * from `wearers` where ((`wearers`.`UserName` like %Taylor%)) and `wearers`.`deleted_at` is null and `client_id` = 9 order by `wearers`.`id` desc limit 5)
```

**Comment by jbrooksuk** [comment]
This isn't an issue because accessors are not searchable by Nova, by default. If you need your accessors to be searchable, you should look at using Laravel Scout with Nova.

**Comment by preliot** [comment]
For anyone with the same issue: If your accesor is getting something from another related table, an alternative is this package: https://github.com/TitasGailius/nova-search-relations

Now you can find your user name:

```php
public static $searchRelations = [
        'users' => ['name'],
    ];`
