### ISSUE TITLE
Not showing Actions in List view

### ISSUE THREAD

**Issue by Krato** [laravel/nova-issues#239]
Hello, I don't know why but I'm not able to see the Actions dropdown in the List View. Only in Details view.

A friend sends me their test suit. He is able to see, not in my computer.

I've seen the api call to actions and the console shows the enabled actions, but not showing in List view.

![captura de pantalla 2018-08-27 a las 10 14 52](https://user-images.githubusercontent.com/74367/44652157-1b91a400-a9e3-11e8-8e8a-037b3f33130a.jpg)

Why?

**Comment by GuidoHendriks** [comment]
Only appears when you select a row.

**Comment by liampmccabe** [comment]
Perhaps an inactive state that has a reduced opacity & pointer events set to none as well a possible tooltip informing the user to check a row might be clearer?
