### ISSUE TITLE
Sometimes env() fails in displaysUsing

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#2390]
Laravel Version: 5.8.37
Nova Version: 2.11.1
PHP Version: 7.2.19
Operating System and Version: Windows 10
Browser type and version: Chrome 79 64-bits

**Description**

I've got a field that shows an url based on a slug saved in de database. This slug is combined with a fixed variable from .env file to create a full url. 

Sometimes, and i can't seem to pinpoint when, the env() function returns null and the url doens't work. It happened to me when i saved a resource, just loaded the detail page and also on the index page. I don't understand how it happens, but it does happen to often. I've seen this issue for some months now (dev enviroment).

**Recreate issue**

1. Create a env variable like APP_DOMAIN='my-application.com'
2. Create a resource and a field like so:

```php   

  $fieldsGeneric[] = Fields\Text::make(ucfirst(__('webshopURL')), 'webshopSlug')
            ->sortable()
            ->displayUsing(function ($slug) {
                $url =  $slug . env('APP_DOMAIN');
                 return URL::html($url);
            })
            ->asHtml()
            ->exceptOnForms();
```

3. F5 allot, login / logout. Not sure why / when the issue is caused.
4. When it fails the url just shows the wrong url (because of the missing env() variable.

**Comment by jbrooksuk** [comment]
You should never use `env` outside of the configuration files as these values are not cached. You should use `config()`.

**Comment by preliot** [comment]
Thanks for the pointer, i will change this and see what happens.

After your comment i've read https://laravel.com/docs/5.8/configuration#configuration-caching . This suggests that returning null (always) happens when config:cache is used. In my case i did not use config:cache and null is only sometimes returned.
