### ISSUE TITLE
MorphTo is Too Slow to Load Relationship

### ISSUE THREAD

**Issue by vincenzoraco** [laravel/nova-issues#2391]
- Laravel Version: 6.16.0
- Nova Version: 2.11.1
- PHP Version: 7.4.0
- Database Driver & Version: Mysql 8.0.17

### Description:
The MorphTo field won't load the relationship if too many records are stored.

### Steps To Reproduce:
When using MorphTo like so:

```php
MorphTo::make('Resource', 'communicationable')->types([
    Customer::class,
])->readonly()->nullable(),
```

The frontend will hit this route `https://project.test/nova-api/communications/morphable/communicationable?type=customers&current=62874&first=false&search=&withTrashed=false&viaResource=customers&viaResourceId=62874&viaRelationship=communications` and it will not load the relationship.

i've noticed that if I use the `->searchable()`  method, it will load very fast. Unfortunately, if I use it with the `->readonly()` method, it won't show the filed at all.

Can you please look into this or at least make that `->searchable()->readonly()` can work together?

**Comment by jbrooksuk** [comment]
When you don't use `searchable`, every option has to be loaded into the view which will undoubtedly be slow when you have lots of options available.

I shall investigate `readonly` not working with `searchable`.

**Comment by jbrooksuk** [comment]
Actually, why would you use `readonly` on a `MorphTo` field?

**Comment by ZoreAnkit** [comment]
This issue still persists. Slow loading causes issues when we try to save the form as the field is not loaded users get errors. Please fix this issue.
