### ISSUE TITLE
Possible Bug | Text Resource $attribute value conflicting with Model Relation Function name

### ISSUE THREAD

**Issue by nikhilbaby2000** [laravel/nova-issues#2392]
**Reminder: Only a Possible Bug**

- Laravel Version: 6.15.0
- Nova Version: 2.10.1
- PHP Version: 7.2.26
- Database Driver & Version: MySQL v5.6
- Operating System and Version: Cent OS 7.4.1708
- Browser type and version: Google Chrome 78.0.3904.70

### Description:
Nova Text Field `$attribute` field value conflicting with Model Relationship function name.

### Steps To Reproduce:
Create Model: `Car`
Add Model Relation: `build()`

Create Resource: `Car`
Create Text Resource: `Text::make('Build', 'build')`

Try to load the Create new Car resource page.
The Page hangs without reporting the error.

--- Its only a possible bug. We faced the issue because the developer wrongly added the Model Relationship function - `build()` - in the model. This function was not needed. However this brought a possible situation to light.

In Nova, for Fields like `BelongsTo`, `HasOne` or any other relationship fields expects the 2nd argument - `$attribute` - to be a defined Model Relation function name.
I wish if other Nova Fields like `Text`, `Select` could make an exception & not check if `$attribute` value is a Model Relation function or not OR throw an execution error.

Thanks!

**Comment by jbrooksuk** [comment]
It's considered bad practise to create a relationship with the same name as an attribute. This isn't a bug :)
