### ISSUE TITLE
searching belongs to relation error: Maximum execution time of 60 seconds

### ISSUE THREAD

**Issue by davidgabbay** [laravel/nova-issues#2394]
- Laravel Version: 6.16.0
- Nova Version: 2.11.1.
- PHP Version: 7.2.11
- Database Driver & Version:
- Operating System and Version: windows 10
- Browser type and version: chrome

when searching "customer_id" at a "belongs to" relationship 
Notice am not talking about the global search, but inside a relationship search.

If i type the "customer number" fast then no error occur
If i type the "customer number" fast then an error occur

I believe that the reason is that
On the global search there is a limit of 5 results for each resource 
However there is no limit for the number of results in relationship search.
How can i limit the  results in relationship search ?

Also for each digit i type there is a query that is being sent to the sql server
When i have 75000 rows there are many results.
However when i type the customer_id fast there are no sub queries between the digits.

here is the error:
i get an error:
[2020-02-27 18:22:18] local.ERROR: Maximum execution time of 60 seconds exceeded {"userId":4,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Maximum execution time of 60 seconds exceeded at C:\\xampp\\htdocs\\turtlecrm\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Grammars\\Grammar.php:1242)
[stacktrace]
#0 {main}
"}

**Comment by davidhemphill** [comment]
We're looking into other methods of making this easier, but for the time being you can specify a method like this one on the parent resource:

```php
// Post.php
public static function relatableCategories($request, $query)
{
    $query->limit(5);
}
```

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by davidgabbay** [comment]
There is no such a method "relatableCategories" in Nova.
Maybe you ment "relatableQuery" ?
Both of them are not limiting to 5 results.

**Comment by davidgabbay** [comment]
Its not working for me, maybe you meant "relatableQuery" and not "relatableCategories" ?
Non of them limits the results

**Comment by davidgabbay** [comment]
i think you meant:

class posts extends Resource
    
{
    public static function relatableQuery( $request, $query)
    {
        return $query->limit(5);
    } 
.......

to be clear: at the resource of nova and not at the module

**Comment by davidhemphill** [comment]
No, Nova also supports a dynamic query method. It's the second example in the docs link I sent.

<img width="782" alt="image" src="https://user-images.githubusercontent.com/58970/75629805-cbcd0380-5baa-11ea-8a60-19febcae2a7d.png">

**Comment by crynobone** [comment]
See https://nova.laravel.com/docs/3.0/resources/relationships.html#limiting-relation-results

![image](https://user-images.githubusercontent.com/172966/106987874-56e64e80-67a9-11eb-805d-807bd06bc4f7.png)
