### ISSUE TITLE
Resource update form button should have a way to show confirmation dialog just like delete button. 

### ISSUE THREAD

**Issue by Nainabbas** [laravel/nova-issues#2397]
Resource update form button should have a way to show confirmation dialog just like a delete button.  
My client wants to have a confirmation dialog on the update button.

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
