### ISSUE TITLE
Filtering without a global scope result in wrong search results 

### ISSUE THREAD

**Issue by newtongamajr** [laravel/nova-issues#2398]
- Laravel Version: 6.17.0
- Nova Version: 2.11.1
- PHP Version: 7.2.26
- Database Driver & Version: Mysql 5.7.19
- Operating System and Version: Ubuntu 
- Browser type and version: Ubuntu 18.04.3 LTS
- Reproduction Repository: https://github.com/###/###

### Description:
I have a model Contractor inherited from another model Person that has as table 'persons'. All kinds of Person lives in 'persons' table: Contractor, Customer, Supplier and so on. to identify each of these entities, 'person' has a json column called nature that contains {"contractor": true, "customer": true} and each of my inherited model classes has a global scope to filter the specific kind of Person, like this one:
  protected static function boot()
  {
    parent::boot();
    static::addGlobalScope(new TipoPessoaScope('contractor'));
  }

Each of these Resources that manipulates 'Persons' has a special filter that removes that global scope, in order to be able to transform other persons into that kind of person (contractor, customer and so on) thru an action. At this moment that the filter removing the global scope is applied the search fails because it doesn't take into account the global scope removal.

Expected results in this situation:

If a filter that removes a global scope is applied, the result query should obey this constraint as any other filter applied to the query being executed.

**Comment by spekulatius** [comment]
Related https://github.com/laravel/nova-issues/issues/2934
