### ISSUE TITLE
Currency field not shown correct in CNY

### ISSUE THREAD

**Issue by phoenixg** [laravel/nova-issues#2399]
- Nova Version: v2.11.1
- PHP Version: 7.1.32

```php
Currency::make('The amount', 'amount_field')->currency('cny')->locale('zh_CN'),
```

If the value in db is 100 which stored in cents. It did not shown correctly as 1.00, but still shown as 100.

**Comment by jbrooksuk** [comment]
You're storing in cents, but Nova treats it as a full value. You should add a `resolveUsing(function ($value) { return $value / 100; }` to your field.

**Comment by phoenixg** [comment]
@jbrooksuk That does not suit for all kinds of currency, so Currency field does not support that? Some kind of currency is not devided by 100, but by 10 or by 1000.
