### ISSUE TITLE
DateTime field doesn't support format as "fromNow"

### ISSUE THREAD

**Issue by jameslkingsley** [laravel/nova-issues#24]
Version: 1.0.5

You're able to specify a format using the `format` method, however you can't choose to use Moment's `fromNow` [method](https://momentjs.com/docs/#/displaying/fromnow/).

**Comment by gonzunigad** [comment]
+1

**Comment by richvida** [comment]
+1

**Comment by davidhemphill** [comment]
There are no plans to implement this feature.
