### ISSUE TITLE
Html typo error

### ISSUE THREAD

**Issue by approached** [laravel/nova-issues#240]
Hi @ all

i found a typo error in: 

> nova/resources/views/auth/passwords/reset.blade.php

Line 33:
`<label class="block font-bold mb-2" for="password-confirm" control-label">{{ __('Confirm Password') }}</label>`

The control-label attribute tag is flawed.

**Comment by tillkruss** [comment]
Will be fixed in next release.

**Comment by approached** [comment]
Fixed
