### ISSUE TITLE
No way for dashboard input or pagination?

### ISSUE THREAD

**Issue by CitizenBeta** [laravel/nova-issues#2400]
We have the need for a large number of cards that show line graphs for each of our customers. Trends are perfect! Only problem is after about 100 customers we're basically ddosing ourselves and need to break up our dashboard into multiple pages. 

To solve this, we're doing this to show 40 sets of cards per page:

```
for ($i = 0; $i < $limit; $i++) {
    $className = 'Page' . ($i + 1) . 'CartAbandonmentDashboard';
    eval("class {$className} extends \App\Nova\Dashboards\CartAbandonmentDashboard {}");
    $dashboards[] = new $className($i, $showPerPage);
}
```
This works, but the problem is, this creates a bunch of links on the left-nav. Now its starting to look messy.

Dynamically adding multiple dashboards in this way appears to be the only method because there's no way to pass input into a dashboard to set results or pagination on dashboards as far as I can tell. Is there a better way?

**Comment by CitizenBeta** [comment]
And the reason why we dont just do this:

```
$dashboards[] = new OverallPerformanceDashboard(1, 30);
$dashboards[] = new OverallPerformanceDashboard(2, 30);
```

Is because the pages dont update when you click between them. For some reason re-using the same dashboard multiple times with dynamic input causes them to not load cards when you click back and forth.

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
