### ISSUE TITLE
Metrics ranges with future dates

### ISSUE THREAD

**Issue by piksha** [laravel/nova-issues#2401]
It is possible to set metrics range dates in the future (for example upcoming deliveries, tasks) by using a negative number as a key for the range array element.
```
public function ranges()
    {
        return [
            -1 => 'Next 24 hours',
            -7 => 'Next 7 days',
            -30 => 'Next 30 Days',
        ];
    }
```
To make it work it requires to update how date ranges are set. So the first date is always the smallest and second is the largest.
1) Metrics\Trend.php aggregate() function: whereBetween($dateColumn, [min($startingDate, $endingDate), max($startingDate, $endingDate)]) 
2) Metrics\Value.php previousRange($range, $timezone) function same approach

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
