### ISSUE TITLE
Nova is available for free

### ISSUE THREAD

**Issue by calin-berbecaru** [laravel/nova-issues#2403]
Dear contributors,

I would like to warn you that the source code of Nova is available for free:

**REDACTED**

I have to admit I've dowloaded it, but just for evaluation/dev purposes. As soon as I have a paying customer I will pay the full licence.

**Comment by jbrooksuk** [comment]
Thank you for bringing this to our attention.

**Comment by calin-berbecaru** [comment]
Well, a free Nova licence would be appreciated. Thank you.
