### ISSUE TITLE
Access Request Filters From Lens' Fields Function

### ISSUE THREAD

**Issue by MannikJ** [laravel/nova-issues#2405]
Can I define a filter whose value I can retrieve inside the `resolveUsing()` callback of a field? The filter should not be applied globally, but within the field's callback.

It seems like out of the box I can only retrieve the value from within the `query()` function, because of the `Laravel\Nova\Http\Requests\LensRequest`  vs. `Illuminate\Http\Request`.

**Comment by jbrooksuk** [comment]
`LensRequest` extends `NovaRequest` which itself extends `Request` and it looks like we're passing an instance of `NovaRequest` to the `fields()` function, so you should be fine.

**Comment by MannikJ** [comment]
Ok, your are correct! It is in fact no problem with the request object passed to the fields function for the normal index query.
I use [laravel-nova-excel](https://github.com/Maatwebsite/Laravel-Nova-Excel) to export the results, but for exporting the passed `Maatwebsite\LaravelNovaExcel\Requests\ExportLensActionRequest` (which is also a NovaRequest and has the filters function), does not hold the active filter values.
