### ISSUE TITLE
Cannot access model id in fillUsing callback when creating resource

### ISSUE THREAD

**Issue by shingsoso** [laravel/nova-issues#2407]
- Laravel Version: 5.8
- Nova Version: 2.0
- PHP Version: 7.2

```
public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
            Text::make('name')->fillUsing(function($request, $model, $attribute, $requestAttribute) {
                dd($model->id);
            }),
        ];
}
```
# It return null .

**Comment by jbrooksuk** [comment]
Because the id doesn't exist when you're at the form level.

**Comment by shingsoso** [comment]
> Because the id doesn't exist when you're at the form level.

So there is no way for me to customize a many to many relationship fields when creating ?

**Comment by shingsoso** [comment]
I found a way to get the model 's id in fillUsing() function 

```
CustomField::make('custom')->fillUsing(function ($request, $model, $attribute, $requestAttribute) {
            if (is_subclass_of($model, 'Illuminate\Database\Eloquent\Model')) {
                      $model::saved(function ($model) use ($attribute, $request) {
                                dd($model->id);
                      } 
}
```

**Comment by pavloniym** [comment]
@shingsoso 
Will not work on Octane (Swoole)!
On swoole `$model:saved ` event will fire every time on every model change (even if data change is not related with `CustomField`) and `$request` will leak to another processes which will cause data overwrite for all models

Wokraround:
```php
 ->fillUsing(function (NovaRequest $request, TeamUser $teamUser, string $attribute) {
    if ($teamUser->getKey() === null) $teamUser->save(); // hack!
    $teamUser->roles()->sync($request->get($attribute) ?? []);
})
```
