### ISSUE TITLE
Nova translations regarding resources do not contain placeholders anymore

### ISSUE THREAD

**Issue by Jebble** [laravel/nova-issues#2408]
- Laravel Version: 6.2
- Nova Version: 2.0
- PHP Version: 7.4.2

### Description:
In the Nova documentation you can see that a destructive action for example says "Delete User". In this version of Nova it says "Delete Resource". The translation files available after nova:install don't have placeholders.
For exmaple in `resources/lang/vendor/nova/en.json` you can see 
`"The :resource was created!": "The :resource was created!",`
But for deleting it is `"Are you sure you want to delete this resource?": "Are you sure you want to delete this resource?",` So there is no placeholder in the translation meaning that everything in nova is always called "Resource" instead of the actual Resource name.

Almost everything regarding Resources is hard coded to be "Resource".

**Comment by jbrooksuk** [comment]
Changing this will break too many translations used by other people.

We'll consider this in a future release though.

**Comment by Jebble** [comment]
Sad to read this comment. As the Documentation actually shows these Resources are translatable but they are not. That in my eyes look like it's a big and should be fixed. 

Resources already have their labels so these translations shouldnt break anything but fix them.
