### ISSUE TITLE
Nova::provideToScript doesn't update Nova.config values during resources navigation only on first page Load

### ISSUE THREAD

**Issue by arzola** [laravel/nova-issues#2409]
- Laravel Version: 6.2
- Nova Version: 2.1.11
- PHP Version: 7.3
- Database Driver & Version: MySQL 8
- Operating System and Version: Docker Environment 
- Browser type and version: Firefox / Chrome

### Description:

I'm using Nova serving callback to provide some data to my custom vue tool but Nova::provideToScript only works on page load and it doesn't work in subsequent requests navigating between Resources

I just want to change the value according the current resource loaded

```
Nova::serving(function (ServingNova $event) {
Nova::provideToScript([
                        'variable' => $variable,
                    ]);
});
```

### Steps To Reproduce:

Add the above code in the boot() method of your Tool/Component ServiceProvider you will see your variable set the first time you land in the page, but the variable cannot be override or set when other resource page is loaded through ajax

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!

**Comment by adrianthedev** [comment]
This still happens on Nova 3.3.0 with a resource-tool. What can I provide to investigate?
Would a screen recording and the code suffice?

**Comment by onlinelaser** [comment]
I'm seeing the same issue on Nova 3.32 as well.
