### ISSUE TITLE
Scope Relatable Filtering

### ISSUE THREAD

**Issue by ajarti** [laravel/nova-issues#241]
Hi guys,

I wondered if there is a way to scope the Relatable Filtering on a Nova resource?  I have a single users table, that houses both employers and job seekers, so I need to filter by both.  By Job Seekers on the application resource and by employers on the job resource. 

I hunted about, but looks like only one relatableQuery can be defined.

Any suggestions?

**Comment by ajarti** [comment]
I could always just switch based on the $request->getRequestUri() which contains the search caller .. but that just seems messy .. lol

**Comment by ajarti** [comment]
Actually what is a better question .. is how can we pass additional parameters with the search that can be used in the relatableQuery ? :)

**Comment by julianpoma** [comment]
+1 to this!

**Comment by paul-muckypuddle** [comment]
I have something similar (only want `Users` of a certain type within certain dropdowns). To accomplish this, in my `fields` method:

    $planOptions = Plan::where('is_contract', true)->pluck('name', 'id');
    $userOptions = User::where('entity_type', 'App\Student')->pluck('name', 'id');

    return [
        
        ID::make()->sortable(),

        BelongsTo::make('Plan')->exceptOnForms(),

        BelongsTo::make('User')->exceptOnForms(),

        Select::make('Plan')->options($planOptions)->onlyOnForms(),
        Select::make('User')->options($userOptions)->onlyOnForms(),

    ];

**Comment by ajarti** [comment]
@paul-muckypuddle thanks for the suggestions, that works great for short lists so thanks.  We still need the Dependent Filter for large lists that are searched.

**Comment by paul-muckypuddle** [comment]
@ajarti glad it helped - totally agree, hit the exact same problem, hopefully the Nova team will take onboard :)

**Comment by gonzunigad** [comment]
@ajarti it is not documented, but you can create custom relatable filters for every field creating a relatable{Model}. 

On Nova\Application you can create a `relatableUser($query) {...}`  and in your Nova\JobResource another `relatableUser($query) {...}' with the corresponding filter.

**Comment by iBet7o** [comment]
@ajarti I have the same problem. Could you solve it?

**Comment by itsgonnabesick** [comment]
@gonzunigad Just to precise that if you want to do a relatable{Model}, the BelongTo field is looking for the plural of the model name.

```php
    /**
     * Get the associatable query method name.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @param  \Illuminate\Database\Eloquent\Model  $model
     * @return string
     */
    protected function associatableQueryMethod(NovaRequest $request, $model)
    {
        $method = 'relatable'.Str::plural(class_basename($model));

        if (method_exists($request->resource(), $method)) {
            return $method;
        }
    }
```

And the fonction need to be static and need the request as well as the query.
```php
forward_static_call($this->associatableQueryCallable($request, $model), $request, $query);
```

So, for example:

```php
BelongsTo::make('Contact')
```

Would need this function to work
```php
    public static function relatableContacts(NovaRequest $request, $query)
    {
        return $query;
    }
```

**Comment by ppisecky** [comment]
I agree with @mathieutu that the method should be called with the relation name. Or an even better alternative is look by relation name first, then by model name.

Here's a valid use case. You have a list of `Projects` and a list of `Users`. Each user has a role. Each project can has 2 relations with the `users` table: the person who is responsible managment and the person responsible for budget. For each of the relations you want to limit the users available for association to a subset of users with a particular role - such as manager or accountant. This is similar to something I'm working on right now. The only solution I see at the time is probably extending the `BelongsTo` field and using a custom one.

**Comment by dkulyk** [comment]
```php
public function actions(Request $request)
{
    return [
        RelatedFilter::make('Category', 'category_id')
            ->options(function () {
                return Category::pluck('title', 'id');
            }),

        RelatedFilter::make('SubCategory', 'subcategory_id')
            ->related('category_id')
            ->options(function ($request, $filters) {
                return SubCategory::when($filters['category_id'], function ($query, $value) {
                    $query->where('category_id', $value);
                })->pluck('title', 'id');
            }),
    ];
}

**Comment by yehudahkay** [comment]
+1

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by bartabel** [comment]
@jbrooksuk Now that this is closed, how can we track whether this is already implemented or not? Do we have another overview of feature requests? Documentation often doesn't describe "advanced" features, so I'm not sure if this is already changed or if we still need workarounds.

**Comment by dacastro4** [comment]
The only way I could solve this was by using the field from the route. Example:

```
public static function relatableContacts(NovaRequest $request, $query)
{
    if($request->route()->parameter('field') === 'finance_contact') {
        return $query->whereHas( 'types', function ( Builder $typesBuilder ) {
            $typesBuilder->where( 'type_id', 1);
        });
    }

    return $query;
}
```

`$request->route()->parameter('field')` returns the relationship name so I could do it using that.

**Comment by crynobone** [comment]
I believe the latest options **Relatable Query** should already cover this:

![image](https://user-images.githubusercontent.com/172966/160824729-23c557a8-fcb5-4bd5-a739-56489b999e05.png)
