### ISSUE TITLE
Update laravel and Nova

### ISSUE THREAD

**Issue by webmasterowi** [laravel/nova-issues#2412]
- Laravel Version: 6.2
- Nova Version: 2.0
- PHP Version: 7.3

### Description:
Hello, I want to update laravel form 6.2 to 7 but  when i try it shows that nova is not compatible since I have to update nova from the current 2.0 version to the 3, so i when yo upgrade guide in nova docs and after I change in the composer from 2.0 to 3.0 it show me this error when I do update

- The requested package laravel/nova ~3.0 exists as laravel/nova[2.1.x-dev, dev-master] but these are rejected by your constraint.
 Please help, I dont know what to do.

**Comment by jbrooksuk** [comment]
You should clear your Composer caches.
