### ISSUE TITLE
Image Multiple selection

### ISSUE THREAD

**Issue by bing8u** [laravel/nova-issues#2415]
```php
Image::make('轮播图', 'images')->withMeta(['multiple' => 'multiple'])

// or

Image::make('轮播图', 'images')->withMeta([
     'extraAttributes' => ['multiple' => 'multiple']
])
```

It still has only one file selected, I need it to return an array

**Comment by bing8u** [comment]
官方能这样直接在这个组件上添加功能变更为多选吗，

一个整晚在找办法，发现了扩展包可以实现，但都不友好。

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
