### ISSUE TITLE
Pass Disk to File Storage Invokables

### ISSUE THREAD

**Issue by mdavis1982** [laravel/nova-issues#2417]
- Laravel Version: 7.0.4
- Nova Version: 3.0.1
- PHP Version: 7.4.3
- Database Driver & Version: MySQL 8.0.19
- Operating System and Version: macOS 10.15.3
- Browser type and version: Chrome 80.0.3987.132
- Reproduction Repository: N/A

### Description:
When using an invokable object for customising file / image storage, the disk to use needs to be set twice.

If the disk is set in the resource as follows:

```php
Image::make('Avatar', 'image_path')
    ->disk('media')
    ->store(new StoreAvatar())
```

Then when using the invokable, the disk needs to be set in the call to the `store` method:

```php
class StoreAvatar
{
    public function __invoke(Request $request, Model $model): array
    {
        $disk = 'media';
        $directory = 'avatars';

        return [
            'image_path' => $request->image_path->store($directory, $disk),
            'image_original_name' => $request->image_path->getClientOriginalName(),
            'image_size' => $request->image_path->getSize(),
        ];
    }
}
```

If the `$disk` argument is not provided to the `store` method call, the `public` disk is used.

The disk needs to be set on the resource so that image previews in forms etc work as expected.

### Steps To Reproduce:
1. Add a Resource with an image
2. Set up a different disk in filesystem config
3. Set the disk inside the resource
4. Use an invokable object for storage, and call the `store` method without passing a disk

### Proposed Resolution:
I think it would be useful to pass the configured disk from the resource to the invokable as a parameter:

```php
public function __invoke(Request $request, Model $model, string $disk): array
```

That way, the disk would only need to be configured on the resource, and I wouldn't forget to update it in both places when things change 😄 

The call to `store` would still need to pass the disk - which is fine and expected when taking control of the storage - but it would only need to be configured in one place.

**Comment by dkulyk** [comment]
Parameters already passed to callback:
```php 
public function __invoke($request, $model,  $attribute, $requestAttribute, $disk, $storagePath)
```

**Comment by jbrooksuk** [comment]
Documented at https://github.com/laravel/nova-docs/commit/2c9abd1856f32506c7b36b39767fa6d4833fac00
