### ISSUE TITLE
Image field not reloading when relation is changed

### ISSUE THREAD

**Issue by Mopsit** [laravel/nova-issues#2418]
- Laravel Version: 6.18
- Nova Version: 2
- PHP Version: 7.4

I'm currenly picking a relation from a dropdown on one of my resources, then displaying the fields from the relation. All my fields are updating the content when I swap relation. All except Image field.

When I view the data in dev tools, I can see ImageLoader component src changing and everything, but it doesn't reload the image and rerender the HTML. It just stays the same.

Is this a bug or is that just how Vue works?

**Comment by jbrooksuk** [comment]
Can you please provide a reproduction of this issue.
