### ISSUE TITLE
Nova use wrong class in HasMany

### ISSUE THREAD

**Issue by sitnikov** [laravel/nova-issues#2419]
- Laravel Version: 6.18.0
- Nova Version: 2.12.0
- PHP Version: 7.2.27
- Database Driver & Version: mysql-percona 5.6
- Operating System and Version:  Centos 7.x
- Browser type and version: Google Chrome 

### 

Nova use wrong class in HasMany if two classes with same name but in different namespaces.

### Steps To Reproduce:

1).
namespace App\Nova\Currency;
class History extends \App\Nova\Resource {
public static $model = 'App\\Currency\\History';
}

2).
namespace App\Nova\Product;
class History extends \App\Nova\Resource {
public static $model = 'App\\Product\\History';
}

3).
namespace App\Nova;

class Product extends Resource {
...
public function fields(Request $request)
{
	return [
		...
		HasMany::make('Price History', 'history', 'App\Nova\Product\History')->onlyOnDetail()
		...
	];
}

4).
namespace App\Nova;

class Currency extends Resource {
...
public function fields(Request $request)
{
	return [
		...
		HasMany::make('History', 'history', 'App\Nova\Currency\History')
		...
	];
}

Product detail page show HasMany table with App\Nova\Currency\History  fields but with App\Product\History data.

When I am rename App\Nova\Product\History to some other name this fix this issue

**Comment by jbrooksuk** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](https://larachat.co/).
