### ISSUE TITLE
Changing per page value show "not matching criteria" when there are not enough results

### ISSUE THREAD

**Issue by chelev** [laravel/nova-issues#242]
Version: 1.0.6

How to reproduce the issue:

I have a resource with 70 items. By default I see 25 per page. If I go to page number 3 for example I see the 50-70 record. Once I am on page number 3 if I change to 100 records per page I end up with "not matching criteria" because it remember I am on page number 3 and it is looking for records from 200 to 300 instead of redirecting me back to page number 1 because I don't have enough records.

**Comment by davidhemphill** [comment]
I believe this is fixed.

**Comment by davidhemphill** [comment]
Fixed in that you can remove the filtering and get back to an actual viewable page.
