### ISSUE TITLE
Nova resource level validation is not available

### ISSUE THREAD

**Issue by raulsh** [laravel/nova-issues#2420]
- Laravel Version: 6.x
- Nova Version: 2.x
- PHP Version: 7.3.x
- Database Driver & Version: MySQL 5.x.x
- Operating System and Version: Docker/Linux
- Browser type and version: Chrome

### Description:

Nova resource level validation is not available. There are validations per field, but not for entire resource. For example:
I need add a poll (its a poll software), but I need check if the user had a available polls to add more. I readed the documentation but there is nothing for doing that.

**Comment by jbrooksuk** [comment]
You should use Observers.

**Comment by adrianthedev** [comment]
You can create your [own validation rule](https://laravel.com/docs/7.x/validation#custom-validation-rules) and pass the `$request` object to that rule in the Nova Resource. Then, in the rule you get the model you are trying to validate from the `$request` object.

```
Number::make('Gift card amount')->max(500)->step(1)->rules('required', new ValidateItSomeMoreWithTheRequest($request)),
```
