### ISSUE TITLE
The 4th params in $this->sumByDays() of lens trend metric, not support Y-m-d format

### ISSUE THREAD

**Issue by phoenixg** [laravel/nova-issues#2421]
- Laravel Version: 5.x
- Nova Version: v2.11.1
- PHP Version: 7.1.32

My `$dateColumn` param is not `datetime/timestamp`, but a Y-m-d date, but Nova as a result make add time automatically in sql(My value is '2019-09-01', it searches '2019-09-01 10:12:33'). How to just use date?

My code:
```php
public function calculate(Request $request) {
        return $this->sumByDays($request, MyModel::class, 'paid_num', DB::raw("my_date"));
}
```

**Comment by jbrooksuk** [comment]
Metrics are made to use Timestamp columns, if you need to customise this, then you'd need to create a custom Metric class that works this way.
