### ISSUE TITLE
not show the name of the logged in user

### ISSUE THREAD

**Issue by Tony133** [laravel/nova-issues#2422]
- Laravel Version: 6.12.0
- Nova Version: 2.12.0
- PHP Version: 7.3.9
- Database Driver & Version: 5.7.25
- Operating System and Version: MacOS 10.14.6
- Browser type and version: Chrome 80.0.3987.132

### Description:
the panel does not show the name of the logged in user.
every time I change to a new version I always do the command as reported in the documentation:

```php artisan nova: publish```

<img width="1347" alt="laravel-nova" src="https://user-images.githubusercontent.com/11542387/76232873-a2a21800-6227-11ea-8fe3-5b2de842ca29.png">

**Comment by medvinator** [comment]
check file **resources/views/vendor/nova/partials/user.blade.php**

**Comment by Tony133** [comment]
The file is there, this is its content:

```
<dropdown-trigger class="h-9 flex items-center" slot-scope="{toggle}" :handle-click="toggle">
    @isset($user->email)
        <img
            src="https://secure.gravatar.com/avatar/{{ md5($user->email) }}?size=512"
            class="rounded-full w-8 h-8 mr-3"
        /> 
    @endisset

    @isset($user->image)
        <img src = "{{ asset('/storage/'. $user->image) }}" class="rounded-full w-8 h-8 mr-3"/>
    @endisset
    
    <span class="text-90">
        {{ $user->name ?? $user->email ?? __('Nova User') }}
    </span>
</dropdown-trigger>

<dropdown-menu slot="menu" width="200" direction="rtl">
    <ul class="list-reset">
        <li>
            <a href="{{ route('nova.logout') }}" class="block no-underline text-90 hover:bg-30 p-3">
                {{ __('Logout') }}
            </a>
        </li>
    </ul>
</dropdown-menu>

```

**Comment by jbrooksuk** [comment]
Do you have any errors in the console?

**Comment by jbrooksuk** [comment]
I'm going to close this because I don't believe it to be a bug in Nova. I have a fresh application working just fine.

**Comment by Tony133** [comment]
in console with I have errors

**Comment by Tony133** [comment]
I managed to solve

Thank you

**Comment by Payetus** [comment]
> I managed to solve
> 
> Thank you

How did you solve it @Tony133
