### ISSUE TITLE
Computed Fields not working with Field Formatting

### ISSUE THREAD

**Issue by gekkedev** [laravel/nova-issues#2423]
- Laravel Version: 6.7.0
- Nova Version: v3.0.2
- PHP Version: 7.4.0
- Database Driver: SQLite

### Description:
[Computed Fields](https://nova.laravel.com/docs/1.0/resources/fields.html#computed-fields) don't seem to work with [Field Formatting](https://nova.laravel.com/docs/1.0/resources/fields.html#field-resolution-formatting)

### Steps To Reproduce:
Create a dummy resource and copy the code for this dummy field:
```
Text::make("test field", function() {
    return "A";
})->displayUsing(function($value) {
    return $value . "B";
}),
```
Expected result: `AB`
Actual result: `A`

**Comment by jbrooksuk** [comment]
This should be fixed in the latest release [v3.2.0](https://nova.laravel.com/releases/3.2.0).
