### ISSUE TITLE
Stackable filters doesnt work as expected

### ISSUE THREAD

**Issue by chilio** [laravel/nova-issues#2424]
- Laravel Version:7.0.8
- Nova Version: dev.master
- PHP Version: 7.2.11
- Database Driver & Version: PGsql
- Operating System and Version: Win10x64 - 18363.693
- Browser type and version: Chrome 80.0.3987.132 
- Reproduction Repository: https://github.com/###/###

### Description:
Filters work great, out of the box, however, if you want to stack them, you get results from only one of filters.

### Steps To Reproduce:
1. Create 2 filters. In my case, both boolean, but tested with other types and it doesn't change a thing.
2. Filter through, any of these filters -> results are fine, and expected.
3. However, if you try to combine them together in the UI, they produce false results - only the first filter gets applied, not all of them.
All of these filters should be applied, not the first one only...

**Comment by jbrooksuk** [comment]
Are you re-using the same filter, but with different options? If so, filters are keyed based on the class name by default, to re-use one you need to have a different class name or set the key.
