### ISSUE TITLE
can't choose current item when I use a Self-Relationship

### ISSUE THREAD

**Issue by huoding** [laravel/nova-issues#2425]
- Laravel Version: 5.8.37
- Nova Version: 2.12.0
- PHP Version: 7.3.8
- Database Driver & Version: mysql 5.8
- Operating System and Version: mac os
- Browser type and version: chrome 80

### Description:
I have a content table, it has a Self-Relationship:

```
model:

class Content extends Model
{
    public function parent()
    {
        return $this->belongsTo(Content::class, 'parent_id');
    }

    public function children()
    {
        return $this->hasMany(Content::class, 'parent_id');
    }

nova:

BelongsTo::make('content', 'parent', Content::class)->nullable()
```

### Steps To Reproduce:
When i try to create children this related Models HasMany,
Its not choosing current item its not coming with selected value.
in typing "parent" area coming with children from "viaRelationship" parameter from url when i change url to "children to parent" its working well

<img width="677" alt="xxx" src="https://user-images.githubusercontent.com/3479812/76302734-76f06200-62fb-11ea-8410-22fbcd466d7e.png">

**Comment by preliot** [comment]
Laravel Version: 5.8.37
Nova Version: 2.11.1
PHP Version: 7.2.19
Operating System and Version: Windows 10
Browser type and version: Chrome 79 64-bits

**Description**

This is coincendence, i run into the same issue just now!

I've got a resource with catalog products. Some of them are simple products (no issues) and some are variations with simple products as configurable options. All simple, configurable and configurable options are in the same table. 

I can see my recursive related product variations. I'ts also possible to view or delete a product variation.  But i **can't create or update**  an existing related resource. Both actions result in a 404, see console output for details:

```
/nova-api/catalog-products/field/children:1 Failed to load resource: the server responded with a status of 404 (Not Found)
vendor.js?id=fdec6f749c878e3a3065:1 Error: Request failed with status code 404
    at FtD3.t.exports (vendor.js?id=fdec6f749c878e3a3065:1)
    at t.exports (vendor.js?id=fdec6f749c878e3a3065:1)
    at XMLHttpRequest.f.onreadystatechange (vendor.js?id=fdec6f749c878e3a3065:1)
Xt @ vendor.js?id=fdec6f749c878e3a3065:1
Ft @ vendor.js?id=fdec6f749c878e3a3065:1
Ht @ vendor.js?id=fdec6f749c878e3a3065:1
(anonymous) @ vendor.js?id=fdec6f749c878e3a3065:1
/nova-api/catalog-products/field/children:1 Failed to load resource: the server responded with a status of 404 (Not Found)
vendor.js?id=fdec6f749c878e3a3065:1 Error: Request failed with status code 404
    at FtD3.t.exports (vendor.js?id=fdec6f749c878e3a3065:1)
    at t.exports (vendor.js?id=fdec6f749c878e3a3065:1)
    at XMLHttpRequest.f.onreadystatechange (vendor.js?id=fdec6f749c878e3a3065:1)
Xt @ vendor.js?id=fdec6f749c878e3a3065:1

``` 


**Model**

```php

class CatalogProduct extends Model
{
//..
   public function children(): ?Relations\HasMany
    {
        return $this->hasMany(CatalogProduct::class, 'parent', $this->getKeyName());
    }

   public function isConfigurable(): bool
    {
        return $this->type == ProductType::CONFIGURABLE;
    }
 //..
}
```

**Nova resource**

```php
//..
 public function fields(Request $request): array
    {
        $fields = [];

        if($this->isConfigurable())
        {
            $fields[] = Fields\HasMany::make(ucfirst(__('configurableProducts')), 'children', CatalogProduct::class)
                ->singularLabel(__('configurableProduct'));
        }

        return $fields;
    }
```

**Comment by preliot** [comment]
Seems related to https://github.com/laravel/nova-issues/issues/2646. Really need a fix :)

**Comment by jbrooksuk** [comment]
@preliot I think yours is a dupe, but contains more info?

**Comment by jbrooksuk** [comment]
Closing for #2646 as it contains more info.
