### ISSUE TITLE
Nova v3: Custom and third party tools routes added via router.addRoutes not working

### ISSUE THREAD

**Issue by m-lotze** [laravel/nova-issues#2427]
- Laravel Version: 7.0.8
- Nova Version: 3.0.2
- PHP Version: 7.4
- Database Driver & Version: MySQL 5.7
- Operating System and Version: homestead
- Browser type and version: Chrome

### Description:
I just upgraded a project form nova 2 to 3. My custom tools and some third party tools register frontend routes in tool.js like this:

```
Nova.booting((Vue, router, store) => {
    router.addRoutes([
        {
            name: 'images',
            path: '/images',
            component: ImageManager
        }
    ])
})
```
navigation.blade.php:

```
<router-link tag="h3" :to="{name: 'images'}"
             class="cursor-pointer flex items-center font-normal dim text-white mb-6 text-base no-underline">
    <svg class="sidebar-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
        <path fill="var(--sidebar-icon)"
              d="M20 7a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9c0-1.1.9-2 2-2h2.38l1.73-3.45A1 1 0 0 1 9 3h6a1 1 0 0 1 .9.55L17.61 7H20zM9.62 5L7.89 8.45A1 1 0 0 1 7 9H4v10h16V9h-3a1 1 0 0 1-.9-.55L14.39 5H9.62zM12 17a4 4 0 1 1 0-8 4 4 0 0 1 0 8zm0-2a2 2 0 1 0 0-4 2 2 0 0 0 0 4z"/>
    </svg>
    <span class="sidebar-label">
        Bilder
    </span>
</router-link>
```

In v3 this seems to not work anymore. The navigation is rendered but no links are rendered. What changed?

**Comment by m-lotze** [comment]
Seems to have somthing to do with my approach of combining all scripts for tools etc.

**Comment by Niblu** [comment]
Have you found the solution to this? Having an exact same problem now.
