### ISSUE TITLE
Feature request: Access resource filter values inside the actions method

### ISSUE THREAD

**Issue by robindrost** [laravel/nova-issues#2428]
Hello,

Is it possible to retrieve the filters that are applied on a resource inside the actions method? It seems that this is currently not possible.

Use case:
I can filter my users on attending date. So i can apply that date onto a query that is used to generate field values used in the action.

Thanks in advance :).

**Comment by skoyah** [comment]
Hey @robindrost  i believe you can just use the [base64_decode()](https://www.php.net/manual/en/function.base64-decode.php) php function to get the filters from the request.

Give it a try and let me know how it went!

**Comment by robindrost** [comment]
Hey @skoyah. Thanks for the reply. This does only work on the main request and not on the sub requests like when getting the filters.

**Comment by skoyah** [comment]
Oh, you mean to access the filters on the `actions()`method on the resource class?

**Comment by robindrost** [comment]
Correct :)!

**Comment by skoyah** [comment]
I was able to get the filters on the `actions()` method:

<img width="1234" alt="Screenshot 2020-04-06 at 16 48 08" src="https://user-images.githubusercontent.com/36083448/78571422-77124d80-7826-11ea-99f9-814bb6c1465e.png">

<img width="441" alt="Screenshot 2020-04-06 at 16 49 04" src="https://user-images.githubusercontent.com/36083448/78571495-8a251d80-7826-11ea-8efd-b2d6586d3d7a.png">

**Comment by skoyah** [comment]
And here I can decode them:

<img width="499" alt="Screenshot 2020-04-06 at 16 51 05" src="https://user-images.githubusercontent.com/36083448/78571745-da03e480-7826-11ea-9f2d-7e598e9abbed.png">

<img width="1096" alt="Screenshot 2020-04-06 at 16 50 55" src="https://user-images.githubusercontent.com/36083448/78571755-dcfed500-7826-11ea-9a50-39947616cd91.png">

**Comment by davidhemphill** [comment]
You can check out the internal implementation of filter decoding in the `DecodesFilters` trait in `src/Http/Requests/DecodesFilters`.
