### ISSUE TITLE
Feature: Auto Discovery

### ISSUE THREAD

**Issue by vmitchell85** [laravel/nova-issues#243]
Would be cool if tool auto-discovery existed. Currently Laravel uses the `composer.json` file to auto discover service providers, could we add a `nova` section?

Maybe something like:
```
"extra": {
        "laravel": {
            "nova": [
                "Beyondcode\\TinkerTool\\Tinker"
            ]
        }
    },
```

**Comment by taylorotwell** [comment]
This repository is for tracking bugs. Feature requests may be emailed to Nova customer support.
