### ISSUE TITLE
DateTime field cannot be unset once set

### ISSUE THREAD

**Issue by natbentley** [laravel/nova-issues#2430]
- Laravel Version: 6.18.0
- Nova Version: 2.12.0
- PHP Version: 7.4.1
- Database Driver & Version: MySQL 5.6
- Operating System and Version: Homestead (release) 
- Browser type and version: Chrome 80.0.3987.132 

### Description:

Clicking a DateTime resource field in Nova brings up the Flatpickr interface.  Clicking off the datepicker fills in the field, even when a date is not selected.  Once a date is set, it's seemingly impossible to remove the date (i.e. selecting the text and deleting, tabbing away, pressing escape).  When a field is not required, this is problematic as once set, cannot be unset, and if tabbing through fields, is automatically populated.

### Steps To Reproduce:

Create new Nova resource, add a Laravel\Nova\Fields\DateTime field type to it, then via Nova create a new record using that resource.  Click the DateTime field, then click off the element.  DateTime is populated and is seemingly impossible to remove.  Suggest adding ability to delete text in field, or a button to clear data.

**Comment by natbentley** [comment]
Apologies, looks like my bug report is a duplicate of #2358

**Comment by jbrooksuk** [comment]
Dupeo fio
