### ISSUE TITLE
Refreshing a page after altering the per page option doesn't work

### ISSUE THREAD

**Issue by milewski** [laravel/nova-issues#2432]
- Laravel Version: 6
- Nova Version: 2.12.0

### Description:

When modifying the per page option on a resource table and refreshing the page the `resource per page` option is not respected

![image](https://user-images.githubusercontent.com/2874967/76593378-23675980-6531-11ea-88ba-42f1c9fc6a5f.png)

### Steps To Reproduce:

1 - Open any resource page
2 - Change the per page option to 100
3 - Refresh the page
5 - See the URL shows `?XXXXX_per_page=100`, however, the items on the resource is `25 of XXX`

**Comment by jbrooksuk** [comment]
I'm not able to replicate this in v3.2.1

**Comment by milewski** [comment]
Just upgrade to version `v3.2.1` tried again problem still persists, I tried removing every custom package, steps to reproduce was  straight forward:

1 - generate 500 fake users 
2 - go to user index page
3 - change the per page to 100
4 - wait for the page finish loading check at the bottom it is 100 of 500
5 - refresh the page (F5) 
6 - scroll to the bottom again see it is 25 of 500

**Comment by jbrooksuk** [comment]
In our test application there is a query parameter added for the `users_page`: http://nova-fresh.test/nova/resources/users?users_page=18

Does this not happen for you? Try running `php artisan nova:publish --force`.

**Comment by milewski** [comment]
`users_page` page only appears if I go to the next page, so it looks like this:

```
?userss_page=2&users_per_page=100
```

and the footer it shows `201-300 of 8446` 

however, if I refresh the page the URL still looks like `?userss_page=2&users_per_page=100` but the footer shows: `101-150 of 8446` so it is no longer showing 100 records per page, 

And I'm using simple pagination:

```
'pagination' => 'simple',
```
