### ISSUE TITLE
Can not turn on vue devtools

### ISSUE THREAD

**Issue by keganlester** [laravel/nova-issues#2436]
- Laravel Version: 7.0
- Nova Version: 3.0.2.
- PHP Version: 7.2.5
- Database Driver & Version: pgsql 
- Operating System and Version: mac Catalina
- Browser type and version: chrome 
- Reproduction Repository: any fresh

### Description:
I can not turn on vue devtools. Looks like I have a dependency missing but I can't figure out what it is.

### Steps To Reproduce:
copy fresh laravel nova into nova directory
composer update
copy steps from docs to remove devtools
cd ./vendor/laravel/nova
mv webpack.mix.js.dist webpack.mix.js
npm install
npm run dev
then this error 

ERROR in ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources/js/components/TooltipContent.vue
Module build failed: SyntaxError: Unexpected token (14:6)

  12 |   render(h) {
  13 |     return (
> 14 |       <div
     |       ^
  15 |         class={this.$props.class || defaultClasses}
  16 |         style={`max-width: ${this.maxWidth}px`}
  17 |       >

 @ ./resources/js/components/TooltipContent.vue 4:21-367
 @ ./resources/js/components.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/css/app.css

ERROR in ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources/js/components/Icons/Loader.vue
Module build failed: SyntaxError: Unexpected token (18:6)

  16 |   render(h) {
  17 |     return (
> 18 |       <svg
     |       ^
  19 |         class="mx-auto block"
  20 |         style={{ width: `${this.width}px` }}
  21 |         viewBox="0 0 120 30"

 @ ./resources/js/components/Icons/Loader.vue 4:21-362
 @ ./resources/js/components.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/css/app.css

ERROR in ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources/js/components/Tooltip.vue
Module build failed: SyntaxError: Unexpected token (27:6)

  25 |   render(h) {
  26 |     return (
> 27 |       <v-popover
     |       ^
  28 |         trigger={this.trigger}
  29 |         offset={this.offset}
  30 |         placement={this.placement}

 @ ./resources/js/components/Tooltip.vue 4:21-360
 @ ./resources/js/components.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/css/app.css

ERROR in ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources/js/components/Dropdown.vue
Module build failed: SyntaxError: Unexpected token (27:6)

  25 |   render(h) {
  26 |     return (
> 27 |       <v-popover
     |       ^
  28 |         trigger={this.trigger}
  29 |         offset={this.offset}
  30 |         placement={this.placement}

 @ ./resources/js/components/Dropdown.vue 4:21-361
 @ ./resources/js/components.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/css/app.css
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/keganlester/.npm/_logs/2020-03-16T18_20_39_912Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by davidhemphill** [comment]
Compiling Nova from source is not supported.

**Comment by thaisanly** [comment]
@keganlester you need to add babel configuration on nova folder.

```
{
    "plugins": [
        "transform-runtime",
        "transform-vue-jsx",
        "syntax-jsx",
        "transform-object-rest-spread"
    ],
    "presets": [["env"]],
    "env": {
        "test": {
            "presets": [["env", { "targets": { "node": "current" } }]]
        }
    }
}

```

**Comment by sfinktah** [comment]
**Update**

In fairness, I extracted nova into a fresh install of Laravel, inserted:

```
  "resolutions": {
    "node-sass": "6.0.1"
  }
```

To the end of `/vendor/laravel/nova/package.json`, removed all the test dependencies, then ran

```
yarn add node-sass@6.0.1 --force --dev
yarn run dev
cd ../../../
artisan view:clear
artisan nova:publish
```

And it just worked.

I used `yarn` because there was already a `yarn.lock` file present.
