### ISSUE TITLE
The validation message does not appear under the currency field.

### ISSUE THREAD

**Issue by kamilkozak** [laravel/nova-issues#2437]
- Laravel Version: 6.18.1
- Nova Version: 2.12.0

The validation message does not appear under the currency field. There is only a red border.

**Comment by pokono** [comment]
Is this fixed? On what version?

**Comment by crynobone** [comment]
> Is this fixed? On what version?

Fixed on v3.1.0 > Fixed an issue preventing validation errors from being correctly passed to Currency fields. #830
