### ISSUE TITLE
Action Log empty

### ISSUE THREAD

**Issue by jwahdatehagh** [laravel/nova-issues#244]
I set up an action as laid out in the documentation, but in the table log it never shows a value for the 'Initiated By' column:
![screen shot 2018-08-27 at 15 17 57](https://user-images.githubusercontent.com/2725836/44662102-0a5d8d00-aa0d-11e8-8d50-f5e7bf39ca74.png)

My user resource has a working `title` function.

Thanks!

**Comment by Livijn** [comment]
I get the same. Looking in the DB, it shows that `user_id` is being set.
