### ISSUE TITLE
Different behaviour using markdown field in WYSIWYG preview vs displayed content

### ISSUE THREAD

**Issue by craigcartmell** [laravel/nova-issues#2440]
- Laravel Version: 6.7.0
- Nova Version: 2.5.0
- PHP Version: 7.3.9
- Database Driver & Version: Postgres
- Operating System and Version: Linux Ubuntu
- Browser type and version: Chrome 80.0.3987.132
- Reproduction Repository: 

### Description:

The behaviour of using a tilde to strike through text in the markdown preview differs when viewing the actual content on the details page of a resource.

### Steps To Reproduce:

1. Add some markdown to strikethrough text using a single tilde
2. Click preview in WYSIWYG to see the strikethrough applied
3. Click save to be redirected to details page
4. Click show content next to field
5. See text does not have strikethrough applied

<img width="859" alt="Screenshot 2020-03-18 at 06 58 03" src="https://user-images.githubusercontent.com/3315022/76933957-376eda80-68e6-11ea-9a09-df0f07358247.png">
<img width="863" alt="Screenshot 2020-03-18 at 06 58 08" src="https://user-images.githubusercontent.com/3315022/76933960-3a69cb00-68e6-11ea-907c-88c8050d9fad.png">
<img width="193" alt="Screenshot 2020-03-18 at 06 58 44" src="https://user-images.githubusercontent.com/3315022/76933965-3d64bb80-68e6-11ea-891b-58e49c6849b2.png">

**Comment by jbrooksuk** [comment]
Just as a test, can you use double strike-through please:

```md
~~strike~~
```

**Comment by craigcartmell** [comment]
Double strikethrough works as expected @jbrooksuk

**Comment by jbrooksuk** [comment]
Okay, that means this isn't an issue because Nova uses Markdown-IT which is using GitHub's Markdown Syntax: https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#styling-text

**Comment by craigcartmell** [comment]
Shouldn't the behaviour shown in the preview of the WYSIWYG match the content though? Or am I missing something?

**Comment by jbrooksuk** [comment]
However, I've noticed Nova using a different Markdown renderer between the detail and form view.

**Comment by jbrooksuk** [comment]
@craigcartmell I'm just testing switching out the Markdown renderer now.

That said, you'll need to upgrade to v3.0

**Comment by craigcartmell** [comment]
Thanks @jbrooksuk
