### ISSUE TITLE
Laravel Nova Excel Export Failing

### ISSUE THREAD

**Issue by adheesha23** [laravel/nova-issues#2441]
- Laravel Version: 5.8.35
- Nova Version: 2.8.0
- PHP Version: 7.2.26
- Database Driver & Version:MySQL -  5.7.28
- Operating System and Version: nginx
- Browser type and version: Chrome Latest

### Description:
We have an issue currently with the Laravel Nova excel export. Currently we have around 6000 records in our user table and we are unable to export those records with Laravel Nova Excel export functionality. The request for export getting timeout giving the error "Allowed memory size exhausted". The user table only have simple 1 to 1 relationship with 2 other tables only and it should be a straightforward download without any memory issues. After investigation we have found in Laravel Nova download Excel action, it is querying one record at a time for each field. We need to know is there a solution for this to use download excel export records as a bulk instead of queriying one record at a time which is memory exhausting. We appreciate your support on this matter.

### Steps To Reproduce:
Try to export around 6000 records with relationship of 1 or 2 other tables.

**Comment by davidhemphill** [comment]
This is not a support forum for external third-party Nova packages.
