### ISSUE TITLE
Global Search dislikes large numbers

### ISSUE THREAD

**Issue by einar-johan** [laravel/nova-issues#2442]
- Laravel Version: 7.1.3
- Nova Version: 3.0.2
- PHP Version: 7.4.3
- Database Driver & Version: PostgreSQL 12.2

### Description:
When I search in the global search (navbar) with a large number I get "server error". I often need to look up id's consisting of 18 digits that I've stored as a string in the database. This large number is an external id, so it's just used as a model attribute. 

The database clearly doesn't like that we try to use that input-value as an integer when we look it up in database tables. I use int4 for the ID-columns . 

Error: 
`Numeric value out of range: 7 ERROR:  value "707050000012345678" is out of range for type integer (SQL: select * from "comments" where (("comments"."id" = 707050000012345678 or "comments"."id"::text ilike %707050000012345678%)) and ("creator_id" = 75) and "comments"."deleted_at" is null order by "comments"."id" desc limit 5)`

I just upgraded Nova, and this worked fine before in version 2.3.1. I think this was the last version where it was still possible to lookup with high numbers, as I've experienced this before, but then rolled-back version.

### Steps To Reproduce:
Try to search with a big number, for example 707050000012345678.

**Comment by jbrooksuk** [comment]
@einar-johan I'm curious, what happens when you search your resources for a big number?

**Comment by jbrooksuk** [comment]
Also, are you using 32-bit version of PHP or 64?

**Comment by einar-johan** [comment]
Hi @jbrooksuk  :) When I search the resources (on their resource page) everything is working alright, and I get the results as expected. I run the  64-bit version of PHP.

**Comment by jbrooksuk** [comment]
Hmm, that's weird because the global search uses the resource index search code:

```php
$query = $resource::buildIndexQuery(
    $this->request, $resource::newModel()->newQuery(),
    $this->request->search
);
```

**Comment by einar-johan** [comment]
Hold on, I'm sorry, I have many resources, and I just tried them all now after you feedback. Some fail, but not every resource. The comments resource from my original message is still failing, but most of the others are okey. 

I've discovered that the ones that are failing is failing because of 'id' being in $search array property on the Nova resource. If I comment out the 'id' field the search works fine, both on the resource and in the global search. 

It seems like it's not possible to have the ID as searchable field. 

For me, this solves my problem so far as I seldom search for a models ID anyway. But maybe something for you guys to be aware of?

**Comment by jbrooksuk** [comment]
I believe ID is always searched, even if it's removed from `$searchable`?

**Comment by einar-johan** [comment]
I tested in my app now, and yes, you are correct. I get all the resources with that ID I search for. 

Then it is a bit strange that the searches fails when 'id' is in the search property. 

As an experiment I created a new model, and created a resource file for it by running the "nova:resource" command. The resource template used for generating new resource files has 'id' in the $search property, so now the searches fails again.

If the 'id' is searched for automatically anyways, maybe it could be removed from the $search property? It's a bit misleading, as you could think removing it also removes it from being included in searches. Is it only used as a placeholder?

**Comment by jbrooksuk** [comment]
@einar-johan here is the code that is responsible for this behaviour:

```php
$canSearchPrimaryKey = is_numeric($search) &&
                                   in_array($query->getModel()->getKeyType(), ['int', 'integer']) &&
                                   ($connectionType != 'pgsql' || $search <= PHP_INT_MAX) &&
                                   in_array($query->getModel()->getKeyName(), static::$search);
```

**Comment by einar-johan** [comment]
Ok, after some testing I now think understand how this is put together. 

So that code triggers the query that produces the error I get when the primary key is in the $search array. And ID is not always searched for, like I thought in my previous comment, only if in the $search array.

That means if someone 
1) search for a number that is higher than the primary key integer type allows in the database and 
2) has 'id' in the $search array for any of the resources
they will get this server error. In my case I will not be able to search for Id's as long as I need to look up large numeric values.

Seems like there should be done some more testing on the users $search input other than just checking if its numeric. I guess this will also produce an error if the users $search input is decimal, maybe is_integer() is better?

I don't know if Laravel keeps track of max value for the primary keys, but that would be nice to check the input against, or just set a roof for max integer size to signed int4 size for searches?

**Comment by einar-johan** [comment]
I guess you could solve it something like this:

On the resource 
```php 
    public static $maxPrimaryKeySize = 2147483647;

```

and in applySearch() you append

```php 
(property_exists(get_called_class(), 'maxPrimaryKeySize') ? $search < static::$maxPrimaryKeySize : true) &&
```

Thanks for the help ;)

**Comment by chescos** [comment]
This is the same bug that is explained in #680. It got fixed in the past but was then re-introduced in a later version of Nova, see #2063. Using `PHP_INT_MAX` makes no sense in this case because the max integer value of PHP has nothing to do with the max integer value of the search column.

**Comment by chescos** [comment]
![image](https://user-images.githubusercontent.com/12296880/85434942-0fe37a00-b587-11ea-96e5-6a6f7cdcf733.png)
