### ISSUE TITLE
Relationships are loading each time for each field

### ISSUE THREAD

**Issue by adheesha23** [laravel/nova-issues#2443]
- Laravel Version: 5.8.35
- Nova Version: 2.8.0
- PHP Version: 7.2.26
- Database Driver & Version:MySQL -  5.7.28
- Operating System and Version: nginx
- Browser type and version: Chrome Latest

### Description:
Currently in Laravel Nova Action Fields, all relationships are re processed for every field. And when there are over 6000 records in the relation, its loading for each field. This is exhausting lot of memory and slowing down the admin area. Is there a way to load the relation data one time and use it for each field. Appreciate your support on this matter.

### Steps To Reproduce:
When loading over 6000 records with relationship of 1 or 2 other tables it is slowing down.

**Comment by jbrooksuk** [comment]
Sorry, but we are unable to debug your issue without a reproducible code example. Once you provide that we can open this up again.
