### ISSUE TITLE
MorphTo field does not show field name on detail.

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#2444]
Laravel Version: 5.8.37
Nova Version: 2.11.1
PHP Version: 7.2.19
Operating System and Version: Windows 10
Browser type and version: Chrome 79 64-bits

### Description:

A morphto field does not show it's field name on the detail, which means the presented information is without it's context.

```php
 $fieldsGeneric[] = Fields\MorphTo::make(ucfirst(__('owned_by')), 'ownedBy')->types([
                        \App\Nova\Supplier\Distributor::class,
                        \App\Nova\Supplier\Supplier::class,
                    ]);
```

**detail**

This results in:

Supplier: MySupplier

I was expecting someting like this:
 
Owner: **Supplier MySupplier** ór
Owner: **MySupplier (Supplier)**

**Comment by jbrooksuk** [comment]
This should be fixed in the latest release.
