### ISSUE TITLE
Pivot filed as required not working

### ISSUE THREAD

**Issue by icaroce** [laravel/nova-issues#2445]
- Laravel Version: 6.18.2
- Nova Version: 2.12.0
- PHP Version: 7.4.1
- Database Driver & Version: MySQL
- Operating System and Version: Windows Server 2012/IIS 8.5
- Browser type and version: Google Chrome 80.0.3987.132

### Description:

Set pivot fileds as required, when try to insert with empty fields, the page go to insert without check required fields
```
            BelongsToMany::make('Valores','values', Airport::class)->fields(function(){
                return [
                    Currency::make('value')->currency($this->pivot->from_currency ?? ($this->pivot->currency ?? 'USD'))->required(true),
                    Select::make('currency')->options([
                            'USD' => 'USD',
                            'EUR' => 'EUR',
                            'BRL' => 'BRL',
                            'ZAR' => 'ZAR',
                    ])->required(true),
                    Select::make('from_currency')
                        ->options([
                            'USD' => 'USD',
                            'EUR' => 'EUR',
                            'BRL' => 'BRL',
                            'ZAR' => 'ZAR',
                        ])
                        ->nullable(),
                ];
            })->required()
```

### Steps To Reproduce:

In both Resources are set the same pivot fields.

https://gfycat.com/smoothhilariousgoldfinch

**Comment by yevhenkoriakin** [comment]
And when you set default attributes in custom pivot model like this

`    protected $attributes = [
        'currency' => USD,
    ];
`

It's not working. Fields always empty. Although the default fields work in normal models.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
