### ISSUE TITLE
ServeNova middleware triggered in normal API call

### ISSUE THREAD

**Issue by arthur798** [laravel/nova-issues#2446]
- Laravel Version: 7
- Nova Version: latest
- PHP Version: 7.4
- Database Driver & Version: Mysql 5.7
- Operating System and Version: ubuntu 18.04
- Browser type and version: n/a

So our laravel application is api based, we have about 60 routes in api.php currently, however I have noticed that any request to those routes is triggering a query to ServeNova middleware. It got me wondering why is that happening as I am doing nothing in nova and surely it should only trigger when accessing nova. Could it have anything to do that nova guard is API based same as rest of the api?

See screenshot with details from telescope

https://imgur.com/qUObY8k

**Comment by davidhemphill** [comment]
The `ServeNova` middleware is pushed to the global HTTP stack and conditionally registers Nova's service provider if it's actually a Nova request.

**Comment by arthur798** [comment]
but it's not a nova request so why does it cause more struggle for requests that have nothing to do with it?

**Comment by davidhemphill** [comment]
What "struggle" does it cause?

**Comment by arthur798** [comment]
creates 2 queries which are duplicates, takes up db connection to perform them and if we are doing 30 queries with 50 concurrent users everything matters. no reason for it to do it

**Comment by davidhemphill** [comment]
The `ServeNova` middleware doesn't do any queries. 🤷‍♂ It simply loads Nova's service provider if it's a Nova request and if so, fire the `NovaServiceProviderRegistered` Event. 

For example, here's a fresh Laravel install with a fresh Nova install:

<img width="1203" alt="image" src="https://user-images.githubusercontent.com/58970/77256107-18e84680-6c3a-11ea-877c-bd46503ba8a4.png">

Notice how there's no queries.

**Comment by arthur798** [comment]
Okay but in the screenshot above it did make that request from an normal api endpoint?

**Comment by davidhemphill** [comment]
It doesn't matter. The middleware is loaded on *every* request. If `ServeNova` was doing database calls it would be there.

**Comment by arthur798** [comment]
Surely the Nova middleware should only be attached on Nova endpoints? Why is it attached anywhere else

**Comment by winter-ice** [comment]
@davidhemphill 

Same issue here.
![image](https://user-images.githubusercontent.com/24680921/81106146-a6ac9680-8f47-11ea-9e66-6d3e05f9337a.png)
![image](https://user-images.githubusercontent.com/24680921/81106210-c5ab2880-8f47-11ea-93e7-2a18d389583f.png)

In normal API call and I have not query the current user.

**Comment by arthur798** [comment]
Yeah it keeps happening to me all the time, disabling Nova hides this query

**Comment by abdomf** [comment]
@davidhemphill same issue here

**Comment by mohammedabdallah** [comment]
@davidhemphill  same issue here

**Comment by crynobone** [comment]
If you're experiencing this issue when `nova.path` is set to `/` this should have been fixed in `v3.16.3`.

However `ServeNova` will still be executed everywhere if you use above configuration with `nova.domain` set to `null`.

**Comment by jbarmanet** [comment]
Same issue here. 
May I ask for clarification @crynobone : if nova is used with default setting, installed on the same domain as the main application, and using `/nova` as path... How should be `nova.domain` set to something that is not `null` to avoid executing `ServeNova` middleware upon each api call?
