### ISSUE TITLE
VaporFile field download issues.

### ISSUE THREAD

**Issue by Medalink** [laravel/nova-issues#2447]
- Laravel Version: 7.2.1
- Nova Version: 3.1.0
- PHP Version: 7.4.
- Database Driver & Version: Mysql 8.0.11
- Operating System and Version: Laravel Vapor
- Browser type and version: Chrome 80.0.3987.149 (Official Build) (64-bit)

### Description:

I am test driving the new Laravel Nova VaporFile upload field. My file get's created within my S3 bucket with a UUID. I save the model and the UUID appears in my database. However when I go to download the file from Nova I get a 502 gateway error.

[chrome download view](https://photos.app.goo.gl/7vgGrgFvMPUvTbPt6)

I have tried to find a way to see what the server side error is but nothing shows up in the vapor logs or within flareapp.

I do not see any requests in the Chrome console or any JS errors.

I am using the field like this, nothing fancy:

`VaporFile::make('Test Vapor File')`

I tried manually putting the file to public in S3 but got the same result.

This feature is not currently documented so perhaps I am doing something wrong?

**Comment by davidhemphill** [comment]
Is the file actually getting uploaded to S3? I had problems during testing with a bucket that was not created/configured by Vapor.

**Comment by davidhemphill** [comment]
The field generally uses the same storage mechanisms as the File field and in the places it differs it's only slightly. Alternatively, if you feel like debugging more and can verify the file is actually uploaded to S3, try setting the `download` callback manually.

**Comment by Medalink** [comment]
@davidhemphill the file does get stored on S3 and I can preview/download it from there. It's the nova button to download it that is not working. I will try to make a new bucket and see where that get's me as I believe this one was made by a dev outside of vapor.

**Comment by Medalink** [comment]
@davidhemphill used a new bucket in my vapor config, deployed, tried a new file and see the get into S3 inside the new bucket. But again the download link does not work in nova after saving my model and viewing the resource.

[see screenshot](https://photos.app.goo.gl/chikupq267gDXp6b9)

**Comment by davidhemphill** [comment]
What's the error shown when hitting the route in the Network tab of the Dev Tools?
