### ISSUE TITLE
Actions button not working.

### ISSUE THREAD

**Issue by saimemre** [laravel/nova-issues#2448]
- Laravel Version: 5.8
- Nova Version: 2.0
- PHP Version: 7.2.10
- Database Driver & Version: Mysql 8.0.11
- Operating System and Version: Mac os
- Browser type and version: Crome 80.0.3

### Description:
My action buttons do not operate, they remain in the gray background.
![Screen Shot 2020-03-21 at 03 28 20](https://user-images.githubusercontent.com/1628766/77215233-14ca0500-6b24-11ea-85e5-42b7280bd168.png)

### Steps To Reproduce:
I re-created the resources with the "php artisan nova:publish
" command, but it has not changed.

Thanks.

**Comment by davidhemphill** [comment]
Update to the latest version from the 2.x major release (2.12.0).

**Comment by saimemre** [comment]
@davidhemphill 
I changed it, but it has not improved.
