### ISSUE TITLE
Trying to add a trix attachment in an Action modal closes the modal

### ISSUE THREAD

**Issue by druc** [laravel/nova-issues#2449]
- Laravel Version: 7.2.2
- Nova Version: 3.1.0
- PHP Version: 7.3.15
- Database Driver & Version:
- Operating System and Version: macOS Catalina 10.15.3
- Browser type and version: Chrome/Firefox/Safari

### Description:
If you have an action containing a Trix field, clicking the add attachment button closes the modal, making it impossible to run the action.

Video: https://www.loom.com/share/e5716d2eab584d47a5564817d87dbc3a

### Steps To Reproduce:
1. setup Trix attachments.
2. create an action with a trix field.
3. try to add an attachment and run the action.

### One way to fix it
Edit `resource/js/components/Modal.vue@51` and add a `e.isTrusted` check before closing the modal.
```
close(e) {
   if (!e.isTrusted) return false;
   
   let classArray = Array.isArray(this.classWhitelist)
        ? this.classWhitelist
        : [this.classWhitelist]
   
   // code
}
```

**Comment by RaymondAtivie** [comment]
This hasnt been fixed
