### ISSUE TITLE
relatableQuery Not work when passed a dynamic var but work in a static value

### ISSUE THREAD

**Issue by vFire** [laravel/nova-issues#2450]
- Laravel Version: 5.8.0
- Nova Version: 2.12.0
- PHP Version: 7.2.19
- Database Driver & Version: Mysql 5.7.24
- Operating System and Version: Windows7
- Browser type and version: Chrome
- Reproduction Repository: https://github.com/###/###

### Description:
In a self-relation model, I just want to exclude self from a belongTo list. When I supply the where with a static value just like number 7, it do work, but if I give it a var even the result of it exactly equal 7, it just not work.

I've test a lot, even I change the relatableQuery with relatable*ModelName*, the same problem.

I'm not sure it is a bug or something I mis-understood.

### Steps To Reproduce:

> public static function relatableQuery(NovaRequest $request, $query)
    {
        // $resource = $request->route('resource');
        $resourceId = (int)$request->route('resourceId');
        //echo 'ResourceID:'.$resourceId;
        return $query->where('id', '!=', $resourceId); // if i give it a static value 7, it do work. :(
    }

![2020-03-23_221814](https://user-images.githubusercontent.com/15304028/77326986-92c12280-6d55-11ea-87d2-eef9aec8e378.png)
I just want to exclude self from the self-belongTo field.

**Comment by davidhemphill** [comment]
You're looking for [Relatable Filtering](https://nova.laravel.com/docs/3.0/resources/authorization.html#relatable-filtering). You will need to create a method similar to this:

```php
public static function relatableCmsNodes(NovaRequest $request, $query)
{
    return $query->where('id', '!=', $request->resourceId);
}
```

**Comment by vFire** [comment]
Thank you david, I should use $request->resourceId not $request->route('resourceId').

**Comment by mrleblanc101** [comment]
That's so weird. I seem to have this issue in Nova 4.
This work:
```
return $query->where('serie_id', 2);
```
But this doesn't work:
```
if($request->get('serie')){
    $serie = \App\Models\Serie::find($request->get('serie'));
    return $query->where('serie_id', (int) $serie->id);
}
```
But `(int) $serie->id` value is `2`...
