### ISSUE TITLE
Add a snippet in Metrics documentation for name property

### ISSUE THREAD

**Issue by jacobzlogar** [laravel/nova-issues#2451]
Might be helpful for some people to have a docs snippet about defining the `name` of a metric, 
all that's required is setting `public $name = 'Metric Name';`- I would've submitted a PR directly to the documentation but i could not find an open repo.

**Comment by davidhemphill** [comment]
https://github.com/laravel/nova-docs if you want to PR this :-)

**Comment by jacobzlogar** [comment]
@davidhemphill 🤦‍♂ thanks apparently i didn't look too hard
