### ISSUE TITLE
Feature Request: Hide App Name on the header next to the search bar

### ISSUE THREAD

**Issue by abishekrsrikaanth** [laravel/nova-issues#2453]
Could you add a config to the `nova.php` to hide the App Name on the header next to the search bar? It doesn't make sense to me to show the App name on the header when there is a logo on the header to identify it. As a quick fix, setting the `name` config on `nova.php` fixes it, but that creates a new problem, it empties the `<title>` tag on the page.

**Comment by davidhemphill** [comment]
You can customize your layout to remove the site link. 

In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
