### ISSUE TITLE
Feature Request: Toasted warning class

### ISSUE THREAD

**Issue by Quiss** [laravel/nova-issues#2454]
Good afternoon, we noticed that some packages use toasted nova, we would like for you to add a `.warning` class to new release :)

<img width="721" alt="Снимок экрана 2020-03-25 в 12 13 56" src="https://user-images.githubusercontent.com/4972114/77520487-55ae7a80-6e92-11ea-9ec8-328c86c1b0ef.png">

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

Feel free to open a PR for this :)

**Comment by skoyah** [comment]
This is a great addition to the core! @Quiss I also created a package for a client app that required something similar. This might help you.

https://github.com/skoyah/nova-toasted
