### ISSUE TITLE
Can't construct new query in detailQuery() in \App\Nova\Resource override

### ISSUE THREAD

**Issue by SRaromicon** [laravel/nova-issues#2455]
- Laravel Version: 7.1.1
- Nova Version: 3.0.2
- PHP Version: 7.2.
- Database Driver & Version: mysql
- Operating System and Version: Debian 10
- Browser type and version: Google Chrome 80
- Reproduction Repository: none

### Description:
I need to reopen this issue. Because it's not possible to overwrite the detailQuery function in .
If you overwrite detailQuery in your Resource like this:

```php
    public static function detailQuery(NovaRequest $request, $query)
    {
        return $request->model()->where('dlnr','=', 1);
    }
```
The original query will be still used, if you return a different query. But it's possible to alter the original query.

```php
    public static function detailQuery(NovaRequest $request, $query)
    {
        return $query->orWhere('dlnr','=', 1);
    }
```

So the bug is in my opinion in  Laravel\Nova\Http\Controllers\ResourceShowController:
handle function should look like this:

```php
    public function handle(ResourceDetailRequest $request)
    {
        $resource = $request->newResourceWith(
            $request->newResource()->detailQuery($request, $request->findModelQuery())->firstOrFail());

        $resource->authorizeToView($request);

        return response()->json([
            'panels' => $resource->availablePanelsForDetail($request),
            'resource' => $resource->serializeForDetail($request),
        ]);
    }
````

### Steps To Reproduce:
1. Create a Resource
2. Try to return a different query from detailQuery function.

**Comment by davidhemphill** [comment]
Can you describe the use case which requires this?

**Comment by SRaromicon** [comment]
Use case is pretty simple, if you want to use uuids as primary key for example. 

But the function has also a return value, which is useless right now. This is confusing in my opinion, because the return value is never used.

**Comment by davidhemphill** [comment]
Why are you not using using a `Text` field for your IDs instead?

```php
Text::make('ID');
```

**Comment by SRaromicon** [comment]
Because the uuid is saved as binary(16) in database and the where query will fail. So i need to transform the requested id to binary before querying.
It's possible to reset the bindings and where clauses before, but it's not so clean, then returning a new query.
