### ISSUE TITLE
Can't see custom tool's updated content

### ISSUE THREAD

**Issue by huszerldani** [laravel/nova-issues#2456]
- Laravel Version: 7.3.0
- Nova Version: 3.0.0
- PHP Version: 7.3.14
- Database Driver & Version:
- Operating System and Version: Windows 10
- Browser type and version: Chrome

### Description:
I wanted to create a custom nova tool for the first time.
I created the tool's files as in the documentation. I changed the markup in the vue file and i run the npm run watch command from the tool's root folder.

I can't see any changes on the tool's nova page, it is the same as the default page(Black hole)

**Comment by huszerldani** [comment]
I just installed a fresh laravel and Nova 3.1, but the problem is still exists.

The "dist/tool.js" file shows the updated component, but I can't see the changes in the browser.

**Comment by huszerldani** [comment]
I found the solution:

https://stackoverflow.com/questions/53503521/nova-tool-not-updating

**Comment by smcnepal** [comment]
This one also not working
https://stackoverflow.com/questions/53503521/nova-tool-not-updating..
