### ISSUE TITLE
Overeager loading...?

### ISSUE THREAD

**Issue by telkins** [laravel/nova-issues#246]
I'm not yet 100% sure, but it looks like a Nova resource gets a little overeager when loading.

I have the following models *and* nova resources:
* organization
* event
* activity

An event model *belongs to* an organization model.  That is, an event has a reference to an organization via its `organization_id`.  It also always loads its activity count:
```
    /** @var array */
    protected $withCount = [
        'activities',
    ];
```

An activity model *belongs to* an event model.  That is, an activity has a reference to an event via its `event_id`.

My activity resource eager loads events:
```
    public static $with = [
        'event',
    ];
```

It also has the following field declared:
```
    public function fields(Request $request)
    {
        return [
            // ...
            BelongsTo::make('Event'),
            // ...
```

My event resource doesn't eager load anything.  It does, however, have the following *field*:
```
    public function fields(Request $request)
    {
        return [
            // ...
            BelongsTo::make('Organization'), // <-- pay attention to this for later on...
            // ...
```

When I select *an individual activity* from the Nova UI's activities page, it appears to eager load the events, as expected:
```
// from mysql log:
select `events`.*, (select count(*) from `activities` where `events`.`id` = `activities`.`event_id`) as `activities_count` from `events` order by `events`.`id` desc
```

This is good and as expected.

*However*....it then goes and individually loads the *organization* for all events...!  It looks like it has a single API call to get all of the events.  It likely does this to populate the event dropdown on the edit activity screen.

This is where I start to get a little uncertain about what's taking place, exactly.  The log records about 15 queries that look like *exactly* this:
```
`select * from `organizations` where `organizations`.`id` = 1 limit 1
```

*Then*, after a couple more queries, which appear to be in their own API call because of a query to the user table first, there are what appear to be 460 of the exact same queries:
```
`select * from `organizations` where `organizations`.`id` = 1 limit 1
```

(I should note that there are exactly 460 events in my database and only a handful of organizations.  Most events belong to one organization and a very small handful belong to a second organization.  So, a small handful of the queries likely look for organization ID = 2.)

In fact, I've confirmed that there is a call to the following URL:
```
http://homestead.test/nova-api/activities/associatable/event?current=4&first=false&search=&withTrashed=false
```

Now, this is where it gets interesting and where I believe Nova is getting overeager when loading these resources.  If I remove the following from my organization resource fields array, then I get *zero* queries for organizations:
```
    public function fields(Request $request)
    {
        return [
            // ...
            // BelongsTo::make('Organization'), // <-- removing this line makes *all* the difference
            // ...
```

So, I can see why loading an individual activity would load its event as well as all of the possible events to fill the dropdown (no...I haven't made it `searchable`...yet).  I cannot, however, see why declaring an event's fields to include a further relationship (organization) would have any impact on the situation.

I hope that this information is sufficiently clear.  While I don't mind a workaround here, I think it does reflect a real problem underneath the hood.  If I'm not mistaken, it seems like Nova is very eagerly loading all sorts of resources, even though they aren't used for anything.

I've also tried to simplify my examples here from my "real" code, so I may have made a small mistake and/or overlooked something.  I'll re-read this and simplify my "real" code a bit, too.  But, if anyone has any questions or needs more details, I'll be happy to try to provide it for them.  I'll also be happy to try some different things to see what happens.

Thanks in advance...!  :-)

**Comment by telkins** [comment]
Forgot to note that I'm on Laravel 5.6.34 and Nova 1.0.6.

**Comment by michaelchunn** [comment]
I'm seeing the same thing.  Laravel Framework 5.6.34 also

**Comment by poxin13** [comment]
Yeah same deal here. Not able to use update on a couple of my models because it runs php out of 2 GB of memory and times out. Possibly related to #112 and #56

**Comment by demency** [comment]
For me. By removing $with in model and adding $with in nova resource solve my issue.

**Comment by telkins** [comment]
@poxin13 Thx for your input.  Now that you mention it, I had one of the worst OS crashes on my MacBook Pro that I've experienced in recent years...and this was after using Nova for a few days.  Not sure if they're related, but I know switching iTerm tabs was either impossible or very, *very* slow....perhaps because of massive memory consumption...?

Anyway, I wasn't really able to troubleshoot at the time and I didn't consider that it might be related to Nova.  Looking back, I'm not so sure.

**Comment by telkins** [comment]
@demency Thanks for the suggestion.  This might be good for Nova, but what about when *not* using Nova...?  I have `$with` in my model definitions to improve the API's performance.  If I remove them to make the admin perform better, then I lose out on the actual product/service that I'm developing.  :-(

**Comment by demency** [comment]
I agree with you @telkins .

**Comment by ragingdave** [comment]
a temporary fix is to add `setEagerLoads([])` on the BelongsTo Field:resolve method ~L133. This makes it so it doesn't make the single queries, but I would assume that if you are using selectable, and use a related field in the subtitle or title, then they will come back.

**Comment by JoshStaff** [comment]
A very temporary fix to speed up development until this gets discussed / fixed is to to what @ragingdave suggested -- Override the resolve method on `Laravel\Nova\Fields\BelongsTo`

`<?php

namespace App\Nova\FieldOverrides;

use Laravel\Nova\Fields\BelongsTo as NovaBelongsTo;

class BelongsTo extends NovaBelongsTo {

    public function resolve($resource, $attribute = null)
    {
        $value = $resource->{$this->attribute}()->withoutGlobalScopes()->setEagerLoads([])->first();

        if ($value) {
            $this->belongsToId = $value->getKey();

            $this->value = $this->formatDisplayValue($value);
        }
    }
}`

**Comment by ragingdave** [comment]
This most likely relates to #112 and based on my own tests is potentially also affecting MorphTo as well

**Comment by taylorotwell** [comment]
I honestly discourage hard-coding eager loads in your Eloquent models. It generally leads to just bad situations with over-eager loading like you are describing. IMO it's better to define the eager loads when you actually need them rather than always doing it.

**Comment by telkins** [comment]
@taylorotwell Thx for the advice.  I'm not sure if you're responding to the original issue or one of the follow-up posts.  In my case, however, *I do not have any hard-coded eager loading going on in any of my Eloquent models.*  As I noted, I have eager loading in a couple of my Nova resources.  In order to make things more clear, I've removed the hard-coded eager loading in the two Nova resources and I experience the exact same thing.  In the one instance, I navigate to edit an activity and one of the Nova API request results in 465 database queries.  It's exactly like I described in the original post.

So...if weren't responding to my original post, then I guess you can ignore what I just wrote.  ;-)  If you were, however, then you should know that removing any hard-coded eager loads in Eloquent models and Nova resources does not alleviate/eliminate the problem.  The only thing that seems to eliminate the problem is to remove the `BelongsTo` relation field on the event Nova resource.  (Keep in mind, I'm editing an activity Nova resource which `BelongsTo` an event Nova resource.) . So, I'm editing an activity....it loads *all* of the possible events (465) and then, in turn, queries 465 individual organizations.  Remove the event's `BelongsTo` organization reference and the "over-eager-loading" goes away.  Of course, then the event Nova resource is incomplete.

Hope this helps.

**Comment by abordage** [comment]
I had the same problem and solution provided by @ragingdave and @JoshStaff worked for me. Thanks

**Comment by manmohanjit1** [comment]
Before this I was using:
https://github.com/treeStoneIT/belongs-to-field

However, that caused my model observers to not be able to access relationships at all. Even with load() or loadMissing(). I had to call the relationship and manually load it.

@JoshStaff method works, my model observers now have access to the relationships. I ended up extending the BelongsTo field and just overriding it.

**Comment by dkulyk** [comment]
This has been fixed and will be included in the next release.

**Comment by fedeisas** [comment]
@dkulyk was this ever released? Can't find any mention of it on the release log. Thanks!

**Comment by timcv** [comment]
Its merged: https://github.com/laravel/nova/pull/151

I can gain access to the nova repo by logging in to nova.laravel.com and connecting your github account.
