### ISSUE TITLE
The actions method is run once for each resource on an index page, despite only being needed once in total

### ISSUE THREAD

**Issue by natbentley** [laravel/nova-issues#2461]
- Laravel Version: 6.18.3
- Nova Version: 2.12.0
- PHP Version: 7.4.1
- Database Driver & Version: MySQL 5.7

### Description:

At the moment it appears that the actions method of a resource is run once on a listing, and again for each resource in that listing (i.e. 1 + 25 on a standard Nova resource response), leading to poor performance and frequently duplicated queries, etc, despite only needing to be run once.

### Steps To Reproduce:

- Create a Nova Resource
- Fill that resource with dummy data
- Add a debug to the actions method on your resource (e.g. as per image below)

<img width="477" alt="Screenshot 2020-03-27 at 21 23 07" src="https://user-images.githubusercontent.com/37216142/77801674-391c6900-7071-11ea-8625-570451c33f17.png">

- View index page of resource
- Check debug of the resource nova API call

For example, I have a `BulkAllocateCredits` action that has a `fields` method that performs a query of available `Credit`s.  On a result set of 100 customers/page, this lookup is run once for each resource (`GET nova-api/{resource}`), as well as once for the actions call (`GET nova-api/{resource}/actions`), even though they'll be the same for every resource - 100 more lookups than needed, making for a very slow response.

Whilst I can cache this query, it seems odd that the action is loaded multiple times when it's only needed once.

Adding the following code stops the actions being loaded for each resource, but is a hacky fix:

 ```
   public function actions(Request $request)
    {
        if($this->id != null) { return []; }
```

**Comment by natbentley** [comment]
Adding to the above, it actually appears the call for available actions on line `358` of `laravel/nova/src/Resource.php` can be commented out without any ill effects - actions can still be run on the index page, but there's no longer a performance hit.

<img width="824" alt="Screenshot 2020-03-28 at 14 19 44" src="https://user-images.githubusercontent.com/37216142/77825166-76c7d300-70ff-11ea-9c9f-538c0aa3f962.png">

Or am I missing something fundamental?

**Comment by mavericksthinker** [comment]
@natbentley 
<img width="842" alt="Screen Shot 2020-03-29 at 12 01 49 PM" src="https://user-images.githubusercontent.com/38578359/77840831-b6e98d00-71b5-11ea-8008-4d352574bfdd.png">

This might give an insight about your issue and also a way to avoid it if you dont need

**Comment by natbentley** [comment]
Hi @mavericksthinker that's useful to know, however even with ->exceptOnTableRow() added, the Actions are still created and the fields() method run, resulting in a large volume of additional requests and data returned.

In my specific case, it's the difference between a <900ms response and a 5+ second response, and a payload of <25kb vs >250kb.

**Comment by mavericksthinker** [comment]
@natbentley I agree as I mentioned there should be an option mentioned to avoid calling for available option if an user uses exceptOnTableRow. Or if you desperately want it now just override the function on your side until any such is implementation is included in the core

**Comment by davidhemphill** [comment]
I think you'll have to cache the query here. There's use-cases which require us to not use a cached version of the actions on each resource.

**Comment by natbentley** [comment]
Thanks @mavericksthinker, @jbrooksuk and @davidhemphill - will continue to apply my fix until it's hopefully resolved in a later release.  Appreciate all the time and feedback.

**Comment by u12206050** [comment]
I see this issue is closed but have the same issue now. It is a huge penalty including to many actions especially ones that are a bit bigger since they are built for each resource row on the index page. Any updates on when this will be optimised?

**Comment by crynobone** [comment]
> Any updates on when this will be optimised?

No plan to change, @davidhemphill suggestion still the recommended approach.
