### ISSUE TITLE
Currency Field do not show proper currency locale for computed field

### ISSUE THREAD

**Issue by tititorn** [laravel/nova-issues#2463]
- Laravel Version: 7.3.0
- Nova Version: 3.1.0
- PHP Version: 7.2.24
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:
Currency Field do not show proper currency locale for computed field

### Steps To Reproduce:
Currency::make('Price'); /* Correctly Formatted */

Currency::make('Discounted Price', function() { return $this->price * 0.5; } /* Incorrect */

**Comment by jbrooksuk** [comment]
Can you please try this in v3.2.0?
