### ISSUE TITLE
Markdown field doesn't display correctly on index page

### ISSUE THREAD

**Issue by simonhunt** [laravel/nova-issues#2464]
- Laravel Version: 7.2.2
- Nova Version: 3.1.0
- PHP Version: 7.3.16
- Database Driver & Version: MySQL 14.14
- Operating System and Version: Linux Mint 19.3
- Browser type and version: Chrome 80 on Linux
- Reproduction Repository: N/A

### Description:
When showing a Markdown field on an index page using showOnIndex() the field preview includes the title of the field and also adds a grey line below the field entry (unlike other fields).

### Steps To Reproduce:
Create a Markdown field and add to the index page using showOnIndex().

![Laravel Nova Markdown Field Bug](https://user-images.githubusercontent.com/2714455/77837093-832a4b00-7154-11ea-90eb-d43f27ded64c.png)

**Comment by jbrooksuk** [comment]
Markdown fields are not meant to be shown on the index.

**Comment by cjholowatyj** [comment]
Just going to leave a comment here for others in the same boat as me to react to in hope others want the same thing...

We want Markdown on our index pages! (And we want to be able to use it within Stacks as well!

Please please please implement this support! (i.e. I use Markdown fields for many of my description columns on my eloquent models, and being able to stack a name field as a title and a markdown field as small content beneath it is huge!)

**Comment by cjholowatyj** [comment]
Just going to leave a comment here for others in the same boat as me to react to in hope others want the same thing...

We want Markdown on our index pages! (And we want to be able to use it within Stacks as well!

Please please please implement this support! (i.e. I use Markdown fields for many of my description columns on my eloquent models, and being able to stack a name field as a title and a markdown field as small content beneath it is huge!)
