### ISSUE TITLE
ValueMetric 0 result % increases

### ISSUE THREAD

**Issue by iamoat** [laravel/nova-issues#2465]
- Laravel Version: 7.3.0
- Nova Version: 3.1.0
- PHP Version: 7.2
- Database Driver & Version:
- Operating System and Version: Ubuntu 18.04
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:

ValueMetric doesn't show percentage change when the current value is equal to 0. 

### Steps To Reproduce:
Set $previous value to non-zero. 
Set $result value to 0.

### Solution

Update increaseOrDecrease method in ValueMetric.vue as follows. 

```js
    increaseOrDecrease() {
      if (this.previous == 0 || this.previous == null || (this.value == 0 && this.zeroResult == false))
        return 0

      return (((this.value - this.previous) / this.previous) * 100).toFixed(2)
    },
```

**Comment by jbrooksuk** [comment]
Anything to 0 is always a 100% increase/decrease, so this kind of feels redundant.
