### ISSUE TITLE
Impossible to read facade/ignition exception views

### ISSUE THREAD

**Issue by tanthammar** [laravel/nova-issues#2467]
- Laravel Version: 7.3
- Nova Version: 3.1.0

### Description:
When there is an exception Laravel tries to show the facade/ignition view. It is impossible to read it with the default Nova theme.

<img width="316" alt="Skärmklipp 2020-03-31 15 05 04" src="https://user-images.githubusercontent.com/21239634/78029883-9100eb80-7361-11ea-82dc-ceef570a0323.png">

**Comment by davidhemphill** [comment]
This is a pretty common issue with Ignition. Unfortunately there's not much we can do to fix it on the Nova end of things.
