### ISSUE TITLE
Required_if error messaging more specific

### ISSUE THREAD

**Issue by camaech** [laravel/nova-issues#2468]
- Nova Version: 2.12.0

### Description:
If I add a specific validation rule to my resource, I'd like to be able to add a more specific validation rule.
`->rules('required_if:type,==,4')`
 
If I add a validation message like this, it doesn't work.
`'featured_image' => [
        'required_if:type,==,4' => 'The :attribute field is required when :other is Blog.',
  ],`

Only something more generic like this works.
`'featured_image' => [
            'required_if' => 'The :attribute field is required when :other is Blog.',
        ],`

Is there a way to be more specific about the validation messaging in Laravel Nova?

**Comment by davidhemphill** [comment]
Look into using Laravel's Custom Validation Rules: https://laravel.com/docs/5.8/validation#custom-validation-rules

**Comment by adrianthedev** [comment]
Check out https://github.com/laravel/nova-issues/issues/2420#issuecomment-607769014
