### ISSUE TITLE
File fields do not show on Index

### ISSUE THREAD

**Issue by p0nt** [laravel/nova-issues#2469]
It seems file fields are not showing up on the index, it would be great if files could be downloadable on the index as well apart from through the view.

Currently I fix this hard coded from the public directory but that is a security risk because if people know the URL they can download files directly from a path.

**Comment by p0nt** [comment]
![Screenshot 2020-03-31 at 16 32 06](https://user-images.githubusercontent.com/25501135/78038467-2ce42480-736d-11ea-8b9f-3b7396944bb6.png)

**Comment by davidhemphill** [comment]
You can override this by calling the `showOnIndex` method. No plans to make file fields visible from the index at this time.
