### ISSUE TITLE
Unable to allow attach{Model} whilst disallowing create on BelongsToMany relationship

### ISSUE THREAD

**Issue by bencounsell** [laravel/nova-issues#247]
I want to allow the attachment of a BelongsToMany field, but at the same time disallow creation of the BelongsToMany model by certain users.

I have the following setup:

**Models**
- Product
- Category
- Product belongs to many categories.

I am using Laravel Policy classes to grant/deny permissions on both models. I have read the docs on granting permissions for relationships - using the `attach{Model}` and `detach{Model}` works as expected.

I run into trouble as soon as I create a CategoryPolicy and return false from `create` method — this removes the "Attach Category" button from the Product details page.

I don't want all users to create new Categories (only admins can do that). However, all users should be allowed to attach existing categories to products.

**Policies**
ProductPolicy.php

```
    public function attachCategory(User $user, Product $product, Category $category)
    {
        return true;
    }

    public function detachCategory(User $user, Product $product, Category $category)
    {
        return true;
    }
```

CategoryPolicy.php

```
    public function create(User $user)
    {
        return $user->isAdmin();
    }
```

This restricts the creation of categories to only admin users — however, it stops the ability for all users to attach and detach categories.

Returning true from the CategoryPolicy's create method brings the "Attach Category" functionality back, but obviously allows categories to be created by anyone.

I know I could add a layer of validation to the Category creation, to only allows a new category to be saved by certain users, however that would still allow any user access to the category creation form.

Is there a way to only allow the creation of categories by certain users, but still allow the attachment of categories by any user?

**Comment by bayareawebpro** [comment]
2nd on this, having the same issue.

**Comment by jobcerto** [comment]
After a while, in the latest release (and old ones) 1.0.7, i notice that there's none of the componentes linked with creation or index pages for belongs to many

// Belongs To Field...
Vue.component('index-belongs-to-field', require('./components/Index/BelongsToField.vue'))
Vue.component('detail-belongs-to-field', require('./components/Detail/BelongsToField.vue'))
Vue.component('form-belongs-to-field', require('./components/Form/BelongsToField.vue'))

// Belongs To Many Field...
Vue.component('detail-belongs-to-many-field', require('./components/Detail/BelongsToManyField.vue'))

**Comment by bencounsell** [comment]
Pretty sure this is a dupe of #111

**Comment by taylorotwell** [comment]
Fixed in upcoming release.
