### ISSUE TITLE
Polymorphic relations no longer display properly

### ISSUE THREAD

**Issue by crynobone** [laravel/nova-issues#2470]
- Laravel Version: 7.4.0
- Nova Version: 3.2.0
- PHP Version: 7.4.3
- Database Driver & Version: MySQL 5.7

### Description:

Polymorphic relations no longer visible on resource index and detail.

<img width="1396" alt="Screenshot 2020-04-02 at 12 22 52 PM" src="https://user-images.githubusercontent.com/172966/78210741-b1ee4b80-74dd-11ea-9c65-1102d636a4e4.png">

### Steps To Reproduce:

Update nova to 3.2.0.

**Comment by jnorms** [comment]
I have the same problem!

**Comment by davidhemphill** [comment]
Fixed via https://github.com/laravel/nova/pull/848

**Comment by equinoxmatt** [comment]
@davidhemphill I am encountering this issue in v2.12.0, will the #848 fix (applied to v3.2.1) be applied to the v2?
