### ISSUE TITLE
Custom Action Buttons on Form

### ISSUE THREAD

**Issue by techdaddies-kevin** [laravel/nova-issues#2471]
It would be fantastic to have the ability to customize the action buttons shown at the bottom of the resource form. Right now we have `Create`, `Create and Add Another` but those two buttons don't fit all circumstances. For instance, we have a client request to add a `Create and Copy` button to allow them to quickly create very similar resources. Right now, I don't see any way to achieve this. I feel like this could be useful for many different types of actions. For instance, when creating a user, a `Create and Send Password Reset Email` button. Or when creating a new Order in an e-commerce shop a `Create order and send confirmation`, etc...This would be a very useful addition for quite a few use cases.

**Comment by davidhemphill** [comment]
I understand what you're saying. This is currently possible (although with a slightly different implementation) like so:

```php
public function fields(Request $request)
{
    $this->when($request->isCreateOrAttachRequest(), function () use ($request) {
        return Panel::make('After Save Actions', [
            Select::make('After Save')->options([
                'send_welcome_email' => 'Send welcome email',
                'send_activation_email' => 'Send activation email',
            ])->fillUsing(function () use ($request) {
                return function () use ($request) {
                    if ($request->after_save == 'send_welcome_email') {
                        return dispatch(new SendWelcomeEmail($this->resource));
                    }
                };
            }),
        ]);
    }),
}
```

This will create a panel on the create view with a field allowing you to select a post-save job to run.

**Comment by techdaddies-kevin** [comment]
Thanks for the update. That's a really nifty implementation, but from a UI perspective, it's very...blah. I still am of the opinion that being able to add custom buttons/actions should be possible. Sometimes, you really do want to do something other than the standard create or update, and selecting that something from a dropdown that's separate from the button grouping is really ugly and non-intuitive. If it's an action that happens when you click one of those buttons, it should be near those buttons. 

I appreciate your help in trying to find an existing solution. But please consider this a formal feature request - Being able to control the buttons on a resource form will be an invaluable feature.

**Comment by bernhardh** [comment]
@techdaddies-kevin 
Sorry for a none topic related question: How do you hide the detail view?

**Comment by Broutard** [comment]
Agree with @techdaddies-kevin, It would be very awsome to be able to customize the save buttons.
Thanks to consider this request.
