### ISSUE TITLE
KeyValue field error

### ISSUE THREAD

**Issue by lifeblood** [laravel/nova-issues#2474]
- Laravel Version: 7.4.0
- Nova Version: 3.2
- PHP Version: 7.4
- Database Driver & Version: MySQL 5.7.29
- Operating System and Version: Ubuntu 18.04.4 LTS 
- Browser type and version: chrome
- Reproduction Repository: -

### Description:

insert options field value {"dubbo": "1.3.5"}
![image](https://user-images.githubusercontent.com/3621748/78468630-4bbb3000-774c-11ea-948c-881b5bb31ed5.png)

result:
![image](https://user-images.githubusercontent.com/3621748/78468349-c767ad80-7749-11ea-9e63-87d45ff3308f.png)
 
### Steps To Reproduce:
````
KeyValue::make('Options')->rules('json'),
````

**Comment by jbrooksuk** [comment]
Your `options` field needs to be cast to an array within your Model.

**Comment by lifeblood** [comment]
NICE
````
    protected $casts = [
        'options' => 'collection',
    ];
````

**Comment by davidhemphill** [comment]
lol
