### ISSUE TITLE
Readonly Image field allows deleting existing uploaded image.

### ISSUE THREAD

**Issue by abishekrsrikaanth** [laravel/nova-issues#2478]
- Laravel Version: 7.4.0
- Nova Version: 3.2.1
- PHP Version: 7.4.3
- Database Driver & Version: MySQL
- Operating System and Version: macOS Catalina
- Browser type and version: Brave v1.5.113
- Reproduction Repository: https://github.com/laravel/nova

### Description:
Readonly Image field allows deleting the image. When an Image field on the resource is set to `readonly`, the button to upload a new file is disabled, but the link button to `delete` the existing image is not disabled.

### Steps To Reproduce:
On a resource, add an `Image` field and set it to readonly

```
Image::make('Image', 'image_url')->preview(function ($url) {
                return $url;
            })->thumbnail(function ($url) {
                return $url;
            })->readonly(),
```

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
