### ISSUE TITLE
Nova action can not get resourceId in index resources. but can get in detail resources.

### ISSUE THREAD

**Issue by lifeblood** [laravel/nova-issues#2479]
-Laravel Version: 7.4.0
-Nova Version: 3.2.1
-PHP Version: 7.4
-Database Driver & Version: MySQL 5.7.29
-Operating System and Version: Ubuntu 18.04.4 LTS
-Browser type and version: chrome
-Reproduction Repository: -

### Description:
Nova action can not get resourceId in index resources. but can get in detail resources.
````
public function fields()
    {
       $res = Project::findOrFail(request()->resourceId);
        return [
            Textarea::make('Remark')->withMeta(["value" => $res->remark]),
        ];
    }
````

**Comment by davidhemphill** [comment]
There's no `resourceId` available in the request because it's an index request, which is not a view for a single model. If you're trying to utilize the current resource's ID (detail view) on a related index view, you need to use the `$request->resourceId` parameter and check for its existence.

**Comment by lifeblood** [comment]
Is it possible to put **resourceId** in current CHECKBOX label?
![image](https://user-images.githubusercontent.com/3621748/78620251-09136800-78b2-11ea-8b72-345850cdb75b.png)

**Comment by lukesnowden** [comment]
```javascript
this.$parent.resource.id.value
```

**Comment by ConsoleTVs** [comment]
I understand this is an "Index" view, but the part we're rendering is inside the iteration of each resource. There are components that don't have a `value` and require additional logic to be handled using the resource ID.

The solution proposed by @lukesnowden works but looks like a hack. Is there a technical reason to why we can't have access to that resource ID that we're iterating over the table?

**Comment by Sentoki** [comment]
At end of the day it looks weird. We have same index view, we can for example have both simple action and inline action on same page, and regular action works fine, but inline action, several pixels aside, don't.

**Comment by ghRocam** [comment]
This resourceId is a must in the actions handle function, from what I can see, many people is requesting this behavior.  Sometimes we only need to target a single user for an action and not to iterate the entire resources, thus the inline action doesnt make much sense.

**Comment by ziming** [comment]
Agree, it would be very nice if we can get the current record on actions that is performed on showOnDetail or showInline where the action apply to a single record.

**Comment by crynobone** [comment]
@ziming `fields()` now has `NovaRequest` as parameter, you can get the resourceId or retrieve the model via the request instance.

**Comment by ghRocam** [comment]
@crynobone Thats only for the details page, with the ->onlyOnIndex() function in the resource and in the action file I tried:

```
    public function fields(NovaRequest $request)
    {
        Log::error('fields: ', [$request->fields(), $request->fields]);
        return [
            Text::make('Title', 'term')
        ];
    }
```

No success, or do I miss something ?

**Comment by ziming** [comment]
@crynobone I just tested, it work in detail view but not on showInline view.

It would be really great if $request->resourceId is avaliable for showInline (table row) too!

**Comment by rameshguthulakkd** [comment]
It would be easy if we get the current record ID for action closure
