### ISSUE TITLE
Resources menu heading still shows when there aren't any resources

### ISSUE THREAD

**Issue by JoshMoreno** [laravel/nova-issues#2480]
- Laravel Version: 7.3.0
- Nova Version: 3.2.1
- PHP Version: 7.3.16

### Description:
"Resources" in the sidebar still shows when there are 0 resources after filtering through `$resource::displayInNavigation`.

The issue is in the view `resources/navigation.blade.php`. It's calling `\Laravel\Nova\Nova::availableResources(request())` which only filters out based on `$resource::availableForNavigation($request)`. 

In my case a 3rd party package has `$displayInNavigation` set to `false`, but never overrode `availableForNavigation` which returns true by default.

In `resources/navigation.blade.php`

```diff
-@if (count(\Laravel\Nova\Nova::availableResources(request())))
+@if ($navigation->isNotEmpty())
```

This makes more sense since further down in the view we're looping over `$navigation`.

**Comment by jbrooksuk** [comment]
Out of interest, why would you hide all resources? Just to use the dashboard?

**Comment by JoshMoreno** [comment]
Yea just the dashboard. For this project the client wants the user to fill out a form, which then grants them access to other models/resources. But since he only wants the user to fill out the form once  he doesn’t want the form resource showing in the sidebar and just wants a link to view their submission on the dashboard. So when the user first signs in they end up seeing the “Resources” heading when there aren’t any resources they have access to yet.
