### ISSUE TITLE
"Showing / Hiding Fields" no longer prevent data from being accessed only shown

### ISSUE THREAD

**Issue by bilfeldt** [laravel/nova-issues#2482]
- Laravel Version: 7.4.0
- Nova Version: 3.2.0 / 3.2.1
- PHP Version: 7.4.3
- Database Driver & Version: MySQL 8
- Operating System and Version: macOS 10.15.3
- Browser type and version: Chrome Version 80.0.3987.116 (Official Build) (64-bit)
- Reproduction Repository: -

### Description:
As of Laravel Nova 3.2.0 (also in 3.2.1) then a fields "Showing / Hiding Fields" feature like `exceptOnForm()` and `onlyOnIndex()` no longer ensures that the data is not accessed when it should not be shown. Meaning that a field that should only be shown on the index page is also loaded on the create page.

This can cause problems when a field use an accessor that requires certain data to be set (like relationships). Of cause the accessor can be made "safe" by implementing fallback like `optional()` but it seems to be a newly introduced bug that this data is even fetched.

### Steps To Reproduce:

Insert an accessor on the `Post` model which access a field on a related resource:

#### Setup `Post` model
```php
/**
 * Using this attribute require eager loading of the relationships `author`.
 *
 * @return string
 */
public function getTestAttribute(): string
{
    return $this->author->id; // This will fail if no author is associated with the Post
}
```
The `Post` model belongsTo an author:
```php
public function author(): \Illuminate\Database\Eloquent\Relations\BelongsTo
{
    return $this->belongsTo(Author::class);
}
```

#### Setup `Post` Nova resource
Now the Nova resource should use this attribute like so:

```php
Text::make('Test')
    ->onlyOnIndex(), // This should (and did up until Nova 3.2.0) avoid loading of this field on all pages except the index page.
```

#### Expected behavior
Going to Nova and creating a new resource should not cause any problems since the `test` attribute should never be loaded.

#### Actual behavior
Going into Nova and loading the create page causes an exception:
```
Trying to get property 'id' of non-object
```
With the following stack trace:
```
/Users/anders/Valet/demo/app/Models/Post.php:XX
--
/Users/anders/Valet/demo/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:466
/Users/anders/Valet/demo/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:1402
/Users/anders/Valet/demo/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:380
/Users/anders/Valet/demo/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:359
/Users/anders/Valet/demo/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1590
/Users/anders/Valet/demo/vendor/laravel/framework/src/Illuminate/Support/Arr.php:148
/Users/anders/Valet/demo/vendor/laravel/framework/src/Illuminate/Support/helpers.php:162
/Users/anders/Valet/demo/vendor/laravel/nova/src/Fields/Field.php:263
/Users/anders/Valet/demo/vendor/laravel/nova/src/Fields/Field.php:246
/Users/anders/Valet/demo/vendor/laravel/nova/src/Fields/FieldCollection.php:51
/Users/anders/Valet/demo/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php:178
/Users/anders/Valet/demo/vendor/laravel/nova/src/Fields/FieldCollection.php:53
/Users/anders/Valet/demo/vendor/laravel/nova/src/ResolvesFields.php:306
/Users/anders/Valet/demo/vendor/laravel/nova/src/ResolvesFields.php:290
/Users/anders/Valet/demo/vendor/laravel/nova/src/ResolvesFields.php:149
/Users/anders/Valet/demo/vendor/laravel/nova/src/ResolvesFields.php:174
/Users/anders/Valet/demo/vendor/laravel/nova/src/Http/Controllers/CreationFieldController.php:23
```

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
