### ISSUE TITLE
Using Nova 2.0, how can we directly upload to S3?

### ISSUE THREAD

**Issue by aligajani** [laravel/nova-issues#2484]
- Laravel Version: 6.18
- Nova Version: 2.x
- PHP Version: 7.3
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:
 ```
 File::make('Information Memorandum File', 'information_memorandum_attachment_full_document_file')
                ->help('Please ensure file is under 20000kb')
                ->rules("file", "max:20000")
                ->disk('s3')
                ->path('tmp')
                ->deletable(false)
                ->disableDownload()
                ->onlyOnForms(),
```

**Comment by jbrooksuk** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](https://larachat.co/).

**Comment by aligajani** [comment]
@jbrooksuk  I did already, but its not very much active. I would appreciate any guidance James.

**Comment by davidhemphill** [comment]
Pro license holders may submit support requests to nova@laravel.com or by using the support widget on http://nova.laravel.com. 😃

But I will tell you, Nova doesn't currently have a way to upload a file directly to S3 unless you're using the `VaporFile` field. Doing so would mean we'd have to create adapters for each type of Filesystem Laravel supports, which we don't plan on doing yet.

**Comment by ahmedkandel** [comment]
@aligajani I have created a tool to directly upload files to S3 please check at https://github.com/ahmedkandel/nova-s3-multipart-upload
