### ISSUE TITLE
Add help text to panels

### ISSUE THREAD

**Issue by aarreedd** [laravel/nova-issues#2485]
It would be great if you can add help text to a panel to describe a group of fields. 

    (new Panel('Address Information', $this->addressFields()))
        ->help('Help text that is displayed above the panel.'),

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by kamilkozak** [comment]
How to use it with relationship fields?
