### ISSUE TITLE
Change button text depending on view

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#2486]
Client is requesting a different button text for the index and create. Unfortunatly the button text is identical for both index and create views (**New :resource**).

Would be nice to be able to change the button text depending on what you are doing (index, detail, update, create).

For example:

![supplier-index](https://user-images.githubusercontent.com/5418196/78791419-229ad980-79b0-11ea-9d06-8857c8b66daa.jpg)

On the index view a button with **New :resource**

![supplier-new](https://user-images.githubusercontent.com/5418196/78791474-347c7c80-79b0-11ea-9037-cf9e543a4f48.jpg)

And when a resource is created **New :resource & Back**

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
