### ISSUE TITLE
full-width-content no working

### ISSUE THREAD

**Issue by socramjunio2** [laravel/nova-issues#2487]
Fields support full_width_content but unfortunately they are not enabled.

Do you have any idea when they will qualify?

**Comment by davidhemphill** [comment]
The full-width setting is available only for certain core Nova fields to maintain consistent design, and is also available as an API for any custom first-party or third-party fields. There's no plans make this a user-configurable setting.

**Comment by Aseksas** [comment]
This update also for us be very useful. Currently now we overwrite all fields for that... Also if label not set, remove label html from element. 

With this feature we can easy split Panels extended object into multiple columns per line, it helps with multiple fields a lot...
