### ISSUE TITLE
Exact or Text Filter Feature Request

### ISSUE THREAD

**Issue by ziming** [laravel/nova-issues#2488]
Currently, there are only Select, Boolean and Date Filter

I believe we can benefit greatly with a new filter type

Let's say I want to filter by user_id of 5

While it's true that I can use the search feature. There are likely other id columns as well as say many user_ids that has 5 such as 125, 523, 58...

If we can have a filter type where i just take in a text field value and compare, it will be much easier.

Currently select filter requires pre-defined options, boolean is checkboxes, while date filter is for dates values only.

I feel this is a deeply needed filter. Please consider.

Thank you.

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by MannikJ** [comment]
Related to #1750
