### ISSUE TITLE
Error when install latest laravel 7.x and Nova 3.3.0

### ISSUE THREAD

**Issue by thienkimlove** [laravel/nova-issues#2489]
- Laravel Version: 7.3
- Nova Version: 3.3.0
- PHP Version: 7.3
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:
Failed to run php artisan nova:install with message

```
File does not exist at path /Users/tieungao/Codes/php/chinav2/vendor/laravel/nova/src/Console/stubs/nova/resource.stub.

  at vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:52
    48|         if ($this->isFile($path)) {
    49|             return $lock ? $this->sharedGet($path) : file_get_contents($path);
    50|         }
    51| 
  > 52|         throw new FileNotFoundException("File does not exist at path {$path}.");
```

### Steps To Reproduce:

1. Install latest Laravel

`composer create-project --prefer-dist laravel/laravel chinav2`

2. Add to `composer.json`

`"laravel/nova": "~3.0"`

```
"repositories": [
        {
            "type": "composer",
            "url": "https://nova.laravel.com"
        }
    ]
```
Run `composer update` and `php artisan nova:install` got error.

**Comment by jbrooksuk** [comment]
This is now fixed in v3.3.2
