### ISSUE TITLE
Populating error morphTo

### ISSUE THREAD

**Issue by franzdumfart** [laravel/nova-issues#249]
MorphTo-field works like a charm but populating the inputs when editing causing problems. Maybe it has something to do with using the build in `morphMap()` method in `AppServiceProvider.php`. The relation field is empty, no console errors.

The relation itself seems to work because the index-view shows correct data.

![screen shot 2018-08-27 at 16 49 15](https://user-images.githubusercontent.com/1145410/44666657-29621c00-aa19-11e8-97a4-ff6c0b604e9f.png)

**Comment by michaelchunn** [comment]
The Actionable trait logic does not honor the the morphMap() method in AppServiceProvider.php either.
