### ISSUE TITLE
searchable on BelongsTo filed dose not work, not returning any items

### ISSUE THREAD

**Issue by osamaAbdullah** [laravel/nova-issues#2490]
`BelongsTo::make('customer', 'customer', Customer::class)
				->rules('required')
				->searchable(),`

### it does send get request to 
[mydomain]/nova-api/orders/associatable/customer?first=false&search=eml&withTrashed=false&viaResource=&viaResourceId=&viaRelationship=

but nothing it returned {"resources":[],"softDeletes":false,"withTrashed":false}

**Comment by davidhemphill** [comment]
"Blowing up" doesn't tell us what's going wrong. Please post a full example of how to show your error, along with any error messages you receive. `searchable` is working normally (we have lots of automated tests verifying this), so it's likely a user configuration issue.

**Comment by osamaAbdullah** [comment]
**### I have two models first one is Customers**

`<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    protected $guarded = [];

    public function notes()
	{
		return $this->hasMany(Note::class);
	}

}`


` Schema::create('customers', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->timestamps();
        });`

**### and it's corresponding nova resource**

`<?php

namespace App\Nova;

use Illuminate\Http\Request;
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Fields\Text;
use Laravel\Nova\Http\Requests\NovaRequest;

class Customer extends Resource
{
    
    public static $model = \App\Customer::class;

    public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),

			Text::make('name'),
        ];
    }
}
`

**### And here is the second one Note**

`<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Note extends Model
{
    protected $guarded = [];

    public function customer()
	{
		return $this->belongsTo(Customer::class);
	}
}
`

`Schema::create('notes', function (Blueprint $table) {
            $table->id();
            $table->text('body');
            $table->unsignedBigInteger('customer_id');
            $table->timestamps();
        });`

**### and it's coresponding nova resource** 

`<?php

namespace App\Nova;

use Illuminate\Http\Request;
use Laravel\Nova\Fields\BelongsTo;
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Fields\Trix;
use Laravel\Nova\Http\Requests\NovaRequest;

class Note extends Resource
{
    public static $model = \App\Note::class;

    public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),

			Trix::make('body'),

			BelongsTo::make('customer', 'customer', Customer::class)
				->searchable(),
        ];
    }
}
`

![image](https://user-images.githubusercontent.com/26807223/79144407-99c4d900-7dc7-11ea-9bae-9d8c1e987c94.png)
 this is a screenshot it's not returning any thing 

it sends a request with ajax  but nothing is returned

![image](https://user-images.githubusercontent.com/26807223/79145245-ff659500-7dc8-11ea-9a71-70643c219253.png)

this is the screenshot of sent request


how ever i tried the exact same process on to other models for tests With User and Post and **searchable** workers very fine there what is happning!!!

**Comment by davidhemphill** [comment]
Your example doesn't define any [searchable columns](https://nova.laravel.com/docs/3.0/search/global-search.html#searchable-columns) in your `Resource` file.

**Comment by osamaAbdullah** [comment]
i thought **searchable columns** are only for searching in index page.
thank you a lot i appreciate it.
