### ISSUE TITLE
Code field has a weird fixed height

### ISSUE THREAD

**Issue by milewski** [laravel/nova-issues#2491]
- Laravel Version: 7.5
- Nova Version: 3.3.2

### Description:

Hi Latest version of nova made the Code field looks terrible:

Now: 
![image](https://user-images.githubusercontent.com/2874967/78962442-ad054980-7b26-11ea-9dd8-5800e0a9c26a.png)

Before:

![image](https://user-images.githubusercontent.com/2874967/78962506-d920ca80-7b26-11ea-9a74-41f36000b139.png)

**Comment by davidhemphill** [comment]
We fixed a performance issue with `Code` fields in v3.3.0. To get the field to the height you'd like, you now have to either set an explicit height with the `height` method, set the field to automatically size with the `autoHeight` method, or set the field to 100% of its contents using the `fullHeight` method:

<img width="584" alt="image" src="https://user-images.githubusercontent.com/58970/79010424-8bf12880-7b27-11ea-8d54-a80877edc0de.png">

**Comment by chescos** [comment]
@davidhemphill which of those height settings results in bad performance?

**Comment by davidhemphill** [comment]
The performance issue was in the `Code` field's underlying Codemirror JavaScript component. On long documents, when set to infinity height with a lot of content, the field takes a really long time to render.
