### ISSUE TITLE
SoftDelete Trashed action missing when no entries found

### ISSUE THREAD

**Issue by duckzland** [laravel/nova-issues#2492]
- Laravel Version: 7.4.0
- Nova Version: 3.1.0
- PHP Version: 7.4.4
- Database Driver & Version: mysql 14.14
- Operating System and Version: Ubuntu 18.04
- Browser type and version: any
- Reproduction Repository: none

### Description:
The Trashed action box (as in the screenshot) is missing when there are no "not soft deleted" entries even though there are "soft deleted" in the database.

### Steps To Reproduce:
1. Create Models with softdeleted capability
2. Create Nova resources for the models
3. Create a single entry for the model via nova (at this point the Trashed action will show)
4. soft delete the entry
5. At this point the Trashed action will not show, thus user cannot Force delete the last soft deleted entry

**Thrashed visible when there is at least 1 entry at the database**
![Screenshot_2020-04-10 Engage hub](https://user-images.githubusercontent.com/1064954/78963259-87c60a80-7b29-11ea-84cb-1efa5354c580.png)

**Thrashed is not visible where there is 1 "soft deleted" entry at the database but 0 "not soft deleted" entry**
![Screenshot_2020-04-10 Engage hub(1)](https://user-images.githubusercontent.com/1064954/78963248-81379300-7b29-11ea-9a4a-62ff60974b85.png)

**Comment by kieran-dpp** [comment]
Causing us problems too, please can this be resolved quickly.
This is also an issue when searching a resource returns 0 results, you have to clear the search of the resource and then you can see the trashed filter.

**Comment by Athuli7** [comment]
Facing this issue.

**Comment by chrispage1** [comment]
Same again running Nova 3.6.

**Comment by chrispage1** [comment]
A little bit more digging and the culprit is the `authorizedToRestoreAnyResources` computed property within `resources/js/views/Index.vue`.

Ultimately, it calculates whether the value is true or false by grabbing the first resource and checking the resources `authorizedToRestore` flag. Of course, when there are no resources here, this won't work!

**Comment by darkylmnx** [comment]
Facing issue too here, any news on a possible fix?

**Comment by labcenter2020** [comment]
Facing this issue too.

**Comment by crynobone** [comment]
I believe this has been fixed via laravel/nova#978
