### ISSUE TITLE
Action Field to search and select a resource id (something like BelongsTo)

### ISSUE THREAD

**Issue by ziming** [laravel/nova-issues#2493]
Requesting for an Action Field like BelongsTo that allow me to select a user_id for example and searchable if the users table is too large. Select field can't do that.

For the Actions.

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by rela589n** [comment]
Is there some implementation over the web? I haven't found one.
