### ISSUE TITLE
ResolvesFields::creationFields() no longer resolves resources to fields

### ISSUE THREAD

**Issue by ralphschindler** [laravel/nova-issues#2495]
- Laravel Version: 7.5.2
- Nova Version: 3.3.2
- PHP Version: 7.4.4
- Database Driver & Version:
- Operating System and Version: n/a
- Browser type and version: n/a
- Reproduction Repository: https://github.com/###/###

### Description:

Custom fields that expect $this->value to be present when creating a new resource in the UI no longer have `$this->value` populated.

Between Nova versions 3.3.2 and 3.1, `ResolvesFields::creationFields()` was refactored. It no longer calls `resolvesFields()` which in turn ensures that a fields value (resource) is resolved to Field.

(`ResolvesFields::creationFields()` used to call `ResolvesFields::resolveFields()` (to get the `availableFields()`) which in turn called `$fields->whereInstanceOf(Resolvable::class)->each->resolve($this->resource);`)

The lack of value in the Field breaks Fields that expect to calculate some field state based off computed attributes that are available in new/fresh models.

This could be related to a refactor for this issue:
https://github.com/laravel/nova-issues/issues/2482

### Suggested Fix

Either call `resolveFields()` to get the list of available fields in `ResolvesFields::creationFields()` which will give you a list of all the `availableFields()` fully resolved, or iterate the `FieldCollection` and resolve each with the `$this->resource` as `ResolveFields::resolvesFields()` does.

**Comment by davidhemphill** [comment]
What's an example of a built-in Nova field that is failing, and how can I replicate the error?

**Comment by davidhemphill** [comment]
Also, creation fields don't have values (being that they're empty), so not quite sure what the issue would be there.

**Comment by ralphschindler** [comment]
Here is an example...

This library has not yet updated to Laravel 7's eloquent casting, but the theory and usage remains the same. New (empty) objects may have an attribute replaced with a rich value object / data transfer object that has empty state.

In this library, any attribute can be exposed as either an Image or ImageCollection, the wiring for this is setup at Eloquent's trait initialization hook. So in Nova it is checked as such:

https://github.com/ziffmedia/laravel-eloquent-imagery/blob/beta/src/Nova/EloquentImageryField.php#L63-L90

That aside, with Laravel 7's Custom Casting, here is an example (based off the Laravel manual example) where empty objects have complex (yet still empty) values associated with them:

```php
namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    // ...
    protected $casts = [
        'address' => Casts\AddressCaster::class
    ];
}

// the address container object / value object / data transfer object / etc

class Address { /* .... */ }

// finally the caster:

namespace App\Models\Casts;

use App\Models\Address;
use Illuminate\Contracts\Database\Eloquent\CastsAttributes;

class AddressCaster implements CastsAttributes
{
    public function get($model, $key, $value, $attributes)
    {
        return new Address(
            $attributes['address_line_one'],
            $attributes['address_line_two']
        );
    }

    public function set($model, $key, $value, $attributes)
    {
        return [
            'address_line_one' => $value->lineOne,
            'address_line_two' => $value->lineTwo,
        ];
    }
}
```

Finally, here is a fresh object with complex attribute (with empty state):

```console
~/t/test-laravel-7 ➜  artisan tinker                                                                                          
Psy Shell v0.10.2 (PHP 7.4.2 — cli) by Justin Hileman
>>> $user = new App\Models\User
=> App\Models\User {#3014}
>>> $user->address
=> App\Models\Address {#3015}
```

I can put together a failing example later today if you like.

**Comment by davidhemphill** [comment]
I think the gist of what you're saying is that `default` attributes on the Model (whether using custom casts or not) are not available for setting defaults for Nova Resources?

**Comment by ralphschindler** [comment]
Yeah, I think we're on the same page there.

By `default` I take that to mean calling `Field::resolve()` which in turn would do the right thing depending on the Nova configured field (either calling resolveAttribute() in `->resolve()`, the computed property (if it is a `ComputedField`, or for relations calling their own `Field::resolve()` override (which may do something specific/different deepening if it is a BelongsToMany, MorphTo, etc).
