### ISSUE TITLE
art route:cash

### ISSUE THREAD

**Issue by N1Prop** [laravel/nova-issues#2496]
- Laravel Version: 7.5.2
- Nova Version: 3.3.2
- PHP Version: 7.4.3

### Description:
After upgrading nova to V3.3.2 and running art route:cache getting error. 

Route cache cleared!

   LogicException
  Unable to prepare route [api/user] for serialization. Uses Closure.
  at vendor/laravel/framework/src/Illuminate/Routing/Route.php:1056

**Comment by davidhemphill** [comment]
That is not a Nova route.
