### ISSUE TITLE
Nova panel Password reset issue

### ISSUE THREAD

**Issue by janithchamp** [laravel/nova-issues#2497]
Hello,

I'm facing this issue in reset nova admin panel password. I am not able to change package files inside laravel framework. This is working correctly when I changed config/auth.php Authentication defaults, but I need to use an extra one. Can you please help me out? that would be really grateful.

"Argument 2 passed to Illuminate\Auth\Passwords\PasswordBroker::__construct() must implement interface Illuminate\Contracts\Auth\UserProvider, null given, called in /var/www/vendor/laravel/framework/src/Illuminate/Auth/Passwords/PasswordBrokerManager.php on line 73 "

cheers...

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).
