### ISSUE TITLE
Wrong CSS & JS paths

### ISSUE THREAD

**Issue by PatrickSTM** [laravel/nova-issues#2498]
- Nova Version: 3.3.2
- PHP Version: 7.5
- Operating System and Version: Windows 10.0.18363
- Browser type and version: Chrome 80.0.3987.163

I just did a new Laravel & Laravel-Nova installation.

However, CSS & JS files are not loaded because Nova always accesses the "vendor" directory.

![image](https://user-images.githubusercontent.com/13473121/79048034-98a27900-7c1a-11ea-9ff6-2c9a99a09259.png)

**Comment by davidhemphill** [comment]
Couldn’t get this replicated on a fresh install of Nova.

**Comment by PatrickSTM** [comment]
I found the mistake.
This error happens when laravel can be called from a subdirectory.
The document root must point to the laravel installation, otherwise this error will occur.
