### ISSUE TITLE
Declaring HasMany, HasOne fields don't really work in fieldsForDetail function

### ISSUE THREAD

**Issue by ziming** [laravel/nova-issues#2499]
- Laravel Version: 7
- Nova Version: 3
- PHP Version: 7.4

### Description:
I declared a bunch of fields as shown below:

```php
public function fieldsForDetail(NovaRequest $request)
    {
        return array_merge($this->fields($request), [
            HasOne::make('Profile', 'profile'),
            HasMany::make('Books', 'books'),
        ]);
    }
```

It shows up on detail view but when I click create Books button, it goes to the create books page and is forever empty. Upon checking console I see that it says 

Failed to load resource: the server responded with a status of 404 ()

So I thought I need to add to fieldsForCreate and fieldsForUpdate

```php
public function fieldsForCreate(NovaRequest $request)
    {
        return $this->fieldsForDetail($request);
    }

public function fieldsForUpdate(NovaRequest $request)
    {
        return $this->fieldsForDetail($request);
    }
```

But it still does not work, hence this bug report. Thank you

**Comment by davidhemphill** [comment]
`HasMany` and `HasOne` fields are not designed to be used on create forms. You should place these relations in the `fields` method.
