### ISSUE TITLE
Hide resources from sidebar

### ISSUE THREAD

**Issue by thegregthomp** [laravel/nova-issues#250]
I've created multiple resources that are important for relationships and some sub-actions but I'd like to hide them from the sidebar. Is this possible? Thanks.

**Comment by tillkruss** [comment]
Checkout the `availableForNavigation()` method on your resources.

**Comment by thegregthomp** [comment]
@tillkruss thanks for the super fast response. Is this somewhere in the docs?

**Comment by tillkruss** [comment]
Not sure. Maybe submit a PR.

**Comment by thegregthomp** [comment]
@tillkruss I'm only asking because I can't find any reference to the method anywhere in docs or code.

**Comment by albalooshi** [comment]
Add this in the resource that you want to hide
`public static $displayInNavigation = false;`

**Comment by thegregthomp** [comment]
@albalooshi perfect thanks, wish this was in docs somewhere.

**Comment by poxin13** [comment]
It's in the code anyway in `/nova/Resource.php`

```
    /**
     * Indicates if the resource should be displayed in the sidebar.
     *
     * @var bool
     */
    public static $displayInNavigation = true;
```

**Comment by guyaloni** [comment]
You can also add a dynamic logic in case you need it using `availableForNavigation` function in your `Nova\Model` class:

    public static function availableForNavigation(Request $request)
    {
        // TODO – add your logic
        return true;
    }

**Comment by WyattCast44** [comment]
For future searchers, now documented here: https://nova.laravel.com/docs/1.0/resources/#registering-resources

**Comment by barnomics** [comment]
Thanks @guyaloni ! 

`availableForNavigation` should be documented (I can't find it at the moment)

**Comment by jaesung2061** [comment]
Is it possible to both hide and forbid access to it for certain users? Or is it just cosmetic?

**Comment by poxin13** [comment]
@jaesung2061 there's an entire section on Authorization in the docs that will forbid access. The option above is cosmetic. https://nova.laravel.com/docs/2.0/resources/authorization.html#authorization

**Comment by abr4xas** [comment]
You can also add something like this in your `NovaServiceProvider.php` file:

```php
(new Foo)->canSee(function () {
    // stuff
})
```

**Comment by coreyworrell** [comment]
This is old issue I realize, but @poxin13 I don't see a clear way to use a policy to prevent access to the resource on its own, but to allow access when part of a relationship.. ie: user cannot see all User resources (User model), but when editing a Team resource, they see list of Members (User model). How could this be done?

**Comment by gavinhewitt** [comment]
> This is old issue I realize, but @poxin13 I don't see a clear way to use a policy to prevent access to the resource on its own, but to allow access when part of a relationship.. ie: user cannot see all User resources (User model), but when editing a Team resource, they see list of Members (User model). How could this be done?

Came here looking for the same thing :-(

**Comment by monaye** [comment]
@coreyworrell @gavinhewitt have you tried checking with the request object? you may conditionally allow based on the request URL or something. haven't tried yet though.

**Comment by timkerr222** [comment]
Is it possible to use these properties/methods to hide Dashboards?
