### ISSUE TITLE
when some models have too may hasToMany relationships when you visit detail page for that model it will redirect you to home page and some time it will take default values of msql configuration in config/database.php rather than taking values from .env files

### ISSUE THREAD

**Issue by osamaAbdullah** [laravel/nova-issues#2500]
### my user model has all following hasMany relations:

`		        HasMany::make('Orders', 'orders', Order::class),
			HasMany::make('Notes', 'notes', Note::class),
			HasMany::make('Customers', 'customers', Customer::class),
			HasMany::make('Websites', 'websites', Website::class),
			HasMany::make('Countries', 'countries', Country::class),
			HasMany::make('Cities', 'cities', City::class),
			HasMany::make('Branches', 'branches', Branch::class),
			HasMany::make('ItemTypes', 'itemTypes', ItemType::class),
			HasMany::make('ItemSizes', 'itemSizes', ItemSize::class),`

### and here corsponding methods in User.php model:

`	public function websites()
	{
		return $this->hasMany(Website::class);
	}

	public function orders()
	{
		return $this->hasMany(Order::class, 'creator_id');
	}

	public function notes()
	{
		return $this->hasMany(Note::class);
	}

	public function itemSizes()
	{
		return $this->hasMany(ItemSize::class);
	}

	public function itemTypes()
	{
		return $this->hasMany(ItemType::class);
	}

	public function customers()
	{
		return $this->hasMany(Customer::class, 'creator_id');
	}

	public function countries()
	{
		return $this->hasMany(Country::class);
	}

	public function cities()
	{
		return $this->hasMany(City::class);
	}

	public function branches()
	{
		return $this->hasMany(Branch::class);
	}`

**Comment by davidhemphill** [comment]
Nova doesn't change anything in the reading of configuration variables. And it seems unlikely that it's a Nova bug redirecting, but likely a missing resource or something similar.

**Comment by osamaAbdullah** [comment]
![image](https://user-images.githubusercontent.com/26807223/79346195-bf262400-7f3a-11ea-8fd1-9043d7a0809f.png)

![image](https://user-images.githubusercontent.com/26807223/79346631-44a9d400-7f3b-11ea-8e6c-6ffdccbdb9b9.png)

![image](https://user-images.githubusercontent.com/26807223/79346699-57bca400-7f3b-11ea-95e4-d02d1b60f519.png)


**that is the screenshot of errors and after that it redirects to 403 page**


![my .env file](https://user-images.githubusercontent.com/26807223/79347050-d44f8280-7f3b-11ea-89ae-76b22cbeab29.png)

![config/database.php](https://user-images.githubusercontent.com/26807223/79347144-f6e19b80-7f3b-11ea-875b-bdf227f62ced.png)

it does not take it from .env as usual and as expected, but it takes from config/batabase.php is there any other explanations ??  and beside this only happens some times, many times every thing works as expected.

**Comment by jbrooksuk** [comment]
Try running `rm -rf bootstrap/cache/*` from within your app directory.

**Comment by osamaAbdullah** [comment]
i did that and it's working perfectly no issues until now thank you, **but can you tell me what was going on?**

**Comment by osamaAbdullah** [comment]
sorry i thought it worked as the issue is not happening always, but it didn't wok i checked every single corresponding method on  models that are responsible for returning their hasMany Relationship it did't work, then i commented out all of them and added them one by one after refreshing page when i uncommented each one then some times it redirected with only one of them and some times it didn't, that means the problems are not with any of them some thing else causes that issue,
