### ISSUE TITLE
Don't find Nova router

### ISSUE THREAD

**Issue by sweetsica** [laravel/nova-issues#2501]
- Laravel Version: 7.x.x
- Nova Version: #.#.#
- PHP Version: 7.2
- Database Driver & Version: Laragon - Homestead - Xampp
- Operating System and Version: Win10
- Browser type and version: Opera
- Reproduction Repository: https://github.com/###/###

### Description:
I just install but when i update composer, it's show "Juncing nova..." then when i'm done, it's missing nova (as my route:list picture) :(

### Steps To Reproduce:
All as document, since composer update at laravel/nova. It's not migrating, it's juncing... i had fix moon and intl but not different.

**Comment by demency** [comment]
Did you check if you have the NovaServiceProvider on provideer list? . Im not pretty sure if that is a windows related issue, but I can confirm about the existence of bug and already exists some issue. So this is duplicated

**Comment by demency** [comment]
#660 is the issue

**Comment by sweetsica** [comment]
@demency Thank for reading. Yes, i have it. And all nova-api route. Except /nova route :|

**Comment by sweetsica** [comment]
@demency oh, i got it. After composer update -> php artisan nova:install. I must add 
App\Providers\NovaServiceProvider::class,
at config/app.php
then all will be fine. Thank for your help!

**Comment by demency** [comment]
Sometimes, packages on Laravel require a local and package ServiceProviders. 💡
