### ISSUE TITLE
Database seed, the toArray method seems a bug.

### ISSUE THREAD

**Issue by lifeblood** [laravel/nova-issues#2502]
- Laravel Version: 7.4.0
- Nova Version: 3.3.2
- PHP Version: 7.4
- Database Driver & Version: MySQL 5.7.29
- Operating System and Version: Ubuntu 18.04.4 LTS 
- Browser type and version: chrome
- Reproduction Repository: -

### Description:
````
<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use App\OpsServer;
use Faker\Generator as Faker;
use Carbon\Carbon;

$factory->define(OpsServer::class, function (Faker $faker) {

    static $number = 1;


    return [
            'server_type' => '1',
            'vt_type' => '0',
            'os_type' => '1',
            'ops_namespace_id' => '1',
            'ops_location_id' => '1',
            'ops_project_id' => '1',
            'ip' => sprintf('172.20.100.%s', $number++),
            'created_at' => '2020-04-12 13:00:29'
    ];
});

````

````
class OpsServerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $users = factory(\App\OpsServer::class)->times(2)->make();
        dd($users->makeVisible(['created_at'])->toArray());
````

not call toArray()
result:
![image](https://user-images.githubusercontent.com/3621748/79069713-f7432200-7d02-11ea-9485-82aca3bc8748.png)

called toArray()
result:
![image](https://user-images.githubusercontent.com/3621748/79069721-0a55f200-7d03-11ea-8cd7-65b62cfbb169.png)

**Comment by dmarkussen** [comment]
Looks like this maybe similar to issue #2460.

**Comment by davidhemphill** [comment]
Closing as this doesn't seem to be specific to using Nova.

**Comment by lifeblood** [comment]
https://laravel.com/docs/7.x/upgrade#date-serialization
