### ISSUE TITLE
Sortable() works two times

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#2503]
Laravel Version: 5.8.37
Nova Version: 2.11.1
PHP Version: 7.2.19
Operating System and Version: Windows 10
Browser type and version: Chrome 79 64-bits

### Description:

Sorting works the first two times, the third time nothing happens. Can see first two ajax calls in my browser development tools, then nothing anymore.

Interesting, will also happen if you load the url with sorting 'DESC' directly:

<MY_URL>/resources/catalog-products?catalog-products_order=sku&catalog-products_direction=desc

When i try to sort on another field, i can again sort the original field two times.

**reproduce**

1. Create nova resource
2. Add non-computable field 
3. Add sortable
4. Sort two times
5. Third time doens't work

**Comment by davidhemphill** [comment]
The third click resets the column to no sorting.

**Comment by preliot** [comment]
So it is by design, thanks for the info

**Comment by preliot** [comment]
Just checked it to be sure, but the third time no reset occurs. It just stays sorted in the DESC order.

**Comment by davidhemphill** [comment]
Can you post an example where the third time doesn't reset? It seems to be working correctly on all the examples I've tried.

**Comment by milewski** [comment]
Same issue, the third click doesnt reset, and the forth click doesnt sort back ASC etc...

**Comment by preliot** [comment]
Not a laravel Nova issue as it turned out! 

Narrowed it down to this package [https://github.com/Flagstudio/nova-actions-left](https://github.com/Flagstudio/nova-actions-left).

Also posted an issue there [https://github.com/Flagstudio/nova-actions-left/issues/2](https://github.com/Flagstudio/nova-actions-left/issues/2)

**Comment by preliot** [comment]
Fixed by repo owner in version 0.2.0
