### ISSUE TITLE
Translations not retrieved from resources\lang\vendor\nova\nl.json

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#2505]
Laravel Version: 5.8.37
Nova Version: 2.11.1
PHP Version: 7.2.19
Operating System and Version: Windows 10
Browser type and version: Chrome 79 64-bits

### Description:

I see several translations not working anymore like "Create :resource" or ":resource Details".

resources\lang\vendor\nova\en.json (default english)
resources\lang\vendor\nova\nl.json (dutch translations)

When i add the translation to resources\lang\vendor\nl.json, translations work.  Checked https://nova.laravel.com/docs/1.0/customization/localization.html#overview, but it seems to be the right path for the translation.

**Comment by jbrooksuk** [comment]
I'm not able to replicate this, sorry.

I created a `./resources/lang/vendor/nova/nl.json` with:

```json
{
    "Create :resource": "Maken :resource"
}
```

![image](https://user-images.githubusercontent.com/246103/79229844-97ac5a00-7e5b-11ea-9e42-c3183324fdbd.png)

And Nova correctly shows me the translations:

![image](https://user-images.githubusercontent.com/246103/79229913-b27ece80-7e5b-11ea-8810-1b7bfbb3c6c0.png)

**Comment by jbrooksuk** [comment]
Oh, I also had to set my `app.locale` to be `nl`.

**Comment by preliot** [comment]
I've just tried it, but the results are strange. I can see the correct translation in the index view 'Maken User', but if i click on the new resource button, i get the default translation.

`\nova\src\Panel.php` seems to be the issue. The method `defaultNameFor(Create / Detail / Update)` returns the string from `/lang/vendor/nl.json` instead of `/lang/vendor/nova/nl.json`.

I can also see a translation issue on actions, but everywhere else it seems fine.

(Apologies for the delay it took me to answer to your reply)

**Comment by preliot** [comment]
Have just tried this with a fresh Nova install and translations work as expected. Don't understand why some translations in my application are picked up from `/lang/vendor/nl.json`. Will fix it by placing those translations there.

**Comment by DecortDev** [comment]
@preliot did you solved the translations issue or are you still using your workaround by placing the .json in `/lang/vendor/`? I have the same problem.

**Comment by preliot** [comment]
@DecortDev Still using workaround. Couldn't figure out the why unfortunatly.

**Comment by connordoner** [comment]
I'm having this issue using the latest version of Nova. Translations don't seem to change if I change them in `vendor/laravel/nova/resources/lang/en.json` either.
