### ISSUE TITLE
Control over created models/attached fields

### ISSUE THREAD

**Issue by genesiscz** [laravel/nova-issues#2506]
So actually I am reacting to this PR https://github.com/laravel/nova/pull/869 where we got the hidden fields, which is great. 

Now, it may be a question if there's already a way to do this, or a feature request if it doesn't.

I have several resources that needs additional model fields to be filled.
This is quite easy, just overriding the newModel to fill the required fields which aren't directly controllable by the form. 

```php
    static function newModel() {
        /** @var VoucherModel $model */
        $model = parent::newModel();
        $model->creator_id = Auth::id();
        return $model;
    }
```

Now the problem rises when I don't actually know the field value and actually need to derive the value from the request. This might be a bad example, but let's say I add a weight to the ingredient resource. The products resource, that uses this ingredient, needs to update it's total weight based on all of their ingredients.

```php
   static function newModel($request) {
      if ($request->isUpdate()) {
        $weightDiff = $request->oldModel->weight - $request->weight;
        $request->model->products()->...->addWeight($weightDiff);
      } else {
         ...
      }
   }
```

Also, I have several BelongsToMany fields, which, on attach, needs to add additional data about the attached (pivot) row. 

```
  static function onAttach($resource) {
     if ($resource->name == "ingredient") {
        $resource->attaching(function($model, $request) {
            $model->creator_id = Auth::id();
        });
     }
  }
``` 

Does this make sense? We don't actually have an (easy) way to modify the fields that are being inserted into the pivot tables.

**Comment by socieboy** [comment]
You can use Observers.
Observe for the model and use the methods, **updating**, **creating**.

**Comment by genesiscz** [comment]
- That doesn't work for the syncing pivot fields tho. (note that I don't use pivot models but only ->belongsToMany) - https://github.com/laravel/framework/pull/14988#issuecomment-245945061
- How do I get the request fields of NovaRequest in that observable? Is it safe to ask the DI to somehow get this request, if so, how?

**Comment by davidhemphill** [comment]
Does using the `fillUsing` callback function on your pivot fields not work for your use-case?

```php
public function fields() {
    return [
        BelongsToMany('Example')->fields([
            Text::make('Weight')->fillUsing(function ($request, $model, $attribute, $requestAttribute) {
                // Fill pivot fields here                
            })
        ]),
    ];
}
```

**Comment by genesiscz** [comment]
It kinda is, but it isn't documented at all. On a sidenote, I haven't found the new Hidden field documented either. 

This method would be ok for using the model/request to derive the data, but what if I want to fill more fields that are not part of this, eg. user_id. Let's say it's not a field I can show to the user because it's a secret, would I just go with Hidden field filling the value somehow to empty so the value doesn't show up for user in code and fillUsing to edit the model?

**Comment by genesiscz** [comment]
It still is kinda issue, I had to go with third party package which doesn't seem to work well with Nova sometimes. Pivot data observers are still a problem.

**Comment by davidhemphill** [comment]
Yes you can grab the current `NovaRequest` from IoC: `app(NovaRequest::class)`.

Nova's resources and fields are not designed to manage pivot data. Any effort to do so is a hack outside of what's officially supported at this time. If using Observers or `fillUsing` callbacks on your fields isn't enough to satisfy your requirements, I don't think we have any other options.
