### ISSUE TITLE
Missing documentation for $availableForEntireResource on Action class

### ISSUE THREAD

**Issue by flexchar** [laravel/nova-issues#2508]
I am trying to figure out what `$availableForEntireResource` property means on nova action class. I cannot find any documentation for it. 

```php
    /**
     * Indicates if this action is available to run against the entire resource.
     *
     * @var bool
     */
    public $availableForEntireResource = false;
```

Frankly, I was hoping this would allow action to be visible on resource index and called without any resource selected. 

#2211 seems to be related.

**Comment by mira-thakkar** [comment]
@flexchar have you found any documentation for this property so far?

**Comment by flexchar** [comment]
Hey @mira-thakkar, unfortunately not. I only dug through source code and found that it may have something to do with pivot resources..

Code: https://github.com/laravel/nova/search?q=availableForEntireResource

(if you don't have access, you can link [through here](https://nova.laravel.com/settings#github))

**Comment by mira-thakkar** [comment]
@flexchar Thanks!
