### ISSUE TITLE
Fields shall not be loaded if action is hidden

### ISSUE THREAD

**Issue by flexchar** [laravel/nova-issues#2509]
- Laravel Version: 7.4.0
- Nova Version: 3.2.1
- PHP Version: 7.4

### Description:

Based on [Action Visibility](https://nova.laravel.com/docs/3.0/actions/defining-actions.html#action-visibility), if I set action to be visible only on detail view, I would expect fields to not be loaded (performance issue).

I have action that for fields loads information from API spanning thousand entries. Even thou it's cached behind Redis, it still causes significant slow down (3sec). 

I can see that Nova calls actions endpoint with `/actions?resourceId=12345` if on detail. I'd suggest to detect this and, if hidden, simply return fields as null. Or something like #219 but for the actions :)

### Example Action

With a little hack to prevent loading fields (and thus calling API) when on index page.

```php

class LinkMagentoProduct extends Action
{
    /**
     * Indicates if this action is only available on the resource detail view.
     *
     * @var bool
     */
    public $onlyOnDetail = true;

    /**
     * Perform the action on the given models.
     *
     * @param  \Laravel\Nova\Fields\ActionFields  $fields
     * @param  \Illuminate\Support\Collection  $models
     * @return mixed
     */
    public function handle(ActionFields $fields, Collection $models)
    {
        $models->each(function (MalgodtProduct $model) use ($fields) {
            $item = MagentoAPI::getAllProducts()->get(request('magentoId'));
            $model->linkMagentoProduct($item);
        });
    }

    /**
     * The job failed to process.
     *
     * @param ActionFields $fields
     * @param Collection $models
     * @param Mixed $error
     *
     * @return void
     */
    public function failed(ActionFields $fields, Collection $models, $error)
    {
        Log::error($error);
        return Action::danger($error->getMessage());
    }

    /**
     * Get the fields available on the action.
     *
     * @return array
     */
    public function fields()
    {
        if (!request('resourceId')) {
            return [];
        }

        return [
            SelectAutoComplete::make('Magento Product', 'magentoId')
                ->options($this->getListOfProducts())
                ->displayUsingLabels()
                ->help(MagentoAPI::getCacheStatusLine()),
        ];
    }

    /**
     * Get formated list of Magento products for Nova action
     *
     * @return array
     */
    public function getListOfProducts(): array
    {
        $items = MagentoAPI::getAllProducts();

        return $items
            ->mapWithKeys(function ($entry) {
                return [
                    $entry->entity_id => "#{$entry->entity_id} ({$entry->type_id}) {$entry->name}",
                ];
            })
            ->all();
    }
}

```

**Comment by davidhemphill** [comment]
Can you update your issues with an example of code that you wish to work this way?

**Comment by flexchar** [comment]
Sure, David! In the example class I have hacked for now to return empty array when request is from index view. This also causes fields to not be available when executing action so had to use another request helper.

I wish it'd simply not load if it's hidden. It happens in `jsonSerialize` method on Action class, line 634.

**Comment by flexchar** [comment]
Well this may be stale but I believe it doesn't make it any less relevant :)

**Comment by crynobone** [comment]
Unfortunately this is by design and this would not be an easy task for the current series.

What you can do is to cache the API request locally, using `Cache` or `Sushi` to reduce overhead of making API request all the time.
