### ISSUE TITLE
Dynamic Filter Name

### ISSUE THREAD

**Issue by pyramid-ali** [laravel/nova-issues#2511]
- Laravel Version: 7.5
- Nova Version: 3.3.2
- PHP Version: 7.4
- Database Driver & Version: mysql
- Operating System and Version: ubuntu
- Browser type and version: firefox

### Description:
defining multiple filter class in filter array causes a bug to show the correct filter's name

### Steps To Reproduce:

![carbon](https://user-images.githubusercontent.com/12711392/79240467-14086280-7e87-11ea-96ef-5ec9b90a8187.png)

![carbon (1)](https://user-images.githubusercontent.com/12711392/79240486-19fe4380-7e87-11ea-9106-40f548e96f75.png)

![Screenshot from 2020-04-14 19-31-33](https://user-images.githubusercontent.com/12711392/79240501-1d91ca80-7e87-11ea-8e9f-e7ace3831403.png)

I just created a filter named ActiveFilter, then I change filter name with a provided column name, but when I use multiple time of the same filter in a resource, all filter's name is the same as the first one

**Comment by jbrooksuk** [comment]
You need to override the `key` method:

```
/**
     * Get the key for the filter.
     *
     * @return string
     */
    public function key()
    {
        return get_class($this);
    }
```
