### ISSUE TITLE
Model newQuery lost in detail view nova resource

### ISSUE THREAD

**Issue by nickkuijpers** [laravel/nova-issues#2512]
- Laravel Version: 7.5.2
- Nova Version: 3.3.2
- PHP Version: 7.4
### Description:

I am using the following structure in models, to define the 'scope' of permission. The nova resource file is using this Transaction model where it is automatically limited to not show more than only the newQuery results. So the view of this Transaction model, is limited to the post_type "transactions". I use multiple models on the same database table, where the difference is defined by the 'post_type' column. With multiple models laying over this table, i can switch the results with the newQuery method in the model.

Previously it was working in Nova that when the nova resource is using the model Transactions, it was limited to that defined newQuery of the model. It still is for the index overview of the resource, but when going into the detail page of the nova resource, i can switch the url ID to a other post_type for example like 'order' and i can access that record in the database.

```php
class Transactions extends Posts
{    
    protected $table = 'posts'; 

    public function newQuery()
    {
        $query = parent::newQuery();
        
        $query = $query->where([
            ['post_type', '=', 'transactions'],
        ]);        

        return $query;
    }
```

The issue; in this file: 

Laravel\Nova\Http\Requests\InteractsWithResources.php, at line 102, you have got the following method:

```php
public function findModelQuery($resourceId = null)
    {
        return $this->newQueryWithoutScopes()->whereKey(
            $resourceId ?? $this->resourceId
        );
    }
```

In this method, the query is fetched withoutScopes. I think this was not there before, because if i set it to the following, it is maintaining the newQuery of the model.

```php
public function findModelQuery($resourceId = null)
    {
        return $this->newQuery()->whereKey(
            $resourceId ?? $this->resourceId
        );
    }
```

Is this something we can fix or is this in here because of some reason?

Thank you.

**Comment by davidhemphill** [comment]
The usage of `newQueryWithoutScopes` has been there since the beginning so I'm not sure how to proceed. You can update the `detailQuery` of your Resource to get a similar effect.

**Comment by nickkuijpers** [comment]
Hi David,

Thank you for responding, i will look into it what happened. 

Have a nice day!
