### ISSUE TITLE
ability to define keys on KeyValue field

### ISSUE THREAD

**Issue by Sabonzy** [laravel/nova-issues#2514]
currently only one row is rendered when using the nova `KeyValue` field, to add a new row you would have to click on `add Item` button, when dealing with large data size and if you have to create at least four rows per every record then this is a pain to deal with (at least for me). to deal with this issue i created a new `nova Field` using the `KeyValue` field as a head start. 

I added below method to `Field` class
```php
public function keys(array $keys)
{
    return $this->withMeta(['keys' => $keys]);
} 
```
and this to the `FormField` vue component 
```javascript
addRows() {
    return _.tap(this.field.keys, keys => {
        if (keys === undefined) {
            this.addRow()
        } else {
            for (let i = 0; i < keys.length; i++) {
                this.theData = [...this.theData, {id: guid(), key: keys[i], value: ''}]
            }
        }
        return keys
    })
},
```
which will enable you to do this `KeyValue::make('options')->keys(['a','b','c','d'])`
the end results is
![image](https://user-images.githubusercontent.com/8821242/79277120-bd0b8900-7e98-11ea-99dc-42bf65a1866b.png)

this works for me but it also added some extra kb to the files. It will be nice if we have this baked in.
Thanks.

**Comment by sirikkoster** [comment]
I think it's better to handle this in a Observer

**Comment by Sabonzy** [comment]
> I think it's better to handle this in a Observer

observers are related to models and this is a UI related issue, how will u handle this with an Observer

**Comment by sirikkoster** [comment]
Ok, I see what you mean.

I misunderstood it, I thought you must create it each time you create this model

**Comment by jbrooksuk** [comment]
Feel free to submit a PR :)

In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
