### ISSUE TITLE
Can not get the  selectedResources in nova with php

### ISSUE THREAD

**Issue by lifeblood** [laravel/nova-issues#2519]
> The selected resource IDs are available in the props passed to the modal component:
> 
> <img alt="image" width="1484" src="https://user-images.githubusercontent.com/58970/62875221-41918080-bce8-11e9-8b11-636e91318263.png">
> 
> Also, it's not documented, but you can specify your own Vue component to use instead of the ConfirmActionModal on your Action class by overriding the `component` method. The Modal will receive the selected resource IDs as an array. If your action is only used on a single resource, you can then fetch details about the resource to show in the modal however you'd like.

How can get selectedResources in nova with php?
![image](https://user-images.githubusercontent.com/3621748/78772167-effadc00-79c3-11ea-9c43-6816e9acbaae.png)

**Comment by lifeblood** [comment]
![image](https://user-images.githubusercontent.com/3621748/79438024-928b0e80-8005-11ea-9199-974b0b1abb8d.png)
I need to update data in index form with modal action

**Comment by davidhemphill** [comment]
The selected resources are passed to the `handle` method of your action's PHP class.

**Comment by lifeblood** [comment]
> The selected resources are passed to the `handle` method of your action's PHP class.

But I want to get it before run action
