### ISSUE TITLE
Cannot globally search resource when `displayInNavigation` is set to false

### ISSUE THREAD

**Issue by rikless** [laravel/nova-issues#2520]
- Laravel Version: 7.5
- Nova Version: v3.4.0 
- PHP Version: 7.4

### Description:
When `public static $displayInNavigation = false;` the resource is not available for global search, even if globalySearchable is set to true.

**Comment by rikless** [comment]
@davidhemphill Thank you David. Any news about this issue ?

**Comment by rikless** [comment]
@davidhemphill Hello David, I'd like to know if it's planned to fixing it in the next release. I have pro license and I'm locked in a previous version for now.

Thanks for your help.

**Comment by rikless** [comment]
@jbrooksuk coule you consider this issue please ?

**Comment by jbrooksuk** [comment]
@rikless I've not been able to replicate this:

![image](https://user-images.githubusercontent.com/246103/86765280-dc9df200-c040-11ea-9c2c-ed639ff4b753.png)

In the screenshot, you can see that the **Categories** resource is not displaying, but is available in the global search still.

Can you provide any further information?

**Comment by rikless** [comment]
@jbrooksuk maybe it has been fixed by https://github.com/laravel/nova/pull/887 because David replicated it when the issue was created.

**Comment by jbrooksuk** [comment]
Either way, I'm glad it's resolved :)
