### ISSUE TITLE
Boolean Field alignment

### ISSUE THREAD

**Issue by skoyah** [laravel/nova-issues#2522]
- Laravel Version: 6.18.3
- Nova Version: 2.12.0
- PHP Version: 7.3.12

The Boolean field is not being align correctly.

Without specifying the alignment, by default it has the class `text-center` duplicated as seen below:

![Screenshot 2020-04-16 at 15 37 38](https://user-images.githubusercontent.com/36083448/79462761-3d94cb80-7ff8-11ea-8fe5-37e135af6eba.png)
![Screenshot 2020-04-16 at 15 38 22](https://user-images.githubusercontent.com/36083448/79462879-67e68900-7ff8-11ea-9db0-45a710669914.png)
![Screenshot 2020-04-16 at 15 38 43](https://user-images.githubusercontent.com/36083448/79462935-792f9580-7ff8-11ea-8a44-5aa4ec30cc21.png)

Adding the class `inline-block` to the svg itself solves this issue:

![Screenshot 2020-04-16 at 15 41 44](https://user-images.githubusercontent.com/36083448/79463193-cf043d80-7ff8-11ea-9006-45e07f332f25.png)

Regarding the duplicated class name for the text alignment I was not able to find the reason why.

**Comment by davidhemphill** [comment]
How does one demonstrate this visual issue? On a fresh install of Nova the Boolean field is aligned correctly with its header.

**Comment by skoyah** [comment]
I have a Nova app for packages creation only.

I'll create a new one tomorrow to check if this issue persists.

**Comment by davidhemphill** [comment]
Ok, sounds good. Please post if you find out how to reproduce.

**Comment by blackfyre** [comment]
@skoyah did you manage to find source of the problem?
