### ISSUE TITLE
Problems updating to 3.4

### ISSUE THREAD

**Issue by mxm1070** [laravel/nova-issues#2523]
- Laravel Version: 7.6.2
- Nova Version: 3.4.0
- PHP Version: 7.4.4

### Description:
I was trying to update Nova from 3.3.2 to 3.4 and I ran into this problem in composer:

```
Package operations: 0 installs, 5 updates, 0 removals
  - Removing laravel/nova (v3.3.2)
  - Installing laravel/nova (3.0.x-dev 73f71a3): Downloading (failed)    Failed to download laravel/nova from dist: The "https://api.github.com/repos/laravel/nova/zipball/73f71a38401dfbdfd6130a0fcc392a9c621b4e45" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing laravel/nova (3.0.x-dev 73f71a3): The authenticity of host 'github.com (140.82.112.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos
```

I followed the steps to generate a token and used it and it did update to 3.4 according to the footer in the UI. But in composer it now says I'm on laravel/nova 3.0.x-dev 73f71a3 and I feel like that might cause a problem in the future.

**Comment by ilvalerione** [comment]
Hi, same issue here:

![Immagine](https://user-images.githubusercontent.com/13559278/79495216-911d0e80-8024-11ea-84cb-cfa02e4d1c69.png)

**Comment by davidhemphill** [comment]
Hi there! I republished the version's distribution just in case, and created a fresh Laravel install. I was able to install Nova according to the documentation. Please try again!

**Comment by mxm1070** [comment]
I tried updating again, but it still wants to update to the dev branch. I removed the composer requirement, the vendor folder, and composer.lock entry and I was able to get it to attempt an install of 3.4, but now I'm running into the issue from #2516.

**Comment by ilvalerione** [comment]
404 file not found persist.

![Immagine](https://user-images.githubusercontent.com/13559278/79545669-5c936c00-8091-11ea-8a4e-5121b87fd6c1.png)

**Comment by jbrooksuk** [comment]
What does your `composer.json` file look like? Please make sure you follow the installation instructions at https://nova.laravel.com/docs/3.0/installation.html#installing-nova-via-composer

**Comment by ilvalerione** [comment]
Here is my composer file: 

```
    "repositories": [
        {
            "type": "composer",
            "url": "https://nova.laravel.com"
        }
    ],
```

Dependencies section:

```
        "laravel/cashier": "^11.0",
        "laravel/framework": "^7.0",
        "laravel/horizon": "^4.0",
        "laravel/nova": "~3.0",
        "laravel/passport": "^8.4",
```

**Comment by ilvalerione** [comment]
@jbrooksuk I update the list of dependencies including all packages I'm using. It could be useful if you want test my dependencies list.

**Comment by ilvalerione** [comment]
I forced horizon to the previous version:

```
"laravel/horizon": "4.2.1"
```

that depends from `cakephp/chronos ^1.0` and the installation go further.

**Comment by DougSisk** [comment]
Having the same issue. Adding `"cakephp/chronos": "^1.0"` to my `composer.json` fixed it for me.

**Comment by beebmx** [comment]
I have the same issue with `3.4.0`

**Comment by poldixd** [comment]
Same issue here.

I have `"laravel/nova": "~3.0"` in my ` composer.json` and I only get the Version `3.0.x-dev 73f71a3`.

```
$ composer show
[...]
cakephp/chronos                         2.0.3
[...]
laravel/framework                       v7.6.2 
laravel/helpers                         v1.2.0
laravel/horizon                         v4.3.0
laravel/nova                            3.0.x-dev 73f71a3
laravel/passport                        v8.4.3
laravel/scout                           v8.0.0 
laravel/socialite                       v4.3.0
laravel/tinker                          v2.4.0
laravel/ui                              v2.0.1
[...]
```

I deleted the `composer.lock` and the `vendor`folder and executed `composer install` but I had no success.

```
- Installing laravel/nova (3.0.x-dev 73f71a3): Downloading    Failed to download laravel/nova from dist: The "https://api.github.com/repos/laravel/nova/zipball/73f71a38401dfbdfd6130a0fcc392a9c621b4e45" file could not be downloaded (HTTP/1.1 404 Not Found)
```

**Comment by jdssem** [comment]
I have the same issue, too.

**Comment by larsjanssen6** [comment]
Same here

**Comment by SuddenlyRust** [comment]
Try to set the next higher version range. This worked for me:
`"laravel/nova": "~3.4"`

The operator `~3.4` is equivalent to `>=3.4 <4.0.0`. This means you still will get all further all minor and patch updates.

I have tried `"laravel/nova": "~3.0"` like it is recommended in the documentation. But I also got the `3.0.x-dev` branch out of  it. Maybe it should be updated in the documentation to use a higher version range.

**Comment by jaap115** [comment]
> I tried updating again, but it still wants to update to the dev branch. I removed the composer requirement, the vendor folder, and composer.lock entry and I was able to get it to attempt an install of 3.4, but now I'm running into the issue from #2516.

I'm running into the same issue. I can update to 3.4 but then running in to #2516 again

```
name     : laravel/nova
descrip. : A wonderful administration interface for Laravel.
keywords : admin, laravel
versions : * v3.4.0
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] git@github.com:laravel/nova.git 08bfcfe836310f1492e8bd81f7457d2c961fd00c
dist     : [zip] https://nova.laravel.com/dist/laravel/nova/laravel-nova-08bfcfe836310f1492e8bd81f7457d2c961fd00c-zip-3fffb4.zip 08bfcfe836310f1492e8bd81f7457d2c961fd00c
names    : laravel/nova

autoload
psr-4
Laravel\Nova\ => src/

requires
brick/money ^0.4.2
cakephp/chronos ^1.0
doctrine/dbal ^2.9
ext-intl *
illuminate/support ^7.0
laravel/ui ^2.0
moontoast/math ^1.1
php ^7.2.5
spatie/once ^1.1 | ^2.0
symfony/console ^5.0
symfony/finder ^5.0
symfony/intl ^5.0
symfony/process ^5.0

requires (dev)
mockery/mockery ^1.0
orchestra/testbench ^5.0
phpunit/phpunit ^8.4
predis/predis ^1.1

```

**Comment by bobbybouwmann** [comment]
@davidhemphill @jbrooksuk Why is this issue closed? 

We hit the same issues with installing the dependencies. I believe a good solution has been provided in #2516 already. Let me know if I can help in any way!

**Comment by gerardnll** [comment]
Still running into this issue... I'm also using horizon if that helps..

**Comment by justindantzer** [comment]
This is currently working for me
```
"require": {
    ...
    "laravel/horizon": "^4.0",
    "laravel/nova": "~3.4",
    ...
}
```

```
cakephp/chronos                        1.3.0
...
laravel/framework                      v7.7.0
laravel/horizon                        v4.2.1
laravel/nova                           v3.4.0
```

**Comment by benyarb** [comment]
Also had this issue. Composer update with ~3.0 tries to install 3.0.x-dev 73f71a3 and gets a "Repository not found" error. Composer update with ~3.4 installs correctly.

**Comment by daugaard47** [comment]
Not sure it this helps or not, but for some reason upgrading to this latest version caused a 404 error every time I tried to access the login screen. Tried all the update this and composer that stuff...
I uninstalled/reinstalled twice. 404 every time.

Nothing worked, but I could see all the routes were there with a route check.

Fixed it with a workaround by adding the login route to my web routes.

`Route::get('/nova', 'Laravel\Nova\Http\Controllers\LoginController@showLoginForm');`

Works on `artisan serve` and with laragon. Haven't tried in production yet due to this error.

**Comment by JohnRoux** [comment]
Same issue here.
I used `"laravel/horizon": "4.2.1"` to get around it but would really like a fix

**Comment by souri84** [comment]
same issue now :/ i tested cakephp/chronos fix but it's not working for me :/

**Comment by petethewizard** [comment]
I keep getting:

`  [RuntimeException]                                                                                                                         
  Failed to execute git clone --mirror -- 'https://ghp...5iF:x-oauth-basic@github.com/laravel/nova.git' '/home/petar/.cache/composer/vcs/gi  
  t-github.com-laravel-nova.git/'                                                                                                            
                                                                                                                                             
  Cloning into bare repository '/home/petar/.cache/composer/vcs/git-github.com-laravel-nova.git'...                                          
  remote: Repository not found.                                                                                                              
  fatal: repository 'https://github.com/laravel/nova.git/' not found   `

on windows 10 using php 8.0 with `composer install` why is it trying to pull it from git GitHub?

**Comment by GalahadXVI** [comment]
> I keep getting:
> 
> ` [RuntimeException] Failed to execute git clone --mirror -- 'https://ghp...5iF:x-oauth-basic@github.com/laravel/nova.git' '/home/petar/.cache/composer/vcs/gi t-github.com-laravel-nova.git/'
> 
> Cloning into bare repository '/home/petar/.cache/composer/vcs/git-github.com-laravel-nova.git'... remote: Repository not found. fatal: repository 'https://github.com/laravel/nova.git/' not found `
> 
> on windows 10 using php 8.0 with `composer install` why is it trying to pull it from git GitHub?

Try adding your nova credentials to auth.json

```
{
  "http-basic": {
	"nova.laravel.com": {
            "username": "email here",
            "password": "licence here"
    }
}
```

**Comment by HassanElshazlyEida** [comment]
1. Create file at root directory with name "auth.json"
2. copy your nova credentials to it```
{
    "http-basic": {
        "nova.laravel.com": {
            "username": "email",
            "password": "passsword"
        }
    }
}
```
3.  composer update
