### ISSUE TITLE
Exceeding server file upload limit does not throw error

### ISSUE THREAD

**Issue by bcorcoran** [laravel/nova-issues#2527]
- Laravel Version: 7.6.2
- Nova Version: 3.4.0
- PHP Version: 7.4.3

### Description:
Upload that exceeded server's file upload limit did not throw an error.

Nova acted as though the upload was successful, but upon returning to the resource it was not present.

I increased the file upload limit and the file uploaded as expected.

The following is the code used to handle the upload:

```
File::make('Attachment')
                ->store(function (Request $request, $model) {
                    return [
                        'attachment' => $request->attachment->store('attachments/supplementals'),
                        'attachment_name' => $request->attachment->getClientOriginalName(),
                        'attachment_size' => $request->attachment->getSize(),
                        'attachment_mime_type' => $request->attachment->getMimeType(),
                    ];
                })
                ->onlyOnForms(),
```

**Comment by nathan-io** [comment]
Related to https://github.com/laravel/nova-issues/issues/1998
