### ISSUE TITLE
404 relate-authorization error on server

### ISSUE THREAD

**Issue by thegregthomp** [laravel/nova-issues#253]
My nova instance works perfect locally but issues arise on a hasMany relationship on the server. I get a 404 on a hasMany relationship I make in one of my resources. Url structure is: 
`/nova-api/quotes/relate-authorization?viaResource=orders&viaResourceId=7&viaRelationship=quote&relationshipType=hasMany`

**Comment by thegregthomp** [comment]
This appears to be a nova specific issue as I was able to query a hasMany relationship through laravel with no issues

**Comment by thegregthomp** [comment]
This had something to do with my nginx config. I went and cross referenced the laravel nginx config reco, made some changes and it works now 

https://laravel.com/docs/5.6/deployment#nginx

**Comment by Markvandersteen** [comment]
What was the exact change to your config that fixed it?

**Comment by GingerNinjaNicko** [comment]
I had this exact problem and checked my config against the default provided by laravel after I found the parameters simply were not being passed through so my old config must have been rewriting the query string to make it unintelligible to Nova.

The problem lines for me were:
```
location / {
    try_files $uri $uri/ /index.php?$query_string;
}
````

**Comment by nCuXaP** [comment]
Thank you @GingerNinjaNicko, that was my problem also.

**Comment by coroo** [comment]
Thank you so much @thegregthomp and @GingerNinjaNicko. Its workss!!
