### ISSUE TITLE
Forgot your password failed, have no password_resets table

### ISSUE THREAD

**Issue by lifeblood** [laravel/nova-issues#2530]
![image](https://user-images.githubusercontent.com/3621748/79736616-aba8fd80-832c-11ea-81f6-4ca137e95e61.png)

**Comment by jbrooksuk** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](https://larachat.co/).
