### ISSUE TITLE
Availibility to use Nova Components to custom fields

### ISSUE THREAD

**Issue by rogermlml** [laravel/nova-issues#2531]
I have a custom field and I'm asking if it's possible to use the filter component ore the index component( table ) that nova has at the different resources!

In my own component Vue i have a table, and also a filter but it will be great if you can use the same components that nova use!

It's that possible? How can I achieve it?

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
