### ISSUE TITLE
Currency Value with Currency Field as single Nova Field

### ISSUE THREAD

**Issue by sirikkoster** [laravel/nova-issues#2534]
It would be great is there is an Currency Field that refers to an currency field in the database

Now you have to specify a value field and a currency field separate

product_value = number
product_currency = [USD, EUR, HKD]

```php
Currency::make('Product value', 'product_value')->currency('EUR')
```
Would be great if this is possible because the currency could be variable
```php
Currency::make('Product value', 'product_value')->currencyField('product_currency')
```

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by stephan-v** [comment]
Why has this not been added? For a platform with multiple currencies this is pretty much the first thing you would want.

**Comment by sirikkoster** [comment]
Any progress, regarding this feature?

**Comment by goromachine** [comment]
Any progress?

**Comment by crynobone** [comment]
This is not being worked on at the moment, and yes some attempt to build this feature was initiated recently without success.

Above suggestion would only worked to resolve and display Currency value. However, at the moment it's impossible to cover all use cases to fill the value as Currency:

* It's not possible to retrieve object-based cast used for each attribute from Eloquent,
* Even if we do, there is no standard "Money" or "Currency" casting class built in with Laravel.
*
