### ISSUE TITLE
maintain fields input values after saving

### ISSUE THREAD

**Issue by Sabonzy** [laravel/nova-issues#2536]
Is there a way to let certain fields maintain it's input values after saving the record.
For instance when creating a record where the fields are `user (this is via relationship)`, `year`, `month` where multiple records exist under under the same `month` and multiple `month` under same `year`, is there a way to specify that the `month` and `year` field maintain it's input values after saving.

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by davidhemphill** [comment]
No there's no way to do this. Nova expects after save that the creation form should fresh.
