### ISSUE TITLE
Index table broken when delete policy is disabled

### ISSUE THREAD

**Issue by nchornii** [laravel/nova-issues#2538]
- Laravel Version: 7.7.1
- Nova Version: 3.4.0
- PHP Version: 7.2.28
- Database Driver & Version: 

### Description:
When **delete** method in `app/Policies/ArtikelPolicy.php` returns true everything is ok:
```
    public function delete($user)
    {
        return true;
    }
```
Table looks like this:
![Screenshot (1)](https://user-images.githubusercontent.com/62063744/79975348-81c61700-84a3-11ea-9839-78bd0414a972.png)

But once I disable delete ability in  `app/Policies/ArtikelPolicy.php`:
```
public function delete($user)
    {
        return false;
    }
```
Table got broken and looks like this:
![Screenshot (2)](https://user-images.githubusercontent.com/62063744/79975569-da95af80-84a3-11ea-929d-b92d11b17547.png)

as you can see one extra table header is present. 
### Steps To Reproduce:
- Disable delete ability.
- Take a look to Index Table

**Comment by nchornii** [comment]
@bobbybouwmann any updates in here?

**Comment by bobbybouwmann** [comment]
@nchornii I can't help you with this. I never had this issue before myself.

**Comment by nchornii** [comment]
@davidhemphill
any updates? 
great support for the not free administration panel :(

**Comment by davidhemphill** [comment]
It appears this issue was fixed in an already-released version of Nova. I was not able to replicate the issue using the steps provided. Please feel free to respond if the issue persists and we'll open this back up. Thanks!
