### ISSUE TITLE
Currency field not working on Windows PHP because it's missing money_format()

### ISSUE THREAD

**Issue by phillipfickl** [laravel/nova-issues#254]
The currency field does not work on some OS (eg Windows) installs of PHP, because they lack strfmon capabilities. (See https://secure.php.net/manual/fa/function.money-format.php under Notes)

A cross-platform solution would be good, until then maybe a warning in the docs.

**Comment by vernard** [comment]
4 months in and still no solution. Sad.

Any quick fixes?

**Comment by dkulyk** [comment]
You can make a polyfill. :)

**Comment by dillingham** [comment]
Here is what I'm using for money format, if anyone is stuck

```php
<?php

namespace App\Nova\Fields;

use Laravel\Nova\Fields\Field;

class Money extends Field
{
    public $component = 'text-field';

    public function __construct($name, $attribute = null, $resolveCallback = null)
    {
        parent::__construct($name, $attribute, $resolveCallback);
        
        $this->displayUsing(function() {
            return '$' . number_format($this->value, 2, '.', ','); 
        });
    }
}
```

**Comment by davidhemphill** [comment]
There will likely be no plans to implement this feature. There are other fields on http://novapackages.com that accomplish the same thing in a cross-platform way. Maybe we'll merge those in if the package maintainer agrees.
