### ISSUE TITLE
[Question] Run Job as Nova Action via Actionable possible?

### ISSUE THREAD

**Issue by davi5e** [laravel/nova-issues#2540]
- Laravel Version: 7.7.1
- Nova Version: 3.4.0
- PHP Version: 7.3

I have a model that uses the `Actionable` trait which implements observers to handle events such as `created` and others, calling jobs to do so.

The thing is, it's hard to tell what's going on with the jobs since there is no simple way to communicate their status to the user...

As Nova's actions handles this beautifully in the actions panel for the model (when dispatched via the queue worker), my question would be whether I can register an action "manually", as in dispatch a regular job as if it were an action?

**Comment by jbrooksuk** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](https://larachat.co/).

**Comment by davi5e** [comment]
For anyone interested.

```php
use Illuminate\Database\Eloquent\Collection;
use Laravel\Nova\Actions\DispatchAction;
use Laravel\Nova\Http\Requests\ActionRequest;

    // ...
    $action = new JobClass();
    $actionRequest = app(ActionRequest::class);
    $actionRequest->action = $actionRequest->query->set('action', $action->uriKey());
     DispatchAction::forModels(
        $actionRequest,
        $action,
        'handle',
        Collection::wrap($desiredModelHere),
        $actionRequest->resolveFields()
);
```
