### ISSUE TITLE
GlobalSearch constructor expects Collection, array given

### ISSUE THREAD

**Issue by bobbybouwmann** [laravel/nova-issues#2545]
- Laravel Version: 7.7.1
- Nova Version: 3.4.1
- PHP Version: 7.3.17
- Database Driver & Version: -
- Operating System and Version: -
- Browser type and version: -
- Reproduction Repository: -

### Description:
The `$resources` type in `Laravel\Nova\GlobalSearch` has been changed from `array` to `Collection`. However, the method hasn't changed. It's still doing a normal foreach. The second argument that is passed to this method is also an array and not a collection. So the types don't match anymore
```
/**
 * Create a new global search instance.
 *
 * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
 * @param  \Illuminate\Support\Collection  $resources
 * @return void
 */
public function __construct(NovaRequest $request, $resources)
{
     $this->request = $request;
     $this->resources = $resources;
}
```
Looking in the code of Nova where the actual global search is performed, there is also an array passed to this method because `Nova::globallySearchableResources($request)` still returns an array.
```
return (new GlobalSearch(
    $request, Nova::globallySearchableResources($request)
))->get();
```

The reason I have a problem with this is that I override the global search with some functionality. Suddenly my `phpstan` fails because the types don't match anymore.

**Comment by davidhemphill** [comment]
How would you demonstrate this in a test or example app?

**Comment by bobbybouwmann** [comment]
@davidhemphill I'm not sure why you need a full demo app. The value that is being returned by `Nova::globallySearchableResources($request)` is an array and the type hint for the second argument for `GlobalSearch` is a `Collection`. 

This normally works fine in PHP. However, we run phpstan which checks on these kinds of errors. 

My question remains, why is the `$resources` now type hinted to a collection, while it's never used as a `Collection`? There is only a foreach over the `$resources`.

**Comment by bobbybouwmann** [comment]
@davidhemphill Can I get an update on this? Our builds are sadly still failing because of this doctype change.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍

**Comment by bobbybouwmann** [comment]
Thanks @davidhemphill 👍
