### ISSUE TITLE
Can't change Nova::name()

### ISSUE THREAD

**Issue by sweetsica** [laravel/nova-issues#2546]
- Laravel Version: 7.7.1
- Nova Version: v3.1.0
- PHP Version: 7.1
- Database Driver & Version: Heidi SQL
- Operating System and Version: Windows 10
- Browser type and version: Opera
- Reproduction Repository: https://github.com/###/###

### Description:
Hello,
I'm using Nova Laravel, but i can't change app name by normal. To change it, i must change App_name at .env. Any ideals or helps? Thank you!

Here is my .env
![image](https://user-images.githubusercontent.com/28801986/80229004-04a0ca80-867a-11ea-8370-e4aa30f21335.png)

Here is my config\app.php
![image](https://user-images.githubusercontent.com/28801986/80229126-2dc15b00-867a-11ea-90c6-d006442fbc3b.png)

And here is  nova\src\Nova.php
![image](https://user-images.githubusercontent.com/28801986/80229219-4d588380-867a-11ea-8860-61260d61b9b9.png)

And the last is nova\config\nova.php
![image](https://user-images.githubusercontent.com/28801986/80229275-62cdad80-867a-11ea-9c04-4dfd6c54a872.png)

The result is .env data
![image](https://user-images.githubusercontent.com/28801986/80229352-7d078b80-867a-11ea-8b9d-e4a738f799a8.png)

I still don't know how does it work. Why it's only receive data app name at .env? 

Thanks for reading :(

**Comment by jbrooksuk** [comment]
Your `.env` file contains a space. Try and remove that.
