### ISSUE TITLE
Cannot validate VaporFile nor VaporImage

### ISSUE THREAD

**Issue by lucasromanojf** [laravel/nova-issues#2548]
- Laravel Version: 7.8.1
- Nova Version: 3.4.1
- PHP Version: 7.4.4
- Database Driver & Version: MySQL 8
- Operating System and Version: Ubuntu 18.04.4 LTS
- Browser type and version: Google Chrome 80.0.3987.163 64 bits
- Reproduction Repository: -

### Description:

When I try to use normal file validations (mime, dimensions, size etc) with Vapor file fields, the validations fail.

So I tried validating manually. This is what I did:

```php
VaporImage::make('Image')
    ->rules('bail', 'required', function($attribute, $value, $fail) {
        if (Storage::size($value) > 1000000) {
            return $fail('The image should not have more than 1 MB');
        }
    }),
```

But it also does not work, since $value just gives me the original file name, and not the current file key (path) on S3.

So, how can I validate a Vapor file field?

### Steps To Reproduce:

Just create a VaporFile or VaporImage and try to validate using normal file validations (mime, dimensions, size etc). Also try validating using closure. Both methods are not possible.

**Comment by lucasromanojf** [comment]
Any news about this? The stale bot is saying that it will be closed but there is no solution yet.

**Comment by ahamilton9** [comment]
May be tangentially related to https://github.com/laravel/nova-issues/issues/2554. They are different problems, but both related to the value that gets sent to both the underlying Nova code and to rules. 2554 was closed but is not resolved.

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/97537137-42035d80-19f9-11eb-90d4-840a599b0fc1.png)

You can solved this by refering to `$attribute` instead of `$value`.

```php
VaporImage::make('Photo', 'photo_url')
    ->rules('bail', 'required', function($attribute, $value, $fail) use ($request) {
        if (Storage::size($request->input('vaporFile')[$attribute]['key']) > 1000) {
            return $fail('The image should not have more than 1 KB');
        }
    }),
```
