### ISSUE TITLE
Actions resource has appeared in the sidebar, unable to hide

### ISSUE THREAD

**Issue by LorenzoSapora** [laravel/nova-issues#2551]
Not listed in the changes. Although looking through the changes, it seems the resource gathering has changed.

Would like the option to `public static $displayInNavigation = false;` but seem to be unable to. 

![image](https://user-images.githubusercontent.com/25519274/80388987-73f90300-88a2-11ea-8d0f-6c734937edd8.png)

Seems to be since v3.4.1. While this is a nice addition, control has been taken away from the user to hide/show this without some policy to remove it.

**Comment by davidhemphill** [comment]
We noticed this issue as well. Should be fixed in the next release. 👍

**Comment by lifeblood** [comment]
how to display this actions

**Comment by qubeek** [comment]
Hello, @LorenzoSapora. You can override base ActionsResource and change it in nova.php (configs). It's not a simple solution, but it works.

1. Create an empty class
2. Extend base ActionsResource class
3. Set `$displayInNavigation` false
4. Change model for actions in configs

It presented at the end of the config:
![image](https://user-images.githubusercontent.com/46513293/81079678-82759900-8ef8-11ea-879c-97480bcafe15.png)
