### ISSUE TITLE
fail to register action_event when primary key of a model is not integer

### ISSUE THREAD

**Issue by osamaAbdullah** [laravel/nova-issues#2553]
i have a **permission** model

![image](https://user-images.githubusercontent.com/26807223/80403406-33ac7b80-88c8-11ea-94ca-e7ac33b53e22.png)

and have many to many relationship with **Role** model when i try to attach roles from permission resource or detach from role resource is gives this error 

![image](https://user-images.githubusercontent.com/26807223/80403727-bf260c80-88c8-11ea-940f-6ac14b1467df.png)

**Comment by davidhemphill** [comment]
If you deviate from Nova's built-in migrations in any way for your application (to use non-integer primary keys for example), then you must modify the database columns to accept string formats on your end.

**Comment by osamaAbdullah** [comment]
@davidhemphill  how can i disable action_events entirely
