### ISSUE TITLE
Cannot edit a resource containing a VaporFile or VaporImage

### ISSUE THREAD

**Issue by MaximeWillinger** [laravel/nova-issues#2554]
- Laravel Version: 7.7.1
- Nova Version: 3.4.0
- PHP Version: 7.4.2

### Description:
When editing a resource with a `VaporImage` or `VaporFile` field, without modifying it, the following error occurs:

```
Trying to access array offset on value of type null.
VaporFile.php:136
```

### Steps To Reproduce:

1. Create a table with the following column.
```php
$table->string('image')->nullable();
```
2. Create the related Nova Resource with one of the following fields.
```php
return [
    VaporImage::make('Image'),
    // VaporFile::make('Image'),
];
```
3. Go to the resource's edit page `/resources/examples/1/edit`.
4. Click on `Update Example`.

**Comment by davidsneal** [comment]
Still an issue in 3.5.0

**Comment by rogierverbrugge** [comment]
Ive extended VaporFile.php and changed the prepareStorageCallback function() to

```php
/**
 * Prepare the storage callback.
 *
 * @param  callable|null  $storageCallback
 * @return void
 */
protected function prepareStorageCallback($storageCallback)
{
    $this->storageCallback = $storageCallback ?? function ($request, $model, $attribute, $requestAttribute) {
        if (! $request->$requestAttribute) {
            return $this->attribute = $model->{$attribute};
        }

        return $this->mergeExtraStorageColumns($request, [
            $this->attribute => $this->storeFile($request, $requestAttribute),
        ]);
    };
}

```

Seems to resolve the issue. Don't have the time to test and pull request the issue though.

**Comment by notf0und** [comment]
This issue has to be reopened since still existing on nova v3.8.2

**Comment by ahamilton9** [comment]
Still exists. Hopefully can be fixed along with https://github.com/laravel/nova-issues/issues/2548

**Comment by dvigueras** [comment]
As @rogierverbrugge said, extending the `VaporFile` class and overwriting the `prepareStorageCallback` method solves the problem. The problem is that the field is not present in the input request.

**Comment by devoncmather** [comment]
Composer update, still has the issue, posting here to get a notification for when it's fixed ✌🏻

**Comment by ibrahim-mubarak** [comment]
I had to tweak @rogierverbrugge solution to work with Flexible Layout
```php
    /**
     * Prepare the storage callback.
     *
     * @param callable|null $storageCallback
     *
     * @return void
     */
    protected function prepareStorageCallback($storageCallback)
    {
        $this->storageCallback = $storageCallback ?? function ($request, $model, $attribute, $requestAttribute) {
                return $this->mergeExtraStorageColumns($request, [
                    $this->attribute => ! $request->$requestAttribute
                        ? $model->{$attribute}
                        : $this->storeFile($request, $requestAttribute),
                ]);
            };
    }
```
Haven't been able to completely test it yet though
