### ISSUE TITLE
Still missing tailwind css classes

### ISSUE THREAD

**Issue by ThaDaVos** [laravel/nova-issues#2556]
### Description:
The tailwind classes are still missing and nothing has been done since this issue: https://github.com/laravel/nova-issues/issues/373

So, we can do one of the following:
A. Fix the documentation - preferably not
B. Add the full tailwind library - prefer this one
C. Give us a good workaround for the problem

Or else people will start the think about:
D. Stop using Nova and use something else like Laravel Backpack

Ps: Just add a thumbs up if you're interested by clicking on the emoticon below
⬇ - click down there

**Comment by demency** [comment]
We need release the kraken to add that feature

**Comment by demency** [comment]
Why dont add this feature vía package?

**Comment by jbrooksuk** [comment]
Nova uses its own customized version of the Tailwind configuration. So the recommended approach is to either use the classes available in the system already or add them to your specific tool's CSS via the included CSS file or the style block within the component.

**Comment by ThaDaVos** [comment]
So the only answer is to bloat the tools css, probably have issues with duplicated classes overriding each other and causing more issues then needed -> good answer...

**Comment by davidhemphill** [comment]
Take your attitude somewhere else.
