### ISSUE TITLE
asd label on dashboard when publish nova

### ISSUE THREAD

**Issue by mattiaefesto** [laravel/nova-issues#2557]
- Laravel Version: 6.18.13
- Nova Version: 2.9.4
- PHP Version: 7.4.1
- Database Driver & Version: Mysql 5.7.26
- Operating System and Version: macOS Catalina 10.15.4
- Browser type and version: Google Chrome 81.0.x

### Description:
I have a dashboard with custom cards.
When I want to publish nova to update, the command `php artisan nova:publish`, it completely clear my dashboard, and show my only a div with "asd" label...
I've found the label in the file nova/public/app.js line 44643
```
var render = function() {
  var _vm = this
  var _h = _vm.$createElement
  var _c = _vm._self._c || _h
  return _c(
    "div",
    { attrs: { dusk: "dashboard-" + this.name } },
    [
      _vm.cards.length > 1
        ? _c("heading", { staticClass: "mb-6" }, [
            _vm._v(_vm._s(_vm.__("Dashboard")))
          ])
        : _vm._e(),
      _vm._v(" "),
      _vm.shouldShowCards ? _c("div", [_vm._v("\nasd\n    ")]) : _vm._e()
    ],
    1
  )
}
var staticRenderFns = []
render._withStripped = true
module.exports = { render: render, staticRenderFns: staticRenderFns }
if (false) {
  module.hot.accept()
  if (module.hot.data) {
    require("vue-hot-reload-api")      .rerender("data-v-1f79daf6", module.exports)
  }
}
```

### Steps To Reproduce:
Publish a new version of nova

It's only me? Am I missing some steps?
I've followed the update guide on the site and this is the result I have

![Schermata 2020-04-28 alle 14 30 12](https://user-images.githubusercontent.com/59648480/80487320-e75f4b00-895c-11ea-933a-00d6a3a98418.png)

Thanks!
\m

**Comment by davidhemphill** [comment]
This doesn't seem to be an issue with Nova, but perhaps in one of your custom dashboards. If you can demonstrate the issue exists on a fresh Nova install, then feel free to open a new issue with details on how to show this. 👍
