### ISSUE TITLE
Cannot save or update a resource that has a `VaporImage` field

### ISSUE THREAD

**Issue by davidsneal** [laravel/nova-issues#2558]
- Laravel Version: 7.8.1
- Nova Version: 3.4.1
- PHP Version: 7.4.0
- Database Driver & Version: MySQL 5.7.27
- Operating System and Version: macOS 10.15.3
- Browser type and version: Chrome 80.0.3987.163
- Reproduction Repository: sorry it's private

### Description:

When using a `VaporImage` field, saving with a new image works no problem. When updating a resource entry that has a file already, or creating a new entry *without* selecting an image fails to save.

It's line 136 in Laravel\Nova\Fields\VaporFile where the error is thrown. `$request->input('vaporFile')` is `null` as it's not being sent, and the `storeFile` method is trying to access the index 'key' of it as if it were an array.

### Steps To Reproduce:

- Create a resource with `VaporImage`. e.g. `VaporImage::make('Logo')`
- Try to save without an image
- Error

- Create a resource with `VaporImage`. e.g. `VaporImage::make('Logo')`
- Save with image
- Click to update
- Error

**Comment by bkintanar** [comment]
seems related to #2554

**Comment by davidsneal** [comment]
You're right @bkintanar, exactly that
