### ISSUE TITLE
Markdown does not allow multiple simultaneous lists in the same textarea

### ISSUE THREAD

**Issue by bradenkeith** [laravel/nova-issues#2560]
- Laravel Version: 7.9.2
- Nova Version: 3.5.0
- PHP Version: 7.4.5
- Database Driver & Version: N/A
- Operating System and Version: Vapor, Local (Homestead)
- Browser type and version: Mac Chrome Version 81.0.4044.122 (Official Build) (64-bit)

### Description:

If within a markdown element you have multiple lists, you need to alternate between `-` and `*`. It will not allow multiple unorganized lists using the same precursor. When it is not functioning, the item will be wrapped in `<p></p>` causing undesired line breaks

### Steps To Reproduce:
1. Create a markdown field
2. Make a list:
```md
* One
* Two

* Three
* Four
```
3. Preview:
![image](https://user-images.githubusercontent.com/219298/80555129-5e1c3880-899d-11ea-9a2c-ec62e830ff32.png)

### Work Around:
1. Create a markdown field
2. Make a list:
```md
* One
* Two

- Three
- Four
```
3. Notice, it now shows as desired. It seems alternating `*` and `-` allows it behave as desired

Other things I've noticed, this seems to only happen when a list follows another list. Adding any element in between bypasses this problem (a title, or text for example)
```md
* One
* Two
#
* Three
* Four
```

**Comment by crynobone** [comment]
This seem to be a limitation with `markdown-it` and even `commonmark` spec:

* https://spec.commonmark.org/dingus/
* https://markdown-it.github.io/

Given the markdown syntax as:

```markdown
* one
* two

* three
* four
```

Both services return:

```html
<ul>
<li>
<p>one</p>
</li>
<li>
<p>two</p>
</li>
<li>
<p>three</p>
</li>
<li>
<p>four</p>
</li>
</ul>
```
