### ISSUE TITLE
How can I dynamically change the name of a filter?

### ISSUE THREAD

**Issue by tsn-Sergey** [laravel/nova-issues#2561]
For example, I pass the column name in the constructor. And I want the filter to be named according to the column.

```php
public function filters(Request $request)
{
     return [
         new DateRangeFilter('created_at'),
         new DateRangeFilter('started_at'),
         new DateRangeFilter('finished_at')
     ];
}
```
The name is set only the first time a new DateRangeFilter('created_at') is created.

**\App\Nova\Filters\DateRangeFilter.php**

```php
/**
 * DateRange constructor.
 *
 * @param string $column
 */
public function __construct($column)
{
    $this->column = $column;
}

/**
 * Get the displayable name of the filter.
 *
 * @return string
 */
public function name()
{
    return ucwords(str_replace('_', ' ', $this->column));
}
```

**Comment by jbrooksuk** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](https://larachat.co/).
