### ISSUE TITLE
Add searchable select field

### ISSUE THREAD

**Issue by satoved** [laravel/nova-issues#2562]
Nova already has a searchable field for relations:
![image](https://user-images.githubusercontent.com/14319239/80589305-99ad1600-8a22-11ea-93fb-e7b2e7e9ae96.png)

But it doesn't have this field as is. Only the Select field. I have a big Select field and making it "searchable" would be great, since it's already there.

**Comment by davidhemphill** [comment]
Just added a PR for this. 👍 

In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
