### ISSUE TITLE
BelongToMany "once" by default and "multiple" option

### ISSUE THREAD

**Issue by royduin** [laravel/nova-issues#2563]
Related:
- https://github.com/laravel/nova-issues/issues/318
- https://github.com/laravel/nova-issues/issues/895

With a BelongToMany relationship it could be possible that the relation can be attached multiple times (as mentioned here: https://github.com/laravel/nova-issues/issues/318#issuecomment-506860853) but in most cases it's only preferable once.

Within the "Laravel-5-Generators-Extended" package from Laracasts / Jeffrey Way which is used a lot to generate pivot table migrations there is a primary index to prevent duplicates: https://github.com/laracasts/Laravel-5-Generators-Extended/blob/d205e09bf31f571d6dd842350383f9fa9dda57f7/src/stubs/pivot.stub#L20

I think it's better to have that behavior by default within Nova so things like this: https://github.com/laravel/nova-issues/issues/318#issuecomment-621283485 are not needed and taken care of by Nova.

In case someone does have a project where it needs to attach a relationship multiple times it would be nice to have the old behavior with a `->multiple()` option.

**Comment by AforDesign** [comment]
I'm in a project that needs this functionality atm.

It looks like it's not possible now to have multiple pairs of the same relation in a pivot table.
I get a 'This [modelname] is already attached' error in the UI when I try to acchieve this.

This forces me to manually add the same relation-combination without using the NOVA UI.
Which is technically perfectly ok, when using a pivot table with a unique primary key.

I think such a constraint shoud be handled by the database, not by the UI.

To prevent duplicates, you could/should a unique field combination constraint in the database.
For example add a migration with:
`$table->unique(['model1_id', 'model2_id']);`

**Comment by royduin** [comment]
Please reopen.

**Comment by wightspace** [comment]
Please reopen.

**Comment by crynobone** [comment]
See https://nova.laravel.com/docs/3.0/resources/relationships.html#allowing-duplicate-relations 

This was introduced in version 3.23

**Comment by wightspace** [comment]
@crynobone Thank you
