### ISSUE TITLE
Cannot save resource that has 2 Vapor Image fields on the same resource.

### ISSUE THREAD

**Issue by fransjooste1** [laravel/nova-issues#2565]
- Laravel Version: 7.9.2
- Nova Version: 3.5.0
- PHP Version: 7.4.1
- Database Driver & Version: MariaDB 10.4.11
- Operating System and Version: Windows 10 10.0.18362
- Browser type and version: Chrome.81.0.4044.129 (Official Build) (64-bit)
- Reproduction Repository: Private Sorry

### Description:
Having 1 `VaporImage` field on a resource works beautifully. But having 2 `VaporImage` fields on the same resource fails.

The error returned is `File already exists at path: b7d6d07b-7796-4363-ae2a-d9c6b079bb96`. Checking console network tab shows there are two distinct signed-storage-url's being created, each with unique key values returned, but in code it seems only one is being used for both `VaporImage` fields.

### Steps To Reproduce:
- Create resource with 2 `VaporImage` fields:
e.g. `VaporImage::make('Image One')` & `VaporImage::make('Image Two')`
- Try to save resource
- Error

**Comment by mbryne** [comment]
I am also experiencing this issue, only have one image on the page also resolves the issue for me.

Let me know if I can provide more information.

**Comment by mbryne** [comment]
Update: I have put together a sample repository, I have set the path on each VaporImage field and played around with the storeAs function and this has allowed me to successfully save the resource but I believe you are correct that it is re-using the same S3 reference uuid for all fields on the page.

* [Sample repository](https://github.com/mbryne/nova-issue-test)
* [Setting path on field](https://github.com/mbryne/nova-issue-test/blob/master/app/Nova/ProfilesNotWorking.php#L59)

**Comment by mbryne** [comment]
Just taking a look at the post request here and there is no difference between the posted data for both fields so the second field is overriding the first:


```
hero: exhibitor-bg.jpg
vaporFile[key]: tmp/8f6eb6f3-4b59-4e14-a49c-c98c6cb366c1
vaporFile[uuid]: 8f6eb6f3-4b59-4e14-a49c-c98c6cb366c1
vaporFile[filename]: exhibitor-bg.jpg
vaporFile[extension]: jpg
logo: homepage-bg.jpg
vaporFile[key]: tmp/c7daff85-1f35-449d-b6a7-387a74843e64
vaporFile[uuid]: c7daff85-1f35-449d-b6a7-387a74843e64
vaporFile[filename]: homepage-bg.jpg
vaporFile[extension]: jpg
```

**Comment by mbryne** [comment]
I've managed to solve this issue locally by adding the attribute to the relevant vue components and Nova field classes.

I edited the following file from the main Nova repo, I then compiled the assets and copied them generated assets to the public/vendor/nova in my own app.

**resources/js/components/Forms/FileField.vue, lines 131-147:**

```vue
  mounted() {
    this.field.fill = formData => {
      const attribute = this.field.attribute;

      if (this.file && !this.isVaporField) {
        formData.append(attribute, this.file, this.fileName)
      }

      if (this.file && this.isVaporField) {
        formData.append(attribute, this.fileName)
        formData.append('vaporFile['+attribute+'][key]', this.vaporFile.key)
        formData.append('vaporFile['+attribute+'][uuid]', this.vaporFile.uuid)
        formData.append('vaporFile['+attribute+'][filename]', this.vaporFile.filename)
        formData.append('vaporFile['+attribute+'][extension]', this.vaporFile.extension)
      }
    }
  },
```

Then I created the following file in my own application that references the new attribute key and I use that extended field in my Nova resource.

**app/Nova/Fields/VaporFile.php**

```php
<?php

namespace App\Nova\Fields;

use Illuminate\Support\Facades\Storage;

class VaporFile extends \Laravel\Nova\Fields\VaporFile
{

    /**
     * Store the file on disk.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  string  $requestAttribute
     * @return string
     */
    protected function storeFile($request, $requestAttribute)
    {
        return with($request->input('vaporFile')[$requestAttribute]['key'], function ($key) use ($requestAttribute, $request) {
            $fileName = $this->storeAsCallback
                ? call_user_func($this->storeAsCallback, $request)
                : str_replace('tmp/', '', $key);

            Storage::disk($this->getStorageDisk())->copy($key, $this->getStorageDir().'/'.$fileName);

            return ltrim($this->getStorageDir().'/'.$fileName, '/');
        });
    }

}
```

This is all working and tests are passing in my local repo but I'm short on the time required to go through the pull request process.

Hope this helps.

**Comment by xdosli00** [comment]
@mbryne This solution works great! I can't see how this is not implemented in nova though

**Comment by richardjkeys** [comment]
This still seems to be the case.
