### ISSUE TITLE
Change default to 'desc' for first click on sortable column

### ISSUE THREAD

**Issue by Andy-Baker** [laravel/nova-issues#257]
Almost always when I'm sorting a column, I'm wanting to see the largest numbers first. At present you must click twice. It would be useful if we either have a default of 'desc' or can pass another variable to sortable() to change the default.

**Comment by davidhemphill** [comment]
By default the newest rows are shown and when you click the arrow they are sorted inversely. I'm not sure what you're asking us to change here.

**Comment by warksit** [comment]
I have just come across this myself. 

@davidhemphill with regard to the ID column what you say is correct and might well be what you want the default to be.

Say I have an amount column. When I click it to sort it sorts ASC, click again DESC, and again to reset. What @David-Griffiths and I would both like I believe is to be able to have the first click to sort DESC, then ASC, then reset. Is this possible?
