### ISSUE TITLE
visiting /nova gives 404 - not found

### ISSUE THREAD

**Issue by wouterdialogic** [laravel/nova-issues#2570]
- Laravel Version: 7.9.2
- Nova Version: 3.5.0 
- PHP Version: 7.2.5
- Database Driver & Version: SQL, via XAMP
- Operating System and Version: Windows 10
- Browser type and version: Chrome
- Reproduction Repository: Can i share nova content this way?

When following the install process via the nova docs, I see a 404 when visiting /public/nova.

added lines to json 
run composer update
php artisan nova:install
php artisan migrate
added App\Providers\NovaServiceProvider::class to app.php in the config dir, under providers. These werent added automatically.
I can see the route when doing php artisan route:list: 
localhost/nova2/public/nova | GET|HEAD | nova | nova.index

I`ve read up the posts I can find on stackoverflow, not sure how to continue.

UPDATE - beneath, question remaining is can i get this to work via XAMP as well, instead only via php artisan serve

**Comment by wouterdialogic** [comment]
I checked the routes in NovaServiceProvider, they are shown:

``
Nova::routes()
  ->withAuthenticationRoutes()
  ->withPasswordResetRoutes()
  ->register();
``

Also tried:
 - cd nova
 - npm install
 - npm run dev
 - cd ..
 - php artisan nova:publish

**Comment by demency** [comment]
There are many nova 404 issues. Routes and assets compile are different issues. Windows aparently have some bugs. No one of past issues detect where is the problem.

Idk if you do all steps done when you rebuild nova assets. But as I said, nova assets and nova path throwing 404 are different issues.

**Comment by menadio** [comment]
> 
> 
>     * Laravel Version: 7.9.2
> 
>     * Nova Version: 3.5.0
> 
>     * PHP Version: 7.2.5
> 
>     * Database Driver & Version: SQL, via XAMP
> 
>     * Operating System and Version: Windows 10
> 
>     * Browser type and version: Chrome
> 
>     * Reproduction Repository: Can i share nova content this way?
> 
> 
> When following the install process via the nova docs, I see a 404 when visiting /public/nova.
> 
> added lines to json
> run composer update
> php artisan nova:install
> php artisan migrate
> added App\Providers\NovaServiceProvider::class to app.php in the config dir, under providers. These werent added automatically.
> I can see the route when doing php artisan route:list:
> localhost/nova2/public/nova | GET|HEAD | nova | nova.index
> 
> I`ve read up the posts I can find on stackoverflow, not sure how to continue.
> 
> UPDATE - beneath, question remaining is can i get this to work via XAMP as well, instead only via php artisan serve

Do you see the nova login route? I had a similar issue where all other nova routes were listed except the login and logout routes. Running `php artisan route:cache` fixed it for me.

**Comment by davidhemphill** [comment]
No one's been able to list steps to reliably demonstrate this on a Window machine, and every time I've tried on mine, it seems to be a user error causing it to not install or some intricacy with tools like XAMP. If it's working with `artisan serve` it's likely a specific issue in XAMP that we wouldn't be able to diagnose and not an issue with Nova itself.

**Comment by stuartcusackie** [comment]
Just to confirm. I need to add **App\Providers\NovaServiceProvider::class** to config/app manually. Windows 10 / Laravel 8 / Homestead / Fresh Install.

**Comment by chrisparma** [comment]
try adding in app/config/app.php 
this line App\Providers\NovaServiceProvider::class

**Comment by mahfoudfx** [comment]
Hello,
I think it is due to that Nova doesn't support sub directory, in your case "localhost/nova2/public/nova", must be "localhost/nova".

**Comment by MarcosGit** [comment]
This works for me:

add this in your virtual host

<Directory /var/www/html/checkin>
    AllowOverride All
</Directory>
