### ISSUE TITLE
Subtitle not working in attach page from BelongsToMany relation

### ISSUE THREAD

**Issue by hnphi** [laravel/nova-issues#2572]
- Laravel Version: 7.9.2
- Nova Version: 3.5.0
- PHP Version: 7.4.3
- Database Driver & Version: MySQL 8

### Description:
Follow this PR [#884](https://github.com/laravel/nova/pull/884)

I have relationship fields:
![code2](https://user-images.githubusercontent.com/13552002/80909289-33d9ca80-8d51-11ea-8755-201779814899.png)

![code](https://user-images.githubusercontent.com/13552002/80909222-e2c9d680-8d50-11ea-89b8-ebc4f4ef6404.png)

Subtitle working with global search:
![has_sub](https://user-images.githubusercontent.com/13552002/80909240-fd9c4b00-8d50-11ea-84fc-1a85fddd8a9f.png)

 and BelongsTo field:
![has_sub_2](https://user-images.githubusercontent.com/13552002/80909262-10af1b00-8d51-11ea-8ac2-ccfb1af8802a.png)

but not working in attach page from BelongsToMany field:
![not_sub](https://user-images.githubusercontent.com/13552002/80909316-74d1df00-8d51-11ea-8650-1bf78547bcfb.png)

**Comment by swetakodur** [comment]
Any update on this issue? We really want to use this. A quick turnaround here will be quite appreciated.

**Comment by schonhoff** [comment]
Have the same issue.
Nova version 3.6 here

**Comment by stu177** [comment]
Same here on 3.6.0.

**Comment by ashleyfae** [comment]
I have the same issue.

**Comment by davidhemphill** [comment]
I believe this feature already works:

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/58970/94727673-ae207200-0324-11eb-8458-9971c19e1fe3.png">

I was able to get this working by specifying the `subtitle` on my `User` resource and using this code:

```php
BelongsToMany::make('Users')->searchable()->withSubtitles(),
```
