### ISSUE TITLE
Unable to provide default for BooleanGroup field

### ISSUE THREAD

**Issue by ziming** [laravel/nova-issues#2573]
Like there is no way for me to specify by default which options are checked and which are not.

**Comment by ziming** [comment]
Thank for informing me stale.

**Comment by jbrooksuk** [comment]
@ziming are you wanting to select default options?
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by ziming** [comment]
It is a bug, not a feature request. @jbrooksuk

**Comment by jbrooksuk** [comment]
It's a feature request, because it's not behaviour that is broken :)

**Comment by emjayess** [comment]
#wtfnova

**Comment by crynobone** [comment]
https://github.com/laravel/nova-issues/discussions/3277

**Comment by emjayess** [comment]
> #3277
> 
> Marking this as implemented.

I find it remarkable that ^ this is considered "implemented", and Laravelco still charges a premium for this package.

🙄
