### ISSUE TITLE
"Card" resource generated JS error

### ISSUE THREAD

**Issue by nowak-ninja** [laravel/nova-issues#2575]
- Laravel Version: 7.9.2
- Nova Version: 3.x
- PHP Version: 7.3.16
- Database Driver & Version: MySQL 5.6.x
- Operating System and Version: Linux
- Browser type and version: Chrome (latest)

### Description:
If I create Nova resource named "Card" it can't be accessed and generates JS error in browser console:

`TypeError: Cannot read property 'length' of undefined`

### Steps To Reproduce:
`php artisan nova:resource -m Card Card`

**Comment by ankkk** [comment]
Yes, I have the same problem

**Comment by jbrooksuk** [comment]
Please make sure that you followed the instructions once you've created the card:

```
You *must* override the uriKey method for your Card resource.
```
