### ISSUE TITLE
Unable to recover after trying to submit a form when offline

### ISSUE THREAD

**Issue by adriaanzon** [laravel/nova-issues#2578]
- Laravel Version: 7.9.2
- Nova Version: 3.5.0
- PHP Version: 7.4.5
- Database Driver & Version: N/A
- Operating System and Version: Reproduced on Windows and macOS
- Browser type and version: Reproduced on Safari and Chrome
- Reproduction Repository: N/A

### Description:

When trying to submit an update form for a resource, while your internet connection is offline, the submit buttons remain disabled, and no error message is shown:

<img width="536" alt="image" src="https://user-images.githubusercontent.com/4326420/81078903-1b9fb200-8eef-11ea-8d93-2ea609c81c9b.png">

The following error appears in the browser's console:
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/4326420/81079105-66212e80-8eef-11ea-8a48-d3da67971a0f.png">

This is especially problematic with long forms that may take a long time to fill out, because, when this happens, the disabled buttons prevent you from resubmitting the form after you fixed your internet connection.

The create form doesn't have this problem, the buttons do not get disabled. But I would at least expect a warning message.

### Steps To Reproduce:

* For an existing resource, open the "edit" form
* Disable your computer's internet connection, mimicking e.g. a Wi-Fi failure
* Try submitting the form by pressing either of the "update" buttons
* Find out that your internet connection failed, and cry out over the fact that you need to fill out your form a second time

**Comment by adriaanzon** [comment]
This issue still exists in Nova 3.7.1

**Comment by jbrooksuk** [comment]
I believe we can use [window.navigator.onLine](https://caniuse.com/#search=navigator.onLine) to detect the online presence and show an alert if you're offline.

**Comment by jbrooksuk** [comment]
Having given this more thought, we'd definitely accept a PR to notify the user when they're offline, but Nova has never stated it works offline, so we're going to close this.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
