### ISSUE TITLE
Global Search interferes With Resource Search

### ISSUE THREAD

**Issue by novocent** [laravel/nova-issues#2579]
- Laravel Version: 7.9.2
- Nova Version: 3.5.0
- Laravel/Scout: v7.2.1
- teamtnt/laravel-scout-tntsearch-driver  v8.1.0     
- teamtnt/tntsearch  v2.3.0   

- PHP Version: 7.3.13
- Database Driver & Version: 8.0.17
- Operating System and Version: osX Catalina 10.15.4
- Browser type and version: FireFox 75

### Description:
The global search search result parameters unexpectedly interfere with results when searching a resource.  When I search for a keyword against a given resource the wrong number of results are shown.

In trying to debug the issue I had a search use case with 7 possible results.  Nova had a search term plus and additional filter which should have narrowed the result to 4 matches. Nova shows 2 matches. 

I manually inspected the sqlLite db index file and confirmed the the correct matches against the DB (in my case 7 without the filter and 4 with the filter). I ran the search manually in tinker and confirmed the correct result (again 7/4). Nova produced 5/2 (without filter/with filter). 

If I disable Scout,  with usesScout(),  on the resource the result is correct (7/4).
if I change $globalSearchResults to a 6 I get 6/3.
If I change $globalSearchResults to a 7 I get 7/4.

$globalSearchResults (default of 5) must be set higher than the total search result count for the main search of a resource to behave properly. 

### Steps To Reproduce:

adjust $globalSearchResults and search a resource that is indexed with Scout.

**Comment by alexpgates** [comment]
@novocent +1. Have you come up with any better solution?

**Comment by tomhelmer** [comment]
I ran into this problem and after som digging i found the problem :

```
 protected static function initializeQueryUsingScout(NovaRequest $request, $query, $search, $withTrashed)
    {
        $keys = tap(static::applySoftDeleteConstraint(
            static::newModel()->search($search), $withTrashed
        ), function ($scoutBuilder) use ($request) {
            static::scoutQuery($request, $scoutBuilder);
        })->take(static::$globalSearchResults)->get()->map->getKey();

        return static::applySoftDeleteConstraint(
            $query->whereIn(static::newModel()->getQualifiedKeyName(), $keys->all()), $withTrashed
        );
    }
```
So scout queries can't return more than $globalSearchResults ( default 5 ) results.

I previous versions this value was hardcoded to 200

Tom

**Comment by fbingha** [comment]
I encountered this as well today .. makes no sense for the resource search to be playing by the globalsearchresults value.

**Comment by fbingha** [comment]
Caused by: https://github.com/laravel/nova/pull/858

**Comment by davidhemphill** [comment]
Yeah I goofed this one up. Just pushed a PR to address this. 👍
