### ISSUE TITLE
Model naming collision.

### ISSUE THREAD

**Issue by jwahdatehagh** [laravel/nova-issues#258]
I have a model named `Card`. The index request fails because of the `/cards`-endpoint defined in Nova's routes file on line 46.

My quickfix is to just move it down below the `/{resource}`. I think Nova should use more unique names for static endpoints like that.

**Comment by bencorlett** [comment]
Yep, I've also experienced this. I ended up just making a bunch of bogus `cardModel` relationships:

```php

/**
 * Get the relationship for the Card this Stamp belongs to.
 */
public function card(): BelongsTo
{
    return $this->belongsTo(Card::class);
}

/**
 * Workaround for the reserved "Card" word in Nova.
 */
public function cardModel(): BelongsTo
{
    return $this->card();
}
```

That works in part, except the sporadic references to `CardModel` in the admin (it appears that the `label()` method isn't respected in some cases, but in others.

**Comment by jwahdatehagh** [comment]
Cool! I resolved it by just naming the Nova Resource sth other than `Card`:

```php
class SkimCard extends Resource
{
    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static $model = 'App\Models\Card';

     // ...
}
```

**Comment by bencorlett** [comment]
Yep, that's what I did:

```php
class CardModel extends Resource
{
    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static $model = 'App\Card';

    /**
     * Get the displayable label of the resource.
     *
     * @return string
     */
    public static function label()
    {
        return 'Cards';
    }
}
```

However, the label doesn't appear to be used on *other* resources referring to the model (in my case, `Stamp` has a Nova `BelongsTo` field):

```php
class Stamp extends Resource
{
    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [
            BelongsTo::make('CardModel'),
        ];
    }
}
```

<img width="408" alt="screen shot 2018-09-18 at 6 59 17 pm" src="https://user-images.githubusercontent.com/181919/45676414-fffa6300-bb74-11e8-9690-77080a25f8a1.png">

**Comment by jwahdatehagh** [comment]
Aaah gotcha!

If you want, you can just overwrite the label functions:

```php

/** {@inheritDoc} */
public static function label()
{
    return 'SKIM Cards';
}

/** {@inheritDoc} */
public static function singularLabel()
{
    return 'SKIM Card';
}

/**
 * Get the value that should be displayed to represent the resource.
 *
 * @return string
 */
public function title()
{
    return str_limit($this->title, 50);
}
```
