### ISSUE TITLE
WithoutTrashed on BelongsToMany and MorphyToMany

### ISSUE THREAD

**Issue by Gummby** [laravel/nova-issues#2585]
Hello is it possible to get WithoutTrashed on BelongsToMany and MorphyToMany as well?

**Comment by jerearaujo03** [comment]
Please!

**Comment by vbezruchkin** [comment]
Hello,

Any chance to have it in one of the upcoming versions? 

Thanks

**Comment by crynobone** [comment]
Duplicate of #2750 

As currently it not possible since pivot relationship itself doesn't contain logic to handle this. https://github.com/laravel/nova-issues/issues/2750#issuecomment-783053029
