### ISSUE TITLE
Unable to render Vue.js in markdown textarea

### ISSUE THREAD

**Issue by connor11528** [laravel/nova-issues#2586]
- Laravel Version: 5.8.3
- Nova Version: 2.0
- PHP Version: 7.2.15

### Description: 
I have a blog built with Laravel Nova [here](https://employbl.com/blog). When I go to write a blog post that includes Vue.js snippets the blog post does not render, instead gives a blank white screen. I published a sample blog post demonstrating the issue here: https://employbl.com/blog/vuejs-markdown-laravel-nova

In my controller I call the `Markdown::parse` method:

```
$markdown = Markdown::parse($post->body);
```
Then render that in a blade file:
```
<div class="col-lg-8 col-md-10 mx-auto blog-post-content">
      {{ $markdown }}
</div>
```

This is the `Post` model I have in **app/Nova/Post.php**:

```
class Post extends Resource
{
    public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
            BelongsTo::make('User')->rules('required'),
            Text::make('Title')->rules('required')->sortable(),
            Text::make('Subtitle')->rules('required')->hideFromIndex(),
            Text::make('Slug'),
            Text::make('Featured Image'),
            Text::make('Canonical Url'),
            Markdown::make('Body')->rules('required'),
            DateTime::make('Published On')->rules('required'),
        ];
    }
```

### Steps To Reproduce:
- Create a model with a markdown field
- Add Vue.js code to the markdown
- Try to render the Vue.js code as markdown

**Comment by jbrooksuk** [comment]
You need to escape your content.


This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](https://larachat.co/).
