### ISSUE TITLE
Reload index view when clicking on menu button

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#2587]
I've got an overview with orders with a payment status column. This payment status column is changed when a user pays an order with an external service. 

When i click on the left menu link the resource is not reloaded. Instead i have to press F5 to reload the resource.

**Comment by preliot** [comment]
still an issue (or request)...

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by preliot** [comment]
Bypassed by adding recent polling feature:

Nova\MyResource.php
```php
 /**
     * Indicates whether the resource should automatically poll for new resources.
     *
     * @var bool
     */
    public static $polling = true;

/**
     * The interval at which Nova should poll for new resources.
     *
     * @var int
     */
    public static $pollingInterval = 15;

```
