### ISSUE TITLE
Bug: CustomLensHeader frontend component not imported into assembly

### ISSUE THREAD

**Issue by oleksandr-roskovynskyi** [laravel/nova-issues#2588]
- Laravel Version: 6.18.13
- Nova Version: 2.12.0
- PHP Version: 7.3
- Browser type and version: Chromium 81.0 (Vue DevToos)

### Description:
CustomLensHeader frontend component not imported into assembly nova/resources/js/components.js

To fix the error, you need to add the following to this file:
```
import CustomLensHeader from '@/components/CustomLensHeader'

Vue.component('custom-lens-header', CustomLensHeader)
```

### Steps To Reproduce:
https://nova.laravel.com/docs/2.0/customization/frontend.html#vue-devtools
and go to any lens, the error will appear in Vue DevTools
![image](https://user-images.githubusercontent.com/57599426/81332600-01f79980-90ac-11ea-8994-46743ec6a186.png)

```
[Vue warn]: Unknown custom element: <custom-lens-header> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Lens> at resources/js/views/Lens.vue
       <Root>
```

**Comment by oleksandr-roskovynskyi** [comment]
Correct this mistake, I pointed out its essence and solution!

**Comment by jbrooksuk** [comment]
We accept PRs on the main Nova repo as well :)
