### ISSUE TITLE
SESSION_DOMAIN .env variable prevents Nova axios requests from working

### ISSUE THREAD

**Issue by jbraband** [laravel/nova-issues#259]
Laravel Version: 5.6.35 (clean install)
Nova Version: 1.0.6 (clean install)
-------------------------------------------------------

I have an existing site onto which I am installing Nova. Everything is good except creating/saving content i.e. any POSTing to the server-side API.

I have identified the issue to be our site's setting of SESSION_DOMAIN=.mydomain.com in .env

This setting is there since our site uses multiple subdomains and we need authentication (therefore cookies) to be shared across them.

To better troubleshoot and confirm this I installed a clean 5.6.35 environment, and setup authentication with php artisan make:auth

I then installed Nova 1.0.6 and got that functional even to the point of being able to successfully save content.

I then set SESSION_DOMAIN in .env to .mydomain.com, clear laravel's config, cache laravel's config, clear my browser cookies, and re-login to Nova.

At this point, saving content returns HTTP Status 419 on every POST request.

I have whittled it down to the fact that the Axios client is not properly adding the X-XSRF-TOKEN header from the XSRF-TOKEN cookie. For whatever reason, the front-end javascript is unable to pull cookie value's from cookies when .env's SESSION_DOMAIN is set.

Please let me know if further clarification is needed or anything I can do to help track this down further

**Comment by jbraband** [comment]
I should maybe added that this is over SSL and using the default 5.6.35 values for session.secure (false) and session.http_only (true)

Changing session.secure to true is allowing Axios to read the cookie and add the X-XSRF-TOKEN header, but the POST is still rejected with 419. I am digging further in at the moment.

**Comment by jbraband** [comment]
alrighty, here's a work-around that allows Nova's javascript to retrieve the XSRF-TOKEN cookie with a root domain set. I override the addCookieToResponse in the default VerifyCsrfToken middleware. instead of always passing $config('session.domain') to the Cookie constructor, pass null if $request->is('nova/*') is true

'''php
<?php

namespace App\Http\Middleware;

use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as Middleware;
use Symfony\Component\HttpFoundation\Cookie;

class VerifyCsrfToken extends Middleware
{
    /**
     * The URIs that should be excluded from CSRF verification.
     *
     * @var array
     */
    protected $except = [
        //
    ];

    /**
     * Add the CSRF token to the response cookies.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Symfony\Component\HttpFoundation\Response  $response
     * @return \Symfony\Component\HttpFoundation\Response
     */
    protected function addCookieToResponse($request, $response)
    {
        $config = config('session');

        $response->headers->setCookie(
            new Cookie(
                'XSRF-TOKEN', $request->session()->token(), $this->availableAt(60 * $config['lifetime']),
                $config['path'], $request->is('nova/*') ? null : $config['domain'], $config['secure'], false, false, $config['same_site'] ?? null
            )
        );

        return $response;
    }

}
'''

**Comment by davidhemphill** [comment]
Closing as this seems like an edge case.

**Comment by meduzen** [comment]
Encountered the same issue. Here’s [how I solved it](https://laracasts.com/discuss/channels/laravel/laravel-57-session-not-maintained-while-using-subdomains?page=1#reply=510811). Not even sure why it occurred and why what I did solved it.
