### ISSUE TITLE
Metrics Value start date

### ISSUE THREAD

**Issue by halah-m** [laravel/nova-issues#2590]
- Laravel Version: 7.10.2
- Nova Version: 3.0.2
- PHP Version: 3.3.12

### Description:
There's an issue in nova Metrics Value, where it don't count the rows that is created today, if I changed the date to yesterday, it works.

**Comment by davidhemphill** [comment]
Nova metrics use the user's browser timezone. Sometimes that causes certain resources to not show up that are in the future in UTC. This is confusing and will probably be changed in a later version, but for now, it's the way they're designed. You can get around this by specifying Nova's timezone `Nova::userTimezone`.

**Comment by AlbinoDrought** [comment]
User timezone support makes sense. Trend metrics return expected values but Value metrics return unexpected values (as OP noted: yesterday's values / outdated values).

Do these metric types interact with `Nova::userTimezone` differently? Trend metrics (and associated timezone features, if they exist) work perfectly.
