### ISSUE TITLE
Image field - unable to change URL (again)

### ISSUE THREAD

**Issue by syntafin** [laravel/nova-issues#2591]
- Laravel Version: 7.10.3
- Nova Version: 3.5.0
- PHP Version: 7.4.5
- Database Driver & Version: MySQL
- Operating System and Version: Windows 10 1909
- Browser type and version: Vivaldi 3.0.1874.38 (also Brave and Chrome)
- Reproduction Repository: https://github.com/XIVDATA/dev (Repo is private)

### Description:
Unable to recive the correct path to an image, even there is a path set.
Example:
```
Image::make('Avatar')
           ->disk('ffxiv')
           ->path('avatar')
           ->disableDownload(),
```

The disk is setup correct, but the URI at the end ignoring the `path()`.

The same Bug issued [here](https://github.com/laravel/nova-issues/issues/127) before, was fixed with Laravel 5.7 and Nova 1.0.17, booth an earlier version then I using at the moment.

### Steps To Reproduce:
1. Setup a Image Field
2. Store Images outside the root folder of selected disk
3. Set the path to the subfolder in the Image field

**Comment by syntafin** [comment]
Tested now under later production system:

* Laravel Version: 7.10.3
* Nova Version: 3.5.0
* PHP Version: 7.4.5 (FPM)
* Database Driver & Version: MySQL/MariaDB 10.4.12
* Browser Type: Vivaldi/Brave/Chrome (actual stable builds)

**Comment by simonpeters** [comment]
I'm having the same issue. path is ignored.

**Comment by crynobone** [comment]
Will check on this next week. I imagine right now stored image field doesn't contain the path in the database, right?

**Comment by syntafin** [comment]
Correct. I can post how I fixed it, as soon as I am on pc. I will edit this comment :).

**Comment by crynobone** [comment]
> Correct. I can post how I fixed it, as soon as I am on pc. I will edit this comment :).

Still waiting for the update and I'm not clear regarding item 2 and 3 on the original **Steps To Reproduce**

**Comment by syntafin** [comment]
Sorry, totally forgot that.....

The fix was more a workaround. Instead of trying do define a folder like here:

```
Image::make('Avatar')
           ->disk('ffxiv')
           ->path('avatar')
           ->disableDownload(),
```

I just create a different Disk in the config:
```
Image::make('Avatar')
           ->disk('ffxiv_avatar')
           ->disableDownload(),
```
```
'ffxiv_avatar' => [
            'driver' => 'local',
            'root' => storage_path('app/public/ffxiv/avatar'),
            'url' => env('APP_URL').'/storage/ffxiv/avatar',
            'visibilty' => 'public',
        ],
```

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/101732901-e7c9e200-3af8-11eb-9913-4d21f1b8c84b.png)

![image](https://user-images.githubusercontent.com/172966/101732978-04661a00-3af9-11eb-8a58-2442b52d162e.png)

I cannot replicate the issue on latest Laravel Nova. You can review the code at https://github.com/nova-issues/issue-2591/commit/e5850f8e0c1283a773b343525cc7c7fa7ae89a16
