### ISSUE TITLE
text in value matrices is outside of card's border

### ISSUE THREAD

**Issue by osamaAbdullah** [laravel/nova-issues#2592]
![image](https://user-images.githubusercontent.com/26807223/81435136-01283b80-9170-11ea-9f80-ccc284e5ed43.png)

**Comment by jbrooksuk** [comment]
Sorry, but there's not enough information to go off of here. If the issue you have still persists, please feel free to open a new issue with all the details of what you're trying, what you expect to happen, what's happening, and how to reproduce it. Thanks!
