### ISSUE TITLE
How to remove / disable create button

### ISSUE THREAD

**Issue by mikeerickson** [laravel/nova-issues#2593]
I am trying to figure out a way to either disable or remove the `Create` button?  I am wanting to disable this on a per resource basis?  I have created the appropriate Policy to see if that would help, but alas it does not work either.

**Comment by vesper8** [comment]
Would like to know the same. I would like to make all resources "read-only". I understand that using policies you can prevent actions such as create/delete/update, but I would like to allow users to browse records and not have the edit/delete/create buttons visible at all

**Comment by vesper8** [comment]
Ok that was easy... just add this to your Nova resource file

```
    public static function authorizedToCreate(Request $request)
    {
        return false;
    }

    public function authorizedToDelete(Request $request)
    {
        return false;
    }

    public function authorizedToUpdate(Request $request)
    {
        return false;
    }
```

This will hide the delete, edit and create buttons for everyone. If you would like to only hide it for certain users it's probably best to use policies, or I suppose you can do a check inside the methods above

**Comment by mikeerickson** [comment]
@vesper8 I have added as you documented to the resource class in question, but the buttons to create and all individual rows buttons appear?
