### ISSUE TITLE
BelongsToMany doesn't respect singularLabel in edit-attached/attach

### ISSUE THREAD

**Issue by genesiscz** [laravel/nova-issues#2598]
- Laravel Version: xxx
- Nova Version: v3.1.0
- PHP Version: 7.4.0
- Database Driver & Version:

### Description:
I have Product resource having BelongsToMany variants field:

```
 BelongsToMany::make(__("Variants"), "variants", Variant::class)->fields(function() {
                return [
                    Text::make(__("Price addition"), "price_addition")),
                ];
            })->singularLabel("Variant"),
```

I click edit attached (url looks like `nova/resources/products/7/attach/variants?viaRelationship=variants&polymorphic=0`)

The label of the form is "Update Variant".

However, the field itself doesn't show the singular label:

![image](https://user-images.githubusercontent.com/1512353/81595853-6cb61700-93c3-11ea-95ff-ca6dd690fb6e.png)

**Comment by genesiscz** [comment]
This is still an issue

**Comment by genesiscz** [comment]
Still an issue

**Comment by genesiscz** [comment]
Okay.

**Comment by alex-osborn** [comment]
This is still an issue, using v3.30.0. Additionally the singularLabel() of the resource is ignored.

**Comment by NessterGit** [comment]
Still an issue. v4.21.00
