### ISSUE TITLE
relationship pagination can go out of page

### ISSUE THREAD

**Issue by BostjanOb** [laravel/nova-issues#260]
When looking at a relationship and using pagination you can click next too many times.

This is not a problem when you are clicking slowly, but if you want to go to the end and click next very fast it will not block the last click.

Gif example: http://recordit.co/TW1xtZ7m76

Version: 1.0.6
How to reproduce:
1. Go to the last page
2. Go back 1 page
3. Quickly click next 2 times

**Comment by Etmolf** [comment]
What we do in such cases is pass the `loading` boolean as `prop` to all child components and simply set the `disabled` property of the pagination buttons based on that.

The `<PaginationLinks>` component is a child of `<Card>` which itself is a child of `<LoadingCard>` which holds the needed `loading` state.

So i see 2 possible solutions:

- Pass the `loading` state as prop to the `<PaginationLinks>` component
- Use the global Nova EventBus

That way it is nearly impossible to go out of range (based on our own experience with vue paginations)

Should be an easy fix also :-)

**Comment by davidhemphill** [comment]
I wasn't able to get this to happen for me, and this fix is not the same as this fixes suggested above, but if you go out of range you now have access to the pagination to click back so...
