### ISSUE TITLE
Default Value for Action Fields

### ISSUE THREAD

**Issue by 949mac** [laravel/nova-issues#2600]
It doesn't look like this is possible or well documented.

I have a scenario where the Fields in an Action modal work perfectly, but many times there is a default value which should go along with it that the user should see.

https://nova.laravel.com/docs/3.0/resources/fields.html#default-values doesn't seem to apply to Actions.

Best Regards,

Mike

**Comment by jmarcher** [comment]
I can confirm this issue is still there on v3.6

**Comment by ragingdave** [comment]
@davidhemphill Although this says it was addressed in 3.9.0, it seems it wasn't completely addressed, or in general addressed for at least the date field. In v3.9.1, the Date field, will be buggy depending on the default value you send it. For example, if it's today's date, then the placeholder is set, but the field isn't actually filled in, but if you set the default to tomorrow, then the field is filled in appropriately. Just appears to be a UI thing as the actual value is sent through correctly and even passes validation.

**Comment by davidhemphill** [comment]
The Date field issue was fixed in v3.9.3 which was just released. 👍
