### ISSUE TITLE
[Feature Request] Can we have the ability to sort resource group, similar to how you can sort resources

### ISSUE THREAD

**Issue by vesper8** [laravel/nova-issues#2605]
https://github.com/laravel/nova-issues/issues/2287 shows how you can sort resources by adding a priority flag and regsitering it in the NovaServiceProvider. This works great (and I believe is still undocumented).

But, like many, I've organized my resources into groups and now I have so many groups and resources that I would like to be able to define the order of the groups without having to number them 1-10

So maybe we could have a `sortResourceGroupsBy` added ? : )

On a side note, it would be nice to be able to collapse/expand resource groups.. my sidebar has gotten really really high

Cheers

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by wbemanuel** [comment]
@vesper8 Here's is my workaround: https://github.com/laravel/nova-issues/issues/1663#issuecomment-703699411
