### ISSUE TITLE
Unable to clear a nullable DateTime field

### ISSUE THREAD

**Issue by rreynier** [laravel/nova-issues#2606]
- Laravel Version: 7.9.2
- Nova Version: 3.5.0
- PHP Version: 7.4.5
- Database Driver & Version: mysql 5.7
- Operating System and Version: Ubuntu 18.04
- Browser type and version: Chrome  81.0.4044.129

### Description:

I have a property on my Blog resource defined as such:

```
DateTime::make('Published at')->nullable(true)
```

Once you have clicked the DateTime input and the picker appears, it is impossible to clear the date and time again. You can select the text in the input, and clear it, but as soon as you focus out the date/time gets filled in. 

To note, the regular Date input (which has the same picker minus the hours) does work as expected. 

### Steps To Reproduce:
- create new resource 
- click the date time input
- try to clear the input

**Comment by mauricoder** [comment]
Same problem here. When a DateTime field got a value it's impossible to make it null again

**Comment by mikeerickson** [comment]
Thanks for reporting this, it was driving me nuts and I poured docs and google, but nada.  Then I see this report 🤓

**Comment by gkermer** [comment]
Same here. I would appreciate a fix for this.

**Comment by ziming** [comment]
This is a longstanding problem. The way i deal with it currently is with a custom nova action to set the datetime field to null.

The other thing i hope the datetime field could do is to auto prepopulate with the current time when i select the date.

**Comment by rreynier** [comment]
Ideally there would be a more explicit way to clear the input to be null. Maybe a button to clear it?

**Comment by ckuhnsmtr** [comment]
I'm having this same problem. @ziming  thanks for the suggestion about the custom action to clear the date. That workaround will work for me for now but in the future it'd be nice to be able to clear the input without resorting to a custom action.

**Comment by chrispage1** [comment]
There are a few too many workarounds with Nova for my liking! I've got the same issue.

The use case is a post published timestamp. It would be great to see this resolved!

**Comment by Equruler** [comment]
It is the same as #2358 

For those who need temporary solution.

Just add this code, (a button as help()) after your Field which do a clear datetime field function:

`
DateTime::make('datetime')->help("<div class='flex flex-col'><div class='ml-auto text-sm font-bold text-primary cursor-pointer dim' style='font-style: normal;'
                onclick = \"this.parentElement.parentElement.parentElement.querySelector('input')._flatpickr.clear()\" 
                >Clear</div></div>"
`

**Comment by chrispage1** [comment]
@Equruler - nice solution. I've created a pull request which cements this a little more into the field

**Comment by gonzunigad** [comment]
@chrispage1 can you link the PR here? :)

**Comment by chrispage1** [comment]
@gonzunigad sure it's https://github.com/laravel/nova/pull/907

It's tagged as `needs work` but that work has been done.

**Comment by dillingham** [comment]
@jbrooksuk looks like this was merged in but I don't see it on the release notes 🤔

https://github.com/laravel/nova/pull/928

**Comment by chrispage1** [comment]
Yep, time to close this issue 👍

**Comment by davidhemphill** [comment]
Fixed via laravel/nova#907

**Comment by j-dexx** [comment]
@davidhemphill can you detail how to actually do this please.  

There's this - https://nova.laravel.com/docs/3.0/resources/fields.html#nullable-fields which I've done but there's nothing in the datetime dropdown that I can see that allows you to clear it.

If you delete the contents of the field when I click off the field again it get's filled with the current date at noon
