### ISSUE TITLE
Default value does not work for BelongsTo and MorphTo fields

### ISSUE THREAD

**Issue by kitbs** [laravel/nova-issues#2608]
- Laravel Version: 7.11.0 (fresh install)
- Nova Version: 3.6.0 (fresh install, no other packages)
- PHP Version: 7.3.8
- Reproduction Repository: https://github.com/kitbs/freshnova/tree/test-default

### Description:
The `default()` method released in v3.4.0 does not work for BelongsTo and MorphTo fields:
- When BelongsTo is not searchable, the default value appears to be selected, but when the Create button is clicked, no value is sent in the POST request, and a "The ... field is required" validation error appears.
- When BelongsTo is searchable, no default value is selected.
- There is no ability to specify the default morphable type for a MorphTo field, and no default value is selected.

#### BelongsTo (not searchable)
- Create a [Post](https://github.com/kitbs/freshnova/blob/test-default/app/Nova/Post.php) resource with a BelongsTo field and corresponding relationship on the [model](https://github.com/kitbs/freshnova/blob/test-default/app/Post.php):
  ```php
  BelongsTo::make('Author', 'author', User::class)
      ->default(auth()->id()),
  ```
- Navigate to the create route for the Post resource.
- Observe the BelongsTo field appears to be filled with the current user's name.
- Click "Create Post" without changing any fields.
- Observe the "The author field is required." validation message appears.
- Open Developer Tools > Network and find the failed POST request.
- Observe the `author:` key in the Form Data is empty.

#### BelongsTo (searchable)
- Add a searchable BelongsTo field to the Post resource:
  ```php
  BelongsTo::make('Co-author', 'coauthor', User::class)
      ->searchable()
      ->default(auth()->id()),
  ```
- Navigate to the create route for the Post resource.
- Observe the BelongsTo field has no value selected.
- As above.

#### MorphTo
- Create an [Image](https://github.com/kitbs/freshnova/blob/test-default/app/Nova/Image.php) resource with a MorphTo field and corresponding relationship on the [model](https://github.com/kitbs/freshnova/blob/test-default/app/Image.php)
  ```php
  MorphTo::make('Imageable', 'imageable')
      ->default(auth()->id())
      ->types([
          Post::class,
          User::class,
      ]),
  ```
- Note that there is no way to specify whether the Post or User type should be defaulted.
- Navigate to the create route for the Comment resource.
- Observe that no default value is selected.
- As above.

**Comment by vesper8** [comment]
Don't mean to hijack but I think it's related, I'd like to add that `default()` does not seem to work for the `Hidden` field either. I've added it to a form along with other form inputs, all fields work except the `Hidden` one which is just blank no matter what I do

I tried following the example

```
Hidden::make('Slug')->default(Str::random(64));
```

as well as 

```
Hidden::make('Slug')->default('test');
```

And the value of Slug is always empty

**Comment by ziming** [comment]
Can confirm, this need fixing.

**Comment by jbrooksuk** [comment]
@vesper8 I'm not able to replicate your issue with `Hidden` fields. The value is always set for me in v3.7.x

@kitbs it seems that the issue with `default` specifically occurs for `BelongTo` fields that are `searchable`. It looks like the `MorphTo` field also doesn't work with `default`, regardless of whether it's `searchable`.

**Comment by brtastic** [comment]
Default value works well for values but for relationships it does not use value anymore but a `belongsToId` field (for BelongsTo).
Fixing it seem to require something like this:
```
'belongsToId' => $this->belongsToId ?? $this->resolveDefaultValue(app(NovaRequest::class)),
```
in `jsonSerialize` method of BelongsTo. With this, it actually saves the default value if there is no value specified. Why even use `belongsToId` instead of simply re-using the value?

Not sure if there will be any bugs introduced by the line above, seems to work fine for me

**Comment by FreekVR** [comment]
I can confirm this doesn't work for BelongsTo fields, in fact, I used the _exact same_ setup as in the documentation:

https://nova.laravel.com/docs/3.0/resources/fields.html#default-values
```
BelongsTo::make('Name')->default($request->user()->getKey()),
```

The default value shows up correctly in the UI, but the validation fails on "The Name field is required."

**Comment by azurinspire** [comment]
Default value for `BelongsTo` without searchable seems to work but not with it, should it work?

**Comment by azurinspire** [comment]
I have Nova v3.14.0 installed and this problem still exists, default value is selected when creating new resource but when I click Create button, there is an error saying field is required.

**Comment by crynobone** [comment]
@azurinspire I would advised creating a new issue with full reproducing example/code instead of commenting on a closed issue. It easier to look on each bug individually instead of trying to figured out new issue vs existing issue (already fixed) here.

**Comment by azurinspire** [comment]
@crynobone I don't think there is a new issue, if you follow @kitbs original issue description and just run `composer update` to update Nova to latest version, the same problem exists still in that example also. Of course I can open a new issue with exactly the same description if that helps.

**Comment by crynobone** [comment]
Create new issue.
