### ISSUE TITLE
Allow click on current menu item to reload page

### ISSUE THREAD

**Issue by Andy-Baker** [laravel/nova-issues#261]
If we want to see more recent data for a resource, we have to either hit F5 and reload everything, or click to another resource then back again.

I think click-is-reload is simplest but other options would be a refresh button, or allowing ajax updates every N seconds as part of the model class.

**Comment by bayareawebpro** [comment]
Yeah we also need this ability to open a new tab.

**Comment by davidhemphill** [comment]
Vue's router doesn't support this. :-/
