### ISSUE TITLE
Disable reload on Action-Events index list

### ISSUE THREAD

**Issue by orlyapps** [laravel/nova-issues#2611]
Hello,

another small detail. The action-event index list reloading every 15 seconds. This is great to see always the the newest events. But when you want to study and slowly ready through the events it gets reloaded :)

A config would be great for this.

Thanks

**Comment by crynobone** [comment]
I believe you can do the following now (from any service provider):

```php
Laravel\Nova\Actions\ActionResource::$polling = false; // disable polling
```

or 

```php
Laravel\Nova\Actions\ActionResource::$showPollingToggle = true; // show toggling button
```
