### ISSUE TITLE
Feature request: resource copying

### ISSUE THREAD

**Issue by noith** [laravel/nova-issues#2612]
Hello. I'd like to propose a new feature of resource copying or auto populating fields on creation form with data from for example get request.
I think for e-commerce dashboards this is a cool feature for adding new products just by copying another and editing.
Population of creation form with get request is cool for creating products from some another data source

**Comment by latwelve** [comment]
You could do this yourself with an action very easily

**Comment by noith** [comment]
Actually I wanted to, but didn't find how to pass values to creation form of resource. 
I would be glad if you give me a hind

**Comment by noith** [comment]
> You could do this yourself with an action very easily

Actually I wanted to, but didn't find how to pass values to creation form of resource.
I would be glad if you give me a hind

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
