### ISSUE TITLE
withSubtitles() on BelongsToMany

### ISSUE THREAD

**Issue by latwelve** [laravel/nova-issues#2613]
The addition on withSubtitles() on BelongsTo is great but it has exactly the same use to be part of BelongsToMany.. 

Use case:
When selecting related Users for a Resource if multiple Users have the same name it's impossible to tell them apart without making their title include this information (a little messy)

Adding withSubtitles() to related fields would allow a way to display unique data like an email address for the search... exactly the same as it does with belongsTo() 

Thanks!

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
https://github.com/laravel/nova-issues/issues/2572#issuecomment-701580519
