### ISSUE TITLE
Long text for belongsto field set in broken css

### ISSUE THREAD

**Issue by socramjunio2** [laravel/nova-issues#2616]
- Laravel Version: 7.6.#
- Nova Version: 3.5.#
- PHP Version: 7.4.#
- Database Driver & Version: Mysql 8
- Operating System and Version: Unbuntu.20
- Browser type and version: Chrome.latest
- Reproduction Repository: https://github.com/###/###

### Description:
Long text for belongsto field set in broken css

### Steps To Reproduce:
Put a long name in the field
[Screen shot](https://trello-attachments.s3.amazonaws.com/5e8216c1d7e4875ccb7a9adf/5ebe9c83c4486a867ea183aa/4cbd7f33809ffa8749c08b0b9bb8d631/image.png)

**Comment by jbrooksuk** [comment]
@davidhemphill I think we should set a max-width and truncate longer text, what do you think?

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/99907743-7973da00-2d19-11eb-8f7d-32d9f64ba487.png)

![image](https://user-images.githubusercontent.com/172966/99907750-87c1f600-2d19-11eb-9a8a-34f5e70df619.png)

This everything working as expected.
