### ISSUE TITLE
Icon-shaped inline action button

### ISSUE THREAD

**Issue by socramjunio2** [laravel/nova-issues#2617]
I need to put an icon in the inline action to standardize the buttons as shown in the screen shot, if this functionality already exists I haven't seen it.

Thank you.

![Button clone icon](https://trello-attachments.s3.amazonaws.com/5e8216c1d7e4875ccb7a9adf/5ebe9ba16a61c7508854f4bc/79e622b494a3f495bc636ecea8f1d808/image.png)

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by bernhardh** [comment]
It would result in a much cleaner UI.

**Comment by rikiless** [comment]
@bernhardh I used your solution. But it also impacts button in confirm dialog so I have to cancel this confirmation modal.
<img width="1440" alt="Screenshot 2021-03-15 at 12 24 39" src="https://user-images.githubusercontent.com/589851/111146249-8008b480-8589-11eb-829f-0f16ee68f582.png">
.

**Comment by bernhardh** [comment]
@rikiless haven't used it with the confirmation dialog, but you can easily fix it by adding the `table` selector befor it:

```
table .index-my-custom-action {
    ...
}
```

then the icon will only appear inside tables.
