### ISSUE TITLE
Total resource count in pagination is not formatted (no thousand separator)

### ISSUE THREAD

**Issue by chescos** [laravel/nova-issues#2619]
- Laravel Version: 7.11
- Nova Version: 3.6.0
- PHP Version: 7.4

### Description:

The total resource count in the resource pagination is not formatted, there is no thousand separator applied.

Here's an example:

![Example](https://media.chescos.me/s/GgM2Gb.png)

**Comment by crynobone** [comment]
This should have been fixed via laravel/nova#918
