### ISSUE TITLE
Question: Can I extend resources and used in custom nova tool?

### ISSUE THREAD

**Issue by squierll** [laravel/nova-issues#262]
It is possible to extend resource controller and used in nova tool?
So that could be using all features and customize controllers and routes for e.g using external API services.
What is the best solution?
Or is better to build tool from zero?

**Comment by lucasromanojf** [comment]
Hello, did you find a solution?

**Comment by squierll** [comment]
Yes, i find solution, but it's not optimal.

For now I'm using Observers.
Laravel Nova is an excellent tool that saves you a lot of time.
To save time and simplify work, it would be great that you could use and extend base nova resource controller in custom nova tools.

**Comment by lucasromanojf** [comment]
I agree, extending would be better. Hope they do this in a near future.
