### ISSUE TITLE
Feature Request: Show / hide fields via checkboxes on index

### ISSUE THREAD

**Issue by Grayda** [laravel/nova-issues#2622]
I had a look around to see if this was already an issue, but with 2,600 issues, I wasn't able to find anything.

Some of my resources have a LOT of fields, and it's making my index cluttered. I'd like to see a feature where I could show / hide fields via a series of checkboxes, so users could set up their own views to only see what they want to see. It'd be great if these could be persisted so you wouldn't have to tick and untick every time you refreshed the page. 

I've created a mockup here: 

![image](https://user-images.githubusercontent.com/4891563/82014328-bfdbe280-96bf-11ea-9e9d-312cf685fdb1.png)

My first thought was to create a filter that listed all the fields, and used a callback to `hideOnIndex()` to show / hide fields that way, but having this built in would be far better. I also searched for a third party package that could do this, but I wasn't able to find one either.

I know that lenses are supposed to achieve something like this, but again, that's a pre-set list of fields that the end user can't customize, and I had envisioned a Javascript solution that would instantly hide / show fields as you ticked them.

EDIT: Another welcome feature related to this would be drag & drop ordering of the fields. I probably wouldn't use it personally, however others might.

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by jbrooksuk** [comment]
@Grayda check out https://twitter.com/jbrooksuk/status/1283012864282972160
