### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by ankkk** [laravel/nova-issues#2627]
- Laravel Version: 7.11.0
- Nova Version: 3.6.0
- PHP Version: 7.4
- Database Driver & Version: Postgres 12
- Operating System and Version: Mac OS (10.15.4)
- Browser type and version: Chrome 83 (Beta)
### Description:

I have a model with name: `Card`. When trying to open a resource , I get an error:
```js
TypeError: Cannot read property 'length' of undefined
```
And network 200 GET response: 
```json
[{"width":"full","component":"help","prefixComponent":false,"onlyOnDetail":false}]
```

**Comment by alanpilloud** [comment]
I also had the same issue. This comes from the resource being also named `Card`.

Then, I noticed that this warning was shown after the resource creation :

`You *must* override the uriKey method for your Card resource.`

I found the solution here : https://github.com/laravel/nova-issues/issues/857

Which is to add this method in the Nova resource : 

```
/**
 * Get the URI key for the resource.
 *
 * @return string
 */
public static function uriKey()
{
    return 'kard';
}
```

**Comment by jbrooksuk** [comment]
When you generate a resource, if it's using a reserved name - like "Card" - you are asked to override the `uriKey`.
