### ISSUE TITLE
Panel doesn't work when creating new/updating resource data. Panel only appears when displaying details

### ISSUE THREAD

**Issue by khairulamri** [laravel/nova-issues#263]
Laravel version: 5.7
Nova version: 1.0.6

**Comment by telkins** [comment]
I thought this was a bug, too.  But, then I read the docs: https://nova.laravel.com/docs/1.0/resources/fields.html#field-panels

>If your resource contains many fields, your resource **"detail"** screen can become crowded. For that reason, you may choose to break up groups of fields into their own "panels"

So, perhaps it's by design...?

But or not, I think it would be nice to be able to "panel" create/update views.  :-)

**Comment by freshface** [comment]
Would be nice to have this on edit/add views

**Comment by davidhemphill** [comment]
duplicate of #29
