### ISSUE TITLE
Empty nova.name produces margin on global search

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#2631]
- Laravel Version: 7.12
- Nova Version: 3.6.0

### Description:

If you set the config in nova.name to `''` an empty string the link element still produces `mr-6` which pushes the global search out of alignment with other elements on the page.

before
![before](https://user-images.githubusercontent.com/29180903/82366388-1f97fd80-99e0-11ea-8b4a-09c070dfef7c.png)

after
![after](https://user-images.githubusercontent.com/29180903/82366408-245cb180-99e0-11ea-8b08-93461c850dec.png)

**Comment by vladski** [comment]
Set it to NULL instead

**Comment by dillingham** [comment]
@vladski thanks
