### ISSUE TITLE
Q: "NavigationDuplicated" error in vendor.js - Editing a resource - Text field - Underscore escaping?

### ISSUE THREAD

**Issue by nea** [laravel/nova-issues#2632]
- Laravel Version: 7 (current)
- Nova Version: 3.6.0
- PHP Version: 7.4
- Database Driver & Version: MySQL
- Operating System and Version: Win10
- Browser type and version: Chrome 81

### Description:
Hi there,

we have a User resource and try to edit the resource. Everything works fine, route is called `nova/resources/users/1/edit`, user is edited. Changing a field and clicking "Update User" results in the following error:

```
{_name: "NavigationDuplicated", name: "NavigationDuplicated", message: "Navigating to current location ("/resources/users/1/edit") is not allowed", stack: "Error↵    at new e (http://localhost:8000/vendor/n…dor/nova/app.js?id=587ceb744944d21f5cff:1:653653)"}
```

I commented out all relations already, all filters etc. Tried changind boolean fields, text fields etc. but always the same error and I am really starting to have any idea where and how as here is also no more on that error, where it origins and why.

Any help is appreciated.

Thanks a lot in advance

**Comment by nea** [comment]
As additional information, after commenting out every field and adding them one after the other, this field leads to a fail: `Text::make('Locale', 'locale')`

That is just a normal varchar field on the User model. No special handling on the model, no Attribute magic, nothing. Comment out, works. Comment in, broken!

Really lost a little ^^'

**Comment by nea** [comment]
One more feat:
If `locale` is e.g. `en_GB` I cannot change any field until I change the locale. If the field contains multiple underscores or non, e.g. `en__GB` I can change other fields without changing the locale and the error does not pop-up.

Is this maybe an escape issue?


Thanks

**Comment by nea** [comment]
Another addition:
A text field not named `Locale` works with text input such as `en_GB`. Text and field `Locale` does not. The mere presence breaks the update. If changed itself (_dirty_ flag?) it works once.

It seems the combination of field and content triggers some odd behaviour.

**Comment by crynobone** [comment]
I was unable to recreate the issue on latest Laravel Nova. Can you share reproducing code to validate the issue.

I'm aware of potential NavigationDuplicated when using vue router and a PR is being done for other use case, but editing resources at the moment failed to yield the same error. 

Reference: https://stackoverflow.com/questions/57837758/navigationduplicated-navigating-to-current-location-search-is-not-allowed
