### ISSUE TITLE
MorphTo field does not show field name on detail - part 2

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#2634]
Laravel Version: 7.11.0
Nova Version: 3.6.0
PHP Version: 7.2.19
Database Driver & Version: mysqlm 5.7.24
Operating System and Version: windows 10
Browser type and version: chrome 81 (64 bits)

**Description:**

A morphto field does not show it's field name on detail, which means the presented information is without it's context.

```php
 $fieldsGeneric[] = Fields\MorphTo::make(ucfirst(__('owned_by')), 'ownedBy')->types([
                        \App\Nova\Supplier\Distributor::class,
                        \App\Nova\Supplier\Supplier::class,
                    ]);
```
**Detail resource**

This results in:

Supplier: MySupplier

I was expecting someting like this:

Owner: Supplier MySupplier or perhaps
Owner: MySupplier (Supplier)

(Please note the word owner)

(This issue was already reported earlier [https://github.com/laravel/nova-issues/issues/2444](https://github.com/laravel/nova-issues/issues/2444) but closed. Not sure if i should comment there or add a new issue.)

**Comment by equinoxmatt** [comment]
Also having this issue, it makes the information in the detail view very confusing.

**Comment by equinoxmatt** [comment]
This is also still a problem in v2.12.0

**Comment by crynobone** [comment]
If we follow the Index vs Detail the argument above is correct. But if we follow Detail vs Form then the current seem correct. 

### Index
```
Owner: Supplier: MySupplier
```

### Detail
```
Supplier: MySupplier
```

### Form
```
Owner: Supplier
Supplier: <MySupplier>
```
