### ISSUE TITLE
delete own account

### ISSUE THREAD

**Issue by Wissamus** [laravel/nova-issues#2636]
I would like to unable the possibility of deleting our own user account. How Could i do that on laravel nova ?

**Comment by demency** [comment]
Its possible using laravel policies, see docs.

**Comment by Wissamus** [comment]
Trust me i did :p

**Comment by demency** [comment]
In other cases, i set up some behavior on model events using policies. I think, if you implement view, create, update, **delete** or restore methods probably you can disable the own user deletion. I don't know if i can trust you without args. But you makes me laugh
