### ISSUE TITLE
Resource without subtitle shows 'No additional information...'

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#2637]
Laravel Version: 7.11.0
Nova Version: 3.6.0
PHP Version: 7.2.19
Database Driver & Version: mysqlm 5.7.24
Operating System and Version: windows 10
Browser type and version: chrome 81 (64 bits)

### Description:

When you add a subtitle to a resource, the morphTo field can show a nice subtitle underneath the results. 

But when there is no subtitle available (in my case a user has no rights), the text 'No additional information...' is shown. Regardless if i remove the subtitle() method on the Distributor resource or return null, this text is returned. IMHO it should show no subtitle.

### Steps To Reproduce:

```php
 $fieldsGeneric[] = Fields\MorphTo::make(ucfirst(__('owned_by')), 'ownedBy')->types([
                        \App\Nova\Supplier\Distributor::class,
                        \App\Nova\Supplier\Supplier::class,
                    ])->onlyOnForms()
            ->withoutTrashed()
            ->withSubtitles();
```

**Comment by preliot** [comment]
not stale... could this stalebot just go away?

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
