### ISSUE TITLE
[Discussion] Concerns about composer based packages!

### ISSUE THREAD

**Issue by devmsh** [laravel/nova-issues#264]
Hi all,

In fact this is not a bug nor a feature requests, but I need to know if anyone concerns about having lots of composer packages. for a sample project, I currently have 10+ separated fields, metrics, and tools packages, and I feel not comfortable with this.

What about you?

**Comment by jwahdatehagh** [comment]
I don't understand what would be the problem with that. Nicely versioned tools. Thats a good thing...

**Comment by davidhemphill** [comment]
It's not a problem. :-D

**Comment by davidhemphill** [comment]
You could consolidate everything into one package if it bugs you that much.
