### ISSUE TITLE
Saving images with trix in pivot field

### ISSUE THREAD

**Issue by bnagydeveloper** [laravel/nova-issues#2642]
- Laravel Version: 6.18.15
- Nova Version: 1.12.0
- PHP Version: 7.3.17
- Database Driver & Version: MySQL 8
- Operating System and Version: Ubuntu 18.04

### Description:

Saving a trix field with image into a pivot field is not working.
Lets say we have a post and a user. Each user can comment on a post and the comment is saved on a pivot table as following:
User
- id
- name

Post
- id
- title

Comment
- id
- post_id
- user_id
- comment_data

Using this structure, when I attach a new comment to a post in nova and add a new image, nova throws an exception in /var/www/vendor/laravel/nova/src/Http/Controllers/TrixAttachmentController.php line 21

```   
public function store(NovaRequest $request)
    {
        $field = $request->newResource()
                        ->availableFields($request)
                        ->findFieldByAttribute($request->field, function () {
                            abort(404);
                        });

        return response()->json(['url' => call_user_func(
            $field->attachCallback, $request
        )]);
    }

My assumtion is that nova cant field comment_data field since it is searching for it in the posts fields because it is calling the following url to save the image:
http://localhost/nova-api/posts/trix-attachment/comment_data
I also added for testing purposes the comment_data to the post resource, which resulted in data comment_data being saved on the post itself.

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!

**Comment by bnagydeveloper** [comment]
> This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!

I updated to laravel 7.2 and nova 3.7.1 but saving trix content with image is still not working

**Comment by dhi2** [comment]
@jbrooksuk @bnagydeveloper Me too, I upgraded but I have the same issue.
