### ISSUE TITLE
The key in options in Select Field is being used to store items instead value

### ISSUE THREAD

**Issue by djilousp** [laravel/nova-issues#2643]
- Laravel Version: 5.8.38
- Nova Version: 2.9.2
- PHP Version: 7.2.24
- Database Driver & Version: mysql 8.0.16
![Screenshot from 2020-05-26 14-37-20](https://user-images.githubusercontent.com/32374382/82908647-2edaf600-9f60-11ea-99a1-2d93080acf03.png)
**Description**
I'm populating data from another model into select field , but when trying to store the value of an option the key is being stored instead
```
            Select::make('Icon')->options(
                DB::table('media')->get()->pluck('name')
            ),
```
![Screenshot from 2020-05-26 14-52-56](https://user-images.githubusercontent.com/32374382/82909014-a01aa900-9f60-11ea-8eed-04eabafbd0d6.png)

**Comment by jbrooksuk** [comment]
This is correct, please see https://nova.laravel.com/docs/3.0/resources/fields.html#select-field
