### ISSUE TITLE
Action Events Log: Attach Resource Log

### ISSUE THREAD

**Issue by yesninja** [laravel/nova-issues#2644]
There may be a way to override this right now, but I wanted to show when a relationship resource was attached to a model, and looks like inside ResourceAttachController doesn't push the event into the action_events log.  Was there a specific reason to omit this?  Seems like for some resources IE adding a role or a permission to a User we would want to know who added it.  

Any particular way to override the controller to add this functionality myself without changing any core nova controllers?

Sorry if this is the wrong area, but thought I would not only ask for this, but also see if there is a workaround for my use.

Thanks,

Aaron

**Comment by jbrooksuk** [comment]
So I just tested this out in 3.8.2 and Nova does track this already.
