### ISSUE TITLE
Invalid theme asset url generation behind reverse proxy

### ISSUE THREAD

**Issue by netpok** [laravel/nova-issues#2647]
- Nova Version: 3.6.0

### Description:
Nova themes generate http asset urls by default when behind a reverse proxy. The reason for this is that the asset urls are generated before the Trustproxies middleware.

The solution to this is wrapping the `Nova::theme` call to `Nova::serving` in the provider, you should update the [stub](https://github.com/laravel/nova/blob/3.0/src/Console/theme-stubs/src/ThemeServiceProvider.stub). This probably affects other components too.

**Comment by rreynier** [comment]
I found the same issue after digging around for couple hours! And yes, the TrustProxies middleware has not run yet, so it doesnt recognize the request properly.

**Comment by jbrooksuk** [comment]
@netpok thanks. Would you consider making a PR to fix this?
