### ISSUE TITLE
Get Resource Name

### ISSUE THREAD

**Issue by ginlove0** [laravel/nova-issues#2648]
Hi. I am trying to get the resource name and push it to the title of the page. Is this possible to make it? anyone have a solution please help. Thanks

<img width="421" alt="Screen Shot 2020-05-28 at 12 04 13" src="https://user-images.githubusercontent.com/37786431/83090352-ecd6bf00-a0db-11ea-87bb-c082a72393e4.png">

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).
