### ISSUE TITLE
I can't log in to Nova for more than one time.

### ISSUE THREAD

**Issue by khaledBawz** [laravel/nova-issues#2649]
- Laravel Version: 7.12.0
- Nova Version: 3.6.0
- PHP Version: 7.4
- Database Driver & Version: Mysql 8.0.19
- Operating System and Version: MacOS 10.15.4
- Browser type and version: Chrome 83.0.4103.61

### Description:
I can't log in to Nova again if I've logged in for the first time using any user credentials. It's keeping redirect me back to the login page without any error message. Even I click to reset password it redirects me back to the login page. I notice the ```remember_token``` coulmn in users table is filled with the token.

### Steps To Reproduce:
1. Login to Nova.
2. Logout.
3. Try to login again with the previous user credentials but the bug happens.

The only solution for this is running the code ```php artisan cache:clear```
I'm using file cache driver

Thank you

**Comment by davidhemphill** [comment]
How does one reproduce this on a fresh Nova instance? It really seems like something weird is in your setup since no one else has run into this.
