### ISSUE TITLE
Scope Relatable Metrics / Cards

### ISSUE THREAD

**Issue by SamoVanHinten** [laravel/nova-issues#265]
Hi guys,

I wondered if there is a way to use the filter generated scope in the Metrics to work with.
In my case i have a Resource wich can be filtered by months and want the metrics in sync only for that month if this statement makes sense to you. I don't want the global Resource scope there..

I hunted about, but ran against a wall (maybe this wall only exists in my head)

Any suggestions?

**Comment by angelocala94** [comment]
Same here. It would be nice to be able to filter the Metrics too!

**Comment by davidhemphill** [comment]
You can scope metrics using request parameters and passing the data to a model scope:

```php
public function calculate(Request $request)
{
    return $this->count($request, User::customScope())
}
```
