### ISSUE TITLE
Garbled problem when inserting non-alphabet languages

### ISSUE THREAD

**Issue by Meteorstrikes** [laravel/nova-issues#2651]
- Laravel Version: 7.14.1
- Nova Version: 3.6.0
- PHP Version: 7.3.11
- Database Driver & Version: MySQL 5.7.22
- Operating System and Version: Amazon Linux release 2
- Browser type and version: Chrome 81.0.4044.138

### Description:
I manually insert data from the Resources, the text data will be garbled. (Japanese is my case.)
When I checked the registered data's charset was "iso-8859-1". It doesn't seem to be converted to UTF-8. The collation order of the database and table is set to "utf-8mb4_unicode_ci".

### Steps To Reproduce:
1. Transition to resources of target table
2. Click the create button to move to column input form
3. Type Japanese in the text field and submit.
4. The registered data in the database is garbled and displayed in the list.

I would appreciate it if you could give me a hint of solution.
Thank you.

**Comment by Meteorstrikes** [comment]
I have upgraded an older version of Laravel. When confirming the requirements for Nova version 3, Nova required Laravel Framework version 7+.

However, the problem still occurs after the upgrade.

**Comment by jbrooksuk** [comment]
Can you please supply some text to test this with?

**Comment by Meteorstrikes** [comment]
Do you want the Japanese text for the test? If you want it, I tested the place names such as "東京 / Tokyo", "大阪 / Osaka", and "京都 / Kyoto". If I didn't answer your request, please reply again.

**Comment by Meteorstrikes** [comment]
Hello. Finally, I solved the problem. It was my misunderstanding. I was overconfident with the garbled JSON problem. The problem was due to PHP's "mbstring.encoding_translation". It was because I turned "On" the item.
I'm sorry that my careless mistake made your time and worry. So this question closes.
Thank you for taking the time to me. From now on, I will fully use your package.
