### ISSUE TITLE
How to use nova fields in a custom tool?

### ISSUE THREAD

**Issue by techguydev** [laravel/nova-issues#2654]
Hi, I want to use  nova fields in a custom tool, I do not find clear informations in the docs, has anyone done it?

Thanks

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).

**Comment by aiman1717a** [comment]
@techguydev were you able to figure this out? i am also having the same issue

**Comment by techguydev** [comment]
@aiman1717a   as David said, these components we not supposed to be used in custom tools, I have. just used an external library: https://element.eleme.io/#/en-US

**Comment by tom-it** [comment]
You can use form fields in your tool by adding the vue components, like this:

```<form-text-field
              :field="{
                    attribute: 'group',
                    name: __('Phone'),
                    placeholder: __('111-222-1234')
                }"
              :errors="validationErrors"
          />```

**Comment by 1stKarkan** [comment]
I got it working for belongs-to inputs (v3.30.0):

```
<form-belongs-to-field resource-name="order-processes"
  :field="{
    resourceName: 'customers',
    attribute: 'customer',
    name: __('Customer'),
    placeholder: __('Select'),
    searchable: true,
    showCreateRelationButton: true,
  }"
></form-belongs-to-field>
```

Note that the prop `resource-name` must be the plural of a resource that holds an ID to the selectable resource. In this case i want to select a customer resource, which belongs in this case to order-processes. In the `field` prop, make sure to add `resouceName` and `attribute`. The name is the plural of the searched resource, while the attribute is the name of relation, which will likely be the singular of the resource.

**Comment by datashaman** [comment]
If you want better clues about how to structure this data, have a look at the XHR requests in the webdev tools network tab on an edit page. The metadata for the form is returned as a JSON payload.
