### ISSUE TITLE
When l label a resource with a name ending with letters "ia", it generates a Create button ending with letters "ium"

### ISSUE THREAD

**Issue by angelocapone** [laravel/nova-issues#2656]
- Laravel Version: 7.13.0
- Nova Version: 3.4.1
- PHP Version: 7.4.2
- Database Driver & Version: pgsql
- Operating System and Version: macOS 10.15.15
- Browser type and version: Chrome 83.0

### Description:
As soon as I label a resource with a name ending with letters "ia", it generates a  Create button ending with letters  "ium"
i.e. the button name replace the ending letters "ia" with "ium"

This is my setting to label the resource:
```
public static function label() { return 'Categoria'; }
```
then the button get called "Create Categorium"
<img width="974" alt="Screen Shot 2020-06-01 at 20 55 53" src="https://user-images.githubusercontent.com/49022955/83443616-580cf200-a44a-11ea-9a05-7cca01dddc34.png">

### Steps To Reproduce:
Easy to reproduce, simply label a resource called 'Categoria'

**Comment by brunocfalcao** [comment]
label() should be used for plural words.

I think what you are trying to achieve is:

```php

    public static function label()
    {
        return 'Categorias';
    }

    public static function singularLabel()
    {
        return 'Categoria';
    }
```

That way it works fine :)

**Comment by angelocapone** [comment]
All sorted then. Thank you very much!
