### ISSUE TITLE
PlaceField doesn't work with JSON attributes

### ISSUE THREAD

**Issue by mathieutu** [laravel/nova-issues#2657]
- Laravel Version: 7.13.0
- Nova Version: 3.6.0
- PHP Version: 7.4.5
- Database Driver & Version: PGSQL 12
- Operating System and Version: N/A
- Browser type and version: Last Firefox
- Reproduction Repository: https://github.com/###/###

### Description:
Hi, Laravel Nova handles properly fields for nested/json attributes:
```php
Text::make('Foo', 'foo->bar')
```

The Place field however fails to load, because of the way you get the container to pass to algolia config (resources/js/components/Form/PlaceField.vue:51)
```js
container: document.querySelector('#' + this.field.attribute),
// so document.querySelector('#foo->bar') wich is not the same in css, and so return null.
```
We have two ways to fix that:
- Escaping the attribute name: `document.querySelector('#foo-\\>bar')` will work,
- using the vuejs ref attribute and use `this.$refs.XXX` to get the element to set the container with. (this is better, more maintainable, and actually this is made for this type of usage)

I can do a PR if you want.

### Steps To Reproduce:

```php
Place::make('Foo bar', 'foo->bar')
```

Thanks.
Matt'

**Comment by jbrooksuk** [comment]
@mathieutu we'd love a PR if you're able to put one together for us?

**Comment by mathieutu** [comment]
Hi, I'm now in a cycling trip around the country, and come back in September. So I think I'll pass on this one. 😅
