### ISSUE TITLE
Creating a resource w/ BelongsToMany field is really, really slow.

### ISSUE THREAD

**Issue by 949mac** [laravel/nova-issues#2658]
- Laravel Version: 7
- Nova Version: 2.x-3.x
- PHP Version: 7.3

### Description:

I have a "Case" resource with ~1,000 records. Clicking on the resource in the navigation loads very quickly.  I have another resource "Mailing", which has a `BelongsTo::make('Case')` field. When creating a new Mailing, it takes a very long time to populate the BelongsTo field.

![Screen Recording 2020-06-02 at 1 33 07 PM 2020-06-02 13_46_30](https://user-images.githubusercontent.com/23151962/83568080-7cfb7680-a4d7-11ea-8493-43e9502bd055.gif)

### Steps To Reproduce:
1. Create two models and two resources
2. Populate one of the resources with 1,000+ records ("Case" in my scenario)
3. Add a BelongsToMany relationship between the models
4. Create a new record on the resource containing the BelongsTo field ("Mailing" in my scenario)
5. Go grab a cup of coffee and hopefully the field will be ready upon return

**Comment by davidhemphill** [comment]
Use `searchable` on the field.

**Comment by 949mac** [comment]
Welp, there we go!

**Comment by demency** [comment]
Hi @949mac. That's not normal. You should debug your code. Maybe a not good query are here or unnecessary things are being loaded.
