### ISSUE TITLE
Resource fields using onlyOnForms are calculated on Index views

### ISSUE THREAD

**Issue by 970Design** [laravel/nova-issues#2659]
- Laravel Version: 7.14.1
- Nova Version: 3.6.0
- PHP Version: 7.3.1
- Database Driver & Version: MySQL 5.7.25
- Operating System and Version: Mac OSX 10.14.6
- Browser type and version: Firefox 78.0b1
- Reproduction Repository: https://github.com/###/###

### Description:

When using onlyOnForms() on a resource field it is still processed when viewing the Index page of the resource.

For example this resource field:

```php
Select2::make('Handler', 'handler_id')
  ->sortable()
  ->options(DB::table('handlers')->pluck('username', 'id'))
  ->configuration([
      'placeholder'             => __('Choose an option'),
      'allowClear'              => true,
      'minimumResultsForSearch' => 1,
      'multiple'                => false,
  ])
  ->withMeta(['value' => $this->handlerID($request)])
  ->onlyOnForms()
```

Would perform the `DB::table('handlers')->pluck('username', 'id')` query for each resource on the Index, despite using onlyOnForms().

This has a fairly large impact on the performance of the Index views.

### Steps To Reproduce:
Create a resource defined as onlyOnForms with a query and view an index page.

**Comment by jbrooksuk** [comment]
You should check out the [Dynamic Field Methods](https://nova.laravel.com/docs/3.0/resources/fields.html#dynamic-field-methods) documentation.
