### ISSUE TITLE
Metrics defaultRange doesn't work

### ISSUE THREAD

**Issue by ibrunotome** [laravel/nova-issues#2660]
- Laravel Version: 7.12.0
- Nova Version: 3.6.0
- PHP Version: 7.4.6

### Description:

Seems like the defaultRange method of a sum query is not working:

### Steps To Reproduce:

Ranges of a metric:

```php
    public function ranges()
    {
        return [
            30      => '30 dias',
            7       => '7 dias',
        ];
    }
```

Add `->defaultRange(7)` before the result of the query, but will always show 30 (no cacheFor() is used)

```php
->defaultRange(7)
->sum($request, $query, 'price_paid')
->prefix('R$');
```

**Comment by massimodellarovere** [comment]
I use property metric $selectedRangeKey

```php
    /**
     * Nova metric class.
     * Nova metric variable.
     *
     * @var string|null
     */

    public $selectedRangeKey = 7;
```

**Comment by jbrooksuk** [comment]
Nova needs to know ahead of time (i.e. not within the `calculate` method) what the default range is. Using `defaultRange` within the `calculate` method has no effect, basically. 

Instead, the `defaultRange` method should be used like so:

```php
public function cards(Request $request)
{
    return [
        (new TotalUsers)
            ->help('This is calculated using all users that are active and not banned.')
            ->defaultRange(365),
    ];
}
```

**Comment by QQ879** [comment]
@jbrooksuk I'm actually doing it exactly the same way you did, but it's not working.
