### ISSUE TITLE
Email, Phone Field for convenience.

### ISSUE THREAD

**Issue by ziming** [laravel/nova-issues#2662]
I know we can still do this with displayUsing to add mailto: or tel: link when it's displayed on show or index view

But having these convenience commonly used fields can really improve quality of development experience in my opinion.

Just like how Country field is also sort of a useful convience field.

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
