### ISSUE TITLE
The dashboards() service provider is called on every route, even API requests

### ISSUE THREAD

**Issue by CitizenBeta** [laravel/nova-issues#2663]
- Laravel Version: 7
- Nova Version: 3.6.0
- PHP Version: 7.4
- Database Driver & Version: mysql 8
- Operating System and Version: Ubuntu 9.10
- Browser type and version: Chrome

### Description:
The dashboards() function in the nova service provider runs on every API call, such as nova cards which wastes a ton of resources, especially if you have queries run and many nova users at the same time.

### Steps To Reproduce:
Put a nice big query in the dashboards() function in the Nova service provider, and you'll see it run in the barry debug bar for every call. I can't think of any reason why this function would need to be called every time, especially for the async card calls.

**Comment by ibrunotome** [comment]
I created a revenue dashboard yesterday and started to see big spikes in my database everytime that I load the default dashboard:
<img width="1307" alt="Screen Shot 2020-06-23 at 21 29 09" src="https://user-images.githubusercontent.com/4256471/85481635-95bbf100-b598-11ea-9790-7994f1fe8aca.png">

Also, looking in the requests in the browser network tab, I can see the requests that I make in my other 2 dashboards been called in the default dashboard.

**Comment by ibrunotome** [comment]
My "hotfix" at this moment:

```php
        if (!request()->is('nova-api/dashboards/revenue-report*')) {
            return [];
        }
```

In the cards() method of all others dashboards.

**Comment by jbrooksuk** [comment]
Thanks for reporting this!

You may override the `boot` method in your `NovaServiceProvider`:

```diff
    public function boot()
    {
-       parent::boot();
+       $this->routes();
+
+       Nova::serving(function (ServingNova $event) {
+           $this->authorization();
+           $this->registerExceptionHandler();
+           $this->resources();
+
+           Nova::cards($this->cards());
+           Nova::tools($this->tools());
+
+          if ($event->request->is('nova-api/dashboards/*')) {
+              Nova::dashboards($this->dashboards());
+          }
+       });
    }
```

**Comment by dillingham** [comment]
Related https://github.com/laravel/nova-issues/issues/1162

**Comment by CitizenBeta** [comment]
Another side effect of this is that we can't get query string values.

So in the Nova service provider:

$id = request()->query('id');
$dashboards[] = new PerformanceDashboard($id);

Does actually pass the value the first time, but since the cards are fetched on every request and doesnt actually use the initial load, the query string is not usable by the dashboard. If the background requests made use of the initial dashboards() load, we not only would avoid the performance issue, but now we can use query string data as well in generating our dashboards.

SIDE NOTE <3 <3 <3 <3 <3 <3

If there was a way to have a simple dropdown or some form of input on dashboards, it would be amazing. Right now if you want to display a dashboard and allow for more specificness, such as narrowing that same dashboard for a particular ID or filter based on an input, you have to generate a dashboard for every possible iteration.

$dashboards[] = new PerformanceDashboard($id); <---- bad
$dashboards[] = new PerformanceDashboard(); <---- good, then we have a text field to work with on the dash. query string is a good stop gap but now we have to put a readme somewhere to tell our staff what's possible to add to the query string.

**Comment by alberto-bottarini** [comment]
The same problem occurs if you put a slow query in `cards` method in NovaServiceProvider

**Comment by davidhemphill** [comment]
I don't believe there's an issue with Nova here. NovaServiceProvider needs to run for every request to ensure it works correctly. You can't plop a big ole query in that file without it getting ran for every request. It'd be better to lazy-load it (via closure if possible), or by getting the data via AJAX when the component is created. This is how most of Nova works. 👍

**Comment by CitizenBeta** [comment]
Frustrating to see this summarily closed without consideration, considering how much detail is here regarding the issue.

> NovaServiceProvider needs to run for every request to ensure it works correctly. You can't plop a big ole query in that file without it getting ran for every request. 

NovaServiceProvider needs to run but the cards() function does not. That's the issue here and the evidence abovea long with the workardounds illustrates this. This is an issue affecting performance for everyone using Nova, and especially those with dynamically determined number of cards.

**Comment by ibrunotome** [comment]
Totally agree with you @CitizenBeta. The cards doesn't need to be called at every request. A new employee was hired this week to word directly with Nova. He may have time to **really work on this bug**.

**Comment by CitizenBeta** [comment]
@davidhemphill how can this please be reopened?

**Comment by vesper8** [comment]
I've personally noticed that a LOT of things get run in double/triple in my application, I haven't taken the time to debug it to see if it's caused by a 3rd party Nova package I installed. But I encourage all of you to add some logging into some of your expensive nova-related files and check if it's getting run multiple times. I've curbed this issue by adding my own caching layer in front of my expensive queries.. but I think there's a possible design flaw which is causing files to get loaded multiple times even when they are now "visibly" in use

**Comment by bernhardh** [comment]
I think its in general a bad idea to add code which only is needed to run on one single page (the dashboard) to be executed on each request. So to be honest - there should NOT be a `cards` method at all in a service provider. The "default" dashboard should be handled and defined like any other dashboard as a separete class instance of `Dashoard`. Otherwise it is and will be a useless performance killer.

**Comment by MelodyHacker** [comment]
> My "hotfix" at this moment:
> 
> ```
>         if (!request()->is('nova-api/dashboards/revenue-report*')) {
>             return [];
>         }
> ```
> 
> In the cards() method of all others dashboards.

great code !!!!!!
tyvm you code 
i am custom dashboard and  nova cards more 78 class.
if loads app wait 1:30 min and loads server 
if fix this on NovaServiceProvider  8-13 sec and not load my server
