### ISSUE TITLE
Resource index and BelongTo index

### ISSUE THREAD

**Issue by amidesfahani** [laravel/nova-issues#2664]
- Laravel Version: 7.13
- Nova Version: 3.6
- PHP Version: 7.4.3
- Database Driver & Version: MySql
- Operating System and Version: Windows 10

### Description:
I have a nested Category table
--------
ID - parent_id - title

and a product table
--------
id category_id title

by default all categories no matter what parent id are listed in index view of Category resource
now I need to display parentless (parent is null or 0) categories in Index view with the following code:
```
public static function indexQuery(NovaRequest $request, $query)
 if (!$request->findParentModel()) {
  return $query->parentless();
 }
 return $query;
}
```
works fine but the problem is in product resource belongsTo field now this field only accepts parentless category!

```
BelongsTo::make(__('Category'), 'category', Category::class)
                ->withMeta([
                    'belongsToId' => $categoryId
])->sortable()->searchable()->withSubtitles()->showCreateRelationButton()->withoutTrashed(),
```

**Comment by tolitz22** [comment]
is this already fixed [amidesfahani](https://github.com/amidesfahani) ?
