### ISSUE TITLE
Multiple Query Indexes

### ISSUE THREAD

**Issue by LukaVodopivec** [laravel/nova-issues#2665]
Is it possible to add multiple indexes that are usually processed only by indexQuery() function in every Nova Resource Model? If not, is there perhaps a way to add a relatively simple custom implementation? I am using this to index custom computed fields.

**Comment by alberto-bottarini** [comment]
What about lenses?

**Comment by davidhemphill** [comment]
This is what [Lenses](https://nova.laravel.com/docs/3.0/lenses/defining-lenses.html#defining-lenses) are for.
