### ISSUE TITLE
can not override actions in lens (the actions that are shown in table rows) 

### ISSUE THREAD

**Issue by osamaAbdullah** [laravel/nova-issues#2666]
in the documentation, it says you can override actions in lense but that only works for actions that are not shown in table row. how to hide those actions that are shown in the row of the table

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
Should be possible now.
