### ISSUE TITLE
Default value in Action Field doesn't work

### ISSUE THREAD

**Issue by bertoloti** [laravel/nova-issues#2668]
- Laravel Version: 7.14.1
- Nova Version: 3.6.0
- PHP Version: 7.4.3
- Database Driver & Version:
- Operating System and Version: Ubuntu 20.04
- Browser type and version: Chrome
- Reproduction Repository: https://github.com/###/###

### Description:
I've defined a nova Action that is supposed to send an email to a client with his account data. The idea is to attach a `Trix` or `Textarea` field to the action with a default content email template and if possible with the account details already populated within the email content. This way the user will be able to customize the email before sending it.

### Steps To Reproduce:
I've tried just adding text to the field using the `default()` method but it doesn't seems to take effect within the `Action` class
```
/**
     * Get the fields available on the action.
     *
     * @return array
     */
    public function fields()
    {
        return [
            Textarea::make('Email content')->default('Simple text')
        ];
    }
```

**Comment by DaibaCity** [comment]
I ran into the same problem. Would be very nice if this can be fixed or added to Nova!

**Comment by DaibaCity** [comment]
Btw this seems to be the same issue as 
https://github.com/laravel/nova-issues/issues/2600

**Comment by sanis** [comment]
+1 went into the same issue.

**Comment by jbrooksuk** [comment]
Duplicate.
