### ISSUE TITLE
Filter ignores duplicate values

### ISSUE THREAD

**Issue by kakajansh** [laravel/nova-issues#2670]
We have categories structured like this

Man
-- Shoes
-- Accessories
Woman
-- Shoes
-- Accessories

In this situation options will ignore duplicate values, because option values are taken from array keys as stated in docs:

> The options method should return an array of keys and values. **The array's keys will be used as the "human-friendly" text that will be displayed in the Nova UI.** The array's values will be passed into the apply method as the $value argument. This filter defines two possible values: admin and editor.

Is there any special reason for current implementation? Would not it better if keys used as value and values as label.

<img width="321" alt="Screen Shot 2020-06-09 at 2 21 56 AM" src="https://user-images.githubusercontent.com/7093483/84081777-09d29280-a9f8-11ea-9a58-63b61457cd74.png">

**Comment by jbrooksuk** [comment]
You would need to generate the keys with different IDs.
