### ISSUE TITLE
Add 2 card on index and onlyOnDetail

### ISSUE THREAD

**Issue by agusesetiyono** [laravel/nova-issues#2672]
- Laravel Version: 7
- Nova Version: 3
- PHP Version: 7.4
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:

I have problem to add 2 cards on my resource, i want to display one card on index, and another card on detail only. 

The card on detail will show, but not for the one i want to show on index only.

```
public function cards(Request $request)
    {
        return [
            (new \Tastic\Invoice\Invoice)->orderDetail($request->resourceId)->onlyOnDetail(), // this show on detail
            (new \Tastic\OrderFilter\OrderFilter), // this not show, why??
        ];
    }
```

**Comment by jbrooksuk** [comment]
Sorry, but we are unable to debug your issue without a reproducible code example. Once you provide that we can open this up again.
