### ISSUE TITLE
Rounding is necessary to represent the result of the operation at this scale.

### ISSUE THREAD

**Issue by jigarhalani** [laravel/nova-issues#2673]
- Laravel Version: 7.11
- Nova Version: 3.0
- PHP Version: 7.4.6
- Database Driver & Version:  8.0.20 MySQL
- Operating System and Version: Ubuntu 18.04.4 LTS
- Browser type and version: Chrome 83.0.4103.97

### Description:
After upgrading from 2.0 to 3.0 I am getting issue in the currency field 

`Currency::make('Tax Rate', 'tax_rate')->onlyOnDetail(),`

whenever I access any page where currency defined and value of field in 4 precession than i am getting below error.

`Rounding is necessary to represent the result of the operation at this scale. {"userId":35387,"exception":"[object] (Brick\\Math\\Exception\\RoundingNecessaryException(code: 0): Rounding is necessary to represent the result of the operation at this scale. at /home/vagrant/sinbad/vendor/brick/math/src/Exception/RoundingNecessaryException.php:19)`

[https://imgur.com/nYz0nh9](url)

 tax_rate field is decimal(19,4) in my DB

**I am only getting this error if my tax_rate field is in 4 precession i.e 20.7987
if its in 2 precession than there is no error 20.7900**

### Steps To Reproduce:

1). Add currency field in any resource and store value in DB with 4 precession.
2). Access detail page or index page for this resource

**Comment by gerardnll** [comment]
You already answered yourself. Currency fields support 2 decimals not 4. Brick\Money cannot truncate those 2 decimals without telling it how. You could extend the field and overwrite the `toMoneyInstance` function to create a CustomContext(4) or even make a property. This change could be implemented to Nova without much effort.

**Comment by daryledesilva** [comment]
@jigarhalani add: `->context(new \Brick\Money\Context\CustomContext(4))`
