### ISSUE TITLE
More formal message on a 403 or 404 page

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#2676]
Right now when something goes wrong, a user sees one of these two messages:

"The government won't let us show you what's behind these doors"
"We're lost in space. The page you were trying to view does not exist."
   
Would appreciate a more formal text ór the possibility to choose a formal text.

**Comment by davidhemphill** [comment]
You can register your own 404 and 403 error components inside a Nova tool:

```js
Nova.booting((Vue, router, store) => {
    Vue.component('error-404', require('./component/Custom404))
})
```

**Comment by preliot** [comment]
@davidhemphill Thanks for the snippet!

**Comment by mistaketodo** [comment]
@davidhemphill hi
I have problem with loggin in to admin pannel, after credits i see 403 error The government won't let us show you what's behind these doors how to pass it?
thanks
