### ISSUE TITLE
MorphTo field ignores policy and shows link, which results in a 404.

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#2677]
Laravel Version: 7.15.0
Nova Version: 3.6.0
PHP Version: 7.2.19
Database Driver & Version: mysqlm 5.7.24
Operating System and Version: windows 10
Browser type and version: chrome 81 (64 bits)

MorphTo field ignores policy and shows link to resource, even though the user is forbidden to access that resource. Would be better if a policy denies access to a resource, an empty cell is presented.

This is related to an older issue, which removed the table cell entirely (https://github.com/laravel/nova-issues/issues/2023)

**Comment by preliot** [comment]
Not stale, very fresh!

**Comment by preliot** [comment]
Still fresh to date!

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/99358420-78d9de80-28e8-11eb-8618-80615f3da9fb.png)

Unable to replicate the issue, see the code I used to replicate the issue https://github.com/nova-issues/issue-2677/commit/0c5c60998afcac02d5fbccbbffdaea3316886d9b

**Comment by crynobone** [comment]
Closing for now, but feel free to create new issue on how to reproduce the issue.

**Comment by preliot** [comment]
@crynobone Sorry, was busy with other work. When i've got the time, i will revisit this and check your repo. Thanks for your effort!
