### ISSUE TITLE
 drop-down bar with left menu similar nova docs？

### ISSUE THREAD

**Issue by lifeblood** [laravel/nova-issues#2678]
The column on the left can there be a second class, and then can there be a drop-down bar
![image](https://user-images.githubusercontent.com/3621748/84425041-87dea580-ac53-11ea-9e68-344d1a030c92.png)

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
