### ISSUE TITLE
Feature: Ability to edit primary key

### ISSUE THREAD

**Issue by richstandbrook** [laravel/nova-issues#268]
I have a model that has a unique string as the primary key. I'd like to be able to edit it in Nova, but it seems Nova just hides the primary key from the form with no override I can find.

**Comment by Andy-Baker** [comment]
I first thought you could override the query with `editQuery()` the same way as `indexQuery()`, but the former doesn't exist.

Try exploring global scopes on the main Laravel model to `select id as custom_id`, then use that.

**Comment by davidhemphill** [comment]
Just use a Text field?

**Comment by richstandbrook** [comment]
@davidhemphill I add `Text::make('ID'),` and it shows on the list view and the details view but it's still left off the form view, so I can't edit it.

**Comment by fbingha** [comment]
More importantly, not sure of use cases where the primary key is editable but there are cases where I need to be able to define the primary key when creating an element. At this time, the primary key field is not show on the create form.

**Comment by christopherarter** [comment]
@davidhemphill Can this issue be re-opened? @fbingha described exactly the situation I'm in as well. The Text field does not work.

**Comment by davidhemphill** [comment]
Ok, you're right it doesn't show. I've added this though and it will be available in the next release. 👍

**Comment by nikans** [comment]
@davidhemphill it does not render as a link in a table view, though.

<img width="281" alt="Screenshot 2021-03-19 at 13 32 55" src="https://user-images.githubusercontent.com/1039100/111767355-aeeb9700-88b7-11eb-80a8-80f082a7fcfc.png">

**Comment by nikans** [comment]
I've created a custom text field, so you can edit your ID fields or link a title field on the index screen.

https://github.com/nikans/text-linked
