### ISSUE TITLE
new item in sidebar, "Actions"

### ISSUE THREAD

**Issue by cloudstudio** [laravel/nova-issues#2680]
- Laravel Version: 7.11
- Nova Version: v3.6.0
- PHP Version: 7.4

Hello! since I update to Laravel nova 3.6,0 I have a new item in sidebar, "Actions" I read that it was fixed, anyway I have it in my project, so maybe is not fixed at all ?

Thanks !

![Captura de pantalla 2020-06-12 a las 12 41 54](https://user-images.githubusercontent.com/3589377/84494609-1da51f80-acaa-11ea-9042-08deaa7d57fe.png)

**Comment by davidhemphill** [comment]
I wasn't able to replicate this on a new Nova install. This seems to still be fixed under normal circumstances. If you can offer a reproduction, we'll take another look. :-)

**Comment by cloudstudio** [comment]
Hello @davidhemphill this happend when update , not fresh install, maybe can I check something

I try with a new installation and everything is fine, the error is when the update is made, so maybe we have a BUG here.

Can you reopen this ? thanks
