### ISSUE TITLE
BelongsTo returning all records when ID is 0

### ISSUE THREAD

**Issue by poxin13** [laravel/nova-issues#2682]
Relationship is working great in Nova unless the parent ID is 0. If zero it will return *all* the records in the relationship in the dashboard:
`HasMany::make('Contacts', 'contacts', 'App\Nova\Contact'),`
`BelongsTo::make('Company', 'company', 'App\Nova\Company'),`

Some sanity checking, everyhing below is normal,

`Company::first()->id;` = 0
`Contact::find(31695050)->company_id;` = 0
`Contact::find(31695050)->company()->count();` returns 1

```
public function company()
    {
        return $this->belongsTo('App\Company', 'company_id', 'id');
    }
```

Pulling back the count manually works fine and is the correct number
```
Text::make('Contacts', function () {
    return $this->contacts()->count();
})
```

**Comment by jbrooksuk** [comment]
Sorry, but there's not enough information to go off of here. If the issue you have still persists, please feel free to open a new issue with all the details of what you're trying, what you expect to happen, what's happening, and how to reproduce it. Thanks!
