### ISSUE TITLE
Heading with Closures

### ISSUE THREAD

**Issue by Milkhan** [laravel/nova-issues#2685]
- Laravel Version: 6.2
- Nova Version: 2.11.1
- PHP Version: 7.3.9

### Description:
I tried to add a dynamic value in Heading but no success. Don't we have this feature or am I doing something wrong? Thank you!

### Steps To Reproduce:
` Heading::make('Name', function () {
                        return $this->name;
                    }),`
or
` Heading::make(function () {
                        return $this->name;
                    }),`

**Comment by davidhemphill** [comment]
I was not able to reproduce an issue with using a computed Heading field. If you can provide more detail on what error you receive or what happens, please open a new issue so we can take a look at it. Thanks!

**Comment by warksit** [comment]
For anyone else who ends up here!

`Heading::make($this->name),`
