### ISSUE TITLE
"Update undefined" in title when updating BelongsToMany resource

### ISSUE THREAD

**Issue by carnevalle** [laravel/nova-issues#2686]
- Laravel Version: 7.15.0
- Nova Version: 3.6.0
- PHP Version: 7.4.5
- Browser type and version: Google Chrome 83.0.4103.97

### Description:
When editing a BelongsToMany resource it blinks "undefined" in the title where it says "Update [resource name]" when saving the changes and before it shows the resource again.

[See video here](https://www.dropbox.com/s/7g8n7agnb9viisb/Sk%C3%A6rmoptagelse%202020-06-13%20kl.%2021.49.42.mov?dl=0)

**Comment by preliot** [comment]
Same issue in Nova 3.13.0

**Comment by crynobone** [comment]
![CleanShot 2020-10-25 at 19 43 18](https://user-images.githubusercontent.com/172966/97106092-8ee5ec00-16fa-11eb-9cba-a8c49720c22d.gif)

Tried replicating on 3.13.0 but unable to replicate (used Slow 3G on Chrome).

**Comment by preliot** [comment]
[2020-10-26 08-46-59.zip](https://github.com/laravel/nova-issues/files/5437493/2020-10-26.08-46-59.zip)

Default Nova Laravel install (3.13.0). 
Windows 10 / Chrome (latest)
No throttle.

**Comment by crynobone** [comment]
@preliot as shown above (in my reply) I wasn't able to recreate the issue. Is there any Chrome console error that we can use to debug the issue.

**Comment by preliot** [comment]
@crynobone no console errors :(

I can see a difference between your and my (and @carnevalle 's) example. In my example the title remains on screen while the form is being removed during the request. In your example the title and form are removed. during the request, so you won't see the 'undefined'.

Don't know why, but perhaps this helps solving this issue.

If you need more, don't hesitate to ask :-)

**Comment by crynobone** [comment]
> In your example the title and form are removed. during the request, so you won't see the 'undefined'.

Actually it's the same, just that I force Chrome to emulate Slow 3G connection so I slow everything down to debug, but can't see it with fast or slow connection.

![image](https://user-images.githubusercontent.com/172966/97152140-7255bc80-17ab-11eb-97db-94fc7b16f564.png)

**Comment by preliot** [comment]
Just tested it again and got some strange results:

1) Forced chrome to slow 3g -> saw 'Undefined' for a longer time.
2) Fiddled around a bit with loading / reloading resources.
3) Tried it again and suddenly both the title / table disappear when attaching. Which means i can't see the undefined.
4) But when i pressed ctrl+f5 the issue reappears...

So for some unknown reason the title tag stays up and results in a 'undefined' blink. And sometimes the title tag is removed while creating the next form (thus elliminating the blinking undefined). Strange!
