### ISSUE TITLE
Can we change the folder name on root "nova" to some thing else ??

### ISSUE THREAD

**Issue by ahmadsaadkhan** [laravel/nova-issues#2688]
Can we change the folder name on root "nova" to some thing else same to change the folder name in "app/nova" .
i have managed to changed the folder name in "app/nova" it sort of work shows the dashboard page but resources are gone.
My main question is are we able or allowed to change the root directory name to some thing else.

**Comment by davidhemphill** [comment]
Check out the `path` option in Nova's configuration file `config/nova.php`.

**Comment by Delaney** [comment]
Can we have the option of having multiple paths? Something like

```
'path' => [
        '/nova',
        '/folder/nova',
    ],
```

**Comment by bashgeek** [comment]
Sounds like an edge case to me, you can easily use a rewrite rule in your webserver config for this.
