### ISSUE TITLE
Action > support for panel field

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#2689]
I'm creating an action which needs several fields. Would be great when i could use panels to create a cleaner look (less crowded). 

Right now when i try to add a panel, i get an exception:

`local.ERROR: Call to undefined method Laravel\Nova\Panel::resolve() {"userId":306,"exception":"[object] (Error(code: 0): Call to undefined method Laravel\\Nova\\Panel::resolve() at <path_to_project>\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\HigherOrderCollectionProxy.php:60)`

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by riabiy-denis** [comment]
@davidhemphill 

This is very important, since it will unlock the possibility of a multistep action (via extending Panel).
