### ISSUE TITLE
Attach multiple items for BelongsToMany relation

### ISSUE THREAD

**Issue by devmsh** [laravel/nova-issues#269]
I have `Season` and `Team` resources and they are Many-to-Many related.

I know I can develop my own Action to attach multiple selected teams to a season, but I feel it's must be supported by default?

**Comment by devmsh** [comment]
I tried to developed a custom actions for that, but notice that there is no Field to display a List from another resource? not using the Relations fields because it will not work within the Action field method?

**Comment by davidhemphill** [comment]
There will likely be no plans to implement this feature inside of create/edit views.
