### ISSUE TITLE
Filtering MorphTo dropdowns

### ISSUE THREAD

**Issue by IMPMAC** [laravel/nova-issues#2690]
```
MorphTo::make('Type', 'Agentable')->types([
    Agent::class,
    User::class,
]),
```
When you have the above code, it will load every row in those models on creation/update. Is there a way that you could filter those results for each model with a query. For example, I want to only show users who have the "is_active" boolean set.

Maybe like 
```
MorphTo::make('Type', 'Agentable')->types([
    Agent::class,
    User::query(function($query) {return $query->where('is_active', true);}),
]),
```

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
Should be able to use https://nova.laravel.com/docs/3.0/resources/authorization.html#relatable-filtering
