### ISSUE TITLE
Datetime field are populated, but with `NULL` , which cause SQL error

### ISSUE THREAD

**Issue by florentpoujol** [laravel/nova-issues#2691]
First-of I known this is not strictly a Nova issue, and propably more a configuration/server thing, but please hear me out.

All our models have the created_at/updated_at attributes, with the corresponding fields in the database that are not nullable `TIMESTAMP` with the default value of `CURRENT_TIMESTAMP`.

Since we started using Nova we pretty much always leave these fields empty in Nova and they are automatically populated.  
It work in our local env and in one production-like staging env.

But we just deployed the app in a new env/hosting (but same Mysql5.7 DB (and same SQL_MODE)) and apparently the fields gets populated by `NULL`, with cause the `Column 'created_at' cannot be null` SQL error.

If I am not mistaken the fields are supposed to be populated by Laravel itself, even before trying to insert them in the DB, when they haven't been modified already ?
It seems to work since we create model in many places in the code and these works fine.

It doesn't work only from a Nova field.  
Do you know any reason why would the fields exist, but with a NULL value, which prevent their update and cause the error ?

Many thanks in advance !

**Comment by florentpoujol** [comment]
I note that this does not happen for other datetime fields, including the `deleted_at` field.

This seems to only happen for fields that precisely have a default value...

**Comment by chrispage1** [comment]
If you have the 'Created At' and 'Updated At' fields registered within your Nova resource that will force fill the models values. You don't really want to have the created_at and updated_at fields registered in Nova, these are purely for administration only.

**Comment by florentpoujol** [comment]
> If you have the 'Created At' and 'Updated At' fields registered within your Nova resource that will force fill the models values. You don't really want to have the created_at and updated_at fields registered in Nova, these are purely for administration only.

Hey, thanks for you reply.

We do have both fields on all our resources.
Now that I think about it, they may indeed not be useful on the creating form.  
Assuming these are the fields that fill the attribute with the wrong value (and I have no idea why they would do that, only on a single hosting provider), I will try later to remove them.

But even with them, the fields on the model gets populated by the wrong value.
For now I patched this by forcing the fields on all models from the `creating` event (from our base model, so thanks god we don't have to do that for all of them individually), why is basically what `Model->updateTimestamps()` (or whatever its name) is supposed to do.

**Comment by jbrooksuk** [comment]
I see what you're saying, but like you said, this isn't strictly a Nova issue, so I am closing it.
