### ISSUE TITLE
belongsTo field throws error upon quickcreate() if resource has an ID field present

### ISSUE THREAD

**Issue by cpommiss** [laravel/nova-issues#2693]
- Laravel Version: 7.14.1
- Nova Version: 3.6.0
- PHP Version: 7.4.6
- Database Driver & Version: MySQL/MariaDB, 15.1/10.1.41-MariaDB
- Operating System and Version: Debian 9
- Browser type and version: Any

### Description:

When using the quickCreate() feature of the BelongsTo field, I've found that I get a JS error when attempting to quickCreate().

The error:
TypeError: (intermediate value).forEach is not a function

Removing the ID field from the resource I'm trying to quickCreate() fixes the issue. Not sure why.

I've tried swapping out the ID field for the R64 field, but that makes no difference. The only way the form appears is if the ID field is removed as a field from the Nova resource.

The resource in question is just a collection of standard Text and Select fields.

**Comment by davidhemphill** [comment]
Nova's `BelongsTo` field does not have a `quickCreate` method.

**Comment by cpommiss** [comment]
Apologies, I've no idea how this issue ended up in this repo -- meant for a totally different one. Sorry!
