### ISSUE TITLE
JS Error when using Date Filter

### ISSUE THREAD

**Issue by gpressutto5** [laravel/nova-issues#2694]
- Laravel Version: 7.16.1
- Nova Version: 3.6.0
- PHP Version: 7.4.7
- Browser type and version: Chrome 83.0.4103.106

### Description:

When using date filters I get this error when setting a date:

![image](https://user-images.githubusercontent.com/12385501/85210240-a9efbc00-b314-11ea-8c87-ed3af9e6344b.png)

The filter works however. This is my code:

```php
class DeliveryDate extends DateFilter
{
    public function name()
    {
        return __('Delivery Date');
    }

    public function apply(Request $request, $query, $value)
    {
        return $query->whereDate('delivery_date', Carbon::parse($value));
    }
}
```

I have already run `nova:publish` and `view:clear`.

**Comment by jbrooksuk** [comment]
I can confirm this bug, but I've yet to figure out what's causing it.

**Comment by crynobone** [comment]
I no longer can reproduce the issue on latest Laravel Nova. It could have been fixed for some times and not updated here. Closing issue for now but you can make a new issue if you still experiencing the issue.
