### ISSUE TITLE
how to redirect from a middleware to a custom tool component

### ISSUE THREAD

**Issue by techguydev** [laravel/nova-issues#2695]
- Laravel Version: 7
- Nova Version: 3
- PHP Version: 7.4
- Database Driver & Version:
- Operating System and Version: MacOS
- Browser type and version: Chrome
- Reproduction Repository: https://github.com/###/###

### Description:

I am trying to redirect a user after checking for a condition in a middleware, I have tried to use 
```
return redirect('/admin/paddle-subscription');

````
But it does not work, it just redirects the page and shows it right in the browser url but show a 404 error in the screen, it looks  that as nova uses vue.js it is creating some kind of errors.

I have been reading some post in laracast   https://laracasts.com/discuss/channels/nova/nova-resource-route-redirect and it is clearer to me that it requires a special way to redirect.

I have tried 
```
 return redirect()->action('\Laravel\Nova\Http\Controllers\RouterController@show', ['resource' => '/admin/paddle-subscription']);
```
And it does not work, how I am supposed to redirect properly?

Thanks

**Comment by techguydev** [comment]
I think this has to do with a Vue router problem, how am I supposed to redirect in order to make it work properly? I think this is something that shoulded be documented

**Comment by davidhemphill** [comment]
You didn't provide any code or way to reproduce the issue.
