### ISSUE TITLE
Forms are getting pre-filled with a record in the database

### ISSUE THREAD

**Issue by heyaj19** [laravel/nova-issues#2697]
- Laravel Version: 7.16.1
- Nova Version: 3.6
- PHP Version: 7.3
- Database Driver & Version: MySQL
- Operating System and Version: Mac OS, Windows 10
- Browser type and version: Firefox, Chrome
- Reproduction Repository: https://github.com/###/###

### Description:
 This issue occurred in 2.0.9 and I was told to update it went away but is now back again https://github.com/laravel/nova-issues/issues/2237

**Comment by davidhemphill** [comment]
We are not able to reproduce your issue without a reproduction repository or example of how to show the issue. Please post again with detailed steps when you can demonstrate this on a fresh Nova install.
