### ISSUE TITLE
High throughput on application when unused

### ISSUE THREAD

**Issue by dawsonnn3** [laravel/nova-issues#2698]
- Laravel Version: 7.14.1
- Nova Version: 3.6.0
- PHP Version: 7.4.7
- Database Driver & Version: MySQL 5.7.30
- Operating System and Version: #.# Ubuntu 18
- Browser type and version: #.#  Google Chrome
- Reproduction Repository: https://github.com/###/###

### Description:

I'm getting a very high throughput on Laravel nova when it is completely unused. I installed it about 3 months ago but I haven't taken the time to actually dive into it so it has been sat there, unused for all of this time.

I have just recently installed NewRelic, and I have noticed that the throughput for Laravel Nova is extremely high. It's reaching up to more than 1,000 requests per minute. The average is around 700 requests per minute.  What can cause that? I'm not using it. Nobody else is using it. I've checked the logs and nobody is even attempting to access it.

It's also the third most time consuming process on my application so this isn't something that I can just ignore.

![nova-throughput](https://user-images.githubusercontent.com/10324979/85277668-ab87c400-b47b-11ea-8a03-a52b017e8531.png)

![image](https://user-images.githubusercontent.com/10324979/85278126-6c0da780-b47c-11ea-9c3d-f690732ce34c.png)

Ignore the spike in transaction time. That was caused by the server performing some CPU intensive tasks.

My server usually gets about 5,000 requests per minute (not accounting for the nova requests).

**Comment by davidhemphill** [comment]
Nova's `ServeNova` middleware is applied to the global middleware stack, meaning it's ran on every web request. That's why it will show high in the list.

**Comment by dawsonnn3** [comment]
But why is that necessary? Can it be disabled without removing nova completely? It is now head and shoulders above every single transaction listed on NewRelic. I'm not entirely sure why it needs a throughput of 1,000 requests per minute  if it is completely unused.

**Comment by jbrooksuk** [comment]
> I'm not entirely sure why it needs a throughput of 1,000 requests per minute if it is completely unused.

Just to clarify this, the `ServeNova` middleware will be ran for every request in your Laravel application. However (and very importantly), it will not handle the request if it's not a Nova endpoint that is being hit. You can see this at https://github.com/laravel/nova/blob/f267812b18b0458851886121af265c0e999f8fe3/src/Http/Middleware/ServeNova.php#L20-L24
