### ISSUE TITLE
display message when attaching resource

### ISSUE THREAD

**Issue by latifiyll** [laravel/nova-issues#2699]
I'm looking for a method to display flash message after attaching on resource.
Example: When **attaching** an attribute to a Product, I want to show flash message after redirecting to Product Page.

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
