### ISSUE TITLE
Allow Partition Metrics to support JSON Fields

### ISSUE THREAD

**Issue by jameslkingsley** [laravel/nova-issues#27]
Version: 1.0.5

I've ran into a problem with using a JSON field as the `groupBy` column. Take this JSON structure for example:

```json
{
    "platform": "twitter"
}
```

I'm trying to make a partition metric that does `gruopBy` on that `platform` property inside the JSON field of the database records.

I think the third argument to `$this->count( ... )` needs to support the `->` operator somehow, such as:

```php
return $this->count(
    $request,

    Stat::whereType('social'),

    'data->platform'
);
```

**Comment by davidhemphill** [comment]
Yeah it doesn't support JSON fields currently. Seems pretty useful. I'll add it to the list.

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
