### ISSUE TITLE
Actions, can someone explain this to me?

### ISSUE THREAD

**Issue by Jam0r85** [laravel/nova-issues#270]
I have a service class which generates an invoice, some items and then increments the next invoice number in a teams table. The process works fine.

When using it with a Nova action and selecting multiple records to carry this action out on, it uses the same invoice number even through it's incremented in the team table?

I'm not queuing the action.

**Comment by GuidoHendriks** [comment]
Sounds to me like it could use old data, have you tried getting fresh data in the action using `fresh()`?

**Comment by Jam0r85** [comment]
This is what I don't get because the action returns a collection of models and all i'm doing is running the service on each model.

`
        foreach ($models as $model) {
            $statement = (new CreateStatement($model))->handle();

            (new CreateStatementItems($statement))->handle();
        }
`

**Comment by GuidoHendriks** [comment]
Did you eager load `team` for your `$models`? I still think it has already loaded the next invoice number, and is not refreshed after incrementing it after the previous invoice.

**Comment by Jam0r85** [comment]
Nope, not eager loaded anything.

Even if I do

```
$public invoiceNumber;

public function __construct()
{
$this->invoiceNumber = $team->next_invoice_number
}

public function handler()
{
$this->invoiceNumber++
}
```

The number never changes for the next invoice generated.

**Comment by davidhemphill** [comment]
We are unable to debug your issue without a reproducible code example.
