### ISSUE TITLE
MorphTo nullable validation is not working.

### ISSUE THREAD

**Issue by muhghazaliakbar** [laravel/nova-issues#2700]
- Laravel Version: `v7.5.2`
- Nova Version: `v3.6.0`
- PHP Version: `7.4`
- Operating System and Version: `MacOS Catalina Version 10.15.5`

### Description:
I'm having problem with nullable validation in `MorphTo` relationship that get an error like this:
```json
{"message":"The given data was invalid.","errors":{"patheable_type":["patheable type is invalid."]}}
```
I don't know what I missed but I just follow the instruction from docs here: https://nova.laravel.com/docs/3.0/resources/relationships.html#morphto

### Detailed steps to reproduce the issue:

`PathItem` model relationship:
```php
/**
 * Get the owning patheable model.
 */
public function patheable()
{
    return $this->morphTo();
}
```

`PathItem` resource:
```php
MorphTo::make('Patheable')
    ->types([Course::class, Video::class])
    ->nullable(),

Markdown::make('Text')
    ->nullable()
    ->alwaysShow()
    ->hideFromIndex(),
```

**Comment by crynobone** [comment]
Tried replicating the issue but everything work as expected in latest Laravel Nova. You can see the code https://github.com/nova-issues/issue-2700/commit/fbdddbbde92115a8d7f8d379858ebc03b93dbcc6

**Comment by crynobone** [comment]
Closing the issue for now. Feel free to create new issue with additional info on how to reproduce the issue if the problem still persist.
