### ISSUE TITLE
Make field panels macroable

### ISSUE THREAD

**Issue by salparadise** [laravel/nova-issues#2701]
It would be nice to have field panels `macroable` just like other fields. I have a bunch of panels and it would be much more convenient to use custom method to fill them with meta instead of calling `withMeta` repeatedly and perform the same operation.

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
