### ISSUE TITLE
Deletion in my observer leads to 404

### ISSUE THREAD

**Issue by khavishbhundoo** [laravel/nova-issues#2702]
- Laravel Version: 7.16.1
- Nova Version: 3.6.0
- PHP Version: 7.4.7
- Database Driver & Version:
- Operating System and Version:  Centos 8.x
- Browser type and version: Chrome  83.0.4103.106 

### Description:

I have an [eloquent observer](https://laravel.com/docs/7.x/eloquent#observers) where i delete the model that has been created after doing some work.

The observer works fine and the deletion works fine.However nova return 404. 

### Detailed steps to reproduce the issue on a fresh Nova installation:

1.Create MyModel  Eloquent Model
2.Create an eloquent observer and change `created` as below 
3.Add a Nova resource for MyModel  
4.Try to insert a record
```
public function created(MyModel $model)
{
      //do some work here and then delete
      $model->delete();
}
```
If you just have `$model->delete();` in the created then i expect the record to be deleted

**Comment by coreyworrell** [comment]
By default, after creating a resource Nova redirects to the "view" of that resource. Since you are deleting the resource right away, the redirect goes to a 404.

In your resource class for the `MyModel`, you can override this `redirectAfterCreate` method like so:

```
public static function redirectAfterCreate(NovaRequest $request, $resource)
{
    return $this->redirectAfterDelete($request);
}
```
