### ISSUE TITLE
Custom Search gets right data but returns {"count":0}

### ISSUE THREAD

**Issue by packytagliaferro** [laravel/nova-issues#2704]
- Laravel Version: #.#.# 
Current
- Nova Version: #.#.# 
Current
- PHP Version: #.#.#
7.4

### Description:
Creating a custom search query to be able to search encrypted data will not actually populate in index. If I `dd` the query it shows the correct record but when I try and return it i get `{"count":0}`

```
 public static function indexQuery(NovaRequest $request, $query)
    {
        if (request()->filled('search')) {
            $term = $request->search;

            $query = AppConsumer::all()->filter(function ($record) use ($term) {
                if (($record->email) == $term) {
                    return $record;
                }
            });

            return $query->first();
        }

        return $query;
    }
```

**Comment by davidhemphill** [comment]
You cannot replace the query inside `indexQuery`, you must modify the existing query passed in as a parameter.
