### ISSUE TITLE
Extending Packages That Use Nova / Feature Request

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#2705]
If non nova packages contained nova resources for other Nova enabled projects..
It is a little tricky to allow adding fields, filters, cards, actions & lenses.
It would be **awesome** if we could hook into the rendering of those per resource.

```php
use Package\Nova\Resources\User;
```
```php
Nova::hooks()->fields(User::class, function($fields) {
    // add or remove fields
    return $fields;
});

Nova::hooks()->filters(User::class, function($filters) {
    // add or remove filters
    return $filters;
});

Nova::hooks()->cards(User::class, function($cards) {
    // add or remove cards
    return $cards;
});

Nova::hooks()->lenses(User::class, function($lenses) {
    // add or remove lenses
    return $lenses;
});

Nova::hooks()->actions(User::class, function($actions) {
    // add or remove actions
    return $actions;
});
```

**Comment by dillingham** [comment]
@davidhemphill / @jbrooksuk here's my current attempt in a project

```php
$this->app->singleton('Package\Nova\Hooks', function ($app) {
    return new \Package\Nova\Hooks;
});
```
```php
<?php

namespace Package\Nova;

class Hooks
{
    public $listeners = [];

    public function fields($resource, $callable = null)
    {
        return is_null($callable)
            ? $this->get($resource, 'fields')
            : $this->add($resource, 'fields', $callable);
    }

    public function cards($resource, $callable = null)
    {
        return is_null($callable)
            ? $this->get($resource, 'cards')
            : $this->add($resource, 'cards', $callable);
    }

    public function actions($resource, $callable = null)
    {
        return is_null($callable)
            ? $this->get($resource, 'actions')
            : $this->add($resource, 'actions', $callable);
    }

    public function filters($resource, $callable = null)
    {
        return is_null($callable)
            ? $this->get($resource, 'filters')
            : $this->add($resource, 'filters', $callable);
    }

    public function lenses($resource, $callable = null)
    {
        return is_null($callable)
            ? $this->get($resource, 'lenses')
            : $this->add($resource, 'lenses', $callable);
    }

    private function add($resource, $element, $callable)
    {
        $resource = is_object($resource)
            ? get_class($resource)
            : $resource;

        $values = isset(
            $this->listeners[$resource],
            $this->listeners[$resource][$element]
        ) ? $this->listeners[$resource][$element] : [];

        $this->listeners[$resource][$element][] = $callable;
    }

    private function get($resource, $element)
    {
        $values = [];

        $resource = is_object($resource)
            ? get_class($resource)
            : $resource;

        if(!isset($this->listeners[$resource][$element]))
        {
            return [];
        }

        foreach($this->listeners[$resource][$element] as $callable)
        {
            $values = is_array($callable)
                ? array_merge($values, $callable)
                : $callable($values);
        }

        return $values;
    }
}

**Comment by demency** [comment]
Cool @dillingham

**Comment by jbrooksuk** [comment]
@dillingham thanks for the suggestion. I have a couple of questions:

1. Why would a package be reaching into a projects resource and editing it?
2. Would it not be more reasonable for the package to be providing its own fields - that do whatever the package needs to do - and the developer uses that instead?

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by dillingham** [comment]
@jbrooksuk good thoughts. The idea was for use cases where a package comes equipped with nova resources registered automatically via service providers and were fully featured / ready to go but open to making slight tweaks. Less of a boilerplate resource for a developer to use and more of a complete solution to a problem.

### Example scenario:

Developer makes a package: `Laravel support`: comes with a Vue widget, routes, controller for a help scout alternative.

Developer also advertises that the package has "Nova support" to allow managing of support tickets, for license holders.

The package would have a `src/Nova` directory with tools, resources, filters, cards for a full support ticket experience.

With hooks, it could be composer install & done _**with option**_ to modify in a service provider.

Without hooks it would require creating resources and extending the package resources.

The only thing missing that Nova doesn't have for that currently is a way to alter package resources.

---

_Package's service provider_

```php
public function boot()
{
    if (class_exists(\Laravel\Nova\Nova::class)) {
        Nova::resources([
            \Package\Nova\Resources\Visitor::class,
            \Package\Nova\Resources\Ticket::class,
        ]);
    }
}
```

_Consumer's service provider_

```php
use App\Nova\Filters\CustomFilter;
use Package\Nova\Resources\Visitor;
```
```php
public function boot()
{
    Nova::hooks()->filters(Visitor::class, function($filters) {
       $filters[] = CustomFilter::class;

        return $filters;
    });
}
```

---


### Another example:

If spark was purely an API with optional Nova support.. 

You could give a complete solution like spark is now..

But allow adding fields and adjustments

**Comment by dillingham** [comment]
@jbrooksuk maybe one day Horizon, Telescope & Spark could all use Nova for their UI.. :)
