### ISSUE TITLE
When an issue is closed, how do i communicate the issue still exists?

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#2706]
Not sure where to put this, but i will try it here.

When i post an issue and it's fixed or closed for another reason, i would like the possibilty to reopen it if the issue is not fixed. 

For example, this issue https://github.com/laravel/nova-issues/issues/2373 and https://github.com/laravel/nova-issues/issues/2386 were both closed, but the problem stil exists. I've added comments to both of them, but now they are autoclosed by the lockbot.

So how could one communicate an issue still exists?

**Comment by davidhemphill** [comment]
We don't generally go back and look at issues that have been closed with fixes. Like the lock bot mentions, you should post a new issue for related bugs and give as much detail as possible on how to demonstrate the issue within a fresh Nova instance.
