### ISSUE TITLE
Listing resources as Cards within a Dashboard

### ISSUE THREAD

**Issue by emperorjm** [laravel/nova-issues#2709]
I have been searching for a solution to show a tabular list of data within a Dashboard and unable to find any such option but this seems like something that most projects would need. Showing 5 or more items and then having a link to go to the actual resource page.

If there is a way to do this right now I would love some insight.

**Comment by cord** [comment]
This should do the trick: https://novapackages.com/packages/m-a-k-o/nova-custom-table-card

and check out https://novapackages.com/packages/nova-bi/nova-databoards

**Comment by emperorjm** [comment]
Thanks a lot @cord. I got the table card package working (https://novapackages.com/packages/m-a-k-o/nova-custom-table-card).
