### ISSUE TITLE
Cards() are not updated with direct navigation

### ISSUE THREAD

**Issue by cord** [laravel/nova-issues#2713]
- Laravel Version: 7.4
- Nova Version: 3.7

### Description:

with directly linked resources using e.g. https://novapackages.com/packages/digital-creative/collapsible-resource-manager and navigating between the same resources, e.g.

`/nova/resources/databoards/1` -> `/nova/resources/databoards/3`

the `nova-api/cards` request is not updated, so even the resource details are refreshed, the cards are not.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Install
https://novapackages.com/packages/nova-bi/nova-databoards
with 
https://novapackages.com/packages/digital-creative/collapsible-resource-manager

create 2 Databoards (listed in the menu), then navigate between them

**Comment by alberto-bottarini** [comment]
I think it's not a nova issue. You could ask to packages owners

**Comment by cord** [comment]
@alberto-bottarini I tested and am pretty sure it is a Nova issue. The links in the menu follow the correct format and clicking on them changes the page, but the cards() vue method is not updated. To the cards stay the same.

**Comment by alberto-bottarini** [comment]
You should open an issue that does not involve third-party packages. 
Nova admins are super busy and I think they will ignore issues that mention other packages.

**Comment by cord** [comment]
@alberto-bottarini thanks for the hint - will try to build a simple scenario

**Comment by davidhemphill** [comment]
Sorry, but we can't offer support for 3rd-party packages. Your best bet is to raise an issue on the GitHub repository of the package itself. If you still think there's an issue with Nova itself, please post a new issue with a reproducible example on a fresh Nova install without the package installed. Thanks!

**Comment by cord** [comment]
Did some investigation and narrowed it down to https://github.com/laravel/nova-issues/issues/2719
