### ISSUE TITLE
"An option named "no-interaction" already exists." on nova:tool

### ISSUE THREAD

**Issue by Tarpsvo** [laravel/nova-issues#2714]
- Laravel Version: 7.17.2
- Nova Version: 3.7.0
- PHP Version: 7.4.7
- Database Driver & Version: MySQL
- Operating System and Version: MacOS 10.15.3

### Description:

As described in https://github.com/laravel/nova/pull/901, `nova:tool` command now always throws the error `An option named "no-interaction" already exists.`

### Detailed steps to reproduce the issue on a fresh Nova installation:

Install Nova 3.7.0. Run `php artisan nova:tool`

**Comment by davidhemphill** [comment]
Duplicate of #2707
