### ISSUE TITLE
availableForNavigation() not working

### ISSUE THREAD

**Issue by noahlocke** [laravel/nova-issues#2717]
-Laravel Version: 7.18.0
-Nova Version: 3.7.1
-PHP Version: 7.4.7
-Database Driver & Version: mariadb 10.14.13
-Operating System and Version: MacOS Mojave 10.14.6

### Description:
Upon upgrading to Nova 3.7.2 from 2.12.0 all of my resources are appearing on the navigation menu, including the ones that are explicitly returning `false` from the `availableForNavigation()` function.

### Steps to reproduce the issue:

Include the following on any resource:
```php
public static function availableForNavigation(Request $request)
{
    return false;
}
```

The expected behavior is that the resource should _not_ appear on the left nav.

**Comment by jbrooksuk** [comment]
Sorry, but we are unable to debug your issue without a reproducible code example in v3.7.1. Once you provide that we can open this up again.
