### ISSUE TITLE
Filter's options array is not following best practice?

### ISSUE THREAD

**Issue by monaye** [laravel/nova-issues#2718]
I am new to Nova but I found it very weird why this was set up the way it is right now. 
Currently, the `options` method from the `Filter` class requires _human-friendly_ text to be `key` of the array instead of `value`. 

I tried to find if someone already opened the issue but couldn't find so opening a new one for the discussion. I can try to submit PR if this is something Laravel team wants to change.

**Comment by jbrooksuk** [comment]
I agree it's weird, but it's like this because you can choose to only pass labels. It also follows the `pluck` convention “title,id” order for selects in Eloquent.

**Comment by crynobone** [comment]
array key may only accept `string` or `int`, if you have any requirement to use other scalar type values then you wouldn't be able to use it on array key.
