### ISSUE TITLE
Change Request: make Vue Cards() dynamic

### ISSUE THREAD

**Issue by cord** [laravel/nova-issues#2719]
When switching directly between resource detail views (e.g. using [Collapsible Resource Manager
](https://novapackages.com/packages/digital-creative/collapsible-resource-manager) the cards are not updated.

Similar to the `getResource` Vue method a `getCards` method is required, which re-loads cards when the `resourceId` is changing, see

https://github.com/laravel/nova/blob/3.0/resources/js/views/Detail.vue#L501

Any hint where to start implementing this is appreciated - e.g. where do I find the `HasCards` vue component?

**Comment by jbrooksuk** [comment]
For reference, `HasCards` can be found at https://github.com/laravel/nova-js/blob/master/src/mixins/HasCards.js

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
Fixed and released on v3.21.1
