### ISSUE TITLE
Same page number when aplying items by page filter

### ISSUE THREAD

**Issue by lopandpe** [laravel/nova-issues#2721]
- Laravel Version: 6.18.13
- Nova Version: 2.12
- PHP Version: #.#.#

### Description:
When you change the filter of number of items by page, nova keeps you on the same page, even if now there aren't so many pages. It must jum to the first page (or to the last one available)

### Detailed steps to reproduce the issue on a fresh Nova installation:
With 60 items on a resource. Click on page 2. Change number of items by page to 100.

----
Thanks for your work!

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
