### ISSUE TITLE
High security fails

### ISSUE THREAD

**Issue by IgorDePaula** [laravel/nova-issues#2723]
- Laravel Version: 5.8
- Nova Version: 2.0
- PHP Version: 7.2
- Database Driver & Version:
- Operating System and Version: ubuntu 18.04
- Browser type and version: mozilla firefox
- Reproduction Repository: not aplicable

### Description:

I create a rule where only the unique email can access the dashboard, but if anyone user go to login form and request a reset password link, after he reset your password by link, it should can't access the dashboard.

### Detailed steps to reproduce the issue on a fresh Nova installation:

1- create laravel project and add nova them.
2- add auth scaffold
3- override the attemptLogin on Auth/LoginController add the code below:

 ```php 
protected function attemptLogin(Request $request)
    {
        if ($request->email != 'admin@example.com') {
            return redirect()->to('/admin');
        }
        return $this->guard()->attempt(
            $this->credentials($request), $request->filled('remember')
        );
    }
```

Anyone user can't access the dashboard, ok, its right, but on change your password by link reset password, they access the dashboard, and not should can.

**Comment by alberto-bottarini** [comment]
Using email as discriminant ia not a good idea.
I should add a new boolean column (e.g. admin) on users and check its truthiness.

**Comment by IgorDePaula** [comment]
I agree, but the client that request me.

**Comment by jbrooksuk** [comment]
If you want to prevent password resets, then don't call `withPasswordResetRoutes` within your `NovaServiceProvider`:

```diff
    protected function routes()
    {
        Nova::routes()
-                ->withAuthenticationRoutes()
                ->withPasswordResetRoutes()
                ->register();
    }
```

**Comment by IgorDePaula** [comment]
I means that the User don't should enter on system after reset your password. He should do login again.
