### ISSUE TITLE
nova.index Route Not Registered

### ISSUE THREAD

**Issue by sajanp** [laravel/nova-issues#2724]
- Laravel Version: 7.18.0
- Nova Version: 3.7.1
- PHP Version: 7.4.5
- Database Driver & Version: MySQL 5.7
- Operating System and Version: Ubuntu 18.04
- Browser type and version: Firefox 
- Reproduction Repository: N/A

### Description:
Trying to make a link to the route named `nova.index`, when the view is rendered an exception is thrown saying ```Route [nova.index] not defined.```

In ```php artisan route:list```, the ```nova.index``` route clear exists.

When dumping the routes on screen with ```Route::getRoutes()```, all Nova routes exist, except for ```nova.index```.

If I try to make a link to ```nova.logout```, that works perfectly as expected.

Nova service provider is defined in config/app.php, route:clear and config:clear have been run.

**Comment by jbrooksuk** [comment]
`nova.index` is registered automatically and dynamically by Nova. This is a reserved route.

**Comment by bilfeldt** [comment]
@jbrooksuk Does Nova provide any helper function for creating routes for a given resource? There must be a lot of situations where users would like to link to a given page.

Alternatively I guess the best option is to simple create it using the path (although I guess that can change at any time): `redirect(config('nova.path').'/resources/users/1');`

Thanks.
