### ISSUE TITLE
Notifications: add option to close and option to copy

### ISSUE THREAD

**Issue by joostvanhoof** [laravel/nova-issues#2725]
When something goes wrong a notification/toast is shown at the bottom left. What I often find is that:

1. The error message in the notification is long and I can't fully read it before it closes
2. I want to copy the error message

Adding a 'close' button to the notification would solve 1. If the auto-close behavior is something that needs to stay, it would be nice to increase the delay.

Add a 'copy' or 'copy and close' button to the notification would enable 2. If I want to copy the message now it's really difficult because if you want to select the text you're actually closing the notification.

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
