### ISSUE TITLE
Trashed filter is disappeared if nothing found in table

### ISSUE THREAD

**Issue by aghayeff** [laravel/nova-issues#2726]
- Laravel Version: 7.0
- Nova Version: 3.6.0
- PHP Version: 7.2.5
- Database Driver & Version: Mysql 8.0
- Operating System and Version: Mac OS Catalina

### I have a User Resource that includes Soft Deletes.  Lets say that there is only 1 user and  I want to soft delete it and then restore it.

But after deleting the table will be empty and trashed filter will be disappeared from table. So, I can not restore it. 

The only way is adding one more user, after this trashed filter will be displayed again.

**Comment by jbrooksuk** [comment]
Whilst testing this issue, I also noticed that the filter disappears when selecting "Only Trashed".

**Comment by preliot** [comment]
Also an issue on Nova 3.8.4. And @jbrooks, also noticed that one  :-)
