### ISSUE TITLE
Cannot globally search resource when `displayInNavigation` is set to false since 3.4

### ISSUE THREAD

**Issue by rikless** [laravel/nova-issues#2727]
- Laravel Version: 7
- Nova Version: From 3.4 to latest
- PHP Version: 7.4
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/laravel/nova-issues/issues/2520

### Description:
This bug is flagged since a long time ago. Didn't have any news about the issue : https://github.com/laravel/nova-issues/issues/2520

Email support does not respond with pro license, with email, or with the chatbox

### Detailed steps to reproduce the issue on a fresh Nova installation:

Is there a way to dig in, because we are locked on 3.3.2 ?

**Comment by jbrooksuk** [comment]
Please don't create duplicate issues.
