### ISSUE TITLE
Currency step value should not be auto-adjusted by currency

### ISSUE THREAD

**Issue by madsem** [laravel/nova-issues#2728]
Hi,

the step value shouldn't be auto set depending on base unit for the current currency.
If I have a field like this for example:

```php
Currency::make('MaxSpendWithoutRevenue', 'maxSpendWithoutRevenueAmount')
                    ->step(1)
                    ->currency($this->account->currency)
                    ->symbol($currencySymbol),
```

I'd expect the step value to be what I set it to, but then realized that Nova automatically adjusted the step value to be `0.01`. Even though I set it to `1`.

```php
/**
     * Determine the step value for the field.
     *
     * @return string
     */
    protected function getStepValue()
    {
        if ($this->minorUnits) {
            return '1.0';
        }

        return (string) 0.1 ** Currencies::getFractionDigits($this->currency);
    }
```

Solution is of course to add the `->step(1)` at the end after I set the currency dynamically. But still, this is unexpected and shouldn't work like that imho.

**Comment by crynobone** [comment]
I would think setting `->step(1)` as the last in chain is the right move here. 

Calling the following methods will override steps:

* `currency`
* `asMinorUnits`
* `asMajorUnits`

And depending on the sequences it always possible to have a inconsistent step value.
