### ISSUE TITLE
Nova resource use Nova default currency when Eloquent model has column named 'currency'

### ISSUE THREAD

**Issue by madsem** [laravel/nova-issues#2729]
- Laravel Version: 7.18.0
- Nova Version: 3.7.1
- PHP Version: 7.4.0
- Database Driver & Version: Mysql 8.0

### Description:
Given a migration like this:
```php
Schema::create('adv_accounts', function (Blueprint $table) {
            $table->id();
            $table->string('currency', 3)->default('EUR');
 });
```

And a Nova Resource Field like this:
```php
Text::make('Currency'),
```

Nova will always display 'USD' currency if that is the default setting.

When migration field is renamed to 'currency_code' for example, it works and displays the correct currency code.
```php
Text::make('Currency', 'currency_code'),
```

**Comment by davidhemphill** [comment]
Nova's `Text` field doesn't apply any special formatting to the underlying field values. 

If your example code happens to be a `Currency` field and not a `Text` field, the `Currency` field docs do state that Nova will use `USD` as the default unless you've overridden the `nova.currency` configuration value. Alternatively for the `Currency` field, you can override it using the `currency` setter.
