### ISSUE TITLE
Returning a response to a Resource detail page causes redirect to main Nova Dashboard

### ISSUE THREAD

**Issue by mitchierichie** [laravel/nova-issues#2731]
- Laravel Version: 7.19.0
- Nova Version: 3.7.1
- PHP Version: 7.4.6
- Database Driver & Version: mysql@5.7
- Operating System and Version: MacOS Catalina 10.15.5
- Browser type and version: Chrome 83.0.4103.116

### Description:

I have a resource tool that is registered to my Account resource. This resource tool sends a Nova.request().post() to an API route, and in that API route, if I send back a response like so:

```php 
$response = Http::get('some_endpoint');
return response($response->json(), $response->status());
```

Once the response is received on the resource's Detail page, I am redirected immediately back to /, or the top level of my Nova app. I've tried a number of workarounds, for example:

```php
return response()->json($response->json(), $response->status());
```

```php
return response($response->body(), $response->status());
```

```php
return response('xxx', 401);
```

If I just return an array, this seems to work just fine, but the problem is I want to be able to send the correct status code so I can then/catch the response in my Tool.vue.

### Detailed steps to reproduce the issue on a fresh Nova installation:

See above, just create a Nova installation, register any Resource Tool to the Account Resource, send a Nova request to an API endpoint, and return a response object.

If anyone can provide some insight on how I can avoid this issue, I'd greatly appreciate it. Is this expected behavior on a Resource Detail screen?

**Comment by jbrooksuk** [comment]
This is because of https://github.com/laravel/nova/blob/ba838d3d7d7dbd287386dc59f67021acc09f9977/resources/js/util/axios.js#L22-L34

**Comment by mitchierichie** [comment]
@jbrooksuk I appreciate the response! This is very useful information. Is it documented anywhere? 

I ask because I spent a lot of time trying to figure out what was happening and I think my browser may have even cached the redirect, as it was redirecting me even when I was returning 200 from my route.
