### ISSUE TITLE
Trix field "attach file" button always shows

### ISSUE THREAD

**Issue by TheOddler** [laravel/nova-issues#2732]
- Laravel Version: v7.19.0
- Nova Version: v3.7.1
- PHP Version: PHP 7.2.30
- Operating System and Version: Ubuntu Xenial in Docker
- Browser type and version: Firefox 78.0.1

### Description:

The "Attach file" button on the Trix field is shown even when not calling `withFiles`.

![image](https://user-images.githubusercontent.com/1831376/86940848-8d8cb580-c143-11ea-9789-f5959f6104ba.png)

![image](https://user-images.githubusercontent.com/1831376/86940871-92ea0000-c143-11ea-8270-3871aa5f472b.png)

The code to make the field is just:

`Trix::make('Text')` nothing else.

It seems this issue existed before (https://github.com/laravel/nova-issues/issues/2173) but was then fixed in Nova 2.8. However, the bug seems to be back.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Simply add a Trix field with `Trix::make('Text'),` and the button is there.

**Comment by jbrooksuk** [comment]
This is not a bug in Nova, but a decision in Trix that the button is always visible. You can hide it with a bit of CSS though. https://github.com/basecamp/trix/issues/775

**Comment by mgussekloo** [comment]
Strange decision by Trix, and very counterintuitive in Laravel Nova. Here's a workaround I came up with:

In the resource, make sure there's an extra attribute for Trix instances that support upload.

```php
Trix::make('Game introduction', 'introduction')->stacked()->withFiles('public')->withMeta(['extraAttributes' => [
    'data-has-upload' => 'true']
]),
```

Add some javascript to the Nova frontend (using Nova::script) to hide the upload button for any Trix without the extra attribute.

```js
addEventListener("trix-initialize", function(event) {
	var element = event.target;
	if (!element.hasAttribute("data-has-upload")) {
	    var toolbarElement = element.toolbarElement;
		var groupElement = toolbarElement.querySelector(".trix-button-group--file-tools");
		groupElement.style.display = 'none';
	}
});
```

**Comment by GautierDele** [comment]
Hello @jbrooksuk,

I believe this need to be included in Nova since in the doc, allowing uploads is only available when `withFiles` isn't false.
Adding a bit of code that reproduce the @mgussekloo behaviour isn't possible ?

Thanks

**Comment by resyncdigital** [comment]
@jbrooksuk this should fix it: (taking @mgussekloo 's example code a bit further):

`nova/resources//js/components/Trix.vue`

```
 initialize() {
      if (!this.withFiles) {
        var toolbarElement = this.$refs.theEditor.toolbarElement
        var groupElement = toolbarElement.querySelector(
          '.trix-button-group--file-tools'
        )
        groupElement.style.display = 'none'
      }

      this.$refs.theEditor.editor.insertHTML(this.value)

      if (this.disabled) {
        this.$refs.theEditor.setAttribute('contenteditable', false)
      }
    },
```
