### ISSUE TITLE
redirectAfterDelete not working

### ISSUE THREAD

**Issue by pxlrbt** [laravel/nova-issues#2735]
- Laravel Version: 7.17.1
- Nova Version: 3.7.1 (also tested with 3.2.1)
- PHP Version: 7.4
- Database Driver & Version: MariaDB 10.5
- Operating System and Version: Linux Arch
- Browser type and version: Chromium 83
- Reproduction Repository: https://github.com/pxlrbt/nova-resource-delete-redirect

### Description:

This feature was proposed here https://github.com/laravel/nova-issues/issues/2350 and implemented in v.2.12 (https://github.com/laravel/nova/pull/809).

When deleting a resource it successfully returns the redirect URL but the frontend won't react to it.

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Create a resource
- Go to detail page
- Delete resource

**Comment by anditsung** [comment]
@jbrooksuk 

can make ReosurceDestroyController like this?

```
$request->chunks(150, function ($models) use ($request) {
    $models->each(function ($model) use ($request, &$oldModel) {
        $this->deleteFields($request, $model);

        if (in_array(Actionable::class, class_uses_recursive($model))) {
            $model->actions()->delete();
        }

        $model->delete();

        tap(Nova::actionEvent(), function ($actionEvent) use ($model, $request) {
            DB::connection($actionEvent->getConnectionName())->table('action_events')->insert(
                $actionEvent->forResourceDelete($request->user(), collect([$model]))
                    ->map->getAttributes()->all()
            );
        });

        if ($request->isForSingleResource()) {

            return response()->json([
                'redirect' => $request->resource()::redirectAfterDelete($request, $model),
            ]);
        }
    });
});
```

since the redirect only work for single resource and with this can work with redirectafterdelete with parent resource

**Comment by mark-apn** [comment]
I can confirm this. In the inspector I can see the correctly overridden URL. But the Vue frontend is not redirecting to the page.

![afbeelding](https://user-images.githubusercontent.com/62654433/91580457-6ab19d00-e94d-11ea-84cc-c07e0b28f5b5.png)
