### ISSUE TITLE
Markdown Fields Not showing on Show Page

### ISSUE THREAD

**Issue by mdavis1982** [laravel/nova-issues#274]
Nova Version: 1.0.6

If I have a Markdown field in my resource, and the underlying data is null, I'm not seeing the corresponding field on the show page:

<img width="1100" alt="screen shot 2018-08-28 at 12 55 07" src="https://user-images.githubusercontent.com/199807/44721369-9df09580-aac1-11e8-8e1c-01c5b0f62110.png">

<img width="1145" alt="screen shot 2018-08-28 at 12 55 32" src="https://user-images.githubusercontent.com/199807/44721386-ab0d8480-aac1-11e8-869a-258f88480acc.png">

**Comment by bradders** [comment]
@mdavis1982 Is this still an issue? Do you see the same error that I get in my issue: https://github.com/laravel/nova-issues/issues/405

**Comment by davidhemphill** [comment]
This has been fixed and will be included in an upcoming release.
