### ISSUE TITLE
[FR] Prevent Action Field dataloss when clicking outside of Action Modal

### ISSUE THREAD

**Issue by AlbinoDrought** [laravel/nova-issues#2741]
(Since this does not seem supported in core, I will probably hack out a solution)

We use Actions in our instance of the Laravel Nova dashboard. Some of these Actions have Fields. There have been at least a few times where users are filling out the fields and accidentally click outside of the Modal. This causes the Modal to disappear and all entered data to be lost.

Here is a demo: https://webmshare.com/play/yj7ob

I see two quick solutions:

- Show a confirmation inbetween Modal.vue `v-on-clickaway` and `emit('modal-close')`
- Bring back the same Field data when reopening the Action (probably messy)

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by AlbinoDrought** [comment]
For what it's worth, here is what I ended up with:

```js
(function () {
    var observer = new MutationObserver(function (mutations) {
        mutations.forEach(function (mutation) {
            mutation.addedNodes.forEach(function (addedNode) {
                if (addedNode.classList && addedNode.classList.contains('modal') && addedNode.getAttribute('data-testid') === 'confirm-action-modal') {
                    if (addedNode.hasAttribute('data-click-propagation-disabled')) {
                        return;
                    }
                    addedNode.setAttribute('data-click-propagation-disabled', true);
                    addedNode.addEventListener('click', function (e) {
                        e.stopPropagation();
                    });
                }
            });
        });
    });

    observer.observe(document.body, { childList: true, subtree: true });
})();
```

**Comment by vesper8** [comment]
I'd like to implement your solution @AlbinoDrought, thanks for sharing it.

So this prevents modals from closing when you click on the overlay?

How are you loading this script exactly? You're adding it to a published view.. such as inside resources/views/vendor/nova/layout.blade.php ? 

I've never tried to add a script this way.. can you share a snippet of exactly how you're using Nova::script to add this?

Many thanks!

**Comment by AlbinoDrought** [comment]
Hey @vesper8 , I do it simliar to a [custom Nova tool](https://nova.laravel.com/docs/3.0/customization/tools.html#registering-assets) using `Nova::script` inside a `Nova::serving` block. 

Here is what I currently have: (all paths relative to Laravel project root)

./resources/js/nova/no-dialog-clickoutside.js

```js
// See also https://github.com/laravel/nova-issues/issues/2741

// 2020-07-16: Modals currently look like this:
// <div class="modal select-none fixed pin z-50 overflow-x-hidden overflow-y-auto text-left" data-testid="confirm-action-modal" tabindex="-1" role="dialog">

(function () {
    var observer = new MutationObserver(function (mutations) {
        mutations.forEach(function (mutation) {
            mutation.addedNodes.forEach(function (addedNode) {
                if (addedNode.classList && addedNode.classList.contains('modal') && addedNode.getAttribute('data-testid') === 'confirm-action-modal') {
                    if (addedNode.hasAttribute('data-click-propagation-disabled')) {
                        return;
                    }
                    addedNode.setAttribute('data-click-propagation-disabled', true);
                    addedNode.addEventListener('click', function (e) {
                        e.stopPropagation();
                    });
                }
            });
        });
    });

    observer.observe(document.body, { childList: true, subtree: true });
})();
```

./app/Providers/NovaServiceProvider.php

```php
<?php

// <snip>

class NovaServiceProvider extends NovaApplicationServiceProvider
{
    // <snip>
    public function boot()
    {
        parent::boot();
        Nova::serving(function () {
            // disabling closing of action dialog boxes on click-outside, https://github.com/laravel/nova-issues/issues/2741
            Nova::script('no-dialog-clickoutside', resource_path('js/nova/no-dialog-clickoutside.js'));
        });
    }
    // <snip>
}
```

**Comment by vesper8** [comment]
@AlbinoDrought thank you!! that's so useful to know I can do this. Thanks to your clear instructions I got it working in under a minute. Great day to you sir!
