### ISSUE TITLE
add setPivot feature

### ISSUE THREAD

**Issue by ahmedsayedabdelsalam** [laravel/nova-issues#2742]
<img width="693" alt="Screen Shot 2020-07-17 at 3 18 38 AM" src="https://user-images.githubusercontent.com/29691074/87737993-aa2c8b80-c7dc-11ea-9c6a-6b4a68b5b81d.png">

**Comment by AforDesign** [comment]
Working with properties on Pivots is possible:
https://nova.laravel.com/docs/3.0/resources/relationships.html#pivot-fields

If you want to be able to directly set the value of it from your model, you can try a Nova Package for online editing, or set a Mutator and Accessor on your original model. For example:

Add a new property to your model to access the pivot property.
You can name it as you wish.
```
protected $appends = [
    'isAvailable',
];
```

Add an Accessor to get it's value (getter):
```
public function getIsAvailableAttribute($value) {
        // get existing property from specifications relation, I assume your property name is set in a 'name' column
        return $this->specifications->firstWhere('name', 'is_available);
}
```

Add an Accessor to set it's value (setter):
```
public function setIsAvailableAttribute($value) {
        // get existing property from specifications relation, I assume your propertyn value is set in a 'value' column
        $this->specifications->firstWhere('name', 'is_available)->value=$value;
}
```

This example is overly simplified/
You should add checks if the specification is set at all and what to do when not.

**Comment by ahmedsayedabdelsalam** [comment]
Many thanks for your reply.


I think I can not use this pattern 
I'll try to explain the situation
I have CarCategory model and Specification model the relationship between them is many to many 
The pivot table has an extra field named is_available and it is a Boolean 
I setup two relations in the category model 
availableSpecificatios (whereapivot is_available is true)
missingSpecifications (whereapivot is_available is false)

I wantes to have different relations each of them sets the is_available value depend on the relation so I don't think the mutator would help

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
