### ISSUE TITLE
Add support for "county" auto-completion, in Place Field

### ISSUE THREAD

**Issue by aedart** [laravel/nova-issues#2745]
In some situations, it would be really nice to be able to use the "county" information, that is delivered by Algolia places API.
Thus, if the Place Field could be expanded to auto-complete a county field, that would be really great.

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by stockhausen** [comment]
sorry we need county !

**Comment by crynobone** [comment]
Place Field has been deprecated, removing `request` tag.
