### ISSUE TITLE
currency field's design is corrupted in forms for small screens

### ISSUE THREAD

**Issue by osamaAbdullah** [laravel/nova-issues#2746]
- Laravel Version: 7
- Nova Version: 3.7
- PHP Version: 7

### currency fields design is corrupted in forms for small screens:

![this is the screenshot](https://user-images.githubusercontent.com/26807223/87974123-39ce8480-cad2-11ea-9445-78a695918017.png)

while other fields design is very good

![image](https://user-images.githubusercontent.com/26807223/87974253-713d3100-cad2-11ea-87eb-cee3e2dcf0a1.png)
 

### it's corrupted only in small screens

this is the related code
```
Currency::make('Shipping price', 'shipping')
					->step(0.01)
					->max(1000000000000)
					->min(0)
					->creationRules('required', new MinimumRequiredBalance)
					->updateRules('required', new UpdatingOrderRule(optional($this)->id), 'min:0'),

Currency::make('Internal shipping', 'internal_shipping')
					->withMeta([
						'value' => optional($this)->internal_shipping ?? 0 ,
					])
					->max(1000000000000)
					->step(0.01)
					->min(0)
					->rules('required', 'min:0'),
```

**Comment by jbrooksuk** [comment]
Are you using a custom or responsive theme somewhere? I can't replicate this.

![image](https://user-images.githubusercontent.com/246103/88028120-23571600-cb30-11ea-8886-3c9dcf25aef0.png)

**Comment by davidhemphill** [comment]
Nova isn't provided with a responsive interface.
