### ISSUE TITLE
Per model timezone setting

### ISSUE THREAD

**Issue by jontas** [laravel/nova-issues#2747]
I would love the ability to set a model's timezone for its date/datetime fields.  Rather than have just a single timezone based on the user's setting I need each model to be able to set its own timezone based on another property.

Maybe an API like:

```
DateTime::make('created_date')->withTimezone(function($object) {
    return $object->timezone;
});
```

**Comment by jbrooksuk** [comment]
Try this:

```php
DateTime::make('Created At', 'created_at', function ($value) {
    return $value->timezone('Europe/London');
}),
```

**Comment by mbryne** [comment]
How did you go with this @jontas?

I have not had any luck using the example above, it always stays locked to my default App timezone,

I tried using the example above, and extra attempts using `resolveUsing` and `displayUsing`.
