### ISSUE TITLE
npm package laravel-nova 1.2.1+ breaks error messages

### ISSUE THREAD

**Issue by uandco** [laravel/nova-issues#2748]
- Laravel Version: 6.18.25
- Nova Version: 2.9.2
- PHP Version: 7.3.10

### Description:

That might be specific to the Larval version I use but I inherited the project and haven't tried to upgrade to the latest 2.x version yet, but compiling components with npm's laravel-nova 1.2.1 or 1.2.2 breaks error messages (works with 1.2.0).

### Detailed steps to reproduce the issue on a fresh Nova installation:

```
cd nova
npm install
mv webpack.mix.js.dist webpack.mix.js
npm run dev
```

That will use the latest laravel-nova package (1.2.2)
The produced vendor.js file will have this chunck of code:

```
  computed: {
    errorClasses: function errorClasses() {
      return this.hasError ? [this.errorClass] : [];
    },
    fieldAttribute: function fieldAttribute() {
      return this.field.attribute;
    },
    validationKey: function validationKey() {
      return this.field.validationKey;
    },
    hasError: function hasError() {
      return this.errors.has(this.validationKey);
    },
    firstError: function firstError() {
      if (this.hasError) {
        return this.errors.first(this.validationKey);
      }
    }
  }
```

This doesn't show error messages anymore when fields are validated

Now force laravel-nova to 1.2.0, rebuild, vendor.js now contains:

```
  computed: {
    errorClasses: function errorClasses() {
      return this.hasError ? [this.errorClass] : [];
    },
    fieldAttribute: function fieldAttribute() {
      return this.field.attribute;
    },
    hasError: function hasError() {
      return this.errors.has(this.fieldAttribute);
    },
    firstError: function firstError() {
      if (this.hasError) {
        return this.errors.first(this.fieldAttribute);
      }
    }
  }
```

The whole `validationKey` bit is gone and error messages display correctly.

Is that specific to Nova 2.9.2 and this version needs to stick to the npm package laravel-nova 1.2.0?

Thanks

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!

**Comment by ngiraud** [comment]
Hi, I'm working on a Laravel 6 installation and Nova 2.12.0 installation, which is the latest available update for a Laravel 6 application, and I still have the problem.

- Laravel Version: 6.18.41
- Nova Version: 2.12.0
- PHP Version: 7.3.16

The problem is for Nova 2.12 there isn't a validationKey in the field prop, and since the nova-js 1.5 version it uses this key, see : https://github.com/laravel/nova-js/commit/4fe3c28683f20db485d7ddc50df579c63c6ad2ed#diff-47145c3e7e815109007db7d2e4b82eab

**Comment by uandco** [comment]
@ngiraud replace `"laravel-nova": "^1.2.0"` with `"laravel-nova": "1.2.0"` in package.json so the dependency doesn't get upgraded to the breaking version.

**Comment by ngiraud** [comment]
@uandco I did that, the problem is I have to edit the package.json in the nova vendor folder to get it done, and I don't think this is the right way to do it.

@jbrooksuk Do you think a version can be tagged with this change for the 2.12 version of Nova?
