### ISSUE TITLE
Change custom dashboard titles

### ISSUE THREAD

**Issue by bernhardh** [laravel/nova-issues#2749]
Not sure if its a bug or a feature. At the moment, you can't change the title of a custom dashboard. I know, that I could change the translation, but this would change the title of ALL dashboards. So for example, if you have multiple dashboards, all of them will be called "Dashboard" (or whatever translation you used).

The `label()` method is only used for the sidebar, not for the "page title". Here is the code from `resources/js/views/Dashboard.vue`

```vue
    <heading v-if="cards.length > 1" class="mb-6">{{
      __('Dashboard')
    }}</heading>
```

**Comment by jbrooksuk** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by vesper8** [comment]
@bernhardh did you figure it out ?
