### ISSUE TITLE
Add $withCount property to resource

### ISSUE THREAD

**Issue by chescos** [laravel/nova-issues#275]
It would be awesome to have a `$withCount` property on a resource, so that the specified relationship counts would be eager loaded through `withCount()`. Due to performance it's currently impossible to show the count of relations that have hundreds or even thousands of entries through the  `$with` property.

**Comment by Andy-Baker** [comment]
I got around this by modifying the query for specific pages. For example, this is in my User resource:

```
    public static function indexQuery(NovaRequest $request, $query)
    {
        return $query->withCount('images');
    }
```

You then add this to fields()

```
Number::make('Images', 'images_count')
    ->sortable()
    ->onlyOnIndex(),
```

**Comment by davidhemphill** [comment]
No plans to add this currently. The solution above looks like what you need. 👍
