### ISSUE TITLE
detach belongstomany with softdelete not working correctly

### ISSUE THREAD

**Issue by AforDesign** [laravel/nova-issues#2750]
- Laravel Version: 7.20.0
- Nova Version: 3.7.1
- PHP Version: 7.4.1.
- Database Driver & Version: MySQL 5.7.26

### Description:
Detaching a `BelongsToMany` Relation with the `SoftDelete` trait on the pivot table does not reflect in Nova.

The `deleted_at` field of the record does got set.
Yet, the relation is still shown as attached in Nova.
`TrashedOnly` shows nothing.

**This actually results in a bigger problem:**
The relation cannot be force deleted.
The soft-delete cannot be undone

You have to manually edit the database, or manage the softdelete outside Nova.

**Comment by oleghmelevschi** [comment]
+1 here

**Comment by crynobone** [comment]
After reviewing the whole implementation we are unable to support the feature at the moment since soft deletes for pivots aren't officially supported by Laravel Framework.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
