### ISSUE TITLE
Extend from nova::layout on app view

### ISSUE THREAD

**Issue by socialab-admin** [laravel/nova-issues#2751]
- Laravel Version: 7.21.0
- Nova Version: 3.8.0
- PHP Version: 7.2.5

Description:
When trying to use the Nova layout (vendor/nova/layout.blade.php) within a non-Nova view, I get this error.

`Uncaught TypeError: Cannot read property 'forEach' of undefined`

Steps To Reproduce:
Copy `cp nova/resources/views/layout.blade.php resources/views/vendor/nova/layout.blade.php`
Add `@extends('nova::layout')` inside an app view e.g.resources/views/test.blade.php.

**Comment by jbrooksuk** [comment]
Nova layouts aren't designed to be used like this. You'll probably need to remove some of the JS code from the layout and create a copy of it.
