### ISSUE TITLE
HasOne relationship displays a table as if it were a HasMany relationship

### ISSUE THREAD

**Issue by xoco70** [laravel/nova-issues#2753]
- Laravel Version: 7.20.0
- Nova Version: 3.7.1
- PHP Version: 7.4.3
- Database Driver & Version: Postgres 12.2
- Operating System and Version: Ubuntu 20.04
- Browser type and version: Chrome Version 84.0.4147.89 (Official Build) (64-bit)

### Description:

When I include a HasOne::make('meter') in my User model, it displays it as a list.

So I've made this workaround:

```
           new Panel('Compteur',
                [
                    Text::make('PRM', 'meter.prm'),
                    Text::make('Label', 'meter.label'),
                    Text::make('Type', 'meter.conso_prod'),
                    Text::make('Priorité', 'meter.pack'),
                    Boolean::make('Autoconsommation individuelle ?', 'meter.aci'),
                    Text::make('Type', 'meter.conso_prod'),
                ]
            ),
            new Panel(' Adresse',
                [
                    Place::make('Adresse', 'meter.address_line_1')->countries(['FR'])->hideFromIndex(),
                    Text::make('Adresse Ligne 2', 'meter.address_line_2')->hideFromIndex(),
                    Text::make('Ville', 'meter.city')->hideFromIndex(),
                    Text::make('Code postal', 'meter.cp')->hideFromIndex(),
                    Country::make('Pays', 'meter.country')->hideFromIndex(),
                    Text::make('meter.Latitude')->hideFromDetail(),
                    Text::make('meter.Longitude')->hideFromDetail(),

                    MapMarker::make('Localisation')
                        ->latitude('meter.latitude')->default(0)
                        ->longitude('meter.longitude')->default(0)
                        ->defaultZoom(17)
                        ->hideFromIndex(),
                ]), 

```
But now all fields are present in creation form.

HasOne::make('meter') should display info natively, not like a hasMany relationship

**Comment by jbrooksuk** [comment]
Can you please provide some screenshots as to how these are displaying and how you'd expect them to display?

**Comment by xoco70** [comment]
Hi, 

Here is the screenshot

![hasOne](https://user-images.githubusercontent.com/5855577/88541553-34fb5a80-d015-11ea-9d3b-897c0c6e7b72.png)

And the field is defined with:

`HasOne::make('Compteur', 'meter', 'App\Nova\Meter'),`

If I know there will be only one result, I would expect the hasOne relationship to display the details into a panel, not a list. A list is good for hasMany relationship.

**Comment by jbrooksuk** [comment]
Thanks for confirming this. I am going to covert the `HasOne` field to a separate `Panel` component.

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by rdarcy1** [comment]
@jbrooksuk Could you confirm if this is being implemented?
