### ISSUE TITLE
Partition Metric percentage are not display( more then 1000 record)

### ISSUE THREAD

**Issue by xiyixia** [laravel/nova-issues#2755]
- Laravel Version: 7.21.0
- Nova Version: 3.8.1
- PHP Version: 7.2.19
- Database Driver & Version: mysql 5.7
- Operating System and Version: ubuntu18.04
- Browser type and version: Chrome 83.0.4103.116

### Description:
Partition Metric percentage are not display in more then 1000 records 
![image](https://user-images.githubusercontent.com/16682676/88267956-315d9000-cd04-11ea-945f-2e170729d945.png)
But it's ok when records are less then 1000 
![image](https://user-images.githubusercontent.com/16682676/88268021-50f4b880-cd04-11ea-9bb7-94b84b9c14f5.png)

```
class UserActPlan extends Partition
{
    /**
     * Calculate the value of the metric.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @return mixed
     */
    public function calculate(NovaRequest $request)
    {
        return $this->count($request, AppLog::class, 'act');
    }

    /**
     * Determine for how many minutes the metric should be cached.
     *
     * @return  \DateTimeInterface|\DateInterval|float|int
     */
    public function cacheFor()
    {
        // return now()->addMinutes(5);
    }

    /**
     * Get the URI key for the metric.
     *
     * @return string
     */
    public function uriKey()
    {
        return 'api-user-act-plan';
    }
}
```

**Comment by skollro** [comment]
@davidhemphill, this is still a bug in v3.23.1 and should not be closed :)

**Comment by crynobone** [comment]
@skollro there seem to be a regression bug introduced in `3.23`, submitted a PR

**Comment by philipbaginski** [comment]
The same.
