### ISSUE TITLE
Using Laravel Nova with Timeseries database TimescaleDB ( from Postgres )

### ISSUE THREAD

**Issue by xoco70** [laravel/nova-issues#2756]
- Laravel Version: 7.20.0
- Nova Version: 3.7.1
- PHP Version: 7.4.3
- Database Driver & Version: Postgres 12 with TimescaleDB 12
- Operating System and Version: Ubuntu 20.04

### Description:
I am using TimescaleDB, from postgres. 

I can use eloquent to query my timeSerie table, as if it were any postgres table, in Laravel, but when I try to access Laravel Nova resource, I get an error message telling me there is no 'id' field, which is correct.

Is there a way to manage TimescaleDB data for readonly purposes?

How should I configure my resource ?

**Comment by jbrooksuk** [comment]
Hey @xoco70, we received your support ticket, and David has replied.
