### ISSUE TITLE
Can't sort sortable after sorting twice

### ISSUE THREAD

**Issue by dtannen** [laravel/nova-issues#2757]
- Laravel Version: 7.2.0
- Nova Version: 3.8.1
- PHP Version: 7.4
- Database Driver & Version: MySQL
- Operating System and Version: Ubuntu
- Browser type and version: Chrome

### Description:

On many sortable fields, after you sort twice - it will not allow you to sort again.   DateTime specifically always has this behavior.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Make a sortable DateTime column and then click the sort more than twice.

**Comment by crynobone** [comment]
Unable to replicate the issue on latest Laravel Nova.

![CleanShot 2020-10-26 at 12 32 29](https://user-images.githubusercontent.com/172966/97134177-6eb03e80-1787-11eb-9c40-1bcc9d2fd7f0.gif)
