### ISSUE TITLE
Add ability to disable database transaction on Nova Actions

### ISSUE THREAD

**Issue by andreisusanu** [laravel/nova-issues#2758]
Currently everything that runs inside an Action runs within DB transaction.

```Laravel\Nova\Actions\Transaction```

This can be problematic when creating new models and dispatch queueble jobs using the new model.
Our current fix is to call DB::commit() after saving the new model, and then dispatch it to the job queue.

It would be nice to have an explicit way of disabling DB transaction at Action level.

**Comment by jbrooksuk** [comment]
Duplicate of https://github.com/laravel/nova-issues/issues/180
