### ISSUE TITLE
The Nova homepage is using false advertising

### ISSUE THREAD

**Issue by chescos** [laravel/nova-issues#2759]
### Description:

The [Nova homepage](https://nova.laravel.com/) says:
> Every type of Eloquent relationship is fully supported.

See:

![image](https://user-images.githubusercontent.com/12296880/88467471-d7152880-ced7-11ea-961a-8a955f7e6e5f.png)

This is factually incorrect and pretty misleading. The [HasManyThrough](https://laravel.com/docs/7.x/eloquent-relationships#has-many-through) relationship is [not supported](https://github.com/laravel/nova-issues/issues/585) and there are also officially [no plans to add support](https://github.com/laravel/nova-issues/issues/1683#issuecomment-506413763) for it.

Could you please remove the false advertising from the Nova homepage? Some people might buy it and actually expect all Eloquent relationships to be fully supported, as advertised.

**Comment by jbrooksuk** [comment]
At the time Nova was released, the `HasManyThrough` relationship wasn't a thing.
