### ISSUE TITLE
Bug: Action with Action::download response won't download in Firefox

### ISSUE THREAD

**Issue by andypa** [laravel/nova-issues#276]
Nova version: 1.0.6
Firefox version: 62.0b20 
Chrome version: 68.0.3440.106

I created an action which creates a PDF and after creation, the PDF should be prompted to download. The return statement looks like this: 

`
return Action::download(url($filePath), 'mypdf.pdf');
`

In Firefox, the download prompt doesn't show up. When trying the same action in Chrome, I get prompted for the download of the file.

**Comment by AegirLeet** [comment]
ActionSelector.vue uses `document.createElement('a')` to create a link and `link.click()` to simulate a click (triggering the download). In Firefox, this won't work unless the link is also explicitly added to the DOM before clicking it.
Something like `document.body.appendChild(link)` will fix this bug.

**Comment by BengtHagemeister** [comment]
@AegirLeet this fix worked for me.

**Comment by orlyapps** [comment]
@AegirLeet This fix works. Any Update on a offical fix?

**Comment by XGhozt** [comment]
+1

**Comment by techouse** [comment]
Any development on this issue? 😐

**Comment by laurencei** [comment]
Ran into this issue as well.

When exporting, you can see the network request, and a 200 status return - but the response does not trigger a download in Firefox (but does in Chrome ok).

See screenshot. Chrome is on the left, and it work perfectly. Firefox is on the right - no download. No errors in console.

![ff](https://user-images.githubusercontent.com/1210658/46928114-a78b8800-d084-11e8-9b95-6e642633861e.gif)

**Comment by SchuBu** [comment]
> 
> 
> ActionSelector.vue uses `document.createElement('a')` to create a link and `link.click()` to simulate a click (triggering the download). In Firefox, this won't work unless the link is also explicitly added to the DOM before clicking it.
> Something like `document.body.appendChild(link)` will fix this bug.

where exactly in ActionSelector.vue do I have to put the code-portion? 

Thx!

Peter

**Comment by AegirLeet** [comment]
Inside the `handleActionResponse` method, add `document.body.appendChild(link)` before the `link.click()`.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in an upcoming release.

**Comment by Nassu972** [comment]
Here using 1.3.0 and still got this bug

**Comment by Ange7** [comment]
laravel 5.7
laravel nova : dev-prod
Firefox : quantum 64.0

same problem...
