### ISSUE TITLE
Trigger action from a card

### ISSUE THREAD

**Issue by aedart** [laravel/nova-issues#2761]
I have a "minor" situation, where I need to trigger a specific resource's action, from a card. Unfortunately, there appears no easy way to achieve this.
More specifically, it is the modal dialog that I wish to open, so that additional information associated with the action can be filled by users. Furthermore, the card is displayed on a dashboard, where it makes the most sense for some users to perform "quick" actions.

**Comment by milewski** [comment]
I'm still writing docs for this unreleased package but it seems to provide exactly what you need: https://github.com/dcasia/nova-dashboard

**Comment by jbrooksuk** [comment]
You can build a custom card for this.

**Comment by aedart** [comment]
@milewski Thanks mate. Your project looks very interesting - I will give it a try.
