### ISSUE TITLE
Action fields: Rules apply even if a field is not loaded

### ISSUE THREAD

**Issue by v-bubar** [laravel/nova-issues#2763]
- Laravel Version: 7.21.0
- Nova Version: 3.6.0
- PHP Version: 7.4.5
### Description:
I have an action where the `fields` method loads two different sets of fields depending on a condition. I get validation errors for one set of fields event though another one is loaded. 

### Detailed steps to reproduce the issue on a fresh Nova installation:
In `fields` method fo a action:
```
if ($condition) {
    return [
        Heading::make('Lorem ipsum dolor sit amet')->asHtml();
    ];
} 

return [
    Text::make('Foo', 'foo')->rules('required'),
];
```
Even thou `$condition` is true and the heading is loaded, I receive validation error saying that `foo` is required. 
This doesn't happen if I use `required()` instead of `rules('required')`.

**Comment by jbrooksuk** [comment]
Instead of using a condition for which fields to display, try using https://nova.laravel.com/docs/3.0/resources/fields.html#dynamic-field-methods

**Comment by v-bubar** [comment]
@jbrooksuk Unfortunately, I don't think this is relevant in my case, because the `$condition` does not depend on context and my action is detail-only anyways.
