### ISSUE TITLE
Support withPivotValue

### ISSUE THREAD

**Issue by buttjer** [laravel/nova-issues#2764]
- Laravel Version: 7.0.0
- Nova Version: 3.0.0
- PHP Version: 7.4.0
- Database Driver & Version: mariadb 10
- Operating System and Version: docker
- Browser type and version: chrome current

### Description:

The BelongsToMany.php function ```withPivotValue``` is not fully supported. New pivot records will not receive the value.

### Detailed steps to reproduce the issue on a fresh Nova installation:

use and expect ```withPivotValue``` as described in BelongsToMany.php:

```php
    /**
     * Set a where clause for a pivot table column.
     *
     * In addition, new pivot records will receive this value.
     *
     * @param  string|array  $column
     * @param  mixed  $value
     * @return $this
     *
     * @throws \InvalidArgumentException
     */
```

**Comment by crynobone** [comment]
Hi @buttjer 

Can you share a reproducing code for the missing use case.

**Comment by buttjer** [comment]
Hi @crynobone 

App\Nova\User
```php 
use Laravel\Nova\Fields\BelongsTo;

BelongsTo::make('Childrens')->nullable();
BelongsTo::make('Parents')->nullable();
```

 App\Models\User
```php

public function childrens() {
    return $this->belongsToMany('App\Models\User')->withPivotValue('relation', 'children');
}

public function parents() {
    return $this->belongsToMany('App\Models\User')->withPivotValue('relation', 'parent');
}

```

**Comment by buttjer** [comment]
@crynobone @jbrooksuk Please keep in mind that this would be a nice workaround for this heavy issue: #2625
