### ISSUE TITLE
required_if validation not working

### ISSUE THREAD

**Issue by arall** [laravel/nova-issues#2766]
- Laravel Version: 7.0
- Nova Version: 3.0
- PHP Version: 7.3
- Database Driver & Version: MySQL
- Operating System and Version: Vagrant / Homestead
- Browser type and version: Chrome

### Description:

I'm facing an issue when using `required_if` validation.

Here is the code I'm using in the resource fields:

```
BelongsTo::make('Asset Status', 'status'),
BelongsTo::make('Employee')->nullable()->rules('required_if:status_id,1'),
````

So, according to the Laravel docs, if the Status field (status_id) equals 1, the Employee field will be required, but it doesn't work (is not required)

I've also tried by removing the `nullable()` method, but then it is always required, it doesn't matter what value is on `status_id`.

**Comment by davidhemphill** [comment]
The attribute being validated is ‘status’ not ‘status_id’. Changing it to ‘status’ will make it validate correctly.
