### ISSUE TITLE
Error translating :resource in singular form

### ISSUE THREAD

**Issue by henryavila** [laravel/nova-issues#2767]
- Laravel Version: 7.20.0
- Nova Version: 3.7.1

### Description:
The translation of: "No :resource matched the given criteria" don't consider the Resource `singularLabel()`.
In my case, the resource name is: "**Inscrições**" and the singular form (`singularLabel()`) is "**Inscrição**".

The translation of "No :resource matched the given criteria"  becomes 
"Nenhum **inscriçõe** correspondeu aos critérios indicados", instead of 
"Nenhum **inscrição** correspondeu aos critérios indicados."

**Comment by milewski** [comment]
I don't think `Str::plural/Str::singular` understands Portuguese, I think it is English only.. but regardless the translation of "Nenum inscrição" and "Nenum inscriçõe" isn't right anyway it's missing an `A` *Nenhuma* :P

**Comment by jbrooksuk** [comment]
Yes, this is a Laravel translation issue.
