### ISSUE TITLE
email always required on create or update

### ISSUE THREAD

**Issue by anditsung** [laravel/nova-issues#2768]
- Laravel Version: 7.21
- Nova Version: 3.8.2
- PHP Version: 7.4.8
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:
email always required even set nullable
<img width="1042" alt="Screen Shot 2020-07-28 at 13 17 18" src="https://user-images.githubusercontent.com/1090413/88626340-af3ee400-d0d4-11ea-87ff-509b3e572f61.png">

### Detailed steps to reproduce the issue on a fresh Nova installation:
```
public function fields(Request $request)
    {
        return [
//            ID::make()->sortable(),

            Text::make('Name')
                ->rules('required')
                ->creationRules('unique:religions,name')
                ->updateRules('unique:religions,name,{{resourceId}}'),

            BelongsTo::make('User')
                ->onlyOnDetail(),

            Text::make('Email')
                ->nullable()
                ->rules('email')
                ->hideFromIndex(),

            Hidden::make('user_id')
                ->default($request->user()->id),
        ];
    }
```

**Comment by milewski** [comment]
@anditsung I have the following and it works:

```php
Text::make('Email')
                    ->nullable()
                    ->creationRules('nullable', 'unique:users,email')
                    ->updateRules('nullable', 'unique:users,email,{{resourceId}}'),
```

**Comment by anditsung** [comment]
Field is not nullable until add required rules?

**Comment by milewski** [comment]
@anditsung `->nullable()` only makes the select option to be able to select no value it has nothing to do with validation

**Comment by davidhemphill** [comment]
The values of `rules` are merged in with `creationRules` and `updateRules`. If you need separate validation for each you should only use `creationRules` or `updateRules`.
