### ISSUE TITLE
Action name asHtml

### ISSUE THREAD

**Issue by Paulsky** [laravel/nova-issues#2769]
I would like to use HTML (icons) in my Action Table Row buttons (showOnTableRow). Please see; https://nova.laravel.com/docs/3.0/actions/defining-actions.html#action-titles

```
/**
 * The displayable name of the action.
 *
 * @var string
 */
//public $name = 'Action Title';
public $name = '<span class="my-custom-class">Action <strong>Title</strong></span>';
```

Please add something like 'asHtml' to the Action. I tried `->withMeta(['asHtml' => true])`. But no luck.

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by Paulsky** [comment]
Maybe this issue is kind of related; https://github.com/laravel/nova-issues/issues/2617
