### ISSUE TITLE
Disable href to belongsTo field

### ISSUE THREAD

**Issue by cerelli** [laravel/nova-issues#277]
Is it possible to disable the href link on belongsTo field ?
![esempio](https://user-images.githubusercontent.com/6558535/44723410-368e1200-aad0-11e8-876f-27d50e27d355.png)

**Comment by wfeller** [comment]
You can use a computed field maybe?
https://nova.laravel.com/docs/1.0/resources/fields.html#computed-fields

Text::make('Title', function () {
    return $this->title->your_key;
})

**Comment by cerelli** [comment]
Thanks !
