### ISSUE TITLE
BelongsTo Field Are Always Ordered Alphabetically

### ISSUE THREAD

**Issue by mdavis1982** [laravel/nova-issues#2771]
- Laravel Version: 7.22.4
- Nova Version: 3.7.1
- PHP Version: 7.4.7
- Database Driver & Version: MySQL 8.0.19
- Operating System and Version: macOS 10.15.3
- Browser type and version: N/A

### Description:
When adding a `BelongsTo` field, the options are always ordered alphabetically, and there are no options to rearrange them. It also doesn't respect any ordering defined on the model's relationship.

It's this line of code that is doing the ordering: https://github.com/laravel/nova/blob/3.0/src/Http/Controllers/AssociatableController.php#L34

Is it possible to add something like `->preordered()` so that any default ordering can be respected, or a simple `->orderBy('column')` option?

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
This has been fixed in [v3.26.0](https://nova.laravel.com/releases/3.26.0)

```php
BelongsTo::make('User')->dontReorderAssociatables(),
```
