### ISSUE TITLE
Internal server error alert

### ISSUE THREAD

**Issue by rehamwalid** [laravel/nova-issues#2772]
- Laravel Version:6.15
- Nova Version: 2.10.1
- PHP Version: 7.3

I added an action(Export Products)  to export all products but the action takes time so i created a job so that when  i run the action it calls the job and export the data in the background , it works fine and all data are exported but for some reason an **internal server error** alert appears although the job ran successfully  

any idea why this happen or if there is way to hide this alert  

Thank you

**Comment by jbrooksuk** [comment]
This issue board is for tracking bugs, not general development questions. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](https://larachat.co/).
