### ISSUE TITLE
Model name is being parsed for translation but returns content of translation file as array instead of translation

### ISSUE THREAD

**Issue by k2idev** [laravel/nova-issues#2774]
- Laravel Version: 7.22.4
- Nova Version: 3.8.2
- PHP Version: 7.4.8
- Database Driver & Version: 
- Operating System and Version: macOS 10.15.6
- Browser type and version: Safari
- Reproduction Repository: https://github.com/###/###

### Description:
I upgraded from Nova 3.7.1 to 3.8.2 and now Nova is unable to show the dashboard 

because "htmlspecialchars() expects parameter 1 to be string, array given"

in vendor/laravel/nova/resources/views/resources/navigation.blade.php

### My understanding of the issue

I have a Model name 'Module'
It is registered in Nova as  public static $model = 'App\Module';

When I open the dashboard in Nova an error occurs.

The error occurs in this line in `navigation.blade.php` (line 24)
 `{{ $resource::label() }}`

What seems to be happening is that `label()` tries to translate the name of the model with `__('Modules')`
The helper function `__()` does this: `return app('translator')->get($key, $replace, $locale);` and tries to get the translation.

In `ressources/lang/en` I have a file called `modules.php`

```php
<?php

return [
    /* English */

    'overview' => 'Overview of Learning Units',
    'content' => 'Content',
    'selfAssessment' => 'Self Assessment',
];
```

Now the problem is that `app('translator')->get($key, $replace, $locale)` **returns the content of this file and not the translation**.

This breaks navigation.blade.php with the "expected string but got array" because `app('translator')->get(..)` returns 
```php
  Array
    (
       [overview] => Overview of Learning Units
       [content] => Content
       [selfAssessment] => Self Assessment
    )
```

instead of `'Modules'`

* I can work around this by defining `public static function label()` in Nova/Module.php 
* I can also work around the error by renaming `ressources/lang/en/modules.php` 

But it seems that this is bug(?) and should not happen - and it works fine in v 3.7.1

PS: Sorry if there are any formal mistakes in reporting this issue (it's the first time I am doing this :))

**Comment by davidhemphill** [comment]
Nova’s translation system is designed to be used with Laravel’s JSON translations, not the array based ones.

**Comment by k2idev** [comment]
Ok - but then why does it work in 3.7.1 and stops working in 3.8.2 ?
Also
