### ISSUE TITLE
Unable to unit test nova after configuring nova guard

### ISSUE THREAD

**Issue by ahinkle** [laravel/nova-issues#2776]
- Laravel Version: 7.22.4
- Nova Version: 3.8.2
- PHP Version: 7.4.7
- Database Driver & Version: MySQL 5.7
- Operating System and Version: MacOS Catalina
- Browser type and version: N/A
- Reproduction Repository: N/A

### Description:
When changing the nova guard configuration (`NOVA_GUARD`) the nova tests returns an unauthenticated redirect (302) although there is nothing wrong on the frontend and I'm able to authenticate with the new guard as intended. I checked my config and added a `NOVA_GUARD` PHP unit config setting. I'm unable to write any php unit tests as the nova guard doesn't pass the `\Laravel\Nova\Http\Middleware\Authenticate` middleware when running from the console.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Replicate the default Laravel users table, migration, factory, model and name it `admin`.

Config/auth.php - add a custom provider:
```php
'providers' => [
        ....

        'admins' => [
            'driver' => 'eloquent',
            'model' => \App\Admin::class,
        ],
    ],
```

Config/auth.php - register the guard:
```php
    'guards' => [
        ...
        'admin' => [
            'driver' => 'session',
            'provider' => 'admins',
        ],
    ],
```

Add the guard to `.env`and`phpunit.xml`:
`.env`:
```
NOVA_GUARD=admin
```

`phpunit.xml`:
```
<server name="NOVA_GUARD" value="admin" />
```

Test:
```php
    public function test_authorized_user_has_access()
    {
        $this->actingAs(factory(\App\Admin::class)->create());
        
        $this->get('/nova-api/users/1')
            ->assertStatus(200); // fails and returns 302 redirect, unauth
    }
```

I want to continue to note, I can log in on the actual application and it's working as intended. I just simply can't write any tests for nova as they are all returning authorized.

My middleware hasn't changed from the default nova values - there is no other customization on this app other than adding the guard above.
config/nova.php:
```php
    'middleware' => [
        'web',
        Authenticate::class,
        DispatchServingNovaEvent::class,
        BootTools::class,
        Authorize::class,
    ],
```

**Comment by ahinkle** [comment]
Just needed to specify the driver. ha rookie mistake.

`$this->actingAs(factory(\App\Admin::class)->create(), 'admin');`

**Comment by maloun96** [comment]
I'm getting similar problem. Now I have 404 error.

```php
$this->actingAs(factory(\App\Admin::class)->create(), 'web')
    ->getJson('/nova-api/users')
    ->dd();
```
But in routes I have nova-api
<img width="1486" alt="image" src="https://user-images.githubusercontent.com/8277264/195319778-42e63aa1-6cb6-422d-8001-668a244b1bda.png">
