### ISSUE TITLE
Boolean Label on Stacked Field

### ISSUE THREAD

**Issue by flakerimi** [laravel/nova-issues#2777]
I want to group some checkboxes together:
```
 Stack::make('Details', [
                Boolean::make('stacked'),
                Boolean::make('adr'),
                Boolean::make('frigo'),
                Boolean::make('fragile'),
            ]),         
```

but it shows without boolean Labels 

<img width="91" alt="Screenshot 2020-08-01 at 15 37 25" src="https://user-images.githubusercontent.com/871482/89102815-e8e15900-d40c-11ea-81c1-bd969edcd2eb.png">

How to make them With label so I know which one is checked. I have many columns and I need to group them together so I have less horizontal scroll.

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by flakerimi** [comment]
Thats one way to close issues, but this is bug not request, since there is no way to do it. Anyways.

**Comment by emjayess** [comment]
Nor does `trueValue()` or `falseValue()` work in this stacked context

```php
    Boolean::make('bool', fn() => false)
        ->trueValue('yep')
        ->falseValue('nope')
    ,
```

**Comment by amg1114** [comment]
Could someone fix the problem?
