### ISSUE TITLE
Places & searchable Country field

### ISSUE THREAD

**Issue by Mopsit** [laravel/nova-issues#2779]
- Laravel Version: 7.22.4
- Nova Version: 3.8.2

If you have a Places field and a Country field with the searchable() attached, it wont get filled properly, when you select an address from the Places field. I don't know if this is just the behaviour it's supposed to have and that it's not supposed to work with searchable(), but it would be a nicer if it would still work.

**Comment by davidhemphill** [comment]
The places field is designed to only work with `Text` fields.
