### ISSUE TITLE
Empty filter dropdown on SoftDeletes and withoutTrashed()

### ISSUE THREAD

**Issue by rasmuscnielsen** [laravel/nova-issues#2781]
- Laravel Version: 7.18.0
- Nova Version: 3.8.2
- PHP Version: 7.4

### Description:

When having a HasMany relation to a model that SoftDeletes with the `withoutTrashed()` argument it displays an empty filter dropdown.

![Screenshot 2020-08-04 at 13 25 39](https://user-images.githubusercontent.com/8465957/89289163-0efa3980-d657-11ea-8ace-d63a9e543319.png)

I believe the issue occurs as a result of the following if-statements in `FilterMenu.vue`:

FilterMenu.vue:2
```
  <dropdown
    v-if="filters.length > 0 || softDeletes || !viaResource"
    dusk="filter-selector"
  >
```

and 

FilterMenu.vue:44
```
<!-- Soft Deletes -->
<div v-if="softDeletes && showTrashedOption">
```

**Suggested solution:**

FilterMenu.vue:2
```
  <dropdown
    v-if="filters.length > 0 || (softDeletes && showTrashedOption) || !viaResource"
    dusk="filter-selector"
  >
```

### Detailed steps to reproduce the issue on a fresh Nova installation:

Create a model+ nova resource ie. "User".

Create a HasMany relation ie. "Servers" that SoftDeletes  and apply the `withoutTrashed` option on the field configuration.

Now there should be a filter button with no items.

**Comment by nickshontz-ych** [comment]
@davidhemphill any thoughts on this?

**Comment by preliot** [comment]
I'm seeing very similar behaviour, but with different code:

```php
Fields\HasOne::make('Customer shop',  'shop', Shop::class);
```

I have only one filter (trashed) available. First the filter works as expected. When i try to filter on trashed only, i get the same result:

![image](https://user-images.githubusercontent.com/5418196/92585110-d15f8080-f294-11ea-8fc0-425c5c411abe.png)

HTML output:

```html
<div class="select-none overflow-hidden bg-white border border-60 shadow rounded-lg" direction="rtl" dark="true" style="width: 290px;">
<div class="scroll-wrap overflow-x-hidden overflow-y-auto" style="max-height: 350px;">
<!---->  
<!----> 
<!---->
</div>
</div>
```

**Comment by temp1029** [comment]
Also seeing this in Nova 3.9.1 and Laravel 7.28.1.

If I remove the 'SoftDeletes' the filter icon and dropdown go away. I don't remember if filtering on hasMany relationships was possible before in Nova.

**Comment by preliot** [comment]
> I'm seeing very similar behaviour, but with different code:
> 
> ```
> Fields\HasOne::make('Customer shop',  'shop', Shop::class);
> ```
> 
> I have only one filter (trashed) available. First the filter works as expected. When i try to filter on trashed only, i get the same result:
> 
> ![image](https://user-images.githubusercontent.com/5418196/92585110-d15f8080-f294-11ea-8fc0-425c5c411abe.png)
> 
> HTML output:
> 
> ```
> <div class="select-none overflow-hidden bg-white border border-60 shadow rounded-lg" direction="rtl" dark="true" style="width: 290px;">
> <div class="scroll-wrap overflow-x-hidden overflow-y-auto" style="max-height: 350px;">
>   
>  
> 
> </div>
> </div>
> ```

My issue is gone in nova 3.13.0.

**Comment by crynobone** [comment]
Unable to recreate the issue on latest Laravel Nova.

**Comment by preliot** [comment]
Recently there was a fix for trashed filter not appearing; i think that fix also fixed this one.
