### ISSUE TITLE
Resource label gets array when project has translation with similar model name

### ISSUE THREAD

**Issue by zetrider** [laravel/nova-issues#2786]
- Laravel Version: 7.24.0
- Nova Version: 3.3.0
- PHP Version: 7.4.8

### Description:
For example there is model Book, and translation file /resources/lang/en/book.php
My \App\Nova\Book class doesn't have method label.

Method Laravel\Nova\Resource::label tries to get name by code:
`return __(Str::plural(Str::title(Str::snake(class_basename(get_called_class()), ' '))));`

After that we have problem: 

> htmlspecialchars() expects parameter 1 to be string, array given .../vendor/laravel/nova/resources/views/resources/navigation.blade.php

### Temporary solution
Redefine method label in App\Nova\Resource
`use Illuminate\Support\Str;`

`    /**
     * Get the displayable label of the resource.
     *
     * @return string
     */
    public static function label()
    {
        return Str::plural(Str::title(Str::snake(class_basename(get_called_class()), ' ')));
    }`

**Comment by ntsbstn** [comment]
I can confirm the issue.

**Comment by vilhelmjosander** [comment]
I can confirm as well. The temporary solution does the trick for now.

**Comment by davidhemphill** [comment]
Nova's translations use Laravel's JSON file functionality. Switch the translation to use JSON. 👍
