### ISSUE TITLE
Searchable option from BelongsTo is attempting to download the whole database

### ISSUE THREAD

**Issue by milewski** [laravel/nova-issues#2787]
- Laravel Version: 7.*
- Nova Version: 3.8.2

### Description:

When using the BelongsTo with ->searchable() option it causes memory limit error or returns way too many results 

```php
 BelongsTo::make('Client')->searchable()
```

If the client table has let's say 100k records if you input a single character like `1` it causes the server to attempt to retrieve all the records that match the search param... which in certain cases is everything...

![image](https://user-images.githubusercontent.com/2874967/89759185-2a17ee00-db1c-11ea-8981-f2f02472c0bb.png)

ideally should be more options to the searchable functionality to limit the number of results retrieved or even to set minimum characters to be input before it performs the search..

I sugest something like this:

```php
 BelongsTo::make('Client')->searchable([ 'limit' => 10, 'minInput' => 3 ])
```

**Comment by indigoram89** [comment]
+1

**Comment by HRR1337** [comment]
+1

**Comment by davidhemphill** [comment]
You can limit the returned results by using Relatable Filtering: [https://nova.laravel.com/docs/3.0/resources/authorization.html#relatable-filtering](https://nova.laravel.com/docs/3.0/resources/authorization.html#relatable-filtering)
