### ISSUE TITLE
Create button and attach form for Belongstomany relationship

### ISSUE THREAD

**Issue by thiname** [laravel/nova-issues#2788]
Hi there !
I'm searching a fix for our Nova App. I have a relationship belongstomany between Minute and Stakeholder in which I have a pivot.
I would love to have attach or create  belongstomany relationship as shown in my screenshots :
1. A searching field to attach stakeholders to my minute
![attach-stakeholder](https://user-images.githubusercontent.com/33346555/89789298-b0363380-db20-11ea-8518-f41a58b63e2a.jpg)
2. A create button to create new stakeholder with a modal window
![create-stakeholder](https://user-images.githubusercontent.com/33346555/89789306-b1fff700-db20-11ea-8b08-e3295ec6a7ef.jpg)
As we have for for one level deep relationship (belongsto)
We already found this following resources but they are not satisfaying for our users :
https://github.com/dillingham/nova-attach-many (because we have to many resources to list and we can only attach not create)
https://novapackages.com/packages/yassi/nova-nested-form (we can only create not attach)
https://novapackages.com/packages/benjacho/belongs-to-many-field (we can only attach)
Can someone help me about other available resources to do this or who already developped it ?

**Comment by osteel** [comment]
@davidhemphill hi, any plan to implement this? Seems like a fairly common use case. Would be even better if we could include pivot data on that creation form too

**Comment by ThaDaVos** [comment]
I am looking for the same solution but I remember something that calling `->create()` on a belongsToMany field in Laravel itself was also broken in versions 5.8/6 - it wasn't setting the id's - maybe that's the reason it's not supported?

**Comment by 0528Makoto** [comment]
1+

**Comment by enricv** [comment]
+1

**Comment by RobinMoretti** [comment]
+1

**Comment by molbal** [comment]
+1

**Comment by hassan-knopsmedia** [comment]
+1
