### ISSUE TITLE
Decimals in Currency field with asMinorUnits

### ISSUE THREAD

**Issue by Nyratas** [laravel/nova-issues#2789]
- Laravel Version: 7.23.2
- Nova Version: 3.8.2
- PHP Version: 7.4.5

### Description:

When using `asMinorUnits`, one would expect the value to be stored as minor units and displayed in major units. In my experience, the `asMinorUnits()` option sets the Number field's `step` to `1.0`, which means the user has to enter minor units (and that's not user friendly at all). When changing the `step()` manually, values still get rounded, which confirms that the currency value is exposed in minor units to user.

I guess my point is : when using minor units in the database, Nova should translate this value into major units so it is easier to use for a common human. The edited value should then be translated back into minor units for storage.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Create model & migration with:

```php
...
$table->integer('price');
...
```

Create a resource with:

```php
Currency::make('Displayed price', 'price')
    ->currency('EUR')
    ->asMinorUnits();
```

Then try to save `€ 125,48`.

I would expect Nova to store `12548`, but it stores `125`.

When entering `€ 12`, I would expect Nova to store `1200`.
When entering `€ 125,489`, I would expect Nova to store `12549`.

Thank you! :)

**Comment by madsem** [comment]
But the resource isn't responsible for saving the data, mainly for displaying.
I think this should still happen on the model level, i.e through accessors/mutators and custom casts?

For example I am using `Brick/Money` in my project outside of Nova, if Nova now automatically does all this, it could mess things up.

**Comment by Nyratas** [comment]
Well, even if that's technically true, that's not really the issue here.

My point was that the field is filling the resource's model with the wrong value while using `asMinorUnits()`. It is getting rid of the provided decimals before it even hits the model, meaning that your accessor method would handle the wrong value even if the provided value is translated into minor units on the model's level:

1. User enters `€ 125,48` in the `Currency` field
2. The field fills the resource's model with `125`
3. The model's accessor transforms this value into `12500`
4. We're `48` cents short.

I agree we could (and probably should) cast or mutate the attribute on the model level. However, what's the point of a `asMinorUnits` method when it actually behaves as the same default "major units" configuration, minus the decimals?

**Comment by madsem** [comment]
I see, misunderstood that part ;)
The issue is the comma I believe.

Brick/Money under the hood works with dot as separator. Not sure this relates to Nova tbh.

**Comment by Nyratas** [comment]
No worries :)

About the decimals : 
- `asMinorUnits` sets the `step` to `1.0` which does not allow decimal values since it triggers a browser validation error (similar to "Please provide an integer")
- When manually changing the step to `0.01` and using `.` as decimal separator (instead of a comma), an exception is thrown (`brick/math/src/Exception/RoundingNecessaryException`: Rounding is necessary to represent the result of the operation at this scale.)
- Same result when using a comma as decimal separator.
