### ISSUE TITLE
Text field display case shortcuts

### ISSUE THREAD

**Issue by jameslkingsley** [laravel/nova-issues#279]
Would be neat if there were some display case shortcut methods on the `Text` field (and any other field where it applies). Quite often I find myself doing the following:

```php
Text::make('Driver')->displayUsing(function ($value) {
    return studly_case($value);
})
```

So some shortcuts would look something like:

```php
Text::make('Driver')->studlyCase()
// Or other cases
    ->camelCase()
    ->kebabCase()
    ->upperCase()
    ->lowerCase()
```

**Comment by davidhemphill** [comment]
No plans to add this to core, but I think this is a 3rd-party package on novapackages.com
