### ISSUE TITLE
Pivot action doesn't resolve models when using custom pivot attribute name

### ISSUE THREAD

**Issue by deshack** [laravel/nova-issues#2790]
- Laravel Version: 7.24.0
- Nova Version: 3.8.2
- PHP Version: 7.4.9
- Database Driver & Version: n/a
- Operating System and Version: n/a
- Browser type and version: n/a
- Reproduction Repository: n/a

### Description:

`ActionRequest::mapChunk()` doesn't take custom `pivot` attribute names into consideration.
Therefore, when resolving the resources on which to apply the action, it populates a collection of `null` values where pivot models should be returned.
This in turn resolves in a `Trying to access property <pivot foreign key> on a non-object` error in `ActionRequest::actionableKey()`, called by `ActionEvent`.

```php
protected function mapChunk($chunk)
    {
        return ActionModelCollection::make($this->isPivotAction()
                    ? $chunk->map->pivot // pivot should be `participation` in our example below
                    : $chunk);
    }
```

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Define two models related by a many-to-many relationship with pivot data and custom `pivot` attribute name.

First model:

```php
class Group extends Model {
  public function participants() {
        return $this->belongsToMany( User::class, 'group_user', 'group_id', 'user_id' )
                    ->as( 'participation' )
                    ->using( GroupParticipant::class )
                    ->withPivot( [ 'is_admin' ] )
                    ->withTimestamps();
    }
}
```

Second model:

```php
class User extends Model {
   public function groups() {
        return $this->belongsToMany( Group::class, 'group_user', 'user_id', 'group_id' )
                    ->as( 'participation' )
                    ->using( GroupParticipant::class )
                    ->withPivot( [ 'is_admin' ] )
                    ->withTimestamps();
    }
}
```

Pivot model:

```php
class GroupParticipant extends Pivot {
  protected $table = 'group_user';

    protected $casts = [
        'is_admin' => 'bool',
    ];
}
```

2. Define Nova resources with bi-directional relationship.

```php
class Group extends Resource {
// ...

  public function fields( Request $request ) {
    return [
      BelongsToMany::make( 'Participants', 'participants', User::class )->searchable()
                         ->fields( function () {
                             return [
                                 Boolean::make( 'Administrator', 'is_admin' ),
                             ];
                         } )
                         ->actions( function () {
                             return [
                                 new MyGroupParticipantAction()
                             ];
                         } ),
    ];
  }
// ...
}
```

```php
class User extends Resource {
// ...

  public function fields( Request $request ) {
    return [
      BelongsToMany::make( 'Groups', 'groups', Group::class )->searchable()
                         ->fields( function () {
                             return [
                                 Boolean::make( 'Amministratore', 'is_admin' ),
                             ];
                         } )
                         ->actions( function () {
                             return [
                                 new MyGroupParticipantAction()
                             ];
                         } ),
    ];
  }
// ...
}
```

Action is omitted since it doesn't really matter.

3. On the Group detail screen, select at least one related model and run the `MyGroupParticipantAction` action.
4. An error is thrown:

Trying to get property `'group_id'` of non-object {"userId":1,"exception":"[object] (ErrorException(code: 0): Trying to get property 'group_id' of non-object at /path/to/nova/src/Http/Requests/ActionRequest.php:189)

**Comment by deshack** [comment]
A solution could be the following:

```php
protected function mapChunk( $chunk ) {
        return ActionModelCollection::make( $this->isPivotAction()
            ? $chunk->map->{$this->pivotRelation()->getPivotAccessor()}
            : $chunk );
    }
```

Given that `ActionRequest::pivotRelation()` returns a `BelongsToMany` relation.

**Comment by benlumley** [comment]
I am seeing this issue; and the suggested fix above fixes it.

**Comment by crynobone** [comment]
Laravel Nova does come with dusk tests covering pivot action with fields on BelongsToMany relationship and it's returning green. At this point please create a full reproducing code to demonstrate the issue in case there a use case that we have yet to discover.

**Comment by Evanslooten** [comment]
I ran into this issue in my current project with Nova. The proposed solution did correct the issue with the action on the pivot. I'd be happy to provide whatever information you need to identify the issue.

**Comment by crynobone** [comment]
@Evanslooten submit new bug report using the available template.
