### ISSUE TITLE
Cannot hover over the help icon on trend metrics

### ISSUE THREAD

**Issue by milewski** [laravel/nova-issues#2791]
- Laravel Version: 7.*
- Nova Version: 3.8.2

![image](https://user-images.githubusercontent.com/2874967/90001696-57070500-dcc4-11ea-8f24-bf245dd29632.png)

Clicking or Hovering on this doesn't work as the chart itself is on top of the help icon

**Comment by xoco70** [comment]
same with laravel 8

**Comment by preliot** [comment]
Same with nova 3.13.0.

**Comment by crynobone** [comment]
Closing this in favour of #2996
