### ISSUE TITLE
Stored boolean field values ignored in pivot table for many-to-many relationship (view and edit), but not when same pivot model/table is loaded as own resource

### ISSUE THREAD

**Issue by jonnott** [laravel/nova-issues#2792]
- Laravel Version: 7.22.4
- Nova Version: 3.8.2
- PHP Version: 7.3
- Database Driver & Version: MySQL 5.7

### Description:

Pivot table for Organisation/User relationship (users, organisations, organisation_user tables) has booleans `is_admin` and `is_leader`, and even though these are set as 1 in the existing db entries, they show as red crosses in pivot relationship view in Nova detail view , and un-ticked checkboxes on the form. However, if you tick the checkboxes, the 1 values are stored back to the db correctly.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Database
```
CREATE TABLE `organisation_user` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `organisation_id` bigint(20) unsigned NOT NULL,
  `user_id` bigint(20) unsigned NOT NULL,
  `is_admin` tinyint(1) NOT NULL DEFAULT '0',
  `is_leader` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `organisation_user_organisation_id_user_id_unique` (`organisation_id`,`user_id`)
) 
```

User model
```
	public function organisations()
	{
		return $this->belongsToMany(Organisation::class)
			->using(OrganisationUser::class)
			->withTimestamps();
	}
```

Organisation model
```
	public function users()
	{
		return $this->belongsToMany(User::class)
			->using(OrganisationUser::class)
			->withTimestamps();
	}
```

OrganisationUser pivot model
```
use Illuminate\Database\Eloquent\Relations\Pivot;

class OrganisationUser extends Pivot
{
	public $incrementing = true;

	public $casts = [
		'is_admin' => 'bool',
		'is_leader' => 'bool',
	];
}
```

Nova User resource
```
	public function fields(Request $request)
	{
		return [
			ID::make()->sortable(),

			Gravatar::make()->maxWidth(50),

			Text::make('Name')
				->sortable()
				->rules('required', 'max:255'),

			Text::make('Email')
				->sortable()
				->rules('required', 'email', 'max:254')
				->creationRules('unique:users,email')
				->updateRules('unique:users,email,{{resourceId}}'),

			Password::make('Password')
				->onlyOnForms()
				->creationRules('required', 'string', 'min:8')
				->updateRules('nullable', 'string', 'min:8'),

			BelongsToMany::make('Organisations')->fields(new OrganisationUserFields),
		];
	}
```

Nova Organisation resource
```
	public function fields(Request $request)
	{
		return [
			ID::make(__('ID'), 'id')->sortable(),

			Text::make('Name')
				->sortable()
				->rules('required', 'max:255'),

			BelongsToMany::make('Users')->fields(new OrganisationUserFields),
		];
	}
```

OrganisationUserFields
```
<?php

namespace App\Nova;

use Laravel\Nova\Fields\Boolean;

class OrganisationUserFields
{
	/**
	 * Get the pivot fields for the relationship.
	 *
	 * @return array
	 */
	public function __invoke()
	{
		return [
			Boolean::make('Is Admin?', 'is_admin'),
			Boolean::make('Is Leader?', 'is_leader'),
		];
	}
}
```

Things that appear to make no difference to the problem:
- whether `is_admin` and `is_leader` are cast to 'bool' or 'boolean' in the OrganisationUser pivot model's $casts attribute, or not
- whether the `is_admin` and `is_leader` fields are nullable() or not in the database
- whether or not the belongsToMany() relationship definition methods in the User or Organisation models call `using(OrganisationUser::class)`
- whether or not I declare the boolean pivot field as `Boolean::make('Is Admin?', 'is_admin')` or `Boolean::make('Is Admin')`

**Comment by jonnott** [comment]
But if I make a Nova resource for OrganisationUser directly..

```
    public function fields(Request $request)
    {
        return [
            ID::make(__('ID'), 'id')->sortable(),
			Boolean::make('is_admin'),
			Boolean::make('is_leader'),
        ];
    }
```

.. then the existing stored boolean fields for `is_admin` and `is_leader` show correctly as green tick icons and checked checkboxes in view / forms respectively, as expected.

**Comment by davidhemphill** [comment]
I believe you need to specify the `withPivot` method on the relationship methods.

**Comment by jonnott** [comment]
> I believe you need to specify the `withPivot` method on the relationship methods.

@davidhemphill And that alone will fix Nova picking up the values correctly?
