### ISSUE TITLE
Query metrics 

### ISSUE THREAD

**Issue by Payetus** [laravel/nova-issues#2794]
I would like to be able to query models in metrics.  For example I have a Value Metric , that counts the number of posts:

` public function calculate(Request $request)
    {
        return $this->count($request,  Post::class);
    }`

But I would like to count only published Post  something like:

` public function calculate(Request $request)
    {
        return $this->count($request,  Post::class)->where('published', true);
    }`

**Comment by davidhemphill** [comment]
You can simply query the DB and return the value using the `result` method:

```php
$count = Post::where('published', true)->count();
$this->result($count);
```
