### ISSUE TITLE
"Attach & Attach Another" does not entirely reset the form

### ISSUE THREAD

**Issue by gaelreyrol** [laravel/nova-issues#2797]
- Laravel Version: 7.25.0
- Nova Version: 3.8.2
- PHP Version: 7.4

### Description:

When I attach a resource to another resource using the "Attach & Attach Another" option. It saves the relationship correctly, but the select field will have the option for the resource that I just attached still selected.

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Create a resource A with an association of resource B
2. Create 1 A resource record and Create 2 B resource records
3. "Attach & Attach Another" B resource record to A resource

This issue has the same behavior as #1244

### Diagnostic

In `https://github.com/laravel/nova/blob/3.0/resources/js/views/Attach.vue`:

It seems that when the function `attachAndAttachAnother` is called, the `selectedResourceId` is not reset in the function `initializeComponent` so when the router re-render the page, the function `getAvailableResources` still has the old `selectedResource` in the state.

**Comment by ryangjchandler** [comment]
Can confirm that I'm having this problem too.

**Comment by davidhemphill** [comment]
Sure!
