### ISSUE TITLE
Date::make('date')->required() is not validating anything, and not resolving date name for error message when using workaround

### ISSUE THREAD

**Issue by xoco70** [laravel/nova-issues#2799]
- Laravel Version: 7
- Nova Version: 3.8.2
- PHP Version: 7.4
- Database Driver & Version: Postgres
- Operating System and Version: Ubuntu 20.04
- Browser type and version: Chrome

### Description:

When trying to add `->require()` to a date field, validation is not happening, I have to use : `->rules('required')` and validation will give me the red message if letting date empty

### Detailed steps to reproduce the issue on a fresh Nova installation:

            Date::make('Start', 'date_start')->required(), // Failing when submitting post, will not validate this

            Date::make('Start', 'date_start')->rules('required'), // This one works

It will also not resolve the field name, and will take the field name for the message:

`Le champ date start est obligatoire.` instead of `Le champ Start est obligatoire.`

**Comment by xoco70** [comment]
It also happens in Select fields...

**Comment by xoco70** [comment]
![Screenshot from 2020-08-14 17-29-18](https://user-images.githubusercontent.com/5855577/90266104-cfe89700-de53-11ea-8a46-49cdee631303.png)

It seems the field is managed different from others, there is no red line

**Comment by davidhemphill** [comment]
You still have to specify validation rules. `required` only marks the field visually as required and is usually not required if you've specified validation rules.
