### ISSUE TITLE
[Feature] HTML Field

### ISSUE THREAD

**Issue by SeoFood** [laravel/nova-issues#280]
A field type where you can return your own html so you can display images, links, status labels with your color etc.

```php
HTML::make('Custom HTML', function() {
    return '<strong>' . $this->status . '</strong>';
})
```

**Comment by albalooshi** [comment]
I haven't tired this but I think this is achievable (for now until this feature to be implemented) by creating a [custom field](https://nova.laravel.com/docs/1.0/customization/fields.html#building-fields)

**Comment by SeoFood** [comment]
yeah its possible but I don't want to create custom fields for just simple fields.

**Comment by treeStoneIT** [comment]
I have made a custom HTML field for anyone that needs: https://github.com/treeStoneIT/nova-html

**Comment by laraning** [comment]
Your solution is the best David, since it will give us full flexibility to render any HTML we want via a view :) happy to see it on the next Nova version 👍🏻

**Comment by RicardoRamirezR** [comment]
Version 1.0.9 has this covered
```
Text::make('Title')->asHtml()
```
