### ISSUE TITLE
404 on Show of certain resources. Javascript: Cannot read property 'searchable' of undefined

### ISSUE THREAD

**Issue by asdf072** [laravel/nova-issues#2800]
- Laravel Version: 7.25.0
- Nova Version: 3
- PHP Version: 7.4.8
- Database Driver & Version: MySql
- Operating System and Version: Ubuntu 18.04.4
- Browser type and version: Chrome 84

### Description:
When going to a Show route/action of certain resources, the browser flashes a fully rendered screen, then immediately redirects to the 404 page. No log errors anywhere. The only clue I have is the javascript error:
```
TypeError: Cannot read property 'searchable' of undefined
    at a.render (app.js?id=e9f0a1a2c2c4761dd5f0:1)
    at a.t._render (vendor.js?id=f9725df909a5af18907e:1)
    at a.hn.before (vendor.js?id=f9725df909a5af18907e:1)
    at hn.get (vendor.js?id=f9725df909a5af18907e:1)
    at new hn (vendor.js?id=f9725df909a5af18907e:1)
    at vendor.js?id=f9725df909a5af18907e:1
    at a.wn.$mount (vendor.js?id=f9725df909a5af18907e:1)
    at a.wn.$mount (vendor.js?id=f9725df909a5af18907e:1)
    at init (vendor.js?id=f9725df909a5af18907e:1)
    at vendor.js?id=f9725df909a5af18907e:1
```

**EDIT/SOLUTION** I misunderstood "registering" a resource. I simply wanted to hide some resources in the left menu. Manually registering resources accomplishes that, but made the others completely unavailable for relationships. Summary: I need to go back to `public static $displayInNavigation = false;`

**Comment by indigoram89** [comment]
I have the same right how.

The problem when I add HasMany::make('Accounts') in the nova/user resource.

I think about it for an hour but I do not understand the reason.

**Comment by indigoram89** [comment]
I understood =) I do not add the nova/account resource in the NovaServiceProvider.

Nova::resources([
    \App\Nova\User::class,
    \App\Nova\Account::class,
])

**Comment by asdf072** [comment]
I tried getting rid of manually registered resources, and now it works fine. (Commenting out the entire NovaServiceProvider::resources() method.) I'll have to look at the docs again, but certainly seems like something is broken.

Here's what I had in the service provider:

```
    // use App\Nova as AN;

    public function resources()
    {
      Nova::resources([
        AN\Customer::class,
        AN\Community::class,
        AN\CmVendor::class,
        AN\Crew::class,
        AN\Supplier::class,
        AN\JobTemplate::class,
        AN\User::class,
      ]);
    }
```
