### ISSUE TITLE
TransformUsing method on fields

### ISSUE THREAD

**Issue by Marko298** [laravel/nova-issues#2802]
Is it possible to add something like `transformUsing` method that will be called in `fillAttributeFromRequest` before inserting value into model?

### Example

Before
```php
$model->{$attribute} = $this->isNullValue($value) ? null : $value;
```

After
```php
$value =  $this->isNullValue($value) ? null : $value;

$model->{$attribute} = call_user_func($this->transformCallback, $value)
```

It will reduce complexity of cases when you just want to modify value a bit before passing to model

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
