### ISSUE TITLE
Stacked fields with labels

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#2809]
I would like the possibility to show field names next to the stacked fields. Or a custom prefix / suffix would also be great.

Right now i have a stack of payd by currency fields, but the labels are missing. I've tried the displayUsing() route, but then the part that formats goes out the window.

```php
 ->displayUsing(static function ($value) {
                return __('lense.paydPSP') . ': ' . $value;
            })

//this does what i want, but without money formatting
```
Also see issue #2777

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by preliot** [comment]
Temp fix for anyone interested:

1. Create custom currency field
2. Create vars, override constructor and add few methods. Now you can you the correct formatting with a prefix / suffix.

```php

  /*
     * Prefix for currency
     *
     * @var string
     */
    public $prefix = null;

    /*
     * Suffix for currency
     *
     * @var string
     */
    public $suffix = null;

 /**
     * Create a new field.
     *
     * @param  string  $name
     * @param  string|null  $attribute
     * @param  mixed|null  $resolveCallback
     * @return void
     */
    public function __construct($name, $attribute = null, $resolveCallback = null)
    {
        parent::__construct($name, $attribute, $resolveCallback);

       //override displayUsing from parent
 $this->displayUsing(function ($value) {
            return ! $this->isNullValue($value) ? $this->prefix . $this->formatMoney($value) . $this->suffix : null;
        });
}

  public function prefix($prefix)
    {
        $this->prefix = $prefix;
        return $this;
    }

    public function suffix($suffix)
    {
        $this->suffix = $suffix;
        return $this;
    }
```
