### ISSUE TITLE
Feature: Custom ActionEvent Model

### ISSUE THREAD

**Issue by howlowck** [laravel/nova-issues#281]
**Nova Version:** 1.0.6

**Problem**: I cannot extend the `Laravel\Nova\Actions\ActionEvent` model for Nova to utilize.  The goal is to overwrite a method on the `ActionEvent` model.

**Why**: I'm using `hyn/multi-tenant` package and would like to make the nova dashboard available per-tenant. I need a way to either add a trait or overwrite the `getConnectionName` method.  Either way I'd need a way to extend the original ActionEvent model.

**Proposed Solution**: Add a new property in the `nova` configuration called "models" and the value like below:
```php
'models' => [
    'action_event' => App\ActionEvent::class
],
``` 

then utilize the value of the configuration to instantiate the ActionEvent model in nova.

**Other Solutions Considered**: 
* For those using `hyn/multi-tenant`, there is option to force the specific models to use `tenant` connection.  The package achieves this by using `forward_static_call` on `setConnectionResolver`, however that will not work because many times, connection can be set with `$fooModel->setConnection($barModel->getConnectionName())`.  And since `getConnectionName` is a instance method, there is no way to overwrite it without extending the class.

----
Comments and alternative solutions welcome.  Thank you!

**Comment by ibrunotome** [comment]
@taylorotwell @themsaid Please take a look in this feature to customise db connection of ActionEvent.

**Comment by waygou** [comment]
Hope it can be changed soon, since it is not allowing Hyn multi-tenant to be used ...

@howlowck, @ibrunotome did you guys found any other solutions?

**Comment by ibrunotome** [comment]
Not yet @waygou

**Comment by abclive** [comment]
@waygou Thank you so much, I can confirm this works!

Just so everything is in order you also need to copy the migration `2018_01_01_000000_create_action_events_table.php` from the laravel/nova vendor folder to the tenant migration sub directory and run `php artisan tenancy:migrate` to create the action_events table in the tenants databases.

**Comment by ibrunotome** [comment]
Sorry for the delay @waygou, but on my case I need to store only the action events on another database exclusively to audits, where I keep all my other audits (api logs, eloquent audits etc).

**Comment by waygou** [comment]
Well, on that case it's a new issue different from this one originally opened I think.

**Comment by alberto-bottarini** [comment]
Is there any news about this feature?

**Comment by maede-a** [comment]
@taylorotwell @themsaid any update?

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!

**Comment by howlowck** [comment]
☝️ ☝️ ☝️ ☝️ ☝️ 

I don't think that's how Github issues work. You just move this issue to a milestone then close it immediately without acknowledging the validity of the idea. This adds nothing to your feedback loop nor to the customer's confidence that their voice is heard.

**Comment by jbrooksuk** [comment]
@howlowck apologies, I've updated my comment text and flagged this as a feature request.

This is how we manage the Nova issues.

**Comment by marijoo** [comment]
Any news on this feature?

**Comment by davidhemphill** [comment]
Launched with https://nova.laravel.com/releases/2.9.4
