### ISSUE TITLE
Custom action doesn't update original/changes columns in the action_events table

### ISSUE THREAD

**Issue by jsheffers** [laravel/nova-issues#2810]
- Laravel Version: 7
- Nova Version: 3.8.2
- PHP Version: 7.3
- Database Driver & Version: MySQL
- Operating System and Version: Mac
- Browser type and version: Chrome 83

### Description:
Creating a custom action that updates a simple text field in a model does not keep track of original and changed values.  This works really well for the update method on a standard model, however, if you dispatch an action that updates a model it isn't able to determine what's changed.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Create a custom text field on any default model with a corresponding column.  Create an action in Nova and attach it to the resource detail page.  Have the action simply update the text field with custom data.  After verifying the model updated the text field successfully in the database go find the entry in the action_events table and you'll see the original and changes columns will be null.

It's possible this is not a bug and this is simply the intended behavior.  If so this can be closed and I can move it to a feature request.

Custom action `CallAction.php`:

```php
<?php
namespace App\Nova\Actions;
use Illuminate\Support\Collection;
use Illuminate\Queue\SerializesModels;
use Laravel\Nova\Fields\ActionFields;
use Laravel\Nova\Fields\Text;
use Laravel\Nova\Actions\Action;

class CallAction extends Action
{
    use SerializesModels;

    public $name = 'Update Active';

    public function fields()
    {
        return [];
    }

    public function handle(ActionFields $fields, Collection $calls)
    {
        $newText = $fields->text;
        // loop through items
        foreach ($calls as $call) {
            // set active
            $call['text'] = $newText;
            // commit changes
            $call->save();
        }
    }
}
```

After this action is completed for a specific row (model), the DB row looks like this:

<img width="1393" alt="Screen Shot 2020-08-20 at 2 36 37 PM" src="https://user-images.githubusercontent.com/656483/90811467-ab2c6d80-e2f2-11ea-8c09-b6cb4491f823.png">

The last two columns that show `null` are the original and changes columns in that table.  Shouldn't these be showing the original attributes and what's changed?

**Comment by anditsung** [comment]
$call->text = $newText;

And the fields is empty

**Comment by AEmad01** [comment]
You can use
`public $withoutActionEvents = true;` in your action then:
modify the forResourceUpdate function in ActionEvent to take an optional paramter $name
`public static function forResourceUpdate($user, $model,?String $name)`
then you can use 
`Nova::actionEvent()->forResourceUpdate(Auth::User(), $invoice,'Refund')->save();` to trigger the action. 
`'name' => $name?$name:'Update',` to save the action name taken as an input. 
Not the best solution but it works for now, do the same if your action is a destroy/create type.

**Comment by d3v4nt** [comment]
any news on this one? my custom action won't update original/changes columns as well
