### ISSUE TITLE
Customize search behaviour

### ISSUE THREAD

**Issue by jkudish** [laravel/nova-issues#2811]
Hey there!

The search on resource index pages seems to have a hardcoded debounce set to 500ms. In our use case we're finding the debounce to be a bit too short and it often submits before we're done typing.
I was wondering if it would be possible to make the debounce customizable via a PHP setting. Alternatively if there was an option to only submit searches with an enter keypress or submit button, that would also work.

**Comment by jkudish** [comment]
@jbrooksuk @davidhemphill thank you both for working on this. I'm glad the prop is being respected now but it unfortunately didn't address my question/request of being able to customize the debounce value of the index views search. It is still hardcoded in that component and I see no way to customize it.

What do you think of being able to customize it?

**Comment by jkudish** [comment]
Just saw https://github.com/laravel/nova/pull/942 🎉 awesome!

**Comment by jkudish** [comment]
Hey @davidhemphill I see that Nova 3.9 and added support for "Nova's search debounce is now user-configurable. #942" However, it still didn't address my question/request of being able to customize the debounce value of the _index view's_ search. It is still hardcoded in that component and I see no way to customize it.

What do you think of being able to customize it?

**Comment by davidhemphill** [comment]
Pushed a PR to address this. 👍

**Comment by alex-osborn** [comment]
This is great, thank you! Adjusting both resource debounce and the global search was an ongoing request from many of our customers (we want to drop the debounce down to provide a more responsive experience). Much appreciated.
