### ISSUE TITLE
ID Field coming up as empty on all the pages.

### ISSUE THREAD

**Issue by imrealashu** [laravel/nova-issues#2813]
- Laravel Version: v7.25.0
- Nova Version: v3.8.2
- PHP Version: PHP 7.3.13 (cli) (built: Dec 18 2019 16:08:06) ( NTS )
- Database Driver & Version: MySQL 8
- Operating System and Version: Mac OS Cataline (10.15.6)
- Browser type and version: Chrome

### Description:
The ID field coming up empty even if it's mentioned properly in the model. I was working fine but I'm not sure which change removed IDs from all the Model.  
```
public function fields(Request $request)
    {
        return [
            ID::make('ID', 'id')->sortable(),
            Text::make('Label')->required(),
            HasMany::make('Commission Slabs', 'commissionSlabs')
        ];
    }
```
I'm sure there's neither anything changed on the Nova Models nor on the App Models. Just to be exact I did try using other Nova fields such as `Text::make('ID')` and it seems to be working fine except the `ID` Nova Field. 

Checks
1. `id` is the primary key.
2. Checked `$model->getKeyName()` which was returning `id`

<img width="1155" alt="Screenshot 2020-08-23 at 04 00 19" src="https://user-images.githubusercontent.com/3916999/90966853-2bbabc00-e4f5-11ea-942c-2095d6255dda.png">

**Comment by iruoy** [comment]
Nah I've got the same issue in 3.8.4

- Laravel Version: 7.25.0
- Nova Version: 3.8.4
- PHP Version: PHP 7.4.9
- Database Driver & Version: MySQL 8
- Operating System and Version: macOS Catalina (10.15.6)
- Browser type and version: Firefox

**Comment by iruoy** [comment]
It's been a while since I've worked with Nova. Completely forgot about that. Thanks.

It's looking great now.
