### ISSUE TITLE
Vertical align content in table rows

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#2814]
Just wrote a lense with stacked fields to show order payment & VAT information. Would be nice if i could vertical align all fields (including icons) to top. Right now it looks like this:

![image](https://user-images.githubusercontent.com/5418196/91143793-58b4cd80-e6b3-11ea-89d6-bca46942ba98.png)

This is what i would like to be possible:

![image](https://user-images.githubusercontent.com/5418196/91143958-9b76a580-e6b3-11ea-95e5-c4b71e2ad0dc.png)

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
