### ISSUE TITLE
Add ability to add a new HasMany relationship record via Popup

### ISSUE THREAD

**Issue by romaldyminaya** [laravel/nova-issues#2815]
Hi,

Is there anyway possible to add a new HasMany relationship record via Popup? I'll relate the example.

If I have a resource (Car) that has many (Parts), each time I add a child part, I'm redirected to a new view in which I need to fill the data, save, and then go back to be able to see the Car again.

It would be nice to have the ability to tell the HasMany relationship field that when you clic the create or add button, the form is displayed in a popup, something like this:

```
    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [
            HasMany::make('Car parts', 'parts', 'App\Nova\Resources\CarParts')
                ->createViaPopup(),
        ];
    }
```

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by groax** [comment]
I really really want this... !! <3
