### ISSUE TITLE
Laravel Nova Field ->max() and Rule should reference user input value not database value

### ISSUE THREAD

**Issue by latwelve** [laravel/nova-issues#2816]
- Laravel Version: 7.x
- Nova Version: 3.8.3
- PHP Version: 7.4

When using Currency or Number the ->max() value is referencing already saved information on the model.. IE

Number::make('Price'),

Number::make('Discount')
->max($this->price),

Will reference a stored value from the database and not the newly inputted value of the field that has passed its own validation.

The same happens when creating a Rule and passing a variable new MinMaxDiscount($this->price);

Surely we want to return the latest value entered by the user in the form and not a database stored value? or have I missed something very obvious?

**Comment by dkulyk** [comment]
See https://laravel.com/docs/7.x/validation#rule-lte

**Comment by latwelve** [comment]
> See https://laravel.com/docs/7.x/validation#rule-lte

Not sure that helps, the max and rule should reference current input values not saved values?

**Comment by davidhemphill** [comment]
When calling `$this`, inside a `Resource`, if the method or property is not available on the `Resource`, it will delegate to the underlying `Model` instance (if one is available). There doesn't seem to be a bug here.

**Comment by latwelve** [comment]
@davidhemphill sorry just a quick question.. 
if I haven't understood incorrectly...

A Resource is previously saved. Both Price and Discount have a value.
On Edit / Update

The price and the discount field are changed.. then surely the validation should be checking the new values that are to be updated and not the stored values in the database?

Thanks
