### ISSUE TITLE
Relatable query does not provide mixins of scopes.

### ISSUE THREAD

**Issue by dkulyk** [laravel/nova-issues#2817]
- Laravel Version: 7.*
- Nova Version: 3.8.4
- PHP Version: 7.4
- Database Driver & Version: Mysql 5.7
- Operating System and Version: all
- Browser type and version: all

### Description:
BelongsTo::buildAssociatableQuery with `$request->first === 'true'` don't provide scopes for request `$model->newQueryWithoutScopes()->whereKey($request->current)`

### Detailed steps to reproduce the issue on a fresh Nova installation:

Add relatableQuery to resource with `->withTrashed()` for model with SoftDeletes.

When your model selected, throws error like `Method Builder::withTrashed` not found.
![image](https://user-images.githubusercontent.com/370042/91176146-86693900-e6ea-11ea-850a-8a5099a35907.png)

```php
    public static function relatableThreads(NovaRequest $request, $query): Builder
    {
        return $query->withTrashed();
    }
```

No need to use `\Laravel\Nova\Fields\BelongsTo::associatableQueryCallable` when first is 'true'

**Comment by davidhemphill** [comment]
Replied via the PR.
