### ISSUE TITLE
Currency / number: when editting trailing zero's disappear (part 2)

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#2818]
Laravel Version: 7.18
Nova Version: 3.8.4
PHP Version: 7.2.19
Operating System and Version: Windows 10
Browser type and version: Chrome 79 64-bits

**Description**:

When i edit a resource with a currency (or number with two decimals) i expect the decimal part to always show zero's. Instead i get this:

19,49
19,5
19,51

and also

19,99
20
20,01

**Steps To Reproduce:**

Use a Number (with two decimals) or Currency field
Edit resource
Observe trailing zero's

**Disclaimer**

This issue was posted earlier as https://github.com/laravel/nova-issues/issues/2373 and closed in https://github.com/laravel/nova/pull/818, but it did not fix my issue.

**Comment by preliot** [comment]
go away stale bot, ksssshh!

**Comment by preliot** [comment]
good boy!

**Comment by crynobone** [comment]
I don't think it's suitable to make a default for this but you should be able to do the following:

```php
Currency::make('Balance')
    ->fillUsing(function ($request, $model, $attribute) {
        $model->balance = round($request->{$attribute});
    }),
```
