### ISSUE TITLE
Form Labels adding "fff" behind actual value

### ISSUE THREAD

**Issue by marctich** [laravel/nova-issues#2819]
- Laravel Version: 7.26.0
- Nova Version: 3.8.4
- PHP Version: 7.4
- Database Driver & Version: mysql / 8.0.20
- Operating System and Version: #.#
- Browser type and version: Edge + Chrome

### Description:
For some odd reason, since updating to 3.8.4, my form-labels (and only those), are all display "fff" behind them.

### Detailed steps to reproduce the issue on a fresh Nova installation:
No clue, don't have a fresh installation, just upgrade nova and it occurred. The actual label values aren't containing "fff", see screenshots below.

![image](https://user-images.githubusercontent.com/1815234/91199222-e2898880-e6fd-11ea-9e9c-f0a91fb87027.png)
![image](https://user-images.githubusercontent.com/1815234/91199946-d05c1a00-e6fe-11ea-9e4c-8eb63a51a27d.png)
![image](https://user-images.githubusercontent.com/1815234/91200475-832c7800-e6ff-11ea-809b-62e2ded4cc1d.png)

**Comment by davidhemphill** [comment]
Sorry, but we are unable to debug your issue without a reproducible code example. When you're able to demonstrate the issue with an example, feel free to open a new issue.
