### ISSUE TITLE
Lens having currency field value throws exception when ordering

### ISSUE THREAD

**Issue by kosmonowt** [laravel/nova-issues#2821]
- Laravel Version: 7.26.1
- Nova Version: 3.8.4
- PHP Version: 7.4.7
- Database Driver & Version: mysql 5.7.26
- Operating System and Version: MacOS & Linux
- Browser type and version: Brave (latest stable)
- Reproduction Repository: https://github.com/###/###

### Description:
If I want to reorder a lens that has a currency field I receive the following error: `production.ERROR: The given value "" does not represent a valid number. {"userId":1,"exception":"[object] (Brick\\Math\\Exception\\NumberFormatException(code: 0): The given value \"\" does not represent a valid number. at /var/www/php-core/vendor/brick/math/src/BigNumber.php:75)`

### Detailed steps to reproduce the issue on a fresh Nova installation:

Create a Model `MyModel` with any attribute that could resolve to a currency, regardless if it has a representation in the database or if it is resolved through a function. In my case I am using the following:
```php
    public function getTotalPriceAttribute() : float {
        return 0; // just as an example. This function is not even called when throwing the error
    }
```

Create a Resource to that Model `MyModelResource`.

Connect a Lens to that Resource `MyModelSpecialLens`

```php
            Currency::make("mail_to_customer")->currency("EUR")->readonly()
            Text::make("count_tickets")->readonly()->sortable(),
            DateTime::make( "locked_at")->readonly()->sortable()
```

Call that lens through nova and try to order by __count_tickets__ or __locked_at__ you should see the error mentioned above.

Here's some more of the stack:

```
[2020-08-27 23:52:45] production.ERROR: The given value "" does not represent a valid number. {"userId":1,"exception":"[object] (Brick\\Math\\Exception\\NumberFormatException(code: 0): The given value \"\" does not represent a valid number. at /var/www/php-core/vendor/brick/math/src/BigNumber.php:75)
[stacktrace]
#0 /var/www/php-core/vendor/brick/money/src/Money.php(190): Brick\\Math\\BigNumber::of()
#1 /var/www/php-core/nova/src/Fields/Currency.php(106): Brick\\Money\\Money::of()
#2 /var/www/php-core/nova/src/Fields/Currency.php(120): Laravel\\Nova\\Fields\\Currency->toMoneyInstance()
#3 /var/www/php-core/nova/src/Fields/Currency.php(80): Laravel\\Nova\\Fields\\Currency->formatMoney()
#4 [internal function]: Laravel\\Nova\\Fields\\Currency->Laravel\\Nova\\Fields\\{closure}()
#5 /var/www/php-core/nova/src/Fields/Field.php(224): call_user_func()
#6 /var/www/php-core/vendor/laravel/framework/src/Illuminate/Support/helpers.php(433): Laravel\\Nova\\Fields\\Field->Laravel\\Nova\\Fields\\{closure}()
#7 /var/www/php-core/nova/src/Fields/Field.php(225): tap()
#8 /var/www/php-core/nova/src/Fields/FieldCollection.php(66): Laravel\\Nova\\Fields\\Field->resolveForDisplay()
#9 /var/www/php-core/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php(202): Laravel\\Nova\\Fields\\FieldCollection->Laravel\\Nova\\Fields\\{closure}()
#10 /var/www/php-core/nova/src/Fields/FieldCollection.php(68): Illuminate\\Support\\Collection->each()
#11 /var/www/php-core/nova/src/Lenses/Lens.php(136): Laravel\\Nova\\Fields\\FieldCollection->resolveForDisplay()
#12 /var/www/php-core/nova/src/Http/Requests/LensRequest.php(54): Laravel\\Nova\\Lenses\\Lens->resolveFields()
#13 /var/www/php-core/app/Nova/Lenses/OrdersWithTickets.php(42): Laravel\\Nova\\Http\\Requests\\LensRequest->withOrdering()
```
#13 refers to the following simple line in my Lens `$query->havingMailorderOffers();`: 
```php
    public static function query(LensRequest $request, $query)
    {
        return $request->withOrdering($request->withFilters(
            $query->havingMailorderOffers();
        ));
    }
```

Adding "nullable()" to the currency field will resolve the issue:

```php
            Currency::make("mail_to_customer")->currency("EUR")->readonly()->nullable()
            Text::make("count_tickets")->readonly()->sortable(),
            DateTime::make( "locked_at")->readonly()->sortable()
```

This is not really understandable for the average developer. We found out that it has to do with the function `Field::isNullValue()`

```php
    protected function isNullValue($value)
    {
        if (! $this->nullable) {
            return false;
        }

        return is_callable($this->nullValues)
            ? ($this->nullValues)($value)
            : in_array($value, (array) $this->nullValues);
    }
```

Even though the `$value` __is__ NULL it's not returning true here... Why?

IMHO this is an inconsistency throughout the whole Lens system (as `nullable()` is not really necessary on lenses), but in that case it is required. Probably it's possible to resolve the issue for the `Currency` field only, but maybe there is more behind that.

In case I could not really make my point please forgive me. it's late and I am not a native english speaking person.

Cheers.

**Comment by crynobone** [comment]
Fixed `v3.12.0` via laravel/nova#991
