### ISSUE TITLE
<style> tag within svg logo unwillingly removed

### ISSUE THREAD

**Issue by loicm** [laravel/nova-issues#2825]
- Laravel Version: 5.8.35
- Nova Version: 2.12.0
- PHP Version: 7.3.19

### Description:

When having a custom svg logo replacing the Nova one and that svg file contains a `<style>` tag, the `<style>` tag is removed from Nova, except on the login page.

### Detailed steps to reproduce the issue on a fresh Nova installation:

- Edit the `resources/views/vendor/nova/partials/logo.blade.php` with a svg file containing a `<style>` tag.
- On the login page, with devtools see that the `<svg>` tag of the logo contains the `<style>` tag. 
- Login to Nova
- With devtools, see that under the `<svg>` tag of the logo, there is no `<style>` tag anymore.

**Comment by davidhemphill** [comment]
I believe this is a limitation within VueJS itself since the single-file components also use a `<style>` block.
