### ISSUE TITLE
Stack Field doesn't support PHP Generators

### ISSUE THREAD

**Issue by degecko** [laravel/nova-issues#2828]
- Laravel Version: 7.26.1
- Nova Version: 3.8.4
- PHP Version: 7.4.9
- Database Driver & Version: MySQL 8.0.17
- Operating System and Version: macOS 10.15.6
- Browser type and version: Chrome 84.0.4147.135

### Description:
With the latest update on the Stack field, in the constructor, this was added:

```
    public function __construct($name, $attribute = null, $lines = [])
    {       
         if (is_array($attribute)) {
            $lines = $attribute;
            $attribute = null;
        }
```

To add backwards compatibility for the old Stack initialization, where no sorting $attribute was required.

The problem is that is_array is not enough to check if that field is iterable, it also needs to check if it's a Generator instance, as some people, such as myself, might use yield everywhere to construct that 'array'.

Because a Generator is no array, it doesn't enter that if and that results in a `null` output when the field is resolved.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Create a stack field that uses a function to return a Generator instance.

```
Stack::make('Custom ID', self::customIdColumns());
```

```
public static function customIdColumns()
{
    yield Line::make('Some line');

    if (/* random check */) {
        yield Line::make('Another line');
    }
}
```

To fix it, I suggest replacing the is_array() check with is_iterable().
The commented param type should be updated as well.

Thanks!

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
You can solved this by adding the following:

```php
Stack::make('Custom ID', iterator_to_array(self::customIdColumns()));
```
