### ISSUE TITLE
MorphToMany Relations Doesn't show subtitles on search

### ISSUE THREAD

**Issue by alshf89** [laravel/nova-issues#2829]
- Laravel Version: 7.26
- Nova Version: 3.8.4
- PHP Version: 7.4

### Description:

On `MorphToMany` Relation I call `searchable()` and `withSubtitles()` methods on it and override the `subtitle()` method on related resource, but when I try to create an attachment and search the `MorphToMany` resource, it shows `No Additional information ...` on subtitles.

<img width="1151" alt="Screen Shot 2020-09-01 at 2 50 33 PM" src="https://user-images.githubusercontent.com/14111656/91838436-bec8c400-ec62-11ea-9945-186bea577fc6.png">

### solution 

After some research on nova's code, I find out that we have to modify and add subtitle key to the `formatAttachableResource` method on the `\Laravel\Nova\Fields\MorphToMany` class, such as the way `\Laravel\Nova\Fields\BelongsToMany` class behave.

```php
class MorphToMany extends Field implements DeletableContract, ListableField, RelatableField
{
    /**
     * Format the given attachable resource.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @param  mixed  $resource
     * @return array
     */
    public function formatAttachableResource(NovaRequest $request, $resource)
    {
        return array_filter([
            'avatar' => $resource->resolveAvatarUrl($request),
            'display' => $this->formatDisplayValue($resource),
            'subtitle' => $resource->subtitle(), // Missing Key
            'value' => $resource->getKey(),
        ]);
    }
}
```

Then we can see the correct subtitle:

<img width="1152" alt="Screen Shot 2020-09-01 at 2 55 14 PM" src="https://user-images.githubusercontent.com/14111656/91838755-3e569300-ec63-11ea-8274-acdfde52023d.png">

**Comment by alshf89** [comment]
I tried to connect my Nova account to github and send PR for this issue but it's not working and gives me some error....

**Comment by NorthBlue333** [comment]
Hi.
I just wanted to add that subtitles do not show either with the BelongsToMany field when attaching a resource.

**Comment by davidhemphill** [comment]
GitHub imposes sanctions on certain countries so you may be running into that. Sorry. :-/

**Comment by alshf89** [comment]
@davidhemphill OK, I don’t want to send any PR or etc ... but the problem still exists, Could you please fix this issue in future releases ?

Thanks,
