### ISSUE TITLE
Avatar File size validation

### ISSUE THREAD

**Issue by bradders** [laravel/nova-issues#283]
Unsure whether this is a Nova question, or a more generic Laravel one, but I ran into an issue using the `Avatar::make()` command.

I got an error 'File "" does now exist' which turned out to be thrown when trying to upload a huge file.

Is there any way to set a file size limit for uploads, and display a more useful error message?

**Comment by shirshak55** [comment]
you mean rules('max:1024*6') don't work on avatar file field?

**Comment by bradders** [comment]
Indeed, adding a max rule was what I needed: 

`Avatar::make("Avatar", "avatar")->disk("public")->rules("image", "max:5000")`

**Comment by bradders** [comment]
Reopening this as I still seem to be having issues with validating the Avatar field.

`Avatar::make("Avatar", "avatar")->disk("public")->rules("nullable", "image", "max:5000")`

When I submit a blank form (to test the validation) I get the following error. Which only seems to be present when I don't input an avatar.

Unhandled promise rejection TypeError: "_context2.t0.response is undefined" (app.js:28507:11)

The underlying database column for that is a VARCHAR 255 which allows null values.

**Comment by pr-baernholdt** [comment]
Currently, there seem to be no front-end image size validation and it just ignores the image size related rules and sends the request to the nova backend.

**Comment by davidhemphill** [comment]
Wasn't able to reproduce this. Please open a new issue if you can replicate this in a way we can test. :-)
