### ISSUE TITLE
URL generated with ID column but routing is locked to the PK.

### ISSUE THREAD

**Issue by Athuli7** [laravel/nova-issues#2830]
- Laravel Version: 7.27.0
- Nova Version: 3.8.4
- PHP Version: 7.4.9
- Database Driver & Version: MySQL, 8
- Operating System and Version: macOS / Ubunutu 18.04
- Browser type and version: Chrome 85

#### Model

```
<?php

namespace App\Models;

class Model extends \Illuminate\Database\Eloquent\Model
{
    public $primaryKey = "id";
    public $timestamps = true;
    protected $guarded = ['id'];
    public function getRouteKeyName(){ return 'id'; }
}
```

```
<?php

namespace App\Models;

class Department extends Model
{
    public function EmployeeContracts() { return $this->hasMany('App\Models\EmployeeContract'); }
}
```

#### Resource

```
<?php

namespace App\Templates;

use App\Nova\Resource;
use Laravel\Nova\Fields\ID;
use Illuminate\Http\Request;
use Laravel\Nova\Http\Requests\NovaRequest;

class ConfigurationResources extends Resource
{
    public static $title = 'name';
    public static $search = ['name',];
    public static $group = 'Configurations';
    public function fields(Request $request)
    {
        return [
            ID::make(__('Name'), 'name')->sortable(),
        ];
    }
    public function cards(Request $request)
    {
        return [];
    }
    public function filters(Request $request)
    {
        return [];
    }
    public function lenses(Request $request)
    {
        return [];
    }
    public function actions(Request $request)
    {
        return [];
    }
}

```

```
<?php

namespace App\Nova;

use Illuminate\Http\Request;
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Http\Requests\NovaRequest;

class Department extends \App\Templates\ConfigurationResources
{
    public static $model = \App\Models\Department::class;
}
```

The urls generated for view, edit & delete have the name as the key. Eg: https://ahs.sakura.lara/resources/languages/Malayalam/edit?viaResource&viaResourceId&viaRelationship, which results in a 404.

The issue is the ID field type being used instead of the text field type. But why would the url generation change if the routing is fixed to the PK.

**Comment by crynobone** [comment]
I would expect that when you use `ID::make(__('Name'), 'name')` then the model should use `name` as primaryKey. 

```php
<?php

namespace App\Models;

class Department extends Model
{
    public $primaryKey = 'name';
    protected $keyType = 'string';

    public function EmployeeContracts() { return $this->hasMany('App\Models\EmployeeContract'); }
}
```

> The issue is the ID field type being used instead of the text field type. But why would the url generation change if the routing is fixed to the PK.

If you check `Illuminate\Http\Resources\DelegatesToResource` which is used by `Laravel\Nova\Resource` by default it still look based on `Model::$primaryKey` unless you override the method.

**Comment by crynobone** [comment]
Closing this for now as there are way to resolve this at the moment.
