### ISSUE TITLE
Console error when using date filter

### ISSUE THREAD

**Issue by dgoldstein89** [laravel/nova-issues#2831]
- Laravel Version: 7.27.0
- Nova Version: 3.7.1
- PHP Version: 7.4.5
- Browser type and version: Chrome 85.0.4183.83 (Official Build) (64-bit)

### Description:
Closing the calendar produces the following console error:
`Uncaught (in promise) NavigationDuplicated: Avoided redundant navigation to current location: ...`
This happens  when selecting a date or clicking away.
The filter seems to still work.

**Comment by eboye** [comment]
Same here

Laravel Version: 7.28.3
Nova Version: 3.10.0
PHP Version: 7.4.10
Browser type and version: Chrome 86.0.4240.42 (Official Build) beta (x86_64), Firefox Developer Edition 81.0b9 (64-bit)

I was doing some changes to my custom cards that are watching for url changes and though it was that, but then I realized it's the date filter.

It's even worse in Firefox, it stops my cards from working after this error. In Chrome it just continues working.

**Comment by davidhemphill** [comment]
This error is fired because Vue thinks we're trying to navigate to the same route. When you change filters, the URL params are changed, which triggers a refresh. Anyhow, I wasn't able to replicate an issue keeping things from loading, so closing since there's not really any harm in a JavaScript console error.

**Comment by eboye** [comment]
Hmm, I see your point, and it makes sense, but as I'm hooking to url change to update my cards, it breaks thing when there is an error for some reason.

Here's what I'm doing:

nova doesn't provide the filtered scope of resources based on filter to cards. So I'm using "on url change" event to trigger new query. I'm then base64 decoding the filter params, make the query out of it, do the calculations and then update the cards.

When I change the date in any of my filters, it changes it, then clicking outside of the date input gives this error which breaks my event handler.

Is there any nova event like Nova.$on('filter-change') which I can hook into ???

**Comment by davidhemphill** [comment]
There are internal events fired, but no events on the Nova event bus. I'll look into adding that. :-)

**Comment by eboye** [comment]
@davidhemphill great, thanks.
