### ISSUE TITLE
Default value for filter should increase displayed filter count

### ISSUE THREAD

**Issue by tpetry** [laravel/nova-issues#2832]
- Laravel Version: 7.27.0
- Nova Version: 3.8.4

### Description:
When using the [default option](https://github.com/laravel/nova-issues/issues/848#issuecomment-545363874) for a resource filter the filter will be activated with the specified value by default. So when the resource index is opened the filter is active, but it's not visible that an filter is active so almost nobody is aware that a filter can be deactivated to see more data.

So if you open the resource index with an active default filter you see:
<img width="1387" alt="Bildschirmfoto 2020-09-03 um 12 17 52" src="https://user-images.githubusercontent.com/315686/92102959-974b3600-eddf-11ea-9279-0ceb80e1d90b.png">

But you should see the following to know you can change an active filter:
<img width="1379" alt="Bildschirmfoto 2020-09-03 um 12 18 01" src="https://user-images.githubusercontent.com/315686/92103018-ab8f3300-eddf-11ea-9829-186d9dd815ef.png">

**Comment by davidhemphill** [comment]
The existing functionality is how it was designed to work.

**Comment by warksit** [comment]
> The existing functionality is how it was designed to work.

Can I ask why?
