### ISSUE TITLE
Why my user page only show edit button ,dont have view and delete ?

### ISSUE THREAD

**Issue by Cheewingtan** [laravel/nova-issues#2837]
- Laravel Version: #.#.#
- Nova Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:
I follow the documentation install nova on my project but after I finish the installation ,my user page only can edit the user data ,it doesn't have the view and delete button 
<img width="1440" alt="Screenshot 2020-09-05 at 10 28 12 PM" src="https://user-images.githubusercontent.com/11556877/92307206-31b99e00-efc7-11ea-94a0-01a6685bd435.png">
I use v2.12.0 version

**Comment by davidhemphill** [comment]
You likely have a Policy that is keeping your user from having view and delete permissions.
