### ISSUE TITLE
Conditionally Loading Theme Service Providers

### ISSUE THREAD

**Issue by zikoudev** [laravel/nova-issues#2838]
Hey, 

I would like to use multiple themes/packages in my nova app, but all ThemeServiceProvider are auto loaded and there's no option to switch between themes, ex : original & rtl

It would be really helpful to add this feature ! 

Current work around is to edit the boot function in the ThemeServiceProvider.php file of the package
```
    public function boot()
    {
        $locale = \App::getLocale();
        if($locale == 'ar'){
		//original boot code
        }
    }
```

**Comment by jbrooksuk** [comment]
You could disable the package from being auto-discovered and load it when required, https://laravel.com/docs/7.x/packages#package-discovery
