### ISSUE TITLE
Creation fields request access to parent model

### ISSUE THREAD

**Issue by SethTompkins** [laravel/nova-issues#284]
Currently when the creation fields are requested from nova, details from the parent request are not passed through. This makes it impossible to use data like `viaRelation` and `viaRelationId` to generate fields that may have conditional attributes based on whether or not they are being created from a certain parent detail screen.

**Original request**

`/nova/resources/field-mappings/new?viaResource=mappings&viaResourceId=1&viaRelationship=field_mappings`

**Intent**

Creating a related record from the detail page of a parent record: there is a select box on the form that has options that should be different based upon data from the parent record.

**Problem**

When gathering metadata to generate the fields on the frontend, Nova makes a request to `/nova-api/field-mappings/creation-fields` without passing through the query string from the original request: `?viaResource=mappings&viaResourceId=1&viaRelationship=field_mappings`. This means that the `NovaRequest` available to the child resource's `fields` method cannot properly call `->findParentModel()` on its supplied `$request` argument to get the related parent model.

**Comment by itsgonnabesick** [comment]
I've been searching for hours how I could do conditionnal filtering of BelongsTo on forms.
The only thing I've found is that you could put a static function relatable{Model} on your ressources to scope your relatableQuery for a specific ressource but there`s nothing in the request or the query that gives the via's informations. So far I'm stuck.

**Comment by adriandmitroca** [comment]
I have faced the same issue as well. The most basic solution for this seems to be passing query params altogether with `/creation-fields` request so within the `fields` method we could just pick it up directly like `$request->get('viaResource')`.

What do you guys think about this?

@davidhemphill @taylorotwell

**Comment by dkulyk** [comment]
It has been added in v1.2.1.

**Comment by webspectyler** [comment]
Is there an example of how to use this in 1.2.1?

**Comment by adriandmitroca** [comment]
Okay, I've found that when you access the resource via detail view following are passed with the request:

```
[
  "viaResource" => "users"
  "viaResourceId" => "45"
  "viaRelationship" => "actions"
]
```

However, not when you are trying to edit resource - in this case, the request is still empty like before 1.2.1.

Could you please re-open this issue @bonzai?

**Comment by dkulyk** [comment]
PR was sent to upstream.

**Comment by Megatron4537** [comment]
> Okay, I've found that when you access the resource via detail view following are passed with the request:
> 
> ```
> [
>   "viaResource" => "users"
>   "viaResourceId" => "45"
>   "viaRelationship" => "actions"
> ]
> ```
> 
> However, not when you are trying to edit resource - in this case, the request is still empty like before 1.2.1.
> 
> Could you please re-open this issue @bonzai?

How so? I am trying to access viaResourceId from `NovaRequest $request` via route(), get(), query(), all return null, it seems as im only able to retrive the parent models name but not it's id

**Comment by adriandmitroca** [comment]
@Megatron4537 have you tried `request('resourceId')`?

You need to be aware that not in all context Nova is aware of selected resource but code still can be executed - this might be the case for rendering resource index for example. I highly recommend using Laravel Dump Server for inspecting these values to preview entire request lifecycle.

**Comment by Megatron4537** [comment]
dump server is indeed useful, I still can't access my parent resource when in relatableChildModel even though it's in the url displayed, it seems as tho the relatable query is passed to another controller with a different url

**Comment by aaronahearne** [comment]
This was closed for no reason and still hasnt been resolved. You cannot access any of the related resource data when attaching resources which really hinders the usefulness of the relatable query.

**Comment by yordivd** [comment]
I still have this issue in Nova 4.x on inline creation modal for BelongsTo relation.
