### ISSUE TITLE
Laravel Nova Delete Button Not working

### ISSUE THREAD

**Issue by merajsiddiqui** [laravel/nova-issues#2840]
- Laravel Version: v5.8.38
- Nova Version: 2.5.0
- PHP Version: 7.1.3
- Database Driver & Version: MySQL
- Operating System and Version:  MacOS
- Browser type and version: Chrome

### Description:
<img width="1462" alt="Screen Shot 2020-09-06 at 4 33 45 PM" src="https://user-images.githubusercontent.com/7237606/92325838-c3c0b580-f05e-11ea-8bba-7652d7e16051.png">

I have been facing issue with Nova Delete button. When clicked it makes the are grey but no action takes place. I have tried and `php artisan nova:publish` as well `php artisan nova:publish --force` suggested in other issue. I am stuck.

**Comment by jbrooksuk** [comment]
v2.5.0 is outdated. Please update.

**Comment by kylescousin** [comment]
I have 3.15 and still have this issue.
