### ISSUE TITLE
BelongsTo field in the fieldsForCreate method

### ISSUE THREAD

**Issue by iBet7o** [laravel/nova-issues#2841]
- Laravel Version: 7.27.0
- Nova Version: 3.8.4
- PHP Version: 7.4.1
- Database Driver & Version: MySQL 8.0.19

### Description:

I use the fieldsForCreate method to show the necessary fields to create a record but when I want to add a field of type BelongsTo I get the following error: **"Trying to get property 'resourceClass' of non-object"**.

Model:

```php
    ...

    public function customer()
    {
        return $this->belongsTo(\App\Customer::class);
    }

    ...
```

Resource:

```php
    ....

    public function fieldsForCreate(Request $request)
    {
        return [
            Heading::make(__('Customer')),

            BelongsTo::make(__('Customer'), 'customer', Customer::class),
        ];
    }

    ...
```

If I only use the fields method the field is displayed without problems.

**Comment by crynobone** [comment]
Similar report to #2770

**Comment by crynobone** [comment]
Tested on latest Laravel Nova and unable to replicate this via https://github.com/nova-issues/issue-2841/commit/cfcc7b4e9fb2638cd87a70f5abeed9ef0b818778

We did make multiple changes to dynamic field method which could have solved this issue.
