### ISSUE TITLE
Slug Field: Not shown on create, doesn't work with unique

### ISSUE THREAD

**Issue by bashgeek** [laravel/nova-issues#2845]
- Laravel Version: 8.0
- Nova Version: 3.9.1
- PHP Version: 7.4.10
- Database Driver & Version: MariaDB 10.5.5
- Operating System and Version: macOS 10.15.6
- Browser type and version: Brave 85.x

### Description:
First of all, thanks for adding this kind of field to the core package!

However, I ran into some issues migrating our current system over. We need the Slug to be unique in our system, since we just it as part of our URL's. I can setup the rules accordingly (see below), which works fine on updating (at least I'm getting an error message that this Slug is already in use when trying to change it to something that already exists), but it doesn't on creating a post. Reason for this might be that the slug field isn't showing at all on create (I also tried forcing it with `showOnCreating()`), so it's not able to show the error message.

Can we have the Slug field also show on create, which will show the suggested slug while I change the title (or whatever is set as `from()`) inside and let me change the slug if I wanted to or run into a unique error?

Thanks a lot!

### Detailed steps to reproduce the issue on a fresh Nova installation:
Installed, using `Slug::make('Slug')->from('Title')->readonly(false)->updateRules('unique:posts,slug,{{resourceId}}')->creationRules('unique:posts,slug')` as field

**Comment by davidhemphill** [comment]
I'm not sure why it's not showing on create for you, but it is in a fresh Nova installation: 

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/58970/92616832-4f675b80-f284-11ea-8395-f3b22c1f0e71.png">

Make sure you've republished your assets if you updated from 3.9.0 to 3.9.1.

**Comment by bashgeek** [comment]
@davidhemphill Still doesn't work for me. Using 3.9.2 now, did a fresh, separate installation, but still doesn't show on create.

- Fresh base Laravel 8.0 installation
- Fresh Nova 3.9.2 installation 
- Added Post migration (title + slug field as text) + Post model
- Added Post resource

Post resource fields:
```php
public function fields(Request $request)
    {
        return [
            ID::make(__('ID'), 'id')->sortable(),
            Text::make('Title')->rules('required'),
            Slug::make('Slug')->from('Title')->readonly(false),
        ];
    }
```

I did a little digging and ran Nova in dev mode (`npm run dev` in nova folder + publish afterwards) and it comes up with the following errors in console in the create screen:
```
[Vue warn]: Error in render: "TypeError: Cannot read property 'type' of undefined"

found in

---> <FormSlugField> at resources/js/components/Form/SlugField.vue
       <Card> at resources/js/components/Card.vue
         <FormPanel> at resources/js/components/Form/Panel.vue
           <LoadingView> at resources/js/components/LoadingView.vue
             <CreateForm> at resources/js/components/CreateForm.vue
               <Create> at resources/js/views/Create.vue
                 <Root>
```

```
TypeError: Cannot read property 'type' of undefined
    at Proxy.render (app.js?id=e73a4a9259956abf86da:53508)
    at VueComponent.Vue._render (vendor.js?id=7efac0ee6de635f56844:117065)
    at VueComponent.updateComponent (vendor.js?id=7efac0ee6de635f56844:117581)
    at Watcher.get (vendor.js?id=7efac0ee6de635f56844:117992)
    at new Watcher (vendor.js?id=7efac0ee6de635f56844:117981)
    at mountComponent (vendor.js?id=7efac0ee6de635f56844:117588)
    at VueComponent.webpackJsonp../node_modules/vue/dist/vue.common.dev.js.Vue.$mount (vendor.js?id=7efac0ee6de635f56844:122558)
    at VueComponent.webpackJsonp../node_modules/vue/dist/vue.common.dev.js.Vue.$mount (vendor.js?id=7efac0ee6de635f56844:125458)
    at init (vendor.js?id=7efac0ee6de635f56844:116639)
    at createComponent (vendor.js?id=7efac0ee6de635f56844:119487)
```

I left the test install up and running here, if you want to have a look yourself at these errors:
```
http://64.227.14.150/nova
test@test
test123
```

**Comment by bashgeek** [comment]
@davidhemphill Can you please confirm, that you saw my comment? Otherwise I'll have to open a new ticket, thanks a lot!

**Comment by davidhemphill** [comment]
You would have to make sure and update your locally-compiled version to use the latest laravel-nova NPM package to correctly compile it locally. I'm still not able to replicate your issue with any of the latest versions. :-(

**Comment by bashgeek** [comment]
@davidhemphill Alright, I had another deeper look and I think I found the issue. I specifically set `->readonly(false)` in the Nova resource for the Slug field. If I specifically set it to `->readonly(true)` is does indeed show and seems to work, but cannot be changed because it's readonly - which it definitely should to make the user be able to change it when it already exists and should be unique.

The underlying problem here seems to be, that `extraAttributes` isn't set for the field, if readonly is not specifically set, which results in a Javascript error in the frontend, which expects it. It seems to work properly on update because of this code block:
https://github.com/laravel/nova/blob/512af9cfca0c50b9c391492b1a327d9944b35f12/src/Fields/Slug.php#L87 which sets it readonly.

I think #2855 was reporting the exact same thing, just with less details. Can you try to replicate the issue by simply setting `->readonly(false)` for the Slug field and check the create form again?

You should be able t

**Comment by brensondevalfa** [comment]
I can confirm. If i add `->readonly(true)` field works. An yes #2855 is same issue.

**Comment by sileence** [comment]
I'm experiencing this problem on Laravel 8, Laravel Nova 3.16.3.

I tried recompiling the assets and the error persists, as @brensondevalfa indicated, it works only if I add ->readonly(true) to the slug field.


```
[Vue warn]: Error in render: "TypeError: undefined is not an object (evaluating '_vm.extraAttributes.type')"

found in

---> <FormSlugField> at resources/js/components/Form/SlugField.vue
       <Card> at resources/js/components/Card.vue
         <FormPanel> at resources/js/components/Form/Panel.vue
           <LoadingView> at resources/js/components/LoadingView.vue
             <CreateForm> at resources/js/components/CreateForm.vue
               <Create> at resources/js/views/Create.vue
                 <Root>
```
