### ISSUE TITLE
Nova Date Field in Nova Action fails validation and passes no value

### ISSUE THREAD

**Issue by MohammadAbusaleh** [laravel/nova-issues#2848]
- Laravel Version: 7.28.0
- Nova Version: 3.9.1
- PHP Version: 7.4.3
- Database Driver & Version: MySql 5.7
- Operating System and Version: Pop!_OS 20.04 LTS
- Browser type and version: Chrome 85.0.4183.83

In Nova Action, Date fields fail to validate
![image](https://user-images.githubusercontent.com/12821490/92622706-69318e80-f2d6-11ea-871d-109364106b34.png)

Steps to reproduce
1- run `php artisan nova:action UploadLocalLicense`

2- Code for Nova Action

```
<?php

namespace App\Nova\Actions;

use Illuminate\Bus\Queueable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Log;
use Laravel\Nova\Actions\Action;
use Laravel\Nova\Fields\ActionFields;
use Laravel\Nova\Fields\Date;
use Laravel\Nova\Fields\Image;
use Laravel\Nova\Fields\Select;

class UploadLocalLicense extends Action
{
    use InteractsWithQueue, Queueable;

    /**
     * Perform the action on the given models.
     *
     * @param ActionFields $fields
     * @param Collection $models
     * @return mixed
     */
    public function handle(ActionFields $fields, Collection $models)
    {
        foreach ($models as $model) {
            Log::info($fields->issued_on);
            Log::info($fields->expires_on);
        }
    }

    /**
     * Get the fields available on the action.
     *
     * @return array
     */
    public function fields()
    {
        return [
            Image::make('License')->rules('required', 'mimes:jpg,jpeg,png', 'max:1024'),

            Select::make('Agency')->options([
                'FTA' => 'FTA',
                'DMCA' => 'DMCA'
            ])->rules('required'),

           Date::make('Issued On')->rules('required', 'date_format:Y-m-d'),

           Date::make('Expires On')->rules('required', 'date_format:Y-m-d')
        ];
    }
}
```

3- Add to Nova Resource

`(new UploadLocalLicense())->confirmButtonText('Upload License'),`

**Additional Information:**

1- DateTime works fine, the issue only concerns the Date field

![image](https://user-images.githubusercontent.com/12821490/92624775-f1b12e80-f2d8-11ea-8162-11ce52257528.png)

2- In the console, when date is selected this error shows

![image](https://user-images.githubusercontent.com/12821490/92623818-d265d180-f2d7-11ea-9964-cd463e3e8b8a.png)

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
