### ISSUE TITLE
Redirect user to url app, not nova

### ISSUE THREAD

**Issue by socialab-admin** [laravel/nova-issues#2851]
Is there a way to redirect the user after creating a resource to a page of my application (not nova)?
![Captura](https://user-images.githubusercontent.com/45668463/92646815-5ced0780-f2bd-11ea-88ce-6552747506a6.PNG)

Currently I modified the nova layout to integrate it into my design, it looks and works great, but I need to create a repository and then redirect the user to a page of my application that is not NOVA

**Comment by rvalenzuelaferrada** [comment]
If anyone has the same problem, write a package in laravel nova to fix it.
https://novapackages.com/packages/laramaker/redirect-after-asset

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
