### ISSUE TITLE
3.9.2 version reporting incorrectly

### ISSUE THREAD

**Issue by ragingdave** [laravel/nova-issues#2854]
- Laravel Version: 7.28.1
- Nova Version: 3.9.2
- PHP Version: 7.4.3

### Description:
3.9.2 is showing the previous version of 3.9.1.

**Comment by abishekrsrikaanth** [comment]
Seems like the version was not bumped at https://github.com/laravel/nova/blob/3.0/src/Nova.php#L157

**Comment by davidhemphill** [comment]
Fixed this in later versions. Thanks for reporting!
