### ISSUE TITLE
Slug field is not displayed in resource creation form

### ISSUE THREAD

**Issue by HexPande** [laravel/nova-issues#2855]
- Laravel Version: 7.28.1
- Nova Version: 3.9.2
- PHP Version: 7.4

### Description:
The problem is that when creating a resource, the "nova/resources/js/components/Form/SlugField.vue" component accesses the non-existent property this.field.extraAttributes

### Solution:
In the vue component, make an appeal like this.field.extraAttributes || {}

OR

In class (nova/src/Fields/Slug.php) in the returned array of method jsonSerialize() add the element 'extraAttributes' => []

**Comment by davidhemphill** [comment]
I'm not able to replicate your issue on a fresh Nova installation of 3.9.2. The Slug field is showing correctly.

**Comment by brensondevalfa** [comment]
I have same issue "TypeError: e.extraAttributes is undefined" when creating new resource.
Laravel 8.2
Nova 3.9.4
PHP 7.3

**Comment by davidhemphill** [comment]
Upgrade to v3.10.0
