### ISSUE TITLE
panelsWithDefaultLabel() return array instead of collection

### ISSUE THREAD

**Issue by ahmedkandel** [laravel/nova-issues#2857]
- Laravel Version: 7.23.2
- Nova Version: 3.8.2
- PHP Version: 7.4.7
- Database Driver & Version: MySQL 5.7.23
- Operating System and Version: Win 10
- Browser type and version: Chrome 85.0.4183.102

### Description:
I am creating a **new Resource Tool** that will callback a local API. Inside the controller method that will handle the API request I have injected **NovaRequest** to use it to retrieve the resource information as following:
```php
public function save(NovaRequest $request)
{
    $resource = $request->findResourceOrFail();

    $resource->authorizeToUpdate($request);

    $model = $resource->model();

    $tool = $resource->availablePanelsForDetail($request)
        ->whereInstanceOf(MyToolClass::class)
        ->firstWhere('attribute', $request->route('field'));

        abort_unless($model && $tool, 404);

        //Do the job and return json
}
```
When call the API i get an error 500 **"Call to a member function whereInstanceOf() on array"**
I have checked the source code of **ResolvesFields.php** and found that **panelsWithDefaultLabel()** return array instead of collection.
So I have created a PR to fix this https://github.com/laravel/nova/pull/959

### Detailed steps to reproduce the issue on a fresh Nova installation:
Call **whereInstanceOf()** or any collection method on **availablePanelsForDetail()**

**Comment by crynobone** [comment]
I will check with @davidhemphill on this but it seem that the original code was committed 15 months ago and I would expect that this is more a docblock error than code error.  

In the meantime you can use the following first:

```php
$tool = collect($resource->availablePanelsForDetail($request))
        ->whereInstanceOf(MyToolClass::class)
        ->firstWhere('attribute', $request->route('field'));
```
