### ISSUE TITLE
Trix Field always passes empty value

### ISSUE THREAD

**Issue by aulab-hackademy** [laravel/nova-issues#2858]
- Laravel Version: 8.0.1
- Nova Version: 3.9.2
- PHP Version: 7.4.10
- Database Driver & Version: MySQL 5.7
- Operating System and Version: Mac OSX 10.15.6
- Browser type and version: Chrome

**Comment by loekwetzels** [comment]
Possibly related to #2853

**Comment by bredisvictor** [comment]
Nova Version: 3.9.2, the same issue.
Cannot continue development because of this bug, also can't roll back because have did many commits after nova update.
Please FIX IT soon as possible.

**Comment by sanis** [comment]
laravel/framework                  v7.28.1            The Laravel Framework.
laravel/nova                       v3.9.2             A wonderful administration interface for Laravel

Same happens to me.

**Comment by crynobone** [comment]
https://github.com/laravel/nova-issues/issues/2853#issuecomment-692224262

This should have been fixed with `v3.9.4`. Closing this for now but feel free to create new issue if the problem still persist.
