### ISSUE TITLE
Metric Equal Previous and Current does not show constant but blank

### ISSUE THREAD

**Issue by JurjenRoels** [laravel/nova-issues#2859]
- Laravel Version: 8 
- Nova Version: 3.9.2
- PHP Version: 7.3.16
- Database Driver & Version:
- Operating System and Version: Mac
- Browser type and version: Chrome _ Safari
- Reproduction Repository: https://github.com/###/###

### Description:
When I add a metric to the dashboard and within a range I have the same value for result and previous. 
Nothing is shown in the Increase/Decrease. I would Expect an indication that the increase/decrease is constant.

### Detailed steps to reproduce the issue on a fresh Nova installation:
    public function calculate(NovaRequest $request)
    {
        return $this->result(100)->previous(100);
    }

**Comment by crynobone** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/107175810-bb531900-6a08-11eb-93c1-59f105441017.png)

I tried implementing this but not happy with the result. 

```html
<p class="flex items-center text-80 font-bold">
  <svg width="24" height="24" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="text-warning stroke-current mr-2">
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 12H4"></path>
  </svg>
</p>
```
