### ISSUE TITLE
Package installer selection when create nova tool using nova:tool 

### ISSUE THREAD

**Issue by zeroseed** [laravel/nova-issues#286]
Hi so sometimes i have a problem with js dependencies installation using NPM , but succeed when using YARN, maybe when nova ask to install NPM dependencies , we can choose install using NPM or YARN 
because nowadays i think everyone use YARN too 😃

**Comment by davidhemphill** [comment]
This repository is for tracking bugs. Feature requests may be emailed to Nova customer support.
