### ISSUE TITLE
Disable Scout for related search

### ISSUE THREAD

**Issue by Lampone** [laravel/nova-issues#2860]
- Laravel Version: v7.28.1
- Nova Version: v3.9.2
- PHP Version: 7.2.29
- Database Driver & Version: MySQL 5.7.29

### Description:
If your search for a related resource and scout is enabled, nova will first search for the search-string and then filter the result based on the relation. The related search is unusable because the 5 results of the search are not actually related.

Is there a way to disable scout for a related search? This way the search and relation constrain could be in the same query and only search related models. 

### Detailed steps to reproduce the issue on a fresh Nova installation:
2 related models with a lot of records and search for the related model.

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by infostreams** [comment]
For random Googlers, the answer is to add this to your Nova Resource

```php
public static function usesScout()
{
    return false;
}
```

From https://stackoverflow.com/a/56263508
