### ISSUE TITLE
BelongsToMany pivot table fields validation errors

### ISSUE THREAD

**Issue by keizah7** [laravel/nova-issues#2861]
- Laravel Version: 8.0
- Nova Version: v3.9.1
- PHP Version: 7.4.9
- Database Driver & Version: mysql 5.7
- Operating System and Version: macOS Catalina 10.15.6
- Browser type and version: Firefox 80.0.1

### Description:
BelongsToMany relationship don't show pivot table fields validation errors on attaching to resource

`App\Nova\Model;`
```
BelongsToMany::make(__('Prekės'), 'products', 'App\Nova\Product')
->fields(function () {
    return [
        Currency::make(__('Kaina'), 'price')
            ->rules('required'),
        Text::make(__('Matmenys'), 'dimensions'),
        Number::make(__('Kiekis'), 'quantity')
            ->rules('nullable', 'integer'),
        Text::make(__('Vienetas'), 'unit'),
        Currency::make(__('Nuolaida'), 'discount')
            ->rules('nullable', 'min:0'),
    ];
})->rules('required')
```

### Detailed steps to reproduce the issue on a fresh Nova installation:
Resource / Attach Model / Select Model (TypeError: this.resourceInformation is undefined shows up) /  Attach Model button
![image](https://user-images.githubusercontent.com/49227202/92977781-8dd46480-f496-11ea-9341-9bf502657f7b.png)

POST | nova-api/orders/1/attach/products?editing=true&editMode=attach
![image](https://user-images.githubusercontent.com/49227202/92977824-ae9cba00-f496-11ea-811e-97c4911dea0c.png)

**Comment by crynobone** [comment]
Should be fixed via laravel/nova#997 and release today (tuesday weekly release).
