### ISSUE TITLE
Error with Resource label translations

### ISSUE THREAD

**Issue by jcorrego** [laravel/nova-issues#2864]
- Laravel Version: 8.2.0
- Nova Version: 3.9.2
- PHP Version: 7.4.10
- Database Driver & Version: Mysql 8
- Operating System and Version: MacOS Catalina
- Browser type and version: Chrome 85.0.14

### Description:
When Nova is trying to render the label of the resources in its navigation, i get 
`ErrorException
htmlspecialchars() expects parameter 1 to be string, array given`

I have traced the issue to be with my existing translations. For example.
i have this file in my system: `resources/lang/es/teams.php`
And i have a Nova resource called `Team`.
So when Nova is trying to display the translated string for the plural of the resource `teams`,  the `$resource::label()` method is returning all my translation strings inside my lang php file, as an array...
For now, i have included those strings in the `.json` translation files that i normally dont use, and the error is gone...

**Comment by BnitoBzh** [comment]
I have the same issue with two translation files (teams.php, surveys.php). If i remove them it works.
The issue starts at nova@3.8.0.
