### ISSUE TITLE
Split `withAuthenticationRoutes` into `withLoginRoute` and `withLogoutRoute`

### ISSUE THREAD

**Issue by faustbrian** [laravel/nova-issues#2865]
The `withAuthenticationRoutes` method is currently responsible for registering the login and logout routes that nova uses. This is generally not an issue but when you want to disable the nova login so that the login has to happen at another place you need to manually register the routes like below.

```php
    protected function routes()
    {
        Nova::routes()->register();

        // Manually register this to avoid enabling the non-2FA login from nova.
        Route::namespace('Laravel\Nova\Http\Controllers')
            ->domain(config('nova.domain', null))
            ->middleware(config('nova.middleware', []))
            ->prefix(Nova::path())
            ->group(function () {
                Route::get('/logout', 'LoginController@logout')->name('nova.logout');
            });
    }
```

More often then not I am using the above snippet because I want to enforce 2FA login through another part of the application that handles all of the authentication flow. The quickest and easiest solution this problem I think would be to split `withAuthenticationRoutes` into 2 methods that are separately responsible for registering login and logout routes so that it is easier to disable everything except the logout route.

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
