### ISSUE TITLE
DateFilter format Y-m-d H:i

### ISSUE THREAD

**Issue by keizah7** [laravel/nova-issues#2866]
- Laravel Version: 8.0
- Nova Version: v3.9.1
- PHP Version: 7.4.9
- Database Driver & Version: mysql 5.7
- Operating System and Version: macOS Catalina 10.15.6
- Browser type and version: Firefox 80.0.1

### Description:
Can't change DateFilter format to Y-m-d H:i. Where is options method in filter class, but it does not pass data to the component

![image](https://user-images.githubusercontent.com/49227202/93197265-192e4e00-f754-11ea-8f73-b4bd0f900200.png)

**Comment by keizah7** [comment]
I created package to solve my problem.
https://novapackages.com/packages/keizah7/custom-date-filter
It would be cool if nova implemented this functionality too

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
