### ISSUE TITLE
Add npm install scripts to root package.json

### ISSUE THREAD

**Issue by mitchierichie** [laravel/nova-issues#2868]
Similarly to how each nova component has a build and build-prod script in the application's package.json, it would be helpful to have 'npm i' and 'npm i --production' scripts for each component.

I'm using [npm-run-all](https://www.npmjs.com/package/npm-run-all) to run these, which saves me a lot of time/typing.

In each console command php file, the function would look something like this (using Field as example but would need to change function calls for different component types)

```php
            /**
     * Add a path repository for the tool to the application's composer.json file.
     *
     * @return void
     */
    protected function addScriptsToNpmPackage()
    {
        $package = json_decode(file_get_contents(base_path('package.json')), true);

        $package['scripts']['build-'.$this->toolName().'-dev'] = 'cd '.$this->relativeToolPath().' && npm run dev';
        $package['scripts']['build-'.$this->toolName().'-prod'] = 'cd '.$this->relativeToolPath().' && npm run prod';

        
        $package['scripts']['install-'.$this->fieldName().'dev'] = 'cd '.$this->relativeFieldPath().' && npm i';
        $package['scripts']['install-'.$this->fieldName().'-prod'] = 'cd '.$this->relativeFieldPath().' && npm i --production';

        file_put_contents(
            base_path('package.json'),
            json_encode($package, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)
        );
    }
```

You might notice, I also added -dev to the dev scripts, as using things like npm-run-all, it makes it much easier to run them and not run -prod scripts.

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
