### ISSUE TITLE
Trix field questions

### ISSUE THREAD

**Issue by thegregthomp** [laravel/nova-issues#287]
Two questions related to this field: 

1: The field always starts in a "Show Content" state. I'd like the content to show by default. Is this possible? 
![image](https://user-images.githubusercontent.com/1554124/44732560-91fdd700-aab3-11e8-9c9d-284005390b93.png)

2: Is it possible to have the field always editable, even if you're not in the editable state for the resource? I know this is a long shot but just asking. Thanks!

**Comment by albalooshi** [comment]
**Warning** this is a quick hack, and needs to be done at every update until the original developers give an option to do that.

In `public/nova-assets/app.js`

Search for `data:function(){return{expanded:!1}}` and remove the `!` , an example: `data:function(){return{expanded:1}}`

**Comment by davidhemphill** [comment]
1. Yes. Added and will be included in an upcoming release.
2. No.

**Comment by albalooshi** [comment]
@davidhemphill 
Hi David, I cant find the documentation for "Allow Textarea, Markdown, and Trix fields to always show content if desired.", can you please give an example hows thats done?
