### ISSUE TITLE
Relatable: "field" parameter inconsistently holds either resource or relationship name

### ISSUE THREAD

**Issue by sgittel** [laravel/nova-issues#2870]
- Laravel Version: 7.26.0
- Nova Version: 3.8.4
- PHP Version: 7.4

### Description:
In BelongsTo fields, `$request->route()->parameter('field')` contains the name of the relationship method.
In BelongsToMany fields, the same parameter contains the plural name of the relatable Nova resource (not the model name, I checked).

### Detailed steps to reproduce the issue on a fresh Nova installation:
Have Nova resources "Offerer" and "Contact". The "Contact" resource has an underlying model "\App\Contact", name the model for "Offerer" whatever you want. Have BelongsTo `employee` or BelongsToMany `employees` eloquent relationship set up according to the resource field, depending on the case (see below).

#### Case 1:
In `public function Offerer::fields()` return
```php
...
BelongsTo::make(__('employee', 'employee', Contact::class),
...
```
Then, when performing the relatable query, in `public static function Offerer::relatableContacts(NovaRequest $request, $query)` you can check `$request->route()->parameter('field')` and it will give you `employee`. This will give you the opportunity to limit the relatable query depending on the relationship used, in case you have multiple relationships between Offerer and Contact.

#### Case 2:
In `public function Offerer::fields()` return
```php
...
BelongsToMany::make(__('employees', 'employees', Contact::class),
...
```
Then, when performing the relatable query, in `public static function Offerer::relatableContacts(NovaRequest $request, $query)` you can check `$request->route()->parameter('field')` and it will give you `contacts` instead of 'employees'. Therefore you can not distinguish between different relationships between Offerer and Contact.

This might be related to or causing #2842

**Comment by davidhemphill** [comment]
Hi! Please create a reproduction repository so we can check this issue out directly. Thanks!

**Comment by crynobone** [comment]
Changing the route parameter behavior could potentially create a breaking changes for those that already consider this behavior. However, I made a PR that would will pass the `Field` as 3rd parameter for `relatableQuery()`.
