### ISSUE TITLE
Can't set any text field empty, because Nova tries to save it as NULL

### ISSUE THREAD

**Issue by zhenya31** [laravel/nova-issues#2873]
Even when resource's field isn't required and isn't nullable I can't save empty string because Nova tries to save it as NULL so it throws an exception like "SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'text' cannot be null..."

Is there any solutions?

**Comment by keizah7** [comment]
You can try set default value for attribute in your model
```
protected $attributes = [
        'text' => '',
];
```

**Comment by davidhemphill** [comment]
Laravel by default converts incoming empty string values in the request to NULL values.
