### ISSUE TITLE
Changelog needed, or needs to linked

### ISSUE THREAD

**Issue by ux-engineer** [laravel/nova-issues#2875]
I follow releases in your private laravel/nova repository. All the releases have "compile + version" as the comment...that is really uninformational.

Do you have a changelog? Release messages should either include a list of changes, or link to a changelog.

I went to your documentation site but there is no changelog. Then went to the laravel/nova repository's main page to find that readme.md does not mention it either, and there is no changelog.md file.

**Comment by davidhemphill** [comment]
Changes are listed on the Nova website: https://nova.laravel.com/releases

No plans to duplicate it elsewhere.

**Comment by ux-engineer** [comment]
@davidhemphill oh, it's not linked in the [actual docs](https://nova.laravel.com/docs/3.0/installation.html) nor the repo?
