### ISSUE TITLE
Can't access request filters in resource details using metric calculate method 

### ISSUE THREAD

**Issue by keizah7** [laravel/nova-issues#2876]
- Laravel Version: 8.0
- Nova Version: v3.10.10
- PHP Version: 7.4.10
- Database Driver & Version: mysql 5.7
- Operating System and Version: macOS Catalina 10.15.6
- Browser type and version: Firefox 80.0.1

### Description:
I have Client resource and it has many orders. I created data range filter and want access filters data in client details metric  using `calculate` method. It don't work.
If I try access filters in resource index using metric calculate` method it works.

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Create Resource, Filter and Metric
- Register Filter and Metric
- Try access `$request->filters` in resource index  using metric `calculate` method  metric `calculate` method - OK
- Try access `$request->filters` in resource index using metric `calculate` method  - FAIL

**Comment by davidhemphill** [comment]
Filter values aren't sent to metrics as they weren't designed that way. Converting this to a feature request.
