### ISSUE TITLE
dump() and exception() not working in filter apply()

### ISSUE THREAD

**Issue by JurjenRoels** [laravel/nova-issues#2877]
- Laravel Version: 8.x
- Nova Version: 3.10.0
- PHP Version: 7.3
- Database Driver & Version:

Description:
I created a filter and wanted to debug something before returning the $query.
Both dump() and new throw exception do not appear in Telescope in other places this works

**Comment by davidhemphill** [comment]
This will not work since filters are triggered over AJAX.
