### ISSUE TITLE
Toggle field + readonly doesn't work

### ISSUE THREAD

**Issue by Jun-ocx** [laravel/nova-issues#2879]
- Laravel Version: #.#.#
- Nova Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:

I want my toggle field temporarily not editable by setting it readonly or disabled 
However, none of my tries worked whereas other fields are working fine (ex) textarea, text, and belongsTo, etc.

Did I do wrong? or is there any way to hack or work it around this?

### Detailed steps to reproduce the issue on a fresh Nova installation:

```
// first try
            Toggle::make('Active', 'is_active')
                ->readonly(),
                ->disabled()

//second
                ->withMeta([
                    'readonly' => true,
                    'disabled' => true,
                ])

//third
               ->withMeta(['extraAttributes' => [
                    'readonly' => true,
                    'disabled' => true,
                ]])
```

**Comment by alberto-bottarini** [comment]
What is a Toggle field? I cannot find on documentation: https://nova.laravel.com/docs/3.0/resources/fields.html

**Comment by davidhemphill** [comment]
Nova doesn't have a `Toggle` field type. Please take any 3rd-party issues to their respective repositories. Thanks!
