### ISSUE TITLE
BelongsTo field don't get prefilled using viaResourceId when self-relationship

### ISSUE THREAD

**Issue by alberto-bottarini** [laravel/nova-issues#2880]
- Laravel Version: 8.5.0 _(but I think is not related)_
- Nova Version: 3.10.0 _(but I think is not related)_
- PHP Version: 7.3.11 _(but I think is not related)_

### Description:

BelongsTo fields gets no prefill when using a self-relationship.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Create a migration and a model using these files:

```php
//migration.php
Schema::create('nodes', function (Blueprint $table) {
    $table->id();
    $table->string('name');
    $table->integer('parent_node_id')->nullable();
    $table->timestamps();
});
```

```php
//app/Models/Node.php
class Node extends Model
{
    use HasFactory;

    public function parentNode()
    {
    	return $this->belongsTo(Node::class, 'parent_node_id');
    }

    public function childrenNodes()
    {
    	return $this->hasMany(Node::class, 'parent_node_id');
    }
}
```

Then create a Nova Resource with these fields:

```php
//app/Nova/Node.php

public function fields(Request $request)
{
    return [
        ID::make(__('ID'), 'id')->sortable(),
        Text::make(__('Name')),
        BelongsTo::make(__('Parent'), 'parentNode', Node::class)->nullable(),
        HasMany::make(__('Children'), 'childrenNodes', Node::class),
    ];
}
```

Then create a model with a name and without any parent (obviously, because it's the first one).
Details page will be like this screenshot:

<img width="1139" alt="Screenshot 2020-09-19 at 11 06 50" src="https://user-images.githubusercontent.com/1442934/93663415-3c187500-fa68-11ea-849f-04b30569cae9.png">

Now, if you click on "Create Node" button in HasMany panel, you will be redirected to create page, **but BelongsTo field is not prefilled with the selected parent node id**.

<img width="1152" alt="Screenshot 2020-09-19 at 11 08 15" src="https://user-images.githubusercontent.com/1442934/93663449-6c601380-fa68-11ea-8294-fb3d3df32710.png">

If you change fields order in Nova Resource (HasMany *before* of BelongsTo)

```php
//app/Nova/Node.php

public function fields(Request $request)
{
    return [
        ID::make(__('ID'), 'id')->sortable(),
        Text::make(__('Name')),
        HasMany::make(__('Children'), 'childrenNodes', Node::class),
        BelongsTo::make(__('Parent'), 'parentNode', Node::class)->nullable(),
    ];
}
```

everything start working:

<img width="1135" alt="Screenshot 2020-09-19 at 11 09 18" src="https://user-images.githubusercontent.com/1442934/93663476-91ed1d00-fa68-11ea-8c9b-102439e370e4.png">

**Comment by jonasbrenig** [comment]
Also check the relationship of you model.
I was using `belongsToMany()` before and forgot to remove the 2nd argument of the relationship.

failed:
>return $this->hasMany(TourDriver::class, 'tour_drivers');

worked:
>return $this->hasMany(TourDriver::class);

**Comment by rderks88** [comment]
In case it helps someone: Just noticed that if the parent resource defines a fieldsForCreate() and that methods does NOT contain the HasMany relation, the BelongsTo field on your child resource does not pre-populate.

Without the fieldsForCreate(), the fields() method obviously should also define the HasMany field.
