### ISSUE TITLE
BelongsToMany incorrect resource name

### ISSUE THREAD

**Issue by FaridAghili** [laravel/nova-issues#2881]
- Laravel Version: 8.5.0
- Nova Version: 3.10.0
- PHP Version: 7.4.10
- Database Driver & Version: MySQL Server 5.7.29

### Description:
BelongsToMany's Attach form show `undefined` instead of resource name.

### Detailed steps to reproduce the issue on a fresh Nova installation:
```php
BelongsToMany::make('countries')
```

### Result
![image](https://user-images.githubusercontent.com/8607021/93722381-43906900-fba3-11ea-9e67-a45fdbe73f21.png)

**Comment by jonasbrenig** [comment]
- make sure that the modal that is connected to the resource has a relationship to `countries` (you can provide the relationship name with the second argument.
- you can also provide a third argument that references the resource you are trying to use (not the model!)
```php
BelongsToMany::make('Items', 'items', Item::class)
```

Hope that helps

**Comment by FaridAghili** [comment]
@jonasbrenig Already did that, but it shows `undefined` instead of resource title;

**Comment by davidhemphill** [comment]
I was not able to replicate this issue with the code you provided. The resource label is showing correctly in all instances I tested. 

Sorry, but we are unable to debug your issue without a reproducible code example. When you're able to demonstrate the issue with an example, feel free to open a new issue.
