### ISSUE TITLE
invalid input syntax for type uuid: 50058270226890 when global searching 50058270226890 even after desactivate search for Notification resource

### ISSUE THREAD

**Issue by xoco70** [laravel/nova-issues#2883]
- Laravel Version: 8.3.0
- Nova Version: 3.10.0
- PHP Version: 7.4.3
- Database Driver & Version: Psql
- Operating System and Version: Ubuntu 20.04
- Browser type and version: Chrome

### Description:

I have a meterId that is a string in DB: 50058270226890

When I do local search, there is no problem.

But when I do a global search, I get from http://localhost:8000/nova-api/search?search=50058270226890

`    "message": "SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type uuid: \"50058270226890\" (SQL: select * from \"notifications\" where (\"notifications\".\"id\" = 50058270226890 or \"notifications\".\"id\"::text ilike %50058270226890%) and \"type\" = SendMessage and (\"notifiable_id\" = 1) and \"notifications\".\"deleted_at\" is null order by \"notifications\".\"id\" desc limit 5)",`

I tried to disable global search with:

`public static $globallySearchable = false;`

But it had no effect. So I cleared everything, just in case:

```
php artisan cache:clear
php artisan config:clear
php artisan route:clear
composer dump-autoload
```

But it had no effect neither.

The Notification resource is based on the built-in Notification model, and the ID is a UUID.

**Comment by jonasbrenig** [comment]
`50058270226890` is not a valid UUID...
Try to save a valid one and see if the search works afterwards.

https://www.uuidgenerator.net

**Comment by xoco70** [comment]
Off course 50058270226890 is not a valid UUID, it comes from global search, so, I could search anything. Here it is a serial number.

**Comment by davidhemphill** [comment]
@xoco70 Would you try something for me real quick in your app? On line 78 of `Laravel\Nova\GlobalSearch.php`, would try changing the line to this:

```diff
- $this->request->search
+ (string) $this->request->search
```

**Comment by xoco70** [comment]
@davidhemphill I made the change, but it didn't fix the issue. Just giving the same error.

**Comment by crynobone** [comment]
@xoco70 best on my test it seem Postgres has a limit of `2147483647` as max id, when given any value above that you going to experience above error. I would recommend you to update `App\Nova\Resource`:

```php
<?php

namespace App\Nova;

use Laravel\Nova\Http\Requests\NovaRequest;
use Laravel\Nova\Resource as NovaResource;

abstract class Resource extends NovaResource
{
    /**
     * The maximum value of the resource's primary key column.
     *
     * @var int
     */
    public static $maxPrimaryKeySize = 2147483647;

    //
}
```

**Comment by xoco70** [comment]
Yes, it seems to be working great ! Thanks for the trick !

**Comment by crynobone** [comment]
@xoco70 Glad that helps, but there few odd things about your setup.

* `DatabaseNotification` model should be using `$keyType = 'uuid;` which shouldn't attempt to search by primary key, but in your case it still attempt it. I would start looking back at the Notification model and resource.
* It seem that your `notifications` table is setup correctly.

I'm proceeding to close this issue now based on fact that this is more likely a usage issue instead of a bug in Laravel Nova. Feel free to open a new issues with details if there any other issue.
