### ISSUE TITLE
Nova needs a way to hide some modal fields

### ISSUE THREAD

**Issue by keizah7** [laravel/nova-issues#2884]
Nova needs a way to hide some fields in modal.

Order has belongs to relation with Client resource.
In order create client has `showCreateRelationButton`
It would be cool if there was way to detect that form is in modal and hide some columns

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
