### ISSUE TITLE
"count(): Parameter must be an array or an object that implements Countable" on deleting a resource

### ISSUE THREAD

**Issue by Ludar-Pavel** [laravel/nova-issues#2886]
- Laravel Version: 7.28.3
- Nova Version: 3.8.4
- PHP Version: 7.3.21

### Description:
Removing a Laravel Nova resource throws an error and does not remove the resource.

Error text: `count(): Parameter must be an array or an object that implements Countable`

Likely related to the ongoing count() deprecation/behaviour change in PHP 7.2 and on.

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Create a new Nova resource that you are able to remove.
2. Attempt to remove it.

**Comment by Ludar-Pavel** [comment]
Updated to Nova 3.11. Still reproducible.

Dug a little deeper - in DeleteResourceRequest, this->resources is NULL at the moment of calling isForSingleResource.

HTTP query looks like this: 

![query](https://user-images.githubusercontent.com/69010336/95099057-6ff8c900-06fd-11eb-8cef-7ed7034b6bec.png)

That last part doesn't look right, does it?

**Comment by Ludar-Pavel** [comment]
UPDATE: Seems that the problem was Nginx misconfiguration. The query string was not passed down to Laravel.

**Comment by Ludar-Pavel** [comment]
That being said, forward-porting count() is a good idea.

**Comment by davidhemphill** [comment]
How do we reproduce this problem on the latest version?

**Comment by Ludar-Pavel** [comment]
It should break if you send a DELETE request for a resource with an empty query string.

**Comment by crynobone** [comment]
I understood the error, but the generated URL should always has `resources` in the query string. 

Not sure whether hiding the requirement is a good idea, it wouldn't be beneficial for the users to not see the issue and assume everything working fine here.
