### ISSUE TITLE
Invalid token provided

### ISSUE THREAD

**Issue by no-more-bugs** [laravel/nova-issues#2887]
- Laravel Version: 7.0.#
- Nova Version: 3.10.#
- PHP Version: 7.3.#
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:
after composer update, console ask token. i use api token from account, but console return invalid token provided.

**Comment by davidhemphill** [comment]
Contact support via nova@laravel.com for help with API key issues. Thanks!
