### ISSUE TITLE
Action fields do not show help text

### ISSUE THREAD

**Issue by FaridAghili** [laravel/nova-issues#2888]
- Laravel Version: 8.5.0
- Nova Version: 3.10.0
- PHP Version: 7.4.10
- Database Driver & Version: MySQL Server 5.7.29

### Description:
Nova does not show help text defined for its fields.

### Detailed steps to reproduce the issue on a fresh Nova installation:
```php
Text::make('Example')
    ->help('Example help text.')
```
And no help text is shown below field in Action modal.

**Comment by stephan-v** [comment]
I'm having the same issue. Can this be re-opened?

**Comment by armeniax** [comment]
Why this was closed? Little bit of clarification would be nice.

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/105254519-c0b50480-5bbc-11eb-8167-e82692076d6b.png)

A closed bug without explanation always meant there already a PR to fixed the issue and it has been merged. You should follow steps under <https://nova.laravel.com/docs/3.0/contributions.html#contributing> to gain access to `laravel/nova` repository so you can what's the progress.

**Comment by crynobone** [comment]
If anyone here still have an issue, open a [New Issue](https://github.com/laravel/nova-issues/issues/new?assignees=&labels=&template=1_Bug_report.md) with full reproducing code so we can evaluate the issue for you.

**Comment by armeniax** [comment]
@crynobone 
Well the thing is that many fields lost their help texts, which means something was changed in Nova, Since current change didn't bring in help texts.

I also see different field packages adding <help-text ... > </help-text> sections in FormField.vue which means the help text is removed from base FormField.vue.

Anyway, I guess I need to open issue ticket on each package git instead of here, since the change was introduced in Nova I think.

**Comment by crynobone** [comment]
> Anyway, I guess I need to open issue ticket on each package git instead of here, since the change was introduced in Nova I think.
 
 Package should follow Laravel Nova development progress if they want to override the component. Otherwise we can't fix any bug in Nova.

**Comment by armeniax** [comment]
@crynobone 
Is there somewhere I can see the breaking changes Nova is introducing for developers ?

**Comment by crynobone** [comment]
> Is there somewhere I can see the breaking changes Nova is introducing for developers ?

We don't do breaking change on stable version, but the UI need frequent update and we don't consider that's as breaking changes. If you want to review the commit you can get access to the code via https://nova.laravel.com/docs/3.0/contributions.html#contributing

**Comment by armeniax** [comment]
Got it, anyway, a change broke all custom developed fields out there, removing the help texts

**Comment by stephan-v** [comment]
Please link the resolving PR when you are closing issues. Also even if you did update the UI and don't consider this breaking, it is currently not at all inline with the documentation.

**Comment by driesvints** [comment]
@stephan-v maybe you missed @crynobone's message here which shows the related PR was linked: https://github.com/laravel/nova-issues/issues/2888#issuecomment-764035704
