### ISSUE TITLE
Policies need site refresh for limited resources

### ISSUE THREAD

**Issue by NormanHuth** [laravel/nova-issues#2890]
- Laravel Version: 8.5.0
- Nova Version: 3.10.0
- PHP Version: 7.4.3
- Browser type and version: Chrome

I have limited the number of resources to create for each user.

```php
    /**
     * Determine whether the user can create models.
     *
     * @param  \App\Models\User  $user
     * @return mixed
     */
    public function create(User $user)
    {
        if ($user->emotes->count()>=5) {
            return false;
        }

        return true;
    }
```

Only the button to create a new resource disappears and only appears when I reload the page.

Is there an option to update the page or permissions for the corresponding resources after one is deleted or created?

I tried it first through the model. Unfortunately without success.
```php
    /**
     * Bootstrap the model and its traits.
     *
     * @return void
     */
    public static function boot()
    {
        parent::boot();
        static::created(function () {
            redirect(Request::url());
        });
    }
```

**Comment by kakajansh** [comment]
as a quick workaround, I think something below should work

1. In your resource file, define custom `redirectAfterCreate`
```php
/**
 * Return the location to redirect the user after creation.
 *
 * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
 * @param  \Laravel\Nova\Resource  $resource
 * @return string
 */
public static function redirectAfterCreate(NovaRequest $request, $resource)
{
    return "/force-reload/$resource";
}
```

2. As Nova handles routing with vue-router, put this somewhere in custom tool.
```js
Nova.booting((Vue, router, store) => {
  router.addRoutes([
    {
      path: '/force-reload/:resourceName',
      redirect: to => {
        const route = router.resolve({name: 'index', params: to.params})
        window.location.href = route.href
      }
    }
  ])
});
```

**Comment by NormanHuth** [comment]
1. Make a error. `App\Nova\Test could not be converted to string`. I've change it to:
```php
return '/force-reload/'.$resource->getKey();
```

2. I created a tool and the content of the tool.js is:
```
<script>
Nova.booting((Vue, router, store) => {
    router.addRoutes([
        {
            path: '/force-reload/:resourceName',
            redirect: to => {
                const route = router.resolve({name: 'index', params: to.params})
                window.location.href = route.href
            }
        }
    ])
});
</script>
```

And I add the new Tool to the NovaServiceProvieder.
But I'm landing on the page: http://localhost/settings/force-reload/19

**Comment by davidhemphill** [comment]
I've seen this several times now, and previously felt we needed to wait until a breaking release to fix this, but going to look into patching something in for now. 👍

**Comment by NormanHuth** [comment]
@davidhemphill 

Is there any option to redirect to Update/Delete/Create outside Nova? Then I could simply redirect from there back to Nova as a temporary solution.

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
