### ISSUE TITLE
Nova index search loads wrong result set

### ISSUE THREAD

**Issue by marijoo** [laravel/nova-issues#2892]
- Laravel Version: 8.4.0
- Nova Version: 3.10.0
- PHP Version: 7.4.8
- Database Driver & Version:
- Operating System and Version: macOS 10.15.6
- Browser type and version: Chrome 85.0.4183.121

### Description:
When searching through a resources index, Nova will eventually load the wrong result set because of conflicting requests. It seems like sometimes the results are overridden by the result set of a keyup event triggered earlier while typing the search query. The expected results only flashes for a second.

The behavior can be seen here, where `137` would match 7 records whereas `1378` would match exactly one record.

![Sep-23-2020 14-33-49](https://user-images.githubusercontent.com/360736/94013140-f205fb00-fda9-11ea-8c76-e95378f7ea4e.gif)

In the example above it is also noticeable that the total record count is updated correctly so that under the table it says `1-7 of 1` instead of the expected `1-1 of 1`.

### Detailed steps to reproduce the issue on a fresh Nova installation:
With a larger set of data, where queries might take some time, quickly type a search query where the first part of the query would match a larger result set than the expected one.

**Comment by Dontorpedo** [comment]
same for me, especially with a larger set of data when i dont input the query fast enough.

**Comment by davidhemphill** [comment]
One reason we've avoided adding this is Promise cancellation proposal was withdrawn. However, Axios does support it so I'll look into adding it in a future version.

**Comment by marijoo** [comment]
This seems to happen when filtering in Lenses also and is quite annoying. Any updates on this one?

**Comment by jeffreydevreede** [comment]
I have seen similar behavior in other paginated table plugins. 
An easy way I've seen this been fixed is add a counter to the requests, so for example:

- first long request -> number 1
- second quick request -> number 2
- second quick request comes back -> result from number 2 is shown.
- first long request comes back -> number 1 is lower then number 2, so this result is ignored.
