### ISSUE TITLE
Problem when using "Inline Relations" with BelongsTo Field and Image Fields

### ISSUE THREAD

**Issue by bhensonweb** [laravel/nova-issues#2896]
- Laravel Version: 8.6.0
- Nova Version: 3.10.0
- PHP Version: 7.4.4
- Database Driver & Version: Ver 14.14 Distrib 5.7.29, for Linux (x86_64) using  EditLine wrapper
- Operating System and Version: Mac OS 10.15.6
- Browser type and version: Chrome 85.0.4183.102
- Reproduction Repository: https://github.com/###/###

### Description:

This occurs when:

When creating/editing a Nova Resource which includes an Image Field and BelongsTo Field. 

When the BelongsTo Field is utilizing "Inline Relations" feature via "showCreateRelationButton" method.

And when the Inline Relationship Resource also includes an Image Field.

Then upon clicking the Inline Relationship field the overlay opens as it should but when clicking "choose file" the overlay closes, and the chosen file gets placed into the parent's Image field instead of within the overlay. No Inline Resource is created.

If the Parent Resource is then created, it does actually use the image that was intended for the Inline Resource.

**Comment by regiszanandrea** [comment]
Hi @davidhemphill , I had this bug with MorphTo Field too. 

Is there a prevision to this be fixed?

**Comment by crynobone** [comment]
Just an update, I'm already working on a fix but will need to work on dusk tests to ensure that it does really work as expected.
