### ISSUE TITLE
Multiple panels in edit too

### ISSUE THREAD

**Issue by cloudstudio** [laravel/nova-issues#29]
Hey ! we can create multiple panels, but just in show view, could be nice if this work in edit too.

It would be nice to have it also separated into panels when editing, so you can make more beautiful / usable panels.

Thanks guys !

![edit](https://user-images.githubusercontent.com/3589377/44536201-3bcc1500-a6fc-11e8-8cf4-609c0f1a0dcb.png)
![show](https://user-images.githubusercontent.com/3589377/44536204-3bcc1500-a6fc-11e8-9712-9635a1eda718.png)

**Comment by MattMangoni** [comment]
This would be awesome.

**Comment by Stuart-vuejazzle** [comment]
It would be great if you could also define side panels, that sit on the right hand side and take up about 20% width or less.
I think it would work well for something like a status select box that doesn't need the width of main fields.

**Comment by stuartmccord** [comment]
It would be great if you could also define side panels, that sit on the right hand side and take up about 20% width or less.
I think it would work well for something like a status select box that doesn't need the width of main fields.

**Comment by FreekVR** [comment]
+1 for this, especially nice for really large models. Perhaps even make them collapsible in the process?

**Comment by kayyyy** [comment]
Not just in edit mode, also for the create mode it would be nice to have those panels 👍

**Comment by cloudstudio** [comment]
@kayyyy yep ! i mind in all modes :P

Maybe in the future, but tabs / cards / side / sizes, could be perfect, i think with this 4 options, we can make beautiful views.

**Comment by taylorotwell** [comment]
This repository is for tracking bugs. Feature requests may be emailed to Nova customer support.

**Comment by Andy-Baker** [comment]
Would be nice to have a public area for feature requests.

**Comment by dillingham** [comment]
Also maybe relations https://github.com/laravel/nova-issues/issues/338

**Comment by MarouaneSH** [comment]
+1, I need this to

**Comment by avs262** [comment]
+1

**Comment by cloudstudio** [comment]
@bonzai @davidhemphill hello ! news about this ? its planed since Aug, any chance ? :P

Thanks !

**Comment by nenads** [comment]
+1

**Comment by kirya-dev** [comment]
+1

**Comment by carloshc** [comment]
+1

**Comment by wimurk** [comment]
+1 awesome

**Comment by rikless** [comment]
+1

**Comment by David-Griffiths** [comment]
+1

**Comment by tripex** [comment]
Is this implemented or still just planned?

**Comment by kirya-dev** [comment]
> Is this implemented or still just planned?

seems they simple added special Element named as Heading

**Comment by christophrumpel** [comment]
+1 for having the panels on edit and create as well.

**Comment by ilikourou** [comment]
+1 for panels on edit/create pages.

**Comment by christophrumpel** [comment]
+ 1 for panels on edit view as well.

It also gets a problem when using Panels + Heading fields for the details view, because on the edit view only the Heading fields will be shown, which often doesn't make sense anymore because of the missing grouping headline with the Panel names.

**Comment by kgp43** [comment]
+1 for panels on edit/create pages.

**Comment by preliot** [comment]
+1, would make allot of sense.

I use panels to seperate information, looks great on a detail screen. When i try to edit this information, Panels are ignored and one big screen is shown. This is troublesome, because i group information with a title. This is what i mean:

Variable Orgizational Structure

...
Locations: true
Departments: true
...

On my detailscreen this works perfectly. However when i edit this information, the panel (with header) is missing and the options as standalone items don't make any sense.

Proposal

Use panels on edit screen or give developer an option to do so, for example: ->withPanels()

**Comment by bolechen** [comment]
I use the `eminiarts/nova-tabs` package(https://github.com/eminiarts/nova-tabs) to achieve this method, this package can spilt fields into different tabs like this:


![](https://user-images.githubusercontent.com/3426944/51790797-055a6080-219a-11e9-8da4-33a621093265.png)

**Comment by christophrumpel** [comment]
Oh, that's interesting. Need to give it a try. Wonder how it behaves with validation errors. (Showing them on the current tab, switches tab etc.)

**Comment by preliot** [comment]
> I use the `eminiarts/nova-tabs` package(https://github.com/eminiarts/nova-tabs) to achieve this method, this package can spilt fields into different tabs like this:
> 
> ![](https://user-images.githubusercontent.com/3426944/51790797-055a6080-219a-11e9-8da4-33a621093265.png)

@bolechen Tried it yesterday in latest Nova, but it did only work on the detail screen. My edit screen looked the same as the default nova panels. Strange.

**Comment by christophrumpel** [comment]
It also works in edit view: https://github.com/eminiarts/nova-tabs#tabs-on-edit-view

**Comment by preliot** [comment]
> It also works in edit view: https://github.com/eminiarts/nova-tabs#tabs-on-edit-view

My mistake. Missed the part where i had to explicitly add a trait:  use Eminiarts\Tabs\TabsOnEdit;

**Comment by ArmeniaH** [comment]
bump

**Comment by gavinhewitt** [comment]
It's been more than a year. Any news on this?

**Comment by kirya-dev** [comment]
Im invented own kirya-dev/admin with panels. Its working good for me

**Comment by gavinhewitt** [comment]
> Im invented own kirya-dev/admin with panels. Its working good for me

That is awesome... for you. It doesn't solve anything for Nova.
