### ISSUE TITLE
Boolean field always shows false in table view

### ISSUE THREAD

**Issue by nsbucky** [laravel/nova-issues#290]
I have a pivot table that has a tinyInt colum.  That field is displayed using:

`Boolean::make('Required'),`

When the value is displayed in a table view, it always show the red dot (which I assume means false), for both 0 and 1 values in the column.

**Comment by jwahdatehagh** [comment]
I can confirm.

**Comment by jwahdatehagh** [comment]
It seems the field values are not loaded properly. If i register it as a `Text`-field, it's value is `null`.

**Comment by davidhemphill** [comment]
I'm not able to replicate this issue on the current build with the information provided.
