### ISSUE TITLE
Input fields do not emit global events but text fields do, why?

### ISSUE THREAD

**Issue by jonasbrenig** [laravel/nova-issues#2900]
- Laravel Version: 7.23.1
- Nova Version: 3.9.1
- PHP Version: 7.4.8
- Database Driver & Version: MySql 8.0
- Operating System and Version: Ubuntu 18.04.5 LTS
- Browser type and version: 85.0.4183.121 (Official Build) (64-bit)
- Reproduction Repository: /

### Description:

First of all: Thank you for Nova, it helps is make progress a lot faster and focus on the more important things.

**tldr:**  _Text field emits global Nova event, but Select field does not._

I am working on a custom field that want's to listen to other fields and calculate things on the client side.
For that I looked into vue dev tools events and noticed that Nova conveniently emits events on every field natively.
So I thought that I could just listen to them. And that is partially true.
Since the [Form Field](https://github.com/laravel/nova-js/blob/master/src/mixins/FormField.js#L57) emits global events through the `handleChange()` function I can listen to events like this:

```js
Nova.$on("title-change", function (message) {
    console.log("title changed to: " + message);
});
```

But the [BelongsTo Field](https://github.com/laravel/nova/blob/3.0/resources/js/components/Controls/SelectControl.vue#L40) does not emit this event globally. It just emits a "normal" event that can not be fetched by Nova. (or I don't know how).

I was super excited when I found out that I could fetch the value of Text fields and instantly assumed that this should be available for all fields, but unfortunately it is not.
I suggest to just call the `handleChange()` function in all fields or emit the global Nova event in a different way to allow for very powerful client-side tools.
This could be as simple as mirroring the value from another field but this gives a lot of new options to nova.

Thank you for your support in advance.

### Detailed steps to reproduce the issue on a fresh Nova installation:

- install Laravel and Laravel Nova
- add a Text Field and a Select Field to a resource
- open the `/nova/resources/resource_name/new`
- open vue dev tools event tab
- type into the text field and see a global event
- select an option from the select dropwon and only finda "normal" event

make vue dev tools visible by:
```shell
cd ./vendor/laravel/nova
mv webpack.mix.js.dist webpack.mix.js
npm install
npm run dev
rm -rf node_modules
cd -
php artisan nova:publish
```

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍

**Comment by jonasbrenig** [comment]
@davidhemphill Thanks a lot for that fast fix and realease.
This is really powerful. :-)
