### ISSUE TITLE
"npm run dev" to enable Vue Devtools shows error

### ISSUE THREAD

**Issue by MdMostaFizurRahaman** [laravel/nova-issues#2901]
I can not run npm run dev to enable Vue Devtools is shows some error:

10% building modules 2/2 modules 0 active
<--- Last few GCs --->
8)[21112:0000018CC026ED70]   339386 ms: Mark-sweep 2053.7 (2058.7) -> 2050.2 (2059.7) MB, 441.8 / 0.0 ms  (+ 434.4 ms in 93 steps since start of marking, biggest step 7.5 ms, walltime since start of marking 969 ms) (average mu = 0.172, current mu = 0.097) a[21112:0000018CC026ED70]   340185 ms: Mark-sweep 2054.6 (2059.7) -> 2041.2 (2055.2) MB, 499.9 / 0.0 ms  (+ 281.8 ms in 66 steps since start of marking, biggest step 9.3 ms, walltime since start of marking 799 ms) (average mu = 0.107, current mu = 0.021) a

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 00007FF70EC6978D]
    1: StubFrame [pc: 00007FF70EC6B29B]
    2: StubFrame [pc: 00007FF70EC490BC]
Security context: 0x03bf1e2808d1 <JSObject>
    3: split [000003BF1E28EBC1](this=0x015180ac4959 <Very long string[13863]>,0x015180ac4921 <JSRegExp <String[#9]: (\\+|\/+)>>)
    4: join [000000D244136D71] [C:\laragon\www\easystore\nova\node_modules\memory-fs\lib\join.js:~6] [pc=00000380786F2E66](this=0x0236c5b41b09 <JSGlo...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF70E0551EF napi_wrap+114271
 2: 00007FF70DFFFE66 v8::base::CPU::has_sse+66630
 3: 00007FF70E000C66 v8::base::CPU::has_sse+70214
 4: 00007FF70E81522E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF70E7FD301 v8::SharedArrayBuffer::Externalize+833
 6: 00007FF70E6C983C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1436
 7: 00007FF70E6D4A70 v8::internal::Heap::ProtectUnprotectedMemoryChunks+1312
 8: 00007FF70E6D1594 v8::internal::Heap::PageFlagsAreConsistent+3204
 9: 00007FF70E6C6D93 v8::internal::Heap::CollectGarbage+1283
10: 00007FF70E6C5404 v8::internal::Heap::AddRetainedMap+2452
11: 00007FF70E6E660D v8::internal::Factory::NewFillerObject+61
12: 00007FF70E44CCA1 v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+1665
13: 00007FF70EC6978D v8::internal::SetupIsolateDelegate::SetupHeap+546637
14: 00007FF70EC6B29B v8::internal::SetupIsolateDelegate::SetupHeap+553563
15: 00007FF70EC490BC v8::internal::SetupIsolateDelegate::SetupHeap+413820
16: 00007FF70EC56D72 v8::internal::SetupIsolateDelegate::SetupHeap+470322
17: 00000380786F2E66
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2020-09-26T14_14_36_388Z-debug.log

-Node Version: 12.18.1
-NPM Version: .14.5
-Nova Version: 3.8.2

**Comment by davidhemphill** [comment]
This is an out of memory error. Enabling Vue Devtools should not cause this. Without more information, this would be impossible for us to diagnose.
