### ISSUE TITLE
BelongsToMany - Cannot read property 'preventFormAbandonment' of undefined 

### ISSUE THREAD

**Issue by bredisvictor** [laravel/nova-issues#2903]
- Laravel Version: 7.28.3
- Nova Version: 3.10.0
- PHP Version: 7.4.2

### Description:

1. When changing relation attachment, appears error in console `Cannot read property 'preventFormAbandonment' of undefined`
 <img width="1502" alt="Screen Shot 2020-09-28 at 1 38 53 PM" src="https://user-images.githubusercontent.com/24625107/94422574-fa867900-018f-11eb-9d83-2b96521901a8.png">

2. The second issue is when trying to attach relation that already have been attached from before, validation error message didn't appear to user, nothing not happen but error throwing to the console
<img width="1506" alt="Screen Shot 2020-09-28 at 1 49 51 PM" src="https://user-images.githubusercontent.com/24625107/94423559-7cc36d00-0191-11eb-8555-c858ecc565ea.png">

**Comment by dgoldstein89** [comment]
Experiencing the same issue

**Comment by dgoldstein89** [comment]
I'm experiencing the same issues. It looks like `this.resourceInformation` is `undefined`. 
To elaborate on the 2nd issue, no messages are displayed (error and success).

**Comment by crynobone** [comment]
Managed to replicate this issue while migrating nova-dusk-suite. Sending PR soon.
