### ISSUE TITLE
Enabling polling for resource index closes modals

### ISSUE THREAD

**Issue by kohutovic** [laravel/nova-issues#2904]
- Laravel Version: 8.6.0
- Nova Version: 3.10.0
- PHP Version: 7.4

### Description:
When a polling listener rerenders the index for a resource it closes all opened modals (for actions for example)

### Detailed steps to reproduce the issue on a fresh Nova installation:
- enable polling on a resource
- open action dialog
- wait until page index reloads

**Comment by vesper8** [comment]
Also this new auto-polling feature is currently undocumented
