### ISSUE TITLE
Select resources on resource index and paging

### ISSUE THREAD

**Issue by gkermer** [laravel/nova-issues#2905]
- Laravel Version: 7.28.3
- Nova Version: 3.10.0
- PHP Version: 7.2

### Description:
When you want to select resources on a page, the selection is lost when you switch the page. You are not able to execute a Nova action with selected resources from over several pages.

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Go to resource index
2. Select some resources on page 1
3. Switch to page 2
4. Switch back to page 1

The selection from step 2 is lost. Is this the expected behaviour?

**Comment by davidhemphill** [comment]
Yes, it is not designed to keep the current selection when switching pages.
