### ISSUE TITLE
Inconsistence between filter and select options

### ISSUE THREAD

**Issue by LTroya** [laravel/nova-issues#2907]
- Laravel Version: 8.6.0
- Nova Version: 3.11.0
- PHP Version: 7.4
- Database Driver & Version: Postgres 12.3
- Operating System and Version: MacOsx 10.15
- Browser type and version: Chrome 85
- Reproduction Repository: N/A

### Description:

I don't know if this is the desired behavior but it looks like the select component uses `key` as `value` and the `value` as `label` of an associative array

For this array: 

```
const TYPE_VALUES = [
        self::CLIENT => 'Client',
        self::EMPLOYEE => 'Employee',
        self::PROVIDER => 'Provider'
    ];

# Nova field configuration
Select::make('Type')->options(\App\Models\Person::TYPE_VALUES)
```

This is the ouput for the previous select:

![image](https://user-images.githubusercontent.com/6491259/94600227-38020980-0257-11eb-897c-3a08887f6056.png)

In other hand, for the filter options, for the same array I received the followed output:

![image](https://user-images.githubusercontent.com/53018851/94599222-c4133180-0255-11eb-9b63-5a76c6108412.png)

It will be great if I could use the `TYPE_VALUES` for those two options

### Detailed steps to reproduce the issue on a fresh Nova installation:

Create a person model:

`php artisan make:model Person -m`

Add the following fields on people migration:

```
$table->string('name');
$table->string('type');
```

Create this variable in `Person` model:

```
const TYPE_VALUES = [
        self::CLIENT => 'Client',
        self::EMPLOYEE => 'Employee',
        self::PROVIDER => 'Provider'
    ];
```

Create a nova resource:

```
php artisan nova:resource Person
```

Add the following fields: 

```
Select::make('Type')->options(\App\Models\Person::TYPE_VALUES),
Text::make('Name'),
```

Then, create a filter for this resource:

```
php artisan nova:filter PersonType
```

Add the following options:

```
return Person::TYPE_VALUES;
```

Hope you can reproduce it

**Comment by davidhemphill** [comment]
This is the way it was designed, but even if we wanted to change it now, it would be a breaking change.

**Comment by crynobone** [comment]
Changing the structure above will limit filter usability to `string` or `integer` value. I believe you can solve this right now by using `array_flip()`.

```php
    /**
     * Get the filter's available options.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function options(Request $request)
    {
        return array_flip(Person::TYPE_VALUES;
    }
```

**Comment by LFTroya** [comment]
@crynobone Oh, thanks. I didn't know that options
