### ISSUE TITLE
Nova broken due to variable reference error

### ISSUE THREAD

**Issue by ragingdave** [laravel/nova-issues#2908]
- Laravel Version: 8.7
- Nova Version: 3.11
- PHP Version: 7.4

### Description:
Upon Updating I was greeted by:
Undefined class constant 'searchable'
vendor/laravel/nova/src/Resource.php:264 
It seems that a recent update has changed the reference style to the $searchable static variable causing this issue

### Detailed steps to reproduce the issue on a fresh Nova installation:
Install the latest version, and try and load Nova with a resource....that's basically it

**Comment by davidhemphill** [comment]
Just fixed it and pushed a patch release!
