### ISSUE TITLE
This image could not be found.

### ISSUE THREAD

**Issue by Livijn** [laravel/nova-issues#291]
I have an image field in my DB which I am displaying using 

```
Avatar::make('image')
    ->disk('s3'),
```

It works well on the Index, however when browsing specific users, I receive this error: 
`Failed to load https://xxx.s3.eu-west-2.amazonaws.com/users/famous-people-copd-02.jpg: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://xxx.test' is therefore not allowed access.`

Here is how it looks on the [User Index](https://gyazo.com/6324eb66d7aeb40197fb9b4b95c3b8bc) and here is the error on [User Details](https://gyazo.com/ce7257172cc519da7ca110e27e144047).

Why is it not working with the remote image when on details? I checked #209 which is similar, however the image *should* be on another host.

**Comment by bonzai** [comment]
#150

**Comment by garrettbland** [comment]
@Livijn I resolve the issue by following the accepted answer here

[https://stackoverflow.com/questions/17533888/s3-access-control-allow-origin-header](https://stackoverflow.com/questions/17533888/s3-access-control-allow-origin-header)

**Comment by davidhemphill** [comment]
You have to allow CORS on your S3 bucket.
