### ISSUE TITLE
Image Field Get File With http://localhost In The URL

### ISSUE THREAD

**Issue by namnh06** [laravel/nova-issues#2911]
- Laravel Version: 8.x.x
- Nova Version: 3.x.x
- PHP Version: 7.4.x
- Database Driver & Version: MySQL 5.7
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:
Uploaded & stored the image to the localhost server, saved the image name in Database.
When loaded to the website, the HTTP://localhost was added into the URL of the file.

The Field:
```
 Image::make('Photo', 'photo_url')
                ->disk('user')
                ->hideFromIndex(),
```

The filesystem.php
```
  'user' => [
            'driver' => 'local',
            'root' => storage_path('app/public/user'),
            'url' => env('APP_URL') . '/storage/user',
            'visibility' => 'public',
        ],
```

The .env
```
APP_URL=
```
Stored and saved in the DB with the name. I could find it via a link, for example, `http://localhost/storage/user/85GtYgx9RbznjRYQYXQ4hL4zvFXTMUgThbdS1LkG.png`

The problem is it shows up
`http://localhost/storage/user/http://localhost/388UEn6tLxecb6EmchFuG8lsgVX5B8hUuGGubRGw.png`

So, it can't load the image.

**Comment by crynobone** [comment]
I was unable to replicate the issue based on https://github.com/nova-issues/issue-2911/commit/f24e832f56d8da0ba210356444a08a9d8f4c3a9d

![CleanShot 2020-10-26 at 12 09 38](https://user-images.githubusercontent.com/172966/97133283-6c001a00-1784-11eb-872e-d0d920b92940.gif)

**Comment by namnh06** [comment]
Thanks for your help @crynobone,
Hmm, looks weird from my side, I really don't know what happened.
I think I have record my screen.

**Comment by crynobone** [comment]
Closing this for now, but feel free to reopen a new issue with reproducing code.

**Comment by namnh06** [comment]
Hi @crynobone , thank you for your help & sorry for the delay, please look at the images below:

1. As you can see, the URL is not normal, it's `localhost/storage/http://localhost/4SMdmOmb5vap3R66OThLizyzIoQv0pFU4v5FrbcI.png`
![avatar-url](https://user-images.githubusercontent.com/28762252/99233566-fbe63080-2825-11eb-8a7b-caeedf8ce397.png)


2. This is my field in Nova:
![avatar-nova](https://user-images.githubusercontent.com/28762252/99233583-030d3e80-2826-11eb-8dd2-5ea84c241563.png)

3. This is from DB:
![avatar-db](https://user-images.githubusercontent.com/28762252/99233596-086a8900-2826-11eb-8a90-3ce18684d6c6.png)

4. This is in the storage folder
![avatar-storage](https://user-images.githubusercontent.com/28762252/99233614-0ef90080-2826-11eb-9aee-637d46d52811.png)

Could you please help me out? Please let me if you need any images from my project.

**Comment by crynobone** [comment]
> Could you please help me out? Please let me if you need any images from my project.

This seem to be a configuration issue rather than Laravel Nova bug. Unable to help except can only recommends:

* Set `APP_URL=http://localhost` instead of `APP_URL=`
* Run `php artisan storage:link`
* Verify that other app configuration changes doesn't cause any issue (I tested with basic configuration and can't replicate the issue).

**Comment by Sohail-purelogics** [comment]
Having the same issue on my side. trying to upload the file to the s3 bucket the file uploads but when showing on detail view it is added site URL before was s3 URL. have you found the solution?
