### ISSUE TITLE
BelongsToMany | TypeError: Cannot read property 'attribute' of null

### ISSUE THREAD

**Issue by StanBarrows** [laravel/nova-issues#2914]
- Laravel Version: 8.7.1
- Nova Version: 3.11.1
- PHP Version: 7.4.10
- Database Driver & Version: MySQL 5.7.31
- Operating System and Version: **Lando** | https://docs.lando.dev/config/laravel.html
- Browser type and version: Chrome & Safari
- Reproduction Repository: https://github.com/StanBarrows/nova-bug

### Description:
- It looks like the BelongsToMany Relationship is broken.

`TypeError: Cannot read property 'attribute' of null
`

![image](https://user-images.githubusercontent.com/10268813/94768100-af967c80-03ae-11eb-8eaa-96c760c23e62.png)

### Detailed steps to reproduce the issue on a fresh Nova installation:

- Install Nova via composer
- Create User <=> Client Relation
- Create a User Model (BelongsToMany => Client)
- Create a Client Model (BelongsToMany =>User)

**User**
```
  public function clients()
    {
        return $this->belongsToMany(Client::class)->withTimestamps();
    }
```

**Client**
```
 public function clients()
    {
        return $this->belongsToMany(Client::class)->withTimestamps();
    }
```

**In Nova** 

`BelongsToMany::make('Users'),
  BelongsToMany::make('Clients'),
`

Try to attach new Clients to the Users model.

![image](https://user-images.githubusercontent.com/10268813/94767865-06e81d00-03ae-11eb-9bfc-18014667d619.png)

### Reproduction Repository
I've created a fresh Laravel Nova setup where the error is reproducible 

https://github.com/StanBarrows/nova-bug

**Installation steps**
- lando start (only if you use Lando)
- cp .env.example .env
- update .env values
- add a auth.json with your Nova configuration or use a different auth method

```
{
  "http-basic": {
    "nova.laravel.com": {
      "username": "EMAIL",
      "password": "API_TOKEN"
    }
  }
}

```
- composer install
- php artisan migrate:fresh 
- php artisan nova:user

**Comment by instanceofman** [comment]
I got the same issue with MorphToMany

**Comment by chelev** [comment]
Getting exactly the same issue with both on BelongsToMany and MorphToMany

Laravel Version: 8.7.1
Nova Version: 3.11.1
PHP Version: 7.4.10

**Comment by charlielangridge** [comment]
I've got the same issue running 
Laravel Version: 8.7.2
Nova Version: 3.11.1
PHP Version: 7.4.10
on Laragon on Win10

**Comment by brensondevalfa** [comment]
Yes same problem in my project.

**Comment by davidhemphill** [comment]
There's a fix coming out this morning :-)

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍

**Comment by davidhemphill** [comment]
@StanBarrows Appreciate the kind tone in your question!

This is actually something that's been on my mind the past few months and something we are actively working on at the moment. Admittedly, our front-end testing is not comprehensive enough. Our Dusk test suite does not run when our unit tests do...only when we think about doing it. So we're working on rectifying that. As a result, our front-end will be a lot more stable in the coming weeks.

**Comment by brensondevalfa** [comment]
When we can expect next release?

**Comment by alshf89** [comment]
Same issue here with nova 3.11.1 and php 7.4.

**Comment by pelmered** [comment]
I had the same issue, but updating to `v3.12.0` fixed this. Thanks!

See: https://nova.laravel.com/releases/3.12.0
> Fixed an issue with BelongsTo fields and default values. #983

**Comment by ryanzzeng** [comment]
I still got the issue even I have updated to `v3.12.1`, do you guys know how to fix it? 

![image](https://user-images.githubusercontent.com/21005264/95697223-b2844d80-0c89-11eb-8848-28935d483080.png)

**Comment by alshf89** [comment]
@ryanzzeng try to remove cached views. I had same issue on 3.11 but today I updated to 3.12.1 and its working ...

**Comment by BenySLO** [comment]
**Always be sure to run `php artisan nova:publish` after upgrading to update Nova's JavaScript and CSS assets.**
this solved my problem
