### ISSUE TITLE
Adding total of a column on index view

### ISSUE THREAD

**Issue by MdMostaFizurRahaman** [laravel/nova-issues#2916]
Hey there! If it is possible to add total of a column to the footer of the table of any index view, it will be very good for us. So there is a request to add this feature to next nova update if possible.

I think there is a way of show total of a column by using card or metrics. But some cases it is better to show the total on the footer of the table.

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
