### ISSUE TITLE
runCommand() should be compatible with ::runCommand()

### ISSUE THREAD

**Issue by aalicki** [laravel/nova-issues#2917]
- Laravel Version: 6.18.41
- Nova Version: 2.0
- PHP Version: 7.2
- Database Driver & Version: MySQL
- Operating System and Version: Mac OS Catilina (v 10.15.6)
- Browser type and version: Firefox 81
- Reproduction Repository: https://github.com/###/###

### Description:

When attempting to upgrade from Laravel 5.8 to Laravel 6.x, I am receiving the following error after running either `composer install` or `compser update`:

```
ErrorException  : Declaration of Laravel\Nova\Console\AssetCommand::runCommand($command, $path) should be compatible with Illuminate\Console\Command::runCommand($command, array $arguments, Symfony\Component\Console\Output\OutputInterface $output)
```

### Detailed steps to reproduce the issue on a fresh Nova installation:
Running `composer install` or `compser update` will trigger this issue. This can also be triggered by running `composer require` for a new package.

**Comment by davidhemphill** [comment]
Unfortunately, Nova 2.x is no longer supported. I'm not sure why this error would affect your application (we've not seen it reported before), but you should try upgrading to 3.x.
