### ISSUE TITLE
BelongsToMany - TypeError: Cannot read property 'attribute' of null

### ISSUE THREAD

**Issue by bredisvictor** [laravel/nova-issues#2918]
- Laravel Version: 7.28.3
- Nova Version: 3.11.1
- PHP Version: 7.4.2
- Database Driver & Version: MySQL 5.7.26
- Operating System and Version: Mac OS
- Browser type and version: Chrome 85.0.4183.121

### Description:
`BelongsToMany` relation didn't work, cannot attach, detach. Appear error in console `TypeError: Cannot read property 'attribute' of null`

<img width="1511" alt="Screen Shot 2020-10-01 at 9 33 57 PM" src="https://user-images.githubusercontent.com/24625107/94849346-eeb7e280-042d-11eb-8640-d8aca333d1d2.png">

**Comment by yevhenkoriakin** [comment]
Same problem

use v3.10.0 
after v3.11.0  `BelongsToMany` relation didn't work

**Comment by yevhenkoriakin** [comment]
@davidhemphill @jbrooksuk  @taylorotwell  please fix it

**Comment by smartens80** [comment]
Bump

**Comment by crynobone** [comment]
This has been fixed in 3.x branch waiting for next release. PR laravel/nova#992
