### ISSUE TITLE
[Feature Request] Add withoutConfirmation() to actions

### ISSUE THREAD

**Issue by vesper8** [laravel/nova-issues#2919]
I understand that it's generally bad UX to have something performed immediately after selecting an item from a dropdown, but I have a use case where this is precisely what I want. I am using inline actions through showOnTableRow() and I want to perform non-destructive actions immediately upon clicking on them, without having to see a modal and click the 'confirm' button. It's fine and dandy that this remains the default behaviour but adding a simple withoutConfirmation() option to the actions would add more flexibility and reduce the number of necessary clicks in some cases where it makes sense.

Thanks

**Comment by vesper8** [comment]
Oh.. I see this actually already exists https://github.com/laravel/nova/blob/c21365694cbcd4002d7a5225f683ff26dae4f989/src/Actions/Action.php#L533

And it's called `->withoutConfirmation()` too

Just tested it.. works perfectly.. I can't find it anywhere in the documentation however.. this should be documented

Cheers

**Comment by davidhemphill** [comment]
added to the docs 👍
