### ISSUE TITLE
Nova Changing File Extensions on Uploaded Files

### ISSUE THREAD

**Issue by mddickens** [laravel/nova-issues#2922]
- Laravel Version: 8.7.1
- Nova Version: 3.10.0
- PHP Version: 7.4.11

### Description:

When uploading an Adobe Illustrator file, Nova changes the file extension to 'pdf' from 'ai'. This makes it impossible to retrieve later. Nova needs to leave the file extension alonw

### Detailed steps to reproduce the issue on a fresh Nova installation:

Upload an 'ai' file on either the Image or File field type

**Comment by crynobone** [comment]
> This makes it impossible to retrieve later. Nova needs to leave the file extension alone.

By default Laravel uses Symfony MimeGuesser to validate and determine upload file extension. This is not done by Nova. 

![Screenshot 2020-10-05 at 3 38 23 PM](https://user-images.githubusercontent.com/172966/95052098-ea871000-0720-11eb-97ba-3dcb22c89eda.png)

One quick solution that I can give at the moment is to extends `storeAs()` and hardcode the `ai` as the extension file.

```php
           File::make('File')
                ->creationRules('required')
                ->disk(config('filesystems.default'))
                ->storeOriginalName('file_name')
                ->storeSize('file_size')
                ->storeAs(function (Request $request) {
                    return sha1($request->file->getClientOriginalName()).'.ai';
                }),
```
