### ISSUE TITLE
unable to access parent resource inside action handle method on many-to-many relation

### ISSUE THREAD

**Issue by vesper8** [laravel/nova-issues#2924]
I have a Feed model that has a many-to-many relation to a Channel model using a pivot table.

When viewing a Feed page in Nova, I can see its multiple channels listed. I have inline actions (that use `->withoutConfirmation()`)

When I perform my inline action, inside the actions `handle()` method, I am unable to reference my parent Feed ID

I have tried passing the $feed object (or its ID) to the Action constructor, this works however the passed value is no longer available inside the `handle()` method

I have also tried accessing the feedId value from the request using `request('viaResourceId')`

Again this fails because this is only accessible at first, but when you actually execute the action it is no longer part of the request

Is there a way to access the parent model inside the action's `handle` method? Or is there a way to pass variables to the action such as a `withData()` on the action?

**Comment by vesper8** [comment]
I've worked around by adding this super hacky way.. in my Feed resource I added

```
    public function __construct($resource)
    {
        \Cache::forever(auth()->user()->id() . `-current-feed`, request()->input('viaResourceId'));

        parent::__construct($resource);
    }
```

And then later in my channel inline-action I can reference the feedId using `$feedId = \Cache::get(auth()->user()->id() . `-current-feed`);`

But this is very hacky and it would cause a problem if a user had two tabs opened and was working with two different feeds at the same time

**Comment by crynobone** [comment]
You could do the following:

```php
<?php

namespace App\Nova\Actions;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Support\Collection;
use Laravel\Nova\Actions\Action;
use Laravel\Nova\Fields\ActionFields;
use Laravel\Nova\Http\Requests\ActionRequest;

class LogParentResourceId extends Action
{
    use InteractsWithQueue, Queueable;

    /**
     * Get the parent resource ID.
     *
     * @var int|null
     */
    public $parentResourceId;

    /**
     * Execute the action for the given request.
     *
     * @param  \Laravel\Nova\Http\Requests\ActionRequest  $request
     * @return mixed
     * @throws MissingActionHandlerException
     */
    public function handleRequest(ActionRequest $request)
    {
        $this->parentResourceId = $request->viaResourceId ?? null;

        return parent::handleRequest($request);
    }

    /**
     * Perform the action on the given models.
     *
     * @param  \Laravel\Nova\Fields\ActionFields  $fields
     * @param  \Illuminate\Support\Collection  $models
     * @return mixed
     */
    public function handle(ActionFields $fields, Collection $models)
    {
        info('Parent resource id: '.$this->parentResourceId);
    }

    /**
     * Get the fields available on the action.
     *
     * @return array
     */
    public function fields()
    {
        return [];
    }
}
```
