### ISSUE TITLE
NovaServiceProvider return cards 

### ISSUE THREAD

**Issue by niunaiyi** [laravel/nova-issues#2925]
once I click any resource menu , NovaServiceProvider return cards and tools serval times.
my Cards or Tools get Data from DB, it cost time too much.
looks like:
[2020-10-02 22:56:07] local.INFO: return cards   
[2020-10-02 22:56:07] local.INFO: return cards   
[2020-10-02 22:56:08] local.INFO: return cards   
[2020-10-02 22:56:08] local.INFO: return cards   
[2020-10-02 22:56:08] local.INFO: return cards   
[2020-10-02 22:56:08] local.INFO: return cards

**Comment by ahinkle** [comment]
Hi there,

More information would be helpful to help with your issue:

- What version of Nova are you using?
- What version of Laravel are you using?
- What does your NovaServiceProvider file look like?

**Comment by niunaiyi** [comment]
looks like this:

class NovaServiceProvider extends NovaApplicationServiceProvider
{

/**
 * Get the cards that should be displayed on the default Nova dashboard.
 *
 * @return array
 */
protected function cards()
{
	\Log::info('return cards');
	$data = getDataFromDB();
	$style = ...;
	$options = ...;
	return [
		(new LineChart())
		  ->title('title')
		  ->series($data, $style)
		  ->options($options)
		  ->width('full'),
	];
}
}

laravel:V8.8.0
laravel-nov:V3.11.1

**Comment by crynobone** [comment]
The structure is intentional based on Nova requirement. 

I would suggest you to defer calling database operation from `cards()`. Alternatively you can opt for `spatie/once` which is required by Nova but it will be consider as separate request on each ajax request.
