### ISSUE TITLE
hi, wanted to ask about action buttons

### ISSUE THREAD

**Issue by SerjoA** [laravel/nova-issues#2927]
i have made it so that i can add inline action buttons as i want that will reuse the action fields from nova
using  https://github.com/dillingham/nova-button/pull/41
i closed this pr since it included nova source files
my question is if i can do a pr using nova source code on the nova codebase 

i will show what i mean in this mov file, and pull request, if something is wrong plz tell me ill remove it if its not ok

example how to use on fields function :

Button::make('Deposit')
    ->style('success-outline')
    ->action(DepositToPlayer::class),

that way it will reuse fields and all logic from action class

mov file is in the pull request

**Comment by davidhemphill** [comment]
You may not publish the Nova source code as that's a violation of our Terms. :-)

**Comment by SerjoA** [comment]
iam trying to delete it now , but overall this is not something that of interest to make the button reuse action class?
