### ISSUE TITLE
Jetstream Support

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#2928]
Would be mind blowing if the Vue components that power Jetstream were enabled within Nova.

![Frame 1 (1)](https://user-images.githubusercontent.com/29180903/95027263-2bb9ea00-0665-11eb-88e2-711a571a173d.png)

**Comment by ahinkle** [comment]
Have any examples that would directly provide a benefit?

**Comment by dillingham** [comment]
@ahinkle log into vapor, basically the same experience.

For a solo dev this wouldn't be useful at all.

I worked on a nova panel that had 20 internal office users managing real estate.
Each were department heads with assistants etc.
Teams would of solved my average implementation.
Sessions, 2fa, changing of password would of also been useful.

While Nova remains a admin panel for developers..
This could add tons of benefit for other use cases.

I think it would make the auth side of Nova fully featured without the maintenance.

**Comment by SerjoA** [comment]
sorry for the q, but you are saying it's not possible to use Jetstream on nova views , like livewire?

**Comment by dillingham** [comment]
@SerjoA no I was just thinking it would be cool if when you install nova, jetstream's vue components were used (inertia stack) for your Nova security & user specific settings. The empty dropdown in Nova would then have all Jetstream's options.

**Comment by ahinkle** [comment]
For what it's worth, Taylor mentioned yesterday on a Livestream of a "Nova Overhaul". Not sure what that would include but stay tuned 👍

**Comment by dillingham** [comment]
@ahinkle yeah, Im very excited to see what they come up with.

**Comment by NanoCellWebDesign** [comment]
It would be nice but Jetstream and Nova are two separate products. I would assume this would be something you would have to do yourself or something the community would have to make and release as a 'Middle Man Package' of sorts.

Adding support for Jetstream out of the box to Nova would bloat it for people not using Jetstream, even if it is recommended to use it now.

**Comment by dillingham** [comment]
@NanoCellWebDesign with things like api and teams disabled by default.. it may very well remove bloat by not having an auth implementation maintained by the Nova project and folks can enable those features as they wish.

but you're right, if you're not using Jetstream.. would have to be disabled for the actual "non admin" app.

**Comment by NanoCellWebDesign** [comment]
@dillingham I think maybe that a separate package to connect the 2 would be best, might have to make that lol, then in that you could listen to the config of Jetstream and enable/disable the features seen in nova on the fly. That would a community addon package or an official addon package to complement nova, I think that would be the best implementation as there is no bloat using either on there own or both with no connectivity.

Or it could be that nova shipps with it but you have to use a nova equivalent to jetstreams --teams link --jetstream to add the resources.

**Comment by NanoCellWebDesign** [comment]
@dillingham i use jetstreams login for nova already, i made the nova/login redirect to /login then added a button on the dropdown to goto /nova. This forces the user to login via jetstream with f2a if enabled and then they can click the link to goto nova.

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
