### ISSUE TITLE
Request: Add sql syntax highlighting to Code field

### ISSUE THREAD

**Issue by vmitchell85** [laravel/nova-issues#293]
Would like for the Code field to be able to support sql.

The steps to do so would be:  
1. Importing the mode `import 'codemirror/mode/sql/sql'`
2. Passing in the correct mode (`text/x-sql`) to the `language` function

It would be nice to automatically convert a language of `sql` to the `text/x-sql` mode that CodeMirror needs.

Thanks for the awesome work! Loving Nova so far!

**Comment by davidhemphill** [comment]
This has been fixed and will be included in an upcoming release.
