### ISSUE TITLE
MorphToMany field error starting in Nova 3.11

### ISSUE THREAD

**Issue by ramcda** [laravel/nova-issues#2931]
- Laravel Version: 8.8.0
- Nova Version: 3.11.1
- PHP Version: 7.4.9
- Database Driver & Version: MariaDB 10.5.5
- Operating System and Version: Centos 7.7
- Browser type and version: All versions of Firefox & Chrome

### Description:
Beginning in 3.11 when changes were made to the MorphTo fields basic relationships functionality was broken.  Whenever you use the "Attach" functionality to attach a related model it blows up with a client error below.

**TypeError: this.field is null**
    clearSelection http://ct.itinnovative.com/vendor/nova/vendor.js?id=8337884d0b7b132299df:1
    initializeComponent http://ct.itinnovative.com/vendor/nova/app.js?id=9315b56b5fde09a69c70:1
    mounted http://ct.itinnovative.com/vendor/nova/app.js?id=9315b56b5fde09a69c70:1
    It http://ct.itinnovative.com/vendor/nova/vendor.js?id=8337884d0b7b132299df:1
    en http://ct.itinnovative.com/vendor/nova/vendor.js?id=8337884d0b7b132299df:1
    insert http://ct.itinnovative.com/vendor/nova/vendor.js?id=8337884d0b7b132299df:1
    It http://ct.itinnovative.com/vendor/nova/vendor.js?id=8337884d0b7b132299df:1
    n http://ct.itinnovative.com/vendor/nova/vendor.js?id=8337884d0b7b132299df:1
    x http://ct.itinnovative.com/vendor/nova/vendor.js?id=8337884d0b7b132299df:1
    Ii http://ct.itinnovative.com/vendor/nova/vendor.js?id=8337884d0b7b132299df:1
    _update http://ct.itinnovative.com/vendor/nova/vendor.js?id=8337884d0b7b132299df:1
    mount http://ct.itinnovative.com/vendor/nova/vendor.js?id=8337884d0b7b132299df:1
    get http://ct.itinnovative.com/vendor/nova/vendor.js?id=8337884d0b7b132299df:1
    run http://ct.itinnovative.com/vendor/nova/vendor.js?id=8337884d0b7b132299df:1
    fn http://ct.itinnovative.com/vendor/nova/vendor.js?id=8337884d0b7b132299df:1
    ee http://ct.itinnovative.com/vendor/nova/vendor.js?id=8337884d0b7b132299df:1
    Gt http://ct.itinnovative.com/vendor/nova/vendor.js?id=8337884d0b7b132299df:1
vendor.js:1:1039135

### Detailed steps to reproduce the issue on a fresh Nova installation:
This issue impacts all MorphToMany fields however the easiest way to reproduce is to install the nova-permissions package as shown below.

- composer require vyuldashev/nova-permission

- add the MorphToMany field below to your user resource
```php
use Laravel\Nova\Fields\MorphToMany;

public function fields(Request $request)
{
    return [
        //.....
        MorphToMany::make('Roles', 'roles', \Vyuldashev\NovaPermission\Role::class),
    ];
}
```
-- Click the "Attach Role" button from the user detail page and it should blow up with the error stack above.  Again this seems to impact all MorphToMany fields not just this one.
- Open up one of your users and

**Comment by jkudish** [comment]
I'm seeing this with `BelongsToMany` fields as well

**Comment by jkudish** [comment]
According to https://github.com/laravel/nova-issues/issues/2918, this has been fixed in 3.x branch waiting for next release. PR laravel/nova#992

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
