### ISSUE TITLE
Handling of GlobalScopes within Nova

### ISSUE THREAD

**Issue by spekulatius** [laravel/nova-issues#2934]
Hey @ahinkle and @crynobone,

I'm using global scopes to filter models in my application. I was wondering how to remove the global scope within Nova. I could find any information on nova.laravel.com regarding this. My attempt tweaking it in the `NovaServiceProvider` didn't work:

```php
    public function boot()
    {
        parent::boot();

        // Remove global scopes to allow viewing all.
        Nova::serving(function () {
            \App\Site::withoutGlobalScope('own_entries');
        });
    }
```

I would love ot hear how to approach this. I'm keen to avoid tweaking the scope it to whitelist the admin accounts as it would also allow to access the entities on the frontend as well.

In case it's relevant:

- Laravel Version: 7.28.3
- Nova Version: 3.11.1
- PHP Version: 7.2.24

Cheers,
Peter

**Comment by ahinkle** [comment]
I don't think you can do it that way as the boot method is after the the serve callback therefore, already including the global scopes.

Might be something to consider as a new feature. For a fix now, you would have to listen to the booted event and rehydrate your model.

**Comment by davidhemphill** [comment]
There's a couple of approaches:

```php
Nova::serving(function () {
     \App\Site::clearBootedModels();
});
```

or 

```php
public static function indexQuery(NovaRequest $request, $query)
{
    $query->withoutGlobalScopes();

    return parent::indexQuery($request, $query);
}
```

The `detailQuery` removes scopes automatically and as such you don't need to remove them.

**Comment by spekulatius** [comment]
Aweome, works! Thank you @davidhemphill!

**Comment by gepopp** [comment]
Hi @davidhemphill, im looking arround for a while now, searching for a solution how to remove global scopes in a morphTo field,
non of the to methods above work, do u have any hint how to go about this? Or is there any option to tell nova to ignore a global scope completley?
