### ISSUE TITLE
ActionEvent resource not customizable

### ISSUE THREAD

**Issue by gldrenthe89** [laravel/nova-issues#2935]
- Laravel Version: 8.8
- Nova Version: 3.11.1
- PHP Version: 7.4.10
- Database Driver & Version:
- Operating System and Version: MacOs 11.0 Beta 9
- Browser type and version: Firefox 81.0.1
- Reproduction Repository: ....

### Description:
I just found out that the built in ActionEvent resource is activated when creating the resource for it. I also found out that i cannot override/extend the built in resource. The problem is now that i want all my resources in the 'tight' table style. And this i not the only 'setting' which would not work. In my opinion this is a bug because now i cannot change anything on this resource. It would bee nice if the created ActionEvent resource could extend the built in one so we can change settings (such as table style, menu grouping and menu order etc.) and override functions.

**Comment by crynobone** [comment]
You should be able to override the resource class using config.

```php
    'actions' => [
        'resource' => Laravel\Nova\Actions\ActionResource::class,
    ],
```

If `config/nova.php` doesn't have the option you either copy the snippet or re-publish the config file.

**Comment by gldrenthe89** [comment]
> You should be able to override the resource class using config.
> 
> ```
>     'actions' => [
>         'resource' => Laravel\Nova\Actions\ActionResource::class,
>     ],
> ```
> 
> If `config/nova.php` doesn't have the option you either copy the snippet or re-publish the config file.

I am so sorry for not even thinking about this. Thanks. got it to work now. 

For inormation purposes to other i have my custom ActionEvent.php resource set-up like this:
```php
<?php

namespace App\Nova;

use ChrisWare\NovaBreadcrumbs\Traits\Breadcrumbs;
use Illuminate\Http\Request;
use Laravel\Nova\Actions\ActionResource;

class ActionEvent extends ActionResource
{
    use Breadcrumbs;

    /**
     * The visual style used for the table. Available options are 'tight' and 'default'.
     *
     * @var string
     */
    public static $tableStyle = 'tight';

    /**
     * Whether to show borders for each column on the X-axis.
     *
     * @var bool
     */
    public static $showColumnBorders = true;

    /**
     * The logical group associated with the resource.
     *
     * @var string
     */
    public static $group = 'Logging';

    /**
     * Determine if this resource is available for navigation.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return bool
     */
    public static function availableForNavigation(Request $request)
    {
        return true;
    }
}
```

This way i dont have to build a complete custom resource class. but just extending the allready available one (which is actually amazing)
