### ISSUE TITLE
Icon alignment in index view

### ISSUE THREAD

**Issue by alberto-bottarini** [laravel/nova-issues#2936]
If I edit policy in order to have update/delete actions available only on some records, this is what happens

<img width="270" alt="Screenshot 2020-10-06 at 09 54 14" src="https://user-images.githubusercontent.com/1442934/95174117-e65b0100-07b9-11eb-8670-50a0a60ed18c.png">

I think icon alignment has to be respected

**Comment by davidhemphill** [comment]
If you remove all of the permissions, there would just be a big blank space. In light of this, I don't think there's a problem with the current approach.

**Comment by alberto-bottarini** [comment]
It should use blank space only if at least 1 row has the icon. 
If an icon is hidden for every rows, the blank space could be removed.
