### ISSUE TITLE
Ability to set min length for search (globally or per resource)

### ISSUE THREAD

**Issue by glamorous** [laravel/nova-issues#2937]
It would be great to not hacking the debounce amount so users won't search on "a" or "e" in your whole database. If would be nice to set a minimum length per resource. Searching an id "1" wouldn't be possible anymore, but thats the responsibility of the programmer.

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
