### ISSUE TITLE
index view get content of fields() AND fieldsForIndex() on Nova 3.12

### ISSUE THREAD

**Issue by henryavila** [laravel/nova-issues#2939]
- Laravel Version: 8.9
- Nova Version: 3.12
- PHP Version: 7.4
- Browser type and version: Chrome

### Description:
In Nova 3.12.0 The fields in index view has the content of `fields()` and  `fieldsForIndex()` .

I have this code (code reduced to minimum possible to demonstrate the error)
``` php
 public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
            Text::make('Nome', 'name'),
            Textarea::make('Descrição', 'note'),
            Boolean::make('Ativo', 'active'),
        ];
    }

    public function fieldsForIndex()
    {
        return [
            Boolean::make('Ativo', 'active'),
            Text::make('Nome', 'name'),
        ];
    }
```

With this code, In index viw, I get the this fields: **ID, Name, Active, Active, Name**

### Detailed steps to reproduce the issue on a fresh Nova installation:
In a Resource add the method  `fieldsForIndex()`  with just some specific fields. The index view will not respect it.

Rolling back Nova to v3.11 fixed the problem

**Comment by SquareBeard** [comment]
Breaking change introduced by https://github.com/laravel/nova/pull/994
Reminder from the documentation: "The fieldsForIndex, fieldsForDetail, fieldsForCreate, and fieldsForUpdate methods always take precedence over the fields method."
Rolling back also.

**Comment by davidhemphill** [comment]
Confirmed. Working on a fix. :-)

**Comment by goldmerc** [comment]
I can see this has been patched. When can we expect the next release with this patch included? Thanks.

**Comment by drewroberts** [comment]
This impacted me as well. Grateful for your work on patching it.
