### ISSUE TITLE
Code field json format not working since v3.11

### ISSUE THREAD

**Issue by henryavila** [laravel/nova-issues#2942]
- Laravel Version: 8.9.0
- Nova Version: 3.12.0
- PHP Version: 7.4

### Description:
In Code field, the `->json()` code format is not working. Data is display as text

### Detailed steps to reproduce the issue on a fresh Nova installation:
In Nova Resource add the field:
``` php
Code::make('Data')->json(),
```
Instead of a formatted code, will display a plain text

Until Nova `v3.10.0` it works as expected, display the json data formatted. Upgrading to Nova `v3.11` trigger the error. The actual `v3.12.0` keeps the error

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release (today). 👍

**Comment by PMassoels** [comment]
I keep on having the same problem. I fixed it temporary by adding a cast to the model when I know my field contains json.

```php
$this->model()
                    ->mergeCasts(
                        [
                            'my_field' => 'array',
                        ]
                    );
```
