### ISSUE TITLE
Can't compile Nova for dev

### ISSUE THREAD

**Issue by goldmerc** [laravel/nova-issues#2943]
- Laravel Version: 8.9.0
- Nova Version: 3.12.0
- Homestead: 20.04 branch
- npm: 6.14.6
- node: 14.5.0

I just updated to Nova 3.12.0. I wanted to use DevTools and followed the instructions in docs. When I run 'npm install' it fails with a file not found error...

```
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/vagrant/if.3/vendor/laravel/nova/node_modules/acorn-dynamic-import/node_modules/acorn/package.json.391031875
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/vagrant/if.3/vendor/laravel/nova/node_modules/acorn-dynamic-import/node_modules/acorn/package.json.391031875'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2020-10-07T16_29_08_444Z-debug.log
```

I installed acorn and ran npm install again but then there was another missing package. I continued to install missing packages but no luck.

Any suggestions? Thanks

**Comment by goldmerc** [comment]
I found a work around. I ran the commands on my host machine rather than the VM and everything worked as expected. This was with node 14.13.0 & npm 6.14.8. I was able to compile Nova for dev.

Then I decided to update my Homestead VM with apt-get so that I had the same versions of node and npm that worked on my host machine. I tried again in the VM and again it failed with a file not found error. 

I did some googling and found this which suggests it may be a VM issue... https://github.com/laravel/homestead/issues/1239#issuecomment-511875101

In the thread someone suggests adding type: "nfs" to the Homestead.yml file. I tried this and npm install progressed much further but this time failed with "Failed at the pngquant-bin@4.0.0 postinstall script."

I'd still prefer to compile in the VM if anyone knows how! Thanks.

**Comment by goldmerc** [comment]
ps. 'yarn install' works fine in Homestead and after that I can run 'npm run dev'. I'm fairly new to npm & yarn. Is there any problem installing with yarn and then moving back to npm?

**Comment by crynobone** [comment]
I would assume `yarn install` is the best option to compile Nova own assets since the repository contains `yarn.lock` instead of `package-lock.json`.

**Comment by goldmerc** [comment]
@crynobone - thanks, that makes good sense. In that case, may I request that the Nova docs are updated? It's probably obvious to more experienced coders but to an amateur like me, it took me a few hours to figure that out!...

https://nova.laravel.com/docs/3.0/customization/frontend.html#vue-devtools

Also, I'm still not clear on one thing. If I need to use 'yarn install', should I then use 'yarn run dev' instead of 'npm run dev' or do both work just fine?

**Comment by crynobone** [comment]
@goldmerc sorry for the late reply.

Talked with the team and so far from the discussion running `npm install` from VM is definitely still PITA. I personally would encourage to use `yarn install` since we already have `yarn.lock` but Laravel ecosystem in general would prefer `npm` over `yarn`. Will relook into this in future once we start doing big changes to Nova.

**Comment by goldmerc** [comment]
@crynobone - thanks! I started doing all the npm commands from the host machine anyway and that's working fine for me now.
