### ISSUE TITLE
User resource is not registering

### ISSUE THREAD

**Issue by nickbasile** [laravel/nova-issues#2948]
- Laravel Version: 8.9.0
- Nova Version: 3.12.1
- PHP Version: 7.4.3
- Database Driver & Version: MySQL
- Operating System and Version: MacOS Mojave 10.14.6
- Browser type and version: Chrome 85.0.4183.102

### Description:
I have a Laravel 8 project using Jetstream with Inertia (v1.4.0). When I installed Nova, the user resource did not appear in the sidebar nav. I generated another resource for a different model and that one appeared. I deleted the default user resource and generated another one, but it also did not appear. I tried to manually register the resource using the `resources` method in `NovaServiceProvider`, but that didn't work either.

The only clue I have is that PHPStorm is saying that I have `Multiple definitions exist for class 'User'` when I check the `use` statement in the resource. My `App/Models` directory only has one user model in it, so I'm not sure where the other one is coming from. 

When I hover over the class definition of my user model, PHPStorm says that `Other declarations of class 'User' exist at jetstream/…/User.php, UserWithTeams.php`. I've tried excluding the `vendor` directory from PHPStorm, but it still shows the same error.

Thank you for the help!

**Comment by crynobone** [comment]
> When I hover over the class definition of my user model, PHPStorm says that Other declarations of class 'User' exist at jetstream/…/User.php, UserWithTeams.php. I've tried excluding the vendor directory from PHPStorm, but it still shows the same error.

Yes PHPStorm could report this issue but those files aren't autoloaded via composer so it shouldn't be related to this issue. Can you publish the reproducing code so I can look into this further.

**Comment by nickbasile** [comment]
Thanks @crynobone!

This is the User resource:

```
<?php

namespace App\Nova;

use Illuminate\Http\Request;
use Laravel\Nova\Fields\Gravatar;
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Fields\Password;
use Laravel\Nova\Fields\Text;

class User extends Resource
{
    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static $model = \App\Models\User::class;

    /**
     * The single value that should be used to represent the resource when being displayed.
     *
     * @var string
     */
    public static $title = 'name';

    /**
     * The columns that should be searched.
     *
     * @var array
     */
    public static $search = [
        'id', 'name', 'email',
    ];

    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),

            Gravatar::make()->maxWidth(50),

            Text::make('Name')
                ->sortable()
                ->rules('required', 'max:255'),

            Text::make('Email')
                ->sortable()
                ->rules('required', 'email', 'max:254')
                ->creationRules('unique:users,email')
                ->updateRules('unique:users,email,{{resourceId}}'),

            Password::make('Password')
                ->onlyOnForms()
                ->creationRules('required', 'string', 'min:8')
                ->updateRules('nullable', 'string', 'min:8'),
        ];
    }

    /**
     * Get the cards available for the request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function cards(Request $request)
    {
        return [];
    }

    /**
     * Get the filters available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function filters(Request $request)
    {
        return [];
    }

    /**
     * Get the lenses available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function lenses(Request $request)
    {
        return [];
    }

    /**
     * Get the actions available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function actions(Request $request)
    {
        return [];
    }
}
```

Here is the user model:
```
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;
use Laravel\Cashier\Billable;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;
    use Billable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'is_onboarded',
        'role',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'is_onboarded' => 'boolean',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];

    protected static function boot()
    {
        parent::boot();

        static::deleting(function ($model) {
            $model->cancelSubscription($model);
        });
    }

    public function tracks()
    {
        return $this->hasMany(Track::class);
    }

    public function works()
    {
        return $this->hasMany(Work::class);
    }

    public function isAdmin()
    {
        return $this->role === 'admin';
    }

    public function isSubscribed()
    {
        if($this->isAdmin()) {
            return true;
        }

        return $this->subscribed('Monthly Plan') || $this->subscribed('Annual Plan');
    }

    public function cancelSubscription($model)
    {
        if($model->subscribed('Monthly Plan')) {
            $model->subscription('Monthly Plan')->cancelNow();
        }

        if($model->subscribed('Annual Plan')) {
            $model->subscription('Annual Plan')->cancelNow();
        }
    }
}
```

Are there any other files that would help?

**Comment by crynobone** [comment]
https://github.com/nova-issues/issue-2948

I tried replicating the issue using `laravel new --jet` and use `inertia` + `no team` option and everything working fine at my end.

![Screenshot 2020-10-09 at 9 34 38 AM](https://user-images.githubusercontent.com/172966/95532830-274e5200-0a14-11eb-8bf2-96e09be1ff6a.png)
![Screenshot 2020-10-09 at 9 34 52 AM](https://user-images.githubusercontent.com/172966/95532835-2ae1d900-0a14-11eb-98d5-0726996fdb61.png)

**Comment by nickbasile** [comment]
Thanks @crynobone! I did a fresh install as well and it looks like it's working there. So, there must be something funky going on with my project.

Thank you again for the help! If I figure out what's happening, I'll post it here in case someone else runs into the same issue 😄

**Comment by nickbasile** [comment]
Figured it out! I had a `UserPolicy` that wasn't configured correctly. So, everything was behaving as intended.

**Comment by Gismo1337** [comment]
> `UserPolicy`

I ran into the same after created UserPolicy. could you explain in detail?

**Comment by Jul000** [comment]
@Gismo1337 . I had the same problem, I changed UserPolicy viewAny to allow admin or add a before function in UserPolicy to give the ability to all admin.
