### ISSUE TITLE
BelongsToMany not using title attribute

### ISSUE THREAD

**Issue by charlielangridge** [laravel/nova-issues#295]
I've got two BelongsToMany fields, both between User and Event models, but for different purposes, however Nova is titling them both "User" on the record page
`
BelongsToMany::make('Contacts', 'contacts', \App\Nova\User::class),
            BelongsToMany::make('Managers', 'managers', \App\Nova\User::class),
`

![pivot-ex](https://user-images.githubusercontent.com/8578083/44744959-46244f80-aafe-11e8-9e42-48041058dc1c.jpg)

**Comment by bradenkeith** [comment]
The first variable in the make command is for the Name. On BelongsToMany field, it seems to only be used on the attach screen for the dropdown menu. I believe your intent is to alter the label of the resource model. I would suggest creating a new nova resource for Managers, which will extend User and a resource for Contacts, which will extend User. For each, it will have a single method for altering how you wish the label to appear on this screen:


```
class Manager extends User
{

    /**
     * Get the displayble label of the resource.
     *
     * @return string
     */
    public static function label()
    {
        return 'Managers';
    }

}
```

Your field then becomes: `BelongsToMany::make('Managers', 'managers', \App\Nova\Manager::class)`

**Comment by charlielangridge** [comment]
Thanks @bradenkeith - it's a bit of a work around but works! (hopefully it'll be made easier in future releases!)

**Comment by pabloguerrez** [comment]
FYI: If you don't want to show the "work around"-Resource on the navigation sidebar you can add this to the class:
```
    /**
     * Indicates if the resource should be displayed in the sidebar.
     *
     * @var bool
     */
    public static $displayInNavigation = false;
```

**Comment by laraning** [comment]
My 2 cents, what I did was to extend the Model and not the Resource. Then I've created a brand new Resource on that Model extension.

To not worry about all the model inheritance issues (relationships, table name, etc) I've used the https://github.com/tightenco/parental package.
