### ISSUE TITLE
3.12 doesn't show any card on dashboard

### ISSUE THREAD

**Issue by olivM** [laravel/nova-issues#2950]
- Laravel Version: 8.9.0
- Nova Version: 3.12
- PHP Version: 7.4.11
- Database Driver & Version: mysql 8.0.21
- Operating System and Version: OSX 10.15
- Browser type and version: all

### Description:
Nova Dashboard is completely empty (not even the default Help Card)

But the same cards correctly shows up on resource index

Rollback to 3.11 solved the problem

**Comment by crynobone** [comment]
Seem to be related to laravel/nova#1000

**Comment by olivM** [comment]
:/ can't understand why a translation related issue woudl apply to dashboard but not to resource index

currently diving into nova cards code to search for an answer

**Comment by olivM** [comment]
ok so it seems the solution was simply "php artisan nova:publish --force"

but i thought Nova would show a notice on the backend when this is needed

**Comment by crynobone** [comment]
@olivM Glad that solved your problem.

> but i thought Nova would show a notice on the backend when this is needed

That would be Telescope and Horizon, which should be useful since it should be only seen by internal user. 

You can however automate the process using the following guide: https://nova.laravel.com/docs/3.0/installation.html#keeping-nova-s-assets-updated

**Comment by jordanbaindev** [comment]
Inside App\Providers\NovaServiceProvider.php

changing "use Laravel\Nova\Dashboards\Main;" to "use App\Nova\Dashboards\Main;" worked for me
