### ISSUE TITLE
Customizing Resource Classes for BelongsToMany field

### ISSUE THREAD

**Issue by AforDesign** [laravel/nova-issues#2951]
The BelongsTo field has a nice option to use a custom resource.
Could this option please be added tot the BelongsToMany field too?

Right now it's not possible to link to view or edit a pivot resource from a BelongsToMany relation field.
If it is possible, I'd love to hear how.

**Why this request?**
Some of my pivot relations have relations of their own.
Which is perfectly valid.

You can create a pivot model and a Nova pivot resource. This  works fine.
However, the pivot resource can only be accessed via the Nova resource menu, not from the relationship itself.
Finding the correct pivot resource via the resource menu can be hard.

I've tried adding the pivot's id to the BelongsToMany fields, but this doesn't work correctly.
It does show the correct id of the pivot model, but it links to the related resource instead of the pivot resource, resulting in the following link structure: https://[domain]/[path_to_related_resource]/[id_of_pivot_resource]

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
