### ISSUE TITLE
Boolean field  send only 0 or 1

### ISSUE THREAD

**Issue by OthmanAlseagh** [laravel/nova-issues#2954]
Laravel Version: 7.22*
Nova Version: 3.9.1

Description
The values set are not being sent as i want. I'm expecting to get either trueValue('yes') or falseValue('no'), but whatever I do it send only  0 or 1.
 
Boolean::make('Is_active')
    ->trueValue('yes')
    ->falseValue('no')

![hh](https://user-images.githubusercontent.com/25552544/95674471-1f7be280-0bb9-11eb-893a-6713f083a1ed.png)

**Comment by crynobone** [comment]
From the documentation.

> The Boolean field may be used to represent a boolean / "tiny integer" column in your database.

The `trueValue()` and `falseValue()` is only there for computed field where you might want to use for read only field etc, it wasn't designed to used on the form.

**Comment by crynobone** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by OthmanAlseagh** [comment]
@crynobone if its so , why should be sent like is_active 0.
why its included in POST method if its so,
i am trying to change the 0 value to false Or 'false' that can laravel update database .
even I send it like               Boolean::make('Is_active')              its also send the nigitve value 0.

if you dont know how to sole it dont close the issue. let another person fix it.

i looked for that issue but did not be fixed untile now

**Comment by OthmanAlseagh** [comment]
when i update resource with a true value it sends 1, so its updated in database .
otherwise send false value  0

**Comment by OthmanAlseagh** [comment]
@davidhemphill  still I have this problem even if use fillUsing
Boolean::make('is_active')
->fillUsing(
                    function ($request, $model) {
                        if ($request->is_active === 0){
                            return $model->is_active = false;
                        }else{
                            return $model->is_active = true;
                        }
                }),



OR 


Boolean::make('is_active')
->fillUsing(
                    function ($request, $model) {
                        if ($request->is_active === 0){
                            return $request->is_active = false;
                        }else{
                            return $request->is_active = true;
                        }
                }),
I do not want request to send    is_active=0  because it did not update the field in database

otherwise      is_active=false   should be sent that laravel can understand
