### ISSUE TITLE
BelongsToMany -  TypeError: Cannot read property 'attribute' of null

### ISSUE THREAD

**Issue by ryanzzeng** [laravel/nova-issues#2955]
- Laravel Version: v8.9.0
- Nova Version: 3.12.1
- PHP Version: 7.4
- Database Driver & Version: PostgreSql
- Operating System and Version: docker with ubuntu
- Browser type and version: chrome latest version

### Description:
I have a similar issue as https://github.com/laravel/nova-issues/issues/2918,  a good example is the relationship with user and client, user belongs to many client and client belongs to many users, but when i try to attach client to user in nova, it return following page and error:

![image](https://user-images.githubusercontent.com/21005264/95704079-7528bb80-0c9b-11eb-9922-4d4f7c84e4ab.png)

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. A new laravel project with latest nova
2. Create a new user model , a client model, setup the many to many relationship
3. login in nova, try to view a single user, and attach a client with him.

**Comment by crynobone** [comment]
Can you reconfirm the issue based on https://github.com/laravel/nova-issues/issues/2938#issuecomment-706919868

Also a sample repo to replicate the issue would be helpful if issue still persist.

**Comment by StanBarrows** [comment]
I can confirm the issue still exists on the reverse relationship.

https://github.com/laravel/nova-issues/issues/2914

![image](https://user-images.githubusercontent.com/10268813/96007482-ce7d2000-0e3e-11eb-92f5-9977c11e4ae1.png)

**Comment by BenySLO** [comment]
**Always be sure to run `php artisan nova:publish` after upgrading to update Nova's JavaScript and CSS assets.**
this solved my problem

**Comment by crynobone** [comment]
@StanBarrows `app.js?id=9315b56...` isn't the latest bundled with Laravel Nova v3.12.1. 

```json
{
    "/app.js": "/app.js?id=0e8b186d07d5c3587013",
    "/app.css": "/app.css?id=0b758c2722665b3fefc1",
    "/vendor.js": "/vendor.js?id=3097eff3fea5a307a5a0",
    "/manifest.js": "/manifest.js?id=2d315777967b6001bcf1"
}
```

**Comment by crynobone** [comment]
Closing this, but if you still having similar issue feel free to open a new issue with details.
