### ISSUE TITLE
Styling issue on `With Trashed` checkbox 

### ISSUE THREAD

**Issue by alshf89** [laravel/nova-issues#2956]
- Laravel Version: 7.24
- Nova Version: 3.12.1
- PHP Version: 7.4
- Browser: Chrome 85.0.4183.121 (Official Build) (64-bit)

### Description:
Styling issue on `With Trashed` checkbox. It's happening on Attachment forms. it's ok on other forms.

<img width="849" alt="Screen Shot 2020-10-12 at 11 18 19 AM" src="https://user-images.githubusercontent.com/14111656/95719583-e5741480-0c7c-11eb-9462-f6018e3e63ea.png">

**Comment by carlcassar** [comment]
I can confirm this issue when using `BelongsToMany::make()`. While we are on the topic, it would also be nice to have a `withoutTrashed()` method on `BelongsToMany`

**Comment by alshf89** [comment]
Im using `MorphToMany` Relation

> I can confirm this issue when using `BelongsToMany::make()`. While we are on the topic, it would also be nice to have a `withoutTrashed()` method on `BelongsToMany`
