### ISSUE TITLE
Long names of resources let title grow and push buttons away

### ISSUE THREAD

**Issue by sebsel** [laravel/nova-issues#2957]
- Laravel Version: 8.9.0
- Nova Version: 3.12.1
- PHP Version: 7.4.9
- Browser type and version: Firefox 81.0.1, but also Chrome 86.0.4240.75 (macOS)

### Description:

When resources have long names (and they do sometimes) the titles will push the buttons off the edge of the page.
The best way to show is just with a picture: the last part scrolls off the page.

![image](https://user-images.githubusercontent.com/16517999/95742116-ca5ed000-0c8f-11eb-941d-59a4ccd737d9.png)

**Comment by sebsel** [comment]
Part of it seems to be the `.flex-no-shrink` on that `<h1>`, and I understand why it's there. There got to be some way around it I think.

**Comment by crynobone** [comment]
I believe https://github.com/laravel/nova/commit/c4e7fd2eb86a4dcbc528c8e4c84935ff8ad0e6cd should solve this issue and will be available on next release.
