### ISSUE TITLE
Nova update process

### ISSUE THREAD

**Issue by fletch3555** [laravel/nova-issues#296]
I'm not sure if you're already discussing this internally, but if not, please take this suggestion.

The UX of updating Nova is horrendous... Having to download a zip file into your project is a massive step backwards.  Let's not even mention all the people that have subsequently pushed that directory into their public github repo.

Wouldn't it be nice to be able to continue using Composer like we're already doing?  What if I said it should be fairly simple to do?

Composer already has the [concept of repositories](https://getcomposer.org/doc/05-repositories.md), allowing for secondary/tertiary/etc package sources.  Composer can also handle composer repositories with [custom stream options](https://getcomposer.org/doc/05-repositories.md#stream-options).

What if you built a packagist clone that hosted your custom private repositories (Spark, Nova, etc), and tracked users with credentials (user/pass or API keys of some sort).  These credentials can be tracked and used to identify the user requesting the package via HTTP stream options on the composer repository (similar to below).  The packages.json file can be a Laravel route that generates the file based on what packages the credentials have access to.

```
{
  "repositories": [{
    "type": "composer",
    "url": "https://example.org",
    "options":  {
      "http": {
        "header": [
          "API-TOKEN: YOUR-API-TOKEN"
        ]
      }
    }
  }]
}
```

The benefit here is that the repository could be added to the `laravel/laravel` starter, or part of the install steps for Spark/Nova/etc.  Then everything else should function no differently than it would with any other composer package.

This would serve as a central auth/licensing system for the Laravel ecosystem.  I'm even willing to build  it for you (or at least contribute to it) if you don't have time.

Thoughts? Concerns? Questions? I'm all ears!

**Comment by keesh7663** [comment]
However, if the current system is to remain as is, could we have some sort of notification we can subscribe to?  Email or something?  Logging in regularly to check for updates is daunting

**Comment by imerr** [comment]
Agree with @keesh7663: Email notifications for new versions would already be a huge help

**Comment by fletch3555** [comment]
@taylorotwell any plans for this, or something similar?

**Comment by davidhemphill** [comment]
https://nova.laravel.com/docs/1.0/installation.html#updating-nova
