### ISSUE TITLE
Add emit resource update / create

### ISSUE THREAD

**Issue by labcenter2020** [laravel/nova-issues#2960]
Hi there,

Potentially a feature request or just some guidance if there's a better way to do it.

I'm looking to trigger some form of notification / alert / popup / modal when a resource is created/updated (outside of the default toast one). I've had a quick dig but couldn't find a way of doing this. 

**Scenario** - A resource uses an observer class to send some details to an external API. The changes won't take effect for 5 minutes so I want to display a "Please wait 5 minutes for this to take effect" message.

**Possible Solution** - Add ` Nova.$emit('resource-updated' this.resourceInformation.singularLabel.toLowerCase());` to Update.vue, utilise a global tool (not a resource one) and add the component somewhere relevant such as layout.blade.php. I presume this could be mirrored in the creation. 

=====================

Things I've tried which either didn't work or couldn't be utilised fully:

- **Translations file for default toast messages** Didn't work due to it effecting all the resources (only need on 1 or 2). Plus Ideally would be nicer to be more impactful / add specific messages.
-  **Resource Tool**  Semi implemented via using router.beforeEach((to, from, next) => {} in tools.js and checking the "to" and "from" name with some global variables. Doesn't cover all situations though such as "update and continue editing" and felt a bit awkward with the router guard. 
- **PHP registered field** I could register a field and check against the updated_at field but it didn't meet all situations (continue editing / add another) and didn't feel like the best way UX wise to have a readonly input mixed in with the rest. 
- **Cards**  I couldn't find a way or don't think its possible to use the $request variable when registering cards to only display them after a resource been created or updated.

=======================

I might of overlooked something but hopefully a scenario/solution and some things I've tried above.

Cheers!

**Comment by crynobone** [comment]
Would be a great PR if you're up for it. Sounds handy. 🤙

Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
