### ISSUE TITLE
$this->id empty in Resource fields() method on form submission

### ISSUE THREAD

**Issue by keironwaites** [laravel/nova-issues#2963]
- Laravel Version: 7.28.3
- Nova Version: 3.10.0
- PHP Version: 7.4.10
- Database Driver & Version:
- Operating System and Version: macOS Catalina 10.15.7
- Browser type and version: 86.0.4240.75 (Official Build) (x86_64)
- Reproduction Repository: n/a

### Description:

Expected to have access to $this->id from within Resource fields() method. It is there for nearly every call to it for normal view / save calls. However for some reason it is not there for one of the calls to field(), triggered during the save process.

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Create a fresh resource.
2. Add this fields() method:

```
    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function fields(Request $request)
    {
        \Log::emergency($this->id);

        return [
            Text::make('Id'),
        ];
    }
```

3. Submit the form in your browser.
4. Tail the logs and you will see something like this:

[2020-10-15 12:46:01] local.EMERGENCY: 6216719  
[2020-10-15 12:46:01] local.EMERGENCY:   
[2020-10-15 12:46:01] local.EMERGENCY: 6216719  
[2020-10-15 12:46:01] local.EMERGENCY: 6216719  
[2020-10-15 12:46:01] local.EMERGENCY: 6216719

Observe that the second line has no value.

**Comment by crynobone** [comment]
Can you share what exactly you want to do with `$this->id` and `rules()` as that should be expected AFAIK.

**Comment by keironwaites** [comment]
Apologies, I have changed the bug report as I realised ->rules() had nothing to do with it.

I am using $this->id as an example. In actuality, I am wanting to check the value of another arbitrary field (which is also NUL) - if it is a certain value then I will add a ->help() text to a different field.

**Comment by keironwaites** [comment]
Further apologies. I believe this was caused by me not passing id as a form field. I was passing:

ID::make(__('Id'), 'user_id')->sortable(),

When I changed it to:

ID::make(__('Id'))->sortable(),

$this->id was no longer NULL.

**Comment by davidhemphill** [comment]
Resource and their fields are not always resolved with an underlying model instance, like for Create views for example. Your best bet is to use the `optional` helper:

```php
public function fields(Request $request)
{
    info(optional($this)->id);
    return [
        //
    ];
}
```
