### ISSUE TITLE
if using this when on resource field and the field was relation

### ISSUE THREAD

**Issue by anditsung** [laravel/nova-issues#2967]
- Laravel Version: 8
- Nova Version: 3
- PHP Version: 7

Failed to load resource: the server responded with a status of 404 (Not Found)

http://dev:8888/nova-api/employees/field/contracts?resourceName=contracts&viaResource=employees&viaResourceId=14&viaRelationship=contracts

found out about the problem

if i add this

```
$this->when( $this->is_contract, function () {
                return HasMany::make(__("Contracts"), 'contracts', Contract::class);
            }),
```

it will return 404

but if i change it to 

```
HasMany::make(__("Contracts"), 'contracts', Contract::class)
```

but not all employee have contract

**Comment by crynobone** [comment]
Can you provide a full reproducing code. We already have tests with `$this->when()` and it's not returning 404 so we definitely needs more information to move forward.

**Comment by anditsung** [comment]
Tomorrow will create a new project to test this

**Comment by crynobone** [comment]
@anditsung After further checking I have confirm that it's not possible. `when()` will not register the field if the first parameter return `false` while using `canSee` will always register the field and only hide it from view. 

It not possible to make `when()` behave similar to `canSee`, and even if we do it will be a breaking change.
