### ISSUE TITLE
VaporFile and VaporImage File Downloading Issue

### ISSUE THREAD

**Issue by pip3firehydrants1** [laravel/nova-issues#2970]
- Laravel Version: 8.0
- Nova Version: 3.0
- PHP Version: 7.4
- Database Driver & Version:
- Operating System and Version: Vapor
- Browser type and version: Chrome

### Description:

I am attempting to use both the VaporFile and VaporImage fields. They will upload a file successfully although the file is saved as the UUID in S3 without an extension. In turn, when the file or image is downloaded, it downloads without an extension - essentially making it useless. 

I have tried to append the ->storeOriginalName('attachment_name') which is tied to a string in the model - did not work. I have also tried using the ->storeAs(...) with a function to grab the filename and file extension and it always failed.

Is there something I'm missing or is there no way to store the file with the original extension?

### Detailed steps to reproduce the issue on a fresh Nova installation:

Upload a file using the VaporFile or VaporImage while the deployed on Laravel Vapor

**Comment by crynobone** [comment]
Can you share full reproducing code.

**Comment by pip3firehydrants1** [comment]
`
    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [
            ID::make(__('ID'), 'id')->sortable(),
            BelongsTo::make('User')->withoutTrashed()->searchable(),
            Text::make('Airman Records Type ID'),
            Date::make('Expires')->rules('required'),
            VaporImage::make('Attachment')->prunable()->nullable(),
            Hidden::make('Site ID', 'site_id')->default(function ($request) {
                return $request->user()->site_id; /* Attaches Site ID */
            }),
        ];
    }
`

I have also tried the varient of

`VaporImage::make('Attachment')->storeOriginalName('attachment_name)->prunable()->nullable(),`

Where 'attachment_name' was a string column for that model

**Comment by pip3firehydrants1** [comment]
Also - if you were to delete the image when editing the resource and not change any other field and click update you will receive a server error of

vendor/laravel/nova/src/Fields/VaporFile.php:149
Message
Trying to access array offset on value of type null
{
"userId": 1,
"exception": {
"class": "ErrorException",
"message": "Trying to access array offset on value of type null",
"code": 0,
"file": "/var/task/vendor/laravel/nova/src/Fields/VaporFile.php:149"
}
}

**Comment by crynobone** [comment]
[![Screenshot 2020-10-20 at 4 14 31 PM](https://user-images.githubusercontent.com/172966/96559663-ed246080-12ef-11eb-8068-f5b516361658.png)](https://github.com/laravel/nova/pull/888#issuecomment-620229735)

Based on related issues it seem to be an expected behaviour, and you can solved this by doing the following.

```php
VaporImage::make('Attachment')
    ->prunable()
    ->nullable()
    ->storeAs(function ($request) {
        return $request->input('vaporFile')['attachment']['key'].'.'.$request->input('vaporFile')['attachment']['extension'];
    }),
