### ISSUE TITLE
Can you add ability edit text as HTML

### ISSUE THREAD

**Issue by codegor** [laravel/nova-issues#2973]
https://i.imgur.com/TOwEhSj.png
Can you add ability edit text as HTML?
 (like in WerdPress https://i.imgur.com/EEqB0pn.png https://i.imgur.com/iQLCdqp.png)

**Comment by crynobone** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
