### ISSUE TITLE
Attach / Detach Buttons

### ISSUE THREAD

**Issue by goldmerc** [laravel/nova-issues#2974]
When using a BelongsToMany relationship field, the standard view / edit / delete icons are used. 

View behaves as we expect. Edit allows you to change which resource is attached and delete detaches the resource.

I like being able to detach the resource but I think the trash icon is confusing. I know it shows the detach tooltip but I would prefer a different icon. Something which visually differentiates what will happen when it is clicked. At the moment, if the user doesn't hover over the icon, they would probably expect it's going to delete that model.

Also, I can see why the edit icon works the way it does but in some use cases, I would like the edit button to provide the usual behaviour of linking to the model's standard edit page but I don't think this is possible?

**Comment by preliot** [comment]
This also confused me in another issue. Something like a break / unbreak chain icon would be nice!

**Comment by goldmerc** [comment]
Yes, I thought some variation on the link symbol could work. I also think it could be something like the heroicons chart-pie symbol which seems to do a good visual representation of detach to me (especially if the slice being removed was slightly larger).

**Comment by preliot** [comment]
Just checked https://github.com/sschoger/heroicons-ui , but i don't see your chart-pie icon. Seems to me there is no good solution in this icon set for attaching or detaching.

**Comment by breakeryouko** [comment]
https://github.com/tailwindlabs/heroicons

I guess he's talking about the 5th column, 5th row icon in this repo.

**Comment by goldmerc** [comment]
Yup, that's the one I meant. For me, something like that does a good visual representation of detach. But then I was thinking, "detach" makes sense to us as it reflects the semantics of the code but I'm not sure it would be very clear to an end user. I tried to think of other terms, link, relate, associate. I don't think any are perfect, but on balance I think more people would understand the link / unlink metaphor, so perhaps the chain icon is the best option?

**Comment by preliot** [comment]
This one would make sense, but there is no 'unlink' icon present:

![image](https://user-images.githubusercontent.com/5418196/97277515-decacd00-1838-11eb-865c-a5e4f3e38cca.png)

**Comment by crynobone** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
