### ISSUE TITLE
NovaServiceProvider cards() didn't show the metrics on nova main page

### ISSUE THREAD

**Issue by khatabwedaa** [laravel/nova-issues#2975]
- Laravel Version: 8.10.0
- Nova Version: 3.12.1
- PHP Version: 7.4.11
- Database Driver & Version: mysql & 8.0.21-0ubuntu0.20.04.4
- Operating System and Version: ubuntu 20.04
- Browser type and version: chrome
- Reproduction Repository: privite

### Description:
After update, nova version from 3.10.0 to 3.12.1, the cards on the main page didn't show

This what function return 

```
{"label":"Dashboard","cards":[{"width":"full","component":"help","prefixComponent":false,"onlyOnDetail":false}]}
```

![Screenshot from 2020-10-19 19-21-32](https://user-images.githubusercontent.com/38974561/96490018-8a27c080-1240-11eb-8767-af2d50e0e7f2.png)

**Comment by josespinal** [comment]
Why did you close this issue? Was it fixed?

**Comment by josespinal** [comment]
For anyone coming to this issue because you don't see the defined cards on Dashboard. Possible fixes are to run:

```
php artisan view:clear
php artisan nova:publish
```

**Comment by khatabwedaa** [comment]
Hello @josespinal, I fix it as you mention with nova:publish command
