### ISSUE TITLE
Rule::exists() not working properly on nova field

### ISSUE THREAD

**Issue by meyer59** [laravel/nova-issues#2976]
- Laravel Version: 7.28.4
- Nova Version: 3.12.1
- PHP Version: 7.3.5
- Database Driver & Version: Mysql 5.7..26
- Operating System and Version: Win10 
- Browser type and version: Chrome  86.0.4240.75

### Description:
Hi
We had a` Rule::exists() `validation on an Action field in place and it suddenly not working anymore.
It throws an Exception `trim() expects parameter 1 to be string, array given`
For the record, here is the buggy field implementaiton with the Rule
```
  Select::make('Equipement', 'equipment_id')->searchable()
                  ->options(PlayerEquipment::whereNull('player_id')->orderBy('mac_address')->pluck('mac_address', 'id')->all())
                  ->displayUsingLabels()
                ->rules(Rule::exists('player_equipment', 'id')->whereNull('player_id')->whereNull('deleted_at')),
```
If i comment the `rule()` method, the action run successfully.
Casting the `Rule::exists` with `(string)` resolve the error but, is it a normal behaviour ?
Here is a screenshot of the error
![image](https://user-images.githubusercontent.com/9505463/96566549-fd274a80-12c5-11eb-8bb2-db1d6007a679.png)

### Detailed steps to reproduce the issue on a fresh Nova installation:
-Create an Action
-Add a `Select` field
-Add a `Rule::exists` validation in the `rule()` method
-Execute the Action

Cordially

**Comment by devfrey** [comment]
`rules()` doesn't support objects, only strings. Either build up the `exists` rule manually, or cast the code in your example to string.

**Comment by crynobone** [comment]
@meyer59 This seem to be a limitation with some of Laravel Validation helpers usage with Laravel Nova. However you can solve this by wrapping the `exists` rule with `[]` such as below:

```php
Select::make('Equipement', 'equipment_id')->searchable()
    ->options(PlayerEquipment::whereNull('player_id')->orderBy('mac_address')->pluck('mac_address', 'id')->all())
    ->displayUsingLabels()
    ->rules([Rule::exists('player_equipment', 'id')->whereNull('player_id')->whereNull('deleted_at')]),
```

**Comment by crynobone** [comment]
`Field::rules()` only accepts `array`, `string`, `Illuminate\Contracts\Validation\Rule` or `Closure`. `Rule::exists()` however doesn't implements `Illuminate\Contracts\Validation\Rule` causing invalid usage.
