### ISSUE TITLE
Partition metrics "Serialization of clouser is not allowed" after upgrade v3.13.0

### ISSUE THREAD

**Issue by massimodellarovere** [laravel/nova-issues#2979]
- Laravel Version: 8.11.2
- Nova Version: 3.13.0
- PHP Version: 7.4.3
- Database Driver & Version: MYSQL
- Operating System and Version: Ubuntu 20.04 LTS
- Browser type and version: Chrome 86.0.4240.75

### Description:

Partition metrics "Serialization of clouser is not allowed" after upgrade v3.13.0

```php
class CountStatus extends Partition
{
    public function calculate(Request $request)
    {
        return $this->count($request,$this->model(),'cashend')
            ->label(function($value) { return $this->customLabels($value); });
    }
}

```

### Detailed steps to reproduce the issue on a fresh Nova installation:
![screen](https://user-images.githubusercontent.com/5731295/96651977-94f35b80-12fb-11eb-807b-73822932045d.jpg)

**Comment by crynobone** [comment]
Will look into this ASAP.
