### ISSUE TITLE
Index query uses LIKE which breaks big tables

### ISSUE THREAD

**Issue by bilfeldt** [laravel/nova-issues#2981]
- Laravel Version: 8.10.0
- Nova Version: 3.12.1
- PHP Version: 7.4
- Database Driver & Version: MySQL 8.0
- Operating System and Version: -
- Browser type and version: -
- Reproduction Repository: -

### Description:
The columns defined in a resources [Searchable Columns](https://nova.laravel.com/docs/3.0/search/global-search.html#searchable-columns) will be used for searches performed by Laravel Nova.

The problem is that Laravel Nova performs a search using a `LIKE` operator and both leading and trailing wildcard `%` like so:
```php
// src/PerformsQueries.php@applySearch

$likeOperator = $connectionType == 'pgsql' ? 'ilike' : 'like';
...
$query->orWhere($model->qualifyColumn($column), $likeOperator, '%'.$search.'%');
```

The problem is that indexes cannot be used when using a leading wildcard, and this causes search functionality to break for huge tables even though they have proper indexing.

> MySQL also uses indexes for LIKE comparisons if the argument to LIKE is a constant string that doesn't start with a wildcard character.
[Source](https://tecfa.unige.ch/guides/mysql/man/manuel_MySQL_indexes.html#:~:text=MySQL%20normally%20uses%20the%20index,wildcard%20prefix%20like%20'something%25'%20.)

### Proposed solution
It makes sense that the _default_ behaviour is to use wildcard searches so that searching for `Doe` in a users table will find `John Doe Smith`. The problem is that searching completely breaks on huge tables, so a possible solution could be to implement a setting for this search behaviour (for each resource since it is often only a few resources that are huge):
- Wildcard (leading and trailing) - Default
- Trailing wildcard - will use indexes but can still cause problems on large tables
- Strict (no wildcard) - will work on all tables as long as proper indexing is in place

### Detailed steps to reproduce the issue on a fresh Nova installation:
This example is for a huge users table - a more realistic example could be a transactions table or something else that could be really big.

The example below contains migration, model and Nova resource. Increasing the number of entires in the database will cause an increased search time. Doing an `EXPLAIN` on the performed search statement will show that no indexes can be used.

Searching for `Doe` on the users index page results in an API request 
```
GET /nova-api/users?filters=W10%3D&orderBy=&page=1&perPage=25&relationshipType=&search=Doe&trashed=
```
which executes the following SQL:
```sql
select
  *
from
  `users`
where
  (
    `users`.`name` like '%Doe%'
    or `users`.`email` like '%Doe%'
  )
order by
  `users`.`id` desc
limit
  26 offset 0
```

Running an explain on this shows that `possible_keys=NULL`.

#### Migration

```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('email')->unique();
            $table->timestamps();

            $table->index('name'); // We have an index on names
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('users');
    }
}

```

#### Model

```php
<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', // We have an index on names
        'email',
        'password',
    ];
}
```

#### Nova resource

```php
<?php

namespace App\Nova;

use Illuminate\Http\Request;
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Fields\Text;

class User extends Resource
{
    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static $model = \App\Models\User::class;

    /**
     * The single value that should be used to represent the resource when being displayed.
     *
     * @var string
     */
    public static $title = 'name';

    /**
     * The columns that should be searched.
     *
     * @var array
     */
    public static $search = [
        'id', // This is indexed by default
        'name', // We have an extra index on this column
    ];

    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),

            Text::make('Name')
                ->sortable()
                ->rules('required', 'max:255'),

            Text::make('Email')
                ->sortable()
                ->rules('required', 'email', 'max:254')
                ->creationRules('unique:users,email')
                ->updateRules('unique:users,email,{{resourceId}}'),
        ];
    }
}

```

**Comment by bilfeldt** [comment]
@crynobone your PR #1059 is a much appreciated fix.

One thing I must admit I did not anticipate when posting this issue is that it appears that MySQL is not able to do any index merging when using the like operator - more details [here](https://dev.mysql.com/doc/refman/8.0/en/index-merge-optimization.html) - meaning that all rows will be scanned even when using non-wildcard. Okay, time for an example:

## Example

Let us say we have a `posts` table with many (many many!) records. This table has the columns `id`, `slug`, `author_id` and `content`. Now the three first are all indexed.

In Nova then we might wanna make the columns `id`, `slug` and `author_id` searchable:

```php
// app/Nova/Port.php

/**
 * The columns that should be searched.
 *
 * @var array
 */
public static $search = [
    'id',
    'slug',
    'author_id',
];
```

Now making a search for `2164989` results in the following query:
```sql
select *
from
  `posts`
where
  (
    `id` = '2164989'
    or `id` like '%2164989%'
    or `uuid` like '%2164989%'
    or `author_id` like '%2164989%'
  )
  and `deleted_at` is null
```

Using the powers of PR #1059 let us add the following:

```php
/**
 * Override default wildcard search.
 *
 * @link  https://github.com/laravel/nova-issues/issues/2981
 * @param  string  $column
 * @param  string  $search
 * @return string
 */
protected static function searchableKeyword($column, $search)
{
    return $search; // do exact search. Default Laravel Nova is: '%'.$search.'%'
}
```
but we know the query looks like:

```sql
select *
from
  `posts`
where
  (
    `id` = '2164989'
    or `id` like '2164989'
    or `uuid` like '2164989'
    or `author_id` like '2164989'
  )
  and `deleted_at` is null
```
Now the problem is that running an explain on this shows that MySQL cannot use index merging :(

If instead of the `$likeOperator` we could somehow set the search to be strict (`=`) then the query would work:

```sql
select *
from
  `posts`
where
  (
    `id` = '2164989'
    or `id` = '2164989'
    or `uuid` = '2164989'
    or `author_id` = '2164989'
  )
  and `deleted_at` is null
```

But that is not possible (also note that the id search appears twice in this list, which is because Nova adds it twice).

**Comment by bilfeldt** [comment]
As of Laravel Nova 4 this can be easily modified by using a custom search query class and registering this in static `searchableColumns()` method on the resource as explained in the docs for [Full-Text Indexes](https://nova.laravel.com/docs/4.0/search/#full-text-indexes) - see the class `Laravel\Nova\Query\Search\SearchableText` for inspiration.

**Comment by ekazda** [comment]
> custom search query class and registering this in static `searchableColumns()` method

When I do this, I get the following error:

`strpos(): Argument #1 ($haystack) must be of type string, App\Nova\Query\Search\AuctionItemIdSearch given`

I'm trying the following:

```
public static function searchableColumns()
    {
        return [
            new ItemIdSearch('item_id'),
            'item_name',
            'make',
            'model'
        ];
    }
```

And my `ItemIdSearch` is a direct copy/paste from the `SearchableText` function in Nova at this point. I only changed the namespace and class name thus far.. 

If possible, can you elaborate on how to do this please?

**Comment by bilfeldt** [comment]
@ekazda Not sure what class `ItemIdSearch` you are referring to. But the error message seems to indicate that you are returning another class; `App\Nova\Query\Search\AuctionItemIdSearch`
