### ISSUE TITLE
Boolean fields always have a 1/0 value in, but are true/false out

### ISSUE THREAD

**Issue by scadh** [laravel/nova-issues#2982]
- Laravel Version: 7.28.3
- Nova Version: 3
- PHP Version: 7.3.2
- Database Driver & Version: mysql
- Operating System and Version: MacOS 10.15.7
- Browser type and version: Chrome

### Description:
Screenshot attached. 
![nova_error](https://user-images.githubusercontent.com/32772804/96757334-e7378980-139a-11eb-86d7-1b3736b72dcf.png)
When I update an item in Nova, the Action Details log ALWAYS shows all Boolean fields in the resource as having been changed. It shows the 'Original' value for each as a 1 or 0, and the 'Changes' value as true or false. It makes no difference whether I actually change the value or interact with the field in any way, this happens every time. This is a problem for me because I am trying to use the isDirty() and/or wasChanged() methods in an Observer to trigger an email in the event that one particular Boolean value has changed. Even when I don't make any changes to the form, the change from 1 to true or 0 to false causes both isDirty() and wasChanged() to evaluate true. This causes email to be sent when none should. The corresponding column in mysql still correctly reflects 1/0, for what it's worth.

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Create a new resource with a Boolean field
- Update the resource without changing the Boolean
- View the resource Action Details log and note the "change" from 1/0 to true/false.

**Comment by scadh** [comment]
Within 5 minutes of posting this, I found a workaround for this. I don't think it's ideal, but it does solve the problem by forcing values to 1/0 instead of true/false.

Boolean::make('Confirmed', 'is_confirmed')
                ->trueValue(1)
                ->falseValue(0),

**Comment by crynobone** [comment]
You needs to add `$casts` property to the model.

```php
    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'published' => 'boolean',
    ];
```

![image](https://user-images.githubusercontent.com/172966/96826422-eb7ca900-1465-11eb-8518-196333913b19.png)
