### ISSUE TITLE
Detail view title is truncated to soon, needs more width

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#2983]
- Laravel Version: 7.28.4
- Nova Version: 3.13.0
- PHP Version: 7.2.19
- Database Driver & Version: Mysql, 5.7.24
- Operating System and Version: Windows 10 (64 bit)
- Browser type and version: Chrome (latest)

### Description:

Detail view now shows title truncated. I understand the need to truncate, but there is no space now to show relevant information. 

![image](https://user-images.githubusercontent.com/5418196/96845954-92a31580-1451-11eb-954f-a2bd1ac149f5.png)

### Detailed steps to reproduce the issue on a fresh Nova installation:

* Fresh Laravel Nova install
* Create some dummy users
* Open detail of one of them

**Comment by marcoraddatz** [comment]
Why has this been closed without any comment? Will it be reverted soon? Is this request invalid because of... whatever? I also agree that the truncate doesn't make any sense that early.

**Comment by preliot** [comment]
@marcoraddatz it's closed because it's fixed. You probably can't see anything, because you need to link your nova account to your github account in order to see that information. I've experienced the same issue some time ago  :-)

**Comment by marcoraddatz** [comment]
> @marcoraddatz it's closed because it's fixed. You probably can't see anything, because you need to link your nova account to your github account in order to see that information. I've experienced the same issue some time ago :-)

Many thanks! Will do it now.
