### ISSUE TITLE
Trying to change sorted column while some other column is sorted in descending order resets the sorting

### ISSUE THREAD

**Issue by nikazooz** [laravel/nova-issues#2984]
- Laravel Version: 8.9.0
- Nova Version: 3.13.0
- PHP Version: 7.4.9
- Database Driver & Version: PostgreSQL 12
- Operating System and Version: Alpine Linux (kernel v4.19)
- Browser type and version: Firefox (latest)

### Description:
When resource table is sorted in descending order on one column clicking on a different column in order to sort by it resets sorting entirely. This doesn't happen if old sorting was in ascending order.

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Fresh Nova install
- Create some dummy users
- Make sure name and email columns are sortable (should be by default)
- Click on name column to sort by name in ascending order
- Click again on name column to change sorting order to descending
- Click on email column to switch to sorting by email in ascending order
- The sorting is reset instead of sorting by email in ascending order

**Comment by crynobone** [comment]
Ping @davidhemphill, not sure if this is intended behaviour or a bug.

**Comment by crynobone** [comment]
```js
    orderByField(field) {
      let direction = this.currentOrderByDirection == 'asc' ? 'desc' : 'asc'

      if (this.currentOrderBy != field.sortableUriKey) {
        direction = 'asc'
      }
```

Looking at the code this seem intended behaviour.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by nikazooz** [comment]
@crynobone That part is fine. I'd say the issue is with `SortableIcon` component's `handleClick` method. This solves the issue I'm talking about:
```js
handleClick() {
  if (this.isSorted && this.isDescDirection) {
    this.$emit('reset')
  } else {
    this.$emit('sort', {
      key: this.uriKey,
      direction: this.direction,
    })
  }
},
```

**Comment by crynobone** [comment]
I'll check again on monday.
