### ISSUE TITLE
Polling information on index

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#2986]
Would be great if there is some visual feedback on polling being active. Right now i've created a card doing that, but this doesn't look great imho.

![image](https://user-images.githubusercontent.com/5418196/96882132-47076080-147f-11eb-8b1f-6e59c8191441.png)

Perhaps something like 'data refreshes every x seconds' next to the search? Or something like a refresh icon next with x seconds?

**Comment by preliot** [comment]
Appreciating the new feature in 3.14.0 to show a polling toggle, helps!

```
 /**
     * Indicates whether to show the polling toggle button inside Nova.
     *
     * @var int
     */
    public static $showPollingToggle = true;

```

**Comment by davidhemphill** [comment]
Glad you like it. 😄
