### ISSUE TITLE
VaporFile and VaporImage Error When No File Is Selected

### ISSUE THREAD

**Issue by pip3firehydrants1** [laravel/nova-issues#2988]
- Laravel Version: 8.0
- Nova Version: 3.0
- PHP Version: 7.4
- Database Driver & Version: Vapor
- Operating System and Version: Vapor
- Browser type and version: Chrome
- Reproduction Repository: https://github.com/###/###

### Description:

When submitting a form with VaporFile or VaporImage as a field and a file has not been selected the following error occurs

```
[2020-10-24 04:21:04] local.ERROR: Trying to access array offset on value of type null {"userId":1,"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type null at C:\\xampp\\htdocs\\xxx\
ova\\src\\Fields\\VaporFile.php:149)
```

When you go to line 149 you see

```
return with($request->input('vaporFile')[$requestAttribute]['key'], function ($key) use ($request) {
```

This would make sense why there is an error because no file was selected and as such there will be no 'key' to grab from the input array.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Use VaporFile or VaporImage on a resource and attempt to submit the form without selecting a file - you will receive this error. Must be serving this on Laravel Vapor.

This is the resource code:

```
     /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [
            ID::make(__('ID'), 'id')->sortable(),
            Badge::make('Status')->map([
                'OPEN' => 'warning',
                'CLOSED' => 'success',
            ]),
            DateTime::make('Created At')->format('DD MMM YYYY hh:mm A')->exceptOnForms(),
            Select::make('Status')->options([
                'OPEN' => 'Open',
                'CLOSED' => 'Closed',
            ])->onlyOnForms()->rules('required'),
            VaporFile::make('xxx'),
        ];
    }

```

**Comment by crynobone** [comment]
> This would make sense why there is an error because no file was selected and as such there will be no 'key' to grab from the input array.

I believe the setup for optional file upload should be:

```php
VaporFile::make('xxx')->nullable(),
```

**Comment by pip3firehydrants1** [comment]
After adding the '->nullable()' to the VaporFile I receive this error when in Vapor

```
{
"userId": 1,
"exception": {
"class": "ErrorException",
"message": "Trying to access array offset on value of type null",
"code": 0,
"file": "/var/task/vendor/laravel/nova/src/Fields/VaporFile.php:149"
}
}
```

**Comment by crynobone** [comment]
@pip3firehydrants1 thank you for the response. A PR has been made to fixed the issue.

https://github.com/laravel/nova/pull/1039
