### ISSUE TITLE
Composer is complaining that moontoast/math is abandonded, they recommend using brick/math instead

### ISSUE THREAD

**Issue by cdrum** [laravel/nova-issues#2990]
- Laravel Version: 8.11.2
- Nova Version: 3.13
- PHP Version: 7.4
- Database Driver & Version:
- Operating System and Version: Ubuntu 20.04 LTS
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:

Composer is complaining that moontoast/math is abandonded, they recommend using brick/math instead

### Detailed steps to reproduce the issue on a fresh Nova installation:

When running `composer install`, we get the following warning:
Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead.

**Comment by crynobone** [comment]
We'll consider this on the next-series. However as for now it's still safe to use `moontoast/math` as mentioned by Ramsey himself, https://github.com/laravel/nova-issues/issues/2270#issuecomment-583044259

**Comment by cdrum** [comment]
Cheers thanks
