### ISSUE TITLE
Bug with fieldsForCreate and creation of related resource

### ISSUE THREAD

**Issue by codegor** [laravel/nova-issues#2992]
- Laravel Version: 8.11.2
- Nova Version: 8.13.0
- PHP Version: 7.4.11
- Database Driver & Version: PostgreSQL
- Operating System and Version: Ubuntu 18
- Browser type and version: Chrome latest
- Reproduction Repository: https://nova.laravel.com/docs/3.0/resources/fields.html#dynamic-field-methods

### Description:
If I use fieldsForCreate and if I hit create Resource from relation resourse that resource does not auto selected

Resource without fieldsForCreate method:

https://i.imgur.com/rqlt1yT.png
https://i.imgur.com/R2LlUBy.png

Resource with fieldsForCreate method:

https://i.imgur.com/ThkAKWw.png
https://i.imgur.com/Oc7vGSy.png

### Detailed steps to reproduce the issue on a fresh Nova installation:

For Example: 
User resource has fieldsForCreate 
and 
If I hit create a Company for selected User 
then 
(at create company view) user, from which i came, does not auto selected

```php

namespace App\Nova;

use Illuminate\Http\Request;
use Laravel\Nova\Fields\{BelongsTo, Boolean, Number, DateTime, Date, HasMany, KeyValue, Text, Markdown, Hidden, Select};
use Laravel\Nova\Http\Requests\NovaRequest;

use DigitalCreative\MegaFilter\{MegaFilter, HasMegaFilterTrait, Column};
use Silvanite\NovaFieldCheckboxes\Checkboxes;
use OptimistDigital\MultiselectField\Multiselect;
use EmilianoTisato\GoogleAutocomplete\{GoogleAutocomplete, AddressMetadata};

class User extends Resource {
    ....
    /**
	 * Get the fields displayed by the resource.
	 *
	 * @param \Laravel\Nova\Http\Requests\NovaRequest $request
	 * @return array
	 */
	public function fieldsForCreate(NovaRequest $request) {
            ....
        }
        ....
}

namespace App\Nova;

use Illuminate\Http\Request;
use Laravel\Nova\Fields\{BelongsTo, Boolean, Number, DateTime, Date, HasMany, KeyValue, Text, Markdown, Hidden, Select};
use Laravel\Nova\Http\Requests\NovaRequest;

class Company extends Resource {
    ....
    //**
	 * Build a "relatable" query for the given resource.
	 *
	 * This query determines which instances of the model may be attached to other resources.
	 *
	 * @param \Laravel\Nova\Http\Requests\NovaRequest $request
	 * @param \Illuminate\Database\Eloquent\Builder $query
	 * @return \Illuminate\Database\Eloquent\Builder
	 */
	public static function relatableUsers(NovaRequest $request, $query) {
		return $query->where('users.status', 'active');
	}
}

```

**Comment by crynobone** [comment]
Hi @codegor, Just wanted to confirm, does `relatableCompanies()` has any affect on the issue? Planning to replicate to issue today.

**Comment by codegor** [comment]
No, relatableCompanies() -> relatableUsers(), and this is for showing how company depends of users. I commented (switch off) this method - without result, only if I comment (switch off) fieldsForCreate - bug vanish

**Comment by felixstoessel** [comment]
Seems as this might have something to do with #3030.

**Comment by crynobone** [comment]
> Seems as this might have something to do with #3030.

Not related, completely different issue.

**Comment by crynobone** [comment]
Similar to #3030 I wasn't able to replicate this issue. You can refer the reproducing code <https://github.com/nova-issues/issue-2992/commit/9ed18d3e52f51c1e763bcee52a825ee78c71a477>. Do report back if I missed out anything.

**Comment by richvida** [comment]
Also running into this issue
