### ISSUE TITLE
Count distinct in Trend metrics

### ISSUE THREAD

**Issue by miki131** [laravel/nova-issues#2994]
Hi there,

Can you add ability to count distinct columns in trend metric?

**Comment by crynobone** [comment]
You could refer to the documentation.

https://nova.laravel.com/docs/3.0/metrics/defining-metrics.html#partition-query-types

**Comment by crynobone** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by miki131** [comment]
@crynobone there is no way to count distinct now, because of
```php
return $this->aggregate($request, $model, $unit, 'count', $resource->getQualifiedKeyName(), $column);
```

Can I make PR to fix this?

**Comment by crynobone** [comment]
You can try submitting a PR and @davidhemphill will decide on it.
