### ISSUE TITLE
Class 'Laravel\Nova\Actions\ActionResource' not found

### ISSUE THREAD

**Issue by progcode** [laravel/nova-issues#2995]
- Laravel Version: 8.11.2
- Nova Version: 3.13.0
- PHP Version: 7.3.13
- Database Driver & Version: mysql

### Description:

I got the following error, with a clean install:

`Class 'Laravel\Nova\Actions\ActionResource' not found (View: /home/admin/web/pay2.hu/public_html/nova/resources/views/layout.blade.php)
`
### Detailed steps to reproduce the issue on a fresh Nova installation:

Clean install.

**Comment by crynobone** [comment]
Not enough information to replicate the issue. I would recommend the following:

* Check laravel/nova installation status: `composer show | grep "laravel/nova"`
* Run `composer dump-autoload`
* Check the actual file exist `vendor/laravel/nova/src/Actions/ActionResource.php`

**Comment by progcode** [comment]
**composer show | grep "laravel/nova":**
laravel/nova                       dev-develop A wonderful administration interface for Laravel.

**composer dump-autoload**
```
Generating optimized autoload files> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: fruitcake/laravel-cors
Discovered Package: laravel/nova
Discovered Package: laravel/tinker
Discovered Package: laravel/ui
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Package manifest generated successfully.
Generated optimized autoload files containing 5397 classes
```
**Check the actual file exist vendor/laravel/nova/src/Actions/ActionResource.php**:
Not exists. But i dont understand why, this is a clean nova install without any extra package.

**Comment by progcode** [comment]
**I also tried:**

- deleted vendor and composer.lock and reinstall
- re-run nova:install
- run nova:publish

nothing work

**Comment by crynobone** [comment]
@progcode If you're using composer install route, it should show something like:

```
composer show | grep "laravel/nova"
laravel/nova                       v3.13.0   A wonderful administration interface for Laravel.
```

It's a bit harder to debug when you install via zip. But again unable to replicate the issue.

**Comment by progcode** [comment]
as i wrote:

```
composer show | grep "laravel/nova"
laravel/nova dev-develop A wonderful administration interface for Laravel.
```

**Comment by progcode** [comment]
I dont know what happened with the install process, a lot of file missing from vendor/laravel/nova/src , i copied this files from my local environment and now everything works properly

**Comment by crynobone** [comment]
Glad the problem solved.

**Comment by vdBergMike** [comment]
For those still wondering what solved this issue:

After upgrading Nova from 3.* to 4.*, when you replaced the `use` as documented for the new classes in your  `/config/nova.php`,  make sure the `use Laravel\Nova\Actions\ActionResource;` is still there!
