### ISSUE TITLE
Cannot sort Badge field

### ISSUE THREAD

**Issue by xoco70** [laravel/nova-issues#2997]
- Laravel Version: 8.11.2
- Nova Version: 3.13.0
- PHP Version: 7.4
- Database Driver & Version: PgSQL
- Operating System and Version: Ubuntu 20.04
- Browser type and version: Chrome

### Description:

I have this badge: 

```
$coverage = [
        ];
        for ($i = 0; $i <= 25; $i++) {
            $coverage["$i %"] = "danger";
        }
        for ($i = 26; $i <= 50; $i++) {
            $coverage["$i %"] = "warning";
        }
        for ($i = 51; $i <= 75; $i++) {
            $coverage["$i %"] = "info";
        }
        for ($i = 76; $i <= 100; $i++) {
            $coverage["$i %"] = "success";
        }

Badge::make("Taux de repartition", function () {
                if ($this->repartition_rate == 0) return "0 %";
                return (int)($this->repartition_rate) . " %";
            })->sortable()->onlyOnIndex()->map($coverage),
```
`sortable()` is not working for this field.

**Comment by crynobone** [comment]
https://nova.laravel.com/docs/3.0/resources/fields.html#computed-fields

Computed fields can't used `sortable()`, this is a limitation on Laravel Nova but you can try the following:

```php
Badge::make("Taux de repartition", 'repartition_rate')
    ->displayUsing(function ($value) {
        if ($value == 0) return "0 %";
        return (int)($value) . " %";
    })->sortable()->onlyOnIndex()->map($coverage),
```

**Comment by xoco70** [comment]
This will work, because I do have a repartition_rate field in DB. 

If there is no field in db, and the field is a true computed field, it wouldn't work. 

Is there a workaround for those case ?

**Comment by crynobone** [comment]
> Is there a workaround for those case ?

It would be a performance nightmare to load all the information to memory and sort. It's just simply unpractical.
