### ISSUE TITLE
Value metrics with join

### ISSUE THREAD

**Issue by JeromeRiffier** [laravel/nova-issues#2999]
- Laravel Version: 8.11.2
- Nova Version: 3.13.0
- PHP Version: 7.4.11
- Database Driver & Version: 
- Operating System and Version: linux on Docker
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:

Value metrics crash when it is used with some join in the count function $model parameter because created_at is ambiguous.
It would be great to have the possibility to specify with what table we wan't to use the created_at.

![image](https://user-images.githubusercontent.com/53470235/97422489-266f5880-190e-11eb-9a29-03d667561133.png)

### Detailed steps to reproduce the issue on a fresh Nova installation:

- Have 2 laravel models with relation with timestamps on both
- Create a new value metric for 1 of the model
- Join the second model in the count inside the calculate function of the metrics
- Test it

**Comment by GautierDele** [comment]
The problem is that you need to specify the dateColumn argument of the function.
![image](https://user-images.githubusercontent.com/12382966/97422876-b4e3da00-190e-11eb-9993-4b04412f9f27.png)

Still, shouldn't it default to the "table.column" value instead of "column" value ?

**Comment by crynobone** [comment]
This seem to be a harder fix than I expected.

By using `getQualifiedCreatedAtColumn()`, few existing tests now fails. Either the tests are incorrect or we have a bigger problem at the moment. Will have to look at this again later.
