### ISSUE TITLE
Defining resource name for the sidebar

### ISSUE THREAD

**Issue by vyuldashev** [laravel/nova-issues#3]
For example I name class UserResource and want in to appear as “Users” in sibebar.

**Comment by themsaid** [comment]
Can you please share a more general screenshot?

**Comment by vyuldashev** [comment]
Lets take another example. Resource `AgentResource`:

```php
class AgentResource extends Resource
{
    // ...
    public static function label()
    {
        return 'Agents';
    }

    public static function singularLabel()
    {
        return 'Agent';
    }
    // ...
}
```

Leads to this:

<img width="333" alt="screen shot 2018-08-23 at 17 32 00" src="https://user-images.githubusercontent.com/1809081/44531930-95cbdb00-a6fa-11e8-8581-a39e9a383f94.png">

Anyway, it seems like overriding label is a bad approach because urls will also remain the same: `nova/resources/agent-resources`. Or Nova may use `label` for generating urls also.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in an upcoming release.
