### ISSUE TITLE
Using resolveUsing for ID field breaks links

### ISSUE THREAD

**Issue by pdewit** [laravel/nova-issues#30]
Tested on Nova Version 1.0.5

Using resolveUsing on an ID field breaks the links:

```
ID::make()->sortable()->resolveUsing(function ($id) {
    return '#' . $id;
}),
```

I want an # in front of my ticket numbers, but this breaks the url when clicking on view/edit/delete/etc, for example ticket #48817:

/nova/resources/tickets/%2348817

**Comment by devmsh** [comment]
Yes, this is because the main `Resource` depend on the `ID` field to generate the `id` within the `serializeForIndex` method.

Easy to overcome by not using the ID field at all and replace it with:
```
Text::make('id')->sortable()->displayUsing(function ($id) {
  return '#' . $id;
}),
```

**Comment by davidhemphill** [comment]
The ID is primarily used for URL generation and as such can't have a hash in them since it's a reserved character. The suggested workaround above seems like a good solution.
