### ISSUE TITLE
Dynamic Form Fields

### ISSUE THREAD

**Issue by noahlocke** [laravel/nova-issues#300]
I have a highly complex model that, when created, uses quite a bit of show/hide logic on the form field components. I couple this with the 'sometimes|required' validation logic. 

The only way I can see to reproduce this on Nova's 'Create' view is to duplicate every single field as a custom field so I can add "v-if" logic and take advantage of the EventBus... would be nice if I could pass a condition/event to the out-of-the-box components, something like:

```
Select::make('NoteFormat')->options($array),

Trix::make('SomeFormat')->showIf('NoteFormat', $array[key])

**Comment by bretto36** [comment]
Would this be dynamic on the page. EG if they select a different value from the drop down some fields would be hidden and others made visible?

I'm after something that shows a panel when a drop down is changed

**Comment by noahlocke** [comment]
Yes, the parameters set would pass props to the Vue component ideally.

**Comment by unxsist** [comment]
We've just released a package that allows you to display fields depending on values of other fields, it's not fully what you've requested, but it's a start. Maybe it helpful: https://novapackages.com/packages/epartment/nova-dependency-container

**Comment by davidhemphill** [comment]
No plans to add this to core at this time. The package above looks nice though.

**Comment by pnj131** [comment]
how we write if condition in nova.?
