### ISSUE TITLE
Please reconsider respecting the global scope.

### ISSUE THREAD

**Issue by nickkuijpers** [laravel/nova-issues#3000]
Hello,

As https://github.com/laravel/nova-issues/issues/1271 is closed without that i understand the consequences and why its not approved, could you maybe reconsider it? Could you maybe provide me with information why this is not possible so that i understand the consequences?

---------
I would also like to have the global scopes be respected. Every Nova update i download, i do a search and replace of the following:

->newQueryWithoutScopes
with:
->newQuery

I have not found anything not working after this. Do i miss something?
---------

I would love to be able to respect the global scopes as i have build a multi tenancy system where the platform_id defines the results of the users. But without respecting the global scope, every user can access data of other platforms. I am limiting the data of the models in what to show like this:

```

    public function newQuery()
    {
        $query = parent::newQuery();
        
        $query = $query->where([
            ['platform_id', '=', $platformId],            
        ]);  

        return $query;
    }
```

As i am now replacing all newQueryWithoutScopes, is there something not working which i miss?

Thank you.

**Comment by crynobone** [comment]
Changing the structure can create huge unexpected changes to every Laravel Nova, that I wouldn't think it would be possible for consideration, until next series/major release unfortunately.

However I would think you can override `App\Nova\Resource` method to automatically register global scopes:

```php
    /**
     * Build an "index" query for the given resource.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public static function indexQuery(NovaRequest $request, $query)
    {
        return $query->getModel()->registerGlobalScopes($query);
    }
```

**Comment by nickkuijpers** [comment]
Hi,

Thank you for the response.

When i use the indexQuery, will that also work for the update and delete request? That is why i could not use the indexQuery for at first try.

So if we are able to define the $query->where([['platform_id', '=', $platformId]]) in the indexQuery like you suggest, that would be the perfect solution but it must be working for every request to prevent users deleting others their posts for example. Now it is only working for the get page.

**Comment by crynobone** [comment]
You can refer to `Laravel\Nova\PerformsQueries` to see the full lists of methods that you can override.  As for details and forms you could also consider applying policy to limit access <https://nova.laravel.com/docs/3.0/resources/authorization.html>

**Comment by nickkuijpers** [comment]
That is very nice, thank you. Is the detailQuery used for the hard delete? As i see the softDelete in the file but not the default delete.

**Comment by crynobone** [comment]
> Is the detailQuery used for the hard delete? As i see the softDelete in the file but not the default delete.

A hard delete can happen from index or detail view, I personally feel this is where Policy is more important rather than filtering the query.

**Comment by matthewjumpsoffbuildings** [comment]
@crynobone this is not completed, its not just soft deletes or resource permissions that might warrant using global scopes. There are many different reasons why global scopes would be used in an application, and just flat out ignoring them in Nova detail/update views makes zero sense. Especially since the global scopes _are_ used on index views, its completely inconsistent.

What is the rationale even? Why was the decision _ever_ made to ignore such a basic, core feature of Laravel model behaviour, but only sometimes? I understand changing it _might_ break some things so it would require a semver bump as a breaking change, but in most cases anyone who _is_ using global scopes likely already is confused and frustrated by the inconsistent usage
