### ISSUE TITLE
VaporFile - "This action is unauthorized."

### ISSUE THREAD

**Issue by 949mac** [laravel/nova-issues#3001]
- Laravel Version: 8.x
- Nova Version: 3.12 and 3.14
- PHP Version: 7.3
- Database Driver & Version: Postgres
- Operating System and Version: Vapor

### Description:

I'm not sure if there's a problem with the documentation, if I misunderstood something, or misconfigured something. But I have a couple Nova projects I'm working on moving into vapor. On both projects, using `VaporFile::make('Store Path')` yeilds...

![image](https://user-images.githubusercontent.com/23151962/97482563-8ddbd700-1913-11eb-9797-8385611840b2.png)

Any ideas? What did I miss?

**Comment by crynobone** [comment]
Hi @949mac 

I haven't go through this and test it out myself, but have you configure `UserPolicy` to allow uploading file as suggested in Vapor documentation? See <https://docs.vapor.build/1.0/resources/storage.html#authorization>

**Comment by 949mac** [comment]
Hey @crynobone, I tried to update earlier but it's been busy!

So I found https://github.com/laravel/framework/issues/32137, and it described something similar.

One of my projects is now working! w00t w00t!

My second project utilizes https://github.com/stancl/tenancy so I'm digging into that one a bit more... Closing this issue. Thanks for your comment!

**Comment by crynobone** [comment]
> One of my projects is now working! w00t w00t!

Just curious, on the project you have separate guard for user and adding additional middleware solve the problem?

**Comment by 949mac** [comment]
I just added a Gate to the AuthServiceProvider's boot method and it worked right away.

**app/Providers/AuthServiceProvider.php**
```
    public function boot()
    {
        $this->registerPolicies();

        Gate::define('uploadFiles', function ($user, $post) {
            return true;
        });
        //
    }
```

It was enough to move me forward :)

**Comment by 949mac** [comment]
I figured out the https://github.com/stancl/tenancy/ configuration and posted the solution at https://github.com/stancl/tenancy/issues/516.
