### ISSUE TITLE
Dynamic nova resources

### ISSUE THREAD

**Issue by nickkuijpers** [laravel/nova-issues#3002]
Hello,

It would be nice to be able to dynamically register Nova resources. Now its loaded as a static resource read in the files directory but it would be nice to have a functionality to register Nova resources without creating a new file. 

I could not find a method which to append to, to register a dynamic resource without having to create the Nova resource file.

**Comment by crynobone** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by alberto-bottarini** [comment]
@nickkuijpers take a look here:

https://github.com/laravel/nova-issues/issues/3151

**Comment by nickkuijpers** [comment]
@alberto-bottarini 

Thanks! Nice post!
