### ISSUE TITLE
The letter "Ə" should be converted to the letter "E" on Slug generation 

### ISSUE THREAD

**Issue by aghayeff** [laravel/nova-issues#3008]
- Laravel Version: 7.0
- Nova Version: 3.14.0
- PHP Version: 7.2.5

The letter "Ə" is a popular letter in Azerbaijan country and is used by Azerbaijani people in worldwide. İt is an additional letter of Latin Alphabet.

[https://en.wikipedia.org/wiki/%C6%8F](https://en.wikipedia.org/wiki/%C6%8F)

<img width="945" alt="Screen Shot 2020-10-29 at 17 04 16" src="https://user-images.githubusercontent.com/7493431/97578221-edb4a980-1a09-11eb-88a3-f4d2c157e536.png">

Thank You!

**Comment by crynobone** [comment]
I believe this something that should be posted to `slugify`, https://github.com/simov/slugify

**Comment by Energon7** [comment]
Hello @crynobone, 
you can add this trick where you call slugify:
   
 ```
  const slugifyMethod = require('slugify')
  slugifyMethod.extend({'ə': 'e'});
```

**Comment by crynobone** [comment]
Yes, but in slugify it either fall under charmap or locale.

I wouldn't think Laravel Nova should be managing this when it can be better managed by slugify project.

**Comment by Energon7** [comment]
I added needed letter and send PR:  https://github.com/simov/slugify/pull/93/commits/b14bd6a8002f802ef1da67918d453d27ed5265d0

**Comment by Energon7** [comment]
@crynobone now you can update slugify from 1.4.5 to 1.4.6 version.

**Comment by crynobone** [comment]
PR submitted.

**Comment by Energon7** [comment]
Thank you.
