### ISSUE TITLE
Visual Bug: Required Asterisk Breaks to New Line

### ISSUE THREAD

**Issue by xpersonas** [laravel/nova-issues#3009]
- Laravel Version: 8.12.1
- Nova Version: 3.9.1
- PHP Version: 7.4.10

### Description:
The asterisk on form labels indicating a required field have a space between the label and the asterisk which creates the possibility of the asterisk breaking onto a new line by itself.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Create a required field and play with viewport width.

<img width="620" alt="Screen Shot 2020-10-30 at 9 40 23 AM" src="https://user-images.githubusercontent.com/5023924/97720193-f783ee80-1a95-11eb-9573-3630c9a3c6e1.png">

### Possible Solution
File: nova/resources/js/components/Form/DefaultField.vue

Original...
```
        <form-label
          :label-for="field.attribute"
          :class="{ 'mb-2': showHelpText && field.helpText }"
        >
          {{ fieldLabel }}

          <span v-if="field.required" class="text-danger text-sm">{{
            __('*')
          }}</span>
        </form-label>
```
To...
```
        <form-label
          :label-for="field.attribute"
          :class="{ 'mb-2': showHelpText && field.helpText }"
        >
          {{ fieldLabel }}<span v-if="field.required" class="text-danger text-sm">{{ __('*') }}</span>
        </form-label>
```
<img width="620" alt="Screen Shot 2020-10-30 at 9 57 05 AM" src="https://user-images.githubusercontent.com/5023924/97720437-4762b580-1a96-11eb-845b-5467d0f669c2.png">

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
