### ISSUE TITLE
Nova Actions progress indication

### ISSUE THREAD

**Issue by Dontorpedo** [laravel/nova-issues#3010]
Why is there no progress indication for actions?

at least something like: resource xx of xxxx is being processed.. 

i create invoices with nova actions with takes some time, a indication of progress would be very helpfull.. are they any plans or tips how to achieve this?

thanks

**Comment by crynobone** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
