### ISSUE TITLE
Filter "per page"  to change the number of resources to show per page via relationships

### ISSUE THREAD

**Issue by inodesrl** [laravel/nova-issues#3012]
Hello, this is my request:
When I list a resource via relationship "hasmany" (in the detail page of parent), I can't see the filter  "per page" (as for normal resource listing), useful to choose the number of results.
This is very useful when I have tables in relation with a lot of record and I want to filter for a different number of results.

I know that I can change the number of resources to show per page via relationships with $perPageViaRelationship, but
I would like to be able to change this setting with a filter online.

thanks, Marco.

**Comment by crynobone** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
