### ISSUE TITLE
BelongsTo field makes duplicate database queries during update

### ISSUE THREAD

**Issue by goldmerc** [laravel/nova-issues#3013]
- Laravel Version: 8.12.13
- Nova Version: 3.14.0
- PHP Version: 7.4.11

### Description:

When I update a resource which is using the built in Nova belongsTo field, I can see in Telescope that the db query to get the existing value of the field is being called 5 times, in 3 different ways...

select * from `countries` where `countries`.`id` = 1 limit 1 (called 3 times)
select * from `countries` where `countries`.`id` = '1' limit 1 (called once)
select * from `countries` where `countries`.`id` = '1' order by `name` asc limit 1 (called once)

This is regardless of whether the field has actually changed or not.

**Comment by goldmerc** [comment]
Been digging a bit deeper - One of the queries is being called during the Scout index update. But even with Scout disabled, I'm still getting 4 queries which all seem to do the same thing...

select * from countries where countries.id = 1 limit 1 (called 2 times)
select * from countries where countries.id = '1' limit 1 (called once)
select * from countries where countries.id = '1' order by name asc limit 1 (called once)

**Comment by crynobone** [comment]
This should be expected, after the resource has been updated Nova will make few AJAX requests to pull in updated data.

**Comment by goldmerc** [comment]
When I view the request in Telescope it appears to be telling me that all of these queries are happening during the PUT request to update the data. There are a couple of additional GET requests related to the field but I'm not talking about those.

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/97860670-823a4700-1d3d-11eb-989f-0c7e6844b42f.png)

Fresh installation and tracking when user on Update page, see commit for details https://github.com/nova-issues/issue-3013/commit/d23b1eaa774071c6c5095b6d6b26ff0f3e694e93

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/97865511-499e6b80-1d45-11eb-9554-482d19c05b17.png)

To reduce the query number you can eager loads the belongs to relationship on the model (if possible).

The two other queries are coming from:

* Validation for update for `BelongsTo` field (`ResourceUpdateController.php:26`)
* Fill request to `BelongsTo` field (`ResourceUpdateController.php:32`)

**Comment by goldmerc** [comment]
Thanks for the explanation. Things are crazy here in London as we go back into lockdown on Thursday but next week when I have more time, I'll look at this again.

**Comment by crynobone** [comment]
Okay, I'm closing this for the time being, for `Validation` and `Fill` it would be hard for us to tweak it for the current release.
