### ISSUE TITLE
The resource details page label need more spacing after adding the "title" to it.

### ISSUE THREAD

**Issue by naifalshaye** [laravel/nova-issues#3014]
- Laravel Version: 8.11.2
- Nova Version: 3.13.0
- PHP Version: 7.4.12

### Description:
The resource singular label in resource details page needs more spacing after adding the "title" to it on Nova latest version.

<img width="488" alt="Screen Shot 2020-11-02 at 2 45 47 AM" src="https://user-images.githubusercontent.com/23122187/97818986-ce8e7400-1cb6-11eb-935c-73731dcfdd70.png">

### Detailed steps to reproduce the issue on a fresh Nova installation:
View any resource details page

**Comment by crynobone** [comment]
This has been fixed in `v3.14.0`. Can you upgrade to `v3.14.0` and see if the problem still persist?

**Comment by naifalshaye** [comment]
I just upgraded Nova to v3.14.0 issue still exists.

**Comment by ljmoleiro** [comment]
I've upgrade to 3.14 and  fixed, thanks @naifalshaye

**Comment by naifalshaye** [comment]
Great, Thanks @ljmoleiro
