### ISSUE TITLE
Current transaction is aborted, commands ignored until end of transaction block.

### ISSUE THREAD

**Issue by hasnatbabur** [laravel/nova-issues#3015]
- Laravel Version: 6.20.2
- Nova Version: 2.12.0
- PHP Version: 7.3.16
- Database Driver & Version: PostgreSQL 11
- Operating System and Version: Docker - Windows 10 (Version 2004)
- Browser type and version: 86.0.4240.75
- Reproduction Repository: Private

### Description:
We have created a nova tool that import posts from csv file. Script has a loop for each entry in csv file. Till October 20, 2020 everything was working fine. My models have eloquent events.

Note, if I put \DB::commit(); at very first then there is no error and posts are imported correctly.

SQLSTATE[25P02]: In failed sql transaction: 7 ERROR: current transaction is aborted, commands ignored until end of transaction block (SQL: select * from "users" where "username" = hasnat limit 1)

### Detailed steps to reproduce the issue on a fresh Nova installation:
In a nova toolbox create a loop and try to run a sql/eloquent to fetch some information from database. You should see sql transaction error for Postgres.

Does anyone face this issue earlier? Please help. Thanks

**Comment by crynobone** [comment]
Since this is a custom Nova Tool, it would be hard for me to debug whether it's actually related to Laravel Nova. 

Could you submit a reproducing code for us to debug the issue.

**Comment by hasnatbabur** [comment]
@crynobone After reading your comment again, I investigate again and finally found issue. In a method that was called by Model created event, I used try catch block but did not throw any exception intentionally. That try block had some error always in that part. That's why the error was ignore and SQL transaction was fired on next loop. Now it works fine.

Thanks a lot for your valuable time. 💯
