### ISSUE TITLE
Fractional seconds data not visualised correctly

### ISSUE THREAD

**Issue by mattyh88** [laravel/nova-issues#3017]
- Laravel Version: 7.28.4
- Nova Version: 3.13.0
- PHP Version: 7.4.2
- Database Driver & Version: MySQL 5.7.31
- Operating System and Version: Linux Debian Buster
- Browser type and version: Google Chrome 86.0.4240.111
- Reproduction Repository: /

### Description:
I'm trying to visualise a DateTime field, formatted as followed: YYYY-MM-DD HH:mm:ss.SSSSSS
My database field is a DateTime field with precision 6. 
The field is visualised as: 2020-11-02 10:00:00.000000 instead of 2020-11-02 10:00:00.111111 (value in my database)

### Detailed steps to reproduce the issue on a fresh Nova installation:
Add this to the fields() method in the Nova resource class: 

    DateTime::make('Logged at', 'logged_at')
        ->format('YYYY-MM-DD HH:mm:ss.SSSSSS')
        ->sortable(),

Thank you.

**Comment by crynobone** [comment]
Unfortunately `DateTime` will automatically convert value using `Y-m-d H:i:s` when resolving the value. See https://github.com/laravel/nova/blob/3.0/src/Fields/DateTime.php#L25-L36

I would suggest you to use the following.

```php
DateTime::make('Logged at', 'logged_at', function ($value) {
    if (! is_null($value)) {
        if ($value instanceof DateTimeInterface) {
            return $value->format('Y-m-d H:i:s.u');
        }

        throw new Exception("DateTime field must cast to 'datetime' in Eloquent model.");
    }
})
->format('YYYY-MM-DD HH:mm:ss.SSSSSS')
->sortable(),
```

**Comment by mattyh88** [comment]
Thanks for the quick reply. 
I added the code as described and it partly fixed the issue: it's only printing the first 3 digits. 
For example: 

Database value 2020-06-15 10:00:00.111222 is visualised as 2020-06-15 10:00:00.111000

**Comment by crynobone** [comment]
![Screenshot_20201103-190847.jpg](https://user-images.githubusercontent.com/172966/97978104-0f49d280-1e08-11eb-995a-2fa4fc8da91b.jpg)

that seem to be a limitation with moment.js
