### ISSUE TITLE
Empty resource icon not centered

### ISSUE THREAD

**Issue by FaridAghili** [laravel/nova-issues#3018]
- Laravel Version: 8.12.3
- Nova Version: 3.14.0
- PHP Version: 7.4.11
- Browser type and version: Google Chrome 86

### Description:
Icon is not centered in empty resource page.

![image](https://user-images.githubusercontent.com/8607021/98000343-a8291f80-1e01-11eb-9fa1-d8a0017a52d2.png)

### Fix:
This can be fixed by adding `mx-auto` to svg icon class

![image](https://user-images.githubusercontent.com/8607021/98000578-e32b5300-1e01-11eb-9da0-459e6a56ca10.png)

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/98013876-e2141900-1e35-11eb-9abc-e6be6e52bac3.png)

Unable to recreate the issue, is there anything else that could have mess up the css?
