### ISSUE TITLE
Using a JSON field in a Trend Metric

### ISSUE THREAD

**Issue by 949mac** [laravel/nova-issues#3020]
- Laravel Version: 8.x
- Nova Version: 3.x
- PHP Version: 7.4
- Database Driver & Version: Postgres

### Description:

When passing a JSON field to the metric, like this:
```
    public function calculate(NovaRequest $request)
    {
        return $this->averageByDays($request, Log::class, "data->>'temperature'");
    }
```

I get this error:

```
"message": "SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near \"temperature\"\nLINE 1: ...R', 'YYYY-MM-DD') as date_result, avg(\"data\"->>'>'temperatur...\n                                                             ^ (SQL: select to_char(\"created_at\" - interval '8 HOUR', 'YYYY-MM-DD') as date_result, avg(\"data\"->>'>'temperature'') as aggregate from \"logs\" where \"created_at\" between 2020-10-06 00:00:00 and 2020-11-04 01:15:51 group by to_char(\"created_at\" - interval '8 HOUR', 'YYYY-MM-DD') order by \"date_result\" asc)",
```

Does https://github.com/laravel/nova/pull/145 support JSON fields in Postgres? Can you update the documentation and provide an example. Thank you!

**Comment by crynobone** [comment]
The code will use utilised `Illuminate\Database\Query\Grammars\PostgresGrammar`. Based on the given code I would assume you can write it as `'data->temperature'` but i could be wrong.

**Comment by 949mac** [comment]
Hey, here's some more information for you.

The appropriate JSON SQL should be like this:

```
SELECT ..., avg((data->>'temperature')::integer) as aggregate FROM tabke
```

I was able to get the metric working, only after hardcoding the value in.

![image](https://user-images.githubusercontent.com/23151962/98063797-b842fe00-1e05-11eb-97a2-0012b6deadd4.png)

And this worked, but obviously, modifying the vendor source is no bueno.

![image](https://user-images.githubusercontent.com/23151962/98064498-4d92c200-1e07-11eb-9cd0-62d2b230a500.png)


---

A few notes:

When my `data` column has a Postgres type of `json` and I query `data->'temperature'`, I get:

![image](https://user-images.githubusercontent.com/23151962/98064287-d2c9a700-1e06-11eb-8d65-6d13871262d4.png)

But changing it to `data->>'temperature'`, I get:

![image](https://user-images.githubusercontent.com/23151962/98064304-da894b80-1e06-11eb-9b59-657c1889af13.png)

Also, because the children of a JSON field aren't type cast, one might need to cast the result to an integer, as I needed to do above.

In addition to a little TLC for JSON fields within metrics, I believe we also need to typecast the field with `::integer` as shown in my example above. 

![image](https://user-images.githubusercontent.com/23151962/98064644-a2363d00-1e07-11eb-99bc-43af21e27822.png)

Thanks again!

**Comment by crynobone** [comment]
I kinda see that's this is something that should be supported at `laravel/framework` level since adding `::integer` is postgres specific method. Based on your argument, aggregated using json field should work at all for Laravel Nova metric. 

I'll bring this up with the framework team as well.

**Comment by 949mac** [comment]
It will need to be handled at the Nova level too, because the `SELECT` arguments are in a `DB::raw(...)` method.

![image](https://user-images.githubusercontent.com/23151962/98072078-082bc000-1e1a-11eb-933e-f3ea423f86d9.png)
