### ISSUE TITLE
Action "download response" ignores name field

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#3021]
- Laravel Version: 7.28.4
- Nova Version: 3.13.0
- PHP Version: 7.2.19
- Database Driver & Version: Mysql, 5.7.24
- Operating System and Version: Windows 10 (64 bit)
- Browser type and version: Chrome (latest)

### Description:

On my action i've created a download response, but it ignores the nice name and uses the original file name.

### Detailed steps to reproduce the issue on a fresh Nova installation:

```php
    /**
     * Perform the action.
     *
     * @param  ActionFields  $fields
     *
     * @return mixed
     */
    public function handle(ActionFields $fields)
    {
        $filePath = $this->getPathToFileNameWithExtention();
        $urlToFile = Storage::disk(Enums\StorageDisk::APP_PUBLIC)
            ->url($filePath);

        $extension = pathinfo($this->getFileNameWithExtention(), PATHINFO_EXTENSION);
        $niceName = rtrim($this->getFileNameNice(), '.') . "." . $extension;

        return \Laravel\Nova\Actions\Action::download($urlToFile, $niceName);
    }
```

**Comment by crynobone** [comment]
The download feature actually generate `<a download="$niceName" href="$urlToFile" />`. HTML5 feature which depends on browser feature and limitation. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download

**Comment by preliot** [comment]
I've checked https://caniuse.com/?search=download, browser should support it. But it doesn't work, unfortunatly.
Doesn't it make more sense to also use the nice name betweem the <a> tags? Like so:

`<a download="$niceName" href="$urlToFile" />$niceName</a>`

Or perhaps drop the download attribute and use:

`<a href="$urlToFile" />$niceName</a>
`

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/98103049-61096000-1ecf-11eb-8660-9d5e5fc0fde8.png)

It might not work if not same-origin URL. 

> Or perhaps drop the download attribute and use: <a href="$urlToFile">$niceName</a>

What would this solve?

**Comment by preliot** [comment]
If you would consider using `<a href="$urlToFile">$niceName</a>` you would fix several (possible) issues:

1. This will work in all browsers, even old / niche ones
2. All the notes (exceptions) you just posted, would not be an issue.
3. There could be a reason to hide the original name. 
4. It will fix my issue!

**Comment by preliot** [comment]
@crynobone Any news on this issue?

**Comment by crynobone** [comment]
> If you would consider using <a href="$urlToFile">$niceName</a> you would fix several (possible) issues:

Tested and it does do as you suggested https://jsfiddle.net/crynobone/fshq2ko6/17/

**Comment by preliot** [comment]
Now i understand why you say:

> The download feature actually generate `<a download="$niceName" href="$urlToFile" />`

I've meant a real html link, but with your example i understand i was wrong! Thanks for your efforts!
