### ISSUE TITLE
Authorization using policies is not working

### ISSUE THREAD

**Issue by martio** [laravel/nova-issues#3022]
- Laravel Version: 8.12.3
- Nova Version: 3.14.0
- PHP Version: 7.4

### Description:

Authorization using policies is not working. I have posting disabled in my policy, but there is still a button to create a post.

### Detailed steps to reproduce the issue on a fresh Nova installation:

```
php artisan make:policy PostPolicy --model=Post
```

```
class AuthServiceProvider extends ServiceProvider
{
    protected $policies = [
        \App\Models\Post::class => \App\Policies\PostPolicy::class,
    ];
}
```

```
class PostPolicy
{
    public function create(User $user, Post $post)
    {
        return false;
    }
}
```

**Comment by crynobone** [comment]
Create a reproducing code at https://github.com/nova-issues/issue-3022/commit/3a904fe40546e282fb223f0b3026bd39259a4d06 and unable to replicate the issue.

![image](https://user-images.githubusercontent.com/172966/98103743-6fa44700-1ed0-11eb-9ad1-a6aaad1482f9.png)

**Comment by martio** [comment]
I'm sorry it's my fault :(

```
-        Gate::before(function ($user, $ability) {
-            return $user->role->is(UserRole::Administrator) ? true : null;
-        });
```
