### ISSUE TITLE
Is there any way to get Laravel action collections so fast?

### ISSUE THREAD

**Issue by MdMostaFizurRahaman** [laravel/nova-issues#3023]
- Laravel Version: 8.0
- Nova Version: 3.14
- PHP Version: 7.4
- Database Driver & Version: 5.7 (MYSQL)

### Description:
I have a inventory application with Laravel nova. On that application I am downloading any resource as pdf using [mpdf library](https://github.com/niklasravnsborg/laravel-pdf). There are some times we needs thousands of records on the pdf. But if I check thousands of records from the index layout after filtering it, it still takes much time to load the collections in Laravel nova action.
#### Here is my action code:

` /**
     * The number of models that should be included in each chunk.
     *
     * @var int
     */
    public static $chunkCount = 200000000;

    /**
     * Perform the action on the given models.
     *
     * @param  \Laravel\Nova\Fields\ActionFields  $fields
     * @param  \Illuminate\Support\Collection  $models
     * @return mixed
     */
    public function handle(ActionFields $fields, Collection $models)
    {
        if($models->count() > 1000)
        {
            return Action::danger('Maximum rows exceeded.');
        }
        $filename = "assets_".time().".pdf";
        $subtitle = $fields->subtitle;

        ini_set("pcre.backtrack_limit", "10000000000");
        $pdf = \PDF::loadView('pdf.pages.assets', compact('models', 'subtitle'), [], [
            'mode' => 'utf-8',
        ]);
        $pdf->save(Storage::path($filename));

        return Action::redirect( route('dump-download', compact('filename')) );
    }

    /**
     * Get the fields available on the action.
     *
     * @return array
     */
    public function fields()
    {
        return [
            Text::make('Subtitle', 'subtitle')
                ->rules('nullable', 'string', 'max:100')
        ];
    }`

**Comment by crynobone** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
