### ISSUE TITLE
Ability to show extra information in select list when attaching as related model

### ISSUE THREAD

**Issue by aligajani** [laravel/nova-issues#3024]
When I attach two models together using a select list, there are instances when I want more information in the select list than just the name of the person for instance. 

Many people can have similar names, so it helps here to populate extra data alongside, such as, ID or email. Is this possible in **Nova 2**? I don't see this basic feature documented anywhere. Please assist.

![image](https://user-images.githubusercontent.com/1730778/98198259-79559b00-1f20-11eb-919d-5af6c322ef41.png)

**Comment by crynobone** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
