### ISSUE TITLE
Can't load resource: TypeError: Cannot read property 'length' of undefined and Cannot create property 'currentValue' on string '<'

### ISSUE THREAD

**Issue by laraketai** [laravel/nova-issues#3026]
- Laravel Version: 8.13.0
- Nova Version: 3.14.0
- PHP Version: 7.4.0

### Description:

TypeError: Cannot read property 'length' of undefined
    at a.render (app.js?id=ab23adce198d6b5c0187:1)
    at a.t._render (vendor.js?id=3097eff3fea5a307a5a0:1)
    at a.hn.before (vendor.js?id=3097eff3fea5a307a5a0:1)
    at hn.get (vendor.js?id=3097eff3fea5a307a5a0:1)
    at hn.run (vendor.js?id=3097eff3fea5a307a5a0:1)
    at fn (vendor.js?id=3097eff3fea5a307a5a0:1)
    at Array.<anonymous> (vendor.js?id=3097eff3fea5a307a5a0:1)
    at Gt (vendor.js?id=3097eff3fea5a307a5a0:1)
Xt @ vendor.js?id=3097eff3fea5a307a5a0:1
app.js?id=ab23adce198d6b5c0187:1 false

vendor.js?id=3097eff3fea5a307a5a0:1 TypeError: Cannot create property 'currentValue' on string '<'
    at updateFilterState (app.js?id=ab23adce198d6b5c0187:1)
    at app.js?id=ab23adce198d6b5c0187:1
    at app.js?id=ab23adce198d6b5c0187:1
    at Array.forEach (<anonymous>)
    at app.js?id=ab23adce198d6b5c0187:1
    at u._withCommit (app.js?id=ab23adce198d6b5c0187:1)
    at u.commit (app.js?id=ab23adce198d6b5c0187:1)
    at u.commit (app.js?id=ab23adce198d6b5c0187:1)
    at n.commit (app.js?id=ab23adce198d6b5c0187:1)
    at app.js?id=ab23adce198d6b5c0187:1
Xt @ vendor.js?id=3097eff3fea5a307a5a0:1
Ft @ vendor.js?id=3097eff3fea5a307a5a0:1
Ht @ vendor.js?id=3097eff3fea5a307a5a0:1
(anonymous) @ vendor.js?id=3097eff3fea5a307a5a0:1
Promise.catch (async)
It @ vendor.js?id=3097eff3fea5a307a5a0:1
en @ vendor.js?id=3097eff3fea5a307a5a0:1
wn._init @ vendor.js?id=3097eff3fea5a307a5a0:1
a @ vendor.js?id=3097eff3fea5a307a5a0:1
(anonymous) @ vendor.js?id=3097eff3fea5a307a5a0:1
init @ vendor.js?id=3097eff3fea5a307a5a0:1
n @ vendor.js?id=3097eff3fea5a307a5a0:1
(anonymous) @ vendor.js?id=3097eff3fea5a307a5a0:1
d @ vendor.js?id=3097eff3fea5a307a5a0:1
(anonymous) @ vendor.js?id=3097eff3fea5a307a5a0:1
t._update @ vendor.js?id=3097eff3fea5a307a5a0:1
hn.before @ vendor.js?id=3097eff3fea5a307a5a0:1
hn.get @ vendor.js?id=3097eff3fea5a307a5a0:1
hn.run @ vendor.js?id=3097eff3fea5a307a5a0:1
fn @ vendor.js?id=3097eff3fea5a307a5a0:1
(anonymous) @ vendor.js?id=3097eff3fea5a307a5a0:1
Gt @ vendor.js?id=3097eff3fea5a307a5a0:1
Promise.then (async)
Ut @ vendor.js?id=3097eff3fea5a307a5a0:1
ee @ vendor.js?id=3097eff3fea5a307a5a0:1
(anonymous) @ vendor.js?id=3097eff3fea5a307a5a0:1
hn.update @ vendor.js?id=3097eff3fea5a307a5a0:1
t.$forceUpdate @ vendor.js?id=3097eff3fea5a307a5a0:1
(anonymous) @ vendor.js?id=3097eff3fea5a307a5a0:1
c @ vendor.js?id=3097eff3fea5a307a5a0:1
It @ vendor.js?id=3097eff3fea5a307a5a0:1
n @ vendor.js?id=3097eff3fea5a307a5a0:1
(anonymous) @ vendor.js?id=3097eff3fea5a307a5a0:1
(anonymous) @ vendor.js?id=3097eff3fea5a307a5a0:1
u @ vendor.js?id=3097eff3fea5a307a5a0:1
(anonymous) @ vendor.js?id=3097eff3fea5a307a5a0:1
setTimeout (async)
Ni @ vendor.js?id=3097eff3fea5a307a5a0:1
(anonymous) @ vendor.js?id=3097eff3fea5a307a5a0:1
requestAnimationFrame (async)
(anonymous) @ vendor.js?id=3097eff3fea5a307a5a0:1
requestAnimationFrame (async)
Si @ vendor.js?id=3097eff3fea5a307a5a0:1
L @ vendor.js?id=3097eff3fea5a307a5a0:1
Ri @ vendor.js?id=3097eff3fea5a307a5a0:1
remove @ vendor.js?id=3097eff3fea5a307a5a0:1
A @ vendor.js?id=3097eff3fea5a307a5a0:1
b @ vendor.js?id=3097eff3fea5a307a5a0:1
(anonymous) @ vendor.js?id=3097eff3fea5a307a5a0:1
t._update @ vendor.js?id=3097eff3fea5a307a5a0:1
hn.before @ vendor.js?id=3097eff3fea5a307a5a0:1
hn.get @ vendor.js?id=3097eff3fea5a307a5a0:1
hn.run @ vendor.js?id=3097eff3fea5a307a5a0:1
fn @ vendor.js?id=3097eff3fea5a307a5a0:1
(anonymous) @ vendor.js?id=3097eff3fea5a307a5a0:1
Gt @ vendor.js?id=3097eff3fea5a307a5a0:1
Promise.then (async)
Ut @ vendor.js?id=3097eff3fea5a307a5a0:1
ee @ vendor.js?id=3097eff3fea5a307a5a0:1
t.$nextTick @ vendor.js?id=3097eff3fea5a307a5a0:1
(anonymous) @ app.js?id=ab23adce198d6b5c0187:1
x @ app.js?id=ab23adce198d6b5c0187:1
(anonymous) @ app.js?id=ab23adce198d6b5c0187:1
e.<computed> @ app.js?id=ab23adce198d6b5c0187:1
o @ app.js?id=ab23adce198d6b5c0187:1
(anonymous) @ app.js?id=ab23adce198d6b5c0187:1
Promise.then (async)
o @ app.js?id=ab23adce198d6b5c0187:1
(anonymous) @ app.js?id=ab23adce198d6b5c0187:1
t @ app.js?id=ab23adce198d6b5c0187:1
(anonymous) @ app.js?id=ab23adce198d6b5c0187:1
l @ app.js?id=ab23adce198d6b5c0187:1
m @ vendor.js?id=3097eff3fea5a307a5a0:1
r @ vendor.js?id=3097eff3fea5a307a5a0:1
r @ vendor.js?id=3097eff3fea5a307a5a0:1
yt @ vendor.js?id=3097eff3fea5a307a5a0:1
Ct.confirmTransition @ vendor.js?id=3097eff3fea5a307a5a0:1
Ct.transitionTo @ vendor.js?id=3097eff3fea5a307a5a0:1
e.push @ vendor.js?id=3097eff3fea5a307a5a0:1
Ft.push @ vendor.js?id=3097eff3fea5a307a5a0:1
b @ vendor.js?id=3097eff3fea5a307a5a0:1
It @ vendor.js?id=3097eff3fea5a307a5a0:1
n @ vendor.js?id=3097eff3fea5a307a5a0:1
Qr.o._wrapper @ vendor.js?id=3097eff3fea5a307a5a0:1

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Create a new laravel install
2. add nova
3. change nova path to /api/nova
4. create a nova user

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/98238262-135d2800-1fa1-11eb-9854-beb488458134.png)

See https://github.com/nova-issues/issue-3026/commit/f7ee6a2ca6dabaa58a0669b5aa8c6a0de1395702

**Comment by laraketai** [comment]
**** In local development work fine, issue appears on production (nginx, ubuntu 16.4, DigitalOcean)

**Comment by laraketai** [comment]
<img width="1252" alt="Снимок экрана 2020-11-05 в 18 13 36" src="https://user-images.githubusercontent.com/29000827/98239819-bfe3dd80-1f92-11eb-9640-6c87c2ce1803.png">

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/98240626-a77cbe80-1fa4-11eb-9720-35f6017c2a6f.png)

Test the code using ngork and still working fine. You should check if you missed out any step when deploying the code.
