### ISSUE TITLE
Incomplete translations

### ISSUE THREAD

**Issue by martio** [laravel/nova-issues#3027]
- Laravel Version: 8.12.3
- Nova Version: 3.14.0
- PHP Version: 7.4

### Description:

Incomplete translations, eg "Create" button or "Resources" in the left column (sidebar).

<img width="1440" alt="Zrzut ekranu 2020-11-5 o 21 52 01" src="https://user-images.githubusercontent.com/133636/98295201-79ea4200-1fb1-11eb-8768-3bd6ba586893.png">

**Comment by davidhemphill** [comment]
From the language files: 

<img width="438" alt="image" src="https://user-images.githubusercontent.com/58970/98295505-4985b200-1f77-11eb-8d32-bf9eae0818ea.png">

and it's used here inside of `Resource`: 

<img width="813" alt="image" src="https://user-images.githubusercontent.com/58970/98295658-7934ba00-1f77-11eb-89d2-55d3636a59d9.png">

If you don't have a `singularLabel` method defined on the resource using the translation helper, it won't be translated. Make sure you have one set. :-)

**Comment by martio** [comment]
> singularLabel

For me, it is correct, but it does not work. @davidhemphill davidhemphillNotice that the resource is translated. The phrase "Create" is not translated. And "Resources" in the sidebar. I am using the current version of the translations

<img width="842" alt="Zrzut ekranu 2020-11-5 o 22 02 44" src="https://user-images.githubusercontent.com/133636/98296400-2973e400-1fb3-11eb-8e7d-3fe87459b8ec.png">
<img width="968" alt="Zrzut ekranu 2020-11-5 o 22 04 20" src="https://user-images.githubusercontent.com/133636/98296410-2c6ed480-1fb3-11eb-9ab3-84d8b0966883.png">
<img width="913" alt="Zrzut ekranu 2020-11-5 o 22 05 16" src="https://user-images.githubusercontent.com/133636/98296414-2da00180-1fb3-11eb-82e6-403c147e23cf.png">

**Comment by martio** [comment]
`nova/resources/views/resources/navigation.blade.php`

```
<span class="sidebar-label">{{ __('Resources') }}</span>
```

<img width="951" alt="Zrzut ekranu 2020-11-5 o 22 37 38" src="https://user-images.githubusercontent.com/133636/98299223-a43efe00-1fb7-11eb-8312-b628af5a672b.png">

but it does not work...

**Comment by martio** [comment]
@davidhemphill  I checked that the translation file was loading and it works fine in most places.

**Comment by monaye** [comment]
@martio did you find the fixes? Somehow only the "Create " part is not translated on mine as well.

**Comment by vFire** [comment]
Same thing... Not fixed yet in the new released.

**Comment by crynobone** [comment]
> Same thing... Not fixed yet in the new released.

@vFire create a new issue with full description and reproducing code if you have a problem using translation.
