### ISSUE TITLE
mb_strtoupper() expects parameter 1 to be string, array given (View: /vendor/laravel/nova/resources/views/layout.blade.php)

### ISSUE THREAD

**Issue by jorgenb** [laravel/nova-issues#3029]
- Laravel Version: v8.13.0
- Nova Version: v3.14.0
- PHP Version:  7.4.11
- Database Driver & Version: Postgresql 9.6
- Operating System and Version: macOS Catalina 10.15.6
- Browser type and version: Chrome 86.0.4240.183
- Flare: https://flareapp.io/share/v5pgMAE7#F89

### Description:

I am getting this error on a fresh L8 v8.13.0 and Nova v3.14.0 install after changing the default locale and adding a file named `action.php` within the `resources/lang` directory.

![Skjermbilde 2020-11-06 kl  10 11 32](https://user-images.githubusercontent.com/8543501/98348051-8786e280-2018-11eb-9710-5fdedb0e841b.png)

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Add a new folder to `resources/lang`. E.g. `nb`.
2. Add a file named `action.php` to the `resources/lang/en` and the `resources/lang/nb` folders.
3. Change the default locale in the `config/app.php` file to `'locale' => 'nb',` 

More info: https://flareapp.io/share/v5pgMAE7#F89

See also: #2804 (the "fix" mentioned in this issue about renaming the offending file does resolve the problem).

**Comment by crynobone** [comment]
The easiest fix is actually to copy `resources/lang/vendor/nova/en.json` to `resources/lang/vendor/nova/nb.json`. 

I'll will propose to add an artisan command to make this process easier. 

> This actually a limitation with Laravel Framework unfortunately.

**Comment by jorgenb** [comment]
> The easiest fix is actually to copy `resources/lang/vendor/nova/en.json` to `resources/lang/vendor/nova/nb.json`.

I can live with that. Thanks!
