### ISSUE TITLE
Default value does not work for BelongsTo and MorphTo fields

### ISSUE THREAD

**Issue by azurinspire** [laravel/nova-issues#3030]
This is a copy of the issue #2608 which doesn't seem to be fixed with https://github.com/laravel/nova/pull/975. Pull request was released in 3.11.0 but the same error exists still in 3.14.

---

* Laravel Version: 7.29.3 (fresh install)
* Nova Version: 3.14.0 (fresh install, no other packages)
* PHP Version: 7.4.7
* Reproduction Repository: https://github.com/kitbs/freshnova/tree/test-default
* Run `composer update` after cloning

## Description:

The default() method released in v3.4.0 does not work for BelongsTo and MorphTo fields:

* When BelongsTo is not searchable, the default value appears to be selected, but when the Create button is clicked, no value is sent in the POST request, and a "The ... field is required" validation error appears.
* When BelongsTo is searchable, no default value is selected.
* There is no ability to specify the default morphable type for a MorphTo field, and no default value is selected.

### BelongsTo (not searchable)

* Create a Post resource with a BelongsTo field and corresponding relationship on the model:

```php
BelongsTo::make('Author', 'author', User::class)
        ->default(auth()->id()),
```

* Navigate to the create route for the Post resource.
* Observe the BelongsTo field appears to be filled with the current user's name.
* Click "Create Post" without changing any fields.
* Observe the "The author field is required." validation message appears.
* Open Developer Tools > Network and find the failed POST request.
* Observe the author: key in the Form Data is empty.

### BelongsTo (searchable)

* Add a searchable BelongsTo field to the Post resource:

```php
BelongsTo::make('Co-author', 'coauthor', User::class)
        ->searchable()
        ->default(auth()->id()),
```

* Navigate to the create route for the Post resource.
* Observe the BelongsTo field has no value selected.
* As above.

### MorphTo

* Create an Image resource with a MorphTo field and corresponding relationship on the model

```php
MorphTo::make('Imageable', 'imageable')
        ->default(auth()->id())
        ->types([
            Post::class,
            User::class,
        ]),
```
    
* Note that there is no way to specify whether the Post or User type should be defaulted.
* Navigate to the create route for the Comment resource.
* Observe that no default value is selected.
* As above

**Comment by felixstoessel** [comment]
I can also verify that I have the exact same issue.

**Comment by crynobone** [comment]
As discussed in Discord this not going to be an easy fix.

File based fields need to be removed before attempting to add a new file. This is the current expected behaviour to ensure that even if you delete and skipped updating the resource, file field would no longer contain the uploaded file and the database doesn't refer to a none existing file.

**Comment by crynobone** [comment]
Unable to reproduce the issue on latest Laravel Nova. See reproducing code https://github.com/nova-issues/issue-3030/commit/23bba39f14281f42571a1534612198bd1bddabbe

![image](https://user-images.githubusercontent.com/172966/98496672-23b12380-227d-11eb-9ba7-bfce61f0f5d2.png)

**Comment by felixstoessel** [comment]
Here is our code for the field:
```
<?php

use App\Nova\User;
use Laravel\Nova\Fields\BelongsTo;

$shouldSeeUsers = Api::shouldSeeUsers(request()->user()); // true

return BelongsTo::make('Nutzer', 'user', User::class)
  ->sortable()
  ->default(request()->user()->getKey())
  ->canSee(function($request) use ($shouldSeeUsers) {
    return $shouldSeeUsers;
  });
```

We also changed the logic inside Resource::indexQuery() to filter the list of seeable users for a particular user to only 1 (self). So when the dropdown get's generated for the field, there is only a `–` and the one user inside it.

When creating a new entry with a user field, the User seems to get selected, but inside the DOM, you see that it doesn't get selected. When you manually click inside the field and select the one user manually again, everything works. So maybe a Vue related issue (maybe when filtering via indexQuery() and/or having only 1 entry for the user field to select) or something with the extra-arguments for the `make('Nutzer', 'user', User::class)`.

<img width="616" alt="user" src="https://user-images.githubusercontent.com/13189565/98520386-40942980-2272-11eb-9423-a124936cebe8.png">

**Comment by crynobone** [comment]
@felixstoessel can you update the code under https://github.com/nova-issues/issue-3030 and make it failed just like you describe? We need to reproducible code before we can debug how to fix the issue.

**Comment by felixstoessel** [comment]
@azurinspire Can you help @crynobone to create the reproducible code? I am currently not able to do this.

**Comment by azurinspire** [comment]
In this repo https://github.com/kitbs/freshnova/tree/test-default the problem goes away by updating Laravel from 7 to 8. But my project, where I have the same problem, is already in Laravel 8.13... I try to search more.

**Comment by crynobone** [comment]
@azurinspire if the error only happened on Laravel 7 then it should have something to do with framework changes between the two version. 

Right now it's very hard to make a fix without knowing the exact combination that cause the issue.

**Comment by felixstoessel** [comment]
@azurinspire Did you change something in `Resource::indexQuery()` by any chance? Do you have only 1 user to select or multiple?

**Comment by azurinspire** [comment]
@felixstoessel no, I haven't change that. In my own project problem is in team selector and there are 254 teams to select.

**Comment by felixstoessel** [comment]
Okay. So this might have something to do with either JavaScript not using `default()` correctly or `default()` in general.

**Comment by crynobone** [comment]
> no, I haven't changed that. In my own project problem is in team selector and there are 254 teams to select.

Are you using native select to show the teams or you using `searchable()` options. One would need to preload the relations while the other will only request teams based on search query.
