### ISSUE TITLE
BelongsTo field not pre-selected when creating relation for HasOne

### ISSUE THREAD

**Issue by gbuckingham89** [laravel/nova-issues#3033]
- Laravel Version: 8.13.0
- Nova Version: 3.14.0
- PHP Version: 7.4.11
- Database Driver & Version: Postgres 12
- Operating System and Version: Ubuntu 18.04 LTS
- Browser type and version: Mac OS Safari 14 (15610.1.28.1.9, 15610)
- Reproduction Repository: https://github.com/gbuckingham89/nova-issue

### Description:

I have a one-to-one relationship between a User model and a Profile model. The User model contains the HasOne relationship and the Profile model has the BelongsTo relationship (and therefore the foreign key). I have the relevant Nova resources with their relationships too (see example repo).

If I view a User model in Nova, and go to the Profile relationship section and click the "Create Profile" button. The page loads, but the "User" field (the relationship) isn't pre-selected with the User - I would expect it to.

I have another relationship, a one-to-many, where the User model has many Bookmarks. If I then try to a new Bookmark model from the view User page, the "User" field is pre-selected - which is what I would expect when creating a HasOne relationship.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Create two models with a one-to-one relationship between them, and the same Nova resources. Attempt to create a new model fro the relationship from the main model.

Another example repo is available here: https://github.com/gbuckingham89/nova-issue (see the User and Profile models / resources)

### Example of issue:

![video1](https://user-images.githubusercontent.com/1455253/98482264-2158b600-21f8-11eb-8a1b-4a12889373c7.gif)

Example of expected behaviour (from one-to-many):

![video2](https://user-images.githubusercontent.com/1455253/98482270-30d7ff00-21f8-11eb-964c-2787c2d09b15.gif)

**Comment by crynobone** [comment]
This should already fixed via laravel/nova#1042
