### ISSUE TITLE
Slug field are buggy, have a lack of functionality and bad UI

### ISSUE THREAD

**Issue by ArroWsGM** [laravel/nova-issues#3034]
- Laravel Version: 7.x | 8.x
- Nova Version: >= 3.9
- PHP Version: 7.4
- Reproduction Repository: https://github.com/ArroWsGM/nova-bug

#### 1 bug
This field can be really handy, but due to field design, it's impossible to use `hideWhenUpdating` or `readonly` with the slug field. 
To be clear, I think this
```
            Slug::make('Slug')
                ->from('name')
                ->hideWhenUpdating()
```
or
```
            Slug::make('Slug')
                ->from('name')
                ->readonly($this->checkPermissions($request))
```
would never work on updating because of this part in the `Slug.php`
```
        if ($request->isUpdateOrUpdateAttachedRequest()) {
            $this->readonly();
            $this->showCustomizeButton = true;
        }
```

I think, expected behavior with `readonly` is overriding `showCustomizeButton` property when a resource is updating, and `hideWhenUpdating` must have a highest priority.

#### 2 functionality
On updating, after you hit the `Customize` button, the slug field became a regular text input, without any "slugifying" functions, and it's just killing any usability.
![image](https://user-images.githubusercontent.com/9962071/98559470-5116c500-22af-11eb-8f4e-a98f769662a2.png)

I think, it must convert typing on the fly, or at least have that functionality on the server-side, before applying validation rules like this one:
```
        ->updateRules('unique:users,slug,{{resourceId}}')
```
Also, in some circumstances, is nice to have a customized "slugifying" provider.

#### 3 bad UI
I think, `Customize` button is ugly, especially when used with `->help()` text with link
![image](https://user-images.githubusercontent.com/9962071/98555832-10b54800-22ab-11eb-8385-551f2a361e5a.png)
Input addon looks much better
![image](https://user-images.githubusercontent.com/9962071/98557559-0a27d000-22ad-11eb-8e3b-b1f816858495.png)
especially, with state-related CSS.

Obviously, all of it can be reached in many other ways, but have some of this functionality out of the box would be very nice.

**Comment by zareismail** [comment]
In addition do not support the `Arabic` and `Persian` languages.

**Comment by ArroWsGM** [comment]
@zareismail 
> Also, in some circumstances, is nice to have a customized "slugifying" provider.
thanks, I think right about such situations

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by ArroWsGM** [comment]
@davidhemphill 
Primary this is a bug report, not a  feature request. I think field behavior when it ignores standard modificators like `hideWhenUpdating` or `readonly` is a bug.
