### ISSUE TITLE
NovaRequest user method does not return the user in tests anymore since v3.15.0

### ISSUE THREAD

**Issue by ben182** [laravel/nova-issues#3036]
- Laravel Version: 8.14.0
- Nova Version: 3.15.0
- PHP Version: 7.4.7
- Database Driver & Version: MySQL 5.7.29
- Operating System and Version: macOS Catalina 10.15.7
- Browser type and version: Chrome 86.0.4240.183

### Description:
After upgrading my Nova version from 3.14.0 to 3.15.0 I experienced failing tests. In particular the `user` method on the `NovaRequest` class injected into the `indexQuery` method on each resource does not return the user anymore. Instead, it returns null. After some debugging this does only apply to feature tests. I am authorizing my users in the tests with `$this->actingAs($user);`.

It might be caused by these fixes in the 3.15.0 update:
- Nova will bind the current request type to NovaRequest. #1068
- Nova will now apply indexQuery to make selecting resources and select all matching more consistent when not viewing from viaRelationship. #1060

**Comment by crynobone** [comment]
Can you share a sample of failing test, I need to know what are the processes occurred during the test. 

It could be related to `Nova will bind the current request type to NovaRequest` however if a test only make one request this shouldn't cause any issue, and running `actingAs()` doesn't make any request.

**Comment by ben182** [comment]
Sure.

I have a custom tool. In the tool I have a controller function that looks like this
```
public function index(NovaRequest $novaRequest)
    {
        $bots = Bot::buildIndexQuery($novaRequest, BotModel::query(), null, [], [
            'name' => 'asc',
        ])
        ->get();
```
So I am injecting the NovaRequest into the controller method and pass the object to the index query method on the Bot Resource.

The Bot indexQuery looks like that:
```
    public static function indexQuery(NovaRequest $request, $query)
    {
        if ($request->user()->hasRole('manager')) {
            return $query;
        }

        return $query->whereIn('id', $request->user()->bots->pluck('id'));
    }
```

And finally the test:
```
$user = User::factory()->create();
$user->assignRole('manager');
$this->actingAs($user);

$bot = Bot::factory()->create();

$response = $this->getJson(route('intent-test.initial.index'));
```

**Comment by crynobone** [comment]
@ben182 I attempted to recreate a similar tests but so far unable to replicate the issue. I'm not sure if I missed anything but you can look at it at https://github.com/laravel/nova/pull/1077

**Comment by ben182** [comment]
Thanks for your efforts. How can I access the laravel/nova repo?

**Comment by crynobone** [comment]
You can follow the guidelines from https://nova.laravel.com/docs/3.0/contributions.html#contributing

**Comment by ben182** [comment]
Please try the following test to reproduce the issue:

```
$user = User::factory()->create();
$this->actingAs($user);

$this->app->make('router')->get('nova-request-test/user', function (NovaRequest $request) {
    dump(app(Request::class)->user());
    dump($request->user());
})->name('nova-request-test-user');

$response = $this->getJson('nova-request-test/user');
```

The first dump returns the user
The second shouldn't

**Comment by crynobone** [comment]
I added another test and even if I run dump it still work as expected. Even if I change the code to exactly as you describe:

```php
    public function test_it_bound_nova_request_can_get_user_from_resolver()
    {
        $user = factory(User::class)->create();

        $this->actingAs($user);

        $this->app->make('router')->get('nova-request-test/user', function (NovaRequest $request) {
            dump(app(Request::class)->user()->toArray());
            dump($request->user()->toArray());
        })->name('nova-request-test-user');

        $this->getJson(route('nova-request-test-user'))
            ->assertOk();
    }
```

![image](https://user-images.githubusercontent.com/172966/98888951-edb9ac80-24d3-11eb-8828-8dd8bab57d80.png)

**Comment by ben182** [comment]
Hi,
after some more debugging I stumbled across the following behavior: I resolve the NovaRequest class in my observer to check if the request came from Nova. So if you resolve the class and hit a route then the class breaks somehow. Check this out:
```
$user = User::factory()->create();

$this->actingAs($user);

resolve(NovaRequest::class);

$this->app->make('router')->get('nova-request-test/user', function (NovaRequest $request) {
    dump($request->user());
    dump(app(Request::class)->user());
})->name('nova-request-test-user');

$this->getJson('nova-request-test/user')->dump(); 
```

The first dump should return `null`

**Comment by crynobone** [comment]
In that case I would marked this as solved.

PR laravel/nova#1074 should already cover most of the use case. However if you resolve NovaRequest outside of the request then you need to manually forget it, using the following:

```php
$this->actingAs($user);

$request = resolve(NovaRequest::class);

$this->app->forgetInstance(NovaRequest::class);

$response = $this->getJson(route('nova-request-test-user'));
```

**Comment by ben182** [comment]
Okay thanks. I modified each time I resolved the class. Just out of interest why is this needed now?

**Comment by crynobone** [comment]
> Okay thanks. I modified each time I resolved the class. Just out of interest why is this needed now?

It would allow you to get resolved `NovaRequest` when checking model policy (or any other places), which was previously not possible since `NovaRequest` was never bound to the container.

![image](https://user-images.githubusercontent.com/172966/99055971-ae26b980-25d4-11eb-8c49-983362c19f55.png)

**Comment by ben182** [comment]
Ah okay now I get it. The main problem is that in my test I create models before the actual request. When creating the models the observer gets fired and the NovaRequest class gets resolved and bound to the container. So when I do the request later in the test it uses this instance which is obviously not the actual request class. So putting `app()->forgetInstance(NovaRequest::class);` is quite dangerous in the observer because it may fix the test but during the actual request it will delete my Request from the instance right?

**Comment by ben182** [comment]
It my observer I do the following
```
$request = resolve(NovaRequest::class);

if (
    $request->isCreateOrAttachRequest() ||
    $request->isUpdateOrUpdateAttachedRequest()
) {
    // do action
}
```

**Comment by crynobone** [comment]
@ben182 That would work in some cases but for example if the container resolve `ActionRequest` from controller (`ActionRequest` extends `NovaRequest`). When you only have that, the resolved instance will only be `NovaRequest` and not `ActionRequest` as what's resolved in the Controller. The PR changed that

**Comment by ben182** [comment]
Okay I fixed the observers by doing
```
if (! app()->has(NovaRequest::class)) {
    return;
}

$request = resolve(NovaRequest::class);
if (
    $request->isCreateOrAttachRequest() ||
    $request->isUpdateOrUpdateAttachedRequest()
) {
    // do action
}
```
