### ISSUE TITLE
CSS Bug for "Standalone" Action Dropdown when table is empty

### ISSUE THREAD

**Issue by danielschweiger** [laravel/nova-issues#3039]
- Laravel Version: 8.14
- Nova Version: 3.15

### Description:

See attached image.

<img width="1067" alt="2020-11-11 um 10 20 44" src="https://user-images.githubusercontent.com/2277612/98793686-85ea5f80-2408-11eb-85e7-bb2bf9597439.png">

### Detailed steps to reproduce the issue on a fresh Nova installation:

Add a standalone action where the resource has no entries

**Comment by crynobone** [comment]
Tested on a fresh Nova application.

![image](https://user-images.githubusercontent.com/172966/99018354-d55d9680-2594-11eb-8ad1-ccb70ed254d6.png)

 By default there should be a filter dropdown on the right of action selector. Can you verify why it was missing on your screenshot (is there any configuration used for the app).

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/99028861-e796ff00-25ab-11eb-833f-52c31679ad03.png)

Managed to replicate it, issue only occur on related resources. will create a PR today.
