### ISSUE TITLE
Duplication of query/requests

### ISSUE THREAD

**Issue by LorenzoSapora** [laravel/nova-issues#3040]
- Laravel Version: 8.14.0
- Nova Version: 3.15.0
- PHP Version: 7.4

### Description:

Requests seem to be duplicated on refresh, or when using nova router.

### Detailed steps to reproduce the issue on a fresh Nova installation:

- Create a resource
- Add

```php
    public static function indexQuery(NovaRequest $request, $query)
    {
        Log::info($request);
        return $query;
    }
```
- View logs, refresh page, see duplication

![image](https://user-images.githubusercontent.com/25519274/98806922-d1edd200-2411-11eb-86c1-188a5ec7a1e0.png)

**Comment by crynobone** [comment]
Try using:

```php
info('Requesting: '.$request->url(), $request->all());
```

And you would see there actually two different requests:

![image](https://user-images.githubusercontent.com/172966/98814070-261fa300-2460-11eb-9d38-39d740e28bd4.png)
