### ISSUE TITLE
Error when customizing HasManyThrough field

### ISSUE THREAD

**Issue by paulvl** [laravel/nova-issues#3041]
- Laravel Version: 8.14.0
- Nova Version: 3.15.0
- PHP Version: 7.4.10
- Database Driver & Version: MySQL 5.7.31
- Operating System and Version: macOS Catalina 10.15.7
- Browser type and version: All browsers same error

### Description:

I cant define a custom name for HasManyThrough relationship as the way I define it for HasMany

This works for all my fields including HasMany
`HasMany::make('Facturas', 'invoices', \App\Nova\Invoice::class),
`

This Works for HasManyThrough
`HasManyThrough::make('Services'),
`

And this too
`HasManyThrough::make('Services', 'services', \App\Nova\Service::class),
`

But this doesn't
`HasManyThrough::make('Servicios', 'services', \App\Nova\Service::class),
`

and display the following error:
`Class 'Laravel\Nova\Servicio' not found`

I am missing something?

**Comment by zareismail** [comment]
Hi. I have this problem too. and this is a bug in the HasManyThrough implementation.
This field not work for resources that placed out of the `App /Nova` directory.
@davidhemphill

**Comment by zareismail** [comment]
This is solution:

current HasManyThrough `__construct`:

```
public function __construct($name, $attribute = null, $resource = null)
    {
        parent::__construct($name, $attribute);

        $resource = $resource ?? ResourceRelationshipGuesser::guessResource($name);

        $this->resourceClass = $resource;
        $this->resourceName = $resource::uriKey();
        $this->hasManyThroughRelationship = $this->attribute;
    }
```

should be change to this:

```
public function __construct($name, $attribute = null, $resource = null)
    {
        $resource = $resource ?? ResourceRelationshipGuesser::guessResource($name);

        parent::__construct($name, $attribute, $resource);


        $this->resourceClass = $resource;
        $this->resourceName = $resource::uriKey();
        $this->hasManyThroughRelationship = $this->attribute;
    }
```

@davidhemphill  @taylorotwell
