### ISSUE TITLE
Delete not working on index view

### ISSUE THREAD

**Issue by kylescousin** [laravel/nova-issues#3046]
- Laravel Version: 8
- Nova Version: 3.15
- PHP Version: 7.4
- Database Driver & Version: Mysql 5.7
- Operating System and Version: Kubuntu 20.4
- Browser type and version: Chrome

Problem: Clicking the trashcan on any index view of a resources pops up a gray layover 

How to reproduce: Click on the trashcan on a resource overview page. Screenshot: https://i.imgur.com/IV24xdx.png

Solutions tried: I upgraded to 3.15, the latest version atm, and also did $ php artisan nova:publish - problem still persist.

**Comment by crynobone** [comment]
We have dusk tests that execute the process and it run successfully. https://github.com/laravel/nova-dusk-suite/blob/master/tests/Browser/IndexTest.php#L336-L356

This is likely a usage bug or integration that could cause issue to the said project.

**Comment by kylescousin** [comment]
This is most likely a z-index issue that your dusk test does not account for

**Comment by kylescousin** [comment]
Bit rude to just ignore and close a bug report like this, especially for a paid package

**Comment by crynobone** [comment]
> This is most likely a z-index issue that your dusk test does not account for

Dusk tests already account for accessibility to mouse click.

![image](https://user-images.githubusercontent.com/172966/98929045-8de3f580-2515-11eb-8046-0bbd6ce9c64e.png)

> Bit rude to just ignore and close a bug report like this, especially for a paid package

Yes, this is a paid package however we tested the condition and unable to replicate on existing project with zero 3rd party integration.

**Comment by davidhemphill** [comment]
Can you upload a video of the issue you're having? Can you try setting up a fresh install of Nova and verify the issue exists there as well? Anything we can use to replicate.

**Comment by kylescousin** [comment]
> Can you upload a video of the issue you're having? Can you try setting up a fresh install of Nova and verify the issue exists there as well? Anything we can use to replicate.

If I can mail or PM you somewhere I can send you a login.

**Comment by davidhemphill** [comment]
Send it to nova@laravel.com. 👍
