### ISSUE TITLE
nova change dashboard locale 

### ISSUE THREAD

**Issue by OthmanAlseagh** [laravel/nova-issues#3047]
- Laravel Version: 8.13
- Nova Version: 3.15.0
- PHP Version: 704
- Database Driver & Version:

Description:
i want to change locale of the dashboard, but I couden`t found the button or dropdown  in the dashboard.main to do so.

it seems nothing added to layout.blade.php to fetch the localization.

what should I do to change dashboard locale??????????????

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
