### ISSUE TITLE
Get count of current resource and filter

### ISSUE THREAD

**Issue by poxin13** [laravel/nova-issues#305]
Would like to be able to show the basic count of a resource when being filtered or searched (records returned).

I noticed in the network requests this info is actually there grabbed via: `/nova-api/model/count?search=&filters=myfilterhere` and returns a count of exactly what I'm looking for, even when searching. Is there a way to display this via a Card or otherwise on the resource index? The built-in value cards aren't dynamic so I don't think it would work that way.

**Comment by noahlocke** [comment]
@poxin13 like this?
```
    public function calculate(Request $request)
    {
        return $this->count($request, Note::where('status_id', 2));
    }
```

**Comment by poxin13** [comment]
Using `$this->count` in a metric will try to utilize 'ranges()'. For a basic count of records returned `return $this->result()` would be better but can't figure that out. Would also be nice to have this dynamic as you are searching on a resource.

**Comment by stueynet** [comment]
It appears whenever you get a resource or filter it it makes two requests. Once for the data and the second just for the count. So this is likely a matter of handling that response and sticking it somewhere in the table (top or bottom maybe)

![screen shot on 2018-10-21 at 13-14-55](https://user-images.githubusercontent.com/1100677/47270016-a4384680-d533-11e8-9ccb-45a5a7a51bae.png)

**Comment by davidhemphill** [comment]
Nova now has this.

**Comment by novocent** [comment]
How can you access this count in a custom card?

**Comment by jbrooksuk** [comment]
Custom cards would need to calculate this themselves.

**Comment by damarinov1** [comment]
How can you use `$this->count()` with filtered results? For me it always returns the all unfiltered results.

**Comment by nikoo-eshratabadi** [comment]
can someone please help with this. i also want the count of filtered results and index query.
