### ISSUE TITLE
Auto close showCreateRelationButton Modal

### ISSUE THREAD

**Issue by cao-minh-duc** [laravel/nova-issues#3050]
- Laravel Version: 8
- Nova Version: 3.15
- PHP Version: 7,4
- Database Driver & Version: MySQL 8
- Operating System and Version: Window
- Browser type and version: Chrome
- Reproduction Repository: https://github.com/###/###

### Description:
Auto close model when showCreateRelationButton and modal have file field

![image](https://user-images.githubusercontent.com/17726941/99139386-aade0d00-266a-11eb-9bb1-2e6316fbb4c2.png)

![image](https://user-images.githubusercontent.com/17726941/99139392-b0d3ee00-266a-11eb-9e2b-1813c931d33e.png)

![image](https://user-images.githubusercontent.com/17726941/99139395-b7fafc00-266a-11eb-9f80-4268a8a271b3.png)

**Comment by crynobone** [comment]
I have attempted to fix this issue with laravel/nova#1030 and able to avoid this behaviour on Chrome + Mac. 

@davidhemphill It might be best if modal can only trigger close if we explicitly click on the faded overlay, cancel button or escape button.

**Comment by crynobone** [comment]
I personally unable to replicate the issue on Chrome (Mac) and Chrome (Windows 10 via Parallel). 
Oddly enough when `form-file-input` click event is triggered, it's not executing `Modal.close()` event but that seem to occur on your installation.

![image](https://user-images.githubusercontent.com/172966/99625818-fe39cc00-2a6b-11eb-8244-27d11bcc37f9.png)

![image](https://user-images.githubusercontent.com/172966/99625822-009c2600-2a6c-11eb-8584-85f37de1b4a0.png)
