### ISSUE TITLE
Nova action triggered via a hasMany does not have the relation id in the action.

### ISSUE THREAD

**Issue by nickkuijpers** [laravel/nova-issues#3051]
It would be nice to have the ID of the relation of where the action is triggered.

**Comment by nickkuijpers** [comment]
I now do this for example;

```php
$referer = request()->headers->get('referer');
$referer = explode('/', $referer);
$relationId = last($referer);
```

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
