### ISSUE TITLE
Some fields are not emitting change events

### ISSUE THREAD

**Issue by goldmerc** [laravel/nova-issues#3052]
- Nova Version: 3.15.0

I notice that the currency field and the textarea field don't emit events on change like other field do.

In both cases I can fix this by adding `@input="handleChange"` to the input (and rebuilding nova)

**Comment by crynobone** [comment]
Will make a PR on this however I also marking this as feature request since AFAIK this is an internal feature on Laravel Nova and was never documented for public usage.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
