### ISSUE TITLE
displayUsing doesn't use value from resolveUsing

### ISSUE THREAD

**Issue by goldmerc** [laravel/nova-issues#3053]
As far as I understand the value passed to the displayUsing callback uses the value from the resolveAttribute method and as such, if a resolveUsing callback is set, it is ignored.

There may be good reason for this! But at first glance, it seems to me that it would make sense if the value passed to the displayUsing callback comes from the resolveUsing callback if one is set.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
