### ISSUE TITLE
Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead.

### ISSUE THREAD

**Issue by SlyDave** [laravel/nova-issues#3054]
- Laravel Version: 8.14.0
- Nova Version: 3.15.0
- PHP Version: 7.4

### Description:

Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead.

**Comment by crynobone** [comment]
We'll consider this on the next-series. However as for now it's still safe to use `moontoast/math` as mentioned by Ramsey himself, https://github.com/laravel/nova-issues/issues/2270#issuecomment-583044259
