### ISSUE TITLE
Code field json format not working

### ISSUE THREAD

**Issue by henryavila** [laravel/nova-issues#3055]
- Laravel Version: 8.15.0
- Nova Version: 3.15.0
- PHP Version: 7.4

### Description:
In Code field, the `->json()` code format is not working. Data is display as text

### Detailed steps to reproduce the issue on a fresh Nova installation:
In Nova Resource add the field:
``` php
Code::make('Data')->json(),
```
Instead of a formatted code, will display a plain text

**Comment by crynobone** [comment]
Did you casts `data` to `array`, `object` or `collection`?

**Comment by henryavila** [comment]
Hi @crynobone, I have not cast.

I tried  casting to `array` and now it works, but I believe that a -=>json()` should be able to format a json string.
A `->json()` format that don't work on json content and just in array seens worng for me.

Besides, the documentation don't inform that the json format just work on array data.


Its working in my app now (with the array cast), but I keep believing its a error in Laravel Nova.

As you can see here: https://github.com/laravel/nova-issues/issues/2942 the `Code::make('Data')->json(),` works for json string until Nova v3.10. It was fixed in  v3.12 and stopped working in future version

**Comment by crynobone** [comment]
Based on changes on https://github.com/laravel/nova/pull/993/files the cast requirement is expected as the test model has been updated and this is more of a outdated documentation rather than a bug.

**Comment by henryavila** [comment]
Thanks @crynobone
