### ISSUE TITLE
Provide hide() for all kind of fields

### ISSUE THREAD

**Issue by TheSETJ** [laravel/nova-issues#3056]
Currently, `hide()` method with the following implementation exists only in the `ID` field:

```php
public function hide()
{
    $this->showOnIndex = false;
    $this->showOnDetail = false;
    $this->showOnCreation = false;
    $this->showOnUpdate = false;

    return $this;
}
```

But it can be useful for other fields too. In various cases, I wished I had that for fields like `Text`, `Number`, and `BelongsToMany`. It's especially useful for `BelongsToMany` field when you want to display pivot fields and you're forced to implement in on the related resource ([because that's how you handle it](https://nova.laravel.com/docs/1.0/resources/relationships.html#pivot-fields)) to be able to make it work, but you really don't want to display it on the related resource.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
`BelongsToMany` or any `Field` extends `Macroable` so adding this feature should already be doable if your project requires it.

https://tighten.co/blog/the-magic-of-laravel-macros/
