### ISSUE TITLE
[Feature Request] hide create/update/delete/search on nested resources (HasMany)

### ISSUE THREAD

**Issue by vesper8** [laravel/nova-issues#3057]
I know how to hide the create button in general using

```
    public static function authorizedToCreate(Request $request)
    {
            return false;
    }
```

What I want to know is how to hide the create button for nested resources

So if I'm viewing a Post and I have a HasMany field to display its Comments, I want the create button to be there for creating a new post, but I want to hide it in the HasMany('Comments') section

I tried this but that doesn't work

```
    public static function authorizedToCreate(Request $request)
    {
        if ($request->has('viaResource')) {
            return false;
        }

        return false;
    }
```

Many thanks

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/99535998-b328a600-29e4-11eb-8b5d-8e75093f9ff7.png)

In `DockPolicy` you can add the following method:

```php
    public function addShip(User $user, Dock $dock)
    {
        return false;
    }
```

**Comment by vesper8** [comment]
thanks @crynobone that's useful.. however isn't there a way to hide the create button for ALL nested resources, always? Some of my resources have 10+ HasMany nested resources and if I need to add a new method 10x it gets tedious
