### ISSUE TITLE
`Pivot Fields` don't have access to the selected resource id 

### ISSUE THREAD

**Issue by rickschippers** [laravel/nova-issues#3059]
- Laravel Version: 7.29.3
- Nova Version: 3.15.0
- PHP Version: 7.4.12
- Operating System and Version: Ubuntu 20.04

I'm running into the same issue as described here: https://github.com/laravel/nova-issues/issues/2187, but my usecase is slightly different, and cannot be solved by the suggestion there.

I have a many-to-many relationship with some pivot fields on the pivot table. In my case it's Channel and Campaign. 

Now I want to attach a Campaign to a Channel using a belongsToMany field with the pivot fields added to it.

On the attach screen I want to access the Channel resource or resource id. I need this because the options for the (select) pivot fields are dependent on the Channel. But on there I don't seem to have access to the resourceId. 

The request is coming from, and it doesn't have the needed data:
`GET /nova-api/channels/creation-pivot-fields/campaigns?editing=true&editMode=attach HTTP/2.0`

**Comment by rickschippers** [comment]
@davidhemphill thanks

**Comment by oseintow** [comment]
@rickschippers how did you resolve it?
