### ISSUE TITLE
Request: Defining the colors of a partition matrix

### ISSUE THREAD

**Issue by albalooshi** [laravel/nova-issues#306]
It would be very useful of the if I can define the colors of a partition matrix while assigning the labels to it. so for example if something is completed it should be marked green, not red. This will create confusion for the end user who is using Nova.

![screen shot 2018-08-29 at 10 06 49 am](https://user-images.githubusercontent.com/13213888/44771311-4ca0de80-ab73-11e8-8384-e47947ee9840.png)

**Comment by shane-smith** [comment]
Yes, please. In my case, I'd simply like to have more contrasting colours - so the ability to specify a list would be helpful. I don't need to tie them to particular values.

For example, I have three possible options and having something like Red/Blue/Green would make it easier to tell them apart at a glance:
![image](https://user-images.githubusercontent.com/943942/47263268-c63ac480-d545-11e8-95c3-f027c9f0f85e.png)

**Comment by GigaMick** [comment]
This is essential functionality. I am partitioning between two types and the default colors (red shade orange and orange shade red) are pretty much identical unless you look closely. Not great.

**Comment by albalooshi** [comment]
Any updates on this issue?

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
