### ISSUE TITLE
Listing ActionEvents on Resource screen breaks when custom auth guard is defined 

### ISSUE THREAD

**Issue by duncmc** [laravel/nova-issues#3062]
- Laravel Version: 8.5.1
- Nova Version: 3.15.0
- PHP Version: 7.4.9
- Database Driver & Version: MySQL 5.7.30
- Operating System and Version:MacOS 10.14.6
- Browser type and version: Safari 14.0.1
- Reproduction Repository: https://github.com/###/###

### Description:

My application has two authentication systems – one for members who register on the public site, and one for administrative users who use Nova.

The front end authentication system uses a Member model while Nova uses the conventional User model.

To facilitate this I have two guards defined in `config.auth.guards`. The public guard for members is defined on  `config.auth.guards.web` and the Nova guard is defined on `config.auth.guards.nova`.

It looks like this…

    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'members',
            'passwords' => 'members',
        ],

        'nova' => [
            'driver' => 'session',
            'provider' => 'users',
            'passwords' => 'users',
        ],
    ],

I have two corresponding auth providers defined on `config.auth.providers` which looks like this…

    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\Models\User::class,
        ],

        'members' => [
            'driver' => 'eloquent',
            'model' => App\Models\Member::class,
        ],
    ],

The Nova authentication guard is defined in `config.nova.guard`' It looks like this…

    'guard' => 'nova',

There are several actions available to Users in the Nova admin system. When viewing a Resource which has been the target of an Action, the Actions table fails to render and I see the following error…

"Class name must be a valid object or string"

Having followed the stack trace I have pinpointed the source of the error to line 46 of `Nova\Actions\ActionEvent` where the `user()` method is defined as follows…

    /**
     * Get the user that initiated the action.
     */
    public function user()
    {
        return $this->belongsTo(
            config('auth.providers.'.(config('nova.guard') ?? 'users').'.model'), 'user_id' // <-- Line 46
        );
    }

When the default authentication guards are used this works fine but changing the auth guard as I have done breaks the path retrieval for the `auth.providers.xxxxx.model` attribute. This is easily corrected by replacing line 46 as follows…

    public function user()
    {
        return $this->belongsTo(
            config('auth.providers.'.(config('auth.guards.'.(config('nova.guard') ?? 'users').'.provider')).'.model') // <-- Line 46
        );
    }

### Detailed steps to reproduce the issue on a fresh Nova installation:

Define a new authentication guard in `config.auth`. (It can use the default provider.)

    'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
        
        'nova' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
    ],

Edit `config.nova.guard` to use the newly defined auth guard.

     'guard' => 'nova',

Generate and register a new Action.

Log in to Nova and perform the action. 

Navigate to the Resource upon which the action was performed.

The Actions table fails to render and an error message is displayed.

**Comment by crynobone** [comment]
PR made https://github.com/laravel/nova/pull/1086
