### ISSUE TITLE
Remote style

### ISSUE THREAD

**Issue by andrewminion-luminfire** [laravel/nova-issues#3063]
Any thoughts on adding a `Nova::remoteStyle()` method similar to `Nova::remoteScript()`?

Use case: allows loading remote stylesheets for webfonts or any number of CDN-hosted packages (Leaflet, Docsify, etc. provided by unkg.com, cdnjs.com, etc.).

**Comment by andrewminion-luminfire** [comment]
I have a PR ready to go…just need to coordinate with my organization’s authorized GitHub user for the source code repo.

**Comment by crynobone** [comment]
I would say better to try sending a PR so we can have a look at it. 👍🏼

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by andrewminion-luminfire** [comment]
Sorry @crynobone…just got my PR set up and saw that you fixed a week ago.

Thanks!
