### ISSUE TITLE
Case insentitive search not work onto json columns

### ISSUE THREAD

**Issue by yammycode** [laravel/nova-issues#3064]
As I understand, this problem has been noticed for a long time. Can you please tell me if there is a way to implement case-insensitive search in json columns with built-in tools? I am using a language pack for multiple languages and the lack of search is a problem. DB mysql 5.7, utf8mb4_unicode_ci. Nova 3.15.0

**Comment by davidhemphill** [comment]
What issues have listed this before? What exactly are you running into. Have any example code to display the issue? What database? What platform. Please fill out a new issue with the required details from our issue template and we'd be glad to take a look.
