### ISSUE TITLE
The "app/App/Nova" directory does not exist.

### ISSUE THREAD

**Issue by Gelurban** [laravel/nova-issues#3065]
- Laravel Version: ^8.0
- Nova Version: v3.15.0
- PHP Version: 7.4.11
- Database Driver & Version:
- Operating System and Version: Homestead

### Description:
I just installed Nova. When I try to go in the browser to the app.test/nova route, I get the following error:

Symfony\Component\Finder\Exception\DirectoryNotFoundException
The "app/App/Nova" directory does not exist.

It seems that the 
Nova::resourcesIn(app_path('Nova')); 
in NovaApplicationServiceProvider is returning a wrong folder.

If I hardcode it to /home/vagrant/code/myapp/app/App/Nova then it works fine.

Any tip on what I'm doing wrong, or how could I fix this?

Thanks

**Comment by davidhemphill** [comment]
Does `app/Nova/User.php` exist? If not, it's likely you didn't run `php artisan nova:install` when installing Nova.

**Comment by Gelurban** [comment]
Hello @davidhemphill 
Yes, I did run php artisan nova:install and User.php was created on app/App/Nova/User.php

**Comment by crynobone** [comment]
it's seem there some issue with your setup. However given the info above it not possible for us to replicate the issue as `app_path('Nova')` should return the expected path, and the functionality itself came from Laravel Framework core and not Nova.

**Comment by Gelurban** [comment]
Hello @crynobone, thanks for your reply.
app_path('Nova') does indeed return the expected path.
I mean, it returns the relative path: 'app/App/Nova', which is a valid folder. 
However, for some reason, Nova::resourcesIn(app_path('Nova')) doesn't detects it as a valid folder. 
With the absolute path of the directory: /home/vagrant/code/myapp/app/App/Nova it works fine...

**Comment by crynobone** [comment]
> app_path('Nova') does indeed return the expected path.
> I mean, it returns the relative path: 'app/App/Nova', which is a valid folder.

By default it should return `app/Nova` and not `app/App/Nova`. I don't know what happen on your environment so we don't have enough information to suggest any fixes.

**Comment by Gelurban** [comment]
Hello @crynobone,
The only changes in my environment are that everything is inside app/App, instead of app/. So the Nova folder is in app/App/Nova

The files changed are:

**In composer.json:**
```
"psr-4": {
            "App\\": "app/App/",
        },
```

**And in bootstrapp/app.php:**
```
use App\Application;
$app = (new Application(dirname(__DIR__)))->useAppPath('app/App');
```
**The Application.php located in the app/App folder:**
`<?php
namespace App;

class Application extends \Illuminate\Foundation\Application
{
    protected $namespace = 'App\\';
}
`

**Comment by crynobone** [comment]
You shouldn't use relative path when defining `useAppPath()`

#### composer.json:
```json
        "psr-4": {
            "App\\": "app/App/",
        },
```

#### bootstrapp/app.php

```php
$app = (new Illuminate\Foundation\Application(
    $_ENV['APP_BASE_PATH'] ?? dirname(__DIR__)
))->useAppPath(dirname(__DIR__).'/app/App');
```

See reproducing code https://github.com/nova-issues/issue-3065/commit/acf0b7ca7c551bffccc4046ba5b4dda130ef8bc9

**Comment by Gelurban** [comment]
My fault. It's working great now. 
Thank you very much @crynobone
