### ISSUE TITLE
Case insentitive search not work onto json columns

### ISSUE THREAD

**Issue by yammycode** [laravel/nova-issues#3066]
- Laravel Version: 8.15.0
- Nova Version: 3.15.0
- PHP Version: 7.4.12
- Database Driver & Version: mysql 5.7

### Description:
As I understand, this problem has been noticed for a long time (https://github.com/laravel/nova-issues/issues/509#issuecomment-461373010). Can you please tell me if there is a way to implement case-insensitive search in json columns with built-in tools? I am using a language pack for multiple languages and the lack of search is a problem.

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Create some column in migration, like: $table->json('title');
2. Add some data, example: {"en": "News", "ru": "Новость"}
3. Create Nove resource with search field.
4. Try search:
4.1. https://prnt.sc/vnz8d6
4.2. https://prnt.sc/vnz8jb

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by yammycode** [comment]
Why was it closed? I think this is exactly a bug! I asked if there is a way to overcome it at the moment, but that does not mean that it should be left. The search is not working correctly.

**Comment by danieljaniga** [comment]
Hi @yammycode i temporarily resolved this by overriding `applySearch` Resource method a replaced his foreach function with this implementation:
```php
foreach (static::searchableColumns() as $column) {
    $query->orWhere(
        \DB::raw('LOWER(' . $model->getConnection()->getQueryGrammar()->wrap($model->qualifyColumn($column)) . ')'),
        $likeOperator,
        static::searchableKeyword($column, strtolower($search))
    );
}
```

**Comment by yammycode** [comment]
@danieljaniga Thank you!
