### ISSUE TITLE
Bypassing nova routes is pain!

### ISSUE THREAD

**Issue by JonathanDoelan** [laravel/nova-issues#3067]
After a couple of hours I finally found a solution. But it doesn’t really feel good.

```
Route::get('{template?}/{detail?}', function ($template = 'startpage', $detail = '')
{
	return $template . ' … ' . ($detail ?? '');
})
	->where('template', '^(?!' .trim(config('nova.path'), '/'). '|nova-api|nova-vendor)[^\/?#]+')
	->where('detail', '(.*)');
```

In my app I want to send all url-requests to one controller (or closure).
The problem is that also nova routes are getting in there. So we need to bypass all nova-routes.

It could be easier I guess. What about:

```
Route::get('{template?}/{detail?}', 'PageController')
	->where(['template', '!=', 'admin|nova-api|nova-vendor']);
```

or

```
Route::get('{template?}/{detail?}', 'PageController')
	->ignoreNovaRoutes();
```
;)

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
This should work.

```php
Route::get('/{template?}/{page?}', function ($template = 'startpage', $page = null) {
    return response()->json(compact('template', 'page'));
})->fallback();
```

**Comment by JonathanDoelan** [comment]
@crynobone Thanks a lot! That’s a great solution. Why can’t we find this in the official documentation?

**Comment by crynobone** [comment]
It's kinda a customization that highly depends on usage whether you using path or domain, and I just found it by chance when reviewing this issue today.
