### ISSUE TITLE
Title of Resource Attach page shows "undefined"

### ISSUE THREAD

**Issue by infostreams** [laravel/nova-issues#3068]
- Laravel Version: 7.28.4
- Nova Version: 3.15
- PHP Version: 7.4.11
- Database Driver & Version: MySQL 5.7.31
- Operating System and Version: MacOS 10.14.6
- Browser type and version: Firefox 83
- Reproduction Repository: https://github.com/###/###

### Description:

In some cases the "attach resource" page shows uses "undefined" for all the singular verb mentions of the resource you're trying to attach

### Detailed steps to reproduce the issue on a fresh Nova installation:

The resource you want to attach something to:

```php
<?php

namespace App\Nova;

use Illuminate\Http\Request;
use Laravel\Nova\Fields\BelongsToMany;
use Laravel\Nova\Fields\Text;
use Laravel\Nova\Fields\ID;

class Lessoncomponent extends Resource
{
    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static $model = \App\Models\Lessoncomponent::class;

    /**
     * The single value that should be used to represent the resource when being displayed.
     *
     * @var string
     */
    public static $title = 'title';

    /**
     * The columns that should be searched.
     *
     * @var array
     */
    public static $search = [
        'id', 'title',
    ];

    /**
     * Get the displayable label of the resource.
     *
     * @return string
     */
    public static function label() {
        return 'Lesonderdelen';
    }

    /**
     * Get the displayable singular label of the resource.
     *
     * @return string
     */
    public static function singularLabel() {
        return 'Lesonderdeel';
    }

    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [
            ID::make(__('ID'), 'id')->sortable(),

            Text::make('Oefeningen', 'exercises')->onlyOnIndex(),

            BelongsToMany::make('Oefeningen', 'exercises', Exercise::class)->hideFromIndex(true),
        ];
    }
}
```

The resource that is being attached ("Exercise") can be anything, but in my case it's this;

```php
<?php

namespace App\Nova;

use Illuminate\Http\Request;
use Laravel\Nova\Fields\ID;

class Exercise extends Resource
{
    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static $model = \App\Models\Exercise::class;

    /**
     * The single value that should be used to represent the resource when being displayed.
     *
     * @var string
     */
    public static $title = 'title';

    /**
     * The columns that should be searched.
     *
     * @var array
     */
    public static $search = [
        'id', 'title', 'description',
    ];

    /**
     * Get the displayable label of the resource.
     *
     * @return string
     */
    public static function label()
    {
        return 'Oefeningen';
    }

    /**
     * Get the displayable singular label of the resource.
     *
     * @return string
     */
    public static function singularLabel()
    {
        return 'Oefening';
    }

    /**
     * Get the fields displayed by the resource.
     *
     * @param \Illuminate\Http\Request $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [
            ID::make(__('ID'), 'id')->sortable(),
        ];
    }
}
```

If you now try to attach an Exercise to a Lessoncomponent, it will show "Attach undefined" and confuse every single user of this admin panel.

The problem is in these two lines in Lessoncomponent:

```php
            Text::make('Oefeningen', 'exercises')->onlyOnIndex(),

            BelongsToMany::make('Oefeningen', 'exercises', Exercise::class)->hideFromIndex(true),
```

-> The BelongsToMany is defined **after** the Text field that uses the same field ($resource->exercises). If you swap the Text:: and BelongsToMany:: fields the problem doesn't occur. (You could use any field instead of Text::, I'm just using Text:: here to illustrate that this problem occurs within Nova itself and without help from any external libraries)

Previously listed as https://github.com/laravel/nova-issues/issues/1831 but re-opening because it's easily verifiable and reproduceable.

**Comment by infostreams** [comment]
<img width="845" alt="Screenshot 2020-11-23 at 15 08 49" src="https://user-images.githubusercontent.com/1132744/99972167-7a9b1a80-2d9e-11eb-959c-7e433ad90ac6.png">

**Comment by infostreams** [comment]
@davidhemphill Why did you close it? Did I pull that screenshot out of thin air? Or is your argument that this is expected behavior?

**Comment by crynobone** [comment]
@infostreams PR has been merged.

![image](https://user-images.githubusercontent.com/172966/100286321-91fc2280-2fad-11eb-99a8-a5d593910ad4.png)

**Comment by infostreams** [comment]
@crynobone Thanks, that's great news! In this case I apologize for my tone in the previous comment, thanks for sorting this.

**Comment by crynobone** [comment]
@infostreams no problem.

**Comment by infostreams** [comment]
Thanks, I did that just now.
