### ISSUE TITLE
Soft deleting an Actionable model causes its ActionEvent history to be deleted permanently

### ISSUE THREAD

**Issue by murat906** [laravel/nova-issues#3069]
- Laravel Version: 7.29.3
- Nova Version: 3.15.0
- PHP Version: 7.4.12
- Database Driver & Version: MySQL 14.14
- Operating System and Version: Ubuntu 16.04.7 LTS
- Browser type and version: Chrome 86.0.4240.193
- Reproduction Repository: -

### Description:
When a model that uses the `Laravel\Nova\Actions\Actionable` trait gets soft deleted through Nova, all existing `Laravel\Nova\Actions\ActionEvent` entries associated with it get deleted permanently. I'm guessing it's because `ActionEvent` does not use `Illuminate\Database\Eloquent\SoftDeletes` trait, causing `$model->actions()->delete();` 
 statement in `Laravel\Nova\Http\Controllers\ResourceDestroyController::handle()` to delete everything. I also noticed that in `Laravel\Nova\Http\Controllers\ResourceForceDeleteController::handle()`, force delete versions of deletion methods are used while for ActionEvents the same deletion statement as in `ResourceDestroyController` is used.

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Add `SoftDeletes` and `Actionable` traits to the `User` model.
2. Create a new user in Nova dashboard. Go to display page for the user which should show the create event in Actions section.
3. Delete, then restore the user in Nova dashboard.
4. On the display page for the restored user, Actions section should list the delete and restore events, but the create event will be gone.

----

### Current Behavior

* Soft deleting resource will delete all action_events for the resource.
* Force deleting resource will delete all action_events for the resource.

### Expected Behavior

* Soft deleting resource doesn't remove any action_events for the resource.
* Force deleting resource will delete all action_events for the resource.

**Comment by crynobone** [comment]
Can you update the issue with following details, I see what you expect to see on softdelete and restore, but what about softdelete and force delete:

```markdown
### Current Behavior

* Soft deleting resource will delete all action_events for the resource.
* Force deleting resource will delete all action_events for the resource.

### Expected Behavior

<!-- Can you provide what you would assume the expected behavior . -->
```

**Comment by murat906** [comment]
This is how I think it should work.
- Soft deleting a resource: No changes to existing `ActionEvent`s
- Restoring a resource: No changes to existing `ActionEvent`s
- Force deleting a resource: Force delete existing `ActionEvent`s

With the expected behavior in mind, I think it makes sense for `ActionEvent` to continue _not_ using `SoftDeletes` trait.

**Comment by FaridAghili** [comment]
I think action events shouldn't be deleted for a soft deleted model, but the action for soft deleting and restoring that model should be added to its action events.
Force deleting the model should of course delete all of its action events.
