### ISSUE TITLE
Nova-Dusk-Registering-Global-Elements

### ISSUE THREAD

**Issue by shashitejatripurari** [laravel/nova-issues#3070]
- Laravel Version: 7.29.3
- Nova Version: 3.15.0
- PHP Version: 7.4.11
- Database Driver & Version:
- Operating System and Version: windows 10 pro
- Browser type and version: Chrome 73

### Description:

In nova-dusk where we have to register global selectors or override the Laravel\Nova\Testing\Browser\Pages\Page;;

### Detailed steps to reproduce the issue on a fresh Nova installation:

Visit any resource eg: Create which extends Laravel\Nova\Testing\Browser\Pages\Page;

**Comment by crynobone** [comment]
Please provide detail about the issue. What do you mean by `In nova-dusk where we have to register global selectors or override the Laravel\Nova\Testing\Browser\Pages\Page;`

**Comment by shashitejatripurari** [comment]
> Please provide detail about the issue. What do you mean by `In nova-dusk where we have to register global selectors or override the Laravel\Nova\Testing\Browser\Pages\Page;`

<?php

namespace Tests\Browser\Pages;

use Laravel\Nova\Testing\Browser\Pages\Page as BasePage;

abstract class Page extends BasePage
{
    /**
     * Get the global element shortcuts for the site.
     *
     * @return array
     */
    public static function siteElements(): array
    {
        return [
            '@file' => '#__media__files',
            '@custom-input'     => 'input.w-full.form-control.form-input.form-input-bordered.input'
        ];
    }
}

before nova 3.14 version nova-dusk-suit was not included for testing, so I have added few global selectors in the above file stored in tests/Browser/Pages/ where I can use the selectors in all the dusk test pages.

In 3.14 version nova-dusk-suite is included for testing which comes with the above file in vendor folder, now how do I register the global selectors in this file?

I tried to override this Class but it requires URL method stub function as mandatory,  I think this function is not required to register the elements globally, then what is the solution for it?

**Comment by shashitejatripurari** [comment]
namespace Tests\Browser\Pages;

use Laravel\Nova\Testing\Browser\Pages\Page as BasePage;

abstract class Page extends BasePage
{
    /**
     * Get the global element shortcuts for the site.
     *
     * @return array
     */
    public static function siteElements(): array
    {
        return [
            '@file' => '#__media__files',
            '@custom-input'     => 'input.w-full.form-control.form-input.form-input-bordered.input'
        ];
    }
}

before nova 3.14 version nova-dusk-suit was not included for testing, so I have added few global selectors in the above file stored in tests/Browser/Pages/ where I can use the selectors in all the dusk test pages.

In 3.14 version nova-dusk-suite is included for testing which comes with the above file in vendor folder, now how do I register the global selectors in this file?

I tried to override this Class but it requires URL method stub function as mandatory,  I think this function is not required to register the elements globally, then what is the solution for it?

**Comment by crynobone** [comment]
> In 3.14 version nova-dusk-suite is included for testing which comes with the above file in vendor folder, now how do I register the global selectors in this file?

What's not possible now? I haven't test it out but you should be able to extends the method normally, and you just using this to test your Nova app, right?

**Comment by shashitejatripurari** [comment]
> > In 3.14 version nova-dusk-suite is included for testing which comes with the above file in vendor folder, now how do I register the global selectors in this file?
> 
> What's not possible now? I haven't test it out but you should be able to extends the method normally, and you just using this to test your Nova app, right?

Yeah I'm using to test for my Nova app, now I'm not able to use those as mentioned in the [document dusk#global-shorthand-selectors](https://laravel.com/docs/8.x/dusk#global-shorthand-selectors) and gets the below error

<img width="889" alt="bug-selector" src="https://user-images.githubusercontent.com/69587984/100081223-c87e5400-2e6c-11eb-81eb-9d96f7826482.PNG">

**Comment by crynobone** [comment]
Post a reproducing code so I can check the issue. Still not clear or understand if there any issue to begin with.

**Comment by shashitejatripurari** [comment]
**Actual test file**
namespace Tests\Browser\Documents;

use Laravel\Dusk\Browser;
use Laravel\Nova\Testing\Browser\Pages\Create;
use Tests\DuskTestCase;

class CreateDocumentResourceTest extends DuskTestCase
{
    /**
     * A Dusk test example.
     *
     * @return void
     */
    public function testCreateDocumentResource()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                    ->visit(new Create('documents'))
                    ->waitForText('Create Document', 60)
                    ->type('@name', 'test-document')
                    ->attach('@file', base_path('storage/seeds/test_image.png'))
                    ->create()
                    ->waitForText('The document was created', 60);
        });
    }
}

_**Reference files**_

**create.php file from vendor which is used in CreateDocumentResourceTest.php**

namespace Laravel\Nova\Testing\Browser\Pages;

use Laravel\Dusk\Browser;
use Laravel\Nova\Nova;

class Create extends Page
{
    use HasSearchableRelations;

    public $resourceName;

    /**
     * Create a new page instance.
     *
     * @param  string  $resourceName
     * @return void
     */
    public function __construct($resourceName)
    {
        $this->resourceName = $resourceName;
    }

    /**
     * Get the URL for the page.
     *
     * @return string
     */
    public function url()
    {
        return Nova::path().'/resources/'.$this->resourceName.'/new';
    }

    /**
     * Run the inline create relation.
     */
    public function runInlineCreate(Browser $browser, $uriKey, callable $fieldCallback)
    {
        $browser->click("@{$uriKey}-inline-create")->pause(500);

        $browser->elsewhere('.modal', function ($browser) use ($fieldCallback) {
            $fieldCallback($browser);

            $browser->create()->pause(250);
        });
    }

    /**
     * Click the create button.
     */
    public function create(Browser $browser)
    {
        $browser->click('@create-button')->pause(500);
    }

    /**
     * Click the create and add another button.
     */
    public function createAndAddAnother(Browser $browser)
    {
        $browser->click('@create-and-add-another-button')->pause(500);
    }

    /**
     * Assert that the browser is on the page.
     *
     * @param  Browser  $browser
     * @return void
     */
    public function assert(Browser $browser)
    {
        $browser->pause(500);
    }

    /**
     * Assert that there are no search results.
     */
    public function assertNoRelationSearchResults(Browser $browser, $resourceName)
    {
        $browser->assertMissing('@'.$resourceName.'-search-input-result-0');
    }

**Comment by shashitejatripurari** [comment]
> Post a reproducing code so I can check the issue. Still not clear or understand if there any issue to begin with.
> 
> I do see why you need to register `siteElements()`, you can use `@{field.attribute}` directly for `FileField` (if I understand the error correctly). Most file tests in `nova-dusk-suite` uses `file` as attribute so that why there's `[dusk="file"]` in the tests.

This is not only with @file selector but with other selectors too

**Comment by crynobone** [comment]
Tested with https://github.com/nova-issues/issue-3070/commit/bd6f65c64826f6f592d607760c999182386c76fb and have no issue using `@file` or other selectors.

![image](https://user-images.githubusercontent.com/172966/100096626-3ccded00-2e97-11eb-95ef-4e78ef0b6f39.png)
