### ISSUE TITLE
Overriding indexQuery() to use include withTrashed() throws an error on action responses

### ISSUE THREAD

**Issue by alexpgates** [laravel/nova-issues#3071]
- Laravel Version: 7.29.3
- Nova Version: 3.15.0
- PHP Version: 7.4.2
- Database Driver & Version: MySQL 8.0.19
- Operating System and Version: Ubuntu 18.04.3

### Description:

I'm overriding a Nova resource to always include `withTrashed()`.

```
    // Override the index query to show trashed
    public static function indexQuery(NovaRequest $request, $query)
    {
        return $query->withTrashed();
    }

```

This works fine to always include soft deleted models on index listings inside Nova. 

With the latest update, I now get an error when running an action against a resource.

```
Call to undefined method Illuminate\Database\Eloquent\Builder::withTrashed()

Call to undefined method Illuminate\\Database\\Eloquent\\Builder::withTrashed() at /.../vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:50)
```

Perhaps there's a better way to override the index query to always include `withTrashed()` - but for now, as a temporary workaround, I've adjusted `indexQuery()` to this:

```
    // Override the index query to show trashed
    public static function indexQuery(NovaRequest $request, $query)
    {
        if(!isset($request->action)){
            return $query->withTrashed();
        }
        return $query;
    }

```

Is it possible that this is related to:

"Nova will now apply indexQuery to make selecting resources and select all matching more consistent when not viewing from viaRelationship. #1060"
In the latest release?

**Comment by crynobone** [comment]
> Perhaps there's a better way to override the index query to always include withTrashed()

Resource come with filter that allows you to toggle between the options. So that's not a good default.

> but for now, as a temporary workaround, I've adjusted `indexQuery()` to this

This seem to be a good solution, but I would tweak it as:

```php
use Laravel\Nova\Http\Requests\ActionRequest;

    /**
     * Build an "index" query for the given resource.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public static function indexQuery(NovaRequest $request, $query)
    {
        if (! $request instanceof ActionRequest) {
            return $query->withTrashed();
        }

        return $query;
    }
```

You can refer to https://github.com/laravel/nova-issues/issues/2266 to see why the changes has been added.

**Comment by alexpgates** [comment]
@crynobone That works! Thank you for providing a better solution. I really appreciate your help.
