### ISSUE TITLE
Closing parenthesis doesn't properly show in action modal help text

### ISSUE THREAD

**Issue by preliot** [laravel/nova-issues#3073]
- Laravel Version: 7.28.4
- Nova Version: 3.14.0
- PHP Version: 7.2.19
- Database Driver & Version: 5.7.24
- Operating System and Version: Windows 10 (64 bits)
- Browser type and version: Chrome (latest), Firefox (latest)

### Description:

Closing parenthesis ')' doens't show properly in help text. Observed this in latest chrome and firefox. See example:

![image](https://user-images.githubusercontent.com/5418196/100062873-99e28800-2e30-11eb-87b8-af7893275c2e.png)

translation file:

```php

\\..
 'ExportOrderRemarkHelp' => 'Inclusief het order veld "Opmerking koper" (<strong>vinkje aan</strong>). Dit is het opmerking veld van een order.',
'ExportOrderItemRemarkHelp' => 'Inclusief het order artikel veld "Opmerking" (<strong>vinkje aan</strong>). Dit is het opmerking veld op artikel niveau.',
```

Couldn't find the cause, perhaps i'm making an obvious error? Tried to replace <strong> with <b>, same effect.

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/100076888-a987be00-2e7c-11eb-82c9-a1df749ac9b0.png)

![image](https://user-images.githubusercontent.com/172966/100077053-d9cf5c80-2e7c-11eb-8c4f-027fc4b8f044.png)

It seem to be an issue with `font-style: italic` with the font. Will communicate with the team on how to handle this.

**Comment by preliot** [comment]
Perhaps the Nova font doens't have italic and the browser tries to implent it's own? When i set the font to 'sans-serif' the issue is also gone.

**Comment by crynobone** [comment]
> Perhaps the Nova font doens't have italic and the browser tries to implent it's own? When i set the font to 'sans-serif' the issue is also gone.

Had verified there a bug with font https://github.com/googlefonts/nunito/issues/26

**Comment by preliot** [comment]
Gues we will wait on those people, thanks for investigating!

**Comment by crynobone** [comment]
I'm marking this as stale since we don't have any solution for now but it's in my to do list and will monitor googlefonts/nunito#26 from time to time.

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/100294405-aea25580-2fc1-11eb-9265-a1f1754048f4.png)

Looks like it has been fixed.
