### ISSUE TITLE
Add a suffix to Partition Metric

### ISSUE THREAD

**Issue by xoco70** [laravel/nova-issues#3074]
- Laravel Version: 8.15.0
- Nova Version: 3.15.0
- PHP Version: 7.4
- Database Driver & Version: Psql
- Operating System and Version: ubuntu 20.04
- Browser type and version: Chrome

### Description:

![Screenshot from 2020-11-24 11-23-37](https://user-images.githubusercontent.com/5855577/100081631-88f14100-2e47-11eb-90a2-9262f1a3a579.png)

I use partition metrics to display quantity and not counts. In my case, a user uses 13.43% of solar energy, and 86.57% from the grid.
I need the quantity to be in kWh like below:

```
Conso réseau (58 kWh - 86.57%)
Autoconsomation (9 kWh - 13.43%)
(67 kWh total)

```

Is it possible ?

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
