### ISSUE TITLE
&users_per_page= not adhered to on page refresh

### ISSUE THREAD

**Issue by keironwaites** [laravel/nova-issues#3075]
- Laravel Version: 7.29.3
- Nova Version: 3.15.0
- PHP Version: 7.4.12
- Database Driver & Version: mySQL 5.7.28
- Operating System and Version: macOS Catalina 10.15.7 (19H15)
- Browser type and version: Chrome 87.0.4280.67
- Reproduction Repository: n/a

### Description:

When visiting a resource page I am able to change the Per Page drop down to load more than the default number of records. When I do this, ?users_per_page=[chosen option] is appended to the URL.

However, if I refresh this page, ?users_per_page= is ignored.

I would like and expect this value to be recognised and utilised, especially since I can link to other filter options by serialising that data. Alternatively, I would expect ?users_per_page= to be handled in the same way as the other filter options (i.e. by being passed as a serialised string).

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Visit a fresh resource page (e.g. Users).
2. Change the Per Page option to something other than the default (e.g. 100).
3. Observe that more rows are loaded successfully.
4. Refresh the page.
5. Observe that the URL still has ?users_per_page=[chosen option] in it, but value in the Per Page option has reverted back to the default and the number of rows loaded also adheres to the default.

**Comment by crynobone** [comment]
PR submitted.
