### ISSUE TITLE
Nova-Dusk-Custom-Selector

### ISSUE THREAD

**Issue by shashitejatripurari** [laravel/nova-issues#3077]
### Description:
 
With reference to #3070 

### Detailed steps to reproduce the issue on a fresh Nova installation:

If you can please try with below files, this is my exact requirement, I'm facing a problem by adding custom global selectors in Page.php file, please try to add any custom selector in page.php as shown below, I took @file as custom selector as example, you may take other example not only the file.

namespace App\Nova;

use App\Nova\Fields\MultiFiles;
use Illuminate\Http\Request;
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Fields\Text;

class Document extends Resource
{
    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static $model = \App\Models\Document::class;

    /**
     * The single value that should be used to represent the resource when being displayed.
     *
     * @var string
     */
    public static $title = 'id';

    /**
     * The columns that should be searched.
     *
     * @var array
     */
    public static $search = [
        'id',
    ];

    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [
            ID::make(__('ID'), 'id')->sortable(),
            Text::make('Name'),
            MultiFiles::make(__('Files'), 'files')
                ->withMeta(['multiple' => true]),
        ];
    }

    /**
     * Get the cards available for the request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function cards(Request $request)
    {
        return [];
    }

    /**
     * Get the filters available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function filters(Request $request)
    {
        return [];
    }

    /**
     * Get the lenses available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function lenses(Request $request)
    {
        return [];
    }

    /**
     * Get the actions available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function actions(Request $request)
    {
        return [];
    }
}

<img width="819" alt="add_file" src="https://user-images.githubusercontent.com/69587984/100193898-bce96680-2f1a-11eb-8148-0287e08a4c00.PNG">

I took @file selector as an example for this issue as nova fields Multifiles doesn't have dusk selector so I have registered this id='#__media__files' in custom global selector, please try to add any custom selector in page.php file and test it

### Adding custom selector
namespace Tests\Browser\Pages;

use Laravel\Dusk\Page as BasePage;

abstract class Page extends BasePage
{
    /**
     * Get the global element shortcuts for the site.
     *
     * @return array
     */
    public static function siteElements()
    {
        return [
            '@file' => '#__media__files',
        ];
    }
}

### Testing
namespace Tests\Browser\Resources;

use App\Models\Document;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Laravel\Dusk\Browser;
use Laravel\Nova\Testing\Browser\Pages\Create;
use Tests\DuskTestCase;

class DocumentTest extends DuskTestCase
{
    use DatabaseTransactions;

    /**
     * A Dusk test example.
     *
     * @return void
     */
    public function testCreateDocumentResource()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs(1)
                ->visit(new Create('documents'))
                ->waitForText('Create Document', 60)
                ->type('@name', 'test-document')
                ->attach('@file', base_path('storage/seeds/Document.pdf'))
                ->create()
                ->waitForText('The document was created', 60);

            $document = Document::latest()->first();

            $this->assertSame('test-document', $document->name);
            $this->assertNotNull($document->file);
        });

        Document::query()->each(function ($document) {
            $document->delete();
        });
    }
}

**Comment by crynobone** [comment]
Nova doesn't provide multiple upload. Any custom field should provide it's own `dusk` attribute if there a requirement for it and not the responsibility of `Testing`.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
