### ISSUE TITLE
Actions are not being passed to soft deleted resource

### ISSUE THREAD

**Issue by TheSETJ** [laravel/nova-issues#3078]
I have a resource with some actions on it. When I soft delete it and go to its detail page, I do not see the action selector. I debugged using Vue.js devtool and noticed to the action is being passed to `action-selector` component. Is it intentional? How can I enable an action to be displayed for a soft deleted resource?

@davidhemphill Sorry for mentioning you, but I need to find a solution ASAP.

Thanks in advance.

**Comment by crynobone** [comment]
> Is it intentional? How can I enable an action to be displayed for a soft deleted resource?

A soft deleted resource is technically a deleted resource (with capability to be restored). Nova doesn't offer any options to enable an action to be display until the resource is restored.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by TheSETJ** [comment]
> > Is it intentional? How can I enable an action to be displayed for a soft deleted resource?
> 
> A soft deleted resource is technically a deleted resource (with capability to be restored). Nova doesn't offer any options to enable an action to be display until the resource is restored.

There is no trick or anything? I really really need this.

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/100205940-afdf6e00-2f40-11eb-8b2e-32e0d9ce7fb1.png)

After further checking it seem that it's possible to run action, not sure what's missing on your setup.

**Comment by TheSETJ** [comment]
@crynobone I can't share my exact source code. Let me know what thins are important, so I can provide some minimal code snippets to further investigate this issue.

**Comment by crynobone** [comment]
> Let me know what thins are important, so I can provide some minimal code snippets to further investigate this issue.

I just updated `laravel/nova` tests to verify against the scenario and everything is working as expected (without changing the code). So it might be a bug related to your environment. Can you try rebuilding the scenario on a fresh installation?

**Comment by TheSETJ** [comment]
I removed `vendor` directory and then ran `composer install`. I still don't see actions on the soft-deleted resource.

Based on `composer.lock` I have `laravel/nova` version `3.15.0` and `laravel/framework` version `7.29.2`.

**Comment by TheSETJ** [comment]
@crynobone 

I'm truly sorry! I've put a code in `actions` method to only include actions if the model is not soft deleted.
It's my second time that I report something here and I realize it was my own fault. :man_facepalming: I am embarrassed.
I'm going to close this as it's not a bug at all.
