### ISSUE TITLE
Resource::$showPollingToggle typed as int

### ISSUE THREAD

**Issue by shaffe-fr** [laravel/nova-issues#3079]
Hi,
Nova 3.14 introduced a new Resource property `$showPollingToggle` that is typed as `int` instead of `bool`.

```php
/**
 * Indicates whether to show the polling toggle button inside Nova.
 *
 * @var int
 */
public static $showPollingToggle = false;
```

Thank you,
Karel

**Comment by davidhemphill** [comment]
Fixed via https://github.com/laravel/nova/commit/88fa43201522e9b6123dfbdf005204dbd640e600
