### ISSUE TITLE
Remove BelongsTo relation

### ISSUE THREAD

**Issue by age007nt** [laravel/nova-issues#308]
When a relation is selected, it can't be deleted.
![00316_screenshot](https://user-images.githubusercontent.com/16705814/44774675-5e3ab400-ab7c-11e8-85c6-112759852a8e.png)
How can I delete a relation? (set the _null_ value to the field _poll_id_ in the table)

**Comment by johnnydee8** [comment]
same here, seems like an easy thing to do, yet I can't find a way around it

**Comment by jasonlav** [comment]
Able to reproduce. Definitely appears to be a bug.

**Comment by satoved** [comment]
Same issue on many Selects in the Nova, starting from the default Select field. Maybe there should be an option like ->nullable() or ->optional() for all fields using Select, which will remove the 'disabled' attributed from the first option.

**Comment by dillingham** [comment]
This would be solved by removing `disabled` from the first select option

BelongsToField.vue line 43

```html
<option value="" disabled="disabled" selected="selected">Choose User</option>
```

And letting an empty value store as null for nullable relationships
Essentially undoing the selection made, that's how I expected it to work personally.

**Comment by dillingham** [comment]
Duplicate https://github.com/laravel/nova-issues/issues/89
