### ISSUE TITLE
Laravel 8 install 

### ISSUE THREAD

**Issue by 8108905** [laravel/nova-issues#3080]
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for laravel/nova * -> satisfiable by laravel/nova[3.15.0].
    - laravel/nova 3.15.0 requires ../vendor/symfony/console ^5.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
jason@MacBook-Pro novaLaravel %

**Comment by crynobone** [comment]
Have you setup `repositories` to either use path or composer based on the installation guide? 

https://nova.laravel.com/docs/3.0/installation.html#installing-nova

Please share your `composer.json` file.
