### ISSUE TITLE
Nova Metrics issue

### ISSUE THREAD

**Issue by dimaMatveev** [laravel/nova-issues#3082]
- Laravel Version: 7.29
- Nova Version: 3.10.0
- PHP Version: 7.4
- Database Driver & Version: MySQL 8
- Operating System and Version: ubuntu 20
- Browser type and version: Chrome latest

### Description:

Seems that method `currentRange()`(\Laravel\Nova\Metrics\Value) doesn't work properly as far as Browser's timezone is taken into consideration.
This part of code 
`return [
                now($timezone)->today(),
                now($timezone),
            ];` 
specifically `now($timezone)->today()` returns Carbon with midnight time in App's timezone(UTC in my case), but what it should return is the time of midnight in Browser's timezone converted into App's timezone. As result metrics that are fetched from DB are not accurate(taking into account that App and DB timezones are the same, all in UTC in my case).

Example:

-  for example my browser's timezone is `Europe/Minsk` so `now($timezone)->today()` returns "2020-11-26 00:00:00.000000" and this time is used for DB query as well, but in fact it should be "2020-11-25 21:00:00.000000" in order to get accurate results.

The solution I suggest is following:
`
return [
                today($timezone)->tz(config('app.timezone')),
                now($timezone)->tz(config('app.timezone')),
            ];
`
Please elaborate on it.

**Comment by crynobone** [comment]
I understand the issue and yeah the fix should be able to do it.

But I will need sometimes to build up a good feature tests example when doing PR for this. Will add this on my backlog.

**Comment by basherr** [comment]
@crynobone Would you allow me to take this and work on it?

**Comment by crynobone** [comment]
@basherr sure but the fix definitely need to include feature tests to ensure we fixed the problem.

p/s: I personally have lots of bad experience dealing with timezone :joy:

**Comment by basherr** [comment]
@crynobone thanks for allowing me though the repo cloning does not work for me.(https://nova.laravel.com/docs/3.0/contributions.html).

![image](https://user-images.githubusercontent.com/10073316/100495840-28c50c80-3171-11eb-8113-761dca4bce5d.png)

**Comment by crynobone** [comment]
I assume you already linked and has access to `laravel/nova`, then you should use your github username and not email address. Or use ssh style.

**Comment by basherr** [comment]
I have an account on **Laravel Nova** but that's not premium. The `repository` seems not found with valid `creds` though

`fatal: repository 'https://github.com/laravel/nova.git/' not found`

**Comment by dimaMatveev** [comment]
@crynobone If you want I can help you with fix

**Comment by crynobone** [comment]
@dimaMatveev sure

**Comment by dimaMatveev** [comment]
@crynobone Pls add me to repo then

**Comment by crynobone** [comment]
Sorry I don't have access to do it. The only access is via https://nova.laravel.com/docs/3.0/contributions.html

**Comment by dimaMatveev** [comment]
@crynobone I face the same issue `fatal: repository 'https://github.com/laravel/nova.git/' not found`

**Comment by crynobone** [comment]
Just wait until I send a PR for this.
