### ISSUE TITLE
Exception Call to a member function getAuthIdentifier() on null in Actions/ActionEvent.php

### ISSUE THREAD

**Issue by 4n70w4** [laravel/nova-issues#3083]
- Nova Version: 3.15.0

### Description:

Case: I use Nova with disabled `Laravel\Nova\Http\Middleware\Authenticate` and `Laravel\Nova\Http\Middleware\Authorize`. Without login, user, etc. User is `null` value everywhere. But on run actions I get exception:

```json
{
    "message": "Call to a member function getAuthIdentifier() on null",
    "exception": "Error",
    "file": "/var/www/app/vendor/laravel/nova/src/Actions/ActionEvent.php",
    "line": 316,
...
}
```

Workaround:

Replace `$request->user()->getAuthIdentifier()` to `$request->user() ? $request->user()->getAuthIdentifier() : null` in `Actions/ActionEvent.php`.

```sql
ALTER TABLE `action_events` CHANGE COLUMN `user_id` `user_id` BIGINT(20) UNSIGNED NULL ;
```

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by 4n70w4** [comment]
Workaround 2: use https://github.com/jrseliga/pseudo for get Guest Users Entity

```
composer require agilesdesign/pseudo
```

`config/auth.php`

```php
'guards' => [
    // To use with web guard
    'web' => [
        'driver' => 'pseudo',
        'provider' => 'users',
    ],
    
    // To use with api guard
    'api' => [
        'driver' => 'pseudo-token',
        'provider' => 'users',
    ],
],
```
