### ISSUE TITLE
Notification feed/center

### ISSUE THREAD

**Issue by asivaneswaran** [laravel/nova-issues#3084]
It would be great to have a notification feed/center. It would be really useful to allow users to keep an eye of some changes that might have happened when they were away and it will developers to be able to hook into the Laravel Notifications easier.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
