### ISSUE TITLE
Page not updating with navigating between subpages of the same tool, e.g. /myTool/page-1 -> /myTool/page-2

### ISSUE THREAD

**Issue by cord** [laravel/nova-issues#3085]
- Laravel Version: 7
- Nova Version: #3.15
- PHP Version: 7.4

### Description:

When navigating between pages of the same tool  e.g.

`/myTool/page-1` -> `/myTool/page-2`

the content is not updated.

### Detailed steps to reproduce the issue on a fresh Nova installation:

install

https://novapackages.com/packages/digital-creative/collapsible-resource-manager 

and a tool with pages, e.g. 

https://novapackages.com/packages/digital-creative/nova-dashboard

which is using the same route, but different parameters to the url.

### Related:
https://github.com/laravel/nova-issues/issues/3049 -> https://github.com/laravel/nova/pull/1083
https://github.com/laravel/nova-issues/issues/2719

**Comment by crynobone** [comment]
`Detail.vue` already contains the following:

```js
  watch: {
    resourceId: function (newResourceId, oldResourceId) {
      if (newResourceId != oldResourceId) {
        this.initializeComponent()
      }
    },
  },
```

This should already cover the use case. Is there anyway I can test this on a basic Laravel Nova apllication without using the package.

**Comment by cord** [comment]
@crynobone thanks for checking, actually I messed up here and just corrected the name of the issue. I can confirm direct navigation between resources updates the content.

Just got some information from @milewski that he later will add more details to this issue.

**Comment by crynobone** [comment]
@cord @milewski please provide steps to replicate this on a basic Nova installation (without additional packages) so I can replicate the issue locally and verify the issue.

**Comment by crynobone** [comment]
Closing this for as it seem this issue need to be fixed via `digital-creative/nova-dashboard`.
