### ISSUE TITLE
Frontend blocked until resource count request has finished

### ISSUE THREAD

**Issue by cord** [laravel/nova-issues#3086]
- Laravel Version: 7
- Nova Version: 3.15
- PHP Version: 7.4
- Database Driver & Version:
- Operating System and Version: #MacOS 11
- Browser type and version: Chrome latest

### Description:

While working with a resource with slow query (...another topic why this exists...) the GUI frontend blocks (not clickable or scrollable) after loading the index items and displaying a otherwise complete frontend until the 

`/nova-api/myResource/count`

has finished.

This request should be done asynchronously to allow users to interact with the app even before the resource count is displayed.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
