### ISSUE TITLE
No PHP 8 support

### ISSUE THREAD

**Issue by iruoy** [laravel/nova-issues#3087]
- Laravel Version: 8.16.0
- Nova Version: 3.15.0
- PHP Version: 8.0.0

### Description:
PHP 8 compatibility isn't included in the `composer.json`.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Try to install Laravel Nova on a machine with PHP 8.

**Comment by crynobone** [comment]
Support for PHP 8 currently work in progress.

**Comment by davi5e** [comment]
For informational purposes, is there any timeline on this to set expectations accordingly?

**Comment by driesvints** [comment]
Nova is currently blocked by Scout which is blocked by Algolia PHP SDK itself. I've started working on a PR here: https://github.com/algolia/algoliasearch-client-php/pull/644

I've given several options to take the PR further but it's mostly in the hands of Algolia now. The PR is failing on some Algolia keys which only they can look into. I'm going to pick up work on the PR hopefully on Monday to see if I can also get the PHP 7.4 & 8 builds to the point of the failing keys.

**Comment by tahacankurt** [comment]
Is there any update about this issue?

**Comment by driesvints** [comment]
@tahacankurt if this issue is still open and doesn't have any new comments then no there wasn't any update.

**Comment by driesvints** [comment]
Actually there is! We've removed the algolia dev dependency from scout so we could rag php 8 support but nova is still blocked through testbench dusk which is blocked by algolia.

**Comment by powellblyth** [comment]
Looks like Algolia is ready... https://github.com/algolia/algoliasearch-client-php/pull/644#issuecomment-749496481

**Comment by briandotdev** [comment]
> Looks like Algolia is ready... [algolia/algoliasearch-client-php#644 (comment)](https://github.com/algolia/algoliasearch-client-php/pull/644#issuecomment-749496481)

And it sounds like it's thanks to @driesvints 👏

**Comment by davidhemphill** [comment]
I believe this should be fixed due to https://github.com/laravel/nova/pull/1109. Will be pushed in the next release.

**Comment by mathieutu** [comment]
@davidhemphill Could we tag the release quickly? (even if it has just that in it)
It's blocking upgrades. 

Thanks.

**Comment by iruoy** [comment]
@mathieutu Nova (and other Laravel products) are released on wednesday, so it shouldn't be too long now.

**Comment by mathieutu** [comment]
@iruoy ok thanks, didn't know that!

**Comment by osteel** [comment]
Sorry – is this available? I'm trying to update my setup after upgrading to PHP 8 and this is what I get:

```
Problem 1
    - laravel/nova[v3.9.0, ..., 3.18.0] require php ^7.2.5 -> your php version (8.0.0) does not satisfy that requirement.
    - Root composer.json requires laravel/nova ^3.9 -> satisfiable by laravel/nova[v3.9.0, ..., 3.18.0].
```

I can't seem to access Nova's repository (is it private?) so I'm not sure what has been done recently, nor if the release that was mentioned is available yet.

**Comment by mathieutu** [comment]
Nope, nothing tagged yet. (and actually the releases are not on Wednesday for laravel products, according to the previous release dates)

**Comment by osteel** [comment]
@mathieutu thanks for the quick reply. Where do you see the release tags?

**Comment by crynobone** [comment]
Laravel Nova scheduled released are every 2 weeks on Tuesday (US timezone) unless there a priority bugfix that we need to patch.

The support for PHP 8 should be released on the 5th of January (tomorrow)

**Comment by driesvints** [comment]
All Laravel releases are *usually* done on Tuesdays.

**Comment by osteel** [comment]
Hi there, I've upgraded Nova and as a result the Composer dependencies are correctly installing.

But I now get PDO method signature errors:

```
Declaration of Doctrine\DBAL\Driver\PDOConnection::query() must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs)
```

[This issue](https://github.com/laravel/nova-issues/issues/3088) seems related. Essentially, the signature of `PDOConnection::query()` has changed with `doctrine/dbal` [v2.12](https://github.com/doctrine/dbal/blob/3.1.x/UPGRADE.md#pdo-signature-changes-with-php-8) for PHP 8 support, in a way that is incompatible with Nova.

Upgrading to `doctrine/dbal` v3 would apparently fix it, but Nova currently prevents it to maintain support for Laravel 7.

Is there a way around this or is PHP 8 effectively not supported yet?

Thanks

**Comment by driesvints** [comment]
@osteel Upgrade both Laravel and DBAL 2.x to the latest versions. This should fix that.

**Comment by osteel** [comment]
@driesvints I don't know how I missed that but it did the trick! Thanks for the quick response
