### ISSUE TITLE
Upgrade requirements doctrine to ^3.

### ISSUE THREAD

**Issue by abkrim** [laravel/nova-issues#3088]
Problem 1
    - laravel/nova is locked to version 3.15.0 and an update of this package was not requested.
    - laravel/nova 3.15.0 requires doctrine/dbal ^2.9 -> found doctrine/dbal[v2.9.0, ..., 2.12.x-dev] but it conflicts with your root composer.json require (^3.0).

**Comment by crynobone** [comment]
Only Laravel Framework 8 support Doctrine 3 while Laravel Nova 3.x will support Laravel Framework v7 and v8. 

At the moment it's not safe to allow `"doctrine/dbal": "^2.9|^3.0"` as this would break Laravel Framework v7 if `v3.0` get resolved.

**Comment by abkrim** [comment]
I don't understand well.

You say: " Laravel Nova 3.x provide support for Laravel Framework v7 and v8."


I've Laravel Framework 8, and Laravel Nova 3

```
"require": {
        "php": "^7.3",
        "ext-json": "*",
        "64robots/nova-fields": "^0.17.0",
        "armincms/json": "^0.5.1",
        "david-griffiths/nova-dark-theme": "^1.0",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^1.0",
        "gregoriohc/laravel-nova-theme-responsive": "^0.8.1",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.0",
        "laravel/horizon": "^5.0",
        "laravel/nova": "~3.0",
        "laravel/tinker": "^2.0",
        "maatwebsite/excel": "^3.1",
        "spatie/ssh": "^1.4"
    },
```

but
```
composer require doctrine/dbal
Using version ^3.0 for doctrine/dbal
./composer.json has been updated
Running composer update doctrine/dbal
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/nova is locked to version 3.15.0 and an update of this package was not requested.
    - laravel/nova 3.15.0 requires doctrine/dbal ^2.9 -> found doctrine/dbal[v2.9.0, ..., 2.12.x-dev] but it conflicts with your root composer.json require (^3.0).
```

**Comment by crynobone** [comment]
1. `laravel/nova` already require `"doctrine/dbal": "^2.9"` so that application should already be able to use it.
2. `doctrine/dbal` v3 is only supported by `laravel/framework` v8 and above.
3. `laravel/nova` supports `laravel/framework` v7 and v8.
4. allowing `laravel/nova` to require `doctrine/dbal` v3 will cause issues to everyone using Laravel Nova with Laravel Framework v7.

**Comment by crynobone** [comment]
Marking this as `next-series`  or when we removed support for Laravel Framework 7. Will revisit this when the time come.
