### ISSUE TITLE
Replace/extend NovaRequest in order to sanitize user input before validation

### ISSUE THREAD

**Issue by JonathanDoelan** [laravel/nova-issues#3092]
- Laravel Version: 8.16.1
- Nova Version: 3.15.0
- PHP Version: 7.4.2

### Description:

I need to sanitize some inputs in Nova. What is the best way to achieve this?
Normally I would create a custom Request class and put my sanitization into prepareForValidation().

How can I achieve this?

**Comment by crynobone** [comment]
You should be able to use `Field::fillUsing()` method.

**Comment by JonathanDoelan** [comment]
@crynobone Thx. The problem is that `Field::fillUsing()` is called after validation.
This is not what we want in specific cases.

For example, when we have a rule `min:6` and the user input is `__test__` (where underscore stands for space). If we run a sanitization-method that trims the whitespaces (here underscores), it should throw an error, but because sanitization happens after validation it will be valid …

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by JonathanDoelan** [comment]
Aaaah … we can put the [validation logic](https://laravel.com/docs/8.x/validation#quick-writing-the-validation-logic) inside the fillUsing-callback!
Then it works! Maybe this is worth mentioning in the docs!?

Example:
```
Text::::make('Name', 'name')
    ->fillUsing(function ($request, $model, $attribute, $requestAttribute) {
        $request->validate([
		$attribute => 'min:6',
	]);
        $model->{$attribute} = Str::title($request->input($attribute));
    }),
```
