### ISSUE TITLE
pointing nova URI path to '/' doesn't work

### ISSUE THREAD

**Issue by 0xZeus** [laravel/nova-issues#3093]
- Laravel Version: 8.17.0
- Nova Version: 3.16.0
- PHP Version: 7.4.12
- Database Driver & Version: MySQL
- Operating System and Version: Linux
- Browser type and version: NA
- Reproduction Repository: NA

### Description:
setting the URI path to site root '/' used to work until 3.16.0 released.

### Detailed steps to reproduce the issue on a fresh Nova installation:
changing 'path' => `'/nova',` to `'path' => '/',` in `config/nova.php`, laravel welcome page still show up ..
in earlier releases nova used to override laravel welcome page

**Comment by crynobone** [comment]
Just send a PR for this. Meanwhile you can solved this temporarily using the following:

### `config/nova.php`

Fallback to `env('APP_URL')` instead of `null`.

```php
    'domain' => env('NOVA_DOMAIN_NAME', env('APP_URL')),
```

### `routes/web.php`

Comment the default `/` route.

```php
// Route::get('/', function () {
//     return view('welcome');
// });
```

**Comment by cudret** [comment]
this fix dosent work on "xampp windows" (worked on linux server)

**Comment by medvinator** [comment]
Also, the fix does not work with a dynamic nova domain 🥺

**Comment by crynobone** [comment]
> Also, the fix does not work with a dynamic nova domain 

Can you provide how you setup dynamic nova domain on your app.

**Comment by medvinator** [comment]
> Can you provide how you setup dynamic nova domain on your app

In `config/nova.php`

```php
'domain' => null,
'url' => '/',
'path' => '/',
```

Waiting publish your PR https://github.com/laravel/nova/pull/1113 (it work)

**Comment by crynobone** [comment]
`v3.16.1` and `v3.16.2` released with the fixes.

with the releases you can revert all the temporary workaround mention above.

**Comment by groax** [comment]
> `v3.16.1` and `v3.16.2` released with the fixes.
> 
> with the releases you can revert all the temporary workaround mention above.

So it 'works' now? :)

**Comment by cudret** [comment]
updated..seems to work

**Comment by jbrooksuk** [comment]
It works :)

**Comment by BroJenuel** [comment]
I need help.. the path works fine. but when I go to these pages. nothing shows on my page and shows errors on my console. 

![image](https://user-images.githubusercontent.com/31676163/114978730-3d096c00-9ebc-11eb-8749-6ab814aafb8f.png)

**Comment by BroJenuel** [comment]
this error shows up, I really really need help.
![image](https://user-images.githubusercontent.com/31676163/114978968-a4bfb700-9ebc-11eb-9298-efd3f64faafd.png)
