### ISSUE TITLE
help-text not showing on several 3rd party packages

### ISSUE THREAD

**Issue by JonathanDoelan** [laravel/nova-issues#3095]
- Laravel Version: 8.16.1
- Nova Version: 3.15.0
- PHP Version: 7.4.2

### Description:

I’m working with several packages that provide custom fields and are not able to show the `->help('text')`.

(Example) list of packages:
- Whitecube\NovaFlexibleContent\Flexible
- Emilianotisato\NovaTinyMCE\NovaTinyMCE
- DmitryBubyakin\NovaMedialibraryField\Fields\Medialibrary

Is there a chance that this is a nova issue?

**Comment by crynobone** [comment]
@JonathanDoelan have you tried contacting the packages maintainers? They need to implements the support first.

**Comment by JonathanDoelan** [comment]
@crynobone They have open issues on their github pages. I was just wondering if something inside nova did change, because it does not look like coincidence to me anymore?

**Comment by crynobone** [comment]
`Field::jsonSerialize()` pass the `helpText` value from XHR request such as:

![image](https://user-images.githubusercontent.com/172966/100861118-580aaf00-34cc-11eb-9641-c1e1a1cb77b1.png)

Each field vue component then need to handle it manually. If they don't then it's not visible.
