### ISSUE TITLE
The better implementation for the `HasOne` detail view

### ISSUE THREAD

**Issue by zareismail** [laravel/nova-issues#3096]
Hey.
The `HasOne` field in the details view; shows a table with one row. but I think is better that display the related `detail-view` of the related resource.

Two different implementations are here. first [via table](https://pasteboard.co/JD74tdk.png) and second [via the view](https://pasteboard.co/JD75fxQ.png).

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
