### ISSUE TITLE
Resetting the list order does not return to the default order

### ISSUE THREAD

**Issue by JonathanDoelan** [laravel/nova-issues#3097]
- Laravel Version: 8.16.1
- Nova Version: 3.15.0
- PHP Version: 7.4.2

### Description:

In index view, when reordering the list, the list does not return to the default order. So if we click the column-sort-button until it resets ordering, the url still shows `?pages_order=title&pages_direction` instead of nothing.

This is how I implemented default ordering:
```
	public static function indexQuery(NovaRequest $request, $query)
	{
		$query->when(empty($request->get('orderBy')), function(Builder $q)
		{
			$q->getQuery()->orders = [];
			return $q->orderBy('updated_at', 'desc');
		});
	}
```

Maybe getting rid of `?pages_order=title&pages_direction` will solve the issue?

**Comment by crynobone** [comment]
The url still shows `?pages_order=title&pages_direction` instead of nothing.

This is the intended behavior at the moment, but I'm failing to see where this cause an error or bug. Can you elaborate further so I can reproduce the issue.

**Comment by JonathanDoelan** [comment]
@crynobone 

if you implement this …

```
	public static function indexQuery(NovaRequest $request, $query)
	{
		$query->when(empty($request->get('orderBy')), function(Builder $q)
		{
			$q->getQuery()->orders = [];
			return $q->orderBy('updated_at', 'desc');
		});
	}
```

… then for example you will get this entries:

id | title | updated_at
-|-|-
1 | title b | 2020-12-03
3 | title c | 2020-12-02
2 | title a | 2020-12-01

They are sorted by `updated_at`.

If you then click on the “title column button” you will get:

id | title ↑ | updated_at
-|-|-
2 | title a | 2020-12-01
1 | title b | 2020-12-03
3 | title c | 2020-12-02

**URL:** `?model_order=name&model_direction=asc`

If you click again:

id | title ↓ | updated_at
-|-|-
3 | title c | 2020-12-02
1 | title b | 2020-12-03
2 | title a | 2020-12-01

**URL:** `?model_order=name&model_direction=desc`

And then if you click again and “reset” you will get the following:

id | title | updated_at
-|-|-
1 | title b | 2020-12-03
2 | title a | 2020-12-01
3 | title c | 2020-12-02

**URL:** `?model_order=name&model_direction`

So it looks like it’s ordered by `id`, which is not intended.

**Comment by crynobone** [comment]
Thanks you for the reply, will use this to replicate the issue at my end and work on a fix (if possible).

**Comment by crynobone** [comment]
I believe this should be the best solution to handle the scenario.

```php
    /**
     * Build an "index" query for the given resource.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public static function indexQuery(NovaRequest $request, $query)
    {
        return $query->when(empty($request->get('orderByDirection')), function(Builder $query) {
            $query->getQuery()->orders = [];

            return $query->orderBy('updated_at', 'desc');
        });
    }
```

**Comment by JonathanDoelan** [comment]
@crynobone Thank you!
