### ISSUE TITLE
Replace the "Create and Add New" button with "Create and Continue Editing"

### ISSUE THREAD

**Issue by MB116** [laravel/nova-issues#3098]
Hello!
I need feature to replace the "Create and Add New" button with "Create and Continue Editing".
If is it possible now, please tell me how?

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
