### ISSUE TITLE
issue with snake case table relation Belongs to

### ISSUE THREAD

**Issue by mpoma** [laravel/nova-issues#31]
Table name: assets_types, 
model name: AssetType,
Ok for resource editing.
But when I try to used in a relations, BelongsTo::make('AssetType'), I have the error

![imagen](https://user-images.githubusercontent.com/7820360/44536318-8cc71380-a6d2-11e8-90f1-efe303c59bef.png)
I put the table name explicit in the model, protected $table = 'assets_types';,  and get the same error
Thanks guys!!!

**Comment by pdewit** [comment]
You should be able to use `BelongsTo::make('Asset Type')`

**Comment by MattMangoni** [comment]
Something with something like BelongsTo::make('AssetType', 'assettype', AssetType::class) :)

The second parameter is the name of the relationship, the third the nova resource's one.

**Comment by mpoma** [comment]
I dont find in the doc
 BelongsTo::make('AssetType', 'assettype', AssetType::class) :)

The second parameter is the name of the relationship, the third the nova resource's one.
