### ISSUE TITLE
ServeNova does not handle domains with ports anymore

### ISSUE THREAD

**Issue by davi5e** [laravel/nova-issues#3100]
- Laravel Version: 8.17
- Nova Version: 3.16.2 
- PHP Version: 7.4

### Description:

Since the last changes in `nova/src/Http/Middleware/ServeNova.php` the method `isNovaRequest` does not handle `config('nova.domain')` when a port value is present.

Example: `nova.some.domain:8080`

### Detailed steps to reproduce the issue on a fresh Nova installation:

Just deploy nova in a subdomain that needs a port to trigger `No hint path defined for [nova].`.

This is happening because the old way (below) used to work fine and now the presence of a port messes up the newer code.

```diff
diff --git a/nova/src/Http/Middleware/ServeNova.php b/nova/src/Http/Middleware/ServeNova.php
index 6859c35..905fbc1 100644
--- a/nova/src/Http/Middleware/ServeNova.php
+++ b/nova/src/Http/Middleware/ServeNova.php
@@ -37,10 +38,14 @@ class ServeNova
         $domain = config('nova.domain');
         $path = trim(Nova::path(), '/') ?: '/';
 
-        if ($domain !== config('app.url') && $path === '/') {
+        if (! is_null($domain) && $domain !== config('app.url') && $path === '/') {
+            if (Str::startsWith($domain, ['https://', 'http://'])) {
                 return $request->root() === $domain;
             }
 
+            return rtrim($request->getHttpHost().$request->getBaseUrl(), '/') === $domain;
+        }
+
         return $request->is($path) ||
                $request->is(trim($path.'/*', '/')) ||
                $request->is('nova-api/*') ||
```

**Comment by crynobone** [comment]
@davi5e this should be handled in `v3.16.3`, just released.

**Comment by davi5e** [comment]
Thank you, it's working!

Looking at the `v3.16.3` version, what would happen if `config('nova.domain')` **do not** have a port and `$request->getHttpHost()` **does**? I think this scenario used to work too...

**Comment by crynobone** [comment]
> I think this scenario used to work too (depending on config('app.url'))...

In previous iteration, when path set to `/`, regardless if you hitting Laravel Nova routes or any other part of the Laravel app. Nova assume you are serving Nova and load unnecessary cards and services that has potential to slow down your app. That the reason we added the logic on 3.16.0 and further improve it in 3 patch release.
