### ISSUE TITLE
Glued parameter for each ajax call

### ISSUE THREAD

**Issue by PrzemekTkaczyk** [laravel/nova-issues#3101]
- Laravel Version: 8.17.0
- Nova Version: 3.16.12
- PHP Version: 7.4
- Browser type and version: Chrome

### Description:
Hi Guys, 
I've been updated Laravel to 8 and Nova to 3.16, and now to every ajax call (get, post..) I see glued URL param like below:
Does anybody know what happened?

![image](https://user-images.githubusercontent.com/11367987/101143286-f86cea80-3616-11eb-9d8f-ef90a069afad.png)

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/101144670-a26a6800-3653-11eb-9fd7-e2be25200888.png)

I'm not seeing the issue on 3.16.2, few thing that we can check:

* Do you have any extension on Chrome that could cause this?
* Can it be replicated on other browser such as Firefox?
* Can you replicate the issue on a fresh Laravel Nova installation?

**Comment by crynobone** [comment]
Also, we just release `v3.16.3` which made some changes to `vendor.js`. Update and run `php artisan nova:publish`

**Comment by PrzemekTkaczyk** [comment]
OK, I will check the new version, 
For now - chrome & ff & safari have this issue
waiting for info from more devs in our company 

and try a "clean" version of nova...

**Comment by PrzemekTkaczyk** [comment]
OK, so:
- update doesn't help,
- on the fresh installation of Nova there is not issue like this...
- the links with added "URL" param were on local and also on production server..

If you have any tips where to search for the issue, it would be great :)

**Comment by crynobone** [comment]
@PrzemekTkaczyk not sure how to help on this since none of the URL seem to be related to what Laravel Nova generate or uses. Is there any new npm update that could cause the issue?

**Comment by PrzemekTkaczyk** [comment]
@crynobone 
someone added some interceptors for ajax calls - I didn't saw it earlier and it was at the same time when I updated Nova...
so the issue is to close (or delete)
Sorry for any unnecessary confusion...

**Comment by crynobone** [comment]
@PrzemekTkaczyk no problem
