### ISSUE TITLE
Login screen not using custom theme css file

### ISSUE THREAD

**Issue by mddickens** [laravel/nova-issues#3102]
I created a custom theme for my installation and it works great except the login screen isn't picking up the custom css file.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by mddickens** [comment]
Perhaps I'm just stupid but what part of this was a feature request? Isn't it a bug when you supposedly support custom themes but don't honor them on the login screen?

**Comment by crynobone** [comment]
> Perhaps I'm just stupid but what part of this was a feature request? Isn't it a bug when you supposedly support custom themes but don't honor them on the login screen?

![image](https://user-images.githubusercontent.com/172966/101299221-5a725d80-386c-11eb-8e53-8c58262f0d0c.png)

Can you use the bug report template when issuing a bug report including how to replicate the issue.

**Comment by crynobone** [comment]
This actually can be solved by adding the following:

```php

    /**
     * Register the Nova routes.
     *
     * @return void
     */
    protected function routes()
    {
        Nova::routes()
                ->withAuthenticationRoutes(['web', DispatchServingNovaEvent::class])
                ->withPasswordResetRoutes(['web', DispatchServingNovaEvent::class])
                ->register();
    }
```

**Comment by mddickens** [comment]
Thank you! That does work and now my custom theme is used across the app as it ought to be. This needs to be pulled into the package.

 

Mark
