### ISSUE TITLE
Page title not shown for Tools

### ISSUE THREAD

**Issue by PaoloCentomani** [laravel/nova-issues#3104]
- Laravel Version: 8.17.2
- Nova Version: 3.16.3
- PHP Version: 7.4.13
- Database Driver & Version: MySQL 8.0.22
- Operating System and Version: macOS 11.0.1
- Browser type and version: Safari 14.0.1

### Description:

<img width="1377" alt="Screen Shot 2020-12-06 at 11 56 45" src="https://user-images.githubusercontent.com/4149197/101278237-67367900-37ba-11eb-8621-a5b38f1375dc.png">

### Detailed steps to reproduce the issue on a fresh Nova installation:

- `php artisan nova:tool acme/price-tracker`
- Register the tool in `NovaServiceProvider`

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/101298719-51808c80-386a-11eb-9204-a5fee18747bd.png)

You can update the page title from `resources/js/components/Tool.vue`:

```js
<script>
export default {
  metaInfo() {
    return {
      title: 'PriceTracker',
    }
  },
  mounted() {
    //
  },
}
</script>
```

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
Marking this as a request but I did send a PR to add a default title code when running `php artisan nova:tool`
