### ISSUE TITLE
OptimistDigital\MultiselectField\Multiselect Field 

### ISSUE THREAD

**Issue by Wissamus** [laravel/nova-issues#3106]
Hello World, 
currently i use this package https://packagist.org/packages/optimistdigital/nova-multiselect-field to group a multiselct list but i don't know how to manage the pivot table.

Below my code : 

#### this function ollow us to filter the client rights : 
```
  public function clientRights(){

        $clients = DB::table('clients as cli')->select('cli.name as label', 'cli.first_name as lab', 'ent.name as group')
            ->leftJoin('companies as ent', function ($join) {
                $join->on('ent.id', '=', 'cli.company_id');
            })
            ->get();
        $return = [];
        foreach($clients as $client){
            $case = ["label" =>  $client->label.' '.$client->lab, "group" => $client->group];
            array_push($return, $case);
        }
        return $return;

    }

```

#### I use this Multiselect :
```

Multiselect::make('Users rights', 'clients')->options(function (){
                    return $this->clientRights();
                }
 )->groupSelect(),

```
 "culmun clients doesn't exist " so when we try to record our form we have an error telling us that this column does not exist in the table, which is normal. 

I want to do something like this { BelongsToManyField::make('Utilisateurs ayant droit', 'clients', 'App\Nova\Client') } but with the Multiselect. 

Any suggestion ?

SOS HELP

**Comment by crynobone** [comment]
Based on error shown this seems to be missing proper relationship on the eloquent model. You should start from there.

**Comment by Wissamus** [comment]
the clients relationship exist on my eloquent model, and {  BelongsToManyField::make('Utilisateurs ayant droit', 'clients', 'App\Nova\Client' } works but it doesn't group the list

**Comment by crynobone** [comment]
> the clients relationship exist on my eloquent model, and { BelongsToManyField::make('Utilisateurs ayant droit', 'clients', 'App\Nova\Client' } works but it doesn't group the list

I failing to see how this is Laravel Nova issue. Have you posted the issue on the package GitHub issues?

Or can you recreate the issue on fresh Laravel Nova so I can review this.

**Comment by Wissamus** [comment]
I created this issue on laravel nova-issue... 

Can u send me the url of the github plz so i can create the issue.

thank u

**Comment by crynobone** [comment]
https://github.com/optimistdigital/nova-multiselect-field

**Comment by Wissamus** [comment]
@crynobone done 

https://github.com/optimistdigital/nova-multiselect-field/issues/79

**Comment by crynobone** [comment]
Closing this as no further action for now.
