### ISSUE TITLE
Nova version once usage broken

### ISSUE THREAD

**Issue by ragingdave** [laravel/nova-issues#3109]
- Laravel Version: 8.17.2
- Nova Version: 3.16.3
- PHP Version: 7.4.3

### Description:
In a recent change to pull the Nova version from composer json, the once usage is now broken for spatie/once v1 users. This is because there's no object for v1 to attach the cached value on. Broken in PR https://github.com/laravel/nova/pull/1061. Can confirm that once v2 resolves the issue, but that's potentially alot of broken laravel apps due to https://github.com/spatie/once/issues/49

### Detailed steps to reproduce the issue on a fresh Nova installation:
Load nova when the app composer json specifies spatie/once ^1.0. See the breakage

**Comment by crynobone** [comment]
Sent PR to bump the minimum to `spatie/once` v2.

`2.0.0` was first released on January 2018. Should be a good step to do so now.

**Comment by ragingdave** [comment]
The waiting to upgrade isn't about wanting to or not. There is an issue ever since 2.0 release that prevents using once in models. It's been reported a number of times, and has never been fixed so those that need to use once in models, has had to stay on v1. Unless you want to fix spatie once as well to work in models, then I hope that PR doesn't get merged and I'll make the same comment there as well.
