### ISSUE TITLE
Nova asking none existing (null) models on belongs to relationship

### ISSUE THREAD

**Issue by CSenshi** [laravel/nova-issues#3111]
- Laravel Version: 8.16.0
- Nova Version: 3.15.0
- PHP Version: 7.4.4
- Database Driver & Version: Mysql
- Operating System and Version: Homestead.(virtualbox, 9.4.0)
- Browser type and version: Chrome.87.0.4280.66

### Description:
Nova asking for relationships on non existing models on `BelongsTo` relationship. Why? It might or might not be a bug but how can one work around this problem effectively?

### Detailed steps to reproduce the issue on a fresh Nova installation:
Imagine having class `Chat` which has `dealer_user_id` field which corrseponds to `DealerUser` class. `DealerUser` class has field `dealer_id` which corresponds to `Dealer` class. so it's like :

`Chat` ------BelongsTo------> `DealerUser` ------BelongsTo------> `Dealer`

So:

`Chat` ------BelongsTo------> `Dealer`

Therefore I created relationship `dealer` in `Chat` class using `dealerUser` relationship (see below).

```php
class Chat extends Model
{
    protected $fillable = ['dealer_user_id'];

    public function dealerUser()
    {
        return $this->belongsTo(DealerUser::class, 'dealer_user_id', 'id');
    }

    public function dealer()
    {
        return $this->dealerUser->dealer();
    }

}
```
Afterwards I added nova relationship as follows:

```php
class Chat extends Resource
{
    public function fields(Request $request)
        {
            return [
                ID::make(__('ID'), 'id')->sortable(),
                BelongsTo::make('Dealer', 'dealer', Dealer::class)->sortable(),
                BelongsTo::make('Dealer User', 'dealerUser', DealerUser::class)->sortable(),
            ];
        }
    }
}
```
Now the problem is that when I created Nova Chat resource and added `BelongsTo` relationship it bugged saying:

`"Call to a member function dealer() on null", exception`

After some debugging I found that Nova is asking for non existing model for `DealerUser` and queries something like this:

`select * from 'dealer_users' where 'dealer_users'.'id' is null`

and this queries something that is null!

### Solution:
I solved the problem as follows:
```php
    public function dealer()
    {
        if($this->dealerUser == null)
            return $this->dealerUser();
        return $this->dealerUser->dealer();
    }
```
I know that it helps but why is something like this happening? Is there a better way of handling this situation? I tried `HasOneThrought` relationship but it doesn't really work on this case, so I think it would be best if I implemented this using one relationship but which one or how?

**Comment by crynobone** [comment]
This seem to be a bad relationship design more than anything. Shouldn't you use `hasOneThrough`?
