### ISSUE TITLE
Actions BelongsTo field not working

### ISSUE THREAD

**Issue by RomkaLTU** [laravel/nova-issues#3112]
- Laravel Version: 8.17.2
- Nova Version: 3.16.3
- PHP Version: 7.4
- Database Driver & Version: Mysql 8

### Description:

I have this simple action:

```
/**
 * Perform the action on the given models.
 *
 * @param  \Laravel\Nova\Fields\ActionFields  $fields
 * @param  \Illuminate\Support\Collection  $models
 * @return mixed
 */
public function handle(ActionFields $fields, Collection $models)
{
    foreach ($models as $model) {
        $model->update([
            'user_id' => $fields->user
        ]);
    }
}

/**
 * Get the fields available on the action.
 *
 * @return array
 */
public function fields()
{
    return [
        BelongsTo::make('User', 'user', User::class),
    ];
}
```

At first, it seems fine, but when I select User from BelongsTo relation and try to save exception is throwing:

`Argument 1 passed to Laravel\Nova\Fields\BelongsTo::getRelationForeignKeyName() must be an instance of Illuminate\Database\Eloquent\Relations\Relation, instance of Illuminate\Support\Fluent given, called in /Users/rd/Sites/bns-crm/vendor/laravel/nova/src/Fields/BelongsTo.php on line 212
`

**Comment by RomkaLTU** [comment]
Maybe this is a limitation of action fields? As an alternative we can use this approach:

`Select::make(__('Vartotojas'), 'user_id')->options(\App\Models\User::all()->pluck('name', 'id')),`

**Comment by crynobone** [comment]
Action is dependent from a specific Resource and using `BelongsTo` or any other relationship is invalid.

You should use:

```php
Select::make(__('Vartotojas'), 'user_id')->options(\App\Models\User::all()->pluck('name', 'id')),
```

**Comment by blackfyre** [comment]
@RomkaLTU  @crynobone  Any ideas on how to do this with a `MorphTo` relation?
