### ISSUE TITLE
Minified Javascript file app.js is not called app.min.js

### ISSUE THREAD

**Issue by cweiske** [laravel/nova-issues#3113]
- Laravel Version: 8
- Nova Version: 3.14.0

### Description:
I use `ack` to search code in files and have excluded minified files from search (`*.min.js`, `*.min.css`).
Unfortunately nova ships `app.js` which is minified but not marked as such with its file name.

Please rename that file to `app.min.js`.

Dito for `app.css`; that should be `app.min.css`. `vendor.js` should be `vendor.min.js`

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
