### ISSUE TITLE
`Boolean::make('Fixed')->default(true)` is not checked by default

### ISSUE THREAD

**Issue by AlbinoDrought** [laravel/nova-issues#3114]
- Laravel Version: 8.13.0
- Nova Version: 3.13.0
- PHP Version: 7.4.13
- Database Driver & Version: Postgres
- Operating System and Version: 5.9.11-3-MANJARO
- Browser type and version: Firefox 83.0
- Reproduction Repository: https://gist.github.com/AlbinoDrought/e7052013846e15430d71fbce6d84241c

### Description:

`Boolean` exposes `Boolean::make('Fixed')->default($value)` as documented here: https://nova.laravel.com/docs/3.0/resources/fields.html#default-values

I have this field in my resource:

```php
Boolean::make('Fixed')->default(true),
```

I expect to see this when I open the resource creation page:

![image](https://user-images.githubusercontent.com/852873/101543006-7a7f4b00-3958-11eb-9335-da42d61a0132.png)

But I see this instead:

![image](https://user-images.githubusercontent.com/852873/101542994-73583d00-3958-11eb-8d2f-8d3f305521fb.png)

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Create a `bugs` table with `$table->boolean('fixed');`
2. Create a `Bug` model with `php artisan make:model Bug`
3. Create ` Bug` Nova resource with `php artisan nova:resource Bug`
4. Add a `Boolean::make('Fixed')->default(true)` field to it
5. Open Nova dashboard, create a new bug

The `Fixed` field is unchecked, even though `true` was specified as the default value.

**Comment by RomkaLTU** [comment]
`Boolean::make('Fixed')->withMeta(["value" => 1])`

**Comment by crynobone** [comment]
`default()` should accept `Closure` and not `boolean`.

```php
Boolean::make('Fixed')->default(function () { 
    return true; 
}),
```

**Comment by AlbinoDrought** [comment]
I encounter the same behaviour when using `Boolean::make('Fixed')->default(fn () => true),`

**Comment by crynobone** [comment]
Submitted a PR and it has been merged (should be available on next release).

With the PR you can either do:

```php
Boolean::make('Fixed')->default(true),
```

Or

```php
Boolean::make('Fixed')->default(function () { 
    return true; 
}),
```
