### ISSUE TITLE
Nova field: `required` is ignored

### ISSUE THREAD

**Issue by bernhardh** [laravel/nova-issues#3115]
- Laravel Version: 8.18.1
- Nova Version: 3.16.3
- PHP Version: 7.4.3
- Database Driver & Version: 10.5.8-MariaDB-1:10.5.8
- Operating System and Version: Ubuntu 20.04
- Browser type and version: Chrome 87.0.4280.88

### Description:

The `required()` method on fields is not working. The `*` is shown on the label, but I can save a resource, even if the field is empty. If I change `->required()` to `->rules('required')`, it works as expected (you get the error message).

### Detailed steps to reproduce the issue on a fresh Nova installation:

Create a model + resource with a string field `name` and mark the field as required:

```php
public function fields(Request $request)
{
    return [
        ID::make(__('ID'), 'id')->sortable(),
        Text::make('Name')->required(),
    ];
}
```

Now try to save it and you will see, that you can save it (or get at least an SQL error, if the field is not nullable).

If you change it to 

```php
public function fields(Request $request)
{
    return [
        ID::make(__('ID'), 'id')->sortable(),
        Text::make('Name')->rules('required'),
    ];
}
```

it works as expected.

**Comment by crynobone** [comment]
That's is expected, I discussed this exact issue with the team and here's what @davidhemphill said:

> To clear up the confusion around this, the `required` method is intended for situations where the developer has a complex validation requirement (e.g. `required_if:x:7y,z`). The user can pass in a Closure to determine if the required asterisk should be shown. If the user just has a simple `required` validation rule, they should just use the validation rule since that will add the asterisk as well.

**Comment by bernhardh** [comment]
Seriously? It's not a bug, its a feature? A method named `required` doesn't make the field required?

**Comment by monaye** [comment]
I totally understand Laravel's team intention and it makes perfect sense to me. The documentation seems enough and thanks for adding it so quickly.

**Comment by bernhardh** [comment]
I understand the intention and the behavior is just fine for me, but the naming of the method is just misleading.

**Comment by monaye** [comment]
@bernhardh yah.. you are right. 'showRequired', 'showAsRequired'?

**Comment by likeabas** [comment]
I am wondering, why was this issue not picked up?
While I have been using Nova in the past, I ran into the same issue again today, but forgot about this very specific rule. It takes a lot of time for developers to debug things like this every time.
