### ISSUE TITLE
Cannot run Github action tests. Emergency.

### ISSUE THREAD

**Issue by binaryk** [laravel/nova-issues#3116]
- Laravel Version: 8.0.0
- Nova Version: 3.16.0
- PHP Version: 7.4
- Database Driver & Version: mysql
- Operating System and Version: Ubuntu 18.04 (from github actions)

### Description:

The CI stoped working since 3 days ago (7 December) when trying to install nova. This is the script: 

```
      - name: Install Dependencies
        run: |
          composer config "http-basic.nova.laravel.com" "${{ secrets.NOVA_USERNAME }}" "${{ secrets.NOVA_PASSWORD }}"
          composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
```

The output: 

![image](https://user-images.githubusercontent.com/6833714/101769113-29558f80-3aef-11eb-8c03-af929fa9e5f1.png)

We had to buy another license to test it, and added it on the github settings -> secrets, but the issue still remain.

Other fact: it works with `psalm.yml`, which has the same way to install dependencies.

**Comment by binaryk** [comment]
Just tried to push configuration in another way, and got this:

![image](https://user-images.githubusercontent.com/6833714/101771881-4724f380-3af3-11eb-8871-3c1dd2c61dbc.png)

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/101772125-e9f66580-3b25-11eb-826c-e3ff6cf3288b.png)

From the first error, I can't determine whether composer install failed on `laravel/nova` or other dependencies, also check `aa8bc532` commit and it's not found on Laravel Nova repository: https://github.com/laravel/nova/commit/aa8bc532

As for the second options, you need to force `composer require "laravel/nova:^3.0" --prefer-dist` to avoid using git clone (which would cause another issue related to git clone permission under GitHub Action).

**Comment by binaryk** [comment]
Thanks @crynobone , it worked after:

- added as a first script: `composer clear-cache`  (before composer install itself)
- changed `~3.0` to `^3.0`


Thank you for your help.

**Comment by crynobone** [comment]
You can also use `composer install --no-cache`, which would avoid the issue as well AFAIK
