### ISSUE TITLE
Cannot perform resource action that relies on content in the resource

### ISSUE THREAD

**Issue by powellblyth** [laravel/nova-issues#3117]
- Laravel Version: 8.18.1
- Nova Version: 3.16.3
- PHP Version: 7.4.12
- Database Driver & Version: Mysql / 
- Operating System and Version: Docker Ubuntu
- Browser type and version: Chrome / latest
- Reproduction Repository: https://github.com/###/###

### Description:
If an action is only allowed to be shown for a resource that has a specific data property, that action is impossible to run, and sends abort(403).

#### Use case
a use case for this is I want to show a button that deactivates a blog post. You can only deactivate a blog post if the status is active. I use the cansee callback to show only if the status is active.

What happens is the framework checks to see if the action exists, but looks for a list of actions available on a blank instance of the resource, which will not be active/,

#### What should happen:
when the action button is clicked, the action should be validated against the extant resource.

#### Workaround
in the beginning of the `canSee` method in the actions method of the resource allow the action if the object ID is null
```
                ->canSee(function () {
                    if( is_null($this->resource->id)){
                         return true;
                     }
                })
```
### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Create a resource
1. Create new action `DummyAction` using ` php artisan nova:action DummyAction`

(trimmed for brevity)

```
<?php

namespace App\Nova\Actions;

use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Log;
use Laravel\Nova\Actions\Action;
use Laravel\Nova\Fields\ActionFields;

class DummyAction extends Action
{
    public $showOnTableRow = true;

    public function handle(ActionFields $fields, Collection $models)
    {
        Log::debug('got here');
    }
}

```
1. Add the action to your resource
```
  public function actions(Request $request)
    {
        return [
            DummyAction::make()
                ->canSee(function () {
                    return !is_null($this->resource->id);
                })
            ];
}
```
Click on the "Dummy Action" button and you are presented with a 403 page.

**Comment by crynobone** [comment]
You should be able to do the following

```php
use Laravel\Nova\Http\Requests\ActionRequest;

// ...

DummyAction::make()->canSee(function ($request) {
    return $request instanceof ActionRequest || !is_null($this->resource->id);
}),
```

> Unfortunately we're stuck with `$request instanceof ActionRequest` for the current series as the current behaviour that we need to respect is that "Action can only be run if it can be seen". Changing that would potentially causing a huge breaking change to some customers

**Comment by powellblyth** [comment]
Hi, thanks for this. I've done as you suggested, it's a better solution, thank you for your help.
