### ISSUE TITLE
Custom deletion confirmation message

### ISSUE THREAD

**Issue by sailingdeveloper** [laravel/nova-issues#3118]
Currently, when deleting a resource, it shows a generic "Delete Resource" title and "Are you sure you want to delete the selected resources?" body.

Now, while I can update the translations to change this text everywhere, I want to do it on a per-resource basis. Being able to shortly explain the _consequences_ of deleting a certain resource is a feature I'd really like to see in Nova.

**Comment by sailingdeveloper** [comment]
By the way, if at all possible, i'd be completely willing to write it in Nova myself. 🙂

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
