### ISSUE TITLE
onlyOnTableRow / showOnTableRow doesn't work with lenses only

### ISSUE THREAD

**Issue by MohammadAbusaleh** [laravel/nova-issues#3120]
- Laravel Version: 7.30.0
- Nova Version: 3.16.3
- PHP Version: 7.4.3
- Operating System and Version: Ubuntu 20.04
- Browser type and version: Chrome  87.0.4280.88

### Description:

Action doesn't work (gif below) if the action is only on the lens and not used in the main Nova/Resource.
Action works fine from the lens if it's defined in the Nova Resource.

Console returns 404 and the URL of the Nova Resource.

![ezgif-3-438b5b174d7b](https://user-images.githubusercontent.com/12821490/101922821-06f36d00-3be8-11eb-9a7c-f0377cc4a4f8.gif)

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Create a lens.
- Create an action.
- Define the action and use onlyOnTableRow (or) showOnTableRow.
- Click Run Action and it won't work.

**Comment by crynobone** [comment]
![CleanShot 2020-12-14 at 09 25 20](https://user-images.githubusercontent.com/172966/102030821-1b558680-3def-11eb-98b6-8d69d6751bc2.gif)


Unable to reproduce the issue, you can review the code https://github.com/nova-issues/issue-3120/commit/0393a7437ee31f5af625426cf7b863ed50a9d8fe

**Comment by crynobone** [comment]
I think this could be related to #2947

As far as we know, any nova packages that override `ResourceTableRow.vue` could cause this issue. Please contact the package maintainer to update the file to support latest Laravel Nova.

The one we know so far:

* `optimistdigital/nova-sortable`
* `flagstudio/nova-actions-left`
