### ISSUE TITLE
[Feature Request] how to make filters persistent

### ISSUE THREAD

**Issue by vesper8** [laravel/nova-issues#3123]
Currently I have a scenario where my client wants to add restaurants and restaurant menu items. There are thousands of menu items so to make it easier I've added a restaurant filter.

So my client sets the restaurant filter to only display menu items from that restaurant, then they can click a button to add a new menu item, they add the new item and then it brings them back to the menu items list but the restaurant filter does not persist. So they have to do several clicks once again to get back into the filtered list and rinse/repeat.

The restaurant filter should persist, or there should be an option to have it persist somehow.

**Comment by vesper8** [comment]
closing issue before it is auto-closed, but would appreciate any ideas or answers : )

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
> I would guess you need to interact directly with `resources/js/store/resource.js` to programmatically interacts with current filters.
