### ISSUE TITLE
Allow for more inline relationships while creating/updating.

### ISSUE THREAD

**Issue by stephan-v** [laravel/nova-issues#3124]
I think this package loses a lot of value due to not having more inline relationships while creating/updating. So far there are inline relationships but there are only 2 of them.

For example having something like this:

`MorphOne::make('Address'),`

It should be easy to add an address model when I am creating/editing the resource but this is currently not possible. 
Currently my flow has to be for a user to first create an address resource and then attach it later while creating the resource which needs to address. In a real life scenario this is kind of absurd when we are talking about usability.

I appreciate the simplicity of the package so far, but not being able to do something like this is a reason to almost stop using it. Too be honest I also expect a little bit more of this package on dealing with relationships since this is paid software.

**Comment by crynobone** [comment]
Please refer to https://nova.laravel.com/docs/3.0/resources/relationships.html#creating-inline-relations

![CleanShot 2020-12-14 at 18 04 05](https://user-images.githubusercontent.com/172966/102068179-1c120b00-3e37-11eb-8036-1d490b61fb07.gif)

**Comment by stephan-v** [comment]
Like I said it does not work with a `MorphOne`.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by stephan-v** [comment]
@davidhemphill Not to be a downer here but I don't think closing requests is a good solution here because they will get drowned with issues that are actually closed. Can't there be another repository like what Laravel has with `laravel/ideas`?

**Comment by stephan-v** [comment]
Any update on this?

**Comment by crynobone** [comment]
No plan yet, and in theory it's an extremely large work for the current iteration.
