### ISSUE TITLE
Allow for prepopulated searchable relationships.

### ISSUE THREAD

**Issue by stephan-v** [laravel/nova-issues#3125]
I thought it would be a given that there was also a searchable relationship which has pre-populated fields.
Currently when you add `->searchable()` to a relationship it adds the searchable form but it removes all populated fields.

Pretty much what this community packages does but integrated in Laravel Nova for official support.

https://novapackages.com/packages/alexbowers/nova-prepopulate-searchable

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
