### ISSUE TITLE
Slow loading time on every single page

### ISSUE THREAD

**Issue by lukaisailovic** [laravel/nova-issues#3127]
- Laravel Version: 8.18.1
- Nova Version: 3.16.3
- PHP Version: 7.4
- Database Driver & Version: MySql 5.7
- Operating System and Version: Windows 10
- Browser type and version: Chrome

### Description:

I just started using Nova, and first thing I noticed is how slow everything is. I added just a few models and it literally takes a few seconds to render the whole page. Also, the user page is loading a few relations, and it takes about 5s to load whole page.
I googled this issue, and it seems like other people had this as well. Saw that its a feature to prevent some sort of flicker or something, but honestly I wouldn't mind the flicker if it would load in 100-200ms, as now it just feels like its unusable.

If its not clear, I'm talking about the '...' loading on cards when displaying any kind of content, not the page loader below navbar.

Is there a configuration to disable this, or somewhere in source where its located so I can change it so some normal value?

### Detailed steps to reproduce the issue on a fresh Nova installation:

Just add a few models, should be pretty apparent.

**Comment by crynobone** [comment]
This is a hard issue to tackle since it highly depends on many factors which hard for everyone to replicate easily, but there some suggestion:

1. You can look at [Eager Loading](https://nova.laravel.com/docs/3.0/resources/#eager-loading) for Resources.
2. Use [Debugbar](https://github.com/barryvdh/laravel-debugbar) to check queries and model hydration. Latest Telescope also have support for this as well.
3. Look at database indexing. This talk cover the subject in-depth https://www.youtube.com/watch?v=HubezKbFL7E

----

Aside from that when we load a resource page there a few step Nova needs to do until initial loading marked as completed.

1. Parse data from query string
2. Get all filters info for the resource
3. Get the resources
4. Get current resources count
5. Get all the lens info for the resource
6. Get all the actions info for the resource

**Comment by lukaisailovic** [comment]
It seems to me like an issue on frontend. I started with brand new app, and have 10 users in db so indexes aren't really relevant. Still it takes 5 secs to complete loading of the page.

By checking some of the code, it looks like the frontend works like this:
Load cards
Wait
Populate cards with user data
Wait
Load card for relation
Wait
Populate card for relation

I'm not sure if that's an expected behaviour or something is wrong, but it seems like there is a lot of wait time (Timeouts) 

I read about eager loading, but if I do it like that, it will create bottlenecks on other pages. Is there a way to eager load relations only on user resource page, but not on other pages?

**Comment by crynobone** [comment]
```
By checking some of the code, it looks like the frontend works like this:
Load cards
Wait
Populate cards with user data
Wait
Load card for relation
Wait
Populate card for relation
```

Which card is populating user data, is it metric, or resource? 

Have you try the suggestion above the look at what's is actually slow? There's too many things that I have to assume happening right now. The suggestion would help us to understand where the bottleneck in the application, I assuming it's probably related to database structure, if not then probably look into server hardware.

**Comment by lukaisailovic** [comment]
Resource. I'll add debugbar now, but my point is that I don't think it has anything to do with the app. Its a brand new app with 3 models, 50 seeded rows in db and Its taking 5 seconds to load everything on the page. I'm running app locally (tried both development and production env) on i9 so I don't think its a hardware bottleneck, but I can't even begin to think what will happen when I deploy it to 2 core vps.

**Comment by crynobone** [comment]
> Resource. I'll add debugbar now, but my point is that I don't think it has anything to do with the app. Its a brand new app with 3 models, 50 seeded rows in db and Its taking 5 seconds to load everything on the page. I'm running app locally (tried both development and production env) on i9 so I don't think its a hardware bottleneck, but I can't even begin to think what will happen when I deploy it to 2 core vps.

![image](https://user-images.githubusercontent.com/172966/102344722-4a2e5100-3fd7-11eb-91e1-6feddb6af4d8.png)

Local network accessing via Valet on i7.

![image](https://user-images.githubusercontent.com/172966/102344765-59150380-3fd7-11eb-87f5-738e66760575.png)

Ngork using Expose (I would expect it to be much slower than average VPS)

![image](https://user-images.githubusercontent.com/172966/102344942-95e0fa80-3fd7-11eb-8aa3-89991c1442de.png)

Data seeded with 30,000 rows

![image](https://user-images.githubusercontent.com/172966/102344979-a42f1680-3fd7-11eb-8116-9fa258a06cc6.png)

**Comment by ahaneef29** [comment]
I'm also facing an issue, sometime dashboard or resource with 100 records got stuck. When I check the network tab it shows a pending request. Before I was hosting with low config server like 512 MB Ram, Later I upgraded to 1 GB server.  Still I couldn't find an issue, this issue from nova or anything I need to change in PHP ini. ?

**Comment by crynobone** [comment]
> When I check the network tab it shows a pending request. 

Pending request normally relates to available max connections to the web server. I probably start looking at nginx or apache web server configuration

**Comment by lukaisailovic** [comment]
Just installed debugbar, looks like queries run as expected and finish in ms, but the whole requests to display users took just over 2s which maybe indicates that its a networking issue?
![ss](https://i.imgur.com/AvDntQF.png)

I didn't mention I'm running the app trough docker, but the normal app isn't behaving abnormal so I don't think that would be an issue.

**Comment by Benoit1980** [comment]
I had a similar problem with Laravel, and realised it was from Xdebug, everything slows down when Xdebug is on. Make sure Xdebug is not active on your server/browser/IDE.

**Comment by crynobone** [comment]
![CleanShot 2020-12-17 at 16 43 05](https://user-images.githubusercontent.com/172966/102473900-f4b77a00-4092-11eb-8402-efda7f4fd15f.png)

Retested a Laravel Nova setup with 30,000 records on Sail (docker) and Takeout MySQL (docker on external network) and still can get ~1sec response.

**Comment by lukaisailovic** [comment]
Upon further testing I've found the problem. Slow loading is due to docker windows issues, nothing to do with nova. Unfortunately, its greatly exaggerated and very noticeable when using nova because of the amount of requests it makes and most of them waiting for the previous one to finish.

**Comment by crynobone** [comment]
Thank you for the update @lukaisailovic

**Comment by djvickx** [comment]
> I had a similar problem with Laravel, and realised it was from Xdebug, everything slows down when Xdebug is on. Make sure Xdebug is not active on your server/browser/IDE.

Spent hours trying to figure out why Nova is responding slow on my local docker setup. Thank you so much @Benoit1980 you saved my days. That xdebug was the only reason for slowness of app on local.

**Comment by internetbug256** [comment]
Hi. I 've also started to notice the same. I've been working for a couple of years using Linux server, and Laravel and Nova were a flash. However, I started to notice strange delays for one same page, that loads instantly one time, and several secs next one, when I know it should take exactly the same. And yes, I am using Docker.

**Comment by noriods** [comment]
Just in case this helps someone else...

I was facing the same issue but there was nothing in the Network tab of DevTools and none of the other suggestions helped.

Turns out that I had a relationship (on a few resources) that was being loaded into a `<select>`

This caused huge delays in rendering the page.

Adding `->searchable()` to those field definitions helped immensely and now Nova is SUPER fast again.

This is already mentioned in the docs but is easy to miss if you created the relationship field (and it was working fine) and then added a bunch of relation rows later, causing the "sudden" slow down.

Hope this helps!

**Comment by murcoder** [comment]
For me, it was also extremely slow until I **deactivated the Laravel Debug Bar** and debugging, especially with these environment variables:
```
APP_DEBUG=false
DEBUGBAR_ENABLED=false
```

**Comment by zynxoso** [comment]
> This is a hard issue to tackle since it highly depends on many factors which hard for everyone to replicate easily, but there some suggestion:
> 
> 1. You can look at [Eager Loading](https://nova.laravel.com/docs/3.0/resources/#eager-loading) for Resources.
> 2. Use [Debugbar](https://github.com/barryvdh/laravel-debugbar) to check queries and model hydration. Latest Telescope also have support for this as well.
> 3. Look at database indexing. This talk cover the subject in-depth https://www.youtube.com/watch?v=HubezKbFL7E
> 
> ----
> 
> Aside from that when we load a resource page there a few step Nova needs to do until initial loading marked as completed.
> 
> 1. Parse data from query string
> 2. Get all filters info for the resource
> 3. Get the resources
> 4. Get current resources count
> 5. Get all the lens info for the resource
> 6. Get all the actions info for the resource
