### ISSUE TITLE
Postgres Grouping error (MorphedByMany): Column "taggables.tag_id" must appear in the GROUP BY clause or be used in an aggregate function

### ISSUE THREAD

**Issue by jan-demsar** [laravel/nova-issues#3128]
- Laravel Version: 8.18
- Nova Version: 3.17
- PHP Version: 8.0
- Database Driver & Version: Postgres 13.1
- Operating System and Version: Ubuntu:20.04 (Laravel Sail)
- Browser type and version: -
- Reproduction Repository: -

### Description:
There is a problem with MorphedByMany relation when using Postgres (most likely MySql when using `strict=true` as well. 

The problem occurs because query is being grouped by primary key, but since simplePaginate later selects pivot table columns, this does not work, since those columns should be added to `group by` statement as well.

### Detailed steps to reproduce the issue on a fresh Nova installation:

I have a basic many to many polymorphic relationship: `post`, `tag`, `taggables` (tag_id, taggable_type, taggable_id).

On Post Nova model I have `MorphToMany::make('Tags')` and it works great.

On Tag Nova model I have `MorphToMany::make('Posts')` which is causing problems.

The following exception is being thrown (url: http://larvel.test/nova-api/posts?search=&filters=W10%3D&orderBy=&perPage=25&trashed=&page=1&viaResource=tags&viaResourceId=1&viaRelationship=posts&relationshipType=morphToMany) : 

``` 
Illuminate\Database\QueryException
SQLSTATE[42803]: Grouping error: 7 ERROR: column "taggables.tag_id" must appear in the GROUP BY clause or be used in an aggregate function LINE 1: ...domain.*, count(url.id) as "relUrls", "domain".*, "taggables... ^ (SQL: select domain.*, count(url.id) as "relUrls", "domain".*, "taggables"."tag_id" as "pivot_tag_id", "taggables"."taggable_id" as "pivot_taggable_id", "taggables"."taggable_type" as "pivot_taggable_type" from "domain" inner join "taggables" on "domain"."id" = "taggables"."taggable_id" left join "url" on "domain"."id" = "url"."domain_id" where "taggables"."tag_id" = 1 and "taggables"."taggable_type" = App\Models\Domain group by "domain"."id" order by "domain"."id" desc limit 26 offset 0)
```

The actual query:

```
select post.*,
       count(url.id)               as "relUrls",
       "post".*,
       "taggables"."tag_id"        as "pivot_tag_id",
       "taggables"."taggable_id"   as "pivot_taggable_id",
       "taggables"."taggable_type" as "pivot_taggable_type"
from "post"
         inner join "taggables" on "post"."id" = "taggables"."taggable_id"
         left join "url" on "post"."id" = "url"."post_id"
where "taggables"."tag_id" = 1
  and "taggables"."taggable_type" = 'App\Models\post'
group by "post"."id", taggables.tag_id, taggables.taggable_id, taggables.taggable_type
order by "post"."id" desc
limit 26 offset 0;
```

I noticed, that under the hood, simplePaginate method is being used to display the results.

I tried calling Post->domains()->simplePaginate(10) manually and that works well (it does not group by `post.id`).

Then I realised that Laravel Nova's ResourceIndexController already receives a query that is being grouped by `post.id`, but without pivot table selects (which are later added using simplePaginate()). 

So there are 2 solutions: 
1) Either remove that group by statement
2) Add pivot columns to the group by statement as well

But unfortunately I was not able to track down where the group statement is added. 😅

**Comment by crynobone** [comment]
@jan-demsar Would it be possible to create a reproducing code for this issue?

**Comment by jan-demsar** [comment]
I am closing the issue. I  realised the problem was `groupBy` inside an indexQuery of a related model (Post) 🤦‍♂️

**Comment by jan-demsar** [comment]
I am closing the issue. I realised the problem was groupBy inside an indexQuery of a related model (Post) 🤦‍♂️
