### ISSUE TITLE
Feature Request: Table row actions - allow to hide button on specific resource

### ISSUE THREAD

**Issue by bernhardh** [laravel/nova-issues#3129]
I have a `Article` resource and I wanna add a button to each row of this resource, to open this article not in nova, but on my frontend. For this, there is a `getUrl` method in my model, which returns the url of the model as a string, but only if it meet certain conditions (for example the article has a `published_at` date in the past). If not, it returns `null`.

For this, I have created an `Action`:

```php
class PreviewUrlAction extends Action {
    public static function make(...$arguments) {
        return parent::make($arguments)
            ->withoutConfirmation()
            ->onlyOnTableRow();
    }
    
    public function handle(ActionFields $fields, Collection $models) {
        if($url = $models->first()->getUrl()) {
            return static::openInNewTab($url);
        }

        return static::danger('No valid url');
    }
}
```

and it works, but the only problem with it is, that you can see this button on each row, even if there is now url. Thats why I added the `static::danger('No valid url')` "fallback".

The feature I would need is to conditionally hide the button for the `onlyOnTableRow`. Something like:

```php
public function showTableRowButton(Model $models) {
    // true or false
}
```

**Comment by crynobone** [comment]
You should be able to use `canSee()` for this usage.

```php
PreviewUrlAction::make()->canSee(function () {
    return $request instanceof \Laravel\Nova\Http\Requests\ActionRequest 
        || ! is_null($this->resource->getUrl());
}),
```
