### ISSUE TITLE
Date field not displayed on forms

### ISSUE THREAD

**Issue by bencounsell** [laravel/nova-issues#313]
Date fields are not displayed on forms. They are displayed on the index listing and details page.

I have the following setup:

Model: App\Version.php
```
protected $dates = ['release_date'];
```

Database Field:
![cleanshot 2018-08-29 at 13 46 53 2x](https://user-images.githubusercontent.com/418008/44785900-c5636300-ab92-11e8-9ff6-a7a724fc1779.png)

Nova Resource: App\Nova\Version.php
```
use Laravel\Nova\Fields\Date;

...

Date::make('Release Date', 'release_date')->format('Y-m-d')->onlyOnForms(),
```

If I change to using a DateTime field, then the date picker is displayed on the forms — however, I don't want a time picker for this `DATE` field.

Seems like a bug, is anyone else seeing this?

**Comment by telkins** [comment]
What version of Nova are you using?  There was a similar issue early on that has since been resolved.

See here under 1.0.4: https://nova.laravel.com/releases

If it's not that, then it may be something new or related.  And, no, I'm not seeing that and I'm on 1.0.7.

**Comment by bencounsell** [comment]
My bad! Upgrading fixes the issue.
