### ISSUE TITLE
SlugField TypeError when creating a resource

### ISSUE THREAD

**Issue by sileence** [laravel/nova-issues#3130]
- Laravel Version: 8.19.0
- Nova Version: 3.16.3
- PHP Version: 7.4.9
- Database Driver & Version: not database related
- Operating System and Version: macOs Catalina
- Browser type and version: Safari, Chrome, Firefox

When trying to create a resource that has a slug field I get a "TypeError".

I tried recompiling the assets and the error persists, as @brensondevalfa indicated here: https://github.com/laravel/nova-issues/issues/2845 it works only if I add `->readonly(true)` to the slug field. I imagine this is also related to: https://github.com/laravel/nova-issues/issues/2855 

I'm reopening the issue since I've tried updating Nova and recompiling the assets (even reinstalling everything and clearing all the browser cache) but I still see the error.

```
[Vue warn]: Error in render: "TypeError: undefined is not an object (evaluating '_vm.extraAttributes.type')"

found in

---> <FormSlugField> at resources/js/components/Form/SlugField.vue
       <Card> at resources/js/components/Card.vue
         <FormPanel> at resources/js/components/Form/Panel.vue
           <LoadingView> at resources/js/components/LoadingView.vue
             <CreateForm> at resources/js/components/CreateForm.vue
               <Create> at resources/js/views/Create.vue
                 <Root>
```

**Comment by crynobone** [comment]
Unable to reproduce the issue, see https://github.com/nova-issues/issue-3130/commit/b59f0f3e1634580fed6b668d43d53479ba9eea0c

![CleanShot 2020-12-17 at 09 01 42](https://user-images.githubusercontent.com/172966/102424775-dc217280-4046-11eb-96b7-bf97ea90da43.gif)

**Comment by crynobone** [comment]
Can you share `composer show -D` for the project or is there any nova packages that could have override `SlugField.vue` component?
