### ISSUE TITLE
Filter is broken

### ISSUE THREAD

**Issue by groax** [laravel/nova-issues#3131]
- Laravel Version: 7.0
- Nova Version: 3.17.0
- PHP Version: 7.4.5

### Description:
The new Nova update makes the filter not filter anymore. It did work fine in version 3.16.3

### Detailed steps to reproduce the issue on a fresh Nova installation:
Create a Filter and add a default value

**Comment by crynobone** [comment]
Have you publish the assets using `php artisan nova:publish` and verify everything is working?

v3.17.0 does introduces a changes to filters with reduce the string length to make it supported on resources with many filters, but it should still work with filter + default value.

Tested the code with 3.17.0 and everything still working.

![CleanShot 2020-12-17 at 09 01 42](https://user-images.githubusercontent.com/172966/102473575-925e7980-4092-11eb-8a89-f51b9945e5c0.gif)

------ 

Will need a full reproducing code to verify the issue.

**Comment by groax** [comment]
php artisan nova:publish did the trick! Thnx
