### ISSUE TITLE
Lens actions issue

### ISSUE THREAD

**Issue by kreexzoi** [laravel/nova-issues#3132]
- Laravel Version: 7.29.3
- Nova Version: 3.17.0
- PHP Version: 7.2
- Database Driver & Version: mysql
- Operating System and Version: Arch Linux
- Browser type and version: Firefox 84

### Description:
Actions remain from the previous lens page.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Create 2 lenses for one resource with different actions.

**Comment by crynobone** [comment]
@kreexzoi do you happen to navigate between the Lens from custom navigation link on the sidebar?

**Comment by kreexzoi** [comment]
> 
> 
> @kreexzoi do you happen to navigate between the Lens from custom navigation link on the sidebar?

yep. But url for lens is the same as from dropdown panel.

**Comment by kreexzoi** [comment]
@crynobone Can we directly fetch filters/actions with `to.param.lens`? Something like
```vue
this.initializeFilters(to.params.lens)
this.getActions(to.params.lens)
```

If we call `this.getActions()` (or fetch filters) and navigate between lens by vue router with custom navigation then actions fetch to previous lens
