### ISSUE TITLE
Exceptions are not reported to Sentry

### ISSUE THREAD

**Issue by cweiske** [laravel/nova-issues#3133]
- Laravel Version: v8.19.0
- Nova Version: 3.14.0
- PHP Version: 7.3.24

### Description:
My laravel application has its own exception handler that reports exceptions to a private Sentry instance. Today I encountered an exception inside Nova on the production system, but that was not reported to sentry.

It turns out that Nova overrides the exception handler (#2034) and thus nova-related exceptions are not logged to Sentry.

This is not documented anywhere. Nobody knows that this problem exists until one sees this problem on a production system.

We use sentry so that we get automatically notified of errors in our code, and not need to wait for customers to report them.
Nova's implementation breaks this.

Please either fix this or document it in the documentation, not hidden inside a closed issue.

**Comment by garyross** [comment]
In the `Providers/NovaServiceProvider.php`  add the following:

```
protected function registerExceptionHandler(): void
{
     $this->app->bind(NovaExceptionHandler::class, Handler::class);
}
```

**Comment by crynobone** [comment]
This has been updated on the documentation <https://nova.laravel.com/docs/3.0/installation.html#error-reporting>, and additional PR to improve the usage on Laravel 8 has been added to laravel/nova#1138
