### ISSUE TITLE
redirectAfterUpdate() does not take the user to the top of the page when redirecting from one /edit page to another

### ISSUE THREAD

**Issue by keironwaites** [laravel/nova-issues#3135]
- Laravel Version: 7.30.0
- Nova Version: 3.17.0
- PHP Version: 7.4.13
- Database Driver & Version: mySQL 5.7.28
- Operating System and Version: MacOS Catalina 10.15.7
- Browser type and version: Chrome 87.0.4280.88
- Reproduction Repository: n/a

### Description:

This is an oversight of the recently fixed #3049

When redirecting from one /edit page to another /edit page, the page UI is now drawn correctly. However, the user is still at the bottom of the page.

Problems with the current situation:

1. This is not the standard behaviour. If you save a record without redirectAfterUpdate() defined you are taken to the top of a resource list page.
2. The user could become confused - either thinking the page has not saved correctly, or by thinking they are still on the previous record.

Please see an example video below:

![Redirect - does not take you to the top of the screen](https://user-images.githubusercontent.com/23054272/102757893-e0f96580-4369-11eb-9e5e-356a6552e2a9.gif)

### Detailed steps to reproduce the issue on a fresh Nova installation:

Create a resource with many fields.

Add a redirect to another record within the same resource, e.g.:

```
    /**
     * Return the location to redirect the user after update.
     *
     * @param \Laravel\Nova\Http\Requests\NovaRequest $request
     * @param \App\Nova\Resource $resource
     * @return string
     */
    public static function redirectAfterUpdate(NovaRequest $request, $resource)
    {
        return '/resources/users/1229921';
    }
```

Observe that the destination page is in the same position as the previous page (the bottom of the page where the Update buttons are).

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
I'm marking this as `request` because the behavior doesn't change when you use the default redirection vs custom direction. In both cases this does remain the same. However will still investigate if we can improve the behavior.
