### ISSUE TITLE
Laravel Nova Production Page Expired

### ISSUE THREAD

**Issue by Peterragheb** [laravel/nova-issues#3138]
- Laravel Version: 8.14.0
- Nova Version: 3.15.0
- PHP Version: 7.4

### Description:

My App is working fine locally and on staging server but I'm getting Page Expired on the production server. And sometimes I get too many redirects.
At first I thought the problem was that I was using redis as my session_driver I changed it to be file to match my staging server config but It didn't work.
The only difference between the production server and the staging server is that
I'm using a load balancer and I have a root domain and an alias domain.

**Comment by crynobone** [comment]
> I'm using a load balancer and I have a root domain and an alias domain.

You should avoid using `file` session driver if you're using a load balancer. 

Other than that I don't have enough information to suggest anything more and this isn't really a specific Laravel Nova issue but instead server configuration setup for Laravel.

You should try one of the discussion channels:
* https://laracasts.com/discuss/channels/servers
* https://laravel.io/forum
* [#server on Discord](https://discord.com/invite/KxwQuKb)
