### ISSUE TITLE
Unable to get filters to work. Apply method not called on filter class.

### ISSUE THREAD

**Issue by navidnadali** [laravel/nova-issues#3139]
- Laravel Version: 8.19
- Nova Version: 3.17
- PHP Version: 7.4
- Database Driver & Version: MySQL 5.7
- Operating System and Version: Docker Alpine Image
- Browser type and version: N/A
- Reproduction Repository: N/A

### Description:

Hi, 

I'm unable to get Filtering to work on any of our Nova resources, The option displays fine but once the filter is selected (although the state is saved and loaded again on reload), none of the resources are being filtered. 

I initially assumed this would be an issue with the code in apply()on the filter class not returning a correct SELECT but debugging this, at no point this code is being called even when the filter is selected (but filter must be registered correctly for options to show?).

Nova resource class: https://gist.github.com/navidnadali/272f970b2addea991a658cb57f427231
Nova filter class: https://gist.github.com/navidnadali/876bd805bca14a00d4cffabfd4f87c3b
Laravel model class: https://gist.github.com/navidnadali/fea79ce403e3da996b5adebe08201a1e

![image](https://user-images.githubusercontent.com/2290350/102838929-4b0c1c00-43f7-11eb-8f37-3f3c59f42f49.png)

Any help appreciated 

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Replicate Model / Resource and Filter as per gists provided above. 
2. Model migration below simplified with what is needed to test (status column)

```        
Schema::create('websites', function (Blueprint $table) {

            $table->id();

            $table->string('name');
            $table->string('url');
            $table->string('status');

            $table->timestamps();

});
```

3. Access nova resource page, create new resource with status => active
4. Access nova resource index page, filter by status and inactive, observe that all records including active show.

**Comment by crynobone** [comment]
Can you share the output of `composer show -D` for the project.

**Comment by navidnadali** [comment]
I'm scared you are going to judge me.. 

```
root@709969ea0b54:/var/www# composer show -D
benjacho/belongs-to-many-field     1.8              belongsToMany nova representation in field.
bensampo/laravel-enum              v3.2.0           Simple, extensible and powerful enumeration implementation for Laravel.
bytelaunch/readonly-on-update      dev-main da82d10 A Laravel Nova tool.
chris-ware/nova-breadcrumbs        2.1.2            A Laravel Nova tool.
davidpiesse/nova-toggle            0.0.6            A Boolean Toggle Switch Field
dillingham/nova-assertions         1.2.0            Nova api testing requests & assertions
dillingham/nova-detail-link        1.0.2            A Laravel Nova field.
ebess/advanced-nova-media-library  3.4.0            Laravel Nova tools for managing the Spatie media library.
eminiarts/nova-permissions         1.0.6            Laravel Nova Grouped Permissions.
eminiarts/nova-tabs                1.3.1            Laravel Nova - Tabs.
facade/ignition                    2.5.3            A beautiful error page for Laravel applications.
fakerphp/faker                     v1.13.0          Faker is a PHP library that generates fake data for you.
fideloper/proxy                    4.4.1            Set trusted proxies for Laravel
fourstacks/nova-checkboxes         v0.1.7           A Laravel Nova field.
fruitcake/laravel-cors             v2.0.3           Adds CORS (Cross-Origin Resource Sharing) headers support in your Laravel application
google/apiclient                   v2.8.3           Client library for Google APIs
guzzlehttp/guzzle                  7.2.0            Guzzle is a PHP HTTP client library
illuminatech/nova-config           1.0.2            A Laravel Nova tool for application configuration management.
kabbouchi/nova-impersonate         v1.4.0           A Laravel Nova field allows you to authenticate as your users.
langleyfoxall/xero-laravel         v3.1.1           💸 Access the Xero accounting system using an Eloquent-like syntax
laravel/framework                  v8.19.0          The Laravel Framework.
laravel/nova                       3.17.0           A wonderful administration interface for Laravel.
laravel/slack-notification-channel v2.3.0           Slack Notification Channel for laravel.
laravel/tinker                     v2.5.0           Powerful REPL for the Laravel framework.
martinjuul/many-to-many            1.0.1            A Laravel Nova field.
mockery/mockery                    1.4.2            Mockery is a simple yet flexible PHP mock object framework
nunomaduro/collision               v5.1.0           Cli error handling for console/command-line PHP applications.
php-junior/nova-logs               v1.0.10          Provides a Log Viewer for Laravel Nova
phpunit/phpunit                    9.5.0            The PHP Unit Testing framework.
saumini/count                      v1.0.1           A Laravel Nova field.
silvanite/novatoolpermissions      v1.1.3           Laravel Nova Permissions (Roles and Permission based Access Control (ACL))
spatie/laravel-medialibrary        8.10.1           Associate files with Eloquent models
webklex/laravel-imap               2.3.0            Laravel IMAP client
```

**Comment by crynobone** [comment]
> I'm scared you are going to judge me..

Need to see if there any filter package that could cause the issue.

**Comment by navidnadali** [comment]
I know @crynobone , I'm just joking at the number of packages used..  Thanks for looking at it so quickly. 

If you think its a conflicting package, I'll start removing one by one and see where I get? This was in my history (so I had the same train thought)

```
root@709969ea0b54:/var/www# composer show -D | grep -c filter
0
```

**Comment by crynobone** [comment]
Unable to reproduce the issue on fresh Laravel Nova application, you can see the reproducing code at https://github.com/nova-issues/issue-3139/commit/99909e0b421fcefd52325a69d7b8dba3f9fcfdd3

![CleanShot 2020-12-22 at 10 22 43](https://user-images.githubusercontent.com/172966/102841371-cc879c80-443f-11eb-9e57-8ac438725ee6.gif)

**Comment by navidnadali** [comment]
Hi @crynobone , Thanks for reproducing. 

I have further information following more investigation on my side. 

I've xdebugged the code as the filtering logic is performed in laravel/nova and the following diff fixes the issue in my case:

```
Index: vendor/laravel/nova/src/FilterDecoder.php

<+>UTF-8
===================================================================
--- vendor/laravel/nova/src/FilterDecoder.php	(date 1608607059408)
+++ vendor/laravel/nova/src/FilterDecoder.php	(date 1608607059408)
@@ -44,8 +44,8 @@
         }
 
         return collect($filters)->map(function ($filter) {
-            $class = key($filter);
-            $value = $filter[$class];
+            $class = $filter['class'];
+            $value = $filter['value'];
 
             $matchingFilter = $this->availableFilters->first(function ($availableFilter) use ($class) {
                 return $class === $availableFilter->key();

```

Looks like the incoming array of filters in my case is different to what is expected. 

This is the value of $filters as set in (https://github.com/laravel/nova/blob/3.0/src/FilterDecoder.php#L80)

```
array (
  0 => 
  array (
    'class' => 'WebsiteStatus',
    'value' => 'inactive',
  ),
) 
```

Looks like the code is expecting something like: 

```
array (
  0 => 
  array (
    'WebsiteStatus' => 'inactive'
  ),
) 
```

**Comment by navidnadali** [comment]
I've also checked off the following off my list of things to check (with no luck):

1. Confirmed no scopes are being applied on model
2. Removed any plugins/modules that could interfere, anything nova/field/filter related
3. Tried stock AppServiceProvider and removed all tools. 
4. Removed vendor folder completely (rm -rf vendor/*) and reran composer install in case of any local changes.

**Comment by crynobone** [comment]
> I've xdebugged the code as the filtering logic is performed in laravel/nova and the following diff fixes the issue in my case

This changes should be irrelevant in the issue. On my reproducing tests I specify `3.17.0` tag which should have the same value as what you have at the moment (unless you not using stable release).

> I've also checked off the following off my list of things to check

Did you run `php artisan nova:publish`?

**Comment by devfrey** [comment]
Ran into the same issue, `php artisan nova:publish` fixed it

**Comment by navidnadali** [comment]
Thank you both, that fixed it. 

Still not sure about the data structure of the encoded filters being sent changing depending on if nova assets have been published or not, but I think we all have bigger fish to fry..

All the best

**Comment by MesselhyLinkDev** [comment]
Hello there, somehow I ran into the same error and I had to change the FilterDecoder.php file... I tried the `php artisan nova:publish` and it didnt work with me i completely changed my filters function from this:
`public function filters()
    {
        if (empty($filters = $this->decodeFromBase64String())) {
            return collect();
        }

        return collect($filters)->map(function ($filter) {
            $class = key($filter);
            $value = $filter[$class];

            $matchingFilter = $this->availableFilters->first(function ($availableFilter) use ($class) {
                return $class === $availableFilter->key();
            });

            if ($matchingFilter) {
                return ['filter' => $matchingFilter, 'value' => $value];
            }
        })
            ->filter()
            ->reject(function ($filter) {
                if (is_array($filter['value'])) {
                    return count($filter['value']) < 1;
                } elseif (is_string($filter['value'])) {
                    return trim($filter['value']) === '';
                }

                return is_null($filter['value']);
            })->map(function ($filter) {
                return new ApplyFilter($filter['filter'], $filter['value']);
            })->values();
    }
`


to this:

`public function filters()
{
    // 1) Decode once, into a local
    $decoded = $this->decodeFromBase64String();

    // 2) If it's empty or not an array, bail out early
    if (empty($decoded) || ! is_array($decoded)) {
        return collect();
    }

    return collect($decoded)
        ->map(function ($filter) {
            // 3a) New Nova “class/value” structure
            if (is_array($filter) && array_key_exists('class', $filter) && array_key_exists('value', $filter)) {
                $class = $filter['class'];
                $value = $filter['value'];

            // 3b) Legacy structure: [ 'Some\Filter\ClassName' => $value ]
            } elseif (is_array($filter) && count($filter) === 1) {
                $class = key($filter);
                $value = current($filter);

            // 3c) Completely unexpected: log & skip
            } else {
                \Log::warning('Skipping unexpected Nova filter format', ['filter' => $filter]);
                return null;
            }

            // 4) Find the actual Filter instance by key()
            $matching = $this->availableFilters
                             ->first(fn($f) => $f->key() === $class);

            return $matching
                ? ['filter' => $matching, 'value' => $value]
                : null;
        })
        // 5) Remove nulls (bad formats)…
        ->filter()
        // 6) Drop any “empty” values
        ->reject(function ($item) {
            $v = $item['value'];

            if (is_array($v)) {
                return count($v) < 1;
            }

            return is_null($v) || (is_string($v) && trim($v) === '');
        })
        // 7) Wrap ’em up as ApplyFilter objects
        ->map(fn($item) => new ApplyFilter($item['filter'], $item['value']))
        ->values();
}
`

i kindly want to know why did this issue appear all of a sudden and also im not applying any filters from my resource
`  public function filters(NovaRequest $request)
    {
        return [];
    }`

my laravel nova version = 4.35.10
