### ISSUE TITLE
Login action redirect to wrong URL

### ISSUE THREAD

**Issue by Livijn** [laravel/nova-issues#314]
Hey, when using *ngrok* for temporarily sharing my site, Nova directs the form action to my local url `xxx.test/nova/login` instead of `http://0893c4dc.ngrok.io/nova/login`.  I tested updating the `APP_URL` in the `.env` but Nova is not listening to that change. I did also clear the config cache.

When I check the `login.blade.php`, I see that Nova uses `action="{{ route('nova.login') }}"`. That route is registered like this:
```
Route::namespace('Laravel\Nova\Http\Controllers')
            ->middleware($middleware)
            ->as('nova.')
            ->prefix(Nova::path())
            ->group(function () {
                Route::get('/login', 'LoginController@showLoginForm');
                Route::post('/login', 'LonController@login')->name('login');
            });
```

How can I make it so that Nova uses the current APP_URL?

**Comment by davidhemphill** [comment]
This doesn't seem to be an issue anymore from my testing with ngrok.

**Comment by Matpewka** [comment]
Same problem with nginx with proxy_pass directive
