### ISSUE TITLE
Policy relation not working (HasMany)

### ISSUE THREAD

**Issue by groax** [laravel/nova-issues#3140]
- Laravel Version: 7.30.1
- Nova Version: 3.18.0
- PHP Version: 7.4.2

### Description:
Hi,

I have a problem with the Policies and im not able to filter relations.. 
What i want to do is disable the 'Create' button in the Navpack rescource and enable it when making a relation with a Client.
I followed the documentation (authorization#relationships) but it is not working :(

I have a model ```Fund``` and ```Navpack``` the Resource for ```Fund``` is named ```Client```.
The Policies are named ```ClientPolicy``` and ```NavpackPolicy```

The roles are working with LDAP.

#### Fund model
```
class Fund extends Model
{
    // more stuff above :)

    public function navpacks()
    {
        return $this->hasMany(NavPack::class, 'client_id');
    }
}
```

#### NavPackPolicy
```
class NavPackPolicy extends Policy
{
    use HandlesAuthorization;

    public function create(User $user): bool
    {
        return false;
    }

    public function addFund(User $user, Fund $model): bool
    {
        return $this->check($user, 'intranet_navpack_client_create', $model);
    }
}
```

#### Policy
```
abstract class Policy
{

    protected function check(User $user, string $string, object $model = NULL)
    {
        if ($string === 'false' or $string === '') {
            return false;
        } elseif ($string === 'true') {
            return true;
        }

        return in_array($string, $user->roles()) or in_array(self::$admin, $user->roles());
    }
}
```

#### Result
![image](https://user-images.githubusercontent.com/11779856/102943096-65a5ca00-44b7-11eb-8182-f67d4f893213.png)

#### AuthServiceProvider
```
protected $policies = [
    // Model => Policy
    Fund::class => ClientPolicy::class,
    NavPack::class => NavPackPolicy::class,
];
```
Im stuck for 2 days now and im getting crazy here :P

Can someone help me with this?

**Comment by groax** [comment]
And yes! the User has the role 'intranet_navpack_client_create' 👍

**Comment by crynobone** [comment]
I having a hard time following the issue. From what I understand is that `NavPack` resource should be read-only and user can create `NavPack` from `Fund` detail page.

In that case shouldn't you need to have `ClientPolicy::addNavPack()` method instead?

**Comment by groax** [comment]
No, doesn't work :(

**Comment by crynobone** [comment]
```js
    /**
     * Determine if the create button should be displayed.
     */
    shouldShowCreateButton() {
      return (
        this.authorizedToCreate &&
        this.authorizedToRelate &&
        !this.alreadyFilled
      )
    },
```

Based on `CreateResourceButton.vue` it's seem to be an expected behavior to require `NavPackPolicy::create()` to return `true` before allowing it to be created from `Fund` resource.

**Comment by groax** [comment]
So add(model) is a joke? because `Create` has to be `true` for add(model) to work but it doesn't

**Comment by crynobone** [comment]
> So add(model) is a joke? because Create has to be true for add(model) to work but it doesn't
If i set NavPackPolicy::addFund() or ClientPolicy::addNavPack() to false, the button is still showing

Based on the code, yes that's seem to be the case. Unfortunately changing this right now going to cause a breaking change to anyone that's expecting it to work as it is. Will queue a documentation PR to add the tip/warning to the feature.

**Comment by groax** [comment]
okay it works now.. but the Create is still showing on the `Resource`, I will hide it with CSS  and move on and wait on a fix. Thnx for the help @crynobone!
