### ISSUE TITLE
Unique Validation on Nullable Fields

### ISSUE THREAD

**Issue by kmekler** [laravel/nova-issues#3141]
- Laravel Version: ^7.0
- Nova Version: ^3.0
- PHP Version: ^7.4
- Operating System: Mac
- Browser type: Chrome 

### Description:

I've got a nullable field that validates for uniqueness, but if the user leaves that field blank, they get an error saying that the name is already taken because there's already a value of NULL in the database. I can't find a way to only apply the unique validation if the field is not empty, and have seen others looking to do the same.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Text::make('Name')
       ->sortable()
       ->nullable()
        ->creationRules('unique:employers,name')
        ->hideFromIndex(),

**Comment by crynobone** [comment]
You should just create custom validation rule for this case.

**Comment by mahfoudfx** [comment]
@kmekler can you try without `->nullable()` and with `nullable` inside `creationRules`
```php
Text::make('Name')
    ->sortable()
    ->creationRules('nullable', 'unique:employers,name')
    ->hideFromIndex(),
```
