### ISSUE TITLE
Lens ordering with MSSQL

### ISSUE THREAD

**Issue by jirkacisar** [laravel/nova-issues#3143]
- Laravel Version: 8.20.1
- Nova Version: 3.18.0
- PHP Version: 7.4.12
- Database Driver & Version: sqlsrv (PHP drivers Version 5.8.1 for SQL Server)
- Operating System and Version: Win 10
- Browser type and version: Edge latest (but it does not matter)

### Description:
- error message on the second page of the lens

### Detailed steps to reproduce the issue on a fresh Nova installation:
- create new lens by https://nova.laravel.com/docs/3.0/lenses/defining-lenses.html
- define functions like:
```
    public static function query(LensRequest $request, $query)
    {
        return $request->withOrdering($request->withFilters(
            $query->select(self::columns())
                  ->orderBy('revenue', 'desc')
        ));
    }
    protected static function columns()
    {
        return [
            'companies.id',
            'companies.title',
            DB::raw('1 as revenue'),
        ];
    }
    public function fields(Request $request)
    {
        return [
            ID::make(__('ID'), 'id')->sortable(),
            
            Text::make('Title', 'title'),

            Number::make('Revenue', 'revenue', function ($value) {
                return '$'.number_format($value, 2);
            }),
        ];
    }
```
- first page is ok, but go to the second page and get the error: https://imgur.com/Jq9t0Kf
- if I remove ```->orderBy('revenue', 'desc')``` then it works, but unordered...

**Comment by crynobone** [comment]
I think this seem to be MSSQL specific/usage issue, have you tried asking on one of the support channel <https://nova.laravel.com/docs/3.0/support.html>

**Comment by jirkacisar** [comment]
>have you tried asking on one of the support channel https://nova.laravel.com/docs/3.0/support.html
I'll try, thank you.
