### ISSUE TITLE
undefined index: class - on all resources with defined filters

### ISSUE THREAD

**Issue by eAvio** [laravel/nova-issues#3145]
- Laravel Version: 7.30.1
- Nova Version: 3.18.0
- PHP Version: 7.4.13
- Database Driver & Version: MySQL 5.7
- Operating System and Version: MacOS
- Browser type and version: Safari 14

### Description:
Suddenly all resources that uses filters trowing error: "undefined index: class" ... If I remove all the filters from "filters" list then it works, but I don't have any filter.

`Undefined index: class {"userId":1,"exception":"[object] (ErrorException(code: 0): Undefined index: class vendor/laravel/nova/src/FilterDecoder.php:48)`

**Comment by crynobone** [comment]
Please run `php artisan nova:publish` to fixed the issue.
