### ISSUE TITLE
Make BooleanGroup work for SET columns

### ISSUE THREAD

**Issue by cweiske** [laravel/nova-issues#3146]
BooleanGroup fields save their data as JSON-encoded string into the database.

MySQL provides the ["SET" type](https://dev.mysql.com/doc/refman/8.0/en/set.html):
> A SET is a string object that can have zero or more values, each of which must be chosen from a list of permitted values specified when the table is created

SETs take up little space, unlike the JSON strings.
Querying records that have one of the values in the set is also very easy with FIND_IN_SET.

Please make BooleanGroup work with SQL SET columns.

**Comment by crynobone** [comment]
This need to be supported by Laravel Framework first, and ideally compatible with Postgres, Sqlite and MSSQL.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
