### ISSUE TITLE
Combine all of Nova custom packages' assets

### ISSUE THREAD

**Issue by sbarale** [laravel/nova-issues#3147]
This is in reference to this post id: https://github.com/laravel/nova-issues/issues/1146#issuecomment-515891323

I -**love**- Nova... but I'm having to run this command in order to make sure the tool is performant, so the question is two-fold: 

1) Will this ever be addressed ? 
2) Am i overlooking something and it's not required to be run ?

The problem I'm facing is that, even though the script referenced above is AWESOME .. the more things you add, the bigger those files become. I have a feeling that there's A LOT of duplicated code which could (potentially) be saved by tying everything together using laravel-mix and in the end, just run 'npm run prod' before deploying the tool to production.

Keep up the good work!

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
This will be a big feature request, while the suggested command would work in some setup it also would need to handle the following:

* Asset on remote site including CDN should be excluded.
* Asset for Tool accessible for some users shouldn't be accessible to another set of user, combining all assets going to break this, and above command completely ignore this. This will be the hardest challenge.
