### ISSUE TITLE
redirectAfterDelete not work on index resource

### ISSUE THREAD

**Issue by rvalenzuelaferrada** [laravel/nova-issues#3148]
- Laravel Version: 8.20.1
- Nova Version: 3.18.0
- PHP Version: 7.3

When removing an element from the index resource, it does not do the redirection, this would be the expected behavior, but currently it only works on the resource detail page

**Comment by crynobone** [comment]
> When removing an element from the index resource, it does not do the redirection, this would be the expected behavior, but currently it only works on the resource detail page.

Yup, that the expected behavior possible at the moment. In index, you will be able to delete multiple resources at once and it would be impossible to cover all the possible redirection.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
