### ISSUE TITLE
BelongsToMany pivot fields now shown

### ISSUE THREAD

**Issue by orlyapps** [laravel/nova-issues#315]
The pivot content is shown in the edit but not in the index. But when i change the pivot keys like this
"pivot.price" it shows on the index but no longer on the edit :)

```

BelongsToMany::make('Articles')->fields(new ArticleSupplierFields)

// Pivot fields
class ArticleSupplierFields
{
    public function __invoke()
    {
        return [
            Number::make('price'),
            Number::make('delivery_time'),
            Boolean::make('default')
        ];
    }
}`

```

![selection_036](https://user-images.githubusercontent.com/5220826/44791910-0bc0be00-aba3-11e8-9a63-ca47646bf82a.png)

![selection_037](https://user-images.githubusercontent.com/5220826/44791935-1da26100-aba3-11e8-91e9-ca406f7ffe09.png)

**Comment by Jam0r85** [comment]
I'm having a similar issue but the fields are not shown when creating or updating either.

**Comment by orlyapps** [comment]
I have found a "workaround", you can add "displayUsing" to the pivot fields and it should work.

```
            Number::make('price')->displayUsing(function($field) {}),
            Number::make('delivery_time')->displayUsing(function($field) {}),
            Boolean::make('default')->displayUsing(function($field) {}),
```

**Comment by BengtHagemeister** [comment]
same as #186

**Comment by admench** [comment]
In your laravel model, have you ensured that the relationship method includes the pivot data? That fixed it for me.

```
public function end_users()
    {
        return $this->belongsToMany(EndUser::class)->withPivot('notes');
    }
```

**Comment by maherelgamil** [comment]
as @admench said in the previous comment , you should add `->withPivot('notes');` in your relation.

**Comment by midesweb** [comment]
For me the problem was a Nova outdated version. I have updated Nova to solve the issue https://nova.laravel.com/docs/2.0/installation.html#updating-nova
