### ISSUE TITLE
Stop using static class/properties/method to increase flexibility and customization

### ISSUE THREAD

**Issue by alberto-bottarini** [laravel/nova-issues#3151]
Hi, i would like to propose this idea in order to make nova cooler and more flexible than now.
I used Nova a lot in the last year and often I face with this "static issue" that limits a lot my flexibility.

### Proposal: To avoid use of `static` things

Using static method, property, class reference is a big limit. You have to write each resource and you cannot create dynamic stuff. I try to better explain with some examples.

### Dynamic dashboard:

An administrators of a Nova installation would like to be autonomous to create dashboards. I create a Model/Resource called CustomDashboard. Each CustomDashboard has a list of widgets with some data and configurations. It's a regular model that will persist on `custom_dashboard` table.

I would like to create automatically a Nova Dashboard class for each of these CustomDashboard. I tried with this in NovaServiceProvider:

```shell
php artisan nova:dashboard CustomNovaDashboard
```

```php
    protected function dashboards()
    {
        return [
           CustomDashboard::all()->map(function($dashboardModel) { 
               return new CustomNovaDashboard($dashboardModel);
           });
        ];
    }
```

It seems to work but it's not true.

Each Nova Dashboard class needs to implement some ugly static methods (`label` and `uriKey`) and this breaks my idea. If these methods were not-static, i could write them, for example, in this way:

```php
class CustomNovaDashboard {

    public function __construct(CustomDashboard $dashboardModel)
    {
        $this->dashboardModel = $dashboardModel;
    }

    public function label()
    {
        return $this->dashboardModel->title;
    }

    public function label()
    {
        return str_slug($this->dashboardModel->title);
    }
    
    public function cards()
    {
        //some custom logic based on $this->dashboardModel
    }
}

```

Bam! Automatically I can allow user to create dashboard!

### Dynamic resource:

Sometimes I have model that has `type` attribute. Type is a belongsTo relationship. For example I could create Course model and different types like "Free", "Premium", "Paid".
Customers would like to have these course split in 3 different resources in navigation bar. 
I can perform it creating 3 similar resource and using `indexQuery` method to filter out records. For example:

```php
class FreeCourse extends Resource
{
    public static $model  = 'App\Models\Course';
    
    public static function indexQuery(NovaRequest $request, $query)
    {
        $query->where('type_id', 1);
    }
}

class PremiumCourse extends Resource
{
    public static $model  = 'App\Models\Course';
    
    public static function indexQuery(NovaRequest $request, $query)
    {
        $query->where('type_id', 2);
    }
}
```

This is very frustrating. I cannot create dynamic Resource but I need to copy&paste them, changing the type_id in the indexQuery method. Very bad.

Like in the dashboard example, if these methods were not static, I could write, for example, this example:

```php
class TypedCourse extends Resource
{
    public static $model  = 'App\Models\Course';

    public function __costruct(Type $type)
    {
        $this->type = $type;
    }
    
    public function indexQuery(NovaRequest $request, $query)
    {
        $query->where('type_id', $this->type->id);
    }
}
```

And in NovaServiceProvider:

```php
protected function resources()
{
    Nova::resources(Type::all()->map(function($type) {
        return new TypedCourse($type);
    });
}
```

Bam! Dynamic resources with automatic filter!

### Dynamic lens:

Same problem as before. 

### Dynamic actions, filters, metrics, cards:

What? Oh yes! 
They are already a non-static class. 
Why? I think they are implemented in a better way, allowing developers to be more creative!

Why this different approach?

### And so?

The only advantage to use static things in Nova is to avoid the instantiation of class in order to retrieve some "extra information" like the `model`, `search`, `title`. But this is a very big limitation in my opinion and, in a product like Nova, the customization is more important than to limit resource consumption. 

A change like this, I know, is a big not retro-compatible change, but I think it will be also a big improvement that does not cost so much in terms of effort. 
I'm sure a lot of developers will appreciated this.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by cord** [comment]
In the meanwhile enjoy https://novapackages.com/packages/nova-bi/nova-dashboard-manager

**Comment by alberto-bottarini** [comment]
I'll take a look. Thanks

**Comment by muhammadsaeedparacha** [comment]
@alberto-bottarini  Hey were you able to find a working solution for this?

**Comment by alberto-bottarini** [comment]
Yes, in a super ugly way. I'm so sorry to share it with you :)

Basically I created an inline Dashboard class (using `eval`) that extends a BaseDashboardClass. I also set my dashboard model as static property of that class in order to retrieve it in my static and not-static method (uriKey, label, cards...)

In `dashboards` method in NovaServiceProvider`:

```php
    protected function dashboards()
    {
        return MyDashboardModel::all()->map(function($dashboard) {
            $className = "FakeCustomNovaDashboard{$dashboard->id}";
            eval("class $className extends App\Nova\Dashboards\CustomNovaDashboard  {
                public static \$staticDashboard;
                public static function getStaticDashboard()
                    {
                        return self::\$staticDashboard;
                    }
            };");
            $novaDashboard = new $className;
            $novaDashboard::$staticDashboard = $dashboard;
            $novaDashboard->dashboard = $dashboard;
            return $novaDashboard;
        })->toArray();
    }
```


and in my `App\Nova\Dashboards\CustomNovaDashboard` class

```php
abstract class CustomNovaDashboard extends Dashboard
{

    public function cards()
    {
        $dashboardModel = static::getStaticDashboard();
        //custom logic to create card
    }

    public static function uriKey()
    {
        return 'custom-dashboard-' . static::getStaticDashboard()->id;
    }

    public static function label()
    {
        return static::getStaticDashboard()->name;
    }

    abstract public static function getStaticDashboard();
}

```
