### ISSUE TITLE
Popup Filter Date not open in desktop view but open in mobile view

### ISSUE THREAD

**Issue by massimodellarovere** [laravel/nova-issues#3152]
- Laravel Version: 8.21.0
- Nova Version: 3.19.0
- PHP Version: 7.4.3
- Database Driver & Version: MYSQL
- Operating System and Version: Ubuntu 20.04.1 LTS
- Browser type and version: Chrome Versión 87.0.4280.66 (Build oficial) (64 bits)

### Description:

Popup Filter Date not open in desktop view but open in mobile view (with version nova 3.18 is ok)

### Detailed steps to reproduce the issue on a fresh Nova installation:
![Captura de pantalla_área-de-selección_20210105222459](https://user-images.githubusercontent.com/5731295/103725952-b8967b80-4fa5-11eb-9b8c-aaf94db57f59.jpg)

Console Developer Chrome
![Captura de pantalla_área-de-selección_20210105223324](https://user-images.githubusercontent.com/5731295/103726101-162ac800-4fa6-11eb-8cdc-b348947072a2.jpg)

**Comment by crynobone** [comment]
This should be fixed in 3.19.1, https://nova.laravel.com/releases/3.19.1
