### ISSUE TITLE
Resource with Scout Search wrong initial order by after Upgrade Version 3.19 Nova

### ISSUE THREAD

**Issue by massimodellarovere** [laravel/nova-issues#3153]
- Laravel Version: 8.21.0
- Nova Version: 3.19.0
- PHP Version: 7.4.3
- Database Driver & Version: MYSQL
- Operating System and Version: Ubuntu 20.04.1 LTS
- Browser type and version: Chrome Versión 87.0.4280.66 (Build oficial) (64 bits)

### Description:

Resource with Scout wrong initial order by after Upgrade Version 3.19 Nova

### Screen with version 3.18 - The product  initial order by ID descend.. New products are first..
![OLD](https://user-images.githubusercontent.com/5731295/103730702-75420a00-4fb1-11eb-9a5a-f4beceebbb6e.jpg)

### Screen with version 3.19 - The product  initial order by ID ascend.. OLD products are first..
![new](https://user-images.githubusercontent.com/5731295/103730729-82f78f80-4fb1-11eb-9e44-c4f002cb3074.jpg)

**Comment by crynobone** [comment]
This should be fixed in 3.19.1, https://nova.laravel.com/releases/3.19.1
