### ISSUE TITLE
Pagination - Optionally don't calculate and display total record counts

### ISSUE THREAD

**Issue by andrew-belac** [laravel/nova-issues#3156]
Some context.  I have a table with a little over 300,000 records in it.  The table is being used for staging.  The environment is deployed using Vapor.  The initial load time of the resource index page can take a long time on a small database and even when the database instance size is larger it still is 95% of the total time for the resource index page to load.  

I don't believe the pagination past a 10 pages or showing the total number or records is useful when there are large row counts.  Users will filter or search to find the data they are looking for.  After researching the select count(*) problem and realising the this query cannot be optimised for InnoDB tables I would ask that when the pagination mode is "simple" the option to remove the total record count and not to perform the query at all is made available via a configuration option.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
