### ISSUE TITLE
Console error when using date filter

### ISSUE THREAD

**Issue by dgoldstein89** [laravel/nova-issues#3157]
- Laravel Version: 7.30.1
- Nova Version: 3.19.1
- PHP Version: 7.4.5
- Database Driver & Version: MySQL 5.7.29
- Operating System and Version: Windows 10 Pro
- Browser type and version: Chrome 87.0.4280.88

### Description:
Selecting a date on the date filter produces a console error: `Uncaught (in promise) Error: Navigation cancelled...`
The filter still seems to work fine. I imagine this is related to #3035.

**Comment by crynobone** [comment]
I seen the error few times before and it's more of a warning than an error. In the past we try to catch the exception to avoid being thrown to console but I worry we hiding an actual error if similar exception thrown using the same type.
