### ISSUE TITLE
Search with Scout + Elasticsearch failed after upgrade version 3.19 

### ISSUE THREAD

**Issue by massimodellarovere** [laravel/nova-issues#3158]
- Laravel Version: 8.21.0
- Nova Version: 3.19.0
- PHP Version: 7.4.3
- Database Driver & Version: MYSQL
- Operating System and Version: Ubuntu 20.04.1 LTS
- Browser type and version: Chrome Versión 87.0.4280.66 (Build oficial) (64 bits)
- Laravel Scout + babenkoivan/elastic-scout-driver v1.2.1 

### Description:

Search failed after upgrade version 3.19 Nova 

![Captura de pantalla_área-de-selección_20210107180328](https://user-images.githubusercontent.com/5731295/103955533-7b9cc700-5114-11eb-9c1c-84ee021c3b10.jpg)

**Comment by crynobone** [comment]
The only relevant place I see that could cause this is `take(static::$scoutSearchResults)`

```php
public static function buildIndexQueryUsingScout(NovaRequest $request, $search = null,
                                          $withTrashed = TrashedStatus::DEFAULT)
    {
        return tap(static::applySoftDeleteConstraint(
            static::newModel()->search($search), $withTrashed
        ), function ($scoutBuilder) use ($request) {
            static::scoutQuery($request, $scoutBuilder);
        })->take(static::$scoutSearchResults);
    }
```

Now, is `$scoutSearchResults` set to a `string` instead of `int`?

**Comment by massimodellarovere** [comment]
$scoutSearchResults is int

![Captura de pantalla_área-de-selección_20210107190351](https://user-images.githubusercontent.com/5731295/103958525-35973180-511b-11eb-968e-5639316f95cf.jpg)

**Comment by crynobone** [comment]
@massimodellarovere The code error out at https://github.com/babenkoivan/elastic-scout-driver/blob/master/src/Factories/SearchRequestFactory.php#L86-L89 and `$builder->limit` gets the value from `->take(static::$scoutSearchResults)`.

It's pretty straightforward to be honest, just that `babenkoivan/slastic-scout-driver` decide to use strict type on scout.

**Comment by crynobone** [comment]
Could you also check `$globalSearchResults` on Resource to ensure it's all int.

**Comment by massimodellarovere** [comment]
Check globalSearchResults

![Captura de pantalla_área-de-selección_20210107193631](https://user-images.githubusercontent.com/5731295/103960273-beb06780-511f-11eb-99e0-87da0767336b.jpg)

**Comment by massimodellarovere** [comment]
There is something very strange I added some log lines before the error

```php
protected function makeSize(Builder $builder, array $options): ?int
{
        \Log::info(is_int($options['perPage']) ? 'SI' : 'NO');
        \Log::info($options['perPage']);

        return $options['perPage'] ?? $builder->limit;
}
```

Result LOG is 25 but not INT

[2021-01-07 19:35:19] local.INFO: NO  
[2021-01-07 19:35:19] local.INFO: 25  
[2021-01-07 19:35:19] local.ERROR: Return value of ElasticScoutDriver\Factories\SearchRequestFactory::makeSize() must be of the type int or null, string returned {"userId":240669,"exception":"[object] (TypeError(code: 0): Return value of ElasticScoutDriver\\Factories\\SearchRequestFactory::makeSize() must be of the type int or null, string returned at /home/ubuntu/environment/e-website/vendor/babenkoivan/elastic-scout-driver/src/Factories/SearchRequestFactory.php:90)

**Comment by crynobone** [comment]
@massimodellarovere I don't know where `$options['perPage']` came from (doesn't seem to be laravel/scout), better check with the package maintainer on that.

**Comment by massimodellarovere** [comment]
OK thank you

**Comment by massimodellarovere** [comment]
I have noticed the following

/e-website/vendor/laravel/nova/src/Http/Requests/ResourceIndexRequest.php

```php
    /**
     * Get the paginator instance for the index request.
     *
     * @param  \Laravel\Nova\Http\Requests\ResourceIndexRequest  $request
     * @param  string  $resource
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return array
     */
    public function searchIndex()
    {
        $resource = $this->resource();             // I have add this
        var_dump($this->viaRelationship());    // I have add this
        var_dump($this->perPage);                 // I have add this

        return (new QueryBuilder($resource = $this->resource()))->search(
            $this, $this->newQuery(), $this->search,
            $this->filters()->all(), $this->orderings(), $this->trashed()
        )->paginate(
            $this->viaRelationship()
                        ? $resource::$perPageViaRelationship
                        : ($this->perPage ?? $resource::perPageOptions()[0])
        );
    }

```

Variable  $this->perPage is string

```
bool(false) string(2) "25" {,…}
exception: "TypeError"
file: "/home/ubuntu/environment/e-website/vendor/babenkoivan/elastic-scout-driver/src/Factories/SearchRequestFactory.php"
```

If change  

: ($this->perPage ?? $resource::perPageOptions()[0])
: (int) ($this->perPage ?? $resource::perPageOptions()[0])

My search return OK
![Captura de pantalla_área-de-selección_20210107213927](https://user-images.githubusercontent.com/5731295/103967868-df34ed80-5130-11eb-9672-280b584808a4.jpg)

**Comment by crynobone** [comment]
@massimodellarovere string shouldn't be the issue since Laravel pagination allows that. It seem that the package tried to force `int` when it accepts a int (with either string or int type).

I submitted laravel/nova#1161 but do think the package need to fix this as well.

**Comment by crynobone** [comment]
Submitted PR to https://github.com/babenkoivan/elastic-scout-driver/pull/12
