### ISSUE TITLE
Select/BelongsTo searchable method with parameter

### ISSUE THREAD

**Issue by bernhardh** [laravel/nova-issues#3159]
Select and Relation Fields have the method `searchable()` with no parameter. The method does the following:

```php
    public function searchable()
    {
        $this->searchable = true;

        return $this;
    }
```
why not add a parameter to disable the searchable if needed, like nova has for basically all other similar options. Something like this:

```php
    public function searchable($searchable = true)
    {
        $this->searchable = $searchable;

        return $this;
    }
```

This is an easy fix and would be backward compatible and break nothing.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
