### ISSUE TITLE
Advanced resource pagination with more information

### ISSUE THREAD

**Issue by chescos** [laravel/nova-issues#316]
The resource pagination should be improved. Currently, there is only a "Previous" and a "Next" button and no information whatsoever.

I'd like to see something like that on the bottom left:

![selection_112](https://user-images.githubusercontent.com/12296880/44792705-cbfad600-aba4-11e8-82fd-642f9b22e201.png)

And something like that on the bottom right:

![selection_113](https://user-images.githubusercontent.com/12296880/44792707-cbfad600-aba4-11e8-9c59-324c5c0e7b90.png)

**Comment by poxin13** [comment]
Agreed, was looking for something similar #305. Number of pages, records returned, etc.

**Comment by bluec** [comment]
Honestly thought pagination like this would be a baseline feature... i'd hardly call it advanced it's just standard for any CRUD admin interface. Hopefully this will get implemented soon because I don't see any way to do it easily and Nova is fairly useless without it IMO.

**Comment by davidhemphill** [comment]
It's done this way because it can be really resource intensive/slow to calculate that on really large datasets.

**Comment by chescos** [comment]
@davidhemphill do you consider adding it as an optional setting that could be enabled through a property on the resource? It could be disabled by default and enabled by adding something like `public static $advancedPagination = true;` to the resource.

Your concern makes a lot of sense but still, I believe that this feature is pretty important to many people.

**Comment by poxin13** [comment]
I've noticed that the request to get the required information for this is already currently being done in nova. If you check the network tab in chrome you can see a request that returns the current count of a resource including any filters and search results applied.

For example searching on a user resource will already run a request for:
```
/nova-api/users/count?search=username&filters=&perPage=25&trashed=&page=1
```
Which returns: `{"count":1}`. It's not not being displayed on the index.

**Comment by bluec** [comment]
> It's done this way because it can be really resource intensive/slow to calculate that on really large datasets.

@davidhemphill hmm this is not good. i understand there may be performance concerns on huge datasets but that doesn't mean this feature isn't necessary or warranted. this is a really basic requirement for an admin system.

**Comment by sdmpxs** [comment]
I tend to agree with the above comments that this is needed. I've just spent a few days converting an app from Backpack to Nova and now I may have to forget that as the client I've done this for uses the pagination as part of their workflow. It is a growing dataset of about 10K records that its needed for.

**Comment by bluec** [comment]
You would think that Nova would follow Laravel's methodology and use `paginate()` by default and provide an option to use `simplePaginate()` for large datasets when you do not need to display a link for each page number.

**Comment by ibrunotome** [comment]
I think this is a basic admin panel feature, the paginate methods of laravel api works good.

**Comment by dillingham** [comment]
**Disagree** I don't see skipping from page 1 to 4 to 7 to 8 as mission critical like others above.

I also think that with 5 tables on a page, the less clutter the better

**Comment by sdmpxs** [comment]
I’d normally agree except for one project where it is which is why I think it should be an option. If it isn’t mission critical for you, you don’t need to enable it.

**Comment by dillingham** [comment]
@sdmpxs can you describe why a user **needs** to jump from page 1 to 3 to 7 as a required workflow? Honestly don’t see the usefulness that ordering and searching and next and previous doesn’t satisfy?

**Comment by bluec** [comment]
@dillingham seriously? have you ever used another admin interface? could you not even envisage why it might be useful for a user to know _how many_ results they are browsing? are you actually saying that "less clutter" is a reason to deny features?

if this is really not something you consider reasonable, then why does laravel have a paginate() method? why does almost every data-led admin system in the world use pagination for result sets? it's so unbelievable basic, even MS Access had it in like 1997.

**Comment by dillingham** [comment]
As someone who wants the feature you should be able to defend its value lol am I not allowed to disagree, with actual points, not just “don’t enable it” while I ask why you NEED it? :)

**Comment by dillingham** [comment]
And I didn’t say anything about “result count” that makes sense. I said I disagree with that linking 1-2-3-4-5 is valuable in comparison to the clutter it creates.

**Comment by ibrunotome** [comment]
The Nova tables could at least show a small text "showing x of y results" in the bottom of the table, cause I think that I don't need a metric card to show the total rows of the table.

**Comment by chescos** [comment]
I agree that jumping from page 5 to 7 or from page 5 to 3 isn't that important. But I am really missing the total result count. This is so important for many situations, e.g when you want to know how many orders a customer has in total, or how many failed transactions a customer has (using a filter).

**Comment by bluec** [comment]
The value is this: it enables the user to navigate through the result set in a way that provides designation of their current position, provides knowledge of the size of the result set, and allows the user to jump forward or backward in defined chunks. 

For example, if you are browsing an alphabetical list of 1000 records all beginning with A in page sizes of 100, then you might have an inkling that the records you're most interested in are on around page 4 or 5. If you only have forward and backward that would be several mouse clicks away. User interface design isn't solely about making things look uncluttered, it's also about providing a suitable navigation experience and ensuring the user understands where they are etc.

All that said, the result count is arguably more important than the paginated navigation which I can understand some people not seeing a use case for. However, since the original objection was because DB counts are expensive, then if the result count is included (and therefore the final page number is known) then it's hard to see a reason not to also provide an option for a fuller pagination.

**Comment by chescos** [comment]
Anyways, I don't see a reason why both features (advanced pagination and row count) couldn't be added to Nova as an optional feature which needs to be enabled on the resource. Sure, performance might be an issue on big tables and maybe some people want a cleaner look. Making them optional removes this issue. Those features are very basic CRUD admin panel features and they are trivial to implement with Laravel and Vue. Many people expect them to be there because they are usually found in any CRUD admin panel and they have proven to be useful. I hope this still gets added.

**Comment by SanderMuller** [comment]
I agree, this feature is needed.

**Comment by Etmolf** [comment]
Laravel already has pagination and knows how to return pagination responses on API requests including any needed meta information.

current_page | 1
-- | --
data | […]
first_page_url | "http://page.local?page=1"
from | 1
last_page | 2
last_page_url | "http://page.local?page=2"
next_page_url | "http://page.local?page=2"
path | "http://page.local"
per_page | 50
prev_page_url | null
to | 50
total | 75

Should not really be a problem. Why reinvent the wheel? :-)

**Comment by davidhemphill** [comment]
Nova now shows the current and total results in the bottom of the footer.

**Comment by chescos** [comment]
@davidhemphill The last update that I see on the [Releases](https://nova.laravel.com/releases) page is from October 25, 2018 (3 weeks ago), are you talking about a future release? Just a little confused because you said `Nova now shows [...]`.

**Comment by davidhemphill** [comment]
The resource current/total count has been added to the bottom of the footer and will be included in an upcoming release.

**Comment by bluec** [comment]
Does this mean the option for full pagination will be coming soon?

**Comment by davidhemphill** [comment]
Not necessarily but I'll be looking into it soon.

**Comment by poxin13** [comment]
Looks like this didn't make it in v1.1.8?

**Comment by asantibanez** [comment]
Hi @davidhemphill 

Quick question, is there a way to limit the number of records returned in the pagination? Let's say I want the first 20 records. Currently, Nova just returns the last 5 records.

Thanks in advance.

**Comment by dkulyk** [comment]
![pagination](https://user-images.githubusercontent.com/370042/49407497-7b75b480-f761-11e8-9fa1-7e785695c052.gif)

**Comment by dkulyk** [comment]
PR was send to upstream.
Looks like that:
![image](https://user-images.githubusercontent.com/370042/49442443-3178e700-f7d2-11e8-9419-fd4acf8cdb7d.png)

**Comment by dillingham** [comment]
Currently the "25/150 resources" is more confusing when you click next & it doesnt change

should be (perPageCount * pageNumber) . '/' . totalCount

also would love it if it didnt say "resources" 50/150 is clear enough to me & doesnt add context

**Comment by dillingham** [comment]
Related https://github.com/laravel/nova-issues/issues/1148

**Comment by aszaffranietz** [comment]
@dkulyk would love to see that implemented. :heart:

**Comment by dkulyk** [comment]
Maybe after New Year holidays.

**Comment by thechrisroberts** [comment]
Definitely would like to see pagination improvements, including:

- Upon switching pages, page should scroll to the top
- Have actual page count links showing current page/total # of pages (configurable for cases where this might cause performance issues)
- If not page counts, then at least adjust the current counts for clarity. The "number shown/total entries" is more confusing than helpful and tells me nothing about where I am in a result set.
- Pagination links at the top as well as bottom of the list - or at least pagination info at the top, so when you're at the top of the page you'll know that you're not on page 1 of results, etc.

**Comment by chescos** [comment]
I agree with @thechrisroberts - pagination still needs a lot of improvements, and it's currently poorly implemented. Just look at how other admin panels and data table libraries do it. No need to reinvent this, pretty much everyone is doing the same thing and it works great:

* Display forward and backward buttons
* Display the number of total rows
* Display the current page number
* Display buttons for jumping forward and backward more than just 1 page
* Display the current position in the table ("showing rows from offset X to offset Y")

**Comment by davidhemphill** [comment]
There's going to be some work on advanced pagination, but got some other priorities first. Will update this thread when we get there.

**Comment by plakhin** [comment]
Documentation says:

> By default, Nova Resources are displayed using the "simple" style. However, you may customize this to use the "links" style. You can enable this by setting the `pagination` option in your `app/nova.php` configuration file:

Absolutely not clear. What is this `app/nova.php` config file? Can not find it anywhere.

**Comment by bolechen** [comment]
> Documentation says:
> 
> > By default, Nova Resources are displayed using the "simple" style. However, you may customize this to use the "links" style. You can enable this by setting the `pagination` option in your `app/nova.php` configuration file:
> 
> Absolutely not clear. What is this `app/nova.php` config file? Can not find it anywhere.

pagination config only for nova 2.x now

**Comment by plakhin** [comment]
> pagination config only for nova 2.x now

I recently updated to Nova 2.0, may be the reason is that I updated but not made a fresh install. Can not understand where to look for `app/nova.php` config file.

**Comment by bolechen** [comment]
> > pagination config only for nova 2.x now
> 
> I recently updated to Nova 2.0, may be the reason is that I updated but not made a fresh install. Can not understand where to look for `app/nova.php` config file.

look at this

https://github.com/laravel/nova/blob/2.0/config/nova.php

u may run php `nova:publish` after upgrade?

**Comment by plakhin** [comment]
>https://github.com/laravel/nova/blob/ed076595b2b5b42c5153572de82954759e8dc7a3/config/nova.php#L92

Not found :(

> u may run php nova:publish after upgrade?

don't remember, will try now

**Comment by plakhin** [comment]
Running `nova:publish` updated published nova resources and now adding `'pagination' => 'links',` to 
 `config/nova.php` did the switch. (Before running `nova:publish` it did nothing of course).

So, documentation should be fixed:
"You can enable this by setting the `pagination` option in your `app/nova.php` configuration file" should be "You can enable this by setting the `pagination` option in your `config/nova.php` configuration file".

**Comment by plakhin** [comment]
The last question is how to display 100 records per page, not 25.

**Comment by greggh** [comment]
@davidhemphill the docs say app/nova.php for setting the pagination to links, should be config/nova.php. Simple one, but people here seem to be having trouble with it.
