### ISSUE TITLE
No Resources translations in Jetstream setup

### ISSUE THREAD

**Issue by vodolgiy** [laravel/nova-issues#3160]
- Laravel Version: 8.21.0
- Nova Version: 3.19.1
- PHP Version: 7.4.13
- Database Driver & Version: MariaDB 10.5.8-1
- Operating System and Version: Linux 5.9.16-1-MANJARO x86_64 20.2.1 Nibia
- Browser type and version: Firefox Developer Edition 85.0b4-1
- Reproduction Repository: https://github.com/###/### 

### Description:
When created Nova translation in resources/lang/vendor/nova, i noticed, than translation won`t work on resource label, singularLabel and any fields, but works on Search Field. On same setup without Jetstream everything works well.

Then I tried disable component by component of Jetstream and noticed, when commenting configurePermissions() method in JetstreamServiceProvider.php at boot() method - translations working well.

**Comment by crynobone** [comment]
Can you share reproducing code for this issue. I can't really follow what's breaking at the moment.

**Comment by crynobone** [comment]
Here a reproducing code and I wasn't able to reproduce the issue as expected: https://github.com/nova-issues/issue-3160/commit/8ad93ba87aac8d9dfd33395eae1b097080ccf153

> translation won`t work on resource label, singularLabel and any fields

For all there, you have to do it manually.
