### ISSUE TITLE
Unable to add MorphtoMany Relationship

### ISSUE THREAD

**Issue by jamespavett** [laravel/nova-issues#3161]
- Laravel Version: 8.21.0
- Nova Version: 3.19.1
- PHP Version: 7.4.3
- Database Driver & Version: MySQL 8.0.21
- Operating System and Version: Ubuntu 18
- Browser type and version: Chrome / Firefox

### Description:

I don't seem to be able to show a new MorphtoMany relationship in one of my resource classes.

I have added the following lines to the fields array of the resource class:

`MorphToMany::make('Shift', 'shifts', ShiftResource::class),`

However when trying to access the page I get the following errors:

![image](https://user-images.githubusercontent.com/10764464/104210060-5668cb00-542a-11eb-92ae-3c881221e968.png)

![image](https://user-images.githubusercontent.com/10764464/104210263-92039500-542a-11eb-8ab5-10a1d8f31e81.png)

I have tried this on numerous models / resources, and the same fault seems to occur within the Spatie Permissions package, so I assume this most be something to do with Nova itself?

**Comment by crynobone** [comment]
It seem you using `spatie/once` v3 on PHP 7.x environment. You might want to check whether you have different PHP version between web and cli and avoid using `--ignore-platform-reqs` during composer update.

**Comment by jamespavett** [comment]
Sorry for the delay in responding, but what you suggested worked perfectly, so that you for the input.

Does version 3 of spatial/once require PHP 8+ then?

**Comment by crynobone** [comment]
> Does version 3 of spatial/once require PHP 8+ then?

Yes. also you could follow the step suggested by @themsaid https://twitter.com/themsaid/status/1341715935741284353?s=20
