### ISSUE TITLE
Make Laravel\Nova\GlobalSearch obey resource sort callback

### ISSUE THREAD

**Issue by ovogel-wigital** [laravel/nova-issues#3162]
If I set a sorting strategy by ``Nova::sortResourcesBy()`` it only applies to the menu. It would be nice if the elements in the global search, would also be displayed in this order.

I added this feature myself in ``nova/src/GlobalSearch.php:86``, but I think this could be integrated in the standard installation.

Thanks.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
This seem to already implemented on the latest Laravel Nova.
