### ISSUE TITLE
JSON Code Formatting Broken

### ISSUE THREAD

**Issue by bdelamatre** [laravel/nova-issues#3164]
- Laravel Version: 7.29.3
- Nova Version: 3.19.1
- PHP Version: 7.4.x
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: Chrome, Latest
- Reproduction Repository: https://github.com/###/###

### Description:
After upgrading Laravel Nova ->json() fields are no longer formatted as JSON. These fields were properly formatted prior to upgrading Nova to the latest version and now just show as an unformatted string.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Have a Nova Admin resource and field of type Code with the ->json() method called on it. The field, which was previously pretty printed, is now just an unformatted string.

**Comment by crynobone** [comment]
Have you set the model attributes to cast as array, object or collection?

**Comment by bdelamatre** [comment]
I have not, because it's purposely stored as a string in the database. It just so happens that we would like that string formatted as JSON in the Nova Admin.  E.g. we do not generally want the field treated as JSON throughout our system.

**Comment by crynobone** [comment]
Unfortunately the requirement was made to fix another issue on Laravel Nova. See https://github.com/laravel/nova-issues/issues/2909

**Comment by bdelamatre** [comment]
I see. Did I miss a release note about this breaking change and is there an accepted workaround?

**Comment by crynobone** [comment]
It was added in Laravel Nova v3.12.0 <https://nova.laravel.com/releases/3.12.0> and the changes has been reflected on the documentation.

If you just want to display the code as JSON and not going to edit the content via Laravel Nova then you either can convert it to computed field or use `resolveUsing`:

```php
// Computed field

            Code::make('Meta Data', function ($value) {
                return json_decode($this->metadata, true);
            })->exceptOnForms()->json(),

// Resolve Using

            Code::make('Meta Data', 'metadata')
                ->resolveUsing(function ($value) {
                    return json_decode($value, true);
                })->exceptOnForms()->json(),
```

**Comment by bdelamatre** [comment]
I will give that a go, thanks!
