### ISSUE TITLE
TypeError: e.cards is undefined

### ISSUE THREAD

**Issue by JonathanDoelan** [laravel/nova-issues#3166]
- Laravel Version: 8.22.1
- Nova Version: 3.19.1
- PHP Version: 7.4.2

### Description:

On my dashboard I am getting the error `TypeError: e.cards is undefined`. It is the same problem as described [here](https://laracasts.com/discuss/channels/nova/laravel-nova-error-js-typeerror-ecards-is-undefined).
The error only occurs on the online server. On localhost it works.

Any ideas?

**Comment by crynobone** [comment]
Can you create a reproducing code on a fresh installation?

**Comment by JonathanDoelan** [comment]
@crynobone Sorry, not sure what you mean: a fresh laravel installation or a fresh nova installation?

**Comment by crynobone** [comment]
I seen the post before but I couldn't replicate the issue so my end. I would assume that you have some usage combination that could cause the issue. So can you share a repo with reproducing code that could demonstrate the issue?

**Comment by JonathanDoelan** [comment]
@crynobone I’ll try.

Some other problems that also occur, in the online version only:
The page <title> first renders correctly, but then switches to „undefined | undefined“
The pagination displays a „NaN“ when `'pagination' => 'links',` in config: `1-12 of NaN`

**Comment by JonathanDoelan** [comment]
@crynobone I cannot share a repo with reproducing code. Because I can’t test it on that (live!) server where the problem occurs.

### BUT …

I’ve found out that this bug occurs since nova version **3.12.0** — Version 3.11.1 and below works.

Here are my composer requirements:

"php": "^7.2.5",
"betterapp/laravel-db-encrypter": "dev-master",
"caouecs/laravel-lang": "^7.0",
**"coderello/laravel-nova-lang": "^1.4",**
**"digital-creative/collapsible-resource-manager": "^1.2",**
**"dmitrybubyakin/nova-medialibrary-field": "^3.2",**
**"emilianotisato/nova-tinymce": "^1.1",**
"fideloper/proxy": "^4.2",
"fruitcake/laravel-cors": "^1.0",
**"ghalwash/merq-laravel-nova-theme-responsive": "^1.1",**
**"gobrightspot/nova-detached-actions": "^1.0",**
"guzzlehttp/guzzle": "^7.0.1",
**"idf/nova-html-card": "^1.2",**
"intervention/image": "^2.5",
"laravel/framework": "^8.0",
"laravel/nova": "~3.0",
"laravel/tinker": "^2.0",
"laravelcollective/html": "^6.1",
**"optimistdigital/nova-menu-builder": "^4.1",
"optimistdigital/nova-settings": "^2.5",**
**"superlatif/nova-tag-input": "^1.4",**
**"techouse/intl-date-time": "^1.6",**
**"vyuldashev/nova-permission": "^2.9",
"whitecube/nova-flexible-content": "^0.2.6"**

Does this help you?

**Comment by crynobone** [comment]
> Does this help you?

You could try removing nova dependency one by one to see if that's the cause of the problem.

**Comment by JonathanDoelan** [comment]
@crynobone I removed the dependencies one by one like you’ve suggested, but I’m always getting the same error!

Did it with these packages:

"digital-creative/collapsible-resource-manager": "^1.2",
"dmitrybubyakin/nova-medialibrary-field": "^3.2",
"emilianotisato/nova-tinymce": "^1.1",
"ghalwash/merq-laravel-nova-theme-responsive": "^1.1",
"gobrightspot/nova-detached-actions": "^1.0",
"idf/nova-html-card": "^1.2",
"optimistdigital/nova-menu-builder": "^4.1",
"optimistdigital/nova-settings": "^2.5",
"superlatif/nova-tag-input": "^1.4",
"techouse/intl-date-time": "^1.6",
"vyuldashev/nova-permission": "^2.9",
"whitecube/nova-flexible-content": "^0.2.6"

I’ve even tried to delete all the nova resources and other files in App\Nova … but the same error appears all the time: I’m not able to display cards, the page <title> is `undefined` and pagination also doesn’t work. :)

### Here is the full error:

TypeError: e.cards is undefined
render https://example.com/vendor/nova/app.js?id=8a75eb6da95381e6f76b:1
_render https://example.com/vendor/nova/vendor.js?id=18c9503e0001d6fac7dd:1
mount https://example.com/vendor/nova/vendor.js?id=18c9503e0001d6fac7dd:1
get https://example.com/vendor/nova/vendor.js?id=18c9503e0001d6fac7dd:1
run https://example.com/vendor/nova/vendor.js?id=18c9503e0001d6fac7dd:1
fn https://example.com/vendor/nova/vendor.js?id=18c9503e0001d6fac7dd:1
ee https://example.com/vendor/nova/vendor.js?id=18c9503e0001d6fac7dd:1
Gt https://example.com/vendor/nova/vendor.js?id=18c9503e0001d6fac7dd:1
Xt https://example.com/vendor/nova/vendor.js?id=18c9503e0001d6fac7dd:1
Ft https://example.com/vendor/nova/vendor.js?id=18c9503e0001d6fac7dd:1
Ht https://example.com/vendor/nova/vendor.js?id=18c9503e0001d6fac7dd:1
_render https://example.com/vendor/nova/vendor.js?id=18c9503e0001d6fac7dd:1
mount https://example.com/vendor/nova/vendor.js?id=18c9503e0001d6fac7dd:1
get https://example.com/vendor/nova/vendor.js?id=18c9503e0001d6fac7dd:1
run https://example.com/vendor/nova/vendor.js?id=18c9503e0001d6fac7dd:1
fn https://example.com/vendor/nova/vendor.js?id=18c9503e0001d6fac7dd:1
ee https://example.com/vendor/nova/vendor.js?id=18c9503e0001d6fac7dd:1
Gt https://example.com/vendor/nova/vendor.js?id=18c9503e0001d6fac7dd:1

### Conclusion

Because of that, I’m convinced that these are problems with nova and the shared hosting provider of my client!
Please, try to reproduce it by installing nova on a shared hosting server!

Why does it work with version 3.11.1 and below?

**Comment by crynobone** [comment]
> Why does it work with version 3.11.1 and below?

It could be related to assets changes in 3.12.0, if the deployment was done correctly this should work fine. However I'm not able to help without getting enough information.

**Comment by JonathanDoelan** [comment]
@crynobone I’ve really tried everything to get it working now. I do not have any further idea.

It would be nice if you could try it out on a shared hosting, to see if you can find the bug.
To reproduce, simply install laravel + nova … that’s all to reproduce the bug … I’ve tried it several times now.

It must be in nova since >= 3.12.0

I’ve also discovered that the pagination bug occurs since >= 3.18.0 [see](https://github.com/laravel/nova-issues/issues/3166#issuecomment-760147262)

For now I will roll back to 3.11.1 … but well … 

:(

**Comment by JonathanDoelan** [comment]
They’ve found a solution: [https://laracasts.com/discuss/channels/nova/laravel-nova-error-js-typeerror-ecards-is-undefined](https://laracasts.com/discuss/channels/nova/laravel-nova-error-js-typeerror-ecards-is-undefined)
