### ISSUE TITLE
BelongsTo searchable field withSubtitles() not including subtitle() in search result

### ISSUE THREAD

**Issue by bdelamatre** [laravel/nova-issues#3168]
- Laravel Version: 7.29.3
- Nova Version: 3.19.1
- PHP Version: 7.4.x
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:

Possibly related to https://github.com/laravel/nova-issues/issues/2736

When defining a BelongsTo field and chaining both the ->searchable() and ->withSubtitles() method on that field, subtitles aren't included in the search results. The subtitle is confirmed to work via the global search.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Example field configuration on resource:

  BelongsTo::make('Contact', 'contact', Contact::class)
      ->sortable()
      ->searchable()
      ->withSubtitles(),

Search field works as expected, except the subtitle isn't included in the result.

**Comment by crynobone** [comment]
Unable to replicate with latest code.

![image](https://user-images.githubusercontent.com/172966/104667489-2b73c500-5711-11eb-878e-7d6c8b9f2bda.png)

**Comment by bdelamatre** [comment]
Later then the 3.19.1 release? I don't see an upgrade available.

Here I can see on global search when searching for a Contact that the subtitle() is returned (subtitle is an e-mail address):
<img width="969" alt="withsubtitles_1" src="https://user-images.githubusercontent.com/3412927/104737372-25caaf00-5712-11eb-8edf-5d40173583b5.png">

Here is the field configuration on my form for selecting a searchable contact:
<img width="577" alt="withsubtitles_2" src="https://user-images.githubusercontent.com/3412927/104737763-ac7f8c00-5712-11eb-9e98-10969a81d001.png">

Here is the behavior on the searchable BelongsTo field, with no subtitle() (i.e. e-mail address) shown:
<img width="968" alt="withsubtitles_3" src="https://user-images.githubusercontent.com/3412927/104738080-1009b980-5713-11eb-91c9-73d0c73e7457.png">

**Comment by crynobone** [comment]
You can check the reproducing code <https://github.com/nova-issues/issue-3168/commit/5d594035de5b2a01fc31e14f359a7b79bc9c92e2>

![image](https://user-images.githubusercontent.com/172966/104739783-1b47fe00-5782-11eb-9712-c80448352448.png)
![image](https://user-images.githubusercontent.com/172966/104739816-23a03900-5782-11eb-8472-5e34a4fcff85.png)

**Comment by crynobone** [comment]
It seem like you're using an outdated `form-belongs-to-field`, which is possible if you require Nova Packages that override the component: https://github.com/search?q=%22form-belongs-to-field%22&type=code

**Comment by bdelamatre** [comment]
I have searched the entire project source (including vendors) and only see references to `form-belongs-to-field` in the nova assets. Specifically:

private/nova/resources/js/fields.js
private/nova/public/app.js
private/public/vendor/nova/app.js
public/vendor/nova/app.js

I examined private/nova/resources/js/fields.js which appears to reference private/nova/resources/js/components/Form/BelongsToField.vue which matches what was downloaded in 3.19.1

**Comment by bdelamatre** [comment]
Okay, I have this issue resolved. The issue is, simply put:

`php artisan nova:publish` doesn't place it's resources in the application's public.path, but rather in ./public. I am not sure if there is a way to make `nova:publish` aware of the actual public directory, but the workaround for us is to manually copy and paste ./public/vendor/nova into the actual public location after running the publish command.
