### ISSUE TITLE
nova:resourcetool adds over 1000 npm dependencies in it's folder

### ISSUE THREAD

**Issue by AforDesign** [laravel/nova-issues#3169]
- Laravel Version: 7.30.2
- Nova Version: 3.19.1
- PHP Version: 7.4.1
- Database Driver & Version: MySQL5.7.26
- Operating System and Version: MacOS 10.14.6

### Description:

I want to add a simple button to the resource detail page with a link to view the resource/model page on the frontend.
Apparently, I'll need to make a resource-tool for this.
But when I make one and follow the steps, it creates a huge node_modules folder in the component with 1639 ! packages, 80MB in size.

Clearly, this can't be right... right?

Most of the packages are allready located in the main node_modules folder of laravel

### Detailed steps to reproduce the issue on a fresh Nova installation:
$ php artisan nova:resource-tool a4d/resource-frontend
$ y
$ y
$ y

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by AforDesign** [comment]
Hi David, I see you closed this issue.

Does it mean this behaviour is intentional?
It really occurs to me it's a bug.

I'm not asking for help on how to create a resource-tool. 
Although a complete example in the documentation would be extremely helpful.

**Comment by crynobone** [comment]
Yes it is intentional, `node_modules` is only required locally to compile the assets and are not required to be pushed to production. You are also modify the requirement based on your preferred usage.

**Comment by AforDesign** [comment]
> Yes it is intentional, `node_modules` is only required locally to compile the assets and are not required to be pushed to production. You are also modify the requirement based on your preferred usage.

Thanks, crynobone.

I'm just not very comfortable with this whole dependency mess.
Adding hundreds of packages over and over again for just a few lines of code just feels so incredibly inefficient. And also totally insecure to depend on each of them. 
It's a very weak chain imho.
But who am I to question these proven techniques?
