### ISSUE TITLE
BelongTo broken with 1.0.8 update (title changed)

### ISSUE THREAD

**Issue by Jam0r85** [laravel/nova-issues#317]
Using BelongsTo gives me the following error when creating/updating..

```
Call to undefined method Laravel\Nova\Fields\BelongsTo::buildAttachableQuery()"

file
:
"/Users/james/code/steve-morris/nova/src/Http/Controllers/AttachableController.php"
line
:
29
```

AttachableController differences

1.0.8
```
        $field = $request->newResource()
                    ->availableFields($request)
                    ->firstWhere('resourceName', $request->field);
```

1.0.7
```
        $field = $request->newResource()
                    ->availableFields($request)
                    ->firstWhere('attribute', $request->field);
```

**Comment by bradenkeith** [comment]
Can you post how your BelongToMany field is defined? The code changes you mentioned were to patch a workaround that was required for multi word attributes.

**Comment by Jam0r85** [comment]
Model

```
    /**
     * A team can have many staff members.
     */
    public function users()
    {
        return $this->belongsToMany(User::class)
                    ->withPivot(['role','position','brief']);
    }
```

Nova Resource
```
            BelongsToMany::make('Users')->fields(new TeamUserPivotFields)
```

PivotFields
```
    public function __invoke()
    {
        return [
            Text::make('Position'),

            Select::make('Role')
                ->options([
                    'administrator' => 'Admin',
                    'manager' => 'Manager',
                    'clerical' => 'Clerical'
                ]),

            Trix::make('Brief')
                ->help('Displayed on public team page.')
        ];
    }
```

**Comment by RicardoRamirezR** [comment]
Here is working well.

One curiosity in the error:
```php
Call to undefined method Laravel\Nova\Fields\BelongsTo::buildAttachableQuery()"
```
Shows ```BelongsTo``` not ```BelongsToMany ```

**Comment by Jam0r85** [comment]
Ok there is a different error here then.

Removing the BelongsTo on my Nova Resource and this works but I still get an error with it added.

Nova Resource
```
            BelongsTo::make('User', 'Owner')->searchable(),
            BelongsToMany::make('Users')->fields(new TeamUserPivotFields)
```

Model
```
    /**
     * A team belongs to an owner.
     */
    public function owner()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * A team can have many staff members.
     */
    public function users()
    {
        return $this->belongsToMany(User::class)
                    ->withPivot(['role','position','brief']);
    }
```

So is there a different error here?

**Comment by RicardoRamirezR** [comment]
I've checked the BelongsTo field in my model and is working here.

**Comment by bradenkeith** [comment]
BelongsTo is working for me utilizing your code as well
```
BelongsTo::make('User', 'Owner')->searchable(),
```
```
/**
* A team belongs to an owner.
*/
public function owner()
{
	return $this->belongsTo(User::class);
}
```

**Comment by Jam0r85** [comment]
What on earth.. I still get the error.

Only when removing the BelongsTo from the Nova resource does the BelongsToMany work fine.

I'll investigate further and close this.

**Comment by Jam0r85** [comment]
OK had a fiddle with this.

BelongsToMany refuses to work if the BelongsTo field comes before it, that's when I get the BelongsTo error.

However if I move it after the BelongsToMany, then it works fine?

Works
```
            BelongsToMany::make('Users')->fields(new TeamUserPivotFields),
            BelongsTo::make('User', 'owner')->searchable(),
```

Doesn't work
```
            BelongsTo::make('User', 'owner')->searchable(),
            BelongsToMany::make('Users')->fields(new TeamUserPivotFields),
```

Can someone else confirm this?

I'm using UUID's for these records.

**Comment by RicardoRamirezR** [comment]
@Jam0r85 not using UUID's here. I've added a ```BelongsTo``` to a resource that has a ```BelongsToMany``` and it worked.

**Comment by davidhemphill** [comment]
ok, what's the consensus here. What do I need to do on a fresh installation to see this issue? Have a private repo I could pull down?

**Comment by abordage** [comment]
> Works
> 
> ```
>             BelongsToMany::make('Users')->fields(new TeamUserPivotFields),
>             BelongsTo::make('User', 'owner')->searchable(),
> ```
> 
> Doesn't work
> 
> ```
>             BelongsTo::make('User', 'owner')->searchable(),
>             BelongsToMany::make('Users')->fields(new TeamUserPivotFields),
> ```
> 
> Can someone else confirm this?

I have the same problem. If `BelongsTo` is used below `BelongsToMany` - works

**Comment by telkins** [comment]
Could this be related to #425 ...?

**Comment by telkins** [comment]
Just back from commenting on #425 .  I've been having the same problem and because of this issue I've been able to get it to work, it seems, by changing the order from `BelongsTo`/`BelongsToMany` to `BelongsToMany`/`BelongsTo`.

You can check out the other issue for a bit more information.

I'm curious to hear, btw, for those that say that it's working....are they using the same Nova resource for both `BelongsTo*` fields...?

**Comment by telkins** [comment]
@RicardoRamirezR Thanks for the feedback.  Would you mind posting your code?

I ask this because it's not clear to me that those fields you're referring to are for the same Nova resource.  That is, are all three fields ("three `BelongsTo` and one `BelongsToMany`") for the **same** Nova resource...`App\Nova\User`, for example....?

I'm not 100% sure, but I don't think people are having problems with mixing `BelongsTo` and `BelongsToMany` fields in any particular order so long as they each deal with **different** Nova resources.  It's only when those Nova resources are the **same** that the ordering seems to become an issue.  At least, that's what it's looking like....

**Comment by shirshak55** [comment]
So weird adding on top of fields array get it fixed :(

**Comment by jankremlacek** [comment]
@RicardoRamirezR 

same here, BelongsTo and BelongsToMany (_in this order_) pointing to the same Resource causes the error. Opposite order in the field list works.

@davidhemphill, here is a repo showing it: https://github.com/jankremlacek/belongsto_vs_belongstomany_same_resource

it's fresh Laravel and Nova install (_1st commit_), and:

- modes, resources, and respective migrations: broken order: https://github.com/jankremlacek/belongsto_vs_belongstomany_same_resource/commit/2361b8b0a358735322972e2d4312f8acdcee2ed6

- working order: https://github.com/jankremlacek/belongsto_vs_belongstomany_same_resource/commit/7c1d5fa07029e0d534cd61a401aceee91a85c33e

Hope it will help.

**Comment by jankremlacek** [comment]
@RicardoRamirezR 

same here, BelongsTo and BelongsToMany (in this order) pointing to the same Resource causes the error. Opposite order in the field list works.

@davidhemphill, here is a repo showing it: https://github.com/jankremlacek/belongsto_vs_belongstomany_same_resource

it's fresh Laravel 5.7 and Nova 1.2.0 install (Nova itself is not included, so please copy it into /ova), and:

modes, resources, and respective migrations: broken order: https://github.com/jankremlacek/belongsto_vs_belongstomany_same_resource/commit/0c646882e367ef388df09dba132d07910d667fb1

working order: https://github.com/jankremlacek/belongsto_vs_belongstomany_same_resource/commit/a549a29ca00f49b7446fa4616cc7db5c8403600e

Hope it will help.

**Comment by jankremlacek** [comment]
@RicardoRamirezR, @davidhemphill, sorry for the previous deleted message, forgot to hide Nova from the Repo 🙈
