### ISSUE TITLE
Creating a new theme results in a TypeError within ThemeServiceProvider

### ISSUE THREAD

**Issue by Helmi** [laravel/nova-issues#3173]
- Laravel Version: 8.22.1
- Nova Version: 3.19.1
- PHP Version: 8.0.1
- Using Sail

### Description:

Creating a new theme in Nova using 

```
sail php artisan nova:theme example/my-theme
```

results in a TypeError 

```
Example\MyTheme\ThemeServiceProvider::Example\MyTheme\{closure}(): Argument #1 ($event) must be of type Laravel\Nova\Events\ServingNova, Laravel\Nova\Events\NovaServiceProviderRegistered given, called in /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php on line 391
```
### Detailed steps to reproduce the issue on a fresh Nova installation:

- create a theme using the documented command nova:theme
- (optional: publish the theme)

**Comment by crynobone** [comment]
Will submit a PR soon, in the meantime you should be able to update  `Example\MyTheme\ThemeServiceProvider`:

```php
Nova::booted(function (ServingNova $event) {
```

changed to 


```php
Nova::booted(function ($event) {
```
