### ISSUE TITLE
Uncaught ReferenceError: CreateNova is not defined

### ISSUE THREAD

**Issue by frddl** [laravel/nova-issues#3174]
- Laravel Version: 8.21.0
- Nova Version: 3.18.0
- PHP Version: 7.3

![image](https://user-images.githubusercontent.com/16150999/104819625-27968e80-5848-11eb-98b0-7a711ec0c1bb.png)

### Description:
I get this right at /admin route, which is my nova path.
Tried to `npm install` and `npm run dev` inside nova folder, then deleting `public/vendor/nova` and publishing nova assets once again. Didn't help.

**Comment by crynobone** [comment]
Can you provide a reproducing step? Because the default installation process should just be `php artisan nova:publish`.

**Comment by frddl** [comment]
> Can you provide a reproducing step? Because the default installation process should just be `php artisan nova:publish`.

Unfortunately I cannot, because this was after I mirgated the project from my local machine to the server. Issue disappeared after reinstalling nova.

**Comment by crynobone** [comment]
Closing this for now as not reproducible (it could been just a bad deployment). However feel free to recreate a new issue if anyone can come out with more details.

**Comment by ugurdnlr** [comment]
is there any update ?

**Comment by ahmed-tahoon** [comment]
any update


> is there any update ?

**Comment by muhzak** [comment]
Also awaiting update.
