### ISSUE TITLE
Validating arrays

### ISSUE THREAD

**Issue by MatanYadaev** [laravel/nova-issues#3175]
How should I validate arrays with Laravel Nova?

An example as it used in a FormRequest:
```php
public function rules(): array
{
    return [
        'address' => 'required|array',
        'address.name' => 'required|string',
        'address.geo_point' => 'required|array',
        'address.geo_point.latitude' => 'required|numeric',
        'address.geo_point.longitude' => 'required|numeric',
    ];
}
```

**Comment by navidnadali** [comment]
Hey! That looks like documentation from laravel maybe? Although same validation system is used, you'd usually setup your validation rules when you define them within the resource. Like this:

```
Text::make('Name')
    ->sortable()
    ->rules('required', 'max:255'),
```

See here for more details: https://nova.laravel.com/docs/3.0/resources/validation.html

**Comment by crynobone** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or other support channel listed at <https://nova.laravel.com/docs/3.0/support.html#support-questions>

**Comment by MatanYadaev** [comment]
@crynobone It is a feature request, not a real question because this feature isn't supported.
Laravel Nova isn't able to support array validation today.

The only workaround is to use the `afterValidation` method.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
