### ISSUE TITLE
Pass `NovaRequest` instead of `Request` in `fields` method

### ISSUE THREAD

**Issue by MatanYadaev** [laravel/nova-issues#3176]
Currently `Resource@fields` receives `Illuminate\Http\Request`, it will be better if it will receive `Laravel\Nova\Http\Requests\NovaRequest`. (if it's possible)

Before:
```php
public function fields(Request $request): array
{
  //
}
```

After:
```php
public function fields(NovaRequest $request): array
{
  //
}
```

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
