### ISSUE TITLE
Extra tr>td displayed for read-only resources displayed as sub-resource

### ISSUE THREAD

**Issue by lptn** [laravel/nova-issues#3179]
- Laravel Version: 8.22.1
- Nova Version: 3.19.1
- PHP Version: 7.4.4

### Description:
first tbody>tr>td is reserved for checkboxes, but for read-only resources we don't display them on tbody, but still display  an empty `tr` in thead. Hide/display conditions should be identical
![image](https://user-images.githubusercontent.com/5278175/104954131-bfc37d80-59d8-11eb-8e2d-960467c3fac3.png)

**Comment by crynobone** [comment]
Just to verify, how did you setup the read-only resource?

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/104985368-bfb09580-5a4b-11eb-9e89-44f3ab8def39.png)

I didn't manage to replicate the issue, there might be something missing on my end or it could be possible you have any 3rd party packages that could override `ResourceTable.vue` which could cause the issue.

**Comment by lptn** [comment]
@crynobone
>Just to verify, how did you setup the read-only resource?
 
I use this trait to make a resource read-only and delete:
```php
/** @see https://nova.laravel.com/docs/2.0/resources/authorization.html#policies */
trait ReadOnlyAccess
{
    /** @see \Laravel\Nova\Authorizable::authorizedToCreate() */
    public static function authorizedToCreate(Request $request): bool
    {
        return false;
    }

    /** @see \Laravel\Nova\Authorizable::authorizedToUpdate() */
    public function authorizedToUpdate(Request $request): bool
    {
        return false;
    }

    /** @see \Laravel\Nova\Authorizable::authorizedToDelete() */
    public function authorizedToDelete(Request $request): bool
    {
        return false;
    }

    /** @see \Laravel\Nova\Authorizable::authorizedToForceDelete() */
    public function authorizedToForceDelete(Request $request): bool
    {
        return false;
    }

    /** @see \Laravel\Nova\Authorizable::authorizedToRestore() */
    public function authorizedToRestore(Request $request): bool
    {
        return false;
    }
}
```

is there a better way to Hide "Create Resource" button and other controls to  modify a resource?

**Comment by crynobone** [comment]
Noted, Just checking to make sure I didn't missed anything.

**Comment by blhylton** [comment]
This issue also appears to be happening if you use `HasOne` even if you have permission to write.

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/105128084-3f5a6500-5b1d-11eb-97e7-771122621b8e.png)

I don't get the screenshot and above trait, the screenshot clearly shows edit button is visible but code for `authorizedToUpdate()` return `false`.

Also, I attempted to replicate the issue unable to replicate the issue even using the exact trait. See https://github.com/nova-issues/issue-3179/commit/4dafbac1584b4090460d2f3b50d005028f9e353c

![image](https://user-images.githubusercontent.com/172966/105128289-b263db80-5b1d-11eb-8b10-c27d39442116.png)

Unable to proceed right now, @lptn can you review https://github.com/nova-issues/issue-3179 and submit the required step to make it fails.

------------

@blhylton Please create another issue for your case, complete with reproducing code.

**Comment by jkudish** [comment]
I'm having the same issue, both in 3.19.1 and 3.20

**Comment by crynobone** [comment]
> So I'm thinking one of the third party packages I use might be the culprit. 

You could search under `vendor` and find if any packages does the following (replace Nova resource table or resource table row:

```js
Vue.component('resource-table', ...)
Vue.component('resource-table-row', ...)
```

**Comment by jkudish** [comment]
@crynobone thanks that was a good tip. It appears https://github.com/optimistdigital/nova-sortable/ is the culprit

**Comment by jkudish** [comment]
Reported it here: https://github.com/optimistdigital/nova-sortable/issues/73

**Comment by blhylton** [comment]
Good catch @jkudish, using the same extension in my project. I had a feeling that might be it once third-party packages came up, but hadn't had a chance to go back and verify.

**Comment by crynobone** [comment]
Closing this issue and if anything related to `nova-sortable` please continue at optimistdigital/nova-sortable#73
