### ISSUE TITLE
BelongToMany attach dropdown list showing already attached items

### ISSUE THREAD

**Issue by jorgv** [laravel/nova-issues#318]
When using BelongToMany field, it works correctly but the dropdown list still shows all the possible options even the ones already attached.

Is there a way to update the list to show only the items that haven't been attached?

Steps to reproduce
For example User Role,

User -> Attach Role -> Shows the whole list Administrator, Manager, User
Attach Administrator Role to User 1
Going again to Attach Role Administrator option still there and if I select it will throw an exception

![image](https://user-images.githubusercontent.com/32174909/44796964-690e3c80-abae-11e8-9d28-7e15c15f1fca.png)

```
{message: "The given data was invalid.", errors: {roles: ["This role is already attached."]}}
errors
:
{roles: ["This role is already attached."]}
message
:
"The given data was invalid."
```

That could be fine for really small lists but for the large list would be impossible to remember which items have been attached. 

How can I filter the list to show only the items that have not been attached?

thanks

**Comment by loren138** [comment]
It is possible to (sort of) do this with an authorization Policy on attach.  Unfortunately, authorization to attach also includes authorization to edit.  Not a big deal if you don't have any pivot columns, but problematic if you do....

```
<?php

namespace App\Policies;

use App\Product;
use App\ProductSubProduct;
use App\SubProduct;
use App\User;
use Illuminate\Auth\Access\HandlesAuthorization;

class ProductPolicy
{
    use HandlesAuthorization;

    /**
     * Create a new policy instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    public function view()
    {
        return true;
    }

    public function viewAny()
    {
        return true;
    }

    public function create()
    {
        return true;
    }

    public function update()
    {
        return true;
    }

    public function delete()
    {
        return true;
    }

    public function attachSubProduct(User $user, Product $product, SubProduct $subProduct)
    {
        return !ProductSubProduct::query()->where('ProductID', $product->ID)->where('SubProductId',
            $subProduct->ID)->exists();
    }

    public function detachSubProduct(User $user, Product $product, SubProduct $subProduct)
    {
        return true;
    }
}
```

**Comment by vineeth030** [comment]
This might help [Answer from Stackoverflow](https://stackoverflow.com/questions/53331599/laravel-nova-only-load-relationship-with-certain-property-in-form-dropdown)

**Comment by dlaytonjames** [comment]
Here's my solution
my layout is 

- Orgs have many Users and Many Teams
- Users have many Orgs and many Teams
- Teams have 1 Org and many Users
- A user can belong to an org without being in a team

This is how I populate the Nova attach user to team screen dropdown.

This method is on my Nova Team resource, hope it helps others, took me ages to work out.  Hope it's documented well enough to make sense.

```
    /**
     * $request is the nova request that contains the nova team resource you are on.
     * You use undocumented findResourceOrFail() to get the underlying team  
     * team being attached to.  That allows us to build a relatable query for
     * Users and filter out any that are already linked to the team but are
     * also a member of the organisation the team belongs to.
     *
     * $query is the Eloquent query to select the user models to populate
     * the attach user to team list.
     *
     * This shows users that belong to the team organisation and who
     * are not already attached to the team.
     *
     * @param NovaRequest $request
     * @param             $query
     *
     * @return mixed
     */
    public static function relatableUsers(NovaRequest $request, $query)
    {
        // find the team we are attaching to
        $team = $request->findResourceOrFail();

        // Find users not attached to team but is in org
        // User whereHas org membership to match the team org
        // User whereDoesntHave link (attached) to the team
        return $query->with('Orgs')
              ->whereHas('Orgs', function ($query) use ($team) {
                  $query->where('org_id', $team->org_id);
                })
              ->whereDoesntHave('Teams', function ($query) use ($team) {
                  $query->where('team_id', $team->id);
                });
    }
```

**Comment by phuclh** [comment]
Here is my solution:

```
public static function relatableQuery(NovaRequest $request, $query)
    {
        // Get the current inventory.
        $resourceId = $request->route()->parameter('resourceId');

        // Get the array of product ids that already attached.
        $inventory = app(self::$model)::find($resourceId);
        $attachedItems = $inventory->products()->get()->pluck('id');

        return $query->whereNotIn('id', $attachedItems);
    }
```

**Comment by phuclh** [comment]
@jorgv how can you exclude that code from edit action? Because when you attach a user to all roles, you cannot edit that anymore.

**Comment by davidhemphill** [comment]
This is not a bug. There are use cases where one should be able to add an attachable relation multiple times.

**Comment by royduin** [comment]
What I've used:
```
public static function relatableQuestions(NovaRequest $request, $query)
{
    return $query->whereNotIn('id', $request->findModelOrFail()->questions()->pluck('id'));
}
```
Keep in mind you've to specify this on both sides and change "questions" to your relationship name.

**Comment by jbvios** [comment]
Any updates ? Did you solve it @jorgv  ?

**Comment by MelchiorKokernoot** [comment]
@royduin Thanks Roy! Works like a charm. I did have to change the `instanceof BelongsToMany` to the FQN of the relation since the Nova\BelongsToMany was used by default as it was already imported. I also had to change the pluck('id','id') column as it was ambiguous.  
Kind regards, MelchiKork
