### ISSUE TITLE
Add `afterValidation` method to Actions

### ISSUE THREAD

**Issue by MatanYadaev** [laravel/nova-issues#3181]
Resources have `afterValidation` method, this way you can dynamically change the rules - Actions should have this method as well.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
The feature has been added to v3.21.0
