### ISSUE TITLE
Badge Field does not update from Action

### ISSUE THREAD

**Issue by jonasbrenig** [laravel/nova-issues#3185]
- Laravel Version:  8.11.2
- Nova Version: 3.16.3
- PHP Version: 7.4.11

### Description:
I use a badge field which is calculated on the fly.
If I run an action that would result in the badge field changing, the badge does not update.
Now if I navigate to a different part of Nova and return (without page reload), the badge field properly updates.

It seems like this could maybe easily fixed by emitting some "refetch-data"-event in the badge component?

I hope the description is not too broad.

Thanks for the help in advance.

**Comment by davidhemphill** [comment]
An event is already broadcast for metrics to refresh when actions are run, so it makes sense that the index views could do so as well. Care would need to be taken to ensure actions ran on relation index views, do not trigger refreshes in unrelated relation index views.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
