### ISSUE TITLE
Nova Install should not override the User.php by default

### ISSUE THREAD

**Issue by ludo237** [laravel/nova-issues#319]
As the title suggests if you have a `User.php` in your `app/Nova` folder the command `php artisan nova:install` will override that file. 

Maybe a `--force` or a silent check could improve the experience with this command

**Comment by RicardoRamirezR** [comment]
@ludo237 it also overrides ```config/nova.app```, ```app/Providers/NovaServiceProviders```.

But you *only* install once.

**Comment by ludo237** [comment]
@RicardoRamirezR yes but the command is still there, since it's an artisan command a `--force` parameter would be nice

**Comment by GuidoHendriks** [comment]
Doesn’t seem like that big of an issue. Just revert the changes if you screw up. 🙃

**Comment by RicardoRamirezR** [comment]
as @GuidoHendriks says: ```git checkout master -- app/Nova/User.php```
