### ISSUE TITLE
Grouping fields in 1 row

### ISSUE THREAD

**Issue by RomkaLTU** [laravel/nova-issues#3192]
Please provide instructions or make it possible to group fields in 1 row. Why on earth this doesn't implement with 3 major releases. 

Here is an example of what I'm trying to achieve. 

![142796029_3956494907775666_1765272113008278992_n](https://user-images.githubusercontent.com/10167743/105633431-2c1f0080-5e61-11eb-97dc-d52d70d0c2ee.png)

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
See https://novapackages.com/packages/codenco-dev/nova-grid-system

**Comment by davidhemphill** [comment]
Nova will likely never support this as multi-column forms have long been known in UX circles to confuse users.
