### ISSUE TITLE
Nova Custom Tool not setting Page Title

### ISSUE THREAD

**Issue by jamespavett** [laravel/nova-issues#3193]
- Laravel Version: 8.24.0
- Nova Version: 3.20
- PHP Version: 7.4.3
- Database Driver & Version: 8.0.21
- Operating System and Version: Ubuntu 18.04
- Browser type and version: Chrome 87

### Description:
When using a Custom Tool via Nova there is no way of setting a title for the page. For resources I believe it uses the Resource's group, however this does not seem to be the case for Custom Tools.

Just to include two examples, first for a resource which seems to display the page title as _ResourceGroup | AppName_

![image](https://user-images.githubusercontent.com/10764464/105709779-161b4980-5f0e-11eb-8ad1-cfa57121a504.png)

However for a Custom Tool, you only see the output as  _| AppName_ 

![image](https://user-images.githubusercontent.com/10764464/105709813-23d0cf00-5f0e-11eb-8189-b065e0fa2dba.png)

Potentially there may be way to override this, but I cannot see anything in the documentation, so this may just be an oversight?

### Detailed steps to reproduce the issue on a fresh Nova installation:

Attempt to create custom nova-component in fresh installation. View created tool title in browser.

**Comment by crynobone** [comment]
Vue components for Tool has access to all plugins registered under Nova including `vue-meta`, `portal-vue` and `v-tooltip`.

For example in the latest release, the `resources/js/components/Tool.vue` stub will contain a default page title as the following:

```js
export default {
  metaInfo() {
    return {
      title: 'PriceTracker',
    }
  }
}
```

Planning to submit this to documentation today.
