### ISSUE TITLE
Access .env variables

### ISSUE THREAD

**Issue by stephan-v** [laravel/nova-issues#3194]
Simple question. When creating a custom tool how do you access env variables like these inside your `Tool.vue` component?

```
process.env.MIX_MAPBOX_APP_ID
```

**Comment by anditsung** [comment]
You can add the config using withMeta on the field class

**Comment by stephan-v** [comment]
Do you have an example of this? Where am I suppose to add `withMeta` ? Since this is a tool I'm not using any fields.
