### ISSUE TITLE
Base table or view already exists: 1050 Table 'failed_jobs' already exists

### ISSUE THREAD

**Issue by whoacowboy** [laravel/nova-issues#3195]
- Laravel Version: 8.24
- Nova Version: v3.20.0
- PHP Version: #.#.#
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:
When installing Nova on an existing laravel app and DB I get the following error.

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'failed_jobs' already exists (SQL: create table `failed_jobs` (`id` bigint unsigned not null auto_increment primary key, `uuid` varchar(255) not null, `connection` text not null, `queue` text not null, `payload` longtext not null, `exception` longtext not null, `failed_at` timestamp default CURRENT_TIMESTAMP not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

**Comment by davidhemphill** [comment]
Nova doesn't ship with a migration file for a `failed_jobs` table. I'd look in your migrations folder and make sure there isn't an extra one, and that your database is starting fresh each time you migrate locally. 👍
