### ISSUE TITLE
Nova filter - listen to "clear-selected-filters" for custom filters

### ISSUE THREAD

**Issue by dorinniscu** [laravel/nova-issues#3196]
It would be helpful if we could reset the filters from a child (Ex: dependent filters)

If I change the country I would like to reset the children (county / city etc.).

Currently it is kind of recursive (need to update filter state for each child and generate _redirects / cancelled request error._)

```
this.$store.commit(`${this.resourceName}/updateFilterState`, {
    filterClass: this.filterKey,
    value: '',
})
```
It would be nice if we can listen for **@clear-selected-filters="clearSelectedFilters"** on the custom filters components inside **FilterMenu.vue**.

```
<!-- Custom Filters -->
<component
  v-for="filter in filters"
  :resource-name="resourceName"
  :key="filter.name"
  :filter-key="filter.class"
  :is="filter.component"
  :lens="lens"
  @input="$emit('filter-changed')"
  @change="$emit('filter-changed')"
  @clear-selected-filters="clearSelectedFilters"
/>
```

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
