### ISSUE TITLE
Ability auto generating Slug on editing resource

### ISSUE THREAD

**Issue by aghayeff** [laravel/nova-issues#3206]
Laravel Version: 7.0
Nova Version:3.20
PHP Version: 7.4

I wonder why slug is not generated automatically on editing resource? Sometimes, client retypes a new title with long character and wanna see new generated slug. Clicking Edit Link near slug field is good, but is not generated at all. 

Thanks!

**Comment by crynobone** [comment]
It's an expected behaviour at the moment, no plan to change.
