### ISSUE TITLE
Key value field: deleted first item in the list when updating

### ISSUE THREAD

**Issue by bezbeli** [laravel/nova-issues#3207]
- Laravel Version: 8.25.0
- Nova Version: 3.20.0
- PHP Version: 7.4.4
- Database Driver & Version: Ver 8.0.21 for osx10.15 on x86_64 (Homebrew)
- Operating System and Version: osx10.15 on x86_64
- Browser type and version: 88.0.4324.96 (Official Build) (x86_64)

### Description:

first item in the list gets deleted if key is set to 0 (zero), only when updating, creating it is not an issue, everything works as expected.

![Screen Shot 2021-01-30 at 1 14 51 PM](https://user-images.githubusercontent.com/860368/106356107-4fccc580-62fd-11eb-9fea-352930b2d2ef.png)

But when entry is updated, first item gets deleted

![Screen Shot 2021-01-30 at 1 15 17 PM](https://user-images.githubusercontent.com/860368/106356120-6a06a380-62fd-11eb-8613-11c1bcf068d3.png)

**Comment by crynobone** [comment]
This has been fixed and released in v3.21.0
