### ISSUE TITLE
Ability to redirect after resource deletion

### ISSUE THREAD

**Issue by rela589n** [laravel/nova-issues#3208]
## Problem

Hi, I faced the problem when I need to redirect to parent resource on child deletion. But how can I get parent resource ID if I don't have access to resource deleted.

I mean `redirectAfterDelete` is static (can't do `$this->resource->parentRelation->id`).

```php
public static function redirectAfterDelete(NovaRequest $request)
```

The request doesn't contain enough information.

## Solution:

In `\Laravel\Nova\Http\Controllers\ResourceDestroyController::handle` on line 45 pass model which was deleted.

![image](https://user-images.githubusercontent.com/41589422/106392115-15485300-63f9-11eb-9c6e-55db5cfb96b4.png)

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
