### ISSUE TITLE
Prevent users from updating pivot table fields

### ISSUE THREAD

**Issue by BengtHagemeister** [laravel/nova-issues#321]
I have a pivot table role_user with an additional field notes. I want to prevent through a policy that a user can edit this notes. I cannot find an option for that. 

The convention used to prevent attaching models is not working for updating.
    
    public function attachUser()
    {
      working
    }

    public function updateUser()
    {
       not working
    }

**Comment by chrisbjr** [comment]
I'm having the same problem.

I have a `BelongsToMany` relationship between models/resources but I don't want users to be able to create/edit/update this.

I tried creating a policy by creating a model for the pivot (extending the `Pivot` as well) but the policy does not seem to have any effect.

Any ideas on how to achieve this?

**Comment by dkulyk** [comment]
Policy applied for resources. If you need permissions for the pivot use HasManyThrough relation and a separate resource for it.

**Comment by BengtHagemeister** [comment]
@dkulyk Can you maybe give an example? 

I tried to use a separate model for it (as @chrisbjr did) but it doesn't seem to work for me either.

**Comment by BengtHagemeister** [comment]
@dkulyk Thank you for your description but this is more a workaround. It should be possible to add policies to pivot tables without changing the whole relationship.

**Comment by davidhemphill** [comment]
@dkulyk's answer if the recommended approach here.
