### ISSUE TITLE
Can't run action from lens if record is out of resources indexQuery

### ISSUE THREAD

**Issue by NowakAdmin** [laravel/nova-issues#3210]
- Laravel Version: 7.30.0
- Nova Version: 3.17.0 & 3.20.0 
- PHP Version: 7.4.13
- Database Driver & Version: mariaDB
- Operating System and Version: Debian 10
- Browser type and version: Chrome

### Description:
When resource have custom indexQuery that list not all records of resource if i use lens that shows all records - can't run action on that record.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Create Resource, add custom indexQuery
im my code it is:
`public static function indexQuery(NovaRequest $request, $query)
    {
            return $query
                ->where('user_id', $request->user()->id)
                ->get();
    }` 

add action to that resource 

add lens to that resource with custom Query
my example:
`public static function query(LensRequest $request, $query)
    {
        return $request->withOrdering($request->withFilters(
            $query->orderBy('ID', 'asc')
        ));
    }`

Running action from lens will fail. - You'r not authorized to run this action

changing in main resource indexQuery to:
`public static function indexQuery(NovaRequest $request, $query)
    {
        if( auth()->user()->role == 'admin') return $query->get();
        else{
            return $query
                ->where('user_id', $request->user()->id)
                ->get();
        }
    }`
Bring back ability to run action on lens.

It's not connected to Update Policy (its granted anyway). I saw topics connected to missing update policy, some ppl there said they have it and still not get out of issue - probably they have like me custom indexQuery.

**Comment by crynobone** [comment]
The description very vague, I would definitely think you need to provide full reproducing code so we can look at it to properly debug the issue. Action using `indexQuery()` is the expected behavior and action needs to have the ability to update the resource before running the action.
