### ISSUE TITLE
Fix timezone calculation in Value Metrics

### ISSUE THREAD

**Issue by cwilby** [laravel/nova-issues#3211]
- Laravel Version: 8.0.25
- Nova Version: 3.0.20
- PHP Version: 7.4.2
- Database Driver & Version: Postgres 10
- Operating System and Version: Linux/Mac
- Browser type and version: Chrome

### Description:

(Tagging @crynobone from https://github.com/laravel/nova-issues/issues/2044#issuecomment-770356440)

When calculating metrics relating to time (e.g. "Users in the last 24 hours", Nova uses the users browser timezone for the start/end dates used in the query when it should use `APP_TIMEZONE` for these dates.  By not doing this, the UI displays  under/overlapping data in the metric. 

### Example

Say we want to calculate "User signups in the last 24 hours".  It is `2021-01-31 20:00:00` in UTC, and the following users signed up in the last 24 hours, in a database where `APP_TIMEZONE` is UTC.

```js
[
    { id: 1, created_at: '2021-01-30 19:00:00' }, // 25 hours ago
    { id: 2, created_at: '2021-01-30 20:00:00' }, // 24 hours ago
    { id: 3, created_at: '2021-01-30 21:00:00' }, // 23 hours ago
    { id: 4, created_at: '2021-01-30 22:00:00' }, // 22 hours ago
    ...
    { id: 25, created_at: '2021-01-31 19:00:00' }, // 1 hour ago
    { id: 26, created_at: '2021-01-31 20:00:00' }, // Now
]
```

Now let's say a user with a browser timezone of `America/Los_Angeles` opens this metric at this moment.  

Nova makes a request to `/nova-api/metrics/{metric}?timezone=America/Los_Angeles`, where it calculates start/end boundaries where `end` is the current time in `America/Los_Angeles`, and `start` is 24 hours prior, then _uses those dates to query the database, whose dates are stored in UTC._

The problem with this is that the start/end date and the dates in the database are in two different timezones, and will result in over/underlapping data.

When `$request->timezone` is `America/Los_Angeles` (-0800), the user gets 16 hours worth of data 8 hours late.

```php
$previousCount = with(clone $query)->whereBetween(
  'created_at',
  [
    "2021-01-29 20:00:00",    // 48 hours ago in PST
    "2021-01-30 20:00:00".    // 24 hours ago in PST
  ]
);

$currentCount = with(clone $query)->whereBetween(
  'created_at',
  [
    "2021-01-30 20:00:00",    // 24 hours ago in PST
    "2021-01-31 20:00:00".    // Now in PST
  ]
);
```

When `$request->timezone` is `Africa/Johannesburg` (+0200), the user gets 22 hours worth of data immediately.

```php
$previousCount = with(clone $query)->whereBetween(
  'created_at',
  [
    "2021-01-30 06:00:00",    // 48 hours ago in +0200
    "2021-01-31 06:00:00".    // 24 hours ago in +0200
  ]
);

$currentCount = with(clone $query)->whereBetween(
  'created_at',
  [
    "2021-01-31 06:00:00",    // 24 hours ago in +0200
    "2021-02-01 06:00:00".    // Now in +0200
  ]
);
```

I believe the solution is for the `start` and `end` dates passed to `whereBetween` to be in the server timezone, not the user's browser timezone.  

The following gist replaces `vendor/laravel/nova/Metrics/Value.php` with the solution applied, and for me it has been working in multiple timezones.  https://gist.github.com/cwilby/6a63eb44bf2e89759410b640c757035f

**Comment by crynobone** [comment]
Thank @cwilby, I'll try to convert the above example to tests today so we can figure out the best solution.

**Comment by crynobone** [comment]
This has been fixed and released in v3.21.0

**Comment by sirhB** [comment]
I am on 3.26 and still having this issue.

**Comment by crynobone** [comment]
@sirhB create a new issue with full description on what the current and expected behavior.
