### ISSUE TITLE
Separate displayUsing on Index and Detail view

### ISSUE THREAD

**Issue by ambengers** [laravel/nova-issues#3214]
We have this use-case that a Ticket model title can be more than 50 characters long. 

What we'd like to do is to limit the number of characters on the Index view so the column does not look like its occupying the entire table, but show the full title on the Detail view so that our team mates can validate the title. 

So, maybe we can also have `displayOnIndexUsing($callable)` and `displayOnDetailsUsing($callable)` methods?

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
You should be able to utilize `$request` since it an instance of `Laravel\Nova\Http\Requests\NovaRequest`.


```php
Text::make('Name')->displayUsing(function ($name) use ($request) {
    if ($request->isResourceIndexRequest()) {
        return Str::upper($name);
    }
    
    return $name;
}),
```

**Comment by ambengers** [comment]
@crynobone This is a very useful feature that I didn't know about. I confirm your solution is working. Thank you very much!

@davidhemphill This is maybe something worth adding to the documentation.
