### ISSUE TITLE
[REQUEST] Persist query filter configuration

### ISSUE THREAD

**Issue by didix16** [laravel/nova-issues#3219]
Hi there! I'm trying to persist the query filter configuration per user so, when I return again the user keeps the last filter was seeing.
I saw that  actually the only way to handle the filters is through the apply() method from filter itself. I cannot guess if the apply method is called by entering the first time to resource index view or the user has changed the filter by interaction with filter components...

So it would be nice to add some mechanism that we can use to guess if filter is being updated by user interaction.

I just saw that inside **Index.vue, @filter-changed="filterChanged"** is being called when user changed some filter. It could be nice that in such action the filter will be notified that is being changed by user interaction or maybe in the apply method collect such info incoming from request, I don't know. Just some mechanism to inform that.

Thanks in advance.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
