### ISSUE TITLE
HasOneThrough has a value of null, does not render

### ISSUE THREAD

**Issue by ddxor** [laravel/nova-issues#3220]
- Laravel Version: 8.22.1
- Nova Version: 3.19.1
- PHP Version: 7.4
- Database Driver & Version: mariadb 10.4
- Operating System and Version: macOS Big Sur, Docker (cyberduck/php-fpm-laravel:7.3)
- Browser type and version: Any

### Description:

When referencing a good HasOneThrough relationship - which works in tinker as expected - as a field, the field is not rendered. Noteworthy that the field is returned from the API with a `value` of `null`.

**Comment by crynobone** [comment]
The description quite vague, would it be possible to share reproducing code or screenshot to demonstrate the issue at the moment.

**Comment by ddxor** [comment]
Yes, sure. Thanks for the reply.

I have a resource `App\Nova\Foo` with corresponding model `App\Models\Foo`. A relationship `bar()` exists on the model, which returns a valid `HasOneThrough` entity.

So, calling for example `Foo::find(1)->bar()` returns a valid `HasOneThrough` working entity relationship.

But when I write in the `Foo` resource `fields()` method: `return [Fields\HasOneThrough::make('Foo')];` nothing is rendered on any page for this resource. It's worth noting that all other fields defined there work, including other relationships.

Am I missing something? Is a nova `HasOneThrough` relationship not supposed to render something, like a `BelongsTo` relationship does for example?

**Comment by ddxor** [comment]
I have resolved this issue by republishing frontend assets and updating to the latest version (although I was already on the version which officially supported `HasOneThrough`).
