### ISSUE TITLE
Removed from repository with a valid license

### ISSUE THREAD

**Issue by LorenzoSapora** [laravel/nova-issues#3221]
My access to the laravel/nova repository has been removed, and can no longer attach my account via the settings on nova.laravel.com.

Seems odd to pull this out of the blue, without notifying license holders?

**Comment by Ali-Shaikh** [comment]
Yea, I was shocked also that this happened out of the blue.

**Comment by FaridAghili** [comment]
This was already announced via email.

**Comment by medvinator** [comment]
> This was already announced via email.

When? I didn't get anything

**Comment by genesiscz** [comment]
Also didn't get any notice
