### ISSUE TITLE
Integrate VueJs component library

### ISSUE THREAD

**Issue by whoacowboy** [laravel/nova-issues#3224]
Hi,

i just started using Nova and it is a real time saver, thanks. I wanted to request integrating a VueJs component library into the next release. It doesn't matter to me which one https://vuematerial.io/, https://vuetifyjs.com/en/, https://www.vue-tailwind.com/ or any other. I just want an easier way to make my custom fields, tools, etc. to use dialogs, modals or whatever I happen to need. I have been adding my own which works, but it just takes time I'd rather spend on my idea and not reinventing the wheel.

Thanks!

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by riabiy-denis** [comment]
Agree with that. We need some library with components to use in Tools.
