### ISSUE TITLE
Accessing a parent relationship on creation within resource

### ISSUE THREAD

**Issue by latwelve** [laravel/nova-issues#3227]
I find it tricky to get the parent relationships data when trying to create a related resource.

My nova project is quite large with a decent amount of relationships - and this is the main thing that I find a real struggle to handle elegantly.

**Example of what I'm  trying to achieve:**
Create a related BookingItem that pulls back a value (exchange_rate) that is set from the Booking... IE
`$this->model()->booking->season->exchange_rate`

I'm sure I could probably achieve this with a custom field but it'd be overkill

`
    # Booking Model
    
    public function items(): HasMany
    {
        return $this->hasMany(BookingItem::class);
    }
    
    # Booking Item Model
 
    public function booking(): BelongsTo
    {
        return $this->belongsTo(Booking::class);
    }    
    
`

When creating a Booking Item Resource via a Booking Resource there is (as far as I can see) an easy way to get the Booking ID from the parent or even better the Model relationship so I can query it from the BookingItem like 

`$this->model()->booking->XYZ or similar.`

I've been trying to use the Request object on a private function but can't seem to get it to work on creation to grab it from the request url.. 

`/resources/booking-items/new?viaResource=bookings&viaResourceId=1&viaRelationship=items`

However I really hate the fact that I'm looking at a url to see a relationship so it'd be lovely if it was accessible 

Thanks
and sorry if my request is badly formatted!

**Comment by latwelve** [comment]
This may also help explain:

```
class BookingItem extends Resource
{

    // I dont mind if it has to be first accessed via a function here or the field created here then using $this->exchange_rate(); within fields to access it
    // private function exchange_rate() { 
    // xxx
    // }

    public function fields(Request $request)
    {
       
      return [

            Text::make('Exchange Rate',function(){
                return $this->model()->booking->season->exchange_rate;
            })->showOnCreating()->hideOnUpdating(),
```

**Comment by crynobone** [comment]
Laravel Nova doesn't show Computed Field on creation/updation form, do you have any other use case that we can apply this to?
