### ISSUE TITLE
Github laravel/nova repo has gone

### ISSUE THREAD

**Issue by ArroWsGM** [laravel/nova-issues#3229]
- Laravel Version: any
- Nova Version: any
- PHP Version: any
- Database Driver & Version: any
- Operating System and Version: any
- Browser type and version: any
- Reproduction Repository: https://github.com/laravel/nova

### Description:
There is no more option to install Nova from Github repo?

**Comment by crynobone** [comment]
Remove `vendor` folder and run `composer update --prefer-dist`.

**Comment by crynobone** [comment]
Also check out: https://github.com/laravel/nova-issues/discussions/3222#discussioncomment-332605

**Comment by ArroWsGM** [comment]
This is a really bad idea I think. First of all, not always developers is a licence holder, but my client is, and I obviously can't receive any emails, second - we can't track changes without repo.

**Comment by crynobone** [comment]
This isn't something to be discussed. Nova team cannot start new series development without removing previous series contibutors.
