### ISSUE TITLE
Document existing Vue Components

### ISSUE THREAD

**Issue by whoacowboy** [laravel/nova-issues#3230]
Hi this is a follow up to my previous request #3224.

I was digging through your source `./resources/js/components` and I think instead of add another framework you could document your components. You might even be able to pull them into their own packages and get people to add what they need.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
I personally don't think this is suitable, all Vue components are not within Laravel Nova public API where we will frequently make breaking changes to fix bugs.

**Comment by whoacowboy** [comment]
I have been developing with Laravel and Vue for years now, but I am new to using Nova. It is a real time saver. I find I spend most of my time when I am building front-end components. For example, on the project I am working on, I had to integrate a few fairly standard components, e.g. Modal dialog, CheckBox, etc. I typically work with larger frameworks and I found it frustrating to have to integrate components that Nova already used. I have been using the Nova components because they are already loaded in there. It would be extremely useful if you documented what you have or adopt an existing component framework that you would have to maintain. 

I understand it would be a PiTA, but the value for me would be immense. 

The other thing you could do is integrate an existing framework that you could make available and then build your Nova specific components off of those tools. You wouldn't have to worry about Nova's codebase fluctuating and you would extend Nova quite a bit IMO.

**Comment by riabiy-denis** [comment]
Can't agree more on that. Anything. But we need it.
