### ISSUE TITLE
My nova fork got deleted and i don't know why

### ISSUE THREAD

**Issue by simonschaufi** [laravel/nova-issues#3232]
I have a valid license for nova, connected my account to the github repo and a couple of days ago my fork got deleted and i don't have access to nova itself anymore. Since I don't know where I can ask for help, I'm doing it here. Can someone please tell me what happened and why?

**Comment by dkulyk** [comment]
https://davidhemphill.com/2020-in-review

> @crynobone  
welcome
current paid customer should still be able to download existing Orion releases after this. Just that the repo will be temporarily not accessible.

**Comment by simonschaufi** [comment]
Oo thanks for the info
