### ISSUE TITLE
 Failed to download laravel/nova 

### ISSUE THREAD

**Issue by killerbugs** [laravel/nova-issues#3233]
- Laravel Version: 7
- Nova Version: #.#.#
- PHP Version: 7.4
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:

Failed to download laravel/nova from dist: The 'https://nova.laravel.com/dist/laravel/nova/laravel-nova-a50eb75d8c5ea26320353f96c26266ad53c5ff93-zip-714e68.zip' URL could not be accessed: HTTP/2 403

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/107165190-1d9e2080-69ed-11eb-818e-436a9f6dd94b.png)

No issue with the URL, are you sure you have configured Composer Auth correctly as suggested in the documentation? 

> When running composer update, you will be prompted to provide your login credentials for the Nova website. These credentials will authenticate your Composer session as having permission to download the Nova source code. To avoid manually typing these credentials, you may create a Composer auth.json file while optionally using your API token in place of your password.
>
> https://nova.laravel.com/docs/3.0/installation.html#installing-nova-via-composer

**Comment by lhilton** [comment]
I can confirm this issue now exists for me as well. Attempted to update an existing project for the first time in a few months, could not get the latest version.

My `composer.json`:

```json
{
    ...
    "require": {
        ...
        "laravel/nova": "~3.0"
    },
    ...
    "repositories": [
        {
            "type": "composer",
            "url": "https://nova.laravel.com"
        },
        ...
    ]
}
```

and my `auth.json`

```json
{
    "http-basic": {
        "nova.laravel.com": {
            "username": "xxxxxxx@xxxxxxx",
            "password": "xxxxxxx-my-api-key-xxxxxxx"
        }
    }
}
```

The error message from `composer update` can be seen in this screenshot:

![Failed to download laravel/nova from dist: Invalid credentials for 'https://nova.laravel.com/dist/laravel/nova/laravel-nova-a50eb75d8c5ea26320353f96c26266ad53c5ff93-zip-714e68.zip', aborting.](https://the.unexpectedreboot.com/1612908969/Screen-Shot-2021-02-09-14-15-52.80.png "Error Message")

**Comment by Tarpsvo** [comment]
Yeah, the auth.json API token solution stopped working for me as well. Had to include username and password instead.
