### ISSUE TITLE
Image Field File Url appending APP_URL or AWS_URL to img src

### ISSUE THREAD

**Issue by andrewfschorr** [laravel/nova-issues#3236]
- Laravel Version: 7.0
- Nova Version: 3.21.0
- PHP Version: 7.4.15 
- Database Driver & Version:
- Operating System and Version: mac OS 11.2
- Browser type and version: Chrome 88
- Reproduction Repository: https://github.com/###/###

### Description:

I have a model that looks like the following, it's just a data model that produces an S3 image 
```
class DrinkImage extends Model
{
    protected $fillable = [
        'filename', 'url', 'drink_id',
    ];

    public function drink()
    {
        return $this->belongsTo('App\Drink');
    }
}
```

And it's created with the following: 
```
$path = $request->file('image')->store('images', 's3');
\Storage::disk('s3')->setVisibility($path, 'public');
$image = DrinkImage::create([
    'filename' => basename($path),
    'url' => \Storage::disk('s3')->url($path),
]);
$drink->image()->save($image);
```

The table schema looks like
```

| id | filename | url | drink_id |
|--|--|--|--|
| 1 | xyz | https://foo.s3.amazonaws.com/images/xyz.jpeg | 23 |
```

However in the nova admin dashboard the images are broken

`<img src="src="src="http://localhost/storage/https://topofshelf.s3.amazonaws.com/images/LrIefVRJbIHyOVFpbH36qON8LaDk6ofSTug7viBA.jpg"" class="align-bottom w-8 h-8 rounded" style="object-fit: cover;">`

And you can see the misconfigured non-url encoded **https%3A** in the url :[

What is also odd is that if I add `AWS_URL='FOO'` to my .env and change my nova class to `Image::make('Image', 'url')->disk('s3'),` then it in turn changes to `<img src="FOO/https://topofshelf.s3.amazonaws.com/images/LrIefVRJbIHyOVFpbH36qON8LaDk6ofSTug7viBA.jpg" class="align-bottom w-8 h-8 rounded" style="object-fit: cover;">`

### Detailed steps to reproduce the issue on a fresh Nova installation:
Steps above are on fresh Nova installation.

**Comment by crynobone** [comment]
And how did you access the image in Laravel Nova?

**Comment by andrewfschorr** [comment]
Just `'image' => $drink->image,` and my Drink model looks like

```
    public function image()
    {
        return $this->hasOne('App\DrinkImage');
    }
```

**Comment by crynobone** [comment]
I mean how did you configure the Image/File field?

**Comment by andrewfschorr** [comment]
I've really been trying any way possible. 

If I keep my Image like `Image::make('Image', 'url'),` and `APP_URL=foo` then the image ends up being `src="foo/storage/https://topofshelf.s3.amazonaws.com/images/LrIefVRJbIHyOVFpbH36qON8LaDk6ofSTug7viBA.jpg"` or if I delete `APP_URL` completely, its `src="/storage/https://topofshelf.s3.amazonaws.com/images/LrIefVRJbIHyOVFpbH36qON8LaDk6ofSTug7viBA.jpg"`

And if change it to `Image::make('Image', 'url')->disk('s3'),` `APP_URL` has no bearing on it, but `AWS_URL=FOO` (which I normally exclude) makes it `src="FOO/https://topofshelf.s3.amazonaws.com/images/LrIefVRJbIHyOVFpbH36qON8LaDk6ofSTug7viBA.jpg"`

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/107305860-bb155500-6abe-11eb-93cd-82fe9e021deb.png)

You can override `thumbnail()` and `preview()` method:

```php
Image::make('URL')->thumbnail(function ($value) {
    return $value;
})->preview(function ($value) {
    return $value;
}),
```

Unfortunately, it would require more customization if you need to allow editing/removing images via Laravel Nova as this doesn't follow the conventional structure described in https://nova.laravel.com/docs/3.0/resources/file-fields.html

**Comment by andrewfschorr** [comment]
Woah, I was prepared to do some string manipulation in those methods, but literally just replacing the entire line with what you had above seemed to have fixed the issue. I guess we can close this issue, but it would still reason to think that it's an actual bug and for some reason it's trying to return the APP_URL or AWS_URL in the thumbnail and preview image in the template/client side. Cheers! :)
