### ISSUE TITLE
Incomplete translations

### ISSUE THREAD

**Issue by martio** [laravel/nova-issues#3237]
- Laravel Version: 8.25.0
- Nova Version: 3.20.0
- PHP Version: 8.0.1

### Description:

Incomplete translation when localization is set to another language in the app config file.

### Detailed steps to reproduce the issue on a fresh Nova installation:

FILE: config/app.php

When _**'locale' => 'en'**_ is **OK**:

<img width="1440" alt="Zrzut ekranu 2021-02-10 o 11 16 03" src="https://user-images.githubusercontent.com/133636/107496743-fc2a6980-6b91-11eb-8122-96662fb81ca1.png">

When _**'locale' => 'pl'**_ is **INCOMPLETE** ("Resouces" label in sidebar and "Create" button):

<img width="1440" alt="Zrzut ekranu 2021-02-10 o 11 16 26" src="https://user-images.githubusercontent.com/133636/107496787-0c424900-6b92-11eb-8c08-5b134463b8ca.png">

NovaServiceProvider:

```
    public function boot()
    {
        parent::boot();

        Nova::serving(function (ServingNova $event) {
            $this->app->setLocale('pl');

            Nova::translations([
                resource_path('lang/vendor/nova/en.json'),
                resource_path('lang/vendor/nova/pl.json'),
            ]);
        });
    }
```

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/107502799-20a73580-6bd4-11eb-95f8-1e862f6d3660.png)

This doesn't seem to be correct.
