### ISSUE TITLE
Computed field causes exception when trying to create/update resource model

### ISSUE THREAD

**Issue by chescos** [laravel/nova-issues#324]
I have a computed field which accesses the property `value` of the `Coupon` relation (which is eager loaded through the `$with` property):

```php
Number::make('Value', function () {
    return $this->coupon->value;
})
```

Viewing works fine, in both index and detail.

But when I try to create or update a model, I get this exception: `Trying to get property 'value' of non-object`.

**Comment by David-Melo** [comment]
I had this happen. In my case, I had to put and IF there the account for when an item is created and doesn't have the relation created/loaded yet.

**Comment by chescos** [comment]
@David-Melo thank you for the workaround. But I still consider it a bug, I can't believe that it is expected to wrap your computed fields into `if` statements?

**Comment by davidhemphill** [comment]
This is basic PHP...if you don't have a coupon property and try to access a property on that non-existent relation, it will throw an exception.
