### ISSUE TITLE
Action Response Modals do not appear from resource index table

### ISSUE THREAD

**Issue by rklugman** [laravel/nova-issues#3240]
- Laravel Version: 8.26.1
- Nova Version: 3.21.0
- PHP Version: 8.0.0
- Database Driver & Version: MySQL 8.0.23
- Operating System and Version: Mac OS 10.15
- Browser type and version: 88.0.4324.150 

#### Action Response Modals

Custom modal not shown when action is performed inline from resource index table.

<img width="1180" alt="Screen Shot 2021-02-12 at 8 44 14 AM" src="https://user-images.githubusercontent.com/40756947/107738021-8697d800-6d0e-11eb-9cb0-352c97e63892.png">

I believe this is because `vendor/laravel/nova/resources/js/components/Index/InlineActionSelector.vue` does not have a dynamic component for the custom modal which is available from the resource detail page `vendor/laravel/nova/resources/js/components/ActionSelector.vue:74`

**Comment by davidhemphill** [comment]
Hey thanks for noticing this! We'll take a look.

**Comment by davidhemphill** [comment]
I also like the emojis in your Action labels. 👍

**Comment by davidhemphill** [comment]
Fixed in the latest release: https://nova.laravel.com/releases/3.21.1
