### ISSUE TITLE
Trend Metric doesn't accept width '2/4' 

### ISSUE THREAD

**Issue by hniehorster** [laravel/nova-issues#3246]
- Laravel Version: 8.0
- Nova Version: 3.22.0
- PHP Version: 7.3
- Database Driver & Version: MySQL 8.0.1
- Operating System and Version: Mac OS 14
- Browser type and version: Safara and Chrome

### Description:
When adding multiple metrics on a resource the width of '2/4' doesn't work. 
```
public function cards(Request $request)
    {
        return [
            (new Metrics\InvoiceRevenue())->width('1/4'),
            (new Metrics\InvoiceRevenue())->width('1/4'),
            (new Metrics\RevenueTrend())->width('2/4'),
        ];
    }
```

The Revenue Trend isn't displayed. 

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Add a resource
2. Add a Value metric and assign it twice with width '1/4'
3. Add a trend metric and assign width of '2/4'

### What does work? 
*✅ '1/4' works*
```
 return [
            (new Metrics\InvoiceRevenue())->width('1/4'),
            (new Metrics\InvoiceRevenue())->width('1/4'),
            (new Metrics\RevenueTrend())->width('1/4'),
        ];
```
![Screenshot 2021-02-17 at 18 14 53](https://user-images.githubusercontent.com/12053327/108241365-0af1bd00-714c-11eb-8792-a73c645634e3.png)

*✅ '1/3' works*
```
return [
            (new Metrics\InvoiceRevenue())->width('1/4'),
            (new Metrics\InvoiceRevenue())->width('1/4'),
            (new Metrics\RevenueTrend())->width('1/3'),
        ];
```
![Screenshot 2021-02-17 at 18 15 54](https://user-images.githubusercontent.com/12053327/108241489-2eb50300-714c-11eb-96c1-0b634b5ab381.png)

*👎 '2/4' doesn't work*
```
       return [
            (new Metrics\InvoiceRevenue())->width('1/4'),
            (new Metrics\InvoiceRevenue())->width('1/4'),
            (new Metrics\RevenueTrend())->width('2/4'),
        ];
```
![Screenshot 2021-02-17 at 18 17 06](https://user-images.githubusercontent.com/12053327/108241657-5a37ed80-714c-11eb-8972-ba185d8e2dcb.png)

**Comment by chinleung** [comment]
Why not `1/2` instead of `2/4` though? 🤔

**Comment by hniehorster** [comment]
Damn you are smart :P, works. But still think that 2/4 should work. Makes it more consistent.
