### ISSUE TITLE
Ability to configure nova-api route middelware 

### ISSUE THREAD

**Issue by pavinthan** [laravel/nova-issues#325]
So we can implement the Nova service with other client like Mobile Application, 
please load api route configuration from `config/nova.php`.

**Comment by pavinthan** [comment]
Any ideas?

**Comment by approached** [comment]
I have the same problem. Nova api is not configurable! I have workaround with HTTP-Referrer. But if you have tests, you became big problems with routings. :-(

I hope this feature is coming.

**Comment by gkermer** [comment]
I also would appreciate it if the api route `/nova-api` would be configurable within `config/nova.php`.

**Comment by alexbowers** [comment]
Can someone explain a use-case for making this configurable?

I believe that quite a few packages would have this as a hardcoded value so it may be a BC issue.

**Comment by approached** [comment]
I would create two dashboards. That's are completely different based on Layout, Resources, Actions.

That's why i have two ServiceProvider for this job (dependig which url will accessed).

**Comment by alexbowers** [comment]
@approached When you say "two dashboards" do you mean two completely separate installs of Nova, or do you mean that you want 2 dashboard pages?

**Comment by approached** [comment]
How do you set 3 dashboard? Like for:
* customer
* reseller
* admin

Of course, you want to use one installation of nova. It uses normally this folder: `<projectdir>/nova`.
The second step is for each dashboard to create a `Serviceprovider`. In the serviceprovider,  i will set the dashboard-url. But in this step can't configure the `nova-api` url.

@alexbowers  I think the answer is two 2 dashboard pages? I'm not clear with the question.

**Comment by alexbowers** [comment]
@approached My reason for that question was to see whether this package i've built is suitable for you.

If you are looking at having three separate entities of Nova (which cannot be solved simply with Gate and policies), then it may not be what you're looking for.

Worth looking at though, incase it is:

https://github.com/alexbowers/nova-multiple-dashboard/

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by pavinthan** [comment]
@davidhemphill thank you so much to take action on this issue and is there any way like trello to see the progress of the feature requests or what are the changes coming with other releases? 🤔 

We ask this feature because to connect with our other client application ( mobile app ),
It's should really help to integrate with other clients without any changes.

Nova is really pain killer for developers 💯, thanks again for this product 🙏
