### ISSUE TITLE
Method Illuminate\\Database\\Eloquent\\Collection::getKey does not exist

### ISSUE THREAD

**Issue by bdelamatre** [laravel/nova-issues#3250]
- Laravel Version: 8.x
- Nova Version: 3.22.0
- PHP Version: 8.x
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:

Adding Nova fields to accommodate the out-of-box JetStream User and Team relationship Created two resources, one for User and one for Team. 

On the User resource added this field:
`BelongsToMany::make('Other Teams', 'teams', Team::class),`

The definition of teams() from JetStream on the User model is:
```
/**
 * Get all of the teams the user belongs to.
 *
 * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
 */
public function teams()
{
    return $this->belongsToMany(Jetstream::teamModel(), Jetstream::membershipModel())
                    ->withPivot('role')
                    ->withTimestamps()
                    ->as('membership');
}
```

When I attempt to attach the team through the Nova UI, I receive the following exception:
```
"message": "Method Illuminate\\Database\\Eloquent\\Collection::getKey does not exist.",
    "exception": "BadMethodCallException",
    "file": "/var/www/vhosts/myvhost/private/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php",
    "line": 103,
```

I was able to trace this error to Laravel\Nova\Rules line 90:
`if ($modelBeingUpdated->{$attribute}->getKey() == $value) {`

teams() doesn't have a getKey() method.  If I comment out lines 90 and 92 this UI works as expected.

**Comment by crynobone** [comment]
Those lines will only be executed for inverse of `HasOne` or `MorphOne`. This shouldn't happen if you declare the field as `BelongsToMany`

**Comment by bdelamatre** [comment]
The field was defined as BelongsToMany:
`BelongsToMany::make('Other Teams', 'teams', Team::class),`

However, it seems to be working today with the lines uncommented. I probably did accidently configure to HasOne before switching to BelongsToMany though. Maybe something was cached?
