### ISSUE TITLE
Reload button on Index of resource

### ISSUE THREAD

**Issue by vFire** [laravel/nova-issues#3251]
Do I missed something? I just can't find how to reload the current resource index page, not refresh the whole page since it is built of vuejs. Or I can create a custom button in it?

**Comment by vFire** [comment]
Not the polling related function.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
