### ISSUE TITLE
Metrics with timestamp doesn't work

### ISSUE THREAD

**Issue by absolutezeroo** [laravel/nova-issues#3254]
- Laravel Version: 8
- Nova Version: 3
- PHP Version: 7.4
- Database Driver & Version: Mysql

### Description:

Metrics does not work with timestamps stored in the database:

![image](https://user-images.githubusercontent.com/39636956/108651536-44b32280-74c2-11eb-9497-99ae4754871e.png)

![image](https://user-images.githubusercontent.com/39636956/108651558-54326b80-74c2-11eb-8243-ba10a4a5e9b3.png)

![image](https://user-images.githubusercontent.com/39636956/108651453-11709380-74c2-11eb-92bf-febd1d528775.png)

### Detailed steps to reproduce the issue on a fresh Nova installation:

Use timestamp in your database and in your metric change dateColumn by the timestamp field

**Comment by crynobone** [comment]
Sorry but unfortunately Trend Metric isn't designed to work with timestamp column at the moment, and it would be hard to generate compatible SQL queries for every database.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
