### ISSUE TITLE
pagination filter on relationships hasMany

### ISSUE THREAD

**Issue by gustav1105** [laravel/nova-issues#3256]
On the resource i can filter for pages per results.
On a related field i cannot?

Please include the results per page filter on index views exposed as hasMany relationship on resource. thanks

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
