### ISSUE TITLE
Uncaught ReferenceError: CreateNova is not defined

### ISSUE THREAD

**Issue by milewski** [laravel/nova-issues#3257]
Getting this error after upgrading from nova: `3.20` to `3.22`, UI doesn't load as it is a runtime error that happens before vue app is mounted

![image](https://user-images.githubusercontent.com/2874967/108837007-89e36b80-760c-11eb-92c6-064ba16f6337.png)

**Comment by crynobone** [comment]
try running `php artisan nova:publish`.

**Comment by milewski** [comment]
I did that multiple times, I have also tried to remove the assets from the public folder and republish.. now I'm trying to compile the code by myself so I can see the real error

**Comment by milewski** [comment]
Never mind I figured it out. I was using `app.js` from `v3.20` and `manifest/vendor.js` from `v3.22` my CDN was configured to ignore the ?v= in the URL...
