### ISSUE TITLE
DateFilter format can not be changed

### ISSUE THREAD

**Issue by schonhoff** [laravel/nova-issues#3258]
### System
- Laravel Version: 8.27
- Nova Version: 3.22
- PHP Version: 7.4
- Database Driver & Version: MySql
- Operating System and Version: Windows/Ubuntu
- Browser type and version: Chrome 88.0.4324.182

### Description
The format can not be changed on a date filter. 
Old ticket: https://github.com/laravel/nova-issues/issues/1170
As @jbrooksuk mentioned there if we experiencing the issue we should open a new ticket.

### Detailed steps to reproduce the issue on a fresh Nova installation
1.) create a standard date filter as explained in the [Dokumentation](https://nova.laravel.com/docs/3.0/filters/defining-filters.html#date-filters)
2.) try to change the date format or the alt format to the German date notation "DD.MM.YYYY"
3.) Nothing will change

### Other things I tried
I tried to add some properties to the meta data in the constructor:
``` php
  $this->withMeta([
      'format' => 'DD.MM.YYYY',
      'pickerFormat' => 'd.m.Y',
      'altFormat' => 'd.m.Y'
  ]);
```

### Possible solution
In "nova/resources/js/components/Filters/DateFilter.vue" add something like the firstDayOfWeek switch to enable possible format switches.

Hope this bug can be solved.

**Comment by crynobone** [comment]
Duplicated of #2866

**Comment by schonhoff** [comment]
Hm, is it really a feature request? I would guess that it is a bug because the functionality should be always given and not different in another component. Hopefully it will be changed.
