### ISSUE TITLE
File field not respecting path()

### ISSUE THREAD

**Issue by epalmans** [laravel/nova-issues#3259]
- Laravel Version: 8.24.0
- Nova Version: 3.20.0
- PHP Version: 7.4.13
- Database Driver & Version: MySQL 5.7
- Operating System and Version: Ubuntu 18.04 (production) + Windows 10 (local dev.)
- Browser type and version: Chrome 88
- Reproduction Repository: <closed source>

### Description:
When using the ```File``` field, the ```path()```-method provided by the ```Storable````-trait may be used. While the path seems to be respected on _storing_ files, it won't be when downloading the files.

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Create a nova resource. The backing model is using a table with two nullable varchar(191) fields: ```resume``` and ```resume_filename```. The first one holds the actual name of the file (not the full path) as is being stored within a s3 bucket's 'applicants/'-folder. The latter contains the original name of the file as uploaded by the user.
2. The field defintions:
```php
File::make('Resume')
    ->path('applicants')
    ->disk('s3_private')
    ->storeAs(fn (Request $request) => sha1($request->resume->getClientOriginalName()).'_'.Str::random(6))
    ->storeOriginalName('resume_filename'),

Text::make('Resume filename', 'resume_filename')->exceptOnForms()->hideFromIndex(),
```

### Suggested solution
Within Laravel\Nova\Fields\File, change:
1. the ```getStoragePath()```-method to include the path, ie.:
```php
public function getStoragePath()
{
    return $this->getStorageDir().'/'.$this->value;
}
```
2. Within the download and delete callbacks (in the constructor), swap out the use of ```$this->value``` for ```$this->getStoragePath()```
3. [untested] Probably, the same should apply to the thumbnail and preview callbacks for the Image field/class

**Comment by epalmans** [comment]
PS. as a workaround, I'm now removing the explicit ```path()```` and specifying ```applicants/_<filename>_``` within the field's value. That works, but is just a slightly less nice implementation.

**Comment by crynobone** [comment]
Seem to be a breaking change. Will consider this for next series.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
