### ISSUE TITLE
Feature Request: Metrics refresh

### ISSUE THREAD

**Issue by SpiritSaint** [laravel/nova-issues#3262]
> Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to  post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

I'm pretty sure that Metrics are cool stuff but i has been watching how to make it more great. Looking the following code inside of MetricBehavior.js:

```javascript
if (this.card.refreshWhenActionRuns) {
      Nova.$on('action-executed', () => this.fetch())
    }
```
That's possible as we add a new meta data to the card like "refreshUsingInterval", setting a configurable number. 

```javascript
if (this.card.refreshUsingInterval) {
  setInterval(() => this.fetch(), this.card.refreshInterval)
}
```

What you think about this?

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
