### ISSUE TITLE
sortable() on belongsTo sort by id instead of title

### ISSUE THREAD

**Issue by eAvio** [laravel/nova-issues#3265]
` BelongsTo::make('Company')->sortable(),`

Company resource has `public static $title = 'name';`

On index we see companies names, but when trying to sort them they are not sorted by name but by ids.

I guess this is not expected.

Is there any workaround for that?

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by eAvio** [comment]
Hi, This is not request for a new feature, I guess this is bug, no? Isn't it expected that if you click "sort" on index that you actually get items sorted?

**Comment by timcv** [comment]
This is clearly a bug. And it has been asked for multiple times.

**Comment by davidhemphill** [comment]
It's not a bug. The column is `company_id` and it is sorted based on that local value.
