### ISSUE TITLE
Action only handles half the results of "select all matching"

### ISSUE THREAD

**Issue by rderks88** [laravel/nova-issues#3269]
- Laravel Version: 8.12.#
- Nova Version: 3.0.#
- PHP Version: 8.0.#
- Database Driver & Version: Postgres but irrelevant
- Operating System and Version: Linux
- Browser type and version: Chrome

### Description:
After using "select all matching" to update a large batch of resources, only half of the chunks will be processed. I did find similar issues but they did not handle this specific case. They considered deleting for which reverse chunk order would be the solution. In this case using "chunkById" instead of "chunk" within method "chunks" within "namespace Laravel\Nova\Http\Requests\ActionRequest" seems to be the solution. That however is also mentioned in [https://github.com/laravel/nova-issues/issues/1314](https://github.com/laravel/nova-issues/issues/1314) but does not solve the issue for me.

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Create 1000 records of a resource (at least bigger then your chunkSize (default 200))
- Create an action that updates and saves one of the resource's columns within the action
- Go to your index page and use "select all matching"
- After the action is completed, only half the chunks will be processed correctly

**Comment by crynobone** [comment]
This has been fixed in 3.23.0 but please upgrade to 3.23.1. https://nova.laravel.com/releases
