### ISSUE TITLE
Value Metric showing "No Current Data" when value is 0

### ISSUE THREAD

**Issue by Livijn** [laravel/nova-issues#327]
[As seen here](https://gyazo.com/c4e317419b4f3934531bc027c269d8bd) my Value Metric is showing "No Current Data" when the value is actually 0. It confuses the user (or me) to believe something actually went wrong.

Is there anyway you might allow for 0-values, or should I create a custom card?

**Comment by Livijn** [comment]
Might be same as #122

**Comment by LorensoD** [comment]
This doesn't seem to be fixed. When I pass a 0-value to the result function it still shows the "No Current Data" message. 

I'm using the Value Metric to display a single calculated value so I only pass the result:
`return $this->result($value);`

How do I, with https://github.com/laravel/nova-js/pull/4, prevent this message from displaying when the result value is actually 0?

**Comment by krb19xx** [comment]
I am having the same issue - when returning a result value of 0, the Nova dashboard metric shows the 0 value but also says "No Current Data". How can we make the "No Current Data" message go away?

**Comment by tpetry** [comment]
@davidhemphill This is still happening on nova 2.4.0

**Comment by Livijn** [comment]
@davidhemphill This is not fixed and should be reopened.
