### ISSUE TITLE
Not using config.nova.name for titleTemplate in Vue

### ISSUE THREAD

**Issue by borutjures** [laravel/nova-issues#3270]
- Laravel Version: 8.29.0
- Nova Version: 3.22.0
- PHP Version: 8.0.2
- Database Driver & Version: pgsql 12
- Operating System and Version: macOS 10.15.17
- Browser type and version: Firefox 86.0

### Description:

Title text in the browser's tab for Nova views is using base Laravel's APP_NAME instead of Nova's APP_NAME in Nova's Vue app.

Blade templates are correctly using `<title>{{ \Laravel\Nova\Nova::name() }}</title>` which displays `config.nova.name`.
See: `nova/resources/views/layout.blade.php`

Nova's Vue app is using `titleTemplate: '%s | ${window.config.appName}'` and `window.config.appName` is taken from the base Laravel app. It should be **`window.config.nova.appName`**.
See: `nova/resources/js/Nova.js`

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Change Nova's app name in `config/nova.php`: `'name' => env('NOVA_APP_NAME', env('APP_NAME')) . ' Admin',`
2. Go to `https://example.test/nova/dashboards/main`.
3. Title in the browser's tab is `Dashboard | Laravel` instead of `Dashboard | Laravel Admin`.

**Comment by borutjures** [comment]
I didn't have any expectations of convincing anybody to fix such a minor bug.
However I was disappointed when this issue was closed without a comment. @davidhemphill 

I've spent more time looking at the code. There is a quick fix on the PHP side. @taylorotwell 

Source file: `Laravel\Nova\src\NovaServiceProvider.php`
Function: `registerJsonVariables()`

Original line: `'appName' => config('app.name', 'Laravel Nova'),`
Fixed line: `'appName' => config('nova.name', 'Laravel Nova'),`

**Comment by crynobone** [comment]
@borutjures closed assigned bug only meant a PR has been merged. However we still waiting for upcoming release before updating this issue.

**Comment by borutjures** [comment]
Thank you for the PR and the explanation.

I've learnt your approach now. I was used to having such issues marked as `Waiting for release` since we don't see the private PRs.

Thank you all for the Nova!

**Comment by crynobone** [comment]
This has been fixed in 3.23.0 but please upgrade to 3.23.1. https://nova.laravel.com/releases
