### ISSUE TITLE
add extraAttributes to PasswordField

### ISSUE THREAD

**Issue by bdelamatre** [laravel/nova-issues#3271]
Please clone the extraAttributes feature from the Text and Textarea fields to Password. It would probably be useful for all fields but is particularly useful on passwords for the purpose of managing various tags for password managers. For example:

```php
Password::make('Password')
  ->onlyOnForms()
  ->withMeta([
      'extraAttributes'=> [
          'data-lpignore' => 'true',
      ],
  ])
```

Will prevent LastPass passwords from populating the password field when creating / updating a (user) resource

**Comment by stevepowell2000** [comment]
This would be great as it would allow the user edit screens to not automatically populate the password field and possibly erroneously change a user password

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
