### ISSUE TITLE
BelongsTo field always ordered by SORT_REGULAR

### ISSUE THREAD

**Issue by martijngastkemper** [laravel/nova-issues#3272]
In `AssociatableController::index()` the result set is ordered with `->sortBy('display')`. I would like to be able to control that, because it uses the default `SORT_REGULAR` and I want sort it the same as MySQL `order by` does for consistency.

I would like to be able to call `->sortBy('display', SORT_NATURAL | SORT_FLAG_CASE)` or be able to disable that sorting so the order of the query is used.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
You can now use following to avoid `sortBy('display')`

```php
BelongsTo::make('User')->dontReorderAssociatables(),
```
