### ISSUE TITLE
Partition metric seems to round off float values

### ISSUE THREAD

**Issue by introwit** [laravel/nova-issues#3275]
- Laravel Version: 8.28.1
- Nova Version: 3.22.0
- PHP Version: 7.4
- Database Driver & Version: MySQL 8
- Operating System and Version: Mac Catalina
- Browser type and version: Chrome 88.0.4324.192

### Description:

Hi, The Partition Metrics round off float values to nearest accurate integer. However this can cause an issue when the metric is dealing with sensitive values such as costs of things where the float values might be needed as it is. So is it possible to set some flag to let the list on left hand side in the metric card consider listing the float values as it is? 

### Detailed steps to reproduce the issue on a fresh Nova installation:

- After a fresh install of nova, create a partition metric and let the `calculate` method return the following:

```php
public function calculate(NovaRequest $request)
{
        return $this->result([
            'X cost' => 0.03
            'Y cost' => 1.2, 
            'Z cost' => 0.15,
        ]);
}
```

- This will return 0, 1 & 0 respectively. The pie chart on right side needs integer which is fair, but maybe the left side list of values can display floats as it is?

**Comment by crynobone** [comment]
You should be able to customize `$roundingPrecision` and `$roundingMode` property based on your use case. For full control override `result()` method.

**Comment by introwit** [comment]
@crynobone woah thanks! Looks like its missing from the docs. Have sent a [PR](https://github.com/laravel/nova-docs/pull/312) to include this in the docs.
