### ISSUE TITLE
Custom field missing $component

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#3278]
- Laravel Version: 8.10
- Nova Version: 3.9

### Description:

$component missing from the field class when `php artisan nova:field vendor\field-name`
This causes the field to output nothing until you explicitly define a $component property.
I don't think anyone would know to do this by default and might cause confusion.

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/109927860-c5162680-7cff-11eb-98f5-6056204466dd.png)

Seem to be the current default.

**Comment by dillingham** [comment]
Ok maybe the project im working on has something off about it.

Sorry, just thought it was missing for everyone

**Comment by crynobone** [comment]
It could be you have published the stub and now it became outdated?
