### ISSUE TITLE
Display of the place field is cut off in the modal of an action.

### ISSUE THREAD

**Issue by socialab-admin** [laravel/nova-issues#3279]
- Laravel Version: 8.30.1
- Nova Version: 3.22.0
- PHP Version: 8.0
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: Google Chrome 88

### Description: (Attachment screenshot)
![Captura](https://user-images.githubusercontent.com/45668463/109982455-b1a79300-7ce0-11eb-9ef2-1f5371b43f9b.PNG)

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Create an action
2. Add an Action Fields of type Place

**Comment by crynobone** [comment]
This has been fixed in 3.23.0 but please upgrade to 3.23.1. https://nova.laravel.com/releases
