### ISSUE TITLE
Shortcut keys fire when modal is open

### ISSUE THREAD

**Issue by latwelve** [laravel/nova-issues#3280]
- versions: latest

## Description:

If you have a model which requires user input via a field, it's quite easy to shut the model by accident by misclicking the form and pressing E which triggers the shortcut key to edit the Resource.

There is no check on the model before closing it and it feels natural to expect this should be disabled whilst a model is active and takes priority

From a UX persepctive I actually think shortcut keys using a single a-z character should be disabled by default as I find it has more drawbacks that positives. The global search "/" seems sensible by default

## Reproduce:

1, create an action with a form field
2, trigger the action to open its model
3, press E

User loses their model and any text they had input in the model form field

**Comment by crynobone** [comment]
This has been fixed in 3.23.0 but please upgrade to 3.23.1. https://nova.laravel.com/releases
