### ISSUE TITLE
Stacked field labels remain at 20% (w-1/5) width

### ISSUE THREAD

**Issue by neilwhitespace** [laravel/nova-issues#3281]
- Laravel Version: 8.31.0
- Nova Version: 3.22.0
- PHP Version: 7.4.15
- Database Driver & Version: N/A
- Operating System and Version: N/A
- Browser type and version: (All browsers, class issue)
- Reproduction Repository: https://github.com/neilwhitespace/laravel-nova-issue-stacked-fields

### Description:
It appears that when a field is stacked using the `stacked` method within field creation, its "edit" page label remains as wide as before. It may benefit from using the full width of the panel to allow for wider field labels, as well as the fields themselves.

### Detailed steps to reproduce the issue on a fresh Nova installation:

 - Modify any resource's field to have a long label and use the `stacked` method.
 - View the field on the resource's edit page

**Comment by crynobone** [comment]
This has been fixed in 3.23.0 but please upgrade to 3.23.1. https://nova.laravel.com/releases
