### ISSUE TITLE
`Line` field (within `Stack`) don't take into account methods like `onlyOnIndex`

### ISSUE THREAD

**Issue by beNjiox** [laravel/nova-issues#3282]
- Laravel Version: 8.27.9
- Nova Version: 3.21.0 
- PHP Version: 7.4.13
- Database Driver & Version: PostgreSQL 10
- Operating System and Version: MacOS
- Browser type and version: Latest Firefox
- Reproduction Repository: Don't have one but reproduction is fairly easy, hopefully (see below)

### Description:

I'm using the Stack field a lot lately, which is a supper addition to Nova.
My problem is that I was expecting the visibility helpers to work for the lines composing a Stack.
I'm talking about methods such as :

- `onlyOnDetail`
- `onlyOnIndex`
- `hideFromIndex`
- `hideFromDetail`

Turns out, it doesn't work.
All lines will always be displayed everywhere, no matter what I do.
I don't know if this wasn't intended to work that way, but I would find this very useful.

For example, I would like only a few lines to be included in my index views, but all of them in the detail page. That way I can group related information within the same Stack, without cluttering the index view. Without this option, I need to hack my way through (without using Stack, through a Text field doing conditionals based on some of the $request properties..), which is doable but ot ideal.

### Detailed steps to reproduce the issue on a fresh Nova installation:

In any Nova Resource, add a Stack in the returned array in the `fields` method :

```php
Stack::make(
    'customer',
    [
		// we want this line everywhere
        Line::make("attributeOne", fn() => $this->attributeOne),

		// we want this line only on index
        Line::make("attributeTwo", fn() => $this->attributeTwo)->onlyOnIndex(),

		// we want this line only on detail page
        Line::make("attributeThree", fn() => $this->attributeThree)->onlyOnDetail()
    ]
);
```

**Comment by crynobone** [comment]
Try updating to latest Laravel Nova release. Seem to be duplicate of #3242

**Comment by beNjiox** [comment]
Ah! @crynobone! You are right.
The last version solves it. 
Sorry I looked in the issues first, but only in the open ones.
Thanks for checking this out that fast. 🙏
