### ISSUE TITLE
Nova event 'resource-loaded' not emitted on detail view

### ISSUE THREAD

**Issue by vladderave** [laravel/nova-issues#3283]
- Nova Version: 3.22.0

### Description:
The Nova event 'resources-loaded' is emitted on the list-view, 'resource-loaded' on the edit view, but not on the detail view.

Similar issue: https://github.com/laravel/nova-issues/issues/2029

**Comment by crynobone** [comment]
I cannot find any commit history indicating it was ever `Nova.$emit('resources-loaded')` from within `views/Detail.vue`. User may receive the event if the detail page contains a resource table. 

Marking this as a feature request for now.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
