### ISSUE TITLE
Add support for markdown-it attributes plugin to Markdown Field

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [laravel/nova-issues#3285]
I was wondering if there was any chance the core Markdown field would be able to support/correctly display attributes, as allowed by the https://github.com/arve0/markdown-it-attrs plugin for markdown-it (since you are using markdown-it)

This would allow things like `[Laravel](https://laravel.com/){target="_blank"}` 

It is currently working in terms of storing the raw data in the database, but when the Field is previewed in Nova both in Form and Detail mode, the `{target="_blank"}` bit renders visibly after the link, instead of disappearing

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
