### ISSUE TITLE
Maxlength attribute not respected by Slug field

### ISSUE THREAD

**Issue by haltsir** [laravel/nova-issues#3286]
- Laravel Version: 8.31.0
- Nova Version: 3.22.0
- PHP Version: 7.4.11
- Browser type and version: Firefox 86.0

### Description:

SEO-wise it's better to have a slug with max length of 50-60 symbols. I'm trying to create a blog system and automatically generate slugs from title, but setting the maxlength attribute only works if I type in the slug directly, not when I generate it from another field (i.e. Title). This is becase JavaScript can override the maxlength attribute.

IMO the code that automatically generates the slug field should also check whether the maxlength attribute is set and respect its limitations.

Same thing goes for the `rules()` method on a field, when using `rules(['max:10'])` the Slug field keeps updating over the limitation while typing into the Title field.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Create a Slug field that generates from a Title field:

```
public function fields(Request $request)
    {
        return [
            Slug::make(__('Slug'))
                ->from('Title')
                ->withMeta(['extraAttributes' => ['maxlength' => 10]]),
            Text::make('Title')
        ];
    }
```

Type symbols in the Title field to generate the content of the Slug field. Expected behaviour is to stop at the 10th character, but currently it continues beyond that.

**Comment by crynobone** [comment]
I'm considering this as a feature request and we do need to define some expectations before implementing this. 

* Would using `<input maxlength="10">` be enough?
* What's the expectation if title exceed 10 characters
* What's the expectation if slug already exists in the database.
* Other considerations...

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by haltsir** [comment]
Regarding the expectations:

- Using `<input maxlength="10">` wouldn't be enough since this limitation can be skipped by changing the Slug field's `value` property by JavaScript. It should however still be present as an attribute to the Slug input field since it would easily protect against manually typing in characters.
- If the Slug input field reaches its max length, no new characters should be appended to it unless any are deleted before that. Characters can be deleted either manually from the Slug field or programatically by reducing the Title size (as it is now). An extra would be to notify the user of the reached limitation, but I don't see this as a necessity.
- If the slug already exists in the database the current behaviour should continue to be used, whatever it is. Ideally it would mark the field in red and display a duplication error, but I don't see that as a necessity.
- The limitation should be considered against any valid slug character. It should validate the length of the Slug field before the already existing functionality of generating it from Title has tried to add a new character to the Slug. Basically it would allow further automatic generation or manual typing of characters only when `input.value.length` is less than the value of `input.attributes.maxlength`, so to speak. The `maxlength` input attribute will take care of manual typing, but functionality is needed for the automatic one as it is done by JavaScript. This validation should be triggered on any programatic attempt to add a new character to the Slug field.
