### ISSUE TITLE
Set currency for amount dynamically.

### ISSUE THREAD

**Issue by stephan-v** [laravel/nova-issues#3287]
Currently you can set the currency on a Currency field using `->currency('EUR')` except this does not help when you have a different currency per Payment record.

Am I seriously forced to do something like this in order to achieve this in a paid software product?

```
Currency::make('Amount')->asMinorUnits()->displayUsing(function(int $amount, Payment $payment, $test) {
    return Money::ofMinor($amount, $payment->currency)->formatTo(config('app.locale', 'en'));
}),
```

**Comment by bilfeldt** [comment]
@stephan-v this can be done like so:

```php
Currency::make('Amount')->currency($this->currency); // The currency used will be taken from the models column `currency`
```
