### ISSUE TITLE
Laravel Nova stores unknown job_batch id in CallQueuedAction (job) class, causing Laravel Horizon to display a link to an unknown job_batch record

### ISSUE THREAD

**Issue by mattyh88** [laravel/nova-issues#3290]
- Laravel Version: 8.22.1
- Nova Version: 3.19.1
- PHP Version: 7.4.2
- Database Driver & Version: Mysql 5.7
- Operating System and Version: Debian GNU/Linux 10 (buster)
- Browser type and version: Chrome 89.0.4389.82
- Reproduction Repository: -

### Description:
Laravel Nova stores an unknown job_batch id in CallQueuedAction (job) class, causing Laravel Horizon to display a link to an unknown job_batch record.

There are two parts in this bug report: 

1) Laravel Nova stores a value for the batchId field in its Laravel\Nova\Actions\CallQueuedAction (job) class. 
The batchId is generated by calling the Str::orderedUuid() utility, in the queueForModels() method of the Laravel\Nova\Actions\DispatchAction class. 
Laravel Nova does not store a job_batch record in the job_batches table. 

2) Laravel Horizon checks if it can find the batchId field in the job payload, when navigating to a job detail screen (Laravel\Horizon\resources\js\screens\recentJobs\job.vue). If it finds the batchId field, a link to the batch detail screen will be added on the job detail screen. However, when clicking this link, an error occurs saying that the batch does not exist as Nova did not create one.

### Detailed steps to reproduce the issue on a fresh Nova installation:
1) Execute a Nova action that implements the ShouldQueue interface.
2) Go to the job detail screen of your Nova action, in Laravel Horizon (you will see a link to the batch detail screen)

**Comment by crynobone** [comment]
Laravel Nova batchId isn't compatible with Laravel Job Batching at the moment. 

The value is only relevant to `action_events`

**Comment by glamorous** [comment]
So it's a bug in Horizon than? Because Horizon thinks it's a batch and shows links for the batch, but it doesn't exists and gives exceptions/errors when navigating those hyperlinks.

**Comment by glamorous** [comment]
@crynobone any updates on this? Should there be an issue created for Laravel Horizon?

**Comment by crynobone** [comment]
There no progress on this, 2 different feature overlaps and I can't say it's a bug with Horizon because Horizon expecting to handle Laravel Job Batching and Nova been using `$batchId` way before Job Batching and changing it on 3.x would cause breaking change.

We only be looking at this for next series
