### ISSUE TITLE
Main dashboard is empty, cards are not displayed

### ISSUE THREAD

**Issue by wijourdil** [laravel/nova-issues#3291]
- Laravel Version: 8.33.0
- Nova Version: 3.22.0
- PHP Version: 7.4.16
- Database Driver & Version: 10.5.9-MariaDB
- Operating System and Version: macOS 11.2.3
- Browser type and version: Firefox 86

### Description:

Recently I noticed my main dashboard was empty. The cards were well displayed before, but at a moment (after an update I guess ? 🤷) the dashboard just started to show nothing.

I have tried to update nova resources with command `php artisan nova:publish --force` but it changed nothing
The only way I found to get my cards back on the main dashboard was to call the `Nova::copyDefaultDashboardCards()` method myself, like this :

```php
// app/Providers/NovaServiceProvider.php

public function boot()
{
    parent::boot();

    Nova::serving(function () {
        Nova::copyDefaultDashboardCards();
    });
}
```

The thing is, on a fresh install I don't have this issue, and I don't need to call the `Nova::copyDefaultDashboardCards()` method

**Comment by crynobone** [comment]
> The thing is, on a fresh install I don't have this issue, and I don't need to call the Nova::copyDefaultDashboardCards() method

Definitely need more info in order to replicate the issue.
