### ISSUE TITLE
Flex form for display with columns as most of the admin tools do

### ISSUE THREAD

**Issue by flyzard** [laravel/nova-issues#3293]
I was wondering if we could have a ` :class="this.classes"` (or something more nova idiomatic) in the `vendor/laravel/nova/resources/js/components/Form/Panel.vue` main element so that we could have a flexible layout, passing `->withMeta(['classes' => 'w-1/3'])` in the `Laravel\Nova\Panel`?

Of course, this wouldn't suffice, since the form (or the other parent element) would have to be flex or a grid. But I think this would be a nice feature for everyone, since almost all admin panels normally have two columns, one with the main info another with the secondary.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
