### ISSUE TITLE
Trix upload .pptx file as .bin to AWS S3

### ISSUE THREAD

**Issue by henryavila** [laravel/nova-issues#3295]
- Laravel Version: 8.33.1
- Nova Version: 3.22.0
- PHP Version: 8.0.3
- Operating System and Version: Ubuntu 20.04 | Windows 10 

### Description:
Uploading file via trix to AWS S3, if the file has some extensions, ex: .pprx, its uploaded as .bin

### Detailed steps to reproduce the issue on a fresh Nova installation:
```
Trix::make('Conteúdo', 'text')
    ->required()
    ->alwaysShow()
    ->withFiles(config('filesystems.cloud'))
    ->path($this->model()->getFilePath()),
```

While uploading files with this code, if the file has the extension `.pptx`, it's uploaded as `.bin`.
- Files like `.pdf` are uploaded correctly
- The files are uploaded to correct path
- the file is not corrupted. If i rename the uploaded `file.bin`  to `file.pptx` the content are unchanged.

**Comment by crynobone** [comment]
Unable to replicate the issue, I'm guessing you might be missing `fileinfo` extension.

![CleanShot 2021-03-22 at 14 18 01](https://user-images.githubusercontent.com/172966/111948219-cb870980-8b19-11eb-9050-2abe1a2c87fe.gif)

**Comment by crynobone** [comment]
Additional details, AWS S3 doesn't do any file renaming, everything is done at Laravel (with Nova) level. 

You also can debug this locally by testing against `File::guessExtension($pathToPptxFile)` to see the output on your application.

![image](https://user-images.githubusercontent.com/172966/112084398-ab138980-8bc3-11eb-9715-d6edbad31f64.png)

**Comment by henryavila** [comment]
Hi @crynobone. Thanks for the reply.
I made this test and its returning ` .bin`. See
![image](https://user-images.githubusercontent.com/8429941/112368600-032cb780-8cba-11eb-8b7b-4060ca3fb3b1.png)


Tomorrow I will  debug this function to see what is happening. Thanks for pointing the Direction!

**Comment by henryavila** [comment]
@crynobone I found the problem.
This behavior happens just with one file. I analyzed the file and it was generated from `LibreOffice`, not MS Office.

It's  still a problem, but it's not a Laravel Nova problem.

Thanks for the help.
