### ISSUE TITLE
The action modal freezes when the record has been removed by another user.

### ISSUE THREAD

**Issue by rvalenzuelaferrada** [laravel/nova-issues#3296]
- Laravel Version: 8.33.1
- Nova Version: 3.21.1
- PHP Version: 8.0

### Description:
When I execute an action with modal to send a message in a resource, if the resource was eliminated by another administrator user at the same time that I am writing the message in modal, after pressing the "run action" button it generates an error, but it does not redirect and it does not return a message, therefore the user does not know what happens.

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Create a resource and add an action with a text field
2. Press the button to execute the action and display the modal where you will write the text.
3. Don't close the modal. Log in to another browser and delete the resource on which the other user is executing the action.
4. Returns to the user who is typing in the modal and executes the action.

The expected behavior should be to return an error message "The record no longer exists or was deleted" and reload the index view from where the action is being executed to visualize that the record no longer exists.

![notfoundhttpexception](https://user-images.githubusercontent.com/32209726/111829433-76ee4f00-88cb-11eb-9f5a-34711d9baa5d.PNG)

**Comment by crynobone** [comment]
> The expected behavior should be to return an error message "The record no longer exists or was deleted" and reload the index view from where the action is being executed to visualize that the record no longer exists.

In step 2 of your reproducing step, do you select single action or run from the resource detail page?

**Comment by rvalenzuelaferrada** [comment]
In step two, you should use a standalone action and execute the action from the index view, I hope my answer was helpful.

**Comment by davidhemphill** [comment]
Would you consider using a validation rule to determine if the model is in a valid state?

**Comment by crynobone** [comment]
@rvalenzuelaferrada I added few dusk tests to verify this issue and none actually triggers 404 HTTP error as described above. Can you send a full reproducing code so we can move forward with this?
