### ISSUE TITLE
Vue DevTools, the webpack.mix.js.dist file is missing

### ISSUE THREAD

**Issue by soipo** [laravel/nova-issues#3297]
When following the documentation,

```
cd ./vendor/laravel/nova
mv webpack.mix.js.dist webpack.mix.js
npm install
npm run dev
rm -rf node_modules
cd -
php artisan nova:publish
```

I get 

mv: webpack.mix.js.dist: No such file or directory

This is the nova version  "laravel/nova": "~3.0",

I did not manage to get the vuedevtool  to run with the documentation.

Using this :

Add  to cd ./vendor/laravel/nova/webpack.mix.js

```
window.Vue.config.productionTip = false
window.Vue.config.devtools = true
```

```
cd ./vendor/laravel/nova
npm install
npm run dev
rm -rf node_modules
cd -
php artisan nova:publish
```

Worked for me

**Comment by crynobone** [comment]
I wonder if you tried to run `mv` more than once, which could cause `webpack.mix.js.dist` to be missing when you run it after the first time.

**Comment by soipo** [comment]
I didn't , I deleted the vendor folder
