### ISSUE TITLE
Not showing in Vue dev tools

### ISSUE THREAD

**Issue by OwenMelbz** [laravel/nova-issues#33]
I think this could potentially be closed easily if it's just me.

However currently when developing new nova components, and running `npm run watch` from within the component folder the Vue developer tools fails to detect Vue.

Is anybody else able to confirm if this is the same for them?

**Comment by alexbowers** [comment]
The reason for this is because you are not using the assets from within Nova itself, but a published version of the assets.

There is a `php artisan vendor:publish` for Nova, run that and see if that helps?

**Comment by vyuldashev** [comment]
Go to nova folder and run 

```bash
npm install
npm run dev
```

Then, run `nova:publish` in your application.

**Comment by OwenMelbz** [comment]
@vyuldashev seems to throw an error running `npm run dev`

```
➜ npm run dev

> @ dev /Users/owen/Sites/nova-playground/nova
> npm run development


> @ development /Users/owen/Sites/nova-playground/nova
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module '/Users/owen/Sites/nova-playground/nova/webpack.mix'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/owen/Sites/nova-playground/nova/node_modules/laravel-mix/setup/webpack.config.js:9:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/owen/.npm/_logs/2018-08-23T17_15_21_169Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/owen/.npm/_logs/2018-08-23T17_15_21_462Z-debug.log
```
looks like maybe it cannot find the webpack mix file?

**Comment by vyuldashev** [comment]
@bbrala yep, I forgot about this

**Comment by OwenMelbz** [comment]
So to summarise for anybody else

```
cd ./nova 
npm i
mv webpack.mix.js.dist webpack.mix.js
npm run dev
cd ../
php artisan nova:publish
```

This should put it into dev mode so you can use your dev tools! :)

Thanks for everybody's input!

**Comment by davidpiesse** [comment]
Has anyone else got this to work?
Followed the steps without any exceptions - but still forces prod mode...

**Comment by alg0rithmm** [comment]
@OwenMelbz after 'php artisan nova:publish`

I get the fallowing errors..

`vendor.js?id=ae8b15d6be7930cff9fb:92603 [Vue warn]: Property or method "currentFilters" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <ResourceIndex> at resources/js/views/Index.vue
       <Root>
warn @ vendor.js?id=ae8b15d6be7930cff9fb:92603
warnNonPresent @ vendor.js?id=ae8b15d6be7930cff9fb:93909
get @ vendor.js?id=ae8b15d6be7930cff9fb:93951
render @ app.js?id=b266027752dcefae6850:38735
Vue._render @ vendor.js?id=ae8b15d6be7930cff9fb:96554
updateComponent @ vendor.js?id=ae8b15d6be7930cff9fb:94798
get @ vendor.js?id=ae8b15d6be7930cff9fb:95152
run @ vendor.js?id=ae8b15d6be7930cff9fb:95229
flushSchedulerQueue @ vendor.js?id=ae8b15d6be7930cff9fb:94991
(anonymous) @ vendor.js?id=ae8b15d6be7930cff9fb:93847
flushCallbacks @ vendor.js?id=ae8b15d6be7930cff9fb:93768
Promise.then (async)
microTimerFunc @ vendor.js?id=ae8b15d6be7930cff9fb:93816
nextTick @ vendor.js?id=ae8b15d6be7930cff9fb:93860
queueWatcher @ vendor.js?id=ae8b15d6be7930cff9fb:95078
update @ vendor.js?id=ae8b15d6be7930cff9fb:95219
notify @ vendor.js?id=ae8b15d6be7930cff9fb:92709
reactiveSetter @ vendor.js?id=ae8b15d6be7930cff9fb:93026
proxySetter @ vendor.js?id=ae8b15d6be7930cff9fb:95310
(anonymous) @ app.js?id=b266027752dcefae6850:10491
Promise.then (async)
getLenses @ app.js?id=b266027752dcefae6850:10490
_callee$ @ app.js?id=b266027752dcefae6850:10311
tryCatch @ app.js?id=b266027752dcefae6850:32162
invoke @ app.js?id=b266027752dcefae6850:32396
prototype.(anonymous function) @ app.js?id=b266027752dcefae6850:32214
step @ app.js?id=b266027752dcefae6850:12822
(anonymous) @ app.js?id=b266027752dcefae6850:12833
Promise.then (async)
step @ app.js?id=b266027752dcefae6850:12832
(anonymous) @ app.js?id=b266027752dcefae6850:12833
Promise.then (async)
step @ app.js?id=b266027752dcefae6850:12832
(anonymous) @ app.js?id=b266027752dcefae6850:12840
F @ app.js?id=b266027752dcefae6850:28461
(anonymous) @ app.js?id=b266027752dcefae6850:12819
created @ app.js?id=b266027752dcefae6850:10357
callHook @ vendor.js?id=ae8b15d6be7930cff9fb:94931
Vue._init @ vendor.js?id=ae8b15d6be7930cff9fb:96640
VueComponent @ vendor.js?id=ae8b15d6be7930cff9fb:96808
createComponentInstanceForVnode @ vendor.js?id=ae8b15d6be7930cff9fb:96320
init @ vendor.js?id=ae8b15d6be7930cff9fb:96141
createComponent @ vendor.js?id=ae8b15d6be7930cff9fb:97618
createElm @ vendor.js?id=ae8b15d6be7930cff9fb:97565
patch @ vendor.js?id=ae8b15d6be7930cff9fb:98140
Vue._update @ vendor.js?id=ae8b15d6be7930cff9fb:94680
updateComponent @ vendor.js?id=ae8b15d6be7930cff9fb:94798
get @ vendor.js?id=ae8b15d6be7930cff9fb:95152
run @ vendor.js?id=ae8b15d6be7930cff9fb:95229
flushSchedulerQueue @ vendor.js?id=ae8b15d6be7930cff9fb:94991
(anonymous) @ vendor.js?id=ae8b15d6be7930cff9fb:93847
flushCallbacks @ vendor.js?id=ae8b15d6be7930cff9fb:93768
Promise.then (async)
microTimerFunc @ vendor.js?id=ae8b15d6be7930cff9fb:93816
nextTick @ vendor.js?id=ae8b15d6be7930cff9fb:93860
Vue.$nextTick @ vendor.js?id=ae8b15d6be7930cff9fb:96527
_callee$ @ app.js?id=b266027752dcefae6850:55064
tryCatch @ app.js?id=b266027752dcefae6850:32162
invoke @ app.js?id=b266027752dcefae6850:32396
prototype.(anonymous function) @ app.js?id=b266027752dcefae6850:32214
step @ app.js?id=b266027752dcefae6850:12822
(anonymous) @ app.js?id=b266027752dcefae6850:12833
Promise.then (async)
step @ app.js?id=b266027752dcefae6850:12832
(anonymous) @ app.js?id=b266027752dcefae6850:12840
F @ app.js?id=b266027752dcefae6850:28461
(anonymous) @ app.js?id=b266027752dcefae6850:12819
beforeEach @ app.js?id=b266027752dcefae6850:55080
iterator @ vendor.js?id=ae8b15d6be7930cff9fb:91315
step @ vendor.js?id=ae8b15d6be7930cff9fb:91089
runQueue @ vendor.js?id=ae8b15d6be7930cff9fb:91097
confirmTransition @ vendor.js?id=ae8b15d6be7930cff9fb:91344
transitionTo @ vendor.js?id=ae8b15d6be7930cff9fb:91246
init @ vendor.js?id=ae8b15d6be7930cff9fb:91866
beforeCreate @ vendor.js?id=ae8b15d6be7930cff9fb:89912
callHook @ vendor.js?id=ae8b15d6be7930cff9fb:94931
Vue._init @ vendor.js?id=ae8b15d6be7930cff9fb:96636
Vue @ vendor.js?id=ae8b15d6be7930cff9fb:96739
liftOff @ app.js?id=b266027752dcefae6850:48612
(anonymous) @ posts:166
vendor.js?id=ae8b15d6be7930cff9fb:92603 [Vue warn]: Property or method "currentFilters" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <ResourceIndex> at resources/js/views/Index.vue
       <Root>
warn @ vendor.js?id=ae8b15d6be7930cff9fb:92603
warnNonPresent @ vendor.js?id=ae8b15d6be7930cff9fb:93909
get @ vendor.js?id=ae8b15d6be7930cff9fb:93951
render @ app.js?id=b266027752dcefae6850:38735
Vue._render @ vendor.js?id=ae8b15d6be7930cff9fb:96554
updateComponent @ vendor.js?id=ae8b15d6be7930cff9fb:94798
get @ vendor.js?id=ae8b15d6be7930cff9fb:95152
run @ vendor.js?id=ae8b15d6be7930cff9fb:95229
flushSchedulerQueue @ vendor.js?id=ae8b15d6be7930cff9fb:94991
(anonymous) @ vendor.js?id=ae8b15d6be7930cff9fb:93847
flushCallbacks @ vendor.js?id=ae8b15d6be7930cff9fb:93768
Promise.then (async)
microTimerFunc @ vendor.js?id=ae8b15d6be7930cff9fb:93816
nextTick @ vendor.js?id=ae8b15d6be7930cff9fb:93860
queueWatcher @ vendor.js?id=ae8b15d6be7930cff9fb:95078
update @ vendor.js?id=ae8b15d6be7930cff9fb:95219
notify @ vendor.js?id=ae8b15d6be7930cff9fb:92709
reactiveSetter @ vendor.js?id=ae8b15d6be7930cff9fb:93026
proxySetter @ vendor.js?id=ae8b15d6be7930cff9fb:95310
getActions @ app.js?id=b266027752dcefae6850:10502
_callee$ @ app.js?id=b266027752dcefae6850:10315
tryCatch @ app.js?id=b266027752dcefae6850:32162
invoke @ app.js?id=b266027752dcefae6850:32396
prototype.(anonymous function) @ app.js?id=b266027752dcefae6850:32214
step @ app.js?id=b266027752dcefae6850:12822
(anonymous) @ app.js?id=b266027752dcefae6850:12833
Promise.then (async)
step @ app.js?id=b266027752dcefae6850:12832
(anonymous) @ app.js?id=b266027752dcefae6850:12833
Promise.then (async)
step @ app.js?id=b266027752dcefae6850:12832
(anonymous) @ app.js?id=b266027752dcefae6850:12833
Promise.then (async)
step @ app.js?id=b266027752dcefae6850:12832
(anonymous) @ app.js?id=b266027752dcefae6850:12840
F @ app.js?id=b266027752dcefae6850:28461
(anonymous) @ app.js?id=b266027752dcefae6850:12819
created @ app.js?id=b266027752dcefae6850:10357
callHook @ vendor.js?id=ae8b15d6be7930cff9fb:94931
Vue._init @ vendor.js?id=ae8b15d6be7930cff9fb:96640
VueComponent @ vendor.js?id=ae8b15d6be7930cff9fb:96808
createComponentInstanceForVnode @ vendor.js?id=ae8b15d6be7930cff9fb:96320
init @ vendor.js?id=ae8b15d6be7930cff9fb:96141
createComponent @ vendor.js?id=ae8b15d6be7930cff9fb:97618
createElm @ vendor.js?id=ae8b15d6be7930cff9fb:97565
patch @ vendor.js?id=ae8b15d6be7930cff9fb:98140
Vue._update @ vendor.js?id=ae8b15d6be7930cff9fb:94680
updateComponent @ vendor.js?id=ae8b15d6be7930cff9fb:94798
get @ vendor.js?id=ae8b15d6be7930cff9fb:95152
run @ vendor.js?id=ae8b15d6be7930cff9fb:95229
flushSchedulerQueue @ vendor.js?id=ae8b15d6be7930cff9fb:94991
(anonymous) @ vendor.js?id=ae8b15d6be7930cff9fb:93847
flushCallbacks @ vendor.js?id=ae8b15d6be7930cff9fb:93768
Promise.then (async)
microTimerFunc @ vendor.js?id=ae8b15d6be7930cff9fb:93816
nextTick @ vendor.js?id=ae8b15d6be7930cff9fb:93860
Vue.$nextTick @ vendor.js?id=ae8b15d6be7930cff9fb:96527
_callee$ @ app.js?id=b266027752dcefae6850:55064
tryCatch @ app.js?id=b266027752dcefae6850:32162
invoke @ app.js?id=b266027752dcefae6850:32396
prototype.(anonymous function) @ app.js?id=b266027752dcefae6850:32214
step @ app.js?id=b266027752dcefae6850:12822
(anonymous) @ app.js?id=b266027752dcefae6850:12833
Promise.then (async)
step @ app.js?id=b266027752dcefae6850:12832
(anonymous) @ app.js?id=b266027752dcefae6850:12840
F @ app.js?id=b266027752dcefae6850:28461
(anonymous) @ app.js?id=b266027752dcefae6850:12819
beforeEach @ app.js?id=b266027752dcefae6850:55080
iterator @ vendor.js?id=ae8b15d6be7930cff9fb:91315
step @ vendor.js?id=ae8b15d6be7930cff9fb:91089
runQueue @ vendor.js?id=ae8b15d6be7930cff9fb:91097
confirmTransition @ vendor.js?id=ae8b15d6be7930cff9fb:91344
transitionTo @ vendor.js?id=ae8b15d6be7930cff9fb:91246
init @ vendor.js?id=ae8b15d6be7930cff9fb:91866
beforeCreate @ vendor.js?id=ae8b15d6be7930cff9fb:89912
callHook @ vendor.js?id=ae8b15d6be7930cff9fb:94931
Vue._init @ vendor.js?id=ae8b15d6be7930cff9fb:96636
Vue @ vendor.js?id=ae8b15d6be7930cff9fb:96739
liftOff @ app.js?id=b266027752dcefae6850:48612
(anonymous) @ posts:166
vendor.js?id=ae8b15d6be7930cff9fb:92603 [Vue warn]: Property or method "currentFilters" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <ResourceIndex> at resources/js/views/Index.vue
       <Root>
warn @ vendor.js?id=ae8b15d6be7930cff9fb:92603
warnNonPresent @ vendor.js?id=ae8b15d6be7930cff9fb:93909
get @ vendor.js?id=ae8b15d6be7930cff9fb:93951
render @ app.js?id=b266027752dcefae6850:38735
Vue._render @ vendor.js?id=ae8b15d6be7930cff9fb:96554
updateComponent @ vendor.js?id=ae8b15d6be7930cff9fb:94798
get @ vendor.js?id=ae8b15d6be7930cff9fb:95152
run @ vendor.js?id=ae8b15d6be7930cff9fb:95229
flushSchedulerQueue @ vendor.js?id=ae8b15d6be7930cff9fb:94991
(anonymous) @ vendor.js?id=ae8b15d6be7930cff9fb:93847
flushCallbacks @ vendor.js?id=ae8b15d6be7930cff9fb:93768
Promise.then (async)
microTimerFunc @ vendor.js?id=ae8b15d6be7930cff9fb:93816
nextTick @ vendor.js?id=ae8b15d6be7930cff9fb:93860
queueWatcher @ vendor.js?id=ae8b15d6be7930cff9fb:95078
update @ vendor.js?id=ae8b15d6be7930cff9fb:95219
notify @ vendor.js?id=ae8b15d6be7930cff9fb:92709
reactiveSetter @ vendor.js?id=ae8b15d6be7930cff9fb:93026
proxySetter @ vendor.js?id=ae8b15d6be7930cff9fb:95310
(anonymous) @ app.js?id=b266027752dcefae6850:10505
Promise.then (async)
getActions @ app.js?id=b266027752dcefae6850:10504
_callee$ @ app.js?id=b266027752dcefae6850:10315
tryCatch @ app.js?id=b266027752dcefae6850:32162
invoke @ app.js?id=b266027752dcefae6850:32396
prototype.(anonymous function) @ app.js?id=b266027752dcefae6850:32214
step @ app.js?id=b266027752dcefae6850:12822
(anonymous) @ app.js?id=b266027752dcefae6850:12833
Promise.then (async)
step @ app.js?id=b266027752dcefae6850:12832
(anonymous) @ app.js?id=b266027752dcefae6850:12833
Promise.then (async)
step @ app.js?id=b266027752dcefae6850:12832
(anonymous) @ app.js?id=b266027752dcefae6850:12833
Promise.then (async)
step @ app.js?id=b266027752dcefae6850:12832
(anonymous) @ app.js?id=b266027752dcefae6850:12840
F @ app.js?id=b266027752dcefae6850:28461
(anonymous) @ app.js?id=b266027752dcefae6850:12819
created @ app.js?id=b266027752dcefae6850:10357
callHook @ vendor.js?id=ae8b15d6be7930cff9fb:94931
Vue._init @ vendor.js?id=ae8b15d6be7930cff9fb:96640
VueComponent @ vendor.js?id=ae8b15d6be7930cff9fb:96808
createComponentInstanceForVnode @ vendor.js?id=ae8b15d6be7930cff9fb:96320
init @ vendor.js?id=ae8b15d6be7930cff9fb:96141
createComponent @ vendor.js?id=ae8b15d6be7930cff9fb:97618
createElm @ vendor.js?id=ae8b15d6be7930cff9fb:97565
patch @ vendor.js?id=ae8b15d6be7930cff9fb:98140
Vue._update @ vendor.js?id=ae8b15d6be7930cff9fb:94680
updateComponent @ vendor.js?id=ae8b15d6be7930cff9fb:94798
get @ vendor.js?id=ae8b15d6be7930cff9fb:95152
run @ vendor.js?id=ae8b15d6be7930cff9fb:95229
flushSchedulerQueue @ vendor.js?id=ae8b15d6be7930cff9fb:94991
(anonymous) @ vendor.js?id=ae8b15d6be7930cff9fb:93847
flushCallbacks @ vendor.js?id=ae8b15d6be7930cff9fb:93768
Promise.then (async)
microTimerFunc @ vendor.js?id=ae8b15d6be7930cff9fb:93816
nextTick @ vendor.js?id=ae8b15d6be7930cff9fb:93860
Vue.$nextTick @ vendor.js?id=ae8b15d6be7930cff9fb:96527
_callee$ @ app.js?id=b266027752dcefae6850:55064
tryCatch @ app.js?id=b266027752dcefae6850:32162
invoke @ app.js?id=b266027752dcefae6850:32396
prototype.(anonymous function) @ app.js?id=b266027752dcefae6850:32214
step @ app.js?id=b266027752dcefae6850:12822
(anonymous) @ app.js?id=b266027752dcefae6850:12833
Promise.then (async)
step @ app.js?id=b266027752dcefae6850:12832
(anonymous) @ app.js?id=b266027752dcefae6850:12840
F @ app.js?id=b266027752dcefae6850:28461
(anonymous) @ app.js?id=b266027752dcefae6850:12819
beforeEach @ app.js?id=b266027752dcefae6850:55080
iterator @ vendor.js?id=ae8b15d6be7930cff9fb:91315
step @ vendor.js?id=ae8b15d6be7930cff9fb:91089
runQueue @ vendor.js?id=ae8b15d6be7930cff9fb:91097
confirmTransition @ vendor.js?id=ae8b15d6be7930cff9fb:91344
transitionTo @ vendor.js?id=ae8b15d6be7930cff9fb:91246
init @ vendor.js?id=ae8b15d6be7930cff9fb:91866
beforeCreate @ vendor.js?id=ae8b15d6be7930cff9fb:89912
callHook @ vendor.js?id=ae8b15d6be7930cff9fb:94931
Vue._init @ vendor.js?id=ae8b15d6be7930cff9fb:96636
Vue @ vendor.js?id=ae8b15d6be7930cff9fb:96739
liftOff @ app.js?id=b266027752dcefae6850:48612
(anonymous) @ posts:166
app.js?id=b266027752dcefae6850:10524 Uncaught (in promise) TypeError: _this6.initializeFilterValuesFromQueryString is not a function
    at app.js?id=b266027752dcefae6850:10524`

**Comment by alg0rithmm** [comment]
@OwenMelbz after `php artisan nova:publish`

When I open the Dashboard of my Nova app there are no errors but when I open a Resource I get the fallowing errors...

```[Vue warn]: Property or method "currentFilters" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties
found in
---> <ResourceIndex> at resources/js/views/Index.vue
       <Root>
[Vue warn]: Property or method "currentFilters" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
found in
---> <ResourceIndex> at resources/js/views/Index.vue
       <Root>

[Vue warn]: Property or method "currentFilters" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <ResourceIndex> at resources/js/views/Index.vue
       <Root>

app.js?id=b266027752dcefae6850:10524 Uncaught (in promise) TypeError: _this6.initializeFilterValuesFromQueryString is not a function

**Comment by aramirez92** [comment]
> @OwenMelbz after `php artisan nova:publish`
> 
> When I open the Dashboard of my Nova app there are no errors but when I open a Resource I get the fallowing errors...
> 
> ```
> found in
> ---> <ResourceIndex> at resources/js/views/Index.vue
>        <Root>
> [Vue warn]: Property or method "currentFilters" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
> found in
> ---> <ResourceIndex> at resources/js/views/Index.vue
>        <Root>
> 
> [Vue warn]: Property or method "currentFilters" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
> 
> found in
> 
> ---> <ResourceIndex> at resources/js/views/Index.vue
>        <Root>
> 
> app.js?id=b266027752dcefae6850:10524 Uncaught (in promise) TypeError: _this6.initializeFilterValuesFromQueryString is not a function
> ```

Have you ever solved the issue?

**Comment by OwenMelbz** [comment]
Nope sorry, it worked from when I originally posted.

However all the recent updates that have been released *might* not work.

Somebody might need to post new instructions, we’re not using nova for anything anymore so haven’t needed to revisit

**Comment by Krato** [comment]
@OwenMelbz See here: https://gist.github.com/Krato/b3f5891b917dadeb696b4aa36dda06d4

**Comment by Dixens** [comment]
Late to the party but for me adding `Vue.config.devtools = true` to `Nova.booting((Vue, router, store)` in nova-components/My-Component/resources/js/tool.js (and disabling it conditionally with a `process.env.NODE_ENV === 'production'` check) did the trick.

**Comment by chrillep** [comment]
> Late to the party but for me adding `Vue.config.devtools = true` to `Nova.booting((Vue, router, store)` in nova-components/My-Component/resources/js/tool.js (and disabling it conditionally with a `process.env.NODE_ENV === 'production'` check) did the trick.
This should be default setting when generating a tool @davidhemphill

**Comment by ramirespoa** [comment]
check you environment config requirements for version of laravel nova you are using:

https://nova.laravel.com/docs/3.0/installation.html#requirements
