### ISSUE TITLE
[Feature Request] Customize relationship loading on details view

### ISSUE THREAD

**Issue by chescos** [laravel/nova-issues#330]
It's great that you can view the relationships of a model in the details view. But there are situations when it becomes an issue that all relationships are loaded automatically and without any navigation.

Example: My `User` model has more than 20 relationships. I'd love to add them all to my `User` resource so that I can browse them in the details view of my `User` resource. But since they are all automatically loaded when I open up the details view, the loading times are unnecessarily long and it's a pain to scroll through them all.

What I would propose is to be able to add relationships to a drop-down menu in the details view. Initially, no relationship is selected. Upon selection, the relationship is loaded and displayed. When you select a different relationship, the previous relationship is hidden and the newly select relationship is displayed. This would eliminate both the scrolling issue and the loading time issue, and it would be a great experience to browse through any number of relationships.

**Comment by shirshak55** [comment]
I think we can implement that drop down if there is relationship more than 5 I guess otherwise dropdown switching can be pain isn't it

Nice idea by the way

**Comment by chescos** [comment]
@shirshak55 That sounds great! If you don't want to force the relationship to be on the drop-down at a maximum (e.g 5), you could also add a method like `separateFromDropdown` on the field class.

**Comment by chescos** [comment]
There's now a package for this: https://github.com/eminiarts/nova-relationship-selector

I still hope it gets added to Nova though as this is a basic feature that's necessary for big projects.

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
