### ISSUE TITLE
Default search should be case insentitive with json field

### ISSUE THREAD

**Issue by keizah7** [laravel/nova-issues#3303]
#509 The issue is still present if you search onto json columns.

**Comment by crynobone** [comment]
Hi there. Unfortunately, this requires a huge refactor to search query as JSON field is strictly case-sensitive. However, we also looking at the possibility of improving the search-related query for the next series, and this one of the areas we can improve.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
