### ISSUE TITLE
delete on nova action resource will not show what resource is deleted

### ISSUE THREAD

**Issue by anditsung** [laravel/nova-issues#3313]
laravel: 8
nova : 3

<img width="1083" alt="Screen Shot 2021-03-31 at 11 36 19" src="https://user-images.githubusercontent.com/1090413/113091112-72079480-9215-11eb-80bd-aada9ee667d1.png">
<img width="1073" alt="Screen Shot 2021-03-31 at 11 35 36" src="https://user-images.githubusercontent.com/1090413/113091116-759b1b80-9215-11eb-840b-02e4aa4f27de.png">

as the title.
the action did not record any deleted resource. it just show the user deleting something but dont know that it is.

**Comment by crynobone** [comment]
This has been fixed in 3.23.0 but please upgrade to 3.23.1. https://nova.laravel.com/releases
