### ISSUE TITLE
Please add to the documentation how to add builtin components from laravel nova.

### ISSUE THREAD

**Issue by BroJenuel** [laravel/nova-issues#3320]
The problem is I dont know what components to use on my tool page, I have to scramble the internet just to find this components. example is the trix-editor component. and other components.. hoping that it will be added on the documentation..

also the styles of button and others. So that it will be consistent when creating new page or tools . thanks :)

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
