### ISSUE TITLE
BelongsToMany: adds hyphen between 2 word model like this App\Course::long-features()

### ISSUE THREAD

**Issue by rbijkercom** [laravel/nova-issues#3322]
- Laravel Version: 8.35.1
- Nova Version: 3.22.0
- PHP Version: 7.4
- Database Driver & Version: mysql
- Operating System and Version: Mac OS 11.2.3
- Browser type and version: Chrome 89.0.4389.114
- Reproduction Repository: https://github.com/###/###

### Description:
I have a model "Course" with a relationship `BelongsToMany::make('LongFeatures')`
When attaching a new LongFeature Nova gives an error
`Call to undefined method App\Course::long-features()`
but is should be looking for `App\Course::longFeatures()` instead.
How do I get Nova to attach this longFeature correctly?

### Detailed steps to reproduce the issue on a fresh Nova installation:
Model Course.php has this relationship
```
public function longFeatures()
{
  return $this->belongsToMany( LongFeature::class, 'long_feature_course', 'course_id')
    ->using( LongFeatureCourse::class)->orderBy( 'sort_order' );
}
```
As a Nova resource I have Nova/Course.php with this relationship:
`BelongsToMany::make('LongFeatures')`

In Nova, on the Course resource view, I can see the related longFeatures correctly.
<img width="990" alt="Screenshot 2021-04-03 at 12 06 41" src="https://user-images.githubusercontent.com/4490603/113487934-2249f700-94bb-11eb-9363-7be41d12b3df.png">

But when trying to attach a new longFeature I get this error:
`Call to undefined method App\Course::long-features()`

I get the error on the page where it is trying to attach the model:
`/nova/resources/courses/1/attach/long-features?viaRelationship=longfeatures&polymorphic=0`
<img width="1235" alt="Screenshot 2021-04-03 at 12 04 39" src="https://user-images.githubusercontent.com/4490603/113487933-20803380-94bb-11eb-9d1c-c16396e7d9db.png">

So it is putting a hyphen between the 2 words. It's looking for `App\Course::long-features()`, but it should look `App\Course::longFeatures()`

I've already tried this without luck:
`BelongsToMany::make('LongFeatures', 'longFeatures', 'App\Nova\LongFeature'),`

**Comment by crynobone** [comment]
Using below should solve your issue:

```php
BelongsToMany::make('LongFeatures', 'longFeatures')
```
