### ISSUE TITLE
Using below should solve your issue:

### ISSUE THREAD

**Issue by rbijkercom** [laravel/nova-issues#3325]
Using below should solve your issue:

```php
BelongsToMany::make('LongFeatures', 'longFeatures')
```

_Originally posted by @crynobone in https://github.com/laravel/nova-issues/issues/3322#issuecomment-813019511_

Unfortunately that doesn't work. It keeps added the hyphen between the 2 words.
`Call to undefined method App\Course::long-features()`
When I change the model name to 1 word `Feature` with relationship `features` the problem is solved. 
This would mean BelongsToMany Nova relationships with models that have 2 words like `LongFeature` don't work. Could you try? 
Maybe there is another solution, otherwise I think it's a bug. Agree?
Thank you for your help!

**Comment by crynobone** [comment]
My reply because I have tried it, and Nova itself have tests covering this options

**Comment by rbijkercom** [comment]
> My reply because I have tried it, and Nova itself have tests covering this options

Thanks for the quick reply. I accidentally created a new issue. You can delete this issue is you have permission to do so. 👍
