### ISSUE TITLE
v3.23.0 not in composer repo

### ISSUE THREAD

**Issue by bashgeek** [laravel/nova-issues#3328]
Was wondering why my app isn't updating Nova to v3.23.0, turns out it's not listed in the Composer repo (as documented here: https://nova.laravel.com/docs/3.0/installation.html#installing-nova-via-composer), v3.22.0 is still the latest version in there.

**Comment by crynobone** [comment]
Hi @bashgeek 

We are aware of the issue and currently working on it. Please wait for 3.23.1 or above because there's few issue with the current release:

* `laravel-nova` 1.10.0 release missing `mapProps` function causing Nova not to loads properly. 
* Satis server not updating with new version.

**Comment by milewski** [comment]
For me I get a runtime javascript error after installing it... It doesn't load at all.. all I can see is a blank page

**Comment by crynobone** [comment]
@bashgeek @milewski Please upgrade to 3.23.1, all above issues should be solved.

**Comment by bashgeek** [comment]
Works now, thanks!
