### ISSUE TITLE
File field inside of creation modal

### ISSUE THREAD

**Issue by lisotton** [laravel/nova-issues#3329]
- Laravel Version: 6.20.20
- Nova Version: 2.12.0
- PHP Version: 7.4.16
- Database Driver & Version:
- Operating System and Version: Debian Buster
- Browser type and version: Firefox 87.0

### Description:
When have a field of type `BelongsTo` with option `->showCreateRelationButton()` and inside of the modal there is a field of type `File` with the same column name as outside of the modal, when the file is selected, the modal is closed and the file is populated in the field outside of the modal.

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Create a model called `Podcast` with a column named `file`
- Create a model called `Image` with a column named `file`
- Create a relationship between `Podcast` and `Image` (`Podcast` belongs to `Image`), so the `podcasts` table will have a column `image_id`.
- Create a Nova Resource for `Image`.
- Create a Nova Resource for `Podcast` and add:
```
BelongsTo::make('Image', 'image', 'App\Nova\Ĩmage')
    ->showCreateRelationButton()
    ->hideFromIndex();
```
- Open Nova and click in button "Create" and try to select a file inside of the modal, you will see that the modal will be closed and the file will be populated for `file` for `Podcast`, not for `Image`.

**Comment by crynobone** [comment]
This has been fixed in Nova 3.

Unfortunately we no longer release fix for v2, please upgrade to v3 as soon as possible.
