### ISSUE TITLE
[Enhancement proposal] Hidding the "With Trashed" checkbox

### ISSUE THREAD

**Issue by laraning** [laravel/nova-issues#333]
I am using soft deletes on a model, but when I am refering that relationship I would like to hide the "With Trashed"checkbox from the Edit form.

Reason is I don't want the end user to understand this concept, but I still want to have soft deletes on the Model.

Maybe something like:

```php
BelongsTo::make('VehicleType', 'type')
                ->disableTrash()
```

Is there a way to do it?

![image](https://user-images.githubusercontent.com/35408392/44819175-35520780-abec-11e8-891e-d3afad28b893.png)

Thank you for the help!

**Comment by bobinrinder** [comment]
Totally agreed, we use soft deletes in a lot of places but the average user does not (need to) understand the concept and it would be good to hide it for them.
To be flexible with permissions I would rather hope for a 
```
BelongsTo::make('VehicleType', 'type')
                ->showWithTrashed(auth()->user()->isSuperAdmin())
```
that defaults to `true` or `false` if not given obviously

**Comment by stonkeep** [comment]
Some solution?

**Comment by dillingham** [comment]
+1 Im using soft deletes as an admin feature to catch any user mistakes

Would be cool as a global config option in the NovaServiceProvider

```
Gate::define('viewNova', function ($user) {});
Gate::define('viewSoftDeletes', function ($user) {});
```

**Comment by dkulyk** [comment]
Better to use the withTrashed ability in the policy for each resource. 
This way you can issue permissions for each model separately.

In the my resource(I inherit base resource) I use this:
```php
    public static function softDeletes()
    {
        return (static::authorizable() ? Gate::check('withTrashed',
                [static::newModel()]) : true) && parent::softDeletes();
    }
```

**Comment by waygou** [comment]
Works like a charm, thanks!

**Comment by davidhemphill** [comment]
Closing as the solution was posed above.

**Comment by skalero01** [comment]
What if i'd like to hide the withTrashed option only on the edit page? I dont want to hide the filter, does somebody know? :D

**Comment by davidhemphill** [comment]
You could potentially check the current URI using the `request()` helper, but it'd be a bit of a workaround.

**Comment by bkilshaw** [comment]
Is it not possible to chain a ->hideWithTrashed() like we do with ->hideFromIndex() ?

**Comment by loveyuxiao** [comment]
hope add disableTrashed(true|false) just like R64\NovaFields\BelongsTo

**Comment by briavers** [comment]
This worked for me. (guess it was added into nova) so I'll leave it here for others who might find this thread
```
BelongsTo::make('order')
    ->withoutTrashed(),
```

**Comment by didix16** [comment]
@briavers but not on BelongsToMany ... I hope they add also in BelongsToMany too.

**Comment by tpetry** [comment]
@didix16 At the moment you can just hide it with some custom css in your `meta.blade.php`:

```html
<style>
    label[dusk$="with-trashed-checkbox"] {
        display: none;
    }
</style>
```

**Comment by didix16** [comment]
@tpetry ok thanks. I'll use it till they add the functionality for BelongsToMany.

**Comment by genesiscz** [comment]
Any news?

**Comment by KiddoLin** [comment]
Hi~ The BelongsToMany field has not withoutTrashed method, how to filter the pivot that use SoftDeletes? thx~
nova version: v2.9.3

**Comment by ricardov03** [comment]
> +1 Im using soft deletes as a super admin feature to catch any admin mistakes
> 
> Here it is as a global config option in the NovaServiceProvider
> 
> ```
> Gate::define('viewNova', function ($user) {});
> Gate::define('canSoftDelete', function ($user) {});
> ```
> 
> in Resource.php
> 
> ```
> public static function softDeletes()
> {
>     if (\Gate::check('canSoftDelete')) {
>         return parent::softDeletes();
>     }
> 
>     return false;
> }
> ```

Thanks, this option work great for me.

**Comment by ricardov03** [comment]
> Better to use the withTrashed ability in the policy for each resource.
> This way you can issue permissions for each model separately.
> 
> In the my resource(I inherit base resource) I use this:
> 
> ```
>     public static function softDeletes()
>     {
>         return (static::authorizable() ? Gate::check('withTrashed',
>                 [static::newModel()]) : true) && parent::softDeletes();
>     }
> ```

@dkulyk I'm relative new on Nova but a fast learner, I really want to understand your solution, looks simpler but it doesn't work for me when I try to use it.

**Comment by genesiscz** [comment]
> > Better to use the withTrashed ability in the policy for each resource.
> > This way you can issue permissions for each model separately.
> > In the my resource(I inherit base resource) I use this:
> > ```
> >     public static function softDeletes()
> >     {
> >         return (static::authorizable() ? Gate::check('withTrashed',
> >                 [static::newModel()]) : true) && parent::softDeletes();
> >     }
> > ```
> 
> @dkulyk I'm relative new on Nova but a fast learner, I really want to understand your solution, looks simpler but it doesn't work for me when I try to use it.

What field do you want to put this on?

**Comment by ricardov03** [comment]
I'm using the solution shown by @dillingham. I would like to understand how can I use instead my Policy File to do the same job and without touch the core files of Nova.

This is my current configuration:
**File:** _NovaServiceProvider.php_
```php
        Gate::define('canSoftDelete', function ($user) {
            return $user->is_admin();
        });
```

**File:** _NovaServiceProvider.php_
```php
    public static function softDeletes()
    {
        if (\Gate::check('canSoftDelete')) {
            return parent::softDeletes();
        }

        return false;
    }
```

I would like to use just the Policy file of my Model to do the same.

**Comment by LiamKarlMitchell** [comment]
Looking for a way to do this in nova 4, so far I'm using a variable to store the field and running withoutTrashed()
```php
        $categorySelect = BelongsTo::make('Category', 'category', 'App\Nova\Category')
            ->rules('required')
            // Default to Main category.
            ->withMeta([
                "belongsToId" => 2,
            ])
            ->relatableQueryUsing(function (NovaRequest $request, Builder $query) {
                $query->whereIsPublished(true)->orderBy('sort_order', 'asc');
            })->dontReorderAssociatables()
            ->sortable()
            ->filterable()
            ->help("If you feel a new category is required please contact our support.");

        if (!$user->is_admin) {
            $categorySelect->withoutTrashed();
        }
```
If the withoutTrashed had a parameter defaulting to true might be nicer.
```php
    /**
     * hides the "With Trashed" option.
     * bool|null $value
     * @return $this
     */
    public function withoutTrashed($value=true)
    {
        $this->displaysWithTrashed = $value;

        return $this;
    }
    ```

**Comment by evelynDickinson** [comment]
// --- INDEX & DETAIL: Display History Correctly ---
            // Uses your 'participantTrashed' relationship to show names even if deleted.
            BelongsTo::make('Participant', 'participantTrashed', Participant::class)
                ->exceptOnForms()
                ->sortable(),

            // --- FORM: Hidden Checkbox, But Includes Trashed ---
            BelongsTo::make('Participant', 'participant', Participant::class)
                ->onlyOnForms()
                ->withoutTrashed() // 1. This HIDES the "With Trashed" checkbox UI
                ->relatableQueryUsing(function (NovaRequest $request, $query) {
                    // 2. This FORCES deleted records to appear in the dropdown anyway
                    return $query->withTrashed();
                }),
