### ISSUE TITLE
Search with scout when filters are active seems to be broken

### ISSUE THREAD

**Issue by lenssoft** [laravel/nova-issues#3334]
- Laravel Version: 8.36.§
- Nova Version: 3.22.0
- PHP Version: 7.4.9
- Database Driver & Version: mysql / 8.0.21
- Operating System and Version: macOS 11.2.3
- Browser type and version: Chrome

### Description:
Search results are not displayed when a filter is active
Reson: ResourceIndexController: response->resources is not an array becuase some models get filtered out from search result. This causes ResourceTable.vue component not render the table (expects an array for resources)

We are using elastic for scout - SCOUT_DRIVER=Matchish\ScoutElasticSearch\Engines\ElasticSearchEngine

As a temporary fix I had to override the newCollection method on searchable models

```php
/**
     * Create a new Eloquent Collection instance and ignores the keys.
     *
     * @param  array  $models
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function newCollection(array $models = [])
    {
        $collection = parent::newCollection($models);
        return $collection->values();
    }
```

**Comment by crynobone** [comment]
> response->resources is not an array becuase some models get filtered out from search result.

Scout should get result ids and then it will query using Eloquent will query whereIn ids + filters queries. 

I failed to follow why response `resources` isn't an array? cause it's would come from Eloquent, or how filter 

---------------

I would think it best if you can share full reproducing code to replicate the problem

**Comment by crynobone** [comment]
It seems to be the ElasticSearchEngine returning slightly different structure that expected.
