### ISSUE TITLE
 v3.9.4 upgrade latest version failed

### ISSUE THREAD

**Issue by lifeblood** [laravel/nova-issues#3337]
Current version is v3.9.4
then 
composer update 
![image](https://user-images.githubusercontent.com/3621748/114120724-9fdc8f80-991f-11eb-93f6-2eaed9b3b8b7.png)

**Comment by crynobone** [comment]
That's just warning. Nothing to worry about.

**Comment by lifeblood** [comment]
> That's just warning. Nothing to worry about.

But the result of the problem is not to upgrade to the latest version

**Comment by crynobone** [comment]
Can you share the output of `composer why-not "laravel/nova:v3.32.1"` and `composer show`

**Comment by lifeblood** [comment]
![image](https://user-images.githubusercontent.com/3621748/114188533-d0eaad80-997b-11eb-8274-fda8901b5db3.png)
