### ISSUE TITLE
Action Event Log should show the fields that were sent through the action

### ISSUE THREAD

**Issue by jchandler** [laravel/nova-issues#3338]
When I make a model `Actionable` and then attach an action with a field to that model, it saves the details all correctly in the database.  But when I go to look at the Action Log itself, it doesn't show me the value of the fields that were entered.  

The action that I'm doing has a dropdown with six options.  So in this case, the Action Event Log is useless for my users, because if they can't see the value of the dropdown, then what the action did is very unclear.

I can work around this by defining six different actions, but I'd rather not do that.  And I think this could be useful in many other action log situations.  

For now, I've just added the following line in ActionResource.php::fields()
`Text::make(__('Action Fields'), 'fields'),`

It's ugly, but functional.  I would request something that unserializes the `fields` column and displays it nicely on the Action Log Details.  Thank you!

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/114139260-67e64400-9941-11eb-8b45-a53c400c984f.png)

The field data is stored as `serialize()` data. You can override the default `ActionResource` via nova config if you have this requirement.
