### ISSUE TITLE
BelongsTo foreign key isn't considered as BigInt

### ISSUE THREAD

**Issue by paulgokk** [laravel/nova-issues#3339]
- Laravel Version: 8.36.2
- Nova Version: 3.23.1
- PHP Version:  7.4.13
- Database Driver & Version: MySQL 5.7
- Operating System and Version: MacOS Big Sur 11.2.3
- Browser type and version: Google Chrome 89

### Description:
When Nova loads relations on create/edit view, their IDs are not BigInt (they are rounded). As a result, Laravel can’t associate the relation with the model.
I am using *asBigInt()* on ID for Company and Employee resources.

### Detailed steps to reproduce the issue on a fresh Nova installation:
It's enough to create two models/resources. For example, Company and Employee. An Employee has *company_id* foreign key (BelongsTo relation).
When I create an Employee, Nova loads Company relation (*/nova-api/employees/associatable/company*). Companies IDs return rounded (with zeros at the end) from this query. Ok, I can choose a related Company in the UI, but I can't save it — Laravel can not associate a relation with the model.

**Comment by paulgokk** [comment]
Attached demonstration screen record

https://user-images.githubusercontent.com/4935888/114158601-89d5cb80-992d-11eb-98f1-fa238f16e994.mp4

**Comment by crynobone** [comment]
This has been fixed in v3.23.2
