### ISSUE TITLE
View button not working on HasMany field

### ISSUE THREAD

**Issue by rahilpeerbits** [laravel/nova-issues#3340]
- Laravel Version: 6.20.18
- Nova Version: 2.12.0
- PHP Version: 7.3.8
- Operating System and Version: Ubuntu 16
- Browser type and version: Chrome

While browsing HasMany field with view button which redirects to 404 page. It doesn't generate a valid view URL.

User Model
```
public function userDevices()
    {
        return $this->hasMany(UserDevice::class, 'user_id');
    }
```

Nova Resource
`HasMany::make('Users', 'userDevices', DeviceUsers::class)`

![image](https://user-images.githubusercontent.com/57667066/114506092-efd49280-9c4e-11eb-972c-d154dcbe86c9.png)

**View button on the above image redirects to `http://localhost/nova`. It should redirect to the respective user's detail page.**

**Comment by crynobone** [comment]
Laravel Nova 2 no longer received any bug fixes, please upgrade to Nova 3 as soon as possible.

I checked this on Nova 3 and the link works fine.
