### ISSUE TITLE
Partition Metrics failed calc % with number > 1000 (with format mask)

### ISSUE THREAD

**Issue by massimodellarovere** [laravel/nova-issues#3342]
- Laravel Version: 3.23.1
- Nova Version: 8.37.0
- PHP Version: 7.4.3
- Database Driver & Version: MySQL 5.7
- Operating System and Version: Ubuntu 20.04.2 LTS
- Browser type and version: Chrome 89.0.4389.114

### Description:

![Captura de pantalla_área-de-selección_20210413125934](https://user-images.githubusercontent.com/5731295/114599426-b143d580-9c58-11eb-91a7-da8937d4d63d.png)

### Detailed steps to reproduce the issue on a fresh Nova installation:

First two Metric OK because value is 652. If value is >= 1000 failed

**Comment by crynobone** [comment]
This has been fixed in v3.23.2
