### ISSUE TITLE
Thousand separators missing in Currency field

### ISSUE THREAD

**Issue by horaceho** [laravel/nova-issues#335]
Nova 1.0.8
````
Currency::make('Initial Deposit')->hideFromIndex(),
````
Output:
![initial deposit](https://user-images.githubusercontent.com/6657/44826439-9f48cc00-ac41-11e8-8d8d-39dbec81e76f.png)
Expected "490,815.00", but thousand separator is missing.

**Comment by horaceho** [comment]
Seems to be caused by missing: ````setlocale(LC_MONETARY, "en_US");````...

**Comment by Jam0r85** [comment]
I'm also having this issue, including no currency symbol showing.

In comparison using the exact same format and number somewhere else using money_format displays the amount correctly.

`
money_format('%.2n', $this->entity->getLettingFeeWithDiscount() / 100);
returns £250.00
`

in nova
`
            Currency::make(__('Rent'), 'current_rent_amount')
                ->format('%.2n')
                ->exceptOnForms()
                ->resolveUsing(function ($value) {
                    return $value / 100;
                })->displayUsing(function ($value) {
                    return $value / 100;
                }),

returns 900
`

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
