### ISSUE TITLE
Update and Continue Editing results in 404 error if id (primary key) is changed

### ISSUE THREAD

**Issue by AforDesign** [laravel/nova-issues#3350]
- Laravel Version: 7.30.4
- Nova Version: 3.23.1
- PHP Version: 7.4.1
- Database Driver & Version: MySQL 5.7.26
- Operating System and Version: MacOS 10.14.6
- Browser type and version: Firefox 87.0

### Description:
When I change the value of the primary key in the resource and press the 'update & continue editing' button, it redirects to the route/url with the old value, resulting in a 404 error.

### Additional information:
I'm pretty sure this wasn't an issue in the past, so my guess it's a bug due to a recent change.
The 'update' button still works and does redirect to the updated value.

**Comment by crynobone** [comment]
Which version did you upgrade it from?

**Comment by AforDesign** [comment]
I did update very recently for the higly needed 'allowDuplicateRelations' option on the belongstomany relation.
Before that I was working on v3.21.1 

I update on a regular base so I couldn't tell you the last version it was still working in.
I'm pretty sure it still worked 1-2 months ago at max.

**Comment by crynobone** [comment]
If that the case can you make a reproducing repository in order to replicate the issue

**Comment by AforDesign** [comment]
I'm sorry, but I can't.

I know you're trying to help and really could use this, but it's currently not an option for me.
What I can do, is rolling back a few commits to try to pinpoint at what stage this started and make a step by step instruction how to reproduce this.

Atm I'm very short on time, but the steps I would try to test if it reproduces this error is:

1. Clean install of latest Laravel 7 version
2. Install latest Nova package
3. Create new model with the id set to the type String
4. Create a Nova Resource for this model
5. Add a new model with an id of 'Old id'
6. Then update this model and change the id to 'New id'
7. Click on the 'update & continue editing' button to confirm the change

**Comment by crynobone** [comment]
can you share code example of 5 and 6?

**Comment by AforDesign** [comment]
Hi Crynobone,

I use the default create button on the resource page.
So there's no custom code involved.

The code for the id-field itself is:

`            Text::make('id')
                ->sortable()
                ->hideFromIndex(function (ResourceIndexRequest $request) {
                    return $request->viaRelationship();
                })
            ,`

**Comment by crynobone** [comment]
Fixed in [v3.24.0 release](https://nova.laravel.com/releases/3.24.0).
