### ISSUE TITLE
Route [nova.index] not defined.

### ISSUE THREAD

**Issue by cinemapub** [laravel/nova-issues#3351]
- Laravel Version: 8.36.2
- Nova Version: 3.23.1
- PHP Version: 8.0.3
- Database Driver & Version: mySQL
- Operating System and Version: Linux (via Laravel Sail)
- Browser type and version: Chrome

### Description:
when I want to use `route('nova.index')` in a Blade file, it gives me the error "Route [nova.index] not defined."
In the same file I also use `route('horizon.index')` and `route('nova.logout')`, and they work as expected.
When I list all routes with `php artisan route:list --columns=name,uri,method | grep index` I get both Horizon and Nova indexes listed as being registered:
```
| GET|HEAD | horizon/{view?}                                                                            | horizon.index                   |
| GET|HEAD | nova                                                                                       | nova.index                      |
```

### Detailed steps to reproduce the issue on a fresh Nova installation:

* Install Laravel 8 + Nova + Horizon. (would probably also do the same without Horizon)
* Edit `resources/views/vendor/nova/partials/user.blade.php` and add a link to the nav bar in top right

```html
<li>
	<a href="{{ route('nova.index') }}" class="block no-underline text-90 hover:bg-30 p-3">
		Nova Dashboard
	</a>
</li>
<li>
	<a href="{{ route('nova.logout') }}" class="block no-underline text-90 hover:bg-30 p-3">
		{{ __('Logout') }}
	</a>
</li>
```
* start Laravel (`sail up`)
* login 
* go to Nova index (in my case `http://localhost/nova/dashboards/main`)
* get error: 

> Symfony\Component\Routing\Exception\RouteNotFoundException
> Route [nova.index] not defined. (View: /var/www/html/resources/views/vendor/nova/partials/user.blade.php)
> in vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:429

I found issue [445](https://github.com/laravel/nova-issues/issues/445), but e.g. "`Just use config('nova.path') instead of route('nova.index') to generate URL`" does not work here, and there are no catch-all routes.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by cinemapub** [comment]
How is expecting `route('nova.index')` to work as advertised, a feature request? It is very much a bug report.

**Comment by crynobone** [comment]
Because it was never part of existing feature.

**Comment by cinemapub** [comment]
OK, I see! Thanks!
