### ISSUE TITLE
IndexQuery does not apply to search results correctly

### ISSUE THREAD

**Issue by kbellpostman** [laravel/nova-issues#3354]
- Laravel Version: 8.5.15
- Nova Version:  3.22.0
- PHP Version: 8
- Database Driver & Version: MySQL8
- Operating System and Version: Windows 10
- Browser type and version: Chrome

### Description:

IndexQuery does not apply to search results inside an index view. I'm wondering if this to be expected? 

### Detailed steps to reproduce the issue on a fresh Nova installation:

I've set up an indexQuery to filter my index view by a column:

![image](https://user-images.githubusercontent.com/60920059/115030770-c07c8a80-9ec7-11eb-8901-1d0743e4dcd7.png)

When I search through the resource it filters correctly... but the pagination is now suddenly running without the index query filter set. The index view is hiding all the resources in the table but still spreading them over the pagination pages like based on what would happen if there was no IndexQuery set. 

![image](https://user-images.githubusercontent.com/60920059/115031021-01749f00-9ec8-11eb-924a-ab664ad8ccb2.png)

**Comment by crynobone** [comment]
Is this using Scout search or normal search?

**Comment by kbellpostman** [comment]
The normal search. The problem disappears when I take out the indexQuery.

**Comment by crynobone** [comment]
Unable to reproduce the issue, see https://github.com/nova-issues/issue-3354/commit/4b7aa8501574a0f01c771eff536572d758179a1a

![image](https://user-images.githubusercontent.com/172966/115314862-a503cf00-a1a8-11eb-861d-af38a9054d67.png)

**Comment by kbellpostman** [comment]
Thanks Mior for checking it out! I traced the inner workings but I'll do a little bit research and a test with a clean checkout. 

Alex

**Comment by crynobone** [comment]
Please create new issue with reproducing code if you have similar problem.
