### ISSUE TITLE
belongsToMany:make cannot be used with big tables

### ISSUE THREAD

**Issue by gilr** [laravel/nova-issues#3356]
- Laravel Version: 8.37.0
- Nova Version: 3.23.2
- PHP Version: 7.3.26
- Database Driver & Version: MySQL 5.7.24
- Operating System and Version: Windows 10
- Browser type and version: Firefox 87

### Description:
With a small table, the "attach" screen of a belongsToMany relationship field works, but with a lot of records, the screen is partly displayed then it crashes. I didn't find any solutions (with a dedicated resource build on the relationship, it is possible to use the searchable method, but I don't know how to modify the 'attach' built-in screen). If this is not possible, the belongsToMany relationship field cannot be used in production, which is a real issue.

### Detailed steps to reproduce the issue on a fresh Nova installation:
 - Create an "author" Model & Table.
 - Create a "signature" Model & Table (author_id, pseudonym_id), which is the belongsToMany relation table (between author and author).
 - Add the belongsToMany::make(...) relationship field in the author Resource.
 - Populate the author table with 15 000 records.

Then try to add relationships:
 - Display an author detail view, then click on "Attach" on the right if the belongsToMany part.
 - Then on the Attachment view ((Url example : mysite.test/nova/resources/authors/7/attach/authors?viaRelationship=pseudonyms&polymorphic=0):
 - the screen is not complete (please compare with the screen below with a small number of records):
![Attach in progress](http://www.bdfi.info/img/couv/a/attach_partialscreen.jpg)
 - On this screen, the dropdown selection box cannot be used...
 - and then it ends with a memory crash:
![Attach Memory crash](http://www.bdfi.info/img/couv/a/attach_memorycrash.jpg)

With a small list of records, it works:
![Attach OK](http://www.bdfi.info/img/couv/a/attach_withtrashed.jpg)
And with the select box:
![Attach select](http://www.bdfi.info/img/couv/a/attach_listfull.jpg)

Is there a usable workaround?

**Comment by crynobone** [comment]
Use `searchable()` option.

**Comment by gilr** [comment]
I'm sorry, I though I tried it, but I may have used belongsToMany()->withoutTrashed()->searchable() then did search in the documentation, then removed the two methods (searchable and withoutTrashed) as both of them were not indicated for the belongsToMany method.

### => Caution: 
As far as I could see, in the Nova documentation, the searchable() method is indicated only for belongsTo, MorphTo and MorphToMany : [searchable-relations)](https://nova.laravel.com/docs/3.0/resources/relationships.html#searchable-relations). It should be great to it.

(and now it's work, except in the view after an 'edit' action, the dropdown selection box is always disabled. I will try to understand)
