### ISSUE TITLE
Nova.removeShortcut is not a function

### ISSUE THREAD

**Issue by origami1024** [laravel/nova-issues#3357]
- Laravel Version: 8.37.0
- Nova Version: 3.23.2

### Description:
After Nova update from 3.22 to 3.23.2 I get the error Nova.removeShortcut is not a function in my custom tool.
My **guess** is it was offscreen renamed to disableShortcut, is that so?

According to doc it isn't
https://nova.laravel.com/docs/3.0/customization/frontend.html#shortcuts

**Comment by crynobone** [comment]
Documentation updated based on changes. You may preserve the old function by adding the following:

```js
if (!Nova.removeShortcut) {
  Nova.removeShortcut = (key) => { Nova.disableShortcut(key); } 
}
```
