### ISSUE TITLE
DateTime widget shows current date, but not current time (shows 12:00:00 instead).

### ISSUE THREAD

**Issue by YasamDevelopment** [laravel/nova-issues#3362]
- Laravel Version: 7.30.4
- Nova Version: 3.21.1
- PHP Version: 7.4.16
- Database Driver & Version: mysql 8
- Operating System and Version: Ubuntu 20.04 (LTS) x64
- Browser type and version: Chrome 89.0.4389.128 & Safari 14.0

### Description:
- In my Laravel Resource file, I have a:
```
DateTime::make('Date')
                ->rules('required'),
```
- In Nova Admin Panel, when Creating a new Resource, before doing anything, the textbox of the DateTime widget shows (in light grey text) the current date & time (eg: 2021-04-23 09:35:50).
- But when clicking on the textbox (to popup the widget), the widget shows the CORRECT date (2021-04-23) in the calendar area, but shows the INCORRECT time (12:00:00) in the time area.

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Just make a simple DateTime field (like the example above). Then in Nova Admin Panel, go to create a new resource. See the current date & time (in light gray) in the textbox. Click on the textbox, and see the correct date (in calendar area), but incorrect time (in time area).

**Comment by crynobone** [comment]
From what I understand here this is the default behavior from Flatpickr.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
You should be able to do the following:

```php
use Laravel\Nova\Fields\DateTime;

DateTime::make('Purchased At')->default(now()->second(0))->incrementPickerMinuteBy(1),
```
