### ISSUE TITLE
Load 'app\Nova\Dashboards\' as default dashboard

### ISSUE THREAD

**Issue by Tommvv** [laravel/nova-issues#3363]
### **What I am looking for:**

A way to potentially load an `app\Nova\Dashboards\DashboardExample` as the default dashboard.

### **Problem**

Nova comes with a default dashboard which is build in the `NovaServiceProvider` and gives you the possibility to add additional dashboards using the `dashboards()` function.

When using this `dashboards()` function, you add **additional** dashboards instead of loading in a different dashboard as the **default** dashboard which is not what I am looking for.

The default dashboard is the standard location you end up after signing in, however not every user should see the same dashboard which is why I am looking for a way to change the default dashboard depending on your *'roles'*.

### **Current "*solution*":**

Currently I am calling a custom function in the `cards()` function.
The `cards()` function expects an array of cards/metrics to populate the default dashboard.

The *'custom'* function in `cards()` expects your **current role**.

The *'custom'* `dashboardContent()` function has an array for every dashboard containing their corresponding content. 

Depending on what role you have as a user, your dashboard will be filled with the content belonging to your corresponding role. 

I have done this by making an array containing all the *'dashboard arrays'* and giving them a *key/value* pair using the **role enums**. So if your role matches an **enum array key**, it will return the corresponding dashboard array containing the content required to **build** the default dashboard. 

    public function dashboardContent($role)
    {
        //array of metrics per dashboard
        $role1Metrics = [new Metrics1, new Metrics2, new Metrics3];
        $role2Metrics = [new Metrics1, new Metrics2];
        $role3Metrics = [new Metrics3];

        $dashboard = array(
            Roles::role1()->getValue() => $role1Metrics,
            Roles::role2()->getValue() => $role2Metrics,
            Roles::role3()->getValue() => $role3Metrics
        );

        if (array_key_exists($role, $dashboard)) {
            return $dashboard[$role];
        }
    }

This could also be done using a ***switch case*** which would look something like this

    public function dashboardContent($role)
    {
        //array of metrics per dashboard
        $role1Metrics = [new Metrics1, new Metrics2, new Metrics3];
        $role2Metrics = [new Metrics1, new Metrics2];
        $role3Metrics = [new Metrics3];

        switch($role) {
            case Roles::role1():
                return $role1Metrics;
            case Roles::role2():
                return $role2Metrics;
            case Roles::role3():
                return $role3Metrics;
        }
    }

This all works great, and I haven't noticed any bad performance. However I do not feel good about having to go out of my way like this to use the default dashboard.

Ultimately I would love it if I could make/manage dashboards in `app\Nova\Dashboards\` and to initialise these as default depending on **role**. As I feel like this would be way more maintainable in the future as the dashboard content will all be in their respective file rather than having to add them to an array in a custom function.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
