### ISSUE TITLE
Nova localization files not used on login page

### ISSUE THREAD

**Issue by IdrisN** [laravel/nova-issues#3364]
- Laravel Version: 8.34.0
- Nova Version: 3.22.0
- PHP Version: 7.4.13

### Description:

I support multiple languages in my laravel application, but nova should be only in english. I've created translation files according to the nova docs but the login page is not using the language file for nova located at `resources/lang/vendor/nova/...` but the the the one located in `resources/lang/...`. The Nova dashboard itself is using the right files. It's only the login page.

this i my file tree:

```
resources/lang
├── de 
│   ├── auth.php <--------┐
│   └── validation.php    ├--- these files are used
├── de.json <-------------┘
├── ...
└── vendor
    └── nova
        ├── en
        │   ├── auth.php <--------┐
        │   └── validation.php    ├--- but these files should be used
        └── en.json <-------------┘
```

### Detailed steps to reproduce the issue on a fresh Nova installation:

Create a language file for nova resulting in the structure above. If your locale is english, choose another language for nova.

**Comment by IdrisN** [comment]
I enforced the language in nova by adding the following code to the boot function of the `NovaServiceProvider.php`

```
Nova::serving(function (ServingNova $event) {
    app()->setlocale('en');
});
```

But this is not applied to the login page.

**Comment by crynobone** [comment]
Unable to reproduce the issue, see the following reproducing code/commit https://github.com/nova-issues/issue-3364/commit/be69527881331097131b36f07117709ca7ce5414

![image](https://user-images.githubusercontent.com/172966/115868325-e0cfba80-a46e-11eb-8188-994cb71e180e.png)

**Comment by crynobone** [comment]
Use following:

```php
Nova::booted(function ($event) {
    app()->setlocale('en');
});
```

**Comment by IdrisN** [comment]
I could reproduce your solution. First of all thanks for that.

Using `Nova::booted(...)` instead of `Nova::served(...)` to set the app locale changed the language on the login page.
But `Nova::booted(...)` did not change the nova app language. Using both did the trick.

```
public function boot()
    {
        parent::boot();

        Nova::booted(function () {
            app()->setlocale('en');
        });

        Nova::serving(function (ServingNova $event) {
            app()->setlocale('en');
        });
    }
```

### Remaining Problem

The translation files located inside the respective language directories are still not used.

```
resources/lang
├── en 
│   └── auth.php <------- is used for the error messages
├── ...
└── vendor
    └── nova
        ├── en
        │   ├── auth.php <-------- this file should be used for the error messages
        │   └── validation.php    
        └── en.json <------------- is used for the login page and nova app
```

I could reproduce this by forking your code and adding the respective NL files.
https://github.com/IdrisN/issue-3364/commit/b13002c1b9b7cfb0e97cfbbdb35de29a8198875b

I would say the issue still persists although my personal problem is solved.

**Comment by crynobone** [comment]
```
└── vendor
    └── nova
        ├── en
        │   ├── auth.php <-------- this file should be used for the error messages
```

Laravel Nova uses `laravel/ui` for authentication, therefore it is expected behavior to use `resources/lang/en/auth.php` and not `resources/lang/vendor/nova/en/auth.php`.
