### ISSUE TITLE
Use morph map for Trix attachable

### ISSUE THREAD

**Issue by wimski** [laravel/nova-issues#3376]
It would be nice if Trix would use morph mapping (if available) instead of the FQN. This would guard against breaking data when a model class is moved.

#### `Laravel\Nova\Trix\DeleteAttachments:36-40`
```php
Attachment::where('attachable_type', get_class($model)) // replace with $model->getMorphClass()
    ->where('attachable_id', $model->getKey())
    ->get()
    ->each
    ->purge();
```

#### `Laravel\Nova\Trix\PendingAttachment:49-55`
```php
Attachment::create([
    'attachable_type' => get_class($model), // replace with $model->getMorphClass()
    'attachable_id' => $model->getKey(),
    'attachment' => $this->attachment,
    'disk' => $disk,
    'url' => Storage::disk($disk)->url($this->attachment),
]);
```

**Comment by crynobone** [comment]
This has been fixed with [v3.25.0 release](https://nova.laravel.com/releases/3.25.0).
