### ISSUE TITLE
Add scrollbar to index view

### ISSUE THREAD

**Issue by ahmad13504** [laravel/nova-issues#3377]
I have a resource with 14 columns, now I've added 1 more field, but it breaks the layout and does not add a scrollbar.
I'm using the 3.5 version.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by davidhemphill** [comment]
Need some more information. A screenshot would help. :-)
