### ISSUE TITLE
Return type mismatch between DecodesFilters and FilterDecoder

### ISSUE THREAD

**Issue by wimski** [laravel/nova-issues#3378]
- Nova Version: 3.24.0

### Description:
There is a mismatch between the return types of the `filters` method in `DecodesFilters` and `FilterDecoder`. The `DecodesFilter` trait return the filters from `FilterDecoder`, which is a collection, but it says it returns an array.

#### `Laravel\Nova\Http\Requests\DecodesFilters`
```php
/**
 * Get the filters for the request.
 *
 * @return array
 */
public function filters()
{
    return (new FilterDecoder($this->filters, $this->availableFilters()))->filters();
}
```

#### `Laravel\Nova\FilterDecoder`
```php
/**
 * Decode the given filters.
 *
 * @return \Illuminate\Support\Collection
 */
public function filters()
{
    // method body
}
```

**Comment by crynobone** [comment]
Thank you for the report.
