### ISSUE TITLE
Actions applied on all models of the resource (with indexQuery()), instead of the selected model(s).

### ISSUE THREAD

**Issue by LTKort** [laravel/nova-issues#3379]
- Laravel Version: 8.40
- Nova Version: 3.24
- PHP Version: 7.4
- Database Driver & Version: MySQL

### Description:
In the handle function of an action, the collection contains all the models from the index query function of the resource.
So on selecting a row (or multiple), executing the action, it gives a collection of all the models of the resource from the index query.
Instead of returning the selected rows. 

### Detailed steps to reproduce the issue on a fresh Nova installation:
Install Laravel & Nova
Create a Model & Resource for e.g. User
Add an IndexQuery function to the Resource e.g.
```php
public static function indexQuery(NovaRequest $request, $query)
{
    return $query->whereNotNull('email_verified_at');
}
```

Create an action for the resource:
```php
public function handle(ActionFields $fields, Collection $models)
{
    foreach ($models as $model) {
          $user = $model->delete();
    }
}
```
When you select a user, and apply the action. It will be applied on all users that match the IndexQuery. 
And not only the selected user.

### Workaround
It doesn't happen if we check the request instance first:

```php
public static function indexQuery(NovaRequest $request, $query)
{
    if (!$request instanceof \Laravel\Nova\Http\Requests\ActionRequest) {
          return $query->whereNotNull('email_verified_at');
    }
}
```

**Comment by crynobone** [comment]
I have created a reproducing code and everything seems to be working as expected. See https://github.com/nova-issues/issue-3379/commit/b6ff692cd440775b275cf93eb4f65125632a49ec

### Expected behaviors

* Select one or multiple rows will use `indexQuery()` only for selected rows.
* Select all with use `indexQuery()` for all rows on current page.
* Select all matching rows will use `indexQuery()` on all pages.

**Comment by crynobone** [comment]
If this isn't the same on your project it could be caused by 3rd party packages overriding Nova components and it changes the default behaviors

**Comment by crynobone** [comment]
Someone should create a new bug report with reproducing repository. As discussed in this thread we have tried reproducing the issue and failed, and the original poster has not added any new information to verify the issue.
