### ISSUE TITLE
No loading indicator when deleting / force-deleting

### ISSUE THREAD

**Issue by vesper8** [laravel/nova-issues#3385]
In my application triggering a delete/force-delete on a model such as User causes a big chain reaction of cascade deletes.. It can easily take 2-3 seconds for a User to be fully deleted as a result. Currently when deleting a user in Nova there is no spinner/loading indicator that occurs after clicking on the 'delete' button. It just sits there and waits 2-3 seconds. The problem is exacerbated when selecting multiple users for deletion.. which can then take 30+ seconds if you've selected 10+ users for deletion

I would really like to see an overlay with a spinner here to indicate work is being done, and to prevent users from navigating away from the page while work is happening

I'm on `3.24.0`

**Comment by crynobone** [comment]
This has been fixed in [v3.26.0](https://nova.laravel.com/releases/3.26.0)
