### ISSUE TITLE
Field doesn't store the value using the `AsArrayObject` cast.

### ISSUE THREAD

**Issue by masterix21** [laravel/nova-issues#3387]
- Laravel Version: 8.41.0
- Nova Version: 3.24.0
- PHP Version: 8.0.3
- Database Driver & Version: MySQL
- Operating System and Version: OSX 
- Browser type and version: Chrome

### Description:
Using `AsArrayObject` the field shows the value but in edit mode, the value won't be updated.

```php
Text::make('Rule name', 'rule->name')->hideFromIndex()->rules('nullable', 'string'),
...
```

**Comment by masterix21** [comment]
I've found a workaround like so:
```php
Text::make('Rule name', 'rule->name')
     ->hideFromIndex()
     ->rules('nullable', 'string')
     ->fillUsing(function ($request, $model, $attribute, $requestAttribute) {
          data_set($model, Str::of($attribute)->replace('->', '.'), $request->input($attribute));
     })
...
```

PS: replacing `rule->name` with `rule.name` isn't a solution because I've already tried.

**Comment by crynobone** [comment]
Acknowledge this issue is a bug. However, I do feel that we need to collect more use-case before attempting to make a fix. 

1. How does it behave with other json/collection/array casts.
2. Nova 3 still supports Laravel Framework 7 which doesn't have `AsArrayObject` as far as I know.

**Comment by masterix21** [comment]
Yes, Laravel 7 doesn't support `AsArrayObject`. Before moving to `AsArrayObject`, I had always used the array cast, as the workaround code (but without the `fillUsing()` method).

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
