### ISSUE TITLE
cakephp/chronos dependency issue with prefer lowest

### ISSUE THREAD

**Issue by wimski** [laravel/nova-issues#3388]
- Laravel Version: 8.25.0 (as a dependency of `orchestra/testbench ^6.17`)
- Nova Version: 3.19.0
- PHP Version: 7.4 || 8.0
- Reproduction Repository: https://github.com/wimski/nova-carbon-chronos-issue

### Description:

When developing a package for Nova I encountered an issue when testing with the lowest dependency versions possible. See the error message in the [production repo readme](https://github.com/wimski/nova-carbon-chronos-issue#nova-carbon-chronos-issue).

If I explicitly require `cakephp/chronos ^2.0` the issue goes away, but I don't want to require this as my code does not directly depends on it.

**Comment by crynobone** [comment]
Laravel Nova only tested with Testbench 6 at the moment while we do still support Laravel Framework 7. No plan to change this for Orion but we are removing Chronos for next major release.
