### ISSUE TITLE
javascript error when Switching between dashboards

### ISSUE THREAD

**Issue by bamatic** [laravel/nova-issues#3389]
- Laravel Version: 8.35.1
- Nova Version:3.21.0
- PHP Version: 7.3
- Database Driver & Version: mysql 5.7.24
- Operating System and Version: windows 10
- Browser type and version: chrome Version 90.0.4430.93 (Build officiel) (64 bits)
- Reproduction Repository: https://github.com/###/###

### Description:
I have several  dashboards with similar cards, values of cards are given in php using withmeta functions defined in card's src/php file, if i reload the page all works fine but if i navigate between dashboards, and i switch from a dashboards to an another, page is not reload and in the last "loaded" dashboards cards gets the values of the precedent card in the same position, if cards in the same position are diferents, page is load correctly

https://www.youtube.com/watch?v=cJnQMkBgAVc

**Comment by crynobone** [comment]
Can you replicate the issue on fresh installation?
