### ISSUE TITLE
Internal server error for scripts & styles on nova-api route

### ISSUE THREAD

**Issue by pepijn-vanvlaanderen** [laravel/nova-issues#3390]
- Laravel Version: 8.41.0
- Nova Version: 3.25.0
- PHP Version: 8.0.3
- Database Driver & Version: MariaDB 10.3.29
- Operating System and Version: Ubuntu (using laravel Sail)
- Browser type and version: 90.0.4430.212
- Reproduction Repository: https://github.com/###/###

### Description:
I am upgrading a project where we use Nova. After upgrading all packages including Nova to the latest versions, all scripts and styles loaded through `/nova-api/scripts/*` and `/nova-api/styles/*` are resulting into an 500 internal server error. 

The resulting error message:

```
file_get_contents(): Argument #1 ($filename) must be of type string, array given {"exception":"[object] (TypeError(code: 0): file_get_contents(): Argument #1 ($filename) must be of type string, array given at /var/www/html/vendor/laravel/nova/src/Http/Controllers/ScriptController.php:28)
```

The issue seems to be in the ScriptController and the StyleController, where `$request->script` and `$request->style` are both empty and thus the retrieved `$path` is just the complete array of scripts / styles.

I can get it to work if I change i.e. the ScriptController to:

```
public function show(NovaRequest $request, $script)
{
    error_log($request->script); // --> This is empty
    error_log($script); // --> This passes indeed the script name

    $path = Arr::get(Nova::allScripts(), $script);

    abort_if(is_null($path), 404);

    return response(
        file_get_contents($path),
        200,
        [
            'Content-Type' => 'application/javascript',
        ]
    )->setLastModified(DateTime::createFromFormat('U', (string) filemtime($path)));
}
```

Does anyone have some pointers in how I can fix this issue?

**Comment by crynobone** [comment]
Unable to replicate this on a default installation. In fact, we have multiple dusk tests covering this use case. Can you create a reproducing repository on GitHub and share it here?

**Comment by pepijn-vanvlaanderen** [comment]
Hi @crynobone, thanks for your reply. The error message that I got was pretty generic, but I eventually looked into all third-party nova plugins I use and got it sorted out, ran into an issue with the nova settings package: https://github.com/optimistdigital/nova-settings/issues/60..
