### ISSUE TITLE
Resource URL causes 502

### ISSUE THREAD

**Issue by jesseschutt** [laravel/nova-issues#3391]
- Laravel Version: 8.41.0
- Nova Version: 3.21.0
- PHP Version: 7.4.18
- Database Driver & Version: Postgres 12
- Operating System and Version: Mac OS 10.15.7
- Browser type and version: Brave V1.24.85
- Reproduction Repository: 
 
### Description:
When upgrading from Nova 3.19 I'm seeing an issue on Homestead where certain resource urls are triggering 502 nginx errors. 

For example, the following url is generated on 3.21.0 and generates the 502 error: 
`http://demo.test/nova-api/classrooms?search=&filters=W10%3D&orderBy=&perPage=5&trashed=&page=1&viaResource=teachers&viaResourceId=1&viaRelationship=classrooms&relationshipType=hasMany`

Compared to the same resource url on 3.19.0: 
**INCORRECT**
`http://demo.test/nova-api/classrooms/relate-authorization?viaResource=teachers&viaResourceId=1&viaRelationship=classrooms&relationshipType=hasMany`

**UPDATED**
`http://demo.test/nova-api/classrooms?search=&filters=W10%3D&orderBy=&perPage=25&trashed=&page=1&viaResource=teachers&viaResourceId=1&viaRelationship=classrooms&relationshipType=hasMany`

If I modify the 3.21.0 url and remove either `viaResourceId=1` or `viaRelationship=classrooms` the response is properly generated.

I have attempted this on a freshly rebuilt instance of the latest currently available Homestead (v12.2.0) at the time of this writing.

Thanks for your time!

**Comment by crynobone** [comment]
above URLs are two different URLs. Can you recreate the issue on fresh installation?

**Comment by jesseschutt** [comment]
Thanks for the response! You are correct, I copied the wrong sample url into my original post. I've amended it now.

For example on 3.19 Nova is calling `http://demo.test/nova-api/classrooms?search=&filters=W10%3D&orderBy=&perPage=25&trashed=&page=1&viaResource=teachers&viaResourceId=1&viaRelationship=classrooms&relationshipType=hasMany` which results in the `HasMany` field to display the classroom list as expected:

<img width="1024" alt="Screen Shot 2021-05-15 at 7 00 42 AM" src="https://user-images.githubusercontent.com/353047/118359971-47666680-b54b-11eb-8020-b39a30befbd2.png">

The same page in 3.21.0 is calling `http://demo.test/nova-api/classrooms?search=&filters=W10%3D&orderBy=&perPage=5&trashed=&page=1&viaResource=teachers&viaResourceId=1&viaRelationship=classrooms&relationshipType=hasMany`to fetch the same `HasMany` field which results in the 502 error:

<img width="1067" alt="Screen Shot 2021-05-15 at 7 13 49 AM" src="https://user-images.githubusercontent.com/353047/118360436-1b4be500-b54d-11eb-98c6-6d3247a9e1ac.png">

From what I can see the only difference between the two is that one is using 25 perPage and the other 5. The same endpoint is failing between 3.19.1 and 3.21.0. 

Perhaps it has something to do with this item in the release notes? 
<img width="446" alt="Screen Shot 2021-05-15 at 7 18 36 AM" src="https://user-images.githubusercontent.com/353047/118360534-c65c9e80-b54d-11eb-947f-3ca60109aa29.png">

I appreciate any suggestions you may have - thank you

**Comment by jesseschutt** [comment]
I've isolated the problem and it is unrelated to Nova - the issue was a field on a Nova model was calling `->findModelQuery()` which was creating the 502. I'm not sure if it was causing some kind of a loop but refactoring that to a different approach removed the error.

Thanks for the help!
