### ISSUE TITLE
Accessibility: Modals are not tab-proof

### ISSUE THREAD

**Issue by sedlatschek** [laravel/nova-issues#3395]
- Laravel Version: 8.41.0
- Nova Version: 3.25.0
- PHP Version: 7.4.6
- Database Driver & Version: MySQL 5.7
- Operating System and Version Win10
- Browser type and version: Chrome 88 / Edge 90

### Description:

Modals do not prevent the user from focusing elements from the backdrop using the keyboard. Blind users need to have the tab navigation restricted to the current modal, as they are not able to tell that a modal is still open once they 'tabbed' out of it by accident.

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Open any resource table
2. Click on the delete button of any resource
3. Press the keyboard button `tab` a few times

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
