### ISSUE TITLE
Accessibility: Error pages are not recognized by screenreaders

### ISSUE THREAD

**Issue by sedlatschek** [laravel/nova-issues#3396]
- Laravel Version: 8.41.0
- Nova Version: 3.25.0
- PHP Version: 7.4.6
- Database Driver & Version: MySQL 5.7
- Operating System and Version Win10
- Browser type and version: Chrome 88 / Edge 90

### Description:

When running into error pages (eg 404), [JAWS 2021](https://www.freedomscientific.com/products/software/jaws/) continues to read elements from the backdrop, compeletely ignoring the displayed error page. I assume that is because the error has no `role="alert"` attribute.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
