### ISSUE TITLE
Accessibility: Boolean icons not recognized by screenreaders

### ISSUE THREAD

**Issue by sedlatschek** [laravel/nova-issues#3398]
- Laravel Version: 8.41.0
- Nova Version: 3.25.0
- PHP Version: 7.4.6
- Database Driver & Version: MySQL 5.7
- Operating System and Version Win10
- Browser type and version: Chrome 88 / Edge 90

### Description:

The boolean icons are not recognized by screenreaders such as JAWS 2021. Blind users have no way of retrieving the value.

![boolean icon](https://user-images.githubusercontent.com/58665536/118691909-d43e4800-b809-11eb-80bd-2b6a5f9b5baf.png)

**Comment by sedlatschek** [comment]
It looks like all icons use `aria-labelledby` the wrong way. From what I understand this attribute is used to reference another element by id (the same way `for` works). For the `false` icon the attribute is set to `x-circle`, but no element with the id `x-circle` exists. Is this done on purpose?

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
