### ISSUE TITLE
Laravel Nova install failed on Laravel 8

### ISSUE THREAD

**Issue by christophe-44-27** [laravel/nova-issues#3399]
- Laravel Version: 8.12
- Nova Version: 3.25.0
- PHP Version: 8.0.3
- Database Driver & Version: MySQL
- Operating System and Version: Windows 10

### Description:
I'm following the documentation to install Laravel Nova on my project and it's failing with error message that tells "NovaServiceProvider not found" when i launch "php artisan nova:install"

![image](https://user-images.githubusercontent.com/7846034/118728715-eda8b980-b834-11eb-91d3-7bbed34192b9.png)

### Detailed steps to reproduce the issue on a fresh Nova installation:
Install a fresh Laravel install (version 8, it works in version 7), use composer or the way to unzip the files into laravel root folder, and launch "php artisan nova:install".

**Comment by dwightwatson** [comment]
I have an issue when upgrading Nova and publishing the latest assets, so I suspect this is related. Did the latest version ship without stubs or something?

```
> @php artisan nova:publish
Unable to locate publishable resources.
Publishing complete.
Unable to locate publishable resources.
Publishing complete.
Unable to locate publishable resources.
Publishing complete.
Unable to locate publishable resources.
Publishing complete.
```

**Comment by crynobone** [comment]
@dwightwatson @christophe-44-27

Please revert to `"laravel/framework": "8.41.0"` until https://github.com/laravel/framework/pull/37405 has been merged and tagged.

@christophe-44-27 

After downgrading, delete `App\Providers\NovaServiceProvider::class` from `config/app.php` and run `php artisan nova:install` again.

**Comment by christophe-44-27** [comment]
Indeed, it's working with 8.41.0 for Laravel, thank you @crynobone !

**Comment by crynobone** [comment]
@christophe-44-27 let's keep this open until a patch has been released.

**Comment by crynobone** [comment]
v8.42.1 has been released on should solve this issue. thank you all.
