### ISSUE TITLE
Buttons and titles are using uriKey's english singularized form instead of singular label

### ISSUE THREAD

**Issue by lucasromanojf** [laravel/nova-issues#34]
That was fixed in 1.0.5 for the "Create" button on index screen. But this is still happening in other screens (like inside create and update screens title and buttons)

**Comment by reganjohnson** [comment]
Related: https://github.com/laravel/nova-docs/issues/21

**Comment by reganjohnson** [comment]
The `label()` and `labelSingular()` are also not being respected on the column headers on tables of related models. In the below screenshot, `STRIPECUSTOMERS` should be `STRIPE CUSTOMERS`.

![screen shot 2018-08-23 at 12 46 00 pm](https://user-images.githubusercontent.com/12020344/44539631-b08a5980-a6d2-11e8-8489-e9275f4824c2.png)

**Comment by disitec** [comment]
Explained here #36 and here #61
