### ISSUE TITLE
Feature request: Illuminate\Foundation\Http\FormRequest support

### ISSUE THREAD

**Issue by DSpeichert** [laravel/nova-issues#340]
It would be very helpful if instead of redefining validation rules on every field, we could connect a pre-existing `Illuminate\Foundation\Http\FormRequest` that is written for a given model to the Nova Resource class, ideally a different one for creating and updating.

**Comment by peanut24** [comment]
Agreed, created an issue for this as well #106

**Comment by DSpeichert** [comment]
Oops, I searched but couldn't find it. This is duplicate of #106.
