### ISSUE TITLE
Can't publish Nova assets after upgrade to 3.25.0

### ISSUE THREAD

**Issue by percymamedy** [laravel/nova-issues#3400]
- Laravel Version: 8.42.0
- Nova Version: 3.25.0
- PHP Version: 8.0.3
- Operating System and Version: macOS Big Sur 11.3

### Description:

After recent upgrade to 3.25.0, tried to run ```php artisan nova:publish``` faced with the following errors:

![image](https://user-images.githubusercontent.com/11259669/118975806-69198080-b985-11eb-9311-b939178f57e8.png)

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Upgrade to nova 3.25.0
2. run nova:publish

**Comment by crynobone** [comment]
Upgrade to Laravel Framework 8.42.1, there an bug with 8.42.0 causing Nova to not work properly
