### ISSUE TITLE
Resource isSoftDeleted() method should check the trashed() method in case it was overridden.

### ISSUE THREAD

**Issue by jonagoldman** [laravel/nova-issues#3403]
- Laravel Version: 8.42.1
- Nova Version: 3.23.2
- PHP Version: 8.0.3

### Description:
In my app models, I override the `trashed()` method from the `SoftDeletes` trait to add some custom logic.

But in `Laravel\Nova\Resource`, this method is not used:

```php
public function isSoftDeleted()
{
    return static::softDeletes() && ! is_null($this->resource->{$this->resource->getDeletedAtColumn()});
}
```

This could be simplified to:
```php
public function isSoftDeleted()
{
    return static::softDeletes() && $this->resource->trashed();
}
```

This will respect overrides and reduce code duplication.

**Comment by crynobone** [comment]
This has been fixed in v3.27.0: https://nova.laravel.com/releases/3.27.0
