### ISSUE TITLE
Accessibility: Modals do not reset focus after closing

### ISSUE THREAD

**Issue by sedlatschek** [laravel/nova-issues#3404]
- Laravel Version: 8.41.0
- Nova Version: 3.25.0
- PHP Version: 7.4.6
- Database Driver & Version: MySQL 5.7
- Operating System and Version Win10
- Browser type and version: Chrome 88 / Edge 90

### Description:

When a modal is closed the focus does not reset to the triggering html element. Focussing starts at the body element again, which means users that can not use a mouse have to tab through the whole page to get back to where they had left off.

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Navigate to any index view
2. Click at the Trashcan in any row
3. Cancel the Modal
4. Press Tab
The focus will end up on the start of the page again.

**Comment by sedlatschek** [comment]
Is it a goal to make Nova accessible? Should I continue to report accessibility issues?

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
> Is it a goal to make Nova accessible? Should I continue to report accessibility issues?

We will look into implementing what's possible based on our knowledge of the issue.
