### ISSUE TITLE
Checkboxes are confusing when only standalone actions are available on index

### ISSUE THREAD

**Issue by sanderbaas** [laravel/nova-issues#3409]
- Laravel Version: 8.43.0
- Nova Version: 3.25.0

### Description:
I have a resources with one action and this is a standalone action. The user is not allowed to delete records. However, the checkboxes are visible on each row and it is possible to execute the standalone action after having selected one or more rows. I think this is confusing for users.

I think it would be better if the checkboxes are not visible when only standalone actions are available. Also when there are regular actions and standalone actions available, the standalone actions should not be executable when checkboxes are checked.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
