### ISSUE TITLE
 Action  defined as  onlyOnDetail show in resources list in Lens mode

### ISSUE THREAD

**Issue by sitnikov** [laravel/nova-issues#3411]
- Laravel Version: v8.44.0
- Nova Version: 3.25.0
- PHP Version: 7.4.x
- Database Driver & Version: MySQL 5.6
- Operating System and Version: Centos 7
- Browser type and version: Chrome Latest

Action registred  as  onlyOnDetail

return [
            (new RejectOrder())->onlyOnDetail(),

            (new OrderReportDownload())->canRun(function (){
                //NB ! override authorizedToUpdate
                return true;
            })
];

In "main" resourses list - all is ok, no this action visible when some resourses selected. 

In Lens mode - this action visible when some resourses selected.

<img width="653" alt="Screenshot 2021-05-27 212738" src="https://user-images.githubusercontent.com/140812/119878757-30544b00-bf33-11eb-947a-09c0f01271f0.png">
<img width="679" alt="Screenshot 2021-05-27 212632" src="https://user-images.githubusercontent.com/140812/119878759-30ece180-bf33-11eb-9981-1a28d9bbb1c7.png">

**Comment by crynobone** [comment]
This has been fixed in [v3.26.0](https://nova.laravel.com/releases/3.26.0)
