### ISSUE TITLE
DateField is not localized, is always in English

### ISSUE THREAD

**Issue by rzuloagageli** [laravel/nova-issues#3412]
- Laravel Version: 8.x
- Nova Version: 3.24.0
- PHP Version: 7.4
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:

`Laravel\Nova\Fields\Date` does not allow localization: the Front-End datepicker element (flatpickr) is always in English even with the Nova application being in another language. This should be solved where `flatpickr` is instantiated, `vendor/laravel/nova/resources/js/components/DateTimePicker.vue`. In the method `createFlatpickr()`

```
  methods: {
    createFlatpickr() {
      this.flatpickr = flatpickr(this.$refs.datePicker, {
        enableTime: this.enableTime,
        enableSeconds: this.enableSeconds,
        onClose: this.onChange,
        onChange: this.onChange,
        dateFormat: this.dateFormat,
        altInput: true,
        altFormat: this.altFormat,
        allowInput: true,
        // static: true,
        time_24hr: !this.twelveHourTime,
        locale: { firstDayOfWeek: this.firstDayOfWeek }, // Only allows localization for firstDayOfWeek
      })
    },
   ...
}
```

To have it localized it should be:

```
import { Spanish } from 'flatpickr/dist/l10n/es.js'

export default {
  ...
  methods: {
    createFlatpickr() {
      this.flatpickr = flatpickr(this.$refs.datePicker, {
        enableTime: this.enableTime,
        enableSeconds: this.enableSeconds,
        onClose: this.onChange,
        onChange: this.onChange,
        dateFormat: this.dateFormat,
        altInput: true,
        altFormat: this.altFormat,
        allowInput: true,
        // static: true,
        time_24hr: !this.twelveHourTime,
        locale: Spanish,
      })
    },
  ...
  }
}
```

As it is right now, with the calendar in English but the application in another language, it messes with the users, because some of them might not know English. And even if they did, to have a different language for the date picker is inconsistent.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Use field `Laravel\Nova\Fields\Date` in any resource.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
JavaScript needs to be compiled with all known languages in order to support this based on the above suggestion.
