### ISSUE TITLE
I updated my laravel and nova from 7 to 8 and nova to last version i have error 

### ISSUE THREAD

**Issue by shahabzebare** [laravel/nova-issues#3413]
- Laravel Version: 8.44.0
- Nova Version: 3.26.0
- PHP Version: 7.4
- Database Driver & Version:
- Operating System and Version: Mac OS last version
- Browser type and version: chrome last version
- Reproduction Repository: https://github.com/###/###

### Description:
ArgumentCountError
Too few arguments to function Laravel\Nova\Resource::__construct(), 0 passed in /Users/albnuser/Desktop/Projects/BadinanGroup/Doctors/nova/src/Resource.php on line 398 and exactly 1 expected (View: /Users/albnuser/Desktop/Projects/BadinanGroup/Doctors/nova/resources/views/layout.blade.php)
https://doctors.test/portal/resources/roles

https://www.loom.com/share/583998edff6a4ada947321814dab438f

**Comment by crynobone** [comment]
@shahabzebare 

1. Can you share which exact version previously on Laravel and Laravel Nova
2. Did the model namespace changed during the upgrade and has the Resource model been updated with it?
3. Is there any 3rd pary packages that may been broken during the upgrade?

**Comment by shahabzebare** [comment]
1. laravel 7 and nova was 3.10
2. i changed model namespace and change all import three no error in code 
3. i updated all 3rd part packages

**Comment by shahabzebare** [comment]
Thanks solved was problem call resource not model 
Thanks for your help
Best
