### ISSUE TITLE
A way to generate a Nova resource link

### ISSUE THREAD

**Issue by orrd** [laravel/nova-issues#3420]
In some scenarios there needs to be a way to generate a URL link to a Nova resource for use in other PHP code.  The author of issue #345 does a good job of explaining the need for this.  There are lots of replies that talk about a way to generate it in a Text field, but we're looking for a way to generate the URL for use in other areas of our code (as was the author of issue #345).  The conclusion from all the comments seems to be that there isn't yet a way to do this with Nova.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
We'll try to look into this once we finalized big changes for next major version to see how this fits in.

**Comment by cja-github** [comment]
Is there still no way to generate a URI for a Nova resource?

My use case is that I am exporting Laravel records to another system and I want to give that other system a URI for the Nova resource for each record so that users can click a link in the other system to open the resource in Nova.
