### ISSUE TITLE
ID link should be disabled when the resource is not viewable

### ISSUE THREAD

**Issue by shaffe-fr** [laravel/nova-issues#3421]
### Specs:
- Laravel Version: 8.44.0
- Nova Version: 3.26.1
- PHP Version: 7.4.7
- Database Driver & Version: MySQL
- Operating System and Version: Windows 10
- Browser type and version: Firefox 89

### Description:

1. Create a ressource
2. Update the policy to deny details view

### What is the expected behaviour:

1. The eye View icon should be hidden
2. The link on the ID column should not be clickable.

### What is the actual behaviour:

The eye icon is hidden but the ID field is still clickable. Clicking that link leads to a 403 error page

![image](https://user-images.githubusercontent.com/3834222/120774062-32fe0400-c522-11eb-83f9-8da277790dab.png)

**Comment by trovster** [comment]
If anyone is still experiencing this, [republish your Nova assets](https://nova.laravel.com/docs/3.0/installation.html#updating-nova-s-assets).
