### ISSUE TITLE
Error message unclear if file size is too big

### ISSUE THREAD

**Issue by LucileDT** [laravel/nova-issues#3422]
- Laravel Version: 7.13.0
- Nova Version: 3.6.0
- PHP Version: 7.4.12
- Database Driver & Version: ? *(I did not setup my environment and I don't know how to get this information)*
- Operating System and Version: Xubuntu 18.04
- Browser type and version: Firefox 89.0a1 64bits

### Description:

When uploading a too big image in an Image field without any Validation rule, the error thrown is about not being able to add a new empty database entry instead of explaining that the image is too big:

```
"SQLSTATE[HY000]: General error: 1364 Field 'filename' doesn't have a default value (SQL: insert into `article` (`id`, `updated_at`, `created_at`) values (143, 2021-06-07 12:35:36, 2021-06-07 12:35:36))"
```

### Detailed steps to reproduce the issue on a fresh Nova installation:

- create an Article entity which have a `filename` field (used to store the image filename)
- in Nova codebase, create an Article with an Image without any Validation rule:

```php
class Article extends Resource
{
    // [...]
    public function fields(Request $request)
    {
        return [
            ID::make()
                ->sortable(),

            Image::make('Image', 'filename')
                ->disk('public')
                ->path('articles')
                ->prunable(),
        ];
    }
    // [...]
}
```

- in Nova frontend, go to the Article page and try to create one using an absurdly big file (like 1GB)

**Expected behavior:**

- Article creation does not work
- An error is thrown ("There was a problem submitting the form")
- There is a HTML5 error on the Image field (similar to the one we get when we submit something with an empty required field) explaining that the file is too big (e.G. "The image you provided is too big (current maximum size allowed: [current maximum size allowed], please provide a smaller image").

**Current behavior:**

- Article creation does not work
- An error is thrown ("SQLSTATE[HY000]: General error: 1364 Field 'filename' doesn't have a default value (SQL: insert into \`article\` (\`id\`, \`updated_at\`, \`created_at\`) values (143, 2021-06-07 12:35:36, 2021-06-07 12:35:36))")

**Comment by crynobone** [comment]
There few issues here:

1. `ValidatePostSize` middleware should have caught this and prevent INSERT SQL from being executed. You need to make sure `App\Http\Kernel::$middleware` contains `\Illuminate\Foundation\Http\Middleware\ValidatePostSize::class`. See https://github.com/laravel/laravel/blob/0296bb63e1d465bcfff1f84f00313aeb26a2c84b/app/Http/Kernel.php#L21 for example.
2. To set HTML 5 error, you need to set validation rules for the image. You can refer to https://nova.laravel.com/docs/3.0/resources/validation.html and https://laravel.com/docs/7.x/validation#rule-size
3. I just open a PR to improves form request error notifications laravel/nova#1369

**Comment by LucileDT** [comment]
For information, my `App\Http\Kernel` already contains `\Illuminate\Foundation\Http\Middleware\ValidatePostSize::class`:

```php
protected $middleware = [
    \App\Http\Middleware\TrustProxies::class,
    \Fruitcake\Cors\HandleCors::class,
    \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
    \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
];
```

**Comment by LucileDT** [comment]
Another thing I just encountered: if I have a validation rule (it can be any of them), I do not encounter the SQL error and there is an HTML5 field error displayed. I'll update the original post to add this information.

**Comment by crynobone** [comment]
> in Nova codebase, create an Article with an Image without any Validation rule

You shouldn't do this. 

BTW the issue should be fixed on the upcoming Laravel Nova.

![CleanShot 2021-06-08 at 07 35 02](https://user-images.githubusercontent.com/172966/121100312-27fde900-c82c-11eb-94f9-dbd92258b889.gif)
