### ISSUE TITLE
Accessibility: Cancel anchor can not be triggered using keyboard only

### ISSUE THREAD

**Issue by sedlatschek** [laravel/nova-issues#3423]
- Laravel Version: 8.44.0
- Nova Version: 3.26.1
- PHP Version: 7.4.6
- Database Driver & Version: MySQL 5.7
- Operating System and Version: Win10
- Browser type and version: Chrome 88

### Description:
The cancel button of the create and edit forms can not be triggered using only the keyboard. Blind users are not able to cancel forms at all. Please don't use anchors without `href` attribute, use buttons instead. 

![image](https://user-images.githubusercontent.com/58665536/121042107-a79ba180-c7b3-11eb-9669-51e32c3f9368.png)

Laravel Nova is not accessible, which is a problem in enterprise environments.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
