### ISSUE TITLE
Accessibility: Focus should move on form input errors

### ISSUE THREAD

**Issue by sedlatschek** [laravel/nova-issues#3426]
- Laravel Version: 8.44.0
- Nova Version: 3.26.1
- PHP Version: 7.4.6
- Database Driver & Version: MySQL 5.7
- Operating System and Version: Win10
- Browser type and version: Chrome 88

### Description:
When having a form error, the focus should be set to the first invalid input. Blind users currently have to do a lot of "tabbing" once they run into form errors, because the focus stays at the submit button.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
