### ISSUE TITLE
localize flatpickr

### ISSUE THREAD

**Issue by daguilarm** [laravel/nova-issues#343]
There is a easy way to localize flatpickr?

**Comment by techouse** [comment]
Any news on this issue? It's frustrating and the only way to fix this now is making your own datepicker like [this guy here](https://github.com/JoffreyC22/nova-french-datepicker)

**Comment by emiliogrv** [comment]
Hi @daguilarm, @techouse I can solved it without create other field

Just add the next to bottom file `resources/views/vendor/nova/layout.blade.php`:

```html
    <!-- Change language default -->
    <script src="https://npmcdn.com/flatpickr@4.5.2/dist/l10n/es.js"></script>
    <script>
        flatpickr.localize(flatpickr.l10ns.es)
        flatpickr('.flatpickr-input')
    </script>
```

This found with any language supported by flatpickr, regards

**Comment by batFormat** [comment]
@emiliogrv 
I did not have such a file, is this normal?

I copied it from the composer/vendor and pasted as you say, it works)

**Comment by emiliogrv** [comment]
@batFormat Yes, it's normal, copying the folder is part of the customization

Already updated my comment

**Comment by Dontorpedo** [comment]
@emiliogrv 

hmm, tried in 1.3.1 but nothing happens at all..

i see the code on the bottom of my layout.blade.php but no changes, and no error...

**Comment by pleone** [comment]
LoL that's fun.

At least mention this "hack" (i would not call it a solution) in the doc
