### ISSUE TITLE
Add resource polling for resource detail screen

### ISSUE THREAD

**Issue by cwilby** [laravel/nova-issues#3433]
Currently resource polling is supported on the index screen,  it would be useful to be able to enable this for detail screens as well.  

Our current use case (similar to https://github.com/laravel/nova-issues/issues/3432) is refreshing a list of job models that complete within 2-5 seconds.

Occasionally we create the job model/resource manually which dispatches a job via eloquent events.  When this happens, Nova redirects to the detail page for the created resource.  

At this point, it would be ideal for the detail page to start polling for updates, so the user could see if the job succeeded or failed in real time.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
