### ISSUE TITLE
Accessibility: Metric helptext can not be reached using the keyboard only

### ISSUE THREAD

**Issue by sedlatschek** [laravel/nova-issues#3434]
- Laravel Version: 8.44.0
- Nova Version: 3.26.1
- PHP Version: 7.4.6
- Database Driver & Version: MySQL 5.7
- Operating System and Version: Win10
- Browser type and version: Chrome 88

### Description:
The helptext to a metric card can not be reached using the keyboard only. Please use a `button` instead of a `div` element or create a hidden `sr-only` as an alternative for screenreader users.

![image](https://user-images.githubusercontent.com/58665536/121352292-00427a00-c92d-11eb-9174-28d1d7539683.png)

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
