### ISSUE TITLE
Use of MorphTo in Nova Actions

### ISSUE THREAD

**Issue by eman-telp** [laravel/nova-issues#3435]
Hello,
So I have been trying to use `Laravel\Nova\Fields\MorphTo` in an action to allow the user to edit multiple resources at a time.
when running the action, it works as required and retrieves the type and related records.
![image](https://user-images.githubusercontent.com/58248022/121359392-1e63a680-c93c-11eb-85cc-5d9405902860.png)
 However, when I click Run Action, I get the following error:

![image](https://user-images.githubusercontent.com/58248022/121359730-739fb800-c93c-11eb-9537-12de9b0d6f53.png)

Is there any way that I can get MorphTo fields in a nova action?

**Comment by crynobone** [comment]
Action has no knowledge of Resource or Model Relationship. This just not possible at the moment.

**Comment by zgetro** [comment]
@eman-telp  you can use https://github.com/dillingham/nova-ajax-select package to pull custom data via ajax.
