### ISSUE TITLE
custom validation message not beeing displayed properly

### ISSUE THREAD

**Issue by vwasteels** [laravel/nova-issues#3436]
- Laravel Version: 8.40
- Nova Version: 3.26.1
- PHP Version: 8.0.7
- Database Driver & Version: does not matter
- Operating System and Version: MacOS 10.14 Mojave
- Browser type and version: Chrome Latest
- Reproduction Repository: 

### Description:

sub validation message are thrown in json format like so : 

![Screenshot -  2021-06-09 à 17 33 50](https://user-images.githubusercontent.com/1151398/121384837-e9118580-c948-11eb-92e0-55900aaf13c7.jpg)

### Detailed steps to reproduce the issue on a fresh Nova installation:

In `./resources/lang/fr/validation.php` :

```php
    'custom' => [
        'thumbnail' => [
            'dimensions' => [
              'min_width' => "Largeur min : :min_width",
              'max_width' => "Largeur max : :max_width",
              'min_height' => "Hauteur min : :min_height",
              'max_height' => "Hauteur max : :max_height",
            ]
        ],
    ],
```

in `./app/nova/Outil.php` , fields method :

```php
              Image::make("Vignette", 'thumbnail')
                ->rules([
                    'dimensions:min_width=200,max_width=800',
                    'max:600'
                ])
                ->maxWidth('200'),
```

**Comment by crynobone** [comment]
Please provide a full repository to replicate this issue.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
This is a hard issue to be solved when Laravel Framework itself unable to identify whether the dimension rule failed due to `min_width` or `max_width`. You may solve this at the moment by creating a custom Dimension validation rule class.
