### ISSUE TITLE
callable rule

### ISSUE THREAD

**Issue by Broutard** [laravel/nova-issues#3437]
- Laravel Version: 8.46.0
- Nova Version: 3.26.1
- PHP Version: 7.3

### Description:
When a callable is passed to rules() without an array, an exception is raised (only if there is no other rule before)

### Detailed steps to reproduce the issue on a fresh Nova installation:
```
Select::make('f1')
    ->options(['S' => 'Small', 'M' => 'Medium', 'L' => 'Large'])
    ->rules(function ($attribute, $value, $fail) {
        return $fail('This rule fails.');
    }),
```
=> Too few arguments to function App\\Nova\\Test::App\\Nova\\{closure}(), 1 passed and exactly 3 expected

```
Select::make('f1')
    ->options(['S' => 'Small', 'M' => 'Medium', 'L' => 'Large'])
    ->rules('required', function ($attribute, $value, $fail) {
        return $fail('This rule fails.');
    }),
```
```
Select::make('f1')
    ->options(['S' => 'Small', 'M' => 'Medium', 'L' => 'Large'])
    ->rules([function ($attribute, $value, $fail) {
        return $fail('This rule fails.');
    }]),
```
=> Works as expected

**Comment by crynobone** [comment]
That's what expected at the moment, closure usage is limited to the following.

```php
Select::make('f1')
    ->options(['S' => 'Small', 'M' => 'Medium', 'L' => 'Large'])
    ->rules(function ($request) {
        return [
            function ($attribute, $value, $fail) {
                return $fail('This rule fails.');
            },
        ];
    }),
```

**Comment by Broutard** [comment]
Ok, but why it works when it associated with another rule ?
Seems not documented: https://nova.laravel.com/docs/3.0/resources/validation.html#rules
