### ISSUE TITLE
validation issue on hasMany  inline function

### ISSUE THREAD

**Issue by abdulSF** [laravel/nova-issues#3443]
On the following code. I am using hasMany with inline relation. But when I add validation on fields in "BundlePublications". It is not working.

// Bundle Resource
HasMany::make('Bundle Product', 'BundlePublications',
\App\Nova\BundlePublication::class)
->inline(),

//BundlePublications Resource
Number::make('Quantity', 'qty')->rules('required'),

**Comment by crynobone** [comment]
Inline for HasMany isn't a feature made by Laravel Nova. You should ask the package maintainer for the relevant 3rd party package.
