### ISSUE TITLE
Tooltip on index view prevents resource action buttons from being clickable

### ISSUE THREAD

**Issue by JernejHartman** [laravel/nova-issues#3445]
- Laravel Version: 8.44.0
- Nova Version: 3.26.1
- PHP Version: 8.0.2
- Browser type and version: Any

### Description:
When there is only one row on index resource view, the resource action buttons (view, edit, delete, restore) are not clickable because the button's tooltip is incorrectly positioned on hover. This happens because the parent (the table container in this case) has a overflow-x: auto set and when there is only a single row displayed there is not enough space to properly calculate the position of the tooltip. The tooltip then gets displayed directly over the button, making it unclickable. More info on this subject can be found [here](https://github.com/Akryum/v-tooltip/issues/192#issuecomment-514328339). Note that this issue only happens when the table is fully visible (eg. no scrollbars are displayed) and only a single row is inside.

To resolve this issue you have to pass `defaultBoundariesElement: 'window',` when installing the v-tooltip component. Below is a workaround the issue, but did not test if this fix has any other implication with tooltips being used elsewhere.

Here is the full JS code that fixes this bug (you have to register the JS file through Nova::script):

```
import VTooltip from 'v-tooltip'

Nova.booting((Vue, router, store) => {
    Vue.use(VTooltip, {
      defaultBoundariesElement: 'window',
    });
});
```

### Detailed steps to reproduce the issue on a fresh Nova installation:

Create a Nova resource and display only a single item in the list. Try clicking any of the resource action buttons (view, edit, delete).

**Comment by crynobone** [comment]
https://user-images.githubusercontent.com/172966/122547484-be1ee400-d062-11eb-9a7d-023d00ca521f.mp4

Unable to replicate.

**Comment by JernejHartman** [comment]
I've managed to figure out what the issue was. We have extra CSS's applied to our nova theme, which reduces the height of each table row:

```
.table td {
  height: auto;
}
```

Not sure if this still applies as a bug, I can close this issue if it does not. Would be great if this would somehow be applied in nova directly.

**Comment by davidhemphill** [comment]
This isn't really a bug due to the customized CSS. You can however get a similar effect on the table row height by specifying the "tight" styling on for the resource table: https://nova.laravel.com/docs/3.0/resources/#table-styles
