### ISSUE TITLE
BelongsToMany fields not displaying when combined with fieldsForIndex()

### ISSUE THREAD

**Issue by henryavila** [laravel/nova-issues#3453]
- Laravel Version: 8.47.0
- Nova Version: 3.26.1
- PHP Version: 8.0

### Description:
The BelongsToMany fields not displaying if the resource has `fieldsForIndex()`

### Detailed steps to reproduce the issue on a fresh Nova installation:
In a relation between `App` and `Area`, define the `BelongsToMany` relation in both resources
```php

//Area
BelongsToMany::make('Apps', 'apps', NovaApp::class)->fields(new AppAreaFields()),

// App
BelongsToMany::make('Áreas', 'areas', NovaArea::class)->fields(new AppAreaFields()),

// AppAreaFields
  public function __invoke()
  {
      return [
          Boolean::make('Access', 'allow_access_to_employees_area')
              ->displayUsing(fn () => isset($this->pivot) ? $this->pivot->allow_access_to_employees_area : null),
      ];
  }

// in both models, I have
->withPivot('allow_access_to_employees_area');
```

If the resource has the method `fieldsForIndex()` the content of `AppAreaFields` is not displayed. If I remove the `fieldsForIndex()`, the content of `AppAreaFields` is displayed.

**Comment by crynobone** [comment]
please provide full code, I don't think I understand what you meant about having `fieldsForIndex()`

**Comment by henryavila** [comment]
Hi @crynobone, for `fieldsForIndex()`  I mean this: https://nova.laravel.com/docs/3.0/resources/fields.html#dynamic-field-methods

Basically, if I use Dynamic Field Methods (as point in doc on above link) on a resource, the BelongsToMany relation don't show the pivot data.

The resource will get just the fields defined in `fieldsForIndex()` and ignore the BelongsToMany fields

Hope it's more clear now.

**Comment by henryavila** [comment]
Sorry @crynobone, The problem is that I have to replicate the BelongsToMany Field on  `fieldsForIndex()`. Making it it work.
Thanks for the attention!
