### ISSUE TITLE
Using a casted enum field results in an "is not nullable" error

### ISSUE THREAD

**Issue by Synchro** [laravel/nova-issues#3456]
- Laravel Version: 8.42
- Nova Version: 3.26.1
- PHP Version: 8.0.7

### Description:

I have a model with contains a [Spatie/Enum](https://packagist.org/packages/spatie/enum) property, which is cast in the model:

    protected $casts = [
        'type' => PointsType::class,
    ];

I define this in a Nova resource like this:

    Select::make('Type')
        ->default(PointsType::return())
        ->options(array_combine(PointsType::toLabels(), PointsType::toValues())),

When I go to the "create" page for this resource in Nova, I get this error:

> Field type on App\Models\Points is not nullable

This field is indeed not nullable, but that's why I'm providing a default value. If I comment out the cast, the error goes away and the page loads correctly, including the default value, but of course I also lose the automatic casting features. Adding `nullable()` to the Nova field doesn't help.

How can I get Nova to use the default value and avoid this error?

**Comment by Synchro** [comment]
I have worked around it using:

    protected $casts = [
        'type' => PointsType::class . ':nullable',
    ];

This way the cast stays working, but it does seem unnecessary as this property is not nullable.

**Comment by crynobone** [comment]
This seems to be a question for `spatie/enum` rather than Laravel Nova. `default()` should just resolve a scalar value and if `App\Models\Points::return()` does that Laravel Nova should have no problem using it.

**Comment by Synchro** [comment]
Well `return()` does return a string, which is why I'm somewhat mystified!

**Comment by crynobone** [comment]
> I'm wondering if it's creating an empty instance prior to setting the defaults or something?

Again, if this related to `spatie/enum` I would say it best to report it the package repository. I don't think the error even comes from Laravel Nova.

https://github.com/spatie/laravel-enum/blob/055a7bb1747632c184d4fbe5d40bfb3656f1a8b0/src/Exceptions/NotNullableEnumField.php
