### ISSUE TITLE
Trigger event "field-change" for FileField

### ISSUE THREAD

**Issue by lisotton** [laravel/nova-issues#3459]
Hi, 

Most of the fields trigger an event `Nova.$emit(this.field.attribute + '-change'...` when there is a change to the input, but it is not the case for `FileField`, there are some events when using `VaporFile`, but I think should emit an event for `FileField` as well.

Best regards,

Leandro Isotton

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by lisotton** [comment]
I have a resource for Podcasts and I would like to extract the duration of the audio to populate the field `duration` after the file is selected.

**Comment by crynobone** [comment]
> I have a resource for Podcasts and I would like to extract the duration of the audio to populate the field duration after the file is selected.

So the event has to emit the full file? Other field changes event just send scalar values (mostly string/array etc).

**Comment by lisotton** [comment]
Yes @crynobone, for example in my case, to be able to use `FileReader`, I need the `event.currentTarget.files[0]`.
