### ISSUE TITLE
[3.27.0] ID Fields not showing any value on Index View

### ISSUE THREAD

**Issue by mstaack** [laravel/nova-issues#3463]
Latest Nova: 3.27.0
Latest Laravel: 8.49.0

With the latest nova update all my ID values are gone only(!) in the index view:

![image](https://user-images.githubusercontent.com/10169509/123960172-48ded780-d9af-11eb-94d5-63d2c91c87be.png)
![image](https://user-images.githubusercontent.com/10169509/123960208-5300d600-d9af-11eb-9822-1593a2961695.png)

In the Detail View all is fine permission wise.

I am using currently this snippet to determine permissions in my ressource:
```php
public static function authorizedToViewAny(Request $request)
    {
        return $request->user()->can('venues');
    }

    public function authorizeToView(Request $request)
    {
        return $request->user()->can('venues');
    }

    public function authorizedToView(Request $request)
    {
        return $request->user()->can('venues');
    }
```

Guess this is related somehow to the new changes from the changelog:

```
Nova will no longer show an ID field link if the user isn't allowed to view the resource.
```

**Comment by crynobone** [comment]
The commit just disable link, and not the ID itself. You definitely has another issue here.

**Comment by mstaack** [comment]
reverting solves the issue so far:
```
  - Downgrading laravel/nova (3.27.0 => 3.26.1)
 ```

**Comment by crynobone** [comment]
All the changes in `resources/js/components/Index/IdField.vue`. It should fall under `v-else-if` when user not authorized to view.

**Comment by mstaack** [comment]
well the variable does not exists, as i mentioned in the js error above. 

```
TypeError: Cannot read property 'authorizedToView' of undefined
    at a.render (app.js?id=002c49299d24455547bf:1)
    at a.t._render (vendor.js?id=158eb2009eabe0a47c04:1)
    at a.hn.before (vendor.js?id=158eb2009eabe0a47c04:1)
    at hn.get (vendor.js?id=158eb2009eabe0a47c04:1)
    at new hn (vendor.js?id=158eb2009eabe0a47c04:1)
    at vendor.js?id=158eb2009eabe0a47c04:1
    at a.Ln.$mount (vendor.js?id=158eb2009eabe0a47c04:1)
    at a.Ln.$mount (vendor.js?id=158eb2009eabe0a47c04:1)
    at init (vendor.js?id=158eb2009eabe0a47c04:1)
    at vendor.js?id=158eb2009eabe0a47c04:1
```

might use:
```
resource?.authorizedToView
```

**Comment by crynobone** [comment]
Created a reproducing code and unable to replicate above issue, See https://github.com/nova-issues/issue-3463/commit/19ccb0e0fc5e8f8d975fc10d055e7aeb940cb4d5

![image](https://user-images.githubusercontent.com/172966/123964750-5bc0ce80-d9e6-11eb-8727-81063804a094.png)

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/123964966-975b9880-d9e6-11eb-8403-adf079335c33.png)

If you have any 3rd party package and it overrides `resources/js/components/Index/ResourceTableRow.vue` that would be the cause of this issue. And the 3rd party package need to be updated to support `v3.27.0`.

**Comment by mstaack** [comment]
ok found it thank you for the help:

https://github.com/optimistdigital/nova-sortable/blob/master/resources/js/components/ResourceTableRow.vue#L35
