### ISSUE TITLE
Ambiguous id on massive delete

### ISSUE THREAD

**Issue by GautierDele** [laravel/nova-issues#3466]
- Laravel Version: 8.49.0
- Nova Version: 3.27.0
- PHP Version: 7.4.20
- Database Driver & Version:
- Operating System and Version: Windows 10
- Browser type and version: Google chrome
- Reproduction Repository: Might be easy to reproduce on your side, tell me if not :)

### Description:

Basically when we massivelly delete a resource it does display an error.

It seems like the condition is quite strange ? Giving a "where id > x" (see next screens).

### Detailed steps to reproduce the issue on a fresh Nova installation:

Go to a resource:
![image](https://user-images.githubusercontent.com/12382966/124602592-4ece3000-de69-11eb-9987-62d325df06f8.png)

Apply a filter with a join on an external table:
![image](https://user-images.githubusercontent.com/12382966/124602625-58f02e80-de69-11eb-8c31-c16611e40291.png)

Select all resources:
![image](https://user-images.githubusercontent.com/12382966/124602681-660d1d80-de69-11eb-83e1-17a171d346f2.png)

Delete those:
![image](https://user-images.githubusercontent.com/12382966/124602725-6f968580-de69-11eb-8abd-f2eeea4509c0.png)

The error:
![image](https://user-images.githubusercontent.com/12382966/124602773-7d4c0b00-de69-11eb-80c3-8c0b38a7c0c9.png)

It seems like some have been deleted:
![image](https://user-images.githubusercontent.com/12382966/124602862-981e7f80-de69-11eb-93be-1e156ea5e428.png)

I don't quite understand or really know the functioning of Nova on this. Do not hesitate to ask further questions.
I did try to delete without filters and it's working well.

**Comment by crynobone** [comment]
Would appreciate code example, mainly resource and filter so I can replicate the issue and create tests for it.

**Comment by crynobone** [comment]
Just an update, I tried to replicate the issue and unable to replicate the issue. Would definitely need the code example.

https://github.com/laravel/nova-dusk-suite/commit/8356423cf1b088103d5b131b428fb3662fffa275

**Comment by GautierDele** [comment]
Ok I will try to provide you something clear

**Comment by GautierDele** [comment]
@crynobone there you have it: https://github.com/GautierDele/nova-test-bug

You can simply migrate and seed and then filter with the user filter. Massive delete will push the error.

**Comment by GautierDele** [comment]
Hello @davidhemphill 
Did you close this because it has been resolved ? 
Thanks

**Comment by davidhemphill** [comment]
Yep! I merged the fix and it'll come out in the next release. 👍

**Comment by crynobone** [comment]
Fixed in v3.28.0: https://nova.laravel.com/releases/3.28.0
