### ISSUE TITLE
MorphMany relationship don't working in Nova Resources

### ISSUE THREAD

**Issue by rodralme** [laravel/nova-issues#347]
I tried to use MorphMany resources but it didn't work.

**Comment by lucasromanojf** [comment]
No data was returned when using MorphMany. Tried to get the related models using tinker and it worked, which means that the relation is working properly. But the MorphMany field isn't returning data.

**Comment by lluisandreu** [comment]
Yes, that is not working for me either.

**Comment by davidhemphill** [comment]
We are unable to debug your issue without a reproducible code example.
