### ISSUE TITLE
The value of the Slug Field on the current resource gets overwritten from another resource

### ISSUE THREAD

**Issue by abishekrsrikaanth** [laravel/nova-issues#3470]
- Laravel Version: 8.50.0
- Nova Version: 3.27.0
- PHP Version: 8.0
- Database Driver & Version: MySQL
- Operating System and Version: Mac OS Big Sur
- Browser type and version: Brave 1.26.74

### Description:
The Slug Field on the current resource is affected by the `Create` resource of a BelongsTo Field.

Here is the code:

```
    Text::make('Name'),
    BelongsTo::make('Vendor', 'vendor', Vendor::class)->showCreateRelationButton(function () use ($request) {
        return $request->isUpdateOrUpdateAttachedRequest() == false;
    }),
    ....
    Slug::make('Slug', 'slug')->from('Name')->showOnUpdating(false),
```

Below is a screencast of the issue.

![CleanShot 2021-07-15 at 03 25 36](https://user-images.githubusercontent.com/1639302/125698365-0359dd35-9f26-471a-8173-275c601e57cb.gif)

The Slug Field is configured to use the `Name` field on the current resource. The `Create` relation opens a modal that has a `Name` field. The `Name` field on the `Create` relation modal conflicts with the current resource causing the `Slug` field use the Name field from the `Create` Modal.

**Comment by crynobone** [comment]
Fixed in v3.28.0: https://nova.laravel.com/releases/3.28.0
