### ISSUE TITLE
The BelongsTo field dropdown throws `Trying to get property 'resourceClass' of non-object` when not present in `fields()` method

### ISSUE THREAD

**Issue by 949mac** [laravel/nova-issues#3471]
- Laravel Version: 8
- Nova Version: 3.27
- PHP Version: 7.4
- Database Driver & Version: MySQL
- Operating System and Version: Mac

### Description:

The BelongsTo field dropdown is empty if the corresponding field doesn't exist in the `fields()` method.

### Detailed steps to reproduce the issue on a fresh Nova installation:

- [ ] Create a BelongsTo field in `fieldsForCreate()` but omit it from `fields()`
- [ ] Go to page, and observe empty dropdown with `Trying to get property 'resourceClass' of non-object` error

#### Example 

BelongsTo field doesn't populate when the corresponding field does not exist in the `fields()` method
```
    public function fieldsForCreate()
    {
        return [
            BelongsTo::make('Case Manager', 'case_manager'),
        ];
    }

    public function fields(Request $request)
    {
        return [
            // ❗ missing `BelongsTo::make('Case Manager', 'case_manager') throws error
        ];
    }
                
```

![image](https://user-images.githubusercontent.com/23151962/125843487-581b43a7-7b47-4354-bc99-bcd49b3a4304.png)

Adding the corresponding field to the `fields()` method then renders as expected.
```
    public function fieldsForCreate()
    {
        return [
            BelongsTo::make('Case Manager', 'case_manager'),
        ];
    }

    public function fields(Request $request)
    {
        return [
            BelongsTo::make('Case Manager', 'case_manager'), // 👈 This fixes it
        ];
    }
                
```

![image](https://user-images.githubusercontent.com/23151962/125843450-90260473-c2d5-4c49-a972-92747db1216f.png)

**Comment by crynobone** [comment]
Fixed in v3.28.0: https://nova.laravel.com/releases/3.28.0
