### ISSUE TITLE
showCreateRelationButton shows only new created item

### ISSUE THREAD

**Issue by haythoo** [laravel/nova-issues#3472]
- Laravel Version: 8.40
- Nova Version: v3.27.0
- PHP Version: 7.3
- Database Driver & Version: MySQL 8
- Operating System and Version: Mac Big Sur
- Browser type and version: Chrome latest

### Description:
I'm trying to use Creating Inline Relations like this:
`BelongsTo::make('category')->withoutTrashed()->showCreateRelationButton(),`

The inline creating is working, but the select shows only the new created category.

### Detailed steps to reproduce the issue on a fresh Nova installation:

![Screen Recording 2021-07-16 at 6 56 05 PM](https://user-images.githubusercontent.com/3076507/125975658-fec5ab64-deb7-4017-8f26-019db134b01f.gif)

**Comment by haythoo** [comment]
Sorry, check this video:

https://user-images.githubusercontent.com/3076507/125975918-26bd455a-267a-42cc-9db6-294c979f052c.mov

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by haythoo** [comment]
But this is not feature, this is bug, the feature is there, it is not working properly.

**Comment by crynobone** [comment]
> But this is not feature, this is bug, the feature is there, it is not working properly.

The code working as intended, therefore this is a change request and threat differently from a bug.

**Comment by haythoo** [comment]
Thanks dear, got it now.
