### ISSUE TITLE
Null values are replaced by the the default value in Detail view

### ISSUE THREAD

**Issue by leandreallema** [laravel/nova-issues#3473]
- Laravel Version: 7.30.4
- Nova Version: 3.26.1
- PHP Version: 7.4.15
- Database Driver & Version: mysql  Ver 15.1 Distrib 10.4.17-MariaDB
- Operating System and Version: Windows 10 Home Version	10.0.19042 Build 19042
- Browser type and version: Google Chrome  91.0.4472.124

### Description:

A field using a default value will show the default value on the detail view when its value is null. As per the documentation, the default value should be only used to populate fields at creation. If the value of a field is null, it is what should be shown on de detail view, not the default value.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Create the following field:

- Create a model with a **nullable** field.
- Create a resource for the model.
- Create a **nullable** field on the resource for the field. Assign a **default value** on that field.
Ex: `Text::make('MyField')->rules(['nullable'])->default('Default')`
- Create a new instance of the model by **keeping the field's value to null** (Empty the field before saving).
![image](https://user-images.githubusercontent.com/87537844/125980984-4bb90c56-4c22-499c-abfe-b1a1ae645c1f.png)
- Go to the newly created instance's detail page.
- The field displayed value is the **default value instead of null**. (It will show 'Default' instead of '-')
![image](https://user-images.githubusercontent.com/87537844/125981168-71bef653-aa2a-4c01-8042-bb6964ea4aba.png)

Without the `->default('Default')`, it looks like this:
![image](https://user-images.githubusercontent.com/87537844/125981371-d6bd457f-b2fe-4fcb-89cd-ed0142436320.png)
This is what is expected to show even with a default value.

**Comment by crynobone** [comment]
Yes, that's the current behavior for default and will only be fixed on the next major release to avoid any breaking changes. 

For such a requirement, you mostly just want a default value on creating.

https://crynobone.com/add-field-default-only-on-create-on-laravel-nova/
