### ISSUE TITLE
Laravel nova api slow performance the first time

### ISSUE THREAD

**Issue by ttungbmt** [laravel/nova-issues#3474]
- Laravel Version: 8.5.22
- Nova Version: 3.26.1
- PHP Version: 7.4.4
- Database Driver & Version:
- Operating System and Version: Windows 10
- Browser type and version: Chrome

### Description:

![image](https://user-images.githubusercontent.com/12232155/126336183-512e336c-7d04-4d68-8a36-e21bb46eb978.png)

**Comment by davidhemphill** [comment]
Please give us more information on your environment and setup, along with any other information that could help us demonstrate the issue.

**Comment by crynobone** [comment]
It would be obvious when the project requires many 3rd party packages, and there's not a good way to combat this when some of the requested stylesheets have higher priority than others: e.g: `nova-tailwind` which is 3.0MB
