### ISSUE TITLE
Add defaultHour and defaultMinute to DateFilter.vue

### ISSUE THREAD

**Issue by keizah7** [laravel/nova-issues#3475]
Just noticed you add datetime picker hour and minute increments option. Our project really needs ability to change date filter default hour and time in filter. Thanks!

https://flatpickr.js.org/options/

![image](https://user-images.githubusercontent.com/49227202/126634612-485d33ab-8cba-4a7c-b4e2-4bb698d4ef60.png)

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
DateFilter bundle with Laravel Nova doesn't have time option enabled. You probably referring to 3rd party package here.

**Comment by keizah7** [comment]
@crynobone yes.
https://github.com/keizah7/nova-date-filter

It would be perfect if this functionality appears in nova itself.

I did these options myself in
https://github.com/keizah7/nova-date-filter/commit/e5ade3957ddc086c25d0d9bab4d41a9b57daf584
but after production compile, nova throws error. I can use this feature only with unminified code
