### ISSUE TITLE
On IPad ,Date field inside action modal randomly closes modal while focusing 

### ISSUE THREAD

**Issue by Pamposgsk** [laravel/nova-issues#3476]
When focusing a date field with an action modal, it will sometimes dismiss the modal.This does not happen anymore if using laptop but it happens on iPad

Iam using the latest frameworks

**Comment by sedlatschek** [comment]
I've also had this happening a few times, but on desktop. I was not able to pin it down to a certain circumstance yet.

**Comment by mcadet** [comment]
In fact, it's happening on my Macbook pro too with chrome browser. We need to click perfectly on the placeholder otherwise randomly close the modal.

**Comment by albalooshi** [comment]
+1

**Comment by crynobone** [comment]
Released in v3.30.0 <https://nova.laravel.com/releases/3.30.0>
