### ISSUE TITLE
Sorting relationships on dot notation

### ISSUE THREAD

**Issue by GautierDele** [laravel/nova-issues#3477]
- Laravel Version: 8.51.0
- Nova Version: 3.27.0
- PHP Version: 8.0.8
- Database Driver & Version: MSSQL

### Description:

When you set a text field with dot notation to refeer a relationship:
```php
Text::make(__('Transmission Mode'), 'doc.typetelecom.NOM_TYPE_TELECOM')
    ->sortable(),
```

The field is displaying well but when you try to sort this field, the following error arrives:
```
SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]L'identificateur en plusieurs parties \"doc.typetelecom.NOM_TYPE_TELECOM\" ne peut pas être lié. (SQL: select top 26 * from [NETWORK_DOC_FICHIER] order by [doc].[typetelecom].[NOM_TYPE_TELECOM] asc)
```

Basically, eloquent is trying to use dot notation in the sql query which seems strange.

Is this related to mssql ?
Is this a bad way of doing on our side ? Do we need to approach this problem another way ?

### Detailed steps to reproduce the issue on a fresh Nova installation:
Make a text with dot notation on a relationship with the sortable functionnality.

Sort on index.

Thanks,
Gautier

**Comment by crynobone** [comment]
It's not possible to make a sortable with dot notation (relationship) as it wouldn't be able to be translated to a proper SQL query.

**Comment by GautierDele** [comment]
I truelly believe this should be included in the core package.

By the way for all the googlers coming here, here you have my workaround:

```php
// App\Nova\Resource.php
// ...
    /**
     * Apply any applicable orderings to the query.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @param  array  $orderings
     * @return \Illuminate\Database\Eloquent\Builder
     */
    protected static function applyOrderings($query, array $orderings)
    {
        $orderings = array_filter($orderings);

        if (empty($orderings)) {
            return empty($query->getQuery()->orders) && ! static::usesScout()
                ? $query->latest($query->getModel()->getQualifiedKeyName())
                : $query;
        }

        foreach ($orderings as $column => $direction) {
            if (Str::contains($column, '.')) {
                $query->joinRelationship(Str::beforeLast($column, '.'));
                $query->orderBy(Str::afterLast($column, '.'), $direction);
            } else {
                $query->orderBy($column, $direction);
            }
        }

        return $query;
    }
// ...
```

I'm using `https://github.com/kirschbaum-development/eloquent-power-joins` to sort but you can manually do it on your side.

**Comment by crynobone** [comment]
Feel free to use it on your project. For the core we need to balance feature for most users, while this may be great performance impact will be different between applications.

**Comment by GautierDele** [comment]
I don't really get why this might impact performance for most users since this is user intended but no problem about it ;)

have a good day
