### ISSUE TITLE
Default sorting on ID (primary key)

### ISSUE THREAD

**Issue by developeritsme** [laravel/nova-issues#348]
**Nova version 1.0.8**

Method `applyOrderings` on trait `PerformsQueries` always adds orderBy model's primary key ordering!

```php
public static function indexQuery(NovaRequest $request, $query)
{
    return $query->orderBy('field1')->orderBy('field2');
}
```

should produce query
```sql
SELECT * FROM table ORDER BY field1, field2
```

but it produces
```sql
SELECT * FROM table ORDER BY id DESC, field1, field2
```

so adds `id decs, ` in front of desired order(s)

@themsaid @taylorotwell

**Comment by vocalspace** [comment]
This is also a problem with the count request, which does
```
select count(*) as aggregate from table order by ......
```
You cannot order a count... It may get ignored in MySql, but not in Postgres or others.

**Comment by vocalspace** [comment]
It also adds ``id [dir]``` to ``` select count(*) as aggregate ```   Which throws an error in PostgreSQL.

**Comment by noahlocke** [comment]
@developeritsme and @vocalspace `orderBy()` doesn't seem to work at all on the `indexQuery`?

**Comment by edgarnadal** [comment]
@davidhemphill please any workaround on this?

**Comment by edgarnadal** [comment]
As a workaround I overwrite the applyOrdering method in my resource:

```php
    /**
     * Apply any applicable orderings to the query.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @param  array  $orderings
     * @return \Illuminate\Database\Eloquent\Builder
     */
    protected static function applyOrderings($query, array $orderings)
    {
        return $query;
    }
```

**Comment by davidhemphill** [comment]
You can overwrite the `indexQuery` to customize sorting.

**Comment by noahlocke** [comment]
@davidhemphill did you read the issue? The problem is that no matter how you attempt to order the `indexQuery`, it appears that it's hard coded. So no, you can't overwrite the `indexQuery` to customize sorting... unless we're all missing something?

@developeritsme have you found this issue to persist?

**Comment by victorpfm** [comment]
> @davidhemphill did you read the issue? The problem is that no matter how you attempt to order the `indexQuery`, it appears that it's hard coded. So no, you can't overwrite the `indexQuery` to customize sorting... unless we're all missing something?
> 
> @developeritsme have you found this issue to persist?

Tried to overwrite the indexQuery method but it doesn't affect the query at all.

**Comment by gizburdt** [comment]
I have the same issue

**Comment by wvervuurt** [comment]
Same here, I contacted David to ask for re-opening this issue

**Comment by WasserEsser** [comment]
@davidhemphill Why is this issue not being re-opened?

**Comment by madsem** [comment]
@davidhemphill I have the same issue, I'm building a reporting model that is supposed to show aggregated sales statistics, and have additional lenses attached to it.

I'm overriding the indexQuery as you said:

`LandingPageReport` resource:
```php
public static function indexQuery(NovaRequest $request, $query)
    {
        return $query
            ->select('landing_pages.name')
            ->join('landing_pages', 'landing_page_id', '=', 'landing_pages.id')
            ->selectRaw('sum(visits) as visits')
            ->selectRaw('sum(impressions) as impressions')
            ->selectRaw('sum(clicks) as clicks')
            ->selectRaw('avg(ctr) as ctr')
            ->selectRaw('sum(conversions) as conversions')
            ->selectRaw('avg(conversion_rate) as conversion_rate')
            ->selectRaw('sum(revenue) as revenue')
            ->selectRaw('sum(spend) as spend')
            ->selectRaw('avg(return_on_ad_spend) as return_on_ad_spend')
            ->selectRaw('avg(earnings_per_visit) as earnings_per_visit')
            ->selectRaw('avg(earnings_per_click) as earnings_per_click')
            ->selectRaw('round(avg(time_on_site), 0) as time_on_site')
            ->groupBy('landing_pages.name')
            ->orderBy('revenue', 'desc');
    }
```

But this errors out:
```sql
ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'laravel.landing_page_reports.id'
```

Because Nova **always** orders by `id`, which it really shouldn't if the idea is that a developer can customize the index.

This also goes hand in hand with issue #655

**Comment by elev8studio** [comment]
I can't believe this is still an issue 3 years on!! I'm having the same problem. It's a massive bug.. how has this not been fixed??

**Comment by crynobone** [comment]
```php
/**
     * Build an "index" query for the given resource.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public static function indexQuery(NovaRequest $request, $query)
    {
        if (empty($request->orderByDirection)) {
            $query->reorder()->orderBy('field1')->orderBy('field2');
        }

        return $query;
    }
```
