### ISSUE TITLE
Laravel Scout - sortable fields won't work

### ISSUE THREAD

**Issue by GautierDele** [laravel/nova-issues#3480]
- Laravel Version: 8.51.0
- Nova Version: 3.27.0
- PHP Version: 8.0.8
- Database Driver & Version: MSSQL
- Laravel Scout Version: 9.2.3 with meilisearch

### Description:

Basically, it's known that you can't order by with laravel scout, the solution provided is to create another index with the sorting by default. Don't know if there is anything special to include this in Nova.
The problem on Nova is that it's not informing the user about this problem:
![image](https://user-images.githubusercontent.com/12382966/127321211-f52004f4-0f23-4ac5-86ec-f9c5f3a7f7c9.png)
As you can see I ran a search to force scout search and sorted by id but the sort won't change anything ...

The better would be to support multiple indexes for each sortable fields but this might be heavy.

**Comment by crynobone** [comment]
The main focus of Scout support is that it's will sort the search results based on the most relevant results based on each engine technology.

**Comment by GautierDele** [comment]
Effectively I missed that part but that doesn't change the fact that sorting when searching won't lead to anything and can mislead users ?

**Comment by crynobone** [comment]
> Effectively I missed that part but that doesn't change the fact that sorting when searching won't lead to anything and can mislead users ?

I will submit a PR to hide sort button when searching via Scout.

**Comment by crynobone** [comment]
Fixed in v3.28.0: https://nova.laravel.com/releases/3.28.0
