### ISSUE TITLE
Field file, download link not working

### ISSUE THREAD

**Issue by Pro-Empresa** [laravel/nova-issues#3481]
- Laravel Version: 8.40
- Nova Version: 3.27.0
- PHP Version: 7.4.3
- Database Driver & Version:
- Operating System and Version: ubuntu 20.04
- Browser type and version: Firefox, Google Chrome
- Reproduction Repository: https://github.com/###/###

### Description:

File Field download link not working on firefox and in google chrome download link work but show download.html file with error Failed - No file
Someone can help me pass to this error, maybe another way to download resource file.

In advance thank you.

**Comment by crynobone** [comment]
We have dusk tests testing against this use case. Please provide a reproducing steps so we can understand your use case.

**Comment by Pro-Empresa** [comment]
first thank you for your replay.

I am new using nova and i have one consultant resource and i am using file field to uploads files like identification document but when i upload the file all is good but the file field download link dont work.

When i click the download link nothing happen in firefox browser but when i test in google chrome i get this errror:
Filed - no file

<img width="730" alt="47960460-2c5a2980-dfd3-11e8-8941-bf1923aaed55" src="https://user-images.githubusercontent.com/86831275/127642092-2c926722-98b0-41de-a3f7-8142e5afaf0e.png">

when i click in download link using firefox not happen and when i using google chrome see the image error:

![Screenshot from 2021-07-30 08-46-56](https://user-images.githubusercontent.com/86831275/127642259-760b61a8-b160-450a-ab28-4e898f338ccd.png)

This error is the same with this #933

One more thing, when i remove consultant model the file stored is not removed from folder.

**Comment by crynobone** [comment]
Can you share the code? Or create a repository containing full example just like under https://github.com/nova-issues/

**Comment by Pro-Empresa** [comment]
can i give you access to my repository in bitbucket.

**Comment by Pro-Empresa** [comment]
Hi, i implemente file field in other resource and its work great, so the problem is in my side i will check my code.

Thank you crynobone for you time.
