### ISSUE TITLE
Select options different for Select::make and for a filter select when you require an optgroup

### ISSUE THREAD

**Issue by warksit** [laravel/nova-issues#3483]
- Laravel Version: 8.51.0 
- Nova Version: 3.27.0
- PHP Version: 8.0.8

### Select options different for Select::make and for a filter select when you require an optgroup

For Select::make the options array neeeds to use `'label'`:
```
Select::make('Manager', 'manager_id')
    ->options([
        4 => ['group'=> 'Managers', 'label' => "Andrew"],
        3 =>  ['group'=> 'Managers', 'label' => "Rhiannon"],
        2 =>  ['group'=> 'Managers', 'label' => "Tom"],
        6 => ['group'=> 'Directors', 'label' => "Peter"]
    ]),
```
For the options on a filter it needs to use `'name'`:
```
public function options(Request $request)
    {
        return [
            4 => ['group'=> 'Managers', 'name' => "Andrew"],
            3 =>  ['group'=> 'Managers', 'name' => "Rhiannon"],
            2 =>  ['group'=> 'Managers', 'name' => "Tom"],
            6 => ['group'=> 'Directors', 'name' => "Peter"]
        ];
    }
```
Should they not be consistent?

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
