### ISSUE TITLE
Database Notification Component

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#3486]
Would be cool if Nova had Laravel's native notification `database` channel support

I wrote a component you can use if you want

- https://github.com/vuewind/jetstream/blob/master/src/Elements/Notifications.vue
- https://vuewind.com/jetstream/elements (first component)
- https://github.com/dillingham/notifications/blob/main/src/NotificationController.php

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
