### ISSUE TITLE
[Feature Request] full page paginated global search results

### ISSUE THREAD

**Issue by jbraband** [laravel/nova-issues#349]
One thing that Nova is missing (as far as I can see) is a full page search results view. I think its sometimes tough to find what you want with only 5 results per searchable model in the dropdown below the search field.

Granted, the dropdown is functional and useful for quick targeted searches, but broad general searches I think would be better served with a more traditional search interface. Perhaps with a collapsible filter area allowing you to check off which models to search and other filters to be brainstormed at a later date.

This could make a great nova tool project for someone in the meantime, but I think it'd be important for it to be tied into the user experience of the global search input in the header of Nova (i.e. hitting <enter> flips the VusJS app to the results views)

**Comment by albalooshi** [comment]
+1

**Comment by davidhemphill** [comment]
This would be best as an addon-package.
