### ISSUE TITLE
Undefined property: Laravel\Nova\Actions\CallQueuedAction::$queue

### ISSUE THREAD

**Issue by Synchro** [laravel/nova-issues#3495]
- Laravel Version: 8.52.0
- Nova Version: 3.27
- PHP Version: 8.0.8
- Database Driver & Version: MySQL 8
- Operating System and Version: Ubuntu 20.04
- Browser type and version: n/a

### Description:

I have an action that triggers a queued job, so I followed the docs that say I just need to add an `implements ShouldQueue` to make it work, and I have added in the queue traits:

    use InteractsWithQueue;
    use Queueable;

It does seem to work, however, it also throws this warning:

```
Undefined property: Laravel\Nova\Actions\CallQueuedAction::$queue
 Illuminate\Queue\Queue->pushOn(...)
nova/src/Actions/DispatchAction.php:73:in `pushOn'
69	
70	            Queue::connection(static::connection($action))->pushOn(
71	                static::queue($action),
72	                new CallQueuedAction(
73	                    $action, $method, $request->resolveFields(), $models, $batchId
74	                )
75	            );
76	        });
77	    }
```

The docs say that I can optionally customise the `$queue` property in the constructor, however, I don't want to and I'm happy for it to use whatever the default queue is. Why is it not using the default queue and throwing this error?

My job is dispatched like this:

```php
    public function handle(ActionFields $fields, Collection $models)
    {
        foreach ($models as $model) {
            Artisan::queue(
                'products:make',
                [
                    'gtin'     => $model->gtin,
                    'quantity' => $fields->quantity,
                    'batch'    => $fields->batch,
                ]
            );
        }

        return Action::message('Products queued for creation; they will be ready soon!');
    }
```

**Comment by crynobone** [comment]
Can you share reproducing code?

**Comment by Synchro** [comment]
The only thing I missed off is that I'm extending `DestructiveAction` rather than plain `Action`:

```php
namespace App\Nova\Actions;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Laravel\Nova\Actions\Action;
use Laravel\Nova\Actions\DestructiveAction;

class CreateProducts extends DestructiveAction implements ShouldQueue
{
    use InteractsWithQueue;
    use Queueable;
    use SerializesModels;

```

`CallQueuedAction` does not occur anywhere in my code.

Other than what is inside the queued job itself, there is nothing else, but I don't see that should make any difference because this issue occurs before it gets that far. I have no control over the type of that `$action` param (that I'm aware of), and I'm not touching the `$queue` property at all, so surely this is internal to Nova?

**Comment by crynobone** [comment]
Unable to reproduce the issue, See https://github.com/nova-issues/issue-3495/commit/ba2bac681efdcf62f588631ce48c6ec1176c04e4
