### ISSUE TITLE
Add link and note to icons to nova docs

### ISSUE THREAD

**Issue by tomhatzer** [laravel/nova-issues#35]
Thank you once again for getting me the information about the used icons in nova, @themsaid !

It would be great if others could also profit from this information, so why not add it to the nova docs?

For everyone interested, the used icons are the Heroicons by @sschoger : https://github.com/sschoger/heroicons-ui

Have a great day!

**Comment by tomhatzer** [comment]
The link at the bottom is the one that‘s taking you to the repository with the icons 😊👍🏻

**Comment by davidhemphill** [comment]
This belongs over here https://github.com/laravel/nova-docs :-D
