### ISSUE TITLE
file field not work in nova action

### ISSUE THREAD

**Issue by Pro-Empresa** [laravel/nova-issues#3508]
Hi, the file field not working on nova action, saved path on database is (/tmp/phpvOH6aS) and no file is upload to directory.
I am using nova: v3.28 

my action file:

'
class SendPaymentProof extends Action
{
    use InteractsWithQueue, Queueable;

    /* public function __construct()
    {
        $this->runCallback = function (Request $request) {
            return true;
        };
    } */

    /**
     * The displayable name of the action.
     *
     * @var string
     */
    public $name = 'Enviar Comprovativo';

    /**
     * Perform the action on the given models.
     *
     * @param  \Laravel\Nova\Fields\ActionFields  $fields
     * @param  \Illuminate\Support\Collection  $models
     * @return mixed
     */
    public function handle(ActionFields $fields, Collection $models)
    {
        
        foreach ($models as $model){
            $model->update([
                'payment_proof_attachment' => $fields->payment_proof,
            ]);

            //Mail::to($model->email)->queue(new ConsultantEmail($model, 'Invalidate'));
        }

        return Action::message('Comprovativo pagamento enviado com sucesso.');
    }

    /**
     * Get the fields available on the action.
     *
     * @return array
     */
    public function fields()
    {
        return [
            File::make('Comprovativo Pagamento', 'payment_proof')->disk('payments')
        ];
    }
}`

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
