### ISSUE TITLE
Action onlyOnDetail, display when single selecting record

### ISSUE THREAD

**Issue by Jam0r85** [laravel/nova-issues#351]
Would be nice to have an action which should only be performed on a single record be displayed when selecting a single record from the index screen but hiding when more than one record is selected?

**Comment by dkulyk** [comment]
**onlyOnDetail** mean show only on detail view.

**Comment by Rogierownage** [comment]
> **onlyOnDetail** mean show only on detail view.

Right, so perhaps there should be a new function, something like **->singleItemOnly()**, that does what this issue describes.

**Comment by dkulyk** [comment]
I believe in future releases we will add ability to add custom action buttons, also button to run specified action.

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by phoenixg** [comment]
I want this feature too.
