### ISSUE TITLE
Order By on Dynamic Relatable Query

### ISSUE THREAD

**Issue by jBOKA** [laravel/nova-issues#3512]
- Laravel Version: 8.54.0
- Nova Version: 3.28.0
- PHP Version: 7.4

### Description:

In Nova 3.26.0 a fix has been introduced for
https://github.com/laravel/nova-issues/issues/1484
which allowed to disable the default sorting-by-title for dropdowns of associatable/related fields, so that the `relatableQuery` could be used with custom sorting.

Somehow I still have a bug, which messes up the sorting in my (dynamic) relatableQuery (here relatableDeliveries). 
The code applies to the query, but upon creation of the query in

Laravel\Nova\Fields\BelongsTo->buildAssociatableQuery
in line 270 after the make call, the query already has a orderBy on the `id` field of my associatable (here: Delivery), which preceeds and overrides any other sorting that follows.

DOES NOT WORK:
```
    public static function relatableDeliveries(NovaRequest $request, $query)
    {
        return $query->orderBy('field1', 'ASC');
    }
```

WORKAROUND BUT NOT SOLUTION:
Adding a reorder to reset the orderBy in the query
```
    public static function relatableDeliveries(NovaRequest $request, $query)
    {
        return $query->reorder()->defaultList();
    }
```

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by jBOKA** [comment]
Hey, what's up with you, did you read my description?

I'm not asking for a feature.
My relatable query does definitely not allow to sort custom, which it intentionally should as seen in the efforts in https://github.com/laravel/nova-issues/issues/1484

I even took the time to dig, why it doesn't work. Would you be so respectful to tell me why this is a feature request?

**Comment by crynobone** [comment]
> My relatable query does definitely not allow to sort custom, which it intentionally should as seen in the efforts in #1484

PR for #1484 (which is also marked as `feature`) handles disabling sorting from Eloquent Collection, it was never meant to handle any query order by changes. 

> Would you be so respectful to tell me why this is a feature request?

You may see this as something not working as expected, but it's simply not something it was designed to handle yet, which made it a feature request and we need to examine the impact of such feature.

From what I can see, this would ignore any sorting from `Resourcei::indexQuery()` coming from `Laravel\Nova\Fields\BelongsTo->buildAssociatableQuery::272` and potentially can introduce a "bug" to someone else.

**Comment by jBOKA** [comment]
Mior thanks for your time. I understand now.
