### ISSUE TITLE
login with username

### ISSUE THREAD

**Issue by kephren226** [laravel/nova-issues#3513]
I think we should have a better way for using username or whatever filed we want for login instead of email 
I'm looking for something like that but until now i haven't found a good solution

**Comment by davidhemphill** [comment]
Nova's authentication is implemented using laravel/ui. We encourage any project which needs to veer from the defaults to implement the authentication controllers themselves and modify the published Nova views to use the correct column for the menu.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
