### ISSUE TITLE
Route names

### ISSUE THREAD

**Issue by wimski** [laravel/nova-issues#3514]
I would like to have [named routes](https://laravel.com/docs/8.x/routing#named-routes) for Nova, because:

> Named routes allow the convenient generation of URLs or redirects for specific routes.

Sometimes I want to link to a Nova page from my own code and I'd rather use a well-defined route name (almost like a constant) than the literal path.

For example:
```php
Route::get('/{resource}', 'ResourceIndexController@handle')->name('resource.index');
Route::get('/{resource}/{resourceId}', 'ResourceShowController@handle')->name('resource.detail');
```

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
