### ISSUE TITLE
Both using `confirmText` and `fields` in Action modal

### ISSUE THREAD

**Issue by medvinator** [laravel/nova-issues#3515]
Now `confirmText` is shown only if there are no fields  🥺
It would be great in some cases to use both.

**Example**:
<img src="https://user-images.githubusercontent.com/21067613/130096001-f49fd069-198c-4c90-9919-ecfa31510fcd.png" width="50%">

Thanks!

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by mgralikowski** [comment]
```        
<p v-if="action.fields.length == 0" class="text-80 px-8 my-8">
    {{ action.confirmText }}
</p>
<div v-else>
    <!-- Action Fields -->
</div>
```

I don't understand what is the intention of this condition as we can always pass empty string if we don't want this text. Now we are limited to only fields without any description above them.

**Comment by ry167** [comment]
You can use `->help('Lorem ipsum...')` to add help text below the field at least. 

I agree the `if` condition above is a poor choice - please allow both

**Comment by mgralikowski** [comment]
Yea, but it looks unnatural 😔
