### ISSUE TITLE
Remove .text-white class from Icons 

### ISSUE THREAD

**Issue by PinkFlufflyLlama** [laravel/nova-issues#3516]
# Remove .text-white class from Icons 
In nova, the icons Edit and Run Action have the .text-white class on the SVG meaning that if you were to set a light colored sidebar and then override .text-white to make the text dark, it also makes those icons color darker. Removing the class and adding a color in the .btn-icon class or if that is not doable, adding a .btn-white class in place of .text-white would solve this issue.

Image of the icons in question:
![image](https://user-images.githubusercontent.com/13354155/130096820-7458f5f6-acb6-4526-ae79-7802fb340442.png)

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by PinkFlufflyLlama** [comment]
> 👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

Hey, I know that this is subjective, but as there is a misuse of .text-white to style something that isn't text is this not a bug?

**Comment by crynobone** [comment]
> but as there is a misuse of .text-white to style something that isn't text is this not a bug?

This is the default, changing it now may solve your issue but can potentially cause a bug to others.
