### ISSUE TITLE
Set Action name for `action_events` table

### ISSUE THREAD

**Issue by medvinator** [laravel/nova-issues#3517]
I use localization in Nova App:  English and Russian.

I created Action with custom name
```php
    public function name(): string
    {
        return __('Clone');
    }
```

To show this value in the Action Selector and the title of the Action Modal.

But in Action Log in column `name` stored a localized value (ex. in Russian **Clone** is `Клонировать`.)

It is not clear how to localize this value for English when viewing the Action Log page.

Maybe the Action could use a different property for the Action Selector and the title of the Action Modal?

Or give the opportunity to set the name of the Action for the Log.

Now i use that hack (but it's uncomfortable and ugly)

```php
// App\Models\ActionEvent.php

class ActionEvent extends \Laravel\Nova\Actions\ActionEvent
{
    public static function defaultAttributes(ActionRequest $request, Action $action, $batchId, $status = 'running'): array
    {
        $attributes = parent::defaultAttributes($request, $action, $batchId, $status);
        if (method_exists($action, 'nameForLog')) {
            $attributes['name'] = $action->nameForLog();
        }

        return $attributes;
    }
}

```

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
