### ISSUE TITLE
custom validation msg not working

### ISSUE THREAD

**Issue by mateusgalasso** [laravel/nova-issues#3525]
- Laravel Version: 8
- Nova Version: 3
- PHP Version: 8
### Description:
the format in validation.php is not working
```
'custom' => [
        'aabb' => [
            'relatable' => 'Another msg',
        ],
    ],
```

### Detailed steps to reproduce the issue on a fresh Nova installation:
publish laravel nova validation and change

**Comment by crynobone** [comment]
This should be possible now with Laravel Framework 9.2 and above combined with [After Validation Hooks](https://nova.laravel.com/docs/3.0/resources/validation.html#after-validation-hooks):

```php
protected static function afterValidation(NovaRequest $request, $validator)
{
    $validator->setCustomMessages([
        Relatable::class => 'Another msg',
    ]);
}
```
