### ISSUE TITLE
DateTime field 24 hour issue.

### ISSUE THREAD

**Issue by latwelve** [laravel/nova-issues#3529]
- Laravel Version: 8x
- Nova Version: 2x
- PHP Version: 8x

I've seen an old issue relating to this with a solution but it was closed due to them not having a registered version of nova.
However I believe the issue still exists as I don't see any mention of it in the documentation.

Here is the issue:
https://github.com/laravel/nova-issues/issues/1069

Basically there is no way to set the calendar popup to display as 24hours even when the format for the dates shown in the field can be set to 24 hours which is a little unusual from a users perspective. Please allows us to pass the variables to the picker so we have full control of the date format in the picker modal.

**Comment by crynobone** [comment]
By default Laravel Nova set 12/24 hours based on client locale, changing this would be a change request.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
