### ISSUE TITLE
Updating resource with attached photos - field is required error

### ISSUE THREAD

**Issue by bradykeeling** [laravel/nova-issues#353]
Nova 1.0.8

When I try to update a resource that has an image previously attached to it, it gives an error saying "field is required." 

The update form shows the thumbnail of image, but says "no file selected".

I'm able to access the resource image in my views and the file name is stored in the database, so I'm not sure why I am getting these errors.  Am I missing something?

Please see screenshots:

![screen shot 2018-08-30 at 11 40 40 am](https://user-images.githubusercontent.com/3791996/44866303-7bd64f00-ac4a-11e8-9f53-5272d3b7f14f.png)

![screen shot 2018-08-30 at 11 42 43 am](https://user-images.githubusercontent.com/3791996/44866313-80026c80-ac4a-11e8-8f8c-492c6fc59c75.png)

![screen shot 2018-08-30 at 11 43 36 am](https://user-images.githubusercontent.com/3791996/44866325-8395f380-ac4a-11e8-962e-d9401087cb87.png)

**Comment by v1nk0** [comment]
I guess this is nothing browser related.

The input field seems to stay empty when not overwriting the existing file/image/avatar, so for the validation, the "required" rule is not matched.

**Comment by StanBarrows** [comment]
@bradykeeling 

Did you found a workaround for this problem?

**Comment by bradykeeling** [comment]
@StanBarrows Not really... I just disabled the "required" rule until a fix is released.

**Comment by lfukumori** [comment]
Try use this closure instead 'required' rule:
```
function ($attribute, $value, $fail) use ($request) {
    $model = $this->resource->find($request->route('resourceId'));
    if (empty($value) && empty($model->$attribute)) {
        $fail(__(':Attribute is required.', ['attribute' => __($attribute)]));
    }
},
```

**Comment by bradykeeling** [comment]
Thanks @lfukumori, I'll give this a go!

Also, what is the purpose of the double underscore "__" before the $attribute variable?

**Comment by lfukumori** [comment]
The $fail() parameter is a fail message. Something like "Field is required.". The function with double underscore __() is for translate this sentence and attribute.

**Comment by dwyer14** [comment]
Nova 1.1.4 and somewhat related—I'm also getting this error for Image fields that aren't required, but are submitted empty, regardless of previously attached images/files. Also tried adding `sometimes` to rules; no dice. Example code:
```
Image::make('Email Image')
  ->rules('mimes:jpeg,jpg,png')
  ->help('Image used in header of all email messages.'),

Image::make('Social Image')
  ->rules('sometimes', 'mimes:jpeg,jpg,png')
  ->help('Image used in social network preview cards.'),
```

![image](https://user-images.githubusercontent.com/13950848/47197215-58ff1780-d32a-11e8-8b51-b759eebb65bc.png)

**Comment by ceejayoz** [comment]
@dwyer14 I opened a new issue for that; it's a separate thing. #1050

**Comment by NioTeX** [comment]
#885

**Comment by davidhemphill** [comment]
I believe this issue should be fixed. Please post a new issue if the issue persists.
