### ISSUE TITLE
Pivot fields are not shown on overview when using multiple BelongsToMany relationships for same model

### ISSUE THREAD

**Issue by sgerritsen** [laravel/nova-issues#3533]
- Laravel Version: 8.56.0
- Nova Version: 3.29.0
- PHP Version: 7.3.29
- Database Driver & Version: mysql 10.2.33 MariaDB
- Operating System and Version: MacOS Big Sur 11.5.2
- Browser type and version: Google Chrome 92.0.4515.159
- Reproduction Repository: https://github.com/sgerritsen/nova-multiple-belongsToMany-relations-bug

### Description:
I have 2 models (`Application` and `PartnerSchool`) which are connected via two BelongsToMany relationships (`partnerSchools()` and `selectedDestination()`). Each relationship has its own pivot table (`application_partner_schools` and `selected_destinations`) and therefore its own pivot fields.

Model/Application relationships:
![image](https://user-images.githubusercontent.com/41360073/131497147-3f35a4ec-7f42-44bb-a507-d0ba88e60ddf.png)

Model/PartnerSchool relationship:
![image](https://user-images.githubusercontent.com/41360073/131501273-4c6f57de-3be6-4f65-8d74-08b1a1d00df3.png)

#### 1
The first problem is that the pivot fields of the relationships shown on the Nova/Application are determined by the fields() method on the Nova/PartnerSchool model.
This is counterintuitive, since I would expect the `fields()` method on the Nova/Application model to determine which pivot fields are shown on the Application detail page, not the `fields()` method on the Nova/PartnerSchool.

Nova/Application model:
![image](https://user-images.githubusercontent.com/41360073/131499704-03566a7b-7562-4d56-a329-2ce467f9ee3f.png)

Nova/PartnerSchool model:
![image](https://user-images.githubusercontent.com/41360073/131499861-3ae2d880-349e-4cc2-9f4a-9f7870f935d0.png)

Result on Nova/Application detail:
![image](https://user-images.githubusercontent.com/41360073/131500089-41e9a1d6-922f-4c0c-afe8-c33e324ba724.png)

#### 2
The second issue is that when I add the second BelongToMany relationship (`selectedDestination()`) to the Nova/Application detail page, that it only the pivot field from the `partnerSchools()` (`order`). When I then try to add the relationship to the Nova/PartnerSchool and add the pivot field (`selected`) in the `fields()` method, then none of the pivot fields are shown on the Application detail page.

Nova/Application model:
![image](https://user-images.githubusercontent.com/41360073/131501979-d5e5f86e-5291-4d40-b1a8-ecf37ec5cab5.png)

Nova/PartnerSchool model:
![image](https://user-images.githubusercontent.com/41360073/131502084-d7961742-fcd1-40ef-9e13-29c857ff4f6e.png)

Result on Nova/Application detail for selected destination:
![image](https://user-images.githubusercontent.com/41360073/131502214-a36256d9-5347-42b9-adda-22ad21f3207e.png)

Result on Nova/Application detail for partner schools:
![image](https://user-images.githubusercontent.com/41360073/131502250-480fc6f9-8b86-4aa9-b99a-e67ccedce964.png)

PS: The fact that `selectedDestination()` is singular is intentional.

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Create 2 models.
2. Make 2 BelongsToMany relationships using separate pivot tables, each with their own pivot fields.
3. Add the BelongsToMany relationships to the Nova models `fields()` methods.
4. Watch the bug unfold.

**Comment by crynobone** [comment]
Can you share a full repository?

**Comment by sgerritsen** [comment]
@crynobone I've prepared a fresh repository showcasing the bug. Try commenting the different BelongToMany fields to simulate the issues.

https://github.com/sgerritsen/nova-multiple-belongsToMany-relations-bug
