### ISSUE TITLE
BelongsToMany allowDuplicateRelations rule "NotExactlyAttached" doesn't filter out computed fields

### ISSUE THREAD

**Issue by Tarpsvo** [laravel/nova-issues#3535]
- Laravel Version: 8.58
- Nova Version: 3.29.0
- PHP Version: 7.4

### Description:

BelongsToMany field has a method "allowDuplicateRelations" which adds the rule "NotExactlyAttached" to the field.

The rules passes() method gets the fields like so:

```php
$resource->resolvePivotFields($this->request, $this->request->relatedResource)
  ->each(function ($field) use ($query) {
    $query->wherePivot($field->attribute, $this->request->input($field->attribute));
  });
```

But it does not filter out fields that are computed, so the final query will contain clauses like `table_name.ComputedField IS NULL` and the query will fail as the column `ComputedField` does not exist.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Create a BelongsToMany relationship with a computed field.

```php
BelongsToMany::make('Attributes', 'productAttributes')
    ->fields(function () {
        return [
            Text::make('Value', function ($resource) {
                return $resource->value;
            })->onlyOnIndex(),
        ];
    })
    ->allowDuplicateRelations(),
```

**Comment by crynobone** [comment]
Released in v3.30.0 <https://nova.laravel.com/releases/3.30.0>
