### ISSUE TITLE
MorphTo field returns an error when running action 

### ISSUE THREAD

**Issue by WillyReyno** [laravel/nova-issues#3538]
- Laravel Version: 8.55.0
- Nova Version: 3.29.0
- PHP Version: 7.4.14

### Description:

I'm trying to set up an action which needs to retrieve a MorphTo relationship in order to run.

Here is my action's fields method: 
```
public function fields()
    {
        return [
            MorphTo::make('commentable')->types([\App\Nova\Post::class, \App\Nova\Video::class])
                ->withoutTrashed()
                ->searchable(),
        ];
    }
```

`App\Models\Comment.php` relationship: 
```
    public function commentable(): MorphTo
    {
        return $this->morphTo();
    }
```

`App\Models\Post.php` &  `App\Models\Video.php` relationship: 
```
    public function comments(): MorphMany
    {
        return $this->morphMany(Comment::class, 'commentable');
    }
```

When the action modal appears, fields are correctly displayed, I can select between Post & Video, and then search through them to select the entry I want. However when I click on the "Run action" submit button, the following exception occurs: 

 ```
exception: "Error"
file: "/var/www/html/vendor/laravel/nova/src/Fields/MorphTo.php"
line: 296
message: "Object of class Illuminate\\Support\\Fluent could not be converted to string"
```

Is this an issue with nova or am I doing something wrong?

**Comment by crynobone** [comment]
Action does not aware of the model and doesn't support relationship fields.
