### ISSUE TITLE
Where are the bug fixes?

### ISSUE THREAD

**Issue by lucasromanojf** [laravel/nova-issues#354]
At the beginning lots of bug fixes were happening, sometimes having more than one release per day.

Now there are a lot of issues/requests open and no releases fixing them. Most of them are simple to fix (like hardcoded translations for example) but they don't get fixed or the fixes don't get released.

We'd like to have news from Nova team, maybe some kind of roadmap so we can see the status of the issues/requests, and if they will be done or not. Currently the issues/requests mostly don't even get answer.

Please Nova team, let us know what is happening!

**Comment by davidhemphill** [comment]
There have been regular releases and fixes and there will continue to be. Stayed tuned to the releases section of the Nova website.
