### ISSUE TITLE
Boolean field shows as `false` when the underlying column is `null`

### ISSUE THREAD

**Issue by chescos** [laravel/nova-issues#3541]
The Boolean field doesn't seem to support nullable columns, it shows as `false`:

```php
            Boolean::make('Test', 'test')
                ->nullable()
                ->rules('nullable', 'boolean'),
```

**Comment by crynobone** [comment]
Boolean only handle `true` and `false` at the moment. Any change to this can be considered as breaking.

**Comment by chescos** [comment]
So nullable boolean fields are just not supported?

**Comment by crynobone** [comment]
As you have mention as well, null behave as false at the moment.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
`Boolean` UI in Laravel Nova has always been `true` vs `false` state. Icon in Index and Detail and Checkbox on Form. 

Introducing a new `nullable` state would require a huge revamp to above UI.
