### ISSUE TITLE
Please show "Your session expired!" when I hit create a resource button and not after I hit submit button.

### ISSUE THREAD

**Issue by hasnatwe** [laravel/nova-issues#3543]
So my web browser remains open most of the time with hibernation. Is there a way to show session expired when I hit submit button during resource creation? After filling long list of fields when I see I need to reload then all effort is just gone.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
