### ISSUE TITLE
date_format validation

### ISSUE THREAD

**Issue by mahfoudfx** [laravel/nova-issues#3544]
- Laravel Version: 8.59.0
- Nova Version: 3.29.0
- PHP Version: 8.0.10
- Database Driver & Version:
- Operating System and Version: Ubuntu 20.04.3 LTS
- Browser type and version: Microsoft Edge 93.0.961.38 / Google Chrome 93.0.4577.63

### Description:
Validation rule using date_format shows an error due to format.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Here is the fields example :
`Date::make('Birth date', 'b_date')->format('DD/MM/YYYY')->pickerDisplayFormat('d/m/Y')->rules('required','date_format:d/m/Y'),`

Below, the error message
![image](https://user-images.githubusercontent.com/31103481/132967144-f85ea8e5-e4bd-4f3e-b3a0-e16f848207a5.png)

**Comment by crynobone** [comment]
`->format()` is only used to display date on the input placeholder. Internally we only used `Y-m-d` between frontend and backend.

**Comment by mahfoudfx** [comment]
> `->format()` is only used to display date on the input placeholder. Internally we only used `Y-m-d` between frontend and backend.

Thanks for your reply.
So is there any solution to customize the date format for validation ?
I think this issue is very similar [#3284](https://github.com/laravel/nova-issues/issues/3284)

**Comment by crynobone** [comment]
> So is there any solution to customize the date format for validation ?

Format will always be `Y-m-d`
