### ISSUE TITLE
Slug field not working with arabic

### ISSUE THREAD

**Issue by maherelgamil** [laravel/nova-issues#3545]
- Laravel Version: 8.0
- Nova Version: 3.29.0
- PHP Version: 8.0.9
- Database Driver & Version:MySQL 8.0.9
- Operating System and Version: macos
- Browser type and version: chrome

### Description:
Slug field not working with Arabic text.

**Comment by crynobone** [comment]
This should be handled by slugify library: https://github.com/simov/slugify/issues/100

**Comment by maherelgamil** [comment]
@crynobone So, how can add signify options from the nova side ?!
