### ISSUE TITLE
Unique validation on BelongsTo field

### ISSUE THREAD

**Issue by mahfoudfx** [laravel/nova-issues#3546]
- Laravel Version: 8.59.0
- Nova Version: 3.29.0
- PHP Version: 8.0.10
- Database Driver & Version:
- Operating System and Version: Ubuntu 20.04.3 LTS
- Browser type and version: Microsoft Edge 93.0.961.38 / Google Chrome 93.0.4577.63

### Description:
Hello,
I have a **Gsample** model with `belongsTo` relation to barcode. The barcode on the **Gsample** model is defined to be unique.
When I try to choose a duplicate value, I get an SQL Integrity Check error message (which is correct BTW) rather than the field validation tool.
![image](https://user-images.githubusercontent.com/31103481/132997449-79806f93-f7da-4997-869d-27560c9e7363.png)

### Detailed steps to reproduce the issue on a fresh Nova installation:
**Gsample Model**
```php
class Gsample extends Model
    {
        protected $fillable = [
            'gmovementbarcode_barcode',
    }
public function gmovementbarcode()
    {
        return $this->belongsTo(\App\Models\Gmovementbarcode::class, 'gmovementbarcode_barcode', 'gbarcode_barcode');
    }
```
**Gsample Resource**
```php
BelongsTo::make(__('Barcode'),'gmovementbarcode', Gmovementbarcode::class)->sortable()->searchable()->withoutTrashed()->rules('required', 'unique:App\Models\Gsample,gmovementbarcode_barcode'),
```

**Comment by crynobone** [comment]
Laravel Nova already pre-defined `Relatable` rule for belongs to. The above code isn't useful.

![image](https://user-images.githubusercontent.com/172966/133008120-643d4452-0778-47db-a257-e3742be9a672.png)
