### ISSUE TITLE
Change field's properties based on value of another field

### ISSUE THREAD

**Issue by lucasromanojf** [laravel/nova-issues#355]
Would be great if we have the possibility of changing a field based on other field's value. For example, I have a checkbox that enables/disables another field, or hides/shows another field.

**Comment by lucasromanojf** [comment]
Also, that could be applied to selects/belongsto fields, where after selecting a value, something could happen to another specified field

**Comment by noahlocke** [comment]
#300

**Comment by rickmacgillis** [comment]
It'd be especially nice if I can use @noahlocke's `showIf` method to see if the resource model has a certain parameter set in order to display it. (Ex. Check if the resource is an admin, and then show Spark announcements for the user.)

**Comment by unxsist** [comment]
We've just released a package that allows you to display fields depending on values of other fields, it's not fully what you've requested, but it's a start. Maybe it helpful: https://novapackages.com/packages/epartment/nova-dependency-container

**Comment by noahlocke** [comment]
@davidhemphill is this no longer planned? Asking because I saw you closed #300 and mentioned it's not planned for addition into core...

**Comment by davidhemphill** [comment]
I would use the package listed above as it seems to do everything you want.

**Comment by lucasromanojf** [comment]
I agree to @noahlocke , this should be a core functionality. Hiding/showing/disabling/enabling fields based on other fields values is a very common use case. Also @davidhemphill, it looks like the package is abandoned since October 2018 and has issues.

**Comment by jordyvandomselaar** [comment]
Bump, gotta agree there as well.

**Comment by seandelaney** [comment]
:+1

**Comment by batFormat** [comment]
+1!

**Comment by ronnytorresmtz** [comment]
+1

**Comment by PrafullaKumarSahu** [comment]
+1

**Comment by rchl2** [comment]
+1

**Comment by Lotfull** [comment]
+1

**Comment by monadashish** [comment]
Everythings works perfect , but my validation for that field stopped working

**Comment by ephraimlambarte** [comment]
+1

**Comment by josespinal** [comment]
+1

**Comment by marijoo** [comment]
+1

**Comment by BenWalters** [comment]
@davidhemphill @jbrooksuk has this been thought about any further? The 3rd party package doesn't do exactly what is required, at least not without lots of code duplication! It would be a great feature to have native to Nova and something I keep requiring.
Thanks.

**Comment by Payetus** [comment]
+1

**Comment by geodeveloper** [comment]
+1

**Comment by lu-roth** [comment]
+1

**Comment by jhayg12** [comment]
+1
