### ISSUE TITLE
BelongsToMany field with pivot fields 'id' displays the pivot id as resource id label on relation table

### ISSUE THREAD

**Issue by MilosCabarkapa** [laravel/nova-issues#3557]
- Laravel Version: 8.60.0
- Nova Version: 3.28.0
- PHP Version: 8.0.9
- Database Driver & Version:
- Operating System and Version: windows 10
- Browser type and version: Chrome 93.0.4577.82 

### Description:

I have a User to User many to many relation and I'm trying to insert the pivot table id into the belongsToMany field, but when I do that my resource id label gets displayed as pivot table id. 
The links are correct and they point to the right User resource but the label is showing the pivot table id instead of the User id.

This is my code for the belongsToMany field inside App\Nova\User resource :
```
BelongsToMany::make('Matches', 'matches', 'App\Nova\User')->fields(function () {
             return [
                    DateTime::make('Matched at', 'created_at'),
                    Text::make('Record', function () {
                        $url = Nova::path() . "/resources/". Match::uriKey() ."/". $this->pivot->id); 
                        return "<a class='no-underline dim text-primary font-bold' href='{$url}'>{$this->pivot->id}</a>";
                    })->asHtml()
                ];
            }),
```

Front end display:
![BelongsToMany bug](https://user-images.githubusercontent.com/90902154/133764521-06726570-2d79-4984-a2fa-212a304cca47.jpg)

I also noticed that the `BelongsToField.vue` component takes `field.belongsToId` for the link and `field.value` as the label,
so I'm guessing that the `field.value` which should be the resource id gets overtighten by pivot id

**Comment by crynobone** [comment]
This is expected behaviour at the moment. Pivot doesn't have it's own View page, which is why you can only go to related Resource detail page.

**Comment by MilosCabarkapa** [comment]
So the expected behavior is for the resources `user.id` to be labeled with `pivot.id` value ? To be more specific the table id link that points to `nova/resources/user/293` instead of being labeled `293` which is the `user.id`, is being labeled and rendered as `6342`  which is `pivot.id`. That is the expected behavior for a link to resource id 293 to be labeled as 6342 ?

**Comment by PatrykTucki** [comment]
We're also experiencing this issue. 

The many-to-many relationship is User <-> Organisation with a pivot table in-between.
On the user resource page, each organisation resource row points to valid organisation resource.
However, pivot ID is displayed instead of an organisation ID (bug).
Also, pivot ID column is linked to organisation resource (also a bug).

![screenshot-localhost_8000-2022 08 17-14_00_06](https://user-images.githubusercontent.com/9299202/185113579-28415bee-c85c-4c20-833c-debf5dd99d45.png)

**Comment by crynobone** [comment]
@PatrykTucki if you have an issue/bug, please create new issue using the bug report template with full reproducing repository to demonstrate the issue.
