### ISSUE TITLE
Flatpickr date picker not loading on Nova resource creation screen.

### ISSUE THREAD

**Issue by calumfrogspark** [laravel/nova-issues#3558]
- Laravel Version: 8.58.0
- Nova Version: 3.19.0
- PHP Version: 8.08
- Database Driver & Version: mysql (10.5.9-MariaDB Homebrew)
- Operating System and Version: macOS 11.6 
- Browser type and version: Firefox (92.0)

### Description:
When adding a date field to a nova resource (using `Laravel\Nova\Fields\Date;` import) and then trying to load the field in question on the resource creation/edit page the field does not load.

Instead of getting a date picker field as expected, the field renders on the page as a simple text field.
Upon some exploration within the browser console, I get the error in the attached screenshot.

<img width="844" alt="Screenshot 2021-09-17 at 16 01 03" src="https://user-images.githubusercontent.com/55081509/133805107-24d688ad-780a-46db-ae24-74f6d34a1c3b.png">
<img width="967" alt="Screenshot 2021-09-17 at 16 01 21" src="https://user-images.githubusercontent.com/55081509/133805109-1a8a2ba3-ca87-4c2f-ad97-40256f55fc23.png">

I assume that this is the cause of the issue since the creation of the flatpickr element appears to be failing.

I am wondering if this is something that is localised to my project (maybe a configuration issue) or whether this is a bug in the `nova/public/vendor.js` file.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Te replicate the issue please follow the steps below:

1. Install laravel/nova 
2. Create the database and then a database table with a date field in the table.
3. Create a matching resource in nova for the test database table (i.e. in `app/Nova/NewResource.php`).
4. Import  `use Illuminate\Http\Request;` and `use Laravel\Nova\Fields\Date;` into the nova resource.
5. In the `public function fields()` function return a new `Date` field using `Date::make('<name of test date field here'),`.
6. Load the resource creation window in a browser to test if the datepicker is working.

**Comment by crynobone** [comment]
Please provide the full repository code containing the bug so we can debug the issue.

**Comment by calumfrogspark** [comment]
Unfortunately it wont be possible to provide the entire repo due to the fact that this is a business project and the repo is private/restricted.

Is there any more details I can give you to try and clarify this futher?

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/134005441-26cab490-5e02-4159-a644-176dab68890d.png)

Unable to replicate the issue. We need the reproducible code in order to replicate the problem as what was suggested didn't do it.

![image](https://user-images.githubusercontent.com/172966/134005637-b1c91c44-4fe8-49c6-8958-c2be9391a528.png)
