### ISSUE TITLE
Actions set to table row dont send viaRelationship params

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [laravel/nova-issues#3559]
- Laravel Version: 7.30.4
- Nova Version: 3.29.0
- PHP Version: 7.4.23
- Database Driver & Version: MySQL 8
- Operating System and Version: MacOS 11.5.2
- Browser type and version: Chrome 93.0.4577.82

### Description:

When setting actions to `onlyOnTableRow` or `showOnTableRow` for Resources shown in a `HasMany` on another resources detail page, it appears that the normal `viaRelationship`, `viaResource` etc query params are not sent to the action api POST request

For example a `User` may have a `HasMany` field for `Posts` which is using a Laravel `hasMany()` model method called `posts()` and if there is a table row Action on the `Post`, it appears the `via` query params are not being set.

However if I use the same action, but instead of making it on each row, its set up the 'normal' way (eg selecting Posts using the checkboxes and running the action from the dropdown at the top of the Posts area on the Users detail page) - then the `via` query params _are_ sent

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by matthewjumpsoffbuildings** [comment]
Perhaps I'm wrong but this feels kinda like a bug? It should be sending those params regardless of if the action is triggered the standard way, or via the table row button right?

**Comment by matthewjumpsoffbuildings** [comment]
@crynobone @davidhemphill - the solution is incredibly simple, and appears to be due to an oversight.

In `nova/resources/js/components/Index/ResourceTableRow.vue`, on line 33, the current version has:
```js
        <inline-action-selector
          v-if="availableActions.length > 0"
          class="mr-3"
          :resource="resource"
          :resource-name="resourceName"
          :actions="availableActions"
          :endpoint="actionsEndpoint"
          @actionExecuted="$emit('actionExecuted')"
        />
```

All that is required to make table row Action buttons/dropdowns correctly send query params, is to change it to this:
```js
        <inline-action-selector
          v-if="availableActions.length > 0"
          class="mr-3"
          :resource="resource"
          :resource-name="resourceName"
          :actions="availableActions"
          :endpoint="actionsEndpoint"
          :query-string="{          // add the missing query-string prop
            viaResource,
            viaResourceId,
            viaRelationship,
          }"
          @actionExecuted="$emit('actionExecuted')"
        />
```

**Comment by matthewjumpsoffbuildings** [comment]
Hell, when using the InlineActionSelector, which lives on ResourceTableRow, why not pass the `:resource` along to the Modal as well, and any fields inside it? eg in `InlineActionSelector.vue`
```html
    <!-- Action Confirmation Modal -->
    <portal to="modals">
      <component
        v-if="confirmActionModalOpened"
        class="text-left"
        :is="selectedAction.component"
        :working="working"
        :resource="resource"
        :selected-resources="selectedResources"
        :resource-name="resourceName"
        :action="selectedAction"
        :endpoint="endpoint"
        :errors="errors"
        @confirm="executeAction"
        @close="closeConfirmationModal"
      />
```
And then in `ConfirmActionModal.vue`, including the changes from https://github.com/laravel/nova-issues/issues/1813 where you should add the `:selectedResources` prop as well:
```html
          <!-- Action Fields -->
          <div
            class="action"
            v-for="field in action.fields"
            :key="field.attribute"
          >
            <component
              :is="'form-' + field.component"
              :errors="errors"
              :resource-name="resourceName"
              :field="field"
              :show-help-text="field.helpText != null"
              :resource="resource"
              :selectedResources="selectedResources"
            />
          </div>
```

@crynobone @davidhemphill these simple additions would make customising the information displayed in Action modals _so_ much more flexible via custom fields, without having to override core nova components
