### ISSUE TITLE
Hide resource from list when using `viewAny()` policy method

### ISSUE THREAD

**Issue by keesh7663** [laravel/nova-issues#356]
I'm configuring Nova to be both an administrative dashboard for my staff as well as a web ui for my users.  When using policies to restrict my users from viewing administrative resources, the resource still displays in the left pane and when clicking it directs the user to a 403 page.  This seems counter-intuitive for users who are going to be poking around the dashboard to see what they can and can't do.

My request is that when hiding a resource using the `viewAny()` policy method, it should completely hide it from the resource list, thus truly hiding it.

**Comment by keesh7663** [comment]
Ok, apologies for posting this, but I managed to get it to work easily.

**Comment by srottem** [comment]
How did you accomplish this?

**Comment by krgaurav1992** [comment]
@srottem 
Add this function to your resource class:
`public static function authorizedToViewAny(Request $request)
    {
        return false;
    }`

**Comment by MarlonRaphael** [comment]
@krgaurav1992 Example please
