### ISSUE TITLE
Typo: occured

### ISSUE THREAD

**Issue by ordago** [laravel/nova-issues#3567]
- Laravel Version: 8.60.0
- Nova Version: 3.29.0
- PHP Version: 7.4
- Database Driver & Version:

### Description:

I found a typo on this file:

vendor/laravel/nova/resources/lang/en.json

```diff
-      "An error occured while uploading the file.": "An error occured while uploading the file.",
+      "An error occurred while uploading the file.": "An error occurred while uploading the file.",
```

I noticed though the package Laravel-Lang/lang:

https://github.com/Laravel-Lang/lang/blob/e8eda353258c725ba14ced355e91089435ac4c18/locales/af/af.json#L36

https://www.yourdictionary.com/occured

### Detailed steps to reproduce the issue on a fresh Nova installation:

Install nova, see typo, 😮.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
