### ISSUE TITLE
Resource relationship view button modification

### ISSUE THREAD

**Issue by keizah7** [laravel/nova-issues#3568]
It would be cool, to pass relationship data (viaRelationship and so on) to view button as edit button has.

![image](https://user-images.githubusercontent.com/49227202/134855728-3d4ec255-74eb-41a1-9092-24faa8f711d8.png)

![image](https://user-images.githubusercontent.com/49227202/134855770-52aaff67-1fdd-4d89-88a6-bbacd1aecd9d.png)

If belongsToMany relation has many extra columns

```
BelongsToMany::make(__('Platforms'), 'platforms', Platform::class)
    ->fields(function () {
        return [
            SearchableSelect::make('User', 'user_id')
                ->resource(User::class), // or pivot model

            Number::make('Commission')
                ->help('%')
                ->rules('nullable', 'numeric', 'max:100'),

            Currency::make('Price without commission', 'price_without_commission')
                ->rules('nullable', 'numeric', 'min:0'),

            Currency::make('Public price', 'price_with_commission')
                ->help('(with commission)')
                ->rules('nullable', 'numeric', 'min:0'),
        ];
    }),

    DateTime::make(__('Uploaded at'), 'created_at')
        ->sortable()
        ->canSee(fn () => isset($this->pivot))
        ->displayUsing(fn () => isset($this->pivot) ? $this->pivot->created_at : null),
```

you cant open relation pivot table and view them all

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
