### ISSUE TITLE
relatableQuery $request parameter should have the i

### ISSUE THREAD

**Issue by gonzunigad** [laravel/nova-issues#357]
![image](https://user-images.githubusercontent.com/1103494/44875977-0a13fa80-ac76-11e8-939c-d2846ba21ae2.png)

I need to filter the data is returned to a relation, but in two different ways. 

**For example:** 
`Post` Resource have an author field and an editor field. Both are `Users`, but in one select i should list all the users, and in the other one, just the users who has a 'editor' role.

**Comment by gonzunigad** [comment]
And it looks like the orderBy is overridden afterwards. It always lists on alphabetical order, but in my case are a list of chronological statuses. I prefixed a number to the name to overcome this problem.

**Comment by noahlocke** [comment]
I think this is the same problem I'm encountering. I have Users, Clients, and Notes. When creating a Note, I first select a User (BelongsTo). Next I need to select a Client, but I only want the Clients that BelongsToMany Users. I've tried this with custom fields, extending the BelongsTo field, but I don't see any way to pass a filter to the /nova-api/{resource}/associatable/{field} endpoint...

**Comment by dkulyk** [comment]
You can check $request->viaRelationship for checking a foreign relation name.

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
