### ISSUE TITLE
Inconsistencies between Laravel and Laravel Nova relationship guessing

### ISSUE THREAD

**Issue by bintzandt** [laravel/nova-issues#3571]
- Laravel Version: 8.61.0
- Nova Version: 3.29.0
- PHP Version: 8.0

### Description:
There are inconsistencies between how Laravel and Laravel Nova guess relationships.

Laravel seems to adhere to camelCase relationships ([example](https://github.com/laravel/framework/blob/8918a9dda190c3dee436193a9cb0b5672c914e4e/src/Illuminate/Database/Eloquent/Factories/Factory.php#L517)).

Laravel Nova seems to adhere to snake_case relationships, see the line below. This line is copied from the constructor of the base `Field` class.
```
$this->attribute = $attribute ?? str_replace(' ', '_', Str::lower($name));
```

In the `BelongsTo` field, the `attribute` field is used for setting the relationship.

```
$this->belongsToRelationship = $this->attribute;
```

I'm not sure whether this inconsistency is intended but it feels weird that Laravel and Laravel Nova adhere to different constraints.

I'm curious what you think about this!

**Comment by crynobone** [comment]
Following should work:

```php
HasOne::make('Profile', 'userProfile'),
```

However I'm marking this for `next-series` `request`.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
