### ISSUE TITLE
Eagerloading in Global Search!

### ISSUE THREAD

**Issue by amidesfahani** [laravel/nova-issues#3575]
- Laravel Version: 8.42.1
- Nova Version: 3.29
- PHP Version: 8
- Database Driver & Version: MySql
- Operating System and Version: Windows 10
- Browser type and version: Firefox

### Description:
Nova Resource does not load relation fields in global search and it is null in title or subtitle functions. 
Resource and model $with variable populated.

**Comment by crynobone** [comment]
PR merged and pending next patch release.
