### ISSUE TITLE
[Feature Request] confirmation modal that cannot be closed in mandatory actions

### ISSUE THREAD

**Issue by suleymanozev** [laravel/nova-issues#3577]
confirmation modal that cannot be closed(Not clickable backdrop) in mandatory actions

**Comment by suleymanozev** [comment]
I'm currently using the action abstract class I've already written. It would be nice if it was in Nova.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by davidhemphill** [comment]
What happens if the user just refreshes?
