### ISSUE TITLE
Set Class and merge extraAttributes for fields

### ISSUE THREAD

**Issue by amidesfahani** [laravel/nova-issues#3578]
Hello
Please make it possible to set CSS Classes for fields.
and merge multiple extraAttributes in Field Class.

for example:
Text::make(__('Title'), 'title')->class('border-blue-500')->labelClass('text-red-600')->fieldClass('rtl text-black')

Thank you

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
