### ISSUE TITLE
Customize low and max values for Trend metrics.

### ISSUE THREAD

**Issue by wotta** [laravel/nova-issues#358]
So I am running into the following problem.
I am displaying the amount of money left on a balance within the last 7 days.

The issue is that it can be possible for a balance to be below `0` on days.
The graph doesn't show it at the moment.

So I looked into the code of the `Trend` metric card and I see the following config option : `low: 0,`.
While looking at the plugin used to display these metrics I saw that it can be configured to show less than `0`.

Can this be fixed so we can configure it from the metric classes?

**Comment by caseysprague** [comment]
+1 for this. My issue is that trends that have values that are very close to each other (33.24, 35.1, 31.5, etc.) are very difficult to visualize on a graph when the low is defaulted to zero. It's almost a straight line.

Maybe there's a better way to handle. All ears. :)

Thanks!

**Comment by wotta** [comment]
I submitted this as a feature request after talking with @themsaid.
We will see when this is implemented.
