### ISSUE TITLE
X icon missing in search field

### ISSUE THREAD

**Issue by brunolanevik** [laravel/nova-issues#3584]
- Laravel Version: 8.62.0
- Nova Version: 3.29.0
- PHP Version: 7.4.13
- Database Driver & Version:
- Operating System and Version: MacOS Big sur
- Browser type and version: Firefox 93.0

### Description:
When using the search function for resources the X has gone missing in Firefox. 
![Screenshot 2021-10-08 at 11 00 31](https://user-images.githubusercontent.com/686753/136531082-ac9b67ee-4df4-4d87-b9af-97554b2d31a9.png)

It does appear in Chrome:
![Screenshot 2021-10-08 at 11 02 18](https://user-images.githubusercontent.com/686753/136531107-466a2958-730d-4f74-9092-53226ce35236.png)

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Go to resource
- Input query in search field

**Comment by crynobone** [comment]
That Chrome own implementation for `<input type="search">`. Firefox doesn't have one at the moment.
