### ISSUE TITLE
Make 502 time-outs visible instead of showing the loading-spinner

### ISSUE THREAD

**Issue by Jaspur** [laravel/nova-issues#3587]
When using Nova with Vapor it'll happen sometimes that some resources cannot load correctly when pagination is set to a high number. This will respond with a 502 response, but visual there is a spinner that keeps loading. A toast that a time-out occurred or an error message instead of the loading-spinner would be more helpful for normal users (non-developers). Now I keep complains of users that loading takes very long, but actually a 502 time-out occured.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
> A toast that a time-out occurred or an error message instead of the loading-spinner would be more helpful for normal users (non-developers). Now I keep complains of users that loading takes very long, but actually a 502 time-out occurred.

Wouldn't Nova already show an error toast right now?
