### ISSUE TITLE
Model create is not firing on new resource

### ISSUE THREAD

**Issue by bcdennis** [laravel/nova-issues#359]
The event 'creating' doesn't appear to be firing when creating a new resource from inside Nova.

**Comment by bcdennis** [comment]
At first I thought I hadn't read the docs and closed the issue.  But I believe I've confirmed it.  I've tried assigning some code to fire via the boot method as well as wiring up an observer.

No code isn't executing for the creating event when a new model is created via Nova.

**Comment by davidhemphill** [comment]
Can you post the code you're using to reproduce this as a gist or inline?

**Comment by davidhemphill** [comment]
I'm not able to replicate your issue. I used an inline observer like this:

```php
<?php

namespace App;

use Ramsey\Uuid\Uuid;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    public static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            $model->uuid = Uuid::uuid4()->toString();
        });
    }
}
```

I also used an Observer object like this: 

```php
<?php

namespace App\Providers;

use App\Post;
use Ramsey\Uuid\Uuid;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Post::observe(PostObserver::class);
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }
}

class PostObserver {
    function creating($model)
    {
        $model->uuid = Uuid::uuid4()->toString();
    }
}
```

Both of these approaches worked fine.

**Comment by bcdennis** [comment]
Can you share your resource configuration?

**Comment by bcdennis** [comment]
I had overridden my constructor and missed calling the parent.

I apologize for wasting your time.

**Comment by davidhemphill** [comment]
Hey @bcdennis, it happens!
