### ISSUE TITLE
Double Nova menu dashboard

### ISSUE THREAD

**Issue by vapordev** [laravel/nova-issues#3599]
Hi there,

We have a slight issue where the Nova dashboard is replicating itself, but only on the live version? Locally is totally fine.

v: 3.29.0 then we updated to latest 3.30.0 yesterday with composer update and php artisan nova:publish - still same issue.
![Screenshot 2021-10-21 at 06 14 36](https://user-images.githubusercontent.com/68593178/138215556-870fd154-2b8f-4719-b6a5-9c6c36f791df.png)

**Comment by crynobone** [comment]
Can you share a reproducing steps?

**Comment by vapordev** [comment]
We use Laravel Vapor to push everything through, and we can't see anything here locally that would create this issue?
![Screenshot 2021-10-21 at 07 16 57](https://user-images.githubusercontent.com/68593178/138222057-f1fcee7a-357d-46ca-bd50-ecf8c60117bc.png)
![Screenshot 2021-10-21 at 07 17 57](https://user-images.githubusercontent.com/68593178/138222069-6360eb87-b5ea-4de3-bc24-e0562ded7525.png)
