### ISSUE TITLE
Some strings are not translatable

### ISSUE THREAD

**Issue by gonzunigad** [laravel/nova-issues#36]
Using 1.0.5
This is the creation form:

![image](https://user-images.githubusercontent.com/1103494/44537287-c0a33880-a6d4-11e8-81d1-c44002d6a694.png)

The title is not using the singular label defined on the resource. Is not working either on 'Create SINGULAR_NAME' button.

![image](https://user-images.githubusercontent.com/1103494/44537296-c4cf5600-a6d4-11e8-99ff-8dccd81fb4a0.png)

The 'Create & Add Another' translations is not working.
![image](https://user-images.githubusercontent.com/1103494/44537307-cd279100-a6d4-11e8-8050-b5378824b6e1.png)

**Comment by disitec** [comment]
More info here #61

**Comment by disitec** [comment]
Just confirming that in 1.0.6 release `Create &amp; Add Another` and `Update &amp; Continue Editing` are not translatable yet (I guess due to special chars?)

**Comment by YassineGherbi** [comment]
@disitec Confirmed! I fixed it by adding 
![image](https://user-images.githubusercontent.com/15906337/44622987-ac6d6000-a8bb-11e8-96ae-ec0b13ddc53b.png)
to my translation file. Just as a quick fix!

**Comment by davidhemphill** [comment]
Is this still an issue?

**Comment by disitec** [comment]
@davidhemphill not this one but a there are some places where localization does not work. Like here #480

**Comment by gonzunigad** [comment]
Thanks! Now almost every string is translatable. 

I am still having issues with `Increase` and `Decrease` strings. 
[image](https://user-images.githubusercontent.com/1103494/45849128-45e73080-bd07-11e8-90ac-cbe67d19bde9.png)

![image](https://user-images.githubusercontent.com/1103494/45849196-8050cd80-bd07-11e8-9f23-5bc74301578c.png)




I am using V1.1.1

**Comment by mvnobrega** [comment]
I am still having issues with no file selected inside upload buttons

**Comment by carloshc** [comment]
> I am still having issues with no file selected inside upload buttons

I found it in ``vendor/laravel/nova/resources/js/components/Form/FileField.vue`` line 88.

```javascript
    data: () => ({
        file: null,
        label: 'no file selected',
        fileName: '',
        removeModalOpen: false,
        missing: false,
        deleted: false,
        uploadErrors: new Errors(),
    }),
```
But I don't know hot to change it. I tried with ``withMeta()`` and didn't work:

```php
            // Don't work
            File::make('FIle','file')
                ->disk('local')
                ->withMeta(['extraAttributes' => [
                  'label' => 'teste']
                ])
                ->onlyOnForms(),

```

Any help?

**Comment by bonzai** [comment]
@carloshc: This has been fixed and will be included in the next release.
