### ISSUE TITLE
Can't create a custom field with latest laravel nova and sail / custom field does not render

### ISSUE THREAD

**Issue by Lednerb** [laravel/nova-issues#3603]
- Laravel Version: 8.67.0
- Nova Version: 3.3.0
- Sail Version: latest

### Description:
Running `./vendor/bin/sail php artisan nova:field lednerb/my-field-name` fails at the `npm install` process.
It seems that there is an issue with the `node-sass` compilation.

I've tested some workarounds, for example setting the required `laravel-mix` version in the `package.json` file to version `^6.0`.

The installation proceeds (although the `scripts` part has to be adjusted, see migration guide from `laravel-mix`), however there is another problem: The fields will not render when added to a resource's `fields` array.

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Use latest `sail` version
- run `php artisan nova:field acme/color-picker`
- confirm `Would you like to install the field's NPM dependencies? (yes/no) [yes]:`

### Error log
Errors start in line `8887`

[2021-10-22T20_00_10_045Z-debug.log](https://github.com/laravel/nova-issues/files/7401087/2021-10-22T20_00_10_045Z-debug.log)

**Comment by crynobone** [comment]
See https://github.com/laravel/docs/pull/7553
