### ISSUE TITLE
Restrict action to lense or filter

### ISSUE THREAD

**Issue by poxin13** [laravel/nova-issues#361]
Would like to only have certain actions available on a defined lense or filter. For example if I create a 'billing' lense, the ability to run an action on them should only display there and not on the primary resource index.

**Comment by adamthehutt** [comment]
I need this as well. For us it's a resource that has a "Pending" status filter, and certain actions can only be performed on a resource in the pending state.

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by dillingham** [comment]
This was released in 1.3.2
