### ISSUE TITLE
Add locale to slugify

### ISSUE THREAD

**Issue by haltsir** [laravel/nova-issues#3616]
I request a very simple update to the slugify utility that would add localisation support.

`const slugify = (value, separator = '-') => {
  return slug(lowerCase(value), {
    replacement: separator,
    locale: window.config.locale
  })
}`

With this minor update the Slug field will apply the localisation rules that are defined in the slugify library.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
