### ISSUE TITLE
MorphMany field fails to call getPivotAccessor()

### ISSUE THREAD

**Issue by soenisa** [laravel/nova-issues#3617]
- Laravel Version: 8.66.0
- Nova Version: 3.30.0
- PHP Version: 7.4.24
- Database Driver & Version:
- Operating System and Version: macOS Big Sur 11.2.3
- Browser type and version: N/A
- Reproduction Repository: [https://github.com/soenisa/nova-morph-many-issue](https://github.com/soenisa/nova-morph-many-issue)

### Description:
After update to v3.30 the MorphMany field on a resource fails to call "getPivotAccessor()"

I've created a repo to replicate this. In the repo the User model has a MorphMany field to the Log model. The migration will create test data.

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Clone the repo
2. `composer install`
3. Create .env file with database config
4. `php artisan migrate`
5. `php artisan serve`
6. Navigate to Nova login (for me `http://127.0.0.1:8000/nova`)
7. Log in with user `admin@example.com` and password `password`
8. Go to Users resource
9. Go to first user
10. Perceive the error
```
"Call to undefined method Illuminate\\Database\\Eloquent\\Relations\\MorphMany::getPivotAccessor()"
```

**Comment by crynobone** [comment]
MorphMany doesn't use pivot so this declaration is wrong.

```php
MorphToMany::make('Logs', 'logs')
                ->referToPivotAs('Activity')
```

**Comment by crynobone** [comment]
You declare `MorphToMany` field but uses `MorphMany` relationship.

```php
    public function logs()
    {
        return $this->morphMany(Log::class, 'loggable');
    }
```
