### ISSUE TITLE
Specific connection for action_events table

### ISSUE THREAD

**Issue by poxin13** [laravel/nova-issues#362]
Have multiple databases in an app. When using `Actionable` on a model it will use `$connection` specified on the model itself. Can't find a way to configure what connection would be used specifically for the `action_events` table on Eloquent models, if that can even be an option.

**Comment by davidhemphill** [comment]
https://nova.laravel.com/docs/1.0/actions/defining-actions.html#queued-actions

**Comment by ibrunotome** [comment]
@davidhemphill is not about queued actions, is about database connection to store action_events in another connection instead of the default

**Comment by davidhemphill** [comment]
Sorry I misposted the link. It's this one: (the heading is the next on down 😉) https://nova.laravel.com/docs/1.0/actions/defining-actions.html#customizing-the-connection-and-queue

**Comment by ibrunotome** [comment]
I think that still not the point yet, is about to save the action events in a DB::connection('customconnection') instead of the default database, not about queues. To do this I think that would have to modify the ActionEvent model.

**Comment by maede-a** [comment]
@poxin13 did you find any solution for this?

**Comment by poxin13** [comment]
I didn't, ended up using Spatie's Activitylog instead. https://github.com/spatie/laravel-activitylog/issues/423

**Comment by shineirvin** [comment]
@davidhemphill As just this guy said, I just want to change the db connection for the action_events like adding protected $connection inside model. please help us.

**Comment by davidemorotti** [comment]
A solution would be to change the path of the ActionResource file in the nova configuration to a custom one (which will have exactly the same content as the default ActionResource class).

On the newly created resource, you can change the model to point to a custom one which extends the default ActionEvent model, like this:
```
<?php

namespace App;

use Laravel\Nova\Actions\ActionEvent;

class CustomActionEvent extends ActionEvent {
    protected $connection = 'your-connection';

    public static function boot()
    {
        parent::boot();
    }
}
```
There, you can then specify a connection to use.

Hope this helps somebody!
