### ISSUE TITLE
Explicitly specify the underlying resource for a lens.

### ISSUE THREAD

**Issue by attac-t** [laravel/nova-issues#3622]
- Laravel Version: 8.62.0
- Nova Version: 3.29.0
- PHP Version: 8.0.9

### Description:
When a lens is executed, the underlying resource is always the nova resource that the lens is registered to. This poses a problem when the lens must always read from the same resource. The Lens class's constructor takes a resource parameter but it seems that this doesn't change the underlying resource.

`    /**
     * Create a new lens instance.
     *
     * @param  \Illuminate\Database\Eloquent\Model|null  $resource
     * @return void
     */
    public function __construct($resource = null)
    {
        $this->resource = $resource ?: new stdClass;
    }`

### Detailed steps to reproduce the issue on a fresh Nova installation:

From your lens class which extends the abstract Lens class provided by nova, specify the resource in the constructor.

`public function __construct($resource = \Book::class)
    {
        parent::__construct($resource);
    }
`

When you dd as per below, the model won't be the one that belongs to the specified resource.

`
public static function query(LensRequest $request, $query)
    {
        dd($query->getModel()->getTable());
`

**Comment by crynobone** [comment]
Above usage is not supported by Nova.
