### ISSUE TITLE
Hide Dashboard Resources

### ISSUE THREAD

**Issue by timkerr222** [laravel/nova-issues#3627]
It would be nice if `displayInNavigation` or `availableForNavigation` properties could be used in Nova Dashboards.

Thanks!

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
