### ISSUE TITLE
Specify per resource policy

### ISSUE THREAD

**Issue by lucasromanojf** [laravel/nova-issues#363]
Sometimes I need different resource config for the same model. I am creating different resources for what I need, but then I have to extend my main model for each resource so I can specify different policies for each resource. My suggestion is implement a way to allow specifying per resource policies, so I dont need to keep extending models to have different policies.

**Comment by davidhemphill** [comment]
I don't understand your use-case. If you can explain it more thoroughly we can take a look at this again.

**Comment by cargie** [comment]
I think it's useful and I also need it.
For example: Team and User models.
I will create a Team, User and Member resource. Basically, I will use only the Member resource on HasMany for Team so that I have custom fields for the User model and I will disable edit, view. just the delete permission

**Comment by ckonkel** [comment]
> I don't understand your use-case. If you can explain it more thoroughly we can take a look at this again.

Here is a use case...

I have several Products Categories that can only be managed by specific users..

(left menu)
Resource
 - All Products
 - Product Apparel
 - Product Jewelry

Users  that edit type apparel products can only see those products and have a specific field layout that caters to that product. Kinda like a product creation wizard...

Same for Jewelry...

All Products is a view for admins that does not need all the bells and whistles that the other two product types have - so its very data centric.

I know that Lens exist for this potential functionality, but I need the left hand menu link and all the functionality a resource page provides...

I currently have several Resources that all share the same model, but offer a different experience. And it works great ...just cant add unique policies to each of them to view/edit/delete.....

Any suggestions would be welcomed as well... but would like to see something like this implemented.

**Comment by jazmy** [comment]
Hi Ckonkel,

  I was trying to do the same thing so I created a new resource and customized it but ran into issues with the policies.  I think the correct Laravel Nova way to control what is displayed on a resource is by using the canSee function on your fields in your resource.

```
 public function fields(Request $request)
    {
        return [
  Text::make('AdminOnlyNotes')->canSee(function ($request) { return isAdmin(); }),
      ];
    }
```

Instead of creating a new custom resource for different views.

**Comment by Gasol** [comment]
I have the same issue and end up with the same idea as the OP. After digging the Resource class to see how it determine what resource can be seen by users.  I can't believe how easy it is. So I wanna share with you guys. Just override the `authorizedToViewAny` method as following. Hopefully, this will be useful to you. Lastly, by doing so. There is no need to create a model and policy for it again again, and again. 

```php
class YourResource extends Resource
{
    public static function authorizedToViewAny(Request $request)
    {
        return true; // depends on what you need. 
    }
}
```
