### ISSUE TITLE
field with readonly and default field not saving

### ISSUE THREAD

**Issue by whchi** [laravel/nova-issues#3630]
- Laravel Version: 8.70.2
- Nova Version: 3.30.0

### Description:
Fields with default() won't save into database if use readonly(), but still displays on page.

#### 1. define a field with default use readonly
```php
            Number::make('example_field')
                ->default(666.666)
                ->readonly()
                ->rules(['required'])
```
#### 3. check data in database
field value won't save

**Comment by crynobone** [comment]
That the current expected behaviour.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
