### ISSUE TITLE
KeyValueItem dose not get index parameter in KeyValueField.vue

### ISSUE THREAD

**Issue by mydansun** [laravel/nova-issues#3631]
- Laravel Version: any
- Nova Version: 3.30.0
- PHP Version: any
- Database Driver & Version:
- Operating System and Version: any
- Browser type and version: any
- Reproduction Repository: 

### Description:

In `resources/js/components/Detail/KeyValueField.vue` line 15, `KeyValueItem` is not passed the `index` parameter, which results in the `dusk` label has `undefined` in the view mode.

![image](https://user-images.githubusercontent.com/8871143/141425503-d82d5ddd-a550-4e3b-a2f6-f0d1359ec88c.png)

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Create a Nova Resource that has a KeyValue Field.
2. Input some values in that field in the create page.
3. Go to the view page and inspect the dusk label of the KeyValue component.

**Comment by crynobone** [comment]
Please provide full reproducing code to get the following issue as the dusk selector is being used by our dusk tests suite without failure.

**Comment by mydansun** [comment]
@crynobone 

Hello 

This bug only affects the view page, and does not affect test cases that using the `type` method with dusk selectors.

**Comment by crynobone** [comment]
Fixed in v3.31.0: https://nova.laravel.com/releases/3.31.0
