### ISSUE TITLE
Action with `->onlyOnTableRow()` will not show in `Lens` page.

### ISSUE THREAD

**Issue by rezuankassim** [laravel/nova-issues#3632]
- Laravel Version: v8.70.2
- Nova Version: v3.30.0
- PHP Version: 8.0.12
- Database Driver & Version: mysql - 8.0.27
- Operating System and Version: macOS Monterey - 12.0.1
- Browser type and version: Firefox - 94.0.1

### Description:
Action that is `->onlyOnTableRow()` in `lens` index page will not show, but it will show in `resources` index page. 

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Create a resource, a lens for the resource and an action for the resource
- Attach the action to the lens and add `->onlyOnTableRow()` to the action
- Action will not display in the table row

### Images:
<img width="1181" alt="Screenshot 2021-11-14 at 12 21 11 AM" src="https://user-images.githubusercontent.com/53212160/141651153-305b59bc-185f-4a82-9869-0302c4800693.png">

<img width="1181" alt="Screenshot 2021-11-14 at 12 21 48 AM" src="https://user-images.githubusercontent.com/53212160/141651166-785ef8b5-df6f-4300-a74b-21497fe588a6.png">

**Comment by rezuankassim** [comment]
Can I know when I can pull the latest code for Laravel Nova where this issue is fix?

**Comment by crynobone** [comment]
Fixed in v3.31.0: https://nova.laravel.com/releases/3.31.0
