### ISSUE TITLE
Unable to hide fields in `Lens` page

### ISSUE THREAD

**Issue by rezuankassim** [laravel/nova-issues#3633]
- Laravel Version: v8.70.2
- Nova Version: v3.30.0
- PHP Version: 8.0.12
- Database Driver & Version: mysql - 8.0.27
- Operating System and Version: macOS Monterey - 12.0.1
- Browser type and version: Firefox - 94.0.1

### Description:
Unable to hide any field using either `hide()` for `Laravel\Nova\Fields\ID` field or `hideFromIndex()` for `Laravel\Nova\Fields\Text` field in `lens` page.

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Create lens page for resource
- Hide `Laravel\Nova\Fields\ID` field using `hide()` or `Laravel\Nova\Fields\Text` field using `hideFromIndex()`
- Field will still be showing in the `lens` page

### Images:
<img width="1181" alt="Screenshot 2021-11-14 at 12 28 29 AM" src="https://user-images.githubusercontent.com/53212160/141651367-ccedc986-232d-405a-b612-318f5bb93133.png">

<img width="1181" alt="Screenshot 2021-11-14 at 12 29 16 AM" src="https://user-images.githubusercontent.com/53212160/141651381-c3919371-8ad5-43ff-a0f9-5fb303baa05e.png">

**Comment by crynobone** [comment]
There no form or detail page for Lens, it wouldn't be useful to have `hideFromIndex()` or `readonly()` for Lens context.

**Comment by rezuankassim** [comment]
@crynobone so is just better for me just don't register the field if I don't want to display in in the listing table?

**Comment by crynobone** [comment]
yes
