### ISSUE TITLE
Large app.js and vendor.js sizes, could be fixed by using Async Vue components

### ISSUE THREAD

**Issue by bawarkamalqader** [laravel/nova-issues#3635]
- Laravel Version: 8.54
- Nova Version: 3.29.0
- PHP Version: 8.0.12

### Description:
The first time nova is loaded is very slow, i found that the app.js file is very large in size even after `npm run prod`

I believe we can use Async vue components to load the components when they are needed.

Example : `nova/resources/js/components.js`
In the above file, a lot of components are loaded synchronously. We can load them asyncly, like this;

Instead of `Vue.component('action-selector', ActionSelector)`
We can use **`Vue.component('action-selector', () => import('@/components/ActionSelector'));`**

This way, the file will be loaded using ajax when needed, instead of loading them all at once.
 I think a minimum version of 2.4.0+ is needed for vue-router to work with this, i am not sure.

<img width="1407" alt="Screen Shot 2021-11-15 at 9 38 57 PM" src="https://user-images.githubusercontent.com/35786269/141837533-2fcce875-fa91-4dd3-a6b8-c1bfc1059070.png">

I found out this issue was also reported earlier, but was not solved. I hope we can get a fix for these.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by bawarkamalqader** [comment]
Actually i dont see this as a feature request, i see this as a real issue with the nova dashboard, after installing some tools, this even gets bigger, and in my case the amount of javascript loaded first was close to 20 Megabytes.

Unfortunately i dont understand why you insist that this is not an issue
