### ISSUE TITLE
nova.laravel.com down?

### ISSUE THREAD

**Issue by duckzland** [laravel/nova-issues#3636]
- Laravel Version: #.#.#
- Nova Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Detailed steps to reproduce the issue on a fresh Nova installation:

This might not been the proper place to report this, but havent found any other place to do so.

Anyways... https://nova.laravel.com/ down? cannot do composer install and seems the site isnt accessible

**Comment by crynobone** [comment]
This has been fixed, can you try again.

**Comment by duckzland** [comment]
thanks its fixed now..
