### ISSUE TITLE
BelongsTo field not populated after laravel/framework update

### ISSUE THREAD

**Issue by pcorrick** [laravel/nova-issues#3637]
- Laravel Version: 8.71.0
- Nova Version: 3.30.0
- PHP Version: 7.4
- Database Driver & Version: mysql  Ver 15.1 Distrib 10.3.31-MariaDB
- Operating System and Version: debian-linux-gnu (x86_64)
- Browser type and version: Firefox 94.0.1

### Description:
I have a simple BelongsTo field which populates correctly when creating a new resource, however after updating laravel/framework to 8.71.0 the dropdown no longer populates.

![image](https://user-images.githubusercontent.com/32149746/142144958-b669634f-47aa-419d-a7aa-05f49098991b.png)

### Detailed steps to reproduce the issue on a fresh Nova installation:
Create a resource with a belongsTo field
Update laravel/framework (v8.70.2 => v8.71.0)
Create a resource in Nova and notice the dropdown for a BelongsTo field is not poulated.

**Comment by crynobone** [comment]
Thank you for the report, a PR has been made to `laravel/framework` to solve this bug.

**Comment by nicolalazzaro** [comment]
@crynobone can you share the PR id? Thanks.

**Comment by timkerr222** [comment]
Is this related to this same issue? 

https://github.com/laravel/nova-issues/issues/112

Line 161 of vendor/laravel/nova/src/Fields/BelongsTo.php

`  value = $resource->{$this->attribute}`;
This does not work:

`$value = $resource->{$this->attribute}()->withoutGlobalScopes()->getResults();`

**Comment by timkerr222** [comment]
@nicolalazzaro did you run composer update?

**Comment by nicolalazzaro** [comment]
> @nicolalazzaro did you run composer update?

No, the file is outside the `vendor` folder.
`nova/src/Fields/BelongsTo.php`

**Comment by crynobone** [comment]
Please update to Laravel Framework 8.72.0
