### ISSUE TITLE
BelongsToMany field not filling withPivotValue defined on relation

### ISSUE THREAD

**Issue by FaridAghili** [laravel/nova-issues#3639]
- Laravel Version: v8.70.2
- Nova Version: v3.30.0
- PHP Version: v8.0.12
- Database Driver & Version: MySQL v8.0.27
- Operating System and Version: Windows 10 Pro
- Browser type and version: Google Chrome 95

### Description:
I have a `Music` model which has a `BelongsToMany` relation to `Artist` model defined like this:
```php
public function singers(): BelongsToMany
{
    return $this->belongsToMany(Artist::class)
        ->withPivotValue('role', 'Singer');
}
```

The intermediate table is defined like this:
```php
Schema::create('artist_music', function (Blueprint $table) {
    $table->foreignIdFor(Artist::class)->constrained()->cascadeOnDelete();
    $table->foreignIdFor(Music::class)->constrained()->cascadeOnDelete();
    $table->string('role');
});
```

When I use `Tinker` to test, the following code works as expected:
```php
Music::find(1)->singers()->attach(Artist::find(1))
```

New record added to table:

![image](https://user-images.githubusercontent.com/8607021/142188835-30d27163-5ae7-4063-a1a0-4be91ac5989b.png)

But in Nova, the following field won't work:
```php
BelongsToMany::make('Singer', 'singers', Artist::class)
    ->searchable()
```

It gives this error:
```
SQLSTATE[HY000]: General error: 1364 Field 'role' doesn't have a default value (SQL: insert into `artist_music` (`music_id`, `artist_id`) values (1, 1))
```

As you can see in the SQL query above, it doesn't fill `role` column which its value is defined in `singers` relation.

Is it a bug or am I doing something wrong?

**Comment by crynobone** [comment]
prefilling default using `pivotValues()` has no affect on Laravel Nova. I would suggest using custom Pivot Model or hidden fields for now.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
