### ISSUE TITLE
Default value for filter

### ISSUE THREAD

**Issue by lucasromanojf** [laravel/nova-issues#364]
Is there a way to define a default value for filter?

**Comment by dbmeister** [comment]
I'd like to know if this is possible too

**Comment by rivenme** [comment]
I like to have this feature too.

**Comment by davidhemphill** [comment]
You can now do this by specifying the `default` method on the filter.

**Comment by larsjanssen6** [comment]
@davidhemphill hmm not working for me guess I'm doing something wrong?

```
class ActiveStatus extends Filter
{
    /**
     * @var string
     */
    public $name = 'Actief status';

    public function apply(Request $request, $query, $value): Builder
    {
        return $query->where('active', $value);
    }

    public function options(Request $request): array
    {
        return [
            'Actief' => 1,
            'Gearchiveerd' => 0
        ];
    }

    public function default()
    {
        return 'Actief';
    }
}
```

I would expect `Actief` to be selected by default but it's not. 

I' updated Nova to version `v1.2.0`.

**Comment by larsjanssen6** [comment]
Don't forget to run `php artisan nova:publish` after updating like I did 👍

**Comment by thegregthomp** [comment]
@davidhemphill any example of how to use it?

**Comment by MarouaneSH** [comment]
` Default()  method` didn't work for me either ` Boolean filters` on`Lens`

**Comment by vitorhugodotpt** [comment]
@MarouaneSH  Boolean filters expects return an array, like this

`public function default()
    {
        return [
            'admin' => true,
            'editor' => false
        ];
    }`

**Comment by mikebronner** [comment]
I'm seeing issues with boolean filters not properly updating the array indicator. For example, if I have default filters selected for boolean filters, the filter indicator does not reflect any applied filters. Also, if I select multiple boolean filters manually, the filter indicator will increase the count, but then not decrease it when I deselect them. Is anyone else seeing this as well?

**Comment by phuclh** [comment]
I have the same issue when using boolean filter. The default value was set but the array didn't change.

**Comment by mikebronner** [comment]
@phuclh I think this issue is of relevance for you, and confused me for the longest time as well: https://github.com/laravel/nova-issues/issues/1138

**Comment by phuclh** [comment]
@mikebronner  so it means we cannot change the array of resources, that default method just returns a static value and don't do anything else. Is that correct?

**Comment by mikebronner** [comment]
The issue I had was that it is not showing that a filter is applied if you specify a default value (that seems to be a feature, not a bug, which I referenced in the link). However, you should be able to set the default value dynamically in the `default()` method. I'm not sure I understand your question completely. You say you have the same issue as posted above, but it seems you might be experiencing something else.

Can you be more clear on which array doesn't change? If you click the filters button, you should see your filter already selected. That means it is working.

**Comment by phuclh** [comment]
@mikebronner  yes, the filter already selected when I click the filters button. I have a keyword resource and I just load unused keywords on the initial load. When I set `unused` value in default method the resource still lists all keywords (unused + used). Here is my code:

```
/**
     * Apply the filter to the given query.
     *
     * @param \Illuminate\Http\Request $request
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param mixed $value
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function apply(Request $request, $query, $value)
    {
        if ($value == 'used') return $query->used();
        else if ($value == 'unused') return $query->unused();
        else return $query->whereIn('is_used', [true, false]);
    }

    /**
     * Set the default options for the filter.
     *
     * @return array
     */
    public function default()
    {
        return [
            'unused'
        ];
    }

    /**
     * Get the filter's available options.
     *
     * @param \Illuminate\Http\Request $request
     * @return array
     */
    public function options(Request $request)
    {
        return [
            'Used'   => 'used',
            'Unused' => 'unused',
            'Both'   => 'both'
        ];
    }
```

**Comment by mikebronner** [comment]
@phuclh Reference my working example above. Notice that you need to set it to true. Try that.

**Comment by phuclh** [comment]
@mikebronner that was my fault. The default should return a string, not an array in my case. Thank you for your help :D.

**Comment by gbrits** [comment]
Thanks @davidhemphill for implementing the **default** method - for anyone else's reference, this was how I got a user ID oriented lens to work by being all-ticks:

```
class UserWorkflow extends BooleanFilter
{
    /**
     * Apply the filter to the given query.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @param  mixed  $value
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function apply(Request $request, $query, $value)
    {
      // Get all true user IDs:
      $true_ids = array_keys(array_filter($value));
      return $query->whereHas('users', function($q) use($true_ids) {
          $q->whereIn('user_id', $true_ids);
      })->get();
    }

    public function options(Request $request)
    {
      $users = \App\User::all();
      $options = [];
      foreach($users as $user) {
        $options[$user->name] = $user->id;
      }
      return $options;
    }

    public function default() {
      $users = \App\User::all();
      $options = [];
      foreach($users as $user) {
        $options[$user->id] = true;
      }
      return $options;
    }
}
```

This determines which user is relevant to the given Nova index and all users are pre-selected by default, to be unticked optionally. Obviously this wouldn't always work great with a huge user base, just wanted to share the edge-case implementation.

**Comment by eugenevdm** [comment]
Could someone please confirm that the default filter only works on Boolean filters?

The documentation is unclear:

https://nova.laravel.com/docs/4.0/filters/defining-filters.html#filter-default-values

> If you would like to set the default value of a filter, you may define a default method on the filter class:

Should that read:

> If you would like to set the default value of a **boolean** filter, you may define a default method on the filter class:

**Comment by crynobone** [comment]
The current documentation is correct. Please stop commenting on old issue hoping to get help. The issue was created on a much earlier version of Nova where any discussion here no longer relevant to current version.
