### ISSUE TITLE
allow to specify an id (or anchor) on HasMany, etc

### ISSUE THREAD

**Issue by vesper8** [laravel/nova-issues#3645]
I have many resources that are very long with lots of relationships and it would be nice to be able to scroll directly to a given relationship by adding a hashtag in the url

For example

```
HasMany::make('Posts')->id('posts'),

or

HasMany::make('Posts')
            ->withMeta([
                'id' => 'child-messages',
            ]),

or
            
HasMany::make('Posts')
            ->withMeta([
                'extraAttributes' => [
                    'id' => 'child-messages',
                ],
            ]),       
```

`https://mydomain.com/nova/resources/users/277#posts`

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
