### ISSUE TITLE
Please add full page loading indicator when triggering actions with withoutConfirmation

### ISSUE THREAD

**Issue by vesper8** [laravel/nova-issues#3648]
Currently if you trigger an action you get a modal asking you to confirm, and upon clicking, a loading indicator until the action is finishing performing.

However if you add the `->withoutConfirmation()` then you don't get the modal, but you also don't get any loading indicator to prevent you from navigating away while the (lengthy) action is taking place.

I would appreciate if you added  a full screen-overlay with loading indicator in this instance as well.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
