### ISSUE TITLE
resource detail metrics do not reload after action finishes

### ISSUE THREAD

**Issue by vesper8** [laravel/nova-issues#3649]
I have 3 trend metrics on my resource detail card, and I've noticed that if I run an action that affects the data being displayed in the metrics card, once the action finishes the resource data itself is updated but the metrics are not updated and require a manual page reload before they will show the new data.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
This already available:

[resources/js/views/Detail.vue#L73](https://github.com/laravel/nova/blob/3.0/resources/js/views/Detail.vue#L73)
[resources/js/views/Detail.vue#L322-L325](https://github.com/laravel/nova/blob/3.0/resources/js/views/Detail.vue#L322-L325)
