### ISSUE TITLE
Using orWhereHasMorph in indexquery shows unrelated results to the current model in morphMany field

### ISSUE THREAD

**Issue by AEmad01** [laravel/nova-issues#3655]
- Laravel Version: 8.32
- Nova Version: 3.22
- PHP Version: 7.4
- Database Driver & Version: MYSQL
- Operating System and Version: MacOS 
- Browser type and version: Chrome

### Description:
When using orWhereHasMorph in an indexquery and trying to view a resource beings up all index query results even if they are not related to the current model.

`return $query->whereHasMorph('requirementable', [\App\Bug::class, \App\Request::class], function ($query) use ($request) {
            $query->whereHas('project', function (Builder $query) use ($request) {
                $query->where('team_id', $request->user()->team->id);
            });
        })->orWhereHasMorph('requirementable', [\App\Project::class], function ($query) use ($request) {
            $query->where('team_id', $request->user()->team->id);
        });`

I have this, which allows a user to view requirements related to their projects, bugs and requests, which works perfectly in the index view.

However when using the MorphMany field and viewing a specific project, all requirements are shown even if not related to the project.

**Comment by crynobone** [comment]
Please provide full reproducing code in order for us to understand the current and expected behavior.
