### ISSUE TITLE
Using an invalid theme name creates a mess

### ISSUE THREAD

**Issue by Synchro** [laravel/nova-issues#3656]
- Laravel Version: 8.73.2
- Nova Version: 3.30.0
- PHP Version: 8.0.13
- Database Driver & Version:
- Operating System and Version: macOS 12.0.1
- Browser type and version: n/a
- Reproduction Repository: https://github.com/###/###

### Description:

The docs on themes describe creating a theme like this:

    php artisan nova:theme example/miami-ice

That works fine, but there are constraints on the name that are not mentioned in the docs. This will fail:

    php artisan nova:theme example/Miami-ice

because composer doesn't like packages with upper-case chars in their names. Unfortunately, this invalid name is not spotted until quite late on in the process, by which time it's already made changes to composer.json and other things. It would be much better to validate this name earlier, before any changes have been made.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Attempt to create a Nova theme with a name that contains upper-case characters, such as:

    php artisan nova:theme example/Miami-ice

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by Synchro** [comment]
As far as I can see, this is a straightforward bug. It's not a feature request, nor a request for help, nor something that needs any particular discussion. It's basically the same as any other bug that relates to inappropriate validation.
