### ISSUE TITLE
Global search return "NO RESULTS FOUND" - but still display results after cca. 2 sec.

### ISSUE THREAD

**Issue by eAvio** [laravel/nova-issues#3657]
When using "Global search", we experience strange behaviour.
We first get message "NO RESULTS FOUND" - BUT if you wait another sec or 2 the correct results still appear.

We are using latest version of Laravel Nova: v3.30.0

See screenshoots:
[https://www.dropbox.com/s/kcv3z9fiuaigivj/search%20problem1.jpg?dl=0](https://www.dropbox.com/s/kcv3z9fiuaigivj/search%20problem1.jpg?dl=0)

[https://www.dropbox.com/s/d29zw66g643ekjg/Search%20problem.jpg?dl=0](https://www.dropbox.com/s/d29zw66g643ekjg/Search%20problem.jpg?dl=0)

**Comment by crynobone** [comment]
Unable to reproduce, can you provide full reproducing code.
