### ISSUE TITLE
Too many errors in PHP 8.0 by not declaring the type of the variables

### ISSUE THREAD

**Issue by abkrim** [laravel/nova-issues#3658]
- Laravel Version: 8.73.2
- Nova Version: 3.30.0
- PHP Version: 8.0
- Operating System and Version: Ubutnu 20.04

### Description:
After update composer this morning app fails by not declaring the type of the variables

### Detailed steps to reproduce the issue on a fresh Nova installation:

production.ERROR: Type of Laravel\Nova\Actions\ActionEvent::$casts must be array (as in class Illuminate\Database\Eloquent\Model) {"userId":1,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Type of Laravel\\Nova\\Actions\\ActionEvent::$casts must be array (as in class Illuminate\\Database\\Eloquent\\Model) at /home/abkrim/Sites/almanzil/vendor/laravel/nova/src/Actions/ActionEvent.php:0)

On code
```
protected $casts = [
        'original' => 'array',
        'changes' => 'array',
    ];
```

Must be 
```
protected array $casts = [
        'original' => 'array',
        'changes' => 'array',
    ];
```

Also all elements of Laravel Nova package.

I am upset, because I am using php 8.0 not php 8.1 and I don't think it is mandatory although it is, I recommend the type declaration in php.

Any idea?
![Castris_20211126_110709](https://user-images.githubusercontent.com/1238625/143563798-42139aca-6d4e-402e-a5fc-e9fd41170099.jpg)

**Comment by crynobone** [comment]
Laravel Nova still support PHP 7.2 and above and we don't use typed variables.
