### ISSUE TITLE
Add in resource index the ability to use another field as the clickable link to the detail

### ISSUE THREAD

**Issue by dan-lutd** [laravel/nova-issues#3659]
Currently the ID field is clickable and links to the detail page.
In a case where the display of the ID in unwanted, that leaves the only clickable item on the far right.
On a small index row the button the right works.
But on a row with many fields it requires scrolling the screen.
Is there a way to set another field as a clickable link to open the detail like the ID ?
Would it be useful to follow in the steps of [nova-id-link](https://github.com/dillingham/nova-id-link)

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
