### ISSUE TITLE
Possibility to customize create and create and add another labels only for creation page

### ISSUE THREAD

**Issue by studioilgranello** [laravel/nova-issues#3661]
Hello, this is related to issue #2134

Basically if the "Create ..." button label is changed, it will reflect in other pages where it should instead be at default value.
For example, if i want the button to show "Save & Exit" when i'm creating a resource, i can modify it like so:
```php
    /**
    * Get the text for the create resource button.
    *
    * @return string|null
    */
    public static function createButtonLabel()
    {
        return "Save & Exit";
    }
```
but doing so results in the same label also in the relationship parent resource, like so:

![image](https://user-images.githubusercontent.com/93132893/144226933-570dc303-8543-4903-b22c-9b1d01540340.png)

which, for the above page, makes no sense.

The same can be applied to the "Create & add another" button, which in addition has no possibility to customize the label at all.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
