### ISSUE TITLE
Select field tries to execute an undefined method

### ISSUE THREAD

**Issue by dees040** [laravel/nova-issues#3662]
- Laravel Version: 8.73.2
- Nova Version: 3.30.0
- PHP Version: 8.0.2
- Database Driver & Version: MySQL 8.0
- Operating System and Version: MacOS
- Browser type and version: Chrome

### Description:
The following code will throw a method not exists exception (`Method Illuminate\Http\Request::Invitation does not exist.`).
```php
Select::make('Type')
    ->options(['Request', 'Invitation']),
```

If you check the docs of the [`is_callable()` method](https://www.php.net/manual/en/function.is-callable.php), you can see that this method can accept an array linking to the callable class/object and method. So my example above will try and call the `Invitation` method on the `Request` facade.

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Add a field with the example I provided in the description.

### Possible solution:

In the `options()` method in the `Select` field change the if statement to:
```php
if (is_callable($options) && ! is_array($options)) {
    $options = $options();
}
```

**Comment by crynobone** [comment]
Potential breaking change if someone uses it to store options on callable classes. e.g:

```php
Select::make('Type')->options(['App\Models\Type', 'groupedOptions']); // etc
```

Use the following if you want to avoid such problem:

```php
Select::make('Type')
    ->options(fn () => ['Request', 'Invitation']),
```
