### ISSUE TITLE
Add {attribute}-change event for DateField

### ISSUE THREAD

**Issue by m-lotze** [laravel/nova-issues#3663]
Most of the Nova fields emit a `{attribute}-change` event. The DateField (and maybe others) does not, because the `handleChange` method form the `FormField` mixin is overwritten. Please consider adding the event, so it is possible to listen for changes and e.g. update a second DateField.

Also when a DateField is invalid the error classes are applied only to the hidden input. `border-danger` should also be set on the input of the datepicker.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
