### ISSUE TITLE
Mismatch between code and docs. on Nova Resource `fields` method.

### ISSUE THREAD

**Issue by BnitoBzh** [laravel/nova-issues#3664]
- Laravel Version: 8.74.0
- Nova Version: 3.30.0
- PHP Version: 8.0.13
- Database Driver & Version: sqlite3
- Operating System and Version: macos  12.0.1
- Browser type and version: Firefox 94.0.1

In the actual documentation (v3) `Resource@fields` receives `Laravel\Nova\Http\Requests\NovaRequest`, but in the package `Resource@fields` receives `Illuminate\Http\Request`.
In addition, `fieldsForIndex`, `fieldsForDetail`, `fieldsForCreate`, `fieldsForUpdate` methods receive `Laravel\Nova\Http\Requests\NovaRequest` in docs and code.

There is an error in doc or code .. But for consistency with all methods, the code should be updated

**Comment by crynobone** [comment]
> There is an error in doc or code .. But for consistency with all methods, the code should be updated

The code can only be updated for Laravel Nova 4 to avoid breaking changes. For now, we'll update the documentation.
