### ISSUE TITLE
Feedback when a form with validation errors is resubmitted 

### ISSUE THREAD

**Issue by alhoqbani** [laravel/nova-issues#367]
When a user resubmit a form that has validation errors, there is nothing indicate that the form is being submitted if the error messages has not changed. The user will think the form was not submitted and keep trying.  

It would be good if there is some indication that form is being processed. For example, a spinning wheel on the button or disabling the button...

**Comment by davidhemphill** [comment]
We now clear out the validation errors when resubmitting.
