### ISSUE TITLE
Global Search Filter reset the retrieved data

### ISSUE THREAD

**Issue by JhosepIslam** [laravel/nova-issues#3670]
- Laravel Version: 5.8
- Nova Version:  2.5
- PHP Version: 7.1.3

- Operating System and Version: Ubuntu 18.04.3 LTS
- Browser type and version: Google Chrome 96.0.4664.45

### Description:
When I write for some result on the Global Search input, the result data reset when i click a item o when levea a least 3 secons

### Detailed steps to reproduce the issue on a fresh Nova installation:

Type some on the global search filter When the result is fetched click in any item or wait 3 or more second The data retrieved  reseted

This happened the 80% of the times

https://user-images.githubusercontent.com/50124161/144948639-fc882ca5-0af7-4901-8def-02c6a73d7a24.mp4

**Comment by crynobone** [comment]
Global search or Index search? And please give more detail as I don't understand the description or the audio on the video.

**Comment by crynobone** [comment]
Laravel Nova 2 no longer receive any patch release, please upgrade to Laravel Nova 3 as soon as possible.
