### ISSUE TITLE
cast datetime is returned as string when shown on BelongsToMany related resource

### ISSUE THREAD

**Issue by vesper8** [laravel/nova-issues#3672]
Using latest Nova 3.3.0

I have a resource Program that has Users attached to it.

On my users I have a datetime field `approved_at`

On my user mode I have

```
    protected $dates = [
        'approved_at',
    ];
```

On my User resource, the date fields display correctly and are treated as DateTime correctly.

On my Program resource, I have

```
BelongsToMany::make('Users'),
```

Which works via a `program_user` pivot table.

When a program has users, with valid approved_at dates, it throws the error `Datetime field must cast to datetime`

This seems like a bug.

I tried to work around it by using a computed field:

```
Text::make('Approved At', function () {
    return $this->approved_at ? $this->approved_at->format('Y-m-d H:i:s') : null;
}),
```

This threw an error `Call to a member function format on string`

So this reveals the problem.. somehow my field which is properly cast is being returned as a string when loaded via `BelongsToMany`

Finally I found a working workaround like so, but this seems like a bug:

```
Text::make('Approved At', function () {
    return $this->approved_at ? Carbon::parse($this->approved_at)->format('Y-m-d H:i:s') : null;
}),
```

**Comment by crynobone** [comment]
Unable to reproduce the issue

![image](https://user-images.githubusercontent.com/172966/145305747-7e40c77d-f086-4db0-904f-5420a39d12dc.png)

![image](https://user-images.githubusercontent.com/172966/145305763-8776dfd2-8385-4441-96a0-5e1cd8f6e40f.png)
