### ISSUE TITLE
Cannot click on right-most CRUD buttons on the first row of a table

### ISSUE THREAD

**Issue by ShadowSpade** [laravel/nova-issues#3673]
- Laravel Version: 8.52.0
- Nova Version: 3.22
- PHP Version: 7.4
- Database Driver & Version: MySQL 8.0
- Operating System and Version: Windows 10 Pro 
- Browser type and version: Firefox 95
- Reproduction Repository: https://github.com/###/###

### Description:

Cannot click on right-most CRUD buttons in the first row of a table. Doesn't happen to every table on a detail page. Its also only the 3 crud buttons, as you can see in the GIF I can click on the view button which is a custom button, I can also click on the ID of the row to actually access it. Workaround is also to tab to the buttons and press enter

![cantClick](https://user-images.githubusercontent.com/67732805/145382815-55ea258b-1329-407b-8a48-7d279fd2116f.gif)

### Detailed steps to reproduce the issue on a fresh Nova installation:

There is nothing really specific, this appears to be entirely random, happens to me, my team members and our support members, all on different browsers and some on W10 some W11. This has been happening for a while, even on previous Nova versions (2) and since atleast Laravel 6.

**Comment by crynobone** [comment]
Please provide reproducing code on fresh Laravel Nova installation so we can debug your use case. I cannot reproduce this issue.
