### ISSUE TITLE
Placeholder is not working on SelectField, DateField, ...

### ISSUE THREAD

**Issue by m-lotze** [laravel/nova-issues#3674]
- Laravel Version: 8.75.0
- Nova Version: 3.30.0

### Description:

The `->placeholder('placeholder')` method is not working on at least the SelectField and the DateField. This is because the placeholder is only set with `$this->withMeta(['extraAttributes' => ['placeholder' => $text]]);` and therefore `this.field.placeholder` in vue components is always null. Other Fields like BelongsToField or CurrencyField also use `this.field.placeholder`.

### Detailed steps to reproduce the issue on a fresh Nova installation:

A `SelectField::make('select')->options([...])->placeholder('foo')` always has `Choose an option` as first option, instead of `foo`.

A `DateField::make('date')->placeholder('foo')` sets a placeholder of `moment().format(this.format)` on the hidden input. The visible input has no placeholder.

Changing the placeholder method in Field.php like below, should solve this. Except for the hidden input issue in DateField.

```
public function placeholder($text)
{
    $this->placeholder = $text;
    $this->withMeta(['extraAttributes' => ['placeholder' => $text]]);
    $this->withMeta(['placeholder' => $text]);

    return $this;
}
```

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
