### ISSUE TITLE
Incompatible return types using php 8.1

### ISSUE THREAD

**Issue by ibrunotome** [laravel/nova-issues#3675]
- Laravel Version: v8.75.0
- Nova Version: 3.30.0
- PHP Version: 8.1.0
- Octane: v1.0.21

### Description:

After upgrade to php 8.1, this warning starts to appear in ray:

<img width="1272" alt="Screen Shot 2021-12-12 at 07 07 46" src="https://user-images.githubusercontent.com/4256471/145708238-ba86a966-8dc3-45cb-bf11-dcd584975535.png">

### Detailed steps to reproduce the issue on a fresh Nova installation:
Create a new project with php 8.1 and nova latest version. Obs: These warnings are only showed by ray app here.

**Comment by crynobone** [comment]
PHP 8.1 support has been merged but is pending the next patch release. However, this shouldn't stop you from being able to use the existing Laravel Nova 3 with PHP 8.1 as what you are seeing is just a deprecation warning which only goes `null` logger driver, and the Ray collects all registered logs and reports it back to its client.

**Comment by davi5e** [comment]
@crynobone kinda offtopic but not entirely, but could this repo be used to "release" the version as well?

If so, people would be able to leverage Github's notifications to get updates seamlessly...

**Comment by kyryl-bogach** [comment]
Would be nice to have a release soon 👍🏻

**Comment by kyryl-bogach** [comment]
Is there any chance that we have this in a hotfix or a release soon? It is the only dependecy that is blocking our migration to PHP 8.1. In our application, this is not treated as a warning but as an error.

Thank you in advance,
@crynobone

**Comment by crynobone** [comment]
> It is the only dependecy that is blocking our migration to PHP 8.1. In our application, this is not treated as a warning but as an error.

None of the code breaks in PHP 8.1, above are all PHP warnings indicating that the feature will be removed on future PHP major releases.
