### ISSUE TITLE
Nova index search loads wrong result set

### ISSUE THREAD

**Issue by fissible** [laravel/nova-issues#3679]
- Laravel Version: 6.0
- Nova Version: 2.12.0
- PHP Version: 7.4.3
- Database Driver & Version:
- Operating System and Version: macOS
- Browser type and version: Chrome 96

### Description:
https://github.com/laravel/nova-issues/issues/2892

Earlier results from a previous keystroke replaces results from a later (more up-to-date) search.

### Detailed steps to reproduce the issue:
Seed a large data set in a given resource.
Perform a search using the resource search field.

### Developer notes:
It makes sense that the cause of the problem is the latency of responses derived from the response size; initial keystrokes would generate a larger result set than later keystrokes (which will generally produce fewer and fewer results as more specific criteria is searched). Later searches return faster and "beat" the earlier requests to the client, thus the older result set overwrites the more current result set.

### Ideas:
I have encountered this issue in projects in the past and there are a few strategies that have been helpful.
1. Add a debounce to the input handler which causes the client to send fewer requests.
2. Implement promise cancelling which effectively causes responses from canceled requests to be ignored.
3. Implement a "most recent response" mechanism to ignore earlier requests.
- Either send a request ID from the client and send it back with the response
- Or send a request received timestamp back to the client

**Comment by crynobone** [comment]
#2892 is already solved by Axios cancellation.

Please provide reproducing step if you still experiencing a new issue since the above description from what I understand mimic the previous issue instead of showing that there's a new issue.

**Comment by fissible** [comment]
Thank you.
