### ISSUE TITLE
->stacked() not working on detail pages

### ISSUE THREAD

**Issue by timcv** [laravel/nova-issues#3680]
- Laravel Version: 8.76.1
- Nova Version: 3.30.0
- PHP Version: 7.4
### Description:
Text::make('Name')->stacked() works on the edit page.
When i go in to the detail page the field is not showed as stacked.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
