### ISSUE TITLE
Can't use DateTimes ,TimeField or DateRange in Laravel Nova Actions

### ISSUE THREAD

**Issue by Ahmed-Ashraf-eng** [laravel/nova-issues#3683]
- Laravel Version: 7.30.4
- Nova Version: 3.27.0
- PHP Version: 7.2.5
- Database Driver & Version:
- Operating System and Version: windows 10
- Browser type and version: google chrome

Can't use DateTimes ,TimeField or DateRange in Laravel Nova Actions

Steps To Reproduce:
Create a Nova Action,
Add it to a Resource,
Add a DateTime / TimeField / DateRange field on the Action,
Launch the Action on your Resource,
Use the calendar, to try and change the month
The "Action" popup will disappear. The calendar remains on screen. It's impossible to validate the action launch.
![nova issue](https://user-images.githubusercontent.com/71425935/146401895-41987585-a207-4c54-beed-94e0a26d8d7f.png)

**Comment by Ahmed-Ashraf-eng** [comment]
**this is my code**

public function fields()
    {
        return [
            TimeField::make(__('open from'), 'start_time')->rules('required'),
            TimeField::make(__('open to'), 'end_time')->rules('required'),
        ];
    }

**Comment by crynobone** [comment]
Related issue with `DateTime` and `Date` should have been fixed in Laravel Nova v3.30.0, please upgrade to latest release: https://nova.laravel.com/releases/3.30.0

As for `TimeField`, please consult 3rd party package which provide the field.

**Comment by sanderbaas** [comment]
I don't think this problem solved with release 3.30.0. I am running into the same issue where the action disappears when I click on certain places like time of month buttons on the date picker.

**Comment by Ahmed-Ashraf-eng** [comment]
the problem was not solved with the upgrade

**Comment by crynobone** [comment]
@sanderbaas submit a new issue with full reproducing code.
