### ISSUE TITLE
Search on pivot table additional fields

### ISSUE THREAD

**Issue by dan-lutd** [laravel/nova-issues#3689]
On the pivot table between an account and their vendor are fields for the distribution center and customer number fields that are unique to the relationship.
Using Laravel 8, nova 3.30, php 8.0

Global search does not pick up these additional fields:

```
BelongsToMany::make(__('Vendors'), 'vendors', 'App\Nova\Vendor')->fields(fn() => [
        Select::make('Distribution Center','distribution_center_id')
          ->displayUsingLabels()
          ->options($dist_centers),
        Text::make('Vendor Username'),
        Text::make('Account Number')
]
),
```

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
