### ISSUE TITLE
resource details

### ISSUE THREAD

**Issue by rtd21** [laravel/nova-issues#369]
When generate resource, with command: php artisan nova:resource. I don't have the link to the resource details. Like this.
Когда я генерирую ресурс с помощью команды: php artisan nova:resource. У меня отсутствует ссылка на детали ресурса. 
![image](https://user-images.githubusercontent.com/36414175/44898840-1c8f4200-ad11-11e8-8d59-3ab2a4ae9b4a.png)

**Comment by bonzai** [comment]
https://nova.laravel.com/docs/1.0/resources/authorization.html#policies

**Comment by rtd21** [comment]
I already have politicians. And there is permission for all actions for the
administrator.

**Comment by davidhemphill** [comment]
If you think there's a bug in Nova, and not a configuration issue on your end, can you please post a gist showing how to replicate your issue?

**Comment by rtd21** [comment]
I just watching videos on youtube. All people, who generate new resource
have link to resource detail. So, I can do the conclusion, that problem in
configuration on my device or the installation may have gone wrong.
But I have no idea about the reasons for this. Because I did everything
according to the instructions.
31 авг. 2018 г. 19:29 пользователь "David Hemphill" <
notifications@github.com> написал:
>
> If you think there's a bug in Nova, and not a configuration issue on your
end, can you please post a gist showing how to replicate your issue?
