### ISSUE TITLE
Add option to searchable select/relation fields to allow showing everything but allowing to search in frontend

### ISSUE THREAD

**Issue by lucasromanojf** [laravel/nova-issues#37]
Currently, searchable fields doesn't show anything until searched. This is not a bug, the purpose of this ticket is to ask for an option that allows searchable fields to show all options but still allowing to search in frontend.

![image](https://user-images.githubusercontent.com/3661610/44537264-ad906880-a6d4-11e8-93fe-5c0fc6892640.png)

**Comment by devmsh** [comment]
And make it return the most used items by default please :D

**Comment by davidhemphill** [comment]
There's a package that will do this: https://novapackages.com/packages/alexbowers/nova-prepopulate-searchable. There's no plan to add that by default because it could be really slow with large datasets.
