### ISSUE TITLE
Required field

### ISSUE THREAD

**Issue by LimitTech** [laravel/nova-issues#370]
Hello! 

Is there any option to set a required field?

Thanks

**Comment by macolson** [comment]
You can set a required field using the Nova / Laravel rules definitions like in the [documentations example](https://nova.laravel.com/docs/1.0/resources/fields.html#field-types)

```php
Password::make('Password')
    ->onlyOnForms()
    ->creationRules('required', 'string', 'min:6')
    ->updateRules('nullable', 'string', 'min:6'),
```

**Comment by LimitTech** [comment]
Oh! Thank you!

I did a search using "required" word and I didn't find anything so I thought it was something like the default value: https://github.com/laravel/nova-issues/issues/58
