### ISSUE TITLE
BelongsToMany fields not support belongsTo

### ISSUE THREAD

**Issue by keizah7** [laravel/nova-issues#3701]
- Laravel Version: 8
- Nova Version: 3.3
- PHP Version: 7.4

I'm trying to use belongsTo in belongsToMany fields but getting an error. Pivot model has `order` relationship, but it seems code can't resolve it

```
BelongsToMany::make('Items', 'products', \App\Nova\Warehouse\Product::class)
    ->searchable()
    ->fields(function () {
        return [
            BelongsTo::make('Užsakymas', 'order', Order::class),
        ];
    })
    ->allowDuplicateRelations(),
```

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/49227202/148185211-09005ad6-0523-4ae7-85f5-2738bdc22d76.png">

**Comment by crynobone** [comment]
We don't officially support using `BelongsToMany` on `BelongsTo` relationship.

**Comment by gepopp** [comment]
@crynobone besides the belongsTo, none of belongsToMany Pivot Model functionality is available by default, right?
