### ISSUE TITLE
Got "pngquant failed to build" error while npm install under vendor/laravel/nova

### ISSUE THREAD

**Issue by iamoat** [laravel/nova-issues#3702]
- Laravel Version: 8.77.1
- Nova Version: 3.30.0
- PHP Version: 7.4.18
- Database Driver & Version: MySQL
- Operating System and Version: Ubuntu 18.04
- Browser type and version: Chome
- Node Version: 14.18.2
- NPM Version: 6.14.15
- libpng-dev Version: 1.6.34

### Description:

Perform npm install under "vendor/laravel/nova" or during custom fields process and then got the error regarding pngquant

![image](https://user-images.githubusercontent.com/1286835/148235906-b6a1db66-62f7-4f18-8578-b7f4cc24ef82.png)

### Detailed steps to reproduce the issue on a fresh Nova installation:

cd ./vendor/laravel/nova
mv webpack.mix.js.dist webpack.mix.js
npm install

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/148321326-0adf99dc-477c-4a7d-af64-a4cc8372e4fe.png)

Unable to reproduce the issue.

**Comment by crynobone** [comment]
Looks like you need to install `libpng-dev` on your platform (see your screenshot for more information).

**Comment by iamoat** [comment]
> Looks like you need to install `libpng-dev` on your platform (see your screenshot for more information).

I did have libpng-dev on my Ubuntu as stated above. 

It's quite weird that this is not working. 

I tried many npm and node versions but still didn't work.

**Comment by iamoat** [comment]
> Looks like you need to install `libpng-dev` on your platform (see your screenshot for more information).

@crynobone 

This is able to reproduce. I tried on two different systems running Ubuntu 18.04.2 LTS. 

Both of them has libpng-dev 1.6.34 installed. 

![image](https://user-images.githubusercontent.com/1286835/148326925-9bf76612-68e0-46da-a0e2-482bf781a8dd.png)

![image](https://user-images.githubusercontent.com/1286835/148326941-f5203c7d-67d1-4b1e-accb-cce6452bef23.png)

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/148331231-f9cb92ff-e3f1-4f83-9ba3-49167844c3b4.png)

Tested with Laravel Sail and still can't reproduce the issue.

**Comment by iamoat** [comment]
> 

Were you on Ubuntu 18.04?

**Comment by crynobone** [comment]
> Were you on Ubuntu 18.04?

I have already confirmed It can be installed with proper configuration, whether or not it can be installed on every combination is out of support scope, sorry.
