### ISSUE TITLE
Nova lang folder location

### ISSUE THREAD

**Issue by gpanos** [laravel/nova-issues#3703]
- Laravel Version: 8.6
- Nova Version: 3
- PHP Version: 8.0
- Database Driver & Version: mysql 8
- Operating System and Version: macos 11.4
- Browser type and version: chrome 96

### Description:
If the application keeps the lang folder at the root of the project like the default Laravel 9 structure that is coming soon (https://github.com/laravel/laravel/tree/master/lang) and we run nova install command the a new lang folder is created inside resources (resources/lang/vendoer/nova). 
This is taking priority over the lang folder at the root of the project causing all the other translations to not work. 
Is there a way to customize the location that the nova lang directory is published ?
Thanks a lot in advance.

**Comment by crynobone** [comment]
The support for root lang will be added alongside Laravel 9 support.
