### ISSUE TITLE
HasMany Inline

### ISSUE THREAD

**Issue by nickpoulos** [laravel/nova-issues#3704]
It would be really helpful to have an inline HasMany. I know this was attempted in another third-party package that had issues getting this to work right due to certain only parent details being stored and retrieved from the URL. But I am hoping with official support it becomes do-able somehow.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
