### ISSUE TITLE
BelongsTo not repopulating after 'deleting' the current value

### ISSUE THREAD

**Issue by BeSiteBV** [laravel/nova-issues#3706]
- Laravel Version: 8.40.0
- Nova Version: 3.30.0
- PHP Version: 7.4.27
- Browser type and version: Chrome 96 & Firefox 96b10

### Description:
While attempting to select a different item from the belongsTo dropdown, it doesn't repopulate the field after pressing the 'x' to delete the currently selected item. 

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Create 2 models (event, location for example)
- Add a belongsTo relationship
- Add a couple of items (location)
- Add an event, select location A from the dropdown 
- Try to edit the event and select location B

`BelongsTo::make('location')
                ->searchable()
                ->sortable()
                ->prepopulate();`

**Comment by crynobone** [comment]
Laravel Nova doesn't have `prepopulare()` method. Can you reproduce the issue on a fresh Laravel Nova installation without that package, feel free to share the reproducing code here.

**Comment by BeSiteBV** [comment]
Hmm, my bad. 
I see that we're using GeneaLabs/nova-prepopulate-searchable to enable the user to search for specific items (since the list can be pretty long). Since this isn't an issue with Nova (perhaps a hidden feature request? :-)), I'll close this issue. 

Thank you for replying!
