### ISSUE TITLE
Select field doesn't work with canSee

### ISSUE THREAD

**Issue by kevariable** [laravel/nova-issues#3709]
- Laravel Version: 8.x.x
- Nova Version: Latest
- PHP Version: 7.4.x
- Database Driver & Version:
- Operating System and Version: linux (Arch Linux)

### Description:
```
Select::make('Merchant')
                ->canSee(fn () => false)
                ->options(
                    User::whereRelation('roles', 'name', '=', 'Merchant')
                        ->get()
                        ->flatMap(fn ($merchant) => [$merchant->email => $merchant->name])
                ),
```

### Detailed steps to reproduce the issue on a fresh Nova installation:

The select field doesnt work with canSee, but work with another field like `Text`

![image](https://user-images.githubusercontent.com/56016477/148759025-6fa71c2b-433c-4a23-8ad9-8812efd129cc.png)

**Comment by crynobone** [comment]
Action doesn't implements `canSee`.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by kevariable** [comment]
Alright, thanks for fast response. I'll do conditional manually first @davidhemphill @crynobone
