### ISSUE TITLE
Field notes / instructions below input label

### ISSUE THREAD

**Issue by admench** [laravel/nova-issues#371]
Thanks for such a fantastic tool. I Love it!

It would be fantastic to add an optional *note / instructions* to the field label to give the editor further information on what should be input into the field.

Here you can see an example taken from Craft CMS:

![screen shot 2018-08-31 at 09 34 11](https://user-images.githubusercontent.com/672916/44902129-1002ed80-ad01-11e8-9a98-97b2474591d4.png)

**Comment by admench** [comment]
![field-note-example](https://user-images.githubusercontent.com/672916/44902290-7a1b9280-ad01-11e8-9753-9547ba334a2c.png)

**Comment by macolson** [comment]
@admench 

Try appending ->help('Your custom help text')

`Text::make('Advisor id', 'advisor_id')->help('This must correspond to MK')`

**Comment by admench** [comment]
Thanks @macolson I didn't realise it was possible. Not in the docs.

**Comment by davidhemphill** [comment]
@admench That'd be a nice little PR. 😄
