### ISSUE TITLE
CouldQueue for Actions

### ISSUE THREAD

**Issue by Grafikart** [laravel/nova-issues#3710]
With the current version of Nova `v3.30.0` it's possible to enqueue action implementing the `ShouldQueue` interface. But in some case it could be nice to be able to enqueue only if the action is heavy (for instance exporting one row is not queued, but exporting more than 10 rows will be enqueued).

## Proposition

A new interface `CouldQueue` could be used in the DispatchAction to choose if the action should be enqueued or not depending on the request or the models.

```php
        if (
            $action instanceof ShouldQueue ||
            ($action instanceof CouldQueue && $action->shouldQueue($request, $models)
        ) {
            return static::queueForModels($request, $action, $method, $models);
        }
```

This would be an easy to implement feature imo

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
