### ISSUE TITLE
Use of Transactions Breaks Storing/Updating In MongoDB

### ISSUE THREAD

**Issue by alexc-wormhole** [laravel/nova-issues#3712]
- Laravel Version: 8
- Nova Version: 3
- PHP Version: 8
- Database Driver & Version: MongoDB
- Operating System and Version: Ubuntu 20

### Description:

No, Nova doesn't officially support MongoDB; nor does Laravel. Yes, the MongoDB driver needs to implement transactions for v4.

However, in these files:

- Actions/Transaction.php
- Actions/DispatchAction.php
- Http/Controllers/ResourceUpdateController.php
- Http/Controllers/ResourceStoreController.php
- Http/Controllers/AttachedResourceUpdateController.php
- Http/Controllers/ResourceAttachController.php

Code like this prevents basic save() when using any NoSQL DB just for create/update:

```
    public function handle(CreateResourceRequest $request)
    {
        $resource = $request->resource();

        $resource::authorizeToCreate($request);

        $resource::validateForCreation($request);

        $model = DB::transaction(function () use ($request, $resource) { // <--- this
            [$model, $callbacks] = $resource::fill(
                $request, $resource::newModel()
            );
```

Wouldn't it be better to set a flag in `config/nova.php` which allows people the option to use transactions or not? Something like this:

```
    /*
    Specifies whether or not to create and update models using database transactions. Set to false if you
    are using a database driver which does not support them.
    */
    'transactions' => true, 
```

Filing under bugs as the idea of Eloquent - as far as i am aware - is to abstract the DB logic so any driver can be used. There's no need to do it for everything in Nova, but simple create/update is a must. I rarely work on any Laravel project these days - or any other - which is using an RDBMS as its primary storage. I can update a private repo, but it's a nightmare if we need to upgrade the whole package.

This doesn't need to be a stand-off between users configuring unsupported drivers, driver maintainers, and Nova maintainers. Surely there has to be a simpler workaround which will allow Nova to be used more widely?

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by davidhemphill** [comment]
Like you said Laravel, and Nova by extension, doesn't support MongoDB. If Laravel ever supports MongoDB officially, we will implement support for it inside of Nova.
