### ISSUE TITLE
PHP Deprecated message after update PHP to version 8.1.1

### ISSUE THREAD

**Issue by massimodellarovere** [laravel/nova-issues#3713]
- Laravel Version: 8.80.0
- Nova Version: 3.30.0
- PHP Version: 8.1.1
- Database Driver & Version: MySQL 5.7.12
- Operating System and Version: Ubuntu 20.04.3 LTS
- Browser type and version: Brave 1.34.81 Chromium: 97.0.4692.99 

### Description:
Receive multiple message in Apache Log after update PHP to version 8.1.1

![image](https://user-images.githubusercontent.com/5731295/150642687-524dabf0-a308-4b53-aebe-95c88565d084.png)

**Comment by bashgeek** [comment]
Definitely still happening, Mr. Stale Bot.

**Comment by crynobone** [comment]
The fix has been implemented and waiting for next patch release.

**Comment by leMaur** [comment]
@crynobone Any ETA for the next patch release?
