### ISSUE TITLE
Required fields not validated when using multiple panels

### ISSUE THREAD

**Issue by marjangvg** [laravel/nova-issues#3716]
- Laravel Version: 8.80.0
- Nova Version: 3.30.0
- PHP Version: 7.3.16
- Database Driver & Version: MySQL 5.7
- Operating System and Version: Win 10
- Browser type and version: Chrome 97.0.4692.71

### Description:
I have multiple nova panels in the model, and each of them has a required field in it. When submitting the form, only the fields in the first panel are validated. 
Once I fill the fields in the first panel, the form can be submitted even though the other required fields in the other panels are still empty.

### Detailed steps to reproduce the issue on a fresh Nova installation:
![browser](https://user-images.githubusercontent.com/3532308/151189601-a1460214-6499-468e-94df-21f0e88c59ae.png)
![code](https://user-images.githubusercontent.com/3532308/151189608-b2d2b3c9-1e99-4803-9cfa-185017b327c3.png)

**Comment by crynobone** [comment]
`->required()` is not the same to `->rules('required')`.

**Comment by davidhemphill** [comment]
Yes, @crynobone is correct, `the required` method on a field is typically used with a callback to visually mark the field as required in cases where it's too complex for validation rules to indicate as such.
