### ISSUE TITLE
Add Laravel Nova API Documenation

### ISSUE THREAD

**Issue by ZebTheWizard** [laravel/nova-issues#3718]
It would be nice to have web documentation like Laravel Illuminate API (https://laravel.com/api/8.x/index.html) for Nova.

This would allow developers to easily explore features available through inheritance.  My IDE can not easily jump to the underlying classes.  Having an API reference on the web could also help drive sales and help developers create better tools. 

What do you all think about this?

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by ZebTheWizard** [comment]
For future reference:

I have been using Nova since version 1.0 and I just learned today that most of the available capabilities lie in `Laravel\Nova\Resource`.   The current developer resources and marketing give the illusion that Nova is fairly strict.

With API documentation, advanced developers could easily discover the power of Nova.  For example, there is a method `shouldAddActionsField` which allows the actions UI to be hidden while allowing a model to be actionable. 

In my opinion, at a minimum it would be nice to highlight underlying traits in the current documentation like:
`Laravel\Nova\Authorizable`
`Laravel\Nova\FillFields`
`Laravel\Nova\PerformsValidation`
`Laravel\Nova\PerformsQueries`
`Laravel\Nova\ResolvesActions`
`Laravel\Nova\ResolvesFields`
`Laravel\Nova\ResolvesFilters`
`Laravel\Nova\ResolvesLenses`
`Laravel\Nova\ResolvesCard`

**Comment by crynobone** [comment]
Laravel Framework API documentation makes sense since it's a collection of libraries while all the above classes are internal classes that we use to build Nova as software. 

Putting those as public API would be we no longer able to change the internal methods within patch releases to fixed bugs are introduce none-breaking features.

**Comment by ZebTheWizard** [comment]
I see what you mean.

Do you foresee any use cases where a subset of those traits/methods are extracted into a public API?  Or will all the methods from the traits above remain as internal code?  Just curious.
