### ISSUE TITLE
Forgot Password link not showing when used with Octane

### ISSUE THREAD

**Issue by jcsoriano** [laravel/nova-issues#3724]
- Laravel Version: 8.81.0
- Nova Version: 3.30.0
- PHP Version: 8.0.7
- Operating System and Version: Ubuntu 20.04.2
- Browser type and version: Chrome 97.0.4692.99

### Description:

When Laravel Nova is used with Octane, the "Forgot Your Password?" link is not showing. It works when not running from an Octane server, but it's not showing when run from Octane.

Here's my investigation so far:

1. The "Forgot your password?" link showing depends on `if (Nova::resetsPasswords())` being true

2. When I do `dump(Nova::resetsPasswords())` on auth/login.blade.php (served from Octane), it returns false

3. The only place I see `$resetsPasswords` being set to true is in `->withPasswordResetRoutes()`. I confirm that my `NovaServiceProvider` has `Nova::routes()->withPasswordResetRoutes()` in it

4. The only place I see `$resetsPasswords` being set back to false is in `InteractsWithEvents@flushState`

5. The only place I see `Nova::flushState()` being called is in line 55 of `NovaCoreServiceProvider.php` **which is only called when the `Laravel\Octane\Events\RequestReceived` is fired**

**Thus, it seems that when Nova is served from Octane, `::resetsPasswords()` will always be false.**

When I run `Nova::resetsPasswords();` on tinker, it returns true, likely because Octane's `RequestReceived` event does not fire when in tinker.

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Create a new Laravel app with Laravel Nova
2. Install Laravel Octane
3. Serve the app on an Octane server, and go to Nova's login page

You will see that the "Forgot your password?" link does not show

**Comment by jcsoriano** [comment]
Is removing line 47 of `Laravel\Nova\Concerns\InteractsWithEvents` the solution to this? I'd be willing to do a PR for this change but Nova isn't open source (understandably) :)

**Comment by crynobone** [comment]
Octane should always re-register ServiceProvider on each request but it seems it not doing so in your case. Will investigate this issue next week.

**Comment by crynobone** [comment]
Fixed in v3.31.0: https://nova.laravel.com/releases/3.31.0
