### ISSUE TITLE
displayUsing() and title() conflict  

### ISSUE THREAD

**Issue by mikecornille** [laravel/nova-issues#3726]
- Laravel Version: 8.81.0
- Nova Version: 3.30.0
- PHP Version: 7.4.6
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
