### ISSUE TITLE
Missing Tailwind classes

### ISSUE THREAD

**Issue by bencounsell** [laravel/nova-issues#373]
It seems that the CSS shipping with Nova is a limited version of Tailwind — not all classes are available. Looking out the tailwind.js, some of the utilities are commented out, I'm guessing to save on file size?

The docs say:

> Nova utilizes the Tailwind.css utility library for all styling. So, you are free to leverage all Tailwind features and classes that are needed by your custom components.

For example: In a custom Card, I'm trying to use Tailwind background classes but they are not included in the CSS.

Try adding `bg-grey-darker` and that class is not defined in the CSS.

**Comment by davidhemphill** [comment]
Nova uses its own customized version of the Tailwind configuration. So the recommended approach is to either use the classes available in the system already or add them to your specific tool's css via the included CSS file or the `style` block within the component.

**Comment by AidanCoreBlue** [comment]
The documentation needs to be updated, if there's a custom tailwind configuration then it's not accurate to say "all Tailwind features and classes" are available.

**Comment by slovenianGooner** [comment]
I agree, in fact, many are missing. It would be at least nice to have the list of available classes available in docs somewhere.

**Comment by camaech** [comment]
Please update tailwind to the latest version. Or give us a way to include specific tailwind styles globally.

**Comment by 2bj** [comment]
+1

**Comment by maherelgamil** [comment]
any updates here ? @davidhemphill

**Comment by njbarrett** [comment]
Would love an update on this..

**Comment by bolechen** [comment]
+1

**Comment by blumtech** [comment]
+1

**Comment by diphone-net** [comment]
+1

**Comment by maherelgamil** [comment]
+1

**Comment by thechrisroberts** [comment]
Yep, still an undocumented subset while the documentation states, "...you are free to leverage all Tailwind features and classes..."

**Comment by Ragash** [comment]
embarrassing

**Comment by rexliu0715** [comment]
+1

**Comment by amidesfahani** [comment]
++1

**Comment by ThaDaVos** [comment]
When will this be fixed, seriously.... I wanted to build up a nice card grid as follows - but noticed classes were missing...
https://codepen.io/codetimeio/pen/RYMEJe

**Comment by revenew** [comment]
+1

**Comment by parfumix** [comment]
+1

**Comment by ThaDaVos** [comment]
Please don't +1 guys - just add a thumbs up on the original comment instead

**Comment by ThaDaVos** [comment]
New issue for who ever is interrested: https://github.com/laravel/nova-issues/issues/2556

**Comment by desaintflorent** [comment]
Missing so much a **real** and **updated** tailwindcss capability too !
I guess we will have to keep dreaming about it.

**Comment by mehmetuygun** [comment]
They fixed the issue by removing it from the documentation. It's a good solution I think!

**Comment by nsoncode** [comment]
So if one askes for your money for Nova and the documentation clearly says all tailwind features are available in Nova.... maybe I'm asking to much here but... maybe prioritize adding the missing parts of tailwind or remove the statement from the documentation. Thank you!

**Comment by Milkhan** [comment]
@davidhemphill Do we have a class reference list that is available in the code? I would like to see which classes are available. If there is no such list,  I can volunteer to create one with a bit of guidance.
Thank you

**Comment by pesovski** [comment]
Come on, it would be effortless to add it with Nova. It's shame it works only with a subset of classes.

**Comment by Tarpsvo** [comment]
As Nova's maintainers are not flexing, I decided to make the simplest package Nova has ever seen.

https://github.com/optimistdigital/nova-tailwind

The motivation behind this? I create a lot of open-source packages for Laravel Nova and I've encountered the issue of missing Tailwind classes multiple times now. I decided to just create one package that fills in the gaps and add it as a dependency of the other packages so every package could use the Tailwind classes.

**Comment by codicastudio** [comment]
Following up on this topic. The other issues opened on this topic are closed without a reasonable resolution.

**Comment by slavicd** [comment]
Not a solution, David.

**Comment by oraneedwards** [comment]
I imported tailwind to the nova component sass file. Good enough workaround for me.

`@import url(https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css);`

**Comment by leecolarelli** [comment]
Missing pl-10! Simple classes missing. Really could do with fixing.

**Comment by johnpuddephatt** [comment]
If I use JIT with my own tool, and my tool use a class like "p-4", this appears in a stylesheet that comes after Nova's main stylesheet, which means that p-4 takes precedence over breakpoint-specific styles like "md:p-8" in the main Nova stylesheet (because in CSS, media queries don't have higher specificity, so order of occurrence matters).

One way around this could be @nbyloff's suggestion about extending what files Nova's TW scans. 

Another – simpler? – solution could be to update the nova docs to tell all packages to use a tailwind prefix (https://tailwindcss.com/docs/configuration#prefix)

**Comment by nullthoughts** [comment]
@nbyloff One workaround is to add a prefix, unfortunately it's not an elegant one (inspired by https://github.com/outl1ne/nova-color-field/blob/master/tailwind.config.js):

tailwind.config.js
```js
module.exports = {
    ...
    prefix: 'nc-'
}
```

Then you would reference the classes/utilities you'd like with the prefix (eg. `nc-py-6`, `nc-grid`, `nc-grid-cols-3`, etc). You could obviously only reference the missing utilities in that manner, however sticking to the prefix in your Nova Tool would ensure all Tailwind utilities are available.

Nova is a wonderful asset, and maybe down the road Tools could be stubbed with the fully accessible Tailwind utilities (maybe conflicts can be avoided by using a prefix in the Nova core instead?)

Note: Utilizing just `@tailwind utilities;` in tool.css might also help avoid conflicts.

**Comment by abordage** [comment]
If you need missing color styles (or any others styles) - try this: https://github.com/abordage/tailwind-colors

Styles with all palette are already generated. In the config, you can specify which styles still need to be added.

**Comment by massimodellarovere** [comment]
I found this solution for my environment:

```
module.exports =
{
  prefix  : 'admin-',
  darkMode: ['class', 'html[class~="dark"]'],
  content :  [
    './app/Nova/**/*.php',
    './resources/assets/admin/**/*.{vue,js}'
  ]
};
```
![image](https://user-images.githubusercontent.com/5731295/186976365-9d2723b3-2c93-48f9-b0fe-fa79ccfd7c85.png)

**Comment by xfolder** [comment]
`cd ./vendor/laravel/nova
mv webpack.mix.js.dist webpack.mix.js
npm install
add safelist patterns (/^.*/ for all) to tailwind.config.js
npm run dev
rm -rf node_modules
cd -
php artisan nova:publish`
![twcjs](https://user-images.githubusercontent.com/13942856/190120621-a053c4a6-7c6f-4c5c-8a96-20891e6d4602.png)

**Comment by stephan-v** [comment]
@davidhemphill Please re-open this because this is not resolved in the slightest. It feels like developing custom components is an afterthought due to how this is set up.

**Comment by wtySk** [comment]
Is this still an issue in 2025?
Since the author has adopted Tailwind and intentionally limited the available CSS classes, it would make more sense to provide a configuration option allowing users to choose whether to use the full set of styles.
The current approach—only allowing a subset without clearly indicating which classes are available—is not ideal.

**Comment by GoatFreezy** [comment]
This is still an issue. 
Trying to customize some badges and not knowing why come classes just doenst work with nothing talking about this in the documentation is really frustrating.
If you doenst know tailwind configuration and doenst lookup laravel nova core files you cannot know which classes or option are available to this day.

**Comment by Livijn** [comment]
I agree there should be an easier way to do this. I solved it by just including tailwind like this in boot() of NovaServiceProvider:
```php
Nova::remoteScript('https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4');
```

You can get the cdn script url from:
https://tailwindcss.com/docs/installation/play-cdn
