### ISSUE TITLE
Softdeletes - Filter OnlyTrashed - Actions: Force delete and Delete

### ISSUE THREAD

**Issue by ilievinti** [laravel/nova-issues#3732]
- Laravel Version: 8.12
- Nova Version: ~3.0
- PHP Version: 7.4
- Operating System and Version: w10
- Browser type and version: Mozilla
- Reproduction Repository: https://github.com/###/###

### Description:

Using Model with trait SoftDeletes i delete one record then i filter Only Trashed, i select one trashed record, i click recycleBin icon and i see action Force delete (ok) but action Delete too (not ok). It is correct?

### Detailed steps to reproduce the issue on a fresh Nova installation:

![temp2](https://user-images.githubusercontent.com/36962734/152831008-133f254d-7533-4d88-ae8f-12da5181b396.jpg)

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
