### ISSUE TITLE
Filter Only Trashed - but near icon Filter do not appear (1)

### ISSUE THREAD

**Issue by ilievinti** [laravel/nova-issues#3733]
- Laravel Version: 8.12
- Nova Version: ~3.0
- 
### Description:

Filter Only Trashed - but near icon Filter do not appear (1) to see that i have filtered records. Is it correct?

### Detailed steps to reproduce the issue on a fresh Nova installation:

![temp3](https://user-images.githubusercontent.com/36962734/152834499-de46ab6d-bc70-4744-8130-2db26ffd2c09.jpg)

**Comment by crynobone** [comment]
Trashed and Per Page aren't filters
