### ISSUE TITLE
Allow us to append "Resource" to resource class names

### ISSUE THREAD

**Issue by diontron** [laravel/nova-issues#3735]
it's really confusing trying to constantly differentiate between my models and resources because they have the exact same name

if we could do "UserResource extends Resource" i think this would be greatly beneficial.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
