### ISSUE TITLE
Disable editing and/or deleting

### ISSUE THREAD

**Issue by talovicnedim** [laravel/nova-issues#374]
It would be great if it's possible to hide create/edit/delete buttons and excluding the form.

The reason why I need this is that I have a contact page where data is inserted by API (from mobile apps) so I don't need adding/editing data by admins. 

I know it's possible to hide buttons by CSS, but is there any native method?

**Comment by poxin13** [comment]
https://nova.laravel.com/docs/1.0/resources/authorization.html#policies

**Comment by davidhemphill** [comment]
Please check the autorization docs linked above. 😄

**Comment by farwish** [comment]
https://github.com/laravel/nova-issues/issues/252

**Comment by emad-sure** [comment]
@davidhemphill  what if i want to use authorizedToDelete() in the resource with some condition like :
please show the delete icon when some value is true according to all records in the resource table

**Comment by emad-sure** [comment]
@davidhemphill  so far you were right about the authorization through the policy 
i could make something like that  : 

`public function delete(User $user, Term $term)
    {
        return $term->deleteable ;
    }`

where deleteable is a boolean value in my table
