### ISSUE TITLE
Symfony\Component\Mime\Exception\LogicException: An email must have a "From" or a "Sender" header.

### ISSUE THREAD

**Issue by fabiov** [laravel/nova-issues#3740]
- Laravel Version: 9.0.2
- Nova Version: 3.31.0
- PHP Version: 8.1.0
- Database Driver & Version: mysql 8.0
- Operating System and Version: Ubuntu 20.04
- Browser type and version: all
- Reproduction Repository: https://github.com/###/###

### Description:
![error](https://user-images.githubusercontent.com/2004589/153627781-ce6d263e-aa34-42c9-a984-2b7d9b4a1986.png)

### Detailed steps to reproduce the issue on a fresh Nova installation:
Go to **/nova/password/reset** page then insert a valid email and press **Send Password Reset Link**

**Comment by crynobone** [comment]
See https://github.com/laravel/framework/issues/40940
