### ISSUE TITLE
`action_events` DB table name is hardcoded

### ISSUE THREAD

**Issue by lptn** [laravel/nova-issues#3745]
- Laravel Version: 8.X.X
- Nova Version: 3.31.0
- PHP Version: 8.1

### Description:
There are at least 14 places where `action_events` table name is hardcoded:
![image](https://user-images.githubusercontent.com/5278175/153912340-73902170-2a00-4073-bdd2-b9635a4c36bf.png)

There is an ability to customise `ActionEvent` model (use custom one e,g, by existing \Laravel\Nova\Actions\ActionEvent::class), it will be also nice to have an ability to customize table name. If I will extend  \Laravel\Nova\Actions\ActionEvent and override `public function getTable()` - it's still not enough, as table name hardcoded in other places

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
