### ISSUE TITLE
Unnecessary field calculation slows down BelongsTo dropdown data retrieval

### ISSUE THREAD

**Issue by puzzledmonkey** [laravel/nova-issues#3748]
- Laravel Version: 8.81.0
- Nova Version: 3.31.0
- PHP Version: 7.4.26
- Database Driver & Version:
- Operating System and Version: Windows 10
- Browser type and version: Firefox
- Reproduction Repository: https://github.com/###/###

### Description:
On a Nova resource, a large and complicate fields() array - especially one with calculated fields - will involve lots of calculations and sometimes additional related object loads, when loading each model.

However, for dropdowns such as BelongsTo the majority of these fields are unnecessary. When loading lots of options, this delay can make a huge difference. As anecdotal evidence, I have a system that loads 2000 staff for a dropdown, and in this case, the problem means the difference between 0.5 seconds, and 4-5 seconds for the /nova-api/<resource>/associatable/<relation> responses on my current production system.

The simple fix is to add this to the top of fields() for any affected resources (or a similar object-oriented solution for multiple resources)

```
public function fields(Request $request)
    {
        if ($request->is('*/associatable/' . Str::kebab(class_basename(get_called_class())))) {
            return [];
        }
...
```

This avoids all of the field computation and calculations which are unnecessary for the dropdown population. It seems to have no sideeffects.

I wonder what is the use case for calculating fields for these dropdown api calls, and if it would not be better to avoid calling fields() altogether in this case, since it appears the data is read anyway directly from the id and static::$title fields.

For the record, I tried to optimise the database dropdown query through the relatableQuery function, but the gains made there were significantly less compared to this.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Unfortunately not easy due to the complexity of generating a fields() object with the amount of data where speed is noticably effected.

**Comment by crynobone** [comment]
The full database data needs to be available because Nova needs to resolve title(), subtitle(), avatar in certain. Even the basic dropdown it needs to resolve title() from Resource.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by puzzledmonkey** [comment]
@crynobone I am talking about the dropdown fields only - when editing a resource, for any BelongsTo fields for example.
In this case they are loading a url for data which is /nova-api/<resource>/associatable/<dropdown-resource>

for example /nova-api/staff/associatable/department - when populating a 'department' dropdown on a 'staff' resource when editing the staff resource.

returning [] in the fields() method for this url has no effect on the dropdown information as far as I can see. In the title() method for the resource, I have full access to all fields on the underlying model (eg $this->department->name). This seems unrelated to  the fields() function return value.

@davidhemphill I would consider this a bug as it's slowing down the system by calculating a lot of field schema information for each resource, that is then ignored for the dropdown population. This causes significant extra processing and delay for large numbers of complicated resource objects, and as I wrote above it has seemingly no bearing on title() { return $this->... } capabilities.

**Comment by crynobone** [comment]
You're asking for a breaking change. As I said earlier, title() is used via dropdown too.

**Comment by puzzledmonkey** [comment]
sorry @crynobone I must not be explaining myself properly.
For example, in app/Nova/Staff.php

```
public function fields(Request $request)
{
    if ($request->is('*/associatable/' . Str::kebab(class_basename(get_called_class())))) {
        return [];
    }
    return [ ... complicated fields that would take measurable time to calculate when populating the dropdown ... ];
}

public function title() {
    return $this->name . ' with ' . count($this->tasks) . ' tasks';
}
```

this works perfectly fine, showing name with x tasks correctly in both dropdowns via /nova-api/resource/associatable/relation and also everywhere else (i.e. searching results etc). It breaks nothing at all as far as I can see, and I wondered why fields() is getting called in this case as the data it returns seems unused when calling title() for the dropdown.

If it's a problem to add to Nova, no worries, but I just have this code in a base resource class that all others inherit from, and it speeds up all of the dropdowns immeasurably across the site, and I thought it would be good to bring it to the team's attention.

Thanks for a wonderful product in Nova anyway and best wishes.

**Comment by crynobone** [comment]
>  I wondered why fields() is getting called in this case as the data it returns seems unused when calling title() for the dropdown.

Fields are required to verify that there is indeed a `RelatableField` instance (avoid any potential security concern) and from there we build `$field->buildAssociatableQuery()` as well as finding the related Resource from `$field`.

**Comment by puzzledmonkey** [comment]
@crynobone thanks for the clarification. but unless I'm mistaken those `RelatableFIeld` instances and running `$field->buildAssociatableQuery()` are the fields on the object itself, not the related object. so for example I'm not talking here about modifying any output when viewing Staff resources (as per my example above) - it's anything that references the Staff list with a related object.

Just to be clear, say there's another nova resource /app/Nova/User which can belong to a Staff and as such has a `BelongsTo::make('Staff')` field, which, on the 'Edit User' page, loads in the list of Staff objects for the dropdown. Populating this dropdown in the 'Edit User' page for the 'Staff' field is the request I'm targeting with the overriding fields() methods above - so it's not any request relating to the actual User itself (the URL has no id in it, it's just `/nova-api/user/associatable/staff` in this example).

Therefore I don't think it's a security risk in this case but I'm also relatively new to Nova so it's quite possible I'm missing something. Thanks for your time anyway.

**Comment by davidhemphill** [comment]
I would need to see the full `Resource::fields` method, but I suspect there's a field touching the database directly (e.g. Like a `Select::make('Category')->options(Category::all()->pluck('title', 'id')`), instead of returning them from a `Closure`, where they will be deferred). This would slow down Nova quite a bit since the query would be run for every `Resource` instantiation. Can you post your `fields` method?

**Comment by puzzledmonkey** [comment]
hi @davidhemphill yes you're right, that's exactly what's happening - i need extra database fields in order to generate complicated json key/value schemas for the fields() return value (in my case there are kitchens in the database, and i need to retrieve a list of these in order to show the correct fields for the index/detail/edit pages). for index pages showing 20 or so at a time, the impact of this is negligible.

but in the special case of showing the dropdown results (for example `/nova-api/user/associatable/staff` or any other `/nova-api/xxx/associatable/yyy` url), which returns all results at once, calling fields() seems to have no impact whatsoever on the data returned (regardless of using `title()` or not), and therefore these extra calculations seem to be done for no reason.

I did some more digging here and found the reason why it's happening, and it comes down to the auto-detect code for avatars in `nova/src/ResolvesFields.php` in `resolveAvatarField`. I guess in this case there's no workaround without breaking backwards compatibility, since it auto-senses the avatar field from the fields() return result. Alternatively a more messy forwards-compatible way would be to add some static field $showAvatarInDropdown = true/false, for now it can default to true and be set to false if desired, and switched in the future. But I appreciate this is a lot of work, and in this case I'm happy to stick with my solution, however hacky it is :)

**Comment by puzzledmonkey** [comment]
By the way, for anyone else searching here - I solved this by simple overriding resolveAvatarField in my Resource class in the end (since I don't use avatars at all in this project)

```
public function resolveAvatarField(NovaRequest $request)
{
    return null;
}
```
