### ISSUE TITLE
Allow ignore platform reqs for composer

### ISSUE THREAD

**Issue by AbdelkaderBah** [laravel/nova-issues#3749]
I am using Windows and Windows Sublinux and handling multiple PHP versions,
I think it might be useful to be able to pass ignore platform requirements for composer

 ```bash 
--ignore-platform-reqs
``` 

![image](https://user-images.githubusercontent.com/14665300/154020891-cf6b1a38-911e-47e2-b3ac-8231651e2341.png)

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
You should use the exact path to each PHP version binary, such as:

```
/usr/local/Cellar/php@8.0/8.0.15/bin/php artisan nova/tool foo/bar
```

**Comment by AbdelkaderBah** [comment]
> You should use the exact path to each PHP version binary, such as:
> 
> ```
> /usr/local/Cellar/php@8.0/8.0.15/bin/php artisan nova/tool foo/bar
> ```

Thanks but the issue is about Composer platform requirements

**Comment by crynobone** [comment]
> Thanks but the issue is about Composer platform requirements

Composer will follow the current PHP binary.

**Comment by AbdelkaderBah** [comment]
> > Thanks but the issue is about Composer platform requirements
> 
> Composer will follow the current PHP binary.

Yes but you can't pass composer arguments
