### ISSUE TITLE
Blank Avatar Validation Error

### ISSUE THREAD

**Issue by bradders** [laravel/nova-issues#375]
I seem to be having issues with validating the Avatar field.

Avatar::make("Avatar", "avatar")->disk("public")->rules("nullable", "image", "max:5000")

When I submit a blank form (to test the validation) I get the following error. Which only seems to be present when I don't input an avatar.

`Unhandled promise rejection TypeError: "_context2.t0.response is undefined" (app.js:28507:11)`

The underlying database column for that is a VARCHAR 255 which allows null values.

**Comment by StanBarrows** [comment]
Same here with updating an Image field. Not able to leave it blank

<img width="1655" alt="image" src="https://user-images.githubusercontent.com/10268813/44926681-9267cd80-ad52-11e8-853d-f5656acb689a.png">

**Comment by bradders** [comment]
Strangely enough, I get this error in Firefox (61.0.2 macos) and Safari (11.1.2 macos) but not in Chrome (68.0.3440.106 macos).

**Comment by bonzai** [comment]
Can you try upgrading to the newest version?

Feel free to post this issue again if the problem persists.
