### ISSUE TITLE
price asMinorUnits in edit and create

### ISSUE THREAD

**Issue by Chyzhykal** [laravel/nova-issues#3750]
- Laravel Version: 9.0
- Nova Version: 3.31.0
- PHP Version: PHP 8.0.6

### Description:
I have same issue as in https://github.com/laravel/nova-issues/issues/3444

When using asMinorUnits() input in edit and create, currency is not converted. Instead it displays as integer. 

Resource details :
![image](https://user-images.githubusercontent.com/43599055/154331877-00378b2b-e23e-4f68-a865-48684444e669.png)
Edit resource :
![image](https://user-images.githubusercontent.com/43599055/154332012-46c7f02a-d14c-4498-b4e6-41344c6b362f.png)

**Comment by crynobone** [comment]
Yes on the current series it will show the lowest unit for each currency and we have changed this for Nova 4 to avoid any breaking changes. 

Feel free to test out  https://github.com/laravel/nova-issues/issues/3444#issuecomment-887390201 snippet if you want to use it today.

**Comment by Chyzhykal** [comment]
Hi, this snippet didn't seem to work for me. What exactly is it supposed to
do? It should convert 10225 into 102,25 in input?

**Comment by Chyzhykal** [comment]
Tested again today, snippet doesn't work. Still same issue. I cast model value as integer, then i use that snippet field to display : 
![image](https://user-images.githubusercontent.com/43599055/154428887-f09468b3-9091-43e8-b6df-fda11cc78619.png)
Maybe i am doing something wrong?
