### ISSUE TITLE
False negative for `isActionRequest`

### ISSUE THREAD

**Issue by jacob418** [laravel/nova-issues#3755]
Laravel Version: 8.75.0
Nova Version: 3.30.0
PHP Version: 8.0.9
Database Driver & Version: Docker-Image: postgres:13
Operating System and Version: Linux 5.4.0-96-generic
Browser type and version: Google Chrome/96.0.4664.110

### Description:

The `isActionRequest` method of `\Laravel\Nova\Http\Requests\NovaRequest` returns false for an action-request.

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Create a new action
2. Use the `onlyOnTableRow` option
3. Use the `isActionRequest` in the `indexQuery` method

#### Expected behavior

- `isActionRequest` returns true

#### Observed behavior

- `isActionRequest` returns false

### Possible reason

`\Laravel\Nova\Http\Requests\NovaRequest::isActionRequest` checks if the third segment of the path equals `actions`. But in case of table-row actions, the path-segment is `action` thus failing the check.

### Possible fix

Replace `$this->segment(3) == 'actions'` with `$this->segment(3) == 'actions' || $this->segment(3) == 'action'`

**Comment by crynobone** [comment]
`action` URI segment will always be an instance of `ActionRequest`. To avoid causing breaking changes this changes only will happen in Nova 4.
