### ISSUE TITLE
Problem with `+` as action name

### ISSUE THREAD

**Issue by jacob418** [laravel/nova-issues#3756]
Laravel Version: 8.75.0
Nova Version: 3.30.0
PHP Version: 8.0.9
Database Driver & Version: Docker-Image: postgres:13
Operating System and Version: Linux 5.4.0-96-generic
Browser type and version: Google Chrome/96.0.4664.110

### Description:

Using the string `+` character as action name breaks the action trigger (at least for inline actions).

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Create a new Action
2. Set `+` as the name (`class MyAction extends Action { public $name = '+'; /* ... */ }`)
3. [Possibly optional] Define the action as 'inline' with the `onlyOnTableRow` method
4. Try to trigger the action from the Nova UI

#### Expected Behavior

- Action is triggered

#### Observerd behavior

- Action is not triggered
- Browser console logs errors:

```
[Vue warn]: Missing required prop: "selection"

found in

---> <ToolbarResourceDropdown>
       <ToolbarResource>
         <ToolbarToolList>
           <Root>
```

```
[Vue warn]: Error in v-on handler: "TypeError: Cannot read properties of undefined (reading 'withoutConfirmation')"

found in

---> <InlineActionSelector> at resources/js/components/Index/InlineActionSelector.vue
       <ResourceTableRow>
         <Draggable>
           <ResourceTable>
             <LoadingView> at resources/js/components/LoadingView.vue
               <Card> at resources/js/components/Card.vue
                 <LoadingView> at resources/js/components/LoadingView.vue
                   <ResourceIndex> at resources/js/views/Index.vue
                     <DetailHasManyThroughField> at resources/js/components/Detail/HasManyThroughField.vue
                       <RelationshipPanel> at resources/js/components/Detail/RelationshipPanel.vue
                         <LoadingView> at resources/js/components/LoadingView.vue
                           <Detail> at resources/js/views/Detail.vue
                             <Root>
```

```
TypeError: Cannot read properties of undefined (reading 'withoutConfirmation')
    at VueComponent.determineActionStrategy (app.js:81411)
    at VueComponent.executeSingleAction (app.js:10142)
    at click (app.js:54986)
    at invokeWithErrorHandling (vendor.js:113519)
    at HTMLButtonElement.invoker (vendor.js:113844)
    at HTMLButtonElement.original._wrapper (vendor.js:119238)
```

### Possible reason

The computed property `selectedAction` is undefined within the `determineActionStrategy` method.

**Comment by davidhemphill** [comment]
You should consider not using common programming operators for your action names as they definitely can cause complications within PHP or JavaScript.

**Comment by jacob418** [comment]
> You should consider not using common programming operators for your action names as they definitely can cause complications within PHP or JavaScript.

It should be avoided using the display label of an action as identifier since human language tends to conflict with programming languages - for example in the case you are using mathematical operator-signs for labels.
