### ISSUE TITLE
Call to ResourceCountController generates invalid SQL, Error in PostgreSQL when filter present.

### ISSUE THREAD

**Issue by vocalspace** [laravel/nova-issues#376]
In v1.0.8, when browsing any resource, the call to get the count fails **if** a sort order is provided.. 

This fails:
`127.0.0.1:8000/nova-api/users/count?search=&filters=&orderBy=id&orderByDirection=desc&perPage=25&trashed=&page=1&viaResource=&viaResourceId=&viaRelationship=&relationshipType=`

While this works:
`127.0.0.1:8000/nova-api/users/count?search=&filters=&orderBy=&orderByDirection=desc&perPage=25&trashed=&page=1&viaResource=&viaResourceId=&viaRelationship=&relationshipType=`

The reason is `$request->getQuery()` generates this query:
```
select count(*) as aggregate from "users" order by "users"."id" desc
```
Which, while it may be work in MySql, is not valid in PostgreSQL (nor is it the least bit efficient since it counts the aggregate of each selected record instead of querying the table structure for the latest record count).

In order for the above method to work, PostgreSQL requires the query to be grouped by the sort order. 
```
ERROR:  column "users.id" must appear in the GROUP BY clause or be used in an aggregate function
```
Instead, to be most efficient, it should remove the order by, since the count is the count irrespective of order.

Cheers.

**Comment by davidhemphill** [comment]
Since this issue was created, there's been a ton of improvements regarding Postgres and these sorts of situations. Feel free to post a new issue if your issue persists.
