### ISSUE TITLE
Cannot install via composer. Is https://nova.laravel.com down or not responding properly?

### ISSUE THREAD

**Issue by martemorfosis** [laravel/nova-issues#3762]
- Laravel Version: 9.2.0
- Nova Version: 3.31.0
- PHP Version: 8.1.3
- Operating System and Version: Ubuntu 21.10

### Description:

Cannot install via composer, seems that https://nova.laravel.com is not responding properly.

![image](https://user-images.githubusercontent.com/2488715/156398220-cff222ed-43db-4af4-98ae-25f16f7e1097.png)

### Detailed steps to reproduce the issue on a fresh Nova installation:

- Add :

```
    "repositories": {
        "nova": {
            "type": "composer",
            "url": "https://nova.laravel.com"
        }
    }
```
    
to the composer.json file, then
    
- `$ composer update`
- Connection times out

**Comment by martemorfosis** [comment]
Looks like the error happens only when trying to install via `sail composer update` using just `composer update` seems to work fine.

**Comment by davidhemphill** [comment]
Can you file an issue over at the laravel/sail repository? This doesn't seem specific to Nova. Thank you!

https://github.com/laravel/sail/issues/new?assignees=&labels=&template=1_Bug_report.md
