### ISSUE TITLE
Default Translations are not used in some places of Nova

### ISSUE THREAD

**Issue by marijoo** [laravel/nova-issues#3767]
- Laravel Version: 9.4.1
- Nova Version: 3.31.0
- PHP Version: 8.1.3
- Database Driver & Version: MySQL 5.7
- Operating System and Version: macOS 12.2.1
- Browser type and version: 15.3

### Description:

I stumbled upon a problem that seems to be the opposite to the problem mentioned in #2515: Some parts of Nova are not translated with the default translation strings inside `/lang/vendor/nova/de.json`. The custom translations in `/lang/de.json` works fine. It seems that this has something to do with Ajax Requests or something.

### This is what I found out so far:

- I debugged `NovaServiceProvider::allTranslations()` inside the packages `NovaServiceProvider::registerJsonVariables()` method and found out that all translations get correctly loaded, merged and passed to the script: The default translations located in `/lang/vendor/nova/de.json` as well as the custom translations in `/lang/de.json`.
- All custom translations from `/lang/de.json` are used as expected.
- The default translations from `/lang/vendor/nova/de.json` are not used in some places

And here is what bugs me about that last point:
- The buttons to attach relations described with `Attach :resource` by default are translated to the German `Ressource anhängen` even though this translation is located in `/lang/vendor/nova/de.json` *only*.
- The buttons to create a new resource described with `Create :resource` by default **are not** translated to the German `Ressource erstellen` even though this translation is located in `/lang/vendor/nova/de.json`.

I searched the package sources for `Attach :resource` and found out this is only used inside `*.vue` and `*.js` files whereas `Create :resource` is used in some `*.php` files as well.

**Comment by crynobone** [comment]
Can you create a reproducing code repository for us to debug?

**Comment by crynobone** [comment]
Unable to reproduce the issue with basic setup, see https://github.com/nova-issues/issue-3767/commit/d7acb55a09c1222f4f184b61de5d832790789b56

https://user-images.githubusercontent.com/172966/158117083-61218793-634c-4c8b-a954-2cfa7199ec45.mp4

**Comment by novelnet** [comment]
@marijoo did you find a fix? i have the same issue. Some translations are missing exactly as you explained.
