### ISSUE TITLE
Filter Indicator

### ISSUE THREAD

**Issue by itstrueimryan** [laravel/nova-issues#377]
It would be nice to have some indication aside from the URL that the resource set has a filter (or multiple filters) being applied to it, as well as the ability to quickly deactivate those filters individually without having to go into the filters dropdown menu.

**Comment by dillingham** [comment]
![filter-state-1](https://user-images.githubusercontent.com/29180903/45334592-69f98380-b549-11e8-9671-4693f753a33e.png)
![filter-state-2](https://user-images.githubusercontent.com/29180903/45334594-6c5bdd80-b549-11e8-8a8f-831ad3b6a25b.png)

**Comment by davidhemphill** [comment]
This has been added and will be included in an upcoming release.

**Comment by niladam** [comment]
@davidhemphill 	- i'm still not seeing this. Is there something that i'd have to do to see that ?

**Comment by yehudahkay** [comment]
I'm not seeing this either?
