### ISSUE TITLE
  Target class [cache] does not exist on upgrade

### ISSUE THREAD

**Issue by devzonedz** [laravel/nova-issues#3777]
- Laravel Version: 8.83.4
- Nova Version: 3.18
- PHP Version: 7.4.3
- Database Driver & Version: MySQL
- Operating System and Version: Linux Mint 20
- Browser type and version: Chrome
- Reproduction Repository: https://github.com/###/###

### Description:
I wanted to upgrade my laravel nova version from 3.17 to upper version but when i run composer update  i got this exception 
    
    In Container.php line 879:
                                            
      Target class [cache] does not exist.

**Comment by crynobone** [comment]
`cache` should be available on every Laravel installation.

https://github.com/laravel/laravel/blob/9.x/config/app.php#L147
