### ISSUE TITLE
Auth Facade inside Global Scope cause "Allowed memory ... exhausted"

### ISSUE THREAD

**Issue by henryavila** [laravel/nova-issues#3779]
- Laravel Version: 9.5.1
- Nova Version: 3.31.0
- PHP Version: 8.1.0
- Database Driver & Version: Mysql | Postgres
- Operating System and Version: MAC | windows 10
- Reproduction Repository: https://github.com/henryavila/nova

### Description:
When using  `Auth::user()` inside a scope, Nova will consume infinite memory triggering the error
*Allowed memory size of .... bytes exhausted*. The memory limit has been set to 1G but the error remains.

I've tested the same code without nova (on a fresh laravel) and the error don't happens.
The following error is written to log
```
// On Nova login
[16-Mar-2022 15:15:27 UTC] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in ...\vendor\laravel\framework\src\Illuminate\Collections\Arr.php on line 321
[16-Mar-2022 15:15:27 UTC] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in ...\vendor\ramsey\uuid\src\UuidFactory.php on line 475


// When getting all Users inside a route (as pointed in steps bellow)
[16-Mar-2022 15:36:03 UTC] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in ...\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php on line 3471
[16-Mar-2022 15:36:03 UTC] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in ...\vendor\symfony\error-handler\Error\FatalError.php on line 0

```

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Create [a scope](https://github.com/henryavila/nova/blob/main/app/Models/Scopes/SampleScope.php) that contain `Auth::user()`
- Attach the scope in a model
```php
   // inside model, as pointed by docs

   protected static function booted()
    {
        static::addGlobalScope(new SampleScope());
    }
```
- Try to read some data from model
```php
Route::get('/', function () {
    return \App\Models\User::all();
});
```
- The nova became completely broken. All access after login will result in error 500 exceding the max memory usage

A simple workarround is to pass the user to constructor (it's what I did to unbreak the app), it's a bug, then I'm reporting.

**Comment by crynobone** [comment]
I don't think this is Laravel Nova's specific bug. Imagine this.

1. Fetch `App\Models\User::all();`
2. It attempts to boot the global scope `SampleScope`
3. `SampleScope` tries to resolve `Auth::user()`
4. `session` auth guard with eloquent user provider then try to query the `User` model
5. Querying the `User` model from `EloquentUserProvider` triggers `SampleScope`
6. `SampleScope` tries to resolve `Auth::user()`

This is how infinite loops happen and based on your `/` get example. It perfectly shows that it's occurring on basic Laravel installation too.

**Comment by crynobone** [comment]
Closing this issue as we can't fix the usage issue. 

You can however create a custom `EloquentUserProvider` that queries the model without global scope if you wish to continue using `Auth::user()`.
