### ISSUE TITLE
CurrentRouteName not working due to route registration error

### ISSUE THREAD

**Issue by josemanuelsh** [laravel/nova-issues#3780]
- Laravel Version: 8.6.11
- Nova Version: 3.31.0
- PHP Version: 7.3

### Description:

Using ```Route::currentRouteName()``` in the auth layout view ```\nova\resources\views\auth\layout.blade.php``` (for a theme) returns ```null``` every time. After checking the code, I found that the name is specified in the second registered route like this:

File: nova\src\PendingRouteRegistration.php

```
Route::namespace('Laravel\Nova\Http\Controllers')
    ->domain(config('nova.domain', null))
    ->middleware($middleware)
    ->prefix(Nova::path())
    ->group(function () {
        Route::get('/login', 'LoginController@showLoginForm');
        Route::post('/login', 'LoginController@login')->name('nova.login');
    });
```

The issue is fixed by moving the name declaration to the first route like this:

```
Route::namespace('Laravel\Nova\Http\Controllers')
    ->domain(config('nova.domain', null))
    ->middleware($middleware)
    ->prefix(Nova::path())
    ->group(function () {
        Route::get('/login', 'LoginController@showLoginForm')->name('nova.login');
        Route::post('/login', 'LoginController@login');
    });
```

### Detailed steps to reproduce the issue on a fresh Nova installation:

Place the code ```{{ dd( Route::currentRouteName() ) }}``` in ```\nova\resources\views\auth\layout.blade.php``` or in a custom theme layout view.

We use this to create a link to go back to the login page from the "forgot/reset password" pages. We hide the link when we are in the login page. Instead of duplicating all the views for a link, we would like to have it in the layout and hide it when it is not relevant. I believe this is a bug, let me know if it is not.

Thanks.

**Comment by davidhemphill** [comment]
This is not a bug. Nova's `GET` login route does not have a name as we don't use it anywhere in the UI. You can link to the route manually in your layout. :-)
