### ISSUE TITLE
/nova path 404

### ISSUE THREAD

**Issue by suleymanozev** [laravel/nova-issues#3782]
- Laravel Version: 9.5.1
- Nova Version: 3.31.0
- PHP Version: 8.1.3
- Database Driver & Version:
- Operating System and Version: windows-10

### Description:
Clean Nova installation.

/nova path 404

**Comment by crynobone** [comment]
https://user-images.githubusercontent.com/172966/158960214-d4b070c9-2ecd-4934-95a2-fa6df3b9b987.mp4

Just created one project without issue. Definitely need more detail before we can troubleshoot your issue.

**Comment by suleymanozev** [comment]
NovaServiceProvider not added to config/app.php or not auto discovery.
