### ISSUE TITLE
The field help text is not showing anymore

### ISSUE THREAD

**Issue by ibrunotome** [laravel/nova-issues#3783]
- Laravel Version: 8.83.4
- Nova Version: v3.31.0
- PHP Version: 8.1.0
- Database Driver & Version: postgres 14
- Operating System and Version: macOS/docker FROM: openswoole/swoole:4.10.0-php8.1-alpine
- Browser type and version: latest chrome

### Description:
The field help text https://nova.laravel.com/docs/3.0/resources/fields.html#field-help-text is not showing anymore in any of my fields. 

### Detailed steps to reproduce the issue on a fresh Nova installation:

Put a `->help('text here')` on a Nova field and see if it appears on forms.

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/159102291-cc9d6e65-b3f2-4f93-bc64-e4cd983c6c18.png)

Unable to reproduce the issue, please provide more detail or reproducing code.

**Comment by ibrunotome** [comment]
Have you tested with octane/swoole @crynobone?

**Comment by crynobone** [comment]
Are you saying Swoole messing XHR response causing help text not showing while everything else using XHR works fine?

**Comment by ibrunotome** [comment]
Was not saying anything else than "have you tested with octane/swoole?".

I found the error, it was related to a third package (eminiarts/nova-tabs), the help text only appears with the usage of TabsOnEdit trait.

Thanks.
