### ISSUE TITLE
Inline creation support for other relations

### ISSUE THREAD

**Issue by marvin-wtt** [laravel/nova-issues#3785]
According to the nova [docs](https://nova.laravel.com/docs/3.0/resources/relationships.html#creating-inline-relations), inline-creation is only possible for `BelongsTo` and `MorphTo`. However, it is also handy for other relations like `HasMany`.
So far, I don't see a proper way how to achieve this.

For model creation, my idea would be to create the inline-creations in a transaction after the parent model is created so that the child model knows the parent model's ID. Updating shouldn't be a problem.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
