### ISSUE TITLE
Datatime::make() can't cast to database's datatime field

### ISSUE THREAD

**Issue by chinkiver** [laravel/nova-issues#379]
1. Database
I hava a database table named 'start', it's a DATETIME field, and the migration code is
`$table->dateTime('start')->comment('the service's start time')->nullable();`

2.Nova project
`use Laravel\Nova\Fields\Date;`
`Date::make('Star Date', 'start'),`

When I open the 'Service' page, I got a error is `Date field must cast to 'date' in Eloquent model.`
But the `created_at` field is OK!

**Comment by vootrunner** [comment]
Add 

````
    protected $casts = [
				'start' ⇒ 'datetime',
		];
````

To your laravel Model.

See [Attribute Casting](https://laravel.com/docs/5.6/eloquent-mutators#attribute-casting)

**Comment by chinkiver** [comment]
Thanks, it's ok

**Comment by davidhemphill** [comment]
Looks like this is fixed, so closing.
