### ISSUE TITLE
orderBy & orderByDirection is not sent to action handle model

### ISSUE THREAD

**Issue by smartameer** [laravel/nova-issues#3790]
- Laravel Version: 8.x
- Nova Version: 3.31
- PHP Version: 8.1
- Database Driver & Version: Mysql
- Operating System and Version: *
- Browser type and version: *

### Description:

`orderBy` & `orderByDirection` is not sent to actions, whereAs filters are being sent.
Actions handle's model is very raw version where the sorting is not set.
I have `ID::make('ID')->sortable()` which upon selection and action the `model for handle function` gives always ascending order list.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
Introducing such features would automatically create a slow performance issue for everyone processing action on large resources (depending on how the database was setup/indexed) and I don't think it's wise to have this impact on all ongoing Nova applications.
