### ISSUE TITLE
The actions method is run once for each resource on an index page, despite only being needed once in total

### ISSUE THREAD

**Issue by Ahmed-Ashraf-eng** [laravel/nova-issues#3791]
**1. Laravel Version: 7.0	 
2. Nova Version:  3.27.0	
3.  PHP Version: 7.2.5  	
4. Database Driver : MySQL**

**Description:**
At the moment it appears that the actions method of a resource is run once on a listing, and again for each resource in that listing (i.e. 1 + 25 on a standard Nova resource response), leading to poor performance and frequently duplicated queries, etc, despite only needing to be run once.

![nova actions issue](https://user-images.githubusercontent.com/71425935/160276518-0553c809-c551-4153-8420-71496896764a.png)

**Comment by crynobone** [comment]
That is expected when you have the ability to use to show on the index (listing), inline (table row) with multiple combinations, and each has its own `canSee()` requirement. The actions available on the listing and each resource table row will not always contain the same actions.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
