### ISSUE TITLE
Change event is not being emitted when the Select field is searchable

### ISSUE THREAD

**Issue by andrefedalto** [laravel/nova-issues#3797]
- Laravel Version: 8.83.6
- Nova Version: 3.31.0
- PHP Version: 8.0.13
- Database Driver & Version: Postgres 13
- Operating System and Version: Windows 10
- Browser type and version: Chrome 99.0.4844.82

### Description:
The event `this.field.attribute + '-change'` is not being emitted when the Select field is `->searchable()`.

This issue has already been reported here https://github.com/laravel/nova-issues/issues/3569 but was closed. I'm reopening it and explaining why I believe it is a bug.

I ran across this issue while creating a new custom field that listens for other field changes and acts upon them. All of the Nova fields emit the change event, except the Select field when, and only when, the `->searchable()` option is set. I believe that setting a "flag" (searchable) in a field should not affect the change event. I tested several other fields with existing flags and was not able to find the same behavior, only in the searchable select field. 

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Open any given resource and add a select field
```
            Select::make('Test')
                ->options([
                    1 => 'Option 1',
                    2 => 'Option 2',
                ]),
```

2. Create a new MyCustomField following the instructions here https://nova.laravel.com/docs/3.0/customization/fields.html
3. Add the following code to the `FormField.vue` of your new field
```
  mounted() {
    Nova.$on('test-change', value => {
      console.log(value);
    })
  },
```

4. Add your new field to the same resource used on step 1:
```
            MyCustomField::make('Custom Field'),
```

5. Open the update screen of your resource and select any value of the Test select;
6. Notice that the value is logged to the console;
7. Now add `->searchable()` to your Test select, refresh the screen and select any value of the Test select;
8. Notice that nothing was logged to the console.

**Comment by davidhemphill** [comment]
Thanks for reporting!
