### ISSUE TITLE
DateTime field in action form

### ISSUE THREAD

**Issue by sdapkus** [laravel/nova-issues#3799]
- Laravel Version: 9.6
- Nova Version: 3.31
- PHP Version: 8.0.14
- Database Driver & Version:
- Operating System and Version: Mac 12.2.1
- Browser type and version: Chome Version 99.0.4844.84
- Reproduction Repository: https://github.com/###/###

### Description:
DateTime field inside action modal closes, when trying adjust time. Date selection works fine, but as soon as clicked on time - date time modal and action modal closes.

This was not happening on 3.26.1
I've tracked down issue to `components/Modals/ConfirmActionModal.vue` newly created events `datepicker-opened` and `datepicker-closed` are never triggered, if I rollback this file to 3.26.1 everything is working.

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Create action
2. Inside `fields()` add add DateTime field
3. From nova open that action and try adjusting time.
4. Action modal closes.

**Comment by crynobone** [comment]
Are you using Nova's Date or DateTime field or are you using 3rd party field?

**Comment by sdapkus** [comment]
DateTime

`use Laravel\Nova\Fields\DateTime;`

**Comment by crynobone** [comment]
Please submit reproducing code or make changes to https://github.com/nova-issues/issue-3778/commit/493f9b7b3fb107f5eed16dc6c9207c64eb9efd0a to reproduce the issue.

**Comment by sdapkus** [comment]
It just started to be more complex 😅

I've tried on repository that you provided copy & paste my code, it worked perfectly!
Doing `php artisan nova:publish` all files are already same, so I suspect, that nova versions are the same.
Tried creating sample new resource & action on my project and it does not work...

Not sure what extra info I can give to you.

**Comment by crynobone** [comment]
I suspect there might be a custom package overriding the default DateTime field, you can start looking at `composer.json` require and `nova-components` to see if anything related to date/datetime field.

**Comment by sdapkus** [comment]
Good catch!
It was actually another package that was causing problems, and we were actually not even using it 🙈
Removed it and everything started to work.

Thanks for your help!
