### ISSUE TITLE
ID::make() should use model's primary key

### ISSUE THREAD

**Issue by rcknr** [laravel/nova-issues#38]
`ID::make()` assumes that primary key is `id` which often isn't the case. Why not default to `Model::getModel()->getKeyName()` instead?

**Comment by MattMangoni** [comment]
I wouldn't say 'often', but yeah, this is something to take into account :)

**Comment by devmsh** [comment]
What version you use?

```
public static function forModel($model)
    {
        return tap(static::make('ID', $model->getKeyName()))->resolve($model);
    }
```

ID currently use `getKeyName` as you mention

**Comment by davidhemphill** [comment]
As @devmsh posted, the ID field uses the value from getKeyName().

**Comment by rcknr** [comment]
I'm using the latest version and ID field doesn't work for me automatically when . There's nothing in the ID column and sorting fails too:
```
Unknown column 'id' in order clause
```
