### ISSUE TITLE
Bug with hosting Nova v4 at the root of the application

### ISSUE THREAD

**Issue by Bradez** [laravel/nova-issues#3811]
- Laravel Version: 9.6.0
- Nova Version: 4.0.0
- PHP Version: 8.1.3

### Description:
If you're looking to host Nova v4 at the root of the application (such as `https://localhost`), there is currently a bug with Nova v4 that results in broken links.

For example, instead of appearing as `https://localhost/resources/users/1/edit`, they may appear as either `https://localhost/users/1/edit` (missing the `/resources/` prefix on the path) and in other instances `https://resources/users/1/replicate` (likely due to suffixing `/` to the end of `nova.path` causing `//` to occur on the frontend).

This occurs when setting the `nova.path` config path to `/`. There is a temporary workaround which is to set it to an empty string. 

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Change the `nova.path` config value to `/`;
- Navigate to Nova panel (ex. `https://localhost/resources/users`) you'll notice that resources start to link to broken destinations.

**Comment by lukevmk** [comment]
even the login is broken if the `nova.path` is set to `/`

**Comment by pramanikriju** [comment]
+1
This issue is also caused by having any  `/` based path in the config file. 
For example, I set `'path' => 'admin/nova',` and it breaks all the URLs as well, ending up with repeated strings like -
`https://domain/admin/nova/dashboards/admin/nova/resources/users`

**Comment by pramanikriju** [comment]
@crynobone Do you want a repo to replicate this issue?
