### ISSUE TITLE
Bug with setting URL display value

### ISSUE THREAD

**Issue by Bradez** [laravel/nova-issues#3816]
- Laravel Version: 9.6.0
- Nova Version: 4.0.0
- PHP Version: 8.1.3

### Description:
If you follow the [instructions in the documentation](https://nova.laravel.com/docs/4.0/resources/fields.html#url-field) for creating a URL field, the default value for that field is the name of the field itself. Personally, I think the display text should default to the URL value set itself and then allow the end-user to simplify it as demonstrated in the section section of the URL Field documentation.

However, irrespective of that opinion, if you decide to proceed with using `displayUsing(fn () => 'Friendly Display Name')` on the field as indicated in the documentation, it will result in `displayedAs` being successfully set to `Friendly Display Name` although `value` is never set. This means that, because there is no value set (the underlying URL itself), the frontend simply renders it as `—` and with no link.

Adding `parent::resolve($resource, $attribute);` above where `$this->displayedAs` gets set in `resolveForDisplay` on the `URL` field appears to resolve the issue as that results in `$this->value` being set properly.

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Add a new column to the `User` model, such as `website`;
2. Register the new column in the `User` resource and give it a friendly display name: `URL::make('Website')->displayUsing(fn () => 'User Website')`
3. Set the value for `website` for the Resource.
4. Check the Resource details page to see it rendered as `—`.
5. Confirm that disabling `displayUsing(...)` results in the URL working again.

**Comment by MouadZIANI** [comment]
Any updates on this issue ?, it doesn't show the value of the URL field even I tried to use `displayUsing(...)`

**Comment by MouadZIANI** [comment]
Upgrade to v4.1 will fix the issue
