### ISSUE TITLE
KeyValue Field Cannot Depend on Other Field

### ISSUE THREAD

**Issue by aaronwjm360** [laravel/nova-issues#3817]
- Laravel Version: 8.0
- Nova Version: 4.0
- PHP Version: 8.1
- Database Driver & Version: 8.0
- Operating System and Version: Ubuntu (Bullseye)
- Browser type and version: Mozilla Firefox (Latest)
- Reproduction Repository: Latest?

### Description:
I am trying to get a KeyValue field to depend on a Select field. Please see image for code example:
![image](https://user-images.githubusercontent.com/12497992/161814137-939cd790-6bdd-429c-a3d4-c3a02082c60a.png)

This is apparently possible as per documentation. I am **not** depending on the KeyValue field, this is depending on something else.

When I try to load the resource creation page, i get this error:
![image](https://user-images.githubusercontent.com/12497992/161814369-06b8e0ea-b0f0-454c-a7bc-8ac0ebb4c123.png)

It would seem to suggest its not possible?
![image](https://user-images.githubusercontent.com/12497992/161814716-f8228c23-c638-45a8-967e-a60b9b0305a2.png)

Just to give more detail on what I am trying to do - I have a resource which defines a "template" for what you could say is a support ticket, So this ticket would have different questions and I want to be able to set a templated drop down list of preset options which would be saved in an array. But - for ease of use/more intuitive UI, I'd like to make the KeyValue field hidden (preferably) or read only or something if it is not required (such would be the case for a text field - where there are no preset options to provide. Here is an example:
![image](https://user-images.githubusercontent.com/12497992/161816535-8df8dad0-42d0-486b-9c28-d049703b5eee.png)

### Detailed steps to reproduce the issue on a fresh Nova installation:
Please see above.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by aaronwjm360** [comment]
@davidhemphill If I am unable to do something as described in the documentation itself, then surely this is a bug not a feature request?

**Comment by aaronwjm360** [comment]
@crynobone I've got a fix for you. vendor\laravel\nova\src\Fields\KeyValue.php - I have added the SupportsDependentFields trait into this class and now it works perfectly, I haven't done any testing to see if this breaks anything else, but it fixes the bug for sure.
