### ISSUE TITLE
The search field in the documentation is not working

### ISSUE THREAD

**Issue by stonkeep** [laravel/nova-issues#3819]
- Laravel Version: 9.7.0
- Nova Version: 4.0.0
- PHP Version: 8.1

Good morning, when trying to do the search in the documentation, no result is presented

![Screenshot 2022-04-05 162455](https://user-images.githubusercontent.com/3990028/161833797-7d73d13a-a215-4acd-b969-594803305542.png)

**Comment by crynobone** [comment]
Algolia requires up to 24 hours to crawl the new documentation.
