### ISSUE TITLE
License file?

### ISSUE THREAD

**Issue by balping** [laravel/nova-issues#382]
Can someone post the contents of the LICENSE file? It would be important for me before buying to know what I can and cannot do with the software. Can I modify the code for example? Even if I have access to the source (this is in the nature of PHP), modifying source can be prohibited by a license.

It's stated here https://github.com/laravel/nova-issues/issues/233#issuecomment-416217704 that in the composer repo it is marked "MIT", but as I understand, this isn't really the case.

**Comment by BrekiTomasson** [comment]
I believe this is the section you're looking for:

> You may alter, modify, or extend the Software for your own use, or commission a third-party to perform modifications for you, but you may not resell, redistribute or transfer the modified or derivative version without prior written consent from Laravel LLC. Components from the Software may not be extracted and used in other programs without prior written consent from Laravel LLC.

**Comment by balping** [comment]
Thanks.
