### ISSUE TITLE
Brand logo not working

### ISSUE THREAD

**Issue by stonkeep** [laravel/nova-issues#3824]
- Laravel Version: 9.7
- Nova Version: 4.0.0
- PHP Version: 8.1

Bug in changing the logo, if I try to put a logo.svg it gives the following error in the console
```
VM1211:1 Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at <anonymous>:1:5031
    at <anonymous>:1:5123
```
A blank screen appears when I put any logo.jpg or logo.png

**Comment by Bradez** [comment]
I've not had anyissue with setting and using `nova.brand.logo` in our fresh installation or upgrades, barring a slight adjustment in the sizing.

Are you able to post the exact contents of the `.svg` file you're referencing?

**Comment by stonkeep** [comment]
my config is like 

```
 'brand' => [
         'logo' => realpath(__DIR__.'/../public/img/logo.png'),

//         'colors' => [
//             "400" => "24, 182, 155, 0.5",
//             "500" => "24, 182, 155",
//             "600" => "24, 182, 155, 0.75",
//         ]
     ],
```

and I got the error in console
![image](https://user-images.githubusercontent.com/3990028/161996579-302564fc-3332-4d5c-9da2-8fbd574c839f.png)

and in the source is like

![image](https://user-images.githubusercontent.com/3990028/161996681-28f0a00e-5e78-4769-b46d-704d5352d860.png)

**Comment by bashgeek** [comment]
@stonkeep I think the logo only works with SVG files, not with PNGs, because it needs the inline SVG code.

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/162001021-d21cca7a-8734-49a7-8683-af55c7e8c0d9.png)
