### ISSUE TITLE
Nova 4: Field help() method does not accept HTML

### ISSUE THREAD

**Issue by TiiFuchs** [laravel/nova-issues#3825]
With Nova 4.0 the help() method does not accept HTML. But the documentation explains it should be possible. 

The HTML is visible as is in Nova and does not get parsed by the browser. 

https://nova.laravel.com/docs/4.0/resources/fields.html#field-help-text

**Comment by crynobone** [comment]
Fixed in `4.0.5`

**Comment by TiiFuchs** [comment]
Does not seem to work with 4.0.5:

![CleanShot 2022-04-07 at 15 03 17](https://user-images.githubusercontent.com/1958744/162205099-7ca21491-57da-4ef2-bed6-8ab49e12f32f.png)
