### ISSUE TITLE
Feature Request: Nova Cards Width '2/3' to be added back in Nova 4

### ISSUE THREAD

**Issue by RhysLees** [laravel/nova-issues#3826]
In Nova 3 I was able to create cards that were TWO_THIRDS_WIDTH but it seems they have been removed. looking into the card class I can only see the following:

```php
public const FULL_WIDTH = 'full';
public const ONE_THIRD_WIDTH = '1/3';
public const ONE_HALF_WIDTH = '1/2';
```

It would be nice to have back, especially for the Trend Metrics as you don't always need a Full row for it

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by dwightwatson** [comment]
Opened a bug report for this without realising this was already here (#3828).

[The 4.0 documentation still refers to the 2/3 size](https://nova.laravel.com/docs/4.0/metrics/registering-metrics.html#metric-sizes) so this does seem like a bug.

Alternatively, the upgrade guide should mention this and the docs referencing other sizing should be updated.
