### ISSUE TITLE
Nova 4: JsonResource configuration affects root application

### ISSUE THREAD

**Issue by dwightwatson** [laravel/nova-issues#3829]
- Laravel Version: 9.7.0
- Nova Version: 4.0.0
- PHP Version: 8.1.4
- Database Driver & Version:

### Description:

It appears that `NovaCoreServiceProvider` makes a call to `JsonResource::withoutWrapping()` to remove the root `data` attribute from JSON responses. However, this change appears to affect the root application as well. I have a number of APIs that depend upon that `data` attribute (in that I **haven't** used `withoutWrapping`) and now those tests are failing.

### Detailed steps to reproduce the issue on a fresh Nova installation:

In a fresh Laravel installation, create an endpoint that returns a JSON response using a resource:

```php
public function show(User $user)
{
    return new UserResource($user);
}
```

Check that when hitting that endpoint the data returned is nested under a `data` attribute.

Then, install Nova 4 and check that endpoint again. The `data` attribute has disappeared.

**Comment by davidhemphill** [comment]
This has been fixed and a new release has been pushed. 👍

**Comment by bashgeek** [comment]
> This has been fixed and a new release has been pushed. 👍

4.0.1 doesn't show up in composer yet :-(

**Comment by crynobone** [comment]
@Paulsky are you on Octane?

**Comment by Paulsky** [comment]
@crynobone No, I'm not on Octane!

**Comment by crynobone** [comment]
Then your issue is something else, can you submit a reproducing code on a new issue?

**Comment by Paulsky** [comment]
My apologies, I will create a new issue.
