### ISSUE TITLE
Nova 4: DateTime Field: Hide timezone

### ISSUE THREAD

**Issue by Muetze42** [laravel/nova-issues#3834]
A option to hide the timezone in DateTime fields would be nice.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by elizdlt202** [comment]
Can we reopen this?
