### ISSUE TITLE
FEATURE: Redirection Path on Impersonation

### ISSUE THREAD

**Issue by bsormagec** [laravel/nova-issues#3839]
Hey, 
When we are impersonating nova it redirects the main URL of the project. I think it needs to be configurable from User Model or somewhere from the config.

Thanks.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
