### ISSUE TITLE
Compiling Nova Components JS / NPM Dependencies on Forge

### ISSUE THREAD

**Issue by noahlocke** [laravel/nova-issues#384]
Running `npm install` on a component fails:

The `/home/forge/.../nova-components/Trumbo/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✔ pngquant pre-build test passed successfully
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed

**Comment by devmsh** [comment]
Why you need to run npm in your server? just run `npm run prod` and remove the `dist` folder from the `.gitignore` file (don't know why it's ignored by default!) while all field packages remove and publish it with the packages!

**Comment by noahlocke** [comment]
Duh. Thanks @devmsh

**Comment by nickels** [comment]
@noahlocke running `sudo apt-get install libpng-dev` would solve that error.
