### ISSUE TITLE
Nova 4 docs: isImpersonating()

### ISSUE THREAD

**Issue by schonhoff** [laravel/nova-issues#3840]
- Laravel Version: 8.83.7
- Nova Version: 4.0
- PHP Version: 8.0
- Database Driver & Version: MySQL 8
- Operating System and Version: Windows 10
- Browser type and version: Chrome 100

### Description:
I was trying around with the new impersonate functionality. After searching through the docs how I can stop my impersonating I found the following in the docs:
https://nova.laravel.com/docs/4.0/customization/menus.html#customizing-the-user-menu

There was a function `isImpersonating()` mentioned. I installed a route like it is mentioned in the docs:
https://nova.laravel.com/docs/4.0/customization/impersonation.html#inspecting-impersonation-state
But my site throws a 500 error after using the code from the customizing the user menu docs because there is no function `isImpersonating()` available on the `Illuminate\Http\Request`. Is there something I missed?

### Detailed steps to reproduce the issue on a fresh Nova installation:
See above.

**Comment by RhysLees** [comment]
Just run into the same thing, Put the menu into the boot method and got a 500 error.

```php
 Nova::userMenu(function (Request $request, Menu $menu) {
            if ($request->user()->isImpersonating()) {
                $menu->append(
                    MenuItem::make('Stop Impersonating')
                        ->path('/impersonate/stop')
                );
            }

            $menu->prepend(
                MenuItem::make(
                    'My Profile',
                    "/resources/user/{$request->user()->getKey()}"
                )
            );

            return $menu;
        });
```
Above throws 500

**Comment by schonhoff** [comment]
Thanks for the fast answer. Is there a way to see from the request if the user is impersonated or is it just possible with `session()->exists('nova_impersonated_by')` in the frontend? Not every user in our Laravel app has backend access.

**Comment by crynobone** [comment]
```php
use Laravel\Nova\Contracts\ImpersonatesUsers;

app(ImpersonatesUsers::class)->impersonating($request);
```

`$request` can be any instance of `Illuminate\Http\Request`.

**Comment by schonhoff** [comment]
Thanks! Would love to see this in the docs as well :-) But the Nova 4 update is such a nice tool! Great work to the team!

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/161972990-9a5c6d95-e036-4575-b001-3be4e4d95359.png)

I believe this already covers that with just a different usage.
