### ISSUE TITLE
[4.0] JsonResource::withoutWrapping() called globally

### ISSUE THREAD

**Issue by fragkp** [laravel/nova-issues#3842]
- Laravel Version: 9.7.0
- Nova Version: 4.0.1
- PHP Version: 8.1.3
- Database Driver & Version: -
- Operating System and Version: -
- Browser type and version: -
- Reproduction Repository: -

### Description:
`JsonResource::withoutWrapping()` is called globally (NovaCoreServiceProvider) and should only be used inside Nova requests.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Use in your app (not Nova!) a JsonResource. The `data` property is now missing without calling `JsonResource::withoutWrapping()`.

**Comment by anthony-brindley** [comment]
I'm pretty sure there's a new release 4.0.1 which resolves this: https://nova.laravel.com/releases

I have tried updating my version but I don't know if this is available to the public as yet?

**Comment by fragkp** [comment]
@anthony-brindley Sry, you're right.

I'm on 4.0.0 - it seems like the 4.0.1 is currently not available on composer.

>- Root composer.json requires laravel/nova 4.0.1, found laravel/nova[dev-other-shiz-test, dev-reset-focus-to-previous-active-element, dev-join-inline-action-selector-and-table-row-dropdown, dev-composition-exploration, dev-log-viewer, dev-other-shiz, dev-master, dev-fixes-3811, dev-fixes-3814, dev-fixes-3816, dev-fixes-3817, dev-fixes-3825, dev-develop, dev-authorize-method-usage-improvements, v1.0.18, ..., v1.3.2, v2.0.0, ..., v2.12.0, v3.0.0, ..., 3.x-dev (alias of dev-master), 4.0.0, 4.0.x-dev] but it does not match the constraint.

**Comment by crynobone** [comment]
Please wait for `4.0.2`, there an issue with the last tagged making it invisible for everyone.

**Comment by fragkp** [comment]
Resolved with `4.0.2`
