### ISSUE TITLE
Relationship displayable name throwing exceptions.

### ISSUE THREAD

**Issue by Alymosul** [laravel/nova-issues#385]
I have a Post resource, inside the fields() I put the following: `BelongsTo::make('Author', 'user'),`.
However, it throws the following error **Class \App\Nova\Author not found**. Any ideas why is that happening?

**Comment by devmsh** [comment]
```
BelongsTo::make("{Label}", "{RelationMethod}","{ResourceClass}"),
```

e.g.

```
BelongsTo::make('First Team', 'firstTeam', Team::class)->searchable(),
```

First team is the label I want to display, firstTeam is the relation method name, and Team::class refer to the Team Resource (not Team model).

**Comment by Alymosul** [comment]
Thank you!

**Comment by stonkeep** [comment]
Thank you. Helped me a lot
