### ISSUE TITLE
Reset password form is not working

### ISSUE THREAD

**Issue by stonkeep** [laravel/nova-issues#3850]
- Laravel Version: 9.7
- Nova Version: 4.0.3
- PHP Version: 8.1

### Description:
after asking to reset the password I get the following link

`http://localhost/nova/password/reset/f18e32036c304f5927a8e220bb923bcb0e2607930b794470f7ed7ea650d909a9
` 
I fill in the fields and click on reset password, but it's sending the email again with a link to reset the password and it's not keeping the user's password
![image](https://user-images.githubusercontent.com/3990028/162017231-f20b6d37-cad8-4669-ad29-cc55b85eef67.png)

**Comment by stonkeep** [comment]
I think that is because of that 
ResetPassword.vue
```
methods: {
    async attempt() {
      const { message } = await this.form.post(Nova.url('/password/email'))
      Nova.success(message)
      Cookies.set('token', Math.random().toString(36), { expires: 365 })

      Nova.visit('/')
    },
  },
```

ForgotPassword.vue
```
methods: {
    async attempt() {
      const { message } = await this.form.post(
        `${Nova.config('base')}/password/email`
      )
      Nova.success(message)
      Nova.redirectToLogin()
    },
  },
```
both send to same link?

**Comment by crynobone** [comment]
PR merged pending next release.
