### ISSUE TITLE
Nova 4 Installed --> View [app] not found

### ISSUE THREAD

**Issue by cboudreaux** [laravel/nova-issues#3851]
View [app] not found. {"userId":7,"exception":"[object] (InvalidArgumentException(code: 0): View [app] not found. at /Users/cajunmba/LaravelProjects/signs/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137)
[stacktrace]
#0 /Users/cajunmba/LaravelProjects/signs/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\\View\\FileViewFinder->findInPaths('app', Array)
#1 /Users/cajunmba/LaravelProjects/signs/vendor/laravel/framework/src/Illuminate/View/Factory.php(138): Illuminate\\View\\FileViewFinder->find('app')
#2 /Users/cajunmba/LaravelProjects/signs/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(85): Illuminate\\View\\Factory->make('app', Array)
#3 /Users/cajunmba/LaravelProjects/signs/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Routing\\ResponseFactory->view('app', Array)
#4 /Users/cajunmba/LaravelProjects/signs/vendor/inertiajs/inertia-laravel/src/Response.php(113): Illuminate\\Support\\Facades\\Facade::__callStatic('view', Array)
#5 /Users/cajunmba/LaravelProjects/signs/vendor/laravel/nova/src/Exceptions/NovaExceptionHandler.php(88): Inertia\\Response->toResponse(Object(Illuminate\\Http\\Request))
#6 /Users/cajunmba/LaravelProjects/signs/vendor/laravel/nova/src/Exceptions/NovaExceptionHandler.php(68): Laravel\\Nova\\Exceptions\\NovaExceptionHandler->renderInertiaException(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))
#7 /Users/cajunmba/LaravelProjects/signs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(51): Laravel\\Nova\\Exceptions\\NovaExceptionHandler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))
#8 /Users/cajunmba/LaravelProjects/signs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(172): Illuminate\\Routing\\Pipeline->handleException(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))
#9 /Users/cajunmba/LaravelProjects/signs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#10 /Users/cajunmba/LaravelProjects/signs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#11 /Users/cajunmba/LaravelProjects/signs/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#12 /Users/cajunmba/LaravelProjects/signs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#13 /Users/cajunmba/LaravelProjects/signs/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 /Users/cajunmba/LaravelProjects/signs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 /Users/cajunmba/LaravelProjects/signs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 /Users/cajunmba/LaravelProjects/signs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#17 /Users/cajunmba/LaravelProjects/signs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#18 /Users/cajunmba/LaravelProjects/signs/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#19 /Users/cajunmba/.composer/vendor/laravel/valet/server.php(219): require('/Users/cajunmba...')
#20 {main}
"}

**Comment by rvslan** [comment]
Fixed this by launching: php artisan nova:install

**Comment by cboudreaux** [comment]
@crynobone That did not solve the problem.

**Comment by crynobone** [comment]
@cboudreaux Submit new issue with bug report template, indicate where you installing fresh Nova 4 or upgrading from Nova 3: https://github.com/laravel/nova-issues/issues/new?assignees=&labels=&template=1_Bug_report.md

**Comment by dwightwatson** [comment]
@cboudreaux I had a similar issue after shipping Nova 4 to production - it only seemed to occur on what are Livewire endpoints. Are you using Livewire also by any chance?

It looks like the NovaExceptionHandler is trying to return an Inertia response for errors that occur in the main app.

**Comment by cboudreaux** [comment]
@dwightwatson No Livewire here.   : ) I reverted to v3 for now, and will revisit v4 in a few months.  I appreciate you looking into it.

**Comment by crynobone** [comment]
@NEKKA-Rabah please submit new bug report will more details as suggested above.
