### ISSUE TITLE
Multiselect with depend on

### ISSUE THREAD

**Issue by stonkeep** [laravel/nova-issues#3854]
- Laravel Version: 9.7
- Nova Version: 4.0.3
- PHP Version: 8.1

### Description:
Multiselect field content not updating with depedOn option
follow the example below

```
 MultiSelect::make('Cidades')
                ->dependsOn(
                    ['uf'],
                    function (MultiSelect $field, NovaRequest $request, FormData $formData) {
                        $cities = BuscaCidadesIBGE::run($formData?->uf);
                        $field->options($cities);
                    }
                ),
```

**Comment by crynobone** [comment]
PR submitted and pending review

https://user-images.githubusercontent.com/172966/162101675-f081b140-be1e-4f5d-9a8e-84437deb9269.mp4
