### ISSUE TITLE
Building Custom Field Assets is failing

### ISSUE THREAD

**Issue by Jubeki** [laravel/nova-issues#3856]
- Laravel Version: 9.7.0
- Nova Version: 4.0.5

### Description:

It seems like it is not possible to create custom fields out of the box because of missing dependencies among npm.
It resolves itself if the dependencies are installed manually, but this should probably happen out of the box with the default options.

Here the error that occurs after creating a custom field and building the assets:
<img width="1263" alt="Screenshot 2022-04-06 at 21 35 16" src="https://user-images.githubusercontent.com/15707543/162055988-65dc33d3-d00c-4e11-b2a5-285563d2d131.png">

### Detailed steps to reproduce the issue on a fresh Nova installation:
```
php artisan nova:field example/example-field
```
And then always select the default options.

**Comment by Jubeki** [comment]
I know there was already an open issue and an open discussion, but since the default installation is failing, I thought it would be better to report it again, because it should probably not be resolved with entering `laravel/nova` and running `npm install`

Issue: https://github.com/laravel/nova-issues/issues/3813
Discussion: https://github.com/laravel/nova-issues/discussions/3814

**Comment by crynobone** [comment]
>  because it should probably not be resolved with entering `laravel/nova` and running `npm install`

At the moment that the only solution to the problem, will investigate further but it's not an easy fix.

**Comment by thelevicole** [comment]
I'm having the same issue, have installed the Laravel Nova `node_modules` which compiled with no errors however, when the assets are called in the browsers I get the below in the console:

> Uncaught (in promise) TypeError: _vm._self is undefined

[Imgur](https://imgur.com/meBVNwj)

This is on a fresh Nova 4 install and an untouched custom field created with `php artisan nova:field`
