### ISSUE TITLE
After executing of the php artisan nova:resource the admin area is gone

### ISSUE THREAD

**Issue by viterzbayraku** [laravel/nova-issues#3859]
- Laravel Version: 9.7.0
- Nova Version: 4.0.5
- PHP Version: 8.1
- Database Driver & Version: mysql
- Operating System and Version: mac os catalina
- Browser type and version: google chrome 99.0.48

### Description:

After executing of the `php artisan nova:resource Mayster` command the admin area is gone.
The version of Nova is latest.

```
GET https://rukotv.test/adminka/dashboards/main 500
app.js?id=078e27ab5ab9cf445c89:1 [NOVA] Initiating Nova countdown...
app.js?id=078e27ab5ab9cf445c89:1 [NOVA] We have lift off!
app.js?id=078e27ab5ab9cf445c89:1 Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')
    at ir.registerStoreModules (app.js?id=078e27ab5ab9cf445c89:1:67076)
    at ir.liftOff (app.js?id=078e27ab5ab9cf445c89:1:64394)
    at main:41:14
```

**Comment by crynobone** [comment]
New Laravel Nova 4 or upgrade from Nova 3?

**Comment by viterzbayraku** [comment]
> New Laravel Nova 4 or upgrade from Nova 3?

the new

**Comment by crynobone** [comment]
Can you share the content of `Mayster` resource file?

**Comment by viterzbayraku** [comment]
> Can you share the content of `Mayster` resource file?

``
<?php

namespace App\Nova;

use Illuminate\Http\Request;
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Http\Requests\NovaRequest;

class Mayster extends Resource
{
    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static $model = \App\Models\Mayster::class;

    /**
     * The single value that should be used to represent the resource when being displayed.
     *
     * @var string
     */
    public static $title = 'id';

    /**
     * The columns that should be searched.
     *
     * @var array
     */
    public static $search = [
        'id',
    ];

    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @return array
     */
    public function fields(NovaRequest $request)
    {
        return [
            ID::make()->sortable(),
        ];
    }

    /**
     * Get the cards available for the request.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @return array
     */
    public function cards(NovaRequest $request)
    {
        return [];
    }

    /**
     * Get the filters available for the resource.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @return array
     */
    public function filters(NovaRequest $request)
    {
        return [];
    }

    /**
     * Get the lenses available for the resource.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @return array
     */
    public function lenses(NovaRequest $request)
    {
        return [];
    }

    /**
     * Get the actions available for the resource.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @return array
     */
    public function actions(NovaRequest $request)
    {
        return [];
    }
}

``

**Comment by viterzbayraku** [comment]
> Can you share the content of `Mayster` resource file?

```
<?php

namespace App\Nova;

use Illuminate\Http\Request;
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Http\Requests\NovaRequest;

class Mayster extends Resource
{
    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static $model = \App\Models\Mayster::class;

    /**
     * The single value that should be used to represent the resource when being displayed.
     *
     * @var string
     */
    public static $title = 'id';

    /**
     * The columns that should be searched.
     *
     * @var array
     */
    public static $search = [
        'id',
    ];

    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @return array
     */
    public function fields(NovaRequest $request)
    {
        return [
            ID::make()->sortable(),
        ];
    }

    /**
     * Get the cards available for the request.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @return array
     */
    public function cards(NovaRequest $request)
    {
        return [];
    }

    /**
     * Get the filters available for the resource.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @return array
     */
    public function filters(NovaRequest $request)
    {
        return [];
    }

    /**
     * Get the lenses available for the resource.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @return array
     */
    public function lenses(NovaRequest $request)
    {
        return [];
    }

    /**
     * Get the actions available for the resource.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @return array
     */
    public function actions(NovaRequest $request)
    {
        return [];
    }
}

```

**Comment by viterzbayraku** [comment]
`[2022-04-06 22:57:20] local.ERROR: Class "App\Models\Mayster" not found {"userId":1,"exception":"[object] (Error(code: 0): Class \"App\\Models\\Mayster\" not found at /Users/../../../nova/vendor/laravel/nova/src/Resource.php:398)`

**Comment by crynobone** [comment]
Do you actually have the model?

**Comment by viterzbayraku** [comment]
> Do you actually have the model?

No. I will create it manually?

**Comment by crynobone** [comment]
Yes.

**Comment by viterzbayraku** [comment]
Thank you. And one additional question. Sorry for my newbie knowledge. How I can correctly create table in database for this Resource?

**Comment by viterzbayraku** [comment]
Thank you. You can close this topic.
