### ISSUE TITLE
Nova 4: Unable to remove Laravel Nova Branding

### ISSUE THREAD

**Issue by martianatwork** [laravel/nova-issues#3860]
- Laravel Version: 8
- Nova Version: 4.0.5
- PHP Version: 7.4.21

### Description:
Unable to remove footer branding of Nova.

```
Powered by [Laravel Nova](https://nova.laravel.com/) · v4.0.5 (Silver Surfer).
© 2022 Laravel LLC · by Taylor Otwell and David Hemphill
```

Previously it was easy to do it we just had to replace the blade files, now it looks like it is hardcoded in the Vue code

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
