### ISSUE TITLE
Notifications Sidebar Border Dark Mode

### ISSUE THREAD

**Issue by jjjrmy** [laravel/nova-issues#3862]
- Nova Version: 4.0.5

This is a small issue, but on the notifications sidebar, the border is the wrong color on dark mode.

I'm guessing it should be `border-gray-200 dark:border-gray-700`
The latter part is missing so it has a light border on the bottom.

**Comment by crynobone** [comment]
Please provide screenshot

**Comment by jjjrmy** [comment]
<img width="351" alt="Screen Shot 2022-04-06 at 18 33 41" src="https://user-images.githubusercontent.com/1609800/162083427-23f94b65-e2ac-43b1-a3fd-d770e7cf6cfc.png">
<img width="332" alt="Screen Shot 2022-04-06 at 18 34 36" src="https://user-images.githubusercontent.com/1609800/162083530-f5c91300-423a-4d83-a232-f4cb9dc97cc2.png">
Look at the screenshot and the code...
