### ISSUE TITLE
"Your session has expired" on Logout

### ISSUE THREAD

**Issue by jjjrmy** [laravel/nova-issues#3864]
- Laravel Version: 9.7.0
- Nova Version: 4.0.5
- PHP Version: 8.0.2
- Database Driver & Version: Custom Database Driver
- Reproduction Repository: https://github.com/jjjrmy/nova-broken-sessions

### Description:
<img width="669" alt="Screen Shot 2022-04-06 at 18 49 32" src="https://user-images.githubusercontent.com/1609800/162085378-95c339df-7cef-41c4-babe-70d745b6b19c.png">
Seems the nova-api routes are losing session state and regenerating new sessions constantly.
This same issue doesn't happen when I do a fresh install on Jetstream with Inertia.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Add the files from the reproduction repository then in your .env `SESSION_DRIVER=model`
When you login and try to log out, it will give this error because the session was changed as a result of the api routes.
<img width="333" alt="Screen Shot 2022-04-06 at 18 53 53" src="https://user-images.githubusercontent.com/1609800/162085894-4513cf5d-46ca-4a44-8f83-e394b62834f3.png">

**Comment by crynobone** [comment]
Submit full reproducing code.

**Comment by jjjrmy** [comment]
> Submit full reproducing code.

Just copy those files into a new installation. You need me to upload all of Laravel and Nova?
No other code is needed to reproduce.

**Comment by cwray-tech** [comment]
Plus one on this issue.
