### ISSUE TITLE
[4.0] Global search alignment thrown off with subtitle

### ISSUE THREAD

**Issue by dwightwatson** [laravel/nova-issues#3866]
- Laravel Version: 9.7.0
- Nova Version: 4.0.5
- PHP Version: 8.1.4

### Description:
 
When using a subtitle on a resource it breaks the alignment of the global search results.

<img width="379" alt="image" src="https://user-images.githubusercontent.com/1100408/162090713-9beb9e20-a12d-498b-8112-649728da9783.png">

You'd expect "Dwight Watson" to be left-aligned with the email address.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Add a subtitle to your user resource and then search for it in the global search.

```php
    /**
     * Get the search result subtitle for the resource.
     *
     * @return string
     */
    public function subtitle()
    {
        return $this->email;
    }
```

**Comment by crynobone** [comment]
PR submitted and pending review:

### Before

![image](https://user-images.githubusercontent.com/172966/162096249-d58277b3-8011-45d2-b92a-4406eddf7b36.png)

### After

![image](https://user-images.githubusercontent.com/172966/162096266-1e460a1b-6d29-4dd7-9b0f-7748d03e4121.png)
