### ISSUE TITLE
Customising the places "full" autocompleted/selected address?

### ISSUE THREAD

**Issue by ok200paul** [laravel/nova-issues#387]
I'd like for a place field to be able to populate the full address (as granular as possible, including postcode, state and country) into a single "address" field, not multiple fields. Currently it only populates `suggestion.name`, by the looks.

It'd be great to have a config somewhere that allows users to control what Algolia places fields are populated into the field value object.

v1.0.8 ORION

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
