### ISSUE TITLE
HasOne relationship throws an error on edit screen

### ISSUE THREAD

**Issue by carnevalle** [laravel/nova-issues#3872]
- Laravel Version: 9.7.0
- Nova Version: 4.0.5
- PHP Version: 8.0.5
- Database Driver & Version: Mysql 8.0.25
- Operating System and Version: Ubuntu 20.04.2 LTS
- Browser type and version: Chrome Version 99.0.4844.83 (Official Build) (x86_64)

### Description:
I have User model with 1:1 relationship to a Profile model through the e-mail column. After upgrading from Nova 3 to Nova 4 this relationship no longer works when trying to edit a resource. It works on detail and index screens, but throws these errors on edit.

<img width="502" alt="Screenshot 2022-04-07 at 09 27 28" src="https://user-images.githubusercontent.com/54747/162144922-2d5ded53-87cb-421e-910a-09a53873a71d.png">
<img width="526" alt="Screenshot 2022-04-07 at 09 27 13" src="https://user-images.githubusercontent.com/54747/162145007-215cb4f3-df67-41ba-8d07-4679768bdaf9.png">

I have no idea why this no longer works. This same code was functional in Nova 3. Why is it trying to access the wrong part of the relationship? The User model has a relationship called `profile`, but it tries to access the relationship `user` 

`Call to undefined relationship [user] on model [App\Models\User]`

It looks like this on the detail screen
<img width="847" alt="Screenshot 2022-04-07 at 09 26 40" src="https://user-images.githubusercontent.com/54747/162145121-57ddeaeb-6366-4e5c-adc6-a1b7e1687126.png">
<img width="836" alt="Screenshot 2022-04-07 at 09 27 03" src="https://user-images.githubusercontent.com/54747/162145124-fa87185a-b9cf-4939-b601-33b3ace7046f.png">

The relationship is defined like this in the models
```php
// User Model
public function profile()
{
    return $this->hasOne(Profile::class, 'email', 'email');
}

// Profile model
public function user()
{
    return $this->belongsTo(User::class, 'email', 'email');
}
```

The relationship is setup like this in the Nova Resources
```php

// User resource
return [
    ID::make(),
    Text::make('Email'),
    HasOne::make('Profile'),
];

// Profile resource
return [
    ID::make(),
    Text::make('Email'),
    HasOne::make('User'),
];
```

**Comment by crynobone** [comment]
```php
// Profile resource
return [
    ID::make(),
    Text::make('Email'),
    BelongsTo::make('User'),
];
```
