### ISSUE TITLE
Multiple (Dynamic) Filters on one resource doesn't work as expected

### ISSUE THREAD

**Issue by bdelamatre** [laravel/nova-issues#3879]
- Laravel Version: 9
- Nova Version: 4.0.5
- PHP Version: 8
- Database Driver & Version:
- Operating System and Version: Docker PHP Container
- Browser type and version: Chrome
- Reproduction Repository: https://github.com/###/###

### Description:

If you are using a dynamic filter as defined here https://nova.laravel.com/docs/4.0/filters/defining-filters.html#dynamic-filters and you are using the same dynamic filter multiple times (with unique construct parameters), it appears that all of those dynamic filters use only the first filter's definition in the array.

### Detailed steps to reproduce the issue on a fresh Nova installation:

For example, say that you have built a TeamFilter like so:

```
<?php

namespace App\Nova\Filters;

use App\Models\Team;
use Illuminate\Database\Eloquent\Builder;
use Laravel\Nova\Http\Requests\NovaRequest;
use Laravel\Nova\Filters\Filter;

class TeamFilter extends Filter
{
    /**
     * @var string
     */
    protected string $column;

    /**
     * @var string
     */
    protected string $label;

    /**
     * @param string $column
     * @param string $label
     */
    public function __construct(string $column = 'team_id', string $label = 'Team')
    {
        $this->column = $column;
        $this->label = $label;
    }

    /**
     * @return string
     */
    public function name(): string
    {
        return 'Filter By ' . $this->label;
    }

    /**
     * @param NovaRequest $request
     * @param $query
     * @param $value
     * @return Builder
     */
    public function apply(NovaRequest $request, $query, $value)
    {
        return $query->where($this->column, '=', $value);
    }

    /**
     * @param NovaRequest $request
     * @return array|mixed[]
     */
    public function options(NovaRequest $request)
    {
        return Team::all()->pluck('id', 'name')->toArray();
    }
}
```

Now let's say that you have two fields on your resource, `team_id` and `assigned_team_id`. Both should use the same TeamFilter but with unique dynamic options:

```
    /**
     * @param NovaRequest $request
     * @return array
     */
    public function filters(NovaRequest $request)
    {
        return [
            new TeamFilter('team_id', 'Team'),
            new TeamFilter('assigned_team_id', 'Assigned Team'),
        ];
    }
```

Then when you review your filters, you would see two redundant filters "Filter By Team" and "Filter By Team" instead of two unique filters as "Filter By Team" and "Filter By Assigned Team".

**Comment by crynobone** [comment]
I think you missing `key()` method as described in the documentation.
