### ISSUE TITLE
Make Vue available globally

### ISSUE THREAD

**Issue by cretueusebiu** [laravel/nova-issues#388]
Right now every Nova package must include Vue because it's not available globally.

If `Vue` would be available globally, then you can just use the `externals` option for webpack:

```javascript
mix.webpackConfig({
  externals: {
    vue: 'Vue'
  }
})
```

The same thing should be applied for [nova-js](https://github.com/laravel/nova-js/). Make it available globally in the Nova build, then when a package needs it, it would just specify it in the `externals` option.

This would cut about 85KB (for Vue) + 80KB (for nova-js). And that's just if you install one package.

**Comment by davidhemphill** [comment]
There will likely be no plans to implement this feature.
