### ISSUE TITLE
Mailto link doesn't work on index pages.

### ISSUE THREAD

**Issue by jringeisen** [laravel/nova-issues#3880]
- Laravel Version: 8.83.7
- Nova Version: 4.0.5
- PHP Version: 8.1.3
- Database Driver & Version: mysql & 5.7.37
- Operating System and Version: macOS Monterey 12.3
- Browser type and version: Chrome 99.0.4844.84
- Reproduction Repository: https://github.com/###/###

### Description:
When creating a text field and returning it as a mailto link and clicking it on the index page, it does not open the email provider on the operating system but clicks through to the resource. Then when clicked on the details page, it works. 

```php
Text::make('Email')
        ->displayUsing(function ($email) {
            return "<a class='link-default' href='mailto:{$email}'>{$email}</a>";
        })
        ->asHtml()
        ->nullable(),
```

Here is the section of documentation that I used to reference this:
https://nova.laravel.com/docs/4.0/resources/fields.html#formatting-text-as-links

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Create a text field for an email.
2. Add the `displayUsing()` method and return the email as an `<a>` tag with the `href='mailto:'`.
3. Visit the resources index page.
4. Click the email link, it should open your email provider so you can write an email, but instead it takes you to the details page.

**Comment by riasvdv** [comment]
Same for URL fields or any other link. CMD + Click doesn't work either, middle mouse button does work however.

**Comment by jringeisen** [comment]
Was this resolved? I updated to the latest update and I'm still having the issue.

**Comment by davidhemphill** [comment]
It's resolved but a release hasn't been cut with this yet.

**Comment by ziming** [comment]
It would be really nice if Nova 4 comes with Email Field and Telephone field since it is so common. Much more common than URL field in fact.

**Comment by jaxramus** [comment]
For phone numbers I am using this and its working great in Nova 4:

```
            Text::make('Phone')
                ->displayUsing(function ($value) {
                    return '<a href="tel:' . urlencode($value) . '" class="link-default whitespace-nowrap">' . $value . '</a>';
                })
                ->asHtml(),
```
