### ISSUE TITLE
Cards are hidden in desktop mode when hidding them from the responsive view

### ISSUE THREAD

**Issue by potsky** [laravel/nova-issues#3884]
- Laravel Version: 8.83.7
- Nova Version: 4.0.5
- PHP Version: 8.0.12
- Database Driver & Version: PGSQL
- Operating System and Version: sail 1.13.9
- Browser type and version: Brave (Chrome) [Version 1.37.109 Chromium: 100.0.4896.60 (Official Build) (arm64)]
- Reproduction Repository: https://github.com/private

### Description:

Cards are no more displayed

### Detailed steps to reproduce the issue on a fresh Nova installation:

- Reduce your browser window width to go to mobile breakpoint
- Click on the button to Hide cards
- Increase your browser window width to go to desktop breakpoint
- Cards are not displayed
- Search for hours what you have changed in the code to make cards crashed before understanding this :-)

**Comment by davidhemphill** [comment]
Yeah...we know about this, but it's something that wouldn't really happen in a real-life scenario...

**Comment by potsky** [comment]
Yes I think too but perhaps just always displaying the show card button instead of just mobile breakpoint is a correct solution without technical debt.

BTW congrats for this v4 👏👏🤗
