### ISSUE TITLE
Redirect users to a resource instead of the dashboard 

### ISSUE THREAD

**Issue by albalooshi** [laravel/nova-issues#389]
I would like to redirect the users to a specific resource based on their role, what I am currently thinking is checking the URL of the user in NovaServiceProvider's `boot()` and redirect them accordingly. is this the best approach for this problem?

**Comment by nickels** [comment]
That would be a nice feature.

**Comment by dillingham** [comment]
Redirect them to / and do your role check there

**Comment by shigg1120** [comment]
+1

**Comment by robertvrabel** [comment]
+1 I would like the dashboard to only be available to Admins of my application and this would work great to redirect then to a resource I know they have access to.

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by yehudahkay** [comment]
Currently this method works:

To NovaServiceProvider.php add:

`Nova::script('menuFix', __DIR__.'/../../resources/js/fixMenu.js');
`
Create file fixMenu.js with following:

    ```
if (location.pathname == '/' || location.pathname == '/dashboards/main'){
        location.href = '/whereToRedirect'
    }

```

**Comment by mikaelpopowicz** [comment]
You may also use a middleware:

```php
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;

class IndexRedirect
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle(Request $request, Closure $next)
    {
        if ($request->is(config('nova.path'))) {
            return redirect('resources/'.\App\Nova\YouResource::uriKey());
        }

        return $next($request);
    }
}
```

and put it in the global middleware section or in nova config.
