### ISSUE TITLE
Main dashboard loaded after a resource Update

### ISSUE THREAD

**Issue by josemanuelsh** [laravel/nova-issues#3895]
- Laravel Version: 9.1.4
- Nova Version: 4.1.0
- PHP Version: 8.0
- Database Driver & Version:

### Description:

When editing a resource, if the button Update is clicked (not Update & Continue Editing) Nova goes to the Main Dashboard.

### Detailed steps to reproduce the issue on a fresh Nova installation:

I tried this with different resources. It is always the same.

1. Go to Users
2. Enter the edit page on any
3. Click "Update User"
4. [error] The main dashboard is loaded.

The only customization I made was the top logo, following the instructions in the documentation.

**Comment by crynobone** [comment]
Can you submit the full reproducing repository? We already have dusk tests covering this use case and if that were the case we would already notice it.

**Comment by josemanuelsh** [comment]
I figured it out. A middleware (not related to the backend) was changing the Nova path when accessing the `nova-api`. This is not a bug. My apologies.
