### ISSUE TITLE
Action with Depends On doesn't work correctly - Nova 4

### ISSUE THREAD

**Issue by kevariable** [laravel/nova-issues#3897]
- Laravel Version: ^9.0
- Nova Version: "^4.0"
- PHP Version: "php": "^8.0",
- Database Driver & Version: MySQL version 8
- Operating System and Version: Arch Linux
- Browser type and version: Chromium Latest Version
- Reproduction Repository: -

### Description:

Depends On feature doesn't work after upgrading from Laravel Nova 3 for Action

### Detailed steps to reproduce the issue on a fresh Nova installation:

Following all upgrade guide

## Code

```php
Select::make('Name', 'name')
      ->options([
          'xxx' => 'xxx'
      ])->rules('required'),

  Text::make('Store Name')
       ->hide()
      ->dependsOn('name', function (Text $field, NovaRequest $request, FormData $formData) {
      
         // I tries to Log no data was attached here
      
          $field
             ->show()
              ->rules([
                  'required',
                  'max:15',
                  Rule::unique(Channel::class)->where('name', $formData->name)
              ])
              ->help(Str::replace(':name',  $formData->name, 'Please enter your :name xxx name'));
      }),
```

## Screenshots

![image](https://user-images.githubusercontent.com/56016477/162344362-27a274ff-e413-45ee-a8f0-0861ceb14b06.png)

Let me know if need more details on specify issue

**Comment by crynobone** [comment]
Action doesn't implement depends on at the moment.

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
