### ISSUE TITLE
dependsOn not working correctly with multiple dependencies

### ISSUE THREAD

**Issue by puzzledmonkey** [laravel/nova-issues#3899]
- Laravel Version: 8.83.7
- Nova Version: 4.1.0
- PHP Version: 8.0.15
- Database Driver & Version: mysql
- Operating System and Version: Windows 10
- Browser type and version: Firefox & Chrome
- Reproduction Repository: https://github.com/###/###

### Description:

When used in multiple levels, dependsOn is still a little broken. The cause seems to be missing data in the creation-fields and update-fields calls.

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. new Nova install
2. add a model and resource with the following fields:

```
Boolean::make('Test 1'),
Boolean::make('Test 2')->dependsOn(
    ['test_1'],
    function (Boolean $field, NovaRequest $request, FormData $formData) {
        if ($formData->test_1) {
            $field->show();
        } else {
            $field->hide();
        }
    }
),
Boolean::make('Test 3')->dependsOn(
    ['test_1', 'test_2'],
    function (Boolean $field, NovaRequest $request, FormData $formData) {
        if ($formData->test_1 && $formData->test_2) {
            $field->show();
        } else {
            $field->hide();
        }
    }
),
```

3. Create a new resource and tick all 3 boxes (they appear as expected), save resource
4. Edit the resource you just saved, boxes appear as expected
5. Untick and then tick either Test 1 or Test 2
6. Note that Test 3 doesn't re-appear until you do this to BOTH boxes. You can see in the network requests, e.g. if you untick and re-tick Test 1 only test_1: true is sent, although Test 3 depends on both test_1 and test_2

Note - I'm not sure if this is related but a similar issue is that dependsOn isn't firing for default() values:

```
Boolean::make('Test 1')->default(true),
Boolean::make('Test 2')->dependsOn(
    ['test_1'],
    function (Boolean $field, NovaRequest $request, FormData $formData) {
        if ($formData->test_1) {
            $field->show();
        } else {
            $field->hide();
        }
    }
),
```

create a new resource with this and note that Test 2 only shows up if you untick and then retick Test 1. I'm aware this is solvable by adding ->hide() to Test 1 but in cases where the default value is being programmatically generated it would be great to have this work as expected out of the box without needing to conditionally add ->hide()

**Comment by crynobone** [comment]
This pretty complex for me to understand, can you create reproducing code repository for this issue, and probably video on each steps.

**Comment by puzzledmonkey** [comment]
Sure thing.

https://github.com/puzzledmonkey/nova-dependson-test

https://user-images.githubusercontent.com/3913622/162395642-19623040-d2f1-462f-b321-2d2d55b046cb.mp4

You can see the issue here when editing the first time, unticking and ticking 'test 2' doesn't cause test 3 to reappear as only test_2 is sent in the PATCH update-fields request, but when unticking and ticking 'test 1' then it's sending both of test_1 and test_2.

Let me know if I can clarify anything else here.

**Comment by crynobone** [comment]
The Dependable Field detect based on `change` event, which is the root cause of this issue. Will look into fixing this.

**Comment by puzzledmonkey** [comment]
That would also explain the issue with it not picking up the boolean with ->default(true) in dependsOn (the second piece of code in my initial post).

Thanks and good luck!

**Comment by elizdlt202** [comment]
This is still not fixed in the latest release.

**Comment by davidhemphill** [comment]
@elizdlt202 Please post a new issue and fill out the issue template as this issue has been fixed and tested in the way described by the original poster.
