### ISSUE TITLE
Clicking on index filters scrolls page to bottom

### ISSUE THREAD

**Issue by Victor-emil** [laravel/nova-issues#3901]
- Laravel Version: 9.7.0
- Nova Version: 4.1.0
- PHP Version: 8.1.1
- Database Driver & Version: PostgreSQL 13
- Operating System and Version: MacOS
- Browser type and version: Google Chrome 100.0.4896.75 

### Description:

When clicking on the filters icon in order to open the dropdown it scrolls the page to the bottom. 

https://user-images.githubusercontent.com/8555068/162381461-5d73940f-0798-4478-b9ee-8ebacd16ee41.mov

### Detailed steps to reproduce the issue on a fresh Nova installation:

Add the following two filters to a resource and populate the table with 25 records. 

```
DateTime::make('Created At')->filterable()->exceptOnForms(),
DateTime::make('Updated At')->filterable()->exceptOnForms(),
```

**Comment by kazak71** [comment]
I have tha same notice. But I think this problem is in Chrome, in Safari everithing is OK
