### ISSUE TITLE
SVG in thumbnail

### ISSUE THREAD

**Issue by sojkadavid** [laravel/nova-issues#3902]
- Laravel Version: 8.83.7
- Nova Version: 4.1.0
- PHP Version: 8.0.1

### Description:
Not sure if it's a bug (or something with the image file), but when I want to use SVG files for images, it works fine on the detail page, but does not display anything on the list page. Or better say it shows `0x0` sized images.

In my case, I use SVG files for country flags, here is an example:
![us](https://user-images.githubusercontent.com/43849735/162401546-efb50b38-2a87-4569-99a9-6bfe6580426b.svg)

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Save the given file to `public/flags/us.svg`
2. In any Nova resource, add this as one of the fields:
```php
Image::make('Flag',function () {
    $code = 'US'; // this can be a model's attribute
    return 'flags/'.strtolower($code).'.svg';
})
    ->preview(fn($path) => asset($path))
    ->thumbnail(fn($path) => asset($path))
    ->disableDownload()
    ->readonly()
    ->exceptOnForms()
    ->rounded(),
```

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by sojkadavid** [comment]
> 👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

Why is this a `feature request`? SVGs work fine as avatars for search results, but not for indexes?
