### ISSUE TITLE
Detail & edit form redirects to 403 when an S3 image failed to load with 403 forbidden error

### ISSUE THREAD

**Issue by ilyasfoo** [laravel/nova-issues#391]
Version v1.0.8

My image is hosted on S3, and if the link is invalid (ex: empty string) and S3 returns error, somehow triggers redirect to nova's 403 error page.

I have confirmed when the link is valid it does not behave as such.

![image](https://user-images.githubusercontent.com/3747241/44954550-e9e27680-aed5-11e8-8908-125b37d1acb8.png)

**Comment by nickels** [comment]
Same here.

**Comment by dillingham** [comment]
Loosely related to https://github.com/laravel/nova-issues/issues/208

**Comment by stonkeep** [comment]
Same here.
Some solution?

**Comment by gvsrepins** [comment]
I'm also having this issue on Digital Ocean.

**Comment by desaintflorent** [comment]
I can confirm this is also a problem for me. With S3 and laravel nova behind a load balancer. Still no solution to this ?

**Comment by davidhemphill** [comment]
Sorry, but we are unable to debug your issue without a reproducible code example. Once you provide that we can open this up again.
