### ISSUE TITLE
Resources section in main menu can't be translated

### ISSUE THREAD

**Issue by drobee** [laravel/nova-issues#3919]
- Laravel Version: 9.x
- Nova Version: 4.1.0
- PHP Version: 8.1.3
- Database Driver & Version: any
- Operating System and Version: any
- Browser type and version: any

### Description:
The name of the `Resources` section in the main menu isn't translatable. In `Laravel\Nova\Tools\ResourceManager` the name of the section is defined as a string instead of the `__()` translation helper.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
