### ISSUE TITLE
[4.x] Kebab button (3 dots) in Resource Index shows in every row even though no actions are available in its menu

### ISSUE THREAD

**Issue by wdelfuego** [laravel/nova-issues#3925]
- Laravel Version: 9.7.0
- Nova Version: 4.1.0
- PHP Version: 8.1.4
- Database Driver & Version: MySQL 5.7.29
- Operating System and Version: Docker @ MacOS 12.2
- Browser type and version: Safari 12.2

### Description:
Each Resource in its index view has a kebab button (3 dots) that normally shows 'Show Preview' and 'Replicate' options.
If both options are unavailable due to a Policy that doesn't allow them, the popup menu is empty but the button still shows and opens the empty menu. 

This is what it looks like after clicking the kebab button in the first row:
<img width="264" alt="Screenshot 2022-04-11 at 00 05 02" src="https://user-images.githubusercontent.com/1326136/162641823-89fdf285-6514-458a-a3db-2d8ae66283c0.png">

### Solution:
It would be nice if the kebab button hides automatically when no options are available in it.

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Create an Eloquent Model with an accompanying Laravel Policy that returns 'false' for every method except viewAny
- Add a Nova Resource for that Eloquent Model
- Create at least 1 instance of the Eloquent Model in the database
- Open the Index view for that resource in Nova; every row shows the kebab button but when clicked shows an empty submenu

**Comment by crynobone** [comment]
Fixed and pending next release.
