### ISSUE TITLE
Resource rows in index view are clickable even if the user has no rights to view the Resource

### ISSUE THREAD

**Issue by wdelfuego** [laravel/nova-issues#3928]
- Laravel Version: 9.7.0
- Nova Version: 4.1.0
- PHP Version: 8.1.4
- Database Driver & Version: MySQL 5.7.29
- Operating System and Version: Docker @ MacOS 12.2
- Browser type and version: Safari 12.2

### Description:
Resource rows in the index view are normally clickable and directly open the detail view for the Resource.
If the user has no rights to view the Resource, the row is still clickable but leads to a 403.

This is extra annoying because the user can't simply use the browser's back button to go back to the index view, due to the way Nova handles 403 errors (with a redirect from the Resource, so using the back button only regenerates the 403 error and the user is effectively stuck).

### Solution:
It would be nice if the row would stop being clickable if the user doesn't have the right to View the Resource.

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Create an Eloquent Model with an accompanying Laravel Policy that returns 'false' for every method except viewAny
- Add a Nova Resource for that Eloquent Model
- Create at least 1 instance of the Eloquent Model in the database
- Open the Index view for that resource in Nova and click a row in it

**Comment by wdelfuego** [comment]
Has the issue been fixed?

**Comment by crynobone** [comment]
@wdelfuego PR has been merged pending next release.
