### ISSUE TITLE
Where can you edit the dashboard?

### ISSUE THREAD

**Issue by StanBarrows** [laravel/nova-issues#393]
Is there a way to modify the dashboard?

![edit](https://user-images.githubusercontent.com/10268813/44955080-a96f0280-aead-11e8-9fa6-3424ce31eb19.png)

I found within the nova folder a ressource:

```
@extends('nova::layout')

@section('content')
Dashboard Content
@endsection


```

But this does not answer my questions.

Cheers,
Stan

**Comment by stevelacey** [comment]
@StanBarrows you are looking a the Help card that is set by default in your `NovaServiceProvider`

```php
    protected function cards()
    {
        return [
            new Help(),
        ];
    }
```

The idea is you swap this out for some cards/metrics

https://nova.laravel.com/docs/1.0/customization/cards.html#overview

**Comment by StanBarrows** [comment]
@stevelacey 

Thanks a lot! I was missing that out somehow..

**Comment by Bautistaluis** [comment]
Is there a way to completely change the view of the dashboard and replace it with a resource?

**Comment by dillingham** [comment]
Route::redirect(‘nova/dashboard’, ‘nova/resource’);

**Comment by rosswintle** [comment]
Forgive me, I've been using Nova for about half a day.

Can I just put some HTML as welcome/help text for users in a resource's view?

**Comment by dillingham** [comment]
It’s a card in the nova provider. 

Read the docs.

**Comment by rosswintle** [comment]
I know it's a card. I have read the docs. I have watched the Laracasts. 

So back to where I started:

I'd love for there to be an option for this to just be a view or something that I can put some HTML in.

This would be much simpler than the whole creating, building and deploying a card process. I know what the docs say. I'm suggesting it be made easier.

Thanks

**Comment by taeo** [comment]
@dillingham 

> Route::redirect(‘nova/dashboard’, ‘nova/resource’);

👆 Where do you put this?

**Comment by larsemil** [comment]
> @dillingham
> 
> > Route::redirect(‘nova/dashboard’, ‘nova/resource’);
> 
> point_up_2 Where do you put this?

In your route file?

**Comment by yixvan6** [comment]
@Bautistaluis hi, i also want to remove the dashboard page, and redirect it to a resource, is there any solution?

**Comment by gbrits** [comment]
I had to edit the *routes.js* redirect to overcome the issue in my case - as the routing is done via the components in JavaScript, after the redirectTo post from Laravel.

**Comment by benedict-w** [comment]
+1 for dashboard to resource redirect!

**Comment by poncianodiego** [comment]
I also believe there should be an alternative to creating a whole Card

**Comment by stephan-v** [comment]
Please update this. This was one of the first things I was looking at.

**Comment by reense** [comment]
I came up with the following solution:
1) Overwrite the `layout.blade.php` file in your project.
2) Add the following logic after `window.Nova = new CreateNova(config)`:
```php
  window.Nova = new CreateNova(config);

    window.Nova.booting((Vue, router, store) => {
        /** This fixes showing an empty dashboard. */
        router.beforeEach((to, from, next) => {
            if (to.name === 'dashboard.custom') {
                next({ name: 'index', params: { resourceName: 'products'}});
            }

            next();
        });
    });
```

I wanted to redirect to the 'products' resource.

**Comment by mrimran** [comment]
Extending @reense solution with more clear instructions for `Nova 3.x or below`:

- Copy `vendor/laravel/nova/resources/views/layout.blade.php` to `resources/views/vendor/nova/`
- Now open `resources/views/vendor/nova/layout.blade.php` and edit it
- Replace this line with the code below `window.Nova = new CreateNova(config);`

```
    window.Nova = new CreateNova(config);
    window.Nova.booting((Vue, router, store) => {
        /** This fixes showing an empty dashboard. */
        router.beforeEach((to, from, next) => {
            if (to.name === 'dashboard.custom') {
                next({ name: 'index', params: { resourceName: 'users'}});
            }

            next();
        });
    });
```
- Replace `users` with your entity name's plural like `products`
- Now save the file and refresh the nova `dashboard` and you should see the new page.
