### ISSUE TITLE
Nova is running the accessor when using dependsOn

### ISSUE THREAD

**Issue by williamcruzme** [laravel/nova-issues#3935]
- Laravel Version: 8.83.7
- Nova Version: 15.7.0
- PHP Version: 8.0
- Database Driver & Version: MySQL 8.0
- Operating System and Version: macOS 12.3.1 
- Browser type and version: Chrome Version 100.0.4896.75 arm64

### Description:

Having these fields:
```php
Text::make('Prize', 'amount_formatted')
    ->onlyOnIndex(),

Select::make('Type')
    ->options(...)
    ->rules('required'),

Select::make('Position')
    ->options(...)
    ->dependsOn(
        ['type'],
        function ($field, $request, $formData) {
            if ($formData->type !== 'piece') {
                $field->hide();
            }
        }
    ),
```

Nova is running the `amount_formatted` accessor every time the "Type" field is changed in the Update Resource page. Even if the field is not visible when updating (because it has `onlyOnIndex`).

```php
public function getAmountFormattedAttribute()
    {
        return match ($this->type) {
```

and I'm getting `$this->type` as null.

The correct behavior is running the accessors only from index/details.

All this happens only if `->dependsOn()` is present.

**Comment by crynobone** [comment]
Please provide full reproducing code such as https://github.com/nova-issues
