### ISSUE TITLE
key() expects exactly 1 argument, 3 given in global search

### ISSUE THREAD

**Issue by chelev** [laravel/nova-issues#3939]
- Laravel Version: 8.83.7
- Nova Version: 4.1.0
- PHP Version: 8.1.4
- Database Driver & Version:
- Operating System and Version: MacOS, Ubuntu

### Description:

When trying to use the global search in nova since the upgrade to version 4 I am getting the following error. 

"message": "key() expects exactly 1 argument, 3 given",
    "exception": "ArgumentCountError",
    "file": "/vendor/laravel/nova/src/Query/Search.php",
    "line": 52,
    "trace": [
        {
            "file": "/vendor/laravel/nova/src/Query/Search.php",
            "line": 52,
            "function": "key"
        },

**Comment by crynobone** [comment]
Share the affected resource `searchableColumns()` method. You may need to review the log file in order to know the correct resource.

**Comment by chelev** [comment]
> ~Share the affected resource `searchableColumns()` method. You may need to review the log file in order to know the correct resource.~

I see the comment was scratched, do you want me to dig dipper in it, or you were able to reproduce it?

**Comment by crynobone** [comment]
> do you want me to dig dipper in it, or you were able to reproduce it?

bugfix PR submitted, pending review now 😄
