### ISSUE TITLE
Lenses don't hide hasMany and belongsToMany by default

### ISSUE THREAD

**Issue by stevelacey** [laravel/nova-issues#394]
I set up a few lenses that essentially apply filters to what is shown on the regular resource index.

You can share the fields declaration with both a resource and lenses via a standard trait – but lens fields are processed slightly differently to resource fields, whilst a resource will hide `hasMany` and `belongsToMany` by default, lenses won't, it is assumed on a lens that all fields that can be rendered – should be.

To avoid this I did 2 things:
- I customized my trait to mark `hasMany` and `belongsToMany` explicitly as `hideFromIndex` (which is the default on resources already)
- I filtered the fields from the trait in lenses-only, given lenses don't currently acknowledge this bool:
    ```php
    public function fields(Request $request)
    {
        return collect($this->teamTraitFields($request))->where('showOnIndex', true)->toArray();
    }
    ```

I figure this could be made easier either by:
- Adding better support for sharing fields to lenses ... this sounds like a common use case anyway
- Making lenses process fields in the same way resources do – then understanding the above is unnecessary and the trait will work without any additional processing

Nova v1.0.5

**Comment by stevelacey** [comment]
FYI I also wanted to share the index query – given the fields included some counts, I did this again via the trait with the following in the resource:

```php
    public static function indexQuery(NovaRequest $request, $query)
    {
        return self::teamTraitQuery(parent::indexQuery($request, $query));
    }
```

And in the lens:

```php
    public static function query(LensRequest $request, $query)
    {
        return $request->withOrdering($request->withFilters(self::teamTraitQuery($query)));
    }
```

I don't know if this is worth improving on, just putting it here for reference as another use case

**Comment by stevelacey** [comment]
Relates to https://github.com/laravel/nova-issues/issues/549

**Comment by davidhemphill** [comment]
This is a problem best handled on the user end.
