### ISSUE TITLE
[4.x] Action visibility issues

### ISSUE THREAD

**Issue by ajitbohra** [laravel/nova-issues#3943]
- Laravel Version: 9.7.0
- Nova Version: 4.1.0
- PHP Version: 8.1.4
- Database Driver & Version: MySQL 8.0.28
- Operating System and Version: macOS 12.3.1 Monterey
- Browser type and version: chrome 100

### Description:
As per docs 

"By default, actions are visible on both the resource index and detail pages."

Actual behavior is only displayed on `details`.

also `showOnIndex` `onlyOnIndex` not working

### Detailed steps to reproduce the issue on a fresh Nova installation:

Generate action 
``` sh
php artisan nova:action EmailAccountProfile
```

Register action

``` php
/**
 * Get the actions available for the resource.
 *
 * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
 * @return array
 */
public function actions(NovaRequest $request)
{
    return [
        new Actions\EmailAccountProfile
    ];
}
```

**Comment by di-dmosher** [comment]
@ajitbohra To have the actions show up as configured above you have to select a resource first, then you should see the action drop down (which I do). If you want to always show the action you'll need to do `Actions\EmailAccountProfile::make()->standalone()`

**Comment by crynobone** [comment]
Yes, @di-dmosher answer js correct.
