### ISSUE TITLE
MophOne with HasOne fails when HasOne relationship is null

### ISSUE THREAD

**Issue by oskobri** [laravel/nova-issues#3948]
- Laravel Version: 9.7.0
- Nova Version: 4.1.0
- PHP Version: 8.1.0
- Database Driver & Version: Mysql 8

### Description:
An example will be more understandable so here it is.
This bug can be reproduced with 3 resources/models.

```
Models

User

   public function userInformation()
    {
        return $this->hasOne(UserInformation::class);
    }

   public function userable()
    {
        return $this->morphTo();
    }


UserInformation

   public function user()
    {
        return $this->belongsTo(User::class);
    }


Author

   public function user()
    {
        return $this->morphOne(User::class, 'userable');
    }

```

```
Nova resources

User

  HasOne::make('Information', 'usrInformation', UserInformation::class)


Author

  MorphOne::make('User', 'user', User::class)

```

When accessing nova resources Author, if User hasOne userInformation there is no bug.
But if User has no userInformation, relation userInformation is applied to Author and not the user so the error is

`Call to undefined relationship [userInformation] on model [App\\Models\\Author].`

**Comment by oskobri** [comment]
Why is it closed ? The bug is not fixed.

**Comment by crynobone** [comment]
> Why is it closed ? The bug is not fixed.

![image](https://user-images.githubusercontent.com/172966/164245956-2ac01ecc-524b-4451-bf44-315c37858810.png)

If you have any more issue, please create new issue with reproducing step as existing one has been fixed.
