### ISSUE TITLE
belongsToMany relationships to same model does not work as expected

### ISSUE THREAD

**Issue by GerwinV** [laravel/nova-issues#3949]
- Laravel Version: 9.7.0
- Nova Version: 4.1.0

### Description:
We got two `belongsToMany` relationships from model `foo` to the User model.

When we add both to the Nova resource `foo` it shows the right panel with `Users`. The problem is that the second (belongsToMany) panel only shows the Users not already attached to the **first** (belongsToMany) panel. It looks like the Nova resource doesnt take the intermediate table name into account.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Make sure you have a User model and Resource in Nova.

Create a `foo` model with the following `belongsToMany` relations:

```
    public function typeOneUsers()
    {
        return $this->belongsToMany(User::class, 'foo_typeone', 'foo_id', 'user_id');
    }

    public function typeTwoUsers()
    {
        return $this->belongsToMany(User::class, 'foo_typetwo', 'foo_id', 'user_id');
    }
```

Add those to the foo resource:

```
public function fields(NovaRequest $request)
    {
        return [
            ID::make()->sortable(),
            Text::make('Naam', 'name'),
            BelongsToMany::make('Type one', 'typeOneUsers', 'App\Nova\User'),
            BelongsToMany::make('Type two', 'typeTwoUsers', 'App\Nova\User'),
        ];
    }
```

The `BelongsToMany` mentioned **first** will work. We can add users, remove them etc. 
The `BelongsToMany` mentioned second is able to add users who are **not** added to the first panel yet. This fills the right intermediate table. But you are not able to add users who are already added to the first panel. When searching the second panel, you will only find users not added to the first one.

It looks like the resource is not looking at the relation name, but at the first relation when it is from the same model.

<img width="1484" alt="Schermafbeelding 2022-04-11 om 17 45 39" src="https://user-images.githubusercontent.com/5094978/162779676-e5cd4c4b-ff0c-44ea-8d0d-c1a2f309af0c.png">

In this example we have 4 users. None of these users can be added to the second panel. Only when one user in the first panel is deleted, we can add that user to the second panel. So we can add the users, but not search for them if added to the first panel.

Note: if we swap the `BelongsToMany::make` in the resource file, it will work the other way around. So that means it is purely based on the order of the relationships in the resource file.

**Comment by crynobone** [comment]
> It looks like the resource is not looking at the relation name, but at the first relation when it is from the same model.

Our dusk tests are already covering this use case. Can you submit full reproducing code similar to https://github.com/nova-issues to allows use to debug this issue.
