### ISSUE TITLE
[suggestion] Delete and Detach should not have the same icon

### ISSUE THREAD

**Issue by ordago** [laravel/nova-issues#395]
![detach](https://user-images.githubusercontent.com/6376814/44955928-7c255300-aeb3-11e8-9b8a-618b55da7f4c.png)

Third image would be my suggestion, but there is nothing similar in Heroicons UI.

**Comment by marijnhurkens** [comment]
We're currently have the same issue where our users don't see / know the difference between the two. Especially for non-technical users this is confusing. They will expect something to be deleted or delete stuff on accident.

Could this be reopened?

**Comment by davidhemphill** [comment]
In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by jbrooksuk** [comment]
We’d accept a PR for this though.

**Comment by marijnhurkens** [comment]
How would I create a PR for Nova? There is no public repo right?
