### ISSUE TITLE
sortable() on Date field doesn't work if the field name is 'date'

### ISSUE THREAD

**Issue by DonDiegoAA** [laravel/nova-issues#396]
I tore my hair out for hours on this problem, before trying to rename the 'date' field to 'document_date', and all of a sudden, it works.

**Comment by treeStoneIT** [comment]
Interesting, i tried the above but it didn't work for me... do you have date or datetime field?

**Comment by Saymecode** [comment]
Me too

**Comment by DonDiegoAA** [comment]
@treeStoneIT : Initially I had a date field (named date), I tried to convert to DateTime (timestamp in migration), but the sortable problem was present in both case. 
Then I rename the field in database, and both Date and DateTime are now sortable.

**Comment by cloudstudio** [comment]
+1 this could be fixed ? is a really problem...

**Comment by mizmiz** [comment]
Duplicate of #133

**Comment by davidhemphill** [comment]
This has been fixed and will be included in an upcoming release.
