### ISSUE TITLE
DateTime picker closes action modal

### ISSUE THREAD

**Issue by RensenBart** [laravel/nova-issues#3960]
- Laravel Version: 8.83.7
- Nova Version: 3.32.0 
- PHP Version: 8.0.17
- Database Driver & Version: MySQL
- Operating System and Version: MacOS Monterey 12.3.1 (but I doubt this is relevant)
- Browser type and version: Firefox 99.0 (64-bit)

### Description:
If there's a DateTimePicker field in the fields section of an action, it will close the modal, stopping any user input

### Detailed steps to reproduce the issue on a fresh Nova installation:

https://user-images.githubusercontent.com/43001328/162960568-92db5ea1-1bf9-4c5c-b343-2019f3e09603.mov

I've seen previous issues that had a similar issue to this, but none of those had the fix for my case.

**Comment by crynobone** [comment]
See https://github.com/laravel/nova-issues/issues/3799 and https://github.com/laravel/nova-issues/issues/3778#issuecomment-1068754398

**Comment by RensenBart** [comment]
Apologies, it seems there was a package that messed with the DateTime field. Thank you for linking those comments because I 100% would not have found them. I'll open an issue with the package maintainers to see if they can fix it. Thank you for your time!

**Comment by RensenBart** [comment]
Apologies. I have more info pertaining this bug.
I have removed any and all packages that could interfere with the workings of the DateTime field, and figured out a way to reproduce the bug.
It happens whenever there are two or more DateTime fields. Whenever you click one open, input your date & time and directly focus the next one, it breaks. However, if you input your date & time, unfocus the input then focus on the second input, it works again. Video:

https://user-images.githubusercontent.com/43001328/162974917-fbfd88ad-ef13-44c8-9f55-ee2b596fb831.mov

I hope this gives more insight

**Comment by dhonions** [comment]
I am also getting error with DateTime in Nova 4.  I have 5 DateTime fields on a Nova Resource that are identically defined and set-up for a mysql db.  

Input works as expected for the first 2 DateTime inserts and they write to the db as expected, but for the 3rd DateTime I always get a wrong DateFormat error.  No matter what I do.

SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2022-04-13T21:22:41.000Z'

But the 3 fields are defined identically in the db and model and cast to dateTime.

**Comment by crynobone** [comment]
@dhonions don't hijack other issues.

**Comment by dhonions** [comment]
Sorry - I thought it was related.  I shall try better :)

**Comment by davidhemphill** [comment]
There are no plans to update Nova v3 at this point.
