### ISSUE TITLE
Opening Tool in Nova 4 results in 404 error

### ISSUE THREAD

**Issue by rossgillies** [laravel/nova-issues#3968]
- Laravel Version: 9.7.0
- Nova Version: 4.1.0
- PHP Version: 8.0
- Database Driver & Version: pgsql
- Operating System and Version: WSL 2 Rocky 
- Browser type and version: Chrome

### Description:

When creating a Tool in Nova, loading the route directly results in a 404 error.

### Detailed steps to reproduce the issue on a fresh Nova installation:

- Install Nova 4 on new project
- Create a Tool, eg `php artisan nova:tool example/demo-tool`
- cd ./nova-components/DemoTool and npm run watch
- Register tool in service provider
- Go to application.url/nova/demo-tool which shows a 404 response instead of Tool.vue

**Comment by crynobone** [comment]
https://user-images.githubusercontent.com/172966/163070864-e3a1aa40-cd42-4e99-95ee-93eee8af4b3f.mp4

Unable to reproduce.

I guess this related to #3844, can you try following the suggested changes https://github.com/laravel/nova-issues/issues/3844#issuecomment-1091706850 and verify if that solves your issue?

**Comment by rossgillies** [comment]
> CleanShot.2022-04-13.at.06.39.55.mp4 
> Unable to reproduce.
> 
> I guess this related to #3844, can you try following the suggested changes [#3844 (comment)](https://github.com/laravel/nova-issues/issues/3844#issuecomment-1091706850) and verify if that solves your issue?

Thank you, it looks like this was half of the issue.

The other problem was the custom auth guard I was using. props->currentUser and props->novaConfig->mainMenu from HandleInertiaRequests were coming back as empty which seems to have caused the 404 error. I'll further investigate to see if this is related to my auth guard or the package, however switching back to the default user auth has fixed this.

**Comment by crynobone** [comment]
> The other problem was the custom auth guard I was using. props->currentUser and props->novaConfig->mainMenu from HandleInertiaRequests were coming back as empty which seems to have caused the 404 error.

We just updated our documentation regarding this matter: https://nova.laravel.com/docs/4.0/upgrade.html#eloquent-user-provider-required and discussed here: https://github.com/laravel/nova-issues/discussions/3966#discussioncomment-2555171

Also 4.1.1 replaced `Illuminate\Http\Request` in `routes/inertia.php` to `Laravel\Nova\Http\Requests\NovaRequest`.

![image](https://user-images.githubusercontent.com/172966/163076824-eeccd5c9-cf45-43d3-8239-e57b4f439b1c.png)

**Comment by hakanersu** [comment]
Laravel Version: 9.7.0
    Nova Version: 4.2.1
    PHP Version: 8.1
    Database Driver & Version: pgsql
    Operating System and Version: Osx
    Browser type and version: Firefox

I have similar issue. When i visit from click tool link in sidebar i get tool page without profile menu or sidebar. When i reload page it gives me 404 page.

I am using custom guard and when i remove custom guard it is working as expected.

<img width="1450" alt="image" src="https://user-images.githubusercontent.com/1052467/163332150-4bc8a18f-eb63-4940-8e68-a4f2f33535a5.png">

**Comment by hakanersu** [comment]
Laravel Version: 9.7.0
    Nova Version: 4.2.1
    PHP Version: 8.1
    Database Driver & Version: pgsql
    Operating System and Version: Osx
    Browser type and version: Firefox

I have similar issue. When i visit from clicking tool link in sidebar i get tool page without profile menu or sidebar. When i reload page it gives me 404 page.

I am using custom guard and when i remove custom guard it is working as expected.

<img width="1450" alt="image" src="https://user-images.githubusercontent.com/1052467/163332150-4bc8a18f-eb63-4940-8e68-a4f2f33535a5.png">

Edit:

In HandleInertiaRequests below code checking default guard not defined guard in `config/nova.php` When i fix this part profile menu shows up as expected.

```php
'currentUser' => function () use ($request) {
                return with($request->user(), function ($user) use ($request) {
                    return ! is_null($user) ? UserResource::make($user)->toArray($request) : null;
                });
            },
```           

In Nova.php

`availableScripts` checks default guard when i fixed that part tool finally has sidebar and i discovered that many places uses default guard with `$request->user()` but it has to be `$request->user(config('nova.guard'))`

**Comment by crynobone** [comment]
@hakanersu post new issue with full reproducing code.

**Comment by hakanersu** [comment]
@crynobone Issue is exactly same @rossgillies issue. He described he gets 404 which i get 404 when visiting url but when i click from left menu it shows empty page.

**Comment by crynobone** [comment]
@hakanersu Create separate issue with full reproducing code.

**Comment by johnpuddephatt** [comment]
Same issue here with a newly created tool using nova:tool command.

Relevant routes are registered and show when using route:list command. But visiting the URLs/clicking the sidebar menu entry results in a 404.

Using default eloquent auth and have tried the suggestion in https://github.com/laravel/nova-issues/issues/3844#issuecomment-1091706850 without success.

**Comment by crynobone** [comment]
@johnpuddephatt create separate issue and fill in the full issue template with reproducing repository.

A PR has been done for this issue and only handle issue that I understand from the initial replies.
