### ISSUE TITLE
HasOne field return many records even eloquent relation return one

### ISSUE THREAD

**Issue by simpsons310** [laravel/nova-issues#3971]
- Laravel Version: 8.61.0
- Nova Version: 3.29.0
- PHP Version: 7.4.28

### Description:
I've defined a `HasOne` relationship in my model 
```
public function latestService()
{
    return $this->hasOne(Service::class, 'apartment_id', 'id')->latest();
}
```
I've checked this relation and it return only 1 record.
And in my Nova resource file, I've defined Nova relation field `HasOne`
```
HasOne::make(__('Service'), 'latestService', 'App\Nova\Service'),
```
But in the detail view it return all my services in apartment.

I've also checked `ResourceIndexController` in vendor:
```
public function handle(ResourceIndexRequest $request)
    {
        $resource = $request->resource();

        [$paginator, $total, $sortable] = $request->searchIndex();

        return response()->json([
            'label' => $resource::label(),
            'resources' => $paginator->getCollection()->mapInto($resource)->map->serializeForIndex($request),
            'prev_page_url' => $paginator->previousPageUrl(),
            'next_page_url' => $paginator->nextPageUrl(),
            'per_page' => $paginator->perPage(),
            'per_page_options' => $resource::perPageOptions(),
            'total' => $total,
            'softDeletes' => $resource::softDeletes(),
            'sortable' => $sortable ?? true,
        ]);
    }
```
`$paginator->getCollection()` return collection of many services, not the latest.

Please check this issue

**Comment by crynobone** [comment]
Nova 3 does not support Has One of Many, you need to upgrade to Nova 4 which support this via `HasOne::ofMany()` declaration.
