### ISSUE TITLE
Searchable Column Array Executes file() PHP Function

### ISSUE THREAD

**Issue by bayareawebpro** [laravel/nova-issues#3972]
- Laravel Version: 9.2
- Nova Version: 4.1.0
- PHP Version: 8.0.5
- Database Driver & Version: N/A
- Operating System and Version: N/A
- Browser type and version: N/A
- Reproduction Repository: N/A

### Description:

`src/Query/Search.php` line 52 produces an error if the column name matches a built-in function.  This does not produce an error in the previous version.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Add a column name for `file` to a resource and search the index.  

```
    /**
     * The columns that should be searched.
     * @var array
     */
    public static $search = [
       'file',
    ];
```

**Comment by crynobone** [comment]
Fixed in 4.1.1
