### ISSUE TITLE
Column ordering for belongsToMany Pivot fields

### ISSUE THREAD

**Issue by jimarick** [laravel/nova-issues#3973]
Laravel V9
Nova V4.11
PHP V8.0.6

The column/field ordering does not work as expected when viewing the index of a related field.

For example, I have two models called Rapids and Set in a manyToMany relationship (Think of Rapids as just a type of question in an exam I'm working on). Each Rapid can be in many Sets, and each set can have many Rapids.

The Rapids model has a belongsToMany method called set:

```other
public function Set()
   {
       return $this->belongsToMany(Set::class);
   }
```

The set model has the equivalent method:

```other
    public function Rapids()
    {
        return $this->belongsToMany(Rapids::class);
    }
```

The Rapids Nova Resource has the following fields. Note the BelongsToMany field with a pivot column called Order (the order of the questions in the set):

```other
    public function fields(NovaRequest $request)
    {
        return [
            
            ID::make()->sortable(),

            BelongsToMany::make('Set')
            ->filterable()
            ->fields(function ($request, $relatedModel) {
                return [
                    Text::make('Order')->sortable(),
                ];
            }),
        
            Text::make('Finding'),

            Boolean::make('Normal'),

			  Text::make('Set', function() {
                return $this->set->pluck('id')->implode(',') ?? null;
            })->onlyOnIndex(),

            CornerstoneImages::make('Images', 'data'),

		]
	}
```

This works as expected, and when opening up a Set, the related rapids are displayed below, with columns in the correct order. Note Order column in position 2. 

![image](https://res.craft.do/user/full/2dfa1c5b-0204-ac16-f54f-2a27cbaac6d6/doc/DDC58302-4BD4-4287-B122-FFAFEE8A5B0C/322B7698-FBD5-4C28-8923-FE52BD662B8F_2/8mxlrwzsWy7NzuuIWKydErfcVeB3kgbmuTGNZ6c9nxIz/Image.png)

if I put the BelongsToMany field first in the list, then you would expect the pivot field called ORDER to show up first in this index, but instead it moves to the end:

```javascript
public function fields(NovaRequest $request)
    {
        return [
            
            BelongsToMany::make('Set')
            ->filterable()
            ->fields(function ($request, $relatedModel) {
                return [
                    Text::make('Order')->sortable(),
                ];
            }),

            ID::make()->sortable(),
        
            Text::make('Finding'),

            Boolean::make('Normal'),
            
            Text::make('Set', function() {
                return $this->set->pluck('id')->implode(',') ?? null;
            })->onlyOnIndex(),

            CornerstoneImages::make('Images', 'data'),

        ];
    }
```

![image](https://res.craft.do/user/full/2dfa1c5b-0204-ac16-f54f-2a27cbaac6d6/doc/DDC58302-4BD4-4287-B122-FFAFEE8A5B0C/0B7881F1-1E2A-470E-885A-30AD8661484B_2/qmrjAZweaSaVfKZyEAHFO25U2BiW55ntVpOQwyIGLxAz/Image.png)

It appears that whenever the BelongsToMany field is put first in the list, that pivot column always defaults to the last column. However, if you put ANY field before it, then its position works as expected.

**Comment by crynobone** [comment]
Please submit full reproducing code

**Comment by jimarick** [comment]
New laravel project with Nova installed

Create two models with belongsToMany relationships

```javascript
namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    use HasFactory;

    public function Sets()
    {
        return $this->belongsToMany(Set::class)->withPivot('order');
    }
}
```


```javascript
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Set extends Model
{
    use HasFactory;

    public function Questions()
    {
        return $this->belongsToMany(Question::class)->withPivot('order');
    }
}

```


Create Corresponding Migrations including Pivot table

```javascript
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up()
    {
        Schema::create('questions', function (Blueprint $table) {
            $table->id();
            $table->boolean('normal')->nullable();
            $table->text('finding')->nullable();
            $table->timestamps();
        });
    }
};

```


```javascript
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up()
    {
        Schema::create('sets', function (Blueprint $table) {
            $table->id();
            $table->timestamps();
        });
    }
};

```


```javascript
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up()
    {
        Schema::create('question_set', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('question_id');
            $table->unsignedBigInteger('set_id');
            $table->integer('order')->nullable();
            $table->timestamps();
        });
    }
};

```


Populate Database

![image](https://res.craft.do/user/full/2dfa1c5b-0204-ac16-f54f-2a27cbaac6d6/doc/0E0C1A87-C521-4B03-8809-C93DFA172DCD/AB4E7178-1AFD-402F-9BBE-F15D62006B6E_2/Ionx5J1ys5GCYZqgUhShS1fPB17HtiyZMZFcuI5XyWQz/Image.png)

![image](https://res.craft.do/user/full/2dfa1c5b-0204-ac16-f54f-2a27cbaac6d6/doc/0E0C1A87-C521-4B03-8809-C93DFA172DCD/28734CC9-2C6B-43AF-89A0-9AD81BA02E32_2/Cy0DF62xvbkPphq2S5hMhglgVE8B4hIZMlREYziLegsz/Image.png)

![image](https://res.craft.do/user/full/2dfa1c5b-0204-ac16-f54f-2a27cbaac6d6/doc/0E0C1A87-C521-4B03-8809-C93DFA172DCD/4F158C51-3FDD-4068-BD00-A660B5C18913_2/XHwWbyyUsHwttqaxpmWi5YfXpXm7GcAatgtQlvdTfJwz/Image.png)

Create Corresponding Resources

```javascript
<?php

namespace App\Nova;

use Laravel\Nova\Fields\ID;
use Illuminate\Http\Request;
use Laravel\Nova\Fields\Text;
use Laravel\Nova\Fields\Boolean;
use Laravel\Nova\Fields\BelongsToMany;
use Laravel\Nova\Http\Requests\NovaRequest;

class Question extends Resource
{
    public static $model = \App\Models\Question::class;
    public static $title = 'id';
    public static $search = [
        'id',
    ];

    public function fields(NovaRequest $request)
    {
        return [
            BelongsToMany::make('Sets')
                ->fields(function ($request, $relatedModel) {
                    return [
                        Text::make('Order'),
                    ];
                }),

            ID::make()->sortable(),

            Text::make('Finding'),

            Boolean::make('Normal'),
        ];
    }
}
```


```javascript
<?php

namespace App\Nova;

use Laravel\Nova\Fields\ID;
use Illuminate\Http\Request;
use Laravel\Nova\Fields\Text;
use Laravel\Nova\Fields\BelongsToMany;
use Laravel\Nova\Http\Requests\NovaRequest;

class Set extends Resource
{

    public static $model = \App\Models\Set::class;
    public static $title = 'id';
    public static $search = [
        'id',
    ];

    public function fields(NovaRequest $request)
    {
        return [
            ID::make()->sortable(),

            BelongsToMany::make('Questions')
                ->fields(function ($request, $relatedModel) {
                    return [
                        Text::make('Order'),
                    ];
                })
        ];
    }
}


```


Open up the application and view the Sets Resource and click Set 1

![image](https://res.craft.do/user/full/2dfa1c5b-0204-ac16-f54f-2a27cbaac6d6/doc/0E0C1A87-C521-4B03-8809-C93DFA172DCD/AFA6E11D-05BD-4A7C-8E82-65A9DAAE96A4_2/fS2WIcANjSZsD7jg8pnkmyl6LAGEa1yyZGlbyiWIULsz/Image.png)

You will see that even though BelongsToMany field is first in the list, the pivot column called ORDER is positioned as the last column. 

However, if you then re-order the fields in the Question resource so that there is a field before the BelongsToMany pivot field, then it becomes appropriately positioned. It just cant for some reason be first in the list.

app/nova/Question.php

```javascript
public function fields(NovaRequest $request)
    {
        return [
            Text::make('Finding'),

            BelongsToMany::make('Sets')
                ->fields(function ($request, $relatedModel) {
                    return [
                        Text::make('Order'),
                    ];
                }),

            ID::make()->sortable(),

            Boolean::make('Normal'),
        ];
    }
```


 

![image](https://res.craft.do/user/full/2dfa1c5b-0204-ac16-f54f-2a27cbaac6d6/doc/0E0C1A87-C521-4B03-8809-C93DFA172DCD/44B0D530-ADE8-4657-8826-408C9F0FE0C9_2/9rgUSYi84U0pBJscDT2iFQuFVPfebn793zpkAIAhqnoz/Image.png)
