### ISSUE TITLE
Notification url

### ISSUE THREAD

**Issue by oskobri** [laravel/nova-issues#3975]
- Laravel Version: 9.8.1
- Nova Version: 4.1.1
- PHP Version: 8.1.0

### Description:
When using notification nova example and clicking on the notification, I am redirected to `http://localhost:8000/novahttps://example.com/report.pdf` and not `https://example.com/report.pdf`. 

It's well `https://example.com/report.pdf`in nova_notifications table.

```
use Laravel\Nova\Notifications\NovaNotification;

$request->user()->notify(
    NovaNotification::make()
        ->message('Your report is ready to download.')
        ->action('Download', 'https://example.com/report.pdf')
        ->icon('download')
        ->type('info')
);
```

**Comment by crynobone** [comment]
You should be able to pass `Laravel\Nova\URL::remote('https://...')`

**Comment by oskobri** [comment]
Ok but for internal url, it does not work.  
If I want to call `http://localhost:8000/report.pdf` or `route('nova.pages.detail', ['resource' => $resourceKey, 'resourceId' => $resourceId])` in absolute or not it will always redirect to a wrong url. Is there a way to avoid remote url when url must be internal (for a nova resource for exemple) ?

**Comment by crynobone** [comment]
Any URL outside Nova is external. Regardless if it on the same Laravel install.

**Comment by oskobri** [comment]
Ok thanks
