### ISSUE TITLE
Stacked fields are not stacked

### ISSUE THREAD

**Issue by voidgraphics** [laravel/nova-issues#3978]
- Laravel Version: 9.8.1
- Nova Version: 4.1.1
- PHP Version: 8.1.3
- Database Driver & Version: mysql 8.0.27
- Operating System and Version: MacOS Monterey 12.3.1
- Browser type and version: Brave Version 1.37.111 (Chromium: 100.0.4896.79) (Official Build) (arm64)
- Reproduction Repository: None, sorry. It's very easy to reproduce on a brand new Laravel + Nova installation.

### Description:
Following the fix to my previous issue (https://github.com/laravel/nova-issues/issues/3924) included in Nova 4.1.1, the stacked fields now look like this:

![CleanShot 2022-04-13 at 13 32 46](https://user-images.githubusercontent.com/9298484/163171328-3fc5ee87-4af7-4ada-89f7-c3bec0ec8e43.png)

I believe this is a bug as the field is supposed to display under the label. Responsive is also bugged, and also has a padding problem:

![CleanShot 2022-04-13 at 13 36 16](https://user-images.githubusercontent.com/9298484/163171825-65243b60-46e7-4ba5-b916-f3d25fac60c0.png)

### Detailed steps to reproduce the issue on a fresh Nova installation:

Simply visit the edit page of any resource that has a stacked field, e.g.: 

```php
Text::make('Title')->stacked()
```

**Comment by crynobone** [comment]
Sorry, the code missed one class during review.

**Comment by voidgraphics** [comment]
Thanks for being on it so quickly 👍
