### ISSUE TITLE
Extract dashboard footer into a partial for easier customization

### ISSUE THREAD

**Issue by neovive** [laravel/nova-issues#398]
Perhaps this is intended functionality, but there is no clear way to customize the dashboard footer. Consider separating the footer into a separate view partial or adding config options to toggle the Nova link and version number.

**Comment by activemonkeys** [comment]
Copy the \nova\resources\views\layout.blade.php file to  \resources\views\vendor\nova\layout.blade.php 

In this copied layout.blade.php file, you can separate the footer part and put it in other blade file.

**Comment by coreycoburn** [comment]
Hopefully Taylor or David can extract the footer into it's own partial so that we don't have to override the entire layout file.

**Comment by neovive** [comment]
@coreycoburn I changed the issue title to be more specific about extracting the footer into a partial.

**Comment by davidhemphill** [comment]
Ok, I extracted the footer into its own partial. This will now be published by default. Coming in next release.
