### ISSUE TITLE
Toggle for Dark/Light mode missing

### ISSUE THREAD

**Issue by StanBarrows** [laravel/nova-issues#3987]
- Laravel Version: 9.0
- Nova Version: 4.11
- PHP Version: 8.1
- Database Driver & Version:
- Operating System and Version: MacOS
- Browser type and version: Safari/Chrome (latest)

### Description:
On our updated Nova Application (3.0 => 4.0), The toggle for switching between dark & light mode is missing. Is there anything that needs to be activated? I tried it out on a fresh installation, and it worked out of the box. Compared the Core-Files for any enable/disable possibility. Also, there are no console errors present within the Logs.

![CleanShot 2022-04-14 at 01 59 31@2x](https://user-images.githubusercontent.com/10268813/163288652-327ee2a3-f66e-43d7-a918-f8d410add62d.png)

<img width="1229" alt="CleanShot 2022-04-14 at 02 01 16@2x" src="https://user-images.githubusercontent.com/10268813/163288803-9c68241b-2cbc-433e-b7e0-c0ea874fa8d7.png">

**Comment by RhysLees** [comment]
I had the same thing, adding the below into `composer.json` and then running `composer update` and `php artisan clear:cache` `php artisan view:clear` seemed to work:

```php
"scripts": {
    "post-update-cmd": [
        "@php artisan nova:publish"
    ]
}
```

**Comment by StanBarrows** [comment]
@RhysLees 

Thanks for your answer. I already have this within my composer.json file.

**Comment by StanBarrows** [comment]
Yes, I have the problem on local & staging.

The assets are not within the repo and getting generated via CI.

**Comment by RhysLees** [comment]
> not within the repo and getting generated

Share the repo and I can take a look for you

**Comment by StanBarrows** [comment]
@RhysLees 

You should have received an invite.

- The Local User Infos are stored within the following Seeder. Database\Seeders\Administration\UsersTableSeeder.php;

**Comment by RhysLees** [comment]
> @RhysLees
> 
> You should have received an invite.
> 
> * The Local User Infos are stored within the following Seeder. Database\Seeders\Administration\UsersTableSeeder.php;

Your issue was that you set the nova version as "4.0" and not "^4.0" so when you ran `composer update` you were just getting 4.0 not 4.1.1. see below for how versioning works in Composer

```json
"require": {
    "vendor/package": "1.3.2", // exactly 1.3.2 (exact)

    // >, <, >=, <= | specify upper / lower bounds
    "vendor/package": ">=1.3.2", // anything above or equal to 1.3.2
    "vendor/package": "<1.3.2", // anything below 1.3.2

    // * | wildcard
    "vendor/package": "1.3.*", // >=1.3.0 <1.4.0

    // ~ | allows last digit specified to go up
    "vendor/package": "~1.3.2", // >=1.3.2 <1.4.0
    "vendor/package": "~1.3", // >=1.3.0 <2.0.0

    // ^ | doesn't allow breaking changes (major version fixed - following semvar)
    "vendor/package": "^1.3.2", // >=1.3.2 <2.0.0
    "vendor/package": "^0.3.2", // >=0.3.2 <0.4.0 // except if major version is 0
}
```

Once I changed this and run `composer update` it works for me now seems like you have a theme on there though as dark don't change the background

![image](https://user-images.githubusercontent.com/43909932/163489070-274fe52c-3250-4df7-914c-8c781e1c43a7.png)

![image](https://user-images.githubusercontent.com/43909932/163489085-c31a806f-f497-4eea-bc26-07d50629e011.png)

**Comment by StanBarrows** [comment]
Wow awesome catch! Thank you for this!

**Comment by RhysLees** [comment]
No I don't. Not even sure how to enable it 🤣

I'll take another look to see if I can figure out what's up with the colours.

**Comment by StanBarrows** [comment]
@RhysLees 

There is a published nova folder within the vendor directory. I've deleted this and then the dark mode works!

Thanks for your help!
