### ISSUE TITLE
[4.x]translation [en.json] line 436 wrong And missing "Close'

### ISSUE THREAD

**Issue by imnpc** [laravel/nova-issues#3988]
Line 436   "There are no new notifications": "There are no new notifications",

need change to

  "There are no new notifications.": "There are no new notifications.",

And need ADD a line
  "Close.": "Close",

![nova-en-notice](https://user-images.githubusercontent.com/5801647/163302528-8ee79229-6960-4c1d-af69-feae19cec417.jpg)
<img width="298" alt="nova4-notice" src="https://user-images.githubusercontent.com/5801647/163302532-b3ef605b-74da-4c65-8a6a-1a784ff7570d.png">

**Comment by crynobone** [comment]
Fixed and will be available on next release.
