### ISSUE TITLE
Empty delete dropdown when delete disabled for resource and selecting rows

### ISSUE THREAD

**Issue by dmason30** [laravel/nova-issues#3992]
- Laravel Version: 9.7
- Nova Version: 4.1.1
- PHP Version: 8.1

### Description:
When a resource policy prevents allowing a user to delete, when you select all rows the mass delete button displays but when you click it the dropdown is empty. Probably the delete button shouldn't display?

<img width="295" alt="image" src="https://user-images.githubusercontent.com/20278756/163365732-b42bc4df-b27c-4c58-8ae0-c52ee35a47e2.png">
<img width="296" alt="image" src="https://user-images.githubusercontent.com/20278756/163365781-48cb9a0d-b840-4f43-93a5-c8f3cdcb88c7.png">

**Comment by crynobone** [comment]
Please provide full reproducing code.

**Comment by dmason30** [comment]
## Scenario 1: Policy blocks delete & Resource has export action
app/Nova/UserPolicy.php
```php
public function delete()
{
    return false;
}
```

**app/Nova/UserResource.php**
```php
class UserResource extends Resource
{
    public static $model = User::class;

    public static $title = 'name';

    public static $search = ['name', 'email'];

    public function fields(NovaRequest $request)
    {
        return [
            ID::make(__('ID'), 'id')->sortable()->hideFromIndex(),

            Text::make(__('Name'), 'name')->rules(['required', 'string']),

            Text::make(__('Email'), 'email')->rules(['required', 'email']),

            DateTime::make(__('Created At'), 'created_at')->filterable()->exceptOnForms(),

            DateTime::make(__('Updated At'), 'updated_at')->filterable()->exceptOnForms(),
        ];
    }

    public function actions(NovaRequest $request)
    {
        return [
            ExportAsCsv::make()
        ];
    }
}
```

From what I understand is when none of the rows are able to be deleted then the ability to select rows will disappear unless there are actions that require row selection.

The `ExportAsCsv` action brings that back but with the above policy you end up with the empty delete dropdown.

### Steps
**On User Index select all rows**
<img width="880" alt="image" src="https://user-images.githubusercontent.com/20278756/163393112-5e970f29-bd1b-4aa8-b111-3bd20d881148.png">
**Actions dropdown and Mass delete button appears**
<img width="876" alt="image" src="https://user-images.githubusercontent.com/20278756/163393237-ff35568c-61f8-4ca0-9761-7d0dc602c4af.png">
**Clicking the mass delete button reveals empty dropdown**
<img width="872" alt="image" src="https://user-images.githubusercontent.com/20278756/163393327-cf8c0671-d875-4dad-b1db-4cd11f60190f.png">


## Scenario 2: Policy blocks delete only for test users / Resource does not have an action
```php
public function delete(User $user)
{
    return Str::contains($user->email, 'test');
}
```

**app/Nova/UserResource.php**
```php
class UserResource extends Resource
{
    // Same as Scenario 1...
   
    public function actions(NovaRequest $request)
    {
        return [];
    }
}
```

### Steps
**On User Index select all rows**
<img width="927" alt="image" src="https://user-images.githubusercontent.com/20278756/163393816-b7aadf2c-3391-48ed-b095-61da78d142f5.png">
**Unselect rows that can be deleted**
<img width="911" alt="image" src="https://user-images.githubusercontent.com/20278756/163393920-0b985c10-4fe1-4608-88c1-615410a891ff.png">
**Click the mass delete button which shows an empty dropdown**
<img width="918" alt="image" src="https://user-images.githubusercontent.com/20278756/163393986-bd61e20d-321c-4b7e-a939-6d707f9d387d.png">
