### ISSUE TITLE
Layout: Safari renders actions improperly

### ISSUE THREAD

**Issue by parrots** [laravel/nova-issues#3997]
- Laravel Version: 9.8.1
- Nova Version: 17.8.0
- PHP Version: 8.1.4
- Database Driver & Version: Postgres 13
- Operating System and Version: macOS 12.3 (dev) / Ubuntu 20.04.4 LTS (prod)
- Browser type and version: Safari 15.4

### Description:
In Safari, actions in the dropdown are rendered more like buttons than hover items. This only happens to custom actions, built-in ones seem fine. Digging into the CSS it appears that the default ones do _not_ render with the `type="button"` attribute on the link whereas the custom actions do. Removing `type="button"` via inspector seems to fix the rendering issues.

(Safari)
<img width="360" alt="Screen Shot 2022-04-14 at 09 49 56" src="https://user-images.githubusercontent.com/171163/163427091-698700fb-c6c5-40bb-b6bd-3d500b43fbdd.png">

(Firefox)
<img width="308" alt="Screen Shot 2022-04-14 at 09 50 03" src="https://user-images.githubusercontent.com/171163/163427115-bb1c1fc4-539a-46d9-a8e9-5320e466d0b9.png">

### Detailed steps to reproduce the issue on a fresh Nova installation:
Add a custom action, view in Safari

**Comment by crynobone** [comment]
It should have been`<DropdownMenuItem as="button">` where `as` is a props to choose either `link` or `button`. 

This has been fixed and pending next release.
