### ISSUE TITLE
Layout: Heading field rendering does not match documentation

### ISSUE THREAD

**Issue by parrots** [laravel/nova-issues#3998]
- Laravel Version: 9.8.1
- Nova Version: 17.8.0
- PHP Version: 8.1.4
- Database Driver & Version: Postgres 13
- Operating System and Version: macOS 12.3 (dev) / Ubuntu 20.04.4 LTS (prod)
- Browser type and version: Safari 15.4 / Firefox 99.0

### Description:
When moving from Nova 3 -> Nova 4, the styling of `Heading` fields has changed and I believe this was an oversight. The documentation (https://nova.laravel.com/docs/4.0/resources/fields.html#heading-field) shows it should have a non-white background to provide contrast, however now it renders as a white background. This greatly reduces visibility of the header.

Authentication and Integrations are headings, with only the title specified in code and no additional customization. (ex: `Heading::make('Authentication'),`)
<img width="1166" alt="Screen Shot 2022-04-14 at 09 57 15" src="https://user-images.githubusercontent.com/171163/163428022-1262c34d-a819-450e-a6c0-cf1a71ba2a03.png">

Inspecting the HTML, the class attributes for the row's DIV match that non-header rows.

**Comment by crynobone** [comment]
PR merged, will be part of next release.
