### ISSUE TITLE
BelongsToMany fields not displaying?

### ISSUE THREAD

**Issue by webspectyler** [laravel/nova-issues#40]
I've set up the necessary pivot tables and relations, but when I use:

`BelongsToMany::make('Users'),`

...on the Resource's fields() method, the resulting form simply does not display any field for this relationship. It also does not throw any errors or Network output that I can tell. Anyone else having this issue?

**Comment by batFormat** [comment]
They are displayed only in resource details

**Comment by MattMangoni** [comment]
The belongsToMany relationship is only shown on resource details, where you can attach new models and stuff like that.

**Comment by webspectyler** [comment]
Ah, makes sense - thank you for your help!

**Comment by DominikGeimer** [comment]
Is it possible to show specific fields on the index?

**Comment by DonDiegoAA** [comment]
I understand why the belongsToMany relationship is not shown in the Create form, but this could be shown in the Edit form, no ?

**Comment by bahamagician** [comment]
I'm having the same issue of not seeing my belongstomany fields on the create/update screen.  I also thought that it's just how it worked but according to the docs, you should be able to see the belongstomany fields on the create and update screens also:

The docs say this is possible:
[https://nova.laravel.com/docs/1.0/resources/relationships.html#pivot-actions](https://nova.laravel.com/docs/1.0/resources/relationships.html#pivot-actions)

I also received a tweet from Taylor Otwell that makes it seem that it should be working:
[https://twitter.com/bahamagician/status/1034222817619791872](https://twitter.com/bahamagician/status/1034222817619791872)

**Comment by pkeogan** [comment]
@bahamagician  did you ever figure this out?

**Comment by bahamagician** [comment]
Nope.  Apparently that’s not how it works.  I decided against Nova for the project and went another direction.

**Comment by techouse** [comment]
Both models that are linked in the pivot model need to have the same fields set. Only then will the additional pivot fields be displayed in the index.

**Comment by isometriq** [comment]
Looks like I will have to use a custom checkboxes field and some hacking grease...
https://medium.com/laravel-nova/laravel-nova-select-belongstomany-relationships-using-checkboxes-62bdf710c0b4
..not elegant for sure

**Comment by php-writerman** [comment]
https://github.com/dillingham/nova-attach-many
