### ISSUE TITLE
Custom Tool's default page shows wrong path to edit Tool

### ISSUE THREAD

**Issue by WillyReyno** [laravel/nova-issues#4009]
- Laravel Version: 8.83.8
- Nova Version: 4.2.2
- PHP Version: 8.0

### Description:

When creating a tool the default page indicates that the Tool can be edited at `nova-components/ToolName/resources/js/components/Tool.vue` while it should be `nova-components/ToolName/resources/js/pages/Tool.vue`

### Detailed steps to reproduce the issue on a fresh Nova installation:

- Install Nova 4 
- Create a Tool & build Tool's assets
- Register tool in service provider
- Go to the Tool's page and see the black hole default page with message indicating the wrong path

**Comment by crynobone** [comment]
Fixed and will be part of next release
