### ISSUE TITLE
Pivot column ordering for BelongsToMany Fields still not working

### ISSUE THREAD

**Issue by jimarick** [laravel/nova-issues#4011]
Despite upgrading to 4.2.2 the pivot column ordering is still not working as expected. 

Project set up as per previous issue #3973 

I have the Question resource fields in this order:

```
 public function fields(NovaRequest $request)
    {
        return [

            BelongsToMany::make('Sets')
                ->filterable()
                ->fields(function ($request, $relatedModel) {
                    return [
                        Text::make('Order'),
                    ];
                }),

            Text::make('Finding'),

            ID::make()->sortable(),

            Boolean::make('Normal'),
        ];
    }
```

However when displayed in the related resource, the pivot field (called Order) is last in the list, rather than first:

<img width="1250" alt="Screenshot 2022-04-16 at 08 43 35" src="https://user-images.githubusercontent.com/67220144/163666648-592e87c1-01f5-4d6d-a6f0-55197475fb81.png">

If I put the pivot field second or third in the list, it works as expected, just not first.

**Comment by crynobone** [comment]
Fixed via https://github.com/laravel/nova/commit/d4462a1412c1c04c6d4606b2c11708cef2699fc2
