### ISSUE TITLE
Searchable not working in BelongsToMany when Attaching on Nova 4

### ISSUE THREAD

**Issue by neleid** [laravel/nova-issues#4025]
- Laravel Version: 9.8.1
- Nova Version: 4.2.2
- PHP Version: 8.1.4
- Database Driver & Version: MariaDB 10.7.3
- Operating System and Version: Laravel Sail
- Browser type and version: Safari, Chrome

### Description:
This issue is as same as below.
https://github.com/laravel/nova-issues/issues/2311

`The BelongsToMany is now searchable.`
https://nova.laravel.com/releases/3.8.0

Is this feature deleted from Nova 4?

**Comment by crynobone** [comment]
Unable to reproduce, please submit reproducing repository.

**Comment by crynobone** [comment]
@NowakAdmin your issue has been confirmed due to running on an outdated asset, run `php artisan nova:publish` to fix your issue. Which is not related to this bug report.
