### ISSUE TITLE
Currency Field Not Submitting

### ISSUE THREAD

**Issue by anthony-brindley** [laravel/nova-issues#4028]
- Laravel Version: 9.8.1
- Nova Version: 4.2.2
- PHP Version: 8.0.2

### Description:
Currency field not submitting it's value on form submission. Here's a video showing what's happening: https://www.dropbox.com/s/d6spnjmy3jpjswu/chrome_2022-04-18_14-43-35.mp4?dl=0

### Detailed steps to reproduce the issue on a fresh Nova installation:

- Fresh install of Laravel
- Install Nova
- Create a Test model with a string db column
- create a nova resource for your model
- Add a currency field that inserts a value into your db column
- Ensure fillable is set appropriately
- Add a 'creating' model event and capture/dump the data that will be submitted into the database
- Open dev tools and view the network tab
- Enter a value and Submit the form
- Inspect the highlighted request response
- you'll see that the value for the field you submitted is null
- Go back to your resource and change the currency field to a text one
- resubmit the form
- check dev tools and you'll see that the value you submitted is being received ok now.....

**Comment by crynobone** [comment]
Please submit reproducing repository similar to https://github.com/nova-issues as we already have Dusk Tests regarding submitting Currency field value without issues.
