### ISSUE TITLE
BelongsTo field on Action doesn't find correct field

### ISSUE THREAD

**Issue by alexbowers** [laravel/nova-issues#403]
```
public function fields()
    {
        return [
            BelongsTo::make('Branding')->searchable(),
        ];
    }
```

I get the error cannot find `Class 'App\\Nova\\Actions\\Branding' not found` however I am unable to put a full class path in there because it assumes that I am working from the current namespace.

How do i go about having a BelongsTo field in an action, and can it be made so that a FQN is valid, so that I can use `Branding::class` instead?

**Comment by jonrmitchell** [comment]
This seems to be the same problem as #145 and there's a workaround there (pre-populating a dropdown - won't fit every use case but it's an option). I have the same need too, "actions that can do lookups", but it doesn't appear to be supported yet.

**Comment by BobbyBorisov** [comment]
@jonrmitchell in the 145 thread there is a solution but does not work, i don't why, have you tried it?

**Comment by dkulyk** [comment]
Actions doesn't support relations.

**Comment by BobbyBorisov** [comment]
@dkulyk too bad, i hope they include that feature in next releases. Cheers
