### ISSUE TITLE
Multi-columns relationships sorting issues

### ISSUE THREAD

**Issue by egantz** [laravel/nova-issues#4032]
- Laravel Version: 9.8.1
- Nova Version: 4.2.2
- PHP Version: 8.1.5
- Database Driver & Version: MySQL 8.0.23
- Operating System and Version: macOS Monterey 12.4 Beta (21F5048e)
- Browser type and version: Google Chrome 100.0.4896.88 (Official Build) (arm64)
- Reproduction Repository: https://github.com/###/###

### Description:

When using a `BelongsTo` field that has a composite-relationship (using the wonderful package Compoships: https://github.com/topclaudy/compoships) it actually takes the array and try to use it as the sort since the foreign key is an array, it fails claiming: 

`Column not found: 1054 Unknown column 'account_id,store_id,po_number' in 'order clause' at ...`

The generated URL is:
`/?orders_order=account_id%2Cstore_id%2Cpo_number&orders_direction=asc`

Would love to have the ability to maybe override the sortable column? I am unsure how to bypass this while I do need the field to be clickable and send to the right resource (which it does) but fails to make the proper sorting.

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Create a model relationship of BelongsTo that has a composite-relationship (multi column)
![CleanShot 2022-04-18 at 22 23 11](https://user-images.githubusercontent.com/4982233/163907505-5696275d-cfe5-47d4-91ce-e32b3ca78383.jpg)

2. Add a BelongsTo field to a Nova resource that will use that composite-relationship and make sure that field has `->sortable()`
![CleanShot 2022-04-18 at 22 23 37](https://user-images.githubusercontent.com/4982233/163907569-da35a554-ae9a-4e26-9afd-33b95469bfb4.jpg)

3. Try to click on the header of that column to sort it
![image](https://user-images.githubusercontent.com/4982233/163907616-43d1cf49-78dd-4adf-802b-dca0faa1991c.png)

**Comment by crynobone** [comment]
You need to create custom Field to support 3rd party feature.
