### ISSUE TITLE
403 Error Page "Go Home" Link not redirecting to home page

### ISSUE THREAD

**Issue by dev3k** [laravel/nova-issues#4039]
- Laravel Version: 9.8.1
- Nova Version: 4.2.2
- PHP Version: 8.1.2
- Database Driver & Version:
- Operating System and Version: macOs bigSur 11.6.5
- Browser type and version: Chrome  100.0.4896.127 
- Reproduction Repository: https://github.com/###/###

### Description:
invalid home url in 403 page 

### Detailed steps to reproduce the issue on a fresh Nova installation:
after login with email not defined in ViewNova gate , user gets redirected to 403 with link to home page that leads to /nova/dashboards/main instead of /

```
Gate::define('viewNova', function ($user) {
            return in_array($user->email, [
                //
                'admin@gmail.com'
            ]);
        });
```

**Comment by crynobone** [comment]
This change request is logical if `403` is shown due to `viewNova`, but it would be invalid if user just doesn’t have access to specific resource.

**Comment by dev3k** [comment]
yah makes sense , thanks
