### ISSUE TITLE
BelongsTo relation still guesses snake_case instead of camelCase

### ISSUE THREAD

**Issue by sebsel** [laravel/nova-issues#4043]
- Laravel Version: 9.8.1
- Nova Version: 4.2.2
- PHP Version: 8.1.1

### Description:

The [update guide](https://nova.laravel.com/docs/4.0/upgrade.html#relationship-name-conventions) states that Nova has updated how to look for relationships that are named with multiple words (no longer `product_categories` but `productCategories`, as is the convention in Laravel).

This indeed works for all relationships I came across, but not for BelongsTo: it still seeks for the snake_cased version there.

When I compare `Laravel\Nova\Fields\BelongsTo` to `Laravel\Nova\Fields\BelongsToMany`, I see the difference:

`src\Fields\BelongsTo.php` line 119:
```
$this->belongsToRelationship = $attribute ?? ResourceRelationshipGuesser::guessRelation($name);
```

`src\Fields\BelongsToMany.php` line 104:
```
$this->manyToManyRelationship = $this->attribute = $attribute ?? ResourceRelationshipGuesser::guessRelation($name);
```

... adding the `$this->attribute =` to the BelongsTo seems to solve the issue.

**Comment by crynobone** [comment]
Fixed and will be available on the next release (after the current 4.2.3 version).
