### ISSUE TITLE
Dependent Field with `readonly()` toggle is not saving/updating

### ISSUE THREAD

**Issue by Nks** [laravel/nova-issues#4045]
- Laravel Version: v9.9.0
- Nova Version: 4.2.3
- PHP Version: 8.0.17
- Database Driver & Version: mariadb:10.4
- Operating System and Version: MacOS 12.1
- Browser type and version: Chrome Version 100.0.4896.88 (Official Build) (arm64)

### Description:
When using the BelongsTo field and the dependsOn method, the field is not saved. If dependsOn is not used, everything works as expected.

### Detailed steps to reproduce the issue on a fresh Nova installation:

```php
Boolean::make('Is Geo Restricted')
                ->default(false),

            BelongsTo::make('Location')
                ->readonly()
                ->dependsOn(
                    ['is_geo_restricted'],
                    function (BelongsTo $field, NovaRequest $request, FormData $formData) {
                        if ($formData->is_geo_restricted) {
                            $field->readonly(false)->rules('required');
                        }
                    }
                ),
```

https://user-images.githubusercontent.com/349293/164112613-787b2293-1186-4d54-81dc-c0eeb4ed608e.mov

**Comment by Nks** [comment]
Temporary solution:

```php
BelongsTo::make('Location')
    ->rules(function ($request) {
        if ($request->is_geo_restricted) {
            return ['required'];
        }

        return [];
    }),
```

`required_if` doesn't work either.

**Comment by josespinal** [comment]
Hi, was this issue closed because it got resolved? I'm experiencing something similar. 

If I use the readOnly() method and enable the field using dependsOn() (as docs show) the field's value won't pass to an Observer (creating, updating, updated and created methods).
