### ISSUE TITLE
Error for null Markdown field

### ISSUE THREAD

**Issue by bradders** [laravel/nova-issues#405]
I have a Markdown field, which is attached to a nullable TEXT column on my database, and I'm seeing the following error when the value is null (on the detail page):

`[Vue warn]: Error in render: "Error: Input data should be a String"` found in `<DetailMarkdownField> at resources/js/components/Detail/MarkdownField.vue`

When I switch to a Trix field this error goes away. My Nova field pegs the field as nullable:
`Markdown::make("Comment", "comment")->rules("nullable"),`

Only on the detail page, though. Marking the field as `onlyOnDetail()` removes this problem, but I'd ideally like to see this field on the detail.

Any clues?

**Comment by rovansteen** [comment]
As a workaround for now you could add this to your model:

```php
class YourModel extends Model {

    //

    public function getCommentAttribute($attribute)
    {
        if (is_null($attribute)) {
            return '';
        }

        return $attribute;
    }
}
```

But would be nice if this could be fixed so that is not necessary.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in an upcoming release.
