### ISSUE TITLE
Squared images like Avatar or Image are still rounded on table list view.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [laravel/nova-issues#4052]
- Laravel Version: 9.9.0
- Nova Version: 4.2.3
- PHP Version: 8.1.3
- Database Driver & Version: pgsql
- Operating System and Version: who knows honestly it's docker sail.
- Browser type and version: Google Chrome

### Description:

Images that are marked as squared are still rounded on table view.
Probably not a big deal breaker though not what I specified, maybe some methods like this would be good?

->squaredOnIndex()
->roundedOnIndex()

rounded-full overflow-hidden

Example HTML when squared.
```html
<div class="rounded-full overflow-hidden">
    <img src="http://localhost:5550/storage/o5L3FEcpo55iFQVsjPp9yRA4Eo0uCGLyP16kk0Vt.jpg" draggable="false">
</div>
```

### Detailed steps to reproduce the issue on a fresh Nova installation:

Make resource and migration accordingly.

```php
<?php
// ...
            Avatar::make('Logo Image', 'logo_image')
                ->disk('public')
                ->path('images')
                ->storeOriginalName('logo_name')
                ->storeSize('logo_size')
                ->squared()
                ->prunable(),
```

```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateBrandsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('brands', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->timestamps();
            $table->softDeletes();

            // Logo Image for Brand.
            $table->string('logo_image')->nullable();
            $table->string('logo_name')->nullable();
            $table->string('logo_size')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('brands');
    }
}

```

**Comment by macorredor** [comment]
My apologies, but square images still don't work in Laravel Nova 2.4.5.

`
            Image::make(__('Imagen'), 'src')
                ->squared()
                ->disk('public')
                ->showOnPreview()
                ->rules('required'),
`
`
<div class="rounded-full overflow-hidden">
  <img src="https://localhost:8000/storage/oR6WG5uXwps8LCuUHHyKjOzWqR1FXrUgNrwP7g8y.png" draggable="false">
</div>
`

**Comment by LiamKarlMitchell** [comment]
Yeah they still have the rounded class on them.

Looks like this
![image](https://user-images.githubusercontent.com/1968109/164715293-570a377e-cb71-45c0-85f6-f6cb6e4fbb26.png)

I would think that it should be able to look like this as an option.
![image](https://user-images.githubusercontent.com/1968109/164715280-8fa06440-19f5-4e51-8149-4a48f82b1ca8.png)

**Comment by crynobone** [comment]
@macorredor run `php artisan nova:publish` to update your assets.

@LiamKarlMitchell below are the expected behavior copied from Nova 3.

![image](https://user-images.githubusercontent.com/172966/164717130-bdc7bf6f-38a2-4be9-b9fc-076e41bfd3f9.png)

**Comment by macorredor** [comment]
@crynobone Thank you very much! This works for me. I am a newbie in Nova.

**Comment by LiamKarlMitchell** [comment]
Ah okay sorry, maybe its just my understanding but I thought they would be square not rounded corners.

**Comment by macorredor** [comment]
@LiamKarlMitchell You can add a custom css file, in this file you can change the style definition and remove the border radius.
[Here](https://stackoverflow.com/questions/52607189/laravel-nova-include-additional-css-files) you have more information.

**Comment by LiamKarlMitchell** [comment]
Thanks @macorredor , seems like a suitable work around for now but it could be an issue for people who want to have rounded in some places like for User avatar images but square in others.
