### ISSUE TITLE
An issue with the "BelongsTo" field with the dependsOn field.

### ISSUE THREAD

**Issue by cloudifyapps-samir** [laravel/nova-issues#4053]
- Laravel Version: 8.83.9
- Nova Version: 4.2.3
- PHP Version: 8.0.8
- Database Driver & Version: Mysql
- Operating System and Version: Mac 
- Browser type and version: Chrome and 100.0.4896.127

### Description:
We are facing an issue when trying to create the "dependsOn" field of a "BelongsTo" field.
 Ex: So there are two tables i.e classes and sections, as each class can have multiple sections such as A,B,C & D. 
So now create a BelongsTo field for class-'field' and when the user chooses different classes different associated section values for each class must appear.

**Comment by crynobone** [comment]
Please create reproducing repository to demonstrate your issue similar to https://github.com/nova-issues

**Comment by juse-less** [comment]
A bit of a long-shot, but.. @cloudifyapps-samir do you mean that the second `BelongsTo` don't update the data correctly?
I noticed an issue where `Currency::dependsOn()` on a `BelongsTo` doesn't update.
Originally I tried setting the currency directly from the value of the `BelongsTo`, i.e.
```php
// InvoiceLineItem.php

[
    BelongsTo::make(__('Invoice'), attribute: 'invoice', resource: Invoice::class),
    Currency::make(__('Unit Price'), attribute: 'unit_price')
        // Fairly certain I did something like this in Nova 3 (calling a Resource' attributes), albeit not with Currency.
        // This will, at least now, throw an Exception that I can't call currency on null.
        ->currency($this->invoice->currency),
]
```

What I tried instead is
```php
// InvoiceLineItem.php

[
    BelongsTo::make(__('Invoice'), attribute: 'invoice', resource: Invoice::class),
    Currency::make(__('Unit Price'), attribute: 'unit_price')
        ->dependsOn(['invoice'], function (Currency $field, NovaRequest $request, FormData $data): void {
            $field->currency($data->get('invoice'))?->currency;
        }),
]
```

But no dice. I've tried both `return`ing the `$field`, and even tried `dump()` inside of `Currency::dependsOn()`.
`dump()` never shows up anywhere either.

**Comment by crynobone** [comment]
`$data->get('invoice')` will return the ID of `invoice`, not an instance of eloquent.

**Comment by juse-less** [comment]
Ahh. I see! Thanks for the clarification. Then it wouldn't have worked for me, regardless.
I'll have to figure out another way for my use-case. :)

But like I said, not even `dump()` (neither `Log::info()`) in the callback shows up anywhere.
So seems like it's not called.

**Comment by crynobone** [comment]
@juse-less please submit new issue for your problem. This is hijacking @cloudifyapps-samir issue.
