### ISSUE TITLE
Field HasOneThrough not display output column

### ISSUE THREAD

**Issue by massimodellarovere** [laravel/nova-issues#4055]
Laravel Version: 9.9.0
Nova Version: 4.2.3
PHP Version: 8.1.4
Database Driver & Version: MYSQL 5.7
Operating System and Version: Ubuntu 20.04.4 LTS
Browser type and version: Brave Versión 1.37.116 Chromium: 100.0.4896.127 (64 bits)

Field HasOneThrough not display output column

### Model Relation
```php
function user()
{
  return $this->hasOneThrough(
    User::class,Order::class,'id','id','order_id','user_id');
}
```
### Laravel Nova Resource (example second column)
```php
HasOneThrough::make(__('labels.user'),'user',User::class),
```
### Output table ignore column with field definition

![image](https://user-images.githubusercontent.com/5731295/164277321-5676c4c2-797e-40ec-91fb-fa04396aefa4.png)

**Comment by crynobone** [comment]
`HasOneThrough` should only be shown from Detail page and not from Index. Only `BelongsTo` and `MorphTo` are visible from Index.

**Comment by massimodellarovere** [comment]
I thought HasOneThrough returns only one relation, it worked as a BelongsTo and directly showed the value as a field instead of a one line list. But I saw that even if the model has a HasOneThrough relationship I can use the nova "Field" with BelongsTo and it works fine. Thank you for your answer....

```php
function user()
{
  return $this->hasOneThrough(
    User::class,Order::class,'id','id','order_id','user_id');
}
```
```php
BelongsTo::make(__('labels.user'),'user',User::class),
```
