### ISSUE TITLE
displayUsingLabels() not working with action fields

### ISSUE THREAD

**Issue by albalooshi** [laravel/nova-issues#406]
it looks displayUsingLabels() isn't working if used within action fields

```
return [Select::make('Type')->options([ 'Type Zero' => 0,'Type One' => 1, 'Type 2' => 2])
                             ->displayUsingLabels()];
```

![screen shot 2018-09-03 at 9 23 18 am](https://user-images.githubusercontent.com/13213888/44970576-0bd20c80-af5b-11e8-93eb-8755e64363cc.png)

**Comment by albalooshi** [comment]
My bad.

**Comment by otrsw** [comment]
Hi there is this still a valid issue? I find the same behaviour

**Comment by albalooshi** [comment]
@otrsw just switch they key and value positions
`return [Select::make('Type')->options([ 'KEY' => 'LABEL HERE'])
                             ->displayUsingLabels()];

**Comment by brada1703** [comment]
I have tried the example from the documentation, and it still does not work.

```
Select::make('Size')->options([
    'S' => 'Small',
    'M' => 'Medium',
    'L' => 'Large',
])->displayUsingLabels(),
```

I needed to rename the label, i.e.

```
Select::make('Shirt Size', 'shirt_size')->options([
    'S' => 'Small',
    'M' => 'Medium',
    'L' => 'Large',
])->displayUsingLabels(),
```
Then, on the resource page, it still shows the key and not the label.
