### ISSUE TITLE
DependsOn method in Select field throw js error

### ISSUE THREAD

**Issue by jaraj91** [laravel/nova-issues#4063]
- Laravel Version: 9.9.0
- Nova Version: 4.2.3
- PHP Version: 8.1.5
- Database Driver & Version: mysql & MySQL 8.0.27
- Operating System and Version: mac OS 12.3.1 
- Browser type and version: Brave 1.37.116 
- Reproduction Repository: private

### Description:
When I use the 'dependsOn' method on a select field, the following error is thrown in the browser every time the parent field is updated:

Uncaught (in promise) TypeError: this.selectedOption is not a function
    at Proxy.onSyncedField (SelectField.vue:175:12)
    at DependentFormField.js:123:16

### Detailed steps to reproduce the issue on a fresh Nova installation:
```php
Select::make(__('Region'), 'region_id')
        ->options(function () {
            return Region::pluck('name', 'id');
        })
        ->rules('required'),

Select::make(__('Commune'), 'commune')
        ->options([])
        ->dependsOn('region_id', function(Select $field, NovaRequest $request, FormData $formData) {
            return $field->options(Commune::where('region_id', $formData['region_id'])->pluck('name', 'id'));
        })
        ->rules('required')
```

**Comment by crynobone** [comment]
`Commune::where('region_id', $formData['region_id'])` what happened when `region_id` is `null`? 

Please provide reproducing repository similar to https://github.com/nova-issues so we can debug this issue.

**Comment by crynobone** [comment]
Fixes and pending next release.

**Comment by jaraj91** [comment]
ok thanks

**Comment by jaraj91** [comment]
Hi, i test de new release (v4.2.4) with the same code and now throw the next js error:
SelectField.vue:124 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'value')
    at Proxy.selectOption (SelectField.vue:124:27)
    at Proxy.onSyncedField (SelectField.vue:175:12)
    at DependentFormField.js:123:16
