### ISSUE TITLE
Laravel Nova 4 not respect sequence Field defined as HasMany

### ISSUE THREAD

**Issue by massimodellarovere** [laravel/nova-issues#4064]
Laravel Version: 9.9.0
Nova Version: 4.2.3
PHP Version: 8.1.4
Database Driver & Version: MYSQL 5.7
Operating System and Version: Ubuntu 20.04.4 LTS
Browser type and version: Brave Versión 1.37.116 Chromium: 100.0.4896.127 (64 bits)

### In laravel 3 the sequence definition field is same output field after update Nova 4 Hasmany not display as first element but last element in the footer page..

```php
public function fieldsForDetail(NovaRequest $request) 
{
  return [
    HasMany::make(__('labels.products'),'items',Product::class),
    BelongsTo::make(__('labels.user'),'user',User::class),
    Heading::make(Str::upper(__('labels.qty'))),
  ];
}
```
OUTPUT NOVA 3 IS CORRECT
![image](https://user-images.githubusercontent.com/5731295/164350130-90722881-2ff7-48af-8670-8e0f471f2980.png)

OUTPUT NOVA 4 IS NOT DISPLAYED AS FIRST ELEMENT
![image](https://user-images.githubusercontent.com/5731295/164350214-ec5f40c6-4142-4f92-9c10-745b9fc64391.png)

BUT DISPLAYED AS LAST ELEMENT
![image](https://user-images.githubusercontent.com/5731295/164350271-2ebffe47-7a9c-4ae5-871a-21b844284194.png)

**Comment by crynobone** [comment]
Expected behaviour in Nova 4. From the screenshot you will see that the main panel containing Edit and Action has been pushed down after HasMany relationship which cause bad UX.
