### ISSUE TITLE
Icon color (black) date time with dark theme

### ISSUE THREAD

**Issue by massimodellarovere** [laravel/nova-issues#4074]
Laravel Version: 9.9.0
Nova Version: 4.2.3
PHP Version: 8.1.4
Database Driver & Version: MYSQL 5.7
Operating System and Version: Ubuntu 20.04.4 LTS
Browser type and version: Brave Versión 1.37.116 Chromium: 100.0.4896.127 (64 bits)

### Description:
Icon color (black) date time with dark theme

![image](https://user-images.githubusercontent.com/5731295/164497266-fff068e1-0a2f-493b-8eba-d1fcc4648df3.png)

**Comment by crynobone** [comment]
Unfortunately that is a native icon provided by the browser and is different on each browser.

**Comment by massimodellarovere** [comment]
I would add the CSS command color-scheme or ::-webkit-calendar-picker-indicator

```css
element.style {
    color-scheme: dark;
}
```
![image](https://user-images.githubusercontent.com/5731295/164506164-52d66688-9f2e-4a1c-8b30-511f92ff1588.png)
