### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by MiliChang** [laravel/nova-issues#4079]
- Laravel Version: 9.9.0
- Nova Version: 4.2.5
- PHP Version: 8.1.4
- Database Driver & Version: 
- Operating System and Version: #.#
- Browser type and version: Chrome 100.0.4896.127
- Reproduction Repository: https://github.com/###/###

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. I create a resource which is named Notification in Nova
`php artisan nova:resource Notification`

2. When I go to Resource->Notification page and stay for a while, I got an error, and the page will turn to empty until I rename app/Nova/Notification.php to NotificationXXXX.php.
![image](https://user-images.githubusercontent.com/18565358/164612085-99923074-9f10-4405-839c-f0d844a042ab.png)

Does it mean that "Notification" is one of the reserved resource name?

**Comment by crynobone** [comment]
Unable to reproduce, see https://github.com/nova-issues/issue-4079/commit/b0243ea67ce9c6b2a8f37be660fdda364fb72204

![image](https://user-images.githubusercontent.com/172966/165002670-0babaebf-8fc8-41bb-8b35-7ea8c967614a.png)

**Comment by zedix** [comment]
@crynobone I got the same issue with a resource called `Notifications` (resources/notifications), even with no fields.

A js error appear after the perodical call to `nova-api/nova-notifications` and the page becomes _blank_.

![image](https://user-images.githubusercontent.com/27975/165926678-301bddf7-08f2-438d-b546-206f7bba27f8.png)

![image](https://user-images.githubusercontent.com/27975/165926706-55c238e8-9159-4d4d-b11f-ce060a0bc01d.png)

Renaming the Resource from `Notifications` to `NotificationsXxx` seems to resolve the issue.
