### ISSUE TITLE
In Nova 4.2.4, DateTime::displayUsing() started throwing an error when the value is null

### ISSUE THREAD

**Issue by juse-less** [laravel/nova-issues#4080]
- Laravel Version: 9.9.0
- Nova Version: 4.2.4+
- PHP Version: 8.1.5
- Database Driver & Version:
   - MySQL 5.7
   - MySQL 8.0
- Operating System and Version:
   - macOS 12.3.1 (client)
   - AlmaLinux 8.5 (server)
- Browser type and version:
   - Brave Version 1.37.116 Chromium: 100.0.4896.127 (Official Build) (x86_64)
   - Firefox 99.0.1

### Description:
Nova 4.2.4 seems to have introduced a bug where `DateTime` fields throws `Call to a member function toRfc850String() on null`, when using the `displayUsing()` method, if the value is `null`.
Even if the field is marked as `nullable()`.
Commenting out `displayUsing()`, and letting Nova itself format the datetime, it correctly shows the field as `null`.

More specifically, this is thrown in the `DateTime::resolveUsingDisplayCallback()` method.
```php
$this->originalValue = $value->toRfc850String();
```

### Detailed steps to reproduce the issue on a fresh Nova installation:
In this case I used a default Laravel app, and just added a `DateTime` for the default User `email_verified_at` field.
Both the index and detail view throws the error.

**Comment by ziming** [comment]
I suppose you can do something like this?

```php
DateTime::make('created_at')
            ->displayUsing(fn (?CarbonInterface $date) => $date?->toRfc850String());
```

**Comment by juse-less** [comment]
Unfortunately not. This is within Nova this happens.
I've tried using both `DateTime::resolveUsing()` and DateTime::displayUsing()`, with and without each other.
```php
DateTime::make(__('Ended At'), attribute: 'ended_at')
    ->displayUsing(fn (CarbonInterface|null $endedAt): string|null => $endedAt?->toDateTimeString('minute'))
    ->nullable()
```

Doesn't work. As soon as I use either `resolveUsing()` or `displayUsing()`, the method I mentioned above is being called.
And it doesn't respect `nullable()` values.
I did try to quickly follow where it's actually happening, but didn't have the time right now.
For the time being I replaced it with a `Text` field that displays the value.

**Comment by mehrancodes** [comment]
Why this issue is closed without a right answer?

**Comment by jakelehner** [comment]
@crynobone I believe this one was closed in error

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
