### ISSUE TITLE
Laravel Nova 4 Field KeyValue Color Problem With  Dark Theme

### ISSUE THREAD

**Issue by massimodellarovere** [laravel/nova-issues#4085]
Laravel Version: 9.9.0
Nova Version: 4.2.3
PHP Version: 8.1.4
Database Driver & Version: MYSQL 5.7
Operating System and Version: Ubuntu 20.04.4 LTS
Browser type and version: Brave Versión 1.37.116 Chromium: 100.0.4896.127 (64 bits)

![image](https://user-images.githubusercontent.com/5731295/164867872-244a3bb1-f5df-4c85-9370-edf893bf7d44.png)

**Comment by ibrunotome** [comment]
@crynobone @davidhemphill could the text be more whiter?

<img width="577" alt="Screen Shot 2022-05-05 at 21 57 01" src="https://user-images.githubusercontent.com/4256471/167049803-a343dd7a-42b7-464a-a31a-33960a5de65f.png">

**Comment by davidhemphill** [comment]
I'm not seeing that on the latest version:

<img width="491" alt="image" src="https://user-images.githubusercontent.com/58970/167050211-fbaae2a4-2131-4000-b951-2d020248585f.png">

**Comment by ibrunotome** [comment]
@davidhemphill appears to be only on Safari. My example in chrome looks like yours.
