### ISSUE TITLE
404 Exception when trying to delete field

### ISSUE THREAD

**Issue by jameslkingsley** [laravel/nova-issues#409]
I'm trying to setup field deletion on a [custom field](https://github.com/jameslkingsley/nova-media-library-field) but when it fires off the delete request it comes back with a 404 exception (`Symfony\Component\HttpKernel\Exception\NotFoundHttpException`). This seems to be because it's looking for the field on the model and if not found throws this exception.

This doesn't fit well with custom fields that aren't representing a field on the model, but instead representing an entirely different model - in my case it's representing a media model instance from [spatie/laravel-medialibrary](https://github.com/spatie/laravel-medialibrary).

To support this I think it would be best to add a property to the field class indicating whether to validate the field name or not. Some examples below:

**Using the custom field:**
```php
// Logo is not a real field on the model, it's just used as a label
MediaLibraryField::make('Logo')
    ->usingConversion('thumb')
    ->preservingOriginal()
    ->toMediaCollection('logo')
```

**The custom field class:**
```php
class MediaLibraryField extends Field implements DeletableContract
{
    use Deletable;

    /**
     * Indicates whether to validate the field name.
     *
     * @var boolean
     */
    protected $validateFieldName = false;

    ...
}
```

**Comment by shirshak55** [comment]
+1

**Comment by shirshak55** [comment]
Waiting for it to be fixed :)

**Comment by davidhemphill** [comment]
There will likely be no plans to implement this feature.
