### ISSUE TITLE
Customizing Thumbnails Issue

### ISSUE THREAD

**Issue by tschmidiger** [laravel/nova-issues#41]
When trying to customize the thumbnail URL generation method, $this->value is empty because $this refers to the current resource model and not the field class.

```
Image::make('Profile Photo')
    ->disk('public')
    ->thumbnail(function () {
        return $this->value
                    ? Storage::disk($this->disk)->url($this->value)
                    : null;
})
```

As a work-around I just replaced $this->value with $this->image which refers directly to the column name of the resource model.

**Comment by devmsh** [comment]
That's right, the docs need to be updated.

You can access the value using `$this->value` only within the `preview` override function within the `Field` classes, but if you override it in the `Resource` this will not work and you must use the column name as you do.

**Comment by dkulyk** [comment]
In next release the value and disk properties will be pass to callback.
```php
->thumbnail(function ($value, $disk) {
    return Storage::disk(value)->url($disk);
})
```

**Comment by jBOKA** [comment]
@davidhemphill The docs need updating. I also had to check the issues to get past this.

**Comment by dillingham** [comment]
@jBOKA maybe open a issue on https://github.com/laravel/nova-docs/issues detailing what needs to be updated in the docs / your workaround

**Comment by jBOKA** [comment]
Created PR: https://github.com/laravel/nova-docs/pull/123
