### ISSUE TITLE
MorphOne dosn't work on edit 

### ISSUE THREAD

**Issue by oskobri** [laravel/nova-issues#4102]
Laravel Version: 9.7.0
Nova Version: 4.1.0
PHP Version: 8.1.0
Database Driver & Version: Mysql 8

### Description:
This bug is not resolved. On the edit page, the bug still exist.
https://github.com/laravel/nova-issues/issues/3948

**Comment by crynobone** [comment]
@oskobri Can you submit a reproducing code that isn't recursive dependencies? User required Author and Author require User. It's impossible to create User or Author on that app.

**Comment by oskobri** [comment]
I don't understand, isn't the purpose of using morphOne et morphTo relationships ?

**Comment by majomajki** [comment]
I have the same issue. I found a solution on how to work around it.
You need to replace `MorphOne` field to `HasOne` in `fields()` function in you nova resource like this:
from:

    public function fields(NovaRequest $request)
    {
        return [
            ID::make()->sortable(),
            Text::make('Title')->sortable(),
            MorphOne::make('Seo', 'seo', Seo::class),
        ];
    }

to:

    public function fields(NovaRequest $request)
    {
        $seoData['seo'] = $request->get('seo');
        unset($seoData['seo']['seoable']);
        $request->merge($seoData);

        return [
            ID::make()->sortable(),
            Text::make('Title')->sortable(),
            HasOne::make('Seo', 'seo', Seo::class),
        ];
    }

It should help.

BTW 
Probably MorphOne is not handled on Vue side. In the vendor `RelationshipPanel.vue` file there is a condition like this:
    
    relationId() {
      if (this.field.relationshipType === 'hasOne' ) {
        return this.field.hasOneId
      }
    },

and probably it should be:

    relationId() {
      if (this.field.relationshipType === 'hasOne' || this.field.relationshipType === 'morphOne') {
        return this.field.hasOneId
      }
    },
but it helps only with displaying the form, saving is still not possible.

**Comment by stonkeep** [comment]
![image](https://user-images.githubusercontent.com/3990028/169400529-e57f2c31-9953-4b58-b1b3-b9fc32edf01d.png)
This is de telescope screen is calling "undefined" id.

this is my code
`MorphOne::make('Endereço', 'endereco', Endereco::class),`

**Comment by mbardelmeijer** [comment]
We're running into this issue as well. Wondering what the status of this issue is. Is anything else needed to be able to reproduce this?

**Comment by Nks** [comment]
Same issue here. Is there any update on the bug?

**Comment by crynobone** [comment]
PR has been merged and pending next release.

**Comment by gepopp** [comment]
With the 4.9.0 release the loading error on the edit screen is fixed but there is still a bug on the create screen, its not resolving the type and id colums but trys to insert in one column with the morph name.

**Comment by crynobone** [comment]
@gepopp I already submit a bugfix based on your other report #4444 

The PR has been merged and pending the next release.
