### ISSUE TITLE
dependsOn on Code Field throw JS error

### ISSUE THREAD

**Issue by tonyyb** [laravel/nova-issues#4105]
- Laravel Version: 9.8.1
- Nova Version: 4.2.5
- PHP Version: 8.1
- Database Driver & Version: Mysql 5.7
- Operating System and Version: Mac M1
- Browser type and version: Firefox 99.0.1

### Description:

I want to hide / show a Code field based on a select value => a JS error is thrown and the codemirror library is not initialized on the cibled textearea.

![nova-error](https://user-images.githubusercontent.com/11064382/165090062-fce05d64-77aa-4098-a304-7c7ca295f0d2.gif)

### Detailed steps to reproduce the issue on a fresh Nova installation:

```php
Select::make('Type', 'link_type')
    ->options(
        [
            1 => 'A',
            2 => 'B',
        ]
    )
    ->displayUsingLabels()
    ->rules('required')
    ->onlyOnForms(),

Code::make('HTML code', 'html')
    ->dependsOn(
        ['link_type'],
        function (Code $field, NovaRequest $request, FormData $formData) {
            if ($formData->link_type !== 1) {
                $field->hide();
            }
        }),
```

**Comment by crynobone** [comment]
Similar issue with #4089
