### ISSUE TITLE
Bug with attaching models when BelongsToMany

### ISSUE THREAD

**Issue by chelev** [laravel/nova-issues#4119]
- Laravel Version: 8
- Nova Version: 4.2.3

### Description:
Upgrading nova from 4.2.2 to 4.2.3 is bringing an error when trying to attach models from BelongsToMany Relationships

Full Track can be found in here.
https://flareapp.io/share/Vmerd19P#F64

**Comment by crynobone** [comment]
Please run `php artisan nova:publish`

https://nova.laravel.com/docs/4.0/installation.html#updating-nova-s-assets

**Comment by chelev** [comment]
It works. Thanks.
