### ISSUE TITLE
Can't resolve 'form-backend-validation'

### ISSUE THREAD

**Issue by stonkeep** [laravel/nova-issues#4123]
- Laravel Version: 4
From [https://nova.laravel.com/docs/4.0/customization/fields.html](https://nova.laravel.com/docs/4.0/customization/fields.html)
I'm getting error 

```
ERROR in ../../vendor/laravel/nova/resources/js/mixins/HandlesFormRequest.js 1:0-49
Module not found: Error: Can't resolve 'form-backend-validation' in '/home/mateus/ajuda-humanitaria/vendor/laravel/nova/resources/js/mixins'

ERROR in ../../vendor/laravel/nova/resources/js/mixins/HandlesValidationErrors.js 1:0-49
Module not found: Error: Can't resolve 'form-backend-validation' in '/home/mateus/ajuda-humanitaria/vendor/laravel/nova/resources/js/mixins'

ERROR in ../../vendor/laravel/nova/resources/js/mixins/PreventsFormAbandonment.js 7:0-48
Module not found: Error: Can't resolve 'vuex' in '/home/mateus/ajuda-humanitaria/vendor/laravel/nova/resources/js/mixins'

ERROR in ../../vendor/laravel/nova/resources/js/mixins/PreventsFormAbandonment.js 8:0-45
Module not found: Error: Can't resolve '@inertiajs/inertia' in '/home/mateus/ajuda-humanitaria/vendor/laravel/nova/resources/js/mixins'

ERROR in ../../vendor/laravel/nova/resources/js/mixins/PreventsModalAbandonment.js 7:0-48
Module not found: Error: Can't resolve 'vuex' in '/home/mateus/ajuda-humanitaria/vendor/laravel/nova/resources/js/mixins'

ERROR in ../../vendor/laravel/nova/resources/js/mixins/packages.js 13:0-49
Module not found: Error: Can't resolve 'form-backend-validation' in '/home/mateus/ajuda-humanitaria/vendor/laravel/nova/resources/js/mixins'

webpack compiled with 6 errors
```

I know there are other issues with the same error. But I didn't find the answer on how to fix this and if one day it will be fixed by the development team.

This error greatly hinders the development of packages

**Comment by stonkeep** [comment]
I don't know I but, if i do the follow steps


```
cd  ./vendor/laravel/nova)
npm i
mv webpack.mix.js.dist webpack.mix.js
npm run dev
cd ../../../
php artisan nova:publish
```

Compile

**Comment by dniccum** [comment]
@stonkeep The steps that you provided worked for me

**Comment by crynobone** [comment]
PR submitted: https://github.com/laravel/nova-docs/pull/409

**Comment by alexaddw** [comment]
I had the same problem when creating a custom field. To resolve it, I just added these dependencies to the root's `package.json`.

**Comment by davidhemphill** [comment]
The docs have been updated to show you how to properly set up your custom tools and fields.

**Comment by s-fog** [comment]
I have the same ussue, and this fix broke style of admin panel
`cd  ./vendor/laravel/nova)
npm i
mv webpack.mix.js.dist webpack.mix.js
npm run dev
cd ../../../
php artisan nova:publish`

Can u show where docs this fix?

**Comment by s-fog** [comment]
Help please. Cant use custom fields

**Comment by JoDeveloper** [comment]
> I don't know I but, if i do the follow steps
> 
> ```
> cd  ./vendor/laravel/nova)
> npm i
> mv webpack.mix.js.dist webpack.mix.js
> npm run dev
> cd ../../../
> php artisan nova:publish
> ```
> 
> Compile

this worked for me

**Comment by merijnponzo** [comment]
When installing your new field: https://nova.laravel.com/docs/4.0/customization/fields.html
Press yes for all options

after that, go to your new custom field folder and run
```
npm run nova:install
```
worked for me

**Comment by s-fog** [comment]
Thanks! Will try it.
