### ISSUE TITLE
Laravel Nova 4 problem with Create Resource with HasMany relation

### ISSUE THREAD

**Issue by massimodellarovere** [laravel/nova-issues#4126]
Laravel Version: 9.9.0
Nova Version: 4.2.6
PHP Version: 8.1.4
Database Driver & Version: MYSQL 5.7
Operating System and Version: Ubuntu 20.04.4 LTS
Browser type and version: Brave Versión 1.37.116 Chromium: 100.0.4896.127 (64 bits)

Laravel Nova 4 problem with Create Resource with HasMany relation. Same script in Nova 3 is correct

HasMany relation in new environment Nova 4
![image](https://user-images.githubusercontent.com/5731295/165402568-c201f100-3006-43ad-bc08-363799044809.png)

Screen with  infinity loading as result after clic create botton
![image](https://user-images.githubusercontent.com/5731295/165402659-e93bbdb4-0098-4168-8fdd-811441925ddf.png)

Developer Tools i see un error 404 
![image](https://user-images.githubusercontent.com/5731295/165402744-d22f6b7f-4229-4763-b976-27db0e9bb115.png)

**Comment by crynobone** [comment]
Please run `php artisan nova:publish`

https://nova.laravel.com/docs/4.0/installation.html#updating-nova-s-assets

**Comment by massimodellarovere** [comment]
run php artisan nova:publish not resolve the problem 

I receive 404 from this URL /nova-api/products/field/barcodes?resourceName=barcodes&viaResource=products&viaResourceId=1660&viaRelationship=barcodes

**Comment by crynobone** [comment]
Please submit reproducing repository similar to https://github.com/nova-issues

Create with BelongsTo field doesn't access that endpoint so there high possibility that your bug report missing critical information.

**Comment by crynobone** [comment]
Also this dusk tests ensure that the whole process still works:

https://github.com/laravel/nova-dusk-suite/blob/03c1e0230d5bd243158c6eb47e93362a7e439bf6/tests/Browser/CreateWithBelongsToTest.php#L40-L58

**Comment by massimodellarovere** [comment]
Ok I need some time to do the tests and deepen the error I receive, as I have more information I will report in this thread

**Comment by massimodellarovere** [comment]
After several attempts I found this feature that can help you understand why I receive 404 after clic Create Button.

This LINK in Nova 3 receive JSON and in Nova 4 Receive 404
/nova-api/products/field/translations?resourceName=products-translations&viaResource=products&viaResourceId=1660&viaRelationship=translations

Nova 3
![image](https://user-images.githubusercontent.com/5731295/165830011-e8f2198d-a876-4625-befd-a77b4dd0ef5b.png)

Nova 4
![image](https://user-images.githubusercontent.com/5731295/165830272-1d75d650-d541-479f-ac17-7079d14710ff.png)

The difference is that in NOVA 3 HasMany is defined in fields() resource method, in Nova 4 i use ne method fieldsForDetail and not have problem for display HasMany component in Page, but Create Button wrong.

![image](https://user-images.githubusercontent.com/5731295/165830556-ce0bcb0a-5f6d-4384-988a-589b937ba3d2.png)

If iI move definition HasMany in fields() method from fieldsForDetail the button Create is OK non Nova 4
This code recevive 404 in action hasMany

```php

public function fields(NovaRequest $request)
{
        return []
}

public function fieldsForDetail(NovaRequest $request)
{
        return [
            HasMany::make(__('labels.translations'),'translations',Translation::class),
            HasMany::make(__('labels.images'),'images',Media::class),
       ]
}
```

This code recevive 404 is OK

```php

public function fields(NovaRequest $request)
{
        return [
            HasMany::make(__('labels.translations'),'translations',Translation::class),
            HasMany::make(__('labels.images'),'images',Media::class),
       ]
}
```

**Comment by crynobone** [comment]
Please submit reproducing repository similar to https://github.com/nova-issues
