### ISSUE TITLE
Help function for fields should allow html

### ISSUE THREAD

**Issue by neamtua** [laravel/nova-issues#413]
Hi,

The help() function for fields only displays text. If you add html in will show up as text. Would be helpful to allow html here for instances when you might want to link to some other page for information.

<img width="920" alt="screen shot 2018-09-03 at 18 41 50" src="https://user-images.githubusercontent.com/1029457/44994815-13b89d80-afa9-11e8-885a-e90c0e5e2aaf.png">

**Comment by GuidoHendriks** [comment]
Can't you pass a `HtmlString` instance?

**Comment by neamtua** [comment]
Same result

**Comment by davidhemphill** [comment]
This has been fixed and will be included in an upcoming release. You'll be able to pass html to the `help` method.
