### ISSUE TITLE
Nova ignores modified logo.blade.php etc.

### ISSUE THREAD

**Issue by NowakAdmin** [laravel/nova-issues#4132]
Laravel Version: 9.9.0
Nova Version: 4.2.4 // upgraded from 3.31
PHP Version: 8.1.4
Database Driver & Version: mariadb 10.6
Operating System and Version: debian 11
Browser type and version: chrome 100.0.4896.127 64-bit

### Description:
How to properly now modyfy nova style/theme ?

Nova ignores changes in: \resources\views\vendor\nova\partials\logo.blade.php etc files (also footer for example).

also nova:theme no longer exists.

    Command "nova:theme" is not defined.  
                                          
    Did you mean one of these?            
        nova-calendar:export              
        nova-calendar:import              
        nova:action                       
        nova:asset                        
        nova:card
        nova:check-license                
        nova:custom-filter                
        nova:dashboard                    
        nova:field                        
        nova:filter                       
        nova:install                      
        nova:lens                         
        nova:partition                    
        nova:progress                     
        nova:publish                      
        nova:resource                     
        nova:resource-tool                
        nova:stubs                        
        nova:tool                         
        nova:translate                    
        nova:trend                        
        nova:upgrade                      
        nova:user                         
        nova:value 

also in docs is nothing about f. ex. how to replace logo?

**Comment by crynobone** [comment]
See https://nova.laravel.com/docs/4.0/installation.html#brand-logo

**Comment by NowakAdmin** [comment]
Thx, missed that page of docs.

and how to modify footer ?

    'brand' => [
        'footer' => 'Test',

not working

**Comment by crynobone** [comment]
We don't support other customisation than what's available in the documentation officially at the moment. It will be available once we finalise the right approach to handle it.

**Comment by vesper8** [comment]
@crynobone I previously had lots of modifications inside the `resources/views/vendor/nova/partials`, I had added extra things to my navigation, my logo was a lot more than a simple SVG.. seems like you've taken a step backwards as far as letting us customize Nova with the release of V4

Wish you would just let us publish the views and modify as we wish.

Or at the very least.. do like you're doing with the footer

```

 Nova::footer(function ($request) {
        return Blade::render('');
    });
```

But allow us to do the same thing for the logo (at least) and preferably the navigation as well.

**Comment by brogier** [comment]
For anyone reading, i fixt my custom logo by using

```php
Nova::provideToScript([
    'logo' => Blade::render('<svg xmlns="http://www.w3.org/2000/svg" style="background: url({{ $url }}) no-repeat left center; background-size: contain"></svg>', ['url' => 'https://path-to-logo'])
]);
```

**Comment by namnh06** [comment]
> @crynobone I previously had lots of modifications inside the `resources/views/vendor/nova/partials`, I had added extra things to my navigation, my logo was a lot more than a simple SVG.. seems like you've taken a step backwards as far as letting us customize Nova with the release of V4
> 
> Wish you would just let us publish the views and modify as we wish.
> 
> Or at the very least.. do like you're doing with the footer
> 
> ```
> 
>  Nova::footer(function ($request) {
>         return Blade::render('');
>     });
> ```
> 
> But allow us to do the same thing for the logo (at least) and preferably the navigation as well.

I've got the same problem!
Cannot return view or modify the footer is extremely annoying.

**Comment by crynobone** [comment]
@namnh06 Submit new bug report if you have an issue.
