### ISSUE TITLE
Computed field relationship return as an array in index page

### ISSUE THREAD

**Issue by ibrahim-999** [laravel/nova-issues#4135]
- Laravel Version: v8.83.10
- Nova Version: 4.2.7
- PHP Version: PHP 7.4
- Browser type and version: Chrome 100.0

## Describtion ##

- i computed a field in my model using map function to get the status name like this 
- `return $this->statuses->map(fn($status) => [
            $status->name
        ]);`
-  and passed the attribute to the nova resource like that
-  `Text::make('Status', 'status')`
- i got the result correct in the detailed page but it is different in the index page 
- the value of the field in the index page like that `[ [ "jnjn" ], [ "ahshsh" ] ]`

**Comment by crynobone** [comment]
Please submit reproducing repository similar to https://github.com/nova-issues

**Comment by ibrahim-999** [comment]
@crynobone actually I can't but I can get you screenshots from my code if it would help ?

**Comment by crynobone** [comment]
You can create an example app based on example model, not asking you to public the current app.

**Comment by ibrahim-999** [comment]
If you could help without repo I would be glad cuz time is factor for me tell me what you need to see in the code and I will screenshoted to you @crynobone

**Comment by ibrahim-999** [comment]
thank you sir @crynobone i found the solution to my problem and it's to pluck the column name and pass it through the relation in the mutator function in the model 
` return $this->statuses()->pluck('name')->implode(',');`
