### ISSUE TITLE
Issues with logging in when using separate user table for nova users and using custom policies

### ISSUE THREAD

**Issue by leeovery** [laravel/nova-issues#4139]
- Laravel Version: 9.10.1
- Nova Version: 4.2.7
- PHP Version: 8.0.18
- Database Driver & Version: Mysql 8.0.28
- Operating System and Version: macos12.2 on arm64
- Browser type and version: Chrome version 100.0.4896.127 (Official Build) (arm64)

### Description:

I am using a separate user table for nova logins, called 'admin', with a guard called admin, using the session auth driver. 'Normal' users are authed using Sanctum. I also have authorisation policies loaded specifically for serving nova requests. These custom policies are loaded from the AuthServiceProvider, from inside a ServingNova callback. Naturally they expect an `Admin` model as the first param to the policy methods as the currently authed user.

Everything worked fine in Nova v3. But it seems there is an issue with visiting the nova page when already logged into the main app as a 'normal' (non-admin) user.

The error that appears complains that the model sent as the first param to the nova specific auth policies is a `User` model and not an `Admin`.

It seems that when visiting the Nova login page, Nova is attempting to authorise the already logged in user, even though they have separate auth guards and providers. As I said, previously in Nova 3 this behaviour worked as expected.

Interestingly, if both admin and user are already logged in then everything works fine (you can browse nova and the app normally without issues). But, if you log out of 1, the other also logs out. And then if you log into the app, and visit nova, you see the error that the wrong user is being passed to the nova specific policies.

Hopefully this is enough detail but I can provide more or try to dig deeper if necessary.

Thanks.

**Comment by crynobone** [comment]
Please create reproducing repository to allows us to debug the issue. See https://github.com/nova-issues as reference.

**Comment by leeovery** [comment]
@crynobone I have a reproducing repo here https://github.com/leeovery/nova-issue-4139.

I kept the env in the repo for ease. There is a sqlite db with 2 users present.

User:
user@example.com
12345678

Admin:
admin@example.com
12345678

This isn't like my setup but the issue still occurs luckily. I have installed the blade breeze starter to make the login easier for the user.

If you visit the homepage of the app and login using the user credentials above you should be able to login just fine.

Then visit the `/nova` url you will see the issue.

It should show the following: https://flareapp.io/share/xPQ04o2m#F86

**Comment by leeovery** [comment]
Seems the sqlite db is missing, but Im sure you can spin one up :)

I migrated the db, then registered using the app, then used artisan nova:user to create admin user.

**Comment by crynobone** [comment]
This should be fixed in 4.5.0: <https://nova.laravel.com/releases/4.5.0>
