### ISSUE TITLE
"Created At" not showing up in CSV export

### ISSUE THREAD

**Issue by jaxramus** [laravel/nova-issues#4145]
I created an export to CSV action:

        return [
            ExportAsCsv::make()->withFormat(function (\App\Models\Lead $lead) {
                $format['ID'] = $lead->id;
                $format['First Name'] = $lead->first_name;
                $format['Last Name'] = $lead->last_name;
                $format['Email'] = $lead->email;
                $format['Phone'] = $lead->phone;
                $format['Created At'] = $lead->created_at;
                $format['Updated At'] = $lead->updated_at;

                return $format;
            }),
        ];

The "Created At" and "Updated At" columns do not show up in the CSV at all.

**Comment by crynobone** [comment]
You need to cast `Carbon` instance to string
