### ISSUE TITLE
No longer able to install via composer

### ISSUE THREAD

**Issue by potsky** [laravel/nova-issues#4150]
- Laravel Version: 8.83.7
- Nova Version: 4.x
- PHP Version: 8.0.12
- Database Driver & Version: PGSQL
- Operating System and Version: sail 1.13.9
- Browser type and version: Brave (Chrome) [Version 1.37.109 Chromium: 100.0.4896.60 (Official Build) (arm64)]
- Reproduction Repository: https://github.com/private

### Description:

When trying to reinstall nova4 after rollback to nova3, when I run `composer update`, I have:

```
  - Syncing laravel/nova (4.2.7) into cache
Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos
When working with _public_ GitHub repositories only, head to https://github.com/settings/tokens/new?scopes=&description=Composer+on+1b7c54cdd64f+2022-05-03+1350 to retrieve a token.
This token will have read-only permission for public information only.
When you need to access _private_ GitHub repositories as well, go to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+1b7c54cdd64f+2022-05-03+1350
Note that such tokens have broad read/write permissions on your behalf, even if not needed by Composer.
Tokens will be stored in plain text in "/var/www/html/auth.json" for future use by Composer.
For additional information, check https://getcomposer.org/doc/articles/authentication-for-private-packages.md#github-oauth
Token (hidden):
```

### Found !!

Just for others:

- Branch `main` on my repo : nova3
- Branch `nova4` on my repo to test nova4
- Switch back to `main` to fix a bug on production for example
- When coming back in `nova4`, `vendor/laravel/nova` is linked to nova 3 install to `../../nova`
- Composer then try to sync an existing directory instead of downloading nova4

Solution : `rm -rf vendor/laravel/nova` and then `composer update`

**Comment by meyer59** [comment]
So close the ticket ?
