### ISSUE TITLE
Nova 4 redirect when opening login page

### ISSUE THREAD

**Issue by ramonfeleus** [laravel/nova-issues#4151]
- Laravel Version: 9.10.1
- Nova Version: 4.2.7
- PHP Version: 8.1.5
- Database Driver & Version: mysql 8.0.28 (homebrew)
- Operating System and Version: MacOS 12.2
- Browser type and version: all
- Reproduction Repository: n.a.

### Description:
I've just installed a fresh laravel 9 through composer following the  [Laravel 9 manual](https://laravel.com/docs/9.x/installation#installation-via-composer)
This is working well without issues, the demo page is shown on /

After that I tried installing Nova 4, again using composer, with the steps in the [Nova 4 manual](https://nova.laravel.com/docs/4.0/installation.html#installing-nova-via-composer).
The only additional thing needed there was to add an auth.json with "http-basic" credentials for "nova.laravel.com" to enable composer to download the code. After that composer succesfully installed it.
_App\Providers\NovaServiceProvider::class,_ was added to **app.php** after the nova install command. 
**config/nova.php** was added with a valid _license_key_ entry, no further modifications to that.
The project has no further modifications to it. 

But when I visit **/nova** the browser gets multiple 302 redirects to **/nova/login** which ultimately get stopped by my browser (either chrome or firefox).

Is there something else I should have done? Might there be some info missing in the documentation? Or perhaps it is a problem specific to the Laravel and Nova versions combination?

### Detailed steps to reproduce the issue on a fresh Nova installation:
Visit **/nova** the browser gets multiple 302 redirects to **/nova/login**
_(see description segment above)_

**Comment by meyer59** [comment]
I had a similar issue, after long hours of debugging, i found out that the problem was  coming from a misconfiguration in the middleware key in `config/nova.php` 
Make sure you include only these mentionned here in the right order [https://nova.laravel.com/docs/4.0/upgrade.html#updating-configuration-assets-and-translations](url)

```
  'middleware' => [
        'web',
        HandleInertiaRequests::class,
        DispatchServingNovaEvent::class,
        BootTools::class,
    ],

    'api_middleware' => [
        'nova',
        Authenticate::class,
        Authorize::class,
    ],
```

**Comment by ramonfeleus** [comment]
> I had a similar issue, after long hours of debugging, i found out that the problem was coming from a misconfiguration in the middleware key in `config/nova.php` Make sure you include only these mentionned here in the right order [https://nova.laravel.com/docs/4.0/upgrade.html#updating-configuration-assets-and-translations](url) in `config/nova.php`
> 
> ```
>   'middleware' => [
>         'web',
>         HandleInertiaRequests::class,
>         DispatchServingNovaEvent::class,
>         BootTools::class,
>     ],
> 
>     'api_middleware' => [
>         'nova',
>         Authenticate::class,
>         Authorize::class,
>     ],
> ```

Thanks so much, that worked! Maybe this should come as a default in de file, I did not change that section of `config/nova.php` as far as I know, just the license key.
