### ISSUE TITLE
Card height not correct when full width

### ISSUE THREAD

**Issue by RhysLees** [laravel/nova-issues#4158]
- Laravel Version: 9.x
- Nova Version: 4.3.3
- PHP Version: 8.1
- Database Driver & Version: N/A
- Operating System and Version: Win 11 WSL2
- Browser type and version: Chrom Latest
- Reproduction Repository: N/A

### Description:

![image](https://user-images.githubusercontent.com/43909932/166699230-83d7f3c4-fa59-465f-8251-0470624813b5.png)
![image](https://user-images.githubusercontent.com/43909932/166699349-73aa19c0-86d2-473a-ac7b-17f067f817e2.png)
![image](https://user-images.githubusercontent.com/43909932/166699408-96e18d95-584c-45e1-a310-3856e7bcd798.png)

If I change to half-width then the height matches the other cards

![image](https://user-images.githubusercontent.com/43909932/166700779-9aeed7b5-c029-4bce-bdde-45469e4c9e28.png)

**Comment by davidhemphill** [comment]
You know, we had it the other way and people complained it was limited to the height of the other smaller cards. 😅

**Comment by RhysLees** [comment]
> I like your taste...lol. Maybe we could provide a modifier that adds the fixed height. That seems okay to me. I'll add it to my list.
> 
> Thank you for the encouragement! It really does help hearing that.

Awesome I really appreciate your quick response and am glad to see this is something you will consider working on.

Hope you have a good evening 😁

**Comment by davidhemphill** [comment]
Already added...should come out soon. You'll be able to use `fixedHeight()`, `dynamiceHeight()`, and `height(Card::DYNAMIC_HEIGHT)` or `height(Card::FIXED_HEIGHT)`.

Have a good one!

**Comment by davidhemphill** [comment]
👋 Hi there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
