### ISSUE TITLE
Validation error should scroll to the first erroneous field

### ISSUE THREAD

**Issue by DonDiegoAA** [laravel/nova-issues#416]
Currently the scrollbar is making a tiny jump to the top (chrome windows 10)

**Comment by rickmacgillis** [comment]
For me the validation isn't scrolling anywhere. If I click the "Update" button, it'll prevent the submission, but it looks like a bug, rather than a validation error. To assist in the UI, the button should scroll to the element with the first error in it.

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by yehudahkay** [comment]
+1 this is a bug, user doesn't know why save didn't work
