### ISSUE TITLE
Nova 4.3.4 -" Attempt to read property "resourceClass" on null "Error

### ISSUE THREAD

**Issue by yunuselci** [laravel/nova-issues#4162]
- Laravel Version: 9.9.0
- Nova Version: 4.3.4
- PHP Version: 8.1.5
- Database Driver & Version:
- Operating System and Version: Windows 11 
- Browser type and version: Chrome Latest
- Reproduction Repository: NA

### Description:
After updating my Laravel Nova version from 4.2.1 to 4.3.4, my BelongsToMany relations stopped working.No changes have been made to the source code, only the nova version has been updated. Downgrading the Nova version to 4.2.1 fixes the problem.

![image](https://user-images.githubusercontent.com/56027479/166903027-91e2548d-56ac-40e8-836d-2b3da7f8b867.png)

Where it says "Choose Application" in the picture, the applications should be listed, but as you can see, it does not make any listing and gives an error "Attemp to read property "resourceClass" "on null"

I would also like to point out that I am not getting any errors only in this resource. My other resource defined with BelongsToMany also throws an error.

**Comment by crynobone** [comment]
Run `php artisan nova:publish`

**Comment by yunuselci** [comment]
While I was researching this issue, I ran the` php artisan nova:publish` command. Nothing had changed. Now, when I updated my nova version again and ran the `php artisan nova:publish` command, my problem was fixed. Thank you.
