### ISSUE TITLE
Checkbox disappears and reappears with attached actions and authorizedToDelete = false

### ISSUE THREAD

**Issue by Melvintehu** [laravel/nova-issues#4164]
- Laravel Version: 9.0
- Nova Version: 4.0
- PHP Version: 8.0.2
- Browser type and version: Chrome 100 on Windows 11 (100.0.4896.127)

### Description:
Checkbox disappears and reappears when a given resource has actions attached and the authorizedToDelete method returning false.

Below you see a screenshot without the checkboxes (I just clicked one). 

![checkboxes-disappearing](https://user-images.githubusercontent.com/5984622/166916968-fc01f5fe-46ba-4a06-8b6f-4173293678b8.png)

Below you see a screenshot with the checkboxes reappearing.
![checkboxes-reappearing](https://user-images.githubusercontent.com/5984622/166917391-d89bd499-5450-403b-aa6b-5819fa1a0cfb.png)

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Fresh install of Laravel Nova 4
2. Create a new Resource
3. Have the authorizedToDelete method return false
3. Create an action
4. Attach the action to the previously created resource
5. Load the resource
6. Click a checkbox, the checkboxes next to each entry in the table, disappears and then reappears.

**Comment by crynobone** [comment]
I don't think I fully understand what you try to describe at step 7.

**Comment by Melvintehu** [comment]
All the checkboxes on the resource table, are removed from the view and shortly after reappear.   

When I click a random checkbox on my resource table, all the checkboxes are hiding/removed from in the UI. Below you see a screenshot without the checkboxes (I just clicked one). 

![checkboxes-disappearing](https://user-images.githubusercontent.com/5984622/166916968-fc01f5fe-46ba-4a06-8b6f-4173293678b8.png)

Below you see a screenshot with the checkboxes reappearing.
![checkboxes-reappearing](https://user-images.githubusercontent.com/5984622/166917391-d89bd499-5450-403b-aa6b-5819fa1a0cfb.png)

This happens everytime I click a checkbox in the UI.

**Comment by crynobone** [comment]
This doesn't happened on basic installation, can you submit reproducing repository similar to https://github.com/nova-issues

We already have dusk tests covering the use case.
