### ISSUE TITLE
Markdown field doesn't render nested lists

### ISSUE THREAD

**Issue by inventionate** [laravel/nova-issues#4173]
- Laravel Version: 9.11.0
- Nova Version: 4.4.2
- PHP Version: 8.1.5
- Database Driver & Version: MariaDB 10.4
- Operating System and Version: macOS 12.3.1
- Browser type and version: Safari 15.4; Firefox 100

### Description:

Nested lists:

```markdown
- test
  -test 2
- test 3
```

… are correctly recognized in the input mode (syntax) and also correctly saved for further processing. However, in the preview window and e.g. in the detail view they are displayed incorrectly. It doesn't matter which parser is selected.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Use markdown field and insert nested list. Afterwards, click e.g. preview.

**Comment by ziming** [comment]
Also on chrome, not just firefox and safari
