### ISSUE TITLE
no way to disable previews, and preview modal shows despite having no fields

### ISSUE THREAD

**Issue by jaxramus** [laravel/nova-issues#4177]
i searched the documentation and there is currently no way to remove the preview icon

the preview icon also displays when there are no fields set to preview, so it just comes up with an empty box

is there a way to do just remove the preview icon that i missed from the docs?

thank you

**Comment by clementmas** [comment]
There was a discussion here about this subject: https://github.com/laravel/nova-issues/discussions/3983

I think the preview icon should be hidden if there are no fields to preview.
