### ISSUE TITLE
Nova 4.4.0 BC break

### ISSUE THREAD

**Issue by nrueckmann** [laravel/nova-issues#4183]
- Laravel Version: 9
- Nova Version: 4.4.0
- PHP Version: 8.1

### Description:

Nova 4.4.0 breaks BC by removing `Laravel\Nova\Nova::theme()`.
I guess it's not a big deal, because there are other ways to inject assets, but it would be great if minor updates would not break backwards compatibility.

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Install nova prior 4.4.0. 
2. Use `Laravel\Nova\Nova::theme()` (e.g. in your NovaServiceProvider).
3. Try to update to Nova >= 4.4.0

```
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
[2022-05-06 15:25:39] local.ERROR: Method theme does not exist. {"exception":"[object] (BadMethodCallException(code: 0): Method theme does not exist. at /var/www/html/vendor/laravel/nova/src/Nova.php:1188)
```

**Comment by jayjfletcher** [comment]
I've run into the same issue. Was it mentioned somewhere this functionality was being removed? I can't seem to find it being mentioned anywhere.

**Comment by nrueckmann** [comment]
I haven't seen any info. The method has also not been tagged as deprecated before.

**Comment by crynobone** [comment]
You can use `Laravel\Nova\Nova::remoteStyle()` to register theme CSS.
