### ISSUE TITLE
HttpException for APP_ENV=production for unauthorized users

### ISSUE THREAD

**Issue by kishoresai438** [laravel/nova-issues#419]
Hi Team,

Trying to add Authorization to access Nova. It is working fine for correct users(who are having Admin role). But For unauthorized users(User role) it is throwing  HttpException. Added the below code in Gate method.

Note: I am testing from local environment. I just changed the APP_ENV in .env to Prod

```
Gate::define('viewNova', function ($user) {
            return $user->hasAnyRole('Admin');
        });
        return false;
```

**Comment by BengtHagemeister** [comment]
This issue relates to the problem described here: `https://stackoverflow.com/questions/28834189/svg-inline-in-css-not-working-in-firefox?rq=1`

In Firefox the # character indicated the start of a fragment identifier.

It has to be replaced with the url encoded version %23.

**Comment by davidhemphill** [comment]
This is correct behavior.
