### ISSUE TITLE
Some translations are still not working in combination with other nova packages

### ISSUE THREAD

**Issue by novelnet** [laravel/nova-issues#4192]
- Laravel Version: 9.11.0
- Nova Version: 4.4.2
- PHP Version: 8.0.12
- Database Driver & Version:
- Operating System and Version: Win 11
- Browser type and version: Firefox, Chrome (latest)

### Description:
Following up to these two issues #2515, #3767 there is still the problem that some parts of Nova are not translated with the default translation strings inside `/lang/vendor/nova/de.json`.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Fresh Laravel and Nova installation using somewhere the Flexible Content Field (https://github.com/whitecube/nova-flexible-content) causes the missing translations:
![image](https://user-images.githubusercontent.com/31067676/167262808-7d6c490b-1d9c-486d-85e5-141594aa32cc.png)

When commenting out the Flexible Content Field the translations work as normal:
![image](https://user-images.githubusercontent.com/31067676/167262849-fe8c6063-dfc8-45ce-9f8b-7ecf8f8e671f.png)

My locale is set to 'de'.

When i dig deeper into the Flexible Content Field and remove the translation function __() in the custom field constructor, the translations work correctly again:
https://github.com/whitecube/nova-flexible-content/blob/master/src/Flexible.php
![image](https://user-images.githubusercontent.com/31067676/167262995-2b23c1b3-6d5b-4ad9-8760-eca8da7332eb.png)

I opened an issue at the package directly as well. It seems tho, that other nova users have problems with packages or those missing translations too, as the issue comes up repeatedly.

Thanks in advance.

**Comment by crynobone** [comment]
`__()` should never be called before setting current locale (normally through middleware), otherwise you would experience exactly this issue.

Package need to fix this issue.
