### ISSUE TITLE
Nova failed to load on a fresh laravel 9/nova 4 installation

### ISSUE THREAD

**Issue by RealityGamin** [laravel/nova-issues#4197]
- Laravel Version: 9
- Nova Version: 4
- PHP Version: 8

### Description:
I installed a default fresh laravel 9 application, and installed latest nova to test it out and getting the following errors.

![image](https://user-images.githubusercontent.com/100086757/167355524-bcd600b5-7b7a-4b6b-989c-3bd1c9961076.png)

no other files installed by composer

![image](https://user-images.githubusercontent.com/100086757/167355588-ec814c0a-2691-445d-8330-a0ec5b9b3b5c.png)

I ran the following to attempt to resolve it, but it seems like an issue with the app.js loading something
php artisan nova:install
php artisan nova:publish
php artisan view:clear

**Comment by crynobone** [comment]
See https://github.com/laravel/nova-issues/discussions/4127

**Comment by RealityGamin** [comment]
> See #4127

Interesting post, I will play around with it but I will add to my original post that this is happening when loading a fresh laravel nova installation, it will redirect to /nova/login and happens there.

**Comment by RealityGamin** [comment]
> See #4127

Okay.. the temporary solution was to turn off cloudflare.. but honestly that is not a real solution

**Comment by crynobone** [comment]
> Okay.. the temporary solution was to turn off cloudflare.. but honestly that is not a real solution

Deferring JavaScript in a SPA app is not desired. Rocket Loader exists to speed up content loading where JavaScript and CSS can be deferred and text gets displayed first, this doesn't exist in SPA application.
