### ISSUE TITLE
Resource Detail Image Wrong Version

### ISSUE THREAD

**Issue by tschmidiger** [laravel/nova-issues#42]
According to the docs (Customizing Previews) the images displayed on the resource detail page should be the preview version. But the detail and edit page actually show the thumbnail version as it is set in this component:

`nova/resources/js/components/Detail/FileField.vue`
`nova/resources/js/components/Form/FileField.vue`

**Comment by BostjanOb** [comment]
![image](https://user-images.githubusercontent.com/650818/44681963-62fb4d00-aa42-11e8-9780-fdbe2ddb866c.png)

preview is not used in any of the file fields

**Comment by charlielangridge** [comment]
+1

**Comment by Gnative** [comment]
+1

**Comment by Gnative** [comment]
Wondering why this is still a bug ?

**Comment by bonzai** [comment]
This has been fixed and will be included in the next release.
