### ISSUE TITLE
ID Text, for Country Codes, fillable on Forms

### ISSUE THREAD

**Issue by elrufoelrufo** [laravel/nova-issues#420]
Hello,

I have Country Model, the ID is the Country Code (Text). 

I'm having problems to add this field to forms (edit and create). Also to update a country I'm getting an error because the field is not an integer. 

Is there anyway to do it? 

Thanks. Regards.

**Comment by taylorotwell** [comment]
What error do you actually receive?

**Comment by elrufoelrufo** [comment]
Hello,

For update  , I'm obtaining an sql error because actionable_id is not an integer in this case : 

NOTE : No worries about data is fake. 

> SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'AI' for column 'actionable_id' at row 1 (SQL: insert into `action_events` (`batch_id`, `user_id`, `name`, `actionable_type`, `actionable_id`, `target_type`, `target_id`, `model_type`, `model_id`, `fields`, `status`, `exception`, `updated_at`, `created_at`) values (8bb4a19e-5bc9-4792-aefe-1fca2ace3267, 6, Update, App\Country, AI, App\Country, AI, App\Country, AI, , finished, , 2018-09-04 16:40:18, 2018-09-04 16:40:18)) {"userId":6,"email":"pepe@pepe.com","exception":"[object] (Illuminate\\Database\\QueryException(code: HY000): SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'AI' for column 'actionable_id' at row 1 (SQL: insert into `action_events` (`batch_id`, `user_id`, `name`, `actionable_type`, `actionable_id`, `target_type`, `target_id`, `model_type`, `model_id`, `fields`, `status`, `exception`, `updated_at`, `created_at`) values (8bb4a19e-5bc9-4792-aefe-1fca2ace3267, 6, Update, App\\Country, AI, App\\Country, AI, App\\Country, AI, , finished, , 2018-09-04 16:40:18, 2018-09-04 16:40:18)) at /home/vagrant/code/tunerclicknova.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, PDOException(code: HY000): SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'AI' for column 'actionable_id' at row 1 at /home/vagrant/code/tunerclicknova.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php:458)

For insert, the ID field is not showing. I try to force it with "onlyOnForms" but does not work.

Thanks!!
