### ISSUE TITLE
Navigation not highlighted when on detail page

### ISSUE THREAD

**Issue by Kaishiyoku** [laravel/nova-issues#4202]
- Laravel Version: 9.11.0
- Nova Version: 4.4.2
- PHP Version: 8.0.13
- Database Driver & Version: MariaDB 10.7
- Operating System and Version: Windows 11 21H2
- Browser type and version: Microsoft Edge 101.0.1210.39

### Description:

When viewing a model or editing it the left navigation bar loses its CSS highlighting.

### Detailed steps to reproduce the issue on a fresh Nova installation:

* click on a resource (for example Users)
* open an entry (for example the user with the ID 1)
* The "Users" resource navigation link loses its CSS highlighting  color

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/5131112/167510824-a6320d6c-e701-4c46-9ab3-3279e610842d.png">

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/5131112/167510873-6bc82e9f-134d-4893-8f84-017057f075bd.png">

**Comment by crynobone** [comment]
https://user-images.githubusercontent.com/172966/167511671-65a6087a-201b-4c12-a859-a3802d971891.mp4

Unable to reproduce, please ensure you have the latest asset by running `php artisan nova:publish`.

**Comment by Kaishiyoku** [comment]
Thank you @crynobone, that was the issue. I tried to publish the assets using the ´--force´ flag and now it works.
