### ISSUE TITLE
File Field doesn't take FILESYSTEM_DRIVER into account

### ISSUE THREAD

**Issue by calvinmuller** [laravel/nova-issues#421]
I use public for local development and s3 for production - so it seems I run into this problem.

Snippet from File.php
```
    public function __construct($name, $attribute = null, $disk = 'public', $storageCallback = null)
    {
        parent::__construct($name, $attribute);

        $this->disk = $disk;

        $this->prepareStorageCallback($storageCallback);

        $this->thumbnail(function () {
            return null;
        })->preview(function () {
            return null;
        })->download(function ($request, $model) {
            $name = $this->originalNameColumn ? $model->{$this->originalNameColumn} : null;

            return Storage::disk($this->disk)->download($this->value, $name);
        })->delete(function () {
            if ($this->value) {
                Storage::disk($this->disk)->delete($this->value);

                return $this->columnsThatShouldBeDeleted();
            }
        });
    }
```

As you can see it just default to public and therefor for every image/file field I use I have to append 

```
Image::make('Logo', 'logo')
                ->disk(config('filesystems.default'))
                ->prunable(),
```

Could you not just make disk default to null and in the constructer just do something like this to prevent having to add ```->disk(config('filesystems.default')) / ->disk(config('filesystems.cloud'))```
```
if ($disk === null) {
   $this->disk = config('filesystems.default');
}
```

**Comment by calvinmuller** [comment]
closed because fixed?

**Comment by liamjgm** [comment]
@calvinmuller How did you set the default disk in the end? The File class construct always takes disk as 'public' by default

**Comment by tirta-keniten** [comment]
It is painful when I have to type ``->disk('s3')`` everytime I make Image field.

**Comment by calvinmuller** [comment]
agreed. stupid issue and seems they not willing to even fix it. @davidhemphill

**Comment by Jam0r85** [comment]
Any chance this can be looked at again?

It seems strange to not use the default filesystem and just assume we are using public.

Would also solve issue #87

**Comment by desaintflorent** [comment]
I agree too why this issue doesn't have any explanation or fix ?
default filesystem seems the right choice instead of having to defining ourself the disk. 
and especially when you are dealing with different filesystems between local and production.

**Comment by davidhemphill** [comment]
Changing this would require changing the default behavior for the field (which is to use the `public` disk), which we will not do until a breaking release. Also, I don't believe it's a huge inconvenience to define the disk as the third parameter.

```php
File::make('Avatar', 'avatar', 's3');
```

**Comment by cwilby** [comment]
First time seeing this, what would the effect be if the default coalesced to `config('filesystems.default')`?

**Comment by bkuhl** [comment]
This caught me off guard today.  It's not a big deal to pass `config('filesystem.default')` as a 3rd param, just adds a bit of clutter.  Was hoping the `next-series` label being removed would've resolved it, but it seems to still be using the public disk by default.
