### ISSUE TITLE
Ray in Badge file

### ISSUE THREAD

**Issue by andresilvagomez** [laravel/nova-issues#4211]
- Laravel Version: 9.x.x
- Nova Version: 4.5.0
- PHP Version: 8.1.0
- Database Driver & Version: Postgres
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:

vendor/laravel/nova/src/Fields/Badge.php
line 230
Ray is present in Badge field. 

<img width="611" alt="Screen Shot 2022-05-10 at 14 25 49" src="https://user-images.githubusercontent.com/2415015/167707305-5adaae6c-6c47-44b3-834b-a1f38f200bf2.png">

### Detailed steps to reproduce the issue on a fresh Nova installation:

Showing badge file in production

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
