### ISSUE TITLE
Nova 2 checksum failing

### ISSUE THREAD

**Issue by ahamilton9** [laravel/nova-issues#4212]
- Laravel Version: 6.18
- Nova Version: 2.4
- PHP Version: 7.4
- Database Driver & Version: Postgres 14
- Operating System and Version: Lando Alpine Images
- Browser type and version: Unrelated
- Reproduction Repository: Unrelated

### Description:

Sudden error on composer install:

Failed to download laravel/nova from dist: The checksum verification of the file failed (downloaded from https://nova.laravel.com/dist/laravel/nova/laravel-nova-46e5ebbb36e56de0a0b4d87b9db63b1083da3365-zip-8fcd64.zip)

### Detailed steps to reproduce the issue on a fresh Nova installation:

- Have a working Nova 2 install
- Clear your cache and try to install latest version

**Comment by davidhemphill** [comment]
Run `composer update mirrors` on your server.
