### ISSUE TITLE
Menu scroll bar shows even when content is not overflowing

### ISSUE THREAD

**Issue by RhysLees** [laravel/nova-issues#4218]
- Laravel Version: Latest
- Nova Version: 4.5.2
- PHP Version: 8.1
- Operating System and Version: Windows with WSL2
- Browser type and version: Chrome Latest

### Description:

Menu scroll bar shows even when content is not overflowing

![image](https://user-images.githubusercontent.com/43909932/167949100-82fe2f3b-ff01-469d-9db9-450560332145.png)

### Fix
change `overflow-y-scroll` to `overflow-y-auto`

![image](https://user-images.githubusercontent.com/43909932/167949872-ce735ba5-1830-45ac-8c4b-ae48e8653859.png)

**Comment by crynobone** [comment]
CSS has been reverted to previous release.
