### ISSUE TITLE
Add fields between relations not longer working

### ISSUE THREAD

**Issue by StanBarrows** [laravel/nova-issues#4222]
- Laravel Version: 9.12.*
- Nova Version: 4.5.*
- PHP Version: 8.1.

### Description:

**Relations are forced to be displayed at the bottom of each resource.**
There is no more possibility of adding headings or any other field between relations. We used this in Nova 3.0 to give some users a little more context of specific relations by applying a descriptive heading.

```

public function fields(NovaRequest $request)
    {
        return [
    
         (new Panel('Label Panel', $this->labels())),

           $this->timestampsPanel(),

        ];
    }

   protected function labels()
    {
        return [
            Heading::make('Label Description )'),
            HasMany::make('Labels', 'labels', Label::class),

        ];
    }
```
<img width="1553" alt="CleanShot 2022-05-12 at 08 18 27@2x" src="https://user-images.githubusercontent.com/10268813/168004561-a0352fb7-f096-4248-afec-d23eee42c247.png">

**Comment by crynobone** [comment]
This is no longer possible in Nova 4 as relationship will have it's own Panel.

**Comment by StanBarrows** [comment]
@crynobone 

Thanks for the answer. Would be cool to have some Subtitle possibilities to describe relations.

![CleanShot 2022-05-12 at 08 54 35@2x](https://user-images.githubusercontent.com/10268813/168009874-c6f8b0c5-38b3-40f5-bebb-b088b85bc224.png)
