### ISSUE TITLE
[4.x] Dashboards still use "static" logic

### ISSUE THREAD

**Issue by alberto-bottarini** [laravel/nova-issues#4223]
- Nova Version: 4.x

### Description:
I need to create dynamic dashboards using a eloquent model, but Nova still use "static stuff" in their internal code.

My service provider is similar to:

```php
    protected function dashboards()
    {
        return MyModel::all()->map(function($model) {
                return (new CustomDashboard($model));
            }
        )->toArray();
    }
```

CustomDashboard needs $model in order to define name or url:

```php
public function uriKey()
    {
        return $this->model->id;
    }

    public function label()
    {
        return $this->model->name;
    }
```

but Nova *still* use static stuff 👎 

```php
    public static function dashboard($dashboard)
    {
        return with(new $dashboard(), function ($dashboard) {
            return static::make(
                $dashboard->label(),
                '/dashboards/'.$dashboard->uriKey()
            )->canSee(function ($request) use ($dashboard) {
                return $dashboard->authorizedToSee($request);
            });
        });
    }
```

I already noticed this problem for Nova 3.0 (https://github.com/laravel/nova-issues/issues/3151) and I was happy when I discovered that Nova 4.0 stops using static method. But it was a fake happyness because it does not change anything: `label` and `uriKey` methods still get called statically. WHY?

**Comment by davidhemphill** [comment]
The `label` and `uriKey` methods are called on the instance passed to the `with` function...if they were being called statically they would be using the "::".

**Comment by alberto-bottarini** [comment]
Technically you are 100% right, no static calls are performed.

Pragmatically speaking you cannot have dashboard instances with state property, because Nova autonomous call the constructor without knowing the parameters.

In my scenario, I need to create a `CustomDashboard` passing a `CustomModel` that knows how the dashboard has to be rendered. And I cannot implement it because the constructor is invoked in the "nova internals".

This approach has the same limitations of the "static method approach".

I think you should use the dashboard instances that are constructed in the `NovaServiceProvider`.

**Comment by davidhemphill** [comment]
I was able to use the `Nova::dashboards` method to achieve what you're describing:

```php
// NovaServiceProvider::boot
Nova::dashboards([
    Metrics::make('wew'),
]);

// Metrics.php Dashboard
class Metrics extends Dashboard
{
    public function __construct($string)
    {
        return $this->string = $string;
    }

    public function label()
    {
        return $this->string;
    }

	//
}
```

**Comment by alberto-bottarini** [comment]
How can I fix the "menu" problem?
`MenuSection` continues to call an empty contructor...

```php
    public static function dashboard($dashboard)
    {
        return with(new $dashboard(), function ($dashboard) {
            return static::make(
                $dashboard->label(),
                '/dashboards/'.$dashboard->uriKey()
            )->canSee(function ($request) use ($dashboard) {
                return $dashboard->authorizedToSee($request);
            });
        });
    }
```

**Comment by alberto-bottarini** [comment]
I fixed with this override in dashboard class:

```php
    public function menu(Request $request)
    {
        $dashboard = $this;
        return (new MenuItem($dashboard->label()))
            ->path('/dashboards/'.$dashboard->uriKey())
            ->canSee(function ($request) use ($dashboard) {
                return $dashboard->authorizedToSee($request);
            });

    }
 ```
 
 but it's a stupid hack. I don't understand the need to call `new $dashboard`

**Comment by davidhemphill** [comment]
This is why the menu method is there. It's there so you can customize the logic used to define the menu item. 😀
