### ISSUE TITLE
Labels do not hide from resource views in Nova 4

### ISSUE THREAD

**Issue by alekmlynek** [laravel/nova-issues#4228]
- Laravel Version: 9+
- Nova Version: 4.5.1

### Description:
The label does not disappear when you hover-over, then hover-out of it.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Go to any resource view
Hover over any of the action buttons like "delete"
Once the "delete' label shows, hover over it with your mouse
Now hover away up, left, right and the label will stick around forever

![image](https://user-images.githubusercontent.com/4039858/168131012-d4c9e0e2-a1de-4a0b-ad12-6dc82553506b.png)

**Comment by crynobone** [comment]
![CleanShot 2022-05-13 at 06 46 19](https://user-images.githubusercontent.com/172966/168179702-46ec888a-f726-4f17-97ce-10c685e30160.gif)

Unable to reproduce, please ensure you have the latest assets by running `php artisan nova:publish`

**Comment by alekmlynek** [comment]
Not a Nova publishing issue. It happens on all of my projects—attached video for clarification.

https://user-images.githubusercontent.com/4039858/168180463-e2ffce17-685c-4660-b352-ee4faab58222.mov

**Comment by crynobone** [comment]
Please submit reproducing repository similar to https://github.com/nova-issues in order for us to debug your issue.

**Comment by alekmlynek** [comment]
I don't understand. You posted a video that didn't **follow** reproduction instructions. 

I posted a video with behaviour that clearly shows the issue. You need to hover over the label that pops up to trigger it. This is on all of my Nova projects, please simply hover over the label to reproduce on any Nova 4 install.

Uploading a reproduction repo seems a waste of time.

**Comment by alekmlynek** [comment]
Actually, apologies. I did find another project where this does not happen. It's something that is happening on my end. I'll take this on myself and post a solution once I've figured this out. Thanks Crynobone.

**Comment by crynobone** [comment]
I am not able to reproduce your issue so we need to replicate steps which only you know right now. It also waste of time for us to debug an issue that no one else report at the time being without knowing exactly how to reproduce it.

**Comment by trovster** [comment]
I am able to reproduce this. You mouse over the icon to give the title, then move your mouse on to the popup. After you have done this the popup stays, even if you mouse over other icons.
