### ISSUE TITLE
updated_at time set on creation

### ISSUE THREAD

**Issue by kichetof** [laravel/nova-issues#4239]
- Laravel Version: 9.12.2
- Nova Version: 4.5.4 (bug show on previous version too)
- PHP Version: 8.1.5
- Database Driver & Version: Mysql 8
- Operating System and Version: macOS - Laravel Sail
- Browser type and version: Safari 15.4

### Description:

`updated_at` time is set when the record is created. It shouldn't.

### Detailed steps to reproduce the issue on a fresh Nova installation:

```
sail artisan make:model Date -m
sail artisan migrate
sail artisan nova:resource Date
```

_migration_
```php
Schema::create('dates', function (Blueprint $table) {
    $table->id();
    $table->string('test');
    $table->timestamps();
});
```

_Resource_
```php
public function fields(NovaRequest $request)
{
    return [
        ID::make()->sortable(),
        Text::make('Test'),
    ];
}
```

Create a record and see the db:

|id|test|created_at|updated_at|
|--|--|--|--|
|1|write something|2022-05-13 19:36:08|2022-05-13 19:36:08|

**Comment by LTKort** [comment]
This is certainly not a bug of Laravel Nova, and not bug of Laravel either. I think this been in it since Laravel 4.2

**Comment by kichetof** [comment]
Thanks to pointing me to this! I never check it before and with time displayed, I saw like a mistake. The logic behind is true, when you create, you're the first edit of the record. I'll `null` the updated_at on display if it same as created_at, users will not ask me why they are identical :)

You can close this issue
