### ISSUE TITLE
Small problem with icon profile in general panel 

### ISSUE THREAD

**Issue by massimodellarovere** [laravel/nova-issues#4241]
Laravel Version: 9.12.2
Nova Version: 4.5.4
PHP Version: 8.1.5
Database Driver & Version: MYSQL 5.7
Operating System and Version: Ubuntu 20.04.4 LTS
Browser type and version: Brave Versión 1.37.116 Chromium: 100.0.4896.127 (64 bits)

### Description:
When I use Dashboard, the main dasboard but every custom dashboard, I see profile with avatar in top/right screen.
When I use a resource the avatar disappare.

Screenshot with dashboard main or custom dashboard
![image](https://user-images.githubusercontent.com/5731295/168451615-56388ac7-79c8-4e29-bad8-34697f4abe39.png)

Screenshot when I change for see a standard resource

![image](https://user-images.githubusercontent.com/5731295/168451659-0f01903a-0a8c-483c-b1b4-b8801335670f.png)

**Comment by crynobone** [comment]
Unable to reproduce, please provide reproducing repository in order for us to debug the issue.

**Comment by massimodellarovere** [comment]
I found a solution.. The Avatar is defined in fields method the resource User but User have merhod fieldsforIndex etc. If I define Avatar:make in fields methos i see avatar in dashboard and belongto searchable field but not in resource (index,edit, create etc)
If add Avatar::make in fieldsforIndex I see avatar in all resources 

Original code of resource User 
![image](https://user-images.githubusercontent.com/5731295/168452978-c6207b6f-1826-41a4-87a7-9c6368cf575b.png)

If I add Avatar in other method the avatar compare in resource
![image](https://user-images.githubusercontent.com/5731295/168452992-bda52693-5584-4a20-9cc9-c7354e8e5c05.png)

Result after change code
![image](https://user-images.githubusercontent.com/5731295/168453022-f342f47e-d8c8-4fe6-bbf4-f62371601499.png)

**Comment by crynobone** [comment]
Expected limitation. Outside of resources URL balues with always resolved from `fields()`, while browsing resources index URL `fieldsForIndex()` has priority over `fields()`.
