### ISSUE TITLE
Small bug in column with sortable when i use relations

### ISSUE THREAD

**Issue by massimodellarovere** [laravel/nova-issues#4243]
Laravel Version: 9.12.2
Nova Version: 4.5.4
PHP Version: 8.1.5
Database Driver & Version: MYSQL 5.7
Operating System and Version: Ubuntu 20.04.4 LTS
Browser type and version: Brave Versión 1.37.116 Chromium: 100.0.4896.127 (64 bits)

### Description:
I have a resource con sortable column.. When I use normal resource the icon highlight for ASC / DESC is correct
![image](https://user-images.githubusercontent.com/5731295/168452270-afca163d-e4aa-421d-8cf0-bc30b13992e2.png)

If I use same resource as HasMany relation with other resources the icon highlight ASC/DESC failed
![image](https://user-images.githubusercontent.com/5731295/168452303-44414129-1c00-438a-a2fd-baf8de01add1.png)

**Comment by crynobone** [comment]
This requires reproducing repository.

**Comment by crynobone** [comment]
Closing this as stale at the moment, feel free to create a new issue with a full reproducing repository
