### ISSUE TITLE
Export CSV does not export Lens fields

### ISSUE THREAD

**Issue by morrislaptop** [laravel/nova-issues#4249]
- Laravel Version: 9.x
- Nova Version: 4.x
- PHP Version: 8.x
- Database Driver & Version: Postgres 12
- Operating System and Version: Mac 12.3
- Browser type and version: Chrome 101
- Reproduction Repository: ...

**Comment by crynobone** [comment]
The Export CSV uses database fields, you should add `withFormat()` 

<img width="782" alt="Screenshot 2022-05-16 at 6 50 34 AM" src="https://user-images.githubusercontent.com/172966/168497322-5275c89b-3e71-474b-9313-cafc75b7e434.png">

**Comment by morrislaptop** [comment]
@crynobone What about a Lens with a group by?
