### ISSUE TITLE
Missing translation of NotificationCenter

### ISSUE THREAD

**Issue by mateusz-peczkowski** [laravel/nova-issues#4256]
- Laravel Version: 9.12.2
- Nova Version: 4.5.4
- PHP Version: 8.0.16

### Description:
Once more me and translation problem :) 
NotificationCenter.vue line 33 and 35.
"Notifications" and "Mark all as Read" are plain texts

**Comment by davidhemphill** [comment]
These translations were added in 4.5.4. Make sure to run `php artisan publish --force` to ensure you have the latest assets.

**Comment by mateusz-peczkowski** [comment]
Hey. But I am not writing about the language file. Inside:
/vendor/laravel/nova/resources/js/components/Notifications/NotificationCenter.vue I see plain text inside lines 33 and 35
<img width="1166" alt="Zrzut ekranu 2022-05-26 o 15 15 25" src="https://user-images.githubusercontent.com/6013516/170495034-4dffb781-122d-4fb8-9428-695a35e82849.png">

I am on version 4.5.4

**Comment by davidhemphill** [comment]
These translations were added to the language file and used inside the UI. Update your Nova to make sure you have the latest assets:

<img width="812" alt="image" src="https://user-images.githubusercontent.com/58970/170533218-4825aaff-7873-47cd-9779-3bf8c2537ebd.png">
