### ISSUE TITLE
Index table glitch when clicking on checkbox

### ISSUE THREAD

**Issue by hivokas** [laravel/nova-issues#4258]
- Laravel Version: 9.11.0
- Nova Version: 4.5.4
- PHP Version: 8.0.15
- Operating System and Version: macOS 12.3.1
- Browser type and version: Chrome Version 101.0.4951.64 (Official Build) (x86_64)

### Description:

https://user-images.githubusercontent.com/22997803/168661546-cfd0cfa9-0484-4710-acc3-e4772f555803.mov

**Comment by davidhemphill** [comment]
Can you verify this behavior on a fresh Nova installation?

**Comment by morrislaptop** [comment]
I can!

**Comment by crynobone** [comment]
Please submit reproducing repository similar to https://github.com/nova-issues in order for us to debug the issue.

This was previously reported also without reproducing repository. See #4164

**Comment by hivokas** [comment]
@crynobone done: https://github.com/hivokas/issue-4258

It seems to be happening only when resource is not authorized to be deleted.

**Comment by AndreasFurster** [comment]
Same issue here. I've a policy with create and delete disallowed. 

@crynobone can this get fixed? It makes applying actions on multiple resources very annoying.
