### ISSUE TITLE
[feature request] Readonly Resources

### ISSUE THREAD

**Issue by disitec** [laravel/nova-issues#426]
We are dealing with this and we can't find documentation about it.

What about when you want to list, filter, and show a resource but not letting user to create and update it? Think on stripe transactions.

Is there a way to handle that?

**Comment by albalooshi** [comment]
@disitec Try creating a [policy](https://laravel.com/docs/5.6/authorization#creating-policies) for the model that linked to the resource, make sure you return false for the create and update and delete methods, you can [read more about it here ](https://nova.laravel.com/docs/1.0/resources/authorization.html#authorization)

Let me know how it works out for you.

**Comment by lesterchan** [comment]
Here is what I did

In app/Policies/ReadOnlyPolicy.php
```
<?php

namespace App\Policies;

use Illuminate\Auth\Access\HandlesAuthorization;
use App\User;

class ReadOnlyPolicy
{
    use HandlesAuthorization;

    /**
     * Determine whether the user can view the word press post.
     *
     * @param  \App\User $user
     *
     * @return bool
     */
    public function view(User $user): bool
    {
        return true;
    }

    /**
     * Determine whether the user can create word press posts.
     *
     * @param  \App\User $user
     * @return mixed
     */
    public function create(User $user): bool
    {
        return false;
    }

    /**
     * Determine whether the user can update the word press post.
     *
     * @param  \App\User $user
     *
     * @return bool
     */
    public function update(User $user): bool
    {
        return false;
    }

    /**
     * Determine whether the user can delete the word press post.
     *
     * @param  \App\User $user
     * @return bool
     */
    public function delete(User $user): bool
    {
        return false;
    }

    /**
     * Determine whether the user can restore the word press post.
     *
     * @param  \App\User $user
     *
     * @return bool
     */
    public function restore(User $user): bool
    {
        return false;
    }

    /**
     * Determine whether the user can permanently delete the word press post.
     *
     * @param  \App\User $user
     *
     * @return bool
     */
    public function forceDelete(User $user): bool
    {
        return false;
    }
}
```

In app/Providers/AuthServiceProvider.php
```
<?php

namespace App\Providers;

use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
use App\Policies\ReadOnlyPolicy;

class AuthServiceProvider extends ServiceProvider
{
    /**
     * The policy mappings for the application.
     *
     * @var array
     */
    protected $policies = [
        \App\User::class => ReadOnlyPolicy::class,
		\App\Post::class => ReadOnlyPolicy::class,
		\App\Comment::class => ReadOnlyPolicy::class,

    ];

    /**
     * Register any authentication / authorization services.
     *
     * @return void
     */
    public function boot(): void
    {
        $this->registerPolicies();
    }
}
```

**Comment by disitec** [comment]
Policies are fine but what about when you want to restrict access only for nova creation and let frontend work without restrictions? Stripe Transactions again.

I see something missing here, maybe an API like this `protected $showCrateForm = false`

I'll play with policies and see what can I achieve.

**Comment by albalooshi** [comment]
@disitec 
**Warning** This is a workaround hack until this feature implemented by the developer. 

Try [extending the model](https://tighten.co/blog/extending-models-in-eloquent) and adding policies and resources to the extended model. This way the frontend will work fine with the original model while Nova is working with the restricted extended model.

**Comment by laraning** [comment]
Actually Tighten made a package to easy extend models that I also use. Allows me to have different resource models in Nova applying different global scopes.

https://github.com/tightenco/parental

**Comment by albalooshi** [comment]
@laraning Looks awesome thanks! However its still in early stages of development so I still recommend the blog post.

**Comment by dillingham** [comment]
Im seeing a `Laravel\Nova\Authorizable` trait which `Resource` inherits from, with methods like `authorizeToCreate`, not sure how to use it haha but it seems like what you're looking for. I remember seeing in the laracon demo that create buttons disappear and such

**Comment by laraning** [comment]
The create button dissapears if you return false from the “create” method in the model policy.

**Comment by hubertnnn** [comment]
I can see the issue as well. 
The problem is not being able to say that something should be edited or not, but having different permissions on admin panel and in frontend application.

One solution I would see is to have a method that will tell if we are in Nova or not.
this way a policy that solves original issue could look like this:

    public function create(User $user)
    {
        if(Nova::active()) {
            //We are in admin panel
            return false;
        }
        return true;
    }

**Comment by taylorotwell** [comment]
Policies already do this.

**Comment by yuqinghong** [comment]
我希望`BelongsTo::make()`的字段能后只读显示，可能已经有还的解决方法了， 但楼上的评论都是英文， 表示看不懂！

**Comment by telkins** [comment]
> To only effect the Nova resource and add any of these to the resource, no policy needed:
> 
> ```
> public static function authorizedToCreate(Request $request){
>     return false;
> }
> public function authorizedToDelete(Request $request){
>     return false;
> }
> public function authorizedToUpdate(Request $request){
>     return false;
> }
> ```

Looks good.  What about for nested resources...?  That is, a resource that has a relationship with itself.  So, you want to create, update, and delete the resource, but when showing the resource detail, which includes the *nested* resource relation, have it be read-only...?

(If that didn't make sense, let me know and I'll try to provide an example.)

**Comment by stephan-v** [comment]
> To only effect the Nova resource and add any of these to the resource, no policy needed:
> 
> ```
> public static function authorizedToCreate(Request $request){
>     return false;
> }
> public function authorizedToDelete(Request $request){
>     return false;
> }
> public function authorizedToUpdate(Request $request){
>     return false;
> }
> ```

This should be made into a trait honestly. In a lot of cases you don't want to be using policies for this.

**Comment by vesper8** [comment]
> > To only effect the Nova resource and add any of these to the resource, no policy needed:
> > ```
> > public static function authorizedToCreate(Request $request){
> >     return false;
> > }
> > public function authorizedToDelete(Request $request){
> >     return false;
> > }
> > public function authorizedToUpdate(Request $request){
> >     return false;
> > }
> > ```
> 
> This should be made into a trait honestly. In a lot of cases you don't want to be using policies for this.

This doesn't hide other buttons such as the 'edit attached' and 'detach' buttons. Also when using checkbox to select multiple he delete button still appears
