### ISSUE TITLE
Lens's filters doesn't query properly

### ISSUE THREAD

**Issue by mehrancodes** [laravel/nova-issues#4265]
- Laravel Version: 9.7.0
- Nova Version: 4.5.4
- PHP Version: 8.1
- Database Driver & Version: Mysql 8
- Operating System and Version: Mac
- Browser type and version: Chrome

### Description:
I just added some filters to my lens and tried to test out them but when I try to apply a filter on the lens page, it doesn't filter the records. seems like the query doesn't get apply at all.

**Comment by crynobone** [comment]
Please submit reproducing repository similar to https://github.com/nova-issues in order for us to debug the issue.

**Comment by crynobone** [comment]
Closing this as stale at the moment, feel free to create a new issue with a full reproducing repository

**Comment by mehrancodes** [comment]
Unfortunately, I haven't had enough time to reproduce it but I have clearly described how to do it yourself. You just need to create a lens and then add a filter class and test if it works or not!

**Comment by crynobone** [comment]
Our `nova-dusk-suite` already include the use case which doesn't have the described issue. https://github.com/laravel/nova-dusk-suite/blob/master/tests/Browser/LensFilterTest.php
