### ISSUE TITLE
Too long string breaks layout on mobile

### ISSUE THREAD

**Issue by syntafin** [laravel/nova-issues#4268]
- Laravel Version: v9.12.2
- Nova Version: 4.5.4 
- PHP Version: 8.1.5
- Database Driver & Version: 
- Operating System and Version: Ubuntu/20.04
- Browser type and version: Chrome 101
- Reproduction Repository: Private

### Description:
If you show a string with to many characters, it will break the layout on mobile.
For example:

This will work: 3LqTxv7SpDWc0Gl6IUAdLe2lS9fg1iVnXOSIEI2iRKaw

This is to long (64 characters): 3LqTxv7SpDWc0Gl6IUAdLe2lS9fg1iVnXOSIEI2iRKawOdFTUHqXDOhy3t9fXJA0

Workaround is to shorten the name displayed inside the nova Frontend.
Screenshot for details ![Screenshot_20220517-233736~2.png](https://user-images.githubusercontent.com/695535/168934409-250f1236-248e-488b-8446-52e172a7bfc4.png)

**Comment by syntafin** [comment]
So this will get a official fix, or still needed to use a workaround as described in initial post?

**Comment by crynobone** [comment]
PR has been merged and automatically close this issue.

Will bw available on the next release.

**Comment by syntafin** [comment]
![image](https://user-images.githubusercontent.com/695535/170838769-12111af2-70b8-445b-ba89-980aed774fbd.png)

Problem is still there if I print out the full string.

Nova 4.7, depending the release notes it should be fixed:
