### ISSUE TITLE
Having Relationships Breaks Global Search

### ISSUE THREAD

**Issue by CraigHarley** [laravel/nova-issues#427]
Searching for the first few characters of my username, works until adding relationships.

After adding relationships to a couple of models the global search component tries to find results from the name of the class in the relationship, as though it's a column on the db.

![image](https://user-images.githubusercontent.com/8432365/45042291-45416f80-b062-11e8-86b2-6e5fa2931952.png)
![image](https://user-images.githubusercontent.com/8432365/45042360-6b670f80-b062-11e8-9cb4-102a6ec27bfe.png)

It should be searching against the correct fields.

Version 1.08

**Comment by davidhemphill** [comment]
Can you post a gist example we could use to diagnose the issue?

**Comment by CraigHarley** [comment]
Ah this is my mistake. Basically I've done this in my Nova resource:
```
public static $search = [
        'Region',
        'Continent',
        'Country',
        'Airport',
        'Accommodation',
        'Location',
];
```

Is there a way to specify fields from a relationship to search?
I'd like to just be able to filter the name column for the records. Something like this would be great:

```
public static $search = [
        'Region.name',
        'Continent.name',
        'Country.name',
        'Airport.name',
        'Accommodation.name',
        'Location.name',
];
```

**Comment by davidhemphill** [comment]
Currently this isn't supported. You could use Scout and include those fields when configuring your searchable data: https://laravel.com/docs/5.7/scout#configuring-searchable-data

**Comment by glennwilton** [comment]
Not done a lot of testing but adding Inner Joins to the Index Query meant I was able to search on Relationships

Just had to make sure I added in 'jobs.*' else nothing appears


```
class Job extends Resource
{
    public static function indexQuery(NovaRequest $request, $query)
    {
        return
            $query
                ->select('jobs.*', 'campaigns.campaignTitle', 'customerAssets.custAssetDescription')
                ->leftJoin('campaigns', 'campaigns.campaignID', '=', 'jobs.campaignID')
                ->leftJoin('customerAssets', 'customerAssets.customerAssetID', '=', 'jobs.customerAssetID')

        ;
    }
```

And in the search fields
```
    public static $search = [
        'customerID','jobTitle', 'campaigns.campaignTitle', 'customerAssets.custAssetDescription'
    ];
```
