### ISSUE TITLE
scrollbar disappears half the time

### ISSUE THREAD

**Issue by jaxramus** [laravel/nova-issues#4271]
- Laravel Version: 9
- Nova Version: 4.6
- PHP Version: 8
- Operating System and Version: mac monterey
- Browser type and version: chrome 101.0.4951.64
- 
### Description:

i noticed that when visiting a form or detail page that should have a scrollbar, sometimes the scrollbar does not show up giving the user no way to scroll the content on the page. this seems to happen every other visit to the page, and whats weird is the scrollbar appears momentarily when clicking away from the page.

here is a video of this happening: https://imgur.com/a/PDfrgNG

**Comment by ianrobertsFF** [comment]
For anyone maintaining their own private fork this is a regression from the `@click="toggleMainMenu"` change in `MenuItem.vue` toggling `mainMenuShown`. This sets it to true every other time you use the main menu on desktop and thus hides the scrollbars on body.

**Comment by StanBarrows** [comment]
Having the same issues here. This makes it currently not possible to scroll through a index page with more entries then visible on the current screen size.

No Scrollbar on initial page request.
<img width="1312" alt="CleanShot 2022-05-18 at 11 27 17@2x" src="https://user-images.githubusercontent.com/10268813/169006600-b2f493e5-bacb-4a11-a829-5daec225427f.png">

After a page refresh, the Scrollbar is coming back.
<img width="1046" alt="CleanShot 2022-05-18 at 11 27 55@2x" src="https://user-images.githubusercontent.com/10268813/169006797-a6fbb364-f97c-4117-adb6-67325560efd0.png">

**Comment by crynobone** [comment]
A bugfix PR has been submitted, pending review and release by @davidhemphill 

In the meantime you can lock the version to `4.5.4`

**Comment by davidhemphill** [comment]
Merged. 👍

**Comment by davidhemphill** [comment]
Make sure you've updated Nova's assets with `php artisan nova:publish --force` to ensure you're using the latest assets.

**Comment by Akecel** [comment]
Issue is still happening for me to, even with last lest assets and the Nova version 4.6.0

**Comment by bashgeek** [comment]
Yes, for us, too, even on 4.6.1. Especially happening on Dashboards or Tools, Resources seem to be fine now. Can always reproduce not being able to scroll at all when going from a resource index to a dashboard (has to be higher than viewport obviously).

**Comment by Akecel** [comment]
This affects our resources on our side. It makes the scroll bar disappear after clicking on a particular resource from the index. A refresh of the page makes it reappear

**Comment by ianrobertsFF** [comment]
Its this: https://github.com/laravel/nova-issues/issues/4281

The `mainMenuShown` getter wasn't added to MenuSection.vue as well as MenuItem.vue, I imagine there will be a fix for it in the next release as its a simple fix.
