### ISSUE TITLE
[Request] MySQL/Postgres JSON Field Support

### ISSUE THREAD

**Issue by rkleinbc** [laravel/nova-issues#428]
With Laravel's [support for updating JSON fields](https://laravel.com/docs/5.7/queries#updating-json-columns), it would be great if Nova supported defining resource fields for data within a JSON column field (not just a code editor). Maybe a new JSON field type could accept an array mapping each JSON field key to an existing Nova field type. The JSON field could default to displaying as a separate Nova field panel.

Example (not sure if it's valid, but just an idea): 
```php
JSON::make('Options')->json(
   [ 
      'price' => Text::make('Price'),
      'color' => Select::make('Color')->options( \App\Color::getColors() )  
  ]
)
```

**Comment by robmpreston** [comment]
We were actually talking about implementing something like this today for one of our projects that has a flexible JSON field. 👍

**Comment by willmkt** [comment]
There is a package that does this already

https://novapackages.com/packages/fourstacks/nova-repeatable-fields

**Comment by moodslayer** [comment]
Is there anything like this except for relations?  For example, my **pet store** contains a hasMany relation with **pets**.  I can add x amount of pets to the store.  Basically repeatable fields but with relations instead of a JSON payload.

**Comment by disitec** [comment]
In case you are interested we just released a package for this. Take a look. Issues and PRs welcome!

https://novapackages.com/packages/64robots/nova-json

**Comment by olragon** [comment]
I think this should be handled by Nova instead of contrib packages.
I try to add field `options` with array of object style

```js
let simple = [
  {name: "size", values: ["sm", "md", "lg"]},
  {name: "fabric", values: ["cotton", "silk", "linen"]}
]

let nested = [
  {name: "color", values: [{ value: "#FF0000", label: 'Red' }, { value: "blue", label: "Blue" }, { value: "green": label: "Green" }]}
]
```

All contrib packages do not work, summary below:

| Feature | `nsavinov/nova-json-schema-field` | `fourstacks/nova-repeatable-fields` | `64robots/nova-json` |
| --- | --- | --- | --- |
| Nova native field |  |  | 👍 |
| Array of object |  | 👍 |  |
| JSON schema | 👍|  |  |
| Nested object | |  |  |

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
