### ISSUE TITLE
Action fields not showing when `standalone()` is applied

### ISSUE THREAD

**Issue by Livijn** [laravel/nova-issues#4288]
- Laravel Version: v8.83.9
- Nova Version: 3.32.0
- PHP Version: 8.0

### Description:
Action fields are not showing when `standalone()` is applied. They are shown if I remove `standalone()` but that requires that I select a User.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Create an action with fields and apply `standalone()` to it.

**Comment by crynobone** [comment]
![CleanShot 2022-05-21 at 10 36 33](https://user-images.githubusercontent.com/172966/169631075-1a9e9581-4ec2-4409-bffe-9248152bbb9e.gif)

Unable to reproduce.

**Comment by Livijn** [comment]
I ran composer update and now it works. Closing it.
