### ISSUE TITLE
Use non-default guard for Nova auth

### ISSUE THREAD

**Issue by tomhorvat** [laravel/nova-issues#43]
Is there a way to use alternative, non-default guard for Nova auth? I have set up admin guard that uses admin table/model and would like to use that guard for auth.

In my pre-Nova admin, i used auth:admin middleware.

Users are only using frontend.

https://devmarketer.io/learn/setting-multi-authentication-laravel-5-4-part-1/

**Comment by MattMangoni** [comment]
+1

I have an API that uses the api guard as default, but I'd like to manage the content with Nova, and I can't login as long as I don't make the web guard the default one.

**Comment by arnordhaenens** [comment]
Hi @tomhorvat.

I resolved this doing the following. 

1. Create a new custom middleware that extends the default Authenticate middleware coming with nova. In this middleware I just limit the allowed guards to the one I want to target (being admins in this case). 
```php
<?php

namespace App\Http\Middleware\Nova;

use Closure;

class Authenticate extends \Laravel\Nova\Http\Middleware\Authenticate
{
    /**
     * @param \Illuminate\Http\Request $request
     * @param Closure $next
     * @param mixed ...$guards
     * @return mixed
     * @throws \Illuminate\Auth\AuthenticationException
     */
    public function handle($request, Closure $next, ...$guards)
    {
        return parent::handle($request, $next, 'admins');
    }
}
```
2. Then, in `config/nova.php` I replace the default Authenticate middleware with the newly created one. 
3. Last step: In `nova/src/Http/Controllers/LoginController.php` I define the guard by overriding the `guard()` method
```php
<?php

namespace Laravel\Nova\Http\Controllers;

use Laravel\Nova\Nova;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Foundation\Auth\AuthenticatesUsers;
use Illuminate\Foundation\Validation\ValidatesRequests;

class LoginController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles authenticating users for the application and
    | redirecting them to your home screen. The controller uses a trait
    | to conveniently provide its functionality to your applications.
    |
    */

    use AuthenticatesUsers, ValidatesRequests;

    protected function guard()
    {
        return auth()->guard('admins');
    }
```

This last adjustment will resolve the issue of falling back to the default auth driver when actually executing the POST login request. 

@taylorotwell @davidhemphill  @themsaid  
Maybe an option to define the default guard to be used with Nova as a extra configuration option in `config/nova.php`?

@tomhorvat Also, instead of making adjustments in the default Nova `LoginController`, it might be better to overwrite the POST login route and point it to a custom controller, extending the default Nova LoginController, and defining the guard there.

**Comment by jkudish** [comment]
I implemented basically the same solution as @arnordhaenens with my own controller and middleware that I used to override the default one provided by Laravel. Would be awesome to see an option for this, as well as defining other types of login methods (e.g. passport #28 )

**Comment by judge2020** [comment]
As a non-middleware solution, you can change `nova/src/NovaApplicationServiceProvider.php` and change the guard (eg `Gate::check('nova.view', [$request->user()])`) however this will likely overwritten by upgrades.

**Comment by arnordhaenens** [comment]
@judge2020 With that approach you should then better overwrite the `authorization` method in `app/Providers/NovaServiceProvider`, which is available after installing Nova. 

This way changes won't be overwritten by upgrades.

**Comment by tomhorvat** [comment]
@arnordhaenens Thank you for explanation/example!

**Comment by chrisbjr** [comment]
I pretty much wasted almost half the day trying to make my custom guard work only to find this issue and seeing that I've done exactly what @arnordhaenens has done.

It would be great if `nova/src/Http/Controllers/LoginController.php` overrides the `guard()` method with something that can be set in `config/nova.php`:

```
    /**
     * Get the guard to be used during authentication.
     *
     * @return \Illuminate\Contracts\Auth\StatefulGuard
     */
    protected function guard()
    {
        return Auth::guard(config('nova.auth.guard'));
    }
```

@arnordhaenens is also right about having to apply similar adjustments for `ForgotPasswordController` and `ResetPasswordController`. Not sure what changes need to be done to get the guard from the config though.

**Comment by chrisbjr** [comment]
@themsaid can this be tagged as a request?

**Comment by arnordhaenens** [comment]
@chrisbjr In `config/nova.php` you can for example implement the following.

```php
<?php

// ....

    'auth'=>[
        'defaults' => [
            'guard' => 'web', // refers to the auth guard you want to use for Nova
            'passwords' => 'users', // refers to the password broker you want to use for Nova
        ],
    ],

// ....
```

In the Nova's `LoginController` for example, the default `guard()`  method could then implement something of the following. 

```php
<?php

    // ...

    /**
     * @return \Illuminate\Contracts\Auth\StatefulGuard|mixed
     */
    protected function guard()
    {
        return auth()->guard(config('nova.auth.defaults.guard'));
    }

   // ... 
```

The default broker, in for example `ResetPasswordsController` can be defined as following.

```php
<?php

    // ...
    /**
     * @return \Illuminate\Contracts\Auth\PasswordBroker
     */
    public function broker()
    {
        return \Password::broker(config('nova.auth.defaults.passwords'));
    }

```

Doing this, you won't have to overwrite the Controllers by default. 
Similar changes can then also be implemented to the `\Laravel\Nova\Http\Middleware\Authenticate`  middleware.

**Comment by chrisbjr** [comment]
hi @arnordhaenens thanks for the tip with `Password::broker()`. I have this perfectly working now.

**Comment by DenzoNL** [comment]
I would appreciate a feature like this as well as I'm using the package https://github.com/tymondesigns/jwt-auth which requires that the `api` guard uses the `jwt` driver by default, which breaks Nova completely.

**Comment by tomhorvat** [comment]
@davidhemphill @themsaid

> Maybe an option to define the default guard to be used with Nova as a extra configuration option in config/nova.php?

Would you consider making this a config option? To define default guard for Nova?

**Comment by jianminLee** [comment]
``` php
    //NovaServiceProvider
    protected function routes()
    {
        //Name nova Authenticate middleware，Laravel\Nova\Http\Middleware\Authenticate
        \Route::aliasMiddleware('nova.auth', Authenticate::class);
        Nova::routes()
//                ->withAuthenticationRoutes()
//                ->withPasswordResetRoutes()
                ->register();
    }

//config/nova.php
    'middleware' => [
        'web',
       'nova.auth:admin',  //Bring in parameters
        DispatchServingNovaEvent::class,
        BootTools::class,
        Authorize::class,
    ],
//LoginController
//The login controller is best rewritten because the nova constructor already uses the guest middleware //and is not passed in to the guard, which is bad.
//You can copy the nova login controller and add two new methods.
    //Modify the constructor
    public function __construct()
    {
        $this->middleware('nova.guest:admin')->except('logout');
    }
    //Use a different field as the login name
    public function username()
    {
        return 'name';
    }

    //Defining guard
    protected function guard()
    {
        return \Auth::guard('admin');
    }
```
I believe that these will be better in future versions, and there may be imperfections in the early stage.

**Comment by georgewritescode** [comment]
@arnordhaenens Thanks for your write up however, having implemented your steps I am still unable to login using the API guard when using this package for JWTs https://github.com/tymondesigns/jwt-auth. When i've moved things around to get the login to work I then run into errors accessing auth()->user(). Has anyone got it to work with JWT-Auth?

**Comment by HelgeSverre** [comment]
If you're only using the API routes without any web routes, you can simply change the default guard and password to the custom guard and passport table.


/config/auth.php
```php 
'defaults' => [
    'guard' => 'accounts',
    'passwords' => 'accounts',
],
```

**Comment by Frozire** [comment]
> If you're only using the API routes without any web routes, you can simply change the default guard and password to the custom guard and password table.
> 
> /config/auth.php
> 
> ```
> 'defaults' => [
>     'guard' => 'accounts',
>     'passwords' => 'accounts',
> ],
> ```

I am not sure how this works for you, Nova relies on the default guard being session based.

**Comment by HelgeSverre** [comment]
@Frozire  It works because i use Passport for the API guard and my own custom "account" guard as the default (read nova).

**Comment by amazingdetective** [comment]
> @HelgeSverre
> 
> > If you're only using the API routes without any web routes, you can simply change the default guard and password to the custom guard and password table.
> 
> I am not sure how this works for you, Nova relies on the default guard being session based; which is what is causing this problem. I think everyone here is using a 'custom' guard, that relies on JWT authentication, which Nova naturally doesn't support, but the problem would be solvable by being able to specify which guard Nova should use. (In all of our cases above, Web)
> 
> [#575 - Patch #4 for 1.0.16](https://github.com/laravel/nova-issues/issues/575) - Fixes all of these issues listed above, we just need some attention to it.

Is this not included yet? Or why is the issue closed? I have a custom domain AND using jwt - not sure why this wouldn't be done by default..

**Comment by davidhemphill** [comment]
We just added the ability to set a custom guard for Nova. Should come out in the next release.

**Comment by fullfullstack** [comment]
This worked for me:

`    'middleware' => [
        'web',
        'auth:admin',
//        Authenticate::class,
        DispatchServingNovaEvent::class,
        BootTools::class,
        Authorize::class,
    ],
`

**Comment by fullfullstack** [comment]
'middleware' => [
        'web',
        'auth:admin',
//        Authenticate::class,
        DispatchServingNovaEvent::class,
        BootTools::class,
        Authorize::class,
    ],

**Comment by fullfullstack** [comment]
```php

   'middleware' => [
        'web',
        'auth:admin',
//        Authenticate::class,
        DispatchServingNovaEvent::class,
        BootTools::class,
        Authorize::class,
    ],
```

**Comment by fullfullstack** [comment]
This worked for me:

```php
    'middleware' => [
        'web',
        'auth:admin',
//        Authenticate::class,
        DispatchServingNovaEvent::class,
        BootTools::class,
        Authorize::class,
    ],

```

**Comment by plunkettscott** [comment]
@davidhemphill This is only a partial solution. The ActionEvent model still points directly to the model for the users provider. See:

```php
 /**
     * Get the user that initiated the action.
     */
    public function user()
    {
        return $this->belongsTo(config('auth.providers.users.model'), 'user_id');
    }
```

This should point to the provider we have set in the custom guard. This causes the Actions to break, throwing a "Trying to get property of non-object" error as it looks for the user's name on the User. A temporary work-around is to change this in the vendor files, but that can be overwritten on next update.

**Comment by plunkettscott** [comment]
See this screenshots:

<img width="1169" alt="screen shot 2018-10-02 at 12 15 35 pm" src="https://user-images.githubusercontent.com/4952170/46364974-e9580f80-c63c-11e8-80eb-7dc003f01f65.png">

**Comment by jordy-wittouck** [comment]
@davidhemphill Nice work making this feature available however I added a custom guard with a custom authenticatable model. Login works fine, but password reset still looks up the default users table instead of the one of my custom guard.

**Comment by chrisbjr** [comment]
@davidhemphill @jordy-wittouck is right, password reset still looks up the default users. we need a config that would set that as well just like in `config/auth.php`:

```php
/*
    |--------------------------------------------------------------------------
    | Authentication Defaults
    |--------------------------------------------------------------------------
    |
    | This option controls the default authentication "guard" and password
    | reset options for your application. You may change these defaults
    | as required, but they're a perfect start for most applications.
    |
    */

    'defaults' => [
        'guard' => 'web',
        'passwords' => 'users',
    ],
```

**Comment by shalawani** [comment]
@davidhemphill are there any new news regarding the password resets?

**Comment by tanys123** [comment]
yes, we need something like @shalawani mentioned.

**Comment by chrisbjr** [comment]
@davidhemphill should we re-open this issue or make a new one?

**Comment by connor11528** [comment]
Can't you add a guard to config/auth.php?

Possible solution here: https://medium.freecodecamp.org/multiple-authentication-in-laravel-5-6-admin-and-user-3b3efe6da999

**Comment by Frozire** [comment]
> Can't you add a guard to config/auth.php?
> 
> Possible solution here: https://medium.freecodecamp.org/multiple-authentication-in-laravel-5-6-admin-and-user-3b3efe6da999

Yes, and that works for Laravel, but this issue is about specifying the guard for Nova. 

Because of this issue, we git a new config that solved the initial issue, but the password controllers still use default rather than the new Nova config specified ones.

**Comment by basepack** [comment]
@davidhemphill is there any news on this one? 

Could you also please reopen the issue because it partially exists at the moment.

**Comment by nenads** [comment]
Hi,

Same apply when you want to pass array, we know that under the hud guards are array. 

'guard' => env('NOVA_GUARD', ['web','admin']),

Yes i can override default App\Nova\Http\Middleware\Authenticate and add in line 29
`
if (! empty($guard)) {
                //$guards[] = $guard;
                $guards = array_unique(array_merge($guards, $guard));
            }
`
but it feels it is more a bug then a feature/

**Comment by basepack** [comment]
+1

@davidhemphill can you mark this as a feature request?

**Comment by nenads** [comment]
> Hi,
> 
> Same apply when you want to pass array, we know that under the hud guards are array.
> 
> 'guard' => env('NOVA_GUARD', ['web','admin']),
> 
> Yes i can override default App\Nova\Http\Middleware\Authenticate and add in line 29
> `//$guards[] = $guard;`
> ` $guards = array_unique(array_merge($guards, $guard));`
> 
> but it feels it is more a bug then a feature/

This approach has issue with logout routes. As Fix 

1.copy: Laravel\Nova\Http\Middleware\Authenticate to App\Nova\Http\Middleware\Authenticate 
2. rename class namespace
3. line 25 $guard = config('nova.guards');
4. line 28 $guards = array_unique(array_merge($guards, explode(',', $guard)));
5. replace in nova config: //use Laravel\Nova\Http\Middleware\Authenticate;
                                            use App\Nova\Http\Middleware\Authenticate;
6. add new config 'guards' => env('NOVA_GUARDS', 'web,admin-web'), in nova.config

This way Auth will add all guards that we test against.  env('NOVA_GUARD') becomes kinda depricated, but this will keep compatibility with other code.

If anybody see any sec issue please contact me.

**Comment by nenads** [comment]
> +1
> 
> @davidhemphill can you mark this as a feature request?

How you mark as feature request ?

i see this as issue. since nova code is tight with NOVA_GUARD, i don't see normal way of adding them without beeing "hack".

**Comment by nenads** [comment]
> @davidhemphill @jordy-wittouck is right, password reset still looks up the default users. we need a config that would set that as well just like in `config/auth.php`:
> 
> ```
> /*
>     |--------------------------------------------------------------------------
>     | Authentication Defaults
>     |--------------------------------------------------------------------------
>     |
>     | This option controls the default authentication "guard" and password
>     | reset options for your application. You may change these defaults
>     | as required, but they're a perfect start for most applications.
>     |
>     */
> 
>     'defaults' => [
>         'guard' => 'web',
>         'passwords' => 'users',
>     ],
> ```

#1292

**Comment by andru-h** [comment]
@davidhemphill It would be great to be able to define the passwords configuration to be used for Nova.

Currently using the custom guard in `config.nova.guard`

Would you consider adding a `config.nova.passwords` ??

**Comment by thestepafter** [comment]
My team and I are looking to do this as well. Is there any plan to implement these requests @davidhemphill?

**Comment by chrisbjr** [comment]
I've submitted a pull request that fixes the said issues but it is still pending a review from @taylorotwell

**Comment by jacurtis** [comment]
@chrisbjr If you have submitted a pull request, you should link to it here so that we can all go upvote it, comment on it, and make it happen.

**Comment by taeo** [comment]
Dumbfounded how this issues was closed with simply:
> We just added the ability to set a custom guard for Nova. Should come out in the next release.

No how-to or documentation. Not fixed. 🤦🏻‍♂️

**Comment by colemvn** [comment]
> I've submitted a pull request that fixes the said issues but it is still pending a review from @taylorotwell

Any news on this?

**Comment by chrisbjr** [comment]
so... it's been more than a year.... we've already given up on Nova. Sorry, @jacurtis I wasn't able to post the link to the PR but it was closed for inactivity by @davidhemphill. Maybe someone can continue it. Also, not sure if this has been resolved in the previous releases. Most likely not though.

Here is the pull request:
https://github.com/laravel/nova/pull/291

**Comment by thestepafter** [comment]
We went with a different solution as well because this wasn't fixed.

**Comment by chrisbjr** [comment]
I can't believe that if I want an issue fixed, I'd have to make a PR for it, maintainer demands I write tests for it, and when I don't, they close the PR and never resolve the issue. I mean, Nova is a paid product. I'm all for contributing to projects, but this scenario doesn't seem fair. This is a fairly simple issue with a proposed fix in place made by its customers but is ignored.

I love Laravel and I happily pay and use all Laravel products, but the Nova experience has left me totally disappointed.

**Comment by jbunning** [comment]
You can do this by simply changing:

App\Nova\User.php:
 `public static $model = 'App\\User';` ->  `public static $model = 'App\\Admin';`

And adding `NOVA_GUARD=admin` to your .env file

:)

**Comment by nikita-yunoshev** [comment]
> Hi @tomhorvat.
> 
> I resolved this doing the following.
> 
> 1. Create a new custom middleware that extends the default Authenticate middleware coming with nova. In this middleware I just limit the allowed guards to the one I want to target (being admins in this case).
> 
> ```
> <?php
> 
> namespace App\Http\Middleware\Nova;
> 
> use Closure;
> 
> class Authenticate extends \Laravel\Nova\Http\Middleware\Authenticate
> {
>     /**
>      * @param \Illuminate\Http\Request $request
>      * @param Closure $next
>      * @param mixed ...$guards
>      * @return mixed
>      * @throws \Illuminate\Auth\AuthenticationException
>      */
>     public function handle($request, Closure $next, ...$guards)
>     {
>         return parent::handle($request, $next, 'admins');
>     }
> }
> ```
> 
> 1. Then, in `config/nova.php` I replace the default Authenticate middleware with the newly created one.
> 2. Last step: In `nova/src/Http/Controllers/LoginController.php` I define the guard by overriding the `guard()` method
> 
> ```
> <?php
> 
> namespace Laravel\Nova\Http\Controllers;
> 
> use Laravel\Nova\Nova;
> use Illuminate\Http\Request;
> use Illuminate\Routing\Controller;
> use Illuminate\Foundation\Auth\AuthenticatesUsers;
> use Illuminate\Foundation\Validation\ValidatesRequests;
> 
> class LoginController extends Controller
> {
>     /*
>     |--------------------------------------------------------------------------
>     | Login Controller
>     |--------------------------------------------------------------------------
>     |
>     | This controller handles authenticating users for the application and
>     | redirecting them to your home screen. The controller uses a trait
>     | to conveniently provide its functionality to your applications.
>     |
>     */
> 
>     use AuthenticatesUsers, ValidatesRequests;
> 
>     protected function guard()
>     {
>         return auth()->guard('admins');
>     }
> ```
> 
> This last adjustment will resolve the issue of falling back to the default auth driver when actually executing the POST login request.
> 
> @taylorotwell @davidhemphill @themsaid
> Maybe an option to define the default guard to be used with Nova as a extra configuration option in `config/nova.php`?
> 
> @tomhorvat Also, instead of making adjustments in the default Nova `LoginController`, it might be better to overwrite the POST login route and point it to a custom controller, extending the default Nova LoginController, and defining the guard there.

Why does this answer have such positive feedback? This guy changes the code of the Nova source while it should remain untouched!

**Comment by jbrooksuk** [comment]
Nova now supports custom auth guards and will support customising the password broker in the next release.

**Comment by isometriq** [comment]
> Nova now supports custom auth guards and will support customising the password broker in the next release.

Is there documentation about this?

**Comment by beneyraheem** [comment]
How to return the correct user name, now it always returns as Nova User

From ActionResource

`Text::make(__('Action Initiated By'), function () {
                return $this->user->name ?? $this->user->email ?? __('Nova User');
            }),`
