### ISSUE TITLE
Can't use another name for a resource in the menu

### ISSUE THREAD

**Issue by pierrepavlov** [laravel/nova-issues#4304]
- Laravel Version: 8.83.13
- Nova Version: 4.6.1
- PHP Version: 8.0.7
- Database Driver & Version: MySQL (Homebrew) 5.7.32
- Operating System and Version: MacOS 12.3.1
- Browser type and version: Brave 1.38.115
- Reproduction Repository: none

### Description:
It looks like you can't use another name for a resource in the menu. If you pass the name like it's being showed in the documentation you get a "Class not found" error.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Add the following code inside of the NovaServiceProvider.php file:
```
Nova::mainMenu(function(Request $request) {
    return [
        MenuItem::resource('test', User::class)
    ];
});
```

**Comment by crynobone** [comment]
Define the path and title manually instead of using the resource helper if you want full customisation.

**Comment by pierrepavlov** [comment]
Okay, then maybe you could update the documentation?

<img width="821" alt="Screenshot 2022-05-23 at 14 30 56" src="https://user-images.githubusercontent.com/1861083/169819726-4d002161-b646-4e58-a265-43b520ff3ec5.png">

**Comment by pierrepavlov** [comment]
@crynobone Okay, thanks! Well that's what I'm getting from nova.laravel.com  🤷‍♂️

**Comment by crynobone** [comment]
![Screenshot_20220523-204559_Chrome.jpg](https://user-images.githubusercontent.com/172966/169822320-8ea3e665-9c99-4a25-ae45-2d7f490bb8d8.jpg)

**Comment by pierrepavlov** [comment]
Yeah absolutely! I just wanted to make sure that you knew that I'm apparently seeing this old cached version, if anyone else will come with the same issue in the future!
