### ISSUE TITLE
Resource > Details > Soft Deleted badge incorrect style in dark mode

### ISSUE THREAD

**Issue by dmason30** [laravel/nova-issues#4305]
- Nova Version: 4.6.1

### Description:

When viewing the details of a soft deleted resource a 'SOFT DELETED' badge shows next to the title:
<img width="423" alt="image" src="https://user-images.githubusercontent.com/20278756/170030504-7d5bb54c-c21d-4e9f-aaeb-655c2ecf33c1.png">

However, this is dark mode but it is using the badge style of light mode. 

### Fix:

This component needs to add classes `dark:bg-red-400 dark:text-red-900` or be changed to use the `Badge.vue` component 😉 

<img width="455" alt="image" src="https://user-images.githubusercontent.com/20278756/170030989-88b60406-1633-4196-987b-9391e35ea032.png">

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
