### ISSUE TITLE
depondsOn fields

### ISSUE THREAD

**Issue by m4riachi** [laravel/nova-issues#4307]
- Laravel Version: 9.13.0
- Nova Version: 4.6.0
- PHP Version: 8.1.0
- Database Driver & Version: Mysql
- Operating System and Version: Ubuntu 22.04
- Browser type and version: Firefox 100.0.2
- Reproduction Repository: https://github.com/m4riachi/nova

### Description:

I have 3 fields 

- The second one depondsOn the first
- The third one depondsOn the second

If i fill the first i see the change on the second but i get the null value on the third, i have to do a change in the second to get a correct value

app/Nova/Reservation/ReservationInformation.php

**Comment by crynobone** [comment]
Duplicate of #4303

**Comment by m4riachi** [comment]
Its not the same bug, it's another one

**Comment by crynobone** [comment]
Create a new issue with details description, "dependsOn issue" with some code snippet doesn't explain much.
