### ISSUE TITLE
Login.vue attempt method logic not being interpreted properly by browser

### ISSUE THREAD

**Issue by tschmidiger** [laravel/nova-issues#4308]
- Laravel Version: v9.14.0
- Nova Version: v4.6.1
- PHP Version: 8.1.2
- Database Driver & Version:
- Operating System and Version: Windows 11
- Browser type and version: Chrome, Firefox

### Description:

I hooked into the login process in order to implement a two-factor authentication using Fortify. Therefore I set a redirect response for the (overridden) login controller which Nova's **Login.vue** should redirect then to a custom two-factor challenge screen:

```
async attempt() {
    const { redirect } = await this.form.post(Nova.url('/login'))

    if (redirect !== undefined && redirect !== null) {
        window.location.href = redirect
    }

    Nova.visit('/')
},
```

This would actually work, but however the Nova.visit command is being hit before the window.location.ref takes effect. And since the visit command tries to open the Nova dashboard, which is being prevented by my two-factor-middleware, I get redirected to the login screen again. If the attempt method in Login.vue would be as follows, the redirect would work properly:

```
async attempt() {
    const { redirect } = await this.form.post(Nova.url('/login'))

    if (redirect !== undefined && redirect !== null) {
        window.location.href = redirect
    } else {
        Nova.visit('/')
    }
},
```

**Comment by crynobone** [comment]
Can you submit reproducing repository to verify this issue since we already do have dusk tests covering this usage: https://github.com/laravel/nova-dusk-suite/blob/master/tests/Browser/AuthenticatesUserTest.php#L17-L31 

The reproducing repository similar to https://github.com/nova-issues would help us replicate the issue and cover it within our tests

**Comment by tschmidiger** [comment]
Here is the reproduction repo: https://github.com/tschmidiger/nova-login-test
You will find detailed instructions there...
