### ISSUE TITLE
Validating arrays

### ISSUE THREAD

**Issue by stevelacey** [laravel/nova-issues#431]
I want to validate some JSON fields for certain keys – is this supported/planned in Nova?

Ideally I want to share these rules between API endpoints and Nova so that they match – if they take the regular syntax thats pretty trivial.

This approach "works" – but leaves much to be desired:

```php
Code::make('Fields')->json()
    ->rules('required', function ($attribute, $value, $fail) {
        $data = [$attribute => json_decode($value, true)];

        $validator = \Validator::make($data, [
            'fields' => 'required|array',
            'fields.*.name' => 'required|string|max:255',
        ]);

        if ($validator->fails()) {
            return $fail($validator->errors());
        }
    }),
```

**Comment by stevelacey** [comment]
or... is the idea to use a FormRequest here? Is that possible?

**Comment by stevelacey** [comment]
Form request validation work solve this, lets say this is a duplicate of https://github.com/laravel/nova-issues/issues/106

**Comment by telkins** [comment]
@stevelacey Do you recall how you resolved this?  I'm making a `Code` field, too, that should only accept a (JSON) array.  I've kept things pretty simple, but it seems that I can't get it to work regardless of what I do.  😒 

Any help/advice would be appreciated. 🤓
