### ISSUE TITLE
Detailed view scroll lock

### ISSUE THREAD

**Issue by xiaoCreagia** [laravel/nova-issues#4311]
- Laravel Version: 9.13.0
- Nova Version: 4.6.1
- PHP Version: 8.1

duplicated of https://github.com/laravel/nova-issues/issues/4281 , bug still happens on version 4.6.1

![Captura de pantalla 2022-05-25 a las 17 28 21](https://user-images.githubusercontent.com/93589477/170300141-fd977d8f-597c-4aa6-9865-b88593491763.png)
![Captura de pantalla 2022-05-25 a las 17 29 16](https://user-images.githubusercontent.com/93589477/170300172-cec8a0a0-b0d7-4f13-9b36-e058d91b77cd.png)

**Comment by davidhemphill** [comment]
v4.7.0 was released today which should address this.
