### ISSUE TITLE
asHtml field not working

### ISSUE THREAD

**Issue by cloudstudio** [laravel/nova-issues#432]
Hello ! i try new faeature asHtml() not working for me :(

Laravel nova v1.0.10

Here some code :
![code](https://user-images.githubusercontent.com/3589377/45046832-a58edc00-b077-11e8-90d0-0b0017bad493.png)

Badge Blade :
![badge blade](https://user-images.githubusercontent.com/3589377/45046838-a9226300-b077-11e8-984f-19d99e100157.png)

I ignore is_active variable, and print some plain html just for try
![result](https://user-images.githubusercontent.com/3589377/45046847-ab84bd00-b077-11e8-8a88-c2029b91217e.png)

**Comment by bonzai** [comment]
Did you follow steps from [Updating Nova](https://nova.laravel.com/docs/1.0/installation.html#authorizing-nova) section?

**Comment by cloudstudio** [comment]
Wroking now, thanks guys !
