### ISSUE TITLE
When Run action Sorry! You are not authorized to perform this action

### ISSUE THREAD

**Issue by mohammadghole** [laravel/nova-issues#4320]
- Laravel Version: 7
- Nova Version:^3.7
- PHP Version: 7.4

### Description:
Hello,
I am created Nova Action to do Something, but when try to register action inside some nova resource  show me the message 
Sorry! You are not authorized to perform this action
but when register the same action on other nova resource working without any problem.

on other side : on local env I added this function to nova resource 

`      /**
     * Determine if the current user can view the given resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  string  $ability
     * @return bool
     */
    public static function authorizable()
    {
        return true;
    }

`
after added above function worked on local env but after pushed to staging env not working the same problem showing for me.

how can solve this issue, Thanks

**Comment by mohammadghole** [comment]
I found the solution but I don't Know if it is the best 
after I created new record by nova resource the action worked correctly but when I run action on old record in the same resource not created by nova recourse the action not working.

**Comment by crynobone** [comment]
Nova 3.7.0 was released June 2020 and there 43 patch releases since then to Nova 3. You should upgrade to latest Nova 3 and upgrade Laravel to version 8.
