### ISSUE TITLE
Method 'App\Nova\Customer::afterCreate()' is not compatible with method 'App\Nova\Resource::afterCreate()'.

### ISSUE THREAD

**Issue by 0proboy0** [laravel/nova-issues#4321]
- Laravel Version: 9.11
- Nova Version: 4.5.4
- PHP Version: 8.0.2
- Database Driver & Version: Mysql
- Operating System and Version: Windows 10 Pro
- Browser type and version: Google Chrome Version 101.0.4951.67

### Description:
In my Customer resource, I had this error:
`Method 'App\Nova\Customer::afterCreate()' is not compatible with method 'App\Nova\Resource::afterCreate()'.`

When I added this code:
```
public static function afterCreate(NovaRequest $request, Model $model)
{
        
}
```

Picture: 
![image](https://user-images.githubusercontent.com/14108109/170578114-4c40cabc-5ee8-4a0c-ba36-44cd2a9e47b4.png)

**Comment by crynobone** [comment]
We have seen similar report where Intelephense unable to read or understand methods coming from traits in parent class.

This should be reported to the VS Code Intelephense plugin repository.

**Comment by 0proboy0** [comment]
I opened the project on PhpStorm and it clearly indicated that Model (Illuminate\Database\Eloquent\Model) was not imported!
Stupid VS Code!
Stupid me!!
