### ISSUE TITLE
Heading dependsOn does not exist but it should

### ISSUE THREAD

**Issue by kichetof** [laravel/nova-issues#4327]
- Laravel Version: 9.14.1
- Nova Version: 4.7.0
- PHP Version: 8.1.5
- Database Driver & Version: mysql
- Operating System and Version: Laravel Sail
- Browser type and version: Brave

### Description:

As describe on #4260 and released on 4.7.0, Heading could use `dependsOn` but it doesn't work as expected.
`Method Laravel\Nova\Fields\Heading::dependsOn does not exist.`

### Detailed steps to reproduce the issue on a fresh Nova installation:

Add a Heading field with `dependsOn`:
```php
Heading::make('heading')
->hide()
->dependsOn(
    ['allowed'],
    function (Select $field, NovaRequest $request, FormData $formData) {
        if ($formData->allowed === 'null') {
            $field->show();
        }
    }
),
```

**Comment by ianrobertsFF** [comment]
Was just coming to post this

Looks like someone forgot to add `SupportsDependentFields` trait to the heading field.

Adding `use SupportsDependentFields` to your `vendor\laravel\nova\src\Fields\Heading.php` should sort it until next update
