### ISSUE TITLE
default path not working

### ISSUE THREAD

**Issue by Pamposgsk** [laravel/nova-issues#4330]
- Laravel Version: 9.0
- Nova Version: 4.7.0
- PHP Version: 8.0

Hi
After fresh install of nova version 4.7.0 on localhost if I change the path in nova.php to '/' instead of '/nova' I am getting "not found"
thanks

**Comment by crynobone** [comment]
Unable to reproduce.

**Comment by crynobone** [comment]
That's is expected  you need to remove the default routes from `routes/web.php` when you want to set `/`.

That's simplify something you need to do now.

**Comment by Pamposgsk** [comment]
You are a magician !!!Thanks a lot !!
