### ISSUE TITLE
Text color applied to logo is different in main nav/mobile nav

### ISSUE THREAD

**Issue by dwightwatson** [laravel/nova-issues#4331]
- Laravel Version: 9.14.1
- Nova Version: 4.7.0
- PHP Version: 8.1.6

### Description:

My Nova logo uses `fill="currentColor"` to be styled appropriately. This works in the main nav where it has `text-gray-900` and `dark:text-gray-400` applied to it.

However, the mobile nav is different and only has `text-black` applied to it. In dark mode this means the logo is black on a dark background.

Ideally the same text colours would be applied to both the main nav and mobile navs.

**Comment by dwightwatson** [comment]
Or, perhaps an alternative solution: apply a brand colour as the text colour for the logo.

**Comment by crynobone** [comment]
Shouldn't you be able to style the SVG directly, such as `<svg fill="currentColor" class="text-primary-500">`

**Comment by crynobone** [comment]
> Though I still think it's worth fixing the inconsistency of the text classes applied to the main/mobile logos.

Will look into that soon
