### ISSUE TITLE
No nova routes - /nova => page not found

### ISSUE THREAD

**Issue by robertotcestari** [laravel/nova-issues#434]
Tried `php artisan config:clear` and `php artisan route:clear` but none worked for me. Any ideas?

**Comment by dDevDreamer** [comment]
Are you sure you ran the following commands?
```
php artisan nova:install
php artisan migrate
``` 
https://nova.laravel.com/docs/1.0/installation.html#installing-nova

**Comment by outhebox** [comment]
the same issue here

**Comment by nicknick-io** [comment]
Read the docs, and don't skip any steps.

[Installing Nova](https://nova.laravel.com/docs/1.0/installation.html#installing-nova)

**Comment by davidhemphill** [comment]
Please list what steps we can take to reproduce your problem.

**Comment by robertotcestari** [comment]
Thanks found the solution here: in the NovaServiceProvider, the namespace was App\Providers. 
Since i have a custom app name, i had to change that as well and worked.
