### ISSUE TITLE
Back button from detail to index view causes JS error

### ISSUE THREAD

**Issue by jimarick** [laravel/nova-issues#4342]
- Nova Version: 4.7

### Description:
I open an item from a resource index page and view its detail page. Then I click the back button on the browser and encounter a JS error, and the index table fails to load. 

The error is from the file: webpack://laravel/nova/node_modules/@inertiajs/inertia/dist/index.js?8c55 

```
index.js?8c55:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toString')
    at u (index.js?8c55:1:2500)
    at eval (index.js?8c55:1:11411)
u @ index.js?8c55:1
eval @ index.js?8c55:1
Promise.then (async)
n.handleBackForwardVisit @ index.js?8c55:1
n.init @ index.js?8c55:1
setup @ index.js?4bf4:1
callWithErrorHandling @ runtime-core.esm-bundler.js?d2dd:155
setupStatefulComponent @ runtime-core.esm-bundler.js?d2dd:7056
setupComponent @ runtime-core.esm-bundler.js?d2dd:7012
mountComponent @ runtime-core.esm-bundler.js?d2dd:4922
processComponent @ runtime-core.esm-bundler.js?d2dd:4897
patch @ runtime-core.esm-bundler.js?d2dd:4489
componentUpdateFn @ runtime-core.esm-bundler.js?d2dd:5037
run @ reactivity.esm-bundler.js?89dc:167
setupRenderEffect @ runtime-core.esm-bundler.js?d2dd:5156
mountComponent @ runtime-core.esm-bundler.js?d2dd:4939
processComponent @ runtime-core.esm-bundler.js?d2dd:4897
patch @ runtime-core.esm-bundler.js?d2dd:4489
render @ runtime-core.esm-bundler.js?d2dd:5641
mount @ runtime-core.esm-bundler.js?d2dd:3877
app.mount @ runtime-dom.esm-bundler.js?2725:1590
liftOff @ app.js?ced6:205
(anonymous) @ users:56
```

### Detailed steps to reproduce the issue on a fresh Nova installation:
I haven't yet been able to replicate on a fresh installation. 
I have multiple custom fields, and as described in the docs have run:  npm --prefix='vendor/laravel/nova' ci
I have also enabled Vue Dev Tools as per:  https://nova.laravel.com/docs/4.0/customization/frontend.html#vue-devtools

**Comment by AbdullahGhanem** [comment]
up

**Comment by crynobone** [comment]
@AbdullahGhanem if you have similar issue with `nova-sortable` then this should be reported to the relevant repository. We can't fix `nova-sortable` bug and this issue tracker isn't meant for it.
