### ISSUE TITLE
[PR] Adding auto RTL support

### ISSUE THREAD

**Issue by NargesHajiani** [laravel/nova-issues#4353]
### Discussed in https://github.com/laravel/nova-issues/discussions/4306

<div type='discussions-op-text'>

<sup>Originally posted by **FaridAghili** May 25, 2022</sup>
Here I'm going to describe an easy and automated way for adding RTL theme to Nova v4.

**A little background:** I've developed a theme for Nova v3 to add RTL theme 3 years ago and it still works with latest v3 branch, it has ~23k installs:
https://github.com/pishran/nova-rtl-theme

For Nova 4 support, I've tried to find a better approach and here is my suggestion:

1. Add [postcss-rtlcss](https://github.com/elchininet/postcss-rtlcss) package to Nova's `package.json`.
2.  Add `postcssRtlcss` to Nova's `webpack.mix.js` as a postCss plugin:
```js
let postcssRtlcss = require('postcss-rtlcss')
...
.postCss('resources/css/app.css', 'public', [postcssImport(), tailwindcss('tailwind.config.js'), postcssRtlcss()])
```
3. Add a new key to Nova's config file for toggling RTL theme:
```php
...
'rtl' => true, // Defaults to false
...
```
4. In Nova's `layout.blade.php` file, add a `dir` attribute to `html` tag according to the config key added in step 3:
```blade
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" class="h-full font-sans antialiased"
      dir="{{ config('nova.rtl') ? 'rtl' : 'ltr' }}">
...
```

Done!

In this approach, no manual tweaking is required for users and it's also updates with Nova's internal developments when css codes change.

Let me know if there is anything I can do.
@taylorotwell @davidhemphill @crynobone</div>

**Comment by crynobone** [comment]
Please don't make duplicate issue on this. This is being review and we will make the changes when we are ready.
