### ISSUE TITLE
belongstomany hidden when use searchable

### ISSUE THREAD

**Issue by anditsung** [laravel/nova-issues#4357]
- Laravel Version: 9
- Nova Version: 3.32

<img width="1099" alt="Screen Shot 2022-06-02 at 15 43 04" src="https://user-images.githubusercontent.com/1090413/171591714-05750ff8-11cc-463d-bfc0-ab54c2d753db.png">

<img width="1093" alt="Screen Shot 2022-06-02 at 15 43 11" src="https://user-images.githubusercontent.com/1090413/171591741-da04e1db-ae00-4200-a6e1-a12801a56bce.png">

after fill the value then the field will be visible

**Comment by crynobone** [comment]
Expected limitation in Nova 3 and has been fixed in Nova 4 with Inertia.js
