### ISSUE TITLE
Unauthorised 401 response for API requests on the User model after Nova install 

### ISSUE THREAD

**Issue by adnanchowdhury** [laravel/nova-issues#436]
I just install Nova using the installation guide on the documentation. 

Now when I try to make a request on api that gets data from Users table, I get this error:
 

> Uncaught (in promise) Error: Request failed with status code 401

I can't figure out why this is. I had previously used [Voyager](https://laravelvoyager.com/) as an admin panel but I removed it before adding Nova. Could this be related?

**Comment by davidhemphill** [comment]
Can you post the full stack trace of the error from your Laravel log?

**Comment by taylorotwell** [comment]
We are unable to debug your issue without a recreatable code example.
