### ISSUE TITLE
Nova Menu CSS Missing

### ISSUE THREAD

**Issue by infinitypaul** [laravel/nova-issues#4364]
Laravel Version: 9.16.0
Nova Version: 4.7.0
PHP Version: 8.1.5
Database Driver & Version:
Operating System and Version: linux 5.10
Browser type and version: chrome 102

### Description:
I installed a new Nova Tool and my menu CSS isn't styled well anymore
<img width="287" alt="image" src="https://user-images.githubusercontent.com/15332137/171993627-c7e98368-f1b5-4445-8491-de4cca5772c4.png">

### Detailed steps to reproduce the issue on a fresh Nova installation:

I installed  a custom tool be doing the following

php artisan nova:tool infinitypaul/credit-check

Registered it in my App/Providers/NovaServiceProvider

Then I had manually define the tool's menu inside your custom Nova::mainMenu callback since I use a Customized Main Menu

then I enabled Vue Devtool locally by doing the following

cd ./vendor/laravel/nova
mv webpack.mix.js.dist webpack.mix.js
npm install
npm run dev
rm -rf node_modules
cd -
php artisan nova:publish

I did a hard refresh and my Nova menu started showing as attached

and not only the side menu this time around ,  the form input CSS is isn't reflecting

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/15332137/172088931-839f7e99-cf55-4d75-b485-ad7ac158eb5e.png">

**Comment by crynobone** [comment]
> I installed a new Nova Tool and my menu CSS isn't styled well anymore

Please provide reproducing repository detailing the steps and code used

**Comment by infinitypaul** [comment]
> > I installed a new Nova Tool and my menu CSS isn't styled well anymore
> 
> Please provide reproducing repository detailing the steps and code used

@crynobone description updated

**Comment by crynobone** [comment]
Unable to reproduce, see https://github.com/nova-issues/issue-4364/commit/21838e42b015d35fd6259776ed6f34024559cfe0 (changes to `public/vendor/nova/*` was purposely omitted).

<img width="1281" alt="Screenshot 2022-06-06 at 11 44 38 AM" src="https://user-images.githubusercontent.com/172966/172091484-46cf1a51-aa6f-45c2-b916-31506e10e449.png">
<img width="1287" alt="Screenshot 2022-06-06 at 11 45 44 AM" src="https://user-images.githubusercontent.com/172966/172091500-7adcaabc-e29b-4b46-9989-916e029d3da5.png">

**Comment by infinitypaul** [comment]
Thanks @crynobone an old package I did with Nova 3 was the cause of the CSS Conflict, I will close this now
