### ISSUE TITLE
Links doesnt open (only with MMB New Tab)

### ISSUE THREAD

**Issue by syntafin** [laravel/nova-issues#4365]
- Laravel Version: 9.16.0
- Nova Version: 4.7.0
- PHP Version: 8.1.6
- Database Driver & Version: mysql & MariaDB 10.6.8
- Operating System and Version: Local Arch Linux 2022.06.01, Staging Ubuntu 20.04.4
- Browser type and version: Brave 1.39.111 (Chromium 102.0.5005.61)
- Reproduction Repository: (Private)
### Description:
The Links to Resources, Dashboards, etc cant be open with a click.
On click the console shows the following error message:
```
index.js:1 
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toString')
```
Opening the Link with MMB (Third Mouse Button) in a New Tab/Window works as expected.

**Comment by fjsermu** [comment]
Same here! In my case, after update from Nova 3 to 4

**Comment by syntafin** [comment]
It seems to be only on local for me, and caused by a New Line before the JSON response.
![image](https://user-images.githubusercontent.com/695535/172024745-0b3e8aae-9e40-4e55-bfe1-c65e03ee8467.png)

**Comment by crynobone** [comment]
> Reproduction Repository: (Private)

You should be able to submit reproducing repository from a new example application, we are currently unable to replicate the same issue on our side.

**Comment by fjsermu** [comment]
Last update (Laravel nova 4.8.1) and php artisan nova:publish fixed my problem
