### ISSUE TITLE
Laravel\Nova\Macros::FirstDayOfPreviousQuarter has a incorrect hardcoded month in current month check

### ISSUE THREAD

**Issue by KevinHicksSW** [laravel/nova-issues#4369]
- Laravel Version: 9.14.11
- Nova Version: 4.0.7
- PHP Version: 8.1.2

### Description:
Inside Laravel\Nova\Macros\FirstDayOfPreviousQuarter, the code that checks for what the current month is to grab the correct date for the first day of the previous quarter is missing a check for the 6th month (June). Where the 6th-month check should be the 3rd month is being checked for a 2nd time. This is just a simple wrong hardcoded value causing this bug.

```
            } elseif (in_array($month, [4, 5, 3])) {
                return Carbon::createFromDate($year, 1, 1, $timezone)->startOfDay();
```

should be

```
            } elseif (in_array($month, [4, 5, 6])) {
                return Carbon::createFromDate($year, 1, 1, $timezone)->startOfDay();
```

### Detailed steps to reproduce the issue on a fresh Nova installation:
Set up any Nova Metric that has a QTD (Quarter To Date) range and try to load it when the current date is in June (6th month). The metric will crash with an error of trying to call copy() on null.

**Comment by crynobone** [comment]
This has been fixed and is pending next release.

In the meantime, you can add the following code to your value metrics:

```php
use Carbon\CarbonImmutable;

    /**
     * Calculate the previous quarter range.
     *
     * @param  string  $timezone
     * @return array<int, \Carbon\CarbonImmutable>
     */
    protected function previousQuarterRange($timezone)
    {
        return [
            CarbonImmutable::now($timezone)->subQuarterWithoutOverflow()->startOfQuarter(),
            CarbonImmutable::now($timezone)->startOfQuarter()->subSecond(),
        ];
    }
```
