### ISSUE TITLE
1.0.12 : Image field upload fail

### ISSUE THREAD

**Issue by DonDiegoAA** [laravel/nova-issues#438]
I receive no error, but the image is not saved anymore.
That was working perfectly with 1.0.8 (I missed the intermediate versions).

File field still work normally.

**Comment by michaelchunn** [comment]
Check your browser console for the error.  Maybe upload size limit on apache/nginx.

**Comment by DonDiegoAA** [comment]
The problem came from symlinks mess. It's working now.
