### ISSUE TITLE
Method Laravel\Nova\Fields\Trix::dependsOn does not exist

### ISSUE THREAD

**Issue by FrittenKeeZ** [laravel/nova-issues#4380]
- Laravel Version: 8.83.16
- Nova Version: 4.7.0

### Description:
Follow up on https://github.com/laravel/nova-issues/issues/4089
`Method Laravel\Nova\Fields\Trix::dependsOn does not exist`

### Detailed steps to reproduce the issue on a fresh Nova installation:
Just try and use `dependsOn` for a Trix field.

**Comment by ianrobertsFF** [comment]
https://nova.laravel.com/docs/4.0/resources/fields.html#dependent-fields

Trix isn't supported as a field that can either depend on, or be depended on.

**Comment by crynobone** [comment]
#4809 was only was fixed for Markdown.

Trix doesn't support dependsOn remains the same.

**Comment by FrittenKeeZ** [comment]
@crynobone okay, but why isn't it possible to add? I want to show a Trix field when a select has a certain value, and I can't see why that's very different from either Markdown or Code.

**Comment by crynobone** [comment]
It would most likely only work in certain condition but failed on others. It not that we haven't tried supporting it during the initial development.

The suggested issue only solve dynamic transition between hide and show method which was added after Dependent Field initial development.

**Comment by FrittenKeeZ** [comment]
Ahhh okay. I think something is better than nothing, so I hope you'll consider just adding visibility transitions (show/hide) for fields that don't support full dependency.
