### ISSUE TITLE
How to make some fields in a resource readonly or disabled in edit mode

### ISSUE THREAD

**Issue by zhouchang2017** [laravel/nova-issues#439]
How to make some fields in a resource readonly or disabled in edit mode

**Comment by albalooshi** [comment]
Check out my answer here https://github.com/laravel/nova-issues/issues/426#issuecomment-418598615

**Comment by hariesnurikhwan** [comment]
@albalooshi your suggestion seems to prevent the whole resource update.
AFAIK, you can achieve that by making [Custom Fields](https://nova.laravel.com/docs/1.0/customization/fields.html#fields) but obviously this needs to be in core.

**Comment by albalooshi** [comment]
@hariesnurikhwan 
Can you please check my latest comment and give your opinion? https://github.com/laravel/nova-issues/issues/426

**Comment by alexbowers** [comment]
This is coming in the next version:

https://github.com/laravel/nova-issues/issues/704
