### ISSUE TITLE
Display/Hide fields on form based on parent resource?

### ISSUE THREAD

**Issue by hariesnurikhwan** [laravel/nova-issues#440]
Title says it all, does it possible?

For example,
I have `Post` model and `Comment` model. I want to hide field certain field when making comment if the `Post` type is private.

**Comment by laraning** [comment]
Didn't totally understand but did you try to see the canSee() method ?

https://nova.laravel.com/docs/1.0/resources/authorization.html#fields

Might help.

**Comment by taylorotwell** [comment]
This repository is for tracking bugs. Feature requests may be emailed to Nova customer support.
