### ISSUE TITLE
Laravel Valet: Dependent Fields `dependsOn` Field Disappearing

### ISSUE THREAD

**Issue by jjjrmy** [laravel/nova-issues#4404]
- Nova Version: 4.8.1

https://nova.laravel.com/docs/4.0/resources/fields.html#dependent-fields
```php
use Laravel\Nova\Fields\FormData;
use Laravel\Nova\Fields\Select;
use Laravel\Nova\Fields\Text;
use Laravel\Nova\Http\Requests\NovaRequest;

Select::make('Purchase Type', 'type')
    ->options([
        'personal' => 'Personal',
        'gift' => 'Gift',
    ]),

// Recipient field configuration is customized based on purchase type...
Text::make('Recipient')
    ->readonly()
    ->dependsOn(
        ['type'], 
        function (Text $field, NovaRequest $request, FormData $formData) {
            if ($formData->type === 'gift') {
                $field->readonly(false)->rules(['required', 'email']);
            }
        }
    ),
```

Using this example exactly as shown, the `Recipient` is being shown on first load as `readonly`, when you change the `Purchase Type` field the `Recipient` field disappears and doesn't come back no matter what value you select.

**Comment by jjjrmy** [comment]
![ezgif-1-059d706b87](https://user-images.githubusercontent.com/1609800/173248879-eb495bd6-f6fa-491b-9342-b06c9e74c477.gif)

**Comment by jjjrmy** [comment]
This happens only when using Valet.
The request is returning many different things randomly

**Comment by jjjrmy** [comment]
```
127.0.0.1 - - [12/Jun/2022:17:04:30 -0400] "GET /vendor/nova/fonts/snunitosansv11pe0qmimslybiv1o4x1m8cce9i9tacvwo.woff2 HTTP/1.1" 200 11380 "http://nova-broken.test/vendor/nova/app.css?id=76f535e81fb0790088b65cbf509b0f6d" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.115 Safari/537.36"
127.0.0.1 - - [12/Jun/2022:17:04:30 -0400] "PATCH /nova-api/users/creation-fields?editing=true&editMode=create&field=recipient&component=text-field HTTP/1.1" 200 285 "http://nova-broken.test/nova/resources/users/new" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.115 Safari/537.36"
```

**Comment by RealityGamin** [comment]
Seems like dependsOn is broken in general

https://github.com/laravel/nova-issues/issues/4410

**Comment by crynobone** [comment]
> Seems like dependsOn is broken in general

No, we have multiple dusk tests covering the usage and none are failing at the moment. I still believe you are running an old JS files, or as @jjjrmy pointed out maybe a bug with Valet.

**Comment by jjjrmy** [comment]
I ran the same site with `php artisan serve` and it ran with no issues.
I also modified the dependentFields mixin to use another request method and pass `_method: patch` and that also ran with no issues.

So it's for sure an issue with Valet and the Patch request.

**Comment by jjjrmy** [comment]
I'm closing this issue because it randomly started working ... I didn't make any changes. Must have just been a computer issue.
