### ISSUE TITLE
DateTime Keyboard Input Error

### ISSUE THREAD

**Issue by StanBarrows** [laravel/nova-issues#4409]
- Laravel Version: 9.*
- Nova Version:  4.8.*
- PHP Version: 8.1
- Browser type and version: Chrome, Brave

### Description:

I've a DateTime field and set the current input to now()->toDateString().

```
  DateTime::make(__('backend/fields.shipping_date'), 'shipping_date')
                ->hideFromIndex()
                ->rules('required', 'date')
                ->default(function ($request) {
                    return now()->toDateString();
                }),
```

If I want to override or set the current value via keyboard input there is a strange behaviour. In the following video example I try to type in 12.12.2022. Somehow the input gets ignored.

https://user-images.githubusercontent.com/10268813/173251191-13712032-0366-4b22-bda3-8d18816e9a50.mp4

However defining the value via the Select-Menu is working.

**Comment by crynobone** [comment]
Why `now()->toDateString()` and not just `today()`
