### ISSUE TITLE
BelongsTo -> dependsOn is ignoring required() & select is ignoring required() as well

### ISSUE THREAD

**Issue by RealityGamin** [laravel/nova-issues#4410]
- Nova Version: 4.8

### Description:
```
Select::make('Type')->options([
                '0' => 'A',
                '1' => 'B',
                '2' => 'C',
                '3' => 'D',
            ])->required(),

BelongsTo::make('Bind User', 'users', 'App\Nova\User')
            ->dependsOn(
                ['type'],
                function (BelongsTo $field, NovaRequest $request, FormData $formData) {
                    if ($formData->type === 2) {
                        $field->readonly(false)->required();
                    }else{
                        $field->readonly(true)->nullable();
                    }
                }
            )

```
### Detailed steps to reproduce the issue on a fresh Nova installation:

It will show the star next to the field 100% on switching the type, but it will completely ignore the required field and will submit even when its null.

`->rules(['required'])`

did not work either

**Comment by RealityGamin** [comment]
Okay, looking further, I'm noticing that its also ignoring the dropdown required in general!
![image](https://user-images.githubusercontent.com/100086757/173258681-0ad70a8c-d238-4017-bb1c-fe11b65c1982.png)

![image](https://user-images.githubusercontent.com/100086757/173258711-ee17ee83-fe94-4979-856c-db0f493a9d22.png)

**Comment by crynobone** [comment]
Please read the documentation on `required()` and it's limitation

![image](https://user-images.githubusercontent.com/172966/173259201-3166ddfb-9830-4875-a0b6-368e4af50eb1.png)

**Comment by RealityGamin** [comment]
Rules required is being ignored as well, sorry for jot making that clear earlier, I was testing out multiple approaches, all being ignored on belongsTo when depends on

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/173264810-39a3f17a-52c7-418d-98fc-563f3bd92329.png)
![image](https://user-images.githubusercontent.com/172966/173264824-e5683d40-973f-472c-b28a-c7f3f0b0e6bf.png)
![image](https://user-images.githubusercontent.com/172966/173264827-736929ae-0834-4d9a-bb17-0a257ddfcc06.png)

Unable to reproduce, see https://github.com/nova-issues/issue-4410/commit/88bf6868cf64ec5ee4c3c3cb3c8aaaada41179dd
