### ISSUE TITLE
CSS variables all went missing

### ISSUE THREAD

**Issue by ramcda** [laravel/nova-issues#4411]
With the update to Tailwind v3 in 4.8 all of the root CSS color variables went missing except for a handful of the primary theme colors.  

Was it intentional to remove all of the colors?  Anyone who has a branded interface dependent upon any of these colors had their UI break.

:root {
	--colors-black: 0,0,0;
	--colors-white: 255,255,255;
	--colors-blue-50: 239,246,255;
	--colors-blue-100: 219,234,254;
	--colors-blue-200: 191,219,254;
	--colors-blue-300: 147,197,253;
	--colors-blue-400: 96,165,250;
	--colors-blue-500: 59,130,246;
	--colors-blue-600: 37,99,235;
	--colors-blue-700: 29,78,216;
	--colors-blue-800: 30,64,175;
	--colors-blue-900: 30,58,138;
	--colors-sky-50: 240,249,255;
	--colors-sky-100: 224,242,254;
	--colors-sky-200: 186,230,253;
	--colors-sky-300: 125,211,252;
	--colors-sky-400: 56,189,248;
	--colors-sky-500: 14,165,233;
	--colors-sky-600: 2,132,199;
	--colors-sky-700: 3,105,161;
	--colors-sky-800: 7,89,133;
	--colors-sky-900: 12,74,110;
	--colors-primary-50: 240,249,255;
	--colors-primary-100: 224,242,254;
	--colors-primary-200: 186,230,253;
	--colors-primary-300: 125,211,252;
	--colors-primary-400: 56,189,248;
	--colors-primary-500: 14,165,233;
	--colors-primary-600: 2,132,199;
	--colors-primary-700: 3,105,161;
	--colors-primary-800: 7,89,133;
	--colors-primary-900: 12,74,110;
	--colors-yellow-50: 254,252,232;
	--colors-yellow-100: 254,249,195;
	--colors-yellow-200: 254,240,138;
	--colors-yellow-300: 253,224,71;
	--colors-yellow-400: 250,204,21;
	--colors-yellow-500: 234,179,8;
	--colors-yellow-600: 202,138,4;
	--colors-yellow-700: 161,98,7;
	--colors-yellow-800: 133,77,14;
	--colors-yellow-900: 113,63,18;
	--colors-red-50: 254,242,242;
	--colors-red-100: 254,226,226;
	--colors-red-200: 254,202,202;
	--colors-red-300: 252,165,165;
	--colors-red-400: 248,113,113;
	--colors-red-500: 239,68,68;
	--colors-red-600: 220,38,38;
	--colors-red-700: 185,28,28;
	--colors-red-800: 153,27,27;
	--colors-red-900: 127,29,29;
	--colors-green-50: 240,253,244;
	--colors-green-100: 220,252,231;
	--colors-green-200: 187,247,208;
	--colors-green-300: 134,239,172;
	--colors-green-400: 74,222,128;
	--colors-green-500: 34,197,94;
	--colors-green-600: 22,163,74;
	--colors-green-700: 21,128,61;
	--colors-green-800: 22,101,52;
	--colors-green-900: 20,83,45;
	--colors-gray-50: 248,250,252;
	--colors-gray-100: 241,245,249;
	--colors-gray-200: 226,232,240;
	--colors-gray-300: 203,213,225;
	--colors-gray-400: 148,163,184;
	--colors-gray-500: 100,116,139;
	--colors-gray-600: 71,85,105;
	--colors-gray-700: 51,65,85;
	--colors-gray-800: 30,41,59;
	--colors-gray-900: 15,23,42;
}

**Comment by crynobone** [comment]
Should already be fixed in latest release

![image](https://user-images.githubusercontent.com/172966/174713818-77363ac0-c06a-4ad7-9242-09a5a964e128.png)

**Comment by vesper8** [comment]
@ramcda is this now working for you? I tried copying your styles in a theme.css loaded with `Nova::style('theme', resource_path('css/nova/theme.css'));`

And it has no affect.
