### ISSUE TITLE
Logo broken on phone portrait

### ISSUE THREAD

**Issue by RealityGamin** [laravel/nova-issues#4413]
Nova v4.8

Possibly due to tailwind 3 upgrade

But on landscape it's okay, I'm using Samsung S20+

![Screenshot_20220613-050425_Chrome Beta](https://user-images.githubusercontent.com/100086757/173262390-6d722cdf-7ce5-465f-8283-ae1fbff63d17.jpg)
![Screenshot_20220613-050416_Chrome Beta](https://user-images.githubusercontent.com/100086757/173262401-5f845fd4-38e9-42a5-abfa-e664cc4a2c68.jpg)

**Comment by crynobone** [comment]
Duplicate of #4393
