### ISSUE TITLE
Access to undeclared static property App\Providers\NovaServiceProvider::$model error

### ISSUE THREAD

**Issue by FSElias** [laravel/nova-issues#4414]
- Laravel Version: 9.17.0
- Nova Version: 4.8.1
- PHP Version: 8.1.2
- Database Driver & Version:
- Operating System and Version: Microsoft Windows.v10.0.19044.1706
- Browser type and version: Google Chrome.v102.0.5005.63 (Official Build) (64-bit)

### Description:
I am new with Nova and am unsure if I am doing something wrong here, after following the documentation of adding a menu item with a badge, I got the error:
Access to undeclared static property App\Providers\NovaServiceProvider::$model error

### Detailed steps to reproduce the issue on a fresh Nova installation:
php artisan make:model Order
php artisan nova:resource Order

add the following line in App\Nova\NovaServiceProvider.php

```php
    public function boot()
    {
        parent::boot();

        Nova::mainMenu(function (Request $request) {
            return [

                MenuSection::make('Orders', [
                    MenuItem::resource(Order::class)
                            ->withBadge(fn() => static::$model::count(), 'warning'),
                ])->icon('user')->collapsable(),
            ];
        });
    }
```

**Comment by crynobone** [comment]
That's just an example, you need to code your own logic.

**Comment by FSElias** [comment]
Yes, I am aware it is an example, and I can just use \App\Models\Order::count() instead of static::$model::count()
I wanted it to be more dynamic and I thought I did something wrong, anyway thank you.
