### ISSUE TITLE
relatableQuery Field Type Is Wrong

### ISSUE THREAD

**Issue by jjjrmy** [laravel/nova-issues#4419]
- Nova Version: 4.8.1

### Description:
I have a Resource `StepMap`, where you set where the user should go next, with a `MorphTo` field with types `Step` or `StepItem` and a second field `BelongsTo` `Step`. You don't want the Next Step `BelongsTo` field to be able to select the current step (would cause a loop), so that Id must be removed from the options.

```php
# Steppable:
MorphTo::make('Steppable')->types([
    FormStep::class,
    FormStepItemOption::class,
]),
# Next Step:
BelongsTo::make('Step', 'nextStep', FormStep::class),
```

https://nova.laravel.com/docs/4.0/resources/authorization.html#relationship-types

```php
public static function relatableSteps(NovaRequest $request, $query, Field $field)
{
    if (!($field instanceof MorphTo)) {
        return $query->whereNot('id', $request->viaResourceId);
    }

    return $query;
}
```

When you Create it works perfect. When you Update the resource, the field's `instanceof` is returning BelongsTo instead of MorphTo, so the MorphTo field is not showing it's resource.

**Comment by crynobone** [comment]
Submit a reproducing repository for us to debug the issue, you can use https://github.com/nova-issues for example
