### ISSUE TITLE
Strange behavior - resource not loading

### ISSUE THREAD

**Issue by RealityGamin** [laravel/nova-issues#4428]
- Nova Version: 4.9

### Description:

After last nights update, "randomly" and not sure why, when navigating between resources, the page just stops loading.

Sadly, there are no errors in the console :( is there any way to trace this to help report it? This happened on EDGE + Chrome 

Bare in mind, if i click on other resources to load, it will still hang, but if i refresh the page, it will go back to working normally.

![image](https://user-images.githubusercontent.com/100086757/173747804-dbf760aa-2b4f-4987-8e85-0fec59e3d571.png)
![image](https://user-images.githubusercontent.com/100086757/173748031-1692878a-86de-46ae-82d3-1a26d26ae088.png)

**Comment by crynobone** [comment]
Please provide reproducing repository for this issue, we haven't seen anyone else with a similar problem and we don't have enough information to determine the cause of your issue (any code or 3rd party package that may cause this).
