### ISSUE TITLE
checkbox field feature

### ISSUE THREAD

**Issue by kopiaman** [laravel/nova-issues#443]
Can we have checkbox field? I think a lot of applications require the checkbox field.

**Comment by peanut24** [comment]
Will Boolean field not suffice? It gives a checkbox on create / update

**Comment by hariesnurikhwan** [comment]
Try check [silvanite/novafieldcheckboxes](https://novapackages.com/packages/silvanite/novafieldcheckboxes) it might suits your use case.

**Comment by taylorotwell** [comment]
This repository is for tracking bugs. Feature requests may be emailed to Nova customer support.
