### ISSUE TITLE
Set required via DependsOn ignores required rule

### ISSUE THREAD

**Issue by StanBarrows** [laravel/nova-issues#4430]
- Laravel Version: 9.*
- Nova Version: 4.8.1
- PHP Version: 8.1

### Description:

We have a dynamic Select field for the ShippingAddress based on the OrderType. 

If I apply $field->required to the dependsOn method it changes the state of the label with adding the required * but you can still update or create the form without having the option selected.

```
    Select::make('Shipping Address, 'shipping_address_id')
                ->onlyOnForms()
                ->rules('nullable', 'exists:addresses,id')
                ->dependsOn(
                    ['order_type_id'],
                    function (Select $field, NovaRequest $request, FormData $formData) {
                    $field->required(checkIfShippingRequired();
                    }
                ),

```

As an alternative we've tried to override the rules via the $field property. But the rules method does not exists.
`$field->rules(['required', 'exists:addresses,id])`

<img width="954" alt="CleanShot 2022-06-15 at 12 15 55@2x" src="https://user-images.githubusercontent.com/10268813/173803941-e0ed49b8-9f4a-4ec4-a830-8a9ede55306f.png">

<img width="966" alt="CleanShot 2022-06-15 at 12 16 07@2x" src="https://user-images.githubusercontent.com/10268813/173803978-dbdd87f6-1cc4-4fbd-9e8d-fe8cf409b305.png">

**Comment by crynobone** [comment]
> If I apply $field->required to the dependsOn method it changes the state of the label with adding the required * but you can still update or create the form without having the option selected.

Read the documentation regarding `required()` and it's limitation.

> As an alternative we've tried to override the rules via the $field property. But the rules method does not exists.

That's is incorrect, it does exist and we have multiple dusk tests verifying it:

https://github.com/laravel/nova-dusk-suite/blob/f53c4d0340959cf5119daaa5192476be373ef783/app/Nova/Fields/BookPurchase.php#L69-L84
