### ISSUE TITLE
User panel dropdown on mobile wrong z-index and position on right

### ISSUE THREAD

**Issue by suchoproduction** [laravel/nova-issues#4434]
- Laravel Version: 9.17.0
- Nova Version: 4.9.0
- PHP Version: 8.1.0
- Operating System and Version: MacOS
- Browser type and version: Google Chrome 102

### Description:

User panel dropdown on mobile wrong z-index and position on right

![Snímka_obrazovky_2022-06-15_o_18_15_32](https://user-images.githubusercontent.com/6931349/173879123-92c66b72-998a-4543-9bd1-0277fd7f4abb.png)

**Comment by davidhemphill** [comment]
Can you post a bigger screenshot? I can't see what you're demonstrating.

**Comment by suchoproduction** [comment]
A larger photo doesn't make sense because the dropdown is still hidden under the overlay

![Snímka_obrazovky_2022-06-15_o_18_15_32](https://user-images.githubusercontent.com/6931349/173904921-6f18cfdd-9485-4a3f-b943-24341a6f2145.png)

**Comment by suchoproduction** [comment]
![Snímka_obrazovky_2022-06-16_o_18_22_40](https://user-images.githubusercontent.com/6931349/174119413-2579baa2-5bdc-4067-96b6-6d6d494b1e9c.png)
