### ISSUE TITLE
T_PAAMAYIM_NEKUDOTAYIM Error in Tools/Dashboard.php

### ISSUE THREAD

**Issue by GLStephen** [laravel/nova-issues#4436]
- Laravel Version: 8.83.16
- Nova Version:  4.9.1
- PHP Version: 7.4

### Description:

After new install  there is a "T_PAAMAYIM_NEKUDOTAYIM unexpected, ; expected" type of error on the line of code that reads in 4.9.0:

```
if (method_exists($dashboard, 'menuItem')) {
    return $dashboard::make()->menuItem();
}
```

this was changed to have a double T_PAAMAYIM_NEKUDOTAYIM to something like this:

```
if (method_exists($dashboard, 'menuItem')) {
    return $dashboard::SOMEOTHERVALUE::make()->menuItem();
}
```

That is throwing errors in my install.

Rolling back to 4.9.0 resolved the issue.

**Comment by crynobone** [comment]
Can you provide a reproducing code causing the issue. Our dusk tests doesn't seem to experience this error.

**Comment by crynobone** [comment]
This affect any installation using PHP 7.3 and 7.4

**Comment by tonnylund** [comment]
Nova 4.x is supported by Laravel Framework 8.0+
Laravel Framework 8.0+ supports PHP 7.3 and 7.4

Nova is a licence product and this breaks our current setup - please fix this.

**Comment by crynobone** [comment]
Bugfix PR has been merged and pending next release.

**Comment by davidhemphill** [comment]
@tonnylund We're doing our best. Please understand and be kind to the human beings working behind the scenes.
