### ISSUE TITLE
Field::MultiSelect - must be of type array, string given!

### ISSUE THREAD

**Issue by RealityGamin** [laravel/nova-issues#4437]
- Nova Version: 4.9.0
- Laravel Version: v9.17.0 
- Php Version: PHP 8.1.6

### Description:

MultiSelect is throwing an error on create, but works properly on edit. When removing the MultieSelect field from the forms it will submit without issues.

```
public function fields(NovaRequest $request)
    {
        return [
            ID::make()->sortable(),
            
            MultiSelect::make('Trained')->options([
                '0' => 'A',
                '1' => 'B',
                '2' => 'C',
            ]),
        ];
    }
```
![image](https://user-images.githubusercontent.com/100086757/173978322-e05a6135-8a6b-4589-9f71-4bbf77cea73a.png)

![image](https://user-images.githubusercontent.com/100086757/173978033-136bf811-e803-4a57-8817-ed271d3ede8d.png)

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/173979805-2ee7037f-74ab-40e4-9bc3-8b47ccd7777d.png)

The documentation clearly states you need to cast it to `array` or equivalent.

**Comment by RealityGamin** [comment]
> ![image](https://user-images.githubusercontent.com/172966/173979805-2ee7037f-74ab-40e4-9bc3-8b47ccd7777d.png)
> 
> The documentation clearly states you need to cast it to `array` or equivalent.

Thank you so much, I really didn't pay attention to the array part.
