### ISSUE TITLE
Index incorrectly using `fieldsForIndex` to check whether to show `Preview` action

### ISSUE THREAD

**Issue by dmason30** [laravel/nova-issues#4441]
- Nova Version: 4.9.0

### Description:
To determine whether to show the `Preview` action it seems to be only checking for fields in `fieldsForIndex` when it should be checking `fieldsForDetail`.

#### Scenario: only `fieldsForDetail` has `showOnPreview`
```php
class ExampleResource extends Resource
{
    public static $model = Example::class;

    public function fieldsForIndex(NovaRequest $request)
    {
        return [Text::make('Index Field', fn () => 'I am fieldsForIndex')];
    }

    public function fieldsForDetail(NovaRequest $request)
    {
        return [Text::make('Detail Field', fn () => 'I am fieldsForDetail')->showOnPreview()];
    }

    public function fields(NovaRequest $request)
    {
        return [];
    }
}
```

**Result**
Actions '...' is not shown as it didn't check `fieldsForDetail` for previewable fields:
<img width="356" alt="image" src="https://user-images.githubusercontent.com/20278756/174090065-2994e656-d54e-4d70-ba38-527114f1c25d.png">

-----

#### Scenario: only `fields` has `showOnPreview`
```php
class ExampleResource extends Resource
{
    public static $model = Example::class;

    public function fieldsForIndex(NovaRequest $request)
    {
        return [Text::make('Index Field', fn () => 'I am fieldsForIndex')];
    }

    public function fieldsForDetail(NovaRequest $request)
    {
        return [];
    }

    public function fields(NovaRequest $request)
    {
        return [Text::make('Detail Field', fn () => 'I am fieldsForDetail')->showOnPreview()];
    }
}
```

**Result**
Actions '...' is not shown as it didn't check `fields` for previewable fields:
<img width="356" alt="image" src="https://user-images.githubusercontent.com/20278756/174090065-2994e656-d54e-4d70-ba38-527114f1c25d.png">

-----

#### Scenario: `fieldsForDetail` and `fieldsForIndex` has `showOnPreview`
```php
class ExampleResource extends Resource
{
    public static $model = Example::class;

    public function fieldsForIndex(NovaRequest $request)
    {
        return [Text::make('Index Field', fn () => 'I am fieldsForIndex')->showOnPreview()];
    }

    public function fieldsForDetail(NovaRequest $request)
    {
        return [Text::make('Detail Field', fn () => 'I am fieldsForDetail')->showOnPreview()];
    }

    public function fields(NovaRequest $request)
    {
        return [];
    }
}
```

**Result**
Actions '...' shown but preview contains only preview fields from `fieldsForDetail`
<img width="352" alt="image" src="https://user-images.githubusercontent.com/20278756/174090575-01299715-1706-4a7f-920a-f00471839277.png">
<img width="358" alt="image" src="https://user-images.githubusercontent.com/20278756/174091223-beed7da1-a718-4c3c-8e5b-e30bbd2d8fce.png">

**Comment by massimodellarovere** [comment]
Same problem. After upgrade 4.0 i not see "Preview" in my resources..
Preview is gone.
![image](https://user-images.githubusercontent.com/5731295/174402752-4bbec48d-7d06-4d9b-a62c-e28ffe7b2c4a.png)

**Comment by massimodellarovere** [comment]
Just an idea. It would not be appropriate to create a dedicated function like the other modes Display, Index etc
![image](https://user-images.githubusercontent.com/5731295/174403211-1223067e-5b3b-4cee-b080-0362581e498e.png)
![image](https://user-images.githubusercontent.com/5731295/174403279-d06c8fa4-5f13-4a8c-8d39-dca5ec78c837.png)
