### ISSUE TITLE
On Mobile View, Sidebar is Not Closing Onclick of sidebar-item

### ISSUE THREAD

**Issue by provydon** [laravel/nova-issues#4442]
- Laravel Version: #.#.#
- Nova Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:
When in Mobile View.. on-click of the sidebar links is supposed to close the sidebar when nova goes to a new page with inertia
but it's not closing.
<img width="1440" alt="Screen Shot 2022-06-16 at 18 11 07" src="https://user-images.githubusercontent.com/31216637/174128661-a8676d7d-4fd5-45f6-b7d5-5a55ab399882.png">

### Detailed steps to reproduce the issue on a fresh Nova installation:
Install nova
open nova in mobile view
click on any sidebar link
Notice the Sidebar doesn't close when it goes to new page

**Comment by crynobone** [comment]
Unable to reproduce, please ensure you have the latest assets by running `php artisan nova:publish`. 

![CleanShot 2022-06-17 at 08 59 32](https://user-images.githubusercontent.com/172966/174201771-d44cd2d3-a5b9-484c-95ad-005cc038dbdf.gif)

**Comment by provydon** [comment]
ran `php artisan nova:publish` and it fixed it.. thanks
