### ISSUE TITLE
Nova returing 404 - help wanted

### ISSUE THREAD

**Issue by m-a-k-o** [laravel/nova-issues#445]
I updated from version 1.0.8 to 1.0.12 and Nova stop working.

Before update everything was working.

I don't have /nova in my routes, only nova-vendor/*, nova-api/* routes.

I did update as it is in docs.

**Comment by m-a-k-o** [comment]
I found problem.

        Event::listen(NovaServiceProviderRegistered::class, function () {

        });

Routes wrapped inside was not working.

**Comment by bonzai** [comment]
Since version 1.0.9 Nova is always registering its routes after your application's routes. So, for example, if you have a route like this:

```php
// example.com/username
Route::get('{user}', 'UserController@show');
```

you will be no longer able to access the dashboard. You can change your `path` option (`config/nova.php`) to `/no/va` and it should start working again.

**Comment by m-a-k-o** [comment]
Ahh okay. I understand know. This should be noted somewhere :) 

Thank you!

**Comment by bonzai** [comment]
You can leave this issue open for now (maybe this is a bug).

**Comment by m-a-k-o** [comment]
Okay, reopened. Let see if it is issue or not.

**Comment by jameslkingsley** [comment]
Is there a particular reason why they're registered after application routes? Seems most logical to me that they be loaded first since you can change Nova's path anyway, and wildcard routes are pretty common in web applications.

**Comment by jameslkingsley** [comment]
As a quick patch, if you still want to use `/nova` or whatever path you've defined **and** keep your wildcard routes, you can use a bit of RegEx like so:

```php
Route::macro('wildcard', function (string $action) {
    Route::get('/{any}', $action)->where('any', '^(?!nova|admin.*$).*');
});
```

**Note: my Nova path is `admin` however the RegEx contains `nova` as well because it is still used for Nova's API routes.**

**Comment by m-a-k-o** [comment]
Thank you for tip. Or you can simply remove event listener :) but yes, it's not persistent fix.

**Comment by davidhemphill** [comment]
They're registered last because in the previous implementation there was a possibility they could be overwritten by other app routes. The current way ensures all app routes are honored first. If you user catch-all routes, you need to specify a regex to allow nova requests to be passed through: 

```php
Route::get('{user}')->where('user', '^(?!nova).*$');
```

**Comment by clarkewing** [comment]
I’m having a similar problem but I don’t have any catch-all routes... Does anyone know what could be causing this?

**Comment by bonzai** [comment]
Just use `config('nova.path')` instead of `route('nova.index')` to generate URL.

**Comment by clarkewing** [comment]
Good idea. I'll do that for now, but I'm curious as to the cause of this problem.

**Comment by pmochine** [comment]
@davidhemphill 

For others who just don't want to match nova/nova-api

`->where('user', '^(?!(nova|nova-api)$).*$');`

Because I have cases where a user could call himself noval but it won't be shown.

**Comment by nickpoulos** [comment]
Just a quick note, I am finding even if I switch the name of my Nova route to /admin/, I have to still include 'nova' as well as 'admin' in the catch-all route, otherwise tools/fields and other things have issues loading. 

```
Route::get('/{slug}', 'BlogController@post')->where(['slug' => '[a-z0-9-]+', 'slug' => '^(?!nova|admin).*$'])->name("blogPost");
```

**Comment by DSpeichert** [comment]
Interestingly, `route('nova.login')` works even when `route('nova.index')` does not.

**Comment by mohkoma** [comment]
Sometimes, the Nova's api routes stop working. ex: when the `/nova` path works but it redirects you to nova 404 page.

`Route::get('/{user}', [UserController::class, 'index'])->where('user', '^(?!nova|nova-api).*$');`
