### ISSUE TITLE
Nova Login Page Continuously saying "CSRF Token Mismatch"

### ISSUE THREAD

**Issue by provydon** [laravel/nova-issues#4451]
- Laravel Version: #.#.#
- Nova Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:
Hi.. my Nova Login page keeps saying CSRF token mismatch.. please how can i solve this?.. wasn't behaving like this before
<img width="466" alt="Screen Shot 2022-06-19 at 22 00 05" src="https://user-images.githubusercontent.com/31216637/174500184-a94eb0f5-f461-49e0-816a-34689a4ed062.png">
<img width="1440" alt="Screen Shot 2022-06-19 at 21 57 55" src="https://user-images.githubusercontent.com/31216637/174500186-3fc366fc-0890-4845-98df-7bf2b3527b22.png">

**Comment by crynobone** [comment]
Unable to reproduce, please provide the reproducing repository (reproduce from a fresh install) with an exact session driver similar to https://github.com/nova-issues for us to debug the issue.

**Comment by provydon** [comment]
it worked when i removed the default value of "true" that i initially set for SESSION_SECURE_COOKIE in config>session.php
<img width="910" alt="Screen Shot 2022-06-20 at 06 01 54" src="https://user-images.githubusercontent.com/31216637/174528748-8a795231-a783-4c96-bb88-2a10230efd98.png">

**Comment by crynobone** [comment]
![CleanShot 2022-06-20 at 13 29 52](https://user-images.githubusercontent.com/172966/174531653-939b7e19-5339-4912-bbfa-1a665d5721e6.gif)

Unable to replicate the issue, see https://github.com/nova-issues/issue-4451/commit/2d4c7ec376cced5a623a1ec485d0d602c1bc535c
