### ISSUE TITLE
Regarding the Filter Applied after update or change the lens

### ISSUE THREAD

**Issue by parth-ka-patel** [laravel/nova-issues#4459]
### Discussed in https://github.com/laravel/nova-issues/discussions/4458

<div type='discussions-op-text'>

<sup>Originally posted by **parth-ka-patel** June 21, 2022</sup>
Hello,

Here i have two difficulties for applying filter after successful update and change lens 

Problem Explanation : 

1. when i apply any filter and i opened any resource from that update result and apply the changes in product and when i try to update product  so i have to redirect on product listing page with last applied filter value and result as it is so i don't have to apply same filter again 
2. same issue i face when apply filter and when i try to apply lens so in lens result are auto update with same filter in lens so i don't have to apply filter after changing the result in lens resource listing

so here i have this two problem if any one have solution please try to reach out here so it'll be helpful to me.

Thanks.</div>

**Comment by crynobone** [comment]
This feature doesn't exist in Nova at the moment.
