### ISSUE TITLE
REQUEST: Manually set the OrderBy attribute/s on a Field ->orderBy('name') 

### ISSUE THREAD

**Issue by glennwilton** [laravel/nova-issues#446]
For Computed Field or Relationships sorting does not work, it would be nice to manually specify the orderBy attribute, Also for some Fields, you want to sort by a different column such as an ID numerically and not by the Relationship Text Alphabetically. 

Also setting orderBy automatically makes the Column ->sortable() 

BelongsTo::Make('relationship')->orderBy('child_id')   .... or ->orderOn(attribute) if that makes more sense

Would also be nice to specify multiple fields to order by ->orderBy(county','city')

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
Already possible: https://nova.laravel.com/docs/3.0/resources/relationships.html#disable-ordering-by-title
