### ISSUE TITLE
BelongsTo is not loading relationship

### ISSUE THREAD

**Issue by stonkeep** [laravel/nova-issues#4463]
- Laravel Version: 4.9.2
- Nova Version: 9

Good Morning
I have the following relationship between two models: Proposta hasOne Pagamento. Pagamento belongsTo Proposta
At the url 
`http://localhost/nova/resources/pagamentos/new?viaResource=propostas&viaResourceId=35&viaRelationship=pagamento&relationshipType=hasOne`

It's not showing the filled field
![image](https://user-images.githubusercontent.com/3990028/174833221-7498e0b8-1429-4cb1-8cce-e21182adcd47.png)

my code
App\Nova\Proposta
`HasOne::make('Pagamento'),`

App\Models\Proposta
```php
public function pagamento(): HasOne
    {
        return $this->hasOne(Pagamento::class);
    }
```

App\Nova\Pagamento
`BelongsTo::make('Proposta', 'proposta', Proposta::class)->readonly(),`

App\Models\Pagamento
```php
    public function proposta(): BelongsTo
    {
        return $this->belongsTo(Proposta::class);
    }
```

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)
