### ISSUE TITLE
Localization - Using Short Keys - Resource label incorrectly translated to json

### ISSUE THREAD

**Issue by dmason30** [laravel/nova-issues#4467]
- Nova Version: 4.10.0
### Description:
Using the example provided here: https://laravel.com/docs/9.x/localization#using-short-keys

Assume you had this language file:
```php
<?php
 
// lang/en/messages.php
 
return [
    'welcome' => 'Welcome to our application!',
];
```

But also you had a `Message` model and a Nova resource for it with the label specified like this:
```php
// app/Nova/MessageResource.php

class MessageResource extends Resource {
    public static function label()
    {
        return 'Messages';
    }
}
```

We end up with this is the nova menu in 4.10.0:

<img width="266" alt="image" src="https://user-images.githubusercontent.com/20278756/174904671-afc7f8ba-5e9c-41d9-8e73-a3c90195bbb2.png">

**Solution**
I assume you are now translating every label via `__(...)`intentionally now for a good reason. 

As a solution, possibly provide a way for us to disable label translation either globally or per resource?

**Comment by ianrobertsFF** [comment]
It might be a laravel limitation but having a transition file the same name as your resource with no JSON is fairly standard and wasn't an issue before the change to run all labels via the translation method.

"Broken as intended" might be your prerogative on this one, but you'll probably see a number of these issues ongoing.

**Comment by crynobone** [comment]
> It might be a laravel limitation but having a translation file the same name as your resource with no JSON is fairly standard and wasn't an issue before the change to run all labels via the translation method.

To solve this it can only be done in [laravel/framework](https://github.com/laravel/framework), and it is possible that `trans()` and `__()` support need to contain breaking change, or have a separate helper for JSON and php string translation file. You could propose a PR to laravel/framework
