### ISSUE TITLE
Resource with sorting by non-unique field show repeating rows for different pages

### ISSUE THREAD

**Issue by 4n70w4** [laravel/nova-issues#4481]
- Laravel Version: 9.17.0
- Nova Version: 4.9.2
- PHP Version: 8.1.7
- Database Driver & Version: postgres:14.3

### Description:

Laravel/Nova generates queries with `limit` and `order by` to database that return rows with repeated rows on different limit/offset values.

To solve the problem need to add an additional `order by` field for pagination queries, for example, `id`.

https://stackoverflow.com/questions/13580826/postgresql-repeating-rows-from-limit-offset

I could not find in the Nova documentation how to add an additional sort field for pagination.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Add field to resource:

```php
            Number::make(__('Clicks Count'), 'clicks_count')->sortable()->exceptOnForms(),
```

Open in browser and click by field header for sorting

![image](https://user-images.githubusercontent.com/38257723/175775490-3a7eb00b-e158-4ae9-82ac-96105423ab87.png)

See the same rows multiple times on different pagination pages.

First page

![image](https://user-images.githubusercontent.com/38257723/175776692-4af1166d-f17b-4f1f-8350-3b82693fddca.png)

Second page

![image](https://user-images.githubusercontent.com/38257723/175776698-ec8f6852-ed1b-40ac-9081-1b8e38694de4.png)

11 repeats.

Query from telescope for first page:

```sql
select
  "users".*,
  (
    select
      count(distinct(channel_id))
    from
      "channels"
      inner join "channel_message_clicks" on "channel_message_clicks"."channel_id" = "channels"."id"
    where
      "users"."id" = "channel_message_clicks"."user_id"
  ) as "channels_count"
from
  "users"
order by
  "channels_count" desc
limit
  26 offset 0;
```

Query from telescope for second page:

```sql
select
  "users".*,
  (
    select
      count(distinct(channel_id))
    from
      "channels"
      inner join "channel_message_clicks" on "channel_message_clicks"."channel_id" = "channels"."id"
    where
      "users"."id" = "channel_message_clicks"."user_id"
  ) as "channels_count"
from
  "users"
order by
  "channels_count" desc
limit
  26 offset 25;
```

**Comment by crynobone** [comment]
Please provide complete example reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example) 

While I understand how this could be an issue I would still need to be able to know whether it should be handled by Nova or it should be handled by the developer (it seems to be you are using an additional query via `indexQuery`) but isn't stated here (hence why reproducing repository is needed).
