### ISSUE TITLE
ActionResource boolean

### ISSUE THREAD

**Issue by aqjw** [laravel/nova-issues#4484]
- Laravel Version: 9.11
- Nova Version: 4.10.0
- PHP Version: 8.1.3

### Description:

Action Resource does not look at the type of the field and marks the value as modified. Although in fact, it has not changed.

<img width="700" alt="Screenshot 2022-06-27 at 01 11 03" src="https://user-images.githubusercontent.com/13101908/175835677-57d0fd17-405d-42a3-8b80-b7a805433a4b.png">

Resource field:

```
Boolean::make('Active');

```

Migration column:

```
$table->boolean('active');
```

**Comment by crynobone** [comment]
Unable to replicate the issue but am going to submit a PR to ensure `original` show casted value instead of raw value.
