### ISSUE TITLE
[Request] Field->disableWhenUpdating()

### ISSUE THREAD

**Issue by PKuebler** [laravel/nova-issues#449]
Hey,

current i found `Field->hideWhenCreating()` and `Field->hideWhenUpdating()`.

Is it possible `Field->disableWhenUpdating()` render the field like the detail page?

greets
Philipp

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/160318039-e10a6729-fc1a-403c-a928-705c88d8e830.png)

Removing `request` tag for now.
