### ISSUE TITLE
Styles of layouts are broken after updating version from 4.9.* to 4*10.*

### ISSUE THREAD

**Issue by diosby** [laravel/nova-issues#4490]
- Laravel Version: 9.18.0
- Nova Version: 4.10.1
- PHP Version: 8.1.7
- Operating System and Version: Ubuntu 20.04 (bu the same bug on the server)
- Browser type and version: Firefox 101 (other latest browsers as well)

### Description:

Nova CSS styles are broken. 

**4.9.2**
![Screenshot from 2022-06-28 14-16-43](https://user-images.githubusercontent.com/19969187/176167394-dbabfe9e-b8b9-492e-9924-2303b8627ad3.png)

**4.10.1**
![Screenshot from 2022-06-28 14-18-28](https://user-images.githubusercontent.com/19969187/176167398-87df9e3b-bace-47e3-aa0c-d2ffc6c3f45b.png)

The content is too wide, the side menu is under the content. This problem is for each page. 

### Detailed steps to reproduce the issue on a fresh Nova installation:

Our version has been updated and some Nova styles were broken. 

The previous version is 4.9.2, the new version is 4.10.1 (the same for 4.10.0).

**Comment by diosby** [comment]
@crynobone Sure, this command is run automatically after every updating. 

```
Publishing complete.
Copied Directory [/vendor/laravel/nova/public] To [/public/vendor/nova]
Publishing complete.
Copied Directory [/vendor/laravel/nova/resources/lang] To [/lang/vendor/nova]
Publishing complete.
Compiled views cleared successfully.
```

But unfortunately, it doesn't solve the problem.

**Comment by davidhemphill** [comment]
If you customize the app layout you should use the `--force` option when updating Nova to ensure you receive any updates to the layout. You can backport your customizations then.
