### ISSUE TITLE
Modify BelongsTo field options from other BelongsTo

### ISSUE THREAD

**Issue by Krato** [laravel/nova-issues#45]
Hello! I'm trying to do a multilanguage crud. So I create a `Post` resource and `PostTranslation` resource.

Post resource has:

```php
HasMany::make('postTranslations')
```

PostTranslation resource has:

```php
BelongsTo::make('Post')->sortable(),
BelongsTo::make('Locale')->sortable(),
```

Everything is working fine. But, how can I limit the locales select. For example:

I create a Post with ID 1. Then I create a Post with English Locale. So the next time I want to create a translation for Post ID 1, English should be disabled, because there is a translation made it.

How can achieve that with Nova?

Thanks

**Comment by devmsh** [comment]
I think you can achieve this using Validation Rules, I don't know if there is any possibility to customized the select element result query of BelongsTo relationship.

Why not to use the nova-translatable fields instead?

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).
