### ISSUE TITLE
BelongstoMany on forms

### ISSUE THREAD

**Issue by elrufoelrufo** [laravel/nova-issues#450]
Hello,

I believe that BelongstoMany should be able to show on create and update forms. 

On update form like is  working now on details form 

On create form like a repeatable field to create it at the same time that you create a new object. 

Do you have this consideration for the next releases? 

NOTE : The same for HasMany. 

For example, if you have a brand  with differents locations would be great to create the brand and his locations at the same time. 

Thanks. Regards.

**Comment by taylorotwell** [comment]
This repository is for tracking bugs. Feature requests may be emailed to Nova customer support.

**Comment by elrufoelrufo** [comment]
Please Taylor. Could you let me know the email of Nova Customer Support? Thanks for your help.

**Comment by elrufoelrufo** [comment]
> This repository is for tracking bugs. Feature requests may be emailed to Nova customer support.
Hello Taylor, please, could you let me know the email of Nova Customer Support? Thanks!!

**Comment by elrufoelrufo** [comment]
> This repository is for tracking bugs. Feature requests may be emailed to Nova customer support.

Hello Taylor, please, could you let me know the email of Nova Customer Support? Thanks!!

**Comment by vootrunner** [comment]
visit nova.laravel.com and look for the "life preserver" (aka floatation safety device) in the lower right hand corner. I _assume_ that sends email to support.
