### ISSUE TITLE
MorphTo field resolve morph type in an inappropriate way

### ISSUE THREAD

**Issue by mohammedazman** [laravel/nova-issues#4504]
Laravel Version: 9.19.0
Nova Version: 4.11.0
Description: MorphTo field when try to resolve morph type by attribute through  resolveMorphType  function, Whereas the Laravel morphTo  relation  resolve it by the original column value so
When add Mutators or Casts to Attribute that used for  polymorphism relation type E.g.
Cast commentable_type attribute

  // cast model type to get model name without namespace
    public function get($model, string $key, $value, array $attributes)
    {
        $path = explode('\\', $value);
        return array_pop($path);
    }
    
Mostly this will result in an exception so here is a suggestion to use the actual value of the column
 
current code:

    protected function resolveMorphType($resource)
    {
        if (! $type = optional($resource->{$this->attribute}())->getMorphType()) {
            return null;
        }

        $value = $resource->{$type};

        if ($morphResource = Nova::resourceForModel(Relation::getMorphedModel($value) ?? $value)) {
            return $morphResource::uriKey();
        }
    }

Suggested code:

    protected function resolveMorphType($resource)
    {
        if (! $type = optional($resource->{$this->attribute}())->getMorphType()) {
            return null;
        }

        $value = $resource->getRawOriginal($type);

        if ($morphResource = Nova::resourceForModel(Relation::getMorphedModel($value) ?? $value)) {
            return $morphResource::uriKey();
        }
    }

**Comment by crynobone** [comment]
Submit a full reproducing repository based on the use case so we can see how this affect Nova applications and look into adding it into our tests suite.
