### ISSUE TITLE
MenuGroup collapse icon

### ISSUE THREAD

**Issue by aqjw** [laravel/nova-issues#4511]
- Laravel Version: 9.11
- Nova Version: 4.11.0
- PHP Version: 8.1.3

### Description:

In the MenuGroup with collapse, the icon is not clickable.

<img width="698" alt="Screenshot 2022-06-30 at 19 58 40" src="https://user-images.githubusercontent.com/13101908/176735142-4871de45-fe92-4918-8f56-cdaf27e4ba0e.png">

**Comment by crynobone** [comment]
![CleanShot 2022-07-01 at 08 36 02](https://user-images.githubusercontent.com/172966/176800202-e72f7342-e5c5-4f85-964d-1db1435bd244.gif)

Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by aqjw** [comment]
I mean the icon (svg). Did you click on it?

<img width="1322" alt="Screenshot 2022-07-01 at 09 25 45" src="https://user-images.githubusercontent.com/13101908/176836833-f275a3ea-6212-4d3f-a103-10476ba5a1e4.png">

**Comment by crynobone** [comment]
> Did you click on it?

See ![CleanShot 2022-07-01 at 08 36 02](https://user-images.githubusercontent.com/172966/176800202-e72f7342-e5c5-4f85-964d-1db1435bd244.gif)

**Comment by aqjw** [comment]
On the gif, you click in on an item, not the icon
