### ISSUE TITLE
Clicking on a resource and going back results in a 404 error / non rendered navigation

### ISSUE THREAD

**Issue by stefblokdijk** [laravel/nova-issues#4522]
- Laravel Version: 9.19.0
- Nova Version: 4.11.1
- PHP Version: 8.1.7
- Database Driver & Version: MYSQL 8
- Operating System and Version: Ubuntu 20.04
- Browser type and version: Chrome 103.0.5060.53 / Safari 15.5
- Reproduction Repository: N/A

### Description:
When you click on a resource and press the back button, it will result in a 404 error on Safari and on Chrome it hides the navigation.

You'll notice that this only happens when you open a resource by clicking on the table row, not when you click on the eye icon. When you click on the eye icon it will route like a normal Inertia app, while clicking on the table row it will load the resource like you've clicked on a `<a href="">`.

### Detailed steps to reproduce the issue on a fresh Nova installation:
1.) Load a resource overview
2.) Click on a single resource via the text
3.) Click your browsers back button
4.) On Safari you'll see a 404 error. On Chrome look at the console log, you will see these errors that normally don't show: https://cln.sh/M5x9YdgT0rs15N8FlgFq (note: we don't use any impersonation features / code)

**Comment by crynobone** [comment]
Unable to replicate, are you using any 3rd party package which may override `ResourceTableRow` component?

### Safari

https://user-images.githubusercontent.com/172966/177064376-206fff6f-f904-427e-97b8-5dfd77fee820.mp4

### Chrome 

https://user-images.githubusercontent.com/172966/177064390-a67a835a-0ebd-421c-985f-1ed9791486b4.mp4

**Comment by stefblokdijk** [comment]
Thanks for pointing out the `ResourceTableRow` override possibility. Turns out this is related to https://github.com/outl1ne/nova-sortable/issues/128
