### ISSUE TITLE
The date field subtracts one day from the stored one on editing

### ISSUE THREAD

**Issue by ricardov03** [laravel/nova-issues#4524]
- Laravel Version: 9.17.0
- Nova Version: 4.9.2
- PHP Version: 8.1.5
- Database Driver & Version: MySQL 8.0.28
- Operating System and Version: macOS 12.2 arm64
- Browser type and version: Firefox Developer 103.0b3
- Reproduction Repository: https://github.com/ricardov03/bulletbudget (Request for permission)

### Description:
Create a Resource with a Date field. After storing the resource, if you tried to edit the saved resource, the Date field shows a wrong date, specifically a day less from the stored one.

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Create a Random Model (Include a Date field).
2. Create the Resource and choose a Date field (Not Datetime), enabling edit.
3. Store a record and try to edit it. The presented date should show one day less than the stored one.

**Comment by crynobone** [comment]
There's not enough information such as:

- app timezone configuration 
- user timezone configuration
- does DST involved based on the selected date 
- etc. 

Also, we already have the tests covered via https://github.com/laravel/nova-dusk-suite/blob/master/tests/Browser/DateFieldTest.php without the bug reported above.

--------

p/s: You can grant access to me but I would think above requirements is critical info to really debug the issue.

**Comment by ricardov03** [comment]
I am working on this later today. Thanks, @crynobone, for taking the time to check this.

**Comment by crynobone** [comment]
Added `America/Santo_Domingo` to the test suite and unable to reproduce the issue:

https://github.com/laravel/nova-dusk-suite/blob/master/tests/Browser/DateFieldTest.php

**Comment by ricardov03** [comment]
Let me try to replicate the issue in a clean Laravel + Nova installation. Thanks so much for the effort.

**Comment by dacastro4** [comment]
@ricardov03 this is happening to me too. Did you find a way to fix this?

**Comment by ricardov03** [comment]
Hello @dacastro4. I'm still facing this issue, but I haven't the time to replicate the problem for @crynobone .
I'm not migrating, my project started from a clean Laravel installation with a clean Nova 4.

**Comment by dacastro4** [comment]
Thank you @ricardov03. I thought it was going to be some issues during upgrade migration but apparently it is just an issue with the conversion (?) logic of the Date field. We had our app since Nova 3 and we never had that issue before migrating.

@crynobone What I'm testing right now is a date column (not a timestamp, it has to have `00:00:00` as the time) and the app.timezone is `UTC` as well

**Comment by baszach** [comment]
I have the same issue. The `date of birth` attribute is `1968-11-21` but displays `1968-11-20` in Nova frontend.
![image](https://user-images.githubusercontent.com/47082864/180440435-f6bd9074-8b8a-4fdb-9fcf-a80a455e661a.png)
Timezone is configured as `Europe/Berlin`.

**Comment by baszach** [comment]
How is the `Date` field `value` attribute in the Vue component derived? I used `displayUsing` as stated above (formatting `Y-m-d`) and the Vue data looks like that:
![image](https://user-images.githubusercontent.com/47082864/180445518-142814d1-a56f-4a2b-aa02-6aba4c992881.png)
Then without the `displayUsing` Vue data looks as follow:
![image](https://user-images.githubusercontent.com/47082864/180445702-b321bfc4-b742-48f0-92d7-b2104f87cfa1.png)

**Comment by dacastro4** [comment]
Just so you know, I made a custom Date field as a patch for now. The issue is definitely the frontend so i'm still trying to figure out what it is

**Comment by crynobone** [comment]
Closing this as stale at the moment, feel free to create a new issue with a full reproducing repository for us to debug the issue.
