### ISSUE TITLE
Wrong shadow color on focused validated fields

### ISSUE THREAD

**Issue by markwalet** [laravel/nova-issues#453]
Let me first say this: This could be opinion-based. You can close the issue if you want.

When the user focuses on a field with validation errors, the 'focus-shadow' around it should be also red. Now it just stays the same blue color.

How it is now:

<img width="455" alt="screen shot 2018-09-05 at 14 45 29" src="https://user-images.githubusercontent.com/11446771/45094221-f3a8eb80-b11a-11e8-9c34-27cb411ba360.png">

How **I think** it should be:
<img width="271" alt="screen shot 2018-09-05 at 14 45 17" src="https://user-images.githubusercontent.com/11446771/45094220-f3105500-b11a-11e8-9811-bb971be425a5.png">

**Comment by taylorotwell** [comment]
This repository is for tracking bugs. Feature requests may be emailed to Nova customer support.
