### ISSUE TITLE
Error compiling freshly created field in nova 4

### ISSUE THREAD

**Issue by nouce** [laravel/nova-issues#4531]
- Laravel Version: 9.19.0
- Nova Version: 4.11.1
- PHP Version: 8.1
- Yarn Version: 1.22.17

### Description:

When i create a new field with `php artisan nova:field {vendor}/{name}` (eg. fyr/test-field) the build immediately fails to compile. Without me changing anything.

I get the following error: 

<img width="953" alt="Schermafbeelding 2022-07-06 om 11 18 22" src="https://user-images.githubusercontent.com/45368779/177516443-bf92b4a2-eb80-4213-b1fc-100e52910669.png">

this is line 70 in the vue-loader/dist/index.js
`const hasScoped = descriptor.styles.some((s) => s.scoped);`

When i change the vue-loader to version 15.9.4 it compiles without any errors, but then is doesn't show on the resource where i add the field and get the following error in the console:

<img width="525" alt="Schermafbeelding 2022-07-06 om 11 32 05" src="https://user-images.githubusercontent.com/45368779/177519459-5446161b-1bba-4c0c-99cc-02416bbfd3a9.png">

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. `php artisan nova:field {vendor}/{package-name}`
2. `composer update` in project root
3. `cd` into nova-component directory
4. `yarn`
5. `yarn run nova:install`
6. `yarn run dev`
7. The error as described above appears

I hope i described the error goed enough! Am I doing something wrong?

Thanks in advance.

**Comment by crynobone** [comment]
Which version of Node?

**Comment by crynobone** [comment]
Just tested the reproducing steps and was unable to replicate it with `npm` and I'm not sure if there anything we can do here as this could be an integration issue between `yarn` and `vue-loader`.

**Comment by nouce** [comment]
Thanks for the reply! What NPM version are you running? Just tested with NPM and got the same error.

Thanks!

**Comment by crynobone** [comment]
Tested with the following:

```bash
➜ node -v
v14.19.2
➜ npm -v
6.14.17
```

and also

```bash
➜ node -v
v16.15.0
➜ npm -v
8.5.5
```

**Comment by baszach** [comment]
I had the same issue with Yarn. It was a pain and for me it was more convenient to shift back to NPM.

`npm -v`
8.11.0
`node -v`
v16.15.1

This works for me.

**Comment by baszach** [comment]
Not sure if it interferes with something but have you deleted `yarn.lock`, `node_modules` and `package-lock.json` to start with a clean slate?

Also: What does your `package.json` in the custom component look like?

**Comment by nouce** [comment]
So i've re-installed nova and tried to make a field than compile it. At first i did get the same errors. I found out that if i remove the node_modules folder from the root project (so not the node_modelus from the nova field directory) the field compiles without any errors. As soon as I run `npm install` in my root directory (so regenerating the node_modules) the nova field gives the same errors when i compile it.

Any idea how that's possible?

**Comment by crynobone** [comment]
> Any idea how that's possible?

Still not possible to replicate this
