### ISSUE TITLE
Method Date::format does not exist

### ISSUE THREAD

**Issue by nb823** [laravel/nova-issues#4532]
- Laravel Version: 9.5.1
- Nova Version: 4.8
- PHP Version: 8.1.7
- Operating System and Version: Ubuntu 20.04.4 LTS
- Browser type and version:  Firefox 102.0

### Description:

The Laravel Nova `Date` field does not support the `format()` method as is described in the [documentation](https://nova.laravel.com/docs/3.0/resources/fields.html#date-formats).
When trying it anyway, it throws the error: `Method Laravel\Nova\Fields\Date::format does not exist.
`
### Detailed steps to reproduce the issue on a fresh Nova installation:

In any Nova Resource:

```
use Laravel\Nova\Fields\Date;

public function fields(NovaRequest $request)
{
   ...
   Date::make('Birthday')->format('DD MMM'),
   ...
}
```

**Comment by crynobone** [comment]
You are refering Nova 3 documentation. Please read https://nova.laravel.com/docs/4.0/upgrade.html#date-datetime-fields-html5
