### ISSUE TITLE
URL field displays a strange value

### ISSUE THREAD

**Issue by Lednerb** [laravel/nova-issues#4539]
- Laravel Version: 9.19.0
- Nova Version: 4.11.1
- PHP Version: 8.1.3

### Description:
I've discovered a strange behaviour by using the `URL` field with a customized `displayUsing` method:

```php
URL::make(__('Website'), 'website')
   ->displayUsing(fn ($url) => parse_url($url, PHP_URL_HOST))
   ->rules(['required', Rule::unique('clients')->ignore($this->id)]),
```

This field works fine on the most entries I had so far, but using the following one provides the strange output:
`https://www.in-example.de/`

![image](https://user-images.githubusercontent.com/2056876/177596355-97d2091a-39d7-4a67-85c8-4bd54965e409.png)

The output from `parse_url` works fine:
![image](https://user-images.githubusercontent.com/2056876/177596806-a0931cb3-d3a0-44e9-9e33-4d165a56305c.png)

The same issue occurs with other subdomains.

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Create a model with an `URL` field
2. Enter the URL `https://www.in-example.com` and check the output

**Comment by crynobone** [comment]
![CleanShot 2022-07-07 at 08 25 26](https://user-images.githubusercontent.com/172966/177664065-3fa85f29-bc54-403d-af7b-2b2d566a6903.gif)

I tried reproducing the issue but everything work as expected. See https://github.com/nova-issues/issue-4539/commit/d2896d13cef1ee5784a9a7e897fe3d088ece9a25

**Comment by Lednerb** [comment]
Hey @crynobone 

thanks for your quick check and answer.
I will try to investigate the reason for the issue and will post an update here soon.
