### ISSUE TITLE
morphto and morphmany issue - "Call to undefined method {model}::singularLabel"

### ISSUE THREAD

**Issue by elizdlt202** [laravel/nova-issues#4540]
- Laravel Version: 8.75
- Nova Version: 4.11.1
- PHP Version: 8.1

### Description:
I'm using a morph to relationship and then a morphmany and I'm getting this error

```
   "message": "Call to undefined method App\\Models\\ProductionWorkflowQueue::singularLabel()",
    "exception": "BadMethodCallException",
    "file": "/Users/elizabethdelatorre/Sites/eliztest-app/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php",
    "line": 84,

```

### Detailed steps to reproduce the issue on a fresh Nova installation:

**ProductionActivity Model**
```
    public function relatable_activity()
    {
        return $this->morphTo();
    }
```

**ProductionActivity Resource**
```
            MorphTo::make('Related To', 'relatable_activity', 'App\Nova\ProductionActivity')
                ->types([
                    ProductionWorkflowQueue::class,
                    ProductionOrder::class,
                ])->nullable(),
```

account_activities db table fields:
```
"relatable_activity_id"
"relatable_activity_type"
```

**ProductionOrder Model**
```
    public function activities()
    {
        return $this->morphMany(ProductionActivity::class, 'relatable_activity');
    }
```

**ProductionOrder Resource**
`  MorphMany::make('History,  'activities', 'App\Nova\ProductionActivity'),`

**ProductionWorkflowQueue Model**
```
    public function activities()
    {
        return $this->morphMany(ProductionActivity::class, 'relatable_activity');
    }

```
**ProductionWorkflowQueue Resource**
` MorphMany::make('History,  'activities', 'App\Nova\ProductionActivity'),`

### **Also see attachment - the error in the console.** 
It says hasmany on the ProductionWorkflowQueue Resource detail.
should it not say morphMany
```
<?php

namespace Laravel\Nova\Fields;

class MorphMany extends HasMany
{
    /**
     * Get the relationship type.
     *
     * @return string
     */
    public function relationshipType()
    {
        return 'morphMany';
    }
}

```

![Screen Shot 2022-07-06 at 10 09 06 AM](https://user-images.githubusercontent.com/49735067/177605915-75f140bf-a9ad-4667-9733-ef0d26a56d73.png)

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by elizdlt202** [comment]
hi @crynobone here is a fresh repo https://github.com/elizdlt202/issue-4540

**Comment by elizdlt202** [comment]
@crynobone 
Oh oops, we are all good. No issue here - I just now caught my mistake. 
Thank you for your time!!
