### ISSUE TITLE
Hide edit-icon for relations (workaround)

### ISSUE THREAD

**Issue by krns** [laravel/nova-issues#455]
We have `users` and `roles`. Roles are specified via a `MorphToMany` relation. The intermediate table has no additional columns, so the edit-icon of the relation doesn't make much sense in this scenario.

To hide the edit-icon we have implemented the `attachRole` in the user policy and return `false`. If you do so the edit-icon is hidden, but also the drop down when assign a new role is empty.

Our workaround is to check the current route in the `attachRole`-policy.

```
$currentUrl = url()->current();
$indexUrl = action('\Laravel\Nova\Http\Controllers\ResourceIndexController@handle', [
      'resource' => 'roles',
], true);
```

Does anybody have the same struggle?

**Comment by loren138** [comment]
If you can get the request and dump it `dd($request)`, in some cases it is a different class depending on where it came from so you can check with `instanceof`.  (Still rather hacky though.)

**Comment by davidhemphill** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).
