### ISSUE TITLE
Stacked fields are not stacked

### ISSUE THREAD

**Issue by Neodark7** [laravel/nova-issues#4551]
- Laravel Version: 9.17.0
- Nova Version: 4.11.1
- PHP Version: 8.1
- Database Driver & Version: MySQL 8.0
- Operating System and Version: Ubuntu 22.04
- Browser type and version: Chrome 103.0.5060.114
- Reproduction Repository: Should be easy to reproduce

### Description:

Hi ! Is this a bug or am i missing something here ? The code field is not supposed to be displayed under the label when using the ->stacked() method ?

### Detailed steps to reproduce the issue on a fresh Nova installation:

![image](https://user-images.githubusercontent.com/7981869/178123179-718a99b8-c6fe-4bd4-b1ce-ac5d47ae204a.png)

<img width="593" alt="Sans titre" src="https://user-images.githubusercontent.com/7981869/178123318-1e394b50-0981-41ec-9d84-4dd30a2f2b31.png">

**Comment by crynobone** [comment]
Documentation updated to reflect the usage only on create and update form.

![image](https://user-images.githubusercontent.com/172966/181395884-388d3adc-8219-4f5e-9994-4389aa2adb67.png)
