### ISSUE TITLE
Global search results when using meilisearch

### ISSUE THREAD

**Issue by timersys** [laravel/nova-issues#4552]
- Laravel Version: 9.17.0
- Nova Version: 4.9.1
- PHP Version: 8.0.2
- Scout: 9.4.9
### Description:
I'm using scout + Meilisearch on my project. When I search a resource using the resource table search it works fine, or when I use use meilisearch mini-dashboard it also results are fine. 

When I use global search the results are inaccurate. I'm attaching a screenshot where you can see the search results in the table while the ones got in the global search.

So somehow the global search it's using something different than the table search. What I found is that If I change global search `public static $globalSearchResults = 25;` and set it to 25 the results are fine, but of course that widget cannot show 25 results as the dropdown it's higher than the viewport.

<img width="577" alt="Screen Shot 2022-07-10 at 12 21 19" src="https://user-images.githubusercontent.com/1206915/178159636-0c183219-7820-4ca7-8a3b-68610cbef5e8.png">

**Comment by crynobone** [comment]
This is a very vague description of an issue. 

Please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)
