### ISSUE TITLE
Not possible to use Nova 4 in Laravel projects because of Mix / ViteJs?

### ISSUE THREAD

**Issue by libero-developer** [laravel/nova-issues#4555]
- Laravel Version: 9
- Nova Version: 4
- PHP Version: 8.2

### Description:

I get the following error when trying to access Nova: `Unable to locate Mix file: /app.scss. `
This is in a new Laravel project with ViteJs.

Is there a way to get this working? Or is it not possible anymore to use Nova with Laravel projects because of ViteJs ... (??)

**Comment by crynobone** [comment]
Please provide full reproducing steps and how to exactly reproduce the issue.

**Comment by Libero-Software** [comment]
I am sorry. I upgraded yarn and node, and then Nova failed. After downgrading everything, it still was broken. Then i did a view:clear, and it worked again. Don`t know what happend, but i posted this issue to soon.
