### ISSUE TITLE
ID coming 0 when creating new nova resource and setting id manually on model observer

### ISSUE THREAD

**Issue by prakhargvp** [laravel/nova-issues#4557]
- Laravel Version: 8.83.13
- Nova Version: 4.7.0
- PHP Version: 7.3.28

### Description:

After creating a nova resource, It is returing id as 0 and getting not found page. **I'm setting resource id on model observer creating method and i'm able to create resource successfully in database.** only issue is on redirection into created resource in laravle nova dashboard.

![image](https://user-images.githubusercontent.com/7056772/178406757-f3a388c3-42b3-4556-88fb-d0c56d438790.png)

![image](https://user-images.githubusercontent.com/7056772/178407026-5d4f043c-b42e-419d-80e8-e3e5cf6d4508.png)

**Comment by crynobone** [comment]
Please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by Elshaden** [comment]
I had similar issue, I think you need to use  something like   $user->push();  after you create in the Observer. as it is not committed yet to the database till the whole process is completed successfully.

I don't know if this is a bug or how Laravel Observers work.

**Comment by crynobone** [comment]
Closing this as stale at the moment, feel free to create a new issue with a full reproducing repository.
