### ISSUE TITLE
Badge Field Problem after Update to Version 4.12.2

### ISSUE THREAD

**Issue by massimodellarovere** [laravel/nova-issues#4563]
Laravel Version: 9.19.0
Nova Version: 4.12.2
PHP Version: 8.1.7
Database Driver & Version: MYSQL 5.7
Operating System and Version: Ubuntu 22.04 LTS
Browser type and version: Brave Versión 1.37.116 Chromium: 100.0.4896.127 (64 bits)

### Description:

Badge Field Problem after Update to Version 4.12.2

![image](https://user-images.githubusercontent.com/5731295/178602915-1da0f818-4931-438c-ad80-2f622d59dd1c.png)

With previous versions this is the results

![image](https://user-images.githubusercontent.com/5731295/178603209-3cab1793-24f9-44b9-b400-0dd269c8cdde.png)

This is code Badge Field for My Resource Orders

![image](https://user-images.githubusercontent.com/5731295/178603408-ff95d0e9-fe35-4f8b-bb96-6ef1359fc8fa.png)

**Comment by crynobone** [comment]
Please provide code example for this.

![image](https://user-images.githubusercontent.com/172966/178626938-c80f3601-ddc8-4be9-932b-e2217c379449.png)

**Comment by crynobone** [comment]
As for Label, you actually should use the following instead:

```php
Badge::make(__('labels.type'), 'payments.type')->maps([
    // ...
])labels([
    'BANK' => 'BAN',
    'CARD' => 'CAR',
    // ...
]);
```

**Comment by massimodellarovere** [comment]
Example code requested

![image](https://user-images.githubusercontent.com/5731295/178639086-d8c947a6-4264-44a5-9125-07803c08005a.png)

**Comment by massimodellarovere** [comment]
Example code requested

![image](https://user-images.githubusercontent.com/5731295/178639203-e76d723d-3ea4-402c-8dc4-3c3259dcaf79.png)

**Comment by crynobone** [comment]
`eColumn` isn't part of Laravel Nova default Fields, you need to update the fields to match the new code.

```js
  computed: {
    fieldValue() {
      return String(this.field.displayedAs || this.field.value)
    },
  },
}
```

**Comment by massimodellarovere** [comment]
eCloumn is not Custom Nova Field is Class that return un simple String in HTML

**Comment by prookie** [comment]
Hey guys,

I am pretty certain that Nova 4.12.0 introduced a bug which makes `displayUsing()` useless as it does not seem to be executed in any case anymore. This affects every field type as far as I can see. Minimum broken example:

```php
Text::make('Example', 'column')->displayUsing(function($value) {
    return strtoupper($value);
});
```
It just outputs the raw column value as text.

I use `displayUsing()` extensively throughout my project and after updating from 4.11.1 to anything higher or equal to 4.12.0 almost every resource rendering is broken.

**Comment by WillyReyno** [comment]
Can confirm having the same issues with `displayUsing()` with the following code : 

```
Text::make('Markets')
                ->sortable()
                ->exceptOnForms()
                ->hideFromDetail()
                ->textAlign('center')
                ->displayUsing(function ($markets) {
                    $count = '-';
                    if ($markets) {
                        $count = count($markets);
                    }

                    return $count;
                })->asHtml(),
```

`markets` is an array in database, before updating to 4.12.0 the count of items was correctly displayed.
Now my entire array is displayed : 

 
![Capture d’écran 2022-07-14 à 19 08 36](https://user-images.githubusercontent.com/5576482/179042274-0c92e612-d015-42e6-a40a-955a6d5b81b9.png)

**Comment by BerkanYildiz** [comment]
Alright, for me it's not even getting called at ALL on my Code field I believe. It used to work fine and stopped working after one of the latest updates.

**Comment by baszach** [comment]
Hi,

I have noticed that `displayUsing` is not working together with `resolveUsing`. The code below will return **joe** (not capitalized) if `displayUsing` is commented out. Otherwise it will return the _capitalized_ **full_name**.  It should return **JOE** (capitalized). 

`Text::make(__('Name'), 'full_name')->resolveUsing(function ($name) { return 'joe'; })->displayUsing(function ($name) { return strtoupper($name); }),`
