### ISSUE TITLE
Use rap2hpoutre/fast-excel@4.0

### ISSUE THREAD

**Issue by henryavila** [laravel/nova-issues#4569]
rap2hpoutre/fast-excel v4 supports php 8.1 and abandoned the deprecated box/spout.
It works with php7.1+

I need to use rap2hpoutre/fast-excel@4.0, but cant use because Larvel Nova still using v3

Ps: Nova base code don't  need to be changed

**Comment by crynobone** [comment]
Pending https://github.com/rap2hpoutre/fast-excel/pull/282 to be merged.
