### ISSUE TITLE
incorrect display value for TextField

### ISSUE THREAD

**Issue by anditsung** [laravel/nova-issues#4584]
if the value for textfield is 0

on index page will show -
<img width="893" alt="Screen Shot 2022-07-15 at 16 04 21" src="https://user-images.githubusercontent.com/1090413/179192034-0a142ce5-82f5-4194-b2ba-bf57153fc282.png">

but on detail page will show correct number 
<img width="519" alt="Screen Shot 2022-07-15 at 16 04 27" src="https://user-images.githubusercontent.com/1090413/179192056-311901b2-d099-4281-98e7-4a2f3da44087.png">

**Comment by BerkanYildiz** [comment]
Happens to me too, 0 is considered null in some instances.

**Comment by crynobone** [comment]
Unable to replicate or not enough information to reproduce.

![image](https://user-images.githubusercontent.com/172966/179453061-44a181e8-2bf3-4168-9e81-88a09b601a21.png)
![image](https://user-images.githubusercontent.com/172966/179453063-496ccd71-1bea-42a1-8e0f-e3df7dc8a27b.png)

Please submit a proper bug report based on the bug report template with reproducing code and detailed description.

**Comment by anditsung** [comment]
i have create the repo here https://github.com/anditsung/nova-issue-4584
<img width="1069" alt="Screen Shot 2022-07-19 at 12 57 03" src="https://user-images.githubusercontent.com/1090413/179676066-f46a97a2-df1c-4c03-8861-dd2c51a68f73.png">

php artisan migrate:fresh --seed

**Comment by lukres** [comment]
This issue appears related to https://github.com/laravel/nova-issues/issues/4619, which also relates to null/zero values displaying as empty on the index view.
