### ISSUE TITLE
displayUsing not working on Number field

### ISSUE THREAD

**Issue by baszach** [laravel/nova-issues#4585]
- Laravel Version: 9.20.0
- Nova Version: 4.12.2
- PHP Version: 8.1.6
- Browser type and version: Firefox (v102.0)

### Description:
I'm using `displayUsing` on a  field but it's not taking the value. The money in my DB is stored as cents but I want to display the euros. Hence I divide by 100 to display the fee.

Dividing the value (6100) by 100 and logging the result.
![Screenshot from 2022-07-15 11-09-37](https://user-images.githubusercontent.com/47082864/179192985-ca0a9c5d-a710-43f8-ab92-f679958564cc.png)

Logging the value and it says 61.
![Screenshot from 2022-07-15 11-10-30](https://user-images.githubusercontent.com/47082864/179193003-95eb1702-779c-44c2-8906-d85d169eec58.png)

Value displayed is 6100.
![Screenshot from 2022-07-15 11-09-58](https://user-images.githubusercontent.com/47082864/179192998-cd7fcb48-9b62-4fed-8400-aa54ea4d9f92.png)

Is anyone able to reproduce this?

**Comment by prookie** [comment]
Unfortunately yes, this seems to be a bug introduced by version 4.12.0, see https://github.com/laravel/nova-issues/issues/4563.

**Comment by baszach** [comment]
Cool. Thanks for the information. I really wasn't sure if I had hid some bug in my code :)

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by baszach** [comment]
I think I found the problem in #4563. I call `resolveUsing` too. `displayUsing` on it's on works. But together with `resolveUsing` it doesn't. I guess we can close this issue, since #4563 was marked as a bug and contains all the info?

**Comment by crynobone** [comment]
I have checked the code and you are meant to use either one, the code has been persisting since the introduction of `displayUsing`.

**Comment by crynobone** [comment]
The code and commit history prove differently.

**Comment by milewski** [comment]
```php
Text::make('Title', 'content->title')
    ->displayUsing(function (array $title) {
        return 'hi';
    })
```

This doesn't seem to be working for me... instead of displaying `hi` it displays `[ "a", "b", "c" ... ]`

**Comment by baszach** [comment]
> The code and commit history prove differently.

I trust you that the commit history proves differently.

There's still a problem here though. Many tickets and issues have been opened since Nova 4.12, regarding the `displayUsing` method. In this repo but also in other Nova related repos. See this [nova-money-field](https://github.com/vyuldashev/nova-money-field/pull/59#issuecomment-1188271892) for example. Or [issue #4597](https://github.com/laravel/nova-issues/issues/4597). Or [here](https://github.com/laravel/nova-issues/issues/4563#issuecomment-1186038172).

**Comment by crynobone** [comment]
Your issue involved `resolveUsing` and `displayUsing`, which didn't change in 4.12 (It has been the same since initial release where `resolveUsing` will be ignored if `displayUsing` is configured).

**Comment by crynobone** [comment]
@baszach I will reopen this issue if you can come out with reproducing repository similar to <https://github.com/nova-issues>. The issue is closed for now until we have more information to validate your claim on this exact issue.
