### ISSUE TITLE
displayUsing not working on Boolean field

### ISSUE THREAD

**Issue by WillyReyno** [laravel/nova-issues#4597]
- Laravel Version: 9.20.0
- Nova Version: 4.12.6
- PHP Version: 8.0.20

### Description:

displayUsing is not working with Boolean field anymore, it was working before I upgraded from 4.10.0.

### Detailed steps to reproduce the issue on a fresh Nova installation:

* Create a resource with a boolean column/field : 
```
            Boolean::make('Published')
                ->exceptOnForms()
                ->displayUsing(function () {
                    return $this->published_date !== null;
                }),
```

Thanks for your help!

**Comment by crynobone** [comment]
You definitely should use `resolveUsing()` here.
