### ISSUE TITLE
Custom Modal Responses: modal not opened on index view

### ISSUE THREAD

**Issue by PatrykTucki** [laravel/nova-issues#4599]
- Laravel Version: 8.82.19
- Nova Version: 4.12.6
- PHP Version: 8.1.7
- Database Driver & Version: Postgres 14.2
- Operating System and Version: Alpine Linux 3.16
- Browser type and version: Chrome 103
- Reproduction Repository: -

### Description:

Modal is being opened after modal action response when on detail view (correct).
Modal is not being opened after modal action response when on index view (incorrect).

Detail view:
![screenshot-localhost_8000-2022 07 19-12_38_20](https://user-images.githubusercontent.com/9299202/179732622-1dfec865-e9e6-4668-b90d-fb8dd546fe59.png)

Index view:
[screencast-localhost_8000-2022.07.19-12_38_57.webm](https://user-images.githubusercontent.com/9299202/179732629-420ea22c-ef7b-413a-8f95-ab5864629e3f.webm)

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Generate asset with `php artisan nova:asset`
2. Add simple modal component:
```
<template>
  <modal>
    <div class="bg-white rounded-lg shadow-lg overflow-hidden" style="width: 600px">
      <a target="_blank" :href="data.url">{{ data.url }}</a>
    </div>
  </modal>
</template>

<script>
export default {
  name: 'impersonation',
  props:{
    data: { type: Object },
  },
}
</script>
```
3. Make your action return modal response:
```
        return Action::modal('impersonation', [
            'url' => $url,
        ]);
```

**Comment by crynobone** [comment]
As a temporary solution you can use the following code:

```js
<modal :show="true">
   // ...
</modal>
```
