### ISSUE TITLE
Filters not working with arabic characters

### ISSUE THREAD

**Issue by Alymosul** [laravel/nova-issues#460]
All filters aren't working if the value is in arabic. exception thrown in JS

```
vendor.js?id=4bdefdc5aca6b5870310:1 DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at a.filterChanged (http://localhost:8000/nova-assets/vendor.js?id=4bdefdc5aca6b5870310:1:1413364)
    at a.e (http://localhost:8000/nova-assets/vendor.js?id=4bdefdc5aca6b5870310:1:485988)
    at a.I3G/.t.$emit (http://localhost:8000/nova-assets/vendor.js?id=4bdefdc5aca6b5870310:1:505227)
    at a.filterChanged (http://localhost:8000/nova-assets/app.js?id=4745c99803a3f5c0c67f:1:773018)
    at r.on.change (http://localhost:8000/nova-assets/app.js?id=4745c99803a3f5c0c67f:1:719119)
    at e (http://localhost:8000/nova-assets/vendor.js?id=4bdefdc5aca6b5870310:1:486054)
    at HTMLSelectElement.Yr.e._withTask.o._withTask (http://localhost:8000/nova-assets/vendor.js?id=4bdefdc5aca6b5870310:1:518537)
```

**Comment by davidhemphill** [comment]
Can you post a configuration to reproduce this issue? The JS stacktrace isn't that helpful without some context.

**Comment by Alymosul** [comment]
Thanks @davidhemphill for your reply.

I have a Division model that has a name field, the name field contains values in arabic (in the database) and I have a User resource that has DivisionFilter as follows:

```
....App/Nova/User.php

    /**
     * Get the filters available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function filters(Request $request)
    {
        return [
            new DivisionFilter,
            new ContractorStatusFilter
        ];
    }
```
```
...App/Nova/Filters/DivisionFilter.php

    /**
     * Apply the filter to the given query.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @param  mixed  $value
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function apply(Request $request, $query, $value)
    {
        return $query->whereHas('division', function ($innerQuery) use ($value) {
            $innerQuery->where('name', $value);
        });
    }

    /**
     * Get the filter's available options.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function options(Request $request)
    {
        return Division::all()->pluck('name', 'name')->toArray();
    }
```
some values in divisions table: القاهرة & الاسكندرية
<img width="492" alt="screen shot 2018-09-05 at 9 38 34 pm" src="https://user-images.githubusercontent.com/8314647/45116843-4783f680-b154-11e8-9467-d45b2b69cf2f.png">

**Comment by Alymosul** [comment]
@davidhemphill @themsaid can you fix this?

**Comment by arook** [comment]
same issue

how to reproduce:
1. `php artisan nova:filter SampleStatus`
2. in options `
public function options(Request $request)
    {
        return ['中文' => '1', '中文2' => '2'];
    }`

**Comment by tufankilicaslan** [comment]
Having same issue,  for the  characters contains outside of the Latin1 range. is it going to be fix?

**Comment by dkulyk** [comment]
PR has been sent to upstream

**Comment by tufankilicaslan** [comment]
@dkulyk  thanks for the info. is it possible to tell us which file and line changed, so we can override it,  without waiting next release?

**Comment by dkulyk** [comment]
Fixes inside Nova storage. 
https://nova.laravel.com/settings#github

**Comment by emad-sure** [comment]
i solved it this way 
nova version : 1.0 

        // in methods 
        handleChange(event) {
            let value  = btoa(unescape(encodeURIComponent(event.target.value)));
            this.$store.commit(`${this.resourceName}/updateFilterState`, {
                filterClass: this.filterKey,
                value: value,
            })
            this.$emit('change')
        },
    
       // in computed
        value() {
            return decodeURIComponent(escape(window.atob(this.filter.currentValue)))
        },
    `
