### ISSUE TITLE
dependsOn() not supported for Trix fields.

### ISSUE THREAD

**Issue by riptin** [laravel/nova-issues#4600]
- Laravel Version: 9.20.0
- Nova Version: 4.12.6
- PHP Version: 8.1.1
- Database Driver & Version: MYSQL 5.7
- Operating System and Version: Microsoft Windows 10 LTSC 10.0.19044 Build 19044
- Browser type and version: Google Chrome 103.0.5060.114 (64-bit)

### Description:

Currently using `dependsOn` method on Trix field throws an error.

**Comment by crynobone** [comment]
Trix field doesn't support `dependsOn` as indicated in the documentation.
