### ISSUE TITLE
Intended url redirect not working

### ISSUE THREAD

**Issue by henryavila** [laravel/nova-issues#4615]
- Laravel Version: 9.21.3
- Nova Version: 4.12.11
- PHP Version: 8.1

### Description:
If I access any url that requires the user to be authenticated, without been authenticated on Nova, I will be redirect to login page, and after that, Nova will load the main Dashboard, but the correct is redirect back to intended url

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Logout from Nova
- Access any direct url (exscept the Nova home)
- Enter the credencials to login
- Will be redirected to home, instead of the intended url

**Comment by crynobone** [comment]
That's the expected behaviour to any Laravel login. Rebind the LoginController if you want something differently.

**Comment by henryavila** [comment]
@crynobone sorry, but I believe you are wrong.

Redirect to intended url is de default behavior, and it's implemented on Nova, and works fine on Nova v3.

See this code from Nova
```php
namespace Laravel\Nova\Http\Controllers;

class LoginController extends Controller
{
   /**
     * The user has been authenticated.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  mixed  $user
     * @return mixed
     */
    protected function authenticated(Request $request, $user)
    {
        $redirect = redirect()->intended($this->redirectPath());

        return $request->wantsJson()
            ? new JsonResponse([
                'redirect' => $redirect->getTargetUrl(),
            ], 200)
            : $redirect;
    }
}
```

The intended redirect is implemented on Nova, but for some reason, it's not working on Nova 4

**Comment by henryavila** [comment]
@crynobone sorry, but I believe you are wrong.

Redirect to intended url is de default behavior, and it's implemented on Nova, and works fine on Nova v3.

See this code from Nova
```php
namespace Laravel\Nova\Http\Controllers;

class LoginController extends Controller
{
   /**
     * The user has been authenticated.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  mixed  $user
     * @return mixed
     */
    protected function authenticated(Request $request, $user)
    {
        $redirect = redirect()->intended($this->redirectPath());

        return $request->wantsJson()
            ? new JsonResponse([
                'redirect' => $redirect->getTargetUrl(),
            ], 200)
            : $redirect;
    }
}
```

The intended redirect is implemented on Nova, it was working on Nova 3, but for some reason, it's not working on Nova 4

**Comment by ArtDepartmentMJ** [comment]
I'm experiencing the same issue, is there any update on this?
