### ISSUE TITLE
Docs: Upgrade Guide v4 - Updating `config/nova.php`

### ISSUE THREAD

**Issue by jjjrmy** [laravel/nova-issues#4618]
In the section on updating your `config/nova.php`, it is missing the `use ActionResource` in the list list, which is confusing when copying the code as the `use HandleInertiaRequests` is added and it seems the other should be removed.

https://nova.laravel.com/docs/4.0/upgrade.html#updating-configuration-assets-and-translations

> Next, let's update the Nova configuration file. First, ensure that the `middleware` and `api_middleware` configuration options within your application's `nova` configuration file appear as follows:

```diff
+ use Laravel\Nova\Actions\ActionResource;
use Laravel\Nova\Http\Middleware\Authenticate;
use Laravel\Nova\Http\Middleware\Authorize;
use Laravel\Nova\Http\Middleware\BootTools;
use Laravel\Nova\Http\Middleware\DispatchServingNovaEvent;
use Laravel\Nova\Http\Middleware\HandleInertiaRequests;

return [

    // ...

];
```

**Comment by crynobone** [comment]
Upgrade Guide should only reflect changes needed, if a code needs to be removed we would mention it.

**Comment by jjjrmy** [comment]
> Upgrade Guide should only reflect changes needed, if a code needs to be removed we would mention it.
@crynobone 

Except that all the other `use`'d classes that are shown in the snipper are not updated, only the `HandleInertiaRequests` is added. And the `ActionResource` is missing from the snipper, so it's a bit confusing.

**Comment by jjjrmy** [comment]
If it only reflected changes needed then it should only show the new `HandleInertiaRequests` which would also make sense. Yet that is also not mentioned directly but inferred by it being in the snippet.
