### ISSUE TITLE
The value returned by displayUsing is not displayed on index if the underlying model field value is null

### ISSUE THREAD

**Issue by lukres** [laravel/nova-issues#4619]
- Laravel Version: 9.21.5
- Nova Version: 4.12.12
- PHP Version: 8.1.4
- Database Driver & Version: PDO / mysql / mysqlnd 8.1.4

### Description:
The issue manifested in my system after upgrading Nova to 4.12. 

### Detailed steps to reproduce the issue on a fresh Nova installation:

Create a resource with a nullable attribute, add a TextField:

```
Text::make('Name', 'name')->help('Optional')->displayUsing(function() {
    return 'Test';
})
```

The index will show empty cells for resources where the name of the underlying model is null.
<img width="135" alt="Screenshot 2022-07-22 at 10 33 15" src="https://user-images.githubusercontent.com/39759453/180398817-43ba1098-ceb3-47b7-b5eb-d979abfa20d1.png">

**Comment by provydon** [comment]
i'm experiencing the same thing

**Comment by suchoproduction** [comment]
I have the same problem with Stack Line

```
            Stack::make(__('premise.field.area'), [
                Line::make('area')
                    ->asBase()
                    ->displayUsing(fn () => $this->area ? '<strong>' . $this->area . ' m²</strong>' : null)
                    ->asHtml(),

                Line::make('price')
                    ->asBase()
                    ->displayUsing(fn () => $this->price ? Currency::format($this->price, $this->currency, 2) . '/m²' : '')
                    ->asHtml(),
            ])->onlyOnIndex(),
```

After rewriting in the Text field it works, but not in another place
