### ISSUE TITLE
[FEATURE REQUEST] Allow Relationship field types to display custom names.

### ISSUE THREAD

**Issue by rickmacgillis** [laravel/nova-issues#462]
Relationship field types default to the names defined on the relationship resource or the auto-generated resource name. They do not allow for custom names like other field types. With `ownedTeams()` and `teams()` on the Laravel Spark `CanJoinTeams` trait, we need to be able to display those with unique names. Using `Teams` for both headings doesn't work very well for distinguishing what they both mean.

Issue #116 also has this issue.

Example:

```
...
HasMany::make(__('Owned Teams'), 'ownedTeams', Team::class)
    ->onlyOnDetail(),
           	
BelongsToMany::make(__('Member of Teams'), 'teams', Team::class)
    ->onlyOnDetail(),
...
```

**Comment by taylorotwell** [comment]
This repository is for tracking bugs. Feature requests may be emailed to Nova customer support.

**Comment by rickmacgillis** [comment]
@taylorotwell Where do I do that at?

**Comment by dinhngocvuong** [comment]
@rickmacgillis Check it out
<img src="https://image.prntscr.com/image/R6-BJp_aQgK1gvHjwPzCzg.png">

**Comment by rickmacgillis** [comment]
@dinhngocvuong Thanks. I missed that, and now I sent the feature request.
