### ISSUE TITLE
Intended url redirect not working on Nova 4, but works on nova 3

### ISSUE THREAD

**Issue by henryavila** [laravel/nova-issues#4629]
- Laravel Version: 9.21.3
- Nova Version: 4.12.11
- PHP Version: 8.1

### Description:
Nova 4 breaks the intented url from Nova3.
If I access any url that requires the user to be authenticated, without been authenticated on Nova, I will be redirect to login page, and after that, Nova will load the main Dashboard, but the correct is redirect back to intended url

In a fresh nova 3 instalation, if we access, for example, the url https://nova3.test/nova/resources/users without login, after the login, the user will be redirected to https://nova3.test/nova/resources/users

This implemented in Nova3 and Nova 4 in `LoginController`
```php
namespace Laravel\Nova\Http\Controllers;

class LoginController extends Controller
{
   /**
     * The user has been authenticated.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  mixed  $user
     * @return mixed
     */
    protected function authenticated(Request $request, $user)
    {
        $redirect = redirect()->intended($this->redirectPath());

        return $request->wantsJson()
            ? new JsonResponse([
                'redirect' => $redirect->getTargetUrl(),
            ], 200)
            : $redirect;
    }
}
```

but it don't  works on nova 4, probally because o inertiaJs

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Logout from Nova
- Access any direct url (exscept the Nova home)
- Enter the credencials to login
- Will be redirected to home, instead of the intended url

**Comment by crynobone** [comment]
We already have dusk tests covering this use case. https://github.com/laravel/nova-dusk-suite/blob/master/tests/Browser/AuthenticatesUserTest.php

Submit a full reproducing repository similar to https://github.com/nova-issues to verify the issue

**Comment by crynobone** [comment]
Closing this as stale at the moment, feel free to create a new issue with a full reproducing repository.
