### ISSUE TITLE
iFrame opens instead of a redirect to the page

### ISSUE THREAD

**Issue by felipe-dsdev** [laravel/nova-issues#4630]
- Laravel Version: 9.21.3
- Nova Version: 4.12.12
- PHP Version: 8.1.1
- Database Driver & Version: MariaDB 10.5.12
- Operating System and Version: Amazon Linux 2 (Lambda Function with bref php-81-fpm layer)
- Browser type and version: Chrome 103.0.5060.134 64 bits

### Description:

I have a fresh install of Laravel with Laravel Nova and when I click on a link an iFrame opens instead of a redirect to the page.

An example of this problem is the print below as the error:
![image](https://user-images.githubusercontent.com/101280418/180779994-b17dd962-6fee-48cb-8325-9b2943a75c43.png)

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Up the server
- Click on a link

**Comment by felipe-dsdev** [comment]
There is an issue on inertiajs github similar to this same error: https://github.com/inertiajs/inertia/issues/586

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by CodeTechNL** [comment]
I have the same issue and cant discover what is happening. Every now and then after deploying to the staging env this problem pops up. I've removed all the third party extension and still, this issue is showing up.

**Comment by CodeTechNL** [comment]
@felipe-dsdev the issue is with the request headers. Inertia requires you to send the X-Inertia header. I see that you are using Bref.sh and you need to update your config. At the Laravel section, you can find how to add custom headers. https://inertiajs.com/the-protocol shows you all the headers you need to send.

**Comment by felipe-dsdev** [comment]
@CodeTechNL thanks, I'll add these headers and try to run again.

I had problems with other headers, they were causing problems with the CSRF Token.

Note: The problem is not Bref, but CloudFront, as it is a CDN and does the proxy, it needs to pass the headers, but you have to whitelist which headers to pass.

**Comment by felipe-dsdev** [comment]
@CodeTechNL thanks, I inserted the header and it worked.

**Comment by CodeTechNL** [comment]
How did you added this to the config of bref @felipe-dsdev, I did it manually in AWS, kinda curious

**Comment by felipe-dsdev** [comment]
@CodeTechNL I'm using the Serverless Framework lift plugin with Server Side configuration.

The following link has documentation on how to configure the headers:
https://github.com/getlift/lift/blob/master/docs/server-side-website.md#forwarded-headers

**Comment by drelocatelli** [comment]
me too
