### ISSUE TITLE
DisplayUsing falls back to normal value when returned 0

### ISSUE THREAD

**Issue by gizburdt** [laravel/nova-issues#4635]
- Laravel Version: 9.21.6
- Nova Version: 4.12.12
- PHP Version: 8.1.6
- Database Driver & Version: MySQL 5.7.32
- Operating System and Version: macOS 12.4
- Browser type and version: Chrome 103.0.5060.134
- Reproduction Repository: private (sorry)

### Description:
When you have a field with `->displayUsing` and the callback returns 0, the value will fallback to `field.value`

### Detailed steps to reproduce the issue on a fresh Nova installation:
* Add a field with a `->displayUsing`
* Do some kind of calculation in the callback that returns `0`
* The normal value of the field is shown
* I think it's desired to show `0`

### Research
Did some research, I think in file `resources/js/components/PanelItem.vue`, line `93`. Maybe check if this.field.displayedAs is `null`?

Thanks!

**Comment by crynobone** [comment]
Already fixed pending next release.

**Comment by gizburdt** [comment]
Hi @crynobone, sorry to comment on a closed issue. The new update fixed https://github.com/laravel/nova-issues/issues/4634, but did not yet fix this one. Is this one fixed in the next release, or did you maybe confuse these two issues? 

Thanks for the awesome work! :)
