### ISSUE TITLE
Nova stops loading resources after switching to a custom tool page

### ISSUE THREAD

**Issue by JoeSixGo** [laravel/nova-issues#4636]
- Laravel Version: 9.21.6
- Nova Version: 4.12.12
- PHP Version: 8.1.5
- Database Driver & Version:
- Operating System and Version: MySQL 5.7.23
- Browser type and version: Firefox 102.0.1

### Description:

When I browse to a custom tool page, it loads and works correctly, but when i click on another resource or tool, Nova stops  loading any resource, until I force a full page reload from the browser. I made a new custom tool using **php artisan nova:tool**.
Browsing to that new empty tool (only the black hole default page) does not break navigation. Only with the existing custom tool.
I think it must be an issue with inertia.

**Comment by JoeSixGo** [comment]
Also, there are no error messages in the console and I'm getting the JSON response from the server.

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by dmason30** [comment]
@JoeSixGo I had this before it is because your root component for your tool has many root elements. I am unsure if this a bug or something that you have to do for nova or inertia to work.

For Example, if in your root component:

```html
<template>
    <div></div>
    <div></div>
</template>
```

Then you will replicate this issue. However, it can be fixed by ensuring there is only one single root element:

```html
<template>
  <div>
      <div></div>
      <div></div>
  </div>
</template>
```

**Comment by JoeSixGo** [comment]
@dmason30 And that worked! Thanks for your help! I wouldn't figured it out in a million years. I have spent almost a full day trying to fix it.
