### ISSUE TITLE
Method Laravel\Nova\Fields\Trix::dependsOn does not exist.

### ISSUE THREAD

**Issue by sudeeshketto** [laravel/nova-issues#4637]
- Laravel Version: 8.83.22
- Nova Version: 4.12.12
- PHP Version: 8.1

### Description:
Trix::make(__('Description'), 'description')->hide()->dependsOn('status', function (Trix $field, NovaRequest $request, FormData $formData) {
                            if ($formData->status == 'success') {
                            $field->show()->rules(['required']);
                        }
                })
How can I show hide Trix field? depends on is not working.
Please help.

**Comment by crynobone** [comment]
Trix doesn't support `dependsOn`: https://nova.laravel.com/docs/4.0/resources/fields.html#dependent-fields
