### ISSUE TITLE
Image field unexpected behaviour with validation rule "required"

### ISSUE THREAD

**Issue by arkoe** [laravel/nova-issues#4640]
- Laravel Version: 9.21.3
- Nova Version: 4.12.11 (Silver Surfer)
- PHP Version: 8.1

### Description:
When adding `->rules('required')` to an `Image` field, you are required to select a file when editing a Resource, even though there is already an image saved for this resource (the preview shows the existing image):

![image](https://user-images.githubusercontent.com/8835399/181255110-38c15f06-9270-44cd-943b-60b6fe475a23.png)

### Detailed steps to reproduce the issue on a fresh Nova installation:

Add an `Image` field to a Resource class:

```php
Image::make('Partner Logo')
    ->rules('required')
    ->hideFromIndex(),
```

### Expected behaviour

I would expect the `required` validation rule to pass even when not uploading a new image. If for example you'd only set the `required` on `creationRules()`, you are allowed to 'delete' an image from the edit-page and save it.

**Comment by davidhemphill** [comment]
If the image isn't required every time you update the resource, then you probably shouldn't be using the `required` rule on `updateFields`, right? 

For example, if you have a required text field, and remove the value of the field when editing, you'd expect the validation to catch that. Seems like the same thing with any other field type?

**Comment by arkoe** [comment]
> If the image isn't required every time you update the resource, then you probably shouldn't be using the `required` rule on `updateFields`, right?
> 
> For example, if you have a required text field, and remove the value of the field when editing, you'd expect the validation to catch that. Seems like the same thing with any other field type?

You are correct. But if you would throw the `required` in `creationRules()` for example, my direct issue would be fixed. However, you will still be able to remove the image using the trash-icon button, and that's something you do not want to happen.

**Comment by davidhemphill** [comment]
I'm just curious why you wouldn't use the required validation inside `creationRules` instead:

```php
Image::make('Partner Image')
    ->creationRules('required'),
```

This seems to do exactly what you're asking. Technically the field is empty with the way you're doing it, even though the database has a value. Since we can't attach a file from the filesystem when pulling the update fields, there's no way it can have a value until you put one in. Can you try that?

**Comment by crynobone** [comment]
@arkoe 

You can disable `deletable()` (used only on Form view) and instead only allows uploading a new file to replace the old one. `prunable()` would then be executed once the model has been updated to remove the previous file.

```php
Image::make('Photo', 'photo')
                ->prunable()
                ->deletable(false)
                ->creationRules(['required', 'file'])
                ->updateRules(['sometimes', 'file']),
```
