### ISSUE TITLE
Loading overview of a resource will break, if you name a resource "card"

### ISSUE THREAD

**Issue by flazer** [laravel/nova-issues#4644]
- Laravel Version: 9.22.1
- Nova Version: 3.32.0 
- PHP Version: 8.0.13

### Description:

When creating a resource named "Card" the overview will not load any stored items.

![card-issue-overview](https://user-images.githubusercontent.com/5859657/181572716-0591b96e-d2e6-4509-9453-43caab4920ab.png)

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Add a resource and name it "Card" 
```
class Card extends Resource {
...
}
```
- Create and save a record in there
- Go back to overview and admire the loading animation :)

**Comment by crynobone** [comment]
https://nova.laravel.com/docs/4.0/resources/#defining-resources

![image](https://user-images.githubusercontent.com/172966/181648206-e42f6f97-8cc0-4bd3-9957-d205922ba26a.png)
