### ISSUE TITLE
`readonly()` disables the field

### ISSUE THREAD

**Issue by chimit** [laravel/nova-issues#4649]
- Laravel Version: 9.21.6
- Nova Version: 4.12.12
- PHP Version: 8.1.7
- Operating System and Version: macOS Monterey 12.4
- Browser type and version: Safari macOS

### Description:

When I use the `readonly()` method I get `readonly disabled` attributes added into my input. The problem is that I don't want to disable the field. I just want to make it not editable manually.

### Detailed steps to reproduce the issue on a fresh Nova installation:

I'm using `dependsOn` to set a default value to the calculated final amount field. Everything works well until I submit the form. The `amount` field can't be `null`. It's due to the HTML specific when the input field value is not sent when it has a `disabled` attribute. I don't expect this attribute to be added when use the `readonly()` method. Probably, they should be split into two different methods for more granular control: `readonly()` and `disabled()`:

```php
Currency::make('Amount')
    ->currency($this->currency)
    ->dependsOn(
        ['currency', 'base_amount', 'discount'],
        function (Text $field, NovaRequest $request, FormData $formData) {
            $field->currency($formData->currency);
            $field->default($formData->base_amount - $formData->discount);
        }
    )
    ->readonly();
```

**Comment by crynobone** [comment]
Expected behaviour for `readonly()`, see previously closed issue.

**Comment by msucevan** [comment]
> Expected behaviour for `readonly()`, see previously closed issue.

This issue should be reopened. Since readonly don't mean that the field must be disabled. This is the main difference between using disabled and readonly. readonly will append the value to the form data, but disabled will not append the value to the form data.

```
The Boolean readonly attribute, when present, makes the element not mutable, meaning the user can not edit the control.
```

then,

```
The difference between [disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled) and readonly is that read-only controls can still function and are still focusable, whereas disabled controls can not receive focus and are not submitted with the form and generally do not function as controls until they are enabled.
```

How this should be the expected behaviour?
