### ISSUE TITLE
Card Compiling Stuck on 95% - mix-manifest gets wrong path

### ISSUE THREAD

**Issue by CraigHarley** [laravel/nova-issues#465]
After generating a card with the command from the docs and attempting to build it, it get's stuck on 95% completion:

![image](https://user-images.githubusercontent.com/8432365/45151678-da5d7900-b1c6-11e8-80cd-2bc942112926.png)

This is the generated `mix-manifest.json` which doesn't look correct:
```
{
    "/C:/dist/js/card.js": "/C:/dist/js/card.js",
    "/dist/css/card.css": "/dist/css/card.css"
}
```

Maybe these issues are related.

**Comment by julianpoma** [comment]
#143

**Comment by CraigHarley** [comment]
I've tried the code in the other issues, now `webpack.mix.js` looks like this:
```
let mix = require('laravel-mix')

mix.js('resources/js/card.js', __dirname + 'dist/js')
   .sass('resources/sass/card.scss', __dirname + 'dist/css')
    .webpackConfig({
        resolve: {
            symlinks: false
        }
    })
```

Which generates the following `mix-manifest.json`
```
{
    "/C:/dist/js/card.js": "/C:/dist/js/card.js",
    "/dist/css/card.css": "/dist/css/card.css"
}
```

The process finishes though and the files go into the correct place. @davidhemphill I'm aware that the generated `mix-manifest.json` is wrong, how can I get it to output the correct mappings?

**Comment by davidhemphill** [comment]
Just pushed a fix for Windows when compiling assets. 🚀
