### ISSUE TITLE
Fields look squeezed

### ISSUE THREAD

**Issue by davidhemphill** [laravel/nova-issues#4653]
Hi,
my some of my action modals look very squeezed too since Nova 4 e.g. with the `KeyValue` field
![image](https://user-images.githubusercontent.com/47082864/181046968-7f088a03-33d3-43f7-9324-9813fdf7d8a3.png)

but also when some field names are long
![image](https://user-images.githubusercontent.com/47082864/181047190-aaf9250b-f9b6-42b3-8000-955b3604b182.png)

_Originally posted by @baszach in https://github.com/laravel/nova-issues/discussions/4528#discussioncomment-3232353_

**Comment by crynobone** [comment]
@baszach As for the `Text` field, it might be better to use `stacked()` here.

![image](https://user-images.githubusercontent.com/172966/183014390-11c84f94-46d5-4b1b-ab9f-cafa79112a73.png)

We can introduce `break-all` CSS but I don't think it would look nice:

![image](https://user-images.githubusercontent.com/172966/183014457-eded4735-edbb-4b4f-890f-e6dd6ed11dfa.png)
