### ISSUE TITLE
enum in nova

### ISSUE THREAD

**Issue by AzadGh95** [laravel/nova-issues#4662]
- Laravel Version: 9.23.0
- Nova Version: 4.0
- PHP Version: 8.1.7
- Database Driver & Version: sqlite
- Operating System and Version: Ubuntu 21.04
- Browser type and version: GoogleChrome Version 103.0.5060.134
- Reproduction Repository: https://github.com/Vasetkala/financial

### Description:
when i want to use `enum` in nova:
in *Enums\StatusEnum.php*
```php
enum StatusEnum:string
{      
    case pending = 'pending',
    case accept = 'accepted',
}
```
in *migration*:
```php
...
$table->enum('status',Status::cases());
...
```
in *Model*:
```php
...
protected $casts = [
   'status' => StatusEnum::class
];
...
```
and in *Nova Resource*:
```php
...
Select::make('Status', 'status')
  ->options(StatusEnum::cases()),
...
```
, get this error when run `php artisan migrate`:
```
Object of class App\Enums\StatusEnum could not be converted to string
```
and het this error when insert:
```
Object of class  App\Enums\StatusEnum could not be converted to string
```

**Comment by crynobone** [comment]
You should create a static method on `App\Enums\StatusEnum` to return `label` and `value` array.
