### ISSUE TITLE
DateTime::class resolveUsingDisplayCallback() still setting $this->value not $this->displayedAs

### ISSUE THREAD

**Issue by ianrobertsFF** [laravel/nova-issues#4665]
- Laravel Version: 9.22.1
- Nova Version: 4.12.14
- PHP Version: 8.1.7

### Description:
DateTimeField.vue was updated in 4.12.14 to use `displayedAs` when `usesCustomizedDisplay` is true, but `resolveUsingDisplayCallback()` for that field is still setting `$this->value` rather than `$this->displayedAs` (`DateTime.php:161`)

This results in no value being displayed at all when `displayUsing` is used for a DateTime field

**Comment by jeffreyzant** [comment]
Any ETA on the release date?

**Comment by Elshaden** [comment]
Any update on this issue,

**Comment by marijoo** [comment]
Closed as completed almost three weeks ago – still no release or ETA.

**Comment by denniselsinga** [comment]
Seems like this is not released yet...

**Comment by dualklip** [comment]
Nova 4.13.0 has been released. Now seems displayUsing() is working
