### ISSUE TITLE
When clearing global search, it closes as expected then re-opens

### ISSUE THREAD

**Issue by RhysLees** [laravel/nova-issues#4669]
- Laravel Version: ^9.19
- Nova Version: ^4.12
- PHP Version: 8.1
- Database Driver & Version: Mysql
- Operating System and Version: WSL2 Win 11
- Browser type and version: Chrome Latest
- Reproduction Repository: N/A fresh install of nova (the original repo is private)

### Description:

![c92818841c5810fbdbbca2cf07454b25](https://user-images.githubusercontent.com/43909932/183253474-c788d07e-6b44-44ce-bfb1-e856b7a16275.gif)

### Detailed steps to reproduce the issue on a fresh Nova installation:

Global Search for something then backspace the search.
This should close the dialog as the expected behaviour but then it is opening again

**Comment by crynobone** [comment]
I was only able to replicate this on dusk tests using `InteractsWithElement::clear()` method but not on an actual browser using Mac and Windows with Chrome. 

Will fixed the issues based on just dusk tests results for now.
