### ISSUE TITLE
Trix field - attaching files issue on registering a  Nova resource

### ISSUE THREAD

**Issue by thisprojectworks** [laravel/nova-issues#467]
Hi!

Laravel version: 5.7
Laravel Nova version: 1.0.12 

I have a problem with the TRIX field when attaching files.
I have added the migrations and in the Kernel file as it says in the documentation to upload files with Trix.

I describe the problem:

I have a Nova resource (App/Nova /Exhibitions) to which I have added the TRIX field, when I'm going to register a new one (App/Nova/Exhibitions) I add the photos that I want in the field, but when I click the create button I gives this error:

```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'attachable_id' cannot be null (SQL: insert into `nova_trix_attachments` (`attachable_type`, `attachable_id`, `attachment`, `disk`, `url`, `updated_at`, `created_at`) values (App\Exhibition, , cHeZaaVv2LlyNwgrbIJhJvUmzcluD5TDx4bOb3VV.png, public, http://espaitactel.test/storage/cHeZaaVv2LlyNwgrbIJhJvUmzcluD5TDx4bOb3VV.png, 2018-09-06 10:32:39, 2018-09-06 10:32:39))
```

However I have observed that when it comes to an (App/Nova/Exhibitions) already registered and I edit it then I do not get an error and I can save it.

This is due to the fact that when registering, it is not adding me the model ID (App/Nova/Exhibitions) since it does not yet have it. I think it's something that you should solve.

Thank you very much!
Carlos

**Comment by taylorotwell** [comment]
We are unable to debug your issue without a recreatable code example.
