### ISSUE TITLE
Error compiling components when Vue 2 is installed in main package.json

### ISSUE THREAD

**Issue by WillyReyno** [laravel/nova-issues#4677]
- Laravel Version: 9.24.0
- Nova Version: 4.12.14
- PHP Version: 8.0.9
- Operating System and Version: MacOS 12.5
- Reproduction Repository: https://github.com/WillyReyno/nova-component-vue

### Description:

This is issue is related to discussion #4549, but I'm creating an issue as I was able to make a reproduction repo.

When Vue 2 is installed in the main package.json of the laravel app, nova components compilation fails with the following error: 

![Capture d’écran 2022-08-09 à 19 24 24](https://user-images.githubusercontent.com/5576482/183717948-3e6ed012-2dd7-459d-9351-97b53eed70a0.png)

### Detailed steps to reproduce the issue on a fresh Nova installation:

* Create custom tool `php artisan nova:tool acme/price-tracker`
* Install Vue 2 in project's root : `npm install vue@^2.7.8`
* Move into custom tool directory `cd nova-components/PriceTracker`
* Run `npm run dev` / `npm run prod`

**Comment by crynobone** [comment]
This is either an issue with Webpack, Mix or NPM. So far we haven't found a solution for it.
