### ISSUE TITLE
BelongsToMany->fields not behaving like in documentation

### ISSUE THREAD

**Issue by NeroAzure** [laravel/nova-issues#468]
I have a relationship with extra fields on the pivot table. The columns have the names `type` and `notes` i implemented them as select and text fields respectively. 

But the strange things happened then, to see the values of the fields in the index table on the detail-view i had to add a `pivot.`-prefix to the field names, which made them unusable in the forms, so i were forced to double up the fields and only show them when needed (with prefix exceptOnForms and without onlyOnForms)

i used the [documentation](https://nova.laravel.com/docs/1.0/resources/relationships.html#belongstomany) as guide, but it dosn't work that way in the versions: nova is 1.0.10 and laravel v5.6.34

**Comment by taylorotwell** [comment]
We are unable to debug your issue without a recreatable code example.
