### ISSUE TITLE
#4619 is not fixed as of 4.12.14 (The value returned by displayUsing is not displayed on index if the underlying model field value is null)

### ISSUE THREAD

**Issue by lukres** [laravel/nova-issues#4682]
Sorry, I cannot post under the original issue. The issue, description remains exactly the same.
https://github.com/laravel/nova-issues/issues/4619 is not fixed as of 4.12.14

You did fix the related issue #4584 (as the release notes mention: "Fixed an issue where Text fields wouldn't always consistently return a string."), but not #4619.

**Comment by crynobone** [comment]
Please submit a proper bug report as requested in the issue template with example to reproduce the issue and reproducing code.

Also please ensure you already run `php artisan nova:publish` and using the latest assets.
