### ISSUE TITLE
Unable to scroll through list of actions

### ISSUE THREAD

**Issue by samdharris** [laravel/nova-issues#4688]
- Laravel Version: 9.24.0
- Nova Version: 4.12.14
- PHP Version: 8.0.19
- Database Driver & Version: Mysql
- Operating System and Version: MacOS
- Browser type and version: Google Chrome 104.0.5112.79

### Description:
When a resource has a significant number of actions, there is no overflow to access other actions in the list. See the screencast below for better context.

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Have a resource with a significant number of actions (my resource has 12)
2. View a resource in Nova, and click on the horizontal 3 dots in the top right next to the edit icon. 

https://user-images.githubusercontent.com/8377862/184143950-aa01245f-7767-4ab7-85b9-9f841a6f21bf.mov

**Comment by crynobone** [comment]
The container already contains `scroll-wrap overflow-x-hidden overflow-y-auto` which should cover the usage.

![CleanShot 2022-08-12 at 09 24 14](https://user-images.githubusercontent.com/172966/184268312-b87bfc6f-7491-4506-9071-36a3e99aaacc.gif)

Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by samdharris** [comment]
> The container already contains `scroll-wrap overflow-x-hidden overflow-y-auto` which should cover the usage.
> 
> ![CleanShot 2022-08-12 at 09 24 14](https://user-images.githubusercontent.com/172966/184268312-b87bfc6f-7491-4506-9071-36a3e99aaacc.gif) [ ![CleanShot 2022-08-12 at 09 24 14](https://user-images.githubusercontent.com/172966/184268312-b87bfc6f-7491-4506-9071-36a3e99aaacc.gif) ](https://user-images.githubusercontent.com/172966/184268312-b87bfc6f-7491-4506-9071-36a3e99aaacc.gif) [ ](https://user-images.githubusercontent.com/172966/184268312-b87bfc6f-7491-4506-9071-36a3e99aaacc.gif)
> 
> Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

I've had a look at the markup and I can see that the overflow-y-auto property is being overwritten somewhere in my install...

<img width="1203" alt="Screenshot 2022-08-12 at 10 11 53" src="https://user-images.githubusercontent.com/8377862/184323569-eb327be1-a651-4670-9d0e-08f9c2bdbae0.png">

I'll setup a repo
