### ISSUE TITLE
Pivot fields with same name as resource field show resource's value

### ISSUE THREAD

**Issue by jspapp** [laravel/nova-issues#469]
I have the following (simplified) table setup, containing jobs and users attached to those jobs many-to-many. The pivot fields track the user's job status, clock-in, clock-out.
```
jobs
  - id
  - status
  - start_time
  - end_time

job_user
  - job_id
  - user_id
  - status
  - start_time
  - end_time
```

However, in `Nova\Job`, trying to display those pivot fields shows their headers, but fills it with that value from the job.
```php
BelongsToMany::make('Users')
  ->fields([
  Select::make('Status')
    ->options([
      'Pending',
      Accepted',
      'Complete',
    ]),

  DateTime::make('Start Time')
    ->format('M/D/YYYY h:mm a'),

  DateTime::make('End Time')
    ->format('M/D/YYYY h:mm a'),
]),
```

![image](https://user-images.githubusercontent.com/2307915/45177494-22899500-b1e1-11e8-981a-1a47753ae32d.png)

**Comment by jspapp** [comment]
I was able to solve by explicitly stating the pivot:
```php
DateTime::make('Start Time', 'pivot.start_time'),
```

**Comment by o7n** [comment]
Yes, prepending 'pivot.' to the column name fixes that issue. 

But it introduces a new issue where updating that field in the pivot relation does not work any more: the field is empty when the update screen is opened, and entering a value does not do anything.
