### ISSUE TITLE
How associate existing record in HasMany relationship

### ISSUE THREAD

**Issue by fat4lix** [laravel/nova-issues#47]
Nova 1.0.5

For example Team has many users, and user model has team_id. 
HasMany relations in Team detail page allows only to create new User, but what if I want to add an existing user to the Team?

**Comment by vyuldashev** [comment]
Use BelongsToMany.

**Comment by Xsecrets** [comment]
I would like to know this question too, and no using BelongsToMany is not a valid answer as that represents a many to many relationship with a pivot table. We are asking about a one to many relationship without a pivot table.

**Comment by fat4lix** [comment]
> @fat4lix you mean BelongsTo / HasMany?

Yes

**Comment by dillingham** [comment]
Add a `BelongsTo::make('Team')` field to the user and a `HasMany::make('Users')` to team

@alexbowers solved

**Comment by Xsecrets** [comment]
@dillingham yes that works, but the question was from the team how can you select a pre-existing user without creating a new one.

**Comment by tumispro** [comment]
Why is this closed? I am unable to link an existing user to a team (as per the example), only create new ones.

**Comment by reppair** [comment]
yeah it should be working the other way around as well..

**Comment by loreberti89** [comment]
Why is ti Closed?? It's incredible that it is Impossibile associate an Existing record without create new.

**Comment by martijnimhoff** [comment]
I would really like to have an answer to the original question!

**Comment by kr4ft3r** [comment]
If anyone came here wondering, this is how you assign an existing record to a hasMany relationship without creating a new record:
`$team->assignedUsers()->save($user);`
Assuming $team holds Team model record, which has assignedUsers function that returns hasMany, and $user is an existing user record.
