### ISSUE TITLE
[Request] Show total resource records count

### ISSUE THREAD

**Issue by outhebox** [laravel/nova-issues#470]
Hello, Is there a way to show a total records count, hope to see the total number on each resources table in the next release 
![screenshot from 2018-09-06 23-46-22](https://user-images.githubusercontent.com/8408646/45187391-cc444280-b230-11e8-9ed4-407f38e8cbc7.png)

**Comment by davidhemphill** [comment]
This repository is for tracking bugs. Feature requests may be emailed to Nova customer support.

**Comment by outhebox** [comment]
@davidhemphill Where Is the Nova customer support email exactly listed on the Nova website?

**Comment by outhebox** [comment]
i've fixed this, if anyone want to enable this you have to put the code in this path "vendor/laravel/nova/resources/js/views/Index.vue" - line 114

`<div class="px-3 font-bold capitalize tracking-wide text-80">Total {{ resourceName }} ({{ allMatchingResourceCount }})</div>`

**Comment by solmel** [comment]
> This is coming soon.

Any updates? THanks

**Comment by davidhemphill** [comment]
This is already in Nova. Check out latest releases.
