### ISSUE TITLE
Apache root's subfolder ref #181

### ISSUE THREAD

**Issue by num3r06** [laravel/nova-issues#471]
Hi
In reference a #181 
In windows my development environment it's a bitnami wampstack with apache.
My laravel app it's in a root subfolder's http://localhost/ater/public and work fine.
When I've installed nova the admin panel search the asset on root folder's and obviusly not found.
with php artisan serve works
There's a way for using nova in this mode?
![img](https://user-images.githubusercontent.com/7809704/45205037-4f8d8480-b281-11e8-82d7-1b57dbe2c65f.png)
This is a fresh installation of laravel with nova 1.0.12
Thx

**Comment by fletch3555** [comment]
The `asset()` helper method uses your `APP_URL` to determine what path to use.  You likely need to update `APP_URL` in your .env file to include "ater/public".  This is almost 100% not specific to Nova

**Comment by num3r06** [comment]
in nova's layout.blade.php it's not used asset() helper but mix() helper:
```    
<link rel="stylesheet" href="{{ mix('app.css', 'nova-assets') }}">
```
i change APP_URL in the .env file but nothing change
this is my .env
```
APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
APP_DEBUG=true
APP_URL=http://localhost/ater/public/

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3307
DB_DATABASE=ater
DB_USERNAME=root
DB_PASSWORD=secret

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

``
the ater folder it's a subfolder of root's apache folder

**Comment by flashadvocate** [comment]
Having the same issue, and would rather not have to hardcode these paths in the view

**Comment by num3r06** [comment]
Any chance for this. I don't want to use Valet or Doker for development and the only solution for locally development on windows it's a wamp server with many root's directory subfolder (i use bitnami wampstack)

**Comment by AegirLeet** [comment]
Why don't you use `php artisan serve` for local development?

**Comment by num3r06** [comment]
Yes i can but i want to know if it's possible using nova in a subfolder

**Comment by flashadvocate** [comment]
Worth noting that this is not just a local development issue. It’s extremely likely that laravel is used in a production environment that warrants deploying in a sub folder

**Comment by AegirLeet** [comment]
- Replace all calls to `mix()` in your nova::layout view with your adjusted paths
- In Nova's resources directory, replace all instances of `/nova-api` with your adjusted paths
- Recompile Nova's assets and use those in your application

... That might work.

**Comment by flashadvocate** [comment]
Well yeah, until you need to update Nova to the latest release. We shouldn't need to manually make this change.

**Comment by flashadvocate** [comment]
Yeah, unfortunately that's not always true. I work for a university where 3rd-level domains are a premium, and are rarely given out except under very specific circumstances. Nova shouldn't make assumptions about the deployment strategy for an application. It should be flexible enough to support whatever APP_URL is set to.

**Comment by ben182** [comment]
couldn't this easily be fixed by replacing
`<link rel="stylesheet" href="{{ mix('app.css', 'nova-assets') }}">`
with
`<link rel="stylesheet" href="{{ asset(mix('app.css', 'nova-assets')) }}">`?

**Comment by markgp** [comment]
That only gets the assets loading. All of the API endpoints are hard-coded to `/nova-api` throughout the application.

**Comment by num3r06** [comment]
My subfolder's name is ater.
Can you help me to write the .htaccess file correctly
thanks a lot

**Comment by num3r06** [comment]
I try but not works

**Comment by albalooshi** [comment]
@num3r06 it worked for me, try restarting the apache server.

**Comment by num3r06** [comment]
Adding also this works  
```Alias /vendor/nova /var/www/html/ater/public/vendor/nova```
thx

**Comment by num3r06** [comment]
Sorry,
All works fine but nova-api path seems to be hardcoded and not configurable.
There's a chance to overwrite this path?

**Comment by Dennis1000** [comment]
Nova needs to honor the APP_URL .env-setting, all other comments about cheap subdomains, etc are totally senseless.

**Comment by MsFoued** [comment]
I have same issue and i have tried adding asset() helper to every mix() call in nova blade resources,
N
![Screen Shot 2019-06-18 at 08 45 44 (2)](https://user-images.githubusercontent.com/15153313/59663019-0b32fb80-91a6-11e9-9a91-7c22b1d90620.png)
ow i'm getting 404 !!

**Comment by chinleung** [comment]
For anyone who has issue installing it in a subfolder, this is how I got it working for me:
https://gist.github.com/chinleung/2e9f6a9496ded8cd6fadc829b0030229

**Comment by Sndan** [comment]
is there any good solution for this issue ?

**Comment by klimov-paul** [comment]
You may use [illuminatech/override-build](https://github.com/illuminatech/override-build) to apply @chinleung's patch.

Assuming your domain is 'http://test.devel' and subfolder named 'subfolder, the configuration for it will be following:

```php
<?php
// file 'config/override-build.php'
return [
    'packages' => [
        'nova' => [
            'srcPath' => base_path('vendor/laravel/nova'),
            'buildPath' => base_path('vendor/laravel/nova'),
            'patches' => [
                'resources/js/util/axios.js' => [
                    '__class' => Illuminatech\OverrideBuild\Patches\Replace::class,
                    'replaces' => [
                        'axios.create()' => "axios.create({baseURL: 'http://test.devel/subfolder'})"
                    ],
                ],
                'resources/views/layout.blade.php' => [
                    '__class' => Illuminatech\OverrideBuild\Patches\Replace::class,
                    'replaces' => [
                        '"/nova-api/' => '"/subfolder/nova-api/',
                        "mix('app.css', 'vendor/nova')" => "asset(mix('app.css', 'vendor/nova'))",
                        "mix('manifest.js', 'vendor/nova')" => "asset(mix('manifest.js', 'vendor/nova'))",
                        "mix('vendor.js', 'vendor/nova')" => "asset(mix('vendor.js', 'vendor/nova'))",
                        "mix('app.js', 'vendor/nova')" => "asset(mix('app.js', 'vendor/nova'))",
                        '@json(Nova::jsonVariables(request()));' => "@json(Nova::jsonVariables(request()));\nwindow.config.base = '/subfolder' + window.config.base;"
                    ],
                ],
            ],
            'buildCommand' => [
                'mv webpack.mix.js.dist webpack.mix.js',
                'yarn install',
                'yarn run '.((env('APP_ENV') === 'production') ? 'prod' : 'dev'),
            ],
        ],
    ],
]
```

Rebuild command:

```
php artisan override-build nova
```

**Comment by klimov-paul** [comment]
In order to make it better without messing up 'vendor' directory, you may use separated directory for the JS build exporting results to 'public/vendor/nova'.
The config for this will be:

```php
<?php
// file 'config/override-build.php'
return [
    'packages' => [
        'nova' => [
           'srcPath' => base_path('vendor/laravel/nova'),
            'buildPath' => storage_path('build-override/nova'),
            'srcFiles' => [
                'resources',
                '.babelrc',
                'mix-manifest.json',
                'package.json',
                'tailwind.js',
                'webpack.mix.js.dist',
                'yarn.lock',
            ],
            'patches' => [
                'resources/js/util/axios.js' => [
                    '__class' => Illuminatech\OverrideBuild\Patches\Replace::class,
                    'replaces' => [
                        'axios.create()' => "axios.create({baseURL: 'http://test.devel/subfolder'})"
                    ],
                ],
                'webpack.mix.js.dist' => [
                    '__class' => Illuminatech\OverrideBuild\Patches\Replace::class,
                    'replaces' => [
                        ".copy('public', '../nova-app/public/vendor/nova')" => ".copy('public', '../../public/vendor/nova')",
                    ],
                ],
                'resources/views/layout.blade.php' => [
                    '__class' => Illuminatech\OverrideBuild\Patches\Replace::class,
                    'replaces' => [
                        '"/nova-api/' => '"/subfolder/nova-api/',
                        "mix('app.css', 'vendor/nova')" => "asset(mix('app.css', 'vendor/nova'))",
                        "mix('manifest.js', 'vendor/nova')" => "asset(mix('manifest.js', 'vendor/nova'))",
                        "mix('vendor.js', 'vendor/nova')" => "asset(mix('vendor.js', 'vendor/nova'))",
                        "mix('app.js', 'vendor/nova')" => "asset(mix('app.js', 'vendor/nova'))",
                        '@json(Nova::jsonVariables(request()));' => "@json(Nova::jsonVariables(request()));\nwindow.config.base = '/subfolder' + window.config.base;"
                    ],
                ],
            ],
            'buildCommand' => [
                'yarn install',
                'yarn run '.((env('APP_ENV') === 'production') ? 'prod' : 'dev'),
            ],
        ],
    ],
]
```

Rebuild command:

```
php artisan override-build nova
```

Once build is complete you should manually move layout file from 'storage/build-override/nova/resources/views/layout.blade.php' to 'resources/views/vendor/nova/layout.blade.php' using native Nova view override principle.

**Comment by tpetry** [comment]
I submitted a [simple patch](https://github.com/laravel/nova/pull/296) long time ago (you need to activate access to the repository within the nova buying application settings) but the developers decided to not include it. I attached the patch to this comment. I am applying this patch for a long time and it's working for every new version without any problems or conflicts (you need to rebuild the assets after patching). My patch has a few more lines changed compared to the changes by @klimov-paul because i tries to make the most simple fundamental changes so nova plugins work without any problems too.

[Attachment: nova-subfolder-support.patch.txt](https://github.com/laravel/nova-issues/files/3485191/nova-subfolder-support.patch.txt)

**Comment by jbrooksuk** [comment]
I appreciate that this is not going to be to everybody's liking, but I'm closing this issue. Reasons being:

1. Laravel is not meant to be installed from a sub-directory, so making this work would go against best practises and potentially introduce security issues that Laravel does not account for.
2. Supporting sub-directories would introduce more work for the core team, which is not something we want to do at this time.
3. If you wish to run Nova under a sub-directory, @tpetry has a patch that is available above and you do so at your own risk.

**Comment by klimov-paul** [comment]
@jbrooksuk, I afford to remind you, that we are not talking about free open-source project here.
Everyone here have payed money for the Laravel Nova access.

If this is your resolve, you should make a refund to every participant of this conversation, as, in fact, you have sold them product, which is broken, and you refuse to fix it up.

**Comment by davidhemphill** [comment]
It's not broken, you just don't like the outcome, which are based on already-established best practices for Laravel. Locking.
