### ISSUE TITLE
add{Model} doesn't work

### ISSUE THREAD

**Issue by mateusgalasso** [laravel/nova-issues#4713]
- Laravel Version: 9.24.0
- Nova Version: 4.12.14

I have two models 'Proposta' and 'Acao'
in **Acao**
```php
 /**
 * @return HasMany<Proposta>
 */
public function propostas(): HasMany
{
    return $this->hasMany(Proposta::class);
}
```
in **Proposta**
```php
public function acao(): BelongsTo
{
    return $this->belongsTo(Acao::class);
}
```

**in AcaoPolicy add{Model} doesn't work**
```php
public function addProposta(User $user, Acao $acao): bool
{
    if ($acao->status !== AcaoStatus::EM_EXECUCAO) {
        return false;
    }

    return $this->create(user: $user);
}
```
does not enter the addProposta function at all

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by crynobone** [comment]
There not enough information to debug the issue. Based on existing features/dusk tests everything is working as intended. Feel free to submit a bug report with full reproducing code for us to understand the issue.
