### ISSUE TITLE
BelongsTo field doest have min items in searchable

### ISSUE THREAD

**Issue by RenaatoSiilva** [laravel/nova-issues#4718]
- Laravel Version: 9.2
- Nova Version: 4.11.1
- PHP Version: 8.0.2
- Database Driver & Version:
- Operating System and Version: Windows 10
- Browser type and version: Chrome 104.0.5112.82

### Description:
Hello everyone, i was looking for searchable in relationships and i notice that don't have an "min" items option to populate list (https://nova.laravel.com/docs/4.0/resources/relationships.html#searchable-relations) , the select field show some items with search (https://nova.laravel.com/docs/4.0/resources/fields.html#searchable-select-fields).

### Detailed steps to reproduce the issue on a fresh Nova installation:
Create an Select field and a BelongsTo field and apply searchable function.

![belongsto searchable](https://user-images.githubusercontent.com/22757611/185641451-b40e7abe-ec37-4904-b8d7-d41e449abdff.png)
![select searchable](https://user-images.githubusercontent.com/22757611/185641459-511c62eb-02ec-4925-81ec-dc4a465301c6.png)

**Comment by crynobone** [comment]
Expected behaviour for BelongsTo field.
