### ISSUE TITLE
Lens Action fails when run against a row excluded by parent resource indexQuery

### ISSUE THREAD

**Issue by khl-vera** [laravel/nova-issues#4721]
- Laravel Version: 9.7
- Nova Version: 4.12.0
- PHP Version: 8.1.5
- Database Driver & Version:
- Operating System and Version: Ubuntu 20.04 LTS
- Browser type and version: Google Chrome v 104.0.5112.102 (64bit)

### Description:
I get this error when running an action on lense

> 'Sorry! You are not authorized to perform this action.'

when I add indexQuery to the parent resource that excludes rows shown by lens query

the action works when I remove indexQuery from parent resource 

### Detailed steps to reproduce the issue on a fresh Nova installation:

Resource:

```
class Project extends Resource
{
    public function lenses(NovaRequest $request) { return [
        Lenses\ArchivedProjects::make(),
    ]; }
    
    public static function indexQuery(NovaRequest $request, $query)
    {
        return $query->where('archived', false);
    }
}
```

Lense:

```
use App\Nova\Actions\UnarchiveProjectsAction;

class ArchivedProjects extends Lens
{
    public static function query(LensRequest $request, $query)
    {
        return $request->withOrdering($request->withFilters(
            $query->where('archived', true)
        ));
    }
    public function actions(NovaRequest $request) { return [
        UnarchiveProjectsAction::make()
            ->showInline()
            ->withoutConfirmation()
            ->canSee(fn(NovaRequest $request) => true)
            ->canRun(fn(NovaRequest $request) => true),
    ]; }
}
```

**Comment by crynobone** [comment]
Please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by khl-vera** [comment]
Thank you for your reply @crynobone
Unfortunately, I don't have time to create a new project with new resources, models, migrations, …
I reported this issue with snippets of code in order to notify the creators or Laravel nova about it.
As for me I already found a work around by not using a Lens and instead created a duplicate Nova Resource for the same model with a different indexQuery

**Comment by crynobone** [comment]
> I reported this issue with snippets of code in order to notify the creators or Laravel nova about it.

Sorry, unable to reproduce the issue. We can only fix a bug when we able to reproduce the exact issue
