### ISSUE TITLE
PHP 8 - Unsupported operand types: string - int

### ISSUE THREAD

**Issue by DeanWhitehouse** [laravel/nova-issues#4737]
- Laravel Version: 9.26.1
- Nova Version: 4.13.0
- PHP Version: 8.1.2
- Database Driver & Version: MySQL 8.0.29
- Operating System and Version: sail-8.1 (on OSX 12.5.1)
- Browser type and version: Chrome 104.0.5112.101

### Description:
When creating a new trend metric, and attempting to use one of the text keyed ranges (i.e. `TODAY` or `MTD`) I get the error `Unsupported operand types: string - int`.

This appears to be related to the PHP8 and the strictness that comes with types. I've located this back to line `562` in `/vendor/laravel/nova/src/Metrics/Trend.php`. For some reason `$range` here is the word still and not the actual value, maybe these special values have been removed...

### Detailed steps to reproduce the issue on a fresh Nova installation:
* Create a new trend metric with any model
* Select the `TODAY` range
* Error will occur

**Comment by crynobone** [comment]
Can you provide an example? AFAIK Trend metric only supports integer as key for range and you can use `countByHours()` or `countByMinutes()` with range  as `1 => __('Today'),`

**Comment by DeanWhitehouse** [comment]
> Can you provide an example? AFAIK Trend metric only supports integer as key for range and you can use `countByHours()` or `countByMinutes()` with range as `1 => __('Today'),`

@crynobone using the ranges defined here, the key word ones such as `MTD` do not work for when using a trend metric https://nova.laravel.com/docs/4.0/metrics/defining-metrics.html#value-ranges

**Comment by crynobone** [comment]
https://nova.laravel.com/docs/4.0/metrics/defining-metrics.html#value-ranges

That documentation only refers to `Value` metric and not `Trend` metric. See https://nova.laravel.com/docs/4.0/metrics/defining-metrics.html#trend-ranges
