### ISSUE TITLE
sortable not working with relationship model

### ISSUE THREAD

**Issue by dangvandiep** [laravel/nova-issues#474]
In **Character.php**
`
public function characterInfo()
{
        return $this->hasOne(CharacterInfo::class, 'RoleId', 'ID');
}
`

In **CharacterInfo.php**
`
public function character()
{
        return $this->belongsTo(Character::class, 'RoleId', 'ID');
}
`

In Nova Resource:
`
Number::make('KNB', 'characterInfo.Gold')->sortable()->displayUsing(function($knb) {
    return number_format($knb);
}),
`
it displayed but when i click on sort icon, i got an error:

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'characterInfo.Gold' in 'order clause' (SQL: select * from `Player` inner join `player_query_data` on `player_query_data`.`RoleId` = `Player`.`ID` order by `characterInfo`.`Gold` asc limit 26 offset 0)

**Comment by carnevalle** [comment]
#178

**Comment by davidhemphill** [comment]
Currently Nova doesn't support sorting on relationships.
