### ISSUE TITLE
Nova left menu bar is covered by main screen

### ISSUE THREAD

**Issue by cinemapub** [laravel/nova-issues#4746]
- Laravel Version: 9.26.1
- Nova Version: 4.11.0
- PHP Version: 8.1.9
- Database Driver & Version: -
- Operating System and Version: Windows 10
- Browser type and version: Chrom 104.0.5112.102
- Reproduction Repository: https://github.com/###/###

### Description:
For one project, I upgraded from Nova 4.7.0 to 4.13.0 in 1 go and suddenly the contents of the main screen become +- full width and they cover the menu column on the left. 

This is what the bug looks like:
![Nova 4.11](https://i.postimg.cc/X71P0zdH/nova-4-11-0.png)
https://postimg.cc/QH5mQS61

### Detailed steps to reproduce the issue on a fresh Nova installation:
I went back to Nova 4.7.0 (`composer require -W laravel/nova:4.7.0`) and the problem was fixed.
Then I started upgrading one version at a time (4.7 -> 4.8 ...)
The moment the bug pops up it when switching from 4.10 to 4.11. This is when the following related updates happen:
```
  - Downloading symfony/polyfill-intl-icu (v1.26.0)
  - Downloading laravel/nova (4.11.0)
  - Removing symfony/intl (v6.1.0)
  - Installing symfony/polyfill-intl-icu (v1.26.0): Extracting archive
  - Upgrading laravel/nova (4.10.0 => 4.11.0): Extracting archive
```

When I downgrade from 4.11 to version 4.10.0, the problem stays, but when I go back to 4.9.0, it disappears again. This is what it should look like:
![Nova 4.9](https://i.postimg.cc/7YZRdkGJ/nova-4-9-0.png)
https://postimg.cc/4njwHj1X

**Comment by mstaack** [comment]
Did you run artisan nova:publish?

**Comment by crynobone** [comment]
1. Ensure you have run `php artisan nova:publish`
2. If you publish `layout.blade.php`, please sync the changes from `resources/views/layout.blade.php`.
