### ISSUE TITLE
Resource Tool Order

### ISSUE THREAD

**Issue by RenaatoSiilva** [laravel/nova-issues#4757]
-Laravel Version: 9.2
-Nova Version: 4.11.1
-PHP Version: 8.0.2
-Database Driver & Version:
-Operating System and Version: Windows 10
-Browser type and version: Chrome 104.0.5112.82

### Description: 

Laravel nova doest respect order when resource tool exists.

### Detailed steps to reproduce the issue on a fresh Nova installation:  

Create a new resource tool, apply in a resource and create dependancy relations, the resource tool always stay in first place.

![image](https://user-images.githubusercontent.com/22757611/187193635-e5766a43-f2f2-4642-9f9d-85bdbb781d22.png)
![image](https://user-images.githubusercontent.com/22757611/187193700-d033bb0e-4921-4369-9cde-bb113edc0344.png)

**Comment by crynobone** [comment]
Already fixed in 4.12.0: https://nova.laravel.com/releases/4.12.0
