### ISSUE TITLE
4.13.0 Cannot make non static method Laravel\Nova\Dashboards\Main::uriKey() static in class App\Nova\Dashboards\Main

### ISSUE THREAD

**Issue by manuele89** [laravel/nova-issues#4758]
- Laravel Version: 9.19.00
- Nova Version: 4.13.0
- PHP Version: 8.0.21

### Description:
i want to customize url and label of main dashboard. For this, I followed the documentation at this url: "https://nova.laravel.com/docs/3.0/customization/dashboards.html#customizing-dashboards". But if I type this in `app/Nova/Dashboards/Main.php`

`public static function label()
{
    return 'TEST NAME';
}

public static function uriKey()
{
    return 'test-name';
}`

returns the following errors:

1. Cannot make non static method Laravel\Nova\Dashboards\Main::uriKey() static in class App\Nova\Dashboards\Main
2. Cannot make non static method Laravel\Nova\Dashboard::label() static in class App\Nova\Dashboards\Main

**Comment by crynobone** [comment]
The link you posted refer to Nova 3 documentation, you should refer to https://nova.laravel.com/docs/4.0/customization/dashboards.html#defining-dashboards
