### ISSUE TITLE
Problems with Nova and a Catch-all route on path '/{any}'

### ISSUE THREAD

**Issue by carnevalle** [laravel/nova-issues#476]
Hi!

I have an app where I have an SPA running on the root path. This is handled by added a catch all route at the end of my routes/web.php, like this:

`Route::get('/{any}', 'IndexController@index')->where('any', '.*');`

This route catches the Nova-routes and tries to render my SPA when hitting /nova

I fixed this by adding the following to my NovaServiceProvider
`
Event::listen(NovaServiceProviderRegistered::class, function () {
  Route::get('/{any}', 'App\Http\Controllers\IndexController@index')->where('any', '.*');
});
`

<img width="825" alt="skaermbillede 2018-09-07 kl 12 19 57" src="https://user-images.githubusercontent.com/54747/45213685-8622c980-b298-11e8-9a9c-d8fb62ff8b44.png">

I don't know if this could be fixed in some way or whether above solution should be added to the Nova documentation?

**Comment by davidhemphill** [comment]
When using catch-all routes, you have to use a more-restrictive regex to allow nova requests to go through:

`Route::get('/{any}')->where('any', '^(?!nova).*$');`

**Comment by cgarofalo** [comment]
I have the same issue except that I am using a route group. The above solution does not work. Any suggestions? (I have set the nova path in the config to use /admin instead of /nova)
```
Route::group(['prefix' => '{locale}', 'middleware' => ['locale']], function() {
	Route::get('{path}', ['as' => 'pages.show', 'uses' => 'PagesController@show'])->where(['path' => '^(?!admin).*$']);
});
```
Anyway to get routes to trigger before Nova's?

**Comment by tripex** [comment]
I have a problem with my wildcard route, could you see any errors?
Route::get('/{city}/{restaurant_name}-{id}', 'RestaurantController@show_menu')->where('any', '^(?!nova|backend.*$).*')->name('restaurant-menu');

**Comment by jcalosor** [comment]
Any update on this, mine is that the Nova path in the nova.php config works on my local, but on dev server with the same config for nginx it doesn't `'path' => '/admin',`

**Comment by ArmeniaH** [comment]
I am trying to implement

```Route::get('/{alias1?}/{alias2?}', function (Request $request, $alias1 = null, $alias2 = null) {
```...
```})->where('alias1', '^(?!nova).*?$');

But the problem is that in case I have ```example.com/aaa/bbb```, my $alias1 becomes ```aaa/bbb```
Anyone can point me hot to modify regexp to stop on first slash?

**Comment by bakerkretzmar** [comment]
@ArmeniaH I've been having the same problem. After scratching my head about this for most of today (not for the first time) I settled on `^(?!(admin|nova))(\w*)` for the regex. I'm pretty sure this will match any URI segment except "admin" or "nova", and stop at slashes. `\w` is actually pretty limiting, so if you need to support accented characters or dashes or something else you could use `[^\/\s]` instead, which should match anything except whitespace or a "/".

**Comment by fabiotnt** [comment]
Don't forget to include nova-api in where clause. 
`Route::get('/{any}')->where('any', '^(?!admin|nova-api).*$');`

**Comment by ArmeniaH** [comment]
I came up with
```
->where('alias1', '^(?!dashboard|nova).*?$');
```

**Comment by jpmaga** [comment]
Old issue, but, in case someone stumbles upon it like I just did, another solution I've used in the past is to wrap your routes like this:
```php
if (! Request::is('nova*')) {
    Route::get(/* ... */);
}
```

**Comment by srinathreddydudi** [comment]
In case if any one needs to a better solution, For laravel 5.6 or higher, The better way is to use the fallback routes for catch all.
https://laravel.com/docs/5.6/routing#fallback-routes

**Comment by mehruncodes** [comment]
@srinathreddydudi fallback route can't be used for this purpose unless I understood it incorrectly.

**Comment by mehruncodes** [comment]
@jpmaga this one failed as well since the included routes inside that condition don't get catches when we trying to cache our routes.

**Comment by ArroWsGM** [comment]
Recently we have some trouble with @davidhemphill solution when our static page slug begins with `nova` and eventually I end up with this workaround:
```php
$nova = trim(\Laravel\Nova\Nova::path(), '/');
Route::get('/{page}', 'PageController@show')->where('page', "^(?!($nova$|$nova\\/|nova-(api|vendor)\\/)).*$")->name('page.show');
```

**Comment by l00rik** [comment]
> Hi!
> 
> I have an app where I have an SPA running on the root path. This is handled by added a catch all route at the end of my routes/web.php, like this:
> 
> `Route::get('/{any}', 'IndexController@index')->where('any', '.*');`
> 
> This route catches the Nova-routes and tries to render my SPA when hitting /nova
> 
> I fixed this by adding the following to my NovaServiceProvider
> `Event::listen(NovaServiceProviderRegistered::class, function () { Route::get('/{any}', 'App\Http\Controllers\IndexController@index')->where('any', '.*'); });`
> 
> <img alt="skaermbillede 2018-09-07 kl 12 19 57" width="825" src="https://user-images.githubusercontent.com/54747/45213685-8622c980-b298-11e8-9a9c-d8fb62ff8b44.png">
> 
> I don't know if this could be fixed in some way or whether above solution should be added to the Nova documentation?

Can u help me , I got the same problem

**Comment by SebastianBotez** [comment]
> Don't forget to include nova-api in where clause.
> `Route::get('/{any}')->where('any', '^(?!admin|nova-api).*$');`

This is the right answer. Thank you
