### ISSUE TITLE
whereHas not working from indexQuery

### ISSUE THREAD

**Issue by kjoedion** [laravel/nova-issues#4763]
- Laravel Version: 9
- Nova Version: 4
- PHP Version: 8
- Database Driver & Version: mysql
- Operating System and Version: mac
- Browser type and version: chrome

### Description:

I am trying to do a custom relationship search in my `indexQuery`. I know that I can use searchable relations, but I want to add more complex searching capabilities later (such as whereBetween and whereIn on the relationship)

Here is my indexQuery code which does not work:

```php
    public static function indexQuery(NovaRequest $request, $query)
    {
        $query
            ->withCount('castingCalls', 'castingCallsRegistered', 'castingCallsAwaitingConfirm', 'castingCallsConfirmed')
            ->where('role', 'Talent');

        if ($request->search) {
            $query->whereHas('talentFieldValues', function (Builder $query) use ($request) {
                $query->where('value', $request->search);
            });
        }

        return $query;
    }
```

It does not seem to be searching the relationship `talentFieldValues` `value` column properly.

However, I created a command which does a direct query on the model, and it works perfectly:

```php
        $talent = User::query()
            ->withCount('castingCalls', 'castingCallsRegistered', 'castingCallsAwaitingConfirm', 'castingCallsConfirmed')
            ->where('role', 'Talent')
            ->whereHas('talentFieldValues', function ($query) {
                $query->where('value', 'Male');
            })
            ->get();

        print_r($talent->toArray());
```

This code returns the expected results. Why isn't it working on indexQuery?

**Comment by crynobone** [comment]
Create custom invokable class for relationship search and add that class instance to the searchableColumns method.

**Comment by kjoedion** [comment]
nevermind it magically started working

**Comment by kjoedion** [comment]
> Create custom invokable class for relationship search and add that class instance to the searchableColumns method.

Your solution is much better than what I was trying. Thank you.

**Comment by ekazda** [comment]
> Create custom invokable class for relationship search

@crynobone are you able to elaborate on this??
