### ISSUE TITLE
Date field broken on nova 2.12.0

### ISSUE THREAD

**Issue by cweiske** [laravel/nova-issues#4767]
- Laravel Version: v6.20.9
- Nova Version: 2.12.0
- PHP Version: 7.4.30
- Database Driver & Version: mysqlnd 7.4.30
- Operating System and Version: Ubuntu 20.04 LTS
- Browser type and version: Firefox 103.0

### Description:
When creating a resource in the browser and selecting the date in a nova `Date` field, a javascript error occurs:
```
[Vue warn]: Error in v-on handler: "TypeError: event.target is undefined"

found in

---> <DateTimePicker> at resources/js/components/DateTimePicker.vue
       <DefaultField> at resources/js/components/Form/DefaultField.vue
         <FormDate> at resources/js/components/Form/DateField.vue
           <Card> at resources/js/components/Card.vue
             <FormPanel> at resources/js/components/Form/Panel.vue
               <LoadingView> at resources/js/components/LoadingView.vue
                 <CreateForm> at resources/js/components/CreateForm.vue
                   <Create> at resources/js/views/Create.vue
                     <Root>
```

Date fields are unusable in Nova 2.12.0, so we have to fall back to using DateTime fields as workaround.

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Create new resource
2. Add a `Laravel\Nova\Fields\Date` field to the resource
3. Open Nova in the browser, create the new resource instance
4. Click on the date field and select a date
5. Error occurs

----
This was reported at the end of #2853, but that issue was already closed at the time.

**Comment by crynobone** [comment]
This should be fixed in latest Nova 3. Upgrade to Nova 3 or use Nova 4.

**Comment by cweiske** [comment]
I cannot upgrade to Nova 3 or later because I'm limited to Laravel 6.

**Comment by crynobone** [comment]
> I cannot upgrade to Nova 3 or later because I'm limited to Laravel 6.

We no longer releasing any bugfixes for Nova 2. You need to upgrade if you want to fix this issue.
