### ISSUE TITLE
Deleting a file with hideFromDetail returns 404

### ISSUE THREAD

**Issue by alhoqbani** [laravel/nova-issues#477]
When a file/image field is hidden from details page, it cannot be deleted. The request returns 404. 

This is because `FieldDestroyController` looks for the file field in `detailFields` only. 

```
        $field = $resource->detailFields($request)
                    ->whereInstanceOf(File::class)
                    ->findFieldByAttribute($request->field, function () {
                        abort(404);
                    });
```

Is this behaviour on purpose?  I want to show the file field in the form only, is this possible?

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
