### ISSUE TITLE
Does not show pivot fields on update

### ISSUE THREAD

**Issue by mateusgalasso** [laravel/nova-issues#4777]
- Laravel Version:  9.26.1
- Nova Version: 4.13
- PHP Version: 8.1

### Description:
BelongsToMany field is not showing in relationship update

Models/Proposta
```php
public function cidades(): BelongsToMany
    {
        return $this->belongsToMany(Cidade::class)
            ->withPivot(['quantidade_pessoas_previstas', 'quantidade_pessoas_atendidas']);
    }
```

Nova Fields
```php
BelongsToMany::make('Cidades', 'cidades', Cidade::class)
  ->searchable()
  ->fields(function ($request, $cidade) {
      return [
          Number::make('Quantidade de pessoas', 'quantidade_pessoas_previstas'),
      ];
  }),
```

**Comment by mateusgalasso** [comment]
I found out what the problem is.
My Nova\Resource is using the fieldsForUpdate method
But this method doesn't have the BelongsToMany relationship
When I put the relationship inside the fieldsForUpdate it worked

**Comment by crynobone** [comment]
That should be expected.
