### ISSUE TITLE
Missing columns in csv export. Cannot export datetime fields.

### ISSUE THREAD

**Issue by ianbrucey** [laravel/nova-issues#4778]
This is not so much an issue as it is a heads up, since I couldn't find a solution anywhere.
I was trying to use the CSV export feature but I noticed that the columns with the data type of "datetime" would not show up.

To resolve this I had to define an [Accessor](https://laravel.com/docs/9.x/eloquent-mutators#defining-an-accessor) on the model for that particular field. So for ex:

`
protected function createdAt(): Attribute
    {
        return Attribute::make(
            get: fn ($value) => (Carbon::parse($value)->format("Y-m-d h:i:s")),
        );
    }
`

It appears that since the field was effectively cast to a string, the export feature was able to parse it and my fields showed up. Hope this helps

**Comment by ianbrucey** [comment]
Resolved

**Comment by juse-less** [comment]
I can't for the life of me remember where I've read it, but the data that will be exported requires more basic scalar data types.
I.e., an integer, float, or string.
If the value is an object, the column for that row will be blank. If all rows for the same column are blank for this reason, I've also seen the whole column (including the title) be missing in the file.

With that in mind - if an attribute is set to be cast to any variation of date or datetime, the value will be a Carbon or CarbonImmutable, and not a string.
So you need to cast it to a string (or integer/float, depending on your values needs).

If I find where I read this, I can link to it in here.
Pretty sure it was either in the code and/or DocBlock for the export Action, or somewhere in the documentation.
I couldn't find it right away in the [CSV export section](https://nova.laravel.com/docs/4.0/resources/#csv-export) of the documentation right now, though.
