### ISSUE TITLE
Support for non-integer primary keys on models

### ISSUE THREAD

**Issue by m2de** [laravel/nova-issues#478]
There are a number of open issues relating to this and I looked into it a bit further today. I'm unsure how to best report this as the Nova repo is closed source. 

Changing the primaryKey type on a model causes all sort of issues.

```php
protected $primaryKey = 'slug';
protected $keyType = 'string';
public $incrementing = false;
```

This will break my default Nova resource, so I updated the resource and removed the default `ID::make()->sortable(),` entry. I can now view resources again. However saving them will throw an error about the actionable_id being the incorrect type.

This can be resolved by changing the `actionable_id`, `target_id` and `model_id` in the `action_events` table to `varchar(255)`.

The next problem is that Nova will hide the primary key field on create and update forms. My solution here would be to edit `nova/src/ResolvesFields.php` line 96 and 139 to only hide the key columns if it is auto incrementing.

```php
($field->attribute === $this->resource->getKeyName() && $this->resource->getIncrementing())
```

The last issue (as far as I can tell) which I have not had time to find a solution for is that after updating a resource, it tries to redirect back to the original primaryKey value, not the newly updated primaryKey, resulting in a 404 error. I imagine @taylorotwell / @themsaid / @davidhemphill would find it much easier to resolve that one, given their in-depth knowledge of the Nova workings.

Would love to get some idea of whether this might be addresses/fixed in the near future or if I have to implement a workaround in my app to always use the default primary key type? 

Many thanks, any input would be much appreciated.

Related issues #141 #189 #334 #404.

**Comment by CraigHarley** [comment]
I'm using UUID's and I've not had any issue with them after adding `public $incrementing = false;`. Migrations look like this: `$table->uuid('id')->primary();`.

**Comment by m2de** [comment]
Thanks for your input @CraigHarley . So looking at why your solution didn't cause any problems I worked out that I should using the `getRouteKeyName` in my model, instead of changing the `primaryKey` column. This solves my front-end issues without impacting Nova. Thanks for that. Although technically, the issue still remains that if you set your primary key to type string, it will break nova.

I am now using standard ID as primary key and use this to make my routes use the slug instead of the id:

```php
public function getRouteKeyName()
{
    return 'slug';
}
```

**Comment by CraigHarley** [comment]
Wait, are you using your slug as your primary key and allowing it to be edited in Nova?

That's a bad idea for a few reasons, I'd recommend using a primary key you don't expect to change.

**Comment by m2de** [comment]
Correct, that is what I was doing, but purely because I wasn't aware of the `getRouteKeyName` method. From the official Laravel documentation it would appear that you are supposed to change the `$primaryKey` variable. I will try and open a PR to the docs to try and make this more obvious to hopefully help others in similar situations.

**Comment by webhealer** [comment]
I have same problem when using Mongodb BSON _id field as a primary key for Nova resources.  If there is no solution for now, i have to create my own resource tool and make a custom datatable, forms etc.

**Comment by davidhemphill** [comment]
@m2de I just changed `ResolvesFields` to allow one to use a normal `Text` field for editing their ID:

```php
Text::make('Id')
```

I also fixed the issues preventing Nova from navigating to the correct URL if the ID has changed.

I'll have to take a look at the Action log stuff next week and see what can be done there.

**Comment by christopherarter** [comment]
@davidhemphill 

Thanks a ton! I'm assuming these fixes will ship in v1.2.1 soon?

**Comment by guru-tracktik** [comment]
> @davidhemphill
> 
> Thanks a ton! I'm assuming these fixes will ship in v1.2.1 soon?

This will be awesome @davidhemphill

**Comment by iulianbilcu** [comment]
About the 404 redirect:

in the file Update.vue - method 'updateResource' on the redirect, the last parameter is "response.data.id" .

For some reasons, I don't have a column named id but uuid
A quick fix was to append to model an `id` attribute with the uuid value.

**Comment by ragingdave** [comment]
@davidhemphill Was there any movement on enabling action logs to support or at least being able to turn off the action log for non-integer primary keys? Currently you can't do anything in nova on that kind of resource as the ActionEvent triggers no matter if the resource/model is actionable or not.

**Comment by yurii-github** [comment]
got this issue today with action log.. i guess i'm forced to keep integer shadow key for now

**Comment by davidhemphill** [comment]
After thinking this through with @taylorotwell, we've decided to not support this inside of Nova. The underlying Models used by Resources need to have auto-incrementing `id` column. You might be able to work around this by exporting Nova's migrations and changing the key columns to `string` types, but there be dragons.

**Comment by marijoo** [comment]
If anyone else is having issues with this, I think I found a fix.

In your `NovaServiceProvider` add the following to disable the *Action Log* for a model with non-numeric IDs:

```php
use Laravel\Nova\Actions\ActionEvent;

...

public function boot()
{
   parent::boot();

    ActionEvent::saving(function ($actionEvent) {
        if (
            $actionEvent->model_type === "App\Models\OauthAccessToken" 
            && in_array($actionEvent->name, ['Create', 'Update'])
        ) {
            return false;
        }
    });
}
```

**Comment by BenjaminBrandtner** [comment]
@marijoo That's a good workaround for creating and editing. Sadly, deleting a resource still shows an SQL error (even though the actual deletion works), see [this answer](https://github.com/laravel/nova-issues/issues/141#issuecomment-500873615) as to why it's probably unpreventable (as of now).

**Comment by jhm-ciberman** [comment]
Any (real) update on this? I have a Analytics Event tracking system on production with gigs of user events using UUIDs as the primary key, and when deleting any model Nova gives an SQL error. 

I'm not using `ActionEvents` for that resource, I only want to delete it. Any non hacky way to accomplish that? @davidhemphill
