### ISSUE TITLE
Custom CSS not being applied to login page.

### ISSUE THREAD

**Issue by kjoedion** [laravel/nova-issues#4789]
- Laravel Version: 9
- Nova Version: 4
- PHP Version: 8
- Database Driver & Version: mysql
- Operating System and Version: macos monterey
- Browser type and version: chrome latest

### Description:

I have the following `black.css` file:

```css
:root {
    --colors-gray-50: 250, 250, 250;
    --colors-gray-100: 245, 245, 245;
    --colors-gray-200: 229, 229, 229;
    --colors-gray-300: 212, 212, 212;
    --colors-gray-400: 163, 163, 163;
    --colors-gray-500: 115, 115, 115;
    --colors-gray-600: 82, 82, 82;
    --colors-gray-700: 64, 64, 64;
    --colors-gray-800: 38, 38, 38;
    --colors-gray-900: 24, 24, 24;
}
```

I have applied this style in my `NovaServiceProvider`:

```php
Nova::style('black', resource_path('css/black.css'));
```

It works great after logging in, but this style is not being applied to the login page.

**Comment by kjoedion** [comment]
I've also tried doing it this way in a service provider `boot` method and the same thing happens:

```php
        Event::listen(NovaServiceProviderRegistered::class, function ($event) {
            Nova::style('black', resource_path('css/black.css'));
        });
```

**Comment by kjoedion** [comment]
I figured out another way using `meta.blade.php`

**Comment by smartens80** [comment]
@kjoedion can you share your solution / changes to the meta.blade.php file us?

**Comment by kjoedion** [comment]
> @kjoedion can you share your solution / changes to the meta.blade.php file us?

I created the file `resources/views/vendor/nova/partials/meta.blade.php` with this content:

```
<link rel="stylesheet" href="{{ asset('css/black.css') }}">
```

Now that stylesheet is included in all pages of my Nova app, including the login page.

This allowed me to change all of the grays to Tailwind's "neutral" tone by adding this to `black.css`:

```css
:root {
    --colors-gray-50: 250, 250, 250 !important;
    --colors-gray-100: 245, 245, 245 !important;
    --colors-gray-200: 229, 229, 229 !important;
    --colors-gray-300: 212, 212, 212 !important;
    --colors-gray-400: 163, 163, 163 !important;
    --colors-gray-500: 115, 115, 115 !important;
    --colors-gray-600: 82, 82, 82 !important;
    --colors-gray-700: 64, 64, 64 !important;
    --colors-gray-800: 38, 38, 38 !important;
    --colors-gray-900: 24, 24, 24 !important;
}
```
