### ISSUE TITLE
[Feature request] BelongsTo can displayUsingLabels

### ISSUE THREAD

**Issue by Giactan** [laravel/nova-issues#479]
- Property Resource with fields: id, name
- Apartment Resource with fields: id, name, property_id

`BelongsTo::make(__('Property'),'properties',Property::class),`

It will better if Apartment screen can show property's name field instead id field.

<img width="495" alt="screen shot 2018-09-07 at 8 45 10 pm" src="https://user-images.githubusercontent.com/31847606/45222493-f48a7a80-b2de-11e8-8f4f-e6bdb2dc31b3.png">

<img width="439" alt="screen shot 2018-09-07 at 8 44 33 pm" src="https://user-images.githubusercontent.com/31847606/45222458-d9b80600-b2de-11e8-8b6a-2a1958026ebd.png">

**Comment by abordage** [comment]
Set `public static $title = 'name';` in Property.php
