### ISSUE TITLE
No way to clear a nullable date field in Safari

### ISSUE THREAD

**Issue by Synchro** [laravel/nova-issues#4793]
- Laravel Version: 8.83.23
- Nova Version: 4.13
- PHP Version: 8.0.23
- Operating System and Version: macOS 12.6
- Browser type and version: Safari 16

I have republished resources and cleared views.

### Description:
When I have a nullable `Date` field, there is no way to clear it.

```php
            Date::make('Service end')
                ->nullable()
                ->default(null),
```
results in:

![image](https://user-images.githubusercontent.com/81561/189838590-cb3f1f3c-79df-4da1-9ec1-a716efc6f4cf.png)

If I delete each of the date components in the field, they turn grey (as I have done in the first of these):

![image](https://user-images.githubusercontent.com/81561/189839039-d47a0181-9c5e-4a9d-80c2-46e15e817857.png)

but on saving it reverts to its original value.

The database field is nullable and defaults to null.

I have seen #2606 that supposedly fixed this, but it's not fixed for me. Also the `help()` workaround doesn't work for me as it fails to find its target – I guess the structure has changed since then. It looks like as implemented this is subject to a Safari limitation, however, I think it would be better to use an `x` field suffix button as is used on other field types to provide a consistent UX.

Chrome does show a "clear" option:

![image](https://user-images.githubusercontent.com/81561/189840037-6d956156-d6b1-412c-a5d9-a8e41a939530.png)

however, it clears it to `dd/mm/yyyy` rather than an empty field or `–`, which is unexpected.

**Comment by crynobone** [comment]
All the pickers are browser control without any customisation options.

**Comment by Synchro** [comment]
Uh, yes, that's why I suggested a Nova workaround, that's consistent with what Nova does for other field types, that will work independent of browser implementations. Meanwhile it renders Nova partly unusable on some browsers.

**Comment by crynobone** [comment]
No plans for this, Nova 4 attempts to reduce 3rd party packages as much as possible. You can create custom field for date picker to get more customisation
