### ISSUE TITLE
Oversize submissions are not reported in a useful way

### ISSUE THREAD

**Issue by Synchro** [laravel/nova-issues#4794]
- Laravel Version: 8.83.23
- Nova Version: 4.13
- PHP Version: 8.0.23
- Operating System and Version: macOS 12.6
- Browser type and version: Safari 16

### Description:
If you try to upload an image that is too large for the server's config, the way it is reported is not helpful:

![image](https://user-images.githubusercontent.com/81561/189845503-a42722da-6aa1-4da7-a196-d13116fab6af.png)

> There was a problem submitting the form. ""

Looking in the browser's dev console, it shows a 413 error from a URL like `https://example.com/nova-api/locations/82?viaResource=&viaResourceId=&viaRelationship=&editing=true&editMode=update`. 413 is "Entity too large", which makes sense, but it doesn't actually say that in the console so it's not immediately obvious what the problem is for developers, let alone end users.

**Comment by davidhemphill** [comment]
Hi, I wasn't able to replicate the issue on my end. If you could reproduce this issue in a fresh Nova installation and update your issue to include the reproduction repository, that would help us diagnose the issue further. Thanks!

<img width="552" alt="CleanShot 2022-09-16 at 11 34 41@2x" src="https://user-images.githubusercontent.com/58970/190687161-6018741b-826b-4d03-a384-a63fd9973937.png">

**Comment by Synchro** [comment]
Oh, that's interesting, thanks for looking. Suggests it might be a translation issue and not detection of the oversize request. I'll see if I can make a clean repro example.
