### ISSUE TITLE
Dead end after adding/updating related resource

### ISSUE THREAD

**Issue by cotton9** [laravel/nova-issues#48]
v1.0.5 - After adding/updating a related resource, it displays the detail view of the resource with no way to return to the original parent resource's detail view.  This makes it very difficult to create/edit multiple related resources

Example: 
![image](https://user-images.githubusercontent.com/5459717/44538885-9e0f2080-a6d0-11e8-95ef-1a15018d3ce9.png)

Starting with a Post details view...

1. "Create Comment" is clicked
2. The form is filled out and the create/update view's "Create Comment" button is clicked
3. The detail view of the new comment is displayed ... now what?

Seems like it's important to be able to get back to the view that originated the update/creation request.

**Comment by vyuldashev** [comment]
There’s are two buttons in create form. Click on “Create & Add Another".

**Comment by disitec** [comment]
+1 to this. Please consider reopening

**Comment by taylorotwell** [comment]
If you create a Comment, doesn't it have a BelongsTo('Post') field? Click the link to go back to the Post you were working with.

**Comment by cotton9** [comment]
Ahh... I missed adding the relationship field to the Nova resource.  That definitely helps.  Thanks!

**Comment by erikrorstrom** [comment]
Could it possible to have the option to use the same popup that you use on the pivot fields when attaching a resource? So that you don't have to leave the "post" in this example, but stay on that view? 

IMO that makes more sense when the related resource isn't a "primary" resource, but rather a meta table of the main one.

**Comment by davidhemphill** [comment]
https://github.com/laravel/nova-issues/issues/204#issuecomment-422952566

**Comment by josephxwf** [comment]
> If you create a Comment, doesn't it have a BelongsTo('Post') field? Click the link to go back to the Post you were working with.

Really need back button on each page!!!

**Comment by dillingham** [comment]
@josephxwf stop using exclaimation like that, no one likes being digitally yelled at!!!!! 

And every page has a back button, it’s in the browser lol

**Comment by h-zone** [comment]
The Nova creators seem to know nothing about UX, and forgot that works with Nova will be Managers, who nothing knows about programmers feints ears
