### ISSUE TITLE
BelongsTo field label is being computed instead of using the resource singularLabel method

### ISSUE THREAD

**Issue by disitec** [laravel/nova-issues#480]
Relation name is being singularized instead of using the resource singularLabel method. See attached screenshots.

Although I am redeclaring this methods. Label is still sowing as a computation.

```php
/**
     * Get the displayble label of the resource.
     *
     * @return string
     */
    public static function label()
    {
        return 'Clientes';
    }

    /**
     * Get the displayble singular label of the resource.
     *
     * @return string
     */
    public static function singularLabel()
    {
        return 'Cliente';
    }
```

![image](https://user-images.githubusercontent.com/12644599/44605150-8f1b9180-a7e8-11e8-91e0-70b9450e2021.png)

![image](https://user-images.githubusercontent.com/12644599/44605184-a78bac00-a7e8-11e8-8f2b-a803102f3edb.png)

![image](https://user-images.githubusercontent.com/12644599/44605204-ba05e580-a7e8-11e8-902f-1ee21d20bed5.png)

![image](https://user-images.githubusercontent.com/12644599/44605503-e40bd780-a7e9-11e8-9351-aaf34042cbe4.png)

**Comment by disitec** [comment]
@taylorotwell is this fixed?

**Comment by robmpreston** [comment]
@taylorotwell Just confirmed this is not fixed on 1.0.14

**Comment by rjpounder** [comment]
Have you tried this;

Nova/User.php@fields?:
`HasMany::make('Customers', 'customers', Customer::class)`

Then in Nova/Customer.php;

`public static function label()
{
    return __('Customers');
}

public static function singularLabel()
{
    return __('Customer');
}`

**Comment by disitec** [comment]
@taylorotwell this is fixed in details label but still happen in index and select placeholder.


![](https://user-images.githubusercontent.com/12644599/44605503-e40bd780-a7e9-11e8-9351-aaf34042cbe4.png)


![](https://user-images.githubusercontent.com/12644599/44605204-ba05e580-a7e8-11e8-902f-1ee21d20bed5.png)

**Comment by cannect** [comment]
+1 can this issue be opened again?
