### ISSUE TITLE
Nova does not seem to work with multiple databases, changed on runtime

### ISSUE THREAD

**Issue by egrowthnordic** [laravel/nova-issues#481]
**Background**
Two databases db1 and db2, each having table called settings. The corresponding Laravel model is App\Setting. The model has a static public function called setDatabase. This function only sets the parent::on to correct database connection, let's call them mysql1 and mysql2.

In a normalLaravel controller, I can do like this and it will automatically work with the correct database/connection:

$recordsCount = \App\Setting::setDatabase($correctConnectionName)->count()

With Nova, I have created and registered a filter where the apply method returns a $query that actually has the correct connection. Nova doesn't use the custom connection in the query but seems to override it later. 

In the apply method of the filter:
$recordsCount = \App\Setting::setDatabase($correctConnectionName)->count();
The above works fine. Depending on the connection name, it will use different database. 

But when I return only the query (not the count) from the method, it does not work, since it takes the default connection from the configuration and not the one I set during runtime in setDatabase:

return \App\Setting::setDatabase($correctConnectionName);

My hypothesis is that Nova overrides the connection/database name later after the filter has returned the query.

**Comment by davidhemphill** [comment]
Closing since this is a really weird edge case and Nova isn't really designed for stuff like this.
