### ISSUE TITLE
displayUsingLabels() not working in Detail view

### ISSUE THREAD

**Issue by iamoat** [laravel/nova-issues#4812]
- Laravel Version: 8.83.23
- Nova Version: 4.14.3
- PHP Version: 8.0.19
- Database Driver & Version: MySQL 5.7.39
- Operating System and Version: Ubuntu 20.04
- Browser type and version: Chrome 105.0.5195.102
- Reproduction Repository: https://github.com/###/###

### Description:

displayUsingLabels() not working in Detail view.

Instead, it displays the actual value in DB. However, Index and Update views are Ok.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Define a select field in a Nova resource 

```php
return [
 Select::make('Type')->options([
     'individual' => __('Individual'),
     'corporate' => __('Corporate')
 ])
    ->searchable()
    ->displayUsingLabels()
];
```

<img width="845" alt="image" src="https://user-images.githubusercontent.com/1286835/190645741-ba2e9d41-2378-4e7a-b6b1-6a3659727ec9.png">

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/1286835/190645799-a99004ae-0f05-46ef-b08b-4d39f16a8073.png">

<img width="1740" alt="image" src="https://user-images.githubusercontent.com/1286835/190645857-601ecb6b-3fe3-48c5-9ca7-ccf3b472e56a.png">

**Comment by davidhemphill** [comment]
Hi, I wasn't able to replicate the issue on my end. If you could reproduce this issue in a fresh Nova installation and update your issue to include the reproduction repository, that would help us diagnose the issue further. Thanks!

**Comment by iamoat** [comment]
Tried fresh nova install. The issue doesn't exist. It might caused from other package conflicts. 

We can close this case.

**Comment by scramatte** [comment]
Hi,

I've got exactly same issue here @iamoat,  do you use some package for localization such spattie transtable?

Regards

**Comment by datashaman** [comment]
In my case, it's because I define my options in a `dependsOn()` call.
But it seems the `dependsOn()` callback is not called for `Select` fields on detail pages. 😢
