### ISSUE TITLE
Code field with Json option enabled is not shown at first appearance when editing a resource

### ISSUE THREAD

**Issue by onemustcode** [laravel/nova-issues#4820]
- Laravel Version: 9.30.1
- Nova Version: 4.13.0
- PHP Version: 8.1.7
- Database Driver & Version: MySQL 8.30.0
- Operating System and Version: Ubuntu 20.04.4 LTS
- Browser type and version: Chrome 105.0.5195.102 (Official Build) (arm64)

### Description:
When having a **Code** field with the **JSON** option enabled the Code editor is not shown at first appearance when editing an existing resource.

https://user-images.githubusercontent.com/25415479/191183326-5ac644ba-23a0-4bc3-a344-5ece6647a055.mov

### Detailed steps to reproduce the issue on a fresh Nova installation:
Create a Nova resource and add the following Select field;

```php
Select::make('Type', 'type')->options([
    'string' => 'String',
    'int' => 'Getal',
    'money' => 'Bedrag',
    'float' => 'Decimaal',
    'json' => 'Json',
    'bool' => 'Ja/Nee',
    'text' => 'Tekst',
    'key-value' => 'Key/Value',
])
```

Then add a Code field that depends on the selected type from the Select field;

```php
Code::make('Waarde', 'value_json')
    ->dependsOn(['type'], function (Code $field, NovaRequest $request, FormData $formData) {
        if ($formData->type === 'json') {
            $field->show();
        }
    })
    ->json()
    ->onlyOnForms()
    ->hide(),
```

**Comment by crynobone** [comment]
Unable to reproduce on a fresh Nova installation, see https://github.com/nova-issues/issue-4820/commit/60d236fa80eb03409b5bfa82057de2fed4c0d209
