### ISSUE TITLE
policies do not work as expected when depending on attributes of the model beeing updated

### ISSUE THREAD

**Issue by pehbehbeh** [laravel/nova-issues#483]
It seems we found a critical bug, where model policies do not work as expected. 

We have a `budget` field on our Resource:

```
Text::make('Budget')
    ->rules('required', 'integer')
    ->canSeeWhen('editBudget', $this)
```
As you can see there are validation rules and the field is only visible/editable for users with a successful `editBudget` policy. The policy looks like this:

```
public function editBudget(User $user, Company $company): bool
{
    return $user->company->is($company->leasingCompany);
}
```

This works fine for displaying the field to the correct users. But when updating the field the `editBudget` policy gets checked twice: once with an empty `$company` model and once with the actual model beeing updated after that. So the first check to `editBudget` always returns `false` because of the empty model.

I think the first check happens to be an evaluation of the fields to validate because Nova tries to save the unvalidated field to the database. Obviously this fails on dirty input (for example with chars in an integer field):

```
[...] Incorrect integer value: 'example' for column 'budget' at row 1 (SQL: update `companies` set `budget` = example, `updated_at` = [...]
```

Side note: When reversing the above `is()` comparison to `$company->leasingCompany->is($user->company)` you get a `Call on member function is() on null` because of the first check with an empty `$company` model.

**Comment by pehbehbeh** [comment]
So after quite some time of debugging I found a solution to fix this problem which is rather simple.

 The `rulesForUpdate` method in the  `Laravel\Nova\PerformsValidation` trait needs some tiny modification.

The current implementation for reference:

```
public static function rulesForUpdate(NovaRequest $request)
    {
        return static::formatRules($request, (new static(static::newModel()))
            ->updateFields($request)
            ->mapWithKeys(function ($field) use ($request) {
                return $field->getUpdateRules($request);
            })->all());
    }
```

Because of the `(new static(static::newModel())` any policy method during an update request is checked with an newly instantiated (empty) model. Therefore your policy methods fail, if you rely on model attributes (see example above).

You can fix this problem by using the actual model of the update request by replacing `(new static(static::newModel()))` with `($request->findResourceOrFail())`. So the method looks like this:

```
    public static function rulesForUpdate(NovaRequest $request)
    {
        return static::formatRules($request, ($request->findResourceOrFail())
            ->updateFields($request)
            ->mapWithKeys(function ($field) use ($request) {
                return $field->getUpdateRules($request);
            })->all());
    }
```

With this fix the policies are working as expected. We changed this in our base Resource class but it would be great to see this as a fix in Nova core.

*(This probably also applies to the `updateRulesFor` method.)*

**Comment by dangthang7100** [comment]
I wonder why this issue still not fixed. I have same problem when using method `canSee` and `canSeeWhen` and combine with `rules`. Resource is display right but always got error when update it when the rules set to required.

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
