### ISSUE TITLE
searchable closure not working

### ISSUE THREAD

**Issue by mateusgalasso** [laravel/nova-issues#4832]
As in the documentation example
```php
BelongsTo::make('User')->searchable(function ($request) {
     return false;
}),
```
no matter what it returns, it is always showing the field as searchable, it will only work if I put boolean in the method, like this:

`BelongsTo::make('User')->searchable(false),`

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)
