### ISSUE TITLE
Transparent buttons issue

### ISSUE THREAD

**Issue by kitro** [laravel/nova-issues#4838]
- Laravel Version: 9.31.0
- Nova Version: 4.15.0
- PHP Version: 8.1
- Database Driver & Version:
- Operating System and Version:  docker
- Browser type and version: desktop.chrome (Version 105.0.5195.125 (Official Build) (64-bit))

### Description:
Some buttons are transprants, I tried to update the Nova assets with `--force` but still the issue occurred. Some issues mentioned in https://github.com/laravel/nova-issues/issues/4394 are still triggered in the version mentioned above.

I tried to clear all application cache and browser cache.

The `brand.colors[]` config in `nova.php` is commented like the default nova.php config.

![image](https://user-images.githubusercontent.com/5256921/191934840-2f1f1b6b-dd68-4cb8-b0ca-8aad337ed3cf.png)
![image](https://user-images.githubusercontent.com/5256921/191934899-a82770ef-1ad9-4813-accf-c1fe7b02724b.png)

But on **hovering** it shows the bg color

![image](https://user-images.githubusercontent.com/5256921/191935758-ce4b0b10-f8c0-4d73-a175-7a851f2f3bbf.png)

![image](https://user-images.githubusercontent.com/5256921/191935809-1a656fb5-338f-45c0-b4b6-bb3116da8a2d.png)

Thanks,

**Comment by crynobone** [comment]
![CleanShot 2022-09-23 at 17 59 24](https://user-images.githubusercontent.com/172966/191937194-14880640-1cd8-4aea-bc6d-be3a3057c856.gif)

Unable to reproduce the issue, please provide a full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by kitro** [comment]
@crynobone After investigation the issue is related to the external package https://github.com/davidpiesse/nova-toggle/issues/62 
Thank you,
