### ISSUE TITLE
VaporImage doesn't upload file properly in 4.15.1

### ISSUE THREAD

**Issue by riabiy-denis** [laravel/nova-issues#4839]
- Laravel Version: ` 9.31.0`
- Nova Version: `4.15.1`
- PHP Version: ` 8.1.*`
- Database Driver & Version: MySQL8
- Operating System and Version: Vapor
- Browser type and version: Chrome (latest)
- Reproduction Repository: `N/A`

### Description:

In a nutshell, same line of code gives totally different results on different Nova versions. 

```php
VaporImage::make('Thumbnail', 'thumbnail_path')
  ->rules('bail', 'required')
  ->path('public/custom/path')
  ->deletable(false),
```

In Nova `4.13.0` this line of code creates a proper file in `/tmp` folder and then copies it upon save to the custom folder.
For some reason, in `4.15.1` (haven't checked in-between versions) it saves a broken file with a much smaller size (e.g. 100B or 120B, when it's a 3mb image). The rest of the flow is ok, presigned links, etc. 

That's why it took so long to debug. I was sure it's s3 configuration or whatever, but then I noticed, that broken files get uploaded and was stoked. 

Since I see no changes in php-code, I assume it's a front-end bug -> and that's why I didn't notice anything suspicious. JS is minified and obfuscated, so no luck there to figure it out 🗡️ 

### Detailed steps to reproduce the issue on a fresh Nova installation:

Sorry, but I don't have time right now. But sharing my current experience with Vapor and Nova. 
If it's not-reproducable for you — I'm willing to put some effort. But It's quite self-explanatory. 
Fresh nova/laravel/vapor. `4.13.0` works. `4.15.1` don't.

**Comment by riabiy-denis** [comment]
@crynobone thanks :) Will keep an eye, feel free to ping us too.

**Comment by 1stevengrant** [comment]
I too am experiencing this with on 4.15.1

```
VaporImage::make('YouTube Thumb')
                        ->hideFromIndex()
                        ->help('If we want a distinct YouTube thumbnail, upload it here, otherwise we\'ll use the poster image as a default')
                        ->path('youtube_thumbs')
                        ->storeAs(function ($request) {
                            $img = $request->input('vaporFile')['youtube_thumb'];

                            return str_replace('tmp/', '', $img['key']) . '.' . $img['extension'];
                        }),
```

**Comment by crynobone** [comment]
Bugfix PR has been merged and pending next release.

As temporarily, please use `4.14.3` until `4.15.2` or `4.16.0` is released.
