### ISSUE TITLE
"Lock wait timeout exceeded"

### ISSUE THREAD

**Issue by rickmacgillis** [laravel/nova-issues#484]
Nova locks the table when it attaches models to each other. The first time it gives that error is with line # 28 of `Laravel\Nova\Http\Controllers\ResourceUpdateController` even in Nova 1.0.13.

I've been trying to debug this issue for half a day and I'm throwing in the towel. Hopefully someone can point me in the right direction.

For the record, it has to be a deadlock situation, as there's no way the transaction could possibly take that long to attach two models together in a dev environment.

The `User` model is getting a `Role` model attached to it, and the `Role` model is a custom model. I tried attaching two other models together with the same exact configuration as the one having issues, so it's not the way the model is designed, nore is it anything to do with the relationships.

My best guess is that something in the User model is getting locked for the Nova environment, and then the relationship in question is trying to get the lock.

I've also shut off Supervisor, and even restarted MySQL to purge any unused locked that might be causing a deadlock. Nothing seems to fix it.

I stripped the entire `User` Nova resource down to just the bare bones to use `BelongsTo::make(__('Role'), 'adminRole', Role::class),` in the `fields` method as well as the ID. Nothing else is custom in there. So, it has to be elsewhere in the program.

For the record, I'm using Laravel Spark, so the `User` class extends the `SparkUser` as it should.

**Comment by rickmacgillis** [comment]
SUCCESS! I fixed the situation. Here's what was going on in case anyone else is having this issue.

Eloquent apparently needs to process queries in sequence instead of nesting them. By that I mean when you run an `update` query or whatnot on Nova, you can't have it trigger an event that also runs an `update` query on the same table. However, it may also be the fact that Nova uses DB transactions and presumably because the result didn't match what Nova was expecting, it got rolled back.

So, if you're like me and you're using observers to trigger events when stuff happens on Nova, you'll need to disable (or modify) how your listeners respond to those events so it doesn't change the table while Nova changes it. Failing to do so will cause Nova to repeatedly run the same query over and over again.

To see if you're running the events inside of Nova, you'll need to leverage the `Nova::serving()` event listener to set a session variable. Below is an example.

```
Nova::serving(function () {
  Session::put('in_nova', true);
});
```
That should be placed in the `boot()` method of your `NovaServiceProvider`. After that, just use `Session::has('in_nova')` to see if you're running stuff through Nova or not.

**Comment by benjamincrozat** [comment]
@rickmacgillis Thanks man, it actually helped me understand what was going on!
