### ISSUE TITLE
Custom Menu cannot resolve request's user when on a tool url

### ISSUE THREAD

**Issue by vesper8** [laravel/nova-issues#4840]
- Laravel Version: 8.83.23
- Nova Version: 4.15.1
- PHP Version: 8.1.x

### Description:

I use a custom menu and all items in my menu are only visible to certain users. For example I have a custom menu for dashboards that looks like this:

```
    public function menuDashboards()
    {
        $dashboards = [];

        $dashboards[] = MenuItem::dashboard(App\Nova\Dashboards\TotalsDashboard::class)->canSee(function ($request) {
            return $request->user() && $request->user()->isAdmin();
        });
        $dashboards[] = MenuItem::dashboard(App\Nova\Dashboards\GameDashboard::class)->canSee(function ($request) {
            return $request->user() && $request->user()->isAdmin();
        });

        return $dashboards;
    }
```

This works perfectly fine when you're on the landing page of Nova, or on any dashboard, or in any resource/lens/etc

However, when I am on a tool, and I've tested this with multiple tools and the behaviour is the same for all tools, then `$request->user()` is null, and as a result, the entire menu is hidden when the url is that of a tool.

And just to be clear, this is my `config/auth.php` driver

```

    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],
    ],
```

**Comment by crynobone** [comment]
First, check if all routes related to Tool includes auth and session middlewares.

**Comment by vesper8** [comment]
@crynobone Thank you, the `Authenticate::class` middleware was missing, adding it restored the menu.

In testing this, I created a new custom tool using `php artisan nova:tool` and noticed that this issue is still ongoing https://github.com/laravel/nova-issues/issues/4690
https://github.com/laravel/nova-issues/discussions/4678#discussioncomment-3362616

I had to uninstall `@vue/compiler-sfc` and add `vue` to make the error go away when trying to compile the new tool's assets

I think this is a bug that should be fixed?
