### ISSUE TITLE
[Bug] v1.0.13 Update: Uncaught TypeError: Cannot read property 'call' of undefined (manifest.js) and nova:311 Uncaught ReferenceError: CreateNova is not defined

### ISSUE THREAD

**Issue by paras-malhotra** [laravel/nova-issues#485]
After the update to v1.0.13, Nova is crashing. I'm getting the following errors on console:

```
VM1026 manifest.js:1 Uncaught TypeError: Cannot read property 'call' of undefined
    at t (VM1026 manifest.js:1)
    at Object../resources/js/app.js (VM1029 app.js:47543)
    at t (VM1026 manifest.js:1)
    at Object.0 (VM1029 app.js:54517)
    at t (VM1026 manifest.js:1)
    at window.webpackJsonp (VM1026 manifest.js:1)
    at VM1029 app.js:1

nova:311 Uncaught ReferenceError: CreateNova is not defined
    at nova:311
```

I've also observed that app.css and app.js is no longer minified. I think the usual deployment script wasn't run for Nova 1.0.13

**Comment by Jam0r85** [comment]
Same for me.

**Comment by kamui545** [comment]
See #482

**Comment by rickmacgillis** [comment]
We'll continue this thread on issue #482 as it seems more robust that this ticket.

**Comment by paras-malhotra** [comment]
Closing as this is fixed in v1.0.14

**Comment by phoenixg** [comment]
I'm using v1.0.16, I still meet this problem.

**Comment by paras-malhotra** [comment]
@phoenixg v1.0.16 is working fine. Did you make sure to run the Artisan nova:publish command?

**Comment by phoenixg** [comment]
@paras-malhotra Yes I'm sure I followed #482 's bluec's 6 steps, I run `php artisan nova:publish`, not working for v1.0.16.

**Comment by rickmacgillis** [comment]
@phoenixg try deleting your public/nova-resources directory and republish.
