### ISSUE TITLE
[Feature request] support where in Metrics

### ISSUE THREAD

**Issue by SdlasHeras** [laravel/nova-issues#486]
Hi, 

I think that would be very useful to support a "->where" in Metrics. 
For example, I run an affiliate marketing network where we have offers and offers has conversions.
Metrics are useful in the offers Index but I can't see how can a metric card could be useful in the detail page of an offer because the metric is referring to all rows of the table and not to the rows related to that offer.

I think that something like adding (Trend example) a "where" to the aggregate method would help here.

`$results = $query
                ->select(DB::raw("{$expression} as date_result, {$function}({$wrappedColumn}) as aggregate"))
                ->whereBetween($dateColumn, [$startingDate, $endingDate])
                ->where($column_name, $value)
                ->groupBy(DB::raw($expression))
                ->orderBy('date_result')
                ->get();`

I expect that the idea is understable.

thanks

**Comment by urtzi88** [comment]
+1

**Comment by kopiaman** [comment]
Yeah, I need it too. The current solution, I have to make a custom card.

**Comment by sam-g-roberts** [comment]
+1 this would be a really nice feature to have. Loving nova as is though!!

**Comment by functioneelwit** [comment]
+1

**Comment by functioneelwit** [comment]
@kopiaman @GigaMick: Extending a model and adding a global scope might also be a  solution. Like so:

![image](https://user-images.githubusercontent.com/3831260/48189623-ee496680-e340-11e8-8da2-43033fe06c8d.png)

https://tighten.co/blog/extending-models-in-eloquent

Not as pretty but does the trick for me.

**Comment by richartkeil** [comment]
This seems to work perfectly fine, although not documented:
```
public function calculate(Request $request)
{
  return $this->count(
    $request, 
    Model::where('condition_column', '!=', 'archived'), 
    'column_name'
  );
}
```

**Comment by itsgonnabesick** [comment]
> This seems to work perfectly fine, although not documented:

Actually it is. But only in resource detail metrics doc : [Resource Detail Metrics](https://nova.laravel.com/docs/1.0/metrics/registering-metrics.html#resource-detail-metrics)

**Comment by sam-g-roberts** [comment]
You can achieve the same thing by adding a scope to your model.


On your model
`
public function scopeOrders($query)
{
     return $query->where('order_type', 'order');
}
`

On your metric function
`
public function calculate(Request $request)
{
     return $this->countByDays($request, Order::orders());
}
`

**Comment by davidhemphill** [comment]
This is already supported as shown in the docs: https://nova.laravel.com/docs/1.0/metrics/registering-metrics.html#resource-detail-metrics

Also, I really like the use of scopes for this kind of thing. 👍

**Comment by RubenTeles** [comment]
you can use:
`public function calculate(Request $request)
{
return new \Laravel\Nova\Metrics\ValueResult(Model::where('condition_column', '>', 1)->count());
}
`
