### ISSUE TITLE
Nova 4.15: Image filed CORS error if use multidomains

### ISSUE THREAD

**Issue by yaroslawww** [laravel/nova-issues#4860]
- Laravel Version: 9.*
- Nova Version: 4.15
- PHP Version: 8.1

### Description:
Nova 4.15 contains new cool file uploading service.
![image](https://user-images.githubusercontent.com/23663794/193213646-6c3bc8a0-0328-4707-9294-2f2767d153b8.png)

Thank you it works cool. But when the app has multiple domains (and storage doesn't use same domain as nova app) it causes CORS error because now the image loaded by js (before it was just replaced URL in the script).

If revert version to 4.14 it works perfect.

### Detailed steps to reproduce the issue on a fresh Nova installation:

For example, we have an app with two domains `crm.example.com` and `app.example.com` . Nova application is under path `crm.example.com/nova`.
And we have storage pointed to `app` URL.
```php
     'app_feature' => [
            'driver'     => 'local',
            'root'       => storage_path('app/public/app-feature'),
            'url'        => env('APP_URL').'/storage/app-feature',
            'visibility' => 'public',
      ],
```
In this case when nova image field will be initialized it will try to load image by link  `app.example.com/storage/app-feature` ... which will cause CORS error.

The same problem will be if use nova as a subdomain like `nova.example.com`.

--------------

Yes, I understand, there exist some solutions to fix it on my side, like adding access-control-origin headers, or dynamically replacing URL. But generally, I have several apps with the same problems and some apps have much more than 2 domains. So it will be really good if this problem will be fixed in the core nova package. (or by changing code from ajax load image to URL replace, or by adding an additional image field with old functionality where the developer can select what field he needs to use...)

**Comment by crynobone** [comment]
Hi,

I'm having a hard time to tests this issue, do you have a public image with "Cross-Origin Request Blocked" in order for me to verify the fixes.

**Comment by crynobone** [comment]
### 4.14.x

![image](https://user-images.githubusercontent.com/172966/193547371-7a1e95de-25c5-4352-92ca-fbb796436a99.png)

### 4.15.x

![image](https://user-images.githubusercontent.com/172966/193547541-712657df-2a6f-4bb3-8327-49d1ee459bd4.png)


I tested with Ngrok, the behavior seems the same here.

**Comment by yaroslawww** [comment]
@crynobone Sorry,  I can't, for now, provide any image. I will do it when I have some time gap.

**Comment by yaroslawww** [comment]
@crynobone 
Sorry, still no time to play with a separate app to test it.
Anyway, I updated to 4.19 - there still same CORS problem, triggered by this code
![image](https://user-images.githubusercontent.com/23663794/202456945-4ae92200-b88e-4e1b-ba3a-8ca64027da49.png)

NOTE: on your screens you show VIEW mode, but error ocure on EDIT mode (preview image).

Currently I use solution : 
nginx
```
...
location / {
    if ($http_origin ~* "^https?://(crm.site.home|cpd.site.home|sso.site.home)$") {
        add_header Access-Control-Allow-Origin "$http_origin";
    }
....
```
apache
```
SetEnvIf Origin "^http(s)?://(.+\.)?(crm\.site\.home|cpd\.site\.homeco|sso\.site\.home)$" originname=$0
Header always set Access-Control-Allow-Origin %{originname}e env=originname
```

it fix problem for me.

-------------------

P.S. Also noticed one thing: When in database image exists but fiscally file removed on EDIT mode it show nothing
![image](https://user-images.githubusercontent.com/23663794/202458568-9f4a7241-5d24-4922-8910-88d86778861f.png) 
But maybe in this case more useful to show for user some message like "File XXX.png not found", or something like this, to notify user about fiscal file deletion?
