### ISSUE TITLE
Dependent fields works only for the first one

### ISSUE THREAD

**Issue by binaryk** [laravel/nova-issues#4863]
- Laravel Version: 9.28
- Nova Version: 4.15.2
- PHP Version: 8.1.9
- Operating System and Version: MacOs Monterey 12.3.1
- Browser type and version: Brave, 1.42.97

### Description:

If you have many dependent fields, it will only work for the first one. For example: 

```php
Select::make('Purchase Type', 'type')
    ->options([
        'personal' => 'Personal',
        'gift' => 'Gift',
    ]),


Text::make('Recipient')
    ->readonly()
    ->hide()
    ->dependsOn(
        ['type'],
        function (Text $field, NovaRequest $request, FormData $formData) {
            if ($formData->type === 'gift') {
                $field->show();
            }
        }
    ),

Text::make('Sender') // <--- This is not taken into consideration
    ->readonly()
    ->hide()
    ->dependsOn(
        ['type'],
        function (Text $field, NovaRequest $request, FormData $formData) {
            if ($formData->type === 'personal') { 
                    $field->show();
            }
        }
    ),

```

### Detailed steps to reproduce the issue on a fresh Nova installation:

Fresh nova app. 

Create a resource with fields from the code above, and try to switch the Purchase type, you'll see that the Sender field is not displayed at all.

**Comment by crynobone** [comment]
Unable to reproduce the issue: https://github.com/nova-issues/issue-4863/commit/10114a34273d21f9195eb9f1184d8d7499d22b50 

Please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by binaryk** [comment]
Indeed, it works in a new project. Thank you!
