### ISSUE TITLE
If Nova Action takes longer than 1 minute, the loading indicator stops and the action window doesn't close when it finishes

### ISSUE THREAD

**Issue by vesper8** [laravel/nova-issues#4864]
Bit of an edge case no doubt but some of my Nova actions perform tasks that can take up to a few minutes after you select a few fields and click the button to start the action.

I've noticed that at the 1 minute mark the loading indicator (on the button) stops animating, and when my action does finish its task.. even if it's at 61 second.. then there will be no feedback that the action completed and the action window (with the action fields) will fail to close.

**Comment by crynobone** [comment]
I don't think there is anything specific that we can do here, the animation using `<Loader />` component and the SVG already using `<animate repeatCount="indefinite" />`
