### ISSUE TITLE
App title not updating when setting config.name

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [laravel/nova-issues#4865]
- Laravel Version: 9.33.0
- Nova Version: 4.15.2 
- PHP Version: 8.1.4
- Database Driver & Version: MySQL 8.0.28
- Operating System and Version: macOS 11.5.2
- Browser type and version: Chrome 105.0.5195.125 (Official Build) (arm64)

### Description:

When editing `config/nova.php`, if I edit the `name` key, nothing updates in the Nova UI. See below
<img width="725" alt="Screen Shot 2022-10-02 at 4 44 04 am" src="https://user-images.githubusercontent.com/41524/193422696-a52463c1-26a5-4c01-ba39-2a69ff87c5ed.png">
And here is the UI. 
<img width="332" alt="Screen Shot 2022-10-02 at 4 45 42 am" src="https://user-images.githubusercontent.com/41524/193422798-7760548c-3525-4c59-b27e-00d9ea7235a8.png">

Note that the title of the browser tab is updated, but not the text next to the logo in the Nova UI

**Comment by crynobone** [comment]
I believe you should change the SVG via `nova.brand.logo` configuration.

**Comment by matthewjumpsoffbuildings** [comment]
@crynobone oh, the entire thing including the words "Laravel Nova" is an SVG :|
