### ISSUE TITLE
Small Bugs CSS when use field with textAlign center

### ISSUE THREAD

**Issue by massimodellarovere** [laravel/nova-issues#4873]
Laravel Version: 9.33.0
Nova Version: 4.15.2
PHP Version: 8.1.7
Database Driver & Version: MYSQL 5.7
Operating System and Version: Ubuntu 22.04.1 LTS
Browser type and version: Brave Versión 1.37.116 Chromium: 100.0.4896.127 (64 bits)

### Description:
Small Bugs when use textAlign('center') with Field Status (not center component)

![image](https://user-images.githubusercontent.com/5731295/193935568-b17bf277-4553-4e27-b17d-d6a21c739eb0.png)

How I use workaround CSS (I inform you of the problem if in case you want to fix it...)

```
table .text-center > span.inline-flex
{
    margin:auto;
}

```

RESULT

![image](https://user-images.githubusercontent.com/5731295/193935912-bc529197-7be6-44f6-a60e-a34c009975e4.png)

**Comment by RhysLees** [comment]
I cant replicate this
