### ISSUE TITLE
Create/Update/Delete actions don't work when cookie serialization is enabled

### ISSUE THREAD

**Issue by chescos** [laravel/nova-issues#488]
The security fix which was added in Laravel [5.6.30](https://laravel.com/docs/5.6/upgrade#upgrade-5.6.30) disabled cookie serialization by default. However, there are apps that still have enabled serialization to allow backward compatibility with custom cookies.

The create/update/delete actions in Nova don't seem to work when cookie serialization is enabled in the `EncryptCookies` middleware; a `419` HTTP status error code is returned.

**Comment by runningman** [comment]
I seem to have just encountered this issue too

**Comment by ashupp** [comment]
I am encountering this issue as well. Did any of you solve this problem already? An if - how?

**Comment by ashupp** [comment]
@chescos thanks for your fast reply. I am using the current 1.1.3. Maybe its a cross incompatibility with spark - which i am also using. I'll dive into it.

**Comment by davidhemphill** [comment]
I believe this issue should be fixed. Please post a new issue if the issue persists.
