### ISSUE TITLE
Searchable select element

### ISSUE THREAD

**Issue by iAmGuus** [laravel/nova-issues#489]
Hi,

Is it just me or is there no real searchable select like the relationship dropdowns have? I tried adding `->searchable()` to the element, but it just gave me an error that the method was not found. I am on 1.0.12.

**Comment by NikolaySav** [comment]
Give a look
https://github.com/fat4lix/nova-element-ui

**Comment by davidhemphill** [comment]
This is not currently supported but there's 3rd-party packages that do this.
