### ISSUE TITLE
Multiple custom (dynamic) filters don't work on resource

### ISSUE THREAD

**Issue by robbedekien** [laravel/nova-issues#4894]
- Laravel Version: 9.34.0
- Nova Version: 4.15.2
- PHP Version: 8.1.5

### Description:
I would like to first refer to an old issue as this is an extension of this: https://github.com/laravel/nova-issues/issues/3879
I have a custom (dynamic) filter component, implying that I can provide an attribute that is filterable. 
Now when I want to add multiple of the same custom filter, the filter is just duplicated by the one that is listed first. Providing the key() function with a unique value just breaks the filter altogether. It seems like the apply function is never called in that situation.

**Comment by robbedekien** [comment]
Apologies for the late reply, didn't find time to create a repo to reproduce the bug
Here it is: https://github.com/robbedekien/nova-multiple-custom-filters

Steps to reproduce

- Run the linked repository
- Go to the user resource
- There are 2 of the same custom filter, one for `ID` and one for `email`, they don't work together in one resource
- Setting a unique key breaks the filter, see the commented method in TestFilter.php

Hopefully, you can reopen this issue. Otherwise, I can create a new one

**Comment by crynobone** [comment]
The "unique key" should be persistent between every request (in order to match the filter to class). Using `uniqid()` is not supported here.
