### ISSUE TITLE
BelongsToMany does properly search when starting with numeric characters

### ISSUE THREAD

**Issue by nkootstra** [laravel/nova-issues#490]
Hi,

I'm not really sure if it's a bug or by design but when I'm attaching a Barcode to my Product resource it's impossible to do so. Even when copying the complete barcode the autocompletes returns nothing. 

The other way around it works because I'm just entering the name of the product.

For example:
Entering "hello" gives a result.
Entering a barcode like "0049000971507" doesn't work.

<img width="956" alt="screen shot 2018-09-08 at 19 03 47" src="https://user-images.githubusercontent.com/545768/45256698-6e336e80-b39a-11e8-976c-51ca531ea44a.png">
<img width="953" alt="screen shot 2018-09-08 at 19 05 11" src="https://user-images.githubusercontent.com/545768/45256699-712e5f00-b39a-11e8-80f0-72542e7d13fd.png">

It may be a much bigger problem. Searching for a specific barcode (all numeric characters) also doesn't work.

**Comment by taylorotwell** [comment]
Are you using Scout?

**Comment by davidhemphill** [comment]
The newest version (1.0.15) should fix your issue.
