### ISSUE TITLE
Opening  tool in Nova 4 results in an empty modal

### ISSUE THREAD

**Issue by abdelaliabouelhassan** [laravel/nova-issues#4900]
- Laravel Version: 9.35.1
- Nova Version: 4.15.2
- PHP Version: 8.1.2
- Database Driver & Version: MySQL
- Operating System and Version: windows. 10

### Description:
When creating a Tool in Nova, loading the route directly results in a empty modal

### Detailed steps to reproduce the issue on a fresh Nova installation:

-Create a Tool, eg PHP artisan nova:tool example/demo-tool
-Register tool in the service provider
-click on the tool from the menu 

![image](https://user-images.githubusercontent.com/45344920/195231967-dc8ba0f8-ad86-428b-bc2e-55035b39631d.png)

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues/issue-4900/commit/933fd2f9bd335737d0d57ae4ead1b96e37b7261d for example)

**Comment by dorianhouse** [comment]
Had the same issue multiple times with similar configuration.

**Comment by abdelaliabouelhassan** [comment]
when I install fresh laravel project and nova and set up the nova tool example: example/demo-tool it works fine I can visit the URL   'nova/demo-tool' and see the default page.

but when I add on the web.php this line of code the nova tools are not working anymore it shows an empty modal or sometimes it shows the dashboard page on that modal 
```
Route::any('/{any}', function () {
    return view('MainApp');
})->where('any', '.*');
```

**Comment by crynobone** [comment]
> but when I add on the web.php this line of code the nova tools are not working anymore it shows an empty modal or sometimes it shows the dashboard page on that modal

That would be expected if the routes weren't defined using the correct middlewares.

**Comment by abdelaliabouelhassan** [comment]
Yes thanks

**Comment by abdelaliabouelhassan** [comment]
I fixed it with like this 

```
Route::get('/{any}', function () {
    return view('mainapp');
})->where('any', '^(?!admin).*$'); 
```
