### ISSUE TITLE
nova 4 dump inertia-laravel version

### ISSUE THREAD

**Issue by kukac7** [laravel/nova-issues#4901]
- Laravel Version: 9.35.1
- Nova Version: 4.0.0
- PHP Version: 8.1.9

### Description:
`laravel/nova[4.0.0, ..., 4.x-dev] require inertiajs/inertia-laravel ^0.4.5|^0.5.2 -> found inertiajs/inertia-laravel[v0.4.5, v0.5.2, v0.5.3, v0.5.4] but it conflicts with your root composer.json require (^0.6.3).`

**Comment by crynobone** [comment]
Latest version of Nova is 4.15.2, please update to latest version.

**Comment by kukac7** [comment]
if i install based on the [nova documentation](https://nova.laravel.com/docs/4.0/installation.html), it throws this error.

`"laravel/nova": "~4.0"`
