### ISSUE TITLE
Localization issues on Resource Title and Button.

### ISSUE THREAD

**Issue by xiCO2k** [laravel/nova-issues#4907]
When using Localizations I found that the Main title on the page does not use the same localized string that is being used on the menu.

<img width="1592" alt="image" src="https://user-images.githubusercontent.com/823088/195409646-3a227d78-4e07-4f22-b474-325ba8887f98.png">

Also happens the same with the "Create Page", that should be "Criar Página".

**Comment by crynobone** [comment]
Have you setup the following on `Page` resource?

https://nova.laravel.com/docs/4.0/customization/localization.html#resources

**Comment by xiCO2k** [comment]
That solves the issue.

Thanks.

But why it loads on the nav and not on the title, that probably misslead me.
