### ISSUE TITLE
Peeking disappears when trying to select a relation on the peek

### ISSUE THREAD

**Issue by RhysLees** [laravel/nova-issues#4909]
- Laravel Version: 9.x
- Nova Version: 4.16.0
- PHP Version: 8.1
- Database Driver & Version: Mysql
- Operating System and Version: Win 11 WSL2 Ubuntu Latest
- Browser type and version: Chrome Latest

### Description:

https://user-images.githubusercontent.com/43909932/195450956-0bf5a54d-3531-4e51-8c99-12140c9dd7f5.mp4

As seen in the video above, if you make a belongsto shown when peeking, it is a link but you are unable to click it as it disappers when you try to hover it

https://user-images.githubusercontent.com/43909932/195452754-8b203a36-73f7-4db3-9836-c9a00692e500.mp4

Same can be said for file fields. it gives the option to download but you cant click them as it disappears when trying to hover

**Comment by ziming** [comment]
For me it keep rapidly appear and disappear when i hover over over the relation.

**Comment by RhysLees** [comment]
> For me it keep rapidly appear and disappear when i hover over over the relation.

Same thing happens to me sometimes
