### ISSUE TITLE
Slug are not unique

### ISSUE THREAD

**Issue by mrleblanc101** [laravel/nova-issues#4912]
- Laravel Version: 9.34.0
- Nova Version: 4.15.2
- PHP Version: 8.1
- Database Driver & Version: mariadb 10.4
- Operating System and Version: macOS 12.6
- Browser type and version: Chrome 105

### Description:
Slug are not unique inside a collection.
Most of the time, we expect that they are.
This should cause a validation error when saving.
![Capture d’écran, le 2022-10-13 à 10 54 21](https://user-images.githubusercontent.com/17392251/195631801-b1fd6341-0733-4d69-893d-9310b9c9fb79.png)

If a slug with this value already exist, the field should append `-1` to the Slug.
If `-1` also exist, it should increment until it find a value that is not used.
![Capture d’écran, le 2022-10-13 à 10 56 11](https://user-images.githubusercontent.com/17392251/195632288-410ee7ab-14a4-4500-87c7-cd7ca14dc5e7.png)

**Comment by mrleblanc101** [comment]
Maybe there should be a `->unique()` modifier ?

**Comment by crynobone** [comment]
You need to define your own validation rules, Nova doesn't provide any field-based validation except for attaching relationships.

**Comment by mrleblanc101** [comment]
This is not a validation rule tho. The slug is generated in type.
