### ISSUE TITLE
Searchable selection box won't close if there is a lot of field before it 

### ISSUE THREAD

**Issue by yong9402211** [laravel/nova-issues#4917]
- Laravel Version: 9.33.0
- Nova Version: ^4.0
- PHP Version: 8.1.1
- Database Driver & Version: 
- Operating System and Version: Windows 10
- Browser type and version: Microsoft Edge
- Reproduction Repository: https://github.com/###/###

### Description:
Problem:
![image](https://user-images.githubusercontent.com/81783402/195737233-ffb12d73-6590-4f81-af7a-e89cffc8fbb7.png)

Ok:
![image](https://user-images.githubusercontent.com/81783402/195737832-a8dd3d9c-bab2-4eca-bba4-73dbc12b780c.png)

If got a lot of field before the searchable selection, will cause the selection won't close.
Also will cause menu group cannot expand

```
Select::make('Country', 'address_country')
    ->searchable()
    ->filterable()
    ->hideFromIndex()
    ->options(
        Country::orderByRaw('FIELD(id, 209) DESC, name ASC')
        ->pluck('name', 'name')
    )
    ->displayUsingLabels(),

Select::make('State', 'address_state')
    ->searchable()
    ->sortable()
    ->filterable()
    ->dependsOn(
        'address_country',
        function (Select $field, NovaRequest $request, FormData $formData) {
            $field->options(
                State::whereHas('country', function (Builder $query) use ($formData) {
                    $query->where('name', $formData->address_country);
                })
                ->pluck('name', 'name')->sort());
        }
    )
    ->displayUsingLabels(),
```

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues/issue-4917/commit/85550c73428091444303cc321fc8f6b6472bdae2 for example)

**Comment by yong9402211** [comment]
Github: https://github.com/yong9402211/nova-error
Link: http://localhost:8000/nova/resources/posts/new

Screenshot:
![image](https://user-images.githubusercontent.com/81783402/195748303-194a1b01-db2c-4ed7-aad4-2ceca533f279.png)

Video:

https://user-images.githubusercontent.com/81783402/195748573-2ac680cb-2c18-4e58-8580-468ed024a5f3.mp4

**Comment by yong9402211** [comment]
You need to add more field before your searchable selection.
More than your screen height, more than 100vh
