### ISSUE TITLE
Field should not be generic

### ISSUE THREAD

**Issue by bastien-phi** [laravel/nova-issues#4919]
- Laravel Version: 9.35.1
- Nova Version: 4.16.1
- PHP Version: 8.1.11
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:
Field is defined with 
```php
/**
 * @template TValidationRules of array<int, \Stringable|string|\Illuminate\Contracts\Validation\Rule|\Illuminate\Contracts\Validation\InvokableRule|callable>|\Stringable|string|(callable(string, mixed, \Closure):void)
 */
abstract class Field 
{
..
```
in order to reuse `TValidationRules` in field and method types (`rules()`, `getRules()`, ...)

Defining this way implies that `Field` class becomes generic, which is not the case. This could not be an issue but running PHPStan with `checkGenericClassInNonGenericObjectType: true` causes issues like :

```
Method App\Nova\Resources\Rule\RuleResource::fields() return type with generic class Laravel\Nova\Fields\Field does not specify its types: TValidationRules
```

### Detailed steps to reproduce the issue on a fresh Nova installation:

Install PHPStan and define `checkGenericClassInNonGenericObjectType: true` in the config file

Create a new Nova resource with
```php
    /**
     * @return array<int, Laravel\Nova\Fields\Field>
     */
    public function fields(Request $request): array
    {
        return [
            ID::make(),
        ];
    }
```

Run PHPStan.

### How to solve

It would be possible to define a local type alias instead of a template : 
```php
/**
 * @phpstan-type TValidationRules array<int, \Stringable|string|\Illuminate\Contracts\Validation\Rule|\Illuminate\Contracts\Validation\InvokableRule|callable>|\Stringable|string|(callable(string, mixed, \Closure):void)
 */
abstract class Field 
{
..
```
see https://phpstan.org/writing-php-code/phpdoc-types#local-type-aliases

**Comment by crynobone** [comment]
Fixed and pending next release, thank you.
