### ISSUE TITLE
Laravel Model 'strict modes' cause all pages to fail to load (at least Resource, Lens)

### ISSUE THREAD

**Issue by juse-less** [laravel/nova-issues#4923]
- Laravel Version: 9.35.1
- Nova Version: 4.16.1
- PHP Version: 8.1.11
- Database Driver & Version: Percona/MySQL 8.0.29-21
- Operating System and Version: AlmaLinux 8.6
- Browser type and version: Arc 0.72.0 (35182) / Chromium 106.0.5249.119
- Reproduction Repository: https://github.com/juse-less/laravel-nova-issues/tree/issue/laravel-model-strictness

### Description:

Apologies in advance. I'm not sure if this should be considered a bug, or a feature request to use that Laravel feature.

When using Laravel's newer `Model::shouldBeStrict()`, pages fail to load as Laravel is throwing exceptions.
More specifically it appears to be `Model::preventAccessingMissingAttributes()` that is throwing a fit.

The error thrown is
```
The attribute [pivot] either does not exist or was not retrieved for model [<Model FQN>].
```

The Model in question (User), in the provided repo, has no relationships.

<details>
<summary>Attached video and screenshot of the issue</summary>

![ScreenShot 2022-10-14 at 22 27 43](https://user-images.githubusercontent.com/76173223/195950604-8f92db03-4ac4-41aa-8763-90a4d67cfc17.png)

https://user-images.githubusercontent.com/76173223/195950613-351961cd-6fa5-409b-95c6-edd6413d6735.mp4

</details>

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Check out the repo provided, using the branch `issue/laravel-model-strictness`
1. Install dependencies, and publish assets
1. Create a user
1. Log in to Nova
1. View any page (like the users resource)

**Comment by crynobone** [comment]
After various tests/changes to Nova, it seems impossible to support `Model::preventAccessingMissingAttributes()` without introducing breaking changes. As a result, I have submitted laravel/framework#44627 where you should be able to disable strict mode when accessed in Nova.

**Comment by crynobone** [comment]
In the next release, Nova will automatically toggle `Model::preventAccessingMissingAttributes()` when handling Nova Requests.
