### ISSUE TITLE
Trix icon color in dark mode

### ISSUE THREAD

**Issue by skrskr** [laravel/nova-issues#4927]
- Nova Version: v4.15.2

### Description:
When i use trix on dark mode, icons color is black which not clear.
It's a good idea to change black color, so it will be more clear for eyes.
![Screenshot from 2022-10-15 14-09-27](https://user-images.githubusercontent.com/15523129/195985760-be2f3acd-5a0b-4816-ae5f-f9e5389dd586.png)

**Comment by juse-less** [comment]
This was mentioned in #4913 a couple days ago, and linked to the discussion #3955.
In the discussion it's mentioned that Trix itself doesn't support dark mode.
I also saw mentioned that Trix hasn't had any commit for the past 2 years.
Looking at the Trix repo, it does look rather abandoned.

So this could be a bit tricky to solve in a supported way (I haven't done any deep dives).
In #3955, there is however a [workaround mentioned](https://github.com/laravel/nova-issues/discussions/3955#discussioncomment-2958253).

**Comment by skrskr** [comment]
Thanks, i will check it
