### ISSUE TITLE
Add default values on fields when creating

### ISSUE THREAD

**Issue by wfeller** [laravel/nova-issues#493]
Would it be possible to add a default value on fields? This value would be used only when creating.

Something like this maybe:
`Field::make('My field')->defaultValue('some value')`

**Comment by Giactan** [comment]
You can pass this by $attributes in Model
Example: Project/app/Booking.php
```
use Illuminate\Database\Eloquent\Model;

class Booking extends Model
{
    protected $attributes = [
        'status' => 'pending',
        'price' => 0,
        'commission' => 0,
    ];
}
```

**Comment by wfeller** [comment]
Sweet, tyvm 👍

**Comment by zeevin** [comment]
also like this:
`Text::make( 'vsn')->rules('required', 'max:64', 'unique:vendors,vsn,{{resourceId}}')
                ->withMeta(
                    [
                        'value' => (function () {
                            return $this->vsn ?? 2;
                        })(),
                    ]
                ),`

**Comment by dillingham** [comment]
Also if you need method calls you can set it on the resource
```php
public static function newModel()
{
    $model = new static::$model;
    $model->setAttribute('user_id', auth()->id());
    return $model;
}
```

**Comment by notflip** [comment]
> You can pass this by $attributes in Model
> Example: Project/app/Booking.php
> 
> ```
> use Illuminate\Database\Eloquent\Model;
> 
> class Booking extends Model
> {
>     protected $attributes = [
>         'status' => 'pending',
>         'price' => 0,
>         'commission' => 0,
>     ];
> }
> ```

Where in the nova source does this get read?

**Comment by dillingham** [comment]
@notflip when nova instantiates a model, those values come pre-filled
