### ISSUE TITLE
Compilation errors when building a custom field

### ISSUE THREAD

**Issue by grantholle** [laravel/nova-issues#4931]
- Laravel Version: 9.35.1
- Nova Version: 4.16.1
- PHP Version: 8.1.10
- Operating System and Version: macOS 12.6

### Description:

When attempting to create a field, I'm receiving the following errors when compiling assets:

```
ERROR in ../../vendor/laravel/nova/resources/js/mixins/HandlesFormRequest.js 1:0-49
Module not found: Error: Can't resolve 'form-backend-validation' in '/my/project/vendor/laravel/nova/resources/js/mixins'

ERROR in ../../vendor/laravel/nova/resources/js/mixins/HandlesValidationErrors.js 1:0-49
Module not found: Error: Can't resolve 'form-backend-validation' in '/my/project/vendor/laravel/nova/resources/js/mixins'

ERROR in ../../vendor/laravel/nova/resources/js/mixins/PreventsFormAbandonment.js 4:0-48
Module not found: Error: Can't resolve 'vuex' in '/my/project/vendor/laravel/nova/resources/js/mixins'

ERROR in ../../vendor/laravel/nova/resources/js/mixins/PreventsModalAbandonment.js 4:0-48
Module not found: Error: Can't resolve 'vuex' in '/my/project/vendor/laravel/nova/resources/js/mixins'

ERROR in ../../vendor/laravel/nova/resources/js/mixins/packages.js 16:0-49
Module not found: Error: Can't resolve 'form-backend-validation' in '/my/project/vendor/laravel/nova/resources/js/mixins'

webpack compiled with 5 errors
```

The field does not render on my resource.

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Use the installation command to create a field: `php artisan nova:field MyField`
2. Compile assets using `npm run [dev|prod|watch]`.

**Comment by crynobone** [comment]
1. Does this error occur during the first install? or after?
2. Did you run `npm run nova-install` as suggested in the documentation? https://nova.laravel.com/docs/4.0/customization/fields.html#compiling-assets

**Comment by grantholle** [comment]
Apparently it needed `npm run nova:install`.

Although I thought that it prompted that when running `php artisan nova:field`?
