### ISSUE TITLE
Crash when loading sub-relationships on soft-deleted relationships

### ISSUE THREAD

**Issue by potsky** [laravel/nova-issues#4934]
- Laravel Version: 9.35.1
- Nova Version: 4.16.1
- PHP Version: 8.1.10
- Database Driver & Version: pgsql

### Description:

- I have Users
- Users have many Objects
- Objects belongsTo a Team
- Users have many Teams (via Jetstream)

When displaying a Team with relations to Objects, the Objects panel crashes because a User who owned one of the object has been soft deleted.

### Solution

Assume that object (`$this→resource` here) can be soft deleted in `pivotFieldsFor` method of class `ResolvesFields` lines `803-804` and then be `null`. So when adding `?` before `→` resolves the problem.

```php
            $pivotRelation = $this->resource?->{$field->manyToManyRelationship}();
            $field->pivotAccessor = $pivotAccessor = $pivotRelation?->getPivotAccessor();
```

### Detailed steps to reproduce the issue on a fresh Nova installation:

- Install Jetstream with team
- Create a new model Example with:
```php
    public function team(): BelongsTo
    {
        return $this->belongsTo(Jetstream::teamModel());
    }
    public function owner(): BelongsTo
    {
        return $this->belongsTo(User::class)->withTrashed();
    }
```
- Use this Nova pivot for user roles in team:
```php
<?php

namespace App\Nova;

use Laravel\Jetstream\Jetstream;
use Laravel\Nova\Fields\Select;

class TeamUserFields
{
    /**
     * Get the pivot fields for the relationship.
     *
     * @return array<mixed>
     */
    public function __invoke()
    {
        return [
            Select::make(__('Role'), 'role')
                ->options(
                    collect(Jetstream::$roles)
                        ->mapWithKeys(fn ($r, $k) => [$k => $r->name])
                        ->sort()
                        ->toArray()
                )
                ->creationRules('required')
                ->updateRules('required')
                ->displayUsingLabels(),
        ];
    }
}
```
- Create a Team
- Create an Example object belongs to the Team
- Create a User with JetStream role `admin` in the Team
- Make the object Example owned by this User
- Soft delete the User
- Display the Team with the relationship on Example
- it crashes because `Call to a member function teams() on null`

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide a full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)
