### ISSUE TITLE
Allowing Duplicate relations requires a unique pivot field to allow the duplicate attach

### ISSUE THREAD

**Issue by RhysLees** [laravel/nova-issues#4935]
- Laravel Version: 9.35.1
- Nova Version: 4.16.1
- PHP Version: 8.1
- Database Driver & Version: Mysql
- Operating System and Version: Win 11 x WSL2
- Browser type and version: Chrome Latest
- Reproduction Repository: https://github.com/RhysLees/NovaIssues/tree/allow-duplicates

### Description:

https://nova.laravel.com/docs/4.0/resources/relationships.html#allowing-duplicate-relations

To use `allowDuplicateRelations()`, you are required to have a unique pivot field

## To Replicate

Clone the repo switch to allow-duplicates branch
Migrate Fresh Seed  username: `test@example.com` password: `password`
Login to nova
create a Chart
while in chart click `attach key`
create inline
click `attach & attach another`
select the same key you created
click `attach key`
observe the already attached error

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/196292466-7302b9cd-bb20-46d8-92a6-0d7db7479f1c.png)

I believe the indication of `id` column should already be enough?

**Comment by RhysLees** [comment]
No, you have to have another field, ill make a reproduction repo

**Comment by RhysLees** [comment]
@crynobone I have just updated this issue with a repo and instructions. Thanks :)
