### ISSUE TITLE
Sort order not displayed on HasMany fields

### ISSUE THREAD

**Issue by mrleblanc101** [laravel/nova-issues#4942]
- Laravel Version: 9.34.0
- Nova Version: 4.15.2
- PHP Version: 8.1
- Database Driver & Version: mariadb 10.4
- Operating System and Version: macOS 12.6
- Browser type and version: Chrome 105

### Description:
The arrows next to the field should reflect the sort order.
This does not work in HasMany fields.
The sort is correctly applied and even refrected in the URL.
`http://test.local/resources/awards/1` becomes
`http://test.local/resources/awards/1?award_ceremonies_order=date&award_ceremonies_direction=asc`

![2022-10-18 11 56 01](https://user-images.githubusercontent.com/17392251/196482382-1a970d0c-10e4-46cc-9b7f-7054d96a6182.gif)

But it does work in a Collection:
![2022-10-18 11 57 08](https://user-images.githubusercontent.com/17392251/196482480-37728d03-2739-429f-9ebc-d22afa6256d6.gif)

**Comment by crynobone** [comment]
https://user-images.githubusercontent.com/172966/196565873-e861f961-7d3f-4aee-8d6d-ae8a1d764ce4.mp4

Unable to reproduce, you may have 3rd party packages that doesn't support this feature/has a bug.

**Comment by mrleblanc101** [comment]
Weird, I don't have many packages.
Maybe it's Nova Sortable, but it's not even used on that relationship, not in any other relationship of that resource.
```
    "require": {
        "php": "^8.1",
        "laravel/framework": "^9.0",
        "laravel/nova": "~4.0",
        "laravel/tinker": "^2.7",
        "outl1ne/nova-multiselect-field": "^4.1",
        "outl1ne/nova-sortable": "^3.2",
        "sentry/sentry-laravel": "^2.12",
        "spatie/eloquent-sortable": "^4.0",
        "spatie/laravel-query-builder": "^5.0",
        "spatie/laravel-translatable": "^6.0",
        "staudenmeir/belongs-to-through": "^2.12",
        "whitecube/nova-flexible-content": "^1.0"
    },
```

**Comment by crynobone** [comment]
https://github.com/outl1ne/nova-sortable/blob/main/resources/js/entry.js

When a package override Nova's component it does it globally. You're now depending on frontend code provided by the package.
