### ISSUE TITLE
Class 'App\Nova\SubNamespace\Resource' not found

### ISSUE THREAD

**Issue by TonnyORG** [laravel/nova-issues#495]
Another bug found for registering resources under a sub-namespace.

Typing `php artisan nova:resource Vehicle\\Car` will create the new resource under the correct folder (nova/vehicle/car.php) and namespace (App/Nova/Vehicle), however, the `Resource` class is not defined so Laravel assumes that it is inside the `Vehicle` namespace as the Car class is.

The exception is:
```
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
Class 'App\Nova\Vehicle\Resource' not found
```

**Comment by taylorotwell** [comment]
Don't you need to import it?

**Comment by TonnyORG** [comment]
Yes I missed that one, my bad. It's working now.

**Comment by OBTIMLLC** [comment]
Hi,
I have the same issue trying to organize my model, resource in a separated folder and as result after creating a resource in nova i git the same error and unfortunately i am not sure where I what I have to import ! I am beginner level at Nova, could be wonderful if you can point me to the file and command have to be used.
Thank you Taylor & Tonny
