### ISSUE TITLE
`Nova.liftOff()` loads before app processed.

### ISSUE THREAD

**Issue by yaroslawww** [laravel/nova-issues#4957]
- Laravel Version: 9.x
- Nova Version: 9.16
- PHP Version: 8.1
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:
`Nova.liftOff()` loads before app processed.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Laypit contains this script:
```
<!-- Start Nova -->
    <script defer>
        Nova.liftOff()
    </script>
```
This works correctly on my local but on the server, it returns the error:
![image](https://user-images.githubusercontent.com/23663794/197182112-9761337a-d93f-4aa1-8b2f-7de465b42d83.png)
This is because `app` is not fully processed but the browser tries to call it.
for me these updates fix the problem:
```
<!-- Start Nova -->
    <script defer>
        setTimeout(() => { Nova.liftOff() }, 0)
    </script>
```
![image](https://user-images.githubusercontent.com/23663794/197182526-60340726-2dfd-4f5c-aca3-7385fbb53a66.png)

**Comment by crynobone** [comment]
https://github.com/laravel/nova-issues/discussions/4127

Rocket loader is useful for your website but it not suitable for SPA. Please disable it for Nova's route.
