### ISSUE TITLE
json_decode() expects parameter 1 to be string, object given

### ISSUE THREAD

**Issue by TonnyORG** [laravel/nova-issues#496]
Having this **model**:
```
<?php

use Illuminate\Database\Eloquent\Model;

class Script extends Model
{
    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'code' => 'object',
    ];
...
```

And this **nova resource**:
```
<?php

namespace App\Nova;

class Script extends Resource
{
    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [
            ID::make()
                ->sortable(),
            Code::make('code')
                ->json()
                ->hideFromIndex(),
        ];
    }
```

Then the following error will show up: `json_decode() expects parameter 1 to be string, object given`.

**Comment by jameslkingsley** [comment]
You could add this to the field:
```php
Code::make('Code')
    ->json()
    ->hideFromIndex()
    ->resolveUsing(function () {
        return json_encode((array) $this->code, JSON_PRETTY_PRINT);
    })
```

**Comment by TonnyORG** [comment]
@jameslkingsley tyvm, that worked. Not sure if it's ideal but at least worked.

**Comment by taylorotwell** [comment]
Use the `json` cast, not `object`.

**Comment by TonnyORG** [comment]
@taylorotwell if I use json then I cannot perform operations like `$script->code->test` in my app (not Nova) as is not casted to Object. That said, casting it into an object forces me to perform `json_encode` in the Nova resource. If I cast it into json then I've to perform json_decode everywhere in the app where I need to play with the object.

This is the error I get in the app if I use json cast: `Trying to get property 'test' of non-object`.
