### ISSUE TITLE
Attempt to read property on null for placeholder()

### ISSUE THREAD

**Issue by rik-legger** [laravel/nova-issues#4972]
- Laravel Version: v9.37.0
- Nova Version: v4.17.0
- PHP Version: 8.1.10

### Description:
Since Nova v4.16.0 and up I'm having an issue where I'm not able to insert a property into a placeholder for the resource.

### Detailed steps to reproduce the issue on a fresh Nova installation:

```
public function fields(Request $request): array
    {
        Text::make('Example')
            ->placeholder($this->id),
}
```

It will return with 'Attempt to read property "id" on null', in previous versions this functionality worked for me.

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide a full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)
