### ISSUE TITLE
nova 4 path not working

### ISSUE THREAD

**Issue by sajidparwez** [laravel/nova-issues#4983]
- Laravel Version: #.#.#
- Nova Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)
