### ISSUE TITLE
Partition metrics in combination with spatie/laravel-model-states

### ISSUE THREAD

**Issue by MrAtiebatie** [laravel/nova-issues#4985]
- Laravel Version: 9.37.0
- Nova Version: 4.17.1
- PHP Version: 8.0.2
- Database Driver & Version: MariaDB 10.9.3
- Operating System and Version: MacOS Big Sur 11.7
- Browser type and version: Chrome 106.0.5249.119

### Description:
I'm using the great spatie/laravel-model-states package. This will cast a model's string attribute to a State class. However, this produces a bug in Nova when creating a metric. For example, when working with a column invoice_status that will be casted to a State.

```
class Invoice extends Model {
    protected $casts = [
        'invoice_status' => InvoiceState::class,
    ];
}
```

With the following metric:
```
class CountPartition extends Partition {
    public function calculate(NovaRequest $request)
    {
        return $this->count($request, Invoice::class, 'invoice_status');
    }
}
```

However, Nova tries to map the column 'invoice_status' to an array with the count result. But since invoice_status is mapped to a State class it throws an 'Illegal offset error'. It's produced in `Laravel\Nova\Metrics\Partition` in this function:

```
protected function formatAggregateResult($result, $groupBy)
{
    $key = with($result->{last(explode('.', $groupBy))}, function ($key) {
        return Util::value($key);
    });

    // This line ⬇️
    return [$key => $result->aggregate];
}
```

Changing it to use raw original attributes will fix this:

```
$key = with($result->getRawOriginal(last(explode('.', $groupBy))), function ($key) {
    return Util::value($key);
});
```

**Comment by crynobone** [comment]
The suggested changes going to cause breaking change to BackedEnum casted attribute. That's not acceptable.

**Comment by RhysLees** [comment]
i just convert the Enum to a collection for nova with this trait:

```php
<?php

namespace RhysLees\EnumTraits\Traits;

use Illuminate\Support\Collection;
use Illuminate\Support\Str;

trait HasOptions
{
    public static function options(): Collection
    {
        return Collection::make(self::cases())->mapWithKeys(
            fn ($case) => [$case->value => Str::of($case->value)->replace('_', ' ')->value()]
        );
    }
```

```php
<?php

namespace App\Enums;

use RhysLees\EnumTraits\Traits\HasOptions;

enum RoleEnum: string
{
    use HasOptions;

    case ARRANGER = 'Arranger';
    case COMPOSER = 'Composer';
    case LYRICIST = 'Lyricist';
}
```

Then i loop over each Enum and filter the relation to build the results:

```php
class ChartsPerRolePartitionMetric extends Partition
{
    public function calculate(NovaRequest $request)
    {
        $person = Person::find($request->resourceId);

        $results = [];

        foreach (RoleEnum::options() as $role) {
            $results[$role] = $person->charts->filter(function ($chart) use ($role) {
                return $chart->pivot->role->value === $role;
            })->count();
        }

        return $this->result($results);
    }
```

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/198948201-808d3a4d-f551-4cb8-aea4-5c6017523118.png)

I believe this changes should be enough.
