### ISSUE TITLE
[Bug] Tools are not booted when rendering a resource table after logging in, causing fields to not display

### ISSUE THREAD

**Issue by Tarpsvo** [laravel/nova-issues#4991]
- Laravel Version: 9.37.0
- Nova Version: 4.17.1
- PHP Version: 8.1
- Database Driver & Version: MySQL 8
- Operating System and Version: MacOS
- Browser type and version: Brave (Chromium)

### Description:
From what I can tell, before version 4.17, all tools were loaded when logged out as well. Now they're loaded after signing in.

However, this has caused the third party tools that are loaded to not boot at all on the Vue side (Nova.booting() callback is not run).

### Detailed steps to reproduce the issue on a fresh Nova installation:

Instally any third party package (ie outl1ne/nova-inline-text-field). Add the field to a resource. Then open up incognito (or log out and refresh), sign in and open the resource index view. The Vue component isn't mounted.

A little illustration of what the result is on the index view:
![image](https://user-images.githubusercontent.com/2018660/198970203-b9d7f599-f39a-4214-a8f0-e2c83d6aa830.png)

**Comment by crynobone** [comment]
> From what I can tell, before version 4.17, all tools were loaded when logged out as well. Now they're loaded after signing in.

This was never the intended behaviour. You might experience this in some of the earlier 4.x release where no full page reload occue on logout but that has been fixed.

**Comment by Tarpsvo** [comment]
So it's okay for tools not to load at all when signing in?

**Comment by crynobone** [comment]
> So it's okay for tools not to load at all when signing in?

No, the tools should be loaded. However, all your statement contradicts what is currently expected and I cannot replicate this issue.

**Comment by crynobone** [comment]
The only possibility this could occur is for some reason your Nova app doesn't do full page reloading during login or logout. And this isn't possible with current vanilla installation.

**Comment by Tarpsvo** [comment]
Thanks @crynobone! There was indeed an issue on our side with a controller returning a `redirect()` instead of a JSON `['redirect' => '']`. I apologize for the confusion.
