### ISSUE TITLE
Validation of Action fields doesn't work properly

### ISSUE THREAD

**Issue by chimit** [laravel/nova-issues#4998]
- Laravel Version: 9.37.0
- Nova Version: 4.17.1
- PHP Version: 8.1.9
- Database Driver & Version:
- Operating System and Version: macOS Ventura 13.0
- Browser type and version: Safari 16.1
- Reproduction Repository: https://github.com/chimit/nova

### Description:

I have two boolean fields `car_parking` and `moto_parking` which control two Action fields `car_parking_price` and `moto_parking_price`. If car or moto parking is presented at the building level we want to ask for a price for each before running the action. [Here](https://github.com/chimit/nova/blob/master/app/Nova/Actions/CreateProject.php#L36-L49) is the implementation suggested by @crynobone:

```php
    /**
     * Get the fields available on the action.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @return array
     */
    public function fields(NovaRequest $request)
    {
        $model = $request->selectedResources()?->first() ?? $this->model;

        return [
            Number::make('Car parking price')
                ->rules(Rule::requiredIf(fn () => $model->car_parking))
                ->canSee(fn ($request) => $model->car_parking),

            Number::make('Moto parking price')
                ->rules(Rule::requiredIf(fn () => $model->moto_parking))
                ->canSee(fn ($request) => $model->moto_parking),
        ];
    }
```

### Issues:

1. The `required` rule is not applied:

<img width="671" alt="image" src="https://user-images.githubusercontent.com/839349/199208007-9aa5610b-8e86-4334-b0e0-2ecbb52fb5f2.png">

2. For the building with `car_parking=false` and `moto_parking=true` the second field is not displayed in the dialog window:

<img width="672" alt="image" src="https://user-images.githubusercontent.com/839349/199208238-da2415da-e3a5-4bc9-9124-7713aa7e4b7a.png">

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Run migrations and seeders;
4. Try to run the `CreateProject` action on all 3 buildings one by one.

**Comment by crynobone** [comment]
As for `1`, since you already using `canSee()`, having `rules('required')` should be enough. Otherwise you can use `rules([Rule::requiredIf(fn () => $model->car_parking)])` or `rules(Rule::requiredIf($model->car_parking))`

**Comment by crynobone** [comment]
Marking `bug` for `2`.

**Comment by chimit** [comment]
> As for 1, since you already using canSee(), having rules('required') should be enough. 

@crynobone it doesn't work. Looks like the hidden field is still required and fails the validation:

<img width="336" alt="image" src="https://user-images.githubusercontent.com/839349/199682647-b93ca557-32fe-45b9-9d8e-69d1700298c5.png">

> Otherwise you can use rules([Rule::requiredIf(fn () => $model->car_parking)]) or rules(Rule::requiredIf($model->car_parking))

Here is another bug:

1. `rules([Rule::requiredIf(fn () => $model->car_parking)])` works.
2. `rules(Rule::requiredIf(fn () => $model->car_parking))` doesn't work: the field is not marked as required and can be submitted empty.
3. `rules([Rule::requiredIf($model->car_parking)])` works.
4. `rules(Rule::requiredIf($model->car_parking))` doesn't work:
<img width="480" alt="image" src="https://user-images.githubusercontent.com/839349/199683347-93955ce3-d5a3-4e5b-a55d-e46817890854.png">

Looks like only arrays passed to `rules` work properly.

**Comment by crynobone** [comment]
> Here is another bug

`rules()` method would convert `Stringable` such as `Rule::requiredIf()` to `string` which cause the issue. Technically we can't do anything since the issue doesn't exist by wrapping it with `[]` and we don't own `Illuminate\Validation\Rule` class. Use what's working.

**Comment by chimit** [comment]
@crynobone, yes, I will use the array approach for now. But if it's an Illuminate package bug it should be at least reported I guess. And I'm also worry about other devs who may get into the same trap. It would be nice either to fix it or mention in the docs that you must use arrays.

<img width="761" alt="image" src="https://user-images.githubusercontent.com/839349/199877746-f15bfbb5-6d72-41ea-819a-42594e44b935.png">

@davidhemphill, the issue is closed but it seems the bug is not fixed yet. At least, I still have it in the latest [v4.18.2](https://nova.laravel.com/releases/4.18.2) release. Is there any way to track the delivery of this fix?
