### ISSUE TITLE
Multiword resources

### ISSUE THREAD

**Issue by vyuldashev** [laravel/nova-issues#5]
We have model InvoiceTariff resource in our project and override `label` and `singularLabel` method:

```php
public static function label(): string
{
    return 'Invoice tariffs';
}

public static function singularLabel(): string
{
    return 'Invoice tariff';
}
```

I guess the button `Create {placeholder}` can use `singularLabel` for `{placeholder}?

<img width="988" alt="screen shot 2018-08-23 at 17 16 43" src="https://user-images.githubusercontent.com/1809081/44530986-57cdb780-a6f8-11e8-8f57-ba19b3acb2a3.png">

**Comment by liamcottle** [comment]
Looks nice for the `Create` button on the Index page ! Just missing the `New` and `Edit` titles as well as the and `Create` and `Update` buttons. :)

<img width="1018" alt="screen shot 2018-08-24 at 2 28 45 am" src="https://user-images.githubusercontent.com/3173581/44531882-ea487800-a745-11e8-84bd-8a57bba27aae.png">

<img width="993" alt="screen shot 2018-08-24 at 2 28 54 am" src="https://user-images.githubusercontent.com/3173581/44531883-eae10e80-a745-11e8-93d5-da0460a13346.png">

<img width="1000" alt="screen shot 2018-08-24 at 2 29 20 am" src="https://user-images.githubusercontent.com/3173581/44531884-eae10e80-a745-11e8-9641-d6bae9044527.png">

**Comment by vyuldashev** [comment]
@liamcottle I confirm:

<img width="321" alt="screen shot 2018-08-23 at 17 43 14" src="https://user-images.githubusercontent.com/1809081/44532556-07585900-a6fc-11e8-805e-e270fd308655.png">
