### ISSUE TITLE
Mobile display?

### ISSUE THREAD

**Issue by webspectyler** [laravel/nova-issues#50]
Are there plans to make the Nova interface responsive at small screen sizes?

**Comment by vyuldashev** [comment]
Many of our users use mobile phones while not having access to PCs, so this would be great to have.

**Comment by zeroseed** [comment]
Yeah me too , when first look on laravel nova i thought it will be responsive, but it don't,
so it will be great to have simple responsive style like bootstrap maybe 😃

**Comment by alexjose** [comment]
+1

**Comment by bakkertjebrood** [comment]
+1

**Comment by eullercdr** [comment]
+1

**Comment by ankurkwv** [comment]
+1

Planning to use this to power an event software. A lot of our admins will spend heavy time on the desktop ahead of the event, but naturally, things come up during the event and Nova must be accessible on mobile to manage that. Can't use until that's the case unfortunately.

**Comment by alfonsobries** [comment]
+1

**Comment by yaserzizo** [comment]
+1

**Comment by nickels** [comment]
+1

**Comment by DonDiegoAA** [comment]
+1

**Comment by tommymarshall** [comment]
I would stop +1 (everyone gets a notification) and instead do a 👍 to show support for this idea (which is a non-trivial UI enhancement).

**Comment by jslewis90** [comment]
On my external monitor, I typically have my browser docked on one half of the screen with my code editor on the other half. Unfortunately, Nova requires me to scroll to get to the action buttons if I only use exactly half of my screen for the browser.

**Comment by rodwin** [comment]
Hopefully, this will not be a version 2 enhancement

**Comment by bakkertjebrood** [comment]
I honestly dont understand why responsiveness is not part of the first release of Nova. In my opinion every current webapplication created should provide support for mobile. Especially when paying 199 dollars for it.

**Comment by taylorotwell** [comment]
This repository is for tracking bugs. Feature requests may be emailed to Nova customer support.

**Comment by webspectyler** [comment]
Heard back from support this afternoon, for anyone interested:

>We may work on a responsive version in the future, but it's not planned currently. Though, we quite like the power you get from being able to have the whole interface available to yo

**Comment by hailwood** [comment]
> Though, we quite like the power you get from being able to have the whole interface available to you.
What does that even mean?

**Comment by packytagliaferro** [comment]
It seems odd to me that any site is not responsive, especially since it looks like there doc (https://nova.laravel.com/docs/1.0/installation.html) uses the same UI and its responsive. I did see there are some themes coming out by different authors that may provide responsiveness. I haven't tried one but here is a [link](https://novapackages.com/packages/jameslkingsley/nova-stripe-theme)

**Comment by hailwood** [comment]
> I'd pay someone to develop a mobile theme for Nova.

@noahlocke I'd pay for a product that had a mobile theme

**Comment by GuidoHendriks** [comment]
Why so salty? Feature has been requested. Don’t buy it if you don’t want it without responsiveness. And if you already bought it, they offer a refund within 15 days.

**Comment by zeroseed** [comment]
@GuidoHendriks hi actually i requested for refund within 5 days as nova term (email to taylor)
but till now not yet refunded. 
🙁

**Comment by gregoriohc** [comment]
I have made a simple theme to make Nova responsive:
https://github.com/gregoriohc/laravel-nova-theme-responsive
Maybe it's not perfect, but it's a beginning....

**Comment by nlenkowski** [comment]
I've been a Backpack user for awhile. I'm giving Nova a go on a new client project to see how it compares. As much as I'm loving Nova I have to admit I was bummed to find it's not responsive out of the box. The responsive theme by @gregoriohc is working well (👍), but clearly an official theme is needed.

**Comment by ibakhsh** [comment]
@gregoriohc amazing Thank you!! although i would love to know if it has an option to show the desktop version?

**Comment by indigoram89** [comment]
+1
