### ISSUE TITLE
Nova doesn't render number zero in a Number-field

### ISSUE THREAD

**Issue by carnevalle** [laravel/nova-issues#500]
Nova Version: 1.0.14

When saving a zero (0) in the Number-field it shows the field in the UI as if it had no input - even though the value in the database is indeed zero (0)

<img width="975" alt="skaermbillede 2018-09-09 kl 23 05 39" src="https://user-images.githubusercontent.com/54747/45268942-f1c98a00-b484-11e8-911c-9b4edff6609f.png">
<img width="457" alt="skaermbillede 2018-09-09 kl 23 05 49" src="https://user-images.githubusercontent.com/54747/45268943-f1c98a00-b484-11e8-8d83-3f8ab5cb0a97.png">

**Comment by ErwanGuillon** [comment]
It seems to be linked to #278. Same kind of issue.

**Comment by jameslkingsley** [comment]
Probably a situation where it's doing `if ($value) { populate field ... }` so `0` is causing it to not fall into the `if`.

**Comment by AegirLeet** [comment]
https://github.com/laravel/nova-js/blob/master/src/mixins/FormField.js#L31-L33

Any "falsy" value, including 0, will be replaced with an empty string.
Maybe explicitly check for undefined/null instead?

**Comment by ovvessem** [comment]
This (only) works if you have the database field type defined as VARCHAR or have the model field casted to a string instead of a (TINY)INTEGER.

**Comment by satoved** [comment]
Can confirm @jsphpl , pretty critical

**Comment by dillingham** [comment]
confirmed / reproduced | related https://github.com/laravel/nova-issues/issues/562 https://github.com/laravel/nova-issues/issues/840 https://github.com/laravel/nova-issues/issues/500 https://github.com/laravel/nova-issues/issues/122 https://github.com/laravel/nova-issues/issues/951
