### ISSUE TITLE
Nova 4 - Missing Localizations/Translations for Buttons, Alerts if dynamic locale is used to set the language

### ISSUE THREAD

**Issue by SionaFernandes** [laravel/nova-issues#5003]
- Laravel Version: ^8.0
- Nova Version: 4.18.0 
- PHP Version: ^7.3|^8.0

### Description:
The Nova Buttons , Message Alerts does not take translations 
The keys have been added in the json files , but it still does not show correctly

<img width="1139" alt="Screenshot 2022-11-02 at 2 54 20 PM" src="https://user-images.githubusercontent.com/51289294/199458691-ad05e2af-b7cd-4ef7-b789-2062008fbf82.png">

<img width="1145" alt="Screenshot 2022-11-02 at 2 54 37 PM" src="https://user-images.githubusercontent.com/51289294/199458941-a607db97-ef42-46f4-9aaa-46d294643236.png">

**Comment by crynobone** [comment]
We seen this issue a few times and no one has able to provide a reproducing code. AFAIK this issue can be avoided by not using `__()` before locale has been finalised. For application where locale is set based on session this normally occur via middleware.

Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by SionaFernandes** [comment]
Thank you for the quick reply . 
It does seem to not work if `__()` before locale has been finalised

Setting the locale according to user language seems to break it as well - 
Taken from https://laracasts.com/discuss/channels/nova/force-nova-to-use-another-locale
` Nova::serving(function (ServingNova $event) {
            if(Auth::user()){
                app()->setLocale(Auth::user()->language);
            }
            else{
                app()->setLocale('en');
            }
        });
`

Is there a way to set the nova locale based on user language ? 
Thanks

**Comment by crynobone** [comment]
```php
Nova::serving(function (ServingNova $event) { if(Auth::user()){ app()->setLocale(Auth::user()->language); } else{ app()->setLocale('en'); } });
```

This set the locale under middleware, now you need to make sure there no `__()` called before the middleware.
