### ISSUE TITLE
Trix field colors in dark mode

### ISSUE THREAD

**Issue by dmason30** [laravel/nova-issues#5004]
- Nova Version: 4.18.0

Seems this changed in 4.16.0...

### Code:
```php
Trix::make(__('Message'))->default('...')
    ->stacked()
    ->readonly(),
```

### Dark mode
![image](https://user-images.githubusercontent.com/20278756/199496468-1fd0b73f-8845-4346-b379-10189d3786db.png)

### Light Mode
![image](https://user-images.githubusercontent.com/20278756/199496551-e432642c-9e71-4677-b589-5e279e1a9187.png)

**Comment by juse-less** [comment]
There has been a few issues around the Trix field.

Have a look at my [comment here](https://github.com/laravel/nova-issues/issues/4927#issuecomment-1279734334), and, more importantly, follow the links.
As far as I'm aware, there's no real fix for it. 🙁

**Comment by dmason30** [comment]
> There has been a few issues around the Trix field.
> 
> Have a look at my [comment here](https://github.com/laravel/nova-issues/issues/4927#issuecomment-1279734334), and, more importantly, follow the links. As far as I'm aware, there's no real fix for it. 🙁

Yes fair enough, but in 4.15.2 this field displayed at least so you could read it, whatever changed in 4.16.0 seems to have make it unreadable. 

I don't know why we are using a Trix field to render some html when we could probably do it with the Text or Heading field so I will change it to one of those as it is always read only anyway.

**Comment by wamesro** [comment]
https://github.com/laravel/nova-issues/discussions/3955#discussioncomment-2958253
