### ISSUE TITLE
Panel only showing when viewing content.

### ISSUE THREAD

**Issue by kentsigurdsen** [laravel/nova-issues#501]
Hello. 

I have created panels for nicer views when viewing the contant. 

However the content will not show with panels when creating. Can this be fixed?

**Comment by fhusquinet** [comment]
This is the expected behaviour according to the documentation. I would also like to have that possibility when creating/editing a resource.

**Comment by bonzai** [comment]
#29

**Comment by dillingham** [comment]
https://github.com/laravel/nova-issues/issues/338

**Comment by davidhemphill** [comment]
Duplicate of #29
