### ISSUE TITLE
DependsOn issue after 4.12

### ISSUE THREAD

**Issue by dmitov** [laravel/nova-issues#5010]
- Laravel Version: 9.38.0
- Nova Version: 4.12.14 ~ 4.18.2
- PHP Version: 8.1.11
- Database Driver & Version: MariaDB 10.8.3
- Operating System and Version: MacOS 12.6
- Browser type and version: Chrome/Safari latest versions
- Reproduction Repository: -

### Description:
After version 4.12.14, dependant visibility fields are hidden after loading the page. 

### Detailed steps to reproduce the issue on a fresh Nova installation:
Create a dependant field like so:
```
Select::make('Destination', 'destination')->options([
    'office' => 'Office',
    'address' => 'Address',
    'store' => 'Store',
])->displayUsingLabels(),

Text::make('Office', 'office')
    ->hide()
    ->rules('sometimes')
    ->dependsOn('destination', function (Text $field, NovaRequest $request, FormData $formData) {
        if ($formData->destination === 'office') {
            $field->show();
            $field->rules('required');
        }
    }),
```

Nova 4.12.14 works as expected. Every other version up flickers and hides the field after load. Removing the if statement and the `hide()` from the field is not working either. As soon as you add `dependsOn` things go sideways, even if it's empty one.

I'd be willing to take a look why this is happening if someone can guide me where to look at.

**Comment by crynobone** [comment]
I don't think I able to follow what's not working based on the current description. Based on the code example which is similar to our dusk tests, this usage is currently working as expected.

Could you please properly described the current behaviour and expected behaviour based on your use case.

**Comment by crynobone** [comment]
Based on 4.13.0 changelog, if the Text field goes completely hidden after first `Select` changes then that's a clear indication you still on an outdated assets. Running `php artisan nova:publish` should fixed the issue.

**Comment by dmitov** [comment]
@crynobone Yes, this fixed the issue - much appreciated!
