### ISSUE TITLE
Login form goes to /nova instead of my project /

### ISSUE THREAD

**Issue by exwizzard** [laravel/nova-issues#502]
Steps to reproduce:

1. Go to /nova/login and login then logout
2. Go to /login and try to login and you are redirected to /nova instead of /

It works the other way around as well. If I logout on my app and go to /nova/login I will be redirected to / instead of /nova after login.

**Comment by davidhemphill** [comment]
Please post some code demonstrating the bug. Login/logout works for thousands of other people, so if there's an issue, please provide a way we can diagnose it.

**Comment by exwizzard** [comment]
@davidhemphill Login/logout works absolutely fine, the problem is where it takes you after you perform the login.

I tested this on a brand new installation of laravel and nova with make:auth, I can make a private repo if you want since it includes nova but you can test it yourself on your own install as well.

**Comment by cloudstudio** [comment]
@davidhemphill  login is working for thousands of other people sure, i have 

protected $redirectTo = '/mypage'; and nova ingnore it, and redirect to /nova.

same for RegisterController.php not working for now, is any chance to disable nova auth ?

thanks in advance
