### ISSUE TITLE
nova:theme is not documented

### ISSUE THREAD

**Issue by CraigHarley** [laravel/nova-issues#503]
I've generated a theme using: https://novathemes.beyondco.de/

And replaced the output of `php artisan nova:theme` with that output, but there's no documentation on how to register the theme and I can't see it done on another issue.

Can anybody help?

**Comment by peanut24** [comment]
Have you added the theme and repository to your composer.json? The nova:theme command asks if it should add these.

The theme's service provider then serves the styles in the ThemeServiceProvider's boot method.

**Comment by CraigHarley** [comment]
So if anyone is stuck, you need to add the `ThemeServiceProvider` to the providers in `config/app.php`. And make sure it's auto-loadable.

Documentation should be added for this.

**Comment by davidhemphill** [comment]
`ThemeServiceProvider` will be loaded automatically when you choose to add them to your `composer.json`. Otherwise, it's just like any other composer path repo, if it's not added to your `composer.json`, it won't be loaded.

**Comment by dniccum** [comment]
Unfortunately the theme is not loading for me. The application is returning a 500 error the link to my theme:

```
/nova-api/styles/grease-monkey-nova-theme
```

I can verify that it has been loaded to my composer.json, and I am running version 1.1.4

**Comment by dniccum** [comment]
I was able to confirm that the resource path within `ThemeServiceProvider.php` that is auto-generated is incorrect. This is what is generated:

```php
Nova::serving(function (ServingNova $event) {
    Nova::style('grease-monkey-nova-theme', __DIR__.'/../resources/css/theme.css');
});
```

This is what **SHOULD** be generated:

```php
Nova::serving(function (ServingNova $event) {
    Nova::style('grease-monkey-nova-theme', __DIR__.'/../css/theme.css');
});
```

**Comment by cerw** [comment]
This is not working for me either.

**Comment by chescos** [comment]
I still can't find the documentation for this command, am I missing something or why has this issue been closed?

**Comment by jasperf** [comment]
@chescos Do not think it is documented yet. Do hope soon. But in the meanwhile you can watch the basics here https://laracasts.com/series/laravel-nova-mastery/episodes/15

**Comment by mariuscrisan** [comment]
My solution for implementing a local custom theme was to inject the styles and the scripts in `NovaServiceProvider` like so:

```
use Laravel\Nova\Events\ServingNova;

...

public function boot()
{
    parent::boot();

    Nova::serving(function (ServingNova $event) {
        Nova::style('custom', resource_path('css/custom.css'));
        Nova::script('custom', resource_path('js/custom.js'));
    });
}
```

Then simply do your customizations in `resources/css/custom.css` and `resources/js/custom.js`

I hope some of you might find this helpful 😃

**Comment by markrassamni** [comment]
Here are the steps I followed to get a theme working.
1. `php artisan nova:theme maintainer/theme-name`
2. Enter `yes` when asked if you would like to update your Composer packages.
3. Edit the theme as you like at nova-components/ThemeName/resources/css/theme.css
4. `php artisan vendor:publish`. It will present you a numbered list of assets in your project that are publishable. Enter the number corresponding to the service providor for your theme. It should look something like this and you would enter `23`.
>[23] Provider: Maintainer\ThemeName\ThemeServiceProvider

Reload your site and the theme should now be applied.

**Comment by hakanxemik** [comment]
> I was able to confirm that the resource path within `ThemeServiceProvider.php` that is auto-generated is incorrect. This is what is generated:
> 
> ```
> Nova::serving(function (ServingNova $event) {
>     Nova::style('grease-monkey-nova-theme', __DIR__.'/../resources/css/theme.css');
> });
> ```
> 
> This is what **SHOULD** be generated:
> 
> ```
> Nova::serving(function (ServingNova $event) {
>     Nova::style('grease-monkey-nova-theme', __DIR__.'/../css/theme.css');
> });
> ```

This fixed my problem too. The auto-generated ThemeServiceProvider had the same mistake! Thanks for the solution 👍
