### ISSUE TITLE
`displayUsing` not working

### ISSUE THREAD

**Issue by atymic** [laravel/nova-issues#5039]
- Laravel Version: 9
- Nova Version: 4.18.2
- PHP Version: 8.1
- Database Driver & Version:

### Description:
When using `displayUsing` with a select field, I don't see the text returned from the `displayUsing` callback.  The text is returned to the browser in the `displayedAs` field, but isn't actually shown on the detail or list views. 
I can get the correct displayed text by using `resolveUsing` but this then breaks the selection logic.

Have updated to latest nova and republised assets.

![Screen Shot 2022-11-10 at 20 30 18](https://user-images.githubusercontent.com/50683531/201053382-f6e1de40-61b2-458a-82ed-345aa0ed0eb3.png)

Thanks!

**Comment by atymic** [comment]
Interesting, I will make a repro repo. I recompiled for dev mode to debug, which fixed the issue so I'm guessing it's something wonky in the JS. it also borked the css a bit 
![Screen Shot 2022-11-12 at 09 26 56](https://user-images.githubusercontent.com/50683531/201439434-3e4e6b26-a70f-456b-8cb8-e86b9c7b1383.png)
![Screen Shot 2022-11-12 at 09 28 03](https://user-images.githubusercontent.com/50683531/201439466-650b1e88-6a34-4703-8a39-1fde4eb3faae.png)

**Comment by atymic** [comment]
Okay, so I found the issue. Running `php artisan nova:publish` doesn't seem to correctly deal with the existing version of the files in `public/vendor/nova`. Using the git history, I have repro'd the issue

- Run `php artisan nova:publish` as per docs to publish new assets
- Note that the issue persists
- Run  `rm -rf public/vendor/nova` and then `php artisan nova:publish`
- Issue is fixed, new files are published which must contain the fix

Not sure if this is specific to me or a general bug 🤔

**Comment by crynobone** [comment]
It could be a 3rd party replacing default Vue Component and causing this issue on that specific app.
