### ISSUE TITLE
Please add a detailed changelog to releases

### ISSUE THREAD

**Issue by weeman1337** [laravel/nova-issues#504]
In the current Nova release notes I often find a

> Various bug fixes.

Maybe my project waits for a specific bug fix.
It would be really nice to know which bugs are fixed. Thanks :)

**Comment by Andy-Baker** [comment]
100% agreed - would love to see the granular changelog.

**Comment by happyDemon** [comment]
Agreed, the current format would only make sense if we could see into the commit history

**Comment by davidhemphill** [comment]
We're starting to do smaller releases and being more descriptive with our release notes. Thanks!

**Comment by RicardoRamirezR** [comment]
```git diff```
