### ISSUE TITLE
[4.18.0] Casted array attributes are not persisted when using dot notation

### ISSUE THREAD

**Issue by smoothie** [laravel/nova-issues#5042]
- Laravel Version: 9.39.0
- Nova Version: 4.18.2 (4.18.1, 4.18.0)
- PHP Version: 8.1.0
- Database Driver & Version: MySQL v8.0.27
- Operating System and Version: ---
- Browser type and version: ---
- Reproduction Repository: ---

### Description:
Follow up from #5005.

Fields (eg. Text, KeyValue, Boolean) are no longer persisted, nor validated (using rules), when we using dot notations.

Sidenote:
- It seems that at some point the dot notations are translated into snake case.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Let's assume:
1. We need a model with an array attribute. Let's assume the model to be `Partner::class` with a JSON column called `settings`.
2. In a Nova resource we then set specific fields on this setting:
  - `Boolean::make('Active', 'settings.notifications.active'),`
  - `KeyValue::make('Message Types', 'settings.notifications.messageTypes'),`
  - I haven't tested all fields but I'm at least aware that Text, has the very same issue.
3. When creating or updating a partners setting, the settings are empty.
  - And when a field is used in combination with rules, it always fails.
  - When using fillUsing:
    -  The request does not hold the related attribute (eg. `settings.notifications.messageTypes`)
    -  But it has `settings_notifications_messageTypes`.
    - Using fillUsing and manually setting the value could be a tmp workaround.

**Comment by crynobone** [comment]
The fix for #5005 was pushed 8 days ago and yet to be released. Please wait for upcoming release to get it.
