### ISSUE TITLE
Using setValue on field definition breaks the chain

### ISSUE THREAD

**Issue by sentq** [laravel/nova-issues#5043]
- Laravel Version: 9.3.10
- Nova Version: 4.18.2
- PHP Version: 8.1
- Database Driver & Version: MySQL
- Operating System and Version: macOS 12.6
- Browser type and version: Safari 16.1
- Reproduction Repository: https://github.com/###/###

### Description:
When I try setting a value for a field using the `setValue` method, it would break the whole page, since this method isn't chain-able.

**Comment by crynobone** [comment]
The method was designed to be only within `dependsOn()` where it doesn't have to be chain-able. Feel free to submit a feature request.
