### ISSUE TITLE
No visible cursor in Markdown field when using the dark theme

### ISSUE THREAD

**Issue by sewid** [laravel/nova-issues#5047]
- Laravel Version: 9.38.0
- Nova Version: 4.18.2
- PHP Version: 8.1.11
- Database Driver & Version: mySQL
- Operating System and Version: macOS Ventura
- Browser type and version: Safari & Chrome

### Description:
<img width="707" alt="" src="https://user-images.githubusercontent.com/359766/201381565-25d057e4-322b-4973-8e9b-b52660704aac.png">

### Detailed steps to reproduce the issue on a fresh Nova installation:
Add a markdown field to a resource and switch to the dark theme. When you edit the resource, there is no visible cursor in the Markdown field (there is a cursor, but it is black on a very dark background, that's why it is not visible).

**Comment by FatimaMazhit** [comment]
I was also looking for that issue and researched a little bit. Hope it helps, in nova.css:1091 we have :
```
.CodeMirror-cursor {
  @apply dark:border-l-white;
}
```
Which actually sets correctly:
`--tw-border-opacity: 1;`

But CodeMirror doesn't use Tailwind --tw-border-opacity and in codemirror.css:46 :
```
.CodeMirror-cursor {
  border-left: 1px solid black;
  border-right: none;
  width: 0;
}
```
It works just by : 
`.dark .CodeMirror-cursor{
    border-left-color: white;
}` in nova.css.
