### ISSUE TITLE
Field BelongsTo, change display label?

### ISSUE THREAD

**Issue by exzib** [laravel/nova-issues#505]
Is it possible to change the display label on belongsto?

EX:
I have a transaction which has a sender and receiver.
https://puu.sh/BsCTG/c2e54cf8f3.png
https://puu.sh/BsCU8/89f923b9b3.png

            BelongsTo::make('User', 'receiver'),
            BelongsTo::make('User', 'sender')

This code successfully shows them both, but it does not differate between the sender and receiver, i'd like it to show "Sender", "Receiver" instead of "User", "User"

How is this possible?

**Comment by exzib** [comment]
BelongsTo::make('User2', 'receiver', 'App\Nova\User'), <- this worked.

**Comment by RaymondAtivie** [comment]
Solution from  @exzib worked. Please the documentation should be updated. It says nothing about this.

**Comment by dkulyk** [comment]
@RaymondAtivie https://nova.laravel.com/docs/1.0/resources/relationships.html#belongsto
![image](https://user-images.githubusercontent.com/370042/53268471-d67ad000-36ee-11e9-8d12-287606acc94c.png)
