### ISSUE TITLE
Scrolling in Markdown Field (Fullscreen Mode) not possible

### ISSUE THREAD

**Issue by sewid** [laravel/nova-issues#5059]
- Laravel Version: 9.38.0
- Nova Version: 4.18.2
- PHP Version: 8.1.11
- Database Driver & Version: mySQL
- Operating System and Version: macOS Ventura
- Browser type and version: Safari & Chrome
- Description:

### Description:
Scrolling is not possible when using the Nova Markdown field in fullscreen mode. If I have a long markdown text and switch to fullscreen view, scrolling (using the mouse wheel) is no longer possible.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Add a resource with a markdown field. Add some long content to the field. Open markdown editor in fullscreen and try to scroll.

**Comment by n0Sp00n** [comment]
I encountered many bugs that people report for that systems. Do you think this product is really worth it's money? I'm going to commit myself to a very serious project... I am not sure if I trust this product.

Can you share your overall feedback, please?
