### ISSUE TITLE
nova-kit/nova-packages-tool preventing installation of Nova 4.19.0 ?

### ISSUE THREAD

**Issue by vesper8** [laravel/nova-issues#5062]
I'm trying to install the new just-released Nova 4.19.0 and it won't stick.. latest I can get is 4.18.2

After manually specifying `^4.19.0` in my composer.json, I got some errors related to `nova-kit/nova-packages-tool`

Upon inspecting the composer.json inside `nova-kit/nova-packages-tool` I found this:

`"laravel/nova": ">=4.16.0 <4.19.0"`

Maybe I'm misreading but this constraint seems to be imcompatible with `4.19.0` ? It should be `>=4.16.0 <=4.19.0` instead of `>=4.16.0 <4.19.0` ? 

@crynobone

**Comment by taylorotwell** [comment]
Nova kit isn't an official Laravel package.
