### ISSUE TITLE
Nova Value Metrics negative value isn't formated.

### ISSUE THREAD

**Issue by exzib** [laravel/nova-issues#507]
https://puu.sh/BsEET/557d591fa3.png

**Comment by phuclh** [comment]
I use the value metric data, but when it displays the negative value, it put the value in the parentheses. Here is the result when it displays `-100`, looks like: `(100)`. How can I display exact negative value?

**Comment by jbrooksuk** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to #nova on Laravel's Discord or #nova on the Larachat Slack Channel.

**Comment by Grayda** [comment]
For anyone looking for an answer to this, you can call `->format()` on a value, like so:

```php
return $this->result('-1000')
          ->format('0,0.00');
```
