### ISSUE TITLE
Using method relatableQueryUsing(...) on BelongsTo field produces an error

### ISSUE THREAD

**Issue by kazak71** [laravel/nova-issues#5071]
- Laravel Version: #.#.#
- Nova Version: 4.19.0
- PHP Version: 8.1

### Description:
Thank you for your great Nova!

Acording to documentation I registered BelongTo field like this:
            BelongsTo::make('Operator', 'operator', 'App\Nova\Operator')
            ->onlyOnForms()
            ->relatableQueryUsing(function ($query) {
                $query->where('role', 1);
            }),
When I try to add new resource I recieve an error:
Method Laravel\Nova\Http\Requests\ResourceCreateOrAttachRequest::where does not exist.

On editing  resource I recieve error:
Method Laravel\Nova\Http\Requests\ResourceUpdateOrUpdateAttachedRequest::where does not exist.

Without using method relatableQueryUsing everything works properly.

Thanks in advance!

**Comment by crynobone** [comment]
In your case it should have been:

```php
use Illuminate\Database\Eloquent\Builder;
use Laravel\Nova\Fields\BelongsTo;
use Laravel\Nova\Http\Requests\NovaRequest;

BelongsTo::make('Operator', 'operator', 'App\Nova\Operator')
->onlyOnForms()
->relatableQueryUsing(function (NovaRequest $request, Builder $query) {
    $query->where('role', 1);
}),
```
