### ISSUE TITLE
Value metric tooltip and copyable not getting raw count value

### ISSUE THREAD

**Issue by dmason30** [laravel/nova-issues#5074]
- Nova Version: 4.19.0

### Description:
I have a value metric counting all rows for a model:
```php
public function calculate(NovaRequest $request)
{
    return $this->count($request, ExchangeRatesHistory::class)->copyable();
}
```

This renders like this:
![image](https://user-images.githubusercontent.com/20278756/202196989-1ce36814-55dd-404d-b31a-98741f6cb0fa.png)

❌ When you hover over the value the tooltip does not show the raw value (2111)
![image](https://user-images.githubusercontent.com/20278756/202197131-77cee7cd-c391-4be9-be88-ea2bce35225b.png)

❌ When you click to copy the value it puts `2.11k` expected it to put the raw value (2111)

**Comment by davidhemphill** [comment]
We're fixing this, but for now you can set the presentation of the tooltip (and the value that gets copied) by using the `tooltipFormat` method and passing a formatting string accepted by [Numbro.js](https://numbrojs.com)

**Comment by bkuhl** [comment]
Interesting to see what the copyable icon looks like.  I tried it on some text fields and it didn't show any kind of icon on the `detail` page.  Is it supposed to?

**Comment by dmason30** [comment]
> Interesting to see what the copyable icon looks like. I tried it on some text fields and it didn't show any kind of icon on the `detail` page. Is it supposed to?

<img width="640" alt="image" src="https://user-images.githubusercontent.com/20278756/214744868-94a8d929-ffea-43df-8163-75365a7525b6.png">
