### ISSUE TITLE
Remove Tag remove always the first of the list

### ISSUE THREAD

**Issue by oskobri** [laravel/nova-issues#5075]
- Laravel Version: 9.40.1
- Nova Version: 4.19.0
- PHP Version: 8.1
- Database Driver & Version: MYSQL 8
- Operating System and Version: MacOS 12.6
- Browser type and version: Chrome 107

### Description:
Hello,

When i click on the cross to delete a tag with the tag field, it's always the first one in the list that is removed, not the tag i clicked on.

https://user-images.githubusercontent.com/43296157/202201851-87a5d4a5-d34a-429c-adbd-f2e718746817.mov

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)


https://user-images.githubusercontent.com/172966/202360624-b4b6e123-ddd0-4b25-86d4-d33529390e6d.mp4

**Comment by oskobri** [comment]
I don't understand, you have exactly this issue in your video. You want to remove spark and this is nova that is removed not spark. (00:08)

**Comment by crynobone** [comment]
Sorry, just realized I missed the issue.

**Comment by oskobri** [comment]
Why was it closed ?

**Comment by davidhemphill** [comment]
Because this has been fixed and will be included in the next release. 👍
