### ISSUE TITLE
Field argument not supplied to dynamic relatableQuery method

### ISSUE THREAD

**Issue by wdelfuego** [laravel/nova-issues#5081]
- Laravel Version: 9.40.1
- Nova Version: 4.19.0
- PHP Version: 8.0.19

### Description:
I am trying to use the dynamic version of 'relatableQuery' to limit what Staff resources can be linked to a Flight resource.
The Flight resource has a BelongsTo `pilot` field (to `Staff::class`) and a HasMany `staff` field (also to `Staff::class`), which have access to different subsets of Staff resources (not all Staff can be a pilot), so I need to access the field details in the `relatableStaff` method in order to modulate the query properly for each field.

I have a `Flight::relatableStaff(NovaRequest $request, $query)` method that works, but doesn't distinguish between the two fields. According to this part of the documentation: https://nova.laravel.com/docs/4.0/resources/authorization.html#relationship-types it should be possible to add a third argument to the relatableStaff method so I can access the field context.

However, if I change the method signature to `Flight::relatableStaff(NovaRequest $request, $query, Field $field)` as prescribed by the documentation, I get the following error:
`Too few arguments to function App\Nova\Flight::relatableStaff(), 2 passed and exactly 3 expected`

Am I misunderstanding the documentation here or is the third Field argument never passed to the dynamic `relatable` method?

Thanks for your help!

**Comment by crynobone** [comment]
Hi, can you provide complete reproducing code instead of just method signature.

**Comment by wdelfuego** [comment]
Does this functionality work for you as described in the documentation, @crynobone?
If it does, I'll be happy to investigate further to see why this goes wrong in my case.

**Comment by wdelfuego** [comment]
In the meantime, I've found an elegant work-around for the issue.

For anyone interested; I've changed the BelongsTo relation target class from `Staff` to `Pilot` and made Pilot an almost empty subclass of Staff. 

`app/Pilot.php`:

    <?php
    
    namespace App;
    
    class Pilot extends Staff
    {    
    }

`app/Nova/Pilot.php`:

    <?php

    namespace App\Nova;

    use Laravel\Nova\Http\Requests\NovaRequest;

    class Pilot extends Staff
    {
        public static function relatableQuery(NovaRequest $request, $query)
        {
            return $query->where('can_pilot', 1);
        }
    }

This solution avoids the need for a `Flight::relatableStaff` method entirely, thus avoiding the issue where the third `Field` argument isn't supplied to the `relatable` method by Nova contrary to what documentation seems to indicate.

@crynobone Since Nova is responsible for calling that `relatableStaff` method, I'm convinced that the issue exists either in the Nova codebase or in its documentation, but I don't consider investigating that discrepancy my responsibility since Nova is not a FOSS project. Hope you understand, and I hope you can find and solve the issue.

Let me know if you have any questions about my specific project if you have reason to believe this is not a general issue within the Nova codebase.

**Comment by crynobone** [comment]
I asked for reproducing code to understand the structure of relationship and usage. Without that, how can I understand what's is wrong.

> Does this functionality work for you as described in the documentation

I can only assume at the moment without seeing your usage code.

**Comment by wdelfuego** [comment]
I think you misunderstand; the issue is not in my usage code, the issue is in the calling code which is Nova itself (or the documentation is incorrect).

Nova calls the "relatable" query; my code doesn't call it, only implement it. I see this method being called and it works as described in the documentation if I implement it with two methods. However the documentation also [states](https://nova.laravel.com/docs/4.0/resources/authorization.html#relationship-types) that you can add a third `Field` argument to it, but then the method is no longer being called correctly by Nova. So either there is a bug in Nova since it doesn't pass the third argument to the "relatable" query, or the documentation is incorrect. There is no code in my project that I could show you that causes that issue.

If you set up a project using a "relatable" query (for example, `relatableTeams`, like in the documentation) with three arguments, you should either see that it works as described or that the third argument is never passed to that "relatable" query. My guess is on the latter. If you have reason to believe otherwise, I'll be glad to investigate further. But I can't share my entire project and the error is in Nova code itself. I understand that it would be valuable to you to see this tested in a clean repo but since Nova is not a FOSS project I am not wiling to donate free development time to provide evidence for the issue. Hope you understand.

For anyone else running into this issue, my previous comment that was marked "off-topic" shows an elegant workaround/solution, not sure why it was marked as off-topic.

Thanks for your time and effort, @crynobone!

**Comment by crynobone** [comment]
> Nova calls the "relatable" query; my code doesn't call it, only implement it. I see this method being called and it works as described in the documentation if I implement it with two arguments. However the documentation also [states](https://nova.laravel.com/docs/4.0/resources/authorization.html#relationship-types) that you can add a third Field argument to it, but then the method is no longer being called correctly by Nova. 

All the Laravel Nova code related to dynamic "relatableQuery" explicitly sends 3 parameters, which is why I need **reproducing code** but until now has been ignored.

> So either there is a bug in Nova since it doesn't pass the third argument to the "relatable" query, or the documentation is incorrect. There is no code in my project that I could show you that causes that issue.

All usage that I know sends 3 parameters (reviewed twice), I cannot verify your usage without reproducing code. 

> For anyone else running into this issue, my previous comment that was marked "off-topic" shows an elegant workaround/solution, not sure why it was marked as off-topic.

This is a bug report and we need to make sure only relevant information regarding the issue is the priority.

**Comment by wdelfuego** [comment]
I understand. Since I have a good work-around for this issue and since Nova isn't FOSS, I won't be setting up a new repo for the sake of investigating this, but if you could point me to where I can find the Nova code that sends those 3 parameters to the dynamic relatable query I'll try to take a quick look and see if I can find out more.

**Comment by crynobone** [comment]
```
src/Fields/BelongsTo.php:340
src/Fields/BelongsToMany.php:215
src/Fields/MorphToMany:212
src/Fields/MorphTo.php:415
```

**Comment by wdelfuego** [comment]
Thanks, @crynobone. I did some digging and I'm beginning to suspect the issue is most probably being caused by an external package (specifically, `outl1ne/nova-multiselect-field`) that seems to call the dynamic "relatable" query wrongly.

It didn't at all occur to me that that was a possibility so I didn't inspect the stack trace carefully enough, but I absolutely should have. A lesson in humility.

If the cause turns out to be within Nova I'll get back to you with more details, but I don't think so. Thanks for confirming the documentation and for the pointers to Nova's implementation!
