### ISSUE TITLE
Copyable Email fields do not work on Index view

### ISSUE THREAD

**Issue by puzzledmonkey** [laravel/nova-issues#5090]
- Laravel Version: 9.40.1
- Nova Version: 4.19.2
- PHP Version: 8.1.6
- Database Driver & Version: -
- Operating System and Version: -
- Browser type and version: -
- Reproduction Repository: -

### Description:

Copyable Email fields fail when clicking the copy icon on the Index view. The Detail view is fine.

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Add a new resource with a copyable email field
2. Click copy on the Index view.
3. See the error in the console tools 'e is not a function'

On the detail view it works fine. It seems like the copy() method and CopyToClipboard mixin were perhaps left out of Index/EmailField.vue (they exist in Detail/EmailField.vue)

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by puzzledmonkey** [comment]
I'm not sure how you're unable to reproduce it, because it's very simple to reproduce. Are you sure you didn't copy it from the details view and/or already have it in your clipboard? If not - please make a screen recording showing it working, because it definitely does not work here.

https://github.com/puzzledmonkey/nova-email-bug

Try and copy the email from the Customers Index view. You'll get a console error and nothing copied (although the copy icon will turn into a green tick).
![image](https://user-images.githubusercontent.com/3913622/203073192-291b9f8e-4642-41f1-8e00-4ff866c08ead.png)

As I originally said - it's pretty clear the copy() method and CopyToClipboard mixin are missing from Index/EmailField.vue which would be very quick to verify.

**Comment by crynobone** [comment]
Apologies, not realizing was using `Text` in most of our dusk test.
