### ISSUE TITLE
dependsOn doesnt hide field in the details page

### ISSUE THREAD

**Issue by steks89** [laravel/nova-issues#5095]
- Laravel Version: 9.4
- Nova Version: 4.19
- PHP Version: 8.1

### Description:

dependsOn doesn't hide fields in the details page while the update page works fine.

I don't want to have to create hideFromDetail with the same logic as dependsOn.

**Comment by crynobone** [comment]
`dependsOn` is only for Form. Use `hideOnDetail()` for your use case.
