### ISSUE TITLE
Feature Request: Using VaporFile and VaporImage on standard hosting

### ISSUE THREAD

**Issue by bengravesdev** [laravel/nova-issues#5099]
I host my sites on Digital Ocean and deploy them using Forge.

It would be really nice to be able to use VaporFile and VaporImage to upload multigigabyte files directly to S3 regardless of whether they're hosted on Vapor.

I tried to use VaporFile but got a 404 in the console as it tried to find /vapor/signed-storage-url

**Comment by crynobone** [comment]
You need to depends on https://github.com/laravel/vapor-core
