### ISSUE TITLE
Upload Multiple Images / Files ?

### ISSUE THREAD

**Issue by zeroseed** [laravel/nova-issues#51]
Hi , it would be nice if we can upload such as files or images more than 1 , for example i have model Product and ProductImage , this is hasMany relationship, but i need to upload multiple images, how this became possible ? 

Thanks

**Comment by eullercdr** [comment]
Its will be great!

**Comment by thisprojectworks** [comment]
Currently this can be achieved with the [TRIX Field](https://nova.laravel.com/docs/1.0/resources/fields.html#field-types). 
What I did was change the css of the field to make it more user-fiendly and make the images smaller.
```
trix-editor{
  .attachment.attachment--preview{
    width:200px;
    margin: 5px;
  }
}

trix-toolbar{
  display:none;
}
```
It is not a standard solution, but it works perfectly and is fast!

**Comment by taylorotwell** [comment]
This repository is for tracking bugs. Feature requests may be emailed to Nova customer support.

**Comment by afrars** [comment]
![cascadia_pt126dc](https://user-images.githubusercontent.com/43031294/47132507-cfb3fa80-d2c1-11e8-9758-a903f491f728.jpg)

**Comment by 8108905** [comment]
Now Nova 4.20 can not support yet Now nova 4.20 can’t support it. Even laravel-admin supports such a basic problem. If you can, please give me a refund. The total of nova3 and nova4 is 299*2=698. Nova has never been officially used
