### ISSUE TITLE
Accessing resolved fields in an invokable

### ISSUE THREAD

**Issue by JapSeyz** [laravel/nova-issues#511]
When displaying a pivot-field through an invokable, is it possible to access other resolved fields?

I have an invokable that displays the pivot-field price, and in that field I'd like to access the pivotParent to get the currency.

Currently I have to do make an entirely new query, which I'd like to avoid, if it's possible to access the fields somehow.

```php
public function __invoke($request)
    {
        $currency = once(function () use ($request) {
            return $request->toQuery()->first()->pivot->pivotParent->currency;
        });

        return [
            Money::make('Price', $currency, 'price_in_cents'),
        ];
    }
```

**Comment by davidhemphill** [comment]
Pass it through the constructor?

**Comment by JapSeyz** [comment]
@davidhemphill 

I am not sure I follow.

I have this table:

| id | price | quantity | currency |
|----|-------|----------|----------|
| 1  | 100   | 1        | GBP      |
| 2  | 200   | 1        | SGD      |

and would like to display the *price* correctly formatted to the currency.

How would I go about getting the *currency* column when defining the Currency::make("Price") in Nova?
