### ISSUE TITLE
IndexEmptyDialog label no follow $label

### ISSUE THREAD

**Issue by yong9402211** [laravel/nova-issues#5117]
- Laravel Version: 9
- Nova Version: latest
### Description:
<img width="791" alt="Screenshot 2022-11-24 at 6 54 41 PM" src="https://user-images.githubusercontent.com/81783402/203766807-43113857-f136-4050-b778-086d671e4a2b.png">

```
    public static $label = 'revPlatform Statuses';
```
Case sensitive, 1st letter is lowercase, but force display uppercase at IndexEmptyDialog.

**Comment by davidhemphill** [comment]
There is no `label` property on resources. You need to override the `singularName` method on the resource to change it.
