### ISSUE TITLE
Adding this to a trix field, breaks prepared statements

### ISSUE THREAD

**Issue by LorenzoSapora** [laravel/nova-issues#5118]
- Fresh Nova4 install (possibly works on Nova3, too, untested)
- Create resource+model
- Add Trix field to resource
- Create new resource
- Type `"Blade"` into trix.
- Submit form
- Uhoh

**Comment by crynobone** [comment]
https://user-images.githubusercontent.com/172966/203898837-c09b5d93-b23e-4d43-a7c7-d1f3a7458cb8.mp4

Unable to replicate, please submit Bug report using the available template (fill in all the requested information) and reproducing steps.

**Comment by LorenzoSapora** [comment]
Interesting, I was able to replicate over multiple nova installs.. Must be a conflicting package. Will investigate further.
