### ISSUE TITLE
html in DefaultField HelpText Error

### ISSUE THREAD

**Issue by chrillep** [laravel/nova-issues#5119]
- Laravel Version: 9-41
- Nova Version: 4.19.3
- PHP Version: 8.1.12
- Database Driver & Version: mysql 8.0
- Operating System and Version: alpine
- Browser type and version: chrome 107.0.5304.110
- Reproduction Repository: https://github.com/###/###

### Description:
Happy friday! :) 
we used line breaks in the error helptext
since nova 4, the help error text cannot be displayed as html.
FirstError is not v-html
it would be nice if both HelpText and HelpText Error work the same
https://nova.laravel.com/docs/4.0/resources/fields.html#field-help-text

```vue
      <HelpText class="mt-2 help-text-error" v-if="showErrors && hasError">
        {{ firstError }}
      </HelpText>

      <HelpText
        class="help-text mt-2"
        v-if="shouldShowHelpText"
        v-html="field.helpText"
      />
```

### Detailed steps to reproduce the issue on a fresh Nova installation:
https://nova.laravel.com/docs/4.0/resources/validation.html#the-aftercreationvalidation-method
```php
/**
 * Handle any post-creation validation processing.
 *
 * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
 * @param  \Illuminate\Validation\Validator  $validator
 * @return void
 */
protected static function afterCreationValidation(NovaRequest $request, $validator)
{
    if ($this->somethingElseIsInvalid()) {
        $validator->errors()->add('field', 'Something is wrong with this field!<br/> somtheing else <br/>last but not least :)');
    }
}
```

**Comment by crynobone** [comment]
You can override the component if you need this:

![image](https://user-images.githubusercontent.com/172966/204115595-12fd29c9-5009-419d-bb45-245adb070226.png)

**Comment by chrillep** [comment]
cheers ty!
