### ISSUE TITLE
Validation error message remains during editing

### ISSUE THREAD

**Issue by bencomeau** [laravel/nova-issues#512]
## Version
1.0.14

## Description
Once a resource's field fails validation, the error message continues displaying even after successfully saving the resource.

## Steps to reproduce
Using the default `User` resource as an example:
- Select a user to edit
- In the *Email* field, enter an invalid email
- Click *Update & Continue Editing*
- The validation error message properly displays under the *Email* field
![screen shot 2018-09-10 at 10 22 10 am](https://user-images.githubusercontent.com/10427571/45313533-00935980-b4e4-11e8-87f4-cdc7c83ccdcb.png)
- Enter a valid email
- Click *Update & Continue Editing*
- Toaster displays success message, but the validation message is not cleared
![screen shot 2018-09-10 at 10 22 52 am](https://user-images.githubusercontent.com/10427571/45313553-0d17b200-b4e4-11e8-96da-76beb2170d30.png)

**Comment by rickmacgillis** [comment]
I have this same issue. I've tried passing an empty string to `$fail` and it stops the update. (Expected) Returning `null`, `true`, or an empty string doesn't clear the message, but it allows it to update, just like not returning any value.

**Comment by rickmacgillis** [comment]
Bump. It seems like an easy fix.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in an upcoming release.
