### ISSUE TITLE
HasOne not creating or updating records in the database

### ISSUE THREAD

**Issue by ejobity** [laravel/nova-issues#5125]
- Laravel Version: 9.41.0
- Nova Version: 4.19.3
- PHP Version: 8.1.2
- Database Driver & Version: mysql 8
- Operating System and Version: win10
- Browser type and version: chrome

### Description:

I have a USER table and a PROFILE table, with a one-to-one relationship. Profile table has a user_id foreign key.

I created a USER resource and a PROFILE resource and add all the fields for each resource.

In the USER resource, I have this code 

`HasOne::make('Profile'),`

and it creates this view in the USER resource

![image](https://user-images.githubusercontent.com/1079427/204411885-742bdd95-719e-4587-ae76-6b47a7c8c78a.png)

I then click on the button and it takes me to the resource for the profile to be created and I add the information into the fields.

![image](https://user-images.githubusercontent.com/1079427/204412128-f2256295-bbe1-4990-8343-26368b02194c.png)

when I add the data into the fields and click create a profile or update profile the fields come up empty. I also check the database and nothing is added.

![image](https://user-images.githubusercontent.com/1079427/204412268-6178228a-d8ff-4dac-87d2-c913e75e90ca.png)

Is this a bug or am I missing something in the code?

**Comment by crynobone** [comment]
We have this exact example on https://github.com/laravel/nova-dusk-suite and it's being used to run Nova's integration and dusk tests without any failure.

Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)
