### ISSUE TITLE
Markdown field: url + image button not working

### ISSUE THREAD

**Issue by Livijn** [laravel/nova-issues#5126]
- Laravel Version: v9.41.0
- Nova Version: 4.19.3
- PHP Version: Not relevant
- Database Driver & Version: Not relevant
- Operating System and Version: Not relevant
- Browser type and version: Chrome 107.0.5304.110
- Reproduction Repository: https://github.com/###/###

### Description:
After upgrading to Nova 4, I noticed that the Markdown field is not working properly. Whenever I press the image button or the URL button, the console throws an error:

```
TypeError: Cannot read properties of undefined (reading 'chunkSize')
    at et (codemirror.js:902:51)
    at mt (codemirror.js:1006:27)
    at Sa.replaceRange (codemirror.js:6190:14)
    at Proxy.insertBefore (MarkdownField.vue:222:20)
    at Proxy.image (MarkdownField.vue:306:14)
    at Proxy.callAction (MarkdownField.vue:236:30)
    at MarkdownField.vue:43:31
    at runtime-dom.esm-bundler.js:1482:16
    at nn (runtime-core.esm-bundler.js:155:22)
    at rn (runtime-core.esm-bundler.js:164:21)
```

### Detailed steps to reproduce the issue on a fresh Nova installation:
This is all that's added:

```php
Markdown::make('Text', 'body')
```

And I have made sure to run `php artisan nova:publish`.

**Comment by skrypnik-dzencode** [comment]
Hi.
Have the same issue (Markdown field and image) 
```
TypeError: Cannot read property 'chunkSize' of undefined
    at et (codemirror.js:902)
    at mt (codemirror.js:1006)
    at Sa.replaceRange (codemirror.js:6190)
    at Proxy.insertBefore (MarkdownField.vue:222)
    at Proxy.image (MarkdownField.vue:306)
    at Proxy.callAction (MarkdownField.vue:236)
    at MarkdownField.vue:43
    at runtime-dom.esm-bundler.js:1482
    at nn (runtime-core.esm-bundler.js:155)
    at rn (runtime-core.esm-bundler.js:164)
```
Any solutions?

**Comment by Livijn** [comment]
This is still an issue. Surprised more people hasn't experienced this.

**Comment by skrypnik-dzencode** [comment]
@Livijn 
Actually, you can use this feature but it's not comfortable: first - select (highlight) at least one symbol, then press the image button - and it works
![image](https://user-images.githubusercontent.com/65762454/214066703-562a52fc-c914-4e78-934d-f17fc8b14751.png)
![image](https://user-images.githubusercontent.com/65762454/214067221-b4256b44-3c48-43ca-ad63-2e1e35f76b03.png)

**Comment by Livijn** [comment]
@davidhemphill This is merely a work around, not a fix. Shouldn't be closed.

**Comment by crynobone** [comment]
We just merged a update to the markdown editor which will fixed this issue.

A bug report marked with bug and assigned is only closed when a fix has been merged.
