### ISSUE TITLE
Nova 4.18 introduced usability bug: View/update resource open in new tab is now impossible.

### ISSUE THREAD

**Issue by rderks88** [laravel/nova-issues#5129]
- Laravel Version: 8.12
- Nova Version: 4.19
- PHP Version: 8

### Description:
The "view resource" and "update resource" buttons within your "index view" (the little eye and pencil buttons) render as button tags since laravel nova 4.18. This removes the functionality to use ctrl to open the view / edit page on a new tab whilst staying on the index page. Besides being a common usability issue, below I'll describe how we used this "open in new tab".

### Usecase why this is important (for us)
Within our company we use complicated algorithms to analyse lots of resources. Anything that the algorithm has doubts about we show in an index view for a human to check on a daily basis. Workflow is opening all of them in a new tab, and fixing each one. When checked, close the tab. Sometimes the resource needs to be checked later and the user still wants to be able to close the tab.
If between checking each resource you have to go back to the index page, to check where you were, and then hopefully open the one that you should check next, takes a lot... a lot!... more time.

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Install nova 4.19 in a fresh nova project
2. Create one resource
3. Go to index page
4. Hold ctrl and click on view resource (it does not open in a new tab)

It is fixed after downgrading to Nova 4.17.

**Comment by rderks88** [comment]
Solution might be a feature request within Inertia to support intercepting button-tags. Which for now it only intercepts a-tags:
https://github.com/inertiajs/inertia/blob/5298add1abb76ab2478cd3f5df4753fcc9b9156d/packages/core/src/shouldIntercept.ts#L2

**Comment by lk77** [comment]
We have the exact same issue, users are not able to do ctl+clic anymore because, those actions are now buttons instead of links

**Comment by jonasbrenig** [comment]
We got the same issue, a fix would be great :-)

**Comment by matthewjumpsoffbuildings** [comment]
Same issue here, @davidhemphill will this be in an upcoming release?

**Comment by davidhemphill** [comment]
This is closed because we've merged a fix for this. Will be out in today's release.

**Comment by rderks88** [comment]
@davidhemphill thank you so much!
