### ISSUE TITLE
Some Heroicons are not rendered proper

### ISSUE THREAD

**Issue by scramatte** [laravel/nova-issues#5139]
- Laravel Version: 9.19
- Nova Version: 4.
- PHP Version: 8.0.2
- Database Driver & Version: Mysql
- ServerOperating System and Version: Linux Debian 11
- Browser type and version: Chrome 108.0.5359.94 on MacOS Big Sur

### Description:
Some Hero icons are rendered incorrectly such : calculator, fingerprint or cube 

Border color and fill  need to be fixed into Heroicons  .vue components . As you can see bellow. stroke should be set to "none" instead of "currentColor" and fill to "currentColor" instead of "#374151"

_HeroiconsOutlineCalculator.vue_
```
<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    stroke="currentColor"
    width="24"
    height="24"
  >
    <path
      fill="#374151"
      d="M9 6a1 1 0 000 2V6zm6 2a1 1 0 100-2v2zm-1 9a1 1 0 102 0h-2zm2-3a1 1 0 10-2 0h2zm-4 2a1 1 0 100 2v-2zm.01 2a1 1 0 100-2v2zM9 16a1 1 0 100 2v-2zm.01 2a1 1 0 100-2v2zM9 13a1 1 0 100 2v-2zm.01 2a1 1 0 100->
    />
  </svg>
</template>
```

_Examples of incorrect rendering_
 
![image](https://user-images.githubusercontent.com/188766/205963634-e987a7d8-16a0-45ab-9ab7-6fc11220cef3.png)
![image](https://user-images.githubusercontent.com/188766/205963847-c8d986bb-367b-43a6-ac2d-6792ab342bf9.png)
 
### Detailed steps to reproduce the issue on a fresh Nova installation:
Just install fresh nova and set menu icon as  calculator, fingerprint or cube  for example. I haven't got a la list of all incorrect icons.

**Comment by crynobone** [comment]
Fixed and will be part of the next release.

![silver-surfer test-NovaSite-IconsViewer(2)](https://user-images.githubusercontent.com/172966/206033161-1d4e9ba3-9727-4aba-aeba-76f2f1ac8825.png)

**Comment by scramatte** [comment]
Thank you
