### ISSUE TITLE
Currency field does not properly check value for 0.00.

### ISSUE THREAD

**Issue by rickmacgillis** [laravel/nova-issues#514]
In `Fields/Currency.php` the way the currency gets checked and formatted is the following line.

`return $value ? money_format($this->format ?? '%i', $value) : null;`

It makes it so `0.00` is dismissed as the same thing as null. To avoid that issue, use the following LOC.

`return !is_null($value) ? money_format($this->format ?? '%i', $value) : null;`

**Comment by rickmacgillis** [comment]
I'm unable to do a PR on this for obvious reasons, but this is as close as I can get to a PR. I'm hoping it'll get fixed in the next release, as this is an easy fix.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in an upcoming release.
