### ISSUE TITLE
PHP 8.2 is not supported 

### ISSUE THREAD

**Issue by astersnake** [laravel/nova-issues#5148]
- Laravel Version: 9.43
- Nova Version: 4.19
- PHP Version: 8.2

### Description:

The package is not compatible with PHP 8.2 because it has outdated dependencies, has `inertiajs/inertia-laravel`, for example.

``
    - laravel/nova[4.0.0, ..., 4.5.0] require inertiajs/inertia-laravel ^0.4.5|^0.5.2 -> found inertiajs/inertia-laravel[v0.4.5, v0.5.2, v0.5.3, v0.5.4] but it conflicts with your root composer.json require (^0.6.4).
``

### Detailed steps to reproduce the issue on a fresh Nova installation:

Create a new project with PHP 8.2

**Comment by crynobone** [comment]
`- laravel/nova[4.0.0, ..., 4.5.0] require inertiajs/inertia-laravel`

It seems your project is limited to Nova version `4.5.0`, or you didn't share enough information in order for us to debug the issue.

**Comment by astersnake** [comment]
@crynobone It's a [new Laravel](https://laravel.com/docs/9.x/installation) project with PHP version set at 8.2. 

Nova was installed following the [official documentation](https://nova.laravel.com/docs/4.0/installation.html).

No additional changes were made.

**- Reproduction repository:** https://github.com/astersnake/nova-php8.2

###  Log:

```bash
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - laravel/nova[4.5.1, ..., 4.12.13] require rap2hpoutre/fast-excel ^3.2 -> satisfiable by rap2hpoutre/fast-excel[v3.2.0].
    - laravel/nova[4.0.x-dev, ..., 4.19.4] require rap2hpoutre/fast-excel ^3.2|^4.1 -> satisfiable by rap2hpoutre/fast-excel[v3.2.0, v4.1.0].
    - rap2hpoutre/fast-excel v3.2.0 requires box/spout ^3 -> satisfiable by box/spout[v3.0.0, ..., v3.3.0].
    - rap2hpoutre/fast-excel v4.1.0 requires openspout/openspout ^3 -> satisfiable by openspout/openspout[v3.4.0, ..., 3.x-dev].
    - box/spout 3.1.x-dev is an alias of box/spout dev-master and thus requires it to be installed too.
    - laravel/nova[4.0.0, ..., 4.5.0] require inertiajs/inertia-laravel ^0.4.5|^0.5.2 -> satisfiable by inertiajs/inertia-laravel[v0.4.5, v0.5.2, v0.5.3, v0.5.4].
    - openspout/openspout[v3.4.0, ..., 3.x-dev] require php ~7.3.0 || ~7.4.0 || ~8.0.0 || ~8.1.0 -> your php version (8.2.0) does not satisfy that requirement.
    - box/spout[dev-master, v3.0.0, ..., v3.3.0] require ext-zip * -> it is missing from your system. Install or enable PHP's zip extension.
    - inertiajs/inertia-laravel v0.4.5 requires laravel/framework ^5.4|^6.0|^7.0|^8.0 -> found laravel/framework[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.19).
    - inertiajs/inertia-laravel[v0.5.2, ..., v0.6.3] require php ^7.2|~8.0.0|~8.1.0 -> your php version (8.2.0) does not satisfy that requirement.

```

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/206820623-c9daea1f-20d5-4e6a-978b-5eb22fdaeafb.png)

I can just run `composer update` without any issue on the reproduction repository.

**Comment by carestad** [comment]
This seems to be due to the `rap2hpoutre/fast-excel` dependency.

To be fair, `composer install` works fine for me on both 8.1 and 8.2, but it ends up using older and obsolete packages on 8.2 compared to 8.1.

If I run `composer up` on a 8.2 setup, composer does this:

```
  - Removing openspout/openspout (v3.7.4)
  - Locking box/spout (v3.3.0)
  - Downgrading rap2hpoutre/fast-excel (v4.1.0 => v3.2.0)
```

and switching back to PHP 8.1 and running `composer up` I get this:

```
  - Removing box/spout (v3.3.0)
  - Locking openspout/openspout (v3.7.4)
  - Upgrading rap2hpoutre/fast-excel (v3.2.0 => v4.1.0)
```

If Nova could allow the use of `v5.*` as well for `rap2hpoutre/fast-excel` then it shouldn't be a problem anymore. The PR for that change is here: https://github.com/rap2hpoutre/fast-excel/pull/294

**Comment by lptn** [comment]
A new major version of `rap2hpoutre/fast-excel` is released. There is no upgrade guide, but from the [diff](https://github.com/rap2hpoutre/fast-excel/compare/v4.1.0...v5.0.0)  it's seems like the package havent't changed API (but dropped PHP 7.3 and Laravel 5 support 😂)

**Comment by crynobone** [comment]
Support for `fast-excel` 5 will be available on the next release.
