### ISSUE TITLE
Select all items in Resource index ignores policy and displays trash icon

### ISSUE THREAD

**Issue by dm-pf** [laravel/nova-issues#5149]
- Laravel Version: 9.42.2
- Nova Version: 4.19.4
- PHP Version: 8.1.11
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:
With a Policy that doesn't allow `delete / forceDelete`: if you select all items in a Resource - Nova incorrectly displays the Trash bit icon on the right side of the table. The action is abviously not executed even if you try to remove the items - so that's good.

Good (this page - no trash icon):
![Screenshot 2022-12-09 at 22 04 01](https://user-images.githubusercontent.com/100700999/206795904-86e450e0-f2c6-449b-9a20-0e17d5b37319.png)

Bad (all - shows trash icon):
![Screenshot 2022-12-09 at 22 04 21](https://user-images.githubusercontent.com/100700999/206795924-558b9224-8b70-449c-964d-878f19a87091.png)

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Create a Policy that doesn't allow `delete` and `forceDelete`
2. Go to the Resource index
3. Click checkbox to "Select all"
4. Trash icon shows up (shouldn't)

**Comment by crynobone** [comment]
It doesn't ignore policy, even when you press delete it would validate against policy before deletion. 

This was designed to avoid applications from querying the whole resources and checking against policy (imagine you have thousands if not millions of records)

**Comment by yehudahkay** [comment]
The delete shouldn't display
