### ISSUE TITLE
Too many filters breaks layout

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#515]
![breaks](https://user-images.githubusercontent.com/29180903/45334747-1cc9e180-b54a-11e8-8070-e07056acdcef.png)

Maybe a scroll-able  dropdown would be good

**Comment by michaelchunn** [comment]
Similar is true with too many resources.  You are left at bottom of page and can't see the index for the resource selected unless you scroll up to top.

**Comment by DonDiegoAA** [comment]
> Similar is true with too many resources. You are left at bottom of page and can't see the index for the resource selected unless you scroll up to top.

For this issue, this package can help
[https://novapackages.com/packages/alexbowers/nova-categorise-resources](url)

**Comment by dillingham** [comment]
@alexbowers bug

**Comment by alexbowers** [comment]
Also, its weird how the header "FILTER" is showing many times. Whats the purpose of that header, have you named all of your filters that, or is that how it shows? (I haven't got filters in my nova apps yet)

**Comment by dillingham** [comment]
@alexbowers I just duplicated a filter named "filter" for demo purposes

**Comment by alexbowers** [comment]
Ah okay, thanks.

**Comment by alexbowers** [comment]
Perhaps if there are more than X filters, it should have 2 columns for the filters.

**Comment by dillingham** [comment]
Yeah! Could work. Was also thinking some js height calculations & scrolling might be useful

![scroll](https://user-images.githubusercontent.com/29180903/45972392-94e3dd00-c009-11e8-9c55-c7dfd42a88d5.png)

**Comment by davidhemphill** [comment]
Should have a solution to this in an upcoming release. It'll scroll the filter list so it doesn't get too tall.
