### ISSUE TITLE
Nova ignores namespaces when building resources links and labels on sidebar navigation

### ISSUE THREAD

**Issue by tonydotgit** [laravel/nova-issues#517]
Nova's resources navigation is not properly handling namespaced "resources".

Like this class:
```php
<?php

namespace App\Nova\Vehicle;

use App\Nova\Resource;

class Car extends Resource
{
}
...
```

If I have another Car class under a different namespace (per NDA I cannot share more details but we do have a Car class inside `Vehicle` and another one under `Transportation` namespace and we do expect to Nova to render them under a "mapped" route (like laravel.dev/nova/resources/vehicle/cars and laravel.dev/nova/resources/transportation/cars) but it doesn't. Nova register both under the same "label" (on resources sidebar) and route: Cars -> laravel.dev/nova/resources/cars

**Comment by bonzai** [comment]
#21

**Comment by TonnyORG** [comment]
This issue still persists on 1.0.15
