### ISSUE TITLE
actions on belongsToMany with duplicates

### ISSUE THREAD

**Issue by Evanslooten** [laravel/nova-issues#5174]
- Laravel Version: 9.44.0
- Nova Version: 4.19.5
- PHP Version: 8.1.5
- Database Driver & Version:
- Operating System and Version: Ubuntu 22.04
- Browser type and version: Chrome 108

### Description:

If when you define a belongsToMany relationship you specify a named pivot accessor using ->as('accessor'), Nova will be unable to read the relationship via this accessor, showing a cannot read property on null error.

![Attempt to read property on null](https://user-images.githubusercontent.com/4089602/208490193-d4f6b242-cc37-4288-807c-540c584686f7.png)

When removing the name accessor the ID text changes to the ID of the pivot row, and the action will proceed successfully. However, if you look at the call when selecting rows, it still adds the related model ID to the resources payload. This means the action will submit successfully but will load all pivot rows matching on the resource + related model IDs, not the specifically selected pivot row.

![Related Model still in use](https://user-images.githubusercontent.com/4089602/208491203-ab75dd60-f58c-4d51-b376-93755fd824ec.png)

If I remove the ID::make from the Nova resource for the related model and include ID::make within the belongsToMany field, the selection script successfully pulls in the correct resource IDs, but cannot process the action with the error "Sorry! You are not authorized to perform this action." despite a policy returning true for all actions on both models, and pivot, and despite the action working with the related model ID.

![Correct parameters I assume but no authorized](https://user-images.githubusercontent.com/4089602/208492505-15a91874-48cc-4ace-9708-24a8e28ba238.png)

![Sorry](https://user-images.githubusercontent.com/4089602/208494151-8bff2699-d150-4595-8199-918385ee8e12.png)

### Code Samples
**Nova Resource BelongsToMany definition**
```php
BelongsToMany::make(__('Locations'),'location', '\App\Nova\Location')
                ->allowDuplicateRelations()
                ->actions(function() {
                    return [
                        Actions\MoveInventoryLocation::make()
                    ];
                })->referToPivotAs('Inventory')
                ->fields(function($request, $relatedModel) {
                    return [
                        ID::make(),
                        Number::make(__('Bed'), 'column'),
                        Number::make(__('Block Order'), 'order'),
                        Number::make(__('Width')),
                        Number::make(__('Length')),
                        Number::make(__('Block Quantity')),
                    ];
                }),
```

**BelongsToMany Laravel Model Definition**
```php
public function location() {
        return $this->belongsToMany(\App\Models\Inventory\Location::class)
            ->withPivot(
                'id',
                'order',
                'column',
                'width',
                'length',
                'block_quantity'
            )
            ->as('inLocation')
            ->using(InventoryLocation::class)
            ->withTimestamps();
    }
```

**Comment by Evanslooten** [comment]
Additionally, when using named accessors, editing the pivot relationship via the edit button on the row will load incorrect rows, possibly the first row for duplicates. Removing the ->as declaration allows editing as normal.

**Comment by crynobone** [comment]
I would suggest splitting up this issue to multiple small one to make it easier to understand the real issue and how to solve each one. From my understanding, the first screenshot refer to Action confirmation modal and "resource" or "pivot" information is not accessible by default.
