### ISSUE TITLE
[Request] Would it be possible to add previous value in metrics (not just change %)?

### ISSUE THREAD

**Issue by wfeller** [laravel/nova-issues#518]
I think it would be more explicit for most users if they could see the previous value instead of just "+200% increase"

Maybe something like this:
![image](https://user-images.githubusercontent.com/21337627/45348191-43b9ff00-b5ae-11e8-88aa-74497aa527c0.png)

**Comment by davidhemphill** [comment]
If you need changes to the default metrics, you can copy the code and create your own customized versions 👍
