### ISSUE TITLE
Partition labels customization bug

### ISSUE THREAD

**Issue by chimit** [laravel/nova-issues#5180]
- Laravel Version: 9.45.1
- Nova Version: 4.19.5
- PHP Version: 8.1.9
- Database Driver & Version: MySQL 8
- Reproduction repo: https://github.com/chimit/nova

### Description:

The [example](https://nova.laravel.com/docs/4.0/metrics/defining-metrics.html#customizing-partition-labels) with customized labels in the docs doesn't work as described:

```php
public function calculate(NovaRequest $request)
{
    return $this->count($request, User::class, 'stripe_plan')
            ->label(fn ($value) => match ($value) {
                null => 'None',
                default => ucfirst($value)
            });
}
```

The problem is that the "None" label is never displayed. You should set an empty string `''` to make it work instead even though the fields in the database are `NULL` and not empty strings:

```php
public function calculate(NovaRequest $request)
{
    return $this->count($request, User::class, 'stripe_plan')
            ->label(fn ($value) => match ($value) {
               '' => 'None',
                default => ucfirst($value)
            });
}
```

The same for booleans, none of this works:

```php
->label(fn ($value) => match ($value) {
    1 => 'Franchise',
    0 => 'Not franchise',
    default => ucfirst($value)
})
```
```php
->label(fn ($value) => match ($value) {
    '1' => 'Franchise',
    '0' => 'Not franchise',
    default => ucfirst($value)
})
```

<img width="202" alt="image" src="https://user-images.githubusercontent.com/839349/209059336-ffe1ce7c-ed5c-454a-937d-d9a8e343b0b3.png">

Model attribute casting is not taken into account so you can't use booleans as well:

```php
->label(fn ($value) => match ($value) {
    true => 'Franchise',
    false => 'Not franchise',
    default => ucfirst($value)
})
```

### Detailed steps to reproduce the issue on a fresh Nova installation:

Create a partition metric based on a boolean field or a nullable string field.

**Comment by crynobone** [comment]
Can you provide full reproducing code?

**Comment by chimit** [comment]
This bug is so obvious and easy to reproduce. I understand that a reproduction repo is needed for complex cases when you can't reproduce it by yourself but this one is not one of them.

Anyway, here is the repo: https://github.com/chimit/nova

<img width="633" alt="image" src="https://user-images.githubusercontent.com/839349/209104985-36b9226e-37bc-482d-876d-eb21d32c72f6.png">

<img width="633" alt="image" src="https://user-images.githubusercontent.com/839349/209105010-45e44905-6931-41a6-877d-97dc04e83bcc.png">

**Comment by crynobone** [comment]
> I understand that a reproduction repo is needed for complex cases when you can't reproduce it by yourself but this one is not one of them.

Reproduction repository is needed whenever:

- we not clear with the issue
- we may understand it but would need further information (sample data, video, image) to understand 
- whenever we fix something, it's actually solved the issue and not just because we assume it fixed the issue.
