### ISSUE TITLE
BelongsTo Field not populating data in select

### ISSUE THREAD

**Issue by jasonspick** [laravel/nova-issues#519]
I would assume that this field would contain all available options in the targeted relationship. Maybe I'm wrong and missing something.

`public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
            Text::make('name')->sortable(),
            BelongsTo::make('PrimaryLocation','PrimaryLocation','App\Nova\LocationGroups')->sortable()
        ];
    }`

`public function PrimaryLocation(){
            return $this->belongsTo('App\Models\Locations','primary_location_id','id');
        }
    /*`

The table is full. What am I missing?

**Comment by davidhemphill** [comment]
Please provide more code/context if you believe there's an issue.

**Comment by jasonspick** [comment]
I'm not sure how to provide more context. And that is all the code I have. On the LocationGroup resource page (create) there is a drop down called PrimaryLocation. It's drop down is empty. so I cannot select one. This is all the code I have. The first chunk is from the Nova resource file and the second from the LocationGroup model defining the relationship. What else can I show? the database is full. I should have options to choose from.

**Comment by ketanshah79** [comment]
I am having the same issue. The belongsto field in the edit form is not populated.

I have main entity called address and a related entity address_notes. address_notes belong to address. I have over 11000 address and the list will grow. 

Temporary workaround is that I've added exceptOnForms on the belongs to field to stop field from being rendered and hence the error. 

Assuming that the dropdown is trying to get all the addresses and hence breaking down. A select2 autocomplete dropdown might do the job here I think. 

![image](https://user-images.githubusercontent.com/119186/55307503-6130b680-5475-11e9-8f00-fa9e7aa0a9a4.png)

**Comment by Woeler** [comment]
I have exactly the same problem

**Comment by rvanbaalen** [comment]
I am having the same issue. Strange that this gets closed immediately while it just needs more context.

## Steps to reproduce:

1. Have a boat load of users (I have 50k users in my example)
2. Have a resource with a BelongsTo relation to a user
3. Edit that resource and the Max exec time error will show up and the dropdown to select users stays empty.

@davidhemphill please reopen and try to reproduce with the steps above.

**Comment by ketanshah79** [comment]
@davidhemphill - the least you can do is to reply 

@taylorotwell - we use laravel nova for a big client of ours. A good fix for select dropdown having tons of options is to use select 2. Autocomplete should ideally solve the issue.

With a paid subscription, I would expect the service to be a bit better. I am a bit disappointed with the lack of even an acknowledgement.

**Comment by rvanbaalen** [comment]
@ketanshah79 have you tried what I wrote above? Because the documentation clearly states how to handle these situations. 

RTFM; can’t blame ‘support’ if you don’t read the manual.

**Comment by ketanshah79** [comment]
Who are you? STFU !!!

Do you expect a user to scroll through thousands of drop down items to find
what they are looking for?

UX? familiar?

**Comment by Krato** [comment]
Why is this closed? Yes, with `searchable()` works. But if you want to use default select, BelongsTo field fails to select the default value.

**Comment by jbrooksuk** [comment]
I'm unable to confirm this issue in v2.7.1

![image](https://user-images.githubusercontent.com/246103/68863018-6d0c7880-06e6-11ea-8454-0b8275f8b076.png)

When editing a `Post`, which belongs to a `User`, I can clearly see the filled in relationships.

**Comment by dkulyk** [comment]
> @davidhemphill Why is this closed? Yes, with `searchable()` works. But if you want to use default select, BelongsTo field fails to select the default value.

You have a lot records for BelongsTo field.

**Comment by nielspeen** [comment]
Running into this with 2.10.1. (Some 40+K records.)

searchable() is a good solution, though ideally it would enable automatically when the number of records exceeds an X amount.

**Comment by jjelicDev** [comment]
_Laravel Nova version 3.23._
Hello, please open this issue. It is still not fixed. Here is why. 

Main issue was misunderstood. In example provided by @jasonspick , when you want to **create** main Resource (LocationGroup) you have Select field that is defined as BelongsTo (PrimaryLocation) and that Select field is **always empty**. There are rows in database for (PrimaryLocation), but the problem is that it isn't shown in Select field when you want to create main Resource. 

 **He is not talking about Resource update.**

Relationship between this tables is OneToMany, meaning that LocationGroup belongs to only one PrimaryLocation with database field 'primary_location_id'. And inverse is that PrimaryLocation can have zero or more LocationGroup(s).

My opinion is that BelongsTo relationship only looks for connected data, it doesn't allow you to have all PrimaryLocations from database when creating LocationGroup so you can assign a new LocationGroup. That is the issue.

I hope you follow me.
Please fix this.

**Comment by crynobone** [comment]
@jjelicDev if you have an issue create a new issue explaining your problem with complete code example. A lot has change since 3 years ago.
