### ISSUE TITLE
Can't Set Path to Root /

### ISSUE THREAD

**Issue by mdavis1982** [laravel/nova-issues#52]
Version: 1.0.5

**TL;DR**
When trying to set my path to `'/'` in the Nova config, I get:

```
No hint path defined for [nova].
```

**Expanded Explanation**
I have a situation where a CRUD based dashboard is basically our entire application. We're writing a management interface for some data that will be served up via an API to other products.

I want to set the root path of Nova to `'/'` so that our customer service people are greeted with the login form as soon as they go to the domain that Nova will be used on.

Is this possible and I'm just missing something?

Thanks 😄

**Comment by zachweix** [comment]
I don't have Nova and therefore I can't say for certain, but you can create a route in the routes file that redirects '/' to '/nova'

**Comment by mdavis1982** [comment]
@zachweix I could do that, for sure. But then I'd still have Nova in my URI.

**Comment by zachweix** [comment]
@mdavis1982 Well, from what it sounds like, you can have other words, in which case you can have it forward to '/app' or '/dashboard' or something else that looks good

**Comment by aios** [comment]
Can't change nova-api root routes

**Comment by taylorotwell** [comment]
Fixed.
