### ISSUE TITLE
Datetime field default(now()) stays blank

### ISSUE THREAD

**Issue by gepopp** [laravel/nova-issues#5200]
- Laravel Version: 9.44.0
- Nova Version: 4.19.5
- PHP Version: 8.2
- Database Driver & Version: mysql

### Description:
A DateTime field with a ->default( now() ) does not show a value when null.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Setup a DateTime Field like: 
```
 DateTime::make('E-Mail-Adresse bestätigt', 'email_verified_at')
                    ->default( now() )
                     ->required()
                    ->rules('required')
                    ->hideFromIndex()
                    ->hideFromDetail(),
```
is stay empty on creation.

**Comment by crynobone** [comment]
Unable to replicate:

#### Firefox

![image](https://user-images.githubusercontent.com/172966/210189708-1e5e325c-3a4d-47a4-81a8-18fb2c7858bb.png)

#### Chrome

![image](https://user-images.githubusercontent.com/172966/210189716-bb1aa244-3d5c-4bcd-9188-ab3689b070ea.png)

#### Edge

![image](https://user-images.githubusercontent.com/172966/210189726-0ad9f7c7-0c67-49a7-8694-a5377d358824.png)

#### Safari

![image](https://user-images.githubusercontent.com/172966/210189739-a9d508ec-f844-43d1-b65d-343a215b5095.png)

**Comment by gepopp** [comment]
@crynobone thx for trying, i tested it now on edge, chrome and firefox, it allways stays empty. 

I tried it on my Account model with a datetime field and with the "email_verified_at" field on the default users model. 

I also tried to change the timezone to UTC instead of europe/vienna, also stays empty.

Mby its something with the browser language, since it displays the datetime-local field with d.m.y instead of d/m/y in german but ive no clue how to test this...


![image](https://user-images.githubusercontent.com/2655976/210202554-55c9b4b3-4f63-4fec-bda0-af6e8ef4b161.png)

**Comment by crynobone** [comment]
> is stay empty on creation.

are you on the Create or Editing page?

**Comment by gepopp** [comment]
@crynobone i tried both, create and edit, with same result.
BTW if i save a date everything works perfect, its just de default(now()) now showing.

**Comment by gepopp** [comment]
@crynobone  I just switched the language of chrome to english and the app/config timezone to UTC,
it still stays empty, do you have any other idea?

![image](https://user-images.githubusercontent.com/2655976/210203176-905bfc8b-4440-44ab-b484-5b6a21017364.png)

**Comment by gepopp** [comment]
@crynobone im just playing arround, but mby i helps if i do ``` Carbon::setLocale('UTC') ``` before returning the fields in the nova resource it works.

```
 public function fields(NovaRequest $request)
    {

        Carbon::setlocale(config('UTC'));


        return [
            Text::make('Name')
                ->required()
                ->rules('string', 'required', 'max:255'),
            MorphOne::make('Logo', 'logo', 'App\Nova\Image')
                    ->required(),
            Email::make('Email')
                 ->required()
                 ->rules([ 'email', 'required' ]),
            DateTime::make('E-Mail-Adresse bestätigt', 'email_verified_at')
                    ->default(now())
                    ->required()
                    ->rules('required')
                    ->hideFromIndex()
                    ->hideFromDetail(),
            Text::make('Telefonnummer', 'phone')
                ->required()
                ->rules([ 'string', 'required', 'max:50' ]),
            URL::make('Website', 'url')
               ->nullable()
               ->rules([ 'nullable', 'url' ]),
            MorphOne::make('Adresse', 'address', 'App\Nova\Address')
                    ->required(),
            HasMany::make('Nutzer', 'users', 'App\Nova\User'),
        ];
    }
```

**Comment by crynobone** [comment]
> Mby its something with the browser language, since it displays the datetime-local field with d.m.y instead of d/m/y in german but ive no clue how to test this...

Irrelevant, the displayed format doesn't affect resolved format which will be the same regardless of locale. We are using `toIso8601String()` resolved format in `DateTime` field so locale shouldn't have any affect on this.

> i tried both, create and edit, with same result.

`display()` is only available on Create and not Editing.

**Comment by crynobone** [comment]
Okay, understand the issue now. Will work on a fix.
