### ISSUE TITLE
don't show column HasMany laravel nova

### ISSUE THREAD

**Issue by Mohammad-jawareesh-PS** [laravel/nova-issues#5207]
- Laravel Version: "^9.19"
- Nova Version: "~4.0"
- PHP Version: "^8.0.2"
- model movie
`    public function category_movie(){
        return $this-> belongsTo(Category_movie::class);
    }`
-model category 
`   public function category_movie(){
        return $this->belongsTo(Category_movie::class);
    }`
-model Category_movie
`    public function categorys(){
        return $this->hasMany(Category::class,'id');
    }
    public function movies(){
        return $this->hasMany(Movie::class,'id');
    }`

 Category_movie Resource

` ID::make()->sortable(),
        
            HasMany::make('category','categorys',Category_movie::class)->rules('required'),
            HasMany::make('movie','movies',Category_movie::class)->rules('required'),`

![Screenshot 2023-01-06 154320](https://user-images.githubusercontent.com/100040175/211024164-c1d5c600-1277-4bd6-8eb6-f4cc129da6f8.png)

**Comment by Mohammad-jawareesh-PS** [comment]
@davidhemphill

**Comment by davidhemphill** [comment]
@Mohammad-jawareesh-PS, please don't tag spam the maintainers. We have a process for handling issues, and they'll all be handled. Thanks!

**Comment by crynobone** [comment]
This doesn't contain any useful information for maintainers.
