### ISSUE TITLE
Localization Not Working with Some Words

### ISSUE THREAD

**Issue by Abather** [laravel/nova-issues#5209]
- Laravel Version: 9.54.1
- Nova Version: 4.19.5
- PHP Version: 8.1.10
- Operating System and Version: Windows 11
- Browser type and version: Firefox 108.0.2

### Description:
Some words not working probably the only way to make them work is by adding them into the main language JS file (for example: lang/ar.j) and they don't work on (lang/vendor/nova/ar.js),
the phrase that I face this issue with are:
- "Create :resource"
- "Cancel"
-  "Run Action"
- ":resource Details"
- ":resource Details :title"
- ":resource Details: :title"
 I'm facing this issue with two projects. and the only way solve is for me is by adding them to the main language file as i mention.

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)
