### ISSUE TITLE
Partition metric is not properly rendered when mobile and collapsed

### ISSUE THREAD

**Issue by tonyputi** [laravel/nova-issues#5211]
- Laravel Version: 9.19
- Nova Version: 4.19.6
- PHP Version: 8.1.13
- Database Driver & Version: MySQL 8.0 / MariaDB 10.0
- Operating System and Version: Ventura 13.1
- Browser type and version: 108.0.5359.124
- Reproduction Repository: https://github.com/###/###

### Description:
After refresh page Partition metric is not properly rendered when metric cards are collapsed by "Hide Cards" and then shown again.

![image](https://user-images.githubusercontent.com/8282385/211205105-0ec6e8c6-922f-402c-894c-3a76f9f5f799.png)

### Detailed steps to reproduce the issue on a fresh Nova installation:

- Create a resource and add a partition metric;
- Switch to mobile from your browser or your smartphone;
- Click on hide cards;
- Make a full page refresh;
- Wait that all the XHR request are done, especially the cards one;
- Click on show cards;
- Your partition metric should looks like the screenshot posted and the chartist pie is not properly shown;
![image](https://user-images.githubusercontent.com/8282385/211205276-7cdf277a-3400-4b48-9e2c-91f2cf858885.png)

I guess this is a chartist limitation but maybe a nova event can solve the issue asking chartist to re-render the chart on hide/show event

**Comment by crynobone** [comment]
https://user-images.githubusercontent.com/172966/211233964-a607f397-8fd4-494f-9c44-74c8ce6f034f.mp4

Unable to replicate the issue.

**Comment by filipposallemi** [comment]
You need to first hide then refresh and wait a few seconds so all the xhr calls are done and then you can click on show again
