### ISSUE TITLE
Resource's BelongsToMany::make()->fields() never being called

### ISSUE THREAD

**Issue by bkuhl** [laravel/nova-issues#5212]
- Laravel Version: 9.46.0
- Nova Version: 4.19.6
- PHP Version: 8.1.2
- Database Driver & Version: MySQL 8.0.3
- Operating System and Version: OSx 13.0.1 (22A400)
- Browser type and version: Chrome 108.0.5359.124 (Official Build) (arm64)
- Reproduction Repository: https://github.com/###/###

### Description:
I'm unable to get pivot fields to show up as expected on a `BelongsToMany` relationship on the Detail page for my `Guild` as described in [these docs](https://nova.laravel.com/docs/1.0/resources/relationships.html#pivot-fields).

**Message Eloquent Model**

```php
    public function guilds(): BelongsToMany
    {
        return $this->belongsToMany(Guild::class, 'guild_message')
            ->withPivot(
                'premium',
            );
    }
```

**Guild Eloquent Model**

```php
    public function messages(): BelongsToMany
    {
        return $this->belongsToMany(Message::class, 'guild_message')
            ->withPivot(
                'premium',
            );
    }
```

**Nova Guild Resource**

This does not resolve the Premium field at all.

```php
    BelongsToMany::make('Messages')
        ->onlyOnDetail()
        ->fields(function () {
            // Adding a dd() here I can prove this closure is never executed as the page loads successfully just without this field
            return [
                Boolean::make('Premium'),
            ];
        }),
```

The relevant ajax request URL (in case this at all helpful) is `/nova-api/messages/filters?viaResource=guilds&viaResourceId=1&viaRelationship=messages&relationshipType=belongsToMany`

I did find a workaround, which is to add the following to the `Nova/Message` resource:

```
    public function fields(NovaRequest $request)
    {
        return [
            Text::make('Type'),
            Boolean::make('Premium', 'pivot.premium'),
        ];
    }
```

### Detailed steps to reproduce the issue on a fresh Nova installation:

I did not try to recreate the issue on a fresh nova install.

**Comment by crynobone** [comment]
This feature are tested via our Dusk Test suite and doesn't experience what being described.

Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by bkuhl** [comment]
I don't have capacity to spin up a fresh Nova atm to test this further.  At the moment, the workaround is sufficient so I'll close the issue.
