### ISSUE TITLE
BelongsToMany pivot fields do not display when fieldsForCreate defined

### ISSUE THREAD

**Issue by rderks88** [laravel/nova-issues#5217]
- Laravel Version: 8.12
- Nova Version: 4.17
- PHP Version: 8.0
- Database Driver & Version: irrelevant
- Operating System and Version: irrelevant
- Browser type and version: Chrome
- Reproduction Repository: not available

### Description:
When you define pivot fields on a belongsToMany relationship, and that relationship is not included in fieldsForCreate (which would not make sense imo) the pivot fields do not display while trying to attach a new resource via the belongsToMany relationship.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Consider the following:

```
public function fields(NovaRequest $request)
    {
        return [
            BelongsToMany::make('Children')
                ->fields(function () {
                    return [
                        Boolean::make('Published')
                            ->default(true),
                    ];
                }), 
        ];
    }

 public function fieldsForCreate()
    {
        return [
            Text::make('Name'),
        ];
    }
```

While attaching the child you will not get a boolean to set the published attribute on the pivot model. When you add the belongsToMany relationship to fieldsForCreate, you will see it.

**Comment by crynobone** [comment]
This is an expected behaviour and we would be able to change it without introducing performance penalty and deprecating the use of thos dynamic methods

**Comment by rderks88** [comment]
Alright, I do not know Nova well enough to know that this was expected behaviour.
However, it took me quite some time to find out that these two functions were related.
Would you be willing to include it in the docs as a caveat? I can write it and submit a PR.

**Comment by mstaack** [comment]
Had the same issue and it took me a while to figure it out.
