### ISSUE TITLE
Email Verification Laravel 5.7

### ISSUE THREAD

**Issue by packytagliaferro** [laravel/nova-issues#523]
Laravel: 5.7
Nova: 1.0.14

I am using Nova just as the backend for a SAAS application so basically going to app.mydoain.com just pops up the Nova login form. I want Laravel 5.7 Email Verification that comes standard in use for this (so when I add a user they have to verify the email before the can login).

In `config/nova.php` I added the middleware:

```
 'middleware' => [
        'verified',
        'web',
        Authenticate::class,
        DispatchServingNovaEvent::class,
        BootTools::class,
        Authorize::class,
    ],
```

In `User.php` model I implemented it 

```
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Contracts\Auth\MustVerifyEmail;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

....
```
I added some routes in `web.php` for just verification (dont need any other auth)

```
Route::get('email/verify', 'Auth\VerificationController@show')->name('verification.notice');
Route::get('email/verify/{id}', 'Auth\VerificationController@verify')->name('verification.verify');
Route::get('email/resend', 'Auth\VerificationController@resend')->name('verification.resend');
```

and finally in the the `VerificationController.php`:

`protected $redirectTo = '/';`

After I login it just stalls out and either goes to `/email/verify` or `/`. In my db I have already added a timestamp for `email_verified_at` so it shouldn't go to `/email/verify` at all and when it goes to `/` it times-out (too many redirects).

If i remove verified from the middleware in the config it works fine, but no email verification check.

It seems like this should be an easy setup since Nova is an official Laravel package.

**Comment by haoyuguo** [comment]
I added 'verified' after 'web' middleware.  It seems to be working for me.

**Comment by haoyuguo** [comment]
@packytagliaferro 

Nova 1.0.15 I believe.  I did have to add `implements MustVerifyEmail` to User model.

**Comment by haoyuguo** [comment]
Actually I have a live system in development here https://cccon.us

**Comment by pehbehbeh** [comment]
We just implemented the verification feature as described in the docs. Works like a charm.

**Comment by packytagliaferro** [comment]
I will update Nova and check to see if I am getting some error on my side

**Comment by packytagliaferro** [comment]
These seems to be working now with v1.0.16.

**Comment by packytagliaferro** [comment]
Actually I am going to leave this open since it looks like @haoyuguo uses Laravel auth not just nova. The bug I am having is when I use Nova auth.

To reproduce:

Install Nova

Change config/nova to:

```

 'path' => '/',

'middleware' => [
        'verified',
        'web',
        Authenticate::class,
        DispatchServingNovaEvent::class,
        BootTools::class,
        Authorize::class,
    ],
```

Implement it on the user

`class User extends Authenticatable implements MustVerifyEmail
`

then add email verification routes

```
Route::get('email/verify', 'Auth\VerificationController@show')->name('verification.notice');
Route::get('email/verify/{id}', 'Auth\VerificationController@verify')->name('verification.verify');
Route::get('email/resend', 'Auth\VerificationController@resend')->name('verification.resend');
```

This blows it up. I assume its because the login form itself is being protected by `Verified` middleware. Again this is just using Nova stand alone, not Laravel Auth routes. I should be able to just add this and use the Nova login and logout routes as is and then just add the verification routes if the user tries to sign in via the Nova Login form and has not verified their email

**Comment by packytagliaferro** [comment]
@taylorotwell is email verification with just Nova routes in the new release? Or do I need to do my own auth or Laravel Auth to get this to work?  Just trying to figure out what I need to do and what I am doing wrong I guess.

**Comment by hguo-discovery** [comment]
My `nova.php`

'middleware' => [
        'web',
        'verified',
        ......
        Authorize::class,
    ],
