### ISSUE TITLE
Tables in dark mode even when app is in light mode

### ISSUE THREAD

**Issue by brain82** [laravel/nova-issues#5230]
- Laravel Version: 9.47.0
- Nova Version: 4.20.2
- PHP Version: 8.1

### Description:
I've just updated to the latest version of Nova and our table are displayed in dark mode when the app is in light mode.

![image](https://user-images.githubusercontent.com/6013683/212101581-b7d083b0-4b91-4a16-ab31-e20526e0cada.png)

**Comment by proilyxa** [comment]
I have the same problem. I think this library is to blame https://github.com/outl1ne/nova-sortable/issues/157

**Comment by brain82** [comment]
I do indeed @proilyxa. I didn't even suspect that library because the issue is happening on all tables and I only have the sorting feature on two or three tables.
