### ISSUE TITLE
Scrolling sideways on resource index on smaller screen broken since 4.17.0

### ISSUE THREAD

**Issue by ramonfeleus** [laravel/nova-issues#5238]
- Laravel Version: 9.47.0
- Nova Version: >=4.17.0
- PHP Version: 8.1
- Database Driver & Version: MariaDB 10.5.5
- Operating System and Version: MacOs Ventura 13.0.1
- Browser type and version:  Google Chrome 108.0.5359.124 and others.

### Description:
Open a Nova Resource index page on a smaller screen where all columns do not fit horizontally in the viewport(e.g. smartphone, tablet, small desktop). Attempt to scroll sideways to view the other columns and action buttons. Scrolling sideways won't work.
This happened after we've upgraded a an older site's nova version to the latest 4.20.2 version.
After downgrading nova to specific versions I found that it has been an issue since nova 4.17.0. 
It seems the precedence of css classes on the list is the problem:
<img width="676" alt="Scherm­afbeelding 2023-01-13 om 15 51 18" src="https://user-images.githubusercontent.com/73035608/212351228-91fcbc89-71ec-491f-a03e-e25b04ca4c18.png">
The `o1-overflow-hidden` class sets an `overflow: hidden`, disallowing all scrolling on the overview. While `o1-overflow-x-auto` should enable scrolling on the horizontal x-axis by setting `overflow-x: auto`. But the `o1-overflow-hidden` overrides `o1-overflow-x-auto`. In the screenshot you will see that `o1-overflow-hidden` appears twice in the css inheritance in the inspector, indicating it might be in the css twice.

When I set composer to nova 4.16.1 it works. This has different html classes which make sure the scrolling on the x-axis is enabled again after setting `overflow: hidden` on the overview.

<img width="679" alt="Scherm­afbeelding 2023-01-13 om 15 52 35" src="https://user-images.githubusercontent.com/73035608/212352773-661ac26e-6ae3-4771-98f9-c6eb30472112.png">

### Detailed steps to reproduce the issue on a fresh Nova installation:

- Upgrade to latests version or >= 4.17.0.
- Open index of resource with plenty of columns on a small screen, attempt to scroll horizontally to reveal other columns (no scrolling allowed).
- Downgrade nova to 4.16.1.
- Open index of resource with plenty of columns on a small screen, attempt to scroll horizontally to reveal other columns: scrolling works.

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/212526770-1beb54a1-a2b5-4ddc-b0d5-26fcd85c5b07.png)

I don't believe you are using `ResourceTable` component from Laravel Nova, it is possible you are using 3rd party package that overrides the table and causes this issue.

**Comment by ramonfeleus** [comment]
Apparently outl1ne/nova-menu-builder causes this. I'll take the issue there.

**Comment by ramonfeleus** [comment]
Fix has been released: https://github.com/outl1ne/nova-sortable/issues/158
