### ISSUE TITLE
Can't Delete Audio File (AudioField) on s3 (Digital Ocean Spaces)

### ISSUE THREAD

**Issue by henryavila** [laravel/nova-issues#5251]
- Laravel Version: 9.48.0
- Nova Version: 4.21.0 
- PHP Version: 8.2.1
- Reproduction Repository: https://github.com/henryavila/nova-issue/tree/cant-delete-audio-files

### Description:
When using [Audio Fields](https://nova.laravel.com/docs/4.0/resources/fields.html#audio-field) With S3 storage (Digital Ocean Sapces), the download functionality works, But I can't  delete the file.

The playback and download works for Audio and File Fields.
![image](https://user-images.githubusercontent.com/8429941/213487184-f7c6936b-6e9b-4465-9c29-6842b5aecccf.png)

But when I try to edit the Model to delete the file, the option to delete is displayed on FileField, but not on AudioField
![image](https://user-images.githubusercontent.com/8429941/213487645-412f1e31-6920-475b-8b85-2e9b46e49511.png)

My resource code is
```php
public function fields(NovaRequest $request)
	{
		return [

			...

			Audio::make('Arquivo de Áudio', 'audio_file')
				->disk('s3')
				->rules('nullable'),

			File::make('Arquivo de Cifra', 'pdf_file')
				->disk('s3')
				->rules('nullable'),
		];
	}
```

My filesystem has no customization
```php
's3' => [
    'driver' => 's3',
    'key' => env('AWS_ACCESS_KEY_ID'),
    'secret' => env('AWS_SECRET_ACCESS_KEY'),
    'region' => env('AWS_DEFAULT_REGION'),
    'bucket' => env('AWS_BUCKET'),
    'url' => env('AWS_URL'),
    'endpoint' => env('AWS_ENDPOINT'),
    'use_path_style_endpoint' => env('AWS_USE_PATH_STYLE_ENDPOINT', false),
    'throw' => false,
],
```

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Fresh install Laravel and Nova
- Create migration with files columns
- Add AudioField on resource
- Set disk to 's3' using Digital Ocean Spaces
- Upload a file
- Edit the resource to try to delete the file

**Comment by crynobone** [comment]
Unable to replicate the issue

**Comment by henryavila** [comment]
Hi @crynobone, did you clone https://github.com/henryavila/nova-issue/tree/cant-delete-audio-files `cant-delete-audio-files branch` and set up DO Spaces?

**Comment by crynobone** [comment]
> and set up DO Spaces?

I tested it with local Minio, using both `Audio::make()->disk('s3')` and `VaporAudio::make()` without any issue.

**Comment by henryavila** [comment]
As described on title, the file don't appear to delete (when editing resource) when using Digital Ocean Spaces. To reproduce the error, you will need to use Digital Ocean Spaces. I can provide an key to you to test, if you wish

**Comment by crynobone** [comment]
![image](https://user-images.githubusercontent.com/172966/215484383-4c228023-f38d-4d24-af71-732d7f8d048c.png)

Did you setup the CORS as described in DigitalOcean Spaces documentation? 

Minio and DigitalOcean Spaces both claim to be S3 API compliant and it should work the same.
