### ISSUE TITLE
File Field displayUsing() is not working when editing a model

### ISSUE THREAD

**Issue by henryavila** [laravel/nova-issues#5252]
-Laravel Version: 9.48.0
-Nova Version: 4.21.0
-PHP Version: 8.2.1

### Description:
The `->displayUsing()` on a File Field is used to display a friendly name instead of the full path and random file name:
![image](https://user-images.githubusercontent.com/8429941/213492948-44ef2d1a-c35f-4e27-9dc8-06a70bd23707.png)
and it works on Detail Page.

But when Editing an model, we have the possibility to remove an file, but in edit screen, The content of  `->displayUsing()` is not displayed, instead, the full path file is been displayed
![image](https://user-images.githubusercontent.com/8429941/213494197-1406fb4f-0f0a-4c69-afdb-a4791618d04c.png)

Some of the problems are:
- Expose the server path
- Expose the filename on server
- Is not User firendly
- Break the screen on mobile

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Edit an File Field wich has  `->displayUsing()`  defined

**Comment by crynobone** [comment]
https://nova.laravel.com/docs/4.0/resources/fields.html#field-resolution-formatting

as explained in the documentation, the usage only for "index" and "detail" page.
