### ISSUE TITLE
UI Bug: Delete Button is transparent

### ISSUE THREAD

**Issue by miagg** [laravel/nova-issues#5259]
- Laravel Version: 9.48
- Nova Version: 4.21.0
- PHP Version: 8.2
- Database Driver & Version:
- Operating System and Version: Mac OS Ventura 13.1
- Browser type and version: Chrome 109
- Reproduction Repository: private

### Description:
On a fresh nova installation the delete button on the modal is transparent. It seems that nova-toggle style is overriding the background color.

![bug](https://user-images.githubusercontent.com/6439071/213859002-d43d1549-7fe6-4510-a2bb-b9865ca5cbbd.gif)

### Detailed steps to reproduce the issue on a fresh Nova installation:
Click delete button on any resource.

**Comment by Jenry-MA** [comment]
Hi, this publish is very old, but i already fixed using Nova::style.

1. In your public path make new directory (if no exist) name "css" them make file .css
2. Put this code in the css file...

`button[type="button"].bg-primary-500 ,button[type="submit"].bg-primary-500 {`
    `background-color: #058080;`
`}`

`button[type="button"].bg-red-500 ,button[type="submit"].bg-red-500 {`
    `background-color: #ef4444;`
`}`

3. Add this code in you NovaServiceProvider, inside boot function `Nova::style('button',public_path('css/file.css'));`
4. And ready, you will have color in your buttons.
