### ISSUE TITLE
Relationship fields do not show custom names in Nova 1.0.15.

### ISSUE THREAD

**Issue by rickmacgillis** [laravel/nova-issues#526]
I've upgraded to Nova 1.0.15 and the custom names still don't show up for the numerous relationship fields on my resources. `HasMany` for instance is used quite liberally without it displaying the custom text for the resource.

```
BelongsToMany::make(__('Member of Teams'), 'teams', Team::class)
	           	->onlyOnDetail(),
           	
           	HasMany::make(__('Owned Teams'), 'ownedTeams', Team::class)
           		->onlyOnDetail(),
```
Both of these just say "Teams" for their name.

**Comment by victorpfm** [comment]
+1

**Comment by rickmacgillis** [comment]
Bumping as this seems like something obvious that got overlooked.

**Comment by nickels** [comment]
Hi @davidhemphill is this going to be included some time soon? Feature request has - presumably - been made, see #462. Thansk!

**Comment by amit-insense** [comment]
I am facing same , please fix it ! +1

**Comment by alexbowers** [comment]
@rickmacgillis Can you confirm this is still an issue on the latest release?

**Comment by bonzai** [comment]
@alexbowers: I can confirm that it's still an issue in 1.1.3.

**Comment by rickmacgillis** [comment]
@alexbowers Yes I can confirm it. The same code as in the OP produces the following display.

![image](https://user-images.githubusercontent.com/8941225/46094847-0eeea000-c189-11e8-8eaf-ff9a4002ef59.png)

I've done a `nova:publish`, too.

**Comment by rickmacgillis** [comment]
@davidhemphill That makes sense *as a work around* for smaller projects, but for larger projects with 25 `belongsToMany` and `hasMany` relationship fields and growing, that workaround doesn't make sense. It could *easily* double the number of resources, and even stored in a subdirectory, it still doesn't seem like a smart solution.

**Comment by davidhemphill** [comment]
@rickmacgillis Well, we're trying to use our brains here I assure you. 😄 I understand your situation for sure, and we're trying to make it as easy as possible, but there's just not a clear way on how we could allow for that, without creating a whole set of new bugs on the front-end.

**Comment by rickmacgillis** [comment]
@davidhemphill I see. I'll see if there's a way I can make a Nova Package for this as it seems to be quite a popular issue.

**Comment by dillingham** [comment]
@rickmacgillis, he literally just said otherwise. What solution do you have for us all? It’s not a question of if but how.

**Comment by rickmacgillis** [comment]
@dillingham I misread his message as not being willing to fix it because it would mess up the front end code. If you guys are fixing the code, I'd greatly appreciate it.

**Comment by dillingham** [comment]
@davidhemphill would `HasMany::make('Users', 'managers', User::class)->forceLabel('Managers');` be an possibility? Im trying to inspect for parts effected by labels but not super familiar with the wiring

**Comment by rickmacgillis** [comment]
@dillingham How would it be better than changing the constructor to modify the metadata for the view?

**Comment by davidhemphill** [comment]
> Presumably someone else will make one panel-based as Team Nova isn't interested in solving the problem in their source code.

Geez, comments like this really get us motivated!

In related news, we've discussed this more thoroughly and I think we've come up with a workable solution. Will know soon if it pans out.

**Comment by alexbowers** [comment]
@bonzai can you create a new issue detailing that, so that it doesn't get lost?

**Comment by dillingham** [comment]
The Choose <field name> is right just not the left column label

**Comment by davidhemphill** [comment]
Think we've wrapped up all the issues around this in the current release.

**Comment by umerhassan82** [comment]
As in ```BelongsTo``` class
```
public function __construct($name, $attribute = null, $resource = null)
```
it works for me  ```BelongsTo::make('Name', 'Method', 'Nova Resource'),```
