### ISSUE TITLE
The hide method doesn't work

### ISSUE THREAD

**Issue by gmarineau** [laravel/nova-issues#5268]
- Laravel Version: 9.48.0
- Nova Version: 4.21.0
- PHP Version: 8.1.14
- Database Driver & Version: MariaDb
- Operating System and Version: MacOS 13.1 (22C65)
- Browser type and version: Firefox 109.0
- Dev. server : Valet

### Description:

I'm trying to hide a field with the hide method, but it doesn't work and I don't get any console warnings or laravel errors.

If I try to hide a field without dependsOn condition it's the same result the field is still visible.

### Detailed steps to reproduce the issue on a fresh Nova installation:

This is the code in my resource :

```
Boolean::make('Reduce'),

Number::make('amount')
->hide()
->dependsOn(
    ['reduce'],
    function (Number $field, NovaRequest $request, FormData $formData) {
        if ($formData->reduce) {
            $field->show();
        } else {
            $field->hide();
        }
    }
),
```

**Comment by crynobone** [comment]
You can use `$formData->boolean('reduce')` here.

**Comment by gmarineau** [comment]
Sorry, my description of the bug is bad. In this simple example, I expect not to see the field in the form ? But I still see it. This is the bug.

`
Boolean::make('Test', 'test')
->hide(),
`

**Comment by crynobone** [comment]
Do you have any 3rd party packages that may cause this?

**Comment by gmarineau** [comment]
Yes, I found this package cause the trouble : "codenco-dev/nova-grid-system"
