### ISSUE TITLE
showWhenPeeking() relation error when via resource

### ISSUE THREAD

**Issue by keihartonline** [laravel/nova-issues#5275]
- Laravel Version: 9.41.0
- Nova Version: 4.19.3
- PHP Version: 8.1
- Database Driver & Version: mySQL 8.0.31
- Operating System and Version: Docker Mac 4.13.1
- Browser type and version: Chrome Versie 109.0.5414.119

### Description:

We started by setting up various peekable fields by chaining the `->showWhenPeeking()` method to fields we wanted to see when peeking. This all seemed to work.
Still, we found out about a problem with a BelongsTo relationship.
We got an error message saying a method does not exists on a model.

```
Call to undefined method App\Reservering::organisator()
```

![image](https://user-images.githubusercontent.com/115072307/214556937-8ee7fbb3-d294-40fe-8297-b82c868e3694.png)

The error message is correct because the relation `organizer` does not exist on `User` but NOVA shouldn't search for `organizer` on `User` relation at all. In fact, the relation `organizer` is a relation of a `HasMany` relation on `User`, called `Reservations`.

The relationships summarized:
**User** -> hasMany **Reservations** -> BelongsTo a **Organizer** 

So now, when I view a User in NOVA, there is a HasMany card created with all reservations. Only it fails to load records because of the error:

![image](https://user-images.githubusercontent.com/115072307/214558359-1f2a225d-05e7-46d3-8570-194eb58ec809.png)

When I open the resource index for `Reservations`, it all works. So the problem only exists when it's a peekable field within a HasMany card.

To fix it I for now added the following Closure to the `->showWhenPeeking()` on the Organizer BelongsTo Field:

```php
->showWhenPeeking(
    fn (NovaRequest $request) => ! $request->viaResource()
)
```

It is rather difficult to explain. If things are not clear I would like to answer all quesitions.

**Comment by bkuhl** [comment]
Can you share some code of how your relationships are defined?  Perhaps the relevant relationships for `Organizer`, `User` and `Reservations`?  Also supply the `HasMany` (also including what kind of fields method it's using such as `fieldsForIndex()`, `fields()`, `fieldsForDetail()`, etc would be helpful) definition please.

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by keihartonline** [comment]
> Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

Thanks gentlemen, I will create a reproducing repository in the coming days.

**Comment by keihartonline** [comment]
I've created a reproducing repository and found out there wasn't a problem. So I will dig deeper in our project.

**Comment by sanderbaas** [comment]
I work with @keihartonline and have made a minimal reproducing repository, because it seems the problem does still exist after all. The repo can be found at: https://github.com/Partybussen/peekable-bug

**Comment by crynobone** [comment]
This has been fixed and will be available in the upcoming release.
