### ISSUE TITLE
Boolean field with any ->dependsOn() does not show true/checked state

### ISSUE THREAD

**Issue by Tarpsvo** [laravel/nova-issues#5279]
- Laravel Version: v9.48.0
- Nova Version: 4.20.2
- PHP Version: 8.1.13

### Description:
When using a boolean field with ->dependsOn, the dependsOn request always returns the field value as 'false' on update view.

```php
# Field value in database: true

# /nova-api/services/1/update-fields?editing=true&editMode=update&viaResource=&viaResourceId=&viaRelationship=
Field value in response: true

# /nova-api/services/1/update-fields?editing=true&editMode=update&field=triggers_split_orders&component=boolean.boolean-field.triggers_split_orders
Field value in response: false

# Field itself:
Boolean::make('Triggers split orders')
  ->help('Blah blah')
  ->dependsOn(['type'], function ($field, $request, $formData) {
    if ($formData->type !== ServiceTypes::REGULAR_SERVICE) $field->hide();
  }),
```

This dependsOn check causes the field value to always be shown as false.

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by Tarpsvo** [comment]
@crynobone Thanks for the swift reply!

I'm not entirely sure how it's working for you.

This is what I see in Nova's source code:
`# src/Fields/DependentFields.php, line 41`
![image](https://user-images.githubusercontent.com/2018660/214840777-adccdae8-db19-4fd4-9e6c-f2d4a50a6922.png)

And the logs:
![image](https://user-images.githubusercontent.com/2018660/214840898-87070a47-7e71-45f3-8461-e67a8e7772c8.png)

The value is set to null and it's not returned anywhere. What's up with that?

**Comment by Tarpsvo** [comment]
My workaround for this issue would be:

```php
Boolean::make('Triggers split orders')
  ->help('Only applies to REGULAR services. Products from below will be used to create a separate Erply order')
  ->dependsOn(['type'], function ($field, $request, $formData) {
    if ($formData->type !== ServiceTypes::REGULAR_SERVICE) $field->hide();
    $field->value = $this->triggers_split_orders;
  }),
```

**Comment by crynobone** [comment]
The description is vague and the code example doesn't explained everything required to replicate the issue.

**Comment by Tarpsvo** [comment]
My point was that the `syncDependsOn` function in `DependentFields` which is called inside `UpdateFieldController@sync` resets the field value to null. How can it work for you?

**Comment by crynobone** [comment]
> `UpdateFieldController@sync` resets the field value to null. How can it work for you?

This is the expected behavior and no plan to change.

**Comment by Tarpsvo** [comment]
@crynobone 

Inside UpdateFieldController.php @ sync

```
$resource->updateFields($request)
                ->filter(function ($field) use ($request) {
                    return $request->query('field') === $field->attribute &&
                        $request->query('component') === $field->dependentComponentKey();
                })->each->syncDependsOn($request)
                ->first()
```

Returns the field value as null.

However, if I run ->jsonSerialize() on the field, the **'null' becomes boolean false**.

Which causes this check on the frontend to fail inside DependentFormField.js:
![image](https://user-images.githubusercontent.com/2018660/214850156-fdff233d-60a1-4cc9-b923-4b33b742e8ae.png)

Which calls setInitialValue() again and sets the value to false.

**Comment by Tarpsvo** [comment]
This is because Field.php jsonSerialize always calls resolveDefaultValue when there's no value. In case of the Boolean field, the resolveDefaultValue falls back to false when there's no default value configured:

![image](https://user-images.githubusercontent.com/2018660/214850948-16075c02-ae92-412f-ad96-e7bfecbc14c4.png)

**Comment by crynobone** [comment]
`resolveDefaultValue()` is only used on Create and not Update. There a lot of code mentions but isn't relevant.

**Comment by Tarpsvo** [comment]
> `resolveDefaultValue()` is only used on Create and not Update. There a lot of code mentions but isn't relevant.

No it's not.

Check Boolean.php:

![image](https://user-images.githubusercontent.com/2018660/215434383-5c485fd4-a27c-4d5b-b389-0faf33c24fdd.png)


It always falls back to false instead of null. Did you even test this?

**Comment by Tarpsvo** [comment]
@davidhemphill Can you chime on this please? I don't see any way this would work, I call bs on crynobone's "can't reproduce" comment, I doubt he tested it.

Any Boolean field with a ->dependsOn() will refuse to show 'true/checked' state on the **update** view when you have a dependsOn() set to it. And the cause is the snippet in the previous comment - HasDependentFields mixin expects the value to come back as `null`, which would mean the value was not altered. However `Fields/Boolean.php` always falls back to `false` and does not allow `jsonSerialize()` to return `null` for value.

**Comment by crynobone** [comment]
> I call bs on crynobone's "can't reproduce" comment, I doubt he tested it.

I did ask for reproducing code :-)

**Comment by sanderbaas** [comment]
> 

I've got the same problem as @Tarpsvo , but the workaround seems to work. My Boolean field depends on a Select field.

**Comment by Marko298** [comment]
I have the same issue
