### ISSUE TITLE
Dependency brick/money needs updated

### ISSUE THREAD

**Issue by gilbitron** [laravel/nova-issues#5281]
- Nova Version: 4.21.0

### Description:

I'm trying to install the `brick/money` package but getting the following composer error:

```
laravel/nova 4.21.0 requires brick/money ^0.5.0|^0.6.0|^0.7.0 -> found brick/money[0.5.0, ..., 0.7.1] but it conflicts with your root composer.json require (^0.8.0).
```

It looks like `brick/money` v8.0.0 [was released last week](https://github.com/brick/money/releases/tag/0.8.0).

**Comment by crynobone** [comment]
This will be available on the next release.
