### ISSUE TITLE
Error when uploading attachments to Trix field using remote file disk

### ISSUE THREAD

**Issue by JamieWritesCode** [laravel/nova-issues#5291]
- Laravel Version: 9.50.1
- Nova Version: 4.21.0
- PHP Version: 8.1.11
- Database Driver & Version: mysql / sail
- Operating System and Version: sail
- Browser type and version: chrome

### Description:

Attachments in Trix field appear to be bugged. Trix attachments aren't always saved when saving the associated resource. See details below. Using `->withFiles` option and a correctly configured `s3` disk. Trix attachment migrations have been run. 

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Edit a resource with a Trix field
2. Refresh the page with F5 - seems to be consistently reproduced after a page refresh
3. Use the attach button in the toolbar to attach any file type
4. Press "Update & Continue Editing"

Success message shown. Attachment preview disappears. Following error in console:

```
TypeError: Cannot read properties of null (reading 'value')
    at Proxy.handleChange (Trix.vue:56:51)
    at onTrixChange.t.<computed>.t.<computed> (Trix.vue:7:19)
    at nn (runtime-core.esm-bundler.js:155:22)
    at rn (runtime-core.esm-bundler.js:164:21)
    at n (runtime-dom.esm-bundler.js:370:13)
    at triggerEvent (trix.js:15:22495)
    at n.notify (trix.js:21:27203)
    at l.notifyEditorElement (trix.js:21:21775)
    at l.compositionDidChangeAttachmentPreviewURL (trix.js:21:11926)
    at f.attachmentDidChangePreviewURL (trix.js:20:20572)
```

File is successfully uploaded to S3. Seems to be the error is complaining about not being able to find the Trix editor component in order to bubble up the change event resulting in the changes being propagated to the field.

Happy to help debug - this is blocking production development.

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by JamieWritesCode** [comment]
Can confirm that we're still seeing the same issue on 4.22.1 - I'll work on a reproduction repo next week.

**Comment by JamieWritesCode** [comment]
Update, I've found the problem. Still working on understanding Nova internal code enough to work out the best way to demo the issue but I will try and explain here in the meantime.

The problem occurs when attempting to update a resource before any corresponding field attachment uploads are fully completed. Commonly this will happen if you are using an external disk for file storage like S3 which might explain why this didn't show up in your own testing. You would need to mock the additional delay required to pass the file through to a remote file disk.

In this instance, the file is initially uploaded to the server and this upload progress is tracked in the ui using the Trix progress tracking (green progress bar). After which the file is shown in the editor as if the upload is complete - however behind the scenes the request is still pending as the file is now being uploaded to S3 and we are waiting for the corresponding url to be returned.

![image](https://user-images.githubusercontent.com/4597068/223890617-b6b6f09a-2c7b-4b3b-a59e-ed3ed49d3953.png)
![image](https://user-images.githubusercontent.com/4597068/223890678-47ecb5aa-d4cd-4f3f-87e4-93d260a2f069.png)

_In this example, my resource is `post` id of `10` and field name is `content` so this url is `/nova-api/posts/field-attachment/content`._

If you press "Update..." button now, while this content request is still pending, Nova will hold the update resource request until after those pending attachment requests are completed. Clever.

![image](https://user-images.githubusercontent.com/4597068/223890167-438bfc52-4a19-498d-b47d-f0174346b346.png)

However, it appears that because the form data of that update resource request is already created and pending, the new content of the Trix field that is created on returning the attachment url (inserting the figure html etc) are not captured and instead the pending update resource request simply completes with the old form data (the state of the Trix field at the time of the button press).

This results in the field attachment being uploaded to disk and stored in database table correctly, however the HTML content of the Trix field does not include the corresponding `figure` element and attachment details, which are lost.

If you wait for the pending attachment upload to complete completely, the S3 url is returned, the Trix content is updated accordingly and then updating the resource works fine as the new state of the Trix html (with the S3 url) is properly sent along with the update resource request.

I hope this makes sense. I haven't managed to track down how and where Nova "pauses" the update resource request yet to see if I can provide some actionable code changes. Please understand that I'm juggling this debugging around a full time job. 🙃
