### ISSUE TITLE
BelongsTo Relation Error(This {model} may not be associated with this resource.)

### ISSUE THREAD

**Issue by rahwinia51** [laravel/nova-issues#5294]
- Laravel Version: 9.50.1
- Nova Version: 4.21.0
- PHP Version: 8.2.1
- Database Driver & Version: mysql 8.0.31
- Operating System and Version: macOS13.1 on arm64
- Browser type and version: Chome 109.0.5414.87 arm64
- Reproduction Repository: https://github.com/###/###

## Description:

When Model Create or Update,
BelongTo field error occured.
```
This User may not be associated with this resource.
```

Problem is in
/vendor/laravel/nova/src/Rules/Relatable.php:58.

This is normal case.
```sql
select * from users where users. id' = '1' and users. deleted at is null limit 1
```

But, when table has "search" column, query changed like below.
```sql
select * from `users` where (`users`.`id` like '%bar%' or `users`.`name` like '%bar%' or `users`.`email` like '%bar%') and `users`.`id` = '1' and `users`.`deleted_at` is null limit 1
```

### Detailed steps to reproduce the issue on a fresh Nova installation:

add "search" column in foos table(Foo Model)

App/Models/Foo.php
```php
public function user(): BelongsTo
{
    return $this->belongsTo(User::class);
}
```

App/Nova/User.php
```php
public static $search = [ 'id', 'name', 'something_else' ];
```

App/Nova/Foo.php
```sql
// foos table has "search" column.

// if it value is "bar", query like below.

select * from `users` where (`users`.`id` like '%bar%' or `users`.`name` like '%bar%' or `users`.`something_else` like '%bar%') and `users`.`id` = '1' and `users`.`deleted_at` is null limit 1
```

```php
public function fields(NovaRequest $request): array
{
		return [
				ID::make()->sortable(),
		
				BelongsTo::make('User'),
		
				...
		];
}
```

### solution

change "search" column name.

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)
