### ISSUE TITLE
Panel Field in Resource Action

### ISSUE THREAD

**Issue by kerbs-ns** [laravel/nova-issues#5296]
Laravel Version: 9.49.0

Nova Version: 4.21.0

PHP Version: 8.2.1

Sail v1.19.0

### Description:

If one Panel Fileds are used in Resource Action

Method Laravel\Nova\Panel::authorizedToSee does not exist.

**Comment by crynobone** [comment]
`Panel` was never designed for Action, you should be able to use `Heading` instead.

**Comment by kerbs-ns** [comment]
Thank
