### ISSUE TITLE
Customizing colors breaks the hover behavior of trend metrics

### ISSUE THREAD

**Issue by sanzeeb3** [laravel/nova-issues#5297]
- Laravel Version: 8.83.27
- Nova Version: 4.0
- PHP Version: 7.4
- Database Driver & Version:
- Operating System and Version: Windows 10
- Browser type and version: Google Chrome 

### Description:
Trend Metrics (https://nova.laravel.com/docs/3.0/metrics/defining-metrics.html#trend-metrics) doesn't behave as expected when colors is customized. The hover effect doesn't work anymore & the new colors doesn't take effect.

```
    'brand' => [
        'logo' => resource_path('/img/example.svg'),
        'colors' => [
            "400" => "#ff364f",
            "500" => "#120b45",
            "600" => "24, 182, 155, 0.75",
        ]
    ],
```

### Detailed steps to reproduce the issue on a fresh Nova installation:

1) Create trend metrics following the docs above. E.g. `php artisan nova:trend UsersPerDay`.
2) The card looks like this:

![image](https://user-images.githubusercontent.com/16817248/216925557-f891a1a5-1ebe-4244-8ac7-d08ad5195f0b.png)

3) Customize the color using the above config in config/nova.php

4) See the metrics. It doesn't display any data on hover and the new colors also don't apply there.

![screenshot-1](https://user-images.githubusercontent.com/16817248/216925988-fbb598db-3be7-4be8-99a0-f4b5b60f33c4.PNG)

**Comment by crynobone** [comment]
<img width="839" alt="Screenshot 2023-02-06 at 4 54 45 PM" src="https://user-images.githubusercontent.com/172966/216927685-8969635d-234e-4360-9007-139dcf6f3abe.png">

Our documentation mention we only support RGB, RGBA or HSL color code and not HEX as mentioned above.
