### ISSUE TITLE
Ability to search and sort on relationship fields

### ISSUE THREAD

**Issue by Gadurp1** [laravel/nova-issues#53]
So I figured this one out.  First you need to override the indexQuery with a join or with relationships

`   
    public static function indexQuery(NovaRequest $request, $query)
    {
              return $query->join('related_table', 'base_table.related_table.id', '=', 'related_table.id');
    }
    `

Then register the fields in search array (if you want the fields searchable)

`
    public static $search = [
        'id',
        'related_table.some_field',
    ];`

Then you can just add the field as any other base table field

`    
    public function fields(Request $request)
    {
        return [
            Text::make('some_field')->sortable()->onlyIndex(),
        ];
    }`

**Comment by RicardoRamirezR** [comment]
yes

**Comment by gonzunigad** [comment]
+1

**Comment by jasrys** [comment]
+1

**Comment by MattMangoni** [comment]
+1

**Comment by anderly** [comment]
Still an issue if you want to add a BelongsTo type relationship and make that searchable/sortable.

**Comment by gonzunigad** [comment]
+1


GONZALO DE-SPIRITO | Web Development
FRESHWORK STUDIO CHILE - freshwork.cl


Móvil: 881 53 776 | gonzalo@freshwork.cl

**Comment by Gadurp1** [comment]
Reopening because this would be a great feature.

**Comment by v1nk0** [comment]
+1

**Comment by stonkeep** [comment]
+1

**Comment by jasonlav** [comment]
Check out the Search Relations (https://novapackages.com/packages/titasgailius/search-relations) package.
