### ISSUE TITLE
How to make a multi-select? 

### ISSUE THREAD

**Issue by Enmaboya** [laravel/nova-issues#530]
How to make a multi-select? 
if such a possibility at all there is of course
![image](https://user-images.githubusercontent.com/32259003/45412779-92d46280-b688-11e8-9fa1-fd9a58a7e844.png)

**Comment by eberkund** [comment]
I think there should be a checkbox field type as that is probably what most people are looking for.

**Comment by arku31** [comment]
Okay, I quickly implemented it :)
I will probably do a composer package later, but it's already can be used.

**https://github.com/arku31/NovaMultiSelect**

P.S. Author also implemented this, I checked after I've finished mine :( He has used Vue select and I'm using select2 (jquery). So, since now you have 2 prebuild option ;)

**Comment by alexbowers** [comment]
Closed as community package solves problem

**Comment by shirshak55** [comment]
@alexbowers  community is good but  we cannot rely on community on premium package like nova  as they are not maintained :(. Its not that all people buy nova so they are happy for contribution

**Comment by arku31** [comment]
@shirshak55 I can only agree on it, this feature is required too often, I would prefer to have it implemented in Nova without any packages. If my implementation is fine, I completely allow it to use in Nova without mentioning my name and etc.

**Comment by christianmarth** [comment]
Many of these field types such as multiple select and checkboxes should be integrated as part of the core package and not have to rely on third party packages

**Comment by shirshak55** [comment]
Laravel Nova is a premium package so I don't think we should rely on community and it doesn't make any sense although I agree laravel community is awesome and there are many useful plugins :)

**Comment by nyssLab** [comment]
we still waiting on this official multiSelect package

**Comment by shirshak55** [comment]
its not going to come sir soon imho sir.

**Comment by pdolinaj** [comment]
How can I implement this checkboxes package on ATTACH screen where I'm adding related entities with Many to Many relationships? I couldn't find any example. Thanks.

**Comment by isometriq** [comment]
As far as I understand, the BooleanGroup field is useless, it creates a bunch of checkboxes ..cool ..then it saves the input encoded as JSON in a single field ...why not as pivot entries!?

**Comment by isometriq** [comment]
https://medium.com/laravel-nova/laravel-nova-select-belongstomany-relationships-using-checkboxes-62bdf710c0b4
..not elegant for sure, i'm disappointed

**Comment by isometriq** [comment]
What I would like to see is the related resource index in a modal that allow to select one or multiple entries then close and continue filling the form. Maybe there is a `select2` implementation lurking somewhere...

**Comment by JannieT** [comment]
This can do multi-select to a pivot table quite fine: https://github.com/koss-shtukert/laravel-nova-select2-auto-complete

**Comment by 7ammer** [comment]
Not having any multi select input was a surprise to me too! For example with the default nova setup applying a tag to a post is a very clumsy process.

**Comment by binaryk** [comment]
The same here! Still nothing?

**Comment by emjayess** [comment]
> As far as I understand, the BooleanGroup field is useless, it creates a bunch of checkboxes ..cool ..then it saves the input encoded as JSON in a single field ...why not as pivot entries!?

I'm also working around this limitation, presently... in a Nova Action, I load/save the primary resource model, then `->sync()` the pivot/relation with some BooleanGroup array keys fuckery.
