### ISSUE TITLE
Error when trying to log in to the login form: "View [app] not found."

### ISSUE THREAD

**Issue by nikolay94-dev** [laravel/nova-issues#5302]
- Laravel Version:  9.51.0
- Nova Version: 4.21.0
- PHP Version: 8.1
- Database Driver & Version:
- Operating System and Version: Ubuntu 20.04.1 LTS
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)
