### ISSUE TITLE
Trix field is duplicated (After update Nova to Version: 4.22.0)

### ISSUE THREAD

**Issue by RuslanMak** [laravel/nova-issues#5303]
- Laravel Version: 9.51.0
- Nova Version: 4.22.0
- PHP Version: 8.1.14

### Description:
After updates I have a bug. When I click edit resource, the Trix field is duplicated. 
Thank you!

**Comment by crynobone** [comment]
Can you elaborate "Trix field is duplicated"? Maybe a screenshot etc.

**Comment by RuslanMak** [comment]
Detail view
![detail](https://user-images.githubusercontent.com/37831442/217677605-4fabe94c-d90f-47fe-9f26-c0e80c20b0c8.jpg)

When click Edit
![edit](https://user-images.githubusercontent.com/37831442/217677614-08dfbe67-260d-4b77-a54f-dfe9725fc36a.jpg)

**Comment by intositeme** [comment]
Is this fixed? I'm having the same bug. Every time I edit a resource, all the Trix fields have their content duplicated.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍

**Comment by mewejo** [comment]
Is there an ETA on when a release will be made to fix this? It makes Trix unusable on fields with more than a few words
