### ISSUE TITLE
Search on BelongsToMany relationship is broken if using Laravel Scout

### ISSUE THREAD

**Issue by miagg** [laravel/nova-issues#5307]
- Laravel Version: 9.51
- Nova Version: 4.22.0
- PHP Version: 8.2
- Database Driver & Version: MySQL 8
- Operating System and Version: Mac OS Ventura 13.2
- Browser type and version: Chrome 109
- Reproducing repository: https://github.com/miagg/nova-scout-search-issue

### Description:  
If you search on a BelongsToMany relationship table (e.g. Users on a Role resource), it searches the whole table and not the related items. Also the pivot data is missing. If I disable scout for nova, the problem goes away.

![Screenshot 2023-02-09 at 11 34 54 AM](https://user-images.githubusercontent.com/6439071/217774573-9ac1f8f5-fb56-4c46-8727-a39260c2909a.png)

### Detailed steps to reproduce the issue on the reproducing repository:
> Meilisearch must be installed locally in order to fully test it.
1. Copy `.env.example` to `.env`
2. Change `MEILISEARCH_HOST` and `MEILISEARCH_KEY` if not using default settings
3. Create database `nova_search_issue`
4. Run `composer install`
5. Run `php artisan key:generate`
6. Run `php artisan migrate:fresh --seed`
7. Index users by running `php artisan scout:import "App\Models\User"`
8. Add it to valet by running `valet link`
9. Login to nova with `john@doe.com` and `password` as password.
10. Navigate to `/nova/resources/roles`
11. Select a random role
12. Try to search for a user and notice that unrelated users appear and `notes` pivot field is empty.

![Screenshot 2023-02-09 at 1 54 37 PM](https://user-images.githubusercontent.com/6439071/217807608-d0b8b2e5-2f8e-40b1-b27a-1385608258ed.png)

**Comment by crynobone** [comment]
Please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by miagg** [comment]
I managed to solve my problem by completely disabling scout in my `Resource.php` as indicated here #2860

```php
public static function usesScout(): bool
{
    return false;
}
```

However, a proper solution must be found in order to use scout with laravel nova for relationship searches.
