### ISSUE TITLE
Trix Attachment table and model changed with Version 4.22

### ISSUE THREAD

**Issue by schonhoff** [laravel/nova-issues#5309]
- Laravel Version: 9.51.0
- Nova Version: 4.22.0
- PHP Version: 8.1.9
- Database Driver & Version: MySQL 8
- Operating System and Version: Windows 10
- Browser type and version: Chrome 109.0.5414.120

### Description:
After updating to Laravel Nova 4.22 my Trix attachments where not working anymore. I tried to find the Trix attachment model in `Laravel\Nova\Trix` but it wasn't there anymore. After some research in the Laravel Nova vendor direcotry I found the Attachment Model in the namespace `Laravel\Nova\Fields\Attachments`. Because I extended the default model to add a function

```php
    public function attachable(): MorphTo
    {
        return $this->morphTo('attachable');
    }
```

I needed to change it. But that does not resolve the issue. After some more digging into the problem the table of the model changed as well. It was `nova_trix_attachments` and now it is `nova_field_attachment`. This is quite a breaking change in my opinion and it was not mentioned in the release notes.

Here is the old (Version 4.21) Attachment Model:

```php
namespace Laravel\Nova\Trix;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Attachment extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'nova_trix_attachments';

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * Purge the attachment.
     *
     * @return void
     */
    public function purge()
    {
        Storage::disk($this->disk)->delete($this->attachment);

        $this->delete();
    }
}

```

Here is the new (Version 4.22) Attachment Model:

```php
namespace Laravel\Nova\Fields\Attachments;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

/**
 * @property string $attachment
 * @property string $disk
 */
class Attachment extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'nova_field_attachments';

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * Purge the attachment.
     *
     * @return void
     */
    public function purge()
    {
        Storage::disk($this->disk)->delete($this->attachment);

        $this->delete();
    }
}

```

The docs still mentioning the old database structure:
![image](https://user-images.githubusercontent.com/42345405/218105220-f916662b-af90-4358-b00e-d18cf9595372.png)

https://nova.laravel.com/docs/4.0/resources/fields.html#trix-file-uploads

Maybe the table in the models (PendingAttachment and Attachment) could be renamed to match the docs for a non breaking change and can be updated on a Major release in the future?

**Comment by crynobone** [comment]
The documentation should already be updated by now or you can click the following button when it appears:

![image](https://user-images.githubusercontent.com/172966/218288816-0bc654df-e7c4-402d-ba65-b982a00413cf.png)

**Comment by schonhoff** [comment]
Hey @crynobone!

Thanks for updaten the docs.

Maybe you could Mentorin the change in the Release notes, too? With a Motive that you can run the Nova migration again to fix the problem?
