### ISSUE TITLE
Feature request: Grouping tools in menu

### ISSUE THREAD

**Issue by RicLeP** [laravel/nova-issues#531]
I think it would be useful to have the ability to group Tools together. For instance I am adding several tools just for administrators / development and management of the application. They don’t always need to take up so much real estate in the menu. If they could be grouped under one heading that would be helpful. The group should have the ability to be collapsed and opened (maybe the initial state can be specified).

For example:
![image](https://user-images.githubusercontent.com/19726976/45419255-aaa6e900-b67e-11e8-878c-3d9a7e6f7357.png)

Could be similar to this:
![image](https://user-images.githubusercontent.com/19726976/45419416-2ef96c00-b67f-11e8-8183-48504b29343d.png)

There would need to be a way to handle tools that have child sections themselves.

**Comment by bonzai** [comment]
#2
#271

**Comment by JiFus** [comment]
Maybe this will help you (haven't used it myself yet): https://novapackages.com/packages/alexbowers/nova-categorise-resources

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by GuidoThomassen** [comment]
Any updates on this? Or is there an existing package which does this for us?

**Comment by Dontorpedo** [comment]
any updates ?

**Comment by ordago** [comment]
> any updates ?

@Dontorpedo they added this a while ago:

https://nova.laravel.com/docs/3.0/resources/#grouping-resources

**Comment by theianjohnson** [comment]
Would also love to see this
