### ISSUE TITLE
Crash Color picker in nova 4.22.0

### ISSUE THREAD

**Issue by alibeheshtian** [laravel/nova-issues#5313]
- Laravel Version: 9.51.0
- Nova Version: 4.22.0
- PHP Version: 8.1
- Database Driver & Version: Postgres 15
- Operating System and Version: ubuntu 20
- Browser type and version: Google Chrome 110

### Description:
The color picker is crashed when selecting a color by selecting a color point on the screen

**Comment by crynobone** [comment]
Color picker is provided by the browser without using any 3rd party API. This should be reported or fixed by the Browser.

Without additional information I can't confirm but it may be related to https://bugs.chromium.org/p/chromium/issues/detail?id=1245191
