### ISSUE TITLE
Panel doesn't update data-page attribute when navigating

### ISSUE THREAD

**Issue by mex3890** [laravel/nova-issues#5318]
- Laravel Version: 9.51.0
- Nova Version: 4.22.0
- PHP Version: 8.1.14
- Database Driver & Version: MySQL 8.0.22
- Operating System and Version: Ubuntu:22.04(from Sail)
- Browser type and version: Firefox 109.0.1

### Description:
When navigating through Nova pages clicking on its links, the data-page attribute of div#app element does not updates with the new current page info. But if you refresh the page (or access it via its URL) the attribute is correctly set with the current page info.

![image](https://user-images.githubusercontent.com/90221921/218824973-4479b162-74fb-47f3-80ee-66322ddf976a.png)

### Detailed steps to reproduce the issue on a fresh Nova installation:
In any Nova application just inspect the page (pay attention to data-page attribute set into div#app) and navigate through any link, the data-page attribute doesn't change. Refresh the page (or access it again through its URL) and it'll change correctly.

**Comment by thbighead** [comment]
Same issue here, it seems that when navigating through Vue routes the `data-page` content is not updated, but when navigating through Laravel routes (such as refreshing the page or writing down the full page URL) the `data-page` content is correctly updated

**Comment by crynobone** [comment]
The code is handle directly be Inertia, if you feel that is an issue please submit to Inertia project.
