### ISSUE TITLE
Feature request: Nova UI style guide / best practices

### ISSUE THREAD

**Issue by RicLeP** [laravel/nova-issues#532]
There are already so many amazing Nova tools and packages and they look great in the Nova admin.

However I think that a style guide / best practices document would be very valuable and help keep the packages consistent.

I don’t often have to touch WordPress but when I do one of the most frustrating things is how in consistent plugins are. Not just in how they’re built but how they implement with WordPress. Some create new menus, some go inside existing items. Their editing screens can wildly differ in basic things like button colour and placement to having radically layouts and UX/UI.

I understand it’s difficult to enforce and the flexibility offered in Nova is very valuable and must be kept but some guidance would help keep what is a beautiful looking tool remain so. And, as an agency who makes many varying applications and websites for clients, having a consistent looking administration panel provides a far more professional feel.

**Comment by davidhemphill** [comment]
I appreciate the spirit of this, but we really don't want to create/maintain something like that. We're a small team as it is and it's ultimately up to the package providers to provide a great experience anyways.
