### ISSUE TITLE
BelongsTo Field not resolved correctly when editing

### ISSUE THREAD

**Issue by Hannoma** [laravel/nova-issues#5321]
- Laravel Version: 9.52.0
- Nova Version: 4.22.0
- PHP Version: 8.1.3

### Description:
In my resource InventoryLoan I have the following BelongsTo Relationship:
```php
BelongsTo::make('Item', 'item', InventoryItem::class)
                ->withoutTrashed()
                ->sortable()
                ->filterable()
                ->searchable()
                ->required(),
```
This works fine for the index, detail, and creation pages. But when updating the InventoryLoan, no InventoryItem is retrieved and selected as the current value. When inspecting the network tab, I saw the following request to `/nova-api/inventory-loans/associatable/item` with the query:
```
current: 42ab89cb-0478-4b89-88f4-f8e86bc61973
first: true
search: 
withTrashed: false
resourceId: 7adc2ee2-52bb-4931-980c-36fc448ff4c0
viaResource: 
viaResourceId: 
viaRelationship: 
component: belongsto.belongs-to-field.item
dependsOn: eyJpdGVtIjoiVGVzdCJ9
editing: true
editMode: update
```
returning:
```
{
  "resources": [],
  "softDeletes": true,
  "withTrashed": false
}
```

Note that the value for current is the correct id of the item and resourceId is the correct value for the loan I am editing.

**Comment by crynobone** [comment]
Please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by Hannoma** [comment]
I have found the issue.
In my InventoryItemPolicy I check if the item is available. When not one can not create a loan for it.
```php
public function addInventoryLoan(User $user, InventoryItem $item): Response
    {
        if (!$item->isAvailable()) {
            return Response::deny('Item is not available.');
        }

        return $this->checkPermission($user, 'manage') ? Response::allow() : Response::deny();
    }
```
Is there a way to extend my policy method so it returns true if one is updating the loan and forbids adding a loan for an unavailable item?

**Comment by Hannoma** [comment]
Is there an intended way of handling this use case in Nova. My solution works now but seems a bit complicated. Maybe others encounter this behavior as well.

**Comment by crynobone** [comment]
The policy method is exclusive to Nova unless you reusing it outside of Nova, in those case the shared code is how you should handle it.
