### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by TheDoctor0** [laravel/nova-issues#5326]
- Laravel Version: 10.0.0
- Nova Version: 3.32.0
- PHP Version: 8.2.2

### Description:
As [stated in the documentation](https://nova.laravel.com/docs/3.0/installation.html) Nova 3.x supports Laravel 8.x+ but currently it's [impossible](https://laravelshift.com/can-i-upgrade-laravel/laravel/nova) to install it on Laravel 10.
Are there plans to allow installation of it on the latest version of Laravel?
I'm currently upgrading a project and Nova is the last package that blocks an upgrade.

**Comment by crynobone** [comment]
Sorry, we have no plan to make any releases on Laravel Nova 3.

**Comment by drsdre** [comment]
Maybe adjust the documentation on Laravel Nova to state 'Laravel 8.x & 9.x'. This will save some time in dependency hell.

**Comment by sreerajlal** [comment]
Any solution ?
