### ISSUE TITLE
Resource Select All / All Matching does work in Edge

### ISSUE THREAD

**Issue by RicLeP** [laravel/nova-issues#533]
I’ve just tested Nova in Edge and the quick select checkboxes don’t function.

![image](https://user-images.githubusercontent.com/19726976/45421565-56533780-b685-11e8-9d63-3ee50397746c.png)

This is using Edge 17.

**Comment by bonzai** [comment]
#170

**Comment by Giactan** [comment]
Not work on Safari too.
<img width="297" alt="screen shot 2018-09-14 at 10 02 02 am" src="https://user-images.githubusercontent.com/31847606/45527400-89243980-b805-11e8-9a56-86f163d4337b.png">

**Comment by dillingham** [comment]
Related: https://github.com/laravel/nova-issues/issues/86 https://github.com/laravel/nova-issues/issues/170 https://github.com/laravel/nova-issues/issues/533 https://github.com/laravel/nova-issues/issues/196

**Comment by davidhemphill** [comment]
This has been fixed and will be included in an upcoming release.

**Comment by ZacharyDuBois** [comment]
Just ran into this. Thanks for the update!

**Comment by S-anasol** [comment]
Regression?

v1.3.2 

can't select all again.
