### ISSUE TITLE
Create & Add Another visual issue

### ISSUE THREAD

**Issue by kazak71** [laravel/nova-issues#5331]
- Laravel Version: 10
- Nova Version: 4.22.0
- PHP Version: 8.1
- Database Driver & Version: MySQL 8
- Operating System and Version: Ubuntu Server 22.04
- Browser type and version: any types

### Description:
When using **_Create & Add Another_** button browser does not scroll to the top of form but stays on the position where button is clicked. Same behavior is in editing mode when **_Update and Continue editing_** button is clicked .
But if there are any validation errors it scrolls properly.

**Comment by crynobone** [comment]
PR to fix this has been merged and pending next release.
