### ISSUE TITLE
Peekables Tooltip remain visible on loaded resources

### ISSUE THREAD

**Issue by orlyapps** [laravel/nova-issues#5338]
- Laravel Version: 9.0
- Nova Version: 4.0
- Browser type and version: Chrome 109

### Description:
When using Peekables and hovering quickly over links (allready loaded). The tooltip remains visible. A video of this behaviour is attached

Video:
https://share.cleanshot.com/f8KC3RJm

GIF:
![CleanShot 2023-02-20 at 10 26 11](https://user-images.githubusercontent.com/5220826/220065854-9727dcfb-d5e9-4d53-bf71-9bd4badaa37e.gif)

**Comment by crynobone** [comment]
Can you replicate the issue without `nova-tabs`?

**Comment by orlyapps** [comment]
do you need more information or a demo repository?

**Comment by crynobone** [comment]
The issue may be related to Akryum/floating-vue#927

We have added an outside click to hide the mishaving VDropdown but will depends on upstream for the proper fix.
