### ISSUE TITLE
Call to a non existent method in DispatchAction

### ISSUE THREAD

**Issue by gerardnll** [laravel/nova-issues#5343]
- Laravel Version: 10.0.3
- Nova Version: 4.22
- PHP Version: 8.2.1
- Database Driver & Version: not relevant
- Operating System and Version: not relevant

### Description:

Function forModels() on line 212 of file src/Actions/DispatchAction.php is calling `dispatch_synchronouslyForCollection($method, $models);` on line 224 when it should be calling `$this->dispatchSynchronouslyForCollection($method, $models);` resulting in a 500 Server Error.

### Detailed steps to reproduce the issue on a fresh Nova installation:

- create a non queuable an action and try to run it.

**Comment by crynobone** [comment]
Unable to replicate, line 224 shows correct `$this->dispatchSynchronouslyForCollection($method, $models);`

Are you downloading Laravel Nova from the correct source?

**Comment by gerardnll** [comment]
True, sorry... must have been a search and replace from the upgrade to Laravel 10.
