### ISSUE TITLE
Nullable Boolean field

### ISSUE THREAD

**Issue by shaffe-fr** [laravel/nova-issues#5346]
- Laravel Version: 9.48.0
- Nova Version: 4.21.0
- PHP Version: 8.0.19

### Description:

As we can see in `IconBoolean.vue`, the `Index/BooleanField` component supports to be nullable.
However, altough the PHP Boolean field can resolve `null` values (`\Laravel\Nova\Fields\Boolean::resolveAttribute`), the `\Laravel\Nova\Fields\Boolean::resolveDefaultValue` method will always fallback to `false`:
```php
   /**
     * Resolve the given attribute from the given resource.
     *
     * @param  mixed  $resource
     * @param  string  $attribute
     * @return bool|null
     */
    protected function resolveAttribute($resource, $attribute)
    {
        $value = parent::resolveAttribute($resource, $attribute);

        return ! is_null($value)
                    ? ($value == $this->trueValue ? true : false)
                    : null;
    }

    /**
     * Resolve the default value for the field.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @return bool
     */
    protected function resolveDefaultValue(NovaRequest $request)
    {
        return parent::resolveDefaultValue($request) ?? false;
    }
```

I think it would make sense the default value to resolve to `null` when the field is nullable.
That could be something like that: 
```php
    /**
     * Resolve the default value for the field.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @return bool
     */
    protected function resolveDefaultValue(NovaRequest $request)
    {
        return parent::resolveDefaultValue($request) ?? ($this->nullable ? null : false);
    }
```

and the Index/BooleanField should be like that
```vue
<template>
  <div :class="`text-${field.textAlign}`">
    <IconBoolean :value="field.value" :nullable="field.nullable" />
  </div>
</template>

<script>
export default {
  props: ['resourceName', 'field'],
}
</script>

```
Thanks

**Comment by davidhemphill** [comment]
With the `Boolean` field, the value must resolve to either `true` or `false`. `NULL` is not a Boolean value.

**Comment by shaffe-fr** [comment]
With current implementation, with the following code:
```php
Boolean::make('featured')->nullable() /*->nullValues(fn () => null)*/,
```
I would expect the following result:
![image](https://user-images.githubusercontent.com/3834222/220657086-c776f889-5476-447d-8e39-cc64aeb8b13f.png)

What's you take on that?

**Comment by ziming** [comment]
There used to be a very popular nova 3rd party package called nullable nova boolean or nullable nova datetime (can't recall the exact correct names) back in nova 2 or 1 days with lots of stars but that maintainer stopped maintaining it

**Comment by davidhemphill** [comment]
I'm not sure if it does, but I believe using the `nullable` helper here should throw an Exception.

**Comment by shaffe-fr** [comment]
You're right of think it should be either the third nullable state or the exception

**Comment by pab-set** [comment]
I've found a lot of confusion if data in a model/resource has the affirmative negative, when in reality the data defaulted to false instead of staying null. I dug through the native code for the boolean field and the null coloring and functionality is there, albeit inhibited to be a true boolean. It would be nice if the nullable functionality already in boolean fields was accessible.

**Comment by OliverEberlei** [comment]
Just wanted to write an answer here, since this thread came up when googling this issue.

I managed to do this in Nova 5 by using

`->nullable( true, function ($value) { return $value === null; } )`
