### ISSUE TITLE
Allow default Gravatar image to be specified

### ISSUE THREAD

**Issue by RicLeP** [laravel/nova-issues#535]
Rather than having the Gravatar ‘G’ when a user hasn’t uploaded an image it would be cool to be able to select from one of the options they provide, (identicon, monsterid, etc.). Or supply an encoded URL for a custom image.

Details: https://en.gravatar.com/site/implement/images/

**Comment by RicLeP** [comment]
Here’s an implementation:

`

	
	namespace Laravel\Nova\Fields;

	class Gravatar extends Avatar
	{
		/**
	 	 * The Gravatar style
	 	 *
		 * @var string
	 	*/
		public $gravatarStyle = null;

    	/**
     	 * Create a new field.
    	 *
    	 * @param  string  $name
     	 * @param  string|null  $attribute
    	 * @param  mixed|null  $resolveCallback
    	 * @return void
    	 */
   	 	public function __construct($name = 'Avatar', $attribute = 'email', $resolveCallback = null)
    	{
       	 parent::__construct($name, $attribute ?? 'email', $resolveCallback);

        	$this->exceptOnForms();

        	$this->withMeta(['indexName' => '']);
    	}

		protected function resolveAttribute($resource, $attribute)
		{
			$callback = function () use ($resource, $attribute) {
				return 'https://www.gravatar.com/avatar/'.md5($resource->{$attribute}).'?s=300&d='.urlencode($this->gravatarStyle);
			};

			$this->preview($callback)->thumbnail($callback);
		}

		/**
		 * Sets the style of Gravatar to use from: 404, mp, identicon, monsterid, wavatar, retro
		 * robohash, blank or provide a URL to an image
		 *
		 * @return bool
		 */
		public function style($value) {
			$this->gravatarStyle = $value;

			return $this;
		}
	}
`

**Comment by sohaibafifi** [comment]
use Avatar with preview and thumnail callbacks : 

example: 

```
Avatar::make('Avatar')->preview(function () {
                   return 'https://www.gravatar.com/avatar/'.md5(strtolower($this->email)).'?s=200&d=mp';
                })->thumbnail(function () {
                   return 'https://www.gravatar.com/avatar/'.md5(strtolower($this->email)).'?s=100&d=mp';
                }),
```

**Comment by RicLeP** [comment]
Should anyone else read this and want to use the user’s uploaded image or a Gravatar:

```
Avatar::make('Avatar')->thumbnail(function () {
	return $this->avatar ? Storage::disk($this->disk)->url($this->avatar) : 'https://www.gravatar.com/avatar/'.md5(strtolower($this->email)).'?s=200&d=identicon';
})->preview(function () {
	return $this->avatar ? Storage::disk($this->disk)->url($this->avatar) : 'https://www.gravatar.com/avatar/'.md5(strtolower($this->email)).'?s=100&d=identicon';
})->maxWidth(150)
->disableDownload(),
```

And if it’s the logged in user you can set the little icon like so:

\resources\views\vendor\nova\partials\user.blade.php

```
<dropdown-trigger class="h-9 flex items-center" slot-scope="{toggle}" :handle-click="toggle">
    <img src="{{ auth()->user()->avatar ? Storage::disk(auth()->user()->disk)->url(auth()->user()->avatar) : 'https://www.gravatar.com/avatar/'.md5(strtolower(auth()->user()->email)).'?s=200&d=identicon' }}" class="rounded-full w-8 h-8 mr-3"/>
...
```

Replace 'identicon' with the style of Gravatar you want to use

**Comment by anondev-sudo** [comment]
How to override default gravatar avatar?
