### ISSUE TITLE
Custom Tool assets loaded multiple times

### ISSUE THREAD

**Issue by magdicom** [laravel/nova-issues#5354]
- Laravel Version: 9.52.4
- Nova Version: 4.21.#
- PHP Version: 8.2.1

### Description:

I've my custom tool built using the `artisan nova:tool` stub, its CSS and JS files called multiple times (actually 4 times each) in HTML.

### Detailed steps to reproduce the issue on a fresh Nova installation:

using the stub tool will be enough:

```php
<?php
namespace Vendor\MyCustomTool;

use Laravel\Nova\Nova;
use Laravel\Nova\Tool;

class MyCustomTool extends Tool
{
    /**
     * Perform any tasks that need to happen when the tool is booted.
     *
     * @return void
     */
    public function boot()
    {

        Nova::script('my-custom-tool', __DIR__.'/../dist/js/tool.js');
        Nova::style('my-custom-tool', __DIR__.'/../dist/css/tool.css');
    }
}
```

in rendered HTML it will be loaded as:

```html
<!-- Tool Styles -->
<link rel="stylesheet" href="/nova-api/styles/my-custom-tool">
<link rel="stylesheet" href="/nova-api/styles/my-custom-tool">
<link rel="stylesheet" href="/nova-api/styles/my-custom-tool">
<link rel="stylesheet" href="/nova-api/styles/my-custom-tool">
```

the same with JS files.

**Comment by magdicom** [comment]
I've checked and found that `Nova::availableStyles` will add the same item/object multiple times

**Comment by crynobone** [comment]
Unable to reproduce the issue, see reproducing code: https://github.com/nova-issues/issue-5354/commit/8e076ffc8c40538f20d61328bcde735bb2715de2

![image](https://user-images.githubusercontent.com/172966/221721028-c2b874c8-c7b1-4124-84db-44e7f4e4d60b.png)

Please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)
