### ISSUE TITLE
 Data truncated for column 'actionable_id'

### ISSUE THREAD

**Issue by Mamoun2020** [laravel/nova-issues#5358]
- Laravel Version: 9.48.0
- Nova Version: 4.21.0
- PHP Version: 8.0

### Description:
insert into the 'actionable_id' column is too large for the column's data type. Since you mentioned that the ID is a UUID, it's possible that the column is not big enough to store the full UUID value.

we need to change the data type of the column to 'VARCHAR(36)' or 'BINARY(16)'  > (String) to store the full UUID value. Alternatively, you could use a UUID-specific data type like 'UUID' or 'CHAR(36)'.

**Comment by Mamoun2020** [comment]
public function up()
    {
        Schema::table('action_events', function (Blueprint $table) {
            $table->string('actionable_id', 36)->change();
        });
    }

    public function down()
    {
        Schema::table('action_events', function (Blueprint $table) {
            $table->integer('actionable_id')->change();
        });
    }

**Comment by michaelambass** [comment]
Thanks for sharing @Mamoun2020 !
