### ISSUE TITLE
[BUG] View/Edit/Delete actions fail to function when viewing a lens

### ISSUE THREAD

**Issue by dongilbert** [laravel/nova-issues#536]
When viewing resources through a lens, action links fail to point to the correct location. 
![screen shot 2018-09-12 at 8 46 36 am](https://user-images.githubusercontent.com/718028/45429106-9cea6700-b670-11e8-9212-891640cac068.png)

**Comment by davidhemphill** [comment]
Gonna need some more information to diagnose this. These are working on the latest version in both Safari and Chrome. Will open up if you provide a reproducible example.

**Comment by dongilbert** [comment]
Sorry for lacking more details. Did some more digging and found the issue.

It turns out that, quite sensibly, it is _required_ to select the `id` of the resource in your lens query, even if you don't plan on showing the ID column in the lens' table.
