### ISSUE TITLE
Nova does not seem to support Laravel Dynamic Relationships

### ISSUE THREAD

**Issue by Navi2016** [laravel/nova-issues#5368]
![afbeelding](https://user-images.githubusercontent.com/20399169/222450025-c2845077-6507-499a-8b37-28c390411eb1.png)
- Laravel Version: 10.1.5
- Nova Version: 4.22.1
- PHP Version: 8.1
- Database Driver & Version: MySQL 5.7
- Operating System and Version: Windows 10
- Browser type and version: FF

### Description:

When using a dynamic relation in a service provider boot method as described here:
https://laravel.com/docs/10.x/eloquent-relationships#dynamic-relationships

And using, for example a HasOne Nova field on it, Nova does see the relationship method but gives an error and the resource does not load.

"Undefined array key 'metadata_set_gob'"

### Detailed steps to reproduce the issue on a fresh Nova installation:

You need a Product resource and related model via product_id field.

Define a dynamic relation in a SP:
\App\Models\Product::resolveRelationUsing('metadata_set_gob', static function (\App\Models\Product $model) {
    return $model->hasOne(\App\Models\GOB::class, 'product_id');
});

Try using the field in a HasOne field:
HasOne::make('Metadata', 'metadata_set_gob', GOB::class);

Returns the error on trying to create a new resource.

**Comment by crynobone** [comment]
Unable to replicate the issue using the following code: https://github.com/nova-issues/issue-5368/commit/7eb7aa6204a3e3d70da04d10ef48a93422d656b6

Please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by Navi2016** [comment]
THanks for the quick reply, one thing i noticed was you made the relations in the register() method instead of the boot() recommended by the manual, but it did not make a difference.

Looking further into the error it said:
[2023-03-06 10:34:22] local.ERROR: Undefined array key "visualnova_relation_gob" {"userId":1,"exception":"[object] (ErrorException(code: 0): Undefined array key \"visualnova_relation_gob\" at C:\\DATA\\vhosts\\git\\catalogus\\vendor\\laravel\\nova\\src\\Fields\\Field.php:867)

So i looked at Field.php line 867 and it something about the field being required or not, strange so i manually set the relation to not be required:

HasOne::make('Metadata', 'visualnova_relation_gob', \App\Nova\VisualNova\GOB::class)->required(false)

And then it works!

I'm thinking this might not be a bug but it having something to do with the way i generate the Nova fields.

I have not defined them as regular Nova files but defined in database and loop over them to fill the $fields array.

**Comment by crynobone** [comment]
I'm sorry, I can't offer any assistance or PR to fix the issue unless we can reproduce it. You need to submit an example repository where we can see the problem that occurs.
