### ISSUE TITLE
TextArea mismatching color on detail view light & dark mode

### ISSUE THREAD

**Issue by dmason30** [laravel/nova-issues#5370]
- Nova Version: 4.22.1

### Description:
The text colour should match the other fields text colour:

**Dark**
![image](https://user-images.githubusercontent.com/20278756/222470457-ac24a8b3-bd05-4458-a98b-34df88ceb40a.png)

**Light**
![image](https://user-images.githubusercontent.com/20278756/222470570-c3e295a7-9efa-410f-826d-80963c3e2e1b.png)

**Comment by groax** [comment]
I also have a problem with the bar with the buttons. How can I fix the color in dark theme? 
![101332](https://user-images.githubusercontent.com/11779856/236148343-0c870b61-a9cd-4311-9d08-3632c4b9dc25.png)
