### ISSUE TITLE
403 forbidden in Laravel Nova

### ISSUE THREAD

**Issue by exshapoval** [laravel/nova-issues#5372]
- Laravel Version: 10.1.5
- Nova Version: 4.22.1
- PHP Version: 8.1

### Description:
When in .env APP_ENV=local all ok But when APP_ENV=production I see error 403 on my admin/login page

I try to write

```
        Gate::define('viewNova', function ($user) {
            return in_array($user->email, [
                'myrealemail'
            ]);
        });

```
in NovaServiceProvider.php but nothigt

How I can fix it for production?

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)
