### ISSUE TITLE
Change redirect after saving a resource

### ISSUE THREAD

**Issue by itstrueimryan** [laravel/nova-issues#538]
I don't want the View pages for a particular Resource.  The best I've found to hide that functionality is to block it off via a Resource Policy.  However, after creating or updating an instance of that resource, it redirects to its view page, which just gives me a 404.  I would love to customize this redirection.  Is this possible?

**Comment by dillingham** [comment]
The navigation to the detail page is hard coded 
`/nova/resources/js/views/Create.vue` line 99
`/nova/resources/js/views/Update.vue` line 103
So "is it possible?" not currently

This package idea would benefits from such abilities though 
https://github.com/tightenco/nova-package-development/issues/25

**Comment by davidhemphill** [comment]
Can you provide a use-case where it makes sense to not allow the user that can edit and create resources to view them as well?

**Comment by dillingham** [comment]
Two buttons is plenty I think. 

$saveRedirect “detail” or “index” maybe, defaulting to index. 
Then only changing the router route name
Then you’d be able to set this based on role

I cant imagine many cases where you’d do this though. But maybe there are users within the system that can request things or provide info, but aren’t intended to manage that info. Like support requests.

**Comment by martinmildner** [comment]
> Two buttons is plenty I think.

I can well understand your concerns. But if the functionality of the buttons speeds up the work in the backend, the buttons make sense, I think.

The Open Source CMS _Contao_, which I am using a lot, uses in some places even four buttons, which make the workflow super fast (especially when you are using the shortcuts for each button):

<img width="1179" alt="buttons_cms" src="https://user-images.githubusercontent.com/789541/49465407-d957da00-f7fd-11e8-8dad-f77775b8671c.png">

**Comment by dillingham** [comment]
Related https://github.com/laravel/nova-issues/issues/604 https://github.com/laravel/nova-issues/issues/797https://github.com/laravel/nova-issues/issues/862

**Comment by fourstacks** [comment]
> Can you provide a use-case where it makes sense to not allow the user that can edit and create resources to view them as well?

@davidhemphill - I have a use case for this issue if it helps.  I'm building a CRM for a local charity working with refugees who have moved to my local area.  The charity runs a drop-in center and they want to have the ability for volunteers to register new members on the door.  However due to the fact that the registration form asks for somewhat sensitive information and therefore they want to make sure that anyone logged in with a 'volunteer' role is only able to create, and not view/edit Member resources for two reasons:

1) they do not want volunteers to be able to view the profiles of other members in the DB
2) if the device that they are taking registrations on goes missing (the drop-ins can get busy so a tablet going 'missing' wouldn't be totally outside the realms of possibility) they want to make sure that no profiles are viewable with those logins.

Currently I'm using authorisation policies to just say that anyone with a volunteer role can only create Members so obviously after creation they are taken to the 'view' screen which results in a 403.

**Comment by simonfunk** [comment]
I would welcome it too. My situation is, that i have a MorphMany Resource and i show already the view on the view of parent resource, so it makes absolutely sense redirect to parent view and not of the child view.

**Comment by tjmartin69** [comment]
Hi @davidhemphill,

I have the current use case for this. 

A team has many credits linked to them. You can create a credit adjustment against a team. Currently when this is created it goes to the details view of the credit adjustment when for our application it would make more sense to redirect them back to the team. This will save our end users time and confusion.

Below is a view of the team with the create adjustment button. This is where we would like to redirect back to.

<img width="1009" alt="screenshot 2019-01-09 at 14 17 10" src="https://user-images.githubusercontent.com/276399/50904879-4cfe8f80-1419-11e9-912f-469584cd585c.png">

For me a redirect method for create, update, delete would be handy maybe you give it the relationship name on the model and it redirects back to the correct nova resource?

**Comment by eithed** [comment]
Another use case:

I've got an InsurancePolicy resource that has many InsurancePolicyRate resources via HasMany relationship - there shouldn't be IPR index screen, as one IPR can't exist without IP and all IPR information is displayed on IP screen under the relationship details. Currently however, if I'll create an IPR I'll be redirected to 404 page

**Comment by krns** [comment]
The redirect after saving would be a nice feature for us.

@tjmartin69 how do you implemented these tabs? They look very nice.

**Comment by talent-on-view** [comment]
@krns I use this package - https://packagist.org/packages/eminiarts/nova-tabs

**Comment by m-lotze** [comment]
After updating a resource the **default** should be to redirect to last index view or lens. the current behaviour is not what most users would expect in my experience. it is expected to go back where i came from.

**Comment by Ange7** [comment]
someone have news about this feature ?

**Comment by packytagliaferro** [comment]
I would also like to change where redirect goes after creating/updating a resource. In my scenario I would want it to go back to the relationship parent detail page.

**Example:**

I have 2 models Posts and Questions You can never create a Question without a Post. For this reason it would be nice to not show Questions on the left panel menu at all only Posts. Then from a Post detail you add questions and return to that Post detail.

This scenario seems like a perfect time to allow that functionality. For my admins they dont want to look at a giant list of all Questions, they only care about the Post and questions associated with it.

In your flow right now if I have to add 20 Questions to a post I have to:

1. Click on post
2. Click add question
3. Add the question
4. Get retuned to the question detail
5. Click posts (again)
6. Find the post I just added a question to
7. Repeat 19 more times.

Or am I missing something?

**Comment by desaintflorent** [comment]
Same here, I have a belongsTo relationship to a model to add images.
First of all it doesn't make sens to go to all images when you just want to add an image to your model.
But as I don't want to allow all users to see all images I removed the permission and I've got a 403 every time I had an image to the model.

Can we have a fix for that ?

**Comment by alexconesap** [comment]
We faced the same issue and we temporarily solved it adding a few PHP/js code lines over Nova classes.

```
Laravel\Nova\Resource

New method:
    /**
     * Where to route when a model is saved: 'detail', 'index'. It may be overriden at descendants
     * @return string
     */
    public function getRedirectToOnSave() {
        return 'detail';
    }
```

```
Laravel\Nova\Http\Controllers\CreationFieldController.php

Return of index() method:
        $new_resource = $request->newResource();
        return response()->json([
                    'saveRedirect' => $new_resource->getRedirectToOnSave(),
                    'fields' => $new_resource->creationFields($request)->values()->all()
        ]);

```

```
Laravel\Nova\Http\Controllers\UpdateFieldController.php

Return of index() method:
        return response()->json([
                    'saveRedirect' => $resource->getRedirectToOnSave(),
                    'fields' => $resource->updateFields($request)->values()->all()
        ]);
```

```
resources\js\views\Update.vue

Added to data: () => 
saveRedirect: 'detail',

Modified method getFields():
async getFields() {
                        this.loading = true;

                        this.fields = [];
                        this.saveRedirect = 'detail';

                        const {data: response} = await Nova.request()
                                .get('/nova-api/${this.resourceName}/${this.resourceId}/update-fields')
                                .catch(error => {
                                    if (error.response.status == 404) {
                                        this.$router.push({name: '404'})
                                        return
                                    }
                                });

                        this.fields = response.fields;
                        this.saveRedirect = response.saveRedirect;

                        this.loading = false;
                    },
```

```
resources\js\views\Create.vue

Added to data: () => 
saveRedirect: 'detail',

Modified method getFields():
async getFields() {
                        this.loading = true;

                        this.fields = [];
                        this.saveRedirect = 'detail';

                        const {data: response} = await Nova.request().get(
                                '/nova-api/${this.resourceName}/creation-fields',
                                {
                                    params: {
                                        viaResource: this.viaResource,
                                        viaResourceId: this.viaResourceId,
                                        viaRelationship: this.viaRelationship,
                                    },
                                }
                        );

                        this.saveRedirect = response.saveRedirect;
                        this.fields = response.fields;
                        this.loading = false;
                    },

```

Remember to recompile / republish Nova assets/js after performing changes over the .vue files using npm.

At this point you will get exactly the same results you were getting before. The main difference is that now you can edit any of your Nova resources to override the new method declared at the Nova's Resource abstract class:

```
class OneClass extends Resource {
   ...
    public function getRedirectToOnSave() {
        return 'index';
    }
   ...
}
```

In this particular case the OneClass resource will redirect to 'index' rather than to 'detail' after saving.
You may eventually declare a couple of methods instead of a single one getRedirectToOnSave(), one for resource creation redirection and another one for the updating process.

Hope it helps!

**Comment by Ange7** [comment]
@alexconesap but we can't redirect to external URL or other resource with this method ?

**Comment by alexconesap** [comment]
@Ange7 yes, you can do it but to achieve it you would need to modify a bit the code.
BTW thanks to your question I realised that I forgot to publish the changes on both createResource() and updateResource() methods on the .vue files. I modified my previous post to amend that error.

Is just in that methods where you can achieve your goal.

Look:
```
this.$router.push({
    name: this.saveRedirect,   <<<< this is the modified line
    params: {
          resourceName: this.resourceName,
           resourceId: response.data.id,
    },
})
```

This is the 'redirection' to the received saveRedirect value ('index', 'detail', ...). You need to modify the behaviour of this code to redirect totally to an external URL rather than rendering the page content.

In your case you may parse the 'saveRedirect' to detect if it contains http:// or https:// or so and, based on this condition, use a different code. It is just an idea.

**Comment by Ange7** [comment]
just tried with:

1. npm install in /nova/ folder 
2. php artisan nova:publish in /

But now i have a white container (without error)

![image](https://user-images.githubusercontent.com/4114703/52404011-46227580-2ac8-11e9-8131-8c235bbc27ae.png)

**Comment by alexconesap** [comment]
@Ange7 It looks like you are just publishing the "already compiled" .js files from nova to your working directory, but not the new ones resulting of compiling the -modified- .vue files.

So your problem is that your current .js are still waiting for a single json result but you are now providing an array with two fields ('fields' and 'saveRedirect') instead (due to the changes on the .php files). Therefore, the javascript code fails. You can see the error on the javascript console of your browser.

I am new to Nova (just a couple of days using it!) so I am not 100% sure if it is the way to do it, but my suggestion is to access the /nova directory (where you modified the .vue files) and follow this steps:
```
1) Copy the webpack.mix.js.dist and paste it as webpack.mix.js
2) Edit the webpack.mix.js file and modify:
    .copy('public', '../nova-app/public/vendor/nova') 
as 
    .copy('public', '../public/vendor/nova')
3) Run npm run watch
```
NOTE: Instead of "npm run watch" you can also use the "dev" or "prod" commands to just compile and publish but to see what you are doing I would suggest to use watch and make some changes over the .vue files to ensure that everything is correctly compiled and copied to the correct folders.

BTW if somebody else knows how to do these last steps better please help here.

**Comment by Ange7** [comment]
Which version of nova do you use?

**Comment by Ange7** [comment]
My problem is : when i run « npm run * », even without modification. My interface is broken (and i have one build error)

![image](https://user-images.githubusercontent.com/4114703/52408627-8e936080-2ad3-11e9-991b-9b77f3a30963.png)

**Comment by alexconesap** [comment]
1.3.1

**Comment by Ange7** [comment]
@alexconesap okay, same version as you. 

```
$ php --version
PHP 7.1.7 (cli) (built: Aug 28 2017 14:36:34) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
$ node --version
v10.12.0
$ npm --version
6.7.0
```

my package.json 

```
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "test": "jest",
        "watch:test": "jest --watch"
    },
    "devDependencies": {
        "@vue/test-utils": "^1.0.0-beta.29",
        "axios": "^0.17",
        "babel-helper-vue-jsx-merge-props": "^2.0.3",
        "babel-jest": "^23.6.0",
        "babel-plugin-syntax-dynamic-import": "^6.18.0",
        "babel-plugin-syntax-jsx": "^6.18.0",
        "babel-plugin-transform-vue-jsx": "^3.7.0",
        "babel-preset-env": "^1.6.1",
        "cross-env": "^5.0.0",
        "flush-promises": "^1.0.2",
        "jest": "^23.6.0",
        "jest-mock-axios": "^2.1.11",
        "jest-serializer-vue": "^2.0.0",
        "jquery": "^3.2.0",
        "laravel-mix": "^1.0",
        "lodash": "^4.17.11",
        "tailwindcss": "^0.6.6",
        "vue": "^2.6.3",
        "vue-jest": "^2.6.0",
        "vue-router": "^3.0.2",
        "vue-server-renderer": "^2.6.3"
    },
    "dependencies": {
        "chartist": "^0.11.0",
        "chartist-plugin-tooltips": "^0.0.17",
        "codemirror": "^5.43.0",
        "flatpickr": "^4.5.2",
        "form-backend-validation": "^2.3.6",
        "inflector-js": "^1.0.1",
        "laravel-nova": "^1.0.6",
        "markdown-it": "^8.4.1",
        "marked": "^0.3.19",
        "moment": "^2.24.0",
        "moment-timezone": "^0.5.23",
        "numeral": "^2.0.6",
        "pikaday": "^1.8.0",
        "places.js": "^1.15.5",
        "popper.js": "^1.14.7",
        "portal-vue": "^1.5.1",
        "trix": "^1.0.0",
        "vue-async-computed": "^3.5.2",
        "vue-clickaway": "^2.1.0",
        "vue-toasted": "^1.1.26",
        "vuex": "^3.1.0"
    },
    "jest": {
        "setupFiles": [
            "./resources/js/test-setup/bootstrap.js"
        ],
        "testRegex": "(/resources/js/__tests__/.*|(\\.|/)(test|spec))\\.jsx?$",
        "moduleFileExtensions": [
            "js",
            "json",
            "vue"
        ],
        "transform": {
            "^.+\\.js$": "<rootDir>/node_modules/babel-jest",
            ".*\\.(vue)$": "<rootDir>/node_modules/vue-jest"
        },
        "snapshotSerializers": [
            "<rootDir>/node_modules/jest-serializer-vue"
        ],
        "collectCoverage": false,
        "collectCoverageFrom": [
            "**/*.{js,vue}",
            "!**/node_modules/**"
        ],
        "moduleNameMapper": {
            "^@/(.*)$": "<rootDir>/resources/js/$1",
            "\\.(css|jpg|png)$": "<rootDir>/resources/js/util/empty.js"
        }
    }
}
```

**Comment by alexconesap** [comment]
We are using elder versions of both node (7.8.0) and npm (4.2.0). It is all what I can say. Sorry for not being to help you on that.

**Comment by dillingham** [comment]
I really hope anyone brave enough to make all these changes every release doesn’t come back here expecting help lol

If anything maintain your own fork

**Comment by alexconesap** [comment]
@dillingham totally agree LOL It started as a 'quick fix' (pre-fork) and it took us to something deeper

**Comment by packytagliaferro** [comment]
Ha, ya I will be waiting until there is a simple fix in the Resource where I can pass where to redirect after save

**Comment by Krato** [comment]
Any update on this?

**Comment by Krato** [comment]
Ok I get it work! I will explain.

First create a new asset for nova. Example `php artisan nova:asset ericlagarda/test-asset`.

In the new js created add:

```js
Nova.booting((Vue, router, store) => {
	router.beforeEach((to, from, next) => {
		if (from.name == 'create' && to.name == 'detail') {
			let newTo = {
				name : 'index',
				params: {
					resourceName: from.params.resourceName
				}
			}
			next(newTo)
		}
		next()
	})
});
```


This will redirect to index insted to detail page. 

Regards 😄

**Comment by ahmedkandel** [comment]
A quicker workaround would be to access the vue router and do as @Krato commented, e.g. if you override Nova's layout.blade.php add the following js with no need to create asset or compile code
```
<script>
    //When create resource via relationship go to the parent details instead of the create child details
    Nova.app._router.beforeEach((to, from, next) => {
        if ((from.name == 'create' || from.name == 'edit') && from.query.viaRelationship != '' && to.name == 'detail' && to.params.resourceName != from.query.viaResource) {
            let newTo = {
                name : 'detail',
                params: {
                    resourceName: from.query.viaResource,
                    resourceId: from.query.viaResourceId,
                }
            }
            next(newTo)
        }
        next()
    });
</script>
```

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by giojkd** [comment]
Anyone was able to update /vendor/laravel/nova/resources/js/views/Update.vue ?

**Comment by giojkd** [comment]
> <script>
>     //When create resource via relationship go to the parent details instead of the create child details
>     Nova.app._router.beforeEach((to, from, next) => {
>         if ((from.name == 'create' || from.name == 'edit') && from.query.viaRelationship != '' && to.name == 'detail' && to.params.resourceName != from.query.viaResource) {
>             let newTo = {
>                 name : 'detail',
>                 params: {
>                     resourceName: from.query.viaResource,
>                     resourceId: from.query.viaResourceId,
>                 }
>             }
>             next(newTo)
>         }
>         next()
>     });
> </script>

I get edit?viaRelationship=&viaResource=&viaResourceId=:212 Uncaught TypeError: Cannot read property '_router' of undefined while trying this

**Comment by davidhemphill** [comment]
This has been added and will be included in the next release. 👍

**Comment by morrislaptop** [comment]
Docs?

**Comment by dkulyk** [comment]
You must explore sources :)

**Comment by krns** [comment]
Your base resource class now has the following methods:

```php
    /**
     * Return the location to redirect the user after creation.
     *
     * @param \Laravel\Nova\Http\Requests\NovaRequest $request
     * @param \App\Nova\Resource $resource
     * @return string
     */
    public static function redirectAfterCreate(NovaRequest $request, $resource)
    {
        return '/resources/'.static::uriKey().'/'.$resource->getKey();
    }

    /**
     * Return the location to redirect the user after update.
     *
     * @param \Laravel\Nova\Http\Requests\NovaRequest $request
     * @param \App\Nova\Resource $resource
     * @return string
     */
    public static function redirectAfterUpdate(NovaRequest $request, $resource)
    {
        return '/resources/'.static::uriKey().'/'.$resource->getKey();
    }
```

**Comment by tumispro** [comment]
I tried redirecting to parent with the following code, but it doesn't seem to do anything. After updating / creating it still goes to the detail page. The methods are being called, and the output is the location I want it to go to.

/**
     * Return the location to redirect the user after creation.
     *
     * @param \Laravel\Nova\Http\Requests\NovaRequest $request
     * @param \App\Nova\Resource $resource
     * @return string
     */
    public static function redirectAfterCreate(NovaRequest $request, $resource)
    {
        //return '/resources/'.static::uriKey().'/'.$resource->getKey();
        return '/resources/'.$request->viaResource.'/'.$request->viaResourceId;
    }

    /**
     * Return the location to redirect the user after update.
     *
     * @param \Laravel\Nova\Http\Requests\NovaRequest $request
     * @param \App\Nova\Resource $resource
     * @return string
     */
    public static function redirectAfterUpdate(NovaRequest $request, $resource)
    {
        //return '/resources/'.static::uriKey().'/'.$resource->getKey();
        return '/resources/'.$request->viaResource.'/'.$request->viaResourceId;
    }

**Comment by krns** [comment]
@tumispro do you really have the latest nova version installed and also [published the assets](https://nova.laravel.com/docs/2.0/installation.html#updating-nova)?

**Comment by giancanuz** [comment]
@krns 
I've updated and published (forced + clear all caches).
actually I just did:
	public static function redirectAfterUpdate(NovaRequest $request, $resource)
	{
		return '/resources/'.static::uriKey();
	}
method gets called, json response gets correct redirect, but it keeps on redirecting in object details.

**Comment by tumispro** [comment]
@krns yes, I have the same issue @giancanuz is experiencing.

**Comment by vayurobins** [comment]
I also have the same issue and am not able to get it to work. I am using Nova version: 2.0.7 | Laravel version: 5.8.26.
I have added the method to my resource: app/Nova/Subscription.php
`public static function redirectAfterCreate(NovaRequest $request, $resource)
    {
        return '/resources/'.$request->viaResource.'/'.$request->viaResourceId;
    }`

**Comment by mikebronner** [comment]
I have added the following to my `App\Nova\Resource` class, so that it applies to all my models, and it works as advertised:

```php

    public static function redirectAfterCreate(NovaRequest $request, $resource)
    {
        if ($request->viaResource) {
            return "/resources/{$request->viaResource}/{$request->viaResourceId}";
        }

        return parent::redirectAfterCreate($request, $resource);
    }

    public static function redirectAfterUpdate(NovaRequest $request, $resource)
    {
        if ($request->viaResource) {
            return "/resources/{$request->viaResource}/{$request->viaResourceId}";
        }

        return parent::redirectAfterUpdate($request, $resource);
    }
```

Thanks everyone above for suggesting this be put into Nova, thanks @davidhemphill for incorporating it!

**Comment by saqueib** [comment]
@davidhemphill Its working fine if you redirect it within nova. But in my case I need to go to frontend so I updated it something like this 

```php
public static function redirectAfterUpdate(NovaRequest $request, $resource)
{
    return route('posts.show', $resource->slug);
}
```

But its redirecting to this: 
> http://localhost:8000/nova/resources/entries/1/http:/localhost:8000/show/my-blog-post-slug

instead of going to:
> http:/localhost:8000/show/my-blog-post-slug

**Comment by vayurobins** [comment]
Will this work?
`public static function redirectAfterUpdate(NovaRequest $request, $resource)
{
    return route('/posts.show', $resource->slug);
}`

**Comment by saqueib** [comment]
@vayurobins its says route undefined

**Comment by vayurobins** [comment]
Ok, maybe:
`public static function redirectAfterUpdate(NovaRequest $request, $resource)
{
    return route('posts.show', '/' . $resource->slug);
}`

**Comment by mihaileu** [comment]
@mikebronner do you know how to redirect back with filters ? 
The case is the following:
1. I am on resource index with filters applied 
2. edit the resource
3. redirect back to the resource index with filters applied

I made the change to go back to the resource index
`return '/resources/'.static::uriKey();`
But how to preserver the previous filters ?

**Comment by mikebronner** [comment]
@mihaileu Good point. I haven't looked at that aspect yet.

**Comment by bigperson** [comment]
@mihaileu Did you manage to implement preserver the previous filters?

**Comment by rvalenzuelaferrada** [comment]
Those who still have problems with the redirection, I have created a package that has been very useful to achieve the redirection to external url. I hope to be helpful.
https://novapackages.com/packages/laramaker/redirect-after-asset

**Comment by sfinktah** [comment]
If you have a use case where you want to dynamically redirect based on where the creation request came from, this small edit to `nova/src/Resource.php` will allow the query parameter `redirectAfterCreate` to be passed via the creation URL:

`Line 611:`
```php
    public static function redirectAfterCreate(NovaRequest $request, $resource)
    {
        // *** added code starts ***
        $parsedUrl = parse_url($request->server('HTTP_REFERER'));
        $query = [];
        if (!empty($parsedUrl['query'])) {
            parse_str($parsedUrl['query'], $query);
            if (!empty($query['redirectAfterCreate'])) {
                // TODO: is this abusable after caller processes with URL::make ?
                return $query['redirectAfterCreate'];
            }
        }
        // *** added code ends ***
        return '/resources/'.static::uriKey().'/'.$resource->getKey();
    }
```

I use it for returning to a custom nova tool after creation:
```vue
                <li><a :href="$url(`/resources/our-articles/new`, {
                          viaResource: 'articles',
                          viaResourceId: article.id,
                          viaRelationship: 'ourArticles',
                          relationshipType: 'hasMany',
                          redirectAfterCreate: 'markle-article',  // <-- magic
                        })
                    ">Repost</a></li>
```
