### ISSUE TITLE
The Select component converts the string value of the option element to an integer value and rounds it up.

### ISSUE THREAD

**Issue by gtoto007** [laravel/nova-issues#5383]
- Laravel Version: 9.31.0
- Nova Version: 4.22.1
- PHP Version: 8.0

### Description:
If I enter a big string id as the value of a `Select::Make` option it is cast as Integer. The problem is that this value is rounded up.

### Detailed steps to reproduce the issue on a fresh Nova installation:

I putted this `1047467647765319680` as option value with `Select::Make` but it is converted in `1047467647765319700` in  html output

Php code
``` 
Select::make('My select field', 'select-id')->options(['1047467647765319680'=>'Server Test']);
```

Html output
```
<select id="select-id">
  <option value="1047467647765319700">Server Test</option>
</select>
```
### what do you expect?
What I expect is that the value in option doesn't change when the select component will generate the html output.

**Comment by bkuhl** [comment]
I ran into this as well over the weekend... simple workaround (though not ideal) was to base64 encode the numeric value.
