### ISSUE TITLE
Not able to compile assets in Card component

### ISSUE THREAD

**Issue by victorpfm** [laravel/nova-issues#539]
When I create a new card (php artisan nova:card acme/card) and try to compile the assets, it freezes.

```
> @ production C:\Users\Victor Paiva\Code\tennis-insights\nova-components\Card
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 95% emitting
```

Windows 10
Node 6.3.0

**Comment by AegirLeet** [comment]
See https://github.com/JeffreyWay/laravel-mix/issues/1126.
Try adding `mix.setPublicPath('./dist');` to your webpack.mix.js.

**Comment by victorpfm** [comment]
It worked! Thanks!
