### ISSUE TITLE
Nova resource Preview does not support Actions

### ISSUE THREAD

**Issue by alekmlynek** [laravel/nova-issues#5394]
- Laravel Version: 9.52.4
- Nova Version: 4.22.0
- PHP Version: 8.1.16
- Database Driver & Version: MariaDB
- Operating System and Version: MacOS Ventura 13.2.1 (M1Pro)
- Browser type and version: FireFox Dev (111) happens in all
- Reproduction Repository: <NA>

### Description:
When previewing a resource, other resource relationships don't have actions even though they do on the index/details page.

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Create 2 Nova resources (User/Address)
- Add an "Action" to Address
- Add an "Address" relationship field under Nova User with ->showOnPreview()
- When User is previewed, Address shows, but Action does not work

Comment:
- My main goal is to actually include actions from the "current" resource, in this case, User.
- Example: If I preview "User", I'd like to see actions associated with "User"

The reason I'm bringing up in conjunction with other resources is that to achieve my first goal, I have to make a cyclical reference to the resource itself, which will then show the resource Action/View/Edit buttons on the preview.

<img width="945" alt="Screenshot 2023-03-09 at 6 49 44 PM" src="https://user-images.githubusercontent.com/4039858/224203816-a6eb30d8-0960-41e9-82bf-60bc173b5247.png">

**Comment by LorenzoSapora** [comment]
Hey @alekmlynek, is this default behaviour right now? Could you show some code? Thanks

**Comment by alekmlynek** [comment]
Correct, this is the default behaviour. I don't have a test project but can make one if required. My only code to show is simply adding this into any nova resource field:

```HasOne::make('Recipient', 'address', 'App\Nova\Commerce\Address')->showOnPreview()```

This is a simple relationship that correctly shows in the preview. The address has one action in the index but not on the preview page as per the screenshot. 

All of my relationships are like this on the preview page. Let me know if you require more, I can put together a demo maybe.

**Comment by crynobone** [comment]
Due to the complexity of the whole feature it won't be possible to make the action usable on modal without doing major rewrite. If we going to change this it would go down the the route of stripping the HasOne field to more suitable for Preview.

**Comment by LorenzoSapora** [comment]
Ah! Thanks @alekmlynek, I wasn't aware the HasOne had that functionality in preview.

**Comment by alekmlynek** [comment]
@crynobone That's fair. This happens with any relationship in the preview, though. Does that imply no relationship action should work in the preview?

Perhaps a feature consideration then. For now, maybe I can add custom buttons to that view or something. Thanks, I'll give it some thought.

**Comment by davidhemphill** [comment]
It's not really intended for `HasOne` and `MorphOne` fields to work like this in the resource preview modal. This indicates a bug when we're filtering which fields should be shown. In an upcoming version of Nova, these fields will throw an exception when attempting to use the `showOnPreview` and `onlyOnPreview` methods.
