### ISSUE TITLE
HasMany relation in resource to itself

### ISSUE THREAD

**Issue by salvisb** [laravel/nova-issues#5396]
- Laravel Version: 10.3.3
- Nova Version: 4.22.2
- PHP Version: 8.1
- Operating System and Version: macOS
- Browser type and version: Google Chrome 111.0.5563.64

### Description:
Nova allows for defining hasMany relations in our resources which point to the same resource (e.g. a task can have sub-tasks of the same resource type). Which is great for building nested lists! However, the issue is that when sorting such a list by some column, that column is not showing as "active".

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Add parent_id field to the create_users_table migration.
2. Add children relation to User model.
3. Add HasMany::make('Children', 'children', self::class) to the User resource.
4. Navigate to the User resource detail view and add a new child User.
5. Now go back to the detail view and sort children by "name".
6. Column sort icon is not showing as "active"

**Comment by crynobone** [comment]
Please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by salvisb** [comment]
Here you go https://github.com/salvisb/nova-issues-5396
