### ISSUE TITLE
No 404 for random resource string in url

### ISSUE THREAD

**Issue by itstrueimryan** [laravel/nova-issues#540]
Given a Resource called Users that has a url like **http://localhost:8000/resources/users**, if you type anything instead of users that isn't an existing resource, it doesn't result in a 404, just blank content (e.g. **http://localhost:8000/resources/apples**).

**Comment by dillingham** [comment]
https://github.com/laravel/nova-issues/issues/208

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release including Index, Detail, Create, Attach, Update, UpdatedAttached, and Lens views. 👍
