### ISSUE TITLE
Nova Scout search returns error

### ISSUE THREAD

**Issue by junioro12** [laravel/nova-issues#541]
We have a simple model that uses Scout and specifically a MySQL Fulltext index with Scout (this package: https://github.com/YABhq/laravel-scout-mysql-driver)

Its working fine when exposed via API on our own controller.

When Nova attempts to search the model, we're getting an error like so:
`Call to a member function all() on null at /home/vagrant/projects/my-project/vendor/laravel/nova/src/PerformsQueries.php:92`

If we drop the "Searchable" trait from the base Model...things work, but obviously not using Scout/Fulltext indexing/retrieval.

Not sure where to go from here...

**Comment by joachimVT** [comment]
Having the same issue, I will try and look into this issue to find out more details.

**Comment by flexchar** [comment]
Same as @junioro12 
Search with Scout trait causes `Call to a member function all() on null`
> Scout (v4.0.4)  + MySQL Driver by yab (v2.0.5) + Nova (v1.1.7).

**Comment by flexchar** [comment]
Second this!

We need **an option to toggle Scout search** DESPITE Searchable trait on any given model.

**Comment by swapnilmonad** [comment]
@daniel-de-wit Thanks for this solution, it works for me.
I would like to know if we can override such customization by extending files into my repository.
So that in future If we upgrade the Nova then we should not miss such patches or we don't need to worry about it.

**Comment by swapnilmonad** [comment]
> @daniel-de-wit Thanks for this solution, it works for me.
> 



> I'm experiencing the same issue using Nova v1.0.16.
> 
> To get it working, i've changed the `initializeQueryUsingScout` in PerformsQueries.php like so:
> 
> ```
> protected static function initializeQueryUsingScout(NovaRequest $request, $query, $search, $withTrashed)
> {
>     $keys = tap(static::applySoftDeleteConstraint(
>         static::newModel()->search($search), $withTrashed
>     ), function ($scoutBuilder) use ($request) {
>         static::scoutQuery($request, $scoutBuilder);
>     })->take(200)->get()->pluck('id');
> 
>     return static::applySoftDeleteConstraint(
>         $query->whereIn(static::newModel()->getQualifiedKeyName(), $keys->all()), $withTrashed
>     );
> }
> ```
> 
> Where the original line:
> 
> ```
> })->take(200)->keys();
> ```
> 
> Changed into this:
> 
> ```
> })->take(200)->get()->pluck('id');
> ```

I would like to know if we can override such customization by extending files into my repository.
So that in future If we upgrade the Nova then we should not miss such patches or we don't need to worry about it.

**Comment by flexchar** [comment]
Just to note, seems like it is solved in the latest versions.

**Comment by davidhemphill** [comment]
I believe this issue should be fixed. Please post a new issue if the issue persists.

**Comment by junioro12** [comment]
Yes...we upgraded Nova a short while ago and this does appear to be fixed...we appreciate your efforts here...thanks!

**Comment by CaddyDz** [comment]
> Second this!
> 
> We need **an option to toggle Scout search** DESPITE _Searchable_ trait on any given model.
> 
> @davidhemphill this could be implemented easily by adding an extra (boolean) variable that defaults to true. And is used as a second check in addition to _searchable_ trait.

In my case, am using null driver for scout but still want to get results using mysql queries, maybe a better implementation of this?

```php
/**
 * Determine if this resource uses Laravel Scout.
 *
 * @return bool
 */
public static function usesScout(): bool
{
	$searchable = in_array(Searchable::class, class_uses_recursive(static::newModel()));
	$scout_enabled = config('scout.driver');
	return $searchable && $scout_enabled;
}
```
