### ISSUE TITLE
forgot and reset password did not use custom path url

### ISSUE THREAD

**Issue by anditsung** [laravel/nova-issues#5411]
using latest nova 4.22.2

looking at the code on ResetPasswordController and ForgotPasswordController did not check the config like LoginController to check for custom path

accessing nova/password/reset will not be redirect to custom path

**Comment by crynobone** [comment]
Unable to replicate, dusk tests run fine locally with the following code: https://github.com/laravel/nova-dusk-suite/commit/d63d234f31569dca59d5959d5124ef362bd78f20

Please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by anditsung** [comment]
https://github.com/anditsung/nova-test/tree/nova_custom_routes

accessing https://nova-test.test/nova/password/reset still return nova page instead redirect to https://nova-test.test/forgot-password.
custom forgot password page already declare on the config file.
on login page forgot password link show the correct link

**Comment by crynobone** [comment]
> accessing https://nova-test.test/nova/password/reset still return nova page instead redirect to https://nova-test.test/forgot-password.

This is never the correct flow.
