### ISSUE TITLE
URL fields do not show 'copy' button when copyable()

### ISSUE THREAD

**Issue by puzzledmonkey** [laravel/nova-issues#5412]
- Laravel Version: 9.52.4
- Nova Version: 4.22.2
- PHP Version: 8.1.12
- Database Driver & Version: n/a
- Operating System and Version: n/a
- Browser type and version: n/a
- Reproduction Repository: n/a

### Description:

URL fields do not show the copy button when copyable() is set (despite the fact that the copyable() function exists)

### Detailed steps to reproduce the issue on a fresh Nova installation:

Create a resource with a URL field with copyable()
`URL::make('Field')->copyable()`

The copy button doesn't display.

**Comment by puzzledmonkey** [comment]
> Only `Text` and `Email` field support and implements `copyable()`. The URL has the method since it extends `Text` but doesn't have the implementation.
> 
> Will make a PR for the method to throw an exception unless we decide to change it during the PR review.

it would be great if you can implement the copy button if possible rather than throwing an exception :)

**Comment by crynobone** [comment]
The issue is similar to `Text::asHtml()` unable to support copyable, since asHtml and URL value itself will contain clickable link.

**Comment by beNjiox** [comment]
Hey @crynobone don't know if legit but I was wondering if it would be possible to provide a way to support copyable() for fields with asHtml.

My idea would be an api that would like this

```php
Text::make('a_field')
	->resolveUsing(fn() => "... html stuf ...")
	->asHtml()
	->copyableUsing(fn() => "... text stuff being copied ...";
```

I don't know well the internals, so maybe this is simply impossible, but I was felt it would be something possible as it would work juste like displayUsing / resolveUsing except for the copied value.

What do you think ?
That would work for all kind of fields and would prevent you guys to patch fields after fields to support copyable.

**Comment by crynobone** [comment]
The issue is not anchor text/html text being copdy but click event bubbles side affect with `@click.prevent.stop`.

**Comment by puzzledmonkey** [comment]
> The issue is not anchor text/html text being copied but click event bubbles side effect with `@click.prevent.stop`.
> 
> https://jsfiddle.net/zoL123fy/

Yes I guess it would need redoing so there's no text inside the copy button and only the icon is inside (and hence clickable) with the HTML text outside CopyButton
