### ISSUE TITLE
I found an non-localizable element

### ISSUE THREAD

**Issue by h-zone** [laravel/nova-issues#5417]
- Laravel Version: 10.3.2
- Nova Version: 4.22.2
- PHP Version: 8.2.0
- Database Driver & Version: PostgreSQL 14
- Operating System and Version: Debian 11.6
- Browser type and version: Firefox Developer v112.0b4

### Description:
i found some hardcoded "selected" values in code...
"selected" is totally hardcoded?

![2023-03-20_15-53-07](https://user-images.githubusercontent.com/1150044/226345443-9a228727-5d17-4bdb-8cc1-9918df00477f.png)

**Comment by crynobone** [comment]
This has been fixed and will be available next release.
