### ISSUE TITLE
Trend metric appends results not present in `$possibleDateResults`

### ISSUE THREAD

**Issue by skollro** [laravel/nova-issues#5419]
- Nova Version: 4.19.5

### Description:
The bug is located in `src/Metrics/Trend.php`, line 518 to 526.

Trend metric merges `$possibleDateResults` with the actual results from the database. If the actual results from the database contain keys that are not present in `$possibleDateResults`, keys without a match in `$possibleDateResults` will be appended to `$results` and mess up the metric. This can happen due to different timezones when creating monthly stats.

### Possible Solution:
Don't merge both arrays, only replace keys that exist in `$possibleDateResults` with actual values from the database.

**Comment by crynobone** [comment]
We need to be able to replicate the issue before making any fix and possibly adding feature tests to cover this issue.

Please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by skollro** [comment]
See https://github.com/skollro/nova-issue-5419
