### ISSUE TITLE
polymorphic resource suddenly stopped showing nested relationships

### ISSUE THREAD

**Issue by margana** [laravel/nova-issues#5424]
- Laravel Version: 10.x
- Nova Version: 4.21.0 - 4.22.2

### Description:

From the change log for 4.21.0  (related issue #5245)
```
Fixed an issue with nested relationships when using HasOne or HasOneThrough fields.
```

While I understand this was undesired behavior in case of HasOne, the change as it was implemented now also affects MorphOne.

For example, consider the following resources:

- House
- Building
- Room

House morphs to Building, which has many Rooms.

You would want the Rooms relationship to be displayed on the House resource, and this was the case until it suddenly stopped working in Nova v4.21.0.

**Comment by crynobone** [comment]
Sorry but we not able to support this request at the moment and the fix is valid. You might need to consider adding custom Resource Tool etc if you want to handle this.
