### ISSUE TITLE
maxlength on fields

### ISSUE THREAD

**Issue by itstrueimryan** [laravel/nova-issues#543]
Any way to add a maxlength attribute on built-in input fields so the user can't type more than what they're allowed?

**Comment by AegirLeet** [comment]
```
Text::make('Foo')
->withMeta(['max' => 123])
```

**Comment by dillingham** [comment]
@AegirLeet that doesnt work. 

@moodslayer Currently you would have to allow any length but add backend validation 

`->rules('required', 'max:255'),`

**Comment by moodslayer** [comment]
@dillingham Yep, that's what I'm doing.  maxlength would be cool to have, enhances the user experience a bit.

**Comment by AegirLeet** [comment]
@dillingham Oh yeah never mind, that only works for max, not maxlength.

**Comment by dillingham** [comment]
Wish `->withMeta('inputAttr', ['maxlength' => 5])` was an option
Where v-bind="inputAttr", would allow this and custom css class appending too

**Comment by AegirLeet** [comment]
@dillingham Yeah that's pretty much what I did for a custom field I built.
The field has a `withAttributes(array $attributes)` method, which merges the `$attributes` into `$this->meta['attributes]` and the Vue component does a `v-bind="field.attributes"`.
It would be pretty great if this worked with built-in fields too.

**Comment by moodslayer** [comment]
> @moodslayer You could add maxlength in TextField.vue and recompile the nova assets.

@AegirLeet Thanks! That works.

**Comment by dillingham** [comment]
Make sure to do that every time you update :)

**Comment by davidhemphill** [comment]
You can set any attributes you like in the latest versions of Nova.

**Comment by tigusigalpa** [comment]
`Text::make('My Field')->withMeta(['extraAttributes' => ['maxlength' => 12]])`
