### ISSUE TITLE
Using Calculated fields on forms

### ISSUE THREAD

**Issue by jryd** [laravel/nova-issues#544]
I see that you can use calculated fields to display values that don't exist in your database.

My app has a couple of models that have columns, for which the value is calculated on the front end.

The front end is powered by Vue, and the value for these fields is calculated based off the values in other fields and when the model is saved or updated these calculated fields are sent in the request to do this (so they are effectively stored in the database).

I'm wanting to replicate these in Nova.

My short term workaround is to just use a number field (as that is what they are), and type the value in if needed, but I'd love to see support for using calculated fields like this.

**Comment by dillingham** [comment]
Can you do something like this?

```php

Number::make()->withMeta([
    'value' => $this->calculatedField()
])`

```

**Comment by jryd** [comment]
@dillingham that would work to set the initial value, however this wouldn't dynamically change on the page as the fields that are used to calculate the value change.

**Comment by dillingham** [comment]
Sounds like you should make a custom field

**Comment by davidhemphill** [comment]
Yep, would suggest using a custom field for this use-case. 👍

**Comment by codebykyle** [comment]
I made this into a custom field if anyone else is looking for this.

https://github.com/codebykyle/calculated-field
