### ISSUE TITLE
Trix replication is not working - Replicate Resource

### ISSUE THREAD

**Issue by BryanMeurisse** [laravel/nova-issues#5441]
- Laravel Version: 9.19
- Nova Version: 4.0
- PHP Version: 8.1.0

### Description:
When you replicate a resource, the Trix field is not replicated for the new resource, it's empty.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Create a resource with a Trix field, put anything you liek inside.
Try to replicate the resource
The new resource will have an empty Trix field

**Comment by crynobone** [comment]
Any fields implementing `Laravel\Nova\Contracts\Deletable` interface are not able to be replicated. The interface indicates that the field contains uploaded/stored content which should be unique for each row.

However, I going to make a PR to ensure that it would affect `Markdown` or `Trix` field unless it's used with `->withFiles()`

**Comment by potsky** [comment]
@BryanMeurisse here is a workaround:

```php
    public function replicate()
    {
        return tap(parent::replicate(), function ($resource) {
            /** @var NewsModel $model */
            $model = $resource->model();
            $model->your_trix_or_markdown_fields_without_files = $this->model()->your_trix_or_markdown_fields_without_files;
        });
    }
```
