### ISSUE TITLE
Belongsto peekable not working

### ISSUE THREAD

**Issue by jobjen02** [laravel/nova-issues#5444]
- Laravel Version: 10.4.1
- Nova Version: 4.22.2
- PHP Version: 8.1.0
- Database Driver & Version: Postgress
- Operating System and Version: #.#
- Browser type and version: Google chrome
- Reproduction Repository: https://github.com/###/###

### Description:
The peekable function is not working for me, and it never worked. I have multiple belongsto relationships. Also the ->peekable() doesn't work.

### Detailed steps to reproduce the issue on a fresh Nova installation:
I don't know...

**Comment by Navi2016** [comment]
Same, using laravel 10, latest Nova in firefox.

**Comment by jobjen02** [comment]
> 

You have to use the peekable method on the fields that are peekable, not that clear in the docs.

**Comment by jobjen02** [comment]
> Same, using laravel 10, latest Nova in firefox.


You have to use the peekable method on the fields that are peekable, not that clear in the docs.
