### ISSUE TITLE
Licence Reminders

### ISSUE THREAD

**Issue by gepopp** [laravel/nova-issues#5453]
I Just received all 3 Licencsnse-Reminder-Email ( 90 das, 30 days and 3 days ) wihtin a minute!!
The license has allready exired!
You point out, in that emails, that a license is not a subscription, but all dashbaords are now showing the "unregistered" hint again,
is that the way u try to force a rebuy?

**Comment by puzzledmonkey** [comment]
same here - i'm seeing 'unregistered' on all the sites dashboard. i cannot even do a composer install with the old license key, even though in the emails it promises no problems.

this should be a very high priority issue for the team now as all sites which supported financially are now being made to look like cheaters and cannot be built by CI/CD pipelines that install from composer.lock.

**Comment by bkuhl** [comment]
Came here to report the same thing.  Also, the logo is broken in the email

**Comment by puzzledmonkey** [comment]
Very disappointing that 12 hours later the 'unregistered' message is istill not fixed, and was obviously never tested (along with the now-fixed installation issues documened above). Any idea of an ETA @crynobone ?

**Comment by crynobone** [comment]
Hi there,

Issues with downloading Laravel Nova after expiry and Unregistered have been solved. To avoid any issues you can lock your dependencies by running the following command:

composer require "laravel/nova:4.22.2"

----

For any future search, please refer to your license's "last update until" and compare it with the release date from https://nova.laravel.com/releases

**Comment by mwerder** [comment]
I'm also running into this error during deployment!

`Failed to download laravel/nova from dist: The "https://nova.laravel.com/dist/laravel/nova/laravel-nova-xxx.zip" file could not be downloaded (HTTP/2 404 )`

@crynobone I'm on laravel/nova v3.32.0 as our license is only valid until version 3 and it stopped working as well now. How can I fix it as I cannot use v4.22.2?
![nova_license](https://user-images.githubusercontent.com/16059443/230386223-b027f249-057b-4661-8723-02aa46521e24.png)

**Comment by crynobone** [comment]
Hi there,

This issue has been fixed and you should be able to download Nova 3 using Composer again. Sorry for the inconvenience.
