### ISSUE TITLE
Notification bell not showing

### ISSUE THREAD

**Issue by HeadStudios** [laravel/nova-issues#5456]
- Laravel Version: latest version
- Nova Version: 4
- PHP Version: 8.2
- Database Driver & Version: MySQL
- Operating System and Version: Ubuntu
- Browser type and version: Chrome (latest version)
- Reproduction Repository: (mine is set to prive since I have some API keys that got exposed)

### Description:
https://share.getcloudapp.com/JrupOqzd

### Detailed steps to reproduce the issue on a fresh Nova installation:
Every install is the same

**Comment by crynobone** [comment]
![CleanShot 2023-04-06 at 12 45 31](https://user-images.githubusercontent.com/172966/230274282-b5f99309-c704-494a-ba03-5ef4279daa03.gif)

Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by HeadStudios** [comment]
Hi,

I have created a Laravel public repo here:
https://github.com/HeadStudios/issueno-5456-nova

Does this help at all?

**Comment by HeadStudios** [comment]
Hi Crynobone, 

Please find the public repo as per your request:
https://github.com/HeadStudios/issueno-5456-nova

**Comment by crynobone** [comment]
@HeadStudios never share repo with Nova's source code.

**Comment by HeadStudios** [comment]
> HeadStudios

Added you as collaborator to private repo

**Comment by crynobone** [comment]
@HeadStudios why can't you send in a public repo without Nova's source code? Similar to https://github.com/nova-issues

**Comment by HeadStudios** [comment]
Hi, please find public repo below:

https://github.com/HeadStudios/novaissue-5456-nonova

**Comment by crynobone** [comment]
https://github.com/HeadStudios/novaissue-5456-nonova/blob/2abedd928748ae1f4211862164e8d411f6eab036/app/Providers/NovaServiceProvider.php#L26-L31

See the documentation: https://nova.laravel.com/docs/4.0/customization/notifications.html#disabling-notifications

**Comment by HeadStudios** [comment]
Thank you this has fixed my issue. Appreciate the quick response.
