### ISSUE TITLE
Confirmation text of a destructive action is red

### ISSUE THREAD

**Issue by salvisb** [laravel/nova-issues#5457]
- Laravel Version: 10.3.3
- Nova Version: 4.22.2
- PHP Version: 8.2.3
- Browser type and version: 111.0.5563.146

### Description:

According to the documentation https://nova.laravel.com/docs/4.0/actions/defining-actions.html#destructive-actions, destructive actions should show red button, but not the confirmation text. I would expect that custom destructive actions look the same way as default delete action does - red button and grey confirmation text.

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Run `php artisan nova:action DeleteUserAction --destructive`
2. Add DeleteUserAction to the User resource.
3. Navigate to a User detail view and click on "Delete User Action".

ER: Confirmation text is grey.
AR: Confirmation text is red.

**Comment by crynobone** [comment]
Please add some screenshots to what's you referring here.
