### ISSUE TITLE
Laravel\Nova\PerformsValidation - messed TValidationRule template param

### ISSUE THREAD

**Issue by vognev** [laravel/nova-issues#5459]
- Laravel Version: not relevant
- Nova Version: 4.22.2
- PHP Version: not relevant
- Database Driver & Version: not relevant
- Operating System and Version: not relevant
- Browser type and version: not relevant
- Reproduction Repository: https://psalm.dev/r/89c875d422

### Description:

TValidationRule template param of mentioned trait seems broken and causing psalm to throw a fatal error when analyzing codebaze.

**Comment by crynobone** [comment]
Duplicate of #5448
