### ISSUE TITLE
Reference underlying model within LENS fields function

### ISSUE THREAD

**Issue by michaelchunn** [laravel/nova-issues#546]
I have a computed field that works fine in LENS until you click on one of the sortable fields.  Then the resource changes.

dump from fields after running LENS.

```
App\Nova\Lenses\Order\ActiveOrdersLens {#990
  +name: null
  +resource: App\Order {#703
    #fillable: array:2 [
      0 => "order_status"
      1 => "study_status"
    ]
    #casts: array:1 [
      "order_status_at" => "datetime"
    ]
    #appends: array:1 [
      0 => "patient_name"
    ]
    #connection: "mysql"
...
```

dump after sorting the index by selecting one of the sortable fields.

```
App\Nova\Lenses\Order\ActiveOrdersLens {#536
  +name: null
  +resource: {#533}
  +seeCallback: null
}
```

**Comment by davidhemphill** [comment]
Sorry, but we are unable to debug your issue without a reproducible code example. Once you provide that we can open this up again.
