### ISSUE TITLE
Laravel Nova 4.23 issue while updating

### ISSUE THREAD

**Issue by mateusz-peczkowski** [laravel/nova-issues#5460]
- Laravel Version: 10.5.1
- Nova Version: 4.23
- PHP Version: 8.1

### Description:
I've noticed a bug on the screenshot. Then I checked UI and it seems you today released a new Nova version BUT the file that composer is trying to download doesn't exists: https://nova.laravel.com/dist/laravel/nova/laravel-nova-6a14d83663f0484889a7f73ffaed7262bba7a26a-zip-1df780.zip

<img width="1752" alt="Zrzut ekranu 2023-04-7 o 20 40 17" src="https://user-images.githubusercontent.com/6013516/230660671-52ff4532-f897-4e19-b51f-3af18c9e6922.png">

It's not a problem with auth.json as I have my config already there and previous version works perfectly

**Comment by rjarnutowski** [comment]
I am running into the same issue

**Comment by kon3ko** [comment]
same issue

**Comment by zdharris** [comment]
Same here.

**Comment by StanBarrows** [comment]
The manual download does not work as well.

![CleanShot 2023-04-07 at 22 12 03@2x](https://user-images.githubusercontent.com/10268813/230672801-d85cfa3a-0212-45f7-bb31-a1b172464708.png)

**Comment by crynobone** [comment]
Hi there,

This issue should be fixed now, can you try again? Sorry for the inconvenience.

**Comment by mateusz-peczkowski** [comment]
No problem ;) It seems right now working perfectly :) You can close this topic :) Thank you!
