### ISSUE TITLE
MorphMany create from relationship returns 404

### ISSUE THREAD

**Issue by markpavia** [laravel/nova-issues#5468]
- Laravel Version :9.19
- Nova Version: 4.23

### Description:
I have products model with relationship to discount using morhpMany. When trying to create a discount via products resource, it returns 404

![image](https://user-images.githubusercontent.com/6967014/231541026-b4a12442-2343-4246-945e-ec300255eb2b.png)
![image](https://user-images.githubusercontent.com/6967014/231539863-10cefd27-fe92-4801-b427-cdfe90cde1b5.png)
![image](https://user-images.githubusercontent.com/6967014/231539907-eedea329-3405-4010-b7df-3f32bbfeede4.png)

### Detailed steps to reproduce the issue on a fresh Nova installation:

`Product Model`
```php
public function discounts()
{
    return $this->morphMany(Discount::class, 'discountable');
}
```
`Product Resource`
```php
MorphMany::make('Discounts')
```

`Discount Model`
```php
public function discountable()
{
    return $this->morphTo();
}
```
`Discount Resource`
```php
MorphTo::make('Discountable')
                ->types([
                    Product::class
                ])
```

**Comment by crynobone** [comment]
Unable to replicate the issue and we added dusk test to cover this usage: https://github.com/laravel/nova-dusk-suite/blob/10.4/tests/Browser/CreateWithPolymorphicTest.php
