### ISSUE TITLE
Can't upload a image

### ISSUE THREAD

**Issue by atmacoder** [laravel/nova-issues#547]
Image::make('image')->disk('public'),

![default](https://user-images.githubusercontent.com/43233531/45476512-c5916000-b747-11e8-94b9-45ae87e2f5e6.png)

This image could not be found.

![default](https://user-images.githubusercontent.com/43233531/45476494-ba3e3480-b747-11e8-9b29-72768f172bc0.png)

storage folder is empty
![default](https://user-images.githubusercontent.com/43233531/45476379-73e8d580-b747-11e8-934e-d6f9a46577f4.png)

db was updated with filename
![default](https://user-images.githubusercontent.com/43233531/45476319-5c115180-b747-11e8-8e79-21c5daf69eef.png)

**Comment by AegirLeet** [comment]
Did you look in _storage/app/public_?
Did you link the public storage using `php artisan storage:link` as described [here](https://laravel.com/docs/5.7/filesystem#the-public-disk)?

**Comment by atmacoder** [comment]
> 
> 
> Did you look in _storage/app/public_?
> Did you link the public storage using `php artisan storage:link` as described [here](https://laravel.com/docs/5.7/filesystem#the-public-disk)?

thx php artisan storage:link helps
