### ISSUE TITLE
Missing Translation

### ISSUE THREAD

**Issue by Joorren** [laravel/nova-issues#5474]
- Nova Version: 4.23.0

### Description:
One of the strings used in the [Laravel Password Reset flow](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Auth/Notifications/ResetPassword.php#L75-L83) isn't provided in the default json translation file, all the others are present.
`This password reset link will expire in :count minutes.` is the missing string.

**Comment by crynobone** [comment]
Nova's password reset email doesn't contain those line.
