### ISSUE TITLE
Conditionally disable global-search for resources

### ISSUE THREAD

**Issue by JapSeyz** [laravel/nova-issues#550]
Add the possibility for conditionally disabling the global-search for a resource.

Having different user-roles may forbid a role from editing a certain resource. It would then make sense to prevent those from showing up in the global-search bar.

Currently you can hack it in in by doing something like:

```php
 /**
     * Build a Scout search query for the given resource.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @param  \Laravel\Scout\Builder  $query
     * @return \Laravel\Scout\Builder
     */
    public static function scoutQuery(NovaRequest $request, $query)
    {
        // Don't display uneditable resource for user
        if (! auth()->user()->can('edit model')) {
            return $query->where('id', 0)->take(0);
        }

        return $query;
    }
```

However this will still query your Scout Query Provider, and in case it's algolia, use-up one of your queries for no reason.

**Comment by dillingham** [comment]
@JapSeyz see [Scout Filtering](https://nova.laravel.com/docs/1.0/resources/authorization.html#scout-filtering)

**Comment by taylorotwell** [comment]
I don't see any way we could practically do this for all resources?

**Comment by basepack** [comment]
Maybe we can disable the global search per resource only. Or Nova takes the Policies into account. Looks like a small addition to the codebase?

**Comment by farwish** [comment]
```
public static $globallySearchable = false;
```

Actually if all resources' globallySearchable are set false, the global search input form will be removed automaticity.
