### ISSUE TITLE
filterable makes browser to crash

### ISSUE THREAD

**Issue by arturasfrontit** [laravel/nova-issues#5501]
- Laravel Version: 10.9
- Nova Version: 4.23
- PHP Version:  8.1.18
- Database Driver & Version: mysql 8
- Operating System and Version: ubuntu 22.04
- Browser type and version: newest firefox, chrome

### Description:
Resource crashes browser after some time.

![image](https://user-images.githubusercontent.com/131424569/235342575-9df8ebc2-ebe9-489e-8108-ba430d1ae280.png)

After some debuging, I find out that `filterable` causes an issue. Field doesn't appear in filters and after some time browser crashes

```
BelongsTo::make(__('Customer'), 'customer', Customer::class)
    ->exceptOnForms()
    ->hideFromDetail()
    ->sortable()
//                ->filterable()
    ->required(),
```

Field dont work in update too. No results
![image](https://user-images.githubusercontent.com/131424569/235344880-ccec8ec3-a1de-47a5-91bb-22e8dd0ee568.png)

Also I noticed that some customers doesn't display, because those records are deleted, but after restoring them problem still appears: Browser crashes, and field doesn't display in filters list
![image](https://user-images.githubusercontent.com/131424569/235343351-8d42b0d8-251a-437c-973b-52ae3f9e451f.png)

```
public function customer(): BelongsTo
{
    return $this->belongsTo(Customer::class);
}
```

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by arturasfrontit** [comment]
> Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

I think it crashed, because table had 100k items, and there `searchable` was noit called
