### ISSUE TITLE
Layout/Auth.vue doesnt respect darkMode

### ISSUE THREAD

**Issue by whipsterCZ** [laravel/nova-issues#5505]
- Laravel Version: >10
- Nova Version: 4.22
- PHP Version: 8.2

### Description:
If i have selected Dark mode i cant see my AppLogo ( it uses svg with  `fill="currentColor"`) so my logo is Black on dark background....

but i the layout `/vendor/laravel/nova/resources/js/layouts/Auth.vue` there is hardcoded class `text-black` for color property...

```
<template>
  <div class="py-6 px-1 md:px-2 lg:px-6">
    <div class="mx-auto py-8 max-w-sm flex justify-center text-black">
      <AppLogo class="h-8" />
    </div>
...
```

I have spent 8+ hours to override this behaviour and due the architecture I was unable to do it...

can you please fix it ? its one-liner..

And it will be cool to have option how to override these Layouts somehow....

### FIX #####
Just remove this class.. everything works as expected...
```
    <div class="mx-auto py-8 max-w-sm flex justify-center ">
```

**Comment by simon-roland** [comment]
@whipsterCZ Check out https://github.com/Muetze42/nova-assets-changer

It lets you override the vue components of Nova 4
