### ISSUE TITLE
Is there a way to make Markdown fields show on index?

### ISSUE THREAD

**Issue by adnanchowdhury** [laravel/nova-issues#552]
I have a Markdown field in which the text that is added isn't too long, but may still need some text formatting. I would therefore like to be able to show it on index. 

How can I do this?

**Comment by unxsist** [comment]
You can create a new Nova field with `artisan nova:field` and let it extend the `\Laravel\Nova\Fields\Markdown` field. Make sure you override the `$showOnIndex` property and set it to `true`. 

In your fields.js file adjust the index component name to `index-markdown-field` as this is what component will be resolved on the index pages.

Adjust the IndexField.vue file to make your values render as markdown. See below for an example:

```js
<template>
    <span v-html="renderedValue"></span>
</template>

<script>
  const md = require('markdown-it')()

  export default {
    props: ['resourceName', 'field'],

    computed: {
      renderedValue () {
        return md.render(this.field.value)
      }
    }
}
</script>
```

If it's not clear, let me know. I can hook you up with a sample repo.

**Comment by adnanchowdhury** [comment]
> You can create a new Nova field with `artisan nova:field` and let it extend the `\Laravel\Nova\Fields\Markdown` field. Make sure you override the `$showOnIndex` property and set it to `true`.
> 
> In your fields.js file adjust the index component name to `index-markdown-field` as this is what component will be resolved on the index pages.
> 
> Adjust the IndexField.vue file to make your values render as markdown. See below for an example:
> 
> ```js
> <template>
>     <span v-html="renderedValue"></span>
> </template>
> 
> <script>
>   const md = require('markdown-it')()
> 
>   export default {
>     props: ['resourceName', 'field'],
> 
>     computed: {
>       renderedValue () {
>         return md.render(this.field.value)
>       }
>     }
> }
> </script>
> ```
> 
> If it's not clear, let me know. I can hook you up with a sample repo.

Thanks for your help, I did as you suggested and got it working!
