### ISSUE TITLE
BelongsToMany actions not working 

### ISSUE THREAD

**Issue by BeiAduo** [laravel/nova-issues#5523]
- Laravel Version: 10
- Nova Version: 4.24.2
- PHP Version: 8.2
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:

BelongsToMany::make('Roles')
    ->actions(function () {
        return [
            new Actions\MarkAsActive,
        ];
    })

### Detailed steps to reproduce the issue on a fresh Nova installation:

https://nova.laravel.com/docs/1.0/resources/relationships.html#pivot-actions

**Comment by crynobone** [comment]
https://github.com/laravel/nova-dusk-suite/blob/389fe13e50664cc1592d2b4884d5b598bdf734f0/app/Nova/User.php#L183-L199

We already have dusk tests covering this usage: https://github.com/laravel/nova-dusk-suite/blob/master/tests/Browser/PivotActionTest.php

Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)
