### ISSUE TITLE
Cannot use object of type `Laravel\Nova\Support\PendingTranslation` as array using `Select` with `searchable()`

### ISSUE THREAD

**Issue by crynobone** [laravel/nova-issues#5524]
still seeing this issue with:
```Country::make('Country Code')->default('DE')->searchable()->filterable()```

error:

```
    "message": "Cannot use object of type Laravel\\Nova\\Support\\PendingTranslation as array",
    "exception": "Error",
    "file": "/Users/max/project/vendor/laravel/nova/src/Fields/Select.php",
    "line": 121,
```

laravel: 9.52.7
nova: 4.24.2 (Silver Surfer)

_Originally posted by @mstaack in https://github.com/laravel/nova-issues/issues/5514#issuecomment-1543434507_

**Comment by jobjen02** [comment]
Please fix this ASAP
