### ISSUE TITLE
Navigating to resource detail page causes 404 when resource uses large id as string

### ISSUE THREAD

**Issue by nhaynes** [laravel/nova-issues#5527]
- Laravel Version: 9.52.7
- Nova Version: 4.24.0
- PHP Version: 8.1.16
- Database Driver & Version: Mysql
- Operating System and Version: Ubuntu 22.04.1
- Browser type and version: Google Chrome 112.0.5615.165
- Reproduction Repository: https://github.com/nhaynes/nova-issue-5527

### Description:

We have some models where we are using [Snowflake IDs](https://en.wikipedia.org/wiki/Snowflake_ID) instead of the standard integer ids. The implementation is pretty much the same as the [HasUuids](https://github.com/laravel/framework/blob/be0478dea96a6619bb77676f36f67c1500846b17/src/Illuminate/Database/Eloquent/Concerns/HasUuids.php#L8) option that ships with Laravel but instead of Uuids, you get snowflake ids. 

This has been working well for us with Nova until the 4.24.0 update. It seems a change in that release started casting our snowflake IDs as integers and so a Snowflake ID like `171392037059436224` becomes `171392037059436220` once the value is supplied to the Vue front-end. This in turn breaks the links to our resource detail pages because it's the wrong id. 

We've run into this ourselves and so we treat our snowflake IDs as strings in PHP and javascript code:

```php
    /**
     * Casts the Snowflake ID as a string.
     */
    protected function id(): Attribute
    {
        return Attribute::make(
            get: fn ($value) => (string) $value,
            set: fn ($value) => (int) $value,
        );
    }
```

I did some digging around in the `vendor` folder I believe it's line 57 in the `Util.php` file that is causing the problem.

### Detailed steps to reproduce the issue on a fresh Nova installation:

- Create a Model and override the ID so it returns the id s a string
- Create a Model record with the id `171392037059436224`
- Create a Nova resource for that model and view `171392037059436220` as the ID

**Comment by crynobone** [comment]
Can you provide a reproducing repository for this issue? and are you specify the model key type attribute to `string`?

**Comment by nhaynes** [comment]
Here is the reproducing repository: https://github.com/nhaynes/nova-issue-5527

**Comment by nhaynes** [comment]
I tried making use of [asBigInt](https://nova.laravel.com/docs/4.0/resources/fields.html#id-field) on the `ID::make()` field and that appears to fix the issue for the ID field but if you make any references to that Resource using a `BelongsTo` the problem occurs on those `BelongsTo` fields and results in a 404.

**Comment by crynobone** [comment]
Will be available on the upcoming release.
