### ISSUE TITLE
Image Field Error

### ISSUE THREAD

**Issue by lefrancois** [laravel/nova-issues#553]
A form with an Image Field can not be saved without changing image.

Just on Safari (Chrome works fine)

JS Error Message: 
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'e.t0.response.status')

**Comment by AegirLeet** [comment]
See https://github.com/laravel/nova-issues/issues/378.
I posted a fix over there as well.

**Comment by lefrancois** [comment]
Thank you @AegirLeet 
Works perfect!
