### ISSUE TITLE
Bug when using MorphTo relationship on select fields

### ISSUE THREAD

**Issue by DanielDK100** [laravel/nova-issues#5530]
- Laravel Version: 9.52.7
- Nova Version: 4.23.0
- PHP Version: 8.2.6
- Database Driver & Version: MySQL 8.0.33
- Operating System and Version: Linux Mint 21.1
- Browser type and version: Google Chrome 113.0.5672.92

### Description: We have the following relationships in a Nova resource: 
We are experiencing a bug most likely caused by a recent update to Nova since this functionality has worked before in older versions. 

```php
BelongsTo::make('Subject')->readonly(),
MorphTo::make('Target a special value', 'valuable')->types([
    SubjectParameter::class,
    Condition::class,
])->nullable(),
```

**Scenario**
The user has two select fields. When one value is changed in the first select field (the user can chose between SubjectParameter or Condition), the values in the second select field should then be populated by _only_ the relevant data that _belongs_ to the Subject class AND is of a specific morph type (either SubjectParameter or Condition). However, when the user opens the second select field it ignores the relationship to the Subject relation and returns all data - thus making the second select field completely filled with irrelevant data.

I hope this makes sense.
Is this a known bug or is there a solution to this issue?

**Comment by crynobone** [comment]
I don't think I can reproduce this issue.

Can you please provide a reproducing repository with example of such usage.
