### ISSUE TITLE
Unable to limit and order unions

### ISSUE THREAD

**Issue by ArtyomBist** [laravel/nova-issues#5540]
- Laravel Version: 8.8
- Nova Version: 3.26.1
- PHP Version: 8.2
- Database Driver & Version: MySQL, 8
- Operating System and Version: doesn't matter
- Browser type and version: doesn't matter
- Reproduction Repository: https://github.com/laravel/framework/pull/3901

### Description:
Unable to limit and order unions (see last comment)

### Detailed steps to reproduce the issue on a fresh Nova installation:
Create any query in resource with Union
https://github.com/laravel/framework/pull/3901

**Comment by crynobone** [comment]
We no longer support and making any release for Nova 3.

**Comment by ArtyomBist** [comment]
> We no longer support and making any release for Nova 3.

but what about nova 4?
