### ISSUE TITLE
Image field does not render webp files in edit mode

### ISSUE THREAD

**Issue by nhaynes** [laravel/nova-issues#5541]
- Laravel Version: 9.52.7
- Nova Version: 4.24.2
- PHP Version: 8.1.16
- Database Driver & Version: Mysql
- Operating System and Version: Ubuntu 22.04.1
- Browser type and version: Google Chrome 112.0.5615.165
- Reproduction Repository: N/A

### Description:

The [Image field ](https://nova.laravel.com/docs/4.0/resources/file-fields.html#images) accepts [.webp](https://www.iana.org/assignments/media-types/image/webp) file format and displays them properly in the **Index** and **Detail** views but when they are viewed in the **Create** or **Edit** mode, they show as a generic icon. Other image formats like `.png` show in all views just fine. This issue appears to exist regardless if using `public` disk or `s3`. 

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Add an `Image` field to any resource.
2. Upload a `.webp` file.
3. View the generic icon in **Create** and **Edit** views.

---

### Create View
![Nova Create View](https://github.com/laravel/nova-issues/assets/3440002/720705c0-3ae3-4c27-a305-213455551e34)

### Edit View
![Nova Edit View](https://github.com/laravel/nova-issues/assets/3440002/55732ac5-fcb9-447c-a108-d3f860ced36a)

### Detail View
![Nova Detail View](https://github.com/laravel/nova-issues/assets/3440002/2e92aab5-ff7b-41e8-b1ec-8e4c53a4614d)

### Index View
![Nova Index View](https://github.com/laravel/nova-issues/assets/3440002/f8e5a411-a420-4890-b2a2-bfb62f6ab1d7)

**Comment by sagamez48** [comment]
Hi, I've found out the reason of this issue.

The file:
`vendor/laravel/nova/resources/js/composables/useFilePreviews.js`

Line: 4
It needs to be updated.

From:
`const imageTypes = ['image/png', 'image/jpeg', 'image/gif', 'image/svg+xml']`

To:
`const imageTypes = ['image/png', 'image/jpeg', 'image/gif', 'image/svg+xml', 'image/webp']`
