### ISSUE TITLE
Peekable formatting error

### ISSUE THREAD

**Issue by niekdemelker** [laravel/nova-issues#5546]
- Laravel Version: 10.11.0
- Nova Version: 4.24.3
- PHP Version: 8.2.5
- Database Driver & Version: -
- Operating System and Version: Pop! OS 22.04
- Browser type and version: firefox 112.0.1 (64-bits)
- Reproduction Repository: Private

### Description:

in Nova 4.24.1 the render of the peekable popup looked like this and is just fine.
![afbeelding](https://github.com/laravel/nova-issues/assets/17333258/7017cb96-79cb-4ef1-a4c7-868be6148f57)

after the update to version 4.24.2 the popup went to this, no margin on the sides. not as fancy to the eye (and a horizontal scroll bar)
![afbeelding](https://github.com/laravel/nova-issues/assets/17333258/25b79e6a-d28b-41fb-a42c-c09387dd9912)

if is place the css file from the 4.24.1 in a 4.24.3 installation, the peekable looks like the first picture again.

### Detailed steps to reproduce the issue on a fresh Nova installation:
just make a peekable field and take a peek

**Comment by crynobone** [comment]
Doesn't seem to be reproducible with 4.23.3 

![image](https://github.com/laravel/nova-issues/assets/172966/96209542-6791-4844-a3bc-9bb571228670)

**Comment by puzzledmonkey** [comment]
definitely reproducible with 4.23.3

for me, removing the -mx-6 class from the peekable fields make it look normal again.

**Comment by niekdemelker** [comment]
@puzzledmonkey Yes, found out the same thing. the `-mx-6` seems to have gotten higher preference, and doesn't seem necessary at al

![afbeelding](https://github.com/laravel/nova-issues/assets/17333258/5d7d238a-b307-455d-a7e6-35735ea0fe8c)

**Comment by crynobone** [comment]
Looks like Tailwind was updated between those version but isn't updated on
`package-lock.json`

**Comment by puzzledmonkey** [comment]
how is this not reproducible in your tests then @crynobone ? it seems like it's working fine according to your screenshot above?

**Comment by crynobone** [comment]
Because locally we are utilizing `npm ci` which explicitly follows `package-lock.json`. I believe the changes occur during version compilation build (as we don't commit `public` assets during dev).
