### ISSUE TITLE
dependsOn() Trix field does not update his value if setValue is called

### ISSUE THREAD

**Issue by jansgescheit** [laravel/nova-issues#5547]
- Laravel Version: 9.52.7
- Nova Version: 4.24.3
- PHP Version: 8.1.14
- Database Driver & Version: mysql
- Operating System and Version: docker for mac
- Browser type and version: chrome 113.0.5672.92

### Description:

When a Trix field uses dependsOn to set a new Value, the new value is not displayed in the UI.
When I look at the HTTP request, I see the new value. It seems that the frontend component does not update the view.

### Detailed steps to reproduce the issue on a fresh Nova installation:

```php
/**
 * Get the fields available on the action.
 *
 * @param  NovaRequest  $request
 * @return array
 */
public function fields(NovaRequest $request): array
{
    $messages = [
        0 => 'This is message 1',
        1 => 'This is message 2',
        2 => 'This is message 3',
    ];

    return [
        Select::make('Template', 'template')
            ->options([
                0 => 'Selection 1',
                1 => 'Selection 2',
                2 => 'Selection 3',
            ]),

        Trix::make('Message', 'content')
            ->dependsOn('template', function (Trix $field, NovaRequest $request, FormData $formData) use ($messages) {
                if ($formData->template === null) {
                    return;
                }
                $value = $messages[$formData->template];
                $field->setValue($value);
            })
            ->required(),
    ];
}
```

The Action responses looks good. 

Choose Option `Selection 1` 

```json
{
    "attribute": "content",
    "component": "trix-field",
    "dependentComponentKey": "trix.trix-field.content",
    "dependsOn": {
        "template": 0
    },
    "displayedAs": null,
    "fullWidth": false,
    "helpText": null,
    "indexName": "Message",
    "name": "Message",
    "nullable": false,
    "panel": null,
    "placeholder": null,
    "prefixComponent": true,
    "readonly": false,
    "required": true,
    "sortable": false,
    "sortableUriKey": "content",
    "stacked": false,
    "textAlign": "left",
    "uniqueKey": "content-default-trix-field",
    "usesCustomizedDisplay": false,
    "validationKey": "content",
    "value": "This is message 1",
    "visible": true,
    "wrapping": false,
    "shouldShow": false,
    "withFiles": false
}
```

Choose Option `Selection 3` 

```json
{
    "attribute": "content",
    "component": "trix-field",
    "dependentComponentKey": "trix.trix-field.content",
    "dependsOn": {
        "template": 2
    },
    "displayedAs": null,
    "fullWidth": false,
    "helpText": null,
    "indexName": "Message",
    "name": "Message",
    "nullable": false,
    "panel": null,
    "placeholder": null,
    "prefixComponent": true,
    "readonly": false,
    "required": true,
    "sortable": false,
    "sortableUriKey": "content",
    "stacked": false,
    "textAlign": "left",
    "uniqueKey": "content-default-trix-field",
    "usesCustomizedDisplay": false,
    "validationKey": "content",
    "value": "This is message 3",
    "visible": true,
    "wrapping": false,
    "shouldShow": false,
    "withFiles": false
}
```

### Expectation

The Trix field should display the new value if set in a `dependsOn`

**Comment by crynobone** [comment]
Trix doesn't support two-way bindings. https://github.com/basecamp/trix/issues/86

There is some hack suggested in the comment but nothing official from Trix (it remains an undocumented feature) and may stop working in future release: https://github.com/basecamp/trix/pull/99

**Comment by jansgescheit** [comment]
thanks, but one way binding would be enough for me 😄

**Comment by crynobone** [comment]
>thanks, but one way binding would be enough for me 

The issue above can only be solved with 2 way binding.

**Comment by jansgescheit** [comment]
> Trix doesn't support two-way bindings. [basecamp/trix#86](https://github.com/basecamp/trix/issues/86)
> 
> There is some hack suggested in the comment but nothing official from Trix (it remains an undocumented feature) and may stop working in future release: [basecamp/trix#99](https://github.com/basecamp/trix/pull/99)

I don't quite understand the "hack", also apparently the syntax has changed since 2028. If the hack works since 2018, why doesn't Nova use the hack? If it no longer works you are at the same state as now
