### ISSUE TITLE
Validation messages not using custom labels

### ISSUE THREAD

**Issue by erikrorstrom** [laravel/nova-issues#556]
When defining a custom label for a field, the validation message still uses the database column.

![image](https://user-images.githubusercontent.com/6515113/45504765-0f4f6a00-b78b-11e8-9262-f1255a79a776.png)

**Comment by dillingham** [comment]
I can't figure out how to remove an item from the messageBag or else this would work haha

```php
public static function afterValidation(NovaRequest $request, $validator)
{
    $messageBag = $validator->getMessageBag();

    $error = $messageBag->first('name');

    $messageBag->add('name', str_replace('name', 'new-key', $error));
}
```

![errors](https://user-images.githubusercontent.com/29180903/45512376-9392f480-b76d-11e8-9282-a7a866f9c32b.PNG)

**Comment by davidhemphill** [comment]
The official solution right now is to use custom validation messages: https://laravel.com/docs/5.7/validation#custom-error-messages. Looking into a way to support inline custom messages.
