### ISSUE TITLE
Inline action button (three dots) shows when no inline actions available

### ISSUE THREAD

**Issue by rderks88** [laravel/nova-issues#5565]
- Laravel Version: 8.12
- Nova Version: 4.24.*
- PHP Version: 8

### Description:
When Nova 4.23 is installed, it shows no button (three dots) on the right side of a record in the index.
When Nova 4.24 is installed, it shows the button (three dots) on the right side of a record on the index, regardless if that record has inline actions.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Install Nova 4.24, create any model and add at least one record. Turn of any actions (including preview). You will still see three dots.

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by crynobone** [comment]
Based on output from #5592 it seems that this could be possible if your project uses `outl1ne/nova-sortable`, see https://github.com/outl1ne/nova-sortable/issues/172
