### ISSUE TITLE
Missing resource id after upgrade to Nova 4.24.4

### ISSUE THREAD

**Issue by BlackVulcan** [laravel/nova-issues#5567]
- Laravel Version: 9.52.7
- Nova Version: 4.24.4
- PHP Version: 8.1.19
- Database Driver & Version: n/a
- Operating System and Version: n/a
- Browser type and version: n/a
- Reproduction Repository: https://github.com/BlackVulcan/nova-4-deponds-on-action-issue

### Description:

After upgrading the Nova in our application from 4.23.0 to 4.24.4 we noticed that some of our actions where no longer working. After debugging the issue we noticed that the dependsOn calls to the back-end no longer contains the resourceId or the resources parameter. We need this so that we can filter an action based on the option the user selects inside of the Action and also the relations to the resource on which the action needs to run. The Reproduction Repository contains two tags of which 4.23.0 is working and 4.24.4 is broken. 

### Detailed steps to reproduce the issue on a fresh Nova installation:

- Create a new action with two  fields
- Add two fields inside the action
- Let one field depend on another field
- Change the field and see that the resourceId is no longer being send.

**Comment by BlackVulcan** [comment]
When I try your code snippet inside the Reproduction Repository I see that it works for the initial request without any issue:

![afbeelding](https://github.com/laravel/nova-issues/assets/2300342/c471efcc-33f1-43b5-9977-a2a7945c6a61)

But when i change the initial field to be anything else, I am missing the original resource id

![afbeelding](https://github.com/laravel/nova-issues/assets/2300342/ccd716d4-f055-42a0-b978-6a8a8fd38db8)
![afbeelding](https://github.com/laravel/nova-issues/assets/2300342/8c14994b-a0ca-45f2-b021-301f3570187f)

However it seems to be working on the index page as on this page the request still contains the resources[] parameter:

![afbeelding](https://github.com/laravel/nova-issues/assets/2300342/5160aea8-373a-43fa-ba31-e627c15340d9)
![afbeelding](https://github.com/laravel/nova-issues/assets/2300342/88713259-ea5c-4cc0-9bc0-643dcb021aab)

This was the original request nova sends in 4.23.0 to the back-end on the resource detail page

![afbeelding](https://github.com/laravel/nova-issues/assets/2300342/37efbd11-54db-41e6-994a-95f0a68ac963)

**Comment by BlackVulcan** [comment]
I did a recording of the bug and uploaded it to youtube if that helps https://youtu.be/eP2e9Vy0yiA

But as you can see in the video I checked the 4.24.4 tag out inside the repository and updated the code to contain the snippet you supplied in the first comment.

After which I went to the index page of the user resource (CTRL+F5) and tried to work with the action. This can be seen between 0:17 and 0:23 inside the video. The id of the resource `1` was always appended to the result.

After testing this on the index page I repeated the same steps on the detail page for user `1`. However if I change the input of the action on that screen I get null appended to the test input. And if I look in the network tab of the developers console I see that there is no resources[] parameter in the query

**Comment by BlackVulcan** [comment]
And here is a video of doing it on 4.23.0 of Nova: https://youtu.be/J-NWTi0R-MY

**Comment by LintonAchmad** [comment]
+1

**Comment by LintonAchmad** [comment]
We also have this issue - 

We using `HasMany` and when we select all on the index view and then call an action, all the records in the resource are selected instead of the records for the relationship.

these params seem to by missing from the Request URL - `viaResource=xx&viaResourceId=xx&viaRelationship=xx`

**Comment by puzzledmonkey** [comment]
is this fixed in Nova 4.25.0? in the release notes it claims:

"Fixed an issue where selected resources were missing on action fields."

but i am still seeing the same issue with 4.25.1

**Comment by crynobone** [comment]
Avoid issue has been tested and the exact use case has been included in our dusk tests:

https://github.com/laravel/nova-dusk-suite/blob/a8d8b8c645dd75539bdf43db37e4c877914805f3/tests/Browser/DependentActionFieldTest.php#L172-L214

**Comment by puzzledmonkey** [comment]
> Above issue has been tested and the exact use case has been included in our dusk tests:
> 
> https://github.com/laravel/nova-dusk-suite/blob/a8d8b8c645dd75539bdf43db37e4c877914805f3/tests/Browser/DependentActionFieldTest.php#L172-L214

thanks @crynobone 

in that case, my feature request (or is it a bug now?) at https://github.com/laravel/nova-issues/discussions/5549 is NOT a duplicate of this.

using dependsOn fields in an action, the PATCH request when a field changes, does NOT include the selected resources[] in the request.

**Comment by crynobone** [comment]
I not able to replicate that and it looks the same to this. May be worth it to add reproducing repository to show what's missing (not considering it a feature request at the moment).

**Comment by puzzledmonkey** [comment]
thanks @crynobone you are right - i was checking on the old 4.24 version actually, my bad. sorry to waste your time!
