### ISSUE TITLE
Resource named Dashboard causes resource index page issues

### ISSUE THREAD

**Issue by d-pollard** [laravel/nova-issues#5577]
- Laravel Version: 10.12.0
- Nova Version: 4.x
- PHP Version: 8.2.5
- Database Driver & Version: MySQL 8.0.32
- Operating System and Version: MacOS 13.3.1 M1
- Browser type and version: Firefox
- Reproduction Repository: N.A

### Description:
I have a model named Dashboard; naming a nova resource Dashboard causes an error. but renaming it to Dash fixes the issue

![Screenshot 2023-05-26 at 4 58 00 PM](https://github.com/laravel/nova-issues/assets/16292606/c1c7a3b1-83e5-4d43-85e9-0a2ec371c183)

Example of it working when renamed to Dash

![Screenshot 2023-05-26 at 4 58 47 PM](https://github.com/laravel/nova-issues/assets/16292606/13d66270-2641-4ce8-928d-9e8ae8c629b8)

**Comment by crynobone** [comment]
Dashboard has been listed as reserved name not to be use: https://nova.laravel.com/docs/4.0/resources/#defining-resources

You can either rename the class or use custom uri by adding `uriKey()` method to the resource.
