### ISSUE TITLE
Unable to save resource when Flexible Content Field is hidden and has value

### ISSUE THREAD

**Issue by HeadStudios** [laravel/nova-issues#5578]
Laravel Version: 9
Nova Version: 4
PHP Version: 8.2
Database Driver & Version: MySQL
Operating System and Version: MacOS Big Sur
Browser type and version: Version 113.0.5672.126 (Official Build) (arm64)
Reproduction Repository: https://github.com/HeadStudios/novaissue-5456-nonova
### Description:

When Nova Flexible Field is hidden in a panel (or elsewhere) the resource cannot be updated if the Flexible Field contains a value.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Make Campaign.php model with code like so:
https://github.com/HeadStudios/novaissue-5456-nonova/blob/main/app/Models/Campaign.php
Note the FFMPEG flexible field within the panel fields

Video for context: https://p147.p4.n0.cdn.getcloudapp.com/items/d5uDBGmX/05bd1580-5b42-4ef1-8c77-b0c3650235db.mp4?v=c5f4eef7f3d90ef61fcc88e166837603

**Comment by crynobone** [comment]
We don't provide support for 3rd party package issues.
