### ISSUE TITLE
Nova resources can be edited despite authorizedToUpdate is set to false

### ISSUE THREAD

**Issue by ramonrietdijk** [laravel/nova-issues#5580]
- Laravel Version: v10.12.0
- Nova Version: 4.22.2
- PHP Version: 8.2.6

### Description:

Nova resources can still be edited if `authorizedToUpdate` returns `false`. The edit button disappears and the shortcut `e` do not work anymore as expected. Accessing the direct edit link however, e.g. `/nova/resources/users/1/edit`, does work and saves the model.

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Open the default `User` resource.
2. Add the following to the class:

```php
public function authorizedToUpdate(Request $request)
{
    return false;
}
```

3. Open the edit page of the resource manually via the URL and save any modifications.

**Comment by crynobone** [comment]
FYI, we don't document overriding this method and always would suggest user to refer to our documentation.

 `authorizeTo*` is used during form submission and not `authorizedTo*` since it only used on JSON response to indicate whether the edit button should be displayed.
