### ISSUE TITLE
Row selection becomes unresponsive

### ISSUE THREAD

**Issue by LorenzoSapora** [laravel/nova-issues#5583]
- Laravel Version: 10.*
- Nova Version: 4.24.4
- PHP Version: 8.1

The row selector appears to be broken, once a row has been selected, the menu itself becomes unresponsive, only to become responsive again when rows have been cleared.

![selector](https://github.com/laravel/nova-issues/assets/25519274/49616a96-7e8a-481f-9cff-5a64859af801)

**Comment by crynobone** [comment]
Unable to reproduce the issue,  and we already have dusk tests covering this usage.

Please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)
