### ISSUE TITLE
Need to add json options to JOSN fields.

### ISSUE THREAD

**Issue by dkulyk** [laravel/nova-issues#559]
Unicode chars isn't human readable.
![image](https://user-images.githubusercontent.com/370042/45520155-b7335a80-b7c0-11e8-86cd-6c8c7b1663cc.png)

It would not be bad to add parameters for JSON:
```php
Code::make(__('Strings'), 'strings')
    ->json(JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT)
```
By default put `JSON_PRETTY_PRINT`

**Comment by taylorotwell** [comment]
Fixed in upcoming release.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in an upcoming release.
