### ISSUE TITLE
Dots button is showing even if no items 

### ISSUE THREAD

**Issue by valentinrougier39** [laravel/nova-issues#5592]
Laravel Version: 9.52.4
    Nova Version: 4.24.1
    PHP Version: 8.1

Hi, 
in my Nova Resource in Index view, dots button is showing even if there is no items inside : I've disable replicate,... and I haven't action to show in this dropdown. 
Do you have a solution to hide dots button please ? 
Thank you

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by valentinrougier39** [comment]
I have this problem on MacOs Ventura with Firefox and Chrome. I give you versions on the hour

**Comment by crynobone** [comment]
Versions doesn't matter here. We need reproducing code to debug the issue. 

Nova already includes dusk tests to cover this issue and none are failing so we need to replicate your issue, to do that we need reproducing code.

**Comment by mstaack** [comment]
having the same issue, trying to reproduce it on a fresh install

**Comment by valentinrougier39** [comment]
In Nova/Resource.php
`   public function authorizedToReplicate(Request $request): bool
    {
        return false;
    }`

This command disable all replicate button in all resource because I don't need replication. And in my resource I use fields method to display my resource fields : 
`    public function fields(NovaRequest $request)
    {
        return [
            ID::make()->sortable(),
            Text::make('XXXX', 'xxx'),
            Text::make('XXXX', 'xxx'),
            Date::make('XXXX', 'xxx'),
            Email::make('XXXX', 'xxx'),
            Text::make('XXXX', 'xxx'),
        ];
    }`

If you want an another part of code, tell me. Thanks

**Comment by crynobone** [comment]
@valentinrougier39  That's already covered by our dusk tests

https://github.com/laravel/nova-dusk-suite/blob/ef250a225fc82f0892885d6f0ea117435b4e8e15/app/Nova/Captain.php#L147-L156

https://github.com/laravel/nova-dusk-suite/blob/ef250a225fc82f0892885d6f0ea117435b4e8e15/tests/Browser/InlineActionDropdownTest.php#L29-L44

**Comment by valentinrougier39** [comment]
Sure, but I've this result.
![Capture d’écran 2023-06-06 à 09 07 40](https://github.com/laravel/nova-issues/assets/62744879/2fde9477-7be1-48f9-a718-a48b0cbd7d4d)

**Comment by crynobone** [comment]
It could be caused by 3rd party packages, which we don't have control and unable to offer support.

**Comment by crynobone** [comment]
@valentinrougier39 See https://github.com/outl1ne/nova-sortable/issues/172
