### ISSUE TITLE
Help text not visible on a HasMany field

### ISSUE THREAD

**Issue by sanderbaas** [laravel/nova-issues#5595]
- Laravel Version: 8.83.27
- Nova Version: 4.24.4
- PHP Version: 8.1.16
- Database Driver & Version: Mysql 8.0
- Operating System and Version: Ubuntu 22.04
- Browser type and version: Firefox 113.0.1
- Reproduction Repository: https://github.com/Partybussen/has-many-help-bug

### Description:
I've added a help text to a HasMany field, but the help text is not visible on the detail page.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Use the reproduction repo. Follow the steps in the readme. After login, you will be redirected to a Customer page where the HasMany field is visible. There you can see that the help text is not visible.

**Comment by davidhemphill** [comment]
A HasMany field isn't represented in the form view, so there's nothing to show. Where would you expect the help text to be shown in the UI?

**Comment by sanderbaas** [comment]
> A HasMany field isn't represented in the form view, so there's nothing to show. Where would you expect the help text to be shown in the UI?

I would expect it on the detail page, not the form page. A Panel can have a help text that is visible just below the panel title. I would expect it works the same way for a HasMany field.

**Comment by sanderbaas** [comment]
@davidhemphill Or should this be a feature request?
