### ISSUE TITLE
The same "Actions" transaction used for different context

### ISSUE THREAD

**Issue by alies-dev** [laravel/nova-issues#5597]
- Nova Version: 4.25.1 (but actually ANY)

### Description:

"Actions" translation key-value used for 2 completely different cases:
1. Header of Nova actions available at the index page when few resources selected using checkboxes
2. Header of the morph field for associated `\Laravel\Nova\Actions\ActionResource` models (when `\App\Modules\Logging\Models\Actionable` trait is used by app's models)

<img width="1292" alt="image" src="https://github.com/laravel/nova-issues/assets/5278175/f16e06ad-5301-4f35-8b26-73d51b86e007">

<img width="1273" alt="image" src="https://github.com/laravel/nova-issues/assets/5278175/8e257a2e-16a0-46bf-b5bc-09737f2bad43">

There is also a bunch of related issues:
 - https://github.com/laravel/nova-issues/issues/5422
 - https://github.com/laravel/nova-issues/issues/1198

**Comment by davidhemphill** [comment]
I couldn't replicate this issue on the later version of Nova. The labels seem to be correctly translated using Nova's translation feature. Please post a more-thorough issue if you find the issue persists.
