### ISSUE TITLE
BelongsToMany filterable() - Not working on detail page

### ISSUE THREAD

**Issue by TNDJX** [laravel/nova-issues#5605]
- Laravel Version: 9.48.0
- Nova Version: 4.21.0
- PHP Version: 8.1

### Description:

BelongsToMany `filterable()` method is not working correctly on the detail page.
Looking at the logged queries they don't make any sense when filtering on the detail page

https://github.com/laravel/nova-issues/assets/57906002/9a396c66-a44d-437b-8ca0-2ce8cd85c0c5

### Detailed steps to reproduce the issue on a fresh Nova installation:

To reproduce this issue you will need to have 3 resources here is an example of connections and setup

User:
```
User Model
public function bookings(): HasMany
  {
      return $this->hasMany(Booking::class);
  }

User resource
HasMany::make(__('Bookings'), 'bookings', Booking::class),
```

Booking:
```
Booking Model
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function tables(): BelongsToMany
    {
        return $this->belongsToMany(Table::class);
    }

Booking Resource
   BelongsTo::make(__('User'), 'user', User::class),

  BelongsToMany::make(__('Tables'), 'tables', Table::class)
                ->filterable(),
```

Table
```
Table Model
    public function bookings(): BelongsToMany
    {
        return $this->belongsToMany(Booking::class);
    }
```

**Comment by crynobone** [comment]
Please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by TNDJX** [comment]
@crynobone  Here is a reproducing repository 

https://github.com/TNDJX/nova-issue-5605

I have added a database seeder as well so you can run migrate and seed and should be good to go. 

You will notice that when going on the `Bookings` resource and use the `Tables` filter you will get correct results

But when going on `Users` resource and scroll down to `Bookings` relation if you apply `Tables` filter either no results or wrong results will be shown
