### ISSUE TITLE
Trend metrics are not interactive

### ISSUE THREAD

**Issue by alexdemers** [laravel/nova-issues#5607]
I'm running the latest version of Nova 4. I think I've read the documentation enough that I don't see why my trend graphic are not interactive such as hovering over the plots and showing the date. It is only a static image. See screenshot below.

<img width="399" alt="image" src="https://github.com/laravel/nova-issues/assets/1834344/24a1f871-ae9f-4fe3-8e70-055d39ead009">

Here's the code below, which is pretty straight-forward.

```php

<?php
class TotalPlayTime extends Trend
{
    public function calculate(NovaRequest $request): TrendResult
    {
        $builder = Event::where('type', 'track.listened')
            ->where('params->seconds', '>', 0);

        if ($request->model()::class === User::class) {
            $builder->where('user_id', $request->resourceId);
        } elseif ($request->model()::class === Track::class) {
            $builder->where('params->track_id', $request->resourceId);
        }

        return $this->sumByDays($request, $builder, 'params->seconds')
            ->showSumValue()
            ->transform(fn($value) => $value / 60 / 60)->suffix('heures')
            ->withoutSuffixInflection();
    }

    public function ranges()
    {
        return [
            1 => __('Aujourd\'hui'),
            7 => __('Cette semaine'),
            30 => __('30 jours'),
            60 => __('60 jours'),
            365 => __('365 jours'),
        ];
    }

    public function uriKey()
    {
        return 'total-plays-per-day';
    }

    public function name(): string
    {
        return 'Nb. heures par jour';
    }
}
```

How do I make them interactive like the documentation shows? Thanks.

**Comment by crynobone** [comment]
Hi there,

The metric above looks different from what's available on a default Laravel Nova installation.

Please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by alexdemers** [comment]
Well, apparently setting the colors in the config file as hex values breaks this. Got it working.
