### ISSUE TITLE
Textfield asHtml not work in action

### ISSUE THREAD

**Issue by approached** [laravel/nova-issues#561]
Hi @ all

i try to add a textfield asHtml but it doesn't work in **actions**.

Example

```php
    public function fields()
    {
        return [
            Text::make('Hello', function () {
                return 'Hello World';
            })->asHtml(),
        ];
    }
```

In resource classes it works perfect. Reference: #280

**Comment by davidhemphill** [comment]
Computed text fields don't display on forms of any kind. They're only for showing on the index/detail pages.
