### ISSUE TITLE
Code Field does not work correctly with RTL direction

### ISSUE THREAD

**Issue by waadmawlood** [laravel/nova-issues#5615]
- Laravel Version: 10.13.5
- Nova Version: 4.25.1
- PHP Version: 8.1.20
- Operating System and Version: Ubuntu 22.04
- Browser type and version: Chrome, Firefox, Edge

### Description:
Code field doesn't show data JSON if the direction was rtl

LTR
![image](https://github.com/laravel/nova-issues/assets/44348636/c21b9ed1-19d3-4ca7-8f25-80ce72582037)

RTL
![image](https://github.com/laravel/nova-issues/assets/44348636/d632e3c8-c85f-4207-9312-84393c07ac7e)

I used this code

```php
Code::make(__('Properties'), 'properties')->json(JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE)
```

I tried this code but to no avail
```php
Code::make(__('Properties'), 'properties')->json(JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE)
                ->withMeta(['extraAttributes' => ['style' => 'direction: ltr']]),

// ------------

Code::make(__('Properties'), 'properties')->json(JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE)
                ->textAlign('left'),
```

**Comment by crynobone** [comment]
I not familiar with writing "code" in RTL but is there where code should be displayed as RTL?

**Comment by waadmawlood** [comment]
> I not familiar with writing "code" in RTL but is there where scenario where code should be displayed as RTL?

Alright, I used multi locales by auto-switch locale package [https://github.com/badinansoft/nova-language-switch](https://github.com/badinansoft/nova-language-switch) that switches direction with locale

- Arabic -> RTL direction
- English -> LTR direction

**Comment by crynobone** [comment]
My question is, should the Code field content display get converted to RTL or should we enforced LTR?

**Comment by waadmawlood** [comment]
> My question is, should the Code field content display get converted to RTL or should we enforced LTR?

I just want the icon to appear in any direction. It's better to force the LTR.
