### ISSUE TITLE
Nova Relatable Query return wrong type

### ISSUE THREAD

**Issue by lakridserne** [laravel/nova-issues#5617]
- Laravel Version: 9.52.0
- Nova Version: 4.0
- PHP Version: 8.1

### Description:
When using a `relatableQuery`, I get a wrong type returned. So I type hinted the relatable query to always return a Builder, however, I got errors that it returned my model.

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Set up a few models and a relatable query.
- Type hint to builder
- Load in Nova and see the error

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)
