### ISSUE TITLE
Number field with value 0 is not pre-filled while editing

### ISSUE THREAD

**Issue by niveshsaharan** [laravel/nova-issues#562]
I am having a weird issue with Number field. I am creating a Free Plan for customers and Nova is not pre-filling the value 0 while editing.

This is how I created the field:

`Number::make('Price')->rules(['numeric'])->displayUsing(function ($price) {
				return '$' . number_format($price / 100, 2);
			})->sortable(),`

Here is the JSON response:

`{attribute:"price",
component:"text-field",
indexName:"Price",
name:"Price",
panel:null,
prefixComponent:true,
sortable:true,
textAlign:"left",
type:"number",
value:0
}`

Screenshot:
![image](https://user-images.githubusercontent.com/2552126/45541804-a1a84a00-b82d-11e8-8221-806edbb780e6.png)

**Comment by bonzai** [comment]
#122
#444
#500

**Comment by imlida** [comment]
same issues

**Comment by dillingham** [comment]
confirmed / reproduced | related https://github.com/laravel/nova-issues/issues/562 https://github.com/laravel/nova-issues/issues/840 https://github.com/laravel/nova-issues/issues/500 https://github.com/laravel/nova-issues/issues/122 https://github.com/laravel/nova-issues/issues/951 https://github.com/laravel/nova-issues/issues/444
