### ISSUE TITLE
Metric with `refreshWhenFiltersChange` refresh twice on detail page with relations

### ISSUE THREAD

**Issue by tonyputi** [laravel/nova-issues#5621]
- Laravel Version: 10.13.5
- Nova Version: 4.25.1
- PHP Version: 8.2.4
- Database Driver & Version: Maria DB 10
- Operating System and Version: Ventura 13.3.1
- Browser type and version: Chrome Browser 114.0.5735.133 (Official Build) (arm64)
- Reproduction Repository: https://github.com/###/###

### Description:
Metrics with `refreshWhenFiltersChange = true` refresh twice when shown on a detail resource page that contains relations.
The problem is not happening if relation is HasOne or MorphOne cause no relation filters are present.

Note: The metrics are refresh also if user change a filter on one of the relation and I'm not sure that is correct. Maybe would be nice to let the developer choose if he want that metric refresh on relation filter change as well.

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Create one resource;
2. Define some relation such as BelongsToMany or HasMany;
3. Define a metric using `->refreshWhenFiltersChange()` and `->onlyOnDetail()`;
4. Try to go on the detail page of the given resource and metrics should refresh twice;

```
...

public function fields(NovaRequest $request)
{
    ID::make(),

    Text::make('Name', 'name'),

    HasMany::make('Relation Name', 'relationName', RelationResource::class)
}

...

public function cards(NovaRequest $request)
{
    return [
        TotalUsers::make()
            ->onlyOnDetail()
            ->refreshWhenFiltersChange(),
    ];
}

...
```

**Comment by crynobone** [comment]
I not familiar with this use case. Please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by tonyputi** [comment]
Ok I'll provide a fresh laravel/nova repository.

**Comment by tonyputi** [comment]
Here the [repository:](https://github.com/tonyputi/example-nova-app)
After checking out you can run `php artisan migrate --seed`
URL: http://localhost/nova
username: test@example.com
password: password

I understand what you are saying but I'm using the same metrics on index and detail and I don't think is correct to have some logic to disable the `refreshWhenFilterChange` if the user is on detail. On my application I have something like 130 metrics used across multiple resources and even if I can find a workaround I still think this is some wrong behaviour on Nova side. 
Do you agree that many other people can be affected by the same issue?

More over I can see that `refreshWhenFiltersChange` is not accepting a closure and this will make difficult to find a workaround if I don't want to duplicate the metrics just to disable the filter for detial.

``` 
/**
 * Set whether the metric should refresh when filter changed.
 *
 * @param  bool  $value
 * @return $this
 */
public function refreshWhenFiltersChange($value = true)
{
    $this->refreshWhenFiltersChange = $value;

    return $this;
}
```

Here you will find a video that shows the metrics request are duplicated on detail page but if is not enough you can clone the example-nova-app repo and try by your self. I'm sorry for the quality of the video but I cannot upload file more than 10 mb

https://github.com/laravel/nova-issues/assets/8282385/2ad4a78f-e0c1-4215-ae8f-3a3d6ca89595

**Comment by crynobone** [comment]
But why would you need to use `refreshWhenFiltersChange` on those metrics? If there no usage then I would argue we should consider throwing exception when we try to use both methods.

**Comment by tonyputi** [comment]
Look a simple workaround could be on Metric.php:

```
    /**
     * Prepare the metric for JSON serialization.
     *
     * @return array<string, mixed>
     */
    public function jsonSerialize(): array
    {
        return array_merge(parent::jsonSerialize(), [
            'class' => get_class($this),
            'name' => $this->name(),
            'uriKey' => $this->uriKey(),
            'helpWidth' => $this->getHelpWidth(),
            'helpText' => $this->getHelpText(),
            'refreshWhenActionRuns' => $this->refreshWhenActionRuns,
            'refreshWhenFiltersChange' => !$this->onlyOnDetail ? $this->refreshWhenFiltersChange : false,
        ]);
    }
```

**Comment by crynobone** [comment]
The best solution is to not use the combo.

**Comment by tonyputi** [comment]
Hey @davidhemphill can you please give your opinion here?
