### ISSUE TITLE
Delete confirm modal not reset loading state when has error

### ISSUE THREAD

**Issue by giangnh13579** [laravel/nova-issues#5623]
- Laravel Version: Laravel Framework 9.27.0
- Nova Version: 4.18.2
- PHP Version: 8.1.8
- Browser type and version: Version 114.0.5735.110 (Official Build) (64-bit)

### Description:
- Delete confirm modal not reset loading state if any error thrown

### Detailed steps to reproduce the issue on a fresh Nova installation:
- I'm creating a delete feature for a resource called AcUser. This resource has a HasMany relationship with other resources. When I try to delete an AcUser, I have to remove all the related relationships associated with the AcUser resource. To accomplish this, I've modified the delete method in UserPolicy.php. In the index view, the delete button will always be displayed (if the user has the permission to delete). When the user confirms the delete action (by calling the Nova delete API), I will check if there are any relationships associated with the resource. If there are any, an exception will be thrown.
- My code in policy class which worked fine:
```php
    public function delete(User $user, Model $acUser)
    {
        $result = Nova::whenServing(function (NovaRequest $request) use ($user, $acUser) {
            if ($request instanceof DeleteResourceRequest) {
                $canDelete = $this->hasPermissionToDelete($user) && !$acUser->hasAcUserProfile();
                if (!$canDelete) {
                    throw new InfoException(__('No Permission'));
                }
                return true;
            } elseif ($request instanceof ResourceIndexRequest) {
                return $this->hasPermissionToDelete($user);
            } else {
                return null;
            }
        });
        return is_null($result)
            ? $this->hasPermissionToDelete($user) && $acUser->hasAcUserProfile()
            : $result;
    }
```

- After trying delete resource has relationship, exception thrown:

![image](https://github.com/laravel/nova-issues/assets/132031200/a39483fe-8fa1-4838-9e98-377bbe44067a)

- But when I try to delete again, confirm button is still loading

![image](https://github.com/laravel/nova-issues/assets/132031200/3ccdebc0-54c6-4a0e-a28e-e0bead9c317e)

- It seems, when call delete api (by axios in frontend), `catch()` method is not put after call api to handle error case to reset loading state of model

**Comment by puzzledmonkey** [comment]
this happens also for non-destructive actions, i.e. when throwing an error on an observer's 'restoring' method for example, the restore popup also has the 'Confirm' button locked in the 'loading' (3 dots) state.
