### ISSUE TITLE
Action name is not support Chinese

### ISSUE THREAD

**Issue by imlida** [laravel/nova-issues#563]
Action name is not support Chinese, when set the running button will turn gray.

**Comment by 907544030** [comment]
overwrite it on your action
```
    public function uriKey()
    {
        return str_slug(Nova::humanize($this));
    }
```

**Comment by imlida** [comment]
> overwrite it on your action
> 
> ```
>     public function uriKey()
>     {
>         return str_slug(Nova::humanize($this));
>     }
> ```

thank you!

**Comment by alexbowers** [comment]
@davidhemphill This can be closed.

**Comment by dillingham** [comment]
@alexbowers this can be closed
