### ISSUE TITLE
Menusection badge mobile scroll sticky

### ISSUE THREAD

**Issue by jobjen02** [laravel/nova-issues#5632]
- Laravel Version: 10.13.5
- Nova Version: 4.25.1
- PHP Version: 8.1.0
- Database Driver & Version: Postgresql
- Operating System and Version: MacOS, docker container
- Browser type and version: Chrome, 114.0.5735.133
- Reproduction Repository: -

### Description:
When scrolling though the menu on mobile, the badge on a menuSection is sticky and doesn't scroll with the rest of the content.

### Detailed steps to reproduce the issue on a fresh Nova installation:

`
MenuSection::make(__('Section'), [
                    MenuItem::make(__('Item'), 'resources/item'),
                ])
                    ->withBadge(function () {
                        return __('New!');
                    }, 'success')
`

https://github.com/laravel/nova-issues/assets/25797291/341c8a74-c724-4f87-a840-376973f28ce8

**Comment by davidhemphill** [comment]
Not able to reproduce this. There's likely a third-party package or custom CSS causing this issue.

https://github.com/laravel/nova-issues/assets/58970/1227efab-5a58-4a80-b149-68927f369a9b

**Comment by lubnik2005** [comment]
Looks like it got fixed the latest version https://nova.laravel.com/releases/4.27.14, thanks!
