### ISSUE TITLE
URL Field filterable() not working

### ISSUE THREAD

**Issue by TNDJX** [laravel/nova-issues#5636]
- Laravel Version: 9
- Nova Version: 4.25.1
- PHP Version: 8.0

### Description:

`filterable()` Not working on `Laravel\Nova\Fields\URL`

### Detailed steps to reproduce the issue on a fresh Nova installation:

- Define `Laravel\Nova\Fields\URL` on any resource
- Set field to be filterable with method `filterable()`

### Expected result
Have URL filter on index page that we can search

### Actual result
No filter is shown

**Comment by crynobone** [comment]
`URL` field extends `Text` field and I don't experience any issues with it:

https://github.com/laravel/nova-issues/assets/172966/4dba6372-f71a-474b-a9e6-d4949fe7484f

Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)
