### ISSUE TITLE
Trashed

### ISSUE THREAD

**Issue by Enmaboya** [laravel/nova-issues#564]
![default](https://user-images.githubusercontent.com/32259003/45547981-b4be1880-b833-11e8-9f1c-f4372a213a42.png)

why do I display Trashed in filters?
I did not include it.
and how to remove it

**Comment by AegirLeet** [comment]
Are you using the `Illuminate\Database\Eloquent\SoftDeletes` trait in your Models? If you are, the "Trashed" filter will be displayed automatically and allow you to filter for soft-deleted models.

**Comment by Enmaboya** [comment]
> 
> 
> Are you using the `Illuminate\Database\Eloquent\SoftDeletes` trait in your Models? If you are, the "Trashed" filter will be displayed automatically and allow you to filter for soft-deleted models.

can you tell me, is there a way to hide this filter?

**Comment by AegirLeet** [comment]
Override the `softDeletes` method in your resource:
```
public static function softDeletes()
{
    return false;
}
```

I'm pretty sure that should hide the filter while keeping the soft-deletes functional, but you should definitely do some testing.

**Comment by davidhemphill** [comment]
@Enmaboya Currently pagination and the soft-deleting filters are hard-coded. Can you explain what circumstance in your project would lead you to not wanting to be able to access soft-deleted resources?

**Comment by aurawindsurfing** [comment]
Yes that is correct. With Trashed should be visible based on user permissions.

**Comment by mortezarajabi** [comment]
This may do the job. Add it to the App/Nova/Resource.php 

```
public static function softDeletes()
{
    if (static::authorizable() and Gate::check('restore', get_class(static::newModel()))) {
        return parent::softDeletes();
    }

    return false;
}
```

**Comment by NioTeX** [comment]
I believe this ticket should be re-opened, since there is a very good reasons for the features existence.
I'm not saying it should be a high priority, but definitely something that should be developed in the future. 

What are your thoughts @davidhemphill ?

**Comment by gvsrepins** [comment]
@davidhemphill, can you please check this request? 

Thanks in advance!

**Comment by rossmcneil** [comment]
Is there a way to revert this how it used to function before this update? We have a use case for where users don't have permission to force delete but we still need them to be able to view trashed records. Has been working perfectly for us with 10+ admin staff and now that functionality is broken. Possibly related: https://github.com/laravel/nova-issues/issues/2492

**Comment by vesper8** [comment]
related.. is there a way to set the default for the filter, I would like the filter to default to "with trashed"

**Comment by shaun381** [comment]
Is there a way to change the default text from 'Trashed' and 'With Trashed', it's pretty bad English.

**Comment by azariah001** [comment]
@shaun381 Australian here. My users have literally no idea what With Trashed means. Especially in the context of a software program, and neither did I until I started probing the documentation. Why not just say With Deleted? Delete is the keyword of the setting so why is the UI saying Trashed?! We could really do with some regionalisation here.

**Comment by elev8studio** [comment]
@azariah001 You can do this in the translation files.. see `resources/lang/vendor/nova/en.json` 
There are 3 instances where the word Trashed is used. Just change the value in the key/value pair, as below: 
```json
{
  "Only Trashed": "Only Deleted",
  "With Trashed": "With Deleted",
  "Trashed": "Deleted"
}
```
Hope that helps! Just figured this out myself.

**Comment by azariah001** [comment]
> @azariah001 You can do this in the translation files.. see `resources/lang/vendor/nova/en.json`
> There are 3 instances where the word Trashed is used. Just change the value in the key/value pair, as below:
> 
> ```json
> {
>   "Only Trashed": "Only Deleted",
>   "With Trashed": "With Deleted",
>   "Trashed": "Deleted"
> }
> ```
> 
> Hope that helps! Just figured this out myself.

You Legend. Thank you :)
