### ISSUE TITLE
Help Text 

### ISSUE THREAD

**Issue by leonardyrj** [laravel/nova-issues#5640]
- Laravel Version: 9
- Nova Version: 4.25.1
- PHP Version: 8.2

### Description:
help method does not work when resource is called hasOne by another resource.

**Comment by crynobone** [comment]
Marking this a bug as the behavior will be fixed only for inline creating/updating.

**Comment by leonardyrj** [comment]
In the file field type, it still does not appear when it is a hasOne relationship
