### ISSUE TITLE
Lens example not working ($this in static function)

### ISSUE THREAD

**Issue by tobjue** [laravel/nova-issues#565]
There is also a stackoverflow question about this issue:
https://stackoverflow.com/questions/52272370/create-laravel-nova-lens-using-this-when-not-in-object-context

**Comment by hotmeteor** [comment]
I think it's just a mistake in the documentation. If you're going to write you code like this you need to use `self::columns()` instead.

**Comment by davidhemphill** [comment]
We've updated the example in the documentation to address the typo! Sorry about that.
