### ISSUE TITLE
MultiSelect field selection

### ISSUE THREAD

**Issue by Brand3000** [laravel/nova-issues#5652]
I have a MultiSelect field like so:
`            MultiSelect::make('Language', 'languages')->options(WebsiteLanguage::getAllWebsiteLanguagesInArray())
                ->help('Use the Ctrl button for choosing several languages')
                ->default(function () {
                    return array_keys(WebsiteLanguage::getAllWebsiteLanguagesInArray()->toArray());
                })->required(),`
All the options of the select field are chosen by default, but if I click any option with or without pressed ctrl all the options are being reseted. It shouldn't work this way. If I press ctrl and click an option, only this one option should be unselected, not all of them.

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by Brand3000** [comment]
I use this field in the Action feature. The function is:
`    public function fields(NovaRequest $request)
    {
        return [
            MultiSelect::make('Language', 'languages')->options(WebsiteLanguage::getAllWebsiteLanguagesInArray()) ->help('Use the Ctrl button for choosing several languages') ->default(function () { return array_keys(WebsiteLanguage::getAllWebsiteLanguagesInArray()->toArray()); })->required(),
        ];
    }
`

**Comment by AkselMeola** [comment]
This is happening for me too. 
After page has loaded, when user holds ctrl and click any option in the multiselect, it clears all selected and only selects the last selected item. 
It does not however happen when I have made selections, unfocus field, and then select additional options.  

Seems that the initial state of multiselect is somehow buggy.
