### ISSUE TITLE
ERROR in ../../vendor/laravel/nova/resources/js/mixins/PreventsFormAbandonment.

### ISSUE THREAD

**Issue by Patryk48** [laravel/nova-issues#5654]
- Laravel Version: 10.10.0
- Nova Version: 4.0.0
- PHP Version: 8.1

### Description:

ERROR in ../../vendor/laravel/nova/resources/js/mixins/PreventsFormAbandonment.js 9:0-35
Module not found: Error: Can't resolve '@/util/filled' in '/var/www/html/vendor/laravel/nova/resources/js/mixins'

the error occurs when compiling a custom field

Actions done :

*Delete node_modules folder from custom field
*Reinstalling the vendor
* cd vendor/laravel/nova && npm install
* npm run nova:install in (folder with custom field)

Nothing helped please help

**Comment by davidhemphill** [comment]
Should be resolved in 4.26.1
