### ISSUE TITLE
Validation rules behave differently and trigger exceptions

### ISSUE THREAD

**Issue by twarlop** [laravel/nova-issues#5659]
### Description:

Validation seems to behave differently causing (in my case) the following error

```
mb_strlen(): Argument #1 ($string) must be of type string, Laravel\Nova\Fields\Text given {"userId":14,"exception":"[object] (TypeError(code: 0): mb_strlen(): Argument #1 ($string) must be of type string, Laravel\\Nova\\Fields\\Text given at vendor/laravel/framework/src/Illuminate/Validation/Concerns/ValidatesAttributes.php:2377)
```

This was not an issue on nova 4.25.1 

I just went back to some older version, didn't dig deep to find the exact version the issue was introduced, but hope it helps

No longer works on:
- Laravel Version: 9.52.10
- Nova Version: 4.26.1
- PHP Version: 8.2.6
- Operating System and Version: Mac and linux

Pretty sure it has nothing to do with laravel/php/os versions

### Description:

I have a model with some validation rules:

```
    public function fields(NovaRequest $request): array
    {
        return [
            Text::make('Text field'),            
            // the gte:0 no longer works and causes an error
            Currency::make('Price field')
                ->rules(['required', 'numeric', 'gte:0']),
        ];
    }
```

Filling in the form and saving will cause the error. Make sure to specify an actual price to avoid "required" validation

What I've found to be causing it is the following:

in file `vendor/laravel/framework/src/Illuminate/Validation/Concerns/ValidatesAttributes.php:1162`

```
    public function validateGte($attribute, $value, $parameters)
    {
        $this->requireParameterCount(1, $parameters, 'gte');
        
        // ---> Here is the "different behaviour" causing the issue
        // comparedToValue should be null, but it no longer is
        // it seems that "$this->data" now includes all fields like BelongsTo, Date, Text, etc etc with a numeric key (example below)
        // since i want gte:0 -> it looks for the value in the $this->data array on numeric key 0 (at least that what i think it is)
        // Causing the "$this->getValue" call to return a NovaField

        $comparedToValue = $this->getValue($parameters[0]);
        
        $this->shouldBeNumeric($attribute, 'Gte');
        
        //        dd(
//            $this->data,
//            $parameters[0],
//            $comparedToValue,
//            is_null($comparedToValue),
//            is_numeric($value),
//            is_numeric($parameters[0])
//        );

        if (is_null($comparedToValue) && (is_numeric($value) && is_numeric($parameters[0]))) {
            // ---> i should end up in this if statement, but no longer do
            return BigNumber::of($this->getSize($attribute, $value))->isGreaterThanOrEqualTo($this->trim($parameters[0]));
        }

        if (is_numeric($parameters[0])) {
            // ---> i end up in this statement, triggering the "failure" (while data is valid) and eventually i end up with a fatal error when 
            // parsing the validation messages
            return false;
        }

        if ($this->hasRule($attribute, $this->numericRules) && is_numeric($value) && is_numeric($comparedToValue)) {
            return BigNumber::of($this->trim($value))->isGreaterThanOrEqualTo($this->trim($comparedToValue));
        }

        if (! $this->isSameType($value, $comparedToValue)) {
            return false;
        }

        return $this->getSize($attribute, $value) >= $this->getSize($attribute, $comparedToValue);
    }

```

I could bypass the issue, by using min:0 as a validation rule instead, but thought i'd mention it anyway

Original dump (commented dd statement)
![Screenshot 2023-06-29 at 14 40 54](https://github.com/laravel/nova-issues/assets/2856082/17fc54d9-579c-4115-8f39-d1255c11da90)

Dump on 4.26.1 (same dd statement)
![Screenshot 2023-06-29 at 14 40 09](https://github.com/laravel/nova-issues/assets/2856082/ba60ea44-31ba-4703-ab46-ee07c69f15f1)

**Comment by leigeber** [comment]
Something definitely changed. With the latest release many of our fields are failing as required when they aren't required. Dropping this here assuming it may be related.

**Comment by crynobone** [comment]
Can you provide a reproducing code. We have a large feature tests and dusk tests which has yet failed on any validation related tests.

Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by twarlop** [comment]
It's a specific scenario for how GTE is implemented, because it can reference other fields

you can write validation rules like this

`gte:another_field`
or
`gte:123`

the `$this->getValue("another_field")` -> will look into the "data input" and obviously compare to the correct value (because that key will be present in the input payload representing actual form data)

when you use a numeric value, that same logic will still be applied/tried: "does the input array have a key 123"
in case of big numbers, you probably won't end up with an issue, since you probably don't have 123 fields defined in your nova model definition 

-> because laravel assumes all form data has a "string key" instead of a numeric key 
```
[
      "field1" => "value",
      "field2" => "value",
]
```

if you look at my last screenshot, you can see the numeric key 0 being present in `$this->data`
The value of that field is the *first* field defined in my `getFields` method on the nova model. 

so somewhere down the line, your field definitions get injected into that $this->data array for whatever reason -> this is likely changed between the versions i mentioned.
I tried simplifying the example to make it less poluted. But in my case, there's about 7 NovaField instances in the data array, because i defined about 7 in my `getFields` method.

if you look at the first screen, the "null" dump would be an instance of `Text` (novafield) -> so the is_null(comparedToValue) becomes false in this case and validation fails, finally resulting in a fatal error because laravel is trying to format the error message as `value should be greater than ${TextInstance}` the formatting doesn't support objects, it expects a simple data type


I'm pretty confident that laravel/nova has a very decent testsuite, but this is pretty specific.. So i can imagine this scenario not being covered in the suite. I think if you'd try changing one rule to the gte you'll probably end up with an error similar to the one I mentioned. The issue might arise with other validation rules referencing other fields as well, if they allow referencing other fields and numeric values (and if the way of validating is similar to the gte rule)

currently have no time/budget to setup a full code repository.. sorry
I have been able to bypass the issue by changing to the "min" validation rule -> since that doesn't allow referencing other fields.

Feel free to close if you deem my issue report is invalid

Good luck!

**Comment by crynobone** [comment]
Submit a PR to fix this. However, I would suggest swapping `gte` to `min` and `lte` to `max` whenever possible.
