### ISSUE TITLE
Change routeConfiguration method of NovaServiceProvider

### ISSUE THREAD

**Issue by mariapaulinar** [laravel/nova-issues#566]
Can I change the array returned by routeConfiguration from NovaServiceProvider? (vendor\laravel\nova\src\NovaServiceProvider.php). This is the method:

protected function routeConfiguration()
{
        return [
            'namespace' => 'Laravel\Nova\Http\Controllers',
            'as' => 'nova.api.',
            'prefix' => 'nova-api',
            'middleware' => 'nova',
        ];
}

Thanks for your help.

**Comment by Manjul-Nexio** [comment]
Were you able to solve it as i want to change the prefix?
