### ISSUE TITLE
Repeater Field is expecting a Nova resource even when using the Json preset.

### ISSUE THREAD

**Issue by henryavila** [laravel/nova-issues#5660]
- Laravel Version: 10.14.10
- Nova Version: 4.26.1
- PHP Version: 8.1.0

### Description:
Repeater Field is expecting an Nova resource even when using the Json preset.

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Add `Repeater` field to a resource and create a new a repeatable, exactly as pointed in [docs](https://nova.laravel.com/docs/4.0/resources/repeater-fields.html#overview)

This code, will trigger the following error
```php
// \App\Nova\Resources\Commissions\CommissionFieldsResource.php

...

public function fields(Request $request): array
  {
  return [
      Repeater::make('Line Items', 'line_items')
        ->repeatables([
	        \App\Nova\Repeater\LineItem::make(),
        ])
        ->asJson()
    ];
}
````
![image](https://github.com/laravel/nova-issues/assets/8429941/ccbd46bd-e70e-4c8d-a92b-3fd36f3b5ddd)

If I try to add a class i nthe third param, I get the folowinf error
```php
Repeater::make('Line Items', 'line_items', \App\Nova\Repeater\LineItem::class)
  ->repeatables([
	  \App\Nova\Repeater\LineItem::make(),
  ])
->asJson()
```

![image](https://github.com/laravel/nova-issues/assets/8429941/fdb982e5-d064-402c-a09e-8ebbda4b7d1a)

As I'm using the Json preset, the Nova resource should not be required, since the repeatable values will exist just in model column.

If I put the resouce class itsel in the third param, 
```php
Repeater::make('Line Items', 'line_items', CommissionFieldsResource::class)
  ->repeatables([
	  \App\Nova\Repeater\LineItem::make(),
  ])
->asJson()
```
the Repeateble field is displayed in form view, but not in detail

**Comment by henryavila** [comment]
I don't know if it's because of the problem reported, but when editing the resource, if I remove one or more itens, it's  not saved.

I had 3 itens
1
2
3

removed 2 and 3 and added item 4.

After save, the itens on DB was:  1, 4, 3.


If I just update the values without adding or removing itens, its updtes corretly.

**Comment by kichetof** [comment]
Hello,

I tried `Repeater` field and I figured same error.
After searching, issue comme from `\Laravel\Nova\Fields\Repeater` constructor on line 92.

```php
$resource = $resource ?? ResourceRelationshipGuesser::guessResource($name);

if ($resource) { // <-- $resource might not exists has guessResource return a string without check
```

`ResourceRelationshipGuesser::guessResource($name)` could return a classname that doesn't exist. Easy fix is to test if class_exists($resource) to avoid this error.

---

It would be really great to have a display on detail.

Continue, it'll be awesome! 😎

**Comment by leonardyrj** [comment]
I'm following the manual and I'm also having the same problem

**Comment by muhammadsaeedparacha** [comment]
Bump

**Comment by PimButton** [comment]
> the Repeateble field is displayed in form view, but not in detail

After updating to [v4.26.4](https://nova.laravel.com/releases/4.26.4), the error is fixed, but the Repeatable field does still not show up on the detail view, only in the form view when creating or editing. When editing it shows the previous data, so it should be visible on the Detail page as well?

**Comment by davidhemphill** [comment]
There is currently no detail view for the Repeater field.

**Comment by avinashv** [comment]
> There is currently no detail view for the Repeater field.

Is this planned to be implemented or intended to be the case?
