### ISSUE TITLE
Call to undefined method stdClass::forceFill()

### ISSUE THREAD

**Issue by Patryk48** [laravel/nova-issues#5662]
Laravel Version: 10.10.0
Nova Version: 4.0.0
PHP Version: 8.1
Description:
{
    "message": "Call to undefined method stdClass::forceFill()",
    "exception": "Error",
    "file": "/var/www/html/vendor/laravel/nova/src/Fields/Field.php",
    "line": 492,'
}
Related Issue: https://github.com/laravel/nova-issues/issues/5654

**Comment by crynobone** [comment]
Duplicate of https://github.com/laravel/nova-issues/discussions/5650

**Comment by Patryk48** [comment]
@crynobone problem still exist unnecesary :(  :( :(
