### ISSUE TITLE
LensActionRequest->availableFilters() returns filters of resource not of the lens itself.

### ISSUE THREAD

**Issue by kusab85** [laravel/nova-issues#5665]
- Laravel Version: 10.14.1
- Nova Version: 4.26.3
- PHP Version:  8.2.4

### Description:

```LensActionRequest->availableFilters()``` returns filters that are associated with lens' resource not the lens itself.

```LensActionRequest``` class uses ```availableFilters()``` function of ```DecodesFilters``` trait:

```php
    protected function availableFilters()
    {
        return $this->newResource()->availableFilters($this);
    }
```
which should be overwritten like in  ```LensRequest``` class:
```php
    protected function availableFilters()
    {
        return $this->lens()->availableFilters($this);
    }
```
That's my humble opinion...

**Comment by crynobone** [comment]
`LensActionRequest` doesn't have any requirement for `availableFilters()`.

**Comment by kusab85** [comment]
> `LensActionRequest` doesn't have any requirement for `availableFilters()`.

But, what about situation when I want to get applied filters when handling standalone lens action (lens has different set of available filters then the resource)?

**Comment by crynobone** [comment]
Submit a bug report with reproducing repository explicitly showing the issue.

**Comment by crynobone** [comment]
Standalone action shouldn't need the filtered queries as it always get empty Collection.

**Comment by kusab85** [comment]
> Submit a bug report with reproducing repository explicitly showing the issue.
Be my guest :)  #5698

> Standalone action shouldn't need the filtered queries as it always get empty Collection.
I can not see why. I think that standalone action should have ability to act on resources filtered according to users choice. 
For example: exporting filtered resources using standalone action needs two clicks less.
