### ISSUE TITLE
BelongsTo field with dependsOn retains old selected value when changing parent

### ISSUE THREAD

**Issue by emcarson** [laravel/nova-issues#5674]
- Laravel Version: 10.14.1
- Nova Version: 4.26.3
- PHP Version: 8.1.13
- Database Driver & Version: MySQL 8.0.30
- Operating System and Version: Ubuntu 20.04.4 LTS
- Browser type and version: Google Chrome Version 114.0.5735.133 (Official Build)

### Description:

I have two BelongsTo fields, Country and Salesperson. Salesperson dependsOn Country:

```php
BelongsTo::make('Country', 'country', Country::class),

BelongsTo::make('Salesperson', 'salesperson', Admin::class)
    ->dependsOn(['country'], function (BelongsTo $field, NovaRequest $request, FormData $formData) {
        $field->relatableQueryUsing(function (NovaRequest $request, Builder $query) use ($formData) {
            $query
                ->whereHas('countries', function (Builder $query) use ($formData) {
                    $query->where('countries.id', $formData['country']);
                });
        });
    })
    ->nullable(),
```

Whenever I change the Country option, Salesperson should refresh with a list of records for the selected country. That works flawlessly.

Problem is, if I select a Country followed by a Salesperson and then I change the Country again, the Salesperson field appears blank but retains the last Salesperson ID and validation fails ("This Salesperson may not be associated with this resource.").

### Detailed steps to reproduce the issue on a fresh Nova installation:

1) Select Create resource

2) Select a record from the first dropdown (Country), then select a record from the second dropdown (Salesperson).

![image](https://github.com/laravel/nova-issues/assets/12752046/04593258-4007-42f5-8800-908ef96e46cb)

3) Change the Country but leave Salesperson blank:

![image](https://github.com/laravel/nova-issues/assets/12752046/49163eab-6916-4176-8366-b5113a67be90)

4) Submit the form

![image](https://github.com/laravel/nova-issues/assets/12752046/dec3a63c-15fe-4a95-8deb-5ceb6d6e593e)

Validation fails ("This Salesperson may not be associated with this resource.") even though nothing is selected and the field itself is nullable.

**Comment by crynobone** [comment]
If you wish to reset the selected `salesperson` on `country` changes you can do it by adding `$field->setValue(null);`.

**Comment by emcarson** [comment]
Is this the expected behaviour? That the belongsTo field retains the old value even though the options changed and said value isn't selectable anymore?

I asked by partner to test the scenario out with his own project (different models/tables, resources, different Laravel version) and he's getting the exact same result.

I tried reseting the value as instructed in every possible way (before, after and inside `relatableQueryUsing()`) but the result remains the same:

```
BelongsTo::make('Salesperson', 'salesperson', Admin::class)
    ->dependsOn(['country'], function (BelongsTo $field, NovaRequest $request, FormData $formData) {
        $field->setValue(null);
        $field->relatableQueryUsing(function (NovaRequest $request, Builder $query) use ($formData) {
            $query
                ->whereHas('countries', function (Builder $query) use ($formData) {
                    $query->where('countries.id', $formData['country']);
                });
        });
    })
    ->nullable(),
```
```
BelongsTo::make('Salesperson', 'salesperson', Admin::class)
    ->dependsOn(['country'], function (BelongsTo $field, NovaRequest $request, FormData $formData) {
        $field->relatableQueryUsing(function (NovaRequest $request, Builder $query) use ($formData) {
            $query
                ->whereHas('countries', function (Builder $query) use ($formData) {
                    $query->where('countries.id', $formData['country']);
                });
        });
        $field->setValue(null);
    })
    ->nullable(),
```

```
BelongsTo::make('Salesperson', 'salesperson', Admin::class)
    ->dependsOn(['country'], function (BelongsTo $field, NovaRequest $request, FormData $formData) {
        $field->relatableQueryUsing(function (NovaRequest $request, Builder $query) use ($formData) {
            $query
                ->whereHas('countries', function (Builder $query) use ($formData, $field) {
                    $query->where('countries.id', $formData['country']);
                    $field->setValue(null);
                });
        });
    })
    ->nullable(),
```
![image](https://github.com/laravel/nova-issues/assets/12752046/e2e7fc2d-0e78-4d5d-a489-d63addc3e152)

Thank you.

**Comment by crynobone** [comment]
> Is this the expected behaviour? That the belongsTo field retains the old value even though the options changed and said value isn't selectable anymore?

Yes.
