### ISSUE TITLE
Redirect actions that manipulate session fails in 4.26

### ISSUE THREAD

**Issue by atymic** [laravel/nova-issues#5675]
- Laravel Version: 10.14.1
- Nova Version: 4.26.3
- PHP Version: 8.2
- Database Driver & Version

### Description:

It seems that something changed in the way nova handles actions in the recent version. 
I have a simple action that redirects to a URL (impersonation URL). When executing this action inline, it works correctly, however when executing it on the resource page one of the nova requests somehow overrides the session and breaks the impersonation.

I will debug further with a http debugger and see if I can find the specific request. Any ideas on how to prevent nova from making additional requests after the action is performed?

**Comment by crynobone** [comment]
If you want to submit a bug report, provide a way for us to replicate the issue. Above statement seem like more like a question than a bug report.

**Comment by atymic** [comment]
I will try build a repro repo.
