### ISSUE TITLE
Metrics: custom date column is ignored

### ISSUE THREAD

**Issue by josiasmontag** [laravel/nova-issues#568]
Setting a custom `$dateColumn` for a Metric gets ignored. It always uses `created_at`.

Reason is a bug in the `count()` method of `Laravel\Nova\Metrics\Trend`. The last argument is not passed to the `aggregate()` call.

**Comment by bonzai** [comment]
#95
#108

**Comment by taylorotwell** [comment]
Fixed in upcoming release.
