### ISSUE TITLE
Register a Static Actions

### ISSUE THREAD

**Issue by Petoches** [laravel/nova-issues#5680]
- Laravel Version: 9.19
- Nova Version: 4.23.0
- PHP Version: 8.1.18

### Description:

When trying a basic static actions like in the documentation 

    public function actions(NovaRequest $request)
    {
        return [
            Action::openInNewTab('Visit Stripe Dashboard', 'https://stripe.com')->standalone(),
        ];
    }

i get the message : Call to a member function standalone() on array.

I don't understand how static actions are meant to be registered and the documentation is not really explaining it.

**Comment by crynobone** [comment]
Static Action was introduced in 4.24.0: https://nova.laravel.com/releases/4.24.0

You need to upgrade if you want to use this feature.
