### ISSUE TITLE
Nova is not working on production environment(inside a subdirectory)

### ISSUE THREAD

**Issue by deepu-ec** [laravel/nova-issues#5684]
- Laravel Version: 10.10
- Nova Version: 4.0
- PHP Version: 8.1
- Database Driver & Version: MySQL 5.7
- Operating System and Version: Ubuntu 18.04.6

### Description:
I have got a couple of Laravel applications that use Nova. All these apps are accessible using the same domain but under different paths. For example, consider following the directory structure & domain.

Domain: `my-domain.com`
Directory structure:
````
- Web server root dir
   - apps
       - app 1
       - app 2
````

The above apps can be accessed via `my-domain.com\apps\app-1`  and `my-domain.com\apps\app-2`.

`app 1` and `app 2` directories are symlinks to the `public` directory of the actual Laravel applications. The Laravel application is working as expected, but **Nova is not in the production environment**. 

When I try to access the Nova app via `my-domain.com\apps\app-1\nova\login`  all I am getting is an empty page with some errors on the browser console that shows the invalid path to the CSS/JS files(see the screenshot). The subdirectory path is not added when the assets are loaded.

<img width="820" alt="Screenshot 2023-07-05 at 11 33 01" src="https://github.com/laravel/nova-issues/assets/129061342/e92d98cb-060b-4271-8756-ac7881825276">

I tried to fix this issue by creating the layout file inside `resources/views/vendor/nova/layout.blade.php` copying the contents from `vendor/laravel/nova/resources/views/layout.blade.php` and loading the asset files using the `asset()` helper.  This resolved the issue and the Nova login page is working. However, after the page loading is finished the URL is altered and the subdirectory path is appended. So the initial login URL `my-domain.com\apps\app-1\nova\login` is automatically changed to `my-domain.com\apps\app-1\apps\app-1\nova\login` and nothing else will work thereafter. For example, if I submit the login form it will send a request to  `my-domain.com\nova\login` which results in a 404.

I saw a [discussion thread](https://github.com/laravel/nova-issues/discussions/4267) similar to this issue but couldn't find any solution. There is also [another issue](https://github.com/laravel/nova-issues/issues/2136) which says Nova does not support the subdirectory implementation. 

Thank you

**Comment by crynobone** [comment]
Using Nova in a subdirectory is not supported in Nova and Laravel Framework itself: https://laravel.com/docs/10.x/installation#directory-configuration
