### ISSUE TITLE
Nova Errors on Fresh Install

### ISSUE THREAD

**Issue by xongooli** [laravel/nova-issues#5688]
- Laravel Version: ^10.7
- Nova Version: ^4.0
- PHP Version: 8.1.6
- Database Driver & Version: MariaDB 10.4.24
- Operating System and Version: Windows 10
- Browser type and version: chrome  version 114.0.5735.134 (Official Build) (64-bit)
- Reproduction Repository: https://github.com/tenancy-for-laravel/saas-boilerplate

### Composer Install fails with Nova Licence error.

************************************************************************************************
Unable to find Nova (Silver Surfer) license holder with the given license key: [h6*!58KMbu$Ez#].
************************************************************************************************
Warning from nova.laravel.com: 

************************************************************************************************
Unable to find Nova (Silver Surfer) license holder with the given license key: [h6*!58KMbu$Ez#].
************************************************************************************************
 

### Detailed steps to reproduce the issue on a fresh saas-boilerplate installation:

Clone repo.
Run composer install

------------------------------
I've tried creating a .env file and entering a license key -  NOVA_LICENSE_KEY=xxxxxxxxxxxxxxxxxxxxx

I'm not sure where this license key is coming from.  I've tried clearing composer cache, deleting the vendor directory and reinstalling 

But until composer install completes, it seems the .env file is ignored. 

Sure there is a way to skip the Nova installation but I do want to use it.

**Comment by crynobone** [comment]
you need to purchase a license to get the license key.

**Comment by xongooli** [comment]
I have a license key

**Comment by crynobone** [comment]
Here is a quick rundown of how to install Nova.

First, ensure that your project or machine has a valid Composer "auth.json" file for Laravel Nova. You can create one with a command like the following:

```
composer config http-basic.nova.laravel.com {{YOUR_NOVA_EMAIL}} {{YOUR_NOVA_LICENSE_KEY}}
```

Please ensure that the email address matches the login email address you use to sign in to the Nova website and that the license key matches the license key within the license key detail page within your Nova account.

Next, you should run "composer update mirrors" and "composer update" to install Nova.

Please let us know if you continue to have issues.
