### ISSUE TITLE
Wrong search parameter in action on resource index page after refresh

### ISSUE THREAD

**Issue by 40katty04** [laravel/nova-issues#5695]
- Laravel Version: 10.13.5
- Nova Version: 4.26.3
- PHP Version: 8.1
- Database Driver & Version:

### Description:
If  you refresh index page with filled search field and than change search string in all next action requests search parameter is  wrong  till page reload

![Screenshot from 2023-07-06 16-40-26](https://github.com/laravel/nova-issues/assets/38152697/1e8b79a1-f208-4762-a88a-5fc5a5f9b336)

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. go to index page of any resource, that have some actions can be run to multiple entities
2. type in search field "firstSearchWord"
3. refresh page
4. type another search string to get some entities in result (e.g "correct")
5. click "Select all" 
6. open dev console
7. run some action to choosen entities
8. open "action" request and see in Query parameter  "search=firstSearchWord" instead of "search=correct"

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)
