### ISSUE TITLE
MultiSelect Field fails to select integer defaults

### ISSUE THREAD

**Issue by electrictomcat** [laravel/nova-issues#5696]
- Laravel Version: 9.52
- Nova Version: 4.26.3
- PHP Version: 8.2
- Database Driver & Version:
- Operating System and Version: Mac OS Ventura 13.5 Beta (22G5038d) 
- Browser type and version: Chrome 114.0.5735.198

### Description:
When you have a selection of integers as options in a multiselect field and you try and set a default it won't select them.
This does work for non-integer values.

![CleanShot 2023-07-06 at 20 08 10](https://github.com/laravel/nova-issues/assets/16545651/7a1e577e-8e26-4a9e-80c9-120e873876fb)

### Detailed steps to reproduce the issue on a fresh Nova installation:
Create a multiselect field with at least integer options, but can be other options.
Set a default selection including those integer options.
The integer options will not be selected by default.

**Comment by crynobone** [comment]
I believe the Multiselect values should be strict type and will work correctly with the correct default.
