### ISSUE TITLE
Nova Component returning 500 on production

### ISSUE THREAD

**Issue by jringeisen** [laravel/nova-issues#570]
I've created a Nova component that displays as a badge. Everything works fine on development, but when I pushed it to production I started getting this:

`https://essentialstudiomanager.com/nova-api/styles/badge net::ERR_ABORTED 500`
`https://essentialstudiomanager.com/nova-api/scripts/badge net::ERR_ABORTED 500`

I only changed the IndexField.vue file:

`<template>`
`<div>`
        `<span v-if="field.value === 'Active'" class="badge badge-success">{{ field.value }}</span>`
        `<span v-if="field.value === 'Cancelled'" class="badge badge-danger">{{ field.value }}</span>`
    `</div>`
`</template>`

`<script>`
`export default {`
    `props: ['resourceName', 'field'],`
`}`
`</script>`

Any ideas? I did compile all the assets prior to pushing to production. I used yarn production instead of npm production.

**Comment by laurencei** [comment]
Check your Laravel logs for what the error is.

**Comment by Jam0r85** [comment]
Getting the same issue with 4 components I've made.

**Comment by jringeisen** [comment]
I was able to fix this issue. After running yarn install and yarn production i noticed it created a dist folder. So I pushed it up to my master and it was still giving me the same issue. Then I noticed the .gitignore file was ignoring the /dist folder so I removed it from the .gitignore and problem solved.

**Comment by davidhemphill** [comment]
Yep, this was addressed in the latest release. Sorry for the trouble!
