### ISSUE TITLE
DateTime field exception without cast

### ISSUE THREAD

**Issue by afshiney** [laravel/nova-issues#5701]
- Laravel Version: 10.14.1
- Nova Version: 4.26.4
- PHP Version: 8.2.6
- Database Driver & Version: MySQL (8.0.21)
- Operating System and Version: macOS Monterey 12.6.7
- Browser type and version: Chrome

### Description:
Nova used to throw an exception with clear message if DateTime field was used in a resource without the attribute being casted in the model as 'datetime', now it throws "incorrect datetime format" sql error.
I believe it's good call to bring back the exception message + mentioning it on nova docs.

Before (up until version 3):
<img width="509" alt="Screen Shot 2023-07-10 at 1 42 45 AM" src="https://github.com/laravel/nova-issues/assets/24396223/bbc1bca3-230e-43e0-951a-7dd5216293e9">

Now:
<img width="926" alt="Screen Shot 2023-07-10 at 1 47 32 AM" src="https://github.com/laravel/nova-issues/assets/24396223/96aa5c42-339a-4d08-be20-5d6279ab1978">

### Detailed steps to reproduce the issue on a fresh Nova installation:
Declare a DateTime field in a resource without it being casted as datetime

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by afshiney** [comment]
I've pushed my fresh installation [here](https://github.com/afshiney/issue-5701), I hope this is what you needed.

After running the project, please try to create a user resouce and filling the "starting_at" field on it.

**Comment by crynobone** [comment]
https://github.com/afshiney/issue-5701/blob/a77c88c3c5febcdb8c557172ed65b6f09776b0a1/app/Models/User.php#L35C1-L44C7

Missing `starting_at` cast as `datetime`.

**Comment by afshiney** [comment]
> https://github.com/afshiney/issue-5701/blob/a77c88c3c5febcdb8c557172ed65b6f09776b0a1/app/Models/User.php#L35C1-L44C7
> 
> Missing `starting_at` cast as `datetime`.

Correct, my issue is exactly on this matter, when you miss to cast a field as 'datetime', nova doesn't display correct exception message about it.

It throws a sql error, refer to my first message Screenshots please.

**Comment by crynobone** [comment]
> Correct, my issue is exactly on this matter, when you miss to cast a field as 'datetime', nova doesn't display correct exception message about it.

Casting from string to DateTime is handled by the Framework and you need to use the correct cast as suggested in the documentation.
