### ISSUE TITLE
Resource creation (as defined in Docs) not working

### ISSUE THREAD

**Issue by sambarocker** [laravel/nova-issues#571]
Hi!

I'm following exactly the steps shown on https://nova.laravel.com/docs/1.0/resources/#defining-resources (including the name of my first resource, _Post_), and the result is always the same, an error screen -- please see below -- saying it's impossible to find the Class (by the way, the resource is not being automatically registered in the Service Provider).

Can you help me here?

PHP 7.2.9, Laravel 5.7.3, Nova release 1.0.16

<img width="1245" alt="captura de tela 2018-09-14 as 20 12 05" src="https://user-images.githubusercontent.com/5061806/45578952-d1ba1200-b85a-11e8-9d40-eee6633b1368.png">

**Comment by RickBL99** [comment]
How did you solve this!

**Comment by niladam** [comment]
@RickBL99 - in case you got into this error and didn't find a fix. You should probably update your `$model` property on the resource. I usually have something like: 
```php
public static $model = 'App\\Models\\User';
```
