### ISSUE TITLE
confirm event not firing in action modal

### ISSUE THREAD

**Issue by jdion84** [laravel/nova-issues#5713]
- Laravel Version: 10
- Nova Version: 4
- PHP Version: 8
- Database Driver & Version:
- Operating System and Version: macos ventura
- Browser type and version: chrome
- Reproduction Repository: 

### Description:

i have a custom field which I am using inside of an action

from this custom field, i just want to trigger the "run action" button (via the action modal `confirm` event)

heres my code that doesn't work:

```js
<template>
    <table width="100%">
        <tr>
            <th>dealer name</th>
            <th>assign</th>
        </tr>
        <tr v-for="dealer in field.dealers">
            <td>
                {{ dealer.name }}
            </td>
            <td>
                <button type="button" v-on:click="assign(dealer.id)">assign</button>
            </td>
        </tr>
    </table>
</template>

<script>
import { FormField, HandlesValidationErrors } from 'laravel-nova'

export default {
    mixins: [FormField, HandlesValidationErrors],

    props: ['resourceName', 'resourceId', 'field'],

    methods: {
        /*
         * Set the initial, internal value for the field.
         */
        setInitialValue() {
            this.value = this.field.value || ''
        },

        /**
         * Fill the given FormData object with the field's internal value.
         */
        fill(formData) {
            formData.append(this.fieldAttribute, this.value || '')
        },

        assign(dealerId) {
            this.value = dealerId

            this.$emit('confirm');
        },
    },
}
</script>

```

see the `assign` method, when i click on the button nothing happens but i do see the event being emitted in vue dev tools

i've also tried using `Nova.$emit('confirm')` and if i use that, it doesn't even show an event in vue dev tools

what i want is when this button inside my custom field is clicked, the action is confirmed as if clicking the "run action" button in the modal

right now it just doesn't seem to be triggering anything

**Comment by crynobone** [comment]
Such usage is not supported by Nova.

**Comment by jdion84** [comment]
> Such usage is not supported by Nova.

any way i can do this though?

**Comment by jdion84** [comment]
nvm i will just figure out a solution with radio buttons instead

**Comment by jdion84** [comment]
i figured it out

just in case anyone needs to access an action modal via a custom field, you can use:

```js
this.$parent.$parent.$emit('confirm')
```
