### ISSUE TITLE
Problem on deleting item from a repeater field

### ISSUE THREAD

**Issue by metadevstudio** [laravel/nova-issues#5719]
- Laravel Version: 10.15.0
- Nova Version: 4.26.4
- PHP Version: 8.1.6
- Database Driver & Version: mysql 10.3.39-MariaDB-cll-lve
- Operating System and Version: Windows 11 21h2 22.000.1936
- Browser type and version: Chrome 114.0.5735.199 64 bits
- Reproduction Repository: private

### Description:

When using a json repeater field, if I add 2 records, save and try to delete only 1 of them, the request will be made successfully but when I refresh the page, the value that I deleted will be there again.

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Register an repeater field with json preset on any resource.
- Save 2 records.
- Try to delete 1 record.

```php
// Resource
public function fields(NovaRequest $request)
    {
        return [
            // json db column
            Repeater::make('Repeater', 'table_column')->repeatables([
                \App\Nova\Repeater\Field::make()
            ])->asJson(),
        ];
    }

//MODEL
class ResourceModel extends Model
{
    use HasFactory;

    protected $casts = [
      'table_column' => 'array'
    ];
}
```

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍

**Comment by davidhemphill** [comment]
Just released a patch fixing this.
