### ISSUE TITLE
Adding parameter to filter class

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#572]
v1.0.16

I am trying to build a package for date filtering but can't pass a `$column` for some reason

`Unresolvable dependency resolving [Parameter #0 [ <required> $column ]] in class`

```php
public function filters(Request $request)
{
    return [
        new DateFilter('created_at'),
        new DateFilter('updated_at'),
        new DateFilter('confirmed_at'),
    ];
}
```

```php
use Laravel\Nova\Filters\Filter;

class DateFilter extends Filter
{
    public $column;

    public function __construct($column)
    {
        $this->column = $column;
    }

    ...
}

**Comment by taylorotwell** [comment]
This will be fixed in the next release; however, note that you still will not realiably be able to have multiple instances of the same filter type on a resource. We would have no way to know from the front-end which filter of the three you are actually choosing because they are all of the same type. The front-end has no idea which constructor arguments it has, etc. You could make 3 separate classes that extend DateFilter.

But, the root constructor argument thing will be fixed in the next release.

**Comment by dillingham** [comment]
@taylorotwell thank you for for the fix & for the explanation. I see what you mean when I have multiple instances and select an option from one, the vue component updates all other instances. 

Maybe passing vue `$class_name . '-' . spl_object_id($this)`
But I'm not sure what all that entails or effects. Abstract thought.

**Comment by dillingham** [comment]
```php
public function jsonSerialize()
{
    $container = Container::getInstance();

    return [
        'class' => get_class($this) . '-' . spl_object_id($this),

...
```

This makes the filter selectors unique, but `ResolvesFilters` would need to strip id

**Comment by dillingham** [comment]
@taylorotwell / @davidhemphill I think passing the unique id to vue's key would solve that issue

**Comment by BruceGujinhe** [comment]
@taylorotwell yes , the error is still over there in the version 1.21.1. all the vue instance share the same filter's value and other informations.

**Comment by BruceGujinhe** [comment]
I found the way to salve this quesiton. Just to reload the methos key() in  src/XXXFilter.php
so that we could get different key to sign different instance.
```
    public function key()
    {
        return get_class($this) . $this->column;
    }
```

**Comment by alenija** [comment]
Tell me please, is this fixed already?

**Comment by tsn-Sergey** [comment]
> Tell me please, is this fixed already?

Yep, this fixed.
