### ISSUE TITLE
Trend Metrics in sqlite

### ISSUE THREAD

**Issue by sajaddp** [laravel/nova-issues#5726]
- Laravel Version: 10.15.0
- Nova Version: 4.26.5
- PHP Version: 8.2.8
- Database Driver & Version: sqlite 3
- Operating System and Version: macOS 13.4
- Browser type and version: Google Chrome 114

### Description:
When the database is sqlite and we create a Trend Metrics, there is an error `Not enough data available to satisfy format`.
But if we just convert the database to mysql without any changes in the codes, the problem will be solved!

### Detailed steps to reproduce the issue on a fresh Nova installation:

- Define a seeder to build `100` users.
- Set the database to `sqlite` and run `php artisan migrate:fresh --seed`.
- Run the `php artisan nova:trend UsersPerDay` command and assign the user model to it.
- Register METRICS.
- An error occurs!
- Now change the database to `mysql` and run `php artisan migrate:fresh --seed` again.
- Error fixed!

**Comment by crynobone** [comment]
Please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)
