### ISSUE TITLE
Improve pivot-editing capabilities

### ISSUE THREAD

**Issue by JapSeyz** [laravel/nova-issues#573]
Currently, if you have a model with a lot of related models through a pivot. Having to edit multiple of those pivots require a lot of extra clicks.

**Comment by dillingham** [comment]
Make a plugin

**Comment by JapSeyz** [comment]
It's not.

Imagine a pricelist. Having to manually enter every product and change the pivot-data is quite a few extra steps, compared to a modal etc.

As per your previous comment, I am making a plugin for it, but I wrote it here, in hopes of an official solution.

**Comment by dillingham** [comment]
@JapSeyz do you have any examples of what that ui/flow might look like?

**Comment by JapSeyz** [comment]
@dillingham I have added a 4th button to the action-buttons, which opens up a modal for editing the pivot-attributes.

**Comment by davidhemphill** [comment]
@JapSeyz If you can email Nova support with a description/video/etc of your workflow and feature request that'll help. Closing this for now as we're trying to keep this a list of issues, not necessarily feature requests. 😃
