### ISSUE TITLE
Default Callback not working on Repeater Fields

### ISSUE THREAD

**Issue by christian-heiko** [laravel/nova-issues#5732]
- Laravel Version: 9.52.10
- Nova Version: 4.26.5
- PHP Version: 8.1.14

### Description:
Default Value or Default Value Callback is not working inside of Repeater Fields.

`
return [
    Text::make('Test', 'test')->default(function () {
        dd('This should be called.');
    }),
];
`

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Create a Repeater Item with Fields
2. Give the Fields a default value or a default value callback
3. Check the Form.

**Comment by davidhemphill** [comment]
@christian-heiko Can I ask what you're using the `default` method for? We've got a PR in to potentially fix this, but just want to understand your use in the context of the Repeater field. 😃

**Comment by davidhemphill** [comment]
Glad to hear Repeater is helping. We would add this `default` feature anyway, but I'm always curious about real-world use cases like yours, so thanks for sharing. Thanks!

**Comment by crynobone** [comment]
This has been fixed in 4.27.x releases.
