### ISSUE TITLE
Date field is getting timezoned

### ISSUE THREAD

**Issue by satoved** [laravel/nova-issues#5734]
- Laravel Version: 10.15
- Nova Version: 4.26.5
- PHP Version: 8.1

### Description:
When I look at a date field on the details and edit page from a computer in the US, it shifts the actual date to the previous date.

E.g. I have '2023-07-18' in the database under the field with DATE type.

It will show me "07/17/2023" on the details page.

<img width="438" alt="image" src="https://github.com/laravel/nova-issues/assets/14319239/2ad99d84-4db7-4f6b-8330-604873aafd82">

I will also populate "07/17/2023" if I edit the model.

<img width="466" alt="image" src="https://github.com/laravel/nova-issues/assets/14319239/3e74a90e-3456-4b2c-bbcf-4d6c13ca0092">

I guess what happens is, Details/DateField.vue takes the date, converts it to datetime, and then localizes it to the string, and then 2023-07-18 00:00:00 UTC becomes something like 2023-07-17 16:00:00 Pacific Time. So it then shows 2023-07-17.

<img width="547" alt="image" src="https://github.com/laravel/nova-issues/assets/14319239/ae482896-5aca-446d-bc81-c28419c2f05c">

<img width="280" alt="image" src="https://github.com/laravel/nova-issues/assets/14319239/78ced3a9-7c2d-4995-b1ed-fd67dd93e75c">

Similar thing happens with in Form/DateField.vue with luxon:
<img width="469" alt="image" src="https://github.com/laravel/nova-issues/assets/14319239/f46f690b-418e-4222-9825-77ab9dff11df">

I don't think Date field should localized the date at all, because a date is a date.

### Detailed steps to reproduce the issue on a fresh Nova installation:
1) Add a date field to a model with a mysql DATE field in it.
2) Set the date to 2023-07-18 in the database.
3) Open the details page for the model and see 2023-07-17 instead.
4) Try to edit the entry, and see 2023-07-17 in the date input.

**Comment by satoved** [comment]
As a workaround, I'm adding ->dispalyUsing() to the field:
<img width="647" alt="image" src="https://github.com/laravel/nova-issues/assets/14319239/19942550-a09a-41aa-ab83-669206cafc69">

**Comment by crynobone** [comment]
We completely remove the concept of timezone for `Date` in https://nova.laravel.com/releases/4.26.0 and back with multiple dusk tests.

I definitely need a working example with server, user and browser timezone.

**Comment by EPGDigital-MW** [comment]
I have this issue just reported to me, depending where the user is in the world and time of day they see a different date when editing.

If I load my edit page:

My current timezone is Europe/London date shows 22/07/2023 (22nd July 2023)

User in Pacific/Pago_Pago who are now on the next day at time of this message, see 21/07/2023

They should see 22/07/2023 as that's the time thats stored in the database there shouldn't be any timezone conversion happening with dates.

I think like DateTime field we need to set the timezone when setting the Date in Date field

So if we create the value in the Vue component with the timezone that nova is set to, Pacific/Pago_Pago user now sees 22/07/2023 in edit page

```javascript
this.value = DateTime.fromISO(this.currentField.value || this.value, {
    zone: Nova.config('timezone'),
}).toISODate()
```
