### ISSUE TITLE
Slug field preview method defaults to send the string 'Poop' (this is not a joke)

### ISSUE THREAD

**Issue by nbolender** [laravel/nova-issues#5738]
- Laravel Version: 10.15.0
- Nova Version: 4.26.5

### Description:

While debugging an issue with the Slug field, I found that in the source code for fetching the slug preview, the value sent to the server defaults to the word **'Poop'**. In `resources/js/fields/Form/SlugField.vue` line `61`:

```
async fetchPreviewContent(value) {
  const {
    data: { preview },
  } = await Nova.request().post(
    `/nova-api/${this.resourceName}/field/${this.fieldAttribute}/preview`,
    { value: value ?? 'Poop' }
  )

  return preview
},
```

I think it would be most appropriate to change this to an empty string or some other, non-feces related, word.

**Comment by davidhemphill** [comment]
lol

**Comment by davidhemphill** [comment]
There's no situation where `value` will ever be a non-string value, but I've updated this in the latest version to remove it.
