### ISSUE TITLE
Broken displaying of Panels on forms

### ISSUE THREAD

**Issue by ondrejehrlich** [laravel/nova-issues#5739]
- Laravel Version: 9.52.10
- Nova Version: 4.26.5
- PHP Version: 8.2
- Browser type and version: Google Chrome 114.0

### Description:
I am writing to report a bug related to the display of Panels on forms.

Issue: When using Panels, the display on forms appears to be broken. The field paddings within the Panels are not set correctly, leading to an undesirable user experience. See picture:
<img width="1343" alt="Screenshot 2023-07-13 at 16 30 39" src="https://github.com/laravel/nova-issues/assets/66925353/1f396277-22d3-429c-9e82-14068b4495f3">

### Detailed steps to reproduce the issue on a fresh Nova installation:

- Create a resource
- Create panels according to the documentation (https://nova.laravel.com/docs/4.0/resources/fields.html#field-panels)
- See create or edit page

**Comment by crynobone** [comment]
![image](https://github.com/laravel/nova-issues/assets/172966/41461e65-2b1d-4c3f-9f25-12a403d92096)

Unable to reproduce the issue, please provide a full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by ondrejehrlich** [comment]
I've found out that this issue was caused by using nova-tooltip-field package. 
I apologize for the creating an issue for bug that wasn't caused by Nova. 

Thank you for your great work making Nova so cool!
