### ISSUE TITLE
Nova 4.5  Pressing Select All on Index view and then unchecking 1 item, still populates all the models in the Action handle method

### ISSUE THREAD

**Issue by sietse85** [laravel/nova-issues#5740]
- Laravel Version: 9.0
- Nova Version: 4.5
- PHP Version: 8.1

### Description:

When pressing 'select all' in a index view and then unchecking a single item (or more) still gives all the models to the action handle method. I don't know if this is intended or a bug.

![image](https://github.com/laravel/nova-issues/assets/10598991/9accf5e1-7ce4-4151-a566-ab1deb07a305)

![image](https://github.com/laravel/nova-issues/assets/10598991/7678cf47-444a-4a46-856e-3ca866c23740)

![image](https://github.com/laravel/nova-issues/assets/10598991/14fb3862-64a5-4572-9a88-bb84f6ef9ace)

After running an action, the receiving models collection in the handle method of the action receives all models. In my opinion it should not receive the unchecked item.

![image](https://github.com/laravel/nova-issues/assets/10598991/0c79977d-194d-4bf5-a262-9b28d0db209a)

**Comment by crynobone** [comment]
Laravel Nova 4.5 is an old version, please upgrade to latest version and verify the issue still exists.
