### ISSUE TITLE
How to make Repeater inside Repetear fields

### ISSUE THREAD

**Issue by mialyGit** [laravel/nova-issues#5753]
- Laravel Version: 9.52.12
- Nova Version: 4.26.5
- PHP Version: 8.1.0

### Description:

I have this code :

`Repeater::make('Line Items')
            ->fullWidth()
            ->repeatables([
                LineItem::make(),
            ])`

I want to add Repeater FullImageWidth inside LineItem :

```
    public function fields(NovaRequest $request)
    {
        return [
            Text::make('Quantity')->translatable()->fullWidth(),
            MediaHubField::make('Image', 'image')->translatable(),
            Repeater::make('FullWidthImage')->repeatables(
                [
                    FullImageWidth::make()
                ]
            )->asJson()
        ];
    }
```
This gives an error :
` Laravel\\Nova\\Fields\\Repeater\\Presets\\JSON::get(): Argument #2 ($model) must be of type Illuminate\\Database\\Eloquent\\Model, array given, called in C:\\Users\\USER\\Documents\\test_winehubpro\\apps\\nova\\vendor\\laravel\\nova\\src\\Fields\\Repeater.php on line 173`

Any has an idea ??

**Comment by davidhemphill** [comment]
Nested Repeaters are not currently supported.
