### ISSUE TITLE
Eager loading `target` relationship on ActionEvent for a non soft-deleted model throws an exception

### ISSUE THREAD

**Issue by marcmalha** [laravel/nova-issues#5754]
- Laravel Version: 10.9.0
- Nova Version: 4.23.0
- PHP Version: 8.1.17
- Database Driver & Version: psql (PostgreSQL) 14.7 (Ubuntu 14.7-1.pgdg22.04+1)
- Operating System and Version: ubuntu:22.04 docker image
- Browser type and version: Chrome 114.0.5735.198
- Reproduction Repository: https://github.com/###/###

### Description:
The issue is related to the `target(): morphTo` relationship on the ActionEvent object.
The relationship implementation assumes that the `target` model has a `SoftDeletes` trait, which in some cases it doesn't.
Trying to eager load a model that doesn't use the `SoftDeletes` trait will throw a `BadMethodCallException` with the following error message: `Call to undefined method Illuminate\Database\Eloquent\Builder::withTrashed()`.

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Run an action on a resource whose model is not soft deleted
- Run a the following select query in a tinker session: 
        `ActionEvent::with('target')->where('actionable_type', (new NonSoftDeletedModel)->getMorphClass())->get()`

**Comment by crynobone** [comment]
Based on my test this seems to be an issue from the Framework especially `Illuminate\Database\Eloquent\Relations\MorphTo::replayMacros()`:

```
[2023-07-27 23:54:32] local.ERROR: Call to undefined method Illuminate\Database\Eloquent\Builder::withTrashed() {"exception":"[object] (BadMethodCallException(code: 0): Call to undefined method Illuminate\\Database\\Eloquent\\Builder::withTrashed() at /laravel/nova-dusk-suite/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:71)
[stacktrace]
#0 /laravel/nova-dusk-suite/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(36): Illuminate\\Database\\Eloquent\\Builder::throwBadMethodCallException('withTrashed')
#1 /laravel/nova-dusk-suite/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1660): Illuminate\\Database\\Eloquent\\Builder->forwardCallTo(Object(Illuminate\\Database\\Query\\Builder), 'withTrashed', Array)
#2 /laravel/nova-dusk-suite/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/MorphTo.php(362): Illuminate\\Database\\Eloquent\\Builder->__call('withTrashed', Array)
#3 /laravel/nova-dusk-suite/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/MorphTo.php(139): Illuminate\\Database\\Eloquent\\Relations\\MorphTo->replayMacros(Object(Illuminate\\Database\\Eloquent\\Builder))
#4 /laravel/nova-dusk-suite/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/MorphTo.php(121): Illuminate\\Database\\Eloquent\\Relations\\MorphTo->getResultsByType('App\\\\Models\\\\User')
#5 /laravel/nova-dusk-suite/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(673): Illuminate\\Database\\Eloquent\\Relations\\MorphTo->getEager()
#6 /laravel/nova-dusk-suite/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(642): Illuminate\\Database\\Eloquent\\Builder->eagerLoadRelation(Array, 'target', Object(Closure))
#7 /laravel/nova-dusk-suite/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(610): Illuminate\\Database\\Eloquent\\Builder->eagerLoadRelations(Array)
#8 /laravel/nova-dusk-suite/routes/web.php(24): Illuminate\\Database\\Eloquent\\Builder->get()
```

**Comment by crynobone** [comment]
Nevermind, this is under issue with Nova source code.
