### ISSUE TITLE
search bar not filling into request

### ISSUE THREAD

**Issue by electrictomcat** [laravel/nova-issues#5759]
- Laravel Version: 9.52
- Nova Version: 4.26.5
- PHP Version: 8.2
- Database Driver & Version: ---
- Operating System and Version: Mac OSX
- Browser type and version: Chrome 
- Reproduction Repository:

### Description:

When you use the search bar in a resource view and then trigger an action, the text in the search isn't being added to the Nova Request. We built custom logic to be able to fetch the models when using "All" and it relies on the search text being available in the request.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Create a resource.
Search within that resource.
With the search active trigger an action and log the request.

in the query input bag you will see:
"search" = null

**Comment by filipposallemi** [comment]
Hi @crynobone @davidhemphill there is any chance to solve this issue?
We have quite a lot of actions that are affected by this bug. Please give us an update
