### ISSUE TITLE
BelongsTo doesn't work in fieldsForCreate unless defined in Resource::fields

### ISSUE THREAD

**Issue by magdicom** [laravel/nova-issues#5760]
- Laravel Version: 10.16.0
- Nova Version: 4.23.0
- PHP Version: 8.2.8

### Description:
this issue is typical to the last one reported #5749 , the difference here is the field being called and the resource method I'm calling it from, the solution is the same as in #5749  

### Detailed steps to reproduce the issue on a fresh Nova installation:
to reproduce this error define a `BelongsTo` field in `Resource::fieldsForCreate` or `Resource::fieldsForUpdate`:

the code belong will give a 404 error, unless you define the same `BelongsTo` field in the `Resource::fields` method.

```php
class Post extends Resource
{
    public function fields(NovaRequest $request)
    {
        return [
            Text::make('Title'),
        ];
    }

    public function fieldsForCreate(NovaRequest $request)
    {
        return [
            BelongsTo::make('User'),
        ];
    }
}
```

**Comment by crynobone** [comment]
Please add `BelongsTo` field to `fieldsForCreate()` or `fields()` if you need to use this structure.

**Comment by sentq** [comment]
@crynobone using `BelongsTo` inside `fieldsForCreate` won't work unless its also specified in the `fields` method.

**Comment by crynobone** [comment]
My bad, use `fields` if you need this requirement.
