### ISSUE TITLE
Confilt when using in one function isFormRequest() & isResourceDetailRequest()

### ISSUE THREAD

**Issue by Patryk48** [laravel/nova-issues#5763]
- Laravel Version: 10.10.0
- Nova Version: 4.0.0
- PHP Version: 8.1.0
- Database Driver & Version:
- Operating System and Version: Ubuntu 21.04
- Browser type and version Chrome

### Description:
When using in resource class in one fuction  isFormRequest() & isResourceDetailRequest(), relation return confilts

![2023-08-01_23h26_15](https://github.com/laravel/nova-issues/assets/138042563/efddc6ce-cec2-4ecb-9351-92e3f9948c3c)
![image](https://github.com/laravel/nova-issues/assets/138042563/86a46abb-408a-4a85-b250-0a06dec09827)

**Comment by Patryk48** [comment]
![image](https://github.com/laravel/nova-issues/assets/138042563/871cab89-1b3a-4266-98da-0601bb388dcb)

**Comment by crynobone** [comment]
Can you show the complete error.

**Comment by crynobone** [comment]
That's no a correct use-case for `isFormRequest()` and `isResoruceDetailRequest()`.

Also, see https://nova.laravel.com/docs/4.0/resources/fields.html#dynamic-field-methods
