### ISSUE TITLE
Inability to deselect after selecting page content

### ISSUE THREAD

**Issue by mshtroylab** [laravel/nova-issues#5766]
- Laravel Version: 10.17.0
- Nova Version: 4.26.#

### Description:
after i click on  select all in index table and close the pop up,
after that unselect not working
![image](https://github.com/laravel/nova-issues/assets/135962688/bcee06d1-d405-4403-a559-177b71902a34)

https://github.com/laravel/nova-issues/assets/135962688/482f305d-de7a-49a9-acfa-8ad9db544ae9

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by VitaliyMinenko** [comment]
Have the same problem, 

https://github.com/laravel/nova-issues/assets/11076616/01668d2f-7a8c-44d8-b7f4-184877eab0f6

**Comment by VitaliyMinenko** [comment]
I resolve this by removing step by step composer puckages and found one which broke me header of the tables.
In my case it was "gobrightspot/nova-detached-actions": "dev-master",
