### ISSUE TITLE
Text unregisterd display after a time

### ISSUE THREAD

**Issue by giangnh13579** [laravel/nova-issues#5769]
- Laravel Version: Laravel Framework 10.5.1
- Nova Version: 4.22.2
- PHP Version: PHP 8.1.8

### Description:
- My applications which run with laravel nova display `UNREGISTERED` text after a time

![image](https://github.com/laravel/nova-issues/assets/132031200/45eb18ab-9153-487b-8701-80685494ffd2)

- In CI/CD, when starting docker container which contains laravel nova application, I've added command `php artisan nova:check-license` to check license.
- After deployment sucess, everything works fine. No `UNREGISTERED` displayed and in container log shows that command `php artisan nova:check-license` checked successfully. But after a time, few days or few weeks (I have 4 servers run with laravel nova), `unregistered` text display again

This text is annoying because in our servers, there are servers for production environment.

**Comment by crynobone** [comment]
Please contact Nova Support via email or [nova.laravel.com](https://nova.laravel.com/) as we need to identify your account before proceeding:
