### ISSUE TITLE
Users can't be impersonated more than once per session/back-to-back

### ISSUE THREAD

**Issue by amharris** [laravel/nova-issues#5773]
- Laravel Version: 10.17.1
- Nova Version: 4.26.5
- PHP Version: 8.2.7
- Database Driver & Version: MySQL 8.0.33
- Operating System and Version: Fedora 38 Workstation (running Laravel through Sail, with Docker Desktop)
- Browser type and version: Firefox 116; Chrome 115

### Description:

Impersonating users back-to-back isn't possible, resulting in the admin/Nova user being redirected to `/login` and having to sign in to `/nova` all over again, each time they wish to impersonate a user. 

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Set up a new Laravel instance (either via Composer or via the remote Sail shell script, passing in `mysql` as follows: `curl -s "https://laravel.build/example-app?with=mysql,memcached,mailpit,selenium" | bash`)
2. Add Jetstream (`composer require laravel/jetstream`)
   1.  (with Inertia + SSR: `php artisan jetstream:install inertia --teams --ssr --dark`)
3. Add Nova
4. Follow the [Nova documentation](https://nova.laravel.com/docs/4.0/customization/impersonation.html#enabling-impersonation) to add the 'Impersonation' trait
5. Create a few Users via a seeder or in the terminal
6. Sign in to `/nova` with one of them
7. Go to the list/table page for the User resource(s)
8. Click the overflow menu next to another user and select 'Impersonate'
   1. This should take you to the Dashboard, impersonating that user
9. Go back to `/nova` and click 'Stop Impersonating' on the panel in the top-right
10. Return to the list/table page for Users
11. Click 'Impersonate' against a different one
12. You should now find that it redirects to you `/login`
13. You have to go back to `/nova` and sign in all over again to be able to impersonate each and every time, rather than being able to impersonate multiple users, back-to-back

#### Other notes/findings:

The interesting detail I've spotted is that if I _don't_ try to impersonate for a second time (after having done so once), I _can't_ reach my `/dashboard` as though I'm a user, but I can _still_ access /nova.
If I login to `/nova` and _don't_ impersonate anyone, I _can_ switch to `/dashboard` (as you'd expect).

It's as if I'm still sort of signed into Nova as an admin, but not properly, and that the admin session needs logging in all over again in order to work properly.

I'm not sure as to whether part of the impersonated user's session details still remain after stopping the impersonation, and if that causes a conflict, leading to being signed out the next time around (or upon trying to access `/dashboard`), if stopping the session removes part of the admin/Nova user's session details, or if it's something else entirely.

**Comment by crynobone** [comment]
Unable to replicate the issue: https://github.com/nova-issues/issue-5773/commit/7a5c148f5b8ebb8afe6d5490fa5b6724ee215a45

Please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old or not relevant anymore. Feel to open up a new issue if you're still experiencing this problem.

**Comment by beiaduo** [comment]
Sometimes it's normal, sometimes it's not
