### ISSUE TITLE
Migrations not published with nova:install

### ISSUE THREAD

**Issue by kirkbushell** [laravel/nova-issues#5774]
- Laravel Version: 10.10
- Nova Version: 4.26.5
- PHP Version: #.#.#
- Database Driver & Version: Postgres
- Operating System and Version: Mac OSX Ventura 13.5
- Browser type and version: Chrome, latest.
- Reproduction Repository: N/A

### Description:

Installing a clean copy of nova isn't publishing the migrations

### Detailed steps to reproduce the issue on a fresh Nova installation:

Fresh install, Laravel and Nova, go through the install steps.

Nova installation will not publish the migrations, so artisan migrate does nothing, thereby resulting in lots of errors soon as you log in.

**Comment by crynobone** [comment]
Default installation doesn't publish migrations and it would load from Nova source code by default. Mind sharing the reproduction repository so we can debug the generated code.
