### ISSUE TITLE
Error in tests: "BadMethodCallException: Method Illuminate\Http\Request::inertia does not exist."

### ISSUE THREAD

**Issue by yaroslawww** [laravel/nova-issues#5775]
- Laravel Version: 10.x
- Nova Version: 4.x
- PHP Version: 8.1

### Description:
When I want  emulate api request for tests like
```php
 $response = $this->actingAs($this->admin)
    ->put("/nova-api/{$this->uriKey}/{$this->post->getKey()}", [
          'title' => 'FooBar',
    ]);
```
I receive the error `BadMethodCallException: Method Illuminate\Http\Request::inertia does not exist.`
This is because `NovaExceptionHandler@renderInertiaException` method has this code:
```php
if ($request->inertia()) {
    return Inertia::render('Nova.Error')->toResponse($request)->setStatusCode(500);
}

return parent::render($request, $e);
```
But in test `$request` is simple Request instance and not contains `inertia` method.

Can you add to code check?
```php
if (method_exists($request, 'inertia') && $request->inertia()) {
    return Inertia::render('Nova.Error')->toResponse($request)->setStatusCode(500);
}

return parent::render($request, $e);
```

**Comment by crynobone** [comment]
Inertia service provider provides the macro and your application would already auto discover that.

**Comment by yaroslawww** [comment]
@crynobone  Yes, thank you. If load `\Inertia\ServiceProvider` class all works perfectly. Thank you!
