### ISSUE TITLE
Lens does not respect eager loading on resource using $with

### ISSUE THREAD

**Issue by alex-osborn** [laravel/nova-issues#5777]
- Laravel Version: 10.17.1
- Nova Version: 4.26.5
- PHP Version: 8.2.5
- Database Driver & Version: MySQL 8
- Operating System and Version: OSX 13.3.1
- Browser type and version: Chrome 115
- Reproduction Repository: See screenshot

### Description:

Upgrading a project from Nova 3 -> 4.

A number of the lenses are not loading. 

We have lazy loading disabled at the Laravel level.

The Nova resources explicitly indicate the relations to eager load.

However running Nova 4, `$with` appears to be ignored on the resource when using a lens.

See screenshot - the eager loading is defined two lines above the line causing the error.

### Detailed steps to reproduce the issue on a fresh Nova installation:

![Screenshot 2023-08-07 at 2 33 39 PM](https://github.com/laravel/nova-issues/assets/880420/e38e3aed-d640-4d4d-b7f1-07f262d98c3e)

**Comment by crynobone** [comment]
Lens doesn't inherit Resource `$with` or `indexQuery()` and allows you full control over the generated SQL using `query()` method and this is the expected behavior.
