### ISSUE TITLE
Redirect to /login not working

### ISSUE THREAD

**Issue by fetaciik** [laravel/nova-issues#5778]
- Laravel Version: 10.17.1
- Nova Version: 4.26.5
- PHP Version: 8.1.7

### Description:

I changed path in nova.php configuration to '/'. At first everything was ok but from some version whenever access key expired it wouldn't redirect me to /login but just give blank page with code 200.

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)
