### ISSUE TITLE
Selected all checkbox allow to force delete all resourses.

### ISSUE THREAD

**Issue by VitaliyMinenko** [laravel/nova-issues#5780]
- Laravel Version: 10.0
- Nova Version: 4.23.0
- PHP Version: 8.1
- Database Driver & Version:
- Operating System and Version: Ubuntu
- Browser type and version: Chrome

When i create resoure i disable posibility to force delete by method 
`    public function authorizedToForceDelete(Request $request)
    {
        return false;
    }`

But when i choose checkbox Select all at main menu that nova allow to force delete and replicate this items.

![image](https://github.com/laravel/nova-issues/assets/11076616/615f71b9-23a3-4180-adb0-4dca9157b68b)

**Comment by crynobone** [comment]
Explained in https://github.com/laravel/nova-issues/discussions/4474#discussioncomment-3008533
