### ISSUE TITLE
Invalid Argument Exception : View [app] not found.

### ISSUE THREAD

**Issue by ValentinGaudin** [laravel/nova-issues#5781]
- Laravel Version: 10.12.0
- Nova Version: 4.24.4
- PHP Version: 8.2
- Database Driver & Version: MSSQL 18.1
- Operating System and Version: Mac M1 / Ventura 13.4
- Browser type and version: Arc 1.2.1

### Description:

I created a user via `CreaterUserUsing` command in nova, make a observer to trigger the creation, and send a link to reset password.

I obtain this : 

<img width="1084" alt="image" src="https://github.com/laravel/nova-issues/assets/81967154/3265039b-e48d-44ec-979f-99161d9e86e3">

### Detailed steps to reproduce the issue on a fresh Nova installation:
Add UserObserver
```php
    public function created(User $user): void
    {
        Password::sendResetLink(['email' => $user->email]);
    }

```
Create User With command
Click on link

Someone have information to avoid this error ?

Other project work perfectly, miss something ?

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by ValentinGaudin** [comment]
Hello @crynobone ! 

It's a private repo on GitLab so : 

Create a UserObserver and add this : 
```php
    /**
     * Handle the User "created" event.
     */
    public function created(User $user): void
    {
        Password::sendResetLink(['email' => $user->email]);
    }
```

The static password is from Facade.

Bind the observer in the `protected $observers` in  the EventServiceProvider.php.

Lunch the `php artisan nova:user`

Create a user

Catch the email and click on the button to reset the password. 

It's that all you need ?

**Comment by crynobone** [comment]
`Laravel\Nova\Http\Controllers\ResetPasswordController` is an internal controller, if you need to reuse this you need to ensure all required middlewares and additional requirements is added.

**Comment by crynobone** [comment]
You can create your own `Controller` either using `laravel/ui`, `laravel/breeze` or `laravel/jetstream`. The Controller from Laravel Nova is specifically used for Nova. We don't support using it outside it designed purposed.
