### ISSUE TITLE
Nova Notifications breaks some words

### ISSUE THREAD

**Issue by henryavila** [laravel/nova-issues#5784]
- Laravel Version: 10.17.1
- Nova Version: 4.26.5
- PHP Version: 8.1

### Description:
Some words on Nova Notifications are breaked.
![image](https://github.com/laravel/nova-issues/assets/8429941/15fd2c77-900e-4644-89f2-a9436c86df88)

Removing the "break-all" fix the problem
![image](https://github.com/laravel/nova-issues/assets/8429941/bb2d807e-9ff4-446d-87f3-4ca86c605498)
![image](https://github.com/laravel/nova-issues/assets/8429941/13551012-a92f-4464-8201-8e5ee0736501)

and still it works with different text size

![image](https://github.com/laravel/nova-issues/assets/8429941/0b335dca-0af2-44e7-9a8b-ea31a5808178)
![image](https://github.com/laravel/nova-issues/assets/8429941/3f36dfa0-0e0d-463d-835d-a041d8e13e3f)

### Detailed steps to reproduce the issue on a fresh Nova installation:
Send NovaNotification with the folowing text: "This is a sample of notification with more than one line. Some long words are "breaked""

**Comment by crynobone** [comment]
Conflict with #5618

**Comment by henryavila** [comment]
This solved booth of the problems

``` css
-ms-word-break: break-all;
word-break: break-all;
word-break: break-word;

-webkit-hyphens: auto;
-moz-hyphens: auto;
hyphens: auto;
```


![image](https://github.com/laravel/nova-issues/assets/8429941/6218df51-4ac1-4c91-a7d6-c38cac5255a3)

![image](https://github.com/laravel/nova-issues/assets/8429941/87c84528-3298-4434-9957-43e4360d4ddd)
