### ISSUE TITLE
Metric range for current day doesn't work

### ISSUE THREAD

**Issue by hermanschutte** [laravel/nova-issues#579]
When adding a range for 0 days, `now()->subDays(0)`, no data is returned. Is it possible to get metric values for only the current day?

```php
public function ranges()
{
    return [
        0 => 'Today',
        1 => 'Yesterday',
        30 => '30 Days',
        60 => '60 Days',
        365 => '365 Days',
        'MTD' => 'Month To Date',
        'QTD' => 'Quarter To Date',
        'YTD' => 'Year To Date',
    ];
}
```

**Comment by dillingham** [comment]
Yesterday to now is "today", also checkout `[->showLatestValue()](https://nova.laravel.com/docs/1.0/metrics/defining-metrics.html#displaying-the-current-value)`

**Comment by hermanschutte** [comment]
> Yesterday to now is "today", also checkout [->showLatestValue()](https://nova.laravel.com/docs/1.0/metrics/defining-metrics.html#displaying-the-current-value)

Thanks, [->showLatestValue()](https://nova.laravel.com/docs/1.0/metrics/defining-metrics.html#displaying-the-current-value) is exactly what I was looking for.
