### ISSUE TITLE
phpstan complains about Repeater Field

### ISSUE THREAD

**Issue by DenMette** [laravel/nova-issues#5792]
- Laravel Version: 10.18.0
- Nova Version: 4.26.5
- PHP Version: 8.2
- Database Driver & Version: n/a
- Operating System and Version: n/a
- Browser type and version: n/a
- Reproduction Repository: n/a

### Description:

When using phpstan with the defaults of larastan I encounter an issue with the Repeater Field.
`Parameter 1 $repeatables of method Laravel\Nova\Fields\Repeater::repeatables() expects array<int, string>, array<int, CustomRepeater> is given`.

### Detailed steps to reproduce the issue on a fresh Nova installation:

`phpstan.neon`

```neon
includes:
    - ./vendor/nunomaduro/larastan/extension.neon
parameters:
    paths:
        - app
    level: 9
    ignoreErrors:
    excludePaths:
    checkGenericClassInNonGenericObjectType: false
```

Just run phpstan

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
