### ISSUE TITLE
Notifications : Mark as read is display when the notif is already readed

### ISSUE THREAD

**Issue by valentinrougier39** [laravel/nova-issues#5798]
- Laravel Version: 10.18
- Nova Version: 4.27.10
- PHP Version: 8.1
- Database Driver & Version: MYSQL

### Description:
Hi, I've updated Laravel and Nova on lastest version. About Notifications center : when a notification is read, the button "Mark as read" is still displayed. In MessageNotification.vue, I feel like there is no condition on that : if the notification is already readed or not.

Thank you

**Comment by crynobone** [comment]
Fixed in https://nova.laravel.com/releases/4.27.12

**Comment by valentinrougier39** [comment]
@crynobone , after update the package in 4.27.12, and re-install to be sure, it seems doesn't work
