### ISSUE TITLE
Required asterisk doesn't appear in action lens

### ISSUE THREAD

**Issue by Keko-94** [laravel/nova-issues#5799]
- Laravel Version: 10.18
- Nova Version: 4.27.10
- PHP Version: 8.1
- Database Driver & Version: MariaDB
- Operating System and Version: Win10
- Browser type and version: Firefox@latest
- Reproduction Repository: https://github.com/Keko-94/nova-clean

### Description:
No asterisk in the required fields action from a Lens
![image](https://github.com/laravel/nova-issues/assets/62820283/a2654a2f-56ee-4c17-9c62-64252ff176d0)

### Detailed steps to reproduce the issue on a fresh Nova installation:
In the User resource, register a Lens and an Action
In the Lens register the same action
In the Action, add a field like that:
`Text::make('Toto')->rules('required')`

**Comment by crynobone** [comment]
![CleanShot 2023-08-14 at 11 00 45](https://github.com/laravel/nova-issues/assets/172966/b2f63c31-359d-4097-862a-9db1c102e00f)

Unable to replicate the issue: 

https://github.com/laravel/nova-dusk-suite/blob/9702bc75193b377b129f8f9e2efc778e23e475bd/app/Nova/Actions/ChangeCreatedAt.php#L40-L46

**Comment by crynobone** [comment]
![CleanShot 2023-08-14 at 11 00 45](https://github.com/laravel/nova-issues/assets/172966/b2f63c31-359d-4097-862a-9db1c102e00f)

Unable to replicate the issue: 

https://github.com/laravel/nova-dusk-suite/blob/9702bc75193b377b129f8f9e2efc778e23e475bd/app/Nova/Actions/ChangeCreatedAt.php#L40-L46

https://github.com/laravel/nova-dusk-suite/blob/02ef6a6b4207be13687797e4c804979791b122ef/app/Nova/Lenses/PassthroughLens.php#L91-L95

**Comment by Keko-94** [comment]
I tried again my issue persists.

**User (resource):**

```
public function lenses(NovaRequest $request)
    {
        return [
            new UserLens()
        ];
    }
```

```
public function actions(NovaRequest $request)
    {
        return [
            ChangeCreatedAt::make()->sole()
        ];
    }
```

**UserLens (lens):**


```
 public function actions(NovaRequest $request)
    {
        return parent::actions($request);
    }
```



**ChangeCreatedAt (action):**
```
 public function fields(NovaRequest $request): array
    {
        return [
            DateTime::make('Created At', 'created_at')
                ->rules('required'),
        ];
    }
```

I updated my repo if you want to check.

**Comment by crynobone** [comment]
Clone your repository and tests it out on Firefox and still can't reproduce:

https://github.com/laravel/nova-issues/assets/172966/ae85a174-3286-4f72-8371-25da07d27fef

**Comment by crynobone** [comment]
Does two usage doesn't affect required. You need to provide the exact replication steps as I have tested your example repository and above video clearly shows that it's working as expected.

**Comment by Keko-94** [comment]
Called the action from the three dots.

https://github.com/laravel/nova-issues/assets/62820283/0a99d7da-b46a-44d0-8981-7a0bbea2a571
