### ISSUE TITLE
CSS problem with loading status in dark mode 

### ISSUE THREAD

**Issue by massimodellarovere** [laravel/nova-issues#5802]
- Laravel Version: 9.52.15
- Nova Version: 4.27.10
- PHP Version: 8.1.21
- Database Driver & Version: MYSQL 8.0
- Operating System and Version: Ubuntu 22.04 LTS
- Browser type and version: brave & chrome

### Description:

![image](https://github.com/laravel/nova-issues/assets/5731295/848fced7-f265-4e27-bb57-fa57f9e46152)

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
