### ISSUE TITLE
Dragging a file can cause Select ->searchable() to show options

### ISSUE THREAD

**Issue by Samuele-Mori** [laravel/nova-issues#5804]
- Laravel Version: 10.18.0
- Nova Version: 4.26.5
- PHP Version: 8.2.9

### Description:
After selecting an option if i drag a file, with no other clicks, my searchable Select shows the options. This prevents the file from being uploaded.
Without `->searchable()` I don't have this issue.
This also happens using the example in the documentation.

My code is pretty basic, it's just a searchable select.
   ```
 public function fields(Request $request)
    {
        return [
            Select::make('Size')->searchable()->options([
                'S' => 'Small',
                'M' => 'Medium',
                'L' => 'Large',
            ])->displayUsingLabels(),

            Select::make('Size no searchable')->options([
                'S' => 'Small',
                'M' => 'Medium',
                'L' => 'Large',
            ])->displayUsingLabels(),
            
            // Test, unnecessary
            File::make(__('File'), 'path'),
        ];
    }
```

![select](https://github.com/laravel/nova-issues/assets/6436017/a95c5e31-e029-4ec0-ae4f-9d974a4ebc9b)

### Detailed steps to reproduce the issue on a fresh Nova installation:
To reproduce this issue you just need a Select with `->searchable()`. I hope this is enough.

**Comment by crynobone** [comment]
Please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by Samuele-Mori** [comment]
I'm sorry for the lack of information.

### Detailed steps to reproduce the issue on a fresh Nova installation:

To reproduce the code I used [issue-5605](https://github.com/nova-issues/issue-5605) as referecence.

- Clone and set up
- In App/Nova/Booking.php add `use Laravel\Nova\Fields\Select;` and
```
Select::make('Size')->searchable()->options([
                'S' => 'Small',
                'M' => 'Medium',
                'L' => 'Large',
            ])->displayUsingLabels(),
```
in fields function. I added the code to line 50.
- Go to the [page](http://localhost:8000/resources/bookings/new)
The searchable select should be visible.

![image](https://github.com/laravel/nova-issues/assets/6436017/f89af110-41d0-4b95-b015-f6eaeb727381)

- Select a size
- Drag a file
Notes: No clicks between selecting and dragging. To reproduce the bug the select must have focus.

![select-issue5605](https://github.com/laravel/nova-issues/assets/6436017/ee0393cf-8cf7-4521-8dd2-0a7443a6f561)
