### ISSUE TITLE
Impersonation doesn't redirect properly when using APP_URL

### ISSUE THREAD

**Issue by puzzledmonkey** [laravel/nova-issues#5812]
- Laravel Version: 10
- Nova Version: 4,27,12
- PHP Version: 8.2

### Description:
Impersonation doesn't redirect properly when using APP_URL

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Use NOVA_PATH to set Nova to run in a subfolder
2. Impersonate someone
3. Note how you're redirected to / instead of /<nova-path>

to fix, the default should probably be
```
'impersonation' => [
    'started' => '/' . trim(env('NOVA_PATH', ''), '/'),
    'stopped' => '/' . trim(env('NOVA_PATH', ''), '/'),
],
```
in config/nova.php

**Comment by crynobone** [comment]
Laravel doesn't support such usage https://laravel.com/docs/10.x/installation#directory-configuration

**Comment by puzzledmonkey** [comment]
> Laravel doesn't support such usage https://laravel.com/docs/10.x/installation#directory-configuration

Then what is the point of the NOVA_PATH?

(My apologies for writing APP-_URL in the description, I meant NOVA_PATH)

**Comment by crynobone** [comment]
I can only assume what you trying to do here based on the description. Maybe best to have a reproduction repo.

**Comment by puzzledmonkey** [comment]
I just want Nova to redirect to the main Nova landing page rather than /, when NOVA_PATH is set and I impersonate/stop impersonating someone.

**Comment by puzzledmonkey** [comment]
Or perhaps Nova just needs to wrap the impersonation URLs in Nova::url () instead of changing the config file?

**Comment by puzzledmonkey** [comment]
@crynobone does this explain my use case and the issue I'm experiencing?
