### ISSUE TITLE
The Nova HomeController isn't calling the initialPath closure

### ISSUE THREAD

**Issue by peterr6** [laravel/nova-issues#5814]
- Laravel Version: 9.52.15
- Nova Version: 4.12.0
- PHP Version: 8.1.21
- Operating System and Version:  macOS Ventura 13.4.1
- Browser type and version: chrome 115.0.5790.114

### Description:
The Nova HomeController isn't calling the initialPath closure.

### Detailed steps to reproduce the issue on a fresh Nova installation:
In NovaServiceProvider.php

Nova::initialPath( function($request) {
    return $request->user()->isAdmin() ? '/dashboards/overview' : '/resources/incidents';
} );

[2023-08-17 11:20:51] local.ERROR: Object of class Closure could not be converted to string {"userId":1521,"exception":"[object] (Error(code: 0): Object of class Closure could not be converted to string at /app/vendor/laravel/nova/src/Concerns/HandlesRoutes.php:17)

[stacktrace]
#0 /app/vendor/laravel/nova/src/Http/Controllers/Pages/HomeController.php(19): Laravel\\Nova\\Nova::url(Object(Closure))

**Comment by crynobone** [comment]
This has been fixed and is pending the next release
