### ISSUE TITLE
Documentation pages can't be opened in a new tab, 404

### ISSUE THREAD

**Issue by maryisdead** [laravel/nova-issues#5815]
Since you can't open issues in https://github.com/laravel/nova-docs, I'll just leave this here.

You can't open any of the pages of the left-hand navigation in a new tab. I don't know what's going on under the hood but this happens for Global Search, for example:

1. URL is https://nova.laravel.com/docs/search/global-search
2. Upon clicking it, it actually opens https://nova.laravel.com/docs/search/global-search.html

This "redirect" doesn't happen if you request https://nova.laravel.com/docs/search/global-search directly, resulting in 404.

**Comment by davidhemphill** [comment]
This should be fixed.
