### ISSUE TITLE
Nova userTimezone not working as expected

### ISSUE THREAD

**Issue by mnowak-umich** [laravel/nova-issues#5818]
- Laravel Version: 9.52.15
- Nova Version: 4.27.12
- PHP Version: 8.2.8
- Database Driver & Version: MySQL
- Operating System and Version: MacOS 10.15
- Browser type and version: Chrome 16.0.5845.96

### Description:

So I read in the docs that I can set the timezone per user using the userTimezone method in the nova service provider. However, in Nova, it still says UTC next to all of my DateTime fields. When you edit a field, it shows the timezone I specified in the datetime editor but it saves it back to the database with the time I chose but in UTC. So in the editor, it says America/Detroit next to the field and if I enter noon, I would expect to see 16:00 in the database since UTC is currently 4 hours ahead. But I see 12:00 in the database.

Perhaps I need clarification on any additional steps I need to take to make this feature work. I expected to see UTC datetimes converted to the user's timezone and upon save, those datetimes converted back to UTC and stored that way.

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by mnowak-umich** [comment]
@crynobone Here's a simple repo: https://github.com/mnowak-umich/timezone-test

And a video of my demonstration of the issue: https://www.loom.com/share/48b7c50742bd481d8241ff4c2b9edf94?sid=e3d49038-5b7a-435d-b9d9-b859f1f2a136

Thanks for looking into this.

**Comment by crynobone** [comment]
Unable to replicate the issue using your repository.

https://github.com/laravel/nova-issues/assets/172966/b00082a3-47f2-45b1-8e4e-324a6a755208

**Comment by mnowak-umich** [comment]
@crynobone Any thoughts on what might be happening?
