### ISSUE TITLE
The action menu in the details view appears empty

### ISSUE THREAD

**Issue by mshtroylab** [laravel/nova-issues#5820]
- Laravel Version: 10.#.#
- Nova Version: 4.#.#

### Description:
 If there are no actions, the menu should be hidden

### Detailed steps to reproduce the issue on a fresh Nova installation:
![image](https://github.com/laravel/nova-issues/assets/135962688/fbd49a61-7800-40c9-a61f-e7f2e25babbc)

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by mshtroylab** [comment]
@crynobone 
If I remove edit and delete the permissions from the resource the kebab button still exist even it's empty

**Comment by crynobone** [comment]
> If I remove edit and delete the permissions from the resource the kebab button still exist even it's empty in show resource page

Still need that reproducing repository in order for us to debug the issue.

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
