### ISSUE TITLE
`Nova::initialPath` as closure error `Object of class Closure could not be converted to string`

### ISSUE THREAD

**Issue by dmason30** [laravel/nova-issues#5824]
- Nova Version: 4.27.12

### Description:
Search nova code for usages of `Nova::$initialPath` you will find two places doing `Nova::url(Nova::$initialPath)` in `HomeController` and `LoginController`.

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. In `NovaServiceProvider` define the below
```php
Nova::initialPath(function () {
    return '/dashboards/main';
});
```
2. In nova navigate to nova root path in browser address bar (e.g. `domain.dev/nova`)
3. Below error occurs
<img width="1384" alt="image" src="https://github.com/laravel/nova-issues/assets/20278756/d3c07ec2-e875-48fa-9c90-61b089c48228">

**Comment by crynobone** [comment]
fixed and pending next release

**Comment by dmason30** [comment]
Oh mb sorry @crynobone
