### ISSUE TITLE
2 Belongs To Depending on Each Other cancelling each other's value

### ISSUE THREAD

**Issue by muhammadsaeedparacha** [laravel/nova-issues#5825]
- Laravel Version: 10.x
- Nova Version: latest
- PHP Version: 8.2
- Database Driver & Version:
- Operating System and Version: Mac latest
- Browser type and version: Chrome latest
- Reproduction Repository: https://github.com/###/###

### Description:
```
BelongsTo::make('Client')->dependsOn(['contact'], function ($field, $request, $formData) {
    // Update relatable query so only client of selected contact shows up
    // $formData does not have value of itself
}),
BelongsTo::make('Contact')->dependsOn(['client'], function ($field, $request, $formData) {
    // Update relatable query so only contacts of selected client show up
    // $formData does not have value of itself
}),
```
When I select a Contact,
Then I select a Client,
The contact value becomes null

Bug: The field doesn't store the field value in `value` property
<img width="1290" alt="Screenshot 2023-08-22 at 8 30 49 AM" src="https://github.com/laravel/nova-issues/assets/2680384/1746cf28-895e-4bef-9c71-05087057a152">

`DependentFormField` sends the empty `value` property in request for dependson

**Comment by crynobone** [comment]
Sorry but we don't officially support recursive depends on.
