### ISSUE TITLE
Model Events fired from Laravel Nova aren't able to access the model's relationships

### ISSUE THREAD

**Issue by danhanly** [laravel/nova-issues#5829]
- Laravel Version: 10.19.0
- Nova Version: 4.27.12
- PHP Version: 8.2.8
- Database Driver & Version: MariaDB 10.11.4
- Operating System and Version: Sail 1.23.4
- Browser type and version: Firefox (latest)
- Reproduction Repository: N/A

### Description:

I’m having an issue with model events from certain contexts.

When a new ‘Post’ model is created, I store the ‘Latest Post Date’ against the User. I do this by using model events on the Post model:

```
static::saved(function (Post $post) {
    $post->author->latest_post_date = data_get($post->author->latestPost(), 'latest_post_date');
    $post->author->save();
});
```

When a post is saved, it grabs the latest Post by that author, and stores the field in `latest_post_date`. This supports editing an existing Post to adjust the post date, and creating. It always selects the correct latest post date.

I’ve tests supporting this, and it’s working as expected throughout my application and in production.

The issue I have is specifically within Laravel Nova.

When a new ‘Post’ is created in Nova, the Post passed to the model event is fully devoid of all relations - which means I get null upon requesting `$post->author`

Within the model event, I’ve tried the following:

```
1. $post->refresh();
2. $post->load('author');
3. $post->author()->first();
4. Author::find($post->author_id); // I can confirm $post->author_id is correctly filled with the relevant ID, and that the Author model does in fact exist
```

All of the above returns null on those relationships within the model event, only when triggered through Laravel Nova.

I’ve dug through the Laravel Nova ‘Resource’ class and all relevant traits to see if I can identify the point in which the model relations are stripped out, or perhaps a property that explicitly disables them but to no avail (though I may have missed it, some of that code is dense).

I’ve also tried replicating this logic by overloading the ‘Resource’ `afterCreate` method, but this has the same behaviour.

The issue only exists when the Post is created directly via Laravel Nova; when creating the Post within the context of my application proper, it works as expected.

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Create a `Post` model that is related to a parent model (like `Author` for example)
2. Create a `belongsTo` method on the `Post` that relates it specifically to the dependent model
3. Create a `static::saved` model event on the `Post` model that accesses the dependent relationship
4. Create and save an instance of the model through Laravel proper
5. Create and save an instance of the model through Laravel Nova

Step 4 will function as expected, but Step 5 will fail as the dependent relationship will not be correctly loaded.

**Comment by crynobone** [comment]
Please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by danhanly** [comment]
In case anyone else encounters the same, I'll update with what was actually happening in the background, then close.

I had a global scope on my Author model that depended on some authentication data.

This meant that when I was using the site from either my tests, or my main application, the authentication data was present, and all relevant models were related to that authentication data.

However, as I'm logged in as an 'admin' user within Nova, it meant the authentication data wasn't present, or didn't relate to the record I was updating.

Though a quirk of the way Nova works mean it didn't throw an exception, but rather just failed quietly and refused to load the relation. So from Nova, the relation was null (even if I tried to load it directly), but from the main site the relation was filled correctly.

An exception instead of a quiet fail would have saved some serious time, but that's not the crux of this issue.
