### ISSUE TITLE
handleKeydown event in resource index

### ISSUE THREAD

**Issue by daguilarm** [laravel/nova-issues#583]
Hi, I am working in a card (located in the resource index), and it has a input form. The problem is each time you push 'c' key on the keyboard will redirect you to the resource create page, and this is a problem when you write in something in the input field and push the 'c' key.

There is a way to disable this feature? to remove this key shortcuts?

**Comment by davidhemphill** [comment]
You have to instruct your card to stop propagation of the keydown event. Something like this:

```vue
<template>
  <input @keydown.stop="handleKeydown" />
</template>
```

Otherwise, the event will bubble all the way up to the global handler which redirects to the create screen for the resource.
