### ISSUE TITLE
Inline more action icon without any action 

### ISSUE THREAD

**Issue by parth-ka-patel** [laravel/nova-issues#5830]
- Laravel Version: ^8.75
- Nova Version: 4.25.1
- PHP Version: 7.4.23
- Database Driver & Version:
- Operating System and Version: Windows 11 Pro 22H2
- Browser type and version: Google Chrome 116.0.5845.97

### Description: 
I don't want the replication in some resources so then I used the authorizedToReplicate and return false it'll not display right now but the blank icon is displayed on inline rows so is there any option to hide them ??

### Detailed steps to reproduce the issue on a fresh Nova installation:
Create any new resource and apply this method in nova resource **authorizedToReplicate** and just return false then it'll happen

 
![Screenshot 2023-08-23 114849](https://github.com/laravel/nova-issues/assets/87844357/3fa42cd2-3cd0-4a02-ad18-0af2eda3f930)

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

![CleanShot 2023-08-23 at 14 38 42](https://github.com/laravel/nova-issues/assets/172966/c3063f5a-05f8-4e81-bb11-5701dab3f9d0)

https://github.com/laravel/nova-dusk-suite/blob/02ef6a6b4207be13687797e4c804979791b122ef/app/Nova/Captain.php#L147-L156

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
