### ISSUE TITLE
list resource : can't delete an item

### ISSUE THREAD

**Issue by valentinrougier39** [laravel/nova-issues#5839]
- Laravel Version: 10.19.0
- Nova Version: 4.27.13
- PHP Version: 8.1
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

Hi, on List Resource, when I click on the trash to delete an item, the modal is not showed, I've the black filter behind the modal but the modal doesn't appear. I've all permissions to view, update delete... And I've checked : if we disable permissions, the trash disapear.
Have you a solution please ? Is pretty sensitive because admin's can't delete some items. 

Thank you

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
