### ISSUE TITLE
Date format bug

### ISSUE THREAD

**Issue by victorpfm** [laravel/nova-issues#584]
Date formatting only works when I use the DateTime field type, and don't work when I use the Date field type.

```
Date::make('Término', 'termino')->format('DD/MM/YYYY'), // doesnt work, displays the default yyyy-mm-dd
DateTime::make('Término', 'termino')->format('DD/MM/YYYY') // works properly
```

The problem is I dont want to have the hour and minute option on the form.

**Comment by davidhemphill** [comment]
Can you explain the problem with a little more detail? Having trouble getting what you're expecting and what's actually happening in the interface.

**Comment by victorpfm** [comment]
I'm expecting the DateField Date::make('Término', 'termino')->format('DD/MM/YYYY') to display the date in the given format on detail and index pages. It actually displays it in the default format YYYY-MM-DD

**Comment by RicardoRamirezR** [comment]
See #44

**Comment by taylorotwell** [comment]
Does it show the correct format on the index and detail screens?

**Comment by dwyer14** [comment]
@taylorotwell No, default formatting on both index & detail.

**Comment by nickels** [comment]
I'm on v1.1.1 - ran php artisan nova:publish after upgrade.

```
Date::make('Date')->format('DD MMM'),
```

returns `2018-09-25` on the index & details field.

**Comment by RicardoRamirezR** [comment]
@nickels remember `php artisan view:clear` here is ok.

**Comment by dwyer14** [comment]
Yup, that did it! Will open a separate issue for `NULL` dates.

**Comment by nickels** [comment]
@RicardoRamirezR, thanks for the tip. Easy one to forget, unfortunately no joy for me!

**Comment by RicardoRamirezR** [comment]
@nickels and `php artisan nova:publish --force`?
