### ISSUE TITLE
HasManyThrough Relationship

### ISSUE THREAD

**Issue by Benjyclay** [laravel/nova-issues#585]
I have Orders, Items and OrderItems. The below is the relationship on the Order model.

```
return $this->hasManyThrough(Items::class, OrderItem::class);
```

To add a HasManyThrough Relationship record requires a user to create the pivot table's resource. The HasMany Field works but when you hit create it will create the Item rather than an OrderItem.

**Comment by ragingdave** [comment]
I ran into this too and I think it's just a missed relation in Nova altogether. The only way at this time might be creating a custom resource tool, perhaps generic enough to share that just displays a read only list for now.

**Comment by nickels** [comment]
@davidhemphill is this being considered?

**Comment by davidhemphill** [comment]
Yes.

**Comment by CraigHarley** [comment]
@davidhemphill has there been any movement on this? It'd be a great feature to have.

**Comment by BobbyBorisov** [comment]
@CraigHarley I was wondering can we make the has many through relation in the model and use HasMany in the Nova resource fields?

**Comment by CraigHarley** [comment]
Yeah you can do that, but as somebody else mentioned it fails when creating a new relationship through Nova then.

Viewing is fine with that set up.

**Comment by BobbyBorisov** [comment]
Ah I see, for now I need only viewing, so I guess I'm fine! Would be nice to have the full feature though! Maybe in the next version of Nova. 🙏

**Comment by iHazzam** [comment]
Any movement on this?

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by iHazzam** [comment]
@davidhemphill What's the best way to make feature requests (or requests for custom packages? I guess?) 
This is pretty key in my eyes and I'm keen to keep pursuing it

**Comment by Pamposgsk** [comment]
> Yes.

Hi Is there a plan to include this relationship?

**Comment by francoisauclair911** [comment]
+1

**Comment by rexliu0715** [comment]
+1

**Comment by artisaninweb** [comment]
+1

**Comment by xmannv** [comment]
Same question is it available ?

**Comment by GuidoThomassen** [comment]
+1

**Comment by ryancco** [comment]
+1

**Comment by 4n70w4** [comment]
Any news?

**Comment by halberio** [comment]
+1

**Comment by maherelgamil** [comment]
+1

**Comment by abkrim** [comment]
+1

**Comment by amandasaffer** [comment]
+1

**Comment by ragingdave** [comment]
@davidhemphill We are now over a year past the "it's being considered" comment, and seemingly there has been no movement on it as well as no communication regarding this. Even I'm starting to get annoyed by all the "+1" comments that end up as issue notifications. Can there be any sort of update as to if this is actually being worked at in any capacity at all? If only just to stop the "+1" and additional questions at least? With Nova specifically saying:

> Nova has full support for all of Laravel's relationships

This ticket seems to just want to actually make good on that statement, because HasManyThrough is, in fact, a Laravel relationship type so it missing is what everyone is going on about. Any sort of update would likely go along way with addressing this issue rather than it just getting closed without any sort of resolution since, technically this isn't a feature request, but is actually a bug that needs fixing.

**Comment by SanderMuller** [comment]
+1

**Comment by bruno-rodrigues** [comment]
@taylorotwell ?

**Comment by janjakabovic** [comment]
+1
@taylorotwell  @davidhemphill

**Comment by genesiscz** [comment]
+1

**Comment by wwwroth** [comment]
Bummed out I just ran into this blocker. +1.

**Comment by Tyldar** [comment]
+1

**Comment by laradvance** [comment]
+1

**Comment by ffeeff** [comment]
+1

**Comment by ineghi** [comment]
+1

**Comment by chescos** [comment]
How is this still not supported?

**Comment by priceluke** [comment]
+1

**Comment by imashosx** [comment]
+1

**Comment by bulldog5046** [comment]
Oh good, i'm not going mad! +1

**Comment by demency** [comment]
We need 2 release the kraken 😂✌️ +1

**Comment by bertoloti** [comment]
+1

**Comment by jwktje** [comment]
+1

**Comment by neoplomero** [comment]
+1

**Comment by noncototient** [comment]
+1

**Comment by aubreychiduku** [comment]
+1

**Comment by khaledBawz** [comment]
+1

**Comment by chescos** [comment]
-1

**Comment by Payetus** [comment]
+1

**Comment by matthewjumpsoffbuildings** [comment]
As @ragingdave said, this isnt a feature request - this is a glaring oversight of a basic Laravel eloquent relationship. HasManyThrough has been a part of Laravel since at least v4, probably v3. @davidhemphill this is a paid product, give us _some_ idea of what is going on

**Comment by matthewjumpsoffbuildings** [comment]
Oh great, looks like they have no plans to support it :|

https://github.com/laravel/nova-issues/issues/1683#issuecomment-506413763

**Comment by davidhemphill** [comment]
I just put in a PR to add this to Nova. Thanks everybody!

**Comment by brillliant** [comment]
> I just put in a PR to add this to Nova. Thanks everybody!

what nova vesrion has this fix?

thanks in advance

**Comment by davidhemphill** [comment]
Next release will support the feature.
