### ISSUE TITLE
filterable() on JSON column does not work

### ISSUE THREAD

**Issue by jdion84** [laravel/nova-issues#5858]
adding the `filterable` method to a JSON column does not do anything:

```php
Boolean::make("Accept Terms", "customer_fields->accept_terms")
    ->filterable(),
```

when i apply filters nothing happens, it just keeps showing all records

do i need to specify a custom closure for every JSON field or is there some other way to make this work?

**Comment by crynobone** [comment]
Please submit a proper bug report using the given template: https://github.com/laravel/nova-issues/issues/new?assignees=&labels=&projects=&template=1_Bug_report.md

**Comment by jdion84** [comment]
i must have had something cached because its working great now
