### ISSUE TITLE
Cant search index by related model field

### ISSUE THREAD

**Issue by victorpfm** [laravel/nova-issues#586]
When I add a related field in the $search array:

`public static $search = ['user.name'];`

Nova tries to search a literal user.name field and not the field name in users table.

**Comment by dillingham** [comment]
@victorpfm there's a package for that 

https://novapackages.com/packages/titasgailius/search-relations

**Comment by davidhemphill** [comment]
Yeah, this is not supported in core currently. The package above seems nice, but haven't tested it with the various DB drivers supported in Laravel.
