### ISSUE TITLE
Asset loading performance issue

### ISSUE THREAD

**Issue by patrix152** [laravel/nova-issues#5868]
- Laravel Version: 10.10.0
- Nova Version: 4.0.0
- PHP Version: 8.
- Database Driver & Version:
- Operating System and Version: Ubuntu 21.04
- Browser type and version: Chrome, Firefox
- Reproduction Repository: https://github.com/###/###

### Description:
I am struggling with performance new.
I checked the resource and queries between the database and the backend go fast.

The problem is assets, in the case of large components, nova loads them terribly slow. availability time about 10s.

I believe that the problem may be that all scripts are loaded at boot, which causes a custom field or resource tool that is not used in a given view to be loaded

![image](https://github.com/laravel/nova-issues/assets/34523222/9e96730a-1be7-470f-accf-187f9d883100)

![image](https://github.com/laravel/nova-issues/assets/34523222/97424321-9482-41eb-8f92-ee809d54ab7e)

**Comment by crynobone** [comment]
Can you share the content of your `composer.json`.

**Comment by patrix152** [comment]
![image](https://github.com/laravel/nova-issues/assets/34523222/a019416b-6bc4-4917-b758-999346c2330e)
@crynobone please look

**Comment by davidhemphill** [comment]
You're most likely doing database queries on every page load. You should be sure to only hit the database when needed. There's nothing else that would cause slowness on the PHP side.

Without seeing the code for the components, we aren't really able to debug performance issues.
