### ISSUE TITLE
Making a nova card made language strings stop working.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [laravel/nova-issues#5869]
- Laravel Version: 9
- Nova Version: 4.27.12
- PHP Version: 8.1.22
- Database Driver & Version: Postgresql
- Operating System and Version: Windows 10 with Ubuntu running in WSL2.
- Browser type and version: Chrome, latest.

### Description:
When I made a new card last night following the documentation, it published lang files into the resources/lang directory.
But the path should actually be lang in the root of the project.

This made all my existing translations and validations stop working.

I have en as the only language in my project.
Renaming the resources/lang folder to something else made the problem go away.

I was following nova docs for Defining cards, I use sail.
https://nova.laravel.com/docs/customization/cards.html#accessing-card-options

```
sail artisan nova:card acme/analytics
```

This prompted a composer install and asked for my license (as it was not persisted within my docker) I entered the details and it updated, but after this I noticed the translation strings were showing the key name like "validation.required" "validation.min" etc.

**Comment by LiamKarlMitchell** [comment]
Actually sorry it may have been this package: https://github.com/dniccum/nova-documentation/blob/master/src/ToolServiceProvider.php#L72C1-L74C20
I can see in my git log that both adding this package, and making the new card added/updated files in resources/lang.

**Comment by crynobone** [comment]
`nova:card` command doesn't contain anything related to language files.
