### ISSUE TITLE
BelongsTo field resets after changing value when depends on other field

### ISSUE THREAD

**Issue by kusab85** [laravel/nova-issues#5872]
- Laravel Version:10.22.0
- Nova Version: 4.27.12
- PHP Version: 8.2.4
- Database Driver & Version: SQL lite
- Operating System and Version: Windows 10 22H2
- Browser type and version: FF, Chrome
- Reproduction Repository: https://github.com/kusab85/TestApp/tree/BelongsTo-resets-when-dependsOn-other-field

### Description:

Value of BelongsTo field resets to its initial value when dependsOn other field.

```php
/**
 * App/Nova/Post.php 
 */

    public function fields(NovaRequest $request)
    {
        return [
            // [...]
            BelongsTo::make('User')
                ->dependsOn(
                    ['created_at'],
                    function (BelongsTo $field, NovaRequest $request, FormData $formData) {
                        $field->help(
                            '$formData = '.var_export($formData->getAttributes(), true)."</br>\n".
                            '$field->value = '.var_export($field->value, true)
                        );
                    }
                ),
           // [...]
        ];
    }
```

1. Initial state of form (creating new post)
![obraz](https://github.com/laravel/nova-issues/assets/53086618/0507eaa7-8f28-4489-a793-cab06e4fc8b8)

2. Selecting a user
![obraz](https://github.com/laravel/nova-issues/assets/53086618/1a42238a-5ce2-4b1e-a315-2fee096b67f9)

3. Setting creation date
![obraz](https://github.com/laravel/nova-issues/assets/53086618/c20983cc-cdde-4b1b-ad69-f5e464b2cb57)

4. Form state after creation date setting
![obraz](https://github.com/laravel/nova-issues/assets/53086618/fe1aae2c-d5e5-4cbb-aa08-271ea2c715e2)

### Detailed steps to reproduce the issue on a fresh Nova installation:
Check reproduction repository.

**Comment by crynobone** [comment]
You shouldn't use `$field->value` as we need to determine whether it is undefined or null from `dependsOn`. You should be able to get the current value from `$formData`.

**Comment by kusab85** [comment]
So, if I stop reading ```$field->value``` on server side the form field will stop resetting on client side? That's quite inobvious behavior ;-)

**Comment by crynobone** [comment]
https://github.com/laravel/nova-dusk-suite/blob/10.4/tests/Browser/DependentBelongsToFieldTest.php#L112-L155

This this in Nova repository hasn't failed yet, which should have if what you claimed did happened.

**Comment by kusab85** [comment]
So @crynobone, please tell me if I'm misreading the ```test_it_reset_the_field_value``` test entirely.

**The expected behavior** of dependent ```BelongsTo``` field **is to reset** to its original value _(null on creating)_ as soon as field on which it depends on changes its value?
