### ISSUE TITLE
Overflowing Select Input causing issues

### ISSUE THREAD

**Issue by MLDMoritz** [laravel/nova-issues#5874]
- Laravel Version: 10
- Nova Version: current

### Description:

This Select Input is cut off due to overflow-hidden in the form.

![image](https://github.com/laravel/nova-issues/assets/46711821/b7d8d92d-fad2-4c37-8197-7c97e7799af3)

Removing `overflow-hidden` from `bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden space-y-6` fixes this issue:

![image](https://github.com/laravel/nova-issues/assets/46711821/2d526256-21d3-4c0c-9b1a-e4bed34bd7b1)

### Detailed steps to reproduce the issue on a fresh Nova installation:

Create an action with many Select options.

### Quick Fix
Custom admin.css
```css
.modal form {
    overflow: visible;
}
```

**Comment by Perzonallica** [comment]
I can confirm, this is still an issue on version `4.29.5`

![overflowIssue](https://github.com/laravel/nova-issues/assets/3707338/7772b693-1458-4de9-af91-d459c8efd0cd)

**Comment by dmason30** [comment]
Yep, running into this too with a custom field, the `overflow-hidden` on the card component means the full dropdown gets cut off at the bottom of the card. Only alternative would to be render it outside the card similar to popovers but this would not be preferred.

<img width="571" alt="image" src="https://github.com/laravel/nova-issues/assets/20278756/e59ba86a-52bd-4722-bcce-caecbb78cf4e">

**Comment by davidhemphill** [comment]
We have fixed the overflow issue by teleporting the search results to the body. Upgrading Nova should fix this in Nova's fields.
