### ISSUE TITLE
3 dots have dissapeared for Action flyout on Nova resources

### ISSUE THREAD

**Issue by HeadStudios** [laravel/nova-issues#5876]
- Laravel Version: 9
- Nova Version: 4.25.1
- PHP Version: 8.2
- Database Driver & Version: MySQL
- Operating System and Version: Macbook
- Browser type and version: Chrome latest
- Reproduction Repository: https://github.com/HeadStudios/novaissue-5456-nonova
- 
### Description:
The 3 dots on my resource detail pages to select actions attached to resources have dissapared.

Video for context: https://share.getcloudapp.com/geu18lK5

### Detailed steps to reproduce the issue on a fresh Nova installation:

Just setup the install and the 3 dots will not show

**Comment by crynobone** [comment]
Someone on Discord mentioned this is caused by         `lednerb/nova-action-button-selectors` package. We have tested this before and unable to replicate with vanilla Laravel Nova

**Comment by HeadStudios** [comment]
THank you for the quick response. And it does make sense that this would be disabled by the plugin if inline buttons would be created instead. Chrs
