### ISSUE TITLE
Unable to save with empty datetime fields

### ISSUE THREAD

**Issue by Navi2016** [laravel/nova-issues#588]
Have a few DateTime fields in my model, but they are nullable so not required to be filled in.

When trying to save the form in Nova, it will error saying: 'Data is missing'. It wants you to select a date even though it should not be required.

v1.0.16

**Comment by davidhemphill** [comment]
We are unable to debug your issue without a reproducible code example.

**Comment by orrd** [comment]
I found that this "Data is missing" error can happen if you don't have the "Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull" middleware enabled.  

You have to add it to your Kernel.php's $middleware list.  But if you prefer not to use that middleware for my own code, you can instead add it to your $routeMiddleware (give it whatever name you want), and then add that route middleware to your config/nova.php's 'middleware' list.

**Comment by orrd** [comment]
It should work if you add `->nullable()` to the field in the Nova field definition.  I believe `nullable()` was added in Nova 2.x, so you may need the newer version of Nova.
