### ISSUE TITLE
Fields' show() or hide() are not working

### ISSUE THREAD

**Issue by eapacheco** [laravel/nova-issues#5888]
- Laravel Version: 10.23.0
- Nova Version: 2.25.1
- PHP Version: 8.2.6
- Database Driver & Version: Postgres 15.3
- Operating System and Version: Mac OS 13.5.2 (22G91)
- Browser type and version: Arc 1.7.0 (Chromium Engine Version 116.0.5845.179)

### Description:
- `show()` and `hide()` are not working on some Fields
- The example below will be on Text fields, but I've had the same result with many fields.

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Fresh Laravel
- Fresh Nova
- On `App\Nova\User::fields`, add `->hide()` to Name
- On `App\Nova\User::fields`, add `->onlyOnDetail()` then `->show()` to Email
- Open User resource and notice: a) Name is still visible; b) Email is not displayed on Index

All changes:
![image](https://github.com/laravel/nova-issues/assets/18501540/f3d7783b-756a-48aa-85b4-c66498f3923a)

Result on browser (dark mode):
![image](https://github.com/laravel/nova-issues/assets/18501540/b0abe28e-5b22-4a83-81cf-ad73638cec0e)

**Comment by crynobone** [comment]
Hide and Show method should only be used with Dependent Field feature.
