### ISSUE TITLE
Nova allows skipping 2FA

### ISSUE THREAD

**Issue by dwightwatson** [laravel/nova-issues#5889]
- Laravel Version: 10.23.0
- Nova Version: 4.27.12
- PHP Version: 8.2.10
- Database Driver & Version: N/A
- Operating System and Version: N/A
- Browser type and version: N/A

### Description:

In previous discussions around 2FA support in Nova (#4214, #4708) it has been suggested to use `config('nova.routes.login')` to override the login path and force the user through the non-Nova login flow (like Fortify) which would enforce 2FA if required. However, this simply prevents the login form from being displayed.

The actual POST endpoint under the hood remains. A malicious user with admin credentials could still POST to `/nova/login` and authenticate without 2FA. I think this a potential security issue.

Perhaps there should be a configuration option within Nova to totally disable all the auth-related routes (login, password reset, logout)?

In the meantime, you can stub out the route to prevent it from being accessed.

```php
Route::post('nova/login', fn () => abort(403));
```

### Detailed steps to reproduce the issue on a fresh Nova installation:

* Create Laravel app using Jetstream
* Register user and enable 2FA
* Logout
* Visit Nova and successfully login without 2FA

If you stub out the login path using `config(['nova.routes.login' => '/login'])` then you can still do a `POST /nova/login` with credentials and authenticate.

**Comment by crynobone** [comment]
You should be able to disable Nova's authentication routes:

![CleanShot 2023-09-15 at 19 34 40](https://github.com/laravel/nova-issues/assets/172966/1bfdbe07-31a8-4afb-b775-283f7a36e798)

**Comment by crynobone** [comment]
@PNardman Please submit a new bug report with full reproduction repository.
