### ISSUE TITLE
Allow enabling support for trend metric helpers for other database drivers.

### ISSUE THREAD

**Issue by danmatthews** [laravel/nova-issues#5894]
- Laravel Version: 10.20.0
- Nova Version: 4.27.12
- PHP Version: 8.2.10
- Database Driver & Version: Singlestore, 1.5.1
- Operating System and Version: Mac OS X Ventura 13.2.1
- Browser type and version: Arc Browser, latest.
- Reproduction Repository: -

### Description:

We use [Singlestore](https://singlestore.com) as our database, so we get the following message when logging into our nova dashboard now:

<img width="565" alt="CleanShot 2023-09-20 at 07 07 23@2x" src="https://github.com/laravel/nova-issues/assets/149426/70fea2ba-15de-4f9f-baee-da4f43370a4a">

### Detailed steps to reproduce the issue on a fresh Nova installation:

- Create singlestore account
- Get license key
- Install their (https://github.com/singlestore-labs/singlestoredb-dev-image) dev db image with docker.
- Install Laravel
- Install Nova
- Create a trend metric helper that works with MySQL.
- Install the singlestore laravel driver (https://github.com/singlestore-labs/singlestoredb-laravel-driver)
- Update your `.env` file settings to use singlestore.
- Get the error above.

### Suggestion:

Either, add Singlestore to the whitelist, or:

Allow manually adding to the list of databases that are supported by pushing using a facade or static method in `AppServiceProvider` or `NovaServiceProvider`:

```php
// Obviously, if they don't work on this type of DB, it's the user's problem, not yours.
Nova::enableTrendMetricHelpersForCustomDatabaseConnection("singlestore");
```

This also helps people who might be moving to other more novel DB systems or creating their own custom named drivers to support features MySQL might not out of the box.

Happy to contribute a PR if you want to add me to the repo + remove me when it's done. 👍🏻

**Comment by crynobone** [comment]
You can do this if `singlestore` support all date related functions used in `MySqlTrendDateExpression`

```php

use Laravel\Nova\Metrics\MySqlTrendDateExpression;
use Laravel\Nova\Metrics\TrendDateExpressionFactory;

TrendDateExpressionFactory::macro('mysql', function ($query, $column, $unit, $timezone) {
    return new MySqlTrendDateExpression($query, $column, $unit, 'UTC');
});
```

**Comment by danmatthews** [comment]
@crynobone amazing thank you, will take a look at this today.

**Comment by danmatthews** [comment]
Worked perfectly, thanks!
