### ISSUE TITLE
HasOne doesn't allow dependsOn

### ISSUE THREAD

**Issue by LorenzoSapora** [laravel/nova-issues#5896]
`HasOne` doesn't allow usage of `dependsOn`.

**Comment by crynobone** [comment]
This is as expected: https://nova.laravel.com/docs/resources/fields.html#dependent-fields

**Comment by LorenzoSapora** [comment]
Sure, I checked the docs before posting, but _why_? How is `HasOne` different from `HasMany`? I'm just trying to show/hide the hasOne based on a Boolean, seems wasteful to pull a whole package just for a show/hide
