### ISSUE TITLE
Create a child-relationship entry from the parent entry (User and usersettings)

### ISSUE THREAD

**Issue by julianpoma** [laravel/nova-issues#59]
For example, a `UserModel `and `UserSettingModel` in a `OneToOne` relationship. It would be nice to setup the UserSettings when I am creating a new User. (this could apply also when editing).

Sorry for the bad english. I hope its clear.

**Comment by devmsh** [comment]
#79 same request here

**Comment by SamerDiab** [comment]
Check this 
https://novapackages.com/packages/shivanshrajpoot/nova-create-or-add
and 
https://novapackages.com/packages/yassi/nova-nested-form
