### ISSUE TITLE
white page on laravel nova/login

### ISSUE THREAD

**Issue by kamhawy4** [laravel/nova-issues#5902]
- Laravel Version: 9.19
- Nova Version: 4
- PHP Version: 8.2.10
- Operating System and Version: Mac
- 
### Description:

when I was working locally everything was fine with Nova. but when moved to production I have a problem when I open nova/login I have just a white page and in the console there this error createNovaApp is not defined I tried every Solution on the internet.

there anyone have a Solution for this?

<img width="1440" alt="Screenshot 2023-09-22 at 5 02 51 PM" src="https://github.com/laravel/nova-issues/assets/25951080/09309829-ae3c-4f08-9c0e-2de7f71d1b8a">

**Comment by crynobone** [comment]
Have you publish Nova's asset?

**Comment by kamhawy4** [comment]
yes
<img width="1440" alt="image" src="https://github.com/laravel/nova-issues/assets/25951080/0934b998-79f2-4038-842e-b689af24e365">

**Comment by kamhawy4** [comment]
yes 

<img width="1440" alt="image" src="https://github.com/laravel/nova-issues/assets/25951080/8e6534b4-baa8-4254-a98f-275cf8483e79">

**Comment by crynobone** [comment]
using `sudo` can cause file permission issue if web server being accessed using different user/user group privilege. Might need to check that.

**Comment by kamhawy4** [comment]
OK. now I run it without sudo .
and I run  sudo chmod -R 777 html for all project 
and same issue

**Comment by majdcodes** [comment]
make sure your APP_URL in .env in you ip address

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.

**Comment by gnanakeethan** [comment]
@crynobone I just had a fresh install of Laravel + Nova and facing same issue.

**Comment by crynobone** [comment]
@gnanakeethan feel free to submit reproductions repository as requested above.

**Comment by gnanakeethan** [comment]
@crynobone Seems like an issue is not reproducible. I happened to have brand config setup. Then when I removed it, the app started working. Then added it again, it is working. 

Attempted on a fresh install and followed steps and it is working. 

Is there anything related to caching some configuration in the user level?

**Comment by crynobone** [comment]
It unclear until we can have a reproductible setup to debug.

**Comment by gnanakeethan** [comment]
https://github.com/gnanakeethan/nova-4-login-issue/blob/main/config/nova.php

<img width="1020" alt="Screenshot 2023-10-05 at 10 24 04" src="https://github.com/laravel/nova-issues/assets/2353181/8534f0c9-a5a7-4ac6-aaf1-a14f37054774">


I added a PNG on the public/images folder and referenced that using public_path function.

**Comment by gnanakeethan** [comment]
<img width="473" alt="Screenshot 2023-10-05 at 10 25 42" src="https://github.com/laravel/nova-issues/assets/2353181/df29f2c7-7460-458a-8253-2ae446e4cd42">
This also results in the same scenario. 

Blank screen empty of Nova config

**Comment by gnanakeethan** [comment]
I think I missed the note, that the logo should be SVG

**Comment by crynobone** [comment]
Nova only supports SVG file as logo.
