### ISSUE TITLE
->dependsOn() is returning string not array of values from Multiselect

### ISSUE THREAD

**Issue by puremana** [laravel/nova-issues#5905]
- Laravel Version: 10.23.1
- Nova Version: 4.27.1
- PHP Version: 8.2
- Database Driver & Version: MySQL 5.7
- Operating System and Version: Ubuntu 20.04
- Browser type and version: Chrome version 117
- Reproduction Repository: 

### Description:

I am using the [outl1ne/nova-multiselect-field](https://github.com/outl1ne/nova-multiselect-field) package, but I do not think the issue is with the package.

Code
```php
    Multiselect::make('List Config 1', 'input1')
        ->options(ListConfig::where('label', 'LIKE', '%config%')->pluck(
            'label',
            'key'
        )->toArray())->rules(sprintf('exists:%s,key', $listConfig))
        ->help(
            'List config 1'
        ),
    Multiselect::make('List Config 2', 'input2')
        ->options(ListConfig::where('label', 'NOT LIKE', '%config%')->pluck(
            'label',
            'key'
        )->toArray())->rules(sprintf('exists:%s,key', $listConfig))
        ->help(
            'List config 2'
        ),
    Hidden::make('Combined Lists', 'combined')->dependsOn(
        ['input1', 'input2'],
        function (Hidden $field, NovaRequest $request, $formData): void {
            // Use easily editable GUI inputs to create the JSON value for the database
            $combinedLists = [];
            $combinedLists['input1'] = $formData->input1 ?? [];
            $combinedLists['input2'] = $formData->input2 ?? [];
            $field->value = json_encode($combinedLists);
        }
    ),
```

Nova Version 4.22.1 introduced a bug where the value returned for `$formData->input1` and `$formData->input2` are strings, not arrays but only when you save the resource without editing either input1 or input2.

Version 4.22.0 and below work as expected.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Create a nova resource model with code like above which depends on a multiselect input.
Create a new resource of in Nova, selecting some value from the multiselect, save the resource.
Open up that same resource to edit, and save immediately.

Check database to see you have now saved "[1,2,3,4]" instead of [1,2,3,4].

**Comment by crynobone** [comment]
Please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
