### ISSUE TITLE
AssociatableController ignores fields nested in Stack::field

### ISSUE THREAD

**Issue by rderks88** [laravel/nova-issues#5910]
- Laravel Version: 8.83.27
- Nova Version: 4.23.0
- PHP Version: 8.1
- Database Driver & Version:
- Operating System and Version: Linux

### Description:

The AssociatableController does not take into account fields nested within a Stacked field on the index page.
This is a problem when trying to create resources with a belongsTo relation.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Clean installation
Create two entities, of which one has a belongsTo relationship to the other
Add the belongsToField to the fields() method
Add the belongsToField to the fieldsForCreate() method
It now works as expected
Make sure the belongsToField in the fields method gets nested in a Stack-field
Creating the entity does not work like expected anymore (associatable request will 404)

**Comment by rderks88** [comment]
It has to do with this part:
```
$field = $request->newResource()
                  ->**availableFieldsOnIndexOrDetail($request)**
                  ->whereInstanceOf(RelatableField::class)
                  ->findFieldByAttribute($request->field, function () {
                      abort(404);
                  })->applyDependsOn($request);
                    ```

**Comment by crynobone** [comment]
Please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
