### ISSUE TITLE
Cant custom Scout seaches on Nova 4

### ISSUE THREAD

**Issue by huynguyen-twentyci** [laravel/nova-issues#5911]
- Laravel Version: 10.24.0
- Nova Version: 4.27.13
- PHP Version: 8.2.9
- Database Driver & Version: MSSQL 17
- Operating System and Version: macOS 13.5.2
- Browser type and version: Chrome 117.0.5938.92
- Reproduction Repository: https://github.com/###/###

### Description:
I'm using Elasticsearch as project's search engine and i want to custom query on an index search of nova resource. What i did in older version (nova 2) is overiding "initializeQueryUsingScout" function on a resource file. But on Nova 4, i found that, the line $search = ''; on "vendor/laravel/nova/src/Query/Builder.php" might be a reason, then in function "initializeQuery" of "vendor/laravel/nova/src/PerformsQueries.php", i cant overide my desire function, it always hit "empty(trim($search))". Please check, thanks.

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Install laravel, nova, elasticsearch
- Use searchable on a resource
- Try to custom query search on this resource by overiding funtion "initializeQueryUsingScout"

**Comment by crynobone** [comment]
This method is not designed to be overridden that way, to use custom Scout you should only have to set SCOUT_DRIVER and it should work out of the box.
