### ISSUE TITLE
Unable to Delete

### ISSUE THREAD

**Issue by parcle** [laravel/nova-issues#592]
after installing nova on 5.7 create and update work smooth ... but i'm unable to delete a record from dashboard both for a new created Model and standard User

**Comment by davidhemphill** [comment]
We are unable to debug your issue without a reproducible code example.

**Comment by parcle** [comment]
Nova is supposed to work without any code ... i  have followed instruction reported so ..
after installation i have
Create Resource
php artisan nova:resource Post
Added fields definition on resource (via fields array)

After this operation resource are available on my Dashboard , i can create and update but not delete

**Comment by davidhemphill** [comment]
Sorry, but you've provided no code or relevant details about your app which indicate there is an actual issue. If you post your resource/model configuration, a stack trace, or anything else, we might be able to determine if there's an issue. Plenty of folks have done the exact same thing as you and it's working, so we need more details. :-)

**Comment by parcle** [comment]
This is my migration file for
`<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateChatChannelsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('chat_channels', function (Blueprint $table) {
            $table->increments('id');
            $table->timestamps();
            $table->boolean('active')->default(false);
            $table->string('who')->nullable();
            $table->string('how')->nullable();
            $table->string('with')->nullable();
            $table->string('wellcomeMsg')->nullable();
            $table->text('socketURL')->nullable();

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('chat_channels');
    }
}
`
This is my Model 

`<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
 


class ChatChannel extends Model
{


    protected $table = 'chat_channels';





}
`
This is the resource file

`<?php

namespace App\Nova;

use Laravel\Nova\Fields\Boolean;
use Laravel\Nova\Fields\ID;
use Illuminate\Http\Request;
use Laravel\Nova\Http\Requests\NovaRequest;
use Laravel\Nova\Fields\Text;

class ChatChannel extends Resource
{
    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static $model = 'App\ChatChannel';

    /**
     * The single value that should be used to represent the resource when being displayed.
     *
     * @var string
     */
    public static $title = 'id';

    /**
     * The columns that should be searched.
     *
     * @var array
     */
    public static $search = [
        'id',
    ];

    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     *
     *             
     *
     *
     */
    public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),

            Boolean::make('active')
                ->sortable(),
                   Text::make('who')
                ->sortable(),
            Text::make('how')
                ->sortable(),
            Text::make('with')
                ->sortable(),
            Text::make('wellcomeMsg')
                ->sortable(),
            Text::make('socketURL')
                ->sortable(),




        ];
    }

    /**
     * Get the cards available for the request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function cards(Request $request)
    {
        return [];
    }

    /**
     * Get the filters available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function filters(Request $request)
    {
        return [];
    }

    /**
     * Get the lenses available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function lenses(Request $request)
    {
        return [];
    }

    /**
     * Get the actions available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function actions(Request $request)
    {
        return [];
    }
}
`
This is the standard Controller 
`<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\ChatChannel;

class ChatChannelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
     

    }

 
}
`

after configuration i have published Nova with artisan and via dashboard im able to create and update record but NOT delete them. No log error on php-fpm backend.

**Comment by moth** [comment]
Got it.

In my apache config;

```
    <LimitExcept GET HEAD POST>
        Require all denied
    </LimitExcept>
```

Changed to

```
    <LimitExcept GET HEAD POST DELETE>
        Require all denied
    </LimitExcept>
```

**Comment by kkoppenhaver** [comment]
I had the same issue and was able to resolve it by making sure I was updated to the latest version of Nova and running `php artisan nova:publish`.
