### ISSUE TITLE
403 Error in Production Environment

### ISSUE THREAD

**Issue by mhmadskarsh98** [laravel/nova-issues#5920]
- Laravel Version: ^9.19
- Nova Version: 4.27
- PHP Version: 8.1
- Database Driver & Version: mysql 8.0
-Laravel vapor

### Description:

I am currently facing a problem where I receive a 403 error when attempting to use the Laravel Nova application in a production environment. I want to emphasize that my subscription is active, and my license is also active. To provide you with more information, I have already set the NOVA_LICENSE_KEY variable in my environment file as follows:

NOVA_LICENSE_KEY="***********Ku7Asw9wx***************************"

However, despite having an active license and setting the NOVA_LICENSE_KEY, I am still encountering this issue.

##Note : 
in local environment everything is good and run 

##
this is a gate on NovaProvider
    protected function gate()
    {
        Gate::define('viewNova', function ($user) {
            return true;
        });
    }

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by mhmadskarsh98** [comment]
Certainly, here are the detailed steps to reproduce the issue on a fresh Nova installation

1- Install Nova Package: composer require laravel/nova
2- Add Nova License to .env: NOVA_LICENCE=*****
3- Check Nova License : php artisan nova:check-license , output command "Your license key is valid and correctly configured! Thank you for being a Nova customer. 🚀"
4- on non-production env run successfully
5- Gate Function:
![image](https://github.com/laravel/nova-issues/assets/52927549/a22d156b-66a5-4e9d-a4f9-f73fe4cef3c2)

**Comment by crynobone** [comment]
Unable to replicate based on exact step above: https://github.com/nova-issues/issue-5920/commit/e8fc2c78c23ed8047c3a38a16694dec07f0fc9de

**Comment by r0bbie** [comment]
Odd, I'm seeing this exact issue. Been testing Nova locally for a while, no issues.

On server, if I set APP_ENV to 'local' Nova loads fine, if anything else I get a 403. NOVA_LICENSE_KEY is set, and "Production URL" in my Nova license panel. Strange!
