### ISSUE TITLE
MenuSection Component is Hard-Coded in Serialization

### ISSUE THREAD

**Issue by tylernathanreed** [laravel/nova-issues#5922]
- Laravel Version: 10.23.1
- Nova Version: 4.27.12
- PHP Version: 8.2.10
- Database Driver & Version: Postgres 14.9
- Operating System and Version: Windows 11
- Browser type and version: Chrome 117

### Description:

When creating a child class of the `MenuSection` class, overriding the `$component` property is not sufficient to change the `component` attribute in the JSON payload, as the `jsonSerialize` method has it hard-coded.

From `MenuSection`:

```php
/**
 * Prepare the menu for JSON serialization.
 *
 * @return array<string, mixed>
 */
public function jsonSerialize(): array
{
    /* ... */

    return [
        /* ... */
        'component' => 'menu-section',
        /* ... */
    ];
}
```

The code should be using `$this->component` instead:

```php
public function jsonSerialize(): array
{
    /* ... */

    return [
        /* ... */
        'component' => $this->component,
        /* ... */
    ];
}
```

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
