### ISSUE TITLE
BelongsToMany non-pivot action shouldn't use `PivotId`

### ISSUE THREAD

**Issue by Peterragheb** [laravel/nova-issues#5923]
- Laravel Version: 10.25.1
- Nova Version: 4.27.13
- PHP Version: 8.1.23
- Database Driver & Version: postgres
- Operating System and Version: macOS 13.5.2
- Browser type and version: Chrome 117.0.5938.132
- Reproduction Repository: 
### Description:
Selecting resources to run actions on in BelongsToMany field passes the ID field's pivotValue regardless if it's a pivot action or not. 

I think this is due to that now in the `IndexConcerns.js` file since `selectedResourceIds` returns the `pivotValue` on the ID field.
The request's `toSelectedResourceQuery` selects from related table with the pivot ids which returns 0 records and causes the action to return "Sorry! You are not authorized to perform this action." 

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Create a belongs to many relationship and add action to the related resource (not a pivot action)
- Try running the action

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by Peterragheb** [comment]
Well I found the root cause of the issue. It's because I'm chaining `->withPivot(['id'])` on the relationship definition. 
In my opinion the pivot id shouldn't take priority over the related model Id when it's not a pivot action. However I'm not sure you consider this a bug and that you'd like to handle this case. 

In case you want to reproduce this issue: [here's a repo](https://github.com/Peterragheb/test-nova-belongs-to-many-action-issue)
- run `php artisan db:seed` (this will create all the needed resources)
- Open the Project resource detail page
- select the user and try to run the "Test Action"

**Comment by crynobone** [comment]
Pivot ID should have priority when it is available, since we can target the specific IDs instead of just relying on related IDs.

**Comment by Grafikart** [comment]
> Pivot ID should have priority when it is available, since we can target the specific IDs instead of just relying on related IDs.

The behaviour changed between 4.26 and 4.27 so it break apps on a minor change (which is unexpected). 
In my opinion PivotIDs should be sent in another field and not mixed with "id".

**Comment by crynobone** [comment]
> In my opinion PivotIDs should be sent in another field and not mixed with "id".

This would break other applications as well. Pivot ID should always have priority when it is available.

**Comment by rikless** [comment]
> This would break other applications as well. Pivot ID should always have priority when it is available.

No because it was not the behavior until this release. What breaks applications now, is this unexpected and undocumented change.

**Comment by crynobone** [comment]
Sorry but this is the expected behaviour, we probably missing some dusk tests to cover this usage causing the issue to occur.

If someone willing to create a reproducing repository to showcase what need to change I would be willing to take a look.

**Comment by Grafikart** [comment]
A reproductable repo was already given in [previous answer](https://github.com/Peterragheb/test-nova-belongs-to-many-action-issue).

If this is the intended behaviour it means Actions are broken on every relation using id as pivot, with a confusing error "you are not authorized..." and no way to fix this issue since the query created inside the action does not handle this correctly (it expects id to be used on the main Model, not the Pivot). The  PHP code from `toSelectedResourceQuery()` does not reflect this intended behaviour. Then a fix could come from an edit to `toSelectedResourceQuery()`

**Comment by rikless** [comment]
@crynobone any feedback ?

**Comment by rikless** [comment]
@crynobone just a followup ?

**Comment by crynobone** [comment]
Still under review. Will update the issue once a PR is in place.

**Comment by Peterragheb** [comment]
Yes all good now. Thanks!
