### ISSUE TITLE
Disable BelongsTo href/link if the user doesn't have access to view the target resource

### ISSUE THREAD

**Issue by m2de** [laravel/nova-issues#593]
Whenever I use a `BelongsTo` field, on the detail view this becomes a clickable link (Area in particular in this example)

![screen shot 2018-09-18 at 15 59 33](https://user-images.githubusercontent.com/17720020/45696628-e4cf2980-bb5b-11e8-8bbe-dce37cdd5c49.png)

While the user has permission to see the value of this entry, they do not have permissions to `view` the actual `Area` resource. So clicking the link will result in a 403 error. Nova should not make this clickable unless the user has permission to view the target resource.

Alternatively one solutions would be to just provide an option on the `BelongsTo` field type to disable the click-through?

Many thanks.

**Comment by dillingham** [comment]
Ah yes totally need this. Also ->removeLink() would be handy and perform the same behavior but for scenarios where we don’t want it linked.

**Comment by dkulyk** [comment]
PR was sent to upstream. 
Added cannotView() method and view permission checking.
```php
class GroupPolicy
{
    public function view($user, $group)
    {
        return $group->id !== 2;
    }
}
```
![image](https://user-images.githubusercontent.com/370042/50426021-8917e900-088c-11e9-8ca6-e14fa3e4732c.png)

**Comment by dillingham** [comment]
@dkulyk that’s awesome. May be assumed that view would hide it altogether vs just the link. Maybe a flag on the field? 

#### hides completely view policy 
BelongsTo::make()

#### hides completely view policy 
BelongsTo::make()->removeLink()

#### calls removeLink when policy view
BelongsTo::make()->staticWhenPolicy()

**Comment by dkulyk** [comment]
`BelongsTo::make()` - will hide link if policy forbidden.
if you add `->cannotView()` link will be hidden in any way.
`->cannotView(false)` will set default behavior

Method name may be changed. If @davidhemphill will says about it.

**Comment by dillingham** [comment]
This would also close this https://github.com/laravel/nova-issues/issues/960

**Comment by dkulyk** [comment]
> This would also close this #960
I don't think so.

**Comment by dillingham** [comment]
If this doesn't remove link when unauthorized but keeps the text in place then I am totally misunderstanding this issue / feature proposal

**Comment by dkulyk** [comment]
if you don't have viewAny permission relations will hid in resource views

**Comment by davileichsenring** [comment]
This method is still working? I am using 3.1 and having issue. In my policies only admin can view/add/edit,remove but it shows the link to view. I tried to use ->cannotView() but it is not a allowed method.

**Comment by dkulyk** [comment]
It's not working yet. Maybe in the next(>1.3.2) releases.

**Comment by aaronahearne** [comment]
Yet another Nova issue closed for no apparent reason.

The docs arent even correct, has anyone tried to create custom resource tools? The docs are completely wrong.

Not the sort of thing you expect from a paid product.

**Comment by gpressutto5** [comment]
Why was this issue closed? It's pretty useful, and I have found no workaround for this.

**Comment by sabid** [comment]
#### Linking to resource

 When relationship unauthorized to view, link will not displayed on Details or Index views. Also you can disable link mannualy:

 ```php
BelongsTo::make('User')->viewable(false)
```

**Comment by dillingham** [comment]
@sabid @dkulyk, thanks! wish it wasnt still bold.. looks like a link

**Comment by gpressutto5** [comment]
@sabid @dillingham Are you guys sure it's working? It's not working at all here. The text keeps blue and clickable. Using Laravel 5.8 and Nova 2.0.1.
![image](https://user-images.githubusercontent.com/12385501/56327110-4043b300-614f-11e9-84ee-fb791540fa11.png)
![image](https://user-images.githubusercontent.com/12385501/56327130-5cdfeb00-614f-11e9-8d5b-162a185142d7.png)
![image](https://user-images.githubusercontent.com/12385501/56327161-826cf480-614f-11e9-8426-f65bbbe21457.png)

**Comment by dillingham** [comment]
@m2de try `php artisan nova:publish`
