### ISSUE TITLE
Progress bar disappears before all requests finish

### ISSUE THREAD

**Issue by ragingdave** [laravel/nova-issues#594]
The progress bar on resource indexes that take longer than a second (give or take) are not under the progress bar loading indicator. This means that for those longer resources, the progress bar is gone before the request finishes and as a user, especially on paginated content, I assume it's already loaded when it actually hasn't yet.
I don't think this can really be considered an edge case as I only have upwards of 50k records for this resource.

**Comment by davidhemphill** [comment]
The progress bar isn't for the loading of resources. It's for the loading of the component. :-)
