### ISSUE TITLE
View policy does not stop row being displayed

### ISSUE THREAD

**Issue by unlikenesses** [laravel/nova-issues#595]
Nova 1.0.15. I have a list of Users. I want all users to be displayed in this table except users with a `role` of `foo`. So I create a `UserPolicy`:

    public function view(User $user, User $model)
    {
        return $model->role !== 'foo';
    }

This does indeed stop me from clicking through to view users of type `foo`, but they still appear in the list. I would expect them to be invisible in the list. Is there any way to do this?

**Comment by m2de** [comment]
You should be able to achieve what you need using the [Index Filter query](https://nova.laravel.com/docs/1.0/resources/authorization.html#index-filtering).

```php
    // app\Nova\User.php

    public static function indexQuery(NovaRequest $request, $query)
    {
        return $query->where('role', '!==', 'foo');
    }
```

**Comment by davidhemphill** [comment]
@unlikenesses The answer given by @m2de's is the correct one. :-)

**Comment by unlikenesses** [comment]
I used @m2de's code exactly, and the result was that neither of my users (one of role `foo`, the other of role `bar`) was displayed.

**Comment by davidhemphill** [comment]
@m2de's answer uses a `role` column on the user. You probably want to use a `whereHas` type of clause to achieve what you're looking for.

**Comment by unlikenesses** [comment]
I'll look into it, thanks.
