### ISSUE TITLE
JSON fields doesn't work

### ISSUE THREAD

**Issue by dkulyk** [laravel/nova-issues#596]
Nova 1.017

If use 'field->option' attributes Field doesn't resolve value.

[Reproducible code example](https://github.com/dkulyk/nova-issues/tree/json_fields)

**Comment by taylorotwell** [comment]
Can you paste a small code example I can copy and paste from this issue directly?

**Comment by taylorotwell** [comment]
Fixed in upcoming release.

**Comment by dkulyk** [comment]
I'll do this in future issues.
