### ISSUE TITLE
Slug field doesn't take into account readonly()

### ISSUE THREAD

**Issue by lptn** [laravel/nova-issues#5973]
- Laravel Version:v10.25.1
- Nova Version: v4.27.14 

### Description:

"Customize" button still available even if the firld is readonly:
<img width="236" alt="image" src="https://github.com/laravel/nova-issues/assets/5278175/553efdb1-9d22-4b0e-8597-f3d10bd8a469">

### Detailed steps to reproduce the issue on a fresh Nova installation:
```php
            Text::make('Title', 'title'),
            Slug::make('Slug', 'slug')
                ->from('Title')
                ->readonly(true),
```

**Comment by crynobone** [comment]
Sorry, we don't support this feature to be used this way. `readonly()` is only supposed to be added on Update form (automatically).
