### ISSUE TITLE
Searchable BelongsTo unable to close dropdown

### ISSUE THREAD

**Issue by TNDJX** [laravel/nova-issues#5983]
- Laravel Version: 10.13.5
- Nova Version: 4.27.14
- Reproduction Repository: https://github.com/TNDJX/nova-issue-5605

### Description:
If we have a lot of fields in the create/update view and scrolling is required, the searchable fields' backdrop position is wrong and we can't close the dropdown by clicking outside of the field

### Detailed steps to reproduce the issue on a fresh Nova installation:

- Clone the repo above and use Sail to run a project
- run migrations and db:seed
- Navigate to /resources/bookings/new
- There is many copy pasted user fields, at the beginning we can open drop-down by click on field and close it by clicking outside, but as we start to scroll down backdrop position gets worse and we are unable to close drop-down

https://github.com/laravel/nova-issues/assets/57906002/077fb382-4f2e-4975-817e-77041eb48464

**Comment by TNDJX** [comment]
@crynobone any update on this issue its quite annoying I can see many releases happened but this is still not fixed or is it?

**Comment by davidhemphill** [comment]
I believe this issue should be fixed. Please post a new issue if the issue persists.

**Comment by davidhemphill** [comment]
Fixed in 4.32.0
