### ISSUE TITLE
Help text doesn't show on form with MorphOne field

### ISSUE THREAD

**Issue by Caminyx** [laravel/nova-issues#5989]
- Laravel Version: 10.29.0
- Nova Version: 4.28.0
- PHP Version: 8.2

### Description:
Help text doesn't show on the resource edit form (or anywhere else).

### Detailed steps to reproduce the issue on a fresh Nova installation:
Add a MorphOne field to a resource with a help text. Go to the resource edit form and see that the help text is missing.

Sample : `MorphOne::make('Picture', 'picture')->help('width 1000px, height 800px'),`

**Comment by crynobone** [comment]
Unable to replicate the issue.

```php
MorphOne::make('Photo')->help('Company photo'),
```

![CleanShot 2023-10-30 at 08 24 55](https://github.com/laravel/nova-issues/assets/172966/3fe05009-2254-4198-aea2-78f3d4c10b8d)
