### ISSUE TITLE
Display correct values in metrics

### ISSUE THREAD

**Issue by willmkt** [laravel/nova-issues#599]
When using value metrics it shows the value in US format, i made a custom query to show the values in BRL format.

    public function calculate(Request $request)
    {
        $value= DB::table('bills_pay')
                ->whereDate('due_date', Carbon::today())
                ->sum(DB::raw('(value/100)'));

       return $this->result('R$ ' . number_format($value, 2, ',', '.'));
   }

but if the value is below the 1.000 i get the american formata, and if greaten than 1000 i get my format.

**Comment by taylorotwell** [comment]
I think you can return whatever values you want manually?
