### ISSUE TITLE
Impersonation menu seems to be missing

### ISSUE THREAD

**Issue by guybrun** [laravel/nova-issues#5994]
- Laravel Version: 10.14.1
- Nova Version: 4.28.0
- PHP Version: 8.1.21
- Database Driver & Version: Server version: 10.5.19-MariaDB-0+deb11u2-log - Debian 11
- Operating System and Version:  Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux 
- Browser type and version: Chrome Version 118.0.5993.89 (Official Build) (64-bit)

### Description:
When upgrading from Nova 4.27.14 to Nova 4.28.0, the impersonation menu disappears.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Impersonation menu Disappeared  when upgrading from Nova 4.27.14 to Nova 4.28.0
![nova-4 27 14](https://github.com/laravel/nova-issues/assets/11294565/a45067c0-7aca-4189-b130-57f086d87910)
![nova-4 28 0](https://github.com/laravel/nova-issues/assets/11294565/157e1d3d-6501-42c9-8ee5-739b45e9cc68)

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

Our Nova repository already has this usage tested using Dusk test and haven't failed yet on the latest version: https://github.com/laravel/nova-dusk-suite/blob/10.4/tests/Browser/ImpersonatesUserTest.php

**Comment by guybrun** [comment]
This issue seemed to be related to the third party package  "lednerb/nova-action-button-selectors": "^2.0"
The uninstalling of this package removed the issue with the menu.
