### ISSUE TITLE
The actions are not shown on table metric.

### ISSUE THREAD

**Issue by thisiskaden** [laravel/nova-issues#5997]
- Laravel Version: 10.29.0
- Nova Version: 4.28.0
- Operating System and Version: mac 14.0(23A344)
- Browser type and version: chrome 118.0.5993.117

### Description:
The actions are not shown on table metric after upgrade to v4.28.0 from v4.27.14

### Detailed steps to reproduce the issue on a fresh Nova installation:

![1](https://github.com/laravel/nova-issues/assets/1886022/22a6bf9b-89a5-4078-9474-6aacf085a33c)
![2](https://github.com/laravel/nova-issues/assets/1886022/91b669be-eb51-4172-886b-94a002331cc9)

**Comment by Keko-94** [comment]
Same issue in the Resource table, the onlyInline actions don't show up since the latest release.
