### ISSUE TITLE
BelongsTo relation doesn't change after saving by replicating from the relatable lists.

### ISSUE THREAD

**Issue by sunnydesign** [laravel/nova-issues#5998]
- Laravel Version: `9.52.16`
- Nova Version: `4.28.0`
- PHP Version: `8.1.16`
- Database Driver & Version: `mysql  Ver 8.0.32-0ubuntu0.22.04.2 for Linux on x86_64 ((Ubuntu))`
- Operating System and Version: `Linux 3f4d84d59979 5.15.0-87-generic #97-Ubuntu SMP Mon Oct 2 21:09:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
- Browser type and version: `118.0.2 (64) Mozilla Firefox Snap for Ubuntu`
- Reproduction Repository: https://github.com/sunnydesign/nova/tree/master

### Description:

When we are replicating the `Category` item belonging to the `Building` from the related table with `Categories` (pic. 1) on the `Building` page, we changing the relation in the edit form from original `building_id` to another `building_id` (pic. 2), after saving the related `building_id` is saved as the original (3 pic.). 

pic. 1
![изображение](https://github.com/laravel/nova-issues/assets/36501326/56cf0d32-56d9-4cd9-a286-ff3e8f638deb)

pic. 2
![изображение](https://github.com/laravel/nova-issues/assets/36501326/7be01931-ba64-4e7e-94a0-9af5973e7d51)

pic. 3
![изображение](https://github.com/laravel/nova-issues/assets/36501326/7c4380fa-a38d-4ad6-b210-6ef0c80ab691)

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. We have 2 entities: `Building` and `Category`. `Category` belongs to the `Building`.
2. We setup 2 buildings items (`buildings.id=1`, `buildings.id=2`) and 1 category (`categories.id=1`, `categories.building_id=1`) item belonging to the first building.
3. Press `replicate` button for the first category item on the [building page](http://localhost/nova/resources/buildings/1) in the list of related categories.
4. On the [edit page](http://localhost/nova/resources/categories/1/replicate?viaResource=buildings&viaResourceId=1&viaRelationship=categories) change building from 1 to 2.
5. Press button `Create category`.
6. As result we can see new category belonging to the first building instead of the second one (`categories.id=2`, `categories.building_id=1`).

**Comment by davidhemphill** [comment]
Hey there! I wasn't able to replicate this issue using your repository. The building was changed correctly when replicating. Perhaps something was fixed between the time you posted and when I was able to check, but closing for now since I can't replicate.

**Comment by sunnydesign** [comment]
@davidhemphill  @davidhemphill This issue is still not resolved in the latest version v4.32.11.

There is a gif with reproducing.

![Peek 2023-12-22 11-33](https://github.com/laravel/nova-issues/assets/36501326/4c40bcde-ee72-4616-9190-5b067776cd6f)
