### ISSUE TITLE
Can not use computed values with Heading field

### ISSUE THREAD

**Issue by lptn** [laravel/nova-issues#5999]
- Laravel Version: 10.29.0
- Nova Version: 4.28.0 (Silver Surfer)

Related issue: https://github.com/laravel/nova-issues/issues/2685

### Description:

It's not possible to use computed fields with `Heading` field type. I tried different approaches:
```php
Heading::make('Computed heading (label)', function () {
    return 'Computed heading (value)';
}),

Heading::make('Computed heading (label)', null, function () {
    return 'Computed heading (value)';
}),

Heading::make(function () {
    return 'Computed heading (value)';
}),

Heading::make('Computed heading (label)')->displayUsing(function () {
    return 'Computed heading (value)';
}),


Heading::make('Computed heading (label)')->fillUsing(function () {
    return 'Computed heading (value)';
}),
```

nothing works. The issue is in `\Laravel\Nova\Fields\Heading::__construct`: we need to remove `$this->withMeta(['value' => $name]);` line

Why do I need it: prevent heavy value computing on index page (I need to compute this value for details page only)

**Comment by crynobone** [comment]
The Heading field doesn't support computed usage, will consider throwing exception in upcoming version.

**Comment by lptn** [comment]
@crynobone 
thanks! That also means we need to update PHPDoc, in the current version it's confusing:
```php
/**
 * @method static static make(mixed $name, string|null $attribute = null, callable|null $resolveCallback = null)
 */
class Heading extends Field implements Unfillable
``

**Comment by crynobone** [comment]
ResolvingCallback isn't ComputedCallback.

**Comment by lptn** [comment]
@crynobone 


>ResolvingCallback isn't ComputedCallback.

I know, but this code also doesn't work as expected:

```php
Heading::make('Computed heading (label)', null, function () {
    return 'Computed heading (value)';
}),
```

it sets $resolveCallback, but it's never used on frontend. That's why I called it "confusing"

**Comment by lptn** [comment]
closing because:
>The Heading field doesn't support computed usage, will consider throwing exception in upcoming version.
