### ISSUE TITLE
views/Create.vue: Items in iteration should have unique keys

### ISSUE THREAD

**Issue by disitec** [laravel/nova-issues#6]
This may cause render errors
```html
<div v-for="field in fields">
```

**Comment by disitec** [comment]
"It is recommended to provide a key with v-for whenever possible, unless the iterated DOM content is simple, or you are intentionally relying on the default behavior for performance gains."

Maybe you'll never face an issue, but you could add it if its free. Maybe this
```html
<div
  v-for="field in fields"
  :key="field.component"
>
``
https://vuejs.org/v2/guide/list.html#key

**Comment by themsaid** [comment]
@davidhemphill could you confirm?

**Comment by davidhemphill** [comment]
Keys in this context only matter if you're re-rendering the field list and the component order has changed and only then the default strategy works well enough.

**Comment by disitec** [comment]
Only wondering if it was free to key that up. But its your decision. It's a bit weird for me see the linter and console warnings while developing.

Thanks for taking it in consideration.
