### ISSUE TITLE
Allows to align fields

### ISSUE THREAD

**Issue by michielgerritsen** [laravel/nova-issues#60]
Hi,

At this moment it is not possible to align fields, only the `Boolean` and `File` field are centered. Is it possible to add and `textAlign($alignment);` function on the base class? Especially for the `Currency` column this is a no-brainer.

**Comment by taftse** [comment]
Check out line 88 in Laravel\Nova\Fields\Field.php looks like you can specify it by overriding this value public $textAlign = 'left';  and maybe create a new Currency Field that extends the original but just sets line $textAlign to center like Boolean and File

**Comment by Jam0r85** [comment]
I've tried this but it seems to just push the label over and not the value?

**Comment by corbinhesse** [comment]
You can customize this on any field by using the `withMeta` method.

```php
Number::make('Total')->withMeta(['textAlign' => 'center']),
```

The problem is the tbody does not align correctly due to the alignment class applying to a inline-block span tag.

I added this CSS to an external sheet, and now the fields align correctly.

```css
.table td span.whitespace-no-wrap {
    display: block;
}
```

**Comment by michielgerritsen** [comment]
Ah yes, i see. Thanks!

**Comment by eugenevdm** [comment]
My apologies for raising this old issue, but is there a standard way to align Currency and or numeric fields to the right?

I tried  `->withMeta(['textAlign' => 'right']),` but that only seems to align the column name, not the column values. I then tried adding the CSS as mentioned by @corbinhesse to `resources/views/layouts/app.blade.php` in the header after the other style includes but still no joy.

**Comment by corbinhesse** [comment]
@eugenevdm - `resources/views/layouts/app.blade.php` has no correlation with Nova.

```shell
cp nova/resources/views/layout.blade.php resources/views/vendor/nova/layout.blade.php
```

Add an external stylesheet or inline CSS to the `resources/views/vendor/nova/layout.blade.php` file, and it'll work.

**Comment by Etmolf** [comment]
@davidhemphill

That's still an issue and should take no longer than 10 seconds to fix in one of the upcoming Nova versions. Sure we can hack the css, but we all have to do it in every single project.

the "text-align" should also be on the `td`, not on the inline `span`

**Comment by IVNtech** [comment]
@corbinhesse thanks for your code it makes the magic!!
->withMeta(['textAlign' => 'center']),
