### ISSUE TITLE
Date field must cast to 'date' in Eloquent model when use 'morphedByMany' and 'withPivot' method

### ISSUE THREAD

**Issue by nvn6w** [laravel/nova-issues#600]
I have database to manage inventory. It has tables: imports, items, tools, products.

- imports (id, code, ...)
- itemables (id, import_id, item_id, item_type, import_date, ...)
- tools (id, name, ...)
- products (id, name, ...)

Models:
`Import` has relation:

`public function tools()
    {
        return $this->morphedByMany(Drug::class, 'itemable')->withPivot(['import_date']);
    }`

`public function products()
    {
        return $this->morphedByMany(Tool::class, 'itemable')->withPivot(['import_date']);
    }`

`Tools` has relation:

`public function imports()
    {
        return $this->morphToMany(Import::class, 'itemable');
    }
`

`Product` has relation:

`public function imports()
    {
        return $this->morphToMany(Import::class, 'itemable');
    }
`

In `Nova\Import`, I add fields:

`MorphedByMany::make('tools')->fields(function () {
                    return [Date::make('Import Date', 'import_date')];
                })->searchable(),`

`MorphedByMany::make('products')->fields(function () {
                    return [Date::make('Import Date', 'import_date')];
                })->searchable(),`

Problem:
- I create new `item` by choosing tool / product and set import_date, it's ok.
- I update `item`, nova show me a notification `Date field must cast to 'date' in Eloquent model` and do not show form.

I created model `Itemable` and cast field `import_date` to date but no use. 

![image](https://user-images.githubusercontent.com/1118624/45728510-738e8580-bbf2-11e8-9a1c-e1e7574ffcd8.png)

**Comment by quantbm** [comment]
You are able to define a custom pivot model and tell your relationships to use this custom model when they are defined. See the [documentation](https://laravel.com/docs/5.7/eloquent-relationships#many-to-many), under the heading **Defining Custom Intermediate Table Models**.

Chúc may mắn :)
