### ISSUE TITLE
The icons are not shown on table metric

### ISSUE THREAD

**Issue by thisiskaden** [laravel/nova-issues#6006]
- Laravel Version: 10.29.0
- Nova Version:  4.28.1
- Operating System and Version: mac 14.0(23A344)
- Browser type and version: chrome 118.0.5993.117

### Description:

The icons are not shown on table metric after upgrade to v4.28.1 from v4.28.0

### Detailed steps to reproduce the issue on a fresh Nova installation:
![2](https://github.com/laravel/nova-issues/assets/1886022/8a82d454-fa0f-4473-b29d-c3bcd025d9df)
![1](https://github.com/laravel/nova-issues/assets/1886022/934a0bb6-1cb6-4832-804e-813352078c55)

**Comment by crynobone** [comment]
Please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)
