### ISSUE TITLE
Panel collapsable / collapsedByDefault local storage key is not unique to the resource

### ISSUE THREAD

**Issue by dmason30** [laravel/nova-issues#6011]
- Nova Version: 4.28

### Description:

Say you have these two resources with collapsable panels:

```php
class ExampleA extends Resource {
  public function fields(NovaRequest $request) {
        return [
             Panel::make('Settings', [
                  Text::make('Some field', 'some_field'),
             ])->collapsable(),
        ];
  }
}
```

```php
class ExampleB extends Resource {
  public function fields(NovaRequest $request) {
        return [
             Panel::make('Settings', [
                  Text::make('Another field', 'another_field'),
             ])->collapsable(),
        ];
  }
}
```

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. If you navigate to `Example A` resource details screen and collapse the `Settings` panel
2. `nova.panels.Settings.collapsed` is written to local storage with a value of `true`
3. Navigate to `Example B` resource details screen and the `Settings` panel will be collapsed
4. This is because it ends up using the same `nova.panels.Settings.collapsed` key

### Proposed solution

The resource `uriKey` should be included in the localStorage key?

---

### Additional request

Another issue is if we are on a multi language application where the panel label is translated. 

For a simple example:
- English: Settings
- Other: Sëttïngs

Then because the key is being generated using the translated panel name if a user switches language they are going to lose all their collapsed panels because the key is changed between languages.

- English key: `nova.panels.Settings.collapsed`
- Other: `nova.panels.Sëttïngs.collapsed`

It would be helpful, if you allowed us to provide an `attribute` like we do for all other fields to the `Panel` which when it is provided will prefer to use that in the local storage key rather than the panel name. For example:

```php
class ExampleA extends Resource {
  public function fields(NovaRequest $request) {
        return [
             Panel::make(
                 __('Settings'), 
                 [
                     Text::make('Another field', 'some_field'),
                 ],
                'some-attribute', // <--- new attribute argument
             )->collapsable(), 
        ];
  }
}
```

**Comment by davidhemphill** [comment]
Panels already have a `slug` property, but you're right, we do currently use the `name` in the localStorage key. Changing this would technically be a breaking change, but seems harmless enough that we could do it in a patch release.

**Comment by dmason30** [comment]
@davidhemphill thanks for looking at this. Would be nice DX if you could make it possible to set the attribute via a fluent method too? Happy if you disagree though 😜
