### ISSUE TITLE
DynamicSelect Not showing Required field message below field.

### ISSUE THREAD

**Issue by Mahesh-Thakor** [laravel/nova-issues#6016]
- Laravel Version: 8.83.27
- Nova Version: 4.27.13
- PHP Version: 8.1
- Database Driver & Version: mysql
- Operating System and Version: Ubuntu 22.04 LTS 
- Browser type and version: Chrome Version 118.0.5993.88
- Reproduction Repository: 

### Description:
Like others field showing Required field message (Ex: Text Field)
![image](https://github.com/laravel/nova-issues/assets/87413182/10866ec8-1c5a-4aea-8943-039599d04ee6)

Why DynamicSelect not showing required field below it?

![image](https://github.com/laravel/nova-issues/assets/87413182/458f57ff-f53b-43cd-86ab-d59da29d14bf)

### Detailed steps to reproduce the issue on a fresh Nova installation:

`DynamicSelect::make('Reporting Group', 'reporting_group_id')
                    ->options([
                        '1' => 'Test1',
                        '2' => 'Test2'
                    ])
                    ->sortable()
                    ->wrapperClasses("w-1/2 float-left remove-border flex")
                    ->fieldClasses("md:w-3/5 px-3 py-2")
                    ->labelClasses("md:w-1/4 px-3 py-2")
                    ->rules('required'),
  `

**Comment by crynobone** [comment]
Sorry but we don't maintain `DynamicSelect` custom field.
