### ISSUE TITLE
Edit button showing detail view not ther edit form view

### ISSUE THREAD

**Issue by ProjectesFUAB** [laravel/nova-issues#6019]
- Laravel Version: 10.30.1
- Nova Version: 4.29.2
- PHP Version: 8.2.11
- Database Driver & Version: SQLSRV 16.0.1105.1
- Operating System and Version: Windows 10 - 22H2
- Browser type and version: Google Chrome 119.0.6045.105

### Description:
After  clean install of Nova, when click on edit button in a resource got redirected to detail view not the edit form view. This not  happen with early versions such Nova 4.24.4 in other projects.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Install Laravel (composer create-project laravel/laravel new-project)
Config env file
migrate
Install Nova
Create User

**Comment by mariusghitoiu** [comment]
This happens to me as well after updating at 4.29.2

**Comment by FaridAghili** [comment]
Recently upgraded 4 of my projects to 4.29.2, just checked all of them right now, couldn't confirm the issue you are describing.
All of them working as expected (Edit button goes to edit page, view button goes to details page).

Please make sure you have published new assets.

**Comment by crynobone** [comment]
Fixed and pending next release.
