### ISSUE TITLE
Disabling action via `canRun` displays checkboxes initially but removes them after clicking

### ISSUE THREAD

**Issue by Sjoertjuh** [laravel/nova-issues#6027]
- Laravel Version: 10.31
- Nova Version: 4.29.4
- PHP Version: 8.1
- Database Driver & Version: mysql 8.0
- Operating System and Version: Windows (via WSL2 Ubuntu)
- Browser type and version: Chrome 119.0.6045.105
- Reproduction Repository: https://github.com/Sjoertjuh/nova-action-bug

### Description:

When no actions are allowed and the user is not allowed to delete a resource, the checkboxes show up in the table, even though they shouldn't. After clicking on one, they dissappear

### Detailed steps to reproduce the issue on a fresh Nova installation:

- Add the the `authorizedToDelete` function in a resource and return `false`.
```php
public function authorizedToDelete(Request $request): bool
{
    return false;
}
```
- Add an action (generated with `php artisan nova:action` is fine) to the resource and return `false` in the `canRun` function
```php
public function actions(NovaRequest $request)
{
    return [
        TestAction::make()
            ->canRun(fn () => false)
    ];
}
```

When you open the page of the resource, at first the checkboxes are shown, but when you click on them, they dissappear:

https://github.com/laravel/nova-issues/assets/63722509/8d011b22-032d-44bd-bbce-d2dc45fcfc96

**Comment by crynobone** [comment]
Hi there,

A quick solution to this is to actually use `canSee()` insteads of `canRun()` when possible. The different between the two is that `canSee()` only check against the `$request` while `canRun()` will allow you to check against `$request` and `$model` instance.

What's happening for your use case is that without selection:

1. Nova detects there are action(s) available for the Resource using just `canSee`.
2. You select a resource, Nova makes a request to confirm it has any actions based on the selected resource(s) using `canSee` and `canRun`
3. Resource detected there no actions and unable to delete resources so it remove the checkbox.

**Comment by Sjoertjuh** [comment]
@crynobone I have made the issue here clearer than what my actual use-case is, so unfortunately this doesn't work out for me. Still, thanks for the help!
