### ISSUE TITLE
Searchable select doesn't close when too low in page

### ISSUE THREAD

**Issue by Sjoertjuh** [laravel/nova-issues#6028]
- Laravel Version: 10.31
- Nova Version: 4.29.4
- PHP Version: 8.1
- Database Driver & Version: mysql 8.0
- Operating System and Version: Windows (via WSL2 Ubuntu)
- Browser type and version: Chrome 119.0.6045.105
- Reproduction Repository: https://github.com/Sjoertjuh/nova-select-bug

### Description:

When a searchable select is too low on a page, it isn't closed when clicking outside of it.

### Detailed steps to reproduce the issue on a fresh Nova installation:

- Add lots of filler fields in a resource
```php
Textarea::make('Filler'),
Textarea::make('Filler'),
Textarea::make('Filler'),
Textarea::make('Filler'),
Textarea::make('Filler'),
Textarea::make('Filler'),
Textarea::make('Filler'),
Textarea::make('Filler'),
Textarea::make('Filler'),
```
- Afther the fillers, add a searchable select field
```php
Select::make('Bug')
    ->options([1, 2, 3])
    ->searchable(),
```

When clicking on the select and then clicking outside of it, it isn't closed. It looks like this is because the close handler element is not covering the entire page when scrolled (see video).

https://github.com/laravel/nova-issues/assets/63722509/f0255a92-e97b-4d10-bd49-e776b91c676c

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
