### ISSUE TITLE
Can't load nova-assets and nova-api from domain.com/laravelapps/

### ISSUE THREAD

**Issue by halimtuhu66** [laravel/nova-issues#603]
I've create laravel projects on locals that has a vhost with domain name (ex. mylocaldomain.com). and my laravel apps is in `mylocaldomain.com/laravelnova` ... 
my problem is, nova-assets and nova-api is not found and always send request with url `mylocaldomain.com/nova-assets` and `mylocaldomain.com/nova-api`.
is there a way to make nova-assets go to `mylocaldomain.com/laravelnova/nova-assets` ?

sorry for my bad english

**Comment by AegirLeet** [comment]
#471 same problem?

**Comment by halimtuhu66** [comment]
ah yes thank you for your fast response...

**Comment by alexbowers** [comment]
Duplicate of #471
