### ISSUE TITLE
With Trashed option in BelongsTo field doesn't works when you have an item selected

### ISSUE THREAD

**Issue by dualklip** [laravel/nova-issues#6031]
- Laravel Version: 10.30.1
- Nova Version: 4.29.4
- PHP Version: 8.2.12
- Database Driver & Version: MariaDB 11.1.2
- Operating System and Version: macOs 14.1
- Browser type and version: Google Chrome 118.0.5993.117

### Description:

When you have a resource with a BelongsTo field, and this relationship is with another entity that have soft delete capabilities, the field allows you to filter with or without trashed items.
 
![Screenshot 2023-11-08 at 11 36 43](https://github.com/laravel/nova-issues/assets/2706500/76370b2a-0400-4c84-a974-8501474c2784)

This feature makes a new request to update the dropdown when you click on it, but that only works when you don't have an item previously selected. If you have an item selected, then the requested is not made.

![Screenshot 2023-11-08 at 11 45 39](https://github.com/laravel/nova-issues/assets/2706500/77b26f86-4ca4-495c-96d7-fdf6111397ee)

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Creates a model with soft delete enabled
```php
$table->uuid('id')->primary();
$table->timestamps();
$table->string('title');
$table->uuid('parent_id')->nullable();
$table->softDeletes();
```
3. Define the relationship on the Model
```php
public function parentCategory(): BelongsTo
{
    return $this->belongsTo(Category::class, 'parent_id');
}
```
4. Creates the Nova resource with the field
```php
BelongsTo::make('parentCategory', Category::class)->nullable(),
```

https://github.com/laravel/nova-issues/assets/2706500/56905b5c-972d-4789-87ee-9a3fd4a05fac

**Comment by andrebreia** [comment]
We're also experiencing this issue. Is there an update on this?

Thanks!
