### ISSUE TITLE
2 Belongs To Depending on Each Other cancelling each other's value

### ISSUE THREAD

**Issue by ch-hamzzyy** [laravel/nova-issues#6039]
- Laravel Version: 10.x
- Nova Version: latest
- PHP Version: 8.2
- Database Driver & Version:
- Operating System and Version: Windows Latest
- Browser type and version: Chrome Latest
- Reproduction Repository: https://github.com/###/###

### Description:
```
BelongsTo::make('Client')->dependsOn(['contact'], function ($field, $request, $formData) {
    // Update relatable query so only the client of the selected contact shows up
    // $formData does not have a value for itself
}),
BelongsTo::make('Contact')->dependsOn(['client'], function ($field, $request, $formData) {
    // Update relatable query so only contacts of selected clients show up
    // $formData does not have a value for itself
}),
```
When I select a Contact,
Then I select a Client,
The contact value becomes null

Bug: The field doesn't store the field value in `value` property
<img width="1290" alt="262212066-1746cf28-895e-4bef-9c71-05087057a152" src="https://github.com/laravel/nova-issues/assets/71060601/1684d7bd-ae08-43e5-951b-ce0b74284dac">

`DependentFormField` sends the empty `value` property in request for dependson

**Comment by davidhemphill** [comment]
Having two fields depend on each other is not currently supported in dependent fields because it would lead to an infinite loop.
