### ISSUE TITLE
Feature Suggest: After update resource redirect

### ISSUE THREAD

**Issue by Donkfather** [laravel/nova-issues#604]
Now if the user doesn't have permission to view a specific resource after updating one it will try to redirect to view resource.
It would be nice if it would know that the user doesn't have permission to view and redirect to index for example.

Long story short: Make redirects take policies into account

**Comment by dillingham** [comment]
In what case should a user not be able to view a resource that they can edit?
Just make a redirect if you want a redirect
https://github.com/laravel/nova-issues/issues/797#issuecomment-437100111

**Comment by dillingham** [comment]
Related https://github.com/laravel/nova-issues/issues/538 https://github.com/laravel/nova-issues/issues/604 https://github.com/laravel/nova-issues/issues/797 https://github.com/laravel/nova-issues/issues/862

**Comment by seagyn** [comment]
A use case that I am currently looking at is if you add / update a resource from a related resource (Add a post from a user detail page) then it would be a better flow if it took you back to the user detail view rather then to the post detail view.

In my use case, I have conversations with messages. If you add a message, I want you to go back to the conversation.

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
