### ISSUE TITLE
Card `overflow-hidden` class breaks searchable select field overflow.

### ISSUE THREAD

**Issue by dmason30** [laravel/nova-issues#6040]
- Nova Version: 4.29.4, 4.29.5

### Description:
The addition of `overflow-hidden` class to the `Card.vue` component in 4.29.4 has broken select field overflow when the field is near the bottom of the card. 

**Form**
See video of how the `overflow-hidden` is making the field select move when the search part is rendered and how the `overflow-hidden` is hiding the results.

```php
Select::make('Example', 'name')
    ->options(collect(range(1, 30))
        ->mapWithKeys(fn ($i) => ["example_$i" => "Example $i"]),
    )
    ->searchable(),
```
https://github.com/laravel/nova-issues/assets/20278756/3ab8983e-2f5d-4cbb-afce-71ce0b48fae1

**Attaching**
```php
MorphToMany::make('Users', 'users', UserResource::class)
                ->fields([...])
                ->searchable(),
``` 
               
<img width="567" alt="image" src="https://github.com/laravel/nova-issues/assets/20278756/497fead8-9ff4-4727-a787-cbad71126187">

**Comment by kazak71** [comment]
I confirm!
But this problem is not related only to card. It's probabli more complex. 
It's appears without using card but when form fields are few

**Comment by davidhemphill** [comment]
I believe this issue should be fixed. Please post a new issue if the issue persists.
