### ISSUE TITLE
Request for Localization Support in Confirm Dialog for Notification Deletion

### ISSUE THREAD

**Issue by fivevaiai** [laravel/nova-issues#6043]
- Laravel Version: v10.20.0
- Nova Version: 4.27.12
- PHP Version: 8.1.22

## Description:

In Laravel Nova, internationalization (i18n) is implemented in most parts, but there are some omissions. Specifically, the text in the confirmation dialog for deleting notifications, located at line 170 in `vendor/laravel/nova/resources/js/components/Notifications/NotificationCenter.vue`, is not i18n compliant. This section displays a fixed English message: "Are you sure you want to delete all the notifications?", which does not support display in other languages like Japanese. To fully realize Nova's multilingual support, i18n compliance for this part is necessary.

![image](https://github.com/laravel/nova-issues/assets/147669732/b5b47f94-e6b6-4556-81b2-bf25703a46e4)

## Detailed Steps to Reproduce the Issue on a Fresh Nova Installation:

1. Install Laravel Nova on a new Laravel application.
2. Configure localization settings in Laravel Nova.
3. Click the notification icon in the Nova header.
4. Click the three-dot menu.
5. Click "Delete all notifications".
6. Observe that the confirmation dialog displays the fixed English message: "Are you sure you want to delete all the notifications?".

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
