### ISSUE TITLE
Upgraded to Nova 4 Installed --> View [app] not found

### ISSUE THREAD

**Issue by MitzaCeusan** [laravel/nova-issues#6044]
- Laravel Version: 9.52.16
- Nova Version: 4.29.5
- PHP Version: 8.1.8
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: Chrome 118.0.5993.117
- Reproduction Repository: https://github.com/###/###

### Description:

I have upgraded from Laravel Nova 3.26.1 to 4.29.5
When loading any /nova/resources/ url the page crashes with the error:
View [app] not found.

VerifyCsrfToken->handle()
     * @param  \Closure  $next     * @return mixed     */    public function handle($request, Closure $next)    {        return parent::handle($request, $next);    }}

**Comment by crynobone** [comment]
Please make sure you follow the upgrade guide and import the correct middlewares.

**Comment by MitzaCeusan** [comment]
working after added missing middleware.
