### ISSUE TITLE
MorphToMany with Pivot Repeater fields is not working

### ISSUE THREAD

**Issue by msucevan** [laravel/nova-issues#6046]
- Laravel Version: 10.31
- Nova Version: 4.29.5
- PHP Version: 8.1
- Database Driver & Version: MySQL 8.0.33 (DBNGIN)
- Operating System and Version: Herd v1.3.1 (Build: 18)
- Browser type and version: Chrome 119 on macOS (Sonoma)

### Description:
When I attach a MorphToMany with pivot fields is working as expected, when I'm loading the view/edit page I get an error: `: Cannot access offset of type string on string ``
Is this currently not supported, can I handle this somehow? Or it's a issue?

### Detailed steps to reproduce the issue on a fresh Nova installation:
Reproduce with this snippet
```php
            MorphToMany::make(__('Suppliers'))
                ->sortable()
                ->rules('required')
                ->fields(function ($request, $relatedModel) {
                    return [
                        Repeater::make(__('Prices'), 'bulk_prices')->repeatables([
                            BulkPrices::make(__('Prices')),
                        ]
                        )->asJson(),
                    ];
                }),
```

**Comment by davidhemphill** [comment]
Sorry, but we are unable to debug your issue without a reproducible code example. When you're able to demonstrate the issue with an example, feel free to open a new issue.

**Comment by hosnyben** [comment]
Facing the same issue :/
