### ISSUE TITLE
"Update Media" button is disabled after Laravel Nova v4.28.0 in MediaLibrary Field package

### ISSUE THREAD

**Issue by tmartty** [laravel/nova-issues#6047]
- Laravel Version: 10.32.1
- Nova Version: 4.28.0
- PHP Version: 8.1

### Description:

When using @dmitrybubyakin Medialibrary Field (https://github.com/dmitrybubyakin/nova-medialibrary-field), starting from Laravel Nova v4.28.0, when editing a media item fields, the modals "Update Media" button can't be clicked and shows as disabled:
![image](https://github.com/dmitrybubyakin/nova-medialibrary-field/assets/24498673/578f0dab-9f57-4bea-a9fe-efdb576fb18c)

![image](https://github.com/dmitrybubyakin/nova-medialibrary-field/assets/24498673/19e656c5-a7d3-4f9f-8032-f7766547886b)

If I downgrade Laravel Nova to v4.27.14 (the latest previous version), it works fine.

**Comment by davidhemphill** [comment]
The library likely uses Nova's internal components which are subject to change and aren't under public API. Post an issue on the package maintainer's repository for support. Thanks!
