### ISSUE TITLE
BelongsTo Field doesn't display icon anymore

### ISSUE THREAD

**Issue by GautierDele** [laravel/nova-issues#6053]
- Laravel Version: 10.32.1
- Nova Version: 4.31.3
- PHP Version: 8.2.11
- Database Driver & Version: 
- Operating System and Version: #.#
- Browser type and version: Google Chrome

### Description:

The belongsTo fields doesn't display the icon anymore.

V4.22.0:
![image](https://github.com/laravel/nova-issues/assets/12382966/6eb3887d-a094-4cd5-bb58-0c40d9ae908e)

V4.31.3:
![image](https://github.com/laravel/nova-issues/assets/12382966/bbbbe691-fbc4-4692-8f48-d3929e277a5b)

The icon disapear when the fill is auto field when editing an existing model. This prevent from clearing the field for example.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Setup a Nova Resource with a BelongsTo field, edit an existing entry

**Comment by andypooletrioteca** [comment]
It gets rendered at the top-right of the field's panel.
<img width="832" alt="Captura de pantalla 2023-11-22 a las 12 40 28" src="https://github.com/laravel/nova-issues/assets/55230020/4da4e38a-4cc5-45c9-997e-b2f976cc232d">

**Comment by GautierDele** [comment]
Its disapoiting, dont think its normal actually

**Comment by davidhemphill** [comment]
This has been fixed in a recent release. 👍
