### ISSUE TITLE
Backdrop of SearchSearchInput isn't working in Modal

### ISSUE THREAD

**Issue by BenGentner** [laravel/nova-issues#6058]
- Laravel Version: 9.52.5
- Nova Version: 4.31.3

### Description:
I'm using the SearchSearchInput.vue component in a custom Nova Tool within a Modal. The component adds a Backdrop with z-[35]. The Modal adds a Backdrop with z-[55]. So I can't close the SearchInput Options by clicking outside the component. 
![Bildschirmfoto 2023-11-22 um 14 16 47](https://github.com/laravel/nova-issues/assets/74174237/dd9738f0-9ae0-4abb-8f67-afe469f68639)
![image](https://github.com/laravel/nova-issues/assets/74174237/a291043a-9e37-466e-89c4-b28d4e6b15f7)
![Bildschirmfoto 2023-11-22 um 14 30 43](https://github.com/laravel/nova-issues/assets/74174237/910a70fd-22ba-4c2b-9bc3-b63aa4e8e5de)
Could the z-index on the SearchSearchInput be increased or could we get the option to change the z-index via a prop? 

### Detailed steps to reproduce the issue on a fresh Nova installation:
Using the SearchSearchInput.vue within a Modal

**Comment by davidhemphill** [comment]
Nova's internal components are not under public API, versioned, and change frequently. It's not advised to use them for this reason. 

We're working on a package that will address this for Nova, but it's not ready yet!
