### ISSUE TITLE
Searchable select arrow key up / down does not scroll with the options

### ISSUE THREAD

**Issue by dmason30** [laravel/nova-issues#6059]
- Nova Version: 4.32.1

### Description:

Given this select:

```php
Select::make('Example', 'example')
    ->options(collect(range(1,25))
        ->mapWithKeys(fn ($i) => ["example_$i" => "Example $i"])
    )
    ->searchable()
```

The arrow key presses do not scroll the options, the `SearchInput.vue` component has explicit code to try and achieve this but seems is no longer working.

https://github.com/laravel/nova-issues/assets/20278756/4f11b001-2602-493e-b051-47c2e09c22cd

**Comment by davidhemphill** [comment]
This has been fixed in the 4.32.6 release. 👍
