### ISSUE TITLE
Notification unread count inconsistent text colour on dark mode

### ISSUE THREAD

**Issue by dmason30** [laravel/nova-issues#6061]
- Nova Version: 4.32.1

### Description:
On dark mode the text colour is white, which is inconsistent with how we use the primary background colour, for example, with buttons.
<img width="141" alt="image" src="https://github.com/laravel/nova-issues/assets/20278756/0fec0ea0-3544-4be6-b2a6-70d46a27d909">

### Fix
Add `dark:text-gray-800` to make it display like this:
<img width="138" alt="image" src="https://github.com/laravel/nova-issues/assets/20278756/77f17137-10c2-4791-9227-ff5fef7ba47b">

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
