### ISSUE TITLE
Searchable BelongsTo clear selection icon wrong visual positioning

### ISSUE THREAD

**Issue by oliver-wunu** [laravel/nova-issues#6062]
- Laravel Version: 10.33.0
- Nova Version: 4.32.2
- PHP Version: 8.1.24
- Database Driver & Version: mysql 8.0.35
- Operating System and Version: macOS 14.0 (23A344)
- Browser type and version: Arc 1.17.2 & Safari 17.0

### Description:
Using a BelongsTo Field with the `->searchable()` option leads to a wrong position of the clear selection X icon when a model is selected. This visual issue occurs on edit view and also occurs on create screen if `nullable()`is added to the resource field.

Light Theme
<img width="1250" alt="Screenshot 2023-11-24 at 10 58 51" src="https://github.com/laravel/nova-issues/assets/70704034/901cd176-a1df-40e1-9ca3-316458ac0742">

Dark Theme
<img width="1242" alt="Screenshot 2023-11-24 at 10 56 45" src="https://github.com/laravel/nova-issues/assets/70704034/32e38cb7-e153-4660-b76a-c590a13a4c91">

### Detailed steps to reproduce the issue on a fresh Nova installation:
Create a Nova Resource with a Belongsto Field like below.
`BelongsTo::make('user')->searchable()->nullable()->hideFromIndex(),`

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
