### ISSUE TITLE
Textarea on detail renders different text colour compared to `alwaysShow`

### ISSUE THREAD

**Issue by dmason30** [laravel/nova-issues#6072]
- Nova Version: 4.32.1

### Description:

Occurs on both theme types, the correct colour is the 'Hidden by default' examples shown below. As that colour matches the colour used by other fields.

**Light Mode**
<img width="830" alt="image" src="https://github.com/laravel/nova-issues/assets/20278756/f94c40cc-9b45-41a8-980b-3c92f51736c8">

**Dark Mode**
<img width="835" alt="image" src="https://github.com/laravel/nova-issues/assets/20278756/84e3370c-0c2d-4a99-a3d2-1e81d05f400e">

### Detailed steps to reproduce the issue on a fresh Nova installation:

```php
Textarea::make('Hidden by default', fn () => 'This is an example text area that is NOT using always show.'),

Textarea::make('Always show', fn () => 'This is an example text area that is using always show.')
    ->alwaysShow(),
```

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
