### ISSUE TITLE
no theme button color on dark mode

### ISSUE THREAD

**Issue by anditsung** [laravel/nova-issues#6077]
- Laravel Version: 10
- Nova Version: 4.32.6
- PHP Version: 8.1

<img width="668" alt="Screenshot 2023-11-30 at 13 21 31" src="https://github.com/laravel/nova-issues/assets/1090413/f0a247f0-2ed2-469c-8fe6-bdc5680bd02c">

<img width="656" alt="Screenshot 2023-11-30 at 13 21 36" src="https://github.com/laravel/nova-issues/assets/1090413/436e059e-b1da-4c10-859b-57f1cb4f0ee8">

just notice there is no theme button color on dark mode

-- 
i think start from 4.28

**Comment by rzuloaga** [comment]
Isn't it the crescent icon?

**Comment by anditsung** [comment]
> Isn't it the crescent icon?

Correct icon but not using brand color when selected. Default should be sky color just like the sun

**Comment by davidhemphill** [comment]
This was fixed in a recent release...Thanks for reporting!
