### ISSUE TITLE
Anchor tag for 'View' and 'Edit' button does not have the `href` attribute set 

### ISSUE THREAD

**Issue by JaredPage** [laravel/nova-issues#6083]
- Laravel Version: ^10
- Nova Version: All versions from v4.29.3 onward.
- PHP Version: ^8.2
- Database Driver & Version: MySQL 8.0.27
- Operating System and Version: On both MacOS and Ubuntu
- Browser type and version: Browser doesn't affect results.

### Description:
All of the 'edit' links in a resource have a null 'href' value from version 4.29.3 onward. See pictures below. When the edit or view buttons are hovered over (or you just inspect source), you will see that the `href` value for the anchor tag is blank/null from 4.29.3 onward. This results in the 'edit' and 'view' buttons being unable to be opened in a new tab (right-click, open in new tab) and/or using the middle mouse button for the same purpose. 

There is also weird behaviour where the initial request is then cancelled, and a subsequent XHR request is made to the correct URL. For the earlier version, this cancelled request includes the `<id>/edit` portion of the URL, whereas in the newer one, it omits it.

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Install v4.29.2
- Install v4.29.3 or any version afterwards and notice that every resource does not have the correct link associated with it for the 'Edit' or 'View' buttons. 

![1  id-present (4 29 2)](https://github.com/laravel/nova-issues/assets/7892646/f5a4f773-e68f-4317-afaa-bb7b72cb771e)
![2  no-id-present (4 29 3)](https://github.com/laravel/nova-issues/assets/7892646/d4c8168d-9a1a-47aa-9877-fe8c5a256cfd)
![cancelled-behaviour-2](https://github.com/laravel/nova-issues/assets/7892646/006ea1c7-3e35-4222-b1e6-9ddb70ade789)
![cancelled-behaviour-1](https://github.com/laravel/nova-issues/assets/7892646/5396400a-5f8d-40c3-a131-871ef338bed3)

**Comment by vDk3** [comment]
+1 very annoying

**Comment by andypooletrioteca** [comment]
Already opened an issue related to this and has been closed... Weird decision.

#6075

**Comment by anditsung** [comment]
https://github.com/laravel/nova-issues/issues/6126

looks like this issue causing 2 new tab when click using ctrl / command

**Comment by jesse-davis** [comment]
Would appreciate a fix for this one.
