### ISSUE TITLE
Blank Lens Icon visible on a resource with no Lens.

### ISSUE THREAD

**Issue by superuser-me** [laravel/nova-issues#6088]
- Laravel Version: 10.35.0 
- Nova Version: 4.32.9
- PHP Version:  8.2.13 

### Description:

It's showing a blank Lens icon on recources which has no lens.
Upon clicking that icon shows tiny blank circle.

I have updated from  nova version `4.27.14` to `4.32.9`
and after that it's happening,

i have cleared views cache & composer cache after update.

![CleanShot 2023-12-07 at 12 53 43 PM@2x](https://github.com/laravel/nova-issues/assets/71923103/a3a72dd0-39bf-4056-81bb-81a898c59135)

https://share.cleanshot.com/FT6yNX8p

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by tommiekn** [comment]
+1 same issue here

**Comment by davidhemphill** [comment]
To diagnose and fix issues, we need to be able to reproduce them. Having detailed bug reports, and ideally, a reproduction repository is the best way to help us.

When you can provide a reproducible example on a fresh instance of Nova, we'd love to take a look and work towards a resolution!
