### ISSUE TITLE
Got a bug after updating to 4.x

### ISSUE THREAD

**Issue by Ashour-dev** [laravel/nova-issues#6089]
- Laravel Version:^10.0
- Nova Version: ^4.32
- PHP Version: 8.0
- Database Driver & Version: Mysql
- Operating System and Version: Windows 11

### Description:
I am developing a multi-tenant app, it was running on 3.x normally without any issues. Once I updated Nova to 4.x, I started having problems. First, it started to look for app.blade.php in the default resources/views directory, which was never there. As it's not possible to publish the layout anymore I added the vendor path (base_path('vendor/laravel/nova\resources\views')) to the paths in the config/views.php, and it worked. but I had to rename the layout file (from layout.blade.php to app.blade.php) as it was looking for this path, and it worked. Then I started getting this error in console: 
```
app.js:343 Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')
    at br.registerStoreModules (app.js:343:17)
    at br.liftOff (app.js:180:10)
    at login:41:14
```

which links to this part in the app.js file:
```
 /**
   * Register the built-in Vuex modules for each resource
   */
  registerStoreModules() {
    this.app.use(this.store)

    this.config('resources').forEach(resource => {
      this.store.registerModule(resource.uriKey, resourceStore)
    })
  }
```

I am not using Vue in my app at all, could this be related?

**Comment by crynobone** [comment]
Please refer to https://github.com/laravel/nova-issues/discussions/4127
