### ISSUE TITLE
Metrics with Relationship

### ISSUE THREAD

**Issue by packytagliaferro** [laravel/nova-issues#609]
Lets say I have 2 tables Bags and Items

Each Bag has a "type" field (gym, grocery, garbage, ect). 
Each Item has a "ounces" field (int)

The Bag model has a relation:

```
public function items()
        {
            return $this->hasMany('App\Item');
        }
```

At the top of the resource Bags I want to display a partition metric that shows the type of bags sorted by total item ounces. If I create a partition metric, how can I calculate this?

`
 return $this->sum($request, Bag::class, Bag::items->ounces , 'type');`

**Comment by gonzunigad** [comment]
I think you can not do it with the predefined aggregations, but you can easily build your own resutls. 

```
return $this->result([
    'Garbage' => 100, //Calculate somehow
    'Groceries' => 200, //Calculate somehow
    'Gym' => 300, //Calculate somehow
]);
```

**Comment by alexbowers** [comment]
Closing due to the solution by gonzunigad

**Comment by christianmarth** [comment]
This is a poor implementation, there needs to be a way to dynamically calculate metrics using relationships

**Comment by Ji20on** [comment]
How?

**Comment by mikebronner** [comment]
Here's an example using polymorphic relationships, as per the nova docs (https://nova.laravel.com/docs/2.0/metrics/defining-metrics.html#manually-building-partition-results):
```php
        return $this->result((new Tag)
            ->withCount("photos")
            ->orderBy("photos_count", "DESC")
            ->get()
            ->pluck("photos_count", "name")
            ->toArray());
```

**Comment by karamqubsi** [comment]
Hi, If anyone coming here and still looking for a simpler way. 

Another simple way is to create SQL view which will contains all columns that you wish to use in your metric and maybe filtered by some conditions ( if needed ).

You can include the view in your migrations as well, 
```php
    public function up()
    {
        DB::statement("
        CREATE VIEW bags_view AS
        SELECT b.id , b.col1 , i.col2 , b.col3   , .....
        FROM bags b
        LEFT JOIN items i ON (i.bag_id = b.id)
        ....
          ");
    }

```

Then create a class you may create a new namespace like App\ModelViews ,or App\ReadOnly, and have a Bag under that namespace

Then make sure to update the $table attribute if needed, 

```php
namespace App\ModelViews;

use Illuminate\Database\Eloquent\Model;

class Bag extends Model
{
    protected $table = 'bags_view';

...
```

After that use it as if it was a normal model in your metrics.

**Comment by Thiritin** [comment]
If anyone run's into this issue. Please refer to this Documentation Page. You can simply do a where request.
https://nova.laravel.com/docs/2.0/metrics/registering-metrics.html#resource-detail-metrics
