### ISSUE TITLE
Filterable() is broken after upgrading to 4.32.7, Select all button is missing

### ISSUE THREAD

**Issue by superuser-me** [laravel/nova-issues#6093]
I think the redesign of essential parts of nova is rushed thing,
I don't know the intentions of team for this redesign rush.
This essential things get's slipped from testing, because after any upgrade i think you do testing of all logical things,
Team should test these visual features before releasing any redesign.

My filters were working fine in 4.32.6

Please read  all version numbers carefully.
 
 After upgrading i ran `php artisan nova:publish`
 and `composer dumpautoload -o`
 
![CleanShot 2023-12-09 at 05 49 01 PM@2x](https://github.com/laravel/nova-issues/assets/71923103/2c652a36-1e0c-48ff-bcff-a5e936b7d8f6)

But if i upgrade to 4.32.7
it shows no filters,
without any change in my code.

![CleanShot 2023-12-09 at 05 47 24 PM@2x](https://github.com/laravel/nova-issues/assets/71923103/b44ded5f-f205-4abe-880d-1827bf0e3300)

Also select all button is missing after version **4.27.14**.
i said version 4.27.14 not recent ones.

![CleanShot 2023-12-09 at 05 50 12 PM@2x](https://github.com/laravel/nova-issues/assets/71923103/18ffe0e2-852b-49ce-93b6-2bc9ec161345)

**Comment by crynobone** [comment]
Please update to latest version, which should already contain the fixes and new tests
