### ISSUE TITLE
Searchable Select Action Field not working

### ISSUE THREAD

**Issue by Mihkel100** [laravel/nova-issues#6097]
- Laravel Version: 10.35.0
- Nova Version: 4.32.9
- PHP Version: 8.2

### Description:

Cannot choose option from Searchable Select when it is used as Action Field.
The problem started since Nova version 4.32.7

```php
public function fields(NovaRequest $request)
{
    return [
        Select::make('Staff', 'staff_id')
            ->searchable()
            ->options(
                $this->staffOptions()
            ),
    ];
}
```

**Comment by henryavila** [comment]
Same problem here. 

Can confirm that works on  v4.32.6

**Comment by sanderbaas** [comment]
There's also some debug console logging going on:

![image](https://github.com/laravel/nova-issues/assets/4152895/585d76bc-3839-4921-a13e-a843e8152723)

**Comment by alancolant** [comment]
Same problem here.

**Comment by votkapower** [comment]
Same here, cant select, cant search, have to downgrade to regular select :/

**Comment by Mihkel100** [comment]
> Same here, cant select, cant search, have to downgrade to regular select :/

Or you can downgrade to Nova 4.32.6.

composer.json
`"laravel/nova": "4.32.6"`

**Comment by votkapower** [comment]
> > Same here, cant select, cant search, have to downgrade to regular select :/
> 
> Or you can downgrade to Nova 4.32.6.
> 
> composer.json `"laravel/nova": "4.32.6"`

Where the `Action::download` doesn't work. These recent versions are kinda messed up.
Messaging just to confirm the bug and hopefully it's get prioritized.

**Comment by davidhemphill** [comment]
Just pushed a hotfix for this until we sort why the `SearchInput` used by `BelongsTo` field is not handling events.
