### ISSUE TITLE
Export action stopped working properly

### ISSUE THREAD

**Issue by kazak71** [laravel/nova-issues#6098]
- Laravel Version: 10.35.0
- Nova Version: 4.32.9
- PHP Version: 8.1
- Database Driver & Version: MySql 8
- Operating System and Version: ubuntu server
- Browser type and version: all browsers
- Reproduction Repository: https://github.com/###/###

### Description:
After update Nova to version 4.32.9 Export Action (to CSV and to xlsx) stopped working. It shows up, I can select records, but where click button to run action, nothig happend - action just closes without any response.
In Nova v4.32.6 export action works fine.

**Comment by votkapower** [comment]
Same here, its returned as reponse to the nova request, instead of being forced dowload, and there is no hook you can use to change that easy :/

**Comment by kazak71** [comment]
Привет!
Това им се случва за пореден път.
Проблема явно им е не в самия респонс, а в липсващ в него хедър за сваляне. Това се наблюдава и когато създадеш екшън за сваляне на ресурс - резултатът е същият. Показва се съобщение, че действието е успешно, а няма резултат. Явно вече имат няколко разработчици на Vue и някой чупи работата на другите си колеги. Например преди няколко версии имаше проблем с един клас, който се прилагаше на div във формите - overflow-hidden и това водеше до ‘отрязване’ на searchable selectboxes при форми с малко контроли. Бяха го оправили, но сега чета, че пак се проявява при някои колеги. Все по- дразнещо става при всеки ъпдейт да се налага тотален тест на цяла система преди прилагане на промените. За малки системи не е проблем, но за по- сериозни - вече става голям, особено ако има много различни роли потребители.

Поздрави,
Петър Казаков

**Comment by mstaack** [comment]
same issue https://github.com/laravel/nova-issues/issues/6100

**Comment by davidhemphill** [comment]
Duplicate of #6100
