### ISSUE TITLE
Saving resource with custom primaryKey throws error on redirect to resource detail view

### ISSUE THREAD

**Issue by randelsr** [laravel/nova-issues#610]
I have a resource that has an enumerated primaryKey, eg tier_id of the tiers table.

When I save this resource via Nova, the resource properly saves to the database, but when Nova redirects to the new resource detail view, I receive the following:

[2018-09-19 18:39:29] local.ERROR: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "undefined" (SQL: select * from "tiers" where "tiers"."tier_id" = undefined limit 1) ...

Maybe on save, it's not obtaining the new resource's proper ID from the api?

When I try this with a standard object with primaryKey 'id' everything works fine..

**Comment by randelsr** [comment]
https://github.com/laravel/nova-issues/issues/189

**Comment by dkulyk** [comment]
Duplicate of https://github.com/laravel/nova-issues/issues/1124

**Comment by dkulyk** [comment]
This has been fixed and will be included in the next release.

**Comment by iSWORD** [comment]
Any idea when the next release coming out? It should fix a couple issues I'm having.
