### ISSUE TITLE
Action dropdown headings 'Actions' header shows even when there are no Actions to be displayed.

### ISSUE THREAD

**Issue by dmason30** [laravel/nova-issues#6101]
- Nova Version: 4.32.9

### Description:
On a resource with all possible actions disabled that would display under the new `Actions`  header you end up with this:

<img width="338" alt="image" src="https://github.com/laravel/nova-issues/assets/20278756/25d7cb09-9e48-446f-ba4a-182c445cc6d1">

I would expect the 'Actions' header and the divider beneath to be hidden in this case:

<img width="321" alt="image" src="https://github.com/laravel/nova-issues/assets/20278756/75895dc7-6094-427f-93e9-5f430826502a">

**Comment by mstaack** [comment]
yes, having the same also

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍

**Comment by marventhieme** [comment]
@davidhemphill Is there any way to utilize the showHeadings property from `vendor/laravel/nova/resources/js/components/Dropdowns/ActionDropdown.vue`, so that I can globally hide those headings?
