### ISSUE TITLE
Width /5 is no longer working

### ISSUE THREAD

**Issue by alingeopress** [laravel/nova-issues#6104]
- Laravel Version: 10.34
- Nova Version: 4.32.9
- PHP Version: 8.2
- Database Driver & Version: MySQL
- Operating System and Version: Ubuntu 20.4
- Browser type and version: Firefox 120.0.1

### Description:
Since updating it to Laravel Nova 4, the width sizes are behaving really weird, so like this width is no longer working (pics attached)
`(new CandidateMetrics)->width('2/5'),
            (new NewCandidates)->width('1/5'),
`
![image](https://github.com/laravel/nova-issues/assets/143711487/3152dd65-3392-43ea-a04e-785dc5b0ce1f)

from my tests only width('1/3') is working anymore 

### Detailed steps to reproduce the issue on a fresh Nova installation:
Create a new card and add a 1/5 or 2/5 width to it.

**Comment by davidhemphill** [comment]
'1/5' is no longer available as an option in Nova v4 due to space concerns. The available options are: 'full', '1/3', '1/2', '1/4', '2/3', and '3/4'.
