### ISSUE TITLE
Handle nova config file in tools routing stubs

### ISSUE THREAD

**Issue by RomainMazB** [laravel/nova-issues#6106]
- Laravel Version: 10.37.1
- Nova Version: 4.32.9
- PHP Version: 8.2

### Description:
When creating our fist Tool, the documentation states:
> The route group specifies that all "API routes", **which will typically be invoked from the client via [Nova.request](https://nova.laravel.com/docs/4.0/customization/frontend.html#nova-requests)**, should receive a **/nova-vendor/tool-name URL prefix**, where tool-name is the "kebab-case" name of your tool.

As expected, the stub for the Tools prefix the route group with the `/nova-vendor/tool-name` part.

But, when using `Nova.request`, the config `nova.path` (which defaults to `/nova`) is prepended to the request, and I guess (not tested) that the `nova.domain` is also supported by the javascript library.

I suggest that the stub should include the config path and domain to avoid losing time to figure why we get a 404 with a basic routing file for our tool.

**Comment by crynobone** [comment]
It not clear what's the issue here, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by RomainMazB** [comment]
Hi @crynobone
I guess these snippets of code are enough to understand:

This is the default `routes` method of the `ToolServiceProvider` when using the `nova:tool` command:
```php
protected function routes()
{
  if ($this->app->routesAreCached()) {
    return;
  }

  Nova::router(['nova', Authenticate::class, Authorize::class], 'world-creator')
    ->group(__DIR__.'/../routes/inertia.php');

  Route::middleware(['nova', Authorize::class])
    ->prefix('nova-vendor/world-creator') // <--- Here is the problem
    ->group(__DIR__.'/../routes/api.php');
}
```
I created a basic route inside my tool `routes/api.php` file:
```php
use MazLaboratory\WorldCreator\Http\Controllers\WorldCreator;

Route::put('/create', [WorldCreator::class, 'create']);
```
And inside my `Tool.vue` frontend file, I want to call this create controller method using the recommended `Nova.request` library:
```js
export default {
  data: () => ({
    formData: {
      world_name: '',
      map_name: '',
      maximum_players: undefined,
      map_width: undefined,
      map_height: undefined,
    }
  }),
  methods: {
    async createWorld() {
      await Nova.request().put(`nova-vendor/world-creator/create`, this.formData)
        .then(response => Nova.success(response.data))
        .catch(error => Nova.error(error.response.data))
    }
  }
}
```
Reading the Tool documentation and trusting the `ToolServiceProvider` stub, this should work ...
But it fails into a 404 because the route group is not prefixed by the config `nova.prefix` and `nova.domain` which looks like to be included inside `Nova.request` but not inside the `ToolServiceProvider` stub!
![image](https://github.com/laravel/nova-issues/assets/53976837/e15b971e-166a-4e32-8fbf-9d74931b39e5)

The final working code for my `ToolServiceProvider` looks like this and this is how I expected the stub to be:
```php
Route::middleware(['nova', Authorize::class])
    ->prefix(config('nova.path').'/nova-vendor/world-creator')
    ->group(__DIR__.'/../routes/api.php');
```
In my case, the `nova.domain` config is null but I guess that I would have to add `->domain(config('nova.domain'))` to this code if not.

**Comment by crynobone** [comment]
`nova-vendor` normally should be the at the root level similar to `nova-api` and configurable `nova`

**Comment by RomainMazB** [comment]
> `nova-vendor` normally should be the at the root level similar to `nova-api` and configurable `nova`

Actually, the route is when generating Tool. I modified the route file to add the `/nova` part which correspond to my `nova.path` config.

If this is the expected behavior, do we have any way to use `Nova.request` to call a root level route like `myapp.dev/nova-vendor/my-tool` ?
`Nova.request` for sure prepend all routes called with the `nova.path` config.
