### ISSUE TITLE
`Select` component in Actions is slow to show results

### ISSUE THREAD

**Issue by meyer59** [laravel/nova-issues#6107]
- Laravel Version: 10.37.3
- Nova Version: 4.32.9
- PHP Version: 8.2
- Database Driver & Version: MYSQL
- Operating System and Version: UNIX
- Browser type and version: chrome 119.0.6045.124

### Description:
We have noticed an issue with the _Select_ component in our _Actions_; it doesn't seem to be working properly after the latest update of Nova. The issue manifests as a significant lag in the visual response, giving the impression of extensive processing taking place in the background. This behavior started occurring since the most recent update of Nova.
This is very annonying since the Select component is used everywhere in the app.
Here is a screenshot of the console, the last log appears once i open the Select
![image](https://github.com/laravel/nova-issues/assets/9505463/eb94352f-8db2-4dbf-9989-cb1c35ddf535)

### Detailed steps to reproduce the issue on a fresh Nova installation:
put a searchable select in an action and try to open it

**Comment by CaddyDz** [comment]
For now you can downgrade to `4.27.13`

**Comment by meyer59** [comment]
@davidhemphill, is there any way to prioritize this bug? It seems to be affecting all of the Nova Select components.

**Comment by mbensch** [comment]
I am facing a similar issue: A basic searchable select renders with dropdown open and is not interactive at all. Not sure if this warrants a new bug report or if this is related. Here is a [Jam](https://jam.dev/c/42883a36-85e9-4207-8a28-4df9ddb0bb1d)

**Comment by crynobone** [comment]
Please check if the latest version (4.32.15) still has this issue.

**Comment by meyer59** [comment]
yes it's better but we cannot close the Select.
Also can you remove the Console pollution ? There are plenty of plugin with webpack/vite to remove them in prod build
Thanks
![image](https://github.com/laravel/nova-issues/assets/9505463/c82826b0-1437-45b5-88f1-9ad0205afdff)

**Comment by crynobone** [comment]
> yes it's better but we cannot close the Select.

Please provide video of this.

**Comment by meyer59** [comment]
[screen-capture (11).webm](https://github.com/laravel/nova-issues/assets/9505463/28a58d49-7272-4a18-9550-79a65fff35fe)

**Comment by crynobone** [comment]
![CleanShot 2024-02-28 at 10 34 27](https://github.com/laravel/nova-issues/assets/172966/d8d7169d-e985-4ad6-a935-8545597fe40d)

**Comment by meyer59** [comment]
That's weird. I converted and updated the comment with an mp4 file.

**Comment by crynobone** [comment]
![image](https://github.com/laravel/nova-issues/assets/9505463/c82826b0-1437-45b5-88f1-9ad0205afdff)

This code was removed on `v4.32.10`, are you sure you're on the latest version?

**Comment by meyer59** [comment]
My bad, i forgot the` nova:publish` command. Now the console is cleared but the Select still doesn't close, as shown in the video.

**Comment by meyer59** [comment]
Hey
I don't know if it's related to the fix but the Select doesn't work anymore.
Keeps open, cannot select a value nor search.
![image](https://github.com/laravel/nova-issues/assets/9505463/a58fd2a5-1336-43e8-b569-e59c74022029)


Nova v.4.32.16
