### ISSUE TITLE
Select all checkbox disappeared

### ISSUE THREAD

**Issue by tommiekn** [laravel/nova-issues#6108]
- Laravel Version: 9.52.16
- Nova Version: 4.32.10
- PHP Version: 8.2

### Description:
The 'Select All' checkbox in all tables disappeared while upgrading from 4.27.13. to 4.32.10

### Detailed steps to reproduce the issue on a fresh Nova installation:
![Screenshot 2023-12-15 at 11 57 04 AM](https://github.com/laravel/nova-issues/assets/24386363/cbb663b8-afdd-4393-9eb4-d93493ee2667)
there is no more checkbox to select all records

@crynobone just wanted to add, i still had this issue prior to the upgrade:
https://github.com/laravel/nova-issues/issues/5925

and after the upgrade, on top of the select all checkbox disappearing, I have this issue too:
https://github.com/laravel/nova-issues/issues/6088

As I see you are unable to reproduce these issues, I would ask you if you can help us debug what we are seeing, as multiple users clearly have the same issue.
I am assuming that this may be due to being using Nova 3.x and then upgrading 4.0, as you are testing a clean 4.x you prob don't see these issues, maybe something hasn't been upgraded correctly or there was something missing in the update docs or something.

I have been reading over and over the upgrade guide to see if I have missed anything, but it doesn't seem I have.

**Comment by davidhemphill** [comment]
Respectfully, without the ability to replicate this on a fresh instance of Nova, there's no real way we can start to diagnose your issues. There isn't enough information in your bug reports to work with.

I encourage you to spend some time replicating these issues in a new install so we can get to work fixing any issues that may exist.

**Comment by superuser-me** [comment]
@tommiekn did you found the solution of this issue?

**Comment by tumainimosha** [comment]
Had a similar issue and downgrading to 4.27.13 fixed it for me
