### ISSUE TITLE
filterable() in fields doesnt show any filter

### ISSUE THREAD

**Issue by tommiekn** [laravel/nova-issues#6109]
Laravel Version: 10.37.3
Nova Version: 4.32.10
PHP Version: 8.2

### Description:
The Fields that were set as filterable() are not showing up anymore in the filter modal.
The only filter that shows is the "Per page" one.

![Screenshot 2023-12-15 at 1 37 27 PM](https://github.com/laravel/nova-issues/assets/24386363/ef49c935-9cbf-4575-9e5a-2f6805120628)

### Detailed steps to reproduce the issue on a fresh Nova installation:

Add filterable() to any field:
Text::make('Delivery Status', 'deliveryStatus')->sortable()->filterable(),

Check if the Field is actually filterable in the filter modal.

**Comment by davidhemphill** [comment]
Respectfully, without the ability to replicate this on a fresh instance of Nova, there's no real way we can start to diagnose your issues. There isn't enough information in your bug reports to work with.

I encourage you to spend some time replicating these issues in a new install so we can get to work fixing any issues that may exist.
