### ISSUE TITLE
Laravel Nova translatable

### ISSUE THREAD

**Issue by EmanueleCoppola** [laravel/nova-issues#611]
What if I want to let users choose their interface language by clicking a link?
Something like http://mysite.it/it/nova/login, http://mysite.it/en/nova/login and http://mysite.it/nova/login for default language?

**Comment by dillingham** [comment]
Maybe utilize [sub-domain routing ](https://laravel.com/docs/5.7/routing#route-group-sub-domain-routing) for that.

en.example.com / es.example.com => set session variable

**Comment by dillingham** [comment]
```php
Route::get('/{locale}/login', function(){
    
    App::setLocale($locale);

    return redirect()->route('nova.login');
});
```

**Comment by davidhemphill** [comment]
Another way to approach this is by having a `locale` column on the `User` and placing this in the `boot` method of your `NovaServiceProvider`.

```php
Nova::serving(function (ServingNova $event) {
    $this->app->setLocale($event->request->user()->locale);
});
```

**Comment by zek** [comment]
What about putting a selectbox next to avatar and username on the right corner?

**Comment by h-zone** [comment]
> 
> 
> What about putting a selectbox next to avatar and username on the right corner?
You will need to serve this selectbox.
I an not found any correct solution. Only crutches via tool and hardcoding.
