### ISSUE TITLE
Currency Field: Incorrect sorting

### ISSUE THREAD

**Issue by whisust** [laravel/nova-issues#6112]
- Laravel Version: 10.37.3
- Nova Version: 4.32.10
- PHP Version: ^8.1

### Description:

Sorting made by a Currency field linked to a double(13, 4) field in DB sorts by string value and not numeric value.

```
public function fields(NovaRequest $request) {
    return [
        Currency::make('Amount', 'amount')
                ->currency('EUR')
                ->sortable(),
    ]
}

```

![Capture d’écran 2023-12-15 à 18 35 24](https://github.com/laravel/nova-issues/assets/22323709/4506dc3a-8713-4f9f-9419-d1f573971b9b)
![Capture d’écran 2023-12-15 à 18 35 13](https://github.com/laravel/nova-issues/assets/22323709/4f6cd92d-977f-4098-94eb-6229c500ecf5)

**Comment by crynobone** [comment]
Ordering SQL is done directly at Eloquent query layer, see `Laravel\Nova\PerformsQueries::applyOrderings()` method.
