### ISSUE TITLE
filters not shown

### ISSUE THREAD

**Issue by mshtroylab** [laravel/nova-issues#6116]
- Laravel Version: 10
- Nova Version: 4.32.11
- PHP Version: 8.2

### Description:

in version 4.32.6 resource filters work fine
but in 4.32.11 all filters have hidden

### Detailed steps to reproduce the issue on a fresh Nova installation:
1- add filter to any resource
2- try to use this filter

![Screenshot_5](https://github.com/laravel/nova-issues/assets/135962688/393898e7-da57-429b-988c-cfa8834aad3e)
![Screenshot_4](https://github.com/laravel/nova-issues/assets/135962688/0e3195bf-d06d-4a40-b340-9d250b36de7d)

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by superuser-me** [comment]
@crynobone please check this carefully,
it's broken in between 4.32.7 and 4.32.6,
in 4.32.6 it was working for me,
i have manually tested one by one nova versions to check which version has introduced this bug,
i found 4.32.7 is the one.

i have reported this at first and now we already 2 more similar issues,
[https://github.com/laravel/nova-issues/issues/6109](https://github.com/laravel/nova-issues/issues/6109)
[https://github.com/laravel/nova-issues/issues/6093](https://github.com/laravel/nova-issues/issues/6093)
[https://github.com/laravel/nova-issues/issues/6116](https://github.com/laravel/nova-issues/issues/6116)

**Comment by davidhemphill** [comment]
"Create a custom filter and use it" is not 'detailed steps to reproduce'.

To diagnose and fix issues, we need to be able to reproduce them. Having detailed bug reports, and ideally, a reproduction repository is the best way to help us.

When you can provide a reproducible example on a fresh instance of Nova, we'd love to take a look and work towards a resolution!

**Comment by jeffcaulfield-morphsites** [comment]
I was going to attach a new sample project with a single "Email Verified" Yes/No filter on the User resource, which was essentially all I needed to reproduce this issue locally yesterday… except that now it's working (as of today). I un-pinned the actual project I'm working on from 4.32.6 and it also works with no other changes (both on 4.32.10 and 4.32.11).

The only thing I can think of is that some of the assets were somehow cached in a broken state. 🤷‍♂️

**Comment by superuser-me** [comment]
@jeffcaulfield-morphsites  is there any other things which you have noticed in broken state?
i removed cached assets, but i am still seeing the  lens icon in a resource with zero lenses.

**Comment by jeffcaulfield-morphsites** [comment]
Sorry @superuser-me I really have no idea. I was, however, referring to browser caching of those assets rather than the assets themselves. Sorry if that doesn't help.

**Comment by NorthNick** [comment]
I also had this problem and tracked it down to the [gobrightspot/nova-detached-actions](https://github.com/gobrightspot/nova-detached-actions) package, which has sadly been abandoned. Replacing it with the [datomatic/nova-detached-actions](https://github.com/datomatic/nova-detached-actions) fork fixed both the missing filters and incorrectly appearing lens menu problems. Some button restyling was needed, but otherwise it's a straight swap.
