### ISSUE TITLE
Encountering `this.$refs.searchable.close is not a function` Error When Filtering Relationships on Index Page

### ISSUE THREAD

**Issue by mostafaznv** [laravel/nova-issues#6118]
- Laravel Version: 10.38.0
- Nova Version: 4.32.11
- PHP Version: 8.3.0
- Database Driver & Version: Mysql 8.0.33
- Operating System and Version: MacOS 14.2 
- Browser type and version: Google Chrome 120.0.6099.109

### Description:
I'm facing an issue with `filterable`/`searchable` relationships in my Nova resources.
These fields work fine when I want to `create`/`update` an item on the add/edit pages. **However, when I attempt to filter results on the index page, the filter box crashes, and I receive a console error.**

<br />
<br />

**Resource Fields:**
![screenshot](https://github.com/laravel/nova-issues/assets/7619687/33a7a279-9dc3-438b-ab07-d83db5e456df)

**Filters (Crashed State):**
![image](https://github.com/laravel/nova-issues/assets/7619687/1c947042-463d-44c0-a8ba-a3b5e5c437e5)

**Console Error:**
![Screenshot 1402-09-29 at 1 37 32 in the afternoon](https://github.com/laravel/nova-issues/assets/7619687/cb69bb02-9d3f-4726-a458-6ba0803d72ed)

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.

**Comment by mostafaznv** [comment]
Apologies for the delay.
I've recreated the issue with additional information. You can find it here:

https://github.com/laravel/nova-issues/issues/6189
