### ISSUE TITLE
Multiple 'canRun' callbacks do not work in the UI

### ISSUE THREAD

**Issue by nbejansen** [laravel/nova-issues#6124]
- Laravel Version: 10.38.1
- Nova Version: 4.32.11
- PHP Version: 8.1
- Database Driver & Version: MySQL v8
- Operating System and Version: Ubuntu 22.04 LTS
- Browser type and version: Brave & Chrome

### Description:

When you define two actions on a resource with a `canRun` callback, both of which return `false` the second action is not grayed out.

<img width="289" alt="image" src="https://github.com/laravel/nova-issues/assets/20165378/44f47d7d-0702-4263-9da0-0de31e9c591f">

### Detailed steps to reproduce the issue on a fresh Nova installation:

```php
OpenTeamInOpenproviderNovaAction::make()
    ->canRun(function (NovaRequest $request, \App\Models\Team $team) {
        return false;
    })->onlyOnDetail(),

SyncTeamToOpenproviderNovaAction::make()
    ->canRun(function (NovaRequest $request, \App\Models\Team $team) {
        return false;
    })->onlyOnDetail(),
```

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍

**Comment by nbejansen** [comment]
Thanks!
