### ISSUE TITLE
canRun() method disable in the UI only first action from the array of actions

### ISSUE THREAD

**Issue by sunnydesign** [laravel/nova-issues#6127]
- Laravel Version: 9.52.16
- Nova Version: v4.32.11 (Silver Surfer)
- PHP Version: 8.1.16
- Database Driver & Version: mysql  8.0
- Operating System and Version: Ubuntu 22.04.1 LTS
- Browser type and version: Mozilla Firefox 119.0.1 (64)
- Reproduction Repository: https://github.com/sunnydesign/nova

### Description:
When we have more than one action and want to disallow all of them and disable in the UI by `canRun()` method, in the UI will disable only first action.

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Create two actions and disallow both of them (return `false` from the `canRun` callback) :

```
    public function actions(NovaRequest $request)
    {
        return [
            resolve(FirstAction::class)
                ->canRun(fn ($request, $building) => false),
            resolve(SecondAction::class)
                ->canRun(fn ($request, $building) => false),
        ];
    }
```

2. See result.
![Peek 2023-12-22 12-15](https://github.com/laravel/nova-issues/assets/36501326/359ebf21-c247-4da5-be89-148e4b2e75c2)

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
