### ISSUE TITLE
uniqueField not working in Repeater Fields ​on HasMany Preset 

### ISSUE THREAD

**Issue by zzzet** [laravel/nova-issues#6128]
- Laravel Version: v10.33.0
- Nova Version: ~4.32.6
- PHP Version: 8.2.12

### Description:
[Repeater Fields](https://nova.laravel.com/docs/resources/repeater-fields.html#repeater-fields) are still in Beta as per the documentation. An issue has been identified in the [HasMany Preset](https://nova.laravel.com/docs/resources/repeater-fields.html#hasmany-preset) code block.

Code in Laravel\Nova\Fields\Repeater\Presets\HasMany:
```php
/**
 * Delete missing relations.
 *
 * @param  string  $attribute
 * @param  \Illuminate\Database\Eloquent\Model  $model
 * @param  \Illuminate\Support\Collection  $repeaterItems
 * @param  mixed  $uniqueField
 * @return void
 */
public function deleteMissingRelations(string $attribute, Model $model, Collection $repeaterItems, $uniqueField): void
{
    /** @var \Illuminate\Database\Eloquent\Relations\HasMany $relation */
    $relation = $model->{$attribute}();

    $availableItems = $repeaterItems->map(function ($item) use ($uniqueField) {
        return $item['fields'][$uniqueField];
    })->all();

    $deletableIds = $relation->pluck($uniqueField)
        ->reject(function ($id) use ($availableItems) {
            return in_array($id, $availableItems);
        });
 
    if ($deletableIds->isNotEmpty()) {
        $model->{$attribute}()->whereKey($deletableIds)->delete();
    }
}
 ```

The `\Laravel\Nova\Fields\Repeater`:
```php
/**
 * Determine if the field collection contains an ID field.
 */
protected function fieldsContainsIDField(FieldCollection $fields): bool
{
    return $fields->contains(function (Field $field) {
        return $field instanceof ID && $field->attribute === $this->uniqueField
            || $field instanceof Hidden && $field->attribute === $this->uniqueField;
    });
}
```
The problem lies in the fact that the uniqueField is not always the primary key, causing issues during the delete operation.

In the `deleteMissingRelations` function, I tested with this for my local fix:
```
if ($deletableIds->isNotEmpty()) {
   $model->{$attribute}()->whereIn($uniqueField, $deletableIds)->delete();
}
```

### Detailed steps to reproduce the issue on a fresh Nova installation:

To reproduce the issue on a fresh Nova installation, follow the steps outlined in the documentation for [Upserting Repeatables Using Unique Fields](https://nova.laravel.com/docs/resources/repeater-fields.html#upserting-repeatables-using-unique-fields).

Note: Further testing may be required to confirm its effectiveness.

**Comment by crynobone** [comment]
This has been fixed and will be available on the next release.
