### ISSUE TITLE
Command clicking View icon opens multiple tabs

### ISSUE THREAD

**Issue by pb30** [laravel/nova-issues#6133]
- Laravel Version: 10.38.2
- Nova Version: 4.32.11
- PHP Version: 8.1.4
- Database Driver & Version: MariaDB 10.5
- Operating System and Version: macOS 14.2.1 (23C71)
- Browser type and version: Safari 17.2.1 (19617.1.17.11.12)
- Reproduction Repository: https://nova-demo.laravel.com/nova/resources/events

### Description:

Command + Click the View (eyeball) icon on a row and it opens two tabs: One with the row detail, and another of the same listing page you are on

### Detailed steps to reproduce the issue on a fresh Nova installation:

Happens as described above on Nova demo https://nova-demo.laravel.com/nova/resources/events

**Comment by davidhemphill** [comment]
Duplicate of #6126
