### ISSUE TITLE
On the details page, the authorizedToRun of the Action is not all called

### ISSUE THREAD

**Issue by lexitack** [laravel/nova-issues#6134]
- Laravel Version: 10.39.0
- Nova Version: 4.32.11
- PHP Version: 8.3

### Description:
function availableActionsOnDetail in \Laravel\Nova\ResolvesActions
```        return $this->resolveActions($request)
                    ->authorizedToSeeOnDetail($request)
                    ->each->authorizedToRun($request, $this->resource)
                    ->values();
```
echo in \Illuminate\Support\Traits\EnumeratesValues:
```
    public function each(callable $callback)
    {
        foreach ($this as $key => $item) {
            if ($callback($item, $key) === false) {
                break;
            }
        }

        return $this;
    }
```
So, when you have multiple actions, if the authorizedToRun in the preceding actions returns false, the authorizedToRun in the following actions does not take effect.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
