### ISSUE TITLE
Actions dropdown styles overwritten

### ISSUE THREAD

**Issue by does1tmatter** [laravel/nova-issues#6135]
Responsive action dropdown class `md:hidden` being overwritten by `flex`
![image](https://github.com/laravel/nova-issues/assets/90624105/286824db-17be-4f07-8fa9-9593c8c5cb3f)
(screenshot was taken in 1300px width window)

Nova version v4.32.11

**Comment by davidhemphill** [comment]
The `flex` class is coming from a third-party package, not from Nova itself.
