### ISSUE TITLE
Display related on attach interface

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#614]
v1.0.19

Displaying the related resource that is being attached would be really intuitive 

![attach-account](https://user-images.githubusercontent.com/29180903/45799009-058da100-bc7a-11e8-8f40-3675680b11d5.png)

nova/resources/`users/3/`attach/accounts?viaRelationship=accounts&polymorphic=0

| before | after 
|  ------- | ----- 
![attach-account-before](https://user-images.githubusercontent.com/29180903/45798897-94e68480-bc79-11e8-9cfd-996df9ee200f.png) | ![attach-account](https://user-images.githubusercontent.com/29180903/45798900-9912a200-bc79-11e8-8a5c-4f81f23aad46.png)

I don't think this would impede on the option to one day use this component in a modal either

It is clearer, to me atleast, that you're attaching brian to an account

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by crynobone** [comment]
The feature has been added to v3.21.0
