### ISSUE TITLE
BelongsTo Field Authorization

### ISSUE THREAD

**Issue by tschmidiger** [laravel/nova-issues#6143]
- Laravel Version: 10.40.0
- Nova Version: 4.32.11
- PHP Version: 8.2.14

### Description:
The authorize method of Laravel\Nova\Fields\BelongsTo does not check the viewAny policy for the related resource anymore. In previous Nova versions (e.g. 3.30.0) this check has been performed:

```
public function authorize(Request $request)
{
    return $this->isNotRedundant($request) && call_user_func(
        [$this->resourceClass, 'authorizedToViewAny'], $request
    ) && parent::authorize($request);
}
```

In which Nova version was this removed and why?

**Comment by crynobone** [comment]
This was added in Laravel Nova 4 and complies with normal Resource Controller policy: https://laravel.com/docs/10.x/authorization#authorizing-resource-controllers
