### ISSUE TITLE
Trix Field - 404 error while upload attachment with URL /nova-api/nova-settings/trix-attachment/{field}

### ISSUE THREAD

**Issue by arasan-goaugment** [laravel/nova-issues#6145]
- Laravel Version: 7.30.6
- Nova Version: 3.30.0
- PHP Version: 7.4.33
- Database Driver & Version: MySQL
- Operating System and Version: Ubuntu - AWS
- Browser type and version: Chrome120.0
- Reproduction Repository:###

### Description:
POST method route is not found in routes list for `nova-api/nova-settings/trix-attachment/{fieldName}` 

### Detailed steps to reproduce the issue on a fresh Nova installation:
Added the below code in `app/Providers/NovaServiceProvider.php`

```
\OptimistDigital\NovaSettings\NovaSettings::addSettingsFields([
            Tabs::make('Site Settings', [
                Tab::make('Dealer Alert', [
                    Boolean::make('Dealer Alert Enabled', 'dealer_alert_enabled'),
                    RadioButton::make('Dealer Alert Style', 'dealer_alert_type')
                        ->options([
                            'announcement' => 'Announcement (blue)',
                            'warning' => 'Warning (yellow)',
                            'error' => 'Error (red)',
                        ])
                        ->stack()
                        ->default('announcement')
                        ->marginBetween(50),
                    Trix::make('Dealer Alert Message', 'dealer_alert_message')->withFiles('public')->withMeta(['extraAttributes' => [
                        'data-has-upload' => 'true']
                    ])->alwaysShow(),
                ])
            ]),
        ], [
            'dealer_alert_enabled' => 'boolean',
        ]);
```
The above code gives 404 error while uploading document like below.
![Beneteau-Git-Ref](https://github.com/laravel/nova-issues/assets/89513999/cefdfd82-c585-4dc0-87e5-0e3c040a1f11)

URL is not found for POST method in the route list by doing `php artisan route:list` but can see the URL for DELETE method like below image
![Beneteau-route-Git-Ref](https://github.com/laravel/nova-issues/assets/89513999/a959c47e-1658-4e1d-92f1-13c05f8d2313)

I don't know what is the issue here for the route is not generating for attachment POST method and what to do to resolve the issue. Kindly help me to fix this. Thanks in advance

**Comment by crynobone** [comment]
Hey there,

Unfortunately, we don't support this version of the Laravel Nova anymore. 

Thanks!
