### ISSUE TITLE
Laravel\Nova\Metrics\ValueResult wrong PHPdoc type of $format param

### ISSUE THREAD

**Issue by trippo** [laravel/nova-issues#6146]
- Laravel Version: 10.40.0
- Nova Version: 4.32.11
- PHP Version: 8.3

### Description:
On `Laravel\Nova\Metrics\ValueResult` class the function `format` must accept an `array|string $format` param
```php
/**
 * Set the metric value formatting.
 *
 * @param  string  $format
 * @return $this
 */
public function format($format)
    {
        $this->format = $format;

        return $this;
    }
```

This is documentation about the `format` method
<img width="493" alt="image" src="https://github.com/laravel/nova-issues/assets/497169/e1291497-1ac4-4c32-8b8a-34ce5177f03b">

**Comment by brayann** [comment]
+1 on this. PHPStan is complaining about me passing an array to the `format` method.
