### ISSUE TITLE
File cannot prune in repeater

### ISSUE THREAD

**Issue by edmondtham** [laravel/nova-issues#6153]
- Laravel Version: 10.38.1
- Nova Version: 4.32.11
- PHP Version: 8.1
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Detailed steps to reproduce the issue on a fresh Nova installation:

FIle::make('File', 'file')->prunable(),

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
