### ISSUE TITLE
canRun() only disables the first action of the list

### ISSUE THREAD

**Issue by salvisb** [laravel/nova-issues#6154]
- Laravel Version: 10.40.0
- Nova Version: 4.32.11
- PHP Version: 8.2
- Browser type and version: Google Chrome Version 120.0.6099.216 (Official Build) (arm64)

### Description:
Let's say I have three actions and all of them have **canRun()** defined on them with a return value of "false". canSee() is not defined on any of them. The first issue is that on the detail view only the first action in the list is disabled (grayed out). Rest of the actions are displayed as active and are clickable. If I were to comment out the first action, then the next action will become disabled. And the second issue is in the index view, canRun() method instead of disabling actions hides them (i.e. behavior is not consistent with the detail view).

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Create three actions and register them on a resource.
2. Define canRun() method on all of them and make it return "false".
3. Observe the result in a detail and index view.

**Comment by salvisb** [comment]
Just in case https://github.com/jbumaniss/nova-app/pull/1/files

**Comment by crynobone** [comment]
This has been fix and will be available in the next release.
