### ISSUE TITLE
Action CanSee,but go 403

### ISSUE THREAD

**Issue by niunaiyi** [laravel/nova-issues#6155]
public function actions(NovaRequest $request)
    {
        return [
            (new OrderFinishAction())
                ->showInline()
                ->showOnDetail()
                ->canSee(function () {
                    $model =  $this->model();
                    if(in_array($model->status, ['stat1', 'stat2'])) {
                        return true;
                    }
                    return false;
                }),
        ];
    }
if have canSee function, the Action goto 403， if have not or only return true, it works.

**Comment by crynobone** [comment]
Such usage is not supported, you should use `canRun()` to validate against the model.

**Comment by niunaiyi** [comment]
i try it, just canRun return ture, still dont work.

**Comment by niunaiyi** [comment]
can you give me a sample?
