### ISSUE TITLE
Searchable Select field options do not appear when creating new resource

### ISSUE THREAD

**Issue by rklugman** [laravel/nova-issues#6162]
- Laravel Version: 10.41.0
- Nova Version: 4.32.11
- PHP Version: 8.2
- Database Driver & Version:
- Operating System and Version: Linux
- Browser type and version: Chrome 120.0.6
- Reproduction Repository: https://github.com/###/###

### Description:

There seems to be an issue with Select fields with option `searchable` but only when creating a new resource. When you initially drop down the select, no options are presented even though there are options. Pressing enter selects the first available option and thereafter options are visible. I can see from inspecting the DOM, that elements are there, but they just don't appear.

![2024-01-22 15 25 32](https://github.com/laravel/nova-issues/assets/40756947/f779703d-dc45-4900-83a0-37380c0ccbfd)

### Detailed steps to reproduce the issue on a fresh Nova installation:
```
Select::make('Some field', 'some_field')
    ->filterable()
    ->searchable()
    ->options(['value1', 'value2'])
```

**Comment by crynobone** [comment]
Unable to reproduce the issue with latest version, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by nirav-arsenaltech** [comment]
I’m facing the same issue: When we select 'No' for 'Apply to Shipping' and save, the system doesn't retain that information. Although the value is saved correctly, it doesn't display the 'No' option after saving, se below attachment

https://d.pr/v/3AYgxn
