### ISSUE TITLE
Policy is evaluated twice when running actions

### ISSUE THREAD

**Issue by Timisorean** [laravel/nova-issues#6167]
- Laravel Version: 10.42.0
- Nova Version: 4.32.11
- PHP Version: 8.2

### Description:

```php
(new CancelBooking)
    ->confirmButtonText('Cancel')
    ->canSeeWhen('cancel', $this),
```

We using `canSeeWhen` to restrict which actions can bee seen/run for users. But we encountered an issue getting 403 when calling the action. It appears that the policy gets called twice with different models. The first call is done with the correct model object that is loaded from the database. Therefore the user can see and run the action. The second call has an empty model object with only default attributes that is not loaded from the database. Meaning that the `exists` attribute is set to false. We fixed it by just checking the `exists` attribute every policy method. But that is an tedious solution. Is this expected behavior.

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
