### ISSUE TITLE
After conposer install getting Javascript erros in the browser console and nova login page is blank with just background color.

### ISSUE THREAD

**Issue by Meeshalk** [laravel/nova-issues#6169]
- Laravel Version: 9.45.1
- Nova Version: 4.9.5
- PHP Version: 8.1
- Database Driver & Version: MySQL
- Operating System and Version: macOs 14.3
- Browser type and version: chrome.#
- Reproduction Repository: https://github.com/###/###

### Description:
After installing laravel/pint as a dev dependency. It started happing. But the reason I feel is `php artisan nova:publish` this command which runs after every composer update.

![image](https://github.com/laravel/nova-issues/assets/33943135/73476f85-d4f9-4a82-b23a-74f8caffaa4c) - now

![image](https://github.com/laravel/nova-issues/assets/33943135/6cd25ca1-e757-4661-8ccf-abd596ac9c02) - earlier

**Comment by MammutAlex** [comment]
@Meeshalk I see that this issue was closed due to inactivity. I'm encountering a similar problem. Could you please provide an update and let me know if there has been any progress in resolving the issue?
