### ISSUE TITLE
Resource group title OTHER is shown if elements are not grouped and $displayInNavigation = false

### ISSUE THREAD

**Issue by macolson** [laravel/nova-issues#618]
If all resources have been grouped but a single resource definition has no ```$group``` definition and has set ```public static $displayInNavigation = false;``` the OTHER resource group title is shown in the navigation tree.

![image](https://user-images.githubusercontent.com/42863360/45810097-21b92e80-bcca-11e8-9bd3-7ab57700e094.png)

Nova version: v1.0.19

**Comment by bonzai** [comment]
#612

**Comment by sabid** [comment]
The same problem

**Comment by alexbowers** [comment]
this issue has been confirmed:

To reproduce:

```
public static $displayInNavigation = false;
```

in one resource and 

```
public static $group = 'Group name';
```

in the other

**Comment by bernhardh** [comment]
Same here. Not fixed yet, but I have several ressources and all in groups, but empty "other" is show. @hotmeteor fix is not working for me on v1.1.3. Code:

```php
abstract class Resource extends \Laravel\Nova\Resource
{
    public static $group = '';
}
```

And my only Ressource:

```php
class City extends Resource
{
    public static $model = 'App\Models\City';
    public static $group = "Stadtbereich";

   public function fields(Request $request)
    {       
        return [
            ID::make()->sortable(),
        ];
    }
}
```

**Comment by m2de** [comment]
Agree this is an issue especially as some packages/tools could include resources with navigation set to false which don't use the Applications base resource.

**Comment by nasrulhazim** [comment]
> Agree this is an issue especially as some packages/tools could include resources with navigation set to false which don't use the Applications base resource.

Yerp. Having the same issue. Even if you have Nova resource, which has navigation disabled, the `Other` menu will appear.

**Comment by Etmolf** [comment]
As we have access to the partial, there is an easy fix which works globally for all resources:

edit your `resources/views/vendor/nova/resources/navigation.blade.php`

`should be around line 10`
```
@foreach(Nova::groupedResources(request()) as $group => $resources)

// filter resources based on $displayInNavigation
// if no resource in the group is displayed, the collection will be empty
@php
    $resources = $resources->filter(function($resource) {
	return $resource::$displayInNavigation;
    });
@endphp

@if (count($resources) > 0)
```
Nova should do the same in `Nova::groupedResources` - if it does, the fix is obsolete.

**Comment by mhdHussein** [comment]
Hi there,
I have the same problem
