### ISSUE TITLE
Nova License Purchasing Page throws 500 error

### ISSUE THREAD

**Issue by Fijvect** [laravel/nova-issues#6198]
- Laravel Version: N/A
- Nova Version: N/A
- PHP Version: N/A
- Database Driver & Version:
- Operating System and Version: Windows 11
- Browser type and version:  Tried on both Chrome and Firefox, latest versions.
- Reproduction Repository: N/A

### Detailed steps to reproduce the issue on a fresh Nova installation: N/A
![image](https://github.com/laravel/nova-issues/assets/12387268/0c61285e-b94a-4240-a577-d87e3134b127)

**Comment by crynobone** [comment]
Hi there, 

This should be fixed now, sorry for the inconvenience.
