### ISSUE TITLE
Change per page don't reset current page

### ISSUE THREAD

**Issue by Malezha** [laravel/nova-issues#62]
May be no data for selected page.

**Comment by taylorotwell** [comment]
Please explain your issue more thoroughly with screenshots.

**Comment by jarda256sparktech** [comment]
@taylorotwell  if you have pagination set to 25 and you are on page 10. And then you switch to 100 items per page. You have no results, because page not resets to 1 but stays on 10.

**Comment by ryanpaulfyfe** [comment]
I'm having this same issue. For example if I select to filter to '100 per page', it doesn't update and stays with the default 25 listed.

For example:

/nova/resources/users?users_per_page=100

--

![Screenshot from 2019-04-09 14-03-08](https://user-images.githubusercontent.com/329825/55827651-493de000-5ad0-11e9-9a2f-0e2ba0e1b904.png)

--

![Screenshot from 2019-04-09 14-03-17](https://user-images.githubusercontent.com/329825/55827652-4cd16700-5ad0-11e9-96e7-20ac3e3c6d84.png)

**Comment by turzaizsolt** [comment]
I have the same issue as @ryanpaulfyfe
