### ISSUE TITLE
Format output value for Metric

### ISSUE THREAD

**Issue by danielbrodin** [laravel/nova-issues#620]
You can easily change the label, but I want to change the output of the value. In my case I have a bunch of media files where I output the total size of all files, but seeing it in bytes isn't that valuable for many users so I would like to transform it into something more readable.

**Comment by dkulyk** [comment]
@bonzai Has your PRs fixed it?

**Comment by bonzai** [comment]
Yes, but it's not merged yet.

**Comment by dkulyk** [comment]
This has been fixed and will be included in the next release.

**Comment by TiGR** [comment]
@dkulyk is there an easy workaround for this?
