### ISSUE TITLE
BelongsTo Form field visual regression

### ISSUE THREAD

**Issue by mrleblanc101** [laravel/nova-issues#6201]
- Nova Version: 4.32.12

### Description:

Resource:
```php
BelongsTo::make(__('Service'), 'service'),
```

Model:
```php
public function service()
{
    return $this->belongsTo(Service::class);
}
```

v4.32.11

<img width="1800" alt="Screenshot 2024-02-14 at 9 22 26 PM" src="https://github.com/laravel/nova-issues/assets/17392251/88519ac6-9a8b-429a-937c-f7ec9ff5d4f9">

v4.32.12

<img width="1800" alt="Screenshot 2024-02-14 at 9 24 03 PM" src="https://github.com/laravel/nova-issues/assets/17392251/0814062a-9d32-491d-bc2b-89bd74b0173e">

**Comment by mrleblanc101** [comment]
Initially it display a searchable dropdown, clear the value and it become a native select.
![2024-02-14 21 27 22](https://github.com/laravel/nova-issues/assets/17392251/323fe03e-ae60-4193-963b-6cf9ab0360a9)

**Comment by mrleblanc101** [comment]
This happen when creating via a relatable resource, I have `public static $displayInNavigation = false;` set.
If I change `public static $displayInNavigation = true;` and create from the Resource listing, I don't have this bug.

**Comment by crynobone** [comment]
> Initially it display a searchable dropdown, clear the value and it become a native select.

Put this as separate issue as it's not a regression from 4.32.12

**Comment by mrleblanc101** [comment]
@crynobone No problem, but are you sure ? 🤔 
Clearly I had neither issue on 4.32.11

**Comment by mrleblanc101** [comment]
@filipposallemi Don't do that. They don't owe you anything. A CMS is not an easy thing to build, build your own if your not happy.
