### ISSUE TITLE
KeyValue Field visual bug

### ISSUE THREAD

**Issue by mrleblanc101** [laravel/nova-issues#6202]
- Nova Version: 4.32.12

### Description:

When the key is multiline, but the value is not, the value `<textarea>` height won't match with the key `<textarea>` height leaving a space of different color.
<img width="1800" alt="Screenshot 2024-02-14 at 11 39 28 PM" src="https://github.com/laravel/nova-issues/assets/17392251/6038f4fb-0e50-4b23-8713-c495c5060108">

**Comment by mrleblanc101** [comment]
Also, clicking the key field shows a focus ring.
<img width="1800" alt="Screenshot 2024-02-14 at 11 46 30 PM" src="https://github.com/laravel/nova-issues/assets/17392251/9bf0c399-6c87-45ac-b76e-f537bd770209">

Clickting the value field does not show a focus ring.
<img width="1800" alt="Screenshot 2024-02-14 at 11 46 39 PM" src="https://github.com/laravel/nova-issues/assets/17392251/7c313b8a-50a5-49c5-b569-9458233b3c7f">

**Comment by mrleblanc101** [comment]
Not stale

**Comment by crynobone** [comment]
Released with Laravel Nova 5.0.0

Feel free to open up a new issue if you're still experiencing this problem on the latest version.
