### ISSUE TITLE
BelongsTo field sometime shows as searchable even if not provided

### ISSUE THREAD

**Issue by mrleblanc101** [laravel/nova-issues#6203]
- Laravel Version: 4.32.12

### Description:

Initially it display a searchable dropdown, clear the value and it become a native select.

Resource:
```php
BelongsTo::make(__('Service'), 'service'),
```

Model:
```php
public function service()
{
    return $this->belongsTo(Service::class);
}
```

![2024-02-14 21 27 22](https://github.com/laravel/nova-issues/assets/17392251/323fe03e-ae60-4193-963b-6cf9ab0360a9)

**Comment by crynobone** [comment]
Create via relationship will show as searchable by default. An expected behaviour to allow cancelling the relationship by clicking `x` and redirect to create page (notice the breadcrumb changed).

**Comment by mrleblanc101** [comment]
@crynobone You are right, I just tested and I have the same behavior in 4.32.11, sorry for the confusion.
From what I understand you use a custom Select when you need to make a field searchable or to add the clear button.
I was wondering, why don't you use the custom Select all the time, but remove the search field if `searchable` is not set or `false` ? It would be more consistent then sometime using the browser native Select, but maybe I'm missing something.
