### ISSUE TITLE
The BelongsToMany field is not displayed on the edit form, but only on the detail (view) form

### ISSUE THREAD

**Issue by ay232** [laravel/nova-issues#6207]
- Laravel Version: 10.43.0
- Nova Version: 4.12
- PHP Version: 8.2.13
- Database Driver & Version: PostgreSQL v.14
- Operating System and Version: MacOS 13.5
- Browser type and version: Chrome: 121.0.6167.160 (Official Build) (arm64)
- Reproduction Repository: https://github.com/###/###

### Description:

The BelongsToMany field is not displayed on the edit form, but only on the detail (view) form. The documentation states that it should be displayed and it's even possible to invoke a method to display the "Create" button - "->showCreateRelationButton()".

### Detailed steps to reproduce the issue on a fresh Nova installation:
This code:
`BelongsToMany::make('Groups', 'groups', GroupOfBrand::class)`
does not display the field for selecting brand groups in the brand editing form, but only in the view form.

<img width="1768" alt="Screenshot 2024-02-15 at 13 59 56" src="https://github.com/laravel/nova-issues/assets/46033262/50dc420a-5971-47b1-9f83-f3a11d78a452">
<img width="1223" alt="Screenshot 2024-02-15 at 14 00 46" src="https://github.com/laravel/nova-issues/assets/46033262/d2959fe8-cea9-4cdf-8476-e55a3cadb996">

**Comment by crynobone** [comment]
Unable to reproduce the issue. Please upgrade to the latest version and try again.

**Comment by ay232** [comment]
It does no works! Can you show me video with this feature?

**Comment by ay232** [comment]
The BelongsToMany field is not displayed in the editing form even in a newly created project with the latest versions of Laravel and Nova.

**Comment by crynobone** [comment]
We have dusk tests covering this usage and not seeing anything outside the expected behaviour.

**Comment by ay232** [comment]
> We have dusk tests covering this usage and not seeing anything outside the expected behaviour.

please answer - should the BelongsToMany field be displayed on the edit form or only on the view form?
