### ISSUE TITLE
Select Field does not return a value on v4.32.12 (strict equality issue)

### ISSUE THREAD

**Issue by LTKort** [laravel/nova-issues#6211]
- Laravel Version: 10.44.0
- Nova Version: 4.32.12
- PHP Version: 8.3.0
- Database Driver & Version: MySQL
- Reproduction Repository: https://github.com/laravel/nova

### Description:
Since the update for v4.32.12, a Select field with options that uses an Integer as key is not returned as a valid selectedOption.
In the SelectField.vue there are some changes made with comparisons:
```diff
let selectedOption = find(
    this.currentField.options,
-     v => v.value == this.currentField.value
+     v => v.value === this.currentField.value
)
```
The key type (this.currentField.value) differs from the selected options key type (v.value), which causes an empty selectedOption. 
It looks like the selected value is compared as text vs number, while PHP sets the value as an integer.
The issue does not appear in v4.32.11

### Detailed steps to reproduce the issue on a fresh Nova installation:
Add a Select field to an Action, fill the with options ```$options = User::limit(5)->pluck("name", "id"); ``` (Array or Collection)
Run the action, the field value for the handle with be empty.

**Comment by filipposallemi** [comment]
@taylorotwell @davidhemphill shame

**Comment by LTKort** [comment]
@crynobone If I add a function to map the option values to a string, the Select field & strict equality seems to be working.

Example:
```js 
mappedOptions() {
  let mappedOptions = this.currentField.options.map(option => {
    return { label: option.label, value: `${option.value}` }
  })
  return Object.assign(this.currentField.options, mappedOptions)
},
```

Before: `{label: 'Lars', value: 1}`
After:  `{label: 'Lars', value: '1'}`

**Comment by filipposallemi** [comment]
The reality is that they are not using Nova at all otherwise they would have spot those issues immediately

**Comment by VenoM9078** [comment]
been 2 days, any update on this?
