### ISSUE TITLE
Metrics Bug after update to V4.32.12

### ISSUE THREAD

**Issue by massimodellarovere** [laravel/nova-issues#6215]
![image](https://github.com/laravel/nova-issues/assets/5731295/97b7b615-f2bd-4771-ad1d-8336252af653)

**Comment by rezawikan** [comment]
I also got this issue

**Comment by mnedoszytko** [comment]
i concur

<img width="431" alt="image" src="https://github.com/laravel/nova-issues/assets/2605478/43d937e1-a06a-4552-bc9c-30dcd0175b41">

**Comment by mnedoszytko** [comment]
4.32.13 did not solve the issue. i need to downgrade to .11 on production because of that
![image](https://github.com/laravel/nova-issues/assets/2605478/3be3ce3e-e253-41e6-8e48-876561b3b568)

**Comment by mnedoszytko** [comment]
4.32.13 did not solve the issue. I need to downgrade to .11 on production
![image](https://github.com/laravel/nova-issues/assets/2605478/26924e33-cb3f-4c22-b7e3-07e94db9969c)

**Comment by provydon** [comment]
I got this issue too

**Comment by daPhantom** [comment]
+1 same for me 

![Uploading Untitled.jpg…]()

**Comment by filipposallemi** [comment]
I have the same issue

**Comment by FrancoFourmantin** [comment]
Same issue here

<img width="533" alt="Screenshot 2024-02-21 at 17 03 25" src="https://github.com/laravel/nova-issues/assets/57300976/dd4af0e1-7cde-4a07-a3b2-3a52f47a65f9">
