### ISSUE TITLE
Peeking stuck in loading state after upgrading to 4.32.13

### ISSUE THREAD

**Issue by yzzhushu** [laravel/nova-issues#6219]
- Laravel Version: 10.44.0
- Nova Version: 4.32.13
- PHP Version: 8.2.8
- Database Driver & Version: SQLServer2019
- Operating System and Version: MacOS
- Browser type and version: Chrome121.0.6167.184
- Reproduction Repository: N/A

### Description:

Yesterday, I upgrade laravel-nova from version 4.32.9 to 4.32.13 by command: composer update.

Today, I discovered some abnormal phenomena.

1. class form-input-bordered is missing in app.css file
![WX20240219-163803](https://github.com/laravel/nova-issues/assets/17975215/f525694c-8079-4b31-95fb-1db0112280c7)

2. belongsTo peeking is abnormal
![WX20240219-163903](https://github.com/laravel/nova-issues/assets/17975215/56ff33d0-3f91-49ea-b57b-864b65396803)

**Comment by yzzhushu** [comment]
When peeking, it will get data from xxx/nova-api/{resource}/{id}/peek, now it doing nothing

**Comment by crynobone** [comment]
`form-input-bordered` was renamed to `form-control-bordered`. This doesn't fall under our public API so the changes is allowed in minor or patch releases.
