### ISSUE TITLE
[1.1.0] Form buttons are different

### ISSUE THREAD

**Issue by MarceauKa** [laravel/nova-issues#622]
<img width="1137" alt="capture d ecran 2018-09-20 a 19 13 10" src="https://user-images.githubusercontent.com/1665333/45835128-75973800-bd09-11e8-8aa6-1f4ef8883363.png">

**Comment by dillingham** [comment]
That's just you, likely due to a 3rd party stylesheet

**Comment by davidhemphill** [comment]
Nothing changed related to these buttons. Make sure you've updated your assets with `nova:publish --force`.
