### ISSUE TITLE
Search by multiple columns

### ISSUE THREAD

**Issue by luislpv22** [laravel/nova-issues#623]
Whenever you try to find f.e. a customer by his first name and last name you won't be able to find him if you type his full name, as you can only search by a single column at once, so I made this workaround to make it possible for non Scout users.

Sending an array of columns inside the search array:
`App\Nova\Customer`
```php
public static $search = [
    'id',
    'firstname',
    'lastname',
    'email',
    ['firstname', 'lastname']
];
```

It will concat all columns and compare it with the search term
`Laravel\Nova\PerformsQueries`
```php
protected static function applySearch($query, $search)
{
    return $query->where(function ($query) use ($search) {
        if (is_numeric($search) && in_array($query->getModel()->getKeyType(), ['int', 'integer'])) {
            $query->orWhere($query->getModel()->getQualifiedKeyName(), $search);
        }

        $model = $query->getModel();

        foreach (static::searchableColumns() as $column) {
            if (is_array($column)) {
                foreach ($column as $key => $col) {
                    $column[$key] = $model->qualifyColumn($col);
                }
                $concat = implode(", ' ', ", $column);
                $query->orWhereRaw("CONCAT(".$concat.") LIKE '%" . $search . "%'");
            } else {
                $query->orWhere($model->qualifyColumn($column), 'like', '%' . $search . '%');
            }
        }
    });
}
```

**Outputs before modification:**
- 'Taylor' => `Found`
- 'Otwell' => `Found`
- 'Taylor Otwell' => `Not found`

**Outputs after modification:**
- 'Taylor' => `Found`
- 'Otwell' => `Found`
- 'Taylor Otwell' => `Found`

It might be better done with an additional attribute called `$multipleSearch` with its own methods.

**Comment by brunogaspar** [comment]
Will require some minor tweaks, like allowing this to work on PgSQL using `ILIKE` instead of `LIKE` for example.

But, would be very nice to have this baked in somehow.

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by haneef5k** [comment]
Looking forward for this issue ?

**Comment by albalooshi** [comment]
@davidhemphill any plans to merge this feature?

**Comment by davidgabbay** [comment]
CONCAT is not available on SQL Server 2008

**Comment by davidgabbay** [comment]
could someone help how to do is without CONCAT ?
since CONCAT is not available on SQL Server 2008

**Comment by atymic** [comment]
Is there a reason this was closed?

**Comment by jbrooksuk** [comment]
@atymic we auto-close feature requests.

**Comment by matthewjumpsoffbuildings** [comment]
This is still a major issue and source of confusion.

If a table has a first_name and last_name, and someone in Nova searches for both first and last name, no results are returned... which leads them to think that there is no entry that matches.

**Comment by matthewjumpsoffbuildings** [comment]
The solution is so damn simple. 

In `Laravel\Nova\PerformsQueries`, in the `applySearch` method, replace this:
```php
foreach (static::searchableColumns() as $column) {
    $query->orWhere($model->qualifyColumn($column), $likeOperator, '%'.$search.'%');
}
```
with this:
```
$searchSplit = explode(" ", $search);
foreach (static::searchableColumns() as $column) {
    foreach ($searchSplit as $s) {
        $query->orWhere($model->qualifyColumn($column), $likeOperator, '%'.$s.'%');
    }
}
```

**Comment by matthewjumpsoffbuildings** [comment]
Here is an updated version of `applySearch` that works with https://github.com/TitasGailius/nova-search-relations as well, all you need to do is add this to your `Resource.php` file and searches behave in a sane manner

```php
protected static function applySearch($query, $search)
	{
		return $query->where(function ($query) use ($search) {
			$model = $query->getModel();

			$connectionType = $query->getModel()->getConnection()->getDriverName();

			$canSearchPrimaryKey = is_numeric($search) &&
									in_array($query->getModel()->getKeyType(), ['int', 'integer']) &&
									($connectionType != 'pgsql' || $search <= PHP_INT_MAX) &&
									in_array($query->getModel()->getKeyName(), static::$search);

			if ($canSearchPrimaryKey)
				$query->orWhere($query->getModel()->getQualifiedKeyName(), $search);

			$likeOperator = $connectionType == 'pgsql' ? 'ilike' : 'like';

			$searchSplit = explode(" ", $search);
			foreach ($searchSplit as $word)
			{
				
				$query->where(function($query) use ($word, $model, $likeOperator)
				{
					// normal column search
					foreach (static::searchableColumns() as $column) {
						$query->orWhere($model->qualifyColumn($column), $likeOperator, '%'.$word.'%');
					}

					// relationship column search
					foreach (static::searchableRelations() as $relation => $columns) {
						$query->orWhereHas($relation, function ($query) use ($columns, $word) {
							$query->where(static::searchQueryApplier($columns, $word));
						});
					}
				});

				
			}
		});
	}
```

**Comment by akki-io** [comment]
I was working on a project which has ~600k users and we wanted to search by name i.e. first_name + last_name. Ideally, we would have liked to use Scout but given the nature of the project, I build a small trait to handle this.

https://github.com/akki-io/laravel-nova-search

**Comment by temp1029** [comment]
I updated @matthewjumpsoffbuildings code to work with version 2.0.1 (maybe earlier?) of https://github.com/TitasGailius/nova-search-relations. Use it the same way, by placing it in Resource.php.

```
protected static function applySearch($query, $search)
{
    return $query->where(function ($query) use ($search) {
        $model = $query->getModel();

        $canSearchPrimaryKey = is_numeric($search) &&
                                in_array($model->getKeyType(), ['int', 'integer']) &&
                                ($model->getConnection()->getDriverName() != 'pgsql' || $search <= PHP_INT_MAX) &&
                                in_array($model->getKeyName(), static::$search);

        if ($canSearchPrimaryKey)
            $query->orWhere($query->getModel()->getQualifiedKeyName(), $search);

        $searchWords = explode(" ", $search);
        foreach ($searchWords as $word)
        {
            $query->where(function ($query) use ($word) {
                parent::applySearch($query, $word);
                static::applyRelationSearch($query, $word);
            });
        }
    });
}
```
