### ISSUE TITLE
Nova doesn't listen to the connection on the model

### ISSUE THREAD

**Issue by jamesblackwell** [laravel/nova-issues#6230]
- Laravel Version: 10.8
- Nova Version: 4.29.5
- PHP Version: 8.2
- Database Driver & Version: mysql / pgsql

### Description:

I have a model that uses a Postgres connection, whereas most use Mysql. When trying to save a resource Nova gives an error that the table doesn't exist because it's using the Mysql connection. 

### Detailed steps to reproduce the issue on a fresh Nova installation:

1) Install Nova
2) Set two database connections
3) Create a model that uses the non, default connection
4) Create nova resource for model in 3
5) Witness error when trying to save, since Nova uses default connection.

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by jamesblackwell** [comment]
I’ll try find some time to setup a repo for you.

Why were you unable to reproduce?

**Comment by jamesblackwell** [comment]
I've found the bug, it is with creationRules

```
Text::make('Slug')
                ->sortable()
                ->rules('max:255')
                ->creationRules('unique:pages'), // this line causes Nova to use at the default connection, rather than the connection specified by the model
```

**Comment by jamesblackwell** [comment]
Thanks, this fixes it: 

```
...
->creationRules('unique:App\Models\Page,slug')
```
