### ISSUE TITLE
zero-division issue

### ISSUE THREAD

**Issue by kpsabithgit** [laravel/nova-issues#6245]
- Laravel Version: 10+
- Nova Version: 4.32.15
- PHP Version: 8.30
- Database Driver & Version:
- Operating System and Version: Mac

"zero-division issue with Progress metrics" still exists even after it rectified by release v4.22.1 (Silver Surfer)

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)
