### ISSUE TITLE
Action::downloadURL does not download files

### ISSUE THREAD

**Issue by WillyReyno** [laravel/nova-issues#6249]
- Laravel Version: 10.46.0
- Nova Version: 4.32.15
- PHP Version: 8.3.2
- Database Driver & Version: MySQL 8.0
- Operating System and Version: Ubuntu 20.04
- Browser type and version: Chrome 121.0.6167.184

### Description:

I was using `Action::download` until now, but since it is deprecated I tried switching to `Action::downloadURL` which is now recommended. Unfortunately this version does not work and nothing is downloaded.

### Detailed steps to reproduce the issue on a fresh Nova installation:

* Create an action with `php artisan nova:action DownloadAction`
* Attach the action to a resource
* In the handle() method of the Action, add the following: 
```
return Action::downloadURL('test.png', 'https://nova.laravel.com/img/laravel-nova-mockup-light.png');
```
* On the resource index, trigger the action and nothing will happen (tested with png & zip files)

On the opposite, if you use the deprecated way, the file will be successfuly downloaded: 
```
return Action::download('https://nova.laravel.com/img/laravel-nova-mockup-light.png', 'test.png');
```

**Comment by richard-raadi** [comment]
Am running into this as well. Also Nova 4.32.15.

**Comment by msucevan** [comment]
Same here.

**Comment by crynobone** [comment]
Documentation has been updated to the correct usage.

Also using `Action::downloadURL()` is for "Static Actions" and not as "Action Responses"

**Comment by ekazda** [comment]
Is there an expected release date on this fix?
