### ISSUE TITLE
Joining a table to an indexQuery messes up primary table fields on resource list.

### ISSUE THREAD

**Issue by pedrodevoto** [laravel/nova-issues#625]
I have a `roles` table with a `level` field that I use to determine the level of permissions a user has. Naturally, every user is able to see every other user of the same level as them and above it. (So, a user with a role of level of 2 should be able to see every user with a role level of 2+)

I overrode the `indexQuery` method in the `User` resource to filter out users of a higher role than the role of the authenticated user. 

This is my method:
```PHP
    public static function indexQuery(NovaRequest $request, $query)
    {
        if ($request->user()->isAdmin()) {
            return $query;
        }
        return $query
            ->join('roles', 'roles.id', '=', 'users.role_id')
            ->where('roles.level', '>=', $request->user()->role->level);
    }
```

The problem is that the `roles` table also contains a field called `name`, so in the list of users, the `Name` column is populated with the role's name, instead of the user's name. 

I tried modifying the User's name field to `Text::make('Name', 'users.name')` but it didn't seem to work.

**Comment by bonzai** [comment]
Try to use `select()` method:
```php
return $query
	->select('users.*')
    ->join('roles', 'roles.id', '=', 'users.role_id')
    ->where('roles.level', '>=', $request->user()->role->level);
```

**Comment by pedrodevoto** [comment]
@bonzai That worked, thanks. Closing this, although I'm not sure if it is still a bug or not.

**Comment by jacob418** [comment]
> Try to use `select()` method:
> 
> ```
> return $query
> 	->select('users.*')
>     ->join('roles', 'roles.id', '=', 'users.role_id')
>     ->where('roles.level', '>=', $request->user()->role->level);
> ```

Give that man a beer!!
