### ISSUE TITLE
Download not working when there is multiple computed file fields

### ISSUE THREAD

**Issue by AEM5299** [laravel/nova-issues#6251]
- Laravel Version: 10.44
- Nova Version: 4.32.11
- PHP Version: 8.2
- Database Driver & Version: MySQL v8
- Operating System and Version: ubuntu:22.04
- Browser type and version: Firefox V124
- Reproduction Repository: 

### Description:
When there is multiple computed file fields on a resource, the download for **all** of them just download the first file field defined. 

They all seem to have the same key on the frontend (`computedField`), which might be the issue. I couldn't find a way to configure the keys manually.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Create a resource with 2 computed File fields with downloads enabled. Go to the resource page then try to download the **second** file. It will try to download the first instead.

**Comment by crynobone** [comment]
> They all seem to have the same key on the frontend (computedField)

This is the expected behaviour of Computed Field. You can't use this type of field to solve your requirements.
