### ISSUE TITLE
Date field must cast to 'date' in Eloquent model.

### ISSUE THREAD

**Issue by VaHHiLLiH** [laravel/nova-issues#6256]
- Laravel Version: 8.75
- Nova Version: 4.0
- PHP Version: 7.4
- Database Driver & Version: PostgreSql 11
- Operating System and Version: windows 10
- Browser type and version: google chrome 122.0.6261.95

### Description:
I can’t display the created module in the admin panel with Date fields. 
Here is the transformation array : 
protected $casts = [
        'date_start_season' => 'date',
        'date_end_season' => 'date',
    ];
Here are the fields created:
\Laravel\Nova\Fields\Date::make('date_start_season', 'date_start_season')
                ->rules('required', 'date'),

            \Laravel\Nova\Fields\Date::make('date_end_season','date_end_season')
                ->rules('required', 'date'),
 Here is the error :
 Date field must cast to 'date' in Eloquent model.

I don’t understand what I did wrong, please help)

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by VaHHiLLiH** [comment]
I found an error, I specified the casts array in the Nova resource, not in the model...
