### ISSUE TITLE
Action modal with BelongsTo searchable field causing freeze entire app

### ISSUE THREAD

**Issue by webard** [laravel/nova-issues#6257]
- Laravel Version: 10.47.0
- Nova Version: 4.32.16
- PHP Version: 8.2.16
- Database Driver & Version: Mysql  8.2.16
- Operating System and Version: MacOS 14.3.1
- Browser type and version: Chrome 122.0.6261.112

### Description:

Hello,

I have action class with one field that is searchable relation:
```php
class AssignPatronToLead extends Action
{
    /**
     * Perform the action on the given models.
     *
     * @param  Collection<int,\Illuminate\Database\Eloquent\Model>  $models
     * @return mixed
     */
    public function handle(ActionFields $fields, Collection $models)
    {
       // save logic
    }

    /**
     * Get the fields available on the action.
     *
     * @return array<mixed>
     */
    public function fields(NovaRequest $request)
    {
        return [
            BelongsTo::make('User', 'patron', User::class)
                ->searchable()
                ->required(),
        ];
    }
}
```

After triggering Action from resource, modal shows with opened search input and entire app just freeze. I cannot close modal, enter text to search input or do anything.

<img width="680" alt="image" src="https://github.com/laravel/nova-issues/assets/855788/582e00f6-004f-4c3a-a815-9ac97b91fcf6">

### Detailed steps to reproduce the issue on a fresh Nova installation:

- Create Action with some BelongsTo field that is searchable
- Trigger action from resource

**Comment by bmoex** [comment]
Same problem occurs with Select element (most likely same element underneath)

```php
Select::make('Example')
    ->searchable()
    ->options([
        '1' => 'abc',
        '2' => 'def',
        '3' => 'ghi',
    ]),
```
<img width="672" alt="Screenshot 2024-03-07 at 12 23 18" src="https://github.com/laravel/nova-issues/assets/2414665/1d4c4472-5d11-46d0-b9ac-c94c51466d5c">

Nothing is selectable
