### ISSUE TITLE
Text fields have different states, but looks exactly same

### ISSUE THREAD

**Issue by webard** [laravel/nova-issues#6258]
- Laravel Version: 10.47.0
- Nova Version: 4.32.16
- PHP Version: 8.2.16
- Database Driver & Version: Mysql  8.2.16
- Operating System and Version: MacOS 14.3.1
- Browser type and version: Chrome 122.0.6261.112

### Description:

<img width="1483" alt="image" src="https://github.com/laravel/nova-issues/assets/855788/e7f72939-ca79-4dbb-b2a2-7fe5874ec61e">

- Not readonly fields looks like readonly
- Not filled readable fields looks like filled fields

This problem exists only on light mode, in dark mode there is little difference:
<img width="1501" alt="image" src="https://github.com/laravel/nova-issues/assets/855788/ecb3be2e-d0b7-4d40-9186-623105607591">

But in my opinion readonly field should be more dimmed than field with placeholder.

### Detailed steps to reproduce the issue on a fresh Nova installation:
- just add some fields that are filled, not filled and disabled.

**Comment by webard** [comment]
Exactly, there is no problem with filling data, but styling might be confusing for users.

**Comment by morhi** [comment]
The issue is in `vendor/laravel/nova/resources/css/form.css` on line 19. As said already the attribute of the input fields is set to `data-disabled="false"`, but the style does not care about the value set for this attribute, so it gets applied to all input elements.
