### ISSUE TITLE
Repeater don't save translation

### ISSUE THREAD

**Issue by cereneto** [laravel/nova-issues#6264]
- Laravel Version: 10.46.0
- Nova Version: 4.32.15
- PHP Version: 8.0.2
- Database Driver & Version: PostgreSQL 12.17
- Operating System and Version: Ubuntu 20.04
- Browser type and version: Chrome V 122.0.6261.95 

### Description:

Hello,

I am experiencing an issue with the Outl1ne\nova-translatable package in Laravel Nova, where data is not being saved to the database when using the ->translatable() trait on repeater fields within row items. 

Expected Behavior:
Data entered in the translatable fields of repeater items should be correctly saved in the database for each configured language.

Actual Behavior:
Translatable data is either not saved at all or not properly persisted, leading to a lack of translated data in the database post-form submission.

Potential Cause:
The alteration in the structure of field names for translatable fields seems to interfere with proper data handling in the fill() method, resulting in truncated field names in the request payload and consequently, failure to save the data as expected.

Here is the fill() method in question:

From RepeaterField.vue
```
fill(formData) {
    this.finalPayload.forEach((repeatable, i) => {
        const attribute = `${this.fieldAttribute}[${i}]`;
        formData.append(`${attribute}[type]`, repeatable.type);
        Object.keys(repeatable.fields).forEach(key => {
            formData.append(`${attribute}[fields][${key}]`, repeatable.fields[key]);
        });
    });
}
```

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Create a repeater field in a Nova resource.
2. Install Outl1ne\nova-translatable package and dependencies.
3. Within this repeater's items, include text fields that utilize the ->translatable() trait.
4. After filling out the fields in the Nova interface and submitting the form, the data appears to be processed but does not persist in the database.

**Comment by crynobone** [comment]
Hi there,

We don't handle issue related to integration with 3rd party packages.
