### ISSUE TITLE
Cannot update attached resource with searchable relation

### ISSUE THREAD

**Issue by webard** [laravel/nova-issues#6266]
- Laravel Version: 10.47.0
- Nova Version: 4.32.16
- PHP Version: 8.2.16
- Database Driver & Version: Mysql  8.2.16
- Operating System and Version: MacOS 14.3.1
- Browser type and version: Chrome 122.0.6261.112
### Description:

<img width="1544" alt="image" src="https://github.com/laravel/nova-issues/assets/855788/cebed84c-bee7-4660-9628-f33c138c6800">

Field `Permissions` is freezed (cannot click or search) when I update attached relation. My field configuration is:
```php
BelongsToMany::make('Permissions', 'permissions', Permission::class)->searchable()->sortable(),
```

Attaching new resource works perfect:
<img width="1487" alt="image" src="https://github.com/laravel/nova-issues/assets/855788/50872db5-f14f-427d-8328-06cd1f412f48">

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Connect two resources by BelongsToMany relation
- Attach something to Resource
- Try to edit Attached resource

**Comment by crynobone** [comment]
Edit many-to-many resources is only designed to allow editing pivot fields and not the related resources itself.

**Comment by mihob** [comment]
@crynobone 

Why is that? Can't it be made optional? Either edit the resource or the pivot fields?

If there are no pivot fields, the button is completely useless and very confusing for users.
