### ISSUE TITLE
Nova cannot update a table column with a space

### ISSUE THREAD

**Issue by richardkeep** [laravel/nova-issues#6269]
- Laravel Version: 10.47.0
- Nova Version: 4.35.16
- PHP Version: 8.1
- Database Driver & Version: MySQL 8.0
- Operating System and Version: Mac OS
- Browser type and version: Google Chrome

### Description:
When you have a table column name with a space, Nova can display the value but you cannot update it.

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Create a Model, e.g Post model and its migration
```php
Schema::create('posts', function (Blueprint $table) {
    $table->id();
    $table->string('Post Name')->nullable(); // a column with a space
}
```

2. Migrate the table and manually add a record in DB. (maybe using tinker or TablePlus)
3. Create a Nova Resource: ```App\Nova\Post```
4. Add the Field: ```Text::make('Post Name', 'Post Name')'```
5. Open the post edit page and try to update it and submit.
6. **The Post Name won't update in the database**

1. Change the table column from `Post Name` to something like `post_name` or `postname` and update the Nova field accordingly.
2. Try to update the same post.
3. It will update!!!

I have searched for a similar issue on the closed issues table and the discussion tab and it seems no one has ever encountered the same. I am working on a legacy project and I am not allowed to rename the table columns for now. I believe this is a bug.

**Comment by crynobone** [comment]
Check the issue with the Laravel Framework team and we have concluded that it's not a common usage and isn't being tested. 

Since you can't change the database, it could be possible to create an observer to rename `post_name` to `Post Name`:

```php
    /**
     * Handle the User "creating" event.
     */
    public function creating(Post $post): void
    {
        $post->setAttribute('Post Name', $post->post_name);
        unset($post->post_name);
    }
```

**Comment by crynobone** [comment]
Alternatively you can set a accessor and mutator to handle this requirements.

**Comment by richardkeep** [comment]
@crynobone Creating a mutator still cannot fix it

```php
public function post_name(): Attribute
{
    return Attribute::make(
        get: fn () => $this->{'Post Name'}
    );
}
```

and in the Nova resource

```php
Text::make('Post Name', 'post_name')->onlyOnForms(), // doesn't show the value from DB for editing
Text::make('Post Name', 'Post Name')->exceptOnForms(), // shows the value from DB
```
