### ISSUE TITLE
When running an action on a single model, don't show unrunnable action

### ISSUE THREAD

**Issue by rickmacgillis** [laravel/nova-issues#627]
It's a bit odd to see the action I'd like to run, and then when I'm trying to perform the action on one row, go through the stage of filling out a form only to find out I'm unable to run the action on that row.

To make things more obvious, I suggest making the `canRun` method run on the first item checked, and disabling the actions that cannot be run for that item. Perhaps it might make more sense to run it on every checked-box until one comes up where it is possible to run an action previously disabled. (Assuming it won't become too time-intensive)

The way it works when only some actions finish doesn't clue anyone in that they weren't completed. Perhaps it might be prudent to check if some failed because of the permissions and display a second toast alerting the admin that some items weren't completed - subsequently logging the failures to the Action Log for easy review.

[REDACTED PREVIOUS UPDATE]

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
