### ISSUE TITLE
sumBy* methods of Trend metric does not accept Illuminate\Contracts\Database\Query\Expression

### ISSUE THREAD

**Issue by webard** [laravel/nova-issues#6270]
- Laravel Version: 10.47.0
- Nova Version: 4.32.16
- PHP Version: 8.2.16
- Database Driver & Version: Mysql  8.2.16
- Operating System and Version: MacOS 14.3.1
- Browser type and version: Chrome 122.0.6261.112

### Description:

I have Trend metric like this:
```php
 public function calculate(NovaRequest $request)
    {
        return $this
            ->sumByDays(
                $request,
                PhoneCall::where('caller_user_id', $request->resourceId),
                DB::raw('duration_in_seconds/60'),
                'created_at')
            ->suffix(' minutes')
            ->showSumValue();
    }
```

which using `duration_in_seconds` column, but in Trend I want to show minutes so I divided value by 60.

Everything works correctly, but Larastan reports error:
```
 Parameter #3 $column of method Laravel\Nova\Metrics\Trend::sumByDays() expects  
         Illuminate\Database\Query\Expression|string,                                    
         Illuminate\Contracts\Database\Query\Expression given.  
```

I haven't checked other metrics or methods like sumByMinutes etc, but this error probably also occurs.

PS.
I know about `transform()` method, but Raw expressions should work too.

### Detailed steps to reproduce the issue on a fresh Nova installation:
- create metric with `DB::raw()` expression as $column parameter.

**Comment by crynobone** [comment]
In newer Laravel, `Illuminate\Database\Query\Expression` does extends `Illuminate\Contracts\Database\Query\Expression` and that shouldn't cause Larastan to throw an error. However, we also support version where `Illuminate\Database\Query\Expression` doesn't extend `Illuminate\Contracts\Database\Query\Expression` and only implements `__toString()`. 

This feel more like a Larastan issue.
