### ISSUE TITLE
Squared images like Avatar or Image are still rounded on global search

### ISSUE THREAD

**Issue by msucevan** [laravel/nova-issues#6273]
- Laravel Version: v10.47.0
- Nova Version: 4.32.15
- PHP Version: 8.2

### Description:
In the globally search if I have a squared Avatar in the global search is still appending the rounded class.

Refer to issue #4052

Is still a bug.

<img width="382" alt="image" src="https://github.com/laravel/nova-issues/assets/57497646/d256a1dc-9d25-46f6-896b-f32c4245fc3f">

### Detailed steps to reproduce the issue on a fresh Nova installation:

Create a field with squared and search the resource globally

**Comment by crynobone** [comment]
This is expected behaviour and rounded will have `rounded-full` instead.
