### ISSUE TITLE
[11.x] Route [login] not defined due to missing auth routes registration

### ISSUE THREAD

**Issue by codebarista** [laravel/nova-issues#6274]
- Laravel Version: 11.0.3
- Nova Version: 4.33.0
- PHP Version: 8.3.3
- Database Driver & Version: sqlite
- Operating System and Version: macOS Sonoma Version 14.4
- Browser type and version: Google Chrome Version 122.0.6261.129 (Official Build) (arm64)

### Description:
A new installation of Laravel 11 and Nova 4 does not redirect the `nova.path` to the login page. The login url itself works.

### Detailed steps to reproduce the issue on a fresh Nova installation:
1.  Install Laravel 11: `laravel new awesomeness`
2. Install Nova 4: `cd awesomeness` && [composer require laravel/nova](https://nova.laravel.com/docs/installation.html)
3. `php artisan serve`
4. Navigate to: http://127.0.0.1:8000/nova

### Expected behaviour
Redirect to: http://127.0.0.1:8000/nova/login

### Current response
```
Symfony\Component\Routing\Exception\RouteNotFoundException
Route [login] not defined.
```

### Possible "Fix"
Add auth routes to `routes/web.php`

```php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', static function () {
    return view('welcome');
});

Auth::routes();
```

Unfortunately, I didn't get to the root cause, or perhaps I overlooked a configuration?

**Comment by eimantaaas** [comment]
Getting the same issue with clean Laravel 11 install

**Comment by jivanrij** [comment]
I've just encountered the same issue. 
1. Fresh instal of Laravel 11 and Nova 4
2. Local development using Laravel Herd
3. Running PHP 8.2

I've also added the Auth::routes(); in routes/web.php which temporary fixed it for now.

**Comment by filipposallemi** [comment]
I solved in this way on my bootstrap/app.php:
```
<?php

use Illuminate\Foundation\Application;
use Illuminate\Foundation\Configuration\Exceptions;
use Illuminate\Foundation\Configuration\Middleware;
use Illuminate\Foundation\Http\Middleware\TrimStrings;

return Application::configure(basePath: dirname(__DIR__))
    ->withRouting(
        web: __DIR__.'/../routes/web.php',
        commands: __DIR__.'/../routes/console.php',
        health: '/up',
    )
    ->withMiddleware(function (Middleware $middleware) {
        $middleware->append(TrimStrings::class);
        $middleware->redirectGuestsTo(fn () => route('nova.pages.login'));
    })
    ->withExceptions(function (Exceptions $exceptions) {
        //
    })->create();
```

**Comment by niekdemelker** [comment]
I don't have this problem because I use a different authentication system, but if the link works cant you just update the config?

I use the below config in /config/nova.php

```
    'routes' => [
        'login' => '/auth/redirect',
        'logout' => '/auth/logout'
    ]
```

So maybe you could do something like:

```
    'routes' => [
        'login' => '/nova/login',
        'logout' => '/nova/logout'
    ]
```

Don't know if it works, but maybe this helps finding the problem.

**Comment by nastoychev** [comment]
> * Laravel Version: 11.0.3
> * Nova Version: 4.33.0
> * PHP Version: 8.3.3
> * Database Driver & Version: sqlite
> * Operating System and Version: macOS Sonoma Version 14.4
> * Browser type and version: Google Chrome Version 122.0.6261.129 (Official Build) (arm64)
> 
> ### Description:
> A new installation of Laravel 11 and Nova 4 does not redirect the `nova.path` to the login page. The login url itself works.
> 
> ### Detailed steps to reproduce the issue on a fresh Nova installation:
> 1. Install Laravel 11: `laravel new awesomeness`
> 2. Install Nova 4: `cd awesomeness` && [composer require laravel/nova](https://nova.laravel.com/docs/installation.html)
> 3. `php artisan serve`
> 4. Navigate to: http://127.0.0.1:8000/nova
> 
> ### Expected behaviour
> Redirect to: http://127.0.0.1:8000/nova/login
> 
> ### Current response
> ```
> Symfony\Component\Routing\Exception\RouteNotFoundException
> Route [login] not defined.
> ```
> 
> ### Possible "Fix"
> Add auth routes to `routes/web.php`
> 
> ```
> <?php
> 
> use Illuminate\Support\Facades\Route;
> 
> Route::get('/', static function () {
>     return view('welcome');
> });
> 
> Auth::routes();
> ```
> 
> Unfortunately, I didn't get to the root cause, or perhaps I overlooked a configuration?

The possible fix works in browser, but with follow command throw exception:
![image](https://github.com/laravel/nova-issues/assets/41673191/d46ec3c4-e5ee-43fd-8c83-cc1fe07246f4)

**Comment by nastoychev** [comment]
> $middleware->redirectGuestsTo(fn () => route('nova.pages.login'));

Thanks, if someone has another login routes and want to decouple nova: 
`$middleware->redirectGuestsTo(function (Illuminate\Http\Request $request) {
            $isNovaPath = $request->is(str_replace(search: '/',replace: '',subject: config('nova.path')));
            return $isNovaPath ? route('nova.pages.login') : null;
        });`

**Comment by nastoychev** [comment]
@crynobone should we make PR to nova-docs?

**Comment by cameronmurphy** [comment]
Having this problem too. The `nova/login` route is there when I run `artisan route:list`. Seems like a Nova bug more than a documentation issue? I feel like out of the box Nova should be able to handle redirecting unauthenticated users from `/nova` to `/nova/login`.

**Comment by crynobone** [comment]
There's scenarios where:

1. application has a "frontend" login for normal user.
2. application and Nova use separate auth guard. 

For above cases, Nova shouldn't be the default redirected page for login.

**Comment by cameronmurphy** [comment]
Fair, it's just strange that setting up Nova on a 10.x Laravel project does the redirect for you and on a 11.x Laravel project it doesn't.

**Comment by crynobone** [comment]
There's a new prompt in `nova:install` command to solve this. For existing application above code work or you can update `App\Providers\NovaServiceProvider`:

```diff
/**
* Register the Nova routes.
*
* @return void
*/
protected function routes()
{
    Nova::routes()
-       ->withAuthenticationRoutes()
+       ->withAuthenticationRoutes(default: true)
        ->withPasswordResetRoutes()
        ->register();
}
```

**Comment by saschaende** [comment]
Had the same problem with a FRESH install. Why do I have to solve this by searching and finding this here?

**Comment by cameronmurphy** [comment]
This issue is back and should be reopened. It was reintroduced in Nova 4.35.2 when this was added to line 34 in `vendor/laravel/nova/src/PendingRouteRegistration.php`:

```php
Nova::url('/login') !== '/login'
```

This always evaluates to `false` because `Nova::url('/login')` always returns `/login` when Nova is mounted at the root of the web server.

**Comment by thiagox86** [comment]
One easier way to resolve this is add just one line into  bootstrap/app.php:

<?php

use Illuminate\Foundation\Application;
use Illuminate\Foundation\Configuration\Exceptions;
use Illuminate\Foundation\Configuration\Middleware;

return Application::configure(basePath: dirname(__DIR__))
    ->withRouting(
        web: __DIR__.'/../routes/web.php',
        commands: __DIR__.'/../routes/console.php',
        health: '/up',
    )
    ->withMiddleware(function (Middleware $middleware) {

        **$middleware->redirectGuestsTo('login');**

    })
    ->withExceptions(function (Exceptions $exceptions) {
        //
    })->create();
    
    
You just have to see if your route is correctly named as 'login'.

**Comment by KasparRosin** [comment]
@crynobone I'm not sure the issue is fixed. Still experiencing this with nova 5.1.4.
I have a lightly different setup where I have defined NOVA_DOMAIN to be "nova".

Meaning that my web runs on localhost:8000, but nova is served from nova.localhost:8000 (not sure if this matters.) Fix proposed by @thiagox86 works.

**Comment by prodevuk** [comment]
Try this in your `web.php` routes file:

```
Route::get('/', function () {
    if (Auth::check()) {
        return redirect()->route('nova.pages.dashboard.custom', 'main');
    }
    return redirect()->route('nova.login');
})->name('home');
```

This is assuming you modified your nova path to be served from root.
