### ISSUE TITLE
Action::visit fails

### ISSUE THREAD

**Issue by ArtDepartmentMJ** [laravel/nova-issues#6280]
- Laravel Version: 10.48.3
- Nova Version: 4.33.0
- PHP Version: 8.3

### Description:
Action::visit as described in the [docs](https://nova.laravel.com/docs/actions/registering-actions.html#visit-actions) does not appear to be working in the latest version.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Add this to a resource:
```
public function actions(NovaRequest $request): array
{
    return [
        \Laravel\Nova\Actions\Action::visit('View users', Nova::url('/resources/users'))->standalone(),
    ];
}
```
Error:
```
Call to undefined method Laravel\Nova\Actions\ActionResponse::standalone() 
```
If standalone() is removed, it throws this:
```
Call to undefined method Laravel\Nova\Actions\ActionResponse::shownOnIndex() 
Call to undefined method Laravel\Nova\Actions\ActionResponse::shownOnTableRow()   
```

**Comment by webard** [comment]
You can make your own action like `php artisan nova:action ViewUsers` and in this Action class make:
```php
public function handle(ActionFields $fields, Collection $models)
{
    ActionResponse::visit(Nova::url(...));
}
```

There is some mess in docs, I had similar problem with `Action::modal()`.

**Comment by ArtDepartmentMJ** [comment]
Thanks, this got me in the right direction. The only thing to add here is that you nees to return the response and also that Nova::url is unnecessary.

The docs really need sorting out!

```
public function handle(ActionFields $fields, Collection $models)
{
    return ActionResponse::visit('resources/users');
}
```

**Comment by crynobone** [comment]
```diff
use Laravel\Nova\Actions\Action;

public function actions(NovaRequest $request): array
{
    return [
-        Action::visit('View users', Nova::url('/resources/users'))->standalone(),
+       Action::visit('View users', Nova::url('/resources/users'), [])->standalone(),
    ];
}
```

Will update the documentation.
