### ISSUE TITLE
Text fields always look disabled & disabled class doesn't work for dark mode

### ISSUE THREAD

**Issue by FinnPaes** [laravel/nova-issues#6286]
- Laravel Version: 10.47.0
- Nova Version: 4.32.16
- PHP Version: 8.3.3
- Browser type and version: Google Chrome 122.0.6261.112

### Description:
The `Text` fields always applies the `data-disabled` CSS selector because it does not evaluate if the value is true or false but only checks for existence.

<img width="1400" alt="Scherm­afbeelding 2024-03-18 om 10 49 35" src="https://github.com/laravel/nova-issues/assets/71390226/8ddf081e-e080-422e-8fc0-c2bc03ef162d">

So the `.form-control[data-disabled]` needs to be changed to: `.form-control[data-disabled=true]`

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Create a Text (`Laravel\Nova\Fields\Text`) field in a resource.
2. Open it in Nova with **light mode**.
As you can see, it gets the disabled classes.

Then another issue comes up paired with this one is that the disabled class is not visible in dark mode for the Text field. Looks like it's even missing for the dark mode feature?

**Comment by crynobone** [comment]
Fixed in 4.33.0
