### ISSUE TITLE
Trix field does not work in Panel

### ISSUE THREAD

**Issue by webard** [laravel/nova-issues#6287]
- Laravel Version: 10.48.3
- Nova Version: 4.33.0
- PHP Version: 8.2.17
- Database Driver & Version: MySQL 8.3.0
- Operating System and Version: MacOS Sonoma 14.4 (23E214)
- Browser type and version: 122.0.6261.129

### Description:

I want to show `Trix` field in Panel:
```php
            Panel::make(__('Content'), [
                Trix::make(__('Content'), 'content')
                    ->required()
                    ->rules('required')
                    ->alwaysShow(),
            ]),
```

When I remove `Panel::make`, everything works fine, but when fields are in Panel, Trix field never shows up.

### Detailed steps to reproduce the issue on a fresh Nova installation:
- just configure Trix field in Panel

**Comment by crynobone** [comment]
Unable to replicate the issue:

![CleanShot 2024-05-16 at 10 20 15](https://github.com/laravel/nova-issues/assets/172966/df29b5ef-904d-462b-b32d-ba599bf65ece)

**Comment by webard** [comment]
@crynobone Trix field works correct directly on Resource. Upload does not work when field is added to Action.

**Comment by webard** [comment]
Okay, looks like it's working now. Checked on newest version.
