### ISSUE TITLE
Nova Menu Gravatar

### ISSUE THREAD

**Issue by wefixit-tech** [laravel/nova-issues#629]
I edit the file in **nova/resources/views/partials/user.blade.php**, 
to use avatar upload picture like this **{{ (auth()->user()->avatar) }}**, 
but when i refresh the page and inspect the element it doesnt make any change, 
OS: windows and nova 1.1.1, i tried everything, running npm install on nova folder and npm run dev and watch, but none of this makes change at all, i hope someone can help me with this.

**Comment by bonzai** [comment]
Use this file instead - `resources/views/vendor/nova/partials/user.blade.php`.

**Comment by davidhemphill** [comment]
The `/nova` directory isn't intended to be customized. You need to customize the partial found at `resources/views/vendor/nova/partials/user.blade.php` as @bonzai mentioned.
