### ISSUE TITLE
SQLSTATE[HY000]: General error: 1 near "on": syntax error 

### ISSUE THREAD

**Issue by xerc** [laravel/nova-issues#6293]
- Laravel Version: 11.0.7
- Nova Version: 4.33.0
- PHP Version: ^8.2
- Database Driver & Version: SQlite (before 3.24.0)

### Description:

just created `laravel` w/ `nova` should run with `sqlite`

### Detailed steps to reproduce the issue on a fresh Nova installation:

go to `/nova/login` & login => redirect to `/nova/dashboards/main` & shows error

### Solution
```diff
   "require": {
     "php": "^7.3|^8.0",
+    "ext-sqlite3": "^3.24",
```

**Comment by xerc** [comment]
```sql
insert into
  "cache" ("key", "value", "expiration")
values
(
    <app>_cache_nova_valid_license_key,
    b: 1;,
    <TS>
)
on conflict ("key") do
  update
  set
    "key" = "excluded"."key",
    "value" = "excluded"."value",
    "expiration" = "excluded"."expiration"
```

**Comment by crynobone** [comment]
What's the exact version of SQLite?

**Comment by xerc** [comment]
> What's the exact version of SQLite?

3.7.17 2013-05-20 << might be to old ?!

**Comment by crynobone** [comment]
Laravel 11 requires SQLite 3.35+
