### ISSUE TITLE
Translate True/False value in Boolean field

### ISSUE THREAD

**Issue by disitec** [laravel/nova-issues#63]
Is there a way to translate that value in the details view?

![image](https://user-images.githubusercontent.com/12644599/44543561-2c56c700-a710-11e8-8a80-29c19f34eda1.png)

**Comment by fat4lix** [comment]
Yes, you can.
Boolean::make('Active')
        ->trueValue('On')
        ->falseValue('Off');

**Comment by disitec** [comment]
I’ve tried that but doesn’t work. As I read in documentation is for setting the value in case you are not using true, false, 0 or 1

**Comment by themsaid** [comment]
Ok we're changing this in the upcoming release.

**Comment by zachgarcia1** [comment]
Has this been updated? i still can't seem to affect the true false values of my boolean field.
