### ISSUE TITLE
search only for primary key

### ISSUE THREAD

**Issue by Catsys** [laravel/nova-issues#630]
If search value is integer, to the request is added "id='{$value}' and ". this makes it impossible to search for other numeric fields such as user_id or order_id

I understand that this speeds up the search, searching only for keys. but let's leave it to the conscience of developers. I propose to add the flag of $searchForAllFields to the possibility of disabling this feature

UPD
Added a check on the number to speed up the search. Numerical indexes are often found together and can be used by placing the order of the fields in the desired order. Also, you do not usually need a part of the number

`nova/src/PerformsQueries.php:60`

	`protected static function applySearch($query, $search)
	{
		if (is_numeric($search) && in_array($query->getModel()->getKeyType(), ['int', 'integer'])) {
			if (static::$searchForAllFields === false) {
				$query->whereKey($search);
			}
		}

		return $query->where(function ($query) use ($search) {
			$model = $query->getModel();

			foreach (static::searchableColumns() as $column) {
				if (is_numeric($search) && in_array($query->getModel()->getKeyType(), ['int', 'integer'])) {
					$query->orWhere($model->qualifyColumn($column),  '=', $search );
				}
				else {
					$query->orWhere($model->qualifyColumn($column), 'like', '%' . $search . '%');
				}
			}
		});
	}`

`nova/src/Resource.php:60`
`public static $searchForAllFields = false;`

**Comment by cannect** [comment]
Please leave it open if you want it seen by Nova developers?
