### ISSUE TITLE
Changing rules inside dependsOn not working well when submit

### ISSUE THREAD

**Issue by ProjectesFUAB** [laravel/nova-issues#6308]
- Nova Version: 4.33.1

### Description:

When change rules on dependsOn, not working well. 

```
Select::make('Tipus', 'tipus')
   ->options(['Mòdul' => 'Mòdul', 'Assignatura' => 'Assignatura'])
   ->rules('required'),

BelongsTo::make('Mòdul', 'modul', 'App\Nova\Assignatura')
   ->sortable()
   ->withoutTrashed()
   ->dependsOn(
      ['tipus'],
      function (BelongsTo $field, NovaRequest $request, FormData $formData) {
         if ($formData['tipus'] === 'Assignatura') {
            $field->rules(['required']);
         } else {
            $field->rules(['nullable'])->setValue(null);
         }
         ray($field);
      }),
```
The $field seems to update fine, but the rules are not applied correctly in the case of the nullable when I try to save the record

(before change Select)
![image](https://github.com/laravel/nova-issues/assets/71957731/b8cb549f-224e-46a5-b77b-13a5bb58f9c3)

(after Select change and submit)
![image](https://github.com/laravel/nova-issues/assets/71957731/e70b995b-e5d6-4580-8544-4e4a32874263)

**Comment by ProjectesFUAB** [comment]
Sorry you can delete this issue. I modified the code to make the rule nullable always and the error when submiting still present.

Suppose that trouble is in another place

**Comment by crynobone** [comment]
`$field->nullable()` and `$field->rules(['nullable'])` does have different behavior.
