### ISSUE TITLE
Sorting in lenses not work when there is BelongsToMany field in it

### ISSUE THREAD

**Issue by webard** [laravel/nova-issues#6311]
- Laravel Version: 10.48.4
- Nova Version: 4.33.1
- PHP Version: 8.2.17
- Database Driver & Version: Mysql 8.3
- Operating System and Version: MacOS Sonoma 14.4.1 (23E224)
- Browser type and version: Chrome 123.0.6312.87

### Description:

Sorting in Lenses does not work when there is any `BelongsToMany` field in it. I have very simple `Lens` for testing purpose:

```php
 /**
     * Get the query builder / paginator for the lens.
     *
     * @param  \Laravel\Nova\Http\Requests\LensRequest  $request
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return mixed
     */
    public static function query(LensRequest $request, $query)
    {
        return $request->withOrdering($request->withFilters(
            $query
        ));
    }

 /**
     * Get the fields available to the lens.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @return array
     */
    public function fields(NovaRequest $request)
    {
        return [
            ID::make(Nova::__('ID'), 'id')->sortable(),
            BelongsToMany::make('Languages'),
        ];
    }
```

and when I try to sort rows there is an error:
```
Call to undefined method Illuminate\Database\Eloquent\Relations\BelongsToMany::getForeignKey()
```

Yes, `BelongsToMany` field does not make any sense in Lenses, but for sake of simplicity, I created simple method in my internal abstract Lens class:
```php
 /**
     * Get the fields available to the lens.
     *
     * @return array<int, \Laravel\Nova\Fields\Field>
     */
    public function fields(NovaRequest $request)
    {
        /** @var Model $model */
        $model = $this->resource;

        return $request->newResourceWith($model)->fields($request);
    }
```

which copies all fields from original Resource and I think that many users can do this, so please, do not close issue without resolving. I think all we need is skipping BelongsToMany/MorphToMany relations in this method of `Laravel\Nova\Http\Requests\LensRequest` class:

```php
/**
     * Get foreign key name for relation.
     *
     * @param  \Illuminate\Database\Eloquent\Relations\Relation  $relation
     * @return string
     */
    protected function getRelationForeignKeyName(Relation $relation)
    {
        return method_exists($relation, 'getForeignKeyName')
            ? $relation->getForeignKeyName()
            : $relation->getForeignKey();
    }
```

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Create two resources related by BelongsToMany relation and connect them
- Create Lens with BelongsToMany field

**Comment by crynobone** [comment]
Lens is meant for displaying a lists of flatten data.
