### ISSUE TITLE
Partition metrics - NaN

### ISSUE THREAD

**Issue by nsaumini** [laravel/nova-issues#632]
Issue : Displays `NaN%` when the total count is 0.

Sample result : 
```
[
    'Group1' => 0,
    'Group2' => 0,
    'Group3' => 0
]
```

Output :

![image](https://user-images.githubusercontent.com/12414016/45873880-17259480-bdb1-11e8-81ab-a6e4c72b537b.png)

**Comment by alexbowers** [comment]
This issue is confirmed:

It only happens if *all* of the partitions are 0. If any of them are positive, then they show 0% correctly.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
