### ISSUE TITLE
Cannot add validation to the depend-on field

### ISSUE THREAD

**Issue by bocanhcam** [laravel/nova-issues#6326]
I have this simple code that requires users to fill in the `billing_name` if `is_billing` is true.
However, the validation is not working at all. I still can submit the form without filling in the `billing_name` when `is_billing` is checked.
`show()` still works.
```php
public function fields(NovaRequest $request)
    {
        return [
            Boolean::make('他に請求先を指定','is_billing')->onlyOnForms(),
            Text::make('請求先氏名','billing_name')
                ->hide()
                ->dependsOn(['is_billing'], function (Text $field, NovaRequest $request, FormData $formData) {
                    if ($formData->is_billing === true) {
                        $field->show()->rules(['required', 'max:50']);
                    }
                })
                ->placeholder('（半角50文字まで）')
                ->onlyOnForms(),
        ];
    }
```

- Laravel Version: 10.48.4
- Nova Version: 4.33.1
- PHP Version: 8.2.17

**Comment by webard** [comment]
Same in my app, rules setted on field in dependsOn closure are not respected.

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by webard** [comment]
Here is reproduction repo: https://github.com/webard/nova-issue-6326 , in `User` resource is sample.

Bug occurs when other fields is depend on Boolean field (Select works correctly, I didn't check all fields).

**Comment by crynobone** [comment]
Does `$formData->bool('is_billing') === true` worked for your use case?

**Comment by bocanhcam** [comment]
@crynobone This worked. I'll close this issue.

`$formData->boolean('is_billing') === true`
