### ISSUE TITLE
Trend Metrics show Trend of a table, but the table has no id field.

### ISSUE THREAD

**Issue by guoxiangke** [laravel/nova-issues#633]
![image](https://user-images.githubusercontent.com/1160703/45875132-5f50b100-bdc9-11e8-97d2-663a0f727e7a.png)

or how to rewrite the id used by  Trend Metrics?

**Comment by jbrooksuk** [comment]
This issue board is for tracking bugs and feature requests. Please direct general questions to #nova on Laravel's Discord or #nova on the Larachat Slack Channel.
