### ISSUE TITLE
Custom Tool bug.

### ISSUE THREAD

**Issue by AbdallahAli912** [laravel/nova-issues#6334]
- Laravel Version: 9.0
- Nova Version: 4.0
- PHP Version: 8.2
- Database Driver & Version: mysql
- Operating System and Version: mac os 
- Browser type and version: chrome

- In custom tool i have a lot of components when go from one component to another it's work but after that if i tried to open any other menu element from sidebar it have problem in loading (load empty page).
- the problem happens when more than one component in successive way.
- 
<img width="1204" alt="Screenshot 2024-04-03 at 2 10 40 PM" src="https://github.com/laravel/nova-issues/assets/54299150/5bf7be2b-616f-4884-bd80-6b0947c40c67">

### Detailed steps to reproduce the issue on a fresh Nova installation:
- create custom tool.
- create two pages on it.
- in page 1  make button which goes to page 2.
- open page 1 then click page 2 button after that try to open any element in sidebar.
- not load page correctly without any errors.

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by yzzhushu** [comment]
> Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

I have the same problem. Here is the steps to reproduce the issue:

-  Set Customized Main Menu
<img width="713" alt="image" src="https://github.com/laravel/nova-issues/assets/17975215/43f0cfa7-cbf8-4b4b-8e68-dbdaca0d2944">

- Show by video
https://github.com/laravel/nova-issues/assets/17975215/b5501440-364d-4824-ba2f-fe94588137f6

**Comment by crynobone** [comment]
> I have the same problem. Here is the steps to reproduce the issue:

No, still need the full reproducing repository.

**Comment by yzzhushu** [comment]
> > I have the same problem. Here is the steps to reproduce the issue:
> 
> No, still need the full reproducing repository.

I have solved this problem by regenerating the tool package. ^_^

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
