### ISSUE TITLE
Problem with actions

### ISSUE THREAD

**Issue by daguilarm** [laravel/nova-issues#634]
Hi, I just created my first action, and I haven't able to use this feature. Each time I click in the action button I recive an error message, and the javascript fail:

<img width="2337" alt="captura de pantalla 2018-09-21 a las 12 22 20" src="https://user-images.githubusercontent.com/2663941/45875878-3b757700-bd99-11e8-944c-d0b83ab0c554.png">

I don't know why the javascript stops...

My action:
```

/**
     * Perform the action on the given models.
     *
     * @param  \Laravel\Nova\Fields\ActionFields  $fields
     * @param  \Illuminate\Support\Collection  $models
     * @return mixed
     */
    public function handle(ActionFields $fields, Collection $models)
    {
        foreach ($models as $model) {
            $model->plot_status = $fields->plot_status;
            $model->save();
        }
    }

    /**
     * Get the fields available on the action.
     *
     * @return array
     */
    public function fields()
    {
        return [
            Select::make('plot_status')
                ->options([
                    0 => 'Desactivado',
                    1 => 'Activo',
                ]),
        ];
    }
```

<img width="550" alt="captura de pantalla 2018-09-21 a las 12 28 30" src="https://user-images.githubusercontent.com/2663941/45876084-e5ed9a00-bd99-11e8-88fa-724fdec5ba53.png">

**Comment by davidhemphill** [comment]
I'm not able to replicate this on my end using what you've sent. Can you provide more information on your setup and platform?

**Comment by daguilarm** [comment]
I just test a new laravel project with nova and it is working... I thing is some nova package problem... I will test then one by one. Thanks!
