### ISSUE TITLE
Nova Filter `apply()` Method can accept or return more than just a `Builder` Instance

### ISSUE THREAD

**Issue by pjkellar** [laravel/nova-issues#6342]
- Laravel Version: 10.40
- Nova Version: 4.22.2
- PHP Version: 8.1
- Database Driver & Version: MySQL 8
- Operating System and Version: macOS Sonoma Version 14.4
- Browser type and version: Safari Version 17.4.1 (19618.1.15.11.14)

### Description:

When you create a new filter using `php artisan nova:filter` the resulting new class has the `apply()` method that has the `Buidler` specified as the return type (via a doc block). My team uses strict return types, so we update the method signature as such. We’ve just ran into an issue where we received an error when attempting to run an action on a filtered set of resources while viewing them in a BelongsToMany field of a related resource.

### Detailed steps to reproduce the issue on a fresh Nova installation:

If you have applied a filter and then select all resources to run an action on, the action will receive a payload with `resources: all`

When Nova attempts to get the selected resources, if it was `all` it checks to see if it was via a relationship or not. If it is, it creates a new model for that resource type, calls `findOrFail` with the resource ID, then loads the relationship like this: `->{$this->viaRelationship}()` — which does not return an instance of Builder, but an instance of the specific relationship type, in my case a BelongsToMany).

This query is then passed in to the `buildIndexQuery` which is where the filters are applied, and where the apply method will accept a query that is *not* an instance of `Builder`, but rather an instance of `Relation`. 

I feel like either the doc block should be updated to reflect that it is not *always* going to be an instance of `Builder` or you could update the `QueriesResources::newQuery()` function to call `->getQuery()` on the relation before returning. (See image)

![image](https://github.com/laravel/nova-issues/assets/14946432/37777f6b-db7c-43fc-b495-669e4e7562c2)

**Comment by crynobone** [comment]
This will be updated once we remove support for Laravel 8 which doesn't have `Illuminate\Contracts\Database\Eloquent\Builder`.
