### ISSUE TITLE
Remember a selected filter or pagination status when navigating & modifying resources

### ISSUE THREAD

**Issue by stephaneisenbach** [laravel/nova-issues#6344]
@eAvio anything with `next-series` will only be available on Laravel Nova 4.

_Originally posted by @crynobone in https://github.com/laravel/nova-issues/issues/1925#issuecomment-990840252_
            
https://github.com/laravel/nova-issues/discussions/4673#discussion-4290275

**Comment by stephaneisenbach** [comment]
@crynobone "not planned" but marked as "implemented" #1925?

**Comment by crynobone** [comment]
Implemented as for the Cancel action described in the original post.

**Comment by scramatte** [comment]
Hello,

I'm running. 4.33 and when you create or update resource, filters and pagination are not remembered on index page.
So why you mark it as implemented?

Regards

**Comment by crynobone** [comment]
There a idea discussion still open regarding this: https://github.com/laravel/nova-issues/discussions/4673

The original issue contain multiple issues and contain a solution for one of the issue. This is why we encourage single issue per problem and not attempt to combine multiple issues into one.

**Comment by stephaneisenbach** [comment]
> The original issue contain multiple issues and contain a solution for one of the issue. 

@crynobone You mean #1925 as original?

> The original issue contain multiple issues and contain a solution for one of the issue. 

@crynobone For which of the multiple issues exactly a solution has been implemented? I can't tell that any of it works.

> This is why we encourage single issue per problem and not attempt to combine multiple issues into one.

@crynobone So should we split it into more issues? Like this:

1. Remember a selected filter status when navigating
2. Remember a selected filter status when modifying resources
3. Remember pagination when navigating
4. Remember pagination when modifying resources

In my opinion, it all belongs together.

**Comment by crynobone** [comment]
Reproducing step 1 until 4.

**Comment by scramatte** [comment]
Remember must  be works on update and create
