### ISSUE TITLE
Sortable() works only two times 

### ISSUE THREAD

**Issue by AnniDineva** [laravel/nova-issues#6345]
- Laravel Version: 8.83.27
- Nova Version: 3.31.0 
- PHP Version: 7.1
- Database Driver & Version:
- Operating System and Version: #.#
Operating System and Version: Windows 11
Browser type and version: ChromeVersion 123.0.6312.107 (Official Build) (64-bit)

### Description:
Sorting works the first two times, the third time nothing happens.

I see the same issue here https://github.com/laravel/nova-issues/issues/2503 but I don't have this package https://github.com/Flagstudio/nova-actions-left/issues/2 and the issue is not from him.

**Comment by crynobone** [comment]
We no longer making any new release or support Laravel Nova 3.
