### ISSUE TITLE
`Nova.request()` auto handle message

### ISSUE THREAD

**Issue by bocanhcam** [laravel/nova-issues#6352]
I'm using custom-tools and I have a simple function using `Nova.request()`.

```js

async getRoom() {
            const apiUrl = '/api/room';

            this.loading = true;
            await Nova.request().get(apiUrl)
                .then(response => {
                    // To do
                })
},

```
The thing is Nova auto shows a toast error message when the API gets error 500.
![Screenshot from 2024-04-17 17-29-56](https://github.com/laravel/nova-issues/assets/35592955/2406f151-70a7-40a7-a62d-3a96f7cdaf60)

If I use Axios or change the HTTP response in the back-end when error then the message will not be shown.
Such as: `message => $e->getMessage()` to `xxx => $e->getMessage()`

Is this a feature or does my code have bugs? in this custom tool, I don't use any `Nova.error`.

And seems like it only handles error 500. When error 404 I don't see it show toast error.

- Laravel Version: 10.48.4
- Nova Version: 4.33.2
- PHP Version: 8.2

**Comment by crynobone** [comment]
That's the expected behavior since `setupAxios()` would register all the response interceptors. You should use your own Axios instance to avoid this if you need it.
