### ISSUE TITLE
Adding fields programmatically doesn't render the new fields

### ISSUE THREAD

**Issue by electrictomcat** [laravel/nova-issues#6358]
- Laravel Version: 10.48.8
- Nova Version: 4.33.3
- PHP Version: 8.3
- Database Driver & Version:
- Operating System and Version: MacOS
- Browser type and version: Chrome 124.0.6367.62
- Reproduction Repository: ///

### Description:
I have code in fields where I pull a value from request() and create new fields based on that value.

This functionality hasn't been used much but sometime in the last 4 months it stopped rendering the added fields.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Create two fields, one which depends on the other.
In the fields() function inject a third field when the request() shows the dependent field is filled.
The third field won't be rendered.

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by electrictomcat** [comment]
Here is an example project where you can replicate the issue:
https://github.com/electrictomcat/nova-debug-example

**Comment by crynobone** [comment]
That doesn't seem to be in any way supported or suggested from our documentation. Please utilise Dependent Fields or use `canSee()` if you want to selectively filter visibility.

**Comment by electrictomcat** [comment]
I understand it's outside of the documented functionality but it was
working for years.

I can't use canSee or hide and show because I would have to load 10000+
fields just to show 80 when the correct selection is made. The only
workaround was to inject fields as needed.

**Comment by crynobone** [comment]
> I understand it's outside of the documented functionality but it was
working for years.

That doesn't mean it was meant to be supported or intended to work

**Comment by electrictomcat** [comment]
Alright I understand I will undo it and build something else.
