### ISSUE TITLE
Select Field display key

### ISSUE THREAD

**Issue by AbdallahAli912** [laravel/nova-issues#6378]
- Laravel Version: 10
- Nova Version: 4.33.1
- PHP Version: 8.2
- Database Driver & Version:sql
- Operating System and Version: mac os
- Browser type and version: chrome

Select Field Display key not value in nove resource details and index.
,options array [ key => value], store key thats ok. must display value in retrieve not work it display key.

## detailed steps
- create nova resource
- add select field with options array [ key => value] 
- submit form 
- see details page (key displayed instead of value)

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by crynobone** [comment]
Please read the documentation: https://nova.laravel.com/docs/resources/fields.html#select-field
