### ISSUE TITLE
Filters and Page on index view are lost after update or create

### ISSUE THREAD

**Issue by scramatte** [laravel/nova-issues#6379]
- Laravel Version: 10
- Nova Version: 4.33
- PHP Version: 8.0
- Database Driver & Version: Postgres 
- Operating System and Version: Debian 11
- Browser type and version: Any

Filters and Page on index view are lost after update or create

Regards

**Comment by crynobone** [comment]
Duplicate of https://github.com/laravel/nova-issues/discussions/4673
