### ISSUE TITLE
Multi select  not showing the selected options on index and details page

### ISSUE THREAD

**Issue by ptravassos** [laravel/nova-issues#6381]
- Laravel Version: 10.48.10
- Nova Version: 4.33.3
- PHP Version: 8.2
- Database Driver & Version: mysql

### Description:
Working on previous Nova version (4.33.2).
On the multiselect, if you select the "Small" (Key "S") and "Small Medium"  (Key "SM") options, and save it. It will show on index and Details the "Small", "Small Medium" and "Medium". Like a combination of all caracter of the key values.

![Screenshot 2024-05-10 at 15 52 08](https://github.com/laravel/nova-issues/assets/5153801/1fb9b266-ed30-4123-a246-73b544783d0f)
![Screenshot 2024-05-10 at 15 50 55](https://github.com/laravel/nova-issues/assets/5153801/8653db2f-1411-441e-b4e9-f2ec0a35ac26)

The same happened with numeric keys. Select the key 31 and 39 and it showed the values of keys, 1, 3, 9, 31, 39.

### Detailed steps to reproduce the issue on a fresh Nova installation:
**Database Column** "plans" Varchar 255
**Model cast: ** 'plans'=>'array'
**Nova Model with field:**
```
MultiSelect::make('Plans')->options([
                'S' => 'Small',
                'SL' => 'Small Large',
                'SM' => 'Small Medium',
                'M' => 'Medium',
                'L' => 'Large',
            ]),
```

**Comment by crynobone** [comment]
Regression from https://github.com/laravel/nova-issues/issues/6350
