### ISSUE TITLE
Inconsistent name of breadcrumbs method in controllers

### ISSUE THREAD

**Issue by JanuszSmola** [laravel/nova-issues#6399]
- Laravel Version: 11.5.0
- Nova Version: 4.33.3
- PHP Version: 8.3.7

### Description:
Every single controller which generates breadcrumbs uses `breadcrumbs` method to generate it except one. `\Laravel\Nova\Http\Controllers\Pages\ResourceUpdateController` is using `breadcrumb` as a method name. For consistency reasons I think it would be nice to change it to `breadcrumbs` (with "s", as in other controllers). It will also help overriding this method.

So I suggest change:
```protected function breadcrumb(ResourceUpdateOrUpdateAttachedRequest $request)```
to:
```protected function breadcrumbs(ResourceUpdateOrUpdateAttachedRequest $request)```

**Comment by crynobone** [comment]
Will be part of Nova 5 release
