### ISSUE TITLE
Cached items for resource-specific Metrics show data for other resources

### ISSUE THREAD

**Issue by rickmacgillis** [laravel/nova-issues#640]
When caching a Metric for a resource where the Metric has `onlyOnDetail()` specified, the Metric will cache one resource's data and display it on all resources.

To avoid this issue, alter the `getCacheKey()` method of `Laravel\Nova\Metrics\Metric` to utilize the `$resourceId` property if the `$onlyOnDetail` property is `true`.

**Comment by alexbowers** [comment]
This bug has been confirmed:

1. If the cache is used, and multiple different resources use the metric, the cache persists across them both.

2. If the cache is used, and multiple different resource detail pages show the metric, the cache persists across them all.

In short, if the value is cached, it will always show the cached value, regardless of the request.

**Comment by ppisecky** [comment]
I font have the source at hand right now bit I would expect that this might be a case of using the metric URI as id for the cache record. I would try generating the URI based on the Resource used. Thats just a guess though.

**Comment by mvdnbrk** [comment]
I think this can be fixed easily 😄 

Will take a look and propose a PR to fix this.
