### ISSUE TITLE
BelongsTo or Select with searchable() does not work in action modal

### ISSUE THREAD

**Issue by jonnigg** [laravel/nova-issues#6401]
- Laravel Version: ^8.78
- Nova Version: 4.33.3
- PHP Version: 8.0
- Database Driver & Version: Postgres
- Operating System and Version: MacOS 13.4.1
- Browser type and version: Brave version 1.65.130 using Chromium 124.0.6367.159

### Description:

When using BelongsTo::make()->searchable() or Select::make()->searchable() in the fields function of an action the searchable input box is will not become focusable (won't allow text input). As a result. The search functionality does not work. The searchable() functionality does work in normal forms however. It seems that this issue is limited to being used in the modal that is presented when running actions. I have attached a few screenshots below. 

FWIW - It almost feels like a z-index issue such that the input is behind some other element.

I am using the following:
Nova: v4.33.3 (Silver Surfer)

Screenshots:
![image](https://github.com/laravel/nova-issues/assets/3459294/34cb8a1b-21f6-42c9-94b0-43169a813855)

![image](https://github.com/laravel/nova-issues/assets/3459294/3d7e05cc-f4c2-4cf7-a344-49d1e69a00d0)

### Detailed steps to reproduce the issue on a fresh Nova installation:
Created simple action and added copy pasted the Select example code form the documentation but added searchable()

**Comment by crynobone** [comment]
Are you sure you are running on the latest assets? Please run `php artisan nova:publish` and test again.

**Comment by jonnigg** [comment]
I didn't even think about doing a republish. I just assumed that initial publish was enough. I apologize for not doing this before posting this issue. I will close this as fixed. Thank you so much for that @crynobone
