### ISSUE TITLE
__soft_deleted=0 on models without SoftDeletes (Algolia can't find anything)

### ISSUE THREAD

**Issue by rickmacgillis** [laravel/nova-issues#641]
Nova keeps sending __soft_deleted=0 as one of the filters on every request to Algolia through Scout. However, because the attribute isn't present on the indices at Algolia for models not using `SoftDeletes` all queries fail for those models.

While I could add `SoftDeletes` to every model I'd like to index and reimport them, it'd be completely useless.

For the record, the models in question never had `SoftDeletes` enabled, so it's not an issue with having to re-import them or flush the indices.

**Comment by rickmacgillis** [comment]
Is anyone else experiencing this issue, or have any suggestions on how to get around the issue in the meantime?

**Comment by cpavalet** [comment]
I'm having the same Scout Algolia issue as well with zero results on the searches that do not use softdeletes. I am using soft deletes on some tables but not on all. The tables that have softdeletes do return the correct result.

**Comment by batFormat** [comment]
I have the same problem scout algolia gives an empty result in the new.

How to solve this problem?

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
