### ISSUE TITLE
A bug when using dependsOn method through inline create

### ISSUE THREAD

**Issue by yzzhushu** [laravel/nova-issues#6419]
- Laravel Version: 10.35.0
- Nova Version: 4.32.9
- PHP Version: 8.1
- Database Driver & Version:
- Operating System and Version: MacOS
- Browser type and version: Chrome

### Description:

I set fields with `fullWidth` and `stacked` in `fieldsForInlineCreate` function,  when resource created by inline create, the dependented field can't load `fullWidth` and `stacked` attribute, it just load from the default `fields` function

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by yzzhushu** [comment]
I reproduced this problem by record my screen

**Comment by yzzhushu** [comment]
Uploading Screen Recording 2024-06-03 at 17.32.02.mov…

**Comment by yzzhushu** [comment]
[Screen Recording 2024-06-03 at 17.47.12.mov.zip](https://github.com/user-attachments/files/15532130/Screen.Recording.2024-06-03.at.17.47.12.mov.zip)

**Comment by yzzhushu** [comment]
I uploaded my record by zip file. I don't know why I can't upload by mov media file.


Please download the file and you can know why I mean

**Comment by crynobone** [comment]
Please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)
