### ISSUE TITLE
Incorrect method call for Batch Action in "toQueryWithoutScopes" method

### ISSUE THREAD

**Issue by dzandrey** [laravel/nova-issues#6421]
- Laravel Version: 11.3.1
- Nova Version: 4.33.3
- PHP Version: 8.2

### Description:
In Laravel Nova when attempting to retrieve selected resource IDs through the `selectedResourceIds()` method, an issue with incorrect processing of the comma-separated string of identifiers has been discovered.
- file: vendor/laravel/nova/src/Http/Requests/InteractsWithResourcesSelection.php
- method: selectedResourceIds()
![01-2024-06-11_18-57](https://github.com/laravel/nova-issues/assets/4937766/a683fda3-d764-4560-b0b8-b2725336fc7b)

 The issue lies in the improper conversion of the string containing identifiers into an array, leading to incorrect logic in determining the number of selected resources and subsequent erroneous invocation of the `detailQuery` or `indexQuery` methods in the `ActionRequest` class.
- file: vendor/laravel/nova/src/Http/Requests/ActionRequest.php
- method:  toQueryWithoutScopes()
![02-2024-06-11_19-00](https://github.com/laravel/nova-issues/assets/4937766/7825d079-e90e-4e0c-a579-9d3452b83418)
![03-2024-06-11_19-08](https://github.com/laravel/nova-issues/assets/4937766/d050a5d6-65b6-49fe-aebb-767ae83a3473)

### Detailed steps to reproduce the issue on a fresh Nova installation:
Open resource index page and apply any Action to multiple records

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by crynobone** [comment]
For context, Nova would only send a string as `all` or an array of IDs, so comma separated string is not an expectwd behaviour. This has been tested vja our integration and dusk tests. You need to submit reproduing code to confirm such issue exista.

**Comment by dzandrey** [comment]
@crynobone 
https://github.com/dzandrey/nova-issue-batch-action

**Comment by crynobone** [comment]
The usage of `selectedResourceIds()` is limited to Action Modal confirmation and not during submission and therefore isn't a bug. You should look at `toSelectedResourceQuery()` on how to access it, since all methods here are internal we not making changes to the above method.

**Comment by dzandrey** [comment]
Here is the method you're referring to.
![04-2024-06-12_17-18](https://github.com/laravel/nova-issues/assets/4937766/5bf82192-a8e8-4825-ac0e-083cb63aa799)
Bbut it uses toQueryWithoutScopes() from which it takes $resource::detailQuery instead of $resource::indexQuery. In this case, $resource::indexQuery should be triggered because I am calling the action on the list and not on the detail page.
