### ISSUE TITLE
Opening the Filter Menu sometimes causes a refresh

### ISSUE THREAD

**Issue by tylernathanreed** [laravel/nova-issues#6424]
- Laravel Version: 10.48.12
- Nova Version: 4.34.2
- PHP Version: 8.2.13

### Description:

Opening the Filter Menu can cause a refresh when the backing value changes from a string to an integer, even if the value is effectively the same (e.g. `2` vs `"2"`).

### Detailed steps to reproduce the issue on a fresh Nova installation:

Follow these steps:
1. Create a resource
2. Add a filterable select field
3. Have the select field's option values be integers
4. In the UI, filter to any option
5. Refresh the page (this forces the filter values to source from the URL string)
6. Open the filter menu
7. The resource table will refresh just by opening the menu, despite not having selected anything yet

Repository:
https://github.com/tylernathanreed/nova-issues/pull/1/files

Video:

https://github.com/laravel/nova-issues/assets/6486381/5124c5c7-541c-49c0-af35-f4a56f1f0485

### Root Cause

It took me awhile to figure this one out, but the root cause was the filter value changing from a string to an integer (e.g. `"2"` to `2`). When a value is initially selected, the value ends up being a string. However, when the value is initialized from a string, the `Filter/SelectField` component finds the option matching the string-based value, and assigns `option.value` to `this.value`, where `option.value` was actually an integer.

I was able to hack in a fix by modifying the source code for `Filter/SelectField`'s `watch:selectedOption` function, and changing `this.value = option.value` to `this.value = String(option.value)`. There may be edge cases that need to be explored, but that solution definitely solved my problem.

**Comment by tylernathanreed** [comment]
@crynobone 

I've created a repository for you, and I've linked a pull request (to my own repository) that shows you the files I added on top of the default Nova installation.

I've also attached a video demonstrating the bug.

**Comment by crynobone** [comment]
Released with Laravel Nova 5.0.0

Feel free to open up a new issue if you're still experiencing this problem on the latest version.
