### ISSUE TITLE
[Request] Allow asHtml() method for "Select" fields

### ISSUE THREAD

**Issue by chescos** [laravel/nova-issues#644]
`Select` fields are often used for a `status` or `type` column. I'd love to assign typography (especially font-color and font-weight) to the different types and statuses so that the table becomes easier to read.

**Comment by davidhemphill** [comment]
Create a custom field for this.

**Comment by domstubbs** [comment]
If this was a valid request for text fields (#280) I’m not sure why it’s not also valid for selects. There’s a lot of overhead involved in creating a custom field, but after replicating the Text fieldtype’s asHtml method in the Select fieldtype I can have my custom behaviour working in a couple of minutes.
