### ISSUE TITLE
BelongsToMany runs excessive (heavy) queries

### ISSUE THREAD

**Issue by fruitl00p** [laravel/nova-issues#6451]
- Laravel Version: 11.10
- Nova Version: 4.34.3
- PHP Version: 8.3
- Database Driver & Version: MariaDB 11.2.3

### Description:
We have a BelongsToMany relation which seems to do a lot of queries eventhough the original pivot is empty?

We have the following setup:

Model: Compontent 
```...
    public function cook_products(): BelongsToMany
    {
        return $this->belongsToMany(Product::class)
            ->wherePivot('direction', ComponentProductDirection::ToProduct)
            ->withPivot(['direction', 'quantity']);
    }
```
And in Nova we have:
```
            BelongsToMany::make(__('Cook products'), 'cook_products', Product::class)
                ->searchable()
                ->fields(fn () => [
                    Number::make(__('Quantity'), 'quantity')
                        ->readonly(!$request->user()->isAdmin())
                        ->rules('required'),
                    Hidden::make('direction')
                        ->default(ComponentProductDirection::ToProduct),
                ]),
```

When hitting the details page this incurs a `/nova-api/products?search` request with the following filter (shortened):
```
[
  "search" => ""
  "filters" => "<some hash, removed for brevity>"
  "orderBy" => ""
  "perPage" => "5"
  "trashed" => ""
  "page" => "1"
  "viaResource" => "components"
  "viaResourceId" => "25"
  "viaRelationship" => "cook_products"
  "relationshipType" => "belongsToMany"
]
```
This results in 14 queries of which 10 are duplicate?

![image](https://github.com/laravel/nova-issues/assets/1492861/bd21b343-9623-4700-bc8e-032239e4a7ba)

(even though there were no relations)

If having 9 actual cook_products relations this balloons to 67 queries of which 7 where unique (!)

I'm not sure if this is a bug, a feature request or missing documentation. (or something else)

**Comment by fruitl00p** [comment]
Further inspection reveals that in the XHR request for /nova-api/ I can't alter the construction of the 'component' class to exclude all other relations (i.e. using a `without()` call in the nova-api/-request. Also It seems that this is where the issue stems from; both Component and 'Product' and the Pivot have even more releations that are N+1 Queried multiple times... Hence the massive increase in (duplicate) queries. 

Any way I can hook into this (without sacrificing the '$with = []' in my models?

**Comment by crynobone** [comment]
Please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
