### ISSUE TITLE
Error when updating code->json field

### ISSUE THREAD

**Issue by flashadvocate** [laravel/nova-issues#646]
I have a settings TEXT column that stores json on a `divisions` table. I'm using `Code::make('settings')->json()` to register the field, but when updating, I get the following error:

`Undefined property: App\Division::$settings`

Version of Nova is `1.1.3`. 

Field displays fine, but refuses to update

**Comment by basreklam** [comment]
I'm getting an error saying `Array to string conversion` when i'm trying to save the JSON.
Also on `1.1.3`.

`Code::make('Cart data', 'raw_cart_data')
                ->json()`

**Comment by age007nt** [comment]
@basreklam, add to your model: `protected $casts = ['raw_cart_data' => 'array']`

**Comment by basreklam** [comment]
> @basreklam, add to your model: `protected $casts = ['raw_cart_data' => 'array']`

Thanks, yeah - The save do work - however, it might screw things up, so be careful when using this.

**Comment by alexbowers** [comment]
Issues i'm able to reproduce:

If i have no casting on the model, and I try to store a JSON value like:

```json
{
  "one": "two",
  "two": "three"
}
```

This throws an SQL error:

![image](https://user-images.githubusercontent.com/842974/45981572-6556c400-c04d-11e8-8f99-3aeed9ef11fb.png)

Setting the cast to:

```php
protected $casts = [
    'info' => 'json',
];
```

allows it to save without any issues.

Perhaps a better error can be reported, but I don't feel like this is a bug having now tested it.

thoughts @davidhemphill ?

**Comment by davidhemphill** [comment]
Not a bug. This is the same as Date columns not being cast correctly on the model level.

**Comment by cjke** [comment]
Might not be a bug - but should it not be documented somewhere?

**Comment by dillingham** [comment]
@cjke it is documented on the framework docs, this has to be assumed when working with json IMO
https://laravel.com/docs/5.7/eloquent-mutators#array-and-json-casting

**Comment by cjke** [comment]
Perhaps. There is a level of frustration as I jump between these issues, the nova docs and the laravel docs. Maybe I shouldn't have targeted this issue in particular - but its the third issue tonight where I've cycled between the issues/docs trying to get an answer. It's not the end of the world, but for a paid product I wouldn't expect to have to do that

**Comment by dkulyk** [comment]
You can use 
```php
Code::make('Cart data', 'raw_cart_data')
    ->language('application/json')
```

**Comment by yehudahkay** [comment]
I think nova should handle without casts, or at least add this to the documentation
