### ISSUE TITLE
Nullable fields

### ISSUE THREAD

**Issue by victorpfm** [laravel/nova-issues#647]
When I have a null date, it is displayed as 'Invalid Date', but only on index. When on detail, it displays a dash as expected.

And what about nullable boolean fields? It is displayed as false by default, can I have a null boolean field that is not displayed as false?

**Comment by davidhemphill** [comment]
Null dates aren't displayed on the index. Boolean fields are true or false only for obvious reasons. 

If you have some code to show where an issue may be please post it.

**Comment by victorpfm** [comment]
> Null dates aren't displayed on the index.

Yes, they are displayed as 'Invalid Date'

![image](https://user-images.githubusercontent.com/21281931/45950506-77495000-bfd6-11e8-993b-b4f5edaa0fe1.png)

`Date::make('Nascimento')->format('DD/MM/Y'),`

Nova v1.1.3

**Comment by mattsims** [comment]
I am also seeing this issue using v1.1.3.

**Comment by davidhemphill** [comment]
Apologies, I misunderstood! This has been fixed and will be included in an upcoming release.

**Comment by edanisko** [comment]
Issue remains in v1.1.4

**Comment by davidhemphill** [comment]
@edanisko Create a new issue and supply some code demonstrating so.
