### ISSUE TITLE
BelongsToMany has many duplicate queries on detail page

### ISSUE THREAD

**Issue by niekdemelker** [laravel/nova-issues#6479]
- Laravel Version: 11.17.0
- Nova Version: 4.34.3
- PHP Version: 8.3.9
- Reproduction Repository: https://github.com/niekdemelker/issue-6479

### Description:
When using an `BelongsToMany` field, this will show all related models on the Details page. This request to fetch all relation records however calls the DB many times to fetch the ViaResource model. Sometimes over 20 times in one request (Strange enough `Model::preventLazyLoading(! app()->isProduction())` doesn't block this behaviour.).

The logging states this call is done repeatedly from 'Http/Requests/InteractsWithRelatedResources.php:72' and one time from 'Http/Requests/QueriesResources.php:38'.

### Detailed steps to reproduce the issue on a fresh Nova installation:

- run migrations & seeder
- create nova user
- Open Nova and navigate to 'service levels' and open the details page of the generated record
- Open Telescope and search on the tag 'bug' to see the recorded queries of this request

**Comment by crynobone** [comment]
Please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by niekdemelker** [comment]
> Please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

I already did that. the steps to reproduce take into account you use the provided repo. Se https://github.com/niekdemelker/issue-6479

**Comment by niekdemelker** [comment]
Do you still require more info? If you need more information on some parts please tell so I can Elaborate
