### ISSUE TITLE
Override JS components

### ISSUE THREAD

**Issue by victorpfm** [laravel/nova-issues#648]
I can't figure out how to override Nova's vue components to edit the resource detail header.

Should I edit the /nova folder's files and recompile or can I do it somewhere else?

And if I want to change globally the MomentJS locale, where should I do it?

I was able to do it on a nova-component by adding this to the card.js:

```
Nova.booting((Vue, router) => {
    Vue.component('confrontos-interclubes-card', require('./components/Card'));
    moment.locale('pt-br')
})
```

**Comment by davidhemphill** [comment]
Don't edit code in the nova folder. It'll simply get overwritten when you upgrade. Use tools to define custom components...even custom versions of the built-in ones.

**Comment by markacianfrani** [comment]
> Don't edit code in the nova folder. It'll simply get overwritten when you upgrade. Use tools to define custom components...even custom versions of the built-in ones.

So if I wanted to add, lets say a 4th action button next to delete, I would need to create a new Tool, add a new RouterLink, then add a custom version of ResourceTableRow, a custom ResourceTable, and a custom ResourceIndex ? 

How would you create a custom ResourceTable (or any other components) if it requires the InteractsWithResourceInformation mixin from 'laravel-nova?" Is there a way to import that from inside a tool?

**Comment by jasonlav** [comment]
+1

**Comment by davidhemphill** [comment]
You should only have to override the row component.

You could import `yarn add laravel-nova`.

**Comment by aglipanci** [comment]
@davidhemphill is there a simple example on how to override for example only the row component. That would be much appreciated!

**Comment by davidhemphill** [comment]
```js
import YourResourceTableRow from './YourResourceTableRow'

Vue.component('resource-table-row', YourResourceTableRow)
```

**Comment by njbarrett** [comment]
Here's a better example. Create your custom tool and then in your tool.js add:

```
import Tool from './components/Tool';

Nova.booting((Vue, router, store) => {
    Vue.component('resource-table-row', Tool);
});
```

**Comment by freshway** [comment]
@njbarrett Im triying something like you:
> tool.js
```javascript
import MyLens from './components/views/Lens';

Nova.booting((Vue, router, store) => {
    router.addRoutes([{
            name: 'nova-improvements',
            path: '/nova-improvements',
            component: require('./components/Tool'),
        }])
});
Nova.booting((Vue, router, store) => {
	Vue.component('lens', MyLens)
});
```
Script was compiled and loaded on navigator but, the main "lens" component is still executing.

Anyone know what might be happening, please?

I think that, my component is loading before the original.

**Comment by fbingha** [comment]
Is there a way to override the resource-table-row as used by a single resource, not for all resources?

**Comment by didix16** [comment]
> import YourResourceTableRow from './YourResourceTableRow'
> Vue.component('resource-table-row', YourResourceTableRow)
@davidhemphill 

Which file is suposed to insert those lines and which commands are necessary to properly view the changes?

Thanks in advance

**Comment by puzzledmonkey** [comment]
@freshway and anyone else who runs into this - when overriding default views for nova (which isn't recommended but if you gotta do it...)
> Script was compiled and loaded on navigator but, the main "lens" component is still executing.

```
import Lens from './components/Lens'

Nova.booting((Vue, router) => {
  router.beforeEach((to, from, next) => {
    if (to.name == 'lens') {
      next({
        name: 'custom-lens',
        params: Object.assign({}, to.params, { component: Lens }),
        query: to.query,
      })
    } else {
      next()
    }
  })

  Vue.component('lens', Lens)
  router.addRoutes([
    {
      name: 'custom-lens',
      path: '/resources/:resourceName/lens/:lens',
      component: Lens,
      props: true,
    },
  ])
})

```

inspired by https://github.com/DigitalCloud/nova-custom-views
