### ISSUE TITLE
Partition metrics do no show the chart correctly positioned

### ISSUE THREAD

**Issue by extrabright** [laravel/nova-issues#6486]
- Laravel Version: 10.48.16
- Nova Version: 4.32.12
- PHP Version: 8.3
- Operating System and Version: Macbook Air M3, OS Sonoma 14.5
- Browser type and version: Latest version of major browsers

### Description:

The partition metric when rendered doesn't display the chart correctly. Is somehow hidden and positioned in a not visible area. I think it's just a CSS problem. See the image below:

<img width="382" alt="Screenshot 2024-08-01 at 08 44 43" src="https://github.com/user-attachments/assets/ae407ab6-ea39-42a5-aa32-fe2ead3a2fc8">

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
