### ISSUE TITLE
Deprecation warning: Usage of DOMNodeInserted event

### ISSUE THREAD

**Issue by web-svb** [laravel/nova-issues#6489]
### Issue Title:
Deprecation Warning: Usage of `DOMNodeInserted` Event in Laravel Nova

### Description:
I encountered a deprecation warning related to the usage of the `DOMNodeInserted` event in Laravel Nova. This event is deprecated and no longer supported in modern browsers. The warning message is as follows:

**_[Deprecation] Listener added for a 'DOMNodeInserted' mutation event. Support for this event type has been removed, and this event will no longer be fired._**

This issue appears to be coming from a vendor file in Laravel Nova.

#### Steps to Reproduce:

1. **Open Laravel Nova Dashboard:**
   - Navigate to the Laravel Nova dashboard in your browser.

2. **Access Custom Tool:**
   - Go to the custom tool within Laravel Nova.

3. **Open Browser Console:**
   - Press `F12` or right-click on the page and select "Inspect" to open the browser's developer tools.
   - Click on the "Console" tab.

4. **Observe Deprecation Warning:**
   - Look for the deprecation warning related to `DOMNodeInserted` in the console logs as you interact with the page.

### Expected Behavior
Laravel Nova should use modern APIs like `MutationObserver` instead of deprecated events.

### Environment:
- **Laravel Version:** 11.19.0
- **Nova Version:** 4.34.3
- **PHP Version:** 8.3.6
- **Browser type and version:** Google Chrome 127.0.6533.88

### Additional Context:
The deprecation warning suggests using modern alternatives like `MutationObserver` for handling DOM mutations, as the deprecated event is no longer supported by browsers.

For further reference on this deprecation, please see the [Chrome Platform Status](https://chromestatus.com/feature/5083947249172480).

**Comment by crynobone** [comment]
> The issue seems to originate from a third-party library used in Laravel Nova.

As this is coming from 3rd-party instead, doesn't that mean it requires an update from the 3rd-party library instead?

**Comment by crynobone** [comment]
Will be part of Nova 5 as we update to Trix v2
