### ISSUE TITLE
Lens count request doesn't contain the container property

### ISSUE THREAD

**Issue by mostafa-rz** [laravel/nova-issues#6491]
- Laravel Version: 11.2.0
- Nova Version: 4.33.1
- PHP Version: 8.2.20
- Database Driver & Version: mysql 8.0.32
- Operating System and Version: Ubuntu 20.04.6 LTS

### Description:

The Nova class `src/Http/Requests/LensCountRequest.php` inherits from the Laravel class [`src/Illuminate/Foundation/Http/FormRequest.php`](https://github.com/laravel/framework/blob/11.x/src/Illuminate/Foundation/Http/FormRequest.php). The Laravel `FormRequest` has a [container property](https://github.com/laravel/framework/blob/7e696458c3a90972320305c72e0683162edb8f30/src/Illuminate/Foundation/Http/FormRequest.php#L24) that is not nullable. **_The container is null when a count request is sent to the backend._**

The reason is `LensCountRequest()->toQuery()` method recreates the request by [`LensRequest::createFrom($this)`](https://github.com/laravel/framework/blob/7e696458c3a90972320305c72e0683162edb8f30/src/Illuminate/Http/Request.php#L439) method. This results in a new request object but without the container. You can see the usage of this method in Laravel [`FormRequestServiceProvider()`](https://github.com/laravel/framework/blob/7e696458c3a90972320305c72e0683162edb8f30/src/Illuminate/Foundation/Providers/FormRequestServiceProvider.php#L33). After they called the `FormRequest::createFrom()`, they also set the container and redirectors again. Please consider this in `LensCountRequest()->toQuery()` so the newly created request contains the container property.
```
/**
 * Transform the request into a query.
 *
 * @return \Illuminate\Database\Eloquent\Builder
 */
public function toQuery()
{
    return tap($this->lens()->query(LensRequest::createFrom($this), $this->newSearchQuery()), function ($query) {
        if (! $query instanceof Builder) {
            throw new LensCountException('Lens must return an Eloquent query instance in order to count lens resources.');
        }
    });
}
```

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. make a lens
2. make a filter for the  lens
3. Inside the `apply()` method of the filter check the `$request` when the count request is reach there
4. The `$request` object doesn't contain the container

**Comment by crynobone** [comment]
Laravel Framework isn't 100% strict type, while the doc block may say `@var Illuminate\Contracts\Container\Container` if you convert it to strict type it needs to be defined as `protected Container|null $container` since the parameter is not initiated within the constructor.

**Comment by mostafa-rz** [comment]
@crynobone 
It is not type-hinted but it doesn't mean that you can break the parent class functionality. If it is a `FormRequest()`, it must be possible to validate it by the [Laravel Form Request Validation](https://laravel.com/docs/11.x/validation#form-request-validation). When you remove the container, the Laravel `authorize()` method fails, because it needs the container.
