### ISSUE TITLE
allowDuplicateRelations update/detach not working as expected

### ISSUE THREAD

**Issue by Norgul** [laravel/nova-issues#6496]
- Laravel Version: v11.15.0
- Nova Version: v4.34.3
- PHP Version: 8.2.20
- Database Driver & Version:
- Operating System and Version: MacOS Sonoma 14.5 (23F79)
- Browser type and version: Chrome Version 127.0.6533.90 (Official Build) (arm64)

### Description:
Having a M:M relation which allows duplicate relations, update and detach do not work as they should be. 

```php
// Migration
Schema::create('movement_product', function (Blueprint $table) {
    $table->id();
    $table->foreignId('movement_id')->constrained();
    $table->foreignId('product_id')->constrained();
    .... // extra pivot fields, but no unique indices
    $table->timestamps();
});

// Relation 
BelongsToMany::make('Products')
    ->fields(...)
    ->allowDuplicateRelations(),
```

If I attach two or more of the same product, initially it creates them okay. However if I want to detach only one, _ALL_ get detached. 

Same thing happens when updating. If I update one product, pivot values of other products copy onto them.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Described above.

Issue is the same as https://github.com/laravel/nova-issues/issues/5779 which received no answer.

**Comment by Norgul** [comment]
Did you actually try to reproduce the issue in those 2 minutes you were looking at it, or are you expecting me to do all the work and possibly even fix it myself?

**Comment by crynobone** [comment]
@Norgul I'm well aware of the previous issues and it was already fixed with additional dusk tests. 

![SmartSelect_20240808_161018_Chrome.png](https://github.com/user-attachments/assets/b846922c-bada-4124-b73d-bcdb4bf35556)

So, there not enough information above to determine if there additional use case not covered intially hence we need the reproducing repository.

**Comment by Norgul** [comment]
@crynobone As you can see from a screenshot, payload to detach endpoint are resource IDs, not pivot row ID, the very same thing the PR was supposed to fix.

![image](https://github.com/user-attachments/assets/70c49157-6c26-4bd7-b35c-7117458548f1)

I tried with a fully basic M:M relation 

```php
// Migration
Schema::create('sale_point_stock_point', function (Blueprint $table) {
    $table->id();
    $table->foreignId('sale_point_id')->constrained();
    $table->foreignId('stock_point_id')->constrained();
    $table->timestamps();
});

// Relation
public function stockPoints(): BelongsToMany
{
    return $this->belongsToMany(StockPoint::class)->withTimestamps();
}

// Resource
BelongsToMany::make('Stock points')->allowDuplicateRelations(),
```

Literally a textbook example, which results in same behavior:

![image](https://github.com/user-attachments/assets/841c8c1d-28ff-44bc-997a-ea63a8d65a2c)

So you tell me...what am I doing wrong which is not according to documentation? 

Where can I see the PR you screenshotted? Checking a fix would for sure shorten my time then actually making a full blown repo...

**Comment by crynobone** [comment]
![CleanShot 2024-08-08 at 16 44 00](https://github.com/user-attachments/assets/6add0d4f-acfa-467e-8621-ff70bd66ce8e)

To determine the pivot ID we need to provide `sale_point_stock_point.id` to the relationship, otherwise, Nova wouldn't have access to it.

**Comment by Norgul** [comment]
Thanks. That resolves it.

**Comment by potsky** [comment]
Hi ! Is it still working on Nova 5 ?

https://cln.sh/C6wChd7rBFGpMy6rVSkZ+

Demo repo : https://github.com/potsky/nova
