### ISSUE TITLE
Empty textarea, remove Show Content?

### ISSUE THREAD

**Issue by Jam0r85** [laravel/nova-issues#65]
Whilst having the 'Show Content' toggle on a textarea is great, it makes it difficult to know whether the field has content or not when just glancing at the detail page.

Perhaps disable this link when the textarea has no value?

**Comment by NSpehler** [comment]
And maybe add an argument we can pass to Textarea to enable/disable the Show Content button?

**Comment by davidhemphill** [comment]
This has been fixed and will be included in an upcoming release.

**Comment by Jam0r85** [comment]
Perfect thank you!
