### ISSUE TITLE
Add optional download for files, images & avatars

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#650]
![downloadable](https://user-images.githubusercontent.com/29180903/45923293-6e5e5e80-beb0-11e8-8089-6bd94cf3db09.png)

Need the ability to add meta or something to instruct File.php to return false for `downloadable`

Also, would be nice if Avatar has this set as false initially. 

BONUS

A canDownload or otherwise would be handy in a admin system

**Comment by lucasromanojf** [comment]
This is a must-have. It is a very simple change. I did it in less than 5 minutes directly in code while this is not added to core.

**Comment by davidhemphill** [comment]
This has been added and will be included in the next release. You'll be able to call `disableDownload` on the `File`, `Image`, and `Avatar` fields. 👍

**Comment by lucasromanojf** [comment]
Thanks @davidhemphill !
