### ISSUE TITLE
Table metrics truncated information

### ISSUE THREAD

**Issue by enricv** [laravel/nova-issues#6503]
- Laravel Version:  9.52.16
- Nova Version:  4.35.0
- PHP Version: 8.3.2
- Database Driver & Version:
- Operating System and Version:  Windows  11 / Linux (3.10.0-1160.99.1.el7.x86_64)
- Browser type and version: Chrome 1270.6533.120 

### Description:

After this modification to nova https://github.com/laravel/nova-issues/issues/6487 included in 4.35.0 relases, make my tables transform from 

![image](https://github.com/user-attachments/assets/88c61583-440d-49a8-86f2-afef22fc4dca)

to 

![image](https://github.com/user-attachments/assets/4576f52c-4130-45bc-805a-3a0a0e402437)

**Comment by jeremynikolic** [comment]
Hi @enricv, thanks for reporting this issue 🙏 

I've managed to reproduce on Chrome as specified, working on a fix 👍

**Comment by enricv** [comment]
Great! Thanks!

**Comment by jsmit99** [comment]
@jeremynikolic is there any ETA when this will be released? As especially now on safari mobile it's almost unreadable.

**Comment by jeremynikolic** [comment]
Let me get back to you on that 👌

**Comment by jeremynikolic** [comment]
@jsmit99 we are finalising the minor release which will contain the fix so any days now 👌
