### ISSUE TITLE
Inconsistent array structuring

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#651]
I would assume these two would follow the same structure
```php
Select::make('Field')->options([
    'value-1' => 'Some Label 1',
    'value-2' => 'Some Label 2'
])
```
> Above is **select field** & below is the select options **for a filter**
```php
public function options(Request $request)
{
    return [
        'Some Label 1' => 'value-1',
        'Some Label 2' => 'value-2',
    ];
}
```

I was hoping to populate both with the same config array but can't

**Comment by 907544030** [comment]
you may use the `displayUsingLabels` method

**Comment by dillingham** [comment]
@907544030 I am for the field. But wanting to use the same array from a single source like a config is not possible.

**Comment by dillingham** [comment]
Feels like there should only be one universal format for select options

**Comment by chescos** [comment]
If you are using an array from a config file, you could use [array_flip](https://secure.php.net/manual/en/function.array-flip.php) like this:

```php
Select::make('Field')->options(config('some.config.array'))
```

```php
public function options(Request $request)
{
    return array_flip(config('some.config.array'));
}
```

**Comment by dillingham** [comment]
@chescos thanks, yeah I'll do that
