### ISSUE TITLE
Multiselect for Actions not working anymore (Uuid Model)

### ISSUE THREAD

**Issue by MBeckers** [laravel/nova-issues#6515]
- Laravel Version: 10.48.20
- Nova Version: 4.35.0
- PHP Version: 8.3.10
- Database Driver & Version: MySQL
- Operating System and Version: Ubuntu 22.04
- Browser type and version: Chrome 128.0.6613.85

### Description:
With Introduction of Change 
`Fix ActionRequest inconsistently receiving comma separated string instead of array.`
in Laravel Nova 4.35.0

```
$query = $this->viaRelationship()
            ? $this->modelsViaRelationship()
            : $this->toQueryWithoutScopes()->whereKey(Arr::wrap($this->resources));
```

Instead of

```
$query = $this->viaRelationship()
            ? $this->modelsViaRelationship()
            : $this->toQueryWithoutScopes()->whereKey(explode(',', $this->resources));
```

Will cause to wrap the resources string into an array which will look like
```
[
     0 => ”firstId,secondId”
]
```

Thus the Request results in not finding any results and returning "Sorry you are not authorized to perform that action"

It might be only happen for Uuids, i had not the time to dig if this issue occurs also for integer IDs

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

Also please make sure you running on the latest assets to ensure the frontend send the correct format. If you override any of the frontend (not sure what's "Multiselect for Action" does) then your frontend code need to be updated
