### ISSUE TITLE
Qatar missing from Country field

### ISSUE THREAD

**Issue by KickSchutte67** [laravel/nova-issues#6516]
- Laravel Version: 10.28.0
- Nova Version: 4.28.0
- PHP Version: 8.1.10

### Description:

Qatar is missing from the country dropdown list on nova version 4.28.0. Is this fixed in a newer release?

**Comment by jeremynikolic** [comment]
Hi @KickSchutte67, thanks for reaching out to us.

Please double check as I can see QA - Qatar being part of our country field since its creation and still present as of today 🤔
