### ISSUE TITLE
Action doesn't work if applied to resource that is found via index search

### ISSUE THREAD

**Issue by bosniakus** [laravel/nova-issues#6518]
- Laravel Version: 11.9
- Nova Version: 4.35.0
- PHP Version: 8.2
- Database Driver & Version: mysql
- Operating System and Version: Windows 11 (Herd)
- Browser type and version: Firefox / 129.0.2 (64-bit)
- Reproduction Repository: ---

### Description:
I have model 'Category' and action 'Add parent to category' which have 'Parent' field (BelongsTo). Everything is set up correctly and it works as intended. If, for example, I choose category 'Aston Martin' and add parent category 'Car' to it via action 'Add parent to category' it works.

**/resources/categories?categories_page=1** - Action on this URL does work!

Issue appear when I use index table search field. Once resources I want to use action on are found, action does not work with error message "This Parent may not be associated with this resource." 

**/resources/categories?categories_page=1&categories_search=aston+martin** - Action on this URL does NOT work

This error message is pretty consistent. I tried to refresh page, to select different parent category without luck.

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Create Model
- Create action that change 'parent_id' on created Model via BelongsTo field
- Search for Resource you want to apply action on
- Apply action

![image](https://github.com/user-attachments/assets/cbc4867b-74c1-445e-bb8e-0ac315aa23fa)

**Comment by jeremynikolic** [comment]
Hi @bosniakus , thanks for reporting this.
I am unsure I understand the full setup you have, therefore making it hard to reproduce.

Please share a sample reproducing repo or code example of how you have set those two models and the mentioned action 🙏

**Comment by bosniakus** [comment]
Hello @jeremynikolic ,

Here is bare minimum repository where you are able to reproduce this issue/bug : https://github.com/bosniakus/laravel-nova-action-bug

Steps to reproduce:
- Create two categories ( "child" and "parent" )
- Try to use action "Add category parent" - It should work
- Search for "child" using index table search
- Once found try again to use action "Add category parent" again - This wont work

Let me know if you need more information.

**Comment by jeremynikolic** [comment]
Thanks @bosniakus I'll be looking into it 🕵️

**Comment by jeremynikolic** [comment]
I've managed to reproduce the issue, investigating the root cause of it 🕵️
