### ISSUE TITLE
Question: Is the 'other' group in the menu translatable?

### ISSUE THREAD

**Issue by JiFus** [laravel/nova-issues#652]
Any help would be appreciated.

![screen shot 2018-09-23 at 12 09 57](https://user-images.githubusercontent.com/9193686/45926880-f16fcb00-bf29-11e8-9d03-73b059c9fc06.png)

**Comment by AegirLeet** [comment]
"Other" is the default, defined in `Laravel\Nova\Resource::$group`. You can override it for all your Resources in your `App\Nova\Resource`:
```
/**
* @var string
*/
public static $group = 'Your translated value';
```

Of course, you can also do this on a per-Resource basis instead.

**Comment by bonzai** [comment]
#635

**Comment by davidhemphill** [comment]
See linked issue above for the solution.
