### ISSUE TITLE
Action class always returns 1 model, regardless of the items the user selects

### ISSUE THREAD

**Issue by sacriley** [laravel/nova-issues#6520]
- Laravel Version: 10.11.2
- Nova Version: 4.35.0
- PHP Version: 8.3
- Database Driver & Version:
- Operating System and Version: CentOS
- Browser type and version: Chrome latest
- Reproduction Repository: https://github.com/###/###

### Description:
I can only retrieve one item for my action when selecting multiple items on the index page, unless I update Laravel Nova to version 4.34.3.

I searched for the problem. this class should be fixed:
`\Laravel\Nova\Http\Requests\ActionRequest::toSelectedResourceQuery`

It always returns 1 model, regardless of the items the user selects:
`$this->toQueryWithoutScopes()->whereKey(explode(',', $this->resources))`

**Comment by webard** [comment]
Same problem in my app with newest version of Nova.

**Comment by crynobone** [comment]
Our dusk tests is still passing with no error at this point. Yes the frontend code has been changed but as long as you not overriding the default and update the assets during the upgrade you should be fine.

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by marcin-tazbir** [comment]
I can confirm we are experiencing the same issue since we updated to the newest version. Recompiling assets didn't help either.

**Comment by tobidotYD** [comment]
I had the same issue,
but like @crynobone said, doing 

``` 
php artisan nova:publish
php artisan view:clear
```

Solved the issue it seems.

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem with reproduction repository as requested above.
