### ISSUE TITLE
Trashcan appears when selecting all even though policy has delete false

### ISSUE THREAD

**Issue by lauritsen** [laravel/nova-issues#6524]
- Laravel Version: 11.10.0
- Nova Version: 4.35.1
- PHP Version: 8.3
- Database Driver & Version: mariadb
- Operating System and Version: Windows 10 with app running in sail on WSL
- Browser type and version: Tested in Firefox and Brave
- Reproduction Repository: 

### Description:
I have a resource where the policy returns false for delete. 
When selecting only the current page, the actions dropdown appears (as expected)
![image](https://github.com/user-attachments/assets/70320793-9ee1-4f61-aaa2-e1816294597e)
When selecting all entries, the actions dropdown appears, but next to it also the trashcan (not expected). 
![image](https://github.com/user-attachments/assets/1e275b48-d3c7-457b-a862-05c304900de2)

Clicking the trashcan opens the popup asking for confirmation of deletion, but confirming does not delete anything (as expected). 

It seems to me like some frontend issue regarding when to show the trashcan and when not to. The policy seems to be in place, as I cannot delete the entries.

**Comment by lauritsen** [comment]
I don't see how the number of records affect the resource policy? My screenshots with one record where just an example. I have another resource where I have multiple pages of records. 
To me it is inconsistent, that if I select what is on the first page there is no trashcan. But when select all records on all pages suddenly the trashcan appears. Also the trashcan/deletion doesn't work, which tells me the trashcan shouldn't be there in any of the cases. 
I don't see the massive performance issue, as the policy relates to the resource, not the records of that resource... 
Or am I missing something? 
Happy to provide a repo with reproduction if that helps, or to try to explain myself clearer :)

**Comment by crynobone** [comment]
> I don't see how the number of records affect the resource policy? 

Nova need to check if it can execute `delete` on each record. This has been reported before and we not taking any action due to this fact for now.

**Comment by lauritsen** [comment]
> > I don't see how the number of records affect the resource policy?
> 
> Nova need to check if it can execute `delete` on each record. This has been reported before and we not taking any action due to this fact for now.

But then why show the trashcan?
