### ISSUE TITLE
Login Form return too many redirect

### ISSUE THREAD

**Issue by laravelwebdev** [laravel/nova-issues#6525]
- Laravel Version: 11.2.0
- Nova Version: 4.35.1
- PHP Version: 8.2
- Database Driver & Version: MySQL
- Operating System and Version: Macos Sonoma
- Browser type and version: Chrome

### Description:
When Nova path in nova.config set to empty, php artisan optimize make login form return too many redirect, maybe nova login route conflict with login › Illuminate\Routing › RedirectController.

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Set Nova Config path to 'path' => '',
2. run php artisan optimize

**Comment by crynobone** [comment]
See https://github.com/laravel/nova-issues/discussions/6450#discussioncomment-9909592

**Comment by laravelwebdev** [comment]
Same here, when you run php artisan optimize with path ='/', login form cannot be accessed
