### ISSUE TITLE
Action::message doesn't work.

### ISSUE THREAD

**Issue by basreklam** [laravel/nova-issues#653]
I'm having a brand new action that only contains the following (for now).

```
public function handle(ActionFields $fields, Collection $models) {
     Action::message('This is a test message');
}
```

But when i'm performing the action I'm not getting that message, neither do i when using the `Action::danger()` method.

What's wrong?

**Comment by AegirLeet** [comment]
Missing return statement.
```
return Action::message('This is a test message');
```

**Comment by basreklam** [comment]
> Missing return statement.
> 
> ```
> return Action::message('This is a test message');
> ```

Wow.. Thanks....

**Comment by BobbyBorisov** [comment]
@AegirLeet i am trying to return Action::danger('some text') and it is not working at all..

**Comment by adick** [comment]
@AegirLeet confirmed, not working in 1.3.1, Nova still displays the default message.

**Comment by stydav** [comment]
Action::danger still not working in 2.2.0
