### ISSUE TITLE
NovaNotification class translation

### ISSUE THREAD

**Issue by eom-eom** [laravel/nova-issues#6535]
- Laravel Version: 111.9
- Nova Version: 4.35.1
- PHP Version: 8.3.11

The chains ->message() and->action() text doesn't translated.

Here's my sample Listener class.
![Screenshot 2024-09-19 at 1 01 19 PM](https://github.com/user-attachments/assets/ab8d343d-4e6c-4587-895e-90bce38f110f)

then this is the output.
![Screenshot 2024-09-19 at 12 49 22 PM](https://github.com/user-attachments/assets/7be74a26-ddac-4d51-9cae-04cabb08b674)

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
