### ISSUE TITLE
BelongsToMany Field Not Working on Create/Edit Forms

### ISSUE THREAD

**Issue by badrshs** [laravel/nova-issues#6536]
## Environment

- Laravel Version:  ^11.9
- Nova Version: 4.33.3
- PHP Version: 8.2.12 
- Operating System and Version: Windows 11 
 
## Issue Description

I'm developing an education course website using Laravel Nova. I'm trying to implement a feature in my `CourseSession` resource that allows an admin to assign multiple beneficiaries (students) to a session at once. However, the current implementation is not working as expected on any view.

## Current Behavior

- Create Form: Unable to assign multiple beneficiaries when creating a new CourseSession and it's not even showing there.
- Edit Form: Unable to assign or modify multiple beneficiaries when editing an existing CourseSession.
- Detail View: I can see a table of beneficiaries and add them, but only one at a time and that expected.

## Expected Behavior

On views (create, and edit):
1. There should be a field where the admin can select multiple beneficiaries at once.
3. When the form is submitted, it should create multiple entries in the `beneficiary_session` pivot table, one for each selected beneficiary.
4. The interface should allow for easy selection of multiple beneficiaries without having to add them one by one.

## Current Database Structure

- `course_sessions` table
- `beneficiaries` table
- `beneficiary_session` pivot table

## Current Implementation

Here's my current implementation in the `CourseSession` Nova resource:

```php
<?php

namespace App\Nova;

use Laravel\Nova\Fields\ID;
use Laravel\Nova\Fields\BelongsTo;
use Laravel\Nova\Fields\BelongsToMany;
use Laravel\Nova\Http\Requests\NovaRequest;

class CourseSession extends Resource
{
    public static $model = \App\Models\CourseSession::class;

    public function fields(NovaRequest $request)
    {
        return [
            ID::make()->sortable(),

            BelongsTo::make('Course'),

            // Other fields for CourseSession...

            BelongsToMany::make('Beneficiaries')
                ->searchable() // I don't care at the moment about the filter, I just need  the BelongsToMany to work
        ];
    }
}
```

And here are the relevant parts of my models:

```php
// App\Models\CourseSession.php
class CourseSession extends Model
{
    public function course()
    {
        return $this->belongsTo(Course::class);
    }

    public function beneficiaries()
    {
        return $this->belongsToMany(Beneficiary::class, 'beneficiary_session'));
    }
}

// App\Models\Beneficiary.php
class Beneficiary extends Model
{
    public function courses()
    {
        return $this->belongsToMany(Course::class);
    }

    public function sessions()
    {
        return $this->belongsToMany(CourseSession::class, 'beneficiary_session');
    }
}

// App\Models\Course.php
class Course extends Model
{
    public function sessions()
    {
        return $this->hasMany(CourseSession::class);
    }

    public function beneficiaries()
    {
        return $this->belongsToMany(Beneficiary::class);
    }
}
```

## The Problem

The multi-select functionality for beneficiaries is not working as expected on any view:

1. On the create form, I'm unable to select and assign multiple beneficiaries to a new CourseSession.
2. On the edit form, I can't modify multiple assigned beneficiaries or add multiple new ones to an existing CourseSession.

## Questions

1. How can I modify my `BelongsToMany` field to allow multiple selections on all views (create, and edit)?
2. Is there a specific Nova field or configuration I should be using to enable bulk assignment of beneficiaries instead of this?
4. Are there any known issues or limitations with `BelongsToMany` fields in Nova that could be preventing multi-select functionality?

Any help or guidance would be greatly appreciated. Thank you!

**Comment by jeremynikolic** [comment]
Thanks for reaching out @badrshs 🙏 

A couple of misunderstanding here: 
- The create form will not contain Many to Many relationships, the resource's model get created then the relationship shows on the details form where you may attach other models as well as edit the pivot table fields if any.
- Your BelongsToMany field seems to be lacking pieces, please look at [BelongsToMany](https://nova.laravel.com/docs/resources/relationships.html#belongstomany)

For further assistance setting things up, please reach out to our support via the Nova website.

As this repo is dedicated for discussing bugs or feature request/improments.
