### ISSUE TITLE
Chinese value in composer.json became unreadable after created asset

### ISSUE THREAD

**Issue by leililei** [laravel/nova-issues#654]
My composer.json became this:

![composer.json](https://user-images.githubusercontent.com/10574520/45927167-8215cd80-bf61-11e8-9016-d531fdceb5ae.png)

to solve this, plz add `JSON_UNESCAPED_UNICODE` to `json_encode($composer, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)` in AssetCommand/ThemeCommand/...

```php
        file_put_contents(
            base_path('composer.json'),
            json_encode($composer, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)
        );
```

**Comment by alexbowers** [comment]
@907544030 Are you able to provide the steps you went through to cause this issue?

**Comment by 907544030** [comment]
execute nova:card or other custom asset commands, and composer.json will be updated while you say yes to add asset to composer.json.

**Comment by alexbowers** [comment]
Confirmed bug.

Happens with any non-ascii characters.

`îéíáå` are examples of others characters it happens with.

Steps to reproduce:

In your `laravel` `composer.json` file, change the name of the package to be:

`anything/éasd` and then run `php artisan nova:asset vendor/name` and it will break immediately.

**Comment by jbrooksuk** [comment]
Replicated in v2.0.9 - pushing a PR which fixes this upstream now.
