### ISSUE TITLE
Database sessions

### ISSUE THREAD

**Issue by msucevan** [laravel/nova-issues#6548]
- Laravel Version: 11.26.0
- Nova Version: 4.35.2
- PHP Version: 8.3
- Database Driver & Version: MySQL
- Operating System and Version: MacOS 15.0
- Browser type and version: Chrome

### Description:
I'm trying to use database session. I published the migrations file and changed the `SESSION_DRIVER=database`, but looks that when is login with Nova, is not storing the session in the database. I'm missing something or I need to rewrite the login method?

**Comment by crynobone** [comment]
1. Nova login is handled via `laravel/ui` and uses Laravel Authentication feature.
2. It uses stateful authentication and should rely on Laravel Session feature.
3. Check the configured value using `php artisan about`

**Comment by msucevan** [comment]
> 3\. php artisan about

Many thanks for your assistance.

Running the command `php artisan about` I realised that the session was still file. So, the first thing that come to my mind was the cache. Refreshing the cache solved my problem.

Another time, many thanks!
