### ISSUE TITLE
Tag fields don't work with replication

### ISSUE THREAD

**Issue by puzzledmonkey** [laravel/nova-issues#6549]
- Laravel Version: 11.26.0
- Nova Version: 4.35.2
- PHP Version: 8.3.6
- Reproduction Repository: https://github.com/puzzledmonkey/nova-issues

### Description:

Tag fields do not fill when replicating resources

### Detailed steps to reproduce the issue on a fresh Nova installation:

1. Checkout the reproduction repository
2. Create a Tag with a name
3. Create a Customer and use the tag you just created in the Tags field
4. Replicate the Customer
5. Observe the Tags field is not populated with the tags from the Customer you are replicating

**Comment by crynobone** [comment]
Replicating resource wrap around Eloquent Model Replication where it doesn't automatically replicate relationship: https://laravel.com/docs/11.x/eloquent#replicating-models

You should create an observer and populate relationship based on your requirement: https://github.com/laravel/nova-issues/discussions/4544#discussioncomment-6158061

**Comment by puzzledmonkey** [comment]
@crynobone Sorry but that is a ridiculous workaround

```
Nova::whenServing(function (NovaRequest $request) use ($product) {
    $existing = Product::find($request->input('fromResourceId'));
    $product->wristbands = $existing?->wristbands;
    $product->carpasses = $existing?->carpasses;
});
```

Why can't Nova do this automatically like it does for every other field?
