### ISSUE TITLE
Slug field not working within Panels

### ISSUE THREAD

**Issue by MaxKorlaar** [laravel/nova-issues#6552]
- Laravel Version: 11.26.0
- Nova Version: 4.35.2
- PHP Version: 8.3.12
- Database Driver & Version: MySQL 8.0.33
- Operating System and Version: macOS 15.0.1
- Browser type and version: Google Chrome 129.0.6668.90

### Description:
The Slug field does not seem to work properly when it is placed inside a Panel's Tab. Whenever the field that the slug is for is updated, a request is made to `/nova-api/undefined/field/slug/preview`, where `undefined` should actually be the name of the resource. When I move the Slug field out of the Tab's fields the field works properly again.

I did some very quick digging and it seems that the prop `resourceName` isn't defined on the `SlugField.vue` component whenever it's placed inside a Tab. I haven't taken the time to figure out why that is but I noticed that this prop is actually explicitly passed to a bunch of other fields, but not the Slug field.

### Detailed steps to reproduce the issue on a fresh Nova installation:

Add a Slug field inside a panel:

```
new Tabs('Tabs', [
                    Tab::make('Content', [
                        Text::make('Title', 'title'),

                        Slug::make('Slug', 'slug')
                            ->from('title')
                     ]
                  ...
])
```

**Comment by crynobone** [comment]
See https://github.com/eminiarts/nova-tabs/issues/262

**Comment by MaxKorlaar** [comment]
Good catch, I literally just noticed this and was typing this very response. My bad! I'll take it up there.
