### ISSUE TITLE
Custom query in `buildIndexQuery` does not work

### ISSUE THREAD

**Issue by damarinov1** [laravel/nova-issues#6553]
- Laravel Version: 10.48.22
- Nova Version: 4.29.4
- PHP Version: 8.2
- Database Driver & Version: Postgresql 15

### Description:
I am trying to override the `buildIndexQuery()` with my own query without using the query instance. The reason is that I want to fetch data from a materialised view table which is different from the Resource model. Essentially, I want to decouple from the resource model and build the query on my own. However, the custom query is ignored when I load the resource in the browser. Dumping the query with a dd() inside buildIndexQuery is showing my query (the one that I want to use), but it's ignored and its building the query from the resource's model when I load the resource in the browser.

```php
    public static function buildIndexQuery(
        Request $request,
        $query,
        $search = null,
        array $filters = [],
        array $orderings = [],
        $withTrashed = TrashedStatus::DEFAULT
    ) {
        $filtersArray = self::getFiltersAsSimpleArray($filters);

        return (new CompanyReportsRepository($filtersArray))->getIndexQuery();
    }
``` 
Note that this logic worked on Nova 3.

### Detailed steps to reproduce the issue on a fresh Nova installation:
- Create a resource called Company.
- Create a resource called Articles and add fields corresponding to the Company model (id, name, etc.).
- Add `buildIndexQueryMethod` in Articles and return a query, for example
```php
return Company::query();
```
- Observe that Nova is building the query from the Model (Article) and not from the one that we provided earlier (Company).

**Comment by crynobone** [comment]
Sorry, this is not the intended use of the method and while it may have worked before it was never design for that.
