### ISSUE TITLE
Associatable search requests return 404

### ISSUE THREAD

**Issue by lozobojan** [laravel/nova-issues#6556]
- Laravel Version: 10.48.22
- Nova Version: 4.35.2
- PHP Version: 8.2
- Database Driver & Version: MySQL 5.7
- Operating System and Version: ubuntu 22.04

### Description:

From this version, associatable search requests return 404. 

For example, `nova-api/customer-complaints/associatable/products?search=beef&resourceId=` works in v4.35.1 but not in 4.35.2.

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by lozobojan** [comment]
I have a `Complaint` model that is related to `Product` model like this:

`public function products()
    {
        return $this->belongsToMany(\App\Models\Product::class, 'product_complaint', 'complaint_id', 'product_id');
    }
`

In Nova Complaint resource, I defined a Multiselect using https://github.com/outl1ne/nova-multiselect-field package:

`Multiselect::make('Products Affected', 'products')->belongsToMany(\App\Nova\Product::class)`

The thing is, it works in v4.35.1 but its search for products in v4.35.2 uses this route: `nova-api/customer-complaints/associatable/products?search=beef&resourceId=` and it returns 404.

**Comment by phatmateo** [comment]
For additional context, someone posted this issue on the nova-multiselect-field package repo https://github.com/outl1ne/nova-multiselect-field/issues/255 @crynobone
