### ISSUE TITLE
Compile 3rd Party Assets For Production

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#656]
Currently if I have 10 packages installed, I may have 10 scripts & 10 css files loading per page.
Even if the current page is unaffected by said packages. That's alot of requests 😨  

**Solution**
`nova:compile` command that loops over the files and bundle their output into one single file.
Include them as they'd render in the html and there is no difference other than http requests.

**update** started a package but can't get the full list of files in a service provider
https://github.com/dillingham/nova-compile

**Comment by taylorotwell** [comment]
Pretty good idea.

**Comment by dillingham** [comment]
Here's a jump on it 😄 would need a `Nova` method for checking compiled

```php
<?php

namespace App\Console\Commands;

use Laravel\Nova\Nova;
use Illuminate\Console\Command;

class NovaCompile extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'nova:compile';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Compile assets for production';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $css = "";
        $js = "";

        foreach (Nova::availableStyles(request()) as $name => $path) {
            $css .= file_get_contents($path);
        }

        foreach (Nova::availableScripts(request()) as $name => $path) {
            $js .= file_get_contents($path);
        }

        \Storage::put('css/compiled.css', $css, 'public');
        \Storage::put('js/compiled.js', $js, 'public');
    }
}
```

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
