### ISSUE TITLE
ExportAsCSV doesn't work

### ISSUE THREAD

**Issue by EK713** [laravel/nova-issues#6563]
- Laravel Version: 11.27.2
- Nova Version: 4.35.3
- PHP Version: 8.2
- Database Driver & Version: 
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:

ExportAsCSV action doesn't work and gives no output after clicking on the export button!

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
