### ISSUE TITLE
Excessive database query when getting resource index (select ... from ... where id is null)

### ISSUE THREAD

**Issue by ruark** [laravel/nova-issues#6567]
Repo for reproduce: https://github.com/ruark/nova-issue-6564

### Discussed in https://github.com/laravel/nova-issues/discussions/6566

<div type='discussions-op-text'>

<sup>Originally posted by **ruark** October 23, 2024</sup>
- Laravel Version: 11.27.2
- Nova Version: 4.35.3
- PHP Version: 8.2.24
- Database Driver & Version: oci8 (yajra/laravel-oci8 11.6.2)

### Description:
When we open the resource index, the system makes a strange query to the database like this:
`select * from (select * from "TABLE" where "TABLE"."ID" is null) where rownum = 1`

In this case, "id" is the primary key. This behavior is implemented in the method `findModel($resourceId = null)` in the trait `\vendor\laravel\nova\src\Http\Requests\InteractsWithResources.php`

Such a query is executed every time when accessing the index of any resource that does not carry any logic. However, given a large table in the database, it greatly affects performance.</div>

In continuation to issue https://github.com/laravel/nova-issues/issues/6564

This is not related to the database type. **I tested with PostgreSQL** - the same bug is present there too. Tried with a fresh installation.

To reproduce the problem, add the following code to the `register()` method of the `App\Providers\AppServiceProvider` class:

```
DB::listen(function ($query) {
    Log::debug($query->sql, $query->bindings);
});
```

Then open the index page of any resource, for example `https://site/nova/resources/users`.

Next, look at the log file, where you will see something like this:
`[2024-10-24 03:52:32] local.DEBUG: select * from "users" where "users"."id" is null limit 1`

Full log: [laravel.log](https://github.com/user-attachments/files/17502053/laravel.log)

Repo for reproduce: https://github.com/ruark/nova-issue-6564

If you also can't reproduce the problem and close this issue - I promise, I will not write about this problem here anymore. After that, for myself, I will correct this behavior locally of a patch. In this case, unfortunately, other Nova customers will sooner or later face this problem. Judging by the number of closed issues, where other people have already reported to you several times about problems with requests when opening the resource index page.

**Comment by crynobone** [comment]
This seems to been fixed alongside other changes to Laravel Nova 5. laravel/nova@4b318ce5

**Comment by ruark** [comment]
So support for Nova 4 is over?

**Comment by ruark** [comment]
> This seems to been fixed alongside other changes to Laravel Nova 5. laravel/nova@4b318ce5

So support for Nova 4 is over?

**Comment by crynobone** [comment]
No plan release for Laravel Nova 4 at the moment.
