### ISSUE TITLE
Call to a member function authorizedToSee() on null (View: \vendor\laravel\nova\resources\views\layout.blade.php)

### ISSUE THREAD

**Issue by beshoo** [laravel/nova-issues#6568]
- Laravel Version: 10.x
- Nova Version: 4.34.3 
- PHP Version: 8.2
- Database Driver & Version:
- Operating System and Version: Windows

### Description:
Once I add this to novaServiceProvider

```
 Nova::mainMenu(function (Request $request) {
            return [
                MenuSection::dashboard(User::class)->icon('chart-bar'),
            ];
        });
```
        
        

```
<?php

namespace App\Providers;

use Illuminate\Support\Facades\Gate;
use Laravel\Nova\Menu\MenuSection;
use Laravel\Nova\Nova;
use Laravel\Nova\NovaApplicationServiceProvider;
use Illuminate\Http\Request;

use App\Nova\User;

class NovaServiceProvider extends NovaApplicationServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        parent::boot();
        //Nova::enableRTL();
        Nova::initialPath('/resources/users');

        Nova::mainMenu(function (Request $request) {
            return [
                MenuSection::dashboard(User::class)->icon('chart-bar'),
            ];
        });

    }

    /**
     * Register the Nova routes.
     *
     * @return void
     */
    protected function routes()
    {
        Nova::routes()
                ->withAuthenticationRoutes()
                ->withPasswordResetRoutes()
                ->register();
    }

    /**
     * Register the Nova gate.
     *
     * This gate determines who can access Nova in non-local environments.
     *
     * @return void
     */
    protected function gate()
    {
        Gate::define('viewNova', function ($user) {
            return in_array($user->email, [
                'beshoo@gmail.com'
            ]);
        });
    }

    /**
     * Get the dashboards that should be listed in the Nova sidebar.
     *
     * @return array
     */
    protected function dashboards()
    {
        return [
            new \App\Nova\Dashboards\Main,
        ];
    }

    /**
     * Get the tools that should be listed in the Nova sidebar.
     *
     * @return array
     */
    public function tools()
    {
        return [];
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }
}

```

![image](https://github.com/user-attachments/assets/9fb4dd7c-d0da-483a-9fdb-d725905c2dca)

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by crynobone** [comment]
@beshoo Your screenshot explicitly shown multiple middleware that doesn't exist in a vanilla Laravel Nova installation. Instead of just a thumb down did you even test it in a basic Laravel Nova installation and see if the problem exists?

**Comment by beshoo** [comment]
Thank you for your reply, I am very sorry I did not mean to give a thumbs down!  but thump up LOL.
And yes on a fresh installation I have the same error but on different file
![image](https://github.com/user-attachments/assets/799aceac-3759-42fd-bab3-32257379de14)

**Comment by beshoo** [comment]
I sent an email to Nova <nova@laravel.com> with the zip file of the complete fresh project for further review, since the Nova script is not open-source.

**Comment by crynobone** [comment]
![CleanShot 2024-10-29 at 11 14 56](https://github.com/user-attachments/assets/84f5076e-226e-474f-9d6e-e00bb2c212a5)

I did not get any issues from the files your provided, just 

```
composer install
php artisan migrate
composer run serve
```

and everything is shown correctly

**Comment by crynobone** [comment]
![CleanShot 2024-10-29 at 11 18 10](https://github.com/user-attachments/assets/a5f70d89-48df-4f37-871e-23fe410814c9)

The class expect class string instance of `Laravel\Nova\Dashboard` and you provides `MenuSection::dashboard(\App\Nova\User::class)->icon('chart-bar')`

**Comment by beshoo** [comment]
I dont follow since am following the documentation 

![image](https://github.com/user-attachments/assets/493fa3b2-2119-45db-849a-b6f7c90d2f50)

Please provide the correct useg!

**Comment by beshoo** [comment]
@crynobone 

![image](https://github.com/user-attachments/assets/274423da-21ab-4c90-af85-87d425294e13)

![image](https://github.com/user-attachments/assets/9be6a47f-d424-4224-977d-f737bbabfb8c)

And following the documentation leads to the previous error.
I am unsure how to pass it as a string since there is no documentation about it.
![image](https://github.com/user-attachments/assets/0365ec60-9d33-4464-b1ee-2d4223da9e2a)
