### ISSUE TITLE
[Bug] displayUsing method has no effect when used on a Lens

### ISSUE THREAD

**Issue by chescos** [laravel/nova-issues#657]
The `displayUsing` method doesn't seem to have any effect when used for any fields in a Lens.

**Comment by abordage** [comment]
+1

**Comment by alexbowers** [comment]
Example reproduction code:

Inside of a lens:

```
public function fields(Request $request)
    {
        return [
            ID::make('ID', 'id')->sortable(),
            Text::make('name')->sortable()->displayUsing(function ($contents) {
                return $contents . " MODIFIED";
            }),
        ];
    }
```

**Comment by pix2D** [comment]
Also `format` (on Currencies), perhaps others too?

**Comment by nasrulhazim** [comment]
> Example reproduction code:
> 
> Inside of a lens:
> 
> ```
> public function fields(Request $request)
>     {
>         return [
>             ID::make('ID', 'id')->sortable(),
>             Text::make('name')->sortable()->displayUsing(function ($contents) {
>                 return $contents . " MODIFIED";
>             }),
>         ];
>     }
> ```

Yeah, i'm having the same issue here as well. 

As for temporary solution:

```php
Text::make('name', function() {
    return $contents . " MODIFIED";
})->sortable()->exceptOnForms(),
```

**Comment by dillingham** [comment]
Related https://github.com/laravel/nova-issues/issues/657 https://github.com/laravel/nova-issues/issues/894 https://github.com/laravel/nova-issues/issues/1149

**Comment by dillingham** [comment]
Related https://github.com/laravel/nova-issues/issues/657 https://github.com/laravel/nova-issues/issues/894 https://github.com/laravel/nova-issues/issues/1149

**Comment by dkulyk** [comment]
PR was sent to upstream.

**Comment by greggh** [comment]
Any word on this one? Using @nasrulhazim's temporary fix right now.

**Comment by dkulyk** [comment]
This has been fixed and will be included in an upcoming release.
