### ISSUE TITLE
Will nova continue to upda

### ISSUE THREAD

**Issue by yangjisen** [laravel/nova-issues#6570]
- Laravel Version: 11
- Nova Version: 4
- PHP Version:8
- Database Driver & Version:
- Operating System and Version: 1
- Browser type and version:1
- Reproduction Repository: https://github.com

### Description:
I am a subscriber of nova. Although it has expired, I have read the update logs in the past year or so and nova has not had many functional updates. May I ask, what are the plans for the future of nova? This is also one of the considerations for deciding whether to continue subscribing for updates.

**Comment by crynobone** [comment]
You can always use the expired license until you feel the need to upgrade, as Nova 5 we currently waiting for some changes to Inertia 2 to make it compatible with Nova.

**Comment by beiaduo** [comment]
I have been a nova subscriber for years. Nova is very uncomfortable to use. For example, some small functions can upload multiple pictures, add 2 columns to one row, and Nova::userMenu adds operations to clear cache and other detailed information, which is very unpleasant.
