### ISSUE TITLE
Dashboard and Resource Loading Very Slow

### ISSUE THREAD

**Issue by heshammostafa123** [laravel/nova-issues#6571]
- Laravel Version: 10.0.0
- Nova Version: 4.33.3
- PHP Version:^8.0

### Description:
When accessing the main URL of a Laravel Nova application, it may check resource.index (or similar resource actions) multiple times
I have attached a sample of the log file when trying to access the main URL anyone can view it 
### Detailed steps to reproduce the issue on a fresh Nova installation:
[laravel.log](https://github.com/user-attachments/files/17586356/laravel.log)

**Comment by AbdallahAli912** [comment]
same issue here, plz help

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by makowskid** [comment]
Whether it's Apple M3/M4 or server with 64GB of RAM and new processor - showing Resource details or edit form takes ages. This should not be a norm:
<img width="771" alt="image" src="https://github.com/user-attachments/assets/7dbd08f0-53c3-4e05-85d3-79afeeff94d2">

**Comment by makowskid** [comment]
And this is my local M3 with 48 GB of RAM, mindblowingly bad performance
<img width="770" alt="image" src="https://github.com/user-attachments/assets/3e2637c6-39ff-4d52-9807-f1480a0cd1e4">

**Comment by jansgescheit** [comment]
I've already stumbled across it myself. You can see it even better if you run tools such as Clockwork or Debugbar and look at the database queries. Nova makes an unbelievable number of database queries, many of which probably have an n+1 problem that you don't even notice and which drag performance down to the basement

**Comment by crynobone** [comment]
@jansgescheit https://github.com/laravel/nova-dusk-suite/blob/8ded9c507c5ff4132f650e0c95f847440ff9c7d8/app/Providers/AppServiceProvider.php#L21-L25 Laravel Nova own test suite (integration and dusk tests) uses `Model::preventLazyLoading()`. If you configure everything correctly you wouldn't have `n+1` issues.

@makowskid I see multiple fetch requests that isn't from a vanilla Laravel Nova installation. Unable to debug further without the reproducing repository as requested above.

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
