### ISSUE TITLE
Cannot show Loading

### ISSUE THREAD

**Issue by keeliang** [laravel/nova-issues#6578]
- Laravel Version: 11.0
- Nova Version: 4.35.3
- PHP Version: 8.3.0
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:
 cannot show loading when filters be changed.

Need to clear value of resourceResponse

Fixed:
 Index.vue ---> Method --> getResources:
        this.resourceResponse  = null

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
