### ISSUE TITLE
Component asset versioning

### ISSUE THREAD

**Issue by JapSeyz** [laravel/nova-issues#658]
When adding .version to a components webpack.mix.js correctly versions it, and generates a manifest, but this is not honored when accessing the resource through the Nova::script or Nova::style methods.

Is there a way to version your component files?

**Comment by davidhemphill** [comment]
`version` isn't supported for Nova components as they're served via Nova's `script` and `style` proxies.

**Comment by JapSeyz** [comment]
How are they cache busted then?

**Comment by sash** [comment]
We are bypassing the problem by changing the name of the asset when registering it to nova:

```php
Nova::serving(function` (ServingNova $event) {
    Nova::script('my-card-name-2020-04-14', __DIR__.'/../dist/js/card.js');
    Nova::style('my-card-name-2020-04-14', __DIR__.'/../dist/css/card.css');
});
```

This works as cache busting as the name is used in the path to load the resource

**Comment by Paulsky** [comment]
Does anyone have a solution for this in Nova 4? Bypassing it with the method provided by Sash works. But it is pretty cumbersome is you have 10+ components and push updates every day.

**Comment by JohnRoux** [comment]
So we're in 2022, using mix, but we can't version our assets :exploding_head:
