### ISSUE TITLE
Repeater field JSON preset could work with attributes nested inside an array but does not

### ISSUE THREAD

**Issue by k8n** [laravel/nova-issues#6582]
The _set()_ method of the Repeater fields' JSON preset works fine if the Repeater is pointed to a nested element of a model's json / array attribute, e.g.  `Repeater::make('Nested Items', 'json_attribute->items')`. The _get()_ method, however, does not.

I create my own preset to override the get() method as follows, and it all appears to work well. Perhaps this could be folded into Nova to give Repeater fields a bit more flexibility? 

```php
class NestedJSON extends JSON
{
    public function get(NovaRequest $request, Model $model, string $attribute, RepeatableCollection $repeatables)
    {
        return RepeatableCollection::make(
            data_get($model, Str::replace('->', '.', $attribute)) // as opposed to $model->{$attribute}
        )
            ->map(function ($block) use ($repeatables) {
                return $repeatables->newRepeatableByKey($block['type'], $block['fields']);
            });
    }
}
```

Thank you for considering this.

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
