### ISSUE TITLE
Unable to load correct Nova Resource with nested resources with same class names

### ISSUE THREAD

**Issue by gcg** [laravel/nova-issues#6584]
- Laravel Version: v11.33.2 
- Nova Version: v4.35.4
- PHP Version: 8.3.13

### Description:

Lets say you have a class with same name as resources in different sub resource namespace/folders (eg: 'App\Nova\Resources\XXX\Log` and `App\Nova\Resources\YYY\Log`) 

Even though I am explicly setting 3rd param on `HasMany` with both class  

```php
      HasMany::make('Logs', 'logs', Log::class),
```

and i tried with string

```php
      HasMany::make('Logs', 'logs', 'App\Nova\XXX\Log'),
```

However, even though the data that log loaded is for the correct eloquent model (since eloquent relationships are not effected the same way nova resources are), the resource is not right so I can only see the matching fields between 2 resources.

**Comment by crynobone** [comment]
Laravel Nova doesn't support using the same attribute for multiple field such as above as `attribute` is consider a unique identifier in this case.

**Comment by gcg** [comment]
> Laravel Nova doesn't support using the same attribute for multiple field such as above as `attribute` is consider a unique identifier in this case.

The field is not multiple, each resource lives their own namespace directory under app/Nova. (XXX model/resource lives in app/models/xxx/XXX and app/models/xxx/log and YYY model lives in its own directory app/models/yyy/yyy and app/models/yyy/log same structure for the nova resources as well. and YYY resource hasmany logs loads the log explicitly, same with XXX.) 

So unless you are not talking about system wide uniqueness, it should work since each class has a unique namespace.

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
