### ISSUE TITLE
Sometimes, for no apparent reason, it throws forbidden

### ISSUE THREAD

**Issue by ondrejehrlich** [laravel/nova-issues#6585]
- Laravel Version: 11.30
- Nova Version: 4.35.4
- PHP Version: 8.3

### Description:

Hi, guys
Thanks for your amazing work building Nova!

Unfortunately, we have been facing a strange problem lately. Occasionally, and without any apparent cause, some users started seeing this: `All Inertia requests must receive a valid Inertia response, however a plain JSON response was received. {"message": "Forbidden"}`
![image](https://github.com/user-attachments/assets/cca19035-7e0d-4c63-af15-430395d6514a)
It always happens randomly for a few minutes and then everything is fine again.
Any idea what it could be or if it could be fixed please?

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by ondrejehrlich** [comment]
Thanks for your attention to this issue. 
I`ve just figured out what was causing the problem. The application is running on AWS Lambda and I use Laravel Vapor for deployment. The firewall in vapor.yml was set to 1000. When this limit was reached, this error appeared.
Thanks again for your great work!
