### ISSUE TITLE
Allow the 'viewNova' gate to be used in local environments.

### ISSUE THREAD

**Issue by orrd** [laravel/nova-issues#659]
The 'viewNova' gate for authorization is currently ignored completely if your environment is 'local'.  This makes it difficult to develop and test your Nova authorization gate, and in general it's not a behavior that all developers want.  So there should be a simple and straightforward way to override that behavior.

I would suggest removing the 'local' environment check from AuthorizesRequests.php, and instead put the 'local' environment check in the sample code provided in NovaServiceProvider.php.  That way developers can leave the 'local' check in place if they want that behavior, or modify the gate to behave differently if they prefer.

**Comment by wfeller** [comment]
I think you can override the authorization() method of NovaApplicationServiceProvider in your own NovaServiceProvider from:

```
protected function authorization()
    {
        $this->gate();

        Nova::auth(function ($request) {
            return app()->environment('local') ||
                   Gate::check('viewNova', [$request->user()]);
        });
    }
```

to this:
```
protected function authorization()
    {
        $this->gate();

        Nova::auth(function ($request) {
            return Gate::check('viewNova', [$request->user()]);
        });
    }
```

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by bolechen** [comment]
+1

**Comment by davidhemphill** [comment]
For those downvoting, would you prefer I just respond with, "We don't accept feature requests. **CLOSED**?" 😄 

We do this because they are not "issues". They are feature requests, of which there is no end. They ask for all sort of things, many of which will never be implemented. If we left them all open, they would just run up the issue count on this board, which (surprise surprise) is something else down-voters are always complaining about. It also makes it difficult to prioritize the *actual* bugs.

**Comment by CitizenBeta** [comment]
@davidhemphill I think the logic of not taking feature requests is sound but in practice it's not so good. There are tons of undocumented features in all Laravel projects and there's no cohesive central place that gets answers from people who are capable of answering. StackOverflow is a black hole for stuff like Nova which is proprietary. The level of usage for Nova I'm sure is great but not close to a community support level of support through 3rd party sites. 

I'm not saying Github is a perfect place but it would be awesome if there was an active central place to track feature requests, even just to see if that feature request is even needed. A bunch of things that get posted are possible without new features, just a better understanding of what's already possible. Nobody knows that something is truely a feature request until someone tells them it isn't possible for sure.

**Comment by rovansteen** [comment]
I agree that it would be nice to have a roadmap where we can see what’s coming up for Nova and which direction it’s going to take in the future.

**Comment by bilfeldt** [comment]
I would be a great security feature to be able to disable the automatic approval of **all** users in local environments.

It could happen that someone accidentally sets the environment to local on a staging server which would then allow access to Nova for all users.

**Comment by desthercz** [comment]
To be honest there are lot of caveats in Nova, so for  production use on any project which is not dead simple i would just fork the Nova, fixed most serious issues and use that version instead of the official one which has very slow development. That is, if that strategy is actually legal.

**Comment by SeanCarrington** [comment]
Override the authorization() method present in the parent class `NovaApplicationServiceProvider.php` and simply remove the local environment check in the return statement. This will enforce a Gate check on regardless of the environment.

```
    /**
     * Configure the Nova authorization services.
     *
     * @return void
     */
    protected function authorization()
    {
        $this->gate();

        Nova::auth(function ($request) {
            return Gate::check('viewNova', [$request->user()]);
        });
    }

```

**Comment by 4n70w4** [comment]
+1! I encountered serious access rights issues after the release. Although in dev everything worked as it should!

**Comment by 4n70w4** [comment]
Also the hardcode with local environment is in the class \Laravel\Nova\AuthorizesRequests:
![image](https://user-images.githubusercontent.com/38257723/64260801-33740000-cf34-11e9-94ec-fbbe773e58b3.png)

This is a very bad design.

**Comment by Alexfilus** [comment]
Now you can override authorization() method from NovaApplicationServiceProvider in app/Providers/NovaServiceProvider.php like that: 
`protected function authorization()
    {
        $this->gate();

        Nova::auth(function (Request $request) {
            return Gate::check('viewNova', [$request->user()]);
        });
    }`
