### ISSUE TITLE
DependsOn  not working on action field

### ISSUE THREAD

**Issue by laravelwebdev** [laravel/nova-issues#6590]
- Nova Version: 4.35.5

DependsOn  not working on action field

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by crynobone** [comment]
Hey there,

We're closing this issue because it's inactive, already solved, old, or not relevant anymore. Feel free to open up a new issue if you're still experiencing this problem.
