### ISSUE TITLE
Symfony 7.2 (stable) from 2024-11-29 leads to errors

### ISSUE THREAD

**Issue by sogo-on-github** [laravel/nova-issues#6596]
- Laravel Version: ^11
- Nova Version: 4.35.5
- PHP Version: ^8.2

### Description:
no changes in mail configuration
update from 2024-11-29 leads to following error:
"message": "The \"\" scheme is not supported; supported schemes for mailer \"smtp\" are: \"smtp\", \"smtps\".",

**downgrade to symfony mailer 7.1 fixes the problem**

### Detailed steps to reproduce the issue on a fresh Nova installation:
same problem in fresh nova installation

**Comment by crynobone** [comment]
A fix has been merged and pending a release (https://github.com/laravel/framework/pull/53585). You should run `composer require "symfony/mailer:~7.1.0"` until the release.
