### ISSUE TITLE
Text asHtml function disabled the table row link

### ISSUE THREAD

**Issue by jsmit99** [laravel/nova-issues#6603]
- Laravel Version: 11.35.0
- Nova Version: v4.35.5
- PHP Version: 8.3
- Database Driver & Version: mysql

### Description:
When you use the asHtml function the row click function does not work anymore.

### Detailed steps to reproduce the issue on a fresh Nova installation:
Add a Text field on a resource.
```
Text::make('Test')
    ->displayUsing(function () {
        return '<span class="flex">test</span>';
    })
    ->asHtml(),
```
When clicking the table row inside the 'Test' column, it does not trigger the row click functionality (like going to the detail page).

**Comment by crynobone** [comment]
This is expected since `asHtml()` is common to contain link or button.

**Comment by jsmit99** [comment]
Though it would be nice as there would be a way to still keep this functionality. For example if I just "color" the text in a column I have to use asHtml though I still would like the row click to behave like that.
