### ISSUE TITLE
Support for inertiajs/inertia-laravel v^2.0

### ISSUE THREAD

**Issue by romainvause** [laravel/nova-issues#6604]
- Laravel Version: 10.48.23
- Nova Version: 4.35.5
- PHP Version: 8.2

### Description:
InertiaJS just [released a stable v2](https://inertiajs.com/upgrade-guide) but will Laravel Nova ^4 will support it without paying a licence renew ?
```
laravel/nova 4.35.5 requires inertiajs/inertia-laravel ^0.4.5|^0.5.2|^0.6.0|^1.0 -> found inertiajs/inertia-laravel[v0.4.5, ..., v0.6.11, v1.0.0, ..., v1.3.2] but it conflicts with your root compose
```

**Comment by crynobone** [comment]
Support is available via Nova 5 using existing active license: https://nova.laravel.com/docs/v5/upgrade
