### ISSUE TITLE
How to pass vuerouter to toasted plugin

### ISSUE THREAD

**Issue by rodwin** [laravel/nova-issues#661]
Using nova v1.1.3

I would like to navigate to a url when a notification is clicked

this.$toasted.show('It worked!', 
                { 
                    type: 'success',
                    action : {
                        text : 'Cancel',
                        push : { 
                            name : 'admin/resources/clients',
                        }
                    },
                })

error: [vue-toasted] : Vue Router instance is not attached. please check the docs

**Comment by davidhemphill** [comment]
Currently, Nova's Vue Router instance isn't passed to Toasted...This has been added and will be included in an upcoming release.
