### ISSUE TITLE
Nova 5 Tab missing Actions Menu and Edit button. 

### ISSUE THREAD

**Issue by gldrenthe89** [laravel/nova-issues#6613]
- Laravel Version: 11.35.1
- Nova Version: 5.0.1
- PHP Version: 8.3
- Database Driver & Version: Mysql 8
- Operating System and Version: macOS 15.2
- Browser type and version: Firefox laters
- Reproduction Repository: unavailabe, private

### Description:

The new Tabs in Nova 5 are cousing the Actions menu en Edit button on the view page to disappear. 

![image](https://github.com/user-attachments/assets/682b11cc-5ffb-4018-9e06-a9387ba84581)

**Comment by gldrenthe89** [comment]
@taylorotwell I have updated to v5.0.2 but the issue is stil there. No actions or edit button for me. You want me to create a new bug report?

I also think i found the issue, is use my tabs like this:

![image](https://github.com/user-attachments/assets/08ca10fc-f127-4003-af4b-1581eaf499dc)
`Tab::group(__(':resource Details: :title', ['resource' => self::singularLabel(), 'title' => $this->title()]), [
                Tab::make('Details', [
                    ID::make()->sortable(),

                    Text::make('Name'),

                ]),
                BasePanel::panel(),
                AuditableLog::make(),
            ])->withToolbar(),`

But this isnt working. When i change as shown below, it works. Looks like the translations breaks the header. 

![image](https://github.com/user-attachments/assets/87c7654a-89ee-41ee-8a0f-0818017cde4a)
`Tab::group('Details', [
                Tab::make('Details', [
                    ID::make()->sortable(),

                    Text::make('Name'),

                ]),
                BasePanel::panel(),
                AuditableLog::make(),
            ])->withToolbar(),`

PS, have fun with the worldwide meetup @taylorotwell i cant join live but will watch it later.

**Comment by crynobone** [comment]
Just write it as:

```php
Tab::group(fields: [
    Tab::make('Details', [
        ID::make()->sortable(),

        Text::make('Name'),

    ]),
    BasePanel::panel(),
    AuditableLog::make(),
]),
```

Nova will add an empty Panel above it to handle to "Toolbar"

**Comment by gldrenthe89** [comment]
> Just write it as:
> 
> ```
> Tab::group(fields: [
>     Tab::make('Details', [
>         ID::make()->sortable(),
> 
>         Text::make('Name'),
> 
>     ]),
>     BasePanel::panel(),
>     AuditableLog::make(),
> ]),
> ```
> 
> Nova will add an empty Panel above it to handle to "Toolbar"

That is what i did to get it to work. But it is nog a solution to the issue i reported ;-)

**Comment by crynobone** [comment]
We not looking to work on any other solution right now
