### ISSUE TITLE
Blank page after refresh

### ISSUE THREAD

**Issue by mateusz-peczkowski** [laravel/nova-issues#6616]
- Laravel Version: 11.36.1
- Nova Version: 5.0.2
- PHP Version: 8.3.7

### Description:
A fresh installation of Laravel 11 and Laravel Nova 5 was performed. Upon visiting the Nova URL, a login page is displayed. Successful login allows access to any page without encountering any issues. However, refreshing a page results in a blank page with an error message, as depicted in the screenshot.
<img width="1800" alt="image" src="https://github.com/user-attachments/assets/d1b93777-8f34-47da-9bdc-a79df584e146" />

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. Install Laravel 11
2. Install Nova 5 via composer (Everything as on the Installation guide upon Nova user create)
4. (optional) Change `config.nova.path` to `/` and remove the body of `routes/web.php`
5. Setup domain in ENV
6. Go to your domain
7. Login to user created in point 2
8. Go to for example users
9. Refresh page

Using `php artisan serve` everything is working, so it can be tested only on Apache projects. Laravel Nova 4 is working normally.

**Comment by mateusz-peczkowski** [comment]
I've added a console log in compiled code
<img width="542" alt="image" src="https://github.com/user-attachments/assets/6877448d-7018-454a-9355-41a86746b5f8" />

And it is shown as "undefined". So something is not loading properly

**Comment by crynobone** [comment]
Unable to replicate the issue with `http` and `https`:

![CleanShot 2024-12-18 at 11 12 24](https://github.com/user-attachments/assets/271e5597-fe44-47f9-b568-34b1c1b6247d)

**Comment by crynobone** [comment]
Unable to reproduce the issue, please provide full reproducing repository based on fresh installation as suggested in the bug report template (or you can refer to https://github.com/nova-issues for example)

**Comment by crynobone** [comment]
Also, `lockdown-install.js` isn't part of Laravel Nova. Could that be the cause of your problem?

**Comment by crynobone** [comment]
![CleanShot 2024-12-18 at 13 50 32](https://github.com/user-attachments/assets/67a90a83-1be4-438e-a499-efb72a2c7522)

I found the issue, on certain browsers the sequence of loading (by Inertia 2) is slightly different as illustrated on screenshot above (left using Firefox and right using Chrome).

**Comment by anditsung** [comment]
i have tested it on safari, chrome, firefox and brave

only firefox is working
