### ISSUE TITLE
Custom color not working on Partition metrics

### ISSUE THREAD

**Issue by laravelwebdev** [laravel/nova-issues#6617]
- Laravel Version: 11
- Nova Version: 5.0.2
- PHP Version: 8,2

### Description:
Custom color not working on Partition metrics

![Screenshot 2024-12-18 at 18 01 29](https://github.com/user-attachments/assets/49a238d9-aa1e-4597-86c9-535b5e13792a)
As you can see, the label show customized color, but the pie chart always show default color

**Comment by christian-heiko** [comment]
i also noticed wrong colors even without customizing them.
