### ISSUE TITLE
[UI] Default panel and tab group/relation panel missing gap

### ISSUE THREAD

**Issue by Tarpsvo** [laravel/nova-issues#6621]
- Nova Version: 5.0.3
- PHP Version: 8.4

### Description:
The default panel and Tab::group() seems to not have a gap in-between. The same applys to default panel and HasMany relation panel.

![image](https://github.com/user-attachments/assets/76172d59-5096-43d3-9be9-af4483ab8963)

### Detailed steps to reproduce the issue on a fresh Nova installation:

```php
public function fields() {
  return [
    // ...snip
    Text::make('Contact name'),
    Text::make('Contact email'),
    Text::make('Contact phone'),

    Tab::group('Details', [
        HasMany::make('Invoices', 'invoices', ContractInvoice::class),
        HasMany::make('Contracts', 'contracts', Contract::class),
        HasMany::make('Metering points', 'meteringPoints', MeteringPoint::class),
    ]),
  ];
}
```

**Comment by saschaende** [comment]
I can confirm, I have the same problem.
