### ISSUE TITLE
login and logout routes issue after upgrading to v5

### ISSUE THREAD

**Issue by animena** [laravel/nova-issues#6625]
- Laravel Version: 11.5.0
- Nova Version: 5.0.3
- PHP Version: 8.3.2-1

### Description:
After I update nova from 4 to 5, and added this parent::register(); to App\Providers\NovaServiceProvider I start getting the error Route [logout] not defined.

Nova is working fine but the main website is not working, if I remove this "parent::register();" it starts working again, 

Here is php artisan route:list 
with parent::register();

 GET|HEAD  nova/login ........................................................................................................................................................................................ nova.pages.login › Laravel\Fortify › AuthenticatedSessionController@create
  POST      nova/login ............................................................................................................................................................................................... nova.login › Laravel\Fortify › AuthenticatedSessionController@store
  POST      nova/logout ........................................................................................................................................................................................... nova.logout › Laravel\Fortify › AuthenticatedSessionController@destroy

without parent::register();

 GET|HEAD  login ........................................................................................................................................................................................................ login › Laravel\Fortify › AuthenticatedSessionController@create
  POST      login ................................................................................................................................................................................................... login.store › Laravel\Fortify › AuthenticatedSessionController@store
  POST      logout ..................................................................................................................................................................................................... logout › Laravel\Fortify › AuthenticatedSessionController@destroy
GET|HEAD  nova/login ........................................................................................................................................................................................ nova.pages.login › Laravel\Fortify › AuthenticatedSessionController@create
  POST      nova/login ............................................................................................................................................................................................... nova.login › Laravel\Fortify › AuthenticatedSessionController@store
  POST      nova/logout ........................................................................................................................................................................................... nova.logout › Laravel\Fortify › AuthenticatedSessionController@destroy

**Comment by crynobone** [comment]
Can you share the content of `bootstrap/providers.php`?

**Comment by balu-lt** [comment]
I had the same issue with my Laravel 10 project.
Managed to fix it by reordering service providers in `config/app.php`
the`FortifyServiceProvider` should be above the `NovaServiceProvider`:
```php
'providers' => ServiceProvider::defaultProviders()->merge([
    // ....
    App\Providers\FortifyServiceProvider::class,
    App\Providers\NovaServiceProvider::class,
    App\Providers\RouteServiceProvider::class,
])->toArray(),
 ```

**Comment by animena** [comment]
> I had the same issue with my Laravel 10 project. Managed to fix it by reordering service providers in `config/app.php` the`FortifyServiceProvider` should be above the `NovaServiceProvider`:
> 
> ```
> 'providers' => ServiceProvider::defaultProviders()->merge([
>     // ....
>     App\Providers\FortifyServiceProvider::class,
>     App\Providers\NovaServiceProvider::class,
>     App\Providers\RouteServiceProvider::class,
> ])->toArray(),
> ```

this works, thanks @balu-lt
