### ISSUE TITLE
File Download from Storage

### ISSUE THREAD

**Issue by kishoresai438** [laravel/nova-issues#663]
Hi team,

I am using S3 as storage for file uploads. I am able to upload files to s3 by using File Field. But I can not able to show this on download list with download link. Please guide me how to show download list in listing.

```
File::make('File Path')
            ->disk('s3')
                ->path('/allfiles/'.Auth::id())
                ->storeAs(function (Request $request) {
                    return $request->file_path->getClientOriginalName();
                }),
```

**Comment by davidhemphill** [comment]
File fields are set to not show on index using `public $showOnIndex = false;`. If you want to show them, the only way to do that right now is to either create a custom field and override `Laravel/Nova/Fields/File.php` to change that property, or show the download link in a computed Text field: https://nova.laravel.com/docs/1.0/resources/fields.html#computed-fields
