### ISSUE TITLE
Two duplicate routers [ verification.verify ]

### ISSUE THREAD

**Issue by beiaduo** [laravel/nova-issues#6634]
- Laravel Version: last
- Nova Version:  last
- PHP Version: 8.3.3
- Database Driver & Version:
- Operating System and Version: #.#
- Browser type and version: #.#
- Reproduction Repository: https://github.com/###/###

### Description:

   LogicException 

  Unable to prepare route [nova-admin/email/verify/{id}/{hash}] for serialization. Another route has already been assigned name [verification.verify].

  at vendor/laravel/framework/src/Illuminate/Routing/AbstractRouteCollection.php:248
    244▕             $route->name($this->generateRouteName());
    245▕ 
    246▕             $this->add($route);
    247▕         } elseif (! is_null($symfonyRoutes->get($name))) {
  ➜ 248▕             throw new LogicException("Unable to prepare route [{$route->uri}] for serialization. Another route has already been assigned name [{$name}].");
    249▕         }
    250▕ 
    251▕         $symfonyRoutes->add($route->getName(), $route->toSymfonyRoute());
    252▕ 

      +19 vendor frames 

  20  artisan:13
      Illuminate\Foundation\Application::handleCommand()

  GET|HEAD  email/verify/{id}/{hash} ................................................................ verification.verify › Laravel\Fortify › VerifyEmailController@__invoke
  GET|HEAD  nova-admin/email/verify/{id}/{hash} .............................................................. verification.verify › Laravel\Fortify › VerifyEmailController

**Comment by crynobone** [comment]
In your `NovaServiceProvider` please add the following:

```diff
    /**
     * Register the Nova routes.
     */
    protected function routes(): void
    {
        Nova::routes()
            ->withAuthenticationRoutes()
            ->withPasswordResetRoutes()
+           ->withoutEmailVerificationRoutes()
            ->register();
    }
```
