### ISSUE TITLE
MorphMany in Tab group not working on Safari

### ISSUE THREAD

**Issue by ryangurn** [laravel/nova-issues#6636]
- Laravel Version: 11.36.1
- Nova Version: 5.0.5
- PHP Version: 8.4.1
- Database Driver & Version:
- Operating System and Version: macOS 15.2
- Browser type and version: Safari 18.2 (20620.1.16.11.8)
- Reproduction Repository: https://github.com/ryangurn/nova-reproduce-repo

### Description:
When using a `Tab::group()` with a MorphMany nova relationship within the group as mentioned in the documentation, the panel does not show up in Safari. Things work as expected within Chrome 131.0.6778.205.

```php
Tab::group("Related", [
    HasMany::make("Estimates", "estimates", Estimate::class),

    HasMany::make("Invoices", "invoices", Invoice::class),

    MorphMany::make("Notes", "notes", Note::class),
]),
```
The above code example is not from my testing repo however I was able to replicate the same issue in the separate repo linked and using the `App\Models\User` model/resource and the `App\Models\Note` model/resource.

### Safari Screenshot
<img width="1527" alt="image" src="https://github.com/user-attachments/assets/86404168-82de-4f0a-be7e-0f9e5f35b688" />

### Chrome Screenshot
<img width="1244" alt="image" src="https://github.com/user-attachments/assets/6b7600ab-35e2-49cb-a9da-2c8a53a7ece1" />

### Detailed steps to reproduce the issue on a fresh Nova installation:
1. clone repo
2. add some dummy data (nothing specific)
3. attempt to view Tab group with MorphMany and it should match my attached screenshots.

**Comment by ryangurn** [comment]
I also just realized that my example has a MorphOne() in the User model but the User resource had MorphMany(). I corrected this outside of the reproduction repo and I am still experiencing the same issue after adjusting the relationship defined in the User model.

**Comment by ryangurn** [comment]
PS thanks for adding tabs, I am very very excited to utilize them and quite excited to see the detail page design progression out of the box continue to improve!

**Comment by crynobone** [comment]
![CleanShot 2024-12-27 at 10 11 55](https://github.com/user-attachments/assets/c070a0d3-422b-46d4-b59c-af6c6cbbf08e)

Tested fine on Safari, the relationship does seems invalid to me, using `MorphOne` relationship but use `MorphMany` field.

**Comment by ryangurn** [comment]
@crynobone, the screenshot above is for a MorphOne, please attempt using MorphMany.

**Comment by crynobone** [comment]
Please check your reproducing repository

**Comment by mziraki** [comment]
@ryangurn @crynobone if relationship field's collapsed status has been saved in browser's local storage and then you put them in new "tabs" panel introduced in Nova 5.0+, they will be hidden. you can clear browser storage cache for the site to fix it. 
I don't know if it counts as a bug but a fix would be nice.

**Comment by crynobone** [comment]
> if relationship field's collapsed status has been saved in browser's local storage and then you put them in new "tabs" panel introduced in Nova 5.0+, they will be hidden.

If that the case here, both Safari and Chrome would have the same behavior.

**Comment by mziraki** [comment]
> > if relationship field's collapsed status has been saved in browser's local storage and then you put them in new "tabs" panel introduced in Nova 5.0+, they will be hidden.
> 
> If that the case here, both Safari and Chrome would have the same behavior.

he can make sure if this is the bug or not with clearing the browser's local storage for the site

**Comment by ryangurn** [comment]
Using private browsing and ensuring the everything is consistently using MorphMany appears to have resolved the issue. I thought this might be a bug but alas turns out it was just some strange caching on my end.
