### ISSUE TITLE
Nova Deploy Shared Hosting

### ISSUE THREAD

**Issue by CanerErgez** [laravel/nova-issues#664]
I tried to set up my shared hosting service. But in some parts I get an error.

Error 1: I am using simple bit htaccess. But when I want to go to the '/ nova' directory, it goes to the endless loop. (http://smartsoccer.xyz/nova)

htaccess source:

```
<IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteCond %{REQUEST_URI} !^public
    RewriteRule ^(.*)$ public/$1 [L]
</IfModule>
```

Error 2: When I want to show an image (for example: http://smartsoccer.xyz/storage/thumbnails/Xx1dzLBeSz4loYAQHdrCyljdrYjr5Kl8dJ4Q5SiY.png)

I get 404 not found error. I did the linking, but the source still cannot be found.

**Comment by alexbowers** [comment]
Is the main laravel app visible? (eg, going to `smartsoccer.xyz` does it show the welcome page?

**Comment by CanerErgez** [comment]
I can access the main page, articles. But photos aren't showing and I get an endless looping error when I want to go to the '/ nova' directory.

**Comment by CanerErgez** [comment]
will re-install the system at the weekend. Links will be in the open position.

**Comment by CanerErgez** [comment]
Re-install the system . i've change .htaccess file

`<IfModule mod_rewrite.c>
   RewriteEngine On 
   RewriteRule ^(.*)$ public/$1 [L]
</IfModule>`

same problems continue ...

**Comment by alexbowers** [comment]
Is there a reason you have to use Shared Hosting?

Does the laravel application work, and just nova doesn't?

**Comment by CanerErgez** [comment]
Laravel application work well . laravel creates the homepage. But it can't bring the pictures.

**Comment by alexbowers** [comment]
Can you confirm you are on the latest version of Laravel Nova, and that you have ran `nova:install` etc.

**Comment by CanerErgez** [comment]
Yes , 2 days ago i will create new laravel and nova . With SSH connection . All commands run .

**Comment by CanerErgez** [comment]
Hello , I solved all problems . 

Nova install shared hosting steps;
1 - create new folder in hosting root folder (Ex: public_html) 
2 - all files (without public) copy and move created file in hosting .
3 - public directory move to 'public_html/website.com'
4 - update index.php load settings (Ex: '../boostrap' to '../../directory/bootstrap')
5 - Now Nova is work well .
6 - change filesystems public register path .
7 - Now all pictures are accessible .

Samples ;
index.php changed rows ;
```
/***/
require __DIR__.'/../../directory/vendor/autoload.php';
/***/
$app = require_once __DIR__.'/../../directory/bootstrap/app.php';
/***/
```

config/filesystems.php
```
'public' => [
            'driver' => 'local',
            'root' => 'storage',
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],
```
