### ISSUE TITLE
How to set hidden text fields

### ISSUE THREAD

**Issue by kishoresai438** [laravel/nova-issues#666]
Hi Team,

I am trying to set some hidden fields in the form. Please suggest how can we implement this as hidden.
```
Text::make('amount')->withMeta(["value" => 100])->onlyOnForms()
```

Thanks,
Sai Kishore

**Comment by alexbowers** [comment]
When you say hidden, do you mean an actual `hidden` or do you mean that you don't want it on the index page, and only to be on the detail page?

If its the latter, then `onlyOnDetail()` is the function that does that.

**Comment by dillingham** [comment]
@kishoresai438 if you want a hidden field just add the type to the meta

```php
Text::make('Title')->withMeta(['type' => 'hidden']),
```

**Comment by davidhemphill** [comment]
@dillingham's answer is the correct one. If this doesn't solve your issue, feel free to comment, but closing for now.

Also closing as this issue number is cursed!

**Comment by kishoresai438** [comment]
Hi @alexbowers ,

I need the hidden field in Form. I am able to manage this in Index, details page by using  `Showing / Hiding Fields`. I want to pass the hidden params to my submission.

Thanks

**Comment by alexbowers** [comment]
@kishoresai438 Can you create a new issue for that, since, while related, is separate.

**Comment by dillingham** [comment]
`label[for="Amount"] {display: none;}`

Problem is @kishoresai438 , you'll still have the input row
You should reconsider hiding it maybe and question whether you need a hidden field. 
I set properties on the model via model observers. Maybe that's what you're trying to do.

```php
class Order extends Model
{
    public static function boot()
    {
        parent::boot();

        static::saving(function ($order) {
            $order->amount = $order->item->price;
        });
    }
```

**Comment by davidhemphill** [comment]
Are we basically wanting a HiddenField that has a value that's resolved when the Resource is resolved?

**Comment by noahlocke** [comment]
@davidhemphill yes, this would allow us to pass hidden values on specific resources. The only issue with @dillingham 's solution is that, in my case at least, I've had to create multiple resources from the same model. I have All Clients, and My Clients. If I'm creating a new "my client", then I'd opt to pass my own user_id along with the new resource (hidden field), where an Admin creating a new "client" would choose the user_id from a list of users.

**Comment by MohmmedAshraf** [comment]
You can use this package: [Nova Hidden Fields](https://github.com/MohmmedAshraf/nova-hidden-field) also you can set default value for your hidden fields.

**Comment by bernhardh** [comment]
If others land here over search engines - there is already a build in field for this nowaday: https://nova.laravel.com/docs/3.0/resources/fields.html#hidden-field
