### ISSUE TITLE
custom-index-toolbar

### ISSUE THREAD

**Issue by mohrajab** [laravel/nova-issues#667]
What this component does?
I notice on release note of verison v1.1.0 that 
"- Add place-holder Vue components for index and detail headers and toolbars that may be customized for your own Nova installation.".
and this is not included yet on documentation.
Any one know what is this, and how we can use it ?

**Comment by alexbowers** [comment]
I believe that Taylor mentioned that this will be made clearer in a future release of Nova, its just the groundwork for some better customisation features.

**Comment by mohrajab** [comment]
thanks @alexbowers , I supposed that when I open the vue templates and see it empty for now, but I want to make sure.

Thanks again

**Comment by alexbowers** [comment]
No problem, feel free to close this issue to keep the repo clean :)

**Comment by davidhemphill** [comment]
In the meantime, basically all you need to do is copy the contents of those components to your own (in a tool probably) and register it with `Vue.component()`,

**Comment by parth-ka-patel** [comment]
i used this custom-index-toolbar in laravel nova 4 and laravel 8.75 but button not visible so can any one please give alternative solution ?
