### ISSUE TITLE
Null JSON code field

### ISSUE THREAD

**Issue by alexbowers** [laravel/nova-issues#669]
Type: Bug Report

### Versions
* PHP Version: 7.2.2
* Laravel Version: 5.7.5
* Laravel Nova version: 1.1.3

---

Have you tested this against the latest version of PHP:

* [ ] Yes
* [X] No

Have you tested this against the latest version of Laravel

* [X] Yes
* [ ] No

Have you tested this against the latest version of Laravel Nova

* [X] Yes
* [ ] No

---

### Bug Type

* [ ] Design / Layout issue 
* [ ] Regression 
* [ ] Missing functionality 
* [X] Other 

### Description of issue

Having a JSON code field in a resource with a default `nullable` value has the value `null` in the Code area, where it should be empty.

### Example code / reproduction steps

Add

```php
Code::make('info')->json()
```

to the fields, and have a migration with the following field:

```php
$table->json('info')->nullable();
```

**Comment by alexbowers** [comment]
Not sure if this is a bug. It does still save as "null", so there is no inconsistency with data

**Comment by sammax** [comment]
I think it should be empty with placeholder text "null".

**Comment by alexbowers** [comment]
Having thought on it, i don't think this is a bug
