### ISSUE TITLE
Firefox loading circles are extremely large

### ISSUE THREAD

**Issue by jasonmccallister** [laravel/nova-issues#67]
Running the latest version of Firefox and when loading resources in Nova, the loading circles are extremely large:
<img width="1084" alt="screen shot 2018-08-23 at 3 05 43 pm" src="https://user-images.githubusercontent.com/5354908/44546538-3ebc0b00-a6e6-11e8-9a3a-d347c05c4b59.png">

Version: 1.0.5

**Comment by themsaid** [comment]
Anyone else seeing this?

**Comment by solidprinciples** [comment]
I have seen this as well.

**Comment by michaeldyrynda** [comment]
Me too

**Comment by ikkebra** [comment]
Same here

**Comment by GuidoHendriks** [comment]
Here too. 61.0.2 (64-bit) on macOS.

**Comment by squierll** [comment]
Me too

**Comment by davidhemphill** [comment]
This has been fixed in the upcoming release.
