### ISSUE TITLE
Negative partition metric value

### ISSUE THREAD

**Issue by alexbowers** [laravel/nova-issues#670]
Having a negative value in the partition messes up with the values.

Perhaps negative values shouldn't be allowed?

```php
public function calculate(Request $request)
    {
        return $this->result([
            'one' => -100,
            'two' => 0,
            'three' => 0,
        ]);
    }
```

![image](https://user-images.githubusercontent.com/842974/45982665-84efeb80-c051-11e8-8ad6-b50045a7c992.png)

**Comment by bonzai** [comment]
This was fixed in version 1.1.9 (a chart with invalid values will be hidden from the view).

https://nova.laravel.com/releases
