### ISSUE TITLE
Group name is case-sensitive

### ISSUE THREAD

**Issue by alexbowers** [laravel/nova-issues#671]
The group name of resources shows as title-case, however it is case sensitive.

Having a resource with:

```
public static $group = 'Group name';
```

and another with:

```
public static $group = 'Group Name';
```

it shows as separate groups

![image](https://user-images.githubusercontent.com/842974/45982745-d9936680-c051-11e8-9fa0-6cb61b79dc29.png)

**Comment by davidhemphill** [comment]
A little late to this one, but case-sensitivity is required for this feature.
