### ISSUE TITLE
Method for setting field detail page link / index link

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#672]
**Package** https://github.com/dillingham/nova-id-link

Having a method to instruct the vue component to render a detail link would be pretty rad.
```php
ID::make()->linked()
```

![orders](https://user-images.githubusercontent.com/29180903/45983855-7cd18500-c02c-11e8-81a8-84fb01691a71.png)

**Comment by alexbowers** [comment]
Seems like a decent idea to me, at least for the ID at a minimum.

**Comment by loren138** [comment]
Temporary fix for linking index pages to detail using the new `asHtml` feature, but it does a full page reload rather than a nice HTML5 transition.  I've tried to use a vue `router-link` but that doesn't seem to get compiled.

## Current code

### Title field
```
            Text::make('Thickness Name', 'Name')->sortable()->rules('required')->displayUsing(function ($value) {
                return view('link', [
                    'id' => $this->ID,
                    'value' => $value,
                    'slug' => $this->uriKey()
                ])->render();
            })->asHtml(),
```

### Link Blade Template
```
<a href="/admin/resources/{{$slug}}/{{$id}}" class="no-underline dim text-primary font-bold">{{$value}}</a>
```

**Comment by dillingham** [comment]
### Possible feature approach

ResourceTableRow.vue line 22 needs the following

```html
:resource-id="resourceId: resource['id'].value"
```

A new component for `index-router-link`

```html
<template>
    <router-link :to="to" v-text="field.value" class="text-justify no-underline dim"></router-link>
</template>

<script>
    export default {
        props: ['resourceId', 'resourceName', 'field'],
        computed: {
            to() {
                return {
                    name: 'detail',
                    params: {
                        resourceName: this.resourceName,
                        resourceId: this.resourceId
                    }
                }
            }
        }
    }
</script>
```

and a helper method on Text

```php
class Text extends Field
{
    public function linkable()
    {
        return $this->useComponent('index-router-link');
    }
}
```

**Comment by hackel** [comment]
Here's a simple implementation of @loren138's solution:
```php
Field::macro('linkToDetail', function ($model) {
    return $this->displayUsing(function ($value) use ($model) {
        return vsprintf('<a href="%s/resources/%s/%d" class="no-underline dim text-primary font-bold">%s</a>',
            [
                config('nova.path'),
                $model->uriKey(),
                $model->getRouteKey(),
                $value,
            ]);
    })->asHtml();
});
```

Then just add `->linkToDetail($this)` to your field definitions.  If anyone can come up with a clever way to avoid having to pass $this to the method, that would be even better.  Look forward to seeing a better solution with native routing.

**Comment by XGhozt** [comment]
+1 on this, would like to be able to link any field to the detail page from the resource index.

**Comment by dillingham** [comment]
I made a package that adds `->linked()` to ID field and uses vue router.

https://github.com/dillingham/nova-id-link

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by bgeree** [comment]
If anyone else tries to achieve this thing:
You can define a belongsTo relation to associate the model with itself.
`public function yourModel()
{
    return $this->belongsTo(YourModel::class, 'id', 'id')->withTrashed();
}`
After that you can put an extra belongsTo field to the index only which automatically renders as a link.
I suppose this comes with a performance penalty, but I haven't found better solution (without creating custom field).
