### ISSUE TITLE
Image not found on local filesystem

### ISSUE THREAD

**Issue by sergionader** [laravel/nova-issues#674]
Hello, 

v1.1.3

I started using Nova today and could do a lot in a little time. Very good -- congrats!!!!

What didn't work: 

I have this file system that I successfully use in my Laravel app. 
``` 
    'my_disk' => [
            'driver'    => 'local',
            'root'      => storage_path('app/clients'),
        ],
``` 
The file name is stored in the 'file' field. 

However,  neither of the following lines will give the expected result: 
`FILE::make('File')->sortable()->disk('proofing_tracking'),`
will show the file name and the download icon/text but nothing will be downloaded -- no error thrown. 

`IMAGE::make('Image', 'file')->disk('proofing_tracking'),`
will show the text This image could not be found. 

Avatar field type also didn't work. 

What am I missing?

Thank you,

Sergio Nader

**Comment by 907544030** [comment]
have you ever run 'php artisan storage:link'

**Comment by sergionader** [comment]
Thank you! I just tried it and got an error: symlink(): No such file or directory
I will try to figure out how to handle it (but it won't hurt if anyone has any hint :-)).

**Comment by uwascan** [comment]
Your file system configuration shows a declaration for `'my_disk'` but your field declaration is using `'proofing_tracking'` may be you should try
`IMAGE::make('Image', 'file')->disk('my_disk'),` in addition to running
`php artisan storage:link`

**Comment by sergionader** [comment]
I had tried it before. 
Here are my filesytem entries: 
``` 
'disks' => [
   'public' => [
            'driver'    => 'local',
            'root'      => storage_path('app/public'),
            'url'       => env('APP_URL').'/storage',
            'visibility'=> 'public',
        ],
   'proofing_tracking' => [
            'driver'    => 'local',
            'root'      => storage_path('app/clients/pars'),
        ],
]

**Comment by sergionader** [comment]
Update: I `rm public/storage` and was able to `php artisan storage:link`

However, still can't see the images, either using 'public' or 'proofing_tracking'  as the disk. 

Any help will be welcome! THanks!

**Comment by sergionader** [comment]
Update 2: just found out that if I save the file using: 
` file::make('File')` 
the image will show 

The same will not occur if I save the file using 
`file::make('File')->disk('proofing_tracking')``
as won't be saved and thus the image won't show.

It looks like I am missing somthing....

**Comment by sergionader** [comment]
It works if I use `file::make('File')` what saves the image on public/storage. 
if I try ->disk('proofing_tracking') it won't save the file. 

Any insight is welcome!!!

Thanks!

**Comment by ChrisFrench** [comment]
> have you ever run 'php artisan storage:link'

This helped me as well i was missing this

**Comment by Milkhan** [comment]
If you've run 'php artisan storage:link' and still can't see the images, try to change this variable in the **.env** file:
**APP_URL=localhost**
to actual address like this 
**APP_URL=http://127.0.0.1:8000**
(in my case the address was: http://127.0.0.1:8000)
And don't forget to run **'php artisan cache:clear'** afterwards.
