### ISSUE TITLE
Authorization & Action

### ISSUE THREAD

**Issue by Kristories** [laravel/nova-issues#676]
I'm create a resource, and need to hide all actions (except `viewAll`) to access its index, also hide edit and delete icons to avoid doing this action.

This is my policy : 

```
viewAny  		true
view 			false
create 			false
update 			false
delete 			false
restore			false
forceDelete		false
```

Then, I registering an action and run it, always displaying a message :

> Sorry! You are not authorized to perform this action.

But when `update` and `delete` policy I change to `true`, it will work. 

How can "action" work  without edit and delete?

**Comment by patrickmounir** [comment]
I have the same issue.

**Comment by nickels** [comment]
but if you don't have `view` you won't see anything. So return `view` as `true` and then use (from the docs):

=====
Index Filtering
You may notice that returning false from a policy's view method does not stop a given resource from appearing in the resource index. To filter models from the resource index query, you may override the indexQuery method on your resource. This method is already stubbed in your App\Nova\Resource base class, you may simply copy and paste it into a specific resource and then modify the query:

/**
 * Build an "index" query for the given resource.
 *
 * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
 * @param  \Illuminate\Database\Eloquent\Builder  $query
 * @return \Illuminate\Database\Eloquent\Builder
 */
public static function indexQuery(NovaRequest $request, $query)
{
    return $query->where('user_id', $request->user()->id);
}

**Comment by Kristories** [comment]
@nickels `view` work with resource detail, I don't need to show it. 

`indexQuery` is out of topic.

**Comment by wfeller** [comment]
You can use canRun() on your action:

```
    public function actions(Request $request)
    {
        return [
            (new MyAction)->canRun(function ($request, $model) {
                return true; //or some logic
            }),
        ];
    }
```

**Comment by Kristories** [comment]
@wfeller it doesn't solve the prolem.

**Comment by hotmeteor** [comment]
Agreed. I think you should be able to run an action, using custom policies, without needing to define `create` or `update`. This is a bit of a show-stopper.

**Comment by julianpoma** [comment]
I need the same feature. I want to avoid my users updating the resource manually, but let them update it via actions.

**Comment by julianpoma** [comment]
@hotmeteor See #558 

```
(new Action\Action)->canRun(function() {
   return true;
}),
```

**Comment by bjrnblm** [comment]
@julianpoma does not work. You have to set `update` and `delete` in the main policy to true even if you set `canRun` to true for the action.

**Comment by warksit** [comment]
@julianpoma's solution is working for an Action but if I change to a DestructiveAction it reverts to 
>Sorry! You are not authorized to perform this action.

The DestructiveAction class is blank other than extending Action so not sure why this behaves differently

**Comment by calvinps** [comment]
@julianpoma I found that the `ActionModelCollection` class has a function called `filterByResourceAuthorization` with the following check:

```
        if ($action instanceof DestructiveAction) {
            $models = $this->mapInto($request->resource())
                           ->filter->authorizedToDelete($request)->map->resource;
        }

```
So it seems that to be able to run a destructive action you have to be authorized to delete the model. Definitely not ideal. In my case I want to have a "cancel subscription" destructive action, but I don't want the customer accessing their subscription to be able to straight up delete the row from the database. 

Did you find a way to allow a destructive action without allowing the user to delete the model itself?

**Comment by ppisecky** [comment]
@calvinps That's really bad. Not all destructive actions equate to deletion of model. For example cancelling an order is a destructive action but it's not the same as deleting the model.

For the time being I believe you could just override the `authorizedToDelete` method on your resource and check the request object:

```php
/**
 * Determine if the current user can delete the given resource.
 *
 * @param  \Illuminate\Http\Request  $request
 * @return bool
 */
public function authorizedToDelete(Request $request)
{
    if ($request->action && $request->action === 'cancel-order') {
        return true; // or do custom checks.. also maybe check that the route matches nova-api/orders/action
    }

    return parent::authorizedTo($request, 'delete');
}
```

**Comment by liyansasongko** [comment]
Why closed?

**Comment by chescos** [comment]
Why is this closed?

**Comment by Kristories** [comment]
The issue still persists, but closed.

**Comment by timcv** [comment]
@davidhemphill Is this some thing you consider to fix?

**Comment by peterfox** [comment]
Is this still a known issue? I've been trying to make a destructive action perform on a Resource but it doesn't seem to use the callback to authorise instead it requires the deletion to be authorised but I don't want the delete button to work as I need to be able to put a flag on the resource's model instead.

**Comment by dennisoderwald** [comment]
+1

**Comment by Ryllaz** [comment]
Issue still exists.

**Comment by Kristories** [comment]
Solved with `canRun` method :

```
/**
 * Get the actions available for the resource.
 *
 * @param  \Illuminate\Http\Request  $request
 * @return array
 */
public function actions(Request $request)
{
    return [
        (new Actions\EmailAccountProfile)->canSee(function ($request) {
            return true;
        })->canRun(function ($request, $user) {
            return $request->user()->can('emailAccountProfile', $user);
        }),
    ];
}
```

**Comment by pokono** [comment]
@Kristories Does canRun works for destructive actions? Not working over here.

**Comment by reppair** [comment]
I ended up doing this in my `User.php` Nova Resource in order to disable the default delete button and still allow the destructive `DeleteUser` action to run..

```php
    /**
     * Custom authorization for the destructive action. This is required because of the UserPolicy::delete()
     * is used for both the custom destructive delete action and the standard delete resource button. The
     * problem is the action canRun() method only gets called if delete() auth method returns true, but
     * we want it to return false in order to hide the default delete button. Paragraph 22 case.
     *
     * See: https://github.com/laravel/nova-issues/issues/676
     * Also: https://github.com/laravel/nova-issues/issues/558
     */
    public function authorizedToDelete(Request $request): bool
    {
        // Decline resource deletions if not using the action.
        if ($request->segment(3) !== 'action')
            return false;

        // Authorize resource deletion when using the action.
        return $request->user()->can('runDeleteAction', \App\Models\User::class);
    }
```

@driesvints @taylorotwell Can't we have the closure passed to `Action::canRun(Closure $callback)` take precedence over the relevant policy method?

This way we can specify custom authorization per action and keep using the policy methods to control the the standard curd actions for Nova Resources as per current implementation and documentation.

**Comment by crynobone** [comment]
@reppair we already made the changes for Nova 4, and unlikely to change it on Nova 3 since it can cause a breaking change to some users.

**Comment by uandco** [comment]
I ran into a similar confusing issue with `canSee` and `canRun` so I might as well post it here if that helps.

In Nova 3 (not sure about 4), you don't need `canRun` (only `canSee` works) if the user running the action has the `update` policy on the model you're running the action against. But if the user cannot update, you need an additional `canRun` to allow the update.

It's not documented that there's an implicit `canRun` using the `update` policy if no specific `canRun` has been specified.
