### ISSUE TITLE
Resolve avatar url

### ISSUE THREAD

**Issue by dmitrybubyakin** [laravel/nova-issues#679]
I have a custom Image field, and I'd like to see it in the search results. Currently my custom field should extend `Laravel\Nova\Fields\Avatar` class.

Current solution:

```php
class CustomImage extends Avatar
{
}
```

Proposal:

```php
class CustomImage extends Image implements Avatar
{
}
```

**Comment by RonMelkhior** [comment]
You can also override the `resolveAvatarUrl` method.

```php
public function resolveAvatarUrl(NovaRequest $request): ?string
{
    return $this->thumb;
}
```

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
