### ISSUE TITLE
[Bug] Searching for numeric values >2147483647 throws exception with PostgreSQL

### ISSUE THREAD

**Issue by chescos** [laravel/nova-issues#680]
You can reproduce this bug by adding the `id` column to the `$search` property of a resource and then try to search for a numeric value that is greater than 2147483647. Only tested with PostgreSQL, not sure about MySQL.

I noticed this because I have some text columns that contain IDs with great numeric values and I tried to search for one of those IDs.

This is the exception:

```
SQLSTATE[22003]: Numeric value out of range: 7 ERROR:  value "2147483648" is out of range for type integer
```

This is an example SQL query that causes the exception:

```
SELECT *
FROM "users"
WHERE ("users"."id" = 2147483648
       OR "users"."id"::text ILIKE %2147483648%
       OR "users"."name"::text ILIKE %2147483648%
       OR "users"."email"::text ILIKE %2147483648%)
ORDER BY "users"."id" DESC
LIMIT 26
OFFSET 0
```

**Comment by chescos** [comment]
@davidhemphill any news on this?

**Comment by agvit** [comment]
it is a bug in trait PerformsQueries ( see PerformsQueries.php ), I fix it as follow:

protected static function applySearch($query, $search)
    {
        return $query->where(function ($query) use ($search) {

// AGV-FIX is_numeric --> is_integer
// errata            if (is_numeric($search) && in_array($query->getModel()->getKeyType(), ['int', 'integer'])) {
// corrige  is_numeric --> is_integer
          if (is_integer($search) && in_array($query->getModel()->getKeyType(), ['int', 'integer'])) {
                $query->orWhere($query->getModel()->getQualifiedKeyName(), $search);
            }
....
