### ISSUE TITLE
On a BelongsTo join show subtitle as well as title

### ISSUE THREAD

**Issue by alexbowers** [laravel/nova-issues#681]
On a BelongsTo field we show the `title` property, if a subtitle property has been defined, we should show that too like we do in the global search area.

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by fbingha** [comment]
I would like this as well. If I have to add data to the $title attribute for BelongsTo to show extended info, it defeats the purpose of adding it to $subtitle for Global Search as global search then ends up with double information.

**Comment by preliot** [comment]
Still very usefull to have
