### ISSUE TITLE
Set Where condition for relational column

### ISSUE THREAD

**Issue by kishoresai438** [laravel/nova-issues#683]
Hi team,

I am trying to add relational column in my form and able to get all the records in my select box. But I need to get records based in where condition. Please suggest on this.

`BelongsTo::make('organisation')`

Expecting the result like below. `organisation_type` is in organisation table.

`BelongsTo::make('organisation')->where('organisation_type', '=', '1')`

**Comment by iszmxw** [comment]
BelongsTo::where('organisation_type' '=', '1')->make('organisation')

**Comment by kishoresai438** [comment]
@iszmxw , it looks like where is not there for BelongsTo.  getting the below error.

`Method Laravel\Nova\Fields\BelongsTo::where does not exist.`
