### ISSUE TITLE
Where is a demo?

### ISSUE THREAD

**Issue by JILeXanDR** [laravel/nova-issues#684]
I did not find it :(
I need try a demo before pay 99$.

**Comment by GuidoHendriks** [comment]
Just request a refund it if you don't like it.

**Comment by JILeXanDR** [comment]
@GuidoHendriks 
To like or not - I need waste a lot of time to write functionality.
Demo admin page can show us all possible cases of functionality and possibilities of customization.....

**Comment by alexbowers** [comment]
There is currently not a demo of the system.

You are able to purchase, and if it doesn't fit your needs, request a refund.

Also, you can watch the video that Taylor made at Laracon US https://www.youtube.com/watch?v=pLcM3mpZSV0
