### ISSUE TITLE
$this->hasArgument returns true when there is no such argument name

### ISSUE THREAD

**Issue by phoenixg** [laravel/nova-issues#685]
My command signature is:

```php
protected $signature = 'cmd-my-script:check {date} {app_id?}';
```

As I run:

```shell
php artisan cmd-my-script:check 2018-08-25
```

It returns `true`, is it supposed to return `false`?

```php
public function handle()
{
    $arguments = $this->arguments();
    dd($this->hasArgument('app_id')); // true
}
```

using laravel 5.7.* and nova 1.1.3

**Comment by alexbowers** [comment]
Is this a bug with Laravel itself, or is it Nova specific?

**Comment by davidhemphill** [comment]
Not sure if there's a bug in Laravel related to this this is definitely a Laravel-only issue.

**Comment by phoenixg** [comment]
@alexbowers OK
