### ISSUE TITLE
uploaded image not display in view

### ISSUE THREAD

**Issue by ecore-agile** [laravel/nova-issues#686]
hi. i have to try to upload image in profile.php in field function bt its not working 
like this
```
public function fields(Request $request)
    {
        return [
        ID::make()->sortable(),
        BelongsTo::make('User')->rules('required'),
         Image::make('Avatar')
                    ->disk('public')
                    ->storeOriginalName('original_name')
                    ->prunable(),
        Text::make('Name')->rules('required')->sortable(),
        Place::make('address')->rules('required'),
        DateTime::make('birthdate')->rules('required')->format('DD MMM YYYY'),
        Text::make('email')->rules('required','email'),
       // Date::make('CreatedAt')->format('DD MMM YYYY'),
    

        ];
    }
```

**Comment by davidhemphill** [comment]
Your field configuration looks correct. Look like you just need to symlink your storage folder like described above.

**Comment by ecore-agile** [comment]
yes i also used php artisan storage:link to link public storage

**Comment by agilasadi** [comment]
@ecore-agile Did you figure what was the issue? I'm stuck at the same point as well

**Comment by DavidHR96** [comment]
> @ecore-agile Did you figure what was the issue? I'm stuck at the same point as well

Any solution?

**Comment by agilasadi** [comment]
@DavidHR96 In my case there the link to the image was not correct because there was base URL in .env I entirely cleaned it and it worked

**Comment by ecore-agile** [comment]
@DavidHR96 @agilasadi 
first of all link your public storage directory using **php artisan storage:link** 
Image::make('image','image')
                            ->disk('public')
                            ->path('photos')
                            ->prunable(),
try this

**Comment by agilasadi** [comment]
Let me guide you through, the way I did it.
Firstly create your folder `under storage/app/` that you want to use for the specific file upload.
Let's call it `post`.
here how your disk setting would look like in `config/filesystems.php`
`
    'disks' => [

        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
        ],

        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],

        'post' => [
            'driver' => 'local',
            'root' => storage_path('app/public/post'),
            'url' => env('APP_URL').'/storage/post',
            'visibility' => 'public',
        ],
`
and than run `php artisan storage:link`

and then remove `http://localhost` from envy. So `APP_URL=` will be empty

if you are all set, run `php artisan config:cache`

try now

**Comment by alcivarv** [comment]
I have been searching all over the internet to display my image!! This has helped me find the solution!! thanks a ton! Also, I am not sure why my image is not storing as the original file name, even when I have the ->storeOriginalName('original_name') -- Not sure if my routing is not done correctly

**Comment by Anticom** [comment]
For some reason the `Image` field doesn't honnor the development port (8000) for me.
I tried the solution proposed by @agilasadi but without luck. I tried both removing `APP_URL` from my .env as well as setting it to `http://localhost:8000` and ran `php artisan optimize:clear` after both modifications but without getting it to work.

**Comment by daugaard47** [comment]
> I have been searching all over the internet to display my image!! This has helped me find the solution!! thanks a ton! Also, I am not sure why my image is not storing as the original file name, even when I have the ->storeOriginalName('original_name') -- Not sure if my routing is not done correctly

Having this same issue. Original File Name stores fine in databse, but Original file name is changed to random string in storage folder...? Did you find a solution to this?

**Comment by NanoCellWebDesign** [comment]
> > I have been searching all over the internet to display my image!! This has helped me find the solution!! thanks a ton! Also, I am not sure why my image is not storing as the original file name, even when I have the ->storeOriginalName('original_name') -- Not sure if my routing is not done correctly
> 
> Having this same issue. Original File Name stores fine in databse, but Original file name is changed to random string in storage folder...? Did you find a solution to this?

Do you have a port on your local host, if so make sure its in .env APP_URL. i just wasted 2 hours on a new project before i realised

**Comment by kawuondo** [comment]
This is for others who need help with this, just go to php.ini in xampp and change the following to this:

upload file size max:
- upload_max_filesize = 50M
- post_max_size = 50M
- max_input_time = 300 
- max_execution_time = 300
