### ISSUE TITLE
Number field, scientific notation

### ISSUE THREAD

**Issue by reinierkors** [laravel/nova-issues#687]
I know this is default behaviour unrelated to Nova, but would be nice if it get's suppressed:

![test](https://j.gifs.com/qYzrO3.gif)

**Comment by dillingham** [comment]
Change it to a text field

**Comment by alexbowers** [comment]
This is the default functionality of the HTML element.

If you want different behaviour, feel free to use the `withMeta()` function to attach javascript functions inline, or use a different field type.
