### ISSUE TITLE
How do I define a field with default values?

### ISSUE THREAD

**Issue by youruan** [laravel/nova-issues#689]
I have a model, used by two or more Nova resource, when I create one model in one of those resource, I need give a different value to the same field, what should I do? thanks

**Comment by bonzai** [comment]
#58

**Comment by alexbowers** [comment]
Based on the linked issue, the following should work:

```
Text::make("Your Field")->withMeta(["value" => "Some Value"])
```

https://github.com/laravel/nova-issues/issues/58#issuecomment-419754713

**Comment by youruan** [comment]
thanks

**Comment by dillingham** [comment]
Set it as a default value on the model.
```php
public static function newModel()
    {
        $model = new static::$model;
        $model->setAttribute('title', 'Hello');
        return $model;
    }
```
