### ISSUE TITLE
Dropdown Value on BelongsTo with condition

### ISSUE THREAD

**Issue by GaurangGhinaiya** [laravel/nova-issues#690]
I have table called `category`

```
CREATE TABLE `categories` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `parent_id` int(11) NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `categories_name_unique` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```
Here is my category resource of nova file 
```
 public function fields(Request $request) {
        return [
            ID::make()->sortable(),
            Text::make('Name')->sortable()->rules('required', 'max:255'),
            BelongsTo::make('Parent Category', 'parent_category', 'App\Nova\Category'),
        ];
    }
```
I want to display only category that parent_id is 0 while create a category. So how can i do this?

**Comment by davidhemphill** [comment]
It seems like you want to use this package: https://novapackages.com/packages/epartment/nova-dependency-container

**Comment by GaurangGhinaiya** [comment]
@davidhemphill You get me wrong. I want something like
`BelongsTo::where('parent_id',0)->make('Parent Category', 'parent_category', 'App\Nova\Category')`
or 
`BelongsTo::make('Parent Category', 'parent_category', 'App\Nova\Category')->where('parent_id',0)`

**Comment by dillingham** [comment]
@GaurangGhinaiya you can add the where clause to the parent_category() method. no?

**Comment by GaurangGhinaiya** [comment]
@dillingham i already did it though i am getting all rows instead of few rows of `categories` table

**Comment by GaurangGhinaiya** [comment]
Duplicate of #683

**Comment by jasonspick** [comment]
This functionality is something I desperately need. so much I cannot use nova until I understand if this is possible. It would be preferable to add the where clause to the field rather than the model.

**Comment by GaurangGhinaiya** [comment]
@jasonspick Yeah i have to remove nova from my project just because i can't use condition on relationship.

**Comment by dillingham** [comment]
Read the docs https://nova.laravel.com/docs/1.0/resources/authorization.html#relatable-filtering

**Comment by jasonspick** [comment]
@dillingham The documentation needs to be expanded on. 1: it's not very clear what it does and 2: whether or not this will actually solve our issue.

**Comment by dillingham** [comment]
You want to filter on relations, the section is called Relatable Filtering
You would like to filter the queries that are used to populate relationship model selection menus

### A direction quote from that section
> If you would like to filter the queries that are used to populate relationship model selection menus, you may override the relatableQuery method on your resource.

**Comment by hadinajem** [comment]
You can do it inside your resource by extending the relatableQuery function
```
public static function relatableQuery(\Laravel\Nova\Http\Requests\NovaRequest $request, $query)
    {
        return $query->where('status', '1');
    }
```

**Comment by jShox** [comment]
I've got similar situation. So I made 2 different Resources. 1 for Index, 2 for Form.

```
            // 1) For Index
            BelongsTo::make('Category', 'category')->exceptOnForms(),

            // 2) For Forms
            Select::make('Category', 'category')->options(function () {
                        return \App\Models\Category::query()
                                       ->select(['id', 'name'])
                                       ->where('parent_id', '=', 0)
                                       ->pluck('name', 'id');
            })->onlyOnForms(),
```
