### ISSUE TITLE
Hiding elements from the index view

### ISSUE THREAD

**Issue by sergionader** [laravel/nova-issues#691]
Hello, 

In a list/index/grid view, 

1. Is there a simple way of hiding the view button or edit button or both?
2. hide the Create <Resource> button
3. hide the dropdown filter (the one that show 'per page;'). 
4. hide the check-box selector at the left of the grid. 

Or, how do I show them based on the @can @cannot directives?

Thanks,

Sergio Nader

**Comment by bonzai** [comment]
You can find answers for 1. and 2. here:

https://nova.laravel.com/docs/1.0/resources/authorization.html

**Comment by sergionader** [comment]
Thanks, @bonzai! Reading it now.

**Comment by sergionader** [comment]
Update: 
the following code (inside a valid and registered Policy), will hide every element I mentioned before: 
```  
 public function update(User $user, Model $model)
    {
        return false;
    } 
```

**Comment by sabrinanne** [comment]
Is it possible to hide the Edit button only in index and still show it in detail page?

**Comment by dkulyk** [comment]
Yes, It is

**Comment by sabrinanne** [comment]
how? :)

**Comment by Tanvir-Officials** [comment]
> Hello,
> 
> In a list/index/grid view,
> 
> 1. Is there a simple way of hiding the view button or edit button or both?
> 2. hide the Create  button
> 3. hide the dropdown filter (the one that show 'per page;').
> 4. hide the check-box selector at the left of the grid.
> 
> Or, how do I show them based on the @can @cannot directives?
> 
> Thanks,
> 
> Sergio Nader

hey did your find the solution for no.3 issue. did u able to hide the per page optioin from filter.

**Comment by vesper8** [comment]
Anyone figure out how to hide the filter button?
