### ISSUE TITLE
Detect loading status for a resource

### ISSUE THREAD

**Issue by daguilarm** [laravel/nova-issues#692]
Is it possible to detect when a resource has finished loading completely? It is because I want than a card be on loading status until the resource is loaded and the loading animation is off. I dont want users click on the button card until the page and the resources are totally loaded.

**Comment by ShayanSolution** [comment]
I have same question. please answer

**Comment by gbrits** [comment]
You can add to the footer of the layout file

     Nova.$on('resources-loaded', () => {
            console.log('Loaded');
     });
