### ISSUE TITLE
Can you get the resource in card on resource detail page?

### ISSUE THREAD

**Issue by Xsecrets** [laravel/nova-issues#695]
I have a card I've written that on the dashboard you choose a particular resource then do stuff related to it. I would like to have the card autoselect the current resource when on the resource detail page, but I haven't been able to figure out how to get any resource data in a card. It's not even in the request unless you count the referrer data, but that just seems like a really bad way to get what I need.

**Comment by davidhemphill** [comment]
Resource Detail cards receive the `resourceId` and `resourceName`, which you can use to hit the Nova API to fetch. That'd lead to multiple API calls obviously, so in the next release I'll pass the current resource to the detail card components as well, so you can just use it.

**Comment by encomienda** [comment]
@davidhemphill  how about passing resourceID to the cards method in a Resource?
