### ISSUE TITLE
 issue no #686 not solved.... i link storage & try to work on server bt still it not working

### ISSUE THREAD

**Issue by ecore-agile** [laravel/nova-issues#699]
i use this
for image preview issue bt this is also not working..
 
```
class Cors
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        return $next($request)
            ->header('Access-Control-Allow-Origin', '*')
            ->header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
    }
}
```

**Comment by ecore-agile** [comment]
![screenshot 11](https://user-images.githubusercontent.com/43604475/46125977-3f155d80-c1e0-11e8-99f5-9406d47e3bc1.png)
![screenshot 12](https://user-images.githubusercontent.com/43604475/46125980-43417b00-c1e0-11e8-903d-db66405f6a3e.png)


by using above code it display in table  bt not in show or edit page..

**Comment by ecore-agile** [comment]
plz solve my isssue...

**Comment by AegirLeet** [comment]
Please open your browser console (F12) and check for errors in the network tab. Any 404s?

**Comment by ecore-agile** [comment]
yes i have received 404 not found image in consol

**Comment by ecore-agile** [comment]
ok thanks i will try after update version..

**Comment by davidhemphill** [comment]
Closing for now, but if the issue persists feel free to comment and we'll look at it again.
