### ISSUE TITLE
Metrics NaN

### ISSUE THREAD

**Issue by TheDarkITA** [laravel/nova-issues#7]
NaN is displayed if the number is 1000 or more

<img width="929" alt="schermata 2018-08-23 alle 16 20 19" src="https://user-images.githubusercontent.com/1368128/44531226-88a9ee80-a6f0-11e8-9006-c5c6243d84b0.png">

**Comment by TheDarkITA** [comment]
My code is identical to the documentation:

return $this->count($request, Report::class);

**Comment by RicardoRamirezR** [comment]
I have the same issue using the code that code 
```php
return $this->count($request, User::class);
```
![image](https://user-images.githubusercontent.com/6526545/44532158-0a315a80-a6b8-11e8-8321-e3c516b45f22.png)

**Comment by themsaid** [comment]
ok we're fixing this
