### ISSUE TITLE
Label & count feature

### ISSUE THREAD

**Issue by Cannonb4ll** [laravel/nova-issues#70]
Would be nice if we can just 'display' a label in the overview, and a counter by relation.

Example:

![Image](http://screenshot.dennissmink.nl/300357d01d9f/Image%202018-08-23%20at%209.40.22%20PM.png)

**Comment by bonzai** [comment]
Use [computed fields](https://nova.laravel.com/docs/1.0/resources/fields.html#computed-fields).

**Comment by Cannonb4ll** [comment]
Thank you!
