### ISSUE TITLE
Nova relation field without resource

### ISSUE THREAD

**Issue by kishoresai438** [laravel/nova-issues#700]
Hi ,

Can't we create relation field with out Nova Resource? 

Example: I have two models as `User, UserEmail`. User model having UserEmail hasMany relational method(userEmail).

Created Resource for User which includes UserEmail relational field.  It is throwing error as `Class App\Nova\UserEmail` not found. Please check my User Resource and correct me.

```
**User Resource
---------**
public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),

            Text::make('First name')
                ->sortable()
                ->rules('required', 'max:255'),
            
            new Panel('Emails', $this->emailFields()),
        ];
    }

    protected function emailFields()
    {
        return [
            HasMany::make('userEmail');
        ];
    }
```

**Comment by davidhemphill** [comment]
You need a resource for every model and relation you wish to connect inside Nova.
