### ISSUE TITLE
No errors on saving the form

### ISSUE THREAD

**Issue by Catsys** [laravel/nova-issues#702]
If the form does not pass validation, then nothing happens. there are no notifications

**Comment by AegirLeet** [comment]
Please provide some example code.

**Comment by Catsys** [comment]
`public function fields(Request $request)
    {

        return [

            ID::make('id'),
	        Boolean::make('Активен', 'status'),
            Text::make('name')
                ->sortable()
	            ->rules('required')
];
}
....`

response
`{"status":"error","error_code":0,"error_message":"The given data was invalid."}`

**Comment by AegirLeet** [comment]
I recreated your resource, like this:
```
namespace App\Nova;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Laravel\Nova\Fields\Boolean;
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Fields\Text;

class TestModel extends Model
{
    // dummy
}

class Test extends Resource
{
    public static $model = TestModel::class;

    public function fields(Request $request)
    {
        return [
            ID::make('id'),
            Boolean::make('Активен', 'status'),
            Text::make('name')
                ->sortable()
                ->rules('required'),
        ];
    }
}

```

When submitting the empty form, i get this response:
```
{"message":"The given data was invalid.","errors":{"name":["The name field is required."]}}
```
And the error is also displayed below the form field.

Can you try creating a resource using my code (adjust namespace if necessary) and test again?

**Comment by Catsys** [comment]
no. dont work
ver 1.1.3
![image](https://user-images.githubusercontent.com/6561435/46139021-2a73ac80-c256-11e8-9766-9649c099323d.png)

**Comment by StanAngeloff** [comment]
Check you are not overriding `invalidJson()` in your `App\Exceptions\Handler` class.

**Comment by bigperson** [comment]
I have some problem.

**Comment by Brianop** [comment]
> Check you are not overriding `invalidJson()` in your `App\Exceptions\Handler` class.

How could I implement something to detect if the request is coming from nova?

**Comment by StanAngeloff** [comment]
> > Check you are not overriding `invalidJson()` in your `App\Exceptions\Handler` class.
> 
> How could I implement something to detect if the request is coming from nova?

From the [documentation](https://nova.laravel.com/docs/1.0/resources/#resource-events):

> If you would like to attach any observer only during Nova related HTTP requests, you may register a `Nova::serving` event listener within your application's `NovaServiceProvider`. This listener will only be executed during Nova requests.

There may be other ways, like inspecting if the URL matches `/nova*` (or whatever's configured in `config/nova.php['url']`).

**Comment by davidhemphill** [comment]
We are unable to debug your issue without a reproducible code example.

**Comment by 949mac** [comment]
@Brianop @bigperson @Catsys,

I had this same issue and was able to solve it by checking my App\Exceptions\Handler class.

My problem was that I was transforming the error response.

My response (that wasn't working) looked like:
![image](https://user-images.githubusercontent.com/23151962/49189534-968c9280-f323-11e8-9fbe-edce9c825e63.png)

```
{
  "error": {
    "first_name": [
      "The first name must be at least 2 characters."
    ]
  },
  "code": 422
}
```

When reverting the error response to the following, everything worked as expected
```
{
  "message": "The given data was invalid.",
  "errors": {
    "first_name": [
      "The first name must be at least 2 characters."
    ]
  }
}
```

**Suggested Debug Steps:**
1. Take a look at in your JS Inspector, and note the response
2. Does the response include an `errors` array?
3. Try replacing your App\Exception\Handler class with the following (below)
4. In Nova, submit the form again. Does your JSON response change? 

This should get you a little closer to solving it.

**Vanilla Laravel 5.7 Exception Handler (~/app/Exceptions/Handler.php)**
```
<?php

namespace App\Exceptions;

use Exception;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;

class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that are not reported.
     *
     * @var array
     */
    protected $dontReport = [
        //
    ];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array
     */
    protected $dontFlash = [
        'password',
        'password_confirmation',
    ];

    /**
     * Report or log an exception.
     *
     * @param  \Exception  $exception
     * @return void
     */
    public function report(Exception $exception)
    {
        parent::report($exception);
    }

    /**
     * Render an exception into an HTTP response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Exception  $exception
     * @return \Illuminate\Http\Response
     */
    public function render($request, Exception $exception)
    {
        return parent::render($request, $exception);
    }
}

```
