### ISSUE TITLE
How to have a space between two words?

### ISSUE THREAD

**Issue by activa-media** [laravel/nova-issues#703]
php artisan nova:resource CallLog

It shows in resource sidebar is CallLogs. How can I make it Call Logs ?

**Comment by outhebox** [comment]
Just override the label function inside your CallLog.php.

```php    
public static function label()
{
        return 'Call Logs';
}
```

**Comment by activa-media** [comment]
@outhebox It works! Thank you! By the way, where can I find this label() and singularLabel() original documentation?

**Comment by AegirLeet** [comment]
I couldn't find it in the online docs, but it's documented in the `Laravel\Nova\Resource` class.
