### ISSUE TITLE
How to set html attributes to fields?

### ISSUE THREAD

**Issue by bernhardh** [laravel/nova-issues#704]
Let's say we have a textarea, but it should only be shown 2 row height. In HTML it would be `<textarea rows="2" name="tworows"></textarea>`. How to do this with nova?

I know, I could do it with an css hack (something like `[name="tworows"] {height: 50px;}`), but thats not a real solution.

**Comment by bernhardh** [comment]
Ok, will use https://github.com/64robots/nova-fields in the meantime

**Comment by AegirLeet** [comment]
You'd have to modify _resources/js/components/Form/TextareaField.vue_ in your Nova sources and add it there:
`:rows="field.rows"`
And also remove the `min-h-textarea` class and add something like `style="height: auto;"` to prevent the field from using the default heights.

Then pass `->withMeta(['rows' => 2])` to the Field.

**Comment by bernhardh** [comment]
Thank you for this hint, but I don't want to overwrite nova files. If I would do it, I wouldn't be able to update nova.

**Comment by davidhemphill** [comment]
The ability to set rows on a `Textarea` field will be available in the next release. You'll be able to set it like this:

```php
Textarea::make('Name')->rows(2);
````

Also, the ability to set any attribute on a text or textarea field is coming in the next release. You'll be able to specify something like this:

```php
Textarea::make('Name')->withMeta([
    'extraAttributes' => [
        'readonly' => true
    ]
]),
```

**Comment by skoyah** [comment]
@davidhemphill I've noticed that de Boolean field lacks the option set extraAttributes

**Comment by osamaAbdullah** [comment]
> Textarea::make('Body')->withMeta([
>     'extraAttributes' => [
>         'readonly' => true
>     ]
> ]);

its working thank you.
