### ISSUE TITLE
dev/staging/production

### ISSUE THREAD

**Issue by sergionader** [laravel/nova-issues#707]
Hello, 
v1.1.3

1. I have three separated environments: local, staging and production.
2. I installed Nova on local and it works well. 
3. I tried to install it on staging and I am getting a 403 error saying "Sorry, you are not authorized to access this page. "
4. As the starting install had some problems, I am not sure if the mess. age relates to something that is not well set or if this is a licensing issue.
5. If this is a licensing issue, how can we handle the different envs from the same application? 

Thanks, 

Sergio Nader

**Comment by davidhemphill** [comment]
It’s not a license issue.

**Comment by bonzai** [comment]
@sergionader: See [Authorizing Nova](https://nova.laravel.com/docs/1.0/installation.html#authorizing-nova):

> This authorization gate controls access to Nova in non-local environments.

**Comment by sergionader** [comment]
Thank a lot, @bonzai!!!!!
It did the trick.

**Comment by lvidal1** [comment]
@bonzai thanks!
