### ISSUE TITLE
Can you add login settings to config

### ISSUE THREAD

**Issue by janicerar** [laravel/nova-issues#708]
Can you add this variables to config:

> nova.login.allow-reset-password: bool (Laravel\Nova\Nova::$resetsPasswords)
> nova.login.allow-register: bool (Laravel\Nova\PendingRouteRegistration->registered)

Because we do not want users to be able to register to Admin Panel or be able to send rest password email from there.

**Comment by AegirLeet** [comment]
Nova doesn't provide a registration page, right?
To disable password resets, can't you simply remove `->withPasswordResetRoutes()` from your NovaServiceProvider?

**Comment by janicerar** [comment]
I work. Tnx.
