### ISSUE TITLE
Add Apollo client

### ISSUE THREAD

**Issue by metalcamp** [laravel/nova-issues#709]
How would one add Apollo (GraphQL) client to Nova? There is a liftOff function in nova/resources/js/Nova.js which boots up a Vue app. In order to use Apollo client I would have to pass apolloProvider to app.
On the other side, when Nova gets updated, everything gets lost.

Can you please provide a sane way to make (Nova) Vue app extensible or simply add Apollo client?

**Comment by davidhemphill** [comment]
No plans to add Apollo to Nova at this time.
