### ISSUE TITLE
Date Class not rendering

### ISSUE THREAD

**Issue by nickels** [laravel/nova-issues#71]
Using v1.0.5

Hello the `Date class` is not rendering in my application. However when using the `DateTime class` it is rendering.

Migration:
`
$table->date('date_of_birth');
`

User Model;
`
protected $dates = [
        'date_of_birth',
    ];
`

User Resource (Nova)
`
Date::make('Date of Birth')->updateRules('required'),
`

**Comment by anderly** [comment]
If you open browser console, do you see any errors?

**Comment by nickels** [comment]
@anderly just reinstalled Nova. Seems to be working. Guess reinstall did the trick. Closing this issue. Thanks for reaching out!
