### ISSUE TITLE
BelongsTo field inside a BelongsTo Field

### ISSUE THREAD

**Issue by Athuli7** [laravel/nova-issues#711]
eg:-

**Person A** in his capacity as **Sr Eng** 
And 
**Person B** in her capacity as **Jnr Auditor**
Approved of 
**Entity X**

The **Capacities** are pulled from a DB.
**Person** belongsToMany **Entities**, each pivot holds the person's capacity.  

Problem:
There is a provision to use a normal field like text, But I'm unable to set a relationship there. Probably due to the inability to define it in the model.

```
BelongsToMany::make('Judges')->searchable()->fields(function () {
    return [
        BelongsTo::make('Generics', 'judge_type_id'),
        //Number::make('judge_type_id'),
    ];
}),
```

**Comment by noahlocke** [comment]
@Athuli7 did you make a custom field called "Generic"?

**Comment by dillingham** [comment]
Duplicate https://github.com/laravel/nova-issues/issues/145

**Comment by Athuli7** [comment]
@noahlocke, no. Sorry about the confusion, Generic is a Model where I hold the Types.

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
