### ISSUE TITLE
Showing the panes when editing

### ISSUE THREAD

**Issue by sergionader** [laravel/nova-issues#712]
Is there a way of showing the panels when editing? 
In my case, they only show when in the view mode. 
Thank you!
Sergio Nader

**Comment by dillingham** [comment]
Search the issues before asking questions

**Comment by dillingham** [comment]
This doesn't seem to be an issue. This is a question.
Maybe join the [Discord chat ](https://discord.gg/DgdFRpd) or [Larachat slack](https://larachat.co/slack) or ask on [stackoverflow](https://stackoverflow.com/questions/tagged/laravel-nova)
All of those options have people willing to help and answer questions! 😄

**Comment by davidhemphill** [comment]
Duplicate of #29
