### ISSUE TITLE
Using Nova inside a current app

### ISSUE THREAD

**Issue by sergionader** [laravel/nova-issues#714]
1. 1. In my current app, I have `domain/app/clients` that display a client list. 
2. 2. I created a Nova resource that does the same: `domain/nova/resources/clients`
3. 3. I am trying to figure out how to show the new Nova grid using the old URL (../app/clients). 
4. Also, I don't want a redirect as the user should always the see the 'old' URL (app/clients)/ 

Any suggestion? 

Thank you!
Sergio Nader

**Comment by dillingham** [comment]
This doesn't seem to an issue. This is a question.
Maybe join the [Discord chat ](https://discord.gg/DgdFRpd) or [Larachat slack](https://larachat.co/slack) or ask on [stackoverflow](https://stackoverflow.com/questions/tagged/laravel-nova)
All of those options have people willing to help and answer questions! 😄

**Comment by davidhemphill** [comment]
Nova's URIS aren't customizable at that level.
