### ISSUE TITLE
Multiple Relations to same Model not working

### ISSUE THREAD

**Issue by Athuli7** [laravel/nova-issues#715]
```
            BelongsToMany::make('Lawyer', 'PetitionerLawyers')->searchable()->fields(function () {
                return [
                    Select::make('Type', 'lawyer_type_id')->options(
                        Generic::where('key', 'Lawyer Type')->get()->pluck('val', 'id')->toArray()
                    )->displayUsingLabels()
                ];
            }),
            BelongsToMany::make('Lawyer', 'RespondentLawyers')->searchable()->fields(function () {
                return [
                    Select::make('Type', 'lawyer_type_id')->options(
                        Generic::where('key', 'Lawyer Type')->get()->pluck('val', 'id')->toArray()
                    )->displayUsingLabels()
                ];
            }),
```

2 Relations with separate pivots. The second one overrides the first.

**Comment by davidhemphill** [comment]
Why do you need two relations with the same label?

**Comment by ghaskell** [comment]
It looks like you may be confusing the arguments @Athuli7 (they're not well-documented atm).

The first argument is the label, the second is the relationship, and the third (undocumented) is the Nova Resource Class. 

If I understand your issue, the correct code would be: 

 ` BelongsToMany::make('PetitionerLawyers', 'Lawyer', Lawyer::class)` 

` BelongsToMany::make('RespondentLawyers', 'Lawyer', Lawyer::class)` 

@davidhemphill I've seen many issues related to this documentation issue.  Are the docs open to PR's?

**Comment by Athuli7** [comment]
As far as I can see, 
![screen shot 2018-09-28 at 07 13 44 am](https://user-images.githubusercontent.com/4718029/46183341-2bf0b380-c2ee-11e8-9c40-e7b4e6b5c477.png)

**Comment by ghaskell** [comment]
Cool, thanks @Athuli7 hadn't seen this repo (probably in the docs) 💯
