### ISSUE TITLE
Feature Request: Make "Per Page" options configurable.

### ISSUE THREAD

**Issue by anderly** [laravel/nova-issues#72]
Would be nice to be able to configure the "Per Page" options, maybe by defining them `config/nova.php` like so:

```
    'per_page' => [
        10,
        15,
        20,
    ];
```

Or maybe via `NovaServiceProvider.php` like:

```
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        parent::boot();

        Nova::options([
            'per_page' => [
                10,
                15,
                20,
            ];
        ]);
    }
```

There are cases where 10 records per page might be appropriate, or 15, etc. or you might want to disable 50, etc.

**Comment by danrichards** [comment]
Configureable at the resource level would be very cool.

**Comment by anderly** [comment]
@danrichards yep, ideally a global configurable setting with per-resource overrides.

**Comment by poxin13** [comment]
Available for relationships
```
    /**
     * The number of resources to show per page via relationships.
     *
     * @var int
     */
    public static $perPageViaRelationship = 5;
```

**Comment by carloshc** [comment]
> How can I change the per page via relationships and per_page so far?

In the resource file that you want to modify the _per page_, override the attribute.

````php
class Comments extends Resource
{

public static $perPageViaRelationship = 10;
````

**Comment by dillingham** [comment]
Also opt-out-able for when you don’t want the option

**Comment by noahlocke** [comment]
@davidhemphill seems like this could easily just be a filter (like it already is on the index) with the option of a default value?

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by keyur5390** [comment]
* Laravel Version: 5.7.19
* Nova Version: 1.1.3

Nova default gives an per page count `25` and filter option of 25, 50, 100.
In my case I want to change this values as I have thousands of records in my 2 modules, so I am fine with default per page result on other pages but I want to change per page number on my these two modules. So how could I change these default per page to my modules?

**Comment by bolechen** [comment]
+1

**Comment by mauricehofman** [comment]
Why is this closed? Does this feature request needs to be re-created because its auto-closed? I think this is a nice feature. 

Something like adding it as a array property to the Resouce class, and then using it as a prop in the FilterMenu.vue? Maybe also adding a second property integer which defines the default 'per page' amount.

**Comment by anderly** [comment]
@davidhemphill put together a quick gist that shows the small changes to `FilterMenu.vue` and `Index.vue` needed to make this work: https://gist.github.com/anderly/e606626f13601c1d22dea65b3571ad28/revisions#diff-ca0f38cd4a45cccfad57e83eb445105a

Then, the `NovaServiceProvider.php` simply needs this:

```php
    Nova::provideToScript([
        'perPageOptions' => config('nova.perPageOptions', [25, 50, 100]),
    ]);
```

`config/nova.php` would store the global default like so:

```php
    'perPageOptions' => [
        10,25,50,100
    ],
```

Finally, the base `Resource` would need:

```php
    /**
     * Get the perPageOptions for the resource.
     *
     * @return array
     */
    public static function perPageOptions(): array
    {
        return static::$perPageOptions ?? [];
    }
```

Then, this could be added to the client config for the resource with a call to `additionalInformation` on the BaseResource or better yet by adding it to the `resourceInformation` method in `Nova.php` like so:

Example:
```php
/**
     * Get meta data information about all resources for client side consumption.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public static function resourceInformation(Request $request)
    {
        return collect(static::$resources)->map(function ($resource) use ($request) {
            return array_merge([
                'uriKey' => $resource::uriKey(),
                'label' => $resource::label(),
                'singularLabel' => $resource::singularLabel(),
                'authorizedToCreate' => $resource::authorizedToCreate($request),
                'searchable' => $resource::searchable(),
                'perPageOptions' => $resource::perPageOptions(),
            ], $resource::additionalInformation($request));
        })->values()->all();
    }
```

Then, you can override these settings on specific resources if desired by defining the resource-specific static `$perPageOptions` like so:

```php
// In a given resource class

public static $perPageOptions = [5, 10, 15, 20];
```

**Comment by dkulyk** [comment]
@anderly You can make a PR with changes.
For getting access to repository you should to [connect to github](https://nova.laravel.com/settings#github)

**Comment by anderly** [comment]
@dkulyk done.

**Comment by keyur5390** [comment]
@anderly In which version your solution is affected? I am using version 1.1.3, does it work for me? If so how could I change my code of app.js file?

Thanks

**Comment by Budy-Love** [comment]
How can i access the config helper in App\Nova\Resource? I want set the default in config\nova.php as mentioned.

in config\nova.php i have added 

```php
'perPageViaRelationshipconfig' => 25,
```

and in App\Nova\Resource

```php
public static $perPageViaRelationship = config('nova.perPageViaRelationshipconfig', 5);
```

**Comment by ievgenklymenko** [comment]
Also would be nice to hide 'Per page' filter completely

**Comment by bilfeldt** [comment]
@davidhemphill is it possible to set the perPageViaRelationship for a given relationship when defining it? That way it is possible to use a different list for each relationship.

Example:

```
HasMany::make('Posts')->perPage(50)
```

**Comment by keizah7** [comment]
You can reverse order, and first element will be selected:

```
/**
 * The per-page options used the resource index.
 *
 * @var array
 */
public static $perPageOptions = [100, 50, 25];

```

**Comment by nickbluestone98** [comment]
You can now do this directly in your Resources. No additional code is required.

```
public static function perPageOptions()
 {
      return [5, 10, 25, 50, 100, 150];
 }
```

More info here: https://nova.laravel.com/docs/3.0/resources/#customizing-pagination
