### ISSUE TITLE
Registration / Signup Page?

### ISSUE THREAD

**Issue by rehmatworks** [laravel/nova-issues#723]
I know this place is for bug reporting, but why there isn't a registration page for users? If the admins don't need to show, they should disable registration feature from config. If any solid reason is there to not provide a registration page, please let us know as this is a crucial part of the websites and without registration page, it is really incomplete.

**Comment by davidhemphill** [comment]
Probably not gonna add this as its better to add your admin users directly using the `nova:user` tool for security reasons.

**Comment by Elshaden** [comment]
@davidhemphill You have it in Forge!.
![image](https://github.com/laravel/nova-issues/assets/33955172/f708ff18-e677-489a-b77b-adec2fc9f738)

I think Nova should have it as an optional route available. so that we do not have to override the login page.

**Comment by davidhemphill** [comment]
@Elshaden I don't work on Forge or for Laravel, but I can tell you this is Forge's signup and login. It redirects to Nova if initially redirected from `/nova`. Nova does not have a signup page.
