### ISSUE TITLE
How to achieve attach like structure for oneToMany relationship?

### ISSUE THREAD

**Issue by bigbharatjain** [laravel/nova-issues#728]
Eg. Region and City are two models. Region can have multiple cities but a city can be associated with a single Region only. For this, I am having a list of cities already added but want to attach city with the region on the details page of a region just like if we have a many-to-many relationship.

**Comment by rivenme** [comment]
I need this as well.

**Comment by davidhemphill** [comment]
Please provide some code, will unclose when you do.

**Comment by bigbharatjain** [comment]
Following are the Region and City Model:

**Region.php**

    <?php
    
    namespace App;
    
    use Illuminate\Database\Eloquent\Model;
    
    class Region extends Model
    {
        public function cities() {
            return $this->belongsToMany('App\City');
        }
    }


----------
**City.php**

    <?php
    namespace App;
    
    use Illuminate\Database\Eloquent\Model;
    
    class City extends Model
    {
        public $timestamps = false;

        public function region() {
            return $this->belongsToMany('App\Region');
        }
    }


And in Nova Resource for Region, I have fields method as below:


    public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
            Text::make('Region Name')->rules(['required', 'max:191'])->sortable(),
            HasMany::make('Cities')
        ];
    }

I can attach cities to the region from this. My question is, how can I validate so that a city can only be attached to one region only i.e. if I have attached any city to region, that city can't be attached to any other region.

**Comment by AegirLeet** [comment]
Your relationships are wrong.

In your database, the `cities` table needs to have a `region_id` field.
**Region** should use `$this->hasMany('App\City')`, because one Region can have many cities.
**City** should use `$this->belongsTo('App\Region')`, because one City can only belong to one Region.
In your **Region Resource**, use `HasMany::make('Cities')`.
In your **City Resource**, use `BelongsTo::make('Region')`.

**Comment by bigbharatjain** [comment]
I am agree with you @AegirLeet but my need is to have many-to-many relationship, just need to validate so that we can only attach one city to one region only in the pivot table.

**Comment by dillingham** [comment]
Write a custom validation rule that checks the for the combination. We aren’t here to write your code :) 

https://nova.laravel.com/docs/1.0/resources/validation.html

https://laravel.com/docs/5.7/validation#using-rule-objects
