### ISSUE TITLE
Mix manifest error on production

### ISSUE THREAD

**Issue by mojosef** [laravel/nova-issues#729]
v1.1.3

I'm receiving this error:

The Mix manifest does not exist. (View: ~/nova/resources/views/auth/layout.blade.php).

The exception is also ignoring my APP_ENV=production variable and printing out the full exception.

Thanks for any help.

**Comment by mojosef** [comment]
I have yeah, with the --force flag also.

**Comment by AegirLeet** [comment]
Does _public/vendor/nova/mix-manifest.json_ exist and is the view you mentioned above using that manifest (by passing `'vendor/nova'` as the second argument to `mix()`)?

**Comment by mojosef** [comment]
The manifest doesn't exist ( I was assuming there was a build process that happened to generate this? ). `vender/nova` is the second argument in `mix()`

**Comment by AegirLeet** [comment]
Nova is distributed with those files already built. You can (re)build them yourself by running `npm run build` in the nova directory.
The files should be in _nova/public/_. The `nova:publish` command copies these into your _public/vendor/nova/_ directory. It should output something like `
Copied Directory [/vendor/laravel/nova/public] To [/public/vendor/nova]`.

**Comment by davidhemphill** [comment]
@AegirLeet is right, the production build files come with the package. `nova:publish --force` should put those files in the correct place . Where are you seeing this exception being thrown?

**Comment by mojosef** [comment]
@AegirLeet @davidhemphill It seems to be a git issue. When I'm copying over the files ( for an update ) certain files seem to be missing. Thanks both for your responses but I'm pretty sure this isn't related to nova now

**Comment by mattdeclaire** [comment]
For future reference, I had a bare `mix-manifest.json` in my `.gitignore`, which prevented me from checking in the Nova manifest. I changed it to `/public/mix-manifest.json` to properly ignore just the app manifest I was creating at build time.

**Comment by Ali-Shaikh** [comment]
Make sure that you are adding '/vendor' in your .gitignore and not 'vendor'. Adding just 'vendor' will ignore all folders named vendor in your codebase and nova resources are in the vendor folder in public folder.

**Comment by KangYoosam** [comment]
running `php artisan nova:publish` command solved my problem.
