### ISSUE TITLE
Integrate nova-js into core

### ISSUE THREAD

**Issue by alexbowers** [laravel/nova-issues#73]
Made a comment on nova-js, but will post here too for visibility.

Currently, it's really difficult to get nova-js setup for being able to change any of its code. Moving the nova-js into core will make it much easier.

I have done the work required to do this, and from my testing there is no side effects regarding compilation times, size of output, but it does make it drastically easier to work with and contribute towards.

[0001-Import-nova-js-into-nova-core.txt](https://github.com/laravel/nova-issues/files/2315939/0001-Import-nova-js-into-nova-core.txt)

**Comment by alexbowers** [comment]
https://github.com/laravel/nova-js/issues/2 reference

**Comment by davidhemphill** [comment]
Have you tested this on Windows to confirm the symlinking issue is not a problem?

**Comment by alexbowers** [comment]
I have not, I do not have a windows machine to test on

**Comment by alexbowers** [comment]
However, I don't see how I would have created any additional issues that Nova does not already have if that is the case, since I am copying the same technique being used by other parts of Nova, namely all of the components

**Comment by cretueusebiu** [comment]
@davidhemphill You don't have to import the real module, just make nova-js available globally in the Nova build and when a package needs it, you can simply specify it via the `externals` option for webpack. 

See #388

**Comment by taylorotwell** [comment]
This repository is for tracking bugs. Feature requests may be emailed to Nova customer support.
