### ISSUE TITLE
ConfirmActionModal.vue missing translate

### ISSUE THREAD

**Issue by mingyoung** [laravel/nova-issues#730]
File: `/resources/js/components/Modals/ConfirmActionModal.vue`
Line: 47

Button `Cancel`

![image](https://user-images.githubusercontent.com/6228858/46209541-b40fa100-c360-11e8-9996-6b7bd35e5e3c.png)

Should be `{{__('Cancel')}}`

**Comment by davidhemphill** [comment]
This has been fixed and will be included in an upcoming release.

**Comment by mingyoung** [comment]
@davidhemphill 

File: `/resources/js/components/Detail/FileField.vue`
Line: 39

![image](https://user-images.githubusercontent.com/6228858/46252776-0acfc480-c4a0-11e8-8caa-2be5e2201108.png)
