### ISSUE TITLE
Handling or overriding CRUD methods?

### ISSUE THREAD

**Issue by XGhozt00** [laravel/nova-issues#735]
Does Nova allow us to do this in some way?

I need to override the delete method to handle foreign key constraints.
And what about handling the request data before processing the update or create?

**Comment by dillingham** [comment]
https://nova.laravel.com/docs/1.0/resources/#resource-events

**Comment by XGhozt00** [comment]
Thanks @dillingham -- but I'm not sure that will work for me. Maybe this is the wrong approach? I need to display an error when a user tries to delete another User that fails foreign key constraints. Or I need to remove the associations with the User before the user is deleted.

Right now when I try to delete a User I just get:

`Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails`

Also, I created the UserOverserver pretty much exactly like the example and I can't tell that it's actually doing anything?

**Comment by dillingham** [comment]
@XGhozt00 maybe something like this in your user model

```php
    public static function boot()
    {
        parent::boot();

        static::deleting(function ($user) {
          // --- do stuff
        });
    }
```
or maybe [soft deleting](https://laravel.com/docs/5.7/eloquent#soft-deleting) to avoid the error and trigger the observer deleted event handler to allow you to force delete after the constraint is satisfied

**Comment by XGhozt00** [comment]
Thanks @dillingham ! I will try that. I also just discovered that I need to define a `$dispatchesEvents` which is why it wasn't doing anything. Oops.
