### ISSUE TITLE
Localizations

### ISSUE THREAD

**Issue by lfukumori** [laravel/nova-issues#739]
en.json
Missing string:
`    "The :resource was updated!": "The :resource was updated!",
`

ConfirmActionModal.vue
From:
`                    <button dusk="cancel-action-button" type="button" @click.prevent="handleClose" class="btn text-80 font-normal h-9 px-3 mr-3 btn-link">Cancel</button>
`
To:
`                    <button dusk="cancel-action-button" type="button" @click.prevent="handleClose" class="btn text-80 font-normal h-9 px-3 mr-3 btn-link">{{__('Cancel')}}</button>
`

ActionSelector.vue
From:
`                title="Run Action"
`
To:
`                title="__('Run Action')"
`
Related image issue above:
![image](https://user-images.githubusercontent.com/8474568/46245963-4a79ac00-c3cd-11e8-8b57-b0e702ca6944.png)

Another problem:
![image](https://user-images.githubusercontent.com/8474568/46245975-709f4c00-c3cd-11e8-8f35-732107dc7374.png)

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
