### ISSUE TITLE
Searchable BelongsTo field bug

### ISSUE THREAD

**Issue by lucasromanojf** [laravel/nova-issues#74]
1) Create a model with a Searchable BelongsTo field filled
2) Edit the model
3) The Searchable BelongsTo field will:

Issue 1: Be empty
Issue 2: Not be able to clear the previously stored value

**Comment by taylorotwell** [comment]
Can't recreate. Works fine for me.

**Comment by lvdhoorn** [comment]
Weird i still have an issue with the Searchable BelongsTo field.

If i create a resource with a Searchable BelongsTo field (let say country) and after the create i do an edit and make the country field empty it will keep the old value and not empty it.

I get no errors and the field is nullable in the database.

`BelongsTo::make('Country')->searchable()->sortable()->nullable()`
