### ISSUE TITLE
Link ID/Title Text on Index to Detail Page (similar to BelongsTo)

### ISSUE THREAD

**Issue by loren138** [laravel/nova-issues#741]
I'm trying to link the first column of my table to the detail page so users don't have to scroll all the way to the right to get to the view button.  (Similar to a belongs to relation but for this resource itself.)

Currently, I've made it work using the new `asHtml` feature, but it does a full page reload rather than a nice HTML5 transition.  I've tried to use a vue `router-link` but that doesn't seem to get compiled.

### Title field
```
            Text::make('Thickness Name', 'Name')->sortable()->rules('required')->displayUsing(function ($value) {
                return view('link', [
                    'id' => $this->ID,
                    'value' => $value,
                    'slug' => $this->uriKey()
                ])->render();
            })->asHtml(),
```

### Link Blade Template
```
<a href="/admin/resources/{{$slug}}/{{$id}}" class="no-underline dim text-primary font-bold">{{$value}}</a>
```

**Comment by dillingham** [comment]
Duplicate https://github.com/laravel/nova-issues/issues/672

**Comment by loren138** [comment]
Thanks!  Closing mine.  I tried searching for `internal link` and `link index to detail`, but missed yours since it just has `link detail` without the index part.

**Comment by dillingham** [comment]
@loren138 you're right, I made the title more searchable

**Comment by dillingham** [comment]
package https://github.com/dillingham/nova-id-link
