### ISSUE TITLE
[request] Back Button On Attach Page

### ISSUE THREAD

**Issue by loren138** [laravel/nova-issues#742]
Can we add a back button to the header of the attach page like the lens page?  Looks like everything needed for that is already there, just need to change the header to

```
        <heading class="mb-3">
            <router-link
                    :to="{
                    name: 'detail',
                    params: {
                        'resourceName': resourceName,
                        'resourceId': resourceId
                    }
                }"
                    class="no-underline text-primary font-bold dim"
                    data-testid="lens-back"
            >
                &larr;
            </router-link>
            {{__('Attach')}} {{ relatedResourceLabel }}
        </heading>
```

~~Also, it would be really nice to show the title of the resource you are attaching to, but that seems harder.~~ (Covered in #614 as mentioned below)

**Comment by dillingham** [comment]
https://github.com/laravel/nova-issues/issues/614 😄 I think if the title was linked it would awesome too

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
