### ISSUE TITLE
Having multiple BelongsTo on the same Model locks related model on both fields during Create

### ISSUE THREAD

**Issue by reado** [laravel/nova-issues#743]
Hey everyone

Just a quick question.. I ran into a problem and I'm wondering if anyone has a suggestion.

I have a scenario where my Nova Resource (named Answer) has 2 BelongTo relationships to the same model (named Question).

I have two fields in my Answer model, on that points to the 'parent' question and one that points to another Question.

When I go through the flow -> Display a particular Question -> Answers -> Add Answer, the question that I had displayed is locked to my "parent" question by disabling the select drop down which is great.. but unfortunately, it's also locked my 'next question' selection as well.

Is it possible to optionality disable the "auto disable" feature of a certain field relationship in scenarios like a create flow?

In theory both drop downs are just returning model id numbers anyway and I'm assuming the disabled select is a connivence for creating a new related model, but it would be nice to be able to disable that functionality when not needed.

Any suggestions would be appreciated!

Thanks!

**Comment by lmatab** [comment]
What was the solution for this problem?

I am a similar situation, I have an order table that has two belongsTo fields ( sender_id and recipient_id) and I have another table with el client information like this:

Order table:
id
sender_id
recipient_id

Client table:
id
name

On the Order model I have :


        public function sender()
        {
            return $this->belongsTo('App\Client', 'sender_id');
        }

        public function receptor()
        {
            return $this->belongsTo('App\Client', 'receptor_id');
        } 

On the Client model:

public function orders() {
    return $this->hasMany('App\Order', 'receptor_id');
}

How can I make this work with nova?

Thanks
