### ISSUE TITLE
[Bug] MorphTo not working on form edit when there is a morphmap assigned

### ISSUE THREAD

**Issue by paras-malhotra** [laravel/nova-issues#744]
This is a reopen of #430 opened 25 days ago as it has not yet been fixed but closed. This issue persists in Nova 1.1.3 so please do not close this assuming this has been fixed. It has not!!

I have a MorphMap assigned in my AppServiceProvider like so:

```
Relation::morphMap([
    'campaign' => Campaign::class,
    'campaign_offer' => CampaignOffer::class,
]);
```

In my resource class, I defined the MorphTo field (with columns named related_id, related_type) like so:

```
MorphTo::make('Related')->types([
    Campaign::class,
    CampaignOffer::class,
])->searchable(),
```

On the index and the detail page, all is good! We can see the related campaign and campaign offers. But on the form page, when I click edit on a record, the values are not pre-populated properly. Here are the screenshots:

Index Page looking good:

<img width="1132" alt="screen shot 2018-09-04 at 10 01 08 pm" src="https://user-images.githubusercontent.com/16099046/45044722-8f404a80-b08e-11e8-8745-69bedd288a84.png">

Form Detail looking good:

<img width="1146" alt="screen shot 2018-09-04 at 10 03 56 pm" src="https://user-images.githubusercontent.com/16099046/45044759-a54e0b00-b08e-11e8-923d-f1fc51eff37b.png">

Form edit broken (this is for ID 421 as shown in the screenshots above) ! The expected behaviour is that it should have the associated Campaign Offer populated on the edit page

<img width="1136" alt="screen shot 2018-09-04 at 10 04 06 pm" src="https://user-images.githubusercontent.com/16099046/45044775-b1d26380-b08e-11e8-966a-734b7e62a92a.png">

**Comment by itsgonnabesick** [comment]
I had the same problem and fix it by initialising the Nova::$resourcesByModel attribute in NovaServiceProvider.

```php
   /**
     * Register the application's Nova resources.
     *
     * @return void
     */
    protected function resources()
    {
        Nova::resourcesIn(app_path('Nova'));
        $morphMap = collect(include(app_path('Maps\MorphMap.php')))->flip();
        Nova::$resourcesByModel = collect(Nova::$resources)->mapWithKeys(function($resource) use ($morphMap) {
            $model = ($resource)::$model;
            if(isset($morphMap[$model])){
                return [$morphMap[$model] => $resource];
            }
            return [];
        });
    }
``` 

A bit sketch but at least it works now.

**Comment by rodrigore** [comment]
@itsgonnabesick  Thanks,  it works!

**Comment by crnkovic** [comment]
It seems that I have found a fix for this bug in Nova's code. Hopefully someone from the Nova team will find this.

The bug was in a `resolveMorphType` method in the `Laravel\Nova\Fields\MorphTo` class. Current state of the code is:

```php
/**
 * Resolve the current resource key for the resource's morph type.
 *
 * @param  mixed  $resource
 * @return string|null
 */
protected function resolveMorphType($resource)
{
    if (! $type = optional($resource->{$this->attribute}())->getMorphType()) {
        return;
    }

    if ($morphResource = Nova::resourceForModel($resource->{$type})) {
        return $morphResource::uriKey();
    }
}
```

However, what if the `$resource->{$type}` returns an alias instead of the model class name? Then, `Nova::resourceForModel('alias')` would not find the model and therefore would not populate the form field. The fix is to find the model by the alias in the morph map before finding the resource:

```php
/**
 * Resolve the current resource key for the resource's morph type.
 *
 * @param  mixed  $resource
 * @return string|null
 */
protected function resolveMorphType($resource)
{
    if (! $type = optional($resource->{$this->attribute}())->getMorphType()) {
        return;
    }

    $model = $this->getMorphAliasForClass($resource->{$type});

    if ($morphResource = Nova::resourceForModel($model)) {
        return $morphResource::uriKey();
    }
}
```

On a related note, `getMorphAliasForClass` in the same class can be simplified by using `getMorphedModel` method on the Relation class, instead of looping through the `$morphMap` variable:

```php
/**
 * Get the morph type alias for the given class.
 *
 * @param  string  $class
 * @return string
 */
protected function getMorphAliasForClass($class)
{
    return Relation::getMorphedModel($class) ?? $class;
}
```

If this happens too on other polymorphic relationships, let me know and I'll find the bugfix for those too.

**Comment by paras-malhotra** [comment]
@davidhemphill @taylorotwell would really appreciate if you could help us with this issue 🙏. Some folks have posted code change suggestions as well.

**Comment by paras-malhotra** [comment]
@crnkovic I couldn't get your solution to work for some reason. @itsgonnabesick's solution works well! Thanks! Hopefully this would be incorporated in the Nova code base soon.

**Comment by bonzai** [comment]
@paras-malhotra: Can you check if the following code fixes the issue?

```php
protected function resolveMorphType($resource)
{
    if (! $type = optional($resource->{$this->attribute}())->getMorphType()) {
        return;
    }

    $value = $resource->{$type};

    if ($morphResource = Nova::resourceForModel(Relation::getMorphedModel($value) ?? $value)) {
        return $morphResource::uriKey();
    }
}
```

Don't change anything else in the `getMorphAliasForClass` method.

**Comment by paras-malhotra** [comment]
@bonzai that works perfectly. Thanks!

**Comment by bonzai** [comment]
I sent a PR and this should be merged soon.
