### ISSUE TITLE
[Nova 1.1.3] Many to many pivot with resource

### ISSUE THREAD

**Issue by EdanBrooke** [laravel/nova-issues#747]
Hi,

In my application I have Establishments, Roles and Users.
An Establishment has many Users, and a User has many Establishments.

This is achieved through a M:M pivot table with a Role associated with it so a User has a role in an Establishment.

In Nova, I've got to the point where I can add a User to an Establishment but must type the Role ID manually. I'd instead like to be able to pick the role from a dropdown and can't get this to work.

Any ideas?

Thanks,
Edan

**Comment by EdanBrooke** [comment]
Lol @dillingham - there's a "question" label that's been applied. Stop being difficult.

**Comment by dillingham** [comment]
Difficult? Well I know the answer to your question should you decide to use the proper channels 😎
