### ISSUE TITLE
ResourceId in class validation rule

### ISSUE THREAD

**Issue by Sparclex** [laravel/nova-issues#749]
At the moment it is not possible to use `{{resourceId}}` in class validation rules or custom class validation rules. 
```php
File::make('file')->updateRules( new DataFile('{{resourceId}}')
```
since the `{{resourceId}}` only gets replaced in string rules:
```php
return collect($rules)->map(function ($rules) use ($replacements) {
            return collect($rules)->map(function ($rule) use ($replacements) {
                return is_string($rule)
                            ? str_replace(array_keys($replacements), array_values($replacements), $rule)
                            : $rule;
            })->all();
        })->all();
```

As a workaround we could retrieve the resource id from the request route
```php
$request->route('resourceId');
```

**Comment by nickels** [comment]
I'm using `$request->resourceId`

```
                Rule::unique('events')->where(function ($query) use ($request) {
                    return $query
                    ->where('id', '!=', $request->resourceId)
                    ->whereYear('event_date', $request->event_date)
                    ->whereSlug($request->slug);
                }),
````

**Comment by telkins** [comment]
Can we update the docs to let people know that `$request->resourceId` or `$request->route('resourceId')` are alternative ways to retrieve the current resource ID...?

I'm asking because the documentation was my first stop once I realized I needed a way to pass the resource ID into a validation object.  Since there was nothing there, I looked here next....luckily.  :-)

If needed, I can create a new issue.

**Comment by thuanok24-art** [comment]
iện tại không thể sử dụng {{resourceId}}các quy tắc xác thực trong lớp hoặc các quy tắc xác thực lớp tùy chỉnh.

File::make('file')->updateRules( new DataFile('{{resourceId}}')
vì {{resourceId}}only được thay thế trong các quy tắc chuỗi:

return collect($rules)->map(function ($rules) use ($replacements) {
            return collect($rules)->map(function ($rule) use ($replacements) {
                return is_string($rule)
                            ? str_replace(array_keys($replacements), array_values($replacements), $rule)
                            : $rule;
            })->all();
        })->all();
Để giải quyết vấn đề này, chúng ta có thể lấy ID tài nguyên từ tuyến yêu cầu

$request->route('resourceId');
