### ISSUE TITLE
Reset link authentication nova

### ISSUE THREAD

**Issue by siturra** [laravel/nova-issues#75]
It doesn't work reset password link  send form:

http://localhost:8000/nova/password/reset/7db9090762c17fe6f7804619625c9065d0f49de0a2cb0d1b96675ef4d1f0033b

**Comment by themsaid** [comment]
please share details, "doesn't work" isn't helping.

**Comment by siturra** [comment]
when resetting the password from the form on the route:

/nova/password/reset

send a link that arrives by email, to reset the password:

/nova/password/reset/{token}

this link doesn't work

**Comment by themsaid** [comment]
what local domain do you server your app on?

**Comment by siturra** [comment]
local

**Comment by themsaid** [comment]
make sure APP_URL in your env file is using the correct URL

**Comment by siturra** [comment]
try it in laravel framework from scratch by installing only nova.

**Comment by hassan-knopsmedia** [comment]
> when resetting the password from the form on the route:
> 
> /nova/password/reset
> 
> send a link that arrives by email, to reset the password:
> 
> /nova/password/reset/{token}
> 
> this link doesn't work

You have to put port number alongside your localhost inside your .env file

**Comment by siturra** [comment]
> > when resetting the password from the form on the route:
> > /nova/password/reset
> > send a link that arrives by email, to reset the password:
> > /nova/password/reset/{token}
> > this link doesn't work
> 
> You have to put port number alongside your (localhost:8000) inside your .env file

3 years later, please.

**Comment by hassan-knopsmedia** [comment]
> > > when resetting the password from the form on the route:
> > > /nova/password/reset
> > > send a link that arrives by email, to reset the password:
> > > /nova/password/reset/{token}
> > > this link doesn't work
> > 
> > 
> > You have to put port number alongside your (localhost:8000) inside your .env file
> 
> 3 years later, please.

My guy, I know that it is 3 years old issue but it still useful for others that stuck on this error.
