### ISSUE TITLE
HasOne - show details not searchable table?

### ISSUE THREAD

**Issue by dmason30** [laravel/nova-issues#751]
When using `HasOne::make` why show it as a searchable table rather than a details section/view/card since there is only ever going to be one result?

I would prefer if it just showed it in its own section entitled with the relation name with the details beneath. 

Is there a way to do this that I am not seeing?

**Comment by DivineOmega** [comment]
It would be great if there was a `->showAsForm()` option on the field, or something similar.

**Comment by yangfan-onion** [comment]
select data in a form within modal would be perfect

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by jakewtaylor** [comment]
Any solutions to this?
