### ISSUE TITLE
Groupable actions

### ISSUE THREAD

**Issue by alexbowers** [laravel/nova-issues#752]
The ability to add `$group = 'name';` onto Actions so that the Actions dropdown can be grouped under `optgroups`

**Comment by dillingham** [comment]
@alexbowers wouldn't that interfere with the optgroups that already exist in actions?

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by tylernathanreed** [comment]
@alexbowers @dillingham 

This could be done if we were to not use a `<select>` for the Action Selector component.

If you could structure it using a dropdown, then having action groups wouldn't be so far fetched.

Example:

![](https://uc5e088b361c9a599a917019133a.previews.dropboxusercontent.com/p/thumb/AAVAvbWpimmQbIu_2IOfAPveYmlzahk7ez4dCiBclYRyoNrwKxlxE-8ykZOyZd1sjUxqFUzNFJdzS1Wjhpsex4nvu3vvxuBx65zhHNX7PJTl3CeFA80PXecqEfxuGiPq005WJE8AoB6uWa1kZkatnswwX3kWJJCKpPql4_z2e331b4XlX4OYGL6SpXlqzfzk86EL-qRcK5-1oO2Sw05hg2XBvlkvVhnlnd9m3IvSm07edZFRtg5jDr6praXddwnvfLYpAb4QvQYVeFvADrHP5iMA/p.png?size_mode=5)
[Alternate Link](https://www.dropbox.com/s/o7mcofxwdcc931k/Top%20Level%20Action%20Gearbox.png?dl=0)

**Comment by LorenzoSapora** [comment]
Throwing a vote into this. Users particularly get a lot of actions/lenses, and being able to group them would be advantageous.

**Comment by DorZuberi** [comment]
Hi Guys,
Anything new on this?

This would be truly useful...

**Comment by crynobone** [comment]
We will respond if there some progress, otherwise just assume no news.

While this work in general, it still doesn't cover how to handle Action selectors on pages where `<optgroup>` are required to differentiate resource actions and pivot actions.
