### ISSUE TITLE
Image field cannot display SVG thumbnails

### ISSUE THREAD

**Issue by ibrunotome** [laravel/nova-issues#753]
Just uploaded a SVG and cannot see thumbnails on index listing or in details. If I convert it to a base64 image, the Nova show me a button to download the image, but still not displaying it. Is this a bug?

**Comment by alexvolik** [comment]
The same issue with SVG format. Also, in the DB it didn't save with a file format ('image' : 'hpQALZV7YaC03A155vjtGeodVYdGDjI7NlWKdFQ2.')

**Comment by dwyer14** [comment]
Yup, +1 for both of those comments. The `svg` file extension seems to be dropped when uploading to S3. Results in a "**This image** could not be found." on the resource detail view, which isn't actually correct—if you click the link, it will display the SVG code...it's just not considered an SVG without the extension.

**Comment by dwyer14** [comment]
Yup, +1 for both of those comments. The svg file extension seems to be dropped when uploading to S3. @davidhemphill Wondering if this is a bug with Nova, Laravel or Flysystem?

**Comment by ibrunotome** [comment]
When SVG is mandatory, I solved this way:

```php
Avatar::make('icon')
    ->disk('gcs')
    ->creationRules('required', 'mimes:svg', 'max:10240')
    ->thumbnail(function () {
        return $this->icon;
    })->store(function (Request $request) {
        $image = UploadDocument::handle($request->file('icon'), 'icons');

        return [
            'icon' => 'data:image/svg+xml;base64,' . base64_encode(file_get_contents($image)),
        ];
    }),
```

*Only works if SVG is mandatory.

**Comment by jBOKA** [comment]
This also happens when using Flysystem. This is either a Laravel or Nova bug.

**Comment by cendekia** [comment]
I did fix this issue by adding `getClientOriginalExtension`, like so:

```php
Avatar::make('Product Icon', 'icon')->disk('public')
   ->storeAs(function (Request $request) {
       return sha1($request->icon->getClientOriginalName()) . '.' . $request->icon->getClientOriginalExtension();
   })
```

Hope it will help

**Comment by jBOKA** [comment]
This is probably directly related to this issue in laravel and maybe to the underlying symfony component
https://github.com/laravel/framework/issues/26511

I think there should be a suggested workaround for this at least. Cluttering up this field definitions with another line (`storeAs`) seems heavy. File field definitions blow up so quickly.

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
