### ISSUE TITLE
[Question] Is Nova meant to evolve into a full CMS?

### ISSUE THREAD

**Issue by mattcdavis1** [laravel/nova-issues#754]
Is the intention for Nova to develop into a full CMS at some point or will certain features purposely be avoided to keep the focus on being an admin panel rather than a full-fledged CMS?  Is there somewhere where the intended future scope / limitations of Nova is provided to guide feature requests?

For example, static page management would be a nice feature that is typical for a CMS to handle but i'm not sure if this type of functionality would be considered out of scope for a product marketed as an Admin Panel.  Just not sure if the current Admin Panel feature set is meant to be the starting point for a more fully-featured CMS or if an Admin Panel is all Nova is ever intended to be.

**Comment by davidhemphill** [comment]
Nova is intended to be first and foremost to be an admin panel. There are lots of features which make it useful for building a CMS with it, but it's also missing a lot of built-in CMS features that would require it to be too opinionated with regards to implementation (per-model translations, static pages, repeater fields, etc).

**Comment by mattcdavis1** [comment]
@davidhemphill - so if i'm understanding you correctly your saying that Nova itself is not intended to be a full CMS at any point in the future but that other developer's may choose to use Nova as a base for creating a CMS.  Is that correct?

**Comment by davidhemphill** [comment]
Yep, exactly.
