### ISSUE TITLE
Lens will not allow you to select all matching records

### ISSUE THREAD

**Issue by michaelchunn** [laravel/nova-issues#755]
It would be nice if the lens index page would allow you to select all matching records.  I have an export action defined and on the lens page it's limited to the records on the current page.

<img width="280" alt="select-all" src="https://user-images.githubusercontent.com/432803/46312185-f5cf6000-c589-11e8-8314-dfb47d0f3f5f.png">

On the index page you have the option to select what's on the current page or all matching.

<img width="301" alt="screen shot 2018-10-01 at 2 49 41 pm" src="https://user-images.githubusercontent.com/432803/46312199-fcf66e00-c589-11e8-911f-b4c1eb7ce00d.png">

**Comment by dillingham** [comment]
This makes it impossible for users to download the reports that I imagined lenses to be useful for

**Comment by webhealer** [comment]
This is very important problem. For now,  when i use lenses, i can not run actions for all matching records. Only i can run over 25 records on the current page. Which makes impossible to generate some report data as @dillingham mentioned.

**Comment by dillingham** [comment]
![crying](https://user-images.githubusercontent.com/29180903/50720192-3e5d5480-1076-11e9-8490-0ca9afa00053.jpg)

**Comment by dillingham** [comment]
@davidhemphill is this planned?

**Comment by dillingham** [comment]
@davidhemphill / @taylorotwell is this planned?

**Comment by dkulyk** [comment]
`All matching records` exists in lens. But Taylor disable it.

**Comment by dillingham** [comment]
@dkulyk/ @davidhemphill /@taylorotwell

Honestly any workaround would be fine, even if it’s a temporary fix. Not having this really is causing problems for me. So if making a new query just for count is the way to go I’m ok with it if it means having the ability to download entire result sets. 

Or even not having a count for select all matching on this, that would be perfectly ok too.

**Comment by dillingham** [comment]
Not at all > No count: It's a **much** smaller pain

**Comment by beausif** [comment]
I ended up turning my lens into a resource and customizing the indexQuery in order to get `All matching records` for the result set I needed. This temporary workaround still has the issue of showing '0' for count.

I would prefer to keep this confined to a lens even with the count issue.

**Comment by davidhemphill** [comment]
Exploring how to fix this as part of some pagination work I'm doing. It looks like all the major plumbing is there, but the issue is like @dkulyk said, having grouping in the query will mess it up?

**Comment by dkulyk** [comment]
If you use Links for pagination you doesn't count all records. 
For extended pagination you need to known count of records. If you have grouping you query count in the group, not all records in query.

**Comment by dkulyk** [comment]
This has been fixed and will be included in the next release.

**Comment by fgilio** [comment]
This is not working for me, the checkboxes from the select dropdown don't do anything once checked. Will see if I manage to solve it before opening a new issue
