### ISSUE TITLE
Get current model id for filtering metrics?

### ISSUE THREAD

**Issue by XGhozt00** [laravel/nova-issues#757]
Is this possible? The only thing we found was this:

```
    public function calculate(Request $request)
    {
    	dump($request->segment(3));
    }
```

That seemed to get the ID of the model pulled from the URI of the nova-api call. Unfortunately I didn't see any other way to just get it from the $request.

We wanted to display metrics when viewing a single record on a model where the metrics are from that specific model. So we just need to filter by the current ID.

**Comment by brunogaspar** [comment]
Have you tried with `$request->resourceId`?

**Comment by XGhozt00** [comment]
No... that worked. Thanks @brunogaspar -- how did you know about that one?
Where should I have looked to find it?

**Comment by brunogaspar** [comment]
Laravel makes it a bit predictable for me now, but i also inspected the `$request` object.

I also try to always inspect the source code to find undocumented goodies :)

**Comment by XGhozt00** [comment]
Ah, heh. Thank you, I appreciate the response.
