### ISSUE TITLE
File field broken when named "Files"

### ISSUE THREAD

**Issue by mattivie14** [laravel/nova-issues#758]
So it looks like if you name a File type field "Files" (potentially because it's looking for a DB column "files"), it will break it. I kept getting this error:
`Call to undefined method Symfony\Component\HttpFoundation\FileBag::store()`
even when trying to save an item without touching the File field, just the field existing with that name seemed to break it.

Once I renamed the field / column (in my case to "Attachment / attachment") the field worked fine.

**Comment by dillingham** [comment]
I used “Upload” as the resource / model

And you can change the display name to files after
