### ISSUE TITLE
To show metrics value as a link, possible?

### ISSUE THREAD

**Issue by horaceho** [laravel/nova-issues#759]
![upcoming-events](https://user-images.githubusercontent.com/6657/46339438-68613e00-c665-11e8-8a8a-b19cbe51f43a.png)

Is it possible to show a metric value (e.g. 3 in the upcoming events metric) as a link, say, to jump to the defined ````uriKey()````?

**Comment by ibrunotome** [comment]
Really interested in this too.

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by jbrooksuk** [comment]
We don't have a public roadmap at the moment, however, we're always looking back over feature requests.

**Comment by rodrigoreyes79** [comment]
Right. And thank you for keeping a close eye on the community suggestions. Having said that, it would be great to know if a specific feature has been picked up or just dropped once it is marked as closed. Having that kind of information is useful because commenting on a closed issue may be pointless unless if the request has gathered the team's attention.

**Comment by jbrooksuk** [comment]
No worries. Usually we're open about feature requests that we won't be adding (at least immediately).

**Comment by CitizenBeta** [comment]
There's a package for this on nova packages but it's no longer supported. Many modern nova features aren't compatible with it. Official support for a link in the cards would be great.

**Comment by sedlatschek** [comment]
I'm also interested in such a feature.

Maybe something similar to the helptext feature, where a small button appears at the corner of the metric card:

![image](https://user-images.githubusercontent.com/58665536/121355091-d50d5a00-c92f-11eb-8182-4d3a2e9c7e9a.png)
