### ISSUE TITLE
Attaching BelongsToMany Relation: Trying to get property 'resourceClass' of non-object

### ISSUE THREAD

**Issue by arnordhaenens** [laravel/nova-issues#76]
Nova version: 1.0.5

The relation in database is as follows

- A rental offer can include many **RentalServices**.
- Visa versa of course, a **RentalService** can be used in many **RentalOffers**. 

Defining the relation in both Nova resources, using a **BelongsToMany** field, the correct **RentalServices** belonging to a specific **RentalOffer** are being displayed. 

Also, when viewing a specific **RentalService**, the correct **RentalOffers** in which the specific **RentalService** is being used are shown. 

However, on both, when trying to attach a new **RentalService** to a **RentalOffer**, an exception is thrown coming from `Laravel\Nova\Http\Controllers\AttachableController` on line 23. 

Error message states: `Trying to get property 'resourceClass' of non-object`.

Somebody else came accros this specific error?

Example of my Nova fields definition for my **RentalService** resource
```php
return [
    BelongsToMany::make('RentalOffers')
        ->fields(function () {
            return [
                Boolean::make('Service Included', 'is_service_included')
            ];
        })
];
```

**Comment by alexjose** [comment]
I am also getting same error `Trying to get property 'resourceClass' of non-object ` when I goto the attach User view.

My setup is like this
```php
class Server extends Model
{
    public function admins()
    {
        return $this->belongsToMany('App\Models\User');
    }
}

============================

class Server extends Resource
{
    public function fields(Request $request)
    {
        return [
            BelongsToMany::make('Users', 'admins'),
        ];
     }
}
```

**Comment by meyer59** [comment]
+1

**Comment by BengtHagemeister** [comment]
It seems like it has something todo with the Uri Key. When I change the api path from

nova.test/nova-api/**coupling-sizes**/23/attachable/material-properties?search=&current=3&first=true&withTrashed=false 

to 

nova.test/nova-api/**couplingsizes**/23/attachable/material-properties?search=&current=3&first=true&withTrashed=false 

it works.

**Comment by arnordhaenens** [comment]
As @BengtHagemeister pointed out, by altering a specific segment in the URL the correct results were returned.

After inspecting the code, I managed to resolve the issue (for my specific case) by overwriting the default static `uriKey` function on both of my resources. 

For my `RentalService` resource
```php
<?php

    /**
     * @return string
     */
    public static function uriKey() :string
    {
        return 'rentalServices';
    }

```

In my `RentalOffer` resource
```php
<?php

    /**
     * @return string
     */
    public static function uriKey(): string
    {
        return 'rentalOffers';
    }
```

In my resources, I also made sure I'm addressing the correct relation by defining the attribute (eg in RentalService resource)
```php
<?php

    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [
            // ...
            BelongsToMany::make('RentalOffer', 'rentalOffers')
                ->fields(function () {
                    return [
                        Boolean::make('Service Included', 'service_included')
                    ];
                })
        ];

```

In frontend, when accessing the site, be sure to do a 'hard refresh' and 'start from the beginning' to prevent any caching issues.

**Comment by meyer59** [comment]
I think it is something that should be fixed in nova even if you found a solution to make it work. 
We shouldn’t have to overwrite method to have the base relation to be resolved.

**Comment by mrmonat** [comment]
@arnordhaenens So you think in ```Laravel\Nova\Resource``` 

```
public static function uriKey()
{
    return Str::plural(Str::camel(class_basename(get_called_class()), '-'));
}
```
instead of

```
public static function uriKey()
{
    return Str::plural(Str::snake(class_basename(get_called_class()), '-'));
}
```

would be the solution? 

One side effect of changing this would be the urls of the resources (for example in the sidebar):

```
// Before "fix"
http://.../nova/resources/product-families
// After "fix"
http://.../nova/resources/productFamilies
```

**Comment by bradenkeith** [comment]
+1

I believe we should be able to specify the attribute, as it is named in the model, as the second variable in the field make function. But it seems to be looking at the URI once it get to `AttachableController`. 

I don't believe the intended purpose would be to change the URL in order for multi-word relationships to be attachable.

In my instance, I am using a BelongsToMany from a `Project` Resource:

```            
BelongsToMany::make('Email Addresses','emailAddresses', EmailAddress::class)
```

Its relationship is defined as:

```
    public function emailAddresses()
    {
    	return $this->belongsToMany('App\EmailAddress');
    }
```

The API Call that GETs is 
`/nova-api/projects/1/attachable/email-addresses?search=&withTrashed=false`

Which causes `AssociatableController` on line 20 `$request->field` to be defined as `email-addresses`. If it was to be defined as `emailAddresses`, all is well.

Additionally, changing the uriKey to `emailAddresses` resolves the error.

`viaRelationship` is a get variable in the browser that obeys the attribute defined in the field creation. I would think this is what should get passed to the API call on the Attach Vue Controller. However, I'm not comfortable enough to say this wouldn't have alternative repercussions.

**Comment by ok200paul** [comment]
I'm finding that when I refactor the belongsToMany eloquent relationship function down to a non-camel-cased function (say `emailAddresses` refactored to `emailaddresses` or something), the "attach" page begins finding the resourceClass. So this issue might be something to do with a camel casing interpretation function somewhere?

The folks who mention issues with two-word stuff in #148 might be on to something.

**Comment by kenneth-g-flux** [comment]
I think the `AttachableController` is looking at the wrong field when trying to find the `BelongsToMany`-field in the resource. It's looking at the `attribute`-field, which is actually the name of the relationship, while the url for the attachable contains the resource name. Changing line 20 in `AttachableController` from
```
->firstWhere('attribute', $request->field);
```
to
```
->firstWhere('resourceName', $request->field);
```
solves the issue when loading the relationship data.
When actually attaching a new resource (the POST-request), a similar change fixes the validation error. Change line 237 in `PerformsValidation` from
```
->firstWhere('attribute', $field)
```
to
```
->firstWhere('resourceName', $field)
```

Does that make sense to any of you? Will that break any other functionality?

**Comment by bradenkeith** [comment]
My initial reaction is that the attribute is whats in error here. The attribute, I believe, refers to the model and its attribute. The resource name should refer to the Nova resource. This is how I understand it.

If my thought is correct, then the attribute seems to be getting generated/manipulated incorrectly. Especially if we're defining it in the creation of the field, it probably should not be manipulated further. Or that the attribute is being assigned to the wrong property on the class.

**Comment by bradenkeith** [comment]
@kenneth-g-flux I see what you're saying now. `$request->field` comes through requesting the resource name, not the attribute, so that would satisfy the issue and still leave attributes where it needs to be. I'll test a little further, but I think you mention the fix here.

**Comment by bradenkeith** [comment]
This resolution has been accepted and merged. It’ll be resolved in a future release of Nova. Thanks everyone!

**Comment by meyer59** [comment]
Fixed in Nova v1.0.8

**Comment by meyer59** [comment]
The bug seems to be fixed but detaching the relationship model seems to be broken has anyone be able to test it ?

**Comment by mrmonat** [comment]
@meyer59 Works for me

**Comment by bradenkeith** [comment]
@meyer59 Affirmative, detaching works without issue for me. Feel free to open another issue with some code if we need to chase this down.

**Comment by zappzerapp** [comment]
https://github.com/laravel/nova-issues/issues/4162#issuecomment-1118408075
