### ISSUE TITLE
Can't fetch metadata in Resource Tool Vue component

### ISSUE THREAD

**Issue by lluisandreu** [laravel/nova-issues#761]
Hello, 

In a resource component I am trying to pass data from the ResourceTool class to the Vue components using methods (like in the example in the Docs). The problem is that I can't get the data in the component using the field variable. 

In the src/Chat.php file I define 

```
public function test() {
        return $this->withMeta(['test' => true]);
}

```
in resources/js/components/Tool.vue

```
<script>
    export default {
        props: ['resourceName', 'resourceId', 'field'],

        mounted() {
            console.log(this.field.test);
        },

        computed: {
        	test() {
        		return this.field.test;
        	}
        }
    }
</script>
```

where 'this.field.test' is undefined.

**Comment by davidhemphill** [comment]
Please post your full example code. Closing until you do that.

**Comment by thegregthomp** [comment]
I'm seeing this issue here, as I suspect a step is missing from the docs. When you define the method that passes the data via withMeta, I assume that method must be called somewhere. The documentation around tools is severely lacking. In the above example, should the `test` method be called somewhere?

**Comment by thinckx** [comment]
I'm experiencing the same issue in version 1.3.2. Exposing methods on the resource class does not work with a Resource Tool. 

What you can do, however, is pass the data  **where you register** your Resource Tool. That is: in the Chat resource in the `fields` method:

```
use Acme\Chat;

/**
 * Get the fields displayed by the resource.
 *
 * @param  \Illuminate\Http\Request  $request
 * @return array
 */
public function fields(Request $request)
{
    return [
        ID::make('ID', 'id')->sortable(),

        Chat::make()->withMeta(['test' => true]),
    ];
}

``` 

In `Tool.vue` you'll see that `this.field` now also contains the `test` property. 

May I suggest to update the docs accordingly?

**Comment by judahnator** [comment]
I am seeing this same issue as well. Cards work fine, but metadata within tools is broke. Using Nova v2.0.8.

Where I am registering the tool:
```php
$tool->withMeta(['foo' => 'bar']);
```

In the tool:
```javascript
mounted() {
    console.log(this.card, this.tool, this.fields);
    // undefined, undefined, undefined
}
```

**Comment by benedict-w** [comment]
I also have this issue with a `Tool` (as opposed to a `ResourceTool`, or `Card`. Have posted on SO https://stackoverflow.com/questions/60525291/laravel-nova-tool-send-metadata-to-vue

**Comment by sil2** [comment]
Why the ticket is closed? What is the solution for this? I have exactly same problem. I want to pass to my Tool.vue some data but prep is empty! please help.

**Comment by Livijn** [comment]
This issue should be reopened.

**Comment by mrcbk** [comment]
For me I can solve this when adding the following to the tools src folders file:

`public function jsonSerialize()
    {
        return array_merge([
            'component' => 'panel',
            'name' => $this->name,
            'showToolbar' => $this->showToolbar,
        ], $this->meta());
    }`

So for a tool tools/take-modal-repairs the following is my complete TakeModalRepairs.php:

`<?php

namespace Tools\TakeModalRepairs;

use Laravel\Nova\ResourceTool;

class TakeModalRepairs extends ResourceTool
{
    public function jsonSerialize()
    {
        return array_merge([
            'component' => 'panel',
            'name' => $this->name,
            'showToolbar' => $this->showToolbar,
        ], $this->meta());
    }
    /**
     * Get the displayable name of the resource tool.
     *
     * @return string
     */
    public function name()
    {
        return 'Take Modal Repairs';
    }

    /**
     * Get the component name for the resource tool.
     *
     * @return string
     */
    public function component()
    {
        return 'take-modal-repairs';
    }
}
`

**Comment by Paulsky** [comment]
Why is this issue closed?

**Comment by amidesfahani** [comment]
This issue should be reopened.

**Comment by RafaelEmery** [comment]
I'm having the same Issue! This issue should be reopened

**Comment by crynobone** [comment]
We don't reopen 2 year old issues. If you still have the issue please create a new issue with example on how to reproduce the issue as mentioned by @davidhemphill
