### ISSUE TITLE
Can't work with tables 'cards' and 'metrics'

### ISSUE THREAD

**Issue by visionp** [laravel/nova-issues#763]
When i create a resourсe for table with name "cards" frontend make query to route "/nova-api/cards" and receives an incorrect response, because this route for 'DashboardCardController@index'.

**Comment by bonzai** [comment]
You need to overwrite the `uriKey` method on your resource:

```php
/**
 * Get the URI key for the resource.
 *
 * @return string
 */
public static function uriKey()
{
    return 'kard';
}
```
