### ISSUE TITLE
Attach model Observer only when NOT serving from Nova

### ISSUE THREAD

**Issue by pylebecq** [laravel/nova-issues#764]
Hello,

This is more a question than an issue but maybe it deserves some code and documentation changes.

I have an application already using model observers to make sure that when some models are created, I also create other models and link many of these models to the currently connected user.

I am now trying to add Nova to this application. When I create one of these observed models from Nova, all the observers are triggered and they are creating many things related to me, the currently connected user. And I don't want that, because after, I have to go to many different screens to delete everything that was created.

So, in the [documentation](https://nova.laravel.com/docs/1.0/resources/#resource-events) I found that you can attach a model Observer when a request is from Nova.

But I would like to know if there is the opposite instead, to make my observer do nothing when the request is from Nova.

Is there an easy way to do this, or an easy way to know it ? Basically I would need a way to access `ServeNova::isNoRequest()` publicly I think. Or if you know any other way, please tell me, and maybe add it to the documentation.

Thanks

**Comment by dillingham** [comment]
@pylebecq Illuminate\Database\Eloquent\Concerns\HasEvents

You can remove observers if Nova::serving

**Comment by pylebecq** [comment]
@dillingham That's an interesting idea. Do you know how can I enforce the service provider that removes observers to be executed after the one adding the observers in the first place ?

Even with this solution, I don't think it's the best way to handle this use case. I don't like to add something and removing it and adding something else instead. It does not feel right. It would be better to add specific stuff on specific conditions I think.

**Comment by tomscholz** [comment]
@pylebecq Did you ever find a solution?

**Comment by pylebecq** [comment]
@tomscholz Sorry for the very late reply. I did not find any solution, and we moved on to other things, it was not such a big issue for the project we were working on.
