### ISSUE TITLE
Default theme requires ridiculously wide browser window

### ISSUE THREAD

**Issue by hackel** [laravel/nova-issues#765]
It seems that the default Nova theme requires a 1280px wide viewport in order to avoid horizontal scrolling.  #50 deals with a "mobile" responsive layout, but this is a huge usability issue **on desktop**, so I consider this a bug, and it needs to be addressed.

Editing a simple form is terribly cumbersome.  There is plenty of unused whitespace in the design, so I can't imagine why it was made this way.  I know many people have fancy HiDPI displays these days, but I'm stuck at 1920 and so typically have a browser window at ~1000px wide.  I'm sure I'm not alone in this, and I bet there are many end-users still dealing with old 1366x768 screens who would have to constantly maximize their browser window just to be able to use this efficiently.

**Comment by dillingham** [comment]
@hackel try `ctrl | cmd + -` (dash symbol) to zoom out. Solves for the interim

**Comment by laraning** [comment]
Two packages that might help you:

https://novapackages.com/packages/gregoriohc/laravel-nova-theme-responsive
https://novapackages.com/packages/ebess/nova-collapsible-sidebar

**Comment by davidhemphill** [comment]
1280px is the same width as the Macbook Pro 13" at default resolution. Not planning on supporting smaller than that unless we introduce a responsive design.

**Comment by hackel** [comment]
@dillingham Right, because users don't need to be able to actually read any of the text or anything...

@laraning Thanks, I'm aware of these, but this is such a serious bug that it needs to be addressed immediately by the developers.  They shouldn't be relying on 3rd party developers to deliver BASIC usability in their product.

@davidhemphill That is only the case if some insane person runs with a *maximized* browser window.  Who in their right mind would do that?  1280 is considered "extra large" by Bootstrap—that should clue you in that what you are doing is wrong.  I understand not supporting mobile devices right away, that's fine.  But not supporting entry-level PCs without fancy displays is absolutely ridiculous.  Medium / 768px is the standard at which your UI should be functional.

You need to change your decision on this.  This isn't some open source project that you are designing for yourself.  You have real-world customers depending on this.  It kind-of blows my mind that you wouldn't follow one of the basic mantras of web design, "mobile first".

**Comment by dillingham** [comment]
@hackel you have a Napoleon complex, but with a tiny computer screen 😆

**Comment by dillingham** [comment]
> That is only the case if some insane person runs with a maximized browser window.

What person with a small screen has windows not maximized? 💩

**Comment by dillingham** [comment]
@hackel your "desktop standard 768px" claim doesn't hold up against these resolution stats

http://gs.statcounter.com/screen-resolution-stats/desktop/worldwide

**Comment by davidhemphill** [comment]
I appreciate your input and expert opinion, but a mobile admin isn't our first priority.

**Comment by hackel** [comment]
@davidhemphill I specifically said I did NOT care about a "mobile admin," which I agree should not be a first priority.  Please do learn to actually read your customers' comments before dismissing them.  Again, this is just basic usability here, on a standard desktop web browser.

If your target audience is only people with Macbook Pros, you should specify that on your product information page so people are aware of the limitations prior to purchasing.

**Comment by davidhemphill** [comment]
Really tired of your condescending tone. Locking this thread as we've already stated our case. Please feel free to request a refund if Nova doesn't meet your needs.
