### ISSUE TITLE
Lens option to remove resource id from query

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#766]
### Background
Lenses automatically include the resource id column in the query
But in some cases excluding the id and making a more general query would be desired.
I made a lens for OrdersByQuarter but because Quarter isn't a resource, there is no ID.

The lens display works when displaying in the nova interface

```php
return $request->withOrdering($request->withFilters(
    $query
        ->selectRaw("QUARTER(orders.created_at) as `quarter`")
        ->selectRaw("COUNT(orders.id) as orders")
        ->groupBy('quarter')
));
```

### Problem
If I download via the nova excel package, I get a [column not included in aggregate error](https://github.com/Maatwebsite/Laravel-Nova-Excel/issues/25)
That column is the `resource table name . id` ie `orders.id`, Which I don't need in the above group by. Also because this query is expected to run against the orders table, it works in nova, but would break obviously if included on a different resource. Additionally needed to css hide the row view | edit | delete

### Solution
Solved by enabling the additions of 
- $hasResourceId = false`. 
- $showsRowActions = false
Bonus
- $table = 'orders'

### Benefits
This would allow lenses to be placed anywhere and with any query. 
If a client expects to see a orders by quarter report on orders page, you could just include the table property, hide the row actions, remove resourceIds and be able to export aggregated etc

**Comment by dillingham** [comment]
Not directly related, but if you're already focused on lenses 👼 https://github.com/laravel/nova-issues/issues/726

**Comment by ppisecky** [comment]
> Also because this query is expected to run against the orders table, it works in nova, but would break obviously if included on a different resource.

Maybe you could abstract the lens away from orders by retrieving the model from the `$query` object?

```php
$table = $query->getModel()->getTable();
return $request->withOrdering($request->withFilters(
    $query
        ->selectRaw("QUARTER(".$table.".created_at) as `quarter`")
        ->selectRaw("COUNT(".$table.".id) as resource_count")
        ->groupBy('quarter')
));
```
