### ISSUE TITLE
Sorry, the page you are looking for could not be found.

### ISSUE THREAD

**Issue by haneef5k** [laravel/nova-issues#768]
After installing successfully., i'm trying to navigate laravelapp.test/nova i got this message "Sorry, the page you are looking for could not be found."

laravel v5.6

**Comment by dillingham** [comment]
@haneef5k follow the installation guide closely. 
https://nova.laravel.com/docs/1.0/installation.html

**Comment by haneef5k** [comment]
@dillingham i followed all the steps in the guide till , `php artisan migrate` i didn't get any issue.

**Comment by dillingham** [comment]
@haneef5k closely means all the steps, not just till migrate. Please read entirely 
https://nova.laravel.com/docs/1.0/installation.html#authorizing-nova

**Comment by haneef5k** [comment]
Issue fixed by running those cmds

```
cd your_project_full_path
sudo chmod -R 0775 storage
sudo chown -R www-data:www-data storage
php artisan config:clear
php artisan view:clear
php artisan route:clear
composer dump-autoload
```

And also because of some space in my .env file.
