### ISSUE TITLE
s3 file download error

### ISSUE THREAD

**Issue by noahlocke** [laravel/nova-issues#769]
I can successfully upload files to s3 using the standard Nova File field:

```php
   public function fields(Request $request)
    {   
        return [
            BelongsTo::make('Consumer','client', \App\Nova\MyConsumers::class),
            File::make('Attachment')->store(new StoreConsumerAttachment),   
            Text::make('Filename')->exceptOnForms(),
            Text::make('File Size', 'size')
                ->exceptOnForms()
                ->displayUsing(function ($value) {
                    return number_format($value / 1024, 2).'kb';
            }),

        ];
    }
```
StoreConsumerAttachment.php:
```php
    public function __invoke(Request $request, $model)
    {
        $path = 'client-attachments'.'/'.$request->viaResourceId;
        return [
            'attachment' => $request->attachment->store($path, 's3'),
            'filename' => $request->attachment->getClientOriginalName(),
            'size' => $request->attachment->getSize(),
        ];
    }
```
yet when I try to download the file from the detail view of my resource, I get a "Failed - Server Problem"

I should note that I can upload/download when using `store($path, 'public')` without problem. 

Also, I don't believe this is an issue with s3 permissions. My aws creds have full s3 access, and I can verify from the command line using the same creds. I can also `put` and `get` files using `php artisan tinker` without any problem. 

Lastly, this is happening in all environments. Local, running on valet; dev, running on Forge.

Anyone else having this issue with Nova/s3 downloads?

**Comment by noahlocke** [comment]
Closing this, I was able to get it working through a different approach... still not sure why the above code works but I can't say for sure it's a Nova bug.

**Comment by noahlocke** [comment]
@erikleon 

In my `Consumer.php` resource class:

```php
 public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
            Text::make('First Name')->sortable()->rules('required', 'string', 'max:35'),
            Text::make('Last Name')->sortable()->rules('required', 'string', 'max:35'),
            HasMany::make('Attachments', 'attachments', \App\Nova\ConsumerAttachments::class),
        ];
    }
```

then, I have my `ConsumerAttachements.php` class:

```php
    public function fields(Request $request)
    {
        return [
            BelongsTo::make('Consumer', 'client', \App\Nova\Client::class),
            File::make('Attachment')
                ->disk('s3')
                ->storeOriginalName('filename')
                ->storeSize('size')
                ->prunable(),

            Text::make('Attachment Name', 'filename')->exceptOnForms(),

            Text::make('Attachment Size', 'size')
                ->onlyOnDetail()
                ->displayUsing(function ($value) {
                    return number_format($value / 1024, 2) . 'kb';
                }),
        ];
    }
```

Biggest difference is that I'm no longer using an invokable class, just plain-jane inline nova field syntax. 

I think there was an issue with the filename in my previous implementation, but this works great and does what I need it to so I didn't spend any time looking into it. Hope this helps!

**Comment by ginlove0** [comment]
@noahlocke 
Hi. Do you know how to preview this file without download?

**Comment by gustav1105** [comment]
Please re-open this thread, I am having difficulty with getting the images,videos,audio downloaded from S3. I can upload no problem, cannot donwload.

NovaDependencyContainer::make([
                File::make('Video')
                    ->disk('s3')
                    ->storeAs(function ($request) {
                        return Str::random(40) . "." . $request->video->getClientOriginalExtension();
                    })
                    ->prunable()
            ])->dependsOn('media_type', KnowledgeCardType::VIDEO),

**Comment by gustav1105** [comment]
I found it is due to the dependencyContainer. plugin... 

thanks anyway
