### ISSUE TITLE
Bug: Logout link broken when nova path is "/"

### ISSUE THREAD

**Issue by anderly** [laravel/nova-issues#770]
Logout link ends up being: https://logout/

**Comment by dillingham** [comment]
Just tested with current version and not able to reproduce

**Comment by anderly** [comment]
Hmmm. I'm running 1.1.4 as well.

**Comment by anderly** [comment]
Ah, found it. Had to replace `{{ Laravel\Nova\Nova::path() }}/logout` in the published `/resources/views/vendor/nova/partials/user.blade.php` with `{{ route('nova.logout') }}`.
