### ISSUE TITLE
Created entities does not respect connection

### ISSUE THREAD

**Issue by nsbucky** [laravel/nova-issues#772]
I have a model called affiliates and it is not on the default connection. When I try to create a new affiliate it complains the table doesnt exist. It seems that even though the model App/Models/Affiliates specifies connection, when the system tries to create a new one, it doesn't reference this connection.

**Comment by te1** [comment]
I have the same problem.

@nsbucky Did you find a solution for this?

**Comment by nsbucky** [comment]
Yes I uninstalled. For now, will just wait a couple more versions and see if it gets fixed.
