### ISSUE TITLE
BelongsTo field does not show custom name on forms

### ISSUE THREAD

**Issue by rickmacgillis** [laravel/nova-issues#773]
As mentioned in issue #526, the BelongsTo field only shows its custom label on the details and index screens, but not on the forms.

**Comment by TheOneDaveYoung** [comment]
@davidhemphill Is there another issue where this was addressed? I'm wondering why it was closed as, at least for me, I am still having this issue in v2.9.2.

```
BelongsTo::make('Member', 'user', 'App\Nova\User')->nullable(),
```
Produces this on the "list" view:
![image](https://user-images.githubusercontent.com/33292917/70855294-820f2f80-1e7d-11ea-8b88-ba963abef344.png)

And this in the "detail" view:
![image](https://user-images.githubusercontent.com/33292917/70855366-7f610a00-1e7e-11ea-898f-7f5303352d74.png)

But produces this on the "form" view:
![image](https://user-images.githubusercontent.com/33292917/70855341-27c29e80-1e7e-11ea-93e1-3042062c02eb.png)

**Comment by Wiejeben** [comment]
@TheOneDaveYoung I'm experiencing exactly the same, it must be a bug that has returned? (I'm new to Nova so perhaps it was never solved...?)

**Comment by GingerNinjaNicko** [comment]
I'm also encountering this issue. 
Why is this closed?

**Comment by GingerNinjaNicko** [comment]
@jbrooksuk Could you please explain?

**Comment by davidhemphill** [comment]
Duplicate of #526

**Comment by TheOneDaveYoung** [comment]
@davidhemphill thanks for your response, but...  #526 is closed as well, and since the issue I'm describing here is still alive in the v2.9 release, shouldn't that be opened back up? Or should a new issue be opened? Just want to make sure it gets documented in the right spot otherwise we'll keep banging away on these issues lingering issues.

**Comment by jbrooksuk** [comment]
I've already made a PR to address this issue, https://github.com/laravel/nova/pull/764

You need to connect your account to GitHub at https://nova.laravel.com/settings#github to see it.

**Comment by TheOneDaveYoung** [comment]
@jbrooksuk Thanks James!!! You rock!
