### ISSUE TITLE
[Bug] Metric Builder Queries Being Combined

### ISSUE THREAD

**Issue by ryantbrown** [laravel/nova-issues#775]
Version 1.1.4

I have three value metrics that all use the same Model, `NewShopifyCompanies`, `NewWooCommerceCompanies` and `NewMagentoCompanies`. The `calculate` method for each is as follows:

```php
    $type = 'Shopify"
    return $this->count($request, Company::whereJsonContains('technologies', $type));
``` 

When I add these metrics to the dashboard, they all show the same number. They all show 187, which is the total combined for all three metrics. When I only use one, it shows the correct number, but as soon as I add another one, both values become the total.

I have tried using `where` inline as well as query scopes, but both produce the same result.

Steps to reproduce:

- Create two new value metric classes
- Use the same model for both classes but filter them separately
- Add both metrics to the Dashboard

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
