### ISSUE TITLE
Empty Action initiated by and target names in model details tab

### ISSUE THREAD

**Issue by pr-baernholdt** [laravel/nova-issues#776]
I am working on a code base that has not followed laravel naming conventions, so I have different column names on my User model which I cannot change. For instance instead of having `name` column I have `user_first_name`, so Nova is unable to show the right name of the user in actions section of models.

This is the preview of my details tab for a sample model:
![image](https://user-images.githubusercontent.com/43473299/46408147-710f4e00-c711-11e8-8f13-974f3d1b96df.png)

This seems to be related to this hardcoded field in the `ActionResource`
![image](https://user-images.githubusercontent.com/43473299/46408226-b3d12600-c711-11e8-9119-6a4ff369824d.png)

Also primary key and the column representing my ID is `user_id` instead of `id`, so I've had to use this temporary solution to overcome the issue of having a column name other than `id` as primary key:
![image](https://user-images.githubusercontent.com/43473299/46408374-4245a780-c712-11e8-89e0-353ac904ef3a.png)

**Comment by pr-baernholdt** [comment]
I could find a solution for the `Action initiated by` name by adding a name attribute

![image](https://user-images.githubusercontent.com/43473299/46408877-e5e38780-c713-11e8-933f-81a59d5f60f8.png)

But the `Action target` is still empty, because it is unable to use custom keys in related models.

![image](https://user-images.githubusercontent.com/43473299/46408863-d6643e80-c713-11e8-99d5-7fba9eece638.png)

![image](https://user-images.githubusercontent.com/43473299/46408913-03185600-c714-11e8-929f-df00fcf2f56a.png)

**Comment by emtudo** [comment]
I also had the problem with the field "name", I solved creating an attribute, as for the fields, you instead of using trait "Actionable" create a method called "actions"

``` 
     public function actions ()
     {
         return $ this-> morphMany (ActionEvent :: class, 'actionable');
     }
``` 

And customize your fields here.

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
