### ISSUE TITLE
Ability to have index only actions

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#778]
There are actions that will only need to be run on a list of resources.
For example, currently looking to prevent downloading an excel file of a single resource.

```php
/**
 * Indicates if this action is only available on the resource index view.
 *
 * @var bool
 */
public $onlyOnIndex = true;
```

I partly feel this should be the default & explicit showOnDetail should be set

**Comment by davidhemphill** [comment]
Gonna leave the action visibility set up the way it is, but added `onlyOnIndex` method and it should be in the next release. 👍
