### ISSUE TITLE
Filtering on many-to-many relationship

### ISSUE THREAD

**Issue by RicLeP** [laravel/nova-issues#779]
Is there a clever way to filter on many-to-many (or any other kind) of relationships? For instance Users can have many Firms. I’d like to be able to filter Users by Firm. It would be great to be able to pass the relationship as a filter.

**Comment by dstiller** [comment]
Take a look at the Filtering Examples from https://nova.laravel.com/docs/1.0/resources/authorization.html#index-filtering
