### ISSUE TITLE
[Feature + Patch] Multiple custom dashboards

### ISSUE THREAD

**Issue by alexbowers** [laravel/nova-issues#78]
There is a dependency on https://github.com/laravel/nova-js/pull/3 getting merged for this to work.

This patch allows for multiple dashboards to be created by the developer. Each dashboard can have its own independent cards.

The `main` dashboard remains as it was, however additional dashboards can be created using `php artisan nova:dashboard DashboardName`

The dashboards are stored in the `app/Nova/Dashboards` directory.

This is how it looks when setup in the system:

It supports all of the features of the standard Dashboard in Nova.

![2018-08-23 21 08 53](https://user-images.githubusercontent.com/842974/44549387-d0dd0700-a718-11e8-9c5a-9a1ac275c360.gif)

An example dashboard may have code like this:

```php
<?php

namespace App\Nova\Dashboards;

use App\Nova\Metrics\CurrentCustomers;
use Laravel\Nova\Dashboard;

class Retention extends Dashboard
{
    public $label = 'Customer Retention';

    public function cards()
    {
        return [
            new CurrentCustomers,
        ];
    }

    /**
     * Get the URI key for the metric.
     *
     * @return string
     */
    public function uriKey()
    {
        return 'customer-retention';
    }
}

```

and the `NovaServiceProvider.php` would have a `dashboards` function in it

```php
...
protected function dashboards()
{
    return [
        new Server,
        new Retention
    ];
}
...
```

[0001-Support-for-multiple-dashboards.txt](https://github.com/laravel/nova-issues/files/2316124/0001-Support-for-multiple-dashboards.txt)

**Comment by viezel** [comment]
Great and powerful idea. 👍🏻

**Comment by alexbowers** [comment]
@davidhemphill Any chance I can get some feedback on this? It will be very useful for how we want to use Nova

**Comment by alexbowers** [comment]
I am very close to having a working package built to do this, so there is no urgent need for it to be integrated into Core.

What I would say is that I have had to use some remarkable hacks to get it to work properly, so a core version would be nice in the future.

For anyone interested, the work in progress is held at https://github.com/alexbowers/nova-multiple-dashboard and should be being released tomorrow, all being well.

**Comment by alexbowers** [comment]
This has now been released as https://novapackages.com/packages/alexbowers/nova-multiple-dashboard

Feel free to implement in Core if you wish, but for now i'll close the issue.
