### ISSUE TITLE
Class not found for HasMany field when a space is used

### ISSUE THREAD

**Issue by XGhozt00** [laravel/nova-issues#780]
We have this field in here:

`HasMany::make('ApplicationActivity', 'activity')->onlyOnDetail()`

And I get this error: `Class 'App\Nova\Application Activity' not found`

If the code is like this:

`HasMany::make('Application Activity', 'activity')->onlyOnDetail()`

It seems not having the space in there works fine and still adds back the space when showing the title when viewing the resource. What's weird though, is that this error doesn't always occur on every system and we're not sure what the difference is and what causes it.

**Comment by davidhemphill** [comment]
Pass the resource class in as the third parameter.

**Comment by XGhozt00** [comment]
@davidhemphill -- I should have mentioned, I know we can do that and that is what we ultimately did to solve it. We were more concerned about it working on one machine and not another and the docs say the class isn't required for it to work. It just seemed like maybe there was a bug there?
