### ISSUE TITLE
ResourceTool: No ToolOptions

### ISSUE THREAD

**Issue by getit-kk** [laravel/nova-issues#784]
Hello,

i've created a component called 'DnsEntry'
`php artisan nova:resource-tool kk/dns-entry`

and then I wanted to submit sth. from the DnsEntry-Class to the Tool.vue as described in 'Tool Options'.
So I added 
```php
/**
 * Indicates that the Stripe inspector should allow refunds.
 *
 * @return $this
*/
public function issuesRefunds() {
    return $this->withMeta(['issuesRefunds' => true]);
}
```

But in Tool.vue within the mounted() function 'this.file' only contains:
{component: "dns-entry", prefixComponent: false, onlyOnDetail: true, panel: "DNS Eintrag"}

Tried with nova 1.1.14 (and all versions <= 1.0.19)

**Comment by davidhemphill** [comment]
I can't makes sense of what your problem is. Please rephrase and provide more description of what you're expecting and what is actually happening?
