### ISSUE TITLE
Chrome error when clicking the filter icon dropdown

### ISSUE THREAD

**Issue by tanthammar** [laravel/nova-issues#785]
When I click on the "filter icon/dropdown" I get the following error in Chrome:

[Deprecation] Using unescaped '#' characters in a data URI body is deprecated and will be removed in M71, around December 2018. Please use '%23' instead. See https://www.chromestatus.com/features/5656049583390720 for more details.

<img width="435" alt="image 2018-10-04 at 12 33 05 pm" src="https://user-images.githubusercontent.com/21239634/46468865-f78b6480-c7d1-11e8-950c-f0b01bbdcbd4.png">

**Comment by davidhemphill** [comment]
This was fixed several versions ago.
