### ISSUE TITLE
One to one relation creation form

### ISSUE THREAD

**Issue by devmsh** [laravel/nova-issues#79]
Is there any possibility to create both model and it's one-to-one relation using the current form fields?

for example, I decoupled the `Match` date and league information, from the `MatchTeam` witch include the teams that play in this match.

I need to create a one shot `Match` creation form, I tried the current fields without success.

**Comment by rcknr** [comment]
Have you tried adding another model using `with` and adding fields using point separator?

**Comment by devmsh** [comment]
Tried with no success!

**Comment by mick340** [comment]
Did you find a solution for this? Currently I’m having the same issue.

**Comment by SamerDiab** [comment]
Check this
https://novapackages.com/packages/shivanshrajpoot/nova-create-or-add
and
https://novapackages.com/packages/yassi/nova-nested-form

@mick340

**Comment by brideo** [comment]
HasOne didn't work for me so I did this, not the prettiest solution but 🤷 

```
Select::make('site_sale_id')->options(
    SiteSaleEntity::query()->get()->mapWithKeys(function ($item, $key) {
        return [$item['id'] => $item['title']];
    })
)
```
