### ISSUE TITLE
[Bug, Patch] Custom ownerKey in the BelongsTo relation.

### ISSUE THREAD

**Issue by dkulyk** [laravel/nova-issues#794]
Laravel: 5.7
Nova: 1.1.4
PHP: 7.2.10

BelongsTo associable always returns the PK value instead the OwnerKey filed's value. [...](https://gist.github.com/dkulyk/c7778362d0509e0e0583731c9ef92396#file-belongsto_custom_ownerkey-patch-L76-L83)

The relatable validation used the PK instead key defined in the relation. [...](https://gist.github.com/dkulyk/c7778362d0509e0e0583731c9ef92396#file-belongsto_custom_ownerkey-patch-L53-L58)

I propose to use keys from the relation:
https://gist.github.com/dkulyk/c7778362d0509e0e0583731c9ef92396

Trait ResolveRelation will need to use in other relationship fields.

**Comment by davidhemphill** [comment]
I would be more likely to take a deeper look at these patches if you included unit tests.

**Comment by dkulyk** [comment]
I will try to write tests.

**Comment by alexbowers** [comment]
@dkulyk Did you manage to get anywhere with the tests?

**Comment by dkulyk** [comment]
> @dkulyk Did you manage to get anywhere with the tests?

Unfortunately I have not had time to do that.

**Comment by fede91it** [comment]
This patch is necessary. Why isn't merged yet?

**Comment by dkulyk** [comment]
Another issues are more important. I planned to fix it.

**Comment by fede91it** [comment]
Thank you man
