### ISSUE TITLE
🐛403 redirection after resource update if view authorization returns false

### ISSUE THREAD

**Issue by MarceauKa** [laravel/nova-issues#797]
- Laravel Version: 5.7.8
- Nova Version: 1.1.4
- PHP Version: 7.2.8

### Description:

I have a model that is always unauthorized for view (I don't want the detail page to be displayed neither the view button on index). But after a form update we're redirected to the detail page that returns a 403 error.

**Comment by jkudish** [comment]
Related to https://github.com/laravel/nova-issues/issues/604

Did you ever find a workaround? I'm encountering the same issue

**Comment by dillingham** [comment]
This isnt a bug, you specifically said you wanted to not authorize that route

If you want to redirect the route instead of a 403, just do so 

```php
Route::get('nova/resources/users/{id}', function () {
    return redirect('/nova/resources/users');
});
```

**Comment by dillingham** [comment]
Related https://github.com/laravel/nova-issues/issues/538 https://github.com/laravel/nova-issues/issues/604 https://github.com/laravel/nova-issues/issues/797 https://github.com/laravel/nova-issues/issues/862

**Comment by davidhemphill** [comment]
You can now override `redirectAfterCreate` and `redirectAfterUpdate` on your `Resource` class to customize where you're redirected after those actions.

**Comment by MarceauKa** [comment]
It seems this feature is not documented (like the BadgeField)

**Comment by skoyah** [comment]
It also seems that a lot of people are experiencing the same problem on not getting redirected to the intended path. 

@davidhemphill could you share a little help on why is that the case?

**Comment by emad-sure** [comment]
@davidhemphill  

> You can now override `redirectAfterCreate` and `redirectAfterUpdate` on your `Resource` class to customize where you're redirected after those actions.

it's doesn't fire , see the following  : 

![2019-09-30_14-08](https://user-images.githubusercontent.com/53175321/65877405-e3018e00-e38b-11e9-9248-65d325e7ffc8.png)
