### ISSUE TITLE
Ability to view `hasOne` related fields, but not update them

### ISSUE THREAD

**Issue by DivineOmega** [laravel/nova-issues#799]
- Laravel Version: 5.6
- Nova Version: 1.1.4
- PHP Version: 7.1

### Description:

In a Nova Resource you can display a HasOne related model's fields using dot notation, but attempt to edit these fields has no effect. 

For example, in a `User` Nova resource, you can define `Text::make('hrDetails.address_line_one);` in the `fields` method. This field displays correctly on the index, view, and edit pages for the `User` resource. However, when saving changes from the edit page, the changes to the related fields are not saved.

I believe this is caused by the code that updates the model, only fills fields for the specific model and not any related models.

### Steps To Reproduce:

1. Create two models with a HasOne relationship between then.
2. Create a new field that references the related model field using dot notation, as described above.
3. Observer the ability to view, but not save changes the contents of these fields.

**Comment by Frozire** [comment]
Anyone who has looked into a, hopefully temporary, workaround for this? Perhaps solvable using the fillUsing on the field?

**Comment by MaximeWillinger** [comment]
I went through this and found two workarounds, depending on what you are trying to achieve.

Saying that you have the following `User` model that has one `Profile` model containing a `phone` attribute.

```php
class User extends Model
{
    public function profile()
    {
        return $this->hasOne('App\Profile');
    }
}
```


### Method 1: using `fillUsing`
With the dot notation, Nova can successfully retrieve the related attribute value but will ignore it if you try to save. You can override this behaviour using `fillUsing` on your field.

```php
Text::make('Phone, 'profile.phone')->fillUsing(function ($request, $model){
   $model->profile->phone = $request->profile_phone;
   $model->profile->save();
}),
```

Note that the field sent by the form has a snake_case name: `profile_phone` (instead of `profile.phone`).


### Method 2: using accessors and mutators ([documentation](https://laravel.com/docs/5.7/eloquent-mutators#accessors-and-mutators))
I'm using this method for `File` and `Image` fields since the previous one doesn't work for these cases.
If you want to have a profile's picture field, first you need to create an accessor and a mutator in the `User` object, like this:

```php
public function getProfilePictureAttribute()
{
   // Don't forget to check the relation here if you don't want any error on Nova.
   return $this->profile ? $this->profile->picture : null;
}

public function setProfilePictureAttribute($value)
{
   $profile = $this->profile;
   $profile->fill(['picture' => $value]);
   $profile->save();
}
```

And then, you can declare the Nova field as you always do:

```php
Image::make('Profile picture')
```

Hope this helps!

**Comment by DivineOmega** [comment]
@MaximeWillinger These are great work arounds. Hopefully similar functionality makes it into Nova.

**Comment by renege** [comment]
@taylorotwell, is it even on the roadmap?

**Comment by dkulyk** [comment]
1) You should use right names of attributes:
```php
Text::make('Phone, 'profile.phone')->fillUsing(function ($request, $model, $attribute, $requestAttribute) {
    [$relation, $attribute] = explode('.', $attribute);
    $model->getRelationValue($relation}->setAttribute($attribute, $model->post($requestAttribute));
})
```
2) You need create relation if it not exists and save it after saving main model.
```php
protected static function fillFields(NovaRequest $request, $model, $fields)
{
    //Make new model if not exists.
    $profile = $model->profle()->firstOrNew([]); 
    $model->setRelation('profile', $profile);

    return array_merge(parent::fillFields($request, $model, $fields), [function () use ($profile, $model) {
        $model->profile()->save($profile);
    }]);
}
```

It is probably worked code, but i don't sure :)

**Comment by davidhemphill** [comment]
Nova's not designed to edit relationship data inside the same forms as its parent resource. The workarounds above are your best option. We may do inline relations some day, but it's not on the radar soon.

**Comment by desaintflorent** [comment]
Previous solutions are not working for me, and especially if you didn't set the relationship before. What I 'm doing as temporary workaround is :

```php
protected static function fillFields(NovaRequest $request, $model, $fields)
{
	$arr = ['profile_phone', 'profile_age'];

	// Get all of our profile details data
	$profileDetails = collect($request->only($arr))
               ->flatMap(function ($item, $key) {
			return [Str::replaceFirst('profile_', '', $key) => $item];
		})->toArray();

	// Then remove them from the main request
	$request->except($arr);

	$result = parent::fillFields($request, $model, $fields);

	$result[1][] = function () use ($profileDetails, $model) {
		// Update or delete depending of a null main value or null on all values.
		if ($profileDetails['phone'] && $profileDetails['age']) {
			$model->profile()->updateOrCreate([], $profileDetails);
		} else {
			$model->profile()->delete();
		}
	};

	return $result;
}
```

And then you don't need to hack your fields, you just do :

```php
Text::make('Phone', 'profile.phone'),
Text::make('Age', 'profile.age'),
```

Clean way to have HasOne relationship on multiple fields and remove te relation when one or all fields are null.

**Comment by edgarnadal** [comment]
> Nova's not designed to edit relationship data inside the same forms as its parent resource. The workarounds above are your best option. We may do inline relations some day, but it's not on the radar soon.

Maybe this can be in the docs @davidhemphill, thanks!

**Comment by ale1981** [comment]
> Previous solutions are not working for me, and especially if you didn't set the relationship before. What I 'm doing as temporary workaround is :
> 
> ```
> protected static function fillFields(NovaRequest $request, $model, $fields)
> {
> 	$arr = ['profile_phone', 'profile_age'];
> 
> 	// Get all of our profile details data
> 	$profileDetails = collect($request->only($arr))
>                ->flatMap(function ($item, $key) {
> 			return [Str::replaceFirst('profile_', '', $key) => $item];
> 		})->toArray();
> 
> 	// Then remove them from the main request
> 	$request->except($arr);
> 
> 	$result = parent::fillFields($request, $model, $fields);
> 
> 	$result[1][] = function () use ($profileDetails, $model) {
> 		// Update or delete depending of a null main value or null on all values.
> 		if ($profileDetails['phone'] && $profileDetails['age']) {
> 			$model->profile()->updateOrCreate([], $profileDetails);
> 		} else {
> 			$model->profile()->delete();
> 		}
> 	};
> 
> 	return $result;
> }
> ```
> 
> And then you don't need to hack your fields, you just do :
> 
> ```
> Text::make('Phone', 'profile.phone'),
> Text::make('Age', 'profile.age'),
> ```
> 
> Clean way to have HasOne relationship on multiple fields and remove te relation when one or all fields are null.

This works great until you introduce a Currency field, any ideas how this can also be used with Currency fields?

**Comment by vediansoft** [comment]
> Previous solutions are not working for me, and especially if you didn't set the relationship before. What I 'm doing as temporary workaround is :
> 
> ```
> protected static function fillFields(NovaRequest $request, $model, $fields)
> {
> // ...
> }
> ```
> 
> And then you don't need to hack your fields, you just do :
> 
> ```
> Text::make('Phone', 'profile.phone'),
> Text::make('Age', 'profile.age'),
> ```
> 
> Clean way to have HasOne relationship on multiple fields and remove te relation when one or all fields are null.

Than you very much, I was able to produce it more dynamically. In the scenario, what if you want to add multiple models.


```
    protected static function fillFields(NovaRequest $request, $model, $fields)
    {
        // Ticker for result array
        $count = 0;

        // The prefix of relatable columns within fields.
        // User::first()->profile->first_name
        // Text::make('Voornaam', 'profile.first_name');
        // $request->input('profile_first_name');
        $filters = ['profile_'];

        // Loop through all defined filters above
        foreach ($filters as $filter) {
            // Setup relations
            $relations[Str::replaceFirst('_', '', $filter)] = self::rejectAndFlattenRelation($filter, $request);
        }

        // Fill all primary fields after relations have been extracted from the request
        $result = parent::fillFields($request, $model, $fields);

        // Some complex iteration through all extracted relation requests
        foreach ($relations as $method => $relation) {

            // Append them to the final result accordingly
            $result[++$count][] = function () use ($relation, $method, $model) {

                // Create if not exists otherwise update with relation fields
                $model->{$method}()->updateOrCreate([], $relation);
            };
        }

        // Finally return result
        return $result;
    }

    private static function rejectAndFlattenRelation($filter, &$request)
    {
        // Grab all the currently available inputs
        $input = collect($request->all());

        // Grab all relatable fields according to filter
        $relatableFields = $input->reject(function ($item, $key) use ($filter) {
            return strpos($key, $filter) === false;
        });

        // Remove relation ship fields from request
        $request->except($relatableFields->toArray());

        // Finally flatten collection and return as array
        return $relatableFields->flatMap(function ($item, $key) use ($filter) {
            return [Str::replaceFirst($filter, '', $key) => $item];
        })->toArray();
    }
```

**Comment by codebetjens** [comment]
Hi @vediansoft 
Been trying out your solution here, but when adding more models to $filters in fillFields-method, it only works on the first one in that array. Have you tried successfully with more than one model?

**Comment by vediansoft** [comment]
> Hi @vediansoft
> Been trying out your solution here, but when adding more models to $filters in fillFields-method, it only works on the first one in that array. Have you tried successfully with more than one model?

Woops, I see I did not push into `$relations`

I think this should fix it 

`$relations[Str::replaceFirst('_', '', $filter)][] = self::rejectAndFlattenRelation($filter, $request);`

I'll revise the code tonight when I'm home.

**Comment by codebetjens** [comment]
Hi.
When debuging everything seems ok, relations and all. If I alter places in the relations-array (in my case the models are `['mbRsk_', 'mbEtimValue_']`, that relation is saved correctly and so on. Database columns have no names that should present a problem. But hey, I'll keep testning.

As for your tip, I don't blindly c&p and go straight here to ask you for a solution. It was a pretty straight up question whether you had successfully added more models and got it to work and not critique against your work. Thanks
