### ISSUE TITLE
Database tables prefix

### ISSUE THREAD

**Issue by antonkomarev** [laravel/nova-issues#8]
Right now only one table exists `action_events`, but in my application I already have table with exact same name. It would be great to prefix all Nova database tables with `nova_` prefix.

**Comment by vyuldashev** [comment]
No, it won't. You can use `Nova::ignoreMigrations()` in `NovaServiceProvider::routes` and copy `nova/database/migrations/2018_01_01_000000_create_action_events_table.php` to your `database/migrations/` and make what you want.

**Comment by antonkomarev** [comment]
But why don't just to use prefix to have clean and obvious migrations separation? I'm sure nova will have a lot of migrations in future, and it could increase cost of maintenance for such a simple thing.

**Comment by vyuldashev** [comment]
Okay, I agree with you. It may be helpful in some situations.

**Comment by guillaume23** [comment]
Prefixes table are not taking by the model. I need to put it manualy. 
in my laravel,in my Invoice Model:
`protected $table = 'invoices';`
and the prefix is "erp_"

and i need to put:
`protected $table = 'erp_invoices';`
for working. 

It's normal ? 
Thanks

**Comment by antonkomarev** [comment]
@guillaume23 This issue isn't about user application models table names. It's about prefixing Nova tables.

**Comment by guillaume23** [comment]
Ok sorry, i create an issue.

**Comment by duellsy** [comment]
Similar to this, we heavily use schemas, every client has their own schema which is set as the base when logged in.

For this reason, we need to set the table name to `public.action_events` to allow events to be recorded.

Meaning we need to edit each of the controllers that explicitly reference `DB::table('action_events')`

So if there was a way to set the table name in a config, that would cater for our use case also 👍

**Comment by davidhemphill** [comment]
This feature is no longer planned for the current series of Nova.
