### ISSUE TITLE
Currency field: Value stored in minor units

### ISSUE THREAD

**Issue by vyuldashev** [laravel/nova-issues#80]
There is a good practice to store money in minor units (for example, cents for dollars).

So here is the implementation for making this possible in Nova in `Laravel\Nova\Fields\Currency` field:

```php
<?php

namespace Laravel\Nova\Fields;

use Laravel\Nova\Http\Requests\NovaRequest;

class Currency extends Number
{
    /**
     * The format the field will be displayed in.
     *
     * @var string
     */
    public $format;

    public $inMinorUnits = false;

    /**
     * Create a new field.
     *
     * @param  string  $name
     * @param  string|null  $attribute
     * @param  mixed|null  $resolveCallback
     * @return void
     */
    public function __construct($name, $attribute = null, $resolveCallback = null)
    {
        parent::__construct($name, $attribute, $resolveCallback);

        $this->step('0.01')
            ->resolveUsing(function ($value) {
                if(!$value) {
                    return $value;
                }

                if($this->inMinorUnits) {
                    $value /= 100;
                }

                return money_format($this->format ?? '%i', $value);
            })
            ->fillUsing(function (NovaRequest $request, $model, $attribute, $requestAttribute) {
                $value = $request[$requestAttribute];
                
                if($this->inMinorUnits) {
                    $value *= 100;
                }
                $model->{$attribute} = $value;
            });
    }

    /**
     * The monetary format the field will used be displayed in.
     *
     * @param  string  $format
     * @return $this
     */
    public function format($format)
    {
        $this->format = $format;

        return $this;
    }

    /**
     * The value in database is store in minor units (cents for dollars).
     */
    public function storedInMinorUnits()
    {
        $this->inMinorUnits = true;

        return $this;
    }
}
```

Usage:

```php
public function fields(Request $request) {
    return [
        // ...
        Currency::make('Balance')->storedInMinorUnits(),
    ];
}
```

**Comment by vyuldashev** [comment]
Storing value is in minors also fixed.

**Comment by bonzai** [comment]
[Your solution will not work for every currency](https://simple.wikipedia.org/wiki/ISO_4217):

> Code formation
> Often, the minor currency unit has a value that is 1/100 of the major unit, but 1/1000 is also common.

Personally I would use something like [moneyphp/money](https://github.com/moneyphp/money) to handle it.

**Comment by eugenevdm** [comment]
I'm requested that this be re-opened as much has changed in the last year.

For starters, PHP 7.4 deprecated `money_format`
Laravel Nova 2.11 now using `brick/money`

But there still is no obvious way to store in minor units unless you wrap mutators everywhere in your code.

**Comment by coryrose1** [comment]
@eugenevdm I'm having this issue in a current application, would you mind sharing your implementation even if that means mutators everywhere?

I can't seem to find the right combination, between using format, resolveUsing, and fillUsing, to ensure that the value is both displayed in dollar format in index/detail/update/create but is stored in cents.

Appreciate any guidance!

**Comment by eugenevdm** [comment]
@coryrose1 using mutators became too complex, so I reverted to https://packagist.org/packages/vyuldashev/nova-money-field which just works. Until Nova supports store in minor units natively I won't be able to use the Currency field.

**Comment by coryrose1** [comment]
@eugenevdm Thanks for the suggestion, we'll likely do the same.

**Comment by stephan-v** [comment]
Why is this closed? This is still an issue.

**Comment by crynobone** [comment]
> Why is this closed? This is still an issue.

Please create a new issue describing your problem with reproducing code. It's not practical to reopen a 2 year old issue when there has been a lot of changes since then.
