### ISSUE TITLE
Singular Label Bug on Relationships

### ISSUE THREAD

**Issue by victorpfm** [laravel/nova-issues#800]
- Laravel Version: 5.7
- Nova Version: 1.1.4
- PHP Version: 7.2

### Description:
Since Nova 1.1.4, Relationship labels are defined by _Relationship::make_ method's first parameter. The create buttons use this parameter to singularize the label in create buttons instead of _Resource::singularLabel()_. The problem is when the singular label is not equal to plural label minus ending 's'.

`HasMany::make('Escalações', 'escalacoes', Escalacao::class)`

![image](https://user-images.githubusercontent.com/21281931/46546665-1fe19480-c8a0-11e8-8b5a-44ac7939dea2.png)

It should display **Inserir Escalação**

I imagine the solution would be something like:

`HasMany::make('Escalações', 'escalacoes', Escalacao::class, 'Escalação')`

### Steps To Reproduce:
Add a HasMany field to a Resource:
`HasMany::make('Escalações', 'escalacoes', Escalacao::class)`
Go to resource index page.

**Comment by bonzai** [comment]
```php
HasMany::make('Escalações', 'escalacoes', Escalacao::class, '')
    ->singularLabel('Escalação')
```

**Comment by victorpfm** [comment]
`->singularLabel('Escalação')`

It works!! Thanks!

**Comment by p4rz1val** [comment]
Wonder if there's any option to extend the default behavior of the singular label function in order to add support for more languages, i'm guessing it depends on the Str::singular Laravel function.
