### ISSUE TITLE
Order Scout Search Results by Algolia’s Rank [FR]

### ISSUE THREAD

**Issue by jens-andre** [laravel/nova-issues#801]
@davidhemphill already answered my support request where he said the search results currently following the Nova ordering only, but I think it’s worth a try for a feature request, because as longer as we use Nova, the harder it becomes to find the right content in different scenarios–our Algolia indices have thousands of objects.

Our real world scenario:
We have a table with lots of recipes. In our case the content managers hand pick related recipes by ingredients. When he or she wants to attach a recipe and makes the relatable search with a common ingredient, there are so many results which are all of the sudden ordered alphabetically. The workaround for the content manager is for now:

- open a browser window
- query the site search (Laravel Scout)
- pick the best result
- copy the title
- paste it into the relatable search in Nova
- hopefully find the recipe right away

Another scenario:
We have a table with thousands of articles. On the resource index we have an action for mass categorization. The content manager creates a new category and likes to select the right articles for this category on the resource index. He or she does the full text search for a specific topic, but doesn’t get the best results because of the ordering which is by ID desc. The workaround is similar to the recipe scenario above.

I understand it’s somehow specific to our project, but I really believe when someones content heavy project grows or is even bigger than ours, the users of Nova will complain when they’re not finding the content right away.

**Comment by dwyer14** [comment]
Yeah, +1 for this. Algolia **nails** the order, based on the text you're actually searching for. Seems like the Scout query should just return those results directly, without messing up the order. @davidhemphill, is that a possible/doable thing?

**Comment by dwyer14** [comment]
Yeah, +1 for this. Seems to sort by ResourceID (descending), which strikes me as a bug. Algolia _nails_ the order, based on the text you're actually searching for. Seems like the Scout query should just return those results directly, without messing up the order. @davidhemphill, is that a possible/doable thing?

**Comment by jeffreydevreede** [comment]
I also have noticed this to be a problem, it seems pretty weird to me to tag this as a request and not as a bug.

In my nova application we are using a lot of records and it definitely doesnt come back with the expected results. I've tried fiddling around a bit with the `initializeQueryUsingScout` and the `applyOrderings` functions and getting a little bit better results now. The following code doesn't look very nice but it gets the job done, it needs to be added to the resource class.

```php
protected static function initializeQueryUsingScout(NovaRequest $request, $query, $search, $withTrashed)
{
    $keys = tap(static::applySoftDeleteConstraint(
        static::newModel()->search($search), $withTrashed
    ), function ($scoutBuilder) use ($request) {
        static::scoutQuery($request, $scoutBuilder);
    })->take(200)->keys();

    // Add the keys to a macro'd function so we can retrieve again at a later point.
    if($keys->count() > 1) {
        $query->macro('getKeys', function () use ($keys) {
            return $keys;
        });
    }

    return static::applySoftDeleteConstraint(
        $query->whereIn(static::newModel()->getQualifiedKeyName(), $keys->all()),
        $withTrashed
    );
}

protected static function applyOrderings($query, array $orderings)
{
    // Retrieve the getKeys macro we have added to the query object before.
    $getKeys = $query->getMacro('getKeys');

    if(empty($orderings) && $getKeys) {
        $keys = $getKeys();
        // This is where we add an order to the results depending on the given keys.
        return $query->orderByRaw(DB::raw('FIELD('.static::newModel()->getQualifiedKeyName().', '.$keys->implode(', ').')'));
    }

    return parent::applyOrderings($query, $orderings);
}
```

**Comment by freekmurze** [comment]
+1 for this one. Algolia is pretty good in ordering the search results according to relevancy, so it makes sense that Nova should use that order.

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by lasselehtinen** [comment]
Hi,

I guess this is the same issue that I am having. The Algolia admin panel and tinker return the results in correct relevance order where as in Nova they are sorted by resource id. It seems quite non-intuitive to sort themby resource id, since Algolia would return them in correct order. I would consider this is a bug as well.

![image](https://user-images.githubusercontent.com/1290186/60251028-70869b00-98d0-11e9-93d0-bfe828d46aa0.png)

![image](https://user-images.githubusercontent.com/1290186/60251039-74b2b880-98d0-11e9-8fc3-1c2c925f08ee.png)

**Comment by lasselehtinen** [comment]
@jeffreydevreede Your snipped works fine, but it happens to break the sortable() fields in the process. I guess because the original applyOrderings method contains the following which takes the parameters in account. Any advice on how would one get both working?

```
foreach ($orderings as $column => $direction) {
    $query->orderBy($column, $direction);
}
```

**Comment by approached** [comment]
@lasselehtinen just check the implantation #1836

**Comment by seanmangar** [comment]
@davidhemphill  I'm using nova in a system where we're searching through approx 100k+ athlete names and we absolutely need a correct search order for relevancy. For example, I search for a very well known Elite Athlete and get my first 2 results to be ordered by the latest, whereas Algolia nails it. I'd say it's a bug as well rather than a feature request. And there's clearly an impact on the User Experience as users need to scan through irrelevant results before getting what they want. Is it possible to fix this please?

**Comment by davidhemphill** [comment]
I think this warrants a fair look, as it's definitely reasonable, but unexpected, behavior. Will probably work on this this week. 👍

**Comment by asivaneswaran** [comment]
Any updates on this?
I have the same issue with my site

**Comment by crynobone** [comment]
If the the query already return value output and the issue at the moment is just the default ordering then this patch should be able to solve it. However I haven't done any tests yet to be able to verify that this would be enough at the moment.

[patch.txt](https://github.com/laravel/nova-issues/files/5730010/patch.txt)
