### ISSUE TITLE
Using nova components in main application (outside of nova admin panel)

### ISSUE THREAD

**Issue by bassemlhm** [laravel/nova-issues#804]
**Feature request**

Wouldn't it be nice if we could also leverage Nova components (Index, Forms, Detail page, Cards or Tools from novapackages.com) in our external application too and not just be restricted to the nova admin panel?

1- Basically, we would just add the scripts and css for Nova in our layout.blade.php

```
<link rel="stylesheet" href="{{ mix('app.css', 'nova-assets') }}">
<script src="{{ mix('app.js', 'nova-assets') }}"></script>
```

2- Then we would be able to use the Nova components like for example, resource-index.

In our blade.php views

```
@section('content')
  My own custom content

  <resource-index :resource-name="'Post'"></resource-index>
@endcontent
```

Or in our app.js

```
 require('./bootstrap');
 window.Vue = require('vue');
 Vue.component('example-component', require('./nova/ResourceIndex.vue'));
 const app = new Vue({
   el: '#app'
 });
```

Does anyone know how we could leverage Nova's components and packages outside of the admin panel and in our main application?

**Comment by davidhemphill** [comment]
I understand why this would be nice, but currently there's no plan to extract each field into a separate component library.

**Comment by riabiy-denis** [comment]
@davidhemphill I know, but still wishing for that :D
