### ISSUE TITLE
Using help() on a field for a resource action renders incorrectly

### ISSUE THREAD

**Issue by tdondich** [laravel/nova-issues#805]
- Laravel Version: 5.7.*
- Nova Version: 1.1.3
- PHP Version:

### Description:
When utilizing the help() method on a field inside a resource action, the modal that shows the action has the help text rendered underneath the field label, not providing sufficient width to the help text.

### Steps To Reproduce:

Add a field to a resource action and provide helper text via help()

Field renders as an example:

![action-field-helper-error](https://user-images.githubusercontent.com/3330334/46563859-bcb02c00-c8b8-11e8-805a-4db58b6aa9a9.png)

**Comment by alexbowers** [comment]
Can you confirm this in 1.1.4?

**Comment by bonzai** [comment]
Duplicate of #626.

**Comment by davidhemphill** [comment]
Help text was moved below inputs a few versions ago. Make sure you're using the latest version, have correctly published the new Nova css/js assets, and provide the exact code to display the problem. I'll open it up when you do.
