### ISSUE TITLE
Textarea parent div width is w-4/5 instead of w-1/2

### ISSUE THREAD

**Issue by GordanaP** [laravel/nova-issues#806]
- Laravel Version: 5.7.8
- Nova Version: 1.1.3
- PHP Version:

### Steps To Reproduce:
``<div class="py-6 px-8 w-4/5"><textarea id="description" dusk="description" rows="3" class="w-full form-control form-input form-input-bordered py-3 h-auto"></textarea></div>``

**Comment by davidhemphill** [comment]
This is not a bug.
