### ISSUE TITLE
Search z-index

### ISSUE THREAD

**Issue by liefie** [laravel/nova-issues#807]
- Laravel Version: 5.6.39
- Nova Version: 1.1.4
- PHP Version: 7.2

### Description:

The z-index on the search has changed to z-20, but the z-index on the trend chart has z-40 so it shows over the search results

### Steps To Reproduce:

global search on dashboard with a trend metric card

**Comment by cbotman** [comment]
Here's a screenshot of the same issue happening on Nova 1.1.7:

![screen shot 2018-11-21 at 10 58 27 am](https://user-images.githubusercontent.com/3414118/48816556-8a319400-ed7d-11e8-9e92-a217282bc011.png)

**Comment by dillingham** [comment]
The dropdown menu does it too / content section loading

**Comment by bonzai** [comment]
This has been fixed and will be included in the next release.
