### ISSUE TITLE
Markdown & Trix fields not showing full content on load

### ISSUE THREAD

**Issue by stuartcusackie** [laravel/nova-issues#808]
- Laravel Version: 5.7.8
- Nova Version: 1.1.4
- PHP Version: 7.2.9
- Chrome Version 69.0.3497.100 and FireFox Version 62.0.3 (64-bit)
- Windows 10

### Description:

Trix & Markdown editor content longer than 10 lines is invisible on load of resource edit screen.

### Steps To Reproduce:

+ Set up either a Trix Field or a Markdown Field 
+ Create a resource and enter some long content into the field
+ Save the resource
+ Reload the page (content invisible after 10 or so lines)
+ Click to reveal invisible content

I have copied and pasted some of the Laravel docs into a markdown field for my example screenshots.

**On load:**
![image](https://user-images.githubusercontent.com/20210934/46572216-d2395a80-c979-11e8-857b-0848f0c94f98.png)

**After clicking:**
![image](https://user-images.githubusercontent.com/20210934/46572226-f1d08300-c979-11e8-95d6-71a721f793fd.png)

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
