### ISSUE TITLE
Using BelongsTo in Lenses

### ISSUE THREAD

**Issue by treeStoneIT** [laravel/nova-issues#809]
- Laravel Version: 5.7.8
- Nova Version: 1.1.4
- PHP Version:  7.2.7

### Description:
I have tried to use `BelongsTo` Field in a Lense
Here is the error i got in the debugbar: 
```
Class 'App\Nova\Lenses\User' not found /../../admin/src/Fields/BelongsTo.php#93 Symfony\Component\Debug\Exception\FatalThrowableError
```

It seems it's looking for the User Class in the wrong place

**Comment by davidhemphill** [comment]
You need to set the third parameter of the BelongsTo field. 

```php
BelongsTo('User', 'user', \App\Namespace\User::class);
```

**Comment by treeStoneIT** [comment]
@davidhemphill I tried, 

I am getting the following error `Call to undefined method App\User::uriKey()
.../.../vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php#50`

**Comment by mostafakram** [comment]
Having the same issue as @bomshteyn and when defined the third parameter as @davidhemphill mentioned i received new error 

> Call to undefined method App\MyModel::uriKey()

**Comment by dkulyk** [comment]
@mostafakram Third parameter must be resource class instead model class.

**Comment by mostafakram** [comment]
Great i believe that it can't find the resource by itself because its not in the name space as the lens .. shouldn't that be added to the documentations?

**Comment by dkulyk** [comment]
[Customizing Resource Classes](https://nova.laravel.com/docs/2.0/resources/relationships.html#belongsto)
