### ISSUE TITLE
Any way to specify relationship method on hasMany relationship.

### ISSUE THREAD

**Issue by Xsecrets** [laravel/nova-issues#81]
For instance I have two models 
Order
OrderProducts
order has a hasmany relationship with orderproducts as below
public function order_products() { return $this->hasMany(OrderProduct::class); }
if I setup a relationship field in nova like this
HasMany::make('OrderProducts');

I get an error about querybuilder function orderproducts not found. I found that if I change the relationship function to orderproducts instead of order_products it works, but is there a way to specify the existing method if differs from what is automatically expected. It can quickly turn into a mess trying to change or duplicate all your existing relationship methods.

I know some of the functions have multiple parameters for specifying things like this, but there is no documentation about any additional parameters on hasmany.

**Comment by Xsecrets** [comment]
Ok that exact code doesn't work, but I managed to figure it out today. Not sure why I couldn't the other day, but it appears to be 
HasMany::make('NovaRelationClassName', 'method_on_app_model');

Thanks for the kickstart.

**Comment by bradders** [comment]
Thanks for the fixes, saved me minutes/hours/days! 🙌🏻

**Comment by notflip** [comment]
@Xsecrets https://github.com/laravel/nova-issues/issues/179#issuecomment-425682756
