### ISSUE TITLE
JSON field does not display full until click mouse at blank beside.

### ISSUE THREAD

**Issue by phoenixg** [laravel/nova-issues#814]
- Laravel Version: v5.7.8
- Nova Version: v1.1.4 and until v1.1.7
- PHP Version: 7.2

### Description:

JSON field does not display full until click mouse at blank beside. I guess it's a javascript code previewer bug.

### Steps To Reproduce:

Before click mouse:

![image](https://user-images.githubusercontent.com/990040/46588019-a0360e80-cac7-11e8-84ff-abca5526fbb6.png)

After click mouse:

![image](https://user-images.githubusercontent.com/990040/46588029-cbb8f900-cac7-11e8-8465-d0c96e280da4.png)

**Comment by bonzai** [comment]
Related to #808.

**Comment by elijahworkz** [comment]
I have the same issue with Code field.
Laravel - 5.7
Nova - 1.1.4

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
