### ISSUE TITLE
Server Error Only when i use Nova

### ISSUE THREAD

**Issue by MalkSof** [laravel/nova-issues#815]
- Laravel Version: 5.7
- Nova Version: 1.1.4
- PHP Version: 7

### Description:
Server Error Only whe i use nova

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/42155335/46588146-810a9300-ca6d-11e8-87af-52c16e996c6b.png)

**Comment by phoenixg** [comment]
I think you can have a look at your ` laravel.log` and see what error it says.

**Comment by alexbowers** [comment]
Please provide more details we can use to help you debug this. I'll reopen when we get these details, if it appears to be a bug in Nova.

**Comment by ShinHyungJune** [comment]
me too T.T i don't know why
