### ISSUE TITLE
Cannot run Action if I set a resource policy's update method return false

### ISSUE THREAD

**Issue by phoenixg** [laravel/nova-issues#817]
- Laravel Version: v5.7.8
- Nova Version: v1.1.4
- PHP Version: 7.2

### Description:

Cannot run Action if I set a resource policy's update method return false

### Steps To Reproduce:

I don't want to update the resource, but I want to execute the action defined for the resource.

**Comment by phoenixg** [comment]
Thank you, that solved my problem, although it may be a little bit confusing.

**Comment by dillingham** [comment]
@phoenixg https://nova.laravel.com/docs/1.0/actions/registering-actions.html#authorization
