### ISSUE TITLE
Cannot attach belongs to many relationship in create/edit views.

### ISSUE THREAD

**Issue by sulemankhann** [laravel/nova-issues#818]
I have two table diets and group and they have many to many relationship. When i add `BelongsToMany::make('Groups')` on my Diet resource i don't get drop down on Diet create/edit view and when i add manually add field to diet resource i get database error groups isn't a know field. How to resolve this issue? How can i alter create query and save diet group to pivot table?

**Comment by dillingham** [comment]
@sulemankhann not an issue, its a question

Try asking here https://laracasts.com/discuss/channels/nova

**Comment by vernard** [comment]
I was kinda hoping this feature exists in Nova. This would be a huge improvement on the user experience.

Any of you guys using an alternative?

**Comment by martijnimhoff** [comment]
Try this: https://github.com/dillingham/nova-attach-many
