### ISSUE TITLE
DateTimePicker localization

### ISSUE THREAD

**Issue by mingyoung** [laravel/nova-issues#819]
- Laravel Version: 5.7.8
- Nova Version: 1.1.3
- PHP Version: 7.2

### Description:
![image](https://user-images.githubusercontent.com/6228858/46598638-60971300-cb17-11e8-832f-a66bd3149880.png)

I see file `DateTimePicker.vue`

It does not applied `locale` option. Could you please add this support?

Thanks.

**Comment by bonzai** [comment]
Duplicate of #343.

**Comment by mingyoung** [comment]
@bonzai Thanks, I'll close this.
