### ISSUE TITLE
Feature Request: URL field (with preview for media)

### ISSUE THREAD

**Issue by peterfox** [laravel/nova-issues#82]
Would be nice to have a simple URL field and even potentially a URL preview if you make expect it to be an Image. I tried making the image stuff work with simply a URL and it didn't work out well, felt overly complicated. Seems like a simple field type to add. Happy to do the work although I have a feeling I'd struggle to implement the Vue component for it.

**Comment by cotton9** [comment]
In the meantime...this package gets you halfway there. https://novapackages.com/packages/pdewit/nova-external-url

**Comment by taylorotwell** [comment]
This repository is for tracking bugs. Feature requests may be emailed to Nova customer support.
