### ISSUE TITLE
HasMany relation field working with ManyToMany Database relations

### ISSUE THREAD

**Issue by cwinkler** [laravel/nova-issues#820]
- Laravel Version: 5.7.8
- Nova Version: 1.1.4
- PHP Version: 7.2.10

### Description:
I have a ManyToMany Relation defined in my Eloquent Models (Users belongsToMany Group and vice versa). If I define a HasMany Field in my User Resource I am able to create and attach a Group to a User. I think this is possible due to Nova using the underlying Eloquent Model's Methods. 

While this may come in handy I am wondering if this is subject to change or intended behavior?

### Steps To Reproduce:
- Create a ManyToMany Relation between two Models
- Create Resources for these Models
- In the first Model add a HasMany Field to the second Model

**Comment by waygou** [comment]
I think too, that's the reason.

Still, as a best practice that I am using is to create the same relationship fields as your model relationships are defined.

Any difference on this might come up with unpredictable results on your Web UI or data model ...

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
