### ISSUE TITLE
Nova Themes not applied to Login

### ISSUE THREAD

**Issue by nickels** [laravel/nova-issues#823]
- Laravel Version: 5.7.8
- Nova Version: 1.1.4
- PHP Version: 7.2

### Description:
Assets created with `php artisan nova:theme` are not loaded on the login page, therefore the custom theme is not applied to the login. In my opinion the theme should also be applied to the login page.

**Comment by blackfyre** [comment]
Can confirm, the theme is not loaded on the login screen.

**Comment by blackfyre** [comment]
For a workaround you can create a `layout.blade.php` file in your `resources/views/vendor/nova/auth` folder based on the one in the package's `vendor/laravel/nova/resources/views/auth/layout.blade.php` file, having Laravel use it to override template provided in the package. Just add
```
<!-- Tool Styles -->
    @foreach(Nova::availableStyles(request()) as $name => $path)
        <link rel="stylesheet" href="/nova-api/styles/{{ $name }}">
    @endforeach
```

in the `<head>` section.

**Comment by pktharindu** [comment]
This issue still remains as of:
- Laravel Version: 5.8.7
- Nova Version: 2.0.0

**Comment by jordyvandomselaar** [comment]
Bump. We're running into this as well. I think the fix would be publishing `auth` views.

Let me know if I can help!

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.

**Comment by dillingham** [comment]
@davidhemphill this makes themes incomplete

**Comment by ievgenklymenko** [comment]
Having this issue as well. Why themes can't be applied to my login form? What's the point of protecting them?..

**Comment by scottybo** [comment]
I suppose this makes sense as Nova can be added to existing projects - you wouldn't want your existing project styling to be overridden by a Nova theme. However I also agree that this doesn't need to be an authorized route.

To extend on @blackfyre's response, here are the steps I took:

- Create a symlink for the css folder for your theme in `nova_components` (on Linux Mint you can just right mouse click the folder and choose 'Make Link'
- Put this new linked folder in `/public/css`, and rename it to something logical (e.g. your theme name)
- In `resources/views/layouts/app.blade.php` add the following below any existing styles:

```
    <link rel="stylesheet" href="{{ mix('app.css', 'vendor/nova') }}">
    <link rel="stylesheet" href="{{ asset('css/YOUR-FOLDER-NAME/theme.css') }}">
```

And you'll now have your themes applied.

**Comment by dillingham** [comment]
@jbrooksuk do you want a new issue or prefer to re-open this?

**Comment by cannycookie** [comment]
Thankyou @scottybo for detailed info although I don't have a 

`resources/views/layouts/app.blade.php`

Your stylesheet code would appear to be referencing `nova/resources/views/layout.blade.php`

Which i have tried copying to: `resources/views/vendor/nova/layout.blade.php`

But it is not applied.  Also tried creating an override in the theme folder:-
`nova-components/CsaAdmin/resources/views/layout.blade.php`

But no luck with that being recognised either.

Can anyone let me know the method for overriding a nova template?

**Comment by davidhemphill** [comment]
You can now do this with the updated theming capabilities added in recent versions.

**Comment by scottybo** [comment]
@davidhemphill brilliant! Do you have any documentation to go along with this?

**Comment by davidhemphill** [comment]
The documentation was updated when the changes released. New themes generated with the `php artisan nova:theme` command contain the new strategy used for themes, which you can backport to your existing themes.

**Comment by jsheffers** [comment]
I've created a theme with the latest Nova and it's still not applied to the login screen.  Is there anything special that needs to be done here?

**Comment by emanuelmutschlechner** [comment]
The simplest way to solve this issue is to register the theme styles when `NovaServiceProviderRegistered` event is dispatched, instead of `ServingNova` in `Nova::serving`.

```php
use Illuminate\Support\Facades\Event;
use Illuminate\Support\ServiceProvider;
use Laravel\Nova\Events\NovaServiceProviderRegistered;
use Laravel\Nova\Nova;

class ThemeServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        // Nova::serving(function (ServingNova $event) {
        Event::listen(NovaServiceProviderRegistered::class, function ($event) {
            Nova::theme(asset('/vendor/theme/theme.css'));
        });
...
```

**Comment by judahnator** [comment]
> ... when `NovaServiceProviderRegistered` event is dispatched ...

Brilliant, this got it to work for me!
