### ISSUE TITLE
belongsto can not be define as utf-8 character

### ISSUE THREAD

**Issue by bfkkkd** [laravel/nova-issues#825]
- Laravel Version: 5.7.6
- Nova Version: 1.1.3
- PHP Version:7

### Description:
BelongsTo::make('用户', 'user')->rules('required'), will display fault

**Comment by bonzai** [comment]
Use third parameter to define resource:

```php
BelongsTo::make('用户', 'user', 'App\Nova\User')->rules('required')
```
