### ISSUE TITLE
Details.vue - button title attributes missing localization variable syntax

### ISSUE THREAD

**Issue by mattivie14** [laravel/nova-issues#829]
On the Details.vue file, the title attribute on the 'delete button' (lines 75-82) is strictly "Delete" instead of using a localization variable like in other places. 
It should be: `title="__('Delete')"` instead of the current: `title="Delete"`

I've changed that verb to "Archive" in the en.json file as our resources are all using soft deletes, and it still shows "Delete" on the details page, which is undesirable. 

(I believe the other buttons on this page also need language variables on the title attributes, and there may be other values as well, however I noticed the Delete one specifically :) )

_P.S. - It would be awesome to be able to configure the font-awesome icon that shows on those buttons as well_

**Comment by alexbowers** [comment]
RE: Font-awesome icons, can you create a separate issue as a feature request for that?

**Comment by dillingham** [comment]
its not font awesome icons, and just override the vue component

```js
Nova.booting((Vue, router) => {
    Vue.component('icon-delete', require('./components/DeleteIcon'));
})```

```html
<template functional>
    <path fill-rule="nonzero" d="M6 4V2a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2h5a1 1 0 0 1 0 2h-1v12a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V6H1a1 1 0 1 1 0-2h5zM4 6v12h12V6H4zm8-2V2H8v2h4zM8 8a1 1 0 0 1 1 1v6a1 1 0 0 1-2 0V9a1 1 0 0 1 1-1zm4 0a1 1 0 0 1 1 1v6a1 1 0 0 1-2 0V9a1 1 0 0 1 1-1z"/>
</template>
```

**Comment by mattivie14** [comment]
@dillingham Where do you actually add that `Nova.booting` code in order to do that?

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍

**Comment by mattivie14** [comment]
@davidhemphill Bit of a follow up on this one, although I don't fully understand how you guys are doing it exactly. 
When I change the localization variable for "Delete", and I click to Force Delete a resource, in the confirmation Modal the Buttons are normally "Cancel" and "Delete" but, in this instance the button says "Archive" (what I changed it to in my localization) however the button should say "Force Delete" to match the current mode and action it's trying to really confirm. 
Looking at the DeleteResourceModal.vue file, it looks as though it potentially could show Force Delete, but for some reason is not. (it may be intentionally showing "Delete" when the mode is Force Delete, this is what I don't fully understand) 
I would make a PR if I knew how to fix it :)
