### ISSUE TITLE
Searchable BelongsTo field bug

### ISSUE THREAD

**Issue by lucasromanojf** [laravel/nova-issues#83]
1) Create a model with a Searchable BelongsTo field filled up
2) Click to edit the model
3) Clear the value of the BelongsTo field by clicking on the "X"
4) Cick the update button
5) The value won't be set to null on the database

**Comment by dillingham** [comment]
SearchInput.vue 
```js
this.$emit('clear', null)
```
BelongsToField.vue
MorphToField.vue
Attach.vue
```html
@clear="clearSelection"
```

```js
clearSelection() {
      this.selectedResource = ''
      this.availableResources = []
},
```

Needs to remove previous model

**Comment by dillingham** [comment]
Related https://github.com/laravel/nova-issues/issues/89
