### ISSUE TITLE
Select field - Title property with value '0' appears empty when attach

### ISSUE THREAD

**Issue by nsaumini** [laravel/nova-issues#830]
I have a `Question` model with many to many relationship with `Choice` model.

Under `Question` resource I have added following field `BelongsToMany::make('Choices')`. I have an entry in `Choice` with title value 0. After I click `Attache Choice` in `Question` detail view, under choice dropdown the entry with title value 0 appears as empty string.

![screen shot 2018-10-11 at 10 21 23](https://user-images.githubusercontent.com/12414016/46781605-0927bb80-cd40-11e8-97a6-c90dadc3e833.png)

**Comment by davidhemphill** [comment]
Sorry, but we are unable to debug your issue without a reproducible code example. Once you provide that we can open this up again.
