### ISSUE TITLE
Nova login page not working on Internet Explorer 11

### ISSUE THREAD

**Issue by desthercz** [laravel/nova-issues#832]
- Laravel Version: 5.7.9
- Nova Version: 1.1.4
- PHP Version: 7.1.22

### Description:
As the title says, Laravel Nova login page does not work in Internet Explorer 11 (v 11.345.17134.0)
![ie_error](https://user-images.githubusercontent.com/25509616/46796223-688bc880-cd4c-11e8-96a5-a9bb3a763eed.PNG)

### Steps To Reproduce:
1) Open Internet Explorer 11
2) Navigate to Laravel Nova site, eg. http://example.test/nova
3) Laravel Nova page will shortly flash in browser, after a second the page turns white and error appears in console.
4) User is enable to interact with admin panel

**Comment by AegirLeet** [comment]
See #822.

**Comment by desthercz** [comment]
Thanks, i will close this now to avoid duplicity.
