### ISSUE TITLE
Props in default-field other than "field" are not parsed in published package

### ISSUE THREAD

**Issue by manogi** [laravel/nova-issues#833]
- Laravel Version: 5.7.9
- Nova Version: 1.1.4
- PHP Version: 7.2

### Description:

My package is the [Tiptap Editor](https://github.com/manogi/nova-tiptap).

Everything works fine locally - I use
```
<default-field :field="field" :errors="errors" :full-width-content="true">
```
and my editor shows over the full width.

But when I push my code to Github and release the package, in the downloaded and installed version those two props :errors and :full-width-content are not "recognized" or whatever you call it, they also show up in the source code as

![image](https://user-images.githubusercontent.com/1419634/46801037-c5da4680-cd59-11e8-9903-a1422d0c617c.png)

..which they shouldn't. Strange.

### Steps To Reproduce:

Make a field package, use ` :full-width-content="true"`, release and install it an see if the field is shown over the full width.

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
