### ISSUE TITLE
Fields\Boolean does not support attributes with '->'

### ISSUE THREAD

**Issue by StanAngeloff** [laravel/nova-issues#834]
- Laravel Version: 5.6.39
- Nova Version: 1.1.4
- PHP Version: 7.1.20

### Description:

In `Laravel\Nova\Fields\Field` each call to `data_get` is accompanied by `str_replace('->', '.', $attribute)`. This is true for `resolveAttribute()` as well.

In `Laravel\Nova\Fields\Boolean`, though, `resolveAttribute()` is overridden and `str_replace` is missing.

**Comment by dkulyk** [comment]
Duplicate #598
