### ISSUE TITLE
Date field not showing red border on error

### ISSUE THREAD

**Issue by reinink** [laravel/nova-issues#835]
- Laravel Version: v5.7.9
- Nova Version: v1.1.4
- PHP Version: 7.2.8

### Description:

When a date field has an error, the border isn't red like other input fields.

![image](https://user-images.githubusercontent.com/882133/46805564-623d2280-cd33-11e8-8d14-4c664cb93248.png)

### Steps To Reproduce:

Simply cause any error on a date field.

**Comment by dkulyk** [comment]
[Patch](https://gist.github.com/dkulyk/1eeac0e5b8107535ab1afde22f765921)

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
