### ISSUE TITLE
Case sensitive data columns will be not shown at Nova

### ISSUE THREAD

**Issue by dennis2711** [laravel/nova-issues#836]
- Laravel Version: 5.7.9
- Nova Version: 1.1.4
- PHP Version: 7.2.10

### Description:

Case sensitive data columns will be not shown at Nova

### Steps To Reproduce:

1. Create a Database Table "users" with a Column which names "userName" 

` $table->string('userName')`

2. Create a UsersSeeder with some or one data record-/s

`public function  run() {
DB::table('users')->insert(['userName' => 'test_user']);
}`

3. Create a User Model and add the Column "userName" to the visiable & fillable array.

`protected $visible = [
        'id',
        'userName',
    ];`

 `protected $fillable = [
        'userName'
    ];`

4. Create the Nova Resource "User" which used the App\User Model

`php artisan nova:resource User`

5. Create a Text Fields which names "userName"

`Text::make('userName')`

6. The Column "userName" will be not shown at the Nova Interface

![nova-bug](https://user-images.githubusercontent.com/28525095/46808945-c7156e80-cd6d-11e8-9678-37a04b35e8d9.JPG)

**Comment by bonzai** [comment]
What if you turn off snake casing of attribute names?

```php
// AppServiceProvider::boot()
App\User::$snakeAttributes = false;
```

**Comment by dkulyk** [comment]
First argument is name of a field. Second is an attribute name. If it not specified the attribute name set from the field's name.
```php
Text::make('User name', 'userName')
```
[Field Column Conventions](https://nova.laravel.com/docs/1.0/resources/fields.html#defining-fields)

**Comment by dennis2711** [comment]
Thanks @dkulyk 
That will work.
