### ISSUE TITLE
Add New on BelongsTo relationship

### ISSUE THREAD

**Issue by dtannen** [laravel/nova-issues#837]
Is there a way to show a link to "Add New" on a belongsTo relationship?  

Even better would be a modal to pop-up or slide down with the form fields to Add New relationship-- and the new addition automatically being selected after being added.

Anyone have a workaround to accomplish something similar?

**Comment by dillingham** [comment]
@dtannen that was proposed as a package idea here https://github.com/tightenco/nova-package-development/issues/47 and eventually an implementation occurred in [a multiple field package](https://github.com/tightenco/nova-package-development/issues/47#issuecomment-424355256). I would personally love to see this as an isolated field package or core field.

**Comment by davidhemphill** [comment]
There will likely be no plans to implement this feature.

**Comment by stuartcusackie** [comment]
Not sure if these closed issues get read again but this would be a nice feature. I've been using a similar CMS and the 'Add new' links are a simple way to save a click and improves the flow for the end-user.

Obviously pop-up modal forms are much bigger endeavour! but perhaps something for Nova 4.

**Comment by crynobone** [comment]
@stuartcusackie https://nova.laravel.com/docs/3.0/resources/relationships.html#creating-inline-relations

**Comment by stuartcusackie** [comment]
@crynobone Thank you! This looks great! Don't know how I missed it.
