### ISSUE TITLE
Error when updating a resource after deleting an image

### ISSUE THREAD

**Issue by unlikenesses** [laravel/nova-issues#838]
- Laravel Version: 5.7.8
- Nova Version: 1.1.3
- PHP Version: 7.1.18

### Description:

Deleting an image in a resource then immediately updating the resource produces this error:

> Another user has updated this resource since this page was loaded

### Steps To Reproduce:

1. Add a resource with an image
2. Delete the image
3. Click Update.

**Comment by cdupoiron** [comment]
Any news on this bug? I can reproduce


    Laravel Version: 5.7.28
    Nova Version: 1.3.2
    PHP Version: 7.2.15

**Comment by yehudahkay** [comment]
+1

**Comment by cdupoiron** [comment]
Hello @unlikenesses , did you find a solution?

**Comment by a2sc** [comment]
Same issue with the `Laravel\Nova\Fields\File` when deleting a file in the edit form I have the same error message:

> Another user has updated this resource since this page was loaded

Here is the code in App\Nova\Product@fields:
```php
File::make('PDF', 'pdf_file')
        ->rules('file', 'mimes:pdf', 'max:10240')
        ->help('PDF file only. Maximum 10Mo.')
        ->disk('public')
        ->path('pdfs')
        ->storeAs(function (Request $request) {
             return $request->pdf_file->getClientOriginalName();
        })
       ->storeSize('pdf_filesize')
       ->disableDownload()
       ->onlyOnForms(),
```

- Local environment
- PHP 7.2.14
- Laravel Framework 5.8.14 
- Laravel Nova 2.0.0

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!

@a2sc I can see that you've re-produced this in v2, could you please create a new issue.
