### ISSUE TITLE
Specify that name field is required in User model for Action Log

### ISSUE THREAD

**Issue by angelocala94** [laravel/nova-issues#839]
Line 69 inside `ActionResource.php`

```     
Text::make(__('Action Initiated By'), function () {
    return $this->user->name ?? $this->user->getKey;
}),
```

This assumes that we use the default `name` field of `users` table.
In my case, I have two different columns `first_name` and `last_name` in my `users` table.

I think that should be mentioned in docs because in my case, the Actions resource does not display anything inside "Initiated by" field.

I've defined an accessor in my `User` model to solve this issue.

**Comment by davidhemphill** [comment]
Glad you found a solution. That's the correct way if you're User model doesn't map 1:1 to Nova/Laravel's.
