### ISSUE TITLE
HasMany Field (BadMethodCallException uriKey does not exist)

### ISSUE THREAD

**Issue by nickels** [laravel/nova-issues#84]
v1.0.5

`HasMany::make('Event Categories', 'categories', 'App\Models\Events\EventCategory'),`

returns:

```
BadMethodCallException thrown with message "Method Illuminate\Database\Query\Builder::uriKey does not exist."
```

**Comment by bonzai** [comment]
The third parameter is `$resource` (not a model).

**Comment by nickels** [comment]
Thanks!

```
HasMany::make('EventCategories', 'categories'),
```

Tries to resolve 
```
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'App\Nova\EventCategory' not found
```

instead of `App\Models\Events\EventCategory` any thoughts?

**Comment by nickels** [comment]
`HasMany::make('EventCategories'),` worked fine when the Nova Resource for the said model was created.. Kind of missed out on that...
