### ISSUE TITLE
Nova doesn't render number zero in a Number-field [again]

### ISSUE THREAD

**Issue by satoved** [laravel/nova-issues#840]
https://github.com/laravel/nova-issues/issues/500 issue is present again

- Laravel Version: 5.7
- Nova Version: 1.1.4
- PHP Version: 7.2

### Description:
Number field doesn't show 0 value

![image](https://user-images.githubusercontent.com/14319239/46905800-58691a00-cf01-11e8-83d7-5990395549a8.png)

### Steps To Reproduce:
1) Create Number field
2) Set 0 value in DB
3) Open form

**Comment by imlida** [comment]
same issues

**Comment by thill0822** [comment]
similar issue. I had to update the DB field to allow null or I get an error on update.

When updating, changes to 0, but if value is already set to 0, Nova is assuming this means null.
