### ISSUE TITLE
custom-detail-toolbar no resourceId available

### ISSUE THREAD

**Issue by bernhardh** [laravel/nova-issues#843]
- Laravel Version: 5.7
- Nova Version: 1.1.14
- PHP Version: 7.2

### Description:
I created a custom-detail-toolbar, but the value of the resourceId property is wrong.

### Steps To Reproduce:

I created the toolbar with `artisan nova:resource-tool bmdev/custom-detail-toolbar` and modified it like so:

```
<template>
    <div class="w-full text-right">
        resourceId:{{ resourceId }}<br>
        resourceName: {{ resourceName}}<br>
        field: {{ field}}
    </div>
</template>
```

And thats the result of it:

![image](https://user-images.githubusercontent.com/642292/46914555-d0861d00-cf9f-11e8-8448-51a60240f2a4.png)

As you can see, there is no data for field and the value of resourceId is wrong.

**Comment by alexbowers** [comment]
Can you confirm the version of Nova you are using? I assume you meant 1.1.4, but want to confirm since you stated 1.1.14

**Comment by bernhardh** [comment]
Ah. sorry. Yes I meant `v1.1.4`

**Comment by Aferz** [comment]
These are the props that are passed to component `custom-detail-toolbar` in view `Detail.vue`.

```html
<custom-detail-toolbar
  :resource="resource"
  :resource-name="resourceName"
  :resource-id="resourceName"
/>
```

So yeah, there is a bug for the `resourceId` prop and as you can see, there is no `field` prop passed down to `custom-detail-toolbar`.

**Comment by AdamFullstripe** [comment]
can you please flag this as a bug?

**Comment by tjmckenzie** [comment]
This is still the case in Nova 1.1.7

**Comment by mnightingale** [comment]
Still a problem on 1.1.8

Partial patch to fix it...

```
--- a/resources/js/views/Detail.vue
+++ b/resources/js/views/Detail.vue
@@ -50,7 +50,7 @@
                         <custom-detail-toolbar
                             :resource="resource"
                             :resource-name="resourceName"
-                            :resource-id="resourceName"
+                            :resource-id="resourceId"
                         />
 
                         <!-- Actions -->
```

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
