### ISSUE TITLE
Allow a morphTo id to be nullable

### ISSUE THREAD

**Issue by filtration** [laravel/nova-issues#846]
So, I have dynamic forms, that can be passed across multiple models and don't always necessarily belong to a specific ID.

For example:

section a (belongs to Model A)
section b (belongs to Model A, and Id 2)

Now I normally get these results like so:

```
    /**
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function sections(): Builder
    {
        return Section::where(function($query) {
            $query
                ->where('owner_type', __CLASS__)
                ->where('owner_id', $this->id);
        })->orWhere(function($query) {
            $query
                ->where('owner_type', __CLASS__)
                ->where('owner_id', null);
        });
    }
```

Now in nova, with morphto, I have to set an id aswell when creating a record, I can't set the id to null:

<img src="https://i.imgur.com/0nTf87e.png">

My db strucure always requires the 'owner_type' but not always the owner_id (if there's no owner ID, it belongs to every record under that model)

So, my records will be like so:

```
INSERT INTO crm.sections 
            (id, 
             user_id, 
             owner_id, 
             owner_type, 
             heading, 
             description, 
             ` position ` , 
             created_at, 
             updated_at) 
VALUES     (6, 
            NULL, 
            NULL, 
            'App\\Projects\\Entities\\Project', 
            'Project Address', 
'Where is the project located? The address will help you organise projects by location' 
            , 
3, 
'2018-10-15 05:54:01.000', 
'2018-10-15 05:54:01.000'); 
```

So, is there anyway to allow the morphto id to be null?

**Comment by asheaheartcup** [comment]
bump. nullable on morphTo() is also an issue with the exists() method. This is a big issue when \Illuminate\Database\Schema\Blueprint::class has a nullableMorphs() method allowing the database to store such behavior.

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
