### ISSUE TITLE
Localization: singular translation not respected on a relations table

### ISSUE THREAD

**Issue by johanvanhelden** [laravel/nova-issues#847]
- Laravel Version: 5.7.9
- Nova Version: 1.1.4
- PHP Version: 7.1

### Description:
I've created Nova resources for the spatie-permissions Role and Permission models.
Since our app is multilingual I've also added the localization methods and translations.
Unfortunately, Nova does not respect this only on relationship fields and still tries to mutate them by itself.

On the resource pages themselves the singular translation works perfectly.

So the singularization messes it up. So it should either not try to singularize if a translation is passed, or it should respect the singular label on the resource.

### Steps To Reproduce:
Create a Nova resource with custom label methods (in my case a `Permission` resource for the `Permission` model):
![screenshot from 2018-10-17 12-33-24](https://user-images.githubusercontent.com/19389981/47080723-0bd75480-d209-11e8-9cf8-3802bc3c1d8c.png)

Add the translation:
![screenshot from 2018-10-17 12-33-47](https://user-images.githubusercontent.com/19389981/47080860-67094700-d209-11e8-9805-c56842c85a85.png)

Add it to another resource (in my case a `User`):
![screenshot from 2018-10-17 12-36-51](https://user-images.githubusercontent.com/19389981/47080834-58bb2b00-d209-11e8-8096-a1a76c92a7a3.png)

And notice it does not respect the translation (it should say the plural `Permissies` or the singular `Permissie` and it should not assume it's English and singularize it the English way: `Permissy`):
![screenshot from 2018-10-17 12-40-24](https://user-images.githubusercontent.com/19389981/47081055-e7c84300-d209-11e8-8311-acde1af04e63.png)

![screenshot from 2018-10-17 12-40-33](https://user-images.githubusercontent.com/19389981/47081057-eb5bca00-d209-11e8-9262-7ac2d4cf6ebd.png)

And as you can see, it works fine on the resource page itself:
![screenshot from 2018-10-19 11-40-58](https://user-images.githubusercontent.com/19389981/47210713-f17db200-d393-11e8-93d5-3c173c7b9d76.png)

---

I am also using https://github.com/franzdumfart/laravel-nova-localizations/tree/master/lang to translate the UI.

**Comment by deivian** [comment]
Those strings are translated from the json file nova generates, not through a .php file

![image](https://user-images.githubusercontent.com/1251146/47147353-5b338880-d2ce-11e8-8153-53990884d686.png)

**Comment by johanvanhelden** [comment]
That sounds weird. You can define resource translation in the resources, but those are completely ignored?

**Comment by bonzai** [comment]
#800

**Comment by johanvanhelden** [comment]
Thanks for the workaround @bonzai - but this still feels like a bug to be honest.

I can not find this in the Nova documentation and it feels wrong that you have to define the singular label 2 times, once on the resource itself and once on the relationship field. I can not imagine this is intentional.

**Comment by gvsrepins** [comment]
The translations is also ignored in the `Details` and `Index` views.
The work around I come up with was to pass the translations direct to the view with the `withMeta` method:

```
BelongsTo::make('Activity')
                    ->singularLabel(__('Activity'))
                    ->nullable()
                    ->searchable()
                    ->withMeta([
                        'indexName' => __('Activity'),
                        'name' => __('Activity')
                    ]),
```

This is bad, but was the only way I could do it.  
If someone could point me to a better solution I'll be glad.

**Comment by davidhemphill** [comment]
There have been lots of improvements to Nova in terms of localization. If the issue persists, please post a new issue. Thanks!

**Comment by lichtner** [comment]
@davidhemphill still persist

**Comment by NickBelhomme** [comment]
I didn't have or noticed this before, but today it pops up in Nova 3.4.0 + laravel 7.6.2

**Comment by NickBelhomme** [comment]
reopening under https://github.com/laravel/nova-issues/issues/2526
