### ISSUE TITLE
is any way use default filter when the resource open

### ISSUE THREAD

**Issue by loveyuxiao** [laravel/nova-issues#848]
the model has Year filed ,i use filter to display 
```
class demo extends Filter
{
    public function apply(Request $request, $query, $value)
    {
        return $query->where('Year',$value);
    }
    public function options(Request $request)
    {
        return [
            '2018',
            '2017',
            '2016',
            '2015',  
        ];
    }
}
```
Has any way use the default filter just like 2018 when the resource list?

**Comment by dkulyk** [comment]
Add a global scope with where(year, date('Y')) in the indexQuery. And remove it in the filter.
This way added condition with the current year by default.

**Comment by loveyuxiao** [comment]
@dkulyk 
i set  global scope in resource indexQuery.
```
    public static function indexQuery(NovaRequest $request, $query)
    {
        return $query->where('Year',\date('Y'));
    }
```
and use the filter  
```
class demo extends Filter
{
    public function apply(Request $request, $query, $value)
    {
        return $query->where('Year',$value);
    }
    public function options(Request $request)
    {
        return [
            '2017',
        ];
    }
}
```
i think the  $query is $query->where('Year','2018')->where('Year','2017')....

how can i set the default Year and user can change it by filter?
just like this?
```
    public static function indexQuery(NovaRequest $request, $query)
    {
       // check  $request->fitler ==( class demo extends Filter)???
        if ($request->fitler==demo filter)
        {
            return $query->where('Year',\date('Y'));
        else
       {
            return $query;
        }
    }
```
Now how can i  get the $request->filter name and params.........

**Comment by dkulyk** [comment]
[This](https://github.com/dkulyk/eloquent-extensions/blob/master/src/Scopes/EnabledScope.php) is example of global scope of a query. You need to implements `Illuminate\Database\Eloquent\Scope` for using it.

In the resource:
```
public static function indexQuery(NovaRequest $request, $query)
{
    $query->withGlobalScope(DefaultYearScope::class, new DefaultYearScope());
}
```
And in the filter:
```
public function apply(Request $request, $query, $value)
{
    return $query->withoutGlobalScope(DefaultYearScope::class);
}
```

**Comment by aurawindsurfing** [comment]
HI @dkulyk and thx a lot for your suggestion! I have a problem implementing it however. I seem to be unable to use:

```
public function apply(Request $request, $query, $value)
    {
        return $query->withoutGlobalScope(UpcomingOnlyScope::class);
    }
```

in my filter. It works on the index, and it is applied correctly but for some reason disabling it does not work.

Any ideas what could be the cause for that?

**Comment by aurawindsurfing** [comment]
There is no:

```
public static function indexQuery(NovaRequest $request, $query)
{
    $query->withGlobalScope(DefaultYearScope::class, new DefaultYearScope());
}
```

There should ``addGlobalScope`` on the boot method of the model.

Then it works. Not sure why ->withGlobalScope does not work in this particular scenario.

**Comment by davidhemphill** [comment]
In your filter, specify the defaults by using the `default` method.

**Comment by aurawindsurfing** [comment]
Hi @davidhemphill by now you mean in the latest release right?

**Comment by aurawindsurfing** [comment]
Ok I changed the way I update to private repo.

Can you tell me how to implement it please? It does not seem to work for me:

```
/**
     * Set the default options for the filter.
     *
     * @return array
     */
    public function default()
    {
        return [
            'Upcoming'
        ];
    }

    /**
     * Get the filter's available options.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function options(Request $request)
    {
        return [
            'Upcoming' => date('Y-m-d h:m:s'),
            'All' => date('1900-01-01 00:00:00'),
        ];
    }
```

**Comment by davidhemphill** [comment]
the value on the right side is the key when it comes to filters:

```php
return [
    'Admin' => 'admin', // <-- this is the key
    'User' => 'user', // <-- this is the key
]
```

And so you would specify `admin` as the default.

**Comment by ndberg** [comment]
Just for future readers, this is now (v2.?) possible with adding a default to a filter:
```
    /**
     * Apply default on resource open 
     *
     * @return array|int|mixed
     */
    public function default()
    {
        return 3;
    }
```

**Comment by opanegro** [comment]
> There is no:
> 
> ```
> public static function indexQuery(NovaRequest $request, $query)
> {
>     $query->withGlobalScope(DefaultYearScope::class, new DefaultYearScope());
> }
> ```
> 
> There should `addGlobalScope` on the boot method of the model.
> 
> Then it works. Not sure why ->withGlobalScope does not work in this particular scenario.

thanks it works
