### ISSUE TITLE
Missing HTML-5 Validation when clicking "Update & Continue editing"

### ISSUE THREAD

**Issue by jwahdatehagh** [laravel/nova-issues#849]
- Laravel Version: 5.7
- Nova Version: 1.1.4
- PHP Version: 7.2.7

### Description:
I have a 'Number' field like the following:
```php
Number::make('Zoom Level')->min(1)->max(3)->step(0.01)
```
The HTML5-based field validation is applied when i click `Update {MODEL}` but not when i click the `Update & Continue Editing` button.

### Steps To Reproduce:
- Create Model with a `Number`-Field
- Add the above validation rules as an example and set an invalid input (e.g. `4`)
- Press `Update & Continue`

**Comment by alexbowers** [comment]
I dont think this is going to do the validation for you, those methods set properties on the number input, which are to do with the increment and decrement buttons that browsers put there, you have to do the validation separately.

https://nova.laravel.com/docs/1.0/resources/fields.html#number-field

**Comment by jwahdatehagh** [comment]
I understand that this is not the actual Laravel-based validation, but it applies HTML-attributes that are used for In-Browser validation when you click the `Update MODEL` button. 

The behaviour of both buttons is inconsistent and as you can check the html5-validity of the form via JS i suggest you fix that ux problem. Either both buttons 'submit the form' or none of them should.

**Comment by alexbowers** [comment]
I'll reopen this to get the feedback from @davidhemphill

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
