### ISSUE TITLE
Route Model Binding in resource tool routing

### ISSUE THREAD

**Issue by alexbowers** [laravel/nova-issues#851]
- Laravel Version: 5.7
- Nova Version: 1.1.4
- PHP Version: 7.1

### Description:
Route model binding does not seem to work in the routes file in a resource tool

### Steps To Reproduce:

Create a resource tool, in the routes.php create 

```
Route::get('/testing/{merchant}', function(\App\Merchant $merchant) { 
    dd($merchant);
});
```

You'll see that $merchant is empty, not reflecting the record ID that was sent to it.

If you remove the typehint `\App\Merchant` then you'll see that it has the correct ID there.

**Comment by davidhemphill** [comment]
Does adding the `Illuminate\Routing\Middleware\SubstituteBindings::class` middleware to your route solve the issue?

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
