### ISSUE TITLE
Asset Doesn't work on aliases folder or subdirectory

### ISSUE THREAD

**Issue by shirshak55** [laravel/nova-issues#852]
Problem:
there should be way to handle aliased folder like 

currently it generates url like this:
```
 <link rel="stylesheet" href="/nova-api/styles/nova-impersonate">
```

But how do i make it 

```
 <link rel="stylesheet" href="/aliased/folders/etc/nova-api/styles/nova-impersonate">
```

It don't obey \URL::forceRootUrl(config('app.url'));
 It is obvious because of following code

```
 @foreach(Nova::availableStyles(request()) as $name => $path)
        <link rel="stylesheet" href="/nova-api/styles/{{ $name }}">
    @endforeach
```

and also these line should be fixed
```
<link rel="stylesheet" href="{{ mix('app.css', 'vendor/nova') }}">
```

Currently layout file is not published so if i edit it will go away with future updates.

Possible Fix:
Can wrap with url helper so it obeys url force etc :)

Reason:
It is because i want to use '/' path for vue cli and laravel inside `/aliased/folders/` and CORS sucks because I don't want to double the latency(first request to cors and actual request)

Thanks

**Comment by davidhemphill** [comment]
I don't understand what problem you are having or what you're actually wanting here. Nova tools publish their assets in the correct place and are served via Nova anyways. Not sure what Vue-CLI (a separate tool) has to do with this either. Care to explain again?
