### ISSUE TITLE
Action Log label not localised/translated

### ISSUE THREAD

**Issue by techouse** [laravel/nova-issues#853]
- Laravel Version: 5.7.9
- Nova Version: 1.1.4
- PHP Version: 7.2.11

### Description:
The _Action Log_ label __"Actions"__ does not get localised according to the JSON lang file.

### Steps To Reproduce:
- use any non-English locale, for example German - `de`,
- download the German localisation JSON file [de.json](https://raw.githubusercontent.com/franzdumfart/laravel-nova-localizations/master/lang/de.json) into `resources/lang/vendor/nova`,
- create a dummy Nova Action and register it in the `User` Nova Resource,
- inside your `User` Model use the `Actionable` trait,
- open the `User` Nova Resource in Nova's administration panel and scroll down to the _Action Log_,
- the label should say __"Aktionen"__ but instead is says __"Actions"__.

**Comment by demency** [comment]
In /nova/src/ResolvesFields.php at line 58 returns a MorphMany::make. 

The first argumen must be modified to add `__('Actions')` helper.

Please add this in the follow update!

**Comment by demency** [comment]
Even more, if you want translate the nova actions status message you must add the translador helper to line 75 of ActionResource.php file. Like this `return ucfirst(__($value));`.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
