### ISSUE TITLE
BelongsToMany attach validation is assuming relation method name

### ISSUE THREAD

**Issue by Asikamiotis** [laravel/nova-issues#854]
- Laravel Version: 5.7
- Nova Version: 1.1.4
- PHP Version:7.1

### Description:
We have User model and Group model and belongsToMany relationship between them (pivot table with user_id,group_id fields), Nova lets me attach the same same Group to a User twice if the relationship method name on User Model is not defined with the method name 'groups' (plural of the Model name that is related to)  

### Steps To Reproduce:

App\User Model :

```
  public function moderating_groups()
    {
        return $this->belongsToMany('App\Group','group_moderator','user_id','group_id');
    }
```

App\Nova\User Resource:

  BelongsToMany::make('Moderating Groups','moderating_groups',Group::class);

Try to attach the same group two times on the user (Nova lets you do that) but if i change the relationship name to 'groups' like so:

App\User Model :
```
    public function groups()
    {
    return $this->belongsToMany('App\Group','group_moderator','user_id','group_id');
    }
```

App\Nova\User Resource:

```
  BelongsToMany::make('Moderating Groups','groups',Group::class);
```

Nova throws me an error when i try to attach the same group a second time on the same user
"This group is already attached."
I Think Nova should not guess that the name of the method that defines belongsToMany relatioship to be the plural name of Model name that you are trying to relate to

**Comment by Artiik** [comment]
The same here. Seems like Nova is smart enough to figure out relation name in the model, but sometimes it's not appropriate, and BelongsToMany field interface can't change this behavior from what I've seen. or am I wrong?

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!

**Comment by MuhammadSulman** [comment]
There are lots of issues those are unsupported, not available solutions etc.
