### ISSUE TITLE
Multiple relationships with the same model bug

### ISSUE THREAD

**Issue by Asikamiotis** [laravel/nova-issues#855]
- Laravel Version: 5.7
- Nova Version: 1.1.4
- PHP Version:7.1

### Description:
Trying to use two different relationships with the same model. There are User & Group models we have A belongsTo relationship and a belongsToMany between them if belongsToMany relationship field is defined after BelongsTo relationship when i am in the Attach (belongsToMany) group to a user i get Method Laravel\Nova\Fields\BelongsTo::buildAttachableQuery does not exist . But if i put  belongsToMany  before BelongsTo  it works fine

**Comment by dkulyk** [comment]
[Patch](https://gist.github.com/dkulyk/a5add2810ca046a30864ca07fc6775c9): Filter fields with attachable relations.

**Comment by dkulyk** [comment]
Duplicate #425

**Comment by bonzai** [comment]
Duplicate of #425

**Comment by dillingham** [comment]
I just experienced this and putting BelongsToMany above BelongsTo worked 1.3.0
