### ISSUE TITLE
Ability to configurable auth layout title

### ISSUE THREAD

**Issue by pavinthan** [laravel/nova-issues#858]
- Laravel Version: 5.7.9
- Nova Version: 1.1.4
- PHP Version: 7.2.8

### Description:
It's hardcoded now, please make it configurable with `{{ Nova::name() }}`

`vendor/laravel/nova/resources/views/layout.blade.php` -> `{{ Nova::name() }}`
`vendor/laravel/nova/resources/views/auth/layout.blade.php` -> *Laravel Nova*

**Comment by bonzai** [comment]
Duplicate of #522.
