### ISSUE TITLE
Number Field Validation: 'min' rule treated as string

### ISSUE THREAD

**Issue by dwyer14** [laravel/nova-issues#859]
- Laravel Version: 5.7.9
- Nova Version: 1.1.4
- PHP Version: 7.2

### Description:
When validating a Number field, the `min` rule isn't applied correctly. Instead of evaluating the value as a number, it treats it like a string. This is apparent in the error message returned.

Here's the field definition on the resource:
```
Number::make('Minimum Donation')
  ->min(5)->max(1000)->step(0.01)
  ->rules('required','min:5')
  ->displayUsing(function ($amount) {
    return '$' . $amount;
  }),
```

Here's a screenshot of the error message:
![image](https://user-images.githubusercontent.com/13950848/47196069-792bd800-d324-11e8-99b1-0f9bcfff1012.png)

### Steps To Reproduce:
Recreate the field definition outlined above, pass in a value greater than 5.

**Comment by RonMelkhior** [comment]
Add the `numeric` rule before you check for `min`. Nova uses the regular Laravel validation rules.

**Comment by dwyer14** [comment]
Ahh, derp—right you are. I knew that and have used it before on regular Laravel stuff; forgot about needing it in Nova as well. Thanks!
