### ISSUE TITLE
Dropdown arrows are missing on Firefox and Safari

### ISSUE THREAD

**Issue by bonzai** [laravel/nova-issues#86]
- Nova version: 1.0.5
- Firefox version: 61.0.2
- Safari version: 11.1 (13605.1.33.1.2)

### Description:

Dropdown arrows are missing on Firefox and Safari:

![nova_dropdown_arrow](https://user-images.githubusercontent.com/98191/44554331-ce86a700-a730-11e8-9276-0d87e0d5b5d5.png)

**Comment by BengtHagemeister** [comment]
Same issue then here #196

**Comment by dillingham** [comment]
Related: https://github.com/laravel/nova-issues/issues/86 https://github.com/laravel/nova-issues/issues/170 https://github.com/laravel/nova-issues/issues/533

**Comment by dillingham** [comment]
Related: https://github.com/laravel/nova-issues/issues/86 https://github.com/laravel/nova-issues/issues/170 https://github.com/laravel/nova-issues/issues/533 https://github.com/laravel/nova-issues/issues/196 https://github.com/laravel/nova-issues/issues/952

**Comment by davidhemphill** [comment]
This has been fixed and will be included in an upcoming release. Removing arrows to make the menus more streamlined.
