### ISSUE TITLE
Check authorization before redirecting to resource detail after creating

### ISSUE THREAD

**Issue by hafez-bsup** [laravel/nova-issues#862]
- Laravel Version: 5.7.9
- Nova Version: 1.1.4
- PHP Version: 7.2

### Description:
After creating a resource, it redirects to resource's detail without checking if the user is authorized to view it. on `nova/resources/js/views/Create.vue` line 109:

```
this.$router.push({
    name: 'detail',
    params: {
        resourceName: this.resourceName,
        resourceId: response.data.id,
    },
})
```

I think you should replace it with something like this:

```
if (authorizedToView) {
    this.$router.push({
        name: 'detail',
        params: {
            resourceName: this.resourceName,
            resourceId: response.data.id,
        },
    })
}
else {
    this.$router.push({
        name: 'index',
        params: {
            resourceName: this.resourceName
        }
    })
}
```

It would be also great if you implement a way to make it possible to customize the redirection after creating (index or detail).

### Steps To Reproduce:
1. Make `create` method of resource's model policy return false.
2. create a resource and, it redirect to resource's detail and error 403 appears.

**Comment by dillingham** [comment]
Related https://github.com/laravel/nova-issues/issues/538 https://github.com/laravel/nova-issues/issues/604 https://github.com/laravel/nova-issues/issues/797 https://github.com/laravel/nova-issues/issues/862

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
