### ISSUE TITLE
[FR] Ability to restrict direct routing to resource

### ISSUE THREAD

**Issue by hafez-bsup** [laravel/nova-issues#863]
Edited By @alexbowers 
------
Currently you can restrict whether a resource is directly viewable in the sidebar, but you can still go to the route directly by going to that URL.

This feature request will allow for restricting the direct route access to the resource, but still allow it to be included in other resources pages (as a HasMany etc)

------

Original below:

- Laravel Version: 5.7.9
- Nova Version: 1.1.4
- PHP Version: 7.2

### Description:
I have 2 resources 'foo' and 'bar', Resource 'foo' hasMany 'bar', so it got listed on 'foo' resource's detail screen. I want to disable resource 'bar' for navigation, so I've override these:

```
/**
 * Indicates if the resource should be displayed in the sidebar.
 *
 * @var bool
 */
public static $displayInNavigation = false;

/**
 * Determine if this resource is available for navigation.
 *
 * @param  \Illuminate\Http\Request  $request
 * @return bool
 */
public static function availableForNavigation(Request $request)
{
    return false;
}

```

It gets hide from navigation but it is still available on its routes: `example.com/resources/bars`

### Steps To Reproduce:
1. disable a resource for navigation
2. it is still available via it route: `example.com/resources/resource-name`

**Comment by alexbowers** [comment]
Thats a separate feature request. As far as i'm aware, you can't disable routing currently.

**Comment by alexbowers** [comment]
You could probably use policy gates to lock down functionality, so if somebody goes there they are effectively locked and unable to do anything, but I dont think you can fully stop its routing

**Comment by hafez-bsup** [comment]
As I said I can't disable viewAny policy because i'm listing this resource on the other resource's detail page. Should I resend this issue via email for feature request or you already considered this issue?

**Comment by alexbowers** [comment]
I can reopen this as a feature request if you like.

**Comment by alexbowers** [comment]
Reopened and modified original post

**Comment by johnanthonyeletto** [comment]
I found a solution to this problem. I'm using this code in `NovaServiceProvider.php`

```
     /**
     * Register the application's Nova resources.
     *
     * @return void
     */
    protected function resources()
    {
        $currentUser = \Auth::user();

        if ($currentUser->type == 'admin') {
            return Nova::resourcesIn(app_path('Nova'));
        }

        return null;
    }
```

Here I'm restricting access to all resources, but you can use a similar method to restrict access to individual resources.

See: [https://nova.laravel.com/docs/1.0/resources/#registering-resources](https://nova.laravel.com/docs/1.0/resources/#registering-resources)

Using this method does not return an error, it just returns a blank screen, but that's good enough for me. This is what I get when I type the route directly as a non-admin user:
![image](https://user-images.githubusercontent.com/18408818/52384138-31070180-2a4a-11e9-910d-79965ec1078d.png)

**Comment by dillingham** [comment]
Route::redirect()

**Comment by johnanthonyeletto** [comment]
> Route::redirect()

I like what you're thinking @dillingham 

I can't seem to get that working though.

**Comment by dillingham** [comment]
@johnanthonyeletto never-mind, only works when you hit the url directly

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
