### ISSUE TITLE
HasMany and HasOne Fields must be Deletable

### ISSUE THREAD

**Issue by hafez-bsup** [laravel/nova-issues#866]
- Laravel Version: 5.7.9
- Nova Version: 1.1.4
- PHP Version: 7.2

### Description:
If Post resource has many Comments, deleting post should causes deletion of all comments. I think `HasOne` and `HasMany` fields must be `Deletable` (like `BelongsToMany` and `MorphToMany`).

### Steps To Reproduce:
1. add a `HasMany` field to the resource.
2. delete a parent record, child records don't get deleted (and causes error if you're using foreign key reference on the database/migration: `local.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails`)

**Comment by davidhemphill** [comment]
This isn't the job of Nova. Lots of use-cases where you'd want the old models to stay intact.

**Comment by hafez-bsup** [comment]
@davidhemphill So why you declared `BelongsToMany` and `MorphToMany` deletable?
One can add or remove `prunable`  method to keep the old models.
