### ISSUE TITLE
Using the `displayUsing` method on File field causes its download to fail

### ISSUE THREAD

**Issue by hafez-bsup** [laravel/nova-issues#868]
- Laravel Version: 5.7.9
- Nova Version: 1.1.4
- PHP Version: 7.2

### Description:
Using `displayUsing` on `File` field causes its download to fail.

```
File::make('File', 'path')
    ->disk('local')
    ->path('files/samples')
    ->storeOriginalName('name')
    ->prunable()
    ->displayUsing(function($path) {
        return $this->name;
    })
    ->rules('required', 'file'),
```
Downloading works fine when I remove `displayUsing`.

### Steps To Reproduce:
1. customize `File` field with `displayUsing` method.
2. try to download the file on 'detail' screen, it fails.

**Comment by ConnorVG** [comment]
To get around it, just pass it a custom working `download` function.

IE, for a project I'm working on we had to do this:
```
File::make('Source', 'path')
  ->disk('internal-stash')
  ->displayUsing(function () {
    return 'keys.txt';
  })
  ->download(function () {
    return Storage::disk('internal-stash')->download($this->path, 'keys.txt');
  }),
```

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
