### ISSUE TITLE
Grammatical issue on 404 error page

### ISSUE THREAD

**Issue by shane-smith** [laravel/nova-issues#869]
- Laravel Version: 5.6.39
- Nova Version: 1.1.4
- PHP Version: 7.1.x

### Description:

The 404 error page includes a grammatical issue: "The page your were trying to view" should instead be "The page you were trying to view".

See highlighted word below:
![image](https://user-images.githubusercontent.com/943942/47263523-ace84700-d54a-11e8-85bb-909674db6fb9.png)

### Steps To Reproduce:

Either try loading a resource with an invalid ID, or directly visit the `/nova/404` route.

**Comment by bonzai** [comment]
This was fixed in version 1.1.9.

https://nova.laravel.com/releases
