### ISSUE TITLE
Set file storage visibility to public or private

### ISSUE THREAD

**Issue by NSpehler** [laravel/nova-issues#87]
Please add an option to set the file visibility to public or private when using remote disks.

I'm guessing this would be similar to the File Visibility section of the Laravel documentation: https://laravel.com/docs/5.6/filesystem

When I'm using the following, uploaded files are set to private on DigitalOcean (would be the same using `s3` I suppose):

`Avatar::make('Avatar')->disk('spaces')`

**Comment by davidhemphill** [comment]
This is configurable in the `filesystems.php` in your config folder.

**Comment by nickkuijpers** [comment]
Hi,

Maybe to give some direction, i have got it working by doing this.

```
Image::make('Logo', 'logo')                
                ->store(function (Request $request, $model) {                    
                    $name = $request->logo->getClientOriginalName();                    
                    $savedName = Storage::disk('s3')->putFileAs('/assets/platforms', $request->logo, $name, 'public');                    
                    return [
                        'logo' => $savedName,
                    ];
                }),       
```

Currently not doing anything with the asset() function, wil do that when creating the frontend. I got it working in the nova backend atm.

**Comment by coccoinomane** [comment]
Hello!

I am in need of having a different visibility setting based on the specific File field.
To accomplish this I have defined separate `s3_public` and `s3_private` disks in `filesystems.php`.
Is this the way to go?

Cheers,
Guido

**Comment by dniccum** [comment]
I was able to figure this out by using an invokable. Here is a quick write up on how I did it:

https://blog.dniccumdesign.com/modify-image-permissions-on-s3-file-uploads-within-laravel-nova/

**Comment by igorsgm** [comment]
You can achieve it by adding the `visibility' => 'public'` in your disk in the `filesystems.php` file. For instance:

```
        's3' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'region' => env('AWS_DEFAULT_REGION'),
            'bucket' => env('AWS_BUCKET'),
            'url' => env('AWS_URL'),
            'visibility' => 'public', // this line
        ],
```
