### ISSUE TITLE
BelongTo Field Label Not Respected

### ISSUE THREAD

**Issue by nickpoulos** [laravel/nova-issues#870]
- Laravel Version: 5.7.9
- Nova Version: 1.1.4
- PHP Version: PHP 7.2.9-1+ubuntu18.04.1+deb.sury.org+1

### Description:
Trying to create a BelongsTo field labeled 'Author' but based on user() relationship.   It still seems to be using the name of the method for the label. 

### Steps To Reproduce:

**1. Create post migration**

 `Schema::create('posts', function (Blueprint $table) {`
            `      $table->increments('id');`
            `    $table->integer('user_id')->unsigned();`
            `    $table->foreign('user_id')->references('id')->on('users');`  
             `  $table->string('title');`
`}`

**2. Add In Post Model**

`public function user()`
    `{`
        `return $this->belongsTo('App\User');`
   ` }`

**3. Add In User Model**

`public function posts()`
   ` {`
        `return $this->hasMany('App\Post');`
    `}`

**4. Add In Nova Resource Post fields() function**
BelongsTo::make('Author', 'user');

This returns an error  "Class App\Nova\Author Not Found" 

When changing the line to `BelongsTo::make('Author', 'user', 'App\Nova\User');`, the error resolves, and the placeholder of the select box says "Choose Author", however the field label to the left still reads "User".

**Comment by bonzai** [comment]
#800

**Comment by arjasco** [comment]
I also mentioned this for point no.2 on my now closed issue #867

**Comment by davidhemphill** [comment]
This has been fixed and will be included in an upcoming release.
