### ISSUE TITLE
Hide certain Rows

### ISSUE THREAD

**Issue by eppak** [laravel/nova-issues#871]
Hello,
i see that a field can bi hidden, but if i want to hide an entire row for some kind of user, how can be accomplished?

**Comment by dkulyk** [comment]
You must to override the indexQuery function and extend query with check for user access.

**Comment by albalooshi** [comment]
@eppak
Just adding the documentation to what @dkulyk said.
https://nova.laravel.com/docs/1.0/resources/authorization.html#index-filtering

**Comment by davidhemphill** [comment]
Modify the `indexQuery`.
