### ISSUE TITLE
Distinct not returning distinct results in Trend Metric

### ISSUE THREAD

**Issue by GigaMick** [laravel/nova-issues#875]
- Laravel Version: 5.6.7
- Nova Version: 1.1.4
- PHP Version: 7.1.8

### Description:

I am trying to create a trend metric but the results being returned are not distinct

### Steps To Reproduce:

Here's my code:
```
 public function calculate(Request $request)
    {
        $builder = order::query()->select('cook_id')->distinct();
        return $this->countByDays($request, $builder)->showLatestValue();
    }
```

I am seeing for today's value "6" when it should be "4" - yes there are 6 rows from today but 3 of them have the same ID and thus the "distinct" call should only count them once.

**Comment by davidhemphill** [comment]
You're going to need to build the result manually.
