### ISSUE TITLE
File deleted from Nova admin panel not automatically removed from storage

### ISSUE THREAD

**Issue by thibaultlavoisey** [laravel/nova-issues#877]
- Laravel Version: 5.7.9
- Nova Version: 1.1.4
- PHP Version: 7.2.8

### Description:

According to the [documentation](https://nova.laravel.com/docs/1.0/resources/file-fields.html#customization):

> When a file is deleted from the Nova administration panel, Nova will automatically remove the underlying file from storage and insert NULL into the field's associated column.

However, it's not working on a fresh installation using the latest versions of Laravel and Nova: NULL is inserted into the field's associated column but the underlying file isn't removed from storage.

### Steps To Reproduce:

* Add a `profile_picture` column to the `2014_10_12_000000_create_users_table.php` migration:

```
$table->string('profile_picture')->nullable();
```

* Add an `Image` field to the `User` resource:

```
// app/Nova/User.php

class User extends Resource
{
    ...

    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [
            ...

            Image::make('Profile Picture', 'profile_picture')
                ->disk('public'),

            ...
    }

    ...
}
```

* Edit a user, add a profile picture then remove it using Nova admin panel. 

---

Expected result: NULL in database, file removed from storage
Current result: NULL in database, file not removed from storage

**Comment by XGhozt** [comment]
Not sure how I feel about having Nova automatically deleting files. If that is added, I'd hope we could optionally include that to the field. You can easily delete the orphaned file(s) within an Observer.

**Comment by devotoare** [comment]
"Files also have a prunable() method you can chain onto their definitions, which means that if I delete the entry in the database, Nova should delete its backing file as well"

source: https://mattstauffer.com/blog/introducing-laravel-nova-a-tool-for-building-admin-panels-and-custom-cmses/

**Comment by taylorotwell** [comment]
It's not marked as prunable.

**Comment by thibaultlavoisey** [comment]
@XGhozt @devotoare @taylorotwell Thanks all for your answers! :) 

Maybe I'm wrong, but marking a `File` field as `prunable` will delete the backing file if the associated model is deleted, no?

However, the use case I'm trying to explain is deleting the file **without** deleting the associated model:

<img width="825" alt="screenshot 2018-10-24 at 10 41 21" src="https://user-images.githubusercontent.com/2022117/47418010-89efaa00-d779-11e8-974d-890c96fabbc9.png">

1. Clicking on "Delete" will trigger the method `handle` of the controller `Laravel\Nova\Http\Controllers\FieldDestroyController`.
2. The controller method retrieves the field to be deleted and then triggers the method `forRequest` of the class `Laravel\Nova\DeleteField`.
3. This method calls the `deleteCallback` of the field then updates the model accordingly.
4. The default `deleteCallback` of the `File` field (can be seen in `Laravel\Nova\Fields\File@__construct`) is to delete the backing file from storage.

Do I miss something?

Thanks :)

**Comment by jimbojsb** [comment]
@taylorotwell I think this is a bug, or at best, undocumented behavior. Even with `prunable` it doesn't seem like it is possible to null out a file field and have the underlying media removed from disk.

**Comment by ekazda** [comment]
@thibaultlavoisey @taylorotwell @jimbojsb Was this nullable file/image issue ever resolved? I'm noticing this behavior in Nova 4 where it seems like the system simply does not allow for nullable image fields, even if they are set to nullable. The interface even says the file has been deleted, but the file is retained and the data for the field does not change to NULL.
