### ISSUE TITLE
Ability to alter images after upload (resize, crop, fit, etc)

### ISSUE THREAD

**Issue by lluisandreu** [laravel/nova-issues#879]
Hello, 

It would be great to have the possibility to alter images after upload using Intervention Image of another library. 

Is there a way to use Intervention with the Image field right now?

Thanks, 

Lluis.

**Comment by lluisandreu** [comment]
I was able to do it in the Image store() method like this: 

`use Intervention\Image\ImageManagerStatic as IMG;`

```
$originalName = $request->image->getClientOriginalName();
$image = IMG::make($request->image)->fit(200)->encode('jpg',90);
Storage::disk('public')->put($originalName, $image);
return $originalName;
```

**Comment by davidhemphill** [comment]
That's what the `store` method is for. 👍
