### ISSUE TITLE
BelongsToMany field rules not validating submission

### ISSUE THREAD

**Issue by jasonlav** [laravel/nova-issues#880]
- Laravel Version: 5.6.39
- Nova Version: 1.1.4
- PHP Version: 7.2.1

### Description:
BelongsToMany field rules not validating submission.

### Steps To Reproduce:
```
BelongsToMany::make('Content')->fields(function () {
    return [
        Number::make('Sort Order')->rules('required'),
    ];
})->searchable()->rules('required'),
```

The Sort Order field is validated. The Belongs to many is not.

**Comment by carloshc** [comment]
In my case in `Users` resource:

```php
BelongsToMany::make('Cursos do Polos', 'cursopolo', 'App\Nova\CursoPolo')
                                ->rules('required',new CursoPoloUserRule($request->cursopolo,$request->id))
                                ->singularLabel('Curso de um Polo'),
```

**Comment by Crazymodder** [comment]
Are there any news on this issue? I got the same problem as described by @jasonlav.

**Comment by christophrumpel** [comment]
I'm experiencing the same problem. Tried to check why the rules do not end up in the `ResourceAttachController` but no success yet.

**Comment by carloshc** [comment]
Any news on this issue?

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
