### ISSUE TITLE
Run a action in computed-fields

### ISSUE THREAD

**Issue by loveyuxiao** [laravel/nova-issues#883]
i use the computed-fields
```
Text::make('Run Action', function () {
  return '<i class="fas fa-ad"></i>';
})->asHtml()
//how to run the exist acion?
->RunAction(DemoAction:class),
```
how can i run the a action? 
only use the custom field?

**Comment by davidhemphill** [comment]
Make a custom field that runs the requested action with the selected resource via ajax. Other than that, use the built-in functionality.
