### ISSUE TITLE
Error when updating a record with a image field

### ISSUE THREAD

**Issue by UdyW** [laravel/nova-issues#885]
- Laravel Version: 5.7.9
- Nova Version: 1.1.5
- PHP Version:

When updating a record with a image/ file field it gives "The image field is required." error even though the image is available. 
<img width="1333" alt="screenshot 2018-10-24 at 09 44 09" src="https://user-images.githubusercontent.com/6145036/47418952-1480db00-d773-11e8-9c94-096eb57b529e.png">
Code 

`   public function fields(Request $request)
    { 
        return [
            ID::make()->sortable(),

            Text::make('Title')
                ->sortable()
                ->rules('required', 'max:255'),

            Text::make('Header title')
                ->sortable()
                ->rules('required', 'max:254'),

            Text::make('Header caption')
                ->rules('required', 'string', 'min:6'),

            Image::make('Banner Image')
                ->rules('required'),

            Textarea::make('Content')
                ->rules('string', 'min:6'),

            Text::make('Slug')
                ->resolveUsing(function($slug){
                    return str_slug($slug);
                }),
        ];
    }`

1.Save image with the record
2.Select the record to edit
3.Try updating the record changing something other than the image field.

Your urgent attention is much appreciated. Please consider this as highest priority since this is a major issue.

**Comment by UdyW** [comment]
Hi,
Do you have any updates on this one please? 
Please let me know as soon as you get any kind of solution.

**Comment by alexvolik** [comment]
The same issue
```
   Image::make('Post Image', 'image')->disk('public')
                ->rules('required')
                ->updateRules('nullable'),
```

**Comment by fabio998** [comment]
same issue, please fix it thank you

**Comment by elrufoelrufo** [comment]
Hello, 

I avoid this error with the following code. Hope it's help to you : 

```php
                ->updateRules('',function ($attribute, $value, $fail) use ($request) {
                    $model = $this->resource->find($request->route('resourceId'));
                    if (empty($value) && empty($model->$attribute)) {
                        $fail(__(':Attribute is required.', ['attribute' => __($attribute)]));
                    }
                }),

```

**Comment by voidgraphics** [comment]
I am also experiencing this issue. A fix is quite urgent. Thanks

**Comment by elrufoelrufo** [comment]
@voidgraphics , I believe you are using rules() and updateRules methods , you should use creationRules() and updateRules, something like this : 

``` php
                Image::make('Banner Image')
                ->creationRules('required')
                ->updateRules('',function ($attribute, $value, $fail) use ($request) {
                    $model = $this->resource->find($request->route('resourceId'));
                    if (empty($value) && empty($model->$attribute)) {
                        $fail(__(':Attribute is required.', ['attribute' => __($attribute)]));
                    }
                })

```

**Comment by NioTeX** [comment]
#353

**Comment by chescos** [comment]
Same issue here. Also, how to remove the "Delete" button? If the column is not nullable, an exception is thrown when Nova tries to set the column to `null`.

**Comment by Gaia-Nutrition** [comment]
The workaround by @elrufoelrufo did not work for me as the attribute is not present in the update request. Therefore, the custom `updateRules` are never called.

Here is what I have got working now:

Nova field rules:
```php
Avatar::make(__('Menu Icon'), 'image_url')
	->disk('public')
	->creationRules('required', 'image')
	->updateRules('file_required:categories,{{resourceId}}'),
```

Custom **implicit** validator extension in the `boot()` function of my `AppServiceProvider.php`
```php
Validator::extendImplicit('file_required', function ($attribute, $value, $parameters, $validator) {
	$tableName = $parameters[0];
	$resourceId = $parameters[1];
	$model = \DB::table($tableName)->find($resourceId);
	return !empty($value) || !empty($model->$attribute);
});
```
Usage:
Replace `TABLE_NAME` in the rule below with the name of the table where your file/image/avatar attribute is being saved to (Usually this is your model's table)

`file_required:TABLE_NAME,{{resourceId}}`

**Comment by Jack97** [comment]
In my opinion, the best way to do this is to set `deletable` on the Image to false - which hides the delete button - then make it required in the `creationRules`.

```php
Image::make('Image')
    ->deletable(false)
    ->creationRules('required'),
```

**Comment by parcle** [comment]
Guys is a pay product ... we can get attention on this issue?

**Comment by douglaszaltron** [comment]
+1

**Comment by ilikourou** [comment]
Having the same issue here too.

**Comment by UdyW** [comment]
I'm beginning to think Laravel has stopped Nova development work. No updates/ releases/ fixes for quite a while.

**Comment by voidgraphics** [comment]
@UdyW not sure what you mean

![Capture d’écran 2019-04-01 à 15 20 30](https://user-images.githubusercontent.com/9298484/55330613-bd093880-5491-11e9-99ee-f1ce60c2339e.png)

That was 5 days ago

**Comment by enrikas** [comment]
+1

**Comment by davidhemphill** [comment]
OP's code is incorrect. You need to provide different rules for creation and deletion.

@UdyW I haven't been fired as far as I know, lol.

**Comment by tanmuhittin** [comment]
Here is what I used

```
->updateRules(Rule::requiredIf(function ($attribute, $value) use ($request) {
                    $model = $this->resource->find($request->route('resourceId'));
                    return (empty($value) && empty($model->$attribute));
                }),'image')
```

**Comment by tannerkozlowski** [comment]
> Here is what I used
> 
> ```
> ->updateRules(Rule::requiredIf(function ($attribute, $value) use ($request) {
>                     $model = $this->resource->find($request->route('resourceId'));
>                     return (empty($value) && empty($model->$attribute));
>                 }),'image')
> ```

It's saying "App\Nova\Rule Not Found"

**Comment by threeaccents** [comment]
Why is this closed if it hasn't been resolved?

**Comment by geodeveloper** [comment]
@davidhemphill this is issue still exists in latest Laravel Nova 3.x with Laravel 7.x.

**Comment by tannerkozlowski** [comment]
When will it be fixed? :)

**Comment by UdyW** [comment]
This bug is un resolved for nearly a year now. Thoroughly disappointed with this. And their dev's just close the issue with out fixing or any explanation :D

**Comment by threeaccents** [comment]
@UdyW You would think a product generating millions of dollars a year would maybe put a little better emphasis on customer support.

**Comment by Dhofca** [comment]
`Image::make('Avatar', 'avatar')
                ->creationRules(['required'])
                ->updateRules(Rule::requiredIf(function ($attribute, $value) use ($request) {
                    $model = $this->resource->find($request->route('resourceId'));
                    return (empty($value) && empty($model->$attribute));
                }), 'avatar'),`

@tanmuhittin's reply is correct, but you need use `->creationRules()` instead of `->rules()`

**Comment by davidhemphill** [comment]
@UdyW @threeaccents What doesn't work for you with the answer I gave?

**Comment by shaffe-fr** [comment]
I created a custom validation rule class to handle that case:
```php
<?php

namespace App\Rules;

use Illuminate\Contracts\Validation\ImplicitRule;
use Illuminate\Contracts\Validation\Rule;
use Illuminate\Database\Eloquent\Model;

class RequiredImage implements Rule, ImplicitRule
{
    protected ?Model $model;
    protected ?string $field;

    public function __construct(?Model $model, ?string $field = null)
    {
        $this->model = $model;
        $this->field = $field;
    }

    public function passes($attribute, $value): bool
    {
        $this->field ??= $attribute;

        if ($value) {
            return true;
        }

        if (empty($this->model->exists)) {
            return false;
        }

        // return $this->model->hasMedia($attribute); for Spatie's Media library
        return (bool) $this->model->{$attribute};
    }

    public function message(): string
    {
        return __('validation.required', ['attribute' => $this->field]);
    }
}
```

**Comment by ravindurajakaruna** [comment]
> I created a custom validation rule class to handle that case:
> 
> ```
> <?php
> 
> namespace App\Rules;
> 
> use Illuminate\Contracts\Validation\ImplicitRule;
> use Illuminate\Contracts\Validation\Rule;
> use Illuminate\Database\Eloquent\Model;
> 
> class RequiredImage implements Rule, ImplicitRule
> {
>     protected ?Model $model;
>     protected ?string $field;
> 
>     public function __construct(?Model $model, ?string $field = null)
>     {
>         $this->model = $model;
>         $this->field = $field;
>     }
> 
>     public function passes($attribute, $value): bool
>     {
>         $this->field ??= $attribute;
> 
>         if ($value) {
>             return true;
>         }
> 
>         if (empty($this->model->exists)) {
>             return false;
>         }
> 
>         // return $this->model->hasMedia($attribute); for Spatie's Media library
>         return (bool) $this->model->{$attribute};
>     }
> 
>     public function message(): string
>     {
>         return __('validation.required', ['attribute' => $this->field]);
>     }
> }
> ```
> 
> And in the resource:
> 
> ```
> Image::make('Avatar', 'avatar')->rules(new RequiredImage($this->resource);
> ```

This worked for me :) Thanks!

**Comment by riptin** [comment]
2022 and this issue still isn't fixed.

**Comment by ivanmijatovic89** [comment]
You can use `Rule::requiredIf` to check if another field must be present...

Example:

```bash
public function fields(Request $request)
    {
        $data = $request->toArray();

        return [
            Images::make('Image A', 'image_a')
                ->rules(
                    Rule::requiredIf(isset($data['__media__']) && isset($data['__media__']['image_b']))
                ),
            Images::make('Image B',  'image_b')
                ->rules(
                    Rule::requiredIf(isset($data['__media__']) && isset($data['__media__']['image_a']))
                ),
       ];
```
