### ISSUE TITLE
Sidebar navigation - empty 'Other' menu

### ISSUE THREAD

**Issue by iHazzam** [laravel/nova-issues#886]
- Laravel Version: 5.7.9
- Nova Version: 1.1.4
- PHP Version: 7.1.3

### Description:

If you have started to use `public static $group = 'GroupName';` on any resources, you get 'OTHER' as a menu option for the ones with no defined group.

Resources which have the property ` public static $displayInNavigation = false;` are still being included in the check whether to display OTHER 

`@foreach(Nova::groupedResources(request()) as $group => $resources)
        @if (count($resources) > 0)`

so either you have to put these resources in a group even though they won't be displayed, or you get 'OTHER' with no resources in it on the sidebar.

### Steps To Reproduce:

Add a group to any resource, add displayInNavigation = false to all other resources but do not add groups to them

**Comment by bonzai** [comment]
#618
