### ISSUE TITLE
Modal with DateTime field disappear when click on hour or minute input

### ISSUE THREAD

**Issue by Giactan** [laravel/nova-issues#887]
- Laravel Version: #.#.#
- Nova Version: 1.1.5
- PHP Version:

### Description:
A model with DateTime field will disappear when you click on hour or minute input

### Steps To Reproduce:
<img width="951" alt="screen shot 2018-10-24 at 6 44 13 pm" src="https://user-images.githubusercontent.com/31847606/47428255-e9bb7480-d7bc-11e8-8bbf-c71eeda2b9a9.png">

**Comment by demency** [comment]
I'm facing with the same bug...

Checking with vue dev tools and the modal close event is triggered.

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍
