### ISSUE TITLE
BelongsTo search filtering

### ISSUE THREAD

**Issue by RespectPick** [laravel/nova-issues#888]
I have one resource Championship with 3 belongsTo methods which belongs to User resource

            BelongsTo::make('Main judge', 'mainJudge', User::class)
                ->onFormsAndDetail()
                ->searchable(),

            BelongsTo::make('Main secretary', 'mainSecretary', User::class)
                ->onFormsAndDetail()
                ->searchable(),

            BelongsTo::make('Judge operator', 'judgeOperator', User::class)
                ->onFormsAndDetail()
                ->searchable(),

I have to filter all of them when during the search because all of them have different roles.

But there is no possibility to add additional conditions to query

**Comment by davidhemphill** [comment]
Customize the relation method on the model to exclude the correct ones.

**Comment by leith** [comment]
I know this is closed, but for anyone who arrives at this, Nova now has this as of 4.19.0 in the form of `relatableQueryUsing()`, which takes a closure parameter that allows you to modify the query building on the way through.

Docs: https://nova.laravel.com/docs/4.0/resources/relationships.html#relatable-query-filtering
