### ISSUE TITLE
Date format missing from create/edit screens

### ISSUE THREAD

**Issue by arjasco** [laravel/nova-issues#889]
New issue as advised on #867

- Laravel Version: 5.7.9
- Nova Version: 1.1.4
- PHP Version: 7.2.3

### Description:
Setting a date format only reflects on index and details screen. 

This is confusing, especially those from countries that don't use the Y-M-D format. 

While building the form elements i genuinely thought the ->format() method was doing nothing till I noticed it only applies on the index/details screens.

![](https://user-images.githubusercontent.com/8780549/47255094-68ce4700-d463-11e8-91a3-de2a2b15536f.png)

### Steps To Reproduce:

```php
Date::make('Date')->format('DD/MMM/YYYY')->sortable(),
```
Format won't be available on create and edit screens.

**Comment by arjasco** [comment]
Been advised this will be fixed in next release 👍

**Comment by christophrumpel** [comment]
Was it?
