### ISSUE TITLE
Feature Request: Optional relationships

### ISSUE THREAD

**Issue by JapSeyz** [laravel/nova-issues#89]
Mark relationships as optional, which allows us to select an empty value.

Handy for orders that may have a coupon etc.

Adding this to the relation fields, BelongsTo etc..

```php
// BelongsTo.php
    /**
     * Indicates if this relationship is optional.
     *
     * @var bool
     */
    public $optional = false;
```

```html
<!-- BelongsToField.vue -->

<option value="" :disabled="isOptional" selected>{{__('Choose')}} {{ field.name }}</option>

...
Computed properties
...

    /**
     * Determine if the related resources is optional
     */
    isOptional() {
        return this.field.optional
    },
```

This would allow us to set the relationship to null when it's not applicable.

**Comment by petericebear** [comment]
Was looking for this also. I have a nullable belongsTo field. Can a null be a value?

**Comment by dillingham** [comment]
This would be solved by removing disabled from the first select option

BelongsToField.vue line 43

<option value="" disabled="disabled" selected="selected">Choose User</option>
And letting an empty value store as null for nullable relationships
Essentially undoing the selection made, that's how I expected it to work personally.

**Comment by XGhozt** [comment]
@davidhemphill -- is this fixed in v1.1.7?

It says: `Support for nullable BelongsTo and MorphTo relationships.`

I still cannot select a nullable value. It says `Choose [model]` and the field is disabled. If edit the field in browser tools and set it to blank/null then it doesn't actually save the value. There's no way to unset a belongsto field. I can save the page without selection an option, but once I select an option I cannot unselect it.

**Comment by stevelacey** [comment]
@davidhemphill when? Is there an interim solution?

**Comment by cam-pgp** [comment]
Was this resolved? Currently when I make a belongsTo field **nullable** it doesn't allow me to deselect the field if it has already been assigned a value:

BelongsTo::make('Campaign')->nullable()

![screen shot 2018-11-26 at 4 09 43 pm](https://user-images.githubusercontent.com/43966192/49049905-daea2800-f195-11e8-8827-6c4fdf561f0e.png)

If I made the field searchable,  I'm able to deselect it but it won't POST with that empty value, it just restores the previous value. 

BelongsTo::make('Campaign')->nullable()->searchable()   

Is there some part of this implementation I'm missing or is this still under-development?

**Comment by julianpoma** [comment]
@cam-pgp Be sure to pubish the new assets: `php artisan nova:publish --force`

**Comment by niladam** [comment]
I'm still encountering this..

**Comment by phikhi** [comment]
Still having this issue :

If the belongsTo is `searchable()`, I can clear the field but, the change won't be saved when the form is submitted.

---

What I already did :

- I upgraded to nova v.2.0.7

- I did a `composer update`
`php artisan nova:publish --force`
`php artisan optimize:clear`

I also cleared my browser cache.

---

Does anyone have a magic solution. Or is there something I forgot ?
