### ISSUE TITLE
distinct() not recognised in calculate method

### ISSUE THREAD

**Issue by GigaMick** [laravel/nova-issues#890]
- Laravel Version: 5.7.0
- Nova Version: 1.1.4
- PHP Version: 7.1.8

### Description:

Adding distinct() to my query is not returning distinct results

### Steps To Reproduce:

```
 public function calculate(Request $request)
    {
        $builder = order::query()->select('cook_id')->distinct();
        return $this->countByDays($request, $builder)->showLatestValue();
    }
```

The above returns a value of "2" but both cook_ids are the same. The same query run in tinker returns "1"

**Comment by davidhemphill** [comment]
This is not enough information to reproduce.
