### ISSUE TITLE
Currency::make('Price')->format('%.2n') is not working when used inside lens file

### ISSUE THREAD

**Issue by jigarhalani** [laravel/nova-issues#894]
- Laravel Version: 5.6.*
- Nova Version: 1.0
- PHP Version: 7.2.9

### Description:
Hi I am using Nova for my admin panel.
**Bug :  ->format function is not working properly inside lens file** 
I have one field which uses currency field to show data I am also passing format for currency using format function.
i.e Currency::make('Price')->format('%.2n') 

This format function is working properly inside Resource file but when **I use this field inside lens it will give 4 trailing zero (0) after the price.**

### Steps To Reproduce:

1) Create a lens for showing any currency value.
2) use the format function to format data.
3) check number is coming with trailing 4 zero on the page.

**Comment by dillingham** [comment]
I can confirm this, was just about to open a issue

**Comment by davidhemphill** [comment]
Any idea what's special about the Lens part of it?

**Comment by dillingham** [comment]
Currently making do with raw selects

```php

 $query
    ->addSelect(['users.id', 'users.name'])
    ->selectRaw("concat('$', format(sum(orders.total), 2)) as total")
    ->join('orders', 'orders.user_id', '=', 'users.id')
    ->groupBy('users.id')
```

**Comment by dillingham** [comment]
Temporary Solution
```php
  $query->selectRaw("concat('$', format(sum(orders.total),2)) as total")
```

**Comment by dkulyk** [comment]
Working on fixing this.

**Comment by dkulyk** [comment]
PR was sent to upstream.

**Comment by dkulyk** [comment]
This has been fixed and will be included in an upcoming release.
