### ISSUE TITLE
BelongToMany cannot attach already attached items

### ISSUE THREAD

**Issue by Hemus** [laravel/nova-issues#895]
I have an Events Model and a Locations Model which both have a BelongsToMany relationship between them both.

The requirement is to be able to attach multiple locations to an event, or the same location (three or four times, maybe).

Anyone know why I can't add the same location more than once and does anyone know how'd I get around this issue? 

<img width="899" alt="attaching_a_location" src="https://user-images.githubusercontent.com/5630773/47501500-9816f680-d85d-11e8-8640-ebd730ce34ca.png">

Can provide more information if required. Thanks for your help, and time you've taken to read this.

**Comment by Hemus** [comment]
The screenshot depicts attaching a location to an event.

**Comment by aaronahearne** [comment]
Did you ever solve this issue?

**Comment by jaseofspades88** [comment]
I seem to have encountered the same issue here

**Comment by incraigulous** [comment]
Anyone know how to do this?

**Comment by aniket-magadum** [comment]
@Hemus  any updates on how did you solve this issue

**Comment by incraigulous** [comment]
@aniket-magadum I ended up solving this by converting my pivot table to a full-fledged model and swapping my belongsToMany relationship with with a hasMany to my former pivot table model. You have to create a nova resource for your new former-pivot-model. 

Resource1 (hasMany) --> <-- (belongsTo) former pivot model (belongsTo) --> <-- (hasMany) Resource2

I still think Nova needs to bake in support for duplicates in a belongsToMany, but this should work for now.

**Comment by aniket-magadum** [comment]
@incraigulous Thankyou very much . I will try if this.

**Comment by royduin** [comment]
Duplicate of: https://github.com/laravel/nova-issues/issues/318

**Comment by jbvios** [comment]
@4nik3t  Did you solve it ?

**Comment by 4nik3t** [comment]
@jbvios Nope it's not solved yet. I have implemented this through a custom Vue component and not with Nova

**Comment by meyer59** [comment]
For anyone running the same issue, as of today, there is a `BelongsToMany::allowDuplicateRelations()` method to allow multiple model to be attached
