### ISSUE TITLE
Hourly Trend in Opposite Order

### ISSUE THREAD

**Issue by dwyer14** [laravel/nova-issues#896]
### Versions
- Laravel Version: 5.7.11
- Nova Version: 1.1.7
- PHP Version: 7.2

### Description:
When counting by hour across 2 or more dates, Trend seems to order correctly on _hour_, but not on _date_.

### Steps To Reproduce:
1. Seed some data w/ `created_at` spanning at least two consecutive days. 
2. Add a trend metric.
3. For the `calculate` method, `countByHours`.
4. For the `ranges` method, return 24, 48 and 72 for keys (optional).
5. Observe a point towards the left and right ends, noting correct _time_ order but incorrect _date_ order.
6. One other note: If you added `ranges`, you'll notice that, when spanning more than 2 days, the first two dates are ordered correctly, but the most recent (ie, right-most) data points are for the earliest date (ie, should be the left-most points).

### Screenshots
Left-ish point (October **25** @ 4am):

![image](https://user-images.githubusercontent.com/13950848/47544673-e18f3200-d8ad-11e8-997e-4b9b80bc1c23.png)

Right-ish point (October **24** @ 10pm):

![image](https://user-images.githubusercontent.com/13950848/47544706-ff5c9700-d8ad-11e8-81eb-f17fe256a2fc.png)

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
