### ISSUE TITLE
Nova Admin is not loaded properly (Absolute path issues)

### ISSUE THREAD

**Issue by keyur5390** [laravel/nova-issues#897]
- Laravel Version: 5.7.3
- Nova Version: 1.1.*
- PHP Version: 7.1.23
![2018-10-26_1149](https://user-images.githubusercontent.com/5053187/47549861-0372ce00-d91b-11e8-92c4-43adba4086c4.png)
![2018-10-26_1149_001](https://user-images.githubusercontent.com/5053187/47549865-053c9180-d91b-11e8-8260-b0a9621071e1.png)
![2018-10-26_1148](https://user-images.githubusercontent.com/5053187/47549868-079eeb80-d91b-11e8-991c-88fc4501d1ac.png)

### Description:
Nova is working perfectly fine for me when I am running using the `php artisan serve` command. But I am wondering about to run the project using localhost followed by project_name (Project is loaded from sub folder). In this case login page loads and after login to admin panel resources are not loading, it shows 404 page (img-1.1).  here If I am clicking on to 'Go Home' button it will load the nova dashboard page but content isn't loaded as the nova-api is not called from proper path (img-1.2). 
To overcome this issue I tried some of the solutions and I found one solution to add the 'domain' in nova config file which is loaded as 'domain' key in 'routeConfiguration' of 'NovaServiceProvider.php' file. but again it throws 404 page (See img 1.3).

**Comment by davidhemphill** [comment]
Nova currently doesn't work in a nested subfolder.

**Comment by keyur5390** [comment]
Is there any way to run the nova project on subdomain?
i.e.
I have one project with http://xyz.com I want to run nova on to http://novaproject.xyz.com

How can I configure this on subdomain?
