### ISSUE TITLE
Translations not working properly

### ISSUE THREAD

**Issue by lucasromanojf** [laravel/nova-issues#9]
The translations (using the json file) are only working on the login screen. They are not working inside resource's index for example.

Also, some texts are not possible to translate. Some examples are the "Search" text (inside search fields), the "TRASHED:" text (inside index filters) and "No {resource} matched the given criteria." (grids) that are hardcoded.

**Comment by gonzunigad** [comment]
+1

**Comment by gonzunigad** [comment]
I fixed it changing the route where the app is looking for the translations on Nova. I think it would be an easy fix.

**Comment by themsaid** [comment]
make sure you're running latest Nova.

**Comment by lucasromanojf** [comment]
I'm running 1.0.5. Translations json is working now, but there are still hardcoded texts.

![image](https://user-images.githubusercontent.com/3661610/44536277-78831680-a6d2-11e8-86de-8c01b46ef405.png)

![image](https://user-images.githubusercontent.com/3661610/44536315-89cc2300-a6d2-11e8-946d-256ab5a22429.png)

![image](https://user-images.githubusercontent.com/3661610/44536434-db74ad80-a6d2-11e8-84e2-6500b4d78fc1.png)

**Comment by squierll** [comment]
+1
I'm running 1.0.8.

**Comment by antoniolore** [comment]
+1
I'm running 1.0.12

**Comment by themsaid** [comment]
Can anyone share what the issue is? Translations are working fine for me and I can't replicate the issue, if someone can share more information that'd be great.

**Comment by antoniolore** [comment]
Hello @themsaid, 

open resources/views/Index.vue line 226:

                        `No {{resourceInformation.label.toLowerCase()}} matched the given criteria.`

The string is hardcoded and I can't translated it by editing en.json or <language_code>.json

Same thing for GlobalSearch and Search components: placeholders strings are hardcoded.

Try to create a new language file and edit "Search" and "No :resource matched the given criteria." tokens. Refresh the page and you will see strings remain untranslated.

**Comment by bonzai** [comment]
Translations are (almost) working, except there are a lot of hardcoded strings inside Vue components:
- #32
- #160
- …

Also some functions stops working if the current language is not English:
- https://github.com/laravel/nova-issues/issues/219#issuecomment-416203872

**Comment by themsaid** [comment]
#219 wow, thanks for pointing this out.

**Comment by themsaid** [comment]
Thanks @antoniolore and @bonzai. I'm working on it.

**Comment by gvsrepins** [comment]
Hello @themsaid!

To help on this matter.. I was only able to translate a BelongsTo field, making an overwrite of the `indexName` value. I think that this was not the intented Behavior since it's not documented. 

Se code bellow to clarify:

```
BelongsTo::make('Activity')
                    ->singularLabel(__('Activity'))
                    ->nullable()
                    ->searchable()
                    ->withMeta(['indexName' => __('Activity')]),
```

PS: Only tested with BelongsTo, but it problem should happens with others realtionship fields to.
