### ISSUE TITLE
composite primary key doesn't work

### ISSUE THREAD

**Issue by underwear** [laravel/nova-issues#900]
- Laravel Version: 5.7
- Nova Version: 1.1.7
- PHP Version: 7.1.6

### Description:
Resource index page requires field id.
Also when i try to see resource details by the relationship I get another error 
    
    mb_strpos() expects parameter 1 to be string, array given
    
### Steps To Reproduce:

    <?php  
      
    namespace App\Entities\Languages;  
      
    use Illuminate\Database\Eloquent\Model;  
      
    class ProductLanguage extends Model {  
      protected $table = 'product_language';  
      
      protected $primaryKey = ['product_id', 'language_id'];  
   
    }
    
#### Stacktrace
    
    #0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'mb_strpos() exp...', '/Users/igorfili...', 112, Array)
    #1 /Users/igorfilippov/Documents/www/avon/vendor/laravel/framework/src/Illuminate/Support/Str.php(112): mb_strpos(Array, '.')
    #2 /Users/igorfilippov/Documents/www/avon/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(359): Illuminate\\Support\\Str::contains(Array, '.')
    #3 /Users/igorfilippov/Documents/www/avon/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1332): Illuminate\\Database\\Eloquent\\Model->qualifyColumn(Array)
    #4 /Users/igorfilippov/Documents/www/avon/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(191): Illuminate\\Database\\Eloquent\\Model->getQualifiedKeyName()
    #5 /Users/igorfilippov/Documents/www/avon/vendor/laravel/nova/src/Http/Requests/InteractsWithResources.php(105): Illuminate\\Database\\Eloquent\\Builder->whereKey('null')
    #6 /Users/igorfilippov/Documents/www/avon/vendor/laravel/nova/src/Http/Controllers/ResourceShowController.php(19): Laravel\\Nova\\Http\\Requests\\NovaRequest->findModelQuery()
    #7 [internal function]: Laravel\\Nova\\Http\\Controllers\\ResourceShowController->handle(Object(Laravel\\Nova\\Http\\Requests\\ResourceDetailRequest), 'product-languag...', 'null')
    #8 /Users/igorfilippov/Documents/www/avon/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
    #9 /Users/igorfilippov/Documents/www/avon/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('handle', Array)
    #10 /Users/igorfilippov/Documents/www/avon/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Laravel\\Nova\\Http\\Controllers\\ResourceShowController), 'handle')

**Comment by fletch3555** [comment]
Not specific to the current version, but here's this: https://blog.maqe.com/solved-eloquent-doesnt-support-composite-primary-keys-62b740120f

In short, this isn't a Nova issue, it's a Laravel/Eloquent limitation.  `$primaryKey` must always be a string

**Comment by underwear** [comment]
Oh sorry, this is eloquent limitation, yes.
There is solution https://github.com/coenjacobs/eloquent-composite-primary-keys

**Comment by davidhemphill** [comment]
The primary key must be a string.

**Comment by tectiv3** [comment]
I am using this [trait](https://github.com/mopo922/LaravelTreats/blob/master/src/Model/Traits/HasCompositePrimaryKey.php)
and after adding this method to it everything works perfectly.
```
    public function getQualifiedKeyName()
    {
        return implode('_', $this->getKey());
    }
```
