### ISSUE TITLE
\Laravel\Nova\Fields\Image not working as intended

### ISSUE THREAD

**Issue by DanielProtopopov** [laravel/nova-issues#901]
- Laravel Version: 5.7.*
- Nova Version: 1.1.7
- PHP Version: 7.2.*

### Description:
\Laravel\Nova\Fields\File::make('Filename')->disk('scans')->sortable() creates a proper link to download the file, while \Laravel\Nova\Fields\Image::make('Filename')->disk('scans')->sortable() displays that image is not found.

### Steps To Reproduce:
filename attribute contains '1.jpeg' in it
Image is in the /var/www/scans/test.api/

Disks are set up like so:
```php
'disks' => [
        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
        ],
        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],
	'scans' => [
			'driver' => 'local',
			'root' => '/var/www/scans/test.api/'
		]
    ],
```

**Comment by davidhemphill** [comment]
The disk has to be symlinked inside the public folder. Can you confirm you've done this?

**Comment by DanielProtopopov** [comment]
Yes, I've ran the command, but it does not allow to specify any directory besides the storage/app/public. I've had to manually create a link named 'storage' in public directory to the required directory outside of the project, after which it worked.
