### ISSUE TITLE
Computed fields callback is executed in creation form

### ISSUE THREAD

**Issue by chinleung** [laravel/nova-issues#902]
- Laravel Version: **5.7.11**
- Nova Version: **1.1.17**
- PHP Version: **7.2.5**

### Description:

I have the following computed field in my Unit resource:

```
public function fields(Request $request)
{
    return [
        ID::make()->hideFromIndex(),

        BelongsTo::make(__('Building'), 'building', Building::class)
            ->searchable(),

        Text::make(__('Address'), function () {
            return $this->building->address;
        })->onlyOnIndex(),
    ];
}
```

Then when I try to create a new Unit resource, I get the following error:

> Trying to get property 'address' of non-object.

When I comment out the line in my callback every thing works fine. I could bypass this by doing:

```
return $this->building ? $this->building->address : null;
```

But I don't think it's expected behaviour for the callback to run in the creation form since it doesn't have any thing to save.

**Comment by davidhemphill** [comment]
The field's value is resolved whether it's blank or not, and so this is expected behavior. The `optional` helper is your friend here.

**Comment by chinleung** [comment]
@davidhemphill But why is Nova trying to resolve a computed field's callback in the creation form even though it's not used? 🤔
