### ISSUE TITLE
Trix default toolbar is useless

### ISSUE THREAD

**Issue by alberto-bottarini** [laravel/nova-issues#905]
I think that default Trix toolbar is too poor. 
You cannot have undeline text, heading (except for H1) or table.

This is very frustrating because all other WYSISYG editors have these features as default. 

I think Nova should use a custom toolbar in order to have more tools enabling this kind of field to be usable on production environment,

**Comment by davidhemphill** [comment]
Create a custom field of what you like or use one from http://novapackages.com
