### ISSUE TITLE
[bug] "0" gets interpreted as null

### ISSUE THREAD

**Issue by alberto-bottarini** [laravel/nova-issues#908]
- Laravel Version: 5.7
- Nova Version: 1.1.4

### Description:
If i write "0" in a number or text field and then reopen edit form, fields is empty and validator gives me an error.

### Steps To Reproduce:
Create a new Text or Number field binded to a int value on database. Put 0 as value and "Update and continue saving". You should see an empty field,

**Comment by imlida** [comment]
same issues in 1.1.7

**Comment by dkulyk** [comment]
Need to add nullable modifier to the all fields and convert value to the null when a field post data is empty. Otherwise set the value as is.

**Comment by alberto-bottarini** [comment]
The "nullability" of the field is working well. If I leave it empty, NULL get saved into database.

The issue is with "0" as value. I guess somewhere it should be reconverted to null when I reopen the form because, I guess, a loosy typed if (`empty` for example).

**Comment by alberto-bottarini** [comment]
The problems seems to be on client. Looking through POST request, I get an empty string instead of 0.

```
Content-Disposition: form-data; name="field1"

3
-----------------------------7560035517432718791326175101
Content-Disposition: form-data; name="field2"


-----------------------------7560035517432718791326175101
Content-Disposition: form-data; name="field3"

7
-----------------------------7560035517432718791326175101
```

field2 was populated with a 0 as value

**Comment by alberto-bottarini** [comment]
Maybe I found the bug:

```
fill(formData) {
     formData.append(this.field.attribute, this.value || '')
},
```

in FormField.vue.

If this.value is 0, it return ""... :-1:

**Comment by alberto-bottarini** [comment]
No one else has this problem?

**Comment by davidhemphill** [comment]
This has been fixed and will be included in an upcoming release.
