### ISSUE TITLE
Conflicts between indexQuery and relatableQuery

### ISSUE THREAD

**Issue by dwyer14** [laravel/nova-issues#909]
- Laravel Version: 5.7.11
- Nova Version: 1.1.7
- PHP Version: 7.2

### Description:
`indexQuery` and `relatableQuery` both work, but not [as documented](https://nova.laravel.com/docs/1.0/resources/authorization.html#index-filtering). 

If `indexQuery` is defined on a Nova resource, it will impact the index **as well as** the relatable options in the select field. If `relatableQuery` is defined, it works as expected/documented, and only filters the options in the select field. If **both** are defined, the `indexQuery` seems to take precedence and override the `relatableQuery`.

If the `indexQuery` is _supposed_ to override the `relatableQuery`, that should probably be documented...but it strikes me as unintentional/a bug. There are times, at least for me, where we want to filter the same on both methods. If that's the case, then it seems you should just call the other method explicitly. For example, if we want the relatables to be filtered the same as the index:

```php
public static function relatableQuery(NovaRequest $request, $query)
{
    return static::indexQuery($request, $query);
}
```

### Steps To Reproduce:
1. Setup two simple models and give one a `belongsTo` relationship to the other.
2. Apply an `indexQuery` that filters the available results.
3. View the options in the select input dropdown, for the owned model.
4. Add a `relatableQuery` that filters in a different way or not at all (ie, `return $query`).
5. View the options in the select input dropdown, for the owned model. The filter in `indexQuery` is still applied.

**Comment by abordage** [comment]
1+, same problem

**Comment by noahlocke** [comment]
@davidhemphill any ideas on this one? It's causing some major problems in my instance.

**Comment by mathieutu** [comment]
Seems to be the same as : https://github.com/laravel/nova-issues/issues/337, isn't it ?

**Comment by dwyer14** [comment]
@mathieutu Definitely related. @noahlocke didn't mention `relatableQuery` in his original post and it sounds like that's probably what he needs...but as mentioned here, it's not going to work as expected, if he's also using an `indexQuery`. He would run into this "overriding" problem, I would guess.

Somewhat related, this issue (909) is talking about an actual _bug_ related to _authorization_, when using the `indexQuery` and `relatableQuery` methods. Based on how these are explained in Nova's documentation, they're specifically for authorization—ie, controlling index and relationship fields based on the _ authenticated user_. I've seen a lot of people (myself included) who also wind up using those methods to add filtering based on _business logic_. To me, it would make a lot of sense to introduce a separate, chainable method (eg, `creatingFilter`), to be called when defining a relationship field (eg, `BelongsTo`) on a resource. Separate issue and more of a feature request, but I feel that's related to what's being discussed here, and in #337.

**Comment by noahlocke** [comment]
@dwyer14 `indexQuery` is what I need, and am using it for authorization. Problem is the scope, as I mentioned in #337. `relatableQuery` is also useful, but rendered useless if one needs to use both methods.

**Comment by webhealer** [comment]
indexQuery always overriding the relatableQuery , which makes impossible to use both methods. i want to apply different query on relation index, but i can't not do.

**Comment by webhealer** [comment]
This is a quick fix, if you want to call relatable query :

```
  public static function indexQuery(NovaRequest $request, $query)
  {
     
   if ($request->viaRelationship) {
      return self::relatableQuery($request,$query);
    }

 }
```

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
