### ISSUE TITLE
Logout route is protected when using nova Guard - user should be denied login.

### ISSUE THREAD

**Issue by johnpaulmedina** [laravel/nova-issues#910]
- Laravel Version: 5.7.11
- Nova Version: 1.1.7
- PHP Version: 7.1.20

### Description:
Logout route is blocked when changing env and nova Guard is configured for specific users. Other users should be denied the login and not logged in and given 403 for all routes.

### Steps To Reproduce:
Enable nova Guard on a per/user basis
Switch env from local to development or production
Login with a non allowed user
Can't logout without clearing session

Would there not be a better auth implementation for this? Maybe the user account should be denied the actual login instead of logging the user and serving a 403 for everything. Can the guard be checked at the actual attempt to login so that the initial login is denied? 

Is this intentional so that a custom authentication is implemented?

This is just an attempt to make the out-the-box application a bit more accommodating as oppose to more configurations needed.

**Comment by krgaurav1992** [comment]
Facing same issue. Any update on this ?

**Comment by RaymondAtivie** [comment]
Facing the same issue.

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
