### ISSUE TITLE
"Open as new Tab" not working for some interactions

### ISSUE THREAD

**Issue by jwahdatehagh** [laravel/nova-issues#911]
- Laravel Version: 5.7.9
- Nova Version: 1.1.4
- PHP Version: 7.2

### Description:
Some call to action buttons don't work as links. This is a UX-problem; As a user i expect to be able to open e.g. the creation or attach view of a resource in a new tab in order to preserve the current screen and be able to quickly switch back to it. It works for some interactions in Nova, it doesn't work for others which is confusing.

### Steps To Reproduce:
Click on one of the following CTAs:
- Create XYZ (Index view)
- Create XYZ (Display view; HasMany relation)
- Attach XYZ (Display view; BelongsToMany relation)
- others?

**Comment by bonzai** [comment]
This was fixed in version 1.2.0.

https://nova.laravel.com/releases
