### ISSUE TITLE
File path with resource id on first save

### ISSUE THREAD

**Issue by weeman1337** [laravel/nova-issues#914]
- Laravel Version: 5.7.12
- Nova Version: 1.1.7
- PHP Version: 7.2

### Description:
I defined a file field as following:

    Image::make(__('image'), 'image')
        ->hideFromIndex()
        ->disk('public')
        ->path('pages/' . $this->resource->id . '/images')

When storing the Nova model for the first time, the resource hasn't been saved yet, so there is no id.  
Storing it a second time works well, since it then has an id.

### Steps To Reproduce:
* Define a Nova model with a file field like the one above referencing the resource id
* Store a new one of this object

Expected: The path contains the id
What happens: Saving the first time, this id is empty

### My thoughts
Maybe the ordering should changed:
1. save the model
2. save the attachments

**Comment by garethnic** [comment]
Does anyone know of a decent workaround for this?

**Comment by garethnic** [comment]
@weeman1337 In [473](https://github.com/laravel/nova-issues/issues/473) they fixed it with the trix field. So I'm assuming somewhere we can override the behaviour.

**Comment by garethnic** [comment]
The way I'm doing it is using the `->store()` function for custom file storage. I need to pass the model through to set relationships up in my global file upload trait. All I ended up doing was `$model->save()` before sending the instance. 

It might be more work for you, but it seems to do the trick. The nova file fields are kept at the bottom so all attributes are saved when I force it.

**Comment by chatzisnik** [comment]
@garethnic thanks for the idea!

`                Image::make('Tile Image')
                    ->creationRules('required')
                    ->deletable(false)
                    ->hideFromIndex()
                    ->store(
                        function (Request $request, $model) {
                            //Saving the model early in order to have a valid $model->id
                            if (!$model->id) {
                                $model->save();
                            }
                            return [
                            'tile_image' => $request->tile_image->store('models/id-'.$model->id.'/', 'public'),
                            ];
                        }
                    ),`

This is what i did to store the model id on the path. The only problem coming from that, is that since the fields below that one,  haven't been added to the request yet, you need to either set a placeholder value before saving the model or make them nullable on your migration,

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!

**Comment by chatzisnik** [comment]
New implementation since saving the model causes issues if you have non nullable fields:
```
                Image::make('Image 3')
                    ->store(
                        function (Request $request, $model, $fieldName = 'image_3' ) {
                            // Saving the model early in order to have a valid $model->id
                            $nextId = $model->id;
                            if (!$model->id) {
                                $statement = DB::select("SHOW TABLE STATUS LIKE 'yourmodelsdbtable'"); // todo get table name from controller or move to model
                                // Check if we already have things on the database
                                if ($statement) {
                                    $nextId = $statement[0]->Auto_increment; 
                                }else{
                                    $nextId = 1;
                                }
                            }
                            return [
                            "$fieldName" => $request->{$fieldName}->store('properties/id-'.$nextId, 'public'),
                            ];
                        }
                    )
                    ->hideFromIndex(),
```

@jbrooksuk: Is there an other way of achieving this ??? Not having an ID at the point

**Comment by jbrooksuk** [comment]
The Trix field works around this by storing a "draft attachment" and then updating to the real ID once the model has been persisted.

**Comment by orrd** [comment]
If you're storing the file with a name that's entirely based on the model ID, then you may not need to store the name of the file in the database (because you can already determine what the filename is from the model ID).  

In that situation, you can just have it save the file as part of the model's saved event handlers like this:

```
Image::make('yourfieldnamehere')
   ->store(function ($request, $model) {
      $class = get_class($model);
      $class::saved(function ($model) use ($request) {
         $request->yourfieldnamehere->storeAs('foldername', $model->id.'.jpg', 'public'),
      });
      return [
         // optionally, you can have a field in your model that just stores true or false 
         // telling you that the file exists.
         'yourfieldnamehere' => true 
      ];
   }),
```

You would also need to set `->preview()` to tell it where to find the file for previews.

One last thought, maybe just use `->hideWhenCreating()` if you don't really need to be able to be able to save a file to the model when it's first created (I did this for user profile photos since I usually don't need to set their photo when the user is first created).

**Comment by kevnk** [comment]
I've tweaked what @orrd wrote if you do want to save the filepath in the database:

```php
Image::make('Photo', 'photo_url', 's3')->store(function (Request $request, $model) {
    $class = get_class($model);
    $class::saving(function ($model) use ($request) {
        $dir = "events/$model->slug";
        $filename = Storage::disk('s3')->put($dir, $request->photo_url, 'public');
        $model->photo_url = $filename;
        return $model;
    });
    return $model->photo_url;
})->prunable(),
```

NOTES:
- I used `$class::saving()` instead of `$class::saved` so I could access the model while it was being saved and add my attribute to the model
- I return the attribute (and it loads the image — first try!)

**Comment by mbryne** [comment]
I'd just like to add my solution to this, if you return a function from the store closure it will be called after the model is saved:

```php
->store(function (Request $request, $model) {
    return function () use ($model, $request) {
        $model->actionOnExistingModel( $request->your_field_here );
    };
})
```

This is covered loosely in the last example before the Invokables subheading on this page:
https://nova.laravel.com/docs/2.0/resources/file-fields.html#customizing-file-storage
