### ISSUE TITLE
ActionEventPolicy not working

### ISSUE THREAD

**Issue by LorensoD** [laravel/nova-issues#917]
To hide the  Action log of my user object I created an `ActionEventPolicy` which works on the Laravel Nova ActionEvent class: `App\Laravel\Nova\Actions\ActionEvent`. 

I registered the policy in my `AuthServiceProvider` like I've done with all my other Policies but for some reason the Policy doesn't seem to work.

Could it be that the policies are overwritten because this is a Class in the `App\Laravel\Nova\Actions` directory?

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
