### ISSUE TITLE
BelongsToMany: Custom pivot attribute name not working on forms

### ISSUE THREAD

**Issue by dwyer14** [laravel/nova-issues#919]
- Laravel Version: 5.7.11
- Nova Version: 1.1.7
- PHP Version: 7.2

### Description:
When using a custom pivot attribute name on your Eloquent model, values are pulled in correctly on the corresponding Resource detail view (under the applicable many-to-many relationship). When you click 'Edit Attached' however, the form fields are blank. That is, the pivot fields aren't pre-filled with the existing/current pivot values.

### Steps To Reproduce:
1. Create 2 models with a many-to-many relationship, and a pivot table that has additional data.
2. Set up default `belongsToMany` relationships on your Eloquent models (ie, without `->as()` method).
3. Create at least one pivot entry, with data in the additional pivot field.
4. Observe Edit Attached form for the resource, viewing the data created in step 3. Note pre-filled data.
5. Add the `->as()` method to your Eloquent model. Observe same Edit Attached, note missing field data.

**Comment by GordanaP** [comment]
The same problem with me.

**Comment by loekwetzels** [comment]
I think it's working properly when you use `withPivot` in your Model. See [eloquent-relationships](https://laravel.com/docs/5.8/eloquent-relationships#many-to-many) in Laravel Docs

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
