### ISSUE TITLE
Unable to see the resource detail

### ISSUE THREAD

**Issue by meyer59** [laravel/nova-issues#92]
Hi,
I am unable to see the
![image](https://user-images.githubusercontent.com/9505463/44561135-5d0c2000-a753-11e8-9324-3f517c60fbc5.png)
of one resource, Anyone is having the same issue ? See the picture below
Thanks
![image](https://user-images.githubusercontent.com/9505463/44561110-42d24200-a753-11e8-8a19-1028eff74eaf.png)

**Comment by judge2020** [comment]
The eye symbol is visible with the `can('view')` function, so it'll inherit whatever Guard your model has in `App\Providers\AuthServiceProvider.php`.

eg, the following will show the eye symbol

```
    protected $policies = [
        'App\Model' => 'App\Policies\ModelPolicy'
    ];
...
```
    public function view(User $user, Model $model)
    {
        return true;
    }
```

**Comment by meyer59** [comment]
Hi,
Thanks @judge2020, I wasn't aware that Nova use the current app Policies. 
It's sounds weird because our policies are for the client side of the app, but nova is for the backoffice side. I must misunderstand something here
