### ISSUE TITLE
BelongsToMany: Data is overwritten when same models linked more than once

### ISSUE THREAD

**Issue by dwyer14** [laravel/nova-issues#920]
- Laravel Version: 5.7.11
- Nova Version: 1.1.7
- PHP Version: 7.2

### Description:
When updating pivot data (ie, Edit Attached), other pivot entries with the same `related_id`s are overwritten. Example used in steps below.

### Steps To Reproduce:
1. Setup two Eloquent models with many-to-many relationship, Person and Occupation.
2. Include at least one piece of additional data in the pivot table. `start` and `end`, for example.
3. Create one Person record and one Occupation record.
4. Create _two_ pivot entries
a.) Linking Person1 to Occupation1 for both entries.
a.) These pivot entries represent two different stints in the same role, by the same person.
5. Edit the second pivot entry via the Edit Attached form for Person1's Occupations.
6. Save and observe that both pivot entries have been updated; the first pivot entry was overwritten.

**Comment by onurguven** [comment]
did you find a solution?

**Comment by dwyer14** [comment]
Nope. This feels like a pretty essential piece of functionality; holding out for a proper fix in Nova's core.

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
