### ISSUE TITLE
[Feature Request] Custom Resource Label

### ISSUE THREAD

**Issue by nasrulhazim** [laravel/nova-issues#921]
Hi,

Currently all the menu labelling is based on pluralised called class and for the create button label, it's singular called class.

It will be nice if we can overwrite the labels display like:

```php
public static $label = 'Custom Resource Label`;
```

As for now, this is my solution to have [Custom Resource Label](https://medium.com/@nasrulhazim/create-custom-resources-label-4489ddfc113a)

It will be good if it's support localisation too.

**Comment by davidhemphill** [comment]
This is why we have the `singularLabel` and `label` methods.

**Comment by nasrulhazim** [comment]
> This is why we have the `singularLabel` and `label` methods.

I see, noted. I've been digging the codes to find a way to overwrite the default behaviour since not able to find how to rename the labels from documentation.

Anyway, thanks for the clarification!
