### ISSUE TITLE
No 'Per Page' Filter available when `authorizedToDelete` returns `false` and no Filters are registered against the Resource

### ISSUE THREAD

**Issue by bgurney** [laravel/nova-issues#923]
- Laravel Version: 5.7.12
- Nova Version: 1.1.7
- PHP Version: 7.1

### Description:

I have a Resource on which `authorizedToDelete` returns `false` and no Filters are registered.

When I browse to the Resource, the Filter select element is not showing, meaning I do not have any way to change the pagination size.

If I change it so that `authorizedToDelete` returns `true`, or I add a Filter to the Resource then it comes back, however I do not have any Filters for this Resource yet.

### Steps To Reproduce:

Return `false` from `authorizedToDelete` method on a Resource with no Filters.

**Comment by davidhemphill** [comment]
This should be fixed by the upcoming reworking of Filters. Feel free to post this issue again if the issue persists in the new version. 👍

**Comment by dwyer14** [comment]
Came searching for this before updating and can confirm—1.1.8 fixes it. Filter/pagination menu is now always available.
