### ISSUE TITLE
Two fields in the same row

### ISSUE THREAD

**Issue by aramirez92** [laravel/nova-issues#924]
Instead of one field per row how can i put two or more small fields on the same row, example: 
![](https://i.imgur.com/773dHSt.png)

[View full image](https://i.imgur.com/773dHSt.png)

Is missing on the docs

**Comment by Enmaboya** [comment]
can you show me an example code?

**Comment by noahlocke** [comment]
@aramirez92 you can't, not with the standard theme anyway. 

You can generate your own `nova:theme` and attempt this, but it's not very easy as there are zero class names, so selectors are a bit tricky.

**Comment by davidhemphill** [comment]
This isn't supported.

**Comment by d0utone** [comment]
Just if anybody stumbles across this: I use Nova Custom Fields and attach the inline-block class manually to the field like this: `->wrapperClasses('break w-1/2 inline-block')`

**Comment by tushar-kharmate** [comment]
> Just if anybody stumbles across this: I use Nova Custom Fields and attach the inline-block class manually to the field like this: `->wrapperClasses('break w-1/2 inline-block')`

@d0utone Can you help me with this more? How to do this?

**Comment by d0utone** [comment]
> > Just if anybody stumbles across this: I use Nova Custom Fields and attach the inline-block class manually to the field like this: `->wrapperClasses('break w-1/2 inline-block')`
> 
> @d0utone Can you help me with this more? How to do this?

@tushar-kharmate sorry for the late reply. I didn't explain it very well. With Custom fields I meant that I used the nova-fields package by 64robots. The docs you need can be found here [](https://nova-fields.netlify.app/custom.html#rowwrapperclasses)

**Comment by BeiAduo** [comment]
> Instead of one field per row how can i put two or more small fields on the same row, example: 
> ![](https://i.imgur.com/773dHSt.png)
> 
> [View full image](https://i.imgur.com/773dHSt.png)
> 
> Is missing on the docs
