### ISSUE TITLE
Partition metric shows scrollbar behind chart

### ISSUE THREAD

**Issue by ruudz** [laravel/nova-issues#925]
- Laravel Version: 5.7.12
- Nova Version: 1.1.7
- PHP Version: 7.2
- Browser: Firefox & Chrome
- OS: Linux

### Description:
I saw #93 but it seems that the problem is still there. If a partition metric has more than 5 items a scrollbar will appear behind the chart as seen here:

![image](https://user-images.githubusercontent.com/2395361/47912914-78558300-de9a-11e8-89d4-d1287cd8da83.png)

### Steps To Reproduce:

1. Create a partition metric as described in the docs (example `php artisan nova:partition UsersPerPlan`).
2. Make sure there are more than 5 values to chart.

**Comment by mvnobrega** [comment]
The same situation in here.

**Comment by davidhemphill** [comment]
I believe this issue should be fixed. Please post a new issue if the issue persists.

**Comment by gpressutto5** [comment]
@davidhemphill Why closing an issue that is clearly still happening?

**Comment by robbykrlos** [comment]
version 2.0.5 - issue still persists.

**Comment by klepak** [comment]
still present in 2.0.7

**Comment by lasselehtinen** [comment]
This is also present in 2.0.11.

**Comment by farzadjafari** [comment]
The issue still persists in version v2.3.1
