### ISSUE TITLE
Update JSON values

### ISSUE THREAD

**Issue by nickels** [laravel/nova-issues#926]
Version v1.1.7

On my model I'm casting to array. 

```
    protected $casts = [
        'options' => 'array'
    ];
```

In the nova resource I'm trying to have a Boolean field:

```
Laravel\Nova\Fields\Boolean::make('Club Members Only', 'options.clubmembers'),
```

It renders correctly, however can't update the value to true or false.

Data is stored in the db using a `jsonb` field like so:

`{"clubmembers": "1"}`

Thoughts?

_Originally posted by @nickels in https://github.com/laravel/nova-issues/issues/598#issuecomment-434449965_

**Comment by iAxel** [comment]
```php
Boolean::make('Club Members Only', 'options.clubmembers')
                ->resolveUsing(function ($value) {
                    return $value;
                }),
```

**Comment by wfeller** [comment]
Like this ?

```
Boolean::make('Club Members Only', 'options.clubmembers')
                ->fillUsing(function ($request, $model, $attribute, $requestAttribute) {
                       if ($request->exists($requestAttribute)) {
                            $model->options['clubmembers'] = !! $request[$requestAttribute];
                        }
                }),
```

**Comment by iAxel** [comment]
```php
Boolean::make('Club Members Only', 'options->clubmembers')
                ->resolveUsing(function ($value) {
                    return $value;
                }),```

Try it

**Comment by nickels** [comment]
Thanks for the feedback, i will try tonight.

**Comment by blackfyre** [comment]
Got a similar issue, high probability of that it's related.
The problem is when creating a record... says that the `options` field doesn't have a default value, which means that it doesn't forward the selected values and it tries to create a row without anything in the options column...

**Comment by nickels** [comment]
@iAxel and others thank you soo much, finally got around implementing your suggestions. It works just perfectly.
