### ISSUE TITLE
MAJOR BUG!!! Please fix ASAP (Tool front end won't change with Tool.vue changes)

### ISSUE THREAD

**Issue by UdyW** [laravel/nova-issues#927]
- Laravel Version: 5.7.9
- Nova Version: 1.1.5
- PHP Version: 7

### **This needs your urgent attention !!! please fix ASAP.**

Updating the Tool.vue does not change the front end.

### Steps To Reproduce:
1. Simply follow the steps in https://nova.laravel.com/docs/1.0/customization/tools.html
2. Do any html change in Tool.vue file.
3. npm run watch
3. Changes won't change the front end view.

**As you can see this is a major issue. Your immediate attention is required.**

PS: Did you test this before release/ documentation?

**Comment by Frozire** [comment]
Are you running your npm run watch from the tools root?

**Comment by UdyW** [comment]
Project root

**Comment by Frozire** [comment]
That's the mistake.

**Comment by UdyW** [comment]
Where does it say that?

**Comment by Frozire** [comment]
It doesn't tell you directly, but it tells you that the tool contains the webpack.mix implying the build process needs to be on the tool.

You can close this issue.

I suggest reading this https://tighten.co/blog/publishing-your-first-laravel-nova-tool to become more familiar with how to create tools with Nova.

Have a nice day.

**Comment by Frozire** [comment]
It doesn't tell you directly, but it tells you that the tool contains the webpack.mix implying the build process needs to be on the tool. Perhaps the documentation could be improved to further clarify this to avoid future confusion.

I suggest reading this https://tighten.co/blog/publishing-your-first-laravel-nova-tool to become more familiar with how to create tools with Nova.

Have a nice day.
