### ISSUE TITLE
Validation rules on additional fields not working on User resource

### ISSUE THREAD

**Issue by rehmatworks** [laravel/nova-issues#928]
- Laravel Version: 5.7
- Nova Version: 1.1.7
- PHP Version: 7.2

### Description:
When additional fields are added to Nova User resource, the validation rules for those fields don't work.

### Steps To Reproduce:
Add an additional field to users table, say age, and when this field is added to Nova `User` resource, then validation rules won't work on that field.

**Comment by davidhemphill** [comment]
We are unable to debug your issue without a reproducible code example.
