### ISSUE TITLE
Nova change sub category on category change

### ISSUE THREAD

**Issue by sumbria** [laravel/nova-issues#929]
I have 2 dropdowns:
1. Dropdown getting data from model - **Category**
2. Dropdown getting data from model - **SubCategory**

```
class Category extends Model
{
	public function sub_categories()
        {
            return $this->hasMany(SubCategory::class);
        }
}

```

How can I change sub categories on category change?

![Nova Category Change](http://www.clipular.com/c/6618609615634432.png?k=1MdI82B1nogOkG2TkXzjPIdNBg0)

Any suggestions would be highly appreciated. Thank you.

**Comment by davidhemphill** [comment]
You can use something like this: https://novapackages.com/packages/epartment/nova-dependency-container.

Also, this issue board is for tracking bugs. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).

**Comment by sumbria** [comment]
This package helps https://novapackages.com/packages/orlyapps/nova-belongsto-depend
