### ISSUE TITLE
Scrollbar on Partition Metric

### ISSUE THREAD

**Issue by poxin13** [laravel/nova-issues#93]
Getting an overlapping scrollbar just on this metric type. Latest version of Chrome and Firefox.

![chrome_2018-08-23_22-24-08](https://user-images.githubusercontent.com/10375741/44561593-7f864500-a723-11e8-9ba0-d1701f9251e8.png)

**Comment by scrothers** [comment]
Confirmed in the latest 1.0.5 release on a vanilla installation.

**Comment by poxin13** [comment]
Fixed in 1.0.6
