### ISSUE TITLE
BelongsTo pivot field error

### ISSUE THREAD

**Issue by jarrodzimm** [laravel/nova-issues#932]
- Laravel Version: 5.7.12
- Nova Version: 1.1.7
- PHP Version: 7.2.9

### Description:

I'm getting this error when attempting to update a BelongsTo pivot field: `Call to undefined method Illuminate\Database\Eloquent\Relations\Pivot laravel nova`
![image](https://user-images.githubusercontent.com/6708162/47959812-4ab42b00-dfbb-11e8-92a3-73ef2132a512.png)

Laravel: Thread.php
```
public function works()
{
    return $this->belongsToMany('App\Work')
        ->withPivot('engagement_id')
        ->using('App\ThreadWork');
}
```

Laravel: Work.php
```
public function threadx()
{
    return $this->belongsToMany('App\Thread')
        ->withPivot('engagement_id')
        ->using('App\ThreadWork');
}
```

Laravel: ThreadWork.php
```
namespace App;

use Illuminate\Database\Eloquent\Relations\Pivot;

class ThreadWork extends Pivot
{
    protected $with = ['engagement'];
    public $timestamps = true;

    public function engagement()
    {
        return $this->belongsTo('App\Engagement');
    }
}
```

Nova: Thread.php
```
public function fields(Request $request)
{
    return [
        BelongsToMany::make('Works')
            ->fields(function () {
                return [
                    BelongsTo::make('Engagement'),
                ];
            }),
    ];
}
```

Nova: Work.php
```
public function fields(Request $request)
{
    return [
        BelongsToMany::make('Threads')
            ->fields(function () {
                return [
                    BelongsTo::make('Engagement'),
                ];
            }),
    ];
}
```

### Steps To Reproduce:

In this example, Threads belong to many Works, Works belong to many Threads, and the intermediate table has an optional belongs to relationship to an Engagement.

1. Set up intermediate table model and Nova resources as included above
2. From the Thread detail page, click "Attach Work"
3. Error appears on `/nova/resources/threads/10/attach/works?viaRelationship=works&polymorphic=0` and BelongsTo field is missing

**Comment by jarrodzimm** [comment]
Upon further reading, I don't think this type of relationship is the best practice. Hence, why I'm running into problems. Closing this issue.

**Comment by rippers66** [comment]
@jarrodzimm  - I am facing this exact same challenge where I want to use a BelongsTo relationship on a pivot field. Did you manage to find an alternative 'best practice' solution to achieve this in Nova?

**Comment by jarrodzimm** [comment]
@rippers66 I ended up avoiding the situation altogether and changed the logic of how I was displaying the relationship. Hopefully, a solution pops up at some point.

**Comment by rippers66** [comment]
Thanks @jarrodzimm  - I'll do a bit more thinking and see if I can come up with something. I'm pretty sure I can do it in Laravel with Vue, but I don't know Nova well enough yet to start changing things under the hood. I'll let you know if I get something working.

**Comment by greggh** [comment]
I have this exact problem, and it is actually the correct way to show my data. But I can't find any solutions to id. Did anyone here actually solve it?

**Comment by jonrobinson** [comment]
@greggh ran into the same situation just now. Haven't gotten a chance to see if there is a "right" way to do this, but here is a quick hack:
`
public function fields(Request $request)
{
    return [
        BelongsToMany::make('Threads')
            ->fields(function () {
                return [
                    Select::make('Engagement', 'engagement_id')->options(Engagement::pluck('name', 'id')->toArray())->displayUsingLabels()
                ];
            }),
    ];
}
`

**Comment by greggh** [comment]
@jonrobinson That quick hack works! Thanks for that.

**Comment by shortcodes** [comment]
And how about attaching Thread with Work. You have to add engagement_id somehow. How to do this using laravel nova?

**Comment by BenWalters** [comment]
> @greggh ran into the same situation just now. Haven't gotten a chance to see if there is a "right" way to do this, but here is a quick hack:
> 
> ```
> public function fields(Request $request)
> {
>     return [
>         BelongsToMany::make('Threads')
>             ->fields(function () {
>                 return [
>                     Select::make('Engagement', 'engagement_id')->options(Engagement::pluck('name', 'id')->toArray())->displayUsingLabels()
>                 ];
>             }),
>     ];
> }
> ```

Thanks @jonrobinson.
@davidhemphill Is there a more elegant way of doing this with Nova? As far as I've understood the documentation it should be possible to do it how initially stated by the author of this issue.

**Comment by ThaDaVos** [comment]
Any fix for this? I'm running into the same issue as I want to show a `BelongsTo` field on my pivot table but also getting the same error as above for me the situation is as follows:

I have a Groups Table, a Roles Table and a Users Table -> they all use the same pivot table as `A user has a role per group`
Inside Laravel it works fine but it looks like the `BelongsTo` is looking on the wrong model for some reason and the only thing I want to show is:
On the Role side: I want to show which Group the user BelongsTo (because now I have the user multiple times, for different Groups but no way of telling)
On the Group side: nothing extra
On the Users side in the Groups list: Show their Role in the Group
On the Users side in the Roles list: Show the Group for which they have that Role

Currently using the `Text::make('{NAME}', {CALLABLE})` as workaround as using it as a computed field but now it's not clickable

**Comment by vodolgiy** [comment]
Hey, anyone know 'best practice' solution for similar situations? Or any fix?

**Comment by lukeptchr** [comment]
I'm still facing this issue, could this please be reopened?
