### ISSUE TITLE
Issues when having multiple relationships to User::class

### ISSUE THREAD

**Issue by tanthammar** [laravel/nova-issues#935]
- Laravel Version: 5.7.12
- Nova Version: v1.1.4
- PHP Version: 7.2.8

### Description:
Tasks have 2, belongsTo relationships, with the User::class, one as "author" and one as "assigned_user"
The double relationship to the User::class causes a non-user-friendly behaviour in Novas workflow.

1. On the Users Detail view the column to show the "delegated" user is missing
2. When creating a related task from User detail view, the field to select(assign) a User is locked

See the attached images for a better explanation.

![image 2018-11-04 at 3 06 06 pm](https://user-images.githubusercontent.com/21239634/47965506-76c9bd80-e048-11e8-99e5-11707d8abe7b.png)
![image 2018-11-04 at 3 09 55 pm](https://user-images.githubusercontent.com/21239634/47965507-76c9bd80-e048-11e8-8faf-63a7062932bf.png)
![image 2018-11-04 at 3 12 17 pm](https://user-images.githubusercontent.com/21239634/47965508-76c9bd80-e048-11e8-83ed-54a09345b849.png)

### Steps To Reproduce:
**App\User**
```
public` function tasks()
    {
        return $this->hasMany(Task::class);
    }

    public function assigned_tasks()
    {
        return $this->hasMany(Task::class, 'assigned_user_id');
    }
```

**App\Nova\User**
```
HasMany::make('Created Tasks', 'tasks', Task::class),
HasMany::make('Assigned Tasks', 'assigned_tasks', Task::class),
````

**App\Task**

```
public function assigned_user()
    {
        return $this->belongsTo(User::class, 'assigned_user_id', 'id')
            ->withDefault();
    }
public function user()
    {
        return $this->belongsTo(User::class);
    }
```

**App\Nova\Task**

```

BelongsTo::make('Author', 'user', User::class)->withMeta([
                'value' => $this->user_id ?? $request->user()->id,
                'belongsToId' => $this->user_id ?? $request->user()->id
            ])->rules('required')->hideFromIndex()->hideFromDetail(),
BelongsTo::make('Author', 'user', User::class)->hideWhenCreating()->hideWhenUpdating(),
BelongsTo::make('Delegated', 'assigned_user', 'App\Nova\User')
            ->searchable()
            ->sortable(),
```

**Comment by abordage** [comment]
similar to #930

**Comment by 949mac** [comment]
Does your JavaScript console show any errors, like #956? Seems like the disabled portion might be similar.
