### ISSUE TITLE
Can't update user resource with encrypted fields

### ISSUE THREAD

**Issue by doriandigital** [laravel/nova-issues#937]
You can display the user resource table with encrypted fields by defining the setNameAttribute() and getNameAttribute() methods in the user model.

The problem is Laravel Nova throws the alert "Invalid payload" when trying to update the user record.

User Model:

`
namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Crypt;

class User extends Authenticatable {

	use Notifiable;

	protected $guarded = ['id'];

	protected $hidden = ['password', 'remember_token'];

	protected $attributes = [
		'active' => 1,
		'role' => 'editor'
	];

	public function setNameAttribute($value) {
		$this->attributes['name'] = Crypt::encryptString($value);
	}

	public function getNameAttribute($value) {
		return Crypt::decryptString($value);
	}

}
`

User resource:

`
namespace App\Nova;

use Illuminate\Http\Request;
use Laravel\Nova\Http\Requests\NovaRequest;
use Laravel\Nova\Fields\ID;
use Laravel\Nova\Fields\Text;

class User extends Resource {

	public static $model = 'App\Models\User';

	public static $title = 'email';

	public static $search = ['id', 'email'];

	// Fields
	public function fields(Request $request) {
		return [
			ID::make()->sortable(),
			Text::make('Email', 'email')->sortable()->rules('required', 'email', 'max:96')->creationRules('unique:users,email')->updateRules('unique:users,email,{{resourceId}}'),
			Text::make('First name', 'name')->sortable()->rules('required', 'max:64')
		];
	}
}
`

This featured is really important in order to be fully GDPR compliant.

**Comment by doriandigital** [comment]
UPDATE:

I found a way to do it.

1. Create a trait for encrypting strings.

```
namespace App\Traits;

use Illuminate\Support\Facades\Crypt;
use Illuminate\Contracts\Encryption\DecryptException;

trait CryptModel {

	// Encrypt attribute
	public function encrypt_attr($value) {
		if (is_null($value)) return;
		return Crypt::encryptString($value);
	}

	// Decrypt attribute
	public function decrypt_attr($value) {
		if (is_null($value)) return;
		try {
			return Crypt::decryptString($value);
		} catch (DecryptException $ex) {
			return $value;
		}
	}
}
```

2. Add the trait to the model getters and setters.

```
namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Traits\CryptModel;

class Member extends Authenticatable {

	use Notifiable, CryptModel;

	protected $table = 'members';

	/// Mutators

	// First name
	public function setFnameAttribute($value) {
		$this->attributes['fname'] = $this->encrypt_attr($value);
	}

	public function getFnameAttribute($value) {
		return $this->decrypt_attr($value);
	}
}
```

**Comment by szabizs** [comment]
A more elegant way would be to observe models via **model observers** or the **model boot method**.

   ```
public static function boot() {
        parent::boot();

        parent::creating(function($model) {
            $model->bitlocker_pin = encrypt($model->bitlocker_pin);
            $model->bitlocker_recovery_key = encrypt($model->bitlocker_recovery_key);
        });

        parent::updating(function($model) {
            $model->bitlocker_pin = encrypt($model->bitlocker_pin);
            $model->bitlocker_recovery_key = encrypt($model->bitlocker_recovery_key);
        });
        parent::retrieved(function($model) {
             $model->bitlocker_pin = decrypt($model->bitlocker_pin);
             $model->bitlocker_recovery_key= decrypt($model->bitlocker_recovery_key);
        });
    }
```
