### ISSUE TITLE
Defining multiple belongsToMany relationships in a resource with the same resourceName fails to pull correct pivot information

### ISSUE THREAD

**Issue by alexgarrett** [laravel/nova-issues#938]
- Laravel Version: 5.7.12
- Nova Version: 1.1.7
- PHP Version: 7.2.5

### Description:

Defining multiple `belongsToMany` relationships in a resource with the same `resourceName` fails to pull correct pivot information. It chooses the first available field based on the non-unique `resourceName`.

### Steps To Reproduce:

1. Define two `belongsToMany` relationships within a resource.

```php
// Nova/Resources/User.php

BelongsToMany::make('Saved courses', 'coursesSaved', Course::class)
    ->searchable(),

BelongsToMany::make('Favourited courses', 'coursesFavorited', Course::class)
    ->fields(function () {
        return [
            Textarea::make('Notes', 'notes'),
        ];
    })
    ->searchable(),
```

2. Navigate to the resource (in this case, `User`).
3. Edit the relationship (in this case `Favourited courses`).
4. Note that pivot is missing.

### Analysis:

This is due to the following code from `ResolvesFields.php` returning on the first find for the field's `resourceName`. Because both resources share the same resource name, the resource for `Saved courses` is returned (as it's defined first).

```php
protected function pivotFieldsFor(NovaRequest $request, $relatedResource)
{
    $field = $this->availableFields($request)->first(function ($field) use ($relatedResource) {
        return isset($field->resourceName) &&
                $field->resourceName == $relatedResource; // here
    });

    if ($field && isset($field->fieldsCallback)) {
        return collect(array_values(
            $this->filter(call_user_func($field->fieldsCallback, $request))
        ))->each(function ($field) {
            $field->pivot = true;
        });
    }

    return collect([]);
}
```

In my case I temporarily changed this to accurately pick the correct field based on a unique `manyToManyRelationship`.

```php
$field = $this->availableFields($request)->first(function ($field) use ($relatedResource, $request) {
    if (isset($field->manyToManyRelationship)) {
        return $field->manyToManyRelationship == $request->viaRelationship;
    }

    return isset($field->resourceName) &&
        $field->resourceName == $relatedResource;
});
```

Tests run fine after the `viaRelationship` query string parameter is taken into account within the tests.

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!

**Comment by lifeblood** [comment]
How to grouping resources?
