### ISSUE TITLE
Width of custom fields is 1/2 and cannot be modified

### ISSUE THREAD

**Issue by cjf** [laravel/nova-issues#940]
- Laravel Version: #.#.#
- Nova Version: 1.1.5
- PHP Version:

### Description:

Creating custom fields sets the parent div to 1/2 instead of 4/5.  This is not modifiable and poses problems creating fields where the extra space would be useful.

This is tangentially related to: https://github.com/laravel/nova-issues/issues/806

### Steps To Reproduce:

Create a custom field.

**Comment by noahlocke** [comment]
@cjf have you tried creating a `nova:theme` to override?

**Comment by markgp** [comment]
Set `:full-width-content="true"` on `<default-field>`

```
<template>
    <default-field :field="field" :errors="errors" :full-width-content="true">
        <template slot="field">
            Your full width field goes here
        </template>
    </default-field>
</template>
```

**Comment by markgp** [comment]
@cjf I looked through some of Nova's built in components in `nova/resources/js/components/Form` to see how they worked. In my case it was `TextareaField.vue` that gave me the answer I was looking for.

It's definitely an area the Nova docs could improve on.

**Comment by davidhemphill** [comment]
Closing as this seems solved.
