### ISSUE TITLE
Attach Relations: Class name must be a valid object or string

### ISSUE THREAD

**Issue by StanBarrows** [laravel/nova-issues#941]
- Laravel Version: 5.7.*
- Nova Version: 1.1.7
- PHP Version: 7,1,3

### Description:

![image](https://user-images.githubusercontent.com/10268813/48045932-a5ec4600-e192-11e8-9989-c3cd6476cdca.png)

### Steps To Reproduce:

1. Create a User Model
2. Create a Role Model

**User**

```
 BelongsToMany::make('Roles'),
```

**Role:**

```
 BelongsToMany::make('Users'),
```

**Visit Roles**

![image](https://user-images.githubusercontent.com/10268813/48045856-4a21bd00-e192-11e8-999c-8f23b185bdc4.png)

**Attach new User without trashed / Attach new User with trashed**

![image](https://user-images.githubusercontent.com/10268813/48045894-7fc6a600-e192-11e8-8cef-09d5aaa7d828.png)

**Comment by StanBarrows** [comment]
Any ideas? I'm Still receiving this error with Nova 1.2.1

**Comment by dkulyk** [comment]
You must to specify a related resource class name.
`BelongsToMany::make('Users', 'users', User::class),`

**Comment by StanBarrows** [comment]
Thanks for the message, I detected the problem. It only appears when you load the relation with a Trait and not directly on the model. Is this a Bug?

**Comment by bensalembilel** [comment]
I have the same issue. 
![Sans titre](https://user-images.githubusercontent.com/23087629/58256179-7aaff980-7d66-11e9-8a53-7952379d4d51.png)
-- code 
![Capture](https://user-images.githubusercontent.com/23087629/58256309-b054e280-7d66-11e9-95e9-3c66f31208c4.PNG)
![Capture1](https://user-images.githubusercontent.com/23087629/58256314-b2b73c80-7d66-11e9-8d18-5efdad71d753.PNG)

**Comment by dkulyk** [comment]
Third parameter is the resource class name.
