### ISSUE TITLE
Safari: Not able to click checkboxes

### ISSUE THREAD

**Issue by StanBarrows** [laravel/nova-issues#942]
- Laravel Version: 5.7.*
- Nova Version: 1.1.7
- PHP Version: 7,1,3
- Safari: Version 12.0.1 (13606.2.104.1.2)

### Description:

Not able to click these boxes on safari.

![image](https://user-images.githubusercontent.com/10268813/48045956-c0beba80-e192-11e8-835c-846bde3b9158.png)

**Comment by techouse** [comment]
I can confirm this behaviour. 

PHP: 7.2.11
Nova: 1.1.7
Laravel: 5.7.12
Safari: 12.0.1 (14606.2.104.1.1)
OS: macOS 10.14.1

**Comment by dillingham** [comment]
Duplicate https://github.com/laravel/nova-issues/issues/170 https://github.com/laravel/nova-issues/issues/533

Related: https://github.com/laravel/nova-issues/issues/86

**Comment by davidhemphill** [comment]
This has been fixed and will be included in an upcoming release.
