### ISSUE TITLE
[Vue warn] Duplicate keys detected: 'my-custom-card.undefined'

### ISSUE THREAD

**Issue by techouse** [laravel/nova-issues#943]
- Laravel Version: 5.7.12
- Nova Version: 1.1.7
- PHP Version: 7.2.11

### Description:
Multiple instances of the same `Laravel\Nova\Card` class (or `Laravel\Nova\Metrics\Value` class, `Laravel\Nova\Metrics\Trend` class or `Laravel\Nova\Metrics\Partition` for that matter) in defined in the `cards()` method inside `App\Providers\NovaServiceProvider` causes Vue to complain with a warning:

```
[Vue warn]: Duplicate keys detected: 'my-custom-card.undefined'. This may cause an update error.

found in

---> <Cards> at resources/js/components/Cards.vue
       <Dashboard> at resources/js/views/Dashboard.vue
         <Root>
```

### Steps To Reproduce:
1. Make a new plain blank `Laravel\Nova\Card` following the [documentation](https://nova.laravel.com/docs/1.0/customization/cards.html#defining-cards). You can also make any new metric as defined in the [documentation](https://nova.laravel.com/docs/1.0/metrics/defining-metrics.html#value-metrics).
2. Now instantiate your new `MyCustomCard` that `extends Laravel\Nova\Card` __at least twice__ in your `App\Providers\NovaServiceProvider`'s `cards()` method like this:
```php
/**
 * Get the cards that should be displayed on the Nova dashboard.
 *
 * @return array
 */
protected function cards()
{
    return [
        new MyCustomCard,
        new MyCustomCard,
    ];
}
```
3. Open your Nova project's dashboard in your browser of choice.
4. Open __Developer Tools__ and go to __Console__
5. Observe Vue complaining with an error saying:
```
[Vue warn]: Duplicate keys detected: 'my-custom-card.undefined'. This may cause an update error.

found in

---> <Cards> at resources/js/components/Cards.vue
       <Dashboard> at resources/js/views/Dashboard.vue
         <Root>
```
<img width="1501" alt="screenshot 2018-11-06 at 09 52 11" src="https://user-images.githubusercontent.com/1174328/48052955-ad6b1980-e1a9-11e8-95cb-b865f7b7592a.png">

**Comment by NVaissaud** [comment]
Hello,

You can overwrite jsonSerialize method from Laravel\Nova\Card by adding a name attribute.

```/**
     * Prepare the element for JSON serialization.
     *
     * @return array
     */
    public function jsonSerialize()
    {
        return array_merge([
            'name' => str_random(32), // Add this to avoid duplicate entry for the same custom card
            'width' => $this->width,
        ], parent::jsonSerialize());
    }```

**Comment by crzzano** [comment]
Looks like this fix no longer works - I am also using multiple instances of the same card on a Dashboard and I get the same duplicate key error. the jsonSerialize() solution doesn't work

**Comment by crzzano** [comment]
This solution works (in your custom Card class)

`public function jsonSerialize()
    {
        return array_merge([
            'uriKey' => Str::random(32), // Add this to avoid duplicate entry for the same custom card
            'width' => $this->width,
        ], parent::jsonSerialize());
    }`
