### ISSUE TITLE
Observer BelongsToMany pivot table

### ISSUE THREAD

**Issue by RespectPick** [laravel/nova-issues#944]
- Laravel Version: 5.7.11
- Nova Version: 1.1.7
- PHP Version: 7.2.9

### Description:

Perhaps this is not a bug but I did not find a solution.

I have three tables users, roles and players. And one pivot table user_role. I need update players table when the user is given the role Player. I have to observe my pivot table but nova doesn’t cause attach and detach methods.

**Comment by RespectPick** [comment]
@techouse Thanks man, it works but only for saving event. I`ve created UsersRolesObserver http://joxi.ru/J2b6Ov0F0xb0N2 . Saving event works well but when I delete Player role by user there is no reaction

**Comment by RespectPick** [comment]
@techouse oh sorry. I missed your first point. After I added this http://joxi.ru/a2X45M1Sw03Dg2 it is all ok. But can you tell me why Nova no longer shows success messenge ( http://joxi.ru/ZrJQ736fw38MzA ) ?

**Comment by techouse** [comment]
Hmm, don't know why it wouldn't trigger a notification since an `Observer` doesn't interfere here. You're basically just listening for `eloquent` events.

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!

**Comment by notflip** [comment]
@jbrooksuk Is this a feature that has been added to the latest version of Nova?

**Comment by smartens80** [comment]
Bumping this. Are observers or callbacks now available in Nova v2.x?

**Comment by AlbinoDrought** [comment]
In case anyone else is wondering, normal pivots and their observers work for me in Nova 3.13.0 without any non-Laravel code:

```php
class BookNote extends Model
{
    // ...
    public function books()
    {
        return $this->belongsToMany(Book::class)
            ->using(BookReference::class);
    }
    // ...
}
```

```php
class BookReferenceObserver
{
    public function created(BookReference $model)
    {
        // ...do something
    }

    public function deleted(BookReference $model)
    {
        // ...do something else
    }
}
```

```php
class AppServiceProvider
{
    // ...
    public function boot()
    {
        BookReference::observe(BookReferenceObserver::class);
    }
    // ...
}
```

Laravel doc links: 
- [Pivot Models](https://laravel.com/docs/8.x/eloquent-relationships#defining-custom-intermediate-table-models)
- [Observers](https://laravel.com/docs/8.x/eloquent#observers)

**Comment by stephenstack** [comment]
Only adding to this because it saved me. ☝️

     return $this->belongsToMany(Book::class)
            ->using(BookReference::class);

Make sure the Pivot Model is a type Pivot. Example below

<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Relations\Pivot;

class BookReference extends Pivot
{
    protected $table = 'book_reference';
    
    // If you need timestamps
    public $timestamps = true;
    
    // If you have any fillable fields in your pivot table
    protected $fillable = [
        'book_id',
        'page_id',
        // any other custom columns
    ];
}
