### ISSUE TITLE
How could I create a new custom view?

### ISSUE THREAD

**Issue by DianaR19** [laravel/nova-issues#948]
I would like to create a section where a view to those already loaded by default in Nova (resources) will be completely different.

**Comment by noahlocke** [comment]
@DianaR19 sounds like a `nova:tool`

**Comment by sabid** [comment]
@DianaR19 view this:

[https://novapackages.com/packages/devmtm/nova-custom-views](https://novapackages.com/packages/devmtm/nova-custom-views)

**Comment by DianaR19** [comment]
@sabid Do you have some example?

**Comment by DianaR19** [comment]
@noahlocke Do you have some example?

**Comment by DianaR19** [comment]
@sabid thanks !! it is a good packages :)
