### ISSUE TITLE
Action Log Error: Class name must be a valid object or string

### ISSUE THREAD

**Issue by StanBarrows** [laravel/nova-issues#949]
- Laravel Version: 5..7.*
- Nova Version: 1.1.7
- PHP Version: 7.1.3

### Description:

Following the Nova Doc: https://nova.laravel.com/docs/1.0/actions/defining-actions.html#action-log

- Class name must be a valid object or string Error
- Failed to load resource: the server responded with a status of 500 (Internal Server Error)
- Unhandled Promise Rejection: Error: Request failed with status code 500

 
### Steps To Reproduce:

- [ ] Initial Set-Up with Actionable Trait
- [ ] Section for actions visible in the User-Area
- [ ] Send out user invitation
- [ ] Receive an Error

**User-Model:**
```
use App\App\Traits\HasUuid;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Nova\Actions\Actionable;

class User extends Authenticatable
{
    use Actionable, Notifiable, SoftDeletes, HasUuid;

}
```
**User Actions:**
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/10268813/48113759-a94c0400-e25c-11e8-92b2-022e97b9a988.png">

**Run an Action:**
<img width="401" alt="image" src="https://user-images.githubusercontent.com/10268813/48113842-fc25bb80-e25c-11e8-8a2d-bfe8ab2d3715.png">

**Action:**
```
public function handle(ActionFields $fields, Collection $models)
    {
        try {
            foreach ($models as $model) {
                $model->notify(new SendPlatformInvitationNotification($model));
            }

            return Action::message('It worked!');
        } catch (\Exception $exception) {
            // @Todo Log

            return Action::danger('Something went wrong!');
        }
    }
```

<img width="477" alt="image" src="https://user-images.githubusercontent.com/10268813/48113953-59ba0800-e25d-11e8-900d-01d14d7e3d92.png">

**Errors:**
<img width="1367" alt="image" src="https://user-images.githubusercontent.com/10268813/48113958-62aad980-e25d-11e8-8874-f95d8d29396f.png">

<img width="1478" alt="image" src="https://user-images.githubusercontent.com/10268813/48113997-971e9580-e25d-11e8-88a8-1e8a390a0826.png">

**Comment by Quinndark** [comment]
I have met the same question.

**Comment by davidhemphill** [comment]
Sorry, but we are unable to debug your issue without a reproducible code example. Once you provide that we can open this up again.

**Comment by phuclh** [comment]
I have the same issue.
