### ISSUE TITLE
[error] Incorrect work Number field with value 0

### ISSUE THREAD

**Issue by academici** [laravel/nova-issues#951]
- Laravel Version: 5.7.13
- Nova Version: 1.1.7
- PHP Version: 7.2.10

### Description:
1. Create unsignedInteger field default 0
2. In Resource: Number::make('Discount'),
3. Create record with "0" value
4. On edit resource give error: discount cant be null
5. Clear discount value, set "0"
6. Resource was updated

### Steps To Reproduce:
none

P.S.
Saw similar closed issues, but i have latest nova version

**Comment by dillingham** [comment]
confirmed / reproduced | related https://github.com/laravel/nova-issues/issues/562 https://github.com/laravel/nova-issues/issues/840 https://github.com/laravel/nova-issues/issues/500 https://github.com/laravel/nova-issues/issues/122

**Comment by davidhemphill** [comment]
This has been fixed and will be included in an upcoming release.

**Comment by msassa** [comment]
> This has been fixed and will be included in an upcoming release.

Sorry, @davidhemphill where this is fixed? I have the 1.3.2 version, and it still happens
