### ISSUE TITLE
BelongsTo "with trashed" checkbox not checkable on Safari

### ISSUE THREAD

**Issue by Yazan-Stash** [laravel/nova-issues#952]
- Laravel Version: 5.7.13
- Nova Version: 1.1.7
- PHP Version: 7.2.9
- Browser: Safari 12.0 (12606.2.11)

### Description:
When defining a BelongsTo field, a small "with trashed" checkbox will appear on create and update, on Safari this checkbox can not be checked. tried it on Firefox and it worked no problem.

### Steps To Reproduce:
- Define a belongsTo relation on a model
- Seed related soft-deletable model with deleted and non-deleted rows
- Check "with trashed" checkbox to create a new model attaching it to a soft-deleted model

**Comment by dillingham** [comment]
Related: https://github.com/laravel/nova-issues/issues/86 https://github.com/laravel/nova-issues/issues/170 https://github.com/laravel/nova-issues/issues/533 https://github.com/laravel/nova-issues/issues/196 https://github.com/laravel/nova-issues/issues/952

**Comment by dillingham** [comment]
Related: https://github.com/laravel/nova-issues/issues/86 https://github.com/laravel/nova-issues/issues/170 https://github.com/laravel/nova-issues/issues/533 https://github.com/laravel/nova-issues/issues/196 https://github.com/laravel/nova-issues/issues/952

**Comment by davidhemphill** [comment]
This has been fixed and will be included in an upcoming release.

**Comment by BobbyBorisov** [comment]
@dillingham @Yazan-Stash @davidhemphill sorry to ask here guys, but is there a way to disable visibility of "with trashed" checkbox? I cannot find it in the docs. Thanks in advance

**Comment by Yazan-Stash** [comment]
@BobbyBorisov As far as I understand it, Laravel uses the static $softDeletes array on the resource to determine if this resource is soft-deletable or not, so you can override it like this
```php
public static $softDeletes = ['Your\\Resource\\Name' => false];
```
hope that helps, best.

**Comment by mf16** [comment]
If all your Nova models extend an `app/Nova/Resource.php` that extends `NovaResource` (I think Nova defaults with this) you can add the above array there for all the models you want to override. It doesn't affect actual softDeleting functionality, even via Nova.
