### ISSUE TITLE
ResetPassword notification subject can't be translated

### ISSUE THREAD

**Issue by danielghitoiu** [laravel/nova-issues#953]
- Laravel Version: 5.6.39
- Nova Version: 1.1.7
- PHP Version: 7.2.5

### Description:
ResetPassword email notification subject is imposible to translate because it is created from class name

### Steps To Reproduce:
- in ForgotPasswordController a callback is registered in construct as follow 
```  ResetPassword::toMailUsing(function ($notifiable, $token) {
            return (new MailMessage)
                ->line(__('You are receiving this email because we received a password reset request for your account.'))
                ->action(__('Reset Password'), url(config('app.url').route('nova.password.reset', $token, false)))
                ->line(__('If you did not request a password reset, no further action is required.'));
        });
```

This will run instead of what it was declared in laravel/framework/src/Illuminate/Auth/Notifications/ResetPassword.php ->toMail()

```    
 return (new MailMessage)
            ->subject(Lang::getFromJson('Reset Password Notification'))
            ->line(Lang::getFromJson('You are receiving this email because we received a password reset request for your account.'))
            ->action(Lang::getFromJson('Reset Password'), url(config('app.url').route('password.reset', $this->token, false)))
            ->line(Lang::getFromJson('If you did not request a password reset, no further action is required.'));
```

As you can see here subject is specified and can be translated. 

A simple solution will be to do the same in Nova ForgotPasswordController.

**Comment by bonzai** [comment]
This was fixed in version 1.2.0.

https://nova.laravel.com/releases
