### ISSUE TITLE
Metric uriKey contains forward slash via Artisan Command

### ISSUE THREAD

**Issue by 949mac** [laravel/nova-issues#954]
- Laravel Version: 5.7
- Nova Version: 1.1.7

### Description:
When running `php artisan nova:value Value/Prospects`, created Metric contains a forward slash in the uriKey.

![image](https://user-images.githubusercontent.com/23151962/48214957-0798e580-e336-11e8-96d4-b1cfd4bf7ca0.png)

### Steps To Reproduce:
Run `php artisan nova:value Value/Prospects`

**Comment by davidhemphill** [comment]
This has been fixed and will be included in the next release. 👍

**Comment by 949mac** [comment]
Thank you, David!
