### ISSUE TITLE
viewAny not accessible with `__call()` on Policy

### ISSUE THREAD

**Issue by blackfyre** [laravel/nova-issues#958]
- Laravel Version: 5.7.13
- Nova Version: 1.1.7
- PHP Version: 7.1

### Description:
The `viewAny()` method has to exist on the Policy to be usable, because the `__call()` magic method doesn't respond to it. It works with the others: `view`, `create`, `update`, `delete`, `restore`, `forceDelete`

### Steps To Reproduce:
1. Create a policy and add a "magic" gate to it
```php
public function __call($name, $arguments)
    {
        if ($arguments[0] instanceof User) {
            dump('your-policy-name-' . $name);
            return $arguments[0]->hasPermissionTo('your-policy-name-' . $name);
        }

        return false;
    }
```
2. Fire up the dump server
3. Try to access the resource
4. Resource appears on the UI, `your-policy-name-viewAny` won't appear on the dump list.

**Comment by szymon-podeszwa** [comment]
I think, your issue is related to my issue.

#1161

**Comment by Peter-Mulligan** [comment]
Still an issue in 2.0

**Comment by dkulyk** [comment]
Magic methods doesn't work for policy. You need to implement `viewAny` and other methods.
Policy has default value If method doesn't exists.

**Comment by davidhemphill** [comment]
You should implement the methods on your Policy instead of using `__call`.

**Comment by allanvb** [comment]
If someone's intrested, the problem could be solved just by overriding `authorizedToAdd`, `authorizedToAttachAny`, `authorizedToAttach`, `authorizedToDetach` inside **Resource** base class of your app. 

_Actual for nova 3.32 (did not tested on nova 4.x_
