### ISSUE TITLE
[Feature Request] onlyWhenExists field display

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#959]
- Laravel Version: 5.7
- Nova Version: 1.1.7
- PHP Version: 5.7

### Description:
In some cases, only showing a field or relationship when present is desirable. 

### Steps To Reproduce:

```php

Text::make('Closed At')->canSee(function() {
    return $this->closed_at != null;
})

HasMany::make('Users')->canSee(function() {
    return $this->users()->count() != 0;
})
```
### Requested Syntax

```php
Text::make('Closed At')->whenExists(),
HasMany::make('Users')->whenExists(),
```

^ Would tie together nicely with [onlyOnDetail ](https://nova.laravel.com/docs/1.0/resources/fields.html#showing-hiding-fields)etc

**Comment by crnkovic** [comment]
Even though there's a `when` method, I find myself using this a lot, such as when showing the `deleted_at` field, so I think this would be a nice addition.

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
