### ISSUE TITLE
Feature Request: Extend existing fields

### ISSUE THREAD

**Issue by noahlocke** [laravel/nova-issues#96]
Perhaps this is already an option, but I didn't see anything in the documentation. My use case is that I need a BelongsTo field that has some dynamic UI properties. Easiest thing in my mind is to extend the already created BelongsTo field class, rather than starting over with a completely new field. Obviously this could be awesome for all field types, but the challenge seems to be that we're not just talking extending a class, but we'd want to extend the Vue components as well...

Something like `php artisan nova:field acme/dynamicBelongsTo --extends=BelongsTo` ?

**Comment by noahlocke** [comment]
An update: I've successfully "extended" a few fields now. A few of them we're more trouble that they're worth (tried Trix, ran into issues with trying to instantiate trix-toolbar twice, gave up). But was able to add the Trumbowyg field just fine and extend the Excerpt Vue component. Also was able to extend BelongsTo, but I opted to just copy/paste the component and update the import paths... still feels really hacky.

**Comment by fdabek1** [comment]
@noahlocke How did you handle extending the fields?  I am trying to extend the BelongsTo field, but when the extends in my component (extends: BelongsTo), I get the following error:

> import storage from '@/storage/BelongsToFieldStorage'

**Comment by noahlocke** [comment]
@fdabek1 to successfully clone and extend the BelongsTo field, you need to make sure and install the vue-clickaway package, `npm install vue-clickaway --save`, in your custom field. 

You can import the BelongsToFieldStorage with:

```
import storage from '../../../../../nova/resources/js/storage/BelongsToFieldStorage.js'
```

**Comment by fdabek1** [comment]
@noahlocke I actually labored, but found a solution using webpack which I am going to leave here for anybody that needs it in the future:

Place this inside of webpack.mix.js for the webpackConfig:

```
     resolve: {
            alias: {
                '@/storage': path.resolve(__dirname, '../../nova/resources/js/storage'),
            },
            modules: [
                path.resolve(__dirname, '../../nova/node_modules/'),
            ],
            symlinks: false
        }
```

And then in my case I wanted the field to emit values for another new custom field to get those:

```
<script>
    import BelongsTo from '../../../../../nova/resources/js/components/Form/BelongsToField';

    export default {
        extends: BelongsTo,

        methods: {
            selectResourceFromSelectControl(e) {
                BelongsTo.methods.selectResourceFromSelectControl.call(this, e);
                Nova.$emit("question-type-selected", {
                    value: e.target.value,
                });
            },
        },
    }
</script>
```

This avoids needing to rewrite any code for a BelongsTo selector, but at the same time lets you create a custom field that gets changes made to the BelongsTo selector by doing this in the new field:

```
created() {
        Nova.$on("question-type-selected", async value => {
            console.log('value', value);

        });
    },
```

**Comment by davidhemphill** [comment]
There's no plan to support extending fields at the moment. It's best to use the custom field system/mixins instead.

**Comment by TheSETJ** [comment]
I need this too.

Consider you need a limited `Textarea` field with customizable max length which in the form displays how many characters are remaining.

With that said, I wish I could create `LimitedTextarea` field extending Nova's `Textarea` field and only implement a custom `FormField` and for index and detail, fallback to Nova's default components for the `Textarea` field.
