### ISSUE TITLE
[Feature Request] alwaysShowTitle() for unauthorized

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#960]
- Laravel Version: 5.7
- Nova Version: 1.17
- PHP Version: 5.7

### Description:
Sometimes a user is not authorized view a belongsTo relationship.
It removes completely from the related resource when not authorized.
In some cases, keeping the `$title` displaying as plain text is the desired outcome.

### Desired syntax
```php
BelongsTo::make('User')->alwaysShowTitle()
```

^ Assuming the authenticated user doesn't have permissions to view Users
^ This would allow them to see the user's name on the resource regardless
^ On index & detail

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
