### ISSUE TITLE
code over line numbers

### ISSUE THREAD

**Issue by Enmaboya** [laravel/nova-issues#962]
Why is the first line always displayed over the line number?
and also when moving to a new line, the printing of the text starts before the number

![image](https://user-images.githubusercontent.com/32259003/48344454-8bcccf00-e68e-11e8-8601-14fbd4f85987.png)

and after saving

![image](https://user-images.githubusercontent.com/32259003/48345319-2b8b5c80-e691-11e8-9a1b-42c5d7c303ba.png)

**Comment by davidhemphill** [comment]
We are unable to debug your issue without a reproducible code example.
