### ISSUE TITLE
Index Filtering error only with User resource

### ISSUE THREAD

**Issue by carloshc** [laravel/nova-issues#963]
- Laravel Version: 5.7.13
- Nova Version: 1.1.7
- PHP Version: 7.2.9

### Description:

Index Filtering error only with User resource.

### Steps To Reproduce:

1. Open the `App\Nova\Resource.php`
2. Copy the entire method `indexQuery`
3. Past in `App\Nova\User.php` and do not make any modifications
4. Go to the User resource in browser

**Output error (Warning)**

`Declaration of App\Nova\User::indexQuery(App\Nova\NovaRequest $request, $query) should be compatible with App\Nova\Resource::indexQuery(Laravel\Nova\Http\Requests\NovaRequest $request, $query)
`

**Additional info**

I have another two resources with index filtering working.

**Code fragment `App\Nova\User.php`**
 
```php
namespace App\Nova;

use App\Rules\CursoPoloUserRule;

use Illuminate\Http\Request;

use Laravel\Nova\Fields\ID;
use Laravel\Nova\Fields\Text;
use Laravel\Nova\Fields\Gravatar;
use Laravel\Nova\Fields\Password;
use Laravel\Nova\Fields\Select;
use Laravel\Nova\Fields\BelongsToMany;
use Laravel\Nova\Fields\MorphToMany;

class User extends Resource
{
    public static $model = 'App\\User';
    public static $title = 'name';

    public static $search = [
        'id', 'name', 'email'
    ];

    public static function label()
    {
        return __('Usuários');
    }

    public static function singularLabel()
    {
        return __('Usuário');
    }

    public static function indexQuery(NovaRequest $request, $query)
    {
        return $query;
    }

(...)

}
```

**Comment by bonzai** [comment]
You're missing import:

```php
use Laravel\Nova\Http\Requests\NovaRequest;
```

**Comment by carloshc** [comment]
You're right, thank you.

The resources created with `artisan nova:resource` does not need to import `Laravel\Nova\Http\Requests\NovaRequest`.

Thank you.
