### ISSUE TITLE
Is Laravel Nova Dead?

### ISSUE THREAD

**Issue by uwascan** [laravel/nova-issues#964]
Hello?
There appears to be a lot unresolved issues so permit me to ask Is Laravel Nova Dead?

**Comment by davidhemphill** [comment]
No.

**Comment by dillingham** [comment]
Fruitful

**Comment by dillingham** [comment]
Fruitful

**Comment by albalooshi** [comment]
A roadmap for Nova will be also nice

**Comment by iAmGuus** [comment]
I really do hope nova will not be discontinued as I really like it and my business depends on it! :+1:

**Comment by davidhemphill** [comment]
If Nova is discontinued I will be out of a job. 😅

**Comment by tristanbailey** [comment]
We have enjoyed offering clients the nova admin, so glad to here it, didn't think was an issue.

David, thanks for the support help the other day.

**Comment by dillingham** [comment]
It seems like a lot for one person to handle. I’m not sure why @taylorotwel doesn’t add Dries Vints to the equation atleast until stable and avoid the comments like this https://github.com/laravel/nova-issues/issues/273#issuecomment-440643436 not my business and not trying to be rude, or offend anyone.. but I put faith into this like many others and letting bugs ride for as long as they have doesn’t seem “production ready” as it was promoted.

**Comment by albalooshi** [comment]
@dillingham Nova is one of the best packages (if you can call it that) out there. Its a shame that is getting treated like this. I wouldn't mind paying more if it will have more attention from the developers. 

Lets hope Taylor assign more people for Nova to help David do his job...

**Comment by tiagosimoesdev** [comment]
@albalooshi  I think a lot of people like myself thinks that $100 for a package per project is high enough.

**Comment by dillingham** [comment]
@albalooshi I agree on how great it is. And I would pay more too. I even paid 3rd party package developers to add certain features sooner than later. Yes fingers crossed because I definitely think David needs more support

**Comment by albalooshi** [comment]
@tiagosimoesdev We need quality and responsiveness from the developer. If that requires money than they should raise the prices. 

There are many great packages out there are free or cheaper for people who cant afford it.

**Comment by albalooshi** [comment]
@mkarnicki 
>  (and I/you can always contribute with bugfixes).
You currently cant #233 , at least not with pull requests.
