### ISSUE TITLE
Show delete action if check passes

### ISSUE THREAD

**Issue by mhetreramesh** [laravel/nova-issues#965]
I wants have a provision to hide delete action for few rows on the basis of some check on the model. Is it possible to make this provision quickly?

Just don't show delete icon, like:
![icons](https://user-images.githubusercontent.com/3095445/48365723-ffc9a000-e6ab-11e8-9166-7f9ce54fd921.png)

**Comment by davidhemphill** [comment]
Use the `authorizedToDelete` method on the Resource.

**Comment by StanBarrows** [comment]
Is this checking for each row or the entire resource?

**Comment by mhetreramesh** [comment]
It worked, thanks.
