### ISSUE TITLE
Optional $morphTitle for resources

### ISSUE THREAD

**Issue by dillingham** [laravel/nova-issues#966]
- Laravel Version: 5.7
- Nova Version: 1.1.7

### Description:

When you `morphTo::make()` it shows the resource title, in most cases thats awesome!
But it becomes redundant if you make your title "Order #1" `order: Order #1`
So in viewing a relationship being morphed, it would be handy to say just the id format

### Steps To Reproduce:

```php
public function title()
{
    return "Order #$this->id";
}
```
### Requested synax
```php
$morphTitle = 'id';

function morphTitle() {
    //
}

// or maybe on the method?

MorphTo::make()->displayUsingId()
MorphTo::make()->showIDFormat()
```

Which basically opts for id `order: 1`

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
