### ISSUE TITLE
Unable to set default values on BelongsToMany

### ISSUE THREAD

**Issue by rjksn** [laravel/nova-issues#967]
- Laravel Version: 5.7.9
- Nova Version: 1.1.7
- PHP Version: 7.2.9 (Homestead)

### Description:

Unable to set default values for Pivot fields in BelongsToMany in Laravel Nova. Updating MySQL to accept null, ignores the default value set in MySQL. Need to pass in value to use Nova, and I'm at a loss. 

### Steps To Reproduce:

Create a model with a BelongsToMany relation and add data to the pivot tables. 

        return $this->belongsToMany(Campaign::class)->withPivot('processing', 'budget', 'spend');

        return $this->belongsToMany(Client::class)->withPivot('processing', 'budget', 'spend');

Create a Nova Model for both the paired Models and add in the fields special code.

            BelongsToMany::make('Campaigns')->fields(function () {
                return [
                    Number::make('Budget'),
                    Number::make('Spend'),
                ];
            })->sortable(),

            BelongsToMany::make('Clients')->fields(function () {
                return [
                    Number::make('Budget'),
                    Number::make('Spend'),
                ];
            })->sortable(),

My default values in the database are default 0. 

        Schema::table('campaign_client', function (Blueprint $table) {
            $table->integer('budget')->unsigned()->default(0);
            $table->integer('spend')->unsigned()->default(0);
        });

**Comment by webspilka** [comment]
Can you try set attributes at your models Client adn Campaign
```php
protected $attributes = ['budget' => 0, 'spend' => 0];
```

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
