### ISSUE TITLE
Default attachable/relatable validation rules not used with custom relationship name

### ISSUE THREAD

**Issue by ThomHurks** [laravel/nova-issues#969]
- Laravel Version: 5.7.13
- Nova Version: 1.1.7
- PHP Version: 7.2.12

### Description & Steps To Reproduce:
In my application I have the typical "User" and "Role" BelongsToMany relationship which works fine in Nova out-of-the-box. If a user already has a role and you try to add it again, you get an error message saying "This role is already attached.". Nice!

However, things break down if you customize things  a bit. In my application I also have two other models called "Sitestatus" and "Sitereason". These two models also have a many-to-many relationship. However, the BelongsToMany relationship on the "Sitestatus" model to "Sitereason" is called "reasons", not "sitereasons", for aesthetic purposes because I don't like to repeat the word "site" too much.
```PHP
public function reasons()
    {
        return $this->belongsToMany('App\Sitereason')->withTimestamps();
    }
```

Accordingly, in the Nova code to display the "Sitereason" relationship on the "Sitestatus" resource I use the following:
```PHP
BelongsToMany::make('Fix reasons', 'reasons', Sitereason::class),
```
So display the resource in the Nova UI as "Fix reasons", but the actual relationship to be used is called "reasons" and the resource to use is the "Sitereason" Nova resource. This seems to work superficially, but if I go to a "Sitestatus" in Nova and try to add a "Sitereason" that is already added, I get an exception that a duplicate entry is being inserted in the database!

I debugged this quite a bit and the problem is the following:
When I try to attach a new resource, the client sends the resource ID to the server using the ```uriKey()``` of the resource. In my case, the ```uriKey``` of "Sitereason" is "sitereasons":
```PHP
public static function uriKey()
    {
        return Str::plural(Str::snake(class_basename(get_called_class()), '-'));
    }
```
When Nova tries to validate my request to attach the resource, it takes the incoming request data, and filters it first and then validates that. I specified the name of the BelongsToMany relationship to be "reasons" because I thought that name looked nicer than "sitereasons", remember? So the "attribute" of that BelongsToMany relationship is "reasons". Nova filters all request data away except "reasons", so unfortunately "sitereasons" is also filtered away and we validate an empty array. This works of course (there's nothing to validate), so the request executes and Nova tries to create a duplicate entry in the database, causing the exception. (I assume some other code maps the "uriKey" name in the request to the actual relationship name correctly, because otherwise the query wouldn't work at all.)

This is the code where the mismatch happens (PerformsValidation.php):
```PHP
 public static function creationRulesFor(NovaRequest $request, $field)
    {
        return static::formatRules($request, (new static(static::newModel()))
                    ->availableFields($request)
                    ->where('attribute', $field)
                    ->mapWithKeys(function ($field) use ($request) {
                        return $field->getCreationRules($request);
                    })->all());
    }
```
In this function, the "field" variable is "sitereasons", this is the ```uriKey``` of the resource and that's the key that the client sends to the server in the request. You can see that Nova filters by doing ```->where('attribute', $field)```, and "attribute" is what we set to be "reasons", so there's no match and the list of fields to be validated becomes empty. As such the BelongsToMany field is not validated with the usual ```RelatableAttachment``` and ```NotAttached``` rules and so we don't get a nice error saying that the resource is already attached.

I can show what the content of ```availableFields``` is before the filter step:
```JSON
[
{
...some other (text) fields
},
{
    "component": "belongs-to-many-field",
    "prefixComponent": true,
    "indexName": "Fix reasons",
    "name": "Fix reasons",
    "attribute": "reasons", <-- the actual relationship name that I set.
    "value": null,
    "panel": null,
    "sortable": false,
    "textAlign": "left",
    "resourceName": "sitereasons", <-- the uriKey that the client sends. Mismatch!
    "belongsToManyRelationship": "reasons", <-- BelongsToMany ctor sets it equal to $this->attribute
    "searchable": false,
    "listable": true,
    "singularLabel": "Fix reason"
  }
]
```

Expected behaviour is that the validation code of Nova works correctly when the name of a relationship doesn't happen to be the plural of the model name (so equal to uriKey). I should be able to name a relationship "foobar" in my model and if I tell Nova that my relationship is called "foobar", then it should work.

**Comment by mikaelpopowicz** [comment]
Relative to #854 

Hi @ThomHurks you may override the `validatorForAttachment` and `validatorForAttachmentUpdate` resource methods.

```php

    public static function validatorForAttachment(NovaRequest $request)
    {
        $validator = parent::validatorForAttachment($request);
        $attribute = $request->input('viaRelationship', false);

        if (filled($attribute)) {
            $field = (new static(static::newModel()))
                ->availableFields($request)
                ->firstWhere('attribute', $attribute);

            if (filled($field) && $field->resourceName !== $field->attribute) {
                $name = $field->resourceName;
                $rules = static::creationRulesFor($request, $attribute);
                $rules[$name] = $rules[$attribute];

                $relationValidator = Validator::make($request->all(), $rules, [], [
                    $name => $field->name,
                ]);

                if (! $relationValidator->passes() && $relationValidator->errors()->has($name)) {
                    $validator->after(function ($validator) use ($name, $relationValidator, $attribute) {
                        $validator->errors()->add($attribute, $relationValidator->errors()->first($name));
                    });
                }
            }
        }

        return $validator;
    }

    public static function validatorForAttachmentUpdate(NovaRequest $request)
    {
        $validator = parent::validatorForAttachmentUpdate($request);
        $attribute = $request->input('viaRelationship', false);

        if (filled($attribute)) {
            $field = (new static(static::newModel()))
                ->availableFields($request)
                ->firstWhere('attribute', $attribute);

            if (filled($field) && $field->resourceName !== $field->attribute) {
                $name = $field->resourceName;
                $rules = static::updateRulesFor($request, $attribute);
                $rules[$name] = $rules[$attribute];

                $relationValidator = Validator::make($request->all(), $rules, [], [
                    $name => $field->name,
                ]);

                if (! $relationValidator->passes() && $relationValidator->errors()->has($name)) {
                    $validator->after(function ($validator) use ($name, $relationValidator, $attribute) {
                        $validator->errors()->add($attribute, $relationValidator->errors()->first($name));
                    });
                }
            }
        }

        return $validator;
    }
```

The inner validator use validation rules of the field based on the `attribute` to validate the `resourceName` input. If the validation fails, it adds the first `attribute` error as `resourceName` error.

**Comment by NioTeX** [comment]
This is a pretty big issue when you have multiple relationships between the same 2 models, because at least one of them needs to have a custom name.
Are there any plans to look at this in the near future?

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!

**Comment by mikmar-ao** [comment]
I have found solution! In your resource just overwrite this function to return same name which is your model relation name and everything will work. 

`public static function uriKey()
    {
        return 'results';
    }`
