### ISSUE TITLE
Internals feature request. Field::withHref('url', $attributes)

### ISSUE THREAD

**Issue by danrichards** [laravel/nova-issues#97]
I'm not sure if this repo's issues are the appropriate forum for feature requests. Maybe update that `readme.md` ;)

I think people would find it immensely helpful to be able to add an href to the content rendered with the native fields. I'm aware Nova automagically links in other related resources. But there are plenty of external resources, tools, etc where it would come in handy to have a href on a native field.

Here goes examples:

```
// A field with a link
Text::make('Email')->withHref("mailto:{$this->email}");

// Overloading the default link
BelongsTo::make('Store')->withHref("nova/my-special-tool/{$this->id}");

// A computed field with a link in a new tab
Text::make('Domain', function() {
    return "{$this->subdomain}.myspecialwebsite.com";
})->withHref("https://{$this->subdomain}.myspecialwebsite.com", ['target' => '_blank']);
```

I understand this may be attainable using a custom field (which I'm going to look into next), but feel it belongs apart of the native inputs, even for overloading the default resource functionality like the example above.

Thank you for the awesome tool.

**Comment by pdewit** [comment]
You can do the last one with my package: [pdewit/nova-external-url](https://github.com/pdewit/nova-external-url)

**Comment by danrichards** [comment]
Thanks @pdewit I noticed your package this other day. Very helpful.

I still think internal support would be better. Other functionality (like sorting) within the fields could be preserved.

**Comment by davidhemphill** [comment]
This repo is for bug reports only but you can use a computed Text field to return whatever HTML you'd like: https://nova.laravel.com/docs/1.0/resources/fields.html#computed-fields
