### ISSUE TITLE
Relationships loaded when hidden

### ISSUE THREAD

**Issue by jasonlav** [laravel/nova-issues#970]
- Laravel Version: 5.6.39
- Nova Version: 1.1.7
- PHP Version: 7.2.1

### Description:
On a resource index, relationships are loaded even when the field is `->hiddenFromIndex()`. Discovered with the `belongsTo` and `belongsToMany` relationship fields, however, does not appear to be isolated to those.

Relationship is not being eager loaded in the model or Nova resource.

### Steps To Reproduce:
Create a Nova resource with a `BelongsTo` field that is hidden from the index. Examine database queries on resource index load.

**Comment by aramirez92** [comment]
Try adding `->hideFromDetail()`

**Comment by krns** [comment]
We have the same problem, but only with `belongsTo` fields. `belongsToMany` works fine.

Another observation is that every row in the list (index view) executes one database query – does anybody else have this?

**Comment by krns** [comment]
Maybe related to https://github.com/laravel/nova-issues/issues/112

**Comment by dkulyk** [comment]
This has been fixed and will be included in an upcoming release.
