### ISSUE TITLE
Duplicate policy requests

### ISSUE THREAD

**Issue by jasonlav** [laravel/nova-issues#972]
- Laravel Version: 5.7.4
- Nova Version: 1.1.7
- PHP Version: 7.2.1

### Description:
Nova makes a lot of (duplicate) gate calls, even in the most basic of resource configuration.

{resource}/cards
viewAny - App\User (2)

{resource}/filters
viewAny - App\User (2)

{resource}/lenses
viewAny - App\User (2)

{resource}/count
viewAny - App\User (2)

{resource}/actions
viewAny - App\User (4)

{resource}/search
update - App\User (25 [once per row])
delete - App\User (25 [once per row])
view - App\User (25 [once per row])
viewAny - App\User (25 [once per row] + 3)

User resource index load of 25 users yields 115 policy calls with 40 duplicate calls. User resource index load of 100 users yields over 400 policy calls. Add soft deletes, relationships, filters, and permissions per-field and policy calls can quickly easily exceed 1000.

Add in a traditional permission system to policies can turn a 300ms page load to a 4-5 second load for 25 results.

At the very least, `viewAny` should not be called every row.

### Steps To Reproduce:
Create a nova resource with an associated policy and look at the gate calls.

**Comment by bobinrinder** [comment]
Same issue for us, this slows down Nova significantly.

**Comment by tolawho** [comment]
Nova doesn't have any update from a month ago.

**Comment by dillingham** [comment]
Any update on this?

**Comment by dkulyk** [comment]
It depends of permissions library. You can cache permissions in policies.

**Comment by dillingham** [comment]
I agree with @dkulyk I stored them in the session

**Comment by webhealer** [comment]
I use redis as a cache server, it works super fast.

**Comment by ppisecky** [comment]
Is anyone using Laravel Bouncer? With Bouncer I am getting some bad performance even with cross-request caching and redis both in local environment as well as on DigitalOcean.

One way I think the performance could be improved is to avoid checking `viewAny` for each row and also denying authorization to restore if the model isn't soft deleted in the first place. So in my base `Resource` class implemented overrides of some two of the authorization methods:

```php
    /**
     * Prepare the resource for JSON serialization.
     *
     * @param  \Laravel\Nova\Http\Requests\NovaRequest  $request
     * @param  \Illuminate\Support\Collection  $fields
     * @return array
     */
    public function serializeForIndex(NovaRequest $request, $fields = null)
    {
        return array_merge($this->serializeWithId($fields ?: $this->indexFields($request)), [
            'authorizedToView' => $this->authorizedToView($request),
            'authorizedToUpdate' => $this->authorizedToUpdateForSerialization($request),
            'authorizedToDelete' => $this->authorizedToDeleteForSerialization($request),
            'authorizedToRestore' => static::softDeletes() && $this->isSoftDeleted() && $this->authorizedToRestore($request), //make sure the model is soft deleted in the first place
            'authorizedToForceDelete' => static::softDeletes() && $this->authorizedToForceDelete($request),
            'softDeletes' => static::softDeletes(),
            'softDeleted' => $this->isSoftDeleted(),
        ]);
    }


    /**
     * Determine if the current user can view the given resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return bool
     */
    public function authorizedToView(Request $request)
    {
        return $this->authorizedTo($request, 'view'); // don't check authorization to `viewAny`
    }
```

Though I'm not sure what the security implications are with this hotfix. Any tips @dkulyk?

**Comment by nasrulhazim** [comment]
I cache them all to speed up. I cache it for a minute only for some reason.

**Comment by dkulyk** [comment]
@ppisecky Nova use standard Policy checks. You need to cache results in the policy or your permission package.

**Comment by davidhemphill** [comment]
Cache the policy checks.

**Comment by gavinhewitt** [comment]
> Nova use standard Policy checks. You need to cache results in the policy or your permission package.

Probably silly question, but how do you exactly cache policies? I can't find any docs on this?

**Comment by dillingham** [comment]
@gavinhewitt 

- listen for login event
- store permission array on the user's session
- update your policies to check that array

**Comment by gavinhewitt** [comment]
Ah! Thanks @dillingham

**Comment by simpsons310** [comment]
> @gavinhewitt
> 
> * listen for login event
> * store permission array on the user's session
> * update your policies to check that array

Hi, It's such a good way. But how do you update session in case that user's permission was changed by another user.
