### ISSUE TITLE
Relatable query This may not be associated with this resource

### ISSUE THREAD

**Issue by RespectPick** [laravel/nova-issues#973]
- Laravel Version: 5.7.11
- Nova Version: 1.1.7
- PHP Version: 7.2

Description:

I have championship and users. One user belongs to championship as judge. But I have to select only users who have role 'Judge'

### Steps To Reproduce:

I created new BelongsTo field

```
            BelongsTo::make('Main judge', 'mainJudge', User::class)
                ->hideFromIndex()
                ->searchable()
                ->nullable(),
```
than created method relatableUsers

```
    public static function relatableUsers(NovaRequest $request, $query)
    {
        return $query->join('users_roles', 'users.id',  '=', 'users_roles.user_id')
            ->join('roles', 'users_roles.role_id', '=', 'roles.id')
            ->where('roles.alias', '=', 'judge');
    }
```

but when I try to save my resource i got an error 

> This main judge may not be associated with this resource

I tried dump this. When I don't use relatableUsers method, I got a user id == 2, but when I use I got a user id == 6. But ID 6 is ID from roles table.

**Comment by davidhemphill** [comment]
You haven't described a bug and this isn't a place for us to fix your code for you. Please direct general questions to [#nova on Laravel's Discord](https://discordapp.com/invite/mPZNm7A) or [#nova on the Larachat Slack Channel](
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=2ahUKEwjRysvjyrfeAhWH6YMKHdIEAigQjBAwAXoECAUQCQ&url=https%3A%2F%2Flarachat.co%2Fslack&usg=AOvVaw0PUcouIq1UyHKjNmWeSnFq).

**Comment by msyadav88** [comment]
I have the same error " This User may not be associated with this resource" , when updating the staff resource having user selectbox, without changing the user.
Staff belongsTo user.
