### ISSUE TITLE
How can I add a new button with its functionality in the index?

### ISSUE THREAD

**Issue by DianaR19** [laravel/nova-issues#975]
I would like to add a new button in the index where I am dying a text and I took the id to which it belongs.

**Comment by 949mac** [comment]
How about adding an Action? https://nova.laravel.com/docs/1.0/actions/defining-actions.html#overview

Otherwise, look into a Resource Tool. https://nova.laravel.com/docs/1.0/customization/resource-tools.html#overview

**Comment by davidhemphill** [comment]
This is what actions are for.

There is also an undocumented `custom-index-toolbar` component you can override by creating a package like this: https://github.com/laravel/nova-issues/issues/451#issuecomment-434948432

**Comment by parth-ka-patel** [comment]
i used this custom-index-toolbar in laravel nova 4 and laravel 8.75 but button not visible so can any one please give alternative solution ?
