### ISSUE TITLE
Relation Attribute not sortable

### ISSUE THREAD

**Issue by StanBarrows** [laravel/nova-issues#978]
- Laravel Version: 5.7.*
- Nova Version: 1.0.17
- PHP Version: 7.1.3

### Description:

Relation Attribute not sortable

### Steps To Reproduce:

```
Boolean::make('Verified Address', function () { return $this->addresses()->first()->verified; })
                ->sortable(),

 Boolean::make('Verified E-Mail', 'email_verified')
                ->sortable(),
```

<img width="443" alt="image" src="https://user-images.githubusercontent.com/10268813/48505190-be212c80-e846-11e8-81d9-54cc4082d481.png">

**Comment by bonzai** [comment]
https://github.com/laravel/nova-issues/issues/178#issuecomment-422688946
