### ISSUE TITLE
Resources only as relations

### ISSUE THREAD

**Issue by alexjose** [laravel/nova-issues#98]
Nova is a great product with huge potential.

There should a way to hide se resources from appearing in the sidebar, but only as the relationship from any other parent resources.

For example I have a resource called Districts and I do not want to show this resource directly in the sidebar but only in the state detail view.

Thanks

**Comment by joselara** [comment]
You can, add to your resource. 

```
    public static function availableForNavigation(Request $request)
    {
        return false;
    }
```

**Comment by alexjose** [comment]
Thanks @joselara 

Just figured out, the following  will also help.

```php
public static $displayInNavigation = false;
```

**Comment by CitizenBeta** [comment]
What's the difference between availableForNavigation and displayInNavigation?

**Comment by Gummby** [comment]
availableForNavigation still lets me visit the resource in my admin panel. Not really sure what it does . displayInNavigation works though
