### ISSUE TITLE
How to display error message after observer prevent to delete row 

### ISSUE THREAD

**Issue by florianMaz** [laravel/nova-issues#981]
When i create or update a model Nova will provide a message like "The User was created".
I have an observer with deleting method which return false in some case, when that happend the row isn't delete. Now how can i display a message when that happend (observer return false and so the row is not delete) ?

My deleting method in observer observer :

/**

     * Handle the file space "deleting" event.
     *
     * @param  \App\FileSpace  $fileSpace
     * @return void
     */

    public function deleting(FileSpace $fileSpace) {

     // Some code
        
        return false;

    }

**Comment by florianMaz** [comment]
Thanks, It's works

**Comment by fede91it** [comment]
It seems the messages are displayed using Vue, so I don't think we can set the displaying of a message trough PHP. I'm wrong?

**Comment by fede91it** [comment]
Also for me. On production the exception message is not displayed

**Comment by lichtner** [comment]
@florianMaz what is your format of parameters you use for throwing validation exception? This doesn't work for me:

```php
public function creating(Model $model)
{
    throw ValidationException::withMessages([
       'message' => 'error message'
    ]);
}
```

**Comment by otrsw** [comment]
> Also for me. On production, the exception message is not displayed

@fede91it - did you ever resolve the issue you mentioned (production hiding the message)?  I understand why it's done, but for "known" exceptions I would expect the message to be shown?

**Comment by fede91it** [comment]
I'm not able to show ANY exception message in a production environment. All its fine in a dev env

**Comment by otrsw** [comment]
> I'm not able to show ANY exception message in a production environment. All its fine in a dev env

@fede91it I needed to throw a "resource wide" exception and have the message displayed in production as well.  I found the following workarround:

Declare a custom Exception and make sure you implement HttpExceptionInterface

    class CalculationException extends Exception implements HttpExceptionInterface
    
This will ensure Nova displays your exceptions getMessage() in the error toasty instead of the default "Server Error" even on production

**Comment by fede91it** [comment]
Can you provide an already implemented and working exception like you suggest?

**Comment by desaintflorent** [comment]
Thank's @otrsw for the beginning of solution. 
As I'm not very familiar with Exceptions, I had to search and try different solution to make It work. 
Here the solution I ended up with @fede91it. If somebody think I can improve, I'm happy to have feedback ! 

```php
use App\Exceptions\MyCustomException;
//[...]
public function updating(Model $model)
{
  throw new MyCustomException('Nova Error Message.');
}
```

```php
namespace App\Exceptions;
use Symfony\Component\HttpKernel\Exception\HttpExceptionInterface;

class MyCustomException extends \Exception implements HttpExceptionInterface 
{
    
    public function getStatusCode()
   {
       return 500;
   }

   /**
    * Returns response headers.
    *
    * @return array Response headers
    */
   public function getHeaders()
   {
       return [];
   }
}
```

**Comment by anditsung** [comment]
> Thank's @otrsw for the beginning of solution.
> As I'm not very familiar with Exceptions, I had to search and try different solution to make It work.
> Here the solution I ended up with @fede91it. If somebody think I can improve, I'm happy to have feedback !
> 
> ```
> use App\Exceptions\MyCustomException;
> //[...]
> public function updating(Model $model)
> {
>   throw new MyCustomException('Nova Error Message.');
> }
> ```
> 
> ```
> namespace App\Exceptions;
> use Symfony\Component\HttpKernel\Exception\HttpExceptionInterface;
> 
> class MyCustomException extends \Exception implements HttpExceptionInterface 
> {
>     
>     public function getStatusCode()
>    {
>        return 500;
>    }
> 
>    /**
>     * Returns response headers.
>     *
>     * @return array Response headers
>     */
>    public function getHeaders()
>    {
>        return [];
>    }
> }
> ```

can you change the default message from "There was a problem submitting the form" to something else?

cant find anything about this.

**Comment by f-liva** [comment]
This is definitely working, but I'd like to bring back the developers' attention here, because we shouldn't go down to this workaround to show our users an error message from the observers.

@davidhemphill @jbrooksuk @taylorotwell
