### ISSUE TITLE
Tool translations aren't forwarded to the front-end

### ISSUE THREAD

**Issue by blackfyre** [laravel/nova-issues#982]
- Laravel Version: 5.7.13
- Nova Version: 1.1.7
- PHP Version: 7.2.11

### Description:
As per Laravel 5.7 docs, I've added the translations to my tool, and in the blade templates / Tinker / ... it works fine. I've expected this to be added to the `Nova.config.translations` object automatically to be used with `__()`, but that's not the case, only the Nova translations are added there.  

The `Nova::provideToScript([])` doesn't help in extending already present translations with the new ones.

**Comment by blackfyre** [comment]
@maslauskas I've already tried very similar things...
```php
            Nova::provideToScript([
                'user' => $event->request->user()->toArray(),
                'permissions' => $event->request->user()->getAllPermissions()->pluck('name')->toArray(),
                'translations' => [
                    'proposal-items::' => __('proposal-editor::kpi')
                ],
            ]);
```

```php
Nova::$jsonVariables['translations']['proposal-items::'] =  __('proposal-editor::kpi');
```

But nothing seems to work...

**Comment by maslauskas** [comment]
Got it to work with this in component's boot method:

```
        /** @var Translator $translator */
        $translator = app('translator');
        $translator->load('*', '*', app()->getLocale());
        $lines = $translator->getFromJson('*');

        Nova::provideToScript([
            'translations' => $lines
        ]);
```

Basically just loading all translations again and providing them to frontend...

**Comment by blackfyre** [comment]
@maslauskas Still no dice... When I dump out the results of your snippet (`$lines`), I only get this:

```bash
 -------- ------------------------------------------------------------
  date     Thu, 15 Nov 2018 16:09:07 +0100
  source   ToolServiceProvider.php on line 36
  file     nova-components\my-resource-tool\src\ToolServiceProvider.php
 -------- ------------------------------------------------------------

"*"
```

**Comment by maslauskas** [comment]
Very strange. For me this little hack works as expected. Hopefully they add something to Nova that would load all component translations to frontend soon.

**Comment by blackfyre** [comment]
@maslauskas Still, this should be a core feature and not something that requires workarounds...

**Comment by blackfyre** [comment]
This is still an issue with Nova 1.2.1

**Comment by d3jn** [comment]
Nova provides translations to front using the following method:

```php
/**
 * Get the translation keys from file.
 *
 * @return array
 */
private static function getTranslations()
{
    $translationFile = resource_path('lang/vendor/nova/'.app()->getLocale().'.json');

    if (! is_readable($translationFile)) {
        return [];
    }

    return json_decode(file_get_contents($translationFile), true);
}
```

Meaning you need to place your translations inside published `resources/lang/vendor/nova` directory.

**Comment by davidhemphill** [comment]
Hey there! In order to keep this repository focused on bug reports, we auto-close feature requests and requests for help. Feel free to post your feature requests so others can discuss and add reactions. We'll keep an eye on them for later planning.
