### ISSUE TITLE
Nova Login - "Exception, Strange Message"

### ISSUE THREAD

**Issue by StanBarrows** [laravel/nova-issues#983]
- Laravel Version: 5.7.*
- Nova Version: 1.0.17
- PHP Version: 7.1.3

### Description:
![save_nova_bug](https://user-images.githubusercontent.com/10268813/48555282-0856ec00-e8e1-11e8-96b0-52e47f1bfd30.png)

### Steps To Reproduce:
I've nova included in an Laravel Application. Sometimes If Log-In to my application and then Login-In into Nov, Ii receive this nice "notification, error". After this error I can hit the refresh button two times and I get redirect to the Nova Dashboard.

**Comment by davidhemphill** [comment]
There seems to be an addon registered that is getting in the way.
