### ISSUE TITLE
There no need for `orchestra/database` for Testbench 3.6+

### ISSUE THREAD

**Issue by crynobone** [laravel/nova-issues#986]
I just bought a Nova license via company account and notice that it adds `orchestra/database` for dev requirement which is no longer needed for Testbench 3.6 and above. `--realpath` option is already available on Laravel core so we no longer need the deps.

**Comment by davidhemphill** [comment]
Just now getting around to this... 😳. If I remove the dependency and try to run the tests every one fails. Is there something specific I should know?

**Comment by crynobone** [comment]
![Screenshot_20190406-070804](https://user-images.githubusercontent.com/172966/55660821-cfd98f80-583a-11e9-8c15-e738358ebe4b.png)

Just remove any reference to `Orchestra\Database`. It should be just under one class.

**Comment by crynobone** [comment]
And `$this->artisan('migrate', ['--path' => realpath(...), '--realpath' => true]);`
