### ISSUE TITLE
Not possible to filter relatables depending of resource updated.

### ISSUE THREAD

**Issue by mathieutu** [laravel/nova-issues#988]
- Laravel Version: 5.7.13
- Nova Version: 1.1.7
- PHP Version: 7.2

### Description:
When fetching "relatable" to edit a resource, the url fetched is `nova-api/users/associatable/{relatable}?first=false&search=&withTrashed=false`. It does not contain the id of the resource updated, and so we can not filter theses relatable depending of the resource being updated (the `relatableQuery` method would allow to do that if only the id of the resource would be in the url !).

There are many cases where we need to filter them, and it will be a true problem. It's why I consider that as a bug.

I can show you severable examples if you need to.

**Comment by dwyer14** [comment]
Just discovered the `relatableResource` (eg, relatableUsers) method via a random Stackoverflow question today; is that documented anywhere? 

Regardless, would +1 this request. If the `viaResource` & `viaResourceId` parameters were included in the `relatable` query, that would be very useful, allowing for business logic filtering.

**Comment by RespectPick** [comment]
This is the worst bug!!! +1

**Comment by bjrnblm** [comment]
I agree that adding the`viaResource` & `viaResourceId` to the `associatable/{relatable}` call as parameters would solve a lot of large relations filtering problems.

@dwyer14 Does the `relatableResource` resolve this problem? Which stackoverflow post are you referring to?

**Comment by dwyer14** [comment]
@bjrnblm It definitely _works_, but only on hard-coded values, as in [the SO example](https://stackoverflow.com/a/53331931/1535999). That is, it does filter as expected...but without the `viaResource`/`viaResourceId` parameters, you're pretty limited on what you can accomplish with it.

**Comment by bjrnblm** [comment]
@dwyer14 Thanks, however I need variable filters not hardcoded. Hopefully this can be added to the relatable call in Nova soon.

**Comment by dwyer14** [comment]
@bjrnblm Yeah, same. That's why I felt those were needed; much more valuable for business logic, if you can filter dynamically. Hopefully we'll see this at some point. 🤞

**Comment by lucasromanojf** [comment]
I agree, this is necessary.

**Comment by zainmalonga** [comment]
@taylorotwell this is HUGE. How to access the resource being edited under relatabeQuery????.

**Comment by dp88** [comment]
I was able to get an instance of my model via its ID `$request->resourceId`.

In my Team Nova resource:
```php
public static function relatableUsers(NovaRequest $request, $query)
{
    $team = \App\Models\Team::find($request->resourceId);
    return $query->where('organization_id', $team->organization_id);
}
```

In my case, now only users belonging to the same organization as the team I'm inspecting will be available to add to that team.

**Comment by bartabel** [comment]
> I was able to get an instance of my model via its ID `$request->resourceId`.
> 
> In my Team Nova resource:
> 
> ```
> public static function relatableUsers(NovaRequest $request, $query)
> {
>     $team = \App\Models\Team::find($request->resourceId);
>     return $query->where('organization_id', $team->organization_id);
> }
> ```
> 
> In my case, now only users belonging to the same organization as the team I'm inspecting will be available to add to that team.

This only works for BelongsToMany relations, not for belongsTo relationships.

**Comment by jbrooksuk** [comment]
This issue relates to an unsupported version of Nova. If you're still experiencing this in the latest version of Nova, please open a new ticket, thanks!
