### ISSUE TITLE
Nova doesn't seem to like if an Eloquent Model has a property and a method with the same name

### ISSUE THREAD

**Issue by guru4vedi** [laravel/nova-issues#989]
- Laravel Version:5.6
- Nova Version: 1.1.7
- PHP Version: 7.2

### Description:
Nova throws a Undefined property while trying to Create/Update a resource.
Here is the [StackOverflow post](https://stackoverflow.com/questions/53329936/undefined-property-error-while-trying-to-create-a-new-resource/53331083#53331083).

### Steps To Reproduce:
Create a Nova resource for a Model that has an attribute and method with the same name.
Try to create new resource from Nova

**Comment by fbingha** [comment]
I've encountered this as well when trying to use a model from a package which has this design.

**Comment by leeovery** [comment]
Also seeing this error when having a method on the model with the same name as a property.

Running Laravel 5.7 and Nova v1.2.1.

**Comment by younus93** [comment]
Any update on how to get Nova to work around this?

**Comment by EdanBrooke** [comment]
I would also be interested in a solution.

**Comment by dkulyk** [comment]
This issue doesn't have relation for Laravel Nova.

Eloquent trying to find relation If your model doesn't have attribute. For prevent this behavior you need to declare default attribute value for model:
```php
property $attributes = [
    'bandwidth'=> 0,
];

function bandwidth()
{
    //do something
}
```
