### ISSUE TITLE
Whitelabeling ...

### ISSUE THREAD

**Issue by danrichards** [laravel/nova-issues#99]
Where is it? People are paying you for the tooling, the first thing they will want to do is make it their own and build something incredible.

Also, my boss doesn't want to explain to investors "What is Laravel Nova?" and either do I.

All snakiness aside, Laravel Nova is incredible, good job. 😄

**Comment by TheDeadCode** [comment]
If you read the terms of service, it’s actually against them to change the design and even the logo of Nova’s dashboard...

**Comment by davidhemphill** [comment]
The package publishes both the layout and the logo blade views, which you can customize for white-labeling purposes. You're also free to create a tool that modifies the app's CSS variables to match your desired branding.

**Comment by danrichards** [comment]
![horses-patoot](https://user-images.githubusercontent.com/470255/44566133-cf700680-a739-11e8-88ba-2f22dc79b8c0.gif)

**Comment by TheDeadCode** [comment]
Alright, I may have over-analyzed this:

> All copyright and proprietary notices and logos in the Control Panel and within the Software files must remain intact.

**Comment by AaronHolbrook** [comment]
@danrichards I figured out that you can override the blade files without having to resort to modifying the 'Nova' blade files.

If you create this directory structure in your main directory:

![](https://cl.ly/87b005b606b3/Image%202018-08-28%20at%202.49.22%20PM.png+)

It will use those before it uses the built in Nova blade files.

This means that you can copy/paste the entire `layout.blade.php` file and remove / modify whatever you want.

As to the legality, I don't have a clue. But I agree with @noahlocke about it being a deal breaker. This is an incredibly useful tool, but I'm starting to see some cracks if we're not going to be able to modify/adjust/configure some things about it. I can't have clients asking 'What is Laravel Nova?'.

**Comment by danrichards** [comment]
Yes @AaronHolbrook, that is the intended functionality of `php artisan nova:publish` 😄 

These assets propagate when you run the command so you can edit them. I hadn't noticed this when I originally created the issue.

I've also notice subsequent calls to the command do not clobber your changes to the files 👍

**Comment by noahlocke** [comment]
So, I emailed @taylorotwell and he did say they were planning to update that language in the terms, and that it's OK for us to modify. My guess is they'll get around to it after Laracon EU.

**Comment by AaronHolbrook** [comment]
Awesome @noahlocke - thanks for investigating!

I hope that they make it easier to configure small areas like that - I'd really prefer not to override the entire layout file just to remove 'Laravel Nova' and replace it with the site's name.
