### ISSUE TITLE
How do I create a Controller in a tool?

### ISSUE THREAD

**Issue by DianaR19** [laravel/nova-issues#990]
I would like to create a Controller to get a json. Supposedly it is created the same as in Laravel, but I already tried
`php artisan make: controller UserController`
and it marks me

> Could not open input file: artisan

How can I create my Controller in a Laravel Nova Tool?

**Comment by bonzai** [comment]
You have an extra space between `make:` and `controller`.

**Comment by cowzorized** [comment]
Hi Diana, creating a Controller has nothing to do with Nova specific. So my guess is you are in the Nova directory while trying the 'php artisan' command, which results in the error above. Make sure you navigate to your root directory of Laravel where the 'artisan' resides, and try the command again.

**Comment by ekandreas** [comment]
Just place a class extended with Controller in your Nova tool folder under http/controllers. Put the full path to the class in routing and you are good to go.

**Comment by davidhemphill** [comment]
Artisan commands can only be run from the root of your project (where the artisan binary is). Running it inside your tool folder will not work. You can create a controller using Artisan and move it into your tool's `src` directory, but you'll also have to change the namespace to match your tool's.

**Comment by DianaR19** [comment]
I have the following code in my controller

```
<?php

namespace App\Http\Controllers;

use App\Models\User;

class ExampleController extends Controller
{
    public function getUsers(){
        $user = User::all();
        return $user;
    }
}
```
this is found in 

> node-components / ExampleTool / src / Http / Controllers / ExampleController.php

But it shows me the following error

![image](https://user-images.githubusercontent.com/35699310/48807081-08405d00-ece2-11e8-8882-e84b891bda5e.png)

@davidhemphill @ekandreas @cowzorized

**Comment by ekandreas** [comment]
Can you show the route?

**Comment by abdessamadelhamdany** [comment]
Try using the namespace of the controller, or maybe import it and use the array notation

**Comment by ryanmillergm** [comment]
Also, Check in your src/ToolServiceProvider to make sure your route prefix is the same:

```
    protected function routes()
    {
        if ($this->app->routesAreCached()) {
            return;
        }

        Route::middleware(['nova', Authorize::class])
                ->prefix('nova-vendor/survey-manager')
                ->group(__DIR__.'/../routes/api.php');
    }
```

as your request in components/Surveys.vue:

```
fetchSurveys() {
        return Nova.request().get('/nova-vendor/survey-manager/surveys').then(response => {
            this.surveys = response.data;
            console.log(response.data);
        });
    },
```

and in routes/api.php:

```
Route::get('/surveys', '\Cfan\SurveyManager\Http\Controllers\SurveysController@index');
```

In src/Http/Controllers:

```
<?php

namespace Cfan\SurveyManager\Http\Controllers;

use Cfan\Api\Models\Survey;
use App\Http\Controllers\Controller;

class SurveysController extends Controller
{
    public function index(){
        $surveys = Survey::all();
        return $surveys;
    }
}
```

Obviously, this is an example and you will have to change paths and namespaces like mentioned in previous comments. Hope this helps someone and gives a good example!
