### ISSUE TITLE
BelongsTo relationships do not work with custom relation name / foreign key

### ISSUE THREAD

**Issue by adriandmitroca** [laravel/nova-issues#991]
- Laravel Version: 5.7.13
- Nova Version: 1.1.7
- PHP Version: 7.2

### Description:

Relationships seem to be completely broken when you don't have a default configuration for them.

### Steps To Reproduce:

Nova Resource (fields method)
```
BelongsTo::make('Customer',  'customer',  'App\Nova\User'),
```

Model:
```
public function customer()
{
   return $this->belongsTo(User::class);
}
```

Result:
`Class name must be a valid object or string.`

Things would work just fine if I'd have user() relationship within my model altogether with `user_id` foreign key in the model. Unfortunately, it seems that renaming relationship to `user` and setting foreign key explicitly isn't enough as it still fails most likely because of having a custom foreign key.

**Comment by bonzai** [comment]
https://nova.laravel.com/docs/1.0/resources/relationships.html#belongsto

> Customizing Resource Classes

> You can customize the resource class used by the relation field by setting the second and third parameters of the make method:

```php
BelongsTo::make('Author', 'author', 'App\Nova\User');
```

**Comment by adriandmitroca** [comment]
Oops, I've entirely missed this part of documentation - however - the original issue seems to be still present.

**Comment by bonzai** [comment]
Can you paste your code here (resource and model)?

Also, the full stack trace would be helpful.

**Comment by adriandmitroca** [comment]
I've just found out that this issue is not related with Nova, it is conflict of some kind with [tightenco/parental](https://github.com/tightenco/parental/) package.

Most likely related with https://github.com/tightenco/parental/issues/20.

Thanks for your assist though.
