### ISSUE TITLE
Custom Card with the name `Table` doesn't show up in the dashboard

### ISSUE THREAD

**Issue by Fawzanm** [laravel/nova-issues#992]
- Laravel Version: 5.7.*
- Nova Version: 1.1.7
- PHP Version: 7.2.11

### Description:
I tried to create a custom Card resource with the name Table. 

```php artisan nova:card foo/table```

Everything went smooth but the card resource `Table` doesn't show up in the Dashboard after adding it  to the NovaSerivceProvider. 

I followed the same steps with a different name and it worked. 

```php artisan nova:card foo/table-card```

### Steps To Reproduce:

```php artisan nova:card foo/table```
Add `new \Foo\Table` to the `NovaServieProvider` files `cards()` method.

**Comment by bonzai** [comment]
It won't work because:

> [Vue warn]: Do not use built-in or reserved HTML elements as component id: table

**Comment by Fawzanm** [comment]
Come on.. I feel like I am brain dead!!
