### ISSUE TITLE
Trix keydown `/`

### ISSUE THREAD

**Issue by tiagocyberduck** [laravel/nova-issues#998]
- Laravel Version: 5.7.12
- Nova Version: 1.1.7
- PHP Version: 7.1

### Description:
If we are trying to enter `/` into it, it goes to the global search.

### Steps To Reproduce:
Type `/` on the trix field

**Comment by dwyer14** [comment]
Odd. Are you sure you're using v1.1.7 for Nova? That bug was fixed in v1.1.0, and is a non-issue in my project, running v1.1.7.

**Comment by davidhemphill** [comment]
Make sure you're using you're actually using the latest version. If you can find a situation that helps us reproduce this (Nova version, browser, more steps, etc), we'll take another look.
